### ISSUE TITLE
Provide an option to set default email app.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1005]
### Description: 
From https://community.brave.com/t/external-mail-application-specified/50611

Firefox has this functionality.

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by hennrynusasatria** [comment]
I think this issue is not required anymore, since iOS now allow third-party browser and third-party e-mail application to be the default application.
