### ISSUE TITLE
Add YouTube / Video Playback Controls

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#1006]
### Description: 

It would be great to add more advanced controls to youtube or general videos (if possible). Main thing would be speed controls by injecting a script to add this.

### Steps to Reproduce 
  1. Visit YT
  2. Under a settings icon or somewhere else in the UI add an option to adjust video playback

**Actual result:** 
NA

**Expected result:**
NA

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
NA

**Brave Version:** 
NA

**Device details:** 
NA

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Playback options are available in playlists feature
https://github.com/brave/brave-ios/issues/3368
