### ISSUE TITLE
Open in a link in a new Tap doesn‘t work anymore in private windows. Since iOS 12.2

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1008]
### Description: 

A user reports that since 12.2, long pressing a link in a private window and pressing Open doesn't work.

We are supposed to have “Open In New Tab”/“Open In New Private Tab”/etc.
But Apple’s Open/Add to Reading List/Copy/Share… comes up

![12 2](https://user-images.githubusercontent.com/7606853/55091067-6654c680-506d-11e9-8fee-00df1b34d817.gif)

### Steps to Reproduce 
  1.Long press on a URL in private mode

**Brave Version:** 
1.9

**Device details:** 
iPhone xs

**Comment by jhreis** [comment]
https://github.com/mozilla-mobile/firefox-ios/pull/4617

**Comment by cndouglas** [comment]
Duplicate of #830.

**Comment by jamesmudgett** [comment]
Could we please add ```nativeLongPressRecognizer.minimumPressDuration = 0.2```

**Comment by jhreis** [comment]
Closing as duplicate per https://github.com/brave/brave-ios/issues/1008#issuecomment-477239805
