### ISSUE TITLE
Unit Tests: CoreData

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#101]
## Files:
>incomplete

**CoreDataStackTests**

- [ ] testWorkerToMainMerge
- [ ] testMainToWorkerMerge
- [ ] testSaveContext

**CD Utilities:**

- [ ] compareContexts // will validate that both new workerContext, and mainContext have same data

**Comment by iccub** [comment]
I added unit tests of all core data model class in this ticket(except `sync` classes)
