### ISSUE TITLE
brave crashes when attempting to sync into a folder that's opened

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#1010]
### Description:

When you're attempting to move a folder from another device into a folder that iOS has opened, the browser will crash once a sync occurs. It will result in the following crash:

* Crash Stack from Xcode --> [stack.txt](https://github.com/brave/brave-ios/files/3018505/stack.txt)

![Screen Shot 2019-03-28 at 2 59 44 AM](https://user-images.githubusercontent.com/2602313/55137913-97360980-5108-11e9-9b2c-59b93564e850.png)

### Steps to Reproduce 

@btlechowski thank you for narrowing down the STR and proving the following STR:

1. Clean install on desktop
2. import the following bookmarks under desktop [randomBookmarks.txt](https://github.com/brave/brave-ios/files/3016588/randomBookmarks.txt) <-- rename to `.html`
3. Create a new sync chain on desktop once the above bookmarks have been imported
4. Clean install Brave on iPhone/iPad
5. Join the sync chain that you created on the desktop with the iOS device
6. Wait for sync to complete on both devices
7. On iPhone: Open `Sports` folder in bookmarks and keep it open (prevent the phone from locking etc)
8. On Desktop: Move `Games` bookmark folder to `Sports`
9. On iPhone: Wait for sync while keeping `Sports` folder open

**Note: The key is to keep bookmark folder open on iOS when syncing**

**Actual result:** 

* Crashes with the following Stack from Xcode --> [stack.txt](https://github.com/brave/brave-ios/files/3018509/stack.txt)

**Expected result:**

Application shouldn't be crashing

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible when using the above STR

**Brave Version:** 

* `1.9 (19.03.27.19)`
* `1.9 (1.2.3.4)` (Xcode from source)

```
Kamils-MBP:brave-ios kjozwiak$ git log -1
commit e9fe96e7c4ffd81236b41e302552609a87270ac0 (HEAD -> development, tag: v1.9, origin/development, origin/HEAD)
Merge: 829037e0 b6dac8bc
Author: Michał Buczek <michal.buczek@protonmail.com>
Date:   Wed Mar 27 20:15:04 2019 +0100

    Merge pull request #1009 from brave/update_beta_icons

    No Bug: Update beta icons
```

**Device details:** 

* `iPad Mini 4` running `iOS 12.1.4`
* `iPhone XR` running `12.1 (16B91)` using Xcode emulator

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information

@btlechowski & @LaurenWags have also reproduced this on their devices.

**Comment by srirambv** [comment]
Able to reproduce crash when root bookmark folder is still open on iOS device. 
1. import bookmark on desktop dont move anything
2. create sync chain on desktop
3. add iphone to sync chain and wait for sync to complete on iphone
4. add ipad to sync chain by scanning qr code on iphone and wait for bookmarks to sync
5. keep bookmark hanger at root level open on both iphone and ipad
6. move sport and social into gaming on desktop 
7. wait for sync to happen on both iphone and ipad, crashes on both ios devices

**Comment by kjozwiak** [comment]
Reproduced using @srirambv STR above as well.

* Crash Stack --> [stack.txt](https://github.com/brave/brave-ios/files/3019167/stack.txt)

Similar error to before @iccub:

```
CoreData: error: NSFetchedResultsController: no object at index 4 in section at index 0
```

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+/ iPad Pro. Verified steps from https://github.com/brave/brave-ios/issues/1010#issuecomment-477670593 worked and no crash.
* Verification **PASSED** on `iPad Mini 4` using `1.9 (19.03.29.14)`
  * Went through the original STR outlined under https://github.com/brave/brave-ios/issues/1010#issue-426337618 & https://github.com/brave/brave-ios/issues/1010#issuecomment-477670593
  * Went through several different combinations of embedded folders and never received the crash
* Verification passed on iPhone 8. Verified steps from original STR outlined under https://github.com/brave/brave-ios/issues/1010#issue-426337618 and https://github.com/brave/brave-ios/issues/1010#issuecomment-477670593 worked and no crash.
* Verification passed on iPad 5th Gen. Verified steps from original STR outlined under https://github.com/brave/brave-ios/issues/1010#issue-426337618 and https://github.com/brave/brave-ios/issues/1010#issuecomment-477670593 worked and no crash.
* Verification passed on iPhone SE Verified steps from original STR outlined under https://github.com/brave/brave-ios/issues/1010#issue-426337618 and https://github.com/brave/brave-ios/issues/1010#issuecomment-477670593 worked and no crash.
