### ISSUE TITLE
Add Setting Item to Share Brave

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1012]
### Description: 
Add the ability to share Brave in the settings

**Comment by jhreis** [comment]
@anthonypkeane How would this work? Like copy a link to clipboard? Open the share sheet?

**Comment by anthonypkeane** [comment]
> @anthonypkeane How would this work? Like copy a link to clipboard? Open the share sheet?

We place a menu item in settings to Share Brave. Pressing that will either:

1) opens a new screen (or modal) with a nice design and have a share button that opens the share sheet. 

_or_

2) directly open the share sheet

We'll populate the text in the share text and provide a URL for people to download the app.

**Comment by kylehickinson** [comment]
@anthonypkeane is this necessary now that iOS default long-press action in iOS 13 includes a share button? 
![IMG_632C92CB7127-1](https://user-images.githubusercontent.com/529104/68985975-d2e12900-07e8-11ea-8432-c7e13ce35eca.jpeg)

**Comment by iccub** [comment]
Let's close, as Kyle said we get this for free in iOS 13
Reopen if you insist on having this in Brave settings
