### ISSUE TITLE
Bring back `Find in page` via url bar

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1019]
We had this feature in Brave 1.6 and removed it by accident while moving onto 1.7 codebase.

**Comment by anthonypkeane** [comment]
https://github.com/brave/brave-ios/issues/868 should sort it
LMK if not

**Comment by LaurenWags** [comment]
* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.12.14)
   - Navigated to a page, tapped on URL bar, typed text into URL bar and saw 'On this page' in drop down and the option to 'Find' my text. Finding my text worked as expected. Selecting 'Cancel' returned me to my page as expected.

![IMG_554399E7AFFA-1](https://user-images.githubusercontent.com/28145373/61157628-b0e73b00-a4c4-11e9-8dbf-0ea92c3eaa5b.jpeg)

* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`
  * ensured that typing into the URL while your on a page displays `On this page`
  * ensured that taping on your text under `On this page` finds the correct text and the correct results
  * ensured that `Find` feature works as expected when using it via `On this page`

![IMG_9786](https://user-images.githubusercontent.com/2602313/61467096-0d28df80-a949-11e9-9597-7ae860bd7d62.PNG)

**Comment by kjozwiak** [comment]
@anthonypkeane @EyanGoldman as this is a design/UX issue, can you guys go through this on an `iPhone X`? If you've already been dog fooding and feel comfortable with the new design/functionality, can either of you please add the `QA Pass - iPhone X` label? Thanks!
