### ISSUE TITLE
Browser crash when updated to 1.9(19.3.29.16)

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1020]
### Description: 
While testing the release build 1.9(19.03.29.16), QA found a lot of random crashes when opening backgrounded tabs/opening new tabs. Needs to be investigated

**Comment by jhreis** [comment]
Just to note, this is not in production, and was only present in beta versions.

**Comment by iccub** [comment]
Hopefully will get fixed by https://github.com/brave/brave-ios/pull/1018

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+ running 1.9.1(19.04.02.12)
  - Verified no crash on upgrade from 1.9(19.03.29.14)
  - Verified upon upgrade switching to unloaded tabs doesn't crash
  - Verified keeping a page open for a bit and then opening a new tab doesn't crash
  - Verified no data loss from upgrade

* Verification passed on iPad Pro running 1.9.1(19.04.02.12)
  - Verified no crash on upgrade from 1.9(19.03.29.14)
  - Verified upon upgrade switching to unloaded tabs doesn't crash
  - Verified keeping a page open for a bit and then opening a new tab doesn't crash
  - Verified no data loss from upgrade

* Verification passed on iPad 5th Gen running 1.9.1(19.04.02.12)
  - Verified no crash on upgrade from 1.9(19.03.29.14)
  - Verified upon upgrade switching to unloaded tabs doesn't crash
  - Verified keeping a page open for a bit and then opening a new tab doesn't crash
  - Verified no data loss from upgrade. Specific upgrade scenario performed: with 1.9 from app store: added bookmarks, history, tabs, stats, cookie, logins/passwords, site specific shield settings, added custom sites to ‘favorites/top site tiles’. Also set default search engine to DDG for Normal and Private tabs. Then updated using 1.9.1 ipa file. Verified version change (1.9 -> 1.9.1) and the following were retained: bookmarks, history, tabs, stats, cookie, login/password, site specific shield settings, custom sites in ‘favorites/top site tiles’, search engine setting. Active Tab was not maintained (this is a known issue https://github.com/brave/brave-ios/issues/736). Also doing some navigation, verified no crashes observed.

* Verification passed on iPhone 8 running 1.9.1(19.04.02.12)
  - Verified no crash on upgrade from 1.9(19.03.29.14)
  - Verified upon upgrade switching to unloaded tabs doesn't crash
  - Verified keeping a page open for a bit and then opening a new tab doesn't crash
  - Verified no data loss from upgrade
