### ISSUE TITLE
Non-referral downloads should use generic refcode - iOS

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1022]
## Description 

All Brave browsers should add a universal "default" Brave refcode into the user profile at first run time (if not already present from a referral download/installation process) and act from that moment forward exactly as any referred download would act.

Desktop Link: https://github.com/brave/brave-browser/issues/2547

**Comment by jhreis** [comment]
What is the ref code desired here, is it hardcoded?

**Comment by srirambv** [comment]
Desktop currently uses `BRV001` for non-referral downloads. 

cc: @bbondy

**Comment by mandar-brave** [comment]
@aekeus please comment
are we tracking iOS organic differently than rest; we should.

**Comment by aekeus** [comment]
iOS is reporting generic referral installs to the 'none' ref code from what I can see on stats.

**Comment by jhreis** [comment]
@mandar-brave is this desired? If not, please advise.

**Comment by mandar-brave** [comment]
Yes @jhreis - we track organics and since platforms are already filtered, none makes sense!

**Comment by jhreis** [comment]
Sounds, closing then as behavior is already correct. Thanks for clarification 😄
