### ISSUE TITLE
Pinch to Zoom not working correctly on all sites

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1023]
### Description: 
Pitch to Zoom doesn't work reliably. On sites like wikipedia it works, but not on https://www.homedepot.com/

### Steps to Reproduce 
  1. Open Brave and navigate to https://www.homedepot.com/
  2. Try Pitch to Zoom

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.9

**Device details:** 
iPhone Xs

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+ (iOS 12.3.1) running 1.10(19.07.08.19)
  - Verified able to pinch-zoom on all pages including pdf files and images 
  - Verified navigating back retains the zoom level on the previous page 

* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.12.14)
  - Verified able to pinch-zoom on all pages including pdf files and images 
  - Verified navigating back retains the zoom level on the previous page
