### ISSUE TITLE
Implement 'Bookmark all tabs' feature

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ios#1029]
### Description: 
For parity with desktop, an option to bookmark all open tabs. This option would allow you to specify a folder in which each opened tab will be bookmarked.

Users would like the ability to sync _opened tabs_ between devices. That would require a bit more work; bookmarking all opened tabs (and opening tabs for all bookmarks in a folder) would allow us to offer a minimal-friction work-around until a more complete solution is available.

**Comment by Poopooracoocoo** [comment]
When I installed Brave I realised only after opening a ton of tabs that you can't tap and hold on the bookmarks button to bookmark all tabs like you can in Safari. I don't think you can even search tabs.

**Comment by Poopooracoocoo** [comment]
issue for android: https://github.com/brave/brave-browser/issues/9443

**Comment by Poopooracoocoo** [comment]
pssst @kylehickinson :)

**Comment by thatsofia** [comment]
Any updates on this?

**Comment by joeyfigaro** [comment]
Would love support for this.

**Comment by Poopooracoocoo** [comment]
@joeyfigaro make sure you've starred the Chromium issues! There's multiple. A bunch of people have tried getting Google to implement this.

**Comment by soner-yuksel** [comment]
Closing this Feature Request since an issue with details and a PR is created.

https://github.com/brave/brave-ios/pull/4133
