### ISSUE TITLE
Unit Tests: Favorites (e.g. Top Sites)

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#103]
## Files:

**FavoriteTests**

- [ ] testInitFavorites
- [ ] testAddFavorite
- [ ] testEditFavoriteURL
- [ ] testEditFavoriteName
- [ ] testDeleteFavorite
- [ ] testMoveToEnd // Should have 3+ favorites, and move a fav to the end, this will protect against out of bounds
- [ ] testMoveEndToStart // Have 3+ favs, move last item to the front
- [ ] testMoveToMiddle // Have 4+ favs and move a middle fav to another middle position

**Utilities**

- [ ] seedFavorites // Adds 4+ favorites into the favorites table
- [ ] checkOrder // Given some array of favs, it will validate that this is the order items are stored in

**Comment by tmancey** [comment]
Unassigning ticket as agreed with Michal that this ticket can be picked up by any developer
