### ISSUE TITLE
Favicon not showing, using fallback when it should not

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1030]
See videos and STR here https://community.brave.com/t/favicon-problem/51360/10

**Comment by danishjafri88** [comment]
This is fixed in https://github.com/brave/brave-ios/pull/983. Fixed by setting priority to fetch icons from specific <link> tags. Also fixed the logic around it.

**Comment by srirambv** [comment]
Verification passed on iphone XR with iOS 13.5 running 1.18(20.06.24.15)
- Verified favicon is shown when available
- Verified fallback icon is used when favicon is not available
------------
Verification passed on iPhone 7+ with iOS 13.5.1 running 1.18(20.06.24.15)
- Verified favicon is shown when available
- Verified fallback icon is used when favicon is not available
------------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.18(20.06.24.15)
- Verified favicon is shown when available
- Verified fallback icon is used when favicon is not available
------------
Verification passed on iPad Pro with iOS 13.6 running 1.18(20.06.24.15)
- Verified favicon is shown when available
- Verified fallback icon is used when favicon is not available
------------
Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.06.24.15)
- Verified favicon is shown when available
- Verified fallback icon is used when favicon is not available
------------
