### ISSUE TITLE
Require user permissions before using accelerometer api

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1031]
### Steps to Reproduce 
  1. Navigate to http://www.albertosarullo.com/demos/accelerometer/

**Actual result:** 
Accelerometer is accessed without user permissions

**Expected result:**
Access to accelerometer api should request user permissions

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.9.1

**Device details:** 
iPhone SE

**Comment by jumde** [comment]
It would also be good to allow this api only for secure domains.

**Comment by iccub** [comment]
Also: research other data that a website can ask from a mobile device cc @danishjafri88

**Comment by ShivanKaul** [comment]
Looks like this was fixed by Apple in iOS 13: https://www.macrumors.com/2019/02/04/ios-12-2-safari-motion-orientation-access-toggle/. I can't repro on the test website in the issue and https://accelerometerdemo.netlify.app/ only works if permissions are granted. Closing
