### ISSUE TITLE
Issue with sharing sites

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1032]
### Description: 
When sharing a site, the correct URL is sometimes not being shared. 
Twitter works fine, but Amazon does not

### Steps to Reproduce 
  1. Open Brave, navigate to amazon.com
  2. Open the share sheet
  3. Try to email the link

https://bravesoftware.slack.com/files/UCLMABWMS/FHRLFFDFY/rpreplay_final1554501784.mp4

**Actual result:** 
The URL is file:///private/var/mobile/Containers/Data/Application/8610FA20-BF86-460D-BE92-474FF05BCBB2/tmp/TempDocs/rb.txt

**Expected result:**
www.amazon.com

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy on Amazon

**Brave Version:** 
1.9.1

**Device details:** 
Xs on 12.2

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 
No

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 running 1.12(19.09.05.20)
* Verified selecting email via share sheet shows the correct title of the product page
![image](https://user-images.githubusercontent.com/17010094/64432749-24539600-d08b-11e9-8450-0e2bdb7314d8.png)

Verification **PASSED** on `iPad Air 3rd Generation` using `iOS 13.1` running `1.12 (19.09.11.22)`:

![IMG_0058](https://user-images.githubusercontent.com/2602313/64751703-ff2bb100-d4ea-11e9-9d2e-4a14b88c3f29.PNG)
![IMG_0057](https://user-images.githubusercontent.com/2602313/64751705-ff2bb100-d4ea-11e9-89a0-6757380af8d8.PNG)
![IMG_0060](https://user-images.githubusercontent.com/2602313/64751912-c6400c00-d4eb-11e9-9452-c1802e57a14b.PNG)
![IMG_0059](https://user-images.githubusercontent.com/2602313/64751913-c6400c00-d4eb-11e9-8d7a-3bca9f64b0b5.PNG)

Verification **PASSED** on `iPhone 6s+` using `iOS 12.4.1` running `1.12 (19.09.13.06)`:

![IMG_9910](https://user-images.githubusercontent.com/2602313/64883244-edeabd80-d62c-11e9-95e7-796d7ba8865b.PNG)
![IMG_9909](https://user-images.githubusercontent.com/2602313/64883246-ee835400-d62c-11e9-9354-2b516089647e.PNG)
