### ISSUE TITLE
URP Beta Endpoint Change

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#1033]
### Description: 

User Referral Promo endpoint for beta builds points to Staging. Additionally, the shortened timeouts only impact development builds, both of these should be changed.

- [ ] beta app should point to production URP endpoint
- [ ] beta app should have shortened timeouts / time limits

### Steps to Reproduce 
  1. In beta app, go into settings
  2. At bottom under "DEBUG" menu, select "View URP Logs"
  3. Top line should show the endpoint URL, this should be a non-staging endpoint

**Comment by LaurenWags** [comment]
* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.12.14). Verified STR from description.
* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`
  * `URP init, host: https://laptop-updates.brave.com` (expected & not a staging link)
