### ISSUE TITLE
Add the ability to allow user to increase the font size of a webpage

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1037]
### Description: 
I see a lot users pitching to zoom to make the text on the screen bigger. 

Independently from the iPhone settings we should have a setting to make the text in the browser bigger. 

@jamesmudgett can you help figure out this one?

**Comment by anthonypkeane** [comment]
internal chat about this here: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1556992923016100

**Comment by anthonypkeane** [comment]
Coming to Safari in iOS13

**Comment by anthonypkeane** [comment]
Linked to https://github.com/brave/brave-ios/issues/1344

**Comment by iccub** [comment]
I will close this in favor of https://github.com/brave/brave-ios/issues/3222
^ this is for website font size

For UI font size there is https://github.com/brave/brave-ios/issues/1344
