### ISSUE TITLE
Unit Tests: Tab/TabManager

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#104]
## Files:

**TabTests**
Definitely would benefit from UI tests, but still something we can unit test.

- [ ] testInitialTab
- [ ] testCloseOnlyTab
- [ ] testNewTab
- [ ] testMoveToEnd // Should have 3+ tabs, and move a tab to the end, this will protect against out of bounds
- [ ] testMoveEndToStart // Have 3+ tabs, move last item to the front
- [ ] testMoveToMiddle // Have 4+ tabs and move a middle tab to another middle position
- [ ] testCloseAllTabs

**Comment by tmancey** [comment]
Unassigning ticket as agreed with Michal that this ticket can be picked up by any developer
