### ISSUE TITLE
App won’t start on IPad Air 2 after 1.9 and later

### ISSUE THREAD

**Issue by Jacalz** [brave/brave-ios#1040]
### Description: 
When updating to 1.9 I noticed that the app just wouldn’t want to start on my iPad Air 2 and 1.9.1 did no difference. It just starts a white screen and nothing more pops up. I have tried reinstalling the app two time. One time on 1.9 and one time on 1.9.1.

### Steps to Reproduce 
  1. Download Brave on IPad Air 2
  2. Try to start it

**Actual result:** 
Not much more than a black screen...

**Expected result:**
Fully functioning and useful.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100% after update to 1.9

**Brave Version:** 
Can get exact version since the app won’t start, but it’s past 1.9

**Device details:** 
iPad Air 2 on IOS 12.2.0

**Comment by Jacalz** [comment]
The latest update of Brave did NOT fix the app and it still just crashes after a couple of seconds. Please reopen!

**Comment by iccub** [comment]
Verification passed on my iPad Air 2

**Comment by EyanGoldman** [comment]
Double confirmed on an iPad Air 2 (iOS 13 Beta)

**Comment by kjozwiak** [comment]
Awesome, thanks @iccub & @EyanGoldman 👍
