### ISSUE TITLE
Add a mechanism to auto update eTLD dat file before release

### ISSUE THREAD

**Issue by danishjafri88** [brave/brave-ios#1042]
### Description: 
- Currently, we use our own implementation to retrieve the eTLD from a URL and we include a possibly outdated eTLD file. We should take advantage of Brave-Core's implementation to receive `domainAndRegistry`, and to automatically get fetch the new file which is generated in Brave-Core at compile time.

### Solution:
- Use the `domainAndRegistry` function from Brave-Core to retrieve eTLD.

**Comment by jhreis** [comment]
Related: https://github.com/brave/brave-ios/issues/838

**Comment by diracdeltas** [comment]
@iccub @anthonypkeane this is actually a security issue that this list hasn't been updated in years. could we get it prioritized? cc @pes10k

**Comment by iccub** [comment]
Talked with Pete.
We will start updating this list before every release and we will modernize our algorithm since it is stale as well

**Comment by iccub** [comment]
Updated ticket description, we will reuse chromium libs for that,
we did not manage to fix everything in time for 1.37 so for 1.37 we only update the .dat file we already have.
Ticket for it is here https://github.com/brave/brave-ios/issues/5113

This ticket will be resolved in Brave 1.38

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 15.5 Beta 3 running 1.38 (22.4.29.16)
- Verified test plan from [#5239](https://github.com/brave/brave-ios/pull/5239)
- Verified shields on various domains from the `public_suffix_list`
- Verified shields retain the site specific settings on session restore
- Verified favicons shows when available but fallbacks on to the generic letter when favicon isn't fetched
- Verified printer abuse test worked as expected
- Verified domains are correctly shown on menu above share menu
- Verified sharing URL works fine, entire URL is shared from share menu
----------
Verification passed on iPhone XR with iOS 15.4.1 running 1.38 (22.4.29.16)
- Verified test plan from [#5239](https://github.com/brave/brave-ios/pull/5239)
- Verified shields on various domains from the `public_suffix_list`
- Verified shields retain the site specific settings on session restore
- Verified favicons shows when available but fallbacks on to the generic letter when favicon isn't fetched
- Verified printer abuse test worked as expected
- Verified domains are correctly shown on menu above share menu
- Verified sharing URL works fine, entire URL is shared from share menu
----------
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.38 (22.4.29.16)
- Verified test plan from [#5239](https://github.com/brave/brave-ios/pull/5239)
- Verified shields on various domains from the `public_suffix_list`
- Verified shields retain the site specific settings on session restore
- Verified favicons shows when available but fallbacks on to the generic letter when favicon isn't fetched
- Verified printer abuse test worked as expected
- Verified domains are correctly shown on menu above share menu
- Verified sharing URL works fine, entire URL is shared from share menu
----------
Encountered  #5311, #5312
