### ISSUE TITLE
Add shake to reopen closed Tab screen

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1048]
### Description: 
Feedback from users that they accidentally swiped on tabs and closed them.

We should add shake to undo here so users can get them back.

![IMG_B3A3F280FEF9-1.jpeg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/a19b562b-52ef-46fd-a6fa-d5b907b6ebc1)

**Comment by iccub** [comment]
Another ideas:

For iPad we can add a shortcut for it like CMD+SHIFT+T, 
for iPhones perhaps a new long tap action on the tabs button

**Comment by kylehickinson** [comment]
Closing in favour of #2123 which can include shake-to-undo

**Comment by soner-yuksel** [comment]
Opening this so we can test the Shake to open Recently Closed Tab the functionality on Tab Tray.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12`, `iPad (9th Gen)` running `iOS 16.2`, `iPadOS 15.6.1` respectively using version `1.48 (23.2.13.20)`

- Ensured that shaking device after closing tab in tab view will prompt the user whether they want to restore that tab.
- Ensured Tab is restored when tapping on `Open`
- Ensured user is able to re-open tab view and shake to reopen tab

<table><tr><td>iPhone</td><td>iPad</td></tr>

<tr><td>

https://user-images.githubusercontent.com/17885425/218850671-0cdc155b-72fe-4ba7-a4f1-60fba837dfa7.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/218850650-557e1bee-93d2-4cc0-8850-f1830ce01755.mov

</td></tr></table
