### ISSUE TITLE
Add the ability to inform and notify users of new features

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1049]
### Description: 
Only a small fraction of our users read the release notes.
Case and point, we are getting reviews and feedback from users asking where Sync is today. V1.9 introduced Sync 2 weeks ago.

We need to display a modal as we do for DDG when private mode is enabled for the first time. 

This "new feature modal" will only be used for big / interesting / cool features, like Sync, Background video etc.

@jamesmudgett can you please provide the UI

@jhreis we'll need to figure out how we localize this screen and how we delete the old text and localizations when no longer needed so that .strings files doesn't balloon.

**Comment by iccub** [comment]
Duplicate of https://github.com/brave/brave-ios/issues/934
