### ISSUE TITLE
Numerous access control warnings for public extensions

### ISSUE THREAD

**Issue by cndouglas** [brave/brave-ios#1051]
### Description:
After updating to Xcode 10.2, there are new warnings about access control for public extensions. For example, in BraveStrings.swift, every string property has the following warning:
> 'public' modifier is redundant for static property declared in a public extension

![](https://user-images.githubusercontent.com/19424103/56052199-6a900d80-5d16-11e9-81ff-95cf432d5807.png)

This is clogging up not only the warnings in Xcode but also the warnings in the CI.

According to https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html:
> Alternatively, you can mark an extension with an explicit access-level modifier (for example, private extension) to set a new default access level for all members defined within the extension. This new default can still be overridden within the extension for individual type members.

Because these extensions are marked public, there is no need to mark each of the extension's properties and functions public. So these modifiers should be removed, as suggested by the compiler.

**Comment by kylehickinson** [comment]
Already fixed in #1004 :)

**Comment by cndouglas** [comment]
> kylehickinson committed an hour ago

What a coincidence. 😃
