### ISSUE TITLE
Implement DeviceCheck

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1052]
### Description: 
Implement DeviceCheck for upcoming Brave Rewards on iOS
https://developer.apple.com/documentation/devicecheck

**Comment by kylehickinson** [comment]
@anthonypkeane This ticket should probably be transferred to [brave-rewards-ios](https://github.com/brave/brave-rewards-ios) as that is where the grants will take place

**Comment by jhreis** [comment]
Issue moved to [brave/brave-rewards-ios #17](https://github.com/brave/brave-rewards-ios/issues/17) via [**ZenHub**](https://www.zenhub.com/)
