### ISSUE TITLE
Long press menu doesn't work while javascript is disabled

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1055]
### Description: 
Most likely a regression of https://github.com/brave/brave-ios/issues/830

### Steps to Reproduce 
  1. Disable javascript in settings
  2. Open a website
  3. Try to long press on a link

**Actual result:** 
Nothing happens

**Expected result:**
Context menu should open

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.9

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
This is not a issue on iOS 13+ (dedicated API now available there)

**Comment by iccub** [comment]
Let's close

**Comment by kylehickinson** [comment]
Just for FYI: This is still an issue on iOS 12, but probably not wide-spread.
