### ISSUE TITLE
Brave feedback component - iOS

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1060]
### Description: 
Add the ability for users to easily give specific feedback and report issues about the app.
Note: This is separate to the App Store review

Build a native form that collects the following info (all optional):

Issue details - what is going on
URL
Email address 
Send system info (TBD but most likely, iOS version, iPhone model, Geo for language)
Auto take a screenshot of the page and the user can send it to us if they wish

(This would be super useful for troubleshooting shield issues)

Simple design idea below but @jamesmudgett can you redesign for iOS

Form info can be sent to out support email, an exact email address will be provided later. 

<img width="376" alt="Screen Shot 2019-04-19 at 9 34 13 AM" src="https://user-images.githubusercontent.com/7606853/56433620-5011e300-6286-11e9-9285-0fd5d7316892.png">

Desktop: https://github.com/brave/brave-browser/issues/4112

**Comment by jhreis** [comment]
Definitely requires thought, like where this information goes, who is reviewing it. May just be best to encourage people to go to community more?

**Comment by atsyed87** [comment]
Team is spread very thin as is replying to Community alone; we don't want to handle more direct email support. Is there any way we can tie this into some automation?

**Comment by karenkliu** [comment]
We explored a couple designs awhile ago:

![report a bug](https://user-images.githubusercontent.com/2388823/64199337-f417b780-ce3e-11e9-928f-a0670c5fe1f2.png)


After talking about it we decided clicking "Report a bug" in iOS settings would open the user's default email client with some information filled out.
@anthonypkeane Maybe this issue should be closed?
