### ISSUE TITLE
Top Sites missing from New Tab on iPad 

### ISSUE THREAD

**Issue by seanf** [brave/brave-ios#1065]
### Description: 

Recently/frequently visited “top” sites are not visible

### Steps to Reproduce 
  1. Open New Tab
  

**Actual result:** 

Adblock stats, but no website links.

![4E20892A-D2A5-4EB8-B4DF-6E0330B052B3](https://user-images.githubusercontent.com/54155/56580304-9b751a00-6615-11e9-9067-944d49b062d0.png)

**Expected result:**

Commonly visited sites should be listed, as seen on other platforms and this iOS video:
https://youtu.be/NoQod9E_9iE

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
Version 1.9.1 (19.04.02.12)

**Device details:** 
iPad 6, iOS 12.1.1

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

**Comment by iccub** [comment]
Top sites are not websites which are frequently visited anymore but rather a special type of bookmark,  You can add your favorite sites there via share menu -> add to favorites

But the weird thing is that there should be few preloaded favorite websites, this looks like a bug.
You can try to kill the app and reopen it to see if the preloaded favorites are back

**Comment by seanf** [comment]
Thanks @iccub. I killed the app - no change. But the share menu worked - I hadn't realised that "Add to Favourites" was provided by Brave, and I thought it was referring to something more generic (Safari). A hint on the New Tab page might aid discoverability.

One thing that might help explain what happened: this iPad was set up from a backup of my old iPad 4, which could only run an old 32-bit version of Brave. I'm not sure if Brave-iOS had Top Sites back then.

**Comment by iccub** [comment]
Thanks for providing the details.
We are revamping bookmarks/settings menu and soon it will be easier to add a website to favorites.

<img width="544" alt="Zrzut ekranu 2019-04-21 o 21 51 17" src="https://user-images.githubusercontent.com/6950387/56657154-9f498080-6697-11e9-9115-3d0a0ac39489.png">

Users will be able to tap on `Add to` and choose whether their save location including home screen top sites.

Closing this ticket for now, feel free to comment if there's anything more to add

**Comment by seanf** [comment]
@iccub Sounds good, thank you!
