### ISSUE TITLE
Add BraveRewards & BraveRewardsUI dependencies

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1070]
https://github.com/brave/brave-rewards-ios

Bridging the two projects, somehow not requiring the user to build the static libraries from brave-core. While the app will obivously need the frameworks, it may not need the actual code. If we can solve the C++ library gen ([brave-rewards-ios#22](https://github.com/brave/brave-rewards-ios/issues/22)), this is actually a non-issue and we can include `brave-rewards-ios` as a Carthage dependency or simply a git submodule (to enable users to edit it within `brave-ios`)

**Comment by iccub** [comment]
I guess this is not needed anymore

**Comment by iccub** [comment]
Rewards integration ticket: https://github.com/brave/brave-ios/issues/1126
