### ISSUE TITLE
fix npm audit errors

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1071]
```
$ npm audit
found 272 vulnerabilities (271 moderate, 1 high) in 7171 scanned packages
  run `npm audit fix` to fix 270 of them.
  2 vulnerabilities require semver-major dependency updates.
```

**Comment by iccub** [comment]
Did you check on latest `development` branch? 
My audit shows `found 1 high severity vulnerability in 7171 scanned packages` and the 1 high vuln is tracked here https://github.com/brave/brave-ios/issues/1057

**Comment by iccub** [comment]
I believe this https://github.com/brave/brave-ios/pull/1035 fixed the remaining npm vulnerabilities
