### ISSUE TITLE
Unable to navigate inside of a bookmark folder or open a bookmark

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1076]
### Description: 
Unable to navigate inside of a bookmark folder

### Steps to Reproduce 
  1. Install 1.9.2
  2. Create a bookmark folder on the left wall
  3. Tap to go inside the folder, doesn't work just highlights the folder
  4. Close  and reopen the bookmark hanger, still cant go inside the folder to bookmark

**Actual result:** 
Unable to navigate inside of a bookmark folder

**Expected result:**
Should be able to go inside the folder to add new bookmarks

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.9.2(19.04.25.1)

**Device details:** 
iPhone 7+ (iOS 12.2)

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)?  N/A

**Comment by srirambv** [comment]
As a consequence of this bug edit option is missing for bookmarks/folders. Only delete option shows up

**Comment by jhreis** [comment]
Closed per above commit (into master, not dev).

**Comment by srirambv** [comment]
* Verification passed on iPhone 7 running 1.9.2(19.5.8.23)
* Verification passed on iPhone 8 running 1.9.2(19.5.8.23)
* Verification passed on iPad 5th Gen running 1.9.2(19.5.8.23)
* Verification passed on iPhone SE running 1.9.2(19.5.8.23)
* Verification passed on `iPad Mini 4 using iOS 12.2 running 1.9.2(19.5.8.23)`
