### ISSUE TITLE
npm should be added to the README

### ISSUE THREAD

**Issue by cicicice** [brave/brave-ios#1078]
I followed the build instructions on my "brand new Mac" and bootstrap.sh complains npm is not installed, maybe it should be more opinionated and install a specific version or recommend one in the README

I should add, going into Xcode Preferences and selecting the command line build tools is also absolutely necessary, if someone has been using Xcode for months or years may have done so already, but on a new Mac it is a must!

**Comment by jhreis** [comment]
Thanks for the feedback, `npm` check happens inside the bootstrap script: https://github.com/brave/brave-ios/blob/development/bootstrap.sh#L23

Most devs would have this, but if not, there is a message there. Definitely will look at mentioning the CLI configuration.
