### ISSUE TITLE
Automate Enterprise betas

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#108]
Launch beta applications using enterprise certificates.

https://github.com/brave/browser-android-tabs/releases

**Comment by tmancey** [comment]
Moved to backlog as work only partially completed in https://github.com/brave/brave-ios/issues/108

**Comment by tmancey** [comment]
Need to figure out where to land the builds, @jhreis knows who to talk to though

**Comment by tmancey** [comment]
Needs further discussion with development

**Comment by tmancey** [comment]
@jhreis @anthonypkeane Joel is this something Anthony can help unblock please?

**Comment by jhreis** [comment]
No, I think we will use Apple's new Testflight tools, they released this last week. Doing research now to identify limitations / capabilities, but looks pretty solid.

**Comment by tmancey** [comment]
Unblocking ticket, and will block again if TestFlight does not work out

**Comment by iccub** [comment]
Closing, we added some enterprise automation here
https://github.com/brave/brave-ios/pull/2732
