### ISSUE TITLE
Peek/pop 3D touch

### ISSUE THREAD

**Issue by olivermagnanimous** [brave/brave-ios#1080]
### Description: 
Not being able to use peek and pop on links or images is the only thing that makes me want to switch back to Safari. The long press is just too slow and it doesn’t show you the peek preview.

**Comment by kylehickinson** [comment]
Related APIs to add this support: https://webkit.org/blog/7016/ios-10-link-preview-api-in-wkwebview/

**Comment by mollyIV** [comment]
Hey guys 👋 

If you do not mind and nobody is working on this issue, I would like to give it a shoot as a first good issue 🙂💪 

Peek and Pop will be a great feature to have in Brave browser, I am very excited about it 🚀

**Comment by iccub** [comment]
I wonder if it's even worth implementing given that 3d touch could be removed in the future

https://forums.macrumors.com/threads/apple-expected-to-remove-3d-touch-from-all-2019-iphones-in-favor-of-haptic-touch.2182908/

@mollyIV our project manager @jhreis is on PTO, I will ping him after he's back to answer you :)

**Comment by mollyIV** [comment]
👋 I opened a draft pull request to make a discussion easier 🙂 

https://github.com/brave/brave-ios/pull/1108

**Comment by jhreis** [comment]
We had to revert this due to iOS 13 gesture conflicts (commit https://github.com/brave/brave-ios/commit/b3f412b9effddf32204463ca478d1e6a3bef0317). Re-opening for now.

**Comment by iccub** [comment]
This isn't easy to fix in iOS 12, iOS 13 support this out of the box.
Labelling as `won't have` for versions earlier than iOS 13
