### ISSUE TITLE
3D Touch cursor in address bar

### ISSUE THREAD

**Issue by olivermagnanimous** [brave/brave-ios#1081]
### Description: 
3D-touching the keyboard on iPhones should let you move the cursor around. It works in text fields, but not the address bar.

### Steps to Reproduce 
  1. Select address bar
  2. 3D Touch the keyboard
  

**Actual result:** 
Haptic feedback but no cursor movement

**Expected result:**
Haptic feedback and you can move the cursor back and forth

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
Version 1.9.1 (19.04.02.12)

**Device details:** 
iPhone XS iOS 12.2

**Comment by srirambv** [comment]
This works in URL bar only if the text is not highlighted. 
![ezgif-5-f2a130053caf](https://user-images.githubusercontent.com/17010094/57297482-b0ce5780-709d-11e9-8100-90bf9f35c057.gif)


Not sure if its supposed to work on text highlight. This is recorded on iPhone 7+

**Comment by olivermagnanimous** [comment]
It does work even when the text is highlighted in Safari.

**Comment by srirambv** [comment]
So Safari is basically removing the text highlight and then scrolls using 3D touch. We should probably do the same.

cc: @iccub @danishjafri88

**Comment by olivermagnanimous** [comment]
It’s the same as for text across iOS by the way, not specific to URL bars. If you highlight something in the Notes app and then try to move around with 3D Touch it’ll un-highlight it and give you a cursor.

**Comment by kylehickinson** [comment]
This should be fixed now that #1990 is merged

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.20.19)
* Verified editing URL highlights the URL and 3D touch allows cursor movement when URL is highlighted
------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.20.19)
* Verified editing URL highlights the URL and 3D touch allows cursor movement when URL is highlighted
------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.20.19)
* Verified editing URL highlights the URL and 3D touch allows cursor movement when URL is highlighted
------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.20.19)
* Verified editing URL highlights the URL and 3D touch allows cursor movement when URL is highlighted
------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.20.19)
* Verified editing URL highlights the URL and 3D touch allows cursor movement when URL is highlighted
