### ISSUE TITLE
Incorrect Brave app used when selecting from share sheet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1084]
### Description: 
Incorrect Brave app used when selecting from share sheet

### Steps to Reproduce 
  1. Install both Beta and Prod build of Brave
  2. Long press on a link in an external app to bring the share sheet in focus
  3. Choose Beta app from share sheet, link opens in Prod build 

**Actual result:** 
Incorrect Brave app used when selecting from share sheet

**Expected result:**
Should use the correct app to switch and open the link via share sheet

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
All

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

**Comment by srirambv** [comment]
@anthonypkeane @jhreis can this is prioritised to have in 1.10 at the latest? Becomes difficult when testing with two installs

**Comment by kylehickinson** [comment]
Would require different URL registrations for internal vs live build. I.e. 

`brave://` for live
`brave-dev://` for dev
`brave-beta://` for beta

**Comment by ciccioska** [comment]
Hi, I follow the @kylehickinson suggestion and I'm working on it. How can I sign a beta version?

**Comment by jhreis** [comment]
@ciccioska There are signing instructions in the [readme](https://github.com/brave/brave-ios/#code-signing) at the bottom.

**Comment by ciccioska** [comment]
@jhreis I just followed the instruction but If I want to install the Beta target on my device I can't because it use a bundle specific. So before I use a custom bundle on my developer account I tried to ask this question to you. Thanks

**Comment by kylehickinson** [comment]
@ciccioska You can use custom bundle IDs since you're right these use bundle IDs for Brave. 

Easiest way is to adjust the `FRAMEWORK_BASE_BUNDLE_ID` here: `Client/Configuration/Base.xcconfig`

**Comment by jacobmbarnard** [comment]
Hi, has this been resolved? Looks like it's been a couple years.

**Comment by pjolt** [comment]
Also came to report this exact issue.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 16.2` using version `1.47 (23.1.23.20)`

- Ensured selecting `brave dev app` from share sheet will open dev channel app
- Ensured selecting `brave release app` from share sheet will open release channel app

Example | Example | Example
-|-|-
![IMG_4329](https://user-images.githubusercontent.com/17885425/214452034-6c5a6168-6f70-40e8-892a-7531182c9dbc.jpg) | ![IMG_4330](https://user-images.githubusercontent.com/17885425/214452037-6f0e8216-3777-48ff-a1b8-60cfc36f14fd.PNG) | ![IMG_4331](https://user-images.githubusercontent.com/17885425/214452041-b87aed0b-688b-4492-9562-5f014f30a3b7.PNG)
