### ISSUE TITLE
BVC taskQueue is refilled in setupTabs() leading to crash.

### ISSUE THREAD

**Issue by danishjafri88** [brave/brave-ios#1085]
### Steps to Reproduce 
  1. Open Settings
  2. Select private browsing mode
  

**Actual result:** 
Crash

**Expected result:**
No crash. App moves to private browsing

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
Can you please add steps for QA?

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+ (iOS 12.3.1) running 1.10 (19.07.08.19)
  - Verified able to toggle PB only mode and no crash
  - Verified setting PB mode only and removing app from memory and relaunch, doesn't crash
  - Verified toggle PB mode retains normal tabs 
* Verification **PASSED** on `iPad Mini 4 running iOS 12.3.1` using `1.10 (19.07.10.17)`
  * ensured that toggling PB several times didn't cause any crashes
  * ensured that the normal tabs/session is retained when switching back and forth
  * ensured history and other data isn't being leaked from PB
  * ensured that using PB only didn't crash when restarting the app several times

- Verification passed on iPhone 8 running iOS 12.3.1 using 1.10(19.07.16.23)
   - Verified able to toggle PB only mode and no crash
  - Verified setting PB mode only and removing app from memory and relaunch, doesn't crash
  - Verified toggle PB mode retains normal tabs
