### ISSUE TITLE
Memory leak in TabManager restoreAllTabs. 

### ISSUE THREAD

**Issue by danishjafri88** [brave/brave-ios#1086]
Restored tab is retained by the lazy stored property restoreAllTabs, leading to memory leak.

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
@jhreis would this be removed from the 1.10 release under ZenHub?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(21.5.26.21)
- Verified test plan from https://github.com/brave/brave-ios/pull/3636
- Verified tabs restore correctly 
-----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.26(21.5.26.21)
- Verified test plan from https://github.com/brave/brave-ios/pull/3636
- Verified tabs restore correctly 
-----------
Verification passed on iPad Pro with iOS 14.5.1 running 1.26(21.5.26.21)
- Verified test plan from https://github.com/brave/brave-ios/pull/3636
- Verified tabs restore correctly
