### ISSUE TITLE
Append Brave/<MajorFxiOSVersion> to User Agent

### ISSUE THREAD

**Issue by bbondy** [brave/brave-ios#1088]
As an example:

Instead of:
`Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/14.0b12646 Mobile/15E148 Safari/605.1.15`

We'd show:
`Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/14.0b12646 Mobile/15E148 Safari/605.1.15 Brave/14`

Keep the custom headers we use for partners for a couple months before removing it.

**Comment by iccub** [comment]
No plans to change UA for now. Will reopen when we decide to go for it
