### ISSUE TITLE
Header UI transition 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1089]
On scrolling up and down, our header transition could be smoother. 
It is very jumpy right now

![UI Header Issue](https://user-images.githubusercontent.com/7606853/57733856-5e6cd800-7655-11e9-94f4-cc1243cd3297.gif)

To reproduce, 
Open a webpage and scroll up and down

**Comment by kylehickinson** [comment]
Closed as cannot reproduce anymore, must have been fixed at some point
