### ISSUE TITLE
Favicon on Brave website blends into an orange background on iOS

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-ios#1092]
## Description
Currently the favicon on the Brave website blends into an orange background:
![IMG_3559](https://user-images.githubusercontent.com/2388823/57896478-ceba5b80-7805-11e9-9829-909076807d23.PNG)
![IMG_ED76A71238F7-1](https://user-images.githubusercontent.com/2388823/57896482-d1b54c00-7805-11e9-8eea-f072c4ca0f85.jpeg)

## Expected Result
The favicon should not have an orange background and be the same as it appears on desktop:
<img width="213" alt="Screen Shot 2019-05-16 at 6 10 32 PM" src="https://user-images.githubusercontent.com/2388823/57896498-eb569380-7805-11e9-91ac-33d777d9d996.png">

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.22.15)
* Verified on light theme
![image](https://user-images.githubusercontent.com/17010094/69445889-4622f780-0d21-11ea-99e9-6be0a98295c3.png)
* Verified on dark theme
![image](https://user-images.githubusercontent.com/17010094/69445896-4a4f1500-0d21-11ea-9c59-d009d1c03fde.png)

----------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.22.15)
* Verified on light theme
![image](https://user-images.githubusercontent.com/17010094/69445918-54711380-0d21-11ea-8dce-ee4eaf1c5c0f.png)
* Verified on dark theme
![image](https://user-images.githubusercontent.com/17010094/69445906-4f13c900-0d21-11ea-854b-303f969b7305.png)
----------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.22.15)
* Verified on light theme
![image](https://user-images.githubusercontent.com/17010094/69446023-8aae9300-0d21-11ea-9108-4e0c6e0721bb.png)
* Verified on dark theme
![image](https://user-images.githubusercontent.com/17010094/69445883-41f6da00-0d21-11ea-95c1-0654ea77e2aa.png)

----------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.22.15)
* Verified on light theme
![image](https://user-images.githubusercontent.com/17010094/69445929-59ce5e00-0d21-11ea-9c56-8bedcb6dd4f7.png)
* Verified on dark theme
![image](https://user-images.githubusercontent.com/17010094/69445938-5f2ba880-0d21-11ea-9eea-4f23b536b3fd.png)

----------
Verification passed on iPad Pro  with iOS 12.4 running 1.14(19.11.22.15)
* Verified on light theme
![image](https://user-images.githubusercontent.com/17010094/69445865-373c4500-0d21-11ea-8a29-d9675b4ca04b.png)
* Verified on dark theme
![image](https://user-images.githubusercontent.com/17010094/69445872-3c998f80-0d21-11ea-8c5e-4fdf3019d529.png)
