### ISSUE TITLE
Google/Duckduckgo image search results display incorrectly 

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-ios#1093]
## Description 

Conversation continued from https://bravesoftware.slack.com/archives/C06UXF3KJ/p1558033869092900

> @lukemulks: 
> There are some caveats, but I'm able to repro what this user is experiencing....I was driving myself nuts over this about 7 months ago on android.
> 
> I'm about 99% convinced that this user is blocking scripts, either in the site-level shield settings, but more likely, within the shield defaults in the browser settings.
> 
> If you block scripts, you can easily repro the conditions that are described for duckduckgo.com.
> 
> None of the other search options: images, shopping, etc. display when scripts are blocked.
> 
> Also, the page appears to be in desktop mode, but it really isn't, it's just different enough with scripts blocked to appear that way.
> 
> For Google image search, I'm able to repro the conditions with scripts blocked as well.
> 
> The page appears to be in a desktop view, even though in mobile, again, because the scripts that make life beautiful are gone.
> 
> Images click through directly to the site that hosts them, instead of Google.
> 
> I have not encountered a twitter image, so am unable to repro that case.
> 
> OK, regarding the *even when I disable shields, I'm still observing the issue* comment, I believe I have found one, or maybe two, potential bugs. Let me know if you, or anyone else, is able to repro this.
> 
## Steps to Reproduce

> *Potential bug 1*
> _*It appears that there's a potential issue with blocking scripts from global shield default settings in the browser*_
> 
> - If I have scripts blocked from the global default shield settings, and I navigate to duckduckgo.com from another website, I'm not observing scripts being blocked.
> 
> - I'm observing the same behavior on google.com as well.
> 
> - Is anyone else able to repro this?
> 
> *Potential bug 2*
> _*From the site-level shields menu, if I block scripts, then restore scripts, the page does not refresh with scripts enabled.*_
> - I'm observing the page reloading with scripts disabled.
> - Also, if I go from having scripts enabled to blocking scripts, the page reloads with scripts disabled. If I then disable shields, the page reloads, but does not reload with scripts enabled as one would expect.
> 
> 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 
iPad Pro, Brave v1.9.2 (19.05.08.23)
iPhone8  iOS 12.2 (19.04.02.12)

### Additional Information 
User report (reddit):
https://www.reddit.com/r/brave_browser/comments/bpekfu/question_on_google_image_search_results_and/

**Comment by GeetaSarvadnya** [comment]
The issue is Reproducible on iPhone8 ( iOS 12.2) with brave version 1.9.2 (19.05.08.23)

STR:

1. Clean profile 1.9.2
2. Enable global shield setting `Block Scripts`
3. Open google.com in a new tab
4. Search `images` 
5. Click on `Images` in google search results
6. Images displayed are zoomed out as if in Desktop mode
7. Scroll down to the bottom of search results page and observe that Mobile mode is displayed
8. Click on Image to view
9. Twitter page is displayed to tweet the particular image




https://drive.google.com/open?id=1ZQZbP-LCRPlDD24N2v9861WAGmvGTHxk

**Comment by iccub** [comment]
let's close, reopen if needed, those websites changed a lot since 2019
