### ISSUE TITLE
Deadlock when blocking ads

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1094]
# Test Plan
See: https://github.com/brave/brave-ios/pull/1095
# 

### Steps to Reproduce 
  1. Clean install, visit jbhifi.com.au

**Actual result:** 
App freezes or crashes for some users

**Expected result:**
Should not freeze

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Often

**Brave Version:** 
1.9.2, also happens on development branch

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Able to crash the browser with following steps
1. Visit https://guardianbookshop.com/
2. Add a few books to the shopping cart
3. Click on checkout 
4. Click on `Ckeckout with PayPal`
5. Browser crashes
6. Repeat steps after relaunching doesn't crash

**Comment by GeetaSarvadnya** [comment]
I have seen 2 crashes on the website https://guardianbookshop.com/.

1. When I click on any random book link - Brave crashed
2. When I click on Contact us and Delivery Information - Brave crashed

cc @iccub

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ and iPad Pro running 1.9.3 (19.05.22.15) 
* Verified test plan from #1095
* Verified browser didn't crash when navigating through the sites mentioned in test plan
* Verified browser didn't crash when navigating through the sites when sync was in progress
* Verified browser didn't crash when retried steps from https://github.com/brave/brave-ios/issues/1094#issuecomment-494356122 and  https://github.com/brave/brave-ios/issues/1094#issuecomment-494356268

Verification passed on iPhone 8 running 1.9.3 (19.05.22.15) 
* Verified test plan from #1095
* Verified browser didn't crash when navigating through the sites mentioned in test plan
* Verified browser didn't crash when navigating through the sites when sync was in progress
* Verified browser didn't crash when retried steps from https://github.com/brave/brave-ios/issues/1094#issuecomment-494356122 and  https://github.com/brave/brave-ios/issues/1094#issuecomment-494356268

Verification passed on iPhone SE running 1.9.3 (19.05.22.15)

Verified passed with iPad (5th Gen) using (19.05.22.15)
* Verified test plan from #1095
* Verified browser didn't crash when retried steps from https://github.com/brave/brave-ios/issues/1094#issuecomment-494356122 and  https://github.com/brave/brave-ios/issues/1094#issuecomment-494356268

Verification passed on`iPad Mini 4 running 1.9.3 (19.05.22.15)`
* Verified test plan from #1095
* Verified browser didn't crash when navigating through the sites mentioned in test plan
* Verified browser didn't crash when navigating through the sites when sync was in progress
* Verified browser didn't crash when retried steps from https://github.com/brave/brave-ios/issues/1094#issuecomment-494356122 and  https://github.com/brave/brave-ios/issues/1094#issuecomment-494356268
