### ISSUE TITLE
Ocassional crashes on 1.9.2

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1096]
# Test plan
See here: https://github.com/brave/brave-ios/pull/1097
# 

### Steps to Reproduce 
  1. Use the app for some time, open some tabs and websites

**Actual result:** 
App crashes with `EXC_BAD_ACCESS`

<img width="1050" alt="Screenshot 2019-05-19 at 8 55 14 PM" src="https://user-images.githubusercontent.com/6950387/58022487-d59ae400-7b0d-11e9-9c64-dd013df8ed27.png">

**Expected result:**
Should not crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 
1.9.2, also happens on latest development build

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Able to reproduce crash on jbhifi.com.au with following steps

1. Set fingerprinting on in global shields settings
2. Open the site in private tab
3. Visit a few pages on the site and add a few items to shopping cart
3. Click on shopping cart and click on checkout 
4. Page loads continuously but remain blank
5. Click on shields, turn of fingerprinting, browser crashes
6. Repeat the steps again, doesn't crash

cc: @iccub

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ and iPad Pro running 1.9.3 (19.05.22.15)
* Verified browser doesn't randomly crash when navigating  jbhifi.com.au / guardianbookshop.com / cyclingweekly.com
* Verified browser didnt crash when following steps from https://github.com/brave/brave-ios/issues/1096#issuecomment-494404696
* Verified browser didnt crash when navigating through the site while sync was in progress

Verification passed on iPhone SE running 1.9.3 (19.05.22.15)

Verified passed with iPad (5th Gen) using 1.9.3 (19.05.22.15).
* Verified browser doesn't randomly crash when navigating  jbhifi.com.au / guardianbookshop.com / cyclingweekly.com
* Verified browser didnt crash when following steps from https://github.com/brave/brave-ios/issues/1096#issuecomment-494404696
* Verified test plan from https://github.com/brave/brave-ios/pull/1097

Verification passed on iPhone 8 running 1.9.3 (19.05.22.15)
* Verified browser doesn't randomly crash when navigating  jbhifi.com.au / guardianbookshop.com / cyclingweekly.com
* Verified browser didnt crash when following steps from https://github.com/brave/brave-ios/issues/1096#issuecomment-494404696
* Verified browser didnt crash when navigating through the site while sync was in progress

Verification passed on `iPad Mini 4 running 1.9.3 (19.05.22.15)`
* Verified browser doesn't randomly crash when navigating  jbhifi.com.au / guardianbookshop.com / cyclingweekly.com
* Verified browser didnt crash when following steps from https://github.com/brave/brave-ios/issues/1096#issuecomment-494404696
* Verified browser didnt crash when navigating through the site while sync was in progress
