### ISSUE TITLE
Full keychain read/write support

### ISSUE THREAD

**Issue by chee** [brave/brave-ios#1109]
it would be great if full Apple Keychain support could be added to the iOS client. Users are able to read passwords from the Keychain, but saving passwords to the Keychain is not available.
There's [a priority/p5 issue](https://github.com/brave/brave-browser/issues/820) to add Keychain support to the desktop browser, and it would be great if that were to come to the iOS client too.

sorry for the brief issue

**Comment by iccub** [comment]
For now we will handle password saving, reading and syncing using shared chromium code, if this happens we will most likely pull changes implemented on brave-core side, let's close it for now
