### ISSUE TITLE
App won't start on iPad with Swedish langauge

### ISSUE THREAD

**Issue by Jacalz** [brave/brave-ios#1111]
### Description: 
As a follow up to #1040 that never got fixed to be honest, I have opened this issue because we have narrowed down the issue and kind of found the underlying problem. Brave after the 1.9.0 update would never start on my iPad Air 2, but worked flawlessly on my iPhone 7. I managed to narrow it down, with some help by @iccub, to it being an issue when using the Swedish language. Switching over to UK English mad the app start again, but the strange thing is that I have the Swedish language on both devices.

My guess is that it has something to do with the regional ad blocking introduced in 1.9. Switching back to Swedish on the iPad makes it not work again.

### Steps to Reproduce 
  1. Switch to Swedish language on an iPad
  2. Try to start the app
  3. Switch to the UK English language
  4. See that app now starts as expected

**Actual result:** 

Crashes when using Swedish language:
![File from iOS](https://user-images.githubusercontent.com/25466657/58709971-909f6900-83bb-11e9-9ea3-7b7e919e67e8.gif)

**Expected result:**
Should start up just like it does with Swedish on iPhone.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
All the time when  using Swedish on iPad

**Brave Version:** 
Can get exact version since the app won’t start, but it’s past 1.9 and up to 1.9.3

**Device details:** 
iPad Air 2 on IOS 12.3.1

**Comment by srirambv** [comment]
The fix for  #1040  is  not yet in the build. Its marked for 1.10 release. 

cc: @iccub @jhreis to confirm if its part of the current release

**Comment by Backspaze** [comment]
I downloaded the app for the first time just now and ran into the same issue on my iPhone 5S (iOS 12.3.1) right from the start.

When I switched the OS language from Swedish (my default setting) to English the app started working, but for me it continued working after I switched back to Swedish. Maybe it's working for me because it's a completely fresh install of the app?

**Comment by iccub** [comment]
This should be working on upcoming 1.10 release, just tested it :) sorry for long waiting time

**Comment by kjozwiak** [comment]
I managed to reproduce the original issue using `1.9.3 (19.05.22.15)` but can't reproduce the problem using `1.10 (19.07.16.23)`. Seems like it's been fixed. 

* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`
  * Channged iOS language to `Swedish (Svenska)`
  * installed & launched `1.10 (19.07.16.23)` on `iPhone 6s+ running iOS 12.3.1` without crashes

* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.16.23)
   - Changed iOS language to `Swedish (Svenska)`
   - installed & launched `1.10 (19.07.16.23)` on `iPad 5th Gen running iOS 12.3.1` without crashes
