### ISSUE TITLE
RSS subscription

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1112]
Investigate adding the ability to subscribe and view RSS in Brave

Internal Chat: 
https://bravesoftware.slack.com/archives/C06UXF3KJ/p1559327911001800
&
https://bravesoftware.slack.com/archives/C06UXF3KJ/p1559328315002000

Some info: https://www.imore.com/what-happened-rss-subscriptions-safari-ios-11

cc @jamesmudgett

**Comment by kylehickinson** [comment]
Closing in favour of #3249
