### ISSUE TITLE
Add New Normal Tab option on Private Browsing mode

### ISSUE THREAD

**Issue by iamLoi** [brave/brave-ios#1113]
I've just recently switched from Firefox to Brave on iOS and I'm enjoying it so far. The killer features were the adblocker and the tabs row.

There is one glaring design flaw thing I've noticed though, which is bugging me. When you're on Normal Browsing and you tap and hold the "+", you can choose New Private Tab or New Tab. But when you're in Private Mode, holding the "+" only gives you New Tab. Where is the New Normal Tab? The option to open New Normal Tab should be there, if only for consistency purposes. It's a design flaw and makes it a hassle to switch out of Private Mode. 

Please add the New Normal Tab option on Private Browsing mode.

Otherwise, Brave for iOS is one of the few (or only) mobile browser able to block Youtube ads, which makes it pretty great!

**Comment by jhreis** [comment]
@tomlowenthal @jumde thoughts on this?
I'm mostly concerned with introducing more mechanisms to leave private mode, as it will potentially add more security holes, but curious on your thoughts.

**Comment by tildelowengrimm** [comment]
I'm with you @joel. It makes sense to open a private tab from normal mode, but it doesn't make sense to me to go the other way. And I'd definitely like to avoid increasing complexity where that potentially leads to security issues.
