### ISSUE TITLE
Unable to open links due to adblock

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1114]
### Description: 
Unable to open links due to adblock

### Steps to Reproduce 
  1. Go to https://investor.pandoragroup.com/
  2. Top navigation links don't work on tap
  3. Disable adblock. top navigation works just fine

**Actual result:** 
Unable to open links due to adblock

**Expected result:**
Should work without having to disable adblock

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.9.3

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
Original community report https://community.brave.com/t/shield-often-blocks-valid-links-in-brave-ios/63495
cc: @anthonypkeane to prioritize for release

**Comment by anthonypkeane** [comment]
Site opens for me @srirambv on my iPhone x (iOS12)
It is a desktop site, but it is opening

**Comment by dnv** [comment]
> Site opens for me @srirambv on my iPhone x (iOS12)
> It is a desktop site, but it is opening

Site loading isn't the problem. The black sub-menu options (News, Financials, Presentations, etc) not working is.

**Comment by iccub** [comment]
Seems to be working now, old ticket and a lot could have changed on that website or within our blocklists
