### ISSUE TITLE
URL Bar overlaps the iOS status bar

### ISSUE THREAD

**Issue by corymcdonald** [brave/brave-ios#1115]
### Description: 

![image](https://user-images.githubusercontent.com/5459225/58814888-30433e00-85ec-11e9-99cf-3d0560db6b9a.png)

### Steps to Reproduce 

I can't figure out a way to reliably reproduce but this has been a minor visual bug for a long time. 

Usually it's after I re

**Reproduces how often:** [Intermittent Issue]

**Brave Version:**  Version 1.9.3 (19.05.22.15) 

**Device details:** iphone 8+ ios 12.2 

### Additional Information 

Someone mentioned this is a bug from FF? Not sure

**Comment by srirambv** [comment]
I've seen this happen too in the previous versions. Usually gets fixed when app focus is changed or open tab tray. Havent seen this happen lately on iPhone 7

**Comment by anthonypkeane** [comment]
I got it once on my iPhone X but could not reproduce.

**Comment by kjozwiak** [comment]
I've had this happen to me several times in the past on my `iPad Mini 4`. As @srirambv mentioned above, this bug has been around for some time now.

**Comment by jhreis** [comment]
@corymcdonald We modified some of the title bar logic, can you test / use 1.11 for awhile, and let me know if this is still an issue?

**Comment by kylehickinson** [comment]
Closed as stale

**Comment by kjozwiak** [comment]
@srirambv can you still reproduce this at all? Have you run into it while going through `1.13`?

**Comment by srirambv** [comment]
@kjozwiak  yes it does reproduce but I don't have an exact scenario/steps to reproduce this consistently. I can reopen the issue if I find a consistent step to reproduce the issue.

**Comment by kjozwiak** [comment]
Going to re-open as this is still a valid issue. I ran into this during the weekend but couldn't find STR.

**Comment by kylehickinson** [comment]
@srirambv have you reproduced this at all since? If so, can you re-test with 1.41, there was some changes with the toolbar visibility/scrolling behaviour (https://github.com/brave/brave-ios/pull/5630) that may have inadvertently fixed this

**Comment by iccub** [comment]
Let's move it to 1.41 for retest after your toolbar changes

**Comment by iccub** [comment]
Closing, and we reopen if this still happens. Unlikely since we've done major changes in order to support the bottom toolbar
