### ISSUE TITLE
Add the ability to "X" out of an old search in the URL bar

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1116]
If you search for something in the URL bar, that search string remains meaning the next time you want to search, you need to backspace the old string before you can add a new one.

Adding an X would add the ability to kill that search term

![IMG_668BE9EB851B-1.jpeg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/fbc41853-155d-43e4-af89-91767e517552)

**Comment by jhreis** [comment]
You can just hit the clear button on keyboard since it is pre-highlighted, do you think this is not enough?

**Comment by anthonypkeane** [comment]
Internal chat: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1574181863403000

No, I'd like to see an x, I think it would be better for the user

**Comment by srirambv** [comment]
* Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69349004-10104580-0c45-11ea-9c49-79c84e55f935.png)

* Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69348923-ee16c300-0c44-11ea-91ce-01bc0852aa35.png)

* Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69348952-f969ee80-0c44-11ea-8953-b654cc03d67d.png)

* Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69348933-f2db7700-0c44-11ea-894f-d674e17364a1.png)

* Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69348961-fd960c00-0c44-11ea-8285-554bbefeb81f.png)
