### ISSUE TITLE
Add an "Open in Brave" link in this open she

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1117]
Investigate if we can add an "Open in Brave" link in this open sheet.

Should work in all apps

![Image-1.jpeg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/deea7676-59e4-4611-ab7a-8fc988067580)

**Comment by jhreis** [comment]
What is this sheet from? We can't control this if it is a different application.

**Comment by anthonypkeane** [comment]
closing as not possible :(
