### ISSUE TITLE
Ebay uk and gmail showing out of date browser

### ISSUE THREAD

**Issue by alex11123** [brave/brave-ios#1118]
### Description: 
Some sites say that the browser is outdated such as eBay uk and gmail

### Steps to Reproduce 
  1.load eBay uk or gmail
  2. See red bar showing that browser is out of date
  3.

**Actual result:** 

**Expected result:**
No message

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Every time

**Brave Version:** 
Ios v1.9.3 19.05.22.15

**Device details:** 
Ios ipad pro 11 12.3.1

**Website problems only:**
- did you check with Brave Shields down? Yes
- did you check in Safari/Firefox (WkWebView-based browsers)? Yes

**Comment by iccub** [comment]
Tested both websites and it doesn't seem to happen anymore.
QA team please verify this too, closing for now
