### ISSUE TITLE
Add bookmarklet support

### ISSUE THREAD

**Issue by andreiburov** [brave/brave-ios#1119]
### Description: 

Like mentioned in the previous repo, there is a need for the bookmarklet support https://github.com/brave/browser-ios/issues/1724. Thus feature is supported by both safari and firefox on ios.

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.16.18)
* Verified bookmark can't be saved with just 
```js 
javascript:function() {}
```
* Verified bookmark can't be saved with just 
```js
javascript:
```
* Verified bookmark is saved as below but doesn't show any error when loading 
```js
javascript:fun
```
* Verified bookmark can be saved as below and an alert prompt is shown 
```js
javascript:(function(){ alert("hello"); })()
```
![image](https://user-images.githubusercontent.com/17010094/67042324-a5279800-f0f5-11e9-822e-79fa315b1596.png)

* Verified editing an existing bookmark to `https://brave.com` successfully updates the favicon and loads the site when selected
* Logged https://github.com/brave/brave-ios/issues/1724 for alert box title being localhost

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.16.18)
* Verified bookmark can't be saved with just 
```js 
javascript:function() {}
```
* Verified bookmark can't be saved with just 
```js
javascript:
```
* Verified bookmark is saved as below but doesn't show any error when loading 
```js
javascript:fun
```
* Verified bookmark can be saved as below and an alert prompt is shown 
```js
javascript:(function(){ alert("hello"); })()
```
![image](https://user-images.githubusercontent.com/17010094/67042324-a5279800-f0f5-11e9-822e-79fa315b1596.png)

**Comment by srirambv** [comment]
Verification passed on iPhone Xr with iOS 13.2 running 1.13(19.10.18.15)
* Verified bookmark can't be saved with just 
```js 
javascript:function() {}
```
* Verified bookmark can't be saved with just 
```js
javascript:
```
* Verified bookmark is saved as below but doesn't show any error when loading 
```js
javascript:fun
```
* Verified bookmark can be saved as below and an alert prompt is shown 
```js
javascript:(function(){ alert("hello"); })()
```
![image](https://user-images.githubusercontent.com/17010094/67124452-880bcb80-f1c0-11e9-9847-5f3d4483a20c.png)


Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.10.18.15)
* Verified bookmark can't be saved with just 
```js 
javascript:function() {}
```
* Verified bookmark can't be saved with just 
```js
javascript:
```
* Verified bookmark is saved as below but doesn't show any error when loading 
```js
javascript:fun
```
* Verified bookmark can be saved as below and an alert prompt is shown 
```js
javascript:(function(){ alert("hello"); })()
```
![image](https://user-images.githubusercontent.com/17010094/67124310-4b3fd480-f1c0-11e9-9a9b-7cf8f3808236.png)


Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.18.15)
* Verified bookmark can't be saved with just 
```js 
javascript:function() {}
```
* Verified bookmark can't be saved with just 
```js
javascript:
```
* Verified bookmark is saved as below but doesn't show any error when loading 
```js
javascript:fun
```
* Verified bookmark can be saved as below and an alert prompt is shown 
```js
javascript:(function(){ alert("hello"); })()
```
![image](https://user-images.githubusercontent.com/17010094/67124287-43803000-f1c0-11e9-97b3-f5c08a6fa63d.png)

**Comment by micahjon** [comment]
Has anyone figured out how to install the Push to Kindle bookmarklet on Brave? Works fine in Safari, but evidently fails validation in Brave. Would be nice if there was some error message or something
https://www.fivefilters.org/push-to-kindle/push-to-kindle-bookmarklet/
