### ISSUE TITLE
Occasional crashes on 1.9.3 (from Xcode crash reporter)

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1120]
I can't reproduce them on my device but there is bunch of crashes related to `FifoDict` in `AdblockStats`

some are caused by `addItem` some by `getItem`. So probably a yet another concurrency bug

<img width="523" alt="Zrzut ekranu 2019-06-4 o 16 30 29" src="https://user-images.githubusercontent.com/6950387/58887663-51885500-86e6-11e9-8421-a28c373d8acc.png">
<img width="523" alt="Zrzut ekranu 2019-06-4 o 16 30 36" src="https://user-images.githubusercontent.com/6950387/58887664-51885500-86e6-11e9-8f47-6b10b58c52b1.png">

**Comment by iccub** [comment]
Fixed in https://github.com/brave/brave-ios/pull/1121

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPad Mini 4 running iOS 12.3.1` using `1.10 (19.07.10.17)`
  * Went through the websites listed under https://github.com/brave/brave-ios/pull/1095
  * Went through several other websites (Amazon, Ebay)
* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`
  * Went through the websites listed under https://github.com/brave/brave-ios/pull/1095
  * Went through several other websites (Amazon, Ebay)
* Verification **PASSED** on `iPad 5th Gen running iOS 12.3.1` using `1.10 (19.07.16.23)`
  * Went through the websites listed under https://github.com/brave/brave-ios/pull/1095
  * Went through several other websites (Amazon, Ebay)

**Comment by kjozwiak** [comment]
@LaurenWags wouldn't mind a quick double check to make sure that someone else isn't seeing crashes when going through the websites mentioned under #1095.

**Comment by LaurenWags** [comment]
Done - added comments to https://github.com/brave/brave-ios/issues/1120#issuecomment-510689804

**Comment by kjozwiak** [comment]
Thanks @LaurenWags 👍
