### ISSUE TITLE
Hide keyboard on passcode doesn't bring it up unless app is restarted

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1122]
### Description: 
Hide keyboard on passcode doesn't bring it up unless app is restarted

### Steps to Reproduce 
  1. Enable passcode and set it require immediately
  2. Background the app and bring it into focus
  3. Hide the keyboard on passcode screen
  4. No way to bring it back up unless you remove the app from memory and relaunch

**Actual result:** 
Hide keyboard on passcode doesn't bring it up unless app is restarted

**Expected result:**
Should be able to bring keyboard back to focus without having to close and relaunch the app

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
App store build

**Device details:** 
iPads 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Brandon-T** [comment]
@srirambv 

Are you by chance seeing this: 
![image](https://user-images.githubusercontent.com/1530031/61812039-bae83280-ae10-11e9-9443-73d3ef48309c.png)

Are you seeing that arrow at the bottom right?

**Comment by srirambv** [comment]
@Brandon-T  This is what I see on the Appstore build. The only way to bring the keyboard back is to background and reopen the app
![File](https://user-images.githubusercontent.com/17010094/62699080-ae391200-b9ac-11e9-93c0-f1e156784376.jpg)

**Comment by srirambv** [comment]
Verification passed on iPhone X with iOS 13.1 beta 2 running 1.12(19.09.07.08)
* Verified keyboard isn't hidden when the app is brought into focus

Verification **PASSED** on `iPad Air 3rd Generation` with `iOS 13.1` running `1.12 (19.09.07.03)`:
* Verified keyboard isn't hidden when the app is brought into focus

Verification **PASSED** on `iPhone 6s+` using `iOS 12.4.1` running `1.12 (19.09.13.06)`:
* Verified keyboard isn't hidden when the app is brought into focus
