### ISSUE TITLE
Update PopoverController from rewards-ios

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1125]
Rewards ios repo has an updated PopoverController, copy the changes and test how it works with our current popup panels

**Comment by LaurenWags** [comment]
* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.12.14)
   - Verified menu and shields popovers display correctly.
   - Verified could close/reopen menu and shields popovers.
   - Verified able to tap on items on menu/shields.

![IMG_E934331EE597-1](https://user-images.githubusercontent.com/28145373/61158126-10921600-a4c6-11e9-8985-56fcdb5aa14f.jpeg)

![IMG_977359107E99-1](https://user-images.githubusercontent.com/28145373/61158132-14be3380-a4c6-11e9-813a-c61da5fc95da.jpeg)

* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`
   - Verified menu and shields popovers display correctly.
   - Verified could close/reopen menu and shields popovers.
   - Verified able to tap on items on menu/shields.

![IMG_9813](https://user-images.githubusercontent.com/2602313/61501370-1cd21380-a99d-11e9-8d5c-ab2ddce3e356.PNG)

![IMG_9812](https://user-images.githubusercontent.com/2602313/61501371-1cd21380-a99d-11e9-8741-da8ddb6bb201.PNG)
