### ISSUE TITLE
Disable video autoplay on iOS?

### ISSUE THREAD

**Issue by GT-GH** [brave/brave-ios#1129]
### Description: 

I followed a link to this site from a thread on Apple's support forums, saying this browser allows disabling video autoplay on iOS. I've been experimenting with the browser on my iPhone for a while now but cannot find a way to set autoplay to off. Videos play automatically on the sites I tried (e.g., cnn.com). I searched the wiki and the issues page but the word "autoplay" doesn't bring up any results. Please help a newbie.

### Steps to Reproduce 
  1. Go to a CNN story that contains video

Thanks!

**Comment by danishjafri88** [comment]
@GT-GH, thanks for taking the effort!
@anthonypkeane should we have a setting to disable AutoPlay completely.
Current autoplay policy: https://webkit.org/blog/6784/new-video-policies-for-ios/

**Comment by anthonypkeane** [comment]
Yes, that would be good.
cc @jamesmudgett for UX and @EyanGoldman

**Comment by EyanGoldman** [comment]
@GT-GH sorry for the delayed response on this one! I'm looking into this right now.

**Comment by jhreis** [comment]
This is definitely a must, but does require a good bit of design work potentially. If disabling auto play on a website, do we allow per-site re-enabling? 

Potentially similar design mechanism as https://github.com/brave/brave-ios/issues/1345

**Comment by jamesmudgett** [comment]
Global toggle, for now would be a great setting to have.

**Comment by GT-GH** [comment]
I second the vote for a global toggle. I never want videos to autoplay.

**Comment by anthonypkeane** [comment]
Under Other Settings add
Enable background video autoplay (on/off toggle) with the default On

_On to respect the standard in https://webkit.org/blog/6784/new-video-policies-for-ios/_

**Comment by EyanGoldman** [comment]
For new users do we want block autoplay to be default on or off? I think on, as users probably won't uninstall an app that isn't autoplaying, but will for apps that are. Would be open to other opinions though.

**Comment by anthonypkeane** [comment]
I made an error here as I forgot we stop auto play today
Therefore to respect this
-> Enable background video autoplay (on/off toggle) with the default On
should change to
-> Enable background video autoplay (on/off toggle) with the default Off

**Comment by anthonypkeane** [comment]
Internal thread: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1571341966118800?thread_ts=1571336493.109000&cid=C06UXF3KJ

**Comment by srirambv** [comment]
Enabling the setting and visiting cnn.com is causing the native video player to open up and persist its not allowing media playback on the article page. 
[media autoplay.zip](https://github.com/brave/brave-ios/files/3745117/media.autoplay.zip)

**Comment by srirambv** [comment]
Moving this out of 1.13 as it requires more indepth testing and investigation which is out of scope for 1.13

**Comment by srirambv** [comment]
+1 from @tankmohit  via #1952

**Comment by jhreis** [comment]
Removed from milestone, see https://github.com/brave/brave-ios/issues/1738 for follow up ticket.
