### ISSUE TITLE
Main Menu Redesign

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#1130]
### Description: 

New menu design. This combines the menu on top left and bottom right into a single centralized menu. Redesigns how 

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by LaurenWags** [comment]
@jhreis where can QA find the expected design for this menu?

**Comment by jamesmudgett** [comment]
![Menu v1](https://user-images.githubusercontent.com/318119/61389558-c2429580-a87e-11e9-9f80-c7908c761aef.png)

**Comment by kjozwiak** [comment]
@LaurenWags https://github.com/brave/brave-ios/issues/1184 has some info on the ordering of the new designed menu as well 👍

**Comment by kjozwiak** [comment]
@anthonypkeane @EyanGoldman as this is a design/UX issue, can you guys go through this on an `iPhone X`? If you've already been dog fooding and feel comfortable with the new design/functionality, can either of you please add the `QA Pass - iPhone X` label? Thanks!

**Comment by LaurenWags** [comment]
* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.16.23)
   - Verified each item under the menu opens and behaves as expected.

![IMG_9E45EAEF979B-1](https://user-images.githubusercontent.com/28145373/61409440-3d706f80-a8b0-11e9-845b-4da68d202983.jpeg)

* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`
   * ensured that each item under the menu opens and behaves as expected
   * ensured the menu's differ when opening the NTP and a tab with a website loaded

![IMG_9776](https://user-images.githubusercontent.com/2602313/61411463-6abf1c80-a8b4-11e9-85e0-84ae21e84408.PNG)

![IMG_9775](https://user-images.githubusercontent.com/2602313/61411464-6abf1c80-a8b4-11e9-9f90-6f259f76235d.PNG)
