### ISSUE TITLE
Bookmarks Pop-out Not Scrollable

### ISSUE THREAD

**Issue by EyanGoldman** [brave/brave-ios#1131]
When going to scroll on the bookmarks pop-out, the bookmarks pop-out begins to move rather than scrolling down

  1. Fill bookmark folder with enough bookmarks to more than fill the view
  2. Attempt to scroll down

Easily reproduced

iPhone X, iOS 12.3.1

Brave Version 19.05.22.15

**Comment by iccub** [comment]
This only happens to me when I scroll down to bottom. Wait a second so the scrolling indicator hides, and then trying to scroll down more(which is impossible since I'm already at the bottom)

Does that happen to you also when you are in middle of bookmarks list or at the top and trying to go down?

**Comment by srirambv** [comment]
Seems similar to #953. #953 is closed but not sure if it made it into any builds nor its part of any closed/active milestone.

**Comment by iccub** [comment]
This is going to be fixed with the new menu design change https://github.com/brave/brave-ios/pull/1058
now bookmarks panel is going to be opened in full screen, no more annoying animations :) closing this
