### ISSUE TITLE
Vimeo not playing on Brave iOS

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1138]
### Description: 
Vimeo not playing on Brave iOS @johnnyryan , specifically this video: https://vimeo.com/337983273

Device: iPhoneX, Brave 1.9.3, iOS 12.3.1, problem occurs with Shields on or off.

Internal Chat: https://bravesoftware.slack.com/archives/C2FQMN4AD/p1560086377017900

I can't reproduce this on my iPhone. I VPN'ed to IE and can't reproduce this way either.

**Comment by anthonypkeane** [comment]
Update

Seems like having fingerprint protection on is causing the issue.

![IMG_5014](https://user-images.githubusercontent.com/7606853/59382176-f07a0600-8d11-11e9-9dd6-b3480ab5e592.PNG)

Fingerprint On
![Fingerprint On](https://user-images.githubusercontent.com/7606853/59382194-f839aa80-8d11-11e9-8a50-75b4905baab3.jpeg)


Fingerprint Off
![Fingerprint Off](https://user-images.githubusercontent.com/7606853/59382232-0ab3e400-8d12-11e9-99e9-a86ee7964f90.jpeg)

**Comment by danishjafri88** [comment]
@anthonypkeane This issue will be present in case Fingerprint Protection is on. Vimeo uses WebGL to draw the player controls. The functions used to draw are very central to fingerprint Protection.

**Comment by jhreis** [comment]
Is this repro on desktop?
