### ISSUE TITLE
Add a , to the Ads & Trackers Blocker number

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1141]
### Description: 
Add a , to the Ads & Trackers Blocker number

![IMG_22E7056F8FBB-1.jpeg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/6911bc54-2995-4ba2-8d91-92d355da969a)

cc @snyderp

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.05.20)
![image](https://user-images.githubusercontent.com/17010094/64444233-a9e24080-d0a1-11e9-9f00-c2aa8e6c292c.png)

Verification **PASSED** on `iPad Air 3rd Generation` with `iOS 13.1` running `1.12 (19.09.07.03)`:

![IMG_0013](https://user-images.githubusercontent.com/2602313/64583901-d24b9280-d360-11e9-87ca-1da54d926072.PNG)

Verification **PASSED** on `iPhone 6s+` using `iOS 12.4.1` running `1.12 (19.09.13.06)`:

![IMG_9911](https://user-images.githubusercontent.com/2602313/64883583-b92b3600-d62d-11e9-9f37-52e65a3d0be2.PNG)
