### ISSUE TITLE
Save login prompt should not be shown when a password manager is set as default

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1142]
### Description: 
In 1.6 we had this option built in to the app where we could set which default password manager should be used in the app. With 1.7 onwards we started to use iOS autofill password manager when 3rd party password manager is installed. This doesn't stop the app from prompting to save using default password manager and not in the 3rd party app set as default

### Steps to Reproduce 
  1. Go to Device Settings -> Password & Accounts -> Autofill Password and set LastPass 
  2. Open Brave and visit a site and login 
  3. Prompts to save login in default app password manager

**Actual result:** 
Save login prompt should not be shown when a password manager is set as default

**Expected result:**
Shouldn't show the option to save in default password manager. If a 3rd party password manager is set it should prompt to switch to the app to store it  (if that is possible) or show an option to not prompt at all.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.9.3

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
I'm not sure this is possible, and iCloud is set as a default regardless. Also, saving passwords is not possible into password managers, so not sure we even want to prevent people from saving them inside Brave.
