### ISSUE TITLE
Install brave 1.5.7 ipa on ios 9.3.5

### ISSUE THREAD

**Issue by sprintel** [brave/brave-ios#1143]
This is actually not an issue but a question. I see that there is an older brave version on github that is not available on app store. How do i install it? I've tried installing it via itunes with no success. I could see the app installing on my ipad screen and then it disappeared. Any help is appreciated. Thank you!

**Comment by srirambv** [comment]
Unfortunately there is no support for devices running anything below iOS 12. The app is only supported on iOS 12 and above. The version you are trying to is really really old and its not recommended to install it as its really far behind in terms of fixes.
