### ISSUE TITLE
Print button is unresponsive for Online PDF bank statements

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#1144]
### Description: 
Print button is unresponsive for Online PDF bank statements

### Steps to Reproduce 
  1. Clean profile 1.9.3
  2. Open online PDF bank statements
  3. Tap on the Action button at the bottom in the iOS device
  4. Tap on "Print" button 

**Note**: Please note this issue is happening only for online PDF bank statements.

**Actual result:** 
The print button becomes unresponsive and it doesn't open the print preview page.

**Expected result:**
Tap on "Print" button should show a print preview page and allow the user to print the PDF

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
1.9.3 (19.05.22.15)

**Device details:** 
iPhone 8 - iOS 12.3.1

**Website problems only:**
- did you check with Brave Shields down? Yes - It did not resolve the issue
- did you check in Safari/Firefox (WkWebView-based browsers)? Yes - works fine in safari

### Additional Information 
cc: @brave/legacy_qa @jhreis
The issue is reported by the community user
https://community.brave.com/t/print-button-unresponsive-on-ipad/64083

**Comment by EvidenceAlpha** [comment]
Any update on this issue ? Thanks

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+ (iOS 12.3.1) running 1.10(19.7.24.20)
   * Verified app doesn't hang when print preview is clicked
   * Verified able to generate print preview for online bank statements
* Verification **PASSED** on `iPad Mini 4 iOS 12.3.1` running `1.10 (19.7.24.20)`
   * ensured that print preview doesn't cause any hangs on several websites and PDF's
   * ensured that print preview doesn't cause any hangs when viewing banking statements
   * ensured printing works
* Verification passed on iPad Pro (iOS 12.3.1) running 1.10(19.7.24.20)
  * Verified app doesn't hang when print preview is clicked
  * Verified able to generate print preview for online bank statements
