### ISSUE TITLE
Browser crashes when device is brought back online with security key plugged in

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1147]
### Description: 
Browser crashes when device is brought back online with security key plugged in

### Steps to Reproduce 
Scenario 1:
  1. Login to the site that supports security keys
  2. Connect the device when website asks for the security key
  3. Put device on offline by disconnecting from wifi
  4. Try to validate using the security key, should give a page not found message
  5. Reconnect to wifi and reload the page and validate using security key
  6. Browser crashes

Scenario 2:
  1. Login to the site that supports security keys
  2. Connect the device when website asks for the security key
  3. Put device on offline by disconnecting from wifi
  4. Try to validate using the security key, should give a page not found message
  5. Reconnect to wifi validate using security key
  6. Browser crashes

Scenario 3
  1. Login to the site that supports security keys
  2. Put device on offline by disconnecting from wifi
  3. Connect the security key and try to validate, nothing happens
  4. Bring device back online, remove the security key
  5. Connect the security key again and try to authenticate, browser crashes
https://bravesoftware.slack.com/archives/CKH2AUS6S/p1560375749009400

Scenario 4:
  1. Login to the site that supports security keys
  2. Use security key to authenticate session
  3. Logout of the site and remove the security key
  4. Relogin to the website again
  5. Disconnect from network
  6. Connect security key to device and try to authenticate
  7. Bring device back online, browser crashes
https://bravesoftware.slack.com/archives/CKH2AUS6S/p1560430694010100

**Actual result:** 
Browser crash

**Expected result:**
No browser crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Device details:** 
Scenario 1, 2, 3 : 
iPhone 7+ (iOS 12.3.1)

Scenario 4: 
iPad Pro (iOS 12.2)

**Comment by kjozwiak** [comment]
@tomlowenthal @jumde basically same question as https://github.com/brave/brave-ios/issues/1157#issuecomment-626991138. Are we expecting further development for WebAuth down the road? Seeing these type of crashes pretty often. Granted, I'm not really sure how many users are using YubiKeys.

**Comment by jumde** [comment]
Tried:

1. Navigating to demo.yubico.com/u2f
2. Start the webauthn workflow
3. Plug in the security key
4. Turned on airplane mode and turned off wifi
5. On completion - error
6. Turned on and refresh
7. Start the workflow
8. Completes successfully.

@srirambv @kjozwiak - Let me know if I'm missing something.

**Comment by kjozwiak** [comment]
Closing as we've deprecated the `Yubikey` SDK in favour of the `WKWebView` SDK as per https://github.com/brave/brave-ios/issues/4473. QA went through verifications via https://github.com/brave/brave-ios/issues/4473#issuecomment-1032291511, https://github.com/brave/brave-ios/issues/4473#issuecomment-1033102239 & https://github.com/brave/brave-ios/issues/4473#issuecomment-1033240109 and couldn't reproduce the crashes using the `WKWebView` SDK.
