### ISSUE TITLE
Unsupported browser message when security key is connected

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1148]
### Description: 
Unsupported browser message when security key is connected

### Steps to Reproduce 
  1. Visit a page that supports security key authentication
  2. Connect the security key when it asks to authenticate
  3. Disconnect device from network
  4. Validate using the security key, page load fails
  5. With security key connected reload the page
  6. Page shows security key unsupported 

**Actual result:** 
Unsupported browser message when security key is connected

**Expected result:**
Should just ask for security key authentication again 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Device details:** 
iPhone 7+ (iOS 12.3.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jumde** [comment]
this happens because the `hasOnlySecureContent` state was incorrect in the `decidePolicyFor navigationAction`. We should be checking this in the `decidePolicyFor navigationResponse` instead.

**Comment by kjozwiak** [comment]
Removing from the `1.10` as per earlier discussion with @jhreis 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6s+ iOS 12.4` using `1.11.1 (19.08.13.17)`

* Using `github.com`, ensured that the case mentioned under https://github.com/brave/brave-ios/issues/1148#issue-455430184 worked without issues.

Verification **PASSED** on `iPad 5th Gen iOS 12.3.1` using `1.11.1 (19.08.13.17)`
   * Using `github.com`, ensured that the case mentioned under https://github.com/brave/brave-ios/issues/1148#issue-455430184 worked without issues.
