### ISSUE TITLE
History navigation is lost when you move back to new tab 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1149]
### Description: 
History navigation is lost when you move back to new tab 

### Steps to Reproduce 
  1. Open a new tab
  2. Visit 4-5 different sites in the same tab
  3. Go back to a previous page from history
  4. Long press on the back button to view history of navigation
  5. Go back to home page, all tab history is lost

**Actual result:** 
https://youtu.be/H98MOw0pP_I

**Expected result:**
Should be able to get back to tab history when navigated back to new tab

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Device details:** 
All mobile

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information  
cc: @jamesmudgett @jhreis @iccub

**Comment by iccub** [comment]
This is not relevant anymore, we backtracked from the removal of forward button, closing
