### ISSUE TITLE
Authentication doesn't work when security key is connected and disconnected quickly

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1150]
### Description: 
Authentication doesn't work when security key is connected and disconnected quickly

### Steps to Reproduce 
  1. Login to a site that supports security key
  2. Wait for the message to use security key
  3. Quickly connect the security key and disconnect
  4. Site doesn't authenticate your account
  5. Reconnect the security key and try to authenticate, account never authenticates
https://bravesoftware.slack.com/archives/CKH2AUS6S/p1560432037010500

**Actual result:** 
Authentication doesn't work when security key is connected and disconnected quickly

**Expected result:**
Should be able to authenticate to the site

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Device details:** 
iPad Pro running 12.2 and iPhone running 12.3.1 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
Removing from the `1.10` as per earlier discussion with @jhreis 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6s+ iOS 12.4` using `1.11.1 (19.08.13.17)`

* Went through the case outlined under https://github.com/brave/brave-ios/issues/1150#issue-455737666 using `github.com` and ensured I could still authenticate after disconnecting/reconnecting the Yubico key several times quickly.

Verification **PASSED** on `iPad 5th Gen iOS 12.3.1` using `1.11.1 (19.08.13.17)`
   * Went through the case outlined under https://github.com/brave/brave-ios/issues/1150#issue-455737666 using `github.com` and ensured I could still authenticate after disconnecting/reconnecting the Yubico key several times quickly.
