### ISSUE TITLE
UI to avoid double-tap on security keys when unplugged

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1153]
Hardware security keys generally take some time to change state where the tap can be accepted, we should think about a pop-over similar to one on desktop to avoid double taps. 

<img width="475" alt="Screen Shot 2019-06-13 at 2 43 51 PM" src="https://user-images.githubusercontent.com/1903815/59469456-b3814280-8de9-11e9-9deb-64d3eadc04eb.png">

### Test Plan:
Specified here: https://github.com/brave/brave-ios/pull/1362

**Comment by LaurenWags** [comment]
Verified passed with iPad 5th Gen using 1.11.1 (19.08.13.17)
   - Verified test plan from https://github.com/brave/brave-ios/pull/1362
   - Dialog does not display URL, this is being tracked here: https://github.com/brave/brave-ios/issues/1335#issuecomment-521000552
