### ISSUE TITLE
Provide an option for users to not show in site prompts

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1155]
### Description: 
Provide an option in the shield menu at the bottom to hide website prompts to open a given website in a native app.

Test: Block in-site prompts
Default = on so these notifications are not shown

Alternative position could be in the settings @jamesmudgett to confirm which is best

Internal Chat: https://bravesoftware.slack.com/archives/C0816QH3R/p1560698822132300

https://github.com/brave/browser-android-tabs/issues/1711

![Screenshot_20190616-214547.png](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/dc930716-72ae-43c1-9eaa-109cbeb8bc38)

**Comment by jhreis** [comment]
Also needs investigation on how to handle these. They may require a website case-by-case basis to handle them, unless they are using some super standard UI.

**Comment by kylehickinson** [comment]
Similar: #1450
