### ISSUE TITLE
Pressing email link give code in the subject, not the link

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1156]
### Description: 
A user was on a website and wanted to share that link with me via email. 

The opened the share sheet and tapped on email. 
instead of the email address populating the Subject header of the email, they got (see screenshot)

### Steps to Reproduce 
  1. Open a website page
  2. Share the page vis email
 

**Actual result:** 
![Screen Shot 2019-06-17 at 10.38.06 AM.png](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/7a7b6954-1787-451a-aedc-4f392e730af6)

**Expected result:**
Links should be easily shared 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent

**Brave Version:** 
1.9.3

**Device details:** 
iPhone 8, 12.2

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
Is this repro on other links, or a common email issue?

**Comment by anthonypkeane** [comment]
Seems to be fixed in 1.11

**Comment by jhreis** [comment]
Marking as fixed, and closing. Feel free to refile if you see issue again.
