### ISSUE TITLE
Add support for U2F/WebAuthn hardware security keys on iOS

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1159]
### Test Plan

Specified here: https://github.com/brave/brave-ios/pull/1158

**Comment by kjozwiak** [comment]
Removing from the `1.10` as per earlier discussion with @jhreis 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6s+ iOS 12.4` using `1.11.1 (19.08.13.17)`

* Went through https://github.com/brave/brave-ios/pull/1158 and ensured the following websites worked as expected:
   * `demo.yubico.com/u2f` --> **PASSED**
   * `webauthn.io` --> **PASSED**
   * `webauthntest.azurewebsites.net` --> **PASSED**
   * `mdp.github.io/u2fdemo` --> **PASSED**
   * `u2fdemo.hypersecu.com` --> **PASSED**
   * `github.com` --> **PASSED**
   * `login.gov` --> **PASSED**

Verification **PASSED** on `iPad 5th gen iOS 12.3.1` using `1.11.1 (19.08.13.17)`
* Went through https://github.com/brave/brave-ios/pull/1158 and ensured the following websites worked as expected:
   * `demo.yubico.com/u2f` --> **PASSED**
   * `webauthn.io` --> **PASSED**
   * `webauthntest.azurewebsites.net` --> **PASSED**
   * `mdp.github.io/u2fdemo` --> **PASSED**
   * `u2fdemo.hypersecu.com` --> **PASSED**
   * `github.com` --> **PASSED**
   * `login.gov` --> **PASSED**
