### ISSUE TITLE
Add total bookmark count for bookmark folders

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1160]
### Description: 
Currently there is no way to know how many bookmarks are sync'd which are part of a bookmark folder. Add total bookmark count for bookmark folders so that it makes it easy to see if the entire list of bookmarks is sync'd or not. Android has the total bookmark count by default for all folders which makes it easy to track the number of bookmarks that is syncd and the remaining ones

**Actual result:** 
No real way to know if the entire bookmark list is sync'd unless you sit and check manually 

**Expected result:**
Easier way to know if everything is sync'd or yet to sync

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
All

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
cc: @anthonypkeane

**Comment by jhreis** [comment]
cc'ing @jamesmudgett thoughts? Could add total on right side. We do present total if you long-press a folder already.

I'm not really sure how useful a count is on average, and again, information is there (but maybe a bit hidden).

**Comment by anthonypkeane** [comment]
Sorry, not doing this one right now.
