### ISSUE TITLE
Clicking link in incognito will not open applications

### ISSUE THREAD

**Issue by EyanGoldman** [brave/brave-ios#1161]
When a user is in incognito mode, if they click on a link that tries to redirect to an external application open, it will block it and open the website instead.

**Comment by tildelowengrimm** [comment]
This should be a configurable setting. Deliberately using private mode to ensure that you don't open other apps should be supported.

**Comment by iccub** [comment]
Now we always prompt the user before opening an external application.
Ref: https://github.com/brave/brave-ios/issues/551
