### ISSUE TITLE
Security keys don't work with login.gov

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1163]
### Description: 
Adding security keys on login.gov fails with errors.

### Steps to Reproduce 
  1. Navigate to login.gov and try to add a security key
  2. Fails!

**Actual result:** 
Fails

**Expected result:**
Should be successful

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.10

**Comment by kjozwiak** [comment]
@jumde mind quickly going through the verification to confirm that this has been fixed? I don't have an account on `login.gov` and need US ID which I don't have. @LaurenWags not sure if you have an account either. If we can't get someone to QA this with a `login.gov` account, we'll need to label it as `QA/No`.

**Comment by jumde** [comment]
@kjozwiak - DM'ed you the test credentials for this domain.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6s+ iOS 12.4` using `1.11.1 (19.08.13.17)`

![IMG_9874](https://user-images.githubusercontent.com/2602313/62987166-7f87c500-be0c-11e9-9a8c-150f55672e01.PNG)
<img width="605" alt="Screen Shot 2019-08-13 at 8 54 00 PM" src="https://user-images.githubusercontent.com/2602313/62987174-83b3e280-be0c-11e9-86aa-2faaedd6eb56.png">

Verification **PASSED** on `iPad 5th Gen iOS 12.3.1` using `1.11.1 (19.08.13.17)`

![IMG_C7619537B32E-1](https://user-images.githubusercontent.com/28145373/63040910-8f4aec00-be94-11e9-8726-4373d49fc2ce.jpeg)
![IMG_879BEDB078C7-1](https://user-images.githubusercontent.com/28145373/63040916-93770980-be94-11e9-8015-43efcdbf956b.jpeg)
