### ISSUE TITLE
Security keys don't work with dropbox.com

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1164]
### Description: 
Adding security keys on dropbox.com fails with errors.

### Steps to Reproduce 
  1. Navigate to dropbox.com and try to add a security key
  2. Fails!

**Actual result:** 
Fails

**Expected result:**
Should be successful

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.10

**Comment by jumde** [comment]
Waiting for response from dropbox

**Comment by iccub** [comment]
We removed yubico sdk in favor of built in webkit webauth api.
This will be reopened if the problem still occurs.
