### ISSUE TITLE
Add ability to go back from nested folder in bookmarks menu.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1165]
### Steps to Reproduce 
  1. Create few nested folder
  2. Go to the deepest folder
  3. Try to dismiss bookmarks panel.

**Actual result:** 
You have to go back up to the root folder to do so.

**Expected result:**
Should be able to do that at each nesting level.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+ (iOS 12.3.1) running 1.10(19.07.08.19)
  - Verified tap on `Done` take back from nested bookmarks folder to tab view
* Verification **PASSED** on `iPad Mini 4 running iOS 12.3.1` using `1.10 (19.07.10.17)`
  * Ensured that taping on `Done` closes the Bookmark window while in nested folders

- Verification passed on iPhone 8 running iOS 12.3.1 using 1.10(19.07.16.23)
   - Verified tap on `Done` take back from nested bookmarks folder to tab view
