### ISSUE TITLE
rpID can be equal or shorter as long as there is still a host

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1167]
Update `validateRPID` to handle these cases.

## Test Plan

1. Navigate to https://webauthntest.azurewebsites.net/
2. Try creating a credential with rp info, suffix to this domain and foo.com. 
3. Both should fail with a Security Error

**Comment by kjozwiak** [comment]
Removing from the `1.10` as per earlier discussion with @jhreis 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6s+ iOS 12.4` using `1.11.1 (19.08.13.17)`

* ensured that setting `RP info` as `Suffix to this domain` fails with `Error: SecurityError: Error registering your security key, please try again.`.

![IMG_FA1DB1B8C6D3-1](https://user-images.githubusercontent.com/2602313/62991404-810db900-be1d-11e9-9b59-e45b83b6c784.jpeg)

Verification **PASSED** on `iPad 5th Gen iOS 12.3.1` using `1.11.1 (19.08.13.17)`
* ensured that setting `RP info` as `Suffix to this domain` or `foo.com` fails with `ERROR: SecurityError: Error registering your security key, please try again.`.
![IMG_0408](https://user-images.githubusercontent.com/28145373/63042019-24e77b00-be97-11e9-9724-b627514f6862.PNG)
