### ISSUE TITLE
Bookmarks bottom toolbar UI issues.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1170]
1. Toolbar isn't extended to safe area
2. There is no shadow line at the bottom toolbar

See screenshot below
![Image from iOS](https://user-images.githubusercontent.com/6950387/59860193-864f0a00-937e-11e9-962c-971c7e746070.png)

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPad Mini 4 running iOS 12.3.1` using `1.10 (19.07.10.17)`

<img width="705" alt="Screen Shot 2019-07-11 at 9 41 39 PM" src="https://user-images.githubusercontent.com/2602313/61096187-aecd9f80-a424-11e9-9216-e8e457609c3f.png">

* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.10.17)`

![IMG_9754](https://user-images.githubusercontent.com/2602313/61096258-e2102e80-a424-11e9-8507-7d0e4d326ef1.PNG)

- Verification passed on iPhone 8 running iOS 12.3.1 using 1.10(19.07.16.23)
![IMG_0079](https://user-images.githubusercontent.com/38657976/61394372-92c47500-a8e0-11e9-9731-2a1c52bec92f.PNG)

**Comment by kjozwiak** [comment]
@anthonypkeane @EyanGoldman as this is a design/UX issue, can you guys go through this on an `iPhone X`? If you've already been dog fooding and feel comfortable with the new design/functionality, can either of you please add the `QA Pass - iPhone X` label? Thanks!
