### ISSUE TITLE
FIDO/FIDO2 APIs fail on iPad Pro

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1176]
### Description: 
FIDO/FIDO2 APIs should work with iPad Pro.

### Steps to Reproduce 
  1. Navigate to demo.yubico.com/u2f
  2. Initiate the U2F workflow
  3. Fails

**Actual result:** 
Fails

**Expected result:**
Should succeed.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Device details:** 
iPad Pro

**Comment by jumde** [comment]
Re-opening after discussion with Yubico, more details here: https://bravesoftware.slack.com/archives/CJMAD25L7/p1565026606102600

**Comment by iccub** [comment]
We removed yubico sdk in favor of built in webkit webauth api.
This will be reopened if the problem still occurs.
