### ISSUE TITLE
New Menu Order Change

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#1184]
### Description: 

Adjust ordering of bottom right new menu

### Steps to Reproduce 
  1. Click bottom right menu
  2. See ordering

**Actual result:** 
 
<img width="218" alt="Screen Shot of bottom right current menu order" src="https://user-images.githubusercontent.com/2781690/60107108-56b05100-9734-11e9-902e-905fb139342c.png">

**Expected result:**

1. Settings
2. History
3. Bookmarks
4. Add to
5. Share

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100%

**Brave Version:** 

1.10 beta

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+(iOS 12.3.1) running 1.10(19.07.08.19)
  - On a page

    ![image](https://user-images.githubusercontent.com/17010094/60986187-e517fb80-a30c-11e9-8e73-5164014107e9.png)

  - On new tab

   ![image](https://user-images.githubusercontent.com/17010094/60986128-d03b6800-a30c-11e9-9774-d5c1ae23b0ef.png)

* Verification **PASSED** on `iPad Mini 4 running iOS 12.3.1` using `1.10 (19.07.10.17)`

- Verification passed on iPhone 8 running iOS 12.3.1 using 1.10(19.07.16.23)
  - Verified the normal tab and PT's order is same in both tabs
    on a page
    
![image](https://user-images.githubusercontent.com/38657976/61393031-bfc35880-a8dd-11e9-82bc-cd9c955a6783.png)
    on a new tab:
    
![image](https://user-images.githubusercontent.com/38657976/61393080-d4075580-a8dd-11e9-8720-f7db6c271f11.png)

**Comment by kjozwiak** [comment]
@anthonypkeane @EyanGoldman as this is a design/UX issue, can you guys go through this on an `iPhone X`? If you've already been dog fooding and feel comfortable with the new design/functionality, can either of you please add the `QA Pass - iPhone X` label? Thanks!
