### ISSUE TITLE
Crash when Turning Shields Off

### ISSUE THREAD

**Issue by danishjafri88** [brave/brave-ios#1187]
### Description: 

The shield off icon are missing from assets after the recent cleanup. To test switch off shields and it crashes.

Regression from #1171

### Steps to Reproduce 
  1. Disable Shields
  2. Observe crash

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+ (iOS 12.3.1) running 1.10(19.07.08.19)
  - Verified no crash when shields disabled on a webpage
  - Verified no crash when shields disabled on a pdf document
  - Verified no crash when shields disabled on an image loaded in a tab 
* Verification **PASSED** on `iPad Mini 4 running iOS 12.3.1` using `1.10 (19.07.10.17)`
  * ensured that you can disable shields on webpages, pdf's, images
  * ensured that toggling shield settings didn't cause any crashes

- Verification passed on iPhone 8 running iOS 12.3.1 using 1.10(19.07.16.23)
  - Verified no crash when shields disabled on a webpage
  - Verified no crash when shields disabled on a pdf document
  - Verified no crash when shields disabled on an image loaded in a tab
  - Verified no crash when shields disabled on YT/Twitch/embedded video 
  - Verified on both normal tab and PT's
