### ISSUE TITLE
Youtube Video Rotation Issues

### ISSUE THREAD

**Issue by EyanGoldman** [brave/brave-ios#1189]
### Description: 
If a video is played without going into full screen mode, then the device is rotates, the video will maintain the same format before the rotation (too small or too big) after the device has rotate

### Steps to Reproduce 
  1. Play a video on youtube.com without going into full screen in vertical mode
  2. Rotate the device
  3. Keep Rotating to see all the different variants

**Actual result:** 
Correct Fit:
![Screen Shot 2019-06-25 at 12.58.48 PM.png](https://images.zenhubusercontent.com/5cf5a25c96db72707b4b2784/02ea8916-ed85-4c8b-9235-0ad9d517a8f6)
Too Small:
![Screen Shot 2019-06-25 at 12.59.05 PM.png](https://images.zenhubusercontent.com/5cf5a25c96db72707b4b2784/26556858-91a7-4af1-aff9-9e659759e75f)
Too Large:
![Screen Shot 2019-06-25 at 12.59.45 PM.png](https://images.zenhubusercontent.com/5cf5a25c96db72707b4b2784/51d4548d-5032-451b-a852-6db91500a8a3)

**Expected result:**
The size of the video should match the size of the video player

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.9.3

**Device details:** 

iPhone X, iOS 13

### Additional Information 
Does not work with Shields down
Works perfectly on Safari

**Comment by srirambv** [comment]
@Brandon-T The video frame in portrait mode is retained for a second before it enlarges to landscape mode is that expected?

**Comment by srirambv** [comment]
seeing the momentary freeze on rotation https://youtu.be/oy3OyIGu7vU

**Comment by kjozwiak** [comment]
> @Brandon-T The video frame in portrait mode is retained for a second before it enlarges to landscape mode is that expected?


Seeing the same thing @srirambv mentioned above on my iPhone 6s+. I didn't get any freezing, but there's a small delay before the video enlarges. Probably not the end of the world but it definitely could be smoother.

**Comment by srirambv** [comment]
Seeing the same momentary freeze on iPad as well while orientation is changed.

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+ (iOS 12.3.1) running 1.10(19.7.26.15)
  * Verified video frame doesn't get stuck when device orientation is changed
  * Logged #1302 as follow up 
* Verification passed on iPad Pro (iOS 12.3.1) running 1.10(19.7.26.15)
  * Verified video frame doesn't get stuck when device orientation is changed
