### ISSUE TITLE
HTTPSE Setting Does Not Change Both HTTP/S Versions

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#1192]
### Description: 

Infinite loop when visiting digg.com with HTTPSE on. Unable to turn off to load website.
Related: https://github.com/brave/brave-ios/issues/688

### Steps to Reproduce 
  1. Turn off global HTTPSE
  1. Visit [http website](http://https-everywhere.badssl.com/)
  2. Turn on HTTPSE for current domain
  3. Site upgraded
  1. Observe that HTTPSE is _not_ set on the `https://` version

**Actual result:** 

HTTPSE setting is not scheme independent.

**Expected result:**

Changing HTTPSE setting for an `http` or `https` version of a website, should impact both `http` and `https` versions.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

1.9.3

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`
  * Went through the STR described under https://github.com/brave/brave-ios/issues/1192#issue-461187980 and ensured that HTTPSE stayed enabled via the `Brave Panel`
  * Ensured that disabling HTTPSE loads `digg.com`

* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.16.23)
   - Verified STR from description
   - Verified disabling HTTPSE allows digg.com to load
   - Logged follow up issue #1271 to fix digg.com not loading with HTTPSE enabled
