### ISSUE TITLE
Implement social media blocking on iOS

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1193]
Similar to desktop we should have options to enable social media blocking on iOS

<img width="731" alt="Screen Shot 2019-06-27 at 10 17 01 AM" src="https://user-images.githubusercontent.com/1903815/60286709-ee44a980-98c4-11e9-8ea9-51d9bcf3abc5.png">

**Comment by iccub** [comment]
closing as stale, we may revisit it some time
