### ISSUE TITLE
Center Brave Shields Caret

### ISSUE THREAD

**Issue by EyanGoldman** [brave/brave-ios#1195]
### Description: 
When the shields icon is clicked in the URL bar, the which protrudes from the menu is not centered on the lion. 

### Steps to Reproduce 
  1. Click on shields icon

**Actual result:** 
![Image from iOS (8).png](https://images.zenhubusercontent.com/5cf5a25c96db72707b4b2784/ef6fdddc-9dc3-4e42-b9ea-03a19d66f0d0)

**Expected result:**
Should be centered

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Every time

**Brave Version:** 
1.10

**Device details:** 
iPhone X

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+ running 

![File](https://user-images.githubusercontent.com/17010094/60971361-fc95bb00-a2f1-11e9-8ee9-eac273086655.jpg)

* Verification **PASSED** on `iPad Mini 4 running iOS 12.3.1` using `1.10 (19.07.10.17)`

<img width="351" alt="Screen Shot 2019-07-11 at 8 20 17 PM" src="https://user-images.githubusercontent.com/2602313/61093609-56dd6b80-a419-11e9-8f84-03fc7512080b.png">

- Verification passed on iPhone 8 running iOS 12.3.1 using 1.10(19.07.16.23)
![IMG_0077](https://user-images.githubusercontent.com/38657976/61394076-fef2a900-a8df-11e9-9fe1-587ead710c5b.PNG)

**Comment by kjozwiak** [comment]
@anthonypkeane @EyanGoldman as this is a design/UX issue, can you guys go through this on an iPhone X? If you've already been dog fooding and feel comfortable with the new design/functionality, can either of you please add the QA Pass - iPhone X label? Thanks!
