### ISSUE TITLE
In settings, change "BRAVE SHIELD DEFAULTS" to "SHIELDS DEFAULTS"

### ISSUE THREAD

**Issue by EyanGoldman** [brave/brave-ios#1196]
### Description: 
Consistent with Brave branding, the product has an "s" at the end of shield. Should be reflected in the settings menu

### Steps to Reproduce 
  1. Navigate to settings
  2. Menu section titled "BRAVE SHIELD DEFAULTS"
  3.

**Actual result:** 
Says "BRAVE SHIELD DEFAULTS"

**Expected result:**
Should say "SHIELDS DEFAULTS"

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Every time

**Brave Version:** 
1.10

**Comment by chickdan** [comment]
I can work on this! I noticed on the desktop version the string is now simply `Shields`, should iOS match?

**Comment by chickdan** [comment]
There are a few others that don't match: 
Other Settings -> Sync
Display & Brightness -> Appearance

Privacy and security is one section on desktop but two sections on iOS, should these be combined?

**Comment by iccub** [comment]
cc @anthonypkeane to confirm we are still making this change and what copy to use

**Comment by anthonypkeane** [comment]
Please change the "BRAVE SHIELD DEFAULTS" to "SHIELDS DEFAULTS" for now.

Thanks

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.3.1 running 1.15(20.01.07.17)
![image](https://user-images.githubusercontent.com/17010094/72280672-df2a0c80-3606-11ea-8e0c-6007740fa2cd.png)

Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.01.07.17)
![image](https://user-images.githubusercontent.com/17010094/72280660-d3d6e100-3606-11ea-9caf-ae7ba36208f0.png)

Verification passed on iPhone 6 with iOS 12.4.4 running 1.15(20.01.07.17)
![image](https://user-images.githubusercontent.com/17010094/72280628-c4579800-3606-11ea-84ae-f8de5333834f.png)

Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.01.07.17)
![image](https://user-images.githubusercontent.com/17010094/72280647-cf122d00-3606-11ea-907b-d85857920980.png)

Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.01.07.17)
![image](https://user-images.githubusercontent.com/17010094/72280638-ca4d7900-3606-11ea-927f-a06d21594004.png)
