### ISSUE TITLE
Passcode UI not resetting on resume to foreground from background

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#1203]
### Steps to Reproduce 
1. Have passcode set.
2. Restart application.
3. Authenticate with passcode.
4. Go to private browsing.
5. Search for anything.. Stackoverflow for example.
6. Minimize app to background
7. Resume app to foreground
7. It prompts to authenticate

**Actual result:** 
It prompts to authenticate but authentication is already filled in from the first time we authenticated.

**Expected result:**
It should prompt without passcode being pre-filled.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100% of the time.

**Brave Version:** 
1.9.3 (1.2.3.4) - Beta

**Device details:** 
iPhone X (12.2)

**Website problems only:**
- did you check with Brave Shields down? - Yes
- did you check in Safari/Firefox (WkWebView-based browsers)?  - Yes

### Additional Information 
Only happens on our "Beta" build (development repository)
![Untitled-1](https://user-images.githubusercontent.com/1530031/60522002-39d8c800-9cb6-11e9-8a16-d5c1328296db.gif)

GIF is quite fast (I had to compress a video into GIF) but as you can see, the passcode field is pre-filled when put back into foreground.

**Comment by kjozwiak** [comment]
Reproduced this several times on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`

**Comment by kjozwiak** [comment]
@jhreis would this be removed from the 1.10 release under ZenHub?

**Comment by Brandon-T** [comment]
@kjozwiak This one has a fix for it. I'm just waiting for it to be verified and merged. Glad I wasn't the only one to reproduce this bug. I will rebase the fix, address feedback, and then I guess it should be okay to merge considering it's only one line of code.

The weird part is that now I'm not able to reproduce it as often on the live build and beta. Before it would happen to me every single time on iPhone X.. Now it happens intermittently. With the fix, it never happens.
