### ISSUE TITLE
Revert change of putting reload button on bottom toolbar

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1207]
Product team has decided to revert that change.
So the only change regarding revamped address bar is to embed shields button onto address bar(same with Rewards button in the future)

**Comment by LaurenWags** [comment]
* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.12.14)

![ipadURLbar](https://user-images.githubusercontent.com/28145373/61157363-f3f4de80-a4c3-11e9-8171-4036195bb6e3.png)

* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`

<img width="587" alt="Screen Shot 2019-07-18 at 10 00 23 AM" src="https://user-images.githubusercontent.com/2602313/61463677-ecf62200-a942-11e9-82b1-dc74cef1dc39.png">

<img width="587" alt="Screen Shot 2019-07-18 at 10 00 12 AM" src="https://user-images.githubusercontent.com/2602313/61463678-ecf62200-a942-11e9-90c0-ec6a815f5074.png">

<img width="1088" alt="Screen Shot 2019-07-18 at 10 02 27 AM" src="https://user-images.githubusercontent.com/2602313/61463816-30e92700-a943-11e9-80d3-81b91364e1a2.png">

<img width="1013" alt="Screen Shot 2019-07-18 at 10 02 12 AM" src="https://user-images.githubusercontent.com/2602313/61463818-30e92700-a943-11e9-95c2-6fdd5717f797.png">

**Comment by kjozwiak** [comment]
@anthonypkeane @EyanGoldman as this is a design/UX issue, can you guys go through this on an `iPhone X`? If you've already been dog fooding and feel comfortable with the new design/functionality, can either of you please add the `QA Pass - iPhone X` label? Thanks!
