### ISSUE TITLE
Passcode doesn't work when app moves from background to foreground

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1210]
### Description: 
On moving the app from background to foreground with passcode, entering the passcode doesn't do anything. 

### Steps to Reproduce 
  1. Setup passcode for your app
  2. Close the app and open it up again
  3. Re-opening the app asks for passcode
  4. Move the app to background by navigating to the home screen
  5. Open the app again
  6. Try entering the passcode

**Actual result:** 
Cannot enter the passcode. The app does not unlock. 

**Expected result:**
Should work and passcode should unlock the app.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
v1.10 (19.07.03.17)

**Device details:** 
iPhone SE

**Comment by Brandon-T** [comment]
Can you describe what it means "Doesn't work"? What happens at step 6? Does the passcode screen show up? Does it show up and not validate properly or?

**Comment by jumde** [comment]
Updated, let me know if its still not clear. Thanks!

**Comment by jhreis** [comment]
Is this still an issue @jumde ?

**Comment by iccub** [comment]
Seems to be working now.
