### ISSUE TITLE
URL bar over-extends when typing new search/address

### ISSUE THREAD

**Issue by EyanGoldman** [brave/brave-ios#1212]
### Description: 
Sometimes when typing in a new search or web address on a new tab, the url bar becomes too long and moves the "cancel" button off the device (to the right) this means the only way to leave the search is to quit the app and come back or try to press the tiny remainder of the "cancel" button

### Steps to Reproduce 
  1. Click on url bar

**Actual result:** 
![Image from iOS.jpg](https://images.zenhubusercontent.com/5cf5a25c96db72707b4b2784/b0c3d88c-0d65-43d9-a952-043e7c36de9d)

**Expected result:**
Cancel button should be totally visible

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Infrequent Issue

**Brave Version:** 
1.10(19.07.05.21)

**Device details:** 
iPhone X, iOS 13 Beta

**Comment by iccub** [comment]
I don't see this anymore, closing.

**Comment by srirambv** [comment]
* Verification passed on iPhone XR with iOS 13.1 running 1.12(19.09.06.17)
* Verification **PASSED** on both `iPad Air 3rd Generation iOS 13.1` running `1.12 (19.09.10.18)`
* Verification **PASSED** on `iPhone 6s+` using `iOS 12.4.1` running `1.12 (19.09.13.06)`:
