### ISSUE TITLE
Unclickable links

### ISSUE THREAD

**Issue by EyanGoldman** [brave/brave-ios#1213]
### Description: 
Links are either not being recognized as links or when clicked, they are not being loaded. This issue occurs with both shields on and off

### Steps to Reproduce 
  1. Google Search a term
  2. No links are clickable

**Actual result:** 
Video Link: https://drive.google.com/file/d/1xnMA8b_d6acAcapR6Urf1D41HhFK8j8T/view?usp=sharing

**Expected result:**
Links should be clickable

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Not often

**Brave Version:** 
1.10(19.07.05.21)

**Device details:** 
iPhone X, iOS 13 beta

**Website problems only:**
Problem persisted with shields up and down

**Comment by EyanGoldman** [comment]
May be related to #1114 however, this also persisted when Shields were down

**Comment by iccub** [comment]
Can't repro anymore on latest beta, closing

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.06.15)
* Verified search term on Google open correctly on both normal and private tabs
* Verified search term on Startpage open correctly in a new normal/private tab

Verification **PASSED** on `iPad Air 3rd Generation` with `iOS 13.1` running `1.12 (19.09.07.03)`:

* Verified search term on on the following search engines open as expected on both normal and PB tabs
   * Google, DDG, Bing, Qwant and Startpage

Verification passed on iPhone 7+ with iOS 12.4.1 running 1.12(19.09.13.06)
* Verified search term on Google open correctly on both normal and private tabs
* Verified search term on Startpage open correctly in a new normal/private tab
