### ISSUE TITLE
Open in a private tab from bookmarks/history launches it in a new tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1216]
### Description: 
Open in a private tab from bookmarks launches it in a new tab

### Steps to Reproduce 
  1. Clean install 1.10(19.07.08.19)
  2. Visit a site and add it as a bookmark
  3. Open bookmarks, Long press on the new bookmark and open in a new tab
  4. Link opens in a normal tab instead of private tab

**Actual result:** 
Open in a private tab from bookmarks launches it in a new tab

**Expected result:**
Link should open in private tab

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.10(19.07.08.19)

**Device details:** 
iPhone 7+ (iOS 12.3.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Link opened from a page opens in private tab as expected. Issue only from bookmarks and history

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPad Mini 4 running iOS 12.3.1` using `1.10 (19.07.10.17)`
   * ensured that links from Bookmarks & History are being opened in PB
* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`
   * ensured that links from Bookmarks & History are being opened in PB
