### ISSUE TITLE
PINS don't work with YubiKeys

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1217]
Set a PIN on a yubikey, and try to authenticate with webauthn.io. Does not work on current releases.

## Test Plan

Specified here: https://github.com/brave/brave-ios/pull/1303

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+ running 1.12
  * Verified `Enter PIN` is prompted when the device is connected
  * Verified entering correct pin brings up browser prompt to touch the key
  * Verified entering the wrong pin fails to validate the key
  * Verified entering correct pin and authorising the key, opening a new tab with key connected doesn't prompt for pin

* Verification passed on iPad 5th Gen using 1.11.1 (19.08.13.17)
  * Verified test plan from https://github.com/brave/brave-ios/pull/1303
  * Verified `Enter PIN` is prompted when the device is connected
  * Verified entering correct pin brings up browser prompt to touch the key
  * Verified entering the wrong pin fails to validate the key

![IMG_A8D0CD594FDD-1](https://user-images.githubusercontent.com/28145373/63032670-43904680-be84-11e9-93e8-5773ee5e4864.jpeg)

**Comment by eparkko-lab** [comment]
@jumde 

**Brave Version:**
1.11.1 (19.08.13.17)

**Device details:**
iPhone Xr (12.3.1)

I noticed that PIN prompts are only required on the first time the security key is inserted and is not required for every get and create request.   If I perform 2 consecutive create requests without removing the key from the phone then I will only need to do the PIN prompt once. 

Steps: 

- Set PIN on YubiKey

- On https://webauthntest.azurewebsites.net/
  - Create a credential for User Bob
   - Insert Key
   - Type in PIN
   - Touch key to authenticate
   - Leave key inserted
   - Create a credential for User Alice
   - Touch key to authenticate

Notice that the 2nd request did not require the user to enter the PIN. This behavior is different from other browsers.
