### ISSUE TITLE
README should link to Brave Community instead of Discord

### ISSUE THREAD

**Issue by braker1nine** [brave/brave-ios#1224]
Apologies for not using the template, but as this isn't an actual code/app issue it didn't seem necessary.

The Discord server is no longer active, so the README should probably stop linking there and link to the Brave Community site. Probably could also link to the [iOS contribution](https://community.brave.com/c/contributing/contributing-ios) section as well, but it's not the most active place so 🤷‍♂️

**Comment by jhreis** [comment]
Thanks for bringing this up. We'll get it fixed.
