### ISSUE TITLE
Implement sync warn message 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1225]
Same as https://github.com/brave/brave-browser/issues/4132 and https://github.com/brave/browser-android-tabs/issues/1475

@anthonypkeane @jhreis this should be part of 1.10 as the text changes went with Android in the last release

**Comment by anthonypkeane** [comment]
Not a blocker for this release, can pick it up on the next as needed. Thanks

**Comment by srirambv** [comment]
@iccub already implemented this as part of the sync fixes for #973

**Comment by LaurenWags** [comment]
* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.12.14)
- Code words screen shows the message but QR code screen does not. Logged #1245 for QR code screen.
![IMG_A7F1E67CFD90-1](https://user-images.githubusercontent.com/28145373/61151746-a755d700-a4b4-11e9-9fcc-7db688e5dc6b.jpeg)

![IMG_D06A569B88F7-1](https://user-images.githubusercontent.com/28145373/61151749-ab81f480-a4b4-11e9-8658-71fd471d5720.jpeg)

* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`

![IMG_9785](https://user-images.githubusercontent.com/2602313/61466281-a35c0600-a947-11e9-9668-13fb5d643bec.PNG)

![IMG_9784](https://user-images.githubusercontent.com/2602313/61466282-a35c0600-a947-11e9-83b4-3f090cb17d74.PNG)
