### ISSUE TITLE
not all PB text being translated

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#1239]
### Description: 

The first part of the PB text isn't being translated. However, the expanded text will be in the correct locale.

### Steps to Reproduce 
  1. Change the device language to something other than english
  2. launch Brave and open a PB tab

**Actual result:** 

![IMG_9755](https://user-images.githubusercontent.com/2602313/61096972-74b1cd00-a427-11e9-9ecf-573a63ce5ddd.PNG)

**Expected result:**

The first part of the PB text should also be translated into the correct locale.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* Using `1.10 (19.07.10.17)`

**Device details:** 

* `iPad Mini 4 running iOS 12.3.1` using `1.10 (19.07.10.17)` - Reproduced
* `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.10.17)` - Reproduced

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by kjozwiak** [comment]
This is also reproducible on `1.9.3 (19.05.22.15)` which is the latest production release that's on the App Store. So definitely not a new regression.

**Comment by danishjafri88** [comment]
Resolved

**Comment by LaurenWags** [comment]
* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.16.23)

![IMG_270312B569AC-1](https://user-images.githubusercontent.com/28145373/61399197-a00b4080-a89b-11e9-9883-25e9bbf93ee0.jpeg)

![IMG_468686AF2D68-1](https://user-images.githubusercontent.com/28145373/61399201-a3063100-a89b-11e9-8833-00d5b5c5c24f.jpeg)

* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`
  * checked using `Italian`, `Portuguese` and `Japanese`

![IMG_9772](https://user-images.githubusercontent.com/2602313/61399249-b913f180-a89b-11e9-95ac-2ffa03e379e5.PNG)

![IMG_9771](https://user-images.githubusercontent.com/2602313/61399250-b913f180-a89b-11e9-8559-d005043f0219.PNG)

![IMG_9770](https://user-images.githubusercontent.com/2602313/61399251-b913f180-a89b-11e9-9274-70acedc82f35.PNG)
