### ISSUE TITLE
"Start a new Sync Chain" & "I have a Sync Code" buttons reverted

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#1240]
### Description: 

The buttons under `Brave Sync` are reverted and are opening the incorrect modal, example:

* Tapping on `Start a new Sync Chain` opens the `I have a Sync Code` experience/modal
* Tapping on `I have a Sync Code` opens the `Start a new Sync Chain` experience/modal

### Steps to Reproduce 
  1. Install/Open `1.10 (19.07.10.17)`
  2. Tap on `Settings` --> `Brave Sync`
  3. Tap on  `Start a new Sync Chain` --> opens `I have a Sync Code`
  4. Tap on `I have a Sync Code` --> opens `Start a new Sync Chain`

**Actual result:** 

* Tapping on `Start a new Sync Chain` opens the `I have a Sync Code` experience/modal
* Tapping on `I have a Sync Code` opens the `Start a new Sync Chain` experience/modal

**Expected result:**

* Tapping on `Start a new Sync Chain` should open the `Start a new Sync Chain` experience/modal
* Tapping on `I have a Sync Code` should open the ``I have a Sync Code` experience/modal

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* Using ` Brave 1.10 (19.07.10.17)`

**Device details:** 

* `iPad Mini 4 running iOS 12.3.1` using `1.10 (19.07.10.17)` - Reproduced
* `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.10.17)` - Reproduced

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by kylehickinson** [comment]
Was already fixed here: https://github.com/brave/brave-ios/pull/1234

**Comment by kjozwiak** [comment]
Thanks @kylehickinson, going to request for a new build that includes the latest changes. Only seeing `19.7.10.17` in the BETA TF right now.

**Comment by jhreis** [comment]
Closing as duplicate, sorry this didn't get included in latest beta.

**Comment by LaurenWags** [comment]
* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.12.14). Verified STR from description.
* Verification **PASSED** on `iPhone 6s+ using iOS 12.3.1` running `1.10 (19.07.16.23)`
