### ISSUE TITLE
shields breaking https://coinmarketcap.com 

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#1241]
### Description: 

Shields is breaking https://coinmarketcap.com which is a problem as it's one of the sites that appears default under `Favourites/NTP`. It's not reproducible on `1.9.3 (19.05.22.15)` which is the current App Store release. Assuming it regressed somewhere in `1.10`.

### Steps to Reproduce 
  1. Install `1.10 (19.07.10.17)` via TF
  2. Once installed, tap on the https://coinmarketcap.com icon on the NTP

**Actual result:** 

![IMG_9759](https://user-images.githubusercontent.com/2602313/61098579-7f6f6080-a42d-11e9-8b98-ed4ce0ef1340.PNG)

**Expected result:**

![IMG_9760](https://user-images.githubusercontent.com/2602313/61098642-a3cb3d00-a42d-11e9-9cb7-64a9007676c8.PNG)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* Using `1.10 (19.07.10.17)`

**Device details:** 

* `iPad Mini 4 running iOS 12.3.1` using `1.10 (19.07.10.17)` - Reproduced
* `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.10.17)` - Reproduced

**Website problems only:**
- did you check with Brave Shields down? Loads correctly when shields are down
- did you check in Safari/Firefox (WkWebView-based browsers)?  N/A

**Comment by iccub** [comment]
This seems to be working now on latest build, please recheck it cc @LaurenWags

**Comment by kjozwiak** [comment]
@iccub I can still reproduce the above using `1.1.0 (19.07.12.14)` on both `iPad Mini 4` & `iPhone 6s+` which are both running `iOS 12.3.1`. @LaurenWags can you reproduce this on your end?

@iccub is `1.1.0 (19.07.12.14)` the latest build? If not, can we get the latest version uploaded into TF?

**Comment by iccub** [comment]
Yes, latest development version should hopefully fix that.

You could also try on fresh install, maybe something got stuck

**Comment by kjozwiak** [comment]
> You could also try on fresh install, maybe something got stuck

@iccub those were on clean profiles. I'll wait till TF gets updated with the latest version.

**Comment by LaurenWags** [comment]
@kjozwiak yes, I can reproduce on same version you listed `1.10 (19.07.12.14)` on iPad 5th Gen which is running iOS 12.3.1 also. Clean profile as well.

**Comment by LaurenWags** [comment]
Issue reproduces with latest Beta 1.10 (19.07.16.21) using iPad 5th Gen.

**Comment by kjozwiak** [comment]
Same results as @LaurenWags with `1.10 (19.07.16.21)`, example:

* `iPad Mini 4` running `iOS iOS 12.3.1` using `1.10 (19.07.16.21)` --> Reproduced
* `iPhone 6s+` running `iOS iOS 12.3.1` using `1.10 (19.07.16.21)` --> Reproduced

Again, I can't reproduce this with the latest release that's out on the App Store, example:

* `iPad Mini 4` running `iOS iOS 12.3.1` using `1.9.3 (19.05.22.15)` --> Couldn't reproduce
* `iPhone 6s+` running `iOS iOS 12.3.1` using `1.9.3 (19.05.22.15)` --> Couldn't reproduce

I also double checked `Android 1.1.1 CR: 75.0.3770.101` which was just pushed live and it seems to . be working without any issues as well.

**Comment by LaurenWags** [comment]
* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.16.23)

![IMG_FEACE576EBD3-1](https://user-images.githubusercontent.com/28145373/61400612-9f27de00-a89e-11e9-919c-cd2845767b0c.jpeg)

* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`

![IMG_E64ECB002AE7-1](https://user-images.githubusercontent.com/2602313/61406217-65100980-a8a9-11e9-8527-2b7995fc07fd.jpeg)
