### ISSUE TITLE
New tab page not showing

### ISSUE THREAD

**Issue by EyanGoldman** [brave/brave-ios#1244]
### Description: 
Intermittently when I open a new tab, instead of showing me the new tab page I get this:
![Image from iOS (9).png](https://images.zenhubusercontent.com/5cf5a25c96db72707b4b2784/d7beddf0-eba6-4def-8eb6-5374e43bc876) 

### Steps to Reproduce 
  1. Open a new tab

**Actual result:** 
See above

**Expected result:**
See new tab page

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent Issue

**Brave Version:** 
1.10 (19.07.12.14)

**Device details:** 
iPhone X, iOS 13 Beta 3

**Comment by iccub** [comment]
Seems to be working now, closing

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 running 1.12(19.09.06.15)
* Verified new tab is shown when the app is launched fresh
* Verified new tab is shown when the app is launched from background
* Verified new private tab is shown when the app is launched fresh with PB only mode set
* Verified new private tab is shown when the app is launched from the background with PB only mode set
* Verified new tab is shown when the app is launched with pin enabled along with face detection
* Verified new tab is shown when the app is launched from the background with pin enabled along with face detection
* Verified new private tab is shown when the app is launched with pin enabled along with face detection and PB only mode enabled
* Verified new tab is shown when the app is launched from the background with pin enabled along with face detection and PB only mode enabled

Verification **PASSED** on `iPad Air 3rd Generation` using `iOS 13.1` running `1.12 (19.09.11.22)`:

* Verified new tab is shown when the app is launched fresh
* Verified new tab is shown when the app is launched from background
* Verified new private tab is shown when the app is launched fresh with PB only mode set
* Verified new private tab is shown when the app is launched from the background with PB only mode set
* Verified new tab is shown when the app is launched with pin enabled along with face detection
* Verified new tab is shown when the app is launched from the background with pin enabled along with face detection
* Verified new private tab is shown when the app is launched with pin enabled along with face detection and PB only mode enabled
* Verified new tab is shown when the app is launched from the background with pin enabled along with face detection and PB only mode enabled

Verification passed on iPhone 7+ with iOS 12.4.1 running 1.12(19.09.13.06)
* Verified new tab is shown when the app is launched fresh
* Verified new tab is shown when the app is launched from background
* Verified new private tab is shown when the app is launched fresh with PB only mode set
* Verified new private tab is shown when the app is launched from the background with PB only mode set
* Verified new tab is shown when the app is launched with pin enabled along with face detection
* Verified new tab is shown when the app is launched from the background with pin enabled along with face detection
* Verified new private tab is shown when the app is launched with pin enabled along with face detection and PB only mode enabled
* Verified new tab is shown when the app is launched from the background with pin enabled along with face detection and PB only mode enabled
