### ISSUE TITLE
Sync QR code screen should show same warning message as code words screen - follow up to 1225

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#1245]
### Description: 
Found while testing #1225 

Same as https://github.com/brave/brave-browser/issues/4491 and https://github.com/brave/browser-android-tabs/issues/1828

### Steps to Reproduce 
   1. Navigate to Settings > Sync
   2. Start a sync chain on device if there isn't one already.
   3. View Code words, you will see added message warning users "Treat this code like a password. If someone gets hold of it, they can read and modify your synced data."
   4. View QR screen.

## Actual result 
No such warning message on QR screen.
![IMG_D06A569B88F7-1](https://user-images.githubusercontent.com/28145373/61151590-4fb76b80-a4b4-11e9-8132-5e1ac9fd5c1f.jpeg)

**Expected result:**
Message like with code words:
![IMG_A7F1E67CFD90-1](https://user-images.githubusercontent.com/28145373/61151603-55ad4c80-a4b4-11e9-96d2-dc5660fcef9f.jpeg)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.10 (19.07.12.14)

**Device details:** 
all

**Website problems only:**
- did you check with Brave Shields down? n/a
- did you check in Safari/Firefox (WkWebView-based browsers)?  n/a

**Comment by GeetaSarvadnya** [comment]
- Verification passed on iPhone 8 running iOS 12.3.1 using 1.10(19.07.16.23)
 
![IMG_0075](https://user-images.githubusercontent.com/38657976/61393797-62300b80-a8df-11e9-8b83-968dfae33336.PNG)
![IMG_0076](https://user-images.githubusercontent.com/38657976/61393807-66f4bf80-a8df-11e9-98b8-76672dbf3cda.PNG)

* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.16.23)
![IMG_C5E9930B538A-1](https://user-images.githubusercontent.com/28145373/61406016-09458080-a8a9-11e9-87e7-50b0defaf5d7.jpeg)
![IMG_FA42254982C1-1](https://user-images.githubusercontent.com/28145373/61406020-0c407100-a8a9-11e9-8464-117040b0f4cd.jpeg)
