### ISSUE TITLE
WebSQL and IndexedDB are not available in private mode

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1247]
### Description: 
WebSQL and IndexedDB are not available in private mode

### Steps to Reproduce 
  1. Navigate to browsertesting.freevar.com/stp.html
  2. IndexedDB and WebSQL are not available

**Actual result:** 
Not available

**Expected result:**
Should be available

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
Development Branch (Commit Id# 85a08fdc38162f64237f830d2c92401c78bac206)

**Device details:** 
iPad

**Comment by jumde** [comment]
This does not work on Safari as well, reaching out to our friends at Apple to check if this is intentional.

**Comment by kylehickinson** [comment]
@jumde Anything ever come out of this? Can this be closed?

**Comment by iccub** [comment]
blocked by Apple, I verified by PJ this can be closed
