### ISSUE TITLE
`Other Settings` heading in Settings needs to be translated

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#1248]
### Description: 
When in Settings, the heading for `Other Settings` only displays in English.

### Steps to Reproduce 
  1. Set language to be something other than English (French, etc)
  2. Install and launch Brave
  3. Navigate to Settings

**Actual result:** 
Other Settings is in English always.
![IMG_0310](https://user-images.githubusercontent.com/28145373/61155298-8c886000-a4be-11e9-8ca1-12ef90d96e5d.PNG)

**Expected result:**
Other Settings should be translated.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.10 (19.07.12.14)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? n/a
- did you check in Safari/Firefox (WkWebView-based browsers)?  n/a

**Comment by iccub** [comment]
Fixed in https://github.com/brave/brave-ios/pull/1254/files

**Comment by LaurenWags** [comment]
* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.16.23)

![IMG_D0C28D416474-1](https://user-images.githubusercontent.com/28145373/61403851-36436480-a8a4-11e9-97bb-0ad1040f2595.jpeg)

* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`

![IMG_9778](https://user-images.githubusercontent.com/2602313/61462973-8ae8ed00-a941-11e9-830f-ee132cc7f613.PNG)

![IMG_9777](https://user-images.githubusercontent.com/2602313/61462974-8b818380-a941-11e9-8e0a-d999d250b33e.PNG)
