### ISSUE TITLE
Rename 'Brave Sync' to 'Sync'

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1252]
This is to align with other platforms.

The history of Sync naming:
`Sync(beta) -> `Brave Sync` -> `Sync`

related old ticket https://github.com/brave/brave-ios/issues/973

**Comment by LaurenWags** [comment]
* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.16.23)

![IMG_F868D765C4D0-1](https://user-images.githubusercontent.com/28145373/61402868-0004e580-a8a2-11e9-86d3-d65a014048c3.jpeg)

* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`

![IMG_9783](https://user-images.githubusercontent.com/2602313/61464843-f41e2f80-a944-11e9-800a-3655dcd5403f.PNG)
