### ISSUE TITLE
WebView becomes blank when showing PDF and Switching from tab tray to browser.

### ISSUE THREAD

**Issue by danishjafri88** [brave/brave-ios#1255]
### Description: 
WebView displays blank pdf document after transitioning from tab tray controller to browser controller.

### Steps to Reproduce 
  1. Open a pdf in browser (any pdf)
  2. Tap tab tray button 
  3. press done button in tab tray to go back to browser

**Actual result:** 
Blank/Empty pdf document

**Expected result:**
Actual document before going to tab controller

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
The issue is internal to a webkit and will require a workaround. Maybe a page refresh?
https://bugs.webkit.org/show_bug.cgi?id=193281

**Comment by srirambv** [comment]
Issue still reproducible. Switch back from tab tray to browser shows blank pages. Reload page brings it back to view. Reproduced on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.06.17)
[#1255-PDF.zip](https://github.com/brave/brave-ios/files/3585636/1255-PDF.zip)

**Comment by iccub** [comment]
Bumping to next release, cc @Brandon-T as you've worked on it

**Comment by Brandon-T** [comment]
iOS 13 completely breaks my fix.. On any iOS 12 device (for which I have 3), it works.. for iOS 13 it doesn't :(

I'll see if I can find another solution.

**Comment by hennrynusasatria** [comment]
Hi @Brandon-T ,

Do you already have any update on the above bug fix?

Thank you.

**Comment by iccub** [comment]
Will be handled in https://github.com/brave/brave-ios/issues/3534
