### ISSUE TITLE
Quick Action for New Private Tab

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ios#1258]
### Description: 
User Request: Support a _Quick Action_ for opening a private tab from the home screen. This would give Brave on iOS parity with Brave on Android.

### Steps to Reproduce 
1. 3d-touch the Brave icon

**Actual result:** 
No option to open a private tab

**Expected result:**
Option to open a private tab

### Additional Information 
https://twitter.com/derlinzer/status/1151122845885521920

![image](https://user-images.githubusercontent.com/815158/61300759-f9e70a00-a7b8-11e9-8e11-6352ba7417c1.png)

Brave on Android:

![image](https://user-images.githubusercontent.com/815158/61300992-6e21ad80-a7b9-11e9-8c11-1c56dc048ea5.png)

**Comment by kylehickinson** [comment]
> Quick actions are dynamic.
>
> If the application has NEVER launched, the actions will only show "Share Brave".
However, after the first launch, the actions will depend on what mode you're browsing in:
>
> **Private Browsing Only Mode:**
New Private Tab -> Launches only private tabs.
>
> **Any Other Mode:**
> New Tab -> Launches a regular tab.
> New Private Tab -> Launches a new private tab.

**Comment by srirambv** [comment]
* Verification passed on iPhone 7 (iOS 12.3.1) running 1.10(19.7.24.20) 
![File](https://user-images.githubusercontent.com/17010094/61911057-47275200-af04-11e9-86b9-1c28dbf14e0a.jpg)

**Comment by kjozwiak** [comment]
@srirambv @LaurenWags do your iPad's have `3D Touch`? Unfortunately my `iPad Mini 4` doesn't so I can't verify this one 😢

**Comment by srirambv** [comment]
I dont think 3D touch is available on any iPad. Its only on [iPhones, Apple Watch  and Macbook Pro's](https://en.wikipedia.org/w/index.php?title=Force_Touch&action=edit&section=5). So we are good on this for mobile.
