### ISSUE TITLE
Long press on any image shows image source too long

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#1266]
### Description: 
Long press on any image shows image source too long

### Steps to Reproduce 
  1. clean profile 1.10 (19.07.16.23)
  2. open google.com
  3. search string `images`
  4. long press on any one image

**Actual result:** 
Long press on any image shows image source too long

![IMG_0067](https://user-images.githubusercontent.com/38657976/61390929-517c9700-a8d9-11e9-8654-b8443bcfa259.PNG)

**Expected result:**

![IMG_0069](https://user-images.githubusercontent.com/38657976/61390953-5a6d6880-a8d9-11e9-8c02-2f5102da07ea.PNG)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
1.10 (19.07.16.23)

**Device details:** 
iPhone 8 - iOS 12.3.1

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information 
cc: @brave/legacy_qa @iccub @jhreis

**Comment by kjozwiak** [comment]
@jhreis would this be removed from the `1.10` release under ZenHub? Looks like it was removed from the `1.10` GH milestone so I'm assuming this isn't making it into `1.10`?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.06.17)
* Verified data source is shown on both normal and private tab
![image](https://user-images.githubusercontent.com/17010094/64459216-5a157080-d0c5-11e9-896b-6cfb8dd09829.png)

Verification **PASSED** on `iPad Air 3rd Generation` with `iOS 13.1` running `1.12 (19.09.07.03)`:

* ensured that the data source was displayed for both normal and private tabs

![IMG_F5C599866768-1](https://user-images.githubusercontent.com/2602313/64574485-a965d600-d33d-11e9-8c92-53a7b3cd99c3.jpeg)

**Comment by srirambv** [comment]
~Verification failed on iPhone 7+ with iOS 12.4.1 running 1.12(19.09.13.06).~ 

Based on internal discussion this is working as expected on iPhone 7+ with iOS 12.4.1 running 1.12(19.09.1306)

Logged #1547
