### ISSUE TITLE
Security keys don't work with gmail.com

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1267]
### Description:
Adding security keys on gmail.com fails with errors.

### Steps to Reproduce
1. Navigate to gmail.com and try to add a security key
2. Fails!

### Actual result: 
Fails

### Expected result:
Should be successful

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

### Brave Version: 
1.10

**Comment by dmennis** [comment]
It's possible that Google is doing a browser validation on the user-agent. Something to look into.

**Comment by christiaanbrand** [comment]
Registration still happens using U2F. Does Brave have support for U2F in addition to WebAuthn?

**Comment by jumde** [comment]
@christiaanbrand Brave does support U2F in addition to WebAuthn

**Comment by jumde** [comment]
@christiaanbrand - Looks like gmail uses chrome runtime APIs for U2F, is there a plan to use the FIDO U2F high-level APIs? We have support for low-level APIs as well, but we don't use the chrome runtime APIs.

**Comment by iccub** [comment]
We removed yubico sdk in favor of built in webkit webauth api.
This will be reopened if the problem still occurs.
