### ISSUE TITLE
Fix YubiKey workflow for fw 5.2.1

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1268]
### Test Plan

Specified here: https://github.com/brave/brave-ios/pull/1295

**Comment by dmennis** [comment]
Here's a good site to test the Brave Browser interaction with a YubiKey 5Ci (firmware: 5.2.1) https://demo.yubico.com/demo/trust

The demo site above works great with a YubiKey 5Ci using firmware: 5.0.8 but fails to register or login with the YubiKey 5Ci (firmware: 5.2.1).

One possible solution to resolve this issue:
Remove the flags: 

> YKFKeyFIDO2GetAssertionRequestOptionUV

 and 

> YKFKeyFIDO2GetAssertionRequestOptionUV

 from the options dictionary. The key should decide when it’s appropriate to ask for UV.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6s+ iOS 12.4` using `1.11.1 (19.08.13.17)`

* ensured that the case mentioned under https://github.com/brave/brave-ios/pull/1295 worked with a Yubico running `FW 5.2.1`
* ensured that the case mentioned under https://github.com/brave/brave-ios/issues/1268#issuecomment-512594107 worked with a Yubico running `FW 5.2.1`

Verification **PASSED** on `iPad 5th Gen iOS 12.3.1` using `1.11.1 (19.08.13.17)`

* ensured that the case mentioned under https://github.com/brave/brave-ios/pull/1295 worked with a Yubico running `FW 5.2.1`
* ensured that the case mentioned under https://github.com/brave/brave-ios/issues/1268#issuecomment-512594107 worked with a Yubico running `FW 5.2.1`
