### ISSUE TITLE
Modernize core data stack

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#127]
Our CD stack is pretty old and full of weird bugs, esp. when working in multiple NSManagedContext environment.
The goal is to use the newest(iOS 10+) NSPersistentContainer with viewContext for main thread operations and background context/s for off thread operations.

**Comment by jhreis** [comment]
Related: https://github.com/brave/browser-ios/pull/1684

**Comment by tmancey** [comment]
Discussed with @iccub and requires further work, moving to product backlog
