### ISSUE TITLE
digg.com infinite loop when HTTPSE is enabled - follow up to 1192

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#1271]
### Description: 
Follow up to #1192 

digg.com goes into infinite loading loop when HTTPSE is enabled. You are able to tap on shields and disable HTTPSE to get digg.com to load.

### Steps to Reproduce 
  1. Ensure HTTPSE is enabled globally.
  2. Visit digg.com in new tab.
  3. Infinite loop.

**Actual result:** 
Infinite loop, site never loads. Can disable HTTPSE from shields and site will load.

**Expected result:**
Site loads with HTTPSE enabled as it does on laptop and Android.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.10 (19.07.16.23)

**Device details:** 
all

**Website problems only:**
- did you check with Brave Shields down? yes
- did you check in Safari/Firefox (WkWebView-based browsers)? n/a

### Additional Information 
reproduced by @kjozwiak

**Comment by iccub** [comment]
Seems to be working now, closing.
