### ISSUE TITLE
Update Strings for Sync to Match Android

### ISSUE THREAD

**Issue by EyanGoldman** [brave/brave-ios#1272]
Update strings in Sync to match updated Android Sync strings

**Comment by EyanGoldman** [comment]
Please reference the following ticket to view appropriate changes.
https://github.com/brave/browser-android-tabs/issues/1475

**Comment by jhreis** [comment]
These tickets have a lot of conversational points, can we get a full summary here of what changes are expected. Are we talking mostly about the warning message?

Is this related to #1273 and #1274 ?

**Comment by iccub** [comment]
Fixed here https://github.com/brave/brave-ios/issues/1225
