### ISSUE TITLE
sync vs scan on QR code screen - follow up to 719

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#1273]
### Description: 
Found while testing #719 

On the QR code screen in the image in the description of #719, the header should say `Sync Chain QR Code` but it currently says `Scan Chain QR Code`.

### Steps to Reproduce 
  1. Install 1.10 (19.07.16.23)
  2. Open Settings, Navigate to Sync.
  3. Tap on Start a new Sync Chain
  4. Tap on Tablet or Phone

**Actual result:** 
See text in blue box:
![IMG_7499DE007D7E-1](https://user-images.githubusercontent.com/28145373/61412465-f33ebc80-a8b6-11e9-9c16-23307ad36d55.jpeg)

**Expected result:**
Per #719, this should say `Sync Chain QR Code`.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.10 (19.07.16.23)

**Device details:** 
all

**Website problems only:**
- did you check with Brave Shields down? n/a
- did you check in Safari/Firefox (WkWebView-based browsers)?  n/a

### Additional Information 
cc @anthonypkeane to review

**Comment by srirambv** [comment]
* Verification passed on iPhone Xr with iOS 13.2 running 1.13(19.10.16.18)
![image](https://user-images.githubusercontent.com/17010094/67035963-b322ec00-f0e8-11e9-9516-11f6652f5076.png)

* Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.10.16.18)
![image](https://user-images.githubusercontent.com/17010094/67035971-b74f0980-f0e8-11e9-8e25-f9ed99602493.png)

* Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.16.18)
![image](https://user-images.githubusercontent.com/17010094/67035944-a69e9380-f0e8-11e9-9e32-3428495c3b9c.png)

* Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.16.18)
![image](https://user-images.githubusercontent.com/17010094/67035982-bcac5400-f0e8-11e9-901b-76c6e9096eaa.png)

* Verification passed on iPad pro with iOS 12.4 running 1.13(19.10.16.18)
![image](https://user-images.githubusercontent.com/17010094/67035956-ad2d0b00-f0e8-11e9-8e3b-61ba673abc76.png)
