### ISSUE TITLE
capitalization on sync screen - follow up to 719

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#1274]
### Description: 
Found while testing #719 

Unexpected capitalization of words on one of the sync UI screens. Per #719, was expecting the words to not be capitalized.

### Steps to Reproduce 
  1. Create a sync chain with one device.
  2. Tap on the device in the list of synced devices
  3. Tap Remove device

**Actual result:** 
On the modal, the words in the blue box are capitalized.
![IMG_F76840692AA9-1](https://user-images.githubusercontent.com/28145373/61412676-78c26c80-a8b7-11e9-8f99-ae8118e47ab3.jpeg)

**Expected result:**
Per #719, wasn't expecting those words to be capitalized.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.10 (19.07.16.23)

**Device details:** 
all

**Website problems only:**
- did you check with Brave Shields down? n/a
- did you check in Safari/Firefox (WkWebView-based browsers)? n/a

### Additional Information 
cc @anthonypkeane to review

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.06.17)

![image](https://user-images.githubusercontent.com/17010094/64459991-4bc85400-d0c7-11e9-9bde-e5e64698a0f0.png)

Verification **PASSED** on `iPad Air 3rd Generation` with `iOS 13.1` running `1.12 (19.09.07.03)`:

![IMG_ACDB6066AB0E-1](https://user-images.githubusercontent.com/2602313/64579333-87c21a00-d350-11e9-8295-995d83b3fd2e.jpeg)

Verification passed on iPhone 7+ with iOS 12.4.1 running 1.12(19.09.13.06)
![image](https://user-images.githubusercontent.com/17010094/64886501-58ebc280-d634-11e9-970e-e5b787c2f08f.png)
