### ISSUE TITLE
sites not loading properly with shields down

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#1279]
### Description: 
Sites aren't loading properly when putting shields down.

### Steps to Reproduce 
1. Enabled all switches for shields in settings.
2. Navigated to slashdot.org. 3rd party ads don't load as expected. Turn off shields --> 3rd party ads still don't load but should.
3. Navigated to https-everywhere.badssl.com. HTTPSE is working as expected. Turn off shields. --> HTTPSE is off as expected.
4. Navigated to raisegame.com. Shields block page as expected. Turn off shields --> Page still shows as blocked by shields but page should load.
5. Navigated to brianbondy.com. Site doesn't load as expected. Turn off shields. --> site still doesn't load but should.
6. Navigated to browserleaks.com/canvas. See message about JavaScript Disabled on site. Turn off shields. --> Still see message about JavaScript Disabled. Doesn't show fingerprinting info as expected.

*note - if you toggle the specific setting, i.e. Block Scripts for brianbondy.com, the site does load properly. so individual toggles seem to be working as expected

**Actual result:** 
Most sites above (excluding https-everywhere.badssl.com) aren't loading when putting shields down.

**Expected result:**
Putting shields down on a site should allow it to load properly.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.9.3 (19.05.22.15)
1.10 (19.07.16.23)

**Device details:** 
iPad 5th Gen

**Website problems only:**
- did you check with Brave Shields down? yes
- did you check in Safari/Firefox (WkWebView-based browsers)?  n/a

**Comment by kjozwiak** [comment]
Basically running into the same issues as @LaurenWags when it comes to global shield settings still being applied even though Brave shields has been disabled. Simple case:

* enable `Block Scripts` globally from `Settings`
* visit http://brianbondy.com and the entire website appears white (expected as script is blocked)
* disable Brave shields for http://brianbondy.com and you'll notice the website not loading
* disable `Block Scripts` globally from `Settings`
* visit http://brianbondy.com and the website will load with shields disabled

As @LaurenWags mentioned above, this is happening on both `1.9.3 (19.05.22.15)` & `1.10 (19.07.16.23)` so it's not a new regression but should be looked at as it might lead to other Shields issues. @CCing @jhreis @anthonypkeane not sure if we want to block this for `1.10` as it already exits in `1.9.3 (19.05.22.15)`. Thoughts?

**Comment by kjozwiak** [comment]
Here's another quick STR/Test Case:

* visit http://brianbondy.com and enable `Block Scripts` (page should be white)
* Disable shields and http://brianbondy.com will still be blocked. `Block Scripts` is being enforced

**Comment by kjozwiak** [comment]
@jhreis @anthonypkeane we should probably fix this one sooner than later as it could cause some confusion for folks who disable the shields but are still seeing things blocked/not working as expected.

**Comment by srirambv** [comment]
@iccub  does #1879 fix this issue as well?

**Comment by iccub** [comment]
@srirambv doubt it, I will check though

**Comment by iccub** [comment]
I went over all test cases and all seem to work now, closing this ticket, please re-test it in 1.20

**Comment by srirambv** [comment]
Blocked on https://github.com/brave/brave-ios/issues/2935

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.08.12)
- Verified page loads correctly when shields down
-------------
Verification passed on iPhone 7+ with iOS 14.0.1 running 1.21(20.10.08.12)
- Verified page loads correctly when shields down
-------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.10.08.12)
- Verified page loads correctly when shields down
