### ISSUE TITLE
Tapping near the edge of Brave Shields selects URL

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#1280]
### Description: 

When tapping near the end of the `Brave Shields`, you'll sometimes end up selecting the URL rather than the `Brave Shields` which gets annoying after a while. Assuming https://github.com/brave/brave-ios/issues/1134 caused this issue.

### Steps to Reproduce 
  1. Open `Brave 1.10 (19.07.16.23)`
  2. Tap near the edge of the `Brave Shields` icon (right side)

You'll notice that sometimes you'll select the URL. Assuming the URL spills over and there's area where it can still be selected to the right of the `Brave Shields` icon.

**Actual result:** 

Example of the issue occurring: https://youtu.be/iqd4Uny90ng

**Expected result:**

Tapping near the edge of `Brave Shields` shouldn't select the URL.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproduced using the above STR.

**Brave Version:** 

* `Brave 1.10 (19.07.16.23)`

**Device details:** 

* `iPhone 6s+ running iOS 12.3.1` - Reproduced
* `iPad Mini 4 running iOS 12.3.1` - Reproduced

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information

CCing @LaurenWags @anthonypkeane @jhreis @EyanGoldman

**Comment by jhreis** [comment]
One solution to this is to add more content/padding around the Brave shield button.

**Comment by EyanGoldman** [comment]
@jhreis this is also an issue w/ refresh button as well

**Comment by kjozwiak** [comment]
> @jhreis this is also an issue w/ refresh button as well

@jhreis did 5de743e also address the refresh issue that @EyanGoldman mentioned or should we create a new issue?

**Comment by iccub** [comment]
@kjozwiak All items on address bar should be better now: Shields, Rewards, Reload, Reader mode buttons

**Comment by srirambv** [comment]
Verification passed on iPhone XR  with iOS 13.1 beta 2 running 1.12(19.09.06.17)
* Verified tapping on the extreme edge of Brave shields doesn't select URL bar

Verification **PASSED** on `iPad Air 3rd Generation` with `iOS 13.1` running `1.12 (19.09.10.13)`:
* Verified tapping on the extreme edge of Shields, Rewards, Reload, Reader mode buttons doesn't select the URL bar

Verification **PASSED** on `iPhone 6s+` using `iOS 12.4.1` running `1.12 (19.09.13.06)`:
* Verified tapping on the extreme edge of Shields, Rewards, Reload, Reader mode buttons doesn't select the URL bar
