### ISSUE TITLE
images aren't always downloaded when using `Save Image` from context menu

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#1281]
### Description: 
While testing 1.10 I found that images aren't always downloaded when I long press on an image and select 'Save Image' from context menu. I am able to reproduce on 1.9.3.

Note - not everyone in QA is having this issue, so seems to be intermittent. @GeetaSarvadnya is able to reproduce but @kjozwiak is not.

### Steps to Reproduce 
  1. Navigate to a site like https://smittenkitchen.com/2014/08/cold-noodles-with-miso-lime-and-ginger/
  2. Scroll down the page a bit and long press on some of the images. 
  3. Select Save Image from the context menu for several. (if new install, you will have to allow Brave access to do this)
  4. Go to your Photos. 
  5. For me, the images are not generally saved, although sometimes the first image is.
  6. Navigate to google image search and search for some images.
  7. Tap on an image to view, long press, and select Save Image.
  8. These images generally save for me.

**Actual result:** 
Sometimes images save, sometimes they do not.

**Expected result:**
Photos should be saved when using 'Save Image'.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
intermittent - reproduces for some members of QA but not others.

**Brave Version:** 
1.9.3 (19.05.22.15) and 1.10 (19.07.16.23)

**Device details:** 
iPad 5th Gen

**Website problems only:**
- did you check with Brave Shields down? n/a
- did you check in Safari/Firefox (WkWebView-based browsers)?  n/a

### Additional Information 
cc @GeetaSarvadnya to add her results

**Comment by GeetaSarvadnya** [comment]
The issue is Reproducible consistently on iPhone 8 (IOS 12.3.1) running 1.10 (19.07.16.23)

open google.com->Search "images"->"www.shutterstock.com/category/nature"->Long press on image->tap on save image
Tried each scenario on a clean profile:
1. Saved 2 images - 2nd image is not saved in the device
Recorded file: https://drive.google.com/open?id=1p12vbmoqZWirMBeiH9lj2avHHMYl7wFO
2. Saved 3 images - 3rd image is not saved in the device
3. Saved 4 images - 4th image is not saved in the device

**Comment by Brandon-T** [comment]
Hmm.. can't reproduce on simulator or real devices (tried iphone simulator X).
Tried real devices: iPhone 6S (12.2) and iPhone X (12.3.1).

Maybe someone else can try :(

**Comment by jhreis** [comment]
@GeetaSarvadnya Do you have image access enabled for Brave?

**Comment by LaurenWags** [comment]
Oddly enough, this worked fine for me with 1.11.1 - no issues. Same sites. Super weird.

**Comment by kjozwiak** [comment]
@GeetaSarvadnya mind checking this again and seeing if you can still reproduce? I could never reproduce the issue @LaurenWags was seeing on my devices.

**Comment by kylehickinson** [comment]
Closing as stale, please submit new issue if it comes up again
