### ISSUE TITLE
Webauthn Security Key Attestation

### ISSUE THREAD

**Issue by eparkko-lab** [brave/brave-ios#1282]
### Description: 
Brave on iOS does not appear to respect Webauthn attestation parameters.  Even if an RP specifies "attestation": "none" the authenticator will still respond with the attestation data.  

### Steps to Reproduce 
  1.  Go to https://webauthntest.azurewebsites.net/ and login
  2.  Click button for Create Credential
  3.  Change the default for RP Info to "This Domain" 
  4.  Change attestation to "None"
  5.  Click Create
  6.  View the attestation info that was returned

**Actual result:** 
Attestation: packed 

**Expected result:**
Attestation: none

Attestation data shouldn't be returned.
Also if attestation data was requested there should also be a prompt for the user to acknowledge that it will be returned.   Chrome 75 on Windows 1903 is an example. 

**Reproduces how often:** Easily reproduced

**Brave Version:** 
1.1.0 (19.06.21.17)

**Device details:** 
iPhone Xr (12.3.1)

**Comment by jumde** [comment]
If we return attestation data, we should display a prompt similar to: 

<img width="450" alt="Screen Shot 2019-07-23 at 9 25 16 AM" src="https://user-images.githubusercontent.com/1903815/61729388-ed6c2f80-ad2b-11e9-8361-ee2bf5fa26c2.png">

cc: @jamesmudgett

**Comment by iccub** [comment]
We removed yubico sdk in favor of built in webkit webauth api.
This will be reopened if the problem still occurs.
