### ISSUE TITLE
Webauthn ResidentKey support 

### ISSUE THREAD

**Issue by eparkko-lab** [brave/brave-ios#1284]
### Description: 
Webauthn ResidentKey support does not seem to be complete on Brave.  It appears that residentKeys can be created during registration, however Brave does not appear to support use of residentKeys for authentication.

### Steps to Reproduce 
  1.  Using Brave on iOS, Go to https://demo.yubico.com/playground
  2.  Register a new user and sign-in
  3.  Click "ADD SECURITY KEY"
  4.  Select the box to "Enable passwordless login with this key"
  5.  Register the key
  6.  SIGN OUT
  7.  At the Sign In Screen click the link for "If you have enabled passwordless login..."
  8.  Try to authenticate with the key.
  9.  Remove key from Phone and plug it into a pc.  
  9.  On Windows 1903 using Edge go to https://demo.yubico.com/playground
 10. At the Sign In Screen click the link for "If you have enabled passwordless login..."
 11. Authenticate using the key that was registered using Brave on iOS. 

**Actual result:** 
During the login attempt using Brave on iOS I was prompted to "Interact with your authenticator", however nothing occurred. 

**Expected result:**
Similar to the experience using Edge on Windows, I should have been able to login to the site using the security key using a passwordless login flow.  

**Reproduces how often:** Easily reproduced

**Brave Version:** 
1.1.0 (19.06.21.17)

**Device details:** 
iPhone Xr (12.3.1)

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+ running 1.12
  * Verified visiting demo.yubico.com/playground and selecting passwordless login prompts to connect the device
  * Connecting the device automatically logs in without having to touch the key connectors

**Comment by kjozwiak** [comment]
@LaurenWags checked `Chrome`, `0.69.103 (dev)` & `Safari` and couldn't login into https://demo.yubico.com/playground on `macOS`

<img width="727" alt="Screen Shot 2019-08-13 at 12 56 51 PM" src="https://user-images.githubusercontent.com/2602313/62961367-9f969480-bdca-11e9-8f18-74ec2f81a609.png">

I checked `Firefox`, `Chrome` and `Brave` on Windows 10 x64 and couldn't get they key to work either. @jumde looks like this is only working on Edge on Windows. Expected?

**Comment by jumde** [comment]
@LaurenWags: That's expected, only Edge has support for password less logins as of now.

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 6s+ iOS 12.4` using `1.11.1 (19.08.12.19)`
   * Went through the above STR and ensured it was also working under `Edge` on `Windows 10 x64` as mentioned via https://github.com/brave/brave-ios/issues/1284#issue-470439223.

* Verified passed with iPad 5th Gen using 1.11.1 (19.08.12.19)
   - confirmed steps 1-8 work on iPad. Per comment above, remaining steps only work on Edge, not other browsers at this time.

**Comment by eparkko-lab** [comment]
@jumde 

**Brave Version:**
1.11.1 (19.08.13.17)

**Device details:**
iPhone Xr (12.3.1)

I noticed that if I create multiple residentKeys on the same site that during a passwordless authentication flow that only the last registered residentKey will get used.   

Steps:

- Create user1 on demo.yubico.com/playground and register a key for passwordless signon

- Create user2 on demo.yubico.com/playground and register the same key for passwordless signon

- Sign on to the site with passwordless credentials.  

The user2 will be the user that is logged on.

**Comment by jumde** [comment]
@eparkko-lab - logged a new issue here: https://github.com/brave/brave-ios/issues/1412
