### ISSUE TITLE
Webauthn support for authenticatorAttachment

### ISSUE THREAD

**Issue by eparkko-lab** [brave/brave-ios#1286]
### Description: 
Brave on iOS does not seem to support authenticatorSelection.authenticatorAttachment.

### Steps to Reproduce 
  1.  Using Brave on iOS go to https://webauthntest.azurewebsites.net/ and login
  2.  Click button for Create Credential
  3.  Change the default for RP Info to "This Domain" 
  4.  Change the default for "Attachment" to "Platform"
  5.  Click "Create" and tap the security key.  
 

**Actual result:** 
The credential will be created using the security key

**Expected result:**
The platform authenticator will be used instead of the security key. 

**Reproduces how often:** Easily reproduced

**Brave Version:** 
1.1.0 (19.06.21.17)

**Device details:** 
iPhone Xr (12.3.1)

**Comment by iccub** [comment]
We removed yubico sdk in favor of built in webkit webauth api.
This will be reopened if the problem still occurs.
