### ISSUE TITLE
URP not working

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#1291]
### Description: 
Referrals are not working properly. `Downloaded` count increases on publisher dashboard, but `Installed` count does not.

### Steps to Reproduce 
1. Loaded 1.10 ipa file on iPad, but didn't open it.
2. Open safari
3. Visit referral page
4. Tapped on download button
5. Was taken to app store
6. Then I opened Brave (the version loaded in step 1).
7. Waited several hours
8. Saw `Downloaded` Count increase on my pubs dashboard, but `Installed` Count did not increase.

**Actual result:** 
Downloaded count increases, but Installed count does not.

When viewing URP logs, this is shown:
![IMG_9854](https://user-images.githubusercontent.com/28145373/61813853-c2a9d600-ae14-11e9-9447-dcd4af4fd759.PNG)

**Expected result:**
In case above, both should be increasing by 1. Also, no errors on URP logs screen.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily.

**Brave Version:** 
1.10 (19.07.22.19)

**Device details:** 
all

**Website problems only:**
- did you check with Brave Shields down? n/a
- did you check in Safari/Firefox (WkWebView-based browsers)?  n/a

### Additional Information 
reproduced by @kjozwiak

**Comment by kylehickinson** [comment]
@LaurenWags  @kjozwiak Which IPA did you use? Was it a beta build IPA?

**Comment by LaurenWags** [comment]
1.10 (19.07.22.19) - it's an IPA file that @kjozwiak gave me, so i'm guessing @jhreis gave it to him. I believe @jhreis already has a fix for this though.

**Comment by kjozwiak** [comment]
> 1.10 (19.07.22.19) - it's an IPA file that @kjozwiak gave me, so i'm guessing @jhreis gave it to him. I believe @jhreis already has a fix for this though.

yup, that's correct 👍I received `1.10 (19.07.22.19)` via an `IPA` file that was supposed to be the RC that QA used for upgrade cases. However, we noticed that `Installed` wasn't being incremented in the `Publisher` dashboard but the `Downloaded` was which means the referral API wasn't working.

At this point, `1.10 (19.07.22.19)` was published into TF so we could see the referral logs as the `IPA` build doesn't have logging as it was an RC so debugging features are removed/hidden. We noticed that we were still getting `invalid API key` errors as the screenshot that @LaurenWags added above with the TF build.

**Comment by kjozwiak** [comment]
Went through the following using an `iPhone 6s+ iOS 12.4` running `1.10 (19.07.24.20)`:

* installed `1.10 (19.07.24.20)` without opening the browser
* visited once of my referral pages and clicked `Download Brave`
* once the `App` store launched, opened `1.10 (19.07.24.20)`
* ensured that the correct referral appeared under `URP Code:`
* ensured that the logs showed `Referral code lookup response: SUCCESS`
* ensured that the logs looked correct with the right referral etc..
* waited 20 mins and restarted the application
* ensured that `Enough time has passed, removing referral` log appeared
* ensured that `URP Code:` was cleared
* ensured that `Installed` & `Downloaded` under the `Publisher Dashboard` incremented

I went through the above x5 with different referrals without issues. Just need confirmation from @jhreis that `Enough time has passed, removing referral` should be appearing in ~20min in this case even though the URL is pointing to the production sever and not staging.

**Comment by srirambv** [comment]
* Verification complete on iPhone 7(iOS 12.3.1) running 1.10(19.7.24.20)
  * Verified correct referral code is shown upon launch 
  * Verified referral code lookup showed success
  * Quit and relaunch showed `Not enough time has passed for referral ping`
  * Around 20 mins, showed `Setting new date for deleting referral code`
  * After 20 mins, `Enough time has passed, removing referral code data` is logged
* Verification complete on Pad Pro(iOS 12.3.1) running 1.10(19.7.24.20)
  * Verified correct referral code is shown upon launch 
  * Verified referral code lookup showed success
  * Quit and relaunch showed `Not enough time has passed for referral ping`
  * Around 20 mins, showed `Setting new date for deleting referral code`
  * After 20 mins, `Enough time has passed, removing referral code data` is logged
