### ISSUE TITLE
Extend AlertPopupView to include an option to enter user text

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1298]
### Description: 
`UserTextInputAlert` dialogs are spoof-able, the dialogs look very similar to `prompt()` alerts in javascript. We should update `AlertPopupView` to include an option for user to enter text to differentiate browser alerts from alerts from web pages.

**Comment by jumde** [comment]
Currently `UserTextInputAlerts` are used in bookmarks, favorites cc: @jamesmudgett @tomlowenthal @jhreis

**Comment by danishjafri88** [comment]
@jumde have an experimental implementation here: https://github.com/brave/brave-ios/pull/690
