### ISSUE TITLE
Provide option to close settings overlay when you are inside nested options

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1299]
### Description: 
There is no way to close the settings overlay when you navigate inside of a nested setting. You have to navigate back to the main screen to close it. 

Sections that have nested options 
1. Search engines (2 level deep)
2. Sync (before creating sync chain)
3. Clear Private Data 
4. Passcode for logins
5. Privacy policy
6. Terms of use

### Steps to Reproduce 
  1. Open Settings
  2. Go to any of the nested settings options like Search Engine
  3. Have to navigate back all screens to come out 

**Actual result:** 
![Image from iOS](https://user-images.githubusercontent.com/17010094/61950800-fb64bf00-af7c-11e9-858a-36dd4f864532.png)

**Expected result:**
Have a `Done` or `Cancel` button depending on the screen to allow users to close/come out of settings page without having to navigate all screens

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
All

**Device details:** 
All, same on iPad and iPhone. iPad has the modal, iPhone uses the entire screen

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
Interesting. Will require a case-by-case basis, like on this screen the word would definitely need to be "cancel" while on others "close" may be more appropriate. Still others, we may not want any at all. Something to gather more info on.

**Comment by iccub** [comment]
This is not valid anymore, new menu changed https://github.com/brave/brave-ios/pull/3465
