### ISSUE TITLE
woi is showing 2016-0104 

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#1300]
### Description: 
Found while testing #1291 

When looking at the logs to test issue above, I saw that my DAU ping was sending 2016-01-04 which is not the accurate week of install.

### Steps to Reproduce 
1. Loaded 1.10 ipa file on iPad, but didn't open it.
2. Open safari
3. Visit referral page
4. Tapped on download button
5. Was taken to app store
6. Then I opened Brave (the version loaded in step 1).
7. If using Beta version, open settings and go to URP logs.
8. Locate DAU ping and woi value.

**Actual result:** 
![IMG_6A045969DD1A-1 (1)](https://user-images.githubusercontent.com/28145373/61952630-56e57b80-af82-11e9-8095-b65a6cea28be.jpeg)

**Expected result:**
accurate week of install

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
unsure

**Brave Version:** 
1.10 (19.07.24.20)

**Device details:** 
iPad

**Website problems only:**
- did you check with Brave Shields down? n/a
- did you check in Safari/Firefox (WkWebView-based browsers)? n/a

### Additional Information 
cc @srirambv as he saw different results.

**Comment by srirambv** [comment]
On the first attempt, there was no DAU ping on my iPhone.
![image](https://user-images.githubusercontent.com/17010094/61953582-c5c3d400-af84-11e9-89d5-dcf9b025168e.png)
But on the second attempt with a clean install, I was able to see the DAU ping with the incorrect week of install date
![image](https://user-images.githubusercontent.com/17010094/61953652-f73c9f80-af84-11e9-854b-cdc15a1a29b5.png)

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+(iOS12.3.1) running 1.10(19.7.26.15) 
  * Verified week-of-install shows correct date
  * Verified Referral code is correctly shown
  * Verified referral code lookup showed SUCCESS
  ![image](https://user-images.githubusercontent.com/17010094/61969977-ca4eb380-afa9-11e9-8a49-c7d35b78b079.png)
* Verification passed on iPad Pro(iOS12.3.1) running 1.10(19.7.26.15) 
  * Verified week-of-install shows the correct date
  * Verified Referral code is correctly shown
  * Verified referral code lookup showed SUCCESS
![ipad](https://user-images.githubusercontent.com/17010094/61974215-fe2ed680-afb3-11e9-9292-e63fe425a9f3.jpg)
