### ISSUE TITLE
Device orientation change should have a smooth transition of video 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1302]
### Description: 
Device orientation change should have a smooth transition of video 

### Steps to Reproduce 
  1. Install 1.10(19.7.26.15)
  2. Play video on YT in portrait mode
  3. Change device orientation
  4. Last video frame when the device was in portrait mode is momentarily shown in landscape mode before the video frame increases its size to match landscape mode

**Actual result:** 
Device orientation change should have a smooth transition of video 

**Expected result:**
Should have a smooth transition when device orientation changes

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.10(19.7.26.15)

**Device details:** 
iPhone 7+  (iOS 12.3.1)
iPad Pro (iOS 12.3.1)
**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)?  N/A

### Additional Information 
cc: @Brandon-T 
Follow up to #1189

**Comment by iccub** [comment]
seems to work, its been a while so closing as stale
