### ISSUE TITLE
Move from old adblock stats lib to adblock-rust

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1307]

**Comment by kjozwiak** [comment]
@jhreis just a quick double check, QA should make sure that the stats are working as expected under the NTP correct? We don't have to worry about a possible adblocking regression on popular websites?

**Comment by iccub** [comment]
@kjozwiak this PR is only about adblocking stats so yes

And there might be small differences between adblocking count compared to previous versions, this still doesn't affect the adblocking mechanism per-se but only blocked resources stat reporting

Check if adblock stat counters are updated on new tab page and on under Brave Shields menu

**Comment by LaurenWags** [comment]
Verified passed with iPad 5th Gen using 1.11.1 (19.08.13.17)
   * Verified stats on NTP were retained on upgrade 1.11 --> 1.11.1
   * Verified stats displayed as expected in shields and on NTP on clean install of 1.11.1
   * Stats did not update on upgrade, logged https://github.com/brave/brave-ios/issues/1398

**Comment by kjozwiak** [comment]
Clearing `Pass` labels. We should recheck this once https://github.com/brave/brave-ios/issues/1398 has been addressed/fixed.

**Comment by kjozwiak** [comment]
This was reverted and QA used https://github.com/brave/brave-ios/issues/1398.
