### ISSUE TITLE
App crashes on Switching back to normal mode from PBM.

### ISSUE THREAD

**Issue by danishjafri88** [brave/brave-ios#1309]
App crashes when switching to normal mode from PBM.
Inferred crash due to changes in #1024 

### Steps to Reproduce 
  1. Open PBM 
  2. Open a Site
  3. Open Tab tray
  4. Tap to change mode

**Actual result:** 
Crash

**Expected result:**
Mode Changed to normal 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

**Comment by anthonypkeane** [comment]
dup of https://github.com/brave/brave-ios/issues/1353

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+ running 1.12 
  * Verified no crash when exiting private tabs
  * Verified long press on a link and select open in private tab, then exit private tab doesn't crash
  * Verified opening a private tab from 3D touch on the home screen and exit private tab doesn't crash
  * Verified setting PB only mode visiting a site and then disable PB mode only doesn't crash
  * Verified opening tab tray and selecting private and visiting a site, then exit private tab via tray doesn't crash the browser

* Verified passed with iPad 5th Gen using 1.11.1 (19.08.13.17)
  * Verified no crash when exiting private tabs
  * Verified long press on a link and select open in private tab, then exit private tab doesn't crash
  * Verified setting PB only mode visiting a site and then disable PB mode only doesn't crash
  * Verified opening tab tray and selecting private and visiting a site, then exit private tab via tray doesn't crash the browser
