### ISSUE TITLE
Support FIDO/U2F fallback

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1312]
### Steps to Reproduce 
 1. Disable FIDO2 on the YubiKey 5Ci (firmware version 5.2.1) using YubiKey manager on the desktop.
2. Opened Brave browser (beta 1.10)
3. Opened https://demo.yubico.com/webauthn-technical/registration to test key registration.
4. Clicked "Next"

![IMG_AB49EE5D7C3D-1](https://user-images.githubusercontent.com/1903815/62160567-2165c880-b2c9-11e9-92e7-257579569be8.jpeg)

**Actual result:** 
Authn/Registration don't work

**Expected result:**
Should work

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Comment by iccub** [comment]
We removed yubico sdk in favor of built in webkit webauth api.
This will be reopened if the problem still occurs.
