### ISSUE TITLE
Update the bootstrap script to use the new YubiKit

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1314]
## Test Plan

Specified here: #1315

**Comment by LaurenWags** [comment]
Verified passed with iPad 5th Gen using 1.11.1 (19.08.12.19)
   - Verified test plan from https://github.com/brave/brave-ios/pull/1315
![IMG_009C15198BC4-1](https://user-images.githubusercontent.com/28145373/62959489-e7b3b800-bdc6-11e9-8259-59a3fda15d66.jpeg)
![IMG_0400](https://user-images.githubusercontent.com/28145373/62959492-ea161200-bdc6-11e9-9e64-f525ec201dce.PNG)

Verification **PASSED** on `iPhone 6s+ iOS 12.4` using `1.11.1 (19.08.12.19)`

* went through the same STR via https://github.com/brave/brave-ios/pull/1315 and ensured that you can `Register` & `Authenticate` under demo.yubico.com/u2f.

![IMG_9860](https://user-images.githubusercontent.com/2602313/62959709-5729a780-bdc7-11e9-869b-20cec52f0a94.PNG)
![IMG_9859](https://user-images.githubusercontent.com/2602313/62959711-5729a780-bdc7-11e9-8891-f569be411d86.PNG)
