### ISSUE TITLE
Cannot play twitch stream

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-ios#1322]
### Steps to Reproduce 
  1. Clean install
  2. Go to twitch.tv
  3. Play stream

**Actual result:** 
Error when attempting to play the stream.
![IMG_0004](https://user-images.githubusercontent.com/34715963/62332363-926ed100-b4bf-11e9-9028-5f5f37a6c247.PNG)

Note: Turning off HTTPSE fixes the issue

**Expected result:**
Twitch stream is played

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.11 (19.8.1.15)

Not reproducible with 1.10 (19.07.19.18)

**Device details:** 
iPhone SE, iOS 12.2

Safari works. FF fails in similar way.

cc @iccub @brave/legacy_qa

**Comment by kylehickinson** [comment]
Closed as stale, and seems to work correctly now
