### ISSUE TITLE
Add Bookmarks Bar to iPad

### ISSUE THREAD

**Issue by timreuscher** [brave/brave-ios#1323]
### Description: 
Visiting bookmarked sites keeps getting harder and harder, particularly on the iPad. First the app required a tap on the bookmark icon in order to see the bookmarks. In the latest version of the app you have to tap the “...” button, then Bookmarks, meaning it now takes two taps just to even see your bookmarks. Safari on iPad and Brave on the Mac  have bookmark bars right above the tabs, so it’s a fairly common feature. And there’s plenty of room.

**Comment by srirambv** [comment]
cc: @anthonypkeane @EyanGoldman @jhreis

**Comment by jhreis** [comment]
Yeah, I think this would be useful, will ask design to work on the UI for this.

**Comment by anthonypkeane** [comment]
As a user option this is fine 
@jamesmudgett for design. Remember "tabs on top" too when thinking about this. 

Option to enable this can be under Other Settings

Show Bookmark bar (on/off toggle) Default = off

Only show for iPad users

**Comment by jamesmudgett** [comment]
![1 12 Sidepanel iPad Only](https://user-images.githubusercontent.com/318119/62888226-70b5eb00-bd04-11e9-805f-546735ebe72b.png)

**Comment by iccub** [comment]
Fixed in https://github.com/brave/brave-ios/issues/1391
