### ISSUE TITLE
Hit box too small for buttons in the URL Bar

### ISSUE THREAD

**Issue by EyanGoldman** [brave/brave-ios#1333]
### Description: 
The hit box for the buttons in the URL bar are too small and triggering inconsistently. We should move to make the hit boxes bigger

### Steps to Reproduce 
  1. Press button in URL bar

**Actual result:** 
It sometimes registers as tapping the URL bar, not the button

**Expected result:**
Tapping the button

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.10

**Device details:** 
iPhone X, iOS 13

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by iccub** [comment]
Duplicate of https://github.com/brave/brave-ios/issues/1326

**Comment by iccub** [comment]
Similar to this https://github.com/brave/brave-ios/issues/1280

**Comment by jhreis** [comment]
Duplicate of #1280
