### ISSUE TITLE
Add bookmarks button to NTP

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#1334]
Need to add 'Bookmarks' as a tile on ntp. First position that can be rearrange like other favorites. Special logic needed to disallow edit or delete on this special icon.
![Home (Light)@2x](https://user-images.githubusercontent.com/318119/62572971-833ea900-b85a-11e9-9659-7f795dcfb22f.png)
[Archive.zip](https://github.com/brave/brave-ios/files/3473948/Archive.zip)

**Comment by anthonypkeane** [comment]
The bookmark tile will be on the left yes? @jamesmudgett

**Comment by jamesmudgett** [comment]
Yes, first position by default so should have a sort order value of -1, but user can rearrange and place at the end (as seen in photo)

**Comment by iccub** [comment]
This collides with our existing spec(custom images etc.)
Closing, we can re-address this when working on refreshed new page design
