### ISSUE TITLE
UI for WebAuthn

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1335]
**Touch Key** - This dialog will be displayed when the user should interact with the key.

On Brave Desktop the dialog looks like:

<img width="503" alt="Screen Shot 2019-08-06 at 2 57 29 PM" src="https://user-images.githubusercontent.com/1903815/62580240-92255b80-b85a-11e9-9f6d-9b9c1f8fd29c.png">

**Allow site to read key data** - This dialog will be displayed when the site is requesting access to the security key data. 

On Brave Desktop it looks like:

<img width="484" alt="Screen Shot 2019-08-06 at 2 58 28 PM" src="https://user-images.githubusercontent.com/1903815/62580503-1f68b000-b85b-11e9-8587-8843d3273dd4.png">

**PIN Required** - This dialog will be displayed when the YubiKey is protected by a PIN

On Brave Desktop it looks like:

<img width="454" alt="Screen Shot 2019-08-06 at 3 00 33 PM" src="https://user-images.githubusercontent.com/1903815/62580539-35767080-b85b-11e9-9a42-13443b154357.png">

**Comment by karenkliu** [comment]
## iOS Designs

User flow:
![user flow - log in with yubikey ios](https://user-images.githubusercontent.com/2388823/62804288-aeffa000-baa1-11e9-9056-b56ac57059c7.png)

Designs:
![1 insert key](https://user-images.githubusercontent.com/2388823/62804609-a65b9980-baa2-11e9-9699-2cf832d9f333.png)
![2 pin required](https://user-images.githubusercontent.com/2388823/62804610-a65b9980-baa2-11e9-985d-cae250433993.png)
![3 verifying key](https://user-images.githubusercontent.com/2388823/62804611-a6f43000-baa2-11e9-93d9-b6164c351f75.png)
![4 touch key](https://user-images.githubusercontent.com/2388823/62804612-a6f43000-baa2-11e9-9d2b-6a4e98e4c165.png)


## Assets
Insert key: 
(animation preview) https://lottiefiles.com/share/zL8bnh
https://assets1.lottiefiles.com/packages/lf20_zL8bnh.json
[insertkey.json.zip](https://github.com/brave/brave-ios/files/3494366/insertkey.json.zip)

Enter PIN:
[enter pin.zip](https://github.com/brave/brave-ios/files/3494498/enter.pin.zip)

Verifying key:
(animation preview) https://lottiefiles.com/share/PsnbwB
https://assets5.lottiefiles.com/packages/lf20_PsnbwB.json
[authenticating.json.zip](https://github.com/brave/brave-ios/files/3494394/authenticating.json.zip)

Touch the key:
(animation preview) https://lottiefiles.com/share/c2gtfd
https://assets5.lottiefiles.com/packages/lf20_c2gtfd.json
[touchthekey.json.zip](https://github.com/brave/brave-ios/files/3494435/touchthekey.json.zip)

Lottie player:
[lottie player.zip](https://github.com/brave/brave-ios/files/3494397/lottie.player.zip)

**Comment by kjozwiak** [comment]
@EyanGoldman @anthonypkeane because this includes a lot of new UI/UX components, can someone run through the above and make sure it's working on `iPhone X`? Hopefully someone has a Yubico key that they can use in the office.

**Comment by EyanGoldman** [comment]
Passed on iPhone X

**Comment by jumde** [comment]
The new UIs are missing the site URLs. Will create a PR to add the URLs back.

**Comment by iccub** [comment]
https://github.com/brave/brave-ios/issues/1335 there's no urls in the new UI

**Comment by iccub** [comment]
I removed them because there were not present here :D

@jumde please also replace with `Enter your security key PIN` with  `Enter your security PIN`

**Comment by karenkliu** [comment]
We can add it to the first screen:
![1 insert key](https://user-images.githubusercontent.com/2388823/62977263-63b3fd00-bdd3-11e9-948d-1c4d9a5766dc.png)


Also the second screen with updated string:
![2 pin required](https://user-images.githubusercontent.com/2388823/62977268-67478400-bdd3-11e9-81bc-602facdb84a0.png)

**Comment by LaurenWags** [comment]
Verified passed with iPad 5th Gen using 1.11.1 (19.08.13.17)
   * Verified screens displayed as per https://github.com/brave/brave-ios/issues/1335#issuecomment-520060032
   * missing URLs to be handled by https://github.com/brave/brave-ios/issues/1359#issuecomment-521038734
   * Screenshots from the iPad (note, unable to get 'Verifying your PIN...' screenshot, it was too quick.
![IMG_0412](https://user-images.githubusercontent.com/28145373/63048671-02f4f500-bea5-11e9-99f0-01c17b94d833.jpg)
![IMG_0413](https://user-images.githubusercontent.com/28145373/63048675-04beb880-bea5-11e9-8930-21cc3132dbd5.jpg)
![IMG_0414](https://user-images.githubusercontent.com/28145373/63048680-06887c00-bea5-11e9-8b70-773ea374f05d.jpg)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6s+ iOS 12.4` using `1.11.1 (19.08.13.17)`.

![IMG_9901](https://user-images.githubusercontent.com/2602313/63105639-37bd8680-bf4f-11e9-9e05-e71448efa5c2.PNG)
![IMG_9899](https://user-images.githubusercontent.com/2602313/63105640-37bd8680-bf4f-11e9-98cc-867bbc4575a8.PNG)
![IMG_9898](https://user-images.githubusercontent.com/2602313/63105641-37bd8680-bf4f-11e9-8046-807e50384abd.PNG)
