### ISSUE TITLE
Clarify OS deployment target

### ISSUE THREAD

**Issue by cndouglas** [brave/brave-ios#134]
(I posted this on the Brave Discord #developers-ios but did not receive a response.)

What is the iOS deployment target for this project? I searched [the project settings file](/brave/brave-ios/blob/development/Client.xcodeproj/project.pbxproj) for `IPHONEOS_DEPLOYMENT_TARGET` and found 10.3 for some targets and 11.3 for others.

**Comment by jhreis** [comment]
We are currently planning on targeting iOS 11.3+ due to certain API restrictions (e.g. content blocking APIs). Sounds like we have a few meta data places to clean up.
