### ISSUE TITLE
Reader mode websites can't be shared/added to Bookmarks

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1340]
### Steps to Reproduce 
  1. Visit a wikipedia article
  2. Open reader mode
  3. Tap on menu

**Actual result:** 
No Add/Share option

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Adding bookmarks in reader mode should add it as a regular website, not reader-mode one

**Comment by quangDecember** [comment]
#1372 : here's my fix, can you help review? thanks

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.06.17)
* Verified article in reader mode shows Add bookmark and share with menu options
* Verified adding article in reader mode as a bookmark adds the actual page as a bookmark
* Verified sharing the article via reader mode shares the actual article
* Verified on both normal and private tab

Verification **PASSED** on `iPad Air 3rd Generation iOS 13.1` running `1.12 (19.09.10.18)`:

* Verified article in reader mode shows Add bookmark and share with menu options
* Verified adding article in reader mode as a bookmark adds the actual page as a bookmark
* Verified sharing the article via reader mode shares the actual article
* Verified on both normal and private tab

Verification passed on iPhone7+ with iOS 12.4.1 running 1.12(19./09.13.06)
* Verified article in reader mode shows Add bookmark and share with menu options
* Verified adding article in reader mode as a bookmark adds the actual page as a bookmark
* Verified sharing the article via reader mode shares the actual article
* Verified on both normal and private tab
