### ISSUE TITLE
GitHub security key registration option is hidden if no keys are registered previously

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1342]
GitHub shows an error while registering a security-key for the first time

```
Security keys are hardware devices that can be used as your second factor of authentication. When signing in, you press a button on the device rather than typing a verification code. Security keys use the FIDO U2F standard.
This browser doesn’t support the FIDO U2F standard yet. We recommend updating to the latest Google Chrome to start using security key devices.
```

## STR

1. Navigate to github.com/
2. Login and navigate to Settings > Security
3. Click on Security Keys
4. If `Security Key` is not present the option to `Register New Device` is not available.

**Comment by kjozwiak** [comment]
Reproduced using `iPhone 6s+ iOS 12.4` using `1.11.1 (19.08.13.17)`

<img width="639" alt="Screen Shot 2019-08-13 at 5 51 08 PM" src="https://user-images.githubusercontent.com/2602313/62979889-ffa13100-bdf2-11e9-921a-238003fb63ba.png">

CCing @LaurenWags ☝️Just a heads up if you're going to be trying GH for the `1.11.1` release.

**Comment by lgarron** [comment]
We just switched to https://github.com/github/webauthn-json/ , which should is less strict about about WebAuthn feature detection. However, WebAuthn registration still seems to be failing and I haven't been able to debug why (since I don't know a way to access the JS console in iOS Brave).

**Comment by jumde** [comment]
I have a debug build, investigating what's going on. Thanks for your help for fixing the authentication workflow.

**Comment by lgarron** [comment]
> I have a debug build, investigating what's going on. Thanks for your help for fixing the authentication workflow.

Any luck on this yet/anything we could do to help?

**Comment by lgarron** [comment]
Conclusion from debugging: we were checking that `navigator.credentials instanceof CredentialsContainer` mainly to get around Flow's typing. Now that https://github.com/github/webauthn-json handles the interaction with `navigator.credentials` for us, we can (and will) remove this code. There's no general need for Brave to implement a hack for `CredentialsContainer`, since there are many such possible ones and this was a quirk specific to GitHub's setup.

**Comment by jumde** [comment]
Verified fixed, registration and authentication works with GitHub.
