### ISSUE TITLE
Add support for Dynamic Type, allow to increase user interface font

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1344]
Make the app to support dynamic type, the user can change their font in settings then the UI should follow it.

**Comment by iccub** [comment]
This is possible in reader mode at the moment

**Comment by anthonypkeane** [comment]
True, but needed on all site IMO without the need for reader mode

**Comment by iccub** [comment]
This is the ticket for user interface font size aka dynamic type,
For website font size please check https://github.com/brave/brave-ios/issues/3222

I also think this ticket should be split in multiple smaller tickets, basically each part of the interface can be updated separately

**Comment by iccub** [comment]
closing, we will use smaller tickets for each area we want to improve
