### ISSUE TITLE
Add the ability to remember Request Desktop Site

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1345]
### Description: 
Add the ability to remember when a user presses Request Desktop Site.
When visiting the site again, that setting should be preserved.

![Enable-Request-Desktop-Website-in-iOS-13-Safari-App](https://user-images.githubusercontent.com/7606853/62664233-a38c6780-b92f-11e9-8555-602b92d993eb.jpg)

**Comment by jamesmudgett** [comment]
This could be stored with shield settings data, no UI. While UI may come later, it may not be necessary. We will need a way to reload (long-press) request mobile from reload and 'Share with...' menu

**Comment by iccub** [comment]
This should work now, desktop preference is now kept in memory, clears after clean app relaunch
Fixed here https://github.com/brave/brave-ios/issues/2210
