### ISSUE TITLE
Security key prompt is dismissed and showed again when key is disconnected and reconnected

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1347]
### Description: 
Security key prompt is dismissed and showed again when key is disconnected and reconnected

### Steps to Reproduce 
  1. Login to a site that supports security keys
  2. Wait for the browser to prompt to connect security key
  3. Connect the device(do not authenticate), popup prompt is retained
  4. Disconnect the key and reconnect it (again do not authenticate)
  5. Connect security key prompt is dismissed and showed again

### Test Plan 
Specified here: https://github.com/brave/brave-ios/pull/1362

**Actual result:** 
Security key prompt is dismissed and showed again when key is disconnected and reconnected

**Expected result:**
Should only dismiss the prompt if the API request times out or when the user cancels it 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.12(19.08.08.06)

**Device details:** 
iPhone 7+ (iOS 12.3.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jumde** [comment]
To address this there are different modals for different states:

1. Insert key modal: U2F APIs are active but key is not inserted
2. Touch key modal: U2F APIs are active and key is inserted
3. Pin Verification modal: Security key has an associated PIN
