### ISSUE TITLE
Touch key dialog shows up multiple times on hitting cancel

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1349]
### Description: 

If the user clicks `cancel` on the touch key dialog it should return an error. The dialog pops-up multiple times before showing an error.

### Steps to Reproduce 
  1. Navigate to demo.yubico.com/u2f
  2. Click register
  3. Hit cancel

### Test Plan
Specified here: https://github.com/brave/brave-ios/pull/1356

**Actual result:** 
The dialog box shows up again

**Expected result:**
Should return an error

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jumde** [comment]
The modal pops-up multiple times if multiple tabs are open. Working on a fix

**Comment by srirambv** [comment]
This is happening due to multiple tabs open. If I only have one tab open and hit cancel the dialog is removed

**Comment by LaurenWags** [comment]
Verified passed with iPad 5th Gen using 1.11.1 (19.08.12.19)
* Verified test plan from https://github.com/brave/brave-ios/pull/1356

Verification **PASSED** on `iPhone 6s+ iOS 12.4` using `1.11.1 (19.08.12.20)`
* Verified test plan from https://github.com/brave/brave-ios/pull/1356 and ensured we're not getting multiple modals when cancelling or going through `Registration` and `Authentication` via demo.yubico.com/u2f.
