### ISSUE TITLE
Report a Bug not working

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1354]
### Description: 
The Report a Bug button is setting not working

### Steps to Reproduce 
  1. Press the Report a Bug button

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.11

**Device details:** 
12.4

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.06.17)

* Verified `Report a bug` opens community page in a new tab
* Verified `Report a bug` opens community page in a private tab when using a private tab
* Verified setting PB only mode and `Report a bug` opens community page in a private tab 

Verification **PASSED** on `iPad Air 3rd Generation` with `iOS 13.1` running `1.12 (19.09.07.03)`:

* Verified `Report a bug` opens community page in a new tab
* Verified `Report a bug` opens community page in a private tab when using a private tab
* Verified setting PB only mode and `Report a bug` opens community page in a private tab 

Verification **PASSED** on `iPhone 6s+` using `iOS 12.4.1` running `1.12 (19.09.13.06)`:

* Verified `Report a bug` opens community page in a new tab
* Verified `Report a bug` opens community page in a private tab when using a private tab
* Verified setting PB only mode and `Report a bug` opens community page in a private tab
