### ISSUE TITLE
Add site url to the touch key modal

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1359]
### Description: 
Cancel on touch key dialog still allows authenticating into the website

### Steps to Reproduce 
  1. Visit u2fdemo.hypersecu.com and create an account 
  2. Add a security key to the account and logout
  3. Relogin to prompt for security key
  4. Cancel the touch the key dialog that pops up
  5. Touch the key connectors, website authenticates and then brings back the popup 

### Test Plan
Specified here: https://github.com/brave/brave-ios/pull/1362

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/62748192-acf7fb80-ba25-11e9-9599-2cd62e47aff1.png)

**Expected result:**
Should include website name in the popup so that easy to understand which popup to use to verify and which ones can be cancelled

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.12

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jumde** [comment]
@srirambv - Can we update the description of this issue? I think this issue captures adding the current url to the touch dialog, let me know if i'm missing something

**Comment by jumde** [comment]
The URLs from the modals were removed in https://github.com/brave/brave-ios/issues/1335. Re-opening.

**Comment by kjozwiak** [comment]
Moving this into https://github.com/brave/brave-ios/milestone/28 as we won't be fixing it for the `1.11.3`(originally `1.11.1`) as discussed previously.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.06.17)
* Verified site name is shown in the popup modal
![image](https://user-images.githubusercontent.com/17010094/64463411-f2195700-d0d1-11e9-87fb-b44af3759261.png)
![image](https://user-images.githubusercontent.com/17010094/64463395-d910a600-d0d1-11e9-8eda-e0e15e0e1a9c.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air 3rd Generation` with `iOS 13.1` running `1.12 (19.09.10.13)`:

![IMG_0021](https://user-images.githubusercontent.com/2602313/64627947-86c7d180-d3be-11e9-8db9-190a02b655ab.PNG)
![IMG_0020](https://user-images.githubusercontent.com/2602313/64627948-86c7d180-d3be-11e9-9c29-7683f650c4fc.PNG)
![IMG_0018](https://user-images.githubusercontent.com/2602313/64627950-86c7d180-d3be-11e9-9421-b2e831cb8042.PNG)
![IMG_0017](https://user-images.githubusercontent.com/2602313/64627951-86c7d180-d3be-11e9-819b-be8707506b92.PNG)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6s+` using `iOS 12.4.1` running `1.12 (19.09.13.06)`:

![IMG_9922](https://user-images.githubusercontent.com/2602313/64886086-66547d00-d633-11e9-916b-a49edfa67b2f.PNG)
![IMG_9921](https://user-images.githubusercontent.com/2602313/64886087-66547d00-d633-11e9-9b5d-986620cbaace.PNG)
![IMG_9920](https://user-images.githubusercontent.com/2602313/64886088-66547d00-d633-11e9-97f6-3e7662e64e3c.PNG)
![IMG_9919](https://user-images.githubusercontent.com/2602313/64886089-66547d00-d633-11e9-81df-996e217c2570.PNG)
