### ISSUE TITLE
Handle special characters in error description for FIDO/FIDO2

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1360]
### Description: 
Special characters in error descriptions for FIDO/FIDO2 result in javascript exceptions.

### Steps to Reproduce 
  1. Navigate to demo.yubico.com/u2f
  2. Insert the security key and wait for the timeout interval

**Actual result:** 
After timeout JS exception occurs

**Expected result:**
Should land on the result page with the correct error

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Comment by jhreis** [comment]
Should this be QA'd?

**Comment by jumde** [comment]
Added the test plan for QA

**Comment by kjozwiak** [comment]
@jumde I don't think this is working as expected. Whenever I let the `Use the security key` modal timeout after ~20s, I'm not seeing any errors being displayed nor am I being routed to a results page that displays an error. The modal basically disappears and the page keeps displaying `Insert and tap your Yubikey` with the animated spinner. Example:

![IMG_9864](https://user-images.githubusercontent.com/2602313/62968477-1dfa3300-bdd9-11e9-9c76-7a34a0a37564.PNG)

**Comment by LaurenWags** [comment]
Verified passed with iPad 5th Gen using 1.11.1 (19.08.12.19)
   - Verified STR from description
![IMG_4B02E32005DF-1](https://user-images.githubusercontent.com/28145373/62969296-f1471b00-bdda-11e9-9047-ffa4b56a644e.jpeg)

Verification **PASSED** on `iPhone 6s+ iOS 12.4` using `1.11.1 (19.08.13.17)`

* ensured that once the timeout occurs on both the `Register` & `Authenticate` modals under `demo.yubico.com/u2f`, an error message is correctly displayed and the page finishes loading.

![IMG_9867](https://user-images.githubusercontent.com/2602313/62971011-c363d580-bdde-11e9-940a-dce2fec4b6e6.PNG)
