### ISSUE TITLE
WebAuthn CBOR map keys in wrong order

### ISSUE THREAD

**Issue by agl** [brave/brave-ios#1365]
# Description: 

CTAP2 / WebAuthn require CBOR structures to follow [additional rules](https://fidoalliance.org/specs/fido-v2.0-ps-20190130/fido-client-to-authenticator-protocol-v2.0-ps-20190130.html#ctap2-canonical-cbor-encoding-form). These include that map keys be ordered lexicographically by encoding. When Brave creates an [attestation object](https://w3c.github.io/webauthn/#attestation-object), at least the `authData` and `fmt` keys are in the wrong order.

### Steps to Reproduce 
  1. Click the &ldquo;MTS WebAuthn&rdquo; button on the [Chromium test site](https://securitykeys.info/test_suite.html).
  2. Touch security key to complete registration.
  3. Note that the registration is rejected due to CBOR issues.

**Brave Version:** 1.11 (19.08.01.15)

**Device details:** iPhone 6s + Yubikey Lightning&amp;USB-C security key.

**Comment by conradcio** [comment]
@tomlowenthal I pushed a fix here https://github.com/YubicoLabs/yubikit-ios/commit/bda1a5df41cfe148b6b37ad240be6d97885295a1 
Let me know if you still have issue.

**Comment by jumde** [comment]
@conradcio - fixed with the fix above. thank you!

**Comment by srirambv** [comment]
@jumde  is the fix part of 1.11.3?

**Comment by jumde** [comment]
@srirambv - The fix should be part of 1.11.3, CBOR ordering should be fixed but there are other issues that have not yet been addressed for the Chromium test site.
