### ISSUE TITLE
Investigate Browser -> Website Automatic Darkmode

### ISSUE THREAD

**Issue by EyanGoldman** [brave/brave-ios#1367]
For iOS 13, on safari, if you visit Twitter.com, the website theme reflects the browser theme. The same does not happen on Brave. This is a useful feature which definitely deserves investigation.

**Comment by Brandon-T** [comment]
This happens automatically if the app itself supports DarkMode. It's from a Media-Query: `prefers-color-scheme` https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

Websites have to support it. But once the app supports dark-mode, it will automatically trigger on the website as well.

So in the screenshots below.. you can see darkmode is supported.. however, it does look weird when it's NOT the web-page.. IE: The menus are dark and light lol.. But webpages that support it look great.

<img width="370" alt="Screen Shot 2019-08-14 at 7 47 44 PM" src="https://user-images.githubusercontent.com/1530031/63063886-9392fb80-becc-11e9-9929-c8afa3d2993f.png">
![Simulator Screen Shot - iPhone X - 2019-08-14 at 19 46 49](https://user-images.githubusercontent.com/1530031/63063889-97268280-becc-11e9-902a-66b5595cc259.png)
<img width="370" alt="Screen Shot 2019-08-14 at 7 47 23 PM" src="https://user-images.githubusercontent.com/1530031/63063892-9988dc80-becc-11e9-825e-4a2fe661e0e7.png">

**Comment by jhreis** [comment]
We are supporting "dark mode", but not following the native iOS 13 implementation, as we want more control over our own theming. This will allow users to choose what their dark mode looks like, or allow us to provide fully alternative themes (e.g. private mode, purple theme).
