### ISSUE TITLE
WebAuthn doesn't work in private mode

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1373]
### Description: 
WebAuthn/U2F doesn't work in private mode

### Steps to Reproduce 
  1. Open a private tab
  2. Navigate to https://demo.yubico.com/u2f
  3. Initiate the registration process

**Actual result:** 
Registration fails

**Expected result:**
Registration should succeed.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Comment by jumde** [comment]
Will be fixed by: https://github.com/brave/brave-ios/pull/1375

**Comment by LaurenWags** [comment]
Verified passed with iPad 5th Gen using 1.11.1 (19.08.12.19)
   - Verified STR from description
![IMG_009C15198BC4-1](https://user-images.githubusercontent.com/28145373/62958602-0fa21c00-bdc5-11e9-95d5-3f781bf1caa0.jpeg)
![IMG_0400](https://user-images.githubusercontent.com/28145373/62958597-0add6800-bdc5-11e9-8e9f-f4c8c82d473b.PNG)

Verification **PASSED** on `iPhone 6s+ iOS 12.4` using `1.11.1 (19.08.12.19)`

* ensured that the STR from https://github.com/brave/brave-ios/issues/1373#issue-479312849 worked as expected

![IMG_9860](https://user-images.githubusercontent.com/2602313/62958777-6b6ca500-bdc5-11e9-8309-c620229a3200.PNG)
![IMG_9859](https://user-images.githubusercontent.com/2602313/62958778-6c053b80-bdc5-11e9-8c17-8fe6d49c9a15.PNG)
