### ISSUE TITLE
Add an option to enable Bookmarks as an option beside the URL bar

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1391]
### Description: 
Add an option to allow users to turn on a button beside the top left URL for one click bookmarks

@jamesmudgett to provide a design, inc where to put the option in settings and the text. 

### Test Plan:

- New bookmark toolbar icon should _not_ be visible on an upgrade
- New bookmark toolbar icon should _not_ be visible on a fresh install for iPhone (default _on_ for iPad)
- There should be a new setting that enables this button to be visible.
    - Changing this to _on_ should make the button visible immediately
    - On iPad, since the settings is in a form sheet, the button will appear on the toolbar, and should be visible (see screenshot in attached PR)
    - On iPhone, button should be visible upon closing the settings
- Turning the new setting _off_ should have the opposite effect (making button disappear immediately)

**Comment by jamesmudgett** [comment]
![bookmarks-button-ntp](https://user-images.githubusercontent.com/318119/62982827-0b8cf300-bdf3-11e9-89de-4e9c08156608.png)
![bookmarks-button](https://user-images.githubusercontent.com/318119/62982828-0b8cf300-bdf3-11e9-8dee-3f389e5ac9d3.png)

**Comment by jamesmudgett** [comment]
![bookmarks-button-ntp](https://user-images.githubusercontent.com/318119/62982856-20698680-bdf3-11e9-892f-382da368554b.png)
![bookmarks-button](https://user-images.githubusercontent.com/318119/62982857-20698680-bdf3-11e9-8b02-02ea73c5c0da.png)

**Comment by anthonypkeane** [comment]
Under **General**
Show Bookmarks Button

default = off

**Comment by jamesmudgett** [comment]
Setting should be in

General
Show Bookmarks Button

Can be below the Show Tabs Bar setting in General section

**Comment by Brandon-T** [comment]
Does this button automatically bookmark the current URL? Or does it open the bookmarks menu/screen?

**Comment by anthonypkeane** [comment]
Opens the bookmark screen

**Comment by iccub** [comment]
Add one more button in url bar with Rewards and see how little space there is

**Comment by anthonypkeane** [comment]
@bradleyrichter can we get a new 2D icon for the bookmark button as the 3D one stands out too much in this design.

**Comment by anthonypkeane** [comment]
![Screen Shot 2019-08-27 at 3 46 02 PM](https://user-images.githubusercontent.com/7606853/63806896-72210f00-c8d1-11e9-9b18-95578a0aca9c.png)

**Comment by jamesmudgett** [comment]
[Archive.zip](https://github.com/brave/brave-ios/files/3553023/Archive.zip)

**Comment by jamesmudgett** [comment]
<img width="923" alt="Screen Shot 2019-08-28 at 4 50 31 PM" src="https://user-images.githubusercontent.com/318119/63895162-f8158680-c9b3-11e9-829e-dc3e7c01869f.png">

**Comment by jhreis** [comment]
Making this platform agnostic.

**Comment by anthonypkeane** [comment]
Updating text to

**Under General**
Show Bookmarks Shortcut

default = off

**Comment by iccub** [comment]
@anthonypkeane what about default off for iPhones, default on for iPads?
We have much more space on iPad's address bar

**Comment by srirambv** [comment]
The first screenshot, is the bookmark icon/button shown when url is in edit mode as well? https://github.com/brave/brave-ios/issues/1391#issuecomment-525936711

**Comment by dnv** [comment]
I think the iPad should definately default to ”on” due to significantly more available space in the iPad address bar.

The iPhone: my device currently shows a ”Refresh” and ”Reading Mode” buttons between the address and the ”Shields” button. Сonstantly refreshing a page is not something a lot of people do on a constant basis, while opening bookmarks is. I would argue for the ”Refresh” button to go as tapping the address bar once followed by an ”Open” archieves the same result.

**Comment by srirambv** [comment]
I would suggest we get rid of the refresh button and replace it with bookmark button and bring back the pull-down refresh. One hand usage is def easy with pulldown refresh. This way we can solve the problem of spacing on iPhones

**Comment by kjozwiak** [comment]
@jhreis moving this into `1.12` as per earlier discussions 👍 

* [1] https://github.com/brave/brave-ios/milestone/24

**Comment by anthonypkeane** [comment]
Confirming. 
- default = off for iPhone
- default = on for iPad


@srirambv we'll come up with a more elegant solution soon. Pull to refresh is needed too, agree.

**Comment by kjozwiak** [comment]
@anthonypkeane @jhreis @srirambv are we worried about space? I guess this will be defaulted to `off` on iPhones so it's a users choice, but if a user ends up enabling both Rewards and Bookmarks, there won't be much space when it comes to the URL bar. We already have some users complaining about the URL space when they enable Rewards. Just a heads up 👍

**Comment by srirambv** [comment]
>but if a user ends up enabling both Rewards and Bookmarks, 

That was the idea behind suggesting this https://github.com/brave/brave-ios/issues/1391#issuecomment-526311767, removing the reload button and bring back pull-down refresh  


Screen size isn't as bad as Android since most of the iOS devices are pretty big except for iPhone SE  and 6 which is small. Other devices should be fine with the bookmarks button and rewards in URL bar.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 running 1.12(19.09.06.17)
* Verified on a clean install of 1.12, bookmark button is not shown next to the URL bar
* Verified on upgrade from Appstore build no bookmark button is shown next to the URL bar
* Verified on upgrade, setting for show bookmark button is disabled 
* Verified enabling Show bookmark button adds a button next to the URL bar
* Verified enabling bookmark button and removing the app from memory and relaunching retains the button and settings enabled
* Verified disabling the setting removes the button immediately 

Verification **PASSED** on `iPad Air 3rd Generation` using `iOS 13.1` running `1.12 (19.09.13.06)`:

* Verified that the bookmark button is enabled by default on clean installs
* Verified that the bookmark button is enabled by default when updating from `1.11.4 (19.08.29.21)`
* Verified that disabling/enabling the bookmark button correctly removes the UI
* Verified that disabled/enabled states are persisted when backgrounding Brave
* Verified that disabled/enabled states are persisted when removing Brave from memory
* Verified that bookmarks are not being lost when when going through the above

Verification passed on iPhone 7+ with iOS 12.4.1 running 1.12(19.09.13.06)
* Verified on a clean install of 1.12, bookmark button is not shown next to the URL bar
* Verified on upgrade from Appstore build no bookmark button is shown next to the URL bar
* Verified on upgrade, setting for show bookmark button is disabled 
* Verified enabling Show bookmark button adds a button next to the URL bar
* Verified enabling bookmark button and removing the app from memory and relaunching retains the button and settings enabled
* Verified disabling the setting removes the button immediately
