### ISSUE TITLE
tabs opened using "window.open" are lost when restarting brave

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#1397]
### Description: 

It seems like tabs that are opened via `target="_blank"` are lost when restarting brave.

### Steps to Reproduce 

**`Case #1:`**

  1. visit https://www.startpage.com
  2. search for `brave software` and click on a few results (these should open in new tabs)
  3. restart brave and you'll notice that the tabs opened via `startpage.com` have been lost

**`Case #2:`**

  1. visit https://www.gmail.com and login into an account
  2. open a few links from several emails (these should open in new tabs)
  3. restart brave and you'll notice that the tabs opened via `gmail.com` have been lost

**Actual result:** 

Example of the issue occurring --> https://youtu.be/TaI8-1fKMF4

**Expected result:**

Opened tabs should never be lost when restarting the browser

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* Using `1.11 (19.08.01.15)` - Reproduced
* Using `1.11.1 (19.08.13.17)` - Reproduced

**Device details:** 

* Using `iPhone 6s+ iOS 12.4`

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

@LaurenWags mind going through to see if you can reproduce the issue with your `iPad`? CCing @jhreis @anthonypkeane

**Comment by LaurenWags** [comment]
Case 1 and Case 2 reproduced with iPad 5th Gen using 1.11.1 (19.08.13.17).

**Comment by danishjafri88** [comment]
This is related to `window.open` which sends a callback in our code to open a popup. Popups are not restored right now. Fixing this now

**Comment by kjozwiak** [comment]
Thanks @danishjafri88 👍 @jhreis @anthonypkeane we should probably include this in the next release. Tab loss is never good :(

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 13.3.1` using `1.15 (20.03.04.18)`:

* Verified both cases outlined under https://github.com/brave/brave-ios/issues/1397#issue-480978507

Verification **PASSED** on `iPad Air 3rd Gen` running `iOS 13.3.1` using `1.15 (20.03.04.18)`:

* Verified both cases outlined under https://github.com/brave/brave-ios/issues/1397#issue-480978507

Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.15 (20.03.04.18)`

* Verified both cases outlined under https://github.com/brave/brave-ios/issues/1397#issue-480978507

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.15 (20.03.04.18)`

* Verified both cases outlined under https://github.com/brave/brave-ios/issues/1397#issue-480978507
