### ISSUE TITLE
stats not updating after upgrade to 1.11.1 and shields don't correctly reflect blocked ads/trackers - follow up to 1307

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#1398]
### Description: 
When upgrading from 1.11 to 1.11.1, the stats on NTP are retained. However, once you visit new sites, the shields on those sites will show `0 Ads and Trackers` blocked even when there are items blocked. Because of this, the `Ads & Trackers Blocked` and `Est. Time Saved` on the NTP don't update after upgrade.

Probably related to https://github.com/brave/brave-ios/issues/1307

### Steps to Reproduce 
1. Install app store version 1.11. Populate stats on NTP.
2. Update to 1.11.1 (19.08.13.17).
3. Verify stats are retained on NTP.
4. Visit some sites that have ads.
5. Shields will show 0 Ads and Trackers blocked with the toggle on.
6. Toggle Block Ads & Tracking off or Shields off. Ads will load on site, so there are Ads there.
7. Open NTP. Your `Ads & Trackers Blocked` and `Est Time Saved` values are the same as in 1.11. 

Note - HTTPS Upgrades does update on NTP, but the other two do not.

**Actual result:** 
Shields show 0 ads/trackers blocked, so some stats on NTP don't update.

![IMG_047247C023EE-1](https://user-images.githubusercontent.com/28145373/63101685-8ebf5d80-bf47-11e9-9fbc-27d07e2763b1.jpeg)

**Expected result:**
Shields to correctly reflect what is blocked. Also, stats on NTP to update.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.11 --> 1.11.1 upgrade.

**Device details:** 
iPad 5th Gen

**Website problems only:**
- did you check with Brave Shields down? n/a
- did you check in Safari/Firefox (WkWebView-based browsers)? n/a

### Additional Information
Here's the NTP stats for 1.11:
![IMG_0418](https://user-images.githubusercontent.com/28145373/63101883-01c8d400-bf48-11e9-9890-58914fc2b981.jpg)

Here are the NTP stats for 1.11.1 after visiting sites with ads/trackers. Note, only HTTPS Upgrades changed:
![IMG_39E3EE3D1E66-1](https://user-images.githubusercontent.com/28145373/63101911-11481d00-bf48-11e9-800a-661831d8d51a.jpeg)

**Comment by kjozwiak** [comment]
Reproduced on `iPhone 6s+ iOS 12.4` when upgrading from `1.11 (19.08.01.15)` --> `1.11.1 (19.08.13.17)`. Example:

![IMG_01AD09DCA52B-1 2](https://user-images.githubusercontent.com/2602313/63103424-1a86b900-bf4b-11e9-875f-3dfbbcadff29.jpeg)

This is `release/blocking` IMO. If users update to this release, NTP/Shield stats are basically broken which is one of our main features in Brave.

**Comment by jhreis** [comment]
Closed per reverting the rust library commit: 73f87a5ae

**Comment by LaurenWags** [comment]
iPad testing summary re: stats/upgrades:
1. Install `1.11` —> Upgrade to `1.11.3` - *PASS*
* with `1.11` from App Store, visit some sites and populate stats.
* updated using `1.11.3` from TF
* Verified post update that NTP stats updated when visiting sites and shields show # of ads/trackers blocked.
2. Install `1.11.2` —> Upgrade to `1.11.3` - *PASS*
* with `1.11.2` from App Store: added bookmarks, history, tabs, stats, cookie, logins/passwords, site specific shield settings, added custom sites to ‘favorites/top site tiles’, set up sync chain
* changed default search engines for Normal and Private tabs
* updated using `1.11.3` from TF
* verified version change (`1.11.2` -> `1.11.3`) and the following were retained: bookmarks, history, tabs, stats, cookie, login/password, site specific shield settings, custom sites in ‘favorites/top site tiles’, search engine setting, sync chain.
* Verified shields/stats issue was not encountered. Stats on NTP updated, count of ads/trackers blocked on shields on individual sites looked correct.
3. Install `1.11.1` —> Upgrade to `1.11.3` (skipping 1.11.2 install/upgrade) - *PASS*
* with `1.11.1` from TF: added bookmarks, history, tabs, stats, cookie, logins/passwords, site specific shield settings, added custom sites to ‘favorites/top site tiles’, set up sync chain
* changed default search engines for Normal and Private tabs
* updated using `1.11.3` from TF
* verified version change (`1.11.1` -> `1.11.3`) and the following were retained: bookmarks, history, tabs, stats, cookie, login/password, site specific shield settings, custom sites in ‘favorites/top site tiles’, search engine setting, sync chain.
* Verified shields/stats issue was not encountered. Stats on NTP updated, count of ads/trackers blocked on shields on individual sites looked correct.

**Comment by kjozwiak** [comment]
Basically went through the same cases as @LaurenWags mentioned above using `iPhone 6s+` using `iOS 12.4`. Update scenarios checked:

* `1.11 (19.8.1.15)` --> `1.11.3 (19.8.16.20)` - **PASSED**
* `1.11.1 (19.8.13.17)` --> `1.11.3 (19.8.16.20)` - **PASSED**
* `1.11.2 (19.8.15.18`) --> `1.11.3 (19.8.16.20)` - **PASSED**
