### ISSUE TITLE
WebAuthn timer should start from the time the JS API is invoked

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1402]
### Description: 
The code currently initiates the timer when the key is plugged in. The timer should start when the JS API is invoked.

### Steps to Reproduce 
  1. Navigate to demo.yubico.com/u2f
  2. Wait for 90 seconds

**Actual result:** 
No error

**Expected result:**
The request should timeout and an error should be displayed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.11

**Comment by iccub** [comment]
We removed yubico sdk in favor of built in webkit webauth api.
This will be reopened if the problem still occurs.
