### ISSUE TITLE
Numerous crashes in latest iOS release

### ISSUE THREAD

**Issue by pde** [brave/brave-ios#141]
I'm seeing numerous crashes in Brave 1.6.3 (18.07.27.16); about every third navigation event causes the app to crash! This seems to happen during or at the end of rendering the destination page; it's a flash of a black screen before the iOS home screen returns.

Running with shields down doesn't fix the problem.

**Comment by iccub** [comment]
Thanks for your report.

This repo is for upcoming Brave 2.0 release. The current app store version repo can be found here https://github.com/brave/browser-ios

We noticed crashes on the latest Brave version and fix for it is ready, we should release a hotfix release soon.
Issue on browser-ios repo https://github.com/brave/browser-ios/issues/1695

I'm going to close this ticket, feel free to comment on the issue I linked, to keep everything in one place.
