### ISSUE TITLE
Implement a single popup window flow for Security key

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1411]
### Description: 
Currently there are 2 popups that show up for security keys. One for connecting the device and second for touching the key to authenticate. The flow doens't look polished and can be enhanced to have a single poup that updates without having to close and relaunch 

### Steps to Reproduce 
  1. Visit a site that supports security key
  2. Popup shows up to connect
  3. Connect the key, popup is dismissed and a second popup comes up to touch to authenticate

**Actual result:** 
Implement a single popup window flow for Security key

**Expected result:**
Have a single popup that animates based on the step to either insert/authenticate

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.11.3

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc: @karenkliu @jumde

**Comment by iccub** [comment]
We removed yubico sdk in favor of built in webkit webauth api.
This will be reopened if the problem still occurs.
