### ISSUE TITLE
Modal screens not taking full screen in iOS 13

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1414]
### Description: 
In iOS 13, view controllers presented modally don't take full screen space, see for example here https://miro.medium.com/max/866/1*JuPvxhMr1isAtYYXG-EDYQ.png

### Steps to Reproduce 
  1. Open app settings
  1. Observe that it is not full screen (see image)

**Actual result:** 
<img width="544" alt="Zrzut ekranu 2019-08-20 o 11 01 48" src="https://user-images.githubusercontent.com/6950387/63333806-54d0cb80-c33a-11e9-9622-dc9c2d874f7b.png">

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 running 1.12(19.09.06.17)
* Verified on a clean install the modal fills the complete screen
* Verified on upgrade the modal fills the complete screen
* Verified device orientation doesn't affect the modal when opened and is full screen

Verification **PASSED** on `iPad Air 3rd Generation` with `iOS 13.1` running `1.12 (19.09.07.03)`:

* ensured that the modal is correctly positioned on a clean install
* ensured that the modal is correctly position after updating from `1.11.4 (19.8.29.21)` to `1.12 (19.09.07.03)`
* ensured that the modal is being positioned correctly when switching between portrait and landscape mode
