### ISSUE TITLE
Add basic user onboarding experience.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1416]
## Description
Make a new onboarding experience for iOS.
Product spec: https://docs.google.com/document/d/1osrM-ljPmGtuV0igBcbtrG1GVXthBs1AnVNODFFv9rQ/edit?ts=5cfed804&pli=1

#### iPhone
![loading](https://user-images.githubusercontent.com/2388823/63454220-38e32d80-c3ff-11e9-853f-e434ddfe9153.png)
![ios 1](https://user-images.githubusercontent.com/2388823/63454192-2963e480-c3ff-11e9-99ac-e13f1b07c5e9.png)
![ios 2 r1](https://user-images.githubusercontent.com/2388823/63454193-2963e480-c3ff-11e9-8072-4a4ab00280cc.png)

#### iPad
![12 9″ iPad Pro - screen 1](https://user-images.githubusercontent.com/2388823/63454310-6cbe5300-c3ff-11e9-9905-e194ad30d5d7.png)
![12 9″ iPad Pro - screen 2 r1](https://user-images.githubusercontent.com/2388823/63454363-8c557b80-c3ff-11e9-8fd6-e80e0f372fb9.png)

#### Animated transitions between screens
1. Loading --> Search engine screen
![loading](https://user-images.githubusercontent.com/2388823/63454810-5c5aa800-c400-11e9-963d-c842d11a265e.gif)
higher res video version: [loading.mp4.zip](https://github.com/brave/brave-ios/files/3526560/loading.mp4.zip)

2. General transitions between screens
When the white panel changes heights between screens, the height change and content should be animated for a smooth transition, for example (this is on Android):
![welcome transition out](https://user-images.githubusercontent.com/2388823/63454910-92982780-c400-11e9-9182-95a7ebebdc35.gif)

**Animation breakdown:** the content in the white panel fades out: start Opacity: 1, end Opacity: 1, duration 0.2s. The white bg resizes starting at T=0.1s to the appropriate height for the next screen, duration 0.3s.  The illustration and new text content fades in starting at T=0.3s: start Opacity: 0, end Opacity: 1, duration: 0.4s.

## Assets

Grab the assets: 
Search engine screen PNGs 
[png assets.zip](https://github.com/brave/brave-ios/files/3526573/png.assets.zip)

Shields screen motion graphic 
[shields.zip](https://github.com/brave/brave-ios/files/3526554/shields.zip)

Abstract link for more CSS and plain text: https://share.goabstract.com/bdad6a90-59ac-4735-ba48-673024c9c22e?sha=7f7b11dedded4529e4ce533acba202c280094a17

**Comment by karenkliu** [comment]
@iccub Design specs added for you!

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 running 1.12(19.09.06.17)
* Verified onboarding flow is shown on a clean install
* Verified SE changes made in onboarding is retained
[iOS_Onboarding.zip](https://github.com/brave/brave-ios/files/3586133/iOS_Onboarding.zip)

Verification **PASSED** on `iPad Air 3rd Generation iOS 13.1` running `1.12 (19.09.10.18)`:

* Verified that the onboarding experience specified under https://github.com/brave/brave-ios/issues/1416#issue-482751314 works as expected
* Verified that tapping on `Skip` correctly closes the onboarding modal
* Ensured that the onboarding experience doesn't reappear when relaunching Brave
* Ensured that the selected SE becomes default for both `Standard` & `Private Tabs`
* Ensured that the animations are smooth and not janky

Verification passed on iPhone 7+ with iOS 12.4.1 running 1.12(19.09.13.06)
* Verified onboarding flow is shown on a clean install
* Verified SE changes made in onboarding is retained
