### ISSUE TITLE
Full Screen does not work in Desktop Site

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#1419]
### Description: 

When using a Desktop site / UA, full screen videos do not work.

### Steps to Reproduce 
  1. Go to website with a video (e.g. youtube)
  2. Request desktop site
  3. Full screen unavailable

**Actual result:** 
No full screen

**Expected result:**
Full screen

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
* Verification passed on iPhone XR with iOS 13. 1 beta 2 running 1.12(19.09.07.08)
https://youtu.be/OI2DwYGJRug
* Verification **PASSED** on `iPad Air 3rd Generation iOS 13.1` running `1.12 (19.09.10.18)`
* Verification passed on iPhone 7+ with iOS 12.4.1 running 1.12(19.09.13.06)
