### ISSUE TITLE
Bookmarks don't get added inside a new folder

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1421]
### Description: 
Bookmarks don't get added inside a new folder

### Steps to Reproduce 
  1. Clean install 1.12
  2. Visit any site
  3. Open menu-> Bookmarks -> Create a new bookmark folder -> Navigate inside the new bookmark folder
   4. Add the site as bookmark under the new folder
   5. Bookmark isn't added under the new folder

**Actual result:** 
https://youtu.be/6DjN_g4kxYE

**Expected result:**
Bookmark should be added inside the new folder

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.12

**Device details:** 
iPhone 7+ (iOS 12.4)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
What's wrong with the video you posted?

You add a new folder at root level there.

When adding a folder from Bookmarks the folder is added at current location.
If you want to specify a save location you have to add it via `Add with` button

**Comment by srirambv** [comment]
@iccub  that's a weird way to add the bookmark IMO. `Add to...` should probably be renamed to `Add bookmark` or merged with the `Bookmarks` option. Instinctively tapping on the bookmarks button gives a sense that you are adding a new bookmark.

**Comment by jhreis** [comment]
@srirambv it is because you aren't necessarily adding a bookmark, you could be adding a favorite, but really a point of discussion for design / product, as this is "to-spec".

cc'ing @jamesmudgett, @anthonypkeane

**Comment by kylehickinson** [comment]
Closing as stale and meets spec
