### ISSUE TITLE
App crashing at launch on iOS 12(TF build)

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1426]
### Steps to Reproduce 
  1. Launch the app

**Actual result:** 
It crashes

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 
Testflight build

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Happens on iOS 12 only

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.06.17)
* Verified no crash after upgrade from previous build
* Verified no crash on clean install launch

Verification **PASSED** on `iPad Air 3rd Generation` with `iOS 13.1` running `1.12 (19.09.07.03)`:
* Verified no crash after upgrade from previous build
* Verified no crash on clean install launch

Verification **PASSED** on `iPad Mini 4` with `iOS 12.4.1` running `1.12 (19.09.07.03)`:
* Verified no crash after upgrade from previous build
* Verified no crash on clean install launch

Verification passed on iPhone 7+ with iOS 12.4.1 running 1.12(19.09.13.06)
* Verified no crash after upgrade from the previous build
* Verified no crash on clean install launch
