### ISSUE TITLE
iPad Onboarding Graphics

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1428]
## Problem Description  
Please design animated graphics for the iPad onboarding

Internal Chat: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1566584614372900?thread_ts=1566579515.366700&cid=C06UXF3KJ

**Comment by karenkliu** [comment]
@anthonypkeane let's close this one; this should be covered by onboarding v2.

**Comment by anthonypkeane** [comment]
closing as superseded by a new design
