### ISSUE TITLE
Profile.profile saving to documents directory in Beta Builds

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1429]
I checked and this only happens on Beta/TF builds, it's due to differences between bundle identifier and a shared container id.

Verification Steps:
- Go into iOS File app and verify that there is no visible `profile.profile` file / folder.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.6.21)
* Verified on a clean install no `profile.profile`  file is created in files folder
* Verified on a clean install, downloading a file doesn't create `profile.profile` file
* Verified on upgrade from Appstore build, no `profile.profile` file is created
* Verified on upgrade from Appstore build, downloading a file doesn't create `profile.profile` file

Verification **PASSED** on `iPad Air 3rd Generation` using `iOS 13.1` running `1.12 (19.09.12.18)`:

* Verified on a clean install no `profile.profile`  file is created in files folder
* Verified on a clean install, downloading a file doesn't create `profile.profile` file
* Verified on upgrade from Appstore build, no `profile.profile` file is created
* Verified on upgrade from Appstore build, downloading a file doesn't create `profile.profile` file

Verification passed on iPhone 7+ with iOS 12.4.1 running 1.12(19.09.13.06)
* Verified on a clean install no `profile.profile`  file is created in files folder
* Verified on a clean install, downloading a file doesn't create `profile.profile` file
* Verified on upgrade from Appstore build, no `profile.profile` file is created
* Verified on upgrade from Appstore build, downloading a file doesn't create `profile.profile` file
