### ISSUE TITLE
Setting text updates

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1431]
### Description: 

Please title cap the following in settings

- [x] Block all Cookies (currently small c)
- [x] Report a Bug (currently small b)

In Show Tabs Bar:
- [x] Never Show (currently small s)
- [x] Always Show (currently small s)
- [x] Show in Landscape Only (currently small l and o)

Internal Chat: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1566622684384900?thread_ts=1566622584.382100&cid=C06UXF3KJ

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.06.21)
![image](https://user-images.githubusercontent.com/17010094/64466937-88ee0f80-d0e2-11e9-94d2-31598f9fd25b.png)
![image](https://user-images.githubusercontent.com/17010094/64466948-8be90000-d0e2-11e9-9494-13afa28fdd35.png)

Verification **PASSED** on `iPad Air 3rd Generation` with `iOS 13.1` running `1.12 (19.09.10.13)`:

![IMG_0023](https://user-images.githubusercontent.com/2602313/64631518-415ad280-d3c5-11e9-8f4d-d945121b1cdc.PNG)
![IMG_0022](https://user-images.githubusercontent.com/2602313/64631519-415ad280-d3c5-11e9-8d89-198cd7b0177c.PNG)

Verification **PASSED** on `iPhone 6s+` using `iOS 12.4.1` running `1.12 (19.09.13.06)`:

![IMG_9915](https://user-images.githubusercontent.com/2602313/64884033-aebd6c00-d62e-11e9-8d28-86290380b39c.PNG)
![IMG_9914](https://user-images.githubusercontent.com/2602313/64884034-aebd6c00-d62e-11e9-8079-42eb988bca32.PNG)

**Comment by kjozwiak** [comment]
@iccub the following settings menu isn't available under `iPad`:

* Never Show
* Always Show
* Show in Landscape Only

Is the above expected?

**Comment by anthonypkeane** [comment]
We don't have it in 1.11.4 @kjozwiak on iPad

**Comment by kjozwiak** [comment]
@anthonypkeane correct, the submenu isn't available for `iPad` under `1.11.4 (19.8.29.21)` either. Just wanted to double check to make sure this is expected 👍
