### ISSUE TITLE
New tab page - can't immediately open bookmarks

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#1432]
### Description: 
When opening a new tab prior to 1.10, you could use the hamburger menu in the top left to open bookmarks.

Starting with 1.10, the hamburger menu is gone in favor of the ellipsis menu in the bottom right. However, this is hidden by the virtual keyboard

### Steps to Reproduce 
  1. Have a profile on Brave 1.10 or newer with bookmarks
  2. Open a new tab
  3. Try to open bookmarks

**Actual result:**
- Focus is on URL bar and you can type
- You can click the tiles that show
- In order to see the ellipsis menu, you need to do something to hide the virtual keyboard
![image](https://user-images.githubusercontent.com/4733304/63741017-0d6da200-c848-11e9-93e7-2a00874cf8b9.png)

**Expected result:**
There should be a way to open bookmarks without having to swipe to hide the virtual keyboard

**Reproduces how often:** 
100%

**Comment by bsclifton** [comment]
Possible solution - show a "Bookmarks" tile:
https://github.com/brave/brave-ios/issues/1334

**Comment by bsclifton** [comment]
**Quick roundup of mentions of this issue**

- Community: `My bookmark icon disappeared`
https://community.brave.com/t/my-bookmark-icon-disappeared/74139

- Community: `Position of the meatball bar button on the footer bar`
Meatball bar meaning the ellipsis (aka kabob menu)
https://community.brave.com/t/position-of-the-meatball-bar-button-on-the-footer-bar/73717

- Community: `Bookmarks on the left hand side`
Probably the most comprehensive feedback
https://community.brave.com/t/bookmarks-on-the-left-hand-side/73436

- Community: `New 1.10 iOS release hides bookmarks`
Lots of great feedback here
https://community.brave.com/t/new-1-10-ios-release-hides-bookmarks/73388

- Community: `Bookmark button`
User mentions top right, but I think they mean bottom right (they do say, in the `...`). Two +1's
https://community.brave.com/t/bookmark-button/76587 

- Community: `Bookmarks diffictul to acceess on iOS (version 1.11 (19.08.01.15))`
https://community.brave.com/t/bookmarks-diffictul-to-acceess-on-ios-version-1-11-19-08-01-15/75256

- > @brave it’s minor but I really liked in the previous iOS version how bookmarks were 1 tap away (sidebar reveal). With the latest update they’re 2 taps. Any way we can get it back to 1? 😅
https://twitter.com/conlan/status/1164389372046692352

- > @brave Not super happy about the extra tap needed to access bookmarks on the iOS app now, especially as bookmarks are the thing I access *the most* in Brave. All that for a couple of extra millimetres on the address bar, like anyone was begging for that 😢
https://twitter.com/jasonfist/status/1157406003459166218

- > No, have also complained. Bookmarks and Share with buttons are the 2 most important functions I use when browsing on iOS.
   >
   > Terrible decision and strongly hope it’s reversed.
https://twitter.com/con_news/status/1159079065107730432

- > @brave seriously your iOS app need work:
   > 1) address bar should suggest stuff from bookmarks
   > 2) bookmarks should have a filter/find bar
https://twitter.com/SlakingGO/status/1160963131331489805

- > @brave why was the bookmarks button removed from the top, next to address bar in iOS? Now I need two more taps just to get to the bookmarks. It was great where it was.
https://twitter.com/jrguay/status/1159454313120509952

- > @BraveSupport This account has been verified by MetaCert@brave not digging the new iOS update that requires 3 clicks to launch a bookmarked webpage. Bookmarks should be its own button on bottom right of screen
https://twitter.com/DugganJared/status/1157064971664203777

- Anecdotal - from my wife 😄 She was not happy about this and said it was a regression in her opinion

**Comment by iccub** [comment]
Another solution is not to show up keyboard upon opening a new tab.

**Comment by anthonypkeane** [comment]
As a short term solution https://github.com/brave/brave-ios/issues/1391 is a good fix

Longer term we need a solution, perhaps a fully custom toolbar

**Comment by jhreis** [comment]
Closing in favor of: https://github.com/brave/brave-ios/issues/1391
