### ISSUE TITLE
Should not show the "alternative search engine" bar when only one search is active

### ISSUE THREAD

**Issue by pes10k** [brave/brave-ios#1437]
I only have DDG as an active search engine, but I still get the "above the keyboard" alternate search engine field

![IMG_529CBF3602C6-1](https://user-images.githubusercontent.com/76526/63790852-09c13600-c8af-11e9-984d-8c8ba6416fb9.jpeg)
![IMG_226585765164-1](https://user-images.githubusercontent.com/76526/63790853-09c13600-c8af-11e9-9004-2a839252f765.jpeg)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.18.17)
- Verified test plan from #2140
- Verified when two different SE is set for normal/private tab quick SE bar is shown along with any other SE enabled
------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified test plan from #2140
- Verified when two different SE is set for normal/private tab quick SE bar is shown along with any other SE enabled
------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.18.17)
- Verified test plan from #2140
- Verified when two different SE is set for normal/private tab quick SE bar is shown along with any other SE enabled
------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified test plan from #2140
- Verified when two different SE is set for normal/private tab quick SE bar is shown along with any other SE enabled
------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.18.17)
- Verified test plan from #2140
- Verified when two different SE is set for normal/private tab quick SE bar is shown along with any other SE enabled
------
