### ISSUE TITLE
Add 'downloads' folder for downloaded files

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1438]
This folder should be excluded from backups

**Comment by iccub** [comment]
Test plan:
- open https://www.thinkbroadband.com/download and download a file
- go to Files.app and look for Brave folder
- verify the downloaded file is placed in `Downloads` folder

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOs 13.1 running 1.12(19.09.06.21)
* Verified as per test plan from https://github.com/brave/brave-ios/issues/1438#issuecomment-529030419
![image](https://user-images.githubusercontent.com/17010094/64466764-aff81180-d0e1-11e9-81ce-d4d59650ca1b.png)
![image](https://user-images.githubusercontent.com/17010094/64466768-b38b9880-d0e1-11e9-8a09-ef407ee88104.png)
![image](https://user-images.githubusercontent.com/17010094/64466769-b71f1f80-d0e1-11e9-9cc6-adf3e6dfa6a8.png)

Verification **PASSED** on `iPad Air 3rd Generation` with `iOS 13.1` running `1.12 (19.09.07.03)`:

![IMG_0005](https://user-images.githubusercontent.com/2602313/64577339-0ebfc400-d34a-11e9-8d95-ffeee08a61e2.PNG)
![IMG_0006](https://user-images.githubusercontent.com/2602313/64577346-12534b00-d34a-11e9-9220-d86825a6fb92.PNG)
![IMG_0004](https://user-images.githubusercontent.com/2602313/64577347-12534b00-d34a-11e9-862b-7855de64841a.PNG)

Verification passed on iPhone 7+ with 12.4.1 running 1.12(19.09.13.06)
![image](https://user-images.githubusercontent.com/17010094/64884917-d31a4800-d630-11e9-8dfb-522efdc1fb84.png)

**Comment by ViRb3** [comment]
May I ask why the Downloads folder is excluded from backups? I just switched phones, restored my backup, wiped the old phone, just to find that all the files I had downloaded were missing. I agree that it is my fault for not checking before, but I did not anticipate this "feature".
