### ISSUE TITLE
Project does not compile for Testing

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#144]
Currently the project does not compile when built for testing (⌘+⇧+U) or running unit tests (⌘+U) due to the many removals/changes made in v2

This is required before any of the unit tests related issues (#102, #103, etc.) may be worked on

**Comment by iccub** [comment]
I work on tests, and for now I use a separate schema and unit test target.
I think for unit tests it will be the best to be able to run them in Fennec scheme(have a habit of running tests before pushing a PR or something) so we need to solve it anyway.
Firefox had a lot of different schemes/targets with different sets of tests enabled, I guess for buddybuild pipelines.

**Comment by kylehickinson** [comment]
Yeah, I enabled testability only for `Fennec`, so now you can actually compile the project for testability (though I have not tested how many of these tests fail now)
