### ISSUE TITLE
Add support for Adblock Rust library

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1442]
# Test Plan
See #1441

# 
Follow up to #1307

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6S+ iOS 12.4.1` using the following test cases:

* Upgraded from `1.11.3 (19.08.16.20)` --> `1.11.4 (19.08.29.21)` and ensured
   * stats under NTP were retained and displayed correctly
   * visiting new websites correctly updated the NTP and updated the stats
   * clicking on the shields panel correctly displayed the correct stats for that particular site
   * ensured that the above cases also worked under PB and NTP/Shields stats were being updated
* Installed `1.11.4 (19.08.29.21)` and ensured the same above cases were working as expected
* Installed `1.11.4 (19.08.29.21)` and quickly loaded `twitter.com`, `reddit.com`, `fb.com`, `buzzfeed.com` and ensured NTP/Shield stats were being updated right away

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 12.4.1 running 1.11.4(19.08.29.21)
* Verified stats are retained during upgrade from 1.11.3 to 1.11.4
* Verified visiting new sites updates stats on  NTP
* Verified stats update on visiting sites from Private tab as well
* Verified shields shows correct stats for each site
* Verified removing app from memory and relaunch updates the stats from previous session
* Verified switching between normal and private tabs retain the stats

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 PB1 running 1.11.4(19.08.29.21)

* Verified stats are retained during upgrade from 1.11.3 to 1.11.4
* Verified visiting new sites updates stats on NTP
* Verified stats update on visiting sites from Private tab as well
* Verified shields shows correct stats for each site
* Verified removing app from memory and relaunch updates the stats from previous session
* Verified switching between normal and private tabs retain the stats

**Comment by LaurenWags** [comment]
Verification passed on iPad 5th Gen with iOS 12.3.1 for update to 1.11.4(19.08.29.21)
* Installed 1.11.3 from app store and
   * added bookmarks, history, tabs, stats, cookie, login/password, site specific shield settings, custom sites to Favorites
   * set default search engine to DDG for normal and private tabs
* Updated to 1.11.4(19.08.29.21) using TF. 
   * Verified version change 1.11.3 --> 1.11.4
   * Verified stats are retained during upgrade from 1.11.3 to 1.11.4
   * Verified visiting new sites updates stats on  NTP
   * Verified stats update on visiting sites from Private tab as well
   * Verified shields shows correct stats for each site
   * Verified removing app from memory and relaunch updates the stats from previous session
   * Verified switching between normal and private tabs retain the stats
   * Verified the following data was retained: bookmarks, history, tabs, cookie, login/password, site specific shield settings, custom sites in Favorites, search engine setting.
   * Verified search engine settings could be changed after upgrade.
