### ISSUE TITLE
Block the "try Chrome” dialogue

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1450]
## Problem Description  
All new user will get the "try Chrome” dialogue when they open google.com

I suggest we block this dialogue

![File.jpg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/9c5fae6c-4819-4516-8093-06876ed80828)

Need input from @tomlowenthal

**Comment by iccub** [comment]
Requires cosmetic filters https://github.com/brave/brave-ios/issues/2683
