### ISSUE TITLE
Make DuckDuckGo the default search engine in the following countries

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1451]
## Description 

Please make DuckDuckGo the default search engine in the following countries:

- Germany
- Australia
- New Zealand
- Ireland

This is for NEW users only

Onboarding will need to be updated

 ## QA Steps

1. Switch device to one of the above locales
1. Install Brave
1. Verify preselected on-boarding option is DDG

**Comment by srirambv** [comment]
~This is failing on all 4 locales. @jhreis @iccub is this still dependant on  https://github.com/brave/internal/issues/648?  If so we need to reopen the issue as #1473 doesn't seem to have fixed this~
Seems to be working now.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air 3rd Generation` with `iOS 13.1` running `1.12 (19.09.07.03)`:

* ensured that `DDG` is selected via the onboarding experience when installing Brave under `Germany`, `Australia`, `New Zealand` and `Ireland`
   * ensured that `DDG` is being used under `Standard Tab` and `Private Tab` when skipping onboarding
   * ensured that `DDG` is being  under `Standard Tab` and `Private Tab` when completing onboarding

Also ensured that updating `1.11.4 (19.08.29.21` to `1.12 (19.09.07.03)` doesn't launch the onboarding experience and leaves the search engines to whatever was selected previously.

![IMG_0007](https://user-images.githubusercontent.com/2602313/64578468-7f1c1480-d34d-11e9-84cd-864e28620797.PNG)

**Comment by kjozwiak** [comment]
> This is failing on all 4 locales. @jhreis @iccub is this still dependant on [brave/internal#648](https://github.com/brave/internal/issues/648)? If so we need to reopen the issue as #1473 doesn't seem to have fixed this

@srirambv seems to be working for my on the iPad. I basically change the `Region` via `Settings` to one of the regions mentioned under https://github.com/brave/brave-ios/issues/1451#issue-486639120 and DDG is the search engine that's selected when the onboarding experience launches on new installs.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.07.08)
* Verified DDG was on top of the list of SE during onboarding and selected by default
* Verified skipping the onboarding process retained DDG as default SE for both normal/private tabs
* Verified finishing the onboarding process retained DDG as default SE for both normal/private tabs
* Verified opening an NPT doesn't prompt DDG modal if no change is made during onboarding
* Logged #1515 for not showing DDG modal when a different SE is set during onboarding other than DDG

Verification passed on iPhone 7+  with iOS 12.4.1 running 1.12(19.09.13.06)
* Verified DDG was on top of the list of SE during onboarding and selected by default
* Verified skipping the onboarding process retained DDG as default SE for both normal/private tabs
* Verified finishing the onboarding process retained DDG as default SE for both normal/private tabs
* Verified opening an NPT doesn't prompt DDG modal if no change is made during onboarding
