### ISSUE TITLE
Refactor Menu Logic

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#1452]
### Description: 

The new menu (`MenuViewController`) is extremely tightly coupled to the associated actions (download manager, bookmarks, history, etc...), and should bubble these actions up to a delegate. There is also a two-way coupling between `BrowserViewController` and `MenuViewController`. This is problematic for certain actions that may be triggered outside of the menu vc (e.g. displaying bookmark panel).

There are a few options but one is to build out a BVC Menu Helper that an object owned by BVC but is also coupled to handle presentations (similar to how MenuVC and BVC function, but wouldn't be bound by the parent-child relationship). 

This way it can become a `MenuDelegate` and be "passed" into the Menu (as a delegate), while abstracting away actual actions from the `MenuVC`, since it is owned by BVC (prevents increasing more bloat on BVC), it could also be called into directly, and handle toolbar related actions. (e.g. inside of BVC: `self.menuHelper.openBookmarks()`)

Bookmark menu is a good place to see where the current architecture falls short. There are (as of this filing), two method to trigger the bookmark menu, and has lead to duplicate logic 🤢😁

**Comment by iccub** [comment]
Invalid since the new menu change https://github.com/brave/brave-ios/pull/3465
