### ISSUE TITLE
Text changes

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1453]
### Description: 
Please change the following copy

> Add to... --> Add Bookmark

Update the iOS13 copy as follows: 

iPad specific one here: 
> Always request desktop site --> Request Desktop Site
(default is on)

**Comment by anthonypkeane** [comment]
Linked to https://github.com/brave/brave-ios/issues/1431 so we may want to do both at the same time

**Comment by srirambv** [comment]
Isn't iPad going to have default desktop site loaded? Shouldn't it say `Request Mobile Site` ?

**Comment by anthonypkeane** [comment]
> Isn't iPad going to have default desktop site loaded? Shouldn't it say `Request Mobile Site` ?
Yes, but I'm following Apple's lead on this one. See their iOS13 settings on the iPad. I don't think we should deviate, it might confuse users.

**Comment by anthonypkeane** [comment]
Small change after chatting with the man

Always request desktop site --> Always Request Desktop Site
(default is on)

**Comment by jhreis** [comment]
Default on for iPad, I'm assuming you meant?

**Comment by jhreis** [comment]
I am moving the theme copy choices out of this ticket, since that feature is not merged yet. That copy will be handled in the PR for themes itself.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 running 1.12(19.09.06.17)
![image](https://user-images.githubusercontent.com/17010094/64465069-a7e7a400-d0d8-11e9-9e61-01712e6c139b.png)
![image](https://user-images.githubusercontent.com/17010094/64465037-88507b80-d0d8-11e9-8682-23e74088cb95.png)

Verification **PASSED** on `iPad Air 3rd Generation` with `iOS 13.1` running `1.12 (19.09.10.13)`:

![IMG_0026](https://user-images.githubusercontent.com/2602313/64638186-4fafeb00-d3d3-11e9-973a-ff6e0a15e7e2.PNG)
![IMG_0025](https://user-images.githubusercontent.com/2602313/64638189-4fafeb00-d3d3-11e9-86b0-0f55e9f96786.PNG)

Verification **PASSED** on `iPhone 6s+` using `iOS 12.4.1` running `1.12 (19.09.13.06)`:

![IMG_9913](https://user-images.githubusercontent.com/2602313/64883774-23dc7180-d62e-11e9-8ecb-52d951a3e627.PNG)
![IMG_9912](https://user-images.githubusercontent.com/2602313/64883775-23dc7180-d62e-11e9-80a2-fd875af38423.PNG)
