### ISSUE TITLE
UIWebView deprecation notice

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1459]
UIWebView is deprecated and may result in rejecting the app in App Store.
We have to remove it.
Currently we use it in UserAgent creation and KIF framework uses it.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air 3rd Generation` using `iOS 13.1` running `1.12 (19.09.12.18)`:

<img width="1565" alt="Screen Shot 2019-09-13 at 2 21 36 AM" src="https://user-images.githubusercontent.com/2602313/64841501-40948d00-d5cd-11e9-8973-b07b65dccbb3.png">

UA for `iPad Air` running `iOS 13.1` via `1.12 (19.09.11.22)` :point_up: (both desktop/mobile)

<img width="1492" alt="Screen Shot 2019-09-13 at 2 24 16 AM" src="https://user-images.githubusercontent.com/2602313/64841614-9bc67f80-d5cd-11e9-9665-67a71b3c9b37.png">

UA for `iPad Air` running `iOS 13.1` via `1.12 (19.09.11.14)` :point_up: (both desktop/mobile)

<img width="1573" alt="Screen Shot 2019-09-13 at 2 25 46 AM" src="https://user-images.githubusercontent.com/2602313/64841683-d29c9580-d5cd-11e9-8dee-b736f00212d2.png">

UA for `iPad Mini 4` running `iOS 12.4.1` via `1.12 (19.09.11.22)` :point_up: (both desktop/mobile)

<img width="1519" alt="Screen Shot 2019-09-13 at 2 27 19 AM" src="https://user-images.githubusercontent.com/2602313/64841765-0a0b4200-d5ce-11e9-9a8f-a678c8af261f.png">

UA for `iPad Mini 4` running `iOS 12.4.1` via `1.12 (19.09.11.14)` :point_up: (both desktop/mobile)

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 12.4.1 running 1.12(19.09.13.06)
Mobile:
![Mobile7+](https://user-images.githubusercontent.com/17010094/64871400-309f9c00-d613-11e9-8a64-6797ba44f617.png)
Desktop:
![iPhone Desktop UA](https://user-images.githubusercontent.com/17010094/64871529-65135800-d613-11e9-853b-fac0edc73048.png)

Verification passed on iPhone XR with iOS 13.1 running 1.12(19.09.13.06)
Mobile:
![mobxr](https://user-images.githubusercontent.com/17010094/64872106-950f2b00-d614-11e9-8d30-e513f7c54ee2.png)
Desktop:
![deskxr](https://user-images.githubusercontent.com/17010094/64872093-8fb1e080-d614-11e9-85a6-adeed14e3b77.png)
