### ISSUE TITLE
Option to limit pasteboard availability in private browsing

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#146]
### Steps to Reproduce 
  1. Enter private browsing
  2. Visit any website
  3. Copy/cut text from either the URL or page content

**Actual result:** User can paste content from the pasteboard on any of their iOS devices configured for iOS Handoff

**Expected result:** Data leakage should not be possible whilst private browsing

**Reproduces how often:** Everytime

**Brave Version:** 2.0 (18.08.06.15)

**Device details:** iPad Pro 10.5" (iOS 11.4.1)

### Additional Information 

Users should have the choice especially with cut and paste which I am sure we all use on a regular basis, but to increase privacy is it worth considering adding an expiry date to pasteboard items thereby giving users the convenience of copy paste but reducing the chance of data leakage. And we could also consider limiting the pasteboard to the local device and not across all the users devices (using iOS handoff) whilst using Private Browsing

**Comment by tildelowengrimm** [comment]
Copy and paste are well-understood standard user gestures. We should not subvert them unless the user has specifically asked us to. I don't think that entering private browsing mode is a sufficient signal that break the well-worn functionality of copy/paste. Copy and paste should work normally unless a user has deliberately chosen to enable a setting which limits them.

**Comment by jhreis** [comment]
This can optionally be a custom setting, but now need design feedback/input.

**Comment by anthonypkeane** [comment]
Right now we don't want to create a setting for this, therefore:

While in private mode, anything in the pasteboard should be destroyed after 45 seconds
Handoff should also be disabled.

**Comment by tildelowengrimm** [comment]
We shouldn't interfere with copy/paste or Handoff. Spoke with @anthonypkeane and I think we're okay just taking a pass on this.
