### ISSUE TITLE
Option to See On-boarding from Settings

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#1463]
### Description: 

Currently on-boarding is only available for new users, with no ability to re-see without uninstalling / reinstalling.

We should add an option to see these screens again.

**Comment by kylehickinson** [comment]
Needs info: Now that rewards opt-in is included in onboarding, how would we let users see the onboarding again?

**Comment by iccub** [comment]
closing as we work on new onbarding flow https://github.com/brave/brave-ios/issues/4298
we may reconsider adding something like this later
