### ISSUE TITLE
Bootstrap.sh - failed to build "BraveRewardsUI" in BraveRewards.xcodeproj

### ISSUE THREAD

**Issue by majd-asab** [brave/brave-ios#1464]
### Description: 
I followed the instructions to setup the repository locally, but im running into an issue at the 'sh ./bootsrap.sh' step.

The bootstrapping goes all the way till it reaches "BraveRewardsUI" and then fails with exit code 65.

### Steps to Reproduce 
  1. clone repo
  2. run 'sh ./bootstrap.sh'

**Actual result:** 

> *** Building scheme "BraveRewardsUI" in BraveRewards.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/majd/Documents/openSource/brave-ios/Carthage/Checkouts/brave-rewards-ios/BraveRewards.xcodeproj -scheme BraveRewardsUI -configuration Release -derivedDataPath /Users/me/Library/Caches/org.carthage.CarthageKit/DerivedData/10.3_10G8/brave-rewards-ios/1cdecece79e49eca0ce5dc53fad215ca66747858 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/6g/bjt_yyrs0jn31x6pwnn71g080000gn/T/brave-rewards-ios SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/majd/Documents/openSource/brave-ios/Carthage/Checkouts/brave-rewards-ios)

> This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/6g/bjt_yyrs0jn31x6pwnn71g080000gn/T/carthage-xcodebuild.g9egpH.log

I opened the xcodebuild log and the issue is in one of the code line:

> <module-includes>:1:1: warning: umbrella header for module 'pop' does not include header 'POPVector.h'
#import "Headers/POP.h"
^
/Users/me/Documents/openSource/brave-ios/Carthage/Checkouts/brave-rewards-ios/BraveRewardsUI/Tipping/TippingViewController.swift:41:7: error: use of unresolved identifier 'isModalInPresentation'
      isModalInPresentation = true
      ^~~~~~~~~~~~~~~~~~~~~

>** ARCHIVE FAILED **

>The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Expected result:**
finish bootstrapping successfully

### Additional Information
Swift version: 5

**Comment by kylehickinson** [comment]
@majd-asab If you are building against the `development` branch, you have to use Xcode 11 (beta 6 or 7 preferably) because we are adopting iOS 13 API's. Please retry with Xcode 11. If you have it installed, make sure you use the `xcode-select` CLI command to point to the beta. Thanks!
