### ISSUE TITLE
bring back the search page and show desktop site options

### ISSUE THREAD

**Issue by AoiYui** [brave/brave-ios#1465]
**Problem Description:** 
I don't really see why these features would be removed in the first place being functions that pretty much every mobile browser in existence. 

**Feature Overview:** pretty self explanatory you'd be adding a unction that should exist an a browser 

**Design:** no need

**Implementation Details:**  should be pretty easy to implement given that it was there and was just removed because ... reasons.

**User Experience:** do I really need to explain this?

**Additional information:** sorry if I come off as rude and/or sarcastic but again why would a basic feature that should exist removed?

**Comment by srirambv** [comment]
https://github.com/brave/brave-ios/issues/1019 was implemented for find in page. When you start editing the URL you get the dropdown that says `On this page`.

Request desktop site is available when you long press on the refresh button and also available in `Share with...` menu.
