### ISSUE TITLE
iOS 13 breaks contextual menu

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#1466]
### Steps to Reproduce 
  1. Long press an image to download
  2. iOS native long press menu appears
  3.

**Actual result:** 

**Expected result:**

Should display our contextual menu

**Reproduces how often:** Easily reproduced

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jamesmudgett** [comment]
Actually this might have been customized a little. Does seem like we lost some options like open image in new tab. Also, we may want to add “Download Image” and “Download linked file” to contextual menu when possible.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.07.08)
* Verified able to save image via context menu
* Verified able to highlight a word shows the cotext menu and able to use all the options

Verification **PASSED** on `iPad Air 3rd Generation iOS 13.1` running `1.12 (19.09.10.18)`

![IMG_0030](https://user-images.githubusercontent.com/2602313/64663904-53676000-d41b-11e9-90db-983f568070e7.PNG)

* Verified that all of the above context items are working as expected
* Verified that the context menu items work for `links` and `text` as well

**Comment by kjozwiak** [comment]
> Also, we may want to add “Download Image” and “Download linked file” to contextual menu when possible.

@jamesmudgett @iccub has this implemented? I'm not seeing `Download linked file` anywhere in context menu's. If this is something we want implemented, do we have an issue filed?

**Comment by iccub** [comment]
It's not implemented atm

**Comment by kjozwiak** [comment]
> It's not implemented atm

@iccub do you know if we have an issue filed?

**Comment by iccub** [comment]
I don't think so @kjozwiak feel free to add it
