### ISSUE TITLE
Need a way to view download content

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#1467]
New download feature has no way to view download. Downloaded a jpg and wasn’t able to open for viewing. 

Would be great to use QL Preview controller here as it provides lots of native functionality and supports many different file types.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.19.15)
* Verified downloaded items shows preview window when clicked on the downloaded file in download sheet
* Verified PDF/JPEG/Gif images preview is shown 
![xrpreview](https://user-images.githubusercontent.com/17010094/69251423-5c914d80-0b7f-11ea-9065-2486bb908942.gif)
----------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.19.15)
* Verified downloaded items shows preview window when clicked on the downloaded file in download sheet
* Verified PDF/JPEG/Gif images preview is shown 
![7preview](https://user-images.githubusercontent.com/17010094/69253395-97e14b80-0b82-11ea-9e87-5014fe7448cc.gif)
----------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.19.15)
* Verified downloaded items shows preview window when clicked on the downloaded file in download sheet
* Verified PDF/JPEG/Gif images preview is shown 
![pad13preview](https://user-images.githubusercontent.com/17010094/69253871-543b1180-0b83-11ea-83b5-a4bfdf3ad497.gif)
----------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.19.15)
* Verified downloaded items shows preview window when clicked on the downloaded file in download sheet
* Verified PDF/JPEG/Gif images preview is shown 
![6preview](https://user-images.githubusercontent.com/17010094/69254676-9e70c280-0b84-11ea-9ec5-879de7bd7174.gif)
----------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.19.15)
* Verified downloaded items shows preview window when clicked on the downloaded file in download sheet
* Verified PDF/JPEG/Gif images preview is shown 
![pad12preview](https://user-images.githubusercontent.com/17010094/69253403-9b74d280-0b82-11ea-957b-7f3c8e0594d2.gif)
