### ISSUE TITLE
Use preferences over SQS for sync

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1470]

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.31.19)
* Verified test plan from #1569
* Verified all devices were listed and bookmarks sync'd
-------
Verification passed on iPhone 7 with iOS 13.2 running 1.13(19.10.31.19)
* Verified test plan from #1569
* Verified all devices were listed and bookmarks sync'd
-------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.31.19)
* Verified test plan from #1569
* Verified all devices were listed and bookmarks sync'd
-------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.31.19)
* Verified test plan from #1569
* Verified all devices were listed and bookmarks sync'd
-------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.31.19)
* Verified test plan from #1569
* Verified all devices were listed and bookmarks sync'd
