### ISSUE TITLE
Webcompat issue on BBC News

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1471]
### Description: 
I'm trying to go full screen on the video of the weather man but it is not working. 

Video of the issue on: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1567433535066100
https://www.bbc.com/news/world-latin-america-49541485

**Comment by jhreis** [comment]
@anthonypkeane would be helpful to get more information:

- device
- OS
- version of Brave

May help to follow the template.
etc...

**Comment by anthonypkeane** [comment]
device: iPad Pro
OS: 13 (beta 8)
version of Brave: 19.09.03.19



>May help to follow the template.

my bad

**Comment by iccub** [comment]
Seems to be working now.
