### ISSUE TITLE
Passcode doesn't screen update when the pin is entered

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1475]
### Description: 
Passcode doesn't screen update when the pin is entered

### Steps to Reproduce 
  1. Clean install 1.12(19.08.30.20)
  2. Enable Pin code
  3. Screen still says `Turn Pincode on`

**Actual result:** 
https://youtu.be/GeFtZrjbBxE

**Expected result:**
Should update the screen when passcode is entered 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.12(19.08.30.20)

**Device details:** 
iPhone XR

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Doesn't happen to me on iPhone 7 iOS 12
I'm updating my iPad to iOS13 and going to recheck it

**Comment by iccub** [comment]
I can repro on iOS13

**Comment by srirambv** [comment]
added iOS 13 label to make it easy to track iOS 13 specific issues

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.06.21)
* Verified on clean install pin code screen updates correctly when enabled
* Verified on upgrade from AppStore build the pin code screen updates correctly when enabled

Verification **PASSED** on `iPad Air 3rd Generation` with `iOS 13.1` running `1.12 (19.09.10.13)`:
* Verified on clean install pin code screen updates correctly when enabled
* Verified on upgrade from AppStore build the pin code screen updates correctly when enabled
