### ISSUE TITLE
Multitasking window doesn't show Shields/Settings popup correctly

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1477]
### Description: 
Multitasking window doesn't show Shields/Settings popup correctly

### Steps to Reproduce 
  1. Open any app
  2. Open brave as a multitasking app
  3. Open shields/settings 

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/64203131-d22f2c80-ce60-11e9-8e4c-bd151ca3260e.png)

![image](https://user-images.githubusercontent.com/17010094/64203119-cb081e80-ce60-11e9-9a19-df06b2c70e9b.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/17010094/64202979-7fee0b80-ce60-11e9-90d3-e9a20c9379c5.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.12(19.08.30.20)

**Device details:** 
iPad

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air 3rd Generation` using `iOS 13.1` running `1.12 (19.09.11.22)`:

![IMG_0056](https://user-images.githubusercontent.com/2602313/64749586-1f0ba680-d4e4-11e9-8935-231d730838d3.PNG)
![IMG_0054](https://user-images.githubusercontent.com/2602313/64749587-1f0ba680-d4e4-11e9-8e0f-69597248df57.PNG)

**Comment by kjozwiak** [comment]
@srirambv mind quickly checking this on your iPad to see if it's working as well?

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 13.1 running 1.12(19.09.11.22)
Landscape:
![image](https://user-images.githubusercontent.com/17010094/64791144-45156300-d545-11e9-9a42-0d698d00c72d.png)
![image](https://user-images.githubusercontent.com/17010094/64791165-4cd50780-d545-11e9-9016-1db839d8ae48.png)
![image](https://user-images.githubusercontent.com/17010094/64791157-49418080-d545-11e9-997f-def915e2a478.png)
![image](https://user-images.githubusercontent.com/17010094/64791185-53fc1580-d545-11e9-97fa-975d834d914b.png)
![image](https://user-images.githubusercontent.com/17010094/64791197-58283300-d545-11e9-839d-c9a3b26b0000.png)

Portrait:
![image](https://user-images.githubusercontent.com/17010094/64791108-36c74700-d545-11e9-930d-59a85e80f948.png)
![image](https://user-images.githubusercontent.com/17010094/64791123-3cbd2800-d545-11e9-9989-e8110b098e5d.png)
![image](https://user-images.githubusercontent.com/17010094/64791134-4050af00-d545-11e9-85fc-aa9e71550320.png)
