### ISSUE TITLE
Translations missing for onboarding

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1486]
### Description: 
Translations missing for onboarding

### Steps to Reproduce 
  1. Set device language to French/German
  2. Clean install 1.12
  3. Welcome tour is not translated

**Actual result:** 
Translations missing for onboarding

**Expected result:**
Should be translated

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.12

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
@anthonypkeane ok to skip translations until next release?

**Comment by iccub** [comment]
Nevermind, there is https://github.com/brave/brave-ios/pull/1511 ready and we will get those strings into 1.12

**Comment by iccub** [comment]
Fixed in https://github.com/brave/brave-ios/pull/1511

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.11.14)
French:
![image](https://user-images.githubusercontent.com/17010094/64715727-00c78b80-d48f-11e9-84cf-23d14c5a10b8.png)
![image](https://user-images.githubusercontent.com/17010094/64715735-058c3f80-d48f-11e9-8bf6-066cd8bf46ea.png)

German:
![image](https://user-images.githubusercontent.com/17010094/64715719-fc02d780-d48e-11e9-8894-ceed42562c6d.png)
![image](https://user-images.githubusercontent.com/17010094/64715686-f5746000-d48e-11e9-97c9-b58f0341fe62.png)

Japanese:
![image](https://user-images.githubusercontent.com/17010094/64715766-0e7d1100-d48f-11e9-8a3a-f5540d5ed117.png)
![image](https://user-images.githubusercontent.com/17010094/64715752-0a50f380-d48f-11e9-8c98-0aa788cb423d.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air 3rd Generation` using `iOS 13.1` running `1.12 (19.09.11.22)`:

### **`French:`**

<img width="368" alt="Screen Shot 2019-09-11 at 10 08 48 PM" src="https://user-images.githubusercontent.com/2602313/64748638-c7b80700-d4e0-11e9-8dd9-e213e0c52f1a.png">

<img width="371" alt="Screen Shot 2019-09-11 at 10 07 55 PM" src="https://user-images.githubusercontent.com/2602313/64748589-a0613a00-d4e0-11e9-80f0-db53780091ce.png">

### **`Polish:`**

<img width="368" alt="Screen Shot 2019-09-11 at 10 08 48 PM" src="https://user-images.githubusercontent.com/2602313/64748638-c7b80700-d4e0-11e9-8dd9-e213e0c52f1a.png">

<img width="380" alt="Screen Shot 2019-09-11 at 10 08 54 PM" src="https://user-images.githubusercontent.com/2602313/64748637-c71f7080-d4e0-11e9-828c-088fb788baaf.png">

### **`Russian:`**

<img width="360" alt="Screen Shot 2019-09-11 at 10 10 16 PM" src="https://user-images.githubusercontent.com/2602313/64748687-fb932c80-d4e0-11e9-895f-7ceeb225a966.png">

<img width="372" alt="Screen Shot 2019-09-11 at 10 10 25 PM" src="https://user-images.githubusercontent.com/2602313/64748686-fb932c80-d4e0-11e9-97f5-7b90b3438303.png">

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 12.4.1 running 1.12(19.09.13.06)
German:
![image](https://user-images.githubusercontent.com/17010094/64885561-7fa8f980-d632-11e9-9adf-110df9d1c6ad.png)
![image](https://user-images.githubusercontent.com/17010094/64885565-833c8080-d632-11e9-9f8a-be65e497ecfe.png)

Japanese:
![image](https://user-images.githubusercontent.com/17010094/64885621-9cddc800-d632-11e9-9a08-5059b5b43837.png)
![image](https://user-images.githubusercontent.com/17010094/64885615-98191400-d632-11e9-8653-8e73d2f29dae.png)

French:
![image](https://user-images.githubusercontent.com/17010094/64885652-a9622080-d632-11e9-970b-9ef63f88d1dd.png)
![image](https://user-images.githubusercontent.com/17010094/64885644-a404d600-d632-11e9-9eb5-a815c1e77597.png)
