### ISSUE TITLE
Switching to PB mode only causes theme to mix up 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1488]
### Description: 
Switching to PB mode only causes theme to mix up 

### Steps to Reproduce 
  1. Set theme to light/dark
  2. Enable PB mode only from settings
  3. Scroll up/down
  4. Buttons colour changes when its out of view 

**Actual result:** 
Issue on Light theme: [LightTheme.zip](https://github.com/brave/brave-ios/files/3580722/LightTheme.zip)
Issue on Dark theme: [DarkTheme.zip](https://github.com/brave/brave-ios/files/3580723/DarkTheme.zip)

**Expected result:**
Should change the entire settings page theme when PB mode only is toggled

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.12(19.9.4.23)

**Device details:** 
iPhone XR (iOS 13)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
Fixed per b0ee4717872972abd4bcaeae417b325abc17ddf3

**Comment by srirambv** [comment]
* Verification passed on iPhone XR with iOS 13.1 running 1.12(19.09.07.08) [theme.zip](https://github.com/brave/brave-ios/files/3593102/theme.zip)
* Verification **PASSED** on `iPad Air 3rd Generation iOS 13.1` running `1.12 (19.09.10.18)`:

* Verification passed on iPhone 7+ with  12.4.1 running 1.12(19.09.13.06)
