### ISSUE TITLE
Add the ability for users to give their email address to us so we can keep in touch

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1489]
### Description: 
Users tell us that they would like to keep in touch with Brave and receive the odd email newsletter / update.

This ticket is to enable a way that users, can if they wish, provide their email.

Exact Spec TBD

Linked to: https://github.com/brave/internal/issues/753

## Designs

Show a "Get privacy tips" banner the first time user visits a search results page.

![image](https://user-images.githubusercontent.com/2388823/107405586-56f19180-6abc-11eb-8ac6-e5af62d28a78.png)

Show banner one time only.

Dark theme is the same as light theme.

## Assets
Figma: https://www.figma.com/file/atoL4LN2kd8ILnPGwohUoV/?node-id=2154%3A26868

**Comment by kylehickinson** [comment]
Awaiting spec, should answer these questions:

- What service are we using to send these emails too
- Where will the privacy policy for storage of those emails go
- How does the design shown handle with NTP stuff
- What's the logic around when to show it

**Comment by karenkliu** [comment]
Designs added!

**Comment by anthonypkeane** [comment]
> Awaiting spec, should answer these questions:
> 
> * What service are we using to send these emails too
> * Where will the privacy policy for storage of those emails go


> * How does the design shown handle with NTP stuff
> * What's the logic around when to show it

Working with @aekeus @kylehickinson to gather the technical info. Marketing are managing the privacy aspects with the relevant teams.  

Designs added as you can see
