### ISSUE TITLE
Do not force portrait mode when device is in landscape 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1491]
### Description: 
Do not force portrait mode when the device is in landscape 

### Steps to Reproduce 
  1. Keep device in landscape mode
  2. Open settings page
  3. Switches to portait mode
   4. Close settings, remains on portrait mode unless the device is rotated to portrait and back to landscape

**Actual result:** 
Do not force portrait mode when device is in landscape 

**Expected result:**
Should auto detect device orientation and switch back to landscape when settings page is closed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.12

**Device details:** 
iPhone XR (iOS13

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Follow up to #867

**Comment by jonathansampson** [comment]
Similarly, the browser will switch to portrait mode when you open the tipping panel while in landscape. This was recently reported by [a user on Twitter](https://twitter.com/tomoyanTweet/status/1272703954900512768):

![tipping-panel](https://user-images.githubusercontent.com/815158/84723184-a4782780-af4a-11ea-95bb-8a029b2e3bac.gif)
