### ISSUE TITLE
Support Dark Mode

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#1493]
## Problem Description 

Support dark mode!

## Feature Overview 

iOS 13 announced dark mode support, and we should support this.

## User Experience 

   - iOS 13 will auto-detect the OS theme, and be themed appropriately
   - Both iOS 12 and 13 will give users option between light/dark mode

## QA Steps

- Verify User Experience toggles / options are correct
- General coloring throughout application. This touches most of the app

### Additional information

🎉

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.11.15)
* Verified clean install automatically chooses the system default theme for the browser
* Verified on upgrade theme is set to default and uses system theme 
* Verified setting light theme on the browser when the device is on dark changes complete browser UI to the light theme
* Verified setting dark theme on the browser when the device is on light changes complete browser UI to dark theme
* Verified setting dark/light theme doesn't affect private browsing window
* Verified changing theme from action centre immediately updates the browser UI to the current theme when its set to automatic
* Verified changing theme from action centre doesn't update the browser UI to the current theme when its set to explicit light/dark

Verification **PASSED** on `iPad Air 3rd Generation` using `iOS 13.1` running `1.12 (19.09.11.22)`:

* Verified clean install automatically chooses the system default theme for the browser
* Verified on upgrade theme is set to default and uses system theme 
* Verified setting light theme on the browser when the device is on dark changes complete browser UI to the light theme
* Verified setting dark theme on the browser when the device is on light changes complete browser UI to dark theme
* Verified setting dark/light theme doesn't affect private browsing window
* Verified changing theme from action centre immediately updates the browser UI to the current theme when its set to automatic
* Verified changing theme from action centre doesn't update the browser UI to the current theme when its set to explicit light/dark 

Verification passed on iPhone 7+  with iOS 12.4.1 running 1.12(19.09.13.06)
* Verified clean install automatically sets the light theme for the browser
* Verified on upgrade theme is set to default and uses system theme(Light)
* Verified updating theme in browser setting take effect immediately
