### ISSUE TITLE
Toolbar Theming Cleanup

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#1494]
## Description

The bottom and top toolbars are currently a bit goofy. One of the main reasons being how intelligent they are about their own coloring states. It was compounded further when individual top and bottom toolbar coloring was supported (e.g. `TabsButton(top: true)`) via #1324 1493

This is probably best done by `appearance()` (see `AppearanceExtensions.swift`).

Specific button colors can be manipulated based on their parent container:
e.g. (something like, the below pseudo-code):
```
ToolbarButton.appearance(whenContainedInInstancesOf: [TopToolbar.self]).appearanceBackgroundColor = // some color
```

At least these places should be cleaned up:
- [ ] ToolbarButton
- [ ] TabsButton

## Test Plan

iPhone:
- [ ] Verify top and bottom toolbar coloring works for all themes
- [ ] Verify top and bottom toolbar buttons are correctly colored for all themes

iPad:
- [ ] Verify top toolbar coloring works for all themes
- [ ] Verify top toolbar buttons are correctly colored for all themes

**Comment by iccub** [comment]
Invalid since the new theming changes https://github.com/brave/brave-ios/pull/3606
