### ISSUE TITLE
3D Touch flicker on iPhone 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1496]
### Description: 
3D Touch flicker on iPhone 

### Steps to Reproduce 
  1. Install 1.12 
  2. Visit any page
  3. 3D touch any hyperlink or image, peek view flickers while opening 

**Actual result:** 
https://youtu.be/Vjv_Ngjtro8

**Expected result:**
No flicker while showing the peek view

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced on iPhone XR but @kylehickinson  mentioned he wasn't able to reproduce it on his iPad

**Brave Version:** 
1.12(19.09.05.20)

**Device details:** 
iPhone XR with iOS 13.1 beta 2

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Found while testing #1080. Not blocking 1.12 on this hence not assigned to any milestone

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.07.03)
* Verified no 3D touch on links bring up the page preview
* Verified no image preview pops up with 3D touch
* Logged #1512 for context menu 

Verification passed on iPhone 7+  with iOS 12.4.1 running 1.12(19.09.13.06)
* Verified no 3D touch on links bring up the page preview
* Verified no image preview pops up with 3D touch

**Comment by kjozwiak** [comment]
Labelling this is `iPhone` as `3D Touch` isn't available on iPad's.
