### ISSUE TITLE
Polish preview menu on iOS13

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1499]
### Description: 
As discussed internally, we need to polish our long-press peek/pop menu

Internal Chat: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1567782520135600

**Comment by srirambv** [comment]
Verification passed on iPhone Xr with iOS 13.2 running 1.13(19.10.16.18)
* Verification passed on normal tab
![image](https://user-images.githubusercontent.com/17010094/67035337-7e626500-f0e7-11e9-8647-af44de2dff2a.png)
* Verification passed on private tab
![image](https://user-images.githubusercontent.com/17010094/67035349-83bfaf80-f0e7-11e9-96b0-522b2b808e5b.png)


Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.16.18)
* Verification passed on normal tab
![image](https://user-images.githubusercontent.com/17010094/67035391-90dc9e80-f0e7-11e9-9417-be14e7002a18.png)
* Verification passed on private tab
![image](https://user-images.githubusercontent.com/17010094/67035323-786c8400-f0e7-11e9-9c59-209e90586493.png)

Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.10.16.18)
* Verification passed on normal tab
![image](https://user-images.githubusercontent.com/17010094/67035402-96d27f80-f0e7-11e9-9aa1-02426405c08b.png)
* Verification passed on private tab
![image](https://user-images.githubusercontent.com/17010094/67035371-8c17ea80-f0e7-11e9-8eb0-ddfb7452d2d5.png)
