### ISSUE TITLE
Show Tabs Bar Options

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1500]
## Problem Description  

Most iOS users of Brave are coming from Safari. 

Safari doesn't have tabs so it may be odd for new users to see them

I suggest we change the default of Show Tabs Bar  from

Always Show
to
Show in Landscape Only

cc @jamesmudgett @jhreis and @srirambv for ideas

**Comment by kylehickinson** [comment]
Any updates for this @jamesmudgett @jhreis @srirambv?

Personally I like the tab bar. Do we get much negative feedback about it?

**Comment by ghost** [comment]
Perhaps Brave's tabs by default is a feature that people appreciate? Though more settings might be helpful for different opinions.

Safari's inclusion of a share button in the bottom toolbar is greatly missed in both Brave and Firefox for iOS. I hate having to tap settings or tap URL to share a page.

Letting people customize their layout would be really nice.
