### ISSUE TITLE
Warn message for sync isn't properly highlighted

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1501]
### Description: 
Warn message for sync isn't properly highlighted

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/64460207-d741e500-d0c7-11e9-8d76-6df96a03a8d7.png)
![image](https://user-images.githubusercontent.com/17010094/64460309-107a5500-d0c8-11e9-8837-5d895d26a29d.png)

**Expected result:**
Similar to Android
![image](https://user-images.githubusercontent.com/17010094/64460380-3ef83000-d0c8-11e9-9579-628934e6bbeb.png)
![image](https://user-images.githubusercontent.com/17010094/64460395-49b2c500-d0c8-11e9-810d-35cefeebb0e6.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.12(19.09.06.17)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Also noted the tabs for `QR Code` and `Code Words` are not highlighted in Orange similar to Android 

cc: @jamesmudgett

**Comment by iccub** [comment]
The segmented control component changed in iOS 13, I'm going to change the selected tint color of it, so it looks like this. Bg and text colors are different depending on theme used, this is iOS 13 only change

<img width="363" alt="Zrzut ekranu 2019-11-18 o 17 15 33" src="https://user-images.githubusercontent.com/6950387/69069826-6f910a00-0a27-11ea-83a1-eead80c3d119.png">

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.20.19)
* Verified warn message is properly highlighted
* Verified segmented control has the correct colour as per https://github.com/brave/brave-ios/issues/1501#issuecomment-555090389
![image](https://user-images.githubusercontent.com/17010094/69347214-13ee9880-0c42-11ea-885f-5f2c01a181ee.png)
![image](https://user-images.githubusercontent.com/17010094/69347226-181ab600-0c42-11ea-9ca2-41208d636181.png)

---

Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.20.19)
* Verified warn message is properly highlighted
* Verified segmented control has the correct colour as per https://github.com/brave/brave-ios/issues/1501#issuecomment-555090389
![image](https://user-images.githubusercontent.com/17010094/69347281-2c5eb300-0c42-11ea-9812-2709a6df3198.png)
![image](https://user-images.githubusercontent.com/17010094/69347271-28329580-0c42-11ea-88c5-ba84b1c9d9a7.png)

---

Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.20.19)
* Verified warn message is properly highlighted
* Verified segmented control has the correct colour as per https://github.com/brave/brave-ios/issues/1501#issuecomment-555090389
![image](https://user-images.githubusercontent.com/17010094/69347317-3d0f2900-0c42-11ea-9d81-b5928ba2fdf7.png)
![image](https://user-images.githubusercontent.com/17010094/69347327-40a2b000-0c42-11ea-86cd-4d54e96de7d7.png)

---

Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.20.19)
* Verified warn message is properly highlighted
* Logged follow up issue #2001 for iOS 12 

---

Verification **PASSED** on `iPhone 6s+` running `iOS 12` using `1.14(19.11.20.19)`

* Verified that the sync warning message is correctly being highlighted
* Verified that both `QR Codes` & `Code Words` toggles are correctly themed
* Created https://github.com/brave/brave-ios/issues/2008 & https://github.com/brave/brave-ios/issues/2006

![IMG_9930](https://user-images.githubusercontent.com/2602313/69359920-90d83d00-0c57-11ea-9c0b-12753175a6ce.PNG)

![IMG_9929](https://user-images.githubusercontent.com/2602313/69359921-90d83d00-0c57-11ea-88cf-dc558af3a5dc.PNG)
