### ISSUE TITLE
Issue when moving from Dark to Light mode and vice versa

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1503]
### Description: 
Set Brave to Auto theme
Then move iOS13 from Dark to Light and vice versa

Brave is not changing and gets a bit messed up. 

Internal Chat: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1567811535145600

### Steps to Reproduce 
  1. as above

**Actual result:** 
Display mode is not adjusting automatically with the OS

**Expected result:**
Display mode should adjust automatically with the OS

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easy

**Brave Version:** 
19.9.6.17

**Device details:** 
iPhone Xs on iOS13 Beta 8

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
Fixing this for the primary browser UI, but see follow up ticket for additional clarity: https://github.com/brave/brave-ios/issues/1506

**Comment by jhreis** [comment]
Test plan in PR.

**Comment by srirambv** [comment]
This is still an issue if the settings page is opened when changing the theme from the action centre. 
@iccub do you want me to open a new issue for this?
[1503.zip](https://github.com/brave/brave-ios/files/3590484/1503.zip)

**Comment by iccub** [comment]
@srirambv  is it the same as https://github.com/brave/brave-ios/issues/1506?

**Comment by srirambv** [comment]
Somewhat similar yes

**Comment by iccub** [comment]
I think you can add this info to that ticket https://github.com/brave/brave-ios/issues/1503#issuecomment-529454092 and we will fix it here

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.07.03)
* Verified the theme change via control panel automatically changes the browser theme 
* Added comment in #1506 for https://github.com/brave/brave-ios/issues/1503#issuecomment-529454092

Verification **PASSED** on `iPad Air 3rd Generation` using `iOS 13.1` running `1.12 (19.09.11.22)`:

* Verified the theme change via control panel automatically changes the browser theme
