### ISSUE TITLE
HBO GO doesn't play because of invalid address. 

### ISSUE THREAD

**Issue by Lucas-Kohorst** [brave/brave-ios#1504]
### Description: 
HBO GO cannot play because of an "invalid address"

### Steps to Reproduce 
  1. Navigate to hbogo.com
  2. Click "start watching"

**Actual result:** 
Popup saying "Cannot open page. Brave cannot open page because it has an invalid address"

**Expected result:**
Watch shows on HBO go

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 

**Device details:** 

Version 1.11.3 (19.08.16.20)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Now hbo seems to force you to download the app, closing as stale
