### ISSUE TITLE
Beta upgrade creates profile.profile files

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1505]
### Description: 
Beta upgrade creates profile.profile files

### Steps to Reproduce 
  1. Install 1.11.4 
  2. Upgrade to 1.12
  3. Creates profile.profile files in file.app

**Actual result:** 
Beta upgrade creates profile.profile files

**Expected result:**
SHould not create  files

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.12(19.09.06.17)

**Device details:** 
iPhone XR (iOS 13.1) 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
This only happens on Beta app in TF and not on release version

**Comment by iccub** [comment]
This will go away once you start upgrading from 1.12 -> 1.13 or newer

**Comment by kylehickinson** [comment]
Can this be closed?
