### ISSUE TITLE
Browser Menus do not Respond to Light/Dark OS Theme Changes

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#1506]
### Description: 

Most menus inside Brave to do not respond to OS dark / light theme changes. 

From a technical perspective, this is an opportunity to clean up menu usage through out application and make parent -> child UI relationships more definitive.

When BVC gets a trait collection update (BVC responds correctly), it should be able to propagate an `applyTheme` update down to all presented VC's and children. This includes having a handle on settings, and all nested menus.

This also breaks the tight coupling we often have throughout the application where children often dismiss themselves (meaning they know how they are being presented).

### Steps to Reproduce 
  1. Make sure theme selection is "automatic"
  1. Open settings (or main menu / shields panel)
  2. Change the OS system theme
  3. Observe settings screen is not dynamically updated (also happens with other menus)

**Actual result:** 

![Image of wrong colored main menu when theme changed](https://user-images.githubusercontent.com/2781690/64469306-5684e800-d0cb-11e9-977d-632d9f3b5857.jpg)
![Image of wrong colored shield panel when theme changed](https://user-images.githubusercontent.com/2781690/64469307-58e74200-d0cb-11e9-8435-8973bdf77564.jpg)

**Expected result:**

All menus should be styled correctly.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 

Related #1503

**Comment by srirambv** [comment]
This is also a problem when app is in settings page and you try to change theme from action menu. Recording in https://github.com/brave/brave-ios/issues/1503#issuecomment-529454092

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(21.5.25.18)
- Verified steps from issue description
- Verified theme updates correctly for menu/shields/rewards while open, when theme is changed via control centre
---------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.26(21.5.25.18)
- Verified steps from issue description
- Verified theme updates correctly for menu/shields/rewards while open, when theme is changed via control centre
--------
Verification passed on iPad Pro with iOS 14.5.1 running 1.26(21.5.25.18)
- Verified steps from issue description
- Verified theme updates correctly for menu/shields/rewards while open, when theme is changed via control centre
