### ISSUE TITLE
crash when transitioning from portrait vs landscape when context menu is opened

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#1513]
### Description: 

Whenever you have a context menu opened, switching from `portrait` to `landscape` crashes Brave.

### Steps to Reproduce 
  1. search for an image on google.com
  2. tap and hold on an image so the context menu appears
  3. once the context menu is opened, transition from portrait to landscape mode

**Actual result:** 

Example: https://youtu.be/xBtNBpMr3ec

**Expected result:**

Brave shouldn't be crashing when transitioning from portrait to landscape mode while a context menu is opened.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% using the above STR.

**Brave Version:** 

* `1.12 (19.09.07.03)` - Reproduced
* `1.11.4 (19.08.29.21)` - Reproduced

**Device details:** 

* `iPad Air 3rd Generation` using `iOS 13.1`
* `iPad Mini 4` using `iOS 12.4`

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @anthonypkeane @srirambv @jhreis

**Comment by srirambv** [comment]
Can't reproduce it on an iPhone. Looks like an iPad only issue
https://youtu.be/r2JBha5esUg

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air 3rd Generation iOS 13.1` running `1.12 (19.09.10.18)`

* Verified the original test case outlined via https://github.com/brave/brave-ios/issues/1513#issue-491390033 (both in normal and PB modes)
* ensured that switching between portrait and landscape doesn't cause any crashes
