### ISSUE TITLE
Add support to Auto-Close Tabs

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1514]
### Description: 
iOS 13 added the option for user to auto close tabs. We should add this option also.

@jamesmudgett and @anthonypkeane to figure out settings as this option needs to go in there and settings is getting big. 

https://www.macrumors.com/how-to/auto-close-old-safari-tabs-in-ios/
Internal Chat: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1568050266166200

**Comment by anthonypkeane** [comment]
@jamesmudgett I suggest

Under Display, 

Add the following option:

Close Tabs 
-Manually 
-After One Day
-After One Week
-After One Month

(same as iOS13)

Please confirm?

**Comment by aaronsantamaria** [comment]
+1 
https://community.brave.com/t/feature-request-close-all-tabs-and-auto-close-idle-tabs-after-x-days/182861/2

**Comment by anthonypkeane** [comment]
Given default browser this is more important now. Can we move forward with this @iccub

**Comment by iccub** [comment]
should not take long to implement @anthonypkeane, need design for it though

**Comment by xndyz** [comment]
This would be an incredible feature. How do we move forward on the design?

**Comment by iccub** [comment]
@fandy i would try to look here https://community.brave.com/c/brave-feature-requests
and add new topic it if it has not been added already

I will try to play with it this week, should be simple to add

**Comment by jamesmudgett** [comment]
Icon
[Archive.zip](https://github.com/brave/brave-ios/files/6206323/Archive.zip)

**Comment by anthonypkeane** [comment]
Search GDrive for "Close stale tabs mini-spec" - lets rock

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(21.5.28.14)
- Verified test plan from https://github.com/brave/brave-ios/pull/3699
------------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.26(21.5.28.14)
- Verified test plan from https://github.com/brave/brave-ios/pull/3699
------------
Verification passed on iPad Pro with iOS 14.5.1 running 1.26(21.5.28.14)
- Verified test plan from https://github.com/brave/brave-ios/pull/3699
------------
