### ISSUE TITLE
DDG modal is not prompted when a different SE is set during onboarding 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1515]
### Description: 
DDG modal is not prompted when a different SE is set during onboarding 

### Steps to Reproduce 
  1. Set device to DE/IE/NZ/AU
  2. Change to `Qwant` during onboarding
  3. Open a new private tab, no DDG modal is prompted

**Actual result:** 
[PBSE.zip](https://github.com/brave/brave-ios/files/3593357/PBSE.zip)

**Expected result:**
Should prompt DDG as default SE for the first private tab when a different SE is set in onboarding

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.12(19.09.07.08)

**Device details:** 
iPhone XR (iOS 13.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Found while testing #1415

**Comment by iccub** [comment]
This is intended we don't show the popup in countries with ddg set as default engine. @anthonypkeane do you think we should change it

**Comment by iccub** [comment]
This needs a product decision bumping to next release

**Comment by anthonypkeane** [comment]
@iccub the DDG modal should always be displayed when a user first enters PB mode

**Comment by srirambv** [comment]
DDG modal should be shown the first time PB mode is enabled for all regions except Qwant supported regions

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 running 1.12(19.09.10.13)

Go through onboarding:

* Set region to IE, follow through onboarding, DDG set as default in onboarding and in settings for normal/private. Open new private tab, no DDG modal shown
* Set region to IE, follow through onboarding, DDG set as default in onboarding, select custom SE in onboarding, updates SE in setting for both normal/private tab. Open new private tab, DDG modal shown
* Set region to the US, follow through onboarding, Google set as default in onboarding and in settings for normal/private. Open new private tab, DDG modal shown
* Set region to the US, follow through onboarding, Google set as default in onboarding, select custom SE in onboarding, updates SE in setting for both normal/private tab. Open new private tab, DDG modal shown

Skip Onboarding:

* Set region to IE, skip onboarding, DDG set as default in settings for normal/private. Open new private tab, no DDG modal shown
* Set region to the US, skip onboarding, Google set as default in settings for normal/private. Open new private tab, DDG modal shown

Verification **PASSED** on `iPad Air 3rd Generation` using `iOS 13.1` running `1.12 (19.09.11.22)`:

Go through onboarding:

* Set region to IE, follow through onboarding, DDG set as default in onboarding and in settings for normal/private. Open new private tab, no DDG modal shown
* Set region to IE, follow through onboarding, DDG set as default in onboarding, select custom SE in onboarding, updates SE in setting for both normal/private tab. Open new private tab, DDG modal shown
* Set region to the US, follow through onboarding, Google set as default in onboarding and in settings for normal/private. Open new private tab, DDG modal shown
* Set region to the US, follow through onboarding, Google set as default in onboarding, select custom SE in onboarding, updates SE in setting for both normal/private tab. Open new private tab, DDG modal shown

Skip Onboarding:

* Set region to IE, skip onboarding, DDG set as default in settings for normal/private. Open new private tab, no DDG modal shown
* Set region to the US, skip onboarding, Google set as default in settings for normal/private. Open new private tab, DDG modal shown

Verification passed on iPhone 7+  with iOS 12.4.1 running 1.12(19.09.13.06)

Go through onboarding:

* Set region to IE, follow through onboarding, DDG set as default in onboarding and in settings for normal/private. Open new private tab, no DDG modal shown
* Set region to IE, follow through onboarding, DDG set as default in onboarding, select custom SE in onboarding, updates SE in setting for both normal/private tab. Open new private tab, DDG modal shown
* Set region to the US, follow through onboarding, Google set as default in onboarding and in settings for normal/private. Open new private tab, DDG modal shown
* Set region to the US, follow through onboarding, Google set as default in onboarding, select custom SE in onboarding, updates SE in setting for both normal/private tab. Open new private tab, DDG modal shown

Skip Onboarding:

* Set region to IE, skip onboarding, DDG set as default in settings for normal/private. Open new private tab, no DDG modal shown
* Set region to the US, skip onboarding, Google set as default in settings for normal/private. Open new private tab, DDG modal shown
