### ISSUE TITLE
"Download Cancelled" hard to read on devices using iOS 12

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#1516]
### Description: 

When cancelling a download under `iOS 12`, it's really hard to read the `Download Cancelled` text that is displayed in the bottom toolbar.

### Steps to Reproduce 
  1. open `1.12 (19.09.07.03)`
  2. load https://www.thinkbroadband.com/download in a new tab 
  3. start downloading a larger file so you have time to cancel
  4. cancel the download via the `X` at the bottom of the download progress toolbar

**Actual result:** 

![IMG_0259](https://user-images.githubusercontent.com/2602313/64583245-5a7c6880-d35e-11e9-9808-7f952f29bb24.PNG)

**Expected result:**

![IMG_0010](https://user-images.githubusercontent.com/2602313/64583448-ef7f6180-d35e-11e9-9218-282f99e9259d.PNG)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* Using `1.12 (19.09.07.03)`

**Device details:** 

* `iPad Mini 4` running `iOS 12.4.1` - Reproduced
* `iPhone 6s+` running `iOS 12.4.1` - Reproduced
* `iPad Air 3rd Generation` running `iOS 13.1` - Couldn't reproduce

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @anthonypkeane @jhreis @srirambv

**Comment by iccub** [comment]
Needs design, bumping for next release

**Comment by srirambv** [comment]
* Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.16.18)
![image](https://user-images.githubusercontent.com/17010094/67034489-c8e2e200-f0e5-11e9-8e23-0340c8ad30c5.png)

* Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.16.18)
![image](https://user-images.githubusercontent.com/17010094/67034458-b8326c00-f0e5-11e9-91dc-7354d33686d9.png)
