### ISSUE TITLE
enabling auto suggestion buttons underneath URL hard to read when using light theme

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#1517]
### Description: 

When using the default/light theme, the `auto suggestion` but `Yes` and `No` buttons to enable auto suggestion are really hard to read compared to `1.11.4 (19.8.29.21)`.

### Steps to Reproduce 
  1. open `1.12 (19.09.07.03)` and ensure that you're using the light theme
  2. type something into the URL bar and notice that `Yes` and `No` are really hard to read

**Actual result:** 

<img width="791" alt="Screen Shot 2019-09-10 at 12 30 20 AM" src="https://user-images.githubusercontent.com/2602313/64584322-34f15e00-d362-11e9-8128-9f49a13fe7f9.png">

**Expected result:**

<img width="795" alt="Screen Shot 2019-09-10 at 12 29 45 AM" src="https://user-images.githubusercontent.com/2602313/64584288-1d19da00-d362-11e9-9c1b-4df7b384d04f.png">

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* Using `1.12 (19.09.07.03)`

**Device details:** 

* `iPad Mini 4` running `iOS 12.4.1` - Reproduced
* `iPhone 6s+` running `iOS 12.4.1` - Reproduced
* `iPad Air 3rd Generation` running `iOS 13.1` - Reproduced

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @srirambv @anthonypkeane @jhreis

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air 3rd Generation` with `iOS 13.1` running `1.12 (19.09.10.13)`:

<img width="786" alt="Screen Shot 2019-09-10 at 11 19 39 AM" src="https://user-images.githubusercontent.com/2602313/64627016-e7eea580-d3bc-11e9-9ca3-dafb58d6777c.png">
<img width="791" alt="Screen Shot 2019-09-10 at 11 19 28 AM" src="https://user-images.githubusercontent.com/2602313/64627018-e7eea580-d3bc-11e9-83f0-c5633cc4ee38.png">

* ensured that `Turn on search suggestions` isn't being displayed while in PB mode

**Comment by kjozwiak** [comment]
@iccub @jhreis @anthonypkeane should the `Yes` and `No` buttons be the same colour as in `1.11.4 (19.8.29.21)`? Right now it appears as light black/grey but originally we were using blue. Either way works, just wanted to make sure this is the expected behaviour/design.

**Comment by iccub** [comment]
It's intended, previously we haven't used any style for those buttons

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.10.13)
Light mode:
![image](https://user-images.githubusercontent.com/17010094/64642179-bd601500-d3db-11e9-8dea-ddc141069e38.png)

Dark mode:
![image](https://user-images.githubusercontent.com/17010094/64642173-b933f780-d3db-11e9-9b52-9929a0ebbbb9.png)


Verification passed on iPhone 7+ with iOS 12.4.1 running 1.12(19.09.13.06)
Dark Mode:
![image](https://user-images.githubusercontent.com/17010094/64880713-da3c5880-d626-11e9-9696-e9d7a637e25d.png)
Light Mode:
![image](https://user-images.githubusercontent.com/17010094/64880736-e7f1de00-d626-11e9-8b6d-0a55e0a3a649.png)
