### ISSUE TITLE
1Password extension uses deprecated UIWebView

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1524]
See issue https://github.com/agilebits/onepassword-app-extension/issues/409

This makes our app to show deprecation notice too.

To temporarily fix this we can either use open PR which fixes it https://github.com/agilebits/onepassword-app-extension/pull/411

or fork this PR to my own repo if there are any security concerns with pointing to an open PR
For carthage we use pinned framework versions

@jumde is it okay to use that PRs branch until it's merged into upstream? Deadlines are tight so we need some temp solution for this

**Comment by jumde** [comment]
@iccub - I'm always wary of using open PRs but this one should be fine given the deprecation of UIWebView. I'm doing a quick check of the PR to see if anything stands out.  

Using the PR branch directly should be fine. Could you file a follow-up issue to remove the PRs branch and use the release branch directly for 1password?

**Comment by iccub** [comment]
Done https://github.com/brave/brave-ios/issues/1527
