### ISSUE TITLE
Search term text colour is too light on dark mode

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1525]
### Description: 
Search term text colour is too light on dark mode

### Steps to Reproduce 
  1. Set device theme to dark
  2. Visit a page and search for a term
  3. Search term is too light on the search bar

**Actual result:** 
Dark Mode:
![image](https://user-images.githubusercontent.com/17010094/64662309-f7e6a380-d415-11e9-8764-09f3e34fb512.png)
Light Mode:
![image](https://user-images.githubusercontent.com/17010094/64662304-f1f0c280-d415-11e9-811b-b072cfbe8664.png)

**Expected result:**
Text should be visible on all themes 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.12(19.09.10.23)

**Device details:** 
iPhone XR (iOS 13.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
Marking as 1.13 as this is not a blocker for 1.12. @anthonypkeane please change milestone if required

**Comment by iccub** [comment]
Does this not happen on iOS 12 devices @srirambv?

**Comment by srirambv** [comment]
Happens on iOS12 as well. Removing iOS13 label.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.31.19)
* Verified search term is visible on  dark theme
![image](https://user-images.githubusercontent.com/17010094/68024884-bd64ee80-fc81-11e9-8f3c-ed6b211d2a5b.png)
* Verified search term is visible on light theme
![image](https://user-images.githubusercontent.com/17010094/68024919-d8376300-fc81-11e9-881d-be9e075e5b58.png)
-------------
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.31.19)
* Verified search term is visible on  dark theme
![image](https://user-images.githubusercontent.com/17010094/68024944-eab19c80-fc81-11e9-9918-2cc43ac47fd9.png)

* Verified search term is visible on light theme
![image](https://user-images.githubusercontent.com/17010094/68024951-eeddba00-fc81-11e9-83db-dd158dae275a.png)

-------------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.31.19)
* Verified search term is visible on  dark theme
![image](https://user-images.githubusercontent.com/17010094/68024962-f8672200-fc81-11e9-94d6-72fd6479578b.png)

* Verified search term is visible on light theme
![image](https://user-images.githubusercontent.com/17010094/68024959-f43b0480-fc81-11e9-9960-ec2319904299.png)

-------------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.31.19)
* Verified search term is visible on  dark theme
![image](https://user-images.githubusercontent.com/17010094/68025080-509e2400-fc82-11e9-9e55-f979da1e1b9a.png)
* Verified search term is visible on light theme
![image](https://user-images.githubusercontent.com/17010094/68025126-6d3a5c00-fc82-11e9-9ed1-dd3907a65f2d.png)

-------------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.31.19)
* Verified search term is visible on  dark theme
![image](https://user-images.githubusercontent.com/17010094/68024976-01f08a00-fc82-11e9-9567-0e2afe93024b.png)

* Verified search term is visible on light theme
![image](https://user-images.githubusercontent.com/17010094/68024979-061ca780-fc82-11e9-98f9-3646b82eb5fb.png)
