### ISSUE TITLE
Remove the www from the URL bar

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1533]
## Problem Description 
I suggest, like Safari, we remove the _www_ from the URL bar to present the URL in a nicer way. 

**Safari**

![IMG_83B922C589FD-1](https://user-images.githubusercontent.com/7606853/64730366-0a9fbd80-d494-11e9-93ed-47e773e04708.jpeg)

**Brave**

![IMG_5801D0AC4384-1](https://user-images.githubusercontent.com/7606853/64730382-11c6cb80-d494-11e9-86e3-45af7b61dc3b.jpeg)

This will also save space up top

@jumde & @tomlowenthal for views

**Comment by jumde** [comment]
We already do this on the desktop browser, sgtm

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 13.1 running 1.13(19.10.18.15)
* Verified visiting an HTTPS site(`irishtimes.com`), www is hidden in URL bar. Clicking on URL bar shows full  `https://www.irishtimes.com`
* Verified visiting a HTTP site(`nyu.edu`), www is hidden in URL bar, clicking on URL bar shows full `http://www.nyu.edu`

Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.18.15)
* Verified visiting an HTTPS site(`irishtimes.com`), www is hidden in URL bar. Clicking on URL bar shows full  `https://www.irishtimes.com`
* Verified visiting a HTTP site(`nyu.edu`), www is hidden in URL bar, clicking on URL bar shows full `http://www.nyu.edu`

Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.18.15)
* Verified visiting an HTTPS site(`irishtimes.com`), www is hidden in URL bar. Clicking on URL bar shows full  `https://www.irishtimes.com`
* Verified visiting a HTTP site(`nyu.edu`), www is hidden in URL bar, clicking on URL bar shows full `http://www.nyu.edu`

Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.18.15)
* Verified visiting an HTTPS site(`irishtimes.com`), www is hidden in URL bar. Clicking on URL bar shows full  `https://www.irishtimes.com`
* Verified visiting a HTTP site(`nyu.edu`), www is hidden in URL bar, clicking on URL bar shows full `http://www.nyu.edu`

Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.18.15)
* Verified visiting an HTTPS site(`irishtimes.com`), www is hidden in URL bar. Clicking on URL bar shows full  `https://www.irishtimes.com`
* Verified visiting a HTTP site(`nyu.edu`), www is hidden in URL bar, clicking on URL bar shows full `http://www.nyu.edu`
