### ISSUE TITLE
dragging links/images/content to split screen opens Safari

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#1534]
### Description: 

When dragging content from Brave into a new window to initiate the split screen on `iOS 13`, the content that's being dragged will open in `Safari` rather than `Brave`.

This might be an iOS limitation due to `Safari` being the default browser but we should see if we can make it so `Brave` opens a new window rather than `Safari` being opened. This will get really annoying as users are forced to use two different browsers.

### Steps to Reproduce 
  1. launch `1.12 (19.09.11.15)`
  2. open `coinmarketcap.com`
  3. tap/hold and drag any link and move it to the side to initiate a split screen

You'll notice that the new content is being opened in `Safari`

**Actual result:** 

* **`Example`** --> https://youtu.be/uY2noZOOqFA

**Expected result:**

We should be opening another `Brave` window rather than opening content in `Safari`

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR

**Brave Version:** 

* `1.12 (19.09.11.15)` - Reproduced

**Device details:** 

* `iPad Air 3rd Generation` running `iOS 13.1`

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? Same issue happens under `Chrome` & `Firefox`

### Additional Information

CCing @srirambv @jhreis @anthonypkeane

**Comment by kylehickinson** [comment]
This is probably blocked until we support multiple windows

**Comment by iccub** [comment]
No other 3rd party browser found a way around it at the moment, I tested all major browsers

**Comment by mtoohey31** [comment]
Just one note to add to this, if this does become possible in the future, it would also be nice to be able to drag the tab directly into split screen, the same way Safari allows you to.

**Comment by iccub** [comment]
Apple still not allowing this :( lets close as wontfix and revisit once they change their mind
