### ISSUE TITLE
re-add missing actions to "Share" menu

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1540]
### Description: 

We're missing both the `Find in Page` and `Request Desktop Site` actions from the `Share with..` menu.

### Steps to Reproduce 
  1. open `1.11.4 (19.08.29.21)`
  2. visit any random website (easiest is just to tap one from `Favourites`)
  3. tap on the kabob menu -> `Share with..`

You'll notice that we're missing both `Find in Page` and `Request Desktop Site` actions

**Actual result:** 

![IMG_0067](https://user-images.githubusercontent.com/2602313/64807627-96cce600-d563-11e9-89b6-9f9bbc12e0b6.PNG)

**Expected result:**

![IMG_0066](https://user-images.githubusercontent.com/2602313/64807643-a0eee480-d563-11e9-94e8-11601dda6f0f.PNG)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible when using the above STR.

**Brave Version:** 

* `1.12 (19.09.12.15)` - Reproduced

**Device details:** 

* `iPad Air (3rd Generation)` using `iOS 13.1`

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)?  N/A

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air 3rd Generation` using `iOS 13.1` running `1.12 (19.09.12.28)`:

![IMG_0078](https://user-images.githubusercontent.com/2602313/64828232-87ff2700-d595-11e9-8d64-194d45b1b580.PNG)

* ensured that `Find in Page`, `Add to Favourites` and `Request Mobile/Desktop Site` works as expected

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 running 1.12(19.09.13.06)
![image](https://user-images.githubusercontent.com/17010094/64868941-51b1be00-d60e-11e9-95d9-a27ecc8fd3a5.png)
Verification passed on iPhone 7+ with 12.4.1 running 1.12(19.09.13.06)
![image](https://user-images.githubusercontent.com/17010094/64868983-65f5bb00-d60e-11e9-891f-0596557e483e.png)
