### ISSUE TITLE
Private tab text remains black until opening settings page on upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1542]
### Description: 
Private tab text remains black until opening settings page on upgrade

### Steps to Reproduce 
  1. Install app store build
  2. Upgrade to 1.12
  3. Open a private tab
  4. Stats text and URL bar placeholder text is all in dark 
  5. Open settings and close, all text changes to white on dark mode

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/64813889-66d80f80-d570-11e9-994b-466a3ed6960e.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/17010094/64813899-6c355a00-d570-11e9-9262-0c39534f8ce0.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.12(19.09.16.10)

**Device details:** 
iPhone 7+ iOS 12

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by anthonypkeane** [comment]
Can't reproduce. Moving to 1.13 to further investigate.

**Comment by kylehickinson** [comment]
@srirambv Can't reproduce. Tried:

1. Click & hold + (add tab button) → New Private Tab
2. Tab switcher > private mode > new tab
3. The same steps when launching in dark mode

It's possible this was fixed already. Maybe worth another verification?

**Comment by iccub** [comment]
Should be fixed thanks to the NTP refactor in 1.18
