### ISSUE TITLE
change the border theme/colour for search suggestions

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#1543]
### Description: 

We're currently using `black` as the border for search suggestions underneath the URL. When using the `Light` theme, this looks a bit off compared to what we had in previous versions. When using the `Dark` theme, we're still using `black` which is hard to see.

### Steps to Reproduce 
  1. launch `1.12 (19.09.12.18)` and start typing something into the URL bar
  2. select `Yes` under `Turn on search suggestions?`

**Actual result:** 

<img width="784" alt="Screen Shot 2019-09-12 at 12 27 06 PM" src="https://user-images.githubusercontent.com/2602313/64826260-196a9b00-d58e-11e9-9c1a-efb7669fc384.png">
<img width="787" alt="Screen Shot 2019-09-12 at 12 33 50 PM" src="https://user-images.githubusercontent.com/2602313/64826261-196a9b00-d58e-11e9-98b3-9f027ed3dca0.png">

**Expected result:**

Either pick a new colour/theme or use what we had before as per the following:

<img width="781" alt="Screen Shot 2019-09-12 at 6 51 44 PM" src="https://user-images.githubusercontent.com/2602313/64826351-62225400-d58e-11e9-8248-3ba7a03b0462.png">

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.12 (19.09.12.18)`

**Device details:** 

* `iPad Air 3rd Generation` using `iOS 13.1` - **Reproduced**
* `iPad Mini 4` using `iOS 12.4.1` - **Reproduced**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @srirambv @jamesmudgett @jhreis @anthonypkeane

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 running 1.12(19.09.13.06)
Light and Dark 
![image](https://user-images.githubusercontent.com/17010094/64874032-4499cc80-d618-11e9-8de9-920a035cdf5e.png)


Verification passed on iPhone 7+ with iOS 12.4.1 running 1.12(19.09.13.06)
Light and Dark 
![image](https://user-images.githubusercontent.com/17010094/64873817-e66ce980-d617-11e9-9185-dbf45a19f000.png)

Verification **PASSED** on `iPad Air (3rd Generation)` using `iOS 13.1` running `1.12 (19.09.13.06)`:

<img width="788" alt="Screen Shot 2019-09-13 at 3 01 22 PM" src="https://user-images.githubusercontent.com/2602313/64887849-81c18700-d637-11e9-9911-41bdb31d0fe2.png">
<img width="783" alt="Screen Shot 2019-09-13 at 3 01 16 PM" src="https://user-images.githubusercontent.com/2602313/64887851-81c18700-d637-11e9-944e-bc798bebe365.png">
