### ISSUE TITLE
sometimes it takes two taps to pick a category when using desktop version (iOS 13)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#1545]
### Description: 

When using the desktop version of https://twitch.tv on an `iPad`, sometimes it takes two taps to pick a game category from https://www.twitch.tv/directory. The first tap will sometimes pick the name of the game and number of followers right underneath the image, the second tap will actually take you to the correct page.

Note: `Chrome` & `Firefox` have the same issue so it's a WebCompat issue with https://www.twitch.tv and not `Brave`. Creating the issue in case there's community feedback as `iPad` is using `Desktop` as default.

### Steps to Reproduce 
  1. launch `1.12 (19.09.12.28)`
  2. open https://www.twitch.tv/directory (ensure it's the desktop version of the site)
  3. tap on a category and you'll notice that some times the name of the game and amount of viewers is selected rather than loading the page.
  4. tap on the same image a second time and the page will load correctly

**Actual result:** 

Example of the issue occurring --> https://youtu.be/gnSFc8pLuIA

**Expected result:**

Tapping on a category via https://www.twitch.tv/directory should open the targeted page rather than selecting the name of the game and the total amount of viewers it currently has.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible when using the STR mentioned above.

**Brave Version:** 

**Device details:** 

* `iPad Air 3rd Generation` running `iOS 13.1` - **Reproduced**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? Yes, reproducible on all the browsers: `Chrome`, `Firefox` and `Safari` running `iOS 13`

### Additional Information

CCing @srirambv @jhreis @anthonypkeane

**Comment by iccub** [comment]
Closing as stale, the website must have changed since then
