### ISSUE TITLE
Add appId exception to enable WebAuthn for GSuite

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1546]
Similar to the code here: https://github.com/WebKit/webkit/blob/master/Source/WebCore/Modules/webauthn/AuthenticatorCoordinator.cpp#L83

**Comment by happyfuncode** [comment]
See also:
Chrome: https://chromium.googlesource.com/chromium/src/+/66.0.3359.158/content/browser/webauth/authenticator_impl.cc#129
Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1436078

**Comment by jumde** [comment]
`appId` functionality does not exist in Brave yet. Work in progress.
