### ISSUE TITLE
No context menu shown for long press on image search results

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1547]
### Description: 
While testing #1266 on iOS 12.4.1, found that long press on image doesn't bring up context menu for saving images. Instead it just highlights the image. 

### Steps to Reproduce 
  1. Visit Google.com and search for an image
  2. Long press on the image 
  3. No popup context menu shown just highlights the image 

**Actual result:** 
[Image search context menu.zip](https://github.com/brave/brave-ios/files/3611417/Image.search.context.menu.zip)

![image (7)](https://user-images.githubusercontent.com/2781690/64890449-65a7f080-d60b-11e9-9bce-c90e66182894.png)

**Expected result:**
Should show context menu on image search result

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.12(19.09.13.06). Also reproduced on Appstore build so not a regression 

**Device details:** 
iPhone 7+ (iOS 12.4.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Also `data:image/jpeg` is not appended to any image file that is being downloaded 
![image](https://user-images.githubusercontent.com/17010094/64887032-956bee00-d635-11e9-8cd7-a11c792eb572.png)

**Comment by iccub** [comment]
This should be working, google intercepts the long press gesture to present its own share menu.
Btw the context menu for iOS 13 has changed slightly

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.31.19)
* Verified context menu is shown on long press when the image is opened from the search result 
------
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.10.31.19)
* Verified context menu is shown on long press when the image is opened from the search result
