### ISSUE TITLE
Website/tab names are hard to view with dark mode enabled

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-ios#1551]
### Description: 
When viewing open tabs in iOS with dark mode enabled, the website titles appear very light and become hard to read:
![image (2)](https://user-images.githubusercontent.com/3299098/65078246-7af58580-d951-11e9-9915-dfff70ef2a76.png)

### Steps to Reproduce 
  1. Enable dark mode in Brave iOS (`Settings --> Display/brightness`)
  2. Open a few tabs
  3. Open tab view and observe site titles

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily/always

**Brave Version:** 
Version: 1.12 (19.09.13.06)

**Device details:** 
iPhone 6s (iOS 12.4.1)

### Additional Information
User report:
https://community.brave.com/t/brave-with-dark-mode-enabled-in-opened-tabs-page-makes-websites-titles-hard-to-see/83335

**Comment by iccub** [comment]
Happens only in iOS 12 btw

**Comment by srirambv** [comment]
* Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.16.18)
![image](https://user-images.githubusercontent.com/17010094/67031958-9edaf100-f0e0-11e9-94b1-296abfb22b27.png)

* Verification passed on iPhone Xr with iOS 13.2 running 1.13(19.10.16.18)
![image](https://user-images.githubusercontent.com/17010094/67031967-a4383b80-f0e0-11e9-900f-20c3e6eee688.png)

* Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.16.18)
![image](https://user-images.githubusercontent.com/17010094/67031972-a8645900-f0e0-11e9-8f97-4c1b02ab8427.png)
