### ISSUE TITLE
Downloads background is light in Dark Mode

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1553]
### Steps to Reproduce 
  1. Turn dark mode on if not already on
  2. Click the menu → Downloads 

**Actual result:** 

![Image from iOS (1)](https://user-images.githubusercontent.com/529104/65080220-c79b8980-d96e-11e9-87ee-fdc204fc5cb7.jpg)

**Expected result:** Should have a dark background, white icon
**Reproduces how often:** Easily
**Brave Version:** 1.12 Live
**Device details:** iPhone X 13.0 GM

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.16.18)
![image](https://user-images.githubusercontent.com/17010094/67029111-a26b7980-f0da-11e9-9313-96753821d930.png)

Verification passed on iPhone Xr with iOS 13.2 running 1.13(19.10.16.18)
![image](https://user-images.githubusercontent.com/17010094/67029163-b8793a00-f0da-11e9-8ff4-3d163e9f784f.png)

Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.16.18)

Logged https://github.com/brave/brave-ios/issues/1722 for theme not updating automatically
