### ISSUE TITLE
Data loss on 1.12 upgrade for some users.

### ISSUE THREAD

**Issue by danishjafri88** [brave/brave-ios#1554]
### Description: 
Users have reported loosing their bookmarks and history when migrating to 1.12.
Likely cause is the failure to migrate DB from documents directory to application support directory.

### Steps to Reproduce 
It has not been reproducible by the dev team, so FWIW
  1. Create bookmarks in older version of app
  2. update to 1.12

**Actual result:** 
No bookmarks

**Expected result:**
Bookmarks should be there

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 
1.12

**Device details:** 
older devices such as iPhone 6s and iPad mini 2
iOS 12

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13 and verified the following scenarios on production build on TF. 

 **Scenario 1: (Pass)**
1. Install 1.12.1 Brave
2. Save a bookmark
3. Open Files app > Brave
4. No files stored in Files app

 **Scenario 2: (Pass)**
1. Install latest 1.12
2. Added bookmarks/favourites/changed settings/open tabs 
3. Install 1.12.1
4. Verified nothing is lost after upgrade

**Scenario 3: (Not reproduced)**
1. 1.12 Users, Bad State

**Scenario 4: (Pass)**
1. Install 1.11.4
2. Add bookmarks/favourites/tabs/change settings
3. Upgrade to 1.12.1
4. Added bookmarks/favourites/tabs/ and changed settings are all retained

**Scenario 5: (Pass)**
1. Install 1.11.4
2. Add bookmarks/favourites/tabs/change settings
3. Upgrade to 1.12.1
4. Added bookmarks/favourites/tabs/ and changed settings are all retained
5. Go into Files app > Brave
6. No files are stored in Files app

**Scenario 6: (Not reproducible) Failed migration**
1. Install 1.11.4
2. Add bookmarks/favourites/tabs/change settings
3. Upgrade to 1.12.1
4. Added bookmarks/favourites/tabs/ and changed settings are all retained
5. Go into Files app > Brave
6. There should be ~3 "Brave" files in Files app (not reproducible as it didn't fail migration)

**Comment by kjozwiak** [comment]
Results for `the following devices:

* iPhone 6s+` using `iOS 12.4.1` - **PASSED**
* `iPad Air (3rd Gen)` using `iOS 13.1` - **PASSED**

#### `New Users` (x2) <-- Using `Production` TF

* installed `1.12.1 (19.9.20.20.23)` & saved a bookmark
* opened `Files.app` and ensured that there weren't any files being stored under `Brave`
* restarted `Brave` a few times and ensured that there weren't any files being created under `Brave`

#### `1.12 Users, Good State -> standard upgrade testing` - (x3) <-- Using `Production` TF

* installed `1.12 (19.9.12.18)` and saved several bookmarks and opened ~10 different tabs
* updated to `1.12.1 (19.9.20.20.23)` and ensured that all the bookmarks and tabs were still present after updating
* opened `Files.app` and ensured that there weren't any files being stored under `Brave`

#### `1.11.4 Users, successful migration` (x3) <-- Using `Production` TF

* installed `1.11.4 (19.8.29.21)` and saved several bookmarks and opened ~10 different tabs
* updated to `1.12.1 (19.9.20.20.23)` and ensured that all the bookmarks and tabs were still present after updating
* opened `Files.app` and ensured that there weren't any files being stored under `Brave`

#### `1.11.4 Users, failed migration` (x3) <-- Using `Production` TF

* installed `1.11.4 (19.8.29.21)` and saved several bookmarks and opened ~10 different tabs
* updated to `1.12.1 (19.09.24.17)` (corrupted DB build) using an `IPA` file and ensured that all the bookmarks and tabs were still present after updating
* opened `Files.app` and ensured that there weren't any files being stored under `Brave`

#### `1.11.4 Users, failed migration` (x3) <-- Using `BETA` TF

* installed `1.11.4 (19.8.30.19)` and saved several bookmarks and opened ~10 different tabs
* updated to `1.12.1 (19.9.20.23.9)` (corrupted DB build)

As mentioned in Slack earlier, the following occurs:

* onboarding appears twice, once for `1.11.4 (19.8.30.19)` and once for `1.12.1 (19.9.20.23.9)` after upgrading
* all NTP stats are being cleared
* Setting are being cleared
* Duplicate `Favorites` under NTP
* `profile.profile` folder is being left behind which includes `login` & `TabManagerScreenshot` files

**Comment by kjozwiak** [comment]
@jhreis mind taking a look at the above to make sure we covered everything?
