### ISSUE TITLE
Improve Pin code UI

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1557]
### Description: 
The UI for this screen is bad, 

@jamesmudgett can you create something better? 

![IMG_2A4A28BF79BC-1.jpeg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/94a63604-8d11-45a0-8a76-38f854b65226)

**Comment by anthonypkeane** [comment]
I think this got resolved in 1.14
Can you confirm @iccub ?
If yes, please close this issue

**Comment by iccub** [comment]
Closing as duplicate of https://github.com/brave/brave-ios/issues/1818
