### ISSUE TITLE
Tab manager screenshots for Private Browsing are not destroyed if the application crashes

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#156]
### Steps to Reproduce 
  1. Enter private browsing mode
  2. Add several tabs
  3. Crash the application (you can add `CrashSimulator.forceCrash()` to the code base)
  4. Relaunch the application
  5. Open iExplorer tool (available from https://macroplant.com/iexplorer)
  6. Navigate to `Documents/profile.profile/TabManagerScreenshots`
  7. Drag files to your desktop
  8. Add `.jpg` extension to files

**Actual result:** Private browsing screenshots are persisted on the file system in the Documents folder

**Expected result:** Private browsing screenshots should not be persisted on the file system in the Documents folder, move to Library/Caches folder as this folder cannot be viewed with tools such as iExplorer

**Reproduces how often:** Everytime

**Brave Version:** 2.0 (18.08.06.15)

**Device details:** Any

### Additional Information 

There is a workaround, whereby if you have orphaned tab manager screenshots you can relaunch Brave, navigate to Private Browsing and add a new tab. This will then delete orphaned tab manager screenshots from the file system

**Comment by tmancey** [comment]
Agreed with @tomlowenthal that this can be deferred to a future version as iTunes File Sharing will be disabled in 1.7 (https://github.com/brave/brave-ios/issues/204)

**Comment by ShivanKaul** [comment]
IIUC a screenshot is taken in private browsing but the expectation is that it will go away once private browsing mode is quit? I might be misunderstanding, but that's not expected behaviour given that screenshotting is OS functionality. This issue is pretty old though so I'll close, but let me know if this is still a concern!
