### ISSUE TITLE
iOS 13 Dark mode auto switch

### ISSUE THREAD

**Issue by devanz** [brave/brave-ios#1572]
### Description: 

It appears if you switch between light and dark mode within Brave, tabs will be refreshed accordingly. However, if you have display set to “Auto” in Brave and switch between light & dark mode under iOS setting , tabs will not be refreshed and you need to manually relaunch the app.

This is quiet annoying if you have dark set to auto under iOS setting, which is my case. :slight_smile:

### Steps to Reproduce 
  1. Configure Display & Brightness to auto on Brave.
2.Switch dark mode under system setting in iOS

**Actual result:** 

**Expected result:**

Tabs are either locked to light or dark mode in brave, you have to manually to close and relaunch the app.

Brave Version( check About Brave):
1.12 (19.09.13.06)

Mobile Device details
iOS 13 iPhone XsMax

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Easily reproduced

### Additional Information
https://wetransfer.com/downloads/f26e644c6d433a61b84cbb5c1c0d0ecb20190923122432/d295c9

**Comment by hennrynusasatria** [comment]
Hi All,

This bug has been reported since last year, but it is still not fixed until today (Brave iOS Version 1.19), when do you plan to fix this bug?

Thank you.

**Comment by hennrynusasatria** [comment]
Hi @devanz @kylehickinson 

Perhaps, it is the same issue as #2558 , please check.

Thank you.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(21.5.25.18)
- Verified steps from issue description
- Verified theme updates correctly for tab strip when theme is changed via control centre
---------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.26(21.5.25.18)
- Verified steps from issue description
- Verified theme updates correctly for tab strip when theme is changed via control centre
--------
Verification passed on iPad Pro with iOS 14.5.1 running 1.26(21.5.25.18)
- Verified steps from issue description
- Verified theme updates correctly for tab strip when theme is changed via control centre
