### ISSUE TITLE
Update Ads & trackers text to match Desktop/Android

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1575]
### Description: 
Update Ads & trackers text to match Desktop/Android

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/65532343-a9cba880-dec9-11e9-9a62-d998a28f89fa.png)

**Expected result:**
Should match desktop and Android. Should be `Ads and Trackers Blocked`

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
All

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
@srirambv Is this simply a copy change? `Ads & Trackers Blocked` → `Ads and Trackers Blocked`?

**Comment by srirambv** [comment]
Actually Android is now having `Ads & Trackers Blocked` but only desktop is having `Ads and Trackers Blocked`. @brave/design  to confirm if desktop should change to `&` from `and` or both mobile should change from `& ` to `and`. Either way it should be consistent across platforms

**Comment by karenkliu** [comment]
I think it's also `Ads & Trackers Blocked` on iOS. We should change desktop so that it matches.

**Comment by srirambv** [comment]
Thanks for the confirmation @karenkliu. I'll add an issue for desktop to have `&` instead of `and`

**Comment by srirambv** [comment]
Closing in favour of https://github.com/brave/brave-browser/issues/6982
