### ISSUE TITLE
Sync devices showing wrong names when tapped

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1587]
### Steps to Reproduce 
  1. Pair 3 devices
  2. Tap on them in sync settings

**Actual result:** 
Sometimes wrong device name is selected

**Expected result:**
Correct device should be selected

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Happens sometimes, if can't repro, wait 1 minute and try again

**Brave Version:** 
1.12

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.11.1.19)
* Verified tapping on the device name shows the correct device name
-----------
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.11.1.19)
* Verified tapping on the device name shows the correct device name
-----------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.11.1.19)
* Verified tapping on the device name shows the correct device name
-----------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.11.1.19)
* Verified tapping on the device name shows the correct device name
-----------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.11.1.19)
* Verified tapping on the device name shows the correct device name
