### ISSUE TITLE
Add Licenses setting option.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1590]
We should allow to present open source licenses we use to users.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.31.19)
![license_iphoneXR](https://user-images.githubusercontent.com/17010094/67996974-5109d100-fc28-11e9-84e2-fd4b3b2838c6.gif)
----------
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.10.31.19)
![license_iPhone6](https://user-images.githubusercontent.com/17010094/67996984-5d8e2980-fc28-11e9-84be-0c7a25ecc927.gif)
----------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.31.19)
![license_iPhone6](https://user-images.githubusercontent.com/17010094/67996990-61ba4700-fc28-11e9-876c-95e8bcd42776.gif)
--------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.31.19)
![license_ipad12](https://user-images.githubusercontent.com/17010094/67997164-47cd3400-fc29-11e9-9cf5-53a44870f7ac.gif)
--------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.31.19)
![license_ipad13](https://user-images.githubusercontent.com/17010094/67997166-4bf95180-fc29-11e9-895b-841609945887.gif)
