### ISSUE TITLE
Update StartPage Icon

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ios#1598]
### Description: 
StartPage, shown in the Search Engine list, has an outdated icon.

**Expected result:**
Icon to use instead:

![StartPage](https://www.startpage.com/assets/images/logo-180x180.png?v=48842639)

**Brave Version:** 
1.12

**Comment by srirambv** [comment]
Verification passed on iPhone Xr with iOS 13.2 running 1.13(19.10.16.18)
* Verified icon is updated in search engine page
![image](https://user-images.githubusercontent.com/17010094/67026433-bf517e00-f0d5-11e9-8371-280f972b12af.png)
* Verified updated icon is used for quick search icon
![image](https://user-images.githubusercontent.com/17010094/67026447-c4aec880-f0d5-11e9-9680-77673be7d726.png)
* Verified updated icon is used on onboarding screen
![image](https://user-images.githubusercontent.com/17010094/67026840-92ea3180-f0d6-11e9-93f0-0b75b9445fa8.png)


Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.16.18)
* Verified icon is updated in search engine page
![image](https://user-images.githubusercontent.com/17010094/67026695-53234a00-f0d6-11e9-805d-17aa3aca206c.png)
* Verified updated icon is used for quick search icon
![image](https://user-images.githubusercontent.com/17010094/67026719-59192b00-f0d6-11e9-90e0-5c2bfbb94cac.png)
* Verified updated icon is used on onboarding screen
![image](https://user-images.githubusercontent.com/17010094/67026681-4dc5ff80-f0d6-11e9-963a-7c1dcddadcbe.png)


Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.16.18)
* Verified icon is updated in search engine page
![image](https://user-images.githubusercontent.com/17010094/67026954-c5942a00-f0d6-11e9-97d6-aa367a430977.png)
* Verified updated icon is used for quick search icon
![image](https://user-images.githubusercontent.com/17010094/67026972-cd53ce80-f0d6-11e9-889d-a8cf4717987d.png)
* Verified updated icon is used on onboarding screen
![image](https://user-images.githubusercontent.com/17010094/67027032-e0ff3500-f0d6-11e9-8b5e-7044c47b4e88.png)
