### ISSUE TITLE
New Private Tab string 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1602]
## Problem Description 
When in private mode, long pressing the plus icon should say New Private Tab

![IMG_E270DC5FD47A-1.jpeg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/37426f40-d39d-4343-be20-c1eefc6fa483)

**Comment by dangdennis** [comment]
I’d like to tackle this as my first swift + iOS PR.

**Comment by iccub** [comment]
go for it @dangdennis :)

**Comment by dangdennis** [comment]
Since this is a text change, would I have to update internationalizations as well? Or is there a script to do this?

**Comment by iccub** [comment]
@dangdennis there should be a string for it already, for opening tabs in normal mode

In normal mode you have two actions `open in new tab`, `open in private tab`
So what needs to be done is to in private tab change string from `private` to the regular `open in new tab`

**Comment by iccub** [comment]
@dangdennis there's `NewPrivateTabTitle` string available, you can use it

**Comment by dangdennis** [comment]
@iccub Thanks for the pointers. That was fun - the installation and build process were so streamlined. Though it took running the shell script twice for my build to eventually succeed.

**Comment by srirambv** [comment]
* Verification passed on iPhone Xr with iOS 13.2 running 1.13(19.10.16.18)
![image](https://user-images.githubusercontent.com/17010094/67015354-6a593c00-f0c4-11e9-8286-35cdc6420072.png)

* Verification passed on iPhone 7+ with iOS 13.1 running 1.13(19.10.16.18)
![image](https://user-images.githubusercontent.com/17010094/67015480-97a5ea00-f0c4-11e9-870a-7d4783f7d48f.png)

* Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.16.18)
![image](https://user-images.githubusercontent.com/17010094/67028601-a21eae80-f0d9-11e9-8964-a97621e24878.png)
