### ISSUE TITLE
Add Password Manager Integrations

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#162]
Port over the existing 1.6 password managers (like 1Password) and hook up with existing settings UI:

![Simulator Screen Shot - iPhone 8 - 2018-08-16 at 11.05.08.png](https://images.zenhubusercontent.com/5b4cfb87b69de9433c0523d6/a98a9618-9f80-49bc-b176-fe8d4eebd906)

**Comment by kylehickinson** [comment]
Also note the TODO in `SettingsViewController.swift`:

```swift
// TODO: Check if Password Managers exist before showing this row
var pmRow = Row(
    text: Strings.Password_manager_button,
    detailText: PasswordManagerShortcutBehavior(rawValue: Preferences.General.passwordManagerShortcutBehavior.value)?.displayString,
    accessory: .disclosureIndicator
)
```

**Comment by tmancey** [comment]
Waiting on final iOS version support information. If we go iOS 12+ we can leverage Apple's newer 3rd party password manager APIs.

**Comment by anthonypkeane** [comment]
Linked to brave/brave-ios#164, we are going with only iOS12 in V1.7

**Comment by kylehickinson** [comment]
Based on brave/brave-ios#164 and us going iOS 12 in 1.7 we can remove the setting for _Password Manager Button_.

**Comment by jhreis** [comment]
Yes, this sounds good, so AFA this ticket goes, completing this will just be removing the UI pieces for this.

**Comment by kylehickinson** [comment]
Correct, I think I'll close this ticket and make a new one for that task

**Comment by jhreis** [comment]
Ref: https://github.com/brave/brave-browser/issues/36028
