### ISSUE TITLE
Add "Share To Brave" extension

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#163]
Port existing extension + URL schemes from 1.6.

Currently the only URL scheme registered is `firefox://` and their internal URL schemes based on environment (`fennec`, `firefox-internal`, etc.)

From `browser-ios`: `BraveShareTo` extension & `ShareToBraveViewController.swift`

**Comment by iccub** [comment]
We had few issues with it on v1.
After PR is ready verify that share to brave works:
- for twitter links
- for links in notes.app
