### ISSUE TITLE
Discard page URL when search result is slow on network connection 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1637]
### Description: 
When you are already on a slow data connection, typing a search term on an already loaded page doesn't properly convey if its loading the previous page or loading the search result
Reported by @bradleyrichter and @Miyayes  

### Steps to Reproduce 
  1. Get on a super slow network
  2. Visit any page and wait till its completely loaded
  3. On the same tab do a search
  4. Once the keyboard is hidden, it isn't clear if the previous page is loading or search result is being loaded

**Actual result:** 
https://bravesoftware.slack.com/archives/C06UXF3KJ/p1570896581057200

**Expected result:**
Proper indication of what page is being loaded, search result or previously visited page

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy when you are having a bad day

**Brave Version:** 
1.12.1

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
potentially solved by https://github.com/brave/brave-ios/issues/6730
