### ISSUE TITLE
Geetest captcha is failing to load on aerlingus.com

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-ios#1638]
### Description: 
Geetest captcha is failing on https://www.aerlingus.com/ due to fingerprint blocks. Seems quite a popular captcha especially in China.

### Steps to Reproduce 
  1.  Using (booking) https://www.aerlingus.com/ will invoke a captcha "geetest.com"
  2. If fingerprinting is enabled, it'll prevent the captcha from loading.
  3. Visit `https://www.aerlingus.com/distil_r_captcha.html?requestId=7bbb06c8-a714-43c7-8336-f50f567aa53c&httpReferrer=%2Fhtml%2Ftemplates%2Ftrip-mgmt%2Fflight-status-panel.html`
  4. Expect geetest to load.

**Actual result:** 
Captcha is blocked

**Expected result:**
Captcha should load

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 
1.11.4 (19.08.29.21)

**Device details:** 
On an Iphone 8 plus on 13.1.2.

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 
Confirm it works in Safari.

**Comment by iccub** [comment]
let's close as stale
