### ISSUE TITLE
Video preroll ads bypassing shields on Wired.com

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-ios#1639]
### Description: 

Video preroll ads are bypassing our shields on wired.com

### Steps to Reproduce 
  1. Navigate to https://www.wired.com/video/watch/hacker-breaks-down-hacking-scenes-from-movies-tv
  2. Play video
  3. Observe preroll video ads

**Actual result:** 
![7CA75CB7-DAFA-480A-AA19-1A88345E258F](https://user-images.githubusercontent.com/8979240/66721993-7e97f300-edbd-11e9-921f-45ff30bc9bc6.png)
![9DD5936B-0C94-4851-9F71-1F0F223C16E9](https://user-images.githubusercontent.com/8979240/66721994-7e97f300-edbd-11e9-8963-17d2fde83c20.png)

Note that in both screenshots, the shields panel displays an active block count (25-30 count observed). 

Does not appear to be an instance where my client has a corrupted DAT file for the block list(s). 

In past instances where DAT files were corrupted, ads would bypass shields, and the block count would display a zero count.

**Expected result:**
Ads are loaded via 3rd party video ads sdk (invoked via video player configuration). 

We should be blocking. 

Additionally, for instances where ads were observed containing the AdChoices badge, clicking on the AdChoices icon navigates the user to a new tab with an adchoices page that reports the 3rd party services and vendors associated with the ad. 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100% of attempts (4 attempts)

**Brave Version:** 
Reproduced in Prod and Brave Beta

Prod: Version 1.12.1 (19.09.20.23)
Beta: Version 1.13 (19.10.09.22)

**Device details:**  
iPad Pro (12.9-inch) (2nd generation)
iOS: 12.4.1

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information

**Comment by lukemulks** [comment]
@ryanbr, I haven’t had a chance to attempt to repro from desktop or android. May be cross-platform, but reporting in iOS first as that’s where this was initially observed and consistently repro’d.

**Comment by lukemulks** [comment]
@jhreis @anthonypkeane apologies for the lack of labels; at some point my permissions level changed for this repro. I can open and edit issues, but am unable to assign people, labels or any other right-column items to the issue. 

Disregard if that’s intentional, just letting you know the lack of labels isn’t from laziness. ;-)

**Comment by ryanbr** [comment]
The preroll (from a desktop testing) is served via doubleclick.net (specifically an xmlhttprequest request)

`https://pubads.g.doubleclick.net/gampad/ads?sz=...`

Is this blocked, or being bypassed? or possibly another mobile-only preroll?

**Comment by iccub** [comment]
I can't repro it anymore, can you @lukemulks @ryanbr?
