### ISSUE TITLE
Passwords saved from 1.6 don't auto-fill in 1.7

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#164]
Verified that password autofill does not currently auto-fill 1.6 passwords

Tested by setting up `browser-ios` with the bundle identifier to match `brave-ios`: `brave.${name}.local.id` then:
- Installing 1.6, saving a login on `github.com/login`. Refreshing to verify it does auto-fill.
- Closing 1.6, installing 1.7 and moving to `github.com/login` again.

Likely a good starting point for understanding the issue: `getLoginsForProtectionSpace()` in `SQLiteLogins.swift`

**Comment by jhreis** [comment]
Waiting on final iOS version support information. If we go iOS 12+ we can leverage Apple's newer 3rd party password manager APIs.

**Comment by anthonypkeane** [comment]
Confirmed that we are going with only iOS12 for V1.7 @jhreis

**Comment by kylehickinson** [comment]
@jhreis @anthonypkeane Does this mean we are no longer going to support saving logins? And if so, what are we doing with the passwords users have saved from 1.6?

**Comment by jhreis** [comment]
@kylehickinson we will still support saved logins, we will just become an iOS password manager. That way, we can leverage Apple's autofill for our own app.

**Comment by kylehickinson** [comment]
Got it. I assume by that you mean we are no longer going to support auto-fill ourselves and will instead have users do so themselves via the keyboard.

I will close this ticket and re-open an enhancement ticket for the task of adding an `AutoFill Credential Provider` to the project

**Comment by jhreis** [comment]
Ref: https://github.com/brave/brave-browser/issues/36028

**Comment by kylehickinson** [comment]
We will be bringing back this feature until a later date when brave/brave-browser#36028 can be done
