### ISSUE TITLE
Stats and Titles Polish

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1641]
Please update the following 

iOS:
**Stats**
Font: SF Pro Text Medium 32pt
Ads & Trackers: #FB542B
HTPPS Upgrades: #A0A5EB
Time Saved: #1E2029 / #FFFFFF
**Titles**
Font: SF Pro Text Medium 10pt
Color: #8C9094

![Screen Shot 2019-10-14 at 4.08.17 PM.png](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/9b109731-47f7-487e-b8d6-f211f6014d75)

cc @jamesmudgett

**Comment by jamesmudgett** [comment]
iOS:
**Stats**
Font: SF Pro Text Medium 32pt
Ads and Trackers: #FB542B
HTPPS Upgrades: #A0A5EB
Time Saved: #1E2029 / #FFFFFF
**Titles**
Font: SF Pro Text Medium 10pt
Color: #8C9094

**Comment by anthonypkeane** [comment]
Update: use **k** for 1000's as Android and iOS do

See the android image above for reference.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.21.22)
* Verified the text size changes after the upgrade
* Verified the text colour of HTTPS is changed after upgrade 
1.12.1(19.9.20.23)
![image](https://user-images.githubusercontent.com/17010094/67251656-bba75980-f43d-11e9-97b2-949cb9f42dc7.png)
1.13(19.10.21.22)
![image](https://user-images.githubusercontent.com/17010094/67251649-b5b17880-f43d-11e9-98c2-ac1c30087530.png)
-------------------------
Verification passed on iPhone 7+ with iOS 13.1 running 1.13(19.10.21.22)
* Verified the text size changes after the upgrade
* Verified the text colour of HTTPS is changed after upgrade 
1.12.1(19.9.20.23)
![image](https://user-images.githubusercontent.com/17010094/67251562-8bf85180-f43d-11e9-9998-11dfbab88e85.png)
1.13(19.10.21.22)
![image](https://user-images.githubusercontent.com/17010094/67251592-9286c900-f43d-11e9-8cf2-04b2cf1ca156.png)
------------------------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.21.22)
* Verified the text size changes after the upgrade
* Verified the text colour of HTTPS is changed after upgrade 
1.12.1(19.9.20.23)
![image](https://user-images.githubusercontent.com/17010094/67251635-acc0a700-f43d-11e9-99d4-d2bf402ca6bc.png)
1.13(19.10.21.22)
![image](https://user-images.githubusercontent.com/17010094/67251627-a7635c80-f43d-11e9-829a-d504b3312e64.png)
--------------------------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.21.22)
* Verified the text size changes after the upgrade
* Verified the text colour of HTTPS is changed after upgrade 
1.12.1(19.9.20.23)
![image](https://user-images.githubusercontent.com/17010094/67251597-97e41380-f43d-11e9-99a1-d4cc3af7251b.png)
1.13(19.10.21.22)
![image](https://user-images.githubusercontent.com/17010094/67251686-d4b00a80-f43d-11e9-9db5-bffc70249fc1.png)
----------------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.21.22)
* Verified the text size changes after the upgrade
* Verified the text colour of HTTPS is changed after upgrade 
1.12.1(19.9.20.23)
![image](https://user-images.githubusercontent.com/17010094/67251546-7e42cc00-f43d-11e9-8c08-6e33608fc411.png)
1.13(19.10.21.22)
![image](https://user-images.githubusercontent.com/17010094/67251541-784ceb00-f43d-11e9-9ba2-1882b37e77c0.png)
