### ISSUE TITLE
Add payment id to brave://rewards-internals to help support with testing

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1643]
@tmancey commented on [Thu Oct 03 2019](https://github.com/brave/brave-rewards-ios/issues/236)

Add payment id to brave://rewards-internals to help support with testing

---

@kylehickinson commented on [Thu Oct 03 2019](https://github.com/brave/brave-rewards-ios/issues/236#issuecomment-538033014)

So we don't have a `brave://` url scheme style settings the same way as desktop. Perhaps we can add a special `brave://rewards-internals` check to the URL and if it is, we display a native VC with the info?

---

@tmancey commented on [Thu Oct 03 2019](https://github.com/brave/brave-rewards-ios/issues/236#issuecomment-538033803)

Or we just access from the about screen, @anthonypkeane @alexwykoff your thoughts?

---

@kylehickinson commented on [Thu Oct 03 2019](https://github.com/brave/brave-rewards-ios/issues/236#issuecomment-538035241)

We don't have an about screen :) Currently clicking on the Version number in the About section in shows a copy version number sheet.

---

@tmancey commented on [Thu Oct 03 2019](https://github.com/brave/brave-rewards-ios/issues/236#issuecomment-538040108)

@kylehickinson @jamesmudgett could make sense to just add to the about section also with a copy sheet

---

@kylehickinson commented on [Thu Oct 03 2019](https://github.com/brave/brave-rewards-ios/issues/236#issuecomment-538078445)

Yeah that could work too, do we care about all the rewards internal info? (Key Info Seed validity, Persona ID, User ID, Wallet creation date)

---

@tmancey commented on [Thu Oct 03 2019](https://github.com/brave/brave-rewards-ios/issues/236#issuecomment-538099734)

@NejcZdovc Your thoughts please?

---

@NejcZdovc commented on [Thu Oct 03 2019](https://github.com/brave/brave-rewards-ios/issues/236#issuecomment-538128525)

I would go in native VC way as I see that we will be adding more data to that page and would be good that all platforms are in sync on what we display. This way QA always has the same data

---

@NejcZdovc commented on [Thu Oct 03 2019](https://github.com/brave/brave-rewards-ios/issues/236#issuecomment-538152149)

this is what we have on desktop

![image](https://user-images.githubusercontent.com/9574457/66168287-bd75be00-e5f1-11e9-9e44-a70e6676ac26.png)

---

@anthonypkeane commented on [Thu Oct 03 2019](https://github.com/brave/brave-rewards-ios/issues/236#issuecomment-538164269)

I suggest we put this in iOS Settings > Brave > Brave Rewards

 `Brave Reward`s would be a new section within that setting

---

@kylehickinson commented on [Thu Oct 03 2019](https://github.com/brave/brave-rewards-ios/issues/236#issuecomment-538165154)

@anthonypkeane As I mentioned in Slack, this wouldn't work well for support. The user cannot copy/paste any of the info, the section/settings would have to be visible regardless of if the user has rewards enabled, and also the only way to get that data in there is to write it to UserDefaults, they can't be read and updated on the fly, meaning it's possible for the data to be out of date

**Comment by anthonypkeane** [comment]
Inside OTHER SETTINGS section add a new row called Brave Rewards (above Sync) with a Brave Rewards icon on the left

Tapping on this opens a new view and in here we place:

- Enable Brave Rewards (On | Off)
Subtext: By turning on Rewards, you agree to the Terms of Service (link to the TOS, see onboarding https://github.com/brave/brave-ios/issues/1695) 
- Hide Brave Rewards Icon (On | Off) 
(move it from the main menu to here)
- Reset Rewards (when available) (On | Off)
_Which is only visible when Rewards is enabled_

Towards the bottom of the screen add Payment ID info. 
_Which is only visible when Rewards is enabled_

@jamesmudgett to confirm

**Comment by anthonypkeane** [comment]
>Under OTHER SETTINGS add a new row called Brave Rewards (above Sync) 

@jamesmudgett adding  the BAT icon here before or after Brave Rewards would serve as a nice visual indicator to the user and hopefully connect the the settings menu with the panel

LMK what you think?

**Comment by anthonypkeane** [comment]
UPDATE

Inside OTHER SETTINGS section add a new row called Brave Rewards (above Sync) with a Brave Rewards icon on the left

Tapping on this opens a new view and in here we place:

Hide Brave Rewards Icon (On | Off)
(move it from the main menu to here)


Towards the bottom of the screen add Payment ID info.
Which is only visible when Rewards is enabled

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.18.15)
* Verified a new section `Brave Rewards`  is added under `Other settings`
![image](https://user-images.githubusercontent.com/17010094/67236895-26459e80-f418-11e9-9873-d1a27eb2f282.png)
* Verified nested option in `Brave Rewards` has an entry for `Hide  Brave Rewards icon` and `Wallet creation date`
* Verified tapping on it shows confirmation message to `Copy Support Info`
![image](https://user-images.githubusercontent.com/17010094/67236908-2c3b7f80-f418-11e9-98f4-9b82d14850fb.png)
* Clicking on `Copy Support Info` copies entire wallet info with retry information 
   ```
   Key Info Seed: Valid
   Wallet Payment ID: 3350f79d-78c3-4168-ac82-520dca6972e0
   Persona ID: 40629E3D-7FC0-4FFA-A260-AACEA4029295
   User ID: 40629E3D7FC0FFAA260AACEA4029295
   Wallet created: 2019-10-21
   Reconciles:
    0FAAD289-01C7-4EA0-83B4-F430A6D50B04:
        Amount: 1
        Retry Step: Final
        Retry Level: -1
   ```
------------------------

Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.10.18.15)
* Verified a new section `Brave Rewards`  is added under `Other settings`
![image](https://user-images.githubusercontent.com/17010094/67236370-26916a00-f417-11e9-8cdb-4a437709cdb5.png)
* Verified nested option in `Brave Rewards` has an entry for `Hide  Brave Rewards icon` and  `Wallet creation date`
* Verified tapping on it shows confirmation message to `Copy Support Info`
![image](https://user-images.githubusercontent.com/17010094/67236387-2c874b00-f417-11e9-8c8e-dfcbc1e446c1.png)
* Clicking on `Copy Support Info` copies entire wallet info with retry information 
   ```
   Key Info Seed: Valid
   Wallet Payment ID: d9749da1-a86e-4a06-a9fd-34b1d88c1ec8
   Persona ID: 791795C0-04D0-4817-800A-C14CDF6BA4CF
   User ID: 791795C004D0817800AC14CDF6BA4CF
   Wallet created: 21/10/19
   ```
----------------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.18.15)
* Verified a new section `Brave Rewards`  is added under `Other settings`
![image](https://user-images.githubusercontent.com/17010094/67233887-0f9c4900-f412-11e9-9f78-8365323e6279.png)
* Verified nested option in `Brave Rewards` has an entry for `Hide  Brave Rewards icon` and `Wallet creation date`
* Verified tapping on it shows confirmation message to `Copy Support Info`
![image](https://user-images.githubusercontent.com/17010094/67233862-0612e100-f412-11e9-97a8-a26cb9cdd026.png)
* Clicking on `Copy Support Info` copies entire wallet info with retry information 
   ```
   Key Info Seed: Valid
   Wallet Payment ID: 7e081b62-9aaa-4685-95df-59a8844eb9fd
   Persona ID: 8C4FF326-C2E0-455C-B556-8899FCA7E13A
   User ID: 8C4FF326C2E055CB5568899FCA7E13A
   Wallet created: 2019-10-21
   ```
---------------
Verification passed on iPhone 6 with iOS 13.4 running 1.13(19.10.18.15)
* Verified a new section `Brave Rewards`  is added under `Other settings`
![image](https://user-images.githubusercontent.com/17010094/67236007-568c3d80-f416-11e9-82cd-52c907434516.png)
* Verified nested option in `Brave Rewards` has an entry for `Hide  Brave Rewards icon` and `Wallet creation date`
* Verified tapping on it shows confirmation message to `Copy Support Info`
![image](https://user-images.githubusercontent.com/17010094/67236034-673cb380-f416-11e9-854b-6a36eef8ca7c.png)
* Clicking on `Copy Support Info` copies entire wallet info with retry information 
   ```
   Key Info Seed: Valid
   Wallet Payment ID: 31894e8c-550e-4e16-a25a-1023f60bfb18
   Persona ID: A86EA645-8694-4DAF-92BA-139FE74C20BE
   User ID: A86EA6458694DAF92BA139FE74C20BE 
   Wallet created: 19/10/19
   ```
----------------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.18.15)
* Verified a new section `Brave Rewards`  is added under `Other settings`
![image](https://user-images.githubusercontent.com/17010094/67234175-a79a3280-f412-11e9-9ab7-6fe34ab7ba30.png)
* Verified nested option in `Brave Rewards` has an entry for `Hide  Brave Rewards icon` and `Wallet creation date` 
![image](https://user-images.githubusercontent.com/17010094/67234186-ae28aa00-f412-11e9-9dd2-975a5b7a7f1e.png)
* Verified tapping on it shows confirmation message to `Copy Support Info`
![image](https://user-images.githubusercontent.com/17010094/67234198-b2ed5e00-f412-11e9-8b47-bde8c48cec6e.png)
* Clicking on `Copy Support Info` copies entire wallet info with retry information 
   ```
   Key Info Seed: Valid
   Wallet Payment ID: 1686be78-fc28-49b6-9e80-44a0eb698a18
   Persona ID: 13A576EA-EB79-451F-8115-7CE3A949DB91
   User ID: 13A576EAEB7951F81157CE3A949DB91
   Wallet created: 21/10/19
   ```
