### ISSUE TITLE
Custom notification text change

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1645]
Please change

Advertisement
for
BRAVE REWARDS 

BRAVE REWARDS is to be all caps

cc @jamesmudgett

**Comment by kylehickinson** [comment]
Duplicate of https://github.com/brave/brave-rewards-ios/issues/243

**Comment by srirambv** [comment]
* Verification passed on iPhone Xr with iOS 13.2 running 1.13(19.10.18.15)
![image](https://user-images.githubusercontent.com/17010094/67131167-9c0bf900-f1d1-11e9-83d5-fb3678e923e7.png)

* Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.10.18.15)
![image](https://user-images.githubusercontent.com/17010094/67131193-b04ff600-f1d1-11e9-97dd-63f6d144ab17.png)

* Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.18.15)
![image](https://user-images.githubusercontent.com/17010094/67131183-a9c17e80-f1d1-11e9-8a41-1bf07a869959.png)

* Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.18.15)
![image](https://user-images.githubusercontent.com/17010094/67131200-b80f9a80-f1d1-11e9-8428-03207d9563a9.png)

* Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.18.15)
![image](https://user-images.githubusercontent.com/17010094/67131173-a0d0ad00-f1d1-11e9-875d-451befcb18b2.png)
