### ISSUE TITLE
New designs for NFC integration

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1646]
## Description
NFC integration for YubiKey needs another modal. This modal lets user select which key to use `NFC` vs `Lightning`.

## Current mock up

![Screen Shot 2019-10-14 at 3 14 34 PM](https://user-images.githubusercontent.com/1903815/66786526-80cd8080-ee95-11e9-8be8-e55c7c1c28c7.png)

## Designs
Add a prelimary onboarding screen that informs the user they can scan or tap their Yubikey. Update the motion graphic with one that depicts inserting a Yubikey or scanning it.

![1 first time](https://user-images.githubusercontent.com/2388823/66877024-c8710c80-ef68-11e9-865f-ab90ebc0c1bd.png)

When the user taps, "Next", show Apple's scan UI but change the description to "Insert or scan your security key…"

![2 second time](https://user-images.githubusercontent.com/2388823/66877042-da52af80-ef68-11e9-8909-af61e3ac6eac.png)

After the first time, do not show the prelimary onboarding screen and only show the Apple scan UI.

## User Flow
![user flow - yubikey insert or scan](https://user-images.githubusercontent.com/2388823/66877079-02421300-ef69-11e9-8850-adaee81e6c30.png)

## Assets
Updated motion graphic TBA

**Comment by iccub** [comment]
Fixed in https://github.com/brave/brave-ios/issues/1609 (correct me if im wrong)
