### ISSUE TITLE
Add Translations for Rewards

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1648]
My First Ad feature (#155) added 2 new strings (`Strings.MyFirstAdTitle`, `Strings.MyFirstAdBody`) that need translations pushed to transifex

**Comment by iccub** [comment]
Will be fixed in https://github.com/brave/brave-ios/issues/1698

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.11.4.20)
* Verified onboarding and sample ad and rewards panel contents are translated in French
![XR_France](https://user-images.githubusercontent.com/17010094/68238384-12cd3280-ffd7-11e9-9a50-2c6cad45aa95.gif)
* Verified onboarding and sample ad and rewards panel contents are translated in German
![XR_Germany](https://user-images.githubusercontent.com/17010094/68238393-16f95000-ffd7-11e9-919b-b973581d060d.gif)
* Verified onboarding and sample ad and rewards panel contents are translated in Japanese
![XR_Japanese](https://user-images.githubusercontent.com/17010094/68238407-1d87c780-ffd7-11e9-9bb0-003bf7765862.gif)
------------
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.11.4.20)
* Verified onboarding and sample ad and rewards panel contents are translated in French
![7_France](https://user-images.githubusercontent.com/17010094/68239370-d7cbfe80-ffd8-11e9-9d81-3208342bd453.gif)
* Verified onboarding and sample ad and rewards panel contents are translated in German
![7_German](https://user-images.githubusercontent.com/17010094/68239393-e0bcd000-ffd8-11e9-9076-e805d8c02804.gif)
* Verified onboarding and sample ad and rewards panel contents are translated in Japanese
![7_Japan](https://user-images.githubusercontent.com/17010094/68239386-dc90b280-ffd8-11e9-9a41-f6b1150455be.gif)
------------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.11.4.20)
* Verified onboarding and sample ad and rewards panel contents are translated in French
![ipad_France](https://user-images.githubusercontent.com/17010094/68240129-507f8a80-ffda-11e9-89e6-d08b48c582f6.gif)
* Verified onboarding and sample ad and rewards panel contents are translated in German
![ipad_German](https://user-images.githubusercontent.com/17010094/68240138-54aba800-ffda-11e9-936c-7ad24e24d956.gif)
* Verified onboarding and sample ad and rewards panel contents are translated in Japanese
![iPad_Japan](https://user-images.githubusercontent.com/17010094/68240155-583f2f00-ffda-11e9-986c-6fc64391375e.gif)
------------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.11.4.20)
* Verified onboarding and sample ad and rewards panel contents are translated in French
* Verified onboarding and sample ad and rewards panel contents are translated in German
* Verified onboarding and sample ad and rewards panel contents are translated in Japanese
-----------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.11.4.20)
* Verified onboarding and sample ad and rewards panel contents are translated in French
* Verified onboarding and sample ad and rewards panel contents are translated in German
* Verified onboarding and sample ad and rewards panel contents are translated in Japanese
------------
