### ISSUE TITLE
Onboarding UI should extend into bottom safe area

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1649]
On an iPhone that doesn't have a home button, the white box should extend into the safe area

![Image from iOS](https://user-images.githubusercontent.com/529104/66601188-5027d700-eb75-11e9-8b6f-a0e2a1c6092b.png)

**Comment by srirambv** [comment]
Verification passed on iPhone Xr with iOS 13.2 running 1.13(19.10.18.15)
![image](https://user-images.githubusercontent.com/17010094/67129567-066e6a80-f1cd-11e9-86e6-da87341f99a1.png)
![image](https://user-images.githubusercontent.com/17010094/67129575-0a9a8800-f1cd-11e9-81f2-343746e54c28.png)
![image](https://user-images.githubusercontent.com/17010094/67129579-0e2e0f00-f1cd-11e9-8d3b-94b5632e6c77.png)
![image](https://user-images.githubusercontent.com/17010094/67129581-125a2c80-f1cd-11e9-92b2-40b3803f3107.png)
![image](https://user-images.githubusercontent.com/17010094/67129590-171ee080-f1cd-11e9-83c8-4a9502d14fb2.png)
