### ISSUE TITLE
Remove redundant iOS 11 version checks

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#165]
There are 17 uses of `if #available(iOS 11, *)` throughout the project which are redundant because we are supporting iOS 11+. These should be removed

**Comment by ccampbell** [comment]
Hi there. I am still running iOS 11 and I am not able to install the app. It seems in the App Store it is marked as only being available for iOS 12 and later. Just wondering if there is a specific reason for this or if you would be open to a PR adding support for iOS 11. 

I would upgrade my phone, but I don’t want iOS 13, and I don’t t hink there is a way to upgrade to 12 without going to 13 😞
