### ISSUE TITLE
Change onboarding button title

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1650]
In Onboarding
Please change the button text for Rewards from “Join” to “Switch on”

**Comment by srirambv** [comment]
* Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.21.22)
![image](https://user-images.githubusercontent.com/17010094/67297451-ec2bd980-f4b7-11e9-92b0-8823346a40c4.png)

* Verification passed on iPhone 7+ with iOS 13.1 running 1.13(19.10.21.22)
![image](https://user-images.githubusercontent.com/17010094/67297526-0665b780-f4b8-11e9-86c8-0ec756647d52.png)

* Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.21.22)
![image](https://user-images.githubusercontent.com/17010094/67297480-f8b03200-f4b7-11e9-995c-8c5b4e4dae02.png)

* Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.21.22)
![image](https://user-images.githubusercontent.com/17010094/67297500-ff3ea980-f4b7-11e9-8ee3-09b14f7ed6e8.png)

* Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.21.22)
![image](https://user-images.githubusercontent.com/17010094/67297472-f3eb7e00-f4b7-11e9-8be3-328d9796aac4.png)
