### ISSUE TITLE
Dismissing my first ad opens a new tab anyways

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1652]
Saw this happen during screen-share with Danish. He swiped upwards to dismiss and it opened tab anyways. Not sure if it was due to a tap registering while it was dismissing or not.

It should only open when user clicks directly on it

**Comment by kylehickinson** [comment]
Couldn't reproduce, please re-open if reproduced

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.25.14)
* Verified dismissing the notification doesn't open a new tab
* Verified left swipe dismisses the notification and doesn't open a new tab
-------------
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.25.14)
* Verified dismissing the notification doesn't open a new tab
* Verified left swipe dismisses the notification and doesn't open a new tab
-------------
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.10.25.14)
* Verified dismissing the notification doesn't open a new tab
* Verified left swipe dismisses the notification and doesn't open a new tab
-------------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.25.14)
* Verified dismissing the notification doesn't open a new tab
* Verified left swipe dismisses the notification and doesn't open a new tab
-------------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.25.14)
* Verified dismissing the notification doesn't open a new tab
* Verified left swipe dismisses the notification and doesn't open a new tab
-------------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.25.14)
* Verified dismissing the notification doesn't open a new tab
* Verified left swipe dismisses the notification and doesn't open a new tab
