### ISSUE TITLE
Should focus on an open browser tab if the URL matches instead of opening a new tab

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#1653]

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified steps from test plan in #2245 
--------
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.12.10)
- Verified steps from test plan in #2245 
--------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.12.10)
- Verified steps from test plan in #2245 
--------
Verification passed on iPad Pro  with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified steps from test plan in #2245 
--------
Verification passed on iPad Pro  with iOS 12.4.4 running 1.15(20.02.12.10)
- Verified steps from test plan in #2245 
--------

Logged follow up suggestion issue #2334
