### ISSUE TITLE
Implement virtual grants

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#1654]

**Comment by srirambv** [comment]
* Verification passed on iPhone XR with iOS 13.2 running 1.13(19.11.4.20)
* Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.11.4.20)
* Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.11.4.20)
* Verification passed on iPad Pro with iOS 13.2 running 1.13(19.11.4.20)
* Verification passed on iPad pro with iOS 12.4 running 1.13(19.11.4.20)
