### ISSUE TITLE
Add support for claiming a grants

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1656]
When a grant is available the user can claim it on the settings screen (or a notifications). 

This needs to be integrated from both points (`solveGrantCaptcha`)

No expiration date when claiming ads earnings in the grant claim screen

Blocked by https://github.com/brave/brave-core/pull/3294

**Comment by srirambv** [comment]
* Verification passed on iPhone XR with iOS 13.2 running 1.13(19.11.4.20)
* Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.11.4.20)
* Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.11.4.20)
* Verification passed on iPad Pro with iOS 13.2 running 1.13(19.11.4.20)
* Verification passed on iPad Pro with iOS 12.4 running 1.13(19.11.4.20)
