### ISSUE TITLE
Clearing browser history should also clear ads history

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1658]
Needs info whether or not this is going to be its own toggle or part of history deletion

**Comment by anthonypkeane** [comment]
Desktop Issue: https://github.com/brave/brave-browser/issues/926

**Comment by anthonypkeane** [comment]
Not required for V1

**Comment by kylehickinson** [comment]
Waiting on implementation details here: https://github.com/brave/brave-browser/issues/926

**Comment by NejcZdovc** [comment]
closing as this should be done as part of https://github.com/brave/brave-ios/issues/1642
