### ISSUE TITLE
Implement system (quiet) notification to alert users there is an Ad Grant available

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1660]
Once a month on ad grant reconciliation day alert users via a system notification (quiet notification) that they have BAT to collect. 

Details on (quiet) notification: http://iosbrain.com/blog/2018/07/05/new-in-ios-12-implementing-provisional-authorization-for-quiet-notifications-in-swift/

Placeholder while I gather the details: @tmancey I will need you help spec'ing out this issue.

**Comment by anthonypkeane** [comment]
>What are we saying in the alert

TBD but for now use: 

Brave Rewards Ads
Looks like you have some BAT waiting for you. Claim it now!


>Where does it go when the user clicks on it

Open the browser and the Rewards Panel


>What happens if the user clicks it and there's no grant there (since we are just sending it every month at a given time)

As we discussed, we should only send this notification if there is an ad grant. You mentioned checking for ad count as a way to do this. 

>Do we schedule it anyways if the user hasn't viewed any ads (somehow)?

No

>Logic has to be in place to schedule/reschedule based on if the user enables/disables ads during the month

- If Ads are enabled, and as soon as possible, i.e. on first open, schedule the notification to fire on the 7th of each month at 1.21 pm local time. 

- If Ads are disabled, cancel the notification

- I need you help figuring out when to cancel the notification if no ads were shown

**Comment by anthonypkeane** [comment]
Reluctantly moving to 1.15, missing the first ad grant claim :(

**Comment by kylehickinson** [comment]
> I need you help figuring out when to cancel the notification if no ads were shown

What in particular do you need help with here?

**Comment by anthonypkeane** [comment]
Discussion about 
>What in particular do you need help with here?

here: https://bravesoftware.slack.com/archives/CKA10H3AS/p1573859707000100

**Comment by anthonypkeane** [comment]
**Update:**

Trigger point for scheduling this notification: 

Schedule: Any time an ad is shown, if no notification is scheduled, schedule it. 
Cancel the trigger, if the user has already claimed their ad grant for that month

**Comment by kylehickinson** [comment]
Simplified Logic:
- Always scheduling following month based on seeing an ad in the current month (i.e. seeing an ad anytime in November, schedules for Dec 7th)
- Claiming an ad grant cancels the current months notification if it exists (i.e. claim grant on the Dec 6th cancels any notification scheduled for Dec)

**Comment by anthonypkeane** [comment]
Updated copy

**Claim your Brave ad rewards**
Time to get rewarded for those ads you've been seeing in Brave.

Taping should open Brave with the panel open

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.22.15)
* Verified no notification shown if there are no ads earning accumulated 
* Verified notification shows up as per test plan
![image](https://user-images.githubusercontent.com/17010094/69583134-26e9cb80-0fa8-11ea-8d36-f8b3e7e22aed.png)
```
[Debug] [BraveRewards] > Scheduled monthly ad grant reminder: <UNNotificationRequest: 0x2966279f0; identifier: rewards.notification.monthly-claim-12, content: <UNNotificationContent: 0x280a00c30; title: <redacted>, subtitle: (null), body: <redacted>, summaryArgument: , summaryArgumentCount: 0, categoryIdentifier: , launchImageName: , threadIdentifier: , attachments: (
), badge: (null), sound: (null), realert: 0, trigger: <UNCalendarNotificationTrigger: 0x28301cf20; dateComponents: <NSDateComponents: 0x283235ef0> {
    Calendar: <CFCalendar 0x2812f4af0 [0x1fec1f5e0]>{identifier = 'gregorian'}
    Month: 12
    Day: 7
    Hour: 13
    Minute: 21, repeats: NO>>. Trigger date: Optional(2019-12-07 18:21:00 +0000)
```
----------------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.22.15)
* Verified no notification shown if there are no ads earning accumulated 
* Verified notification shows up as per test plan
![image](https://user-images.githubusercontent.com/17010094/69582799-58ae6280-0fa7-11ea-997f-00027f068583.png)
```
[Debug] [BraveRewards] > Scheduled monthly ad grant reminder: <UNNotificationRequest: 0x2966279f0; identifier: rewards.notification.monthly-claim-12, content: <UNNotificationContent: 0x280a00c30; title: <redacted>, subtitle: (null), body: <redacted>, summaryArgument: , summaryArgumentCount: 0, categoryIdentifier: , launchImageName: , threadIdentifier: , attachments: (
), badge: (null), sound: (null), realert: 0, trigger: <UNCalendarNotificationTrigger: 0x28301cf20; dateComponents: <NSDateComponents: 0x283235ef0> {
    Calendar: <CFCalendar 0x2812f4af0 [0x1fec1f5e0]>{identifier = 'gregorian'}
    Month: 12
    Day: 7
    Hour: 13
    Minute: 21, repeats: NO>>. Trigger date: Optional(2019-12-07 18:21:00 +0000)
```
-----------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.22.15)
* Verified no notification shown if there are no ads earning accumulated 
* Verified notification shows up as per test plan
![image](https://user-images.githubusercontent.com/17010094/69583185-4ed92f00-0fa8-11ea-963a-d19718b4f2cc.png)
```
[Debug] [BraveRewards] > Scheduled monthly ad grant reminder: <UNNotificationRequest: 0x295f1aee0; identifier: rewards.notification.monthly-claim-1, content: <UNNotificationContent: 0x2832bdc70; title: <redacted>, subtitle: (null), body: <redacted>, summaryArgument: , summaryArgumentCount: 0, categoryIdentifier: , launchImageName: , threadIdentifier: , attachments: (
), badge: (null), sound: (null), realert: 0, trigger: <UNCalendarNotificationTrigger: 0x2808befc0; dateComponents: <NSDateComponents: 0x280b267d0> {
    Calendar: <CFCalendar 0x2829a45f0 [0x1f79bb5e0]>{identifier = 'gregorian'}
    Month: 1
    Day: 7
    Hour: 13
    Minute: 21, repeats: NO>>. Trigger date: Optional(2020-01-07 18:21:00 +0000)
```
-----------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.22.15)
* Verified no notification shown if there are no ads earning accumulated 
* Verified notification shows up as per test plan
![image](https://user-images.githubusercontent.com/17010094/69583244-70d2b180-0fa8-11ea-97a1-224f420b2aca.png)
```
[Debug] [BraveRewards] > Scheduled monthly ad grant reminder: <UNNotificationRequest: 0x295d04060; identifier: rewards.notification.monthly-claim-12, content: <UNNotificationContent: 0x2831f9bc0; title: Claim your Brave ads rewards, subtitle: (null), body: Time to get rewarded for those ads you've been seeing in Brave., summaryArgument: , summaryArgumentCount: 0, categoryIdentifier: , launchImageName: , threadIdentifier: , attachments: (
), badge: (null), sound: (null),, trigger: <UNCalendarNotificationTrigger: 0x280bf9060; dateComponents: <NSDateComponents: 0x283cac160>
    Calendar: <_NSCopyOnWriteCalendarWrapper: 0x280bf9d60>
    Month: 12
    Day: 7
    Hour: 13
    Minute: 21, repeats: NO>>. Trigger date: Optional(2019-12-07 07:51:00 +0000)
```
-------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.22.15)
* Verified no notification shown if there are no ads earning accumulated 
* Verified notification shows up as per test plan
```
[Debug] [BraveRewards] > Scheduled monthly ad grant reminder: <UNNotificationRequest: 0x297598570; identifier: rewards.notification.monthly-claim-12, content: <UNNotificationContent: 0x2816fdb00; title: Claim your Brave ads rewards, subtitle: (null), body: Time to get rewarded for those ads you've been seeing in Brave., summaryArgument: , summaryArgumentCount: 0, categoryIdentifier: , launchImageName: , threadIdentifier: , attachments: (
), badge: (null), sound: (null),, trigger: <UNCalendarNotificationTrigger: 0x282338620; dateComponents: <NSDateComponents: 0x281440630>
    Calendar: <_NSCopyOnWriteCalendarWrapper: 0x28233bd80>
    Month: 12
    Day: 7
    Hour: 13
    Minute: 21, repeats: NO>>. Trigger date: Optional(2019-12-07 07:51:00 +0000)
```
