### ISSUE TITLE
Disabling Auto-Contribute should show "Reward creators for the content you love. Your monthly payment gets distributed across the sites you visit." Copy and icon

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#1662]

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.3.1 running 1.15(20.01.13.17)
- Verified graphics is shown when the individual setting is disabled
![image](https://user-images.githubusercontent.com/17010094/72377669-e40dbf80-36dd-11ea-9a4e-006369cc6a88.png)
- Verified graphics is shown when Rewards is disabled
![image](https://user-images.githubusercontent.com/17010094/72377661-e07a3880-36dd-11ea-8945-12c968bbb2d2.png)

-----
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.01.13.17)
- Verified graphics is shown when the individual setting is disabled
![image](https://user-images.githubusercontent.com/17010094/72377640-d6583a00-36dd-11ea-8866-6a1e5f4b22af.png)
- Verified graphics is shown when Rewards is disabled
![image](https://user-images.githubusercontent.com/17010094/72377620-ca6c7800-36dd-11ea-8de0-f752d8170515.png)

-----
Verification passed on iPhone 6 with iOS 12..4.4 running 1.15(20.01.13.17)
- Verified graphics is shown when the individual setting is disabled
![image](https://user-images.githubusercontent.com/17010094/72377837-3d75ee80-36de-11ea-8a40-259b51ad4538.png)
- Verified graphics is shown when Rewards is disabled
![image](https://user-images.githubusercontent.com/17010094/72377825-3949d100-36de-11ea-81b1-b33f03df3c21.png)

------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.01.13.17)
- Verified graphics is shown when the individual setting is disabled
![image](https://user-images.githubusercontent.com/17010094/72377558-b0cb3080-36dd-11ea-9366-4a74fe173d7d.png)
- Verified graphics is shown when Rewards is disabled
![image](https://user-images.githubusercontent.com/17010094/72377573-b6287b00-36dd-11ea-81a5-50124dc7987f.png)
-----
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.01.13.17)
- Verified graphics is shown when the individual setting is disabled
![image](https://user-images.githubusercontent.com/17010094/72377587-be80b600-36dd-11ea-9ffa-9a1661860867.png)
- Verified graphics is shown when Rewards is disabled
![image](https://user-images.githubusercontent.com/17010094/72377599-c2acd380-36dd-11ea-9ad4-fee3c1e6bd43.png)
