### ISSUE TITLE
Replace hard-coded origin checks in Rewards Reporting

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1663]
PR: https://github.com/brave/brave-ios/pull/1387
Commit: https://github.com/brave/brave-ios/pull/1387/commits/aba4b5b4e354aa026da33e26e3681132f793fabc

As a temporary solution to get through security review hard-coded origins were added to the rewards reporting JS script to avoid sending data to the app and then to ledger when not needed.

We will want to remove those hard-coded origins and implement a better solution that will use `IsMediaLink` from the native lib and enable/disable the user script per origin change.

The native lib method will have to be changed to check for any media type rather than just Vimeo & Twitch.

**Comment by kylehickinson** [comment]
@NejcZdovc Perhaps this could be solved with #1673 ?

**Comment by NejcZdovc** [comment]
Correct
