### ISSUE TITLE
Dismissing the rewards panel while joining and opening it again before it finishes shows "join rewards" instead of loader

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1664]
In order to fix this we need to have a boolean flag for whether or not the wallet is being created to be publicly visible from brave-core so that we may update the Create Wallet screen accordingly.

Also this would allow us to not force the user to wait for create wallet to finish in rewards onboarding

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.18.15)
* Verified test plan from #1636 

Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.18.15)
* Verified test plan from #1636 

Verification passed on iPhone 7+ with iOS 13.1 running 1.13(19.10.18.15)
* Verified test plan from #1636 

Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.18.15)
* Verified test plan from #1636 

Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.18.15)
* Verified test plan from #1636 

Logged #1750  which was reproduced on all devices
