### ISSUE TITLE
Migrate Preferences

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#167]
Blocked per needing detailed information on _what is left to be migrated_. Search engines is likely one area.

Search engines were moved to `Preferences` object, 1.6 uses FF's `Prefs`, needs to be migrated.

`Migration.swift` → `// TODO: Search engine migration`

General audit required to see what else needs migrating

**Comment by tmancey** [comment]
This ticket is blocked with development as needs further investigation

**Comment by kylehickinson** [comment]
https://github.com/brave/brave-ios/blob/development/Client/Frontend/Browser/Search/SearchEngines.swift#L90

Verify that the tests past still after migrating
