### ISSUE TITLE
Add Screen/UI for showing pending Contributions

### ISSUE THREAD

**Issue by danishjafri88** [brave/brave-ios#1670]
Currently on Desktop, users can see the list of pending contributions along with an option to remove them. This screen is missing in iOS in the current development iteration. 

![](https://user-images.githubusercontent.com/5398557/62230811-46992a80-b3e0-11e9-9ec9-ee89eb19216d.png)

**Comment by kylehickinson** [comment]
Design:
- Pending contributions link will be shown in the panel wallet summary under the unverified publisher BAT amount disclaimer when there are pending contributions
- List will show site + amount like one-time tips, tapping said item will show details including the type/pending until and ability to remove the pending contribution

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.18.17)
- Verified pending contribution flow works fine
- Disclaimer
![image](https://user-images.githubusercontent.com/17010094/74827356-4f792b80-5333-11ea-8e63-a35c5f25ebf9.png)
- Pending List
![image](https://user-images.githubusercontent.com/17010094/74827375-556f0c80-5333-11ea-923c-55a22ecd120e.png)
- Site details
![image](https://user-images.githubusercontent.com/17010094/74827386-5c961a80-5333-11ea-8fa9-214d2e493ad6.png)
- Edit mode
![image](https://user-images.githubusercontent.com/17010094/74827397-615ace80-5333-11ea-9e98-d5b984425ec4.png)
--------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.18.17)
- Verified pending contribution flow works fine
- Disclaimer
![image](https://user-images.githubusercontent.com/17010094/74827204-00cb9180-5333-11ea-8a73-3a18400a4528.png)
- Pending List
![image](https://user-images.githubusercontent.com/17010094/74827224-0923cc80-5333-11ea-9a1e-101b411d3d26.png)
- Site details
![image](https://user-images.githubusercontent.com/17010094/74827235-0d4fea00-5333-11ea-8a49-ff6e9b679a7c.png)
- Edit mode 
![image](https://user-images.githubusercontent.com/17010094/74827242-12ad3480-5333-11ea-9cb1-f0f23383d337.png)
--------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified pending contribution flow works fine
- Disclaimer
![image](https://user-images.githubusercontent.com/17010094/74827281-28baf500-5333-11ea-9b67-6a34f2fff742.png)
- Pending List
![image](https://user-images.githubusercontent.com/17010094/74827267-222c7d80-5333-11ea-9356-d58fd4766eb8.png)
- Site details
![image](https://user-images.githubusercontent.com/17010094/74827291-2eb0d600-5333-11ea-82f0-ed1c17c15de0.png)
- Edit mode 
![image](https://user-images.githubusercontent.com/17010094/74827311-37a1a780-5333-11ea-93cf-c4fcf17fdec6.png)
--------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified pending contribution flow works fine
- Disclaimer
![image](https://user-images.githubusercontent.com/17010094/74827107-d37ee380-5332-11ea-919f-9b53c9088933.png)
- Pending List
![image](https://user-images.githubusercontent.com/17010094/74827145-e4c7f000-5332-11ea-921e-0697525739e0.png)
- Site details
![image](https://user-images.githubusercontent.com/17010094/74827119-d7ab0100-5332-11ea-9f3e-07f7a5c86059.png)
- Edit mode 
![image](https://user-images.githubusercontent.com/17010094/74827177-f3aea280-5332-11ea-967b-006e3a30ee64.png)
--------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.18.17)
- Verified pending contribution flow works fine
- Disclaimer
![image](https://user-images.githubusercontent.com/17010094/74826368-79c9e980-5331-11ea-87b8-3fe780e9f3da.png)
- Pending List
![image](https://user-images.githubusercontent.com/17010094/74827107-d37ee380-5332-11ea-919f-9b53c9088933.png)
- Site details
![image](https://user-images.githubusercontent.com/17010094/74827145-e4c7f000-5332-11ea-921e-0697525739e0.png)
- Edit mode
![image](https://user-images.githubusercontent.com/17010094/74827077-c19d4080-5332-11ea-8672-22ee556c2e4e.png)
--------
