### ISSUE TITLE
Consider reducing the height of the panel 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1671]
The rewards panel height is way too big on a 6.1" device (iPhone 7). It covers almost 90% of the screen and is 

![image](https://user-images.githubusercontent.com/17010094/63442333-ec005680-c400-11e9-9c52-23f011e00a05.png)

Looks really odd with an  **almost** full-screen panel with a lot of empty space at the bottom
![image](https://user-images.githubusercontent.com/17010094/63442787-af812a80-c401-11e9-87f9-783e40edca9a.png)

![image](https://user-images.githubusercontent.com/17010094/63442551-4f8a8400-c401-11e9-8349-90e178b751e7.png)

**Comment by srirambv** [comment]
@kylehickinson @anthonypkeane is this going to be done as part of MVP? It really looks bad when the panel covers 90% of the screen even on iPhone X

**Comment by kylehickinson** [comment]
cc @jamesmudgett

**Comment by jamesmudgett** [comment]
Since you are likely navigating to the screen to see the contents of settings, I don't think we should reduce the size. This is an improvement already over going full screen on settings vs displaying in the rewards panel.

**Comment by anthonypkeane** [comment]
Internal Chat: https://bravesoftware.slack.com/archives/CKA10H3AS/p1571158440034100

**Comment by jamesmudgett** [comment]
I understand the nested settings may require less vertical space but I think adjusting vertical height to match each table would be disorienting.

**Comment by anthonypkeane** [comment]
Closing as we aren't doing it

**Comment by srirambv** [comment]
@jamesmudgett  the second and third screenshots look really bad on when there is just too much empty space
