### ISSUE TITLE
Implement restoration of individually excluded sites

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#1674]
![image](https://user-images.githubusercontent.com/529104/72546084-21965800-3858-11ea-8d88-4a856d592d39.png)

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified test plan from #2217
- `Auto Contribution` details view
![image](https://user-images.githubusercontent.com/17010094/74846759-0dfa7780-5357-11ea-97cb-ff94955e7355.png)
- `Supported Sites` view
![image](https://user-images.githubusercontent.com/17010094/74846843-2ff3fa00-5357-11ea-9450-04d5894648c1.png)
- `Excluded Sites` view
![image](https://user-images.githubusercontent.com/17010094/74846853-34b8ae00-5357-11ea-9b31-e173049e8c0a.png)
- `Supported Sites` edit view
![image](https://user-images.githubusercontent.com/17010094/74846869-38e4cb80-5357-11ea-8c6c-b35d24beb92f.png)
![image](https://user-images.githubusercontent.com/17010094/74846893-426e3380-5357-11ea-8f67-102655bd2f13.png)
- `Excluded Sites` edit view
![image](https://user-images.githubusercontent.com/17010094/74846906-4601ba80-5357-11ea-9922-5ea4a2fcbade.png)
![image](https://user-images.githubusercontent.com/17010094/74846920-4e59f580-5357-11ea-852c-c6c8ff150fee.png)
----------
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.18.17)
- Verified test plan from #2217
- `Auto Contribution` details view
![image](https://user-images.githubusercontent.com/17010094/74846949-5a45b780-5357-11ea-8d0a-d3c0d2af23da.png)
- `Supported Sites` view
![image](https://user-images.githubusercontent.com/17010094/74846958-5f0a6b80-5357-11ea-9fd3-d174a3b799f4.png)
- `Excluded Sites` view
![image](https://user-images.githubusercontent.com/17010094/74847000-6cbff100-5357-11ea-91b4-b0ad07af472d.png)
- `Supported Sites` edit view
![image](https://user-images.githubusercontent.com/17010094/74846972-6467b600-5357-11ea-8a6d-28d6f72253dc.png)
![image](https://user-images.githubusercontent.com/17010094/74847050-82351b00-5357-11ea-9384-39e3ee2d72a0.png)
- `Excluded Sites` edit view
![image](https://user-images.githubusercontent.com/17010094/74847025-76e1ef80-5357-11ea-897a-393d9879facf.png)
![image](https://user-images.githubusercontent.com/17010094/74847037-7b0e0d00-5357-11ea-9e1f-19bc95d205ee.png)
----------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.18.17)
- Verified test plan from #2217
- `Auto Contribution` details view
![image](https://user-images.githubusercontent.com/17010094/74847358-fe2f6300-5357-11ea-93c9-06e7b285e992.png)
- `Supported Sites` view
![image](https://user-images.githubusercontent.com/17010094/74847369-038cad80-5358-11ea-8a6b-6c2b1eef8cad.png)
- `Excluded Sites` view
![image](https://user-images.githubusercontent.com/17010094/74847425-17d0aa80-5358-11ea-96c1-540f2b383b37.png)
- `Supported Sites` edit view
![image](https://user-images.githubusercontent.com/17010094/74847391-0a1b2500-5358-11ea-9282-f8f6e9de420a.png)
![image](https://user-images.githubusercontent.com/17010094/74847409-11dac980-5358-11ea-9feb-37c9040189b5.png)
- `Excluded Sites` edit view
![image](https://user-images.githubusercontent.com/17010094/74847441-1d2df500-5358-11ea-8701-38103dc9eda3.png)
![image](https://user-images.githubusercontent.com/17010094/74847462-24ed9980-5358-11ea-950d-2871a4373d65.png)
----------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.18.17)
- Verified test plan from #2217
- `Auto Contribution` details view
![image](https://user-images.githubusercontent.com/17010094/74897929-74ff4700-53be-11ea-95f9-f66d9c255eb4.png)
- `Supported Sites` view
![image](https://user-images.githubusercontent.com/17010094/74897944-7d578200-53be-11ea-8e89-b3dbc7ce0277.png)
- `Excluded Sites` view
![image](https://user-images.githubusercontent.com/17010094/74897940-792b6480-53be-11ea-8d18-bae43e957b8e.png)
- `Supported Sites` edit view
![image](https://user-images.githubusercontent.com/17010094/74897917-6fa1fc80-53be-11ea-80e2-76b93a222e71.png)
![image](https://user-images.githubusercontent.com/17010094/74897940-792b6480-53be-11ea-8d18-bae43e957b8e.png)
- `Excluded Sites` edit view
![image](https://user-images.githubusercontent.com/17010094/74897959-88aaad80-53be-11ea-88fa-6695a9ae597e.png)
![image](https://user-images.githubusercontent.com/17010094/74897964-8ba59e00-53be-11ea-8014-8ff8b2ea01ac.png)
----------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified test plan from #2217
- `Auto Contribution` details view
![image](https://user-images.githubusercontent.com/17010094/74897985-97916000-53be-11ea-9982-2761e32f6ba1.png)
- `Supported Sites` view
![image](https://user-images.githubusercontent.com/17010094/74898063-cc051c00-53be-11ea-9397-75005b958cc3.png)
- `Excluded Sites` view
![image](https://user-images.githubusercontent.com/17010094/74898023-ad068a00-53be-11ea-92d3-45779da8cabf.png)
- `Supported Sites` edit view
![image](https://user-images.githubusercontent.com/17010094/74897985-97916000-53be-11ea-9982-2761e32f6ba1.png)
![image](https://user-images.githubusercontent.com/17010094/74898023-ad068a00-53be-11ea-92d3-45779da8cabf.png)
- `Excluded Sites` edit view
![image](https://user-images.githubusercontent.com/17010094/74898028-b1cb3e00-53be-11ea-8462-546a35bbad5e.png)
![image](https://user-images.githubusercontent.com/17010094/74898018-a8da6c80-53be-11ea-9bd3-031315ed4806.png)
----------
