### ISSUE TITLE
Update Rewards onboarding motion graphic with verified check

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-ios#1680]
### Description
The motion graphics in the onboarding flow needs to be updated with the correct icon for verified creator: https://assets2.lottiefiles.com/packages/lf20_dbg3br.json
preview: https://lottiefiles.com/share/dbg3br

### JSON files
[lottieexport.zip](https://github.com/brave/brave-rewards-ios/files/3727006/lottieexport.zip)

**Comment by chickdan** [comment]
It appears this file was added in #1614

**Comment by kylehickinson** [comment]
Yeah you're right, this one has already been fixed, thanks @chickdan! :)
