### ISSUE TITLE
Update Pub verified/unverified indicators

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#1683]
Rewards is using the old pub verified status icons. New ones attached.
[Archive.zip](https://github.com/brave/brave-ios/files/3729903/Archive.zip)

**Comment by srirambv** [comment]
Verification passed on iPhone Xr with iOS 13.2 running 1.13(19.10.18.15)
* Verified new icon is used on Rewards panel 
![image](https://user-images.githubusercontent.com/17010094/67210340-edd99c80-f3e6-11e9-8ef5-b4f425b07ce2.png)
* Verified new icon is used on both AC and tipping panel
![image](https://user-images.githubusercontent.com/17010094/67228658-c21ade80-f407-11e9-99fa-6778e7794514.png)
![image](https://user-images.githubusercontent.com/17010094/67228672-c9da8300-f407-11e9-8ebd-c6e1d6a83234.png)



Verification passed on iPhone 7+ with iOS 13.1 running 1.13(19.10.18.15)
*  Verified new icon is used on Rewards panel 
* Verified new icon is used on both AC and tipping panel
![image](https://user-images.githubusercontent.com/17010094/67210398-05b12080-f3e7-11e9-8e57-51f96d0ed656.png)

Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.18.15)
*  Verified new icon is used on Rewards panel 
![image](https://user-images.githubusercontent.com/17010094/67210302-dac6cc80-f3e6-11e9-9d1f-76123ce1e09f.png)
* Verified new icon is used on both AC and tipping panel
![image](https://user-images.githubusercontent.com/17010094/67229254-efb45780-f408-11e9-9588-b8b51271193b.png)
![image](https://user-images.githubusercontent.com/17010094/67229269-f80c9280-f408-11e9-845a-1b9fa2d9a813.png)


Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.18.15)
*  Verified new icon is used on Rewards panel 
* Verified new icon is used on both AC and tipping panel
![image](https://user-images.githubusercontent.com/17010094/67210374-ff22a900-f3e6-11e9-84d0-a0e69fe78c2b.png)

Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.18.15)
*  Verified new icon is used on Rewards panel 
* Verified new icon is used on both AC and tipping panel
![image](https://user-images.githubusercontent.com/17010094/67210312-e0241700-f3e6-11e9-9cc6-c2f40d2c6067.png)
