### ISSUE TITLE
One time tip shows crazy exponential value in tips details

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1689]
### Description: 
One time tip shows crazy value  in tips details

### Steps to Reproduce 
  1. Enable rewards and fund wallet
  2. Visit a verified site and do a one time tip
  3. Open tip details, shows crazy exponential value 

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/66862810-afb02900-ef5f-11e9-8488-38578656396f.png)

**Expected result:**
Human readable value such as 1/5/10 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13

**Device details:** 
iPhone Xr

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
It seems that one-time tips are recorded with probi while recurring are not, will have to take a better look at when that changed

**Comment by srirambv** [comment]
This still seems to be an issue on 1.13(19.10.23.22). The USD value is still not shown correctly 
on Japan locale
![image](https://user-images.githubusercontent.com/17010094/67497123-83756600-f64b-11e9-9510-adcabdf2ecb9.png)
on US locale 
![image](https://user-images.githubusercontent.com/17010094/67497162-98ea9000-f64b-11e9-8938-723592ffe5f7.png)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.23.22)
* Verified one-time tip doesn't show exponential value in tip details
![image](https://user-images.githubusercontent.com/17010094/67499016-60988100-f64e-11e9-8c47-d06a2e583262.png)
---------------
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.10.23.22)
* Verified one-time tip doesn't show exponential value in tip details
![image](https://user-images.githubusercontent.com/17010094/67500069-24662000-f650-11e9-84fc-95f45b92d2c0.png)

---------------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.23.22)
* Verified one-time tip doesn't show exponential value in tip details
![image](https://user-images.githubusercontent.com/17010094/67497162-98ea9000-f64b-11e9-8938-723592ffe5f7.png)
---------------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.23.22)
* Verified one-time tip doesn't show exponential value in tip details
![image](https://user-images.githubusercontent.com/17010094/67500079-29c36a80-f650-11e9-9fa3-ada8666c33f2.png)

---------------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.23.22)
* Verified one-time tip doesn't show exponential value in tip details
![image](https://user-images.githubusercontent.com/17010094/67497123-83756600-f64b-11e9-9510-adcabdf2ecb9.png)

-----------------
Logged #1786 for incorrect USD Values
