### ISSUE TITLE
Start browsing button delay is too long looks like onboarding is stuck

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1693]
### Description: 
Joining rewards triggers sample ad notification and then waits for 8secs with the counter at 0. It gives a feeling that the onboarding is stuck. We should consider reducing the wait time before showing the `Start Browsing` button. 

### Steps to Reproduce 
  1. Go through onboarding flow

**Actual result:** 
![FilefromiOS](https://user-images.githubusercontent.com/17010094/66868951-5d293980-ef6c-11e9-91f4-32503f38a329.gif)

**Expected result:**
No UI stall making it look like its stuck without visual feedback

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc: @jamesmudgett @karenkliu @kylehickinson

**Comment by Brandon-T** [comment]
@srirambv I implemented it like this on purpose. I don't actually know if what I did was wrong or not.

Logic:
1. Display countdown.
2. When it hits 0, show my first ad notification.
3. 
    a. If the notification is dismissed naturally, show "Start Browsing".
    b. If the notification is dismissed manually, immediately go to a new browsing tab for ads.

It doesn't show the "Start Browsing" unless the ad disappears either manually or naturally.

**Comment by kylehickinson** [comment]
@Brandon-T Nah that's how it was spec'd out its fine. We chatted about it with @karenkliu [in Slack](https://bravesoftware.slack.com/archives/C06UXF3KJ/p1570824061023800) and we are likely going to replace the leaving "0" with something that makes it more obvious the user should interact with the ad above

That mixed with #1703 should make that a bit better

**Comment by Brandon-T** [comment]
Ok, for now, I'll leave it assigned to Karen and when it gets updated, I'll reassign it to myself if no one takes it or we can just auto-assign it to me.

**Comment by kylehickinson** [comment]
Closed in favour of #1746
