### ISSUE TITLE
Remove Rewards ToS checkbox slide in onboarding

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-ios#1695]
## Description 
Currently, there is an additional step in the onboarding flow to check the Rewards Terms of Service checkbox:
![ios 4](https://user-images.githubusercontent.com/2388823/66870445-55f73100-ef56-11e9-84ea-57189de35a12.png)

Remove the checkbox slide and add "By turning on Rewards, you agree to the Terms of Service." to the Rewards slide.

## Design
![ios 3](https://user-images.githubusercontent.com/2388823/66870469-60b1c600-ef56-11e9-876d-d47df89d45ed.png)

### New user, In ad region
Show search engine selection, Brave Shields explanation, Brave Rewards, and ad onboarding.

![user flow - ios onboarding ads available](https://user-images.githubusercontent.com/2388823/66870504-6effe200-ef56-11e9-93b7-95e9e634d6ff.png)

### New user, Out of ad region
Show search engine selection, Brave Shields explanation, and Brave Rewards.

![user flow - ios onboarding ads unavailable](https://user-images.githubusercontent.com/2388823/66870634-bc7c4f00-ef56-11e9-970c-28450ddc8805.png)

![ios ads unavailable](https://user-images.githubusercontent.com/2388823/66870642-bf773f80-ef56-11e9-9148-e2964b6c14bd.png)

### Existing user, in ad region
Show Brave Rewards and ad onboarding.
![user flow - ios onboarding existing user in ad region](https://user-images.githubusercontent.com/2388823/66870815-1e3cb900-ef57-11e9-8ea2-c2b6c799e704.png)

### Existing user, out of ad region
Show Brave Rewards.
![user flow - ios onboarding existing user out of ad region](https://user-images.githubusercontent.com/2388823/66870869-3b718780-ef57-11e9-8770-126a09fe3b5f.png)

![ios ads unavailable](https://user-images.githubusercontent.com/2388823/66870642-bf773f80-ef56-11e9-9148-e2964b6c14bd.png)

### (Future case) Existing user, BR on, ad becomes available in the region
Show ad onboarding.

![user flow - ios onboarding BR on notify ads](https://user-images.githubusercontent.com/2388823/66877619-fc4d3180-ef6a-11e9-9ae9-fde85b2fd938.png)

![ios br on](https://user-images.githubusercontent.com/2388823/66877615-f8211400-ef6a-11e9-9707-6b17c059941b.png)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.21.22)
* New User 
  * Verified full onboarding flow is shown on clean install of `1.13`
* Existing user in ads supported region who did onboarding in `1.12.1`
  * Verified only rewards onboarding is shown on upgrade from `1.12.1` to `1.13`
* Existing user in ads supported region who skipped onboarding in `1.12.1`
  * Verified only rewards onboarding is shown on upgrade from `1.12.1` to `1.13`
------
Verification passed on iPhone 7+ with iOS 13.1 running 1.13(19.10.21.22)
* New User 
  * Verified full onboarding flow is shown on clean install of `1.13`
* Existing user in ads supported region who did onboarding in `1.12.1`
  * Verified only rewards onboarding is shown on upgrade from `1.12.1` to `1.13`
* Existing user in ads supported region who skipped onboarding in `1.12.1`
  * Verified only rewards onboarding is shown on upgrade from `1.12.1` to `1.13`
--------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.21.22)
* New User 
  * Verified full onboarding flow is shown on clean install of `1.13`
* Existing user in ads supported region who did onboarding in `1.12.1`
  * Verified only rewards onboarding is shown on upgrade from `1.12.1` to `1.13`
* Existing user in ads supported region who skipped onboarding in `1.12.1`
  * Verified only rewards onboarding is shown on upgrade from `1.12.1` to `1.13`
-------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.21.22)
* New User 
  * Verified full onboarding flow is shown on clean install of `1.13`
* Existing user in ads supported region who did onboarding in `1.12.1`
  * Verified only rewards onboarding is shown on upgrade from `1.12.1` to `1.13`
* Existing user in ads supported region who skipped onboarding in `1.12.1`
  * Verified only rewards onboarding is shown on upgrade from `1.12.1` to `1.13`
--------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.21.22)
* New User 
  * Verified full onboarding flow is shown on clean install of `1.13`
* Existing user in ads supported region who did onboarding in `1.12.1`
  * Verified only rewards onboarding is shown on upgrade from `1.12.1` to `1.13`
* Existing user in ads supported region who skipped onboarding in `1.12.1`
  * Verified only rewards onboarding is shown on upgrade from `1.12.1` to `1.13`
---------
Note: The following scenario failed on devices
* Existing user in non-ads supported region upgrading from `1.12.1` to `1.13` isn't shown rewards onboarding flow. Logged #1757 for missing onboarding flow for non-ads region.
