### ISSUE TITLE
Update Wallet copy

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1697]
### Description: 
We have old outdated copy on the below screen

Please update the copy on this screen to

TBD

![IMG_8C6FB25A225B-1.jpeg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/7a507d90-4476-45d0-8d5b-0278b82b0a8c)

**Comment by anthonypkeane** [comment]
Please change the text to **New** as detailed in the image


![image (3)](https://user-images.githubusercontent.com/7606853/67043381-cc269f80-f0de-11e9-98e4-7b1ddb0129fc.png)

**Comment by srirambv** [comment]
* Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.18.15)
![image](https://user-images.githubusercontent.com/17010094/67243113-dfaa7100-f424-11e9-9bc1-e2eab243b054.png)

* Verification passed on iPhone 7+ with iOS 13.1 running 1.13(19.10.18.15)
![image](https://user-images.githubusercontent.com/17010094/67243135-ea650600-f424-11e9-8b87-99bb5818f081.png)

* Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.18.15)
![image](https://user-images.githubusercontent.com/17010094/67243105-dae5bd00-f424-11e9-951e-c217284ffb4c.png)

* Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.18.15)
![image](https://user-images.githubusercontent.com/17010094/67243124-e507bb80-f424-11e9-8430-785edad0c9af.png)

* Verification passed on iPad Prowith iOS 12.4 running 1.13(19.10.18.15)
![image](https://user-images.githubusercontent.com/17010094/67243095-d5887280-f424-11e9-922e-11fd3fb3ea39.png)
