### ISSUE TITLE
Setup Japanese translations for Rewards UI

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1698]
1. Translations from Brave Rewards must be moved to Brave iOS project in transifex
2. Push new strings, translate and pull latest translations

**Comment by iccub** [comment]
Related ticket https://github.com/brave/brave-ios/issues/1648

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.11.4.20)
* Verified rewards UI/sample ad/grant message is translated to Japanese
![XR_Japanese](https://user-images.githubusercontent.com/17010094/68241086-0d261b80-ffdc-11e9-9eb3-b8bd0d4d0209.gif)

--------
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.11.4.20)
* Verified rewards UI/sample ad/grant message is translated to Japanese
![7_Japan](https://user-images.githubusercontent.com/17010094/68241094-10b9a280-ffdc-11e9-8f98-c419bfce3b05.gif)

--------
Verification passed on ipad Pro with iOS 13.2 running 1.13(19.11.4.20)
* Verified rewards UI/sample ad/grant message is translated to Japanese
![iPad_Japan](https://user-images.githubusercontent.com/17010094/68241103-14e5c000-ffdc-11e9-9d4b-f56a2fe20ae4.gif)

--------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.11.4.20)
* Verified rewards UI/sample ad/grant message is translated to Japanese
--------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.11.4.20)
* Verified rewards UI/sample ad/grant message is translated to Japanese
