### ISSUE TITLE
Joining during rewards onboarding sometimes doesn't actually join

### ISSUE THREAD

**Issue by bbondy** [brave/brave-ios#1700]
### Description: 
The first time I got the rewards onboarding I was not a new user, but a new user to rewards.  I joined rewards and accepted the terms, but I still had to later join from the BAT icon in the URL bar.

### Steps to Reproduce 
  1. Install an old version of Brave iOS
  2. Upgrade to the latest version with rewards onboarding
  3. Go through the onboarding, agree to the terms, join rewards, see the test ad
  4. Click on the BAT icon

**Actual result:** 

It shows join rewards

**Expected result:**

I should already be joined

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

I tried to uninstall and install fresh, and I did not reproduce that time.
I wonder if it has to do with an upgrade case where onboarding was already complete but rewards onboarding was new.

**Brave Version:** 
Brave Beta 1.13 (19.10.9.22) via TestFlight

**Device details:** 
iPhone 11 Pro

**Website problems only:**
- did you check with Brave Shields down? n/a
- did you check in Safari/Firefox (WkWebView-based browsers)? n/a

### Additional Information

none.

cc @kylehickinson

**Comment by srirambv** [comment]
Tried on iPhone Xr with 1.12.1 -> 1.13 upgrade step 4 showed wallet details and didn't ask to join rewards again

**Comment by Brandon-T** [comment]
Having a hard time reproducing this one :(
