### ISSUE TITLE
Verified publisher on dark theme needs more contrast

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1708]
### Description: 
Verified publisher on dark theme needs more contrast

**Actual result:** 
Looks more blurred and blended in the dark mode on device. Screenshot doesn't do justice 
![image](https://user-images.githubusercontent.com/17010094/66955699-e86c0300-f030-11e9-9d8b-14c54b784ff6.png)
on iPad
![image](https://user-images.githubusercontent.com/17010094/66955835-35e87000-f031-11e9-92c7-6dd1cf7dac05.png)

**Expected result:**
Have a more prominent contrast for the verified icon on dark theme

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13

**Device details:** 
Both iPhone and iPad

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc: @jamesmudgett @jenn-rhim

**Comment by kylehickinson** [comment]
@jamesmudgett Can we get a verified icon that includes a white checkmark instead of cut-out checkmark for the URL bar?

**Comment by jamesmudgett** [comment]
[Archive.zip](https://github.com/brave/brave-ios/files/3740275/Archive.zip)

**Comment by srirambv** [comment]
* Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.18.15)
![image](https://user-images.githubusercontent.com/17010094/67237788-f1d2e200-f419-11e9-8dce-df9df2a7c649.png)

* Verification passed on iPhone 7+ with iOS 13.1 running 1.13(19.10.18.15)
![image](https://user-images.githubusercontent.com/17010094/67237829-08793900-f41a-11e9-80bf-e2f1b08875ed.png)

* Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.18.15)
![image](https://user-images.githubusercontent.com/17010094/67238329-f9df5180-f41a-11e9-91e1-9174780562c5.png)

* Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.18.15)
![image](https://user-images.githubusercontent.com/17010094/67238344-ffd53280-f41a-11e9-85d7-f6bb5a20a400.png)

* Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.18.15)
![image](https://user-images.githubusercontent.com/17010094/67238317-f51a9d80-f41a-11e9-878d-afeb54f025e4.png)
