### ISSUE TITLE
Disable contribution to non-verified pubs/videos isn't working

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1709]
### Description: 
Disable contribution to non-verified pubs/videos isn't working

### Steps to Reproduce 
  1. Enable rewards 
  2. Add a bunch of non-verified/verified pubs to ac list
  3. Add a bunch of non-verified/verified YT pubs to ac list
  4. Disable `Allow contribution to non-verified pubs` from advance settings under auto-contribute
  5. Go back to ac list, all non-verified sites are still listed in ac 
  ~6. Disable `Allow contribution to videos` from advance settings under auto-contribute~
  ~7. Go back to ac list, all videos pubs are still listed in ac list~
6-7 is working as expected

**Actual result:** 
Disable contribution to non-verified pubs/videos isn't working

**Expected result:**
Disabling each toogle should remove specific sites from ac list, re-enabling should bring the pubs back to the ac list. Should only be lost if ac goes through when its disabled 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.10.16.18)

**Device details:** 
iPhone Xr

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
I'm not sure if this is correct behaviour. Not sure if setting those off are supposed to stop unverified publishers from entering the users AC table or if they're just supposed to stop them from being used during reconciling (@NejcZdovc maybe you can verify, and if not anything additional we're supposed to do)

We are setting the native ledger value correctly here: https://github.com/brave/brave-ios/blob/2e81820e65b9e1aea2538b1fa4d9b3a3deb5c75c/BraveRewardsUI/Settings/Auto-Contribute/Settings/AutoContributeSettingsViewController.swift#L83

**Comment by NejcZdovc** [comment]
4-5 should work like you said, where 6-7 will not exclude them from the table.

**Comment by kylehickinson** [comment]
@srirambv Also, enabling these do not remove already added entries

**Comment by srirambv** [comment]
yeah 6-7 is working as expected. But 4-5 is still a bug with related to desktop. On desktop the moment you disable the setting, every site/pub which is not verified is removed from the list. Enabling it brings back them to the list. I've updated the steps

**Comment by kylehickinson** [comment]
If they come back then desktop is not actually deleting them from the table... maybe they are just hiding them? cc @NejcZdovc

**Comment by NejcZdovc** [comment]
@kylehickinson yes this toggle is just a filter to show/hide we don't delete any data

**Comment by kylehickinson** [comment]
Okay great, we can replicate this filter then in the AC table same as desktop then

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.11.4.14)
* Verified turning off `Allow contribution to non-verified publisher` filters out the verified from the existing list
* Verified turning off `Allow contribution to videos` doesn't add new videos to ac list
------------
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.11.4.14)
* Verified turning off `Allow contribution to non-verified publisher` filters out the verified from the existing list
* Verified turning off `Allow contribution to videos` doesn't add new videos to ac list
------------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.11.4.14)
* Verified turning off `Allow contribution to non-verified publisher` filters out the verified from the existing list
* Verified turning off `Allow contribution to videos` doesn't add new videos to ac list
------------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.11.4.14)
* Verified turning off `Allow contribution to non-verified publisher` filters out the verified from the existing list
* Verified turning off `Allow contribution to videos` doesn't add new videos to ac list
------------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.11.4.14)
* Verified turning off `Allow contribution to non-verified publisher` filters out the verified from the existing list
* Verified turning off `Allow contribution to videos` doesn't add new videos to ac list
------------
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.11.4.14)
* Verified turning off `Allow contribution to non-verified publisher` filters out the verified from the existing list
* Verified turning off `Allow contribution to videos` doesn't add new videos to ac list
