### ISSUE TITLE
Last pass glitch on account.google.com

### ISSUE THREAD

**Issue by iliketofu2** [brave/brave-ios#171]
### Description: 
When visiting the accounts page, when I choose to login and tap last pass from the bar above the text, everything is fine but on the next page it doesn't fill in the password. Quite annoying.

### Steps to Reproduce 
  1. Enable last pass 
  2. Go to the Google accounts page
  3. Login via last pass 
4. Go to the next page 

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
When I do the above 

**Brave Version:** 
Latest version from the app store

**Device details:** 
IPhone 6+ iOS 11.4.1

**Website problems only:**
- did you check with Brave Shields down? No
- did you check in Safari/Firefox Yeah I did, it worked (in safari)
(WkWebView-based browsers)?

**Comment by iliketofu2** [comment]
It's not just Google, it does it on other sites too

**Comment by cndouglas** [comment]
@iliketofu2 I cross-posted this at brave/browser-ios#1714 (the old repository for the current version). This repository is for the new version of Brave that has not been released yet.

**Comment by iliketofu2** [comment]
Oh, thanks!

**Comment by jhreis** [comment]
Thanks @iliketofu2 for submitting and for @Liunkae for porting to the current App Store repo. Will will try to make the repo more clear.

**Comment by jhreis** [comment]
Closing, as we do not even have lastpass support built on this project, so I know it was intended for the other repo. Feel free to continue the conversation over there (https://github.com/brave/browser-ios/issues/1714)
