### ISSUE TITLE
Adds support for media publisher favicon fetching

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1710]
### Description: 
Github verified accounts don't show user profile icon 

### Steps to Reproduce 
  1. Enable rewards
  2. Open a github verified account
  3. Open rewards panel, uses GitHub icon instead of user profile icon

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/66971109-e9fff000-f05d-11e9-90ca-cf741f933f1a.png)

**Expected result:**
Similar to desktop 
![image](https://user-images.githubusercontent.com/17010094/66971091-dfddf180-f05d-11e9-93a6-c5c2cbdf5246.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.10.16.18)

**Device details:** 
iPhone Xr and iPad 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
Issue source needs to be identified.

**Comment by kylehickinson** [comment]
Investigation: `fetchFavIcon:faviconKey:callback` not implemented correctly in `BATBraveLedger.mm:1848`. `url` is the favicon, `favicon_key` is the key for cache

**Comment by kylehickinson** [comment]
Closed as this feature is no longer supported in new Rewards on Brave iOS
