### ISSUE TITLE
Social media icons on tip panel are not clickable

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1712]
### Description: 
Social media icons on tip panel are not clickable

### Steps to Reproduce 
  1. Enable rewards
  2. Visit any verified publisher page and open the tips panel
  3. YT/Twitter icons on the tip panel isn't clickable

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/66972749-955f7380-f063-11e9-940b-fb28eb273a36.png)

**Expected result:**
Clicking the icons should load the respective landing page for that publisher similar to desktop 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.10.16.18)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
@srirambv Good catch, I didn't even realize these were supposed to be buttons 😂

**Comment by srirambv** [comment]
@anthonypkeane  these buttons are not visible on Android not sure if Mobile is supposed to have these buttons show up or not?

**Comment by kylehickinson** [comment]
To be done at a later date, will open a new ticket removing them until then

**Comment by srirambv** [comment]
@kylehickinson can we close this in favour of #2147?

**Comment by kylehickinson** [comment]
@srirambv No we still want to keep this one, #2147 is just to track the interim solution of hiding the social icons since they didn't work properly.

**Comment by kylehickinson** [comment]
Closed as this feature is no longer supported in new Rewards on Brave iOS
