### ISSUE TITLE
Brave on iOS won’t display store.google.com

### ISSUE THREAD

**Issue by thommesborg** [brave/brave-ios#1715]
Please visit http://github.com/brave/brave-ios/issues/ 

…“ Description

as of today I realized that Brave Mobile on iOS won’t display store.google.com correctly. 80% of all imaginary on this site won’t load.
Steps to Reproduce

Use Version 1.12.1 (19.09.20.23)
Goto store.google.com
See no images
Actual result:

Expected result:

A completely loaded and displayed site.

Reproduces how often:

Always. Also after a reset of Brave with all data cleared.
…“

I’ve described everything under that link. I’m sorry about not knowing 'the right forum‘ bevor I wrote down all details. Please have a look at the link. 

The is no change if I disable all shields. 

The issue is reproducible on iOS, iPadOS and Android and only Brave is affected. Changing networks won’t change anything with this issue. Resetting Brave also won’t change anything.

**Comment by thommesborg** [comment]
Here is an additional screenshot from the empty Google Store page.  
![Bildschirmfoto 2019-10-18 um 06 45 29](https://user-images.githubusercontent.com/40795115/67070339-12800b00-f180-11e9-84e8-289e071934cf.png)

**Comment by srirambv** [comment]
No issues here when fingerprint is disabled
![image](https://user-images.githubusercontent.com/17010094/67097646-89b99d00-f188-11e9-8ffc-492c8494739f.png)
I do see the problem occur when I enable fingerprint
![image](https://user-images.githubusercontent.com/17010094/67097657-93db9b80-f188-11e9-86eb-271085fb2f84.png)

Can you take a screenshot of your shields settings on the page similar to the one shown here

**Comment by thommesborg** [comment]
Hi again, I tried it with disabled shields but that didn’t make a change. I didn’t imagine that it’s different to only disable fingerprinting. With fingerprinting disabled, the site loads almost correct, with all shields disabled, the site won’t load correctly. 
It looks like this: 
![AA291CF5-4DB0-4C2A-A8DE-49EAEBC3E4D5](https://user-images.githubusercontent.com/40795115/67105557-3e73ae80-f1c9-11e9-8caf-b83b80d065be.png)

**Comment by srirambv** [comment]
Can you try clearing browser cache once and check. I am somehow not able to reproduce it

**Comment by thommesborg** [comment]
I did that before. On iOS it’s not as easy as on Android to reset an app completely. So, I deleted and reinstalled Brave. Same result. All shields disabled and that site won’t load correct, only fingerprinting disabled and the site loads like you’ve shown with your screenie.

**Comment by thommesborg** [comment]
Additional information: I’m able to repro this on my iPad Pro (2017) that runs iPadOS.
