### ISSUE TITLE
Onboarding Terms and conditions web view cannot be exit on iOS 12

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1720]
### Description: 

When you click the terms and conditions button while onboarding rewards on an iOS 12 device the bar which allows you to close the web view does not appear

https://bravesoftware.slack.com/archives/C06UXF3KJ/p1570824862027700

**Device details:** Tested and not working iOS 12 on an iPhone 7

**Comment by kylehickinson** [comment]
I believe at the time I confirmed you can reproduce this bug on an iOS 12 simulator as well

**Comment by srirambv** [comment]
* Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.21.22). Also verified on iPhone 7+ which got upgraded to iOS 13.1 and works fine on that as well
---------------------
* Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.31.19)
