### ISSUE TITLE
New tab strip retains dark/white theme when quick mode toggled via control center

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1721]
### Description: 
New tab strip retains dark/white theme when quick mode toggled via control center

### Steps to Reproduce 
  1. Set device theme to dark/light
  2. Set browser theme to automatic
  3. Quick toggle between dark/light mode via control center
  4. New tab strip retains dark/light theme based on what device theme is set
  5. Open tab tray and switch back to tabs, resets the theme   

**Actual result:** 
Dark tab strip on iPad
![image](https://user-images.githubusercontent.com/17010094/67027702-0a6c9080-f0d8-11e9-8fb8-b5af46aa31a4.png)

White tab strip on iPhone
![image](https://user-images.githubusercontent.com/17010094/67027715-148e8f00-f0d8-11e9-8783-cae240a7eb7c.png)

[Video record of the issue](https://github.com/brave/brave-ios/files/3740303/theme.zip)

**Expected result:**
Theme should adapt to change automatically

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
All

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by hennrynusasatria** [comment]
Hi All,

This bug has been reported since last year, but it is still not fixed until today (Brave iOS Version 1.19), when do you plan to fix this bug?

Thank you.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(21.5.25.18)
- Verified steps from issue description
- Verified theme updates correctly for tab strip when theme is changed via control centre
---------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.26(21.5.25.18)
- Verified steps from issue description
- Verified theme updates correctly for tab strip when theme is changed via control centre
--------
Verification passed on iPad Pro with iOS 14.5.1 running 1.26(21.5.25.18)
- Verified steps from issue description
- Verified theme updates correctly for tab strip when theme is changed via control centre
