### ISSUE TITLE
Quick theme toggle doesn't update theme for download/history/bookmarks

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1722]
### Description: 
Found while testing #1553. With Downloads/Bookmarks/History page open if you toggle theme from control center it doesn't update the theme for the page but updates the entire browser theme 

### Steps to Reproduce 
  1. Set browser to dark theme
  2. Open download/bookmarks/history
  3. Change theme via control center with downloads/bookmarks/history page opened
  4. Page remains on previous theme only updates when you close and reopen it

**Actual result:** 
Quick theme toggle doesn't update theme for download/history/bookmarks

**Expected result:**
Should update theme accordingly

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.10.16.18)

**Device details:** 
Both iPhone and iPad with iOS 13

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by hennrynusasatria** [comment]
Is this issue also fixed through #2734 ?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(21.5.25.18)
- Verified steps from issue description
- Verified theme updates correctly for history/bookmarks/download tabs open when theme is changed via control centre
---------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.26(21.5.25.18)
- Verified steps from issue description
- Verified theme updates correctly for history/bookmarks/download tabs open when theme is changed via control centre
--------
Verification passed on iPad Pro with iOS 14.5.1 running 1.26(21.5.25.18)
- Verified steps from issue description
- Verified theme updates correctly for history/bookmarks/download tabs open when theme is changed via control centre
