### ISSUE TITLE
Bookmarklet on newtab shows title as localhost:6571

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1724]
### Description: 
Found while testing #1119 , adding a bookmarklet and trying to load it on newtab shows title as https://localhost:6571

### Steps to Reproduce 
  1. Add a bookmarklet that has a js alert 
  2. Open a new tab
  3. Open the bookmarklet, alert has title https://localhost:6571

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/67043291-c12c3900-f0f7-11e9-9f0e-81be4ba4ea73.png)

**Expected result:**
Should say New Tab

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.10.16.18)

**Device details:** 
ALl

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Brandon-T** [comment]
I believe ALL new tabs have this title before bookmarklets. The alert is showing the `window.title` attribute.

I will see if there is a way to change it for blank tabs.

**Comment by iccub** [comment]
we do not show new tab page using a local webserver anymore
