### ISSUE TITLE
Crash when enabling search suggestions

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1725]
### Description: 
There is a crash when enabling search suggestion

Internal Chat: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1571345618120200?thread_ts=1571345550.120000&cid=C06UXF3KJ

### Steps to Reproduce 
  1.  Turn off search suggestion
  2. Search for something
  3. Turn on search suggestion
  4. search for something and the app will crash 

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easy

**Brave Version:** 
1.13 (19.10.16.18)

**Device details:** 
13

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone Xr with iOS 13.2 running 1.13(19.10.18.15)
* Verified turning off search suggestions and performing a search doesn't crash
* Verified turning on search suggestions and performing a search doesn't crash

Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.10.18.15)
* Verified turning off search suggestions and performing a search doesn't crash
* Verified turning on search suggestions and performing a search doesn't crash

Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.18.15)
* Verified turning off search suggestions and performing a search doesn't crash
* Verified turning on search suggestions and performing a search doesn't crash

Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.18.15)
* Verified turning off search suggestions and performing a search doesn't crash
* Verified turning on search suggestions and performing a search doesn't crash

Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.18.15)
* Verified turning off search suggestions and performing a search doesn't crash
* Verified turning on search suggestions and performing a search doesn't crash
