### ISSUE TITLE
Re-Enable the Auto-Play Toggle

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1738]
Should be re-enabled by reverting https://github.com/brave/brave-ios/pull/1737 post 1.13 release for QA to properly test

Refs: https://github.com/brave/brave-ios/issues/1129, https://github.com/brave/brave-ios/pull/1735

**Comment by kylehickinson** [comment]
@jamesmudgett Can you please choose icon to use? Desktop uses the following: 
<img width="123" alt="image" src="https://user-images.githubusercontent.com/529104/123204962-100ea200-d487-11eb-8ce4-de545ded067d.png">

We could use this icon from the Icons Figma: 
<img width="45" alt="image" src="https://user-images.githubusercontent.com/529104/123205123-52d07a00-d487-11eb-9344-0c9826453aae.png">

But fill it in instead of outline to match?

Otherwise perhaps one of the media icons

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.31(21.9.14.15)
- Verified setting is enabled by default on clean install
- Verified visiting this [link](https://www.msn.com/en-us/news/technology/the-new-iphone-13-and-13-mini-explained/vi-AAOs7gM) with setting disabled doesn't play the video when page is loaded
- Verified enabling the setting while on the page, reloads the page and starts playback
- Verified on upgrade setting is added and enabled by default 
-------
Verification passed on iPhone 7+ with iOS 14.8 running 1.31(21.9.14.15)
- Verified setting is enabled by default on clean install
- Verified visiting this [link](https://www.msn.com/en-us/news/technology/the-new-iphone-13-and-13-mini-explained/vi-AAOs7gM) with setting disabled doesn't play the video when page is loaded
- Verified enabling the setting while on the page, reloads the page and starts playback
- Verified on upgrade setting is added and enabled by default 
--------
Verification passed on iPad Pro with iOS 15 running 1.31(21.9.14.15)
- Verified setting is enabled by default on clean install
- Verified visiting this [link](https://www.msn.com/en-us/news/technology/the-new-iphone-13-and-13-mini-explained/vi-AAOs7gM) with setting disabled doesn't play the video when page is loaded
- Verified enabling the setting while on the page, reloads the page and starts playback
- Verified on upgrade setting is added and enabled by default

**Comment by Jip-Hop** [comment]
Has this feature been removed from the app? I'm on version 1.43 (22.9.9.14) on an iPhone SE 2022 and my settings screen doesn't have the [Enable Auto-Play toggle](https://github.com/brave/brave-ios/pull/4090). My settings look like this:

![IMG_8168](https://user-images.githubusercontent.com/2871973/195978626-8205137e-e894-4e60-95c8-df241bdb7de8.PNG)

I don't see anything mentioned in the [changelog](https://github.com/brave/brave-ios/blob/development/CHANGELOG.md) regarding the removal of the autoplay toggle.

**Comment by raayu83** [comment]
I'm desperately look for an iOS Browser that allows enabling Autoplay of Audio for a flashcard application I'm using.
Seems there is currently no single Browser that supports it.
