### ISSUE TITLE
Changing theme during onboarding doesn't change the theme for sample ad

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1739]
### Description: 
Changing theme during onboarding doesn't change the theme for sample ad

### Steps to Reproduce 
  1. Clean install 1.13
  2. Launch browser and start onboarding 
  3. Toggle device theme via control center, sample ad doesn't get the updated theme

**Actual result:** 
![darkads](https://user-images.githubusercontent.com/17010094/67130083-4eda5800-f1ce-11e9-91b9-9fb656979bd7.gif)

**Expected result:**
Should update theme automatically

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.10.18.15)

**Device details:** 
iPhone Xr and iPhone 7+ on iOS 13.2

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Cant reproduce it on iPad

**Comment by kjozwiak** [comment]
Looks like I can still reproduce this using `1.14 (19.11.26.21)` on the following platforms:

* `iPhone 6s` running `iOS 13.2.2` using `1.14 (19.11.26.21)` - **Reproduced**

Example of the issue on `1.14 (19.11.26.21)` (after enabling `light` mode via the control centre):

![IMG_0031](https://user-images.githubusercontent.com/2602313/69690021-7f989180-1098-11ea-95e5-5c85ec51060d.PNG)

@srirambv mind checking on your iPhone and see if you can reproduce as well?

**Comment by srirambv** [comment]
Seems to be working fine for me on iPhone 7+ and iPhone XR. Here's a recording from iPhone 7+
![darklight_notification](https://user-images.githubusercontent.com/17010094/69726300-3a9f4a00-10ee-11ea-9269-0591c485b6a2.gif)

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.27.14)
* Verified changing theme via control center updates theme for sample ad accordingly 
![ipadtheme](https://user-images.githubusercontent.com/17010094/69737622-b3100600-1102-11ea-89b9-b5eb38793647.gif)

**Comment by srirambv** [comment]
@kjozwiak  could you check on the latest build on your device and then we can add the qa pass labels

**Comment by kjozwiak** [comment]
@srirambv I can still reproduce this on my `iPhone 6s` running `iOS 13.2.2` using `1.14 (19.11.27.14)`.

Example of the issue still happening: https://youtu.be/xKw4DV2NidY

**Comment by srirambv** [comment]
There is a slight change in the steps which i think is a different issue. You are changing the theme before enabling rewards which is why it not updating the ad notification theme. Should add a new issue for that and mark it for 1.15

**Comment by kjozwiak** [comment]
As @srirambv mentioned, the STR that I used are a bit different compared to this issue. I was disabling `Dark` mode before opting into `Rewards` and seeing the ad notification as this issue was related to disabling `Dark` mode after you've opted into `Rewards` and received the ad notification.

Created https://github.com/brave/brave-ios/issues/2044 to address the issue that I was seeing and labelling this as `QA Pass - iPhone`
