### ISSUE TITLE
Add Funds text on iOS needs fixing

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-ios#1744]
![image](https://user-images.githubusercontent.com/35932307/67229292-e074e000-f3ef-11e9-9a9b-e1e443683a62.png)

Context: Currently iOS has no way to add funds as the add-funds functionality is under lockdown until User wallets are introduced.

Issue: When a user runs out of funds, text image shows as "Not enough tokens. Please add funds"

Resolution: "Not enough BAT to contribute. Please turn on Ads to earn more funds" 
This is a temporary fix.

cc @jamesmudgett @jenn-rhim @mattmcalister @anthonypkeane

**Comment by srirambv** [comment]
@mandar-brave what message should be put in for regions that don't have ads?

**Comment by mandar-brave** [comment]
Good point @srirambv; i will edit the string above. Stay tuned!

**Comment by mattmcalister** [comment]
This doesn't work if Ads is already turned on: "Not enough BAT to contribute. Please turn on Ads to earn more funds"

Alternative: "Not enough tokens."

Keep it short and sweet.

**Comment by kylehickinson** [comment]
@mattmcalister What about in JP? I assume we will want it to say "Not enough points" instead?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.25.14)
* Verified for both ads supported and not supported region text only shows `Not enough tokens`
![image](https://user-images.githubusercontent.com/17010094/67707065-33bad580-f990-11e9-930b-b7f7e5627f8f.png)
* Verified for Japanese locale shows `Not enough points`
![image](https://user-images.githubusercontent.com/17010094/67707086-39b0b680-f990-11e9-843b-f8bbd1f8fda4.png)
--------------
Verification passed on iPhone 7+ with iOS 13.1 running 1.13(19.10.25.14)
* Verified for both ads supported and not supported region text only shows `Not enough tokens`
![image](https://user-images.githubusercontent.com/17010094/67707115-4b925980-f990-11e9-9999-137ef1691a8e.png)
* Verified for Japanese locale shows `Not enough points`
![image](https://user-images.githubusercontent.com/17010094/67707132-551bc180-f990-11e9-97db-b9271aff1ca8.png)
--------------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.25.14)
* Verified for both ads supported and not supported region text only shows `Not enough tokens`
![image](https://user-images.githubusercontent.com/17010094/67707145-5c42cf80-f990-11e9-84e7-4d54f20f6560.png)
* Verified for Japanese locale shows `Not enough points`
![image](https://user-images.githubusercontent.com/17010094/67707161-61a01a00-f990-11e9-9368-81774e5988fb.png)
--------------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.25.14)
* Verified for both ads supported and not supported region text only shows `Not enough tokens`
![image](https://user-images.githubusercontent.com/17010094/67707181-69f85500-f990-11e9-8986-516401c0d4c8.png)
* Verified for Japanese locale shows `Not enough points`
![image](https://user-images.githubusercontent.com/17010094/67707193-6fee3600-f990-11e9-94ca-d9a8b5b59ff6.png)
--------------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.25.14)
* Verified for both ads supported and not supported region text only shows `Not enough tokens`
![image](https://user-images.githubusercontent.com/17010094/67707312-a0ce6b00-f990-11e9-8bed-40d76987b2b7.png)
* Verified for Japanese locale shows `Not enough points`
![image](https://user-images.githubusercontent.com/17010094/67707225-7bd9f800-f990-11e9-847b-5ed6d1a809a5.png)
--------------
