### ISSUE TITLE
Rewards notification design tweaks

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#1745]
![E957F969-0E1E-43CD-A57A-F70D7D744587](https://user-images.githubusercontent.com/318119/67229642-59306800-f401-11e9-8bcb-dd10d654d812.png)
 Current design seen above. Need to reduce the App name (BRAVE REWRDS) font to regular and should be slight alpha. Can try .6 or .5. Notification title and message should both be same color. To match iOS system notification style.

**Comment by jamesmudgett** [comment]
![333D9552-EA80-4F36-BC89-ABBA3EF1BF10](https://user-images.githubusercontent.com/318119/67230099-423e4580-f402-11e9-905e-a59cd7d476de.jpeg)
![4F5BB4BC-2B44-46EF-9BDC-732A4C89F8D1](https://user-images.githubusercontent.com/318119/67230100-423e4580-f402-11e9-9561-582b42f2e035.jpeg)

**Comment by jamesmudgett** [comment]
Attached system notifications for reference

**Comment by jamesmudgett** [comment]
Also should follow zoom settings
![5AAA9E9A-3CE1-4AAF-A6C8-7A8DAD0CC3F6](https://user-images.githubusercontent.com/318119/67233434-d14e5c00-f408-11e9-8969-67862f267e89.png)

**Comment by kylehickinson** [comment]
@jamesmudgett Not sure what you mean about zoom settings

**Comment by anthonypkeane** [comment]
> Also should follow zoom settings


Zoomed text (accessibility option) mode is not in scope for V1.0

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.30.14)
* Verified ad shows is as per spec in #1756 
![image](https://user-images.githubusercontent.com/17010094/67897086-1161bd00-fb34-11e9-92e2-78f252f3cda3.png)

----------
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.10.30.14)
* Verified ad shows is as per spec in #1756 
![image](https://user-images.githubusercontent.com/17010094/67897177-381ff380-fb34-11e9-87f8-9b98a78f3f87.png)

----------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.30.14)
* Verified ad shows is as per spec in #1756 
![image](https://user-images.githubusercontent.com/17010094/67897185-3e15d480-fb34-11e9-8dbb-a31061132288.png)

----------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.30.14)
* Verified ad shows is as per spec in #1756 
![image](https://user-images.githubusercontent.com/17010094/67897106-1d4d7f00-fb34-11e9-93d8-f433b5c963f6.png)

----------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.30.14)
* Verified ad shows is as per spec in #1756 
![image](https://user-images.githubusercontent.com/17010094/67897193-4241f200-fb34-11e9-8cf8-d5733990e592.png)
