### ISSUE TITLE
Update Onboarding "My First Ad" screen to show start browsing after 1s delay

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1746]
### Description: 
Joining rewards triggers sample ad notification and then waits for 8secs with the counter at 0. It gives a feeling that the onboarding is stuck. We should consider reducing the wait time before showing the `Start Browsing` button. 

### Steps to Reproduce 
  1. Go through onboarding flow

**Actual result:** 
![FilefromiOS](https://user-images.githubusercontent.com/17010094/66868951-5d293980-ef6c-11e9-91f4-32503f38a329.gif)

**Expected result:**
No UI stall making it look like its stuck without visual feedback

## Affected User Flows

Note the final flow "1s delay". This makes the final screen display after a 1s delay regardless of the "My First Ad" auto-dismissing after 3s

### New user, In ad region

![user flow - ios onboarding ads available](https://user-images.githubusercontent.com/2388823/66870504-6effe200-ef56-11e9-93b7-95e9e634d6ff.png)

### Existing user, in ad region

![user flow - ios onboarding existing user in ad region](https://user-images.githubusercontent.com/2388823/66870815-1e3cb900-ef57-11e9-8ea2-c2b6c799e704.png)

### (Future case) Existing user, BR on, ad becomes available in the region

![user flow - ios onboarding BR on notify ads](https://user-images.githubusercontent.com/2388823/66877619-fc4d3180-ef6a-11e9-9ae9-fde85b2fd938.png)

**Comment by LaurenWags** [comment]
Verification passed on iPad 5th Gen with iOS 12.4 running 1.13(19.10.30.14)
* Confirmed 1s delay for `Start Browsing` button in both New User in ad region and Existing User in ad region cases. Note - did encounter https://github.com/brave/brave-ios/issues/1839 while testing this.
------
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.30.21)
* Verified `Start browsing` button shows up after 1sec delay after showing sample ad
* Verified on both clean install and upgrade scenario
-------- 
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.10.30.21)
* Verified `Start browsing` button shows up after 1sec delay after showing sample ad
* Verified on both clean install and upgrade scenario
--------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.30.21)
* Verified `Start browsing` button shows up after 1sec delay after showing sample ad
* Verified on both clean install and upgrade scenario
--------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.30.21)
* Verified `Start browsing` button shows up after 1sec delay after showing sample ad
* Verified on both clean install and upgrade scenario
