### ISSUE TITLE
Show Red Dot on the BAT Icon

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1751]
### Description: 
All new rewards users (new brave users and existing brave users that install the Rewards and Ads build) should be shown a red dot on the BAT icon on first open

Regardless of what they do during onboarding, we want to show this red dot to help alert users to the menu behind the BAT icon

This red dot has no attached notification, and goes away after the panel is opened for the first time.

Android Red Dot
![Screenshot_20191021-163201.jpg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/eae12ee8-79b0-415a-9061-d539f366565a)
 
@alexwykoff or @mandar-brave to provide more details on this feature if I'm missing anything above.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.23.22)
* Clean Install
  * Verified skipping the onboarding still shows the red dot on rewards panel
  * Verified skipping rewards during onboarding still shows the red dot on rewards panel
  * Verified finishing onboarding still shows the red dot on rewards panel
* Upgrade from 1.12.1
   * Verified on upgrade, turn on rewards is shown, skipping it still shows the red dot on panel
   * Verified on upgrade, turn on rewards is shown, finishing it still shows the red dot on panel
![image](https://user-images.githubusercontent.com/17010094/67515372-83399280-f66c-11e9-9945-64b9b9643cc7.png)

-------------
Verification passed on iPhone 7+ with iOS 13.1 running 1.13(19.10.23.22)
* Clean Install
  * Verified skipping the onboarding still shows the red dot on rewards panel
  * Verified skipping rewards during onboarding still shows the red dot on rewards panel
  * Verified finishing onboarding still shows the red dot on rewards panel
* Upgrade from 1.12.1
   * Verified on upgrade, turn on rewards is shown, skipping it still shows the red dot on panel
   * Verified on upgrade, turn on rewards is shown, finishing it still shows the red dot on panel
![image](https://user-images.githubusercontent.com/17010094/67515125-0c9c9500-f66c-11e9-9c72-4aa4d525cefb.png)

-------------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.23.22)
* Clean Install
  * Verified skipping the onboarding still shows the red dot on rewards panel
  * Verified skipping rewards during onboarding still shows the red dot on rewards panel
  * Verified finishing onboarding still shows the red dot on rewards panel
* Upgrade from 1.12.1
   * Verified on upgrade, turn on rewards is shown, skipping it still shows the red dot on panel
   * Verified on upgrade, turn on rewards is shown, finishing it still shows the red dot on panel
![image](https://user-images.githubusercontent.com/17010094/67515147-17572a00-f66c-11e9-978d-e634d3e3bef6.png)
![image](https://user-images.githubusercontent.com/17010094/67515159-1b834780-f66c-11e9-9397-2edf9951d864.png)


-------------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.23.22)
* Clean Install
  * Verified skipping the onboarding still shows the red dot on rewards panel
  * Verified skipping rewards during onboarding still shows the red dot on rewards panel
  * Verified finishing onboarding still shows the red dot on rewards panel
* Upgrade from 1.12.1
   * Verified on upgrade, turn on rewards is shown, skipping it still shows the red dot on panel
   * Verified on upgrade, turn on rewards is shown, finishing it still shows the red dot on panel
![image](https://user-images.githubusercontent.com/17010094/67515112-06a6b400-f66c-11e9-894b-6ebdbebb688f.png)

-------------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.23.22)
* Clean Install
  * Verified skipping the onboarding still shows the red dot on rewards panel
  * Verified skipping rewards during onboarding still shows the red dot on rewards panel
  * Verified finishing onboarding still shows the red dot on rewards panel
* Upgrade from 1.12.1
   * Verified on upgrade, turn on rewards is shown, skipping it still shows the red dot on panel
   * Verified on upgrade, turn on rewards is shown, finishing it still shows the red dot on panel
![image](https://user-images.githubusercontent.com/17010094/67515265-51283080-f66c-11e9-8ce4-00d75ada4467.png)
![image](https://user-images.githubusercontent.com/17010094/67515278-55ece480-f66c-11e9-82fc-3fc1102fc689.png)


-------------
