### ISSUE TITLE
Missing text changes for JP region

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1765]
- "Grants" -> "Details" on wallet header
- "Your wallet" -> "Your balance" in wallet header
- "wallet balance" -> "balance" in tipping view

**Comment by anthonypkeane** [comment]
Text Update: 
On onboarding, for Japan, change tokens to points

**Comment by kylehickinson** [comment]
Auto-contribute wallet notification "BAT" → "BAT Points"

**Comment by kylehickinson** [comment]
Monthly payment AC/recurring tip screens: "BAT" → "BAT Points"

**Comment by srirambv** [comment]
Blocked on https://github.com/brave/brave-ios/issues/1656

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.11.4.14)
* Verified `Grants` is replaced with `View Details`
![image](https://user-images.githubusercontent.com/17010094/68143017-851e1400-fefe-11e9-89d1-b7ab05361228.png)
* Verified `Your wallet` is replaced with `Your balance`
![image](https://user-images.githubusercontent.com/17010094/68143006-7e8f9c80-fefe-11e9-987b-40d79a1cda99.png)
* Verified `Wallet balance` is replaced with `Balance`
![image](https://user-images.githubusercontent.com/17010094/68142990-79325200-fefe-11e9-95d9-72018534ac87.png)
----------------------
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.11.4.14)
* Verified `Grants` is replaced with `View Details`
* Verified `Your wallet` is replaced with `Your balance`
* Verified `Wallet balance` is replaced with `Balance`
----------------------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.11.4.14)
* Verified `Grants` is replaced with `View Details`
* Verified `Your wallet` is replaced with `Your balance`
* Verified `Wallet balance` is replaced with `Balance`
----------------------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.11.4.14)
* Verified `Grants` is replaced with `View Details`
![image](https://user-images.githubusercontent.com/17010094/68143945-86e8d700-ff00-11e9-89b7-f93ba72fb9df.png)
* Verified `Your wallet` is replaced with `Your balance`
![image](https://user-images.githubusercontent.com/17010094/68143935-82bcb980-ff00-11e9-9191-79f91922d5d1.png)
* Verified `Wallet balance` is replaced with `Balance`
![image](https://user-images.githubusercontent.com/17010094/68143917-7c2e4200-ff00-11e9-90c3-a4c29ef58a18.png)

----------------------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.11.4.14)
* Verified `Grants` is replaced with `View Details`
![image](https://user-images.githubusercontent.com/17010094/68143945-86e8d700-ff00-11e9-89b7-f93ba72fb9df.png)
* Verified `Your wallet` is replaced with `Your balance`
![image](https://user-images.githubusercontent.com/17010094/68143935-82bcb980-ff00-11e9-9191-79f91922d5d1.png)
* Verified `Wallet balance` is replaced with `Balance`
![image](https://user-images.githubusercontent.com/17010094/68143917-7c2e4200-ff00-11e9-90c3-a4c29ef58a18.png)
