### ISSUE TITLE
Internal Issue

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1772]
### Description: 
Link: https://github.com/brave/internal/issues/667

**Comment by iccub** [comment]
Closed via https://github.com/brave/brave-ios/pull/1780

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.31.15)
* Verified a new entry for `License` is shown at the bottom of settings
![image](https://user-images.githubusercontent.com/17010094/67980922-d45dff00-fbf5-11e9-960b-d69abd038248.png)
* Verified `License` list all the details as expected
![image](https://user-images.githubusercontent.com/17010094/67980932-d88a1c80-fbf5-11e9-99a7-e75f68f04ebd.png)

----------
 Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.10.31.15)
* Verified a new entry for `License` is shown at the bottom of settings
![image](https://user-images.githubusercontent.com/17010094/67980882-bdb7a800-fbf5-11e9-8647-ad1925c4b2b9.png)
* Verified `License` list all the details as expected
![image](https://user-images.githubusercontent.com/17010094/67980895-c4461f80-fbf5-11e9-835e-4ea1c5cd871a.png)

----------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.31.15)
* Verified a new entry for `License` is shown at the bottom of settings
![image](https://user-images.githubusercontent.com/17010094/67980910-ce681e00-fbf5-11e9-9b7b-34729b3e48e0.png)
* Verified `License` list all the details as expected
![image](https://user-images.githubusercontent.com/17010094/67980903-c90ad380-fbf5-11e9-94c6-58c8e401baa7.png)

----------
 Verification passed on iPad Pro  with iOS 13.2 running 1.13(19.10.31.15)
* Verified a new entry for `License` is shown at the bottom of settings
![image](https://user-images.githubusercontent.com/17010094/68043980-ed75b700-fcac-11e9-961b-a08d42500c86.png)
* Verified `License` list all the details as expected
![image](https://user-images.githubusercontent.com/17010094/68043990-f4042e80-fcac-11e9-87f6-b334981caa30.png)

----------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.31.15)
* Verified a new entry for `License` is shown at the bottom of settings
![image](https://user-images.githubusercontent.com/17010094/68044020-05e5d180-fcad-11e9-91e7-e943e19e7d88.png)

* Verified `License` list all the details as expected
![image](https://user-images.githubusercontent.com/17010094/68044029-0aaa8580-fcad-11e9-8ab8-d0dd939bd47b.png)
