### ISSUE TITLE
Ad "hang time"

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1773]
### Description: 
Please set the ad "hang time" to 30 seconds 
Please link the onboarding ad hang time to the real ad hang time

**Comment by LaurenWags** [comment]
Verification passed on iPad 5th Gen with iOS 12.4 running 1.13(19.10.30.14).
- Confirmed sample ad hang time and real ad hang time is 30s
----
Verification passed on iPad Pro with 13.2 running 1.13(19.10.30.14)
* Verified sample ad and actual ad notification is retained on screen for 30secs
------
Verification passed on iPhone XR with 13.2 running 1.13(19.10.30.14)
* Verified sample ad and actual ad notification is retained on screen for 30secs
------
Verification passed on iPhone 7+ with 13.2 running 1.13(19.10.30.14)
* Verified sample ad and actual ad notification is retained on screen for 30secs
------
Verification passed on iPhone 6 with 12.4 running 1.13(19.10.30.14)
* Verified sample ad and actual ad notification is retained on screen for 30secs
