### ISSUE TITLE
Add BAT Contribution Queue

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1781]
This feature was added in https://github.com/brave/brave-ios/pull/1761 pulled from brave-core: https://github.com/brave/brave-core/pull/3658 and requires testing (Test cases can be found in brave-core PR)

## Test Plan:

- enable rewards with short contribution interval
- claim grant (30 BAT)
- set AC amount to 20 BAT
- add verified publishers to AC table
- add verified recurring tips in this order (5, 10, 10, 10)
- wait for monthly contribution to trigger
- you should see 25 BAT goes through for monthly and 5 BAT from AC

**Comment by kylehickinson** [comment]
Closed in #1761

**Comment by srirambv** [comment]
Blocked on #1656

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.11.4.14)
* Verified steps from issue description
* Verified both recurring tips and ac go through
* Verified low balance message is shown when recurring tip doesn't go through
---------
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.11.4.14)
* Verified steps from issue description
* Verified both recurring tips and ac go through
* Verified low balance message is shown when recurring tip doesn't go through
---------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.11.4.14)
* Verified steps from issue description
* Verified both recurring tips and ac go through
* Verified low balance message is shown when recurring tip doesn't go through
---------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.11.4.14)
* Verified steps from issue description
* Verified both recurring tips and ac go through
* Verified low balance message is shown when recurring tip doesn't go through
---------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.11.4.14)
* Verified steps from issue description
* Verified both recurring tips and ac go through
* Verified low balance message is shown when recurring tip doesn't go through
