### ISSUE TITLE
Implement the NTP image

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1782]
### Description: 
Please implement the NTP image

Search GDocs for the Spec

cc @jhreis 

### Test Plan

Default new behavior:
1. open new browser install
1. see background image!

Default upgrade behavior:
1. upgrade browser
1. open
1. see background image!

Turn off:
1. Go into Settings > New Tab Page > Turn off "Show Background Images"
1. Going back to main screen should see a background without an image (may be dark, or have gradient on white background depending on your current theme).
1. Opening new tabs should not show any background images

Turn On:
1. Go into Settings > New Tab Page > Turn on "Show Background Images"
1. Going back to NTP, should see a background image
1. Opening subsequent new tabs should continue showing background images

---

Addition thing to note during above testing. You should never see an image appear twice on a fresh new tab page. Since the NTP is cached while it is open (e.g. creating 6 tabs at the same time), sibling NTP's will show the same image. _But_ if you close the NTP and open a new one, it should always have a different background. Please inquire if clarity is needed.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.12.05.18)
Clean install
- Verified new tab shows an image
- Verified toggle setting disables images on new tabs and existing new tabs
- Verified enabling the setting shows images on all existing new tabs and new ones
- Verified opening a private tab shows the new tab images
- Verified setting toggles work on both normal and private tabs
- Verified opening N new tabs retain the same image until a page is loaded in one of the tabs

Upgrade install
- Verified on upgrade new tabs show images by default
-------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.12.05.18)
Clean install
- Verified new tab shows an image
- Verified toggle setting disables images on new tabs and existing new tabs
- Verified enabling the setting shows images on all existing new tabs and new ones
- Verified opening a private tab shows the new tab images
- Verified setting toggles work on both normal and private tabs
- Verified opening N new tabs retain the same image until a page is loaded in one of the tabs

Upgrade install
- Verified on upgrade new tabs show images by default
-------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.12.05.18)
Clean install
- Verified new tab shows an image
- Verified toggle setting disables images on new tabs and existing new tabs
- Verified enabling the setting shows images on all existing new tabs and new ones
- Verified opening a private tab shows the new tab images
- Verified setting toggles work on both normal and private tabs
- Verified opening N new tabs retain the same image until a page is loaded in one of the tabs

Upgrade install
- Verified on upgrade new tabs show images by default
-------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.12.05.18)
Clean install
- Verified new tab shows an image
- Verified toggle setting disables images on new tabs and existing new tabs
- Verified enabling the setting shows images on all existing new tabs and new ones
- Verified opening a private tab shows the new tab images
- Verified setting toggles work on both normal and private tabs
- Verified opening N new tabs retain the same image until a page is loaded in one of the tabs
- Verified opening N new tabs retain the same image until a page is loaded in one of the tabs

Upgrade install
- Verified on upgrade new tabs show images by default
-------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.12.05.18)
Clean install
- Verified new tab shows an image
- Verified toggle setting disables images on new tabs and existing new tabs
- Verified enabling the setting shows images on all existing new tabs and new ones
- Verified opening a private tab shows the new tab images
- Verified setting toggles work on both normal and private tabs
- Verified opening N new tabs retain the same image until a page is loaded in one of the tabs

Upgrade install
- Verified on upgrade new tabs show images by default
-------
