### ISSUE TITLE
Tapping on Rewards button notification enters overlay

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1787]
### Steps to Reproduce 
  1. Fresh install, skip onboarding
  2. Tap on the red dot next to rewards button

**Actual result:** 
Overlay is showing

**Expected result:**
Rewards panel should be opened

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
ez

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Not sure if the same is for verified publisher, can't find any :D

**Comment by LaurenWags** [comment]
Verification passed on iPad 5th Gen with iOS 12.4 running 1.13(19.10.30.14)
* Reproduced issue on earlier version. Installed new build and verified STR from description. Rewards panel is shown when tapped on:
![IMG_44B2A73A4B64-1](https://user-images.githubusercontent.com/28145373/67896006-e4aca600-fb31-11e9-8ff9-4605cb5a76dd.jpeg)
----
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.31.19)
* Verified no overlay is shown and shows rewards panel
-----
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.10.31.19)
* Verified no overlay is shown and shows rewards panel
-----
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.31.19)
* Verified no overlay is shown and shows rewards panel
-----
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.31.19)
* Verified no overlay is shown and shows rewards panel
