### ISSUE TITLE
Incorrect text and date format for Tips

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1791]
### Description: 
Incorrect text and date format for Tips

### Steps to Reproduce 
  1. Install 1.13 and enable rewards
  2. Go to Tips details section
  3. Has incorrect text `Next contribution date` instead of `Next monthly tip date`
  4. Has incorrect date format `YY/MM/DD` instead of `MMM DD`

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/67507499-00f5a200-f65d-11e9-85a1-373a151edb7d.png)

**Expected result:**
Should be similar to desktop

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.10.23.22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by LaurenWags** [comment]
Marking as `QA/Blocked` due to https://github.com/brave/brave-ios/issues/1834

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.30.21)
* Verified both text and date format is similar to desktop
![image](https://user-images.githubusercontent.com/17010094/67912647-fa858f80-fb60-11e9-8113-073e71099d55.png)
---------
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.10.30.21)
* Verified both text and date format is similar to desktop
![image](https://user-images.githubusercontent.com/17010094/67912700-20ab2f80-fb61-11e9-84ff-0f28f51f522c.png)

----------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.30.21)
* Verified both text and date format is similar to desktop
![image](https://user-images.githubusercontent.com/17010094/67912711-2d2f8800-fb61-11e9-999a-c0b1b0fb96dd.png)

---------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.30.21)
* Verified both text and date format is similar to desktop
![image](https://user-images.githubusercontent.com/17010094/67912726-39b3e080-fb61-11e9-9ea8-11c5ba28262c.png)

----------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.30.21)
* Verified both text and date format is similar to desktop
![image](https://user-images.githubusercontent.com/17010094/67912715-328cd280-fb61-11e9-83c2-6d8723c28092.png)
