### ISSUE TITLE
Opening a new tab has a 'website loading' animation which seems unintuitive

### ISSUE THREAD

**Issue by yachtcaptain23** [brave/brave-ios#1793]
### Description: 
Opening a new tab causes the top bar to animate as if a website is being loaded.

### Steps to Reproduce 
  1. Open a new tab
  2. Notice the rainbow animation at the top
  3.

**Actual result:** 

**Expected result:**
Should not produce a rainbow animation for new tabs

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100% reproducible

**Brave Version:** 
Beta

**Device details:** 
iPhone 7+
13.1.3

**Comment by iccub** [comment]
Will be fixed in https://github.com/brave/brave-ios/issues/2799
