### ISSUE TITLE
User agent issue on https://www.volkswagen.ie/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-ios#1795]
### Description: 
Visiting `https://www.volkswagen.ie/en.html` Will generate an Upsupported Browser error

### Steps to Reproduce 
  1. Visiting `https://www.volkswagen.ie/en.html`
  2. `Unsupported Browser
Your browser is not currently supported. Please upgrade your browser to the latest version.`
  3.

**Actual result:** 
Error message shows, no way around it or skip it

**Expected result:**
Page should load

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Everytime on page load

**Brave Version:** 
1.11.4

**Device details:** 
Iphone 8 / 13.1.3

**Website problems only:**
- did you check with Brave Shields down?
Shields makes no difference
- did you check in Safari/Firefox (WkWebView-based browsers)? 
Safari is fine

### Additional Information
User agent; `Mozilla/5.0 (iPhone; CPU iPhone OS 13_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/14.0b12646 Mobile/15E148 Safari/605.1.15`

Looking at the debugging, the user agent check is Expecting `"Version/..."` and when it gets `"FxiOS/..."` it'll error. Manually changing this user-agent variable will work around it.

**Comment by lukemulks** [comment]
Observing this issue on several sites from my iPad Pro. 

eBay 
![67DAA6C5-F0D9-4931-951B-BBB0CF6C8711](https://user-images.githubusercontent.com/8979240/74253043-67054400-4ca3-11ea-8166-a156c717293b.png)

GitHub 
![CB1A5629-15A4-429E-9F41-12C03CC8220B](https://user-images.githubusercontent.com/8979240/74253073-72586f80-4ca3-11ea-9dc6-979fe8690512.png)

The optics are pretty rough, as the message states that the user has an insecure browser @anthonypkeane @jhreis apologies if this is being handled elsewhere, this was the issue that appeared closest upon search.

**Comment by iccub** [comment]
This will be fixed once we change user agent to Safari, https://github.com/brave/brave-ios/issues/2210
Beta build should be ready this week

**Comment by iccub** [comment]
Fixed via https://github.com/brave/brave-ios/issues/2210

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.18.17)
- Verified visiting `https://www.volkswagen.ie/en.html` doesn't show any UA error
- Verified visiting desktop page on `https://www.volkswagen.ie/.en.html` doesn't show any UA error
- Verified visiting desktop page on `https://github.com` doesn't show any UA error
- Verified visiting desktop page on `https://ebay.com` doesn't show any UA error
------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified visiting `https://www.volkswagen.ie/en.html` doesn't show any UA error
- Verified visiting desktop page on `https://www.volkswagen.ie/.en.html` doesn't show any UA error
- Verified visiting desktop page on `https://github.com` doesn't show any UA error
- Verified visiting desktop page on `https://ebay.com` doesn't show any UA error
------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.18.17)
- Verified visiting `https://www.volkswagen.ie/en.html` doesn't show any UA error
- Verified visiting desktop page on `https://www.volkswagen.ie/.en.html` doesn't show any UA error
- Verified visiting desktop page on `https://github.com` doesn't show any UA error
- Verified visiting desktop page on `https://ebay.com` doesn't show any UA error
------
Verification passed on iPad Pro with iOS 13.4 running 1.15(20.02.18.17)
- Verified visiting `https://www.volkswagen.ie/en.html` doesn't show any UA error
- Verified visiting desktop page on `https://www.volkswagen.ie/.en.html` doesn't show any UA error
- Verified visiting desktop page on `https://github.com` doesn't show any UA error
- Verified visiting desktop page on `https://ebay.com` doesn't show any UA error
------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.18.17)
- Verified visiting `https://www.volkswagen.ie/en.html` doesn't show any UA error
- Verified visiting desktop page on `https://www.volkswagen.ie/.en.html` doesn't show any UA error
- Verified visiting desktop page on `https://github.com` doesn't show any UA error
- Verified visiting desktop page on `https://ebay.com` doesn't show any UA error
------
