### ISSUE TITLE
Tab tray cells look bad in dark mode

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1796]
### Steps to Reproduce 
  1. Open few tabs in dark mode

**Actual result:** 

<img width="544" alt="Zrzut ekranu 2019-10-25 o 15 34 27" src="https://user-images.githubusercontent.com/6950387/67575497-01656a00-f73d-11e9-9e69-f2dfd3a0da94.png">

**Expected result:**
background color should be visible

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.13.19)
* Verified theme toggle from control center doesn't affect the tabs tiles
* Verified setting theme to dark manually doesn't affect the tab tiles
![image](https://user-images.githubusercontent.com/17010094/69089962-b0ccee00-0a16-11ea-9297-9411e6cd47ba.png)

------------------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.13.19)
* Verified theme toggle from control center doesn't affect the tabs tiles
* Verified setting theme to dark manually doesn't affect the tab tiles
![image](https://user-images.githubusercontent.com/17010094/69090005-b4607500-0a16-11ea-91d1-5a01a74e669e.png)

------------------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.13.19)
* Verified theme toggle from control center doesn't affect the tabs tiles
* Verified setting theme to dark manually doesn't affect the tab tiles
![image](https://user-images.githubusercontent.com/17010094/69089914-ac083a00-0a16-11ea-8064-d32cba65c2bd.png)

------------------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.13.19)
* Verified setting theme to dark manually doesn't affect the tab tiles
![image](https://user-images.githubusercontent.com/17010094/69090060-b9bdbf80-0a16-11ea-9efb-5705000c919b.png)

------------------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.13.19)
* Verified setting theme to dark manually doesn't affect the tab tiles
![image](https://user-images.githubusercontent.com/17010094/69089852-a7438600-0a16-11ea-9ffe-7b77673e7a86.png)
