### ISSUE TITLE
Bottom area of web view can't be tapped.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1801]
### Steps to Reproduce 
  1. Open wikipedia, scroll down to bottom
  2. Try to tap on terms of use or privacy policy links
  3.

**Actual result:** 
They can't be tapped

**Expected result:**
Should be able to tap on them

<img width="544" alt="Zrzut ekranu 2019-10-28 o 15 44 21" src="https://user-images.githubusercontent.com/6950387/67688332-f5c2af00-f999-11e9-8138-0f8f961f3b75.png">

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
This is not website specific

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.20.19)
* Verified test plan from #1802 
--------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.20.19)
* Verified test plan from #1802 
-------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.20.19)
* Verified test plan from #1802 
-------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.20.19)
* Verified test plan from #1802 
-------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.20.19)
* Verified test plan from #1802 
-------
Logged #2017 as a follow up to swipe back action causing UI issues
