### ISSUE TITLE
Verified publisher icon not shown on tips panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1806]
### Description: 
Verified publisher icon not shown on tips panel

### Steps to Reproduce 
  1. Enable rewards
  2. Visit a verified publisher site and open the tips panel
  3. No verified icon on tips panel

**Actual result:** 
iPhone:
![image](https://user-images.githubusercontent.com/17010094/67708336-5f3ebf80-f992-11e9-9e9c-4510815b00b0.png)
iPad:
![image](https://user-images.githubusercontent.com/17010094/67708349-682f9100-f992-11e9-9ec3-4b422cf4c1fb.png)

**Expected result:**
Similar to desktop should have the verified check mark on tips panel as well
![image](https://user-images.githubusercontent.com/17010094/67708386-741b5300-f992-11e9-84bf-5a84a603890b.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.10.25.14)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by kylehickinson** [comment]
@jamesmudgett Can we get a bigger verified icon for this? The current one may look a bit small on this icon

**Comment by jamesmudgett** [comment]
[Archive.zip](https://github.com/brave/brave-ios/files/3780974/Archive.zip)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.30.14)
![image](https://user-images.githubusercontent.com/17010094/67876694-b073be00-fb0e-11e9-8a59-1077e0142e80.png)

-------
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.10.30.14)
![image](https://user-images.githubusercontent.com/17010094/67876686-ac47a080-fb0e-11e9-84b2-64773059ba2c.png)

-------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.30.14)
![image](https://user-images.githubusercontent.com/17010094/67876732-bcf81680-fb0e-11e9-9a41-c7160fcf1155.png)

-------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.30.14)
![image](https://user-images.githubusercontent.com/17010094/67876675-a782ec80-fb0e-11e9-8368-f937d525ea2f.png)

-------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.30.14)
![image](https://user-images.githubusercontent.com/17010094/67876717-b7023580-fb0e-11e9-8212-acbcf7680c50.png)
