### ISSUE TITLE
Formatting on PIN code error

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1818]
### Description: 
Please fix the formatting on this screen

James, can you provide a design option?

![IMG_D093A1055699-1.jpeg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/d6fb401e-dea3-4593-8a37-84901cfdfe94)

**Comment by kylehickinson** [comment]
@jamesmudgett  Is the solution to this just fixing the background colour of the label to be clear?

**Comment by kylehickinson** [comment]
Confirmed just changing background to clear

**Comment by kylehickinson** [comment]
@jamesmudgett confirmed: Going to change text color to red, and get rid of pill background

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.19.15)
* Verified new UI on both normal tabs and private tabs
* Verified new UI on both light and dark theme
-------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.19.15)
* Verified new UI on both normal tabs and private tabs
* Verified new UI on both light and dark theme
-------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.19.15)
* Verified new UI on both normal tabs and private tabs
* Verified new UI on both light and dark theme
-------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.19.15)
* Verified new UI on both normal tabs and private tabs
* Verified new UI on both light and dark theme
-------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.19.15)
* Verified new UI on both normal tabs and private tabs
* Verified new UI on both light and dark theme
-------
Screenshots in https://github.com/brave/brave-ios/issues/443#issuecomment-555627507
