### ISSUE TITLE
Private Browsing info screen glasses should be white

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#1820]
Current state:
![PBO](https://user-images.githubusercontent.com/318119/67801231-c45be900-fa56-11e9-86b6-ff8dc55d7cd2.jpeg)

Sunglasses should be tinted white.

**Comment by srirambv** [comment]
* Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.19.15)
![image](https://user-images.githubusercontent.com/17010094/69260888-99187580-0b8e-11ea-86ab-ba3b515a3af5.png)
* Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.19.15)
![image](https://user-images.githubusercontent.com/17010094/69260874-94ec5800-0b8e-11ea-957a-ba8197e9f4b2.png)
* Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.19.15)
![image](https://user-images.githubusercontent.com/17010094/69260856-8867ff80-0b8e-11ea-9d95-642592b62f2a.png)
* Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.19.15)
![image](https://user-images.githubusercontent.com/17010094/69260863-8f8f0d80-0b8e-11ea-95a8-c0098b7e364b.png)
* Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.19.15)
![image](https://user-images.githubusercontent.com/17010094/69260843-82721e80-0b8e-11ea-912f-f3d6e0273553.png)
