### ISSUE TITLE
Google AMP  - Tipping Bug

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1824]
### Description: 
Bug: i’m trying to tip a publisher (SFGate) via an article i’m reading via their AMP URL. Tipping panel is trying to tip Google.

![File (1).jpg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/cfb98737-ad70-4e18-84d6-7a701e80eeb4)

**Comment by kylehickinson** [comment]
Requires refactoring in a brave-core/native libs level, opened ticket shown above

**Comment by kylehickinson** [comment]
Closed as this feature is no longer supported in new Rewards on Brave iOS
