### ISSUE TITLE
Change first ad to appear after 2 minutes and retry after 2 minutes if no eligible ads for iOS/Android

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1825]
### Description: 
It takes 30 min for the first ad to be delivered. Given previous conversations, this should be 2 min.

We have also changed ads to be delivered after 2 minutes if no previous ads were eligible to be shown

Can this be fixed?

cc @jsecretan

**Comment by tmancey** [comment]
@anthonypkeane This has been fixed in https://github.com/brave/brave-browser/issues/6661 and will be in the next build once approved

**Comment by kylehickinson** [comment]
Still waiting for https://github.com/brave/brave-core/pull/3823 to be merged

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.11.6.18)
- Clean install 
  - Verified after enabling rewards and visiting a site an ad is shown after 2 mins
- Upgrade install
  - Verified upgrading from 1.12.1 and enabling rewards and visiting a site, an ad is shown after 2 mins
------
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.11.6.18)
- Clean install 
  - Verified after enabling rewards and visiting a site an ad is shown after 2 mins
- Upgrade install
  - Verified upgrading from 1.12.1 and enabling rewards and visiting a site, an ad is shown after 2 mins
------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.11.6.18)
- Clean install 
  - Verified after enabling rewards and visiting a site an ad is shown after 2 mins
- Upgrade install
  - Verified upgrading from 1.12.1 and enabling rewards and visiting a site, an ad is shown after 2 mins

**Comment by tmancey** [comment]
@srirambv Can we also test if there are no eligible ads that we retry after 2 mins. As only after an ad is shown should we try every x mins based upon the ads per hour. Thanks
