### ISSUE TITLE
Publisher Shows as unverified if publisher is visited before publisher list finished parsing

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1831]
STR:
1. Visit a verified publisher (i.e. https://twitter.com/alex_wykoff)
2. Enable rewards
3. The publisher will show as unverified both in the URL bar and in the panel (except for right after clicking "refresh", but it will not persist)

**Comment by LaurenWags** [comment]
Verified passed on iPad 5th Gen with iOS 12.4 running 1.13(19.10.30.21)
* Verified STR from description
* Encountered #1863 and #1691 while testing
-------
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.11.4.14)
* Verified pub state is retained while parsing 
* Verified closing and reopening panel doesn't lose publisher verified state
--------
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.11.4.14)
* Verified pub state is retained while parsing 
* Verified closing and reopening panel doesn't lose publisher verified state
--------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.11.4.14)
* Verified pub state is retained while parsing 
* Verified closing and reopening panel doesn't lose publisher verified state
--------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.11.4.14)
* Verified pub state is retained while parsing 
* Verified closing and reopening panel doesn't lose publisher verified state
