### ISSUE TITLE
Subdomains not always shown when browser is in multitask mode

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1833]
### Description: 
TDL+1 isn't shown correctly when browser is in multitask mode

### Steps to Reproduce 
  1. Open Brave in multitask mode
  2. Visit tech.slashdot.org
  3. Only slashdot.org is shown

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/67887687-25042800-fb22-11e9-9d7e-f89a3dee22eb.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/17010094/67887851-744a5880-fb22-11e9-8f43-c2314f9fcf04.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.10.30.14)

**Device details:** 
iPad Pro (iOS 12.4/13.2)

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)?  N/A

### Additional Information
cc: @jumde @kylehickinson 
This is  a regression on iOS 13.2 but same behaviour on 12.4

**Comment by tildelowengrimm** [comment]
`slashdot.org` is the security-critical part of the URL. The important thing is ensuring that string is shown, which it is.

**Comment by kylehickinson** [comment]
So this is not a bug then?

**Comment by jumde** [comment]
`slashdot.org` is important from a security standpoint. I think the URL is shortened because of the BAT icon in the URL bar which is expected. @srirambv - Let me know if I'm missing something here.

**Comment by srirambv** [comment]
>  I think the URL is shortened because of the BAT icon in the URL bar which is expected.

Yes looks like if i disable rewards button it shows up fine.

**Comment by kylehickinson** [comment]
Going to close as not a bug then, please re-open if something else comes up
