### ISSUE TITLE
Tips panel has incorrect label for next tip date - follow up to 1791

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#1834]
### Description: 
Found while testing #1791 

Incorrect text in Tips panel

### Steps to Reproduce 
  1. Install 1.13 and enable rewards
  2. Put BAT in wallet
  3. Set up a monthly tip for a site (mine was verified)
  4. Go to Tips details section

**Actual result:** 
text label for tip date is incorrect:
![IMG_65E58E7B0F81-1](https://user-images.githubusercontent.com/28145373/67894702-7961d480-fb2f-11e9-8f8b-5c33025ddb6c.jpeg)

**Expected result:**
`Next contribution date` should read `Next monthly tip date` per #1791 and this would match desktop as well.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.13 (19.10.30.14)

**Device details:** 
iPad 5th gen iOS 12

**Website problems only:**
- did you check with Brave Shields down? n/a
- did you check in Safari/Firefox (WkWebView-based browsers)? n/a

### Additional Information
cc @srirambv

**Comment by srirambv** [comment]
* Verification passed on iPhone XR with iOS 13.2 running 1.13(19.10.30.21)
![image](https://user-images.githubusercontent.com/17010094/67911276-54d02180-fb5c-11e9-93ec-abf376754893.png)
---------
* Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.10.30.21)
![image](https://user-images.githubusercontent.com/17010094/67911305-76c9a400-fb5c-11e9-8333-8493c4344f7a.png)
---------
* Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.30.21)
![image](https://user-images.githubusercontent.com/17010094/67911376-b1334100-fb5c-11e9-81ec-402d0ff1978b.png)

---------
* Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.30.21)
![image](https://user-images.githubusercontent.com/17010094/67911390-c019f380-fb5c-11e9-946a-df33cfe45255.png)

---------
* Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.30.21)
![image](https://user-images.githubusercontent.com/17010094/67911419-de7fef00-fb5c-11e9-8ce2-74cc95d6c4bb.png)
