### ISSUE TITLE
"My First Ad"/Sample ad doesn't slide in smoothly in certain cases - follow up to 1746

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#1839]
### Description: 
Found while testing #1746 

When testing the `Existing User, in ad region` case from #1746 I noticed that the first/sample ad in onboarding doesn't always slide in smoothly. Sometimes it gets stuck (half way, 1/4 of the way) when sliding in. However, after 1s when the 'Start Browsing' button is shown, the full ad displays. 

### Steps to Reproduce 
  1. Install 1.12.1 from TF
  2. Go thru onboarding.
  3. Open a site in a tab.
  4. Close Brave, remove from memory.
  5. Install 1.13(19.10.30.14) from TF
  6. On launch you are notified about BR
  7. Follow onboarding flow.

**Actual result:** 
Once countdown reaches 0, sometimes the sample ad is stuck (in recording below most of the ad is visible, however I have seen it get stuck halfway) until Start Browsing button appears.

https://drive.google.com/file/d/15XW0ESunD9toH8oBRZwOClSTL9KQczQf/view?usp=sharing

**Expected result:**
Sample ad should slide in fully and smoothly

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
intermittent

**Brave Version:** 
1.13(19.10.30.14)

**Device details:** 
iPad 5th Gen iOS12

**Website problems only:**
- did you check with Brave Shields down? n/a
- did you check in Safari/Firefox (WkWebView-based browsers)? n/a

### Additional Information
cc @srirambv

**Comment by kylehickinson** [comment]
Closed as my first ad is no longer shown
