### ISSUE TITLE
Remove Firefox "Page Actions" button from the Address Bar

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#185]
- [ ] Replace all Photon menus with standard ActionSheet
- [ ] Delete all Photon code

Replace it either with system action sheet or with our new popup style that Kyle has implemented.
The left one is the one we want to get rid of.

<img width="890" alt="zrzut ekranu 2018-08-22 o 14 41 13" src="https://user-images.githubusercontent.com/6950387/44575855-61552f00-a78d-11e8-8852-ebc6dcb1961a.png">

**Comment by kylehickinson** [comment]
Most of the photon action sheets have actually been removed/replaced in #182.

The only one left is the main one (•••).
