### ISSUE TITLE
Settings Wallet Details empty wallet copy missing

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1852]
Should not show `October 2019`, it should show the empty wallet state.

Likely a regression of the JP region stuff where you show a disclaimer in here if region is set to JP

![Simulator Screen Shot - iPhone 11 Pro - 2019-10-31 at 12 40 28](https://user-images.githubusercontent.com/529104/67967250-a7045780-fbdb-11e9-834a-5e70f16ef8c0.png)

**Comment by kylehickinson** [comment]
Couldn't reproduce this, must have been a different problem, but doesn't seem to be happening anymore?

![Simulator Screen Shot - iPhone Xs - 2019-11-18 at 11 07 09](https://user-images.githubusercontent.com/529104/69068949-a77e5a00-09f3-11ea-8e8b-1adbca5b0608.png)
![Simulator Screen Shot - iPhone Xs - 2019-11-18 at 11 07 45](https://user-images.githubusercontent.com/529104/69068951-a8af8700-09f3-11ea-8367-2e47dfcff86e.png)

Closing for now

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14.1(19.12.04.02)

* Verified for ads supported regions and non-ads regions uses the same 
![image](https://user-images.githubusercontent.com/17010094/70182281-8f742f00-16b1-11ea-98cb-5ef855776ad4.png)
* Verified for BAT Points as well
![image](https://user-images.githubusercontent.com/17010094/70182275-8b481180-16b1-11ea-81e7-dddf200aae13.png)

------

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.14.1 (19.12.04.20)`

* Verified that `Japan` (supported ad region) was displaying the correct screen under `Rewards`
* Verified that `Germany` (supported ad region) was displaying the correct screen under `Rewards`
* Verified that `Belarus` (unsupported ad region) was displaying the correct screen under `Rewards`

![IMG_9958](https://user-images.githubusercontent.com/2602313/70192961-7c6e5880-16cb-11ea-837e-4ca0c7a41816.PNG)

![IMG_9959](https://user-images.githubusercontent.com/2602313/70192885-3f09cb00-16cb-11ea-9cb6-57ec9d5e7036.PNG)

![IMG_F9CD36BDFF1E-1](https://user-images.githubusercontent.com/2602313/70192884-3f09cb00-16cb-11ea-8710-8116d321e1b4.jpeg)

-----
Verification passed on iPad Pro with iOS 13.2 running 1.14.1(19.12.05.00)
* Verified on ads supported and non-supported region
* Verified on Japan locale as well
![image](https://user-images.githubusercontent.com/17010094/70248458-ec6ef400-1748-11ea-86ad-bc2b1e824fe2.png)
----
Verification passed on iPad Pro with iOS 12.4 running 1.14.1(19.12.05.00)
* Verified on ads supported and non-supported region
* Verified on Japan locale as well
![image](https://user-images.githubusercontent.com/17010094/70248508-014b8780-1749-11ea-88ff-0987bd638bda.png)
