### ISSUE TITLE
Ad "landing" confirmations are not being generated

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-ios#1855]
### Description: 
When an ad is clicked and you stay on the landing page for more than 10 seconds, it should generate a "landing" event confirmation to correspond to that.  While I have tried this a few times, I see no landing confirmations in the database.

### Steps to Reproduce 
  1. Get a Brave Ad
  2.Tap the Ad
  3. Spend 15 seconds on the landing page

**Actual result:**
No land events in the database.

**Expected result:**
There should be at least some landing events in the database for the iOS platform.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.13 (19.10.30.21)

**Device details:** 
iPhone X, 13.1.3

### Additional Information
@tmancey indicates that this should probably be handled by the native library automatically.

**Comment by tmancey** [comment]
@kylehickinson Do you call `OnPageLoaded` for ads, as internally we detect if an ad run through the business logic for sustaining an ad`. I expect this call is not being made.

Note: However if an ad URL is redirected (likely on staging) then sustaining of the ad will fail. You can search for `Start sustaining ad interaction in` in the logs to determine if working or not.

**Comment by kylehickinson** [comment]
@tmancey I'm pretty sure we call OnPageLoaded for ads that the user taps, yes, but I'll double check today

**Comment by tmancey** [comment]
@kylehickinson Great and if you could send over the console log that would be great and I will see why it could be broken. Thanks
