### ISSUE TITLE
Turn on button text colour changes when ToS is opened

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1860]
### Description: 
Turn on button text colour changes when ToS is opened

### Steps to Reproduce 
  1. Clean install 1.13(19.10.31.19)
  2. Follow onboarding and tap on ToS
  3. Close ToS page, `Turn On` button text changes from white to dark 

**Actual result:** 
![TunrONiOS12](https://user-images.githubusercontent.com/17010094/67982356-ebeab700-fbf8-11e9-9b8b-8d3627449768.gif)

**Expected result:**
Should not change button text colour 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.10.31.19)

**Device details:** 
iPhone 6 (iOS 12.4)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Issue is only on iOS 12. Doesn't happen on iOS 13. Not adding to 1.13 release. not a blocker 
cc: @kylehickinson

**Comment by kylehickinson** [comment]
May not be needed in the future with new onboarding flow

**Comment by jhreis** [comment]
I'm blocking this, since it almost certainly won't be needed during onboarding change.

**Comment by NejcZdovc** [comment]
@kylehickinson can this one be closed?

**Comment by kylehickinson** [comment]
Yeah this can be closed, will be replaced in the near future
