### ISSUE TITLE
Closing a private tab  switches theme from dark to light

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1862]
### Description: 
Closing a private tab causes theme to switch from dark to light

### Steps to Reproduce 
  1. Set device theme to dark
  2. Visit a site with link
  3. Long press on a link and open in a private tab
  4. Exit private tab
  5. Open normal tab again, theme is changed to light from dark even though device theme is still set to dark

**Actual result:** 
![private_light](https://user-images.githubusercontent.com/17010094/67985953-59e6ac80-fc00-11e9-8bc5-2e51f021a902.gif)

**Expected result:**
Not change theme when exiting private tab

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.10.31.19)

**Device details:** 
iPhone 7+ (iOS 13.2)
iPhone XR (iOS 13.2)

**Website problems only:**
- did you check with Brave Shields down? N?A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by iccub** [comment]
This doesn't seem to happen when not using quick switcher, moving out of 1.13 release

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(21.5.25.18)
- Verified steps from issue description
- Verified theme doesn't switch when exiting from private tab
---------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.26(21.5.25.18)
- Verified steps from issue description
- Verified theme doesn't switch when exiting from private tab
---------
Verification passed on iPad Pro with iOS 14.5.1 running 1.26(21.5.25.18)
- Verified steps from issue description
- Verified theme doesn't switch when exiting from private tab
