### ISSUE TITLE
Publisher List loader doesn't appear on panel after creating a wallet on slower devices

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#1863]
Engineering notes:
- Due to the fact that server publisher list doesn't begin downloading before panel shows wallet screen
- Need a hook/observer into when process starts to show the loader when it begins _or_ show the loader after wallet creation by default

### Description: 
Found while testing #1831 

Per discussion with @kylehickinson if you enable rewards while on a site (such as brave.com, not something like a blank new tab page), the panel should indicate, with a spinning circle, that the publisher status is being checked. This isn't happening all the time.

### Steps to Reproduce 
1. Clean install 1.13 (19.10.30.21)
2. Skip onboarding
3. Visit a verified site (such as brave.com)
4. Tap on BAT logo, enable Rewards
5. brave.com shows as unverified 

**Actual result:** 
Spinning circle does not appear, so I clicked on Refresh status in the video below. Spinning circle showed briefly but then went away and there was no visual feedback until I reopened the panel.

https://drive.google.com/open?id=1dg0pV6C3kh_I11fS0kbU6EXC01SyqACV

**Expected result:**
Should not have been able to tap on Refresh Status.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
fairly often

**Brave Version:** 
1.13 (19.10.30.21)

**Device details:** 
iPad 5th Gen iOS12

**Website problems only:**
- did you check with Brave Shields down? n/a
- did you check in Safari/Firefox (WkWebView-based browsers)? n/a

**Comment by NejcZdovc** [comment]
closing as this will be fixed by https://github.com/brave/brave-browser/issues/9502
