### ISSUE TITLE
distorted UI when selecting items from "Downloads"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#1864]
### Description: 

When selecting items from `Downloads` by swiping on them, both the `Share` & `Delete` buttons will look distorted.

### Steps to Reproduce 

  1. install `1.13 (19.10.31.19)` and load https://www.thinkbroadband.com/download
  2. download one of the smaller files and go into `Downloads` once completed
  3. swipe on the download and you'll notice both buttons are distorted

**Actual result:** 

<img width="617" alt="Screen Shot 2019-11-01 at 1 36 37 AM" src="https://user-images.githubusercontent.com/2602313/68004477-12840e80-fc48-11e9-88ad-71077fc962fa.png">

<img width="596" alt="Screen Shot 2019-11-01 at 1 36 29 AM" src="https://user-images.githubusercontent.com/2602313/68004478-12840e80-fc48-11e9-9360-ecc65b9f9133.png">

**Expected result:**

<img width="588" alt="Screen Shot 2019-11-01 at 1 38 17 AM" src="https://user-images.githubusercontent.com/2602313/68004542-4c551500-fc48-11e9-8cb3-0abb5a51d441.png">

<img width="581" alt="Screen Shot 2019-11-01 at 1 38 11 AM" src="https://user-images.githubusercontent.com/2602313/68004543-4c551500-fc48-11e9-955a-88258514b6f3.png">

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.12.1 (19.09.20.23`) on both `iOS 12` & `iOS 13` - `Not reproducible`
* `1.13. (19.10.31.19`) on both `iOS 12` & `iOS 13` - `Reproducible`

**Device details:** 

* `iPad Air (3rd Gen)` running `iOS 13.2` - `Reproducible`
* `iPad Mini 4` running `iOS 12.4.` - `Reproducible`

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @aekeus @jhreis @brave/legacy_qa

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.11.1.19)
* Verified edit buttons on the download page isn't distorted on dark and light theme
---------
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.11.1.19)
* Verified edit buttons on the download page isn't distorted on dark and light theme
---------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.11.1.19)
* Verified edit buttons on the download page isn't distorted on dark and light theme
---------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.11.1.19)
* Verified edit buttons on the download page isn't distorted on dark and light theme
---------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.11.1.19)
* Verified edit buttons on the download page isn't distorted on dark and light theme
