### ISSUE TITLE
different icons are sometimes being displayed when scrolling through `History`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#1865]
### Description: 

When scrolling through the history entries via `History`, you'll notice that some icons load a previous one before loading the correct one which makes the entire experience seem janky.

### Steps to Reproduce

  1. install `1.13 (19.10.31.19)` and visit a bunch of websites so you populate `History`
  2. Once you have ~20-30 entries in `History`, scroll through the list

**Actual result:** 

Example: https://youtu.be/RD8Gz7pukGw

**Expected result:**

Scrolling through `History` should be a smooth experience and icons shouldn't appear like they're "flashing".

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.12.1 (19.09.20.23`) on both `iOS 12` & `iOS 13` - `Not reproducible`
* `1.13. (19.10.31.19`) on both `iOS 12` & `iOS 13` - `Reproducible`

**Device details:** 

* `iPad Air (3rd Gen)` running `iOS 13.2` - `Reproducible`
* `iPad Mini 4` running `iOS 12.4.` - `Reproducible`

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @aekeus @jhreis @brave/legacy_qa

**Comment by iccub** [comment]
Moving out of 1.13 release

**Comment by srirambv** [comment]
This happens on bookmarks as well when you scroll fast after its sync'd

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.18(20.06.16.8)
- Verified steps from issue description
- Verified when no icon is available, it uses default tab icon and then loads the fallback letter 
-------
Verification passed on iPhone 7+  with iOS 13.4.5 running 1.18(20.06.16.8)
- Verified steps from issue description
- Verified when no icon is available, it uses default tab icon and then loads the fallback letter 
-------
Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.06.16.8)
- Verified steps from issue description
- Verified when no icon is available, it uses default tab icon and then loads the fallback letter
