### ISSUE TITLE
Rewards onboarding is not shown for existing user on non-ads region [Follow up to #1757]

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1869]
### Description: 
Rewards onboarding is not shown for existing user on non-ads region [Follow up to #1757]

### Steps to Reproduce 
  1. Set device to non-ads region
  2. Install 1.12.1 finish onboarding
  3. Upgrade to 1.13
  4. No rewards onboarding is shown

**Actual result:** 
Rewards onboarding is not shown for existing user on non-ads region 

**Expected result:**
Should show rewards onboarding if its not enabled in previous versions

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.10.31.19)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Brandon-T** [comment]
Videos sent in Slack: https://bravesoftware.slack.com/archives/DLSAZCHQD/p1572640794005600
I can't seem to reproduce this at all.

Steps:

1. Set device region to Russia.
2. Download 1.12.x from Test-Flight.
3. Go through onboarding (notice no rewards show up and onboarding ends at shields).
4. Change region to Canada.
5. Upgrade to 1.13.x.
6. Go through onboarding (notice Rewards and ads show up).

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.11.2.17)
* Verified upgrading from 1.12.1 to 1.13 shows rewards onboarding for the non-ads region
------
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.11.2.17)
* Verified upgrading from 1.12.1 to 1.13 shows rewards onboarding for the non-ads region
------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.11.2.17)
* Verified upgrading from 1.12.1 to 1.13 shows rewards onboarding for the non-ads region
------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.11.2.17)
* Verified upgrading from 1.12.1 to 1.13 shows rewards onboarding for the non-ads region
------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.11.2.17)
* Verified upgrading from 1.12.1 to 1.13 shows rewards onboarding for the non-ads region
