### ISSUE TITLE
Add copy for Ads Grant message

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1871]
### Description: 
Please add the following copy for Ads Grant claim

![Screen Shot 2019-11-01 at 2.28.18 PM.png](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/d46a97cb-cc46-4720-a544-ecc27bc0a4e9)

Translations needed!

**Comment by srirambv** [comment]
* Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69371099-292cec80-0c6d-11ea-8d44-7592dbee1272.png)

---

* Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69371112-2df1a080-0c6d-11ea-8c7f-4e6c38b411c1.png)

---

* Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69371121-32b65480-0c6d-11ea-9450-b6612fa1193d.png)

---

* Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69370511-1665e800-0c6c-11ea-8fef-11025b317581.png)

----

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.14(19.11.20.19)`

![IMG_9933](https://user-images.githubusercontent.com/2602313/69372297-6befc400-0c6f-11ea-8ed9-fb8177fc52ec.PNG)
