### ISSUE TITLE
Fix onboarding issue for Russian

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1873]
### Description: 

![Image from iOS.jpg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/64c92848-2bd1-498f-882e-0d06fa0f9872)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6s` running `iOS 13.2.2` using `1.14 (19.11.26.21)`

![IMG_0030](https://user-images.githubusercontent.com/2602313/69680304-90390f80-1078-11ea-90d5-59cff8f5cf29.PNG)

---

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.14 (19.11.26.21)`

![IMG_9939](https://user-images.githubusercontent.com/2602313/69680028-b5794e00-1077-11ea-9a8b-75495bcb3484.PNG)

---

Verification **PASSED** on `iPad Air 3rd Gen` running `iOS 13.3` using `1.14 (19.11.26.21)`

![IMG_13D3E393F9B8-1](https://user-images.githubusercontent.com/2602313/69680628-76e49300-1079-11ea-8891-8c4e145fff2f.jpeg)

---

Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.14 (19.11.26.21)`

![IMG_0293](https://user-images.githubusercontent.com/2602313/69680527-23724500-1079-11ea-927d-800eed4d8d78.PNG)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.27.14)
![image](https://user-images.githubusercontent.com/17010094/69740572-9a561f00-1107-11ea-830d-c94c245e1590.png)
![image](https://user-images.githubusercontent.com/17010094/69740587-9f1ad300-1107-11ea-8711-09613513750a.png)
![image](https://user-images.githubusercontent.com/17010094/69740600-a346f080-1107-11ea-8e3d-bd7cc2282434.png)
