### ISSUE TITLE
Add BAP/BAT to the grant claim screen

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1880]
### Description: 

Please add BAP/BAT after the 17.5

Note: This is low priority, if no time, move it to 1.14

![Image from iOS (1).jpg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/eff163b2-1f79-4fb7-bdd6-51ae81bd493d)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.11.2.17)
- Verified grant notification has `Points grant` in message
![image](https://user-images.githubusercontent.com/17010094/68121164-0f518280-fed5-11e9-8578-6482ce104c54.png)
- Verified `BAP` is added after the grant value in the success message
![image](https://user-images.githubusercontent.com/17010094/68121168-12e50980-fed5-11e9-9e20-2479c666aee6.png)

----------
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.11.2.17)
- Verified grant notification has `Points grant` in message
![image](https://user-images.githubusercontent.com/17010094/68121154-0a8cce80-fed5-11e9-87ab-e7f466e70af2.png)
- Verified `BAP` is added after the grant value in the success message
![image](https://user-images.githubusercontent.com/17010094/68121135-ffd23980-fed4-11e9-828b-57c7726df543.png)

----------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.11.2.17)
- Verified grant notification has `Points grant` in message
![image](https://user-images.githubusercontent.com/17010094/68121120-f648d180-fed4-11e9-8de3-79795b097969.png)
- Verified `BAP` is added after the grant value in the success message
![image](https://user-images.githubusercontent.com/17010094/68121145-05c81a80-fed5-11e9-9ecb-34da59368c3f.png)

----------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.11.2.17)
- Verified grant notification has `Points grant` in message
![image](https://user-images.githubusercontent.com/17010094/68121271-53448780-fed5-11e9-8fa3-51cd703a8d39.png)
- Verified `BAP` is added after the grant value in the success message
![image](https://user-images.githubusercontent.com/17010094/68121280-5770a500-fed5-11e9-89e8-2085f9b50808.png)

----------
Verification passed on iPad Pro  with iOS 12.4 running 1.13(19.11.2.17)
- Verified grant notification has `Points grant` in message
![image](https://user-images.githubusercontent.com/17010094/68121092-e6c98880-fed4-11e9-86f9-fd5a060c8fa7.png)
- Verified `BAP` is added after the grant value in the success message
![image](https://user-images.githubusercontent.com/17010094/68121059-ce596e00-fed4-11e9-9dae-7d846424246d.png)
