### ISSUE TITLE
Claim grant button can be spammed

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1882]
### Steps to Reproduce 
  1. Try to claim grant
  2. When it's loading try to tap on it few times

**Actual result:** 
Loading spinner gets stuck, and I can see in logs that the reqest is being resent

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
Will be fixed with virtual grants PR
