### ISSUE TITLE
Claiming grants via settings option uses fake values

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1884]
### Steps to Reproduce 
  1. Wait for grant
  2. Open Rewards settings
  3. Claim on claim grant button

**Actual result:** 
Fake value 30 BAT is used

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
Will be fixed with #1877

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.13(19.11.2.17)
* Verified correct grant value is shown when the grant is claimed
* Verified grant can be used for tipping and auto-contribution
--------
Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.11.2.17)
* Verified correct grant value is shown when the grant is claimed
* Verified grant can be used for tipping and auto-contribution
--------
Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.11.2.17)
* Verified correct grant value is shown when the grant is claimed
* Verified grant can be used for tipping and auto-contribution
--------
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.11.2.17)
* Verified correct grant value is shown when the grant is claimed
* Verified grant can be used for tipping and auto-contribution
--------
Verification passed on iPad pro with iOS 12.4 running 1.13(19.11.2.17)
* Verified correct grant value is shown when the grant is claimed
* Verified grant can be used for tipping and auto-contribution
