### ISSUE TITLE
Implement loading spinner on wallet while tokens are being signed 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1888]
### Description: 
Implement loading spinner on wallet while tokens are being signed 

### Steps to Reproduce 
  1. Enable rewards
  2. Claim token grant
  3. No UI feedback until tokens are signed
  4. Balance shows 0 even though the grant is claimed 

**Actual result:** 
No UI Feedback when grant is claimed and tokens are not signed yet

**Expected result:**
Implement loading spinner similar to Android to have UI feedback that something is going one 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.11.2.17)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information
Would be good to have in 1.13 but not blocking release for it

**Comment by kylehickinson** [comment]
Blocked until we have a hook in ledger lib to update us when this process finishes 

cc @NejcZdovc

**Comment by NejcZdovc** [comment]
@kylehickinson we have this hooks now, so this is ready
