### ISSUE TITLE
Incorrect attention calculation for Twitter accounts

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1889]
### Description: 
Incorrect attention calculation for Twitter accounts

### Steps to Reproduce 
  1. Enable rewards
  2. Visit a verified twitter account page
  3. Stay on the page for min time
  4. Open rewards panel, shows 0% for Attention
  5. Open ac details 
  6. Shows 100% for twitter 

**Actual result:** 
Incorrect attention calcualtion for twitter accounts 

**Expected result:**
Panel and AC list should show the same attention value

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.11.2.17)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by kylehickinson** [comment]
Not a bug, same thing happens on Desktop and is intentional
