### ISSUE TITLE
AC list isn't cleared after contribution goes through

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1890]
### Description: 
AC list isn't cleared after contribution goes through

### Steps to Reproduce 
  1. Enable rewards and claim the grant
  2. Add sites to the ac list
  3. Trigger auto-contribution
  4. Wait for the auto-contribution notification to show up
  5. Open ac details, list of sites isn't removed after contribution goes through

**Actual result:** 
AC list isn't cleared after contribution goes through

**Expected result:**
AC list should be cleared irrespective of the contribution goes through or not

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.11.2.17)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by kylehickinson** [comment]
Blocked until we have some API from ledger lib to tell us that it has finished fetching and verifying tokens

**Comment by jhreis** [comment]
cc'ing @tmancey / @NejcZdovc  how important is this, any idea what the cause is?

**Comment by NejcZdovc** [comment]
@jhreis this is really important as when you do AC you start with new cycle. Not sure why this is a problem as all of this happens in native lib. I think that we just need to refresh UI

**Comment by kylehickinson** [comment]
@srirambv The AC list doesn't update while you're on the page? Or doesn't update regardless of if you leave and come back?

@NejcZdovc We aren't doing anything special I don't think for fetching AC table publishers. Maybe something we're missing: https://github.com/brave/brave-ios/blob/3906d76d7c3cc9bbc469a711c8a33641ca3666ff/BraveRewardsUI/Settings/Auto-Contribute/Details/AutoContributeDetailsViewController.swift#L65-L81

**Comment by NejcZdovc** [comment]
@kylehickinson you are missing important filter `reconcile_stamp`. That's why list is not updated when AC goes through

**Comment by NejcZdovc** [comment]
You can use `GetAutoContributeProps` to get current reconcile stamp

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.14.2 (19.12.11.21)`

* reproduced original issue using STR mentioned via https://github.com/brave/brave-ios/issues/1890#issue-517109977 using `1.14 (19.11.27.22)`
* ensured that that the a-c list was being populated as expected when visiting publishers (before and after an a-c was initiated)
* ensured that tipping both unverified & verified publishers worked without any issues
* ensured that a-c worked without any issues once the devices date was moved past the a-c date
* ensured that the a-c list was cleared when a a-c was initiated
* ensured that the a-c notification appeared without any issues and displayed the correct information

Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.14.2 (19.12.11.21)`

* reproduced original issue using STR mentioned via https://github.com/brave/brave-ios/issues/1890#issue-517109977 using `1.14 (19.11.27.22)`
* ensured that that the a-c list was being populated as expected when visiting publishers (before and after an a-c was initiated)
* ensured that tipping both unverified & verified publishers worked without any issues
* ensured that a-c worked without any issues once the devices date was moved past the a-c date
* ensured that the a-c list was cleared when a a-c was initiated
* ensured that the a-c notification appeared without any issues and displayed the correct information
------
Verification passed on iPhone XR with iOS 13.2 running 1.14.2(19.12.11.21)
* Verified ac list is removed once notification about ac is shown
* Verified ac list gets repopulated after ac goes through when sites are visited
------
Verification passed on iPad Pro with iOS 13.2 running 1.14.2(19.12.11.21)
* Verified ac list is removed once notification about ac is shown
* Verified ac list gets repopulated after ac goes through when sites are visited
