### ISSUE TITLE
New Private tab in quick action should use Brave specific icon

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1896]
### Description: 
New Private tab in quick action should use Brave specific icon

### Steps to Reproduce 
  1. Long press on Brave 
  2. New private tab icon uses FF icon

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/68134472-2baee880-fef0-11e9-9763-97203877f9e8.png)

**Expected result:**
Should use Brave specific icons

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.11.2.14)

**Device details:** 
iPhones with 3D touch

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by jamesmudgett** [comment]
[Archive.zip](https://github.com/brave/brave-ios/files/3804920/Archive.zip)

**Comment by srirambv** [comment]
* Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.22.15)
![image](https://user-images.githubusercontent.com/17010094/69440842-8a10ff00-0d17-11ea-88ac-58e5896c4a79.png)

----

* Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.22.15)
![image](https://user-images.githubusercontent.com/17010094/69440901-a6ad3700-0d17-11ea-8855-14c7951cc267.png)

-----

* Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.22.15)
![image](https://user-images.githubusercontent.com/17010094/69440954-bdec2480-0d17-11ea-8daa-564e72f818ef.png)

-----

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.14 (19.11.22.15)`

![IMG_9937](https://user-images.githubusercontent.com/2602313/69442184-1cb29d80-0d1a-11ea-9b30-fc462feb98eb.PNG)
