### ISSUE TITLE
New tab gets verified check mark 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1901]
### Description: 
New tab gets verified check mark 

### Steps to Reproduce 
  1. Enable rewards
  2. Visit a verified publisher on a new tab
  3. Open a second new tab and open rewards button, shows verified check mark for new tab

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/68222586-384b4380-ffb9-11e9-97f5-d5ea5890c30b.png)

**Expected result:**
Should not show verified check mark for new tabs

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent 

**Brave Version:** 
1.13(19.11.4.20)

**Device details:** 
All dont think device specific

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Brandon-T** [comment]
@srirambv do you know if this happens on development as well? I wasn't able to reproduce it :(

**Comment by srirambv** [comment]
@Brandon-T yes it happens on dev as well but its not always.

**Comment by srirambv** [comment]
- Verification passed on iPhone XR with iOS 13.3.1 running 1.15(20.01.13.17)
  - Verified steps from issue description and no verified check on NTP
----
- Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.01.13.17)
  - Verified steps from issue description and no verified check on NTP
-----
- Verification passed on iPhone 6 with iOS 12.4.4 running 1.15(20.01.13.17)
  - Verified steps from issue description and no verified check on NTP
-----
- Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.01.13.17)
  - Verified steps from issue description and no verified check on NTP
-----
- Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.01.13.17)
  - Verified steps from issue description and no verified check on NTP
