### ISSUE TITLE
Browser crash when copy to clipboard buttons are clicked

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1903]
### Description: 
Browser crash when copy to clipboard buttons are clicked

### Steps to Reproduce 
Brave Rewards
  1. Upgrade to 1.13
  2. Enable rewards 
  3. Open settings -> Brave Rewards -> Click on Wallet creation date, browser crashes

Version Info
  1. Upgrade to 1.13
  2. Open settings -> Tap on version info, browser crashes

**Actual result:** 
![crash (1)](https://user-images.githubusercontent.com/17010094/68251777-d4913c80-fff1-11e9-9b13-74cb1ca4751f.gif)

**Expected result:**
No crash. Should copy support info into clipboard

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.11.5.20)

**Device details:** 
iPad only

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
@srirambv nice find 👍

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 13.2 running 1.13(19.11.5.23)
* Verified no browser crash when version info is clicked
* Verified no browser crash when wallet creation date is clicked
* Verified no browser crash when restore all sites in ac is clicked
-------
Verification passed on iPad Pro with iOS 12.4 running 1.13(19.11.5.23)
* Verified no browser crash when version info is clicked
* Verified no browser crash when wallet creation date is clicked
* Verified no browser crash when restore all sites in ac is clicked
