### ISSUE TITLE
Incorrect message for ads grant in rewards panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1908]
### Description: 
Incorrect message for ads grant in rewards panel

### Steps to Reproduce 
  1. Wait for ads grant to show up
  2. Got to settings 

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/68314057-8f1d4f80-0083-11ea-9b48-673197575bb6.png)

**Expected result:**
Similar to desktop 
![image](https://user-images.githubusercontent.com/17010094/68314031-84fb5100-0083-11ea-8a1f-e7edd7c24246.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13(19.11.5.20)

**Device details:** 
iPhone

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by anthonypkeane** [comment]
Linked to: #1660

**Comment by srirambv** [comment]
* Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69360561-ccbfd200-0c58-11ea-8d09-0ae3a229fdef.png)
* Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69360540-c16ca680-0c58-11ea-8eb9-fff34e2f039a.png)
* Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69360768-1f998980-0c59-11ea-9616-f82840331d87.png)
* Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69360551-c6c9f100-0c58-11ea-9a55-f48dc114a704.png)
* Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69360522-bade2f00-0c58-11ea-90f2-6318ab405ba7.png)
