### ISSUE TITLE
Restoring a wallet does not Enroll the user

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#1911]
### Description: 
When restoring a wallet to an existing wallet, the `isDeviceEnrolled` function returns true that the device is already enrolled because in order to restore a wallet, you must have enrolled previously with a dummy/fake wallet in the first place.

### Steps to Reproduce 
  1. Create a wallet (the dummy/fake wallet)
  2. Restore to existing wallet
  3. Claim a grant.

**Actual result:** 
1. Device is already enrolled from step 1 with paymentId from step 1.. but should be re-enrolled with paymentId from step 2 upon restoring.
2. Claim will fail.

**Expected result:**
1. Claim succeeds.
2. Device re-enrolled.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Extremely Often.

**Brave Version:** 
1.3.x

**Device details:** 
Any Device.

**Website problems only:**
- did you check with Brave Shields down? (N/A)
- did you check in Safari/Firefox (WkWebView-based browsers)?  (N/A)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.19.15)
* Verified restoring a wallet still allows you to claim grants 
------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.19.15)
* Verified restoring a wallet still allows you to claim grants 
------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.19.15)
* Verified restoring a wallet still allows you to claim grants 
------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.19.15)
* Verified restoring a wallet still allows you to claim grants 
------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.19.15)
* Verified restoring a wallet still allows you to claim grants 
------
Logged #1998 for not able to claim grant on the first attempt after restoring the wallet
