### ISSUE TITLE
Investigate issue with Ad Grant claim notification

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1914]
### Description: 
It seems like users are not getting notified about their ad grant. 

Pls investigate. 

Internal Chat: https://bravesoftware.slack.com/archives/CKA10H3AS/p1573053663387500

**Comment by kylehickinson** [comment]
Tested with Jimmy + Michael and it worked without issue on staging:

![IMG_8CD8CA86E8CF-1](https://user-images.githubusercontent.com/529104/68709468-bed8c580-0563-11ea-9b1e-99ff902df5af.jpeg)
![IMG_9C35A88A33F1-1](https://user-images.githubusercontent.com/529104/68709471-c13b1f80-0563-11ea-8731-111e39b63f8d.jpeg)
![IMG_9C35A88A33F1-1 2](https://user-images.githubusercontent.com/529104/68709473-c26c4c80-0563-11ea-80ef-1db6a7f987e4.jpeg)

**Comment by kylehickinson** [comment]
Will investigate separately with @mandar-brave
