### ISSUE TITLE
Don't show claim UI if user cannot get a grant

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1915]
### Description: 
Don't show claim UI in the panel and in settings if user cannot get a grant.

![Claim.jpg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/7798d724-ef02-4882-85fa-1112c5eeae27)

**Comment by kylehickinson** [comment]
Needs information:
- What is "cannot get a grant"?

May need to discuss internally

**Comment by anthonypkeane** [comment]
More here: https://bravesoftware.slack.com/archives/CKA10H3AS/p1573515342442500

**Comment by mandar-brave** [comment]
@kylehickinson rate limitations need to be observed; why show a grant user can never claim. The bug may be something else. cc @NejcZdovc

**Comment by kylehickinson** [comment]
"Cannot claim a grant": Enrolment fails for some reason, therefore cannot claim any grants until re-enrollment is available. Requires server update to know when re-enrollment is available.

**Comment by kylehickinson** [comment]
Blocked until we have an update on server end to make this possible

**Comment by nvonpentz** [comment]
Tracking server side changes here https://github.com/brave-intl/bat-reputation/issues/89

**Comment by kylehickinson** [comment]
Closing as stale, can be re-opened once necessary changes on server side are done
