### ISSUE TITLE
DDG recognized us as Firefox

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1917]
### Description: 
DDG thinks we’re Firefox

Internal Chat: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1573064653227500

![Screenshot_20191106-110239.png](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/6d22690b-6b91-4d2f-93c0-375acd968c91)

##

**Comment by iccub** [comment]
we're Safari now
