### ISSUE TITLE
HTML tags should be removed when classifying a page for Brave ads

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#1918]
### Description: 
HTML tags should be removed when classifying a page for Brave ads otherwise the classifier will likely return "Technology & Computing-Software"

### Steps to Reproduce 
  1. Enable Brave Rewards
  2. Visit www.law.com

**Actual result:** 
Page is classified as "technology & computing-software"

**Expected result:**
Page should be classified as "law-law"

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Search for "Successfully classified page at" in the logs to see the page classification

**Comment by iccub** [comment]
Only stripping html tags is enough, or do we need to do more like extracting only `<body>` contents or removing css/script contents?

**Comment by kylehickinson** [comment]
We're going to just use `document.body.innerText` as it provides the most accurate and quickest solution

**Comment by tmancey** [comment]
I can confirm that tests @kylehickinson showed me using `document.body.innerText` are as good as the desktop page classification

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.22.15)
* Verified page classification is done correctly
[iPhone XRlog.txt](https://github.com/brave/brave-ios/files/3887982/iPhone.XRlog.txt)
-------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.22.15)
* Verified page classification is done correctly
[iPhone7+log.txt](https://github.com/brave/brave-ios/files/3888000/iPhone7%2Blog.txt)
-------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.22.15)
* Verified page classification is done correctly
[iPhone6Log.txt](https://github.com/brave/brave-ios/files/3888014/iPhone6Log.txt)
-------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.22.15)
* Verified page classification is done correctly
[iPad13log.txt](https://github.com/brave/brave-ios/files/3887986/iPad13log.txt)
-------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.22.15)
* Verified page classification is done correctly
[iPad12Log.txt](https://github.com/brave/brave-ios/files/3887983/iPad12Log.txt)
