### ISSUE TITLE
CHANGELOG Release Notes for 1.13

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1921]
- Implement Brave Rewards and Ads. ([#1920](https://github.com/brave/brave-ios/issues/1920))
- Added new preview menu on iOS13. ([#1499](https://github.com/brave/brave-ios/issues/1499))
- Added bookmarklet support. ([#1119](https://github.com/brave/brave-ios/issues/1119))
- Updated new tab stats text size and colours to match desktop. ([#1641](https://github.com/brave/brave-ios/issues/1641))
- Updated StartPage icon. ([#1598](https://github.com/brave/brave-ios/issues/1598))
- Fixed wrong device name being shown when tapped on Sync devices. ([#1587](https://github.com/brave/brave-ios/issues/1587))
- Fixed readablity of website/tab names on dark mode. ([#1551](https://github.com/brave/brave-ios/issues/1551))
- Fixed button border on Shields that were too light on light theme. ([#1548](https://github.com/brave/brave-ios/issues/1548))
- Fixed missing long press context menu on image search results. ([#1547](https://github.com/brave/brave-ios/issues/1547))
- Fixed "Download Cancelled" visibility on iOS 12 devices. ([#1516](https://github.com/brave/brave-ios/issues/1516))
- Removed "www" from the URL bar when visiting a site. ([#1533](https://github.com/brave/brave-ios/issues/1533))
- Removed Alexa top sites recommendations as search suggestions. ([#868](https://github.com/brave/brave-ios/issues/868))
- Removed URL autocomplete while editing an existing URL. ([#807](https://github.com/brave/brave-ios/issues/807))

**Comment by iccub** [comment]
Can this be closed @srirambv?

**Comment by srirambv** [comment]
Yes should have been closed with #1924.
