### ISSUE TITLE
Implement simpler Shield Panel design on iOS

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1923]
## Description

Implement the simpler shield panel design

## Designs
![shields 1](https://user-images.githubusercontent.com/2388823/73316295-5c4ca880-41e7-11ea-845a-e0e4f698b796.jpg)

Tapping the help icon will show more information about Brave Shields:

![shields 2](https://user-images.githubusercontent.com/2388823/73316296-5c4ca880-41e7-11ea-9664-a3f6bd743c78.jpg)

Advanced site-specific controls are available in an expand/collapse section, which persists across sites. So if the user expanded Advanced controls on one site, it will still be expanded when they open Shields on a different site.

![shields 3](https://user-images.githubusercontent.com/2388823/74183046-06b9c800-4bf9-11ea-8632-0b7e5d5e8ea8.jpg)

Label changes:

- "Block Ads & Tracking" becomes "Block cross-site trackers"
- "HTTPS Everywhere" becomes "Upgrade connections to HTTPS"
- "Block Phishing and Malware" is moved to "Brave Shields & Privacy" page in global app settings

Tapping "Change global Shields defaults" under Advanced Controls deeplinks the user to the "Brave Shields & Privacy" page pre-scrolled to the "BRAVE SHIELDS GLOBAL DEFAULTS" section:

![Settings 2](https://user-images.githubusercontent.com/2388823/77212138-570f2a00-6ac3-11ea-99f0-714398341d1b.png)

When Brave Shields is down (whether Advanced controls is expanded or not), users can report a broken site by tapping "Report a broken site"

![shields webcompat 1](https://user-images.githubusercontent.com/2388823/73316327-6a022e00-41e7-11ea-9a19-0aa27a1754a6.jpg)
![shields webcompat 2](https://user-images.githubusercontent.com/2388823/73316328-6a9ac480-41e7-11ea-8fc8-05d759f60039.jpg)

The confirmation message should dismiss on its own after 1s if the user doesn't tap out first:

![shields webcompat 3](https://user-images.githubusercontent.com/2388823/73316329-6a9ac480-41e7-11ea-9dac-b0480cae2d9e.jpg)

### Dark theme
Dark theme is supported. Text, toggles, buttons, links, and icons have lighter colors:

![dark theme shields 1](https://user-images.githubusercontent.com/2388823/73315514-29a1b080-41e5-11ea-9f99-20a67801c9e3.jpg)
![dark theme shields 2](https://user-images.githubusercontent.com/2388823/73315516-29a1b080-41e5-11ea-9d1b-eacbc5600b22.jpg)
![dark theme shields 3](https://user-images.githubusercontent.com/2388823/73319451-43e18b80-41f1-11ea-9849-fbd3bdcbbc06.jpg)
![dark theme shields 4](https://user-images.githubusercontent.com/2388823/73315518-2a3a4700-41e5-11ea-9268-6efbf6487e7b.jpg)
![dark theme shields 5](https://user-images.githubusercontent.com/2388823/73315519-2a3a4700-41e5-11ea-9839-8be293ac5c76.jpg)
![dark theme shields 6](https://user-images.githubusercontent.com/2388823/73315520-2a3a4700-41e5-11ea-8f88-0e8d631b9d4b.jpg)

### Landscape mode
This works the same as currently.

![shields landscape](https://user-images.githubusercontent.com/2388823/73316286-58b92180-41e7-11ea-815f-8a6f6111dfcc.png)

### Settings
Since Brave Shields global defaults now has its own page in app settings, make some minor organizational changes to main app settings page as well:

![Settings 1](https://user-images.githubusercontent.com/2388823/77212153-5ecece80-6ac3-11ea-82e6-2f44b969bf81.png)

![settings refresh overview](https://user-images.githubusercontent.com/2388823/77212159-62625580-6ac3-11ea-916e-7e77ee9cada0.png)

### Interaction finesse
The expand/collapse Advanced controls should animate content in:

![shields expand collapse](https://user-images.githubusercontent.com/2388823/73315409-e2b3bb00-41e4-11ea-9c4a-ae022a7c972d.gif)

Breakdown: Grow white panel 0.2s, then content fades in Y+10 0.3s

Also, use existing iOS functionality to slide content in from left for each new view.

To add delight to the experience as well as a fun touch complimenting the oversized toggle, implement new color gradient when the toggle is ON:

![fabtoggle](https://user-images.githubusercontent.com/2388823/74183364-ad05cd80-4bf9-11ea-8138-dbe348e4300c.gif)

it's a loop with 2ms between each color state + easy ease:
linear-gradient(120deg, rgba(255,167,59,1) 0%, rgba(255,118,84,1) 100%);
linear-gradient(120deg, rgba(255,118,84,1) 0%, rgba(251,84,43,1) 100%);
linear-gradient(120deg, rgba(251,84,43,1) 0%, rgba(247,36,28,1) 100%);
linear-gradient(120deg, rgba(247,36,28,1) 0%, rgba(252,79,130,1) 100%);
linear-gradient(120deg, rgba(252,79,130,1) 0%, rgba(255,167,59,1) 100%);
linear-gradient(120deg, rgba(255,167,59,1) 0%, rgba(255,118,84,1) 100%);
#FFA73B :arrow_right: #FF7654 :arrow_right: #FB542B :arrow_right: #F7241C :arrow_right: #FC4F82 :arrow_right: #FFA73B

[fabtoggle.mov.zip](https://github.com/brave/brave-ios/files/4182705/fabtoggle.mov.zip)

## User Flow
![prototype](https://user-images.githubusercontent.com/2388823/73315628-6ec5e280-41e5-11ea-8300-d94cc066558f.gif)

Zipped .mov: 
[prototype.zip](https://github.com/brave/brave-ios/files/4125423/prototype.zip)

### Notes
Shields will still show the "Report a broken site" button when Shields is down even if they have already reported that site.

## Assets
Figma: https://www.figma.com/file/aiHUCYczQPYP1mtGTOZ5NJ/Sketchimport-ios-shields?node-id=0%3A231

[icons.zip](https://github.com/brave/brave-ios/files/4125506/icons.zip)
[settings icons.zip](https://github.com/brave/brave-ios/files/4187837/settings.icons.zip)

**Comment by karenkliu** [comment]
working on this design currently, will update the issue here when done

**Comment by ghost** [comment]
Bro imagine how obnoxious it would be to have to click "Advanced view" to make any serious changes for every website. We should let people decide if they want Simple or Advanced, not regress to using only Simple.

**Comment by karenkliu** [comment]
@Calefornia We will always support both views since we know there are both types of users; there will be an option set your preferred default view in settings.

**Comment by karenkliu** [comment]
Designs added!

**Comment by anthonypkeane** [comment]
Thanks @karenkliu 
Cookie per domain is not supported now so that can be removed when implementing the design.

cc @snyderp as an FYI

**Comment by kylehickinson** [comment]
@anthonypkeane @karenkliu 

- Given that cookies isn't a shield, do we still want to move it from under Privacy to Shields (in settings)?
- Is there a spec/documentation somewhere for usage of the report a site functionality?

**Comment by anthonypkeane** [comment]
Part 1: Correct, cookies control per domain won't be in the shield but will remain in settings. @karenkliu is working on tidying up those also. See "settings" above

Part 2: https://github.com/brave/vault-updater/blob/master/src/controllers/webcompat.js#L9

**Comment by karenkliu** [comment]
@kylehickinson  FYI we still have a couple things to finalize in Settings:
- do we need block phishing/malware and if so where does it go
- do we need "Block Popups" and if so where does it go

But all the other screens aside from Settings are ready. :)

**Comment by jhreis** [comment]
@karenkliu we can't really answer those, as they are sec requirements, so as far as we know how, they are required.
- Blocking Phishing / malware is a shield, so it should probably go in the shields panel.
- is a global setting, so probably just in the settings page.

**Comment by jhreis** [comment]
Love the settings cleanup, huge improvements. 

I think we should hold off on the timed deletion of private browsing data though, I think it would be worth having more discussions how this applies to private mode and how they two are pseudo-related. Maybe we can simplify the browsing 'modes' with something more mature like the custom settings the screenshot shows.

**Comment by karenkliu** [comment]
@kylehickinson @jhreis Settings designs finalized and assets uploaded. 

- We will hold off on the timed deletion of private browsing data. 
- "Block Popups" goes under "Other Privacy Settings"
- "Block Phishing/Malware goes under "Other Privacy Settings"

lmk if you need anything else!

**Comment by kylehickinson** [comment]
@karenkliu The phishing and malware block is a domain specific shield, we'd actually want to have it in the shields panel as said above here: https://github.com/brave/brave-ios/issues/1923#issuecomment-584375215

Are we saying we're dumping this shield?

**Comment by karenkliu** [comment]
cc @tomlowenthal mentioned it should be in global settings.  Tom, what do you want to do with this one?

**Comment by tildelowengrimm** [comment]
Yes, phishing and malware protection isn't part of Shields; just because something technically can be done on a per-domain basis doesn't mean it should be or that it should be part of Shields. That feature isn't part of Shields on desktop, for instance — Google Safe Browsing is just a global preference, even though I'm sure we _could_ configure it per domain.

**Comment by kylehickinson** [comment]
Okay cool, just clarifying that we are removing it shields panel and its per-domain setting

**Comment by karenkliu** [comment]
@kylehickinson  Update: Add some description text to the "Block Phishing/Malware" item so it looks like this: 
![Settings 2](https://user-images.githubusercontent.com/2388823/74569222-bca15100-4f2e-11ea-9200-8c1edc9ee76a.png)

Abstract updated

**Comment by hennrynusasatria** [comment]
I hope that @jhreis or @anthonypkeane can still look at this feature request.

Thank you.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.0.1 running 1.21(20.10.15.13)

<details>
<summary> Verified the shields is as per design</summary>

<details>
<summary> Light theme</summary>

Default shields | Advance controls | Shields Off | Report broken site | Report site confirmation | About shields | Shields global settings  | Clear Private data & Other Privacy settings 
-- | -- | -- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/96582731-a0329100-12d3-11eb-863a-9d20cd1dca8a.png) | ![image](https://user-images.githubusercontent.com/17010094/96582750-a9bbf900-12d3-11eb-9991-8a7fee74cc48.png) | ![image](https://user-images.githubusercontent.com/17010094/96582774-b0e30700-12d3-11eb-9524-8dc4ef7de0b7.png) | ![image](https://user-images.githubusercontent.com/17010094/96582791-b5a7bb00-12d3-11eb-94c8-ab92e750a3fc.png) | ![image](https://user-images.githubusercontent.com/17010094/96582808-bb050580-12d3-11eb-8059-c295760e7bdd.png) | ![image](https://user-images.githubusercontent.com/17010094/96582825-bfc9b980-12d3-11eb-9c61-6cf23de18ad6.png) | ![image](https://user-images.githubusercontent.com/17010094/96582836-c3f5d700-12d3-11eb-9068-59b1df0c99fc.png) | ![image](https://user-images.githubusercontent.com/17010094/96582855-c821f480-12d3-11eb-8eca-f0d9619ef273.png)

</details>
<details>
<summary>Dark Theme</summary>

Default shields | Advance controls | Shields Off | Report broken site | Report site confirmation | About shields | Shields global settings  | Clear Private data & Other Privacy settings 
-- | -- | -- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/96582902-d7a13d80-12d3-11eb-944a-cd70dfbfed5c.png) | ![image](https://user-images.githubusercontent.com/17010094/96582915-dd971e80-12d3-11eb-8f7e-91df311ad3eb.png) | ![image](https://user-images.githubusercontent.com/17010094/96582964-ee479480-12d3-11eb-990c-37759c5a6048.png) | ![image](https://user-images.githubusercontent.com/17010094/96582982-f4d60c00-12d3-11eb-9d1c-c4a412d40b50.png) | ![image](https://user-images.githubusercontent.com/17010094/96583001-fb648380-12d3-11eb-8c5c-1751f91ad92b.png) | ![image](https://user-images.githubusercontent.com/17010094/96583019-015a6480-12d4-11eb-8bda-995afcfd1a5c.png) | ![image](https://user-images.githubusercontent.com/17010094/96583033-091a0900-12d4-11eb-88ca-e0be1c0752a7.png) | ![image](https://user-images.githubusercontent.com/17010094/96583064-10411700-12d4-11eb-9a02-52cb3bfb2b00.png)

</details>
</details>

- Verified upgrading to new version retains old shields setting 
- Verified shields work as expected in landscape mode 
![image](https://user-images.githubusercontent.com/17010094/96584502-3798e380-12d6-11eb-9657-0e5840befa23.png)
- Verified settings has the new look and shields & privacy is the first option 
  <img width=500 src=https://user-images.githubusercontent.com/17010094/96585049-f523d680-12d6-11eb-9403-9825cf72ee17.png>

- Verified selecting shields and privacy opens up global shields settings 
- Verified clear data presents a confirmation modal 
  <img width=500 src=https://user-images.githubusercontent.com/17010094/96585353-64012f80-12d7-11eb-9867-b64042c1a20c.png>

- Verified Report broken site message is dismissed on its own after 1second of showing the message
- Verified shields view (advanced/collapsed) is retained across tabs and isn't site specific
- Verified shields settings is retained across app launches
- Verified clearing all browser data resets site specific shields settings unless bookmarked (https://github.com/brave/brave-ios/issues/2975#issuecomment-712277986)

-------------------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.15.13)

<details>
<summary> Verified the shields is as per design</summary>

<details>
<summary> Light theme</summary>

Default shields | Advance controls | Shields Off | Report broken site | Report site confirmation | About shields | Shields global settings  | Clear Private data & Other Privacy settings 
-- | -- | -- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/96589719-0ff94980-12dd-11eb-93e9-ed90e796299a.png) | ![image](https://user-images.githubusercontent.com/17010094/96589731-14bdfd80-12dd-11eb-9655-8d05c3396be1.png) | ![image](https://user-images.githubusercontent.com/17010094/96589758-1c7da200-12dd-11eb-8f78-b2c3a778666a.png) | ![image](https://user-images.githubusercontent.com/17010094/96589765-20a9bf80-12dd-11eb-82af-0180d6f2a63d.png) | ![image](https://user-images.githubusercontent.com/17010094/96589777-243d4680-12dd-11eb-81ec-99493c9406cf.png) | ![image](https://user-images.githubusercontent.com/17010094/96589787-27d0cd80-12dd-11eb-8d27-07a764eb4a52.png) | ![image](https://user-images.githubusercontent.com/17010094/96589801-2c958180-12dd-11eb-82fc-a0e1039ab156.png) | ![image](https://user-images.githubusercontent.com/17010094/96589821-30c19f00-12dd-11eb-9fc7-47092ec3e029.png)

</details>
<details>
<summary>Dark Theme</summary>

Default shields | Advance controls | Shields Off | Report broken site | Report site confirmation | About shields | Shields global settings  | Clear Private data & Other Privacy settings 
-- | -- | -- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/96589864-3d45f780-12dd-11eb-807e-ce39b4b9d043.png) | ![image](https://user-images.githubusercontent.com/17010094/96589873-40d97e80-12dd-11eb-8e17-0581af2e0d81.png) | ![image](https://user-images.githubusercontent.com/17010094/96589890-459e3280-12dd-11eb-9122-6ca485f3d571.png) | ![image](https://user-images.githubusercontent.com/17010094/96589904-4afb7d00-12dd-11eb-9522-eeece4d868bf.png) | ![image](https://user-images.githubusercontent.com/17010094/96589923-50f15e00-12dd-11eb-9262-30c3b6846d9c.png) | ![image](https://user-images.githubusercontent.com/17010094/96589945-551d7b80-12dd-11eb-94ad-f20d79b7e736.png) | ![image](https://user-images.githubusercontent.com/17010094/96589959-59499900-12dd-11eb-9010-9497a109354e.png) | ![image](https://user-images.githubusercontent.com/17010094/96589971-5cdd2000-12dd-11eb-959e-7a0d14ca9aab.png)

</details>
</details>

- Verified upgrading to new version retains old shields setting 
- Verified shields work as expected in landscape mode 
![image](https://user-images.githubusercontent.com/17010094/96590017-69617880-12dd-11eb-8416-ac864785b773.png)

- Verified settings has the new look and shields & privacy is the first option 
  <img width=500 src=https://user-images.githubusercontent.com/17010094/96590032-6d8d9600-12dd-11eb-8534-27e74825d4c7.png>

- Verified selecting shields and privacy opens up global shields settings 
- Verified clear data presents a confirmation modal 
  <img width=500 src=https://user-images.githubusercontent.com/17010094/96590064-74b4a400-12dd-11eb-8b28-324212b3658f.png>

- Verified Report broken site message is dismissed on its own after 1second of showing the message
- Verified shields view (advanced/collapsed) is retained across tabs and isn't site specific
- Verified shields settings is retained across app launches
- Verified clearing all browser data resets site-specific shields settings unless bookmarked (https://github.com/brave/brave-ios/issues/2975#issuecomment-712277986)
---------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.10.15.13)

<details>
<summary> Verified the shields is as per design</summary>

<details>
<summary> Light theme</summary>

Default shields | Advance controls | Shields Off | Report broken site | Report site confirmation | About shields | Shields global settings  | Clear Private data & Other Privacy settings 
-- | -- | -- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/96599903-4b4d4580-12e8-11eb-9d43-db3449e1c34d.png) | ![image](https://user-images.githubusercontent.com/17010094/96599914-4e483600-12e8-11eb-994b-ca1536650fe5.png) | ![image](https://user-images.githubusercontent.com/17010094/96599926-50aa9000-12e8-11eb-9588-4a3136817646.png) | ![image](https://user-images.githubusercontent.com/17010094/96599962-5b652500-12e8-11eb-9697-764a6f92740e.png) | ![image](https://user-images.githubusercontent.com/17010094/96599989-61f39c80-12e8-11eb-833e-7de8ba05ca99.png) | ![image](https://user-images.githubusercontent.com/17010094/96600012-6750e700-12e8-11eb-9649-32385cd5563f.png) | ![image](https://user-images.githubusercontent.com/17010094/96600368-c6aef700-12e8-11eb-94db-21b0bd7f3120.png) | ![image](https://user-images.githubusercontent.com/17010094/96600392-ca427e00-12e8-11eb-89dd-ce768c07ecb7.png)

</details>
<details>
<summary>Dark Theme</summary>

Default shields | Advance controls | Shields Off | Report broken site | Report site confirmation | About shields | Shields global settings  | Clear Private data & Other Privacy settings 
-- | -- | -- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/96600433-d62e4000-12e8-11eb-9913-cb4099393c78.png) | ![image](https://user-images.githubusercontent.com/17010094/96600448-d8909a00-12e8-11eb-9ff1-eaa27c872cb2.png) | ![image](https://user-images.githubusercontent.com/17010094/96600468-de867b00-12e8-11eb-81d3-b4e040beb6f2.png) | ![image](https://user-images.githubusercontent.com/17010094/96600477-e2b29880-12e8-11eb-9295-3101dd6d3332.png) | ![image](https://user-images.githubusercontent.com/17010094/96600510-ea723d00-12e8-11eb-9637-00259d002d64.png) | ![image](https://user-images.githubusercontent.com/17010094/96600532-ef36f100-12e8-11eb-9808-06ec9b160688.png) | ![image](https://user-images.githubusercontent.com/17010094/96600550-f52cd200-12e8-11eb-803b-10a710877d47.png) | ![image](https://user-images.githubusercontent.com/17010094/96600560-f827c280-12e8-11eb-971a-494a457d06d7.png)


</details>
</details>

- Verified upgrading to new version retains old shields setting 
- Verified shields work as expected in landscape mode 
![image](https://user-images.githubusercontent.com/17010094/96600037-6d46c800-12e8-11eb-9188-9efd2e684abe.png)

- Verified settings has the new look and shields & privacy is the first option 
  <img width=500 src=https://user-images.githubusercontent.com/17010094/96600651-0fff4680-12e9-11eb-92b7-73314be63011.png>

- Verified selecting shields and privacy opens up global shields settings 
- Verified clear data presents a confirmation modal 
  <img width=500 src=https://user-images.githubusercontent.com/17010094/96600738-2ad1bb00-12e9-11eb-820a-305d42c4f355.png>

- Verified Report broken site message is dismissed on its own after 1second of showing the message
- Verified shields view (advanced/collapsed) is retained across tabs and isn't site specific
- Verified shields settings is retained across app launches
- Verified clearing all browser data resets site-specific shields settings unless bookmarked (https://github.com/brave/brave-ios/issues/2975#issuecomment-712277986)
