### ISSUE TITLE
Provide an Option to Automatically Clear Browsing History 

### ISSUE THREAD

**Issue by noprodev** [brave/brave-ios#1934]
## Problem Description 
Currently, there seems to be no way to automatically and periodically clear browsing history.
This feature is becoming of a privacy oriented browser.

## Feature Overview 
Provide an option in settings / clear private data to periodically, automatically clear browsing history, such as is present in some other browsers.

## User Experience 

   1. Go to settings / clear private data
   2. Select "Clear browsing history every ..."
   3. Choose from options e.g. "End of session", "Every day", "Every month" or the likes

**Comment by bsclifton** [comment]
Similar to desktop's Clear browser data on exit:
![image](https://user-images.githubusercontent.com/4733304/101517680-df757980-3935-11eb-8264-11c851e46bf7.png)

**Comment by bsclifton** [comment]
Related https://github.com/brave/brave-ios/issues/893

**Comment by Brave-Matt** [comment]
This is requested fairly frequently -- @anthonypkeane is there a particular reason we don't have an open issue for this ourselves? https://community.brave.com/t/address-bar-space/210525/4

**Comment by jamesmudgett** [comment]
Product spec in-progress https://bravesoftware.slack.com/archives/G01F4JUNXAQ/p1616518606090900
