### ISSUE TITLE
Implement P3A on iOS

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1938]
### Description: 

UI can be found 

Onboarding:
https://www.figma.com/file/irDJRP35FUwsRu60Wp9fM6/iOS-onboarding?node-id=3321%3A54735

Settings:
https://www.figma.com/file/SLFLpMd7F7Tu58qGBdcUQG/iOS-Settings?node-id=1873%3A15338

Security Ticket: https://github.com/brave/security/issues/1088

**Comment by bsclifton** [comment]
From https://github.com/brave/brave-browser/issues/12723 (Android version of P3A onboarding; linked from https://github.com/brave/brave-browser/issues/6688)

We have this on Android for onboarding:
**Screen 1**
<img src="https://user-images.githubusercontent.com/4733304/197595131-870fbbc2-98b1-4b25-9a10-c880b2158bad.png" width="250px">

**Screen 2**
<img src="https://user-images.githubusercontent.com/4733304/197595217-08ea75d9-3ff2-4475-aa13-d86e811ab07c.png" width="250px">

**Comment by bradleyrichter** [comment]
Yes, please implement the new onboarding screen on iOS with the same choices and strings.

**Comment by bsclifton** [comment]
cc: @kylehickinson ^^

**Comment by anthonypkeane** [comment]
We don't have diagnostic reporting on iOS so the 1st option isn't necessary. 

@Sam-Sibley I saw your Desktop design and it seems to be a little nicer vs what we have on Android. Can we use an iteration of that on iOS? 

Thanks

**Comment by kylehickinson** [comment]
Also would be good to know what we want to do for existing users design and implementation wise

**Comment by bradleyrichter** [comment]
image for reference to comment above:
<img width="664" alt="image" src="https://user-images.githubusercontent.com/13509546/197658043-ba822440-2889-4831-b049-be373f04ff5b.png">

**Comment by anthonypkeane** [comment]
There are 3 items we need for this issue

1. The UI for P3A during onboarding
2. A flow (and UI) for existing users
3. A setting to enable/disable P3A



_____

1. @Sam-Sibley has a design and will share it here soon

2. We can show the above card in 1 to all existing users on upgrade and first launch. 

3. For the Setting

Title: Allow Privacy-Preserving Product Analytics (P3A)
Subtitle: Anonymized P3A info helps Brave estimate overall usage and ensure we're improving popular features

Please place this setting in Brave Shields & Privacy and under the Privacy Hub setting. 

@Sam-Sibley pls confirm if this works okay

**Comment by anthonypkeane** [comment]
> 1. @Sam-Sibley has a design and will share it here soon
> 2. We can show the above card in 1 to all existing users on upgrade and first launch.
> 3. For the Setting
> 
> Title: Allow Privacy-Preserving Product Analytics (P3A) Subtitle: Anonymized P3A info helps Brave estimate overall usage and ensure we're improving popular features
> 
> Please place this setting in Brave Shields & Privacy and under the Privacy Hub setting.
> 
> @Sam-Sibley pls confirm if this works okay


--> There are a few updates to the above. Sam will post the UI and flow shortly. Thanks

**Comment by anthonypkeane** [comment]
**Settings UI:** https://www.figma.com/file/SLFLpMd7F7Tu58qGBdcUQG/iOS-Settings?node-id=1873%3A15338

**Onboarding:** https://www.figma.com/file/irDJRP35FUwsRu60Wp9fM6/iOS-onboarding?node-id=3321%3A54735

P3A card to be shows after Set Default (but before the user can enter a URL
For existing, on first launch after upgrade show the card. 



<img width="750" alt="Screen Shot 2022-10-28 at 10 37 22 AM" src="https://user-images.githubusercontent.com/7606853/198698539-158b3c57-0eae-469f-a931-79be5d2a886b.png">
(Note: UI is correct on Figma not on this image, this image is to detail the position of the P3A card)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPhone 8 iOS version 16.1.1` running `Brave 1.46 (22.12.1.14)`

- Logged https://github.com/brave/brave-ios/issues/6536
- Logged https://github.com/brave/brave-ios/issues/6537

**_1. Verify P3A card/slide in the onboarding_** 

_New user_

- Confirmed that `P3A Slide` is shown in the onbrading after `Set Default` card/slide
- Confirmed that P3A modal text is matching with the Figma spec
- Confirmed that P3A switch can be turned off/on 
- Confirmed updated P3A switch state is retained in the P3A settings under `Brave Shields & Privacy`
- Switch state is not retained after the browser restart, logged https://github.com/brave/brave-ios/issues/6537
- Confirmed that controls inside the P3A modal works as expected
- Confirmed that click on the learn more link opens up the `support.brave.com` page

**`Light mode`** | **`Dark mode`**
-------------------|--------------
![IMG_3220](https://user-images.githubusercontent.com/38657976/205233098-0a36772b-6eaa-41e0-84f1-d1edf88bc982.PNG) | ![IMG_3222](https://user-images.githubusercontent.com/38657976/205233145-d067119e-13c9-43ff-923e-5cfcbaeb0d80.PNG)


_Existing user_

- Confirmed that `P3A Slide` is shown on the NTP on the first launch in an upgraded profile
- Confirmed that P3A modal text is matching with the Figma spec
- Confirmed that P3A switch can be turned off/on
- Confirmed updated P3A switch state is retained in the P3A settings under `Brave Shields & Privacy`
- Switch state is not retained after the browser restart, logged https://github.com/brave/brave-ios/issues/6537
- Confirmed that controls inside the P3A modal works as expected
- Confirmed that click on the learn more link opens up the `support.brave.com` page

**`Light mode`** | **`Dark mode`**
-------------------|--------------
![IMG_3225](https://user-images.githubusercontent.com/38657976/205243668-3e682a6e-846a-43e0-a0e5-671d8a0ce75a.PNG) | ![IMG_3226](https://user-images.githubusercontent.com/38657976/205243713-0864f729-538b-414a-beb7-c9b2555f03bc.PNG)


**_2. Verify P3A settings_** 

- Confirmed that P3A settings `Allow Privacy-Preserving Product Analytics (P3A)` is placed under `Brave Shields & Privacy` and under the Other Privacy Settings section
- Confirmed that the Subtitle: `Anonymized P3A info helps Brave estimate overall usage and ensure we're improving popular features` is shown below the P3A settings
- Confirmed that P3A switch can be turned off/on
- Confirmed that P3A settings `Allow Privacy-Preserving Product Analytics (P3A)` is placed in both clean and upgrded profile of 1.46.x

**`Light mode`** | **`Dark mode`**
-------------------|--------------
![IMG_3227](https://user-images.githubusercontent.com/38657976/205253358-4f6e2c94-37e4-4a94-8890-0843e0585361.PNG) | ![IMG_3228](https://user-images.githubusercontent.com/38657976/205253397-11cf62fd-18f4-4f81-96d4-117f4806f3cf.PNG)

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPad 7th Generation version 15.2` running `Brave 1.46 (22.12.7.22)`


**_1. Verify P3A card/slide in the onboarding_** 

_New user_

- Confirmed that `P3A Slide` is shown in the onbrading after `Set Default` card/slide
- Confirmed that P3A modal text is matching with the Figma spec
- Confirmed that P3A switch can be turned off/on 
- Confirmed updated P3A switch state is retained in the P3A settings under `Brave Shields & Privacy`
- Switch state is not retained after the browser restart, logged https://github.com/brave/brave-ios/issues/6537
- Confirmed that controls inside the P3A modal works as expected
- Confirmed that click on the learn more link opens up the `support.brave.com` page

**`Light mode`** | **`Dark mode`**
-------------------|--------------
![IMG_0301](https://user-images.githubusercontent.com/38657976/206466825-07bd418b-5997-491e-b1ee-0f561cd1701f.PNG) | ![IMG_0302](https://user-images.githubusercontent.com/38657976/206466865-708cb0c1-8d3a-466f-9f32-7d3fcc07caa4.PNG)



_Existing user_

- Confirmed that `P3A Slide` is shown on the NTP on the first launch in an upgraded profile
- Confirmed that P3A modal text is matching with the Figma spec
- Confirmed that P3A switch can be turned off/on
- Confirmed updated P3A switch state is retained in the P3A settings under `Brave Shields & Privacy`
- Switch state is not retained after the browser restart, logged https://github.com/brave/brave-ios/issues/6537
- Confirmed that controls inside the P3A modal works as expected
- Confirmed that click on the learn more link opens up the `support.brave.com` page

**`Light mode`** | **`Dark mode`**
-------------------|--------------
![IMG_0304](https://user-images.githubusercontent.com/38657976/206466985-93fbac85-25fe-4618-acdd-fd2aab8fd821.PNG) | ![IMG_0303](https://user-images.githubusercontent.com/38657976/206467028-75dcf9c9-555a-4878-8a56-adac64e14517.PNG)


**_2. Verify P3A settings_** 

- Confirmed that P3A settings `Allow Privacy-Preserving Product Analytics (P3A)` is placed under `Brave Shields & Privacy` and under the Other Privacy Settings section
- Confirmed that the Subtitle: `Anonymized P3A info helps Brave estimate overall usage and ensure we're improving popular features` is shown below the P3A settings
- Confirmed that P3A switch can be turned off/on
- Confirmed that P3A settings `Allow Privacy-Preserving Product Analytics (P3A)` is placed in both clean and upgrded profile of 1.46.x

**`Light mode`** | **`Dark mode`**
-------------------|--------------
![IMG_0306](https://user-images.githubusercontent.com/38657976/206467788-c1fbcb4b-d661-4653-a0ce-a83896cb8e44.PNG) | ![IMG_0307](https://user-images.githubusercontent.com/38657976/206467847-e3b740b7-cfe6-4e51-9dca-f115d69289f8.PNG)
