### ISSUE TITLE
Cannot download app Pepo from their App Store button

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-ios#1941]
### Description: 
If I go to pepo.com on Brave iOS and hit the "Download on the App Store" button, it just opens a blank tab.  This opens up properly in Safari, and FWIW, when I tried another app install button, LetGo, it worked as expected

### Steps to Reproduce 
  1. Go to Pepo.com
  2. Tap "Download on the App Store" button
 

**Actual result:** 
Blank tab opens

**Expected result:**
Should go to the app store listing for the Pepo app

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.12.1 (19.09.20.23)

**Device details:** 
iPhoneX

**Website problems only:**
- did you check with Brave Shields down? **Yes**
- did you check in Safari/Firefox (WkWebView-based browsers)? **Yes**

**Comment by kylehickinson** [comment]
This happens when creating a new tab for any App Store URL. I.e. you can open a blank new tab and paste `https://apps.apple.com/us/app/brave-fast-privacy-web-browser/id1052879175` into the bar and nothing will happen. It should be opening a small popup at the bottom of the screen to ask you to go to the app store

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.20.19)
* Verified clicking on Download app opens a new tab and loads the AppStore page
* Verified clicking on `View in App Store` button opens up the snack bar to launch AppStore
---------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.20.19)
* Verified clicking on Download app opens a new tab and loads the AppStore page
* Verified clicking on `View in App Store` button opens up the snack bar to launch AppStore
---------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.20.19)
* Verified clicking on Download app opens a new tab and loads the AppStore page
* Verified clicking on `View in App Store` button opens up the snack bar to launch AppStore
---------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.20.19)
* Verified clicking on Download app opens a new tab and loads the AppStore page
* Verified switching to mobile view shows `View in App Store` button on the page
* Verified clicking on `View in App Store` button opens up the snack bar to launch AppStore
---------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.20.19)
* Verified clicking on Download app opens a new tab and loads the AppStore page
* Verified switching to mobile view shows `View in App Store` button on the page
* Verified clicking on `View in App Store` button opens up the snack bar to launch AppStore
