### ISSUE TITLE
Fix copy for ad grants notification

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1942]
Should be `Brave Ads | Your rewards from Ads are here!`

Icon should be `icn-ads` (ads megaphone icon)

![](https://user-images.githubusercontent.com/529104/68709468-bed8c580-0563-11ea-9b1e-99ff902df5af.jpeg)

**Comment by srirambv** [comment]
* Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69372876-955d1f80-0c70-11ea-8a25-0bc3d715c900.png)

* Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69372887-9a21d380-0c70-11ea-8706-bf02b5ceb833.png)

* Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69372912-a6a62c00-0c70-11ea-8a3e-bbb0e7d16e78.png)

* Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69372894-9e4df100-0c70-11ea-9b23-b153444ba1a2.png)

* Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69372900-a27a0e80-0c70-11ea-88d4-8c806cac9b9f.png)
