### ISSUE TITLE
Learn More button not opening a URL

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1944]
### Description: 

Tapping the learn more button is not opening a URL

![IMG_EFC26415F5CA-1.jpeg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/25af5d2c-2f2c-470a-815e-52c6d364ed4a)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.19.15)
* Verified `Learn more` for unverified publisher under rewards panel opens up [support article](https://brave.com/faq-rewards/#unclaimed-funds)
* Verified `Learn more` for unverified publisher under wallet summary opens up [support article](https://brave.com/faq-rewards/#unclaimed-funds) 
-------------------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.19.15)
* Verified `Learn more` for unverified publisher under rewards panel opens up [support article](https://brave.com/faq-rewards/#unclaimed-funds)
* Verified `Learn more` for unverified publisher under wallet summary opens up [support article](https://brave.com/faq-rewards/#unclaimed-funds) 
-------------------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.19.15)
* Verified `Learn more` for unverified publisher under rewards panel opens up [support article](https://brave.com/faq-rewards/#unclaimed-funds)
* Verified `Learn more` for unverified publisher under wallet summary opens up [support article](https://brave.com/faq-rewards/#unclaimed-funds) 
-------------------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.19.15)
* Verified `Learn more` for unverified publisher under rewards panel opens up [support article](https://brave.com/faq-rewards/#unclaimed-funds)
* Verified `Learn more`  for unverified publisher under wallet summary opens up [support article](https://brave.com/faq-rewards/#unclaimed-funds) 
-------------------
Verification passed on iPad Pro  with iOS 12.4 running 1.14(19.11.19.15)
* Verified `Learn more` for unverified publisher under rewards panel opens up [support article](https://brave.com/faq-rewards/#unclaimed-funds)
* Verified `Learn more`  for unverified publisherunder wallet summary opens up [support article](https://brave.com/faq-rewards/#unclaimed-funds)
