### ISSUE TITLE
Investigate possible issue with claiming a (ugp) grant

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1945]
### Description: 

Internal Chat: https://bravesoftware.slack.com/archives/CKA10H3AS/p1573596627463100

![Claim Grant.jpg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/a87c7040-3fc8-4c24-9d7c-57d3941f0d83)

**Comment by kylehickinson** [comment]
Can't reproduce but will keep an eye on it
