### ISSUE TITLE
BAP Change

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1949]
### Description: 
Please change BAP so that BAT or BAP is set on installation (first open) based on locale and cannot be changed, regardless or whether the user changes their locale.

**Comment by anthonypkeane** [comment]
@mattmcalister or @mandar-brave please confirm the above is correct before @kylehickinson implements

**Comment by kylehickinson** [comment]
Confirmed by @alexwykoff

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.19.15)
* Verified test plan from #1972 
* Verified switching regions doesn't change BAT -> BAP/BAT Points
* Verified token grants message don't change based on region change
--------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.19.15)
* Verified test plan from #1972 
* Verified switching regions doesn't change BAT -> BAP/BAT Points
* Verified token grants message don't change based on region change
--------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.19.15)
* Verified test plan from #1972 
* Verified switching regions doesn't change BAT -> BAP/BAT Points
* Verified token grants message don't change based on region change
--------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.19.15)
* Verified test plan from #1972 
* Verified switching regions doesn't change BAT -> BAP/BAT Points
* Verified token grants message don't change based on region change
--------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.19.15)
* Verified test plan from #1972 
* Verified switching regions doesn't change BAT -> BAP/BAT Points
* Verified token grants message don't change based on region change
