### ISSUE TITLE
Crashes when attempting to clear private data on iPadOS 13.2

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1951]
Due to a regression in iOS 13.2 we must show all action sheets as popovers in iPad even when displayed compact width size classes

One missed action sheet was the clear private data action sheet.

**Comment by srirambv** [comment]
Verification passed on iPad Pro with 13.2 running 1.14(19.11.20.19)
* Verified no crash when trying to clear browsing data
![image](https://user-images.githubusercontent.com/17010094/69364790-fbda4180-0c60-11ea-9876-dd08d9895163.png)

* Verified no crash when trying to remove sync device from chain 
![image](https://user-images.githubusercontent.com/17010094/69364798-ff6dc880-0c60-11ea-9d33-e1c55121ab1c.png)

* Verified no crash when trying to remove excluded sites in rewards panel
![image](https://user-images.githubusercontent.com/17010094/69364782-f7158d80-0c60-11ea-9110-63b4c3e16d84.png)
