### ISSUE TITLE
Unable to play media in background on iOS 13.2

### ISSUE THREAD

**Issue by tankmohit** [brave/brave-ios#1952]
Hello Team,

Brave is unable to play media in background.

**OS:** iOS 13.2.2
**Phone:** iPhone XR

**Sites checked:**
- youtube in desktop mode
- player.fm
- listennotes.com
- invidio.us
- soundcloud
- other webistes which allow background playback.

Sites listed above works completely fine in Safari with background playback when screen is turned off.

**Comment by srirambv** [comment]
This is already done in #1129. Background video play should be available in next release.
