### ISSUE TITLE
Snackbar popup UI layout issues

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1960]
Possible regression of #1736 

![Simulator Screen Shot - iPhone 11 Pro - 2019-11-14 at 12 39 25](https://user-images.githubusercontent.com/529104/68881786-cb802980-06db-11ea-9b72-c4243c27c3f4.png)

**Comment by srirambv** [comment]
* Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69364310-1cee6280-0c60-11ea-8a11-80dadc1aadc1.png)

* Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69364305-17911800-0c60-11ea-8946-4b9feb33078a.png)

* Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69364267-06e0a200-0c60-11ea-8768-63c5199f1b82.png)

* Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69364409-40b1a880-0c60-11ea-8778-bc790d859af8.png)

* Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.20.19)
![image](https://user-images.githubusercontent.com/17010094/69364285-0ea04680-0c60-11ea-95de-893a215db7f9.png)
