### ISSUE TITLE
Investigate Bookmark issue

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1961]
### Description: 
Users are reporting 1.13 is deleting bookmarks on upgrade

Some reports are here

https://community.brave.com/t/bookmarks-are-gone/92812/3
https://community.brave.com/t/browser-update-deleted-all-bookmarks-ios/92793/5
https://community.brave.com/t/bookmarks-are-all-gone/92531/2
https://community.brave.com/t/all-my-bookmarks-are-gone-after-latest-update-ios/92947

Others on the App Store reviews. 

Needs action asap

**Comment by kylehickinson** [comment]
Refs #1958

**Comment by atsyed87** [comment]
Another thread on this: https://community.brave.com/t/after-update-no-bookmarks-or-quick-launch/92906

And another: https://community.brave.com/t/sync-problems-folder-structure-lost-most-bookmarks-not-syncing/93164

**Comment by anthonypkeane** [comment]
Gathering some app store reviews in the issue here @jhreis 

https://appfigures.com/reviews/42132121512LnY2BZXjIqagm5JLmkjCJMQ?lang=en
https://appfigures.com/reviews/42132121512LdCtapBpc0LjvAmmjaEWhQw?lang=en
https://appfigures.com/reviews/42132121512LtoTX3j9fpSEeTJneKUdn_w?lang=en
https://appfigures.com/reviews/42132121512L7C5ykgt4ZJjD59IINpHJkg?lang=en
https://appfigures.com/reviews/42132121512Ld-2JtKJdJTGEDGXSWhIkYQ?lang=en
https://appfigures.com/reviews/42132121512LjIf1zZoYWPxiY1ez-A0NCA?lang=en
https://appfigures.com/reviews/42132121512LGaWaZcgzLy1LOhsuPBqNPw?lang=en
https://appfigures.com/reviews/42132121512LlEDaM2vv8jKj840biOvOKA?lang=en
https://appfigures.com/reviews/42132121512Lp59cB-C1-LL0fRBSuOEXgA?lang=en
https://appfigures.com/reviews/42132121512LH5fQWGuVakR5z1hoPtcG5g?lang=en
https://appfigures.com/reviews/42132121512L23F9dPi0LMrof5ZPQzCflw?lang=en
https://appfigures.com/reviews/42132121512LYHkL25KoA3AuXIEHFxQzCw?lang=en
https://appfigures.com/reviews/42132121512LVvBM9BQ3qyWhODbAipL7zw?lang=en
https://appfigures.com/reviews/42132121512LW1tfwwDzT3BF3SdAwerq8g?lang=en
https://appfigures.com/reviews/42132121512LY2hFmIzmnJcA5apRfC1jNg?lang=en
https://appfigures.com/reviews/42132121512LfwyNdItMWHScZLJIyq2GrQ?lang=en
https://appfigures.com/reviews/42132121512LYmaKf9At7PwDZ0Bm6nH1ng?lang=en
https://appfigures.com/reviews/42132121512L4ER4ima_XGCYabZCDacYdQ?lang=en
https://appfigures.com/reviews/42132121512Lqtuq6TzFosJMdQMDPWnLBw?lang=en
https://appfigures.com/reviews/42132121512LYuc-dt6QljTBFGXrnnnb2Q?lang=en
https://appfigures.com/reviews/42132121512LQCUUAt96is__hMu5KLQODg?lang=en
https://appfigures.com/reviews/42132121512LRAvxNzlRoDLSkKkxySzN-Q?lang=en
https://appfigures.com/reviews/42132121512LYjc3-q5_NYIz7uVviwUo1w?lang=en
https://appfigures.com/reviews/42132121512LbXoyG4b0iQJVbMKvBDH7gA?lang=en
https://appfigures.com/reviews/42132121512LNE-KcyfgyAralKFSMzft8A?lang=en
https://appfigures.com/reviews/42132121512LdscO_LXMJcfafvPM16zhdA?lang=en
https://appfigures.com/reviews/42132121512LUQjjqmODh2ZY-dF2L48E6A?lang=en
https://appfigures.com/reviews/42132121512LZ7o2u4tLY1mIIV19sOjY4A?lang=en
https://appfigures.com/reviews/42132121512LpioCprdmIdTnQaA6ga_Hbw?lang=en
https://appfigures.com/reviews/42132121512LfOoJU-Tjq2S3ALBJrsrtfQ?lang=en

**Comment by anthonypkeane** [comment]
https://appfigures.com/reviews/42132121512L3Nfv0aFIUybxte1Kyt8j4A?lang=en
https://appfigures.com/reviews/42132121512L3Jvkwz6jxANqfZeDjSUS9A?lang=en
https://appfigures.com/reviews/42132121512LWa-UDU_6Nz08FmpCaVUKXA?lang=en

**Comment by iccub** [comment]
Fixed in https://github.com/brave/brave-ios/issues/2015
