### ISSUE TITLE
URL alignment is a bit off

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#1964]
### Description: 
Alignment of URLs in address bar is a bit off. 
![image](https://user-images.githubusercontent.com/1903815/68896911-4a2b9580-06e1-11ea-9f7a-d511b0133831.png)

### Steps to Reproduce 
  1. Navigate to wikipedia.org

**Actual result:** 
Only edia.org is displayed in the address bar

**Expected result:**
wikipedia.org should be displayed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
v1.13 (19.11.06.18)

**Device details:** 
iPhone SE

**Comment by anthonypkeane** [comment]
Internal Chat: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1573764773296000

**Comment by iccub** [comment]
This only happens with bookmarks button enabled btw

**Comment by Brandon-T** [comment]
@jumde

This issue happens because of this PR: https://github.com/brave/brave-ios/pull/869 
which fixes this ticket: It’s related to: https://github.com/brave/brave-ios/issues/552

It seems this is 100% intentional.

The comment in the code says:

```swift
//  This override is done in case the eTLD+1 string overflows the width of textField.
//  In that case the textRect is adjusted to show right aligned and truncate left.
```

Expected behaviour is that the URL shifts over to highlight the `"host"` so the user can see whether or not it's a real domain or fake scam website.

**Comment by jhreis** [comment]
Despite this being true @Brandon-T it seems to be shifting too far to the left, the `.org` should at least be right-aligned here, no?

**Comment by Brandon-T** [comment]
@jhreis I fixed that part :)

![image](https://user-images.githubusercontent.com/1530031/68974735-70276780-07bf-11ea-85b5-499ec6decf50.png)

It automatically fixed itself when I fixed the `lock icon` not showing in the url bar. It happened because of a bad layout :)

**Comment by jumde** [comment]
> @jhreis I fixed that part :)
> 
> ![image](https://user-images.githubusercontent.com/1530031/68974735-70276780-07bf-11ea-85b5-499ec6decf50.png)
> 
> It automatically fixed itself when I fixed the `lock icon` not showing in the url bar. It happened because of a bad layout :)

Looks like the correct fix. Can you confirm if the test cases in #552 are not regressed? The idea is to highlight eTLD+1 when we need to truncate the URL.

**Comment by jumde** [comment]
## Test Plan

1. Enable bookmarks shortcut on address bar.
2. Navigate to long URLs like:
- http://paypal-test-domain.paypal.com
- http://paypal.com/long-path-url

and verify that the eTLD+1 is highlighted.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.16(20.05.05.12)
- Verified test plan from https://github.com/brave/brave-ios/issues/1964#issuecomment-624456102
- Navigating to http://paypal.com/long-path-url redirected to Paypal homepage 
- Verified eTLD+1 is highlighted when bookmark button is enabled on mobile 
------------
Verification passed on iPhone XR with iOS 13.3.1 running 1.16(20.05.05.12)
- Verified test plan from https://github.com/brave/brave-ios/issues/1964#issuecomment-624456102
- Navigating to http://paypal.com/long-path-url redirected to Paypal homepage 
- Verified eTLD+1 is highlighted when bookmark button is enabled on mobile 
------------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.16(20.05.05.12)
- Verified test plan from https://github.com/brave/brave-ios/issues/1964#issuecomment-624456102
- Navigating to http://paypal.com/long-path-url redirected to Paypal homepage 
- Verified eTLD+1 is highlighted when bookmark button is enabled on mobile 
------------
Marking as iPhone only as iPad URL bar is not small and entire URL is visible with or without the bookmark button
