### ISSUE TITLE
Scan Sync Code screen styling

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#1965]
In dark mode the text is noticeably dark and appears to be unstyled. 

![Image from iOS (1)](https://user-images.githubusercontent.com/318119/68905635-7ce88480-0707-11ea-9c53-cf9c6abf8ab4.png)

**Comment by jamesmudgett** [comment]
"Sync to device" title is near invisible.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.20.19)
* Verified text is visible on both light and dark theme
![image](https://user-images.githubusercontent.com/17010094/69275661-d559cf00-0baa-11ea-980a-ad6e77c55730.png)

--------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.20.19)
* Verified text is visible on both light and dark theme
![image](https://user-images.githubusercontent.com/17010094/69275690-e4408180-0baa-11ea-97c1-a6497910a0d8.png)

--------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.20.19)
* Verified text is visible on both light and dark theme
![image](https://user-images.githubusercontent.com/17010094/69275686-dee33700-0baa-11ea-8a63-af94f3e2210e.png)

--------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.20.19)
* Verified text is visible on both light and dark theme
![image](https://user-images.githubusercontent.com/17010094/69275702-ea366280-0baa-11ea-82e6-e315c23dec3a.png)

--------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.20.19)
* Verified text is visible on both light and dark theme
![image](https://user-images.githubusercontent.com/17010094/69275676-da1e8300-0baa-11ea-8d43-ad32972d5fd9.png)
