### ISSUE TITLE
Settings should link to the Rewards settings

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#1966]
## Problem Description 
You can open up program settings using the ellipsis in the bottom right. There's even a Rewards settings area. However, that does not show the actual rewards settings (enable/disable ads, enable/disable rewards)
![IMG_0201](https://user-images.githubusercontent.com/4733304/68912284-8fb18800-070c-11ea-9f74-8e7f9603366d.jpg)

## Feature Overview 
Would be great if settings either:
- linked to the Rewards settings, so you can toggle
- provided the toggle

It seems especially weird, because you can hide the rewards icon... but not disable rewards.

**Comment by kylehickinson** [comment]
@anthonypkeane Do we want a button here as well to go to the default rewards panel if the user doesn't have rewards enabled?

**Comment by srirambv** [comment]
- Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.12.10)
![image](https://user-images.githubusercontent.com/17010094/74542687-0d826b00-4f6a-11ea-9568-9d8c17713194.png)
------
- Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.12.10)
![image](https://user-images.githubusercontent.com/17010094/74542676-08252080-4f6a-11ea-919b-a3a0d1b6fe3b.png)
------
- Verification passed on iPhone 6 with iOS 12.4.4 running 1.15(20.02.12.10)
![image](https://user-images.githubusercontent.com/17010094/74542658-022f3f80-4f6a-11ea-91dc-f806eb06aa3d.png)
------
- Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.12.10)
![image](https://user-images.githubusercontent.com/17010094/74542518-c72d0c00-4f69-11ea-932b-03b6a68677bf.png)
------
- Verification passed on IPAD Pro with iOS 12.4.4 running 1.15(20.02.12.10)
![image](https://user-images.githubusercontent.com/17010094/74542631-f8a5d780-4f69-11ea-86f6-341985c70097.png)
