### ISSUE TITLE
Push notify users every month on how much data they saved using Brave

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#1969]
### Description: 
In certain regions, the web is slower towards the end of the month due to data caps, resulting in reduced engagement. 

See here: https://bravesoftware.slack.com/archives/CK3B25E5U/p1573782464020900

**Comment by srirambv** [comment]
How are we ascertaining when the data caps are ending exactly at the end of each month cycle(30/31st)?

**Comment by anthonypkeane** [comment]
We don’t need to

**Comment by iccub** [comment]
Will be part of https://github.com/brave/brave-ios/issues/2502
