### ISSUE TITLE
Adding Ecosia Search Engine

### ISSUE THREAD

**Issue by Justin2997** [brave/brave-ios#1973]
## Problem Description 
Brave mission is to repart the web. One part of that is to propose search engine that try to make the internet a better place.

## Feature Overview 
Ecosia is a search engines that plant tree at a massive scale. Brave should help them. You can learn more here : https://info.ecosia.org/about

**Comment by iccub** [comment]
Thanks for the ticket, we plan to add support for all opensearch compatible engines, the work is done here https://github.com/brave/brave-ios/pull/983
Hopefully we will be able to finish implementing it soon

Related ticket https://github.com/brave/brave-ios/issues/936, closing this one for now
