### ISSUE TITLE
`Copy to clipboard` test is cut on iPhone 5S

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1974]
### Steps to Reproduce 
  1. Add a new sync chain
  2.
  3.

**Actual result:** 

<img width="393" alt="Zrzut ekranu 2019-11-18 o 16 52 49" src="https://user-images.githubusercontent.com/6950387/69067833-11aef300-0a24-11ea-8b9d-ca3aa69e359e.png">

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Happens only on iPhone 5s

**Comment by iccub** [comment]
We don't have access to a real iPhone 5S but this is what it looks like on simulator

<img width="504" alt="Zrzut ekranu 2019-11-21 o 20 31 08" src="https://user-images.githubusercontent.com/6950387/69370247-e0d9f280-0c9d-11ea-9373-8cb515b7fd22.png">

**Comment by kjozwiak** [comment]
Thanks for the double check @iccub 👍 Going to label this as `QA Pass - iPhone` as per the above. We don't have a `iPhone 5s` so this is the best that we're going to do. @srirambv and myself would basically go through the same thing @iccub did.
