### ISSUE TITLE
Add sync device via codewords in Japanese lang missing description

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1979]
### Steps to Reproduce 
  1. Set language to Japanese
  2. Try to add a new device using codewords
  3.

**Actual result:** 

<img width="544" alt="Zrzut ekranu 2019-11-18 o 18 38 55" src="https://user-images.githubusercontent.com/6950387/69076139-1f1fa980-0a33-11ea-9ca5-ea8dc8bebd80.png">

**Expected result:**
Missing description

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6s` running `iOS 13.2.2` using `1.14 (19.11.20.19)`

![IMG_0029](https://user-images.githubusercontent.com/2602313/69383680-51761480-0c88-11ea-9d24-1f0a3de9468c.PNG)

---

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.14 (19.11.20.19)`

![IMG_9934](https://user-images.githubusercontent.com/2602313/69383582-0956f200-0c88-11ea-983c-6beccdedb5b9.PNG)

---

Verification **PASSED** on `iPad Air 3rd Gen` running `iOS 13.3` using `1.14 (19.11.20.19)`

![IMG_A70E59915CC6-1](https://user-images.githubusercontent.com/2602313/69384077-51c2df80-0c89-11ea-8e33-cb744e1a8fa4.jpeg)

---

Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.14 (19.11.20.19)`

![IMG_F062AAA118B3-1](https://user-images.githubusercontent.com/2602313/69383969-0f999e00-0c89-11ea-8d0c-757273e66d2a.jpeg)

-----
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.27.22)
![image](https://user-images.githubusercontent.com/17010094/69821715-78759e80-11d2-11ea-8530-f1f9528dbd72.png)
