### ISSUE TITLE
Navigating to address bar from reader mode hides it

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#1983]
### Description: 
Probably a regression caused by one of my layout constraints fixes

### Steps to Reproduce 
  1. Tap on reader mode
  2. Tap on address bar

**Actual result:** 
<img width="544" alt="Zrzut ekranu 2019-11-19 o 17 32 45" src="https://user-images.githubusercontent.com/6950387/69166002-d16a7600-0af2-11ea-87fb-e9f66010287e.png">

**Expected result:**
The address bar should be present

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.20.19)
* Verified tapping on reader mode and then on URL bar still shows URL again
------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.20.19)
* Verified tapping on reader mode and then on URL bar still shows URL again
------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.20.19)
* Verified tapping on reader mode and then on URL bar still shows URL again
------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.20.19)
* Verified tapping on reader mode and then on URL bar still shows URL again
------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.20.19)
* Verified tapping on reader mode and then on URL bar still shows URL again
