### ISSUE TITLE
Browser crash when PBO is enabled from a private tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1986]
### Description: 
Browser crash when PBO is enabled from a private tab. Found while testing #580 

### Steps to Reproduce 
  1. Login to a site in normal tab
  2. Open new private tab
  3. Go to settings and enable PBO, browser crash

**Actual result:** 
Browser crashes
https://bravesoftware.slack.com/archives/C06UXF3KJ/p1574190790408200

**Expected result:**
No crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14(19.11.19.15)

**Device details:** 
iPhone 7+ (iOS 13.2)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
Can't reproduce this on `iOS 12` using `1.14(19.11.19.15)`. Seems like a `iOS 13` specific issue hence adding the `iOS 13` label. I'll double check `iOS 12` just in case as well during verification.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6s` running `iOS 13.2.2` using `1.14 (19.11.20.19)`
*  Verified that the original STR  via https://github.com/brave/brave-ios/issues/1986#issue-525211220 worked as expected
* Enabled/Disabled `Private Browsing Only` several times and ensured Brave didn't crash

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.14 (19.11.20.19)`
*  Verified that the original STR  via https://github.com/brave/brave-ios/issues/1986#issue-525211220 worked as expected
* Enabled/Disabled `Private Browsing Only` several times and ensured Brave didn't crash

Verification **PASSED** on `iPad Air 3rd Gen` running `iOS 13.3` using `1.14 (19.11.20.19)`
*  Verified that the original STR  via https://github.com/brave/brave-ios/issues/1986#issue-525211220 worked as expected
* Enabled/Disabled `Private Browsing Only` several times and ensured Brave didn't crash

Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.14 (19.11.20.19)`
*  Verified that the original STR  via https://github.com/brave/brave-ios/issues/1986#issue-525211220 worked as expected
* Enabled/Disabled `Private Browsing Only` several times and ensured Brave didn't crash

Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.27.21)
