### ISSUE TITLE
Session in normal tab is not lost when PBO is enabled and then disabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1987]
### Description: 
Session in normal tab is not lost when PBO is enabled and then disabled. Found while testing #580 

### Steps to Reproduce 
  1. Login to a site in normal tab(I logged into community.brave.com)
  2. Enable PBO from settings, warn message is shown from #580
  3. Close the message and disable PBO to go back to normal tabs
  4. Visit the site from step 1, previous session is restored

**Actual result:** 
Session from normal tab is not lost when PBO is enabled and then disabled

**Expected result:**
Should lose all session as per #580 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14(19.11.19.15)

**Device details:** 
iPhone 7+ (iOS 13.2)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Enabling PBO from private tab causes crash captured in #1986

**Comment by kjozwiak** [comment]
I don't think this is 100% resolved as I can still occasionally reproduce the issue. Quick example of the issue being reproduced on a `iPhone 6s` running `iOS 13.2.2` using `1.14 (19.11.20.19)`:

Example of the issue occurring: https://youtu.be/ujSbzpvaOxc

STR:

* launch a brand new installation of `1.14 (19.11.20.19)`
* skip the onboarding process and tap on the Twitter (favourite) that's appearing on the NTP
* log into Twitter and leave the tab opened
* Switch over to `Private`
* once in `Private` mode, select `Settings` and enable `Private Browsing Only`
* Select `OK` on the modal and tap on `Done`
* tap on `Settings` and disable `Private Browsing Only`
* tap on the Twitter icon (favourite) on the NTP and refresh the page

You'll notice that sometimes you'll still be logged in.

@srirambv can you reproduce this on your end? I can reproduce it pretty often, especially with Twitter. I'll wait till @srirambv or someone else can confirm before re-opening the issue.

**Comment by srirambv** [comment]
@kjozwiak  Tried a couple of times but couldn't reproduce it.  I'd suggest logging  a new issue as follow up and blocking this issue so that we can come back and mark this as QA/No once the followup issue is fixed.

**Comment by srirambv** [comment]
I was able to reproduce the issue on 1.14(19.11.26.21). The key step here is not to close the settings when PBO is toggled. If you just enable PBO and disable it while in settings and then go back to normal tab and load the page it still retains the session. But if you close the settings sheet and go into a new Private tab in PBO and then come out to normal mode it will lose the session. Here's a recording of the issue 
![sessions_ios](https://user-images.githubusercontent.com/17010094/69727476-9f5ba400-10f0-11ea-928f-6789194e625e.gif)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.27.14)
* Verified sessions are lost when switching to PBO
* Verified turning off PBO and navigating to the site doesn't restore session
* Verified reloading the site multiple times doesn't restore session
--------------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.27.14)
* Verified sessions are lost when switching to PBO
* Verified turning off PBO and navigating to the site doesn't restore session
* Verified reloading the site multiple times doesn't restore session
--------------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.27.14)
* Verified sessions are lost when switching to PBO
* Verified turning off PBO and navigating to the site doesn't restore session
* Verified reloading the site multiple times doesn't restore session
--------------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.27.14)
* Verified sessions are lost when switching to PBO
* Verified turning off PBO and navigating to the site doesn't restore session
* Verified reloading the site multiple times doesn't restore session
--------------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.27.14)
* Verified sessions are lost when switching to PBO
* Verified turning off PBO and navigating to the site doesn't restore session
* Verified reloading the site multiple times doesn't restore session
--------------
* Logged #2041 as a followup
