### ISSUE TITLE
Hamburger menu stops working after clearing private data

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#199]
### Steps to Reproduce 
  1. Tap hamburger menu button
  2. Tap settings button
  3. Tap "Clear Private Data" button
  4. Switch on "Browsing History", "Cache", "Cookies" and "Saved Logins"
  5. Tap "Clear Private Data" button
  6. Tap Back button
  7. Tap Done button

**Actual result:** Hamburger menu stops working

**Expected result:** Hamburger menu should work

**Reproduces how often:** Everytime

**Brave Version:** Development branch build hash: 93f59d7cb8905acc3dd342c49a8a9f333afd01b1

**Device details:** iPad Pro 10.5" iOS 11.4.1

### Additional Information 

Workaround is to tap the + new tab button

**Comment by kylehickinson** [comment]
Just tested, this is no longer happening on development @  cefaeab, closing!
