### ISSUE TITLE
Status bar flickering light/dark theme while navigating between rewards sheets

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1992]
### Description: 
Top bar has flickering light/dark theme while navigating between rewards sheets

### Steps to Reproduce 
  1. Set device theme to dark 
  2. Open rewards panel
  3. Navigate back and forth in rewards panel
  4. top bar keeps flickering between light/dark theme

**Actual result:** 
![RPReplay_Final1574267632](https://user-images.githubusercontent.com/17010094/69258465-a16eb180-0b8a-11ea-9bd8-833b2c8428d4.gif)

**Expected result:**
Navigating in rewards panel should not affect top bar theme

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13

**Device details:** 
iPhone & iPad

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)?  N/A

### Additional Information
Possibly related to #1714 hence adding to 1.14. Please move both issues if required

**Comment by kylehickinson** [comment]
Tested on latest build and couldn't seem to reproduce this. This isn't related to #1714 specifically, though probably has the same solution

**Comment by iccub** [comment]
Could going to regular Brave app settings first trigger this?
