### ISSUE TITLE
Show monthly ad grant reminder for previous cycle if upgrade during beginning of new cycle

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1993]
If the user upgrades & launches at the beginning of a new ad cycle (1st to 7th day of month), we should check to see if they viewed any ads in the previous cycle and schedule an ad reminder on the 7th of the current month for it since they will be getting an ad grant then

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.22.122)
* Verified log shows `Scheduled monthly ad notification` message with time set
-------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.22.122)
* Verified log shows `Scheduled monthly ad notification` message with time set
-------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.22.122)
* Verified log shows `Scheduled monthly ad notification` message with time set
-------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.22.122)
* Verified log shows `Scheduled monthly ad notification` message with time set
-------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.22.122)
* Verified log shows `Scheduled monthly ad notification` message with time set
-------
All screenshots can be found https://github.com/brave/brave-ios/issues/1660#issuecomment-558368585
