### ISSUE TITLE
Rewards notification text color incorrect in dark mode on iOS 12

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#1995]
As seen:

![IMG_0001](https://user-images.githubusercontent.com/529104/69265340-0fb97100-0b97-11ea-806f-e4d8ecef8571.PNG)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.14 (19.11.20.19)`

![IMG_9935](https://user-images.githubusercontent.com/2602313/69389346-c00f9e00-0c99-11ea-9b99-a9fed008aa11.PNG)

---

Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.14 (19.11.20.19)`

![IMG_A7EE8012BE76-1](https://user-images.githubusercontent.com/2602313/69389477-24326200-0c9a-11ea-92f2-021178277908.jpeg)
------
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.22.15)
![image](https://user-images.githubusercontent.com/17010094/69661192-f0678b80-104f-11ea-8f11-d71a64a16534.png)
