### ISSUE TITLE
Claim grant from panel doesn't work the first time after a wallet is restored

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1998]
### Description: 
Claim grant from panel doesn't work the first time after a wallet is restored

### Steps to Reproduce 
  1. Create a new wallet
  2. Restore a dummy wallet
  3. Wait for grant message to show up
  4. Click claim, goes into an infinite loop
  5. Close and reopen the panel, able to claim the grant 

**Actual result:** 
Claim grant from panel doesn't work the first time after a wallet is restored

**Expected result:**
Should be able to claim grant on first try after restoring the wallet

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14(19.11.19.15)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Found while testing #1911. Not a blocker so marking it for 1.15

**Comment by srirambv** [comment]
Moving to 1.6 to align with #2146

**Comment by kylehickinson** [comment]
@srirambv I don't think either of these should be prioritized as they do not affect any real user flow. Restoring wallets is not available outside of testing
