### ISSUE TITLE
adding spacing between sync text and warning message

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2006]
### Description: 

We should add some spacing between the sync message and the warning message under both `QR Code` and `Code Words` so it look similar to what `Android` is doing. The current implementation looks a bit cluttered.

### Steps to Reproduce 

  1. launch `1.14 (19.11.20.19)` and skip onboarding
  2. select `Settings` --> `Sync` --> `Start a new Sync Chain` --> `Tablet or Phone`

Switch between `QR Code` & `Code Words` and you'll notice the warning message isn't spaced.

**Actual result:** 

![IMG_9928](https://user-images.githubusercontent.com/2602313/69357621-67b5ad80-0c53-11ea-9dfe-9ac35dff9779.PNG)

![IMG_9927](https://user-images.githubusercontent.com/2602313/69357622-67b5ad80-0c53-11ea-99fd-80dbd5fbe5c5.PNG)

**Expected result:**

![image](https://user-images.githubusercontent.com/17010094/64460380-3ef83000-d0c8-11e9-9579-628934e6bbeb.png)

![image](https://user-images.githubusercontent.com/17010094/64460395-49b2c500-d0c8-11e9-810d-35cefeebb0e6.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible when using the above STR.

**Brave Version:** 

* `1.14 (19.11.20.19)`

**Device details:** 

* Using `iPhone 6s+` running `iOS 12.4.1`

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)?  `N/A`

### Additional Information

CCing @srirambv @jhreis @anthonypkeane

**Comment by srirambv** [comment]
- Verification passed on iPhone XR with iOS 13.3.1 running 1.15 (20.01.13.17)
![image](https://user-images.githubusercontent.com/17010094/72361789-0bee2a80-36c0-11ea-8c55-34b49c590f65.png)

- Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15 (20.01.13.17)
![image](https://user-images.githubusercontent.com/17010094/72361741-fda00e80-36bf-11ea-9b48-4e42bc27ca4d.png)

- Verification passed on iPhone 6 with iOS 12.4.4 running 1.15 (20.01.13.17)
![image](https://user-images.githubusercontent.com/17010094/72361761-04c71c80-36c0-11ea-9cf1-02868044e9f4.png)

- Verification passed on iPad Pro with iOS 13.3.1 running 1.15 (20.01.13.17)
![image](https://user-images.githubusercontent.com/17010094/72361699-eeb95c00-36bf-11ea-95ba-2e3877ccf20c.png)

- Verification passed on iPad Pro with iOS 12.4.4 running 1.15 (20.01.13.17)
![image](https://user-images.githubusercontent.com/17010094/72361724-f8db5a80-36bf-11ea-8bde-ff006712c905.png)
