### ISSUE TITLE
Wallet balance automatically updates when ads grant is available

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2007]
### Description: 
Wallet balance automatically updates when ads grant is available

### Steps to Reproduce 
  1. Create a new wallet
  2. Ensure wallet balance is 0 
  3. Wait for ads grant to show up
  4. Once ads grant shows up, even before claiming it wallet balance is already showing the amount that is received in ads grant

**Actual result:** 
https://bravesoftware.slack.com/archives/CKA10H3AS/p1574355078036800

**Expected result:**
Should only update balance once the grant is claimed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14(19.11.20.19)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Found while testing #1908

**Comment by kylehickinson** [comment]
@srirambv Did you test this with a proper wallet (i.e. given an ad grant without restoring wallet). If not, then I wouldn't consider this a valid issue

**Comment by srirambv** [comment]
@kylehickinson  it was on a clean install and restore from the test wallets list we have. I will try this again once the 1.14 is done and update

**Comment by kylehickinson** [comment]
@srirambv Please test again with clean install, no restore, asking @maikelmclauflin to add an ad grant to its payment ID

**Comment by NejcZdovc** [comment]
closing as stale
