### ISSUE TITLE
Rewards onboarding should be skipped when wallet is already created[Follow up to #1753]

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2010]
### Description: 
Follow up to #1753, Rewards onboarding should be skipped when wallet is already created 

### Steps to Reproduce 
  1. Start onboarding on a clean install
  2. Enable rewards via onboarding 
  3. Force quit app before completing onboarding
  4. Relaunch app, starts onboarding again
  5. Shows rewards onboarding again even though rewards is already enabled

**Actual result:** 
Rewards onboarding is shown again even though wallet is already created

**Expected result:**
Rewards onboarding should be skipped and directly showing `Start Browsing` button

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13/1.14

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
@Brandon-T If its possible to somehow skip rewards step if they kill app before clicking "start browsing"/tapping on the ad then that'd work. If it's not possible at this point, just add check to see if wallet is created already when they click agree and skip to next step immediately without creating wallet again.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.12.10)
- Verified force quit app after enabling rewards doesn't start over with wallet creation step
- Verified sample ad notification onboarding is shown after force quitting the app and until start browsing is enabled
-----
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified force quit app after enabling rewards doesn't start over with wallet creation step
- Verified sample ad notification onboarding is shown after force quitting the app and until start browsing is enabled
-----
Verification passed on iPhone 6 with iOS 12.4.4 running 1.15(20.02.12.10)
- Verified force quit app after enabling rewards doesn't start over with wallet creation step
- Verified sample ad notification onboarding is shown after force quitting the app and until start browsing is enabled
-----
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified force quit app after enabling rewards doesn't start over with wallet creation step
- Verified sample ad notification onboarding is shown after force quitting the app and until start browsing is enabled
-----
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.12.10)
- Verified force quit app after enabling rewards doesn't start over with wallet creation step
- Verified sample ad notification onboarding is shown after force quitting the app and until start browsing is enabled
-----
