### ISSUE TITLE
crash when visiting certain websites with rewards enabled

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2013]
### Description: 

Brave crashes when you visit certain websites and have `Rewards` enabled. Issue originally reported by a friend and wife who mentioned that Brave kept crashing on him.

### Steps to Reproduce 

**`Case #1`** (reported by friend)

  1. install `1.13 (19.11.06.18)` or `1.14 (19.11.20.19)`
  2. visit http://tochristmasmarket.com/ (no crash)
  3. enable `Rewards` via the panel and Brave will crash instantly

**`Case #2`** (reported by wife)

  1. install `1.13 (19.11.06.18)` or `1.14 (19.11.20.19)`
  2. visit https://www.westcoastkids.ca (no crash)
  3. enable `Rewards` and start scrolling through the website (instant crash)

**Actual result:** 

Brave crashing when visiting http://tochristmasmarket.com or https://www.westcoastkids.ca when `Rewards` is enabled.

**Expected result:**

Brave shouldn't be crashing when visiting websites while `Rewards` is enabled.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

Reproduced on both `1.13 (19.11.06.18)` & `1.14 (19.11.20.19)`

**Device details:** 

* `iPhone 6s` running `iOS 13.2.2` using `1.14 (19.11.20.19)` - Reproduced
* `iPhone 6s+` running `iOS 12.4.1` using `1.14 (19.11.20.19)` - Reproduced
* `iPad Air 3rd Gen` running `iOS 13.3` using `1.14 (19.11.20.19)` - Reproduced
*  `iPad Mini 4` running `iOS 12.4.1` using `1.14 (19.11.20.19)` - Reproduced

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)?  `N/A`

### Additional Information

CCing @jhreis @anthonypkeane @brave/legacy_qa @iccub

**Comment by kjozwiak** [comment]
Looks like this is still an issue. I can reproduce the crash using the following STR:

* launch `1.14 (19.11.26.13)`
* open http://tochristmasmarket.com/ 
* enable `Rewards`

Platforms:

* `iPhone 6s` running `iOS 13.2.2` using `1.14 (19.11.26.13)` - **Couldn't reproduce**
* `iPhone 6s+` running `iOS 12.4.1` using `1.14 (19.11.26.13)` - **Reproduced**
* `iPad Air 3rd Gen` running `iOS 13.3` using `1.14 (19.11.26.13)` - **Reproduced**
* `iPad Mini 4` running `iOS 12.4.1` using `1.14 (19.11.26.13)` - **Reproduced**

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.26.21)
* Verified steps from issue description no crash after enabling rewards via the panel
* Verified visiting the site after enabling rewards via onboarding doesn't crash 
-------------
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.26.21)
* Verified steps from issue description no crash after enabling rewards via the panel
* Verified visiting the site after enabling rewards via onboarding doesn't crash 
-------------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.26.21)
* Verified steps from issue description no crash after enabling rewards via the panel
* Verified visiting the site after enabling rewards via onboarding doesn't crash 
-------------
Verification passed on iPad Pro  with iOS 13.2 running 1.14(19.11.26.21)
* Verified steps from issue description no crash after enabling rewards via the panel
* Verified visiting the site after enabling rewards via onboarding doesn't crash 
-------------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.26.21)
* Verified steps from issue description no crash after enabling rewards via the panel
* Verified visiting the site after enabling rewards via onboarding doesn't crash

**Comment by kjozwiak** [comment]
Wife found a similar crash with https://www.westcoastkids.ca when you have `Rewards` enabled. Quickly went through the following verification to see if it's the same issue:

* `iPhone 6s` running `iOS 13.2.2` using `1.13 (19.11.06.18)` or `1.14 (19.11.22.15)` - **Reproduced**
* `iPhone 6s` running `iOS 13.2.2` using `1.14 (19.11.27.14)` - **Couldn't reproduce**

@srirambv mind checking quickly to see if it's fixed on your end as well with `1.14 (19.11.27.14)`?

**Comment by kylehickinson** [comment]
@kjozwiak The fix merged in https://github.com/brave/brave-ios/pull/2018 was not present in `1.14 (19.11.22.15)` so it would still crash there

**Comment by kjozwiak** [comment]
> @kjozwiak The fix merged in #2018 was not present in `1.14 (19.11.22.15)` so it would still crash there

@kylehickinson yup, I was just checking to make sure that I can reproduce the issue on a `Dev` build as my wife was reproducing it on production. Double checked with `1.14 (19.11.27.14` to make sure the crash she was experiencing wasn't happening which means it was also covered by #2020.
