### ISSUE TITLE
crash when backgrounding brave while context menu opened from a text field

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2014]
### Description: 

Brave crashes some times when you move it to the background while having a context menu opened from a text field, specifically a password field in this particular instance.

I ran into this at least ~5 times but it doesn't always happen and isn't easy to reproduce. Hoping @iccub or another developer that takes a look can reproduce 👍 

### Steps to Reproduce

  1. launch `1.14 (19.11.20.19)` and tap on the Twitter icon under the NTP (Favourites)
  2. Click on "Login" on Twitter and long press the password field so you get a context menu
  3. once the context menu is displayed, background the application and wait ~30s or so

It doesn't always reproduce but it happened often enough that I was able to capture a video the crash happening.

**Actual result:** 

Example of the crash occurring: https://youtu.be/xFSRBadLLWs

**Expected result:**

Brave shouldn't crash when background the application.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

As mentioned above, I reproduced this ~5 different times but it isn't easy to reproduce. Hoping @iccub or another developer can reproduce and get a crash stack.

**Brave Version:** 

* `1.14 (19.11.20.19)`

**Device details:** 

* `iPad Air 3rd Gen` running `iOS 13.3` using `1.14 (19.11.20.19)` - Reproduced
* `iPhone 6s` running `iOS 13.2.2` using `1.14 (19.11.20.19)` - Reproduced

**Website problems only:**

- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information

CCing @jhreis @brave/legacy_qa @anthonypkeane @iccub

**Comment by iccub** [comment]
Did you have rewards enabled?

**Comment by iccub** [comment]
Bump to 1.15

**Comment by kjozwiak** [comment]
> Did you have rewards enabled?

@iccub nope, didn't have Rewards enabled. Basically ran into it right after I skipped onboarding and went straight to Twitter via the `Favourites` icon on the NTP. Rewards was never enabled when the crashes occurred.

**Comment by kjozwiak** [comment]
I still this from time to time but it's pretty rare and hard to reproduce.

**Comment by kjozwiak** [comment]
Believe I ran into this again and managed to pull a crash stack from the iOS device. I was running through the YubiKey verifications via the manual passes so it's possible it could be https://github.com/brave/brave-ios/issues/1157. Either way, added the crash stack below. @iccub @kylehickinson mind taking a look whenever you have some time to see if the crash stack could be related to the original issue?

* [Client-2021-05-28-231329.ips.beta.txt](https://github.com/brave/brave-ios/files/6581021/Client-2021-05-28-231329.ips.beta.txt)

**Comment by iccub** [comment]
Let's close this for now, there's a chance our recent update to webauth and removing yubico sdk fixed it
