### ISSUE TITLE
Provide an option to restore lost bookmarks during 1.12 migration

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2015]
We should provide an option for users to restore their lost bookmarks.
Basic implementation:

1. Add new Recovered Bookmarks folder in new DB
2. Get all bookmarks from old DB
3. For loop
    1. Remove syncUUID
    2. Insert to new DB to Recovered Bookmarks folder

The restoration process can either happen automatically or through a setting option

**Comment by iccub** [comment]
Test note: It would be good to test it with various app states
1. Normal browsing
2. Private browsing only
3. Normal browsing with pin code enabled
4. WIth Sync enabled

**Comment by srirambv** [comment]
Verification passed on iPhone X with iOS 13.2 running 1.14.2(19.12.9.17)
* Verified bookmarks are restored on upgrade to 1.14.2 
* Verified favourites are restored on upgrade to 1.14.2
* Verified all scenarios except iOS 12 test from #2061 
-------
Verification passed on iPad Pro with iOS 13.2 running 1.14.2(19.12.9.17)

* Verified bookmarks are restored on upgrade to 1.14.2 
* Verified favourites are restored on upgrade to 1.14.2
* Verified all scenarios except iOS 12 test from #2061 
--------
Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.14.2 (19.12.11.21)`

* Verified bookmarks are restored on upgrade to 1.14.2 
* Verified favourites are restored on upgrade to 1.14.2
* Verified all scenarios except iOS 12 test from #2061 
--------
Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.14.2 (19.12.11.21)`

* Verified bookmarks are restored on upgrade to 1.14.2 
* Verified favourites are restored on upgrade to 1.14.2
* Verified all scenarios except iOS 12 test from #2061
