### ISSUE TITLE
Keyboard auto hides while typing

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2016]
### Description: 
Keyboard auto hides while typing

### Steps to Reproduce 
  1. Open a new tab 
  2. Start typing 
  3. Keyboard auto hides

**Actual result:** 
![phone](https://user-images.githubusercontent.com/17010094/69432723-42cf4200-0d08-11ea-8066-13a3911ba179.gif)

**Expected result:**
Should not hide keyboard while typing

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
All

**Device details:** 
Both iPhone and iPad

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
This is even more annoying on iPhone X series as the bottom swipe bar shows up on top of the quick-search bar 
![image](https://user-images.githubusercontent.com/17010094/69432895-8fb31880-0d08-11ea-9f4e-5f487e0b0686.png)

**Comment by kylehickinson** [comment]
Can't reproduce on same build same phone. Do you have a bluetooth keyboard by any chance accidentally connecting to your phone?

**Comment by srirambv** [comment]
@kylehickinson, There is no Bluetooth keyboard. Bluetooth is off on the device. There is also a report from the community 

+1 from https://community.brave.com/t/on-screen-keyboard-does-not-keep-open/94833/2

**Comment by kylehickinson** [comment]
@srirambv Did you have a version this happened on? Was it before we added clear button fix?

**Comment by srirambv** [comment]
@kylehickinson  this happens on current playstore build.

**Comment by kylehickinson** [comment]
@srirambv Will continue looking into it but if you can verify it still happens on 1.14 that'd be good

**Comment by kylehickinson** [comment]
Also to the best of your memory, do you remember if you tested this with passcode enabled? or done anything related to the SyncPair screen or find in page?

**Comment by srirambv** [comment]
No this happens on just clean install no sync/passcode screens ever touched.

**Comment by PascalParvex** [comment]
> @kylehickinson, There is no Bluetooth keyboard. Bluetooth is off on the device. There is also a report from the community
> 
> +1 from https://community.brave.com/t/on-screen-keyboard-does-not-keep-open/94833/2

This is my posting. With the changes made, it got a little better. Easiest way to circumvent it is to close the Brave task and reopen.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.18.17)
- Verified keyboard doesn't auto hide while typing in URL bar
- Verified enabling `Auto hide keyboard` option in settings doesn't cause any issue when typing 
- Verified disabling `Auto hide keyboard` option in settings doesn't cause any issue when typing 
-------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified keyboard doesn't auto hide while typing in URL bar
- Verified enabling `Auto hide keyboard` option in settings doesn't cause any issue when typing 
- Verified disabling `Auto hide keyboard` option in settings doesn't cause any issue when typing 
-------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.18.17)
- Verified keyboard doesn't auto hide while typing in URL bar
- Verified enabling `Auto hide keyboard` option in settings doesn't cause any issue when typing 
- Verified disabling `Auto hide keyboard` option in settings doesn't cause any issue when typing 
-------
Verification passed on iPad Pro with iOS 13.4 running 1.15(20.02.18.17)
- Verified keyboard doesn't auto hide while typing in URL bar
- Verified enabling `Auto hide keyboard` option in settings doesn't cause any issue when typing 
- Verified disabling `Auto hide keyboard` option in settings doesn't cause any issue when typing 
-------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.18.17)
- Verified keyboard doesn't auto hide while typing in URL bar
- Verified enabling `Auto hide keyboard` option in settings doesn't cause any issue when typing 
- Verified disabling `Auto hide keyboard` option in settings doesn't cause any issue when typing 
-------
