### ISSUE TITLE
Navigating back doesn't hide/show browser UI correctly 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2017]
### Description: 
Navigating back doesn't hide/show browser UI correctly 

### Steps to Reproduce 
  1. Visit wikipedia.org
  2. Scroll down and tap on privacy policy
  3. Swipe back to go back to previous page
  4. UI contents are not properly hidden/shown

**Actual result:** 
iPhone 6
![image](https://user-images.githubusercontent.com/17010094/69434928-9d6a9d00-0d0c-11ea-8ad7-ad51fdd42ea6.png)
iPhone XR
![image](https://user-images.githubusercontent.com/17010094/69434958-a9eef580-0d0c-11ea-832f-4c3a437cc0d7.png)
iPhone 7+ (URL bar is not completely hidden)
![image](https://user-images.githubusercontent.com/17010094/69435032-cee36880-0d0c-11ea-8fe1-3ed0b07ff475.png)
iPad Pro (URL bar is not completely hidden)
![image](https://user-images.githubusercontent.com/17010094/69435108-f20e1800-0d0c-11ea-8f78-6761475b9a3f.png)

**Expected result:**
Should show the URLbar/Bottom bar completely or hide them completely 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Follow up to #1801

**Comment by iccub** [comment]
should be fixed with recent toolbar changes, lets retest

**Comment by Uni-verse** [comment]
Not reproduced with `iPhone 12` & `iPhone XR` using `iOS 16.2` & `iOS 15.5` respectively using `1.47 (23.1.18.17)`

CC: @srirambv let me know if you can still reproduce.
