### ISSUE TITLE
Add support for YubiKey (5C Nano) on iPad Pro

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#2019]

**Comment by samueldiethelm** [comment]
Is there any progress on this? I currently need to switch to another browser in order to login with my Yubikey. I suspected maybe it only worked on Safari because of some iOS limitation but it works fine on other third party browsers too.

**Comment by iccub** [comment]
We removed yubico sdk in favor of built in webkit webauth api.
This will be reopened if the problem still occurs.
