### ISSUE TITLE
Application crashes when reordering tabs on tab bar

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#202]
### Steps to Reproduce 

Pre-requisite: Start browser in regular browsing mode

  1. Open tab tray
  2. Add 3 tabs within the tab tray
  3. Change to private browsing mode
  4. Add 2 tabs within the tab tray
  5. Reorder tabs within the tab tray
  6. Open a tab within the tab tray
  7. Reorder tabs on tab bar

**Actual result:** Application crashes

**Expected result:** Application should not crash

**Reproduces how often:** Everytime

**Brave Version:** Development build hash 93f59d7cb8905acc3dd342c49a8a9f333afd01b1

**Device details:** iPad Pro 10.5" iOS 11.4.1

### Additional Information

**Comment by kylehickinson** [comment]
@tmancey I couldn't get this to crash on development @ ebc73f4

**Comment by tmancey** [comment]
Confirmed this is no longer an issue on the latest development branch
