### ISSUE TITLE
Ads region on iOS is unsupported if users Calendar is set to a non-default option

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2022]
Ref https://github.com/brave/brave-browser/issues/7029
Relevant PR: https://github.com/brave/brave-core/pull/4069

In iOS we use `NSLocale` to determine the users current locale and feed this into the ads library. If an iOS user sets a non-default calendar for their region (For example switching from Gregorian to Japanese) the identifier reported by `NSLocale` ends up looking like this `en_US@calendar=japanese` which then is not parsed correctly by bat-native-ads since it is looking for `en_US`/`en-US` specifically.

This results in the user seeing "Ads region not supported" status on the Rewards Settings page even if they are in a supported region

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.3.1 running 1.14.3(20.01.23.16)
- Verified changing to Japanese Calendar doesn't cause any issue with rewards
- Verified setting to Japanese Calendar and enabling rewards via onboarding works fine
- Verified setting to Japanese Calendar and enabling rewards via panel works fine 
- Verified changing to Japanese calendar after rewards is enabled doesn't cause any crash 
-------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.14.3(20.01.23.16)
- Verified changing to Japanese Calendar doesn't cause any issue with rewards
- Verified setting to Japanese Calendar and enabling rewards via onboarding works fine
- Verified setting to Japanese Calendar and enabling rewards via panel works fine 
- Verified changing to Japanese calendar after rewards is enabled doesn't cause any crash 
-------
Verification passed on iPhone 6 with iOS 12.4.4 running 1.14.3(20.01.23.16)
- Verified changing to Japanese Calendar doesn't cause any issue with rewards
- Verified setting to Japanese Calendar and enabling rewards via onboarding works fine
- Verified setting to Japanese Calendar and enabling rewards via panel works fine 
- Verified changing to Japanese calendar after rewards is enabled doesn't cause any crash 
-------
Verification passed on iPad Pro with iOS 13.3.1 running 1.14.3(20.01.23.16)
- Verified changing to Japanese Calendar doesn't cause any issue with rewards
- Verified setting to Japanese Calendar and enabling rewards via onboarding works fine
- Verified setting to Japanese Calendar and enabling rewards via panel works fine 
- Verified changing to Japanese calendar after rewards is enabled doesn't cause any crash 
-------
Verification passed on iPad Pro with iOS 12.4.4 running 1.14.3(20.01.23.16)
- Verified changing to Japanese Calendar doesn't cause any issue with rewards
- Verified setting to Japanese Calendar and enabling rewards via onboarding works fine
- Verified setting to Japanese Calendar and enabling rewards via panel works fine 
- Verified changing to Japanese calendar after rewards is enabled doesn't cause any crash 
-------
