### ISSUE TITLE
Private tab with Tor for iOS

### ISSUE THREAD

**Issue by JonathanDCohen** [brave/brave-ios#2023]
### Description: 
Brave [says that it uses Tor in private tabs](https://support.brave.com/hc/en-us/articles/360018121491-What-is-a-Private-Window-with-Tor-), yet my IP address is clearly visible.

### Steps to Reproduce 
  1. In a regular tab, visit ipinfo.io or any other tool to find your ip address
  2. In a private tab, do the same
  3. As a sanity check, use Onion Broswer to do the same

**Actual result:** 
My IP address is shown the same in both regular and private tabs, but in Onion Browser I get a defferent IP address

**Expected result:**
All three IP addresses should be different with high probability

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Every time

**Brave Version:** 
1.13 (19.11.06.18)

**Device details:** 
iPhone 8 iOS 13.1.3

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Tor is not yet available on iOS. Currently its only available for desktop.  

cc: @tomlowenthal @anthonypkeane

**Comment by iccub** [comment]
We need to wait for Apple to open up their WKWebView more
This article describes Tor possibilities very well

https://benjaminerhart.com/2018/03/state-of-the-onion-ios/

**Comment by JonathanDCohen** [comment]
Thanks for the read, that's an unfortunate situation -- it doesn't seem like this will be resolved any time soon.  It's surprising to me because Onion Browser works ok for me, but then again I don't use it heavily.

There should be something in the documentation to this effect.  If you all point me in the right direction I can take a stab at it.

**Comment by iccub** [comment]
@JonathanDCohen yeah, the Onion browser works, but uses an old webkit implementation called UIWebView, it is way more flexible, but Apple deprecated it in iOS 12.
Additionally, Apple started to warn developers to stop using that outdated UIWebView component, which will result in app rejection

More details:
1. https://github.com/ionic-team/capacitor/issues/1912
2. https://github.com/OnionBrowser/OnionBrowser/issues/47

**Comment by iccub** [comment]
6 years later, this is still impossible to implement with WKWebView, closing this ticket.
We will reopen once Apple allows us to modify network requests in WKWebView

**Comment by manfromarce** [comment]
Onion browser is now using WKWebView. Would it be possible for Brave to implement Tor the same way?
