### ISSUE TITLE
cant display downloaded pdf 

### ISSUE THREAD

**Issue by hanscees** [brave/brave-ios#2024]
### Description: 
If a pdf is downloaded, for instance an attachment to Gmail, it ends up in the downloaded section of brave in ios.
If you click on the pdf nothing happens

### Steps to Reproduce 
  1. Send yourself an email to your Gmail address with pdf attachement
  2. Open Gmail with brave ios browser and download the pdf
  3. Open downloads and try to open pdf

**Actual result:** 
Nothing happens, you can't view the pdf in the download section

**Expected result:**
Pdf is opened in a browser window

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always on my iPad with ios 13.2.3

**Brave Version:** 
1.13(19.11.06.18)

**Device details:** 
IPad 7th generation (2019)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 
Safari shows downloaded pdf.
![9ABE8514-3337-4289-AC6A-6217A136F6C7](https://user-images.githubusercontent.com/5273274/69580279-89f15780-0fd4-11ea-939d-6a732f94dc8b.png)

**Comment by srirambv** [comment]
This is fixed in 1.14 via https://github.com/brave/brave-ios/issues/1467. Should be available via next update.
