### ISSUE TITLE
TypeError: webkit.messageHandlers.contextMenuMessageHandler.postMessage

### ISSUE THREAD

**Issue by AoDev** [brave/brave-ios#2026]
### Description: 

```
TypeError: undefined is not an object
(evaluating 'webkit.messageHandlers.contextMenuMessageHandler.postMessage')
```

Recently, we have started to see this issue triggered for any touch in our website / application for Brave on iOS.

We don't have such call in our codebase.
But I did find a code in this repo that matches the issue in [ContextMenu.js](https://github.com/brave/brave-ios/blob/81418179e4dea5e6e88c2d5f10acbfb6933546e9/Client/Frontend/UserContent/UserScripts/AllFrames/AtDocumentEnd/ContextMenu.js)

### Steps to Reproduce 
I will try to create a standalone test if necessary, please bear with me as I am unsure of the exact conditions.

**Actual result:** 
* Touching anything on the screen will trigger the issue above. (Seems consistent with the event handler of the context menu)
* It seems that `webkit` isn't defined.

**Expected result:**
This should not happen. Especially that we are catching the errors and showing a crash report that prevents the user from going on, because each touch will trigger this report.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
Brave v1.13 (19.11.06.18)

This is a report from sentry.io with version and device.

```
browser: Firefox iOS 14.0
browser.name: Firefox iOS
device: iPhone
device.family: iPhone
handled: yes
level: error
mechanism: instrument
os: iOS 13.2.2
os.name: iOS
```

```
Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/14.0b12646 Mobile/15E148 Safari/605.1.15
```

**Website problems only:**
- did you check with Brave Shields down? **YES**.
- did you check in Safari/Firefox (WkWebView-based browsers)? **YES**

Safari works fine. Only brave in iOS triggers this issue. Brave on an Android device works well. 

### Additional Information

- We recently added Brave Rewards for our domain and it coincides, more or less, with the time of the issue. Although I can't see how these could be related, I prefer to mention it. We have removed them to see if it could be related.

**Comment by iccub** [comment]
Thanks for the report.
Could you check if this also happens on iOS Firefox?

That context menu helper script should be used only on iOS 12 devices, so this must be a bug on our end. I will investigate it later

**Comment by AoDev** [comment]
@iccub We tried on Firefox 2.0.2 (16690). No issue there apparently.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.18.17)
- Verified long-press context works on links work as expected
- Verified long-press context works on images work as expected
- Verified long-press context menu on newtab and tab container works as expected
---------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.18.17)
- Verified long-press context works on links work as expected
- Verified long-press context works on images work as expected
- Verified long-press context menu on newtab and tab container works as expected
---------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified long-press context works on links work as expected
- Verified long-press context works on images work as expected
- Verified long-press context menu on newtab and tab container works as expected
---------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified long-press context works on links work as expected
- Verified long-press context works on images work as expected
- Verified long-press context menu on newtab and tab container works as expected
---------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.18.17)
- Verified long-press context works on links work as expected
- Verified long-press context works on images work as expected
- Verified long-press context menu on newtab and tab container works as expected
