### ISSUE TITLE
Add latest translations for 1.14

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2029]

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.27.22)
* Verified token notification message is translated in Japanese/German/French/Russian
* Verified ad grant notification message is translated in Japanese/German/French/Russian
* Verified UI is translated in general
------------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.27.22)
* Verified token notification message is translated in Japanese/German/French/Russian
* Verified ad grant notification message is translated in Japanese/German/French/Russian
* Verified UI is translated in general
------------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.27.22)
* Verified token notification message is translated in Japanese/German/French/Russian
* Verified ad grant notification message is translated in Japanese/German/French/Russian
* Verified UI is translated in general
------------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.27.22)
* Verified token notification message is translated in Japanese/German/French/Russian
* Verified ad grant notification message is translated in Japanese/German/French/Russian
* Verified UI is translated in general
------------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.27.22)
* Verified token notification message is translated in Japanese/German/French/Russian
* Verified ad grant notification message is translated in Japanese/German/French/Russian
* Verified UI is translated in general
