### ISSUE TITLE
Image credits missing on new tab page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2032]
### Description: 
Image credits missing on new tab page

### Steps to Reproduce 
  1. Open a new tab which has the background image
  2. No image credit is shown

**Actual result:** 
iPhone
![image](https://user-images.githubusercontent.com/17010094/69675021-b4daba80-106b-11ea-800c-d80af28a328d.png)
iPad 
![image](https://user-images.githubusercontent.com/17010094/69675035-bc01c880-106b-11ea-8dcd-d3a4602232e2.png)

**Expected result:**
Image credit should be shown similar to desktop 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14(19.11.26.13)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
cc: @davidtemkin @anthonypkeane . Right now the credit is shown on long press on newtab which is not intuitive anyone who is on desktop would expect to see the credit shown on the new tab itself

**Comment by iccub** [comment]
This is intentional for now and will be changed in subsequent releases afaik
I would keep the ticket but bump it to 1.15

**Comment by bradleyrichter** [comment]
design for the image credits:

cc @deeppandya 

![image](https://user-images.githubusercontent.com/13509546/69890818-d1b20080-12ac-11ea-8c68-b38c1f7816c7.png)


background box:
radius: 6px
background: #000000; opacity: 0.2;

box margin: 10px
padding: 5px

"Photo by" - 12pt regular
"photograpgher name" - 12pt bold

Full text is hyperlinked to open a new tab with provided URL for each credit.

**Comment by anthonypkeane** [comment]
Long press is as per design for this upcoming release. 

This may change in later release but okay for this one. 

Thanks

**Comment by iccub** [comment]
I think we should close this ticket and make a new one after design is changed, wdyt @srirambv

**Comment by srirambv** [comment]
@iccub design form https://github.com/brave/brave-ios/issues/2032#issuecomment-559884032 is implemented on Android. I think it's ok to leave the issue open and have it done as per new design.

Per @anthonypkeane  in https://github.com/brave/brave-ios/issues/2032#issuecomment-559889299 which is already the current design so I'd say just move the issue to the correct milestone where the new design is being implemented to match Android

**Comment by iccub** [comment]
Fine by me

**Comment by jhreis** [comment]
This will be included in the initial product launch, so closing this, as it will not be independent.
