### ISSUE TITLE
Show more is not visible clearly on light theme when images are disabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2033]
### Description: 
Show more is not visible clearly on light theme when images are disabled

### Steps to Reproduce 
  1. Disable NTP images from setting
  2. Set browser to light theme
  3. `Show more` button is not clearly visible due to background gradient being same colour

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/69675237-303c6c00-106c-11ea-8b3e-834610116281.png)
![image](https://user-images.githubusercontent.com/17010094/69675245-34688980-106c-11ea-9c21-02ae0c8edc84.png)

**Expected result:**
Button should be visible clearly

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14(19.11.26.13)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Also the stats colour looks faded because of the background gradient colour

**Comment by iccub** [comment]
The gradient is in the spec so I would leave it for now. I personally prefer plain background color
I updated the gradient a bit so it looks better on more devices

<img width="731" alt="Zrzut ekranu 2019-11-27 o 14 50 00" src="https://user-images.githubusercontent.com/6950387/69729324-64746300-1126-11ea-9b98-2440fb5b100f.png">
<img width="544" alt="Zrzut ekranu 2019-11-27 o 14 43 31" src="https://user-images.githubusercontent.com/6950387/69729326-650cf980-1126-11ea-996b-44f0669590d8.png">

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.27.14)
* Verified disabling background images `Show more` is visible and not blended in with background gradient 
![image](https://user-images.githubusercontent.com/17010094/69749495-a0a0c700-1118-11ea-9663-bdb45888f947.png)

-------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.27.14)
* Verified disabling background images `Show more` is visible and not blended in with background gradient 
![image](https://user-images.githubusercontent.com/17010094/69749514-a8606b80-1118-11ea-8e72-155bd80d0c0c.png)

-------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.27.14)
* Verified disabling background images `Show more` is visible and not blended in with background gradient 
![image](https://user-images.githubusercontent.com/17010094/69749526-ad251f80-1118-11ea-8d47-69789f94afd8.png)

-------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.27.14)
* Verified disabling background images `Show more` is visible and not blended in with background gradient 
![image](https://user-images.githubusercontent.com/17010094/69749489-9b437c80-1118-11ea-8b99-d3a6ca240d22.png)

-------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.27.14)
* Verified disabling background images `Show more` is visible and not blended in with background gradient 
![image](https://user-images.githubusercontent.com/17010094/69749480-967ec880-1118-11ea-92d8-b313bd6fc393.png)
