### ISSUE TITLE
displaying a new NTP image whenever a new NTP is opened

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2036]
### Description: 

The current implementation caches the current image and displays it for every NTP until a website is loaded. Once you open a NTP after a webpage has been loaded, a new image will appear.

We should be displaying a new image whenever a NTP is opened. Basically the same behaviour/implementation that desktop uses. Whenever you open a NTP, a new image is displayed.

### Steps to Reproduce

  1. install & launch `1.14 (19.11.26.21)`
  2. open several NTP and you'll notice that we're using the same image
  3. load any random website (usually just select one from `Favourites`)
  4. open a NTP and you'll notice a new image will be displayed

**Actual result:** 

We're currently caching the NTP image and only displaying a new one if someone loads a website.

**Expected result:**

Should be using the same implementation as desktop and load a new image every time NTP is opened

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* Using `1.14 (19.11.26.21)`

**Device details:** 

* `iPhone 6s` running `iOS 13.2.2` - **Reproducible**
* `iPhone 6s+` running `iOS 12.4.1` - **Reproducible**
* `iPad Air 3rd Gen` running `iOS 13.3` - **Reproducible**
* `iPad Mini 4` running `iOS 12.4.1` - **Reproducible**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)?  `N/A`

### Additional Information

CCing @brave/legacy_qa @jhreis @davidtemkin @anthonypkeane @jamesmudgett

**Comment by kjozwiak** [comment]
Bumping into `1.15` after speaking with @aekeus and @jhreis. This will get fixed in the next iteration. We need to get the current NTP implementation out ASAP.

**Comment by iccub** [comment]
bumping to next release

**Comment by srirambv** [comment]
Verification passed on iPhone X with iOS 13.5 running 1.18(20.6.16.8)
- Verified opening a new tab loads a new background images
- Verified opening a new tab loads a SI on 2nd and every 4th tab
- Verified opening a new tab in PB mode also loads a new background image 
- Verified no SI images are loaded in PB mode
--------
Verification passed on iPhone 7+ with iOS 13.4.5 running 1.18(20.6.16.8)
- Verified opening a new tab loads a new background images
- Verified opening a new tab loads a SI on 2nd and every 4th tab
- Verified opening a new tab in PB mode also loads a new background image 
- Verified no SI images are loaded in PB mode
--------
Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.6.16.8)
- Verified opening a new tab loads a new background images
- Verified opening a new tab loads a SI on 2nd and every 4th tab
- Verified opening a new tab in PB mode also loads a new background image 
- Verified no SI images are loaded in PB mode
--------
