### ISSUE TITLE
adding ability to edit/move favourites from NTP when viewing via "Show More"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2037]
### Description: 

@srirambv mentioned this is a known issue and is being worked on but creating this issue as place holder so we don't forget to QA this once it lands.

When viewing favourites via the `Show More` button under NTP, there's no way of editing/moving around favourites. This becomes problematic when you want to remove/move a website that's currently not appearing in the first row of the NTP. 

### Steps to Reproduce 

  1. install & launch `1.14 (19.11.26.21)`
  2. Under NTP, tap on `Show More`
  3. You'll notice that there's no way of editing/moving/removing favourites in this view

**Actual result:** 

Unable to edit/move/remove favourites when viewing via the `Show More` under NTP. Example:

![IMG_9940](https://user-images.githubusercontent.com/2602313/69691833-27648e00-109e-11ea-9929-2bb40eb92b28.PNG)

**Expected result:**

Users should be able to edit/move/remove favourites when viewing it from the `Show More` screen.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible when using the STR mentioned above.

**Brave Version:** 

* Using `1.14 (19.11.26.21)`

**Device details:** 

* `iPhone 6s` running `iOS 13.2.2` - **Reproduced**
* `iPhone 6s+` running `iOS 12.4.1` - **Reproduced**
* `iPad Air 3rd Gen` running `iOS 13.3` - **Reproduced**
* `iPad Mini 4` running `iOS 12.4.1` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @brave/legacy_qa @anthonypkeane @jhreis

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.27.14)
* Verified edit button shows at the bottom of the sheet
* Verified able to go into edit mode and edit the favourite 
* Verified able to reorder favourites in edit mode
* Verified able to delete favourites in edit mode 
-------------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.27.14)
* Verified edit button shows at the bottom of the sheet
* Verified able to go into edit mode and edit the favourite 
* Verified able to reorder favourites in edit mode
* Verified able to delete favourites in edit mode 
-------------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.27.14)
* Verified edit button shows at the bottom of the sheet
* Verified able to go into edit mode and edit the favourite 
* Verified able to reorder favourites in edit mode
* Verified able to delete favourites in edit mode 
-------------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.27.14)
* Verified edit button shows at the bottom of the sheet
* Verified able to go into edit mode and edit the favourite 
* Verified able to reorder favourites in edit mode
* Verified able to delete favourites in edit mode 
-------------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.27.14)
* Verified edit button shows at the bottom of the sheet
* Verified able to go into edit mode and edit the favourite 
* Verified able to reorder favourites in edit mode
* Verified able to delete favourites in edit mode
