### ISSUE TITLE
sometimes brave automatically starts creating NTP's when using a wireless keyboard

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2038]
### Description: 

Sometimes Brave gets into a weird state where it starts automatically creating NTP's when using a wireless keyboard. This usually happens when you attempt to create a new tab via <kbd>CMD</kbd> + <kbd>T</kbd> when another tab is loading a website.

I couldn't seem to reproduce this on `iOS 13` so assuming it only affects `iOS 12` as it's probably worse at handling wireless keyboards.

### Steps to Reproduce

**Prerequisite**: Ensure that you have a wireless keyboard connected to the device

  1. launch `1.14 (19.11.26.21)`
  2. using the keyboard, copy a website URL so you have something in the clipboard buffer
  3. quickly create a new tab using <kbd>CMD</kbd> + <kbd>T</kbd>, paste the URL and hit "Enter"
  4. while the above website is loading, create a new tab quickly using <kbd>CMD</kbd> + <kbd>T</kbd> and paste the URL again and press "Enter" (try doing this before the previous tab finished loading)

Eventually you'll get into a state where Brave starts creating NTP automatically until you intervene.

**Actual result:** 

Example of the issue occurring: https://youtu.be/YzvUzCuB4ig (creation of tabs is automatic)

**Expected result:**

Brave shouldn't be getting into a state where it starts creating NTP indefinitely until the user intervenes.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

It's not 100% but it only takes a few attempts to reproduce. I would say about ~70%.

**Brave Version:** 

* using `1.14 (19.11.26.21)`

**Device details:** 

* `iPhone 6s` running `iOS 13.2.2` - **Couldn't reproduce**
* `iPhone 6s+` running `iOS 12.4.1` - **Reproduced**
* `iPad Air 3rd Gen` running `iOS 13.3` - **Couldn't reproduce**
* `iPad Mini 4` running `iOS 12.4.1` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @brave/legacy_qa @anthonypkeane @jhreis

**Comment by kylehickinson** [comment]
iOS 12 no longer supported
