### ISSUE TITLE
changing external link request from a regular modal to "AlertPopupView"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2039]
### Description: 

We should be using `AlertPopupView` rather than a regular modal when warning users re: clicking on links that will launch third party applications.

This is a follow up from the discussion via https://github.com/brave/brave-ios/issues/551#issuecomment-558290316.

### Steps to Reproduce

  1. navigate to `mailto://abc@abc.com` and you'll get a regular modal

**Actual result:** 

<img width="490" alt="Screen Shot 2019-11-27 at 3 31 48 AM" src="https://user-images.githubusercontent.com/2602313/69706836-863dfd80-10c6-11ea-83fc-176db6793ff9.png">

**Expected result:**

Should be using `AlertPopupView` instead of a regular modal as per https://github.com/brave/brave-ios/issues/551#issuecomment-558290316.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible when using the above STR.

**Brave Version:** 

* using `1.14 (19.11.26.21)`

**Device details:** 

* `iPhone 6s` running `iOS 13.2.2` - **Reproduced**
* `iPhone 6s+` running `iOS 12.4.1` - **Reproduced**
* `iPad Air 3rd Gen` running `iOS 13.3` - **Reproduced**
* `iPad Mini 4` running `iOS 12.4.1` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @jumde @anthonypkeane @jhreis @brave/legacy_qa

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.12.10)
- Verified AlertPopupView is as per design mentioned in #2055 
- Verified selecting `Allow` switch the focus to external app
- Verified selecting `Don't Allow` dismisses the alert and focus stays on Brave
![image](https://user-images.githubusercontent.com/17010094/74802077-bd573000-52fe-11ea-8c57-90b48b2d2544.png)

------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified AlertPopupView is as per design mentioned in #2055 
- Verified selecting `Allow` switch the focus to external app
- Verified selecting `Don't Allow` dismisses the alert and focus stays on Brave
![image](https://user-images.githubusercontent.com/17010094/74802002-8b45ce00-52fe-11ea-903d-ac414ed9cf28.png)

------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.12.10)
- Verified AlertPopupView is as per design mentioned in #2055 
- Verified selecting `Allow` switch the focus to external app
- Verified selecting `Don't Allow` dismisses the alert and focus stays on Brave
![image](https://user-images.githubusercontent.com/17010094/74802002-8b45ce00-52fe-11ea-903d-ac414ed9cf28.png)

------
Verification passed on iPad Pro with iOS 13.4 running 1.15(20.02.12.10)
- Verified AlertPopupView is as per design mentioned in #2055 
- Verified selecting `Allow` switch the focus to external app
- Verified selecting `Don't Allow` dismisses the alert and focus stays on Brave
![image](https://user-images.githubusercontent.com/17010094/74802008-900a8200-52fe-11ea-92dc-bf32fcc13df3.png)

------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.12.10)
- Verified AlertPopupView is as per design mentioned in #2055 
- Verified selecting `Allow` switch the focus to external app
- Verified selecting `Don't Allow` dismisses the alert and focus stays on Brave
![image](https://user-images.githubusercontent.com/17010094/74802014-94cf3600-52fe-11ea-9222-4214eca5ab91.png)

------
