### ISSUE TITLE
iPad doesn't use desktop UA by default

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2042]
### Description: 
iPad doesn't use desktop UA by default

### Steps to Reproduce 
  1. Clean install browser
  2. Visit whatsmyua.info 
  3. Shows mobile UA instead of desktop

**Actual result:** 
![12ua](https://user-images.githubusercontent.com/17010094/69744174-ad6bed80-110d-11ea-86ec-d57382c3d677.gif)

**Expected result:**
![13ua](https://user-images.githubusercontent.com/17010094/69744183-b1980b00-110d-11ea-9c55-a22fbbaeb072.gif)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13

**Device details:** 
iPad (iOS 12.4)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
Found while testing #1959

**Comment by kylehickinson** [comment]
Did it previously do this before 1.12? (iOS 13 release)

**Comment by iccub** [comment]
iOS 12 uses mobile UA by default, desktop defaults is on iOS 13+
