### ISSUE TITLE
changing theme before opting into "Rewards" via onboarding doesn't change the theme for sample ad

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2044]
### Description: 

When you disable `Dark` mode via iOS's smart centre before opting into `Rewards` via onboarding, the `First Time Ad` notification will still use the `Dark` theme instead of the `Light` theme.

Follow up to the work that was done via https://github.com/brave/brave-ios/issues/1739. 

### Steps to Reproduce 

  1. install & launch `1.14 (19.11.27.14)` (ensure you have `Dark Mode` in the `Control Center`
  2. before opting into `Rewards` with the `Turn On` button, disable `Dark` mode via `Control Center`
  3. you'll notice that the theme changed as expected but the ad notification will still use `Dark`

**Actual result:** 

Example of the issue occurring: https://youtu.be/xKw4DV2NidY

**Expected result:**

![IMG_8CD0257F7FCE-1](https://user-images.githubusercontent.com/2602313/69755866-304d7200-1127-11ea-8e93-cb5e6870bdb5.jpeg)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible when going through the STR mentioned above.

**Brave Version:** 

* using `1.14 (19.11.27.14)`

**Device details:** 

* `iPhone 6s` running `iOS 13.2.2` - **Reproduced**
* `iPad Air 3rd Gen` running `iOS 13.3` - **Couldn't reproduce**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @anthonypkeane @jhreis @brave/legacy_qa

**Comment by kylehickinson** [comment]
Closed as this feature is no longer supported in new Rewards on Brave iOS
