### ISSUE TITLE
"find in page" text field really small making it hard to use the feature

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2045]
### Description: 

Looks like the `Find in page` text field that appears at the bottom of the screen is really small which makes it hard to use the arrow keys. Looks like this regressed as it looks/behaves fine under `1.13 (19.11.06.18)`

### Steps to Reproduce

  1. install & launch `1.14 (19.11.27.19)`
  2. visit https://wikipedia.org/ and initiate a `Find in Page` via the URL bar or `Share With` menu

**Actual result:** 

![IMG_9941](https://user-images.githubusercontent.com/2602313/69761849-94c3fd80-1136-11ea-9187-e492fdf1e9da.PNG)

![IMG_0033](https://user-images.githubusercontent.com/2602313/69761850-94c3fd80-1136-11ea-89a6-f058873a1e9e.PNG)

**Expected result:**

![IMG_9942](https://user-images.githubusercontent.com/2602313/69761994-fedca280-1136-11ea-88cd-a8390d3fac8b.PNG)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* using `1.13 (19.11.06.18)` - **Couldn't reproduce**
* using `1.14 (19.11.27.19)` - **Reproduced**

**Device details:** 

`iPhone 6s` running `iOS 13.2.2` - **Reproduced**
`iPhone 6s+` running `iOS 12.4.1` - **Reproduced**
`iPad Air 3rd G` running `iOS 13.3` - **Reproduced**
`iPad Mini 4` running `iOS 12.4.1` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @brave/legacy_qa @jhreis @anthonypkeane

**Comment by kylehickinson** [comment]
Probably related to #1803 / #1736

**Comment by srirambv** [comment]
* Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.27.22)
![image](https://user-images.githubusercontent.com/17010094/69766503-51718b00-1146-11ea-8ced-f410abd99d2f.png)

* Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.27.22)
![image](https://user-images.githubusercontent.com/17010094/69766496-4585c900-1146-11ea-8b6c-b2d3098f97fd.png)

* Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.27.22)
![image](https://user-images.githubusercontent.com/17010094/69766490-3dc62480-1146-11ea-8b24-5e90f54fdb9a.png)

* Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.27.22)
![image](https://user-images.githubusercontent.com/17010094/69766487-399a0700-1146-11ea-9e8c-e7d21b0398f2.png)

* Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.27.22)
![image](https://user-images.githubusercontent.com/17010094/69766498-4b7baa00-1146-11ea-8eaa-c48ebfa7c5be.png)
