### ISSUE TITLE
Add translations for opening external links popup

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2047]
https://github.com/brave/brave-ios/issues/551
translations for this PR got removed by accident

**Comment by iccub** [comment]
Should be resolved in https://github.com/brave/brave-ios/issues/2047

**Comment by iccub** [comment]
Test plan:

- Use non-english language on your device
- Search for `Brave App Store`
- tap on, install
- verify it's translated

<img width="544" alt="Zrzut ekranu 2019-12-10 o 12 55 34" src="https://user-images.githubusercontent.com/6950387/70527559-802b3080-1b4c-11ea-8a73-8bd1ef51e7dc.png">

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14.2(19.12.09.17)

![image](https://user-images.githubusercontent.com/17010094/70662615-9ad8d480-1c34-11ea-90ef-1b35fd537b58.png)
![image](https://user-images.githubusercontent.com/17010094/70662625-a1674c00-1c34-11ea-93ac-666181b13894.png)
![image](https://user-images.githubusercontent.com/17010094/70662651-acba7780-1c34-11ea-9524-00152f48422b.png)
-------
Verification passed on iPad Pro with iOS 13.2 running 1.14.2(19.12.11.21)

![image](https://user-images.githubusercontent.com/17010094/70665478-a9c28580-1c3a-11ea-96af-5196f871ef10.png)
![image](https://user-images.githubusercontent.com/17010094/70665487-adeea300-1c3a-11ea-9e79-0da80571345f.png)
![image](https://user-images.githubusercontent.com/17010094/70665503-b21ac080-1c3a-11ea-8f8b-d66f19cedf23.png)
------

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.14.2 (19.12.11.21)`

![IMG_9974](https://user-images.githubusercontent.com/2602313/70678979-bd351700-1c61-11ea-899f-cfa7de735447.PNG)

![IMG_9973](https://user-images.githubusercontent.com/2602313/70678980-bd351700-1c61-11ea-85de-8a30639bc9d2.PNG)

![IMG_9972](https://user-images.githubusercontent.com/2602313/70678982-bd351700-1c61-11ea-9c79-789184c6e449.PNG)

Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.14.2 (19.12.11.21)`

![IMG_0283](https://user-images.githubusercontent.com/2602313/70679295-b0fd8980-1c62-11ea-8cf8-d65c4465c1e7.JPG)

![IMG_0282](https://user-images.githubusercontent.com/2602313/70679296-b0fd8980-1c62-11ea-82c7-783ee3108efe.JPG)

![IMG_0281](https://user-images.githubusercontent.com/2602313/70679297-b0fd8980-1c62-11ea-9c72-431262a427d4.JPG)
