### ISSUE TITLE
DDG modal blocks pin code when opening a PT via 3D touch

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2048]
### Description: 
DDG modal blocks pin code when opening a PT via 3D touch

### Steps to Reproduce 
  1. Clean install Brave
  2. Enable Pin 
  3. Background the app
  4. Force touch to open private tab
  5. DDG modal block pin code

**Actual result:** 
iPhone:
![DDG](https://user-images.githubusercontent.com/17010094/69812735-bff22f80-11be-11ea-82bd-025f7b9d6793.gif)
iPad:
![ipadDDG](https://user-images.githubusercontent.com/17010094/69813111-8b32a800-11bf-11ea-9eff-266da24793ed.gif)

**Expected result:**
DDG modal should be shown once browser is unlocked

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13

**Device details:** 
iPhone & iPad

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by GeetaSarvadnya** [comment]
Reproduced the issue in iPhone 8 (iOS 13.2.3) brave version 1.13 (19.11.06.18)

**Comment by iccub** [comment]
Edge case, the popup shows only after PBM is opened for the first time. Unlikely the user will do it like that. Good find though

**Comment by ghost** [comment]
How about we ditch the DDG modal entirely. I'm tired of seeing it for every private window. No option to dismiss.

**Comment by iccub** [comment]
Not applicable anymore once https://github.com/brave/brave-ios/pull/3862 is merged, closing
