### ISSUE TITLE
Database crashes with sync

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2049]
We have a lot of crash reports, triggered in `Sync.getExistingObjects` when accessing a shared device.
This is possibly a concurrency problem.

<img width="599" alt="Zrzut ekranu 2019-11-28 o 16 32 34" src="https://user-images.githubusercontent.com/6950387/69818309-c4d5d400-11fc-11ea-8195-e5157c9049b3.png">

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14.1(19.12.04.02)
* Verified upgrading to 1.14.1 retained the sync devices intact
* Verified editing/deleting bookmark from iPhone doesn't crash
* Verified editing/deleting bookmarks from other devices propagate changes to iPhone and doesn't cause any crash
* Verified removing other devices from sync chain doesn't cause the browser to crash on iPhone
-------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14.1(19.12.05.00)
* Verified upgrading to 1.14.1 retained the sync devices intact
* Verified editing/deleting bookmark from iPhone doesn't crash
* Verified editing/deleting bookmarks from other devices propagate changes to iPhone and doesn't cause any crash
* Verified removing other devices from sync chain doesn't cause the browser to crash on iPhone
-------
Verification passed on iPhone Pro with iOS 13.2 running 1.14.1(19.12.5.00)
* Verified upgrading to 1.14.1 retained the sync devices intact
* Verified editing/deleting bookmark from iPhone doesn't crash
* Verified editing/deleting bookmarks from other devices propagate changes to iPhone and doesn't cause any crash
* Verified removing other devices from sync chain doesn't cause the browser to crash on iPhone
