### ISSUE TITLE
Labels on NTP Hard to Read in Dark Mode

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ios#2059]
### Description: 
Labels on _New Tab Page_ are hard to read with Dark Mode enabled.

### Steps to Reproduce 
  1. Enable Dark Mode
  2. Open New Tab Page

**Actual result:** 
https://twitter.com/gcheseaux/status/1200722850681892865

**Expected result:**
More contrast in labels

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
TBD

**Device details:** 
iOS 13.2

**Comment by jonathansampson** [comment]
I am unable to reproduce on Brave 1.13 on iOS 13.2.3.

![Screenshot 2019-11-30 at 6 05 02 AM (2)](https://user-images.githubusercontent.com/815158/69899695-31a1b900-1338-11ea-859a-fc0f2720feff.png)

**Comment by srirambv** [comment]
+1 from @ha1zum via #2094

**Comment by rismanrp** [comment]
> +1 from @ha1zum via #2094

In my case it’s Light Mode but Private Tab

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.18(20.06.16.8) 
- Verified disabling background images and setting the theme to dark shows favourites text clearly
- Verified disabling background images and setting the theme to dark on PB also show favourites text clearly
- Verified toggle theme from control centre doesn't affect the visibility of text on favourites

------
Verification passed on iPhone 7+  with iOS 13.4.5 running 1.18(20.06.16.8) 
- Verified disabling background images and setting the theme to dark shows favourites text clearly
- Verified disabling background images and setting theme to dark on PB also show favourites text clearly
- Verified toggle theme from control centre doesn't affect the visibility of text on favourites
-------
Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.06.16.8) 
- Verified disabling background images and setting the theme to dark shows favourites text clearly
- Verified disabling background images and setting the theme to dark on PB also show favourites text clearly
