### ISSUE TITLE
Enable downloading of files into the Downloads folder

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#206]
Enable the UI for downloading of files into the Downloads folder by reverting changes made within #205

**Comment by tmancey** [comment]
Closing ticket as no longer required as #195 resolves the issue

**Comment by btlechowski** [comment]
Because of this issue all binary files are opened as text files in the browser.

STR:
1. Open https://github.com/brave/brave-browser/releases
2. Click a zip file

Actual Result:
![IMG_0002](https://user-images.githubusercontent.com/34715963/55168998-3e03bf80-5174-11e9-94b5-65dc77d463dc.PNG)

cc @brave/legacy_qa

**Comment by iccub** [comment]
Removing `needs design` label, first iteration will use mostly Firefoxes UI

**Comment by iccub** [comment]
Test plan:
- open https://www.thinkbroadband.com/download and try to download a file
see if it shows in downloads folder

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12
* Verified on clean install download folder is created in file.app
* Verified on upgrade install download folder is created in file.app

Verification **PASSED** on `iPad Air 3rd Generation` with `iOS 13.1` running `1.12 (19.09.07.03)`:

* Went through the cases outlined under https://github.com/brave/brave-ios/issues/1438
* Went through the cases outlined under https://github.com/brave/brave-ios/issues/206#issuecomment-529030270
* ensured that a `Brave` folder is created under `file.app` for a brand new install
* ensured that a `Brave` folder is created under `file.app` when updating from `1.11.4 (19.8.29.21)` to `1.12 (19.09.07.03)`
* Found https://github.com/brave/brave-ios/issues/1516 when going through the above

Verification passed on iPhone 7+ with iOS 12.4.1 running 1.12(19.09.13.06)
* Verified on clean install download folder is created in file.app
* Verified on upgrade install download folder is created in file.app
