### ISSUE TITLE
Add latest translations for 1.14.1

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#2063]
### Description: 

Pull in translations for 1.14.1.

Some of the strings that should be translated are:

- `Photo by` on the NTP
- `View on` when pressing the NTP credit button (the one that says `Photo by`)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14.1
* Verified `Photo by` and `View on` is translated in 
French
![image](https://user-images.githubusercontent.com/17010094/70198429-dcb9c600-16dc-11ea-80fb-72a36a6adf5d.png)
German
![image](https://user-images.githubusercontent.com/17010094/70198368-b431cc00-16dc-11ea-9cc6-4b6ff392c4ea.png)
Russian
![image](https://user-images.githubusercontent.com/17010094/70198389-c01d8e00-16dc-11ea-9f31-25e877d466bb.png)
Polish
![image](https://user-images.githubusercontent.com/17010094/70198400-c57ad880-16dc-11ea-8b01-c686b212908c.png)
Chinese
![image](https://user-images.githubusercontent.com/17010094/70198434-e17e7a00-16dc-11ea-819f-737e4f549ee2.png)
Spanish
![image](https://user-images.githubusercontent.com/17010094/70198377-bb58da00-16dc-11ea-9cd1-18f5cd1e9908.png)
---------------
Verification passed on iPad Pro with iOS 13.2 running 1.14.1(19.12.05.00)
Chinese
![image](https://user-images.githubusercontent.com/17010094/70249798-eb3ec680-174a-11ea-816a-9ea094a37371.png)
Russian
![image](https://user-images.githubusercontent.com/17010094/70249821-f3970180-174a-11ea-8b15-1e3484fea9af.png)
French
![image](https://user-images.githubusercontent.com/17010094/70249835-f8f44c00-174a-11ea-928d-49d945bda919.png)
German
![image](https://user-images.githubusercontent.com/17010094/70249848-fe519680-174a-11ea-8482-8e96fb583b7f.png)
Polish
![image](https://user-images.githubusercontent.com/17010094/70249858-04477780-174b-11ea-957a-3154218caadf.png)
Italian
![image](https://user-images.githubusercontent.com/17010094/70249877-0d384900-174b-11ea-913f-d4967c7f586a.png)
-------------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14.1(19.12.05.00)
Korean
![image](https://user-images.githubusercontent.com/17010094/70250234-92236280-174b-11ea-981e-bcf8512120c7.png)
Portugese (Brazil)
![image](https://user-images.githubusercontent.com/17010094/70250253-994a7080-174b-11ea-8bf8-a0faff126626.png)
Ukranian
![image](https://user-images.githubusercontent.com/17010094/70250264-9e0f2480-174b-11ea-9deb-3cea5f67fbda.png)
