### ISSUE TITLE
Rewards Auto-Contribute budget should include "Up To" before the amount

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2068]
The copy for auto-contribute amount should say "Up to X BAT". It currently just has "X BAT"

Desktop:
<img width="629" alt="image" src="https://user-images.githubusercontent.com/529104/70158324-0ba44d80-1685-11ea-830d-8e8b6adff3f0.png">

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.3.1 running 1.15(20.01.07.17)
![image](https://user-images.githubusercontent.com/17010094/72277886-ccacd480-3600-11ea-83f9-52097a0566f7.png)

------

Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.01.07.17)
![image](https://user-images.githubusercontent.com/17010094/72278979-1dbdc800-3603-11ea-848f-0a1c5482b485.png)

------
Verification passed on iPhone 6 with iOS 12.4.1 running 1.15(20.01.07.17)
![image](https://user-images.githubusercontent.com/17010094/72279301-d5eb7080-3603-11ea-86ef-86dcbecb075a.png)

------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.01.07.17)
![image](https://user-images.githubusercontent.com/17010094/72278964-17c7e700-3603-11ea-9b1d-170f419a1279.png)

------
Verification passed on iPad Pro with iOS 12.4.1 running 1.15(20.01.07.17)
![image](https://user-images.githubusercontent.com/17010094/72279038-3fb74a80-3603-11ea-88b3-ac63b071d005.png)
