### ISSUE TITLE
Enable iTunes file sharing to allow users to access downloaded files within the Downloads folder

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#207]
Enable iTunes file sharing by adding the UIFileSharingEnabled key set to YES to the info.plist to allow users to access downloaded files within the Downloads folder from iTunes

**Comment by tmancey** [comment]
Closing ticket as no longer required as #195 resolves the issue

**Comment by iccub** [comment]
Will be fixed in https://github.com/brave/brave-ios/issues/206
