### ISSUE TITLE
Implement custom tip amount UI

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2072]
### Description: 

Please implement the custom tip amount UI

![image (1)](https://user-images.githubusercontent.com/7606853/70190741-9b5cf280-16ab-11ea-8ee0-58f7aba9f5b4.png)

Internal Chat: https://bravesoftware.slack.com/archives/G7EDVBQ5C/p1575497354081500

**Comment by kylehickinson** [comment]
@anthonypkeane That link to internal chat doesn't seem to work for me. Also I don't see this feature on desktop currently. Is this something for future?

**Comment by kylehickinson** [comment]
Closed as this feature is no longer supported in new Rewards on Brave iOS
