### ISSUE TITLE
sliding up on NTP dismisses the OSK but URL still expects input

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2073]
### Description: 

When the OSK appears automatically when opening a new tab, swiping up on the NTP page dismisses the OSK but the URL still expects input. When the OSK is dismissed, the URL should return to normal and display both the `BAT` and `Shield` icons. Currently, it will still display `Cancel` even if the OSK isn't visible anymore/has been dismissed.

### Steps to Reproduce 

  1. install & launch `1.14.1 (19.12.04.20)`
  2. skip the onboarding and ensure that `Auto Open Keyboard` is enabled via `Settings`
  3. open a NTP and the OSK should be displayed
  4. swipe up on the NTP and the OSK will be disabled

You'll notice that the URL doesn't return to normal and still expects input from the OSK.

**Actual result:** 

![IMG_9962](https://user-images.githubusercontent.com/2602313/70191663-7e361d00-16c7-11ea-9307-ccd374844d8f.PNG)

**Expected result:**

![IMG_14923083C6F3-1](https://user-images.githubusercontent.com/2602313/70191684-9148ed00-16c7-11ea-9532-f02c8f8ca6d8.jpeg)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible when using the above STR.

**Brave Version:** 

* Using `1.14 (19.11.27.22)` - **Reproducible**
* Using `1.14.1 (19.12.04.20)` - **Reproducible**

**Device details:** 

* `iPhone 6s+` running `iOS 12.4.1` - Reproduced
* `iPhone 6s` running `iOS 13.2.1` - Reproduced
* `iPad Mini 4` running `iOS 12.4.1` - Reproduced
* `iPad Air (3rd Gen)` running `iOS 13.3` - Reproduced

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)?  `N/A`

### Additional Information

CCing @brave/legacy_qa @jhreis @anthonypkeane

**Comment by kylehickinson** [comment]
FYI new flow will allow this due to nature of new scrollable favorites overlay, after you click cancel it will dismiss the overlay

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 13.5.1 running 1.18(20.06.23.18)
- Verified OSK is dismissed when swiped down but favourites overlay is still retained
- Verified shields/rewards button is only shown when the cursor is not in URL bar
-----------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.18(20.06.23.18)
- Verified OSK is dismissed when swiped down but favourites overlay is still retained
- Verified shields/rewards button is only shown when the cursor is not in URL bar
-----------
Verification passed on iPhone XR with iOS 13.5 running 1.18(20.06.23.18)
- Verified OSK is dismissed when swiped down but favourites overlay is still retained
- Verified shields/rewards button is only shown when the cursor is not in URL bar
-----------
Verification passed on iPad Pro with iOS 13.6 running 1.18(20.06.23.18)
- Verified OSK is dismissed when swiped down but favourites overlay is still retained
- Verified shields/rewards button is only shown when the cursor is not in URL bar
-----------
Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.06.23.18)
- Verified OSK is dismissed when swiped down but favourites overlay is still retained
- Verified shields/rewards button is only shown when the cursor is not in URL bar
-----------
