### ISSUE TITLE
OSK being displayed even though "Auto Open Keyboard" is disabled

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2074]
### Description: 

OSK is being displayed even when `Auto Open Keyboard` is disabled by default via `Settings`

### Steps to Reproduce 

  1. install & launch `1.14.1 (19.12.04.20)`
  2. skip the onboarding
  3. the OSK will automatically be displayed even though `Auto Open Keyboard` is disabled

**Actual result:** 

Example of the issue occurring: https://youtu.be/QStrxDqHF7o

**Expected result:**

OSK shouldn't be displayed when `Auto Open Keyboard` is disabled which is the default setting

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible when using the above STR.

**Brave Version:** 

* Using `1.14.1 (19.12.04.20)`

**Device details:** 

* `iPhone 6s+` running `iOS 12.4.1` - **Reproduced**
* `iPhone 6s` running `iOS 13.2.1` - **Reproduced**
* `iPad Mini 4` running `iOS 12.4.1` - **Reproduced**
* `iPad Air (3rd Gen)` running `iOS 13.3` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @brave/legacy_qa @jhreis @anthonypkeane

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.12.05.18)
* Upgrade
  - Open a new tab in 1.14, upgrade to 1.14.1, no keyboard is shown
  - Enable and disable the setting and open a new tab, no keyboard is shown
* Clean install
  - Verified skipping onboarding doesn't show the keyboard on the new tab
  - Verified opening a private tab or normal tab via context menu doesn't show keyboard
  - Verified opening a tab via tab tray doesn't show the keyboard
  - Verified opening tab tray, switching to private and opening a new tab via + doesn't show keyboard
  - Verified switching to PBO only doesn't show the keyboard on the new tab once the setting is closed
----------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.12.05.18)
* Upgrade
  - Open a new tab in 1.14, upgrade to 1.14.1, no keyboard is shown
  - Enable and disable the setting and open a new tab, no keyboard is shown
* Clean install
  - Verified skipping onboarding doesn't show the keyboard on the new tab
  - Verified opening a private tab or normal tab via context menu doesn't show keyboard
  - Verified opening a tab via tab tray doesn't show the keyboard
  - Verified opening tab tray, switching to private and opening a new tab via + doesn't show keyboard
  - Verified switching to PBO only doesn't show the keyboard on the new tab once the setting is closed
----------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.12.05.18)
* Upgrade
  - Open a new tab in 1.14, upgrade to 1.14.1, no keyboard is shown
  - Enable and disable the setting and open a new tab, no keyboard is shown
* Clean install
  - Verified skipping onboarding doesn't show the keyboard on the new tab
  - Verified opening a private tab or normal tab via context menu doesn't show keyboard
  - Verified opening a tab via tab tray doesn't show the keyboard
  - Verified opening tab tray, switching to private and opening a new tab via + doesn't show keyboard
  - Verified switching to PBO only doesn't show the keyboard on the new tab once the setting is closed
----------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.12.05.18)
* Upgrade
  - Open a new tab in 1.14, upgrade to 1.14.1, no keyboard is shown
  - Enable and disable the setting and open a new tab, no keyboard is shown
* Clean install
  - Verified skipping onboarding doesn't show the keyboard on the new tab
  - Verified opening a private tab or normal tab via context menu doesn't show keyboard
  - Verified opening a tab via tab tray doesn't show the keyboard
  - Verified opening tab tray, switching to private and opening a new tab via + doesn't show keyboard
  - Verified switching to PBO only doesn't show the keyboard on the new tab once the setting is closed
----------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.12.05.18)
* Upgrade
  - Open a new tab in 1.14, upgrade to 1.14.1, no keyboard is shown
  - Enable and disable the setting and open a new tab, no keyboard is shown
* Clean install
  - Verified skipping onboarding doesn't show the keyboard on the new tab
  - Verified opening a private tab or normal tab via context menu doesn't show keyboard
  - Verified opening a tab via tab tray doesn't show the keyboard
  - Verified opening tab tray, switching to private and opening a new tab via + doesn't show keyboard
  - Verified switching to PBO only doesn't show the keyboard on the new tab once the setting is closed
----------
