### ISSUE TITLE
dismissing OSK in a NTP and switching to another tab that has a website opened will still have the URL selected

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2078]
### Description: 

When dismissing the OSK on the NTP and than switching to another tab via the `Tab Manager` the URL bar will be selected and the NTP page will be displayed rather than displaying the opened website. Tapping on `Cancel` on the URL bar will display the website as expected.

Most likely similar to https://github.com/brave/brave-ios/issues/2073.

### Steps to Reproduce

  1. install & run `1.14.1 (19.12.04.20)`
  2. open several websites in ~2-3 tabs
  3. open a NTP, dismiss the keyboard by sliding up on the NPT (https://github.com/brave/brave-ios/issues/2073)
  4. tap on the `Tab Manager` and switch over to a tab that has a website opened

You'll notice that the URL is selected and the NTP image is being shown rather than loading the website.

**Actual result:** 

Example of the issue: https://youtu.be/DB5rbpi7fhE

**Expected result:**

When switching to another tab using the `Tab Manager`, the website should always be displayed. The URL shouldn't be displayed because the URL expects input from the OSK.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* Using `1.14 (19.11.27.22)` - **Reproducible**
* Using `1.14.1 (19.12.04.20)` - **Reproducible**

**Device details:** 

* `iPhone 6s+` running `iOS 12.4.1` - **Reproduced**
* `iPhone 6s` running `iOS 13.2.1` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

@brave/legacy_qa @jhreis @anthonypkeane

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.18(20.06.18.18)
- Verified no OSK is popped up when a new tab is opened via tab tray or new tab button 
- Verified no settings for Auto open keyboard 
--------
Verification passed on iPhone 7+ with iOS 13.5.1 running 1.18(20.06.18.18)
- Verified no OSK is popped up when a new tab is opened via tab tray or new tab button 
- Verified no settings for Auto open keyboard 
--------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.18(20.06.18.18)
- Verified no OSK is popped up when a new tab is opened via tab tray or new tab button 
- Verified no settings for Auto open keyboard 
--------
Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.06.18.18)
- Verified no OSK is popped up when a new tab is opened via tab tray or new tab button 
- Verified no settings for Auto open keyboard 
--------
