### ISSUE TITLE
Incorrect image rotation on upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2079]
### Description: 
Incorrect image rotation on upgrade

### Steps to Reproduce 
https://bravesoftware.slack.com/archives/C06UXF3KJ/p1575514218229200

**Actual result:** 
https://bravesoftware.slack.com/archives/C06UXF3KJ/p1575514233229300

**Expected result:**
Should be as per spec

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14.1(19.12.05.00)

**Device details:** 
iPhone XR

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
After several discussions via Slack, it was decided that the current iOS implementation would remain the same for the first iteration and changed in the second iteration.

@srirambv @jhreis I'm on PTO for most of the day tomorrow. If the above is still true tomorrow, we can probably close this off.

**Comment by srirambv** [comment]
Based on the discussion I'd suggest moving this out of the milestone and keep it open rather than closing and creating a new one. Moving it to 1.15 for now and removing release blocking label

**Comment by jhreis** [comment]
This should be fixed up after the latest NTP refactor / release after E3.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.18.17)
- Verified image rotation is 2nd on a clean install and every 4th image after that
-------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified image rotation is 2nd on a clean install and every 4th image after that
-------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.18.17)
- Verified image rotation is 2nd on a clean install and every 4th image after that
-------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified image rotation is 2nd on a clean install and every 4th image after that
-------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.18.17)
- Verified image rotation is 2nd on a clean install and every 4th image after that
-------
