### ISSUE TITLE
Display Incorrectly on Brave Rewards (%@)

### ISSUE THREAD

**Issue by genepg** [brave/brave-ios#2080]
### Description: 
Brave Rewards display `%@`.
It there any things went wrong? or might be Chinese problem?

*Actual result:* 
![31DA83A0-51B3-48A4-BAAC-54F6C828DD39](https://user-images.githubusercontent.com/20477170/70199233-2392d480-174c-11ea-985e-a3dab6e4f727.png)

*Brave Version:* 
Provide full details: v1.14

*Device details:* 
Model type and iOS version: iPhone 6s+ (iOS 13.2.3)

**Comment by kylehickinson** [comment]
@GenePg Yeah, looks like one of our localizations got messed up here, thanks for reporting :)

**Comment by kylehickinson** [comment]
@anthonypkeane Can you check Transifex to see if this was incorrectly translated in the Chinese language? It looks like a space was added between `%` and `@` and would need to be fixed there.

**Comment by anthonypkeane** [comment]
Translators replaced the % with the unicode % character and I've fixed it not for zh & zh_TW

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.3.1 running 1.15(20.0.13.17)
- Verified no `% @` is shown on both Chinese(Simplified) and Chinese (Traditional)
![image](https://user-images.githubusercontent.com/17010094/72458422-8e491e00-3796-11ea-8458-459030e7c686.png)

-----
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.0.13.17)
- Verified no `% @` is shown on both Chinese(Simplified) and Chinese (Traditional)
![image](https://user-images.githubusercontent.com/17010094/72458926-9190d980-3797-11ea-8c0c-e0adf74ca990.png)

-----
Verification passed on iPhone 6 with iOS 12.4.4 running 1.15(20.0.13.17)
- Verified no `% @` is shown on both Chinese(Simplified) and Chinese (Traditional)
![image](https://user-images.githubusercontent.com/17010094/72458930-95bcf700-3797-11ea-9eff-2e152a0d1483.png)

-----
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.0.13.17)
- Verified no `% @` is shown on both Chinese(Simplified) and Chinese (Traditional)
![image](https://user-images.githubusercontent.com/17010094/72458951-9fdef580-3797-11ea-82c2-1f4268ea3878.png)

-----
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.0.13.17)
- Verified no `% @` is shown on both Chinese(Simplified) and Chinese (Traditional)
![image](https://user-images.githubusercontent.com/17010094/72458944-9b1a4180-3797-11ea-963d-8eaa22bfb5ff.png)
