### ISSUE TITLE
Time out details on passcode lockdown copy should have a line break (Follow up of #443)

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2081]
### Description: 

Follow up #443 

Should have a line break between try again and attempts as per:

> Too many failed attempts
> Try again in $TIME minutes

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.18.17)
- Verified lockdown message has proper line break as per new design
![image](https://user-images.githubusercontent.com/17010094/74905091-4f306d00-53d3-11ea-85d7-17ad1090de2f.png)
------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified lockdown message has proper line break as per new design
![image](https://user-images.githubusercontent.com/17010094/74905152-7850fd80-53d3-11ea-99d0-9cf9f240f792.png)
------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.18.17)
- Verified lockdown message has proper line break as per new design
![image](https://user-images.githubusercontent.com/17010094/74905171-830b9280-53d3-11ea-8979-2dbbeb8ac5f0.png)

------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified lockdown message has proper line break as per new design
![image](https://user-images.githubusercontent.com/17010094/74905124-6707f100-53d3-11ea-9506-acf2e77e55c3.png)
![image](https://user-images.githubusercontent.com/17010094/74905132-6a9b7800-53d3-11ea-8f84-8f38d2fea43d.png)
------
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.18.17)
- Verified lockdown message has proper line break as per new design
![image](https://user-images.githubusercontent.com/17010094/74905214-9dde0700-53d3-11ea-9ac9-0bf6752384c9.png)
-------

Need to reverify Japanese Translation once #2341 is merged

**Comment by srirambv** [comment]
Verification passed for Japanese Locale 
![image](https://user-images.githubusercontent.com/17010094/75006650-7735d400-5498-11ea-898b-c9aa4177b067.png)
