### ISSUE TITLE
Incorrect setting toggle for NTP images

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2083]
### Description: 
Incorrect setting toggle for NTP images

### Steps to Reproduce 
https://bravesoftware.slack.com/archives/C06UXF3KJ/p1575551486274100

**Actual result:** 
https://bravesoftware.slack.com/archives/C06UXF3KJ/p1575551502274300?thread_ts=1575551486.274100&cid=C06UXF3KJ

**Expected result:**
https://bravesoftware.slack.com/archives/C06UXF3KJ/p1575551512275100?thread_ts=1575551486.274100&cid=C06UXF3KJ

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14.1(19.12.05.00)

**Device details:** 
All 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by mandar-brave** [comment]
@jhreis @anthonypkeane this is a requirement for NTP. Spec reference here
New section under Brave Settings>(Display)New Tab Page with a new page containing settings: “Show Background Images” default ON, and an exposed setting for “Show Sponsored Images” also ON, when enabled.

**Comment by anthonypkeane** [comment]
iOS has that 

If the below is not per spec can you pls point out what is missing.

**Comment by btlechowski** [comment]
Verification passed on 1.14.3(20.01.28.18) on Production on iPhone SE (iOS 12.4)
- Verified that Disabling the Background images in Settings also disables Sponsored Images
- Verified that Enabling the Background images in Settings also enables Sponsored Images
- Verified that Sponsored images can't be enabled when Background images are disabled

Verification passed on `1.14.3 (20.01.28.18)` on Production on `iPhone 11 (iOS 13.3)`
- Verified that Disabling the Background images in Settings also disables Sponsored Images
- Verified that Enabling the Background images in Settings also enables Sponsored Images
- Verified that Sponsored images can't be enabled when Background images are disabled
- Verified that Sponsored images can be disabled when Background images are enabled

Verification passed on 1.14.3(20.01.28.18) on Production on iPad 5th Gen (iOS 12)
- Verified that Disabling the Background images in Settings also disables Sponsored Images
- Verified that Enabling the Background images in Settings also enables Sponsored Images
- Verified that Sponsored images can't be enabled when Background images are disabled

Verification passed on 1.14.3(20.01.28.18) on Production on iPad Mini (iOS 13)
- Verified that Disabling the Background images in Settings also disables Sponsored Images
- Verified that Enabling the Background images in Settings also enables Sponsored Images
- Verified that Sponsored images can't be enabled when Background images are disabled
