### ISSUE TITLE
Disabling new tab background images

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#2089]
When disabling new tab background images we should fallback to using the theme text coloring for current theme, hide the gradient, and show all available favorites (vs short list)
![70237862-0fdc7380-1736-11ea-8abf-0432baab9dd9](https://user-images.githubusercontent.com/318119/70261408-fea45e80-1757-11ea-9267-6dcb5c0800a4.png)

**Comment by iccub** [comment]
Not applicable anymore, we are refactoring this screen
