### ISSUE TITLE
Add line break on incorrect passcode lockdown timer

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2090]
### Description: 
Follow up to https://github.com/brave/brave-ios/issues/443#issuecomment-553144519

The copy is 
Too many failed attempts
Try again in $TIME minutes

There is a break after _attempts_ which wasn't completed. 

Please add a break after attempts on iPad and iOS

**Comment by kylehickinson** [comment]
Duplicate of #2081 

Sorry didn't mention that I already opened it after commenting on previous ticket 😅
