### ISSUE TITLE
Flip the tab bar coloring for active/inactive

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#2091]
Flip color setting for active and inactive tabs in tabbar. All themes, affected.

**Comment by srirambv** [comment]
- Verification passed on iPhone XR with iOS 13.5 running 1.19(20.07.15.13)

Light Theme | Dark Theme
-- | --
<img width=500 src=https://user-images.githubusercontent.com/17010094/87685859-c3512000-c77b-11ea-8c85-5b4a2bd12e08.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/87685883-c9470100-c77b-11ea-9aa7-f63c6680e671.png>

------------------------ 
Verification passed on iPhone 7+ with iOS 13.5.1 running 1.19(20.07.15.13)

Light Theme | Dark Theme
-- | --
<img width=500 src=https://user-images.githubusercontent.com/17010094/87687044-2beccc80-c77d-11ea-8433-27e09e1b3643.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/87687055-2e4f2680-c77d-11ea-8258-e94ac453ed2c.png>

-----------------
- Verification passed on iPhone 6 with iOS 12.4.7 running 1.19(20.07.15.13)

Light Theme | Dark Theme
-- | --
<img width=500 src=https://user-images.githubusercontent.com/17010094/87686943-0c55a400-c77d-11ea-92bf-4b9471cc6ab3.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/87686933-08c21d00-c77d-11ea-980a-f6822fb537ab.png>

-------------------
- Verification passed on iPad Pro with iOS 13.6 running 1.19(20.07.15.13)

Light Theme | Dark Theme
-- | --
<img width=500 src=https://user-images.githubusercontent.com/17010094/87686982-1677a280-c77d-11ea-927c-65a9b2f3736e.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/87686962-12e41b80-c77d-11ea-8f02-c07551bd6b55.png>

-----------------
- Verification passed on iPad Pro with iOS 12.4.1 running 1.19(20.07.15.13)

Light Theme | Dark Theme
-- | --
<img width=500 src=https://user-images.githubusercontent.com/17010094/87687003-1ecfdd80-c77d-11ea-8b58-242d7811d6e1.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/87686992-1b3c5680-c77d-11ea-8d28-89dd02f71d68.png>
