### ISSUE TITLE
Update design on Brave Rewards wallet balance error message

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-ios#2093]
## Description 
Currently, the Brave Rewards panel (desktop, iOS, Android) shows an error message if:
1. You don’t have an internet connection
2. The balance or wallet details requests failed for some reason from rewards service

It looks like:
![Image from iOS](https://user-images.githubusercontent.com/2388823/70361821-c5432000-1837-11ea-9790-a5a91a54f656.png)

Soften up that error message treatment by:

- Replacing the 'X' icon which may be confused for a close button with an info icon
- Removing the alarming red/pink color palette; this could be a temporary issue so treat this message as informational instead of as a warning
- Using more human language and avoid technical terms like "server", "not responding", etc. That doesn't mean anything to the average user.

## Design
The error message now says:

> **Uh oh!** There was an issue getting your wallet balance. Check your internet connection and try again later.

![wallet details error](https://user-images.githubusercontent.com/2388823/70361867-ed328380-1837-11ea-938d-0a965e6e754d.png)

Apply this message treatment and colors across platforms.

## Assets
[icon-info.svg.zip](https://github.com/brave/brave-browser/files/3934320/icon-info.svg.zip)

**Comment by karenkliu** [comment]
FYI, duplicate cross-platform issues for parity:
Android https://github.com/brave/browser-android-tabs/issues/2354
Desktop https://github.com/brave/brave-browser/issues/7260

**Comment by kylehickinson** [comment]
Closed as this feature is no longer supported in new Rewards on Brave iOS
