### ISSUE TITLE
Nordstrom site broken in iOS - webcompat

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-ios#2096]
### Description: 
The Nordstrom website is breaking in Brave, specifically on iOS

Version 1.13 (19.11.06.18)

Tested on iPhone 6s and iPad Pro. 

Unable to repro on Android.

Have not tested on desktop.

### Steps to Reproduce 
  1. Go to shop.nordstrom.com
  2. Site redirects on initial load, rendering a blank white page.
  3. Dropping shields does not appear to resolve the issue.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?y
- did you check in Safari/Firefox (WkWebView-based browsers)? Y

**Comment by lukemulks** [comment]
cc: @ryanbr @anthonypkeane @jhreis (unable to assign people or labels to issues in this repo, so tagging here and incl. webcompat in issue title).

With holiday season, and hhi people gravitating toward iOS, would likely be wise to prio the fix for this. Android loads fine. Maybe something w/httpsE, as I observe a flash of the site loading before the redirect, or could be something list-related. Observing 6 items blocked, but am afk, and unable to capture a log of sesh traffic.

**Comment by ryanbr** [comment]
~~This maybe a UA check, Just checked Firefox on IOS, and I got the same blank page.~~

**Comment by ryanbr** [comment]
https://github.com/webcompat/web-bugs/issues/42236

https://github.com/mozilla-mobile/firefox-ios/issues/5610

**Comment by srirambv** [comment]
- Verification passed on iPhone XR with iOS 13.3.1 running 1.15(20.01.13.17)
  - Verified page loads correctly and redirects to m.shop.nordstrom.com
-----
- Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.01.13.17)
  - Verified page loads correctly and redirects to m.shop.nordstrom.com
-----
- Verification passed on iPhone 6 with iOS 12.4.4 running 1.15(20.01.13.17)
  - Verified page loads correctly and redirects to m.shop.nordstrom.com
-----
- Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.01.13.17)
  - Verified page loads correctly and redirects to m.shop.nordstrom.com
-----
- Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.01.13.17)
  - Verified page loads correctly and redirects to m.shop.nordstrom.com

**Comment by srirambv** [comment]
- Verification passed on iPhone XR with iOS 13.3.1 running 1.14.3(20.01.23.16)
  - Verified page loads correctly and redirects to m.shop.nordstrom.com
-----
- Verification passed on iPhone 7+ with iOS 13.3.1 running 1.14.3(20.01.23.16)
  - Verified page loads correctly and redirects to m.shop.nordstrom.com
-----
- Verification passed on iPhone 6 with iOS 12.4.4 running 1.14.3(20.01.23.16)
  - Verified page loads correctly and redirects to m.shop.nordstrom.com
-----
- Verification passed on iPad Pro with iOS 13.3.1 running 1.14.3(20.01.23.16)
  - Verified page loads correctly and redirects to m.shop.nordstrom.com
-----
- Verification passed on iPad Pro with iOS 12.4.4 running 1.14.3(20.01.23.16)
  - Verified page loads correctly and redirects to m.shop.nordstrom.com
