### ISSUE TITLE
Favourites icon mismatch when they are reordered

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2099]
### Description: 
Favourites icon mismatch when they are reordered

### Steps to Reproduce 
  1. Add a website as a favourite, sometimes it may not get the icon
  2. Edit and reorder it to a different position
  3. Takes the icon of the tile where it is moved to

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/70459690-b308f200-1a82-11ea-8ee2-79b2849fc85f.png)
![image](https://user-images.githubusercontent.com/17010094/70459675-ad131100-1a82-11ea-8545-36278ade2bab.png)

**Expected result:**
Should show proper icon for each favourite

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy if you run into step 1 

**Brave Version:** 
1.14.1

**Device details:** 
iPad (iOS 13.2) may also happen on iPhones

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Brandon-T** [comment]
Was testing this for quite some time. Having a really extremely hard time reproducing it :S
Any advice?

**Comment by srirambv** [comment]
@Brandon-T does the favourite get an icon when you add it? I think that's the crucial step there not sure how it sometimes doesn't get the icon. One possible option is to add an invalid page

**Comment by Brandon-T** [comment]
Hmm yeah I always get an icon no matter what I do.

**Comment by srirambv** [comment]
@Brandon-T  try adding the site as favourite before the page load completes. That way you will end up with a site tile without icon. I can easily reproduce it and add it this way.

**Comment by szymont** [comment]
I'm experiencing the same issue on version 1.15. Device has iOS 13.4

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.18(20.06.18.18)
- Verified favicons match the site 
- Verified editing a favourite doesn't change/retain the original site favicon
- Verified reordering favourites doesn't cause favicons to be mixed
---------
Verification passed on iPhone 7+ with iOS 13.5.1 running 1.18(20.06.18.18)
- Verified favicons match the site 
- Verified editing a favourite doesn't change/retain the original site favicon
- Verified reordering favourites doesn't cause favicons to be mixed
---------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.18(20.06.18.18)
- Verified favicons match the site 
- Verified editing a favourite doesn't change/retain the original site favicon
- Verified reordering favourites doesn't cause favicons to be mixed
---------
Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.06.18.18)
- Verified favicons match the site 
- Verified editing a favourite doesn't change/retain the original site favicon
- Verified reordering favourites doesn't cause favicons to be mixed
---------
