### ISSUE TITLE
BR copy update for non ads regions

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2100]
### Description: 
Copy may need to be updated for this screen in non ads regions. 

Chat: https://bravesoftware.slack.com/archives/CKA10H3AS/p1575485344069300

**Comment by alexwykoff** [comment]
<img width="403" alt="Screen Shot 2019-12-09 at 12 30 36 PM" src="https://user-images.githubusercontent.com/1434040/70462569-d16dee00-1a80-11ea-8199-a1a53dd8b7c8.png">

The simplest solution would be to remove the paragraph.

**Comment by kylehickinson** [comment]
@alexwykoff @anthonypkeane Are we decided on this:

> The simplest solution would be to remove the paragraph.

**Comment by anthonypkeane** [comment]
Please remove 

> Watch your balance grow as you view privacy preserving ads through Brave

for non ad supported regions

**Comment by kylehickinson** [comment]
This screen will be removed via #2169 so no longer needed
