### ISSUE TITLE
Tab Tray UI Parity

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#211]
Not total parity (i.e. no blurred background, keeping the animation, etc.), but bring the tab tray to match a slightly altered 1.6 tab tray:

- [ ] Update toolbar to be the same color as the background
- [ ] Replace trash tabs with done, and re-arrange toolbar items
- [ ] Update the tab tray background (and toolbar) based on private mode
- [ ] Update private mode icon (shades)

### Screenshots

| Normal | Private (No-Tabs) | Private |
| -- | -- | -- |
| ![normal](https://user-images.githubusercontent.com/529104/44915604-63753b80-ad01-11e8-9779-3eabdb51739a.png) | ![private-notabs](https://user-images.githubusercontent.com/529104/44915618-6a9c4980-ad01-11e8-82e1-a3ee2bc913fe.png) | ![private](https://user-images.githubusercontent.com/529104/44915624-6ec86700-ad01-11e8-89e4-309f9bc43fdd.png) |

**Comment by kylehickinson** [comment]
Needs design approval

**Comment by jhreis** [comment]
Per our meeting today, product team has signed off, just waiting on final confirmation from @tomlowenthal.

@tomlowenthal: lmk if you need anything in your research.

**Comment by tildelowengrimm** [comment]
Yep, this meets the same goal as the current implementation — telling a person what private browsing does (and doesn't) do before they use it. 👍🏻

**Comment by tmancey** [comment]
Great, unblocked and ready for development

**Comment by kylehickinson** [comment]
Rebased since this branch was falling behind a bit
