### ISSUE TITLE
can't open links in Brave from third party applications using "Share via.."

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2112]
### Description: 

Attempting to open links with Brave from third party applications using `Share with..` has regressed on iOS 12. Looks like the regression started on `1.14.2 (19.12.5.19)` which introduced NFC. From my understanding, NFC is only iOS 13 which might have caused issues with iOS 12.

### Steps to Reproduce 

  1. install & launch `1.14.2 (19.12.11.21)`
  2. open Twitter come and find a random link on the timeline
  3. long tap on the link and select `Share via..`
  4. select Brave from the list and you'll notice nothing happens

**Actual result:** 

Trying to share links with Brave from third parties using `Share via..` has regressed and stopped working.

**Expected result:**

Sharing links with Brave from third party applications via `Share via..` should work like it did in `1.14.1 (19.12.05.18)`. 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

 * `1.14.2 (19.12.11.21)` - **Reproduced**
 * `1.14.2 (19.12.9.17)` - **Reproduced**
 * `1.14.2 (19.12.5.19)` - **Reproduced**
 * `1.14.2 (19.12.4.2)` - **Couldn't reproduce**
 * `1.14.1 (19.12.05.18)` - **Couldn't reproduce** (current released version)

**Device details:** 

* `iPhone 6s+` running `iOS 12.4.1` - **Reproduced**
* `iPad Mini 4` running `iOS 12.4.1` - **Reproduced**
* `iPhone 6` running `iOS 13.3` - **Couldn't reproduce**
* `iPad Air (3rd Gen)` running `iOS 13.3` - **Couldn't reproduce**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @jhreis @brave/legacy_qa @anthonypkeane @iccub

**Comment by iccub** [comment]
Does it happen with twitter app only?
I can't repro when sharing a link via Safari on iOS 12

**Comment by srirambv** [comment]
@iccub I can reproduce it on Safari as well. Even with only dev installed, doesn't launch Brave when selecting it from share menu

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.14.2 (19.12.12.15)`

* ensured that you can share websites with Brave using the following applications:
  * `Twitter`, `Firefox`, `Chrome`, `Safari`, `Gmail`
* ensured that I can share links within Brave into the following applications:
  * `Twitter`, `Gmail`, `Notes`, `SMS`, `iMessage`, `Pocket`

Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.14.2 (19.12.12.15)`

* ensured that you can share websites with Brave using the following applications:
  * `Twitter`, `Firefox`, `Chrome`, `Safari`, `Gmail`
* ensured that I can share links within Brave into the following applications:
  * `Twitter`, `Gmail`, `Notes`, `SMS`, `iMessage`, `Pocket`
