### ISSUE TITLE
NFC scan message always shows success icon even when it fails 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2114]
### Description: 
NFC scan message always shows the success icon even when it fails 

### Steps to Reproduce 
  1. Install 1.14.2(19.12.11.21)
  2. Register on mdp.github.io/u2fdemo
  3. Scan device prompt shows up
  4. Tap Yubikey, fails to register but still shows success message

**Actual result:** 
![RPReplay_Final1576158720](https://user-images.githubusercontent.com/17010094/70718262-e4213680-1cbd-11ea-90be-407ead32f80f.gif)

**Expected result:**
Should show correct message 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14.2(19.12.11.21)

**Device details:** 
iPhone 7+ (iOS 13.2). 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
cc: @tomlowenthal @anthonypkeane  to move it out if this is not a high priority

**Comment by Brandon-T** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1530031/70726436-1174e100-1ccc-11ea-9eeb-fe5ea5c21f17.gif)

**Comment by iccub** [comment]
per @jhreis 
This UI is also just Apple confirming that the scan itself was successful, does not mean website is happy with data.
