### ISSUE TITLE
High Level Legacy U2F registration fails on iOS 13.2

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2115]
### Description: 
High Level Legacy U2F registration fails on iOS 13.2

### Steps to Reproduce 
  1. Install 1.14.2 on iOS 13.2 device
  2. Visit mdp.github.io/u2fdemo
  3. Register and scan the device 
  4. Fails to register the yubikey
  5. Register and plugin Yubikey to the phone, registration completes

**Actual result:** 
![RPReplay_Final1576158720](https://user-images.githubusercontent.com/17010094/70718676-a4a71a00-1cbe-11ea-87b9-06a72b35f850.gif)

**Expected result:**
![FilefromiOS](https://user-images.githubusercontent.com/17010094/70718693-a8d33780-1cbe-11ea-9650-e1f5e1a27dfd.gif)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14.2(19.12.11.21)

**Device details:** 
iPhone 7+ (iOS 13.2) - See actual result gif
iPhone XR (iOS 13.3) - See expected result gif

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
@srirambv looks like it's working on my `iPhone 11` running `iOS 13.3` with `YubiKey 4 (NFC)` running `4.3.7`. Basically ran through the STR mentioned in https://github.com/brave/brave-ios/issues/2115#issue-536999688 and it worked on the first attempt.

Let me know if there's anything else that I should try 👍 

#### Video Example:

* https://youtu.be/vBeDXkePDK8

#### Image Example:

![IMG_0001](https://user-images.githubusercontent.com/2602313/72133667-04412580-3350-11ea-9192-d484667f2bf4.PNG)

**Comment by srirambv** [comment]
I was able to register as well with a new YubiKey. Seems to be an issue with the old keys that I have

**Comment by srirambv** [comment]
@kjozwiak  thanks for the double check. @jumde  going to close as not actionable. Will reopen if I start to see this happen again.
