### ISSUE TITLE
All Shields Toggle doesn't work

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#2121]
### Description: 
When toggling all shields, it doesn't disable properly.

### Steps to Reproduce 
  1. Enable "Block Scripts" from the shields menu in the URL bar
  2. Toggle the "All Shields" option to OFF
  3. Notice that the pages still don't load because it didn't take effect.

**Actual result:** 
Shields are still on

**Expected result:**
Shields to be off

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
Any

**Device details:** 
Any

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified steps from #2062 
- Verified the following steps 
```
- Enabled block scripts from settings
- Visited jsfiddle.net, page load fails due to block script
- Disable shields, page reloads and loads the site properly
- Enable shields and disable block script for site, page reloads correctly 
- Disable shields and re-enable, shields settings are retained
```
-------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.18.17)
- Verified steps from #2062 
- Verified the following steps 
```
- Enabled block scripts from settings
- Visited jsfiddle.net, page load fails due to block script
- Disable shields, page reloads and loads the site properly
- Enable shields and disable block script for site, page reloads correctly 
- Disable shields and re-enable, shields settings are retained
```
-------
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.18.17)
- Verified steps from #2062 
- Verified the following steps 
```
- Enabled block scripts from settings
- Visited jsfiddle.net, page load fails due to block script
- Disable shields, page reloads and loads the site properly
- Enable shields and disable block script for site, page reloads correctly 
- Disable shields and re-enable, shields settings are retained
```
-------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified steps from #2062 
- Verified the following steps 
```
- Enabled block scripts from settings
- Visited jsfiddle.net, page load fails due to block script
- Disable shields, page reloads and loads the site properly
- Enable shields and disable block script for site, page reloads correctly 
- Disable shields and re-enable, shields settings are retained
```
-------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.18.17)
- Verified steps from #2062 
- Verified the following steps 
```
- Enabled block scripts from settings
- Visited jsfiddle.net, page load fails due to block script
- Disable shields, page reloads and loads the site properly
- Enable shields and disable block script for site, page reloads correctly 
- Disable shields and re-enable, shields settings are retained
```
-------
