### ISSUE TITLE
Allow ‘Reopen Last Closed Tab’ shortcut (iPadOS)

### ISSUE THREAD

**Issue by andrewcking** [brave/brave-ios#2123]
## Problem Description 
Safari allows one to reopen their most recently closed tab on iPad with the cmd-shift-T shortcut (you can hold command down in safari or brave to see the shortcuts they currently support)..

## Feature Overview 

It would be super useful if Brave could add this shortcut option to match the desktop version of Brave and to mirror the functionality available in iPadOS safari. 

## User Experience 

   1. Close tab A
   2. Hit cmd-shift-T
   3. Tab A reopens (this can even be done multiple times to pull up tabs that we closed before A

**Comment by SwiftWinds** [comment]
Would be awesome if this were brought to standard iOS too. Maybe force touch on the tabs button to popup a "recently closed tabs” window.

**Comment by jonathansampson** [comment]
As was [recently pointed out on Twitter](https://twitter.com/zooko/status/1245853214601121800), it is not currently possible to easily recover a closed-tab in Brave on iOS. Good feature to add.

![image](https://user-images.githubusercontent.com/815158/78315392-77f36880-7522-11ea-8eaf-82c4868d8068.png)

**Comment by Poopooracoocoo** [comment]
On Safari you can tap and hold on the new tab button in the tab switcher to view the list of recently closed tabs.

**Comment by detj** [comment]
> On Safari you can tap and hold on the new tab button in the tab switcher to view the list of recently closed tabs.

It would be great to replicate Safari’s behavior as most iOS/iPadOS Safari users will expect it to work that way. Unless, I don’t know if Apple has got it patented or something. 😛

**Comment by soner-yuksel** [comment]
The Recently Closed Tabs is in PR https://github.com/brave/brave-ios/pull/6755.

This ticket is ready to work on.

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iPadOS 16.2` using version `1.48 (23.2.13.20)`

- Confirmed that using `cmd-shift-T` keyboard shortcut will reopen last closed tab
- Confirmed that user is able to repeat this command to reopen multiple tabs
- Confirmed that reopen tabs using this command will remove them from the Recently Closed Tabs list

https://user-images.githubusercontent.com/17885425/218885872-4d63f702-bf61-4b1f-9de9-36dfcd9eb788.MP4
