### ISSUE TITLE
Tab bar rendering glitch (iPadOS)

### ISSUE THREAD

**Issue by andrewcking** [brave/brave-ios#2124]
### Description: 

Occasionally there is a rendering glitch affecting the tab bar on iPadOS.

### Steps to Reproduce 
I have had this happen in other ways I am pretty sure but at the moment I seem to be able to reproduce it at least this way:
1. Open a tab and navigate anywhere
2. Open a second tab and leave the new tab page up
3. Switch back to the first tab
4. Swipe up to recent apps and switch to another app (any app)
5. Swipe up to recents and switch back to brave

**Actual result:** 
Rendering glitch, note the tab bar

![](https://i.imgur.com/AnxN74J.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
I seem to be able to reproduce this with the above steps every time.

**Brave Version:** 

Version 1.14.1 (19.12.05.18)

**Device details:** 
iPad Pro

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified steps from issue description and no rendering issue
---------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.18.17)
- Verified steps from issue description and no rendering issue
---------
