### ISSUE TITLE
"New Tab Page" under "Settings" is displaying the "Appearance" selection

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2128]
### Description: 

When changing the theme via `Appearance` under `Settings`, the `New Tab Page` menu will display the selection.

### Steps to Reproduce

  1. launch `1.14.2 (19.12.12.17)` or`1.14.1 (19.12.05.18)`
  2. visit the `Settings` page and select an option from `Appearances`
  3. go back into `Settings` and you'll notice `New Tab Page` is displaying that choice/selection

**Actual result:** 

![IMG_9979](https://user-images.githubusercontent.com/2602313/71034740-11b81680-20e8-11ea-80b4-f408d6365ec3.PNG)

![IMG_0036](https://user-images.githubusercontent.com/2602313/71034960-855a2380-20e8-11ea-9c05-7478b7180d9f.PNG)

**Expected result:**

Selecting anything under `Appearances` shouldn't update the ``New Tab Page` menu.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.14.1 (19.12.05.18)` - **Reproduced**
* `1.14.2 (19.12.12.17)` - **Reproduced**

**Device details:** 

* `iPad Air (3rd Gen)` running `iPadOS 13.3` - **Reproduced**
* `iPad Mini 4` running `iPadOS 12.4.1` - **Reproduced**
* `iPhone 6s` running `iOS 13.3` - **Reproduced**
* `iPhone 6s+` running `iOS 12.4.1` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)?  `N/A`

### Additional Information

CCing @jhreis @aekeus @brave/legacy_qa

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.3.1 running 1.15(20.01.13.17)
- Verified changing appearance doesn't show the selected setting for new tab
-------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.01.13.17)
- Verified changing appearance doesn't show the selected setting for new tab
-------
Verification passed on iPhone 6 with iOS 12.4.4 running 1.15(20.01.13.17)
- Verified changing appearance doesn't show the selected setting for new tab
-------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.01.13.17)
- Verified changing appearance doesn't show the selected setting for new tab
-------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.01.13.17)
- Verified changing appearance doesn't show the selected setting for new tab

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.3.1 running 1.14.3(20.01.23.16)
- Verified changing appearance doesn't show the selected setting for new tab
-------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.14.3(20.01.23.16)
- Verified changing appearance doesn't show the selected setting for new tab
-------
Verification passed on iPhone 6 with iOS 12.4.4 running 1.14.3(20.01.23.16)
- Verified changing appearance doesn't show the selected setting for new tab
-------
Verification passed on iPad Pro with iOS 13.3.1 running 1.14.3(20.01.23.16)
- Verified changing appearance doesn't show the selected setting for new tab
-------
Verification passed on iPad Pro with iOS 12.4.4 running 1.14.3(20.01.23.16)
- Verified changing appearance doesn't show the selected setting for new tab
