### ISSUE TITLE
Separate visual for security key PIN when using NFC key

### ISSUE THREAD

**Issue by tildelowengrimm** [brave/brave-ios#2129]
![330DBC1E-3C37-4D9E-B0B7-73053E807A1B](https://user-images.githubusercontent.com/639937/71042912-eb8f7800-20e1-11ea-92ad-927b9e2d1040.png)

Currently, we use an image which looks like a YubiKey 5Ci on the PIN entry screen. I would be better to have a more generic NFC key visual when using an NFC key rather than a lightning one.

**Comment by karenkliu** [comment]
How's this?

![nfc key mock](https://user-images.githubusercontent.com/2388823/73218239-6e0e4d00-410e-11ea-966c-7cd953db4306.png)


[assets.zip](https://github.com/brave/brave-ios/files/4119576/assets.zip)

**Comment by tildelowengrimm** [comment]
The icon on the security key looks very much like a WiFi or RSS icon rather than an NFC visual?

**Comment by karenkliu** [comment]
@tomlowenthal Please send an example NFC visual

**Comment by tildelowengrimm** [comment]
![nfc_cms7f5ef84210](https://user-images.githubusercontent.com/639937/73401791-b1002a00-42a0-11ea-9872-8f00666ceb38.jpg)

**Comment by karenkliu** [comment]
How's this?
![nfc key mock](https://user-images.githubusercontent.com/2388823/73414237-0ea56e00-42c3-11ea-8d0a-dd812f709acc.png)

**Comment by karenkliu** [comment]
bump @tomlowenthal

**Comment by tildelowengrimm** [comment]
LG2M

**Comment by karenkliu** [comment]
here are [assets.zip](https://github.com/brave/brave-ios/files/4196120/assets.zip)

**Comment by karenkliu** [comment]
@jumde Hey is there any movement on this issue? It's just been hanging out on the design board - are we still doing this?

**Comment by karenkliu** [comment]
@anthonypkeane What's happening with this issue?

**Comment by jumde** [comment]
@karenkliu @anthonypkeane  - I can wrap this up post 1.23.1 release.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 14.4` using the following build:

```
1.24 (21.3.25.18)
```

**`5Ci Lighting`** | **`NFC`**
-------------------|--------------
![IMG_3617](https://user-images.githubusercontent.com/2602313/112555205-1b760280-8d9e-11eb-9462-fb5d1bf6981f.png) | ![IMG_3618](https://user-images.githubusercontent.com/2602313/112555221-2466d400-8d9e-11eb-971b-e16a8ac1694c.png)

-------

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using the following build:

```
1.24 (21.3.25.18)
```

![IMG_0158](https://user-images.githubusercontent.com/2602313/112555459-9b03d180-8d9e-11eb-9deb-54bc0193b025.png)

-------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.4` using the following build:

```
1.24 (21.3.25.18)
```

![IMG_0251](https://user-images.githubusercontent.com/2602313/112555886-6f351b80-8d9f-11eb-816e-385cbf17ba98.png)

----

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using the following build:

```
1.24 (21.3.25.18)
```

![IMG_0496](https://user-images.githubusercontent.com/2602313/112556005-b28f8a00-8d9f-11eb-934e-1c379f865bc8.png)
