### ISSUE TITLE
Can't seem to sign in to Medium.com on iOS

### ISSUE THREAD

**Issue by jenn-rhim** [brave/brave-ios#2130]
### Description: 
Medium sends an auth token (short life of 15 min) via email to allow you to sign in. Clicking the button in the email automatically direct you to their home page as a sign-in user. This works on desktop and Android because Brave can be set as a default browser.

On iOS as never being a default browser, to do this, you'd have to copy the auth link provided in the email below the button to try to sign in to Medium web. So far, I haven't had success: Medium sees it as an expired auth token.

Medium throws captcha upon providing email address to request an auth token email
Auth token never gets you through: Medium sees it as an expired auth token, even though a few seconds old, every time.

### Steps to Reproduce 
  1. Go to Medium.com, click sign in, and entered email
  2. Copy auth link in the email
  3. Enter the link into the address bar

**Actual result:** 
You get 'Your sign in link has expired' message. 

**Expected result:**
1. Successful sign in 
2. Perhaps no captcha (haven't seen this on desktop & android vs)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Every time

**Brave Version:** 
iOS
vs 1.14.1 (19.12.05.18)

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down? Yes
- did you check in Safari/Firefox (WkWebView-based browsers)?  Yes

**Comment by Brandon-T** [comment]
I am not able to reproduce this:

https://imgur.com/5X4d35F

I am copying the link from the email and I'm able to sign in. To copy the link, I long-press on it because just doing a quick copy is not enough since gmail actually truncates the link.
