### ISSUE TITLE
security alert in serialize-javascript

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-ios#2134]
see https://github.com/brave/brave-ios/network/alerts for details

**Comment by Brandon-T** [comment]
Hmm I still cannot see this repo or issue. @jhreis Are you able to see it?

**Comment by diracdeltas** [comment]
@Brandon-T i'm opening an autofix for this, will tag you for review when reay

**Comment by iccub** [comment]
Fixed it manually @diracdeltas here https://github.com/brave/brave-ios/pull/2320
and assigned you for review.

`uglifyjs-webpack-plugin` package is deprecated, had to replace it with `terser-webpack-plugin` which is included in webpack
