### ISSUE TITLE
Provide a global settings option similar to NTP dashboard settings on desktop

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2135]
### Description: 
Provide a global settings option similar to NTP dashboard settings on desktop

**Expected result:**
![image](https://user-images.githubusercontent.com/17010094/71172136-7c269f00-222d-11ea-8485-e88cb58af1a6.png)

**Brave Version:** 
Future Brave versions

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
cc @jamesmudgett

**Comment by iccub** [comment]
bunch of this stuff is implemented in few places in settings, you can disable shield stats now for example, closing as stale/invalid
