### ISSUE TITLE
Secure connection security indicator should not be shown for bad SSL requests

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#214]
### Steps to Reproduce 
  1. Navigate to "badssl.com"
  2. Select a link with a ![bad](https://user-images.githubusercontent.com/1188719/44984381-688df100-af74-11e8-830f-361988602372.png) icon, i.e. untrusted-root
  3. Tap "Advanced" button
  4. Tap "Visit site anyway" link

**Actual result:** Secure connection security indicator is shown

**Expected result:** Insecure connection security indicator should be shown

**Reproduces how often:** Every time

**Brave Version:** Development build hash e9d99c36697bc59ff348d174f5dfc6532bd95b3c

**Device details:** iPad Pro 10.5" iOS 11.4.1

### Additional Information 

Fix should be validated at badssl.com by validating that the insecure connection security indicator is shown for all links that have a ![bad](https://user-images.githubusercontent.com/1188719/44984381-688df100-af74-11e8-830f-361988602372.png) icon

**Comment by jamesmudgett** [comment]
Requires displaying a red "broken lock" icon. 
![screen shot 2018-09-06 at 3 13 14 pm](https://user-images.githubusercontent.com/318119/45182599-6a131f80-b1e7-11e8-9cc2-22f1bea85b0a.png)

**Comment by jamesmudgett** [comment]
![screen shot 2018-09-06 at 3 29 36 pm](https://user-images.githubusercontent.com/318119/45183454-b9f2e600-b1e9-11e8-9c99-1ed2bc16d3c7.png)

**Comment by tmancey** [comment]
Assets:

![unlock 2x](https://user-images.githubusercontent.com/1188719/45208675-0f2f0600-b283-11e8-99d1-2b6d2add0dc2.png)
![unlock 3x](https://user-images.githubusercontent.com/1188719/45208676-0f2f0600-b283-11e8-81b3-d977bfb802e8.png)

**Comment by diracdeltas** [comment]
Discussed in security review; we would like this prioritized for next release.
