### ISSUE TITLE
Regular crashes making Brave unusable

### ISSUE THREAD

**Issue by kaicarver** [brave/brave-ios#2142]
### Description: 

Brave crashes within a few minutes. No action necessary, happens when just reading a page, no clicking or scrolling.

Restart: “Well, this is embarrassing, etc.” dialog box. 

Whether restart with or without restore, crashes again soon after restart.

### Steps to Reproduce 
  1. Use Brave as usual, on my new iPad Pro.
  2. It will crash within a few minutes.

**Actual result:** 

Brave crashes.

**Expected result:**

Normal use.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Within less than 5 minutes. Started happening a few days ago.

**Brave Version:** 

Version 1.14.2 (19.12.12.17)

**Device details:** 

iPad Pro A1980 iOS 13.3

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

Brave is sadly unusable for me now on iOS. It had been my default browser on all platforms for the last few weeks.

I’ve seen older reports of this issue from months ago, but this is the first time it happens to me.
Behavior feels the same as this May 2019 report:
https://community.brave.com/t/ios-brave-crashing-every-few-minutes/61871

Workaround: uninstalled and reinstalled the app. Problem seems to have gone away.

**Comment by iccub** [comment]
Hi, two questions to help us identifying the issue
1. Did you have sync enabled?
2. Did you have Brave Rewards enabled?

**Comment by kaicarver** [comment]
1. I did have Sync enabled. It might have been in a strange state, because I got a new iPad, with a restored backup from the old iPad for the new iPad, so I had two “This device” in my list of devices. Since then I deleted the old iPad syncs and initiated a new sync for the iPad.

2. I think I do have Brave Rewards enabled. My wallet is empty on the iPad, but it’s not empty on the desktop. I don’t fully understand rewards yet, but that’s ok, I’m already happy just to use Brave.

**Comment by iccub** [comment]
Thanks for the detailed response @kaicarver
We have seen some random crashes regarding to sync, and still not sure how does it happen

Could you check if the crashes still happen after you remove that device from sync?
And then try to reenable sync and see if it starts to crash again

edit: nevermind, I see that app reinstall helped

**Comment by iccub** [comment]
We have fixed bunch of crashes in 1.14.3 release.
The app should crash much less now, closing this ticket for now
