### ISSUE TITLE
Deleting bookmark with sync enabled happens on wrong thread.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2143]
### Steps to Reproduce 
  1. Use xcode with core data concurrency debugger enabled.
  2. Join two devices, each should have some bookmarks
  3. Delete a bookmark on your device

**Actual result:** 
Threading error is thrown.

**Expected result:**
Should have no error.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.20.19)
- Verified deleting bookmark works fine and updates all devices in sync chain
-------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.20.19)
- Verified deleting bookmark works fine and updates all devices in sync chain
-------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.20.19)
- Verified deleting bookmark works fine and updates all devices in sync chain
-------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.20.19)
- Verified deleting bookmark works fine and updates all devices in sync chain
-------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.20.19)
- Verified deleting bookmark works fine and updates all devices in sync chain
-------
