### ISSUE TITLE
Unable to claim ad grant in first attempt 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2146]
### Description: 
@iccub and @amirsaber  reported that clicking ad grant didn't claim the grant when the notification showed up. Either had to quit browser or close and reopen panel and then claim

### Steps to Reproduce 
  1. Wait for ads grant to show up
  2. Open rewards panel
  3. First tap on claim doesn't claim the grant

**Actual result:** 
NO grant claimed on first tap

**Expected result:**
Should be able to claim the grant in first attempt

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.4.2

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Possibly related to #1998

**Comment by jhreis** [comment]
This should have been fixed already, QA should still verify.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.17(20.5.21.17)
- Verified able to claim grant on the first attempt
-----
Verification passed on iPhone 7+ with iOS 13.4.5 running 1.17(20.5.21.17)
- Verified able to claim grant on the first attempt
-----
Verification passed on iPhone 6 with iOS 12.4.5 running 1.17(20.5.21.17)
- Verified able to claim grant on the first attempt
-----
Verification passed on iPad Pro with iOS 13.4.5 running 1.17(20.5.21.17)
- Verified able to claim grant on the first attempt
-----
