### ISSUE TITLE
Remove tipping panel social media icons until a later date

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2147]
Ref https://github.com/brave/brave-ios/issues/1712

### Description: 

The social media icons currently do nothing in the tipping panel, so they should be hidden until we add the ability to tap them

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.12.10)
- Verified no social media icons are shown on tipping panel
![image](https://user-images.githubusercontent.com/17010094/74630932-a939f400-5181-11ea-9b8c-24a235a3d659.png)

--------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified no social media icons are shown on tipping panel
![image](https://user-images.githubusercontent.com/17010094/74630944-ae973e80-5181-11ea-86c3-a3bfdd66f6c6.png)

--------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.12.10)
- Verified no social media icons are shown on tipping panel
![image](https://user-images.githubusercontent.com/17010094/74630944-ae973e80-5181-11ea-86c3-a3bfdd66f6c6.png)

--------
Verification passed on iPad Pro with iOS13.3.1 running 1.15(20.02.12.10)
- Verified no social media icons are shown on tipping panel
![image](https://user-images.githubusercontent.com/17010094/74630918-a3441300-5181-11ea-8c04-3717a3e2ebe1.png)

--------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.12.10)
- Verified no social media icons are shown on tipping panel
![image](https://user-images.githubusercontent.com/17010094/74630906-9fb08c00-5181-11ea-9d00-826215a09a5c.png)
