### ISSUE TITLE
Secure connection security indicator should not be shown for partially secure sites

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#215]
### Steps to Reproduce 
  1. Navigate to "badssl.com"
  2. Select a link with the ![dubious.svg](https://images.zenhubusercontent.com/5b6d3c6c9f47d341e6ea7783/20c59ef8-fb69-4fdb-98c1-661ad719b113) icon, i.e. mixed-form

**Actual result:** Secure connection security indicator is shown

**Expected result:** Partially secure connection security indicator should be shown

**Reproduces how often:** Every time

**Brave Version:** Development build hash e9d99c36697bc59ff348d174f5dfc6532bd95b3c

**Device details:** iPad Pro 10.5" iOS 11.4.1

### Additional Information 

Fix should be validated at badssl.com by validating that the partially secure connection security indicator is shown for all links that have a ![dubious.svg](https://images.zenhubusercontent.com/5b6d3c6c9f47d341e6ea7783/20c59ef8-fb69-4fdb-98c1-661ad719b113) icon

**Comment by jamesmudgett** [comment]
For cases where user is not navigating to https:// and visits http://site.com we need to drop the lock icon.

**Comment by tmancey** [comment]
@jamesmudgett should partially secure sites should show the broken red lock icon and http:// sites should drop the lock icon or that partially secure sites and http:// sites should drop the lock icon

**Comment by tmancey** [comment]
Needs investigation before development

**Comment by tildelowengrimm** [comment]
We should match the behavior of desktop Chrome, but with our existing iOS icons for now. That means that anything on badssl.com which has a grey-exclamation-mark-in-a-circle icon should have no security indicator on iOS for now — neither a good lock nor a broken red lock.

**Comment by tmancey** [comment]
👍

**Comment by diracdeltas** [comment]
Discussed in security review; we would like this prioritized for next release.

**Comment by tmancey** [comment]
PR submitted under #214
