### ISSUE TITLE
Verified wallet text flickers when panel is opened

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2153]
### Description: 
Verified wallet text flickers when panel is opened

### Steps to Reproduce 
  1. Install 1.15
  2. Enable rewards and connect wallet using Uphold (not KYC)
  3. Open panel, `Your wallet` text flickers once before the hyperlink gets active

**Actual result:** 
![uphold](https://user-images.githubusercontent.com/17010094/71917973-55ce9200-314f-11ea-937e-0a699eefb838.gif)

**Expected result:**
No flickering text when panel is opened

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.15

**Device details:** 
iPhone XR (iOS 13.3.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
This actually happens because we are pinging uphold's servers to determine the status of your account, but there might be a bug around it maybe doing so twice (since you see it go _back_ to "unconnected" state then back to the original). Either way I will investigate to see if we can avoid this

**Comment by GeetaSarvadnya** [comment]
The issue is reproduced for KYC'd wallet as well -  iPhone 8 - iOS 13.3
