### ISSUE TITLE
Clearing partial data destroys all tabs

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2155]
@srirambv commented on [Wed May 10 2017](https://github.com/brave/browser-ios/issues/873)

Description: Clearing partial data destroys all tabs

**Did you search for similar issues before submitting this one?**
Yes

**Expected behavior:**
Should show a warning about tabs being lost or should retain the tabs based on selected options

- Device (iPhone5, iPhone6s plus, iPad 3, ?):
All

- Brave Version:
1.3.3 & 1.3.2 existing issue

- Steps to reproduce:
    1. Open few tabs and visit different sites
    2. Open settings -> Clear browsing data -> Select Cache & Saved Logins -> Clear browsing data
    3. Tap on done, All opened tabs are lost

** Website problems only: N/A
- did you check with Brave Shields down? N/A
- did you check in Puffin/Dolphin/iCab/Maxthon (UIWebView-based browsers)? N/A

- Screenshot if needed:

- Any related issues:

---

@LaurenWags commented on [Wed Jun 13 2018](https://github.com/brave/browser-ios/issues/873#issuecomment-397026662)

Reproduced on iOS10 with iPad with version 1.6.2 (18.05.29.10) using STR from description. (note 'Clear browsing data' is now 'Clear Private Data').

**Comment by dvng88** [comment]
@srirambv : What should be expected alert message to notify users?  **"All current tabs will be closed"**

**Comment by srirambv** [comment]
@dvng88 Ideal behaviour should be no tabs lost. Just cache and saved logins in the above scenario. My personal preference would be as follows 
- Saved login -> `All saved credentials will be lost`, don't clear anything else except saved logins
- Browsing history -> `All browsing history will be cleared`, don't clear anything else except the history
- Cache/Cookie and Data -> `All tabs and current sessions will be lost`, for either of these two settings selected clear everything (tabs/cache/cookies/download data)and leave only saved logins intact
- Download -> `All download history will be lost`, don't clear anything else except download data

Based on the combination of switch selected we can adjust messaging. This would be a lot of rework but that would be the correct way. Just clear what is selected and don't touch anything else. 
cc: @brave/ios folks for their thoughts

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.16(20.05.05.12)
- Verified clearing partial data doesn't destroy any tabs
- Verified clearing partial data(Saved logins/passwords/browsing history) doesn't clear any cookies and session
- Verified clearing all data removes cookies and sessions 
- Verified no tabs are lost when trying to clear full or partial data
------------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.16(20.05.05.12)
- Verified clearing partial data doesn't destroy any tabs
- Verified clearing partial data(Saved logins/passwords/browsing history) doesn't clear any cookies and session
- Verified clearing all data removes cookies and sessions 
- Verified no tabs are lost when trying to clear full or partial data
------------
Verification passed on iPhone 6 with iOS 12.4.5running 1.16(20.05.05.12)
- Verified clearing partial data doesn't destroy any tabs
- Verified clearing partial data(Saved logins/passwords/browsing history) doesn't clear any cookies and session
- Verified clearing all data removes cookies and sessions 
- Verified no tabs are lost when trying to clear full or partial data
------------
Verification passed on iPad Pro with iOS 13.3.1 running 1.16(20.05.05.12)
- Verified clearing partial data doesn't destroy any tabs
- Verified clearing partial data(Saved logins/passwords/browsing history) doesn't clear any cookies and session
- Verified clearing all data removes cookies and sessions 
- Verified no tabs are lost when trying to clear full or partial data
------------
Verification passed on iPad Pro with iOS 12.4.5 running 1.16(20.05.05.12)
- Verified clearing partial data doesn't destroy any tabs
- Verified clearing partial data(Saved logins/passwords/browsing history) doesn't clear any cookies and session
- Verified clearing all data removes cookies and sessions 
- Verified no tabs are lost when trying to clear full or partial data
