### ISSUE TITLE
TrayToBrowserAnimator crash

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2156]
### Steps to Reproduce 
  1. Hard to reproduce, can see https://github.com/brave/brave-ios/issues/636 and check for regressions

**Actual result:** 

<img width="602" alt="Zrzut ekranu 2020-01-8 o 15 42 29" src="https://user-images.githubusercontent.com/6950387/71986879-81c04500-322d-11ea-9b22-54c3d4c71dd7.png">

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Closed here https://github.com/brave/brave-ios/pull/2157

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.15 (20.02.20.19)`

* ensured that tapping the `tab manager` in both normal/PB mode worked as expected
* ensured that closing all opened tabs via `tab manager` created a new tab and didn't cause crashes
* ensured that creating new tabs with a bluetooth keyboard worked as expected

Verification **PASSED** on `iPad Air 3rd Gen` running `iOS 13.3.1` using `1.15 (20.02.20.19)`
                      
* ensured that tapping the `tab manager` in both normal/PB mode worked as expected
* ensured that closing all opened tabs via `tab manager` created a new tab and didn't cause crashes
* ensured that creating new tabs with a bluetooth keyboard worked as expected

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.15 (20.02.20.19)`
                      
* ensured that tapping the `tab manager` in both normal/PB mode worked as expected
* ensured that closing all opened tabs via `tab manager` created a new tab and didn't cause crashes
* ensured that creating new tabs with a bluetooth keyboard worked as expected

Verification **PASSED** on `iPhone 11` running `iOS 12.4.1` using `1.15 (20.02.20.19)`
                      
* ensured that tapping the `tab manager` in both normal/PB mode worked as expected
* ensured that closing all opened tabs via `tab manager` created a new tab and didn't cause crashes
* ensured that creating new tabs with a bluetooth keyboard worked as expected
