### ISSUE TITLE
Wallet status isn't changed in settings page when KYC'd account is linked

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#2158]
### Description: 
Wallet status isn't changed in settings page when KYC'd account is linked
### Steps to Reproduce 
  1. Clean profile
  2. Enable rewards through the onboarding flow
  3. Click on `Verify wallet` and connect to an existing KYC'd uphold account 
  4. Click on BR panel and verify that wallet status changed to `Wallet Verified` in panel
  5. Navigate to the settings page
  6. Wallet status isn't changed to `Wallet Verified` in the settings page

**Actual result:** 
 Wallet status isn't changed to `Wallet Verified` in the settings page

Settings:

![image](https://user-images.githubusercontent.com/38657976/71993655-7ab12b00-325d-11ea-9531-13554736ba61.png)

BR Panel:

![image](https://user-images.githubusercontent.com/38657976/71993590-5bb29900-325d-11ea-9e3a-774dbf80f969.png)

**Expected result:**
 Wallet status should be changed to `Wallet Verified` in the settings page

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Always
**Brave Version:** 

1.15 (20.1.7.17)
**Device details:** 
iPhone 8 - iOS 13.3

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @brave/legacy_qa @kylehickinson

**Comment by kylehickinson** [comment]
Not sure if this will be done on iOS since our settings menu wallet isn't the same as regular panel (already diverges heavily from Desktop in this aspect).

cc @anthonypkeane

**Comment by anthonypkeane** [comment]
Internal chat: https://bravesoftware.slack.com/archives/CB0KCRCQN/p1578522216024300

**Comment by kylehickinson** [comment]
Closing, ticket replaced by #2169
