### ISSUE TITLE
5% ledger fee isn't deducted after sending a tip to verified pubs

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#2159]
### Description: 
5% ledger fee isn't deducted after sending a tip to verified pubs

### Steps to Reproduce 
  1. Clean profile 
  2. Enable rewards through the onboarding flow
  3. Click on Verify wallet and connect to an existing KYC'd uphold account
  4. Open a verified pubs https://brianbondy.com
  5. Send a one-time tip
  6. Click on Activity and check the transaction history in uphold
  7. `0.95 BAT` is listed in transaction history but `0.05 BAT` isn't listed

Note: If I follow the same steps in Desktop, I can see both fees listed in the transaction history

**Actual result:** 
5% ledger fee isn't deducted after sending a tip to verified pubs

**Expected result:**
5% ledger fee should be deducted and should be listed in the transaction history

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Always
**Brave Version:** 

1.15 (20.1.7.17)
**Device details:** 
iPhone 8 - iOS 13.3

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @brave/legacy_qa @kylehickinson

**Comment by kylehickinson** [comment]
@GeetaSarvadnya Can you please post a screenshot in this issue of how desktop shows the fees after a one-time tip

**Comment by GeetaSarvadnya** [comment]
@kylehickinson Please find the screenshot below (captured from desktop).

![image](https://user-images.githubusercontent.com/38657976/71995375-7c302280-3260-11ea-8721-6f6682d476bf.png)

**Comment by kylehickinson** [comment]
Oh this is in Uphold. That is odd, we don't control this process at all on the client. 

@NejcZdovc any ideas why this wouldn't happen for iOS? Possibly a fix applied later in brave-core?

**Comment by NejcZdovc** [comment]
@kylehickinson could be related to https://github.com/brave/brave-browser/issues/7425

**Comment by NejcZdovc** [comment]
also this is not ads, but rewards

**Comment by kylehickinson** [comment]
Ah, I see. @GeetaSarvadnya ☝️

@NejcZdovc Yeah we just have one label for both Rewards & Ads.

**Comment by LaurenWags** [comment]
@GeetaSarvadnya can you confirm if you were rapid tipping (as in https://github.com/brave/brave-browser/issues/7425) or if you only did one tip and the 5% never sent?

**Comment by kylehickinson** [comment]
Also the 5% fee is deducted after a (geometric) random amount of time, @GeetaSarvadnya did it appear at a later date?

**Comment by GeetaSarvadnya** [comment]
@LaurenWags  I have sent only few one-time tips. Y'day I have sent one time tips twice both times it didn't show 5% fee in transactions then I have tried in Desktop once, In desktop, I was able to see both (0.95 and 0.05) immediately. 

![image](https://user-images.githubusercontent.com/38657976/72085399-3f7d2d80-332b-11ea-81b2-7599d86d465b.png)

**Comment by GeetaSarvadnya** [comment]
@kylehickinson 5% fee never reflected for me for the tips which I have sent Y'day and today. Please find the above screenshot

**Comment by LaurenWags** [comment]
Thanks for clarifying @GeetaSarvadnya - sounds to me like iOS doesn't send the 5% at all. @srirambv have you experienced this?

**Comment by kylehickinson** [comment]
cc @NejcZdovc possibly an iOS specific issue in native libs, likely needs more investigation

**Comment by NejcZdovc** [comment]
@kylehickinson Yeah I would be surprised, the only think that I can think of is that timers are not working on iOS, so that they are never called. Do you properly handle `SetTransferFee` as maybe this is lost somewhere?

**Comment by kylehickinson** [comment]
Yep that would be it, we haven't implemented native lib transfer fee callbacks 🙈
