### ISSUE TITLE
window.open(), target=_blank crashes

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2162]
### Steps to Reproduce 
On a real device, enter Private Browsing Mode
Open https://www.w3schools.com/jsref/met_win_open.asp
Open settings, and enable block all cookies
Confirm blocking all cookies.
Disable block all cookies from settings.
Tap on the try it yourself button on the w3 website
It crashes when a new tab is opened from the old tab (popup).

**Actual result:** 

<img width="613" alt="Zrzut ekranu 2020-01-8 o 18 09 30" src="https://user-images.githubusercontent.com/6950387/71999608-0917b380-3242-11ea-8269-ecc25729353c.png">

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Related PR https://github.com/brave/brave-ios/pull/1237, it caused this regression

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.3.1 running 1.14.3(20.01.23.16)
- Verified test plan from issue no browser crash when opening the popup window
-----
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.14.3(20.01.23.16)
- Verified test plan from issue no browser crash when opening the popup window
-----
Verification passed on iPhone 6 with iOS 12.4.4 running 1.14.3(20.01.23.16)
- Verified test plan from issue no browser crash when opening the popup window
-----
Verification passed on iPad Pro with iOS 13.3.1 running 1.14.3(20.01.23.16)
- Verified test plan from issue no browser crash when opening the popup window
-----
Verification passed on iPad Pro with iOS 12.4.4 running 1.14.3(20.01.23.16)
- Verified test plan from issue no browser crash when opening the popup window
