### ISSUE TITLE
Custom publisher tipping banner images don't show up

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2164]
### Description: 
It seems like publisher header custom header images are not appearing on iOS

Please see here for context: https://bravesoftware.slack.com/archives/C0KHGGEUW/p1578463169010100

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.12.10)
- Verified tipping panel for a verified publisher shows the custom banner image
![image](https://user-images.githubusercontent.com/17010094/74638964-f377a100-5192-11ea-8343-820a61ea8d96.png)

------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified tipping panel for a verified publisher shows the custom banner image
![image](https://user-images.githubusercontent.com/17010094/74632757-1ea7c380-5186-11ea-91b4-534cc8de811a.png)

------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.12.10)
- Verified tipping panel for a verified publisher shows the custom banner image
![image](https://user-images.githubusercontent.com/17010094/74632798-354e1a80-5186-11ea-952e-8f769ac04bbb.png)

------
Verification passed on iPad Pro  with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified tipping panel for a verified publisher shows the custom banner image
![image](https://user-images.githubusercontent.com/17010094/74632757-1ea7c380-5186-11ea-91b4-534cc8de811a.png)

------
Verification passed on iPad Pro  with iOS 12.4.4 running 1.15(20.02.12.10)
- Verified tipping panel for a verified publisher shows the custom banner image
![image](https://user-images.githubusercontent.com/17010094/74632773-28312b80-5186-11ea-81b4-67ff6888dd44.png)

------
