### ISSUE TITLE
User agent is outdated

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2168]
### Steps to Reproduce 
  1. Open https://www.whatismybrowser.com/

**Actual result:** 
<img width="289" alt="Zrzut ekranu 2020-01-9 o 13 32 52" src="https://user-images.githubusercontent.com/6950387/72068112-927fc200-32e4-11ea-9c9c-9ce273339f0b.png">

**Expected result:**
Match firefox

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.3.1 running 1.14.3(20.01.26.16)
- Verified Brave UA matches with Firefox
- Brave
![image](https://user-images.githubusercontent.com/17010094/73012009-65063e80-3de3-11ea-8080-b26282f5c7b2.png)
![image](https://user-images.githubusercontent.com/17010094/73012016-6a638900-3de3-11ea-9092-221c1044e17b.png)
- Firefox
![image](https://user-images.githubusercontent.com/17010094/73012027-70f20080-3de3-11ea-98c7-3c1ed8a82bd2.png)
--------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.14.3(20.01.26.16)
- Verified Brave UA matches with Firefox
- Brave
![image](https://user-images.githubusercontent.com/17010094/73011708-c974ce00-3de2-11ea-92a4-37815a570a22.png)
![image](https://user-images.githubusercontent.com/17010094/73011696-c4b01a00-3de2-11ea-8f5d-d92cc2c0e826.png)
- Firefox
![image](https://user-images.githubusercontent.com/17010094/73011724-d1347280-3de2-11ea-955b-c54a71065078.png)

--------
Verification passed on iPhone 6 with iOS 12.4.4 running 1.14.3(20.01.26.16)
- Verified Brave UA matches with Firefox
- Brave
![image](https://user-images.githubusercontent.com/17010094/73012218-d7771e80-3de3-11ea-8573-1867cc1bbef4.png)
![image](https://user-images.githubusercontent.com/17010094/73012229-db0aa580-3de3-11ea-922b-70e1e8bbed28.png)
- Firefox
![image](https://user-images.githubusercontent.com/17010094/73012242-e067f000-3de3-11ea-8881-b5574cad3d7d.png)
--------
Verification passed on iPad Pro with iOS 13.3.1 running 1.14.3(20.01.26.16)
- Verified Brave UA matches with Firefox
- Brave
![image](https://user-images.githubusercontent.com/17010094/73011329-fffe1900-3de1-11ea-9539-b1ad316ea138.png)
![image](https://user-images.githubusercontent.com/17010094/73011406-28861300-3de2-11ea-9b22-022deb77c156.png)
- Firefox
![image](https://user-images.githubusercontent.com/17010094/73011538-6be08180-3de2-11ea-9c0b-3dc9ab4ddfa2.png)
--------
Verification passed on iPad Pro with iOS 12.4.4 running 1.14.3(20.01.26.16)
- Verified Brave UA matches with Firefox
- Brave
![image](https://user-images.githubusercontent.com/17010094/73011256-e230b400-3de1-11ea-99db-d2878af51a32.png)
![image](https://user-images.githubusercontent.com/17010094/73011175-bad9e700-3de1-11ea-8d86-e83feff5cfa7.png)
- Firefox
![image](https://user-images.githubusercontent.com/17010094/73011223-d3e29800-3de1-11ea-928c-867fd60c1e41.png)
--------
