### ISSUE TITLE
Remove Wallet Details from Settings

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2169]
### Description: 

As [per discussion](https://bravesoftware.slack.com/archives/CB0KCRCQN/p1578529773025700?thread_ts=1578522216.024300&cid=CB0KCRCQN) the wallet section as well as its details page from settings will be removed. 

For user wallets, the `Add Funds` & `Withdraw Funds` buttons will be moved into the user wallet details screen

Refs #2158

**Comment by anthonypkeane** [comment]
As per the slack chat, 

Remove the  blue wallet balance section

![IMG_60F2D979BB4C-1](https://user-images.githubusercontent.com/7606853/72102488-f782ea00-32db-11ea-8954-30f2a4368907.jpeg)

and in here, add the add fund and withdraw funds
![IMG_EC2A1902EEF3-1](https://user-images.githubusercontent.com/7606853/72102511-09648d00-32dc-11ea-81e0-dedb1db2436f.jpeg)

@jamesmudgett can you help with a design for this second part?

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.12.10)
![image](https://user-images.githubusercontent.com/17010094/74525756-e9159700-4f47-11ea-9a23-462454152ea2.png)
---------
Verification passed on iPhone 6 with iOS 12.4.4 running 1.15(20.02.12.10)
![image](https://user-images.githubusercontent.com/17010094/74526047-896bbb80-4f48-11ea-90c1-21ff554856fa.png)
---------
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.12.10)
![image](https://user-images.githubusercontent.com/17010094/74526077-9ab4c800-4f48-11ea-9a71-e139a6245e10.png)
---------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.12.10)
![image](https://user-images.githubusercontent.com/17010094/74526268-05660380-4f49-11ea-996d-a99f62b4befa.png)
---------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.12.10)
![image](https://user-images.githubusercontent.com/17010094/74526240-f67f5100-4f48-11ea-8a8f-240ee36ea7fb.png)
