### ISSUE TITLE
User agent for iPad in desktop mode is wrong.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2171]
### Steps to Reproduce 
  1. Open https://www.whatsmyua.info/ on iPad in desktop mode(on by default)
  2. See wrong UA
  3. Reload tab
  4. Different(fixed) UA is showing

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 
Happens on iOS 13.3, not sure about lower versions, could be Apple's bug.

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Fixed in https://github.com/brave/brave-ios/issues/2171

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified reloading the page doesn't change UA
- Verified switching to desktop/mobile retains the UA for that specific tab
--------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.12.10)
- Verified reloading the page doesn't change UA
- Verified switching to desktop/mobile retains the UA for that specific tab
--------
Verification passed on iPhone Pro with iOS 13.4 running 1.15(20.02.12.10)
- Verified reloading the page doesn't change UA
- Verified switching to desktop/mobile retains the UA for that specific tab
--------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified reloading the page doesn't change UA
- Verified switching to desktop/mobile retains the UA for that specific tab
--------
Verification passed on iPhone 6 with iOS 12.4.4 running 1.15(20.02.12.10)
- Verified reloading the page doesn't change UA
- Verified switching to desktop/mobile retains the UA for that specific tab
--------
