### ISSUE TITLE
Claim button not showing immediately after a user presses on the claim you ad grant notification

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2173]
### Description: 
@tomlowenthal saw and tapped the claim your grant system notification message. 

After tapping that notification, the BR panel opened (which is correct)
but the claim button was not visible for some time (perhaps 30 seconds) 
Tom waited (not opening or closing the panel,) and eventually the claim button appeared and he could claim his ad grant. 

We need the claim button to show up immediately in this case.

**Comment by kylehickinson** [comment]
> We need the claim button to show up immediately in this case.

This will be ultimately based on the users connection, as we need to ping server to get grants.

**Comment by anthonypkeane** [comment]
Tom was in the office on Wifi,  it took forever for the claim button to show. 

If we've to wait this long we'll need to UX a better solution. @jamesmudgett can you and I have a think?

**Comment by kylehickinson** [comment]
Based on you're explanation the first request failed somehow, and he got grants after 30s because there is a timer to grab grants after 30s regardless. I just wanted to state that we can't say it'll be "immediately" visible, as a user may have a slower connection

**Comment by tildelowengrimm** [comment]
Sounds like we need to ensure that the client has that info before the notification fires.

**Comment by kylehickinson** [comment]
Unfortunately we can't get that info prior, these are scheduled based on calendar/time. In the case where the user opens the app and gets the grant before it fires we remove the pending notification. Only other option would be enabling some backgrounding to fetch grants periodically. However this is controlled by the user + Apple, we don't know when our app will be given a chance to pull grant info and it's not guaranteed the app will stay alive long enough (depending on users connection) to fetch and schedule a notification

**Comment by tildelowengrimm** [comment]
That latter approach seems more reasonable — make sure that things are actually available before notifying someone. A notification about nothing feels like much worse UX than waiting a little longer before seeing the notification.

**Comment by kylehickinson** [comment]
I think the main issue is that for those use disable Background App Refresh entirely or anyone who uses Energy Saver mode frequently will never receive the notifications since Apple will not allow our app to do any backgrounding period.  The current method only schedules notifications based on you seeing an ad, so theoretically you should have a grant waiting for you when the notification goes out but I agree, it's not foolproof. @anthonypkeane maybe you can hop into this since you were a part of this decision

**Comment by tildelowengrimm** [comment]
I think it's reasonable that disabling background app refresh should prevent us from sending notifications about things that should happen in the background. That sounds like the feature working as intended.
