### ISSUE TITLE
publisher set custom tip amounts display out of order on banner

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#2177]
### Description: 
When you open the tip banner for a verified publisher with custom tip amounts set, the tip amounts don't display from least to greatest (i.e. 5 BAT, 10 BAT, 20 BAT). They display mixed up.

However, if the publisher doesn't have custom tip amounts set, then the tip amounts display in order from least to greatest.

### Steps to Reproduce 
Below sites referenced are on Prod, if you need staging examples msg @LaurenWags 
  1. Have Rewards enabled
  2. Visit a verified publisher without custom tip amounts set (ex. basicattentiontoken.org) and open tip banner
  3. See tip amounts in order 1 BAT, 5 BAT, 10 BAT.
  4. Visit a verified publisher with custom tip amounts set (ex. github.com/feross or rebron.org)

**Actual result:** 
Tip amounts displayed out of order:
![IMG_7E3C83FD2ED7-1](https://user-images.githubusercontent.com/28145373/72184405-5e78cf80-33be-11ea-8893-bd1dda67e2b4.jpeg)

![IMG_D6548E368495-1](https://user-images.githubusercontent.com/28145373/72184427-69336480-33be-11ea-9edb-27d95b93b5b3.jpeg)

**Expected result:**
tip amounts to be in order (least to greatest) when going left to right on the buttons:
![IMG_C9E0CE394F14-1](https://user-images.githubusercontent.com/28145373/72184470-80725200-33be-11ea-87af-8634ba6a0ac2.jpeg)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily for custom tip amounts

**Brave Version:** 
1.14.2 and 1.15

**Device details:** 
iPad

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.12.10)
- Verified publisher custom tip is ordered
![image](https://user-images.githubusercontent.com/17010094/74643445-ba432f00-519a-11ea-875d-da5f9437a246.png)

------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified publisher custom tip is ordered
![image](https://user-images.githubusercontent.com/17010094/74643438-b6171180-519a-11ea-8b39-f5b204eaf78e.png)

------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.12.10)
- Verified publisher custom tip is ordered
![image](https://user-images.githubusercontent.com/17010094/74643475-c4fdc400-519a-11ea-95e0-54244254ec0d.png)

------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified publisher custom tip is ordered
![image](https://user-images.githubusercontent.com/17010094/74643445-ba432f00-519a-11ea-875d-da5f9437a246.png)

------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.12.10)
- Verified publisher custom tip is ordered
![image](https://user-images.githubusercontent.com/17010094/74643438-b6171180-519a-11ea-8b39-f5b204eaf78e.png)

------
