### ISSUE TITLE
User should be informed a Form is not secure

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#218]
### Steps to Reproduce 
  1. Navigate to "badssl.com"
  2. Select either the `very` or `mixed-form` content link
  3. Submit a form

**Actual result:** User is not informed the form is not secure

**Expected result:** User should be informed the form is not secure

**Reproduces how often:** Every time

**Brave Version:** Development build hash e9d99c36697bc59ff348d174f5dfc6532bd95b3c

**Device details:** iPad Pro 10.5" iOS 11.4.1

**Comment by tildelowengrimm** [comment]
This was also reported at https://hackerone.com/reports/402488

**Comment by diracdeltas** [comment]
Discussed in security review; we would like this prioritized for next release.

**Comment by jhreis** [comment]
https://github.com/brave/browser-ios/issues/1729 is for the current repo, and we have scheduled it for the next release!

**Comment by tmancey** [comment]
Resolved by #215, awaiting feedback/sign-off from @tomlowenthal concerning implementation which matches Chrome

**Comment by kylehickinson** [comment]
Closing as our current solution matches Chrome.
