### ISSUE TITLE
Verify Wallet text doesn't match desktop

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#2180]
### Description: 
Desktop Verify Wallet modal text was updated for 1.3.x with https://github.com/brave/brave-browser/issues/7102. After that update, the Verify Wallet screen on iOS does not match desktop 1.3.x.

### Steps to Reproduce 
  1. Install 1.15
  2. Enable Rewards
  3. Tap on Verify Wallet

**Actual result:** 
![IMG_0445](https://user-images.githubusercontent.com/28145373/72189392-ac93d000-33ca-11ea-9877-821cf7b76a7d.PNG)

**Expected result:**
<img width="711" alt="Screen Shot 2020-01-10 at 4 53 37 PM" src="https://user-images.githubusercontent.com/28145373/72189407-bae1ec00-33ca-11ea-8a9a-5c0dca22d7cf.png">

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.15 (20.01.07.17)

**Device details:** 
iPad 5th gen

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
cc @anthonypkeane @jamesmudgett @jenn-rhim
