### ISSUE TITLE
Add Funds text on panel is barely readable

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#2181]
### Description: 
`Add Funds` text on BR panel is barely readable.

https://github.com/brave/brave-ios/issues/2169 says Add/Withdraw funds will be moved from settings, but doesn't specify if the Add Funds button on the panel will be removed as well. 

### Steps to Reproduce 
  1. Enable Rewards
  2. Connect (KYC'd) uphold account
  3. Look at BR panel

**Actual result:** 
![IMG_0446](https://user-images.githubusercontent.com/28145373/72191236-94727f80-33cf-11ea-8bf9-77bf40dddf93.jpg)

**Expected result:**
`Add Funds` text to be readable

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.15 (20.01.07.17)

**Device details:** 
iPad 5th Gen iOS 12.3.1

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
I assume this was iOS 12. As far as I know this button will not move, so definitely will fix

**Comment by LaurenWags** [comment]
@kylehickinson yep, iOS 12, will update description to include iOS version.

**Comment by srirambv** [comment]
Moving to user wallet milestone
