### ISSUE TITLE
Photo app restriction doesn't prompt to change on iOS 13 [Follow up to #903]

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2191]
### Description: 
Photo app restriction doesn't prompt to change on iOS 13 [Follow up to #903]

### Steps to Reproduce 
  1. Set Photo apps to never
  2. Try to save an image from  a page
  3. No UI feedback to change settings to allow saving images

**Actual result:** 
![903Followup](https://user-images.githubusercontent.com/17010094/72287196-95482300-3614-11ea-914c-b1b84ef4f1e1.gif)

**Expected result:**
Some UI feedback to change photo permission for app

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.15(20.01.07.17)

**Device details:** 
iPhone XR 

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)?  N/A

### Additional Information
Not blocking 1.15 but please move if required

**Comment by iccub** [comment]
This is a system context menu and a system prompt, we can't change it at the moment.
Not closing this, we'll see if iOS 14 will gives us some way to manipulate it
