### ISSUE TITLE
Typo error on sync warn message

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2193]
### Description: 
Typo error on sync warn message

### Steps to Reproduce 
  1. Enable sync on device
  2. Select add a device
  3. Find a typo error on sync message

**Actual result:** 
Typo error that everyone missed so far

**Expected result:**
No typo errors 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.15(20.1.13.17)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)?  N/A

### Additional Information
Typo error shipped already in 1.14.2

**Comment by srirambv** [comment]
The fix #2194  is not part of 1.15(20.02.12.10). Need to pull it in for next build

**Comment by srirambv** [comment]
moving out of 1.15 as the text is not replaced everywhere

**Comment by LaurenWags** [comment]
Verification passed on iPad 5th Gen with iOS 12 running 1.15 (20.3.4.18)
- Reproduced on `1.14.3`
- Confirmed when adding a device via QR code or words that `ahold` --> `hold`
![IMG_0458](https://user-images.githubusercontent.com/28145373/75994267-b4528b00-5ec8-11ea-85e3-06292f851a17.jpg)
![IMG_0459](https://user-images.githubusercontent.com/28145373/75994275-b6b4e500-5ec8-11ea-83c4-0eb72b1c9dba.jpg)

----

Verification passed on iPad mini with iOS 13 running 1.15 (20.3.4.18)
- Reproduced on `1.14.3`
- Confirmed when adding a device via QR code or words that `ahold` --> `hold`
![IMG_0021](https://user-images.githubusercontent.com/28145373/75994417-f4197280-5ec8-11ea-82e6-7d3a06aaf9f8.jpg)
![IMG_0022](https://user-images.githubusercontent.com/28145373/75994421-f67bcc80-5ec8-11ea-80dc-93098af9d3ef.jpg)

----

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.15 (20.03.05.13)`:

- Reproduced the issue on `1.14.3`
- Confirmed when adding a device via QR code or words that `ahold` --> `hold`

<img width="588" alt="Screen Shot 2020-03-09 at 2 49 27 PM" src="https://user-images.githubusercontent.com/2602313/76247160-7bdae600-6215-11ea-9196-7515cad6ac47.png">

<img width="586" alt="Screen Shot 2020-03-09 at 2 49 18 PM" src="https://user-images.githubusercontent.com/2602313/76247169-7f6e6d00-6215-11ea-893e-d04b6e91634b.png">

----

Verification **PASSED** on `iPhone 11` running `iOS 13.3.1` using `1.15 (20.03.05.13)`:

- Reproduced the issue on `1.14.3`
- Confirmed when adding a device via QR code or words that `ahold` --> `hold`

<img width="488" alt="Screen Shot 2020-03-09 at 2 53 54 PM" src="https://user-images.githubusercontent.com/2602313/76247378-d3795180-6215-11ea-85d9-b16487f53db5.png">

<img width="487" alt="Screen Shot 2020-03-09 at 2 53 46 PM" src="https://user-images.githubusercontent.com/2602313/76247385-d6744200-6215-11ea-9494-2555fe86db44.png">
