### ISSUE TITLE
remove user wallets from region where it is restricted/not supported

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#2198]
### Description: 
On desktop we had to remove user wallets/Uphold from Japan since it is not supported there. We probably need to do the same for iOS when user wallets are released.

Related desktop items:
https://github.com/brave/brave-browser/issues/5883
https://github.com/brave/brave-core/pull/3444

### Steps to Reproduce 
Scenarios
  1. Clean profile - Enable Rewards for Japan, verify no Uphold/user wallets
  2. Upgrade from a Japan (rewards enabled profile), verify no Uphold/user wallets 

### Additional Information
Unsure if any design work is needed for this.
cc @kylehickinson @mandar-brave @anthonypkeane @srirambv

**Comment by kylehickinson** [comment]
Already completed (will not show button to connect if you are seeing "BAP" JP strings), but should be tested nonetheless (cc @srirambv @kjozwiak)
