### ISSUE TITLE
Regular home screen is showing after entering private mode

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#220]
### Steps to Reproduce 
  1. Enter private mode

**Actual result:** 
Top sites screen is showing.

**Expected result:**
Private home screen should show, on dark background

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
It worked before, looks like a regression

**Comment by tmancey** [comment]
@jhreis Need design approval

**Comment by iccub** [comment]
We could just do it with 1.6 parity

**Comment by jhreis** [comment]
If Private Browsing copy is moved into tab tray, than this is actually correct behavior.

**Comment by kylehickinson** [comment]
This is no longer a bug as Private Browsing copy is moved into the tab tray. Closing and continuing issue tracking in #277
