### ISSUE TITLE
entire a-c not going through due to missing delays

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2200]
Placeholder for https://github.com/brave/brave-browser/issues/7709 which also needs to be fixed on iOS as all current platforms are affected. Quick summary of issue:

When going through an a-c, the entire amount doesn't go through when you have multiple entries in the a-c table due to missing delays

Created issues for iOS & Android:

* Desktop - https://github.com/brave/brave-browser/issues/7709
* Android - https://github.com/brave/browser-android-tabs/issues/2442

CCing @NejcZdovc @jhreis @anthonypkeane @srirambv

**Comment by kylehickinson** [comment]
Requires DB migration to get the fix from brave-core

**Comment by kjozwiak** [comment]
@NejcZdovc re: the database migration, is that referring to https://github.com/brave/brave-core/pull/4252 which you're currently working on?

**Comment by NejcZdovc** [comment]
@kjozwiak yes

**Comment by kylehickinson** [comment]
Will be fixed with #2378

**Comment by srirambv** [comment]
Verification passed on iPhone XR/iPhone 7+/iPhone SE/iPad Pro (iOS 12)/iPad Pro (iOS 13).
- Verification notes https://github.com/brave/brave-ios/issues/2378#issuecomment-612976216
