### ISSUE TITLE
Incorrect message to a verified Brave creator on iOS (Testflight and production versions)

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-ios#2202]
If a user on iOS is browser wallet (iOS does not support user wallets) opens a panel, the panel shows incorrect message about the creator.

see image below:
![image](https://user-images.githubusercontent.com/35932307/72447024-74451680-3769-11ea-8bf9-376a2e79994e.png)

Expected:
No text is expected to be shown. A non user wallet should be able to tip all Brave verified creators, with our without an Uphold account, without an ID check.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.3.1 running 1.14.3(20.01.23.16)
- Verified no sign up message for connected publisher is shown
- Verified on DDG which is a connected publisher on production
------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.14.3(20.01.23.16)
- Verified no sign up message for connected publisher is shown
- Verified on DDG which is a connected publisher on production
------
Verification passed on iPhone 6 with iOS 12.4.4 running 1.14.3(20.01.23.16)
- Verified no sign up message for connected publisher is shown
- Verified on DDG which is a connected publisher on production
------
Verification passed on iPad Pro with iOS 13.3.1 running 1.14.3(20.01.23.16)
- Verified no sign up message for connected publisher is shown
- Verified on DDG which is a connected publisher on production
------
Verification passed on iPad Pro with iOS 12.4.4 running 1.14.3(20.01.23.16)
- Verified no sign up message for connected publisher is shown
- Verified on DDG which is a connected publisher on production
------
