### ISSUE TITLE
Tabs bar showing when there is only 1 tab

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#221]
### Steps to Reproduce 
  1. Enter private mode
  2. Notice there's one tab open and tab bar is showing
  3. Go back to normal mode
  4. Notice there's one tab open and tab bar is showing, it was not there before entering private mode.

**Actual result:** 
Tab bar showing for 1 tab.

**Expected result:**
Tab bar should hide if there's only one tab open.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
Should add that this is simply due to the fact that we are counting all tabs and not number of tabs in that mode for whether to show the tab bar
