### ISSUE TITLE
Implement Safari / iOS UA 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2210]
## Problem Description 
Internal Chat:https://bravesoftware.slack.com/archives/C06UXF3KJ/p1579048485052400

Please implement the Safari / iOS UA 

cc @snyderp

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified desktop UA matches with Safari
![image](https://user-images.githubusercontent.com/17010094/74510687-4dc1f900-4f2a-11ea-91c5-2864b64aa9e8.png)
![image](https://user-images.githubusercontent.com/17010094/74510672-47cc1800-4f2a-11ea-8678-bf3f75d10423.png)
- Verified mobile UA matches with Safari
![image](https://user-images.githubusercontent.com/17010094/74510708-57e3f780-4f2a-11ea-91b9-0b035a1b7f3b.png)
![image](https://user-images.githubusercontent.com/17010094/74510714-5c101500-4f2a-11ea-8cb7-1366ac435802.png)
- Verified sites override multiple domains worked as per test plan in #2309 
- Verified site overrides on iPad 13 with Desktop mode preference enabled as per test plan in #2309 
- Verified site overrides on iPad 13 with Desktop mode preference disabled as per test plan in #2309 
- Verified UA on per tab is retained for the same domain 
- Verified popular sites don't break when switching between Mobile <-> Desktop site
--------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.12.10)
- Verified desktop UA matches with Safari
![image](https://user-images.githubusercontent.com/17010094/74510763-74802f80-4f2a-11ea-8243-40be72e1ceaf.png)
![image](https://user-images.githubusercontent.com/17010094/74510789-83ff7880-4f2a-11ea-937f-6179f3792e99.png)
- Verified mobile UA matches with Safari
![image](https://user-images.githubusercontent.com/17010094/74510775-79dd7a00-4f2a-11ea-81ef-962c29b9dbbf.png)
![image](https://user-images.githubusercontent.com/17010094/74510801-895cc300-4f2a-11ea-8547-622746e7d6a0.png)
- Verified sites override multiple domains worked as per test plan in #2309 
- Verified UA on per tab is retained for the same domain 
- Verified popular sites don't break when switching between Mobile <-> Desktop site
---------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified desktop UA matches with Safari
![image](https://user-images.githubusercontent.com/17010094/74521124-ee221880-4f3e-11ea-87d1-d9256bccd229.png)
![image](https://user-images.githubusercontent.com/17010094/74521242-1873d600-4f3f-11ea-92f9-ecfb19bc5c14.png)
- Verified mobile UA matches with Safari
![image](https://user-images.githubusercontent.com/17010094/74521226-11e55e80-4f3f-11ea-98fe-3215f3b6c26f.png)
![image](https://user-images.githubusercontent.com/17010094/74521205-0bef7d80-4f3f-11ea-90bd-c801f479aa7c.png)
- Verified sites override multiple domains worked as per test plan in #2309 
- Verified site overrides on iPad 13 with Desktop mode preference enabled as per test plan in #2309 
- Verified site overrides on iPad 13 with Desktop mode preference disabled as per test plan in #2309 
- Verified UA on per tab is retained for the same domain 
- Verified popular sites don't break when switching between Mobile <-> Desktop site
--------------
Verification passed on iPhone XR with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified desktop UA matches with Safari
- Verified mobile UA matches with Safari
- Verified sites override multiple domains worked as per test plan in #2309 
- Verified site overrides on iPad 13 with Desktop mode preference enabled as per test plan in #2309 
- Verified site overrides on iPad 13 with Desktop mode preference disabled as per test plan in #2309 
- Verified UA on per tab is retained for the same domain 
- Verified popular sites don't break when switching between Mobile <-> Desktop site
--------
Verification passed on iPhone 6 with iOS 12.4.4 running 1.15(20.02.12.10)
- Verified desktop UA matches with Safari
- Verified mobile UA matches with Safari
- Verified sites override multiple domains worked as per test plan in #2309 
- Verified UA on per tab is retained for the same domain 
- Verified popular sites don't break when switching between Mobile <-> Desktop site
