### ISSUE TITLE
Internal Issue #678

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2211]
### Description: 
Pls implement https://github.com/brave/internal/issues/678

**Comment by anthonypkeane** [comment]
@jhreis This sounds like a trivial piece of work. If we can squeeze it into 1.15 it would be super

**Comment by srirambv** [comment]
@kylehickinson can you please add the test plan for this?

**Comment by kylehickinson** [comment]
@srirambv There's not really an easy test plan: https://github.com/brave/internal/issues/678#issuecomment-586325126

**Comment by srirambv** [comment]
Marking as QA/No due to the complexity of verifying it. same was done on Android-core as well.
