### ISSUE TITLE
Users reporting increased storage on iOS

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2213]
### Description: 
Users are reporting that Brave is taking a huge amount of storage on iOS

Internal thread: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1579142841080600
https://twitter.com/mkirank/status/1217638409016995840?s=12

**Comment by Brandon-T** [comment]
I have investigated this issue
![IMG_53DF0C91C760-1](https://user-images.githubusercontent.com/1530031/73485127-8aa9bf80-4370-11ea-916f-07dca9eb4c74.jpeg)

I have checked every single file in Brave iOS. There are `436,636` rows of publishers in `BraveRewards.sqlite` and `33105` publisher amount rows. It seems to stable out at around 105.7mb.

The size of this database seems to be quite consistent. I have checked over the last 1 hour.. I can continue to monitor it but I believe it to be stabled. At most it'd fluctuate at ~7kb.

I really don't see it increasing but I will check again in another hour or two and confirm for sure.

@kylehickinson

**Comment by anthonypkeane** [comment]
https://appfigures.com/reviews/42132121512LwWZWZac4E5haXJVICiQ5gQ?lang=en

- Taking up 2GB of space!?!?!? Why?

**Comment by Brandon-T** [comment]
@anthonypkeane Posted 7 days ago. This seems like it's happening on upgrade??
One user reports on https://community.brave.com/t/ios-browser-storage-usage/100687/8

> Hi there
> 
> I tried the following which brought the data used down from 2.8GB to 193MB:
> 
> Open “Settings” -> Brave -> Photos -> Tap “Never”
> closed all Apps
> shut down the iPhone
> switched it back on and entered the code and the SIM PIN
> looked at Settings -> General -> iPhone-Memory

I can't see how it's possible that they'd be saving that many photos.. I checked the code in the app, there's nothing that would save photos automatically.

**Comment by iccub** [comment]
closing as stale, latest complaints from users we heard were mostly for playlists which we fixed
