### ISSUE TITLE
Move Monthly Contributions into its own section

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2218]
### Description: 

Desktop moved recurring tips into its own list whereas iOS currently lumps them into "Tips"

<img width="642" alt="image" src="https://user-images.githubusercontent.com/529104/72835162-37d95500-3c58-11ea-9fe4-f18af28a03a0.png">

iOS should have a simple table for only recurring tips that is accessed separately in settings like desktop

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified monthly contribution is a separate section in rewards panel
![image](https://user-images.githubusercontent.com/17010094/74503690-b81d6e00-4f17-11ea-815b-f683e8cb02f8.png)
- Verified view details shows publishers that have monthly contributions set
![image](https://user-images.githubusercontent.com/17010094/74503694-bd7ab880-4f17-11ea-9202-332c0669d305.png)
------
Verification passed on iPhone XR with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified monthly contribution is a separate section in rewards panel
![image](https://user-images.githubusercontent.com/17010094/74503704-c1a6d600-4f17-11ea-9b0c-cdf9152ea0c1.png)
- Verified view details shows publishers that have monthly contributions set
![image](https://user-images.githubusercontent.com/17010094/74503709-c5d2f380-4f17-11ea-9012-c90d89bad390.png)
------
Verification passed on iPhone 6 with iOS 12.4.4 running 1.15(20.02.12.10)
- Verified monthly contribution is a separate section in rewards panel
![image](https://user-images.githubusercontent.com/17010094/74503799-219d7c80-4f18-11ea-9e35-4e6b30e4ea96.png)
- Verified view details shows publishers that have monthly contributions set
![image](https://user-images.githubusercontent.com/17010094/74503804-25c99a00-4f18-11ea-815f-f1a168a9fdf4.png)
------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified monthly contribution is a separate section in rewards panel
![image](https://user-images.githubusercontent.com/17010094/74506194-18fc7480-4f1f-11ea-8bb0-0e76cf27fadd.png)
- Verified view details shows publishers that have monthly contributions set
![image](https://user-images.githubusercontent.com/17010094/74506140-efdbe400-4f1e-11ea-9c38-29b2db69783b.png)
------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.12.10)
- Verified monthly contribution is a separate section in rewards panel
![image](https://user-images.githubusercontent.com/17010094/74506124-e3f02200-4f1e-11ea-8f59-869affa81302.png)
- Verified view details shows publishers that have monthly contributions set
![image](https://user-images.githubusercontent.com/17010094/74506114-df2b6e00-4f1e-11ea-95f8-a142401446b9.png)
