### ISSUE TITLE
Turn on ads message on landscape mode covers half of the NTP view

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2224]
### Description: 
Turn on ads message on landscape mode covers half of the NTP view

### Steps to Reproduce 
  1. Enable rewards on a build that doesn't have ads
  2. Upgrade to 1.4.3 
  3. Enable ads message is shown, Rotate device to landscape 

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/73006117-18693600-3dd8-11ea-93c0-df48e0227a5c.png)

**Expected result:**
Size does matter so better to have a smaller modal 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.4.3

**Device details:** 
iPhone 7+

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by iccub** [comment]
We decided to make it centered on all layout but portrait iPhone, width limited to 400

**Comment by srirambv** [comment]
This needs to be tested again on new build as the design is changed. https://github.com/brave/brave-ios/issues/2224#issuecomment-577879506 is obsolete now

**Comment by btlechowski** [comment]
Verification passed on 1.14.3(20.01.28.18) on Dev on iPhone SE (iOS 12.4)
- Regular page
  - Light Theme
![IMG_0012](https://user-images.githubusercontent.com/34715963/73318751-aa3ecc00-423a-11ea-9b03-84d03999adee.PNG)

  - Dark Theme
![IMG_0013](https://user-images.githubusercontent.com/34715963/73318762-b1fe7080-423a-11ea-90ad-02b4c9891f2e.PNG)


- Sponsored page
  - Light Theme
  ![IMG_0009](https://user-images.githubusercontent.com/34715963/73312952-414f5800-422a-11ea-9668-856782ef49d1.PNG)
  - Dark Theme
  ![IMG_0010](https://user-images.githubusercontent.com/34715963/73312963-48766600-422a-11ea-9ae4-3ba2e13c7bef.PNG)

Verification **PASSED** on `iPhone 11` running `iOS 13.3` using `1.14.3 (20.01.28.18)` via production:

![IMG_0008](https://user-images.githubusercontent.com/2602313/73324507-2f18ee00-4219-11ea-955f-24924c103fe5.PNG)

![IMG_0007](https://user-images.githubusercontent.com/2602313/73324508-2f18ee00-4219-11ea-88b2-814b25a4dede.PNG)

Verification **PASSED** on `iPhone 8` running `iOS 13.3` using `1.14.3 (20.01.29.20)` via production:
![IMG_0297](https://user-images.githubusercontent.com/38657976/73449490-4bd43380-4389-11ea-85b7-ec9e7b9c0a10.PNG)
![IMG_0298](https://user-images.githubusercontent.com/38657976/73449491-4c6cca00-4389-11ea-8c4b-c8ccf97bfd05.PNG)
