### ISSUE TITLE
Implement Siri Shortcuts

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2227]
### Description: 
Spec: Search for "Share Data with Siri"

**Comment by srirambv** [comment]
<details>
<summary>Verification passed on iPad Pro with iOS 14.6 running 1.29(21.07.28.22)</summary>

- Verified test plan from https://github.com/brave/brave-ios/pull/3579
- Verified new setting option for Siri Shortcuts is shown under General settings
- Verified Add to Siri shortcuts are shown and disabled by default 
- Verified able to add Siri shortcuts via settings menu
- Verified saying the voice command performs the specific actions
-  Verified able to delete a Siri shortcut via Settings menu
- Verified Open Settings links to Device Settings app and selects Brave 
- Verified voice commands work for both normal and private tabs
- Verified when Brave News / VPN is not enabled it opens up the specific setting page
- Verified when opt-ed into Brave News, voice command opens a new tab and opens Brave News feed
- Verified voice command for New tab/Private tab works as expected
- Verified Brave Playlist voice command only opens the playlist but doesn't play any video from the list
- Verified able to access Siri voice commands via lock screen/home screen and the action is performed correctly
- Verified typing in the command in Siri suggestions performs the commands correctly and launches Brave
- Verified clicking on Play button on Siri Shortcuts performs the task correctly and launches Brave 

Settings | Siri Shortcuts | Add Shortcut | Edit Shortcut | Delete Shortcut | Siri Shortcuts Cards
-- | -- | -- | -- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/127478928-40b7e2be-861b-4772-ac89-eb612f868551.png) | ![image](https://user-images.githubusercontent.com/17010094/127478899-4afcce6b-c8bc-407d-9045-d7a77e60e160.png) | ![image](https://user-images.githubusercontent.com/17010094/127479017-c96e30c0-d1aa-40ab-a0d6-28db4aacf50f.png) | ![image](https://user-images.githubusercontent.com/17010094/127478970-a763266b-716d-44d0-bb05-541cf43d4565.png) | ![image](https://user-images.githubusercontent.com/17010094/127478991-38b76923-69c4-4795-993f-d1b8d5f617ae.png) | ![image](https://user-images.githubusercontent.com/17010094/127479032-b620f435-ac8a-4d30-9b04-e51b28dd11f4.png)


https://user-images.githubusercontent.com/17010094/127479915-78fa0790-e8ca-4b92-8980-a7d5548d396d.MP4


https://user-images.githubusercontent.com/17010094/127480082-1a51e3cf-a97b-4129-ac4a-663924d8bbf3.MP4


</details>

------------
<details>
<summary>Verification passed on iPhone 7+ with iOS 14.5.1 running 1.29(21.07.28.22)</summary>

- Verified test plan from https://github.com/brave/brave-ios/pull/3579
- Verified new setting option for Siri Shortcuts is shown under General settings
- Verified Add to Siri shortcuts are shown and disabled by default 
- Verified able to add Siri shortcuts via settings menu
- Verified saying the voice command performs the specific actions
-  Verified able to delete a Siri shortcut via Settings menu
- Verified Open Settings links to Device Settings app and selects Brave 
- Verified voice commands work for both normal and private tabs
- Verified when Brave News / VPN is not enabled it opens up the specific setting page
- Verified when opt-ed into Brave News, voice command opens a new tab and opens Brave News feed
- Verified voice command for New tab/Private tab works as expected
- Verified Brave Playlist voice command only opens the playlist but doesn't play any video from the list
- Verified able to access Siri voice commands via lock screen/home screen and the action is performed correctly
- Verified typing in the command in Siri suggestions performs the commands correctly and launches Brave
- Verified clicking on Play button on Siri Shortcuts performs the task correctly and launches Brave 

Settings | Siri Shortcuts | Add Shortcut | Edit Shortcut | Delete Shortcut | Siri Shortcuts Cards
-- | -- | -- | -- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/127482969-f2e4073f-4e90-4cfd-b224-ea5e4e233f3a.png) | ![image](https://user-images.githubusercontent.com/17010094/127482995-81bacb5d-c2e7-43e9-a1fa-b96bbd15509b.png) | ![image](https://user-images.githubusercontent.com/17010094/127483022-9bb450ca-c931-4ddc-a7aa-0c53c3a17fcf.png) | ![image](https://user-images.githubusercontent.com/17010094/127483010-05626a87-d316-4993-a85e-5da3849aeb3e.png) | ![image](https://user-images.githubusercontent.com/17010094/127483127-f1dcae58-6391-4371-a637-18d33875125f.png) | ![image](https://user-images.githubusercontent.com/17010094/127483036-36c99d68-f866-40b7-954b-ccdc5c8ca7d2.png)


https://user-images.githubusercontent.com/17010094/127482339-6c7be32b-043e-427d-8a43-40c4de85b5b0.MP4


https://user-images.githubusercontent.com/17010094/127482390-3af8f409-9b5f-4395-bc0d-88620ac38193.MP4


</details>

------------------
<details>
<summary>Verification passed on iPhone XR with iOS 13.5 running 1.29(21.07.28.22)</summary>

- Verified test plan from https://github.com/brave/brave-ios/pull/3579
- Verified new setting option for Siri Shortcuts is shown under General settings
- Verified Add to Siri shortcuts are shown and disabled by default 
- Verified able to add Siri shortcuts via settings menu
- Verified saying the voice command performs the specific actions
-  Verified able to delete a Siri shortcut via Settings menu
- Verified Open Settings links to Device Settings app and selects Brave 
- Verified voice commands work for both normal and private tabs
- Verified when Brave News / VPN is not enabled it opens up the specific setting page
- Verified when opt-ed into Brave News, voice command opens a new tab and opens Brave News feed
- Verified voice command for New tab/Private tab works as expected
- Verified Brave Playlist voice command only opens the playlist but doesn't play any video from the list
- Verified able to access Siri voice commands via lock screen/home screen and the action is performed correctly
- Verified typing in the command in Siri suggestions performs the commands correctly and launches Brave
- Verified clicking on Play button on Siri Shortcuts performs the task correctly and launches Brave 

Settings | Siri Shortcuts | Add Shortcut | Edit Shortcut | Delete Shortcut | Siri Shortcuts Cards
-- | -- | -- | -- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/127480382-b67fdde9-a037-4e9e-8c24-29c94424168b.png) | ![image](https://user-images.githubusercontent.com/17010094/127480397-e3ccc4dd-02cf-42df-999f-bad08b2083d9.png) | ![image](https://user-images.githubusercontent.com/17010094/127480584-47d8f6fe-5ec9-4d3c-a506-ee0cbc10f66b.png)| ![image](https://user-images.githubusercontent.com/17010094/127480434-4e73870d-73b8-431c-9d06-9124acfe0bf2.png) | ![image](https://user-images.githubusercontent.com/17010094/127480456-3170c317-3beb-46cc-8cbf-16553155c38d.png) | ![image](https://user-images.githubusercontent.com/17010094/127480470-a6463124-4c18-43b6-828e-cdcb14e13f5b.png)

https://user-images.githubusercontent.com/17010094/127480420-3bec56d6-8c3a-4b64-abaf-939631c8d408.MP4


https://user-images.githubusercontent.com/17010094/127480356-d6f7947c-72f0-485c-bda0-c03e3316c69d.MP4


</details>
