### ISSUE TITLE
Sponsored images should not be shown in PBO mode

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2229]
### Description: 
Sponsored images should not be shown in PBO mode

### Steps to Reproduce 
  1. Install 1.14.3 build 
  2. View a branded image on NTP
  3. Switch to PBO, branded images are shown on Private tabs

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/73074662-1ced2780-3e88-11ea-8d75-73f783df45a8.png)

**Expected result:**
No branded images on Private tabs(both private tab in regular browsing mode and PBO mode)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14.3(20.1.24.10)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc @iccub

**Comment by srirambv** [comment]
Scenario 2 
- Clean install 1.14.3
- Launch browser, skip onboarding
- Go to settings and enable PBO mode
- Open a site on the current Private tab
- Open a second new tab, shows branded image as background

**Comment by iccub** [comment]
Will be fixed here https://github.com/brave/brave-ios/issues/2229

**Comment by iccub** [comment]
Should be fixed on latest beta build, re-open if it's not

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 13.3.1 running 1.14.3(20.01.25.15)
- Clean install
```
- Install and skip onboarding, Enable PBO, no sponsored images are shown
- Install and enable rewards via onboarding, Enable PBO, no sponsored images are shown
```
- Upgrade Install
```
- Install 1.14.2, enable PBO, upgrade to 1.14.3, no sponsored images are shown
- Install 1.14.2, upgrade to 1.14.3 and enable PBO, no sponsored images are shown 
```
-----------
Verification passed on iPhone XR with iOS 13.3.1 running 1.14.3(20.01.25.15)
- Clean install
```
- Install and skip onboarding, Enable PBO, no sponsored images are shown
- Install and enable rewards via onboarding, Enable PBO, no sponsored images are shown
```
- Upgrade Install
```
- Install 1.14.2, enable PBO, upgrade to 1.14.3, no sponsored images are shown
- Install 1.14.2, upgrade to 1.14.3 and enable PBO, no sponsored images are shown 
```
-----------
Verification passed on iPhone 7++ with iOS 13.3.1 running 1.14.3(20.01.25.15)
- Clean install
```
- Install and skip onboarding, Enable PBO, no sponsored images are shown
- Install and enable rewards via onboarding, Enable PBO, no sponsored images are shown
```
- Upgrade Install
```
- Install 1.14.2, enable PBO, upgrade to 1.14.3, no sponsored images are shown
- Install 1.14.2, upgrade to 1.14.3 and enable PBO, no sponsored images are shown 
```
-----------
Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.4.3 (20.1.27.18)`

- Clean install
```
- Install and skip onboarding, Enable PBO, no sponsored images are shown
- Install and enable rewards via onboarding, Enable PBO, no sponsored images are shown
```
- Upgrade Install
```
- Install 1.14.2, enable PBO, upgrade to 1.14.3, no sponsored images are shown
- Install 1.14.2, upgrade to 1.14.3 and enable PBO, no sponsored images are shown 
```
-----------
Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.4.3 (20.1.27.18)`

- Clean install
```
- Install and skip onboarding, Enable PBO, no sponsored images are shown
- Install and enable rewards via onboarding, Enable PBO, no sponsored images are shown
```
- Upgrade Install
```
- Install 1.14.2, enable PBO, upgrade to 1.14.3, no sponsored images are shown
- Install 1.14.2, upgrade to 1.14.3 and enable PBO, no sponsored images are shown 
```

Verification is passed on iPhone 8 (iOS 13.3) running 1.14.3 (20.01.29.10) 
- Verified on both clean and upgraded profile
