### ISSUE TITLE
No UI feedback when hide sponsored image is selected

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2231]
### Description: 
No UI feedback when hide sponsored image is selected

### Steps to Reproduce 
  1. Upgrade to 1.14.3
  2. View a branded image
  3. Tap on the `Learn more`, brings up the info modal
  4. Tap on `hide sponsored image`, modal is dismissed without any UI feedback of setting being disabled

**Actual result:** 
No UI feedback when hide sponsored image is selected

**Expected result:**
Show confirmation that setting is disabled

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14.3(20.01.24.10)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
It should reload the current image, if it's a sponsored image it is be reloaded as well

See my low quality gif:

![out](https://user-images.githubusercontent.com/6950387/73190381-34494080-4126-11ea-8c7c-179491cda51c.gif)

**Comment by iccub** [comment]
Should be fixed by ntp refactor
