### ISSUE TITLE
Disable background images is broken on upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2233]
### Description: 
Disable background images is broken on upgrade

### Steps to Reproduce 
  1. Install 1.14.2 and disable background images
  2. Upgrade to 1.14.3 
  3. NTP shows images even though setting is disabled

**Actual result:** 
Disable background images is broken on upgrade

**Expected result:**
Background images should be disabled upon upgrade

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14.3(20.01.24.10)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Will be fixed here https://github.com/brave/brave-ios/pull/2203#pullrequestreview-348111443

**Comment by iccub** [comment]
Should be fixed on latest beta build, re-open if it's not

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.3.1 running 1.14.3(20.01.27.18)
- Verified disabling background image on 1.14.2 and upgrading to 1.14.3 doesn't show background images
- Verified enabling background images starts to show sponsored images
---------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.14.3(20.01.27.18)
- Verified disabling background image on 1.14.2 and upgrading to 1.14.3 doesn't show background images
- Verified enabling background images starts to show sponsored images
---------
Verification passed on iPad Pro with iOS 13.3.1 running 1.14.3(20.01.27.18)
- Verified disabling background image on 1.14.2 and upgrading to 1.14.3 doesn't show background images
- Verified enabling background images starts to show sponsored images
---------
Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.4.3 (20.1.27.18)`

* Verified disabling background image on `1.14.2` and upgrading to `1.14.3` doesn't show background images
* Verified enabling background images starts to show sponsored images
---------
Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.4.3 (20.1.27.18)`

* Verified disabling background image on `1.14.2` and upgrading to `1.14.3` doesn't show background images
* Verified enabling background images starts to show sponsored images
