### ISSUE TITLE
Adjust padding in DDG logo and Font

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#2235]
Bold 13px system font. Add more padding to match image.

## new design
![Screen Shot 2020-01-24 at 1 33 11 PM](https://user-images.githubusercontent.com/318119/73098047-34d7a200-3eae-11ea-843c-521e4ebb9083.png)

## old design
![File](https://user-images.githubusercontent.com/318119/73096690-fe4c5800-3eaa-11ea-97c4-5d0f988f369c.jpg)

**Comment by iccub** [comment]
Closed in https://github.com/brave/brave-ios/pull/2316

**Comment by srirambv** [comment]
- Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.20.19)
![image](https://user-images.githubusercontent.com/17010094/75006359-7e101700-5497-11ea-8b15-2950440943f4.png)

- Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.20.19)
![image](https://user-images.githubusercontent.com/17010094/75006385-908a5080-5497-11ea-838f-448aedc6ba97.png)

- Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.20.19)
![image](https://user-images.githubusercontent.com/17010094/75005014-09d37480-5493-11ea-8b44-000072bf3d4a.png)

- Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.20.19)
![image](https://user-images.githubusercontent.com/17010094/75006297-4a34f180-5497-11ea-883f-75fbf613963e.png)


- Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.20.19)
![image](https://user-images.githubusercontent.com/17010094/75006340-6e90ce00-5497-11ea-8d83-2de18b1430dd.png)
