### ISSUE TITLE
Sample ad notification is not triggered when enabling rewards via sponsored image onboarding

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2237]
### Description: 
Sample ad notification is not triggered when enabling rewards via sponsored image onboarding

### Steps to Reproduce 
  1. Clean install 1.14.3
  2. Skip onboarding
  3. View sponsored image 
  4. Tap on learn more to bring up onboarding modal
  5. Tap on `Turn on Rewards`, sample ad notification is not triggered when rewards is enabled

**Actual result:** 
Sample ad notification is not triggered when enabling rewards via sponsored image onboarding

**Expected result:**
Sample ad notification should be triggered irrespective of how rewards is enabled

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
About 80% time. Sometime ad notification shows up when you open panel other(most) times doesn't show up at all

**Brave Version:** 
1.14.3(20.01.24.18)

**Device details:** 
iPad Pro (iOS 12.4.4)
iPhone 7+ (iOS 13.3.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

**Comment by btlechowski** [comment]
Verification passed on 1.14.3(20.01.28.18) on Production on iPhone SE (iOS 12.4). Verified 5 times.

![IMG_0007](https://user-images.githubusercontent.com/34715963/73310977-a3f22500-4225-11ea-9489-bf9b72479409.PNG)
![IMG_0008](https://user-images.githubusercontent.com/34715963/73310980-a48abb80-4225-11ea-8625-2b5d6170ef13.PNG)

Verification passed on 1.14.3(20.01.28.18) on Production on iPad 5th Gen (iOS 12). Ran thru STR in description 5x, each time I got the sample ad.

![IMG_6FBF09535CAA-1](https://user-images.githubusercontent.com/28145373/73314162-1dc0e900-41fb-11ea-9fd0-9709db69c15b.jpeg)

Verification passed on 1.14.3(20.01.28.18) on Production on iPad Mini (iOS 13). Ran thru STR in description 5x, each time I got the sample ad.

![IMG_866AEE3801FD-1](https://user-images.githubusercontent.com/28145373/73314176-22859d00-41fb-11ea-88aa-d84616d3c0c7.jpeg)

Verification passed on `1.14.3 (20.01.28.18)` on Production using `iPhone 11 (iOS 13.3)`

* ensured that enabling `Rewards` via the SNTP modal displayed the sample ad
* ensured that tapping on the sample ad correctly opened a new tab with the correct website
* ensured that enabling `Rewards` via the SNTP modal after upgrading from `1.14.2 (19.12.12.17)` displayed the sample ad
* went through the above cases x5 to ensure everything was working as expected

![IMG_0003](https://user-images.githubusercontent.com/2602313/73317123-038b0900-4203-11ea-8412-f5cd82ed1e0d.PNG)
![IMG_0002](https://user-images.githubusercontent.com/2602313/73317124-038b0900-4203-11ea-9645-0ad8ff0a38d1.PNG)
