### ISSUE TITLE
Text changes for sponsored images onboarding modal 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2238]
### Description: 
The text needs to be updated `By turning Rewards` should be `By turning on Rewards`. Also `Turn on Brave Rewards to claim your share` suggests that you get share right away after enabling rewards. 

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/73122811-fba73c80-3f56-11ea-820a-66bd6eb9789c.png)

**Expected result:**
TBD

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14.3

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
cc: @karenkliu @mandar-brave @anthonypkeane

**Comment by iccub** [comment]
Fixed in latest beta build, please reopen if it's not

**Comment by bradleyrichter** [comment]
@karenkliu Please see @srirambv 's point above about assumption of instant claim. We can refine this copy more.

**Comment by iccub** [comment]
I fixed the typo part, going to reopen this ticket for further discussion of copy in general

**Comment by karenkliu** [comment]
Yeah, good point, the word "claim" could be confusing because we use that word to actually disperse rewards to users. 

There are some new copy ideas floating around; we should collect them and come up with a string that works for all the use cases. I'll post here with updates.

**Comment by iccub** [comment]
Moving to 1.15

**Comment by kylehickinson** [comment]
Closed as this feature is no longer supported in new Rewards on Brave iOS
