### ISSUE TITLE
Sponsored images are shown for non-ads region

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2239]
### Description: 
Sponsored images are shown for non-ads region

### Steps to Reproduce 
  1. Install 1.14.2 and enable rewards on a non-ads region
  2. Ensure ads is not avaiable
  3. Upgrade to 1.14.3, shows sponsored images

**Actual result:** 
https://bravesoftware.slack.com/archives/CQGTGBNH1/p1579964048253800

**Expected result:**
No sponsored image for non-ads region

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14.3

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
cc: @karenkliu @iccub @jhreis

**Comment by iccub** [comment]
Fixed in latest beta build, please reopen if it's not

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.3.1 running 1.14.3(20.01.27.18)
- Verified upgrading from 1.14.2 to 1.14.3 doesn't show any sponsored background images
- Verified clean install of 1.1.4.3 doesn't show any sponsored background images
- Verified 1.14.3 doesn't have a `Show sponsored image` switch under NewTab settings
------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.14.3(20.01.27.18)
- Verified upgrading from 1.14.2 to 1.14.3 doesn't show any sponsored background images
- Verified clean install of 1.1.4.3 doesn't show any sponsored background images
- Verified 1.14.3 doesn't have a `Show sponsored image` switch under NewTab settings
------
Verification passed on iPad Pro with iOS 13.3.1 running 1.14.3(20.01.27.18)
- Verified upgrading from 1.14.2 to 1.14.3 doesn't show any sponsored background images
- Verified clean install of 1.1.4.3 doesn't show any sponsored background images
- Verified 1.14.3 doesn't have a `Show sponsored image` switch under NewTab settings
