### ISSUE TITLE
Learn more modal doesn't close other modals as well

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2243]
### Description: 
While testing #2230, found that the modals are not auto dismissed when `Learn more` is selected

### Steps to Reproduce 
  1. Install 1.14.3(20.01.25.15)
  2. Enable rewards via SNTP page
  3. Open a new tab with sponsored image, shows modal that you are earning for the NTP image
  4. Tap Learn more, opens a second modal
  5. Close second modal doesn't close the first  one

**Actual result:** 
![modal](https://user-images.githubusercontent.com/17010094/73199354-b1fb5500-4102-11ea-851c-b4953262b3bc.gif)

**Expected result:**
All modals should be closed at once when closing one of them

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14.3(20.01.25.15)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
cc: @iccub

**Comment by iccub** [comment]
Fixed in https://github.com/brave/brave-ios/pull/2203

**Comment by btlechowski** [comment]
Verification passed on 1.14.3(20.01.28.18) on Production on iPhone SE (iOS 12.4). 
- Verified both modals are closed at the same time

Verification passed on 1.14.3(20.01.28.18) on Production on iPad 5th Gen (iOS 12). 
- Verified both modals are closed
- Verified for both Portrait and Landscape modes

Verification passed on 1.14.3(20.01.28.18) on Production on iPad Mini (iOS 13). 
- Verified both modals are closed
- Verified for both Portrait and Landscape modes

Verification passed on `1.14.3 (20.01.28.18)` on `production` using `iPhone 11 (iOS 13.3)`:

- Verified both modals are being closed when closing the second modal via `X`
- Verified both modals are being closed when closing the second modal via via the swipe gesture
- Verified both cases using `portrait` and `landscape` modes

Verification passed on `1.14.3 (20.01.28.18)` on `production` using `iPhone 8 (iOS 13.3)`:

- Verified both modals are being closed when closing the second modal via `X`
- Verified both modals are being closed when closing the second modal via via the swipe gesture
- Verified both cases using `portrait` and `landscape` modes
