### ISSUE TITLE
"Allow contribution for non-verified sites" & "Allow contribution to videos" disabled after upgrade

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2246]
### Description: 

Both `Allow contribution for non-verified sites` & `Allow contribution to videos` are being disabled after upgrading from `1.4.2` --> `1.4.3`.

### Steps to Reproduce 

  1. using TF, install `1.4.2 (19.12.12.15)` and enable rewards
  2. go into the `a-c` settings and you'll notice `Allow contribution for non-verified sites` & `Allow contribution to videos` are enabled
  3. using TF, install `1.4.3 (20.1.27.28)` and go into the `a-c` settings, you'll notice that both Allow contribution for non-verified sites` & `Allow contribution to videos` are disabled without user interaction

**Actual result:** 

Brave shouldn't be disabling `Reward` settings when upgrading.

**Expected result:**

Both `Allow contribution for non-verified sites` & `Allow contribution to videos` should remain enabled.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.4.3 (20.1.27.28)`

**Device details:** 

* `iPad Mini 4` running `iOS 12.4.1` - **Reproduced**
* `iPhone 6s+` running `iOS 12.4.1` - **Reproduced**
* `iPad Air 3rd Gen` running `iOS 13.3` - **Reproduced**
* `iPhone 11` running `iOS 13.3` - **Reproduced**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @srirambv @jhreis @anthonypkeane @kylehickinson

**Comment by kylehickinson** [comment]
This is actually a regression of #2217 (issue #1674), which I don't think is supposed to be in 1.14.3

Also: There is no actual settings being changed here, its just the toggle not showing as "on" despite the underlying setting being "on"

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.20.19)
- Verified steps from issue description and no crash 
- Verified no crash when moving bookmarks from folders to favourites
-------
Verification passed on iPhone XR+ with iOS 13.4 running 1.15(20.02.20.19)
- Verified steps from issue description and no crash 
- Verified no crash when moving bookmarks from folders to favourites
-------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.20.19)
- Verified steps from issue description and no crash 
- Verified no crash when moving bookmarks from folders to favourites
-------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.20.19)
- Verified steps from issue description and no crash 
- Verified no crash when moving bookmarks from folders to favourites
-------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.20.19)
- Verified steps from issue description and no crash 
- Verified no crash when moving bookmarks from folders to favourites
-------

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.20.19)
- Verified upgrading from 1.14.2 to 1.15 doesn't reset the settings
- Verified upgrading from 1.14.3 to 1.15 doesn't reset the settings
-------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.20.19)
- Verified upgrading from 1.14.2 to 1.15 doesn't reset the settings
- Verified upgrading from 1.14.3 to 1.15 doesn't reset the settings
-------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.20.19)
- Verified upgrading from 1.14.2 to 1.15 doesn't reset the settings
- Verified upgrading from 1.14.3 to 1.15 doesn't reset the settings
-------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.20.19)
- Verified upgrading from 1.14.2 to 1.15 doesn't reset the settings
- Verified upgrading from 1.14.3 to 1.15 doesn't reset the settings
-------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.20.19)
- Verified upgrading from 1.14.2 to 1.15 doesn't reset the settings
- Verified upgrading from 1.14.3 to 1.15 doesn't reset the settings
-------
