### ISSUE TITLE
Support "Open in Place" for the Downloads folder

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#225]
Support "Open in Place" for the Downloads folder so that users can open downloaded content directly on their device

**Comment by jhreis** [comment]
@tmancey Can you please provide a bit more info about this ticket, and if it is a duplicate of #206 ?

**Comment by tmancey** [comment]
@jhreis This is not the same, for "open in place" see https://developer.apple.com/document-based-apps/ for when users download PDFs etc.

**Comment by kylehickinson** [comment]
Is this ticket still valid? Is #1467 a duplicate of this?

**Comment by tmancey** [comment]
@kylehickinson Open in place would allow users to open files directly, i.e. preview from the browser

**Comment by kylehickinson** [comment]
Is there a reason why we'd want to do this? I think the quick look preview would be good enough, and let the user open the document in the proper app outside of Brave.

**Comment by kylehickinson** [comment]
Turns out the `Open In` (from [UIDocumentInteractionController](https://developer.apple.com/documentation/uikit/uidocumentinteractioncontroller)) shows pretty much the same thing as the activity controller now… without the preview. Will probably stick with the QuickLook previewer instead

**Comment by kylehickinson** [comment]
Closing for now as we merged QuickLook previewing and closed #1467
