### ISSUE TITLE
"Claim my Reward" modal/overlay covering the entire screen and missing button

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2255]
### Description: 

The `Claim my reward` modal/overlay for ad grants doesn't match the current specification. The current version is missing the `Claim my reward` button and covers the entire screen. Because there's no button available, the only thing the user can do is press the `X` button to close the modal/overlay.

### Steps to Reproduce

  1. install `1.14.3 (20.1.28.18)` via the `Dev` TF channel
  2. skip the `Onboarding` process and go into `Settings` --> `View Rewards Debug Menu`
  3. select `Staging` and restart the browser (should close automatically)
  4. once the browser is relaunched, enable rewards via the panel (`Join Rewards`)
  5. go into `Settings` --> `View Rewards Debug Menu`
  6. restore a wallet that has an ad grant available (use the shared GDoc) and restart the browser
  7. open a new NTP and you'll get the `Brave Reward` modal that displays your ad grant

**Actual result:** 

![IMG_0006 (1)](https://user-images.githubusercontent.com/2602313/73322400-b878f200-4212-11ea-8e84-2e0ab5e569b7.PNG)

**Expected result:**

As per the specification, the modal/overlay should look as follows:

<img width="352" alt="Screen Shot 2020-01-28 at 9 09 11 PM" src="https://user-images.githubusercontent.com/2602313/73322386-b0b94d80-4212-11ea-88ba-f553363d8d4e.png">

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.14.3 (20.1.28.18)` (using the `Dev` TF channel)

**Device details:** 

* `iPhone 11` running `iOS 13.3` - **Reproduced**
* `iPad 3rd Gen` running `iOS 13.3` - **Reproduced**
* `iPhone 6s+` running `iOS 12.4.1` - **Reproduced**
* `iPad Mini 4` running `iOS 12.4.1` - **Reproduced**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @brave/legacy_qa @anthonypkeane @iccub @jhreis @jamesmudgett

**Comment by LaurenWags** [comment]
Verification passed on iPad 5th Gen with iOS 12 running 1.14.3 (20.1.29.20)
   - Verified STR from description, ensured correct modal was displayed
   - encountered and logged #2280 
![2255-ipad-ios12](https://user-images.githubusercontent.com/28145373/73402223-ce41f200-42ba-11ea-8f98-68d19a576aa1.jpeg)

Verification passed on iPad Mini with iOS 13 running 1.14.3 (20.1.29.20)
   - Verified STR from description, ensured correct modal was displayed
   - encountered and logged #2280 
![2255-ipad-ios13](https://user-images.githubusercontent.com/28145373/73402253-def26800-42ba-11ea-82e9-774c60dc99e9.jpeg)

Verification **PASSED**  on `iPhone 11` using `iOS 13.3` running `1.14.3 (20.1.29.20)`

* Went through the STR mentioned via https://github.com/brave/brave-ios/issues/2255#issue-556602028 and ensured the `Claim my grant` modal was being displayed correctly
* Reproduced #2280

![IMG_0019](https://user-images.githubusercontent.com/2602313/73404594-db151480-42bf-11ea-9f86-15edc12c0733.PNG)

![IMG_0020](https://user-images.githubusercontent.com/2602313/73404598-dd776e80-42bf-11ea-8dc9-0169f05eabe1.PNG)

Verification **PASSED**  on `iPhone 6s+` using `iOS 12.4.1` running `1.14.3 (20.1.29.20)`

* Went through the STR mentioned via https://github.com/brave/brave-ios/issues/2255#issue-556602028 and ensured the `Claim my grant` modal was being displayed correctly
* Reproduced #2280

![IMG_9998](https://user-images.githubusercontent.com/2602313/73405029-f16fa000-42c0-11ea-9d58-48c52508d169.PNG)

![IMG_9999](https://user-images.githubusercontent.com/2602313/73405049-ff252580-42c0-11ea-96ce-57d2fe11e8a5.PNG)

Verification passed on 1.14.3(20.01.29.20) on Production on iPhone SE (iOS 12.4)
![IMG_0015](https://user-images.githubusercontent.com/34715963/73407967-f5b8af00-42fa-11ea-8841-1eaa76623691.PNG)

Verification passed on 1.14.3(20.01.29.20) on iPhone 8 (IOS 13.3)
 - Verified the STR from the description
- Encountered https://github.com/brave/brave-ios/issues/2280

![IMG_0295](https://user-images.githubusercontent.com/38657976/73443932-9bacfd80-437d-11ea-887f-ffaff9b9cc91.PNG)
