### ISSUE TITLE
Brand images downloading in not supported regions.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2257]
### Description: 

Sponsored images are being downloaded/used despite being in regions that shouldn't be getting those images. Example:

* `Region: India` & `Language: English` --> downloading/using SNTP images
* `Region: Canada` & `Language: English` --> downloading/using SNTP images

@GeetaSarvadnya also reproduced this issue using `Region: India` & `Language: English` as mentioned above.

Some more context can be found via the following Slack thread:

* https://bravesoftware.slack.com/archives/CQGTGBNH1/p1580280305471800

### Steps to Reproduce

**Prerequisite:**

Ensure that you have `Region: India` `Language: English` or `Region: Canada` & `Language: English` set via the iOS settings

  1. download & launch `1.14.3 (20.1.28.18)`
  2. enable rewards/ads via the initial onboarding
  3. start cycling through SNTP and you'll notice sponsored images

**Actual result:** 

Even though the regions are set to `India` or `Canada`, SNTP images are being downloaded

**Expected result:**

Certain regions shouldn't be getting SNTP images.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* Using `1.14.3 (20.1.28.18)`

**Device details:** 

* `iPhone 11` running `iOS 13.3` - **Reproduced**
* `iPad 3rd Gen` running `iOS 13.3` - **Reproduced**
* `iPhone 6s+` running `iOS 12.4.1` - **Reproduced**
* `iPad Mini 4` running `iOS 12.4.1` - **Reproduced**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @jhreis @jsecretan @bsclifton @srirambv @anthonypkeane @Brandon-T

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 13.3` using `1.14.3 (20.1.29.20)`

* ensured that NTP SI aren't being displayed/used on a clean install when an unsupported region is used
* ensured that NTP SI aren't being displayed/used in PB tabs when an unsupported region is used
* ensured that restarting Brave several times doesn't display/use NTP SI when an unsupported region is used
* ensured that upgrading from `1.4.2 (19.12.12.17)` --> `1.14.3 (20.1.29.20)` when using an unsupported region doesn't display/use NTP SI.
* ensured that disabling/enabling `Show Sponsored Images` via `New Tab Page` settings doesn't enable NTP SI on unsupported regions.
* ensured that disabling/enabling `Show Background Images` via `New Tab Page` settings doesn't enable NTP SI on unsupported regions.
* ensure that NTP SI are being used when using a supported region on a clean install
* ensure that NTP SI are being used when using a supported region after upgrading from `1.4.2 (19.12.12.17)` --> `1.14.3 (20.1.29.20)`

Verification **PASSED** on `iPad 5th Gen` running `iOS 12` using `1.14.3 (20.1.29.20)` (Used Canada as my unsupported region)

* ensured that NTP SI aren't being displayed/used on a clean install when an unsupported region is used
* ensured that NTP SI aren't being displayed/used in PB tabs when an unsupported region is used
* ensured that restarting Brave several times doesn't display/use NTP SI when an unsupported region is used
* ensured that upgrading from `1.4.2 (19.12.12.17)` --> `1.14.3 (20.1.29.20)` when using an unsupported region doesn't display/use NTP SI.
* ensured that disabling/enabling `Show Sponsored Images` via `New Tab Page` settings doesn't enable NTP SI on unsupported regions.
* ensured that disabling/enabling `Show Background Images` via `New Tab Page` settings doesn't enable NTP SI on unsupported regions.
* ensure that NTP SI are being used when using a supported region on a clean install
* ensure that NTP SI are being used when using a supported region after upgrading from `1.4.2 (19.12.12.17)` --> `1.14.3 (20.1.29.20)`

Verification **PASSED** on `iPad Mini` running `iOS 13` using `1.14.3 (20.1.29.20)` (Used Canada as my unsupported region)

* ensured that NTP SI aren't being displayed/used on a clean install when an unsupported region is used
* ensured that NTP SI aren't being displayed/used in PB tabs when an unsupported region is used
* ensured that restarting Brave several times doesn't display/use NTP SI when an unsupported region is used
* ensured that upgrading from `1.4.2 (19.12.12.17)` --> `1.14.3 (20.1.29.20)` when using an unsupported region doesn't display/use NTP SI.
* ensured that disabling/enabling `Show Sponsored Images` via `New Tab Page` settings doesn't enable NTP SI on unsupported regions.
* ensured that disabling/enabling `Show Background Images` via `New Tab Page` settings doesn't enable NTP SI on unsupported regions.
* ensure that NTP SI are being used when using a supported region on a clean install
* ensure that NTP SI are being used when using a supported region after upgrading from `1.4.2 (19.12.12.17)` --> `1.14.3 (20.1.29.20)`


Verification **passed** on 1.14.3(20.01.29.20) on Production on iPhone SE (iOS 12.4). (Used Poland as my unsupported region)
* ensured that NTP SI aren't being displayed/used on a clean install when an unsupported region is used
* ensured that NTP SI aren't being displayed/used in PB tabs when an unsupported region is used
* ensured that restarting Brave several times doesn't display/use NTP SI when an unsupported region is used
* ensured that upgrading from `1.4.2 (19.12.12.17)` --> `1.14.3 (20.1.29.20)` when using an unsupported region doesn't display/use NTP SI.
* ensured that disabling/enabling `Show Sponsored Images` via `New Tab Page` settings doesn't enable NTP SI on unsupported regions.
* ensured that disabling/enabling `Show Background Images` via `New Tab Page` settings doesn't enable NTP SI on unsupported regions.
* ensure that NTP SI are being used when using a supported region on a clean install
* ensure that NTP SI are being used when using a supported region after upgrading from `1.4.2 (19.12.12.17)` --> `1.14.3 (20.1.29.20)`

Verification **PASSED** on `iPhone 8` running `iOS 13.3` using `1.14.3 (20.1.29.20)`

* ensured that NTP SI aren't being displayed/used on a clean install when an unsupported region is used
* ensured that NTP SI aren't being displayed/used in PB tabs when an unsupported region is used
* ensured that restarting Brave several times doesn't display/use NTP SI when an unsupported region is used
* ensured that upgrading from `1.4.2 (19.12.12.17)` --> `1.14.3 (20.1.29.20)` when using an unsupported region doesn't display/use NTP SI.
* ensured that disabling/enabling `Show Sponsored Images` via `New Tab Page` settings doesn't enable NTP SI on unsupported regions.
* ensured that disabling/enabling `Show Background Images` via `New Tab Page` settings doesn't enable NTP SI on unsupported regions.
* ensure that NTP SI are being used when using a supported region on a clean install
* ensure that NTP SI are being used when using a supported region after upgrading from `1.4.2 (19.12.12.17)` --> `1.14.3 (20.1.29.20)`
