### ISSUE TITLE
NTP banner will not show if tab changed before the banner appears

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2264]
### Steps to Reproduce 
  1. Clean install, skip onboarding
  2. Open sponsored tab, then quickly close it or switch back
  3. Open another sponsored tab

**Actual result:** 
The banner will not show

**Expected result:**
Should show

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by LaurenWags** [comment]
Verification passed on iPad 5th Gen with iOS 12 running 1.14.3 (20.1.29.20)
   - Verified STR from description

Verification passed on iPad Mini with iOS 13 running 1.14.3 (20.1.29.20)
   - Verified STR from description

Verification **PASSED** on `iPhone 11` using `iOS 13.3` running `1.14.3 (20.1.29.20)`

* Verified STR mentioned under https://github.com/brave/brave-ios/issues/2264#issue-556743516 worked as expected

Verification **PASSED** on `iPhone 6s+` using `iOS 12.4.1` running `1.14.3 (20.1.29.20)`

* Verified STR mentioned under https://github.com/brave/brave-ios/issues/2264#issue-556743516 worked as expected

Verification passed on 1.14.3(20.01.29.20) on Production on iPhone SE (iOS 12.4)
   - Verified STR from description

Verification passed on 1.14.3(20.01.29.20) on Production on iPhone 8 (iOS 13.3)
   - Verified STR from description
