### ISSUE TITLE
Hard to close translucent NTP banner by 'X' button

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2266]
### Steps to Reproduce 
  1. Clean install, skip onboarding
  2. Show SNTP, wait for banner to show up
  3. Try to close it tapping on left side of 'X' button

**Actual result:** 
Doesn't work

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by LaurenWags** [comment]
Verification passed on iPad 5th Gen with iOS 12 running 1.14.3 (20.1.29.20)
   - Verified STR from description

Verification passed on iPad Mini with iOS 13 running 1.14.3 (20.1.29.20)
   - Verified STR from description

Verification passed on 1.14.3(20.01.29.20) on Production on iPhone SE (iOS 12.4)
   - Verified STR from description

Verification **PASSED** on `iPhone 11` using `iOS 13.3` running `1.14.3(20.01.29.20)`
* Verified STR mentioned via https://github.com/brave/brave-ios/issues/2266#issue-556766547

Verification **PASSED** on `iPad Mini 4` using `iOS 12.4.1` running `1.14.3(20.01.29.20)`
* Verified STR mentioned via https://github.com/brave/brave-ios/issues/2266#issue-556766547

Verification **PASSED** on `iPad Air 3rd Gen` using `iOS 13.3` running `1.14.3(20.01.29.20)`
* Verified STR mentioned via https://github.com/brave/brave-ios/issues/2266#issue-556766547

Verification **PASSED** on `iPhone 8` using `iOS 13.3` running `1.14.3(20.01.29.20)`
* Verified STR mentioned via https://github.com/brave/brave-ios/issues/2266#issue-55676654
