### ISSUE TITLE
SNTP not showing when disabled, then enabled on app launch

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2268]
### Description: 
No SNTP image is shown when toggle the `Show sponsored images` switch 

### Steps to Reproduce 
  1. Clean profile 1.14.3
  2. Enable rewards through on-boarding
  3. Open SNTP saw sponsored image once 
  4. Navigate to settings->New Tab page->Turn off `Show sponsored images`
  5. Remove the app from memory
  6. Relaunch the app and navigate to settings->New Tab page->Turn on `show sponsored images`
Actual: No sponsored images are shown.

**Actual result:** 
No SNTP image is shown when toggle the `Show sponsored images` switch to ON

**Expected result:**
SNTP images should be shown when `Show sponsored images`switch is ON

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 

1.14.3 (20.01.28.18)
**Device details:** 
iPhone 8 - IOS 13.3

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @brave/legacy_qa @jhreis @davidtemkin @anthonypkeane @jamesmudgett

**Comment by LaurenWags** [comment]
Verification passed on iPad 5th Gen with iOS 12 running 1.14.3 (20.1.29.20)
   - Verified STR from description

Verification passed on iPad Mini with iOS 13 running 1.14.3 (20.1.29.20)
   - Verified STR from description

Verification passed on 1.14.3(20.01.29.20) on Production on iPhone SE (iOS 12.4)
  - Verified STR from description

Verification **PASSED** on `iPhone 6s` using `iOS 13.3.1` running `1.14.3(20.01.29.20)` on production:
  - Verified STR from description

Verification **PASSED** on `iPhone 8` using `iOS 13.3` running `1.14.3(20.01.29.20)` on production:
  - Verified STR from description
