### ISSUE TITLE
When Ads, AC, Brave rewards switches are turned OFF explicitly, enable rewards from SNTP enables all switches instead of Brave Reards only 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#2271]
### Description: 

When Ads, AC, Brave rewards switches are turned OFF explicitly, enable rewards from SNTP enables all switches instead of Brave Reards only 
### Steps to Reproduce 
  1. Clean profile 1.14.3
  2. Enable rewards through the onboarding flow
  3. Turn OFF Ads and AC switches and then turn off Brave Rewards switch in brave://rewards page
  4. Open sponsored new tab and click on `Learn more` and click on `Turn on Rewards`.
  5. Turn on rewards from SNTP enables Brave rewards, Ads and AC switches instead of Brave Rewards only.

Note: the same scenario in Desktop, enables only Brave Rewards switch (Ads and AC switches are still in the off state)

**Actual result:** 
Turn on rewards from SNTP enables Brave rewards, Ads and AC switches instead of Brave Rewards only.

**Expected result:**
Should turn ON only Brave Rewards switch

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Always
**Brave Version:** 
1.14.3 (20.01.28.18)

**Device details:** 
iPhone 8 - IOS 13.3

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @brave/legacy_qa @jhreis @davidtemkin @anthonypkeane @jamesmudgett

**Comment by LaurenWags** [comment]
Verification passed on iPad 5th Gen with iOS 12 running 1.14.3 (20.1.29.20)
   - Verified STR from description

Verification passed on iPad Mini with iOS 13 running 1.14.3 (20.1.29.20)
   - Verified STR from description

Verification passed on 1.14.3(20.01.29.20) on Production on iPhone SE (iOS 12.4)
   - Verified STR from description

Verification **PASSED** on `iPhone 6s` using `iOS 13.3.1` running `1.14.3(20.01.29.20)` on `production`:

* Reproduced the original issue using the STR from https://github.com/brave/brave-ios/issues/2271#issue-556847162 with `1.14.3 (20.1.28.18)`
* Verified using the STR mentioned via https://github.com/brave/brave-ios/issues/2271#issue-556847162

Verification **PASSED** on `iPhone 8` using `iOS 13.3` running `1.14.3(20.01.29.20)` on `production`:
 - Verified STR from description
