### ISSUE TITLE
 `you are getting paid for this image...` notification isn't shown in an upgraded profile for SNTP

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#2273]
### Description: 
 `you are getting paid for this image...` notification isn't shown in an upgraded profile for SNTP

### Steps to Reproduce 
  1. Clean profile 1.13 (19.11.6.18)
  2. Enable rewards through the onboarding flow
  3. Disable Ads 
  4. Upgrade to 1.14.3
  5. Turn on Ads by clicking `Turn on Brave Ads` notification which is shown on NTP
  6. Open SNTP - 1st SNTP is opened but there is no `you are getting paid for this image` notification
 

**Actual result:** 
 `you are getting paid for this image...` notification isn't shown in an upgraded profile for SNTP

**Expected result:**
Notification should be shown in an upgraded profile

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 

1.14.3 (20.01.28.18)
**Device details:** 
iPhone 8 - IOS 13.3

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @brave/legacy_qa @jhreis @davidtemkin @anthonypkeane @jamesmudgett

**Comment by iccub** [comment]
There should be only 1 SNTP notification in this case

It resets only if you enable or disable Rewards/Ads from the Rewards panel. It doesn't trigger when ads or rewards are enabled from NTP notificaiton

**Comment by GeetaSarvadnya** [comment]
@iccub  I am not seeing the notification for the 1st SNTP

**Comment by iccub** [comment]
`Turn on Ads by clicking Turn on Brave Ads notification which is shown on NTP`
isn't this the first notification @GeetaSarvadnya?

**Comment by GeetaSarvadnya** [comment]
@iccub ofcourse, step 5 notification is the 1st notification but I am checking notification only for SNTP. Are we not supposed to get `you are getting paid for this image...` notification on 1st SNTP? in the above scenario

**Comment by iccub** [comment]
@GeetaSarvadnya  no, you get only one notification, no matter what state are you in.
On current build there is a bug that two notifications can show, see this ticket https://github.com/brave/brave-ios/issues/2260

So it should be one notification, no matter what rewards state or image type.
This resets only when reseting ads/rewards via rewards panel

**Comment by GeetaSarvadnya** [comment]
@iccub Please see the difference between clean and upgraded profiles:

**Clean Profile**
1. Clean profile 1.14.3
2. Enable rewards through the onboarding flow
3. Disable Ads
4. Open a 1st SNTP - `Get paid to see this background-image`  notification is shown with `Turn on Brave Ads`

**Upgraded Profile**

1. Clean profile 1.13 (19.11.6.18)
2. Enable rewards through the onboarding flow
3. Disable Ads
4. Upgrade to 1.14.3
5. `You can support web creators with tokens` notification is shown on NTP with `Turn on Brave Ads`
6. Turn on Ads by clicking `Turn on Brave Ads` notification
7. Open SNTP - 1st SNTP is opened but there is no `Get paid to see this background-image` notification

**Comment by mandar-brave** [comment]
@Miyayes the notification should show up one time in all cases where applicable, especially if Ads are OFF (which is the key state vs BR). This is not a blocker or a P1 considering user would get paid as they switched on Ads, and we will ensure the learn more and community post will make it further clear. Do solve for it when you can get to this issue in the next cycle.

Since the spec is frozen, let's keep a track of this in git for the moment.

cc @jhreis @kjozwiak
