### ISSUE TITLE
Total attention % rate exceeds 100 when min page time is changed to 1 minute

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#2282]
### Description: 
Total attention % rate exceeds 100 when min page time is changed to 1 minute
### Steps to Reproduce 
  1. Clean profile 1.14.3
  2. Enable rewards through the onboarding flow
  3. Open any YT video and spend 1 min 
  4. Open Wikipedia.org and spend 10 secs
  5. Open Twitter.com and spend 8 secs
  6. Navigate to AC advanced settings and change minimum page time settings to 1 min
  7. AC sites attention % rate exceeds more than 100 when min page time is changed to 1 minute

Note: the same scenario on desktop works fine.

**Actual result:** 
Total attention % rate exceeds 100 when min page time is changed to 1 minute

![image](https://user-images.githubusercontent.com/38657976/73428757-fcc5d880-435f-11ea-9c6b-5bb35149ee4a.png)

**Expected result:**
Total attention % rate should not exceed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Always
**Brave Version:** 
1.14.3, Issue is reproducible even in playstore version

**Device details:** 
iPhone 8 - IOS 13.3

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @brave/legacy_qa @jhreis @anthonypkeane @jamesmudgett

**Comment by kylehickinson** [comment]
I suspect this has less to do with the percentages and more to do with the fact that YouTube.com shouldn't be tracked if you're on a YouTube channel.

**Comment by NejcZdovc** [comment]
@GeetaSarvadnya can you please re-test on the latest version?

**Comment by kylehickinson** [comment]
Closed as this feature is no longer supported in new Rewards on Brave iOS
