### ISSUE TITLE
Add New Haptic Feedback Behavior

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2283]
Add haptic feedback:

- [x] Selecting sponsored image logo
- [x] Selecting image credit button on background images.
- [x] Switching tabs

Internal Chats: 
[one](https://bravesoftware.slack.com/archives/C06UXF3KJ/p1580333633059600) [two](https://bravesoftware.slack.com/archives/C06UXF3KJ/p1580333661060200)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 13` using `1.15 (20.02.20.19)`. Went through the following verifications:

* ensured that tapping on the credits name on the NTP provided haptic feedback
* ensured the tapping the NTP SI logo provided haptic feedback
* ensured that pressing the `+` button provided haptic feedback (once the new tab was created)
* ensured that switching between the tabs via the `Tab Manager` provided haptic feedback

Granted, the vibration is pretty light but seems like it's working on my device. CCing @srirambv.

-------
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.20.19)
- Verified tapping on photo credit has haptic feedback
- Verified tapping on SI logo has haptic feedback
- Verified closing a tab has haptic feedback
- Verified pressing `+` for new tab has haptic feedback
- Verified swipe navigation to switch tabs on bottom  bar has haptic feedback
- Verified haptic feedback is noticeable on both normal and private tab
-------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.20.19)
- Verified tapping on photo credit has haptic feedback
- Verified tapping on SI logo has haptic feedback
- Verified closing a tab has haptic feedback
- Verified pressing `+` for new tab has haptic feedback
- Verified swipe navigation to switch tabs on bottom  bar has haptic feedback
- Verified haptic feedback is noticeable on both normal and private tab

**Comment by kjozwiak** [comment]
@anthonypkeane @iccub I'm getting haptic feedback when closing tabs via the toolbar. Expected?

**Comment by jhreis** [comment]
@kjozwiak Yes, this is expected. Anytime a tab switches (open, click, close) feedback happens. If you feel any of these is buggy or wrong, we can adjust.
