### ISSUE TITLE
NTP SI not updating when app is in foreground for long time.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2285]
### Steps to Reproduce 
  1. Hard to test, needs coordination with server resources.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
Verification **PASSED** using `1.14.3 (20.1.31.17)` on several iOS devices:

* `iPhone 6s+` running `iOS 12`
* `iPhone 6s` running `iOS 13`
* `iPad Air 3rd Gen` running `iOS 13`
* `iPad Mini 4` running `iOS 12`
* `iPad 5th Gen` running `iOS 12`
* `iPad Mini` running `iOS 13`
* `iPhone XR` running `iOS 13`

Went through the following cases and ensured that images/assets were being replaced while Brave was running in the foreground:

**`Test Case #1`**

* installed Brave and ensured that images, logo's and links from `campaign 1` were being used
* pushed assets from `campaign 2` and ensured that images, links and logo's were replaced
* re-installed Brave and ensured assets from `campaign 2` were being used on clean installs

**`Test Case #2`**

* installed Brave and ensured that images, logo's and links from `campaign 2` were being used
* pushed assets from `campaign 1` and ensured that images, links and logo's were replaced
* replaced the assets with an empty `photo.json` and ensured NTP SI weren't being displayed
* re-installed Brave and ensured that there weren't any NTP SI campaigns being used

**`Test Case #3`**

* installed Brave and ensured that images, logo's and links from `campaign 1` were being used
* setup the the server side to send a `403` and ensured it didn't cause any issues client side

CCing @LaurenWags @srirambv
