### ISSUE TITLE
NTP SI logo's are not being replaced when pushing new assets to replace older assets

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2287]
### Description: 

When pushing new NTP SI assets to replace assets that are currently live, the logo isn't being replaced. However, the images and links are being replaced.

When pushing new assets, we should be replacing the following:

* images
* logo(s)
* links

### Steps to Reproduce 

There's really no STR that QA can run through as we need help from someone with access to the back-end. Quick summary of what needs to be completed:

* ensure that current assets are being replaced with newer assets (images/logo/links)
* ensure sending a blank `photo.json` removes the current NTP SI assets without any issues

**Actual result:** 

When pushing new NTP SI assets, the logo's are not being replaced.

**Expected result:**

When pushing new NTP SI assets, it should replace the old images, logos and links.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the scenario mentioned above.

**Brave Version:** 

* `1.14.3 (20.1.30.18)`

**Device details:** 

* `iPhone 6s+` running `iOS 12.4.1` - *Reproduced*
* `iPhone 6s` running `iOS 13.3.1` - *Reproduced*
* `iPad Mini 4` running `iOS 12.4.1` - *Reproduced*
* `iPad Air 3rd Gen` running `iOS 13.3.1` - *Reproduced*

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @bsclifton @jhreis @LaurenWags @srirambv @anthonypkeane @Brandon-T

**Comment by LaurenWags** [comment]
Reproduced using:
- iPad 5th Gen running iOS12
- iPad Mini running iOS13

**Comment by kjozwiak** [comment]
Verification **PASSED** using `1.14.3 (20.1.31.17)` on several iOS devices:

* `iPhone 6s+` running `iOS 12`
* `iPhone 6s` running `iOS 13`
* `iPad Air 3rd Gen` running `iOS 13`
* `iPad Mini 4` running `iOS 12`
* `iPad 5th Gen` running `iOS 12`
* `iPad Mini` running `iOS 13`
* `iPhone XR` running `iOS 13`

Went through the following cases and ensured that images/assets were being replaced while Brave was running in the foreground:

**`Test Case #1`**

* installed Brave and ensured that images, logo's and links from `campaign 1` were being used
* pushed assets from `campaign 2` and ensured that images, links and logo's were replaced
* re-installed Brave and ensured assets from `campaign 2` were being used on clean installs

**`Test Case #2`**

* installed Brave and ensured that images, logo's and links from `campaign 2` were being used
* pushed assets from `campaign 1` and ensured that images, links and logo's were replaced
* replaced the assets with an empty `photo.json` and ensured NTP SI weren't being displayed
* re-installed Brave and ensured that there weren't any NTP SI campaigns being used

**`Test Case #3`**

* installed Brave and ensured that images, logo's and links from `campaign 1` were being used
* setup the the server side to send a `403` and ensured it didn't cause any issues client side

CCing @LaurenWags @srirambv
