### ISSUE TITLE
brave crashes in some cases when retrieving NTP SI assets from the back-end

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2289]
### Description: 

Seems like we have a crash in Brave that occurs when we attempt to retrieve NTP SI assets but none exists in the s3 bucket. Currently just a theory but this crash usually happens when we're switching assets in the s3 bucket.

@mandar-brave @Brandon-T @LaurenWags and myself ran into this crash several times when we were debugging https://github.com/brave/brave-ios/issues/2287.

### Steps to Reproduce 

There really isn't any STR that QA can follow but once this has been addressed, we'll work with @jhreis @bsclifton and @Brandon-T to go through this together to make sure it's fixed before signing off.

**Actual result:** 

Brave crashing in some cases. It usually occurs when we start updating/switching assets on the s3 NTP SI server.

**Expected result:**

Brave shouldn't be crashing.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Honestly not 100% sure but we got the server into a state where Brave started crashing for everyone QAing the issue 100% of the time.

**Brave Version:** 

* `1.14.3 (20.1.30.18)`

**Device details:** 

* `iPhone 6s+` running `iOS 12.4.1` - **Reproduced**
* `iPhone 6s` running `iOS 13.3.1` - **Reproduced**
* `iPad Mini 4` running `iOS 12.4.1` - **Reproduced**
* `iPad Air 3rd Gen` running `iOS 13.3.1` - **Reproduced**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @bsclifton @jhreis @LaurenWags @srirambv @anthonypkeane @Brandon-T

**Comment by kjozwiak** [comment]
Going to move this into the next milestone. We think that https://github.com/brave/brave-ios/issues/2287 might have addressed the crashes we were seeing in earlier testing. However, when we were going through `1.14.3 (20.13.1.17)`,  @LaurenWags ran into one crash. We're not sure if it's related to this or a completely unrelated crash.

We should keep an eye on crash rates/community once `1.14.3 (20.13.1.17)` is pushed out.

**Comment by jhreis** [comment]
Closing this now due to length of time, we can re-open / refile if needed.
