### ISSUE TITLE
Same SI is repeated when browser is relaunched

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2292]
### Description: 
Same SI is repeated when the browser is relaunched

### Steps to Reproduce 
  1. view the first SI 
  2. quit and relaunch app
  3. same SI is shown again for the first time

**Actual result:** 
Same SI is repeated when browser is relaunched

**Expected result:**
Should cycel through the SI's for each launch

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14.3

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
https://github.com/brave/browser-android-tabs/issues/2500 Android issue
cc: @anthonypkeane @mandar-brave

**Comment by jhreis** [comment]
This is actually expected behavior per @mandar-brave
