### ISSUE TITLE
Update Ben Karpinski's photo attribution link from Fall 2019 wallpapers

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-ios#2295]
### Description: 
Currently, Ben Karpinski's photo attribution link is set as [www.benkarpinski.com/landscapes](url). He has requested that we update it to [http://bklandscapes.com/](url). His image is included in the Fall 2019 batch of new wallpapers.

![Screen Shot 2020-01-31 at 11 34 54 AM](https://user-images.githubusercontent.com/2388823/73569918-3cec9000-4420-11ea-946f-1223654de42f.png)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified landing page links to`http://bklandscapes.com/`
-------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified landing page links to`http://bklandscapes.com/`
-------
Verification passed on iPhone 6 with iOS 12.4.4 running 1.15(20.02.12.10)
- Verified landing page links to`http://bklandscapes.com/`
-------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.12.10)
- Verified landing page links to`http://bklandscapes.com/`
-------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.12.10)
- Verified landing page links to`http://bklandscapes.com/`
-------
