### ISSUE TITLE
Disable Bookmarklets URL bar entirely

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#2297]
### Description: 
- Disable bookmarklets due to security issue
- Internal description due to nature of bug discovered
https://bravesoftware.slack.com/archives/G2KN13Z8C/p1580533016008700?thread_ts=1580526417.004800&cid=G2KN13Z8C

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by diracdeltas** [comment]
@Brandon-T @kjozwiak i would say include this in the release notes (can just say `Disable bookmarklets due to security issue`)

**Comment by kjozwiak** [comment]
QA was completed and results were posted via https://bravesoftware.slack.com/archives/C06UXF3KJ/p1580543328128500?thread_ts=1580529851.084000&cid=C06UXF3KJ.
