### ISSUE TITLE
Investigate Privileged Requests

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#2298]
### Description: 

There is a potential flaw in PrivilegedRequests discovered via Bookmarklets. This needs to be investigated further before we can ever re-enable (if at all), bookmarklets from the URL bar or do anything at all related to local assets as all requests for those are Privileged. This includes serving local pages.

https://bravesoftware.slack.com/archives/G2KN13Z8C/p1580533016008700?thread_ts=1580526417.004800&cid=G2KN13Z8C

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
@Brandon-T can you please inline any necessary info from the private thread?
