### ISSUE TITLE
Add Rewards panel icon to "Open Brave Rewards Settings" button (Follow up to #2277)

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2300]
Refs #2277, the rewards panel icon (BAT logo) should be added next to button in settings that opens Brave Rewards settings

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.18.17)
- Verified `Open Brave Rewards Settings` under Settings->Rewards opens rewards panel
![image](https://user-images.githubusercontent.com/17010094/74920140-ad6c4880-53f1-11ea-9722-c9f807e5631a.png)

-----
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.18.17)
- Verified `Open Brave Rewards Settings` under Settings->Rewards opens rewards panel
![image](https://user-images.githubusercontent.com/17010094/74920151-b2c99300-53f1-11ea-84d2-e37ef3ead61e.png)

-----
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified `Open Brave Rewards Settings` under Settings->Rewards opens rewards panel
![image](https://user-images.githubusercontent.com/17010094/74920212-cf65cb00-53f1-11ea-9241-f1f08525c77e.png)

-----
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified `Open Brave Rewards Settings` under Settings->Rewards opens rewards panel
![image](https://user-images.githubusercontent.com/17010094/74920166-b826dd80-53f1-11ea-888e-744bbaae7ed1.png)

-----
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.18.17)
- Verified `Open Brave Rewards Settings` under Settings->Rewards opens rewards panel
![image](https://user-images.githubusercontent.com/17010094/74920169-bc52fb00-53f1-11ea-81d6-b636713c0b06.png)

-----

**Comment by srirambv** [comment]
Verification passed for translated strings on 
- iPhone 7+
![image](https://user-images.githubusercontent.com/17010094/75007531-70f52700-549b-11ea-95df-db7905d4d235.png)

- iPhone XR
![image](https://user-images.githubusercontent.com/17010094/75007521-69358280-549b-11ea-9573-87762549ac07.png)

- iPhone 6
![image](https://user-images.githubusercontent.com/17010094/75007506-620e7480-549b-11ea-9f19-4825c9a3dfc6.png)

- iPad Pro
![image](https://user-images.githubusercontent.com/17010094/75007506-620e7480-549b-11ea-9f19-4825c9a3dfc6.png)

- iPad Pro (iOS12)
![image](https://user-images.githubusercontent.com/17010094/75007514-663a9200-549b-11ea-9281-78089b7b8150.png)
