### ISSUE TITLE
Colors for some websites are inverted

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2304]
### Description: 
See https://community.brave.com/t/webpage-colors-are-inverted/100826/4
for STR and screenshots

### Steps to Reproduce 
  1. Hard to reproduce, doesn't happen often

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by nbubna** [comment]
This is currently happening for me on *all* pages. MacOS 10.15.7, Brave Version 1.23.71 Chromium: 90.0.4430.72 (Official Build) (x86_64)

Every color. Every image. Every site. Trying to move away from Chrome. I'm a new user. This is... off putting.

**Comment by jhmblvd** [comment]
This is still happening. Iphone 11 brave browser in night mode.

**Comment by jhaskell01** [comment]
Still occuring... iphone 13 pro... Brave 1.47.186
Is this ever going to be resolved??

**Comment by TXZ-COSMIC** [comment]
Well I’m still getting this problem all most 2 years later. I guess this was dropped?
