### ISSUE TITLE
Cannot perform swipe up gesture on NTP to dismiss OSK with Auto Open Keyboard setting enabled.

### ISSUE THREAD

**Issue by aungpyaekyaw** [brave/brave-ios#2321]
### Description: 
Should be able  to perform swipe up gesture to dismiss keyboard. Swipe up gesture is not working.

### Steps to Reproduce 
  1. Install 1.14.3
  2. Enable Auto Open Keyboard in NTP setting
  3. Open new tab
  4. Swipe up to dismiss the keyboard. Cannot perform swipe up gesture.

**Actual result:** 
Swipe up gesture is not working.

**Expected result:**
Swipe up gesture should be working.

**Reproduces how often:** 
Easily reproduced

**Brave Version:** 
Version 1.14.3 (20.02.01.06)

**Device details:** 
Device iPhone 8 (iOS 13.3.1)

### Additional Information
May be related with #2073

**Comment by kylehickinson** [comment]
Closed since this preference will no longer exist

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.18(20.06.09.18)
- Verified no setting for `Auto open keyboard` setting under NewTab
![image](https://user-images.githubusercontent.com/17010094/84263774-b702f300-ab3d-11ea-9e44-3b561efe6172.png)
