### ISSUE TITLE
Enabling Sites To Determine Brave

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2323]
### Description: 

Generate a script that is injected into every page that allows them to see Brave:

```
navigator.getUserAgent = function () {
  return {
    "brand": {
      "brand": "Brave"
    }
  }
}
```

cc @snyderp

**Comment by kjozwiak** [comment]
@jhreis assuming this already went through a security review as it's closed/merged. I'm going to remove `needs security review`. Please re-added if that's not the case.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 13.3.1` using `1.15 (20.03.04.18)`:

* Verified the STR outlined under https://github.com/brave/brave-ios/pull/2374

<img width="506" alt="Screen Shot 2020-03-04 at 10 49 22 PM" src="https://user-images.githubusercontent.com/2602313/75946191-67d86280-5e6a-11ea-91b8-9a60b67d96e5.png">

Verification **PASSED** on `iPad Air 3rd Gen` running `iOS 13.3.1` using `1.15 (20.03.04.18)`:

* Verified the STR outlined under https://github.com/brave/brave-ios/pull/2374

<img width="781" alt="Screen Shot 2020-03-04 at 10 56 05 PM" src="https://user-images.githubusercontent.com/2602313/75946529-5a6fa800-5e6b-11ea-87a4-2467e7e8a024.png">

Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.15 (20.03.04.18)`

* Verified the STR outlined under https://github.com/brave/brave-ios/pull/2374

<img width="781" alt="Screen Shot 2020-03-04 at 11 01 37 PM" src="https://user-images.githubusercontent.com/2602313/75946804-21840300-5e6c-11ea-8761-79d6114a7f64.png">

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.15 (20.03.04.18)`

* Verified the STR outlined under https://github.com/brave/brave-ios/pull/2374

<img width="586" alt="Screen Shot 2020-03-04 at 11 04 35 PM" src="https://user-images.githubusercontent.com/2602313/75946961-a1aa6880-5e6c-11ea-8828-408efe2f4e6e.png">
