### ISSUE TITLE
Implement Custom Homepage

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2324]
### Description: 

Please Implement Custom Homepage

Please search G-Drive for "Custom Homepage" for the spec

**Comment by GeetaSarvadnya** [comment]
Verification is in progress

- Verified the test plan from https://bravesoftware.slack.com/archives/GAA4017R7/p1588765690060600
**Clean Install:**
- SR images are shown in all the tabs
- SR component is downloaded successfully
- Ref code is shown as expected
- QR code works fine and able to share it
https://drive.google.com/open?id=1YVnjCqlR8BZl3wvarG75B91kc5_drRXD

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.16(20.05.04.12)

**CHP Clean Install**
- Verified SR images is shown on all tabs
- Verified SR image is shown on Private tabs
- Verified QR code is shown on both normal and private tabs
- Verified QR code scans correctly and shows the correct link
- Verified QR code can be shared 
- Verified changing theme via control centre doesn't cause any issue 
- Verified disabling background disables SR images
- Verified able to switch between SR/SI/Default images via settings without restart
- Verified setting to SR works on both normal and private tabs
- Verified SR promo code is shown in logs correctly 

**Clean Install**
- Verified clean install works fine and no SR images are shown 
- Verified  SI images are shown for supported regions
- Verified SI images are not shown for non-supported regions and only shows default images
- Verified no promo code is shown in logs

**Upgrade Install**
- Verified upgrading from the previous install CHP images are not shown and doesn't show as an option in background images 

**Clean Install using Promo Code**
- Verified no CHP images option shown under NTP Background images
- Verified SI images are shown for supported regions
- Verified SI images are not shown for non-supported regions and only shows default images
- Verified correct `promoCode` is shown in logs

**Upgrade Install using Promo Code**
- Verified upgrading from promoCode install, value is retained and CHP images are not shown 

-----

Verification passed on iPad mini with iOS 13 running 1.16(20.05.04.12)

* Verified the test cases listed above:
   * CHP Clean Install - **PASSED**
   * Clean Install - **PASSED**
   * Upgrade Install - **PASSED**
   * Clean Install using Promo Code - **PASSED**
   * Upgrade Install using Promo Code - **PASSED**

-----

Verification passed on iPad Pro with iOS 12.4.5 running 1.16(20.05.07.15)


**CHP Clean Install**
- Verified SR images is shown on all tabs
- Verified SR image is shown on Private tabs
- Verified QR code is shown on both normal and private tabs
- Verified QR code scans correctly and shows the correct link
- Verified QR code can be shared 
- Verified disabling background disables SR images
- Verified able to switch between SR/SI/Default images via settings without restart
- Verified setting to SR works on both normal and private tabs
- Verified SR promo code is shown in logs correctly 

**Clean Install**
- Verified clean install works fine and no SR images are shown 
- Verified SI images are shown for supported regions
- Verified SI images are not shown for non-supported regions and only shows default images
- Verified no promo code is shown in logs

**Upgrade Install**
- Verified upgrading from the previous install CHP images are not shown and doesn't show as an option in background images 

**Clean Install using Promo Code**
- Verified no CHP images option shown under NTP Background images
- Verified SI images are shown for supported regions
- Verified SI images are not shown for non-supported regions and only shows default images
- Verified correct `promoCode` is shown in logs

**Upgrade Install using Promo Code**
- Verified upgrading from promoCode install, value is retained and CHP images are not shown 

-----

Verification passed on iPad mini with iOS 13 running 1.16(20.05.04.12)

* Verified the test cases listed above:
   * CHP Clean Install - **PASSED**
   * Clean Install - **PASSED**
   * Upgrade Install - **PASSED**
   * Clean Install using Promo Code - **PASSED**
   * Upgrade Install using Promo Code - **PASSED**

-----

Verification passed on iPhone 6 with iOS 12.4.5 running 1.16(20.05.07.15)


**CHP Clean Install**
- Verified SR images is shown on all tabs
- Verified SR image is shown on Private tabs
- Verified QR code is shown on both normal and private tabs
- Verified QR code scans correctly and shows the correct link
- Verified QR code can be shared 
- Verified disabling background disables SR images
- Verified able to switch between SR/SI/Default images via settings without restart
- Verified setting to SR works on both normal and private tabs
- Verified SR promo code is shown in logs correctly 

**Clean Install**
- Verified clean install works fine and no SR images are shown 
- Verified SI images are shown for supported regions
- Verified SI images are not shown for non-supported regions and only shows default images
- Verified no promo code is shown in logs

**Upgrade Install**
- Verified upgrading from the previous install CHP images are not shown and doesn't show as an option in background images 

**Clean Install using Promo Code**
- Verified no CHP images option shown under NTP Background images
- Verified SI images are shown for supported regions
- Verified SI images are not shown for non-supported regions and only shows default images
- Verified correct `promoCode` is shown in logs

**Upgrade Install using Promo Code**
- Verified upgrading from promoCode install, value is retained and CHP images are not shown 

-----
Verification passed on iPhone 8 with iOS 13.3.1 running 1.16(20.05.07.16)
Screenshots are attached in: https://drive.google.com/open?id=1bbBqaLlNQ2THBx8tlrAi-vcTXZmuiImZ

**CHP Clean Install**
- Verified SR images is shown on all tabs
- Verified SR image is shown on Private tabs
- Verified QR code is shown on both normal and private tabs
- Verified QR code scans correctly and shows the correct link
- Verified QR code can be shared 
- Verified changing theme via control centre doesn't cause any issue 
- Verified disabling background disables SR images
- Verified able to switch between SR/SI/Default images via settings without restart
- Verified setting to SR works on both normal and private tabs
- Verified SR promo code is shown in logs correctly 

**Clean Install**
- Verified clean install works fine and no SR images are shown 
- Verified  SI images are shown for supported regions
- Verified SI images are not shown for non-supported regions and only shows default images
- Verified no promo code is shown in logs

**Upgrade Install**
- Verified upgrading from the previous install CHP images are not shown and doesn't show as an option in background images 

**Clean Install using Promo Code**
- Verified no CHP images option shown under NTP Background images
- Verified SI images are shown for supported regions
- Verified SI images are not shown for non-supported regions and only shows default images (Tested for ads not supported region `Latvia`)
- Verified correct `promoCode` is shown in logs (used Dev build to test the logs)

**Upgrade Install using Promo Code**
- Verified upgrading from promoCode install, value is retained and CHP images are not shown
