### ISSUE TITLE
NTP SI - Images not showing after disabled and enabled

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2325]
### Description: 
NTP SI are not shown if a user turns off SI in settings and then enables SI again.

### Steps to Reproduce 
  1. Go to settings and turn off SI
  2. Close settings
  3. Open settings and enable SI

**Actual result:** 
SI are not shown again

**Expected result:**
SI should be shown

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easy

**Brave Version:** 
1.14.3

**Comment by iccub** [comment]
This seems to be broken only when app is running, when relaunched it shows correctly again

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.18.17)
- Verified disabling SI via learn more and enabling the setting still shows SI in 2/4/4 cycle
- Verified toggle SI setting to off and then on still shows SI in the 2/4/4 cycle
------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified disabling SI via learn more and enabling the setting still shows SI in 2/4/4 cycle
- Verified toggle SI setting to off and then on still shows SI in the 2/4/4 cycle
------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.18.17)
- Verified disabling SI via learn more and enabling the setting still shows SI in 2/4/4 cycle
- Verified toggle SI setting to off and then on still shows SI in the 2/4/4 cycle
------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified disabling SI via learn more and enabling the setting still shows SI in 2/4/4 cycle
- Verified toggle SI setting to off and then on still shows SI in the 2/4/4 cycle
------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.18.17)
- Verified disabling SI via learn more and enabling the setting still shows SI in 2/4/4 cycle
- Verified toggle SI setting to off and then on still shows SI in the 2/4/4 cycle
------
