### ISSUE TITLE
Wallet creation year is not fully shown in settings

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2330]
### Description: 
Wallet creation year is not fully shown in settings

### Steps to Reproduce 
  1. Install 1.15
  2. Enable rewards
  3. Go to settings and get confused

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/74530885-34807300-4f51-11ea-984a-57fe1230e463.png)
When Calendar set to Japan
![image](https://user-images.githubusercontent.com/17010094/74530904-42ce8f00-4f51-11ea-9631-d3fe4e6d456a.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/17010094/74530897-3a765400-4f51-11ea-90b0-d0f5b934500f.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.15(20.02.12.10)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
This string is a localized short date string, so it will change region to region
