### ISSUE TITLE
Observing mixed-messaging in YT creator tipping flow on iOS

### ISSUE THREAD

**Issue by lukemulks** [brave/brave-ios#2331]
### Description: 
I was tipping a YT creator to confirm that they had successfully linked their Uphold acct from Brave on iOS, and encountered some mixed messaging that was a little confusing. 

1. When I clicked on the BAT icon in the URL bar to tip the YT creator from YT.com, the Rewards panel eventually updated to remove the “This creator has not linked their acct to uphold...everything you tip will be pledged” copy, after about 15s. This was expected, as the creator had just successfully linked their Creator acct to Uphold (we were testing the flow to confirm they were all set). 

![41BD30C7-EAA0-490B-BF8C-9BDF409C60BE](https://user-images.githubusercontent.com/8979240/74591853-5a992800-4fd0-11ea-9a10-52b45dde3dba.png)

2. However, when I was navigated to the tipping banner as the next step, the tipping banner still displayed the message that displays when Creators have not connected to Uphold. 

![1ED36E56-F08E-42EC-8E59-2CA8381E6C68](https://user-images.githubusercontent.com/8979240/74591887-bbc0fb80-4fd0-11ea-9984-343fcf7c3119.png)

- There’s nowhere in the tipping banner page to refresh the status, unlike the Rewards panel from the URL bar where the user can refresh status and see the message go away after the creator links to Uphold. 

- The tipping banner should update to sync with the creator status that displays from the Rewards panel in the URL bar after the status refreshes to remove the message about the creator needing to link their account / fully verify to receive tips. 

3. Note that I’m able to successfully complete the tipping flow, and observe the success message after completing the flow. This is expected, as the creator has fully verified. 

![0400DCFF-0968-4AF0-A62F-3B52E9B216CC](https://user-images.githubusercontent.com/8979240/74591896-d6937000-4fd0-11ea-965e-443d952882f4.png)

I only appear to be observing this on mobile, iOS so far (have not tested on Android yet). Not observing similar behavior on desktop, but can double check. 

### Steps to Reproduce 
  1. Go to fully verified YT creator
  2. Tip
  3. 

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
TBD

**Brave Version:** 

Version 1.15 (20.02.12.10)

**Device details:** 

iPad Pro (12.9-inch) (2nd generation)
iOS 13.3

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
@lukemulks I'm a bit confused.. so to confirm:

You opened the panel and saw the unverified disclaimer, and clicked "refresh" in there which updated the disclaimer but then opening the tipping panel didn't reflect the updated publisher status?
