### ISSUE TITLE
Implement "Link that you copied" option

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ios#2332]
## Problem Description
Navigating to a link your clipboard means having to first paste the link into the address bar, and then manually invoking navigation. [Users on Twitter](https://twitter.com/NischalShetty/status/1229244871031971841) and elsewhere have voiced their desire to see this issue addressed in Brave on iOS (achieving parity with Brave on desktop, and Android):

![image](https://user-images.githubusercontent.com/815158/74625103-a7841800-5110-11ea-8576-93dbecf824bf.png)

## Feature Overview
This request suggests a _paste and go_ style option, or Chrome's "link that you copied" navigation option.

## Design
This option appears when the user focuses the address bar, and the clipboard contains a valid URL.

## Implementation Details
The following shows this option in Chrome on iOS:

![image](https://user-images.githubusercontent.com/815158/74625212-2a0cd780-5111-11ea-9fcf-21ecdc8d8957.png)

**Comment by iccub** [comment]
This got implemented few versions ago with the new search overlay
