### ISSUE TITLE
Show pending contributions doesn't open contribution list

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2333]
### Description: 
Show pending contributions doesn't open contribution list

### Steps to Reproduce 
  1. Install 1.15(20.02.12.10)
  2. Visit an unverified pub and tip them
  3. Open a new tab and open rewards panel
  4. Tap on `Show pending contribution` doesn't open pending list

**Actual result:** 
![pending-contribution](https://user-images.githubusercontent.com/17010094/74626633-3d05c300-5176-11ea-9ee1-9ed4647183d7.gif)

**Expected result:**
Should open the pending list 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.15(20.02.12.10)

**Device details:** 
iPhone 7+ (iOS 13.3.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Found while testing  #1670

**Comment by kylehickinson** [comment]
This doesn't actually have anything to do with the pending contributions, this bug affects the Learn More button as well. It is a bug related to `LinkLabel` (cc @Brandon-T) where for some reason there is a race condition and the linked text doesn't become tappable for some reason.

@srirambv Opening & Closing the panel would fix this

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.18.17)
- Verified show pending contribution opens the list 
- Verified screenshots here https://github.com/brave/brave-ios/issues/1670#issuecomment-588157912
-----
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.18.17)
- Verified show pending contribution opens the list 
-----
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.18.17)
- Verified show pending contribution opens the list 
-----
Verification passed on iPad Pro with iOS 13.4 running 1.15(20.02.18.17)
- Verified show pending contribution opens the list 
-----
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.18.17)
- Verified show pending contribution opens the list
