### ISSUE TITLE
New tab is opened when a different anchor element is selected 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2334]
### Description: 
Found while testing #1653, if a different anchor element is selected on the support page a new tab is opened when Learn more is selected from the panel

### Steps to Reproduce 
  1. Install 1.16(20.02.12.10)
  2. Visit an unverified publisher and select learn more in panel
  3. Opens a new tab and focus is set to `https://brave.com/faq/#unclaimed-funds`
  4 Select a different anchor element on the support page
  5. Switch back to unverified pub tab and select learn more from the panel, a new tab is opened and loads `https://brave.com/faq/#unclaimed-funds` instead of focusing to the same anchor link on the already opened support page

**Actual result:** 
New tab is opened when a different anchor element is selected 

**Expected result:**
Should switch to the anchor link on the already existing support page 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.15(20.02.12.10)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

**Comment by kylehickinson** [comment]
Technically the full URL is different since you tapped on a different anchor, therefore we open a new tab (`https://brave.com/faq/#unclaimed-funds` vs `https://brave.com/faq/#some-other-anchor`) and we only highlight a tab with the exact same full-url

**Comment by NejcZdovc** [comment]
@kylehickinson can this one be closed?

**Comment by kylehickinson** [comment]
I personally don't think its a big issue and can be closed since a user is unlikely to come across this and even if they did, nothing really bad about it, but ultimately up to @srirambv

**Comment by NejcZdovc** [comment]
working as expected as you changed anchor in the url so, url's are not the same
