### ISSUE TITLE
Get paid for SI modal is shown even when SI is turned off

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2335]
### Description: 
Get paid for SI modal is shown even when SI is turned off

### Steps to Reproduce 
  1. Clean install 1.15(20.02.12.10)
  2. View a SI image, ensure getting paid for sponsored image modal is shown 
  3. Go to settings and disable SI 
  4. Go back modal is retained on stock images

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/74652285-b9ff5f80-51ab-11ea-94b3-29f6cc34e5db.png)

**Expected result:**
Modal should be smart enough to be removed when SI is not being shown

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.15(20.02.12.10)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by GeetaSarvadnya** [comment]
Reproduced in iPhone 8 running Brave 1.14.3 (20.02.01.06)
