### ISSUE TITLE
Add option to disable Bookmarks/OpenTabs/History suggestions when typing in url

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2336]
## Problem Description 

Add option to disable bookmarks/history suggestions when typing in url

## Feature Overview 

This will be one option where the behaviour will be set for entire browser. It will disble and enable the suggestions from all the sources Open Tabs Bookmarks History. 

## Implementation Details 

There will not separate switches for data types. The toggle will control all the types. And it will be added under Search Engines below Search Suggestions.

Do not change default behaviour and only add switch to alert the behaviour. 

##User Experience 

   1. Navigate Settings -> Search -> Disable Suggestions
   2. Focus on url bar and type
   3. Check no suggestions
   
  As mentioned switch behaviour will be for both of the modes. Default and Private.

**Comment by Brave-Matt** [comment]
Have a user bringing this to our attention on Community as well:
https://community.brave.com/t/no-more-bookmark-search/152974

**Comment by Brave-Matt** [comment]
Worth noting that the feature currently does _not_ work. So this option would be an enable/disable feature, essentially?

**Comment by t-h-man** [comment]
Please consider implementing this as it makes no sense to offer the option to disable "recent searches" when they show up anyway under "Bookmarks & History" when using the search bar. 

For me this is actually a deal-breaker and the sole reason I haven't switched to Brave from Safari on iOs. Firefox already offers this. Thank you.

**Comment by t-h-man** [comment]
Still not fixed/has not been implemented. Even when "recent searches" are off in the settings, brave shows search history when we click on the address bar, under "Bookmarks & History"

**Comment by iccub** [comment]
We added it for private browsing only mode, reopening this and we may consider having a toggle to disable it for all browsing modes

**Comment by A-t-s-u-s-h-i** [comment]
1 more user suggests this feature on the community thread here.(Sorry that the thread is written in Japanese) It prevents users to select auto-sugesstion by typing app like simeji.

https://community.brave.com/t/simeji/470242

**Comment by otDan** [comment]
> We added it for private browsing only mode, reopening this and we may consider having a toggle to disable it for all browsing modes

I need this, it's pretty annoying since if I am searching for something I do want autocomplete but I do not want the bookmarks to show up or I would have just opened them myself

**Comment by r-erd** [comment]
(push!)

**Comment by acky001** [comment]
+1 
This should be an essential feature. I waited long for it to be possible on the PC client and thought I can switch from FF now. But not being able to do this on iOS stops me from doing so.

**Comment by MondoBurrito** [comment]
Dear lord, I wish this "privacy-focused" browser would fix this issue. When I search in the title bar, I should NOT be able to see open tabs & bookmarks & history.  At least give us the option to turn this off, just like on the desktop version. This gives no advanatage to using Brave over Firefox. Please allow us to control our privacy on iOS!

**Comment by anthonypkeane** [comment]
Text: Show Browser Suggestions
Description: Turn this on to include results from your History and Bookmarks when searching.
On | Off  -> Default On

**Comment by hffvld** [comment]
Verified on `iPhone 14`using version(s):
```
Device/OS: iPhone 14 / iOS 17.4 Beta
Brave build: 1.62 (24.1.25.17)
BraveCore: 1.62.153 (121.0.6167.85)
```
---------------------------
<details>
<summary> Standard Tab </summary>

**STEPS:**
1. Fresh install and launch Brave 
2. Three-dot menu > Settings > Search Engines > Verify
3. Go back to NTP > Tap `Wikipedia` favorite icon > Wait until landed > Bookmark it
4. Open any article > Bookmark it
5. Tap any link in the article > Wait until landed
6. Open NTP > URL search bar > Type `wiki` > Verify
7. Repeat this step for each URL category (`Bookmarks`, `History` and `Opened tabs`): Tap each of them one by one > Verify
8. Three-dot menu > Settings > Search Engines > Disable `Show Browser Suggestions`
12. Close the settings > Tap the URL search bar > Type `wiki` > Verify

**ACTUAL RESULTS:**
- Verified that the `Show Browser Suggestions` toggle switch is `ON` by default
- Verified that the title is `Show Browser Suggestions` and the description is `Turn this on to include results from your History and Bookmarks when searching`
- Verified that `Open Tabs & Bookmarks & History` suggestion is showing search results for all 3 categories (`Bookmarks`, `History` and `Opened Tabs`)
- Verified that any URL category (`Bookmarks`, `History` or `Opened Tabs`) can be opened
- Verified that no search suggestions are shown when `Show Browser Suggestions` is disabled

---------------------------

*`Show Browser Suggestions` is `ON`*

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/4d26c14f-0c00-4ad3-9856-2d881fa7fbf0) | ![2](https://github.com/brave/brave-ios/assets/128532965/4897dd4b-3503-4405-858f-ed40b0d3b359) | ![3](https://github.com/brave/brave-ios/assets/128532965/ac5d9a84-c23f-455b-9288-79f140eb5f5b) |

*`Show Browser Suggestions` is `OFF`*

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/47ee4a99-5114-4b6a-92de-7788dbcde566) | ![2](https://github.com/brave/brave-ios/assets/128532965/4897dd4b-3503-4405-858f-ed40b0d3b359) | ![3](https://github.com/brave/brave-ios/assets/128532965/b49f846c-4955-4dd6-9969-45227fb36e4f) |

https://github.com/brave/brave-ios/assets/128532965/98a8ce27-7b99-4a31-b0c1-b4bfc576eb24
</details>

<details>
<summary> Private Tab </summary>

**STEPS:**
1. Three-dot menu > Settings > Search Engines > Make sure that `Show Browser Suggestions` is ON
2. Close the settings > Open a new `Private` tab
3. Tap `Wikipedia` favorite icon > Open another article > Bookmark it
4. Tap any link in the article > Wait until landed > Repete it a few more times
5. Open NTP > URL search bar > Type `wiki` > Verify
6. Repeat this step for each URL category (`Bookmarks`, `History` and `Opened tabs`): Tap each of them one by one > Verify
13. Three-dot menu > Settings > Search Engines > Disable `Show Browser Suggestions`
14. Close the settings > Tap the URL search bar > Type `wiki` > Verify

**ACTUAL RESULTS:**
- Verified that URLs from all 3 categories (`Bookmarks`, `History` and `Opened tabs`) that were previously opened in the `Standard` tab, are shown in the `Private` tab suggestions
- Verified that suggestions are shown only for the URLs from the `Bookmarks` and `Opened tabs` categories, but not shown for the URLs from the `History` category, where all of them were opened/bookmarked in the `Private` tab 
- Verified that any URL (from `Bookmarks`, `History` or `Opened Tabs`) can be opened
- Verified that no search suggestions are shown when `Show Browser Suggestions` is disabled

---------------------------

*`Show Browser Suggestions` is `ON`*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/d176f1ba-f6d3-4ae4-86e5-e16825fca282) | ![2](https://github.com/brave/brave-ios/assets/128532965/8c7bbce7-b474-4d81-8f90-820aeb65b9a2) | ![3](https://github.com/brave/brave-ios/assets/128532965/87d4bb3a-12f0-4a85-974a-db319c6cf362) | ![4](https://github.com/brave/brave-ios/assets/128532965/828fd14d-23b3-4712-ab54-e52508ca4f09) |

*`Show Browser Suggestions` is `OFF`*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/0caab50e-19dc-4047-8162-e681d3825ffc) | ![2](https://github.com/brave/brave-ios/assets/128532965/8c7bbce7-b474-4d81-8f90-820aeb65b9a2) | ![3](https://github.com/brave/brave-ios/assets/128532965/87d4bb3a-12f0-4a85-974a-db319c6cf362) | ![4](https://github.com/brave/brave-ios/assets/128532965/4e2ad75a-f16f-4584-b80e-afb094421174) |

https://github.com/brave/brave-ios/assets/128532965/6c7563ea-b8e9-4364-9b52-9a4a9ba40afa
</details>
