### ISSUE TITLE
WKScriptMessage crash

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2337]
### Description: 

Hard to say what is the problem, I believe this is some kind of memory leak.

<img width="601" alt="Zrzut ekranu 2020-02-17 o 16 28 09" src="https://user-images.githubusercontent.com/6950387/74666827-81a75380-51a2-11ea-8e46-5b30d99c21f3.png">

### Steps to Reproduce 
  1. Hard to repro :( Never managed to repro it

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jwise** [comment]
FWIW, I think the root cause of this is if you `release` the last reference to a `WKWebView` off the main thread, at the same time as a `WKWebView` is sending a `WKScriptMessage` back to the main thread.  I think this might also fix it but I'm not 100% convinced.
