### ISSUE TITLE
On dark theme the site details view text is not visible 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2344]
### Description: 
While testing #1670, found on dark theme the site details view text is not visible 

### Steps to Reproduce 
  1. Set device theme to dark 
  2. Send a tip to non-verified pub
  3. Open site details in pending contribution, text is not visible

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/74827573-aa128780-5333-11ea-8157-79346e609d41.png)

**Expected result:**
Text should be visible on any theme

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.15(20.02.18.17)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
@kylehickinson please move the issue to 1.15 if you think this should be fixed in it

**Comment by iccub** [comment]
Moving to 1.15, this should be simple to fix and we still have some time before final RC builds as we are waiting for translations

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15(20.02.20.19)
- Verified text is visible on dark theme and light theme
![image](https://user-images.githubusercontent.com/17010094/75004432-1d7ddb80-5491-11ea-9c33-4c5ac160af36.png)
------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.20.19)
- Verified text is visible on dark theme and light theme
![image](https://user-images.githubusercontent.com/17010094/75004441-240c5300-5491-11ea-8a3b-b911b529e803.png)

------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.20.19)
- Verified text is visible on dark theme and light theme
![image](https://user-images.githubusercontent.com/17010094/75004444-29699d80-5491-11ea-947b-2da3fe5945e7.png)

------
Verification passed on iPad Pro  with iOS 13.3.1 running 1.15(20.02.20.19)
- Verified text is visible on dark theme and light theme
![image](https://user-images.githubusercontent.com/17010094/75004460-34243280-5491-11ea-9ef8-925038401ca4.png)

------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.20.19)
- Verified text is visible on dark theme and light theme
![image](https://user-images.githubusercontent.com/17010094/75004460-34243280-5491-11ea-9ef8-925038401ca4.png)

------
