### ISSUE TITLE
Missing dot(.) in NTP view

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2346]
### Steps to Reproduce 
  1. Enable Rewards & Ads
  2. Visit first sponsored image
  3. Tap on learn more

**Actual result:** 
No dot after `...images in Brave Rewards`

![IMG_6699](https://user-images.githubusercontent.com/6950387/74830810-3c0a9800-5314-11ea-9ca4-c58bb6a6474c.jpg)

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Copy changes in https://github.com/brave/brave-ios/issues/2363

Please compare it with that ticket

**Comment by kjozwiak** [comment]
Labeling this as `QA/No` as the changed as per https://github.com/brave/brave-ios/issues/2346#issuecomment-590476500. Going to check the NTP SI modals via https://github.com/brave/brave-ios/issues/2363.
