### ISSUE TITLE
Remove PIN callout from private mode

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2350]
### Description: 

Please remove this callout

![Screen Shot 2020-02-19 at 11.57.30 AM.png](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/e97d3fac-c64c-45da-bb18-704b021e5e6d)

Slack Thread: https://bravesoftware.slack.com/archives/C20HMJ62H/p1582141555147300

**Comment by kjozwiak** [comment]
Labeling as `QA/Blocked` till https://github.com/brave/brave-ios/issues/2391 is resolved.

**Comment by kjozwiak** [comment]
Removing `QA/Blocked` as https://github.com/brave/brave-ios/issues/2391 has been fixed.

**Comment by LaurenWags** [comment]
Verification **PASSED** on `iPad 5th Gen` running `iOS 12` using `1.15 (20.03.05.14)`:

* Clean Profile testing:
   * ensured that the Pin modal is not being displayed when launching PB for the first time on a clean install of 1.15.
   * ensured that a Pin can still be set from settings in 1.15. Verified able to change Pin and turn the Pin off.
* Upgrade profile testing:
   * ensured that the Pin modal is not being displayed when launching PB for the first time on a profile upgraded from 1.14.3.
   * ensured that a Pin set on 1.14.3 still works after upgrading to 1.15.
* Other:
   * during additional testing of Private Browsing done with https://github.com/brave/brave-ios/issues/2391#issuecomment-595393045 no Pin modal was seen

-----

Verification **PASSED** on `iPad mini` running `iOS 13` using `1.15 (20.03.05.14)`:

* Clean Profile testing:
   * ensured that the Pin modal is not being displayed when launching PB for the first time on a clean install of 1.15.
   * ensured that a Pin can still be set from settings in 1.15. Verified able to change Pin and turn the Pin off.
* Upgrade profile testing:
   * ensured that the Pin modal is not being displayed when launching PB for the first time on a profile upgraded from 1.14.3.
   * ensured that a Pin set on 1.14.3 still works after upgrading to 1.15.
* Other:
   * during additional testing of Private Browsing done with https://github.com/brave/brave-ios/issues/2391#issuecomment-595393045 no Pin modal was seen

-----

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.15 (20.03.05.13)`:

* Clean Profile testing:
   * ensured that the Pin modal is not being displayed when launching PB for the first time on a clean install of 1.15.
   * ensured that a Pin can still be set from settings in 1.15. Verified able to change Pin and turn the Pin off.
* Upgrade profile testing:
   * ensured that the Pin modal is not being displayed when launching PB for the first time on a profile upgraded from 1.14.3.
   * ensured that a Pin set on 1.14.3 still works after upgrading to 1.15.
* Other:
   * during additional testing of Private Browsing done with https://github.com/brave/brave-ios/issues/2391#issuecomment-595393045 no Pin modal was seen

-----

Verification **PASSED** on `iPhone 11` running `iOS 13.3.1` using `1.15 (20.03.05.13)`:

* Clean Profile testing:
   * ensured that the Pin modal is not being displayed when launching PB for the first time on a clean install of 1.15.
   * ensured that a Pin can still be set from settings in 1.15. Verified able to change Pin and turn the Pin off.
* Upgrade profile testing:
   * ensured that the Pin modal is not being displayed when launching PB for the first time on a profile upgraded from 1.14.3.
   * ensured that a Pin set on 1.14.3 still works after upgrading to 1.15.
* Other:
   * during additional testing of Private Browsing done with https://github.com/brave/brave-ios/issues/2391#issuecomment-595393045 no Pin modal was seen
