### ISSUE TITLE
Crash when moving bookmark to favorites on NTP

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2359]
### Steps to Reproduce 
Have at least 4 favorites on iPhone so the next bookmark will overflow, preloaded favorites are enough.
  1. Go to some website
  2. Add it to bookmarks
  3. Open NTP
  4. Open bookmarks panel
  5. Move bookmark from step 1 to favorites

**Actual result:** 
Crash

**Expected result:**
Should not crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15(20.02.20.19)
- Verified steps from issue description and no crash 
- Verified no crash when moving bookmarks from folders to favourites
-------
Verification passed on iPhone XR+ with iOS 13.4 running 1.15(20.02.20.19)
- Verified steps from issue description and no crash 
- Verified no crash when moving bookmarks from folders to favourites
-------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15(20.02.20.19)
- Verified steps from issue description and no crash 
- Verified no crash when moving bookmarks from folders to favourites
-------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15(20.02.20.19)
- Verified steps from issue description and no crash 
- Verified no crash when moving bookmarks from folders to favourites
-------
Verification passed on iPad Pro with iOS 12.4.4 running 1.15(20.02.20.19)
- Verified steps from issue description and no crash 
- Verified no crash when moving bookmarks from folders to favourites
-------
