### ISSUE TITLE
Louis Kim photo credit missing

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2361]
### Description: 
Louis Kim photo credit missing

### Steps to Reproduce 
  1. Open NTP with Lous Kim's photo
  2. Tap on photo credit 
  3. No link to photo credit page is shown

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/75029403-fee70700-54c7-11ea-80fb-a3a16d066e02.png)

**Expected result:**
Should show photo credit landing page link in popup

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.15 and 1.14.3

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 13.3.1` using `1.15 (20.03.04.18)`

* Verified that tapping on `View on Louiskimphotography` opens `http://louiskimphotography.com`
  * ensured it works on both normal tabs and PB
* ensured that pressing `Close` closes the modal without any issues

![IMG_0034](https://user-images.githubusercontent.com/2602313/75920637-c29f9900-5e2d-11ea-9df3-fe2aebb372c2.PNG)

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.15 (20.03.04.18)`

* Verified that tapping on `View on Louiskimphotography` opens `http://louiskimphotography.com`
  * ensured it works on both normal tabs and PB
* ensured that pressing `Close` closes the modal without any issues

![IMG_0002](https://user-images.githubusercontent.com/2602313/75921478-30989000-5e2f-11ea-8ccb-580144d09d92.PNG)

Verification **PASSED** on `iPad Air 3rd Gen` running `iOS 13.3.1` using `1.15 (20.03.04.18)`

* Verified that tapping on `View on Louiskimphotography` opens `http://louiskimphotography.com`
  * ensured it works on both normal tabs and PB
* ensured that pressing `Close` closes the modal without any issues

![IMG_0117](https://user-images.githubusercontent.com/2602313/75921953-1612e680-5e30-11ea-8412-b87504adef69.PNG)

Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.15 (20.03.04.18)`

* Verified that tapping on `View on Louiskimphotography` opens `http://louiskimphotography.com`
  * ensured it works on both normal tabs and PB
* ensured that pressing `Close` closes the modal without any issues

![IMG_0302](https://user-images.githubusercontent.com/2602313/75922433-ff20c400-5e30-11ea-9e11-73d4a88beb48.PNG)
