### ISSUE TITLE
Remove 'get paid' verbiage on Sponsored Images (iOS)

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-ios#2363]
### Description
The word "paid" showing up in the context of seeing sponsored images was causing problems with getting our app approved by Apple. Update the copy with some minor design improvements:

- Replace "get paid" with "earn tokens"
- Add more detail on the modal (previously the modal had pretty much the same information as on the banner, making 'learn more' kind of useless)
- Use more iOS  styled links

### Designs
![ios new SI text](https://user-images.githubusercontent.com/2388823/75066183-355c5c00-549f-11ea-89f0-8c791cc62bad.png)

Carry updates over to alternate views:

![ios sponsored landscape message](https://user-images.githubusercontent.com/2388823/75066707-42c61600-54a0-11ea-8627-8cca6f469989.png)
![ios sponsored landscape modal](https://user-images.githubusercontent.com/2388823/75066390-984df300-549f-11ea-94a2-26c8f6564338.png)
![11″ iPad Pro](https://user-images.githubusercontent.com/2388823/75066705-4063bc00-54a0-11ea-97c9-20ec74ca7cf7.png)

### Assets
Abstract link: https://share.goabstract.com/75d50a1f-7f36-4d4a-942f-d48348c3d094?

**Comment by iccub** [comment]
We decided not to include the bottom separator for second button, after 'Hide sponsored images'

**Comment by LaurenWags** [comment]
Verification passed on `iPad mini` with `iOS 13` running `1.15 (20.3.5.13)`

- Verified `New` designs from https://github.com/brave/brave-ios/issues/2363#issue-569152248 for the following scenarios:

BR on, Ads on - NTP SI
   - Verified `x` closes the banner/modal.
   - Verified tapping on `Learn more` opens the modal with more information.
   - Verified tapping on `Learn more about sponsored images` opens https://brave.com/brave-rewards
   - Verified tapping on `Hide sponsored images` toggles SI off and SI are not shown.

![iPad-iOS13-2363-NTPSI-BRon-Adson-1](https://user-images.githubusercontent.com/28145373/76005079-85441580-5ed8-11ea-813d-bd31921748f2.jpg)
![iPad-iOS13-2363-NTPSI-BRon-Adson-2](https://user-images.githubusercontent.com/28145373/76005090-87a66f80-5ed8-11ea-850c-c9208d6d848d.jpg)

BR on, Ads off - NTP SI
   - Verified `x` closes the banner/modal.
   - Verified tapping on `Learn more` opens the modal with more information.
   - Verified `Turn on Brave Ads` button enables Ads.
   - Verified tapping on `Learn more about sponsored images` opens https://brave.com/brave-rewards
   - Verified tapping on `Hide sponsored images` toggles SI off and SI are not shown.

![iPad-iOS13-2363-NTPSI-BRon-Adsoff-1](https://user-images.githubusercontent.com/28145373/76005111-8f661400-5ed8-11ea-9d8d-1a6a6d7f49ac.jpg)
![iPad-iOS13-2363-NTPSI-BRon-Adsoff-2](https://user-images.githubusercontent.com/28145373/76005117-92610480-5ed8-11ea-920f-7bc07c1cca85.jpg)

BR off - NTP SI
   - Verified `x` closes the banner/modal.
   - Verified tapping on `Learn more` opens the modal with more information.
   - Verified `Turn on Brave Rewards` button enables BR.
   - Verified tapping on `Terms of Service` opens https://brave.com/terms_of_use
   - Verified tapping on `Learn more about Brave Rewards` opens https://brave.com/brave-rewards
   - Verified tapping on `Hide sponsored images` toggles SI off and SI are not shown.

![iPad-iOS13-2363-NTPSI-BRoff-1](https://user-images.githubusercontent.com/28145373/76005140-9ab93f80-5ed8-11ea-8b4f-d721df429f3d.jpg)
![iPad-iOS13-2363-NTPSI-BRoff-2](https://user-images.githubusercontent.com/28145373/76005148-9db43000-5ed8-11ea-8212-e8695e1c0262.jpg)

-----

Verification passed on `iPad 5th Gen` with `iOS 12` running `1.15 (20.3.5.13)`

- Verified `New` designs from https://github.com/brave/brave-ios/issues/2363#issue-569152248 for the following scenarios:

BR on, Ads on - NTP SI
   - Verified `x` closes the banner/modal.
   - Verified tapping on `Learn more` opens the modal with more information.
   - Verified tapping on `Learn more about sponsored images` opens https://brave.com/brave-rewards
   - Verified tapping on `Hide sponsored images` toggles SI off and SI are not shown.

![iPad-iOS12-2363-NTPSI-BRon-Adson-1](https://user-images.githubusercontent.com/28145373/76009441-38177200-5edf-11ea-8be1-faadf4465be2.jpeg)
![iPad-iOS12-2363-NTPSI-BRon-Adson-2](https://user-images.githubusercontent.com/28145373/76009448-39e13580-5edf-11ea-82f4-2ab4b2dfefca.jpeg)

BR on, Ads off - NTP SI
   - Verified `x` closes the banner/modal.
   - Verified tapping on `Learn more` opens the modal with more information.
   - Verified `Turn on Brave Ads` button enables Ads.
   - Verified tapping on `Learn more about sponsored images` opens https://brave.com/brave-rewards
   - Verified tapping on `Hide sponsored images` toggles SI off and SI are not shown.

![iPad-iOS12-2363-NTPSI-BRon-Adsoff-1](https://user-images.githubusercontent.com/28145373/76009474-42d20700-5edf-11ea-983f-bc2f45d377ec.jpeg)
![iPad-iOS12-2363-NTPSI-BRon-Adsoff-2](https://user-images.githubusercontent.com/28145373/76009484-45346100-5edf-11ea-94f4-11bf9c9dc6ca.jpeg)

BR off - NTP SI
   - Verified `x` closes the banner/modal.
   - Verified tapping on `Learn more` opens the modal with more information.
   - Verified `Turn on Brave Rewards` button enables BR.
   - Verified tapping on `Terms of Service` opens https://brave.com/terms_of_use
   - Verified tapping on `Learn more about Brave Rewards` opens https://brave.com/brave-rewards
   - Verified tapping on `Hide sponsored images` toggles SI off and SI are not shown.

![iPad-iOS12-2363-NTPSI-BRoff-1](https://user-images.githubusercontent.com/28145373/76009499-4a91ab80-5edf-11ea-831c-15dbab952965.jpeg)
![iPad-iOS12-2363-NTPSI-BRoff-2](https://user-images.githubusercontent.com/28145373/76009507-4cf40580-5edf-11ea-8d68-44ccbeca9ae5.jpeg)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 13.3.1` using `1.15 (20.03.05.13)`:

- Verified `New` designs from https://github.com/brave/brave-ios/issues/2363#issue-569152248 for the following scenarios:

**`BR on, Ads on - NTP SI`**

*  Verified `x` closes the banner/modal.
* Verified tapping on `Learn more` opens the modal with more information.
* Verified that tapping on `X` closes the NTP SI modal
* Verified that sliding the NTP SI modal away from view closes the modal
* Verified tapping on `Learn more about sponsored images` opens https://brave.com/brave-rewards
* Verified tapping on `Hide sponsored images` toggles SI off and SI are not shown
* Verified that re-enabling NTP SI via the `New Tab Page` settings worked as expected

<img width="482" alt="Screen Shot 2020-03-05 at 12 38 55 PM" src="https://user-images.githubusercontent.com/2602313/76008848-503ac180-5ede-11ea-986e-0ab78c9afb5c.png">

<img width="483" alt="Screen Shot 2020-03-05 at 12 38 45 PM" src="https://user-images.githubusercontent.com/2602313/76008858-5335b200-5ede-11ea-9e96-260317dca20b.png">

**`BR on, Ads off - NTP SI`**

* Verified `x` closes the banner/modal.
* Verified tapping on `Learn more` opens the modal with more information.
* Verified that tapping on `X` closes the NTP SI modal
* Verified that sliding the NTP SI modal away from view closes the modal
* Verified `Turn on Brave Ads` button enables Ads.
* Verified tapping on `Learn more about sponsored images` opens https://brave.com/brave-rewards
* Verified tapping on `Hide sponsored images` toggles SI off and SI are not shown.
* Verified that re-enabling NTP SI via the `New Tab Page` settings worked as expected

<img width="482" alt="Screen Shot 2020-03-05 at 12 48 48 PM" src="https://user-images.githubusercontent.com/2602313/76009744-b1af6000-5edf-11ea-8292-0187dc94e741.png">

<img width="484" alt="Screen Shot 2020-03-05 at 12 48 55 PM" src="https://user-images.githubusercontent.com/2602313/76009775-bffd7c00-5edf-11ea-924f-e2c2993d2b85.png">

**`BR off - NTP SI`**

* Verified `x` closes the banner/modal.
* Verified tapping on `Learn more` opens the modal with more information
* Verified that tapping on `X` closes the NTP SI modal
* Verified that sliding the NTP SI modal away from view closes the modal
* Verified `Turn on Brave Rewards` button enables BR
* Verified tapping on `Terms of Service` opens https://brave.com/terms_of_use
* Verified tapping on `Learn more about Brave Rewards` opens https://brave.com/brave-rewards
* Verified tapping on `Hide sponsored images` toggles SI off and SI are not shown.

<img width="484" alt="Screen Shot 2020-03-05 at 12 57 56 PM" src="https://user-images.githubusercontent.com/2602313/76010484-f8518a00-5ee0-11ea-9e0a-88e319d195ae.png">

<img width="486" alt="Screen Shot 2020-03-05 at 12 58 03 PM" src="https://user-images.githubusercontent.com/2602313/76010507-00a9c500-5ee1-11ea-8de7-d32c0be8d3b5.png">

------

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.15 (20.03.05.13)`:

* Verified `New` designs from https://github.com/brave/brave-ios/issues/2363#issue-569152248 for the following scenarios:

**`BR on, Ads on - NTP SI`**

*  Verified `x` closes the banner/modal.
* Verified tapping on `Learn more` opens the modal with more information.
* Verified that tapping on `X` closes the NTP SI modal
* Verified that sliding the NTP SI modal away from view closes the modal
* Verified tapping on `Learn more about sponsored images` opens https://brave.com/brave-rewards
* Verified tapping on `Hide sponsored images` toggles SI off and SI are not shown
* Verified that re-enabling NTP SI via the `New Tab Page` settings worked as expected

<img width="583" alt="Screen Shot 2020-03-05 at 1 21 30 PM" src="https://user-images.githubusercontent.com/2602313/76012425-41570d80-5ee4-11ea-9c63-08b947ac8529.png">

<img width="588" alt="Screen Shot 2020-03-05 at 1 21 36 PM" src="https://user-images.githubusercontent.com/2602313/76012460-50d65680-5ee4-11ea-88c8-ecd95087b3ba.png">

**`BR on, Ads off - NTP SI`**

* Verified `x` closes the banner/modal.
* Verified tapping on `Learn more` opens the modal with more information.
* Verified that tapping on `X` closes the NTP SI modal
* Verified that sliding the NTP SI modal away from view closes the modal
* Verified `Turn on Brave Ads` button enables Ads.
* Verified tapping on `Learn more about sponsored images` opens https://brave.com/brave-rewards
* Verified tapping on `Hide sponsored images` toggles SI off and SI are not shown.
* Verified that re-enabling NTP SI via the `New Tab Page` settings worked as expected

<img width="587" alt="Screen Shot 2020-03-05 at 1 33 47 PM" src="https://user-images.githubusercontent.com/2602313/76013492-f5a56380-5ee5-11ea-8c89-962ef5e9215b.png">

<img width="588" alt="Screen Shot 2020-03-05 at 1 33 40 PM" src="https://user-images.githubusercontent.com/2602313/76013500-f8a05400-5ee5-11ea-9963-fe92eca2eb16.png">

**`BR off - NTP SI`**

* Verified `x` closes the banner/modal.
* Verified tapping on `Learn more` opens the modal with more information
* Verified that tapping on `X` closes the NTP SI modal
* Verified that sliding the NTP SI modal away from view closes the modal
* Verified `Turn on Brave Rewards` button enables BR
* Verified tapping on `Terms of Service` opens https://brave.com/terms_of_use
* Verified tapping on `Learn more about Brave Rewards` opens https://brave.com/brave-rewards
* Verified tapping on `Hide sponsored images` toggles SI off and SI are not shown.

<img width="579" alt="Screen Shot 2020-03-05 at 1 40 36 PM" src="https://user-images.githubusercontent.com/2602313/76014015-e96dd600-5ee6-11ea-834a-d9a7cdeb4a14.png">

<img width="591" alt="Screen Shot 2020-03-05 at 1 40 30 PM" src="https://user-images.githubusercontent.com/2602313/76014024-ec68c680-5ee6-11ea-8f72-f685dbed2690.png">
