### ISSUE TITLE
IOS Bookmark Folder Icons color after scrolling

### ISSUE THREAD

**Issue by phoogm** [brave/brave-ios#2364]
### Description: 
For Brave on IOS the bookmark folders change background color after scrolling or seem to inherit the icon from existing bookmarks. 

### Steps to Reproduce 
  1. Have an IOS device with Brave browser installed with bookmarks and bookmark folders.
  2. Scroll through the bookmarks up and down.
  3. Observe that some of the folders are no longer showing the default background color but random background colors.

**Actual result:** 
![brave bookmark folder colors](https://user-images.githubusercontent.com/56597375/75092707-c48a7200-557a-11ea-9f85-5b285303238d.png)
![Brave bookmark folders color 2](https://user-images.githubusercontent.com/56597375/75092710-cbb18000-557a-11ea-8e34-2b8d4507102e.png)

**Expected result:**
Expect bookmark folders to maintain their default background color equal to the bookmark panel despite scrolling action.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
Version 1.14.3 (20.02.01.06)

**Device details:** 
Ipad Pro 12.9 Inch 3rd generation (iOS 13.3.1)

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by iccub** [comment]
Thanks for the report.
Do you have sync enabled?

**Comment by phoogm** [comment]
Hello, yes sync has been enabled for Brave browser version 1.3.118 on Mac, Mac, Ipad and Iphone being in a synch chain. Thanks.

**Comment by srirambv** [comment]
This happens when sync is in progress. Folder icons changes to transparent white when sync is complete. This is known but not sure if its an issue per se

**Comment by phoogm** [comment]
Please see below screenshots from the iPhone Xs Max IOS 13.3.1, one in landscape and one in portrait, these are the same unchanged bookmarks. 1) as you can see the landscape one has more colored bookmark folders then the portrait one and even a favicon with a 9 replacing the actual bookmark folder.
![screenshot_iphone_1](https://user-images.githubusercontent.com/56597375/75139757-bc9f0f00-56ed-11ea-86e4-9f8ed0f9b7e5.jpeg)
![Screenshot_iPhone_2](https://user-images.githubusercontent.com/56597375/75139770-c32d8680-56ed-11ea-80b6-f07c6ad4dfb7.png)

2) Compare the bookmark favicon icons from the Mac and the iPhone and observe the ones for 9to5Google (wrong) and MacRumors (wrong) are not matching and these are bookmarks i have had for a long time and have not changed. 
![bookmarksmac](https://user-images.githubusercontent.com/56597375/75139781-ccb6ee80-56ed-11ea-8802-4eb1f218d4fb.png)
![screenshot_iphone_full](https://user-images.githubusercontent.com/56597375/75139804-da6c7400-56ed-11ea-978d-6e09dc9f78f6.jpeg)

Not sure what the issue is, but it looks like a random color is applied to bookmarks and bookmarks folders that are missing favicon icons (as part of the sync process?), however if you have an unchanged set of bookmarks and folders then this should not happen and neither should rotating a device impact the bookmark folder icons background colors or replace icons. Typically i would expect a fallback to a default favicon icon if the real favicon is missing and this being replaced once the site has been visited. Bookmark folders should never change color regardless of device orientation or synch process. Thanks

**Comment by srirambv** [comment]
Issue still reproducible on 1.18(20.06.24.15)
![image](https://user-images.githubusercontent.com/17010094/85853995-2bda5c00-b7d1-11ea-9f6c-f5a9410224b6.png)

Moving the issue out of 1.18 and putting it in 1.19 as @iccub confirmed there isn't much work done on bookmarks except for  favicons

**Comment by iccub** [comment]
Closing, sync v2 will fix this problem
