### ISSUE TITLE
Make sure app background is always black.

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#2370]
### Description: 

App background takes on theme home color. When presenting view controllers modally this causes issues in iOS 13 since views take on a stacked appearance. 

Displaying app background as black (always) will create a more consistent stack appearance.

### Steps to Reproduce 
  1. Tap "Show More" on new tab page
  2. If you are currently in Light theme the background will appear light (and status bar will also be light)

**Expected result:**
All apple apps have a black background, which is apparent a view controller is displayed modally.

### Screenshots

** Current Behavior **
This is fine:
![Current Dark Theme](https://user-images.githubusercontent.com/2781690/76120976-a718c780-5fc0-11ea-970e-da3bc9ea9460.jpeg)

Notice how the app background (behind the status bar), is light, to match the theme. This is what should change.
![Current Light Theme](https://user-images.githubusercontent.com/2781690/76120980-a8e28b00-5fc0-11ea-8268-66d844524579.jpeg)

This is the expected / new behavior. It should only impact light theme, and how the background is dark.
![Expected (new) Light Theme](https://user-images.githubusercontent.com/2781690/76120982-aaac4e80-5fc0-11ea-8665-5c010b528aa8.jpeg)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 13.3.1` using `1.15 (20.03.05.13)`:

#### **`Example using Dark Theme`**

![IMG_0045](https://user-images.githubusercontent.com/2602313/76245350-19341b00-6212-11ea-896e-951644047d0d.PNG)

#### **`Example using Light Theme`**

![IMG_0044](https://user-images.githubusercontent.com/2602313/76245363-1fc29280-6212-11ea-9710-a23fb4a55dbe.PNG)
