### ISSUE TITLE
NTP `unpackMetadata` crash.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2375]
### Description: 

<img width="601" alt="Zrzut ekranu 2020-02-27 o 11 54 00" src="https://user-images.githubusercontent.com/6950387/75438223-de9bca00-5957-11ea-9511-7f59c69bf89e.png">

### Steps to Reproduce 
  1. Hard to reproduce, it crashes for some users only

**Actual result:** 
Crash

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
@jhreis @iccub if this is hard to reproduce and there's no STR, I'm going to label this as `QA/No` as there's not much we can do in this instance. Unless there's some STR that QA can go through.
