### ISSUE TITLE
iOS DB Migration (& rebase to brave-core master)

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2378]
Native libs will now handle all database rather than iOS handle DB side with CoreData (Desktop PR: https://github.com/brave/brave-core/pull/4252) 

iOS needs to handle migrating data from within CoreData to SQLite (creating SQL script to execute before allowing native libs to migrate up to current version of SQLite)

After this, `brave-core-ios` should now be compiled from master rather than our fork which is very behind

**Comment by NejcZdovc** [comment]
@kylehickinson should this be 1.5.1 as well like https://github.com/brave/brave-ios/issues/2200?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.3.1 running 1.15.1(20.04.07.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/2389
- Verified post upgrade wallet balance is retained
- Verified grants are retained in the wallet after upgrade
- Verified One time tips are not lost after upgrade
- Verified recurring tips are not lost after upgrade
- Verified ad grants are not lost after upgrade 
- Verified ac details is not lost after upgarde
- Verified disabling rewards and then upgrading still retains the db correctly 

----
Verification passed on 1.15.1(20.04.07.18) on staging on iPhone SE (iOS 12.4)
- Verified test plan from https://github.com/brave/brave-ios/pull/2389
- Used 1.15 (20.3.5.13) on staging to setup rewards
- Verified wallet balance was retained after upgrade
- Verified One time tips are not lost after upgrade
- Verified recurring tips are not lost after upgrade
- Verified a-c list was not lost after upgrade
- Verified exclude list was not lost after upgrade
- Verified rewards settings were retained after upgrade
- Verified tipping after upgrade
- Verified adding to ac table after upgrade
- Verified excluding pages after upgrade
- Verified above for not verified and verified publishers

----
Verification passed on iPhone 8 with iOS 13.3.1 running 1.15.1(20.04.07.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/2389
- Verified post upgrade wallet balance is retained (restored wallet balance)
- Verified grants are retained in the wallet after upgrade
- Verified one time tips are not lost after upgrade
- Verified recurring tips are not lost after upgrade
- Verified post upgrade supported sites and excluded sites are displayed in AC table
- Verified settings are retained (which are changed /updated in AC advanced and Ads panel)
- Verified post upgrade sites can be excluded and re-added to AC table
- Verified post upgrade new sites can be added to AC table
- Verified post upgrade one-time and recurring tips can be sent to pubs 
- Verified Pending contribution list table
- Verified reserved BAT text display in Rewards Summary and BR panel
- Verified Auto Contribution after upgrade
- Verified Auto contribution and Monthly Tips notifications in the panel
- Verified AC and other data is not lost after browser restart
- Verified AC data is not lost when Auto- contribute switch is turned off
- Verified AC data is not lost when Brave Rewards switch is turned off
---------
Verification passed on iPad Pro with iOS 12.4.5 running 1.15.1(20.04.07.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/2389
- Verified post upgrade wallet balance is retained
- Verified grants are retained in the wallet after upgrade
- Verified one time tips are not lost after upgrade
- Verified recurring tips are not lost after upgrade
- Verified sites are added correctly after upgrade
- Verified ac details is not lost after upgarde
- Verified disabling rewards and then upgrading still retains the db correctly 
-----
Verification passed on iPad mini with iOS 13 running 1.15.1(20.04.07.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/2389
- Used 1.15 (20.3.5.13) on staging to setup rewards (Dev build). 
- Verified wallet balance was retained after upgrade
- Verified wallet transactions list was retained after upgrade
- Verified one time tips list was not lost after upgrade
- Verified recurring tips list was not lost after upgrade
- Verified a-c list was not lost after upgrade
- Verified exclude list was not lost after upgrade
- Verified rewards settings were retained after upgrade
- Verified adding to ac table after upgrade
- Verified excluding pages after upgrade
- Verified able to one time tip after upgrade
- Verified ac was able to be contributed after upgrade
- Verified recurring tips were able to be contributed after upgrade
