### ISSUE TITLE
NTP SI is shown when accessed from overlay.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2380]
### Steps to Reproduce 
  1. Make sure you can see sponsored images
  2. Open some website on one tab
  3. Tap on address bar, then cancel it few times

**Actual result:** 

![IMG_4B0A8E2A2DDF-1](https://user-images.githubusercontent.com/6950387/75579536-5a843800-5a66-11ea-8dc0-559d73a65c76.jpeg)

**Expected result:**
Should not show ntp si

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.18(20.06.09.18) 
- Verified steps from issue description
- Verified visiting a page and then selecting URL bar brings up favourites and no background image is shown
------
Verification passed on iPhone 7+ with iOS 13.5.1 running 1.18(20.06.09.18) 
- Verified steps from issue description
- Verified visiting a page and then selecting URL bar brings up favourites and no background image is shown
------
Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.06.09.18) 
- Verified steps from issue description
- Verified visiting a page and then selecting URL bar brings up favourites and no background image is shown
