### ISSUE TITLE
Failed to open yahoo.co.jp from the address bar.

### ISSUE THREAD

**Issue by chkk525** [brave/brave-ios#2381]
### Description: 
- When I type “yahoo.co.jp” in address bar, I got this error screen saying "the connection is not private"
- This only happens on iOS.

- on mobile, it should redirect to m.yahoo.co.jp
- on laptop, it should redirect to www.yahoo.co.jp

### Steps to Reproduce 
  1. type "yahoo.co.jp" in the address bar 
  2. open it 
  3. you'll see the screen attached

**Actual result:** 
![image](https://user-images.githubusercontent.com/3054915/75646233-4d489280-5c8c-11ea-8b48-0bc7da4b4061.png)

**Expected result:**
- Redirect to m.yahoo.co.jp and see the screen like below
![IMG_2563](https://user-images.githubusercontent.com/3054915/75646281-76692300-5c8c-11ea-9d15-7d3ef9c8e933.PNG)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
- 100% of the time until it succeeds , and it sometimes happens after that

**Brave Version:** 
- 1.14.3

**Device details:** 
- iPhone X / iOS 13.3.1

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by ryanbr** [comment]
Yahoo.co.jp cert expired, https://www.ssllabs.com/ssltest/analyze.html?d=yahoo.co.jp&s=183.79.135.206&latest 

Affected other browsers
