### ISSUE TITLE
Add support for Rewards SKUs

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2383]
- [x] Build out the UI (buy with BAT sheet & its flows). Design on Abstract (iOS > `sku purchase flow.sketch`)
- [x] Build wrapper around shared libs for iOS for SKU APIs in brave-core
- [x] Integrate SKU API’s with UI
- [ ] Integrate SKU API’s with general web flow (if needed)

**Comment by NejcZdovc** [comment]
@kylehickinson can we close this one now as https://github.com/brave/brave-ios/pull/2431 was merged?

**Comment by kylehickinson** [comment]
@NejcZdovc It isn't actually enabled yet, there is a compiler flag that is blocking it. If you want to close off the issue and reopen another later when we're going to release it then that's fine with me

**Comment by iccub** [comment]
I think we can close this one for now
