### ISSUE TITLE
Disable Background Playback Flag

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#2387]
### Description: 

Since iOS 13 webkit has a bug that prevents audio playback, we should remove the flag associated with this feature.

This should have 0 impact to iOS 13, due to the existing but.

For iOS 12, this will remove the current feature of background playback.

### Steps to Reproduce 

* STR can be found via https://github.com/brave/brave-ios/pull/2385

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
Fixed per:
commit: 23ba88f49c3f0ab2958e8cefbb0e532e789e2283
PR: https://github.com/brave/brave-ios/pull/2385

**Comment by LaurenWags** [comment]
Verification passed on `iPad 5th Gen` with `iOS 12` running `1.15 (20.3.5.14)`
   - Verified test plan from https://github.com/brave/brave-ios/pull/2385
   - Ensured when playing a song on Soundcloud and backgrounding the app, the song did not immediately stop playing.
   - Ensured behavior on Soundcloud was the same on both `1.15` and `1.14.3 (20.02.01.06)`
   - Ensured when playing a video on YouTube and backgrounding the app, the song immediately stopped playing.

Verification passed on `iPad mini` with `iOS 13` running `1.15 (20.3.5.14)`
   - Verified test plan from https://github.com/brave/brave-ios/pull/2385
   - Ensured when playing a song on Soundcloud and backgrounding the app, the song did not immediately stop playing.
   - Ensured behavior on Soundcloud was the same on both `1.15` and `1.14.3 (20.02.01.06)`
   - Ensured when playing a video on YouTube and backgrounding the app, the song immediately stopped playing.

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.15 (20.03.05.13)`:

   - Verified test plan from https://github.com/brave/brave-ios/pull/2385
   - Ensured when playing a song on Soundcloud and backgrounding the app, the song did not immediately stop playing.
   - Ensured behavior on Soundcloud was the same on both `1.15` and `1.14.3 (20.02.01.06)`
   - Ensured when playing a video on YouTube and backgrounding the app, the song immediately stopped playing.

Verification **PASSED** on `iPhone 11` running `iOS 13.3.1` using `1.15 (20.03.05.13)`:

   - Verified test plan from https://github.com/brave/brave-ios/pull/2385
   - Ensured when playing a song on Soundcloud and backgrounding the app, the song did not immediately stop playing.
   - Ensured behavior on Soundcloud was the same on both `1.15` and `1.14.3 (20.02.01.06)`
   - Ensured when playing a video on YouTube and backgrounding the app, the song immediately stopped playing.
