### ISSUE TITLE
Make reward Settings button easier to notice 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2390]
### Description: 
@Brave-Matt reports that users are having a hard time figuring out that "setting" is a button

We need a better UX here. @kylehickinson @jamesmudgett for suggestions? 

![IMG_8D23462D3395-1 (1).jpeg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/a9534692-94cc-4e47-b5ab-e24bcef0077e)

**Comment by anthonypkeane** [comment]
Gear icon for settings??

![Settings](https://user-images.githubusercontent.com/7606853/75930214-f6c38b80-5e26-11ea-8543-bf71e04d349a.jpeg)

**Comment by jhreis** [comment]
It would probably be helpful to link to these settings in the actual settings page. The fact that we have two different forms of settings is pretty weird. We even have a settings menu called "Brave Rewards" and almost nothing is in it.

**Comment by kylehickinson** [comment]
@jhreis There actually is a button now (in 1.15 I believe) in that page that opens up the panel with settings already open

**Comment by jhreis** [comment]
@jamesmudgett @karenkliu Any additional thoughts / concerns about this?

**Comment by m-henderson** [comment]
why don't we just put a 1px solid border around it with some padding? It will look like a button.  We can add some border radius to make it nice and round on the edges just like this button: 
![image](https://user-images.githubusercontent.com/16070192/77723479-92779000-6fbe-11ea-99a4-0aeb77674cce.png)

**Comment by Brave-Matt** [comment]
☝️This is pretty much verbatim the solution I suggested when I was originally talking to @anthonypkeane about the button.

**Comment by andrewalisa** [comment]
@m-henderson : I completely support your idea!

**Comment by anthonypkeane** [comment]
ping @jamesmudgett for a final design on this

**Comment by kylehickinson** [comment]
Closed as this feature is no longer supported in new Rewards on Brave iOS
