### ISSUE TITLE
NTP SI - sponsored logo/text can appear stretched

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#2395]
### Description: 
Possibly related to https://bravesoftware.slack.com/archives/CQGTGBNH1/p1581533453300100

Sometimes the sponsored logo/text can appear stretched.

### Steps to Reproduce 
  1. Launch dev build
  2. View NTP SI

**Actual result:** 
Sometimes logo/text appears stretched
https://bravesoftware.slack.com/archives/CQGTGBNH1/p1583422369119100?thread_ts=1583377963.114300&cid=CQGTGBNH1

https://bravesoftware.slack.com/archives/CQGTGBNH1/p1581531805286500

**Expected result:**
logo/text should not appear stretched

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.15 (20.03.05.13)

**Device details:** 
iPad 5th Gen iOS12 and iPad mini iOS13

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
This is something we should fix, but is actually an issue with the images that are being used. The spec stated that all images would be square, yet, not always the case.

Still something we should fix.
