### ISSUE TITLE
Review prompt setting

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2399]
### Description: 

As part of 5.6.1 App Store Reviews (https://developer.apple.com/app-store/review/guidelines/) we now need a setting where users can turn off Review prompt

@karenkliu you please include this in your updated Shield design? 

![Screen Shot 2020-03-05 at 14.30.03.png](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/df96bc1f-109d-4f81-8721-31be942b2bf8)

**Comment by karenkliu** [comment]
@anthonypkeane Not sure what you mean - currently we don't have a review prompt, only an item in Settings that will take users to the App Store to write their review:
<img width="557" alt="Screen Shot 2020-03-05 at 5 35 11 PM" src="https://user-images.githubusercontent.com/2388823/76041803-f3540100-5f07-11ea-8e62-6e229a002698.png">

**Comment by anthonypkeane** [comment]
@karenkliu we do have a review prompt. https://github.com/brave/brave-ios/pull/873

@kylehickinson 
As I read this revision to the guidelines, we need to have a setting that allows user to switch off the review prompt. Currently users cannot disable this 3 times per year prompt.

**Comment by jhreis** [comment]
@anthonypkeane I don't see anything in the above snippet that suggests we should have a setting for this.

**Comment by anthonypkeane** [comment]
ok, my bad. closing
