### ISSUE TITLE
Issue claiming rewards vs the NTP

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2400]
### Description: 
Pressing the "claim my reward" button on this screen didn’t do anything

![Claim.jpg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/71a9d46c-c73e-4d85-8bed-0a66dd783a35)

V1.15 
iOS13
iPhone Xs

**Comment by cconcannon** [comment]
I'm getting an error message that could be related when I click the "claim" button here
![brave_error](https://user-images.githubusercontent.com/16453494/83357214-d5881380-a31f-11ea-9b80-b5725e7d7389.png)

**Comment by NejcZdovc** [comment]
@anthonypkeane is this still the problem?

**Comment by iccub** [comment]
It was some server side issue, nothing with UI.
Closing but please reopen if still valid
