### ISSUE TITLE
Padding between text and buttons increase when going back from pending contribution window

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2403]
### Description: 
Padding between text and buttons increase when going back from pending contribution window

### Steps to Reproduce 
  1. Tip a unverified publisher
  2. Open panel and open rewards summary
  3. Tap on pending contributions
  4. Go back to previous screen
  5. Buttons and text have extra padding

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/76312023-30e5cf00-62f8-11ea-96d2-c73228b1e5d5.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/17010094/76312041-37744680-62f8-11ea-8c47-e69dea0156a2.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.14.3 and 1.15 & 1.15.1

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

**Comment by kylehickinson** [comment]
Closed as this feature is no longer supported in new Rewards on Brave iOS
