### ISSUE TITLE
Tabs bar become dark when scrolling up

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2404]
### Description: 
Tabs bar become dark when scrolling up

### Steps to Reproduce 
  1. Install 1.15.1 
  2. Open a bunch of tabs 
  3. Scroll up on one of the tab, entire tabs bar becomes dark

**Actual result:** 
![RPReplay-Final1583811157](https://user-images.githubusercontent.com/17010094/76478629-532e3880-642f-11ea-9408-d7a20ceee5cc.gif)

**Expected result:**
Not what is happening

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.15.1

**Device details:** 
iPhone 7+

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

**Comment by elemanhillary** [comment]
@srirambv i would like to take this

**Comment by jhreis** [comment]
@elemanhillary you have been assigned, let me know if you need anything.

@srirambv Can you please provide the actual result _in the ticket_ (or a public URL at least)?

**Comment by srirambv** [comment]
updated

**Comment by elemanhillary-zz** [comment]
did i get unassigned this or something else happened

**Comment by srirambv** [comment]
![image](https://user-images.githubusercontent.com/17010094/76598001-d7fc7d80-6527-11ea-8eb7-959045c73faf.png)
Looks like you removed it. I reassiged the issue to you

**Comment by elemanhillary-zz** [comment]
or okay thanks, how the F, did i do that. Sorry for the F

**Comment by elemanhillary-zz** [comment]
am building it from source, @srirambv how do i build 1.15.1

**Comment by jhreis** [comment]
@elemanhillary follow the read me instructions on the main github page (or in repo). If you run into any issues, please reach out via [community](https://community.brave.com/c/contributing/contributing-ios/25), or if there is a bug with the process, you can file a GH ticket.

**Comment by iccub** [comment]
stale, we have a smooth transition now
