### ISSUE TITLE
Display bookmarks sorted

### ISSUE THREAD

**Issue by sanoodles** [brave/brave-ios#2407]
## Problem Description 

Can't find bookmarks nor bookmark folders because their order seems random, plus there is no search functionality

## Feature Overview 

By default, display bookmarks sorted in some human-recognizable way

## Design 

By default, display bookmarks sorted by addition date

## User Experience 

   1. Click on the Bookmarks menu item
   2. The Bookmarks list is displayed, with the bookmarks and also bookmarks folders sorted by addition date (ascending or descending, I don't care)

**Comment by iccub** [comment]
That's a sync problem, this should be fixed once sync v2 is shipped, hopefully soon.
When sync is not enabled, bookmarks are sorted by creation date, you can also reorder them easily
