### ISSUE TITLE
Animations fail to load on https://www.apple.com/macbook-air/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-ios#2415]
### Description: 
Visiting `https://www.apple.com/macbook-air/` doesn't show the animations

### Steps to Reproduce 
  1. Visit `https://www.apple.com/macbook-air/`
  2. Expecting animations to work on site when you scroll down
  3.

**Actual result:** 
No Animations of the Macbook

**Expected result:**
Animations to load

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.15 (20.03.05.14)

**Device details:** 
iPhone 8Plus

**Website problems only:**
- did you check with Brave Shields down? Yes
- did you check in Safari/Firefox (WkWebView-based browsers)?  Yes (Safari works)

### Additional Information
Turning off Fingerprinting will resolve this.   

1 Fingerprint originating from `www.apple.com`

**Comment by jhreis** [comment]
Based on private convos, it appears this is an issue with fingerprint protection.

**Comment by iccub** [comment]
Seems to work now
