### ISSUE TITLE
Updating Package-Lock.json

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#2423]
### Description: 
- `https://github.com/brave/brave-ios/network/alert/package-lock.json/minimist/open`
- Just related to outdated libraries being used across all platforms for millions of applications.
- We updated the packages so we need to make sure stuff still works.

### Steps to Reproduce 
  1. N/A

**Expected result:**
- Sync should work

**Brave Version:** 
- All

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15.1(20.04.07.18)
- Verified sync between iPhone XR  <--> Desktop (1.8.69) works fine. Adding/removing/reordering/editing bookmarks on both devices propagate correctly
- Verified sync between iPhone XR <--> Android (1.5.131) works fine. Adding/Removing/Reordering/Editing bookmarks on both devices propagate correctly  
- Verified sync between iPhone XR <-->  iPhone 7+(1.15.1) works fine. Adding/Removing/Reordering/Editing bookmarks on both devices propagate correctly  
- Verified stats are retained when sync is enabled
- Verified stats are retained when sync is reset 
------------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15.1(20.04.07.18)
- Verified sync between iPhone 7+  <--> Desktop (1.8.69) works fine. Adding/removing/reordering/editing bookmarks on both devices propagate correctly
- Verified sync between iPhone 7+ <--> Android (1.5.131) works fine. Adding/Removing/Reordering/Editing bookmarks on both devices propagate correctly  
- Verified sync between iPhone 7+ <-->  iPad Pro (iOS 13.3.1) (1.15.1) works fine. Adding/Removing/Reordering/Editing bookmarks on both devices propagate correctly  
- Verified stats are retained when sync is enabled
- Verified stats are retained when sync is reset 
------------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15.1(20.04.07.18)
- Verified sync between iPad Pro  <--> Desktop (1.8.72) works fine. Adding/removing/reordering/editing bookmarks on both devices propagate correctly
- Verified sync between iPad Pro <--> Android (1.5.131) works fine. Adding/Removing/Reordering/Editing bookmarks on both devices propagate correctly  
- Verified sync between iPad Pro <-->  iPhone 7+(1.15.1) works fine. Adding/Removing/Reordering/Editing bookmarks on both devices propagate correctly  
- Verified stats are retained when sync is enabled
- Verified stats are retained when sync is reset
------------
Verification passed on iPad Pro with iOS 12.4.5 running 1.15.1(20.04.07.18)
- Verified sync between iPad Pro  <--> Desktop (1.8.72) works fine. Adding/removing/reordering/editing bookmarks on both devices propagate correctly
- Verified sync between iPad Pro <--> Android (1.5.131) works fine. Adding/Removing/Reordering/Editing bookmarks on both devices propagate correctly  
- Verified sync between iPad Pro <-->  iPhone XR (1.15.1) works fine. Adding/Removing/Reordering/Editing bookmarks on both devices propagate correctly  
- Verified stats are retained when sync is enabled
- Verified stats are retained when sync is reset 
 ------------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15.1(20.04.07.18)
- Verified sync between iPhone 6 <--> Desktop (1.8.69) works fine. Adding/removing/reordering/editing bookmarks on both devices propagate correctly
- Verified sync between iPhone 6 <--> Android (1.5.131) works fine. Adding/Removing/Reordering/Editing bookmarks on both devices propagate correctly  
- Verified sync between iPhone 6 <-->  iPad Pro (iOS 13.3.1) (1.15.1) works fine. Adding/Removing/Reordering/Editing bookmarks on both devices propagate correctly  
- Verified stats are retained when sync is enabled
- Verified stats are retained when sync is reset
