### ISSUE TITLE
DB Migrates when not needed after resetting Rewards

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2432]
### Description: 

If the user freshly installs Brave which doesn't migrate any data, then resets Rewards via the Rewards Debug menu, the following launch will migrate the empty CoreData database incorrectly

### Steps to Reproduce 
  1. Install fresh, enable rewards
  2. Claim a grant
  3. Go to debug menu, switch environment or reset rewards

**Actual result:** 
- DB is migrated again, grants disappear

**Expected result:**
- DB should not migrate

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
1.15.1

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.5.15(20.04.07.18)
- Verified DB migration is not done after switching the environment
------
Verification passed on iPad Pro with iOS 13.3.1 running 1.5.15(20.04.07.18)
- Verified DB migration is not done after switching the environment
------
Verification passed on iPhone XR  with iOS 13.4 running 1.5.15(20.04.07.18)
- Verified DB migration is not done after switching the environment
------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.5.15(20.04.07.18)
- Verified DB migration is not done after switching the environment
------
Verification passed on iPad Pro with iOS 12.4.5 running 1.5.15(20.04.07.18)
- Verified DB migration is not done after switching the environment
------
