### ISSUE TITLE
Update UI for error for SKUs

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#2438]
### Description: 

Current SKU workflow presents this modal once the API completes: 

![Screen Shot 2020-04-01 at 10 53 10 AM](https://user-images.githubusercontent.com/1903815/78171892-045e3800-740a-11ea-829b-230ee90f6f30.png)

For SKUs we have these error flows: look forr  `Pay with BAT` spec

We need a new modal if there is an error.

**Comment by iccub** [comment]
closing as stale
