### ISSUE TITLE
Remove Unnecessary Shared Schemes

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#2447]
### Description: 

Currently Xcode is syncing a bunch of schemes, most of these can be removed. Reduce down to just the main four targets:

- Debug
- Dev
- Beta
- Release

![A list of a bunch of Xcode shared schemes](https://user-images.githubusercontent.com/2781690/78587762-6d2f2100-780b-11ea-885e-5103bcc3ffc0.png)

**Comment by iccub** [comment]
Let's bump
