### ISSUE TITLE
One time tips shows up as 0 after DB migration

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2450]
### Description: 
One time tips shows up as 0 after DB migration

### Steps to Reproduce 
  1. Install 1.15 and enable rewards on staging
  2. Claim grant and tip a couple of verified pubs and set recurring tips
  3. Upgrade to 1.15.1   
  4. Open rewards panel and go to one time tips, shows 0 for all one time tips sent 

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/78665311-3cc2b200-78f3-11ea-85cb-739f32e450d0.png)
![image](https://user-images.githubusercontent.com/17010094/78665944-397bf600-78f4-11ea-81f5-fab653250c67.png)

**Expected result:**
Should retain one time tips value that is sent

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.15.1

**Device details:** 
iPhone XR

**Website problems only:**
- did you check with Brave Shields down? na
- did you check in Safari/Firefox (WkWebView-based browsers)? na

### Additional Information
Found while testing  #2378
cc: @kylehickinson

**Comment by kylehickinson** [comment]
@srirambv please attach your database that was migrated (can export via rewards debug menu)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15.1(20.04.07.18)
- Verified one time tips shows correct value after DB migration
---------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15.1(20.04.07.18)
- Verified one time tips shows correct value after DB migration
--------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15.1(20.04.07.18)
- Verified one time tips shows correct value after DB migration
--------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15.1(20.04.07.18)
- Verified one time tips shows correct value after DB migration
--------
Verification passed on iPad Pro with iOS 12.4.5 running 1.15.1(20.04.07.18)
- Verified one time tips shows correct value after DB migration
--------
