### ISSUE TITLE
AC contribution message show 0.0 BAT contributed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2451]
### Description: 
AC contribution message show 0.0 BAT contributed

### Steps to Reproduce 
  1. Install 1.15 and enable rewards
  2. Claim grant and add a few pubs to the AC list
  3. Send a one time tip to a verified pub
  4. Set recurring tip to a verified pub
  5. Upgrade to 1.15.1 and trigger contribution
  6. AC message shows 0.0 BAT

**Actual result:** 
AC contribution message show 0.0 BAT contributed

**Expected result:**
Should show the contribution amount correctly 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.15.1(20.13.31.15)

**Device details:** 
iPhone XR (iOS 13.4)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
Found while testing  #2378
cc: @kylehickinson

**Comment by kylehickinson** [comment]
@srirambv Please attach database for all DB migration tickets

**Comment by srirambv** [comment]
DB files available here https://drive.google.com/file/d/1zEl-Y9YCvrXPo15zCbwLGfJdtVPN_xH-/view?usp=sharing

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4 running 1.15.1(20.04.07.15)
- Verified AC contribution shows correct BAT value contributed after DB migration
---------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.15.1(20.04.07.18)
- Verified AC contribution shows correct BAT value contributed after DB migration
--------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.15.1(20.04.07.18)
- Verified AC contribution shows correct BAT value contributed after DB migration
--------
Verification passed on iPad Pro with iOS 13.3.1 running 1.15.1(20.04.07.18)
- Verified AC contribution shows correct BAT value contributed after DB migration
--------
Verification passed on iPad Pro with iOS 12.4.5 running 1.15.1(20.04.07.18)
- Verified AC contribution shows correct BAT value contributed after DB migration
