### ISSUE TITLE
Not using official 1Password extension repo

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2455]
Due to 1P taking a lot of time with migrating codebase to swift5 and/or UIWebView deprecation we had to use `Sidetalker/onepassword-app-extension` fork for the time being

Now since this PR was merged https://github.com/agilebits/onepassword-app-extension/pull/419
We can go back to using official repo again.

This should be tested by qa just to make sure it still works.

**Comment by iccub** [comment]
Related ticket

#1524

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.4.5 running 1.16(20.04.30.17)
- Verified able to auto-fill data using 1Password as auto-fill manager
-------
Verification passed on iPhone 7+ with iOS 13.3.1 running 1.16(20.04.30.17)
- Verified able to auto-fill data using 1Password as auto-fill manager
-------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.16(20.04.30.17)
- Verified able to auto-fill data using 1Password as auto-fill manager
-------
Verification passed on iPad Pro with iOS 13.4.5 running 1.16(20.04.30.17)
- Verified able to auto-fill data using 1Password as auto-fill manager
-------
Verification passed on iPad Pro with iOS 12.4.5 running 1.16(20.04.30.17)
- Verified able to auto-fill data using 1Password as auto-fill manager
-------
