### ISSUE TITLE
Finalize Copy

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#246]
Copy across entire application must be finalized.

- [ ] Get finalized strings for entire application from design
- [ ] Add in new copy

**Comment by tmancey** [comment]
@anthonypkeane Blocked as need final Copy from design

**Comment by anthonypkeane** [comment]
Update: 

@srirambv will go through and audit the entire app to verify strings are good or places that need modifications. All menus, button options, descriptions, etc

Once 1.7/v2  is ready, please share it with @srirambv and @anthonypkeane and this task can kick off. Thanks

**Comment by anthonypkeane** [comment]
@jhreis  and @tmancey , if you guys can provide a final .strings file, I can move forward with getting the missing strings and getting the .strings file translated. We should make sure there is no (or minimal) strings from V1.6 so we are not translating words we won’t use. 

cc @srirambv

**Comment by jhreis** [comment]
@anthonypkeane not sure a massive, random strings file is the best way to audit the app's string usages. It will probably be more necessary to go through the entire app and validate the strings in English that way. We can still provide a strings file, may just be hard without any context.

**Comment by tmancey** [comment]
@jhreis @anthonypkeane I would recommend string `comments` are first updated/added for every string after running the `clean-nslocalizedstrings` script so translators have a better context as to the use of each string.
