### ISSUE TITLE
[hackerone] javascript: security isssue

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-ios#2463]
see https://hackerone.com/reports/846152 or ask yan for details

## Test Plan
Specified here: https://github.com/brave/brave-ios/pull/2550

**Comment by diracdeltas** [comment]
discussed in Slack, decided solution was just to strip javascript: from the URL bar when pasting

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.17(20.5.21.17)
- Verified test plan from https://github.com/brave/brave-ios/pull/2550
--------
Verification passed on iPhone 7+ with iOS 13.4.5 running 1.17(20.5.21.17)
- Verified test plan from https://github.com/brave/brave-ios/pull/2550
--------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.17(20.5.21.17)
- Verified test plan from https://github.com/brave/brave-ios/pull/2550
--------
Verification passed on iPad Pro with iOS 13.4.5 running 1.17(20.5.21.17)
- Verified test plan from https://github.com/brave/brave-ios/pull/2550
--------
Verification passed on iPad Pro with iOS 12.4.5 running 1.17(20.5.21.17)
- Verified test plan from https://github.com/brave/brave-ios/pull/2550
--------
