### ISSUE TITLE
verified YouTube publisher does not display correctly on panel, ac list, tip list, etc

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#2466]
### Description: 
When you go to open the panel for a verified YouTube publisher, only "on YouTube" displays instead of "Jonathan Sampson on YouTube". If this publisher gets added to the auto contribute list, or a tip list, still only "on YouTube" is displayed instead.

Note - if the publisher is not verified, there is no issue, YouTube channel displays as expected.

### Steps to Reproduce 
  1. Launch Brave, skip onboarding, set env to Staging. Restart the browser as directed.
  2. Enable Rewards, claim staging grant.
  3. Navigate to YouTube.
  4. Search for "Jonathan Sampson"
  5. Open his channel page
  6. Tap on a video to start playing one.
  7. Open panel --> See only "on YouTube"
  8. Open tip banner --> see only "on YouTube" in header.
  9. Tip publisher --> Thank you banner only shows "on YouTube"
  10. View AC table, tips tables, etc --> only "on YouTube" displays.

**Actual result:** 
(ignore balance, the screenshots are from different tests)
![IMG_0472](https://user-images.githubusercontent.com/28145373/79455293-a8271680-7fba-11ea-84ee-778b9b270925.PNG)
![IMG_0473](https://user-images.githubusercontent.com/28145373/79455307-ac533400-7fba-11ea-8155-295296e30545.PNG)
![IMG_0474](https://user-images.githubusercontent.com/28145373/79455323-b07f5180-7fba-11ea-9ab7-026711b62425.PNG)

**Expected result:**
Verified pub name should be displayed like unverified pub name is
![IMG_0476](https://user-images.githubusercontent.com/28145373/79455355-bc6b1380-7fba-11ea-915b-27848f92745e.PNG)
![IMG_0477](https://user-images.githubusercontent.com/28145373/79455360-be34d700-7fba-11ea-988a-ff4a71df7550.PNG)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily, 100%

**Brave Version:** 
1.15 (current app store version)
1.15.1 

**Device details:** 
iPad 5th gen iOS12

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc @brave/legacy_qa

**Comment by NejcZdovc** [comment]
closing in favour of https://github.com/brave/brave-ios/issues/1673
