### ISSUE TITLE
barrons promotion tab not being opened when downloading brave via promotion page

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2471]
### Description: 

Same issue occurring on both Android/iOS as per https://github.com/brave/brave-browser/issues/9287.

`Barrons` promotion tab isn't being opened when downloading Brave via https://brave.com/dowjones-barrons. However, `MW` via https://brave.com/dowjones-marketwatch seems to be working without any issues.

### Steps to Reproduce 

**`NOT WORKING`**

   1. download/install Brave via https://brave.com/dowjones-barrons using the `App Store`
   2. you'll notice that once Brave starts, the `barrons` promotional tab isn't being opened

**`WORKING`**

   1. download/install Brave via https://brave.com/dowjones-marketwatch using the `App Store`
   2. you'll notice that once Brave starts, the `MW` promotional tab isn't being opened

**Actual result:** 

`Barrons` promotion tab is not being opened once Brave is launched after installing from https://brave.com/dowjones-barrons

**Expected result:**

`Barrons` promotion tab should be opened once Brave is launched after installing from https://brave.com/dowjones-barrons

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible when using the above STR.

**Brave Version:** 

* `1.15 (20.03.05.14)` - **Reproducible**
* `1.15.1 (20.04.07.18)` - **Reproducible**

**Device details:** 

* `iPhone 11` running `iOS 13.4.1` - **Reproducible**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @rebron @bsclifton @mandar-brave

**Comment by iccub** [comment]
closing as stale
