### ISSUE TITLE
App is getting slower when using, probably memory leak

### ISSUE THREAD

**Issue by surmacz** [brave/brave-ios#2472]
Brave on iPad is freezing a lot, for example on youtube.com, when I run some videos and scroll down to comments, it freezes for couple of seconds.
Restart of the app helps for couple of minutes.

Also after the restart, the state of tabs is different than before, some tabs which was closed before appear again, some have different addresses.

IPad os: 13.4.1
Model: iPad Pro 3gen
Brave: 1.15 (20.03.05.14)

**Comment by iccub** [comment]
closing as stale for now, we added bunch of improvements since this ticket was created,
Brave 1.32.1 has a nice performance fix for users using Rewards on iOS
