### ISSUE TITLE
Recommend them to add frequently visiting sites to bookmark

### ISSUE THREAD

**Issue by chkk525** [brave/brave-ios#2474]
## Feature Overview 
- Encourage users to add repeat visits to their favorites.
- This is intended to help people migrate from traditional browsers to Brave.

## Implementation Details 

##User Experience 

   1. User visits a site X times
   2. A badge appears above the menu button
   3. Encourage them to use "Add to Bookmark" menu.

**Comment by iccub** [comment]
We want to add both frequent sites and favorites on NTP, should cover this case, closing this one for now
