### ISSUE TITLE
Accessing the JS console

### ISSUE THREAD

**Issue by tdurieux** [brave/brave-ios#2475]
Hello,

My website is not working properly on brave-ios (it is working fine on other ios browser or in brave desktop), and I would like to access the console to see what is happening. I did not find any documentation in this repo or online to do so.

Is it possible to access the JS logs?

Thanks

ps: sorry for not respecting the template

**Comment by iccub** [comment]
Sorry for late reply, not possible unless you build the app by yourself run it via XCode and access your website from Safari on Mac

**Comment by tdurieux** [comment]
There is no plan to add this in brave?

**Comment by markhicken** [comment]
I'm experiencing a bug where things work fine on Brave desktop but not on iOS. As a developer, I can't target Brave, if I can't even debug it. This should really be reopened and prioritized.

**Comment by taishi55** [comment]
@markhicken I'm also having the same issue. My app works fine on Safari (IOS), but it is not on Brave (IOS). I tested on Brave (Desktop) and that works fine too.

**Comment by dgrebb** [comment]
[_This is the way..._](https://github.com/brave/brave-ios/issues/7425)
