### ISSUE TITLE
[security] audit all calls of webview.evaluateJavascript for XSS

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-ios#2480]
we seem to be doing many calls of webview.evaluateJavaScript that take dynamic input. we need to make sure none of them can lead to XSS.

in the future we should consider replacing all these calls with something safer, as Firefox is doing. for instance an interface that only takes a function + JSON arguments to evaluate in a webview context.

**Comment by diracdeltas** [comment]
Noting that this has already caused one severe security issue: https://github.com/brave/brave-ios/issues/2921

**Comment by jumde** [comment]
Should be addressed by: https://github.com/brave/brave-ios/issues/2957
