### ISSUE TITLE
Remains a blank page while loading.

### ISSUE THREAD

**Issue by chkk525** [brave/brave-ios#2484]
### Description: 
- Sometimes, it remains on a blank page when opening a page
- It happens when clicking a link in a page, or trying to reload a page

### Steps to Reproduce 
Not sure how to reproduce but seems to be happening on relatively older devices (6s or 7)

  1. 
  2.
  3.

**Actual result:** 
- Remain on a blank page until reloading again

**Expected result:**
- Open the page 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
- A reporter says it happens "often"

**Brave Version:** 
- v1.15

**Device details:** 
- iPhone 6s

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Should be fixed by this https://github.com/brave/brave-ios/issues/2635
