### ISSUE TITLE
Incorrect favicon is shown for few verified publishers in AC table

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#2485]
### Description: 
Incorrect favicon is shown for a few verified publishers

### Steps to Reproduce 
  - Install 1.15
 - Enable reward and add sites to ac list so rewards db is populated
 - Upgrade to 1.15.2
 - Disconnect network
 - Launch browser and add custom UA 
 - Relaunch network and open rewards panel and click on refresh status on the existing page
 - No browser lag or hang 
 - All verified pub showed verified check on BR panel 
 - Incorrect favicon is shown for few verified publishers in AC table 

**Actual result:** 
Incorrect favicon is shown for few verified publishers in AC table

![image](https://user-images.githubusercontent.com/38657976/80126031-1e75db00-85b0-11ea-9454-49044ca5bd8f.png)

Open and close BR panel shows the favicons as below:
![IMG_0376](https://user-images.githubusercontent.com/38657976/80126069-30577e00-85b0-11ea-8006-3cfc583babfb.PNG)
![IMG_0377](https://user-images.githubusercontent.com/38657976/80126073-32214180-85b0-11ea-9642-ad4efe254337.PNG)

**Expected result:**
The correct favicon should be shown for all the verified publishers in AC table

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Always
**Brave Version:** 
1.15.2

**Device details:** 
iPhone 8 - 13.3.1

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @brave/legacy_qa @kylehickinson

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.18(20.06.24.15)
- Verified steps from issue description 
-------
Verification passed on iPhone 7+ with iOS 13.5.1 running 1.18(20.06.24.15)
- Verified steps from issue description 
-------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.18(20.06.24.15)
- Verified steps from issue description 
-------
Verification passed on iPad Pro with iOS 13.6 running 1.18(20.06.24.15)
- Verified steps from issue description 
-------
Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.06.24.15)
- Verified steps from issue description 
-------
