### ISSUE TITLE
auto contribute list slow to display in UI after update

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#2486]
### Description: 
When testing #2476 and #2477 I noticed that my auto contribute list was slow to display in the UI. Not sure if it is due to the database migration (https://github.com/brave/brave-ios/issues/2378) or something else.

### Steps to Reproduce 
  1. Install 1.15
  2. Enable rewards and add sites to ac list so rewards db is populated (I had 5-8 sites each time I tried this, a mix of sites that would and would not become verified in step 6)
  3. Upgrade to 1.15.2
  4. Disconnect network
  5. Launch browser and add custom UA 
  6. Relaunch network and open rewards panel and click on refresh status on the existing page
  7. No browser lag or hang while console showed "OnDownload" request
  8. Tap on BAT logo and navigate to Auto Contribute details.
--> `Supported sites` says 0. Wait a minute or two (stay on panel), it will update to the expected number
--> Tap on `Supported sites` to view the list (to confirm sites on the list have their verified icon as expected per step 2), list is blank. Again, wait a minute or two with panel open, eventually it will update to show your AC list.

**Actual result:** 
AC list is slow to display in the UI

**Expected result:**
no slowness

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.15.2(20.04.22.20)

**Device details:** 
iPad 5th Gen w/ iOS12
iPad mini w/ iOS13

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc @srirambv as he saw this as well

**Comment by kylehickinson** [comment]
@LaurenWags This is because the server publisher list is inserting large batches of publishers into the DB and therefore keeping DB interactions busy. The UI will still be usable, but the data may take a minute or two to show up

**Comment by LaurenWags** [comment]
gotcha, thanks @kylehickinson - if this is expected I guess we can close this one? wdyt?

**Comment by kylehickinson** [comment]
I think possibly the best we could do is maybe add a loader, but given we are looking towards not doing these huge DB inserts in the near future with pub list v4 I think its probably not worth it.

**Comment by LaurenWags** [comment]
Maybe we leave this open until we get to that point and once v4 is implemented, we can confirm we don't still see this issue?

**Comment by kylehickinson** [comment]
Sounds good to me!
