### ISSUE TITLE
Redirecting AMP to canonical pages.

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#2489]
## Problem Description 

Disable AMP urls. Whether default on / off tbd:
See: https://github.com/brave/brave-browser/issues/8720

## Feature Overview 

See linked ticket

## Design 

Probably just a settings switch.

## Implementation Details 

##User Experience 

See linked ticket

**Comment by iccub** [comment]
closing in favor of the newer ticket https://github.com/brave/brave-ios/issues/4219
