### ISSUE TITLE
http://localhost:6571/about/home shown for tab title while loading

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#249]
### Steps to Reproduce 

Pre-requisite: Use network link conditioner to slow the internet connection to a very slow speed

  1. Navigate to badssl.com

**Actual result:** http://localhost:6571/about/home is shown for the tab title while loading

**Expected result:** badssl.com should be shown for the tab title while loading

**Reproduces how often:** Every time

**Brave Version:** Development build hash 703c831f1c2194e3098be6c6758dc9566a3ec460

**Device details:** iPhone 8 Plus, iOS 11.4.1

### Additional Information 

Once page has finished loading the correct title is shown

<img width="1013" alt="loaded" src="https://user-images.githubusercontent.com/1188719/45417941-42a2d380-b67b-11e8-9f3f-b1623d9eabc3.png">
<img width="1013" alt="loading" src="https://user-images.githubusercontent.com/1188719/45417942-42a2d380-b67b-11e8-87c5-50d71413b782.png">

**Comment by srirambv** [comment]
This looks similar to https://github.com/brave/browser-ios/issues/1657. Does the same fix work for both?

**Comment by tmancey** [comment]
@srirambv They could be related but separate issues as this issue is related to the Tab title and the other issue is related to the Address Bar

**Comment by kylehickinson** [comment]
This is partially fixed by #276, where it will no longer show `localhost` URL's. However the fact is it still shows "New Tab" until the website loads instead of the url.

**Comment by tmancey** [comment]
@jamesmudgett @anthonypkeane Can you please confirm if the above from @kylehickinson is an acceptable solution? If so, then I can close the ticket with a label of `won't fix`

**Comment by anthonypkeane** [comment]
@jamesmudgett I recommend don't fix and go with @kylehickinson solution. If you agree comment here and @tmancey can close the ticket

**Comment by jamesmudgett** [comment]
I agree, @kylehickinson's solution works.
