### ISSUE TITLE
Strip the referrer entirely on cross-origin navigation requests and iframe sub-resources

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#2494]
From: https://github.com/brave/brave-browser/issues/3422

**Comment by fmarier** [comment]
Our [behavior on Desktop](https://github.com/brave/brave-browser/wiki/Deviations-from-Chromium-(features-we-disable-or-remove)#modified-features-and-functionality) is a bit more complicated than what can fit in the issue title, and it is also [in the middle of changing](https://github.com/brave/brave-browser/issues/8696).

However, currently on iOS, we don't spoof or strip the referrer in any way as can be seen on https://fmarier.github.io/brave-testing/referrer-spoofing.html.

**Comment by fmarier** [comment]
Given that we've aligned with Safari (capping the referrer to `strict-origin-when-cross-origin`), I think we can close this.

Would be good to give it a quick test first using the test pages we use in brave-core:
- https://fmarier.github.io/brave-testing/referrer-spoofing.html
- https://referrer.fmarier.org/redirects.html
- https://referrer.fmarier.org/samesite.html.
- https://dev-pages.brave.software/referrer/index.html
- https://fmarier.com/referrer/strict-origin.html

**Comment by jumde** [comment]
Verified on 1.23.1 - all tests look good.
