### ISSUE TITLE
Remove Firefox "Total trackers blocked" menu

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#250]
Remove Firefox "Total trackers blocked" menu

![Screen_Shot_2018-09-12_at_11_15_18.png](https://images.zenhubusercontent.com/5b6d3c6c9f47d341e6ea7783/1a3741ba-2829-4baa-8919-a1508769f6e7)

**Comment by kylehickinson** [comment]
This has already been removed post URL bar/toolbar UI parity. Unless you mean to remove the underlying code?

**Comment by tmancey** [comment]
Already resolved in the latest development build
