### ISSUE TITLE
Background images type option should be disabled when Show background images is disabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2500]
### Description: 
Background images type option should be disabled when Show background images is disabled

### Steps to Reproduce 
  1. Install a SR build
  2. Disable `Show Background Images` under New Tab page options
  3. `Background Images` type is still enabled and selectable 

**Actual result:** 
Background images type option should be disabled when Show background images is disabled

**Expected result:**
Should hide image types option

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.16

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by anthonypkeane** [comment]
@jamesmudgett see: https://docs.google.com/document/d/1DlCHfQXZS3MamKnjCkEHC7yMyJfNObKlgE9X-tJhuEc/edit?disco=AAAAGd5ulIE

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 beta running 1.16(20.05.05.12)
- Verified disabling background images causes the image type selection to be hidden
-------
Verification passed on iPhone 7+with iOS 13.3.1 running 1.16(20.05.05.12)
- Verified disabling background images causes the image type selection to be hidden
-------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.16(20.05.05.12)
- Verified disabling background images causes the image type selection to be hidden
-------
Verification passed on iPad Pro with iOS 13.4.5 running 1.16(20.05.05.12)
- Verified disabling background images causes the image type selection to be hidden
-------
Verification passed on iPad Pro with iOS 12.4.5 running 1.16(20.05.05.12)
- Verified disabling background images causes the image type selection to be hidden
-------
Logged #2516  as a follow up
