### ISSUE TITLE
Update Rewards Balance Report Fetch

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2512]
Related PR: https://github.com/brave/brave-core/pull/5417

The balance report data will be placed within the DB rather than file, this means that we cannot rely on a non-escaping closure for grabbing current months balance report.

Will need to update logic in Brave Rewards UI to account for this.

## Test Case:

- Verify that after tipping/claiming grants/etc. That the main rewards panel displays the correct values in the monthly report

**Comment by NejcZdovc** [comment]
putting in 1.20 as we landed 5417 in 1.11 on desktop

**Comment by anthonypkeane** [comment]
QA will handle this with manual passes
