### ISSUE TITLE
error displayed on pages where twitch stream isn't live

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#2517]
### Description: 
If I navigate to a page where a twitch stream isn't live, I get an error in the area where the video should be. I can still navigate to a video by that streamer and play it though. If I navigate to a page where the twitch stream is live, there's no error.

I can only reproduce this on iOS13 iPad, I cannot reproduce on iOS12 iPad. I can't reproduce this on Safari on either device, UAs are different as well.

### Steps to Reproduce 
  1.  Clean install.
  2. Skip onboarding.
  3. Navigate to twitch.tv/adobe (note, I am not redirected to a mobile page)

**Actual result:** 
![adobe](https://user-images.githubusercontent.com/28145373/81184812-d9be4c80-8f7e-11ea-8920-9547db3a6f13.jpeg)

**Expected result:**
![Image from iOS](https://user-images.githubusercontent.com/28145373/81184878-ee9ae000-8f7e-11ea-9157-b6d7a941b28b.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily for me

**Brave Version:** 
1.16 (20.05.04.12)
1.15.2 (20.04.23.16) - current released build

**Device details:** 
iPad mini iOS13

**Website problems only:**
- did you check with Brave Shields down? yes
- did you check in Safari/Firefox (WkWebView-based browsers)?  yes

### Additional Information
Unable to reproduce with iOS12 iPad, unable to reproduce on Safari using either iOS12 or iOS13 iPads.

Brave UA for iOS13 iPad:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
```

Safari UA for iOS13 iPad:
```
Mozilla/5.0 (iPad; CPU OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Mobile/15E148 Safari/604.1
```

**Comment by srirambv** [comment]
Not reproduced on my devices 
iPad Pro (iOS 13)
- No error message with desktop UA but just shows user offline 
![image](https://user-images.githubusercontent.com/17010094/81185792-a821a180-8fcf-11ea-9a01-37445dbfbbf7.png)
![image](https://user-images.githubusercontent.com/17010094/81185830-b4a5fa00-8fcf-11ea-9cdc-0370013b88e6.png)


iPad Pro (iOS 12)
![image](https://user-images.githubusercontent.com/17010094/81185768-a0fa9380-8fcf-11ea-8f75-7752d9c6b9e3.png)
![image](https://user-images.githubusercontent.com/17010094/81185777-a3f58400-8fcf-11ea-9f69-8b2a09a069ff.png)

**Comment by iccub** [comment]
Not actionable, the website has changed since then
