### ISSUE TITLE
Shields not blocking script in iOS

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-ios#2519]
### Description: 
When opening `https://www.cnbc.com` user is greeted with an Anti-adblock message from Admiral

### Steps to Reproduce 
  1. With shields on,
  2. Opening `https://www.cnbc.com`, and scroll through some pages
  3. Anti-adblock message window will come up

**Actual result:** 
![unnamed-ios](https://user-images.githubusercontent.com/1659004/81278990-96f99300-90aa-11ea-9c77-1aaff1f7b5d1.jpg)
![unnamed-ios2](https://user-images.githubusercontent.com/1659004/81278984-95c86600-90aa-11ea-9bdc-aebf64727a35.jpg)

**Expected result:**
No ad block message, since we're blocking Admiral on other platforms we should have this blocked on iOS.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily, may need more scroll on some `cnbc.com` pages

**Brave Version:** 
1.15.2

**Device details:** 
iPhone 8 Plus, 13.3.1

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
- Android and Desktop are unaffected.
- We block the related Admiral domain `acidpigs.com` in both brave-unbreak and Easyprivacy, this is the domain calling the Anti-adblock message.
- `acidpigs.com` domain was added in 7th Feb (via this commit: https://github.com/brave/adblock-lists/pull/326 )

**Comment by kylehickinson** [comment]
Ref #2612

**Comment by kylehickinson** [comment]
I'm not seeing this in 1.18, going to add it to the milestone

**Comment by kylehickinson** [comment]
Fixed by #2612

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.18(20.06.23.18)
- Verified no anti-adblock popup shown after browsing the site for a while
- Verified no anti-adblock popup shown behind VPN as well
--------
Verification passed on iPhone 7+ with iOS 13.5.1 running 1.18(20.06.23.18)
- Verified no anti-adblock popup shown after browsing the site for a while
- Verified no anti-adblock popup shown behind VPN as well
--------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.18(20.06.23.18)
- Verified no anti-adblock popup shown after browsing the site for a while
- Verified no anti-adblock popup shown behind VPN as well
--------
Verification passed on iPad Pro with iOS 13.6 running 1.18(20.06.23.18)
- Verified no anti-adblock popup shown after browsing the site for a while
- Verified no anti-adblock popup shown behind VPN as well
--------
Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.06.23.18)
- Verified no anti-adblock popup shown after browsing the site for a while
- Verified no anti-adblock popup shown behind VPN as well
--------
