### ISSUE TITLE
Open URL in new tab causes URL to show on the page weirdly 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2521]
### Description: 
Open URL in new tab causes URL to show on the page weirdly 

### Steps to Reproduce 
  1. Open any page
  2. Long press on a link and open in new tab
  3. Link shows up on page weirdly

**Actual result:** 
https://bravesoftware.slack.com/archives/C06UXF3KJ/p1588854436015800

**Expected result:**
Should not behave like it does now 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.15.2

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

**Comment by ProgramComputer** [comment]
As of 1.25, issue is resolved.
