### ISSUE TITLE
CollectionView FRC performance fix

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2522]
So we have one tricky 1.16 crash, it is related to this problem https://stackoverflow.com/questions/20554137/nsfetchedresultscontollerdelegate-for-collectionview
basically FRC doesn’t work well with collectionview, since object updates are called one by one, unlike on table view where you can add multiple items in one batch with beginupdates-endupdates

With the upcoming NTP refactor, we should keep in mind that our temporary solution https://github.com/brave/brave-ios/pull/2520 might not be that great, and implement something better, most likely batch operation will be used, then we call them in `performBatchUpdates`

**Comment by kylehickinson** [comment]
Added batch ops here in NTP refactor: https://github.com/brave/brave-ios/commit/4a74de7aa89b2b534d00b9efc42f4cda7f4f94fa
