### ISSUE TITLE
Improve image transition on clean install when user skips onboarding

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2524]
### Description: 
Improve image transition on clean install when user skips onboarding

### Steps to Reproduce 
  1. Install CHP build
  2. Launch browser and skip onboarding
  3. Shows a black screen and then normal image loads and then SR image loads 

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/81322830-248cb100-90b2-11ea-9af4-bb0fe557e59d.png)

**Expected result:**
Have a smooth loading and image transition on clean install 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.16(20.5.7.15)

**Device details:** 
iPhone 6 (iOS 12.4.5) Lowend device

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
cc: @iccub

**Comment by iccub** [comment]
we have new onboarding now
