### ISSUE TITLE
[iOS] [Android] Update NTP Brave Stats to 'Trackers & Ads Blocked'

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-ios#2528]
### Description: 
Update NTP Brave Stat text from 'Ads and Trackers Blocked' to 'Trackers & ads blocked'

### Steps to Reproduce 
  1. Open a new tab

**Actual result:** 
![Screen Shot 2020-05-08 at 11 25 43 AM](https://user-images.githubusercontent.com/2388823/81436636-a9151900-911e-11ea-9d81-516266ae7c00.png)

**Expected result:**
![Screen Shot 2020-05-12 at 1 12 34 PM](https://user-images.githubusercontent.com/2388823/81740735-48ede200-9452-11ea-88d9-cd346c3d42af.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
all versions

**Device details:** 
n/a

### Miscellaneous
This update is expected on all platforms.
Android https://github.com/brave/brave-browser/issues/9693
Desktop https://github.com/brave/brave-browser/issues/9692

**Comment by anthonypkeane** [comment]
Why not

Trackers & Ads Blocked @karenkliu

**Comment by karenkliu** [comment]
@anthonypkeane We are moving towards Sentence case everywhere (labels, button text, titles, etc.) except for things that are already Proper Nouns. So all three of the Brave Stats numbers should use sentence case because none of them contain proper nouns.

**Comment by anthonypkeane** [comment]
That is not consistent with iOS

**Comment by karenkliu** [comment]
Apple tends to use Title Case for everything, including menu items, but the NTP is our own UI. I don't think we need to conform our capitalization in our own UI to their system text. But LMK your final call on this and I'll update the screens for this issue.

**Comment by kylehickinson** [comment]
Going to close this in favour of https://github.com/brave/brave-ios/issues/2932 which includes some other copy changes
