### ISSUE TITLE
Estimated Ads payout missing

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2531]
### Description: 
A UI bug is causing the estimated ads payout amount to not show up in latest version (1.16)

![image](https://user-images.githubusercontent.com/529104/81484011-397f5680-9210-11ea-8436-cd2c81b8e3ed.png)

**Comment by kjozwiak** [comment]
@kylehickinson re: the STR for this specific issue. QA basically needs to view/receive several ads and ensure that `Estimated pending rewards` is correctly being updated?

Is there anything else in particular that we need to check or should the above be good enough?

**Comment by kylehickinson** [comment]
@kjozwiak  For this ticket in particular all you have to do is verify that the label appears even if it just says 0 BAT. The value was always correct, it was just "hidden" (by being extremely tall and therefore clipped off screen)

**Comment by kjozwiak** [comment]
Gotcha, thanks @kylehickinson 👍 Much appreciated.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.16(20.05.12.20)
<details>
<summary>Verified `Estimated pending rewards` is shown even when balance is 0.0BAT</summary>

![image](https://user-images.githubusercontent.com/17010094/81803299-1b2d9980-9535-11ea-85eb-eefb9537da4b.png)
</details>

<details>
<summary>Verified `Estimated pending rewards` value is shown when there is an actual balance available </summary>

![image](https://user-images.githubusercontent.com/17010094/81803272-0f41d780-9535-11ea-93dd-ffc7190a48a8.png)
</details>

-------
Verification passed on iPad Pro with iOS 13.4.5 running 1.16(20.05.12.20)
<details>
<summary>Verified `Estimated pending rewards` value is shown when balance is 0.0 BAT</summary>

![image](https://user-images.githubusercontent.com/17010094/81810325-60a39400-9540-11ea-89fc-524e91d8cb37.png)
</details>
<details>
<summary>Verified `Estimated pending rewards` value is shown when there is an actual balance available</summary>

![image](https://user-images.githubusercontent.com/17010094/81810489-a6f8f300-9540-11ea-915e-d0f7b8064d54.png)

</details>

-----------------

Verification passed on iPhone 6 with iOS 12.4.5 running 1.16(20.05.12.20)
<details>
<summary>Verified `Estimated pending rewards` value is shown when balance is 0.0 BAT</summary>

![image](https://user-images.githubusercontent.com/17010094/81810819-428a6380-9541-11ea-9b17-45c30a5d8731.png)

</details>
<details>
<summary>Verified `Estimated pending rewards` value is shown when there is an actual balance available</summary>

![image](https://user-images.githubusercontent.com/17010094/81810809-3e5e4600-9541-11ea-9c79-b383a97bc13e.png)

</details>

-----------------

Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.16 (20.05.12.20)`

| "Estimated pending rewards" displaying `0.00 BAT`| "Estimated pending rewards" after Ad|
|:-------------:|:-------------:|
| ![IMG_0308](https://user-images.githubusercontent.com/2602313/81885349-2948dd80-9568-11ea-81ec-e4b55d1e8815.PNG) | ![IMG_0309](https://user-images.githubusercontent.com/2602313/81885345-264ded00-9568-11ea-9a92-a0da3e211366.PNG)
