### ISSUE TITLE
Brave Ads should be auto-enabled if joining a newly supported region

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#2534]
### Description: 
Brave Ads should be auto-enabled if joining a newly supported region

### Steps to Reproduce 
  1. Change device region to a country where ads are not supported, i.e. Cuba
  2. Install Brave Browser
  3. Launch the app
  4. Join Brave Rewards
  5. Quit the app
  6. Change device region to a country where ads are supported, i.e. the United States
  7. Launch the app
  8. Click "my first ad" which appears after x seconds

**Actual result:** 
Ads are disabled and a user is not offered the option to enable ads (there is a workaround where the user can open the Rewards panel and enable ads, however, this is less intuitive in my opinion)

**Expected result:**
The user should be offered the option of joining ads

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.16 (App Store)

**Device details:** 
iPhone 11 Pro Max (iOS 13.4.1)

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information
The user is offered the option to join ads if they click "Start Browsing" instead of click "my first ad"

**Comment by kylehickinson** [comment]
Closed as this already happens, especially with new rewards on iOS
