### ISSUE TITLE
Super Referrer Improvements (Clipboard)

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#2539]
### Description: 

To improve installation metrics, implement clipboard inspection for new referral code detection.

### Steps to Reproduce 

This change is to allow referral codes to be read from the clipboard.

The general tech flow is:

Open Brave
- If first time, read clipboard
- If clipboard matches a predefined prefix, read the associated code that follows (e.g. ABC123)
- Use this ref code, instead of asking the server
- Previously we used /ua endpoint (which provided a ref-code), in this case we will be using /nonua endpoint (but only if a ref-code is found)

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
@bsclifton moving this into the `1.16.2` milestone as per the discussion in Slack.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.17(20.5.26.16)
- Verified all 3 scenarios mentioned in https://github.com/brave/brave-ios/pull/2535
--------
Verification passed on iPhone 7+  with iOS 13.4.5 running 1.17(20.5.26.16)
- Verified all 3 scenarios mentioned in https://github.com/brave/brave-ios/pull/2535
--------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.17(20.5.26.16)
- Verified all 3 scenarios mentioned in https://github.com/brave/brave-ios/pull/2535
--------
Verification passed on iPad Pro  with iOS 13.4.5 running 1.17(20.5.26.16)
- Verified all 3 scenarios mentioned in https://github.com/brave/brave-ios/pull/2535
--------
Verification passed on iPad Pro with iOS 12.4.5 running 1.17(20.5.26.16)
- Verified all 3 scenarios mentioned in https://github.com/brave/brave-ios/pull/2535
--------

This was also verified on 1.17(20.5.27.15)

-------
Verification passed on iPhone 8 with iOS 13.3.1 running 1.17(20.5.26.16) 
- Verified all 3 scenarios mentioned in https://github.com/brave/brave-ios/pull/2535
This was also verified on 1.17(20.5.27.15)

-----
Verification passed on 1.17(20.5.26.16) on Production on iPhone SE (iOS 12.4)
- Verified all 3 scenarios mentioned in https://github.com/brave/brave-ios/pull/2535
This was also verified on 1.17(20.5.27.15)
-----
Verification passed on iPad 5th Gen with iOS 12 running multiple versions but most recently 1.17(20.5.27.15).
- Verified all 3 scenarios mentioned in https://github.com/brave/brave-ios/pull/2535
