### ISSUE TITLE
Update "Request Mobile Site" Activity Icon

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#254]
As per #248, we are waiting on a new request mobile site icon.

This should be replaced with a new icon from design

![request-mobile-site](https://user-images.githubusercontent.com/529104/45505757-6dfcef80-b75b-11e8-8cd8-f56581042865.png)

### Solution Research

Icon is in `Images.xcassets` named `shareRequestMobileSite`.

**Comment by tmancey** [comment]
Discussed with @kylehickinson and this feature is not in 1.6, however removing this feature to add again at a later date may be more effort than adding a new icon. @jamesmudgett @anthonypkeane Your thoughts please?

**Comment by jamesmudgett** [comment]
[https://app.zenhub.com/files/113486284/bda60cbb-1761-4b5e-976d-915e29289fc9/download](https://app.zenhub.com/files/113486284/bda60cbb-1761-4b5e-976d-915e29289fc9/download)
