### ISSUE TITLE
Ads may fail to initialize on subsequent app launches

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2541]
Ads may not initialize when you launch the app, when you have already enabled rewards & ads in a previous launch.

## Test Case

Prerequisite for easier verification: Open Console.app on macOS before hand, connect test device to Mac via lightning cable

1. Fresh install Brave
2. Enable rewards & ads
3. Kill app
4. Launch Console.app, choose test device in left-side panel, filter to `BraveRewards`
5. Launch app
6. Verify ads log appears with the message `Successfully initialized ads`

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.16(20.05.12.20)
- Verified test plan from issue description
- Verified logs shows `Successfully Initialized Ads` even when app is quit and relaunched
```
16:27:01.008847+0530	libswiftFoundation.dylib	Client	[Info] [BraveRewards] > [ads_impl.cc.301] Initialized user model for en language
16:27:01.008897+0530	libswiftFoundation.dylib	Client	[Info] [BraveRewards] > [ads_impl.cc.179] Successfully initialized ads
16:27:01.008945+0530	libswiftFoundation.dylib	Client	[Info] [BraveRewards] > [ad_conversions.cc.83] Ad conversion queue is empty
16:27:01.011171+0530	libswiftFoundation.dylib	Client	[Info] [BraveRewards] > [client.cc.593] Successfully saved client state
```
---------
Verification passed on iPad Pro with iOS 13.4.5 running 1.16(20.05.12.20)
- Verified test plan from issue description
- Verified logs shows `Successfully initialized ads` even when app is quit and relaunched
```
17:00:51.446149+0530	libswiftFoundation.dylib	Client	[Info] [BraveRewards] > [ads_impl.cc.301] Initialized user model for en language
17:00:51.446166+0530	libswiftFoundation.dylib	Client	[Info] [BraveRewards] > [ads_impl.cc.179] Successfully initialized ads
17:00:51.446182+0530	libswiftFoundation.dylib	Client	[Info] [BraveRewards] > [ad_conversions.cc.83] Ad conversion queue is empty
17:00:51.446218+0530	libswiftFoundation.dylib	Client	[Info] [BraveRewards] > [client.cc.593] Successfully saved client state
```

---------

Verification passed on iPhone 6 with iOS 12.4.5 running 1.16(20.05.12.20)
- Verified test plan from issue description
- Verified logs shows `Successfully initialized ads` even when app is quit and relaunched

```
22:08:42.062671+0530	Client	[Info] [BraveRewards] > [ads_impl.cc.301] Initialized user model for en language
22:08:42.063050+0530	Client	[Info] [BraveRewards] > [ads_impl.cc.179] Successfully initialized ads
22:08:42.063455+0530	Client	[Info] [BraveRewards] > [ad_conversions.cc.83] Ad conversion queue is empty
22:08:42.075134+0530	Client	[Info] [BraveRewards] > [client.cc.593] Successfully saved client state
```
---------

Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.16.1 (20.05.12.20)`:

* Verified test plan from issue description
* Verified logs shows `Successfully Initialized Ads` even when app is quit and relaunched

```
20:56:46.151132-0400	Client [Info] [BraveRewards] > [ads_impl.cc.179] Successfully initialized ads
20:56:46.151381-0400	Client [Info] [BraveRewards] > [ad_conversions.cc.83] Ad conversion queue is empty
20:56:46.160348-0400	Client [Info] [BraveRewards] > [client.cc.593] Successfully saved client state
```

**Comment by kjozwiak** [comment]
QA will also go through the following manual passes which includes ad checks as well:

* Manual test run for 1.16.1 on iPad running iOS13 #2545
* Manual test run for 1.16.1 on iPhone running iOS12 #2546
* Manual test run for 1.16.1 on iPhone X running iOS13 #2547
