### ISSUE TITLE
Clear private data doesnt work

### ISSUE THREAD

**Issue by YanAndrew** [brave/brave-ios#2544]
## Description:
The 'Clear Private Data' feature on Brave iOS is not functioning again. Probably since the last update.

## Steps to Reproduce

   1. Launch Private Browsing and surf as normal.
   2. At the end of the surf session, manually clear private data via the browser's Settings
   3. A line moves across the screen at the top indicating data cleared. 
4. In fact, nothing is cleared because all the pages or tabs are still displaying the sites visited.
5. Further confirmation found in the Back' button. 

## Actual result:
All data from the session remains

## Expected result:
All data should've been removed

## Reproduces how often: 
Every time User use Brave

## Brave version (brave://version info)
<L
![8A51075C-D6CA-4AC3-82FC-528CB17A310A](https://user-images.githubusercontent.com/47048793/81761568-d259ee80-94fc-11ea-993f-2eff54885642.png)

![5D12DA29-3DF6-43CB-81B5-CF9A50D87CDC](https://user-images.githubusercontent.com/47048793/81761601-e998dc00-94fc-11ea-928a-a122ce4d5193.png)

## Version/Channel Information:
 I've checked my iPad, same issue 

- Can you reproduce this issue with the current release?
- Can you reproduce this issue with the beta channel?
- Can you reproduce this issue with the dev channel?
- Can you reproduce this issue with the nightly channel?

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? No idea, not tried.
- Does the issue resolve itself when disabling Brave Rewards? Don't know coz I don't do Brave Rewards.
- Is the issue reproducible on the latest version of Chrome? You'll have to check & see.

**Comment by jhreis** [comment]
This may be related to how we no longer clear session data for certain toggles. @YanAndrew if you reset Brave (swipe up on it, to remove it from memory), and relaunch, is the data gone then?

**Comment by diracdeltas** [comment]
agree this should be p1 if it validates

**Comment by YanAndrew** [comment]
Hello @jhreis Brave no longer clear session data? Does that mean that there's no point in using a private mode window and triggering the clear private browsing data function in Settings is pointless? 

Reset, by your definition, will give the user a new Brave browser, but how can users be certain the data from previous sessions are not stored somewhere in the device and a data retrieval software is all that is required to obtain those data?

**Comment by iccub** [comment]
Possibly fixed by https://github.com/brave/brave-ios/pull/2322
I will check it once we merge this PR

**Comment by iccub** [comment]
This is not a bug really, clearing data doesn't close currently opened tabs.
The tab's data is cleared if you close it or go back to private mode.

I think I will just add 1 more option in clearables that removes all opened tabs

**Comment by iccub** [comment]
turns out this still might be a problem, especially for session data, working on a fix

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.09.28.16)
- Verified test plan from issue description
- Logged follow up issue #2907 
--------------------------
Verification passed on iPhone 7+ with iOS 14.0.1 running 1.21(20.09.28.16)
- Verified test plan from issue description
--------------------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.09.28.16)
- Verified test plan from issue description
