### ISSUE TITLE
Update Rewards Logging

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2552]
This PR from brave-core will bring refactored logging coming from Rewards: https://github.com/brave/brave-core/pull/5505

- [ ] Remove `RewardsLogStream` as logs will be fully composed at call site and pass these directly to client (`brave-ios`)
- [ ] Support integer based verbosity instead of enum-based. 0 = error, 1 = warning, etc.

**Comment by NejcZdovc** [comment]
closing in favour of https://github.com/brave/brave-ios/issues/2617
