### ISSUE TITLE
Total balance does not include old promotions

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2556]
Duplicate of https://github.com/brave/brave-browser/issues/9796

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.16.2(20.5.15.21)
- Installed 1.16.1(20.5.12.20) and enabled rewards
- Imported wallet, balance showed 17BAT
![image](https://user-images.githubusercontent.com/17010094/82135349-65f22e80-981f-11ea-8e26-420b0bdbd51a.png)
- Upgraded to 1.16.2, balance updated to 33 BAT
![image](https://user-images.githubusercontent.com/17010094/82135346-5ffc4d80-981f-11ea-9097-e5ee508dc86e.png)
- Tip a verified publisher, balance reduced accordingly and shows in the panel 
![image](https://user-images.githubusercontent.com/17010094/82135341-54a92200-981f-11ea-925a-2c43f2cfb6f3.png)
- Tip an unverified publisher, balance doesn't change, shows the message for an unverified publisher, pending contributions lists the site correctly 
![image](https://user-images.githubusercontent.com/17010094/82135376-aa7dca00-981f-11ea-8b52-2807153be1c6.png)

----------
Verification passed on iPad Pro with iOS 13.4.5 running 1.16.2(20.5.15.21)
- Installed 1.16.1(20.5.12.20) and enabled rewards
- Imported wallet, balance showed 17BAT
![image](https://user-images.githubusercontent.com/17010094/82135354-71ddf080-981f-11ea-96a4-75da520e84c1.png)
- Upgraded to 1.16.2, balance updated to 33 BAT
![image](https://user-images.githubusercontent.com/17010094/82135360-8ae6a180-981f-11ea-994d-e53b45bfc055.png)
- Tip a verified publisher, balance reduced accordingly and shows in the panel 
![image](https://user-images.githubusercontent.com/17010094/82135352-6c80a600-981f-11ea-9cb4-dfe597fe3b00.png)
- Tip an unverified publisher, balance doesn't change, shows the message for an unverified publisher, pending contributions lists the site correctly 
![image](https://user-images.githubusercontent.com/17010094/82135369-a356bc00-981f-11ea-9b27-f5058c63cb1b.png)

------
Verification passed on iPhone 8 with iOS 13.3.1 running 1.16.2(20.5.15.21)
- Installed 1.16.1(20.5.12.20) and enabled rewards
- Imported wallet, balance showed 17BAT
![IMG_0390](https://user-images.githubusercontent.com/38657976/82200683-f498a580-991c-11ea-9968-5d1e31f1349f.PNG)
- Upgraded to 1.16.2, balance updated to 33 BAT
![IMG_0391](https://user-images.githubusercontent.com/38657976/82200754-0b3efc80-991d-11ea-8c9a-c4d66bd7b415.PNG)
- Tip a verified publisher, balance reduced accordingly and shows in the panel 
![IMG_0392](https://user-images.githubusercontent.com/38657976/82200819-23168080-991d-11ea-85b7-c9c681373d43.PNG)
![IMG_0394](https://user-images.githubusercontent.com/38657976/82200949-46413000-991d-11ea-9f77-1c61051a78e0.PNG)

- Tip an unverified publisher, balance doesn't change, shows the message for an unverified publisher, pending contribution lists the site correctly 
![IMG_0393](https://user-images.githubusercontent.com/38657976/82200917-3c1f3180-991d-11ea-860a-b1ba0e03f834.PNG)
![IMG_0395](https://user-images.githubusercontent.com/38657976/82200970-4c371100-991d-11ea-8da9-acdcecd75b3c.PNG)

------------

Verification passed on iPad 5th Gen with iOS 12 running 1.16.2 (20.05.15.21)

- Installed 1.16.1(20.5.12.20) and enabled rewards
- Imported wallet, balance showed 17BAT
![iOS12 iPad panel 1 16 1 before](https://user-images.githubusercontent.com/28145373/82213684-93ec7700-98e2-11ea-91d2-761569fef77f.jpeg)

- Upgraded to 1.16.2, balance updated to 33 BAT
![iOS12 iPad panel 1 16 2 after](https://user-images.githubusercontent.com/28145373/82213699-99e25800-98e2-11ea-900e-caf82f6570ff.jpeg)

- Tip a verified publisher, balance reduced accordingly and shows in the panel
![iOS12 iPad panel verified pub tip 1 16 2](https://user-images.githubusercontent.com/28145373/82213715-9e0e7580-98e2-11ea-8f81-c2d0e1212d96.jpeg)
![iOS12 iPad Tips panel 1 16 2](https://user-images.githubusercontent.com/28145373/82213910-ed54a600-98e2-11ea-84f9-70c7bef23414.jpeg)

- Tip an unverified publisher, balance doesn't change, shows the message for an unverified publisher, pending contributions lists the site correctly
![iOS12 iPad panel unverified pub tip 1 16 2](https://user-images.githubusercontent.com/28145373/82213735-a5358380-98e2-11ea-8db3-919e370d497f.jpeg)
![iOS12 iPad pending contributions 1 16 2](https://user-images.githubusercontent.com/28145373/82213926-f2195a00-98e2-11ea-87d3-455712288ff9.jpeg)

------
Verification passed on iPad mini with iOS 13 running 1.16.2 (20.05.15.21)

- Installed 1.16.1(20.5.12.20) and enabled rewards
- Imported wallet, balance showed 17BAT
![iOS13 iPad panel 1 16 1 before](https://user-images.githubusercontent.com/28145373/82216436-f5aee000-98e6-11ea-8bef-bf5e538a5831.jpeg)

- Upgraded to 1.16.2, balance updated to 33 BAT
![iOS13 iPad panel 1 16 2 after](https://user-images.githubusercontent.com/28145373/82216453-fa739400-98e6-11ea-869c-005dd9579832.jpeg)

- Tip a verified publisher, balance reduced accordingly and shows in the panel
![iOS13 iPad panel verified pub tip 1 16 2](https://user-images.githubusercontent.com/28145373/82216474-00697500-98e7-11ea-9476-ba8718e8ff1a.jpeg)
![iOS13 iPad Tips panel 1 16 2](https://user-images.githubusercontent.com/28145373/82216484-02cbcf00-98e7-11ea-89c6-15d437f8d767.jpeg)

- Tip an unverified publisher, balance doesn't change, shows the message for an unverified publisher, pending contributions lists the site correctly
![iOS13 iPad panel unverified pub tip 1 16 2](https://user-images.githubusercontent.com/28145373/82216492-07908300-98e7-11ea-8a4c-2285343c5d41.jpeg)
![iOS13 iPad pending contributions 1 16 2](https://user-images.githubusercontent.com/28145373/82216509-0bbca080-98e7-11ea-9248-5fb588babe7e.jpeg)

------
Verification passed on iPhone SE (iOS 12.4) running 1.16.2(20.5.15.21)
- Installed 1.16.1(20.5.12.20) and enabled rewards
- Imported wallet, balance showed 17BAT
![IMG_0019](https://user-images.githubusercontent.com/34715963/82237530-16eaed00-9936-11ea-82b7-e46ea0296bba.PNG)
- Upgraded to 1.16.2, balance updated to 33 BAT
![IMG_0020](https://user-images.githubusercontent.com/34715963/82237567-266a3600-9936-11ea-8b34-e7e0c5e432aa.PNG)
- Tip a verified publisher, balance reduced accordingly and shows in the panel
![IMG_0022](https://user-images.githubusercontent.com/34715963/82237736-6f21ef00-9936-11ea-9fb5-6f1fb99b754d.PNG)
- Tip a verified publisher, balance reduced accordingly and shows in the panel
![IMG_0023](https://user-images.githubusercontent.com/34715963/82237766-7b0db100-9936-11ea-86fb-b73ff4eeb9fa.PNG)
