### ISSUE TITLE
HTTP Lock Briefly Displayed

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ios#2561]
### Description: 
When establishing a secure connection, the address bar briefly flashes a red lock.

### Steps to Reproduce 
Navigate to ebay.com

**Actual result:** 
![no-secure-connection-flash](https://user-images.githubusercontent.com/815158/82135486-df126700-97c8-11ea-9ee1-fbd6d294d7bc.gif)

**Expected result:**
The user shouldn't be given the impression they have established an insecure connection.

**Reproduces how often:**
Always.

**Brave Version:** 
1.16

**Comment by iccub** [comment]
not applicable anymore, we removed the red lock, now it shows no lock for brief second, but this is something that's Apple controlled
