### ISSUE TITLE
iOS does not retry to get a downloadId

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#2565]
### Description: 
Found while testing https://github.com/brave/brave-ios/pull/2535

iOS does not retry to get a downloadId if internet is down or referral server is unreachable. 

This was recently implemented on desktop w/ https://github.com/brave/brave-browser/issues/7742

#### Clipboard Identification Verification
1. Visit a Super Referrer landing page
1. Hit the download button
1. This will redirect you to the App Store, _close the App Store_
1. Go to notes app (or some other place with a text field)
1. Paste the clipboard
1. Should output `F83AB73F-9852-4F01-ABA8-7830B8825993` followed by a single character (either `:` or `/`) and then the specific ref code (e.g. ABC123) from the referral
1. So full out put would be `F83AB73F-9852-4F01-ABA8-7830B8825993:ABC123` for example
1. Download Brave through TF
1. Disable internet (this makes sure the fallback is not activated if clipboard fails for some reason)
1. Open Brave
1. Since no internet connection, no custom assets, but ref code should still be shown inside the settings page
1. Re-enable wifi/internet on your device
1. Close Browser, remove from memory, relaunch
1. Check logs.

**Actual result:** 
No downloadId
![Image from iOS](https://user-images.githubusercontent.com/28145373/82588852-59484000-9b69-11ea-9309-d677b3337492.jpg)
![Image from iOS (1)](https://user-images.githubusercontent.com/28145373/82588862-5d745d80-9b69-11ea-918a-cfb09cf09a37.jpg)

**Expected result:**
get a downloadId

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily, reproduced by @srirambv 

**Brave Version:** 
1.17 (20.05.18.18)

**Device details:** 
iOS12 iPad

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.17(20.5.27.15)
- Verified download id is generated and sent back to the server once the device comes online 
- Verified download id is generated without having to relaunch the app after install 
--------
Verification passed on iPhone 7+  with iOS 13.4.5 running 1.17(20.5.27.15)
- Verified download id is generated and sent back to the server once the device comes online 
- Verified download id is generated without having to relaunch the app after install 
--------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.17(20.5.27.15)
- Verified download id is generated and sent back to the server once the device comes online 
- Verified download id is generated without having to relaunch the app after install 
--------
Verification passed on iPad Pro  with iOS 13.4.5 running 1.17(20.5.27.15)
- Verified download id is generated and sent back to the server once the device comes online 
- Verified download id is generated without having to relaunch the app after install 
--------
Verification passed on iPad Pro with iOS 12.4.5 running 1.17(20.5.27.15)
- Verified download id is generated and sent back to the server once the device comes online 
- Verified download id is generated without having to relaunch the app after install 
--------

Verified download id for iPhone XR and iPad Pro gets finalize successfully and confirmed it with @keur 

--------
Verification passed on iPhone 8 with iOS 13.3.1 running 1.17(20.5.27.15)
- Verified download id is generated and sent back to the server once the device comes online 
- Verified download id is generated without having to relaunch the app after install 

------
Verification passed on 1.17 (20.5.27.15) on iPhone SE (iOS 12.4)
- Verified download id is generated and sent back to the server once the device comes online 
- Verified download id is generated without having to relaunch the app after install 
--------
Verification passed on iPad 5th Gen with iOS 12 running 1.17(20.5.27.15)
- Verified download id is generated and sent back to the server once the device comes online 
- Verified download id is generated without having to relaunch the app after install
