### ISSUE TITLE
Close all Tabs Option

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ios#2567]
## Problem Description
[User MDB](https://twitter.com/mdbcdxx/status/1263606166472527873) has requested the ability to close all open tabs. Users are able to quickly view open-tabs, but must close tabs one-by-one. This feature would allow a user to easily (perhaps not too easily, to avoid accidental closure) close all tabs.

## Design
The feature-request on Twitter proposed a 🗑 icon on the tab-view.

![image](https://user-images.githubusercontent.com/815158/82615603-72b0b280-9b90-11ea-8e70-72472f2bbccd.png)

**Comment by kylehickinson** [comment]
@jonathansampson This feature already exists by long-pressing the tab-tray icon in the toolbar while in a Tab: 

![IMG_F69E5A043BB0-1](https://user-images.githubusercontent.com/529104/82625985-9b4aa380-9bb4-11ea-990d-4b4176e7d715.jpeg)

**Comment by jonathansampson** [comment]
@kylehickinson We may want to explore the UX/flow of this feature 🙂

**Comment by kylehickinson** [comment]
@jonathansampson Just an FYI, It mimics the same UX as Safari on iOS

**Comment by jonathansampson** [comment]
All the same; it isn't very intuitive. Just a friendly suggestion :)
