### ISSUE TITLE
After finalizing URP code open NTP is not showing CHP images

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#2571]
### Description: 
After finalizing URP code open NTP is not showing CHP images
Found while testing https://github.com/brave/brave-ios/pull/2535

### Steps to Reproduce 
(scenario 2 from https://github.com/brave/brave-ios/pull/2535)
 
1. Visit a Super Referrer landing page 
2. Hit the download button
3. This will redirect you to the App Store, close the App Store
4. Download Brave through TF
5. Open Brave
6. Verified correct ref code and download_id (CHP images were shown in NTP's)
7. Followed steps to Finalize the URP code
8. Removed brave app from memory 
9. Wait for 10 mins to finalize the URP code
10. Relaunch app after 10 mins
11. Open NTP's, CHP images are not shown in NTP's
12. Open a website e.g brave.com in NTP and then open a NTP is showing CHP images in NTP

**Actual result:** 
After finalizing URP code open NTP is not showing CHP images

**Expected result:**
After finalizing URP code open NTP should show CHP images

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
1.17 (20.05.21.17)

**Device details:** 
iPhone 8 - iOS 13.3.1

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
more info: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1590163640244800

Reproduced issue by @LaurenWags and @srirambv 
cc: @brave/legacy_qa @jhreis @anthonypkeane @bsclifton

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.17(20.5.26.16)
- Verified CHP images are shown even after finalization happens and ref code is removed 
--------
Verification passed on iPhone 7+  with iOS 13.4.5 running 1.17(20.5.26.16)
- Verified CHP images are shown even after finalization happens and ref code is removed 
--------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.17(20.5.26.16)
- Verified CHP images are shown even after finalization happens and ref code is removed 
--------
Verification passed on iPad Pro  with iOS 13.4.5 running 1.17(20.5.26.16)
- Verified CHP images are shown even after finalization happens and ref code is removed 
--------
Verification passed on iPad Pro with iOS 12.4.5 running 1.17(20.5.26.16)
- Verified CHP images are shown even after finalization happens and ref code is removed 
--------

This was also verified as part of Clipboard testing with @keur and tested on 1.17(20.5.27.15)

-------
Verification passed on iPhone 8 with iOS 13.3.1 running 1.17(20.5.26.16)
- Verified CHP images are shown even after finalization happens and ref code is removed 

-------
This was also verified as part of Clipboard testing with @keur and tested on 1.17(20.5.27.15)

------
Verification passed on 1.17(20.5.26.16) on Production on iPhone SE (iOS 12.4)

--------
Verification passed on iPad 5th Gen with iOS 12 running 1.17(20.5.27.15)
- Verified CHP images are shown even after finalization happens and ref code is removed 
- This was also verified as part of Clipboard testing with @keur
