### ISSUE TITLE
Show 'estimated ad earnings this month' on the top-level Brave Rewards settings screen and do not hide under 'View Details' (additional press)

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-ios#2575]
## Description 

The "Estimated ad earnings" counter should appear in the top-level Brave Rewards settings page. Based on support queries, users often mistakenly believe their Brave Ads is broken because they do not see BAT immediately increasing upon seeing an ad. However, this is further exacerbated by "estimated ad earnings" being hidden under an additional press on mobile ("View Details"), which many users miss or do not notice.

![image](https://user-images.githubusercontent.com/11497541/82717628-68171b80-9c6b-11ea-9e75-365dc20a7fe6.png) 

Initial response to this suggested change (August 2019 internally), including among @brave/design, was mostly well-received! :)

## Steps to reproduce 

1. On mobile, go into Brave Rewards settings. (Applies to both iOS and Android)
2. Estimated ad earnings is always hidden under "View Details" rather than surfaced immediately in the top-level Settings page.

**Comment by Miyayes** [comment]
+1 User confused by current UI: https://www.reddit.com/r/brave_browser/comments/hzy6j8/started_using_brave_mobile_ios_watched_5_ads_no/ cc: @brave/design @jsecretan

**Comment by kylehickinson** [comment]
Closed since we no longer have this screen anymore
