### ISSUE TITLE
CHP custom favorites sometimes initialized at second launch.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2577]
### Description: 
Sometimes when you install a CHP build, custom favorites are not shown at first launch, default favorites are shown instead. However on second launch favs will get replaced if they have not been updated by the user(as per spec)

### Steps to Reproduce 
It is a race condition, not easy to reproduce
  1. Install CHP build

**Actual result:** 
Default favorites could be showing

**Expected result:**
Custom favs should have been added.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.17(20.5.26.16)
- Verified custom favourites are shown on the first launch 
--------
Verification passed on iPhone 7+  with iOS 13.4.5 running 1.17(20.5.26.16)
- Verified custom favourites are shown on the first launch 
--------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.17(20.5.26.16)
- Verified custom favourites are shown on the first launch 
--------
Verification passed on iPad Pro  with iOS 13.4.5 running 1.17(20.5.26.16)
- Verified custom favourites are shown on the first launch 
--------
Verification passed on iPad Pro with iOS 12.4.5 running 1.17(20.5.26.16)
- Verified custom favourites are shown on the first launch 
--------

This was also verified on 1.17(20.5.27.15)

--------
Verification passed on iPhone 8 with iOS 13.3.1 running 1.17(20.5.26.16)
- Verified custom favorites are shown on the first launch 

-----
Verification passed on 1.17(20.5.26.16) on Production on iPhone SE (iOS 12.4)
- Verified custom favorites are shown on the first launch 
------

Verification passed on iPad 5th Gen with iOS 12 running 1.17(20.5.26.16)
- Verified custom favorites are shown on the first launch
