### ISSUE TITLE
New Tab Page Enhancements & Favourites Overlay

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2578]
- Tapping the URL bar will now display a scrollable list of favourites rather rather than the NTP.
- NTP code refactored
    - Show more now just highlights URL bar and brings up overlay
    - Removal of auto-keyboard setting since favorites overlay would always hide NTP
- On iOS 13 use new context menus APIs
- Update drag & drop API for favorites reordering while on the favourites overlay
- iPad pointer interactions & right-click context menus for favorites on NTP/Favorites overlay

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.18(20.06.26.17)
<details>
<summary>Stats</summary>
<li>Verified stats load correctly and updates correctly</li>
<li>Verified change in orientation doesn't mess up stats value</li>
</details>

<details>
<summary>Favourites</summary>
<li>Verified favourites appear and are right-aligned even when there are less than 4</li>
<li>Verified changing device orientation doesn't cause any issues with favourites</li>
<li>Verified `Show More` only appears when there's more than 5 favourites on NTP</li>
<li>Verified clicking on `Show More` set focus to URL bar and displays all available bookmarks</li>
<li>Verified no `Show More` is shown if there are less than 5 favourites</li>
<li>Verified changing orientation doesn't cause any issue with NTP images or stats</li>
</details>

<details>
<summary>Sponsored images</summary>
<li>Verified SI are loaded correctly in order</li>
<li>Verified SI is centred correctly when device orientation changes</li>
<li>Verified SI modals on first SI is shown correctly and device orientation change doesn't affect the placement</li>
<li>Verified Rewards popup modal via SI is shown correctly and device orientation change doesn't affect the placement</li>
</details>

<details>
<summary>Background Images</summary>
<li>Verified background images are loaded correctly and are centred correctly when device orientation changes</li>
<li>Verified background images source button works fine and loads the landing page correctly </li>
<li>Verified changing enabling/disabling background images settings doesn't affect stats/favourites</li>
<li>Verified each tab retains its background image</li>
<li>Verified switching between a new tab and a site doesn't update the background image like it used to before</li>
</details>

<details>
<summary>CHP</summary>
<li>Verified CHP is loaded correctly and centred correctly with both device orientation</li>
<li>Verified CHP QR code button is shown correctly and alignment is proper when orientation changes</li>
<li>Verified custom assets are loaded correctly and when tapped loads the landing page</li>
</details>

<details>
<summary>Private tabs</summary>
<li>Verified DDG modal on the private tab is shown correctly</li>
<li>Verified DDG info message on Private tab is shown correctly on both orientation</li>
</details>

<details>
<summary>Theme</summary>
<li>Verified theme settings work fine</li>
<li>Verified when the background image is turned off shows dark-blue background without any gradient when the theme is light</li>
<li>Verified when the background image is turned off shows dark-theme background without any gradient when the theme is dark</li>
</details>

<details>
<summary>Favicons</summary>
<li> Verified favicons are shown correctly on 
<ul>
<li>Favourites</li>
<li>Bookmarks</li>
<li>Add Bookmark page</li>
<li>History page</li>
<li>Search dropdwon</li>
<li>Back/Forward list</li>
<li>Tab tray</li>
<li>Rewards panel</li>
<li>Rewards tipping banner</li>
</ul>
</details>

<details>
<summary>Favourites Overlay</summary>
<li>Verified click on URL bar brings up favourites overlay similar to Safari</li>
<li>Verified able to rearrage favourites only when favourites overlay is shown</li>
<li>Verified able to scroll through favourites list only during overlay is shown</li>
</details>

<details>
<summary>Misc</summary>
<li>Verified long press on favourite brings up context menu on iOS 13 devices</li>
<li>Verified able to edit the favourites and the site logo is loaded immediately</li>
<li>Verified monogram letter with colour background is shown when a favourite is edited and favicons are not avaialble</li>
<li>Verified upgrading from older version retains downloaded favicons for favourites/bookmarks</li>
</details>


------------------


Verification passed on iPhone 7+ with iOS 13.5.1 running 1.18(20.06.26.17)
<details>
<summary>Stats</summary>
<li>Verified stats load correctly and updates correctly</li>
<li>Verified change in orientation doesn't mess up stats value</li>
</details>

<details>
<summary>Favourites</summary>
<li>Verified favourites appear and are right-aligned even when there are less than 4</li>
<li>Verified changing device orientation doesn't cause any issues with favourites</li>
<li>Verified `Show More` only appears when there's more than 5 favourites on NTP</li>
<li>Verified clicking on `Show More` set focus to URL bar and displays all available bookmarks</li>
<li>Verified no `Show More` is shown if there are less than 5 favourites</li>
<li>Verified changing orientation doesn't cause any issue with NTP images or stats</li>
</details>

<details>
<summary>Sponsored images</summary>
<li>Verified SI are loaded correctly in order</li>
<li>Verified SI is centred correctly when device orientation changes</li>
<li>Verified SI modals on first SI is shown correctly and device orientation change doesn't affect the placement</li>
<li>Verified Rewards popup modal via SI is shown correctly and device orientation change doesn't affect the placement</li>
</details>

<details>
<summary>Background Images</summary>
<li>Verified background images are loaded correctly and are centred correctly when device orientation changes</li>
<li>Verified background images source button works fine and loads the landing page correctly </li>
<li>Verified changing enabling/disabling background images settings doesn't affect stats/favourites</li>
<li>Verified each tab retains its background image</li>
<li>Verified switching between a new tab and a site doesn't update the background image like it used to before</li>
</details>

<details>
<summary>CHP</summary>
<li>Verified CHP is loaded correctly and centred correctly with both device orientation</li>
<li>Verified CHP QR code button is shown correctly and alignment is proper when orientation changes</li>
<li>Verified custom assets are loaded correctly and when tapped loads the landing page</li>
</details>

<details>
<summary>Private tabs</summary>
<li>Verified DDG modal on the private tab is shown correctly</li>
<li>Verified DDG info message on Private tab is shown correctly on both orientation</li>
</details>

<details>
<summary>Theme</summary>
<li>Verified theme settings work fine </li>
<li>Verified when the background image is turned off shows dark-blue background without any gradient when the theme is light</li>
<li>Verified when the background image is turned off shows dark-theme background without any gradient when the theme is dark</li>
</details>

<details>
<summary>Favicons</summary>
<li> Verified favicons are shown correctly on 
<ul>
<li>Favourites</li>
<li>Bookmarks</li>
<li>Add Bookmark page</li>
<li>History page</li>
<li>Search dropdwon</li>
<li>Back/Forward list</li>
<li>Tab tray</li>
<li>Rewards panel</li>
<li>Rewards tipping banner</li>
</ul>
</details>

<details>
<summary>Favourites Overlay</summary>
<li>Verified click on URL bar brings up favourites overlay similar to Safari</li>
<li>Verified able to rearrage favourites only when favourites overlay is shown</li>
<li>Verified able to scroll through favourites list only during overlay is shown</li>
</details>

<details>
<summary>Misc</summary>
<li>Verified long press on favourite brings up context menu on iOS 13 devices</li>
<li>Verified able to edit the favourites and the site logo is loaded immediately</li>
<li>Verified monogram letter with colour background is shown when a favourite is edited and favicons are not avaialble</li>
<li>Verified upgrading from older version retains downloaded favicons for favourites/bookmarks</li>
</details>


------------------


Verification passed on iPhone 6 with iOS 12.4.7 running 1.18(20.06.26.17)
<details>
<summary>Stats</summary>
<li>Verified stats load correctly and updates correctly</li>
<li>Verified change in orientation doesn't mess up stats value</li>
</details>

<details>
<summary>Favourites</summary>
<li>Verified favourites appear and are right-aligned even when there are less than 4</li>
<li>Verified changing device orientation doesn't cause any issues with favourites</li>
<li>Verified `Show More` only appears when there's more than 5 favourites on NTP</li>
<li>Verified clicking on `Show More` set focus to URL bar and displays all available bookmarks</li>
<li>Verified no `Show More` is shown if there are less than 5 favourites</li>
<li>Verified changing orientation doesn't cause any issue with NTP images or stats</li>
</details>

<details>
<summary>Sponsored images</summary>
<li>Verified SI are loaded correctly in order</li>
<li>Verified SI is centred correctly when device orientation changes</li>
<li>Verified SI modals on first SI is shown correctly and device orientation change doesn't affect the placement</li>
<li>Verified Rewards popup modal via SI is shown correctly and device orientation change doesn't affect the placement</li>
</details>

<details>
<summary>Background Images</summary>
<li>Verified background images are loaded correctly and are centred correctly when device orientation changes</li>
<li>Verified background images source button works fine and loads the landing page correctly </li>
<li>Verified changing enabling/disabling background images settings doesn't affect stats/favourites</li>
<li>Verified each tab retains its background image</li>
<li>Verified switching between a new tab and a site doesn't update the background image like it used to before</li>
</details>

<details>
<summary>CHP</summary>
<li>Verified CHP is loaded correctly and centred correctly with both device orientation</li>
<li>Verified CHP QR code button is shown correctly and alignment is proper when orientation changes</li>
<li>Verified custom assets are loaded correctly and when tapped loads the landing page</li>
</details>

<details>
<summary>Private tabs</summary>
<li>Verified DDG modal on the private tab is shown correctly</li>
<li>Verified DDG info message on Private tab is shown correctly on both orientation</li>
</details>

<details>
<summary>Theme</summary>
<li>Verified theme settings work fine</li> 
<li>Verified when the background image is turned off shows dark-blue background without any gradient when the theme is light</li>
<li>Verified when the background image is turned off shows dark-theme background without any gradient when the theme is dark</li>
</details>

<details>
<summary>Favicons</summary>
<li> Verified favicons are shown correctly on 
<ul>
<li>Favourites</li>
<li>Bookmarks</li>
<li>Add Bookmark page</li>
<li>History page</li>
<li>Search dropdwon</li>
<li>Back/Forward list</li>
<li>Tab tray</li>
<li>Rewards panel</li>
<li>Rewards tipping banner</li>
</ul>
</details>

<details>
<summary>Favourites Overlay</summary>
<li>Verified click on URL bar brings up favourites overlay similar to Safari</li>
<li>Verified able to rearrage favourites only when favourites overlay is shown</li>
<li>Verified able to scroll through favourites list only during overlay is shown</li>
</details>

<details>
<summary>Misc</summary>
<li>Verified long press on favourite brings up edit/remove context menu</li>
<li>Verified able to edit the favourites and the site logo is loaded immediately</li>
<li>Verified monogram letter with colour background is shown when a favourite is edited and favicons are not avaialble</li>
<li>Verified upgrading from older version retains downloaded favicons for favourites/bookmarks</li>
</details>


------------------


Verification passed on iPad Pro with iOS 13.6 running 1.18(20.06.26.17)
<details>
<summary>Stats</summary>
<li>Verified stats load correctly and updates correctly</li>
<li>Verified change in orientation doesn't mess up stats value</li>
</details>

<details>
<summary>Favourites</summary>
<li>Verified favourites appear and are left-aligned even when there are less than 6</li>
<li>Verified changing device orientation doesn't cause any issues with favourites</li>
<li>Verified `Show More` only appears when there's more than 5 favourites on NTP</li>
<li>Verified clicking on `Show More` set focus to URL bar and displays all available bookmarks</li>
<li>Verified no `Show More` is shown if there are less than 5 favourites</li>
<li>Verified changing orientation doesn't cause any issue with NTP images or stats</li>
</details>

<details>
<summary>Sponsored images</summary>
<li>Verified SI are loaded correctly in order</li>
<li>Verified SI is centred correctly when device orientation changes</li>
<li>Verified SI modals on first SI is shown correctly and device orientation change doesn't affect the placement</li>
<li>Verified Rewards popup modal via SI is shown correctly and device orientation change doesn't affect the placement</li>
</details>

<details>
<summary>Background Images</summary>
<li>Verified background images are loaded correctly and are centred correctly when device orientation changes</li>
<li>Verified background images source button works fine and loads the landing page correctly </li>
<li>Verified changing enabling/disabling background images settings doesn't affect stats/favourites</li>
<li>Verified each tab retains its background image</li>
<li>Verified switching between a new tab and a site doesn't update the background image like it used to before</li>
</details>

<details>
<summary>CHP</summary>
<li>Verified CHP is loaded correctly and centred correctly with both device orientation</li>
<li>Verified CHP QR code button is shown correctly and alignment is proper when orientation changes</li>
<li>Verified custom assets are loaded correctly and when tapped loads the landing page</li>
</details>

<details>
<summary>Private tabs</summary>
<li>Verified DDG modal on the private tab is shown correctly</li>
<li>Verified DDG info message on Private tab is shown correctly on both orientation</li>
</details>

<details>
<summary>Theme</summary>
<li>Verified theme settings work fine</li>
<li>Verified when the background image is turned off shows dark-blue background without any gradient when the theme is light</li>
<li>Verified when the background image is turned off shows dark-theme background without any gradient when the theme is dark</li>
</details>

<details>
<summary>Favicons</summary>
<li> Verified favicons are shown correctly on 
<ul>
<li>Favourites</li>
<li>Bookmarks</li>
<li>Add Bookmark page</li>
<li>History page</li>
<li>Search dropdwon</li>
<li>Back/Forward list</li>
<li>Tab tray</li>
<li>Rewards panel</li>
<li>Rewards tipping banner</li>
</ul>
</details>

<details>
<summary>Favourites Overlay</summary>
<li>Verified click on URL bar brings up favourites overlay similar to Safari</li>
<li>Verified able to rearrage favourites only when favourites overlay is shown</li>
<li>Verified able to scroll through favourites list only during overlay is shown</li>
</details>

<details>
<summary>Misc</summary>
<li>Verified long press on favourite brings up context menu on iOS 13 devices</li>
<li>Verified able to edit the favourites and the site logo is loaded immediately</li>
<li>Verified monogram letter with colour background is shown when a favourite is edited and favicons are not avaialble</li>
<li>Verified upgrading from older version retains downloaded favicons for favourites/bookmarks</li>
</details>


------------------


Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.06.26.17)
<details>
<summary>Stats</summary>
<li>Verified stats load correctly and updates correctly</li>
<li>Verified change in orientation doesn't mess up stats value</li>
</details>

<details>
<summary>Favourites</summary>
<li>Verified favourites appear and are left-aligned even when there are less than 6</li>
<li>Verified changing device orientation doesn't cause any issues with favourites</li>
<li>Verified `Show More` only appears when there's more than 5 favourites on NTP</li>
<li>Verified clicking on `Show More` set focus to URL bar and displays all available bookmarks</li>
<li>Verified no `Show More` is shown if there are less than 5 favourites</li>
<li>Verified changing orientation doesn't cause any issue with NTP images or stats</li>
</details>

<details>
<summary>Sponsored images</summary>
<li>Verified SI are loaded correctly in order</li>
<li>Verified SI is centred correctly when device orientation changes</li>
<li>Verified SI modals on first SI is shown correctly and device orientation change doesn't affect the placement</li>
<li>Verified Rewards popup modal via SI is shown correctly and device orientation change doesn't affect the placement</li>
</details>

<details>
<summary>Background Images</summary>
<li>Verified background images are loaded correctly and are centred correctly when device orientation changes</li>
<li>Verified background images source button works fine and loads the landing page correctly </li>
<li>Verified changing enabling/disabling background images settings doesn't affect stats/favourites</li>
<li>Verified each tab retains its background image</li>
<li>Verified switching between a new tab and a site doesn't update the background image like it used to before</li>
</details>

<details>
<summary>CHP</summary>
<li>Verified CHP is loaded correctly and centred correctly with both device orientation</li>
<li>Verified CHP QR code button is shown correctly and alignment is proper when orientation changes</li>
<li>Verified custom assets are loaded correctly and when tapped loads the landing page</li>
</details>

<details>
<summary>Private tabs</summary>
<li>Verified DDG modal on the private tab is shown correctly</li>
<li>Verified DDG info message on Private tab is shown correctly on both orientation</li>
</details>

<details>
<summary>Theme</summary>
<li>Verified theme settings work fine</li>
<li>Verified when the background image is turned off shows dark-blue background without any gradient when the theme is light</li>
<li>Verified when the background image is turned off shows dark-theme background without any gradient when the theme is dark</li>
</details>

<details>
<summary>Favicons</summary>
<li> Verified favicons are shown correctly on 
<ul>
<li>Favourites</li>
<li>Bookmarks</li>
<li>Add Bookmark page</li>
<li>History page</li>
<li>Search dropdwon</li>
<li>Back/Forward list</li>
<li>Tab tray</li>
<li>Rewards panel</li>
<li>Rewards tipping banner</li>
</ul>
</details>

<details>
<summary>Favourites Overlay</summary>
<li>Verified click on URL bar brings up favourites overlay similar to Safari</li>
<li>Verified able to rearrage favourites only when favourites overlay is shown</li>
<li>Verified able to scroll through favourites list only during overlay is shown</li>
</details>

<details>
<summary>Misc</summary>
<li>Verified long press on favourite brings up edit/remove bookmark menu</li>
<li>Verified able to edit the favourites and the site logo is loaded immediately</li>
<li>Verified monogram letter with colour background is shown when a favourite is edited and favicons are not avaialble</li>
<li>Verified upgrading from older version retains downloaded favicons for favourites/bookmarks</li>
</details>
