### ISSUE TITLE
Favicon Enhancements

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2579]
- Consolidate favicon fetching logic
- Will now attempt to look for `apple-touch-icon` as a large favicon before defaulting to smaller favicons.
- Favorites specifically only load `apple-touch-icon` favicons (closest to 180x180)
    - If none that meet this criteria is found, monogram icon is used (letter + color). 
- Monogram letter is determined by the base domain's first character, or the URL host's first character.  In the case of bookmarks/favorites, if the base domain's first character can not be determined (for instance for a local IP URL), the first character of the bookmark will be used.
- All other favicon locations can display regular favicons or apple-touch-icons depending on which is found.
    - If no favicons are found, monogram icon is used
- Favicons that are mostly transparent around the outside edges will include a small padding around the edges for nicer visibility (i.e. Reddit icon is a rounded circle, and looks funny when it is placed edge-to-edge.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.18(20.06.26.17)
- Verified favicons are properly shown for favourites on a clean install
- Verified favicons are retained correctly when upgrading from an older version
- Verified when favicon is not available or low-resolution icon is found it falls back to monogram icon using letter 
- Verified Monogram letter uses a random colour when adding a favourite/bookmark
- Verified when no icon/letter available it uses the first character of bookmark
- Verified favicons are properly shown in both bookmarks and favourites
- Verified favicons are transparent around the edges 
----------------------------
Verification passed on iPhone 7+ with iOS 13.5.1 running 1.18(20.06.26.17)
- Verified favicons are properly shown for favourites on a clean install
- Verified favicons are retained correctly when upgrading from an older version
- Verified when favicon is not available or low-resolution icon is found it falls back to monogram icon using letter 
- Verified Monogram letter uses a random colour when adding a favourite/bookmark
- Verified when no icon/letter available it uses the first character of bookmark
- Verified favicons are properly shown in both bookmarks and favourites
- Verified favicons are transparent around the edges 
----------------------------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.18(20.06.26.17)
- Verified favicons are properly shown for favourites on a clean install
- Verified favicons are retained correctly when upgrading from an older version
- Verified when favicon is not available or low-resolution icon is found it falls back to monogram icon using letter 
- Verified Monogram letter uses a random colour when adding a favourite/bookmark
- Verified when no icon/letter available it uses the first character of bookmark
- Verified favicons are properly shown in both bookmarks and favourites
- Verified favicons are transparent around the edges 
----------------------------
Verification passed on iPad Pro with iOS 13.6 running 1.18(20.06.26.17)
- Verified favicons are properly shown for favourites on a clean install
- Verified favicons are retained correctly when upgrading from an older version
- Verified when favicon is not available or low-resolution icon is found it falls back to monogram icon using letter 
- Verified Monogram letter uses a random colour when adding a favourite/bookmark
- Verified when no icon/letter available it uses the first character of bookmark
- Verified favicons are properly shown in both bookmarks and favourites
- Verified favicons are transparent around the edges 
----------------------------
Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.06.26.17)
- Verified favicons are properly shown for favourites on a clean install
- Verified favicons are retained correctly when upgrading from an older version
- Verified when favicon is not available or low-resolution icon is found it falls back to monogram icon using letter 
- Verified Monogram letter uses a random colour when adding a favourite/bookmark
- Verified when no icon/letter available it uses the first character of bookmark
- Verified favicons are properly shown in both bookmarks and favourites
- Verified favicons are transparent around the edges
