### ISSUE TITLE
Remove "New Tab Location" Preference and decouple Brave new tab from it

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#258]
The new tab creation is still fairly tightly coupled with the HomePanel logic and FF's new tab location preference. Our `FavoritesViewController` is actually coupled with a tab thats pointing to `localhost/home#panel=0` instead of something simpler.

The preference and logic around showing our favorites is still coupled with the assumption that we have that preference, except since we don't have that preference in brave, its just defaulted to always be `topsites`.

Even if we bring back the new tab location preference (allowing the user's new tab to be a home page and such), it would be a good idea to remove the `localhost/home#panel=0` stuff, since we don't have specific panels.

See: `NewTabAccessors.swift` → `NewTabPage.url`

**Comment by iccub** [comment]
looks stale, can't find those files in the project at all, please reopen if it's still valid
