### ISSUE TITLE
Custom favicons sometimes have wrong scale

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2581]
### Description: 
Please note that bigger favicon refactor is coming.

### Steps to Reproduce 
Hard to repro
  1. Install custom homepage build
  2. Toggle background images settings on and off

**Actual result:** 
Sometimes icons will be stretched

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.17(20.5.26.16)
- Verified on clean install, custom favicons are properly scaled
- Verified turning off background images doesn't change the custom favicons 
- Verified switching between background image options doesn't change the custom favicons 
-------
Verification passed on iPhone 7+ with iOS 13.4.5 running 1.17(20.5.26.16)
- Verified on clean install, custom favicons are properly scaled
- Verified turning off background images doesn't change the custom favicons 
- Verified switching between background image options doesn't change the custom favicons 
-------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.17(20.5.26.16)
- Verified on clean install, custom favicons are properly scaled
- Verified turning off background images doesn't change the custom favicons 
- Verified switching between background image options doesn't change the custom favicons 
-------
Verification passed on iPad Pro with iOS 13.4.5 running 1.17(20.5.26.16)
- Verified on clean install, custom favicons are properly scaled
- Verified turning off background images doesn't change the custom favicons 
- Verified switching between background image options doesn't change the custom favicons 
-------
Verification passed on iPad Pro with iOS 12.4.5 running 1.17(20.5.26.16)
- Verified on clean install, custom favicons are properly scaled
- Verified turning off background images doesn't change the custom favicons 
- Verified switching between background image options doesn't change the custom favicons 
-------
