### ISSUE TITLE
Display rewards-internals information upfront in text

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-ios#2583]
### Description: 

On iOS, there is no equivalent of `brave://rewards-internals`. Instead, users navigate to _Settings > Brave Rewards > Wallet Creation Info_, and then have an option to copy the rewards-internals information to their clipboard ("Copy support info").

In many support cases (e.g., wanting to check whether a user's device is supported, enrolled, etc.), this introduces additional friction into the support process, since users must first (1) copy to clipboard, then (2) open some other app to paste the details, before being able to report the values.

![image](https://user-images.githubusercontent.com/11497541/82936575-cb9b9480-9f5c-11ea-9f20-4b79f0900d16.png)

### Proposed Solution:

Display the rewards-internals information upfront in text under _Settings > Brave Rewards > Wallet Creation Info_, while also keeping the easy "copy to clipboard" button. (Unhide the rewards-internals information from under an additional press/copy-paste.)

**Comment by NejcZdovc** [comment]
closing in favour  of https://github.com/brave/brave-ios/issues/2617
