### ISSUE TITLE
Super Referral Clipboard Check Improvements

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#2584]
### Description: 

Currently when the app launches, it checks the clipboard for a referral code. Following this, it pings the server to retrieve a download id. If this fetch fails, and the app is thrown from memory, it will read from the clipboard again.

The clipboard may have been cleared, but it will still attempt to look at it, and will even replace the ref-code if a new one exists.

A check should be added to prevent re-reading from the clipboard.

Related:
https://github.com/brave/brave-ios/pull/2574/files#r431366934
https://github.com/brave/brave-ios/pull/2574
https://github.com/brave/brave-ios/pull/2535

### Steps to Reproduce 
  1. Copy a referral link (or retrieve from website) `F83AB73F-9852-4F01-ABA8-7830B8825993:ABC123`
  1. Disable internet
  1. Launch Brave (reads from clipboard)
  1. See ref code in settings
  1. Force quit Brave
  1. Copy new ref code (`F83AB73F-9852-4F01-ABA8-7830B8825993:XYZ789`)
  1. Re-open Brave (internet still off)
  1. Look at clipboard, see new ref-code

**Actual result:** 

Ref code is replaced

**Expected result:**

Old ref code should not be overwritten

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100%

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by GeetaSarvadnya** [comment]
Verification passed on iPhone 8 with iOS 13.3.1 running 1.17(20.5.27.21)
- Verified that old ref code is not replaced with new ref code when the internet is OFF
- Verified that custom assets are shown in NTP's also download_id is shown in View URP logs when the internet is reconnected.

---------
Verification passed on 1.17(20.5.27.21) on iPhone SE (iOS 12.4)
- Verified that old ref code is not replaced with new ref code when the internet is OFF
- Verified that custom assets are shown in NTP's also download_id is shown in View URP logs when the internet is reconnected.
- Also verified on Release channel
-------
Verification passed on iPhone XR with iOS 13.5 running 1.17(20.5.27.21)
- Verified old ref code is not replaced when the browser is launched without network access
- Verified after connecting to network custom assets are downloaded and download id is set correctly 
- Verified the above steps on Release channel as well 
--------
Verification passed on iPhone 7+ with iOS 13.4.5 running 1.17(20.5.27.21)
- Verified old ref code is not replaced when the browser is launched without network access
- Verified after connecting to network custom assets are downloaded and download id is set correctly 
- Verified the above steps on Release channel as well 
--------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.17(20.5.27.21)
- Verified old ref code is not replaced when the browser is launched without network access
- Verified after connecting to network custom assets are downloaded and download id is set correctly 
- Verified the above steps on Release channel as well 
--------
Verification passed on iPad Pro with iOS 13.4.5 running 1.17(20.5.27.21)
- Verified old ref code is not replaced when the browser is launched without network access
- Verified after connecting to network custom assets are downloaded and download id is set correctly 
- Verified the above steps on Release channel as well 
--------
Verification passed on iPad Pro with iOS 12.4.5 running 1.17(20.5.27.21)
- Verified old ref code is not replaced when the browser is launched without network access
- Verified after connecting to network custom assets are downloaded and download id is set correctly 
- Verified the above steps on Release channel as well 
--------

Verification passed on iPad 5th Gen with iOS 12 running 1.17(20.5.27.21)
- Reproduced the issue using 1.17 (20.05.27.15)
- Verified old ref code is not replaced when the browser is launched without network access
- Verified after connecting to network custom assets are downloaded and download id is set correctly 
- Verified the above steps on Release channel as well
