### ISSUE TITLE
Initial DAU Ping Sent without Ref Code when Not using Clipboard

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#2586]
### Description: 
Found while testing https://github.com/brave/brave-ios/pull/2535

When running thru `Fallback to Standard System` test case from above PR, my DAU ping was sent without my promo code. Per internal discussions (https://bravesoftware.slack.com/archives/C06UXF3KJ/p1590597370287800), it seems this is likely because the ping was sent before the ref code was obtained (and thus, not shown in the logs). It's possibly a race condition not accounted for.

Note - while testing other scenarios in this PR (such as `Clipboard Full Test`), DAU ping was displayed in logs and did contain ref code.

### Steps to Reproduce 

1. Visit normal referral page (not SR)
1. Click Download
1. Download Brave through TF
1. Open Brave
1. Verify that correct ref code shows up in settings
1. Open URP logs (only available on dev TF build)

**Actual result:** 
No ping displayed: (note - this was discussed and a ping is being sent, but because it does not contain the URP code is not shown in logs)
![Scenario3-Fallback to Standard System](https://user-images.githubusercontent.com/28145373/83073125-e6920580-a03d-11ea-99e8-ce3168faef00.png)

**Expected result:**
Ping:
![Scenario2 - ClipboardFullTest](https://user-images.githubusercontent.com/28145373/83073114-e3971500-a03d-11ea-9f55-2b9fea2b458a.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily with this scenario

**Brave Version:** 
1.17 (20.05.27.15)

**Device details:** 
iPad iOS12

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
On implementation, we should only perform a DAU ping when `Preferences.URP.referralLookupOutstanding.value` is `false`.

If it is `true`, perform normal DAU ping, otherwise do not.

After URP server request is made (either to the `/ua` or `/nonua` endpoint), wait until `referralLookupOutstanding` is set, then perform the ping. On subsequent launches the launch check should handle subsequent DAU pings.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.1 running 1.21(20.11.2.20)
- Verified DAU ping  is sent with ref code and is initialized as well
![image](https://user-images.githubusercontent.com/17010094/98275634-c0797580-1f8c-11eb-889b-cf3adff6d6a0.png)

---------------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.11.2.20)
- Verified DAU ping  is sent with ref code and is initialized as well
![image](https://user-images.githubusercontent.com/17010094/98275669-ce2efb00-1f8c-11eb-82b0-9c6cabd2429d.png)

---------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.11.2.20)
- Verified DAU ping  is sent with ref code and is initialized as well
![image](https://user-images.githubusercontent.com/17010094/98275614-b6f00d80-1f8c-11eb-883a-f34c63db47df.png)
