### ISSUE TITLE
super referral promo did not terminate

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#2588]
### Description: 
Super referral promo termination testing was done and the SR promo did not terminate on my iPad devices, but it did terminate on @btlechowski iPhone. This should be investigated further - not sure if this is an iPad only issue.

### Steps to Reproduce 
  1. Use clipboard method (OXB363) to copy necessary code.
  2. Install 1.17 from TF (did this for both prod and dev TF versions).
  3. Confirmed I was seeing the expected assets.
  4. @bsclifton terminated the SR campaign on the server (see him for more info on how to do this if you need it)
  5. Waited 1hr, 2hr, etc - SR promo was not terminated for me. Close/relaunch, did not matter. However, the promo did terminate for @btlechowski .

**Actual result:** 
super referral promo not terminated

**Expected result:**
super referral promo to be terminated

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.17 (20.05.27.21)

**Device details:** 
iPad 5th gen with iOS12 and iPad mini with iOS13

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc @brave/legacy_qa

**Comment by iccub** [comment]
closing for now, we can revisit once super referrals are back
