### ISSUE TITLE
Expand Rewards to three decimal places

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#2596]
See https://github.com/brave/brave-browser/issues/10027

> Currently the estimated pending rewards display on the brave://rewards page, the estimated pending rewards display on the new tab page widget, and the ad grant claimed amounts round to one decimal place. They should round to 3 decimal places so that users can see ads that yield less than 0.1 BAT per view

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.19(20.07.16.15)
- Verified rewards value has 3 decimal places
------------
Verification passed on iPhone 7+ with iOS 13.5.1 running 1.19(20.07.16.15)
- Verified rewards value has 3 decimal places
------------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.19(20.07.16.15)
- Verified rewards value has 3 decimal places
------------
Verification passed on iPad Pro with iOS 13.6 running 1.19(20.07.16.15)
- Verified rewards value has 3 decimal places
------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.19(20.07.16.15)
- Verified rewards value has 3 decimal places
------------
Logged follow up issue https://github.com/brave/brave-ios/issues/2721 for missing 3 decimal places
