### ISSUE TITLE
Add support for US state level targeting #2383

### ISSUE THREAD

**Issue by moritzhaller** [brave/brave-ios#2597]
Related PR: https://github.com/brave/brave-core/pull/5602/

### Description:
Add support for US subdivision ad targeting ("state-level targeting"). UI changes include a checkbox and dropbox in the ads settings (see screenshot from Desktop below)

<img width="646" alt="Screenshot 2020-06-03 at 07 11 36" src="https://user-images.githubusercontent.com/1259879/83601991-95b46c80-a569-11ea-92ea-facca89a729e.png">

**Comment by iccub** [comment]
closing as stale, freel free to reopen if its still valid, we are pretty limited with Rewards on iOS though
