### ISSUE TITLE
Add 14day retention stat

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2598]

**Comment by kjozwiak** [comment]
@srirambv setup a call with @keur and @iccub and we went through the following:

* ensured that the daily ping is being sent when downloading organically, confirmed ping appears via backend
* ensured that the daily ping is being sent when downloading via a referral, confirmed ping appears via backend
* ensured that the daily ping is being sent when downloading via a super referral, confirmed ping appears via backend

Went through the following devices:

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` - **PASSED**

* Verified daily usage ping is sent when installing organically (via TF without any referrals)
* Verified daily usage ping is sent when installing via https://brave.com/bts (SR)
* Verified daily usage ping is sent when installing via https://brave.com/?ref=red194 (referral)

Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` - **PASSED**

* Verified daily usage ping is sent when installing organically (via TF without any referrals)
* Verified daily usage ping is sent when installing via https://brave.com/bts (SR)
* Verified daily usage ping is sent when installing via https://brave.com/?ref=mim331 (referral)

----------

Verification passed on iPhone 7+ with iOS 13.5.1 running 1.19(20.07.21.11)
- Verified daily usage ping is sent for organic installs
- Verified daily usage ping is sent for Super referral installs(Rush Gaming)
- Verified daily usage ping is sent for referral install (`https://brave.com/SRI433`)

Verification passed on iPad Pro with iOS 13.6 running 1.19(20.07.21.11)
- Verified daily usage ping is sent for organic installs
- Verified daily usage ping is sent for Super referral installs(Rush Gaming)
- Verified daily usage ping is sent for referral install (`https://brave.com/SRI433`)

@keur verified backend ping capture for the above scenarios
------
