### ISSUE TITLE
Super Referrer - QR Code

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2599]
### Description: 

Super Referrer (SR) uses an enhanced referrer tracking system. On iOS, we do this by directing users to a landing page and copying a referral code. 

The SR link is slightly different to the normal referrer link. 

The QR code on the SR custom home page uses the normal referrer link, we need to change this so that URL link for the QR code can be entered in the .json file. 

Link: https://bravesoftware.slack.com/archives/CT7JC4KBM/p1591227697202100

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.18(20.06.23.18)
- Verified QR code has the link in format `https://brave.com/r/<refCode>`
-------
Verification passed on iPhone 7+ with iOS 13.5.1 running 1.18(20.06.23.18)
- Verified QR code has the link in format `https://brave.com/r/<refCode>`
-------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.18(20.06.23.18)
- Verified QR code has the link in format `https://brave.com/r/<refCode>`
-------
Verification passed on iPad Pro with iOS 13.6 running 1.18(20.06.23.18)
- Verified QR code has the link in format `https://brave.com/r/<refCode>`
-------
Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.06.23.18)
- Verified QR code has the link in format `https://brave.com/r/<refCode>`
-------
