### ISSUE TITLE
Menus do not appear on YouTube.com

### ISSUE THREAD

**Issue by Coro365** [brave/brave-ios#2600]
When I run Brave on my iPad and browse youtube.com (New Desktop version), I can't see the settings, etc. when I tap the user icon on the top right.
(The waiting circle will appear forever.)

The following will not always be displayed
* Tap the user icon to display the settings and language selection screen.
* Notification screen

The following are often not displayed
* Library and History are displayed when you tap on the burger menu.

This happens even when Brave Shields is off.
This did not happen with Safari (iOS), Chrome (iOS) and Bravee (macOS)

Thank you for a great app and ad-free, comfortable internet!

![burger](https://user-images.githubusercontent.com/6727442/83739420-8714a500-a690-11ea-970a-b6cbcc274405.PNG)
![notification](https://user-images.githubusercontent.com/6727442/83739439-8c71ef80-a690-11ea-9729-d81d5c9dc769.PNG)
![setting](https://user-images.githubusercontent.com/6727442/83739443-8da31c80-a690-11ea-8fc9-b71d4535e00d.PNG)

iPad 6th generation
Modele MR7J2J/A
iOS 13.5.5 (beta)
Brave for iOS version 1.17 (20.05.27.21)

**Comment by iccub** [comment]
Does it still happen to you? I can't repro
