### ISSUE TITLE
Etags must be double quoted for NTP SI

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2602]
### Description: 
We never hit cache because etag is trimmed of `"` character.

### Steps to Reproduce 
  1. 
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by bsclifton** [comment]
Once this is fixed, we can back out the changes made with https://github.com/brave/devops/issues/3173 by letting @bkero know OR creating a follow up task to let him know once enough users have the fix 😄

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 13.5.1 running 1.18(20.06.26.17)
- Verified test plan from #2623
- Verified SR images are retained between app launches
------------------------
Verification passed on iPhone XR with iOS 13.5 running 1.18(20.06.26.17)
- Verified test plan from #2623
- Verified SR images are retained between app launches
------------------------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.18(20.06.26.17)
- Verified test plan from #2623
- Verified SR images are retained between app launches
------------------------
Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.06.26.17)
- Verified test plan from #2623
- Verified SR images are retained between app launches
------------------------
Verification passed on iPad Pro with iOS 13.6 running 1.18(20.06.26.17)
- Verified test plan from #2623
- Verified SR images are retained between app launches
