### ISSUE TITLE
Remove etag server side hotfix

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2603]
Once this client side bugfix https://github.com/brave/brave-ios/issues/2602 is ready we should consider removing the server side hotfix.

If there's still too many users on older iOS versions this ticket will be bumped to next release.

**Comment by bsclifton** [comment]
@iccub what would the fix for the server side look like?

**Comment by iccub** [comment]
We have to remove some code on server side @bsclifton, i will try to dig an old thread pointing to it
