### ISSUE TITLE
Embed the favicon of Coinmarketcap in app 

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#2604]
This avoid request to `coinmarketcap` on first launch.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.18(20.06.18.18)
- Verified CoinMarketCap tile shows the correct favicon on install
-------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.18(20.06.18.18)
- Verified CoinMarketCap tile shows the correct favicon on install
-------
Verification passed on iPhone 7+ with iOS 13.5.1 running 1.18(20.06.18.18)
- Verified CoinMarketCap tile shows the correct favicon on install
-------
Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.06.18.18)
- Verified CoinMarketCap tile shows the correct favicon on install
-------
