### ISSUE TITLE
Custom favorites are loaded on every app launch

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#2605]
### Description: 
Requests to favorites should not be initiated on startup.

### Steps to Reproduce 
  1. Add a few sites to favorites
  2. Restart the browser
  3. Network requests are sent for all favorites.

**Actual result:** 
Requests are sent for all favorites

**Expected result:**
Requests should not be sent without user interaction.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
Development version (commit id: f315a244403db78ff6f5b8fe4796b2ee305b632f)

**Device details:** 
iPhone SE

**Comment by kylehickinson** [comment]
In addition: When we parse HTML for favicons we should look for all favicons mimicking logic of metadata parser, meaning we will still save a small favicon even if we're looking for a larger one
