### ISSUE TITLE
Print from Brave

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2610]
### Description: 
https://appfigures.com/reviews/42132121512LuqXyegZ0ajcxqNz6Du_xkQ?lang=en

It seems like print from Brave is missing

If Yes, please implement the standard iOS Print option

**Comment by johnsfuller** [comment]
Please provide your app and device versions. If I follow these steps with the most recent app and iOS, then it works.
1. Tap the ellipsis menu
2. tap "share with..."
3. scroll down and look for "print"

**Comment by soner-yuksel** [comment]
Yes the printing option can be exactly accessed like @johnsfuller mentioned, The standard share sheet supports printing by default.

Visualization of the steps:

![Print](https://user-images.githubusercontent.com/6643505/98867974-733e4d80-243d-11eb-8bc8-0be015fa1ef8.png)

**Comment by iccub** [comment]
I'm going to move this ticket to 1.23 for QA to verify

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air (3rd Gen)` on `iOS 14.3` using the following build:

```
1.23 (21.1.28.17)
```

* downloaded `Epson iPrint` and enabled/setup AirPrint for my specific printer (needed the App)
* opened http://www.orimi.com/pdf-test.pdf
* selected `Settings` -> `Share with...` -> `Print`
* ensured that taping on `Cancel` closed the modal
* ensured local printer was selected and clicked on `Print`
* ensured that printing worked as expected

![IMG_0180](https://user-images.githubusercontent.com/2602313/106559134-f4fcbf00-64f2-11eb-8333-265993e26a69.png)
 
Verification **PASSED** on `iPad Mini 4` on `iOS 13.7` using the following build:

```
1.23 (21.1.28.17)
```

* downloaded `Epson iPrint` and enabled/setup AirPrint for my specific printer (needed the App)
* opened http://www.orimi.com/pdf-test.pdf
* selected `Settings` -> `Share with...` -> `Print`
* ensured that taping on `Cancel` closed the modal
* ensured local printer was selected and clicked on `Print`
* ensured that printing worked as expected

![IMG_0432](https://user-images.githubusercontent.com/2602313/106559205-1198f700-64f3-11eb-94ef-7654ec16faa0.png)

Verification **PASSED** on `iPhone 11` on `iOS 14.4` using the following build:

```
1.23 (21.1.28.17)
```

* downloaded `Epson iPrint` and enabled/setup AirPrint for my specific printer (needed the App)
* opened http://www.orimi.com/pdf-test.pdf
* selected `Settings` -> `Share with...` -> `Print`
* ensured that taping on `Cancel` closed the modal
* ensured local printer was selected and clicked on `Print`
* ensured that printing worked as expected

**`Example`** | **`Example`**
---------------|-----------------
![IMG_3519](https://user-images.githubusercontent.com/2602313/106559269-2c6b6b80-64f3-11eb-8f4f-4c5d56a83294.png)  | ![IMG_3520](https://user-images.githubusercontent.com/2602313/106559281-2ffef280-64f3-11eb-9f92-046581910d53.png)

Verification **PASSED** on `iPhone 6+` on `iOS 12.4.1` using the following build:

```
1.23 (21.1.28.17)
```

* downloaded `Epson iPrint` and enabled/setup AirPrint for my specific printer (needed the App)
* opened http://www.orimi.com/pdf-test.pdf
* selected `Settings` -> `Share with...` -> `Print`
* ensured that taping on `Cancel` closed the modal
* ensured local printer was selected and clicked on `Print`
* ensured that printing worked as expected

**`Example`** | **`Example`**
---------------|-----------------
![IMG_0089](https://user-images.githubusercontent.com/2602313/106560444-09da5200-64f5-11eb-9e92-9758b99ec85f.png) | ![IMG_0091](https://user-images.githubusercontent.com/2602313/106560459-0d6dd900-64f5-11eb-9c09-b53f8519e825.png)
