### ISSUE TITLE
Use updated URLs for adblock data

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2611]
Should use `ios` directory instead of `iOS13` directory on s3.

## Test Case:

- Ensure ads are blocked and adblock in general works correctly
- Verify regional adblock works as well

**Comment by LaurenWags** [comment]
Verification passed on iPad 5th Gen with iOS 12 running `1.18 (20.06.24.15)`
   * generally confirmed ad block looks good on sites like buzzfeed, nyt, cnn, etc.
   * specifically visited sites w/ embedded YT videos (https://www.pcmag.com/news/the-best-vr-games-for-2019 and https://www.buzzfeed.com/spenceralthouse/funniest-tv-show-moments-ever were good examples as they each have a bunch of embedded YT videos)
   * confirmed no pre-roll ads seen when shields up
   * confirmed putting shields down did show ads on pages visited and on some YT videos (embedded or not)

-----
Verification passed on iPhone XR with iOS 13.5 running  1.18(20.06.24.15)
- Verified Adblock works fine on all sites
- Verified Adblock works on media sites like YT
- Verified Adblock works on embedded YT videos on sites 
- Verified Adblock works fine on both normal and private tabs
- Verified site-specific Adblock settings work fine
- Verified no pre-roll or post-video ads on YT when shields are up
- Verified toggling Adblock in shields reloads the page and shows/blocks the ads
---------------------------

Verification passed on iPhone 7+ with iOS 13.5.1 running  1.18(20.06.24.15)
- Verified Adblock works fine on all sites
- Verified Adblock works on media sites like YT
- Verified Adblock works on embedded YT videos on sites 
- Verified Adblock works fine on both normal and private tabs
- Verified site-specific Adblock settings work fine
- Verified no pre-roll or post-video ads on YT when shields are up
- Verified toggling Adblock in shields reloads the page and shows/blocks the ads
---------------------------

Verification passed on iPhone 6 with iOS 12.4.7 running  1.18(20.06.24.15)
- Verified Adblock works fine on all sites
- Verified Adblock works on media sites like YT
- Verified Adblock works on embedded YT videos on sites 
- Verified Adblock works fine on both normal and private tabs
- Verified site-specific Adblock settings work fine
- Verified no pre-roll or post-video ads on YT when shields are up
- Verified toggling Adblock in shields reloads the page and shows/blocks the ads
---------------------------

Verification passed on iPad Pro with iOS 13.6 running  1.18(20.06.24.15)
- Verified Adblock works fine on all sites
- Verified Adblock works on media sites like YT
- Verified Adblock works on embedded YT videos on sites 
- Verified Adblock works fine on both normal and private tabs
- Verified site-specific Adblock settings work fine
- Verified no pre-roll or post-video ads on YT when shields are up
- Verified toggling Adblock in shields reloads the page and shows/blocks the ads
---------------------------

Verification passed on iPad Pro with iOS 12.4.5 running  1.18(20.06.24.15)
- Verified Adblock works fine on all sites
- Verified Adblock works on media sites like YT
- Verified Adblock works on embedded YT videos on sites 
- Verified Adblock works fine on both normal and private tabs
- Verified site-specific Adblock settings work fine
- Verified no pre-roll or post-video ads on YT when shields are up
- Verified toggling Adblock in shields reloads the page and shows/blocks the ads
---------------------------

Verification passed on iPhone 8 with iOS 13.3.3 running  1.18(20.06.24.15)
- Verified Adblock works fine on all sites
- Verified Adblock works on media sites like YT
- Verified Adblock works on embedded YT videos on sites 
- Verified Adblock works fine on both normal and private tabs
- Verified site-specific Adblock settings work fine
- Verified no pre-roll or post-video ads on YT when shields are up
- Verified toggling Adblock in shields reloads the page and shows/blocks the ads
