### ISSUE TITLE
Add additional Rewards Internal information to match desktop

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2617]
Desktop 1.11.x & nightly includes a new suite of rewards internals support information including:

- [ ] General info
- [ ] Logs (Last 5k lines)
- [ ] Promotions
- [ ] Contributions
- [ ] _Soon_: Export DB

That should also be added to iOS. Most of this should be able to be shared to support using the native share sheet.

While doing this we will also make this fully native (#2583) and also will ref the logs ticket already existing: #2601

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.1 running 1.21(20.10.27.20)
- Verified rewards internal information is shown correctly 

Wallet info | Promotions | Contirbutions (One-time tip) | Contributions (Recurring tip) | Contributions (AC) | Share rewards internals | Save file
-- | -- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/97542691-1e232600-19bf-11eb-8252-e76a10f98117.png) | ![image](https://user-images.githubusercontent.com/17010094/97542869-617d9480-19bf-11eb-9839-ff96da430be3.png) | ![image](https://user-images.githubusercontent.com/17010094/97543381-11eb9880-19c0-11eb-831c-c487d981ab32.png) | ![image](https://user-images.githubusercontent.com/17010094/97543410-1a43d380-19c0-11eb-88e4-08cf1d56e352.png) | ![image](https://user-images.githubusercontent.com/17010094/97543441-229c0e80-19c0-11eb-806a-89ba0863e29e.png) | ![image](https://user-images.githubusercontent.com/17010094/97543463-30519400-19c0-11eb-9706-d1a1017d6aa7.png) | ![image](https://user-images.githubusercontent.com/17010094/97543495-3b0c2900-19c0-11eb-837d-9fe5182a6cac.png)

- Logged #2995 

--------------------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.27.20)
- Verified rewards internal information is shown correctly 

Wallet info | Promotions | Contirbutions (One-time tip) | Contributions (Recurring tip) | Contributions (AC) | Contributions (AC list) | Share rewards internals | Save file
-- | -- | -- | -- | -- | -- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/97546699-b243bc00-19c4-11eb-8a1a-86dd1a91eb47.png) | ![image](https://user-images.githubusercontent.com/17010094/97546707-b5d74300-19c4-11eb-9ce4-fe35f499bd38.png) | ![image](https://user-images.githubusercontent.com/17010094/97546718-bb348d80-19c4-11eb-944c-a4b56a145e73.png) | ![image](https://user-images.githubusercontent.com/17010094/97546738-c12a6e80-19c4-11eb-925f-a2f126f464e9.png) | ![image](https://user-images.githubusercontent.com/17010094/97546752-c5ef2280-19c4-11eb-99e2-65f754276216.png) | ![image](https://user-images.githubusercontent.com/17010094/97546758-c8ea1300-19c4-11eb-9236-3b1d5a3ba184.png) | ![image](https://user-images.githubusercontent.com/17010094/97546777-cc7d9a00-19c4-11eb-87b0-8f7a171c2f7a.png) | ![image](https://user-images.githubusercontent.com/17010094/97546789-d0112100-19c4-11eb-8174-4354e3cab233.png)
--------------------
--------------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.10.27.20)
- Verified rewards internal information is shown correctly 

Wallet info | Promotions | Contirbutions (One-time tip) | Contributions (Recurring tip) | Contributions (AC) | Contributions (AC list) | Share rewards internals | Save file
-- | -- | -- | -- | -- | -- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/97550042-0d77ad80-19c9-11eb-806f-16042d962497.png) | ![image](https://user-images.githubusercontent.com/17010094/97550030-09e42680-19c9-11eb-95e8-d4472d2bafe8.png) | ![image](https://user-images.githubusercontent.com/17010094/97550057-12d4f800-19c9-11eb-9394-4c504d51ee9c.png) | ![image](https://user-images.githubusercontent.com/17010094/97550193-43b52d00-19c9-11eb-9ff7-959f3abc55ae.png) | ![image](https://user-images.githubusercontent.com/17010094/97550392-8aa32280-19c9-11eb-9cde-a10ede247891.png) | ![image](https://user-images.githubusercontent.com/17010094/97550406-8ecf4000-19c9-11eb-8db2-4fcc60a7537b.png) | ![image](https://user-images.githubusercontent.com/17010094/97550420-92fb5d80-19c9-11eb-9906-3e932db38803.png) | ![image](https://user-images.githubusercontent.com/17010094/97550438-968ee480-19c9-11eb-91f8-1e6fffb50f61.png)
