### ISSUE TITLE
Rendering issues on http://lookfantastic.com/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-ios#2621]
### Description: 
Rendering issues on `http://myprotein.com/` and `http://lookfantastic.com/`

### Steps to Reproduce 
  1.  Visiting `http://lookfantastic.com/` would cause rendering issues as the user scrolled.
  2.
  3.

**Actual result:** 
https://youtu.be/NUbQ7pKVEhI  (Unlisted)

**Expected result:**
Expect user to scroll without rendering of page breaking

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
User who reported this was using an iPhone 6S, indicated partners iPhone XR was okay rendering the page okay

**Brave Version:** 
1.17 (20.05.27.21

**Device details:** 
`iPhone 6s`

**Website problems only:**
- did you check with Brave Shields down?
`Had not affect`
- did you check in Safari/Firefox (WkWebView-based browsers)? 
`Confirmed Safari is fine`

### Additional Information

User is now on iOS 13.5.1, and still experiencing page rendering issues. 

`There’re a few websites built on Ingenuity (web-tech) that don’t load correctly on mobile (at least iOS) in Brave, such as myprotein.com and lookfantastic.com I reckon other sites built on Ingenuity also won’t work right`

**Comment by iccub** [comment]
Seems to be resolved now, closing
