### ISSUE TITLE
BAT Confirmations should not be started if Rewards is disabled

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#2629]
### Description: 
Logging per https://github.com/brave/brave-core/pull/5424

Above PR fixes https://github.com/brave/brave-browser/issues/9544 and per the PR it should also be checked on iOS.

See above issue/PR for more information.

cc @srirambv 

### Additional Information
cc @kylehickinson to review and place in appropriate milestone as this code might already be in iOS

**Comment by kylehickinson** [comment]
Code is already in iOS as our current BraveRewards framework is built off of `1.10.52` and this was merged at `1.10.28`, meaning its already shipping in 1.17. This milestone is closed however so I can't add it to that. @LaurenWags Do you want me to add it to 1.18 to test in iOS or fine to leave it?

Here is the PR that merged this change inadvertently: https://github.com/brave/brave-ios/pull/2566

**Comment by LaurenWags** [comment]
let's test with next iOS release that goes out unless @srirambv feels differently 👍
