### ISSUE TITLE
Update adblock-rust lib

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2630]
It's been almost a year since we updated it, now that we update adblock resources https://github.com/brave/brave-ios/issues/2611 we should revisit it and update so we don't catch any breaking changes

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.18(20.06.22.18)
- Verified no ads shown on pages while browsing
- Verified no ads(skippable/non-skippable) on YT videos 
---------
Verification passed on iPhone 7+ with iOS 13.5.1 running 1.18(20.06.23.18)
- Verified no ads shown on pages while browsing
- Verified no ads(skippable/non-skippable) on YT videos 
---------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.18(20.06.23.18)
- Verified no ads shown on pages while browsing
- Verified no ads(skippable/non-skippable) on YT videos 
---------
Verification passed on iPad Pro with iOS 13.6 running 1.18(20.06.23.18)
- Verified no ads shown on pages while browsing
- Verified no ads(skippable/non-skippable) on YT videos 
---------
Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.06.23.18)
- Verified no ads shown on pages while browsing
- Verified no ads(skippable/non-skippable) on YT videos
