### ISSUE TITLE
Show Adblock version (or date) in Settings

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#2642]
## Problem Description 
The content blocking scripts we use for iOS are hosted in S3. It would be great if there was a way to tell which "version" was there so we could ensure we're up to date

## Design
Maybe there can be a date or version field in the `About` section, near the product version?
![ios](https://user-images.githubusercontent.com/4733304/84962629-29cf1980-b0bc-11ea-88c2-43d668612674.jpg)

**Comment by anthonypkeane** [comment]
Can you make the scroll so that the user has to pull down further than the bottom to show this? (I can explain 
on a call)

![Ad Block Update](https://user-images.githubusercontent.com/7606853/85093749-f49cf700-b1a1-11ea-9f1c-619ad05e58f0.jpeg)

**Comment by kylehickinson** [comment]
@anthonypkeane I thought this only had to be available for QA and we were just going to add the date to the Adblock debug screen?

**Comment by bsclifton** [comment]
We can do this as QA only for now - basically would be great to see the date associated (file timestamp in S3) - @kylehickinson mentioned we have ETag already (we just don't have a way for QA to know what the ETag is)
![image](https://user-images.githubusercontent.com/4733304/87969983-ef201e80-ca77-11ea-90ef-faf97b73750f.png)

Let's just add `Date` to the above (along with ETag and rule count)

**Comment by bsclifton** [comment]
Nice work on this 😄

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.0.1 running 1.21(20.09.28.16) dev build
- Verified Adblock details are shown under settings
![image](https://user-images.githubusercontent.com/17010094/94567097-fe370000-0262-11eb-8574-befa6136a496.png)

-----------------
Verification passed on iPad Pro with iOS 14.0.1 running 1.21(20.09.28.16) dev build
- Verified Adblock details are shown under settings
![image](https://user-images.githubusercontent.com/17010094/94567051-f6775b80-0262-11eb-91fe-1a960d79e197.png)

-----------------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.09.28.16) dev build
- Verified Adblock details are shown under settings
![image](https://user-images.githubusercontent.com/17010094/94566995-e95a6c80-0262-11eb-9414-2b566653a5ed.png)

-----------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.09.28.16) dev build
- Verified Adblock details are shown under settings
![image](https://user-images.githubusercontent.com/17010094/94567016-ef504d80-0262-11eb-8ba1-f929c323575a.png)
