### ISSUE TITLE
Some NTP shows `Show more` button 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2645]
### Description: 
Some NTP shows `Show more` button 

### Steps to Reproduce 
No idea how to reproduce

**Actual result:** 
See comment below for screenshot. Removed the old one as it only showed version info (messed up recording)

**Expected result:**
Should not show `Show More` in NTP 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
No idea

**Brave Version:** 
1.18(20.06.16.08)

**Device details:** 
iPad may happen on iPhone as well 

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
Regression of #2578

**Comment by LaurenWags** [comment]
I can reproduce this with these steps using `1.18 (20.06.26.17)`
1. Have some sites in tabs open including at least one blank NTP
2. Go to one of the sites opened and add to Favorites (3 dots > Share with > Favorites)
3. Go to the already opened NTP.
4. See `Show More` (in the screenshot below you can see it hiding behind my settings)

![IMG_53013B0F327B-1](https://user-images.githubusercontent.com/28145373/86176758-715d9880-baf3-11ea-902a-998f3f64044a.jpeg)
![IMG_711A48740757-1](https://user-images.githubusercontent.com/28145373/86176984-dca76a80-baf3-11ea-95d3-c92bcd709def.jpeg)

5. However, if I open another NTP, that second one won't have `Show More`

![IMG_B628B904749D-1](https://user-images.githubusercontent.com/28145373/86176987-e03af180-baf3-11ea-9413-5f3c04f3ca8d.jpeg)

**Comment by iccub** [comment]
Should be fixed by https://github.com/brave/brave-ios/issues/2681
Please recheck in 1.19

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 13.6 running 1.19(20.07.15.13)
- Verified steps from https://github.com/brave/brave-ios/issues/2645#issuecomment-652043377
--------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.19(20.07.15.13)
- Verified steps from https://github.com/brave/brave-ios/issues/2645#issuecomment-652043377
--------------
Verification passed on iPhone XR with iOS 13.5 running 1.19(20.07.15.13)
- Verified steps from https://github.com/brave/brave-ios/issues/2645#issuecomment-652043377
--------------
Verification passed on iPhone 7+ with iOS 13.5.1 running 1.19(20.07.15.13)
- Verified steps from https://github.com/brave/brave-ios/issues/2645#issuecomment-652043377
--------------
Verification passed on iPhone 6 with iOS 12.4.5 running 1.19(20.07.15.13)
- Verified steps from https://github.com/brave/brave-ios/issues/2645#issuecomment-652043377
--------------
