### ISSUE TITLE
Remove CMC from top tiles

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2646]
Per conversation on https://bravesoftware.slack.com/archives/CQUHQ0PM3/p1592497047464200?thread_ts=1592342679.442400&cid=CQUHQ0PM3

Remove CMC from iOS top tiles and replace with support

URL for the Support link to follow

cc @Brave-Matt for the correct URL (ideally one for iOS specific support)

**Comment by Brave-Matt** [comment]
For Mobile support, the long link is: https://community.brave.com/c/support-and-troubleshooting/mobile-support/

We also have a shortened link:  https://brave.com/msupport

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13. 5 running 1.19(20.07.15.13)
- Verified CMC tile is replaced with Brave Support tile
- Clicking on the tile loads `https://brave.com/msupport` which redirects to `https://community.brave.com/c/support-and-troubleshooting/mobile-support/`
![image](https://user-images.githubusercontent.com/17010094/87660261-afdf8e00-c756-11ea-8cda-3bc6aceb0188.png)
-----

Verification passed on iPhone 7+ with iOS 13.5.1 running 1.19(20.07.15.13)
- Verified CMC tile is replaced with Brave Support tile on a clean install 
- Verified tile is not replaced on upgrade from older install
- Clicking on the tile loads `https://brave.com/msupport` which redirects to `https://community.brave.com/c/support-and-troubleshooting/mobile-support/`
![image](https://user-images.githubusercontent.com/17010094/87660350-d1407a00-c756-11ea-8a0d-efd12fa9ac31.png)

---------
Verification passed on iPad Pro with iOS 12.4.1 running 1.19(20.07.15.13)
- Verified CMC tile is replaced with Brave Support tile on a clean install 
- Verified tile is not replaced on upgrade from older install
- Clicking on the tile loads `https://brave.com/msupport` which redirects to `https://community.brave.com/c/support-and-troubleshooting/mobile-support/`
![image](https://user-images.githubusercontent.com/17010094/87660355-d43b6a80-c756-11ea-98df-2e388bf0c8d5.png)
---------
Verification passed on iPad Pro with iOS 113.6 running 1.19(20.07.15.13)
- Verified CMC tile is replaced with Brave Support tile on a clean install 
- Verified tile is not replaced on upgrade from older install
- Clicking on the tile loads `https://brave.com/msupport` which redirects to `https://community.brave.com/c/support-and-troubleshooting/mobile-support/`
![image](https://user-images.githubusercontent.com/17010094/87665669-313b1e80-c75f-11ea-85cd-fd6eaa612812.png)
-----------------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.19(20.07.15.13)
- Verified CMC tile is replaced with Brave Support tile on a clean install 
- Verified tile is not replaced on upgrade from older install
- Clicking on the tile loads `https://brave.com/msupport` which redirects to `https://community.brave.com/c/support-and-troubleshooting/mobile-support/`
