### ISSUE TITLE
Small Copy changes for Private tabs

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2648]
### Description: 
Some copy feedback from @pes10k 
Link: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1592529180466000?thread_ts=1592528199.462000&cid=C06UXF3KJ

the casing of “private tabs” is sometimes “Private Tabs”, and sometimes “private tabs” and sometimes “Private tabs”

Please change to all to Private Tabs

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.0.1 running 1.21(20.09.10.17)
- Verified all entries for private tabs is camel-cased 

Private tab new tab button | Normal tab new tab button | Private tab message | Long press context menu | Home screen long press menu
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/94428231-47fee800-0188-11eb-8ab8-bd1f6682d372.png) | ![image](https://user-images.githubusercontent.com/17010094/94428255-53521380-0188-11eb-8e12-f2c9af89edc8.png) |![image](https://user-images.githubusercontent.com/17010094/94428291-64028980-0188-11eb-9c1e-2efc4e81d2fb.png) | ![image](https://user-images.githubusercontent.com/17010094/94428322-6fee4b80-0188-11eb-9090-e429d2227700.png) | ![image](https://user-images.githubusercontent.com/17010094/94428366-809ec180-0188-11eb-985e-9439d514d74b.png)

-----------------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.09.10.17)
- Verified all entries for private tabs is camel-cased 

Private tab new tab button | Normal tab new tab button | Private tab message | Long press context menu | Home screen long press menu
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/94666172-06e01280-0305-11eb-88bb-37794ffa3654.png) | ![image](https://user-images.githubusercontent.com/17010094/94666135-f92a8d00-0304-11eb-820d-c2cff60accb4.png) |  ![image](https://user-images.githubusercontent.com/17010094/94665749-730e4680-0304-11eb-8206-c060a087551d.png) | ![image](https://user-images.githubusercontent.com/17010094/94666255-2840fe80-0305-11eb-822d-8dd4cdc21727.png) | ![image](https://user-images.githubusercontent.com/17010094/94666278-3131d000-0305-11eb-810d-02452c703307.png)

-----------------------

Verification passed on iPad Pro with iOS 13.6 running 1.21(20.09.10.17)
- Verified all entries for private tabs is camel-cased 

Private tab new tab button | Normal tab new tab button | Private tab message | Long press context menu | Home screen long press menu
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/94668868-7acfea00-0308-11eb-8955-3794cc0adb01.png) | ![image](https://user-images.githubusercontent.com/17010094/94668439-f0878600-0307-11eb-9677-acec79d2a61b.png) | ![image](https://user-images.githubusercontent.com/17010094/94668515-0dbc5480-0308-11eb-9caa-f69f0e447963.png) | ![image](https://user-images.githubusercontent.com/17010094/94668468-fc734800-0307-11eb-8187-bf7d28934a21.png) | ![image](https://user-images.githubusercontent.com/17010094/94668543-157bf900-0308-11eb-8dc2-e7a6de199eb3.png)

-----------------------

Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.09.10.17)
- Verified all entries for private tabs is camel-cased 

Private tab new tab button | Normal tab new tab button | Private tab message | Long press context menu | 
-- | -- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/94666972-13189f80-0306-11eb-89c0-076fda3845ba.png) | ![image](https://user-images.githubusercontent.com/17010094/94666998-1f9cf800-0306-11eb-99b6-c72b51dbd81b.png) | ![image](https://user-images.githubusercontent.com/17010094/94667024-29266000-0306-11eb-88d6-a0245863d25c.png) | ![image](https://user-images.githubusercontent.com/17010094/94667037-2fb4d780-0306-11eb-9c75-9a512c07d3bd.png)
