### ISSUE TITLE
Reader mode bug

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2649]
### Description: 

Noticed by @pes10k 

> if i enable reader mode, and the disable it, the “reader mode tool bar” still stays at the top of the page (the bar with the “Aa” in it)

![image](https://user-images.githubusercontent.com/7606853/85092346-5b201600-b19e-11ea-86a4-0e3941cbcaef.png)

https://bravesoftware.slack.com/archives/C06UXF3KJ/p1592529408466200?thread_ts=1592528199.462000&cid=C06UXF3KJ

**Comment by hennrynusasatria** [comment]
Hi All,

Firefox iOS does not have this Reader Mode bug, Brave iOS is based on Firefox iOS, thus it will be good if Brave iOS follow features updates (as well as bug fixes) from Firefox iOS codebase.

Thank you.

**Comment by kjozwiak** [comment]
Adding `release-notes/include` as we're fixing an issue that users have experienced on release.

**Comment by kjozwiak** [comment]
Verification **PASSED**  using the following build on the following platforms:

```
1.23 (21.1.28.17)
```

*  `iPad Air (3rd Gen)` on `iOS 14.3` - **PASSED**
* `iPad Mini 4` on `iOS 13.7` - **PASSED**
* `iPhone 11` on `iOS 14.4` - **PASSED**
* `iPhone 6+` on `iOS 12.4.1` - **PASSED**

Cases/STR used:

* ensured the enabling/disabling reader mode didn't leave the toolbar behind
* ensured that enabling reader mode and then closing Brave didn't leave the toolbar behind once Brave was relaunched
* ensured that enabling reader mode and editing the text size/colour didn't leave the toolbar behind after disabling reader mode
* ensured that the reader mode toolbar wasn't visible when switching tabs and than disabling reader mode in the original tab
* ensured that disabling reader mode on multiple tabs didn't leave the reader mode toolbar behind
* ensured the above worked on both normal and private tabs
