### ISSUE TITLE
Favicons not showing in private mode

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2650]
### Steps to Reproduce 
  1. Visit neowin.net in normal mode
  2. Switch to pbm
  3.Start typing neowin in url bar

**Actual result:** 
Monogram is shown instead of proper favicon

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.18(20.06.23.18)
- Verified test plan from issue description
- Verified visiting a site and switching to PBM only mode still shows the favicons
---------------
Verification passed on iPhone 7+ with iOS 13.5.1 running 1.18(20.06.23.18)
- Verified test plan from issue description
- Verified visiting a site and switching to PBM only mode still shows the favicons
---------------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.18(20.06.23.18)
- Verified test plan from issue description
- Verified visiting a site and switching to PBM only mode still shows the favicons
---------------
Verification passed on iPad Pro with iOS 13.6 running 1.18(20.06.23.18)
- Verified test plan from issue description
- Verified visiting a site and switching to PBM only mode still shows the favicons
---------------
Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.06.23.18)
- Verified test plan from issue description
- Verified visiting a site and switching to PBM only mode still shows the favicons
