### ISSUE TITLE
Bug iPadOS functionality for scribble not working correctly

### ISSUE THREAD

**Issue by ghost** [brave/brave-ios#2658]
iPad os 14 has a new scribble feature where on any text box if you draw say weather it will turn it into text however with brave if you scribble you can’t see what your drawing compared to other browsers 

Here is the video of the bug https://drive.google.com/file/d/1iQYCqjJAzWAPwijJ6LhcKPboEtpYdZAn/view?usp=drivesdk

You have to use a Apple Pencil to use the scribble feature

**Comment by ghost** [comment]
Made the video public

**Comment by iccub** [comment]
Thanks for your reports, we will try to support as much new iOS 14 features as possible until September release :)
