### ISSUE TITLE
Disable DCHECK_CALLED_ON_VALID_SEQUENCE in BraveRewards for iOS

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#2667]
## Description 
iOS uses GCD, DCHECK_CALLED_ON_VALID_SEQUENCE can be wrapped using:

`#if !defined(OS_IOS)`

**Comment by kylehickinson** [comment]
Closing as iOS will move to Chromium style threading for DB transactions in brave-core side and will eventually be picked up by a rewards bump
