### ISSUE TITLE
Possible method for setting Brave as default browser?

### ISSUE THREAD

**Issue by augmentedfourth** [brave/brave-ios#267]
### Description: 
Not a bug report; a feature request. This link seems to indicate a method of using an alternate browser as the default on iOS:
https://www.levvel.io/our-ideas/How-to-Change-your-Default-Browser-in-iOS

Basically, you disable Safari in Restrictions, and then any app that attempts to own the http:// and https:// URL schemes no longer has Safari in the way and can then become your default browser. Is this something that Brave could do?

**Comment by augmentedfourth** [comment]
I brought this up at https://community.brave.com/t/default-browser-on-ios/32358 , but the response was less technical than I would have liked. Hopefully this can be addressed here on GitHub.

**Comment by tmancey** [comment]
Agreed in iOS release and triage meeting that this is too risky until Apple provide official guidance

**Comment by vkedwardli** [comment]
For Power User only:

Just tested adding the `http` and `https` scheme into the ipa and resign, surprisingly iOS 12 indeed will prompt and ask for opening the URL in Brave, however there is no handling of `http` and `https` scheme inside the `NavigationPath(url: url)` function.

So it is a bit painful to rebuild from source code for chasing the latest update, instead of just downloading the latest ipa file and injecting the scheme into `info.plist`

**Comment by vkedwardli** [comment]
Just in case anyone (may be from Google?) who have the enough power to IPAPatch:

1. Download the ipa from release
2. Put the following code into the `+ (void)load` function
3. **PROFIT**


```objc
    [NSClassFromString(@"Client.AppDelegate") aspect_hookSelector:@selector(application:openURL:options:) withOptions:AspectPositionInstead usingBlock:^(id<AspectInfo> aspectInfo) {
        
        NSInvocation *invocation = aspectInfo.originalInvocation;
        
        __unsafe_unretained NSURL * originalURL = nil;
        [invocation getArgument:&originalURL atIndex:3];
        
        if( [originalURL.scheme.lowercaseString isEqualToString:@"http"] || [originalURL.scheme.lowercaseString isEqualToString:@"https"] ){
            
            NSURL* braveURL = [NSURL URLWithString:[@"brave://open-url?url=" stringByAppendingString:[[originalURL absoluteString] stringByAddingPercentEncodingWithAllowedCharacters:[NSCharacterSet URLQueryAllowedCharacterSet]]]];
            [invocation setArgument:&braveURL atIndex:3];
            [invocation retainArguments];
        }
        
        [invocation invoke];
        Boolean tempOriginal;
        [invocation getReturnValue:&tempOriginal];
        Boolean original = tempOriginal;
        [invocation setReturnValue:&original];
    } error:NULL];
```

[<img src="https://i.imgur.com/D93oMRO.gif">](https://i.imgur.com/D93oMRO.gif)
