### ISSUE TITLE
Brave crashes when open top-tiles via `Open in New Private Tab`

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#2671]
### Description: 
Brave crashes when open top-tiles via `Open in New Private Tab`

### Steps to Reproduce 
  1. Clean profile 1.18 (20.6.24.15)
  2. Skip the onboarding flow
  3. Long press on any one of the top tile and select the option `Open in New Private tab`
  4. Brave crashes

**Actual result:** 
Brave crashes

**Expected result:**

should not be any crash
**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
1.18 (20.6.24.15)

**Device details:** 

iPhone 8 - IOS 13.3.1
**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @bsclifton @anthonypkeane @brave/legacy_qa

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running  1.18(20.06.6.17)
- Verified no browser crash when opening a favourite in a new private tab
- Verified no browser crash when opening a favourite in a new private tab when URL bar is highlighted
---------
Verification passed on iPhone 7+ with iOS 13.5.1 running  1.18(20.06.6.17)
- Verified no browser crash when opening a favourite in a new private tab
- Verified no browser crash when opening a favourite in a new private tab when URL bar is highlighted
---------
Verification passed on iPad Pro with iOS 13.6 running  1.18(20.06.6.17)
- Verified no browser crash when opening a favourite in a new private tab
- Verified no browser crash when opening a favourite in a new private tab when URL bar is highlighted
---------
