### ISSUE TITLE
Favourites flash when long pressed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2678]
### Description: 
Favourites flash when long pressed

### Steps to Reproduce 
  1. Install 1.18 RC build
  2. Long press on favourites
  3. Favourites flicker before context menu opens

**Actual result:** 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17010094/86034916-5e838f00-ba33-11ea-8f93-77a5fc601645.gif)

**Expected result:**
No flicker

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.18(20.06.26.17)

**Device details:** 
iPad and iPhone running iOS 13.x 

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
Issue not reproduced on iOS 12

**Comment by kylehickinson** [comment]
Could not reproduce in any simulator build (13.5, with and without accessibility settings) or device build (14 beta 1). Don't believe I ever saw this on latest iOS 13 before I updated to 14 beta. Will need further investigation as to why this happens.

Edit: As seen in other video from Sri, the flashed color seems to be based on app theme. Flashing black when in dark mode, white while in light mode

**Comment by kylehickinson** [comment]
@srirambv Can you please re-test this in latest builds to see if it is still reproducible with theme changes that happened in 1.26? May be closable

**Comment by michalnowak061** [comment]
Issue not reproduced on iOS 14.5
