### ISSUE TITLE
Use `apple-touch-icon-precomposed` when avaiable instead of just `apple-touch-icon`

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2679]
### Description: 
Use `apple-touch-icon-precomposed` when avaiable instead of just `apple-touch-icon`

### Steps to Reproduce 
  1. Install 1.17 and edit a favourite and add `https://espn.com`
  2. Visit espn.in in a new tab and add it as a favourite
  3. Upgrade to 1.18
  4. One of the favourite is small with transparent background while the other is filled in 

**Actual result:** 
https://youtu.be/1EihjHs0wnM

**Expected result:**
Should always use favicons that fills the tiles

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.18(20.06.26.17)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by srirambv** [comment]
@kylehickinson comment on the issue
```
So there’s two problems at play here:
1. The page has both an apple-touch-icon and apple-touch-icon-precomposed, and we use the apple-touch-icon even if there’s a apple-touch-icon-precomposed thats better. Maybe we want to adjust this? Im not sure.
2. Since the icon that is pulled is quite small (57x57) it gets centered inside the icon rather than expanded. This is apparent now because we do not fill in backgrounds anymore (because that logic was flawed and would break visibility for single-color favicons)
```

**Comment by kylehickinson** [comment]
I tested this on 1.22 checking `espn.com` which only has 1 `apple-touch-icon` and multiple precomposed icons and it picks the correct precomposed icon already. This may no longer be an issue or was specific to 1.17/1.18 upgrades?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.23(21.2.12.5)
- Verified steps from issue description 
- ----------
Verification passed on iPhone XR with iOS 13.5 running 1.23(21.2.12.5)
- Verified steps from issue description 
- ----------
Verification passed on iPhone XR with iOS 13.5 running 1.23(21.2.12.5)
- Verified steps from issue description 
- ----------
- Logged follow up issue https://github.com/brave/brave-ios/issues/3304
