### ISSUE TITLE
Remove Firefox branding on Error Pages

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#268]
### Steps to Reproduce 
  1. See screenshot under Additional Information

**Actual result:** Firefox branding is shown

**Expected result:** Brave branding should be shown

**Reproduces how often:** Every time

**Brave Version:** Latest development build hash 6671f428bcdad3a22d361519161abfbe1ce39d8a

**Device details:** iPad Pro 10.5" iOS 11.4.1

### Additional Information 

![screen shot 2018-09-17 at 18 19 54](https://user-images.githubusercontent.com/1188719/45748183-e6522d80-bbff-11e8-9971-49b75f6974b4.png)

**Comment by kylehickinson** [comment]
In 1.6 we actually display a popup as such: 
![img_3727](https://user-images.githubusercontent.com/529104/45825877-3a711680-bcc1-11e8-9d1b-8d1d584446a6.png)

So question is whether or not we want to just keep this intermediate page and change the copy to say `Brave` instead of `Firefox` or remove it entirely for the alert.

**Comment by anthonypkeane** [comment]
@tomlowenthal can I get your input on this one.

My recommendation is that we implement the newer “Firefox” solution. Can you confirm you are okay with this?

**Comment by tildelowengrimm** [comment]
The newer Firefox behavior of displaying a modal popup is a lot worse from a security & UX perspective. We should stick with an interstitial which requires two taps to continue, but re-brand as Brave. Ideally, we should re-style this page (all error insterstitials) to match @rossmoody's updated error page designs for desktop, but that's not this issue.

**Comment by kylehickinson** [comment]
@tomlowenthal The two-tap interstitial is actually the newer Firefox behaviour that we have now in 1.7, where as the popup is the live version. 

But good to know we will first replace the copy on this page and ideally down the road implement the re-design :)
