### ISSUE TITLE
Remove Bookmark/Favourite to match Safari

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2680]
### Description: 
Remove Bookmark/Favourite to match Safari

### Steps to Reproduce 
  1. Open a new tab
  2. Long press on favourite to bring up context menu
  3. Shows Edit Bookmark/Remove Favourite

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/86201966-e2836700-bb58-11ea-9f71-d4a3573a3941.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/17010094/86201959-db5c5900-bb58-11ea-84f4-76d9ca6b08e6.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.18(20.06.26.17)

**Device details:** 
iPad and iPhone running iOS 12.x

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
cc: @LaurenWags

**Comment by srirambv** [comment]
cc: @jamesmudgett

**Comment by kylehickinson** [comment]
@srirambv this may not be worth the effort, as it's iOS 12 only

**Comment by srirambv** [comment]
sounds good to me. Can close it as wontfix.
