### ISSUE TITLE
"Show More" never appearing under NTP even after adding ~8 favourites

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2681]
### Description: 

Looks like `Show More` never appears even when you have more than six favourites saved on certain devices. Possibly similar to https://github.com/brave/brave-ios/issues/2645. However, this issue

### Steps to Reproduce

  1. install `1.18 (20.06.26.17)` and add a few websites to favourites
  2. open several NTP and you'll notice that `Show More` never appears

However, when you tap on the URL bar, you'll see the added favourites being listed.

**Actual result:** 

* Example of the issue occurring: https://youtu.be/gGbFbug7T2A

**Expected result:**

Believe `Show More` should appear when there's more than six favourites added.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible on this particular device.

**Brave Version:** 

Using `1.18 (20.06.26.17)`

**Device details:** 

* `iPad Mini 4` running `iOS 12.4.1`

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)?  `N/A`

### Additional Information

**Comment by kjozwiak** [comment]
Think we should at least look into this one and see if we can fix it for `1.18.x`. We're basically regressing `Show More` for some users. If it only affects `iPads` running `iOS 12`, we might be able to move this into the next HF. @srirambv @anthonypkeane @bsclifton thoughts on this one?

**Comment by iccub** [comment]
I'm fine with 1.18.1

**Comment by iccub** [comment]
Adding it back to 1.18, we decided to fix regression bugs found recently.

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.7.1.13)
- Verified test plan from issue description
- Verified `Show More` is shown the moment a new favourite is added in addition to the default ones
- Verified `Show More` is shown on both private and normal tab when there are 7 favourites
----------------------------------
Verification passed on iPad Pro with iOS 13.6 running 1.18(20.7.1.13)
- Verified test plan from issue description
- Verified `Show More` is shown the moment a new favourite is added in addition to the default ones
- Verified `Show More` is shown on both private and normal tab when there are 7 favourites
----------------------------------
- Logged follow up issue #2685
