### ISSUE TITLE
Implement cosmetic filtering

### ISSUE THREAD

**Issue by pes10k** [brave/brave-ios#2683]
Since cosmetic filtering doesn't have the same timing issues as request blocking, it wouldn't need to go through the iOS content blocking / declarative system.

Most (all?) of this information and functionality should already be available in the rust DAT and adblock-rust.  Also, likely a lot of the brave-core [brave_extension content script](https://github.com/brave/brave-core/blob/master/components/brave_extension/extension/brave_extension/content_cosmetic.ts) code could be reused

**Comment by kylehickinson** [comment]
Blocked by https://github.com/brave/brave-ios/issues/3683

**Comment by anthonypkeane** [comment]
For a spec, please search for "Cosmetic Filters and Scriptlet Injections" in GDrive

**Comment by Uni-verse** [comment]
Verified using version 1.37 (22.3.29.15)

Devices: 
iPhone 12 Pro | iOS 15.4
iPad (7th Gen) | iOS 15.2.1
iPhone X | iOS 14.4.2

- Verified that ads on youtube are blocked correctly.
- Verified that the non-video ads that show up below a video are blocked correctly.

iPhone ads blocked | iPhone in-content ad | iPad ads blocked | iPad in-content ad
-|-|-|-
![IMG_2568](https://user-images.githubusercontent.com/17885425/161167683-3d035721-7784-4caa-a16f-2a27bec26a68.PNG) | ![IMG_2567](https://user-images.githubusercontent.com/17885425/161167672-bed4446b-7a80-446e-934e-0109840c6a38.PNG) | ![IMG_0232](https://user-images.githubusercontent.com/17885425/161167746-fc3b09ce-a05d-4d7e-980a-ace8247821c3.PNG) | ![IMG_0233](https://user-images.githubusercontent.com/17885425/161167754-4a1d4c11-a616-4c03-becc-39ffdddf2929.PNG)

**Comment by iccub** [comment]
Let's reopen to verify together with https://github.com/brave/brave-ios/issues/5208

**Comment by Uni-verse** [comment]
Verified using RC #2 version `1.37 (22.4.5.19)`

Devices: 
- iPhone 12 running iOS 15.4
- iPhone X running iOS 14.4.2
- iPad running iOS 15.2.1

PASS - Verified that ads on youtube are blocked correctly.
PASS - Verified that the non-video ads that show up below a video are blocked correctly.

Shields Off | Shields On
-|-
![IMG_2580](https://user-images.githubusercontent.com/17885425/161851123-291271b5-1e8d-4b70-acfc-319064ec12f9.PNG) | ![IMG_2581 3](https://user-images.githubusercontent.com/17885425/161851134-d8914c0b-ed3f-4c3c-8797-f82f0e1db22f.PNG)

Shields Off (iPad) | Shields On (iPad)
-|-
![IMG_0243](https://user-images.githubusercontent.com/17885425/161854139-8408f0a6-47aa-410d-a735-0412957e533f.PNG) | ![IMG_0244](https://user-images.githubusercontent.com/17885425/161854151-e5b286df-aa7f-4890-999a-8ea41be9ecf1.PNG)
