### ISSUE TITLE
Tips button doesn't work on Twitter

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2689]
### Description: 
Tips button doesn't work on Twitter

### Steps to Reproduce 
  1. Visit a verified Twitter publisher
  2. Open rewards panel and click on Send Tip
  3. Tipping banner doesn't open

**Actual result:** 
Tips button doesn't work on Twitter

**Expected result:**
Should be able to tip a verified Twitter publisher

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.18(20.07.01.13)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
Happens on release as well
cc: @kylehickinson @NejcZdovc

**Comment by kylehickinson** [comment]
A small investigation on this:
- It seemed to work on [my own verified Twitter](https://mobile.twitter.com/kylehickinson) on 1.17 (Live/Prod) but not for Sri on Staging 1.18 and Live 1.17: <details><summary> Screenshot: </summary>
![Image from iOS](https://user-images.githubusercontent.com/529104/86371182-97e41680-bc4e-11ea-9410-f930d31d5a31.jpg)
</details >

- We do not show the tipping banner if there is no `publisher` for the given website. This means if ledger method `GetPublisherActivityFromUrl` does not callback with a publisher object the tip button won't do anything.
- Our wrapper method that calls `GetPublisherActivityFromUrl` can fail if the URL we pass is invalid or has no base domain, but for mobile.twitter.com I don't think this would happen

**Comment by kylehickinson** [comment]
Closing since tipping isn't available in Brave iOS anymore
