### ISSUE TITLE
Fix Brave Ads state-level targeting crash

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#2692]
### Description: 
Fix Brave Ads state-level targeting crash

### Steps to Reproduce 
  1. Disable state-level targeting in Ads settings (US Only)

**Actual result:** 
App crashes

**Expected result:**
App should not crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.20.x

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.21(20.10.08.09)

- Verified disabling state-level target doesn't cause crash 

iPhone XR (iOS 13.5) | iPhone 7+ (iOS 14.0.1) | iPad Pro (iOS 12.4.1)
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/95460958-8907b100-096d-11eb-888b-af5aaa49e279.png) | ![image](https://user-images.githubusercontent.com/17010094/95460970-8efd9200-096d-11eb-9841-aeadc09b5ecd.png) | ![image](https://user-images.githubusercontent.com/17010094/95461414-1c40e680-096e-11eb-8816-9f622de9dad2.png)
