### ISSUE TITLE
Fixes state-level targeting crash after upgrade on iOS

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#2694]
https://github.com/brave/brave-browser/issues/10555

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.0.1 running 1.21(20.10.09.13)
- Verified upgrading from 1.19 to 1.21 doesn't cause crash when selecting view details 
-----
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.09.13)
- Verified upgrading from 1.19 to 1.21 doesn't cause crash when selecting view details 
-----
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.10.09.13)
- Verified upgrading from 1.19 to 1.21 doesn't cause crash when selecting view details
