### ISSUE TITLE
Favicon transparency check crash

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2697]
### Description: 

<img width="599" alt="Zrzut ekranu 2020-07-6 o 12 29 21" src="https://user-images.githubusercontent.com/6950387/86584123-bb77cb80-bf84-11ea-8861-f734eeb8b189.png">

### Steps to Reproduce 
Hard to repro, intermittent crash.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 
1.18

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `1.18.1 (20.07.06.15)` using a `iPad Mini 4` running `iOS 12.4.1`. As per https://github.com/brave/brave-ios/pull/2701#issue-444829062, went through the following cases:

* installed `1.18.1 (20.07.06.15)`
* Clicked on `Add Bookmark` on ~50 websites and ensured Brave didn't crash
  * checked the top ~20 websites from https://batgrowth.com/publishers/website
  * checked the websites that come pre-loaded under the New Tab Page
  * loaded several other popular websites
* ensured bookmarks are generally working via https://github.com/brave/brave-ios/issues/2703#issue-651698235

----------------

Verification passed on iPhone XR with iOS 13.5 running 1.18(20.07.06.15)
- Verified no crash when Add bookmark sheet is loaded
- Verified websites load favicons correctly on pages
- Verified default favourites favicon is loaded correctly
- Verified favicons are shown correctly on tab tray
- Verified adding bookmarks on both normal and private tabs and there was no crash
