### ISSUE TITLE
Improve cosmetic adblock on YT 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2698]
### Description: 
Improve cosmetic adblock on YT 

### Steps to Reproduce 
  1. Upgrade to 1.18.1 from 1.18
  2. Open a new tab and visit YT and search for a term
  3. Open a video from search result, video **may** show an overlay ad (cosmetic) which should have been blocked

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/86583846-d560e080-bf7b-11ea-987e-0f44a0295b33.png)

**Expected result:**
No ads what so ever

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent (not always)

**Brave Version:** 
1.18.1(20.07.03.15)

**Device details:** 
iPad Pro with iOS 13.6

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
Found while testing #511
cc: @antonok-edm @ryanbr

**Comment by iccub** [comment]
Related ticket https://github.com/brave/brave-ios/issues/2683

**Comment by ryanbr** [comment]
Probably safe to close @srirambv  

> Related ticket #2683

**Comment by srirambv** [comment]
yup closing it as dupe of #2683
