### ISSUE TITLE
Feature request: Add Brave to iOS "open with..."

### ISSUE THREAD

**Issue by eturk1** [brave/brave-ios#2714]
On iPad OS 3.6 beta, I now see an "open with" menu when opening links in certain apps. I think default browser may also become available in 4.0.

Brave isn't in the list. Doesn't seem to be registered as a browser?

![A3A972DC-808D-46B3-8ED1-68BE6AACECA8](https://user-images.githubusercontent.com/525280/87229590-0cf5d100-c35e-11ea-92ef-314fb80c74e9.jpeg)

**Comment by kylehickinson** [comment]
This UI is actually a custom picker by Google so we can't add ourselves to it unfortunately. However starting in iOS 14 you can add Brave as your default browser and tapping "Safari" will end up opening Brave so I will close this issue 🙂
