### ISSUE TITLE
Temporary disable the Sync UI until Sync V2

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2718]
### Description: 
Temporary disable the Sync UI until Sync V2

@jsecretan can you confirm? WDYT?

**Comment by jsecretan** [comment]
Yes, please do, thanks for bringing this up @anthonypkeane.   We should also get up our warning infobar ASAP.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.19.1(20.07.30.16)

**No sync user**

- Verified upgrading from 1.19 to 1.19.1 without sync chain there is no alert message is shown
- Verified upon upgrade sync option is hidden in settings 

 Before | After
-- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/89036117-01ca0b80-d334-11ea-9bdd-3dec79c0517d.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/89036100-fe368480-d333-11ea-8a69-8fb34712829c.png> 

**Sync user**

- Verified alert message is shown when upgrading from 1.19 with a sync chain
    <img width=250 src=https://user-images.githubusercontent.com/17010094/89036264-42c22000-d334-11ea-8c98-7a2ec286a6a7.png>

- Verified no bookmarks are sync'd after upgrading to 1.19
- Verified adding or removing bookmarks from iOS device doesn't affect/add/remove bookmarks on the sync chain it was part of

-----------

Verification passed on iPhone 7+ with iOS 13.6 running 1.19.1(20.07.30.16)

**No sync user**

- Verified upgrading from 1.19 to 1.19.1 without sync chain there is no alert message is shown
- Verified upon upgrade sync option is hidden in settings 

 Before | After
-- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/89037665-ddbbf980-d336-11ea-975c-0cb3934be0c6.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/89037705-ef9d9c80-d336-11ea-896a-98e0c818972e.png> 

**Sync user**

- Verified alert message is shown when upgrading from 1.19 with a sync chain
    <img width=250 src=https://user-images.githubusercontent.com/17010094/89037695-ea405200-d336-11ea-8e4e-21c420be00fa.png>

- Verified no bookmarks are sync'd after upgrading to 1.19
- Verified adding or removing bookmarks from iOS device doesn't affect/add/remove bookmarks on the sync chain it was part of

-----------

Verification passed on iPad Pro with iOS 12.4.1 running 1.19.1(20.07.30.16)

**No sync user**

- Verified upgrading from 1.19 to 1.19.1 without sync chain there is no alert message is shown
- Verified upon upgrade sync option is hidden in settings 

 Before | After
-- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/89038647-a6e6e300-d338-11ea-921e-0f1607aaff7d.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/89038666-b108e180-d338-11ea-899c-8bfcd5eb7ff8.png> 

**Sync user**

- Verified alert message is shown when upgrading from 1.19 with a sync chain
    <img width=250 src=https://user-images.githubusercontent.com/17010094/89038659-abab9700-d338-11ea-85cf-c6e3a18ab96b.png>

- Verified no bookmarks are sync'd after upgrading to 1.19
- Verified adding or removing bookmarks from iOS device doesn't affect/add/remove bookmarks on the sync chain it was part of
-----------

Verification passed on iPad Pro with iOS 13.6.1 running 1.19.1(20.07.30.16)

**No sync user**

- Verified upgrading from 1.19 to 1.19.1 without sync chain there is no alert message is shown
- Verified upon upgrade sync option is hidden in settings 

 Before | After
-- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/89039217-92efb100-d339-11ea-9c6e-4f5943778996.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/89039200-8b300c80-d339-11ea-91ba-d865aeb46dd3.png> 

**Sync user**

- Verified alert message is shown when upgrading from 1.19 with a sync chain
    <img width=250 src=https://user-images.githubusercontent.com/17010094/89039206-8e2afd00-d339-11ea-9ec5-2681bebfd664.png>

- Verified no bookmarks are sync'd after upgrading to 1.19
- Verified adding or removing bookmarks from iOS device doesn't affect/add/remove bookmarks on the sync chain it was part of
