### ISSUE TITLE
blocking navigation to page

### ISSUE THREAD

**Issue by jcesarmobile** [brave/brave-ios#2726]
### Description: 
Directly navigating to https://capacitorjs.com/docs/apis/push-notifications, but links that navigate to it don't work, the url changes but the content don't load.
The page doesn't have ads or anything different from the rest of the site, I think it's just because of the url containing push-notifications

### Steps to Reproduce 
 1. Open https://capacitorjs.com/docs/apis/permissions
 2. Click next
 3. Should load https://capacitorjs.com/docs/apis/push-notifications but it's blocked

**Actual result:** 
url changes to https://capacitorjs.com/docs/apis/push-notifications but has the permissions content

**Expected result:**
load the actual https://capacitorjs.com/docs/apis/push-notifications content

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
always

**Brave Version:** 
1.18.1

**Device details:** 
iPhone X with iOS 13

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? yes

### Additional Information

We have had a few reports of problems loading the notifications page
https://github.com/ionic-team/capacitor-site/issues/78
https://github.com/ionic-team/capacitor/issues/1866
https://github.com/ionic-team/capacitor/issues/2790
https://github.com/ionic-team/capacitor/issues/2925

Also happens on Brave desktop https://github.com/brave/brave-browser/issues/10792

**Comment by LaurenWags** [comment]
Reproduces on the following versions for me both using iPad mini with iOS13:
1.20 (20.09.02.14) - Dev
1.19.2 (20.08.05.18) - Production App Store version

Note - a page refresh fixes this.

Also, no longer reproduces on desktop per https://github.com/brave/brave-browser/issues/10792#issuecomment-685919289

cc @anthonypkeane @srirambv @rebron

**Comment by iccub** [comment]
seems to work now

**Comment by jcesarmobile** [comment]
yeah, it's working, thanks!
