### ISSUE TITLE
Script pulled through invalid SSL on SSL page leaving browser vulnerable to man-in-the-middle-attacks

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#273]
### Steps to Reproduce 
  1. Navigate to one of the URLs in the Additional Information section

**Actual result:** Test fails

**Expected result:** Test should pass

**Reproduces how often:** Every time

**Brave Version:** Latest development build hash cefaeabbdc27db75dfdabe450c7861c0f892b8be

**Device details:** iPad Pro 10.5" iOS 12

### Additional Information 

Test scripts which pass on 1.6:

https://ios.browsr-tests.com/alt/ssl_http_script.php
https://ios.browsr-tests.com/alt/ssl_delayed_script.php

**Comment by diracdeltas** [comment]
is this also present in the old iOS repo?

**Comment by tmancey** [comment]
This issue is not present in the old iOS repo

**Comment by danishjafri88** [comment]
@tmancey The bug is non reproducible on latest version. Also could not reproduce it on the mentioned  head [cefaeab](https://github.com/brave/brave-ios/commit/cefaeabbdc27db75dfdabe450c7861c0f892b8be). Can you please verify this.

**Comment by jhreis** [comment]
Unable to reproduce, closing.
