### ISSUE TITLE
Fix youtube ads (white-page pre-rolls) in IOS

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-ios#2730]
### Description: 
Youtube ads are still being shown on IOS. reported by @cacevedo222 

**Actual result:** 
![image_from_ios](https://user-images.githubusercontent.com/1659004/88115868-4f939500-cc0b-11ea-8901-405fa3b23e96.jpg)

### Additional Information

From implementing json-prune.js in: https://github.com/brave/brave-ios/pull/2655 we should also implement set.js for ios to prevent these white-screen pre-roll ads.

I implemented the following js snippet in brave-unbreak to prevent these ads in https://github.com/brave/adblock-lists/pull/420 Which seems to help prevent these ads from showing up.

`youtube.com##+js(set, ytInitialPlayerResponse.adPlacements, undefined)`
`youtube.com##+js(set, adPlacements, undefined)`

`set.js source:` https://github.com/brave/uBlock/blob/525d10a489ba832e212f54d11994ffef12fadfe4/assets/resources/scriptlets.js#L589

@Brandon-T

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.0.1 running 1.21(20.10.06.20)
- Verified no pre-roll ads shown when loading YT videos
- Verified on both normal and private tabs 
------------------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.06.20)
- Verified no pre-roll ads shown when loading YT videos
- Verified on both normal and private tabs 
------------------
Verification passed on iPad Pro with iOS 14.0.1 running 1.21(20.10.06.20)
- Verified no pre-roll ads shown when loading YT videos
- Verified on both normal and private tabs 
------------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.10.06.20)
- Verified no pre-roll ads shown when loading YT videos
- Verified on both normal and private tabs
