### ISSUE TITLE
Clear all feature for multiple tabs

### ISSUE THREAD

**Issue by kalebtesfay** [brave/brave-ios#2731]
## Problem Description 
If you have a lot of tabs open it can be annoying to remove all of them one by one. 

## Feature Overview 
Since swiping left and right are already used to clear tabs. Swiping up or down should clear all tabs together.

## Screenshot 

![image](https://user-images.githubusercontent.com/29930657/88157125-5b199880-cbd8-11ea-8fee-0fb6989df566.png)

##User Experience 

   1. User clicks on the tabs manager.
   2. User adds multiple tabs.
   3. User swipes up or down to clear all of them.

**Comment by iccub** [comment]
You can long press on tabs button on bottom toolbar and choose `close all tabs`
