### ISSUE TITLE
Tab Tray gets incorrect theme in iOS 13 when switching OS dark mode on/off

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2733]
If you are using automatic theme mode and change iOS 13 OS-level dark mode while in the tab tray the theme will not update correctly. 

Also after visiting the tab tray, the main app window background color changes thus making the overlay-style modals look weird

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.06.20)
- Verified test plan from #2734
