### ISSUE TITLE
Adblock stopped working today with no diagnostics to my knowledge

### ISSUE THREAD

**Issue by chuggafan** [brave/brave-ios#2735]
### Description: 
As of today, my adblock has stopped working entirely for some currently unknown reason, I have rebooted my IPad and reset my cache in-browser in brave to no avail, if anything helps, FireFox focus + attempting to integrate *that* with safari also did not work to adblock. 

### Steps to Reproduce 
  1. Have brave downloaded
  2. Go to website known to have ads
  3. See ads despite not having the brave rewards program enabled

**Actual result:** 
![image](https://user-images.githubusercontent.com/15003854/88248985-0f66fd80-cc71-11ea-92b1-7916a716b1d4.png)

**Expected result:** No ads, even for the United States Navy.

**Reproduces how often:** Every time, even after full cache clear, an IPad reboot, *AND* an IPad update, I don't know how much more I can do for "reproducible" tests. This happens on every website that has ads on it that I go on, no joke.

**Brave Version:**  v1.18.1(20.07.06.15)

**Device details:** IPad Air 2, both 13.5.1 and 13.6 do this

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

I turned on script blocking for a site and that didn't help, and as mentioned previously, safari/firefox focus both also have this problem (I hooked in FF Focus into Safari)
### Additional Information
I definitely have the room for the blocklists as I had more than 1gb in free space, so that is definitely not the issue, I don't know why it's happening but I've had this problem for *all* day.

**Comment by iccub** [comment]
Should be fixed now, please remove your app from memory and relaunch, it should redownload updated blocklists

**Comment by chuggafan** [comment]
Yep, it was fixed, I was actually about to close the issue when you did this, thanks.

**Comment by iccub** [comment]
Thanks for checking @chuggafan :) fortunately it was a server issue no hotfix release needed
