### ISSUE TITLE
Brave suddenly failing to block ads and trackers

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ios#2736]
### Description: 
Numerous users [[1](https://twitter.com/jborg_arts/status/1285994145631186944), [2](https://twitter.com/Politologue_com/status/1286013284265734144)] recently noted that Brave abruptly stopped blocking ads and trackers on iOS.

This issue appears to have started on/around July 21-22, 2020.

### Steps to Reproduce 
1. Navigate to foxnews.com
2. Check number of items blocked

**Actual result:** 
Brave reports very few, if any, ads and trackers blocked.

**Expected result:**
Brave should detect and block 20+ ads and trackers.

**Reproduces how often:**
Easily, always.

**Brave Version:**
1.18.1, 1.19.x, and 1.20.x

**Device details:** 
iPad

### Additional Information
- I was not immediately able to reproduce the issue when I used my iPad for the first time today, but after several minutes and a couple restarts of the app, I began to consistently reproduce the issue.
  - I removed Brave from my iPad, downloaded 1.18.1 fresh, and immediately reproduced the issue off of first-run.
- This issue appears to reproduce in multiple versions of Brave, as well as on multiple, recent versions of iOS.
- There didn't appear to be anything wrong with https://adblock-data.s3.brave.com/ios/latest.json or https://adblock-data.s3.brave.com/ios/latest.dat. These files were/are downloaded as expected, and do not appear to be malformed in any way.
- Lengthy thread on Slack: https://bravesoftware.slack.com/archives/C3GNZANPR/p1595445865288300

**Comment by jonathansampson** [comment]
Same issue as #2730 and #2735, I suspect.

**Comment by iccub** [comment]
I’m pretty sure I found the problem:
First of all the lists from the internet leak ads, fixing then would fix the problem immediately, for this we have to update both json and dat files to trigger the download for users.
Our bundled lists block ads properly.
Why this started happening now, days after 1.18.1:
When you first download blocklist from the internet we compile both bundled and internet lists.
However when you update blocklists second time, bundled lists do not get compiled, then we only use the one from the internet.
This is really not a bug, but we could still keep compiling the bundled lists no matter what we get from the internet, something to decide on.
The purpose of bundled lists was to have a small quick to compile list that block most common ads,
that list currently has 5000rules
lists from the internet were supposed to be larger and blocking much more ads
and now the 0445.. list has only 2000 rules, something is wrong her

Updating server lists to have more rules should solve this

**Comment by bsclifton** [comment]
OK problem SHOULD be resolved now 👍 Creating a post-mortem internally to find a root cause / come up with plan to prevent from happening again, etc
