### ISSUE TITLE
[Feature Request] Add an option to search selected text with brave

### ISSUE THREAD

**Issue by tankmohit** [brave/brave-ios#2738]
## Problem Description 
When selecting a text in any article there is no option to search it on google or any search engine without leaving brave, and have to use lookup function built inside iOS, which by default opens safari. 

This feature is built directly inside Firefox iOS. please refer to the option **"Search with firefox"** in screenshots below

|Firefox | Brave|
|---|---|
|![357861E4-5930-4D52-A5C2-660B7BDCBFE1](https://user-images.githubusercontent.com/27958239/88568725-68cf8380-d007-11ea-8ef6-196bfd7ed193.png)|![BF0684F2-A826-483B-AAC1-D3B8C048EA8B](https://user-images.githubusercontent.com/27958239/88568737-6e2cce00-d007-11ea-8e52-c85ce4e165c2.png)|

**Comment by hennrynusasatria** [comment]
Hi @tankmohit / All

I believe that this feature can be solved on iOS 14 / iPadOS 14, with the capability of Brave iOS to become the default browser ( #2785 ), thus by clicking "Look Up", then it will redirect to Brave iOS.

I think that the "Search with Firefox" is not standard implementation.

Thank you.

**Comment by tankmohit** [comment]
But this would add few extra steps to accomplish a thing. While on firefox it can be done with single tap.

**Comment by Uni-verse** [comment]
Verified completed using beta app version `1.37 (22.3.11.18)`

Devices used:

```
iPhone 12 Pro | iOS 15.1.1
iPhone X | iOS 14.4.2
iPad (7th Gen) | iOS 15.2.1
```

Acceptance Criteria:

UI:

- [x] 'Search with Brave' displayed
- [x] Option displayed to the right of 'Find in Page' option
- [ ] Displayed in recent searches - https://github.com/brave/brave-ios/issues/5118

Functionality: 
 
- [x] Searches in New Tab
- [x] Searches in New Tab in PB/Private Tab
- [x] Displayed when user selects text in text field
- [x] Displayed when user selects text on page
- [x] Displayed when user selects text in reader mode
- [x] Searches based on search engine selected in settings
- [x] Search query matches search from url bar `https://search.brave.com/search?q={search term}&source=ios`

iPhone | iPad 
-|-
![IMG_2521](https://user-images.githubusercontent.com/17885425/158481851-18cf603f-3901-46b4-9ee6-c206d905e363.PNG) | ![IMG_0193](https://user-images.githubusercontent.com/17885425/158481862-70a79d8b-1a6d-4ce4-a200-9c98a08eab88.PNG)

**Comment by Uni-verse** [comment]
@iccub I noticed that the searches from the context menu are not logged under recent searches. Is this the expected behavior for this feature?

cc: @cuba

**Comment by iccub** [comment]
I think this is worth having a followup ticket @Uni-verse
