### ISSUE TITLE
Replace monthly ($9.99) with local currency value in the VPN plan details modal

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2744]
Originally created by @srirambv via https://github.com/brave/brave-ios-private/issues/18

### Description: 
We have a hard-coded value of $9.99 and $99.9 on the VPN plan details modal which doesn't add up to the actual cost mentioned for the monthly subscription. If anything is not in the local currency then it will be converted to local currency to see if it adds up, which more often than not is always more than the actual. For example the current market rates for 1USD->75.xx INR and the monthly subscription is 849 INR so going by market value 9.99 USD -> 750.xx. So there is a difference of almost 100 INR there and doing the same for a yearly subscription it would be a significantly higher amount. 

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/87747666-def40f00-c7eb-11ea-84fe-02177a2bead1.png)

**Expected result:**
All prices on any screen should be the face value of the local currency and no in USD. 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
All 1.19 builds

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @anthonypkeane @janypiotrowski @iccub

**Comment by anthonypkeane** [comment]
closing as replacing with https://github.com/brave/brave-ios/issues/2747
