### ISSUE TITLE
"Buy" modal doesn't appear on iOS 12 after restarting Brave three times

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2745]
Originally created by @kjozwiak via https://github.com/brave/brave-ios-private/issues/13.

### Description: 

The `Buy` modal isn't being displayed when restarted Brave three times and there was no previous interaction with any of the VPN UI elements. Basically failing the `Buy vpn popup` case under the following:

* https://docs.google.com/document/d/1mvTy2HHjdH22bcWW8gY1lk_UR3OQGwDM6QHZoawgMnI/

### Steps to Reproduce 

  1. download/install `1.19 (20.07.15.13)`
  2. restart Brave three times (make sure you don't interact with the VPN UI)

**Actual result:** 

The following `Buy` modal isn't appearing after restarting Brave three times:

<p align="center">
<img src="https://user-images.githubusercontent.com/2602313/87640244-70904d80-c714-11ea-820b-16d5d2589256.PNG" width=300>
</p>

**Expected result:**

As per the spec/STR, the `Buy" modal should appear after restarting three times if there was no interaction with any of the VPN UI elements.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the following STR.

**Brave Version:** 

* Using `1.19 (20.07.15.13)` from TF

**Device details:** 

* `iPhone 6s+` running `iOS 12.4.1` using `1.19 (20.07.15.13)` - **Reproduced**
* `iPad Mini 4` running `iOS 12.4.1` using `1.19 (20.07.15.13)` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @anthonypkeane @srirambv @iccub

**Comment by kjozwiak** [comment]
Please make sure to take a look at https://github.com/brave/brave-ios-private/issues/13 which includes some context/info via several comments.

**Comment by NejcZdovc** [comment]
+1 from me

**Comment by kylehickinson** [comment]
iOS 12 no longer supported
