### ISSUE TITLE
"VPN is now enabled" modal missing lock icon sometimes

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2746]
Originally created by @kjozwiak via https://github.com/brave/brave-ios-private/issues/6.

### Description: 

Sometimes the `VPN is now enabled` modal is completely blank. It's pretty rare and I've only seen it happen twice so far. However, I don't really have any STR so this might be hard to diagnose/fix.

### Steps to Reproduce 

1. run through the entire VPN process and have it installed/VPN profile created
2. go through the needed authentication to add the Brave Firewall + VPN profile in the iOS settings.

**Actual result:** 

![645B95AC-CA75-460B-8132-B3BE7B42031D](https://user-images.githubusercontent.com/2602313/87504600-f50b9f00-c634-11ea-8e63-857eb8ed4b04.PNG)

**Expected result:**

![23497EF8-7586-418F-90E5-4885AAAC24BD](https://user-images.githubusercontent.com/2602313/87502719-541ae500-c630-11ea-8878-1c6967cd9101.PNG)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

I'm not 100% sure but doesn't happen often. I've only seen this happen twice.

**Brave Version:** 

* Using `1.19 (20.07.14.16)`

**Device details:** 

* `iPhone 11` running `iOS 13.5.1` - **Reproduced**
* `iPad Air 3rd Gen` running `iOS 13.5.1` - **Reproduced**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @bsclifton @aekeus @iccub @srirambv

**Comment by kjozwiak** [comment]
Please make sure to take a look at https://github.com/brave/brave-ios-private/issues/6 which includes some context/info via several comments.

**Comment by iccub** [comment]
Let's close for now and reopen if we still encounter it, i installed vpn many times recently and always saw the lock
