### ISSUE TITLE
IAP VPN Subscription Text

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2747]
### Description: 
Linked to: https://github.com/brave/brave-ios/issues/2744

Please update the text IAP text to

`````````````
Subscriptions will be charged via your iTunes account.

Any unused portion of the free trial, if offered, is forfeited when you buy a subscription. 

Your subscription will renew automatically unless it is cancelled at least at least 24 hours before the end of the current period. 

You can manage your subscriptions in Settings. 

By using Brave, you agree to the Terms of Use and Privacy Policy

`````````````

![image](https://user-images.githubusercontent.com/17010094/87747666-def40f00-c7eb-11ea-84fe-02177a2bead1.png)

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14 running 1.20(20.08.31.09)
- Verified text is updated as per issue description
   <img width=300 src=https://user-images.githubusercontent.com/17010094/91838983-40f6bf80-ec46-11ea-934e-27356dbca47f.png>

--------------
Verification passed on iPhone 7+ with iOS 13.6 running 1.20(20.08.31.09)
- Verified text is updated as per issue description
   <img width=300 src=https://user-images.githubusercontent.com/17010094/91839028-4c49eb00-ec46-11ea-9267-9cc7015f9e4a.png>

-------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.20(20.08.31.09)
- Verified text is updated as per issue description
   <img width=600 src=https://user-images.githubusercontent.com/17010094/91839330-c4181580-ec46-11ea-8c72-7e4ac58b8776.png>
