### ISSUE TITLE
Search updates

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2754]
Update search engines

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.19.1(20.07.30.16)
<details>
<Summary>Existing Users</Summary>
<ul>
	<li>Verified existing search engine is retained post upgrade and performing a search uses the SE set in previous version</li>
	<li>Verified Yahoo is listed as a search engine button post upgrade</li>
	<li>Verified Yahoo shows up as a quick search engine post upgrade</li>
</ul>
</details>

<details>
<summary>New users with Yahoo supported regions</Summary>
<table>
	<tr>
		<td>
			<details>
				<summary>Verified Yahoo shows up as a search engine in onboarding and is the first in the list</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89028694-caa02e00-d324-11ea-8065-eb8d8d2d562f.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89028668-bf4d0280-d324-11ea-8664-de82f856e676.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<details>
				<summary>Verified selecting a different SE/skipping onboarding, Yahoo is shown as the first SE in the quick SE list</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89029065-7a759b80-d325-11ea-8a49-fd1395cfc8c5.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89029067-7c3f5f00-d325-11ea-9a2a-e6eb5243e9ad.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<li>Verified performing a quick search on Yahoo points to `search.yahoo.com`</li>
		</td>
	</tr>
</table>
</details>

<details>
<summary>New users with Yahoo supported region, with regional SE support</summary>

<table>
	<tr>
		<td>
			<details>
				<summary>Verified Yahoo shows up as a search engine in onboarding and is the first in the list with DDG as second</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89031394-54062f00-d32a-11ea-8950-9756f77db24a.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89031383-4ea8e480-d32a-11ea-907d-8f3154415163.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<details>
				<summary>Verified selecting DDG as default during onboarding, Yahoo is shown as the first SE in the quick SE list</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89031434-6b451c80-d32a-11ea-81f4-2ad0b4fb8a9c.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89031442-6e400d00-d32a-11ea-8cc7-53dd418149ae.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<details>
				<summary>Verified, for France, selecting Qwant as default during onboarding, Yahoo is shown as the first SE in the quick SE list</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89031342-3769f700-d32a-11ea-8f65-89abc7052cd6.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89031352-3afd7e00-d32a-11ea-9b61-9bb852a6e679.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			Verified performing a quick search on Yahoo points to
            <ul>
            	<li>`au.yahoo.con` for Australia</li>
            	<li>`ie.yahoo.com` for Ireland</li>
            	<li>`de.yahoo.com` for Germany</li>
            	<li>`fr.yahoo.com` for France</li>
            	<li>`nz.yahoo.com` for New Zealand</li>
            </ul>
		</td>
	</tr>
</table>
</details>


<details>
	<summary>New users on unsupported region</summary>
	
<table>
	<tr>
		<td>
			<details>
				<summary>Verified for unsupported regions, Yahoo isn't on the top of the list during onboarding</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89034477-ef020780-d330-11ea-9ebb-adeafde5454e.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89034470-ec071700-d330-11ea-88ad-7f96c2014fc4.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<li>Verified performing a search on Yahoo uses `search.yahoo.com`</li>
		</td>
	</tr>
</table>
</details>

<details>
	<summary>New users for Malaysia</summary>
		<li>Verified Yahoo is first on the list during onboarding</li>
		<li>Verified performing a search on Yahoo uses `malaysia.yahoo.com`</li>
</details>

-----------------------

Verification passed on iPhone 7+ with iOS 13.5 running 1.19.1(20.07.30.16)
<details>
<Summary>Existing Users</Summary>
<ul>
	<li>Verified existing search engine is retained post upgrade and performing a search uses the SE set in previous version</li>
	<li>Verified Yahoo is listed as a search engine button post upgrade</li>
	<li>Verified Yahoo shows up as a quick search engine post upgrade</li>
</ul>
</details>

<details>
<summary>New users with Yahoo supported regions</Summary>
<table>
	<tr>
		<td>
			<details>
				<summary>Verified Yahoo shows up as a search engine in onboarding and is the first in the list</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89040720-1f9b6e80-d33c-11ea-9012-39095f5e3ff3.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89040701-17433380-d33c-11ea-914d-bac412de0b05.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<details>
				<summary>Verified selecting a different SE/skipping onboarding, Yahoo is shown as the first SE in the quick SE list</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89040788-3641c580-d33c-11ea-8951-79ec90f11bdd.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89040802-39d54c80-d33c-11ea-92ae-8cb05c817fad.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<li>Verified performing a quick search on Yahoo points to `search.yahoo.com`</li>
		</td>
	</tr>
</table>
</details>

<details>
<summary>New users with Yahoo supported region, with regional SE support</summary>

<table>
	<tr>
		<td>
			<details>
				<summary>Verified Yahoo shows up as a search engine in onboarding and is the first in the list with DDG as second</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89040842-49549580-d33c-11ea-8032-f347c159f1a4.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89040850-4ce81c80-d33c-11ea-83ec-84c187b98b3e.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<details>
				<summary>Verified selecting DDG as default during onboarding, Yahoo is shown as the first SE in the quick SE list</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89040875-56718480-d33c-11ea-8b5b-c7a6f43074ec.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89040883-596c7500-d33c-11ea-89c6-f757c3dffbb3.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<details>
				<summary>Verified, for France, selecting Qwant as default during onboarding, Yahoo is shown as the first SE in the quick SE list</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89040912-68532780-d33c-11ea-9588-1257b9b13c9b.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89040908-65f0cd80-d33c-11ea-9c5d-b83bcb9754b7.png></td>
					</tr>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89041558-7f464980-d33d-11ea-880f-5c80b33a911e.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89041573-83726700-d33d-11ea-94de-f1166151e4f1.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			Verified performing a quick search on Yahoo points to
            <ul>
            	<li>`au.search.yahoo.con` for Australia</li>
            	<li>`ie.search.yahoo.com` for Ireland</li>
            	<li>`de.search.yahoo.com` for Germany</li>
            	<li>`fr.search.yahoo.com` for France</li>
            	<li>`nz.search.yahoo.com` for New Zealand</li>
            </ul>
		</td>
	</tr>
</table>
</details>


<details>
	<summary>New users on unsupported region</summary>
	
<table>
	<tr>
		<td>
			<details>
				<summary>Verified for unsupported regions, Yahoo isn't on the top of the list during onboarding</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89040952-7608ad00-d33c-11ea-9966-0476fb85118e.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89040959-786b0700-d33c-11ea-8121-879cec499841.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<li>Verified performing a search on Yahoo uses `search.yahoo.com`</li>
		</td>
	</tr>
</table>
</details>

<details>
	<summary>New users for Malaysia</summary>
		<li>Verified Yahoo is first on the list during onboarding</li>
		<li>Verified performing a search on Yahoo uses `malaysia.yahoo.com`</li>
</details>

-----------------------

Verification passed on iPad Pro with iOS 12.4.1 running 1.19.1(20.07.30.16)
<details>
<Summary>Existing Users</Summary>
<ul>
	<li>Verified existing search engine is retained post upgrade and performing a search uses the SE set in previous version</li>
	<li>Verified Yahoo is listed as a search engine button post upgrade</li>
	<li>Verified Yahoo shows up as a quick search engine post upgrade</li>
</ul>
</details>

<details>
<summary>New users with Yahoo supported regions</Summary>
<table>
	<tr>
		<td>
			<details>
				<summary>Verified Yahoo shows up as a search engine in onboarding and is the first in the list</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89051601-6e510480-d34c-11ea-9d67-3757e6073094.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<details>
				<summary>Verified selecting a different SE/skipping onboarding, Yahoo is shown as the first SE in the quick SE list</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89051660-7f9a1100-d34c-11ea-96ec-335d0017e9d1.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<li>Verified performing a quick search on Yahoo points to `search.yahoo.com`</li>
		</td>
	</tr>
</table>
</details>

<details>
<summary>New users with Yahoo supported region, with regional SE support</summary>

<table>
	<tr>
		<td>
			<details>
				<summary>Verified Yahoo shows up as a search engine in onboarding and is the first in the list with DDG as second</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89051949-e4ee0200-d34c-11ea-9901-85e9bd97ed81.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<details>
				<summary>Verified selecting DDG as default during onboarding, Yahoo is shown as the first SE in the quick SE list</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89052003-f800d200-d34c-11ea-9c2b-4572daf630d2.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<details>
				<summary>Verified, for France, selecting Qwant as default during onboarding, Yahoo is shown as the first SE in the quick SE list</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89052255-5a59d280-d34d-11ea-9f6f-51c28cd53032.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89052336-765d7400-d34d-11ea-8f10-7c6cb6fcfe42.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			Verified performing a quick search on Yahoo points to
            <ul>
            	<li>`au.yahoo.con` for Australia</li>
            	<li>`ie.yahoo.com` for Ireland</li>
            	<li>`de.yahoo.com` for Germany</li>
            	<li>`fr.yahoo.com` for France</li>
            	<li>`nz.yahoo.com` for New Zealand</li>
            </ul>
		</td>
	</tr>
</table>
</details>


<details>
	<summary>New users on unsupported region</summary>
	
<table>
	<tr>
		<td>
			<details>
				<summary>Verified for unsupported regions, Yahoo isn't on the top of the list during onboarding</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89052678-fa176080-d34d-11ea-8d1d-e8d6148f04bc.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<li>Verified performing a search on Yahoo uses `search.yahoo.com`</li>
		</td>
	</tr>
</table>
</details>

<details>
	<summary>New users for Malaysia</summary>
		<li>Verified Yahoo is first on the list during onboarding</li>
		<li>Verified performing a search on Yahoo uses `malaysia.yahoo.com`</li>
</details>

-----------------------

Verification passed on iPad Pro with iOS 13.6 running 1.19.1(20.07.30.16)
<details>
<Summary>Existing Users</Summary>
<ul>
	<li>Verified existing search engine is retained post upgrade and performing a search uses the SE set in previous version</li>
	<li>Verified Yahoo is listed as a search engine button post upgrade</li>
	<li>Verified Yahoo shows up as a quick search engine post upgrade</li>
</ul>
</details>

<details>
<summary>New users with Yahoo supported regions</Summary>
<table>
	<tr>
		<td>
			<details>
				<summary>Verified Yahoo shows up as a search engine in onboarding and is the first in the list</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89054072-1b794c00-d350-11ea-9535-4fb5e15cc4ad.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89054093-2633e100-d350-11ea-9663-92cfc964adc4.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<details>
				<summary>Verified selecting a different SE/skipping onboarding, Yahoo is shown as the first SE in the quick SE list</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89054117-33e96680-d350-11ea-833c-10826bfc6f4d.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89054147-419eec00-d350-11ea-9c42-53804f1d3ece.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<li>Verified performing a quick search on Yahoo points to `search.yahoo.com`</li>
		</td>
	</tr>
</table>
</details>

<details>
<summary>New users with Yahoo supported region, with regional SE support</summary>

<table>
	<tr>
		<td>
			<details>
				<summary>Verified Yahoo shows up as a search engine in onboarding and is the first in the list with DDG as second</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89054187-51b6cb80-d350-11ea-860a-93731b71d31c.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89054322-82970080-d350-11ea-9555-6aeb529903d4.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<details>
				<summary>Verified selecting DDG as default during onboarding, Yahoo is shown as the first SE in the quick SE list</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89054357-904c8600-d350-11ea-9a7f-9828750a6440.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89054349-8d519580-d350-11ea-88b7-6da0b49c8803.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<details>
				<summary>Verified, for France, selecting Qwant as default during onboarding, Yahoo is shown as the first SE in the quick SE list</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89054382-9cd0de80-d350-11ea-81d0-b7ada1cd012b.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89054392-a0646580-d350-11ea-99a0-ee3a2f646f00.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89054445-b4a86280-d350-11ea-805e-5924029c7769.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89054438-b114db80-d350-11ea-8ad5-f93d4bed4918.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			Verified performing a quick search on Yahoo points to
            <ul>
            	<li>`au.yahoo.con` for Australia</li>
            	<li>`ie.yahoo.com` for Ireland</li>
            	<li>`de.yahoo.com` for Germany</li>
            	<li>`fr.yahoo.com` for France</li>
            	<li>`nz.yahoo.com` for New Zealand</li>
            </ul>
		</td>
	</tr>
</table>
</details>


<details>
	<summary>New users on unsupported region</summary>
	
<table>
	<tr>
		<td>
			<details>
				<summary>Verified for unsupported regions, Yahoo isn't on the top of the list during onboarding</summary>
				<table>
					<tr>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89054492-ca1d8c80-d350-11ea-99f5-3574b95bf9ba.png></td>
						<td><img width=300 src=https://user-images.githubusercontent.com/17010094/89054484-c5f16f00-d350-11ea-960e-aa47ab3fb93e.png></td>
					</tr>
				</table>
			</details>
		</td>
	</tr>
	<tr>
		<td>
			<li>Verified performing a search on Yahoo uses `search.yahoo.com`</li>
		</td>
	</tr>
</table>
</details>

<details>
	<summary>New users for Malaysia</summary>
		<li>Verified Yahoo is first on the list during onboarding</li>
		<li>Verified performing a search on Yahoo uses `malaysia.yahoo.com`</li>
</details>

**Comment by kjozwiak** [comment]
@srirambv awesome work with the above 👍
