### ISSUE TITLE
Update search engine for UK

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2766]
### Steps to Reproduce 
  1. Set region to `United Kindgom`
2. Search something using Yahoo

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.19 (20.7.31.18)`
* Verification **PASSED** on `iPhone 11` running `iOS 13.6` using `1.19 (20.7.31.18)`

STR/Cases used for the above verifications:

* changed region to `United Kingdom` via `Language & Region`
* searched using Yahoo via the URL bad and ensured `https://uk.search.yahoo.com` was being used
* searched using Yahoo using quick search while Google was default and ensured `https://uk.search.yahoo.com` was used
* ensured that once you've accepted the https://consent.yahoo.com modal, `https://uk.search.yahoo.com` is being used
* ensured that the above cases work on both PB and Normal modes.

------------------

Verification passed on iPhone  XR with iOS 13.5 running 1.19.1(20.07.31.19)
- Verified setting Yahoo as default in onboarding and doing a search uses `uk.search.yahoo.com`
- Verified doing a search by clicking on Yahoo in quick search bar performs search using `uk.search.yahoo.com`
- Verified once consent is approved on `consent.yahoo.com`, search page loads for `uk.search.yahoo.com`
- Verified correct search URL is used on both normal and private tabs
------------------

Verification passed on iPad Pro with iOS 13.6 running 1.19.1(20.07.31.19)
- Verified setting Yahoo as default in onboarding and doing a search uses `uk.search.yahoo.com`
- Verified doing a search by clicking on Yahoo in quick search bar performs search using `uk.search.yahoo.com`
- Verified once consent is approved on `consent.yahoo.com`, search page loads for `uk.search.yahoo.com`
- Verified correct search URL is used on both normal and private tabs
------------------

Verification passed on iPad Pro with iOS 12.4.1 running 1.19.1(20.07.31.19)
- Verified setting Yahoo as default in onboarding and doing a search uses `uk.search.yahoo.com`
- Verified doing a search by clicking on Yahoo in quick search bar performs search using `uk.search.yahoo.com`
- Verified once consent is approved on `consent.yahoo.com`, search page loads for `uk.search.yahoo.com`
- Verified correct search URL is used on both normal and private tabs
