### ISSUE TITLE
Unable to disconnect voyager service in Brave IOS.

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-ios#2769]
### Description: 
Unable to Disconnect Voyager account in IOS (Voyager option), Internal site.

### Steps to Reproduce 
  1. Unable to Disconnect Voyager account in IOS (Voyager option)
  2. Disconnect button isn't registered in Brave IOS when clicked.
  3.

**Actual result:** 
![voyager-disconnect](https://user-images.githubusercontent.com/1659004/89100946-be64bf80-d44f-11ea-8692-3d48e118e3e0.png)

**Expected result:**
Unable to disconnect a connected account (Voyager)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easyliy

**Brave Version:** 
1.18.1

**Device details:** 
Iphone 8plus

**Website problems only:**
- did you check with Brave Shields down? Yes
- did you check in Safari/Firefox (WkWebView-based browsers)?   Works in Safari and Firefox IOS

### Additional Information
Site requires a login, and hitting disconnect will require the user to re-connect the Voyager account.

Works on Desktop, but not in IOS.

![debug](https://user-images.githubusercontent.com/1659004/89100957-e0f6d880-d44f-11ea-86f7-b3737fb2d575.png)
![debug2](https://user-images.githubusercontent.com/1659004/89101108-3bdcff80-d451-11ea-9722-4c0928c8f881.png)

Can supply a test login/password for further debuging.

**Comment by iccub** [comment]
might be worth retesting, closing it as stale now
