### ISSUE TITLE
Private New Tab Should Show Favourites and Shield Stats

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#277]
The new tab in private mode should now show the same new tab as regular mode with a dark background (showing stats and favourites) due to the fact that Private Mode copy is now shown on the tab tray when no private tabs are created.

The only difference is the DuckDuckGo logo/copy will exist below the favourites which will be implemented in #62

![Screen Shot 2018-09-28 at 10.27.43 AM.png](https://images.zenhubusercontent.com/5b4cfb87b69de9433c0523d6/ff7bf832-2693-4d5c-8af7-8f01596474d8)

**Comment by tmancey** [comment]
@anthonypkeane Is this something you can help unblock please?

**Comment by anthonypkeane** [comment]
Feature parity is to have one set of stats per app, so we need to show the stats on both the normal and private tab screen.
