### ISSUE TITLE
certain search engines are not being displayed under "Quick Search Engines" after upgrade if onboarding skipped

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2770]
### Description: 

When upgrading from `1.19` to `1.19.1` and you skip the `Default search engine` onboarding model, `Yahoo` won't appear under `Quick-Search Engine`. However, when you type something into the URL, you'll notice `Yahoo` is still listed as an option for `Quick-Search` if `Search Suggestions` is enabled.

* Example of the issue occurring --> https://youtu.be/gHtqwr5Klpo

### Steps to Reproduce

  1. install `1.19 (20.7.21.9)` via TF and tap on `Skip` on the `Default search engine` onboarding model.
  2. update to `1.19.1 (20.7.31.17)` via TF
  3. go into `Hamburger Menu` --> `Settings` --> `Search Engines`

You'll notice that `Yahoo` is missing from the `Quick-Search Engine` section.

**Actual result:** 

| Yahoo Missing  | Still Appearing under Suggestions |
|:-------------:|:-------------:|
| ![IMG_0071](https://user-images.githubusercontent.com/2602313/89147351-5cc25500-d524-11ea-83ec-d30b3cf911b8.PNG)  | ![IMG_0072](https://user-images.githubusercontent.com/2602313/89147348-5c29be80-d524-11ea-81fd-72e7a21ab098.PNG)  |

**Expected result:**

`Yahoo` should be appearing under `Quick-Search` so users have the choice to disable if preferred.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

* Reproducible 100% of the time following the above STR.

**Brave Version:** 

* `1.19.1 (20.7.31.17)`

**Device details:** 

* `iPhone 6s+` using `iOS 12.4.1` - **Reproduced**
* `iPhone 11` using `iOS 13.6` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @srirambv @bsclifton @anthonypkeane @iccub

**Comment by srirambv** [comment]
Workaround to get Yahoo in quick search engine list in settings is to change the default SE from Google to something else and then the setting for Yahoo shows up.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.19.1(20.08.03.13)
- Verified steps from issue description
- Verified Yahoo is shown under quick search engine list in settings
- Verified changing default SE doesn't remove Yahoo from SE list
--------------
Verification passed on iPhone 7+ with iOS 13.6 running 1.19.1(20.08.03.13)
- Verified steps from issue description
- Verified Yahoo is shown under quick search engine list in settings
- Verified changing default SE doesn't remove Yahoo from SE list
--------------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.19.1(20.08.03.13)
- Verified steps from issue description
- Verified Yahoo is shown under quick search engine list in settings
- Verified changing default SE doesn't remove Yahoo from SE list
--------------
Verification passed on iPad Pro with iOS 13.6 running 1.19.1(20.08.03.13)
- Verified steps from issue description
- Verified Yahoo is shown under quick search engine list in settings
- Verified changing default SE doesn't remove Yahoo from SE list
--------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.19.1(20.08.03.13)
- Verified steps from issue description
- Verified Yahoo is shown under quick search engine list in settings
- Verified changing default SE doesn't remove Yahoo from SE list
--------------
