### ISSUE TITLE
Remove Unnecessary photo library usage description

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2778]
We have a privacy usage description in the app (`NSPhotoLibraryUsageDescription`) that is not allowed if we want a web browser entitlement, but luckily it seems to be no longer used.

This should be removed and we should ensure that photo upload still works on web pages

**Comment by iccub** [comment]
Test plan:
- Ensure that photo library related functionality in WKWebView still works without NSPhotoLibraryUsageDescription in the Info.plist

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 13.6 running 1.19.2(20.08.05.18)
- Verified able to save images(jpeg/png) from web pages
- Verified able to save gif images correctly 
- Verified able to upload video's on to webpages via the photo library
- Verified able to upload photos on to webpages via the photo library 
- Verified able to share downloaded image/video files with other applications 
--------
Verification passed on iPhone XR with iOS 13.5 running 1.19.2(20.08.05.18)
- Verified able to save images(jpeg/png) from web pages
- Verified able to save gif images correctly 
- Verified able to upload video's on to webpages via the photo library
- Verified able to upload photos on to webpages via the photo library 
- Verified able to share downloaded image/video files with other applications 
--------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.19.2(20.08.05.18)
- Verified able to save images(jpeg/png) from web pages
- Verified able to save gif images but only a frame from the image is saved which is an existing bug(#2790)
- Verified able to upload video's on to webpages via the photo library
- Verified able to upload photos on to webpages via the photo library 
- Verified able to share downloaded image/video files with other applications 
--------
Verification passed on iPad Pro with iOS 12.4.1 running 1.19.2(20.08.05.18)
- Verified able to save images(jpeg/png) from web pages
- Verified able to save gif images but only a frame from the image is saved which is an existing bug(#2790)
- Verified able to upload video's on to webpages via the photo library
- Verified able to upload photos on to webpages via the photo library 
- Verified able to share downloaded image/video files with other applications 
--------
Verification passed on iPad Pro with iOS 13.6 running 1.19.2(20.08.05.18)
- Verified able to save images(jpeg/png) from web pages
- Verified able to save gif images correctly
- Verified able to upload video's on to webpages via the photo library
- Verified able to upload photos on to webpages via the photo library 
- Verified able to share downloaded image/video files with other applications
