### ISSUE TITLE
Update Yubico lib to 3.1.0

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#2781]
### Description: 
Update YubiKit to 3.1.0: https://github.com/Yubico/yubikit-ios/releases/tag/3.1.0

### Test Plan

Verify Yubikey's are still working correctly

**Comment by srirambv** [comment]
@jumde @kylehickinson can you add a test plan for the issue for verification?

**Comment by kylehickinson** [comment]
@srirambv added, it will just be basic verification that yubikey's continue to work as expected. If you already do this test during manual passes you can mark this `QA/No`

**Comment by kjozwiak** [comment]
> @srirambv added, it will just be basic verification that yubikey's continue to work as expected. If you already do this test during manual passes you can mark this `QA/No`

Going to label this as `QA/No` as per above. QA runs through WebAuthN when we run through the manual passes via https://github.com/brave/qa-resources/blob/master/wikitemplate-ios.md#webauthn.
