### ISSUE TITLE
Add http/https URL scheme handlers

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2784]
## Test Plan

- Disable Safari 
    - Go to Settings.app > Screen Time > Content & Privacy Restrictions
    - Turn on `Content & Privacy Restrictions`
    - Go to Allowed Apps
    - Toggle Safari off
- Go to an app such as Notes, Mail, etc. that opens an app with Safari and not in an in-app webview, and click on a http/https link
- The link should open in Brave (if you haven't done this before you will get a prompt to open the link in Brave first)
- In Brave, Enable PBO or switch to private browsing mode
- Repeat open link step
- Verify it opens the link in a private tab

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 13.6 running 1.19.2(20.08.5.18)
- Verified test plan from https://github.com/brave/brave-ios/issues/2784#issue-673749474
<li>Verified clicking a link from notes asks for permission to open in Brave</li>
      <img width=300 src=https://user-images.githubusercontent.com/17010094/89508345-b4cbb680-d7c5-11ea-8588-11b60179471d.png>
<li>Verified if Brave is set to PBO only then opening links opens in a private tab</li>
<li>Verified if Brave is in normal mode but have private tabs open, opening a link via other app launches it in private tab and not in normal tab.</li>

----------------------

Verification passed on iPhone XR with iOS 13.6 running 1.19.2(20.08.5.18)
- Verified test plan from https://github.com/brave/brave-ios/issues/2784#issue-673749474
<li>Verified clicking a https/http link from notes asks for permission to open in Brave<br/>
<img width=300 src=https://user-images.githubusercontent.com/17010094/89510892-1b060880-d7c9-11ea-90b4-3facd3defb0d.png>   <img width=300 src=https://user-images.githubusercontent.com/17010094/89511054-4d176a80-d7c9-11ea-8d02-d53bdeca6b55.png></li>
<li>Verified if Brave is set to PBO only then opening links opens in a private tab</li>
<li>Verified if Brave is in normal mode but have private tabs open, opening a link via other app launches it in private tab and not in normal tab.</li>

----------------------

Verification passed on iPad Pro with iOS 13.6 running 1.19.2(20.08.5.18)

- Verified test plan from https://github.com/brave/brave-ios/issues/2784#issue-673749474
<li>Verified clicking a https/http link from notes asks for permission to open in Brave<br/>
<img width=300 src=https://user-images.githubusercontent.com/17010094/89520323-98377a80-d7d5-11ea-84b5-33fa3b8e90a3.png>   <img width=300 src=https://user-images.githubusercontent.com/17010094/89520274-8655d780-d7d5-11ea-8167-37a8d513026c.png></li>
<li>Verified if Brave is set to PBO only then opening links opens in a private tab</li>
<li>Verified if Brave is in normal mode but have private tabs open, opening a link via other app launches it in private tab and not in normal tab.</li>
