### ISSUE TITLE
Add default browser capability

### ISSUE THREAD

**Issue by snachx** [brave/brave-ios#2785]
## Problem Description 
Set as default browser in iOS/iPadOS
## Feature Overview 
Set as default browser in iOS/iPadOS
## Implementation Details 
Apple has shared its new developer guidelines regarding how to create a third-party app that can be used as a default in iOS 14

https://developer.apple.com/documentation/xcode/allowing_apps_and_websites_to_link_to_your_content/preparing_your_app_to_be_the_default_browser_or_email_client

**Comment by iccub** [comment]
Thanks, we are working on it :)

**Comment by iccub** [comment]
Blocked: waiting for an entitlement from Apple

**Comment by gh0sti** [comment]
@iccub I'm guessing you emailed Apple already for the special entitlement to enable default browser? I'm surprised they are taking this long to send back the special entitlement. Unless do you think they are waiting for iOS 14.1 to push that out to browser developers?

**Comment by iccub** [comment]
Yeah, still waiting @gh0sti 
basically all remaining opened tickets for upcoming release are waiting for Apple 
https://github.com/brave/brave-ios/milestone/53

no official date for iOS14 too

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14 running 1.20(20.09.11.20)
- Verified default browser message is shown on NTP on both normal and private tabs

Normal tab | Private tab
-- | --
![image](https://user-images.githubusercontent.com/17010094/93054413-30d8da00-f661-11ea-9101-91ed985b81ea.png) | ![image](https://user-images.githubusercontent.com/17010094/93054285-038c2c00-f661-11ea-819b-12ed6c91cad0.png)
![image](https://user-images.githubusercontent.com/17010094/93054466-464e0400-f661-11ea-99ba-f80460eb7993.png) | ![image](https://user-images.githubusercontent.com/17010094/93054507-549c2000-f661-11ea-956b-aff8340065d4.png)

- Verified settings show a menu option to set default browser
  <img width=300 src=https://user-images.githubusercontent.com/17010094/93054536-6382d280-f661-11ea-8cbd-25e5b0bece95.png>

- Verified clicking on the settings button opens up app settings where default browser can be changed to Brave
  <img width=300 src=https://user-images.githubusercontent.com/17010094/93054598-7d241a00-f661-11ea-835c-a97b03632a92.png>

- Verified clicking a link from an app opens inapp browser. Clicking on Safari button opens the link in Brave when Brave is set as default browser

**Comment by gh0sti** [comment]
will we see this in the app store this week the 1.20 update?

**Comment by iccub** [comment]
@gh0sti this or next week probably if Apple doesn't delay our app review

**Comment by hennrynusasatria** [comment]
@srirambv 

Is it also applicable on iPad? The Operating System on iPad is called iPadOS now (not iOS anymore).

**Comment by kylehickinson** [comment]
@hennrynusasatria This is also applicable on iPad, yes. iPadOS is just a marketing term, it still runs iOS.
