### ISSUE TITLE
Open with Brave prompt isn't asked on a clean install

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2791]
### Description: 
Open with Brave prompt isn't asked on a clean install

### Steps to Reproduce 
  1. Follow steps from #2784
  2. Uninstall Brave and reinstall 
  3. Open a http/https link via notes app
  4. No prompt is shown to open links in Brave

**Actual result:** 
Open with Brave prompt is not requested on a clean install

**Expected result:**
Probably ask again if the app is uninstalled and reinstalled 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.19.2

**Device details:** 
iPhone (iOS 13)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Please close the issue if this is an OS level problem and not Brave related

**Comment by iccub** [comment]
We can't control it, and it might behave differently in iOS14, the current 'default browser' is a hacky solution

**Comment by iccub** [comment]
I confirmed with @kylehickinson that this is 100% Apple controlled, closing this ticket
