### ISSUE TITLE
Website load progress indicator is bugged

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2799]
### Description: 

The orange progress bar under url bar doesn't work well.

### Steps to Reproduce 
New tab:
  1. Open new 
  2. Progress indicator will show

Loaded tabs:
1. Open two tabs, loads a website to each of them
2. Switch tabs by tapping on tab bar, progress indicator will show up for a second

**Actual result:** 

**Expected result:**
Progress indicator should show only when websites are loading.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.0.1 running 1.21(20.10.06.20)
- Verified steps from issue description and no progress indicator is shown when switching between tabs
-----------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.06.20)
- Verified steps from issue description and no progress indicator is shown when switching between tabs
-----------
Verification passed on iPad Pro with iOS 14.0.1 running 1.21(20.10.06.20)
- Verified steps from issue description and no progress indicator is shown when switching between tabs
-----------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.10.06.20)
- Verified steps from issue description and no progress indicator is shown when switching between tabs
