### ISSUE TITLE
NTP does not appear if quickly switching between tabs

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2805]
### Description: 

If you quickly switch between a web page tab and a new tab page tab, the new tab page will not appear when finally landing on the empty tab.

It's likely due to the animation of hiding the current NTP when moving to a web page tab, then switching back before the animation completes, therefore it being removed from the view hierarchy on the hiding animation completing

### Steps to Reproduce 
  1. Visit any web page on 1 tab
  2. Open a new tab
  3. In the tab bar, quickly tap on tab 1 (web page) then quickly back to tab 2 (empty new tab page)

**Actual result:** A blank white page will show
**Expected result:** The NTP should appear
**Reproduces how often:** Easily
**Brave Version:** local build on brave-today-feed, but probably happens on development

**Comment by iccub** [comment]
I have not seen it happen in a long time, and we moved away from gcdwebserver for NTP, perhaps we close it for retesting without merging the PR by our contributor

**Comment by Uni-verse** [comment]
Not able to repro this with STR above on iOS 14.x or iOS 15.x using version `1.36 (22.3.2.9) BraveCore 1.36.108 (99.0.4844.51)`

Devices: iPad (7th Gen) | iPhone 12 Pro | iPhone X
