### ISSUE TITLE
Support Full Page Screenshots of Brave (like Safari)

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ios#2806]
## Problem Description 

It is not easy to take a full-document screenshot with Brave. It is easy to do this [with Safari](https://user-images.githubusercontent.com/815158/89955172-0f1aac00-dbf8-11ea-8d6c-e1f7e69f7a94.png). When you take a screenshot from within Safari, you are offered the option of extending the screenshot to the full document height. When you take a screenshot from within Brave, this option is not presented.

## Developer Information

See https://developer.apple.com/documentation/uikit/uiwindowscene/3213938-screenshotservice

**Comment by kylehickinson** [comment]
We will add saving to PDF support in iOS 14 (#2807).

Will look into seeing if we can hook into this to provide support for the screenshot service as well. Im not sure if we'll be able to get all the same stuff as Safari. If it ends up _replacing_ the regular screenshot, we will likely have to not implement it since we won't have a way to toggle between taking a screenshot of the web page vs taking a screenshot of the screen

**Comment by kylehickinson** [comment]
Upon further investigation this will require us to implement a scene delegate, which will require more work so not as simple as hooking it up with the same PDF support unfortunately

**Comment by MetaSamsara** [comment]
> Upon further investigation this will require us to implement a scene delegate, which will require more work so not as simple as hooking it up with the same PDF support unfortunately

still looking for a solution. most chrome addons are broken in brave, haven't been able to use a single addon that works so far. this is the most annoying part of being in brave as I do need to save screenshot of scrolled pages.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.49 (23.3.15.17)
- Verified steps from [ #6825](https://github.com/brave/brave-ios/pull/6825)
- Verified able to take full page screenshots
- Verified full page screenshot is saved as a `.pdf` file in specified location
- Verified able to take full page screenshot on both `http`/`https` pages
- Verified taking a screenshot at the bottom of the page and selecting full page saves the full page length as screenshot
- Verified works on both landscape and portrait mode

iPhone 7+ (iOS 15.7.3) | iPhone XR (iOS 16.3.1) | iPad Pro (16.4 Beta 2)
-- | -- | -- 
<video src=https://user-images.githubusercontent.com/17010094/225805750-6b30d6cd-2806-4c89-89b1-3dd4ae9ecd2f.MP4> | <video src=https://user-images.githubusercontent.com/17010094/225805731-a528a258-106e-4cdb-bfdc-7ff1d52e3fcc.MP4> | <video src=https://user-images.githubusercontent.com/17010094/225805711-2be53ee7-737a-48e6-9720-367ba6d93552.MP4>
