### ISSUE TITLE
iOS14, add widget support

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2808]
### Description: 
Add Widget support for iOS14

iOS14 adds support for adding widgets on the home screen. 
We want to add a widget to show users Trackers & Ads blocked info.

@jamesmudgett to provide more info here and design.

**Comment by hennrynusasatria** [comment]
Perhaps, also add search like DuckDuckGo browser widget on iOS.

**Comment by iccub** [comment]
will be handled in https://github.com/brave/brave-ios/issues/4329
