### ISSUE TITLE
Youtube failing to load next videos

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-ios#2810]
### Description: 
Open m.youtube.com on IOS, scroll down expect next videos to load. No further videos are loading

### Steps to Reproduce 
  1. Open m.youtube.com on IOS
  2. Scroll to bottom
  3. Get endless loading, when you hit the bottom of page

**Actual result:** 
No more videos
![unnamed (3)](https://user-images.githubusercontent.com/1659004/90083417-8d955c00-dd66-11ea-92f0-1407e184ad9c.jpg)

**Expected result:**
Show more videos when you scroll.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 

Tested in Brave: 1.18 (20.07.06.15) and Dev 1.19 (20.06.02.17)

**Device details:** 
Iphone 8 plus

**Website problems only:**
- did you check with Brave Shields down?
 Yes, shields doesn't affect it.
- did you check in Safari/Firefox (WkWebView-based browsers)? 
Tested in Firefox, loading works correctly.

### Additional Information
Safari/chrome will open the youtube app, Desktop-site version also fails.
Clearing site settings, doesn't help.

Also reported via reddit .https://old.reddit.com/r/brave_browser/comments/i8nbhb/youtube_does_not_scroll_down_on_mobile_version/

**Comment by kylehickinson** [comment]
Tagging it with `Epic: Rewards` because it seems like its been caused by https://github.com/brave/brave-ios/blob/development/Client/Frontend/UserContent/UserScripts/AllFrames/AtDocumentStart/RewardsReporting.js so solution will require some testing with YouTube & Rewards integration

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14 running 1.20(20.08.31.09)
- Verified able to scroll through videos on home page for YouTube
- Verified able to scroll through the list of videos when playing a video
- Verified able to scroll through the home page with or without rewards enabled
- Verified able to scroll through videos on both normal and private tabs
-------------------
Verification passed on iPhone XR with iOS 13.6 running 1.20(20.08.31.09)
- Verified able to scroll through videos on home page for YouTube
- Verified able to scroll through the list of videos when playing a video
- Verified able to scroll through the home page with or without rewards enabled
- Verified able to scroll through videos on both normal and private tabs
-------------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.20(20.08.31.09)
- Verified able to scroll through videos on home page for YouTube
- Verified able to scroll through the list of videos when playing a video
- Verified able to scroll through the home page with or without rewards enabled
- Verified able to scroll through videos on both normal and private tabs

**Comment by jamesanderson9182** [comment]
Hate to sound like my manager, but do we know when the 1.20.0 release is likely to go out with the fix? Is this something that would be worth extracting out into a small release?

**Comment by iccub** [comment]
@jamesanderson9182 iOS14 is right around the corner and we decided to ship it together with all items needed for the default browser capability, we plan to submit 1.20 to Apple this week

We cut as much as we could for 1.20, now it's basically only the youtube fix + the default browser entitlement

sorry to keep you waiting

**Comment by jamesanderson9182** [comment]
> @jamesanderson9182 iOS14 is right around the corner and we decided to ship it together with all items needed for the default browser capability, we plan to submit 1.20 to Apple this week
> 
> We cut as much as we could for 1.20, now it's basically only the youtube fix + the default browser entitlement
> 
> sorry to keep you waiting

Thank you @iccub for getting back to me so quickly. 

That’s fine and makes sense, I can wait :) 

Good luck with the release & submission.
