### ISSUE TITLE
Implementation of "Find in Page" Function

### ISSUE THREAD

**Issue by hennrynusasatria** [brave/brave-ios#2816]
Hi All,

I understand that "Find in Page" Function can be called from "Share" menu as on the following screenshot:

![WhatsApp Image 2020-08-17 at 13 24 00](https://user-images.githubusercontent.com/69782842/90363766-7370bc00-e08d-11ea-8f87-ea559b9e4c95.jpeg)

![WhatsApp Image 2020-08-17 at 13 30 27](https://user-images.githubusercontent.com/69782842/90364052-f0039a80-e08d-11ea-96bc-3d8145c65c4f.jpeg)

But the "Find in Page" Function should be able to be called from three-dot menu directly, can you explore this feature request?

Thank you.

**Comment by iccub** [comment]
You can also type in url bar, show in page option shows there.
I am going to close this ticket as we do not plan to add it to the 3dot menu

**Comment by hennrynusasatria** [comment]
Hi @iccub 

Thank you for the response.

Please check:

https://github.com/mozilla-mobile/firefox-ios/issues/7116

It is mentioned that the performance is terrible on using JS for "Find in Page" function, does Brave iOS use JS for the "Find in Page" function? If so, is there any plan to implement a function on WKWebView for the "Find in Page" function?

Thank you.
