### ISSUE TITLE
Implementation of Search Function on Tabs Window, History Window, Bookmarks Window and Downloads Window

### ISSUE THREAD

**Issue by hennrynusasatria** [brave/brave-ios#2817]
Hi All,

As a user with huge Histories and Bookmarks, can you explore the Implementation of Search Function on Tabs Window, History Window, Bookmarks Window and Downloads Window?

Below is the sample from Firefox iOS on Search Function on Tabs Window:

![WhatsApp Image 2020-08-17 at 13 26 45](https://user-images.githubusercontent.com/69782842/90365475-04e12d80-e090-11ea-91d8-36f8ab60758d.jpeg)

Thank you.

**Comment by iccub** [comment]
I'm going to split this ticket in 4.
