### ISSUE TITLE
iOS "history" page not recording history

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-ios#2819]
### Description: 
Some reports from users say that Brave on iOS is not recording their history -- appears as though no browsing has been done.

### Steps to Reproduce 
  1. Browse Brave on iOS
  2. Open History page

**Actual result:** 
No browsing entries on History page
![image](https://user-images.githubusercontent.com/3299098/90428736-49ad9a00-e079-11ea-90e0-05beb09a22a1.png)

**Expected result:**
Browsing history to be recorded.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
I was unable to reproduce -- use claims this happens always.

**Brave Version:** 
Brave 1.19

**Device details:** 
iPhone 11 Pro and iPad Pro with iOS 13.6.1

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information
User thread:
https://community.brave.com/t/history-not-working-on-ios/150276

**Comment by srirambv** [comment]
Seems to retain a months worth of history for me 
![image](https://user-images.githubusercontent.com/17010094/90482396-1592b180-e12b-11ea-9072-8487463c236b.png)

**Comment by comedyname** [comment]
Hello, I have also been experiencing this. It's quite sporadic - sometimes will save weeks, other times will only show a day of history. Screenshot is current - showing last week, but no more (I've been using Brave consistently since May)
![FullSizeRender](https://user-images.githubusercontent.com/69859354/90528632-c4a2ad80-e16a-11ea-8f5d-195a7fbbdf8e.jpeg)

**Comment by srirambv** [comment]
@comedyname did you happen to switch to PB only mode in between or happen to clear history any time and seen this issue happen?

**Comment by comedyname** [comment]
@srirambv I may have accidentally switched and immediately switched back (would that auto clear the history?), when going to open a new tab, but don't remember that. I haven't used PB on Brave, and haven't cleared my history since I started using it

**Comment by iccub** [comment]
not applicable anymore since we moved to chromium's history
