### ISSUE TITLE
Favourites and background image is not shown on an NTP

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2821]
### Description: 
Favourites and background image is not shown on an NTP

### Steps to Reproduce 
  1. Clean install 1.20 build
  2. Skip onboarding, NTP doesn't show background image or default favourites
  3. Click on URL bar background image flashes and displays favourites

**Actual result:** 
![ios12ntp](https://user-images.githubusercontent.com/17010094/90476885-44f0f080-e122-11ea-9693-62b3ef258c59.gif)

**Expected result:**
Should show background image when a new tab is opened

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.20(20.08.13.15)

**Device details:** 
iPad Pro iOS 12.4.1

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by kylehickinson** [comment]
@srirambv I don't think this is  new bug, it occurs when the local web server fails to load because you have multiple instances of Brave opened and the port it binds to is already taken

I've seen this bug in the past so it isn't a regression at the very least

**Comment by kylehickinson** [comment]
I thought we already determined this to be not a bug in the past as it should only happen if a user is running multiple Brave instances?

**Comment by kylehickinson** [comment]
iOS 12 no longer supported
