### ISSUE TITLE
Changing FP setting in shields doesn't take effect immediately 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2822]
### Description: 
Changing FP setting in shields doesn't take effect immediately 

### Steps to Reproduce 
  1. Clean install 1.20 build
  2. Visit `https://browserleaks.com/webgl`
  3. Change site shields settings by enabling FP, page reloads but doesn't block FP
  4. Toggle FP off page reloads again
  5. Toggle FP again page reloads this time all FP is blocked

**Actual result:** 
![fpreload](https://user-images.githubusercontent.com/17010094/90481409-9e105280-e129-11ea-986e-f587a54d21d5.gif)

**Expected result:**
Should block items on first try

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.20(20.08.13.15)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by iccub** [comment]
Does it work in 1.19?

**Comment by DiGiTal1133** [comment]
Appleios.1@yahoo.com

**Comment by srirambv** [comment]
@iccub yes seems to happen on 1.19 as well

**Comment by iccub** [comment]
Thanks, removing `regression` label, will try to fix it this week

**Comment by hennrynusasatria** [comment]
Hi @iccub @srirambv @jhreis 

Is it similar issue as #917 ?

Thank you.

**Comment by srirambv** [comment]
@hennrynusasatria not really here page reloads but just doesn't block. Both are different I feel

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.0.1 running 1.21(20.10.06.20)
- Verified steps from issue description 
- Verified FP settings take effect immediately after page reloads
----------------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.06.20)
- Verified steps from issue description 
- Verified FP settings take effect immediately after page reloads
----------------
Verification passed on iPad Pro with iOS 14.0.1 running 1.21(20.10.06.20)
- Verified steps from issue description 
- Verified FP settings take effect immediately after page reloads
----------------

**Comment by srirambv** [comment]
Issue doesn't seem to be fixed on iOS 12. Needs to be retested once confirmed 
![ipad12-fp](https://user-images.githubusercontent.com/17010094/95322934-35c22f80-0895-11eb-9fe2-c96462b805dc.gif)

**Comment by srirambv** [comment]
This seems working on mobiles. On iPad irrespective of desktop site or mobile site the page loads. Same behaviour as desktop
