### ISSUE TITLE
Fingerprinting Blocking is Not Working

### ISSUE THREAD

**Issue by hennrynusasatria** [brave/brave-ios#2823]
Hi All,

**Description:**

Fingerprinting Blocking (FP) is not working, even it is already activated on the Shields, please check by opening on Private Window:

https://fingerprintjs.com/demo

**Steps to Reproduce:**

1. Activate Fingerprinting Blocking on the Shields
2. Open Private Window, go to https://fingerprintjs.com/demo
3. Close Private Window
4. Open Private Window, go to https://fingerprintjs.com/demo
5. You can see that the above demo can still fingerprint that we have visited the webpage previously

**Actual result:**
You can see that the above demo can still fingerprint that we have visited the webpage previously

**Expected result:**
The webpage must not be able to fingerprint the visit

**Reproduces how often:**
Easily reproduced

**Brave version:**
Version 1.19 (20.07.21.09)

cc: @iccub @srirambv @jhreis

**Comment by hennrynusasatria** [comment]
Hi @srirambv 

Do you think that https://fingerprintjs.com/demo uses WebGL Fingerprinting as on #478 ? Can you try to test https://fingerprintjs.com/demo ?

Thank you.

**Comment by pes10k** [comment]
Closing this issue.  Thank you for filing it, but for the reasons explained in https://github.com/brave/brave-browser/issues/20268#issuecomment-1003189602 (starting at "Again, i think fingerprint.js is sneaking by on misleading marketing here, not actual capabilities:") this is not a practical fingerprinting attack, its a very disingenuous commercial service trying to sell faux commercial fingerprinting services in a way that looks good on a small page with limited traffic, but would not work in the wild (and which Brave would provide strong protections against in the wild).

**Comment by cuba** [comment]
This is a non issue. fingerprintjs is not really fingerprinting anything here. For more information you can read here: 
https://github.com/brave/brave-browser/issues/20268#issuecomment-1003189602
