### ISSUE TITLE
VPN text update

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2825]
### Description: 

Please update the text on this screen 

![Image from iOS (3)](https://user-images.githubusercontent.com/7606853/90532188-cb5e0000-e12b-11ea-94f8-07e4e2b2df15.png)

**New Text**

Brave Firewall + VPN

Protect and secure your internet connection while blocking website trackers

~~~~

**Comment by anthonypkeane** [comment]
@iccub I slightly updated the text here - FYI

**Comment by anthonypkeane** [comment]
Also for the other screens

**Change**
Protect your connection and block ads and trackers across your whole device.
**_to_**
Protect your connection and block invasive trackers.


**Change**
This profile allows the VPN to automatically connect and secure traffic across your device - in every app, all the time. This VPN connection will be encrypted and routed through Brave's intelligent firewall to block ads and trackers.
**_to_**
This profile allows the VPN to automatically connect and secure traffic across your device all the time. This VPN connection will be encrypted and routed through Brave's intelligent firewall to block potentially harmful and invasive connections.


**Change**
Protects all of your apps (not just Brave)
**_to_**
Protects you from unwanted connections

**Comment by srirambv** [comment]
<details>
<summary>Verification passed on iPhone 7+ with iOS 14 running 1.20(20.08.31.09)</summary>

`Protect your connection and block invasive trackers.` |  `Protects you from unwanted connections` | `VPN Profile install message`
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/91843246-5d4a2a80-ec4d-11ea-80a9-9e28ed1cb226.png) |![image](https://user-images.githubusercontent.com/17010094/91843201-44da1000-ec4d-11ea-94bc-c562f81b9194.png) | ![image](https://user-images.githubusercontent.com/17010094/91844376-4278b580-ec4f-11ea-8bd2-be38b3176f51.png)

</details>

-------------

<details>
<summary>Verification passed on iPhone XR  with iOS 13.6 running 1.20(20.08.31.09)</summary>

`Protect your connection and block invasive trackers.` |  `Protects you from unwanted connections`  | `VPN Profile install message`
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/91843557-da759f80-ec4d-11ea-9e8a-832026849401.png) | ![image](https://user-images.githubusercontent.com/17010094/91843599-f2e5ba00-ec4d-11ea-8a98-6bbad4ea9a19.png) | ![image](https://user-images.githubusercontent.com/17010094/91844424-58867600-ec4f-11ea-8431-542c95c5d204.png)

</details>

-------------

<details>
<summary>Verification passed on iPad Pro with iOS 12.4.1 running 1.20(20.08.31.09)</summary>

`Protect your connection and block invasive trackers.` |  `Protects you from unwanted connections`  | `VPN Profile install message`
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/91844809-042fc600-ec50-11ea-8bc1-f30e66c90117.png) | ![image](https://user-images.githubusercontent.com/17010094/91844600-aef3b480-ec4f-11ea-9a57-bb03f6bc8fff.png) | ![image](https://user-images.githubusercontent.com/17010094/91844626-b74bef80-ec4f-11ea-8041-357d13e20202.png)

</details>
