### ISSUE TITLE
Rewards text update

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2829]
### Description: 
Please update the text for Rewards as shown in this figma design

https://www.figma.com/file/lu4tsEpIvnNpovX5O2BfNh/Mobile-Rewards-Settings?node-id=48%3A256

Please also remove the reference to USD

cc @mandar-brave for reference as this is rewards related

**Comment by anthonypkeane** [comment]
@bradleyrichter to remove the "blocked" label once he has finalized the copy

**Comment by kylehickinson** [comment]
Copy was finalized by @bradleyrichter

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14 running 1.20(20.09.11.20)
- Verified all USD references are removed from the rewards panel

![image](https://user-images.githubusercontent.com/17010094/93083239-37c81280-f68a-11ea-9f45-10e7da05aed6.png)| ![image](https://user-images.githubusercontent.com/17010094/93083144-1535f980-f68a-11ea-93c7-0ddddcabe60a.png) | ![image](https://user-images.githubusercontent.com/17010094/93083164-1bc47100-f68a-11ea-9b8d-9fae4c7e04b0.png) | ![image](https://user-images.githubusercontent.com/17010094/93083179-2121bb80-f68a-11ea-9c28-0f37a5b8cb30.png) | ![image](https://user-images.githubusercontent.com/17010094/93083197-28e16000-f68a-11ea-8609-d66cb7707e7b.png)
| -- | -- | -- | -- | -- | 
|![image](https://user-images.githubusercontent.com/17010094/93083333-575f3b00-f68a-11ea-92a3-94c1db40419c.png) | ![image](https://user-images.githubusercontent.com/17010094/93083368-6645ed80-f68a-11ea-8d31-16fa23fac2f7.png) | ![image](https://user-images.githubusercontent.com/17010094/93083385-6d6cfb80-f68a-11ea-91b9-06142cc0c98d.png) | ![image](https://user-images.githubusercontent.com/17010094/93083400-74940980-f68a-11ea-94f3-e17ebf5fd6a1.png) | ![image](https://user-images.githubusercontent.com/17010094/93083415-7c53ae00-f68a-11ea-8e63-0480b9270c83.png)

----------------

Verification passed on iPad Pro with iOS 14 running 1.20(20.09.11.20)
- Verified all USD references are removed from the rewards panel

![image](https://user-images.githubusercontent.com/17010094/93085522-98a51a00-f68d-11ea-8664-090b3586484c.png) | ![image](https://user-images.githubusercontent.com/17010094/93085546-a064be80-f68d-11ea-9bff-31cb76a973e8.png) | ![image](https://user-images.githubusercontent.com/17010094/93085583-ae1a4400-f68d-11ea-88e2-775100016345.png) | ![image](https://user-images.githubusercontent.com/17010094/93085610-b83c4280-f68d-11ea-9a07-55dbec629357.png) | ![image](https://user-images.githubusercontent.com/17010094/93085625-bd998d00-f68d-11ea-80a2-d83c9028321e.png)
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/93085661-cdb16c80-f68d-11ea-8142-2669686b7d1d.png) | ![image](https://user-images.githubusercontent.com/17010094/93085688-d99d2e80-f68d-11ea-8b4d-88be8d1415eb.png) | ![image](https://user-images.githubusercontent.com/17010094/93085708-e1f56980-f68d-11ea-88d0-887c8ed6ca01.png) | ![image](https://user-images.githubusercontent.com/17010094/93085950-47e1f100-f68e-11ea-87df-5665cbc2bcaf.png) | ![image](https://user-images.githubusercontent.com/17010094/93086004-5af4c100-f68e-11ea-8804-a2b62822700e.png)

----------------

Verification passed on iPhone XR with iOS 14 running 1.20(20.09.11.20)
- Verified all USD references are removed from the rewards panel

![image](https://user-images.githubusercontent.com/17010094/93086688-6694b780-f68f-11ea-84a5-ef994fa85f92.png) | ![image](https://user-images.githubusercontent.com/17010094/93086895-b8d5d880-f68f-11ea-8106-c6cee52b2da2.png) | ![image](https://user-images.githubusercontent.com/17010094/93087071-f76b9300-f68f-11ea-99a1-80139e46bd1d.png) | ![image](https://user-images.githubusercontent.com/17010094/93087071-f76b9300-f68f-11ea-99a1-80139e46bd1d.png) | ![image](https://user-images.githubusercontent.com/17010094/93087181-1d913300-f690-11ea-9c8a-641a010c7429.png)
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/93087202-25e96e00-f690-11ea-908d-51f73425fe6d.png) | ![image](https://user-images.githubusercontent.com/17010094/93087213-2a158b80-f690-11ea-95a1-4221ba2211c9.png) | ![image](https://user-images.githubusercontent.com/17010094/93087230-300b6c80-f690-11ea-935f-ddd0a1dacf2a.png) | ![image](https://user-images.githubusercontent.com/17010094/93087254-3568b700-f690-11ea-8d48-433e796ae7ee.png) | ![image](https://user-images.githubusercontent.com/17010094/93087281-3e598880-f690-11ea-9588-3b55e4af93bd.png)
