### ISSUE TITLE
Add Night Mode

### ISSUE THREAD

**Issue by hennrynusasatria** [brave/brave-ios#2830]
Hi All,

Is there any plan to add Night Mode on Brave iOS?

The example of Night Mode is as in Firefox iOS below, Brave iOS is based on Firefox iOS, thus it should be easier to fork Night Mode from Firefox iOS and add to Brave iOS. Night Mode is different than Dark Mode or Reader Mode.

Turn on Night Mode:

![WhatsApp Image 2020-08-21 at 09 22 30](https://user-images.githubusercontent.com/69782842/90845357-1a0bd400-e390-11ea-867d-66417d4cc2f3.jpeg)

From this:

![WhatsApp Image 2020-08-21 at 09 22 30 (1)](https://user-images.githubusercontent.com/69782842/90845363-1ed08800-e390-11ea-91f1-faaf9e35c489.jpeg)

Into this:

![WhatsApp Image 2020-08-21 at 09 22 30 (2)](https://user-images.githubusercontent.com/69782842/90845377-21cb7880-e390-11ea-9433-c93d7206394d.jpeg)

Thank you.

**Comment by hennrynusasatria** [comment]
Hi All,

Brave Android already supports Night Mode, please check:

https://github.com/brave/brave-browser/issues/6380

https://github.com/brave/brave-browser/issues/11085

Please also add Night Mode on Brave iOS.

Thank you.

**Comment by pbar1** [comment]
Any movement on this?

**Comment by marios-codes** [comment]
Moved recently from Android to iOS and I really miss that feature. Could you please port it from brave Android? Is it in your future feature list?

Thank you

**Comment by marios-codes** [comment]
Any progress on this? Is there a way to help somehow? Can we get the Android version night mode ported?

**Comment by NN---** [comment]
The missing feature from Firefox iOS.
Thanks for your work!

**Comment by marios-codes** [comment]
This is on the todo list for so long! Are there still any plans on implementing it? Thank you

**Comment by soner-yuksel** [comment]
For implementation and design details and test plan please check the PR linked.
https://github.com/brave/brave-ios/pull/5082

**Comment by anthonypkeane** [comment]
Do you have a setting for this @soner-yuksel?

**Comment by soner-yuksel** [comment]
@anthonypkeane Yes we do in 2 places actually which works in synchronization with each other.

Please check the video 

https://user-images.githubusercontent.com/6643505/158478317-c4ea222f-5717-464a-9f39-123311211768.mp4

You can see more information in PR description https://github.com/brave/brave-ios/pull/5082

**Comment by Uni-verse** [comment]
Verification completed using version `1.37 (22.3.2.23.17)`

Devices: 
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad (7th Gen) | iOS 15.2.1

Acceptance Criteria:

- [x] `Night Mode `Toggle shown under `Settings` > `Appearance` 
- [x] `Night Mode` toggle shown under share menu, after `Share with...`
- [x] Toggling ON/FF `Night Mode` in share menu will close menu automatically
- [x] Enabling `Night Mode` will change browser appearance to Dark as well as inverting website appearance
- [x] `Night Mode` respects websites that support `Appearance` settings (colors will be inverted)
- [x] `Automatic` settings in appearance respects the OS settings
- [x] Disabling `Night Mode` will change browser appearance will default to original settings
- [x] Night Mode w/ Private Tabs

Test Scenarios: 

1. Go Settings -> Appearance -> Set APPEARANCE light Mode
2. Browse wikipedia.org
3. Check Main Page on website is not in night mode and application itself is light mode on
4. Go back to Appearance Settings and Set Night mode toggle on
5. Check Application itself goes to dark mode and check open website is in night mode
6. Go back to Appearance Settings and Set Night mode toggle off
7. Check Application itself goes to light mode and check open website is not in night mode

iPhone
Night Mode (Share Menu) | Appearance Menu | Light w/ Night Mode OFF | Light w/ Night Mode ON | Night Mode ON | Night Mode OFF
-|-|-|-|-|-
![IMG_2546](https://user-images.githubusercontent.com/17885425/159985225-a6c57708-1258-4bd9-83cc-1c5f444a015d.PNG) | ![IMG_2547](https://user-images.githubusercontent.com/17885425/159985226-d7d72cfc-b841-4034-bf64-40b98eaf650d.PNG) | ![IMG_2548](https://user-images.githubusercontent.com/17885425/159985227-6cf7b934-843f-4cfa-8de6-003952e2f850.PNG) | ![IMG_2549](https://user-images.githubusercontent.com/17885425/159985228-53548b56-e636-44ae-92ad-2dc9aed0219d.PNG) | ![IMG_2543](https://user-images.githubusercontent.com/17885425/159985209-3d73e6d1-2ff8-404a-af0b-7fa9fa05460c.PNG) | ![IMG_2545](https://user-images.githubusercontent.com/17885425/159985223-8d762399-7653-48c4-ad9b-e0665506f68b.PNG)

iPad
Share menu | Share menu | Light w/ Night Mode ON | Light w/ Night Mode OFF | Dark w/ Night Mode ON | Dark w/ Night Mode OFF
-|-|-|-|-|-
![IMG_0213](https://user-images.githubusercontent.com/17885425/159985972-b40982bc-303a-48d6-bed3-61762f41e7b7.PNG) | ![IMG_0214](https://user-images.githubusercontent.com/17885425/159985983-a25c342d-93b5-4468-87dd-fdd273cde74d.PNG) | ![IMG_0215](https://user-images.githubusercontent.com/17885425/159985996-ecccf704-6640-476b-b8d2-19a2598a2914.PNG) | ![IMG_0216](https://user-images.githubusercontent.com/17885425/159986001-6adeaaec-4d6d-422c-bdb6-ff75ea0b4076.PNG) | ![IMG_0217](https://user-images.githubusercontent.com/17885425/159986005-61e1c55b-0241-44a6-8eb2-b4bd72c7eb50.PNG) | ![IMG_0218](https://user-images.githubusercontent.com/17885425/159986008-fa00b689-f7ae-49b3-a25e-ade80dd07cdd.PNG)
