### ISSUE TITLE
Add UI to encourage user to set Brave as default browser.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2831]

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14 running 1.20(20.09.11.20)
- Verified default browser message is shown on NTP on both normal and private tabs

Normal tab | Private tab
-- | --
![image](https://user-images.githubusercontent.com/17010094/93054413-30d8da00-f661-11ea-9101-91ed985b81ea.png) | ![image](https://user-images.githubusercontent.com/17010094/93054285-038c2c00-f661-11ea-819b-12ed6c91cad0.png)
![image](https://user-images.githubusercontent.com/17010094/93054466-464e0400-f661-11ea-99ba-f80460eb7993.png) | ![image](https://user-images.githubusercontent.com/17010094/93054507-549c2000-f661-11ea-956b-aff8340065d4.png)

- Verified settings show a menu option to set default browser
  <img width=300 src=https://user-images.githubusercontent.com/17010094/93054536-6382d280-f661-11ea-8cbd-25e5b0bece95.png>

- Verified clicking on the settings button opens up app settings where default browser can be changed to Brave
  <img width=300 src=https://user-images.githubusercontent.com/17010094/93054598-7d241a00-f661-11ea-835c-a97b03632a92.png>

- Verified clicking a link from an app opens inapp browser. Clicking on Safari button opens the link in Brave when Brave is set as default browser
