### ISSUE TITLE
Update onboarding flow

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2832]
Related ticket 
https://github.com/brave/security/issues/199

**Comment by iccub** [comment]
Test plan:
1. No clipboard, no ref code:
- Have empty clipboard
- Fresh install the app
- Verify that no privacy consent onboarding screen is showing

2. Clipboard, no ref code:
- Copy random text to clipboard
- Fresh install the app
- Verify that privacy consent onboarding screen is showing
- Choose either option
- Verify that no sponsored assets are showing

3. Clipboard, ref code, consent:
- Fresh install the app using ref code website
- Verify that privacy consent onboarding screen is showing
- Choose `yes` on consent screen
- (if iOS 14) notice the clipboard alert at the top of the app
- Verify that sponsored assets are downloaded

4. Clipboard, ref code, no consent:
- Fresh install the app using ref code website
- Verify that privacy consent onboarding screen is showing
- Choose `no` on consent screen
- (if iOS 14) verify that no clipboard alert showed
- Verify that sponsored assets are downloaded

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.6 running 1.20(20.09.2.14)
<details>
<summary>No clipboard data</summary>

- Verified no consent message is shown when the clipboard is empty 
</details>
<details>
<summary>No ref code/Random text in clipboard</summary>

- Verified copying random text and doing a clean install shows the consent message. 
- Verified 404 record not found message is shown for ref code lookup 
</details>
<details>
<summary>Ref code in clipboard and consent to clipboard check</summary>

- Verified clean install via ref code prompts consent message after launch
- Verified custom tiles and custom NTP assets are shown after check is complete
- Verified Ref code is shown in logs and captures `downloadID` 
</details>
<details>
<summary>Ref code in clipboard but disagree on clipboard check</summary>

- Verified clean install via ref code prompts consent message after launch
- Verified declining on consent message still show all custom assets and NTP images 
- Verified Ref code is empty in logs
- Verified 404 record not found message is shown for ref code lookup 
</details>

<details>
<summary>Screenshots</summary>

English | French | German | Spanish | Japanese
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/92590697-8e9da880-f294-11ea-8133-526eb49c327c.png) | ![image](https://user-images.githubusercontent.com/17010094/92590722-952c2000-f294-11ea-813a-8623f2e56d37.png) | ![image](https://user-images.githubusercontent.com/17010094/92590737-9c532e00-f294-11ea-841b-c62951b40f09.png) | ![image](https://user-images.githubusercontent.com/17010094/92590756-a543ff80-f294-11ea-96cd-4f6aa209beb6.png) | ![image](https://user-images.githubusercontent.com/17010094/92590768-ad03a400-f294-11ea-9803-0e83158102bf.png)
</details>

---------------------------

Verification passed on iPhone 7+ with iOS 14 running 1.20(20.09.2.14)
<details>
<summary>No clipboard data</summary>

- Verified no consent message is shown when the clipboard is empty 
</details>
<details>
<summary>No ref code/Random text in clipboard</summary>

- Verified copying random text and doing a clean install shows the consent message. 
- Verified 404 record not found message is shown for ref code lookup 
- Verified clipboard alert is shown
</details>
<details>
<summary>Ref code in clipboard and consent to clipboard check</summary>

- Verified clean install via ref code prompts consent message after launch
- Verified custom tiles and custom NTP assets are shown after check is complete
- Verified Ref code is shown in logs and captures `downloadID` 
- Verified clipboard alert is shown 
</details>
<details>
<summary>Ref code in clipboard but disagree on clipboard check</summary>

- Verified clean install via ref code prompts consent message after launch
- Verified declining on consent message still show all custom assets and  NTP images 
- Verified Ref code is empty in logs
- Verified 404 record not found message is shown for ref code lookup 
- Verified clipboard alert is shown 
</details>

<details>
<summary>Screenshots</summary>

English | French | Chinese(Traditional) | Italian | German
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/92593239-b131c080-f298-11ea-848f-10b1099ddde2.png) | ![image](https://user-images.githubusercontent.com/17010094/92593256-b989fb80-f298-11ea-844a-fd4541dd6279.png) | ![image](https://user-images.githubusercontent.com/17010094/92593336-d8888d80-f298-11ea-9f0e-ad44a87f4c60.png) | ![image](https://user-images.githubusercontent.com/17010094/92593359-e5a57c80-f298-11ea-8130-e0cdce8d8f5c.png) | ![image](https://user-images.githubusercontent.com/17010094/92593386-f0601180-f298-11ea-8356-6315207efdb2.png)

Clipboard message 

English | French | Chinese(Traditional) | Italian | German
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/92593687-6f554a00-f299-11ea-9e6f-9faff2c37176.png) | ![image](https://user-images.githubusercontent.com/17010094/92593547-2ef5cc00-f299-11ea-97cd-186330239f7b.png) | ![image](https://user-images.githubusercontent.com/17010094/92593516-20a7b000-f299-11ea-9861-f252bd6305e0.png) | ![image](https://user-images.githubusercontent.com/17010094/92593460-108fd080-f299-11ea-8b00-b6b9d3651316.png) | ![image](https://user-images.githubusercontent.com/17010094/92593414-fe159700-f298-11ea-873a-bd358c670d68.png)

</details>

---------------------------

Verification passed on iPad Pro with iOS 12.4.1 running 1.20(20.09.2.14)
<details>
<summary>No clipboard data</summary>

- Verified no consent message is shown when the clipboard is empty 
</details>
<details>
<summary>No ref code/Random text in clipboard</summary>

- Verified copying random text and doing a clean install shows the consent message. 
- Verified 404 record not found message is shown for ref code lookup 
</details>
<details>
<summary>Ref code in clipboard and consent to clipboard check</summary>

- Verified clean install via ref code prompts consent message after launch
- Verified custom tiles and custom NTP assets are shown after check is complete
- Verified Ref code is shown in logs and captures `downloadID` 
</details>
<details>
<summary>Ref code in clipboard but disagree on clipboard check</summary>

- Verified clean install via ref code prompts consent message after launch
- Verified declining on consent message still show all custom assets and NTP images 
- Verified Ref code is empty in logs
- Verified 404 record not found message is shown for ref code lookup 
</details>
<details>
<summary>Screenshots</summary>

English | Russian | Chinese(Hong Kong) | French | Japanese
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/92596256-767e5700-f29d-11ea-9da5-bdc27ce399ae.png) | ![image](https://user-images.githubusercontent.com/17010094/92596284-7f6f2880-f29d-11ea-9214-0c776917b2c4.png) | ![image](https://user-images.githubusercontent.com/17010094/92596313-8ac25400-f29d-11ea-874a-fe2fe122d758.png) | ![image](https://user-images.githubusercontent.com/17010094/92596341-97df4300-f29d-11ea-97c5-fdbf1edea483.png) | ![image](https://user-images.githubusercontent.com/17010094/92596373-a0d01480-f29d-11ea-851e-afcd7010a20b.png)



</details>
