### ISSUE TITLE
Add translations for 1.20

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2833]
- [x] Push new strings
- [x] Pull translations

**Comment by iccub** [comment]
Blocked until all UI tickets are finished

**Comment by iccub** [comment]
This ticket was split between 2 pull requests:
https://github.com/brave/brave-ios/pull/2854
https://github.com/brave/brave-ios/pull/2857

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.6 running 1.20(20.09.2.14)

<details>
<summary>Verified text is translated</summary>

English | French | German | Spanish | Japanese
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/92590697-8e9da880-f294-11ea-8133-526eb49c327c.png) | ![image](https://user-images.githubusercontent.com/17010094/92590722-952c2000-f294-11ea-813a-8623f2e56d37.png) | ![image](https://user-images.githubusercontent.com/17010094/92590737-9c532e00-f294-11ea-841b-c62951b40f09.png) | ![image](https://user-images.githubusercontent.com/17010094/92590756-a543ff80-f294-11ea-96cd-4f6aa209beb6.png) | ![image](https://user-images.githubusercontent.com/17010094/92590768-ad03a400-f294-11ea-9803-0e83158102bf.png)
</details>

---------------------------

Verification passed on iPhone 7+ with iOS 14 running 1.20(20.09.2.14)

<details>
<summary>Verified text is translated</summary>

English | French | Chinese(Traditional) | Italian | German
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/92593239-b131c080-f298-11ea-848f-10b1099ddde2.png) | ![image](https://user-images.githubusercontent.com/17010094/92593256-b989fb80-f298-11ea-844a-fd4541dd6279.png) | ![image](https://user-images.githubusercontent.com/17010094/92593336-d8888d80-f298-11ea-9f0e-ad44a87f4c60.png) | ![image](https://user-images.githubusercontent.com/17010094/92593359-e5a57c80-f298-11ea-8130-e0cdce8d8f5c.png) | ![image](https://user-images.githubusercontent.com/17010094/92593386-f0601180-f298-11ea-8356-6315207efdb2.png)
</details>

---------------------------

Verification passed on iPad Pro with iOS 12.4.1 running 1.20(20.09.2.14)
<details>
<summary>Verified text is translated</summary>

English | Russian | Chinese(Hong Kong) | French | Japanese
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/92596256-767e5700-f29d-11ea-9da5-bdc27ce399ae.png) | ![image](https://user-images.githubusercontent.com/17010094/92596284-7f6f2880-f29d-11ea-9214-0c776917b2c4.png) | ![image](https://user-images.githubusercontent.com/17010094/92596313-8ac25400-f29d-11ea-874a-fe2fe122d758.png) | ![image](https://user-images.githubusercontent.com/17010094/92596341-97df4300-f29d-11ea-97c5-fdbf1edea483.png) | ![image](https://user-images.githubusercontent.com/17010094/92596373-a0d01480-f29d-11ea-851e-afcd7010a20b.png)

</details>
