### ISSUE TITLE
Add option to disable safe browsing in iOS14

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2839]
WKWebView in iOS14 has `isfraudulentwebsitewarningenable` flag enabled by default.
We should provide a simple toggle in settings that allow users to disable it

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.0.1 running 1.21(20.10.6.20)
- Verified other privacy settings has an entry for `Block dangerous sites`
   <img width=300 src=https://user-images.githubusercontent.com/17010094/95310264-1e2e7b00-0884-11eb-9647-837df58450ec.png>

- Verified disabling the switch and visiting phishing pages from `https://testsafebrowsing.appspot.com/` doesn't show any interstitial page
![iphone-safe](https://user-images.githubusercontent.com/17010094/95316787-2b4f6800-088c-11eb-9c82-a2bf4afd7b89.gif)

- Verified able to load the page from the interstitial page 
--------------
Verification passed on iPad Pro with iOS 14.0.1 running 1.21(20.10.6.20)
- Verified other privacy settings has an entry for `Block dangerous sites`
   <img width=500 src=https://user-images.githubusercontent.com/17010094/95311625-c3961e80-0885-11eb-8834-182255c27702.png>

- Verified disabling the switch and visiting phishing pages from `https://testsafebrowsing.appspot.com/` doesn't show any interstitial page
![ipad-safebrowsing](https://user-images.githubusercontent.com/17010094/95317736-7918a000-088d-11eb-9c72-3cb1008dd02c.gif)

- Verified able to load the page from the interstitial page 
--------------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.6.20)
- Verified other privacy settings don't have  an entry for `Block dangerous sites`
   <img width=300 src=https://user-images.githubusercontent.com/17010094/95311465-8fbaf900-0885-11eb-9992-1f46dddae725.png>

- Verified able to load the page from the interstitial page

**Comment by xwartz** [comment]
I tested it on iOS 15.6, it doesn't work for me
