### ISSUE TITLE
Notification to inform users about default browser

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2840]
### Description: 
I'd like to notify iOS14 users that they can no set Brave as the default browser. 

Implement an OS level check to determine what OS the user is on
If the user is on iOS14, 2 hours after opening Brave schedule the following quiet notification

**Title:** Brave Web Browser
**Message:** Optimized for iOS14. Make Brave your default browser today.

Tapping on the notification deep links the user to settings.app where the user can enable Brave as the default

@jumde please confirm that security are ok with the OS level check?

**Comment by kylehickinson** [comment]
@anthonypkeane A few questions:

- Do we want to remove the timed notification if the app is subsequently opened via http/https URLs (therefore we know that we are set as default)?
  - What if they've already visited us via http/https without ever opening the app through another means
- Do we want to remove the timed notification if they tap on the banner/settings entry that deep links?
- Are we OK if this is _not_ a silent notification (if a user has already allowed Brave notifications permissions in the past)
- Are we OK that tapping the notification will actually launch Brave _first_, then jump into Settings.app

**Comment by anthonypkeane** [comment]
Slack: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1598388250045400

Do we want to remove the timed notification if the app is subsequently opened via http/https URLs (therefore we know that we are set as default)?
->YES
What if they've already visited us via http/https without ever opening the app through another means
->If Brave is already the default (via whatever means) we don’t need to schedule this notification
Do we want to remove the timed notification if they tap on the banner/settings entry that deep links?
-> YES
Are we OK if this is not a silent notification (if a user has already allowed Brave notifications permissions in the past)
-> YES
Are we OK that tapping the notification will actually launch Brave first, then jump into Settings.app
-> YES

**Comment by iccub** [comment]
for me this is redundant if we are going to show a callout on NTP, 
the callout is visible until user taps on it or closes it by 'x' button

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4 running 1.23(21.2.12.9)
- Verified test plan from #3240
   <img width=350 src=https://user-images.githubusercontent.com/17010094/107764014-5f013980-6d27-11eb-81f6-526d4a96ea4a.png>

------------------
Verification passed on iPad Pro with iOS 14.4 running 1.23(21.2.12.9)
- Verified test plan from #3240
   <img width=500 src=https://user-images.githubusercontent.com/17010094/107764424-1b5aff80-6d28-11eb-9f3a-0e86fe55ee20.png>
