### ISSUE TITLE
Web Address and Webpage Disappear After Long Period of Inactivity

### ISSUE THREAD

**Issue by hennrynusasatria** [brave/brave-ios#2842]
Hi All,

### Description: 
Web Address and Webpage Disappear After Long Period of Inactivity

### Steps to Reproduce 
  1. Open many Webpages on Tabs.
  2. Close Brave iOS, then leave it for around a day.
  3. Open Brave iOS, then web address and webpage disappear sometimes.

**Actual result:**

![WhatsApp Image 2020-08-27 at 07 54 46](https://user-images.githubusercontent.com/69782842/91379389-c9dbb880-e84c-11ea-9166-12c86a092512.jpeg)

![WhatsApp Image 2020-08-27 at 07 54 57](https://user-images.githubusercontent.com/69782842/91379400-cd6f3f80-e84c-11ea-80b7-25ecda8d3a8a.jpeg)

**Expected result:**
Web address and webpage must not disappear after long period of inactivity.

Perhaps, it may have relation to #1139

**Reproduces how often:** Intermittent Issue

**Brave Version:** Version 1.19.2 (20.08.05.18)

**Device details:** iPhone 7 (iOS 13.6.1)

**Website problems only:**
- did you check with Brave Shields down? No problem with website.
- did you check in Safari/Firefox (WkWebView-based browsers)? No problem with website

**Comment by srirambv** [comment]
Is it consistent with the steps? Does trying to reload the tab bring back the page? Could be due to discarding of tabs for inactivity is not working correctly

**Comment by hennrynusasatria** [comment]
Hi @srirambv 

Most of time, I found it is consistent with the steps, but indeed it needs more investigation as it is intermittent issue.

Thank you.

**Comment by iccub** [comment]
should be fixed with https://github.com/brave/brave-ios/issues/6730
