### ISSUE TITLE
Pop-up Windows are Not Standard to iOS

### ISSUE THREAD

**Issue by hennrynusasatria** [brave/brave-ios#2844]
### Description: 
Pop-up Windows are Not Standard to iOS

### Steps to Reproduce 
  1. Use Brave iOS for a longer period.
  2. Open Settings Window, its appearance is not standard to iOS.
  3. Check screenshots below, including from Safari for comparison.

**Actual result:**

![WhatsApp Image 2020-08-27 at 10 41 57](https://user-images.githubusercontent.com/69782842/91381983-e37ffe80-e852-11ea-994b-c437583342eb.jpeg)

**Expected result:**

**From Brave iOS**

![WhatsApp Image 2020-08-27 at 10 41 57 (1)](https://user-images.githubusercontent.com/69782842/91382046-07434480-e853-11ea-875a-cdb17bae03aa.jpeg)

**From Safari**

![WhatsApp Image 2020-08-27 at 10 42 48](https://user-images.githubusercontent.com/69782842/91382069-1a561480-e853-11ea-891c-8db99e7cbfd5.jpeg)

**Reproduces how often:** Intermittent Issue

**Brave Version:** Version 1.19.2 (20.08.05.18)

**Device details:** iPhone 7 (iOS 13.6.1)

**Website problems only:**
- did you check with Brave Shields down? Not related to website.
- did you check in Safari/Firefox (WkWebView-based browsers)?  Not related to website.

**Comment by srirambv** [comment]
Related to #1722?

**Comment by hennrynusasatria** [comment]
Hi @srirambv 

No, it is different issue, not related to #1722 

The background window does not really sink according to iOS standard, when the Settings window is floating.

Thank you.

**Comment by kylehickinson** [comment]
This was fixed already by #2734 and will be available in a future release
