### ISSUE TITLE
Smoke test / re-qualify the slim

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#2847]
### Description: 
There has been recent work done to the process which generate the iOS adblock content blocker list 😄 This process has been called "slim-list" as it aggregates a few lists and reduces them to a set

We had a few outages and/or broken rules; details can be seen here (private link):
https://github.com/brave/devops/issues/3401

Specifically, the last two problems were with the conversion of adblock-plus format to iOS content blocker format. Before, this was being done using https://github.com/brave/ab2cb. Now, that functionality is covered via https://github.com/brave/adblock-rust (huge shout out to @antonok-edm for that work!)

I'm capturing this issue for us to re-qualify the dynamically built list. If the list looks good, we can re-enable automation that rebuilds this list on a frequency (once a week I believe)? More details about the frequency and how the components interact with each other can be found here:
https://github.com/brave/slim-list-lambda

Specific problems 

#### Downloading the test client
  1. See `Client.ipa` in https://bravesoftware.slack.com/archives/C06UXF3KJ/p1598544629053900?thread_ts=1598543148.052600&cid=C06UXF3KJ
  2. Download and install using iTunes (you can drag onto device)
  3. Open Settings > General > scroll to bottom > Device Management > BRAVE SOFTWARE > Trust
  4. You should now be able to open the BraveEnt app

#### Proposed tests
1. Log into Twitter.com
2. Verify you can read tweets, use the website in general
3. Log out
4. Log into YouTube.com
5. Verify you can see subscriptions, videos, etc and that you're logged in
6. Log out
7. Visit dailymail.co.uk (or a site which is known to have ads which you expect to be blocked)
8. Verify ads are blocked

**Comment by bsclifton** [comment]
Just ran through the above - also went to a few other sites (craigslist.org, etc). Everything working great! 👍

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.6 running enterprise build
- Verified test plan from issue description
- Verified able to login to Twitter and scroll through the feed and search users 
- Verified able to login to YouTube and play videos without any pre-roll ads or end-video ads. Didn't encounter any non-skippable ads 
- Verified visiting a bunch of popular sites that are ads heavy didn't show any ads 
------------------------
Verification passed on iPhone 7+ with iOS 14 running enterprise build
- Verified test plan from issue description
- Verified able to login to Twitter and scroll through the feed and search users 
- Verified able to login to YouTube and play videos without any pre-roll ads or end-video ads. Didn't encounter any non-skippable ads 
- Verified visiting a bunch of popular sites that are ads heavy didn't show any ads

**Comment by bsclifton** [comment]
Thanks, @srirambv 😄👍 

I'll go ahead and close this issue - I think we're good to go, @pes10k

**Comment by pes10k** [comment]
great!  Thanks ya'll!  I'll work with devops to get things running again
