### ISSUE TITLE
Support the lilo.org Search Engine

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ios#2848]
## Problem Description
A Brave user [has requested](https://twitter.com/pascal_baratoux/status/1299750223024140291) support for the lilo.org search engine.

![image](https://user-images.githubusercontent.com/815158/91642558-e7965280-e9f1-11ea-9d52-29f071967f1e.png)

**Comment by kylehickinson** [comment]
I don't think we'll add direct support, but users should be able to add it themselves when we implement OpenSearch (#936), so I'll close this as a dupe (technically)

**Comment by jonathansampson** [comment]
#936 definitely is the better path forward. Thanks!
