### ISSUE TITLE
archive.is lists Brave as 'unsupported browser'

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2849]
### Steps to Reproduce 
  1. visit archive.is

**Actual result:** 
'Unsupported browser' message is showing.

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
* `iPhone 11` running `iOS 14.0.1` using `1.21 (20.09.30.20)` - **PASSED**

`Mobile view using iPhone iOS 14` | `Desktop view using iPhone iOS 14`
---|---
| ![386A4C45-601E-49CC-86E7-3879512B7607](https://user-images.githubusercontent.com/2602313/94887463-5ed16300-0444-11eb-8bef-621d8b996066.PNG) | ![E06DEA2C-B193-4A1F-A6C5-48D0D2A16854](https://user-images.githubusercontent.com/2602313/94887473-63961700-0444-11eb-8d3f-f64399870321.PNG)

* `iPad Air (3rd Gen)` running `iOS 14.0.1` using `1.21 (20.09.30.20)` - **PASSED**

`Mobile view using iPad iOS 14` | `Desktop view using iPad iOS 14`
---|---
| ![IMG_0160](https://user-images.githubusercontent.com/2602313/94887571-b374de00-0444-11eb-8af0-5e786e87254e.PNG) | ![IMG_0159](https://user-images.githubusercontent.com/2602313/94887581-b7a0fb80-0444-11eb-81ff-1247a552f51c.PNG)

* `iPad Mini 4` running `iOS 13.7` using `1.21 (20.09.30.20)` - **PASSED**

`Mobile view using iPad iOS 13` | `Desktop view using iPad iOS 13`
---|---
| ![IMG_0354](https://user-images.githubusercontent.com/2602313/94887708-06e72c00-0445-11eb-88ef-59c158da0744.PNG) | ![IMG_0353](https://user-images.githubusercontent.com/2602313/94887719-0b134980-0445-11eb-88e2-b0fa21a1ab2c.PNG)

Went through the following cases:

* ensured that archive.is is loading without displaying `Unsupported browser` message on both mobile/desktop versions.

**Comment by kjozwiak** [comment]
@srirambv just needs a iPhone iOS 13 check and the above is done 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.21(20.10.2.20)

iPhone XR (iOS 13.5) with mobile view | iPhone XR (iOS 13.5) with desktop view
-- | --
![image](https://user-images.githubusercontent.com/17010094/95054598-01f6d680-06ea-11eb-99d4-12b30c2e297c.png) | ![image](https://user-images.githubusercontent.com/17010094/95054605-07ecb780-06ea-11eb-8552-de4b59cf0a50.png)

iPad Pro (iOS 12.4.1) with mobile view | iPad Pro (iOS 12.4.1) with desktop view
-- | --
![image](https://user-images.githubusercontent.com/17010094/95054480-d5db5580-06e9-11eb-831b-c7f45e7585c1.png) | ![image](https://user-images.githubusercontent.com/17010094/95054541-f1def700-06e9-11eb-88d2-37ef7aeda34b.png)
