### ISSUE TITLE
Migrate to Swift 4.2

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#285]
Firstly:

- [ ] Verify that our Carthage dependencies support Swift 4.2. (It is already known they support Xcode 10 + Swift 4.1)

A starter list of migration tasks:

- [ ] Run Xcode 10's Swift 4.2 migrator to see what will be automatically changed
- [ ] Add `CaseIterable` where needed, currently anywhere that has its own "allCases" property in an enum. (see: `TabBarVisibility` & `PasswordManagerShortcutBehavior`)
- [ ] Consider using `Bool.toggle()` instead of `bool = !bool` (maybe custom SwiftLint rule?)
- [ ] Replace usages of `guard strongSelf = self else { return }` in favour of `guard self = self else { return }`

**Comment by jhreis** [comment]
We should currently keep browser-ios and brave-ios on as similar an infrastructure setup as possible. browser-ios is currently being upgraded to Xcode 10 + Swift 4.0, we should follow that first, and consider upgrading both simultaneously.
