### ISSUE TITLE
HTTPS vs Data Saved

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2859]
### Description: 
Like Android and Desktop, please replace HTTPS with Data Saved on the NTP
 
Text to be

**Est Data Saved**

**Comment by iccub** [comment]
Related internal ticket
https://github.com/brave/internal/issues/740

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.23(21.2.10.18)
- Verified test plan from #2931
- Verified Est. Data Saved is translated as well 

iPhone 7+ (iOS 14.4) | iPhone XR (iOS 13.5) | iPad Pro (iOS 12.4.1)
-- | -- | --
<img width=1000 src=https://user-images.githubusercontent.com/17010094/107613383-1b7fd000-6c40-11eb-9545-9c5737a431f8.png> | ![image](https://user-images.githubusercontent.com/17010094/107613443-3d795280-6c40-11eb-82f3-b0958aa7f718.png) | ![image](https://user-images.githubusercontent.com/17010094/107613407-2b97af80-6c40-11eb-9d85-d78087a5e15c.png)
