### ISSUE TITLE
Testflight iOS beta ending in 5 days

### ISSUE THREAD

**Issue by gh0sti** [brave/brave-ios#2860]
Brave browser beta in testflight ends in 5 days. You can update it to the 1.19.2 release to give it another 90 days till apple releases ios 14 and gives entitlement for default browser access.

**Comment by iccub** [comment]
There will be no default browser on the beta channel, maybe later after we ship it on release channel.

Reason is beta and release are two products, and each of them requires separate Apple process to get the entitlement, 
at the moment we want to focus to get it done on release channel first
