### ISSUE TITLE
Youtube Videos Don't Work: IOS

### ISSUE THREAD

**Issue by underling3311** [brave/brave-ios#2861]
I made a post 21 days and still hasn't been fixed yet. There is a videos for Proof of what is going on.

Also, Something New I found was the YouTube videos aren't in Library if you have the shield on. After watching the full video. If you disable the shield ads play and the video is seen in the Library of videos you watched.

https://community.brave.com/t/youtube-doesnt-work-on-brave/152645

**Comment by underling3311** [comment]
Some ADMIN said they will report this to fix this right away but NEVER happened. Second ADMIN saw this that post and didn't do anything as well.

**Comment by kylehickinson** [comment]
Hey @MrWaste, sorry about the delay, the bug you are describing is fixed and will available in the next release. We're trying to get it out ASAP!

Support likely found the original issue: https://github.com/brave/brave-ios/issues/2810 and didn't create a new one

**Comment by underling3311** [comment]
@kylehickinson 
I have another post for the Desktop version. Could you look into that because that needs to get fixed as well.
https://github.com/brave/brave-browser/issues/11586
