### ISSUE TITLE
Update user agents

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2864]
User agents are outdated, update them and make new UA for iOS 14

Test Plan
Now we use one user agent per iOS version, which means that iOS 13.1 and 13.6 has exactly the same UA.

user agents to check

any iOS 14 iPhone UA
```
Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) 
AppleWebKit/605.1.15 (KHTML, like Gecko) 
Version/14.0
Mobile/15E148 
Safari/604.1
```

any iOS 14 iPad UA
```
Mozilla/5.0 (iPad; CPU OS 14_0 like Mac OS X) 
AppleWebKit/605.1.15 (KHTML, like Gecko) 
Version/14.0
Mobile/15E148
Safari/604.1
``` 

any iOS 14 desktop UA
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) 
AppleWebKit/605.1.15 (KHTML, like Gecko) 
Version/14.0
Safari/605.1.15
```

any iOS 13 iPhone UA
```
Mozilla/5.0 (iPhone; CPU iPhone OS 13_6_1 like Mac OS X) 
AppleWebKit/605.1.15 (KHTML, like Gecko) 
Version/13.1.2 
Mobile/15E148 
Safari/604.1
```

any iOS 13 iPad UA
```
Mozilla/5.0 (iPad; CPU OS 13_6_1 like Mac OS X) 
AppleWebKit/605.1.15 (KHTML, like Gecko) 
Version/13.1.2
Mobile/15E148
Safari/604.1
``` 

any iOS 13 desktop UA
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) 
AppleWebKit/605.1.15 (KHTML, like Gecko) 
Version/13.1 
Safari/605.1.15
```

any iOS 12 iPhone UA
```
Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_1 like Mac OS X) 
AppleWebKit/605.1.15 (KHTML, like Gecko) 
Version/12.1.2 
Mobile/15E148 
Safari/604.1
```

any iOS 12 iPad UA
```
Mozilla/5.0 (iPad; CPU OS 12_4_1 like Mac OS X) 
AppleWebKit/605.1.15 (KHTML, like Gecko) 
Version/12.1.2
Mobile/15E148
Safari/604.1
``` 

any iOS 12 desktop UA
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) 
AppleWebKit/605.1.15 (KHTML, like Gecko) 
Version/12.1.2
Safari/605.1.15
```

**Comment by srirambv** [comment]
- Verification passed on the following devices as per the test plan described in the issue 

iPhone 7+(iOS 14) Mobile UA | iPhone 7+(iOS 14) Desktop UA 
-- | --
![image](https://user-images.githubusercontent.com/17010094/93055522-ff610e00-f662-11ea-9a60-93d94f3768d1.png) |![image](https://user-images.githubusercontent.com/17010094/93058177-e6f2f280-f666-11ea-81e7-98b4191a703b.png)

iPhone XR (iOS 13.6) Mobile UA | iPhone XR (iOS 13.6) Dekstop UA
-- | --
![image](https://user-images.githubusercontent.com/17010094/93056445-54e9ea80-f664-11ea-997a-c50920590054.png) | ![image](https://user-images.githubusercontent.com/17010094/93057734-4b618200-f666-11ea-8a92-837b7ece2f9a.png)


iPhone 6 (iOS 12.4.7) Mobile UA | iPhone 6 (iOS 12.4.7) Desktop UA
-- | --
![image](https://user-images.githubusercontent.com/17010094/93056378-413e8400-f664-11ea-9d04-ea3a98ed33c2.png) | ![image](https://user-images.githubusercontent.com/17010094/93058292-199ceb00-f667-11ea-8fc4-8e66e76283b6.png)

 iPad Pro (iOS 12.4.1) iPad UA | iPad Pro (iOS 12.4.1) Desktop UA 
-- | --
![image](https://user-images.githubusercontent.com/17010094/93058520-697bb200-f667-11ea-8e23-02abd4e1295c.png)| ![image](https://user-images.githubusercontent.com/17010094/93058482-5bc62c80-f667-11ea-8d4c-01ffb3203fc6.png)

iPad Pro (iOS 13.6) iPad UA | iPad Pro (iOS 13.6) Desktop UA  
-- | -- 
![image](https://user-images.githubusercontent.com/17010094/93057863-79df5d00-f666-11ea-80f3-e53e9a890676.png) | ![image](https://user-images.githubusercontent.com/17010094/93057827-6c29d780-f666-11ea-9375-64384927cdd2.png)
