### ISSUE TITLE
XCode 12/iOS 14 support

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2866]
Make the app to work with XCode 12/iOS 14

**Comment by kjozwiak** [comment]
Going to leave the `QA/Yes` label so we don't let this slip but this will get verified once the manual passes are done. Specifically the following areas as per https://github.com/brave/brave-ios/pull/2758:

* Check if 'save logins' feature still works, for both new and upgraded users.
* Look for UI bugs and or animations issues, this is a common thing to break when upgrading iOS versions

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.1 running 1.21(20.10.27.20)
- Verified save login feature works as expected and auto populates 
- Verified no UI bugs or animation issues 
---------------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.27.20)
- Verified save login feature works as expected and auto populates 
- Verified no UI bugs or animation issues 
---------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.10.27.20)
- Verified save login feature works as expected and auto populates 
- Verified no UI bugs or animation issues
