### ISSUE TITLE
YouTube picture in picture and background playback. ios 14

### ISSUE THREAD

**Issue by Xanthorrhoea** [brave/brave-ios#2894]
## Problem Description 
ios browser currently pauses the video and goes out of full screen when PiP is enabled on the ios full-screen video playback.
## Feature Overview 
Picture in picture allows brave users to close brave while still listening to a longer video, music or a podcast that is hosted on youtube or other video sites. this would help me provide auto tips to content creators who create longer content. 

## Implementation Details 
allow proper function of PiP

##User Experience 

   1. load youtube video
   2. enter fullscreen
   3. tap PiP icon to initiate Picture in picture mode for the video. 
   4. enjoy not having to have the brave app open

### Additional information

goes hand in hand with background video playback which I don't know if youtube allows for non-premium users. 
PiP is also a premium feature of the youtube app. along with zero ads which brave does pretty well. 

*Update 
PiP works fine when viewing videos on twitter and even works with embedded youtube videos. but still not on the main youtube website.

**Comment by srirambv** [comment]
I think the PiP is for just to browse through YT and not come out of browser. 

cc: @iccub

**Comment by Xanthorrhoea** [comment]
I have a reliable workaround for anyone interested. 

In the current build of brave, you can get PiP working every time by simply using the request desktop site feature. 

To find this setting
1 click chare on a youtube video
2. scroll down to the request desktop site button (denoted by a desktop monitor symbol)
3. the page will reload the full site and after clicking on the video it will play as normal in the native ios video player.
4. click the PiP button and voila you have PiP working and only takes a few clicks. 

You can also play while the phone is locked but the video does pause when you turn off the screen.

I hope this helps current brave ios users and the amazing dev team.

**Comment by iccub** [comment]
It's Google blocking PiP for mobile user agents, using desktop user agent is one workaround,
we want to add new feature called 'Playlist' soon which will allow you to watch all kind of videos in PiP mode,

I am going to close this for now
