### ISSUE TITLE
Browser crash when visiting Twitch 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2899]
### Description: 
Reported on https://community.brave.com/t/brave-on-ipad-crashes-with-twitch-tv/165343 and also reproduced the crash on iOS 14 while visiting a twitch profile 

### Steps to Reproduce 
  1. Upgrade to iOS 14 
  2. Visit twitch.tv and load a video, hope it crashes
  3. If not try opening a twitch profile will definitely crash

**Actual result:** 
Browser crash 

**Expected result:**
Don't crash just stream

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.19.2

**Device details:** 
iPhone 7+ (iOS 14 public release)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

**Comment by kylehickinson** [comment]
Adding this to 1.21 milestone but if 1.20 doesn't get through we may want to uplift it and release with 1.20

**Comment by kjozwiak** [comment]
* `iPhone 11` running `iOS 14.0.1` using `1.21 (20.09.30.20)` - **PASSED**
* `iPad Air (3rd Gen)` running `iOS 14.0.1` using `1.21 (20.09.30.20)` - **PASSED**

Went through the following cases:

* verified that playing several Twitch streams didn't cause Brave to crash (full screen included)
* verified that playing streams via `picture in picture` didn't cause Brave to crash
* verified that visiting several profiles didn't cause Brave to crash

------------

Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.06.20)
- Verified no crash when viewing twitch streams 
- Verified no crash when in PiP mode
-------
Verification passed on iPad Pro with iOS 14.0.1 running 1.21(20.10.06.20)
- Verified no crash when viewing twitch streams 
- Verified no crash when in PiP mode
-------

**Comment by ao38572** [comment]
Hello, this ticket was created in reference to the issue I was having. I see it has now been closed as it appears to be fixed. I still have the issue. I’m posting a link to a screen recording of my iPad Pro 2018 (3rd Generation) running iOS14.0.1. 
https://streamable.com/o1hi2f

**Comment by ao38572** [comment]
@srirambv @kjozwiak @kylehickinson 
Tagging to bump my previous comment, apologies if this is the wrong way to get attention for the issue.

**Comment by kylehickinson** [comment]
Hi @ao38572, this issue has been fixed but it's not in the current App Store version (1.20) so it makes sense you'd still be seeing this issue, the fix is scheduled for the upcoming release (1.21) 🙂

**Comment by ao38572** [comment]
@kylehickinson Ahhh okay, thanks so much for the quick response! I greatly appreciate all of the teams help.
