### ISSUE TITLE
[hackerone] #991713 - Reader view injection

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#2904]
https://hackerone.com/bugs?report_id=991713

**Comment by kjozwiak** [comment]
Verification **PASSED** via https://github.com/brave/security/issues/230#issuecomment-704688059. Created https://github.com/brave/brave-ios/issues/2939

Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.06.20) via https://github.com/brave/security/issues/230#issuecomment-704891074
