### ISSUE TITLE
[BUG] YouTube Watch History is Unable to know what your Watching

### ISSUE THREAD

**Issue by underling3311** [brave/brave-ios#2906]
### Description: 
Yotube Watch History is Unable to know what your Watching, not in your history.

### Steps to Reproduce 
  1. Watch the YouTube Video: Here's the Problem https://youtu.be/vAinjcoYv7A
  2. Open Brave go and watch a video on YouTube.

**Actual result:** 
Less then 15 mins video won't show you watched the video in your history. 

**Expected result:**
If you watch a video it doesn't know where your at in the video after finishing it. It still thinks it at the 5 min Mark, always at the 5 mins mark if its seen in your history.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Every Time, try it..

**Brave Version:** 
Lastest Update Version 1.20
Updated Last Night 9-25-2020

**Device details:** 
Iphone XR

**Website problems only:**
- did you check with Brave Shields down? Yes and works fine but you see all the ads from YouTube..
- did you check in Safari/Firefox (WkWebView-based browsers)? Yes and they don't have a problem, its brave's problem.

### Additional Information
Watch the YouTube Video: Here's the Problem https://youtu.be/vAinjcoYv7A

**Comment by underling3311** [comment]
https://youtu.be/vAinjcoYv7A
Watch until the End it, still doesn't show up after watching a full short video.

**Comment by underling3311** [comment]
Message me when this gets fixed, Thank You

**Comment by underling3311** [comment]
So?

**Comment by bsclifton** [comment]
@MrWaste you can subscribe for updates and you'll get notifications when we're able to grab this or triage
![image](https://user-images.githubusercontent.com/4733304/96961797-404a0f00-14ba-11eb-8a8d-8cab7ec686bb.png)

**Comment by underling3311** [comment]
I have already subscribed for updates. @bsclifton thank you for fixing this. Could you look into https://github.com/brave/brave-browser/issues/12113 I know you go back and forth with the different sections. This issue is more on the server side probably. Why would the server be blocking these types of addresses? Something isn't right, please check this out. Its important! 

Thank You
Mr. Waste
