### ISSUE TITLE
Selecting a single SE doesn't show up in quick search engine list

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2908]
### Description: 
Selecting a single SE doesn't show up in quick search engine list

### Steps to Reproduce 
  1. Set DDG as default SE
  2. Enable only google in quick search engine list
  3. Open tab and start typing, no quick search engine strip is shown above keyboard
  4. Enable a second SE, start typing in URL bar, quick search engine strip is shown

**Actual result:** 
Selecting a single SE doesn't show up in quick search engine list

**Expected result:**
Should show quick SE strip even if only one SE is enabled

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.20

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air (3rd Gen)` on `iOS 14.3` using the following build:

```
1.23 (21.1.28.17)
```

* ensured that both the default and selected `Quick-Search` SE are appearing via possible search options when `Show Search Suggestions` is disabled and ensured both are working as expected when selected

**`Suggestions Disabled`** | **`Suggestions Enabled`**
------------------------------|------------------------------
![IMG_0185](https://user-images.githubusercontent.com/2602313/106562953-13fe4f80-64f9-11eb-8e76-07a29749349e.png) | ![IMG_0187](https://user-images.githubusercontent.com/2602313/106562984-1cef2100-64f9-11eb-8f7e-432fceb0f038.png)
![IMG_0188](https://user-images.githubusercontent.com/2602313/106563002-24aec580-64f9-11eb-8b6a-b8c2cbe10f8c.png) | ![IMG_0186](https://user-images.githubusercontent.com/2602313/106563011-27a9b600-64f9-11eb-9107-80c139bd003c.png)

Verification **PASSED** on `iPad Mini 4` on `iOS 13.7` using the following build:

```
1.23 (21.1.28.17)
```

* ensured that both the default and selected `Quick-Search` SE are appearing via possible search options when `Show Search Suggestions` is disabled and ensured both are working as expected when selected

**`Suggestions Disabled`** | **`Suggestions Enabled`**
------------------------------|------------------------------
![IMG_0435](https://user-images.githubusercontent.com/2602313/106563489-d4843300-64f9-11eb-843e-871adc96d986.png) | ![IMG_0438](https://user-images.githubusercontent.com/2602313/106563503-dbab4100-64f9-11eb-93c0-960d3569341c.png)
![IMG_0436](https://user-images.githubusercontent.com/2602313/106563528-e5cd3f80-64f9-11eb-9be9-a4d2b242d686.png) | ![IMG_0437](https://user-images.githubusercontent.com/2602313/106563538-e9f95d00-64f9-11eb-82cd-95df835a1629.png)

Verification **PASSED** on `iPhone 11` on `iOS 14.4` using the following build:

```
1.23 (21.1.28.17)
```

* ensured that both the default and selected `Quick-Search` SE are appearing via possible search options when `Show Search Suggestions` is disabled and ensured both are working as expected when selected

**`Suggestions Disabled`** | **`Suggestions Enabled`**
------------------------------|------------------------------
![IMG_3523](https://user-images.githubusercontent.com/2602313/106564057-b0752180-64fa-11eb-99a0-727755534b77.png) | ![IMG_3525](https://user-images.githubusercontent.com/2602313/106564074-b79c2f80-64fa-11eb-9c04-d989e0b3333a.png)
![IMG_3524](https://user-images.githubusercontent.com/2602313/106564089-bec33d80-64fa-11eb-9284-9a71e42b1cf6.png) | ![IMG_3526](https://user-images.githubusercontent.com/2602313/106564101-c1259780-64fa-11eb-8747-d65dfb395665.png)

Verification **PASSED** on `iPhone 6+` on `iOS 12.4.1` using the following build:

```
1.23 (21.1.28.17)
```

* ensured that both the default and selected `Quick-Search` SE are appearing via possible search options when `Show Search Suggestions` is disabled and ensured both are working as expected when selected

**`Suggestions Disabled`** | **`Suggestions Enabled`**
------------------------------|------------------------------
![IMG_0094](https://user-images.githubusercontent.com/2602313/106564458-3db87600-64fb-11eb-9f20-982c438f6c0b.png) | ![IMG_0096](https://user-images.githubusercontent.com/2602313/106564469-427d2a00-64fb-11eb-91aa-d0873585d82d.png)
![IMG_0095](https://user-images.githubusercontent.com/2602313/106564488-47da7480-64fb-11eb-8d66-abe8d40081c2.png) | ![IMG_0097](https://user-images.githubusercontent.com/2602313/106564496-4a3cce80-64fb-11eb-95ba-f6ceb36d8c2b.png)
