### ISSUE TITLE
Licenses is missing 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2911]
### Description: 
Licenses is missing 

### Steps to Reproduce 
  1. Install 1.21(20.09.28.16)
  2. Open settings
  3. Open license, empty

**Actual result:** 
![license](https://user-images.githubusercontent.com/17010094/94561683-43a3ff00-025c-11eb-90cf-2cf23e785f40.gif)

**Expected result:**
![image](https://user-images.githubusercontent.com/17010094/94561855-82d25000-025c-11eb-9e16-7e1e379076b0.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.21(20.09.28.16)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

**Comment by kylehickinson** [comment]
@srirambv I can't reproduce this, but this bug could be the same bug as when you have multiple instances of Brave open that are using the same local web server port (causing the server to fail to start) which causes white NTP screen. Do you remember if your NTP was also not functioning when this was not working?

**Comment by srirambv** [comment]
@kylehickinson yes seems to be the case of multiple instances of Brave running. I see license details if I have only one instance running. 

Re NTP: Yes I did have multiple versions running at the same time which had caused the issue.

Closing the issue as invalid and not a problem when you have only one instance of Brave running
