### ISSUE TITLE
Fix Error URL Loading Side-Effects

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#2913]
### Description: 
- Error URLs use the `url` query parameter which can cause issues if other URLs have this parameter as they aren't validated against local host.

### Steps to Reproduce 
  1. https://github.com/brave/security/issues/231

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.0.1 running 1.21(20.10.06.20)
- Issue reproduced on 1.20 Appstore build
- Verified upgrading to 1.21 doesn't repro the issue 
---------------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.06.20)
- Issue reproduced on 1.20 Appstore build
- Verified upgrading to 1.21 doesn't repro the issue 
---------------
Verification passed on iPad Pro with iOS 14.0.1 running 1.21(20.10.06.20)
- Issue reproduced on 1.20 Appstore build
- Verified upgrading to 1.21 doesn't repro the issue 
---------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.10.06.20)
- Issue reproduced on 1.20 Appstore build
- Verified upgrading to 1.21 doesn't repro the issue
