### ISSUE TITLE
[hackerone] #993670 - Cross Origin FIDO

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#2921]
https://hackerone.com/bugs?report_id=993670

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.1 running 1.21(20.10.30.21)
- Verification notes found [here](https://github.com/brave/security/issues/239#issuecomment-720390673)
------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.30.21)
- Verification notes found [here](https://github.com/brave/security/issues/239#issuecomment-720390795)
-----
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.10.30.21)
- Verification notes found [here](https://github.com/brave/security/issues/239#issuecomment-720391623)
