### ISSUE TITLE
VPN Row missing from settings

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2922]
### Steps to Reproduce 
  1. Go to settings
  2. No vpn settings row is present

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
- Verification passed on the following devices running 1.21(20.10.2.20)

iPhone 7+ with iOS 14.0.1 | iPhone XR with iOS 13.5  |  iPad Pro with iOS 14.0.1 | iPad Pro with iOS 12.4.1 
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/95053569-86485a00-06e8-11eb-808e-13a97f4fc913.png) | ![image](https://user-images.githubusercontent.com/17010094/95053555-80eb0f80-06e8-11eb-9330-e40f2cbaf9df.png) | ![image](https://user-images.githubusercontent.com/17010094/95053530-7761a780-06e8-11eb-9054-b9f2ad77fa8a.png) | ![image](https://user-images.githubusercontent.com/17010094/95053543-7c265b80-06e8-11eb-90e3-ec7d2cc40b89.png)
