### ISSUE TITLE
Cancel button is not hidden completely 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2925]
### Description: 
Cancel button is not hidden completely. Reported by @bsclifton  as well 

### Steps to Reproduce 
 No proper steps to reproduce happens out of the blue 

**Actual result:** 

Page | NTP
-- | --
![image](https://user-images.githubusercontent.com/17010094/94928650-eb6b3800-04bb-11eb-83a8-18e8b2d09911.png) | ![image](https://user-images.githubusercontent.com/17010094/94928642-e6a68400-04bb-11eb-93c2-603d183da171.png)

**Expected result:**
Should hide the button completely when URL is not highlighted

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent 

**Brave Version:** 
Not sure when it started but have seen this in the past on older builds as well

**Device details:** 
iPhone

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

**Comment by iccub** [comment]
happened to me few times too, no easy way to reproduce

**Comment by kylehickinson** [comment]
I happened to reproduce and fix this in the theme PR, so going to move this back to 1.26

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(21.5.19.19)
- Verified steps from issue description
--------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.26(21.5.19.19)
- Verified steps from issue description
--------
Verification passed on iPad Pro with iOS 14.5.1 running 1.26(21.5.19.19)
- Verified steps from issue description
