### ISSUE TITLE
Login to nytimes.com shows the WebAuthn login modal

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#2928]
### Description: 

Investigate why WebAuthn modal is showing up on the nytimes login page. 

### Steps to Reproduce 
  1. Navigate to nytimes.com
  2. Click on login

**Actual result:** 
WebAuthn modal is displayed

**Expected result:**
Should not be displayed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Comment by iccub** [comment]
Seems to work now
