### ISSUE TITLE
Update copy in settings & shield stats

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2932]
| old | new | where |
| --- | --- | --- |
| Block Ads & Tracking | Block cross-site trackers | Settings, Shields (Advanced) |
| HTTPS Everywhere | Upgrade connections to HTTPS | Settings, Shields (Advanced) |
| Ads & Trackers blocked | Trackers & ads blocked | NTP Stats | 
| Fingerprinting Protection | Block fingerprinting | Shields (Advanced) |

**Comment by karenkliu** [comment]
Should be this:

| old | new | where |
| --- | --- | --- |
| Block Ads & Tracking | Block cross-site trackers | Settings, Shields (Advanced) |
| HTTPS Everywhere | Upgrade connections to HTTPS | Settings, Shields (Advanced) |
| Ads & Trackers blocked | Trackers & Ads blocked | NTP Stats | 
| Fingerprinting Protection | Block fingerprinting | Shields (Advanced) |
| HTTPS Upgrades | Data Saved | NTP Stats |

**Comment by kylehickinson** [comment]
@karenkliu We will not be updating HTTPS Upgrades → Data Saved in this version, that is being tracked separately here: https://github.com/brave/brave-ios/issues/2859

I've updated the rest to match

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.1 running 1.21(20.10.23.15)
- Verified text changes are updated as expected

Shields | Global Shields settings | NTP
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/97307514-b43c3c80-1857-11eb-84a4-73e3f642c413.png) | ![image](https://user-images.githubusercontent.com/17010094/97307523-b8685a00-1857-11eb-9b97-a72c3584db3d.png) | ![image](https://user-images.githubusercontent.com/17010094/97307545-bf8f6800-1857-11eb-96d6-fb6e886d23a4.png)

-------------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.23.15)
- Verified text changes are updated as expected

Shields | Global Shields settings | NTP
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/97307891-2a40a380-1858-11eb-82b1-6ec23543ae84.png) | ![image](https://user-images.githubusercontent.com/17010094/97307913-2f9dee00-1858-11eb-91cd-1d12c7447c19.png) | ![image](https://user-images.githubusercontent.com/17010094/97307942-375d9280-1858-11eb-984c-de6772a5a246.png)


-------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.10.23.15)
- Verified text changes are updated as expected

Shields | Global Shields settings | NTP
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/97307978-417f9100-1858-11eb-9a36-074570a97cfa.png) | ![image](https://user-images.githubusercontent.com/17010094/97307989-45abae80-1858-11eb-8b3c-1434ed4fda98.png) | ![image](https://user-images.githubusercontent.com/17010094/97308017-4a706280-1858-11eb-8b97-ebbe2472d530.png)
