### ISSUE TITLE
Update Brave VPN intro card text + graphic

### ISSUE THREAD

**Issue by karenkliu** [brave/brave-ios#2933]
## Description
Update the promotional copy for VPN so it mentions trying for free and makes it clearer what the additional protections are.

Original thread for this issue:
> It seems strange to introduce the VPN with this `Protect your connection and block ads and trackers across your whole device.`
> Our new mobile onboarding makes it pretty clear that Brave blocks trackers and ads. So why would someone need a VPN that also block trackers and ads?? 

Also:
>...discussing why we aren't necessarily seeing a lot of users testing out the VPN. He brought up the point that maybe it's worth mentioning the free trial in some of the copy? You only find out about the free trial when you select a plan option.

### Steps to Reproduce 
  1. Go to settings
  2. See the intro card

**Actual result:** 
![image](https://user-images.githubusercontent.com/2388823/95141812-fc6bb180-0726-11eb-8ad7-3eaab985c924.png)

## Designs
New copy: `Upgrade to a VPN to protect your connection and block invasive trackers everywhere.`

Replace the background graphic as well; last release we missed incorrect grey icon colors in the background graphic.

![image](https://user-images.githubusercontent.com/2388823/97042095-61941500-1525-11eb-849b-0b73df29e019.png)

## Assets
Figma: https://www.figma.com/file/PqLTp3DnANLQMM1XzaChqZ/iOS-VPN?node-id=0%3A199

**Comment by anthonypkeane** [comment]
Please change the "Learn More" text to "Try for Free"

**Comment by karenkliu** [comment]
Copy updated!

**Comment by kjozwiak** [comment]
@karenkliu going to go off the following design as per https://github.com/brave/brave-ios/issues/2933#issue-715228966:

![image](https://user-images.githubusercontent.com/2602313/106692811-3056c680-65a3-11eb-875d-5d06f61b3509.png)

However, we'll need to update Figma as it's still displaying/using the old design.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air (3rd Gen)` on `iOS 14.3` using the following build:

```
1.23 (21.1.28.17)
```

* ensured that the modal doesn't dismiss when closing settings or restarting the browser if the `X` wasn't selected
* ensured that tapping on `X` correctly closes the modal and doesn't re-appear when re-opening `Settings`
* ensured that selecting `Try for FREE` correctly opened `Brave VPN` subscription screen

**`Example`** | **`Example`**
---------------|-----------------
![IMG_0444](https://user-images.githubusercontent.com/2602313/106695062-d4427100-65a7-11eb-95f5-91d75c4a2d29.png) | ![IMG_0445](https://user-images.githubusercontent.com/2602313/106695069-da385200-65a7-11eb-9a5a-d885cd699db9.png)

Verification **PASSED** on `iPad Mini 4` on `iOS 13.7` using the following build:

```
1.23 (21.1.28.17)
```

* ensured that the modal doesn't dismiss when closing settings or restarting the browser if the `X` wasn't selected
* ensured that tapping on `X` correctly closes the modal and doesn't re-appear when re-opening `Settings`
* ensured that selecting `Try for FREE` correctly opened `Brave VPN` subscription screen

**`Example`** | **`Example`**
---------------|-----------------
![IMG_0444](https://user-images.githubusercontent.com/2602313/106694240-24203880-65a6-11eb-8d75-752b3785f928.png) | ![IMG_0445](https://user-images.githubusercontent.com/2602313/106694248-284c5600-65a6-11eb-9101-c1a19336a09d.png)

Verification **PASSED** on `iPhone 11` on `iOS 14.4` using the following build:

```
1.23 (21.1.28.17)
```

* ensured that the modal doesn't dismiss when closing settings or restarting the browser if the `X` wasn't selected
* ensured that tapping on `X` correctly closes the modal and doesn't re-appear when re-opening `Settings`
* ensured that selecting `Try for FREE` correctly opened `Brave VPN` subscription screen

**`Example`** | **`Example`**
---------------|-----------------
![IMG_3533](https://user-images.githubusercontent.com/2602313/106693779-27ff8b00-65a5-11eb-8471-068f9e61cf1c.png) | ![IMG_3532](https://user-images.githubusercontent.com/2602313/106693789-2cc43f00-65a5-11eb-8e5f-b187ada9747a.png)

Verification **PASSED** on `iPhone 6+` on `iOS 12.4.1` using the following build:

```
1.23 (21.1.28.17)
```

* ensured that the modal doesn't dismiss when closing settings or restarting the browser if the `X` wasn't selected
* ensured that tapping on `X` correctly closes the modal and doesn't re-appear when re-opening `Settings`
* ensured that selecting `Try for FREE` correctly opened `Brave VPN` subscription screen

**`Example`** | **`Example`**
---------------|-----------------
![IMG_0100](https://user-images.githubusercontent.com/2602313/106695306-4dda5f00-65a8-11eb-9f9b-ffef4481c833.png) | ![IMG_0101](https://user-images.githubusercontent.com/2602313/106695315-516de600-65a8-11eb-93e6-6e4571071f7d.png)

**Comment by karenkliu** [comment]
@kjozwiak Okay thanks for the heads up; Figma updated.
