### ISSUE TITLE
Allow Brave Firewall + VPN users to select server location.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2934]

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 14.4` using the following build:

```
1.24 (21.3.29.21)
```

Basically went through the STR/Cases outlined via https://github.com/brave/brave-ios/pull/3333 as a guide.

* ensured that `Automatic` under `Server Region` is set as the default when first installing/subscribing to Brave VPN
* ensured that the correct location is automatically selected when upgrading from `1.23.1 (21.2.24.16)` -> `1.24 (21.3.29.21)`
* ensured that the `host` & `Location` are relatively close to your current location when `Automatic` is selected
* ensured that disabling/enabling the VPN still retains the same region that was selected
* ensured that `Reset Configuration` correctly changes the `host` but keeps the same selected `location`

<details>
<summary>Example of "Reset Configuration"</summary>

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|----------------|-----------------|-----------------
![IMG_3646](https://user-images.githubusercontent.com/2602313/113044619-df5eeb00-916b-11eb-861b-3ace15034474.png) | ![IMG_3647](https://user-images.githubusercontent.com/2602313/113044630-e1c14500-916b-11eb-87be-5a33e7f40c0a.png) | ![IMG_3649](https://user-images.githubusercontent.com/2602313/113044644-e5ed6280-916b-11eb-80f6-9e3f50c5d7e5.png) | ![IMG_3648](https://user-images.githubusercontent.com/2602313/113044657-e980e980-916b-11eb-9ace-2e0d2e4f17d9.png)
</details>

* ensured that switching region correctly selects the correct `Host` & `Location`
* ensured that the IP address is in the correct region when switching `Location` endpoints

<details>
<summary>Changing Regions/Locations </summary>

**`AU Example`** | **`AU Example`** | **`AU Example`** 
---------------|----------------|-----------------
![IMG_3641](https://user-images.githubusercontent.com/2602313/113046663-51383400-916e-11eb-9566-d430391c0665.png) | ![IMG_3640](https://user-images.githubusercontent.com/2602313/113046688-56957e80-916e-11eb-8a71-fb871b685c28.png) | ![IMG_3642](https://user-images.githubusercontent.com/2602313/113046708-5e552300-916e-11eb-98cb-94abe504e38a.png)

**`Singapore Example`** | **`Singapore Example`** | **`Singapore Example`** 
---------------|----------------|-----------------
![IMG_3644](https://user-images.githubusercontent.com/2602313/113047122-e804f080-916e-11eb-9020-d8df158c779d.png) | ![IMG_3643](https://user-images.githubusercontent.com/2602313/113047147-f226ef00-916e-11eb-8614-60e82ea2f74c.png) | ![IMG_3645](https://user-images.githubusercontent.com/2602313/113047165-f9e69380-916e-11eb-9f66-06e0c01088f6.png)
</details>

* ensured that switching back to `Automatic` after changing the location several times correctly picks the closest location/server
* ensured that `VPN Support` opens https://support.brave.com/hc/en-us/articles/360045045952

---------------------

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using the following build:

```
1.24 (21.3.29.21)
```

Basically went through the STR/Cases outlined via https://github.com/brave/brave-ios/pull/3333 as a guide.

* ensured that `Automatic` under `Server Region` is set as the default when first installing/subscribing to Brave VPN
* ensured that the correct location is automatically selected when upgrading from `1.23.1 (21.2.24.16)` -> `1.24 (21.3.29.21)`
* ensured that the `host` & `Location` are relatively close to your current location when `Automatic` is selected
* ensured that disabling/enabling the VPN still retains the same region that was selected
* ensured that `Reset Configuration` correctly changes the `host` but keeps the same selected `location`

<details>
<summary>Example of "Reset Configuration"</summary>

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|----------------|-----------------|-----------------
![IMG_0170](https://user-images.githubusercontent.com/2602313/113085631-35548280-91ae-11eb-9437-5906cd256548.png) | ![IMG_0169](https://user-images.githubusercontent.com/2602313/113085644-384f7300-91ae-11eb-910b-74fd76268083.png) | ![IMG_0168](https://user-images.githubusercontent.com/2602313/113085655-3d142700-91ae-11eb-807c-a3fcd6819a92.png) | ![IMG_0167](https://user-images.githubusercontent.com/2602313/113085667-41d8db00-91ae-11eb-8062-7b62d7a77a7f.png)
</details>

* ensured that switching region correctly selects the correct `Host` & `Location`
* ensured that the IP address is in the correct region when switching `Location` endpoints

<details>
<summary>Changing Regions/Locations </summary>

**`UK Example`** | **`UK Example`** | **`UK Example`** 
---------------|----------------|-----------------
![IMG_0174](https://user-images.githubusercontent.com/2602313/113085764-72b91000-91ae-11eb-9aff-c77be6032c9f.png) | ![IMG_0175](https://user-images.githubusercontent.com/2602313/113085791-7fd5ff00-91ae-11eb-95b9-11e55eb6ca34.png) | ![IMG_0177](https://user-images.githubusercontent.com/2602313/113085823-8f554800-91ae-11eb-9a0f-2ebbd3361b39.png)

**`Netherlands Example`** | **`Netherlands Example`** | **`Netherlands Example`** 
---------------|----------------|-----------------
![IMG_0171](https://user-images.githubusercontent.com/2602313/113085898-ac8a1680-91ae-11eb-81c4-4f9a9791915c.png) | ![IMG_0172](https://user-images.githubusercontent.com/2602313/113085915-b01d9d80-91ae-11eb-87ca-ad706095c472.png) | ![IMG_0173](https://user-images.githubusercontent.com/2602313/113085935-b6137e80-91ae-11eb-9616-84beebbc24b4.png)
</details>

* ensured that switching back to `Automatic` after changing the location several times correctly picks the closest location/server
* ensured that `VPN Support` opens https://support.brave.com/hc/en-us/articles/360045045952

--------------

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using the following build:

```
1.24 (21.3.29.21)
```

Basically went through the STR/Cases outlined via https://github.com/brave/brave-ios/pull/3333 as a guide.

* ensured that `Automatic` under `Server Region` is set as the default when first installing/subscribing to Brave VPN
* ensured that the correct location is automatically selected when upgrading from `1.23.1 (21.2.24.16)` -> `1.24 (21.3.29.21)`
* ensured that the `host` & `Location` are relatively close to your current location when `Automatic` is selected
* ensured that disabling/enabling the VPN still retains the same region that was selected
* ensured that `Reset Configuration` correctly changes the `host` but keeps the same selected `location`

<details>
<summary>Example of "Reset Configuration"</summary>

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|----------------|-----------------|-----------------
![IMG_0497](https://user-images.githubusercontent.com/2602313/113088416-887d0400-91b3-11eb-99a7-dcfd3686a761.png) | ![IMG_0498](https://user-images.githubusercontent.com/2602313/113088423-8adf5e00-91b3-11eb-8279-000edd691134.png) | ![IMG_0499](https://user-images.githubusercontent.com/2602313/113088432-8f0b7b80-91b3-11eb-8396-e17d0654d3ba.png) | ![IMG_0500](https://user-images.githubusercontent.com/2602313/113088443-93379900-91b3-11eb-9e39-33ffc5e81ff6.png)
</details>

* ensured that switching region correctly selects the correct `Host` & `Location`
* ensured that the IP address is in the correct region when switching `Location` endpoints

<details>
<summary>Changing Regions/Locations </summary>

**`Canada Example`** | **`Canada Example`** | **`Canada Example`** 
---------------|----------------|-----------------
![IMG_0504](https://user-images.githubusercontent.com/2602313/113088856-7cde0d00-91b4-11eb-940a-b8562e6cf161.png) | ![IMG_0505](https://user-images.githubusercontent.com/2602313/113088866-81a2c100-91b4-11eb-9b58-5d9c53dc681c.png) | ![IMG_0506](https://user-images.githubusercontent.com/2602313/113088878-85cede80-91b4-11eb-85ba-81bb86c9b1c3.png)

**`Japan Example`** | **`Japan Example`** | **`Japan Example`** 
---------------|----------------|-----------------
![IMG_0501](https://user-images.githubusercontent.com/2602313/113088536-caa64580-91b3-11eb-93b2-9b6eb5a8025a.png) | ![IMG_0502](https://user-images.githubusercontent.com/2602313/113088544-ced26300-91b3-11eb-942e-af349a9f1e56.png) | ![IMG_0503](https://user-images.githubusercontent.com/2602313/113088551-d42fad80-91b3-11eb-961c-d6a80c6fefec.png)
</details>

* ensured that switching back to `Automatic` after changing the location several times correctly picks the closest location/server
* ensured that `VPN Support` opens https://support.brave.com/hc/en-us/articles/360045045952
