### ISSUE TITLE
[Follow up to #1279] Disable shields doesn't load page 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2935]
### Description: 
[Follow up to #1279] Disable shields doesn't load page 

### Steps to Reproduce 
  1. Install 1.21(20.10.2.20)
  2. Enable all switches except cookies under shields settings
  3. Visit `https://slashdot.org`, ensure page doesn't load as expected
  4. Disable shields, page reloads but doesn't load content
  5. Manually refresh the page again, page content loads

**Actual result:** 
![shields-ios](https://user-images.githubusercontent.com/17010094/95199423-b2d9a000-07d4-11eb-8b81-c6bc06234a25.gif)

**Expected result:**
Should load page content automatically when page is reloaded when shields are turned off 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.21(20.10.2.20)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? Yes doesn't load page
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by kylehickinson** [comment]
Ref #2822

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.0.1 running 1.21(20.10.08.12)
- Verified disable shields loads the page correctly 
----------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.08.12)
- Verified disable shields loads the page correctly 
----------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.10.08.12)
- Verified disable shields loads the page correctly on both desktop/mobile page
