### ISSUE TITLE
brave crashing when claiming UGP grant (staging)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2937]
### Description: 

Whenever you attempt to claim `UGP` grant via the staging, Brave will instantly crash. Might be a iOS 14 issue as I couldn't reproduce the crash on `iOS 13.7` & `iOS 12.4.1`. However, as per @srirambv, I can't claim the UGP on `iOS 13.7` & `iOS 12.4.1`. Looks like the crash only occurs on `iOS 14`.

### Steps to Reproduce

  1. install `1.21 (20.10.06.16)` via TF (Dev build)
  2. once installed, launched and run through onboarding (Default SE & Shields)
  3. go into `Settings` -> `View Rewards Debug Menu` and switch to `Staging` (tap on `Exit Now`)
  4. re-launch `1.21 (20.10.06.16)`
  5. enable rewards via `Settings` -> `Brave Rewards` and disable `Hide Brave Rewards Icon`
  6. enable rewards via the rewards icon and attempt the claim the `UGP` on staging

**Actual result:** 

* Example of the instant crash: https://youtu.be/rM7dTPdlNlw

**Expected result:**

Brave shouldn't be crashing when claiming `UGP` grants

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.21 (20.10.06.16)` via TF (Dev build)

**Device details:** 

* `iPhone 11` running `iOS 14.01` - *Reproduced*
* `iPad Air (3rd Gen)` running `iOS 14.01` - *Reproduced*
* `iPad Mini 4` running `iOS 13.7` - *Couldn't Reproduce* (However, can't claim grant)
* `iPhone 6s+` running `iOS 12.4.1` - *Couldn't Reproduce* (However, can't claim grant)

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @iccub @kylehickinson @anthonypkeane @srirambv

**Comment by kjozwiak** [comment]
@kylehickinson assuming we can close this now that it landed in `1.15.x` via https://github.com/brave/brave-core/pull/6794?

**Comment by kylehickinson** [comment]
I will close it with a PR that bumps rewards build with new changes in 1.15.x

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.21(20.10.09.13)
- Verified able to claim grant without crash

iPhone 7+(iOS 14.0.1) | iPhone XR (iOS 13.5) | iPad Pro (iOS 12.4.1)
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/95726362-c1123b00-0c70-11eb-92e0-f45d8590489b.png) | ![image](https://user-images.githubusercontent.com/17010094/95726401-ce2f2a00-0c70-11eb-88f6-40592df21270.png) | ![image](https://user-images.githubusercontent.com/17010094/95726432-d71ffb80-0c70-11eb-8cd4-339d7fa26161.png)
