### ISSUE TITLE
VPN banner missing from "Settings"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2938]
### Description: 

VPN banner is currently missing from the `Settings` page for new users.

### Steps to Reproduce

  1. install `1.21 (20.10.06.16)` from TF
  2. go into the `Settings` page and you'll notice that the VPN banner is currently missing

**Actual result:** 

![536D1454-C5F9-40C1-86BC-B02B6C78F84B](https://user-images.githubusercontent.com/2602313/95248328-27b4d600-07e5-11eb-81a3-fbca6b3e56f8.PNG)

**Expected result:**

![90610481-C502-46AF-AFFB-6F971370E576](https://user-images.githubusercontent.com/2602313/95248342-2c798a00-07e5-11eb-956c-7c4df1665695.PNG)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.21 (20.10.06.16)`(reproduces on any `1.21` builds as `Settings` was reworked.

**Device details:** 

* Reproducible on all devices running `1.21`

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing

**Comment by iccub** [comment]
Works for me, please retest on prod channel

![IMG_0A310E68FE59-1](https://user-images.githubusercontent.com/6950387/95265418-74260300-0831-11eb-9059-255f611963f6.jpeg)

**Comment by kjozwiak** [comment]
As per the conversation on Slack, the banner/modals re: VPN are not appearing on `dev` due to not being able to fetch the prices, hence we don't load any of the banners. Verified that it's working on `1.21 (20.10.06.20)` using production:

![7996FD0C-368C-49C4-97CE-CD5AAD89CE7E](https://user-images.githubusercontent.com/2602313/95274005-a2e0b100-0812-11eb-8aff-44d783911944.PNG)
