### ISSUE TITLE
reader mode breaks when loading certain URLs

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2939]
### Description: 

When loading certain URLs, `reader mode` end up breaking. You'll need to restart Brave to recover.

### Steps to Reproduce 

* STR can be found via https://github.com/brave/security/issues/230#issuecomment-704693192

**Actual result:** 

* Example: https://youtu.be/zFh4qnFKHIQ

**Expected result:**

`Reader Mode` should work as expected, even when loading certain URLs

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.21 (20.10.6.20)`

**Device details:** 

* `iPhone 11` running `iOS 14.0.1` - **Reproduced**
* `iPad Air (3rd Gen)` running `iOS 14.0.1` - **Reproduced**
* `iPad Mini 4` running `iOS 13.7` - **Reproduced**
* `iPhone 6s+` running `iOS 12.4.1` - **Reproduced**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @jumde @srirambv @aekeus @bsclifton

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.0.1 running 1.21(20.10.09.13)
- Verified test plan from https://github.com/brave/brave-ios/pull/2943
- Verified steps from https://github.com/brave/security/issues/230#issuecomment-704693192
- Verified reader mode works fine when switching between apps
- Verified reader mode works fine when quitting and restarting the app
------------------------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.09.13)
- Verified test plan from https://github.com/brave/brave-ios/pull/2943
- Verified steps from https://github.com/brave/security/issues/230#issuecomment-704693192
- Verified reader mode works fine when switching between apps
- Verified reader mode works fine when quitting and restarting the app
------------------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.10.09.13)
- Verified test plan from https://github.com/brave/brave-ios/pull/2943
- Verified steps from https://github.com/brave/security/issues/230#issuecomment-704693192
- Verified reader mode works fine when switching between apps
- Verified reader mode works fine when quitting and restarting the app
