### ISSUE TITLE
make the "X" more visible on the VPN modal under "Settings"

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#2940]
### Description: 

When using the light theme, the `X` on the `VPN` modal via `Settings` is hard to see and could be perceived as a dark pattern re: making it harder to see on purpose.

### Steps to Reproduce

  1. install `1.21 (20.10.6.20)` from TF (release channel) using the light theme
  2. go into `Settings`

**Actual result:** 

<img width="508" alt="Screen Shot 2020-10-06 at 8 31 02 PM" src="https://user-images.githubusercontent.com/2602313/95306227-20c5ac00-0855-11eb-96ce-2a717136faf8.png">

**Expected result:**

<img width="459" alt="Screen Shot 2020-10-06 at 8 33 39 PM" src="https://user-images.githubusercontent.com/2602313/95306243-24f1c980-0855-11eb-952c-dc67af60ff59.png">

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR mentioned above.

**Brave Version:** 

* `1.21 (20.10.6.20)`

**Device details:** 

* Reproducible on all devices using `light` theme.

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @jamesmudgett @aekeus @srirambv @bsclifton @iccub

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.21(20.10.08.12)

iPhone XR (iOS 13.5) Dark  | iPhone XR (iOS 13.5) Light 
-- | -- 
![image](https://user-images.githubusercontent.com/17010094/95585666-6cd04680-0a37-11eb-905c-9c4542355024.png) | ![image](https://user-images.githubusercontent.com/17010094/95585653-693cbf80-0a37-11eb-9c9c-59901b648eea.png)


 iPhone 7+ (iOS 14.0.1) Dark | iPhone 7+ (iOS 14.0.1) Light
-- | --
![image](https://user-images.githubusercontent.com/17010094/95585698-7b1e6280-0a37-11eb-8fd9-9c589dabb5ee.png) | ![image](https://user-images.githubusercontent.com/17010094/95585688-76f24500-0a37-11eb-8010-ad5e97a456f2.png)

iPad Pro (iOS 12.4.1) Dark | iPad Pro (iOS 12.4.1) Light
-- | --
![image](https://user-images.githubusercontent.com/17010094/95587209-ab670080-0a39-11eb-8ce5-27e719fbb4ef.png) | ![image](https://user-images.githubusercontent.com/17010094/95587178-9f7b3e80-0a39-11eb-874b-3e9324985c26.png)
