### ISSUE TITLE
Web server is not set up after backgrounding the app for few seconds

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2944]
### Steps to Reproduce 
  1. Launch the app
  2. Close it, move it to background
  3. Wait few seconds
  4. Open the app again
  5. Try to open a website in reader more, or open a non existing website like `asdasdas.asasa`

**Actual result:** 
Nothing happens

**Expected result:**
Should show reader mode or error page

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Caused by this https://github.com/brave/brave-ios/pull/2773

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.0.1 running 1.21(20.10.09.13)
- Verified steps from issue description
---------------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.09.13)
- Verified steps from issue description
---------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.10.09.13)
- Verified steps from issue description
