### ISSUE TITLE
Add Sync v2 support for bookmarks

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2946]
## Description
Add support for syncing bookmarks with desktop/android using new sync APIs

#### Import from CoreDB succeeds
 - Does table (or records) get deleted? How can we verify

#### Import from CoreDB fails
 - Does this retry? if so, how many times?
 - Failure screen should show - what should this look like?

### Test new profile

**Comment by bsclifton** [comment]
Work-in-progress PRs:
- `brave-core` 1.15.x - https://github.com/brave/brave-core/pull/6866
- `brave-core` 1.16.x - https://github.com/brave/brave-core/pull/7048
- `brave-core` master - https://github.com/brave/brave-core/pull/6722
