### ISSUE TITLE
[hackerone] #1004388 - Login Helper

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#2949]
https://hackerone.com/bugs?report_id=1004388

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.23.15)
- Verified test plan from https://github.com/brave/security/issues/237
-------------
Verification passed on iPhone 7+ with iOS 14.1 running 1.21(20.10.23.15)
- Verified test plan from https://github.com/brave/security/issues/237
-------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.10.23.15)
- Verified test plan from https://github.com/brave/security/issues/237
