### ISSUE TITLE
[upstream/firefox-ios][hackerone] #1634597 - about:blank spoofing

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#2952]
https://bugzilla.mozilla.org/show_bug.cgi?id=1634597

hackerone report: https://hackerone.com/reports/860867

**Comment by kjozwiak** [comment]
@jumde assuming we'll want to include this in the release notes as it fixed a security issue?

**Comment by jumde** [comment]
@kjozwiak - Updated 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** as per https://github.com/brave/security/issues/244#issuecomment-772099890 using the following build:

```
1.23 (21.1.28.17)
```

* `iPad Air (3rd Gen)` on `iOS 14.3` - **PASSED**
* `iPad Mini 4` on `iOS 13.7` - **PASSED**
* `iPhone 11` on `iOS 14.4` - **PASSED**
* `iPhone 6+` on `iOS 12.4.1` - **PASSED**
