### ISSUE TITLE
Unable to join Teams Meeting link in Brave/IOS

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-ios#2955]
### Description: 
Unable to join meeting link in Teams via Brave/IOS

### Steps to Reproduce 
  1. From Teams, send invite to an email address (this can be done via Desktop)
  2. Open email, and copy link into Brave
  3. Button to join meeting, doesn't work.

**Actual result:** 
https://streamable.com/xhgcjz

Link (may/maynot work):
`https://teams.microsoft.com/dl/launcher/launcher.html?url=%2F_%23%2Fl%2Fmeetup-join%2F19%3A29fe3a4374614791bfe0b3e74edaa876%40thread.skype%2F1602551536715%3Fcontext%3D%257b%2522Tid%2522%253a%2522e14e1473-6808-4288-83ac-8006a7fcfa6d%2522%252c%2522Oid%2522%253a%2522bc208d3f-9992-4ff1-8ac5-9701140daead%2522%257d%26anon%3Dtrue&type=meetup-join&deeplinkId=6ed5143f-6d82-4150-93ce-b00d89b9ee38&directDl=true&msLaunch=true&enableMobilePage=true&suppressPrompt=true`

**Expected result:**
Let user join meeting

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily, Shields not affecting it.

**Brave Version:** 
Tested in Brave Release (IOS) and Brave Beta (IOS)

**Device details:** 
iPhone 8Plus

**Website problems only:**
- did you check with Brave Shields down? Yes, doesn't work.
- did you check in Safari/Firefox (WkWebView-based browsers)?  Yes

### Additional Information
Was reported here:
https://old.reddit.com/r/brave_browser/comments/j945m3/cant_click_on_teams_invitation_link_on_brave_ios/

Seems the issue is launching the teams app from within Brave.  This is  what occurred in Firefox/IOS:
![teams-ff](https://user-images.githubusercontent.com/1659004/95806929-70c8d500-0d65-11eb-8a9a-8c2afd3e6bbc.png)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.23.15)
- Verified browser prompts before opening external apps
-------------
Verification passed on iPhone 7+ with iOS 14.1 running 1.21(20.10.23.15)
- Verified browser prompts before opening external apps
-------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.10.23.15)
- Verified browser prompts before opening external apps
