### ISSUE TITLE
Follow-up: brave-ios/2921

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#2957]
Tracking the exhaustive fix for #2921

## Test Plan

Specified here: https://github.com/brave/security/issues/267

**Comment by diracdeltas** [comment]
marking as P1 but it doesn't need to be done immediately. (can wait for 1.23 if needed, but shouldn't wait longer than that)

**Comment by iccub** [comment]
@jumde can this be closed?

**Comment by jumde** [comment]
@iccub - Needs rebase, I'm working on that today. Will share an update when it's ready to merge.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4 running 1.23.1(21.2.22.10)
- Verification notes can be found [here](https://github.com/brave/security/issues/267#issuecomment-781245303)

Verification passed on iPhone XR with iOS 13.5 running 1.23.1(21.2.22.10)
- Verification notes can be found [here](https://github.com/brave/security/issues/267#issuecomment-781245303)

Verification passed on iPad Pro with iOS 12.4.1 running 1.23.1(21.2.22.10)
- Verification notes can be found [here](https://github.com/brave/security/issues/267#issuecomment-781245303)
