### ISSUE TITLE
Brave Ads confirmations initialization fails

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2959]

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.1 running 1.21(20.10.27.20)
- Verified ads confirmations work as expected
------------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.27.20)
- Verified ads confirmations work as expected
------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.10.27.20)
- Verified ads confirmations work as expected
