### ISSUE TITLE
Problems with Sharing a PDF File

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2961]
### Description: 

While Sharing a PDF file in Brave browser, some of the applications have problems.

- Mail app: Instead of attaching the PDF file, the URL of the PDF file is copied as message.
- iBooks: A pop-up showing "Creating a PDF" is shown and nothing happens

### Steps to Reproduce 
  1. Open a PDF file in the browser
  2. Tap 'share'
  3. Share vie 'Books.app.

**Actual result:** 
Nothing happens

**Expected result:**
- Mail app: Should Attach the PDF to Template Email
- iBooks: Should save the PDF to Books

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
1.20

**Device details:** 
iOS 14, did not check previous versions

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Reported by @PrivacyMatters

**Comment by PrivacyMatters** [comment]
Yes. Checked with Shields down. Same issue.

Yes. Checked with Safari/Firefox. No issues.

**Comment by soner-yuksel** [comment]
Changed the description of the ticket and added extra information with regards to new findings.

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 11` running `iOS 14.4` using `1.23 (21.2.5.15)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.4` using `1.23 (21.2.5.15)`
* Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.23 (21.2.5.15)`
* Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.23 (21.2.5.15)`

STR/Cases used for each platform mentioned above:

* loaded https://bitcoin.org/bitcoin.pdf within the browser
* clicked on `Share with...` and selected `Books` and ensured the PDF was copied to Books
* clicked on `Share with...` and selected `Mail` and ensured the PDF was attached to the `New Message` template
* clicked on `Share with...` and selected `iMessage` and ensured the PDF was attached to the `New Message` template

Ran into https://github.com/brave/brave-ios/issues/3279 when running through the above.
