### ISSUE TITLE
[feature/webauthn] Touch key modal does not show up if the key is already plugged in

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#2965]
### Description: 
Touch key modal should show up if the lightning key is inserted.

### Steps to Reproduce 
  1. Navigate to https://mdp.github.io/u2fdemo 
  2. Insert the lightning key
  3. Register and Sign

**Actual result:** 
On sign the modal is not presented if the lightning key is plugged in

**Expected result:**
Touch key modal should be displayed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.20 (20.09.11.20)

**Device details:** 
iPhone 11 + iOS 14

**Comment by kjozwiak** [comment]
Closing as we've deprecated the `Yubikey` SDK in favour of the `WKWebView` SDK as per https://github.com/brave/brave-ios/issues/4473. QA went through verifications via https://github.com/brave/brave-ios/issues/4473#issuecomment-1032291511, https://github.com/brave/brave-ios/issues/4473#issuecomment-1033102239 & https://github.com/brave/brave-ios/issues/4473#issuecomment-1033240109 and couldn't reproduce the crashes using the `WKWebView` SDK.
