### ISSUE TITLE
[feature/webauthn] hardware key registration doesn't work on github.com

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#2966]
### Description: 
Registration of hardware keys to github.com should work

### Steps to Reproduce 
  1. Navigate to https://github.com/settings
  2. Navigate to `Account Security` > Security
  3. Add a lightning key

**Actual result:** 
This device cannot be registered

**Expected result:**
Device registration should work

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.20 (20.09.11.20)

**Device details:** 
iPhone 11

**Comment by kjozwiak** [comment]
Closing as we've deprecated the `Yubikey` SDK in favour of the `WKWebView` SDK as per https://github.com/brave/brave-ios/issues/4473. QA went through verifications via https://github.com/brave/brave-ios/issues/4473#issuecomment-1032291511, https://github.com/brave/brave-ios/issues/4473#issuecomment-1033102239 & https://github.com/brave/brave-ios/issues/4473#issuecomment-1033240109 and couldn't reproduce the crashes using the `WKWebView` SDK.
