### ISSUE TITLE
Searching in page does not work when script blocking is enabled

### ISSUE THREAD

**Issue by tillrathmann** [brave/brave-ios#2968]
### Description: 

Searching in page does not work when script blocking is enabled

### Steps to Reproduce 
  1. Enable blocking scripts.
  2. Open a website.
  3. Search in page.

**Actual result:**

Search in page functionality is not working.

**Expected result:**

Search in page should work in all cases, also with script blocking enabled.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Easily.

**Brave Version:** 

1.20 (20.09.11.20)

**Device details:** 

iPhone SE 1 (iOS 14.0.1)

### Additional Information

In Safari searching in a page works even when Javascript is disabled in the settings.

**Comment by iccub** [comment]
This was a limitation on iOS13 and older devices,
I believe iOS14 brought few handy APIs and we can fix it for iOS14+

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 11` running `iOS 14.6` using `1.27 (21.6.10.21)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.5` using `1.27 (21.6.10.21)`

**`Test Case #1`**

* enabled `Blocked Scripts` globally via `Brave Shields & Privacy` under `Settings`
* visited https://en.wikipedia.org/wiki/Main_Page
* ensured that search is working via the omnibox and `Find in Page` via the `Settings` menu

**`Test Case #2`**

* visit https://en.wikipedia.org/wiki/Main_Page and enable `Block Scripts` via the shields panel
* ensured that search is working via the omnibox and `Find in Page` via the `Settings` menu

Created https://github.com/brave/brave-ios/issues/3772 while running through the above.

-----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.27(21.6.10.21)
- Verified able to perform search when scripts are blocked on an individual site
- Verified able to perform page search when scripts are blocked globally
-----------
Verification passed on iPad Pro with iOS 14.6 running 1.27(21.6.10.21)
- Verified able to perform search when scripts are blocked on an individual site
- Verified able to perform page search when scripts are blocked globally
