### ISSUE TITLE
Add more keyboard shourtcuts

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#2973]
`CMD + D` should open the `add bookmark` prompt

**Comment by ciccioska** [comment]
Is this a mobile issue?

**Comment by iccub** [comment]
Yes @ciccioska, it's mostly for iPad with keyboard attached

**Comment by ciccioska** [comment]
I haven't a physical keyboard for my iPad but I can watch on it.

**Comment by iccub** [comment]
I believe most shortcuts should work on iPad simulator and using keyboard on your mac

This file is a good place to start
https://github.com/brave/brave-ios/blob/development/Client/Frontend/Browser/BrowserViewController/BrowserViewController%2BKeyCommands.swift

**Comment by iccub** [comment]
Another one: `CMD + G` to toggle back when finding text

**Comment by steve28** [comment]
> Another one: `CMD + G` to toggle back when finding text

That’s CMG + G to find aGain (aka, find next) - ie., find the next occurrence on the page.  And while you’re at it, CMD + SHIFT + G is usually find previous occurrence.  This is apple standard and works in most apps

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air (3rd Gen)` on `iOS 14.3` using the following build:

```
1.23 (21.1.28.17) with a connected Logi Bluetooth keyboard
```

**`Case 1`** using `CMD + G` & `CMD + SHIFT + G` (Searching)

* launched `1.23 (21.1.28.17)` and visited https://en.wikipedia.org/wiki/Brave_(web_browser)
* `CMD + F` and ensured that search was working
* searched for `brave` and ensured that `CMD + G` cycled through the results and found the next occurrence
* ensured that `CMD + SHIFT + G` cycled back and found the previous occurrence
* ensured the above worked on both normal/private tabs

**`Case 2`** using `CMD + G` (Saving Bookmarks)

* launched `1.23 (21.1.28.17)` and visited https://en.wikipedia.org/wiki/Brave_(web_browser)
* `CMD + D` and ensured that the `New bookmark` modal appeared without any issues
* ensured that you can `Cancel` and dismiss the modal
* ensured that you can `Save` into `Mobile Bookmarks`, create a new folder and save the bookmark into the newly created folder
* ensured that you can save bookmarks into `Favorites`
* ensured the above worked on both normal/private tabs

----

Verification **PASSED** on `iPad Mini 4` on `iOS 13.7` using the following build:

```
1.23 (21.1.28.17) with a connected Logi Bluetooth keyboard
```

**`Case 1`** using `CMD + G` & `CMD + SHIFT + G` (Searching)

* launched `1.23 (21.1.28.17)` and visited https://en.wikipedia.org/wiki/Brave_(web_browser)
* `CMD + F` and ensured that search was working
* searched for `brave` and ensured that `CMD + G` cycled through the results and found the next occurrence
* ensured that `CMD + SHIFT + G` cycled back and found the previous occurrence
* ensured the above worked on both normal/private tabs

**`Case 2`** using `CMD + G` (Saving Bookmarks)

* launched `1.23 (21.1.28.17)` and visited https://en.wikipedia.org/wiki/Brave_(web_browser)
* `CMD + D` and ensured that the `New bookmark` modal appeared without any issues
* ensured that you can `Cancel` and dismiss the modal
* ensured that you can `Save` into `Mobile Bookmarks`, create a new folder and save the bookmark into the newly created folder
* ensured that you can save bookmarks into `Favorites`
* ensured the above worked on both normal/private tabs
