### ISSUE TITLE
Clearing data deletes sites shields settings

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2975]
### Description: 
Clearing data deletes sites shields settings

### Steps to Reproduce 
  1. Enable `Block scripts` from global setings
  2. Visit `https://jsfiddle.net` and ensure page doesn't load due to block script
  3. Disable block script on shields at site level adding an exception
  4. Clear browser data (keep defaults - all enabled)
  5. Close settings, jsfiddle page is blocked again, check shields block script is enabled again

**Actual result:** 
![siteshields](https://user-images.githubusercontent.com/17010094/96452256-b0ce0300-1210-11eb-8501-76ff1b9a6972.gif)

**Expected result:**
Exceptions to site shields settings should be retained. Should not be lost when browser cache/data is deleted

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.21(20.10.15.13)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by kylehickinson** [comment]
@srirambv This is expected, and is not a regression. It is part of the `Browsing History` toggle, which deletes all of your history & visited domains. Your per-site shield settings are linked to said domains and are deleted unless they are domains associated with a bookmark
