### ISSUE TITLE
Default Text Copy

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2979]
### Description: 
Please update the text on to

Make Brave your default browser. Tap here to open settings and update.

![image.png](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/0767ad99-2496-4b60-a5ac-ee954c6ccba0)

**Comment by karenkliu** [comment]
Can we close this issue in favor of https://github.com/brave/brave-ios/issues/2999 ?

**Comment by kylehickinson** [comment]
@karenkliu Yep its already been closed 🙂
