### ISSUE TITLE
Educational in-product notification

### ISSUE THREAD

**Issue by chkk525** [brave/brave-ios#2980]
## Description
Please search for the spec "Educational in-product notification"

ref: The Issue for Android: https://github.com/brave/brave-browser/issues/12209

## Designs
![image](https://user-images.githubusercontent.com/2388823/104767849-b066da80-5721-11eb-96ec-4a487258c8bc.png)

## Assets
Figma: https://www.figma.com/file/atoL4LN2kd8ILnPGwohUoV/?node-id=1384%3A0

**Comment by kylehickinson** [comment]
@anthonypkeane We do not have access to this spec document

**Comment by kylehickinson** [comment]
@anthonypkeane Is this ready to be worked on? The spec is listed as `draft` still

**Comment by anthonypkeane** [comment]
@karenkliu finished the designs a while back  - check the figma link in the doc for those. 
This can be worked on  - thanks

**Comment by srirambv** [comment]
Verification passed on iPhone iPhone 7+ with iOS 14.4 running 1.23(21.2.12.9)
- Verified educational tooltips shown as per spec and #3151 
- Verified tooltips are shown only once per session even if multiple conditions are satisfied
- Verified tooltips are shown on upgrade as well

Ad block | Video ads block | 10+ ads blocked | Encrypted upgrade
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/107768007-b3a7b300-6d2d-11eb-8ff6-c6e5343bf55f.png) | ![image](https://user-images.githubusercontent.com/17010094/107768027-b904fd80-6d2d-11eb-9592-bd1acd98e066.png) | ![image](https://user-images.githubusercontent.com/17010094/107768035-bdc9b180-6d2d-11eb-8b75-a6d080c3957c.png) | ![image](https://user-images.githubusercontent.com/17010094/107768049-c3bf9280-6d2d-11eb-81e3-bac99e947181.png)


**Private browsing only**

Ad block | Video ads block | 10+ ads blocked | Encrypted upgrade
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/107778809-6ed74880-6d3c-11eb-8eca-3e880fcf5166.png) | ![image](https://user-images.githubusercontent.com/17010094/107778877-8282af00-6d3c-11eb-94f3-b16a9900d273.png) | ![image](https://user-images.githubusercontent.com/17010094/107778891-86aecc80-6d3c-11eb-97e5-03d019230f95.png) | ![image](https://user-images.githubusercontent.com/17010094/107778933-95957f00-6d3c-11eb-920b-ebd00fdf0c61.png)

--------
Verification passed on iPhone iPhone XR with iOS 14.4 running 1.23(21.2.12.9)
- Verified educational tooltips shown as per spec and #3151 
- Verified tooltips are shown only once per session even if multiple conditions are satisfied
- Verified tooltips are shown on upgrade as well

**Normal tabs**

Ad block | Video ads block | 10+ ads blocked | Encrypted upgrade
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/107768080-cc17cd80-6d2d-11eb-94e6-a208f47f547d.png) | ![image](https://user-images.githubusercontent.com/17010094/107768090-d0dc8180-6d2d-11eb-8521-fa63f1f62134.png) | ![image](https://user-images.githubusercontent.com/17010094/107768095-d4700880-6d2d-11eb-9a45-f3bbbede4779.png) | ![image](https://user-images.githubusercontent.com/17010094/107768103-d89c2600-6d2d-11eb-880f-0645cad43b04.png)

**Private browsing only**

Ad block | Video ads block | 10+ ads blocked | Encrypted upgrade
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/107776851-08512b00-6d3a-11eb-8ded-2b49e411b332.png) | ![image](https://user-images.githubusercontent.com/17010094/107776866-0c7d4880-6d3a-11eb-9c99-87bed5a4f55b.png) | ![image](https://user-images.githubusercontent.com/17010094/107776886-12732980-6d3a-11eb-945d-0b50a9a93247.png) | ![image](https://user-images.githubusercontent.com/17010094/107776895-156e1a00-6d3a-11eb-81c4-5aa1bb18ce4e.png)

--------
Verification passed on iPhone iPad Pro with iOS 12.4.1running 1.23(21.2.12.9)
- Verified educational tooltips shown as per spec and #3151 
- Verified tooltips are shown only once per session even if multiple conditions are satisfied
- Verified tooltips are shown on upgrade as well
- Ran into #3306 which seems to be an iOS 12 only issue 

Ad block | Video ads block | 10+ ads blocked | Encrypted upgrade
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/107768131-e2be2480-6d2d-11eb-909c-9712e5b8882c.png) | ![image](https://user-images.githubusercontent.com/17010094/107768138-e782d880-6d2d-11eb-8a08-095fad883e89.png) | ![image](https://user-images.githubusercontent.com/17010094/107768150-ed78b980-6d2d-11eb-93bc-55509e2ede71.png) | ![image](https://user-images.githubusercontent.com/17010094/107768168-f5d0f480-6d2d-11eb-9dfd-b83a6723fed9.png)


**Private browsing only**

Ad block | Video ads block | 10+ ads blocked | Encrypted upgrade
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/107779215-f3c26200-6d3c-11eb-8c06-81512b19254c.png) | ![image](https://user-images.githubusercontent.com/17010094/107779237-fae97000-6d3c-11eb-819f-6d49fb7adaeb.png) | ![image](https://user-images.githubusercontent.com/17010094/107779248-ffae2400-6d3c-11eb-831f-b2a847b038a0.png) | ![image](https://user-images.githubusercontent.com/17010094/107779281-0b014f80-6d3d-11eb-8564-9e99e5483012.png)
