### ISSUE TITLE
Increase App Virality

### ISSUE THREAD

**Issue by chkk525** [brave/brave-ios#2981]
Please search for the spec "Increase App virality" > Sharing Button section for details

GitHub Issue iOS: https://github.com/brave/brave-ios/issues/2981
GitHub Issue Android: https://github.com/brave/brave-browser/issues/12210

**Comment by kylehickinson** [comment]
@anthonypkeane We do not have access to this spec in Drive

**Comment by srirambv** [comment]
<details>
<summary>Verification passed on iPhone 7+ with iOS 14.4.2 running 1.24(21.3.31.15)</summary>

**Note: The values on shields tooltips are divided by 100 so its easy to test all of them.**

- Verified social media share button is shown on all messages when  target is reached

1,000 | 5,000  | 10,000  | 25,000 | 75,000 | 100,000 | 250,000 | 500,000 | 1,000,000 
-- | -- | -- | -- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/113283892-c592e480-92e0-11eb-94db-cccbc4ed4065.png) | ![image](https://user-images.githubusercontent.com/17010094/113283945-d5122d80-92e0-11eb-98b5-ad1d32991f51.png) | ![image](https://user-images.githubusercontent.com/17010094/113284675-dee86080-92e1-11eb-976d-06a3aac6d4ee.png) | ![image](https://user-images.githubusercontent.com/17010094/113284435-8749f500-92e1-11eb-8d04-302d73786aa3.png) | ![image](https://user-images.githubusercontent.com/17010094/113284471-95981100-92e1-11eb-9791-7d7e7a25da08.png) | ![image](https://user-images.githubusercontent.com/17010094/113284478-992b9800-92e1-11eb-8844-f0f4ea418e50.png) | ![image](https://user-images.githubusercontent.com/17010094/113284541-b1031c00-92e1-11eb-90e8-e0dbb6c557f2.png) | ![image](https://user-images.githubusercontent.com/17010094/113284588-c11afb80-92e1-11eb-8889-a84ab1dc2ef9.png) | ![image](https://user-images.githubusercontent.com/17010094/113284611-ca0bcd00-92e1-11eb-995e-2264e2c13d4b.png)

- Verified Shields shows Social media share button next to blocked items 
- Verified clicking on the share button brings up share sheet and is able to share the stats with available apps
- Verified selecting an app brings up the NTP stats as an image and adds the sub text `Every day I save data by browsing the web with Brave`
- Verified the text is translated to Japanese for JP 

Shields Share button | Share Stats message | Translated Popup Message | Translate Share Message
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/113285640-1c99b900-92e3-11eb-8462-2d86f86caca5.png) | ![image](https://user-images.githubusercontent.com/17010094/113285678-258a8a80-92e3-11eb-915b-5566d455b035.png) | ![image](https://user-images.githubusercontent.com/17010094/113287540-a2b6ff00-92e5-11eb-9b5c-db6772142c31.png) | ![image](https://user-images.githubusercontent.com/17010094/113285694-291e1180-92e3-11eb-9cf2-65c809c665b1.png)


- Verified upgrading from 1.23.1 doesn't show the new popups immediately 
- Verified upgrading from 1.23.1 with more than 1k+ trackers blocked, new message shows up if there are 20+ items blocked in the same session 
- Verified benchmark popups don't show up in the same session if there is an educational popup shown
- Verified benchmark popups only show up on JP locale

</details>

-------

<details>
<summary>Verification passed on iPhone XR with iOS 13.5 running 1.24(21.3.31.15)</summary>

**Note: The values on shields tooltips are divided by 100 so its easy to test all of them.**

- Verified social media share button is shown on all messages when  target is reached

1,000 | 5,000  | 10,000  | 25,000 | 75,000 | 100,000 | 250,000 | 500,000 | 1,000,000 
-- | -- | -- | -- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/113282309-a6935300-92de-11eb-8f04-28f4b692099d.png) | ![image](https://user-images.githubusercontent.com/17010094/113282325-abf09d80-92de-11eb-844d-ec38eb0db0c5.png) |![image](https://user-images.githubusercontent.com/17010094/113283009-98920200-92df-11eb-874f-8349a07e6ae9.png)  |![image](https://user-images.githubusercontent.com/17010094/113282376-bad75000-92de-11eb-9164-08588a25014d.png) | ![image](https://user-images.githubusercontent.com/17010094/113282407-c591e500-92de-11eb-8a34-c233ca79241b.png) | ![image](https://user-images.githubusercontent.com/17010094/113282458-da6e7880-92de-11eb-92fa-db4f7ac77986.png) | ![image](https://user-images.githubusercontent.com/17010094/113282806-5963b100-92df-11eb-813b-ed28dfd8e3f3.png) | ![image](https://user-images.githubusercontent.com/17010094/113282863-6da7ae00-92df-11eb-912b-fe7810952c8d.png) | ![image](https://user-images.githubusercontent.com/17010094/113282885-74362580-92df-11eb-9bcb-3738266c882b.png)

- Verified Shields shows Social media share button next to blocked items 
- Verified clicking on the share button brings up share sheet and is able to share the stats with available apps
- Verified selecting an app brings up the NTP stats as an image and adds the sub text `Every day I save data by browsing the web with Brave`
- Verified the text is translated to Japanese for JP 

Shields Share button | Share Stats message | Translated Popup Message | Translated share message
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/113295646-60df8600-92f0-11eb-974c-fc7e2d1a88b1.png) | ![image](https://user-images.githubusercontent.com/17010094/113295708-72289280-92f0-11eb-9a88-92d685fe16c6.png) | ![image](https://user-images.githubusercontent.com/17010094/113295724-781e7380-92f0-11eb-979d-2ee22d3bcabb.png) | ![image](https://user-images.githubusercontent.com/17010094/113286522-3b4c7f80-92e4-11eb-906d-d5ae2e190383.png)

- Verified upgrading from 1.23.1 doesn't show the new popups immediately 
- Verified upgrading from 1.23.1 with more than 1k+ trackers blocked, new message shows up if there are 20+ items blocked in the same session 
- Verified benchmark popups don't show up in the same session if there is an educational popup shown
- Verified benchmark popups only show up on JP locale

</details>

--------

<details>
<summary>Verification passed on iPad Pro with iOS 12.4.1 running 1.24(21.3.31.15)</summary>

**Note: The values on shields tooltips are divided by 100 so its easy to test all of them.**

- Verified social media share button is shown on all messages when  target is reached


1,000 | 5,000  | 10,000  | 25,000 | 75,000 | 100,000 | 250,000 | 500,000 | 1,000,000 
-- | -- | -- | -- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/113283174-d131db80-92df-11eb-94e1-ec9bcbd86995.png) | ![image](https://user-images.githubusercontent.com/17010094/113283200-db53da00-92df-11eb-9959-55b5e0e5dd18.png) | ![image](https://user-images.githubusercontent.com/17010094/113283767-9e3c1780-92e0-11eb-8f4f-51c24a61d6d8.png) | ![image](https://user-images.githubusercontent.com/17010094/113283296-0807f180-92e0-11eb-82b9-3ebd8fd5013e.png) | ![image](https://user-images.githubusercontent.com/17010094/113283324-12c28680-92e0-11eb-8759-1bf5cbc35f4d.png) | ![image](https://user-images.githubusercontent.com/17010094/113283366-1c4bee80-92e0-11eb-90f3-00013c56d34f.png) | ![image](https://user-images.githubusercontent.com/17010094/113283380-21a93900-92e0-11eb-9ac5-f3a246115330.png) | ![image](https://user-images.githubusercontent.com/17010094/113283392-253cc000-92e0-11eb-82a0-a51125038db9.png) | ![image](https://user-images.githubusercontent.com/17010094/113283410-2c63ce00-92e0-11eb-900e-46ae51eaf205.png)


- Verified Shields shows Social media share button next to blocked items 
- Verified clicking on the share button brings up share sheet and is able to share the stats with available apps
- Verified selecting an app brings up the NTP stats as an image and adds the sub text `Every day I save data by browsing the web with Brave`
- Verified the text is translated to Japanese for JP 

Shields Share button | Share Stats message | Translated Popup Message | Translated Share message
-- | -- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/113296660-aea8be00-92f1-11eb-94f4-50d532ab26c9.png) | ![image](https://user-images.githubusercontent.com/17010094/113296686-b700f900-92f1-11eb-9312-6e8c39dfc239.png) | ![image](https://user-images.githubusercontent.com/17010094/113296714-bcf6da00-92f1-11eb-9922-fd91eae4c43a.png) | ![image](https://user-images.githubusercontent.com/17010094/113286693-7353c280-92e4-11eb-88bb-ed09d856e1b7.png)


- Verified upgrading from 1.23.1 doesn't show the new popups immediately 
- Verified upgrading from 1.23.1 with more than 1k+ trackers blocked, new message shows up if there are 20+ items blocked in the same session 
- Verified benchmark popups don't show up in the same session if there is an educational popup shown
- Verified benchmark popups only show up on JP locale

</details>
