### ISSUE TITLE
Shields icon doesn't update immediately after toggling shields

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#2982]
When toggling shields on/off the Brave Shields icon in the toolbar does not updated until after the page has reloaded, this should instead happen immediately after the shield is toggled.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.1 running 1.21(20.10.23.15)
- Verified shields icon is updated immediately after toggling shields 
--------------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.10.23.15)
- Verified shields icon is updated immediately after toggling shields 
--------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.10.23.15)
- Verified shields icon is updated immediately after toggling shields
