### ISSUE TITLE
Brave iOS 1.21 - Brave Today - Layout and header issue

### ISSUE THREAD

**Issue by phoogm** [brave/brave-ios#2986]
### Description: 
Brave Today shows on a NTP but only a small top part of the panel, there is no header showing e.g. "Brave Today" so it almost looks like a bug. The visible panel section also seems not aware of the larger iPad screen, it's fine for the iPhone but for the iPad it could be much wider in landscape which is the most used orientation.  Also when scrolling up the Brave Stats and Top Sites disappear. Lastly the settings icon for the Brave Today widget appears if you scroll the NTP page up enough but disappears when scrolling downwards again which is quite confusing. Overall the NTP get's quite busy and due to elements appearing and disappearing also confusing.

### Steps to Reproduce 
  1. Install Brave 21 via TestFlight
  2. Launch Brave
  3. Observe the Brave Today widget at the bottom of the screen.

**Actual result:** 
![IMG_0059](https://user-images.githubusercontent.com/56597375/96704097-f23aeb80-1393-11eb-855f-c506a75ea57c.jpg)
 

**Expected result:**
![Brave Today Proposal](https://user-images.githubusercontent.com/56597375/96710102-de938300-139b-11eb-9f70-bb1f9c5850e9.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.21

**Device details:** 
iPad Pro 2018, IOS 14.1

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A 

### Additional Information
Thanks for looking into, best regards.

**Comment by kylehickinson** [comment]
Going to close this for now, as after the revamp we will likely look into alternate viewing modes for news
