### ISSUE TITLE
Multiple issues with iOS Rewards BAT Panel

### ISSUE THREAD

**Issue by mandar-brave** [brave/brave-ios#2988]
see image --
![image](https://user-images.githubusercontent.com/35932307/96892737-cd4f8280-143e-11eb-936d-1ea77084680c.png)

issue#1
Panel and notifications are outdated
issue#2
Unable to close out the notification (close button issue)

Not setting a fix it now priority due to anticipated changes.
cc @NejcZdovc @kylehickinson

**Comment by kylehickinson** [comment]
@mandar-brave What version of Brave showed this?

**Comment by mandar-brave** [comment]
I believe this is the latest Beta @kylehickinson

**Comment by kylehickinson** [comment]
@mandar-brave Brave Dev or Brave Beta? If Brave Dev, what Rewards environment (if you changed in the past, can be checked in Rewards Debug menu)?

**Comment by mandar-brave** [comment]
This is coming from @BrendanEich -- @BrendanEich can you provide details for what version of iOS App you were using on TestFlight?

**Comment by dodieboy** [comment]
I'm also having the reward server is not responding on version1.20  IOS 13.4.1

**Comment by bsclifton** [comment]
@kylehickinson this is Dev on test flight - version Version 1.20 (20.09.02.14)

**Comment by kylehickinson** [comment]
Closed as this feature is no longer supported in new Rewards on Brave iOS
