### ISSUE TITLE
AC doesnt go through if monthly tip is set

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#2995]
### Description: 
AC doesnt go through if monthly tip is set

### Steps to Reproduce 
  1. Set recurring tip to a verified pub
  2. Trigger AC
  3. Only recurring tip goes through ac doesn't

**Actual result:** 
AC doesnt go through if monthly tip is set

**Expected result:**
AC should go along with recurring tip

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.21(20.10.23.15)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by srirambv** [comment]
cc: @NejcZdovc @bsclifton @kylehickinson @kjozwiak

**Comment by kjozwiak** [comment]
@bsclifton believe we decided not to fix this as it won't be valid anymore once we decide what we're doing with `1.21`.

**Comment by bsclifton** [comment]
Yup- `wontfix` 😄 Thanks @kylehickinson! I'll go ahead and close this out
