### ISSUE TITLE
[Sync v2] Crash when moving bookmark to just deleted folder 

### ISSUE THREAD

**Issue by btlechowski** [brave/brave-ios#2996]
### Steps to Reproduce 
DeviceA : iPhone SE
DeviceB: Ubuntu 18.04 LTS

1. Clean install on DeviceA and DeviceB
1. Establish sync chain between DeviceA and DeviceB
1. DeviceA: Add bookmark folder FA1
1. DeviceA: Add bookmark A1
1. Wait for sync update
1. DeviceB: Delete FA1 and at the same time on DeviceA: Move A1 to FA1
1. Wait for sync update

**Actual result:** 
Crash

**Expected result:**
No crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.21 (20.10.27.20), iPhone SE (iOS 12.4)

Brave | 1.18.5 Chromium: 86.0.4240.111 (Official Build) nightly (64-bit)
-- | --
Revision | b8c36128a06ebad76af51591bfec980224db5522-refs/branch-heads/4240@{#1290}
OS | Ubuntu 18.04 LTS

cc @brave/legacy_qa @jsecretan @iccub @Brandon-T

**Comment by iccub** [comment]
Should be fixed in `Brave Dev 1.21 (20.11.2.17)` please retest

**Comment by srirambv** [comment]
This is not fixed yet. If you navigate into the folder after its deleted from other device it will still lead to crash. @GeetaSarvadnya also reproduced it

**Comment by iccub** [comment]
let's reopen

**Comment by srirambv** [comment]
@GeetaSarvadnya  logged as a follow-up #3011  as this one already had a commit in the PR
