### ISSUE TITLE
Update the Default Browser Modal

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#2999]
### Description: 
Please update the Default Browser call out on iOS as per the design below.

## Designs
![image](https://user-images.githubusercontent.com/2388823/105755300-f8df7e80-5eff-11eb-870f-e9249e6e99ea.png)

## Assets
Figma: https://www.figma.com/file/atoL4LN2kd8ILnPGwohUoV/?node-id=1369%3A18913

Dark theme is supported!

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4 running 1.23(21.1.5.15) 
- Verified default browser modal is shown on second launch 
- Verified default browser modal is shown on 5th day if not set as default on 2nd launch

![image](https://user-images.githubusercontent.com/17010094/107543201-e54f3b80-6bc0-11eb-9e2a-58e11792653d.png) | ![image](https://user-images.githubusercontent.com/17010094/107543219-e97b5900-6bc0-11eb-97c6-31d3cb7b65ce.png)
-- | --

Logged #3287 as a follow up issue for removing modal from iOS 12/13

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.23(21.2.10.18)
- Verified default browser modal is not shown on 2nd launch or after 5 days
- -----------
Verification passed on iPad Pro with iOS 12.4.1running 1.23(21.2.10.18)
- Verified default browser modal is not shown on 2nd launch or after 5 days
