### ISSUE TITLE
Location bar not focused by default when new tab is open in iOS 14.x

### ISSUE THREAD

**Issue by procmail** [brave/brave-ios#3000]
When a new and empty tab is created in iOS & iPadOS 14.x, the user needs to tab on the location bar first before they can type in the URL. The location bar should be in focus by default.

I previously read that to fix this, an "Auto Show Keyboard" option has to be chosen under New Tab settings, but I can't find it. Also, this should be default behavior anyway. In Windows, Brave already does this by default, so experience should be consistent.

Brave Version 1.20

**Comment by kylehickinson** [comment]
Hi @procmail, thanks for the feedback. This is actually by design and not a bug but we'll keep it in mind for future versions of Brave iOS. As a workaround, you can tap where the `+` icon would be in a new tab page (which will show as a search icon/magnifying glass) and it will focus the URL bar without having to reach up. On iPad with a hardware keyboard you can also use the `⌘+L` shortcut.

**Comment by chillaaar** [comment]
> Hi @procmail, thanks for the feedback. This is actually by design and not a bug but we'll keep it in mind for future versions of Brave iOS. As a workaround, you can tap where the `+` icon would be in a new tab page (which will show as a search icon/magnifying glass) and it will focus the URL bar without having to reach up. On iPad with a hardware keyboard you can also use the `⌘+L` shortcut.

This seems to be a bad design choice as more and more people move to using keyboard with their iPads. It's really annoying having to manually click the address bar every time you're opening a new tab (or use 2 shortcuts to do it). Please make the option of always focusing on the addressbar when opening a new tab or just make it default like all other browsers.

**Comment by riddlerboss248** [comment]
I would love to have this feature. Firefox and Orion Browser on iOS have this, and Vivaldi on android. I believe that as users, we would be greatly appreciative if we were given the opportunity to select between disabling or enabling this feature.
