### ISSUE TITLE
Apple One page should open a modal but it doesn't

### ISSUE THREAD

**Issue by chkk525** [brave/brave-ios#3001]
### Description: 
On Apple One page, it should open the subscription modal but it is blocked on Brave. Attached is when I opened the page with Chrome.
https://one.apple.com/us/

### Steps to Reproduce 
  1. Open https://one.apple.com/us/ on Brave
  2.
  3.

**Actual result:** 
<img src="https://user-images.githubusercontent.com/3054915/97822433-43829d80-1cf9-11eb-815c-3e0d3d70b1d8.jpeg" width=50%>

**Expected result:**
On Safari or Chrome

It should ask if open the Apple One price table
<img src="https://user-images.githubusercontent.com/3054915/97822473-7331a580-1cf9-11eb-982e-f6658cc2f707.PNG" width=50%>

and then open the modal
<img src="https://user-images.githubusercontent.com/3054915/97822470-6f9e1e80-1cf9-11eb-9e5c-8b0233f0b943.PNG" width=50%>

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
- every time

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
This seems to be working now as of 1.21. @chkk525 can you re-test please?

**Comment by chkk525** [comment]
@kylehickinson Yes. It worked for me on 1.21. Thank you!
