### ISSUE TITLE
order of bookmarks in files are slightly different

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#3005]
### Description: 
When testing case from https://github.com/brave/brave-ios/issues/3004, I noticed that the bookmark files from steps 5 and 7 are slightly different. Maybe this isn't an issue, but I am not sure.

### Steps to Reproduce 

1. Install 1.20 from Dev TF
1. Setup bookmarks/folders/subfolders
1. Upgrade to latest 1.21 on Dev TF
1. Wait at least 1 minute
1. View the Files on my iPad (under Brave Dev there was a Bookmarks file that I guess the upgrade creates automatically?) --> sent this file to my laptop to have a copy
1. Check 1.21 to confirm bookmarks are visible as expected :white_check_mark: 
1. Export bookmarks to Files (just wanted to compare this to the one created on upgrade) --> sent this file to my laptop to have a copy

**Actual result:** 
Compare files from steps 5 and 7, ignoring different values for fields like `ADD_DATE` and `LAST_MODIFIED`, one of the bookmarks is in a different place in the file. See below boxes:
<img width="938" alt="Screen Shot 2020-11-02 at 8 57 23 AM" src="https://user-images.githubusercontent.com/28145373/97882238-6315c800-1cf1-11eb-8a9f-f189007aabd5.png">

**Expected result:**
Expected order of bookmarks and files to be the same in both files

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
1.21 (20.10.30.21)

**Device details:** 
iPad iOS13

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Should be fixed in `Brave Dev 1.21 (20.11.2.17)` please retest

**Comment by LaurenWags** [comment]
Verified passed with iOS13 iPad mini using `Brave Dev 1.21 (20.11.2.17)`
---------------
Verification passed on iPhone 7+ with iOS 14.1 running 1.21(20.11.2.20)
---------------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.11.2.20)
