### ISSUE TITLE
Setting for auto closing tabs when not saw during a defined time

### ISSUE THREAD

**Issue by Hydrog3n** [brave/brave-ios#3007]
Hello, Thank you for Developing this Browser <3 

## Problem Description 
When we use Brave in iOS all the day tab starts to accumulate and sometimes I look at the number of tabs I have it's crazy. ~200.
An option in the settings should be added to select if we want of not and the delays. Safari has this feature. 
## Feature Overview 
When this feature has enabled all tabs not watch/display during a defined time should be closed.

**Comment by iccub** [comment]
Thanks for the report, we want to have it at some point
Closing as a duplicate of https://github.com/brave/brave-ios/issues/1514

**Comment by Hydrog3n** [comment]
Oh sorry I didn't found this issue. Thank I will follow it.
