### ISSUE TITLE
Favicons looks pixelated

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3008]
### Description: 
Favicons looks pixelated. Follow-up to #2998

### Steps to Reproduce 
  1. Sync bookmarks with favicons between devices

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/98154283-78931980-1ecc-11eb-937f-3d84031f6960.png)

**Expected result:**
Clear crispy icons

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.21(20.11.2.20)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by iccub** [comment]
closing in favor of https://github.com/brave/brave-ios/issues/6066
