### ISSUE TITLE
Rewards Changes

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3009]
https://github.com/brave/internal/issues/723

**Comment by kjozwiak** [comment]
Labeling this as `QA/Yes` as @srirambv @LaurenWags and myself QA'd the changes. We've also ran through manual passes via https://github.com/brave/brave-ios/issues/3063, https://github.com/brave/brave-ios/issues/3062 and https://github.com/brave/brave-ios/issues/3061.
