### ISSUE TITLE
VPN switch is hidden in menu for translated text

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3012]
### Description: 
VPN switch is hidden in menu for translated text

### Steps to Reproduce 
  1. Set device locale to Russian
  2. Install any version and open menu
  3. VPN switch is not visible

**Actual result:** 
<img width=300 src=https://user-images.githubusercontent.com/17010094/98229655-15e46100-1f52-11eb-98ba-aa2651362e9b.png>

**Expected result:**
Switch should be accessible 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.21(20.11.02.20)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by iccub** [comment]
that string should be a DNT i believe, cc @anthonypkeane

**Comment by cperezabo** [comment]
Same in Spanish
![IMG_3811](https://user-images.githubusercontent.com/3604722/105641384-58874c80-5e62-11eb-9b97-5dba1969d153.jpeg)
Dear designer, in case you don't know, english is not the only language in the world, so why you design interfaces which only will work if the text is in english? 😒

**Comment by iccub** [comment]
Thanks for your report @cperezabo, this was a miscommunication with our translators.
This text should be never translated, otherwise there is not enough space for the toggle

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 11` running `iOS 14.4` using `1.23 (21.2.5.15)`

**`Russian`** | **`Spanish`**
--------------|----------------
![IMG_3548](https://user-images.githubusercontent.com/2602313/107457940-0fe9b780-6b21-11eb-8db0-29619461d950.png) | ![IMG_3549](https://user-images.githubusercontent.com/2602313/107457945-12e4a800-6b21-11eb-9a8c-8ffb603d9722.png)

* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.4` using `1.23 (21.2.5.15)`

**`French`** | **`German`**
--------------|----------------
![image](https://user-images.githubusercontent.com/2602313/107458383-0280fd00-6b22-11eb-95df-aac6393a3994.png) | ![image](https://user-images.githubusercontent.com/2602313/107458411-0e6cbf00-6b22-11eb-89bd-8fd1a443a94d.png)

* Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.23 (21.2.5.15)`

**`Japanese`** | **`Thai`**
--------------|----------------
![IMG_0452](https://user-images.githubusercontent.com/2602313/107458873-f5b0d900-6b22-11eb-9818-f9e28418541c.png) | ![IMG_0453](https://user-images.githubusercontent.com/2602313/107458876-f8abc980-6b22-11eb-9d37-87d03b6a9621.png)

* Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.23 (21.2.5.15)`

**`Swedish`** | **`South Korean`**
--------------|----------------
![IMG_0110](https://user-images.githubusercontent.com/2602313/107459433-30ffd780-6b24-11eb-9b16-ae0d943ec93a.png) | ![IMG_0111](https://user-images.githubusercontent.com/2602313/107459441-34935e80-6b24-11eb-9c0d-a4c2da836cfe.png)
