### ISSUE TITLE
Deleted sites are not synced across the devices

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#3013]
### Steps to Reproduce 

Device 1: IOS (iPhone 8)
Device 2: Desktop (Windows 10 x64)

1. Establish sync b/n device 1 and 2 via QR code
2. Bookmark site 1 and site 2 in IOS
3. Create 2 folders A and B in IOS
4. Make sure all the bookmarks and folders are synced in desktop
5. Delete site 1 from IOS, immediately after that move site 1 into folder A in device 2
6. Deleted site is not synced across the devices in sync chain ( site 1 is retained in Folder A in both devices)
 
**Actual result:** 
Deleted sites are not synced across the devices

**Expected result:**
The deleted site should be removed from all the devices in sync chain

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.21(20.11.02.20)

**Device details:** 
iPhone 8 - iOS 13.3.1

**Website problems only:**
- did you check with Brave Shields down?NA
- did you check in Safari/Firefox (WkWebView-based browsers)? No

### Additional Information
cc @brave/legacy_qa @jsecretan @iccub @Brandon-T

**Comment by btlechowski** [comment]
This is a known issue with sync v2 in general: https://github.com/brave/brave-browser/issues/11156

**Comment by Brandon-T** [comment]
Logged here: https://github.com/brave/brave-browser/issues/12430 and https://github.com/brave/brave-browser/issues/12530

Can't be fixed on the iOS side. This can only be fixed in Brave-Core.

**Comment by GeetaSarvadnya** [comment]
Thanks, @btlechowski @Brandon-T - Closing the issue as dup
