### ISSUE TITLE
Typing text into omnibox should match against open tabs and show open tab in autocomplete result

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#3014]
## Problem Description
As a user, you may have several tabs open. When you search using the URL bar (aka omnibox), it will show autocomplete results. Other browsers will show open tabs as a result and (if selected) will jump to that tab instead of doing the search

## Feature Overview
We should do a match against open tabs when displaying autocomplete results. We could match on the URL of the open tab or the title of the open tab.

## Design
Here's how it looks in Chrome on iOS where the feature is present. Here are the steps I did:
1. Launch Chrome on iOS
2. Open brave.com in a tab
3. Open a new tab; go to cnn.com or some other website (not brave.com)
4. In this new tab, type "brave" into the URL bar. Looks like this:
    ![IMG_1063](https://user-images.githubusercontent.com/4733304/98270194-dd418900-1f4b-11eb-8e35-ceb65f939cda.PNG)
5. Pick the result shown at the bottom (has the icon of the arrow going to the right)
6. You're switched to that original tab (from step 2)
7. If you open up tabs, you'll notice your original tab has focus (new tab not created)
    ![IMG_1064](https://user-images.githubusercontent.com/4733304/98270416-15e16280-1f4c-11eb-9326-7d5f59f0dcb8.PNG)

## Implementation Details
Brave experience should be similar to above

Reported via https://twitter.com/ChadNehemiah/status/1324331947070492672

**Comment by iccub** [comment]
To do: This is simple, but please do small consultation with Kyle on how to design it, you can also compare how other iOS browsers handle it from UI perspective

**Comment by soner-yuksel** [comment]
Taking this ticket out of 1.35 cause we dont have url in memory all the time to make tab suggestions useful. Need futher investigation

**Comment by Uni-verse** [comment]
Verification Completed using 1.38 (22.4.25.21)

Devices:
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad | iOS 15.2.1

1. Open Tab Support 

- Using URL bar to search will display section `Open Tabs & Bookmarks & History`
- Active open tabs will appear in the list indicated by a tab legend on the right hand side.
- Open tabs in the list will display copy `Switch to this tab`
- Webpage icon displayed for open tabs
- Clicking on open tab in list will switch to that tab
- Clicking on history item in load that url
- Closing active tab will remove it from the Open Tabs Sections


2. Open tab section with search engine options enabled/disabled

- Open tabs displayed when search suggestions are enabled/disabled
- Open tabs displayed when recent searches are enabled/disabled
- Recently added tab will be displayed 

3. Upgraded Profile

- Open tabs added before upgrading are displayed
- Tabs opened post upgrade will be displayed 
- Clicking on open tab in list will switch to that tab
- Closing a tab will remove it from the Open Tabs section

Mobile | Tablet
-|-
![IMG_2650](https://user-images.githubusercontent.com/17885425/165639317-eaec3fd8-5eb0-46ed-9ec2-bb50d05278d0.PNG) | ![IMG_0262](https://user-images.githubusercontent.com/17885425/165639331-874bbf35-6dff-4f08-9f33-6a928c860774.PNG)
