### ISSUE TITLE
Browser crash when visiting a reddit page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3016]
### Description: 
Browser crash when visiting a reddit page

### Steps to Reproduce 
  1. Install latest dev build and set wallet to staging
  2. Visit http://reddit.com/u/beachbum0407
  3. Browser crash
  4. Try visiting another reddit user page no crash

**Actual result:** 
Browser crash

**Expected result:**
No crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.21(20.11.6.13)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
Note: Crash happens only on staging and not on production wallet. @LaurenWags  and @GeetaSarvadnya  also reproduced the crash

**Comment by iccub** [comment]
Fixed in `Brave Dev 1.21 (20.11.6.22)`, please retest

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.1 running 1.21(20.11.09.08)
- Verified test plan from issue description
--------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.11.09.08)
- Verified test plan from issue description
--------
Verification passed on iPad Pro with iOS 12.4.1 running 1.21(20.11.09.08)
- Verified test plan from issue description
