### ISSUE TITLE
Add Sync staging switch for QA 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3017]
### Description: 
Add Sync staging switch for QA under QA preferences similar to Android 

**Actual result:** 
No option to switch to sync staging

**Expected result:**
Add Sync staging switch in qa preferences

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.21

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
can you post what does it look like on android?

**Comment by iccub** [comment]
can be set via brave core switches now, i think
