### ISSUE TITLE
Update user agent to 14.3

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3020]

**Comment by kjozwiak** [comment]
@iccub quick question, for some reason Brave is listing the OS as `14_3` but Safari is listing it as `14_4` which is correct. Should Brave be listing the same OS version as Safari in this instance?

**`Brave UA`** | **`Safari UA`**
----------------|------------------
![IMG_3544](https://user-images.githubusercontent.com/2602313/107445911-60561a80-6b0b-11eb-9966-c21186e030d6.png) | ![IMG_3545](https://user-images.githubusercontent.com/2602313/107445918-63510b00-6b0b-11eb-9574-59f6548f5edb.png)

**Comment by iccub** [comment]
Are you on iOS 14.3 or 14.4 @kjozwiak?
In this PR we updated user agents to match iOS 14.3, we can update to higher version on next release,
this is a manual process unfortunately

**Comment by kjozwiak** [comment]
> Are you on iOS 14.3 or 14.4 @kjozwiak?
> In this PR we updated user agents to match iOS 14.3, we can update to higher version on next release,
> this is a manual process unfortunately

Makes sense 👍 The above device is on `14.4` hence Safari picking that up but sounds like we hardcode ours to match up to `14.3` which makes sense why Brave is displaying `14_3` rather than `14_4`.

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 11` running `iOS 14.4` using `1.23 (21.2.5.15)`

**`Brave UA (Mobile)`** | **`Safari UA (Mobile)`**
----------------|------------------
![IMG_3544](https://user-images.githubusercontent.com/2602313/107445911-60561a80-6b0b-11eb-9966-c21186e030d6.png) | ![IMG_3545](https://user-images.githubusercontent.com/2602313/107445918-63510b00-6b0b-11eb-9574-59f6548f5edb.png)

**`Brave UA (Desktop)`** | **`Safari UA (Desktop)`**
----------------|------------------
![IMG_3546](https://user-images.githubusercontent.com/2602313/107449164-14a66f80-6b11-11eb-81d0-21be6b33d1c4.png) | ![IMG_3547](https://user-images.githubusercontent.com/2602313/107449173-18d28d00-6b11-11eb-9fca-3b079c0d6931.png)

* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.4` using `1.23 (21.2.5.15)`

**`Brave UA (Mobile)`** | **`Safari UA (Mobile)`**
----------------|------------------
![IMG_0200](https://user-images.githubusercontent.com/2602313/107449451-939ba800-6b11-11eb-9011-cb657bcd2b23.png) | ![IMG_0201](https://user-images.githubusercontent.com/2602313/107449466-98f8f280-6b11-11eb-8813-4fcbed795e5a.png)

**`Brave UA (Desktop)`** | **`Safari UA (Desktop)`**
----------------|------------------
![IMG_0203](https://user-images.githubusercontent.com/2602313/107449495-a44c1e00-6b11-11eb-935c-4613a4e732d5.png)  | ![IMG_0202](https://user-images.githubusercontent.com/2602313/107449498-a8783b80-6b11-11eb-9232-5144a5db4ceb.png)

* Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.23 (21.2.5.15)`

**`Brave UA (Mobile)`** | **`Safari UA (Mobile)`**
----------------|------------------
![IMG_0107](https://user-images.githubusercontent.com/2602313/107451246-e165df80-6b14-11eb-9d85-1eb561ce1e83.png) | ![IMG_0106](https://user-images.githubusercontent.com/2602313/107451252-e460d000-6b14-11eb-88b6-b426a89f57d6.png)

**`Brave UA (Desktop)`** | **`Safari UA (Desktop)`**
----------------|------------------
![IMG_0109](https://user-images.githubusercontent.com/2602313/107451265-edea3800-6b14-11eb-86a2-e6e7f1d02aff.png) | ![IMG_0108](https://user-images.githubusercontent.com/2602313/107451269-f2165580-6b14-11eb-8e3a-ab2949457544.png)

**Comment by kjozwiak** [comment]
@iccub noticing that the versions differ a bit on `iOS 13` as well. Differences:

**`Mobile View`**

* OS appears as `13_6_1` under Brave but appears as `13_7` on Safari

Assuming the same case re: iOS 13? We're hardcoded to `13_6_1` but the device is on `13.7` which Safari is picking up?

**`Desktop View`**

* OS appears as `10_15` in Brave but appears as `10_15_4` under Safari
* Version appears as `13.1` in Brave but appears as `13.1.2` under Safari

Assuming it's expected as it's the same as the current release but wanted to double check 👍 

**`Brave UA (Mobile)`** | **`Safari UA (Mobile)`**
----------------|------------------
![IMG_0451](https://user-images.githubusercontent.com/2602313/107449862-54218b80-6b12-11eb-8517-6fb90753c98f.png) | ![IMG_0450](https://user-images.githubusercontent.com/2602313/107449870-58e63f80-6b12-11eb-9c77-b511a447485b.png)

**`Brave UA (Desktop)`** | **`Safari UA (Desktop)`**
----------------|------------------
![IMG_0449](https://user-images.githubusercontent.com/2602313/107449892-63083e00-6b12-11eb-8aa3-5188ae01e903.png) | ![IMG_0448](https://user-images.githubusercontent.com/2602313/107449902-66032e80-6b12-11eb-9998-d8ea1ede70c1.png)
