### ISSUE TITLE
Update Yandex SE

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3022]

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.2 running 1.22(20.11.20.16)
**Clean Install(Russian Region)**
- Verified on a clean install Yandex is set as the default search engine
- Verified Yandex is shown on top of the list and is selected as the default 
   <img width=300 src=https://user-images.githubusercontent.com/17010094/99946337-1bbdad00-2d6e-11eb-8caa-73e4bbcb1d2f.png>
- Verified selecting Yandex in onboarding sets it as default for both normal and private tabs
   <img width=300 src=https://user-images.githubusercontent.com/17010094/99946410-3859e500-2d6e-11eb-87c2-6ab4f531374d.png>
- Verified performing a search on URL uses Yandex and adds `?text=race&clid=2423859` to the search URL
  <img width=300 src=https://user-images.githubusercontent.com/17010094/99946575-79ea9000-2d6e-11eb-9b10-79988d966339.png>
- Verified enabling search suggestions works as expected 
   <img width=300 src=https://user-images.githubusercontent.com/17010094/99946636-95559b00-2d6e-11eb-8fe7-0a4e43b2d581.png>
- Verified visiting Yandex and performing a search doesn't add `&clid=2423859` to the search query 
  <img width=300 src=https://user-images.githubusercontent.com/17010094/99946779-d9e13680-2d6e-11eb-97c0-44750cf7ab70.png>
- Verified setting a different search engine as default and using the quick search engine for Yandex still adds `&clid=2423859` to the search URL
- Verified attribution is added on both normal and private tabs when Yandex is set as default


**Upgrade Install**
- Verified setting Google as default on 1.21 and upgrading to 1.22 shows Yandex in search engine list
- Verified with a different default search engine set on 1.21 and upgrading to 1.22, performing a search on Yandex via quick search adds `?text=test&clid=2423859` to the search URL.
- Verified visiting Yandex and performing a search adds `?text=test&clid=2423859` to the search URL
- Verified search suggestions work as expected on upgrade
------------
Verification passed on iPhone XR with iOS 13.5 running 1.22(20.11.20.16)
**Clean Install(Russian Region)**
- Verified on a clean install Yandex is set as the default search engine
- Verified Yandex is shown on top of the list and is selected as the default 
   <img width=300 src=https://user-images.githubusercontent.com/17010094/99955332-15cec880-2d7c-11eb-8c83-80bf36b8fb90.png>

- Verified selecting Yandex in onboarding sets it as default for both normal and private tabs
   <img width=300 src=https://user-images.githubusercontent.com/17010094/99955352-1f583080-2d7c-11eb-9103-7aa17844cf2d.png>

- Verified performing a search on URL uses Yandex and adds `?text=cats&clid=2423859` to the search URL
  <img width=300 src=https://user-images.githubusercontent.com/17010094/99955409-3565f100-2d7c-11eb-8dea-3b3a35bcc46c.png>

- Verified enabling search suggestions works as expected 
   <img width=300 src=https://user-images.githubusercontent.com/17010094/99955436-4151b300-2d7c-11eb-8611-5caee49d8e32.png>

- Verified visiting Yandex and performing a search doesn't add `&clid=2423859` to the search query 
  <img width=300 src=https://user-images.githubusercontent.com/17010094/99955454-4adb1b00-2d7c-11eb-8436-f90d312c9fa8.png>

- Verified setting a different search engine as default and using the quick search engine for Yandex still adds `&clid=2423859` to the search URL
- Verified attribution is added on both normal and private tabs when Yandex is set as default


**Upgrade Install**
- Verified setting Google as default on 1.21 and upgrading to 1.22 shows Yandex in search engine list
- Verified with a different default search engine set on 1.21 and upgrading to 1.22, performing a search on Yandex via quick search adds `?text=test&clid=2423859` to the search URL.
- Verified visiting Yandex and performing a search adds `?text=test&clid=2423859` to the search URL
- Verified search suggestions work as expected on upgrade
------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.22(20.11.20.16)
**Clean Install(Russian Region)**
- Verified on a clean install Yandex is set as the default search engine
- Verified Yandex is shown on top of the list and is selected as the default 
   <img width=300 src=https://user-images.githubusercontent.com/17010094/99963334-8c25f780-2d89-11eb-8ee2-3f1d3269e721.png>

- Verified selecting Yandex in onboarding sets it as default for both normal and private tabs
   <img width=300 src=https://user-images.githubusercontent.com/17010094/99963905-664d2280-2d8a-11eb-8985-5caffcacb2fb.png>

- Verified performing a search on URL uses Yandex and adds `?text=dogs&clid=2423859` to the search URL
  <img width=300 src=https://user-images.githubusercontent.com/17010094/99963943-72d17b00-2d8a-11eb-8512-d84680a0092f.png>

- Verified enabling search suggestions works as expected 
   <img width=300 src=https://user-images.githubusercontent.com/17010094/99964011-8e3c8600-2d8a-11eb-940d-2f32d0395f3e.png>

- Verified visiting Yandex and performing a search doesn't add `&clid=2423859` to the search query 
  <img width=300 src=https://user-images.githubusercontent.com/17010094/99964037-9694c100-2d8a-11eb-9a58-3affebc4adc2.png>

- Verified setting a different search engine as default and using the quick search engine for Yandex still adds `&clid=2423859` to the search URL
- Verified attribution is added on both normal and private tabs when Yandex is set as default


**Upgrade Install**
- Verified setting Google as default on 1.21 and upgrading to 1.22 shows Yandex in search engine list
- Verified with a different default search engine set on 1.21 and upgrading to 1.22, performing a search on Yandex via quick search adds `?text=test&clid=2423859` to the search URL.
- Verified visiting Yandex and performing a search adds `?text=test&clid=2423859` to the search URL
- Verified search suggestions work as expected on upgrade
