### ISSUE TITLE
Unable to view subtitles on fullscreen https://www.crunchyroll.com/

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-ios#3024]
### Description: 
Subtitles don't work on full screen crunchyroll videos.

### Steps to Reproduce 
  1. Visit https://www.crunchyroll.com/fire-force/episode-14-the-ashen-reaper-797794
  2. Play video (expect an advert here)
  3. When video plays, subtitles will show. 
  4. Make fullscreen, subtitles disappear.

**Actual result:** 
No subs in full screen video.

**Expected result:**
Expect subs to work to work in full screen

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 
1.20, and 1.21 Brave Beta

**Device details:** 
IPhone 8Plus

**Website problems only:**
- did you check with Brave Shields down? No
- did you check in Safari/Firefox (WkWebView-based browsers)? 
Safari works fine, Firefox doesn't

### Additional Information
Was reported here
https://community.brave.com/t/no-subtitles-in-fullscreen-crunchyroll/178071

**Comment by iccub** [comment]
needs retesting
