### ISSUE TITLE
Add support for partner cards

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3026]
Spec: `Brave Today Sponsored Content Mini Spec`

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.22(20.11.20.16)
- Verified test plan from https://github.com/brave/brave-ios/pull/3052

iPhone 7+(iOS 14.2) | iPhone XR (iOS 13.5) | iPad Pro (iOS 12.4.1)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/100084478-b982ac00-2e42-11eb-994b-73dace56fc0f.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/100084509-c56e6e00-2e42-11eb-9bf7-e3a6672e1fbe.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/100084551-d0290300-2e42-11eb-8f10-2dae45fdb85e.png>
