### ISSUE TITLE
Update feed when Today publishers are changed

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3033]
### Description: 

When a user changes what publishers are enabled/disabled we should regenerate the cards for NEW new tab pages. Any NTP that is already open should use the old generated cards until a user either closes said NTP and opens a new one _or_ taps the  "New Content Available" button that will appear on top in those old NTPs.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4 running 1.24(21.3.15.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3208
- Verified `New content available` message is only shown when Brave Today feed is loaded 
-----------
Verification passed on iPhone XR with iOS 14.4 running 1.24(21.3.15.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3208
- Verified `New content available` message is only shown when Brave Today feed is loaded

**Comment by srirambv** [comment]
QA blocked on iOS 12 due to #3424
