### ISSUE TITLE
URL autocompletion doesn't suggest bookmarks anymore

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3034]
Regression caused by moving over to the new sync implementation, and having to use new bookmarks model

**Comment by iccub** [comment]
Test plan:
- Install 1.22 build
- Add few bookmarks, add few folders
- Tap on url bar, start typing name of one of bookmarks you added
- Verify that the bookmark shows in url suggestions
- Start typing a name of folder you added
- Verify that the folder does not show up in url suggestions

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.2 running 1.22(20.11.20.16)
- Verified test plan from https://github.com/brave/brave-ios/issues/3034#issuecomment-730317832
-----------
Verification passed on iPhone XR with iOS 13.5 running 1.22(20.11.20.16)
- Verified test plan from https://github.com/brave/brave-ios/issues/3034#issuecomment-730317832
-----------
Verification passed on iPad Pro with iOS 12.4.1 running 1.22(20.11.20.16)
- Verified test plan from https://github.com/brave/brave-ios/issues/3034#issuecomment-730317832
