### ISSUE TITLE
Command + Shift + T keyboard shortcut for re-opening closed tabs

### ISSUE THREAD

**Issue by mtoohey31** [brave/brave-ios#3039]
## Problem Description 

Lack of shortcut to re-open closed tab.

## Feature Overview 

Adding the keyboard shortcut will fix the problem.

## Design 

It might be beneficial to have the option to enable/disable the shortcut because some users may not want their tabs to be recoverable after closing them.

## Implementation Details 

Not an iOS app developer so I'm not sure exactly how it would be done, but if you're looking for more info on how it should work, take a look at safari on iOS, it can do this.

## User Experience 

   1. After closing a tab, the user can use the command + shift + t keyboard shortcut to re-open the closed tab.

### Additional information

N/A

**Comment by iccub** [comment]
we'll fix in https://github.com/brave/brave-ios/issues/3039

**Comment by mtoohey31** [comment]
> we'll fix in #3039

Just checking, did you mean to link to a different issue in this post?

**Comment by iccub** [comment]
Yes sorry, i did a huge repo winter cleanup yesterday.
Here's the proper one https://github.com/brave/brave-ios/issues/2123

**Comment by mtoohey31** [comment]
No worries, thanks!
