### ISSUE TITLE
Preferences aren't persisted throughout multiple launches

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#304]
### Description: 
Preferences aren't persisted throughout multiple launches

### Steps to Reproduce 
  1. Install test build from TF
  2. Change preferences settings 
  3. Remove app from memory and relaunch, changed settings revert back to defaults

**Actual result:** 
Preferences aren't persisted throughout multiple launches

**Expected result:**
Preferences should be retained across multiple launch

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
18.10.02.15

**Device details:** 
iPhone 7+ (iOS 11.4.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
Default favourite gets added everytime app is relaunched #149

**Comment by danishjafri88** [comment]
@srirambv are you still able to reproduce this issue?

**Comment by srirambv** [comment]
@danishjafri88 not able to reproduce it on a new profile. But will keep an eye on this and reopen if I can reproduce this issue

**Comment by srirambv** [comment]
Found consistent steps to reproduce this issue
1. Clear browsing history 
2. Go back to tabs and open tab container
3. Add a new tab via + on tab container
4. Go back to tab container and close the second tab by swipe letft/right, browser crashes
5. Relaunch the app, tiles get a new set of duplicates 

Link to recording https://drive.google.com/open?id=14v_ilFHyBbRjBVibYxO3erjASYqQ9FwF
