### ISSUE TITLE
Crash when set as default browser and opening link from other app 

### ISSUE THREAD

**Issue by cwmke** [brave/brave-ios#3041]
### Description: 
Links opened with the tabs overview left open in Brave leads to a crash.

### Steps to Reproduce 
  1. Set Brave as default browser.
  2. Click the show all tabs button (leave it open.)
  3. Go to another app and open a link.
  4. Brave crashes.

**Actual result:** 
Crash

**Expected result:**
Pressed link opens in a new tab probably without exiting the overview.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced.

**Brave Version:** 
Version 1.21 (20.11.10.16) Device iPhone12,3 (iOS 14.2)
Version 1.21 (20.11.10.16) Device iPad8,10 (iOS 14.2)

**Device details:** 
iPhone 11 Pro; iPad Pro (11-inch) (2nd generation)

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.2 running 1.22(20.11.24.17)
- Verified steps from issue description
- Verified no crash when switching to Brave from other app
---------------
Verification passed on iPad Pro with iOS 14.2 running 1.22(20.11.24.17)
- Verified steps from issue description
- Verified no crash when switching to Brave from other app
