### ISSUE TITLE
Search suggestion text color blinks when text is entered

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3044]
### Steps to Reproduce 
  1. Enable search suggestion
  2. Start typing something

**Actual result:** 
Text color blinks

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
Adding `release-notes/include` as this has been an issue for a while and is user facing.

**Comment by kjozwiak** [comment]
Verification **PASSED** on the following platforms using the following build:

```
1.23 (21.1.28.17)
```

* `iPad Air (3rd Gen)` on `iOS 14.3` - **PASSED**
* `iPad Mini 4` on `iOS 13.7` - **PASSED**
* `iPhone 11` on `iOS 14.4` - **PASSED**
* `iPhone 6+` on `iOS 12.4.1` - **PASSED**

STR/Cases used for the above verifications:

* ensured that the STR /Case outlined via https://github.com/brave/brave-ios/pull/3091#issue-528780791 worked as expected on both `Light` & `Dark` themes.
