### ISSUE TITLE
Open bookmarks screen at last visited folder

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3045]
Users are complaining about having to use 2 taps to go to `Mobile bookmarks` folder,
with this enhancement we will always open it at level of last visited folder
if not possible to visit the folder we fallback to `Mobile Bookmarks` folder
if `Mobile Bookmarks` is not available we fallback to root folder.

**Comment by iccub** [comment]
Test plan:
- Install 1.22
- Add bunch of bookmarks and few nested folders
- Go to a folder, then close the bookmarks screen
- Reopen bookmarks screen, verify that last visited folder was opened
- Navigate back, verify that it correctly navigates back to parent folders

You can play around with it a little bit, general rule is that last visited folder should persist between subsequent visits to the bookmarks list screen

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.2 running 1.22(20.11.20.16)
- Verified test plan from https://github.com/brave/brave-ios/issues/3045#issuecomment-730318911
------------
Verification passed on iPhone XR with iOS 13.5 running 1.22(20.11.20.16)
- Verified test plan from https://github.com/brave/brave-ios/issues/3045#issuecomment-730318911
------------
Verification failed on iPad Pro with iOS 12.4.1 running 1.22(20.11.20.16). Logged https://github.com/brave/brave-ios/issues/3072  as a followup
