### ISSUE TITLE
Add universal link handler for buy-vpn screen.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3046]

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4 running 1.23(21.2.12.15)
- Verified VPN screen opens when link is opened from within Brave
- Logged #3308 for opening via thrid party app
--------
Verification passed on iPad Pro with iOS 12.4.1 running 1.23(21.2.12.15)
- Verified VPN screen opens when link is opened from within Brave
- Logged #3308 for opening via thrid party app
--------
Verification passed on iPhone XR with iOS 13.5 running 1.23(21.2.12.15)
- Verified VPN screen opens when link is opened from within Brave
- Verified VPN screen opens when link is opened from external apps like Safari/Notes
