### ISSUE TITLE
Incorrect Yandex domain

### ISSUE THREAD

**Issue by ilmuk** [brave/brave-ios#3047]
### Description: 

I have iOS settings for Russian lang and I have installed Yandex search engine by default. But when searching I see that the queries go to the domain yandex.kz. KZ is Kazakhstan. Requests should go to yandex.ru or yandex.com

### Steps to Reproduce 
  1. Install Yandex as SE 
  2. Submit searching query

**Actual result:**

Redirected to yandex.kz

**Expected result:**

Redirected to yandex.com

**Reproduces how often:** 

Easily reproduced

**Brave Version:**

1.21

**Device details:** 

iPhone 12 Pro Max iOS 14.2

**Website problems only:**
- did you check with Brave Shields down? -
- did you check in Safari/Firefox (WkWebView-based browsers)? -

**Comment by iccub** [comment]
sorry for that,i believe we did the same as firefox-ios, 
we plan to update yandex urls in this ticket https://github.com/brave/brave-ios/issues/3022, hopefully for next release

closing this as duplicate
