### ISSUE TITLE
Face width calculation fails on https://lenskart.com

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3053]
### Description: 
Face width calculation fails on `https://lenskart.com`

### Steps to Reproduce 
  1. Visit `https://lenskart.com` 
  2. Click on `Check Frame Size` on top left 
  3. Shows unsupported message

**Actual result:** 
<img width=300 src=https://user-images.githubusercontent.com/17010094/99620532-9d83a280-2a1d-11eb-9bac-a26418e36d74.png>

**Expected result:**
<img width=300 src=https://user-images.githubusercontent.com/17010094/99620539-a1172980-2a1d-11eb-8ff9-8357b9644e4c.png>

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.21

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? Yes, works fine

**Comment by iccub** [comment]
Seems to work now
