### ISSUE TITLE
Add button to Brave Partner cards

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3055]
Add a button under the Brave Partner cards that match Brave Offer cards

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4 running 1.23(21.2.12.15)
- Verified partner cards have promoted button under them 
![image](https://user-images.githubusercontent.com/17010094/107797012-5a9e4600-6d52-11eb-9373-cc4d0a9943f0.png)

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.23 (21.2.12.15)`

**Note:** This has been verified/checked on the `staging` server

* ensured that promoted articles are being displayed in the feed once the environment is switched from staging to dev
* ensured that clicking on the `Promoted` button on the article opens https://brave.com/brave-today
* ensured that there's a `Brave Partners` source being listed under `Brave Today Settings`
* ensured disabling promoted articles from the source list removes them from the feed

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|---------------|-----------------|----------------
![IMG_0491](https://user-images.githubusercontent.com/2602313/107799707-c9b47400-6d2b-11eb-8c25-19842f1bb972.png) | ![IMG_0492](https://user-images.githubusercontent.com/2602313/107799715-cd47fb00-6d2b-11eb-8e67-ad8b3e0519c2.png) | ![IMG_0493](https://user-images.githubusercontent.com/2602313/107799729-d2a54580-6d2b-11eb-8f4d-06c3ce1ef5a4.png) | ![IMG_0494](https://user-images.githubusercontent.com/2602313/107799742-d89b2680-6d2b-11eb-8f79-245edcc204ad.png)

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.23 (21.2.12.15)`

**Note:** This has been verified/checked on the `staging` server

* ensured that promoted articles are being displayed in the feed once the environment is switched from staging to dev
* ensured that clicking on the `Promoted` button on the article opens https://brave.com/brave-today
* ensured that there's a `Brave Partners` source being listed under `Brave Today Settings`
* ensured disabling promoted articles from the source list removes them from the feed

**`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|---------------|-----------------|----------------
![IMG_0149](https://user-images.githubusercontent.com/2602313/107800477-cf5e8980-6d2c-11eb-8a2d-9b12d550a8f3.png) | ![IMG_0150](https://user-images.githubusercontent.com/2602313/107800493-d1c0e380-6d2c-11eb-8bf0-e51182038eec.png) | ![IMG_0151](https://user-images.githubusercontent.com/2602313/107800507-d5ed0100-6d2c-11eb-8d3a-ecffcd6d281e.png) | ![IMG_0152](https://user-images.githubusercontent.com/2602313/107800518-d9808800-6d2c-11eb-8e94-fa43b8ee9cae.png)
