### ISSUE TITLE
Brave Shields info text is not localized properly in non-english locales

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3064]
### Steps to Reproduce 
  1. Set language to Polish
  2. Visit a website, open shields panel
  3. Tap on the question mark button

**Actual result:** 
Title and body are the same

![IMG_7074](https://user-images.githubusercontent.com/6950387/99979420-5db71500-2da7-11eb-877b-09d192df8359.PNG)

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
@iccub looks like we're actually showing information, however it's not translated. Assuming we'll need to wait for https://github.com/brave/brave-ios/issues/3109? If that's the case, we should wait for translations before running through this one. CCing @anthonypkeane.

**`Example`**:

![IMG_3528](https://user-images.githubusercontent.com/2602313/106631566-e04c1580-654a-11eb-8855-dcdbf75687b0.png)

**Comment by iccub** [comment]
yes, you can wait with this ticket, we are still waiting for translations

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.23(21.2.10.18)
- Verified shields info text is translated and shown properly

iPhone 7+ (iOS 14.4) | iPhone XR (iOS 13.5) | iPad Pro (iOS 12.4.1)
-- | -- | --
<img width=1000 src=https://user-images.githubusercontent.com/17010094/107612645-98aa4580-6c3e-11eb-9341-95f9a0866d96.png> | ![image](https://user-images.githubusercontent.com/17010094/107612639-9516be80-6c3e-11eb-9254-ac6bd06de5ae.png) | ![image](https://user-images.githubusercontent.com/17010094/107612649-9ba53600-6c3e-11eb-8ca8-2c625bf88839.png)
