### ISSUE TITLE
Use production URLs for Brave Today

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3067]

**Comment by kjozwiak** [comment]
@kylehickinson is there a way of knowing that we're using the production URL? I don't see anything in the `Dev` tools that lets QA see which environment we're using for Brave Today.

**Comment by kylehickinson** [comment]
@kjozwiak Not currently, no, outside of using a proxy like Charles/Proxyman

**Comment by kjozwiak** [comment]
Verification **PASSED** using the following iOS devices:

Ensured that the correct `Brave Today` URL was being used as per the following:

* `iPad Mini 4` running `iOS 13.7` using `1.22 (20.12.2.1)` - **PASSED**
* `iPhone 11` running `iOS 14.2` using `1.22 (20.12.2.1)` - **PASSED**
* `iPhone 6s+` running `iOS 12.4.1` using `1.22 (20.12.2.1)` - **PASSED**
* `iPad Air (3rd Gen)` running `iOS 14.2` using `1.22 (20.12.2.1)` - **PASSED**

Example:

<img width="845" alt="Screen Shot 2020-12-07 at 5 05 41 PM" src="https://user-images.githubusercontent.com/2602313/101412940-6e8c7e00-38b1-11eb-9dff-34a34c88e579.png">
