### ISSUE TITLE
Browser hangs when editing bookmark folder 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3070]
### Description: 
Browser hangs when editing bookmark folder 

### Steps to Reproduce 
  1. Add/sync insane amount of bookmarks [Used this one [Bookmarks_debug.html.zip](https://github.com/brave/brave-ios/files/5588888/Bookmarks_debug.html.zip)]
  2. Add a folder under mobile bookmarks and add a few bookmarks in it
  3. Edit folder from step 2, browser crashes

**Actual result:** 
https://youtu.be/Cdar5p_VA3I

**Expected result:**
No crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.22 (20.11.20.16)

**Device details:** 
iPhone 7+ (iOS 14.2)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
Marking issue for 1.23 as its not a blocker for 1.22
cc: @anthonypkeane @Brandon-T

**Comment by kjozwiak** [comment]
Reproduced the original issue mentioned via https://github.com/brave/brave-ios/issues/3070#issue-749549762 using `1.22 (20.11.20.16)`.

Verification **PASSED** using the following iOS devices:

* `iPad Mini 4` running `iOS 13.7` using `1.22 (20.12.2.1)` - **PASSED**
* `iPhone 11` running `iOS 14.2` using `1.22 (20.12.2.1)` - **PASSED**
* `iPhone 6s+` running `iOS 12.4.1` using `1.22 (20.12.2.1)` - **PASSED**
* `iPad Air (3rd Gen)` running `iOS 14.2` using `1.22 (20.12.2.1)` - **PASSED**

Verified that Brave doesn't crash/stall/hang when running through the STR outlined via https://github.com/brave/brave-ios/issues/3070#issue-749549762.
