### ISSUE TITLE
Last visited folder view is not retained

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3072]
### Description: 
Last visited folder view is not retained

### Steps to Reproduce 
  1. Install 1.22
  2. Add a bunch of nested folders or sync similar structure via desktop
  3. Close bookmarks sheet and reopen goes back to root folder view

**Actual result:** 
https://youtu.be/akJR1JAWZdQ

**Expected result:**
Should open last viewed folder 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.22(20.11.20.16)

**Device details:** 
iPad Pro (iOS 12.4.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
cc: @Brandon-T @iccub

**Comment by srirambv** [comment]
Issue repro's on all versions with bookmark shortcut on URL bar. Removing iOS 12 label

**Comment by LaurenWags** [comment]
Reproduces on iPad with iOS12 (5th Gen) and iOS13 (mini).

Using the Bookmarks icon next to the URL bar on iPads does not retain the last viewed position. IMO would be nice if the position matched the one when accessing Bookmarks from the 3 dots menu.

General steps I followed were:
1. Install 1.22
2. Have bookmarks and some nested folders (I tried both adding manually and via sync)
3. Open 3 dots menu, open Bookmarks
4. Navigate into a sub folder
5. Close Bookmarks
6. Reopen Bookmarks from 3 dots menu, see that position is retained
7. Close Bookmarks
8. Open Bookmarks from icon by URL bar
9. Bookmarks shows root
10. Navigate into a sub folder
11. Close Bookmarks
12. Open Bookmarks from icon by URL bar
13. Bookmarks shows root again

**Comment by kjozwiak** [comment]
@iccub @Brandon-T did we confirm that this was merged into `1.22`? Believe we weren't 100% sure during the last iOS triage meeting. Both @LaurenWags and @srirambv can still reproduce.

At this point, we might want to just open a follow up to fix this in `1.22.1`. CCing @bsclifton.

**Comment by kjozwiak** [comment]
Created https://github.com/brave/brave-ios/issues/3123 as this isn't fixed in `1.22.x`.

**Comment by iccub** [comment]
will be further addressed in this ticket https://github.com/brave/brave-ios/issues/3123
