### ISSUE TITLE
Brave Rewards section is empty

### ISSUE THREAD

**Issue by YuhNoYuh** [brave/brave-ios#3076]
## Description
I couldn’t find a particular section for IOS so i will post here instead. i open up rewards to start the process but all i get is the option to turn off the brave icon. as in this picture 
![8731E353-01F8-4441-BF01-87A9FDE88E14](https://user-images.githubusercontent.com/74927659/99999285-efb22400-2d8d-11eb-906c-84ef1edc3666.jpeg)
![A63EE5C5-22F7-4CF0-938F-B232C0456D8B](https://user-images.githubusercontent.com/74927659/99999286-efb22400-2d8d-11eb-9071-1c56d84b2481.jpeg)
IOS is 14.2 and IPhone X. Any help?

**Comment by bsclifton** [comment]
@YuhNoYuh I moved to appropriate repo and updated the post. I think there are two different settings pages for rewards

@kylehickinson can you confirm? BTW - this will be changing in our upcoming release (1.22)

**Comment by kylehickinson** [comment]
@YuhNoYuh This is the correct screen, rewards settings exist in the rewards panel, which you can view by disabling that preference you found in Settings

> can you confirm? BTW - this will be changing in our upcoming release (1.22)
Correct, there will be further changes to this screen in the next release
