### ISSUE TITLE
Remove/Replace "?" from rewards onboarding string

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3081]
### Description: 

Looks like there's a `?` at the end of the reward onboarding string which doesn't make sense.

### Steps to Reproduce 
  1. install `1.22 (20.11.25.21)` via TF
  2. run through onboarding till you get to rewards

**Actual result:** 

<p align="center">
<img src="https://user-images.githubusercontent.com/2602313/100298482-3d31bb00-2f5f-11eb-9e9f-03be936d57e7.jpg" width=300>
</p>

**Expected result:**

I'm not 100% sure what it should be, but maybe using `!` or a period makes more sense. CCing @jamesmudgett @anthonypkeane to decide how the string should look like.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.22 (20.11.25.21)`

**Device details:** 

* `iPhone 11` running `iOS 14.2` - **Reproduced**

**Website problems only:** `N/A`
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @bsclifton @srirambv

**Comment by kylehickinson** [comment]
Just verified that this was indeed what was in the Figma file 😅: 
<img width="299" alt="image" src="https://user-images.githubusercontent.com/529104/100304579-0cf11900-2f6d-11eb-9ebe-b1daeca1477d.png">

**Comment by srirambv** [comment]
cc: @karenkliu

**Comment by iccub** [comment]
this requires new translations, would be better to address it in next release,
we can hotfix it quickly for English lang though

**Comment by karenkliu** [comment]
I think it the `?` was just supposed to be a period `.` lol @iccub 
A Figma typo! 🙈

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 11` running `iOS 14.2` using `1.22 (20.12.2.0)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.0.1` using `1.22 (20.12.2.0)`
* Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.22 (20.12.2.0)`

Ensured `?` was removed from onboarding as per https://github.com/brave/brave-ios/issues/3081#issue-751219638. Examples:

**`iPhone 11`** | **`iPad Air (3rd Gen)`** | **` iPhone 6s+`** |
-----------------|---------------------------|------------------|
![IMG_3476](https://user-images.githubusercontent.com/2602313/100830544-ea11a980-3431-11eb-8731-06caad70b172.png) | ![IMG_0168](https://user-images.githubusercontent.com/2602313/100830555-f3027b00-3431-11eb-95ad-39a7a507c129.png) | ![IMG_0077](https://user-images.githubusercontent.com/2602313/100834180-74114080-3439-11eb-8dc4-f8081f547b37.png)

**Comment by kjozwiak** [comment]
> this requires new translations, would be better to address it in next release,
> we can hotfix it quickly for English lang though

Created https://github.com/brave/brave-ios/issues/3100 so the above doesn't fall through the cracks. Still needs to be fixed for all locales other than English.
