### ISSUE TITLE
Core data parity between 1.6 and 1.7

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#309]
The goal is to have the same database schema on both versions. It will help with upgrading to the new codebase.

**Comment by iccub** [comment]
Related pull requests that has already been merged:

https://github.com/brave/brave-ios/pull/307
https://github.com/brave/brave-ios/pull/306

**Comment by jhreis** [comment]
CD parity no longer required. As long as DB upgrade happens, we're good!
