### ISSUE TITLE
Brave Creates localhost 'Bookmarks Migration' Tab on Launch

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ios#3092]
### Description: 

Upon launching Brave 1.21 (12.11.10.16), users may witness the creation of a new tab informing them of an issue importing their bookmarks. Issue is demonstrated in the media below; note that prior to closing Brave there are no tabs (other than the NTP) opened. Upon relaunching the browser, a new tab is created pointing to a localhost resource.

![ios-bookmarks-bug](https://user-images.githubusercontent.com/815158/100640803-73bf5b00-32fc-11eb-8847-c2c1bb13c66b.gif)

**Reproduces how often:**
Easily, _for affected users_.

**Brave Version:**
1.21 (12.11.10.16)

**Device details:**
iPhone11,2 (iOS 14.0.1)

**Comment by iccub** [comment]
Fixed in https://github.com/brave/brave-ios/pull/3043 will be ready in next release

Is this a user report or happens to you @jonathansampson?

**Comment by jonathansampson** [comment]
@iccub User report. I was not able to repro.
