### ISSUE TITLE
iOS doesn't warn when its unable to connect to desktop

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3097]
### Description: 

When a user attempts to transfer more than 4 iOS devices to a single desktop, iOS doesn't currently present the user with a modal/error indicating that the 5th transfer failed.

**Actual result:** 

Once you initiate the 5th transfer, there's no errors/indicator letting the user know that the transfer failed.

**Expected result:**

![image](https://user-images.githubusercontent.com/2602313/100918321-53330480-34a6-11eb-9707-56f2cc17495f.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

* 100% reproducible

**Brave Version:** 

* **`1.22 (20.11.26.20)`**

**Device details:** 

This affects all devices/iOS versions as it's a server side issue rather than a client side problem.

**Website problems only:**

- did you check with Brave Shields down? `NA`
- did you check in Safari/Firefox (WkWebView-based browsers)? `NA`

### Additional Information 

cc: @kjozwiak @anthonypkeane

**Comment by kjozwiak** [comment]
This was fixed via a server side fix by @husobee so there's nothing that needs to be done from a client side perspective.

**Comment by kjozwiak** [comment]
Re-opened as this isn't working. I was table to initiate a transfer on the fifth and sixth device but never received the BAT on the desktop.

**Comment by Robodog63** [comment]
> I really appreciate that I love searching going to certain sites but I hate it when I'm looking for somebody and they've got me encrypt it out because she's a web developer knows how to do that but having the extra help and codes to get over some of the junk people put out there's really nice appreciate it

**Comment by kjozwiak** [comment]
Closing after speaking with @husobee. Issue was due to limiting via server side.

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 11` running `iOS 14.2` using `1.22 (20.12.2.1)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.0.1` using `1.22 (20.12.2.1)`
* Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.22 (20.12.2.1)`
* Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.22 (20.12.2.1)`

**`iPhone 11`** | **`iPad Air (3rd Gen)`** | **` iPhone 6s+`** | **` iPad Mini 4`** |
-----------------|---------------------------|------------------|------------------|
![IMG_3492](https://user-images.githubusercontent.com/2602313/101118042-4dc4df80-35b6-11eb-8ba7-5d01032a47a7.png) | ![IMG_0170](https://user-images.githubusercontent.com/2602313/101118464-10ad1d00-35b7-11eb-81a5-42e5c2224904.png) | ![IMG_0079](https://user-images.githubusercontent.com/2602313/101118790-d1cb9700-35b7-11eb-9857-4bc9ee3f860c.png) | ![IMG_0362](https://user-images.githubusercontent.com/2602313/101119395-3b987080-35b9-11eb-8439-61a758b18453.png)

* Verification **PASSED** on `iPad Mini 4` running `iOS 13.4.1` using `1.22 (20.12.2.1)`
![5th transfer](https://user-images.githubusercontent.com/28145373/101163888-4deacc80-3602-11eb-8e4e-dcf55b8c29d8.PNG)
