### ISSUE TITLE
Brave Core/Chromium framework causing increased storage usage

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3099]
Users are reporting seeing increased storage usage (in the GB's) starting in 1.21 

- Sync is not required to be enabled
- Solution should clear out all files causing space increase

**Comment by bsclifton** [comment]
Fixed in `brave-core` 1.20 via https://github.com/brave/brave-core/pull/7349

Uplifts open:
- 1.16 https://github.com/brave/brave-core/pull/7355
- 1.18 part of https://github.com/brave/brave-core/pull/7371
- 1.19 part of https://github.com/brave/brave-core/pull/7431

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 14.2` using `1.22.1 (20.12.10.22)`

**`Scenario 1 - Clean Install`**

* downloaded `1.22.1 (20.12.10.22)` from TF (Dev) and opened/closed Brave several times
* ensured that `Documents & Data` wasn't being incrementally increased on every restart
* opened Brave ~30 times and ensured it stayed ~135-140MB

**`Scenario 2 - Upgrade`**

* downloaded `1.22 (20.12.2.1)` from TF (Dev) and opened/closed Brave several times
* noticed that `Documents & Data` incrementally increased in size every single time
* increased Brave size to ~`1.02 GB`
* updated to `1.22.1 (20.12.10.22)` and ensured that the size of Brave decreased

In this case, it went from `1.02GB` --> ~`137MB`

**`1.22 (20.12.2.1)`** | **`1.22.1 (20.12.10.22)`**
-----------------------|----------------------------
![IMG_3503](https://user-images.githubusercontent.com/2602313/102248092-c721d380-3ece-11eb-8531-3ae67d37a1d0.png) | ![IMG_3505](https://user-images.githubusercontent.com/2602313/102248122-d012a500-3ece-11eb-909e-e4c1f10cc1fa.png)
![IMG_3504](https://user-images.githubusercontent.com/2602313/102248149-dc96fd80-3ece-11eb-9d7b-a9414b0dcda6.png) | ![IMG_3506](https://user-images.githubusercontent.com/2602313/102248160-df91ee00-3ece-11eb-9e9e-a2ae6ca4f33a.png)

------------------

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.22.1 (20.12.10.22)`

**`Scenario 1 - Clean Install`**

* downloaded `1.22.1 (20.12.10.22)` from TF (Dev) and opened/closed Brave several times
* ensured that `Documents & Data` wasn't being incrementally increased on every restart
* opened Brave ~30 times and ensured it stayed ~135-140MB

**`Scenario 2 - Upgrade`**

* downloaded `1.22 (20.12.2.1)` from TF (Dev) and opened/closed Brave several times
* noticed that `Documents & Data` incrementally increased in size every single time
* increased Brave size to ~`1.03 GB`
* updated to `1.22.1 (20.12.10.22)` and ensured that the size of Brave decreased

In this case, it went from `1.03GB` --> ~`143MB`

**`1.22 (20.12.2.1)`** | **`1.22.1 (20.12.10.22)`**
-----------------------|----------------------------
![IMG_0363](https://user-images.githubusercontent.com/2602313/102252022-8ed0c400-3ed3-11eb-8137-37d5638ea2f5.PNG) | ![IMG_0365](https://user-images.githubusercontent.com/2602313/102252322-f25af180-3ed3-11eb-92fd-4fec1e70d44b.PNG)
![IMG_0364](https://user-images.githubusercontent.com/2602313/102252602-4665d600-3ed4-11eb-8067-f3b70e4e31e9.PNG) | ![IMG_0366](https://user-images.githubusercontent.com/2602313/102252619-4b2a8a00-3ed4-11eb-887b-caf011514cac.PNG)

------------------

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.22.1 (20.12.10.22)`

**`Scenario 1 - Clean Install`**

* downloaded `1.22.1 (20.12.10.22)` from TF (Dev) and opened/closed Brave several times
* ensured that `Documents & Data` wasn't being incrementally increased on every restart
* opened Brave ~30 times and ensured it stayed ~135-140MB

**`Scenario 2 - Upgrade`**

* downloaded `1.22 (20.12.2.1)` from TF (Dev) and opened/closed Brave several times
* noticed that `Documents & Data` incrementally increased in size every single time
* increased Brave size to ~`1.1 GB`
* updated to `1.22.1 (20.12.10.22)` and ensured that the size of Brave decreased

In this case, it went from `1.1GB` --> ~`181MB`

**`1.22 (20.12.2.1)`** | **`1.22.1 (20.12.10.22)`**
-----------------------|----------------------------
![IMG_0080](https://user-images.githubusercontent.com/2602313/102256838-e5d99780-3ed9-11eb-8102-62672f9656e8.png) | ![IMG_0082](https://user-images.githubusercontent.com/2602313/102256892-f8ec6780-3ed9-11eb-8f94-3098bbbc6679.png)
![IMG_0081](https://user-images.githubusercontent.com/2602313/102256854-ebcf7880-3ed9-11eb-89a0-4998a4cd676c.png) | ![IMG_0083](https://user-images.githubusercontent.com/2602313/102256911-0144a280-3eda-11eb-9414-8356d291674e.png)

------------------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.2` using `1.22.1 (20.12.10.22)`

**`Scenario 1 - Clean Install`**

* downloaded `1.22.1 (20.12.10.22)` from TF (Dev) and opened/closed Brave several times
* ensured that `Documents & Data` wasn't being incrementally increased on every restart
* opened Brave ~30 times and ensured it stayed ~135-150MB

**`Scenario 2 - Upgrade`**

* downloaded `1.22 (20.12.2.1)` from TF (Dev) and opened/closed Brave several times
* noticed that `Documents & Data` incrementally increased in size every single time
* increased Brave size to ~`1.02 GB`
* updated to `1.22.1 (20.12.10.22)` and ensured that the size of Brave decreased

In this case, it went from `1.02GB` --> ~`146MB`

**`1.22 (20.12.2.1)`** | **`1.22.1 (20.12.10.22)`**
-----------------------|----------------------------
![IMG_0171](https://user-images.githubusercontent.com/2602313/102260862-e1fc4400-3ede-11eb-8729-9a831704ed1a.png) | ![IMG_0173](https://user-images.githubusercontent.com/2602313/102260882-ea547f00-3ede-11eb-8146-ff1bee380d7d.png)
![IMG_0172](https://user-images.githubusercontent.com/2602313/102260912-f5a7aa80-3ede-11eb-8a03-a25ca8b208a0.png) | ![IMG_0174](https://user-images.githubusercontent.com/2602313/102260931-fb9d8b80-3ede-11eb-8dea-610cd974a8ad.png)

**Comment by kjozwiak** [comment]
@LaurenWags mind going through this one more time to see if it's working for you? Wouldn't mind another set of eyes just in case as you mentioned you ran into a few issues when initially running through the above.

**Comment by LaurenWags** [comment]
Verification **PASSED** on `iPad Mini 4` running `iOS 13.4.1` using `1.22.1 (20.12.10.23)`

**`Scenario 1 - Clean Install`**

* downloaded `1.22.1 (20.12.10.23)` from TF (Prod) and opened/closed Brave several times
* ensured that `Documents & Data` wasn't being incrementally increased on every restart
* opened Brave ~30 times and ensured it stayed ~135-140MB

**`Scenario 2 - Upgrade`**

* downloaded `1.22` from App Store and opened/closed Brave several times
* noticed that `Documents & Data` incrementally increased in size every single time
* increased Brave size to ~`1.04 GB`
* updated to `1.22.1 (20.12.10.23)` and ensured that the size of Brave decreased. Note, this took a bit of time in my testing (~40 min) but it did decrease.

In this case, it went from `1.04GB` --> ~`143MB`

**`1.22`** | **`1.22.1 (20.12.10.23)`**
-----------------------|----------------------------
![IMG_F954DDFAE856-1](https://user-images.githubusercontent.com/28145373/102271725-be8cc580-3eed-11eb-9272-6918313c0c2e.jpeg) | ![IMG_9313B07610D7-1](https://user-images.githubusercontent.com/28145373/102272008-175c5e00-3eee-11eb-92f5-e27b50be37a2.jpeg)
![IMG_0D812C86B322-1](https://user-images.githubusercontent.com/28145373/102271827-df551b00-3eed-11eb-84ec-df69030b18aa.jpeg) | ![IMG_796D76379E09-1](https://user-images.githubusercontent.com/28145373/102271898-f3008180-3eed-11eb-99ff-1cdb37662480.jpeg)
