### ISSUE TITLE
Remove/Replace "?" from rewards onboarding string (l10n) - follow up to #3081

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3100]
### Description: 

As per https://github.com/brave/brave-ios/issues/3081#issuecomment-734201879, the original issue was only fixed on English locales. Fix from https://github.com/brave/brave-ios/issues/3081 will need to be applied to all the other locales.

### Steps to Reproduce

**`Prerequisite:`** - Change locale to something other than English.

  1. install `1.22 (20.12.2.0)` via TF
  2. run through onboarding till you get to rewards

**Actual result:** 

<p align="center">
<img src="https://user-images.githubusercontent.com/2602313/100834416-db2ef500-3439-11eb-8ebf-5fe414c7ade9.png" width=300>
</p>

**Expected result:**

`?` should be removed as per https://github.com/brave/brave-ios/issues/3081#issuecomment-737010665.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR mentioned above.

**Brave Version:** 

* `1.22 (20.12.2.0)`

**Device details:** 

* `iPhone 11` running `iOS 14.2` - **Reproduced**

**Website problems only:** `N/A`
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @iccub @karenkliu @kylehickinson @anthonypkeane @bsclifton

**Comment by iccub** [comment]
We don't have time for other languages translations for 1.22, this needs to be addressed at later date

**Comment by iccub** [comment]
Closing in favor of general translations ticket https://github.com/brave/brave-ios/issues/3109
This doesn't involve any code changes, we only have to order new translations for it
