### ISSUE TITLE
Automate updates of httpse data files

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#3107]
### Description: 
https://github.com/brave/brave-ios/tree/development/Client/WebFilters/ShieldStats/Httpse - HTTPSE db is packaged with the app. Going forward we plan to update these data files regularly. In order to avoid updates to the app with updates to the httpse db, code should fetch the updated httpse data files on the fly at regular intervals.

**Comment by kylehickinson** [comment]
Perhaps we should split this out into 2 tickets, one for updating the DB locally for now and another for implementing the actual auto-update code

**Comment by jumde** [comment]
sgtm, created this issue to update the db locally: https://github.com/brave/brave-ios/issues/3122

**Comment by mihaiplesa** [comment]
Does this issue have a priority/timeline?

**Comment by jumde** [comment]
cc: @anthonypkeane @bsclifton

**Comment by iccub** [comment]
We use apple's httpse lists now
