### ISSUE TITLE
improving modal/message when transfer fails

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3108]
### Description: 

We should look into improving the error message that's being displayed when a user fails a transfer. The current message doesn't have any context nor clues on why the transfer might have failed. This is going to make support a real challenge due to the limited capability we have in extracting logs/info.

Probably won't make it into `1.22` but I think we should improve the message.

### Steps to Reproduce

  1. install brave `1.21` from TF
  2. switch over to `staging` via `View Rewards Debug Menu`
  3. restart the browser and enable rewards
  4. claim the UGP grant and update to `1.22`
  5. attempt to scan a random QR code so the transfer fails and you get the above modal/message

**Actual result:** 

![image](https://user-images.githubusercontent.com/2602313/101120754-6cc67000-35bc-11eb-9509-e5dac0f549dd.png)

**Expected result:**

We can do a better job conveying to the user on why the transfer failed. The current message is pretty cryptic and doesn't really give any context on why the transfer failed.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.22 (20.12.2.1)` - **Reproduced**

**Device details:** 

Reproducible on all iOS devices & iOS versions.

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @marshall @aekeus @bsclifton @LaurenWags @srirambv @kylehickinson @iccub

**Comment by kylehickinson** [comment]
Unfortunately on the client side there are only two points of failure: wallet link & VG claim. We are currently showing the code that comes back from ledger in brackets in the current message. If we want enhanced messaging here we have to get additional codes returned by shared lib/ledger to convey different messaging (or at least so the code can be read by support to know what it means)

**Comment by kjozwiak** [comment]
> We are currently showing the code that comes back from ledger in brackets in the current message.

Do we have a list of the other codes? Just curious as all I've been seeing is `(1)` no matter the situation/issue.

**Comment by kylehickinson** [comment]
@kjozwiak https://github.com/brave/brave-core/blob/b7d0b03044d4b308db2878324bda81642dab6e73/vendor/bat-native-ledger/include/bat/ledger/public/interfaces/ledger.mojom#L196

**Comment by kjozwiak** [comment]
awesome, thanks @kylehickinson. Definitely helpful in terms of debugging. CCing @brave/legacy_qa @brave/rewards-support ☝️

**Comment by iccub** [comment]
Let's label it as stale, not many users still having to do the wallet transfer
