### ISSUE TITLE
Update NTP Background Images

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#3112]
New default background images, attribution. Ping for data.

**Comment by kjozwiak** [comment]
@jamesmudgett @iccub can you please update the issue with the set of images that are expected to be in `1.23`? I don't see anything in https://github.com/brave/brave-ios/pull/3120 either.

**Comment by jamesmudgett** [comment]
@kjozwiak https://bravesoftware.slack.com/archives/C07HD31EZ/p1612973465086600

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 14.4` using `1.23 (21.2.10.18)`

Ensured the following:
* each image was credited to the correct person as per the document via https://github.com/brave/brave-ios/issues/3112#issuecomment-776823008
* websites worked were applicable when clicking on the credit/persons name

<details>
<summary>Portrait mode - PASSED</summary>

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![IMG_3571](https://user-images.githubusercontent.com/2602313/107598167-06c51d00-6beb-11eb-98d3-f8c7df2a1902.png) | ![IMG_3570](https://user-images.githubusercontent.com/2602313/107598172-09c00d80-6beb-11eb-9f21-dbdc4e42f815.png) | ![IMG_3569](https://user-images.githubusercontent.com/2602313/107598199-1a708380-6beb-11eb-913e-81be57c1cd80.png) | ![IMG_3568](https://user-images.githubusercontent.com/2602313/107598204-1e9ca100-6beb-11eb-9ed6-7ec882a96fea.png) | ![IMG_3567](https://user-images.githubusercontent.com/2602313/107598209-22c8be80-6beb-11eb-9581-9b330ed931d6.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![IMG_3566](https://user-images.githubusercontent.com/2602313/107598247-396f1580-6beb-11eb-96b9-7c6d48e2a393.png) | ![IMG_3565](https://user-images.githubusercontent.com/2602313/107598250-3d029c80-6beb-11eb-9c41-075268ab0062.png) | ![IMG_3564](https://user-images.githubusercontent.com/2602313/107598260-412eba00-6beb-11eb-8684-f748b0e9fe78.png) | ![IMG_3563](https://user-images.githubusercontent.com/2602313/107598270-44c24100-6beb-11eb-816f-ccb34f771274.png) | ![IMG_3562](https://user-images.githubusercontent.com/2602313/107598275-4a1f8b80-6beb-11eb-9712-b998b04b8d0f.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![IMG_3561](https://user-images.githubusercontent.com/2602313/107598299-5ad00180-6beb-11eb-88c2-d618b93ec8fa.png) | ![IMG_3560](https://user-images.githubusercontent.com/2602313/107598308-5e638880-6beb-11eb-824a-3b4305be3a18.png) | ![IMG_3559](https://user-images.githubusercontent.com/2602313/107598315-61f70f80-6beb-11eb-913d-9e3cd94bdd87.png) | ![IMG_3558](https://user-images.githubusercontent.com/2602313/107598322-66232d00-6beb-11eb-9aad-5f6d9e6f9c6e.png) | ![IMG_3557](https://user-images.githubusercontent.com/2602313/107598326-6a4f4a80-6beb-11eb-939c-dd538e1ff894.png)
</details>

<details>
<summary>Landscape mode - PASSED</summary>

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![IMG_3588](https://user-images.githubusercontent.com/2602313/107599351-345f9580-6bee-11eb-8a0f-a5aef7073e92.png) | ![IMG_3587](https://user-images.githubusercontent.com/2602313/107599356-36c1ef80-6bee-11eb-94ef-ceca9cf45b92.png) | ![IMG_3586](https://user-images.githubusercontent.com/2602313/107599360-3c1f3a00-6bee-11eb-9af3-05bc47971e19.png) | ![IMG_3585](https://user-images.githubusercontent.com/2602313/107599365-40e3ee00-6bee-11eb-9123-dacbd739012d.png) | ![IMG_3584](https://user-images.githubusercontent.com/2602313/107599367-44777500-6bee-11eb-9bfd-a3cd383a67a6.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![IMG_3583](https://user-images.githubusercontent.com/2602313/107599380-4f320a00-6bee-11eb-9c73-14d6b01f498d.png) | ![IMG_3582](https://user-images.githubusercontent.com/2602313/107599383-522cfa80-6bee-11eb-9f6b-85df0d76afe4.png) | ![IMG_3581](https://user-images.githubusercontent.com/2602313/107599388-56591800-6bee-11eb-9ec0-864d03262187.png) | ![IMG_3579](https://user-images.githubusercontent.com/2602313/107599397-5c4ef900-6bee-11eb-9935-1eea9cdad6d0.png) | ![IMG_3580](https://user-images.githubusercontent.com/2602313/107599393-59ec9f00-6bee-11eb-91c1-03af9529bc67.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![IMG_3578](https://user-images.githubusercontent.com/2602313/107599422-74bf1380-6bee-11eb-9e32-abadab3d62f5.png) | ![IMG_3577](https://user-images.githubusercontent.com/2602313/107599428-77ba0400-6bee-11eb-848f-be40965680a2.png) | ![IMG_3576](https://user-images.githubusercontent.com/2602313/107599433-7b4d8b00-6bee-11eb-811c-6d9b4945c768.png) | ![IMG_3575](https://user-images.githubusercontent.com/2602313/107599444-7ee11200-6bee-11eb-8443-0511f35bcd9d.png) | ![IMG_3574](https://user-images.githubusercontent.com/2602313/107599447-830d2f80-6bee-11eb-8a12-28c86b5b1666.png)
</details>

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.4` using `1.23 (21.2.10.18)`

Ensured the following:
* each image was credited to the correct person as per the document via https://github.com/brave/brave-ios/issues/3112#issuecomment-776823008
* websites worked were applicable when clicking on the credit/persons name

<details>
<summary>Portrait mode - PASSED</summary>

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![image](https://user-images.githubusercontent.com/2602313/107600064-9ae5b300-6bf0-11eb-82e1-c04a421133c3.png) | ![image](https://user-images.githubusercontent.com/2602313/107600072-a33dee00-6bf0-11eb-9ba7-4018a2b14aec.png) | ![image](https://user-images.githubusercontent.com/2602313/107600089-acc75600-6bf0-11eb-8804-2838f1619f93.png) | ![image](https://user-images.githubusercontent.com/2602313/107600099-b781eb00-6bf0-11eb-8491-7752a8621aba.png) | ![image](https://user-images.githubusercontent.com/2602313/107600110-bfda2600-6bf0-11eb-9497-e297c85e014a.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![image](https://user-images.githubusercontent.com/2602313/107600182-f617a580-6bf0-11eb-81d8-b9a98759af0f.png) | ![image](https://user-images.githubusercontent.com/2602313/107600201-ffa10d80-6bf0-11eb-8d9a-9a583de8c04f.png) | ![image](https://user-images.githubusercontent.com/2602313/107600205-0891df00-6bf1-11eb-8a31-2c701b141cc3.png) | ![image](https://user-images.githubusercontent.com/2602313/107600214-10ea1a00-6bf1-11eb-80b4-8375ca3c7388.png) | ![image](https://user-images.githubusercontent.com/2602313/107600219-18112800-6bf1-11eb-8f56-e0929fcb455b.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![image](https://user-images.githubusercontent.com/2602313/107600267-38d97d80-6bf1-11eb-8f92-1e31e2c5f4e0.png) | ![image](https://user-images.githubusercontent.com/2602313/107600277-40992200-6bf1-11eb-8deb-700f76a11be8.png) | ![image](https://user-images.githubusercontent.com/2602313/107600288-47279980-6bf1-11eb-8213-3ae78d38f014.png) | ![image](https://user-images.githubusercontent.com/2602313/107600298-50186b00-6bf1-11eb-8414-1c8ee7232635.png) | ![image](https://user-images.githubusercontent.com/2602313/107600305-59093c80-6bf1-11eb-9087-f02cc812509c.png)
</details>

<details>
<summary>Landscape mode - PASSED</summary>

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![image](https://user-images.githubusercontent.com/2602313/107600420-bd2c0080-6bf1-11eb-9262-c3ada3aad58e.png) | ![image](https://user-images.githubusercontent.com/2602313/107600440-c74dff00-6bf1-11eb-84f5-b4bf86e64d79.png) | ![image](https://user-images.githubusercontent.com/2602313/107600450-cf0da380-6bf1-11eb-8840-de772851d60b.png) | ![image](https://user-images.githubusercontent.com/2602313/107600460-d765de80-6bf1-11eb-8689-13a3e37e56a2.png) | ![image](https://user-images.githubusercontent.com/2602313/107600473-e187dd00-6bf1-11eb-925c-4f11b9139c84.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![image](https://user-images.githubusercontent.com/2602313/107600498-f7959d80-6bf1-11eb-85d7-f3cec55338bd.png) | ![image](https://user-images.githubusercontent.com/2602313/107600516-01b79c00-6bf2-11eb-89ed-c95832317d41.png) | ![image](https://user-images.githubusercontent.com/2602313/107600531-0aa86d80-6bf2-11eb-8628-da0342fc3795.png) | ![image](https://user-images.githubusercontent.com/2602313/107600538-1300a880-6bf2-11eb-98d5-e129bc1340be.png) | ![image](https://user-images.githubusercontent.com/2602313/107600556-1d22a700-6bf2-11eb-926e-faf619d8879b.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![image](https://user-images.githubusercontent.com/2602313/107600585-2ca1f000-6bf2-11eb-9f60-53173fed35e0.png) | ![image](https://user-images.githubusercontent.com/2602313/107600593-3592c180-6bf2-11eb-9fc8-b80023d81070.png) | ![image](https://user-images.githubusercontent.com/2602313/107600608-42171a00-6bf2-11eb-8b30-e526f655ea33.png) | ![image](https://user-images.githubusercontent.com/2602313/107600618-4b07eb80-6bf2-11eb-9984-c1f67aedee84.png) | ![image](https://user-images.githubusercontent.com/2602313/107600631-53f8bd00-6bf2-11eb-88fe-64e3094d1b4d.png)
</details>

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.23 (21.2.10.18)`

Ensured the following:
* each image was credited to the correct person as per the document via https://github.com/brave/brave-ios/issues/3112#issuecomment-776823008
* websites worked were applicable when clicking on the credit/persons name

<details>
<summary>Portrait mode - PASSED</summary>

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![IMG_0146](https://user-images.githubusercontent.com/2602313/107601668-6294a380-6bf5-11eb-83da-91c8e22c9289.png) | ![IMG_0144](https://user-images.githubusercontent.com/2602313/107601673-66282a80-6bf5-11eb-82af-5a291bc249ae.png) | ![IMG_0142](https://user-images.githubusercontent.com/2602313/107601685-6c1e0b80-6bf5-11eb-8530-27680f8368bc.png) | ![IMG_0140](https://user-images.githubusercontent.com/2602313/107601707-717b5600-6bf5-11eb-963d-7c2b7e879914.png) | ![IMG_0138](https://user-images.githubusercontent.com/2602313/107601712-75a77380-6bf5-11eb-92fe-79753a183d62.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![IMG_0136](https://user-images.githubusercontent.com/2602313/107601729-822bcc00-6bf5-11eb-8a42-271c862a52fc.png) | ![IMG_0134](https://user-images.githubusercontent.com/2602313/107601736-8526bc80-6bf5-11eb-8072-c22f8a1a8d96.png) | ![IMG_0132](https://user-images.githubusercontent.com/2602313/107601742-88ba4380-6bf5-11eb-999c-42a4e471ad3d.png) | ![IMG_0130](https://user-images.githubusercontent.com/2602313/107601749-8c4dca80-6bf5-11eb-9c1b-3bc69cad11df.png) | ![IMG_0128](https://user-images.githubusercontent.com/2602313/107601755-91127e80-6bf5-11eb-9a3b-7947197dd84e.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![IMG_0126](https://user-images.githubusercontent.com/2602313/107601793-aab3c600-6bf5-11eb-8534-011e2c1ed38b.png) | ![IMG_0124](https://user-images.githubusercontent.com/2602313/107601799-ad162000-6bf5-11eb-8293-f61ecd146826.png) | ![IMG_0122](https://user-images.githubusercontent.com/2602313/107601808-b0a9a700-6bf5-11eb-8996-631656c0419d.png) | ![IMG_0120](https://user-images.githubusercontent.com/2602313/107601812-b43d2e00-6bf5-11eb-94a2-6b4938e1edc8.png) | ![IMG_0118](https://user-images.githubusercontent.com/2602313/107601823-bbfcd280-6bf5-11eb-9da1-9807c6234125.png)
</details>

<details>
<summary>Landscape mode - PASSED</summary>

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![IMG_0147](https://user-images.githubusercontent.com/2602313/107601907-fbc3ba00-6bf5-11eb-9e75-707cba6f300a.png) | ![IMG_0145](https://user-images.githubusercontent.com/2602313/107601910-fe261400-6bf5-11eb-8392-14a4efa0ac22.png) | ![IMG_0143](https://user-images.githubusercontent.com/2602313/107601914-02523180-6bf6-11eb-9d12-ba18aa3ed89b.png) | ![IMG_0141](https://user-images.githubusercontent.com/2602313/107601920-067e4f00-6bf6-11eb-8609-df432e3d0791.png) | ![IMG_0139](https://user-images.githubusercontent.com/2602313/107601923-0b430300-6bf6-11eb-8edc-9ac1c509b90d.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![IMG_0137](https://user-images.githubusercontent.com/2602313/107601940-17c75b80-6bf6-11eb-8bd6-4c6b80cd47f0.png) | ![IMG_0135](https://user-images.githubusercontent.com/2602313/107601944-1bf37900-6bf6-11eb-8710-61367afe0f25.png) | ![IMG_0133](https://user-images.githubusercontent.com/2602313/107601950-1f870000-6bf6-11eb-8c82-a2a78f9de6ab.png) | ![IMG_0131](https://user-images.githubusercontent.com/2602313/107601954-231a8700-6bf6-11eb-92d1-b2dae344ea52.png) | ![IMG_0129](https://user-images.githubusercontent.com/2602313/107601966-2a419500-6bf6-11eb-9a08-c22d65552d05.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![IMG_0127](https://user-images.githubusercontent.com/2602313/107602089-80aed380-6bf6-11eb-8644-3152e98df6ee.png) | ![IMG_0125](https://user-images.githubusercontent.com/2602313/107602111-84425a80-6bf6-11eb-979e-6690a3577a80.png) | ![IMG_0123](https://user-images.githubusercontent.com/2602313/107602122-886e7800-6bf6-11eb-84b3-78b07a3328c0.png) | ![IMG_0121](https://user-images.githubusercontent.com/2602313/107602125-8c9a9580-6bf6-11eb-87cb-01351ba25770.png) | ![IMG_0119](https://user-images.githubusercontent.com/2602313/107602130-90c6b300-6bf6-11eb-967d-e8ed8f81eabf.png)
</details>

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.23 (21.2.10.18)`

Ensured the following:
* each image was credited to the correct person as per the document via https://github.com/brave/brave-ios/issues/3112#issuecomment-776823008
* websites worked were applicable when clicking on the credit/persons name

<details>
<summary>Portrait mode - PASSED</summary>

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![IMG_0488](https://user-images.githubusercontent.com/2602313/107602777-b654bc00-6bf8-11eb-95cd-52760169f37c.png) | ![IMG_0486](https://user-images.githubusercontent.com/2602313/107602781-b94fac80-6bf8-11eb-9401-29938167e7fe.png) | ![IMG_0484](https://user-images.githubusercontent.com/2602313/107602790-bf458d80-6bf8-11eb-80af-40bad0cc85c0.png) | ![IMG_0482](https://user-images.githubusercontent.com/2602313/107602800-c371ab00-6bf8-11eb-9156-9e8df97896f8.png) | ![IMG_0480](https://user-images.githubusercontent.com/2602313/107602814-c8365f00-6bf8-11eb-8393-5796b2f006c8.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![IMG_0478](https://user-images.githubusercontent.com/2602313/107602826-d2585d80-6bf8-11eb-9fec-2417c7c8d0cd.png) | ![IMG_0476](https://user-images.githubusercontent.com/2602313/107602831-d5ebe480-6bf8-11eb-9103-14d271abb293.png) | ![IMG_0474](https://user-images.githubusercontent.com/2602313/107602839-d97f6b80-6bf8-11eb-9698-2f75c9ea48aa.png) | ![IMG_0472](https://user-images.githubusercontent.com/2602313/107602844-ddab8900-6bf8-11eb-8d5e-a22c49eb8f02.png) | ![IMG_0470](https://user-images.githubusercontent.com/2602313/107602852-e2703d00-6bf8-11eb-9678-2423b16dc20e.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![IMG_0468](https://user-images.githubusercontent.com/2602313/107602860-ed2ad200-6bf8-11eb-9592-913fd85c3688.png) | ![IMG_0466](https://user-images.githubusercontent.com/2602313/107602865-f0be5900-6bf8-11eb-889b-f661fb7e086a.png) | ![IMG_0464](https://user-images.githubusercontent.com/2602313/107602867-f451e000-6bf8-11eb-99b5-20c3b77c9399.png) | ![IMG_0462](https://user-images.githubusercontent.com/2602313/107602870-f7e56700-6bf8-11eb-8034-74131683c6c0.png) | ![IMG_0460](https://user-images.githubusercontent.com/2602313/107602879-fd42b180-6bf8-11eb-9b36-da6c02f73df5.png)
</details>

<details>
<summary>Landscape mode - PASSED</summary>

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![IMG_0489](https://user-images.githubusercontent.com/2602313/107603007-6a564700-6bf9-11eb-891a-0d46b398dffd.png) | ![IMG_0487](https://user-images.githubusercontent.com/2602313/107603011-6de9ce00-6bf9-11eb-9e6d-ce2e7781a0be.png) | ![IMG_0485](https://user-images.githubusercontent.com/2602313/107603012-72ae8200-6bf9-11eb-8ad2-072d8daa5107.png) | ![IMG_0483](https://user-images.githubusercontent.com/2602313/107603018-78a46300-6bf9-11eb-945f-0c77e686401f.png) | ![IMG_0481](https://user-images.githubusercontent.com/2602313/107603022-7c37ea00-6bf9-11eb-90ea-0a0287e9809a.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![IMG_0479](https://user-images.githubusercontent.com/2602313/107603048-91ad1400-6bf9-11eb-8037-1e6187dc6a42.png) | ![IMG_0477](https://user-images.githubusercontent.com/2602313/107603050-9245aa80-6bf9-11eb-9fa8-3c4a2fda1c1e.png) | ![IMG_0475](https://user-images.githubusercontent.com/2602313/107603053-92de4100-6bf9-11eb-98f4-a14994675451.png) | ![IMG_0473](https://user-images.githubusercontent.com/2602313/107603055-940f6e00-6bf9-11eb-9bd4-000072b892dc.png) | ![IMG_0471](https://user-images.githubusercontent.com/2602313/107603057-95409b00-6bf9-11eb-9e6a-b234e1298a79.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | 
---------------|----------------|-----------------|----------------|----------------
![IMG_0467](https://user-images.githubusercontent.com/2602313/107603090-ab4e5b80-6bf9-11eb-857d-a2ae61ce7550.png) | ![IMG_0465](https://user-images.githubusercontent.com/2602313/107603091-ac7f8880-6bf9-11eb-899a-f0e9cfe2922c.png) | ![IMG_0463](https://user-images.githubusercontent.com/2602313/107603092-adb0b580-6bf9-11eb-9fde-d185c68aab93.png) | ![IMG_0461](https://user-images.githubusercontent.com/2602313/107603095-aee1e280-6bf9-11eb-8835-caf2c031e141.png) | ![IMG_0469](https://user-images.githubusercontent.com/2602313/107603098-b0aba600-6bf9-11eb-8471-69fe3fceb12e.png)
