### ISSUE TITLE
Update adblock list more frequently

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3113]
Currently the adblock lists are only downloaded once per launch but with devices having more RAM these days it may be days before Brave is ejected from memory. We should add a check on app foreground to download the list if it hasn't been updated within the past 24 hours

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 14.4` using `1.23 (21.2.5.14)`

* verified the STR/Cases outlined via https://github.com/brave/brave-ios/pull/3130#issue-535214102 and ensured that `last fetch time` was being updated

**`Initial Launch`** | **`After ~10min`**
---------------------|-----------------------
![IMG_3555](https://user-images.githubusercontent.com/2602313/107465562-8fcb4e00-6b30-11eb-848f-0abc22dd8727.png) | ![IMG_3556](https://user-images.githubusercontent.com/2602313/107465565-92c63e80-6b30-11eb-838a-06985b2d8078.png)

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.4` using `1.23 (21.2.5.14)`

* verified the STR/Cases outlined via https://github.com/brave/brave-ios/pull/3130#issue-535214102 and ensured that `last fetch time` was being updated

**`Initial Launch`** | **`After ~10min`**
---------------------|-----------------------
![IMG_0210](https://user-images.githubusercontent.com/2602313/107467013-11bc7680-6b33-11eb-86fc-48ad07508a3d.png) | ![IMG_0211](https://user-images.githubusercontent.com/2602313/107467029-1b45de80-6b33-11eb-9339-ba229fd947c9.png)

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.23 (21.2.5.14)`

* verified the STR/Cases outlined via https://github.com/brave/brave-ios/pull/3130#issue-535214102 and ensured that `last fetch time` was being updated

**`Initial Launch`** | **`After ~10min`**
---------------------|-----------------------
![IMG_0458](https://user-images.githubusercontent.com/2602313/107466849-c1ddaf80-6b32-11eb-95b5-0fd20111aa33.png) | ![IMG_0459](https://user-images.githubusercontent.com/2602313/107466871-cace8100-6b32-11eb-9255-f08193af950b.png)

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.23 (21.2.5.14)`

* verified the STR/Cases outlined via https://github.com/brave/brave-ios/pull/3130#issue-535214102 and ensured that `last fetch time` was being updated

**`Initial Launch`** | **`After ~10min`**
---------------------|-----------------------
![IMG_0116](https://user-images.githubusercontent.com/2602313/107465673-ca34eb00-6b30-11eb-9136-f17b363a2206.png) | ![IMG_0117](https://user-images.githubusercontent.com/2602313/107465680-cd2fdb80-6b30-11eb-8449-9fdaf5a6362a.png)
