### ISSUE TITLE
shields don't open on certain sites

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#3116]
### Description: 
Shields won't open on certain sites. Seems like if shields are blocking phishing/malware, tapping on the Brave logo won't open the shields for that site.

### Steps to Reproduce 
  1. Clean install
  2. Navigate to raisegame.com
  3. Tap on shields

**Actual result:** 
Nothing happens

**Expected result:**
Shields should open

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.21 (20.11.10.16) - App Store version
1.22 (20.12.2.1) - TF version

**Device details:** 
iPad mini w/ iOS 13

**Website problems only:**
- did you check with Brave Shields down? n/a
- did you check in Safari/Firefox (WkWebView-based browsers)? n/a

### Additional Information
cc @brave/legacy_qa

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.23(21.1.6.19)
- Verified shields open without any issue after the page is loaded

iPhone 7+ (iOS 14.3) | iPhone XR (iOS 13.5) | iPad Pro (iOS 14.3) | iPad Pro (iOS 12.4.1)
-- | -- | -- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/104017316-cf102300-51af-11eb-8f70-aa878eb07e6e.png> | <img width=200 src=https://user-images.githubusercontent.com/17010094/104017276-bef84380-51af-11eb-8eca-ac11e5bb0165.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/104018020-12b75c80-51b1-11eb-8dfa-947de0eb9860.png> | <img width=350 src=https://user-images.githubusercontent.com/17010094/104018242-61fd8d00-51b1-11eb-946f-b5165c269621.png>
