### ISSUE TITLE
Brave can't open link in some apps

### ISSUE THREAD

**Issue by zdybo** [brave/brave-ios#3121]
### Description: 
My default browser is Brave. When i try to open link on Messenger app, nothing happens. If my default browser is Safari the link opens normally. The problem also occurs with other applications. There is no problem in the Apple Mail application, here links open normally on Brave with Brave as default. Other case, when, for example, in the Facebook application i want to open article, the link starts in the built-in Facebook browser, and from there selecting in the options run in Safari, it easily transfers to Brave and open in Brave. This problem occurs in various applications, the link of which, when clicked, should turn on in Brave, but it doesn't

### Steps to Reproduce 
  1. Having Brave (as default browser) and FB Messenger
  2. Try to open link from message (in Messenger)
  3. The link doesn't open, nothing happens.

**Actual result:**
The link doesn't open, nothing happens.
**Expected result:**
Link open in Brave.

**Reproduces how often:**
Always in some app.

**Brave Version:**  1.21 (20.11.10.16)

**Device details:** 
iPhone 7, iOS 14.2

### Additional Information
It looks like a problem with Brave being my default browser.
###Edit
I would like to add something else, the problem occurs in Messenger when I receive a message in which under the image to which the link is attached - e.g. a Facebook post and underneath, there is no link to this post in the message. The problem does not occur when there is a link in the message under the image pointing to the post, then Brave starts it normally - that is, it transfers to Facebook. It is the same in other applications, in some you can't even launch links.

**Comment by zdybo** [comment]
I would like to add something else, the problem occurs in Messenger when I receive a message in which under the image to which the link is attached - e.g. a Facebook post and underneath, there is no link to this post in the message. The problem does not occur when there is a link in the message under the image pointing to the post, then Brave starts it normally - that is, it transfers to Facebook. It is the same in other applications, in some you can't even launch links.

**Comment by iccub** [comment]
Hi @zdybo, does this problem happens to you when you have Safari as your default browser?
Could you check if it happens when you have Firefox or Chrome set?

We tried to reproduce it but no luck

**Comment by soner-yuksel** [comment]
And in addition what @iccub said, Is it possible to provide us a video of what is happening with/without facebook or an example link that causes this issue.

**Comment by zdybo** [comment]
@iccub @soner-yuksel 
Here links to video's from my phone.
Messenger: https://streamable.com/chqt4o
As you can see, the same is in Chrome as default.
And from polish app Wykop (something like reddit):
https://streamable.com/el0srs
I tried and the same problem is in Firefox.

**Comment by soner-yuksel** [comment]
@zdybo Thanks for sending the details. I cant replicate this whatever I try and the same scenario is working for me through messenger and other apps.
I will mark it for further investigation.

**Comment by zdybo** [comment]
@soner-yuksel 
I think you can try replicate this on Wykop App - https://apps.apple.com/pl/app/wykop/id365459650.

**Comment by zdybo** [comment]
I don't know what help. Now i'm on Brave 1.22.1 and iOS 14.3 and everything works well.

**Comment by iccub** [comment]
Thanks for lettings us know @zdybo, i am going to close this ticket for now, could be some Apple weirdness
