### ISSUE TITLE
Update httpse data files

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#3122]
### Description

Update the httpse data files included in the app. 

## Test Plan

Specified here: https://github.com/brave/brave-ios/pull/3129

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4 running 1.23(21.2.10.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3129
- -------
Verification passed on iPhone XR with iOS 13.5 running 1.23(21.2.10.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3129
- -------
 Verification passed on iPad Pro with iOS 12.4.1 running 1.23(21.2.10.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3129

**Comment by kjozwiak** [comment]
@srirambv looks like the above worked for you? For some reason, mines not updating to HTTPS. Example:

https://youtu.be/jgQWjHe0Wf0

Can you reproduce at all or is it working all the time?
