### ISSUE TITLE
Last visited folder view is not retained - follow up to #3072

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3123]
Originally created by @srirambv via https://github.com/brave/brave-ios/issues/3072. However, it wasn't fixed in `1.22` as QA can still reproduce the issue as per https://github.com/brave/brave-ios/issues/3072#issuecomment-735656871 and https://github.com/brave/brave-ios/issues/3072#issuecomment-740192135. As per process, creating a new issue as code already landed as per https://github.com/brave/brave-ios/commit/d0c072edb3c5fac414ca0675436f4cb637586bab.

> 
> 
> ### Description: 
> Last visited folder view is not retained
> 
> ### Steps to Reproduce 
>   1. Install 1.22
>   2. Add a bunch of nested folders or sync similar structure via desktop
>   3. Close bookmarks sheet and reopen goes back to root folder view
> 
> **Actual result:** 
> https://youtu.be/akJR1JAWZdQ
> 
> **Expected result:**
> Should open last viewed folder 
> 
> **Reproduces how often:** [Easily reproduced, Intermittent Issue]
> Easy
> 
> **Brave Version:** 
> 1.22(20.11.20.16)
> 
> **Device details:** 
> iPad Pro (iOS 12.4.1)
> 
> **Website problems only:**
> - did you check with Brave Shields down? NA
> - did you check in Safari/Firefox (WkWebView-based browsers)?  NA
> 
> 
> ### Additional Information
> cc: @Brandon-T @iccub

**Comment by kjozwiak** [comment]
Labeling `release/blocking`. If we want this fixed in another version, lets remove `release/blocking` and assign a priority.

**Comment by iccub** [comment]
Found the fix, it's a one liner, should be easy to verify, will include in 1.22.1

**Comment by iccub** [comment]
Fixed in https://github.com/brave/brave-ios/pull/3124

**Comment by kjozwiak** [comment]
awesome, thanks for the quick work @iccub 👍

**Comment by LaurenWags** [comment]
Verification passed on iPad mini with iOS 13 running 1.22.1 (20.12.10.22)

* Confirmed navigating into a subfolder retained that selection when viewing Bookmarks from 3 dots menu and shortcut next to the URL bar
* Confirmed selection was retained between the two places
* Confirmed close/relaunch of app retained the selected subfolder
* Confirmed when navigating to a different subfolder and then viewing from the other location showed the same subfolder
* Confirmed for both new and upgrade (from 1.22) profiles.
* Note, if performing an upgrade and you last viewed bookmarks from the shortcut next to the URL bar, on upgrade you will see the root folder. Per discussion in slack, this is expected. However, if you navigate to a subfolder post upgrade then your selection will be retained as expected.

-----------

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.22.1 (20.12.10.22)`

* Confirmed navigating into a subfolder retained that selection when viewing Bookmarks from 3 dots menu and shortcut next to the URL bar
* Confirmed selection was retained between the two places
* Confirmed close/relaunch of app retained the selected subfolder
* Confirmed when navigating to a different subfolder and then viewing from the other location showed the same subfolder
* Confirmed for both new and upgrade  profiles. (used `1.22 (20.12.2.1)`)

-----------

Verification **PASSED** on `iPhone 11` running `iOS 14.2` using `1.22.1 (20.12.10.22)`

* Confirmed navigating into a subfolder retained that selection when viewing Bookmarks from 3 dots menu and shortcut next to the URL bar
* Confirmed selection was retained between the two places
* Confirmed close/relaunch of app retained the selected subfolder
* Confirmed when navigating to a different subfolder and then viewing from the other location showed the same subfolder
* Confirmed for both new and upgrade  profiles. (used `1.22 (20.12.2.1)`)
