### ISSUE TITLE
New setting to configure what happens on startup

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#3126]
## Problem Description
Similar to Desktop, there should be a way to configure what happens when Brave launches

## Feature Overview
User should be able to pick between a few options:
- *Open the New Tab page* opens a blank new tab on launch
- *Continue where you left off* (default) current behavior of storing what tabs were opened and reloading them
- *Open a specific page or set of pages* be able to specify a page that loads on startup

## Design
Example from Desktop
![image](https://user-images.githubusercontent.com/4733304/101517952-295e5f80-3936-11eb-8328-8d1581626cb7.png)

**Comment by iccub** [comment]
No other iOS mobile browser offers this afaik, i checked the most popular ones

**Comment by iccub** [comment]
I will close it for now, it's a very niche request for a mobile browser it seems
