### ISSUE TITLE
Shield stat counter should only increase by 1 for each unique URL blocked

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3127]
Currently if Brave blocks a URL from a web page and that web page then attempts to reload said URL it will count as 2 blocks instead of 1 which is how desktop's count functions.

We should instead only increment the count of the blocked resources based on unique URLs blocked to match desktop

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.23(21.2.11.13)
- Verified starts counter only counts unique URL's blocked

1.22 | 1.23
-- | --
![image](https://user-images.githubusercontent.com/17010094/107658329-edb97c00-6c7d-11eb-85cd-892627061e26.png) | ![image](https://user-images.githubusercontent.com/17010094/107658344-f1e59980-6c7d-11eb-9276-f1f2349efd68.png)

------
Verification passed on iPhone 7+with iOS 14.4 running 1.23(21.2.11.13)
- Verified starts counter only counts unique URL's blocked

1.22 | 1.23
-- | --
![image](https://user-images.githubusercontent.com/17010094/107659182-c7481080-6c7e-11eb-87f2-5feb80050857.png) | ![image](https://user-images.githubusercontent.com/17010094/107659189-cd3df180-6c7e-11eb-83af-e3923d372fb6.png)

-------
Verification passed on iPhone XR with iOS 12.4.1 running 1.23(21.2.11.13)
- Verified starts counter only counts unique URL's blocked

1.22 | 1.23
-- | --
![image](https://user-images.githubusercontent.com/17010094/107659591-33c30f80-6c7f-11eb-8811-36d1811d435a.png) | ![image](https://user-images.githubusercontent.com/17010094/107659607-37569680-6c7f-11eb-9d98-f6be3f76d37b.png)
