### ISSUE TITLE
Update Brave Today intro card copy

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3131]
Ref: https://github.com/brave/brave-browser/issues/13100

Make a stronger connection between the feature name and introductory card on Brave Today.

**Comment by kjozwiak** [comment]
@karenkliu is the following the correct design? The text/summary is the as per https://github.com/brave/brave-browser/issues/13100#issue-759879071 & https://www.figma.com/file/wpjvatVQQvOtC96WaPCw86/Desktop-Brave-Today?node-id=0%3A1 but wanted to double check before QA starts running through the various iOS versions.

![image](https://user-images.githubusercontent.com/2602313/107460793-c3a17600-6b26-11eb-875d-c060d7f47804.png)

**Comment by karenkliu** [comment]
@kjozwiak Yes that is correct. The graphic at the top should also be a Lottie animation (I think this is already implemented). There's no auto-dismiss on this card since we provide a close button.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 14.4` using `1.23 (21.2.10.18)`

* ensured that the lottie animation works on the intro card works as expected
* ensured that the intro card isn't being auto-dismissed
* ensured that taping on `X` closes the intro card and doesn't re-appear (also restarted Brave several times)
* ensured that once dismissed, the intro card is removed from other currently opened NTP
* ensured that intro card doesn't re-appear when disabling/enabling Brave Today
* ensured that `Learn more about your data` opens https://brave.com/privacy/browser/#brave-today
* ensured that `Sources & Settings` opens the `Brave Today` source selection (with the option to disable Brave Today)

![IMG_3589](https://user-images.githubusercontent.com/2602313/107604366-f8343100-6bfd-11eb-90d6-8d9387df67b0.png)

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.4` using `1.23 (21.2.10.18)`

* ensured that the lottie animation works on the intro card works as expected
* ensured that the intro card isn't being auto-dismissed
* ensured that taping on `X` closes the intro card and doesn't re-appear (also restarted Brave several times)
* ensured that once dismissed, the intro card is removed from other currently opened NTP
* ensured that intro card doesn't re-appear when disabling/enabling Brave Today
* ensured that `Learn more about your data` opens https://brave.com/privacy/browser/#brave-today
* ensured that `Sources & Settings` opens the `Brave Today` source selection (with the option to disable Brave Today)

![IMG_0249](https://user-images.githubusercontent.com/2602313/107604888-7513da80-6bff-11eb-9754-f1a4a4e1a685.png)

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.23 (21.2.10.18)`

* ensured that the lottie animation works on the intro card works as expected
* ensured that the intro card isn't being auto-dismissed
* ensured that taping on `X` closes the intro card and doesn't re-appear (also restarted Brave several times)
* ensured that once dismissed, the intro card is removed from other currently opened NTP
* ensured that intro card doesn't re-appear when disabling/enabling Brave Today
* ensured that `Learn more about your data` opens https://brave.com/privacy/browser/#brave-today
* ensured that `Sources & Settings` opens the `Brave Today` source selection (with the option to disable Brave Today)

![IMG_0490](https://user-images.githubusercontent.com/2602313/107606032-d5f0e200-6c02-11eb-946a-f851d9b0b01d.png)

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.23 (21.2.10.18)`

* ensured that the lottie animation works on the intro card works as expected
* ensured that the intro card isn't being auto-dismissed
* ensured that taping on `X` closes the intro card and doesn't re-appear (also restarted Brave several times)
* ensured that once dismissed, the intro card is removed from other currently opened NTP
* ensured that intro card doesn't re-appear when disabling/enabling Brave Today
* ensured that `Learn more about your data` opens https://brave.com/privacy/browser/#brave-today
* ensured that `Sources & Settings` opens the `Brave Today` source selection (with the option to disable Brave Today)

![IMG_0148](https://user-images.githubusercontent.com/2602313/107606217-6d563500-6c03-11eb-8b9d-6c7a795fe2d8.png)

**Comment by kjozwiak** [comment]
Ran into and created https://github.com/brave/brave-ios/issues/3290 & https://github.com/brave/brave-ios/issues/3292 when running through the above.
