### ISSUE TITLE
Implement GPC (dom only) - Part 1

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#3133]
From: https://github.com/brave/brave-browser/issues/11917

Add a navigator.globalPrivacyControl end point in the DOM, that always returns true (boolean, not string). No UX or shields integration is needed. No state is set or maintained.

## Test Case

Navigate to https://webtest-pj.herokuapp.com/gpc.html and verify that navigator.globalPrivacyControl is true for both the mainframe and the iframe.

**Comment by kylehickinson** [comment]
~@jumde If there is a way to test this can you add a test flow for QA?~ Never mind, I see it in the PR :)

**Comment by jumde** [comment]
> ~@jumde If there is a way to test this can you add a test flow for QA?~ Never mind, I see it in the PR :)

Thanks for updating the description.

**Comment by kjozwiak** [comment]
@jumde @kylehickinson assuming this should be closed?

**Comment by iccub** [comment]
No @kjozwiak, we will merge it and close today, need formal decision from our product team whether we include it in next minor release, and yesterday there was a US holiday

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.3 running 1.22.2(21.1.19.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3203   
  <img width=100 src=https://user-images.githubusercontent.com/17010094/105145710-03140e00-5af7-11eb-8d47-8aa99834b457.png>

---------------
Verification passed on iPhone XR  with iOS 13.5 running 1.22.2(21.1.19.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3203   
  <img width=100 src=https://user-images.githubusercontent.com/17010094/105150475-b9c6bd00-5afc-11eb-806a-46c2bcf54e85.png>

---------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.22.2(21.1.19.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3203   
  <img width=100 src=https://user-images.githubusercontent.com/17010094/105150492-be8b7100-5afc-11eb-8af4-4c783fff0b9e.png>
  
---------------

Verification **PASSED** on `iPad Mini 4` on `iOS 13.7` using `1.22.2 (21.1.21.11)`

* Verified the STR/Cases outlined via https://github.com/brave/brave-ios/issues/3133#issue-760587407 & https://github.com/brave/brave-ios/pull/3203#issue-555936262 and ensured that `navigator.globalPrivacyControl` is `true` for both the mainframe and the iframe as per the follownig:

**`Standard Tab`** | **`Private Tab`**
--------------------|-------------------
![IMG_0413](https://user-images.githubusercontent.com/2602313/105403043-35586500-5bf6-11eb-9234-45621ecbbc61.png) | ![IMG_0414](https://user-images.githubusercontent.com/2602313/105403052-38ebec00-5bf6-11eb-9d03-52bcecfc6ad1.png)
