### ISSUE TITLE
Editing a bookmark or folder, puts it at the bottom of the list

### ISSUE THREAD

**Issue by parsd51** [brave/brave-ios#3137]
### Description: 
Editing a bookmark or folder, puts it at the bottom of the list, when only name or url is changed.

I might have seen a report or fix of this issue, but I cannot find it.

### Steps to Reproduce 
  1. Edit a folder or bookmark which is not at the bottom of the list.
  2. Change the name and/or url
  3. Press save

**Actual result:**
Folder or bookmark is located at the bottom.

**Expected result:**
Folder or bookmark keep the position in the list

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy, 100%

**Brave Version:** 
1.22 (20.12.2.0) released version

**Device details:** 
iPad Air 2, iPadOS 14.2

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information
Around 1400 bookmarks (might not matter here)

**Comment by parsd51** [comment]
Same problem occurs for me with 1.22.1

Can you reproduce the problem?

**Comment by iccub** [comment]
We fixed it @parsd51, thanks for your report.
The fix should go live in next release, 1.23

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 11` running `iOS 14.4` using `1.23 (21.2.5.15)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.4` using `1.23 (21.2.5.15)`
* Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.23 (21.2.5.15)`
* Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.23 (21.2.5.15)`

STR/Cases used for the above platforms:

* ensured that editing `Folders` correctly retains the same order/position after saving changes
* ensured that editing `Bookmarks` correctly retains the same order/position after saving changes
