### ISSUE TITLE
Final Brave Rewards transfer

### ISSUE THREAD

**Issue by Greigh** [brave/brave-ios#3138]
### Description: 
With Version 1.22 (20.12.02.00), Brave will not let me transfer to my Desktop Wallet for my final transfer. My guess this is happening because I have a Uphold wallet connected to my browser. 

**Expected result:**
Able to scan a QR code or possibly even the wallet recovery key to my Desktop browser. 

**Brave Version:** 
Version 1.22 (20.12.02.00)
Device iPhone13,4 (iOS 14.2.1)

Desktop:
Version 1.18.70 Chromium: 87.0.4280.101 (Official Build) (x86_64 translated)

**Comment by iccub** [comment]
Final transfer will happen in next iOS release 1.22.1, next desktop build should add the qr code functionality as well

we had to submit 1.22 first to comply with Apple guidelines, we hope to deliver it next week

**Comment by Greigh** [comment]
@iccub Perfect. Thank you for your response! I was super confused.

I am really sorry Apple cracked down on your awesome business platform.
