### ISSUE TITLE
Custom search engine

### ISSUE THREAD

**Issue by GPConnect** [brave/brave-ios#3145]
## Problem Description 
No custom engine option !
## Feature Overview 
Add ability to enter custom search engine !
## Implementation Details 
Will be great if user could enter they own search engine url instead of what provided ! 
##User Experience 

   1. 
   2. 
   3.

**Comment by bsclifton** [comment]
Thanks for the report @GPConnect - I think we'll have this covered by https://github.com/brave/brave-ios/issues/936 where folks can set their search engine to any that implement the OpenSearch spec
