### ISSUE TITLE
Cant Restore My Purchase And Couldnt Connect To VPN

### ISSUE THREAD

**Issue by bluelouie74** [brave/brave-ios#3154]
### Description: 
Cant restore my subscription ive cancelled and re did it still wont work

### Steps to Reproduce 
  1.deleted app
  2.cancelled and re applied for sub
  3.reset phone

**Actual result:** 
Still does not restore

**Expected result:**
Vpn and brave work back normal

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
@bluelouie74 going to close this off but please re-open a new issue if you're still having issues.
