### ISSUE TITLE
[upstream/firefox-ios] #1649160 - RTLO Downloads

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#3155]
https://bugzilla.mozilla.org/show_bug.cgi?id=1649160

## Test Plan
Specified here: https://github.com/brave/brave-ios/pull/3156

**Comment by iccub** [comment]
@jumde does it require QA tests? please add `QA/Yes or NO` label

**Comment by jumde** [comment]
@iccub - Updated

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 11` running `iOS 14.4` using `1.23 (21.2.5.15)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.4` using `1.23 (21.2.5.15)`
* Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.23 (21.2.5.15)`
* Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.23 (21.2.5.15)`

Verification notes can be found via https://github.com/brave/internal/issues/743#issuecomment-776419658.
