### ISSUE TITLE
Small Typo ("Trasfer")

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ios#3163]
https://github.com/brave/brave-ios/blob/1865f35683ae2f2ab048f16bba6dff96addb11fe/BraveShared/BraveStrings.swift#L1655

## Test Case

- Complete wallet transfer via QR code
- On completion modal, copy should read `Balance transfer has initiated` instead of `Balance trasfer has initiated`

**Comment by iccub** [comment]
@kylehickinson can you add a test plan for it? 
Just to tell QA where to navigate to see this text

**Comment by kylehickinson** [comment]
Done

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.3 running 1.22.2(21.1.19.18)
- Verified incorrect text is fixed
  <img width=300 src=https://user-images.githubusercontent.com/17010094/105190000-78023a80-5b2d-11eb-82bd-327db5a9e479.png>

-----

Verification passed on the following devices running 1.22.2(21.1.20.17)
- Verified incorrect text is fixed

iPad Pro(iOS 14.3) | iPad Pro (iOS 12.4.1) | iPhone XR (iOS 13.5)
-- | -- | --
<img width=500 src=https://user-images.githubusercontent.com/17010094/105317463-1fc54a00-5bba-11eb-9dec-c8aef13ad7e3.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/105317481-2653c180-5bba-11eb-8b2f-43abab53beba.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/105318012-e214f100-5bba-11eb-82f8-92c0d5098d4b.png>

---

Verification **PASSED** on `iPad Mini 4` on `iOS 13.7` using `1.22.2 (21.1.21.11)`

* ensured that the `Trasfer` error was corrected and there was no other spelling/grammar issues within the modal.

<p align="center">
<img src="https://user-images.githubusercontent.com/2602313/105397717-697c5780-5bef-11eb-8446-19483761cb40.png" width=300>
</p>
