### ISSUE TITLE
iOS QR code scan not working to transfer Brave Rewards to desktop

### ISSUE THREAD

**Issue by KZFlyer** [brave/brave-ios#3165]
Could not find this specific issue.

### Description: 
When scanning QR code on desktop screen, the following error occurs:
Connection Error
The Brave Rewards server did not 
respond. Please try again in a moment. 
(1)

### Steps to Reproduce 
  1. Tap on Brave Rewards Triangle on Brave iOS
  2. Select Legacy Wallet Transfer - QR Code Reader opens
  3. On Desktop Brave, navigate to Brave Rewards
  4. Select QR Code for iOS Rewards users transferring BAT
  5. QR Code is displayed on screen
  6. Align QR Code within the outline on the iOS screen.
  7. Receive error message

**Actual result:** 
See screen shot

**Expected result:**
Should begin process to transfer BAT from iOS to desktop

**Reproduces how often:** Easily reproduced, error appears at each attempt

**Brave Version:** 
Desktop: Version 1.18.75 Chromium: 87.0.4280.101 (Official Build) (64-bit)
iOS: Version 1.22.1 (20.12.10.23)

**Device details:** 
iPhone 11 iOS 14.4 beta
Desktop is running Windows 10 Pro Build 19041.685

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 
N/A

### Additional Information
Attempted multiple times over the next couple of hours and same error each time. Restarted phone, computer, did not solve.

![Brave Rewards Error](https://user-images.githubusercontent.com/39107717/103183076-568b9700-487e-11eb-8e93-70a76ba5f24e.jpg)

**Comment by Brave-Matt** [comment]
@KZFlyer,
Thank you for opening this issue. We have additional users encountering it as well:
https://community.brave.com/t/why-can-t-i-sync-my-ios-wallet-to-my-laptop/190644/2

**Comment by eduardoturconi** [comment]
For me it never showed an option for moving my BAT. What should I do?

**Comment by bbeale** [comment]
> @KZFlyer,
> Thank you for opening this issue. We have additional users encountering it as well:
> https://community.brave.com/t/why-can-t-i-sync-my-ios-wallet-to-my-laptop/190644/2

Experiencing the same issue. Followed all of the troubleshooting steps in the community thread. 

![IMG_0031](https://user-images.githubusercontent.com/9686813/105118689-e814b000-5a9c-11eb-9e5c-cbc0fed877c9.PNG)

**Comment by iccub** [comment]
Let's close it as stale now, most users should have transferred already
