### ISSUE TITLE
[hackerone] #1068505 - URL parsing issue

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#3168]
https://hackerone.com/bugs?report_id=1068505

## Test Plan
Specified here: https://github.com/brave/security/issues/280

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 11` running `iOS 14.4` using `1.23 (21.2.5.15)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.4` using `1.23 (21.2.5.15)`
* Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.23 (21.2.5.15)`
* Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.23 (21.2.5.15)`

Verification notes can be found via https://github.com/brave/security/issues/280#issuecomment-776412831.
