### ISSUE TITLE
Re-style error interstitials (bad SSL, etc.)

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#317]
As mentioned during discussion around #268 

https://github.com/brave/brave-ios/issues/268#issuecomment-426379195:
> Ideally, we should re-style this page (all error insterstitials) to match @rossmoody's updated error page designs for desktop

<img width="437" alt="50178478-78c6a380-02b9-11e9-9db2-360a875cf0e4" src="https://user-images.githubusercontent.com/2781690/54530626-ac1cdb00-4959-11e9-884f-b6a2be06a623.png">

**Comment by jhreis** [comment]
We will deal with this sometime after 1.7, for now we'll just go with a simply copy change to "Brave" it, for now (https://github.com/brave/brave-ios/issues/361).

**Comment by iccub** [comment]
will be handled in https://github.com/brave/brave-ios/issues/4338
