### ISSUE TITLE
High input lag when typing in url bar.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3171]
### Steps to Reproduce 
  1. Open url bar
  2. Start typing quickly
  3.

**Actual result:** 
Notice how slow it is

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by ryanbugden** [comment]
I'm experiencing this issue.
