### ISSUE TITLE
'Clear' does not show up in url bar when autocompletion is available

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3172]
### Steps to Reproduce 
  1. Visit wikipedia once
  2. Tap on url bar, type `w` start typing the wikipedia url
  3. See that url autocompleted but there is no clear button at the end of it

**Actual result:** 
Clear button is hidden

![IMG_42AA03BEFFA3-1](https://user-images.githubusercontent.com/6950387/103658264-45701380-4f6b-11eb-8e3a-eb8c3a1048b4.jpeg)

**Expected result:**
Should be visible

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.23(21.1.28.17)
- Verified clear button shows up in URL bar when autocompletion is available
![image](https://user-images.githubusercontent.com/17010094/106613138-c79b2a00-6561-11eb-9114-3297e5293933.png)

------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.23(21.1.28.17)
- Verified clear button shows up in URL bar when autocompletion is available
![image](https://user-images.githubusercontent.com/17010094/106620194-3c259700-6569-11eb-97c0-4663396acae4.png)

------------
Verification passed on iPhone 7+ with iOS 14.4running 1.23(21.1.28.17)
- Verified clear button shows up in URL bar when autocompletion is available
![image](https://user-images.githubusercontent.com/17010094/106620174-38921000-6569-11eb-94fa-d799ed977a37.png)
