### ISSUE TITLE
Updated pre-populated search engine list

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3177]
Follow desktop https://github.com/brave/brave-browser/issues/13283

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.3 running 1.22.2(21.1.19.18)

<details>
<summary><b>Scenario 1: Clean Install</b></summary>

- Verified on a clean install `Ecosia` is shown in the list of SE during onboarding
- Verified selecting `Ecosia` sets it as default for both normal and private tab
- Verified skipping onboarding doesn't set `Ecosia` as default
- Verified `Ecosia` is shown in the quick search list on the keyboard when typing into the URL bar
- Verified `Ecosia` is enabled by default for quick search engines

Onboarding | Quick Search Engine | Quick Search settings (With Ecosia) | Quick Search Settings (Ecosia as default) | 
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105168720-6a8b8700-5b12-11eb-9b7d-6bb0f91af5d6.png) | ![image](https://user-images.githubusercontent.com/17010094/105168823-93ac1780-5b12-11eb-84b2-74d7f3f20e44.png) |<img src=https://user-images.githubusercontent.com/17010094/105168942-b9392100-5b12-11eb-8d3d-25399954ab09.png>|<img src=https://user-images.githubusercontent.com/17010094/105168958-c1915c00-5b12-11eb-97b1-fbcf0bafa260.png> |

<details>
<summary><b>Supported Regions</b></summary>

**USA**

Onboarding | Default SE | Quick SE
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105183106-b4319d00-5b25-11eb-987d-8c81795d1185.png) | ![image](https://user-images.githubusercontent.com/17010094/105183195-cdd2e480-5b25-11eb-8484-525dad2be569.png) | ![image](https://user-images.githubusercontent.com/17010094/105183129-b8f65100-5b25-11eb-8e5a-ecb8d473f423.png)

**UK**

Onboarding | Default SE | Quick SE
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105183106-b4319d00-5b25-11eb-987d-8c81795d1185.png) | ![image](https://user-images.githubusercontent.com/17010094/105183195-cdd2e480-5b25-11eb-8484-525dad2be569.png) | ![image](https://user-images.githubusercontent.com/17010094/105183129-b8f65100-5b25-11eb-8e5a-ecb8d473f423.png)

**France** - `Qwant` is default

Onboarding | Default SE | Quick SE
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105183007-9c5a1900-5b25-11eb-83fa-2dc0e9429b6f.png) | ![image](https://user-images.githubusercontent.com/17010094/105183030-a24ffa00-5b25-11eb-8b01-b29e28b46b23.png) | ![image](https://user-images.githubusercontent.com/17010094/105183046-a67c1780-5b25-11eb-9be0-ea1247be2441.png)

**Germany** - `DuckDuckGo` is default

Onboarding | Default SE | Quick SE
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105183457-20ac9c00-5b26-11eb-90a6-d57341ba3b9b.png) | ![image](https://user-images.githubusercontent.com/17010094/105183466-23a78c80-5b26-11eb-91c9-043d7990fd60.png) | ![image](https://user-images.githubusercontent.com/17010094/105183477-273b1380-5b26-11eb-81db-2929e1071470.png)

**Netherlands**  - Translations not available shows everything in English 

Onboarding | Default SE | Quick SE
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105183912-a9c3d300-5b26-11eb-8241-d1a82128e662.png) | ![image](https://user-images.githubusercontent.com/17010094/105183934-ae888700-5b26-11eb-94c7-c6457c693111.png) | ![image](https://user-images.githubusercontent.com/17010094/105183971-b6482b80-5b26-11eb-9a3d-6f37854883e1.png)

**Belgium** - Translations not available shows everything in English 

Onboarding | Default SE | Quick SE
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105183912-a9c3d300-5b26-11eb-8241-d1a82128e662.png) | ![image](https://user-images.githubusercontent.com/17010094/105183934-ae888700-5b26-11eb-94c7-c6457c693111.png) | ![image](https://user-images.githubusercontent.com/17010094/105183971-b6482b80-5b26-11eb-9a3d-6f37854883e1.png)

**Switzerland**

Onboarding | Default SE | Quick SE
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105184812-b137ac00-5b27-11eb-93e5-db85b007245c.png) | ![image](https://user-images.githubusercontent.com/17010094/105184831-b5fc6000-5b27-11eb-9e14-a0931d9b38ef.png) | ![image](https://user-images.githubusercontent.com/17010094/105184846-bbf24100-5b27-11eb-95b6-4831e2487fc3.png)

**Sweden**

Onboarding | Default SE | Quick SE
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105184956-df1cf080-5b27-11eb-97aa-9878cf205029.png) |![image](https://user-images.githubusercontent.com/17010094/105185617-a2052e00-5b28-11eb-8344-2c2e0ea17f23.png) | ![image](https://user-images.githubusercontent.com/17010094/105184979-e643fe80-5b27-11eb-94d9-0d129475da82.png)

- Verified non-supported regions `Ecosia` is not added in the default list during onboarding nor shown in the list of Quick search engines

**Canada**

Onboarding | Quick SE list | Default list
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105185798-e42e6f80-5b28-11eb-8b28-e204e88831ce.png) | ![image](https://user-images.githubusercontent.com/17010094/105185810-e7c1f680-5b28-11eb-8e19-655d7c3d1ebd.png) | ![image](https://user-images.githubusercontent.com/17010094/105185820-ea245080-5b28-11eb-8be2-8758f25161dd.png)

</details>
</details>
<details>
<summary><b>Scenario 2: Upgrade Install</b></summary>

- Verified setting Yahoo as default on `1.22` build and upgrading to `1.22.2` adds `Ecosia` to the list
- Verified setting Google as default on `1.22` build and upgrading to `1.22.2` adds `Ecosia` to the list but doesn't remove `Yahoo` from the list of default search engines 

</details>
<details>
<summary><b>Scenario 3: Referral code</b></summary>

- Verified performing a search using Ecosia quick engine or as default adds `tt=d188c5da` referral code mentioned in https://github.com/brave/internal/wiki/Search-engine-integrations
- Verified visiting `https://ecosia.org` and performing a search doesn't append referral code to the URL 

Referral code | No Referral Code
-- | --
 ![image](https://user-images.githubusercontent.com/17010094/105168768-7d9e5700-5b12-11eb-8b53-1355e4d4481a.png) | ![image](https://user-images.githubusercontent.com/17010094/105169912-1bdeec80-5b14-11eb-8f80-f7c7b2ca83fa.png)

</details>

----------------

Verification passed on iPhone XR with iOS 13.5 running 1.22.2(21.1.19.18)

<details>
<summary><b>Scenario 1: Clean Install</b></summary>

- Verified on a clean install `Ecosia` is shown in the list of SE during onboarding
- Verified selecting `Ecosia` sets it as default for both normal and private tab
- Verified skipping onboarding doesn't set `Ecosia` as default
- Verified `Ecosia` is shown in the quick search list on the keyboard when typing into the URL bar
- Verified `Ecosia` is enabled by default for quick search engines

Onboarding | Default Search Engine | Quick Search 
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105204417-0b426c80-5b3c-11eb-825e-df290754aea2.png) | ![image](https://user-images.githubusercontent.com/17010094/105204430-0e3d5d00-5b3c-11eb-8e9a-51cd6659427d.png) | ![image](https://user-images.githubusercontent.com/17010094/105204437-11384d80-5b3c-11eb-9e75-aeb3d64309ad.png)

<details>
<summary><b>Supported Regions</b></summary>

**USA**

Onboarding | Default SE | Quick SE
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105198166-48efc700-5b35-11eb-8402-d1752fd7273d.png) | ![image](https://user-images.githubusercontent.com/17010094/105198212-56a54c80-5b35-11eb-92e8-6d8fc3262272.png) | ![image](https://user-images.githubusercontent.com/17010094/105198185-4db47b00-5b35-11eb-8062-90e2916d684e.png)

**UK**

Onboarding | Default SE | Quick SE
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105198166-48efc700-5b35-11eb-8402-d1752fd7273d.png) | ![image](https://user-images.githubusercontent.com/17010094/105198212-56a54c80-5b35-11eb-92e8-6d8fc3262272.png) | ![image](https://user-images.githubusercontent.com/17010094/105198185-4db47b00-5b35-11eb-8062-90e2916d684e.png)

**France** - `Qwant` is default

Onboarding | Default SE | Quick SE
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105203055-90c51d00-5b3a-11eb-8c41-c451540e484e.png) | ![image](https://user-images.githubusercontent.com/17010094/105203047-8dca2c80-5b3a-11eb-99d5-fd0e55c6918a.png) | ![image](https://user-images.githubusercontent.com/17010094/105203033-899e0f00-5b3a-11eb-810e-3075b54af618.png)

**Germany** - `DuckDuckGo` is default

Onboarding | Default SE | Quick SE
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105203016-830f9780-5b3a-11eb-85de-9ee184dcb8cb.png) | ![image](https://user-images.githubusercontent.com/17010094/105203006-7f7c1080-5b3a-11eb-99b9-e0a88e55be84.png) | ![image](https://user-images.githubusercontent.com/17010094/105203001-7c812000-5b3a-11eb-8338-10fb1c264f55.png)

**Netherlands**  - Translations not available shows everything in English 

Onboarding | Default SE | Quick SE
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105202968-725f2180-5b3a-11eb-9da6-6784d22d5975.png) | ![image](https://user-images.githubusercontent.com/17010094/105202946-6c694080-5b3a-11eb-9938-f9de242b9916.png) | ![image](https://user-images.githubusercontent.com/17010094/105202957-6f643100-5b3a-11eb-8f40-cd4ec4a346ae.png)

**Belgium** - Translations not available shows everything in English 

Onboarding | Default SE | Quick SE
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105202968-725f2180-5b3a-11eb-9da6-6784d22d5975.png) | ![image](https://user-images.githubusercontent.com/17010094/105202946-6c694080-5b3a-11eb-9938-f9de242b9916.png) | ![image](https://user-images.githubusercontent.com/17010094/105202957-6f643100-5b3a-11eb-8f40-cd4ec4a346ae.png)

**Switzerland**

Onboarding | Default SE | Quick SE
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105202863-53f92600-5b3a-11eb-9491-488b076a2e4a.png) | ![image](https://user-images.githubusercontent.com/17010094/105202881-58bdda00-5b3a-11eb-9a89-9881e361e7f5.png) | ![image](https://user-images.githubusercontent.com/17010094/105202870-55c2e980-5b3a-11eb-8bce-7a3bcf177148.png)


**Sweden**

Onboarding | Default SE | Quick SE
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105202380-d6cdb100-5b39-11eb-9727-0def4c9628db.png) | ![image](https://user-images.githubusercontent.com/17010094/105202412-dfbe8280-5b39-11eb-86b1-310e3df2b784.png) | ![image](https://user-images.githubusercontent.com/17010094/105202427-e3520980-5b39-11eb-8a2b-e5d176bc54ad.png)

- Verified non-supported regions `Ecosia` is not added in the default list during onboarding nor shown in the list of Quick search engines

**Canada**

Onboarding | Default list | Quick SE list 
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105203540-25c81600-5b3b-11eb-865f-ef3d7ad03f7f.png) | ![image](https://user-images.githubusercontent.com/17010094/105203552-29f43380-5b3b-11eb-93c0-ce1489b5065c.png) | ![image](https://user-images.githubusercontent.com/17010094/105203611-3b3d4000-5b3b-11eb-8fd0-4fa38e56e039.png)

</details>
</details>
<details>
<summary><b>Scenario 2: Upgrade Install</b></summary>

- Verified setting Yahoo as default on `1.22` build and upgrading to `1.22.2` adds `Ecosia` to the list
- Verified setting Google as default on `1.22` build and upgrading to `1.22.2` adds `Ecosia` to the list but doesn't remove `Yahoo` from the list of default search engines 

</details>
<details>
<summary><b>Scenario 3: Referral code</b></summary>

- Verified performing a search using Ecosia quick engine or as default adds `tt=d188c5da` referral code mentioned in https://github.com/brave/internal/wiki/Search-engine-integrations
- Verified visiting `https://ecosia.org` and performing a search doesn't append referral code to the URL 

Referral code | No Referral Code
-- | --
![image](https://user-images.githubusercontent.com/17010094/105199984-44c4a900-5b37-11eb-90e0-35bc78253949.png) | ![image](https://user-images.githubusercontent.com/17010094/105200000-49895d00-5b37-11eb-8c1a-55775745b9e1.png)

</details>

-----------
