### ISSUE TITLE
Persist Private Tabs on Exit

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3183]
### Description: 
Context: https://twitter.com/Legen_darium/status/1347605629712666631?s=20

Provide an option to keep private tabs when the user exits the browser. 

The default will be off in that the current behavior is retained, but a user can change this should they wish.

**Suggested Location**

Brave Shields & Privacy
_under block dangerous sites_

add

Retain Private tabs on exit (On/Off toggle). - default off

@jamesmudgett to review before dev work begins.

**Comment by ttang4299** [comment]
Hi @iccubI, any updates on this? I remember you mentioned that this feature would come next after tab sync, and I noticed tab sync being added a few updates back.

**Comment by ttang4299** [comment]
Hi @iccub  , any updates on this? I remember you mentioned that this feature would come next after tab sync, and I noticed tab sync being added a few updates back.

**Comment by iccub** [comment]
Yes @ttang4299, so we've hit some roadblocks, especially when it comes to having multiple windows with private mode or private-only-browsing mode. The rewrite is bigger than expected, at the moment there's no clear timeline for it.
Maybe I will try to push for a more simplified version without perfect handling of private modes

**Comment by notDavid** [comment]
Note that currently Private Tabs are also cleared when temporarily switching to the "non-private tabs" and then back to "private" tabs. Very annoying... 😊

Also, they are cleared at random, when switching between apps, or the app is updated i think.

PS. The [Tweet/context](https://github.com/brave/brave-ios/issues/3183#issue-782424801) no longer exists i think.

**Comment by mailinglists35** [comment]
> Also, they are cleared at random, when switching between apps

I also noticed this as well when switching apps.
Despite having set "clear tabs after one month", many times (under iOS memory pressure I presume?) all tabs get discarded. Config set to private browsing only.

But maybe this should be it's own issue?

**Comment by iccub** [comment]
Private browsing always clear data when the app is killed or if the device is out of memory.
We work on making them persistent and let the user choose their behavior

**Comment by iccub** [comment]
Fixed in https://github.com/brave/brave-ios/pull/7575

**Comment by Uni-verse** [comment]
Verified on `iPhone` per https://github.com/brave/brave-ios/issues/7855#issuecomment-1684482570
