### ISSUE TITLE
Rename "Private Mode" to "Forget Mode"

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3184]
### Description: 

Slack Thread: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1610142590004700

Private Mode can be confusing and we want to help clear up this confusion for users. 

Please rename: 
- [ ] "Private Browsing Only" to "Forget Mode Only"
- [ ] "New Private Tab: to "Forget Mode Tabs" 
- [ ] In the existing Private Mode, rename the "Private" button on the bottom right to "Forget Mode"
- [ ] In the existing Normal Mode, rename the "Private" button on the bottom right to "Forget Mode"
- [ ] On the NTP of the existing Private Mode, change Private Tabs to Forget Mode Tabs - @jumde may need to review this text

Please scan other translations for word "Private" and decide if they should be updated to "Forget Mode".

**Comment by diracdeltas** [comment]
this sounds fine to me but we may want to make a support page called "what is forget mode?" and link to it in the settings
