### ISSUE TITLE
Some pdf sharing problems 

### ISSUE THREAD

**Issue by parsd51** [brave/brave-ios#3185]
Yes. There are similar reports, but I’m not sure they will fix below.

### Description: 
Some pdf sharing problems 

### Steps to Reproduce 
1. Open (just an example):
https://www.trm.dk/media/5076/anlaegsstatus-2-halvaar-2020.pdf

2. Press ... and then Share with..

3a. Press copy and paste to Archives
3b. N/A
3c. N/A
3d. Press find in page and do a search for an existing text string.

**Actual result:** 
4a. A text file with the url is pasted in Archives.
4b. Not an option.
4c. Not an option
4d. No match is found in the pdf file.

**Expected result:**
5a. Pressing copy “should” copy the file. If it’s intended for url copy, there is no possibility to directly save the file to the “file system”, except adding Archives like in #5b.
5b. Possibility to save to Archives
5c. Possibility to open with a file browser, like FileBrowser
5d. Find in page find a matching text string

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy, 100%

**Brave Version:** 
1.22.1

**Device details:** 
iPad Air 2, iPadOS 14.3

**Website problems only:**
- did you check with Brave Shields down? Yes
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information
I noticed the problems with pdf files, but it might also be a problem with other file types.

**Comment by soner-yuksel** [comment]
Yes this issue also covers the problem mentioned https://github.com/brave/brave-ios/issues/2961 and will be fixed with 1.23
