### ISSUE TITLE
Prior scheduled grant reminders appearing

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3186]
Grant reminders that were previously scheduled before 1.21 were accidentally left scheduled causing them to appear despite there being no UI to claim a grant anymore.

Test Case:
- Install old version of Brave (1.20 for instance), view an ad
- Update to a dev build that includes this fix
- Follow usual testing flow to make ad grant reminder appear (change date on phone)
- Verify that Ad grant reminder does not appear

**Comment by srirambv** [comment]
Marking as QA/No based on discussion https://bravesoftware.slack.com/archives/C06UXF3KJ/p1613037920107500
