### ISSUE TITLE
Support Rewards Everywhere

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3188]
Adds support for Rewards Everywhere on iOS through 1.19.x brave-core update.

iOS UI is simplified compared to desktop so changes are minor:

- Wallet is created by default without user enabling rewards
  - Ads are not enabled when a wallet is created, user must toggle Rewards on via panel or settings

The toggle is still the same functionality minus enabling/disabling Rewards as a whole. Toggled on = Ads & AC on instead of Ledger & Ads & AC on

**Comment by kylehickinson** [comment]
As of #3405, wallet is no longer created on launch, and is reserved until the user enables rewards, therefore this can be marked as `QA/No` as there is no user-facing change to be tested. Basic Rewards will be tested with 1.21.x bump and manual passes

**Comment by LaurenWags** [comment]
@kylehickinson should we also remove this one from release notes as well?

**Comment by kylehickinson** [comment]
Yeah thats a good idea :) Done
