### ISSUE TITLE
Quick search engines do not appear if <2 quick search engines enabled

### ISSUE THREAD

**Issue by mrmikeface** [brave/brave-ios#3190]
### Description: 
Quick search does not appear if there only one "Quick-Search Engine" toggled on

### Steps to Reproduce 
  1. Turn off all but one quick search engine in search settings
  2. Open address bar

**Actual result:** No quick search bar appears above keyboard

**Expected result:** Appearance of quick search bar

**Reproduces how often:** Easily reproduced

**Brave Version:** 1.22.1 (20.12.10.23)

**Device details:** iPhone Xs (iOS 14.3)-->

**Website problems only:** Not website related

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.35 (22.1.24.16)`
* Verification **PASSED** on `iPhone 11` running `iOS 14.7.1` using `1.35 (22.1.24.16)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.7.1` using `1.35 (22.1.24.16)`

Verifications were completed via https://github.com/brave/brave-ios/issues/3959#issuecomment-1020426927 which also covers the case mentioned via https://github.com/brave/brave-ios/issues/3190#issue-784539750.
