### ISSUE TITLE
Update PIN key modal text to be visible

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#3193]
### Description: 
Text in the PIN modal for WebAuthN is barely visible

**Actual result:** 
![Screen Shot 2021-01-12 at 3 39 45 PM](https://user-images.githubusercontent.com/1903815/104387725-909aa100-54ec-11eb-9394-85b82c5e0b5f.png)

**Expected result:**
Should be darker

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.22

**Device details:** 
iPhone 11 (iOS 14)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 14.4` using the following build:

```
1.24 (21.3.25.18)
```

**`5Ci Lighting`** | **`NFC`**
-------------------|--------------
![IMG_3617](https://user-images.githubusercontent.com/2602313/112555205-1b760280-8d9e-11eb-9462-fb5d1bf6981f.png) | ![IMG_3618](https://user-images.githubusercontent.com/2602313/112555221-2466d400-8d9e-11eb-971b-e16a8ac1694c.png)

-------

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using the following build:

```
1.24 (21.3.25.18)
```

![IMG_0158](https://user-images.githubusercontent.com/2602313/112555459-9b03d180-8d9e-11eb-9deb-54bc0193b025.png)

-------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.4` using the following build:

```
1.24 (21.3.25.18)
```

![IMG_0251](https://user-images.githubusercontent.com/2602313/112555886-6f351b80-8d9f-11eb-816e-385cbf17ba98.png)

----

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using the following build:

```
1.24 (21.3.25.18)
```

![IMG_0496](https://user-images.githubusercontent.com/2602313/112556005-b28f8a00-8d9f-11eb-934e-1c379f865bc8.png)
