### ISSUE TITLE
[Sync] Crash Deleting bookmarks

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#3194]
### Description: 
There is a crash that happens when deleting bookmarks when favIcon changes. This happens if Desktop deletes some bookmarks while iOS is on a sync chain (at least that's how it reproduced for me). iOS gets notified that a favIcon has changed and attempts to update the deleted bookmark in the UI. This causes a crash.

### Steps to Reproduce 
  1. Add iOS to a Desktop sync chain
  2. Delete lots of bookmarks while keeping iOS bookmarks screen open (fav-icon will update and it will crash)

**Actual result:** 
Crash

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Rare for me

**Brave Version:** 
Brave-Core 1.18.x

**Device details:** 
Tested on iPhone-X 14.

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.3 running 1.22.2(21.1.20.17)
- Verified steps from issue description and no crash when deleting bookmarks/folders
---------
Verification passed on iPhone XR with iOS 13.5 running 1.22.2(21.1.20.17)
- Verified steps from issue description and no crash when deleting bookmarks/folders
---------
Verification passed on iPad Pro with iOS 12.4.1 running 1.22.2(21.1.20.17)
- Verified steps from issue description and no crash when deleting bookmarks/folders
----
Verification **PASSED** on `iPad Mini 4` on `iOS 13.7` using `1.22.2 (21.1.21.11)`

* Verified STR/cases outlined via https://github.com/brave/brave-ios/issues/3194#issue-784679095 and ensured there was no crashes when deleting multiple bookmarks/folders from desktop while `Bookmarks` is opened on `iOS`
