### ISSUE TITLE
[Sync] Delete Other Devices Support

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#3195]
## Problem Description
Desktop added a feature to delete other devices. This feature was NOT added to iOS by accident.. so now iOS needs to support deleting other devices on the sync chain AND it needs to support being deleted by other devices.

## Implementation Details
- iOS should support being deleted from sync chain by other devices such as Desktop and Android.
- iOS should support deleting other devices from the sync chain (Desktop, Android, and other iOS devices).

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4 running 1.24(21.3.24.11)
- Verified remove device is shown when tapped on other devices 
- Verified remove confirmation is shown 
- Verified able to remove other devices from sync chain

![image](https://user-images.githubusercontent.com/17010094/112469809-ccaa7780-8d61-11eb-9d96-048b963dc5e8.png) | ![image](https://user-images.githubusercontent.com/17010094/112469815-d0d69500-8d61-11eb-8aa5-98cd1d01aa77.png)
-- | --

------------
Verification passed on iPhone 7+ with iOS 14.4 running 1.24(21.3.24.11)
- Verified remove device is shown when tapped on other devices 
- Verified remove confirmation is shown 
- Verified able to remove other devices from sync chain

![image](https://user-images.githubusercontent.com/17010094/112469847-db912a00-8d61-11eb-920e-aa121818a4eb.png) | ![image](https://user-images.githubusercontent.com/17010094/112469861-e055de00-8d61-11eb-99f9-307f8156b733.png)
-- | --

------------
Verification passed on iPhone 7+ with iOS 14.4 running 1.24(21.3.24.11)
- Verified remove device is shown when tapped on other devices 
- Verified remove confirmation is shown 
- Verified able to remove other devices from sync chain

![image](https://user-images.githubusercontent.com/17010094/112469922-f368ae00-8d61-11eb-8426-cb09d78b111e.png) | ![image](https://user-images.githubusercontent.com/17010094/112469946-f9f72580-8d61-11eb-976d-1733d0bc0a78.png)
-- | --
