### ISSUE TITLE
Not showing transfer BAT option in rewards menu

### ISSUE THREAD

**Issue by eduardoturconi** [brave/brave-ios#3204]
### Description: 

Can’t transfer my BAT to desktop because there is no option to do that.

### Steps to Reproduce 
  1. Open Brave
  2. Toggle triangle menu

**Actual result:** 

![6F7BC079-7331-4B5E-89DF-56C5E4EB0C42](https://user-images.githubusercontent.com/4389868/104813940-00f63a80-57eb-11eb-8621-2deadc7ae6e1.png)

**Expected result:**

Option to transfer my BAT

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Easily reproduced

**Brave Version:** 

v1.22.1 (20.12.10.23)

**Device details:** 

iPhone 12 Pro

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
@eduardoturconi Hi Eduardo, if you go to Settings, then tap into Brave Rewards, do you see the option to transfer legacy BAT there?

**Comment by eduardoturconi** [comment]
> @eduardoturconi Hi Eduardo, if you go to Settings, then tap into Brave Rewards, do you see the option to transfer legacy BAT there?

No, there is no option:
![499DFFD9-6332-4142-9E4A-B472A417ECB6](https://user-images.githubusercontent.com/4389868/104965138-d2c85480-59bc-11eb-8f4e-4986e1d2c19a.png)

**Comment by andrew-pyle** [comment]
Same observation here. No option to transfer, either in the triangle toggle or the Brave settings page. 

iOS 14.4
Brave 1.22.2 (21.1.21.11)
iPhone SE

**Comment by eduardoturconi** [comment]
Any news? Still doesn’t show any option
