### ISSUE TITLE
Modernize dependency management

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3207]
Move away from Carthage for deps and move static libraries (`.a`) to modern `XCFramework`s to ensure future Xcode compatibility 

## Test Plan

Dependencies may be updated in the process, therefore things that depend on them should be sanity tested.

This includes:

- Image caching (i.e. large and small favicons)
- Local web server (i.e. error pages, tab restore, etc.)
- Animated Lottie images (onboarding)
- Yubi Keys
- SQLite passwords encryption

**Comment by kjozwiak** [comment]
We'll label this as `QA/Pass` once all the issues have been verified and https://github.com/brave/brave-ios/issues/3472, https://github.com/brave/brave-ios/issues/3473 and https://github.com/brave/brave-ios/issues/3474 have been completed.

**Comment by srirambv** [comment]
Marking as passed based on previous comment
