### ISSUE TITLE
Removing Selected Tab Assertion

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#3215]
### Description: 
One of the highest velocity crashes is pointing out to selectTab inside TabManager. If we check Stack Trace this crash is related with TabTrayController and previously this crash has been fixed in https://github.com/brave/brave-ios/issues/3041

So in order have a better insight about the problem the assertion is removed and a guard is added with a logger inside.

### Steps to Reproduce 
We need a quick sanity check in order to be sure this change doesn't effect anything while selecting a tab.

Steps for sanity check Test Plan:
  1. Create new tabs with different URLs and check selecting different tabs work (normal/private)
  2. Put application in background while some tabs are open and click an external link from a different application - Brave Browser should be default browser
  3. Open Tab Tray while some tabs open, put the application in background without closing the TabTray and click an external link from a different application while Brave Browser is default Browser
 

**Actual result:**
Nothing out of ordinary happens

**Expected result:**
After sanity check, select tab related functionality should work properly. Test Plan is shared under Steps to Reproduce

**Reproduces how often:
N/A

**Brave Version:** 
Version 1.22.2 (21.1.20.17)

**Device details:**
Any model iPhone and iPad

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.3 running 1.22.2(21.1.20.17)
- Verified steps from issue description
---------
Verification passed on iPhone XRwith iOS 13.5 running 1.22.2(21.1.20.17)
- Verified steps from issue description
---------
Verification passed on iPad Pro with iOS 12.4.1 running 1.22.2(21.1.20.17)
- Verified steps from issue description

**Comment by kjozwiak** [comment]
Just some context re: the above. @srirambv found an issue where sometimes after an upgrade, tabs wouldn't be restored. So @iccub has reverted https://github.com/brave/brave-ios/pull/3212. As per @iccub:

```
* if no bug on 21.1.21.17 we should use this build from now on and address the tab tray thing later
* if the bug still happens on 21.1.21.17 we can keep using the old 21.1.21.11 build, it means the bug is not a regression and can be investigated later
```
