### ISSUE TITLE
VPN install problems UX improvements

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3219]
## Description
Improve our UX regarding problems with VPN installation

## Designs
-Add a title to the second screen Data to include in the support email
-Change "Send" to Continue to email
-Use the default iOS blue action color instead of the destructive red for Continue to email

![image](https://user-images.githubusercontent.com/2388823/107075641-3c0edc80-679f-11eb-8994-995e2edc06ef.png)

**Comment by anthonypkeane** [comment]
Screenshots for QA verification 

<img width="1282" alt="Zrzut ekranu 2021-01-25 o 16 00 29" src="https://user-images.githubusercontent.com/7606853/106971311-86428000-6703-11eb-9f97-9305de1c879b.png">


 - added 
• Added Contact technical support button to the vpn install screen
• In the contact form screen there is new Error logs toggle
• If users enables it, vpn logs will be added to the support email, see screen number 3

**Comment by iccub** [comment]
This is current design, further design/copy improvements will be fixed in this ticket https://github.com/brave/brave-ios/issues/3285 in next release

cc @srirambv 

<img width="1231" alt="Zrzut ekranu 2021-02-10 o 13 46 06" src="https://user-images.githubusercontent.com/6950387/107511944-6e0cae00-6ba6-11eb-876c-f96e3236bda9.png">

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.23(21.2.5.15)
- Verified `Contact Technical Support` button is added to Install VPN screen
- Verified `Error Logs` is added to the list of options 
- Verified Error logs are added to the email body when clicked on send

![image](https://user-images.githubusercontent.com/17010094/107532216-8e903480-6bb5-11eb-9a3f-30c28e61a942.png) | ![image](https://user-images.githubusercontent.com/17010094/107532231-92bc5200-6bb5-11eb-986b-6097b275c5e1.png) | ![image](https://user-images.githubusercontent.com/17010094/107532248-964fd900-6bb5-11eb-97f6-fe2236ea3c75.png)
-- | -- | --

--------
Verification passed on iPad Pro with iOS 12.4.1 running 1.23(21.2.5.15)
- Verified `Contact Technical Support` button is added to Install VPN screen
- Verified `Error Logs` is added to the list of options 
- Verified Error logs are added to the email body when clicked on send

![image](https://user-images.githubusercontent.com/17010094/107532331-b2ec1100-6bb5-11eb-84fc-db5d95be3c6d.png) | ![image](https://user-images.githubusercontent.com/17010094/107532382-c1d2c380-6bb5-11eb-977d-2dd07d010c60.png) | ![image](https://user-images.githubusercontent.com/17010094/107532431-cbf4c200-6bb5-11eb-88f9-f4fac53f8691.png)
-- | -- | --
