### ISSUE TITLE
Duckduckgo popup for iPhone horizontal has wrong size.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#322]
<img width="950" alt="zrzut ekranu 2018-10-9 o 16 38 35" src="https://user-images.githubusercontent.com/6950387/46694890-4724c280-cc0e-11e8-9114-28e09812b712.png">

This bug also happens in 1.6 codebase.

**Comment by danielbogomazov** [comment]
I can take a look at this if no one else is

**Comment by iccub** [comment]
Go for it @danielbogomazov :)
