### ISSUE TITLE
internal issue #747

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3220]
https://github.com/brave/internal/issues/747

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 14.4 running 1.23(21.2.12.15). More info here https://github.com/brave/internal/issues/747#issuecomment-778360692

--------------

Verified on iPad mini with iOS 13 running 1.23 (21.2.12.9). Testing notes can be found under https://github.com/brave/internal/issues/747#issuecomment-778360692.
