### ISSUE TITLE
some search engines not visible via onboarding and not obvious that list is scrollable

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3223]
### Description: 

In some cases/locales, some SE (search engines) are being cut off in the onboarding modal and it's not obvious that the list is scrollable. We should either improve the way we're displaying SE in our onboarding or make it more obvious that the list is scrollable.

### Steps to Reproduce

  1. change iOS device to a region that supports Ecosia (Canada, Austria etc..)
  2. install & launch `1.22.2 (21.1.20.17)` (installed from TF)
  3. notice that Ecosia isn't being displayed (scroll through the list which isn't obvious)

**Actual result:** 

Video Example (easier to see issue): https://youtu.be/6NGVvZsMB-o

<p align="center">
<img src="https://user-images.githubusercontent.com/2602313/105245828-c5d86c00-5b48-11eb-8276-b4fcf6c6f31f.jpeg" width=300>
</p>

**Expected result:**

<p align="center">
<img src="https://user-images.githubusercontent.com/2602313/105245626-7bef8600-5b48-11eb-94b1-75faeaa09723.PNG" width=300>
</p>

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR mentioned above.

**Brave Version:** 

Using `1.22.2 (21.1.20.17)`

**Device details:** 

* `iPhone 11` running iOS `14.3` - **`Couldn't reproduce`**
* `iPad Air (3rd Gen)` running `iOS 14.3` - **`Reproduced`**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @jamesmudgett @karenkliu @bsclifton @srirambv @aekeus

**Comment by kjozwiak** [comment]
@bsclifton @aekeus moved this into `1.23.1` but we could always add it into `1.23` if needed.

**Comment by kjozwiak** [comment]
Removing `iPad-specific` as @iccub reproduced it on an `iPhone 7` 👍

**Comment by karenkliu** [comment]
I know scrollbar is hidden by default, but can we make it visible just on this panel?

**Comment by kylehickinson** [comment]
@karenkliu There's no way to force that the scroll bars stay visible, we can make them flash or do other things though

**Comment by iccub** [comment]
We decided to flash the scrollbar

**Comment by karenkliu** [comment]
@iccub Thanks for the update!

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 12.4.1 running 1.23.1(21.2.15.14)
- Verified scroll bar flashes after onboarding animation is shown 

https://user-images.githubusercontent.com/17010094/108080288-98a7ac80-7067-11eb-9a28-6f45eb2f881a.MP4

Verification passed on iPad Pro with iOS 14.4 running 1.23.1(21.2.15.14)
- Verified scroll bar flashes after onboarding animation is shown 

https://user-images.githubusercontent.com/17010094/108080947-516deb80-7068-11eb-8a0a-8d125b405506.MP4

Verification passed on iPhone 6 with iOS 12.5.1 running 1.23.1(21.2.15.14)
- Verified scroll bar flashes after onboarding animation is shown 

https://user-images.githubusercontent.com/17010094/108089585-af530100-7071-11eb-84c6-54737262561d.MP4
