### ISSUE TITLE
Ecosia missing when using Ireland as locale

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3224]
### Description: 

Currently `Ecosia` isn't being added into the SE list when using `Ireland` as the locale.

### Steps to Reproduce

  1. download & install `1.22.2 (21.1.20.17)`
  2. before running, ensure `Region: Ireland` & `Language: English Ireland` is selected
  3. run `1.22.2 (21.1.20.17)` and you'll notice `Ireland` is missing from `onboarding` and the SE list under `Settings`

**Actual result:** 

`Ecosia` missing form the SE list.

**Expected result:**

`Ecosia` should be in the list as per https://github.com/brave/brave-ios/issues/3221.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.22.2 (21.1.20.17)`

**Device details:** 

* `iPad Mini 4` running `iOS 13` but @srirambv also reproduced. Reproducible on all devices.

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @bsclifton @srirambv @aekeus

**Comment by iccub** [comment]
Thanks for catching it,
it can be re-tested in `1.22.2 (21.1.21.11)` build already, 
im going to close this issue shortly

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.3 running 1.22.2(21.1.21.11)
- Verified Ecosia is listed for Ireland region

Onboarding | Default Search Engine | Quick Search Engine 
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105350321-e05f2380-5be2-11eb-9783-8d4cdf9ff661.png) | ![image](https://user-images.githubusercontent.com/17010094/105350342-e9e88b80-5be2-11eb-8f3f-9e569b954c53.png) | ![image](https://user-images.githubusercontent.com/17010094/105350326-e48b4100-5be2-11eb-9942-5b72081327a1.png)

--------
Verification passed on iPhone XR with iOS 13.5 running 1.22.2(21.1.21.11)
- Verified Ecosia is listed for Ireland region

Onboarding | Default Search Engine | Quick Search Engine 
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105350371-f4a32080-5be2-11eb-868a-f99e948cce8a.png) | ![image](https://user-images.githubusercontent.com/17010094/105350544-40ee6080-5be3-11eb-9aab-5de6da34fc49.png) | ![image](https://user-images.githubusercontent.com/17010094/105350442-17cdd000-5be3-11eb-9a6b-eb4eda1416b6.png)

------
Verification passed on iPad Pro with iOS 12.4.1 running 1.22.2(21.1.21.11)
- Verified Ecosia is listed for Ireland region

Onboarding | Default Search Engine | Quick Search Engine 
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/105350456-1d2b1a80-5be3-11eb-8239-0edb7f8375db.png) | ![image](https://user-images.githubusercontent.com/17010094/105350511-33d17180-5be3-11eb-92e8-6639200c3f0f.png) | ![image](https://user-images.githubusercontent.com/17010094/105350486-274d1900-5be3-11eb-9596-cd3573ae5050.png)

Verification **PASSED** on `iPad Mini 4` on `iOS 13.7` using `1.22.2 (21.1.21.11)`

* Ensured that `Ireland` was appearing in onboarding/SE lists in `Settings` as per https://github.com/brave/brave-ios/issues/3221

**`Onboarding`** | **`Default Standard`** | **`Default Private`** | **`Default Search`** | **`Ecosia Selected`** |
-------------------|--------------------------|-----------------------|-----------------------|------------------------
![IMG_0415](https://user-images.githubusercontent.com/2602313/105404650-368a9180-5bf8-11eb-990f-e8608c989a65.png) | ![IMG_0416](https://user-images.githubusercontent.com/2602313/105409241-283f7400-5bfe-11eb-87ff-fd35f36e5cf1.png) | ![IMG_0417](https://user-images.githubusercontent.com/2602313/105409325-4a38f680-5bfe-11eb-87aa-e785e00824eb.png) | ![IMG_0419](https://user-images.githubusercontent.com/2602313/105409418-6ccb0f80-5bfe-11eb-9c3a-ca904565257a.png) | ![IMG_0419](https://user-images.githubusercontent.com/2602313/105409814-02669f00-5bff-11eb-88d5-c959c5ee633d.png)
