### ISSUE TITLE
Implement History Sync

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-ios#3227]
## Problem Description 

The iOS browser should sync relevant history entries (based on the same rules Chromium follows).

The iOS Sync Settings should provide a way to enable/disable different Sync types acting from iOS.

## Feature Overview 

- As Chromium rules suggest only "**typed_urls**" will be synced. Which means all the history will be added locally using core as   however entries from directed urls will not be synced with browser. All other rules related with History will stay the same on iOS side UI, the max number of items queried etc.

- Sync Settings will contain a new section which will allow user to toggle different Sync types according to users preference.

## Design 

History UI will stay the same however there will be a new section in Sync settings that has the Sync type toggles.

![1 qq q](https://user-images.githubusercontent.com/6643505/118856605-21232c80-b8a5-11eb-906a-179062da7a26.png)

### Additional information

This implementation will also include "Delete All" functionality on History page so users can have a better place to interact the history deletion.

Ticket for Delete All: https://github.com/brave/brave-ios/issues/3723

**Comment by jsecretan** [comment]
Placeholder for now

**Comment by soner-yuksel** [comment]
The Ticket information is updated with some implementation details and changes.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.30(21.8.6.13)

<details>
<summary><b>Clean Install</b></summary>
<br>

**Scenario 1: No history before joining sync chain**

- Verified able to join a sync chain successfully using QR code or code words
- Verified history sync is disabled by default when Sync is enabled
- Verified no history from other devices are sync'd to iOS when history sync is disabled
- Verified enabling history sync, sync's history from other devices in the chain
- Verified visitng a site on iOS device sync's history to other devices 

**Scenario 2: Existing browsing history before joining sync chain**

- Verified able to join a sync chain successfully using QR code or code words
- Verified history sync is disabled by default when Sync is enabled
- Verified no history from other devices are sync'd to iOS when history sync is disabled
- Verified enabling history sync, existing browsing history from iOS device gets sync'd to other devices in chain
- Verified history from other devices sync across to iOS

**Scenario 3: Delete sync history from iOS Device**

- Verified able to join a sync chain successfully using QR code or code words
- Verified history sync is disabled by default when Sync is enabled
- Verified able to sync existing and new history items across devices
- Verified deleting a single entry from the history tab in iOS devices sync's the change across devices and removes the entry from other devices
- Verified deleting all history from iOS devices propagates the changes to other devices in sync chain and removes all history 

**Scenario 4: Delete sync history from other devices**

- Verified able to join a sync chain successfully using QR code or code words
- Verified history sync is disabled by default when Sync is enabled
- Verified able to sync existing and new history items across devices
- Verified deleting a single entry from the history tab in other devices sync's the change across devices and removes the entry in iOS device
- Verified deleting all history from other device in chain propagates the changes to iOS device and removes all history 

**Scenario 5: Private tab history**

- Verified able to join a sync chain successfully using QR code or code words
- Verified history sync is disabled by default when Sync is enabled
- Verified opening a new private tab on iOS and visiting a site doesn't add the entry to history menu
- Verified sites visited in private tabs are not sync'd to other devices with history sync enabled

**Scenario 6: Private Only mode**

- Verified able to join a sync chain successfully using QR code or code words with PB only mode enabled
- Verified history sync is disabled by default when Sync is enabled
- Verified opening a new private tab and visiting a site doesn't add the site to history tab
- Verified no sites visited in PB only mode gets sync'd across to other devices in the sync chain

**Scenario 7: Loading bookmarks**

- Verified able to join a sync chain successfully using QR code or code words with PB only mode enabled
- Verified history sync is disabled by default when Sync is enabled
- Verified loading a bookmark adds the site to history tab
- Verified added history entry for loading bookmark is not sync'd across to other devices
- Verified bookmarks loaded on other devices doesn't sync to iOS device either

**Scenario 8: Manually visiting site**

- Verified able to join a sync chain successfully using QR code or code words with PB only mode enabled
- Verified history sync is disabled by default when Sync is enabled
- Verified manually typing a site and pressing enter adds the loaded site to history entry
- Verified enabling search suggestions and typing a site name shows suggested site. Selecting the suggested site loads and adds the site to history 
- Verified only manually typed in site is sync'd to other devices and not the suggested site that is loaded 

**Scenario 9: Loading sites via context menu or via link**

- Verified able to join a sync chain successfully using QR code or code words with PB only mode enabled
- Verified history sync is disabled by default when Sync is enabled
- Verified loading a site in a new tab via context menu only adds it to the history list
- Verified site loaded via context menu is not sync'd as history entry to other devices in chain
- Verified visiting `https://startpage.com` and performing a search and clicking on a result loads the page in a new tab. The visited page is only added to history entry but not sync'd across to other devices in sync chain

**Scneario 10: Scanning URL via QR Code**

- Verified able to join a sync chain successfully using QR code or code words with PB only mode enabled
- Verified history sync is disabled by default when Sync is enabled
- Verified scanning QR code for a site loads the page in new tab
- Verified entry for the visited site is added to history
- Verified the history entry for the site loaded via QR Code is sync'd across to all other devices

</details>


<details>
<summary><b>Upgrade Install</b></summary>
<br>

**Scenario 1: Existing Sync chain**

- Verified upgrading from old build retains the sync chain
- Verified on upgrade sync doesn't enable history sync by default
- Verified no history is sync'd upon upgrade from older build with sync enabled
- Verified eanbling history sync post upgrade sync'd browsing history from all devices
- Verified only typed_in urls from all devices are sync'd as expected

**Scenario 2: No previous Sync chain**

- Verified upgrading from old build doesn't enable Sync chain
- Verified enabling sync post upgrade only enables bookmarks by default
- Verified able to enable history sync once joining a sync chain or creating a new one
- Verified existing browsing history is sync'd to all devices on chain once history sync is enabled

**Scenario 3: Private Only browsing mode**

- Verified upgrading from older build with PB only mode doesn't enable Sync upon upgrade
- Verified enabling sync with PB only mode still only enables bookmarks by default and history sync is disabled
- Verified enabling history sync only sync's history from other devices 
- Verified sites visited in PB only mode isn't added to the history list or sync'd across to other devices on the sync chain
- Verified clearing history from other devices doesn't affect the iOS device private tabs

</details>

<details>
<summary><b>Misc</b></summary>
<br>

- Verified chrome internal pages typed on Desktop/Android doesn't sync as they are not added to browsing history 
- Verified closing and reopening app only sync typed_urls and not visiting sites via context menu or hyperlinks
- Verified changing shields settings reloads all tabs affecting history list but doesn't sync all existing hitory links. Only sync's typed in URL's
- Verified clearing browsing data clears all history and cache but reloads all open tabs. Clear history triggers all history to be removed from other devices as well and resync's the typed in URL as its added back to iOS history list

</details>

---------------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.30(21.8.6.13)

<details>
<summary><b>Clean Install</b></summary>
<br>

**Scenario 1: No history before joining sync chain**

- Verified able to join a sync chain successfully using QR code or code words
- Verified history sync is disabled by default when Sync is enabled
- Verified no history from other devices are sync'd to iOS when history sync is disabled
- Verified enabling history sync, sync's history from other devices in the chain
- Verified visitng a site on iOS device sync's history to other devices 

**Scenario 2: Existing browsing history before joining sync chain**

- Verified able to join a sync chain successfully using QR code or code words
- Verified history sync is disabled by default when Sync is enabled
- Verified no history from other devices are sync'd to iOS when history sync is disabled
- Verified enabling history sync, existing browsing history from iOS device gets sync'd to other devices in chain
- Verified history from other devices sync across to iOS

**Scenario 3: Delete sync history from iOS Device**

- Verified able to join a sync chain successfully using QR code or code words
- Verified history sync is disabled by default when Sync is enabled
- Verified able to sync existing and new history items across devices
- Verified deleting a single entry from the history tab in iOS devices sync's the change across devices and removes the entry from other devices
- Verified deleting all history from iOS devices propagates the changes to other devices in sync chain and removes all history 

**Scenario 4: Delete sync history from other devices**

- Verified able to join a sync chain successfully using QR code or code words
- Verified history sync is disabled by default when Sync is enabled
- Verified able to sync existing and new history items across devices
- Verified deleting a single entry from the history tab in other devices sync's the change across devices and removes the entry in iOS device
- Verified deleting all history from other device in chain propagates the changes to iOS device and removes all history 

**Scenario 5: Private tab history**

- Verified able to join a sync chain successfully using QR code or code words
- Verified history sync is disabled by default when Sync is enabled
- Verified opening a new private tab on iOS and visiting a site doesn't add the entry to history menu
- Verified sites visited in private tabs are not sync'd to other devices with history sync enabled

**Scenario 6: Private Only mode**

- Verified able to join a sync chain successfully using QR code or code words with PB only mode enabled
- Verified history sync is disabled by default when Sync is enabled
- Verified opening a new private tab and visiting a site doesn't add the site to history tab
- Verified no sites visited in PB only mode gets sync'd across to other devices in the sync chain

**Scenario 7: Loading bookmarks**

- Verified able to join a sync chain successfully using QR code or code words with PB only mode enabled
- Verified history sync is disabled by default when Sync is enabled
- Verified loading a bookmark adds the site to history tab
- Verified added history entry for loading bookmark is not sync'd across to other devices
- Verified bookmarks loaded on other devices doesn't sync to iOS device either

**Scenario 8: Manually visiting site**

- Verified able to join a sync chain successfully using QR code or code words with PB only mode enabled
- Verified history sync is disabled by default when Sync is enabled
- Verified manually typing a site and pressing enter adds the loaded site to history entry
- Verified enabling search suggestions and typing a site name shows suggested site. Selecting the suggested site loads and adds the site to history 
- Verified only manually typed in site is sync'd to other devices and not the suggested site that is loaded 

**Scenario 9: Loading sites via context menu or via link**

- Verified able to join a sync chain successfully using QR code or code words with PB only mode enabled
- Verified history sync is disabled by default when Sync is enabled
- Verified loading a site in a new tab via context menu only adds it to the history list
- Verified site loaded via context menu is not sync'd as history entry to other devices in chain
- Verified visiting `https://startpage.com` and performing a search and clicking on a result loads the page in a new tab. The visited page is only added to history entry but not sync'd across to other devices in sync chain

**Scneario 10: Scanning URL via QR Code**

- Verified able to join a sync chain successfully using QR code or code words with PB only mode enabled
- Verified history sync is disabled by default when Sync is enabled
- Verified scanning QR code for a site loads the page in new tab
- Verified entry for the visited site is added to history
- Verified the history entry for the site loaded via QR Code is sync'd across to all other devices

</details>


<details>
<summary><b>Upgrade Install</b></summary>
<br>

**Scenario 1: Existing Sync chain**

- Verified upgrading from old build retains the sync chain
- Verified on upgrade sync doesn't enable history sync by default
- Verified no history is sync'd upon upgrade from older build with sync enabled
- Verified eanbling history sync post upgrade sync'd browsing history from all devices
- Verified only typed_in urls from all devices are sync'd as expected

**Scenario 2: No previous Sync chain**

- Verified upgrading from old build doesn't enable Sync chain
- Verified enabling sync post upgrade only enables bookmarks by default
- Verified able to enable history sync once joining a sync chain or creating a new one
- Verified existing browsing history is sync'd to all devices on chain once history sync is enabled

**Scenario 3: Private Only browsing mode**

- Verified upgrading from older build with PB only mode doesn't enable Sync upon upgrade
- Verified enabling sync with PB only mode still only enables bookmarks by default and history sync is disabled
- Verified enabling history sync only sync's history from other devices 
- Verified sites visited in PB only mode isn't added to the history list or sync'd across to other devices on the sync chain
- Verified clearing history from other devices doesn't affect the iOS device private tabs

</details>

<details>
<summary><b>Misc</b></summary>
<br>

- Verified chrome internal pages typed on Desktop/Android doesn't sync as they are not added to browsing history 
- Verified closing and reopening app only sync typed_urls and not visiting sites via context menu or hyperlinks
- Verified changing shields settings reloads all tabs affecting history list but doesn't sync all existing hitory links. Only sync's typed in URL's
- Verified clearing browsing data clears all history and cache but reloads all open tabs. Clear history triggers all history to be removed from other devices as well and resync's the typed in URL as its added back to iOS history list
- Verified typing a search term and using a quick search engine adds the entry in browsing history and sync's to all devices 

</details>

---------------
Verification passed on iPad Pro with iOS 14.6 running 1.30(21.8.6.13)

<details>
<summary><b>Clean Install</b></summary>
<br>

**Scenario 1: No history before joining sync chain**

- Verified able to join a sync chain successfully using QR code or code words
- Verified history sync is disabled by default when Sync is enabled
- Verified no history from other devices are sync'd to iOS when history sync is disabled
- Verified enabling history sync, sync's history from other devices in the chain
- Verified visitng a site on iOS device sync's history to other devices 

**Scenario 2: Existing browsing history before joining sync chain**

- Verified able to join a sync chain successfully using QR code or code words
- Verified history sync is disabled by default when Sync is enabled
- Verified no history from other devices are sync'd to iOS when history sync is disabled
- Verified enabling history sync, existing browsing history from iOS device gets sync'd to other devices in chain
- Verified history from other devices sync across to iOS

**Scenario 3: Delete sync history from iOS Device**

- Verified able to join a sync chain successfully using QR code or code words
- Verified history sync is disabled by default when Sync is enabled
- Verified able to sync existing and new history items across devices
- Verified deleting a single entry from the history tab in iOS devices sync's the change across devices and removes the entry from other devices
- Verified deleting all history from iOS devices propagates the changes to other devices in sync chain and removes all history 

**Scenario 4: Delete sync history from other devices**

- Verified able to join a sync chain successfully using QR code or code words
- Verified history sync is disabled by default when Sync is enabled
- Verified able to sync existing and new history items across devices
- Verified deleting a single entry from the history tab in other devices sync's the change across devices and removes the entry in iOS device
- Verified deleting all history from other device in chain propagates the changes to iOS device and removes all history 

**Scenario 5: Private tab history**

- Verified able to join a sync chain successfully using QR code or code words
- Verified history sync is disabled by default when Sync is enabled
- Verified opening a new private tab on iOS and visiting a site doesn't add the entry to history menu
- Verified sites visited in private tabs are not sync'd to other devices with history sync enabled

**Scenario 6: Private Only mode**

- Verified able to join a sync chain successfully using QR code or code words with PB only mode enabled
- Verified history sync is disabled by default when Sync is enabled
- Verified opening a new private tab and visiting a site doesn't add the site to history tab
- Verified no sites visited in PB only mode gets sync'd across to other devices in the sync chain

**Scenario 7: Loading bookmarks**

- Verified able to join a sync chain successfully using QR code or code words with PB only mode enabled
- Verified history sync is disabled by default when Sync is enabled
- Verified loading a bookmark adds the site to history tab
- Verified added history entry for loading bookmark is not sync'd across to other devices
- Verified bookmarks loaded on other devices doesn't sync to iOS device either

**Scenario 8: Manually visiting site**

- Verified able to join a sync chain successfully using QR code or code words with PB only mode enabled
- Verified history sync is disabled by default when Sync is enabled
- Verified manually typing a site and pressing enter adds the loaded site to history entry
- Verified enabling search suggestions and typing a site name shows suggested site. Selecting the suggested site loads and adds the site to history 
- Verified only manually typed in site is sync'd to other devices and not the suggested site that is loaded 

**Scenario 9: Loading sites via context menu or via link**

- Verified able to join a sync chain successfully using QR code or code words with PB only mode enabled
- Verified history sync is disabled by default when Sync is enabled
- Verified loading a site in a new tab via context menu only adds it to the history list
- Verified site loaded via context menu is not sync'd as history entry to other devices in chain
- Verified visiting `https://startpage.com` and performing a search and clicking on a result loads the page in a new tab. The visited page is only added to history entry but not sync'd across to other devices in sync chain

**Scneario 10: Scanning URL via QR Code**

- Verified able to join a sync chain successfully using QR code or code words with PB only mode enabled
- Verified history sync is disabled by default when Sync is enabled
- Verified scanning QR code for a site loads the page in new tab
- Verified entry for the visited site is added to history
- Verified the history entry for the site loaded via QR Code is sync'd across to all other devices

</details>


<details>
<summary><b>Upgrade Install</b></summary>
<br>

**Scenario 1: Existing Sync chain**

- Verified upgrading from old build retains the sync chain
- Verified on upgrade sync doesn't enable history sync by default
- Verified no history is sync'd upon upgrade from older build with sync enabled
- Verified eanbling history sync post upgrade sync'd browsing history from all devices
- Verified only typed_in urls from all devices are sync'd as expected

**Scenario 2: No previous Sync chain**

- Verified upgrading from old build doesn't enable Sync chain
- Verified enabling sync post upgrade only enables bookmarks by default
- Verified able to enable history sync once joining a sync chain or creating a new one
- Verified existing browsing history is sync'd to all devices on chain once history sync is enabled

**Scenario 3: Private Only browsing mode**

- Verified upgrading from older build with PB only mode doesn't enable Sync upon upgrade
- Verified enabling sync with PB only mode still only enables bookmarks by default and history sync is disabled
- Verified enabling history sync only sync's history from other devices 
- Verified sites visited in PB only mode isn't added to the history list or sync'd across to other devices on the sync chain
- Verified clearing history from other devices doesn't affect the iOS device private tabs

</details>

<details>
<summary><b>Misc</b></summary>
<br>

- Verified chrome internal pages typed on Desktop/Android doesn't sync as they are not added to browsing history 
- Verified closing and reopening app only sync typed_urls and not visiting sites via context menu or hyperlinks
- Verified changing shields settings reloads all tabs affecting history list but doesn't sync all existing hitory links. Only sync's typed in URL's
- Verified clearing browsing data clears all history and cache but reloads all open tabs. Clear history triggers all history to be removed from other devices as well and resync's the typed in URL as its added back to iOS history list
- Verified typing a search term and using a quick search engine adds the entry in browsing history and sync's to all devices 

</details>
