### ISSUE TITLE
Implement tabs sync

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-ios#3229]
## Problem Description 

Add Support to iOS Browser the functionality of syncing Tabs and sending/receiving tab information upon request.

## Feature Overview 

This feature should support 

1. Enabling / Disabling Tab Sync From Settings as a Sync Type

2. Ability to list tabs of synced sessions from other devices and add interactions like open a tab / search / expand-shrink sessions

3. Sync Tabs with the Sync engine on the background when a tab becomes active so other devices can receive tabs from mobile iOS 

4. Add "Send To Your Devices" functionality which will present a way to list devices that can receive a Tab and send the tab information to desired device.

5. Add "Receive Tab" functionality and UI for warning/alerting users about the Tab received from other devices.

## Design 

Some sample test designs for Synced Sessions List - Send Tab To Device - Tab Received.

These designs doesn't represent the final product look, just some test UX.

![test1tabsessionslist](https://user-images.githubusercontent.com/6643505/180494701-42b61a17-d7e9-49ad-8a4c-259ed8f459c2.png)

## User Experience 

   1. To enable Tab Sync:  Open Tabs Navigate Settings -> Sync -> Sync Settings
   2. To display Open Tabs from different sessions: Open TabTray and click Sync Tabs Segmented Control, user should be able to expand/dismiss session from different devices and clicking a item should open a new tab with the url
   3. To send a current tab to another device: Click 3dot menu from 3 dot menu either click Send To Your Devices action or click share and find Send To Your Devices action. From the list of devices shown on the screen select one of them and send.
   4. To receive a tab from other device: When iOs device receives a tab from another device, a Toast will be shown on the screen and there will be Open action for this tab which will open that tab url in a new tab. Toast will be hidden after a certain period of time

### Additional information

The iOS PR logic and UX improvements are WIP.

The brave-core logic and PR can be seen

https://github.com/brave/brave-core/pull/14287

**Comment by ghost** [comment]
Definitely need this feature on iOS

**Comment by VincenzoGalante** [comment]
Patiently waiting for this to arrive. Very frustrating and would def be a reason for a browser switch as it is really essential to me.

**Comment by brandonpollack23** [comment]
Just switched and after realizing this I might switch back, I'll see how it goes :(

**Comment by maenujem** [comment]
Being able to sync open tabs on iOS would be highly welcomed :) 

At least it should be mentioned in FAQ (https://support.brave.com/hc/en-us/articles/360047642371-Sync-FAQ), that it is not possible at this time. This would save people from wasting time to find out.

There are already a bunch of forum entries about people wishing this feature.

- https://community.brave.com/t/syncing-open-tabs/191699
- https://community.brave.com/t/how-to-open-tabs-from-other-devices/179012/34
- https://community.brave.com/t/synced-tabs-on-ios-and-mac-os/239666
- https://community.brave.com/t/open-tabs-sync-between-mac-and-iphone/253585
- https://community.brave.com/t/open-tabs-not-syncing-across-devices-iphone-ipad-mac/274834

As a workaround it would also be welcomed to be able to "add all open tabs to bookmarks" and "open all tabs from bookmarks"..

**Comment by simonmichael** [comment]
Or just "copy links" as in IOS Safari, putting urls of all open tabs in clipboard.

**Comment by BenjaminMichaelis** [comment]
I'm confused with on the desktop version you can hit "send tab to iPhone" but it never actually receives. Seems miss-leading at this point? I don't see an issue specifically about the send tab/page feature but seems similar to this, not the same but has some overlap

**Comment by afshawnlotfi** [comment]
> I'm confused with on the desktop version you can hit "send tab to iPhone" but it never actually receives. Seems miss-leading at this point? I don't see an issue specifically about the send tab/page feature but seems similar to this, not the same but has some overlap

Yeah I am having this issue as well, not sure if this is just a feature of chromium that wasn't removed as Brave hasn't supported it with Sync yet, but I think Brave would be awesome if this and full history sync were fixed.

**Comment by guicbrito** [comment]
I just made a move from chrome to brave and spent half a day setting up all my settings, extensions, tabs, etc on my desktop and android devices.
When i got to my Ipad… Surprise! Can’t sync tabs or even send them to the device. Also, you can’t find out about it until you actually need the feature.
I had tried to make a move from chrome to brave around a year ago, but couldn’t remember why I gave up at the time. Guess that’s why.
I hope you guys are able to implement the feature soon. I believe you should inform the user that it’s not available for the time being somewhere in the sync settings of iOS.

**Comment by iccub** [comment]
I do not want to overpromise, but we are close. Our dev saying best case we get it in 1.43, which is end of August
We want to add both synced tabs, and 'send tab' feature

**Comment by soner-yuksel** [comment]
Hi everyone, 

The ticket information is updated with sufficient information with some test UX and functionality about the feature and like @iccub mentioned we are aiming 1.43 release for the feature.

Brave Core PR progress can be seen https://github.com/brave/brave-core/pull/14287
iOS PR WIP

**Comment by iccub** [comment]
Hi everyone, good news: the tab sync enters public beta today :)
Feel free to check it out, invitation link is here https://testflight.apple.com/join/Trcbh1o3

We added synced tabs and send-to-device functionality.
Remember to enable 'Tab' sync type on all devices you have connected to the sync chain, as it's disabled by default.

**Comment by Uni-verse** [comment]
Verified using `1.43 (22.9.9.14)`

Test Devices:
iPhone XR running iOS 15.x
iPhone 12 Pro running iOS 16.x
iPhone X running iOS 14.4.2
iPad running iPadOS 15.x

**Figma:**

- [x] Tab Sync
- [x] Sending/Receiving 

**Enabling Tab Sync:**

- Verified tapping `Start a sync chain` from the sync tab page will show the Sync chain creation modal
- Verified tapping `Enable tab syncing` will show the Sync settings modal, toggling ON `Open Tabs` will display tabs from other sessions.
- Verified `device name`, `platform type legend` (mobile/tablet or desktop) and `Last synced` time is displayed for each device in the sync chain that has sync tabs enabled.
- Verified user is able to `expand` and `collapse `tab sessions for each device listed
- Verified tapping on other session will open the page in a new tab, user is able to open other sessions from both mobile and desktop.

1 | 2 | 3 | 4
-|-|-|-
![IMG_0041](https://user-images.githubusercontent.com/17885425/189773259-ea57d724-5b82-415d-9fe7-66ffb31eee05.PNG) | ![IMG_0042](https://user-images.githubusercontent.com/17885425/189773418-7fff367c-bb3a-4a73-b51b-f630d917337e.PNG) | ![IMG_0044](https://user-images.githubusercontent.com/17885425/189773448-2a6580c5-884c-4d6a-b8e3-454dd61ce92f.PNG) | ![IMG_0045](https://user-images.githubusercontent.com/17885425/189773449-dd4c0338-06e6-47b4-95ff-da6d9d54cd0b.PNG)

**Sending Tab:**

- Verified sending `Send to your Devices` is shown in the share menu when connected to sync chain.
- Verified using `Send to your Devices` in the menu will bring up `Send Web Page` modal. 
- Verified user is able to select devices listed in the `Send Web Page` modal.
- Verified tapping `Cancel` will dismiss modal
- Verified tapping on `Send to your Device` will dismiss modal and send url to device selected.

1 | 2 | 3 | 4
-|-|-|-
![IMG_0046](https://user-images.githubusercontent.com/17885425/189925074-c0eeba75-e77b-415c-86f1-f0cac0b27c72.PNG) | ![IMG_0558](https://user-images.githubusercontent.com/17885425/189925010-5fea1b5b-12f3-4642-aa6e-f121ae8926df.PNG) | ![IMG_0053](https://user-images.githubusercontent.com/17885425/189927908-84faf6d9-fd42-4653-9e3e-7aa59726d967.PNG) | ![IMG_0054](https://user-images.githubusercontent.com/17885425/189927911-1a2a873b-89a0-4c19-a76e-f42bbf3873c5.PNG)

**Receiving Tab:**

Case 1: Desktop to Mobile

- Verified banner is displayed when receiving tab from other session
- Verified Tapping `Go` will load the tab

Logged - https://github.com/brave/brave-browser/issues/37058

Case 2: Mobile to Mobile

- Verified banner is displayed when receiving tab from other session
- Verified Tapping `Go` will load the tab
- Verified correct legend is shown on the notification banner (mobile)

1 | 2
-|-
![IMG_0556](https://user-images.githubusercontent.com/17885425/189928509-f67fec5c-49ad-41a1-bad6-ef619753ac25.PNG) | ![IMG_0055](https://user-images.githubusercontent.com/17885425/189928868-542925c3-67cb-4e81-975b-f1cf7e39e6fd.PNG)

**Open Tab from Other Session:**

- Verified opening other tabs via the sync tab section
- Verified opening desktop & mobile tab sessions
- Verified notification banner is played when tapping on tabs from other sessions
- Verified tapping "Switch" on the notification banner will load the page
- Verified notification banner is dismissed after a period of time

Example | Example
-|-
![IMG_0047](https://user-images.githubusercontent.com/17885425/189947657-2b6bbe5e-76e1-4c21-9f62-a58000e7d529.PNG) | ![IMG_0565](https://user-images.githubusercontent.com/17885425/189948922-3c6b05aa-849d-4de8-928e-1317c357b1fe.PNG)

**Upgraded Profile:** 

- Verified able to load tabs from other sessions, tapping "Switch" will load the page
- Verified able to send/receive pages on an upgraded profile

**Searching Synced Tabs**

- Verified tabs will be filtered by key words in search
- Verified placeholder text inside field when empty
- Verified tapping cancel removes cursor from search field

Example | Example
-|-
![IMG_0566](https://user-images.githubusercontent.com/17885425/189952764-08fa1b03-2f10-48b7-bbed-5e312c567e75.PNG) | ![IMG_0058](https://user-images.githubusercontent.com/17885425/189952786-15db761e-077e-4025-bbcb-f558cda112ad.PNG)

**Comment by iccub** [comment]
The tab sync is live in build 1.43, go to the App Store to update manually and thank you for your patience

**Comment by BenjaminMichaelis** [comment]
Seems to work well!!

**Comment by soner-yuksel** [comment]
@BenjaminMichaelis happy to hear that 😄

**Comment by theQureshi** [comment]
> The tab sync is live in build 1.43, go to the App Store to update manually and thank you for your patience

@iccub not working for me on the latest Brave for MacOS and iOS.

**Comment by BenjaminMichaelis** [comment]
> > The tab sync is live in build 1.43, go to the App Store to update manually and thank you for your patience
> 
> 
> 
> @iccub not working for me on the latest Brave for MacOS and iOS.

What build? It's working for me in
Version 1.45.2 (22.11.29.0)

On the iPhone14 with iOS 16.1.1

**Comment by theQureshi** [comment]
Working now. I created a new sync from the iPhone (previously it was started from Mac).
