### ISSUE TITLE
Search box remains as if the keyboard would be available even after hiding it

### ISSUE THREAD

**Issue by cperezabo** [brave/brave-ios#3232]
### Steps to Reproduce 
  1. Click in search box
  2. Hide the keyboard by sliding it downwards

**Actual result:** 

https://user-images.githubusercontent.com/3604722/105641431-b61b9900-5e62-11eb-82e1-3e5701506ff8.mp4

**Expected result:**
Search box should come back to it default state because it doesn't make any sense that it keeps activated if the keyboard is not present.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 
1.22.2 (21.1.21.11)

**Device details:** 
iPhone XS Max (iOS 14.3)

**Comment by iccub** [comment]
@jamesmudgett thoughts on UX here? should we dismiss the screen if keyboard is swiped down

**Comment by kylehickinson** [comment]
@jamesmudgett @iccub This was intentional because this is a scrolling list of your favourites. Perhaps we can hide it in the instance where the user has no favs like seen in the report.

**Comment by cperezabo** [comment]
In fact, favorites title should not be displayed if there is no favorites. Other way it's like "here you have your favorites, your beautiful and inexistent favorites"

So, if you have favorites & keyboard is hidden, you can still scroll down your favorites.
If you don't have favorites & keyboard is hidden, there is no reason for the UI to stay that way.

Think about it, you start the searching flow from the bottom of the screen by tapping the search icon, then you type something with the keyboard (still at the bottom), and then decide not to continue searching, so you hide the keyboard (yeah, at the bottom of the screen) and done, you are back where you were!. But NO, when you decide to stop doing what you were doing in the botom of the screen, you have to change your hands position to reach the cancel button in the top-right corner. 😵

Sorry, I'm a little obsessed about UX 🤣

**Comment by iccub** [comment]
we have much more items in the overlay screen, let's close it for now
