### ISSUE TITLE
Confirm Brave Ads are shown after upgrading to iOS build with b-c 1.19.x

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#3237]
See https://github.com/brave/brave-browser/issues/13719

**Comment by kylehickinson** [comment]
Rewards bump was merged, so this just needs to be verified by QA

**Comment by LaurenWags** [comment]
Verified on iPad mini with iOS 13 running 1.24 (21.3.25.18)

Verified test plan from https://github.com/brave/brave-browser/issues/13719

<details>
<summary>Upgrade profile</summary>

Confirmed ads were shown as expected after upgrade

- Installed 1.23.1
- Enabled Rewards
- Viewed ad
- Upgraded to 1.24
- Confirmed ad notifications still received after upgrade

```
[Debug] [BraveRewards] [ad_notification_event_viewed.cc:24] > Viewed ad notification with uuid 33474c3f-1fac-4127-a24f-b636a8a5a556 and creative instance id fa46630a-aa85-4de2-a670-ef43c9ee1aea
```

```
[Debug] [BraveRewards] [redeem_unblinded_token.cc:68] > URL Request:
  URL: https://ads-serve.brave.com/v1/confirmation/cbbf........
  Content: {"blindedPaymentToken":"ZiEQ77te1L6gCijzoki+aql5F4/9TYIajsWN/i9ktkM=","buildChannel":"dev","creativeInstanceId":"fa46630a-aa85-4de2-a670-ef43c9ee1aea","experiment":{},"payload":{},"platform":"ios","type":"view"}
  Content Type: application/json
  Met<…>
```

NTP ad views after upgrade occur as discussed here: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1617021517155400?thread_ts=1616781926.142700&cid=C06UXF3KJ

</details>

-----------------

Verified on iPhone with iOS 14 running 1.24 (21.3.31.15)

Verified test plan from https://github.com/brave/brave-browser/issues/13719

<details>
<summary>Upgrade profile</summary>

Confirmed ads were shown as expected after upgrade

- Installed 1.23.1
- Enabled Rewards
- Viewed ad
- Upgraded to 1.24
- Confirmed ad notifications still received after upgrade

```
[Debug] [BraveRewards] [ad_notification_event_viewed.cc:24] > Viewed ad notification with uuid 59c64abb-89c2-458a-8ecb-4cc5a5b3a932 and creative instance id 7898a259-664a-4052-8382-9c7279ae3249
```

```
[Debug] [BraveRewards] [redeem_unblinded_token.cc:68] > URL Request:
  URL: https://ads-serve.bravesoftware.com/v1/confirmation/849........
  Content: {"blindedPaymentToken":"xmKxekuY9mk1UVDvJEEhBT6UVtxey40RO46M6fesjUI=","buildChannel":"dev","creativeInstanceId":"7898a259-664a-4052-8382-9c7279ae3249","experiment":{},"payload":{},"platform":"ios","type":"view"}
  Content Type: application/js<…>
```

NTP ad views after upgrade occur as discussed here: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1617021517155400?thread_ts=1616781926.142700&cid=C06UXF3KJ

</details>
