### ISSUE TITLE
Tab title isn't readable when theme is changed via control centre

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3243]
### Description: 
Tab title isn't readable when theme is changed via control centre

### Steps to Reproduce 
  1. Install 1.23(21.1.28.16)
  2. Open a couple of tabs and load pages in them
  3. Change theme via control centre
  4. Tab title isn't legible

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/106267390-79182380-6221-11eb-93c0-fa57df542507.png)

**Expected result:**
Readable Tab titles

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.23(21.1.28.16)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by iccub** [comment]
We reverted this change in code, will close this ticket in favor of https://github.com/brave/brave-ios/issues/2558 which got reopened and will be addressed later, not in this milestone
