### ISSUE TITLE
Merge Bookmarks and Favorites

### ISSUE THREAD

**Issue by nickcharles** [brave/brave-ios#3248]
## Problem Description 

Brave currently supports two ways of saving webpages that are important to the user. Favorites and Bookmarks. Functionally these seem to serve the same purpose. But there are different ways of accessing and using each. Why are these separate features? Can they be merged into a single workflow?

## Feature Overview 

Favorites provide the nice feature of being available as tiles on the new tab page. Bookmarks are easy to add using the three dot menu, where as Favorites can only be added by using the Share workflow, which is hard to discover. Favorites also do not appear to be synced using the Sync workflow, while Bookmarks are.

## Design 

Keep the tiles, let me add new tiles (bookmarks or favorites, let's just pick one) from the three dot menu, and make sure they are synced.

**Comment by iccub** [comment]
you can add Favorites from 3-dot menu, just change `Location` to favorites on add-bookmark screen,

But I agree, long term plan is to have top sites synced between all platforms, 
desktop doesn't have top sites/favorites functionality currently, we will revisit it once it's ready on desktop for sure,
this year we plan to add remaining sync types too, for history, tabs, passwords

**Comment by nickcharles** [comment]
Hmm, I wasn't aware of that feature. That at least fixes one of my workflows.

Thanks for the response, looking forward to the rollout.
