### ISSUE TITLE
Add Custom RSS to Brave Today

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3249]
Mini spec name: `RSS in Brave Today Mini Spec`

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4.2 running 1.24(21.3.25.18)

<details>
<summary>Verified test plan from <a href=https://github.com/brave/brave-ios/pull/3317>#3317</a></summary>
<br>
<details>
<summary><b>Add Source page</b></summary>

</details>
<details>
<summary><b>Brave Today Settings</b></summary>

</details>
<details>
<summary><b>Brave Today Feed</b></summary>

</details>
</details>

-----------------
Verification passed on iPhone 7+ with iOS 14.4.2 running 1.24(21.3.25.18)

<details>
<summary>Verified test plan from <a href=https://github.com/brave/brave-ios/pull/3317>#3317</a></summary>
<br>
<details>
<summary><b>Add Source page</b></summary>

</details>
<details>
<summary><b>Brave Today Settings</b></summary>

</details>
<details>
<summary><b>Brave Today Feed</b></summary>

</details>
</details>

----------------

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4.2 running 1.24(21.3.25.18)

<details>
<summary>Verified test plan from <a href=https://github.com/brave/brave-ios/pull/3317>#3317</a></summary>
<br>
<details>
<summary><b>Add Source page</b></summary>

- Verified able to add a site to Brave Today feed by visiting the site and adding it via share sheet

https://user-images.githubusercontent.com/17010094/112813618-4d28eb00-9076-11eb-8479-459ca01f59a0.MP4

- Verified unsupported sites don't show option to add source via share sheet

https://user-images.githubusercontent.com/17010094/112822244-99c4f400-907f-11eb-9799-5451c1ca6342.MP4

- Verified able to add sites manually 

https://user-images.githubusercontent.com/17010094/112814145-ddffc680-9076-11eb-8e53-6f1ad599e4f1.MP4

</details>
<details>
<summary><b>Brave Today Settings</b></summary>

- Verified able to add sites with multiple feeds
  <img width=300 src=https://user-images.githubusercontent.com/17010094/112814198-ed7f0f80-9076-11eb-8136-26316c0bfd55.png>

- Verified able to add sites with single feed
  <img width=300 src=https://user-images.githubusercontent.com/17010094/112814390-28814300-9077-11eb-9dcb-7ac257f6e0e9.png>

- Verified adding an insecure source shows warning
  <img width=300 src=https://user-images.githubusercontent.com/17010094/112814378-23bc8f00-9077-11eb-9eca-8e3358331d52.png>

- Verified adding an unsupported domain manually shows warning
  <img width=300 src=https://user-images.githubusercontent.com/17010094/112814450-38008c00-9077-11eb-9fe6-5d00bd71a46d.png>

- Verified once 5 source limit is reached, adding a new source throws error 
  <img width=300 src=https://user-images.githubusercontent.com/17010094/112815462-40a59200-9078-11eb-9241-fbf2418a38f3.png>

- Verified able to swipe delete the source
  <img width=300 src=https://user-images.githubusercontent.com/17010094/112815453-3e433800-9078-11eb-9d8f-3d95cf0000b1.png>

</details>
<details>
<summary><b>Brave Today Feed</b></summary>

- Verified custom source feed shows up in Brave Today
- Verified able to long press and disable custom feed source

https://user-images.githubusercontent.com/17010094/112806653-ed7b1180-906e-11eb-8e90-adf4fd8e56aa.MP4

</details>
</details>

---------------
Verification passed on iPhone XR with iOS 14.4.2 running 1.24(21.3.25.18)

<details>
<summary>Verified test plan from <a href=https://github.com/brave/brave-ios/pull/3317>#3317</a></summary>
<br>
<details>
<summary><b>Add Source page</b></summary>

- Verified able to add a site to Brave Today feed by visiting the site and adding it via share sheet

https://user-images.githubusercontent.com/17010094/112820681-bfe99480-907d-11eb-8830-a26641f247fc.MP4

- Verified unsupported sites don't show option to add source via share sheet

https://user-images.githubusercontent.com/17010094/112820996-1c4cb400-907e-11eb-9181-8155ee3ee216.MP4

- Verified able to add sites manually 

https://user-images.githubusercontent.com/17010094/112821482-aac13580-907e-11eb-9d20-9d154f1db072.MP4

</details>
<details>
<summary><b>Brave Today Settings</b></summary>

- Verified able to add sites with multiple feeds
  <img width=300 src=https://user-images.githubusercontent.com/17010094/112820017-186c6200-907d-11eb-83a1-4afdf8569416.png>

- Verified able to add sites with single feed
  <img width=300 src=https://user-images.githubusercontent.com/17010094/112820227-54072c00-907d-11eb-8458-9ba22198f533.png>

- Verified adding an insecure source shows warning
  <img width=300 src=https://user-images.githubusercontent.com/17010094/112820113-35a13080-907d-11eb-8ce1-0c142f70206c.png>

- Verified adding an unsupported domain manually shows warning
  <img width=300 src=https://user-images.githubusercontent.com/17010094/112820129-39cd4e00-907d-11eb-92f6-699dcdce55fd.png>

- Verified once 5 source limit is reached, adding a new source throws error 
  <img width=300 src=https://user-images.githubusercontent.com/17010094/112820342-6bdeb000-907d-11eb-94d4-95e23d057628.png>

- Verified able to swipe delete the source
  <img width=300 src=https://user-images.githubusercontent.com/17010094/112820192-4c478780-907d-11eb-9199-4b287a595f71.png>


</details>
<details>
<summary><b>Brave Today Feed</b></summary>

- Verified custom source feed shows up in Brave Today
- Verified able to long press and disable custom feed source

https://user-images.githubusercontent.com/17010094/112821828-12778080-907f-11eb-9c88-9e471ebbf153.MP4

</details>
</details>

-----------------------

Verification passed on iPad Pro with iOS 14.4.2 running 1.24(21.3.25.18)

<details>
<summary>Verified test plan from <a href=https://github.com/brave/brave-ios/pull/3317>#3317</a></summary>
<br>
<details>
<summary><b>Add Source page</b></summary>

- Verified able to add a site to Brave Today feed by visiting the site and adding it via share sheet

https://user-images.githubusercontent.com/17010094/112824593-a26af980-9082-11eb-98e0-643d63793b28.MP4

- Verified unsupported sites don't show option to add source via share sheet

https://user-images.githubusercontent.com/17010094/112825033-2de48a80-9083-11eb-9370-c90fbc5cc32d.MP4

- Verified able to add sites manually 

https://user-images.githubusercontent.com/17010094/112824008-e8738d80-9081-11eb-8a27-05ce1f48b7df.MP4

</details>
<details>
<summary><b>Brave Today Settings</b></summary>

- Verified able to add sites with multiple feeds
  <img width=500 src=https://user-images.githubusercontent.com/17010094/112822812-515a0600-9080-11eb-9a79-53eea0c1740f.png>

- Verified able to add sites with single feed
  <img width=500 src=https://user-images.githubusercontent.com/17010094/112822856-633ba900-9080-11eb-881a-b62ce9037015.png>

- Verified adding an insecure source shows warning
  <img width=500 src=https://user-images.githubusercontent.com/17010094/112822874-6898f380-9080-11eb-9701-a43a972d355b.png>

- Verified adding an unsupported domain manually shows warning
  <img width=500 src=https://user-images.githubusercontent.com/17010094/112822889-6df63e00-9080-11eb-9802-94bdd021678e.png>

- Verified once 5 source limit is reached, adding a new source throws error 
  <img width=500 src=https://user-images.githubusercontent.com/17010094/112822908-76e70f80-9080-11eb-990f-c2e64ab82755.png>

- Verified able to swipe delete the source
  <img width=500 src=https://user-images.githubusercontent.com/17010094/112822922-7c445a00-9080-11eb-9767-5860e922ebf6.png>

</details>
<details>
<summary><b>Brave Today Feed</b></summary>

- Verified custom source feed shows up in Brave Today
- Verified able to long press and disable custom feed source

https://user-images.githubusercontent.com/17010094/112823513-4bb0f000-9081-11eb-9396-ece3c288d10c.MP4

</details>
</details>
