### ISSUE TITLE
Text is not visible when editing a favourite/bookmark in dark mode - Follow up to #2644

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3250]
### Description: 

Text is really light/hard to read when editing bookmarks/favourites. This a follow up to https://github.com/brave/brave-ios/issues/2644.

### Steps to Reproduce 

  1. launch `1.23 (21.1.28.17)`
  2. switch over to `Private` mode
  3. edit a bookmark/favourite under NTP

**Actual result:** 

![IMG_0093](https://user-images.githubusercontent.com/2602313/106561428-a4876080-64f6-11eb-9351-cbec0e1e6566.png)

**Expected result:**

![IMG_3522](https://user-images.githubusercontent.com/2602313/106561098-190dcf80-64f6-11eb-9efe-0af24e358639.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.23 (21.1.28.17)`

**Device details:** 

* `iPhone 6s+` using `iOS 12.4.1`

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @soner-yuksel @iccub @srirambv @bsclifton @aekeus

**Comment by kjozwiak** [comment]
We'll use https://github.com/brave/brave-ios/issues/2644 as for the release notes as it has more info/context.

**Comment by soner-yuksel** [comment]
@kjozwiak What you found out is an edge case that only happens when the browser is private mode using iOS12. 
I have a hack for for solving this case. Will open a PR soon.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.23 (21.2.5.15)`

**`Normal Mode`** | **`Private Mode`**
---------------------|---------------------
![IMG_0104](https://user-images.githubusercontent.com/2602313/107427335-4a3a6100-6aef-11eb-9aa9-cacb8ec1c059.png) | ![IMG_0105](https://user-images.githubusercontent.com/2602313/107427344-4d355180-6aef-11eb-8653-463d0e962ed9.png)

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS12.4.1 running 1.23(21.2.5.14)

Normal Tab | Private Tab
-- | --
![image](https://user-images.githubusercontent.com/17010094/107502378-7fe35680-6b90-11eb-8a6c-6950710ea1fe.png) | ![image](https://user-images.githubusercontent.com/17010094/107502406-84a80a80-6b90-11eb-9053-af5eeac30ae4.png)
