### ISSUE TITLE
Handle Brave Today promoted content events

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#3251]
Register views and clicks on promoted content in Brave Today via the internal ads library using the `OnPromotedContentEvent` API call. (1.21.x)

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4.2 running 1.24(21.3.25.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3450
- Verified got ` Failed to fire promoted content ad event for uuid` when promoted content is opened in same tab/new tab (more info on it here https://bravesoftware.slack.com/archives/CU56GUJ1H/p1615487643036800)
- Verified no promoted content logs shown when opening promoted content in a private tab
----------------
Verification passed on iPhone XR with iOS 13.5 running 1.24(21.3.25.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3450
- Verified got ` Failed to fire promoted content ad event for uuid` when promoted content is opened in same tab/new tab
- Verified no promoted content logs shown when opening promoted content in a private tab
------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.24(21.3.25.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3450
- Verified got ` Failed to fire promoted content ad event for uuid` when promoted content is opened in same tab/new tab 
- Verified no promoted content logs shown when opening promoted content in a private tab
