### ISSUE TITLE
active tab indicator for both normal/private tabs broken

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3253]
### Description: 

Looks like the UI to indicate which tab is currently the active tab has regressed in `1.23.x`. It's almost impossible to tell which tab is currently active and even harder to distinguish between tabs in private mode.

### Steps to Reproduce

  1. download/install `1.23 (21.1.28.17)` from TF
  2. open two tabs in normal mode and notice it doesn't highlight the active tab
  3. open two tabs in private tab and you'll notice it's even harder to distinguish tabs

**Actual result:** 

**`Normal Tab`** | **`Private Tab`**
-------------------|-------------------
![IMG_3536](https://user-images.githubusercontent.com/2602313/106715810-8fc8cc80-65cb-11eb-885e-e654bdd3e225.png) | ![IMG_3537](https://user-images.githubusercontent.com/2602313/106715854-9f481580-65cb-11eb-8e28-0e1e76ca3dda.png)

**Expected result:**

**`Normal Tab`** | **`Private Tab`**
-------------------|-------------------
![IMG_3534](https://user-images.githubusercontent.com/2602313/106715850-9ce5bb80-65cb-11eb-850b-e299f12f3ec5.png) | ![IMG_3535](https://user-images.githubusercontent.com/2602313/106715822-92c3bd00-65cb-11eb-9ff1-2606875fb974.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.23 (21.1.28.17)`

**Device details:** 

* `iPad Air (3rd Gen)` on `iOS 14.3` - **Reproduced**
* `iPad Mini 4` on `iOS 13.7` - **Reproduced**
* `iPhone 11` on `iOS 14.4` - **Reproduced**
* `iPhone 6+` on `iOS 12.4.1` - **Reproduced**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @iccub @soner-yuksel @bsclifton @srirambv @anthonypkeane

**Comment by iccub** [comment]
Fixed in https://github.com/brave/brave-ios/pull/3252

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 14.4` using `1.23 (21.2.5.15)`

**`Normal Mode`** | **`Private Mode`**
---------------------|---------------------
![IMG_3542](https://user-images.githubusercontent.com/2602313/107425643-3988eb80-6aed-11eb-9b38-356272da3e20.png) | ![IMG_3543](https://user-images.githubusercontent.com/2602313/107425655-3c83dc00-6aed-11eb-89d8-f90ccb3512d6.png)

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.4` using `1.23 (21.2.5.15)`

**`Normal Mode`** | **`Private Mode`**
---------------------|---------------------
![IMG_0196](https://user-images.githubusercontent.com/2602313/107426432-37735c80-6aee-11eb-8f75-8ecd3ca30344.png) | ![IMG_0197](https://user-images.githubusercontent.com/2602313/107426486-49ed9600-6aee-11eb-8f8b-3b08a88399b9.png)

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.23 (21.2.5.15)`

**`Normal Mode`** | **`Private Mode`**
---------------------|---------------------
![IMG_0446](https://user-images.githubusercontent.com/2602313/107426803-b2d50e00-6aee-11eb-99c7-cbf1c610fdd2.png) | ![IMG_0447](https://user-images.githubusercontent.com/2602313/107426815-b5cffe80-6aee-11eb-983d-d725a708774a.png)


Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.23 (21.2.5.15)`

**`Normal Mode`** | **`Private Mode`**
---------------------|---------------------
![IMG_0102](https://user-images.githubusercontent.com/2602313/107426038-bb791480-6aed-11eb-979a-b18ae80e0bbf.png) | ![IMG_0103](https://user-images.githubusercontent.com/2602313/107426053-be740500-6aed-11eb-90f3-0c1111ff12e2.png)
