### ISSUE TITLE
Shields menu is unavailable with reader mode enabled

### ISSUE THREAD

**Issue by ianrahman** [brave/brave-ios#3255]
### Description: 
The shields menu next to the URL base is unavailable with reader mode enabled. 

### Steps to Reproduce 
  1. Navigate to any page that supports reader mode, such as a Wikipedia article. 
  2. Enable reader mode by tapping the reader mode icon in the URL bar. 
  3. Tap on the Brave logo next to the refresh icon in the URL bar. 

**Actual result:** 
The tap gesture does not appear to have any effect. 

**Expected result:**
The shields menu opens. 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always. 

**Brave Version:** 
Version 1.22.2 (21.1.21.11)

**Device details:** 
iPhone 12 Pro Max, iOS 14.4

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 
N/A

**Comment by iccub** [comment]
This is intentional, Shields menu work only for regular websites, not the one we host with a localhost, which is reader mode pages or the new tab page
