### ISSUE TITLE
Reader mode is unavailable with scripts blocked

### ISSUE THREAD

**Issue by ianrahman** [brave/brave-ios#3256]
### Description: 
Reader mode is unable to be activated if the shield to block scouts is enabled. 

### Steps to Reproduce 
  1. Navigate to any page that supports reader mode, such as a Wikipedia article. 
  2. Open the shields menu from the top navigation bar. 
  3. Enable the shield to block scripts. 

**Actual result:** 
The reader mode icon usually available in the URL bar disappears. 

**Expected result:**
Reader mode is available for use. 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always. 

**Brave Version:** 
Version 1.22.2 (21.1.21.11)

**Device details:** 
iPhone 12 Pro Max, iOS 14.4

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 
N/A

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 11` running `iOS 14.6` using `1.27 (21.6.10.21)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.5` using `1.27 (21.6.10.21)`

**`Test Case #1`**

* enabled `Blocked Scripts` globally via `Brave Shields & Privacy` under `Settings`
* visited https://www.techpowerup.com/review/nvidia-geforce-rtx-3080-ti-founders-edition/
* ensured that the reader mode icon was visible and working as expected

**`Test Case #2`**

* visit https://videocardz.com/newz/nvidia-launches-geforce-rtx-3070-ti-with-6144-cuda-cores-and-8gb-gddr6x-memory-at-599-usd and enable `Block Scripts` via the shields panel
* ensured that the reader mode icon was visible and working as expected

----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.27(21.6.10.21)
- Verified load a page in reader mode with script blocking enabled on the page
- Verified able to load a page in reader mode with script blocking enabled globally
- Verified reader mode settings are retained on other sites when scripts are blocked per site and globally
----------
Verification passed on iPad Pro with iOS 14.5.1 running 1.27(21.6.10.21)
- Verified load a page in reader mode with script blocking enabled on the page
- Verified able to load a page in reader mode with script blocking enabled globally
- Verified reader mode settings are retained on other sites when scripts are blocked per site and globally
