### ISSUE TITLE
Reader mode is broken with the global shield to block scripts enabled

### ISSUE THREAD

**Issue by ianrahman** [brave/brave-ios#3257]
### Description: 
Enabling the global shield setting to block scripts breaks the reader view, even when the page-specific setting is set to allow scripts. 

### Steps to Reproduce 
  1. Open the global shields menu and set Block Scripts to on. 
  2. Navigate to any webpage that supports reader mode, such as a Wikipedia article. 
  3. Open the shields menu from the top navigation bar and expand the advanced controls. 
  4. Turn Block Scripts off, then dismiss the menu. 
  5. Tap the reader mode icon in the URL bar. 

**Actual result:** 
A blank page is displayed. 

**Expected result:**
The current page is displayed in reader mode. 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
Version 1.22.2 (21.1.21.11)

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Note that this is *not* the same as previously reported issue: https://github.com/brave/brave-ios/issues/3256

In this case, reader mode is available, but broken.

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 11` running `iOS 14.6` using `1.27 (21.6.10.21)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.5` using `1.27 (21.6.10.21)`

Went through the STR/Cases outlined via https://github.com/brave/brave-ios/issues/3257#issue-800288007 and ensured that the page wasn't blank once tapping on reader mode when `Block Scripts` has been disabled via the shields panel.

-------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.27(21.6.10.21)
- Verified steps from issue description
