### ISSUE TITLE
Add support for server/geo selection

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3267]
### Description: 

Please see GDrive "Brave VPN on iOS - V2" for more info.

Add support for server/geo selection

Please upload final screenshots here once dev completed to aid QA

**Comment by anthonypkeane** [comment]
@iccub can we close this out now?

**Comment by iccub** [comment]
Yes, closing as duplicate of https://github.com/brave/brave-ios/issues/2934
