### ISSUE TITLE
Unable to browse http://configure.bmw.ca/en_CA/configure/F22/2020/P0300

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-ios#3272]
### Description: 
Unable to open http://configure.bmw.ca/en_CA/configure/F22/2020/P0300

### Steps to Reproduce 
  1. Open http://configure.bmw.ca/en_CA/configure/F22/2020/P0300
  2. Get past the cookie consent check
  3. Get an instant  error "Unfortunately an error occurred "

**Actual result:** 
![unnamed (8)](https://user-images.githubusercontent.com/1659004/107136594-b4c19480-6969-11eb-9b81-cb36fcc7e2b4.jpg)

**Expected result:**
Show website, without error.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily, refreshing the tab.

**Brave Version:** 
Brave IOS 1.22.2 (21.1.21.11) and Brave IOS Dev 1.24 (21.2.2.19)

**Device details:** 
Iphone 8plus

**Website problems only:**
- did you check with Brave Shields down? Yes
- did you check in Safari/Firefox (WkWebView-based browsers)?  Safari is fine, Firefox show the same issue.

### Additional Information
Shields down doesn't help.

**Comment by ProgramComputer** [comment]
As of 1.25, issue is resolved.

**Comment by ryanbr** [comment]
@ProgramComputer  what was the fix?

**Comment by iccub** [comment]
Seems to behave same as on safari iOS, shows error after region selection then works fine on refresh
