### ISSUE TITLE
"Sources & Settings" under intro card sometimes uses grey text

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3290]
### Description: 

Sometimes the `Sources & Settings` string uses grey text rather than the expected white text. When this happens, it's harder to read as the background of the intro card is grey as well.

### Steps to Reproduce 

I don't really have STR as I've only seen this happen twice. But it usually happens after opening an article from Brave Today. @brave/legacy_qa if you run into this and can reliably reproduce, please update STR 👍 

**Actual result:** 

![image](https://user-images.githubusercontent.com/2602313/107608009-b957a880-6c08-11eb-9d10-b4a871ce3503.png)

**Expected result:**

![image](https://user-images.githubusercontent.com/2602313/107608034-c4123d80-6c08-11eb-92b8-b8662ec5ab54.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

I've only seen this happen a few times so it seems rare but 

**Brave Version:** 

* Reproduced using `1.23 (21.2.10.18)`

**Device details:** 

* `iPhone 11` running `iOS 14.4` using `1.23 (21.2.10.18)` - **Reproduced**
* `iPad Air (3rd Gen)` running `iOS 14.4` using `1.23 (21.2.10.18)` - **Reproduced**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @karenkliu @anthonypkeane @srirambv @bsclifton @iccub @kylehickinson @soner-yuksel

**Comment by kjozwiak** [comment]
I didn't add this into `1.23` as I don't think it's a blocker/something we need to fix ASAP. It's also pretty rare and users won't see it once they've closed the intro card. Plus, I don't really have reliable STR. @anthonypkeane @bsclifton please add it into `1.23` if you feel differently 👍

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.24(21.3.24.11)

iPhone 7+ (iOS 14.4) | iPhone XR (iOS 13.5) | iPad Pro (iOS 12.4.1)
-- | -- | -- 
<img width=350 src=https://user-images.githubusercontent.com/17010094/112318434-ef2a8b00-8ca4-11eb-9dc2-b43b587aa0e0.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/112318583-1719ee80-8ca5-11eb-81ee-0f01a38d11b0.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/112318384-e2a63280-8ca4-11eb-9daa-db13ca05e35e.png>
