### ISSUE TITLE
Intermittent crash when scrolling page while educational notification appearing

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3291]
### Description: 

When on a new profile, scrolling through a website right after it loads while one of the educational notifications from https://github.com/brave/brave-ios/issues/2980 starts loading will intermittently crash the browser. I've ran into this one three different times but can't seem to reproduce often.

Created an issue so we can track/aware that we have a crash for the above scenario.

### Steps to Reproduce

  1. clean install `1.23 (21.2.10.18)`
  2. scroll through Brave Today and select a random article from the feed
  3. once it starts loading, start scrolling through the website
  4. hopefully one of the notifications from https://github.com/brave/brave-ios/issues/2980 is triggered

While the notification appears, Brave will sometimes freeze and crash after ~10s.

**Note:** Crashed twice using the following:
* https://www.theverge.com/2021/2/10/22277540/star-wars-severs-ties-the-mandalorian-gina-carano-cara-dune

**Actual result:** 

Brave freezing/crashing.

**Expected result:**

Brave shouldn't be crashing.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

It's hard to reproduce but there's definitely a crash somewhere there.

**Brave Version:** 

* Reproduced three times using `1.23 (21.2.10.18)`

**Device details:** 

`iPhone 11` running `iOS 14.4` using `1.23 (21.2.10.18)` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @anthonypkeane @srirambv @bsclifton @iccub @kylehickinson @soner-yuksel

**Comment by kjozwiak** [comment]
@bsclifton @anthonypkeane I added this into the `1.23` milestone in case one of the devs can reproduce this. I've crashed ~3-4 times so there's definitely an issue somewhere but it's hard to pinpoint. If we manage to fix it, great. If not, we can leave it opened till we get more info from our crash rates or someone from the community finds better STR.

**Comment by kylehickinson** [comment]
@kjozwiak If you can, please obtain a crash log from your device

See **_Transfer Crash Reports and Device Logs To a Mac_** or **_Locate Crash Reports and Memory Logs on the Device_** on https://developer.apple.com/documentation/xcode/diagnosing_issues_using_crash_reports_and_device_logs/acquiring_crash_reports_and_diagnostic_logs

Otherwise, without reproducing locally we have to wait until the crash logs upload to TestFlight

**Comment by kjozwiak** [comment]
@kylehickinson STR (hopefully this helps with the crash logs)

* install the latest TF Beta (`1.23 (21.2.11.13)` in this case)
* skip all onboarding
* ensure that you have https://www.theverge.com/2021/2/10/22277540/star-wars-severs-ties-the-mandalorian-gina-carano-cara-dune in your clipboard/copied
* paste the above using `Paste & Go`
* once the page starts loading, start swiping down before the `Trackers & ads blocked on this page` education modal appears (this one should be red/organe)

Sometimes you'll get a crash just doing ☝️ If it doesn't crash,

* close the tab with https://www.theverge.com/2021/2/10/22277540/star-wars-severs-ties-the-mandalorian-gina-carano-cara-dune
* restart Brave
* close all onboarding/modals that might appear after restarting
* ensure that you still have https://www.theverge.com/2021/2/10/22277540/star-wars-severs-ties-the-mandalorian-gina-carano-cara-dune in your clipboard/copied
* paste the above using `Paste & Go`
* once the page starts loading, start swiping down before the `+10 trackers & ads blocked on this page` education modal appears (this one should be blue)

Crash Logs --> [Client-2021-02-11-131319.txt](https://github.com/brave/brave-ios/files/5967749/Client-2021-02-11-131319.txt)

Let me know if there's anything else that I can get 👍

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4 running 1.23(21.2.12.9)
- Verified test plan from issue description and https://github.com/brave/brave-ios/issues/3291#issuecomment-777709788
- Verified no crash when scrolling page and tooltip shows up

---
Verification passed on iPhone XR with iOS 13.5 running 1.23(21.2.12.9)
- Verified test plan from issue description and https://github.com/brave/brave-ios/issues/3291#issuecomment-777709788
- Verified no crash when scrolling page and tooltip shows up
------
Verification passed on iPad Pro with iOS 12.4.1 running 1.23(21.2.12.9)
- Verified test plan from issue description and https://github.com/bave/brave-ios/issues/3291#issuecomment-777709788
- Verified no crash when scrolling page and tooltip shows up


iPhone 7+ (iOS 14.4) | iPhone XR (iOS 13.5) | iPad Pro (iOS 12.4.1)
-- | -- | --
<img width=370 src=https://user-images.githubusercontent.com/17010094/107780342-7b5ca080-6d3e-11eb-9ce9-06dc2c238027.png> | <img width=310 src=https://user-images.githubusercontent.com/17010094/107780999-4bfa6380-6d3f-11eb-925b-0e4dac29203f.png> | <img width=500  src=https://user-images.githubusercontent.com/17010094/107781048-5b79ac80-6d3f-11eb-9f19-c1c486244182.png>
