### ISSUE TITLE
Educational notifications/modals should be displayed once per session

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3296]
### Description: 

We're currently showing multiple educational notifications/modals from https://github.com/brave/brave-ios/issues/2980 in the same session as reported by @srirambv. However, as per @karenkliu, we should only be showing one notification/modal per session as per:

```
We only show them one at a time so we can't show both if more than 1 condition is satisfied
```

Android is currently following the above so we'll need to make sure iOS matches the above as well.

### Steps to Reproduce

  1. launch `1.23 (21.2.10.18)` from TF
  2. open amazon.com
  3. you'll notice that you'll get the `Trackers & ads blocked on this page.` notification/modal (red)
  4. dismiss the first notification and you'll get the `Your connection is now encrypted.` (blue) right after (same session)

As per the spec, we shouldn't be getting back to back notifications/modals.

**Actual result:** 

Currently showing multiple educational notifications/modals from https://github.com/brave/brave-ios/issues/2980 in the same session.

**Expected result:**

Shouldn't be showing multiple educational notifications/modals in the same session.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Reproducible 100% using STR/Cases mentioned above.

**Brave Version:** 

Reproduced using `1.23 (21.2.10.18)` from TF

**Device details:** 

* `iPhone 11` running `iOS 14.4` using `1.23 (21.2.10.18)` - **Reproduced**
* `iPad Air (3rd Gen)` running `iOS 14.4` using `1.23 (21.2.10.18)` - **Reproduced**
* `iPad Mini 4` running `iOS 13.7` using `1.23 (21.2.10.18)` - **Reproduced**
* `iPhone 6s+` running `iOS 12.4.1` using `1.23 (21.2.10.18)` - **Reproduced**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

@bsclifton @anthonypkeane @karenkliu @soner-yuksel @srirambv

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4 running 1.23(21.2.12.5)
- Verified steps from issue description
- Verified only one tooltip is shown per session even if multiple conditions are met
- ------
Verification passed on iPhone XR with iOS 13.5running 1.23(21.2.12.5)
- Verified steps from issue description
- Verified only one tooltip is shown per session even if multiple conditions are met
------
Verification passed on iPad Pro with iOS 12.5running 1.23(21.2.12.5)
- Verified steps from issue description
- Verified only one tooltip is shown per session even if multiple conditions are met
