### ISSUE TITLE
Limit Open Search engine additions to regular mode only

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#3300]
From: https://github.com/brave/brave-ios/pull/3231/#issuecomment-777828670

### Description: 
Open Search engines added in private mode, persist across regular mode.

### Steps to Reproduce 
  1. Navigate to search.lilo.org 
  2. Click on the search bar, and add to `Custom Search` or add custom search engine another way manual or auto
  3. Navigate Search Engine  settings and check Standard tab engine list has new custom engine 
  4. Navigate Private tab and check new search engine is not inside  

**Actual result:** 
Open Search addition works in private mode

**Expected result:**
Addition should only work in regular mode

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ (iOS 14.4) running 1.24(21.3.24.11)
- Verified adding custom SE in private tab works
- Custom SE can only be set for normal tabs

https://user-images.githubusercontent.com/17010094/112475492-c53a9c80-8d68-11eb-980b-a01b7d98be7e.MP4

-------------------
Verification passed on iPhone XR (iOS 13.5) running 1.24(21.3.24.11)
- Verified adding custom SE in private tab works
- Custom SE can only be set for normal tabs

https://user-images.githubusercontent.com/17010094/112476190-8eb15180-8d69-11eb-934a-dd2e648df25f.MP4

----------------------
- Verification passed on iPad Pro (iOS 12.4.1) running 1.24(21.3.24.11)
- Verified adding custom SE in private tab works
- Custom SE can only be set for normal tabs

https://user-images.githubusercontent.com/17010094/112479318-d71e3e80-8d6c-11eb-950d-abaf07cf2a1a.MP4
