### ISSUE TITLE
sharing credentials via third party password managers doesn't work

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3301]
### Description: 

Looks like sharing passwords via `Share with...` from third party password managers like 1Password has regressed. Once you've selected the credentials from 1password, the username and password are not being filled in. This works using `1.22.2 (21.1.21.11)` so it regressed somewhere within `1.23`.

### Steps to Reproduce
 
  1. ensure you have 1password installed
  2. install `1.23 (21.2.11.13)`
  3. visit a website that you have credentials within 1password (used LinkedIn in this came)
  4. tap on `Share with..` and select 1password (pick the LinkedIn credentials)

You'll notice nothing is being filled into the username and password fields.

**Actual result:** 

Both username and passwords are not being filled into websites from third party password managers

**Expected result:**

Should be able to fill in both username and password using third party password managers

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR mentioned above.

**Brave Version:** 

Reproduced using `1.23 (21.2.11.13)`

**Device details:** 

* `iPhone 11` running `iOS 14.4` using `1.23 (21.2.11.13)` - **Reproduced**
* `iPad Air (3rd Gen)` running `iOS 14.4` using `1.23 (21.2.11.13)` - **Reproduced**
* `iPad Mini 4` running `iOS 13.7` using `1.23 (21.2.11.138)`  - **Reproduced**
* `iPhone 6s+` running `iOS 12.4.1` using `1.23 (21.2.11.13)` - **Reproduced**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @bsclifton @anthonypkeane @iccub @soner-yuksel @kylehickinson @srirambv

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.23(21.2.12.5)
- Verified steps from issue description
- Verified able to perform autofill using third-party password managers
--------
Verification passed on iPhone 7+ with iOS 14.4running 1.23(21.2.12.5)
- Verified steps from issue description
- Verified able to perform autofill using third-party password managers
--------
Verification passed on iPad Pro with iOS 12.4.1running 1.23(21.2.12.5)
- Verified steps from issue description
- Verified able to perform autofill using third-party password managers
