### ISSUE TITLE
Editing favourite causes icon to be blurry/sharp

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3304]
### Description: 
Editing favourite causes icon to be blurry/sharp

### Steps to Reproduce 
  1. Install 1.23(21.2.12.5)
  2. Add `https://espn.in` as a favourite
  3. Edit the favourite to be `https://espn.com`, favicon becomes blurry

**Actual result:** 
https://bravesoftware.slack.com/archives/C06UXF3KJ/p1613058409135300

**Expected result:**
Favicon should remain same irrespective of domain name change

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.23(21.2.12.5)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA 
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
Follow-up to #2679

**Comment by cuba** [comment]
@iccub  It's not the editing that causes the blurriness. The `espn.com` icon is blurry whilst the `espn.in` icon is not. It just seems to be an issue with the favicon itself.

**Comment by iccub** [comment]
closing in favor of https://github.com/brave/brave-ios/issues/6066
