### ISSUE TITLE
[Follow-up #3046] Add universal link handler for buy-vpn screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3308]
### Description: 
[Follow-up #3046] Add universal link handler for buy-vpn screen

### Steps to Reproduce 
  1. Follow steps from https://github.com/brave/brave-ios/pull/3105 on iOS 14/12 devices

**Actual result:** 
Opening a link via Safari loads brave.com page instead of switching to Brave

**Expected result:**
Should load VPN settings

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.23

**Device details:** 
iOS 14 & iOS 12 devices. Works fine on iOS 13

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

**Comment by iccub** [comment]
Tested it today on app store build and it still does not work for me

**Comment by srirambv** [comment]
Still reproduces for me on the AppStore build https://youtu.be/2tWsNTHtVCw

**Comment by iccub** [comment]
Related ticket https://github.com/brave/brave-com-resources/issues/246

**Comment by iccub** [comment]
Can't be done technically due to default browser entitlement limitations
https://developer.apple.com/documentation/xcode/allowing_apps_and_websites_to_link_to_your_content/preparing_your_app_to_be_the_default_browser_or_email_client
