### ISSUE TITLE
update translations for tooltip

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3310]
Please refer to the following re: what the new translations should be for the tooltip
* https://github.com/brave/internal/issues/747#issuecomment-778463314

**Comment by kjozwiak** [comment]
@kylehickinson mind closing this one off once https://github.com/brave/brave-ios/pull/3309 landed and new TF builds are available?

**Comment by kylehickinson** [comment]
Sure, sorry didn't realize a separate issue was opened. I will link this one to #3309

**Comment by kjozwiak** [comment]
no worries, I just created it ~5min ago. It's easier to follow when there's a separate issue rather than QAing/updating issues that have already been checked/labeled as verified 👍

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 11` running `iOS 14.4` using `1.23 (21.2.12.22)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.4` using `1.23 (21.2.12.22)`
* Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.23 (21.2.12.22)`
* Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.23 (21.2.12.22)`

Verification notes can be found via https://github.com/brave/internal/issues/747#issuecomment-778521329.
