### ISSUE TITLE
Brave Shield breaks QR codes on systembolaget.se

### ISSUE THREAD

**Issue by Dyras** [brave/brave-ios#3311]
### Description: 
Hello! At Systembolaget (The liquor store chain in Sweden) you pick up your ordered liquor at a store by scanning a QR code.

The problem is that this QR code is blocked by Brave Shield on iOS. Haven't tried on Android.

### Steps to Reproduce 
  1. Go to https://www.systembolaget.se/hamta-i-butik/E10000000/
  2. Notice that the QR-code isn't working
  3. Disable Brave Shield
  4. Notice that the QR-code is now working

**Actual result:** The QR-code is blocked by Brave Shield

**Expected result:** The QR-code isn't blocked

**Reproduces how often:** Easily reproduced

**Brave Version:** 1.22.2 (21.1.21.11)

**Device details:**  iPhone 8 (iOS 14.4)

**Website problems only:**
- did you check with Brave Shields down? Yes
- did you check in Safari/Firefox (WkWebView-based browsers)?  Yes, it works

### Additional Information 
The links are delivered with a short URL in the text message, if that matters
http://kb.sbol.ag/E10000000

**Comment by iccub** [comment]
seems to work now
