### ISSUE TITLE
Trying to build brave-ios on Apple Silicon Mac

### ISSUE THREAD

**Issue by xologram** [brave/brave-ios#3314]
### Description: 
I cannot build brave-ios (trying development branch for opensearch goodness) on m1 macbook. 

### Steps to Reproduce 
  1. git clone https://github.com/brave/brave-ios.git
  2. install dependencies from README.md
  3. run sh ./bootstrap.sh

**Actual result:** 
fails on electron install:

npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /opt/homebrew/Cellar/node/15.8.0/bin/node /opt/homebrew/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Us
ers/xologram/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /Users/xologram/.npm/_cacache/tmp/git-clone-8126cc95/node_modules/electron
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c node install.js
Downloading tmp-5254-0-electron-v5.0.0-darwin-arm64.zip
npm ERR! npm ERR! Error: GET https://github.com/electron/electron/releases/download/v5.0.0/electron-v5.0.0-darwin-arm64.zip returned 404
npm ERR! npm ERR! /Users/xologram/.npm/_cacache/tmp/git-clone-8126cc95/node_modules/electron/install.js:49
npm ERR! npm ERR!   throw err
npm ERR! npm ERR!   ^
npm ERR! npm ERR!
npm ERR! npm ERR! Error: Failed to find Electron v5.0.0 for darwin-arm64 at https://github.com/electron/electron/releases/download/v5.0.0/electron-v5.0.0-darwin-arm64.zip
npm ERR! npm ERR!     at Request.<anonymous> (/Users/xologram/.npm/_cacache/tmp/git-clone-8126cc95/node_modules/nugget/index.js:169:61)
npm ERR! npm ERR!     at Request.emit (node:events:378:20)
npm ERR! npm ERR!     at Request.onRequestResponse (/Users/xologram/.npm/_cacache/tmp/git-clone-8126cc95/node_modules/request/request.js:1066:10)
npm ERR! npm ERR!     at ClientRequest.emit (node:events:378:20)
npm ERR! npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:636:27)
npm ERR! npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:129:17)
npm ERR! npm ERR!     at TLSSocket.socketOnData (node:_http_client:502:22)
npm ERR! npm ERR!     at TLSSocket.emit (node:events:378:20)
npm ERR! npm ERR!     at addChunk (node:internal/streams/readable:313:12)
npm ERR! npm ERR!     at readableAddChunk (node:internal/streams/readable:288:9)
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/xologram/.npm/_logs/2021-02-15T19_57_18_570Z-debug.log

**Expected result:**
dependencies installed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
latest 

**Device details:** 
M1 Macbook pro

Is it not possible to build brave-ios from m1 mac?

**Comment by kylehickinson** [comment]
Hi @xologram, this is a known issue and unfortunately `brave-ios` cannot be compiled **to a simulator target** at this time using an M1 Mac. You can however build to a device instead as a workaround.

We're working on getting this working and have it most of the way done, but we have 1 dependency that we are waiting on still to support arm64 simulator slices.

**Comment by xologram** [comment]
Thank you for your reply and suggestion, I will try to build to a device.

**Comment by iccub** [comment]
I would keep this ticket open until we fix it, more people can encounter this problem
