### ISSUE TITLE
Implement domain specific data saved estimation

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3316]
### Description: 
Please search for "Domain Specific Data Saved" on GDrive for a spec

- [x] Implement design
- [x] Implement a way to store the domain specific data 
- [ ] QA

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.28(21.7.8.16)
- Verified test plan from https://github.com/brave/brave-ios/pull/3750
- Verified domain specific saved estimation modal is only shown when all other educational ones are shown
- Verified visiting an unlisted site such as `https://cnn.com` doesn't show the modal
- Verified visiting a listed site shows the modal only once
- Verified quit and relaunch and re-visiting the same site doesn't show the modal a second time
- Verified selecting `Don't show this again` doesn't show the modal anymore

![image](https://user-images.githubusercontent.com/17010094/125068728-b7a5ea00-e0ad-11eb-95ea-6bc4ccc648a4.png) | ![image](https://user-images.githubusercontent.com/17010094/125068673-a78e0a80-e0ad-11eb-86ef-906605e8bfd1.png)
-- | --

------------------------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.28(21.7.8.16)
- Verified test plan from https://github.com/brave/brave-ios/pull/3750
- Verified domain specific saved estimation modal is only shown when all other educational ones are shown
- Verified visiting an unlisted site such as `https://cnn.com` doesn't show the modal
- Verified visiting a listed site shows the modal only once
- Verified quit and relaunch and re-visiting the same site doesn't show the modal a second time
- Verified selecting `Don't show this again` doesn't show the modal anymore

![image](https://user-images.githubusercontent.com/17010094/125068527-7ca3b680-e0ad-11eb-97ac-2db7589a49a1.png) | ![image](https://user-images.githubusercontent.com/17010094/125068577-8a593c00-e0ad-11eb-999e-8eba4e2a6587.png)
-- | --

------------------------
Verification passed on iPad Pro with iOS 14.6 running 1.28(21.7.8.16)
- Verified test plan from https://github.com/brave/brave-ios/pull/3750
- Verified domain specific saved estimation modal is only shown when all other educational ones are shown
- Verified visiting an unlisted site such as `https://cnn.com` doesn't show the modal
- Verified visiting a listed site shows the modal only once
- Verified quit and relaunch and re-visiting the same site doesn't show the modal a second time
- Verified selecting `Don't show this again` doesn't show the modal anymore

![image](https://user-images.githubusercontent.com/17010094/125070471-e9b84b80-e0af-11eb-9c6c-1ce543474706.png) | ![image](https://user-images.githubusercontent.com/17010094/125070491-f046c300-e0af-11eb-90c6-62fdec8e088d.png)
-- | --
