### ISSUE TITLE
Display certificate information for a secure site

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#3324]
## Problem Description 
Certificate information for an HTTPS site is not available on UI

## Feature Overview 
1. On clicking the lock icon in the address bar the certificate information should be displayed.

**Comment by Uni-verse** [comment]
Verification in progress using `1.38 (22.4.25.21)`

**Devices:** 
`iPhone 12 Pro` | `iOS 15.4`
`iPhone X` | `iOS 14.4.2`
`iPad (7th Gen)` | `iOS 15.2.1`

**Clean Install**

- Tapping lock icon in the `url bar` will show the modal with certificate information.
- Once the certificate viewer is open, tapping anywhere outside the modal will dismiss it. 
- Certificate viewer will not be shown when navigating to a webpage that doesn't use `HTTPS`.
- Insecure webpages are be indicated with the exclamation mark icon. 
- Certificate viewer will respect `Appearance` settings (light, dark, automatic).
- Certificate viewer will display invalid certs when visiting `badssl.com`
- Certificate viewer shown when tapping lock icon in landscape. 
- Confirmed certificate viewer will be displayed correct when enabling `bookmarks shortcut` option in the settings.


**Upgraded Profile**

- Confirmed certificate viewer is functional on an upgraded profile.
- Able to display valid and invalid certificate information. 

**Issues encountered**: Certificate view not translated (issue TBD)

1 | 2 | 3 | 4 | 5 | 6 | 7 | 8
-|-|-|-|-|-|-|-
![IMG_0263](https://user-images.githubusercontent.com/17885425/165800822-db7873bb-7884-4d8e-a029-0400f1cf92f3.PNG) | ![IMG_0264](https://user-images.githubusercontent.com/17885425/165800827-465ae7f9-3ac3-4eaf-94b1-48c5ba2a91a5.PNG) | ![IMG_0265](https://user-images.githubusercontent.com/17885425/165800830-2bb8f3df-d0de-4a06-bb2f-b3dfd6804cd8.PNG) | ![IMG_0266](https://user-images.githubusercontent.com/17885425/165800835-f5ef72ab-81d6-4e54-8594-2d4d458b1896.PNG) | ![IMG_2653](https://user-images.githubusercontent.com/17885425/165800838-4c572d38-92a3-494a-9c78-791491cbaf2f.PNG) | ![IMG_2654](https://user-images.githubusercontent.com/17885425/165800842-f310f1b2-11bc-46b4-aaae-01e47bd633d5.PNG)  | ![IMG_2655](https://user-images.githubusercontent.com/17885425/165801368-4a57756d-08cc-41dc-b4da-649b97c85152.PNG) | ![IMG_2656](https://user-images.githubusercontent.com/17885425/165801377-c927bdef-fff6-42a7-a5f5-aa5270ce8f4b.PNG)
