### ISSUE TITLE
WebAuthn APIs should not be available in third party iframes

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#3326]
### Description:
WebAuthn APIs are available in third party iframes

### Steps to Reproduce 
  1. Navigate to https://dustiest-limitation.000webhostapp.com/fido-frame.html
  2. Verify that WebAuthn APIs are not available third party iframes.

**Actual result:** 
WebAuthn APIs are available

**Expected result:**
WebAuthn APIs should not be available

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.23.1

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4 running 1.23.1(21.2.22.10)
- Verified test plan from https://github.com/brave/security/issues/267
------------
Verification passed on iPhone XR with iOS 13.5 running 1.23.1(21.2.22.10)
- Verified test plan from https://github.com/brave/security/issues/267
-----------
Verification passed on iPad Pro with iOS 12.4.1 running 1.23.1(21.2.22.10)
- Verified test plan from https://github.com/brave/security/issues/267
