### ISSUE TITLE
Remove stale sync v1 code.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3327]

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4.2 running 124(21.3.25.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3268
- Verified sync chain is retained when upgrading from 1.22.2
- Verified able to add/remove/reorder/edit favourites 
- Verified post upgrade all sync'd items are retained 
-----------
Verification passed on iPhone XR with iOS 13.5 running 124(21.3.25.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3268
- Verified sync chain is retained when upgrading from 1.22.2
- Verified able to add/remove/reorder/edit favourites 
- Verified post upgrade all sync'd items are retained 
-----------
Verification passed on iPad Pro with iOS 12.4.1 running 124(21.3.25.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3268
- Verified sync chain is retained when upgrading from 1.22.2
- Verified able to add/remove/reorder/edit favourites 
- Verified post upgrade all sync'd items are retained
