### ISSUE TITLE
Staging Certificates are invalid for User Referral Program

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#3337]
### Description: 
Certificates on staging are invalid for the UserReferralProgram.swift's staging URL. This causes pinning to fail.

### Steps to Reproduce 
  1. Run the application.
  2. Check the log and see that the pinning failed exception is thrown.

**Actual result:** 
- Pinning Failed exception is thrown.

**Expected result:**
- Pinning should succeed.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced.

**Brave Version:** 
N/A

**Device details:** 
Any.

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 
N/A

### Additional Information
Devops switched the staging environment to CloudFlare: https://bravesoftware.slack.com/archives/C61QQMWS3/p1614021222026800

**Comment by iccub** [comment]
@Brandon-T label as `QA/Yes` or `No`, I am not sure whether we want to test it on dev channel
