### ISSUE TITLE
Allow users to input custom search engines on iOS

### ISSUE THREAD

**Issue by bbondy** [brave/brave-ios#3343]
Currently Brave on iOS only allows you to select from a pre-determined list of engines. 

It would be great to empower the user to specify an alternate engine.

Here's how a custom search engine input looks on Desktop. 
We should have something similar on iOS.
<img width="501" alt="Screen Shot 2021-02-23 at 11 10 57 AM" src="https://user-images.githubusercontent.com/831718/108872101-d5275b00-75c7-11eb-8acb-af85605897da.png">

Once a new engine is added, a user should be able to select it from within the search setting and from the private search setting.

**Comment by bbondy** [comment]
Closing as dupe of https://github.com/brave/brave-ios/pull/3231

**Comment by soner-yuksel** [comment]
An updated Test Plan and Feature details and information about related PRs and documents can be found 
https://docs.google.com/document/d/1ujsC_pNCdHGxsq_o-2Tzsyn91o_x5pheA-0hP8GBV7g

**Comment by soner-yuksel** [comment]
Search for  Open Search/ Manual Search Engine Addition in GDrive for additional information about the spec and details
