### ISSUE TITLE
Improve cross promotional modal to include Sync use case

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3344]
### Description: 
https://github.com/brave/brave-browser/issues/14325

Slack: https://bravesoftware.slack.com/archives/C20HMJ62H/p1614102140005700

Per the conversation in Slack lets re-design the cross promotional modal to include Sync.

**Comment by iccub** [comment]
Will be handled as a part of the new onboarding https://github.com/brave/brave-ios/issues/4298
