### ISSUE TITLE
Editing a favourite grabs wrong icon before updating to correct favicon

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3345]
### Description: 
Editing a favourite grabs wrong icon before updating to correct favicon

### Steps to Reproduce 
  1. Clean install 1.23.1 TF build
  2. Visit a page and add it to favourites
  3. Reorder the favourite to a different position (move it in one of the default favourite position)
  4. Edit the new favourite that you added in step 2 and change domain name
  5. Favourite grabs wrong favicon before it updates to new one

**Actual result:** 

https://user-images.githubusercontent.com/17010094/108964129-fbee9b80-7672-11eb-923a-62a1fe0bd01c.MP4

**Expected result:**
Should grab the correct favicon when the favourite is edited

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.23.1(21.2.22.10)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by cuba** [comment]
@iccub I tried to take a look at this one but it looks to be fixed already.

**Comment by iccub** [comment]
closing in favor of https://github.com/brave/brave-ios/issues/6066
