### ISSUE TITLE
"Javascript" should read "JavaScript" in Brave Shields & Privacy section

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#3351]
## Description 
"Javascript" should read "JavaScript" in Brave Shields & Privacy section

## Steps to Reproduce

   1.  launch Brave
   2.  go to Settings
   3.  tap on Brave Shields & Privacy
   4. examine the "Block Scripts" section's spelling of "Javascript"

## Actual result:

![IMG_4710](https://user-images.githubusercontent.com/387249/109052976-12a3eb00-7691-11eb-9649-822cf6bc12c3.jpg)

## Expected result:

"Javascript" should read "JavaScript"

## Reproduces how often: 
100%

## Version/Channel Information:

- Can you reproduce this issue with the current release? yes
- Can you reproduce this issue with the beta channel? yes
- Can you reproduce this issue with the nightly channel? yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome? 

## Miscellaneous Information:

The string is in https://github.com/brave/brave-ios/blob/a3e4993b539cdcc29c9e9ce860fbdd10558ba685/BraveShared/BraveStrings.swift#L602

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.24 (21.3.24.11)
- Verified `Javascript` is changed to `JavaScript`


iPhone 7+ (iOS 14.4) | iPhone XR (iOS 13.5) | iPad Pro (iOS 12.4.1)
-- | -- | --
<img width=350 src=https://user-images.githubusercontent.com/17010094/112435366-8a227400-8d3c-11eb-8c3d-b600f17372a0.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/112435381-8ee72800-8d3c-11eb-83e8-8163cde9b461.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/112435702-0026db00-8d3d-11eb-89b4-0477626467ea.png>
