### ISSUE TITLE
Update httpse data files

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#3358]
### Description: 
EFF's HTTPSE rulesets fixed a redirect loop on http://radio.garden/ due to https - https://github.com/EFForg/https-everywhere/issues/19927 

### Test Plan
Specified here: https://github.com/brave/brave-ios/pull/3402

### Steps to Reproduce 
  1. Navigate to http://radio.garden

**Actual result:** 
Redirect loop

**Expected result:**
No redirect loop

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.23.1

**Device details:** 
iPhone 11

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4.2 running 1.25(21.4.15.13)
- Verified test plan from https://github.com/brave/brave-ios/pull/3402
- Encountered #2554 & #3542
---------
Verification passed on iPhone XR with iOS 13.5 running 1.25(21.4.15.13)
- Verified test plan from https://github.com/brave/brave-ios/pull/3402
- Encountered #2554 & #3542
---------
Verification passed on iPad Pro with iOS 14.4.2 running 1.25(21.4.15.13)
- Verified test plan from https://github.com/brave/brave-ios/pull/3402
- Encountered #2554 & #3542
