### ISSUE TITLE
Move "Show More" favorites button up 20px.

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#3359]
There's extra 20px top margin on Show More button that should be removed.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4 running 1.24(21.3.24.11)
- Verified `Show More` button is much closer to the toptiles

1.23.1 | 1.24
-- | --
![image](https://user-images.githubusercontent.com/17010094/112432950-80e3d800-8d39-11eb-99cf-0ad20f9b60e3.png) | ![image](https://user-images.githubusercontent.com/17010094/112433009-90fbb780-8d39-11eb-82e5-6bd922eef0b8.png)

--------
Verification passed on iPhone XR with iOS 13.5 running 1.24(21.3.24.11)
- Verified `Show More` button is much closer to the toptiles

1.23.1 | 1.24
-- | --
![image](https://user-images.githubusercontent.com/17010094/112432862-614caf80-8d39-11eb-9be7-6a276064ed3d.png) | ![image](https://user-images.githubusercontent.com/17010094/112432902-6f9acb80-8d39-11eb-8ba3-a30d0de77712.png)

--------
Verification passed on iPad Pro with iOS 12.4.1 running 1.24(21.3.24.11)
- Verified `Show More` button is much closer to the toptiles

1.23.1 | 1.24
-- | --
![image](https://user-images.githubusercontent.com/17010094/112433041-9b1db600-8d39-11eb-9722-15c1415fb116.png) | ![image](https://user-images.githubusercontent.com/17010094/112433065-a40e8780-8d39-11eb-9bf4-4981fff52a17.png)
