### ISSUE TITLE
Consider adding `WKDataDetectorTypes` to our web views

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3361]
https://developer.apple.com/documentation/webkit/wkdatadetectortypes

These types allow websites to have more interactive links, it can turn addresses into Apple Maps handlers, phone numbers and other stuff.
It is off by default in WKWebView, from my tests it looks like all of them are enabled in Safari iOS,
we can consider adding all or some of them in our app, Firefox added it for phone numbers recently.

Related issue in FF: https://github.com/mozilla-mobile/firefox-ios/issues/7814

**Comment by srirambv** [comment]
Verification passed on the following devices  running 1.28(21.7.5.14)
- Verified test plan from https://github.com/brave/brave-ios/pull/3830
- Verified switch app alert is shown

iPhone XR (iOS 13.5) | iPhone 7+ (iOS 14.5.1) | iPad Pro (iOS 14.6)
-- | -- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/124600213-63f19180-de5e-11eb-94da-33e54e959e0e.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/124600166-5b00c000-de5e-11eb-93ae-01c9521a5fd3.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/124599926-1ecd5f80-de5e-11eb-8f9a-6efdeee18e22.png>
