### ISSUE TITLE
Modernize invalidation logic for NTP SI

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3365]
Checking for byte count is not great, we should see if the json we get contains wallpapers

Discussion here
https://bravesoftware.slack.com/archives/CQGTGBNH1/p1613785862001100?thread_ts=1613785809.000800&cid=CQGTGBNH1

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.24(21.3.16.19)
- Verified NTP SI is shown on prod builds
- Verified NTP SI follows rules of every 4th tab 

iPhone 7+(iOS 14.4) | iPhone XR (iOS 13.5) | iPad Pro (iOS 12.4.1)
-- | -- | --
<img width=420 src=https://user-images.githubusercontent.com/17010094/111511735-f1419680-8746-11eb-93ac-a42788fadd6a.png> | <img width=350 src=https://user-images.githubusercontent.com/17010094/111511812-fdc5ef00-8746-11eb-8144-17ffc24a7f0e.png> | <img width=550 src=https://user-images.githubusercontent.com/17010094/111511698-e8e95b80-8746-11eb-957e-37d745d20a44.png>
