### ISSUE TITLE
Playlists

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3368]

**Comment by srirambv** [comment]
QA Blocked on spec. @anthonypkeane please link the spec so QA can start testing it.

**Comment by anthonypkeane** [comment]
Unblocking as Spec provided

**Comment by srirambv** [comment]
<details>
<summary>Verification passed on iPhone XR with iOS 13.5 running 1.25(21.4.28.19)</summary>
<br> 
<ul>
<li> Verified visiting a YT video shows `Add to Brave Playlist` toast</li>
<li> Verified toast can be dismissed via swipe down</li>
<li> Verified clicking on toast adds the video to playlist</li>
<li> Verified once video is added to playlist, a confirmation toast is shown with open. Clicking that opens the playlist</li>
<li> Verified videos can be played on playlist while streaming</li>
<li> Verified able to add videos to playlist via toast/share menu/long press </li>
<li> Verified once video is added to playlist it is auto saved for offline viewing</li>
<li> Verified able to cancel offline saving feature by swipe and tap on the download cloud button</li>
<li> Verified able to remove a video from playlist via swipe left and selecting remove from confirmation prompt</li>
<li> Verified when playing a video from playlist, background the app doesn't activates picture-in-picture mode</li>
<li> Verified settings changed are retained between restarts</li>
<li> Verified tap on 15 sec back/forward buttons seeks the video 15sec back/forward</li>
<li> Verified able to zoom the video by double tapping on video</li>
<li> Verified locking screen while playing causes it to pause but can continue to background play by clicking on the play button on lockscreen</li>
<li> Verified video auto plays to next one after the current video is done playing</li>
<li> Verified able to skip to the next media </li>
<li> Verified videos doesn't loop once the last video in the playlist is done playing</li>
<li> Verified newly added videos are on top of the list </li>
<li> Verified able to seek video back/forward or increase/decrease volume via control center on lock screen</li>
<li> Verified when a video is put for offline play and network disrupts, video is buffered to download and continues to download when network is back </li>
<li> Verified videos are saved for offline even when browser is not active </li>
<li> Verified videos can be sorted/ordered by moving up/down  </li>
<li> Verified embedded videos on pages don't trigger toast to add to playlist but can still be added to playlist via share menu</li>
<li> Verified selecting `Playlist Offline Data` under clear private data only clears saved videos but doesn't remove the videos itself from the list</li>
<li> Verified selecting `Playlist Media & Offline Data` clears everything from playlist</li>
<li> Verified no crash when clearing playlist data</li>
</ul>
</details>

---------

<details>
<summary>Verification passed on iPhone 7+ with iOS 14.5 running 1.25(21.4.28.19)</summary>
<br> 
<ul>
<li> Verified visiting a YT video shows `Add to Brave Playlist` toast</li>
<li> Verified toast can be dismissed via swipe down</li>
<li> Verified clicking on toast adds the video to playlist</li>
<li> Verified once video is added to playlist, a confirmation toast is shown with open. Clicking that opens the playlist</li>
<li> Verified videos can be played on playlist while streaming</li>
<li> Verified able to add videos to playlist via toast/share menu/long press </li>
<li> Verified once video is added to playlist it is auto saved for offline viewing</li>
<li> Verified able to cancel offline saving feature by swipe and tap on the download cloud button</li>
<li> Verified able to remove a video from playlist via swipe left and selecting remove from confirmation prompt</li>
<li> Verified when playing a video from playlist, background the app activates picture-in-picture mode</li>
<li> Verified settings changed are retained between restarts</li>
<li> Verified tap on 15 sec back/forward buttons seeks the video 15sec back/forward</li>
<li> Verified able to zoom the video by double tapping on video</li>
<li> Verified locking screen while playing continue to background play and can be controled via lock screen controls</li>
<li> Verified video auto plays to next one after the current video is done playing</li>
<li> Verified able to skip to the next media </li>
<li> Verified videos doesn't loop once the last video in the playlist is done playing</li>
<li> Verified newly added videos are on top of the list </li>
<li> Verified able to seek video back/forward or increase/decrease volume via control center on lock screen</li>
<li> Verified when a video is put for offline play and network disrupts, video is buffered to download and continues to download when network is back </li>
<li> Verified videos are saved for offline even when browser is not active </li>
<li> Verified videos can be sorted/ordered by moving up/down  </li>
<li> Verified embedded videos on pages don't trigger toast to add to playlist but can still be added to playlist via share menu</li>
<li> Verified selecting `Playlist Offline Data` under clear private data only clears saved videos but doesn't remove the videos itself from the list</li>
<li> Verified selecting `Playlist Media & Offline Data` clears everything from playlist</li>
<li> Verified no crash when clearing playlist data</li>
</ul>
</details>

---------

<details>
<summary>Verification passed on iPad Pro with iOS 14.4.2 running 1.25(21.4.28.19)</summary>
<br> 
<ul>
<li> Verified visiting a YT video shows `Add to Brave Playlist` toast</li>
<li> Verified toast can be dismissed via swipe down</li>
<li> Verified clicking on toast adds the video to playlist</li>
<li> Verified once video is added to playlist, a confirmation toast is shown with open. Clicking that opens the playlist</li>
<li> Verified videos can be played on playlist while streaming</li>
<li> Verified able to add videos to playlist via toast/share menu/long press </li>
<li> Verified once video is added to playlist it is auto saved for offline viewing</li>
<li> Verified able to cancel offline saving feature by swipe and tap on the download cloud button</li>
<li> Verified able to remove a video from playlist via swipe left and selecting remove from confirmation prompt</li>
<li> Verified when playing a video from playlist, background the app activates picture-in-picture mode</li>
<li> Verified settings changed are retained between restarts</li>
<li> Verified tap on 15 sec back/forward buttons seeks the video 15sec back/forward</li>
<li> Verified able to zoom the video by double tapping on video</li>
<li> Verified locking screen while playing continue to background play and can be controled via lock screen controls</li>
<li> Verified video auto plays to next one after the current video is done playing</li>
<li> Verified able to skip to the next media </li><li> Verified videos doesn't loop once the last video in the playlist is done playing</li>
<li> Verified newly added videos are on top of the list </li>
<li> Verified able to seek video back/forward or increase/decrease volume via control center on lock screen</li>
<li> Verified when a video is put for offline play and network disrupts, video is buffered to download and continues to download when network is back </li>
<li> Verified videos are saved for offline even when browser is not active </li>
<li> Verified videos can be sorted/ordered by moving up/down  </li>
<li> Verified embedded videos on pages don't trigger toast to add to playlist but can still be added to playlist via share menu</li>
<li> Verified selecting `Playlist Offline Data` under clear private data only clears saved videos but doesn't remove the videos itself from the list</li>
<li> Verified selecting `Playlist Media & Offline Data` clears everything from playlist</li>
<li> Verified no crash when clearing playlist data</li>
</ul>
</details>
