### ISSUE TITLE
Drop support for iOS 12

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3369]

**Comment by kjozwiak** [comment]
Labeling this as completed as https://github.com/brave/brave-ios/issues/3612, https://github.com/brave/brave-ios/issues/3613 and https://github.com/brave/brave-ios/issues/3611 have been verified.

**Comment by kjozwiak** [comment]
Changing from `release-notes/exclude` to `release-notes/include`  as we should let users know via the release notes that iOS 12 support was dropped.
