### ISSUE TITLE
Provide a sync setting for 'last visited' folder

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3371]
Some users like it some don't, it should be user configurable.

**Comment by srirambv** [comment]
Blocked on #3550

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4.2 running 1.25(25.4.21.15)
- Verified setting option available in menu and is enabled by default
- Verified navigating into bookmarks folder retains the last visited view when setting is enabled
- Verified disabling last visited folder resets the default view to mobile bookmarks
- Verified disabling last visited folder still allows to navigate back to desktop bookmarks
-----------
Verification passed on iPhone XR with iOS 13.5 running 1.25(25.4.21.15)
- Verified setting option available in menu and is enabled by default
- Verified navigating into bookmarks folder retains the last visited view when setting is enabled
- Verified disabling last visited folder resets the default view to mobile bookmarks
- Verified disabling last visited folder still allows to navigate back to desktop bookmarks
------------
Verification passed on iPad Pro with iOS 14.4.2 running 1.25(25.4.21.15)
- Verified setting option available in menu and is enabled by default
- Verified navigating into bookmarks folder retains the last visited view when setting is enabled
- Verified disabling last visited folder resets the default view to mobile bookmarks
- Verified disabling last visited folder still allows to navigate back to desktop bookmarks
