### ISSUE TITLE
Add opt-in for Brave Today 

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3374]
Drive: `Brave Today Opt-in Spec`

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.24(21.3.16.19)

iPhone 7+ (iOS 4.4) | iPhone XR (iOS 13.5) | iPad Pro (iOS 12.4.1)
-- | -- | --
<img width=400 src=https://user-images.githubusercontent.com/17010094/111475309-da8a4800-8724-11eb-9367-670ccbee6f57.png> | <img width=350 src=https://user-images.githubusercontent.com/17010094/111475167-b9c1f280-8724-11eb-925a-bf6a16b6705a.png> | <img width=550 src=https://user-images.githubusercontent.com/17010094/111475349-e413b000-8724-11eb-830c-1d78ff691623.png>
