### ISSUE TITLE
Learn more about your data should look like a hyperlink

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3375]
### Description: 
Learn more about your data should look like a hyperlink

### Steps to Reproduce 
  1. Install 1.23.1 build
  2. Scroll down to Brave today
  3. `Learn more about your data` looks like plain text

**Actual result:** 
<img width=300 src=https://user-images.githubusercontent.com/17010094/110086762-af9a0e80-7d8a-11eb-9afc-9034e4842dd6.png>

**Expected result:**
Should look like its a hyper link

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.23.1

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by kylehickinson** [comment]
This is the design I was given. Plus, iOS does not have link-styled buttons. We can make it look more like a button but it'd look weird with the button above. Either way, I'll await a fix from design before doing anything

**Comment by jamesmudgett** [comment]
This is the link design from design team.
