### ISSUE TITLE
History window does not persist theme

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3383]
### Description: 
Please see this report https://community.brave.com/t/the-history-window-is-white-instead-of-purple/211984/3

### Steps to Reproduce 
  1. Open the app in private browsing mode
  2. Open history panel

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Marking QA/No as this is not yet fixed on the current PR linked. Follow up issue #3719  logged
