### ISSUE TITLE
Support multiple Brave windows on iPad

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3393]

**Comment by bbraunj** [comment]
+1 ^^^

**Comment by newhollandaus** [comment]
+1 for multiple windows on iPadOS 

Plus, In safari, long holding a link to open in a new window is pretty great. The option is labeled ‘open in split view’

**Comment by iccub** [comment]
Thank you for your patience. The code for multi window is finished :)
This week we upload a public beta with it. It should land in production this month.
I will close this ticket as duplicate of https://github.com/brave/brave-ios/issues/7574
