### ISSUE TITLE
Add Recently Closed Tabs screen

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3395]

**Comment by kylehickinson** [comment]
Refs https://github.com/brave/brave-ios/issues/2123

**Comment by Sam-Sibley** [comment]
@anthonypkeane @kylehickinson Here is the recently closed tabs solution.

Went with long press m the + icon in tab view:
https://www.figma.com/file/r0n9eDEAWZ8VNWZ4Ef2W7I/iOS-NTP?node-id=1186%3A20979

**Comment by Sam-Sibley** [comment]
Here is a screenshot of it. I thought it may need a clear functionality, so added that in too. Uses the same pattern as clear history.<img width="1001" alt="Screenshot 2022-10-27 at 1 31 28 am" src="https://user-images.githubusercontent.com/99699532/198069734-ac27eec5-f3fe-4ea8-9797-00e03cb7ebf0.png">

**Comment by Uni-verse** [comment]
Verified on version `1.48 (23.2.13.20)` using the following device(s):

`iPhone 12`, `iOS 16.2`
`iPad (7th Gen)`, `iPadOS 16.2`
`iPhone XR`, `iOS 15.5`

**New Profile** 

- User is able to access the `Recently Closed Tabs` screen via menu by long pressing on tab icon or by `+` icon in the tab tray
- User is able to restore previously closed tabs by tapping on the items in the Recently closed screen.
- User is able to delete individual items from the `Recently Closed Tabs` by swiping to delete. 
- User is able to delete all items by using the `Clear` button
- User can close the window by pressing `Done`
- User is not able to access Recently Closed Window for `Private tabs`
- Ensured that Recently Closed tabs are removed automatically after `3 days`
- Ensured that when user restores closed tab its removed from the list


**Existing Profile**

- User is able to access Recently Closed Tabs on `upgraded profile`
- User is able to delete/clear items

Example | Example | Example | Example
-|-|-|-
![IMG_0979](https://user-images.githubusercontent.com/17885425/218827205-d9ae332a-6750-4559-80a8-714a1080cbbc.PNG) | ![IMG_0980](https://user-images.githubusercontent.com/17885425/218827510-7eb6de88-cce6-4edb-8379-e6b2ced6453b.PNG) | ![IMG_0982](https://user-images.githubusercontent.com/17885425/218827568-03c04260-6b16-4d3e-9c0b-050cc4e74f4d.PNG) | ![IMG_0983](https://user-images.githubusercontent.com/17885425/218827577-5bea8ac6-e3cb-4128-9ec2-d3f3b0f1dbc0.PNG)
![IMG_0978](https://user-images.githubusercontent.com/17885425/218827194-2122c1f7-48a2-4e0a-9bea-51a1a06dbc22.PNG) | ![IMG_0987](https://user-images.githubusercontent.com/17885425/218828280-8f4138b8-274f-4364-97f4-f037a8634e2e.PNG) | ![IMG_0988](https://user-images.githubusercontent.com/17885425/218828304-8fa6a590-b0fc-46d9-86ca-a3d556bb8551.PNG) | ![IMG_0989](https://user-images.githubusercontent.com/17885425/218828310-9e9165f4-2704-43f9-9407-9f8b47123ee6.PNG)

Example | Example | Example | Example
-|-|-|-
![IMG_0298 2](https://user-images.githubusercontent.com/17885425/218837549-e8429d7a-c9bf-449f-9ee2-ca3be4f4e12f.PNG) | ![IMG_0296 2](https://user-images.githubusercontent.com/17885425/218837633-324221c5-7881-4839-a315-bb0cdd7ad9de.PNG) | ![IMG_0301](https://user-images.githubusercontent.com/17885425/218837682-ef51aa2e-9dfe-40b0-8e9f-5ceaf69c61c2.PNG) | ![IMG_0302 2](https://user-images.githubusercontent.com/17885425/218837686-ac03fbb0-46f0-48c3-8110-8b0e6e0e21f0.PNG)
![IMG_0299 2](https://user-images.githubusercontent.com/17885425/218837773-757487de-9b35-4435-9ded-2b0267a3d6d5.PNG) | ![IMG_0295 2](https://user-images.githubusercontent.com/17885425/218837805-ac6ad8e2-0d10-48af-a919-5fdea0557ae5.PNG) | ![IMG_0300](https://user-images.githubusercontent.com/17885425/218837841-bfd94056-0e30-4704-a69c-bf7bdf0bb826.PNG) | ![IMG_0303 2](https://user-images.githubusercontent.com/17885425/218837859-a438a041-92f0-43a5-b778-76500a82cd33.PNG)
