### ISSUE TITLE
Add ability to search open tabs

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3396]
When a user has 100s of tabs open it is very difficult at the moment to find a specific one you want. We should add the ability to search open tabs from within the tab tray so that it is easier to find tabs based on their titles

Same as bookmarks and history, the tab could be found by either url or the title.
Tabs may be found in their respective modes only, regular for regular and private for private tabs

![IMG_71DA0FF6D564-1](https://user-images.githubusercontent.com/6950387/139673492-69ed468e-7a2f-41ea-afd6-f1ec958b515b.jpeg)

**Comment by kylehickinson** [comment]
Ref https://github.com/brave/brave-ios/issues/3014

**Comment by iccub** [comment]
Blocked: we wait on Tab Tray refactor to merge before we can proceed

**Comment by Uni-verse** [comment]
Verification completed using build version`1.35 (22.1.24.23)`

**PASSED** on `iPhone 12 Pro` running `iOS 15.1.1`
**PASSED** on `iPhone X` running `iOS 14.4.2`
**PASSED** on `iPad (7th Gen)` running `iOS 15.2.1`

- Verified open tab tray functionality
- Verified try searching different queries
- Verified switching to private mode and check the bar is not presented when private mode information is presented
- Verified adding some tabs in private mode
- Verified Test Private mode is working as intended for search

iPhone 12 | iPhone X | iPad 
-|-|-
![IMG_2384](https://user-images.githubusercontent.com/17885425/151051528-b341a3d2-321e-479b-b84f-98967da6c9c2.PNG) | ![IMG_2580](https://user-images.githubusercontent.com/17885425/151051886-8fdd4eff-b8fc-433c-a05a-874676efc9b0.PNG) | ![IMG_0111](https://user-images.githubusercontent.com/17885425/151051777-64527a92-f050-4418-80a0-c59f9eb64bf6.PNG)
