### ISSUE TITLE
Add ability to search bookmarks by title or URL in the bookmarks list

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3397]
Requirements: 

The search bar should be visible right away. No need to swipe down to show it.
Place it under navigation bar.

Search bar placeholder should say `Search Bookmarks`, and use `magnifyingglass` SF symbol as its icon.
The search bar should look like this(ignore navbar and other items)

<img src="https://user-images.githubusercontent.com/6950387/137751738-db351f59-1317-4241-a0d6-0f7e9f1e23ef.jpeg" width="300">

You can either search by url or title of the bookmarked item.
Folders should be excluded from search results.
Keyboard type for the search bar should not autocomplete, and should provide the clear-all button on edit.
When in search mode, you should not be allowed to reorder bookmarks, only edit them by going into bookmark detail.

With no results, we should show `No search results found` message. Without any icon, similar to this
<img src="https://user-images.githubusercontent.com/6950387/137747571-2f3000c8-c094-4469-8554-deff20a02dd0.jpeg" width="300">

**Comment by anthonypkeane** [comment]
The text for the above would be

Search Bookmarks

No search results found

**Comment by soner-yuksel** [comment]
Re-opened to test in 1.34.

This feature was hidden in 1.33 to be included in 1.34 with this [PR](https://github.com/brave/brave-ios/pull/4742).
Restore issue https://github.com/brave/brave-ios/issues/4599

**Comment by soner-yuksel** [comment]
The Restore PR is merged #4742.
The feature can be tested with 1.34

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on **iPhone 8 - iOS version 15.2** running **Brave 1.34 (22.1.4.19)**

- Confirmed search bookmarks bar has a `Search Bookmarks` placeholder
- Confirmed bookmarks search bar is shown in the `Bookmarks` folder
- Confirmed bookmarks search bar is shown in the `Bookmarks` sub folders
- Confirmed search bookmarks bar has magnifying glass symbol as its icon
- Confirmed search bookmarks entry can be searched using bookmarks URL / title
- Confirmed search bookmarks bar has a clear-all button on **Edit**
- Confirmed `no search result found` message is displayed as expected when no search result is found

Example | Example | Example | Example | Example | Example | Example
------|------|-----|------|------|------|------
![IMG_2724](https://user-images.githubusercontent.com/38657976/148250827-e428d07d-1bcd-4988-b321-333e75384662.PNG) | ![IMG_2715](https://user-images.githubusercontent.com/38657976/148248461-729bded8-d609-4d50-ac23-8bcb35923253.PNG) | ![IMG_2716](https://user-images.githubusercontent.com/38657976/148248479-d69400bb-20b4-4f44-b461-dd5c1ff3dfa6.PNG) | ![IMG_2720](https://user-images.githubusercontent.com/38657976/148248505-6995bfd7-a88e-4705-a87e-7d797c7cdf2e.PNG) | ![IMG_2721](https://user-images.githubusercontent.com/38657976/148248533-cce4cf44-b21f-4afd-90e5-8c13646844b4.PNG) | ![IMG_2722](https://user-images.githubusercontent.com/38657976/148248564-ea4f2997-bdb0-4fa3-99e6-1ed122cfa2e0.PNG) | ![IMG_2723](https://user-images.githubusercontent.com/38657976/148248790-68e87aee-7ff5-4f56-a37f-73944cada2ad.PNG)
