### ISSUE TITLE
Add ability to search history by title or URL in the history list

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3398]
Requirements:

The search bar should be visible right away. No need to swipe down to show it.
Place it under navigation bar.

Search bar placeholder should say `Search History`, and use `magnifyingglass` SF symbol as its icon.
The search bar should look like this(ignore navbar and other items)

You can either search by url or title of the history entry.
Clearing history button should still clear all history, not only entries we looked for.
Keyboard type for the search bar should not autocomplete, and should provide the clear-all button on edit.

<img src="https://user-images.githubusercontent.com/6950387/137746000-430d8fe0-05bb-464d-99e0-df082e3e65f5.jpeg" width="300">

When sorting results, you can still try to add history headers like `Today` `Last week` etc
<img src="https://user-images.githubusercontent.com/6950387/137746318-3a6a4498-3e14-420d-b3e4-d190f9b482e0.jpeg" width="300">

With no results, we should show `No search results found` message. Without any icon, similar to this
<img src="https://user-images.githubusercontent.com/6950387/137747571-2f3000c8-c094-4469-8554-deff20a02dd0.jpeg" width="300">

**Comment by soner-yuksel** [comment]
Re-opened to test in 1.34. 

This feature was hidden in 1.33 to be included in 1.34 with this [PR](https://github.com/brave/brave-ios/pull/4742).
Restore Issue https://github.com/brave/brave-ios/issues/4599

**Comment by soner-yuksel** [comment]
The Restore PR is merged https://github.com/brave/brave-ios/pull/4742.
The feature can be tested with `1.34`

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on **iPhone 8 - iOS version 15.2** running **Brave 1.34 (22.1.4.19)**

- Confirmed search bar has a `Search History` placeholder
- Confirmed search bar has magnifying glass symbol as its icon
- Confirmed history entry can be searched using search URL / title
- Confirmed search history bar has a clear-all button on **Edit**
- Confirmed search history result can be deleted/cleared via Delete option
- Logged #4801 and #4802

Example | Example | Example | Example
------|------|-----|------
![IMG_2707](https://user-images.githubusercontent.com/38657976/148234768-6b0ea77b-af06-450d-bbec-754a1a8212c5.PNG) | ![IMG_2708](https://user-images.githubusercontent.com/38657976/148234801-678a6ccb-c097-409b-b83b-2956aedc2fc1.PNG) | ![IMG_2710](https://user-images.githubusercontent.com/38657976/148234829-8db60af0-52b3-4312-968e-4b316fd8f2dd.PNG) | ![IMG_2711](https://user-images.githubusercontent.com/38657976/148234841-26cc0a54-49f7-4f48-adff-e3a5ad5fb4ee.PNG)
