### ISSUE TITLE
Add feature to scan QR code to navigate to a URL

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3399]

**Comment by stephendonner** [comment]
**Verified `PASSED`** using `Brave 1.27 (21.6.15.14)` on `iPhone 6s`, `iOS 14.4.2`

**Steps:**
1. loaded `brave.com` on desktop Brave `nightly`
2. clicked in its URL bar
3. clicked on the QR Code icon
4. launched Brave on iOS
5. tapped in the URL bar
6. tapped on the QR Code icon
7. scanned the `brave.com` QR Code icon from desktop, using my iPhone 6s
8. also scanned the downloaded-from-desktop standalone QR Code for `brave.com`
9. confirmed in both steps 8 & 9 that `brave.com` loaded in a new tab


https://user-images.githubusercontent.com/387249/122137445-7c3f3500-cdf9-11eb-89ae-b4e64e1f4972.MP4

brave.com in-browser QR Code | brave.com standalone QR Code
--------------------|----------------------
<img width="1223" alt="Screen Shot 2021-06-15 at 4 42 08 PM" src="https://user-images.githubusercontent.com/387249/122137269-15ba1700-cdf9-11eb-905e-aede9ac6eaa7.png"> | ![qrcode_brave com](https://user-images.githubusercontent.com/387249/122137303-29fe1400-cdf9-11eb-95ff-7acb63ae4774.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 14.6` using `1.27 (21.6.15.14)`

* ensured that scanning a QRCode from Brave desktop via the omnibox worked as expected
* ensured that scanning a QRCode from Brave desktio via `Create QR Code for this page` via the right click context menu worked as expected
* ensured that scanning a QRCode from Brave desktio via `Create QR Code for this image` via the right click context menu worked as expected
* ensured that scanning a downloaded QR code from brave desktop worked as expected
* scanned a few codes fromhttps://www.qr-code-generator.com/examples and ensured most pages loaded (some are invalid now)
* ensured that a `Scanned` entry is appearing under `Recent Searches` after scanning a QRCode
* ensured that QRCodes scanned via Private Browsing don't appear in the `History` or `Recent Searches` list

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------|----------------|----------------
![IMG_3705](https://user-images.githubusercontent.com/2602313/122154517-2e472300-ce33-11eb-9bf5-36eaadc6d5f6.png) | ![IMG_3706](https://user-images.githubusercontent.com/2602313/122154522-31daaa00-ce33-11eb-9a37-6db2dfc22e9b.png) | ![IMG_3707](https://user-images.githubusercontent.com/2602313/122154535-369f5e00-ce33-11eb-805a-dde8c8bffc19.png) | ![IMG_3708](https://user-images.githubusercontent.com/2602313/122154547-3acb7b80-ce33-11eb-83ea-641ab4ca4120.png) | ![IMG_3709](https://user-images.githubusercontent.com/2602313/122154561-428b2000-ce33-11eb-9065-adf22c47de15.png) | ![IMG_3710](https://user-images.githubusercontent.com/2602313/122154578-4b7bf180-ce33-11eb-8a49-6ea6868d32ea.png)

----

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.5` using `1.27 (21.6.16.15)`

* ensured that scanning a QRCode from Brave desktop via the omnibox worked as expected
* ensured that scanning a QRCode from Brave desktio via `Create QR Code for this page` via the right click context menu worked as expected
* ensured that scanning a QRCode from Brave desktio via `Create QR Code for this image` via the right click context menu worked as expected
* ensured that scanning a downloaded QR code from brave desktop worked as expected
* scanned a few codes fromhttps://www.qr-code-generator.com/examples and ensured most pages loaded (some are invalid now)
* ensured that a `Scanned` entry is appearing under `Recent Searches` after scanning a QRCode
* ensured that QRCodes scanned via Private Browsing don't appear in the `History` or `Recent Searches` list

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------|----------------|----------------
![IMG_0263](https://user-images.githubusercontent.com/2602313/122341169-2cec2800-cf11-11eb-8cec-3f470e0f348c.png) | ![IMG_0264](https://user-images.githubusercontent.com/2602313/122341182-307faf00-cf11-11eb-8def-4a6262b4aa7b.png) | ![IMG_0265](https://user-images.githubusercontent.com/2602313/122341195-35446300-cf11-11eb-9f6a-330aea552a4f.png) | ![IMG_0266](https://user-images.githubusercontent.com/2602313/122341209-39708080-cf11-11eb-9f23-aadf709f4e10.png) | ![IMG_0268](https://user-images.githubusercontent.com/2602313/122341231-3d9c9e00-cf11-11eb-882c-c21730145844.png) | ![IMG_0270](https://user-images.githubusercontent.com/2602313/122341247-42615200-cf11-11eb-875d-22972079194e.png)

----

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.27 (21.6.16.15)`

* ensured that scanning a QRCode from Brave desktop via the omnibox worked as expected
* ensured that scanning a QRCode from Brave desktio via `Create QR Code for this page` via the right click context menu worked as expected
* ensured that scanning a QRCode from Brave desktio via `Create QR Code for this image` via the right click context menu worked as expected
* ensured that scanning a downloaded QR code from brave desktop worked as expected
* scanned a few codes fromhttps://www.qr-code-generator.com/examples and ensured most pages loaded (some are invalid now)
* ensured that a `Scanned` entry is appearing under `Recent Searches` after scanning a QRCode
* ensured that QRCodes scanned via Private Browsing don't appear in the `History` or `Recent Searches` list

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|-----------------|----------------|----------------|----------------|----------------
![IMG_0557](https://user-images.githubusercontent.com/2602313/122342539-c0722880-cf12-11eb-9e89-25a7c9b06a4f.png) | ![IMG_0558](https://user-images.githubusercontent.com/2602313/122342551-c49e4600-cf12-11eb-8e5f-e7f79e2e102d.png) | ![IMG_0559](https://user-images.githubusercontent.com/2602313/122342562-c8ca6380-cf12-11eb-92c5-a0131c907838.png) | ![IMG_0560](https://user-images.githubusercontent.com/2602313/122342573-cd8f1780-cf12-11eb-91e0-060742b2ea2a.png) | ![IMG_0561](https://user-images.githubusercontent.com/2602313/122342586-d2ec6200-cf12-11eb-8dd5-3bc2fe6ce22f.png) | ![IMG_0562](https://user-images.githubusercontent.com/2602313/122342604-d67fe900-cf12-11eb-8d24-1d3b270a8c74.png)

**Comment by kjozwiak** [comment]
Found https://github.com/brave/brave-ios/issues/3798, https://github.com/brave/brave-ios/issues/3799 & https://github.com/brave/brave-ios/issues/3800.
