### ISSUE TITLE
Brave VPN opt-in

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3403]
We should not call Guardian's receipt validation server if a user has never purchased any vpn plan.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 14.4.2` using `1.25 (21.4.28.18)` & `1.25 (21.4.28.19)`

**`Using Dev build`**:

Went into VPN logs and ensured that there's no mention of `VPN receipt` as per https://github.com/brave/brave-ios/pull/3464#issue-600908252.

![image](https://user-images.githubusercontent.com/2602313/116644206-c0a56d00-a940-11eb-869e-92601750a43f.png)

**`Using Production build`**:

* ensured that toggling the `Brave VPN` via `...` menu opened the expected modal/onboarding
* ensured that tapping on `Try for FREE` via `Settings` opened the expected modal/onboarding
* ensured that you can subscribe & restore without any issues
* ensured that clicking on `Install VPN Profile` correctly installed the required VPN profile and enabled the VPN
* ensured that the nearest location was correctly selected (checked IP using https://www.whatismyip.com)
* ensured that you can change location and verified the IP changed via https://www.whatismyip.com

-----

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.25 (21.4.28.18)` & `1.25 (21.4.28.19)`

**`Using Dev build`**:

Went into VPN logs and ensured that there's no mention of `VPN receipt` as per https://github.com/brave/brave-ios/pull/3464#issue-600908252.

![image](https://user-images.githubusercontent.com/2602313/116644920-a4a2cb00-a942-11eb-8d6d-0c9b3c9c07af.png)

**`Using Production build`**:

* ensured that toggling the `Brave VPN` via `...` menu opened the expected modal/onboarding
* ensured that tapping on `Try for FREE` via `Settings` opened the expected modal/onboarding
* ensured that you can subscribe & restore without any issues
* ensured that clicking on `Install VPN Profile` correctly installed the required VPN profile and enabled the VPN
* ensured that the nearest location was correctly selected (checked IP using https://www.whatismyip.com)
* ensured that you can change location and verified the IP changed via https://www.whatismyip.com

-----

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.5` using `1.25 (21.4.28.18)` & `1.25 (21.4.28.19)`

**`Using Dev build`**:

Went into VPN logs and ensured that there's no mention of `VPN receipt` as per https://github.com/brave/brave-ios/pull/3464#issue-600908252.

![image](https://user-images.githubusercontent.com/2602313/116645797-8c33b000-a944-11eb-8a55-eafc55d5f0fd.png)

**`Using Production build`**:

* ensured that toggling the `Brave VPN` via `...` menu opened the expected modal/onboarding
* ensured that tapping on `Try for FREE` via `Settings` opened the expected modal/onboarding
* ensured that you can subscribe & restore without any issues
* ensured that clicking on `Install VPN Profile` correctly installed the required VPN profile and enabled the VPN
* ensured that the nearest location was correctly selected (checked IP using https://www.whatismyip.com)
* ensured that you can change location and verified the IP changed via https://www.whatismyip.com
