### ISSUE TITLE
use same certificate pinset as brave-browser

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-ios#3406]
iOS's certificate pinning set should be the same as desktop. this is blocked on https://github.com/brave/brave-browser/issues/14637.

**Comment by bsclifton** [comment]
We used a new certificate from GlobalSign for the service itself - should be good to go. @Brandon-T added this to cert pinning a while back
![image](https://user-images.githubusercontent.com/4733304/111195704-c5bd8100-8579-11eb-8f07-d52e07a9b156.png)

**Comment by iccub** [comment]
I'll just add proper path to our certificates if you want to take a closer look
https://github.com/brave/brave-ios/tree/development/Client/Assets/Certificates

**Comment by diracdeltas** [comment]
@iccub @bsclifton i should have clarified - this issue is to add some automation to pull the same cert set from brave-core so it's always in sync

**Comment by bsclifton** [comment]
ah ok - thanks @diracdeltas 😄 

We'll need to rework the desktop one to not be Let's Encrypt if we keep GlobalSign. Will update that issue

**Comment by iccub** [comment]
Fixed manually here https://github.com/brave/brave-ios/issues/3755

Ongoing work to automate it with a bootstrap script here https://github.com/brave/brave-ios/issues/4064
