### ISSUE TITLE
Limit rewards outbound calls until rewards interaction

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3410]
Desktop does this on client side by not creating the process unless they'd previously opted in, iOS will likely have to do something similar

## Test Plan

Rewards/ads domains to look for:

```
grant.rewards.*.com
api.rewards.*.com
ads-serve.*.com
brave-user-model-installer-*.*.com
```

With a proxy app open & active (Charles, Proxyman, etc.):

- Launch fresh install, verify no rewards/ads calls are called on launch
- Open the rewards panel and verify some rewards calls happen
- Enable Rewards and verify rest of ads calls happen and ads/rewards functions as normal
- Kill app (force quit), relaunch and verify Rewards calls now happen at launch (because Rewards is enabled)
- Disable rewards, Kill app (force quit), relaunch and verify calls do not happen at launch
- Visit Settings > Brave Rewards (with Rewards still disabled) and verify some rewards calls happen (same calls that happen when visiting panel in step 2)

**Comment by srirambv** [comment]
QA Blocked on test plan

**Comment by kylehickinson** [comment]
@srirambv Test cases added, let me know if you need any additional info 🙂

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 11` running `iOS 14.4.2` using `1.25 (21.4.27.17)` - **PASSED**
* Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.25 (21.4.27.17)` - **PASSED**
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.4.2` using `1.25 (21.4.27.17)` - **PASSED**

#### Test Cases as per https://github.com/brave/brave-ios/issues/3410#issue-832069934

Launched Brave and ensured that none of the above reward API calls are occurring when launching Brave and rewards is disabled:

**`API calls when launching Brave for the first time`**

```
* https://adblock-data.s3.brave.com
* https://laptop-updates.brave.com
```

Ensured that tapping on the rewards panel contacts the following reward API calls:

**`API calls when tapping on the rewards panel for the first time`**

```
* https://grant.rewards.brave.com
* https://rewards.brave.com
* https://api.rewards.brave.com
```

Once rewards has been enabled, ensured that the following API endpoints are contacted:

**`API calls when enabling rewards for the first time`**

```
* https://ads-static.brave.com
* https://ads-serve.brave.com
* https://brave-user-model-installer-input.s3.brave.com
```

Closed/Quit Brave and relaunched while rewards was enabled and ensured that the following API endpoints are contacted:

**`API calls when rewards enabled and Brave is launched`**

```
* https://api.rewards.brave.com
* https://brave-user-model-installer-input.s3.brave.com
* https://ads-static.brave.com
* https://ads-serve.brave.com
* https://grant.rewards.brave.com
```

Ensured that none of the above reward API calls are made once rewards has been disabled and the browser restarted:

**`API calls when rewards has been disabled and Brave restarted`**

```
* https://adblock-data.s3.brave.com
* https://laptop-updates.brave.com
```

Ensured only the following API call is made when viewing the `Brave Rewards` under `Settings` while rewards is disabled:

**`Viewing Brave Rewards settings while rewards disabled`**

```
https://api.rewards.brave.com
```

**Comment by kjozwiak** [comment]
We'll also do a general regression check when we run through the manual passes and ensure that rewards is still working as expected 👍

**Comment by kjozwiak** [comment]
Changing from `release-notes/exclude` to `release-notes/include`  as this was a big issue on desktop/android when it happened. Should definitely be mentioned.
