### ISSUE TITLE
Browser crash on launch

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3411]
### Description: 
Browser crash on launch

### Steps to Reproduce 
  1. Install 1.24 build dev/prod on iOS 12.4.1
  2. Launch browser
  3. Crashes immediately

**Actual result:** 
Browser crash on launch

**Expected result:**
No crash on launch or while using 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.24(21.3.15.18)

**Device details:** 
iPad Pro (iOS 12.4.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
cc: @brave/ios

**Comment by kjozwiak** [comment]
Reproduced the issue on `iPhone 6s+` running `iOS 12.4.1` using the following builds:

* `1.24 (21.3.15.18)` - **Reproduced** (Both Dev/Production channels)

Logs --> [Client-2021-03-16-124402.ips.beta.txt](https://github.com/brave/brave-ios/files/6150778/Client-2021-03-16-124402.ips.beta.txt)

@kylehickinson let me know if the above logs are helpful or if you need anything else 👍

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 12.4.1 running 1.24(21.3.16.21)
- Verified no crash when browser is launched 

-----

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using the following build:

```
1.24 (21.3.17.17) - Both Dev & BETA builds
```

* ensured that Brave doesn't launch at crash
* went through all the onboarding and opened several tabs to make sure there's no crashes that might happen after first launch
