### ISSUE TITLE
Shields educational message shown when shields not visible

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3412]
### Description: 
Shields educational message shown when shields not visible

### Steps to Reproduce 
  1. Install 1.24
  2. Scroll down Brave today
  3. Open an article and before the page loads scroll so shields and bottom toolbar is hidden, educational tooltip shows even when shields is not visible 

**Actual result:** 
<img width=300 src=https://user-images.githubusercontent.com/17010094/111280706-0b3e8480-8634-11eb-96f3-4b0c8fcb2f53.png>

**Expected result:**
Only show when shields is visible

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy but have to be quick. Easily reproduced on Buzzfeed articles opened from Brave Today feed

**Brave Version:** 
1.24(21.3.15.18)

**Device details:** 
iPhone XR

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by soner-yuksel** [comment]
Adding Scrolling guard to pop-over presentation and re-enabling the gestures.

We decided to take different approach here we add a new condition to webview-scrollview to check If user is dragging and disable showing pop-overs If user started dragging.

This will help us to prevent having issue like seeing pop-over when toolbar(shields) are hidden and other issues that can cause dead-lock also help user not to get irritated while they are scrolling in the page for some information.

With the help of this we can also enable gestures again on our pop-overs.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4 running 1.24(21.3.24.11)
- Verified shields tooltip doesn't show up if the URL/bottom tool bar is hidden before page is loaded
-----------
Verification passed on iPhone XR with iOS 13.5 running 1.24(21.3.24.11)
- Verified shields tooltip doesn't show up if the URL/bottom tool bar is hidden before page is loaded
-----------
Verification passed on iPad Pro with iOS 12.4.1 running 1.24(21.3.24.11)
- Verified shields tooltip doesn't show up if the URL/bottom tool bar is hidden before page is loaded
