### ISSUE TITLE
Selecting a custom search engine as default removes it from custom search engine list

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3415]
### Description: 
Selecting a custom search engine as default removes it from custom search engine list

### Steps to Reproduce 
  1. Add GH as a custom search engine
  2. Set GH as default SE, removes it from custom search engine list
  3. Set Bing as default SE, GH is added back to custom search engine list

**Actual result:** 

https://user-images.githubusercontent.com/17010094/111311292-f1ae3480-8655-11eb-8319-9649c5286afd.MP4

**Expected result:**
Not sure

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.24

**Device details:** 
iPhone 7+ (iOS 14.4)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @soner-yuksel  @anthonypkeane

**Comment by soner-yuksel** [comment]
The PR is not eliminating the search engine If it is added as default engine. And also prevents user to the delete engine if it is users default engine.

**Comment by srirambv** [comment]
iPVerification passed on iPhone 7+ with iOS 14.4 running 1.24 (21.3.24.11)
- Verified test plan from https://github.com/brave/brave-ios/pull/3419
- Verified setting a custom search engine as default doesn't allow it to be removed 
----
Verification passed on iPhone 7+ with iOS 14.4 running 1.24 (21.3.24.11)
- Verified test plan from https://github.com/brave/brave-ios/pull/3419
- Verified setting a custom search engine as default doesn't allow it to be removed 
------- 
Verification passed on iPhone 7+ with iOS 14.4 running 1.24 (21.3.24.11)
- Verified test plan from https://github.com/brave/brave-ios/pull/3419
- Verified setting a custom search engine as default doesn't allow it to be removed 

iPhone 7+ (iOS 14.4) | iPhone (iOS 13.5) | iPad Pro (iOS 12.4.1)
-- | -- | --
<img width=350 src=https://user-images.githubusercontent.com/17010094/112340920-ea6fd200-8cb8-11eb-9912-3ec932389a0a.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/112340874-e04dd380-8cb8-11eb-930d-6817780341ab.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/112341139-11c69f00-8cb9-11eb-8042-86cc3439ade2.png>
