### ISSUE TITLE
Fix iOS 11 deprecation warnings

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#342]
There are a few iOS 11 specific deprecation warnings:

- [ ] `'automaticallyAdjustsScrollViewInsets' was deprecated in iOS 11.0: Use UIScrollView's contentInsetAdjustmentBehavior instead`
- [ ] `'touchIDNotAvailable' was deprecated in iOS 11.0: use LAErrorBiometryNotAvailable`
- [ ] `'touchIDNotEnrolled' was deprecated in iOS 11.0: use LAErrorBiometryNotEnrolled`
- [ ] `'touchIDLockout' was deprecated in iOS 11.0: use LAErrorBiometryLockout`

**Comment by vldmrkl** [comment]
Hi, I would like to work on it if you don't mind.

**Comment by jhreis** [comment]
@klymenkoo all yours! Let us know if you run into any issues!

**Comment by vldmrkl** [comment]
@kylehickinson  @jhreis I've fixed the first one: 
`'automaticallyAdjustsScrollViewInsets' was deprecated in iOS 11.0: Use UIScrollView's contentInsetAdjustmentBehavior instead`

Also, I was a bit confused with `'touchIDNotAvailable'`, `'touchIDNotEnrolled'`, and `'touchIDLockout'` as there wasn't any particular file specified in the Issue navigator.

I did research about the way to fix these warnings, and it seems that it's actually a bug in Swift compiler ([StackOverflow discussion](https://stackoverflow.com/questions/46455424/touchidlockout-deprecated-in-ios-11-0/47802525#47802525))

I also tried to search for the same issue on GitHub, however, I found that other people also couldn't solve it:

- [Example 1](https://github.com/NumericDesign/Bement-Parent-Portal/issues/9)
- [Example 2](https://github.com/SanctionCo/pilot-ios/issues/62)

Do you want me to make a Pull Request with solution for 
`'automaticallyAdjustsScrollViewInsets' was deprecated in iOS 11.0: Use UIScrollView's contentInsetAdjustmentBehavior instead` ?

**Comment by kylehickinson** [comment]
@klymenkoo I think the problem with touchID related warnings is somewhere around [here](https://github.com/brave/brave-ios/blob/200e4974f00e0fb9692ce1d7f435e28c112ee5e2/Client/Frontend/AuthenticationManager/AppAuthenticator.swift#L149). However, even commenting out the entire method doesn't silence the warning for some reason.

If you want to poke around by all means :) Otherwise, yeah you can make a PR for the fixes for the scroll view insets, Thanks!

**Comment by vldmrkl** [comment]
@kylehickinson yes, I've been looking exactly at that part of code, but the thing is that it looks right because it uses the `LAErrorBiometryNotAvailable`, `LAErrorBiometryNotEnrolled`, and `LAErrorBiometryLockout`.

According to my research, I tend to believe that it is a Swift compiler bug.

**Comment by cndouglas** [comment]
Swift bug: https://bugs.swift.org/browse/SR-6637
