### ISSUE TITLE
Animation Problems while Adding Custom Search Engine

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#3420]
### Description: 

While adding custom search engine using Open- Search the loading animation is being played on top the search icon and
After search engine is added successfully the Toast warning is hidden behind the keyboard

### Steps to Reproduce 

1. Add GH as a custom search engine
2. Check loading indicator plays on top of search icon
3. Toast is not visible after the search engine is added

**Actual result:** 

- The loading animation after adding custom engine using auto-add happens on the magnifying glass. 
- The toast confirming search engine is added gets hidden behind the keyboard 

Expected result:

- When loading animation is happening the magnifying button should be hidden
- Dismiss the keyboard when a search engine successfully added

 
Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

Brave Version:
1.24

Device details:
iPhone 7+ (iOS 14.4)

Website problems only:

did you check with Brave Shields down? NA
did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4 running 1.24(21.3.24.11)
- Verified when loading animation is happening the magnifying button is hidden
- Verified keyboard is auto-dismissed when SE is added successfully

https://user-images.githubusercontent.com/17010094/112327793-a1fee700-8cad-11eb-87e0-ce515dfeb51f.MP4

---------
Verification passed on iPhone XR with iOS 14.4 running 1.24(21.3.24.11)
- Verified when loading animation is happening the magnifying button is hidden
- Verified keyboard is auto-dismissed when SE is added successfully

https://user-images.githubusercontent.com/17010094/112327928-bfcc4c00-8cad-11eb-8595-5bc43e451cf0.MP4

---------
Verification passed on iPad Pro with iOS 12.4.1 running 1.24(21.3.24.11)
- Verified when loading animation is happening the magnifying button is hidden
- Verified keyboard is auto-dismissed when SE is added successfully

https://user-images.githubusercontent.com/17010094/112327628-7da30a80-8cad-11eb-88db-ca5f7b5d5edb.MP4
