### ISSUE TITLE
Missing translations for Customize Brave Today feed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3423]
### Description: 
Missing translations for Customize Brave Today feed

### Steps to Reproduce 
  1. Set locale to JP
  2. Install 1.24 (21.3.16.19)
  3. Scroll down to Brave today, customize BT is not translated

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/111472034-7c0f9a80-8721-11eb-8a52-29df6a3b5fec.png)

**Expected result:**
Translated text

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.24(21.3.16.19)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by kylehickinson** [comment]
These strings are new and thus not translated yet, will come with #3340

**Comment by iccub** [comment]
Closing in favor of 3340
