### ISSUE TITLE
Update VPN card text to include Geo/Country Selection

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3431]
### Description
Update VPN card text to include Geo/Country Selection

- [x] Create Text - @karenkliu 
- [ ] Update the UI

Currently, the screen looksl ike this: 
![IMG_0DBB45786049-1](https://user-images.githubusercontent.com/7606853/111524145-5383a280-8719-11eb-9070-6ee1cefeb1a7.jpeg)

### Design

<img width="515" alt="Screen Shot 2021-04-12 at 8 43 44 AM" src="https://user-images.githubusercontent.com/2388823/114444981-5a6ccc00-9b84-11eb-9835-d2711cfd33d4.png">

### Assets
Figma: https://www.figma.com/file/PqLTp3DnANLQMM1XzaChqZ/Mobile-VPN?node-id=36%3A2448

**Comment by karenkliu** [comment]
Designs added!

**Comment by mywristbands** [comment]
I'm trying to access the Figma asset, but when I click on it the site says "File not found". Are only some people allowed to access this file?

**Comment by iccub** [comment]
@mywristbands Figma is for Brave employees only

Here's what both screens should look like after copy update

<img width="796" alt="Zrzut ekranu 2021-05-6 o 13 53 40" src="https://user-images.githubusercontent.com/6950387/117294051-79543a80-ae72-11eb-843d-d196c0ec279e.png">

**Comment by iccub** [comment]
Since we are close to finish 1.26, i am going to take over this ticket, cc @mywristbands

**Comment by srirambv** [comment]
@iccub going to mark this as QA/No as the cards are not upto date and there is a follow up issue created for 1.27. Doesn't make sense to add verification notes to this one.
