### ISSUE TITLE
Add Search Engine missing on toolbar for iPad

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3436]
### Description: 
Add Search Engine missing on toolbar for iOS 12 devices

### Steps to Reproduce 
  1. Install 1.24 on iPad Pro with iOS 12.4.1
  2. Visit Wikipedia or Github and click on search box
  3. Keyboard pops up but there is no Add SE button on the toolbar

**Actual result:** 

https://user-images.githubusercontent.com/17010094/111665909-1c8db980-880b-11eb-8652-9e294c0c57bf.MP4

**Expected result:**
Should show add search button for iOS 12 devices

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.24(21.3.17.16)

**Device details:** 
iPad Pro (iOS 12.4.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
cc: @soner-yuksel

**Comment by soner-yuksel** [comment]
This problem is actually related with all the iPads. The add search button is added onto toolbar of iPad Keyboard and in addition Add Engine Activity is added. Please refer the screenshots inside PR descrip.

**Comment by srirambv** [comment]
Reproduced the issue on iPad Pro with iOS 14.4 as well

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.24(21.3.24.11)

iPad Pro (iOS 12.4.1) | iPad Pro (iOS 14.4)
-- | -
![image](https://user-images.githubusercontent.com/17010094/112324186-69a9d980-8caa-11eb-9e22-12f0299170c9.png) | ![image](https://user-images.githubusercontent.com/17010094/112324328-94942d80-8caa-11eb-8761-0aca83d4cc00.png)
