### ISSUE TITLE
Add flags to skip annoying UI callouts in debug mode

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3445]
We devs have to see the onboarding and other callout and popups many times a day.
Let's disable them for debug builds.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4.2 running 1.25(21.4.15.13)
- Verified TF build shows all UI callouts based on trigger values
-----------
Verification passed on iPhone XR with iOS 13.5 running 1.25(21.4.15.13)
- Verified TF build shows all UI callouts based on trigger values
-----------
Verification passed on iPad Pro with iOS 14.4.2 running 1.25(21.4.15.13)
- Verified TF build shows all UI callouts based on trigger values
