### ISSUE TITLE
Source list doesn't auto pick https context

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3453]
### Description: 
Source list doesn't auto pick https context

### Steps to Reproduce 
  1. Install 1.24
  2. Go to Settings -> Brave Today -> Add Source 
  3. Type in `news.google.com`, throws insecure `http` message
  4. Add `https://`prefix to `news.google.com`, shows secure feed list

**Actual result:** 

https://user-images.githubusercontent.com/17010094/112307212-9654f580-8c98-11eb-9aae-580a36e024b8.MP4

**Expected result:**
User doesn't have to specify `https://` manually to get the secure feed list

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.24 (21.3.22.17)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
cc: @kylehickinson

**Comment by kylehickinson** [comment]
This is by design as it uses the same URL parser as the main URL bar in the app. 

Edit:
However there is a bug which does not correctly respect the response URL which may be `https` anyways when forming relative URLs

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4 running 1.24 (21.3.25.18)
- Verified adding domain without http/https prefix selects https source
- Verified adding a http domain upgrade to https when available

https://user-images.githubusercontent.com/17010094/112596592-ee5c3b00-8e03-11eb-8a99-c8a247d2cd6f.MP4

-----------------
Verification passed on iPhone XR  with iOS 13.5 running 1.24 (21.3.25.18)
- Verified adding domain without http/https prefix selects https source
- Verified adding a http domain upgrade to https when available

https://user-images.githubusercontent.com/17010094/112596683-0a5fdc80-8e04-11eb-8982-123a16e335ce.MP4

-----------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.24 (21.3.25.18)
- Verified adding domain without http/https prefix selects https source
- Verified adding a http domain upgrade to https when available


https://user-images.githubusercontent.com/17010094/112596498-cd93e580-8e03-11eb-96bc-269338895da9.MP4
