### ISSUE TITLE
Disabling and deleting a feed enables the next one by default

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3460]
### Description: 
Disabling and deleting a feed enables the next one by default

### Steps to Reproduce 
  1. Add 5 feeds to Brave Today
  2. Disable 4 & 5 feed
  3. Delete 4th feed
  4. 5th feed is enabled automatically

**Actual result:** 

https://user-images.githubusercontent.com/17010094/112473360-2d3bb380-8d66-11eb-94b0-03165f01d985.MP4

**Expected result:**
Disabled feed should remain disabled

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.24(21.3.24.11)

**Device details:** 
iPhone 7+ (iOS 14.4)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

**Comment by kylehickinson** [comment]
The feed is not actually enabled automatically, this is just a visual bug with the switch which will be fixed in #3463

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4 running 1.24(21.3.25.18)
- Verified steps from issue description
-----------
Verification passed on iPhone XR with iOS 13.5 running 1.24(21.3.25.18)
- Verified steps from issue description
-------------
Verification passed on iPad Pro with iOS 12.4.1 running 1.24(21.3.25.18)
- Verified steps from issue description
