### ISSUE TITLE
Enabling Brave Today from settings doesn't list sources list 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3462]
### Description: 
Enabling Brave Today from settings doesn't list sources list 

### Steps to Reproduce 
  1. Clean install 1.24(21.3.24.11)
  2. Open Settings -> Brave today -> Turn on Brave Today
  3. Source list is not shown
  4. Navigate back to settings and reopen Brave Today, source list is shown

**Actual result:** 

https://user-images.githubusercontent.com/17010094/112480866-582a0580-8d6e-11eb-955a-fbef4a200678.MP4

**Expected result:**
Should populate the list when enabled

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.24(21.3.24.11)

**Device details:** 
iPhone 7+ (iOS 14.4) & iPhone XR (iOS 13.5) & iPad Pro (iOS 14.4)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
~~Issue not reproducible on iOS 12~~

**Comment by kylehickinson** [comment]
Removing from 1.24 as this is not a regression, but I will fix this when I refactor the settings screens in SwiftUI

**Comment by mattmcalister** [comment]
Let's close this one, too. No longer relevant.
