### ISSUE TITLE
manually adding certain search engines via Open Search uses inverted favicon 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3469]
### Description: 
Manually adding GH shows inverted favicon 

### Steps to Reproduce 
  1. Install 1.24 on iPad
  2. Manually add GH as a search engine
  3. Shows favicon in inverted colour
  4. Delete and add GH via add search button shows correct favicon

**Actual result:** 

https://user-images.githubusercontent.com/17010094/112617244-9e3da280-8e1c-11eb-8dbe-dcc3241db389.MP4

**Expected result:**
Should add favicon correclty irrespective of how its added

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.24(21.3.25.18)

**Device details:** 
iPad Pro (iOS 14.4) & iPad Pro(iOS 12.4.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
Follow-up for https://github.com/brave/brave-ios/issues/3413

**Comment by kjozwiak** [comment]
Removing `iPad-specific` as I basically ran into the same issue adding another SE. Some more context can be found via:
* https://bravesoftware.slack.com/archives/C06UXF3KJ/p1617046592165500

**Comment by iccub** [comment]
closing in favor of https://github.com/brave/brave-ios/issues/6066
