### ISSUE TITLE
Tab title does not get updated on youtube.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3470]
### Steps to Reproduce 
  1. Make sure tabs are visible, by default on iPad or open at least 2 tabs on iPhone
  2. Go to youtube
  2. Tap on a video
  3. Tap on a different video, from recommended list for example

**Actual result:** 
Tab title has not changed

**Expected result:**
Tab title should have changed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4.2 running 1.25(21.4.15.13)
- Verified test plan from issue description
- Verified tab title updates when a new video is loaded
-----------
Verification passed on iPhone XR with iOS 13.5 running 1.25(21.4.15.13)
- Verified test plan from issue description
- Verified tab title updates when a new video is loaded
----------
Verification passed on iPad Pro with iOS 14.4.2 running 1.25(21.4.15.13)
- Verified test plan from issue description
- Verified tab title updates when a new video is loaded
