### ISSUE TITLE
Subtitles showing always First Tier description for every pop-over

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#3480]
Description:
The description inside Benchmark Tier always show same message.

### Steps to Reproduce 
  1. Follow test plan from #3387
  2. Trigger tooltip for 2nd / 3rd Tier etc.
  3. Description always "Congratulations. You're pretty special" 
  
**Actual result:**

![IMG_6537](https://user-images.githubusercontent.com/6643505/112885856-3ba80900-909f-11eb-8958-24039afb3b53.png)

**Expected result:**
Show designated description for every Tier.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced,

**Brave Version:** 
1.24(21.3.25.18)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? N_A
- did you check in Safari/Firefox (WkWebView-based browsers)? N_A

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4.2 running 1.24(21.3.31.15)
- Verified subtitles match spec 
**Note: The values are divided by 100 so its easy to test all of them.**

1,000 | 5,000  | 10,000  | 25,000 | 75,000 | 100,000 | 250,000 | 500,000 | 1,000,000 
-- | -- | -- | -- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/113283892-c592e480-92e0-11eb-94db-cccbc4ed4065.png) | ![image](https://user-images.githubusercontent.com/17010094/113283945-d5122d80-92e0-11eb-98b5-ad1d32991f51.png) | ![image](https://user-images.githubusercontent.com/17010094/113284675-dee86080-92e1-11eb-976d-06a3aac6d4ee.png) | ![image](https://user-images.githubusercontent.com/17010094/113284435-8749f500-92e1-11eb-8d04-302d73786aa3.png) | ![image](https://user-images.githubusercontent.com/17010094/113284471-95981100-92e1-11eb-9791-7d7e7a25da08.png) | ![image](https://user-images.githubusercontent.com/17010094/113284478-992b9800-92e1-11eb-8844-f0f4ea418e50.png) | ![image](https://user-images.githubusercontent.com/17010094/113284541-b1031c00-92e1-11eb-90e8-e0dbb6c557f2.png) | ![image](https://user-images.githubusercontent.com/17010094/113284588-c11afb80-92e1-11eb-8889-a84ab1dc2ef9.png) | ![image](https://user-images.githubusercontent.com/17010094/113284611-ca0bcd00-92e1-11eb-995e-2264e2c13d4b.png)

-------
Verification passed on iPhone XR with iOS 13.5 running 1.24(21.3.31.15)
- Verified subtitles match spec 
**Note: The values are divided by 100 so its easy to test all of them.**

1,000 | 5,000  | 10,000  | 25,000 | 75,000 | 100,000 | 250,000 | 500,000 | 1,000,000 
-- | -- | -- | -- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/113282309-a6935300-92de-11eb-8f04-28f4b692099d.png) | ![image](https://user-images.githubusercontent.com/17010094/113282325-abf09d80-92de-11eb-844d-ec38eb0db0c5.png) |![image](https://user-images.githubusercontent.com/17010094/113283009-98920200-92df-11eb-874f-8349a07e6ae9.png)  |![image](https://user-images.githubusercontent.com/17010094/113282376-bad75000-92de-11eb-9164-08588a25014d.png) | ![image](https://user-images.githubusercontent.com/17010094/113282407-c591e500-92de-11eb-8a34-c233ca79241b.png) | ![image](https://user-images.githubusercontent.com/17010094/113282458-da6e7880-92de-11eb-92fa-db4f7ac77986.png) | ![image](https://user-images.githubusercontent.com/17010094/113282806-5963b100-92df-11eb-813b-ed28dfd8e3f3.png) | ![image](https://user-images.githubusercontent.com/17010094/113282863-6da7ae00-92df-11eb-912b-fe7810952c8d.png) | ![image](https://user-images.githubusercontent.com/17010094/113282885-74362580-92df-11eb-9bcb-3738266c882b.png)

--------
Verification passed on iPad Pro with iOS 12.4.1 running 1.24(21.3.31.15)
- Verified subtitles match spec 
**Note: The values are divided by 100 so its easy to test all of them.**

1,000 | 5,000  | 10,000  | 25,000 | 75,000 | 100,000 | 250,000 | 500,000 | 1,000,000 
-- | -- | -- | -- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/113283174-d131db80-92df-11eb-94e1-ec9bcbd86995.png) | ![image](https://user-images.githubusercontent.com/17010094/113283200-db53da00-92df-11eb-9959-55b5e0e5dd18.png) | ![image](https://user-images.githubusercontent.com/17010094/113283767-9e3c1780-92e0-11eb-8f4f-51c24a61d6d8.png) | ![image](https://user-images.githubusercontent.com/17010094/113283296-0807f180-92e0-11eb-82b9-3ebd8fd5013e.png) | ![image](https://user-images.githubusercontent.com/17010094/113283324-12c28680-92e0-11eb-8759-1bf5cbc35f4d.png) | ![image](https://user-images.githubusercontent.com/17010094/113283366-1c4bee80-92e0-11eb-90f3-00013c56d34f.png) | ![image](https://user-images.githubusercontent.com/17010094/113283380-21a93900-92e0-11eb-9ac5-f3a246115330.png) | ![image](https://user-images.githubusercontent.com/17010094/113283392-253cc000-92e0-11eb-82a0-a51125038db9.png) | ![image](https://user-images.githubusercontent.com/17010094/113283410-2c63ce00-92e0-11eb-900e-46ae51eaf205.png)
