### ISSUE TITLE
Update themes to match Brave colour palettes

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3482]
The light and dark theme both need updating to match Brave's colour palettes. These more closely resemble the colours used in the Shields/Rewards popovers

**Comment by srirambv** [comment]
Marking as QA Blocked on test plan. @jamesmudgett please add a test plan/screenshots for reference so QA can verify the issue.

**Comment by jamesmudgett** [comment]
![712AF2DB-4AFC-4C0C-939D-4436F9C1E44B](https://user-images.githubusercontent.com/318119/116509978-d60b9000-a889-11eb-8541-c7063196a1f3.png) | ![2EB0AC68-46B1-4EC2-AEC9-3C05BD6CD25E](https://user-images.githubusercontent.com/318119/116509980-d73cbd00-a889-11eb-9df1-93b88300965f.png) | ![325E26E4-DA6C-48AA-A01F-2F6AE53FC291](https://user-images.githubusercontent.com/318119/116509986-d7d55380-a889-11eb-85dc-f9cf3ccd6656.png) | ![8D6EB7DA-3E6F-4AA3-8625-89937359D6C7](https://user-images.githubusercontent.com/318119/116509989-d9068080-a889-11eb-9b4f-49975182a22a.png) | ![25B5C9D3-F519-452E-8245-B02D33D2CD1C](https://user-images.githubusercontent.com/318119/116509992-d9068080-a889-11eb-9994-8b82637e15bc.png)
-- | -- | -- | -- | -- 
 ![A79406AC-12B9-4290-9BC6-EB536EA38527](https://user-images.githubusercontent.com/318119/116509993-d99f1700-a889-11eb-933d-112e517ecbb1.png) | ![FAA53930-F1CD-4612-8533-CF82CC04BA3F](https://user-images.githubusercontent.com/318119/116509996-db68da80-a889-11eb-9c26-c9699ec43052.png) | ![7AEBCF56-BD03-4F30-B84D-08805884B376](https://user-images.githubusercontent.com/318119/116510004-dd329e00-a889-11eb-8b02-ae3cfc2fe049.png) | ![26A57172-03C4-4B3F-8BE4-FBF8FD244A34](https://user-images.githubusercontent.com/318119/116510006-ddcb3480-a889-11eb-8f1b-6248580de2f1.png) | ![07C47CAE-0E76-407F-8882-2040A85523ED](https://user-images.githubusercontent.com/318119/116510011-defc6180-a889-11eb-904d-7bcbf364f089.png)

**Comment by jamesmudgett** [comment]
![07C47CAE-0E76-407F-8882-2040A85523ED](https://user-images.githubusercontent.com/318119/116510011-defc6180-a889-11eb-904d-7bcbf364f089.png)

**Comment by jamesmudgett** [comment]
The shots added above are from expected UI color changes.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.25(21.4.28.19)

<details>
<summary>Verified against screenshots from <a href=https://github.com/brave/brave-ios/issues/3482#issuecomment-828972269>#3482 (comment)</a></summary>


![image](https://user-images.githubusercontent.com/17010094/116516433-864aba00-a8c5-11eb-94a8-6ea1d6f304da.png) | ![image](https://user-images.githubusercontent.com/17010094/116516443-8945aa80-a8c5-11eb-9056-19c46178aeb3.png) | ![image](https://user-images.githubusercontent.com/17010094/116516466-8c409b00-a8c5-11eb-8e69-a33ce31d41bd.png) | ![image](https://user-images.githubusercontent.com/17010094/116516489-906cb880-a8c5-11eb-8538-ec7c689bd494.png) | ![image](https://user-images.githubusercontent.com/17010094/116516582-ad08f080-a8c5-11eb-8741-553f10ef4a31.png)
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/116516637-bd20d000-a8c5-11eb-925c-e2228e7edf19.png) | ![image](https://user-images.githubusercontent.com/17010094/116516673-c873fb80-a8c5-11eb-8c4c-b0ad8a8056b7.png) | ![image](https://user-images.githubusercontent.com/17010094/116516697-d0cc3680-a8c5-11eb-9c60-a6cee7faa1cf.png) | ![image](https://user-images.githubusercontent.com/17010094/116516711-d45fbd80-a8c5-11eb-8831-0bfbf29c15ce.png) | ![image](https://user-images.githubusercontent.com/17010094/116516725-d9bd0800-a8c5-11eb-9def-d50d3ce850d1.png)

</details>

------------

Verification passed on iPhone 7+ with iOS 14.5 running 1.25(21.4.28.19)

<details>
<summary>Verified against screenshots from <a href=https://github.com/brave/brave-ios/issues/3482#issuecomment-828972269>#3482 (comment)</a></summary>


![image](https://user-images.githubusercontent.com/17010094/116522558-3b34a500-a8cd-11eb-8572-ff22adb97ed3.png) | ![image](https://user-images.githubusercontent.com/17010094/116522610-48ea2a80-a8cd-11eb-893a-86246b58c8b8.png) | ![image](https://user-images.githubusercontent.com/17010094/116522642-54d5ec80-a8cd-11eb-9181-c8c28be30099.png) | ![image](https://user-images.githubusercontent.com/17010094/116522656-599aa080-a8cd-11eb-98eb-46909ece3c57.png) | ![image](https://user-images.githubusercontent.com/17010094/116522674-5dc6be00-a8cd-11eb-9593-67a1fcb20be0.png)
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/116522745-7040f780-a8cd-11eb-9fcb-5e6eb691839d.png) | ![image](https://user-images.githubusercontent.com/17010094/116522812-818a0400-a8cd-11eb-8473-0626195d7004.png) | ![image](https://user-images.githubusercontent.com/17010094/116522863-8cdd2f80-a8cd-11eb-9e7b-9909a09a4fe9.png) | ![image](https://user-images.githubusercontent.com/17010094/116522907-95ce0100-a8cd-11eb-87e1-b31615556759.png) | ![image](https://user-images.githubusercontent.com/17010094/116522958-a1b9c300-a8cd-11eb-81e1-cbe1fa877a68.png)

</details>

------------

Verification passed on iPad Pro with iOS 14.4.2 running 1.25(21.4.28.19)

<details>
<summary>Verified against screenshots from <a href=https://github.com/brave/brave-ios/issues/3482#issuecomment-828972269>#3482 (comment)</a></summary>

![image](https://user-images.githubusercontent.com/17010094/116528794-23acea80-a8d4-11eb-9eda-b83f0025814a.png) | ![image](https://user-images.githubusercontent.com/17010094/116528807-26a7db00-a8d4-11eb-829e-adefb2ea33fb.png) | ![image](https://user-images.githubusercontent.com/17010094/116528830-2ad3f880-a8d4-11eb-8c45-71bebabe93ca.png) | ![image](https://user-images.githubusercontent.com/17010094/116528843-2dcee900-a8d4-11eb-80c7-5b34471e8b00.png) | ![image](https://user-images.githubusercontent.com/17010094/116528870-345d6080-a8d4-11eb-9fee-af5f351315a5.png)
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/116528903-42ab7c80-a8d4-11eb-92a5-23d75471521d.png) | ![image](https://user-images.githubusercontent.com/17010094/116528950-50f99880-a8d4-11eb-99d1-2940a5efec01.png) | ![image](https://user-images.githubusercontent.com/17010094/116529018-61117800-a8d4-11eb-823e-baf03b6824cf.png) | ![image](https://user-images.githubusercontent.com/17010094/116529146-83a39100-a8d4-11eb-885a-237b28aae42d.png) | ![image](https://user-images.githubusercontent.com/17010094/116529157-87371800-a8d4-11eb-9b42-3aab96a97db0.png)

</details>
