### ISSUE TITLE
Fix duplicated text on VPN screen

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3484]
### Description: 
"at least" is duplicated on the VPN screen. Can you please fix this issue. 

Thanks

![Screenshot 2021-03-29 at 5 43 44 PM](https://user-images.githubusercontent.com/7606853/112926778-ce10d280-90c8-11eb-8d6c-ca9c9d5c116d.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.25(21.4.15.13)
- Verified duplicate text is removed

iPhone 7+(iOS 14.4) | iPhone XR (iOS 13.5) | iPad Pro (iOS 14.4)
-- | -- | --
<img width=350 src=https://user-images.githubusercontent.com/17010094/115028607-f5371480-9ebc-11eb-9ef5-9a18ae68e1a0.png>  | <img width=290 src=https://user-images.githubusercontent.com/17010094/115028588-f10af700-9ebc-11eb-911a-b75f7aae9bb1.png> | <img width=460 src=https://user-images.githubusercontent.com/17010094/115028621-f9633200-9ebc-11eb-9363-f162585dedbc.png>
