### ISSUE TITLE
webauthn modal appears on other applications when switching apps

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3486]
### Description: 

WebAuthn modal quickly displayed in other applications if you switch over while the `PIN verification` modal is visible. This only happens on devices that have the ability to use third party NFC. For example, this doesn't happen on `iPhone 6s+`.

### Steps to Reproduce

**`Prerequisite:`** ensure that you've set a PIN code on your YubiKey.

  1. visit https://demo.yubico.com/webauthn-technical/registration
  2. tap on `Next` to start the WebAuthn process
  3. when you receive the `PIN verification` modal, switch to another app that's currently opened

**Actual result:** 

**`Example`** | **`Example`**
----------------|---------------
![IMG_3625](https://user-images.githubusercontent.com/2602313/112935606-1690b600-90f2-11eb-8482-8caadb31f4f1.png) | ![IMG_3627](https://user-images.githubusercontent.com/2602313/112935617-1abcd380-90f2-11eb-9bc3-79b508e526ad.png)

**Expected result:**

We shouldn't be showing webauthn modals on other applications when switching over as it might confuse some users.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR mentioned above.

**Brave Version:** 

* `1.23.1 (21.2.24.16)` - **Reproduced**
* `1.24 (21.3.29.21)` - **Reproduced**

**Device details:** 

* `iPhone 12` running `iOS 14.4` - **Reproduced**
* `iPhone 11` running `iOS 14.4` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @anthonypkeane @bsclifton @jumde @brave/legacy_qa

**Comment by iccub** [comment]
Isn't this modal the one that ships with webkit? can this be reproduced with safari-ios?

**Comment by jumde** [comment]
@iccub - this modal is displayed when the NFC scanning is turned on by an app, on app transition we should cancel the webauthn workflow and dismiss this modal.

**Comment by kjozwiak** [comment]
Closing as we've deprecated the `Yubikey` SDK in favour of the `WKWebView` SDK as per https://github.com/brave/brave-ios/issues/4473. QA went through verifications via https://github.com/brave/brave-ios/issues/4473#issuecomment-1032291511, https://github.com/brave/brave-ios/issues/4473#issuecomment-1033102239 & https://github.com/brave/brave-ios/issues/4473#issuecomment-1033240109 and couldn't reproduce the crashes using the `WKWebView` SDK.
