### ISSUE TITLE
Problem with switching between apps while keyboard is opened in Brave and fingerprint lock is enabled

### ISSUE THREAD

**Issue by dave90dave** [brave/brave-ios#3487]
### Description: 
When I switch apps, while the keyboard is open in brave, it the whole page is blurred out, while keyboard is open.
I think that the problem is something with the fingerprint authentication of brave.

(I blurred a couple tabs on purpose, that is not the blur that I mean)

### Steps to Reproduce 
  1. start brave ios
  2. Make sure fingerprint lock is enabled.
  3. go to a site (for example google search)
  4. click on the text box, so that the keyboard is opened.
  5. type some random text.
  6. Double click the Iphone home button, to switch between other apps.
  7. Open another app.
  8. Double click the Iphone home button again.
  9. Switch to brave.
  10. Now the keyboard will be showen, but the site and text box itself, is blurred out.

**Actual result:** 

https://user-images.githubusercontent.com/7985017/112953899-2c2bcd00-913e-11eb-983d-832d69dd8c77.mp4

**Expected result:**
That the site is visible, without full site blur

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
always. when switched between different apps.
You need to have fingerprint lock enabled I guess.

**Brave Version:** 
1.23.1 (21.2.24.16)

**Device details:** 
Iphone SE 2020

**Comment by dave90dave** [comment]
Aditional information:
When double click Iphone home button, and select brave for a second time, the blur disapears.

**Comment by dave90dave** [comment]
Hi,

It have been some months now, and I didn't receive any update on this issue.
The bug does still exist.

When is there gonna be a bugfix?

Regards
Dave

**Comment by kylehickinson** [comment]
Hey @dave90dave I believe this is already fixed when we refactored the browser lock code. I did a quick test and found that it no longer bugged out when backgrounding with the keyboard open. I'm going to close this but if you find it happens again in the latest version please let me know!
