### ISSUE TITLE
New Menu UI

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3491]
Change the `•••` menu to display a scrollable modal which will allow for more dynamic actions within the menu.

Main differences:
- Starts half expanded, can be scrolled to full expansion
- Most screens are presented within the menu (with the exception of Playlist for the time being) and website actions
- Website actions are brought up to the main menu rather than living only within the Share With… menu

Expected behaviour of all actions within the new menu should match previous behaviour of old menu (Bookmarks bring up bookmarks, downloads brings up downloads, show desktop site loads desktop sites, etc. etc.)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(25.1.25.18)

<details>
<summary>Verified test plan from #3465</summary>
<br>

- Verified all menu options work as expected 
- Verified both light/dark theme work fine on menu
- Verified VPN button works correctly and shows loading indicator when trying to connect

New Tab Page | Website | Website Expanded | VPN connecting
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/119870824-af3c8a00-bf19-11eb-8eef-7d21e8249bff.png) | ![image](https://user-images.githubusercontent.com/17010094/119870684-8a481700-bf19-11eb-825c-054ac4051d72.png) | ![image](https://user-images.githubusercontent.com/17010094/119870701-8fa56180-bf19-11eb-8a81-6245fb8c479d.png) | ![image](https://user-images.githubusercontent.com/17010094/119870717-92a05200-bf19-11eb-89a8-4481863be21f.png)

</details>

---------
Verification passed on iPhone XR with iOS 14.5.1 running 1.26(25.1.26.21)

<details>
<summary>Verified test plan from #3465</summary>
<br>

- Verified all menu options work as expected 
- Verified both light/dark theme work fine on menu
- Verified VPN button works correctly and shows loading indicator when trying to connect

New Tab Page | Website | Website Expanded | VPN connecting
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/119871011-e9a62700-bf19-11eb-904a-838279c4b485.png) | ![image](https://user-images.githubusercontent.com/17010094/119870998-e612a000-bf19-11eb-8cc5-7954f4be4591.png) | ![image](https://user-images.githubusercontent.com/17010094/119870988-e1e68280-bf19-11eb-9564-74a9977abf4c.png) | ![image](https://user-images.githubusercontent.com/17010094/119870947-d2ffd000-bf19-11eb-9dc6-fb97b2d14b1a.png)

</details>

----------
Verification passed on iPad Pro with iOS 14.5.1 running 1.26(25.1.26.21)

<details>
<summary>Verified test plan from #3465</summary>
<br>

- Verified all menu options work as expected 
- Verified both light/dark theme work fine on menu
- Verified VPN button works correctly and shows loading indicator when trying to connect

New Tab Page | Website | VPN connecting
-- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/119872274-30e0e780-bf1b-11eb-80a5-f56e6a56ffd5.png) | ![image](https://user-images.githubusercontent.com/17010094/119872115-04c56680-bf1b-11eb-8a95-dab6615da7a5.png) | ![image](https://user-images.githubusercontent.com/17010094/119872507-76051980-bf1b-11eb-8c24-d28792d26051.png)

</details>
