### ISSUE TITLE
links within settings menu lose link colour when return into main settings page from a sub settings page

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3493]
### Description: 

When navigating from the settings page for `Brave Firewall + VPN` into another subpage and then returning back, links will lose their orange hyperlink colour making it difficult to know what is normal text and what is clickable.

### Steps to Reproduce
 
  1. launch `1.24` via TF (`1.24 (21.3.29.21)` in this case)
  2. sign up/grab a subscription for the VPN service (picked the monthly subscription)
  3. go into `Settings` -> `Brave Firewall + VPN`
  4. go into `Change Location` and go back into the root VPN settings page

**Actual result:** 

![IMG_0165](https://user-images.githubusercontent.com/2602313/113083673-95e1c080-91aa-11eb-942b-d533e83d28ba.png)

**Expected result:**

![IMG_0166](https://user-images.githubusercontent.com/2602313/113083693-9ed29200-91aa-11eb-800f-b801891b8a59.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible when running through the above STR.

**Brave Version:** 

* `1.24 (21.3.29.21)` - **Reproduced**

**Device details:** 

* `iPhone 6s+` running `iOS 12.4.1` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @bsclifton @anthonypkeane @iccub @brave/legacy_qa

**Comment by kjozwiak** [comment]
Can probably skip this one for `1.24` and move it somewhere else if it's a tricky fix. I don't think the user base for `iOS 12` is that high plus this isn't something that breaks functionality. Please move into another milestone if needed 👍

**Comment by iccub** [comment]
I think we just drop it, next release is going to be iOS13+

I will see if it's an easy fix, if not I would prefer to skip it

**Comment by iccub** [comment]
And to be sure: this is not a regression?

**Comment by srirambv** [comment]
> I think we just drop it, next release is going to be iOS13+

+1 :point_up:

**Comment by kjozwiak** [comment]
> I think we just drop it, next release is going to be iOS13+
> 
> I will see if it's an easy fix, if not I would prefer to skip it

Agreed, forgot we're dropping `iOS 12` support next release. Going to close this off 👍
