### ISSUE TITLE
Pop-over messages should not be shown on NTP

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#3496]
Description:
The pop-over messages are being shown when NTP is on active display.

Steps to Reproduce

- Follow test plan from #3387
- Create a new tab using the + icon on bottom toolbar while page is loading

**Actual  result:**

![Image from iOS (20)](https://user-images.githubusercontent.com/6643505/113166432-c2c8be80-9210-11eb-8fbb-0cb2b49085fa.png)

**Expected result:**

No pop-over should be presented on NTP

Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced,

Brave Version:
1.24(21.3.25.18)

Device details:
All

Website problems only:

did you check with Brave Shields down? N_A
did you check in Safari/Firefox (WkWebView-based browsers)? N_A

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4.2 running 1.24(21.3.31.15)
- Verified steps from issue description
- Verified notification is only shown when a page is loaded in a tab
-----------
Verification passed on iPhone XR with iOS 13.5 running 1.24(21.3.31.15)
- Verified steps from issue description
- Verified notification is only shown when a page is loaded in a tab
-----------
Verification passed on iPad Pro with iOS 12.4.1 running 1.24(21.3.31.15)
- Verified steps from issue description
- Verified notification is only shown when a page is loaded in a tab
