### ISSUE TITLE
Deleting last private tab in tab tray should not create a new private tab

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#350]
A regression after merging #346, the tab tray no longer shows the empty private mode info since it creates a new private tab upon deleting the final one. 

The expected behaviour should only happen when **deleting it from the tab tray**. Meaning when you delete the last tab from the tab bar on iPad it should still create a new tab

Might be a security bug due to the user not being able to see private mode info after creating 1 private tab in their session.

### Steps to Reproduce 
  1. Switch to private mode (see private mode info) 
  2. Create a new tab
  3. Go back into the tab tray
  4. Delete the only private tab

**Actual result:** Creates a new tab
**Expected result:** Should show private mode info 
**Reproduces how often:** Always

**Comment by jamesmudgett** [comment]
No need to show empty tab tray on final tab close. User can return to private tab messaging by leaving private mode then re-entering private mode.
