### ISSUE TITLE
YouTube is misspelled as Youtube in preloaded new-tab page Favorites list

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#3501]
### Description: 
YouTube is misspelled as Youtube in preloaded new-tab page Favorites list

### Steps to Reproduce 
  1. Open a new-tab page
  2. Look at the `Youtube` (sic) preloaded Favorite

**Actual result:** 

It's written as `Youtube`; line of code is here: https://github.com/brave/brave-ios/blob/7ee352f6e40155ba2e513fdf5cd402bce3472e0e/Client/Frontend/Browser/Favorites/PreloadedFavorites.swift#L18

![YouTube](https://user-images.githubusercontent.com/387249/113404300-c9644c80-935c-11eb-8884-c2f3d4ebdef6.jpg)

**Expected result:**

Should be `YouTube`.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
`1.24 (21.3.17.17)`

**Device details:** 
iPhone 8 Plus

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.25(21.4.15.13)
- Verified on a clean install favourite shows `YouTube`
- Verified on upgrade the favourite still retains `Youtube` and doesn't replace it with `YouTube`

iPhone 7+ (iOS 14.4) | iPhone XR (iOS 13.5) | iPad Pro (iOS 14.4)
-- | -- | --
<img width=350 src=https://user-images.githubusercontent.com/17010094/114994516-c442e980-9e94-11eb-98c0-cf651b2ef1af.png>  | <img width=290 src=https://user-images.githubusercontent.com/17010094/114994536-c86f0700-9e94-11eb-884f-b4bf983d5b5c.png> | <img width=450 src=https://user-images.githubusercontent.com/17010094/114994552-cc9b2480-9e94-11eb-8723-7a90b5db36b3.png>
