### ISSUE TITLE
Tab separator lines not updating with theme change.

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#3506]
### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
Fixed in https://github.com/brave/brave-ios/pull/3552
