### ISSUE TITLE
Add option to always open in Private mode

### ISSUE THREAD

**Issue by Marc66** [brave/brave-ios#3517]
## Problem Description
I used to use Firefox on my iPhone and stopped using all Mozilla products on my devices, switching to Brave. Firefox had a feature to "remember" the last browser setting: if it was last used in normal mode and closed, it would re-open in normal mode. If it was last used in private mode and closed, it would re-open in private mode.

On Brave, if I use private mode and close, the next time I open it, it defaults to normal mode.

## Feature Overview
Could a switch be added to either remember the last browser mode or have a toggle switch to select the default mode (normal or private)?

The tab behaviour does not need to change:
- If the default is to re-open in normal mode, all tabs which were previously opened in normal mode shall be re-opened
- If the default is to re-open in private mode, it should re-open with empty tabs

**Comment by iccub** [comment]
There is `Private Browsing only` mode in app settings.
It makes you always start in private mode, and no tabs are persisted.

Is this good enough for you?

<img width="340" alt="Zrzut ekranu 2021-04-14 o 18 07 46" src="https://user-images.githubusercontent.com/6950387/114742751-52f81f00-9d4c-11eb-84ea-738bb8de47d6.png">

**Comment by Marc66** [comment]
Yes, that's perfect. Sorry I missed it

**Comment by iccub** [comment]
No problem :) thanks for using Brave,

I'm going to close this ticket
