### ISSUE TITLE
Tabs button long press "Close All Tabs" should no longer show a number

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#352]
Should show the number of tabs only for its specific mode (private vs regular) not the combined amount.

![simulator screen shot - iphone x - 2018-10-23 at 16 39 50](https://user-images.githubusercontent.com/529104/47389275-5c0b5680-d6e2-11e8-9704-f20327e5e75c.png)

**Comment by jamesmudgett** [comment]
We have a number indicator in tab tray icon. We can get rid of # here "Close all tabs"

**Comment by jhreis** [comment]
Blocked per a `TabManager` refactor.
