### ISSUE TITLE
Replace Math.random js crypto with crypto.getRandomValues

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3521]
Follow up of https://github.com/brave/security/issues/416

**Comment by Uni-verse** [comment]
Verified on `1.44 (22.10.13.13)` using the following device(s):

iPhone 12 | iOS 16.x
iPhone XR | iOS 15.x
iPhone X | iOS 14.x
IPad | iPadOS 15.x

Test Plan: https://github.com/brave/brave-ios/pull/6070#issue-1388414826

- Verified saved logins are working

![IMG_3901](https://user-images.githubusercontent.com/17885425/195666652-59aa3504-c358-460c-a55f-f038828e8e99.jpg)
