### ISSUE TITLE
Playlist Toast gets stuck

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#3528]
### Description: 
When quickly going back and forth between pages with media items and pages without any, sometimes the playlist toast gets stuck on screen and a new toast appears above the old one. There is no way to get rid of the old one.

### Steps to Reproduce 
  1. Go to a media site
  2. Hit the back button really fast.. then forward, then back (repeatedly do this)
  3. Notice the toast gets stuck.

**Actual result:** 
Toast gets stuck on screen.

**Expected result:**
Toast should not get stuck and should be dismissed when switching websites.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent Issue

**Brave Version:** 
1.25(21.4.15.13)

**Device details:** 
Any

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4.2 running 1.25(21.4.21.15)
- Verified steps from issue description
------------
Verification passed on iPhone XR with iOS 13.5 running 1.25(21.4.21.15)
- Verified steps from issue description
------------
Verification passed on iPad Pro with iOS 14.4.2 running 1.25(21.4.21.15)
- Verified steps from issue description
