### ISSUE TITLE
On iPad, offline videos show wrong size

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3530]
### Steps to Reproduce 
  1. Install on an iPad
  2. Go to youtube, pick a video
  3. Add it to playlsits
  4. Go to to playlists screen

**Actual result:** 
Very small download size value is shown,

![IMG_0198](https://user-images.githubusercontent.com/6950387/114907163-1515fc00-9e1b-11eb-9a9a-8843e2b848ab.jpg)

**Expected result:**
The download size should be bigger

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on following devices running 1.25(21.4.21.15)
- Verified download size is shown properly

iPhone 7+ (iOS 14.4.42) | iPhone XR (iOS 13.5) | iPad Pro (iOS 14.4.2)
-- | -- | --
<img width=350 src=https://user-images.githubusercontent.com/17010094/115875446-207dae80-a43d-11eb-9ee3-bfeec15945a0.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/115875467-25daf900-a43d-11eb-9e05-9b9339d27e9e.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/115874453-04c5d880-a43c-11eb-939d-1fcf7e030677.png>
