### ISSUE TITLE
Playlist: Add to Brave Playlist toast design change

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#3532]
Feedback has suggested that the "Add to Playlist" toast may not feel like part of the Brave UI. One way to get closer to Brave UI is to update the color of the toast.

Keeping existing toast design. Change the current blue background to a Brave brand gradient.

`linear-gradient(304.74deg, #6F4CD2 15.81%, #BF14A2 63.17%, #F73A1C 100%);`

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4.2 running 1.25(214.21.15)
- Verified test plan from https://github.com/brave/brave-ios/pull/3548
- Verified toast uses new design

Add to Brave Playlist | Added to Playlist | View in Playlist
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/115664981-86cdd880-a33a-11eb-9ee8-fa0b77a30c6e.png) | ![image](https://user-images.githubusercontent.com/17010094/115665001-8b928c80-a33a-11eb-87e1-e9d0590516ae.png) | ![image](https://user-images.githubusercontent.com/17010094/115664968-803f6100-a33a-11eb-8b1d-29942bf9d7eb.png)

--------
Verification passed on iPhone XR with iOS 13.5 running 1.25(214.21.15)
- Verified test plan from https://github.com/brave/brave-ios/pull/3548
- Verified toast uses new design

Add to Brave Playlist | Added to Playlist | View in Playlist
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/115664947-79185300-a33a-11eb-9362-ec5ca9a42794.png) | ![image](https://user-images.githubusercontent.com/17010094/115664938-761d6280-a33a-11eb-8ae8-6357ecc0f0d1.png) | ![image](https://user-images.githubusercontent.com/17010094/115664925-7289db80-a33a-11eb-8696-44bb1c2db6b4.png)

--------
Verification passed on iPad Pro with iOS 14.4.2 running 1.25(214.21.15)
- Verified test plan from https://github.com/brave/brave-ios/pull/3548
- Verified toast uses new design

Add to Brave Playlist | Added to Playlist | View in Playlist
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/115664888-61d96580-a33a-11eb-830f-96d8d124c8d1.png) | ![image](https://user-images.githubusercontent.com/17010094/115664899-6736b000-a33a-11eb-814e-504914813f1c.png) | ![image](https://user-images.githubusercontent.com/17010094/115664908-6b62cd80-a33a-11eb-9b47-94a3da6926dd.png)
