### ISSUE TITLE
Opening a pdf, then tab tray and going back to that tab glitches the UI

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3534]
### Description: 
See this post https://community.brave.com/t/bug-in-ios-when-viewing-bat-white-paper/234533

### Steps to Reproduce 
  1. Open the BAT White paper from the brave home site
  2. Select the option to view all tabs open
  3. Open back up the tab with the white paper open

**Actual result:** 
The page opens as a blank black window

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Fixed in https://github.com/brave/brave-ios/pull/4325
please retest using STR in this ticket

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using the following build:

```
1.33 (21.12.6.21)
```

* verified the STR/Cases outlined via https://github.com/brave/brave-ios/issues/3534#issue-859833145 and ensured that PDF's don't appear blank when opening the tab tray and then re-selecting the same PDF or tapping on `Done`.

**`1.32.3 (21.11.17.19)`** | **`1.33 (21.12.6.21)`**
---------------------------|---------------------------
![image](https://user-images.githubusercontent.com/2602313/145080479-4e493919-2b95-41aa-af45-6901d417cc9b.png) | ![image](https://user-images.githubusercontent.com/2602313/145080498-4e32e885-c72a-4a37-b423-c48fb61c5f37.png)

--------------------

Verification **PASSED** on `iPhone 6+` running `iOS 14.6` using the following build:

```
1.33 (21.12.6.21)
```

* verified the STR/Cases outlined via https://github.com/brave/brave-ios/issues/3534#issue-859833145 and ensured that PDF's don't appear blank when opening the tab tray and then re-selecting the same PDF or tapping on `Done`.

**`1.32.3 (21.11.17.19)`** | **`1.33 (21.12.6.21)`**
---------------------------|---------------------------
![image](https://user-images.githubusercontent.com/2602313/145081642-d71cf8c1-87ca-4172-8e15-3a1af3972498.png) | ![image](https://user-images.githubusercontent.com/2602313/145081677-e8ea625d-7271-4675-bbb1-6ee924065542.png)

--------------------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.1` using the following build:

```
1.33 (21.12.6.21)
```

* verified the STR/Cases outlined via https://github.com/brave/brave-ios/issues/3534#issue-859833145 and ensured that PDF's don't appear blank when opening the tab tray and then re-selecting the same PDF or tapping on `Done`.

**`1.32.3 (21.11.17.19)`** | **`1.33 (21.12.6.21)`**
---------------------------|---------------------------
![image](https://user-images.githubusercontent.com/2602313/145082756-8f0fb372-d61d-4935-8e64-50aa8170457b.png) | ![image](https://user-images.githubusercontent.com/2602313/145082722-b7e41e09-43b0-48c2-b53a-e7a029f3b60c.png)
