### ISSUE TITLE
Button on playlist top bar on iPad are hard to tap

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3541]
### Steps to Reproduce 
  1. Use iPad
  2. Open playlist screen
  3. Try to tap near the 'close' or 'show sidebar' buttons

**Actual result:** 
Tap area is super small

**Expected result:**
Add more tap area

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 14.4.2 running 1.25(21.4.21.15)
- Verified tap area for close/show sidebar is large enough to close/show sidebar

https://user-images.githubusercontent.com/17010094/116073585-86aa4180-a688-11eb-8df3-ee409110582f.MP4
