### ISSUE TITLE
Encrypted connection message shown on http pages

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3542]
### Description: 
Encrypted connection message shown on http pages

### Steps to Reproduce 
  1. Clean install 1.25 build
  2. Visit a page to trigger ad block tooltip
  3. Visit `radio.garden` which is a http page, triggers connection encrypted tooltip

**Actual result:** 
<img width=300 src=https://user-images.githubusercontent.com/17010094/115192725-1b3dfe00-a0e3-11eb-9c5c-782656170575.png>

**Expected result:**
Only show encrypted message when http pages are redirected to https

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.25(21.4.15.13)

**Device details:** 
iPhone 7+ (iOS 14.4.2)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc: @soner-yuksel

**Comment by diracdeltas** [comment]
labeling this as sec-high since it involves security indicators

FYI on desktop this shows one HTTPS everywhere subresource upgrade, but the top level page is HTTP.

**Comment by anthonypkeane** [comment]
Please remove this pop up given the conversation in https://bravesoftware.slack.com/archives/G2KN13Z8C/p1618868509001500

**Comment by iccub** [comment]
Closing this one, we will remove the popup in this ticket https://github.com/brave/brave-ios/issues/3556
