### ISSUE TITLE
Audio continues to play even after tab is closed 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3544]
### Description: 
While testing #3358, ran into an bug where the audio continued to play even after the tab was closed. Opening and closing new tabs didn't stop the audio

### Steps to Reproduce 
  1. Clean install 1.25
  2. Open a new tab and open Amazon from favourites
  3. Open a second tab and load `radio.garden`
  4. Wait for the station to auto populate based on location
  5. Move to a different location to change station
  6. Change channel from the list and close the tab, audio continues to play

**Actual result:** 
Audio continues to play even after tab is closed 

**Expected result:**
Stop audio when tab is closed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Happened only once

**Brave Version:** 
1.25(21.4.15.13)

**Device details:** 
iPad Pro (iOS 14.4.2)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
Was able to repro the issue only once and when tried few more times doesn't reproduce

**Comment by iccub** [comment]
Saw it few times too, it's an old bug, unrelated to playlists i'm pretty sure

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(21.5.25.18)
- Verified steps from issue description
- Verified tabs are restored properly 
- Verified audio stops when the tab playing it is closed
---------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.26(21.5.25.18)
- Verified steps from issue description
- Verified tabs are restored properly 
- Verified audio stops when the tab playing it is closed
-----------
Verification passed on iPad Pro with iOS 14.5.1 running 1.26(21.5.25.18)
- Verified steps from issue description
- Verified tabs are restored properly 
- Verified audio stops when the tab playing it is closed
