### ISSUE TITLE
Implement Search Overlay

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3554]
### Description: 
Please search GDrive for "Search Overlay"

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.27(21.6.18.10)
- Verified QR code scanner is shown when URL is focused 
- Verified able to scan a QR code and load the page immediately 
- Verified able to scan QR code can be scanned on both normal and private tabs
- Verified QR code scanned on private tabs do not show up in normal tab recent search history
- Verified `Recent Searches` option shows up when URL is focused
- Verified enabling it shows the 5 most recent searches including QR code scanned URL's 
- Verified show more shows up when there are more than 5 searches and clicking on it shows the whole list
- Verified clear option for recent search throws confirmation before clearing it
- Verified disabling recent searches from Search Engine settings doesn't clear the history
- Verified copying URL/text to clipboard and focusing on URL bar shows `Paste & Go` button
- Verified copying URL and selecting `Paste & Go` loads the page
- Verified copying text and selecting `Paste & Go` performs search
- Verified clicking on the arrow mark in recent searches only fills the URL with search term and doesn't perform/load the search 
- Verified performing a search using Quick SE adds `on StartPage` text to the search history
- Screenshots can be found [here](https://github.com/brave/brave-ios/issues/3758#issuecomment-863933103)
----------------
Verification passed on iPhone 7+ with iOS 14.6 running 1.27(21.6.18.10)
- Verified QR code scanner is shown when URL is focused 
- Verified able to scan a QR code and load the page immediately 
- Verified able to scan QR code can be scanned on both normal and private tabs
- Verified QR code scanned on private tabs do not show up in normal tab recent search history
- Verified `Recent Searches` option shows up when URL is focused
- Verified enabling it shows the 5 most recent searches including QR code scanned URL's 
- Verified show more shows up when there are more than 5 searches and clicking on it shows the whole list
- Verified clear option for recent search throws confirmation before clearing it
- Verified disabling recent searches from Search Engine settings doesn't clear the history
- Verified copying URL/text to clipboard and focusing on URL bar shows `Paste & Go` button
- Verified copying URL and selecting `Paste & Go` loads the page
- Verified copying text and selecting `Paste & Go` performs search
- Verified clicking on the arrow mark in recent searches only fills the URL with search term and doesn't perform/load the search 
- Verified performing a search using Quick SE adds `on StartPage` text to the search history
- Screenshots can be found [here](https://github.com/brave/brave-ios/issues/3758#issuecomment-863933103)

----------------
Verification passed on iPad Pro with iOS 14.6 running 1.27(21.6.18.10)
- Verified QR code scanner is shown when URL is focused 
- Verified able to scan a QR code and load the page immediately 
- Verified able to scan QR code can be scanned on both normal and private tabs
- Verified QR code scanned on private tabs do not show up in normal tab recent search history
- Verified `Recent Searches` option shows up when URL is focused
- Verified enabling it shows the 5 most recent searches including QR code scanned URL's 
- Verified show more shows up when there are more than 5 searches and clicking on it shows the whole list
- Verified clear option for recent search throws confirmation before clearing it
- Verified disabling recent searches from Search Engine settings doesn't clear the history
- Verified copying URL/text to clipboard and focusing on URL bar shows `Paste & Go` button
- Verified copying URL and selecting `Paste & Go` loads the page
- Verified copying text and selecting `Paste & Go` performs search
- Verified clicking on the arrow mark in recent searches only fills the URL with search term and doesn't perform/load the search 
- Verified performing a search using Quick SE adds `on StartPage` text to the search history
- Screenshots can be found [here](https://github.com/brave/brave-ios/issues/3758#issuecomment-863933103)
