### ISSUE TITLE
Update "Add to Playlist" text

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3555]
### Description: 
Please update the "Add to Playlist" text to "Add to Brave Playlist" 

There are 3 or more places where the text needs to change, 

- toast
- long press menu
- In the share section
- In settings

possibly more.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4.2 running 1.25(21.4.21.15)

Toast | Share sheet | Setting
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/115708532-0a51ee80-a368-11eb-9157-be028896999a.png) | ![image](https://user-images.githubusercontent.com/17010094/115708472-f3ab9780-a367-11eb-99a3-e5c79b96ed36.png) | ![image](https://user-images.githubusercontent.com/17010094/115708484-fa3a0f00-a367-11eb-9a6f-56ca72040327.png)

-------------

Verification passed on iPhone XR with iOS 13.5 running 1.25(21.4.21.15)
Toast | Share sheet | Setting
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/115708233-a3ccd080-a367-11eb-8939-dc1cdc8573df.png) | ![image](https://user-images.githubusercontent.com/17010094/115708202-9adbff00-a367-11eb-9cdf-9104de4003b2.png) | ![image](https://user-images.githubusercontent.com/17010094/115708184-96174b00-a367-11eb-8a53-f7546b3c286a.png)

------------------

Verification passed on iPad Pro with iOS 14.4.2 running 1.25(21.4.21.15)

Toast | Share sheet | Setting
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/115707361-96fbad00-a366-11eb-80ce-0ca8a547a8a5.png) | ![image](https://user-images.githubusercontent.com/17010094/115707389-a24ed880-a366-11eb-95f8-68c504f5d0df.png) | ![image](https://user-images.githubusercontent.com/17010094/115707402-a67af600-a366-11eb-852a-58df7b0e88ad.png)
