### ISSUE TITLE
Remove HTTPS upgrade edu-popup

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3556]
Followup of https://github.com/brave/brave-ios/issues/3542

**Comment by kjozwiak** [comment]
Adding `sec-high` as @diracdeltas added it via https://github.com/brave/brave-ios/issues/3542#event-4615375660.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4.2 running 1.25(21.4.21.15)
- Verified test plan from https://github.com/brave/brave-ios/pull/3561
- Verified visiting `https://https-everywhere.badssl.com` doesn't trigger encryption tooltip
---------
Verification passed on iPhone XR with iOS 13.5 running 1.25(21.4.21.15)
- Verified test plan from https://github.com/brave/brave-ios/pull/3561
- Verified visiting `https://https-everywhere.badssl.com` doesn't trigger encryption tooltip
---------
Verification passed on iPad Pro with iOS 14.4.2 running 1.25(21.4.21.15)
- Verified test plan from https://github.com/brave/brave-ios/pull/3561
- Verified visiting `https://https-everywhere.badssl.com` doesn't trigger encryption tooltip

**Comment by kjozwiak** [comment]
Changing from `release-notes/exclude` to `release-notes/include`  as this was a user facing change and labeled as `sec-high` so worth mentioning.
