### ISSUE TITLE
View in playlist toast is always shown when opening media sites

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3557]
### Description: 
View in playlist toast is always shown when opening media sites

### Steps to Reproduce 
  1. Clean install 1.25 build
  2. Visit `https://vimeo.com/watch`
  3. Add a few videos to playlist
  4. Disconnect network 
  5. Open Playlist and play a video which is still saving for offline play
  6. Once video pauses after playing buffered stream, connect to network and open YT page, shows toast for `View in playlist` 
  7. Close and open Twitch.tv page still shows the toast until all the videos are done buffering for offline play

**Actual result:** 
<img width=300 src=https://user-images.githubusercontent.com/17010094/115537743-099b5880-a293-11eb-91f9-a0c9a537487e.png>

**Expected result:**
Should only show the toast after a video is added to the playlist and not when page is loaded 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.25(21.4.15.13)

**Device details:** 
iPhone 7+ (iOS 14.4.2)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T @soner-yuksel please move it out of 1.25 if its a low priority issue

**Comment by Brandon-T** [comment]
> Should only show the toast after a video is added to the playlist **and not when page is loaded**

This is incorrect. The toast shows ALWAYS when the page is loaded.
The toast shows on any website that is in the exception list excel sheet.

@srirambv

**Comment by srirambv** [comment]
> The toast shows ALWAYS when the page is loaded.

Even when you open a new tab and visit a page for the first time its expected to show `View in playlist` toast to be shown?

**Comment by Brandon-T** [comment]
> > The toast shows ALWAYS when the page is loaded.
> 
> Even when you open a new tab and visit a page for the first time its expected to show `View in playlist` toast to be shown?

If that page has a video/audio, yes.

**Comment by srirambv** [comment]
@Brandon-T I am unable to reproduce the original issue where the view in playlist is being shown on visiting a media site. Going to close the issue for now and move it out of milestone. If I run into it again then we can reopen the issue.
