### ISSUE TITLE
Browser crash when long press on soundcloud link

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3559]
### Description: 
Browser crash when long press on soundcloud link

### Steps to Reproduce 
  1. Install 1.25
  2. Open `https://soundcloud.com`
  3. Long press on an artist under `Trending tracks on SoundCloud`
  4. Browser crashes

**Actual result:** 
Browser crash when long press on soundcloud link

**Expected result:**
No crash 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.25(21.4.15.13)

**Device details:** 
iPhone 7+ (iOS 14.4.2)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information

**Comment by iccub** [comment]
Me and Brandon can't repro, can you make a recording or get us crash logs for it?

**Comment by iccub** [comment]
From our tests this seem to not be playlist related, I am going to move it to 1.26 milestone

**Comment by kjozwiak** [comment]
Tried it a few times and couldn't reproduce it either using `1.25.1 (21.5.21.22)`. @srirambv if you can easily reproduce, can you grab the crash stack from `Analytics Data` via `Analytics & Improvements`?

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ (iOS 14.8) running 1.32(21.10.6.16)
- Verified no browser crash when long press on a sound cloud link
-------
Verification passed on iPhone XR (iOS 15.0.1) running 1.32(21.10.6.16)
- Verified no browser crash when long press on a sound cloud link
-------
Verification passed on iPad Pro (iOS 15.1 Beta 3) running 1.32(21.10.6.16)
- Verified no browser crash when long press on a sound cloud link
