### ISSUE TITLE
Custom top tiles on iOS in Japan

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3568]
### Description: 

Linked to: https://github.com/brave/security/issues/428

Please update the top tiles for new users on iOS from the standard global ones to the following: 

https://m.youtube.com/
https://m.yahoo.co.jp/
NTP tutorial page (https://brave.com/ja/ntp-tutorial). - Logo needed @jamesmudgett 
https://mobile.twitter.com/

**Comment by anthonypkeane** [comment]
Hi @jamesmudgett or @karenkliu can you please provide an icon for the Japan NTP tutorial page? Thanks

**Comment by iccub** [comment]
What should `NTP tutorial page (https://brave.com/ja/ntp-tutorial).` be named?
For favorites we show users a logo and a title

**Comment by anthonypkeane** [comment]
"Brave Guide"

@soi-tnk can customize this for Japan during translation.

**Comment by karenkliu** [comment]
@anthonypkeane We can use the "Get Started" icon planned for onboarding tasks housed in sidebar: https://www.figma.com/file/xWGBM3qWbu3RLuZqZGwynk/Icons?node-id=706%3A35

![image](https://user-images.githubusercontent.com/2388823/125338150-b0c4e480-e304-11eb-93c3-ff5e1e8090ca.png)

**Comment by anthonypkeane** [comment]
We will actually pull the favicon from the site.

**Comment by anthonypkeane** [comment]
@soi-tnk any preferences on the icon here?

**Comment by iccub** [comment]
custom non-domain icon requires more work on our side btw

**Comment by anthonypkeane** [comment]
It won't be custom

**Comment by soi-tnk** [comment]
@anthonypkeane No special preference for the icon. I can see this default gray brave logo icon when I add the NTP tutorial page to "favorite" manually. This would be good
![IMG_3183](https://user-images.githubusercontent.com/68244357/125539111-b8924417-4725-45c1-88c1-97b6a2f92094.PNG)

**Comment by iccub** [comment]
@soi-tnk can you give me Japanese names for each of those websites? At the moment we do not translate them in transifex,
if you want to leave some of them in English, let me know too

1. https://m.youtube.com/
2. https://m.yahoo.co.jp/
3. https://brave.com/ja/ntp-tutorial
4. https://mobile.twitter.com/

**Comment by soi-tnk** [comment]
@iccub Please use these!

1. YouTube
2. Yahoo!Japan
3. Braveガイド
4. Twitter

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.29(21.07.20.16)
- Verified test plan from #3931 
- Verified new installs have the set of new tiles on NTP
- Verified the tiles are in the order mentioned in https://github.com/brave/brave-ios/issues/3568#issuecomment-881199729
- Verified the the links for individual tile is as per https://github.com/brave/brave-ios/issues/3568#issuecomment-880701765
- Verified on upgrade the tiles are retained from previous install and not updated to the new set

iPhone XR (iOS 13.5) | iPhone 7+ (iOS 14.5.1) | iPad Pro (iOS 14.6)
-- | -- | --
<img width=240 src=https://user-images.githubusercontent.com/17010094/127287797-a53a390d-8b93-487d-b014-83c9f219b508.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/127287843-c47d583a-b2b5-4754-8580-bca7b2fe9478.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/127287871-15491c3e-4727-454f-8f9d-b415cf3879f5.png>
