### ISSUE TITLE
Long press context menu to add to Brave playlist is missing

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3571]
### Description: 
Long press context menu to add to Brave playlist is missing

### Steps to Reproduce 
  1. Open a video 
  2. Long press on the time bar 
  3. No context menu shown to add to playlist

**Actual result:** 
Long press context menu to add to Brave playlist is missing

**Expected result:**
Show context menu to add to playlist

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.25(21.4.21.15)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T

**Comment by Brandon-T** [comment]
This should be fixed in: https://github.com/brave/brave-ios/pull/3560/files
It was an issue with Javascript.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.25(21.4.27.17)
- Verified long press on the video or trying to drag the seek bar brings up context menu to add to Brave playlist

iPhone 7+ (IOS 14.5) | iPhone XR (iOS 13.5) | iPad Pro (iOS 14.4.2)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/116357938-ffc6a780-a7f4-11eb-8f47-72ac6adf1cca.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/116357916-f9383000-a7f4-11eb-9d92-7a6047644d0a.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/116357894-f3dae580-a7f4-11eb-9c30-332b81b3ebeb.png>
