### ISSUE TITLE
Brave password lock is pulling user custom keyboard for inputs. 

### ISSUE THREAD

**Issue by masq31** [brave/brave-ios#3573]
**Description:** 

Brave password lock is pulling user custom keyboard for inputs. 

**Steps to reproduce:**

Enable password lock checkbox.
Require password immediately checkbox.
Navigate to a text box in brave or outside of application. 
Change keyboard schema to custom keyboard.
Navigate back to brave password lock (change app, lock and unlock device, etc.)
Keyboard present for user password will be user’s custom keyboard. 

**Brave version:**

IOS 14.4.2
Hardware - iPhone SE (2020)

**Website problems only**

did you check with Brave Shields down? N/A
did you check in Safari/Firefox (WkWebView-based browsers)? Yes & Present

![IMG_1384](https://user-images.githubusercontent.com/26071188/116006452-5e173e80-a5d9-11eb-9a6a-01149c087b70.PNG)

**Recommendation:**

https://developer.apple.com/documentation/uikit/uitextfield

**Comment by iccub** [comment]
Fixed by moving to biometric authentication
