### ISSUE TITLE
Allow 'Add to playlist' ntp button to be dismissable

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3574]
### Steps to Reproduce 
  1. Open a video, wait for 'Add to playlist' button to show up

**Actual result:** 
Notice that you can't dismiss it, you have to wait until it hides.

**Expected result:**
Should allow user to dismiss it.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.5 running 1.25(21.4.27.17)
- Verified swipe down dismisses the add to playlist toast
----------
Verification passed on iPhone XR with iOS 13.5 running 1.25(21.4.27.17)
- Verified swipe down dismisses the add to playlist toast
-----------
Verification passed on iPad Pro with iOS 14.4.2 running 1.25(21.4.27.17)
- Verified swipe down dismisses the add to playlist toast
