### ISSUE TITLE
Update Startpage icon

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#3584]
### Description: 
We reference Startpage during onboarding and also in our settings. They have provided us with a new icon

**Actual result:** 
![image](https://user-images.githubusercontent.com/4733304/116280676-cbdc7b00-a73d-11eb-9ec9-c09acf4e89ce.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/4733304/116280624-ba936e80-a73d-11eb-88f7-beb3b5b065a3.png)

### Additional Information
Updated images per @jamesmudgett 
[startpage.zip](https://github.com/brave/brave-ios/files/6386236/startpage.zip)

**Comment by jamesmudgett** [comment]
[startpage.zip](https://github.com/brave/brave-ios/files/6386961/startpage.zip)

**Comment by iccub** [comment]
That's a big icon

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(21.5.13.16)
- Verified Startpage icon is updated on onboarding/Quick Search button and Search settings

Onboarding | Quick Search button | Search Engine list
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/118610136-5bac9c80-b7b3-11eb-9a84-f784832aa4f7.png) | ![image](https://user-images.githubusercontent.com/17010094/118610149-5f402380-b7b3-11eb-8246-d72a03cf8e5c.png) | ![image](https://user-images.githubusercontent.com/17010094/118610164-62d3aa80-b7b3-11eb-878a-4e2707308512.png)

----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.26(21.5.13.16)
- Verified Startpage icon is updated on onboarding/Quick Search button and Search settings

Onboarding | Quick Search button | Search Engine list
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/118610285-839c0000-b7b3-11eb-9ca5-efbec179e3ff.png) | ![image](https://user-images.githubusercontent.com/17010094/118610307-8a2a7780-b7b3-11eb-8d20-dcb3734c3c78.png) | ![image](https://user-images.githubusercontent.com/17010094/118610328-8e569500-b7b3-11eb-8ed1-80fee60bb769.png)

-----------
Verification passed on iPad Pro with iOS 14.5.1 running 1.26(21.5.13.16)
- Verified Startpage icon is updated on onboarding/Quick Search button and Search settings

Onboarding | Quick Search button | Search Engine list
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/118610529-c067f700-b7b3-11eb-91e8-3d7374ca9f9f.png) | ![image](https://user-images.githubusercontent.com/17010094/118610676-ee4d3b80-b7b3-11eb-8ec9-6042a4a119fe.png) | ![image](https://user-images.githubusercontent.com/17010094/118610693-f1482c00-b7b3-11eb-8b1f-fdd02ab3230e.png)
