### ISSUE TITLE
Clear playlist cache fails sometimes

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3585]
### Steps to Reproduce 
  1. Add few videos
  2. Go to playlist settings
  3. Try to clear cache

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Hard to reproduce

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.5 running 1.25(21.4.28.19)
- Verified no crash when clearing data for playlist
--------
Verification passed on iPhone XR with iOS 13.5 running 1.25(21.4.28.19)
- Verified no crash when clearing data for playlist
-------
Verification passed on iPad Pro with iOS 14.4.2 running 1.25(21.4.28.19)
- Verified no crash when clearing data for playlist
