### ISSUE TITLE
[Playlist] - Crash when deleting cache via Privacy Settings

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#3586]
### Description: 
Playlist crashes when deleting cache via the privacy settings

### Steps to Reproduce 
  1. Go to Shields Privacy
  2. Enable both playlist options
  3. Clear Data Now
  4. Experience Crash

**Actual result:** 
Crashes

**Expected result:**
Shouldn't Crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent Issue.

**Comment by iccub** [comment]
duplicate of https://github.com/brave/brave-ios/issues/3586
