### ISSUE TITLE
When fingerprinting is enabled, embedded videos don't play

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3590]
### Description: 

When fingerprinting is enabled, embedded videos don't play

### Steps to Reproduce 
  1. Navigate to https://brave-cm.jp/iecokechallenge/. (with fingerprinting off)
  2. Play the video
  3. Enable fingerprinting in settings
 

**Actual result:** 
Video stops playing

**Expected result:**
Video should play

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Device details:** 
iOS14.5

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

cc @pes10k

**Comment by cuba** [comment]
@anthonypkeane This URL no longer works. Could you provide some details so we can test this and potentially close this ticket?
