### ISSUE TITLE
rewards not being disabled when toggling off via rewards panel

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3591]
### Description: 

There's a pretty bad bug/state where toggling/disabling rewards doesn't actually disable the feature/rewards. The toggle will slide to the disabled position, but rewards won't be disabled. It takes several attempts of disabling/enabling to get it disabled. However, even when you disable it, sometimes restarting the browser will re-enable it again. I've ran into pretty often/easily when running through https://github.com/brave/brave-ios/issues/3410. Reproduced it on the current version that's available in the AppStore as well.

### Steps to Reproduce
 
  1. launch the latest version of `1.25.x` via TF
  2. skip through all the onboarding modals/windows
  3. enable rewards and wait a few seconds
  4. restart the browser and try disabling rewards

If the above case doesn't work, just keep enabling/disabling rewards. You'll eventually get into the above state.

**Actual result:** 

Example of the issue occurring ---> https://youtu.be/SyuP_7Fc__M

**Expected result:**

Rewards shouldn't be that difficult to disable and should work every single time it's toggled

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Pretty easy to reproduce. I can basically do it 100% of the time running through the above STR.

**Brave Version:** 

* `1.24 (21.4.1.15)` - **Reproduced**
* `1.25 (21.4.27.17)` - **Reproduced**

**Device details:** 

* `iPhone 11` running `iOS 14.4.2` - **Reproduced**
* `iPad Mini 4` running `iOS 13.7` - **Reproduced**
* `iPad Air (3rd Gen)` running `iOS 14.4.2` - **Reproduced**

**Website problems only:** `N/A`
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @kylehickinson @anthonypkeane @bsclifton @srirambv

**Comment by kjozwiak** [comment]
Even though this is in `1.24`, probably a good idea to get this fixed in `1.25`. I don't think we've received any reports but users should be able to disable rewards on the first try without any issues.

**Comment by kylehickinson** [comment]
@kjozwiak Investigating this has led me to believe this is a bug on the `brave-core` side of things (likely something in the iOS ads wrapper code) so I don't think a 1.25 fix is realistic

**Comment by kylehickinson** [comment]
This is currently blocked on some changes that are included in #3227

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.30(21.8.5.11)
- Verified steps from issue description
-----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.30(21.8.5.11)
- Verified steps from issue description
-----------
Verification passed on iPad Pro with iOS 14.6 running 1.30(21.8.5.11)
- Verified steps from issue description
