### ISSUE TITLE
legacy grant transfer UI being displayed quickly before the normal panel loads

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3592]
### Description: 

On my `iPad Mini 4` which is a bit slower compared to the other devices, I get the legacy grant transfer UI appearing quickly before the normal rewards panel loads even though it's a new profile without any grants being available.

### Steps to Reproduce

  1. install the latest `1.25` from TF (used `1.25 (21.4.27.17)` in this case)
  2. skip all the onboarding and quickly hit the rewards panel
  3. you'll notice that the legacy grant transfer UI will be visible for a second or so before the normal panel loads

**Actual result:** 

Example of the issue occurring --> https://youtu.be/ArxgZAfRARU

**Expected result:**

The legacy grant transfer UI should be appearing on a new profile/install.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible on my `iPad Mini 4` device running `iOS 13`

**Brave Version:** 

* `1.24 (21.4.1.15)` - **Couldn't reproduce**
* `1.25 (21.4.27.17)` - **Reproduced**

**Device details:** 

* `iPad Mini 4` running `iOS 13.7` - **Reproduced**

**Website problems only:** `N/A`
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @bsclifton @anthonypkeane @kylehickinson @srirambv

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.25(21.4.28.19)
- Verified steps from issue description

https://user-images.githubusercontent.com/17010094/116563392-e52b2600-a8fb-11eb-9c59-7d05a7dc5e9d.MP4

------------
Verification passed on iPhone 7+ with iOS 14.5 running 1.25(21.4.28.19)
- Verified steps from issue description

https://user-images.githubusercontent.com/17010094/116563782-43580900-a8fc-11eb-8306-60f5ceca3ef7.MP4


---------
Verification passed on iPad Pro with iOS 14.4.2 running 1.25(21.4.28.19)
- Verified steps from issue description

https://user-images.githubusercontent.com/17010094/116564018-80bc9680-a8fc-11eb-8881-5c30d0089ea3.MP4
