### ISSUE TITLE
iOS - remove PIN entry from Keychain on fresh install

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#3598]
### Description: 
There is a situation that users can get into where they can forget their PIN. On iOS, there isn't a way to go and edit the keychain so after uninstalling/reinstalling they'll get hit with the same code and can't open Brave

### Steps to Reproduce 
  1. Install Brave
  2. Setup a PIN code 
  3. Forget what PIN code is
  4. Uninstall Brave
  5. Reinstall Brave

**Actual result:** 
User is met with PIN again ☹️ See for more info:
https://community.brave.com/t/forgot-brave-ios-app-passcode/236334

**Expected result:**
Removing/reinstalling should clear the keychain entry and allow Brave to be used again

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(21.5.26.21)
- Verified test plan from https://github.com/brave/brave-ios/pull/3619
- Verified no pin prompt when app is uninstalled and reinstalled
----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.26(21.5.26.21)
- Verified test plan from https://github.com/brave/brave-ios/pull/3619
- Verified no pin prompt when app is uninstalled and reinstalled
-----------
Verification passed on iPad Pro with iOS 14.5.1 running 1.26(21.5.26.21)
- Verified test plan from https://github.com/brave/brave-ios/pull/3619
- Verified no pin prompt when app is uninstalled and reinstalled
