### ISSUE TITLE
Playlist UX change for "Add to Brave Playlist"

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3599]
### Description: 
Link: https://bravesoftware.slack.com/archives/CKJCXTP9B/p1619632564224700

After a users adds a video to Playlist using toast, pressing the open button should take a user to the current video and starting play(no additional taps needed).

Bonus: If we could take it a step further — have it resume playing where the playback cursor is currently. If I’m 5min in then add to playlist and open, it should resume at 5 minutes mark

**Comment by iccub** [comment]
Closing in favor of https://github.com/brave/brave-ios/issues/3976
