### ISSUE TITLE
Feature Migration

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#36]
General ticket as validation of item completion below:

## Porting existing code:

- [x] Tab bar
- [x] Bookmarks
- [ ] Password managers
- [x] Search engines
- [x] Cookie controls
- [ ] URP
- [x] Favorites

## Blending features:
- [x] Pincode
- [x] Readermode
- [ ] Saved logins
- [ ] Private mode
- [ ] ShareTo (“open in...”)

**Comment by kylehickinson** [comment]
Closing this issue after creating individual tickets for remaining tasks. (#162, #163, #164)
