### ISSUE TITLE
Copy change on Error Interstitial Page

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#361]
As mentioned during discussion around #268. This is a short-term solution to just modify copy. Rebrand page away from Firefox and relabel with Brave. Should be a word change.

A simple stopgap for: https://github.com/brave/brave-ios/issues/317

**Comment by kylehickinson** [comment]
This is already fixed in #268 (see https://github.com/brave/brave-ios/commit/c949645e7fc0e948b8bce6387d2b7f33ee18bd04)
