### ISSUE TITLE
Playlist :: Moving a video forward shouldn’t make the toast appear.

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3616]
### Description: 
Moving a video forward shouldn’t make the toast appear.

![File](https://user-images.githubusercontent.com/7606853/116910585-adbdc180-abfa-11eb-8257-e5094ae9d5f7.jpg)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.25.1(21.5.21,22)
- Verified steps from issue description
- Verified seeking a video to a specific position doesn't bring up the Add to playlist context modal
- Verified context menu modal for playlist only shows up when long press on the video or on the seek bar
- Verified on both normal and private tabs
----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.25.1(21.5.21,22)
- Verified steps from issue description
- Verified seeking a video to a specific position doesn't bring up the Add to playlist context modal
- Verified context menu modal for playlist only shows up when long press on the video or on the seek bar
- Verified on both normal and private tabs
----------
Verification passed on iPad Pro with iOS 14.5.1 running 1.25.1(21.5.21,22)
- Verified steps from issue description
- Verified seeking a video to a specific position doesn't bring up the Add to playlist context modal
- Verified context menu modal for playlist only shows up when long press on the video or on the seek bar
- Verified on both normal and private tabs
