### ISSUE TITLE
Private Tabs should be removed when user leaves private mode

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#362]
At the moment private tabs remain in memory even if a user goes back to regular mode.

**Comment by tildelowengrimm** [comment]
What attack vector leads to disclosure after the tabs are unavailable in-app?

**Comment by kylehickinson** [comment]
The current functionality in 1.6 is that once you leave private mode all tabs are removed from memory. Just making sure to follow-suit.

Edit: Perhaps the security label isn't appropriate for this ticket then
