### ISSUE TITLE
[hackerone] RSS feed URL schemes

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3630]
reported at https://hackerone.com/reports/1184379

## Test Plan

https://github.com/brave/internal/issues/772

**Comment by srirambv** [comment]
QA Blocked on https://github.com/brave/internal/issues/772#issuecomment-848642926

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(21.5.25.18)
- Verified test plan from brave/internal#772
-----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.26(21.5.25.18)
- Verified test plan from brave/internal#772
-----------
Verification passed on iPad Pro with iOS 14.5.1 running 1.26(21.5.25.18)
- Verified test plan from brave/internal#772
