### ISSUE TITLE
Update adblock-rust dependency

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3631]

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(21.5.25.17)
- Verified adblock stats work correctly and updates on NTP stats
- Verified using block-ads.json: 7450rules with etag:`aa730c9`
-------------
Verification passed on iPhone 7+  with iOS 14.5.1 running 1.26(21.5.25.17)
- Verified adblock stats work correctly and updates on NTP stats
- Verified using block-ads.json: 7450rules with etag:`aa730c9`
------------
Verification passed on iPad Pro with iOS 14.5.1 running 1.26(21.5.25.17)
- Verified adblock stats work correctly and updates on NTP stats
- Verified using block-ads.json: 7450rules with etag:`aa730c9`
