### ISSUE TITLE
Modernize theme application logic and introduce design system colors

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3632]
Replace the `Themable` API with `UITraitCollection` related APIs to have more stable theming code and replace Firefox/legacy color palette colors with design system colors

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(21.5.26.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3606
- Verified themes are updated as per new scheme
-----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.26(21.5.26.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3606
- Verified themes are updated as per new scheme
-----------
Verification passed on iPad Pro with iOS 14.5.1 running 1.26(21.5.26.18)
- Verified test plan from https://github.com/brave/brave-ios/pull/3606
- Verified themes are updated as per new scheme
