### ISSUE TITLE
Make 'remove from playlist' button destructive.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3640]
<img width="279" alt="Zrzut ekranu 2021-05-6 o 17 23 55" src="https://user-images.githubusercontent.com/6950387/117324168-d7434b00-ae8f-11eb-8649-90a31feae3ed.png">

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.27(21.6.10.21)
- Verified test plan from https://github.com/brave/brave-ios/pull/3680

iPhone XR (iOS 13.5) | iPhone 7+ (iOS 14.5.1) | iPad Pro (iOS 14.6)
-- | -- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/121684599-ce5d1f00-cab6-11eb-82b9-8bcf112dd0ca.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/121684623-d6b55a00-cab6-11eb-8988-74083136eeae.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/121684640-dcab3b00-cab6-11eb-9fec-8a70ce209d0c.png>
