### ISSUE TITLE
Update user agent to 14.6

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3647]

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.27(21.6.10.21)

<details>
<summary>Verified test plan from #3724</summary>


Brave Mobile UA | Safari Mobile UA
-- | --
![image](https://user-images.githubusercontent.com/17010094/122065880-3038c400-cdea-11eb-8e80-7eeb8cb95aac.png) | ![image](https://user-images.githubusercontent.com/17010094/122065921-3890ff00-cdea-11eb-87ae-3933f5076380.png)

Brave Desktop UA | Safari Desktop UA
-- | --
![image](https://user-images.githubusercontent.com/17010094/122065904-34fd7800-cdea-11eb-8085-b0d85c77aabb.png) | ![image](https://user-images.githubusercontent.com/17010094/122065938-3c248600-cdea-11eb-9749-8b7510b51eea.png)

</details>

------------

Verification passed on iPhone 7+ with iOS 14.5.1 running 1.27(21.6.10.21)

<details>
<summary>Verified test plan from #3724</summary>


Brave Mobile UA | Safari Mobile UA
-- | --
![image](https://user-images.githubusercontent.com/17010094/122065972-45155780-cdea-11eb-877b-aa3436dd6e28.png) | ![image](https://user-images.githubusercontent.com/17010094/122066020-4cd4fc00-cdea-11eb-8b91-90d255a9f746.png)

Brave Desktop UA | Safari Desktop UA
-- | --
![image](https://user-images.githubusercontent.com/17010094/122065996-48a8de80-cdea-11eb-9718-7e9bd6cda3f2.png) | ![image](https://user-images.githubusercontent.com/17010094/122066038-4fcfec80-cdea-11eb-8532-d8ed38fe1ce6.png)

</details>

------------
Verification passed on iPad Pro with iOS 14.6 running 1.27(21.6.10.21)

<details>
<summary>Verified test plan from #3724</summary>


Brave Mobile UA | Safari Mobile UA
-- | --
![image](https://user-images.githubusercontent.com/17010094/122066363-99203c00-cdea-11eb-888f-8aff3a2e7d78.png) | ![image](https://user-images.githubusercontent.com/17010094/122066404-a0474a00-cdea-11eb-9424-b99c9ba13bed.png)

Brave Desktop UA | Safari Desktop UA
-- | --
![image](https://user-images.githubusercontent.com/17010094/122066338-945b8800-cdea-11eb-8f44-d2a3f78f3a37.png) | ![image](https://user-images.githubusercontent.com/17010094/122066440-a63d2b00-cdea-11eb-92d7-012b69d07505.png)


</details>
