### ISSUE TITLE
Playlist loses position of current video when you leave/come back

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#3650]
### Description: 
Playlist not keeping track of position of video playing after exiting

### Steps to Reproduce 
  1. Be on the Playlist UI playing a video
  2. Swipe up to switch apps
  3. Return to Brave
  4. Open Playlists

**Actual result:** 
Video starts over from beginning

**Expected result:**
Video should remember the position

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
1.25

**Comment by BrendanEich** [comment]
This is something I'd love to see fixed, and I'm hearing from others who are keen. Prospects? Need help with STR?

**Comment by darkdh** [comment]
I can reproduce this without switching apps
https://user-images.githubusercontent.com/11330831/118205311-e5a3e080-b414-11eb-9355-90a406b0ee28.MP4

**Comment by stephendonner** [comment]
**Verified `PASSED`** using Brave `1.27 (21.6.16.15)` on iPhone 6s, iOS 14.4.2

**Steps:**
1. queued up `https://www.youtube.com/watch?v=dQw4w9WgXcQ` in Playlist
2. tapped on it to start playing the video
3. dragged/tapped (not shown in screencast, but I tested) the slider to seek to another position
4. tapped `Done` at the top right
5. tapped the 3-dots menu on the bottom-right toolbar
6. tapped `Playlist`
7. tapped the `|>` button
8. confirmed the video's position in Playlist returned to that from step 3
9. repeated this a few times

https://user-images.githubusercontent.com/387249/122267971-5b75ee80-ce90-11eb-83eb-de30b778bb00.MP4

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.27(21.6.17.10)
- Verified video restart from where its left off when video is paused and playlist is closed
- Verified video resumes from where it left off even when browser is removed from memory and restarted
- Verified steps from https://github.com/brave/brave-ios/issues/3650#issuecomment-840923852
-----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.27(21.6.17.10)
- Verified video restart from where its left off when video is paused and playlist is closed
- Verified video resumes from where it left off even when browser is removed from memory and restarted
- Verified steps from https://github.com/brave/brave-ios/issues/3650#issuecomment-840923852
------------
Verification passed on iPad Pro with iOS 14.6 running 1.27(21.6.17.10)
- Verified video restart from where its left off when video is paused and playlist is closed
- Verified video resumes from where it left off even when browser is removed from memory and restarted
- Verified steps from https://github.com/brave/brave-ios/issues/3650#issuecomment-840923852
