### ISSUE TITLE
Minor typos in Playlist's Auto-Save for Offline text in Settings

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#3653]
### Description: 
Minor typos in Playlist's Auto-Save for Offline text in Settings

### Steps to Reproduce 

1. launch Brave Beta, Dev, or Nightly
2. tap the 3-dots menu ... on the bottom-right toolbar
3. tap Settings
4. tap Playlist
5. read the `Auto-Save for Offline` section

**Actual result:** 

`... so you can play them while you dont have the internet connection`

![Image from iOS](https://user-images.githubusercontent.com/387249/117529451-7ea5a800-af8c-11eb-9d2e-27fc0fc88e0b.png)

**Expected result:**

`... so you can play them while without internet`, or something similar

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
Brave 1.25 (21.4.30.20)

**Device details:** 
iPhone 8 Plus, iOS 14.6 (18F5055b)

/cc @karenkliu and @srirambv

**Comment by karenkliu** [comment]
Let's use:
>...so you can play them without an internet connection.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.26(21.5.25.18)
- Verified text is updated to as per https://github.com/brave/brave-ios/issues/3653#issuecomment-836952628

iPhone XR (iOS 13.5) | iPhone 7+ (iOS 14.5.1) | iPad Pro (iOS 14.5.1)
-- | -- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/119644903-597eb980-be15-11eb-9027-6b4e1fa65c27.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/119644997-74e9c480-be15-11eb-9256-e4780cb93793.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/119645282-c85c1280-be15-11eb-8da4-a5ad60fb4629.png>
