### ISSUE TITLE
Only Wifi should read Only Wi-Fi in Playlist's Auto-Save for Offline section in Settings

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#3654]
### Description: 
Only Wifi should read Only Wi-Fi in Playlist's Auto-Save for Offline section in Settings

### Steps to Reproduce 

1. launch Brave Beta, Dev, or Nightly
2. tap the 3-dots menu ... on the bottom-right toolbar
3. tap Settings
4. tap Playlist
5. tap Auto-Save for Offline
6. read the pref options

**Actual result:** 

The last option reads `Only Wifi`

![Image from iOS 2](https://user-images.githubusercontent.com/387249/117529629-67b38580-af8d-11eb-88a5-c3f2099ec343.png)

**Expected result:**

It should read `Only Wi-Fi` per `https://www.wi-fi.org/`

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 

Brave 1.25 (21.4.30.20)

Device details:
iPhone 8 Plus, iOS 14.6 (18F5055b)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.26(21.5.25.18)
- Verified text reads as `Only Wi-Fi`

iPhone XR (iOS 13.5) | iPhone 7+ (iOS 14.5.1) | iPad Pro (iOS 14.5.1)
-- | -- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/119645685-3274b780-be16-11eb-8e4e-e9601cd692b2.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/119645717-3d2f4c80-be16-11eb-95fb-e1089914aa2b.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/119645750-47e9e180-be16-11eb-9adc-02fed432e32f.png>
