### ISSUE TITLE
Brave Playlist pop-up on YouTube - Even with feature disabled

### ISSUE THREAD

**Issue by sohnemann** [brave/brave-ios#3656]
### Description: 
When browsing YouTube with Brave on iOS,
the pop-up 'Add to Brave Playlist' shows up when restarting a video at '0:00'
even though the playlist feature has been completely disabled in settings.

It seems to happen every time the slider is used to scrub through the video which makes scrubbing to a specific spot in a video pretty close to impossible!

### Steps to Reproduce 
  1. Browse to any YouTube video
  2. Drag the playback slider back to '0:00'
  3. The pop-up shows up

**Actual result:**
![A0792A5F-DDCD-4631-AE4D-32888F17067F](https://user-images.githubusercontent.com/50672942/117553978-e3562500-b0a8-11eb-9ff6-e6669117fb2f.png)
![FB75295F-E7A1-4767-9C04-E681AC8C7B83](https://user-images.githubusercontent.com/50672942/117553983-e81ad900-b0a8-11eb-9d28-9c5d0c855b24.png)

**Expected result:**
If the playlist feature has been completely disabled, there should be no pop-up.

**Reproduces how often:**
Every time the slider is set back to 0:00.

**Brave Version:** 
Version 1.25 (21.5.4.19)

**Device details:**
iPhone 7 (iOS 14.5.1)

**Website problems only:**
Seems to only happen when on YouTube.
Dailymotion and Metacafe do not provoke this behaviour.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.25.1(21.5.21,22)
- Verified steps from issue description
- Verified seeking a video to a specific position doesn't bring up the Add to playlist context modal
- Verified context menu modal for playlist only shows up when long press on the video or on the seek bar
- Verified on both normal and private tabs
----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.25.1(21.5.21,22)
- Verified steps from issue description
- Verified seeking a video to a specific position doesn't bring up the Add to playlist context modal
- Verified context menu modal for playlist only shows up when long press on the video or on the seek bar
- Verified on both normal and private tabs
----------
Verification passed on iPad Pro with iOS 14.5.1 running 1.25.1(21.5.21,22)
- Verified steps from issue description
- Verified seeking a video to a specific position doesn't bring up the Add to playlist context modal
- Verified context menu modal for playlist only shows up when long press on the video or on the seek bar
- Verified on both normal and private tabs
