### ISSUE TITLE
Option to export or import bookmarks missing

### ISSUE THREAD

**Issue by 8thHalfHour** [brave/brave-ios#3657]
### Description: 

Brave Beta on iOS appears to be missing the import and export feature on iOS described in the Brave article [How do I Import or Export Bookmarks on iOS?](https://support.brave.com/hc/en-us/articles/360057082371-How-do-I-Import-or-Export-Bookmarks-on-iOS-).

### Steps to Reproduce 
 
Follow the instructions on in that article to open the Bookmark Manager and find the **Share** button in the lower left of the panel.

**Actual result:** 

No such icon/button exists.

**Expected result:**

Icon/button exists, as shown in the How-to article.

**Reproduces how often:**

Always.

**Brave Version:** v1.25 (21.4.30.20)

**Device details:** iPad Air 2, iPadOS v14.4.2 (18D70)

### Additional Information

N/A

**Comment by iccub** [comment]
You have to be at root bookmark folder, when in bookmarks screen, try to navigate back until you see `Mobile Bookmarks` folder

let me know if that helped

**Comment by 8thHalfHour** [comment]
That worked 100%! Thank you. Please add that note to the documentation when you get a chance. It ended up being confusing because when entering the **Bookmark Manager**, the app defaults to the last location the user selected a bookmark from or saved a bookmark to. This is often not the root folder.

**Comment by iccub** [comment]
passed your feedback to our user support team, thanks for noticing it :) we will update our article
