### ISSUE TITLE
Settings - Text Polish

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3661]
### Description: 

Please update the Shield settings to Title Case

Block Cross-Site Trackers
Upgrade Connection to HTTPS
Block Fingerprinting

And add . after all sentences under the title setting

![Image from iOS](https://user-images.githubusercontent.com/7606853/117707922-043f7880-b184-11eb-9cde-640cecc5039f.png)

**Comment by rmcfadden3** [comment]
@anthonypkeane — Seems like you already have a specific list of what you want fixed: title casing and punctuation. Is this something you still need my help on? If yes, can you DM me on Slack to discuss?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.32(21.10.6.16)
- Verified setting is changed to sentence casing

iPhone 7+ (iOS 14.8) | iPhone XR (iOS 15.0.1) | iPad Pro (iOS 15.1 Beta 3)
-- | -- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/136548122-0121cb39-6198-41d2-8e41-1d9dfa43be68.png> | <img width=240 src=https://user-images.githubusercontent.com/17010094/136548211-5be03e11-a9d1-46ef-a07c-7323d89c7113.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/136548002-3b4eb79f-941d-4d57-8c28-9983c7503595.png>
