### ISSUE TITLE
Add to Brave Playlist toast is not showing on Odysee.com 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3663]
### Description: 

The Add to Brave Playlist toast is not showing on Odysee.com 

https://appfigures.com/reviews/42132121512Lcw18cRqqDGvoNUIwiSsiiQ?lang=en

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.26(21.5.25.18)
- Verified `Add to Brave Playlist` toast is shown on Odysee.com
- Encountered #3727 on iPhone

iPhone XR (iOS 13.5) | iPhone 7+ (iOS 14.5.1) | iPad Pro (iOS 14.5.1)
-- | -- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/119669016-95bf1380-be2f-11eb-886b-0e149f79251b.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/119669064-a1aad580-be2f-11eb-8ffd-98054b773560.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/119669223-cdc65680-be2f-11eb-9823-fa0d738cf34b.png>
