### ISSUE TITLE
Add to playlist option freezes on 3aw.com

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3665]
### Description: 
Reported here

### Steps to Reproduce 
  1. Go to https://www.3aw.com.au/brett-ratten-responds-to-max-king-critics/
  2. Scroll down to audio player, play it

**Actual result:** 
Notice it freezed the app for few seconds

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Update, i can reproduce the crash on dev build only,
it doesn't crash on live app for me, changing the title

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.25.1(21.5.21.22)
- Verified test plan from issue description
- Verified test plan from https://github.com/brave/brave-ios/pull/3690
----------
+Verification passed on iPhone 7+ with iOS 14.5.1 running 1.25.1(21.5.21.22)
- Verified test plan from issue description
- Verified test plan from https://github.com/brave/brave-ios/pull/3690
----------
Verification passed on iPad Pro with iOS 14.5.1running 1.25.1(21.5.21.22)
- Verified test plan from issue description
- Verified test plan from https://github.com/brave/brave-ios/pull/3690
