### ISSUE TITLE
Brave on iOS - rebase from Firefox to Chromium and closing gaps to desktop experience

### ISSUE THREAD

**Issue by phoogm** [brave/brave-ios#3666]
### Description: 
As a user i would like to see parity between the Desktop and Mobile experience in terms of UI and capabilities (as far as applicable and possible for Mobile and supported by iOS). Also using the same codebase (except for WebKit) would reduce the development effort by not having to maintain completely different codebases for Desktop and Mobile.

### Steps to Reproduce 
  1. Open Brave desktop
  2. Open Brave for iOS
  3. Compare design of tabs and location of controls, Brave stats and Top Sites layout and location.

**Actual result:** 
![Brave browser](https://user-images.githubusercontent.com/56597375/117813650-9e2a2280-b263-11eb-8574-dbf749f44f36.png)

**Expected result:**
Starting point was Edge for iOS beta on Chromium, reworked the icons, added NTP widgets, full NTP panel wallpaper and added a bookmarks bar like present in Safari for iOS.

<img width="1420" alt="Brave chromium rebase" src="https://user-images.githubusercontent.com/56597375/117816570-f0b90e00-b266-11eb-9f67-45ebb0da5a11.png">

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.24 (21.4.1.15)

**Device details:** 
iPad Pro (iPadOS 14.5.1)

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information
Thanks for considering, best regards.

**Comment by kylehickinson** [comment]
Hi @phoogm, the Brave iOS team has already gone down this road of determining if a re-fork using Chromium would be the best direction but it isn't that simple and we came to the conclusion to continue working from the current codebase. 

We can still strive to achieve parity with desktop features as best as we can given our limitation of using WebKit and work to improve the browser & iPad experience—which we already have open issues for (bookmarks bar is one of them: #3392)

If you have other requests regarding desktop parity please feel free to open up issues for them if they don't already exist 🙂
