### ISSUE TITLE
Allow user to disable 'long press to add media to playlist'

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3670]
We have to implement new settings in playlist screen.

Setting name `Enable Long Press`
Footer `When enabled, you can long-press on most video/audio files to add them to your Playlist.`

This ticket will also change `Add to playlist toast footer`
to `When enabled, a bar will automatically show on most media websites making it easier to add those video/audio files to your Playlist.`

This setting should be enabled by default.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(21.5.26.21)
- Verified new settings to disable long press is available and enabled by default 
- Verified when enabled able to long press on audio/video to add to playlist
- Verified when disabled long press add to playlist options is not shown
- Verified when disabled seeking video doesn't bring the add to video context menu
----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.26(21.5.26.21)
- Verified new settings to disable long press is available and enabled by default 
- Verified when enabled able to long press on audio/video to add to playlist
- Verified when disabled long press add to playlist options is not shown
- Verified when disabled seeking video doesn't bring the add to video context menu
-----------
Verification passed on iPad Pro with iOS 14.5.1 running 1.26(21.5.26.21)
- Verified new settings to disable long press is available and enabled by default 
- Verified when enabled able to long press on audio/video to add to playlist
- Verified when disabled long press add to playlist options is not shown
- Verified when disabled seeking video doesn't bring the add to video context menu

iPhone XR (iOS 13.5) | iPhone 7+ (iOS 14.5.1) | iPad Pro (iOS 14.5.1)
-- | -- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/119783064-c309d100-bec4-11eb-9c20-152be7cf98cb.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/119783104-cc933900-bec4-11eb-96e5-fcc07af0e2a4.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/119781964-85f10f00-bec3-11eb-9d9a-a7bf9671359f.png>
