### ISSUE TITLE
Add support for Carplay 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3673]
### Description: 
In Playlist, please add support for Carplay

**Comment by srirambv** [comment]
<details>
<summary>Verification passed on iPhone 7+ (iOS 14.8) and iPhone XR (iOS 15.0.1) running 1.32.1(21.10.20.18) </summary>
<br>

- Verified Brave shows up as an app when the device is connected to CarPlay using USB cable
![image](https://user-images.githubusercontent.com/17010094/138258974-a4be7d4d-830d-422c-924e-9e9b10f87a04.png)
- Verified clicking on Brave opens up the Playlist by default
- Verified when if playlist is empty then shows message about no items available
- Verified when playlist has items lists the playlist items in the same order 

![image](https://user-images.githubusercontent.com/17010094/138259683-5fa4e542-039a-4350-a070-a5079754636e.png) | ![image](https://user-images.githubusercontent.com/17010094/138259786-686ccaf1-b717-4d20-8386-ff2245371f63.png)
-- | --

- Verified settings shows option for restarting playlist item when selected which is disabled by default
- Verified enabling the setting causes the track to start from beginning when selected from the playlist or if the same track is playing

![image](https://user-images.githubusercontent.com/17010094/138264298-27b77814-a18b-474c-b4e8-9dadc4ced40f.png) | ![image](https://user-images.githubusercontent.com/17010094/138259976-c78a92a9-d3c9-42f1-9d16-8053bf97373e.png) | ![image](https://user-images.githubusercontent.com/17010094/138260004-3b3d73b3-fac9-4151-af7e-9c5894409ad4.png)
-- | -- | --

- Verified when a track is playing it shows the playing indicator on the track and on the top right corner
![image](https://user-images.githubusercontent.com/17010094/138260149-d6484279-222f-460b-9f40-62fa2b0447ce.png)
- Verified clicking on the playing indicator on the top right opens up the now playing track
![image](https://user-images.githubusercontent.com/17010094/138260238-62b32417-9b67-4ac8-9f6a-7b7e488a7bf0.png)

- Verified when a playlist item is being played and the device is removed the current playing track stops on the device as well
- Verified after connecting to CarPlay, playing a track on playlist and disconnect the device and reconnecting automatically starts the playback from where it left off
- Encountered #4383 when trying to playback after reconnecting device
- Verified when an item is still downloading or not has been removed from offline playback shows a cloud icon next to the track 
![image](https://user-images.githubusercontent.com/17010094/138264555-13f02d0a-1628-4be3-ab60-c8389a44dd73.png)
- Verified playlist pauses when there is an incoming call. Encountered #4362
- Verified while playing from playlist via CarPlay, using voice command for Siri pauses the carplay
- Verified while playing from playlist via CarPlay, notifications from Apps can be read out loud
- Verified while playing from playlist via CarPlay, able to use browser for other functions
- Verified while playing from playlist via CarPlay, can use maps for navigation and navigation commands can be heard over the track that is currently playing
- Verified when a track finishes and the next one starts, automatically view changes from playlist to now playing
- Verified tracks follow the track speed set in playlist

</details>

<details>
<summary>Verification PASSED on iPhone 12 running iOS 15.0.2 using 1.32.1 (21.10.28.15)</summary>
<br>

* ensured that Brave appears as an available application when connnected to `CarPlay` via `Bluetooth`
* ensured that tapping on the Brave icon opens the `Playlist` by default
* ensured that a `No Items Available` is displayed for on installs or if someone doesn't have anything added within the `Playlist`

**`CarPlay Home`** | **`Default/Clean Install`** | **`Playlist Items Added`**
-------------------|-----------------------------|----------------------------
![IMG_9662](https://user-images.githubusercontent.com/2602313/139377493-bca20c53-fb24-4485-ba2a-5ab19a9dc5a4.png) | ![IMG_9664](https://user-images.githubusercontent.com/2602313/139377509-27193ca8-d3bf-46b6-8ffe-918acf9890bd.png) | ![IMG_9670](https://user-images.githubusercontent.com/2602313/139377608-e0d67b05-afc1-4a10-8eb5-f15615e69b05.png)

* ensured that media is still playing when clicking on `Home` via `CarPlay`
* ensured that the current media that's being played is displayed in the `Home` screen via `CarPlay`
* ensured that the controls work as expected via the `Home` screen on `CarPlay` (Back/Forwards & Pause)
* ensured that clicking on the media panel under the `Home` screen via `CarPlay` opens the Brave application

**`CarPlay Home Screen`** | **`Clicking on Media Panel via CarPlay`**
------------------------------|---------------------------------------------
![IMG_9674](https://user-images.githubusercontent.com/2602313/139378832-4f9a5f02-ce46-4d25-8c21-bf7e68b595c4.png) | ![IMG_9680](https://user-images.githubusercontent.com/2602313/139378984-2be48052-b33f-4e39-b216-8047ee6dc64a.PNG)

* ensured that receiving notifications from other applications doesn't interrupt the current media being played
* ensured that the notification is being displayed without any issue in various areas (Brave/CarPlay Home)
* ensured that tapping on the notification opens the corresponding application within CarPlay without issues

**`Notification via Brave Playlist`** | **`Notification via Brave Playlist`** 
---------------------------------------|--------------------------------------
![IMG_9684](https://user-images.githubusercontent.com/2602313/139379758-ddcd47d5-955b-4e4f-876a-9014b3a1f553.png) | ![IMG_9682](https://user-images.githubusercontent.com/2602313/139379777-29b0e8f6-4748-4d8b-953a-140337be266e.png)

* ensured that both the Brave (Browser) and Brave via `Carplay` display the same Playlist order
* ensured that changing the order of the `Playlist` via browser correctly updates `Carplay` without any issues
* ensured that changing the order while media is being played correctly updates `Carplay` and doesn't cause issues

**`Playlist Order Browser`** | **`Playlist Order CarPlay`**
-------------------------------|------------------------------
![IMG_9686](https://user-images.githubusercontent.com/2602313/139380489-f0e839e9-be39-4a1a-b408-0e373bcde04d.png) | ![IMG_9685](https://user-images.githubusercontent.com/2602313/139380495-4ef9b90a-333d-4337-8f24-04ce8d8f87a4.png)

* ensured that `Restart Playback` under `Settings` is disabled by default
* ensured that tapping on the circle via `Tap to enable playback restarting` enables the feature
* ensured there's a orange `Check` indicating `Restarting Playback` has been enabled
* ensured that tapping on `< Back` via `Playback Options` goes back to the main settings page
* ensured that switching between `Playlist` & `Settings` works without any issues

**`Settings`** | **`Playback Restart Disabled`** |  **`Playback Restart Enabled`**
---------------|-----------------------------------|------------------------------------
![IMG_9692](https://user-images.githubusercontent.com/2602313/139384267-a54af923-c344-4a3a-a152-aad83ed32a08.png) | ![IMG_9688](https://user-images.githubusercontent.com/2602313/139384289-4edad2bf-a903-41c6-82ff-21064662bde5.png) | ![IMG_9690](https://user-images.githubusercontent.com/2602313/139384299-2c5212d9-7ac3-4b40-8e9f-2a55fd656cd6.png)

* ensured that the play indicator is visible under the Playlist view when media is being played

![IMG_9694](https://user-images.githubusercontent.com/2602313/139390205-2c4c567e-622a-4186-8867-2a64b26b873b.png)

* ensured that tapping on the `Play` icon at the top right of the screen opens the media that's currently being played

![IMG_9696](https://user-images.githubusercontent.com/2602313/139390226-dd2211eb-2041-4e64-a951-42ad045ef89b.png)

* ensured that disabling Bluetooth/WiFi and disconnecting from `CarPlay` stops the currently playing media without issues
* ensured that the cloud icon is displayed when media is still being downloaded via the browser
* ensured that the cloud icon re-appears when media that has already been downloaded is removed via the browser

**`Re-downloading removed media (CarPlay)`** | **`Re-downloading removed media (Browser)`**
-----------------------------------------------------|------------------------------------------------------
![IMG_9698](https://user-images.githubusercontent.com/2602313/139391407-84fd91e5-8d95-4f4c-9539-2f7bde55ceae.png) | ![IMG_9697](https://user-images.githubusercontent.com/2602313/139391422-aa635d1a-2c43-4255-8dc5-038860f67e56.png)

* ensured that you can still use Brave for other functions while connected to `CarPlay` and media is being played
* ensured that you can also control media currently being played within the browser/iPhone notification area
* ensured that when media is finished playing, the next item is being played automaticallt
* ensured that map navigation is working while media is being played via Brave
</details>
