### ISSUE TITLE
Add support for Better Video Scrolling

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3675]
### Description: 
Tapping on the video scroll bar should take you to that position on the video/audio file.

**Comment by stephendonner** [comment]
**Verified `PASSED`** using Brave build `1.27 (21.6.15.14)` on `iPhone 6s`, `iOS 14.4.2`.

**Steps:**
1. new install
2. launched Brave (`dev`)
3. loaded `youtube.com`
4. searched for `never gonna give you up` 
5. played video
6. added video to my Playlist
7. tapped `Open` when prompted to open in Playlist
8. (regression-test) confirmed I was able to seek the video with the slider/progress bar traditionally, by tap, hold, and drag motions
9. confirmed I could tap on a position on the slider/progress bar, and the video jumped and resumed playing from there; tried in both landscape and portrait orientations/modes

https://user-images.githubusercontent.com/387249/122163522-3058b400-ce2a-11eb-8b8d-1349d9a3f797.MP4
