### ISSUE TITLE
Search backup

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3681]
Allow to communicate between the iOS device and Brave Search website.
The Brave Search may require us to call an alternative search engine for their results then send it back to the website for better search quality.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 14.6` using `1.27 (21.6.16.15)`

* ensured that the `Not many great matches` card appears when searching for `brave 123 456 789`
* ensured that `https://www.google.com` isn't being contacted when `fallback` is disabled
* ensured that `https://www.google.com` is being contacted when enabling `fallback` and searching `brave 123 456 789`
  * `https://www.google.com/search?q=brave%2520123%2520456%2520889&gl=us`
* ensured that the `These results were privately retrieved from Google` message appears at the top of search results when `fallback` has been enabled
  * ensured that the message doesn't appear once `fallback` has been disabled via the search settings
* ensured that tapping on `Learn More` opens https://search.brave.com/help/google-fallback

**`Example`** | **`Example`** | **`Fallback Disabled`** | **`Fallback Disabled`** |
---------------|-----------------|-------------------------|----------------------------
![image](https://user-images.githubusercontent.com/2602313/122359736-ccb2b180-cf23-11eb-9e50-fd35607753aa.png) | ![image](https://user-images.githubusercontent.com/2602313/122359776-d63c1980-cf23-11eb-82d3-e865672e9506.png) | ![noGoogle](https://user-images.githubusercontent.com/2602313/122359818-e18f4500-cf23-11eb-847a-982b519d73ea.png) | ![fallbackEnabled](https://user-images.githubusercontent.com/2602313/122359837-e8b65300-cf23-11eb-837b-efb96116eea4.png)

----

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.5` using `1.27 (21.6.16.15)`

* ensured that the `Not many great matches` card appears when searching for `brave 123 456 789`
* ensured that `https://www.google.com` isn't being contacted when `fallback` is disabled
* ensured that `https://www.google.com` is being contacted when enabling `fallback` and searching `brave 123 456 789`
  * `https://www.google.com/search?q=brave%2520123%2520456%2520889&gl=us`
* ensured that the `These results were privately retrieved from Google` message appears at the top of search results when `fallback` has been enabled
  * ensured that the message doesn't appear once `fallback` has been disabled via the search settings
* ensured that tapping on `Learn More` opens https://search.brave.com/help/google-fallback

**`Example`** | **`Example`** | **`Fallback Disabled`** | **`Fallback Disabled`** |
---------------|-----------------|-------------------------|----------------------------
![image](https://user-images.githubusercontent.com/2602313/122362237-f7056e80-cf25-11eb-8981-5f8ca0809224.png) | ![image](https://user-images.githubusercontent.com/2602313/122362280-fff64000-cf25-11eb-8ff8-8672f5a538d4.png) | ![disablediPad](https://user-images.githubusercontent.com/2602313/122362318-071d4e00-cf26-11eb-8623-0b5ca43b6970.png) | ![enablediPad](https://user-images.githubusercontent.com/2602313/122362335-0be20200-cf26-11eb-8443-b49330bd0f40.png)

----

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.27 (21.6.16.15)`

* ensured that the `Not many great matches` card appears when searching for `brave 123 456 789`
* ensured that `https://www.google.com` isn't being contacted when `fallback` is disabled
* ensured that `https://www.google.com` is being contacted when enabling `fallback` and searching `brave 123 456 789`
  * `https://www.google.com/search?q=brave%2520123%2520456%2520889&gl=us`
* ensured that the `These results were privately retrieved from Google` message appears at the top of search results when `fallback` has been enabled
  * ensured that the message doesn't appear once `fallback` has been disabled via the search settings
* ensured that tapping on `Learn More` opens https://search.brave.com/help/google-fallback

**`Example`** | **`Example`** | **`Fallback Disabled`** | **`Fallback Disabled`** |
---------------|-----------------|-------------------------|----------------------------
![image](https://user-images.githubusercontent.com/2602313/122365074-5cf2f580-cf28-11eb-941e-324ffd5ea771.png) | ![image](https://user-images.githubusercontent.com/2602313/122365118-67ad8a80-cf28-11eb-9058-6f0b527bd1bd.png) | ![disablediPad](https://user-images.githubusercontent.com/2602313/122365142-6da36b80-cf28-11eb-8609-881054acbd8f.png) | ![enablediPad](https://user-images.githubusercontent.com/2602313/122365169-71cf8900-cf28-11eb-8320-55383c97f34a.png)

**Comment by kjozwiak** [comment]
Created https://github.com/brave/brave-ios/issues/3807 & https://github.com/brave/brave-ios/issues/3808 when running through the above.
