### ISSUE TITLE
Update brave core to 1.25

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3682]

**Comment by stephendonner** [comment]
@iccub @kylehickinson do you have a testplan you can share, to unblock QA on this issue?  Thanks!

**Comment by iccub** [comment]
I believe only sanity check that Rewards functionality is working is enough here

**Comment by kjozwiak** [comment]
@stephendonner we usually close these off once we finish running through everything including the manual test cases. There's really no specific "test plan" other then making sure nothing has regressed. Once we're done with the milestone and the manual passes are finished, we'll add a `QA/Pass` label.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.27(21.6.18.10)
- Verified rewards work fine

Marking it as passed as other two test runs are verified with rewards sections
