### ISSUE TITLE
Clean up Storage framework files.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3684]
Most of code there is unused, it's FF legacy.

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 11` running `iOS 14.6` using `1.27 (21.6.17.10)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.5` using `1.27 (21.6.17.10)`
* Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.27 (21.6.17.10)`

STR/Cases used:

* Logged into `https://www.linkedin.com` and ensured that the `Save` login modal appeared at the bottom
  * ensured that selecting `Save Login` correctly saves the password
  * ensured that selecting `Don't Save` doesn't save the password
  * ensured that the password is being auto-populated when re-logging into the website
  * ensured updating the password after adding an incorrect password works as expected
* Logged into `https://leagueofcomicgeeks.com/` and ensured that the `Save` login modal appeared at the bottom
  * ensured that selecting `Save Login` correctly saves the password
  * ensured that selecting `Don't Save` doesn't save the password
  * ensured that the password is being auto-populated when re-logging into the website
  * ensured updating the password after adding an incorrect password works as expected
