### ISSUE TITLE
Try for Free text is missing in VPN info box in settings

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3691]
### Description: 
Try for Free text is missing in VPN info box in settings

### Steps to Reproduce 
  1. Install 1.26 build
  2. Open Settings menu
  3. Try for Free text is missing from VPN info

**Actual result vs Expected result**

1.26 | 1.25
-- | --
![image](https://user-images.githubusercontent.com/17010094/118660052-be1e9080-b7e5-11eb-9db6-2aacf946714c.png) | ![image](https://user-images.githubusercontent.com/17010094/118659654-6bdd6f80-b7e5-11eb-9e9d-a330f741b665.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.26(21.5.13.16)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

**Comment by kylehickinson** [comment]
Text isn't necessarily missing, its text color is just not white :)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.26(21.5.19.19)

iPhone 7+ (iOS 14.5.1) | iPhoneXR (iOS 13.5) | iPad Pro (iOS 14.5.1)
-- | -- | --
<img width=400 src=https://user-images.githubusercontent.com/17010094/119502504-e831fe80-bd61-11eb-85b1-57c1227e3a31.png> | <img width=320 src=https://user-images.githubusercontent.com/17010094/119503503-f2083180-bd62-11eb-95bc-3e402c828172.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/119502038-6510a880-bd61-11eb-83c8-a18033abe7fd.png>
