### ISSUE TITLE
Farbling & Fingerprinting protections

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3700]
### Description: 
Similar to https://github.com/brave/brave-browser/issues/8787 please implement 

For a spec, please search for "Farbling on iOS" on GDrive

### Test Plan
The following test site has been provided with instructions:
https://dev-pages.brave.software/fingerprinting/farbling.html

Linked to: 
https://github.com/brave/brave-ios/issues/3590
https://github.com/brave/brave-ios/issues/2823
https://github.com/brave/brave-ios/issues/762
https://github.com/brave/brave-ios/issues/746
https://github.com/brave/security/issues/800

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.4.1 running 1.38 (22.4.29.16)
- Verified test plan from [#5156](https://github.com/brave/brave-ios/pull/5156)
- Verified values are different for plugins when FP is enabled on both pages
- Verified values are set to `00000000` on both pages when FP is turned off

<table>
  <th colspan=2>
    <code>https://dev-pages.brave.software/fingerprinting/farbling.html</code>
  </th>
  <th colspan=2>
    <code>https://dev-pages.bravesoftware.com/fingerprinting/farbling.html</code>
  </th>
  </tr>
  <tr>
    <th>Fingerprint ON</th>
    <th>ShieldsFingerprint OFF</th>
    <th>Fingerprint ON</th>
    <th>Shields/Fingerprint OFF</th>
  </tr>
  <tr>
    <td>
      <img width=300 src=https://user-images.githubusercontent.com/17010094/166676916-1a253cdf-5812-4759-abe5-10c90e3b19f3.png>
    </td>
    <td>
      <img width=300 src=https://user-images.githubusercontent.com/17010094/166676903-b168dae3-aff8-4a94-9677-4d5afa8bfa5a.png>
    </td>
    <td>
      <img width=300 src=https://user-images.githubusercontent.com/17010094/166676965-f8a97d32-4d22-48f9-8589-9d8f86feba2c.png>
    </td>
    <td>
      <img width=300 src=https://user-images.githubusercontent.com/17010094/166676946-6169b8af-d2c9-4782-ab6c-77ef808dc88d.png>
    </td>
  </tr>
</table>

---------------

Verification passed on iPad Pro with iOS 15.5 Beta 3 running 1.38 (22.4.29.16)
- Verified test plan from [#5156](https://github.com/brave/brave-ios/pull/5156)
- Verified values are different for plugins when FP is enabled on both pages
- Verified values are set to `00000000` on both pages when FP is turned off

<table>
  <th colspan=2>
    <code>https://dev-pages.brave.software/fingerprinting/farbling.html</code>
  </th>
  <th colspan=2>
    <code>https://dev-pages.bravesoftware.com/fingerprinting/farbling.html</code>
  </th>
  </tr>
  <tr>
    <th>Fingerprint ON</th>
    <th>Shields/Fingerprint OFF</th>
    <th>Fingerprint ON</th>
    <th>Shields/Fingerprint OFF</th>
  </tr>
  <tr>
    <td>
      <img width=500 src=https://user-images.githubusercontent.com/17010094/166678003-ad891339-f6c6-42f8-bf44-5653a8a8b423.png>
    </td>
    <td>
      <img width=300 src=https://user-images.githubusercontent.com/17010094/166678017-d34dd813-f0e2-4cf2-b537-e66685d3c871.png>
    </td>
    <td>
      <img width=450 src=https://user-images.githubusercontent.com/17010094/166678037-a5480bfe-684e-4be4-b38b-b57a66cffa73.png>
    </td>
    <td>
      <img width=300 src=https://user-images.githubusercontent.com/17010094/166678048-c7f01fad-43d7-42f8-90fa-ae07b477bec6.png>
    </td>
  </tr>
</table>

---------------

Verification passed on iPhone 7+ with iOS 14.8.1 running 1.38 (22.4.29.16)
- Verified test plan from [#5156](https://github.com/brave/brave-ios/pull/5156)
- Verified values are different for plugins when FP is enabled on both pages
- Verified values are set to `00000000` on both pages when FP is turned off

<table>
  <th colspan=2>
    <code>https://dev-pages.brave.software/fingerprinting/farbling.html</code>
  </th>
  <th colspan=2>
    <code>https://dev-pages.bravesoftware.com/fingerprinting/farbling.html</code>
  </th>
  </tr>
  <tr>
    <th>Fingerprint ON</th>
    <th>Shields/Fingerprint OFF</th>
    <th>Fingerprint ON</th>
    <th>Shields/Fingerprint OFF</th>
  </tr>
  <tr>
    <td>
      <img width=500 src=https://user-images.githubusercontent.com/17010094/166702642-e498e793-f2a4-4e20-b602-abc377970075.png>
    </td>
    <td>
      <img width=500 src=https://user-images.githubusercontent.com/17010094/166702622-2bd9b1ad-ad71-48f5-a82e-2e3874276bc4.png>
    </td>
    <td>
      <img width=500 src=https://user-images.githubusercontent.com/17010094/166702692-5aac7e45-66fb-4118-a3f0-6904d0104299.png>
    </td>
    <td>
      <img width=500 src=https://user-images.githubusercontent.com/17010094/166702664-d784ab21-7bda-4389-b356-03b56515654e.png>
    </td>
  </tr>
</table>
