### ISSUE TITLE
takes multiple taps to open youtube video

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#3710]
### Description: 
It takes at least 2 (sometimes 3) taps to open a video on YouTube.

@srirambv was able to reproduce on his iPad, but not on his iPhone.

### Steps to Reproduce 
  1. Install 1.25 or 1.25.1
  2. Navigate to youtube
  3. Tap on a video, it does not open
  4. Tap again, maybe it opens, maybe it doesn't.
  5. Tap again if necessary
  6. Finally video opens and you get the "add to playlist" toast UI.

**Actual result:** 
Takes multiple taps (sometimes more than 2) in order to open yt video

**Expected result:**
Video should open after one tap

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.25, 1.25.1

**Device details:** 
iOS13 iPad mini

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Existing issue happens even on 1.24.1 via TF build. Issue doesn't repro on iPhone XR with iOS 13.5

**Comment by kjozwiak** [comment]
Notice it happening as well when running through https://github.com/brave/brave-ios/issues/3718 for the `1.26.x` release. @aekeus @bsclifton this is probably a `P2` or `P3` IMO as it affects YouTube which is probably one of the main video websites users visit.

**Comment by Brandon-T** [comment]
This is happening on Safari as well. Tested on my iPad Pro - OS 14.5
Only happens on Desktop UA (Desktop Site).

**Comment by iccub** [comment]
Let's close it as it is Apple controlled, we have to wait for an upstream fix
