### ISSUE TITLE
Add option to drag drag/rearrange favorites via NTP

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3713]
### Description: 

Lets figure out a way to drag drag/rearrange favorites

Review 
>why can’t we drag/rearrange favorites on the home page in the order we like?…

**Comment by iccub** [comment]
you can do it from the overlay screen cc @kylehickinson

**Comment by kylehickinson** [comment]
Yeah the reason why we dont allow rearranging on the main NTP is because you aren't able to see all your favourites like you can once you focus the URL bar. We could perhaps enable rearranging on the NTP but you'd only be able to drag & drop between your top 4

**Comment by iccub** [comment]
Requirements:
Allow user to rearrange the visible favorites on NTP. Favorites outside of visible ones do not need to be handled.

**Comment by srirambv** [comment]
Blocked on  #4463

**Comment by kjozwiak** [comment]
Labelling this one as `Verified/Passed` as verifications were completed via https://github.com/brave/brave-ios/issues/4463#issuecomment-988289255. The only remaining issue is https://github.com/brave/brave-ios/issues/4651 on `iOS 14` which will be QA'd in that particular GH issue. As per https://github.com/brave/brave-ios/issues/4651#issuecomment-988978983, we're reverting the change for `iOS 14` so you can't move the NTP tiles around.
