### ISSUE TITLE
Add option for custom adblocking lists

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3714]
### Description: 
A iOS reviewer requested that we add support for custom adblocking lists
Desktop is gaining this functionality so perhaps iOS could leverage some of this work

cc @pes10k

**Comment by iccub** [comment]
duplicate of https://github.com/brave/brave-ios/issues/3714

**Comment by davidcollini** [comment]
This should be re-opened as it can't be a duplicate of itself
