### ISSUE TITLE
Update history empty state UI

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3721]
### Description: 

Currently when a user has no history, the list is empty and provides no empty state, we should add something to this screen so it is more obvious

### Screenshot/Design:

Here is a sample design for the empty State:

![savelater](https://user-images.githubusercontent.com/6643505/119557452-351bd200-bd6e-11eb-85f7-caff705ef705.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.30(21.8.5.11)
- Verified empty history state shows as per design in issue description

iPhone XR (iOS 13.5) | iPhone 7+ (iOS 14.5.1) | iPad Pro (iOS 14.6)
-- | -- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/128380916-538d043c-f695-4936-ab05-fb6c75cbc880.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/128380937-23f14ce6-03fc-4d38-93c5-429fa2b44315.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/128381007-a995d8a5-bf8b-4754-949a-7c6afc589850.png>
