### ISSUE TITLE
Listennotes.com isn't recognized to save for playlist

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3726]
### Description: 
Listennotes.com isn't recognized to save for playlist

### Steps to Reproduce 
  1. Install 1.26
  2. Visit listennotes.com
  3. No playlist toast shown. Doesn't allow to add on context menu or share menu

**Actual result:** 
Listennotes.com isn't recognized to save for playlist

**Expected result:**
Should be recognized as per #3648

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.26

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by iccub** [comment]
Depending on complexity this might get moved out of the 1.26, waiting on Brandon's feedback

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(21.5.26.21)
- Verified Add to playlist is shown on listennotes.com

Toast | Menu Entry | Share Sheet
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/119780746-1b8b9f00-bec2-11eb-9e1a-cedde708d239.png) | ![image](https://user-images.githubusercontent.com/17010094/119780768-1fb7bc80-bec2-11eb-941d-665a9eff75ac.png) | ![image](https://user-images.githubusercontent.com/17010094/119780785-234b4380-bec2-11eb-87f8-89604948a511.png)

--------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.26(21.5.26.21)
- Verified Add to playlist is shown on listennotes.com

Toast | Menu Entry | Share Sheet
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/119780814-2c3c1500-bec2-11eb-9dea-f7da08ff534c.png) | ![image](https://user-images.githubusercontent.com/17010094/119780825-2fcf9c00-bec2-11eb-94b1-e1f176d21609.png) | ![image](https://user-images.githubusercontent.com/17010094/119780860-38c06d80-bec2-11eb-989d-1efa7c254131.png)

-------
Verification passed on iPad Pro with iOS 14.5.1 running 1.26(21.5.26.21)
- Verified Add to playlist is shown on listennotes.com

Toast | Menu Entry | Share Sheet
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/119780881-3fe77b80-bec2-11eb-9662-7004c85f13c3.png) | ![image](https://user-images.githubusercontent.com/17010094/119780907-4970e380-bec2-11eb-968e-594c0765e295.png) | ![image](https://user-images.githubusercontent.com/17010094/119780924-4d9d0100-bec2-11eb-8420-4ada54fea10f.png)
