### ISSUE TITLE
Add to playlist missing from share sheet on odysee.com

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3727]
### Description: 
Add to playlist missing from share sheet on odysee.com

### Steps to Reproduce 
  1. Install 1.26 build
  2. Visit `https://odysee.com` and play a video
  3. Dismiss the `Add to Brave Playlist` toast
  4. Open Menu-> Share with
  5. No entry for `Add to Brave playlist` on share sheet

**Actual result:** 

iPhone XR | iPhone 7+ 
-- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/119668273-f13cd180-be2e-11eb-9743-3546a1457551.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/119668494-247f6080-be2f-11eb-8605-d569ccbfed42.png>

**Expected result:**
![image](https://user-images.githubusercontent.com/17010094/119668299-f7cb4900-be2e-11eb-8f02-5cfea08197ef.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.26(21.5.25.18)

**Device details:** 
iPhone only

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Found while testing #3663

**Comment by iccub** [comment]
Moved to 1.26, this is a regression, will be fixed together with https://github.com/brave/brave-ios/issues/3726

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(21.5.26.21)
- Verified add to playlist option shows up on menu and share sheet

Menu listing | Share menu
-- | --
![image](https://user-images.githubusercontent.com/17010094/119780031-3ad5fc80-bec1-11eb-999b-7ea4bed10dfd.png) | ![image](https://user-images.githubusercontent.com/17010094/119780002-327dc180-bec1-11eb-8af3-ac88dfe1da54.png)

------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.26(21.5.26.21)
- Verified add to playlist option shows up on menu and share sheet

Menu listing | Share menu
-- | --
![image](https://user-images.githubusercontent.com/17010094/119779968-298cf000-bec1-11eb-99f1-c3dc3f8aff71.png) | ![image](https://user-images.githubusercontent.com/17010094/119779947-24c83c00-bec1-11eb-944d-9c7f90c0a8ed.png)

-----
Verification passed on iPad Pro with iOS 14.5.1 running 1.26(21.5.26.21)
- Verified add to playlist option shows up on menu and share sheet

Menu listing | Share menu
-- | --
![image](https://user-images.githubusercontent.com/17010094/119779827-06fad700-bec1-11eb-9d3d-1953cf2d1d40.png) | ![image](https://user-images.githubusercontent.com/17010094/119779884-124e0280-bec1-11eb-8851-0121bf0a1274.png)
