### ISSUE TITLE
NTP Tutorial Page is not loading after skipping onboarding

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#3731]
### Description: 

NTP Tutorial Page for JP is not being shown when onboarding is skipped.

Follow-up issue for #3389

### Steps to Reproduce 
  1. Fresh Install and use JP Locale
  2. Skip Onboarding
  3. No NTP page is loaded

**Actual result:** 

No NTP Tutorial Page is loaded

**Expected result:**

NTP Tutorial Page should be loaded after skip onboarding 

**Reproduces how often:** 
Easily reproduced

**Brave Version:** 
v 1.26 (21.5.25.18)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.26(21.5.26.18)
- Verified skipping onboarding loads the NTP tutorial page
- Encountered #3739 
---------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.26(21.5.26.18)
- Verified skipping onboarding loads the NTP tutorial page
- Encountered #3739 
---------
Verification failed on iPad. Logged follow up issue #3740
