### ISSUE TITLE
Rename Brave Today to Brave News and unlock unlimited RSS feeds

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3736]
See spec `Brave News Re-naming Plan`

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.27(21.6.10.21)

<details>
<summary>Verified test plan from #3737</summary>

![image](https://user-images.githubusercontent.com/17010094/121674105-897ebb80-caa9-11eb-8ff5-05c63fe7b2bc.png) | ![image](https://user-images.githubusercontent.com/17010094/121674140-900d3300-caa9-11eb-85fb-e95ac7701523.png) | ![image](https://user-images.githubusercontent.com/17010094/121674147-93a0ba00-caa9-11eb-95e3-8cb3c011558d.png) | ![image](https://user-images.githubusercontent.com/17010094/121674157-969baa80-caa9-11eb-83a3-194913c3ffd4.png) | ![image](https://user-images.githubusercontent.com/17010094/121674165-98fe0480-caa9-11eb-86f2-04d6c508361e.png) | ![image](https://user-images.githubusercontent.com/17010094/121674175-9bf8f500-caa9-11eb-846d-ddef5754fa16.png)
-- | -- | -- | -- | -- | --

</details>

------------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.27(21.6.10.21)

<details>
<summary>Verified test plan from #3737</summary>

![image](https://user-images.githubusercontent.com/17010094/121674259-baf78700-caa9-11eb-9510-b87f2fbfcad4.png) | ![image](https://user-images.githubusercontent.com/17010094/121674287-c2b72b80-caa9-11eb-80ed-375726b5bb37.png) | ![image](https://user-images.githubusercontent.com/17010094/121674291-c5198580-caa9-11eb-87c5-e1a1fef54982.png) | ![image](https://user-images.githubusercontent.com/17010094/121675513-67863880-caab-11eb-8747-bf67d216d772.png)| ![image](https://user-images.githubusercontent.com/17010094/121674302-ca76d000-caa9-11eb-9460-73f847c3baed.png) | ![image](https://user-images.githubusercontent.com/17010094/121674311-ccd92a00-caa9-11eb-902e-533c7e95461f.png)
-- | -- | -- | -- | -- | --

</details>

------------
Verification passed on iPad Pro with iOS 14.6 running 1.27(21.6.10.21)

<details>
<summary>Verified test plan from #3737</summary>

![image](https://user-images.githubusercontent.com/17010094/121674572-217ca500-caaa-11eb-8c7f-deda1bee7afb.png) | ![image](https://user-images.githubusercontent.com/17010094/121675145-eaf35a00-caaa-11eb-90f8-c63c8db4ad03.png) | ![image](https://user-images.githubusercontent.com/17010094/121675169-f6df1c00-caaa-11eb-858f-1de7c21b58a6.png) | ![image](https://user-images.githubusercontent.com/17010094/121675358-34dc4000-caab-11eb-9ece-7b7881afd6ce.png) | ![image](https://user-images.githubusercontent.com/17010094/121675218-078f9200-caab-11eb-8be6-2389fd035015.png) | ![image](https://user-images.githubusercontent.com/17010094/121675233-0eb6a000-caab-11eb-823d-6f7bd32d8190.png) | ![image](https://user-images.githubusercontent.com/17010094/121675248-137b5400-caab-11eb-8512-130e8d89d8cd.png)
-- | -- | -- | -- | -- | -- | --

</details>
