### ISSUE TITLE
Pages with popup dialog box (such as during basic HTTP authentication) do not load

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-ios#374]
**Issue:** On iOS, Brave does not load pages with certain popup dialog boxes. Example: The login page when clicking on “Login to Student Portal” on https://my.unisa.edu.au/public/studentweb never loads on Brave on iOS. 

**Testing:** The login page works fine on Safari, Chrome and Firefox (not Firefox Focus) on iOS. However, the page fails on Firefox Focus. On Firefox Focus, the page loads but immediately says “invalid credentials”. On Brave, the page never loads at all. 

On Brave, I have tried toggling shields, and also enabling settings like “allow popups” in settings. None of these resolved the problem.

**Other sites affected:** According to two users, this happens on other sites as well. The website above is only one example.

**Comment by jhreis** [comment]
@Miyayes is this for the app store version of Brave?

**Comment by kylehickinson** [comment]
It's a bit rough looking, but works on 1.7 tested at development (30114a4)

![simulator screen shot - iphone x - 2018-12-17 at 12 20 20](https://user-images.githubusercontent.com/529104/50103695-3c7e3f00-01f6-11e9-8d48-afbbac0a5f84.png)
