### ISSUE TITLE
Slow on new tab open

### ISSUE THREAD

**Issue by balintbarna** [brave/brave-ios#3747]
### Description: 
Brave iOS is often, but not always, slow to open the new tab page and let me start typing. Sometimes the delay is close to a second, but usually it feels more like a few hundred milliseconds. 

### Steps to Reproduce 
  1. Open browser
  2. Open new tab with "+" button
  3. Try to impatiently open your favorite site
  4. Compare fluidity of experience with Safari

**Actual result:** 
Laggy experience confuses my brain

**Expected result:**
Fluid, satisfying experience allowing me to instantly navigate

**Reproduces how often:** 
Not always, may have a relationship with the number of open tabs

**Brave Version:** 
1.25.1 (21.5.21.22) 

**Device details:** 
iPhone SE 2020
iOS 14.5.1

**Comment by iccub** [comment]
let's close for now
