### ISSUE TITLE
Add ability to change new tab page / disable top sites

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#375]
Quoted from @eatstorming on https://github.com/brave/browser-ios/issues/266

> My personal reasoning for this is just annoyance; the main page of an app I use for extended periods of time, changing based on what I've been browsing, annoys me.
>
>However, there is also a privacy issue at play: an eavesdropper can see what you've been browsing if they manage to look at your screen when you open a new tab.
>
>I understand that for a lot of people this may be a wanted feature. I just don't see why it can't be toggled on and off. So, please, add such an option to this otherwise awesome app.

Following _at least_ Brave desktop's options (https://github.com/brave/browser-ios/issues/266#issuecomment-276412996) would be good.

Similar to search engines, it would probably be to make this configurable for normal and private mode individually. As pointed out, this can be a potential privacy issues, and some people may not want top sites showing in a specific mode.

**Comment by iccub** [comment]
Top sites are now chosen manually(with preloaded default sites), not based on browsing history.

Idk if we removed it(do you know @kylehickinson ) but FF allowed to choose homepage to be either a normal home page, blank tab, or a specific site. Should be easy to reimplement

**Comment by kylehickinson** [comment]
A good chunk of the code is still there. We'd need to implement the user preferences side of things but I think most of the rest is still in the code base.

**Comment by dimazuien** [comment]
+1, would be very nice to have

**Comment by greatestradioshow** [comment]
I would love to have the possibility as for the homepage to set a custom page for new tabs. 
And/or having the possibility to define a page with a grid 4 x 4 where I could place a selection of bookmarks when opening a new tab (also nice to have for the homepage).

**Comment by jhreis** [comment]
@greatestradioshow not the same thing, but you can add favorites via the bookmark menu and these will be added to your main page. Will create a nice grid for you. Might be a decent stop-gap if you weren't familiar with it.

![IMG_7CE409F1E4C5-1](https://user-images.githubusercontent.com/2781690/206038706-13828430-209c-4f95-bf94-8c877fa35044.jpeg)

**Comment by iccub** [comment]
You can remove top sites and shield stats sections now, going to close this one.
There's more improvements coming to NTP like adding custom images as wallpapers, will be tracked in separate tickets.

And as for favorites we plan to have platform parity with desktop and Android, also tracked outside of this ticket
