### ISSUE TITLE
can't tap on `Login` under Twitter when credentials imported from `1Password`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3751]
### Description: 

This has been around for a while so definitely not a new regression but filling in your credentials using `1Password` won't change the state of the `Login` button to active. You'll need edit the username/password fields before the `Login` button goes from disabled to enabled. Seems like the page doesn't know there's a password that's been imported until the fields are edited.

I'm not 100% sure if this is a Brave issue or just an issue with the website but Twitter is basically the only one that I run into this with. There might be others but I haven't ran into them yet. Note: Also reproducible on `Firefox` so this might be a `WkWebView` issue.

### Steps to Reproduce

**`Prerequisites:`**

* ensure that you have a Twitter account
* ensure that you have 1Password and the Twitter credentials are saved within 1Password

**`STR:`**

  1. install the latest Brave (doesn't matter which version as this issue has been around for a while)
  2. once installed, visit twitter.com and import the credentials through `1Password` via `Share`

**Actual result:** 

<p align="center">
<img src="https://user-images.githubusercontent.com/2602313/120423741-03d86e80-c339-11eb-955c-827e4998e17e.png" width=300>
</p>

**Expected result:**

<p align="center">
<img src="https://user-images.githubusercontent.com/2602313/120423704-f3c08f00-c338-11eb-99e8-277acfb4c8cc.png" width=300>
</p>

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above mentioned STR.

**Brave Version:** 

* `1.25.1 (21.5.21.22)`

**Device details:** 

* `iPhone 12` running `iOS 14.6` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `Yes, reproducible with Firefox`

**Comment by srirambv** [comment]
This happens sometimes with builtin password manager as well. Work around is to focus on password field add a char and delete it at the end then the login button enables

**Comment by iccub** [comment]
Potentially fixed with https://github.com/brave/brave-ios/pull/4494
Needs retesting, and twitter layout changed since this was posted

**Comment by kjozwiak** [comment]
Went through the following STR/Cases for all of the platforms mentioned below:

* ensured that 1Password is enabled via iOS `Settings` -> `Passwords` -> `AutoFill Passwords and is allowed to autofill
* loaded twitter.com and tapped on `Sign In`
* entered my username and clicked on `Next`
* tapped on the password field and selected to AuoFill using 1Password
* tapped on `Log In`

Used the following devices/iOS versions:

* Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.33 (21.12.6.21)` - **PASSED**
* Verification **PASSED** on `iPhone 6+` running `iOS 14.6` using `1.33 (21.12.6.21)` - **PASSED**
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.1` using `1.33 (21.12.6.21)` - **PASSED**

**Comment by kjozwiak** [comment]
Quick note: Looks like the website doesn't correctly get rendered when you're auto-filling the password for 1Password. The `Login` button gets placed over the password field. However, clicking on `Login` works fine when this happens. You can down on the page which will start moving the `Login` button down and the password field will start to be visible. Added example screenshots for context. This is also an issue via Chrome so not related to the above work/Brave.

**`Example`** | **`Example`** | **`Example`**
----------------|----------------|---------------
![IMG_0395](https://user-images.githubusercontent.com/2602313/145086182-bbf8662c-6946-4277-94f6-5ccc98dd9015.png) | ![IMG_0396](https://user-images.githubusercontent.com/2602313/145086216-63dfa33d-8015-4c5f-b97c-e9472d979422.png) | ![IMG_0397](https://user-images.githubusercontent.com/2602313/145086225-fe171104-f367-46dc-9d63-41b42a3ea2a0.png)

Looks fine on `iPad` as per the following:

![IMG_0308](https://user-images.githubusercontent.com/2602313/145087105-e57b335b-fbfc-4be2-be58-5f3ba2ecdb3e.png)
