### ISSUE TITLE
Update the pinned certificates from the brave-core list

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#3755]
### Description: 
The latest pinned certificates for brave-core are available here: https://github.com/brave/brave-core/blob/master/chromium_src/net/tools/transport_security_state_generator/input_file_parsers.cc

We should use this list and populate the pinned certificate directory during bootstrap.

**Comment by iccub** [comment]
This ticket was closed, we updated certs manually

Followup ticket to add automation or add during a bootstrap script is here https://github.com/brave/brave-ios/issues/4064
