### ISSUE TITLE
Increase initial height of menu when page actions are visible

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3763]
We should increase the height of the current menu when the user is tapping the menu button while browsing a web page so that the share button is immediately tappable without scrolling

**Comment by kylehickinson** [comment]
I've labeled it `iPhone-specific` but it could technically happen on an iPad if you are using Brave while multitasked and Brave is the smaller window where the pan modal would appear even on iPad

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 14.6` using `1.27 (21.6.10.21)`:

**`1.26 (21.5.28.14)`** | **`1.27 (21.6.10.21)`**
------------------------|--------------------------
![IMG_3703](https://user-images.githubusercontent.com/2602313/121617216-7aa8f200-ca32-11eb-97d3-99ea8a05e4a5.png) | ![IMG_3701](https://user-images.githubusercontent.com/2602313/121617223-7d0b4c00-ca32-11eb-838a-f57401957519.png)
![IMG_3704](https://user-images.githubusercontent.com/2602313/121617272-901e1c00-ca32-11eb-91f2-201881343b36.png) | ![IMG_3702](https://user-images.githubusercontent.com/2602313/121617354-b93eac80-ca32-11eb-9d49-ccd88dd3e7d3.png)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.27(21.6.10.21)
- Verified on normal NTP menu height is same as before
- Verified on a page menu height is increased and share button is visible when menu is opened

https://user-images.githubusercontent.com/17010094/121650871-eec6b280-ca91-11eb-8437-01b88b620d60.MP4
