### ISSUE TITLE
instances of string being searched via `Find on Page` stays highlighted after search bar closed

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3772]
### Description: 

When searching for a string a page using either `On this page` via the omnibox or via the `Find in  page` under the `Settings` menu, pressing `X` will close the search bar at the bottom but will leave all instances of the word still highlighted.

### Steps to Reproduce

  1. visit https://en.wikipedia.org/wiki/Main_Page
  2. search for `the` via the omnibox or  `Find in  page` under the `Settings` 
  3. press `X` to close the search bar
  4. all instances of `the` are still highlighted

**Actual result:** 

**`Example`** | **`Example`**
---------------|-----------------
![IMG_0260](https://user-images.githubusercontent.com/2602313/121620316-2143c180-ca38-11eb-8fe0-af5156f90240.png) | ![IMG_6872](https://user-images.githubusercontent.com/2602313/121620334-256fdf00-ca38-11eb-80c7-98ea8a0c07ec.png)

**Expected result:**

When you close the search bar at the bottom, all highlighted instances should be removed.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

**`1.26 (21.5.28.14)`** - **Reproduced**
**`1.27 (21.6.10.21)`** - **Reproduced**

**Device details:** 

*  `iPhone 11` running `iOS 14.6` - **Reproduced**
*  `iPad Air (3rd Gen)` running `iOS 14.5` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

**Comment by kjozwiak** [comment]
Quick update: this seems to be happening as far back as `1.24` so it's definitely not a new regression. I can't really go any further due to the 90 day limitation of TF but looks like it's been in `Release` for a while.

Believe @kylehickinson mentioned that switching to the `iOS 14` API would fix the above issues but we'll need to figure out what to do with `iOS 13` which we're still supporting.

**Comment by kylehickinson** [comment]
I don't believe this is a problem anymore, it was likely fixed a long time ago when we switched APIs (we're also no longer supporting 13)

**Comment by Uni-verse** [comment]
in progress using version `1.46 (22.12.8.20)` on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.4.2
iPad - iPadOS 15.x

STR: https://github.com/brave/brave-ios/issues/3772#issue-918131178

- Verified instances of string being searched via `Find in Page` are not highlighted after search bar is closed.
- Verified searching again with `Find in Page` does not recall previous values or show them highlighted

<table><tr><td>iPad</td><td>iPhone</td></tr>

<tr><td>

https://user-images.githubusercontent.com/17885425/206782703-7bfb6ff9-537e-4a5c-ac70-a1b82a0fbb50.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/206782587-ad71baaf-70e2-431b-b111-eeaf4ff9b0ed.MP4

</td></tr></table>
