### ISSUE TITLE
Share function reposition

### ISSUE THREAD

**Issue by crazyyzarc** [brave/brave-ios#3773]
Couldn't you place the share function as one of the first points, because that saves time

![21-06-11 13-58-40 3867](https://user-images.githubusercontent.com/4954535/121684266-c4d7b500-cabe-11eb-8eed-7c9479bfa0bc.png)

https://user-images.githubusercontent.com/4954535/121683997-67dbff00-cabe-11eb-81ee-8dfdaa473abf.mp4

**Comment by kylehickinson** [comment]
Hi @crazyyzarc, the reason the share button is a bit lower is that it is included in the list of page-specific actions, but we realize that it's a bit harder to get to it now. In the next update, there will be a change which increases the initial height of the menu which should let you tap that Share To button without the need to scroll (https://github.com/brave/brave-ios/issues/3763)

We'll keep this is mind though when thinking about ways we can make the new menu better 🙂
