### ISSUE TITLE
Brave Search shows as "Brave Search Search"

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#3775]
### Description: 
- When Brave Search is the default engine, the suggestions title shows as "Brave Search Search".

### Steps to Reproduce 
  1. Set brave search as the default search engine.
  2. Search for something with suggestions enabled.

**Actual result:** 
- Shows "Brave Search Search"

**Expected result:**
- Show "Brave Search"

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily Reproduced

**Comment by kjozwiak** [comment]
Can be verified alongside https://github.com/brave/brave-ios/issues/3811 once fixed.

**Comment by srirambv** [comment]
Can mark this as QA/No as #3811 is superseding this issue

**Comment by kjozwiak** [comment]
> Can mark this as QA/No as #3811 is superseding this issue

Agreed 👍 Labelled as `QA/No` and the above was verified via https://github.com/brave/brave-ios/issues/3811#issuecomment-863416123.
