### ISSUE TITLE
Search Overlay, tap recent issue

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#3777]
Tapping a recent search should navigate to the default search engine instead of pasting into the url bar, to avoid the extra tap on go. The only time it should paste is when tapping the arrow icon.

One other issue is tapping on a recent search query shouldn't replicate the recent search record in the database, instead we should sort these by dateSearched then update the timestamp on older searches when they are tapped.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.27(21.6.17.10)
- Verified selecting an entry from recent searches loads the search result on default SE or selected SE
- Verified searching for the same term doesn't duplicate records in recent searches unless searched on a different SE
- Verified clearing recent searches and performing a search still shows the search from history
- Verified selecting a search from history and loading the SERP doesn't add the search term as recent search 
-----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.27(21.6.17.10)
- Verified selecting an entry from recent searches loads the search result on default SE or selected SE
- Verified searching for the same term doesn't duplicate records in recent searches unless searched on a different SE
- Verified clearing recent searches and performing a search still shows the search from history
- Verified selecting a search from history and loading the SERP doesn't add the search term as recent search 
-----------
Verification passed on iPad Pro with iOS 14.6 running 1.27(21.6.17.10)
- Verified selecting an entry from recent searches loads the search result on default SE or selected SE
- Verified searching for the same term doesn't duplicate records in recent searches unless searched on a different SE
- Verified clearing recent searches and performing a search still shows the search from history
- Verified selecting a search from history and loading the SERP doesn't add the search term as recent search
