### ISSUE TITLE
Search Overlay, Paste and Go issue

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#3778]
Tapping "Paste & Go" button should submit the search query instead of just pasting the url in the url bar.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.27(21.6.16.15)
- Verified paste and go performs a search using the default search engine
- Verified works on both normal and private tabs
-------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.27(21.6.16.15)
- Verified paste and go performs a search using the default search engine
- Verified works on both normal and private tabs
-----------
Verification passed on iPad Pro with iOS 14.6 running 1.27(21.6.16.15)
- Verified paste and go performs a search using the default search engine
- Verified works on both normal and private tabs
