### ISSUE TITLE
Expand menu to full when tapping on Settings.

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#3779]
Theres a feeling when tapping on Settings from new menu that the space is cramped. Would be better if we could have it expand the new pan modal to 100%. Swiping back does not need to adjust modal.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.28(21.6.30.8)
- Verified test plan from https://github.com/brave/brave-ios/pull/3847
- Verified menu opens up full when selecting VPN/Downloads/Bookmarks/History/Settings from menu
---------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.28(21.6.30.8)
- Verified test plan from https://github.com/brave/brave-ios/pull/3847
- Verified menu opens up full when selecting VPN/Downloads/Bookmarks/History/Settings from menu
---------
Verification passed on iPad Pro with iOS 14.6 running 1.28(21.6.30.8)
- Verified test plan from https://github.com/brave/brave-ios/pull/3847
- Verified menu opens up full when selecting VPN/Downloads/Bookmarks/History/Settings from menu
