### ISSUE TITLE
Internal Issue #777

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3783]
### Description: 
https://github.com/brave/internal/issues/777

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.28(21.7.5.14)
- Verification notes [here](https://github.com/brave/internal/issues/777#issuecomment-874919037)
-------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.28(21.7.5.14)
- Verification notes [here](https://github.com/brave/internal/issues/777#issuecomment-874919037)
-------
Verification passed on iPad Pro with iOS 14.6 running 1.28(21.7.5.14)
- Verification notes [here](https://github.com/brave/internal/issues/777#issuecomment-874919037)
