### ISSUE TITLE
Bookmark reorder gesture collides with the bottom menu pan gesture.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3787]
### Description: 
This happens on 2 screens:
- Bookmarks panel
- Quick Search engines list

### Steps to Reproduce 
  1. Add few bookmarks
  2. Try to reorder them

**Actual result:** 
Can't be done

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Regression caused by the new bottom menu update.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.28(21.7.8.16)
- Verified test plan from https://github.com/brave/brave-ios/pull/3851
- Verified able to reorder bookmarks and quick search engine without any issues

https://user-images.githubusercontent.com/17010094/125054482-27ac7400-e09e-11eb-8c6b-69ac171ad5ad.MP4

--------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.28(21.7.8.16)
- Verified test plan from https://github.com/brave/brave-ios/pull/3851
- Verified able to reorder bookmarks and quick search engine without any issues

https://user-images.githubusercontent.com/17010094/125055109-cc2eb600-e09e-11eb-9a2f-fdeb6c52d8d5.MP4

---------------
Verification passed on iPad Pro with iOS 14.6 running 1.28(21.7.8.16)
- Verified test plan from https://github.com/brave/brave-ios/pull/3851
- Verified able to reorder bookmarks and quick search engine without any issues

https://user-images.githubusercontent.com/17010094/125056377-15333a00-e0a0-11eb-963f-c7e47e77ee40.MP4
