### ISSUE TITLE
If you add many bookmarks, last bookmark is hidden by the bottom toolbar

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3788]
### Description: 
See this report
https://community.brave.com/t/bookmark-not-display-in-its-entirety/255240/5

### Steps to Reproduce 
  1. Add a lot of bookmarks
  2. Try to access last one

**Actual result:** 
It is hidden by the bottom toolbar

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Regression caused by the new bottom menu

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.28(21.7.8.16)
- Verified bookmarks are not hidden behind bottom toolbar

https://user-images.githubusercontent.com/17010094/125053815-71488f00-e09d-11eb-9979-222dda771ea4.MP4

------------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.28(21.7.8.16)
- Verified bookmarks are not hidden behind bottom toolbar

https://user-images.githubusercontent.com/17010094/125053917-89201300-e09d-11eb-9cf4-6259015d6516.MP4

------------
Verification passed on iPad Pro with iOS 14.6 running 1.28(21.7.8.16)
- Verified bookmarks are not hidden behind bottom toolbar

https://user-images.githubusercontent.com/17010094/125054222-e4ea9c00-e09d-11eb-8fe3-52114cde293f.MP4
