### ISSUE TITLE
Brave crashes on exit after trying to create a legacy wallet

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#3792]
### Description: 
Brave crashes on exit after trying to create a legacy wallet

### Steps to Reproduce 
  1. new profile
  2. launch Brave (dev)
  3. go through onboarding
  4. tap on Settings
  5. near the bottom, tap on View Rewards Debug Menu
  6. tap Create Legacy Wallet
  7. tap Exit Now

**Actual result:** 

Crashes

https://user-images.githubusercontent.com/387249/122128386-77728500-cde9-11eb-9dd6-9d70fb109196.mov

**Expected result:**

No crash; Brave restarts

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
Version 1.27 (21.6.15.14)

**Device details:** 
iPhone 6s, iOS 14.4.2

**Comment by iccub** [comment]
Is this a regression?

**Comment by kylehickinson** [comment]
There is no way in iOS to restart the app, this is how these rewards debug settings have always worked. No regression here
