### ISSUE TITLE
On-screen backspace/delete key doesn't work when autocomplete is enabled

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#3793]
### Description: 
On-screen backspace/delete key doesn't work when autocomplete is enabled

### Steps to Reproduce 
  1. new profile
  2. launch Brave (dev)
  3. load `http://https-everywhere.badssl.com/`
  4. load `brave.com`
  5. load `laurenwags.github.io`
  6. now, tap on the URL bar
  7. clear it
  8. start typing `https://` and then use the on-screen keyboard to try to delete the auto-completed string(s)

**Actual result:** 

Autocomplete keeps suggesting and replacing the text, but pressing delete doesn't work to actually delete characters

https://user-images.githubusercontent.com/387249/122129674-4abf6d00-cdeb-11eb-9edb-b803572af4a1.MP4

**Expected result:**
Pressing the on-screen delete button should allow you to get rid of the auto-completed suggestion and return to `http://`

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
Version 1.27 (21.6.15.14)

**Device details:** 
iPhone 6s, iOS 14.4.2

**Comment by iccub** [comment]
Will be fixed in this ticket https://github.com/brave/brave-ios/issues/3795
