### ISSUE TITLE
WiFi should read Wi-Fi on Private Browsing disclaimer page

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#3794]
### Description: 
`WiFi` should read `Wi-Fi` on Private Browsing disclaimer page

### Steps to Reproduce 
  1. new profile
  2. launch Brave
  3. click on the `[1]` icon on the bottom toolbar
  4. now, tap on `Private`
  5. read the text

**Actual result:** 
![Image from iOS](https://user-images.githubusercontent.com/387249/122132216-44cb8b00-cdef-11eb-91e1-14d423f1704a.png)

**Expected result:**
Should read `Wi-Fi` per `https://www.wi-fi.org/`

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 

**Device details:** 
iPhone 6s, iOS 14.4.2

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.28(21.6.30.8)

iPhone XR(iOS 13.5) | iPhone 7+ (iOS 14.5.1) | iPad Pro (iOS 14.6)
-- | -- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/124140347-4dbf8c00-da80-11eb-8c14-6d577e0096ec.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/124140139-24066500-da80-11eb-97ca-64f4a7889a42.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/124140099-1cdf5700-da80-11eb-9a3c-2d07621c4d49.png>
