### ISSUE TITLE
When text is auto-selected and auto-suggested, the suggestion can't be deleted

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#3795]
### Description: 
- When text is auto-selected and auto-suggested, the suggestion can't be deleted

### Steps to Reproduce 
  1. Type `https://brave.com` and hit enter.
  2. Tap the URL bar and now the URL is automatically selected.
  3. Hit backspace on the auto-selected text.
  4. The URL bar will try to auto-suggest/complete your text based on what was already searched previously.
  5. Hit backspace.

**Actual result:** 
- Notice it does NOT remove the suggested text because it keeps suggesting.

**Expected result:**
- Should delete text

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily Reproduced

**Brave Version:** 
v1.27

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.27(21.6.17.10)
- Verified steps from issue description
- Verified auto-selected text and auto-suggested text can be deleted 

https://user-images.githubusercontent.com/17010094/122539956-11237780-d020-11eb-924f-a4e34657eda5.MP4

-------------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.27(21.6.17.10)
- Verified steps from issue description
- Verified auto-selected text and auto-suggested text can be deleted 

https://user-images.githubusercontent.com/17010094/122540374-7d9e7680-d020-11eb-8e32-862dc81b4296.MP4

------------
Verification passed on iPad Pro with iOS 14.6 running 1.27(21.6.17.10)
- Verified steps from issue description
- Verified auto-selected text and auto-suggested text can be deleted 

https://user-images.githubusercontent.com/17010094/122540606-b76f7d00-d020-11eb-8cda-978f66d3f425.MP4
