### ISSUE TITLE
QRCode should read QR Code

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#3797]
### Description: 
QRCode should read QR Code

### Steps to Reproduce 
  1. new profile
  2. launch Brave
  3. tap in the URL bar
  4. tap on the QR Code icon

**Actual result:** 

Reads `To search by QRCode, align...`

![Image from iOS](https://user-images.githubusercontent.com/387249/122136757-01294f00-cdf8-11eb-9f1b-3c5d51c73928.jpg)

**Expected result:**
Should read `To search by QR Code, align...`

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
Brave 1.27 (21.6.15.14)

**Device details:** 
iPhone 6s, iOS 14.4.2

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 11` running `iOS 14.6` using `1.27 (21.6.16.15)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.5` using `1.27 (21.6.16.15)`
* Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.27 (21.6.16.15)`

**`iPhone 11 using iOS 14.6`** | **`iPad Air (3rd Gen) using iOS 14.5`** | **`iPad Mini 4 using iOS 13.7`**
---------------------------------|--------------------------------------------|------------------------------------
![IMG_3715](https://user-images.githubusercontent.com/2602313/122336311-a0d70200-cf0a-11eb-8113-d88baf8da7e2.png) | ![IMG_0261](https://user-images.githubusercontent.com/2602313/122336323-a46a8900-cf0a-11eb-9c5a-eb1070408f10.png) | ![IMG_0555](https://user-images.githubusercontent.com/2602313/122336330-a896a680-cf0a-11eb-87bc-0847a9dff77c.png)

-------------------
Verification passed on iPhone XR with iOS 13.5 running 1.27(21.6.16.15)
<img width=300 src=https://user-images.githubusercontent.com/17010094/122345103-60de4200-cf3f-11eb-9409-ecbafcc871b8.png>
