### ISSUE TITLE
`Scan QR Code` shortcut missing when tapping Brave icon

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3798]
### Description: 

Looks like we're missing the `Scan QR Code` shortcut under the context menu when tapping and holding the Brave icon. Reported by @srirambv.

### Steps to Reproduce

  1. install `1.27.x` via TF
  2. long tap the Brave icon and notice that the `Scan QR Code` is missing

**Actual result:** 

![IMG_3713](https://user-images.githubusercontent.com/2602313/122155221-84689600-ce34-11eb-8331-be91ff3a70be.jpg)

**Expected result:**

![IMG_6956](https://user-images.githubusercontent.com/2602313/122155228-89c5e080-ce34-11eb-9507-bede24167e80.jpg)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible when running through the above STR

**Brave Version:** 

* `1.27 (21.6.15.14)` - **Reproduced*

**Device details:** 

* `iPhone 11` running `iOS 14.6` - **Reproduced**
* `iPhone 12` running `iOS 14.6` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @anthonypkeane @Brandon-T @iccub @kylehickinson

**Comment by kjozwiak** [comment]
Can probably get this in the next release if possible. Wouldn't consider this a blocker for `1.27`.

**Comment by iccub** [comment]
Yes, better to move it to 1.28

**Comment by Brandon-T** [comment]
This is not in the spec for "Search Overlay".

**Comment by kjozwiak** [comment]
@anthonypkeane is this something we want as well? As mentioned by @Brandon-T, this wasn't in the spec. I think it would be a good addition.

**Comment by anthonypkeane** [comment]
1.28 or later works

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.31(21.8.25.18)
- Verified `Scan QR Code` shortcut is shown when long pressed on home screen app icon
- Verified Camera option opens up when `Scan QR Code` is selected 
- Verified page loads correctly with the QR scan code
- Verified Scan QR Code works on both normal and PB only mode

iPhone XR (iOS 13.5) | iPhone 7+ (iOS 14.5.1) | iPad Pro (iOS 14.6)
-- | -- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/130981317-a721d937-4008-4eba-bf80-5bfe5ad2cef4.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/130981346-330e8942-d49a-4c2d-ae97-21324c5eb9da.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/130981381-c22c575e-2f4d-4170-a74c-0039f18e22d2.png>
