### ISSUE TITLE
QR Code pages opened in PB are appearing in normal mode

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3800]
### Description: 

When opening a tab via the QR code scanner in `Private Browsing`, the tab will also appear in normal mode once switched. We should never leak anything that's opened in PB.

### Steps to Reproduce

  1. install `1.27 (21.6.15.14)`
  2. once installed, run through on-boarding and open a new `Private Browsing` tab
  3. tap on the URL and scan a QR Code while in `Private Browsing`
  4. tap on the `+` to open a new tab (you'll run into https://github.com/brave/brave-ios/issues/3799)
  5. switch back to normal mode and you'll notice the tab from the PB appearing in the tab tray

**Actual result:** 

Tabs opened in PB via the QR code scanner feature are appearing in normal mode

**Expected result:**

We should never leak anything from PB into normal mode

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.27 (21.6.15.14)` - **Reproduced**

**Device details:** 

* `iPhone 11` running `iOS 14.6` - **Reproduced**
* `iPhone 12` running `iOS 14.6` - **Reproduced**
* `iPad Air (3rd Gen)` running `iOS 14.6` - **Reproduced**
* `iPad Mini 4` running `iOS 13.7` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

@bsclifton @anthonypkeane @Brandon-T @iccub

**Comment by iccub** [comment]
great find

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 11` running `iOS 14.6` using `1.27 (21.6.16.15)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.5` using `1.27 (21.6.16.15)`
* Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.27 (21.6.16.15)`

STR/Cases:

* went through the STR/Cases outlined via https://github.com/brave/brave-ios/issues/3800#issue-922118813
* ensured that pages opened via `QR code` are not appearing under `History` in normal mode
* ensured that pages opened via `QR code` are not appearing under `Recent Searches` in normal mode
* ensured that tabs opened via a `QR code` are not being displayed/carried over into normal mode when exiting PB
