### ISSUE TITLE
Remove URLs from Recent Search

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#3803]
### Description: 
- URLs are currently showing up in Recent Search. They should not be shown when typed manually.

### Steps to Reproduce 
  1. Type a URL like `brave.com` in the address-bar/omni-box.

**Actual result:** 
- URL shows up in Recent Search

**Expected result:**
- No URLs in Recent Search

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily Reproduced

**Brave Version:** 
1.27

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.27(21.6.17.10)
- Verified typed in websites don't show up in recent search list
- Verified searching for a website still shows up in recent search list

https://user-images.githubusercontent.com/17010094/122524603-3c05cf80-d010-11eb-9766-c3f633d2486f.MP4

------------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.27(21.6.17.10)
- Verified typed in websites don't show up in recent search list
- Verified searching for a website still shows up in recent search list

https://user-images.githubusercontent.com/17010094/122525036-b8001780-d010-11eb-8466-64fd5011da76.MP4

----------
Verification passed on iPad Pro with iOS 14.6 running 1.27(21.6.17.10)
- Verified typed in websites don't show up in recent search list
- Verified searching for a website still shows up in recent search list

https://user-images.githubusercontent.com/17010094/122532866-d9fd9800-d018-11eb-8070-d0ebfbaf0810.MP4
