### ISSUE TITLE
NTP malformed when opening Brave while in `Private Browsing Only` mode

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3806]
### Description: 

When you close/re-open Brave while it's in `Private Browsing Only` mode, the NTP that's initially opened will be malformed.

### Steps to Reproduce

  1. open Brave (`1.27 (21.6.15.14)` in this case but the issue is present in `1.26.x` as well)
  2. go into the `Brave Shields & Privacy` and enable `Private Browsing`
  3. close/re-open Brave again

**Actual result:** 

**`Example`** | **`Example`**
---------------|-----------------
![IMG_3716](https://user-images.githubusercontent.com/2602313/122339710-67ed5c00-cf0f-11eb-8508-6d47a0c23cf0.png) | ![IMG_0556](https://user-images.githubusercontent.com/2602313/122339728-6e7bd380-cf0f-11eb-9cb3-70e2374ee0f1.png)

**Expected result:**

![IMG_3717](https://user-images.githubusercontent.com/2602313/122339757-75a2e180-cf0f-11eb-8aa6-e1c9e59bfbff.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.26 (21.5.28.14)` - **Reproduced**
* `1.27 (21.6.15.14)` - **Reproduced**

**Device details:** 

* `iPhone 11` running `iOS 14.6` - **Reproduced**
* `iPad Air (3rd Gen)` running `iOS 14.5` - **Reproduced**
* `iPad Mini 4` running `iOS 13.7` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @kylehickinson @Brandon-T @iccub @bsclifton @srirambv @anthonypkeane

**Comment by kjozwiak** [comment]
We can probably get this fixed in the next release due to `1.26` being right around the corner. Reproducible via `1.26 (21.5.28.14)` so it's not a new regression. Plus, I don't think a lot of people use `Private Browsing Only` so the impact isn't large. Easily fixed by opening a new tab.

**Comment by iccub** [comment]
should be working now
