### ISSUE TITLE
`Enable Google Fallback Mixing` switch missing from iOS

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3807]
### Description: 

Looks like we're missing the `Enable Google Fallback Mixing` switch when the `Not many great matches` card appears. Both Desktop/Android have the switch as demonstrated below.

### Steps to Reproduce

  1. install brave from TF (used `1.27 (21.6.16.15)` in this case)
  2. authenticate via `search.brave.com`
  3. search for `brave 123 456 789`

You'll notice that you'll get the `Lion` card but it's missing the `Enable Google Fallback Mixing` switch

**Actual result:** 

![image](https://user-images.githubusercontent.com/2602313/122346734-4a23f500-cf17-11eb-9eed-f75b8abdc957.png)

**Expected result:**

**`Desktop`** | **`Android`**
----------------|---------------
![backupDesktop](https://user-images.githubusercontent.com/2602313/122345702-244a2080-cf16-11eb-9b90-c32e80d1e4e5.png) | ![Screenshot_20210617-025309_Brave](https://user-images.githubusercontent.com/2602313/122346793-5c059800-cf17-11eb-8628-723aef9c97dc.jpg)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR mentioned above.

**Brave Version:** 

* `1.27 (21.6.16.15)` - **Reproduced**

**Device details:** 

* Verification **PASSED** on `iPhone 11` running `iOS 14.6` using `1.27 (21.6.16.15)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.5` using `1.27 (21.6.16.15)`
* Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.27 (21.6.16.15)`

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @bsclifton @iccub @anthonypkeane @srirambv

**Comment by kjozwiak** [comment]
@bsclifton not sure if the above is expected but it's a worse experience compared to Desktop/Android. You can still enable it via the `Settings` page and have it working, but there's no easy way to let users know it's even a feature/setting they can enable.

**Comment by kjozwiak** [comment]
@remusao let us know when the above is live so we can close this off and run through some verification to make sure the toggle works 👍

**Comment by remusao** [comment]
@kjozwiak Done, it's been deployed to `https://search.brave.com` so you should now see the fallback toggle.

**Comment by kjozwiak** [comment]
> @kjozwiak Done, it's been deployed to `https://search.brave.com` so you should now see the fallback toggle.

Closing as per the above 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 14.6` using `1.27 (21.6.16.15)`

* ensured that the `Enable Google Fallback mixing` appears when searching for terms like `brave 123 456 789`
* ensured that tapping on `Dismiss` correctly closes the `Enable Google Fallback mixing` card
  * ensured that it re-appears when another term that needs `fallback` is used
* ensured that `Learn more.` opens https://search.brave.com/help/google-fallback
* ensured that `https://www.google.com` isn't being contact when `fallback` is disabled
* ensured that `https://www.google.com` is being contact once `fallback` has been enabled

![image](https://user-images.githubusercontent.com/2602313/122429650-ef16f000-cf60-11eb-9789-24504a8dd2a9.png)

-----

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.5` using `1.27 (21.6.16.15)`

* ensured that the `Enable Google Fallback mixing` appears when searching for terms like `brave 123 456 789`
* ensured that tapping on `Dismiss` correctly closes the `Enable Google Fallback mixing` card
  * ensured that it re-appears when another term that needs `fallback` is used
* ensured that `Learn more.` opens https://search.brave.com/help/google-fallback
* ensured that `https://www.google.com` isn't being contact when `fallback` is disabled
* ensured that `https://www.google.com` is being contact once `fallback` has been enabled

![image](https://user-images.githubusercontent.com/2602313/122430408-93993200-cf61-11eb-963c-8de161eec669.png)

-------------

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.27 (21.6.16.15)`

* ensured that the `Enable Google Fallback mixing` appears when searching for terms like `brave 123 456 789`
* ensured that tapping on `Dismiss` correctly closes the `Enable Google Fallback mixing` card
  * ensured that it re-appears when another term that needs `fallback` is used
* ensured that `Learn more.` opens https://search.brave.com/help/google-fallback
* ensured that `https://www.google.com` isn't being contact when `fallback` is disabled
* ensured that `https://www.google.com` is being contact once `fallback` has been enabled

![image](https://user-images.githubusercontent.com/2602313/122431493-829cf080-cf62-11eb-8344-ac7b1a6d351f.png)
