### ISSUE TITLE
Update Brave Search beta logo

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3810]
We decided to go back and use the regular Brave lion logo

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 11` running `iOS 14.6` using `1.27 (21.6.17.10)`

**`Onboarding`** | **`Settings`** | **`Quick Search`**
-------------------|----------------|---------------------
![IMG_3729](https://user-images.githubusercontent.com/2602313/122444979-1674b980-cf6f-11eb-92ed-4958759c08c3.png) | ![IMG_3730](https://user-images.githubusercontent.com/2602313/122444986-196faa00-cf6f-11eb-858f-86c19d5e8084.png) | ![IMG_3731](https://user-images.githubusercontent.com/2602313/122445011-1d033100-cf6f-11eb-9273-98aeeb9e6a37.png)

-----

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.5` using `1.27 (21.6.17.10)`

**`Onboarding`** | **`Settings`** | **`Quick Search`**
-------------------|----------------|---------------------
![IMG_0275](https://user-images.githubusercontent.com/2602313/122449420-d401ab80-cf73-11eb-961f-7b61d2fe9fb5.png) | ![IMG_0276](https://user-images.githubusercontent.com/2602313/122449429-d6fc9c00-cf73-11eb-8dbe-fcb0d6fdaebc.png) | ![IMG_0277](https://user-images.githubusercontent.com/2602313/122449452-db28b980-cf73-11eb-8039-70ea12e88af0.png)

-----

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.27 (21.6.17.10)`

**`Onboarding`** | **`Settings`** | **`Quick Search`**
-------------------|----------------|---------------------
![IMG_0567](https://user-images.githubusercontent.com/2602313/122451298-f85e8780-cf75-11eb-9050-f11c6cc47583.png) | ![IMG_0568](https://user-images.githubusercontent.com/2602313/122451308-fac0e180-cf75-11eb-9b79-fd176436ef75.png) | ![IMG_0569](https://user-images.githubusercontent.com/2602313/122451317-feecff00-cf75-11eb-9ff1-716dbef74b79.png)
