### ISSUE TITLE
Conversion are not counted on Single Page Applications

### ISSUE THREAD

**Issue by iambrianfung** [brave/brave-ios#3814]
### Description: 
Brave Ads does not count conversions when the Conversion URL is a single-page application. We need to access the redirect chain to ensure that we measure conversion in iOS in the same way we do for desktop/android.

### Steps to Reproduce 
  1. Open Brave for iOS
  2. Adjust creatives in db to use only `Womplay` ads
  3. Trigger ad
  4. either click ad or navigate to URL `https://womplay.io/?utm_source=brave&utm_campaign=USA-UK&utm_content=You%20Play%20%F0%9F%8E%AE%20We%20Pay%20%F0%9F%92%B0%20Womplay`
  5. complete registration process
  6. confirm that you reached `https://womplay.io/register/ready`, thereby satisfying the conversion URL pattern `https://womplay.io/register/ready*`
  7. confirm if conversion has been counted.

**Actual result:** 
Conversion are not counted

**Expected result:**
Conversion are counted even when the conversion URL is on an SPA

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Relatively easily reproduced. For Womplay, you must use a net new email/account to register otherwise you will be put in to log-in path and not be redirected to the conversion url page

**Brave Version:** 
Release Channel 1.26

**Device details:** 
I believe this to be all iOS ver

### Additional Information
* you must use a net new email/account to register otherwise you will be put in to log-in path and not be redirected to the conversion url page

cc: @tmancey

**Comment by tmancey** [comment]
@kylehickinson we discussed this in the past, it is where `OnTextLoaded` and `OnHtmlLoaded` ads API calls would require the redirect chain to be passed an array of urls and the HTML for SPA changes for the same document are passed to the API calls.

**Comment by tmancey** [comment]
Unfortunately `WKWebView` only fires its functions when a full page load happens but we can add key value observing on the `WebKit.url` property.

**Comment by srirambv** [comment]
Marking this as QA/no after talking to @iccub
