### ISSUE TITLE
Incorrect favicons for favourites when edited

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3818]
### Description: 
Incorrect favicons for favourites when edited

### Steps to Reproduce 
  1. Clean install 1.27(21.6.17.10)
  2. Edit favourite and update the name and URL
  3. Visit the edited favourite in the same tab
  4. Navigate back to NTP on the same tab
  5. Long press on the edited favourite and delete it
  6. Favourites have wrong favicon when repositioned

**Actual result:** 

https://user-images.githubusercontent.com/17010094/122548906-d58dab00-d029-11eb-88d5-a2368b971186.MP4

**Expected result:**
Should use proper favicons

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.27(21.6.17.10)

**Device details:** 
iPhone XR (iOS 13.5)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
cc: @Brandon-T @iccub

**Comment by Uni-verse** [comment]
Verification completed using `1.36 (22.3.2.9) BraveCore 1.36.108 (99.0.4844.51)`

**PASSED** on `iPhone 12 Pro | iOS 15.1.1`
**PASSED** on` iPhone X | iOS 14.4.2`
**PASSED** on `iPad (7th Gen) | iOS 15.2.1`

- Verified favorites have correct favicons when edited/deleted.  https://github.com/brave/brave-ios/issues/3818#issue-924778708

https://user-images.githubusercontent.com/17885425/156635124-9295c3a7-0843-4d69-83f1-e7bac496291f.MP4
