### ISSUE TITLE
Telemetry Events

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#382]
Brave currently has no telemetry events (opt-in or otherwise).

This is just created to facilitate conversations regarding telemetry and track potential places that could be useful.

This assumes all telemetry would solely be opt-in with extremely clear disclaimers.

- crash reports
- bad content rule compiling

**Comment by jhreis** [comment]
Closing this per more global discussions. This involves cross platform talks and is out of scope for solely brave-ios.

**Comment by ghost** [comment]
I noticed that even when Brave rewards is disabled, the Brave iOS browser still sends data. Would be nice if this stopped, and only happened when rewards were enabled. See my post in the community forum:
https://community.brave.com/t/disable-brave-telemetry-data/103403
