### ISSUE TITLE
Core data initialization crash

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3828]
### Description: 

<img width="476" alt="Zrzut ekranu 2021-06-21 o 17 22 00" src="https://user-images.githubusercontent.com/6950387/122787017-3250c600-d2b5-11eb-9dd2-2709cd1b9f26.png">

### Steps to Reproduce 
Hard to reproduce, but there's a lot of reports in xcode crashes organizer.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
We'll close this one off once we're done verifying all the remaining issues and finish running through the manual passes via https://github.com/brave/brave-ios/issues/3902, https://github.com/brave/brave-ios/issues/3903 & https://github.com/brave/brave-ios/issues/3904.

**Comment by srirambv** [comment]
Verification passed on iPhone XR (iOS 13.5) / iPhone 7+ (iOS 14.5.1) / iPad Pro (iOS 14.6)  running 1.28(21.7.9.13).
