### ISSUE TITLE
Prevent Adding Default Search Engines to Search Engine List using Open Search Auto-Add

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#3834]
### Description: 

Some of the Default Search Engines including Brave Search can be added using Open Search Auto add.

We should add Open Search Reference to default Search Engines so the Add functionality will not be activated for already added engines.

### Steps to Reproduce 
  1. Go brave.search.com
  2. Press Search Textfield
  3. The Add button for Open Search is active over the keyboard

**Actual result:** 

The Add button for Open-Search is active

**Expected result:**

It should not be activated.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.27.1 (21.6.22.16)

**Device details:** 
Any Device

**Website problems only:**
N/A

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.28(21.7.6.16)
- Verified default search engine doesn't show quick search engine button 
- Verified manually added search engine via open search stops showing add search engine button

https://user-images.githubusercontent.com/17010094/124931684-5d981c80-dffa-11eb-9597-0c73f0a55b7f.MP4

-----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.28(21.7.6.16)
- Verified default search engine doesn't show quick search engine button 
- Verified manually added search engine via open search stops showing add search engine button

https://user-images.githubusercontent.com/17010094/124931816-786a9100-dffa-11eb-8821-872b72029e1f.MP4

-----------
Verification passed on iPad Pro with iOS 14.6 running 1.28(21.7.6.16)
- Verified default search engine doesn't show quick search engine button 
- Verified manually added search engine via open search stops showing add search engine button

https://user-images.githubusercontent.com/17010094/124932294-ddbe8200-dffa-11eb-9652-9ef2a5b22a04.MP4
