### ISSUE TITLE
Provide an option to allow user to persistent tabs in private mode 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3835]
### Description: 
Please provide an option to allows users to persistent tabs in private mode

Under Display
Persistent Tabs in Private Mode (On/Off)
Default = Off (as we do today)

@jamesmudgett for review before implementation can begin
@jumde for comment as we may need a security review here

**Comment by iccub** [comment]
duplicate of https://github.com/brave/brave-ios/issues/3183
