### ISSUE TITLE
Crash when favorites are reordered 

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3839]
### Description: 
Regression caused by the new search overlay

### Steps to Reproduce 
  1. Add 4 favorite items
  2. Tap on url bar
  3. Long press on a favorite trying to drag it

**Actual result:** 
Crash!

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
This still crashes when favourites is dragged beyond the favourites row. Logged #3879 and marked this as blocked

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.28(21.7.6.16)
- Verified no browser crash when favourite is reordered
------------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.28(21.7.6.16)
- Verified no browser crash when favourite is reordered
------------
Verification passed on iPad Pro with iOS 14.6 running 1.28(21.7.6.16)
- Verified no browser crash when favourite is reordered
