### ISSUE TITLE
Ship Shields blocklists with browser

### ISSUE THREAD

**Issue by tildelowengrimm** [brave/brave-ios#384]
As noted in brave/internal#450, it's possible to bypass Shields protections on first run if you're quick. Because Shields lists aren't shipped with the binary, there's effectively a race condition about whether you get the Shields list or the the your first site visit faster. This isn't a great look.

Instead, we should bake an initial set of Shields lists into the binaries on all platforms. Once installed, lists can be upgraded as usual, but that doesn't leave that possible lag period.

**Comment by jhreis** [comment]
Completed per: https://github.com/brave/brave-ios/issues/71
