### ISSUE TITLE
Update private NTP

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3841]

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.28(21.7.2.17)
- Verified private NTP is updated. Verification notes [here](https://github.com/brave/internal/issues/785#issuecomment-874084197)
--------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.28(21.7.2.17)
- Verified private NTP is updated.  Verification notes [here](https://github.com/brave/internal/issues/785#issuecomment-874084197)
--------
Verification passed on iPad Pro with iOS 14.6 running 1.28(21.7.2.17)
- Verified private NTP is updated.  Verification notes [here](https://github.com/brave/internal/issues/785#issuecomment-874084197)
