### ISSUE TITLE
Quick search engines glitch

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3843]
### Description: 
See this tweet https://twitter.com/Sploitable/status/1407907039972577286

Possible search overlay regression but can be a standalone bug

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.28(21.7.6.16)
- Verified quick search engine only scrolls horizontally

https://user-images.githubusercontent.com/17010094/124916194-4d784100-dfea-11eb-8106-dbe76b510ab4.MP4

-----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.28(21.7.6.16)
- Verified quick search engine only scrolls horizontally

https://user-images.githubusercontent.com/17010094/124916321-700a5a00-dfea-11eb-98e0-8115efc0c7c8.MP4

-----------
Verification passed on iPad Pro with iOS 14.6 running 1.28(21.7.6.16)
- Verified quick search engine only scrolls horizontally

https://user-images.githubusercontent.com/17010094/124916922-1d7d6d80-dfeb-11eb-87d7-0c2e63092f67.MP4
