### ISSUE TITLE
Update adblock-rust library to support new DAT format

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3848]
Currently shipping with 0.3.5 and we will need to update it to the latest (0.3.15) as there is an incoming change to the DAT format

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.29(21.07.20.16)
- Verified test plan from #3895 
-----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.29(21.07.20.16)
- Verified test plan from #3895 
-----------
Verification passed on iPad Pro with iOS 14.6 running 1.29(21.07.20.16)
- Verified test plan from #3895
