### ISSUE TITLE
Settings items reorder

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#385]
This task is blocked until Sync integration https://github.com/brave/brave-ios/issues/37 lands

Add new settings section called `Data`.

Move following items into this section:
- sync
- save logins
- Clear private data(rename it to `Clear browsing data`)

**Comment by anthonypkeane** [comment]
@jamesmudgett to figure out how this will look.

**Comment by jamesmudgett** [comment]
The spec mentioned by @iccub works for me. Will follow settings table design as-is.

**Comment by kylehickinson** [comment]
Closing as stale, menu has changed too much since. If it comes up again we'd need more info anyways
