### ISSUE TITLE
Long press on visited site in search overlay crash

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3853]
### Description: 
<img width="1175" alt="Zrzut ekranu 2021-06-28 o 12 21 33" src="https://user-images.githubusercontent.com/6950387/123621331-6115f180-d80b-11eb-8fe9-e7926594c34b.png">

### Steps to Reproduce 
  1. Fresh install
  2. Visit a website, like wikipedia.org
  3. Tap on url, clear address bar
  4. Type 'wik', wikipedia will show up as an option
  5. Long press on it

**Actual result:** 
Crash

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.28(21.7.2.17)
- Verified steps form issue description
- Verified on both normal and private tab
----------------------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.28(21.7.2.17)
- Verified steps form issue description
- Verified on both normal and private tab
----------------------
Verification passed on iPad Pro with iOS 14.6 running 1.28(21.7.2.17)
- Verified steps form issue description
- Verified on both normal and private tab
