### ISSUE TITLE
Playlist performance improvements

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3855]
Not a bug, but Brandon wanted to potentially improve performance of playlists, especially on slow networks.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.29(21.07.20.16)
- Verified test plan from https://github.com/brave/brave-ios/pull/3781
-----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.29(21.07.20.16)
- Verified test plan from https://github.com/brave/brave-ios/pull/3781
-----------
Verification passed on iPad Pro with iOS 14.6 running 1.29(21.07.20.16)
- Verified test plan from https://github.com/brave/brave-ios/pull/3781
