### ISSUE TITLE
Update Ecosia search parameters

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#3856]
## Description 
Ecosia has an `Add Ecosia to iOS` button on https://ecosia.org (below search text box)
![image](https://user-images.githubusercontent.com/4733304/123836918-181f7500-d8bf-11eb-9390-dbe4bc41a734.png)

The `Add to iOS` button **SHOULD** show if you've **never** done a search in Brave with the built in Ecosia engine.

The `Add to iOS` button **SHOULD NOT** be showing for Brave users who:
- have Ecosia set as their default search engine AND do a search
- do a search with the built in Ecosia quick search (ex: tap the Ecosia icon during search query)
- use an Ecosia URL that has `&addon=brave` added to it (ex: visit https://www.ecosia.org/search?q=brave&addon=brave&tt=e8eb07a6)

## Steps to Reproduce
   1. Fresh profile
   2. Visit https://www.ecosia.org/
   3. `Add to iOS` Button should show
   4. Set Ecosia as default search engine
   5. Search in omnibox 
   6. Go back to https://www.ecosia.org/

## Actual result:
Landing page has a `Add Ecosia to iOS` button

## Expected result:
Landing page should not show `Add Ecosia to iOS` button

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 14.6` using `1.28 (21.7.6.16)`

<details>
<summary>Test Case 1  (Clean install) </summary>

<br>

* ensured that visiting https://www.ecosia.org displayed the `Add Ecosia to iOS` on a clean profile
  * Ecosia wasn't set as the default and a search was never completed via the omnibox
* ensured that visiting https://www.ecosia.org displayed the `Add Ecosia to iOS` on a clean profile
  * Ecosia was set as the default SE but a search using `addon=brave` via the omnibox was never completed
* ensured that `Add Ecosia to iOS` isn't being displayed once a search is completed using `addon=brave`
* ensured that the `addon=brave` parameter was being added into the search query when searching via the omnibox

**`Example`** | **`Example`**
----------------|---------------
![IMG_3745](https://user-images.githubusercontent.com/2602313/124839737-579d2f80-df57-11eb-88fc-c67a2d05d69a.png) | ![IMG_3746](https://user-images.githubusercontent.com/2602313/124839743-5a982000-df57-11eb-8eeb-c9bb33326a23.png)
</details>

<details>
<summary>Test Case 2  (Update from 1.27.1 (21.6.22.16) while Ecosia wasn't set as default SE)</summary>

<br>

* ensured that the current default search engine isn't changed (Brave Search in this case)
* ensured that visiting https://www.ecosia.org displayed the `Add Ecosia to iOS`
  * Ecosia wasn't set as the default and a search was never completed via the omnibox
* ensured that visiting https://www.ecosia.org displayed the `Add Ecosia to iOS`
  * Ecosia was set as the default SE but a search using `addon=brave` via the omnibox was never completed
* ensured that `Add Ecosia to iOS` isn't being displayed once a search is completed using `addon=brave`
* ensured that the `addon=brave` parameter was being added into the search query when searching via the omnibox
</details>

<details>
<summary>Test Case 3  (Update from  1.27.1 (21.6.22.16) while Ecosia is set as default SE)</summary>

<br>

* ensured that visiting https://www.ecosia.org displayed the `Add Ecosia to iOS` before running a search via the omnibox
* ensured that the `addon=brave` parameter was being added into the search query when searching via the omnibox
* ensured that `Add Ecosia to iOS` isn't being displayed once a search is completed using `addon=brave`
</details>

----------------------

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.28 (21.7.8.16)`

<details>
<summary>Test Case 1  (Clean install) </summary>

<br>

**`Quick note:`** looks like the `Add Ecosia to iOS` button only applies when viewing the page via mobile view. While in desktop view, you'll see the `Set as Homepage`.

* ensured that visiting https://www.ecosia.org displayed the `Add Ecosia to iOS` on a clean profile
  * Ecosia wasn't set as the default and a search was never completed via the omnibox
* ensured that visiting https://www.ecosia.org displayed the `Add Ecosia to iOS` on a clean profile
  * Ecosia was set as the default SE but a search using `addon=brave` via the omnibox was never completed
* ensured that `Add Ecosia to iOS` isn't being displayed once a search is completed using `addon=brave`
* ensured that the `addon=brave` parameter was being added into the search query when searching via the omnibox

**`Example (Desktop View)`** | **`Example (Desktop View)`**
----------------|---------------
![IMG_0583](https://user-images.githubusercontent.com/2602313/125003286-e166fe80-e024-11eb-8e62-1afa0df80649.png) | ![IMG_0584](https://user-images.githubusercontent.com/2602313/125003292-e4fa8580-e024-11eb-8d93-a82de586ece9.png)

**`Example (Mobile View)`** | **`Example (Mobile View)`**
----------------|---------------
![IMG_0581](https://user-images.githubusercontent.com/2602313/125003373-1410f700-e025-11eb-944c-be2a91f924fa.png) | ![IMG_0582](https://user-images.githubusercontent.com/2602313/125003379-15daba80-e025-11eb-858e-2dec73fd7065.png)

**`Example (Mobile View)`** | **`Example (Mobile View)`**
----------------|---------------
![IMG_0588](https://user-images.githubusercontent.com/2602313/125003420-2d19a800-e025-11eb-9d1f-1690e7b421d0.png) | ![IMG_0586](https://user-images.githubusercontent.com/2602313/125003423-2f7c0200-e025-11eb-855a-597adb41f792.png)
</details>

<details>
<summary>Test Case 2  (Update from 1.27.1 (21.6.22.16) while Ecosia wasn't set as default SE)</summary>

<br>

**`Quick note:`** looks like the `Add Ecosia to iOS` button only applies when viewing the page via mobile view. While in desktop view, you'll see the `Set as Homepage`.

* ensured that the current default search engine isn't changed (Brave Search in this case)
* ensured that visiting https://www.ecosia.org displayed the `Add Ecosia to iOS`
  * Ecosia wasn't set as the default and a search was never completed via the omnibox
* ensured that visiting https://www.ecosia.org displayed the `Add Ecosia to iOS`
  * Ecosia was set as the default SE but a search using `addon=brave` via the omnibox was never completed
* ensured that `Add Ecosia to iOS` isn't being displayed once a search is completed using `addon=brave`
* ensured that the `addon=brave` parameter was being added into the search query when searching via the omnibox
</details>

<details>
<summary>Test Case 3  (Update from  1.27.1 (21.6.22.16) while Ecosia is set as default SE)</summary>

<br>

**`Quick note:`** looks like the `Add Ecosia to iOS` button only applies when viewing the page via mobile view. While in desktop view, you'll see the `Set as Homepage`.

* ensured that visiting https://www.ecosia.org displayed the `Add Ecosia to iOS` before running a search via the omnibox
* ensured that the `addon=brave` parameter was being added into the search query when searching via the omnibox
* ensured that `Add Ecosia to iOS` isn't being displayed once a search is completed using `addon=brave`
</details>

----------------------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.6` using `1.28 (21.7.8.16)`

<details>
<summary>Test Case 1  (Clean install) </summary>

<br>

**`Quick note:`** looks like the `Add Ecosia to iOS` button only applies when viewing the page via mobile view. While in desktop view, you'll see the `Set as Homepage`.

* ensured that visiting https://www.ecosia.org displayed the `Add Ecosia to iOS` on a clean profile
  * Ecosia wasn't set as the default and a search was never completed via the omnibox
* ensured that visiting https://www.ecosia.org displayed the `Add Ecosia to iOS` on a clean profile
  * Ecosia was set as the default SE but a search using `addon=brave` via the omnibox was never completed
* ensured that `Add Ecosia to iOS` isn't being displayed once a search is completed using `addon=brave`
* ensured that the `addon=brave` parameter was being added into the search query when searching via the omnibox

**`Example (Desktop View)`** | **`Example (Desktop View)`**
----------------|---------------
![IMG_0286](https://user-images.githubusercontent.com/2602313/125017225-b12d5900-e040-11eb-9803-443213ae7310.png) | ![IMG_0288](https://user-images.githubusercontent.com/2602313/125017273-c904dd00-e040-11eb-8c89-7db2adc6f91c.png)

**`Example (Mobile View)`** | **`Example (Mobile View)`**
----------------|---------------
![IMG_0287](https://user-images.githubusercontent.com/2602313/125017287-cf935480-e040-11eb-88c9-41f192a9fb2e.png) | ![IMG_0288](https://user-images.githubusercontent.com/2602313/125017292-d1f5ae80-e040-11eb-864a-ce2ed91a925b.png)
</details>

<details>
<summary>Test Case 2  (Update from 1.27.1 (21.6.22.16) while Ecosia wasn't set as default SE)</summary>

<br>

**`Quick note:`** looks like the `Add Ecosia to iOS` button only applies when viewing the page via mobile view. While in desktop view, you'll see the `Set as Homepage`.

* ensured that the current default search engine isn't changed (Brave Search in this case)
* ensured that visiting https://www.ecosia.org displayed the `Add Ecosia to iOS`
  * Ecosia wasn't set as the default and a search was never completed via the omnibox
* ensured that visiting https://www.ecosia.org displayed the `Add Ecosia to iOS`
  * Ecosia was set as the default SE but a search using `addon=brave` via the omnibox was never completed
* ensured that `Add Ecosia to iOS` isn't being displayed once a search is completed using `addon=brave`
* ensured that the `addon=brave` parameter was being added into the search query when searching via the omnibox
</details>

<details>
<summary>Test Case 3  (Update from  1.27.1 (21.6.22.16) while Ecosia is set as default SE)</summary>

<br>

**`Quick note:`** looks like the `Add Ecosia to iOS` button only applies when viewing the page via mobile view. While in desktop view, you'll see the `Set as Homepage`.

* ensured that visiting https://www.ecosia.org displayed the `Add Ecosia to iOS` before running a search via the omnibox
* ensured that the `addon=brave` parameter was being added into the search query when searching via the omnibox
* ensured that `Add Ecosia to iOS` isn't being displayed once a search is completed using `addon=brave`
</details>
