### ISSUE TITLE
Hide IOS status bar option

### ISSUE THREAD

**Issue by ProgramComputer** [brave/brave-ios#3860]
## Feature Overview 
Add an option in settings to hide IOS status bar while scrolling.
## Design 

N/A
## Implementation Details 

Before:

![Before](https://i.ibb.co/6g5yqMD/04515-ACB-E121-4585-9582-42-F36-DE5-C13-A.png)

After:

![After](https://i.ibb.co/LNtYWbV/E2955-E62-BFEA-458-A-967-F-2089-EC308-A21.jpg)

## User Experience 

1. Occurs while scrolling
2. 
3.

**Comment by iccub** [comment]
We decided to follow what Safari does and always show the smaller url bar, this is good for security reasons.
