### ISSUE TITLE
URL item shared to Brave is not recognized as URL type

### ISSUE THREAD

**Issue by KacperWybranski** [brave/brave-ios#3863]
### Description: 
URL item shared to Brave via Share Extension is always recognized as String and not as URL. It cause searching the url with search engine, so url is loading correctly in app but it prevents adding future functionalities like "brave//bookmark" scheme.

### Steps to Reproduce 
  1. Change 65 line of code in ShareToBraveViewController to:
  `guard let provider = attachments.first(where: { $0.isUrl }) else {` so it won't recognize pure text
  2. Try share "https://www.apple.com" or any other url to Brave

**Actual result:** 
Brave app doesn't open.

**Expected result:**
Brave opens and loads URL.

**Reproduces how often:** 
Always

**Brave Version:** 
development branch

**Device details:** 
Simulator of iPhone SE 2020 with iOS 13.6

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.30(21.8.5.11)
- Verified selecting a text from Safari and sharing with Brave switched to the Brave app
------------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.30(21.8.5.11)
- Verified selecting a text from Safari and sharing with Brave switched to the Brave app
------------
Verification passed on iPad Pro with iOS 14.6 running 1.30(21.8.5.11)
- Verified selecting a text from Safari and sharing with Brave switched to the Brave app
