### ISSUE TITLE
IPv6 addresses not identified as valid URLs

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3866]
See upstream ticket

https://github.com/mozilla-mobile/firefox-ios/issues/6015

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 12` running `iOS 14.7.1` using `1.31 (21.9.13.20)` via the following STR/Cases:

* ensured that https://ipv6.google.com loaded without any issues (IPv6)
* ensured that https://www.v6.facebook.com loads without any issues (IPv6)
* ensured that https://www.google.com loads without any issues (IPv4)
* ensured that https://www.facebook.com loads without any issues (IPv4)

**`IPv6 Supported`** | **`Google (IPv6)`** | **`FB (IPv6)`**
-----------------------|----------------------|-----------------
![DCD73255-9637-4ACB-B2F5-262B62D3D6BC](https://user-images.githubusercontent.com/2602313/133190884-2b0209a2-ce54-40dd-ae92-e9cc885a92cf.PNG) | ![8117E120-769B-42E4-A738-FA969B2A9E26](https://user-images.githubusercontent.com/2602313/133190897-2d86fb27-0470-4962-b599-40c4d5afc1a1.PNG) | ![7FAD302A-8C5E-4F38-9805-7FF22DA31417](https://user-images.githubusercontent.com/2602313/133190911-9a8e31db-a05f-46d4-ae3c-6c9adbd81f38.PNG)

----------------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.7.1` using `1.31 (21.9.13.20)` via the following STR/Cases:

* ensured that https://ipv6.google.com loaded without any issues (IPv6)
* ensured that https://www.v6.facebook.com loads without any issues (IPv6)
* ensured that https://www.google.com loads without any issues (IPv4)
* ensured that https://www.facebook.com loads without any issues (IPv4)

**`IPv6 Supported`** | **`Google (IPv6)`** | **`FB (IPv6)`**
-----------------------|----------------------|-----------------
![IMG_0302](https://user-images.githubusercontent.com/2602313/133191748-419592ac-2142-4a88-b3f7-2d7827fc47dc.PNG) | ![IMG_0299](https://user-images.githubusercontent.com/2602313/133191756-82bfb3f7-f91c-4f24-8f84-8a1ed3777ada.PNG) | ![IMG_0300](https://user-images.githubusercontent.com/2602313/133191773-b021cbc4-7369-4c4b-9b53-2f30bf730f45.PNG)

----------------

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.31 (21.9.8.16)` via the following STR/Cases:

* ensured that https://ipv6.google.com loaded without any issues (IPv6)
* ensured that https://www.v6.facebook.com loads without any issues (IPv6)
* ensured that https://www.google.com loads without any issues (IPv4)
* ensured that https://www.facebook.com loads without any issues (IPv4)

**`IPv6 Supported`** | **`Google (IPv6)`** | **`FB (IPv6)`**
-----------------------|----------------------|-----------------
![IMG_0597](https://user-images.githubusercontent.com/2602313/133193858-ba3f02c7-a192-4dc0-86f7-2240deddb982.PNG) | ![IMG_0595](https://user-images.githubusercontent.com/2602313/133193870-3d2e0acc-d145-47c7-95a7-c06e0057f19f.PNG) | ![IMG_0596](https://user-images.githubusercontent.com/2602313/133193888-15c83326-8b5b-4c0e-b069-8458be530806.PNG)

----------------

Verification **PASSED** on `iPhone 6s+` running `iOS 13.6` using `1.31 (21.9.13.20)` via the following STR/Cases:

* ensured that https://ipv6.google.com loaded without any issues (IPv6)
* ensured that https://www.v6.facebook.com loads without any issues (IPv6)
* ensured that https://www.google.com loads without any issues (IPv4)
* ensured that https://www.facebook.com loads without any issues (IPv4)

**`IPv6 Supported`** | **`Google (IPv6)`** | **`FB (IPv6)`**
-----------------------|----------------------|-----------------
![IMG_0190](https://user-images.githubusercontent.com/2602313/133196255-8b2107c4-fcaa-42d8-bdf2-01f82fbe3551.PNG) | ![IMG_0188](https://user-images.githubusercontent.com/2602313/133196262-b4625424-b266-4688-a9fb-75ad627802cb.PNG) | ![IMG_0189](https://user-images.githubusercontent.com/2602313/133196276-2758a08b-0fb3-41ec-86ad-614a8b99b891.PNG)

**Comment by Brandon-T** [comment]
`https://[2a04:4e42:600::288]` won't work because the IP Address doesn't resolve. The browser will attempt to go to that website and timeout eventually. That is the IPv6 of `brave.com`.

Other websites configured correctly will work though :)
