### ISSUE TITLE
Reopening new tabs increase app memory a lot

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3867]
### Steps to Reproduce 
  1. Open a tab 
  2. Close a tab, open new tab
  3. Repeat 10 times

**Actual result:** 
A lot of memory is used

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Marking as QA/No as this one requires building the code and testing.
