### ISSUE TITLE
Google OAuth will drop WKWebView support.

### ISSUE THREAD

**Issue by actow** [brave/brave-ios#3871]
WKWebView support will be dropped in Sep 2021. 

See details here

https://developers.googleblog.com/2021/06/upcoming-security-changes-to-googles-oauth-2.0-authorization-endpoint.html

**Comment by Brandon-T** [comment]
Hi, thanks for the ticket and letting us know about this.

The documentation states they will drop support for embedded web-views, but it will open in the system's default browser (whichever that is).

Also note that Safari uses the same engine as WKWebView. Chrome iOS also uses WKWebView as Apple doesn't allow any other web engines to run on iOS.

There isn't really a way for them to ban WKWebView and that is why it says: "Apps **should**".
> Embedded webviews implementing or extending WKWebView, or the deprecated UIWebView, do not comply with Google's secure browser policy for its OAuth 2.0 Authorization Endpoint. Apps should allow general, third-party links to be handled by the default behaviors of the operating system, enabling a user's preferred routing to their chosen default web browser or another developer's preferred routing to its installed app through Universal Links. Apps may alternatively open general links to third-party sites in SFSafariViewController.

**Comment by iccub** [comment]
let's close for now
