### ISSUE TITLE
Switch app alert modal isn't dismissed when a new tab is opened via home screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3882]
### Description: 
Switch app alert modal isn't dismissed when a new tab is opened via home screen

### Steps to Reproduce 
  1. Visit `https://shaun.net/resources/test-phone-numbers/` and click on a number to trigger switch app alert
  2. Background app to homescreen 
  3. Long press on Brave icon on home screen and select new tab/new private tab
  4. Alert modal isn't dismissed 

**Actual result:** 

https://user-images.githubusercontent.com/17010094/124477070-7f479880-dd9b-11eb-8130-4d3ca3b1f25b.MP4

**Expected result:**
Should dismiss the alert modal if a new tab/new private tab is opened

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.28(21.7.2.17)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by Uni-verse** [comment]
Verification completed using build `version 1.36 (22.2.11.11)` `BraveCore 1.36.87 (98.0.4758.87)`

**PASSED** on `iPhone 12 Pro` / `iOS 15.1.1`
**PASSED** on `iPhone X` / `iOS 14.4.2`
**PASSED** on `iPad (7th Gen)` / `iPadOS 15.2.1`

- Switch App alert is dismissed when opening new tab from home page
- Switch App alert is dismissed when opening private tab from home page

https://user-images.githubusercontent.com/17885425/154163746-7aeccce4-f748-4b02-9f4a-7395c3750c1a.MP4
