### ISSUE TITLE
Quick Search Engine Bar is overlapping Safe-Area when keyboard is dismissed 

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#3884]
### Description: 

Quick Search Engine Bar is overlapping Safe-Area when keyboard is dismissed 

### Steps to Reproduce 
  1. Install 1.28 build
  2. Enter in URL bar to bring up Quick search engine bar 
  3. Dismiss the keyboard with using drag down gesture
  4. Check the Bar is overlapping with Safe-Are and button are hard to click 

**Actual result:** 

https://user-images.githubusercontent.com/6643505/124506034-d304b280-dd98-11eb-9512-f9ab73927b59.mp4

**Expected result:**

Properly align with Safe-Area bottom inset

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
All

**Device details:** 
Devices with Safe-Area

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.29(21.07.20.16)
- Verified steps from issue description
