### ISSUE TITLE
Browser crash when editing a favourite when a page is loaded

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3890]
### Description: 
Browser crash when editing a favourite when a page is loaded

### Steps to Reproduce 
  1. Clean install 1.28(21.7.5.14)
  2. Visit a page in a new tab
  3. Once page is loaded tap on URL bar and edit a favourite, browser crashes

**Actual result:** 

https://user-images.githubusercontent.com/17010094/124598666-c34ea200-de5c-11eb-8eb1-dca4ba915516.MP4

**Expected result:**
No crash just edit the existing favourite and retain it

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.27 onward

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @iccub

**Comment by GeetaSarvadnya** [comment]
Reproduced on iOS - 14.6 (iPhone 8) - Verified in 1.29 (21.7.29.17)

1. Open a website
2. Add website to favorite list
3. Remove/Edit the favorite
4. Brave crashes

**Comment by iccub** [comment]
Fixed in #3974
