### ISSUE TITLE
Update default browser notification to display device's iOS version

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3899]
### Description: 
This notification should show user's device version instead of hardcoding `iOS 14`
On code side this requires change in NSLocalized string, the number has to be replaced with a number placeholder.
Then in app we have to fetch device's iOS version, with iOS 14 minimum, since iOS 13 can't be set as a default

![File](https://user-images.githubusercontent.com/6950387/124835044-fa1dd880-df80-11eb-85dd-69271f2bd547.jpg)

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Shivakumar-SG** [comment]
Hey @iccub, I would like to take up this issue!
will you please give me a head start?

**Comment by iccub** [comment]
sure @Shivakumar-SG, find this notification in app, see how is it implemented.
You have to change it from a hardcoded string to a string with a placeholder,

Then this placeholder will be number of device's iOS version, so for iOS 14 it will be 14, for 15=15 etc.

**Comment by Shivakumar-SG** [comment]
Hey, I'm kinda new to Xcode and my Xcode app kept crashing and I don't know why. And adding to that, I know git ignores the entire `Local` directory but I don't have an Apple team ID so, I'm not taking this issue on and letting the community know that this issue is still up for grabs!
Thank you.

**Comment by iccub** [comment]
thank you for trying @Shivakumar-SG :)
You can get apple id for free now btw

**Comment by ionutivan** [comment]
@iccub If nobody is on this issue yet, I would like to take it. Thanks

**Comment by iccub** [comment]
@ionutivan I believe one user has started work on it already, but this PR requires changes
https://github.com/brave/brave-ios/pull/3911

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.32(21.10.6.16)
- Verified default browser notification shows device iOS Version

iPhone 7+ (iOS 14.8) | iPhone XR (iOS 15.0.1) | iPad Pro (iOS 15.1 Beta 3)
-- | -- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/136565975-3016786f-c7f3-4942-9f98-a066455a03c0.png> | <img width=240 src=https://user-images.githubusercontent.com/17010094/136567034-80d7066a-297e-432d-a3e1-33f9f43aec84.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/136565998-0b024f72-93cc-473f-a812-0862bb63a3d0.png>
