### ISSUE TITLE
Internal Issue #789 (Search Engine)

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3900]
### Description: 
Please implement https://github.com/brave/internal/issues/789

**Comment by iccub** [comment]
Can this wait for 1.29?

**Comment by kjozwiak** [comment]
Created https://github.com/brave/brave-ios/issues/3906 as a follow up.

**Comment by srirambv** [comment]
Verification passed on iPhone XR (iOS 13.5) / iPhone 7+ (iOS 14.5.1)/ iPad Pro (iOS 14.6) running 1.28(21.7.9.13)
- Verification notes [here](https://github.com/brave/internal/issues/789#issuecomment-878066365)
