### ISSUE TITLE
The preview for URLs and search queries is always in lowercase (problematic for case sensitive links)

### ISSUE THREAD

**Issue by sabogalc** [brave/brave-ios#3901]
### Have you searched for similar issues on the repository?
```
Before submitting this issue, please visit our wiki for common ones: https://github.com/brave/browser-ios/wiki
For more, check out our community site: https://community.brave.com/
```
Yes, I did searches for "case sensitive", "lower case", and "search bar" and I could not find a ticket that describes this issue. I didn't have it in me to comb through all 371 open tickets.

### Description: 
When typing in a URL or search query, the preview text is always in lowercase, and this can be problematic for case sensitive links (such as https://bit.ly ones)

### Steps to Reproduce 
  1. Type a URL or search query that contains capital letters on Brave iOS
  2. See that the preview below the search bar is in all lowercase

**Actual result:** 
![IMG_0818](https://user-images.githubusercontent.com/53708281/124858601-64804a00-df7c-11eb-9ad8-93a4c21cc94e.PNG)

**Expected result:**
![IMG_0818](https://user-images.githubusercontent.com/53708281/124858848-d193df80-df7c-11eb-8ba7-a4efcb0dc48d.PNG)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always happens, easily reproduced

**Brave Version:** 
v1.27.1(21.6.22.16)

**Device details:** 
iPhone 6s iOS 14.6

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Link in question - https://bit.ly/3ADthXI

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.31(21.9.14.15)
- Verified typed-in URL's retain letter casing
- Verified selecting the auto-suggested site loads the actual page that is intended 

iPhone XR (iOS 13.5) | iPhone 7+ (iOS 14.8) | iPad Pro (iOS 15)
-- | -- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/133412503-3ad1f4b8-091a-4d12-85b1-02f657f5bfdf.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/133412457-3958eed5-02a4-44af-8eed-8be2d30e314d.png> |  <img width=400 src=https://user-images.githubusercontent.com/17010094/133412752-0f2be632-1849-4fac-9225-85d065f6efe1.png>
