### ISSUE TITLE
Internal Issue #789 (Search Engine) - follow up to #3900

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#3906]
See https://github.com/brave/internal/issues/789#issuecomment-876892286.

**Comment by srirambv** [comment]
Verification passed on iPhone XR (iOS 13.5) / iPhone 7+ (iOS 14.5.1)/ iPad Pro (iOS 14.6) running 1.28(21.7.9.13)
- Verification notes [here](https://github.com/brave/internal/issues/789#issuecomment-878066365)
