### ISSUE TITLE
Settings menu items aren't all left-aligned properly

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#3909]
### Description: 
Settings menu items aren't all left-aligned properly

### Steps to Reproduce 
  1. launch Brave
  2. tap on the `...` menu item at the bottom
  3. tap on `Settings`
  4. look at the left-alignment of the menu options

**Actual result:** 

`Playlist`, `Search Engines`, and `Sync` don't line up.

![ocd-line](https://user-images.githubusercontent.com/387249/125115273-f5037b00-e09f-11eb-9f6c-9075b57e31c9.png)

**Expected result:**

All menu items should be left-aligned together.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
`1.28 (21.7.9.13)`

**Device details:** 
iPhone 6s

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.20(21.8.5.11)
- Verified menu items are properly left aligned

iPhone XR (iOS 13.5) | iPhone 7+ (iOS 14.5.1)
-- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/128345332-86ef0390-c1ed-4b49-8ed3-22744a7c5b66.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/128345344-5662850e-320e-423d-93cc-09c927324be9.png>

Verification failed on iPad. Logged follow up issue  #4004
