### ISSUE TITLE
Custom search engines url should not be capped at 150 characters

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3914]
### Description: 
See this post https://www.reddit.com/r/brave_browser/comments/ohvl22/150_character_limit_for_custom_search_engines_in/

Some users store their SE preferences as url params which can get pretty long

### Steps to Reproduce 
  1. Set startpage settings, they are stored as url params
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.29(21.07.20.16)
- Verified able to add a custom search engine with more than 150 characters
------------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.29(21.07.20.16)
- Verified able to add a custom search engine with more than 150 characters
------------
Verification passed on iPad Pro with iOS 14.6 running 1.29(21.07.20.16)
- Verified able to add a custom search engine with more than 150 characters
