### ISSUE TITLE
Refactor new bookmarks & history singleton APIs

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3916]
The brave-core APIs `BookmarksAPI` and `HistoryAPI` are no longer singletons from this PR: https://github.com/brave/brave-ios/pull/3703 however the usage in brave-ios still accesses them via `UIApplication.shared.delegate` rather than have the dependencies passed to the browser and required components

We should refactor this to use proper dependency management rather than access it via the AppDelegate from anywhere in the app. Also the `Bookmarksv2` and `Historyv2` models should become simple models and leave all of the actual CRUD to the `*API` classes which already define the methods needed.

## Test Case

Ensure Bookmarks/History sync works as usual

**Comment by srirambv** [comment]
Closing and marking as verified as #4385 & #4387 is verified
