### ISSUE TITLE
Use device authentication for browser lock feature

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3921]
Goal is the move the current custom browser PIN feature to use the users device authentication (including their device PIN)

Spec: `iOS Pin Upgrade`

**Comment by srirambv** [comment]
<details>
<summary>Verification passed on iPhone XR with iOS 13.5 running 1.29(21.07.28.22)</summary>

- Verified test plan from #3922 

**Migration**
- Verified with custom pin setup, upgrading brings up the migration modal before any other modal is being shown
- Verified able to successfully migrate to using iPhone unlock feature
- Verified able to successfully disable browser lock feature
- Verified migration works fine on all 3 scenarios 
  - User has custom PIN and device PIN - Shows migration screen, feature is enabled
  - User has custom PIN and no device PIN - Shows migration screen, feature is disabled
  - User has no custom PIN - No migration screen is shown but setting is updated to `Browser Lock` and set to disabled
 
![image](https://user-images.githubusercontent.com/17010094/127488140-9dc53d42-e47c-435a-b6dd-b75bb728f5e1.png) | ![image](https://user-images.githubusercontent.com/17010094/127488165-5dcee815-156c-44ed-bcd2-053610450f4d.png) | ![image](https://user-images.githubusercontent.com/17010094/127492476-168ffabd-04dc-4b64-b64d-d7c98c549625.png)
-- | -- | --

**Clean Install**
- Verified on clean install no migration screen for Browser lock is shown
- Verified Browser lock is disabled by default on clean install
- Verified enabling Browser lock works fine with normal tabs and PB only

**Authentication Flow**
- Verified backgrounding the app hides the screen the next time the app app is opened via switcher
- Verified app contents (tabs preview) is not visible but shows a thick blur with lock screen icon
- Verified opening the app from background or fresh launch shows authentication immediately 
- Verified cancelling the authentication keeps the app in blurred screen with Unlock button 
- Verified entering an invalid passcode doesn't unlock. Only unlocks with device passcode
- Verified removing biometrics from device forces authentication with pin only
- Verified disabling device pin still allows to open Brave with the feature still being enabled

![image](https://user-images.githubusercontent.com/17010094/127488194-76a273f9-cc49-4999-b814-9bb89774f002.png) | ![image](https://user-images.githubusercontent.com/17010094/127488206-2df74a02-816e-4644-a1dc-38223274ae6d.png) | ![image](https://user-images.githubusercontent.com/17010094/127488226-6d1fdf48-e4f3-4807-b017-8dd5aabefff9.png)
-- | -- | --

</details>

-------------

<details>
<summary>Verification passed on iPhone 7+ with iOS 14.5.1 running 1.29(21.07.28.22)</summary>

- Verified test plan from #3922 

**Migration**
- Verified with custom pin setup, upgrading brings up the migration modal before any other modal is being shown
- Verified able to successfully migrate to using iPhone unlock feature
- Verified able to successfully disable browser lock feature
- Verified migration works fine on all 3 scenarios 
  - User has custom PIN and device PIN - Shows migration screen, feature is enabled
  - User has custom PIN and no device PIN - Shows migration screen, feature is disabled
  - User has no custom PIN - No migration screen is shown but setting is updated to `Browser Lock` and set to disabled
 
![image](https://user-images.githubusercontent.com/17010094/127488022-9d720248-6d6c-4f83-a176-9a90d307bf7f.png) | ![image](https://user-images.githubusercontent.com/17010094/127488038-2903af5d-710d-425b-8d6e-5a3a800fc951.png) | ![image](https://user-images.githubusercontent.com/17010094/127493145-1bc27af6-554a-4471-8c2c-fdcc0f8185ee.png)
-- | -- | --

**Clean Install**
- Verified on clean install no migration screen for Browser lock is shown
- Verified Browser lock is disabled by default on clean install
- Verified enabling Browser lock works fine with normal tabs and PB only

**Authentication Flow**
- Verified backgrounding the app hides the screen the next time the app app is opened via switcher
- Verified app contents (tabs preview) is not visible but shows a thick blur with lock screen icon
- Verified opening the app from background or fresh launch shows authentication immediately 
- Verified cancelling the authentication keeps the app in blurred screen with Unlock button 
- Verified entering an invalid passcode doesn't unlock. Only unlocks with device passcode
- Verified removing biometrics from device forces authentication with pin only
- Verified disabling device pin still allows to open Brave with the feature still being enabled

![image](https://user-images.githubusercontent.com/17010094/127487981-9416fb78-b15c-469d-91a3-d78d54da55bf.png) | ![image](https://user-images.githubusercontent.com/17010094/127487935-d1f3aa12-d623-458f-9da6-8f5794ed91d7.png) | ![image](https://user-images.githubusercontent.com/17010094/127487951-dd54be6d-e8db-46be-ac37-7c75515cada8.png) | ![image](https://user-images.githubusercontent.com/17010094/127488003-44263c24-0801-4dac-859a-78e24fb95c71.png)
-- | -- | -- | --

</details>

---------------

<details>
<summary>Verification passed on iPad Pro with iOS 14.6 running 1.29(21.07.28.22)</summary>

- Verified test plan from #3922 

**Migration**
- Verified with custom pin setup, upgrading brings up the migration modal before any other modal is being shown
- Verified able to successfully migrate to using iPhone unlock feature
- Verified able to successfully disable browser lock feature
- Verified migration works fine on all 3 scenarios 
  - User has custom PIN and device PIN - Shows migration screen, feature is enabled
  - User has custom PIN and no device PIN - Shows migration screen, feature is disabled
  - User has no custom PIN - No migration screen is shown but setting is updated to `Browser Lock` and set to disabled
 
![image](https://user-images.githubusercontent.com/17010094/127489504-d223d588-092e-4c3e-b821-6694235f5b65.png) | ![image](https://user-images.githubusercontent.com/17010094/127489522-b45b1199-cd72-435f-8d92-16915ee5c4f2.png) | ![image](https://user-images.githubusercontent.com/17010094/127494048-aa3db482-4f6b-43e8-bbcd-f0de9e206cd7.png)
-- | -- | --

**Clean Install**
- Verified on clean install no migration screen for Browser lock is shown
- Verified Browser lock is disabled by default on clean install
- Verified enabling Browser lock works fine with normal tabs and PB only

**Authentication Flow**
- Verified backgrounding the app hides the screen the next time the app app is opened via switcher
- Verified app contents (tabs preview) is not visible but shows a thick blur with lock screen icon
- Verified opening the app from background or fresh launch shows authentication immediately 
- Verified cancelling the authentication keeps the app in blurred screen with Unlock button 
- Verified entering an invalid passcode doesn't unlock. Only unlocks with device passcode
- Verified removing biometrics from device forces authentication with pin only
- Verified disabling device pin still allows to open Brave with the feature still being enabled

![image](https://user-images.githubusercontent.com/17010094/127489586-304aaee9-468e-4196-bdc2-40b04a7d8ad8.png) | ![image](https://user-images.githubusercontent.com/17010094/127489568-245b6d97-4dbb-49f0-8e01-e1bd09cf174f.png) | ![image](https://user-images.githubusercontent.com/17010094/127489722-c40946e2-ce20-45d6-af6a-5abca39ca172.png) | ![image](https://user-images.githubusercontent.com/17010094/127489788-e82426bb-063d-4782-9849-c4563e4ae5a4.png)
-- | -- | -- | --

</details>

--------

Encountered #3981

**Comment by ghost** [comment]
Hello, I use the Brave browser on iPad and I would like to leave some feedback regarding this feature in the latest update (1.29).

While I do believe that using the same password as my device for the app is easier to set up, for me it kind of defeats the purpose of having a passcode lock for the app in the first place. This is because I used the passcode to protect my data from people who do know my device's passcode. Now the only case in which the new passcode lock implementation will help will be if I leave my device unlocked and someone takes it and decides to look through it, which I find unlikely.

I would like to see in future versions an option to select a passcode different from that of my device, like it used to be.

I already posted feedback about this change on the brave community forum on this thread, https://community.brave.com/t/passcode-behavior-in-new-ios-version/271631, where I had a lengthy conversation and was told in the end that it would be a good idea to also post my feedback here on Github. Hopefully it is useful to you.
