### ISSUE TITLE
[Playlist] - Sometimes adding media embedded in an iFrame won't work.

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#3923]
### Description: 
Sometimes adding media through gesture recognizer won't work when embedded in an iFrame.

### Steps to Reproduce 
  1. Go to: https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_video
  2. Change: `<video width="400" controls>` to `<video width="400" controls playsinline>`
  3. Hit "Run" button.
  4. Long-Press on the video to add it to playlist.

**Actual result:** 
- Video won't be added to playlist. 
- Popup won't show "Add to Brave Playlist".

**Expected result:**
- Should show popup to "Add to Brave Playlist".

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.27

**Device details:** 
Any

**Website problems only:**
N/A

### Additional Information
Only happens for videos where the content offset of the frame itself is > 0 in either direction relative to the current page.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.29(21.07.20.16)
- Verified steps from issue description
- Verified able to add videos to playlist 

https://user-images.githubusercontent.com/17010094/127185036-54257470-ea36-4891-9b24-2a73d2b74078.MP4

-------------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.29(21.07.20.16)
- Verified steps from issue description
- Verified able to add videos to playlist 

https://user-images.githubusercontent.com/17010094/127186944-84fcfc12-9c7e-4b15-ad3b-5bb96187ef4d.MP4


--------------
Verification passed on iPad Pro with iOS 14.6 running 1.29(21.07.20.16)
- Verified steps from issue description
- Verified able to add videos to playlist 

https://user-images.githubusercontent.com/17010094/127186634-44eb70a0-3513-4baf-8a5e-a3b296e8fee8.MP4
