### ISSUE TITLE
App launches in light mode when Private Browsing Only mode is enabled

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#3936]
### Description: 

When you have Private Browsing Only mode enabled the app is currently restricted to dark mode, however on a fresh launch it will be in light mode anyways

### Steps to Reproduce 
  1. Enable PBO
  2. Kill app from app tray
  3. Re-launch app

**Actual result:** Launches in light mode
**Expected result:** Launch in dark mode since PBO only supports dark mode currently
**Reproduces how often:** Easily
**Brave Version:** Live (1.28)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.30(21.8.5.11)
- Verified PB only mode launches on dark mode as expected 

https://user-images.githubusercontent.com/17010094/128358277-08e8ef10-b605-4c30-8bc6-e36273561be6.MP4

----------
Verification passed on iPhone 7+  with iOS 14.5.1 running 1.30(21.8.5.11)
- Verified PB only mode launches on dark mode as expected 

https://user-images.githubusercontent.com/17010094/128358682-2d00d3fc-4dbf-49ed-9504-05fafc1c4c01.MP4

------------
Verification passed on iPad Pro with iOS 14.6 running 1.30(21.8.5.11)
- Verified PB only mode launches on dark mode as expected 

https://user-images.githubusercontent.com/17010094/128363547-b8621d94-c10a-4d21-82b4-12b41c23406e.MP4
