### ISSUE TITLE
Editing a bookmark scrolls the list to the top

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3938]
### Steps to Reproduce 
  1. Have many bookmarks
  2. Scroll down, edit a bookmark

**Actual result:** 
Goes to the top of the list after edit

**Expected result:**
Should remember edit position.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Mickey242** [comment]
Same issue, tried updating Brave, issue continues.

**Comment by azwafa** [comment]
I'm also experiencing this behavior on Version 1.31.91. Editing, moving, or clicking on bookmarks causes abrupt jumping to the top of the list.

**Comment by iccub** [comment]
I will move that up in terms of priority, hope to fix it soon

**Comment by themew** [comment]
Would love to see this fixed so Brave remembers where in the bookmark list I stopped scrolling so I can resume from that location in the list.  Starting back up at the top each time I open a long bookmark list to get back to where I was takes forever...

**Comment by cuba** [comment]
I could not reproduce this issue. I tested 1.35.1 (iOS 15.2) on an iPhone 13 Pro, iPhone 13 Pro (simulator) and iPad Pro 5th Generation. Could we get someone to verify if this issue still exists or provide more specific device/OS versions.

**Comment by iccub** [comment]
Can't repro either, I'll close this ticket to be re-verified by QA

**Comment by Uni-verse** [comment]
Doesn't repro for me using 1.37 (22.3.11.18)

iOS 15 & 14

**Comment by Uni-verse** [comment]
Verified **no repro** using beta `1.37 (22.3.23.17) on iOS 15 & 14`

Test Devices: 
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad (7th Gen) | iOS 15.2

Test Scenario: 

1. Have many bookmarks
2. Scroll down a bit
3. Edit bookmark in list
4. Save edit 
5. Observe bookmark list position
