### ISSUE TITLE
Implement screentime

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3939]
### Description: 
See this API https://developer.apple.com/documentation/screentime/stwebpagecontroller
It may be possible to block restricted pages based on screentime limits

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by saltedlolly** [comment]
https://developer.apple.com/documentation/screentime/

**Comment by anthonypkeane** [comment]
This would be great @iccub

**Comment by iccub** [comment]
@anthonypkeane Chromium added this framework to their builds, we can see if they utilize it in Chrome and see what can we do with it

**Comment by Klingefjord** [comment]
I would love this so much! 🙏

**Comment by basilweibel** [comment]
This is my number one wish for Brave!

**Comment by saltedlolly** [comment]
Why is this blocked? I'm ever hopeful this will be added

**Comment by tadasajon** [comment]
I would really like this Screen Time feature on Brave -- I'm going to have to use Screen Time to block all non-Safari browsers until this feature is added.

**Comment by saltedlolly** [comment]
Is there any progress on this? It's really frustrating that it does not work when other browsers have implemented it.

**Comment by Abuzeid1** [comment]
screentime is currently being implemented under experimental flag.

Go to brave://flags/
enable Screen Time

**Comment by saltedlolly** [comment]
@Abuzeid1 Does this work on iOS? I know it supports macOS this way, but iOS is that I am really interested in.

**Comment by bgala** [comment]
The screen time flag does not work for me in Private Browsing mode... is there a way to fix this?

**Comment by iccub** [comment]
We still work to deliver it sorry.
I've run into some random crashes and have to investigate why is that happening

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using version `1.58 (23.9.26.17)`

Using test plan in https://github.com/brave/brave-ios/pull/7983#issue-1871478956

- Verified websites open in brave are being tracked under Screen Time activity when `Enable Screen Time` is on
- Verified that setting a time limit for a webpage in screen time iOS settings will restrict access to that page when limit is met.
- Verified notifications will be shown when brave is open for Screen Time settings.
- Verified disabling `Enable Screen Time` will allow access to web page after limit has been met.
- Verified time limits will work in private tabs as well as private browsing mode (after limit is met).
- Verified that webpages are not tracked in private browsing mode or private tabs.

Example | Example | Example | Example | Example | Example | Example
-|-|-|-|-|-|-
![IMG_3537](https://github.com/brave/brave-ios/assets/17885425/5599a3b7-bc44-4241-8697-cbcd74e3ca5d) | ![IMG_3530](https://github.com/brave/brave-ios/assets/17885425/cba2fe0b-10c1-4b7b-8d85-edcea3eaa7bb) | ![IMG_3531](https://github.com/brave/brave-ios/assets/17885425/d002c130-af78-46fb-a269-99824ba1a91f) | ![IMG_3532](https://github.com/brave/brave-ios/assets/17885425/c3c6ff81-7f65-4572-a697-07acedc5053e) | ![IMG_3533](https://github.com/brave/brave-ios/assets/17885425/62d5ca9e-6db1-4b8d-85df-8bbc574223f4) | ![IMG_3534](https://github.com/brave/brave-ios/assets/17885425/46e3c4ac-f5df-4af4-8053-c252e0814350) | ![IMG_3535](https://github.com/brave/brave-ios/assets/17885425/274c909c-095e-421d-b575-d77a3b1a409d)
