### ISSUE TITLE
Selecting a Bookmark should close Settings Menu

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#3950]
### Description: 

Opening a bookmark should also dismiss the Settings If the bookmark screen is presented through Settings-Menu.

### Steps to Reproduce 
  1. Open Settings Menu
  2. Select Bookmark
  3. Navigate one of the folders and click a bookmark

**Actual result:** 

Menu Screen is not dismissed

https://user-images.githubusercontent.com/6643505/126397596-35c71f3a-5a28-4f41-a72d-2eacc381a431.MP4

**Expected result:**

Menu should be dismissed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Easily reproduced.

**Brave Version:** 
1.29 (21.7.20.16)

**Device details:** 
Any iPhone

**Website problems only:**
- did you check with Brave Shields down? N.A
- did you check in Safari/Firefox (WkWebView-based browsers)?  N .

### Additional Information
None

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.30(21.8.5.11)
- Verified menu is auto closed when a bookmark is selected from menu

https://user-images.githubusercontent.com/17010094/128356320-80078cfa-8495-4e1c-9e8e-15d56d758b2b.MP4

---------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.30(21.8.5.11)
- Verified menu is auto closed when a bookmark is selected from menu

https://user-images.githubusercontent.com/17010094/128356427-7cf21ecd-1a6b-478a-8bec-e1df06ca843c.MP4

----------
Verification passed on iPad Pro with iOS 14.6 running 1.30(21.8.5.11)
- Verified menu is auto closed when a bookmark is selected from menu

https://user-images.githubusercontent.com/17010094/128356624-132cb496-80f5-439c-ba3f-adf83f1857ea.MP4
