### ISSUE TITLE
Duck Duck Issue on iOS

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3953]
### Description: 
Review: https://appfigures.com/reviews/42132121512L3HSnzzQ5wq2SFAieRhqvZA?lang=en

Can we please investigate 

>Since a recent update DuckDuckGo go doesn’t work in the Brave app when you try to search for something using the search bar aka where you’d type a website address into and yes DuckDuckGo is/has been my default search engine for ages now. All that happens now is the DuckDuckGo page comes up without any results and even if I try searching for something in the search bar on the actual DuckDuckGo website itself, there’s still no results and the page is blank…where’s me DuckDuckGone?

**Comment by iccub** [comment]
seems to work for me
