### ISSUE TITLE
Unable to toggle Allow Cross-Website Tracking via system Settings

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#3954]
### Description: 
Unable to toggle Allow Cross-Website Tracking via system Settings

This was reported in https://old.reddit.com/r/brave_browser/comments/oooras/on_the_brace_ios_app_crosswebsite_tracking_is/

### Steps to Reproduce 
  1. have either `Brave` or `Safari` set as default (neither affect this, for me)
  2. open `Settings` > `Brave`
  3. at the bottom, try to toggle `Allow Cross-Website Tracking` `off`/`on`

**Actual result:** 

Unable to toggle `Allow Cross-Website Tracking`.

https://user-images.githubusercontent.com/387249/126550665-a138c54a-7d06-4984-baac-a71adc742e7f.MP4

**Expected result:**

Should be able to toggle `Allow Cross-Website Tracking` `off`/`on`.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100% (for me, not others)

**Brave Version:** 
`v1.28 (21.7.9.13)`

**Device details:** 
iPhone 8 Plus, iOS `15.0 public beta (19A5297e)`

**Comment by stephendonner** [comment]
This also doesn't work -- same results, unable to toggle `on`/`off` for Safari, Chrome, and Firefox, even with those set and unset as browser defaults, within iOS.

**Comment by Brandon-T** [comment]
Bug is an iOS bug as we do not control any settings outside the application. This is implemented on the OS level in WebKit which runs outside our Brave-iOS process and doesn't provide an option for us to enable or disable it :)

IIRC, similar bug happened in earlier versions of iOS 14 for App-Tracking Protection as well.
