### ISSUE TITLE
iPad Keyboard Improvements

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#3956]
### Description: 

User Review
>Humble request to see two fixes on an iPad Pro with a keyboard. When you press Cmd+T to open a new tab, have the cursor go to the location bar like it does on the desktop. When you press Cmd+F to search the page, have the cursor go to the search box. Right now you have to manually press into each.

**Comment by KacperWybranski** [comment]
Cmd+T part solved in #4140

**Comment by iccub** [comment]
Closing as a duplicate,
For focusing on url bar there is a `CMD + L` command
