### ISSUE TITLE
Quick search engine bar is missing

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3959]
### Description: 
Quick search engine bar is missing on iOS 13

### Steps to Reproduce 
  1. Clean install 1.29 build
  2. Focus on URL bar to bring up the keyboard
  3. Doesn't show Quick SE bar 

**Actual result:** 

https://user-images.githubusercontent.com/17010094/126992299-ad26bc93-c8eb-4838-91fd-b3b07859798e.MP4

**Expected result:**
Show Quick SE bar when focused on URL bar

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.29(21.07.20.16)

**Device details:** 
iPhone XR (iOS 13.5)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by iccub** [comment]
We are not able to reproduce using real 13.7 device as well as 13.5 simulators

**Comment by srirambv** [comment]
Issue still repro's on iPhone X device with iOS 15. Reopening the issue for further investigation

**Comment by soner-yuksel** [comment]
I figure out the reason behind why this is happening so I am removing the blocked label.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.35 (22.1.24.16)`

* verified the STR/Cases outlined via https://github.com/brave/brave-ios/issues/3959#issue-952879669
* ensured that the icons are clear/visible
* ensured that the `Quick Search` bar is being displayed when a user types into the URL/omnibox
* ensured that `Bing`, `DDG`, `Ecosia`, `Google`, `Qwant` & `Startpage` are enabled by default under `Settings` -> `Search Engines` -> `Quick-Search Engines`
* ensured that the correct order is being displayed when `Quick-Search Engines` was re-arranged via `Settings`
* ensured that tapping on the `Search` icon via the `Quick-Search` bar opens the `Search` section under `Settings`
* ensured that disabling all the search engines `Settings` removes the `Quick-Search` when typing into the URL/omnibox
* ensured that `Quick-Search` is still displayed when there's only a single search engine enabled
* ensured that `Quick Search` searches appear under `Recent Searches`
  * `brave on google.com`
  * `brave on ecosia.org`
  * `brave on duckduckgo.com`
  * `brave on bing.com`
  * `brave on qwant.com`
  * `brave on startpage.com`
* ensured that `brave` was being used/credited when searching as per the following:
  * `https://www.bing.com/search?q=test&pc=MOZB&form=MOZMBA`
  * `https://duckduckgo.com/?q=test&t=brave&ia=web`
  * `https://www.ecosia.org/search?q=test&tt=d188c5da&addon=brave`
  * `https://www.google.com/search?q=test&ie=utf-8&oe=utf-8`
  * `https://www.qwant.com/?q=test&client=brz-brave&t=web`
  * `https://www.startpage.com/do/search?q=test&segment=startpage.brave`

**`Example`** | **`Example`** | **`Example (Order changed)`** | **`Example (Disabled)`**
----------------|----------------|----------------|----------------
![IMG_0523](https://user-images.githubusercontent.com/2602313/150842737-9eb03c61-b200-4a9e-8161-381c5180b04d.png) | ![IMG_0524](https://user-images.githubusercontent.com/2602313/150842750-a6f543ef-283d-410d-816b-e78511e4de66.png) | ![IMG_0526](https://user-images.githubusercontent.com/2602313/150844623-cdfbc7f5-b41f-430f-9996-4446fa46e055.png) | ![IMG_0527](https://user-images.githubusercontent.com/2602313/150844711-845e3b06-bd55-4dc7-99e1-98f0faffed47.png)

---------------------------

Verification **PASSED** on `iPhone 11` running `iOS 14.7.1` using `1.35 (22.1.24.16)`

* verified the STR/Cases outlined via https://github.com/brave/brave-ios/issues/3959#issue-952879669
* ensured that the icons are clear/visible
* ensured that the `Quick Search` bar is being displayed when a user types into the URL/omnibox
* ensured that `Bing`, `DDG`, `Ecosia`, `Google`, `Qwant` & `Startpage` are enabled by default under `Settings` -> `Search Engines` -> `Quick-Search Engines`
* ensured that the correct order is being displayed when `Quick-Search Engines` was re-arranged via `Settings`
* ensured that tapping on the `Search` icon via the `Quick-Search` bar opens the `Search` section under `Settings`
* ensured that disabling all the search engines `Settings` removes the `Quick-Search` when typing into the URL/omnibox
* ensured that `Quick-Search` is still displayed when there's only a single search engine enabled
* ensured that `Quick Search` searches appear under `Recent Searches`
  * `brave on google.com`
  * `brave on ecosia.org`
  * `brave on duckduckgo.com`
  * `brave on bing.com`
  * `brave on qwant.com`
  * `brave on startpage.com`
* ensured that `brave` was being used/credited when searching as per the following:
  * `https://www.bing.com/search?q=test&pc=MOZB&form=MOZMBA`
  * `https://duckduckgo.com/?q=test&t=brave&ia=web`
  * `https://www.ecosia.org/search?q=test&tt=d188c5da&addon=brave`
  * `https://www.google.com/search?q=test&ie=utf-8&oe=utf-8`
  * `https://www.qwant.com/?q=test&client=brz-brave&t=web`
  * `https://www.startpage.com/do/search?q=test&segment=startpage.brave`

**`Example`** | **`Example`** | **`Example (Order changed)`** | **`Example (Disabled)`**
----------------|----------------|----------------|----------------
![IMG_3752](https://user-images.githubusercontent.com/2602313/150851949-21722f40-d34e-47da-af83-58dee8eeb692.png) | ![IMG_3753](https://user-images.githubusercontent.com/2602313/150851983-cfdf020e-2531-49dc-a1e5-21ee87e833fb.png) | ![IMG_3754](https://user-images.githubusercontent.com/2602313/150851996-30830eed-a470-4ea5-a767-9b752963f498.png) | ![IMG_3755](https://user-images.githubusercontent.com/2602313/150852009-aa09972a-270c-4ef5-af19-cdcd12db351a.png)

---------------------------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.2` using `1.35 (22.1.24.16)`

* verified the STR/Cases outlined via https://github.com/brave/brave-ios/issues/3959#issue-952879669
* ensured that the icons are clear/visible
* ensured that the `Quick Search` bar is being displayed when a user types into the URL/omnibox
* ensured that `Bing`, `DDG`, `Ecosia`, `Google`, `Qwant` & `Startpage` are enabled by default under `Settings` -> `Search Engines` -> `Quick-Search Engines`
* ensured that the correct order is being displayed when `Quick-Search Engines` was re-arranged via `Settings`
* ensured that tapping on the `Search` icon via the `Quick-Search` bar opens the `Search` section under `Settings`
* ensured that disabling all the search engines `Settings` removes the `Quick-Search` when typing into the URL/omnibox
* ensured that `Quick-Search` is still displayed when there's only a single search engine enabled
* ensured that `Quick Search` searches appear under `Recent Searches`
  * `brave on google.com`
  * `brave on ecosia.org`
  * `brave on duckduckgo.com`
  * `brave on bing.com`
  * `brave on qwant.com`
  * `brave on startpage.com`
* ensured that `brave` was being used/credited when searching as per the following:
  * `https://www.bing.com/search?q=test&pc=MOZB&form=MOZMBA`
  * `https://duckduckgo.com/?q=test&t=brave&ia=web`
  * `https://www.ecosia.org/search?q=test&tt=d188c5da&addon=brave`
  * `https://www.google.com/search?q=test&ie=utf-8&oe=utf-8`
  * `https://www.qwant.com/?q=test&client=brz-brave&t=web`
  * `https://www.startpage.com/do/search?q=test&segment=startpage.brave`

**`Example`** | **`Example`** | **`Example (Order changed)`** | **`Example (Disabled)`**
----------------|----------------|----------------|----------------
![IMG_0339](https://user-images.githubusercontent.com/2602313/150867263-22375526-cfdd-4a97-9635-29810b689d17.png) | ![IMG_0340](https://user-images.githubusercontent.com/2602313/150867273-d635eea2-7685-42a6-85a4-0244cb58f233.png) | ![IMG_0341](https://user-images.githubusercontent.com/2602313/150867277-9c711d70-4e4a-4060-ae30-d347a2280846.png) | ![IMG_0342](https://user-images.githubusercontent.com/2602313/150867285-d9c5790f-48af-4894-b244-fccb45d0a125.png)

**Comment by kjozwiak** [comment]
Created the following issues while running through the above:

* https://github.com/brave/brave-ios/issues/4890
* https://github.com/brave/brave-browser/issues/20659
* https://github.com/brave/brave-ios/issues/4891
