### ISSUE TITLE
Siri Shorcuts should read Siri Shortcuts

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#3964]
### Steps to Reproduce 
  1. launch `Dev`
  2. tap on `Settings`
  3. look at `Siri Shorcuts`
  4. tap on `Siri Shorcuts`

**Actual result:** 

Spelled `Siri Shorcuts`

example | example
---------|---------
![Image from iOS](https://user-images.githubusercontent.com/387249/127202107-821bfe64-b0ff-4246-b716-8efba09276ec.png) | ![Image from iOS (1)](https://user-images.githubusercontent.com/387249/127202103-1947d040-9291-4fcf-b393-7d32f35b180d.png)

**Expected result:**

Should read `Siri Shortcuts`
**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 
`1.29 (21.7.20.15)`

**Device details:** 
iPhone 6s, iOS 14.7

**Comment by iccub** [comment]
This got fixed in https://github.com/brave/brave-ios/pull/3952 and will be available for testing in next build

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.29(21.07.28.9)
- Verified setting now reads `Siri Shortcuts`

![image](https://user-images.githubusercontent.com/17010094/127304432-d1a48321-189b-48e0-a901-2bd757c8450b.png) | ![image](https://user-images.githubusercontent.com/17010094/127304449-085bf57e-76d2-422d-a7fc-efa8bc9902f9.png)
-- | --
------------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.29(21.07.28.9)
- Verified setting now reads `Siri Shortcuts`

![image](https://user-images.githubusercontent.com/17010094/127304388-67cc7563-b97c-4d4f-8da3-703d069a01fd.png) | ![image](https://user-images.githubusercontent.com/17010094/127304404-a0f5334f-dfc3-4e60-89ff-52508d298f87.png)
-- | --
---------
Verification passed on iPad Pro with iOS 14.6 running 1.29(21.07.28.9)
- Verified setting now reads `Siri Shortcuts`

![image](https://user-images.githubusercontent.com/17010094/127304483-34fa2e94-c58a-40c7-b048-c15de600b4be.png) | ![image](https://user-images.githubusercontent.com/17010094/127304532-29b5cb13-44fd-43b0-88c8-9b53add1f751.png)
-- | --
