### ISSUE TITLE
Inconsistent capitalization of Open a New Tab under Open Brave News heading

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#3965]
### Description: 
Inconsistent capitalization of Open a New Tab under Open Brave News heading

### Steps to Reproduce 
  1. launch `Dev`
  2. tap `Settings`
  3. tap `Siri Shorcuts (sic)`
  4. swipe down to `Brave News`

**Actual result:** 

`Use Shortcuts to Open a New Tab...`

![Image from iOS (1)](https://user-images.githubusercontent.com/387249/127202917-f714175e-3458-42d9-919b-734f9c10b797.png)

**Expected result:**
`Use Shortcuts to open a new tab...`

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
`1.29 (21.7.20.15)`

**Device details:** 
iPhone 6s, iOS 14.7

**Comment by michalnowak061** [comment]
I'm trying to fix this bug

**Comment by Uni-verse** [comment]
Verification completed using `1.36 (22.3.2.9) BraveCore 1.36.108 (99.0.4844.51)`

**PASSED** on `iPhone 12 Pro | iOS 15.1.1`
**PASSED** on `iPhone X | iOS 14.4.2`
**PASSED** on `iPad (7th Gen) | iOS 15.2.1`

- Verified copy for 'Open Brave News' has capitalization consistent with the rest of the page.

iPhone | iPad
-|-
![IMG_2609](https://user-images.githubusercontent.com/17885425/156647166-c8e8ff09-f266-4008-83be-67ab858b7023.PNG) | ![IMG_0168](https://user-images.githubusercontent.com/17885425/156647142-115ccd0d-3e9c-4a9e-803f-158d50d10ef5.PNG)
