### ISSUE TITLE
Favorites screen collection view crash.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3974]
### Steps to Reproduce 
Hard to reproduce, but xcode has a lot of crashes reported.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by bsclifton** [comment]
Shared in PR, but please contact me once this is ready 😄 I can reproduce in Beta and Dev. I'd love to verify the fix

I basically reproduced by going to craigslist, adding a bunch of favorites (over time)... and then deleting them after some time. In the craigslist example, I usually delete the favorite when the person pulls the listing (which might be throwing a 500 error or similar)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.30(21.8.12.8)
- Verified able to remove favourites when focus is on URL bar (show more mode)
- Verified able to reorder favourites when focus is on URL bar (show more mode)
- Verified able to edit favourites when focus is on URL bar (show more mode)
- Verified able to open a favourite in new tab/private tab via context menu when focus is on URL bar (show more mode)
- Verified able to open/edit/remove a favourite on an open page when focus is on URL bar (show more mode)
- Verified favourites work correctly on both normal and private tab
------------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.30(21.8.12.8)
- Verified able to remove favourites when focus is on URL bar (show more mode)
- Verified able to reorder favourites when focus is on URL bar (show more mode)
- Verified able to edit favourites when focus is on URL bar (show more mode)
- Verified able to open a favourite in new tab/private tab via context menu when focus is on URL bar (show more mode)
- Verified able to open/edit/remove a favourite on an open page when focus is on URL bar (show more mode)
- Verified favourites work correctly on both normal and private tab
------------
Verification passed on iPad Pro with iOS 14.6 running 1.30(21.8.12.8)
- Verified able to remove favourites when focus is on URL bar (show more mode)
- Verified able to reorder favourites when focus is on URL bar (show more mode)
- Verified able to edit favourites when focus is on URL bar (show more mode)
- Verified able to open a favourite in new tab/private tab via context menu when focus is on URL bar (show more mode)
- Verified able to open/edit/remove a favourite on an open page when focus is on URL bar (show more mode)
- Verified favourites work correctly on both normal and private tab
