### ISSUE TITLE
Tab Tray collection view crash.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#3975]
### Steps to Reproduce 
Hard to reproduce, sometimes it seems to crash when a favorite is removed or reordered

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by KacperWybranski** [comment]
Hi, I’m not sure if it’s same issue but I find my app crash on the iPad after spamming „cmd + T” on the hardware keyboard, while being in the tab tray view. It happens every time after opening 3-5 tabs.
iPad 8 with iOS 14.6, Brave Browser version 1.30.1

**Comment by iccub** [comment]
good to know, thanks @KacperWybranski, we have problems reproducing any crashes in the tab tray

For this ticket i work on a bigger refactor that should fix all kind of crashes.
Tab Tray is one of our top crash sources right now

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8 running 1.32.5 (21.11.2.23)
- Verified test plan from https://github.com/brave/brave-ios/pull/4210
- Verified no crash when switching between normal and private tabs
- Verified no crash when reordering tabs
-----------
Verification passed on iPhone 7+ with iOS 14.8 running 1.32.5 (21.11.2.23)
- Verified test plan from https://github.com/brave/brave-ios/pull/4210
- Verified no crash when switching between normal and private tabs
- Verified no crash when reordering tabs
------------
Verification passed on iPhone 7+ with iOS 14.8 running 1.32.5 (21.11.2.23)
- Verified test plan from https://github.com/brave/brave-ios/pull/4210
- Verified no crash when switching between normal and private tabs
- Verified no crash when reordering tabs
