### ISSUE TITLE
Playlist - Replace Toast with URL Bar Icon + Add Playlist Menu Button

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#3976]
## Feature Overview 
- Add Playlist URL Bar Icon
- Add Playlist Menu Button & Icon

## Design 
![image](https://user-images.githubusercontent.com/1530031/127371608-05258b00-7e65-4440-948c-425ba34af5c9.png)

## Implementation Details 
- Remove Toast
- Playlist URL Bar Icon has to be associated with a tab so when switching tabs, the URL bar is updated according to the tab being viewed.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.31(21.9.14.15)
- Verified playlist toast is now replaced with a URL bar button that shows up when a video page is loaded
- Verified playlist menu notification also shows up when a video page is loaded
- Verified when the video is added to playlist via URL bar button, menu notification is auto-removed
- Verified after adding video to playlist, URL bar playlist button changes from `Add` to `Added`
- Verified click on playlist added button, shows flyout to open playlist or remove 
- Verified removing a video from playlist via the URL button changes it back to Add to playlist button
- Verified steps from [#3977](#3977)

Add Button & Menu notification | Added to playlist 
-- | --
![image](https://user-images.githubusercontent.com/17010094/133418246-57c9b39b-7811-4a31-9fb4-ad854d6657ac.png) | ![image](https://user-images.githubusercontent.com/17010094/133418226-2770142d-df38-49ef-9667-86bc1606ae5d.png)

------------
Verification passed on iPhone 7+ with iOS 14.8 running 1.31(21.9.14.15)
- Verified playlist toast is now replaced with a URL bar button that shows up when a video page is loaded
- Verified playlist menu notification also shows up when a video page is loaded
- Verified when the video is added to playlist via URL bar button, menu notification is auto-removed
- Verified after adding video to playlist, URL bar playlist button changes from `Add` to `Added`
- Verified click on playlist added button, shows flyout to open playlist or remove 
- Verified removing a video from playlist via the URL button changes it back to Add to playlist button
- Verified steps from [#3977](#3977)

Add Button & Menu notification | Added to playlist 
-- | --
![image](https://user-images.githubusercontent.com/17010094/133418290-58c2ffbf-e0b8-4d84-9a06-d3ca68d936db.png) | ![image](https://user-images.githubusercontent.com/17010094/133418324-43521f9c-3daa-4254-b997-5385bfd8cbd3.png)

------------
Verification passed on iPad Pro with iOS 15 running 1.31(21.9.14.15)
- Verified playlist toast is now replaced with a URL bar button that shows up when a video page is loaded
- Verified playlist menu notification also shows up when a video page is loaded
- Verified when the video is added to playlist via URL bar button, menu notification is auto-removed
- Verified after adding video to playlist, URL bar playlist button changes from `Add` to `Added`
- Verified click on playlist added button, shows flyout to open playlist or remove 
- Verified removing a video from playlist via the URL button changes it back to Add to playlist button
- Verified steps from [#3977](#3977)

Add Button & Menu notification | Added to playlist 
-- | --
![image](https://user-images.githubusercontent.com/17010094/133418163-5b9e7913-7def-48be-8d09-d25e67b2fce3.png) | ![image](https://user-images.githubusercontent.com/17010094/133418125-ecec4ddd-9ead-4fb3-91b1-b3da3c61a134.png)
