### ISSUE TITLE
Incorrect favicons when switching between PB only and normal tabs

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#3986]
### Description: 
Incorrect favicons when switching between PB only and normal tabs

### Steps to Reproduce 
  1. Add a custom favourite by visiting a site and adding it as favourite
  2. Move the favourite into 2nd position on favourites bar
  3. Enable PB only so it clears data
  4. Disable PB only and go back to new tab, one of the favourites has a wrong favicon

**Actual result:** 

https://user-images.githubusercontent.com/17010094/127655095-389cd15b-5fa7-46a4-8696-8865465775a9.MP4

**Expected result:**
Favicons should not get messed up

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.29 (21.07.29.17)

**Device details:** 
iPhone XR (iOS 13.5)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
Possibly related to #3818 & #3345

**Comment by iccub** [comment]
This is the same as https://github.com/brave/brave-ios/issues/4120, let's close this one
