### ISSUE TITLE
Update httpse rulesets

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#3999]
### Description: 
New rulesets available here: https://www.https-rulesets.org/v1/

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.31(21.8.25.18)
- Verified test plan from #4047
- Verified navigating to `http://mirror.cogencto.com` auto redirects to `https://mirror.cogentco.com`
- Verified disabling `Upgrade connections to HTTPS` in global shields settings and visiting `http://mirror.cogentco.com` doesn't update the path to https
- Verified enabling `Upgrade connections to HTTPS` via shields on  `http://mirror.cogencto.com` upgrades the path to `https://mirror.cogentco.com`
------------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.31(21.8.25.18)
- Verified test plan from #4047
- Verified navigating to `http://mirror.cogencto.com` auto redirects to `https://mirror.cogentco.com`
- Verified disabling `Upgrade connections to HTTPS` in global shields settings and visiting `http://mirror.cogentco.com` doesn't update the path to https
- Verified enabling `Upgrade connections to HTTPS` via shields on  `http://mirror.cogencto.com` upgrades the path to `https://mirror.cogentco.com`
-----------
Verification passed on iPad Pro with iOS 14.6 running 1.31(21.8.25.18)
- Verified test plan from #4047
- Verified navigating to `http://mirror.cogencto.com` auto redirects to `https://mirror.cogentco.com`
- Verified disabling `Upgrade connections to HTTPS` in global shields settings and visiting `http://mirror.cogentco.com` doesn't update the path to https
- Verified enabling `Upgrade connections to HTTPS` via shields on  `http://mirror.cogencto.com` upgrades the path to `https://mirror.cogentco.com`
