### ISSUE TITLE
Add Brave Talk web-native communication.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4001]
Look for `Toggle Ads from Brave Properties Mini Spec` in gdrive

**Comment by stephendonner** [comment]
Verified `PASSED` using `1.32.1 (21.10.21.16)` on an `iPhone 6s`, `iOS 14.4.2`.

### Test case 1: Rewards & Ads enabled - PASSED

- install clean browser
- tap `Continue` on the Brave Shields onboarding slide (1st)
- tap `Start` on the Brave Rewards onboarding slide (2nd)
- go to `https://talk.brave.software`
- tap `Start free 1:1 call`
- confirm your Brave Talk call starts
- tap on the BAT icon in the URL bar
- confirm `Brave Rewards` is toggled `On`

example | example | example | example | example
---------|----------|---------|----------|---------
![Image from iOS](https://user-images.githubusercontent.com/387249/138345994-71e5b71c-c3c4-496a-b5f7-4aaa1b43ae77.png) | ![Image from iOS (1)](https://user-images.githubusercontent.com/387249/138345989-7208e39d-06fe-4d12-a902-9bae79c9cb83.png) | ![Image from iOS (2)](https://user-images.githubusercontent.com/387249/138345990-ad70c24b-fbf4-419c-b545-58871cb9f474.png) | ![Image from iOS (3)](https://user-images.githubusercontent.com/387249/138345991-1dfdf40c-5f73-4dec-a4c0-63e6ab69e96d.png) | ![Image from iOS (4)](https://user-images.githubusercontent.com/387249/138345992-5aad8654-d5c7-471f-b11f-541c632da00f.png)


### Test case 2: Rewards & Ads disabled (default) - PASSED

* install clean browser
* tap `Continue` on the Brave Shields onboarding slide (1st)
* tap `Skip` on the Brave Rewards onboarding slide (2nd)
* load `talk.brave.software`
* tap on `Start free 1:1 call`
* confirm you get the `Turn on Rewards` dialog
* dismiss the above dialog
* tap the `x` on the instructional popup
* tap the `Start free 1:1 call` button again
* confirm you get the `Turn on Rewards` dialog

example | example | example | example | example
---------|----------|---------|----------|---------
![Image from iOS (5)](https://user-images.githubusercontent.com/387249/138346855-449a3eaf-1cdd-4fbf-b332-1bf728a14e1f.png) | ![Image from iOS (6)](https://user-images.githubusercontent.com/387249/138346862-4602bc38-586f-4463-bd84-57f5a53504ae.png) | ![Image from iOS (7)](https://user-images.githubusercontent.com/387249/138346865-414b3b50-3129-4c9c-be32-f20e74242eee.png) | ![Image from iOS (8)](https://user-images.githubusercontent.com/387249/138346869-be570593-edd0-43ce-be20-0845655a2a65.png) | ![Image from iOS (9)](https://user-images.githubusercontent.com/387249/138346871-a09b4583-d76d-44bb-9dd7-c95a42625ac8.png)



### Test case 3: enable, disable, re-enable - PASSED

* install clean browser
* tap `Continue` on the Brave Shields onboarding slide (1st)
* tap `Start` on the Brave Rewards onboarding slide (2nd)
* tap on the `...` on the bottom toolbar
* tap `Settings`
* tap `Brave Rewards`
* tap to toggle `Enable Brave Rewards` to `Off`
* load `talk.brave.software`
* tap on the `Start free 1:1 call` button
* confirm you get a `turn on Brave Rewards` instructional popup
* tap on `Turn on Rewards`
* confirmed `You can now start a free call` interstitial appears
* confirm your Brave Talk call starts

example | example | example | example | example | example
---------|----------|---------|----------|---------|----------
![Image from iOS](https://user-images.githubusercontent.com/387249/138348160-9106a197-a11c-4c22-8ce5-aa057a1e2449.png) | ![Image from iOS (2)](https://user-images.githubusercontent.com/387249/138348197-ebf070d8-4186-4778-b7f6-74fde260ca42.png) | ![Image from iOS (1)](https://user-images.githubusercontent.com/387249/138348729-5e5561ab-1d8c-4a4a-a1fe-e3a3949ac18a.png) | ![Image from iOS (3)](https://user-images.githubusercontent.com/387249/138348852-caa2e232-f202-4f10-8526-49425ad5721b.png) | ![Image from iOS (5)](https://user-images.githubusercontent.com/387249/138348266-7dd0de0d-db2f-49e2-9ead-db081d9b36b5.png) | ![Image from iOS (4)](https://user-images.githubusercontent.com/387249/138348263-c17338c5-a8a7-40dc-b21c-d04dadc38eb3.png) 


### Test case 4: private tab - PASSED

* install clean browser
* tap `Continue` on the Brave Shields onboarding slide (1st) 
* tap `Start` on the Brave Rewards onboarding slide (2nd)
* open a new Private Tab
* load `talk.brave.software`
* tap on `Start free 1:1 call`
* confirm you see the instructional popup
* tap the `x` on the instructional popup
* confirm you are returned to `talk.brave.software`

example | example | example
---------|----------|---------
![Image from iOS](https://user-images.githubusercontent.com/387249/138349652-b091a056-60d1-4fe8-b1bc-866ac51da1fc.png) | ![Image from iOS (1)](https://user-images.githubusercontent.com/387249/138349694-b85cf18f-b79a-4d00-96ea-f5f90579083c.png) | ![Image from iOS (2)](https://user-images.githubusercontent.com/387249/138349697-9e85c8e9-7367-4fe5-992c-e06a4ee0a60c.png)

### Test case 5: `dark` mode - PASSED
* install clean browser
* tap `Continue` on the Brave Shields onboarding slide (1st) 
* tap `Skip` on the Brave Rewards onboarding slide (2nd)
* tap on `...` in the bottom toolbar
* tap `Settings`
* tap `Appearance`
* tap on `Dark`
* load `talk.brave.software`
* tap on the `Start free 1:1 call` button
* confirm the resulting popup notification is dark-themed
* tap on the BAT icon in the URL bar
* toggle `Brave Rewards` to `Off`
* reload `talk.brave.software`
* tap on `Start free 1:1 call` button
* confirm you get a dark-themed `Turn on Rewards` doorhanger dialog

example | example | example | example
---------|----------|---------|---------
![Image from iOS](https://user-images.githubusercontent.com/387249/138350911-4d8167aa-03c1-492a-8966-27f76fb7ffe3.png) | ![Image from iOS (3)](https://user-images.githubusercontent.com/387249/138350934-a928d4e3-b034-4526-a7ff-cb375995b940.png) | ![Image from iOS (5)](https://user-images.githubusercontent.com/387249/138351145-e88bc1be-b825-45f8-ac50-085381bb9d75.png) | ![Image from iOS (4)](https://user-images.githubusercontent.com/387249/138351551-9ec59ef8-4708-4076-b1d4-9732470ebfae.png)

**Comment by srirambv** [comment]
<details>
<summary>Verification passed on iPad Pro with iOS 15.1 Beta 3 running 1.32.1(21.10.20.18)</summary>
<br>

- Verified on clean install enabling rewards via onboarding and launching `talk.brave.com` allows to create a 1:1 free call

https://user-images.githubusercontent.com/17010094/138397709-36819eb6-d89a-4ced-b821-42137507cf82.MP4


- Verified on clean install skipping onboarding and loading `talk.brave.com` and trying to start a 1:1 call triggers enabled rewards modal. Once enabled auto redirects to meeting room

https://user-images.githubusercontent.com/17010094/138397849-78ab038b-65e9-4e2c-a7bb-4239f6b01281.MP4

- Verified meeting room is only created when reward is enabled. Skipping/dismissing the info modal and trying to start brings back the enable rewards modal 

https://user-images.githubusercontent.com/17010094/138398361-30b922f8-7053-4715-bb1f-6a009928e7d5.MP4

- Verified its not possible to create a meeting room on private tab. Verified on both Private tab and Private browsing only mode

https://user-images.githubusercontent.com/17010094/138398781-6742eaec-b036-461d-a434-32b47ee8139c.MP4

- Verified changing device theme via control centre updates the modals accordingly

https://user-images.githubusercontent.com/17010094/138399045-37f7d680-ca41-47a5-b1fa-8f3d71e95449.MP4

</details>
