### ISSUE TITLE
Implement bottom toolbar option

### ISSUE THREAD

**Issue by gh0sti** [brave/brave-ios#4002]
## Problem Description
Setting to change UI to have searchbar/omnibox and Tabs on bottom of the screen just above settings

## Feature Overview 
similar to Apple's new Safari iOS 15 update, the search bar is now on the bottom of the page.

## User Experience 

1. with phone screens getting even bigger this would allow end users to be able to reach and touch the search bar for quicker typing of URLs.
2. This would also allow moving between tabs to be easier by having navigation closer to the bottom of the screen or even having similar iOS 15 safari feature to swipe between tabs.
3.

**Comment by TaxingAuthority** [comment]
I know this feature request is six months old but I want to add another plug for the feature. The Firefox iOS app just implemented this option in their latest release. Really helps with navigation while web browsing.

**Comment by riddlerboss248** [comment]
Posting a quick design idea for the bottom adressbar (see attached images). Originally posted on reddit ( https://www.reddit.com/r/brave_browser/comments/u3pfph/my_take_on_bottom_placed_adressbar_on_brave_ios/i4qosq2/?context=3 )


<img width="361" alt="Skärmavbild 2022-04-14 kl  21 29 32" src="https://user-images.githubusercontent.com/103686718/163465145-a5f446a6-3781-4c4d-910b-dc4b7e468fb2.png">
<img width="411" alt="Skärmavbild 2022-04-14 kl  21 29 14" src="https://user-images.githubusercontent.com/103686718/163465154-5ae8a85a-8c63-47ec-a476-590edf68cffd.png">

**Comment by iccub** [comment]
Thank you :)

**Comment by foliot** [comment]
It was a weird transition at first when Safari moved the address bar to the bottom, but it turned out to be a wonderful change that made the controls more reachable, especially in one-handed operation. I think replicating the iOS interface as much as possible would be a nice improvement here.

**Comment by iccub** [comment]
Good news: the bottom toolbar is ready and can be tested in public beta :) build number `1.44 (22.9.27.21)`

You can use this link to give it a try https://testflight.apple.com/join/Trcbh1o3
The feature should go live early next next month

**Comment by gh0sti** [comment]
@iccub thanks, looks good so far. Would it be possible to get the swipe feature similar to safari where I can swipe up to go into the tab switcher? Or possible to also include tab hider when not touching the omnibox?

**Comment by kylehickinson** [comment]
@gh0sti If you swipe up on the URL bar it will already bring up the tab switcher, there is just no interactive aspect to it. Not sure what you mean by tab hider.

**Comment by gh0sti** [comment]
> @gh0sti If you swipe up on the URL bar it will already bring up the tab switcher, there is just no interactive aspect to it. Not sure what you mean by tab hider.

so that makes it easy to move into tab switcher. However when you want tabs shown above omnibox in portrait mode they take up some screen realestate. Is there a way to allow for tabs in portrait mode but to hide/unhide them when you want to see open tabs on a webpage above the omnibox?

**Comment by iccub** [comment]
hi @gh0sti maybe you can show us what do you mean? post a screenshot or a short recording
we are pretty close to what Safari currently offers

**Comment by Uni-verse** [comment]
Verified using `1.44 (22.10.10.19)` & `1.44 (22.10.13.13)` using the following device(s):

iPhone 12 | iOS 16.x
iPhone XR | iOS 15.x
iPhone X | iOS 14.x
iPad (7th Gen) | iPadOS 15.x

<details><summary>Bottom tool bar</summary>

- Verified bottom tool bar is enabled by default
- Verified tabs bar is set to landscape by default
- Verified the following scenarios while bottom bar is enabled: 
1. Turning off tabs bar
2. Setting tabs to `On`
3. Changing device orientation with default settings
4. Using `Find in Page` 
5. Using `Reader mode` with tabs On/Off
6. `Switching tabs` via the tabs bar
7. Enabling bookmarks shortcut 
8. Hiding Rewards

Example | Example | Example
-|-|-
![IMG_0093 2](https://user-images.githubusercontent.com/17885425/195641371-7c453641-4de8-478c-a5c4-9a380887c107.PNG) | ![IMG_0088](https://user-images.githubusercontent.com/17885425/195641395-7d04743f-102f-4f8b-9ce5-d810ea8b1628.PNG) | ![IMG_0094 2](https://user-images.githubusercontent.com/17885425/195641667-d53fd638-6483-464f-b749-ab44445b7bd9.PNG)




</details>


<details><summary>Top Tool bar</summary>

- Verified changing Tabs settings to Top Bar will move the url + tabs bar to the top
- Verified the following scenarios while Top Bar is enabled: 
1. Turning off tabs bar
2. Setting tabs to `On`
3. Changing device orientation with default settings
4. Using `Find in Page` 
5. Using `Reader mode` with tabs On/Off
6. `Switching tabs` via the tabs bar
7. Enabling bookmarks shortcut 
8. Hiding Rewards
9. Private Browsing Mode/Private Tabs

Example | Example | Example | Example
-|-|-|-
![IMG_0096](https://user-images.githubusercontent.com/17885425/195639609-b4b25b5a-4507-442d-992d-9b9ffd74ce30.PNG) | ![IMG_0099](https://user-images.githubusercontent.com/17885425/195639947-e599df61-6fcc-4c52-8342-38075dde6a89.PNG) | ![IMG_0100](https://user-images.githubusercontent.com/17885425/195640604-70b64225-42d6-45c4-819b-1a7ed04d88f7.PNG) | ![IMG_0101](https://user-images.githubusercontent.com/17885425/195640614-fbfe96dd-63e9-4b41-8ad7-dd2bfd3cbba3.PNG)

</details>

<details><summary>Settings Menu</summary>

- Verified added switch under Tabs with options for url bar configuration
- Verified Tabs menu is displayed in landscape orientation
- Verified Tabs section allows user to switch between Bottom and Top Bar
- Verified option contains checkmark to indicate which option is currently selected

Example | Example
-|-
![IMG_0093](https://user-images.githubusercontent.com/17885425/195637920-ef09d517-db8f-4bd3-bae5-52f92c763ede.PNG) | ![IMG_3891](https://user-images.githubusercontent.com/17885425/195639059-bcc05259-74e3-4245-a23a-9b6ff2dcd94f.PNG)


</details>


<details><summary>iPad</summary>

- Verified `Tabs Bar` switch moved to `Tabs` section
- Verified enabled `Tabs Bar` will show tabs below the url bar
- Verified Tab settings are retained when upgrading from 1.43.x

Example | Example
-|-
![IMG_0647](https://user-images.githubusercontent.com/17885425/195652955-f2d4a824-4774-49ce-9f7c-5766a9826ae7.PNG) | ![IMG_0648](https://user-images.githubusercontent.com/17885425/195652964-f6ee4331-22f3-4765-9655-015a2fb58aab.PNG)


</details>


<details><summary>Upgraded Profile (Tabs in Landscape Only)</summary>

- Ensured that Tabs bar settings will be retained when upgrading from version 1.43
- Ensured that user is able to switch to using Bottom Bar after upgrading the app
- Ensured that changing tabs setting from landscape to On/Off is working and user is able to open new tabs as well as switch between tabs via the tabs bar.

![IMG_3894](https://user-images.githubusercontent.com/17885425/195645772-ab0b3148-f8fe-4606-b025-1c73b49f188e.PNG)

</details>

<details><summary>Upgraded Profile (Always Show Tabs)</summary>

- Ensured that Tabs bar settings will be retained when upgrading from version 1.43
- Ensured that user is able to switch to using Bottom Bar after upgrading the app
- Ensured that changing tabs setting from landscape to On/Off is working and user is able to open new tabs as well as switch between tabs via the tabs bar.
- Ensured that hiding rewards option and as well as showing bookmarks is retained when upgraded

![IMG_3895](https://user-images.githubusercontent.com/17885425/195647823-ac7139e4-a6b3-4bf2-a7ed-c44bacf22608.PNG)

</details>


<details><summary>Upgraded Profile (Never Show Tabs)</summary>

- Ensured that Tabs bar settings will be retained when upgrading from version 1.43
- Ensured that user is able to switch to using Bottom Bar after upgrading the app
- Ensured that changing tabs setting from landscape to On/Off is working and user is able to open new tabs as well as switch between tabs via the tabs bar.

![IMG_3896](https://user-images.githubusercontent.com/17885425/195649391-bd8d6d6e-4223-4d95-ba35-b8e060d0108c.PNG)

</details>

<details><summary>Upgraded Profile (Private Browsing Mode Enabled)</summary>

- Ensured that Tabs bar settings will be retained when upgrading from version 1.43
- Ensured that user is able to switch to using Bottom Bar after upgrading the app
- Ensured that changing tabs setting from landscape to On/Off is working and user is able to open new tabs as well as switch between tabs via the tabs bar.

![IMG_3897](https://user-images.githubusercontent.com/17885425/195651436-7b093e18-9028-47b7-a5d8-ea35bee922af.PNG)


</details>
