### ISSUE TITLE
Disable History sync when user switches to PB only

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4009]
### Description: 
Disable History sync when user switches to PB only

### Steps to Reproduce 

**Scenario 1 - PB Only mode before sync is enabled**
  1. Enable PB only mode
  2. Enable Sync and join a sync chain or add devices to the new one
  3. History from other devices show up on iOS
  4. Clear browser history from other device, history sync'd is also removed on iOS

**Scenario 2 - PB only mode after sync is enabled**
  1. Create a sync chain or join one 
  2. Enable history sync 
  3. Switch to PB only mode
  4. No further history is sync'd from iOS but history from other devices and normal tabs history still sync's

**Actual result:** 
History sync is enabled on all the three scenarios which defeats the purpose of private tabs only mode

**Expected result:**
Disable History sync when a user switches to PB only mode

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.30(21.8.5.11)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @soner-yuksel @jumde

**Comment by diracdeltas** [comment]
if a user without pb only opens a private tab, does history in that tab get synced? (it shouldn't)

**Comment by srirambv** [comment]
@diracdeltas no it doesn't. Only normal tab history is sync'd. @soner-yuksel can we disable the history tab to show any data when user switches to Private tabs or PB only?

**Comment by soner-yuksel** [comment]
Our data is not sync'ed and it is not even added while user is on a private tab.

And I believe we should not make a change for Private Tabs. This is the same behaviour on desktop. 
Only concern was PB Only mode and we dont have this mode in desktop or android so the decision about this mode was not to show any history item like and quick PR adds that behaviour.

**Comment by iccub** [comment]
@diracdeltas do you want us to open a formal sec/privacy review for this change once we agree on expected outcome?

**Comment by soner-yuksel** [comment]
> @diracdeltas do you want us to open a formal sec/privacy review for this change once we agree on expected outcome?

@iccub this is the sec-review for iOS https://github.com/brave/security/issues/501. And this feature had 2 separate sec-reviews both for core https://github.com/brave/security/issues/457 and iOS separately. 

Or do you mean a sec review for this particular change ?

@jumde what is your opinion here? I believe we discussed this part and how to implement it and and only sec/privacy concern left is https://github.com/brave/security/issues/501#issuecomment-893836863

**Comment by soner-yuksel** [comment]
PR for this change is merged but re-opening it until having a final decision.

**Comment by jumde** [comment]
Hiding the history in private browsing only mode makes sense to me. 

I think in past we decided to use this issue: https://github.com/brave/brave-ios/issues/3184 - to clean up the settings panel in PBO mode.

**Comment by soner-yuksel** [comment]
Ok in this case I am closing this ticket. If there is any more concern related with this issue please creata new ticket or let me know.

**Comment by srirambv** [comment]
This is still not fully fixed. I can see history from other devices show up on iOS device when history page is kept open 


STR:
1. Set browser to PB only mode
2. Join Sync chain
3. Enable history sync
4. Visit pages on other device by typing in urls
5. Open history page on iOS device
6. Visit a new page on other device, all typed in URL's from other device gets sync'd
7. Navigate away from history page, list is cleared
8. Keep history page open and browser again on other device, history comes back

**Comment by srirambv** [comment]
Marking as QA Blocked due to #4027

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.30(21.8.12.8)
- Verified steps from issue description
- Verified history page shows message when history sync is enabled with PB only mode
------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.30(21.8.12.8)
- Verified steps from issue description
- Verified history page shows message when history sync is enabled with PB only mode
-------
Verification passed on iPad Pro with iOS 14.6 running  1.30(21.8.12.8)
- Verified steps from issue description
- Verified history page shows message when history sync is enabled with PB only mode

iPhone XR | iPhone 7+ | iPad Pro
-- | -- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/129205122-3271d73b-917c-4d30-a94f-9df3472ad7ff.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/129205107-4415a408-7ba1-43cf-b972-fb7d9a367bc8.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/129205134-f47a0ce6-d180-47af-9e1d-3dd0dc4caaf6.png>
