### ISSUE TITLE
iPhone closed tab stuck as a tab navigation background 

### ISSUE THREAD

**Issue by tankmohit** [brave/brave-ios#4019]
### Description: 
- After closing the tab, it flashes for a while during the tab switches or creating a new tab. 

### Steps to Reproduce 
 - Not sure how to reproduce each time. But faced this issue whenever following settings are made. 
 1. Disabled Brave rewards
 2. Search engine suggestions-> On. 
 3. Appearance-> Automatic
4. Show background Images, Default Images only. 
5. Show tabs bar in landscape only. 
6. Show bookmarks shortcut
7. Hide rewards ico

- Left other settings to default 
 
**Actual result:**
[Link to video](https://imgur.com/kHOnn7O)

**Device Information**
- iPhone XR running iOS 14.7.1
- Brave browser version : Version 1.29 (21.8.3.10)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.30.1(21.8.16.22)
- Verified steps from issue description
- Verified steps on both normal and private tabs
-----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.30.1(21.8.16.22)
- Verified steps from issue description
- Verified steps on both normal and private tabs
-----------
Verification passed on iPad Pro with iOS 14.6 running 1.30.1(21.8.16.22)
- Verified steps from issue description
- Verified steps on both normal and private tabs
-----------

Verification **PASSED** on `iPhone 11` running `iOS 14.7.1` using `1.30.1 (21.8.17.19)`

Reproduced the issue several times using `1.30 (21.8.12.16)` by opening/closing a lot of tabs via Normal/PB modes

* spent ~30min or so opening/closing tabs in Normal/PB mode and never ran into the issue

-----------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.7.1` using `1.30.1 (21.8.17.19)`

Reproduced the issue several times using `1.30 (21.8.12.16)` by opening/closing a lot of tabs via Normal/PB modes

* spent ~30min or so opening/closing tabs in Normal/PB mode and never ran into the issue
