### ISSUE TITLE
TrackingProtectionStats and RewardsReporting scripts broken.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4021]
### Description: 
More info here https://github.com/mozilla-mobile/firefox-ios/pull/8880
For us it's 2 scripts that are failing

### Steps to Reproduce 
  1. Go to https://www.crowdcow.com/products/chicken-breast?filter%5Bbid_item%5D=iwceogjzr0h

**Actual result:** 
Image is not showing

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.31(21.8.25.18)
- Verified steps from issue description. Images load on the page when visited using 1.31 build
- Verified steps from #4022 
- Verified shields stats update while keeping it open and NTP stats update when visiting sites
-----------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.31(21.8.25.18)
- Verified steps from issue description. Images load on the page when visited using 1.31 build
- Verified steps from #4022 
- Verified shields stats update while keeping it open and NTP stats update when visiting sites
----------
Verification passed on iPad Pro with iOS 14.6 running 1.31(21.8.25.18)
- Verified steps from issue description. Images load on the page when visited using 1.31 build
- Verified steps from #4022 
- Verified shields stats update while keeping it open and NTP stats update when visiting sites
