### ISSUE TITLE
sharing links from other applications using `Share via..` doesn't work

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4034]
### Description: 

Sharing links with Brave using `Share via..` within other applications stopped working. This isn't reproducible using `1.29 (21.8.3.10)`.

### Steps to Reproduce

  1. install/launch `1.30 (21.8.9.17)` via TF
  2. skip on-boarding/close Brave (you can also leave it opened via background)
  3. go into another application and attempt to share something with Brave via the `Share via..` button

I was using Gmail/Twitter and could reproduce 100% of the time.

**Actual result:** 

You'll notice that a translucent dark colour will quickly flash on the entire screen but nothing will happen. Seems like Brave tries to open but immediately fails.

**Expected result:**

Should be able to share links with Brave from other applications using the `Share via..` context menu.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

*  `1.30 (21.8.9.17)` - **Reproduced**
*  `1.30 (21.8.11.14)` - **Reproduced**

**Device details:** 

* `iPhone 11` running `iOS 14.7.1` - **Reproduced**
* `iPad Air (3rd Gen)` running `iOS 14.7.1` - **Reproduced**
* `iPad Mini 4` running `iOS 13.7` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @srirambv @iccub @kylehickinson

**Comment by srirambv** [comment]
Repro  on upgrade profile as well

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 14.7.1` using `1.30 (21.8.12.16)`

* ensured that sharing links with Brave from `Twitter` via the `Share` context menu works without any issues
* ensured that sharing links with Brave from `Gmail` via the `Share` context menu works without any issues
* ensured that sharing links with Brave from `FB Messenger` via the `Share` context menu works without any issues
* ensured that the above cases worked when Brave opened via background & closed completely

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.7.1` using `1.30 (21.8.12.16)`

* ensured that sharing links with Brave from `Twitter` via the `Share` context menu works without any issues
* ensured that sharing links with Brave from `Gmail` via the `Share` context menu works without any issues
* ensured that sharing links with Brave from `FB Messenger` via the `Share` context menu works without any issues
* ensured that the above cases worked when Brave opened via background & closed completely

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.30 (21.8.12.16)`

* ensured that sharing links with Brave from `Twitter` via the `Share` context menu works without any issues
* ensured that sharing links with Brave from `Gmail` via the `Share` context menu works without any issues
* ensured that sharing links with Brave from `FB Messenger` via the `Share` context menu works without any issues
* ensured that the above cases worked when Brave opened via background & closed completely
