### ISSUE TITLE
Minimize and close playlist

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#4038]
![IMG_2833](https://user-images.githubusercontent.com/318119/129208281-a1b18dbd-1eb5-4864-b277-c3e97a1bdb6c.PNG)

Currently users tap Done to close the playlist window. Keeping the player in PIP mode is reportedly difficult to find. The solution is to add a minimize button on the playlist toolbar, and replace the Done button with a close button.

Tapping the down carat should launch PIP, while tapping the close X should stop the player and close playlist.

![minimize](https://user-images.githubusercontent.com/318119/129208221-a7ac7f08-cb7c-49cb-b992-ec4e3b54ae5e.png)

## Icons
[playlistimages.zip](https://github.com/brave/brave-ios/files/6975910/playlistimages.zip)

**Comment by iccub** [comment]
closing in favor of playlist v2 revamp
