### ISSUE TITLE
Fix History Result Fetch Visit-Time in Query Results

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#4039]
### Description: 
- While fetching History Item from `QueryResults`, `URLRow`'s `last_visit()` function is used. This causes in rare occasions some of the History Items to appear in wrong section.

### Steps to Reproduce 
  1. Add an History item to different time period defined in iOS application(Today / Yesterday / Last Week)
  2. This history items should have exact title/ url but belong different time zones
  3. Check the history item belongs to past time slot doesn't appear in desired slot.
  
**Actual result:** 

History item belongs to past time slot doesn't appear in desired slot.

**Expected result:**

History item shown in proper time slot

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent Issue

**Brave Version:** 
1.30

**Device details:** 
Any Device Type

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by soner-yuksel** [comment]
Re-opening the issue until Chromium bump happen

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.31(21.9.1.16)
- Verified history results are properly listed based on timestamp

iPhone XR (iOS 13.5) | iPhone 7+ (iOS 14.5.1) | iPad Pro (iOS 14.6)
-- | -- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/131797609-61dfa31f-2f23-42a6-afd2-c855d3cdae50.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/131797634-4e8fab73-79f0-4cc0-9338-5aec7788bfac.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/131797678-5bb66b98-3b5f-4ac4-8ce5-95c4adb23283.png>
