### ISSUE TITLE
Add a separate section for history items created earlier than last month

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#4040]
### Description: 

Right now in history list, we have sections showing items from (Today / Yesterday / Last Week / Last Month). If any item is dated before last month it is now shown in the list even it is fetched within the limits.

Adding a new section after Last Month to gather items that has older date called Earlier will be useful for some user who doesnt have many History entries.

### Steps to Reproduce 
  1. Have History items older than 1 Month
  2. Check If these items are displayed If existing time slots has less 200 items

**Actual result:** 

History items older than a month is not displayed

![1history](https://user-images.githubusercontent.com/6643505/129235792-b6e1e614-f728-4ac8-abc1-6de1fe3c120f.png)

**Expected result:**

These items displayed in a separate section

![2122212](https://user-images.githubusercontent.com/6643505/129235905-6fbcf4d8-500a-49a0-80e1-03aa9b69c4ee.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
Any

**Device details:** 
Any

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.32.1(21.10.18.10)

iPhone 7+ (iOS 14.8) | iPhone XR (iOS 15.0.1) | iPad Pro (iOS 15.1 Beta 3)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/137750241-18a957a8-caf8-4ea2-adb8-9a0ed1cf6748.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/137750201-ffcc602c-3d4d-440c-b513-ecf2bbe133fc.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/137750378-97c53199-7ef0-47db-b543-3a1dd4cbc583.png>
