### ISSUE TITLE
Copy update for universal app open

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4042]
### Description: 

Please update the text for the below to

**Open web links in Brave (even when link app is installed)**

![IMG_1C40242FCF07-1 (1)](https://user-images.githubusercontent.com/7606853/129278987-6c98834a-6fef-4c56-9d15-9d9feaa2dab5.jpeg)

**Comment by kylehickinson** [comment]
@anthonypkeane that copy is reversed from the original intent, therefore the default will now have to be **off**

**Comment by iccub** [comment]
Closing this for now, we may revisit in the future
