### ISSUE TITLE
Settings order for pull-to-refresh and set as default browser button are wrong

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4045]
The set as default browser should always be the final item, the pull to refresh setting was below it.

## Expected:
Pull to refresh setting should be above, default browser button should be final item always

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 14.7.1` using `1.30.1 (21.8.16.22)`

<details>
<summary>Screenshot example of fix</summary>

![IMG_8377](https://user-images.githubusercontent.com/2602313/129655092-40a1c600-5131-4145-973f-1cebdb531a3d.png)
</details>

* ensured that enabling/disabling `Enable Pull-to-refresh` via `Settings` worked as expected
* ensured that `Set as Default Browser` opened the Brave iOS settings and allows users to change `Default Browser App` to Brave

------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.7.1` using `1.30.1 (21.8.16.22)`

<details>
<summary>Screenshot example of fix</summary>

![IMG_0294](https://user-images.githubusercontent.com/2602313/129658114-c3526cab-1702-4666-a873-91c5aeb29800.png)

</details>

* ensured that enabling/disabling `Enable Pull-to-refresh` via `Settings` worked as expected
* ensured that `Set as Default Browser` opened the Brave iOS settings and allows users to change `Default Browser App` to Brave

------

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.30.1 (21.8.16.22)`

**Note:** iOS 13 doesn't support default browser as that was introduced in iOS 14

<details>
<summary>Screenshot example of fix</summary>

![IMG_0590](https://user-images.githubusercontent.com/2602313/129657474-ad4045f8-5748-4c3f-b882-7ff42294a903.png)

</details>

* ensured that enabling/disabling `Enable Pull-to-refresh` via `Settings` worked as expected

-----------------
Verification passed on the following devices running 1.30.1(21.8.16.22)
- Verified `Enable Pull-to-refresh` setting is above `Set as Default Browser` setting
- Verified enable/disable `Enable Pull-to-refresh` works as expected
Default browser not available in iOS 13 

iPhone XR (iOS 13.5) | iPhone 7+ (iOS 14.5.1) | iPad Pro (iOS 14.6)
-- | -- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/129683894-574f92d3-ca74-473e-b7cd-d378ed6cf6df.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/129683926-9b721d48-4e27-4afa-ba5b-b6fda8c7bb55.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/129684370-f176fddf-91f8-44d8-9ba3-5f35553137b8.png>
