### ISSUE TITLE
Update Brave Search beta to Brave Search 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4049]
### Description: 
Please update the listing of **Brave Search beta** to **Brave Search** in Settings and on Onboarding (and anywhere else it may be listed) 

Thanks

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.31(21.8.25.18)
- Verified test plan from #4095
- Verified Brave Search beta is renamed to Brave Search in On-boarding screen/Normal tab Search Engine/Private tab Search and Quick Search setting
- Verified Search engine name is renamed post upgrade 

On-boarding | Search Setting |Search Engine Setting | Quick Search Setting
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/130986809-69f7b5ae-2ef9-453f-aeb5-4fcfb6147f46.png) | ![image](https://user-images.githubusercontent.com/17010094/130986956-2d5b37c4-9fc9-4a74-aa53-4dec0cfa7f26.png) | ![image](https://user-images.githubusercontent.com/17010094/130986989-2accc357-a2ad-4caa-9964-05f59733394f.png) | ![image](https://user-images.githubusercontent.com/17010094/130986915-63a4e04d-ab60-4ded-ad77-34f40f8e8f71.png)


------------
Verification passed on iPhone XR with iOS 13.5 running 1.31(21.8.25.18)
- Verified test plan from #4095
- Verified Brave Search beta is renamed to Brave Search in On-boarding screen/Normal tab Search Engine/Private tab Search and Quick Search setting
- Verified Search engine name is renamed post upgrade 

On-boarding | Search Setting |Search Engine Setting | Quick Search Setting
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/130987677-35527afa-792b-4d51-af8c-fe50de12845c.png) | ![image](https://user-images.githubusercontent.com/17010094/130987850-820b3991-e273-4a06-b4af-ab35f94039b0.png) | ![image](https://user-images.githubusercontent.com/17010094/130987875-97769cb2-df77-420c-a7eb-9d090c64e723.png) | ![image](https://user-images.githubusercontent.com/17010094/130987895-8f07b084-e86d-48d5-8df1-56372b43cc01.png)

------------
Verification passed on iPhone XR with iOS 13.5 running 1.31(21.8.25.18)
- Verified test plan from #4095
- Verified Brave Search beta is renamed to Brave Search in On-boarding screen/Normal tab Search Engine/Private tab Search and Quick Search setting
- Verified Search engine name is renamed post upgrade 

On-boarding | Search Setting |Search Engine Setting | Quick Search Setting
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/130988067-ca7e3927-6ff5-45f5-ad0c-59b37570a708.png) | ![image](https://user-images.githubusercontent.com/17010094/130988093-5368f681-c095-4320-a03a-a0c10a57727b.png) | ![image](https://user-images.githubusercontent.com/17010094/130988170-7cce95c6-34dc-4ba0-96b0-8a71ab92b092.png) | ![image](https://user-images.githubusercontent.com/17010094/130988214-fea946f9-a0e7-48e9-9153-8f5ded6c4468.png)
