### ISSUE TITLE
Bookmarklets no longer working in Brave Beta

### ISSUE THREAD

**Issue by geekalert** [brave/brave-ios#4055]
### Description: 
JS bookmarklets have stopped working in the latest beta release.

### Steps to Reproduce 
  1. Browse to a web page.
  2. Select the bookmarklet to use from saved bookmarks.

**Actual result:** 

Absolutely nothing happens.

**Expected result:**

A window pops up asking me to save the web page to my online bookmarking service. I have verified the content of the bookmarklet is the same.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Always.

**Brave Version:** 

v1.30 (21.8.12.16)

**Device details:** 

100% reproducible on iPad Pro 2018 12.9”, iPad Air 2, and iPhone 7 Plus running iOS 14.3-14.7.1.

**Website problems only:**
- did you check with Brave Shields down? Yes.
- did you check in Safari/Firefox (WkWebView-based browsers)? It is working in Safari v14

### Additional Information

N/A

**Comment by Brandon-T** [comment]
Hi, I've attempted to reproduce this issue on `v1.30 (21.8.12.16)`:

1. Added bookmark with `Title: Test` and URL: `javascript:alert('test');`
2. I went to `https://brave.com/` and tapped on the `Settings -> Bookmarks -> Test` and the alert shows up.

Is there a specific bookmarklet that isn't working for you?

**Comment by geekalert** [comment]
You’re right; that example works for me. I am having trouble with a much more complicated bookmarklet from Bookmark Ninja that had been working until the most recent Brave Beta update:

```
javascript:%20(function(){var%20title=encodeURIComponent(window.document.title);var%20url=encodeURIComponent(window.location.href);var%20ua=navigator.userAgent;var%20ver="2.5";if%20(isM())%20mAdd();%20else%20dAdd();function%20dAdd(){var%20br=getBrowser();var%20w=579;var%20h=467;if%20(br=='firefox'){if%20(isMac())%20h=462;else%20h=495;}else%20if%20(br=='opera'){w=600;h=554;}else%20if(br=='safari'){h=488;}else%20if%20(br=='chrome'%20&&%20isMac()){h=467;}else%20if%20(br=='ie'){h=452;}var%20left=(screen.width-w)/2;var%20tops=(screen.height-h)/3;win=window.open('https://www.bookmarkninja.com/addbookmark?title='+title+'&url='+url+'&bv='+ver,%20'_blank',%20'top='+tops+',%20left='+left+',%20width='+w+',%20height='+h+'%20resizable=1,%20location=no,%20menubar=0,%20scrollbars=0,%20status=0,%20toolbar=0');if%20(br=='ie')%20setTimeout(function(){win.focus();},5);}function%20mAdd(){void(window.open('https://www.bookmarkninja.com/m-addbookmark?title='+title+'&url='+url+'&bv='+ver,%20'_blank'));}function%20isM(){if%20(ua.match(/Android/i)%20||%20ua.match(/webOS/i)%20||%20ua.match(/iPhone/i)%20||%20ua.match(/iPad/i)%20||%20ua.match(/iPod/i)%20||%20ua.match(/BlackBerry/i)%20||%20ua.match(/Windows%20Phone/i))%20return%20true;else%20return%20false;}function%20getBrowser(){if%20(ua.match(/Edge/i))%20return%20'edge';if%20(ua.match(/Opera/i))%20return%20'opera';if%20(ua.match(/OPR/i))%20return%20'opera';if%20(ua.match(/Chrome/i))%20return%20'chrome';if%20(ua.match(/Firefox/i))%20return%20'firefox';if%20(ua.match(/MSIE/i))%20return%20'ie';if%20(ua.match(/Windows%20NT/i)%20&&%20ua.match(/rv:11/i))%20return%20'ie';if%20(!!ua.match(/Version\/[\d\.]+.*Safari/))%20return%20'safari';return%20'other';}function%20isMac(){if%20(ua.match(/Macintosh/i))%20return%20true;else%20return%20false;}})();
```

**Comment by Brandon-T** [comment]
Hi @geekalert 
I have investigated the issue. It seems that snippet of Javascript is not correctly encoded as a URL.

The correct encoding is:
```javascript
javascript:%20(function()%7Bvar%20title=encodeURIComponent(window.document.title);var%20url=encodeURIComponent(window.location.href);var%20ua=navigator.userAgent;var%20ver=%222.5%22;if%20(isM())%20mAdd();%20else%20dAdd();function%20dAdd()%7Bvar%20br=getBrowser();var%20w=579;var%20h=467;if%20(br=='firefox')%7Bif%20(isMac())%20h=462;else%20h=495;%7Delse%20if%20(br=='opera')%7Bw=600;h=554;%7Delse%20if(br=='safari')%7Bh=488;%7Delse%20if%20(br=='chrome'%20&&%20isMac())%7Bh=467;%7Delse%20if%20(br=='ie')%7Bh=452;%7Dvar%20left=(screen.width-w)/2;var%20tops=(screen.height-h)/3;win=window.open('https://www.bookmarkninja.com/addbookmark?title='+title+'&url='+url+'&bv='+ver,%20'_blank',%20'top='+tops+',%20left='+left+',%20width='+w+',%20height='+h+'%20resizable=1,%20location=no,%20menubar=0,%20scrollbars=0,%20status=0,%20toolbar=0');if%20(br=='ie')%20setTimeout(function()%7Bwin.focus();%7D,5);%7Dfunction%20mAdd()%7Bvoid(window.open('https://www.bookmarkninja.com/m-addbookmark?title='+title+'&url='+url+'&bv='+ver,%20'_blank'));%7Dfunction%20isM()%7Bif%20(ua.match(/Android/i)%20%7C%7C%20ua.match(/webOS/i)%20%7C%7C%20ua.match(/iPhone/i)%20%7C%7C%20ua.match(/iPad/i)%20%7C%7C%20ua.match(/iPod/i)%20%7C%7C%20ua.match(/BlackBerry/i)%20%7C%7C%20ua.match(/Windows%20Phone/i))%20return%20true;else%20return%20false;%7Dfunction%20getBrowser()%7Bif%20(ua.match(/Edge/i))%20return%20'edge';if%20(ua.match(/Opera/i))%20return%20'opera';if%20(ua.match(/OPR/i))%20return%20'opera';if%20(ua.match(/Chrome/i))%20return%20'chrome';if%20(ua.match(/Firefox/i))%20return%20'firefox';if%20(ua.match(/MSIE/i))%20return%20'ie';if%20(ua.match(/Windows%20NT/i)%20&&%20ua.match(/rv:11/i))%20return%20'ie';if%20(!!ua.match(/Version%5C/%5B%5Cd%5C.%5D+.*Safari/))%20return%20'safari';return%20'other';%7Dfunction%20isMac()%7Bif%20(ua.match(/Macintosh/i))%20return%20true;else%20return%20false;%7D%7D)();
```

If you run the above, it will take you to a `bookmark ninja` login page in a new tab.
This is not an issue with Brave iOS as it does indeed execute bookmarklets correctly, but rather the URL itself is not encoded properly in the first place and `WKWebView` will throw an exception trying to execute the JS you've provided:

```Swift
Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=SyntaxError: Unexpected token '%', WKJavaScriptExceptionColumnNumber=0
```

This can be fixed by unescaping the JS and then reescaping it properly:
```Swift
JS.removingPercentEncoding.addingPercentEncoding(withAllowedCharacters: URLAllowed)
```

but I'm not sure if we should modify or re-encode anything entered by the user. I will get back to you on that after I consult the team.

**Comment by geekalert** [comment]
Hey, there. Thanks for looking at this. Sounds like it’s just an issue with this bookmarklet, so I’ll give the modified one you created a try and pass along if it works for me.

UPDATE: I can confirm that the modified URL works after closing and reopening Brave Beta. I will pass along your findings to the BN team. Thank you for troubleshooting with me! I’ll keep this open, though, to hear your feedback from your group about helping users enter their bookmarklets properly. Thanks again!
