### ISSUE TITLE
Restore CoreData tests for Travis builds

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#406]
Ref #405 

At the moment the `test` lane ignores `DataTests`, some specific CoreData related tests in `TabManagerTests ` and some network async tests due to their flaky nature when running in Travis.

It would be good to figure out how to bring these back without causing our builds to fail

**Comment by iccub** [comment]
Removing network async tests from this ticket and putting it here https://github.com/brave/brave-ios/issues/950
