### ISSUE TITLE
Opening tab tray only focus on current tab before showing up others

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4060]
### Description: 
Opening tab tray only focus on current tab before showing up others

### Steps to Reproduce 
  1. Open a few tabs 
  2. Open tab tray 
  3. Only current tab is shown and others show up when tab goes into tile 

**Actual result:** 

https://user-images.githubusercontent.com/17010094/129704616-32edb314-d279-4b2f-8ec7-4b8c5e7e134a.MP4

**Expected result:**
No weirdness like shown in video 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.30/1.30.1

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by kylehickinson** [comment]
I can't seem to reproduce this anymore, can you please re-test

**Comment by srirambv** [comment]
Can't seem to repro as well. Seems to be fixed. The issue does look old so probably got fixed along the way. Still verified with the same device the issue was reported and everything seems fixed. Marking the issue as verified 

https://user-images.githubusercontent.com/17010094/225570304-602f089f-f4f5-46e9-ae38-60d16f44106c.MP4
