### ISSUE TITLE
Update laptop-updates.brave.com certificate

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4061]
The laptop-updates domain will transition to use new certificates soon.
We should bundle the new cert to prepare for that

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 14.7.1` using `1.30.1 (21.8.17.19)`

* ensured that the `Top Tiles` appeared under NTP after on-boarding was completed
* ensured that clicking on each `Top Tile` loaded the correct website
* ensured that `Open in New Tab` via the long tap context menu opens the correct website
* ensured that `Open in New Private Tab` via the long tap context menu opens the correct website
* ensured that editing both titles & URLs via `Edit Bookmarks` works without any issues
* ensured that you can remove tiles without any issues via `Remove Favorite`
* ensured that re-arrange the order of the `Top Tiles` by dragging them around into different positions
* ensured that removing all of the `Top Tiles` didn't cause any issues/crashes

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|----------------|-----------------|---------------
![IMG_8381](https://user-images.githubusercontent.com/2602313/129831559-5c8a23ad-f63f-429e-aee0-09ff61b22a2a.png) | ![IMG_8382](https://user-images.githubusercontent.com/2602313/129831564-5041a0d8-2dea-45a6-b628-d3988c18ad15.png) | ![IMG_8392](https://user-images.githubusercontent.com/2602313/129834070-cbd13d3d-cb9b-475c-bea4-974e44999511.png) | ![IMG_8393](https://user-images.githubusercontent.com/2602313/129834096-4c3613d3-f20c-4714-8533-ce86c3de9cc6.png)

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.7.1` using `1.30.1 (21.8.17.19)`

* ensured that the `Top Tiles` appeared under NTP after on-boarding was completed
* ensured that clicking on each `Top Tile` loaded the correct website
* ensured that `Open in New Tab` via the long tap context menu opens the correct website
* ensured that `Open in New Private Tab` via the long tap context menu opens the correct website
* ensured that editing both titles & URLs via `Edit Bookmarks` works without any issues
* ensured that you can remove tiles without any issues via `Remove Favorite`
* ensured that re-arrange the order of the `Top Tiles` by dragging them around into different positions
* ensured that removing all of the `Top Tiles` didn't cause any issues/crashes

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|----------------|-----------------|---------------
![image](https://user-images.githubusercontent.com/2602313/129837608-82751783-1eeb-43b1-8ec1-15ef2476c48b.png) | ![image](https://user-images.githubusercontent.com/2602313/129837631-f8799a26-e36d-496a-a757-7d0b3195aafe.png) | ![image](https://user-images.githubusercontent.com/2602313/129837647-b4c34d16-fdaa-4520-aca7-cbc3e52cce65.png) | ![image](https://user-images.githubusercontent.com/2602313/129837689-a0c9ac24-8e58-4858-bc3c-0d79f96dde68.png)

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.30.1 (21.8.17.19)`

* ensured that the `Top Tiles` appeared under NTP after on-boarding was completed
* ensured that clicking on each `Top Tile` loaded the correct website
* ensured that `Open in New Tab` via the long tap context menu opens the correct website
* ensured that `Open in New Private Tab` via the long tap context menu opens the correct website
* ensured that editing both titles & URLs via `Edit Bookmarks` works without any issues
* ensured that you can remove tiles without any issues via `Remove Favorite`
* ensured that re-arrange the order of the `Top Tiles` by dragging them around into different positions
* ensured that removing all of the `Top Tiles` didn't cause any issues/crashes

**`Example`** | **`Example`** | **`Example`** | **`Example`**
---------------|----------------|-----------------|---------------
![IMG_0591](https://user-images.githubusercontent.com/2602313/129855419-33fbaea9-9d2e-4e4d-b28d-d0faab782368.png) | ![IMG_0592](https://user-images.githubusercontent.com/2602313/129855427-ab4194c8-1c00-4b3e-8ea2-03e08d29ee72.png) | ![IMG_0593](https://user-images.githubusercontent.com/2602313/129855440-2d06a867-03a9-4b36-b236-0b2f16c61e30.png) | ![IMG_0594](https://user-images.githubusercontent.com/2602313/129855456-d5220809-7945-4002-905d-5d5076fe0aac.png)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.30.1(21.8.17.19)
- Verified favourites show up on NTP on a fresh install 
- Verified favourites show up irrespective of onboarding completion
- Verified focus on URL bar shows second row of favourites for normal install
- Verified for referral installs, custom favourites show up as expected
- Verified selecting URL bar for referral installs shows only one row of custom favourites no default favourites are shown
- Verified for JP locale, clean install sets region specific custom favourites 
- Verified able to edit/remove/add new favourites 
- Verified able to load favourites properly on new tab/private tab
- Verified switching to PB only mode doesn't lose any favourites

![image](https://user-images.githubusercontent.com/17010094/129853229-ada7961c-b8af-4a95-a8ef-dc02b6edd94b.png) | ![image](https://user-images.githubusercontent.com/17010094/129853241-2fa5686d-e902-419b-a7cd-e46f10e5913b.png) | ![image](https://user-images.githubusercontent.com/17010094/129853329-4bb9dd49-e64f-495c-aed7-e5bd3411635f.png) | ![image](https://user-images.githubusercontent.com/17010094/129853342-982a1f97-0375-48ec-bd84-e9048ef1d4ff.png)
-- | -- | -- | -- |
![image](https://user-images.githubusercontent.com/17010094/129853536-dd508193-1fc9-447a-9ff4-e618b9aa64e9.png) | ![image](https://user-images.githubusercontent.com/17010094/129853400-057e39fc-d072-48b1-9a83-28c309a2cb4c.png) | ![image](https://user-images.githubusercontent.com/17010094/129853417-76cc63cb-c38e-4f06-9656-70e31e9652e8.png) | ![image](https://user-images.githubusercontent.com/17010094/129853433-13eba46d-5a2e-47e1-be59-21e219cb23b1.png)


--------------
Verification passed on iPhone XR with iOS 13.5 running 1.30.1(21.8.17.19)
- Verified favourites show up on NTP on a fresh install 
- Verified favourites show up irrespective of onboarding completion
- Verified focus on URL bar shows second row of favourites for normal install
- Verified for referral installs, custom favourites show up as expected
- Verified selecting URL bar for referral installs shows only one row of custom favourites no default favourites are shown
- Verified for JP locale, clean install sets region specific custom favourites 
- Verified able to edit/remove/add new favourites 
- Verified able to load favourites properly on new tab/private tab
- Verified switching to PB only mode doesn't lose any favourites

![IMG_6839](https://user-images.githubusercontent.com/17010094/129855980-79cc13c7-b795-45c5-b72f-206b63798ede.png) | ![IMG_6840](https://user-images.githubusercontent.com/17010094/129855512-cc5c6893-e20e-483d-bc18-386c90ba555e.PNG) | ![IMG_6841](https://user-images.githubusercontent.com/17010094/129855566-e0ff414e-8d45-4e34-bf06-f7b1763ca47f.PNG) | ![IMG_6842](https://user-images.githubusercontent.com/17010094/129855624-80ea9e4c-f06b-4fd9-af4e-c72fe51a0434.PNG)
-- | -- | -- | --
![IMG_6843](https://user-images.githubusercontent.com/17010094/129855700-6cd09444-003c-4e44-a724-4ef2481b4119.PNG) | ![IMG_6844](https://user-images.githubusercontent.com/17010094/129855732-7765d0ed-a487-4bed-b780-97234a8e50ee.PNG) | ![IMG_6845](https://user-images.githubusercontent.com/17010094/129855758-5b9c4963-dcde-450a-869a-a2998014bb07.PNG) | ![IMG_6846](https://user-images.githubusercontent.com/17010094/129855840-76983791-df7e-4695-89d7-69036c91222d.PNG)


---------------
Verification passed on iPhone XR with iOS 13.5 running 1.30.1(21.8.17.19)
- Verified favourites show up on NTP on a fresh install 
- Verified favourites show up irrespective of onboarding completion
- Verified focus on URL bar shows second row of favourites for normal install
- Verified for referral installs, custom favourites show up as expected
- Verified selecting URL bar for referral installs shows only one row of custom favourites no default favourites are shown
- Verified for JP locale, clean install sets region specific custom favourites 
- Verified able to edit/remove/add new favourites 
- Verified able to load favourites properly on new tab/private tab
- Verified switching to PB only mode doesn't lose any favourites

![IMG_0969](https://user-images.githubusercontent.com/17010094/129857915-e9de4e82-d05b-4cdb-be27-36e9db6582d1.PNG) | ![IMG_0970](https://user-images.githubusercontent.com/17010094/129857961-f73515d6-9f8a-4cc3-a931-7b8bdde65637.PNG)  | ![IMG_0971](https://user-images.githubusercontent.com/17010094/129857980-92d38434-c8aa-45ef-b48d-86438c672438.PNG) | ![IMG_0972](https://user-images.githubusercontent.com/17010094/129858049-d979c79c-7e6d-430b-94fe-8545c5c7197d.PNG)
-- | -- | -- | -- 
![IMG_0973](https://user-images.githubusercontent.com/17010094/129858075-862d813d-b004-4856-b074-2f5b3546883b.PNG) | ![IMG_0974](https://user-images.githubusercontent.com/17010094/129858089-7fa7d4a6-5ca7-4782-9770-079d270e167f.PNG) | ![IMG_0976](https://user-images.githubusercontent.com/17010094/129858106-8b8dae8c-330e-4691-84cc-db1733a73de5.PNG) | ![IMG_0977](https://user-images.githubusercontent.com/17010094/129858149-27786040-bf97-424e-ad59-c9239c0b1225.PNG)
