### ISSUE TITLE
Exclude laptop-updates.brave.com from certificate pinning

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4068]
This will match brave-core behavior
see
https://github.com/brave/brave-core/blob/master/chromium_src/net/tools/transport_security_state_generator/input_file_parsers.cc#L408

**Comment by fmarier** [comment]
Not sure what exactly you're planning to do here, but I would suggest excluding the same three hosts as on brave-core, for consistency. That way the iOS TLS config will be exactly the same as brave-core and there won't be any iOS-specific breakage.

**Comment by iccub** [comment]
In general we should audit what urls currently we do not pin which ones we do and try to match desktop as close as possible
