### ISSUE TITLE
Share menu only shares the base URL

### ISSUE THREAD

**Issue by balintbarna** [brave/brave-ios#4071]
### Description: 
Share menu only shares the base URL eg "http://youtube.com/" and not the part after that eg. "watch?v=XXXXXXX"

### Steps to Reproduce 
  1. open youtube website
  2. open videos
  3. copy url using the share menu
  4. paste somewhere so you can see the content

**Actual result:** 
pasted text is base url

**Expected result:**
pasted text is full url

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
seems to be every time

**Brave Version:** 
latest release

**Device details:** 
iPhone SE 2020
latest iOS release

### Additional Information
This is not a duplicate of #3246 or #3746 as the base URL is correct this time, however not the full URL

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.31(21.8.31.19)
- Verified test plan from #4072 

![image](https://user-images.githubusercontent.com/17010094/131710858-e299df71-b191-49d4-9219-7e9cd5c3cb82.png) | ![image](https://user-images.githubusercontent.com/17010094/131710989-d644b272-1f73-4380-8595-37f1165f2dd3.png)
-- | --
------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.31(21.8.31.19)
- Verified test plan from #4072 

![image](https://user-images.githubusercontent.com/17010094/131710483-6ca8cdc6-6b0b-4884-b141-f09f78b67a82.png) | ![image](https://user-images.githubusercontent.com/17010094/131710522-4ddb377e-358c-4019-8d85-82808fd30d81.png)
-- | --

-----------

Verification passed on iPad Pro with iOS 14.6 running 1.31(21.8.31.19)
- Verified test plan from #4072 
  <img width=500 src=https://user-images.githubusercontent.com/17010094/131713222-519d66db-1e04-4fed-ac40-a77299377554.png>
