### ISSUE TITLE
Intermittent Issue while displaying the History when Sync is enabled

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#4073]
Description:
There are some reports from users when Sync is enabled for History, viewing History Page can cause a crash.
Crash Report from Xcode is added for the problem.

Crash Log From Xcode:

[Dlo5sItyGy7nM8t_opLIJ.xccrashpoint.zip](https://github.com/brave/brave-ios/files/7015637/Dlo5sItyGy7nM8t_opLIJ.xccrashpoint.zip)

Steps to Reproduce

- Enable History Sync
- Open History Screen from the options menu

Actual result:
Users reporting rare crashes

Expected result:
The history screen should be viewed properly

Reproduces how often: [Easily reproduced, Intermittent Issue]
Intermittent Issue

Brave Version:
1.30.1 (21.8.17.19

Device details:
Crash reports are mainly from iPhone 12
OS 14.6 14.7

Website problems only:
did you check with Brave Shields down? NA
did you check in Safari/Firefox (WkWebView-based browsers)?NA

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.31(21.9.1.16)
- Verified test plan from https://github.com/brave/brave-ios/pull/4074
- Verified no crash when opening history page with history entries after sync is enabled
- Verified no crash when opening history page without any history after sync is enabled
--------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.31(21.9.1.16)
- Verified test plan from https://github.com/brave/brave-ios/pull/4074
- Verified no crash when opening history page with history entries after sync is enabled
- Verified no crash when opening history page without any history after sync is enabled
--------
Verification passed on iPad Pro with iOS 14.6 running 1.31(21.9.1.16)
- Verified test plan from https://github.com/brave/brave-ios/pull/4074
- Verified no crash when opening history page with history entries after sync is enabled
- Verified no crash when opening history page without any history after sync is enabled
