### ISSUE TITLE
Rendered pages disappear

### ISSUE THREAD

**Issue by gettyhub** [brave/brave-ios#4078]
### Description: 
Pages don't stay rendered when coming back to brave later.

### Steps to Reproduce 
  1.  Open some pages in one or more tabs
  2.  Go on to something else, possibly triggered by device going back to sleep or some other activity that makes brave inactive
  3.  Come back to brave later
  4. Find that brave kept track of pages in tabs in webpage titles only, but none of them previously rendered are now rendered and there is no link in the address bar
  5. Trying to refresh the page doesn't render the page (maybe it thinks the page is about:blank?), maybe going back through history the page can be manually rerendered

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
Most recent versions

**Device details:** 
iOS 13

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Does it happen to you on latest version 1.30.1? We fixed one thing with blank tabs when you switch or close a tab

**Comment by gettyhub** [comment]
Latest I have is 1.29, but app store hasn't shown 1.30 update, unless I manually go to brave and now it shows that there is an update.  So I'll have to mess around to see if it still messes up.  

It is usually when I go away from brave and come back later, not necessarily just opening/closing tabs.

**Comment by gettyhub** [comment]
Looks like it is still doing it under 1.30.

Maybe the memory is running out on the rig and it tries to reload brave and can't complete the task.  But it was working some revisions ago just fine like the regular desktop version.

**Comment by iccub** [comment]
@gettyhub can you recheck it on 1.30.1?
You might have to go to app store app to update it manually, it's at staged rollout right now

The disappearing webview bug was introduced in 1.29 and fixed in 1.30.1

**Comment by gettyhub** [comment]
I think we are talking about two different bugs

**Comment by gettyhub** [comment]
My bug is still present on 1.30.1

**Comment by iccub** [comment]
Thanks for confirming @gettyhub, we will try to reproduce it on our end and fiix

**Comment by gettyhub** [comment]
After I turned off firewall app, because Safari needs a blocker but not brave, it seems to have cleared up.  Why it affects brave and not safari  I'm not sure.  The firewall app lets you look at a page and then it asks if you want to see it or not.  Strange.

**Comment by iccub** [comment]
what is this firewall app name if you don't mind answering?

**Comment by gettyhub** [comment]
AppFirewall on a jailbroken iOS.

**Comment by iccub** [comment]
@gettyhub 
It could be due to blocking `localhost` ip perhaps or a port.
Our new tab page as well as restored pages(until they are reloaded) are served on a local web server, on port `6571`

**Comment by gettyhub** [comment]
Just did a nmap on that port.  Port is closed.

And if it was in app firewall, don’t know cause I wiped out the entries after disabling its on brave.

Another fellow seems to be reporting the same behavior and probably not using an app firewall.

https://github.com/brave/brave-ios/issues/4150

**Comment by gh0sti** [comment]
Im using nextdns for blocking dns queries. Doesnt matter if I'm on LTE or any wireless connection I lose my web pages or they don't stay static.

**Comment by gettyhub** [comment]
I hit the home button twice and killed brave that way when pages disappear.  When I bring brave back up it recovers the pages or says oops now this is embarrassing and restores the pages.

**Comment by gettyhub** [comment]
Not sure if it is related, but youtube pages hang during scrolling up and down.

**Comment by iccub** [comment]
@gettyhub we made some improvements, currently live in public beta 1.32.5
Here's link if you are interested in trying it out https://testflight.apple.com/join/Trcbh1o3

**Comment by gh0sti** [comment]
@iccub just tried latest beta in testflight still having the same issue on iphone 13 pro max iOS 15.1 rendered pages will disappear after restarting brave browser.

**Comment by iccub** [comment]
@gh0sti  what public beta version is it `1.32.5 (21.11.9.22)`?

**Comment by gettyhub** [comment]
My beta version only shows 1.31 (21.8.31.9) and my regular brave shows 1.32 (21.10.13.18)

**Comment by gh0sti** [comment]
@iccub that exact one from testflight 1.32.5 (21.11.9.22)

**Comment by gettyhub** [comment]
Apparently I have to select a build.  The one I’m on now didn’t come back even after knocking off brave from the background.  How do I select which build?

**Comment by iccub** [comment]
@gettyhub maybe you have to rejoin again idk https://testflight.apple.com/join/Trcbh1o3
In TestFlight it should point to latest 1.32.5 build

**Comment by gh0sti** [comment]
@iccub Also tried 21.11.10.20 still same issue

**Comment by gettyhub** [comment]
> @gettyhub maybe you have to rejoin again idk https://testflight.apple.com/join/Trcbh1o3
> In TestFlight it should point to latest 1.32.5 build

Possibly it needs the more updated firmware.  I haven’t updated the firmware since I bought it used. So the version I am running maybe the limit.

**Comment by gettyhub** [comment]
I have one place for a tab here, but there’s not a tab there.  That’s kind of weird.

**Comment by iccub** [comment]
Did you get a chance to check out latest Brave builds @gettyhub, I wonder if this still happens to you

**Comment by gettyhub** [comment]
> Did you get a chance to check out latest Brave builds @gettyhub, I wonder if this still happens to you

Testflight wouldn’t let me go past a certain older version, possibly because I haven’t updated firmware.  One of my androids started doing something similar.  It wouldn’t even let me get to the pages.  Even downgrading or uninstalling/reinstalling wouldn’t correct it.
