### ISSUE TITLE
Arithmetic queries from omnibar that end in decimals attempt to direct to a url instead of returning search results

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4081]
### Description: 
Arithmetic queries from omnibar that end in decimals attempt to direct to a url instead of returning search results

Example: 21*19*8.8 will try to go to http://21*19*8.8 instead of calculating in search.

Link: https://bravesoftware.slack.com/archives/C01P8A0QHKP/p1629745351049300

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.31(21.9.8.16) 
- Verified test plan from https://github.com/brave/brave-ios/pull/4121#issuecomment-917012712
-----------
Verification passed on iPhone 7+ with iOS 14.51 running 1.31(21.9.13.20) 
- Verified test plan from https://github.com/brave/brave-ios/pull/4121#issuecomment-917012712
-----------
Verification passed on iPhone XR with iOS 14.6 running 1.31(21.9.13.20) 
- Verified test plan from https://github.com/brave/brave-ios/pull/4121#issuecomment-917012712
