### ISSUE TITLE
Revisiting a search link isn’t replacing the safe url elements

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4082]
### Description: 
Link: https://bravesoftware.slack.com/archives/C01NNFM9XMM/p1629374812029500

Per @jamesmudgett, 

>it seems like revisiting a search link isn’t replacing the safe url elements, in this case space

![Image from iOS](https://user-images.githubusercontent.com/7606853/130507373-508c5c69-75d1-4454-b5ab-3f966b03ef8a.png)

James also notes
> may be an issue in iOS and recent searches

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 12` running `iOS 14.8` using `1.31 (21.9.14.15)`

* verified the STR/Cases via https://github.com/brave/brave-ios/pull/4118#issuecomment-917007494

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.8` using `1.31 (21.9.14.15)`

* verified the STR/Cases via https://github.com/brave/brave-ios/pull/4118#issuecomment-917007494

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.31 (21.9.14.15)`

* verified the STR/Cases via https://github.com/brave/brave-ios/pull/4118#issuecomment-917007494
