### ISSUE TITLE
Update the "Could not connect to Server" screen

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4083]
### Description: 

This screen could do would a fresh coat of paint and some copy updates. 

![Error Screen on iOS](https://user-images.githubusercontent.com/7606853/130521536-a8f134f8-6389-410f-b9b2-a867e20986c3.jpeg)

**Comment by iccub** [comment]
There's been some work done already https://github.com/brave/brave-ios/issues/483

**Comment by kylehickinson** [comment]
Can this be closed since https://github.com/brave/brave-ios/issues/4338 is closed?
