### ISSUE TITLE
Brave searches on Google when using Spotlight even after changing the default search engine to Startpage.

### ISSUE THREAD

**Issue by riceset** [brave/brave-ios#4091]
### Description: 
Brave searches on Google when using Spotlight even after changing the default search engine to Startpage.

### Steps to Reproduce 
  1. Go to the iOS home screen.
  2. Swipe down.
  3. Enter a search query and tap the Brave icon to search.

**Brave Version:**
1.30.1

**Comment by kylehickinson** [comment]
Hi @riceset, unfortunately this is an iOS issue and Brave cannot fix it as Apple has not provided any API to us to change what URL they construct when you search using spotlight. The search engine used there will be whichever is selected for Safari (which can be changed in Settings.app > Safari > Search Engine)
