### ISSUE TITLE
Audio keeps playing when you open the 3-dot menu and close it even if all tabs are closed.

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#4092]
### Description: 
- Audio keeps playing when you open the 3-dot menu and close it even if all tabs are closed.

### Steps to Reproduce 
  1. Go to youtube.com in a new tab.
  2. Play a video
  3. Open 3-dot menu.
  4. Close 3-dot menu.
  5. Close tab.

**Actual result:** 
- Audio continues to play

**Expected result:**
- Tab should deallocate and audio should stop playing.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
Any

**Device details:** 
Any

**Website problems only:**
N/A

### Additional Information
- Happens due to a leak in the 3-Dot menu and share activity.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.31(21.9.1.16)
- Verified steps from issue description
--------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.31(21.9.1.16)
- Verified steps from issue description
------------
Verification passed on iPad Pro with iOS 14.6 running 1.31(21.9.1.16)
- Verified steps from issue description
