### ISSUE TITLE
Default search engine resets during upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4096]
### Description: 
Search Engine resets when default is set to Brave Search. Issue originally reported internally by @murphyd 

### Steps to Reproduce 
  1. Install 1.30.1 and select Brave Search beta as default during onboarding
  2. Upgrade to 1.31
  3. Default search engine is reset to Google 

**Actual result:** 
Default search engine resets during upgrade

**Expected result:**
Should retain the default search engine settings

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.31

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by iccub** [comment]
Fixed here https://github.com/brave/brave-ios/pull/4095
Please reopen if this bug still happens to you

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.31(21.8.31.19)
- Verified default search engine is retained during upgrade
------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.31(21.8.31.19)
- Verified default search engine is retained during upgrade
------
Verification passed on iPad Pro with iOS 14.6 running 1.31(21.8.31.19)
- Verified default search engine is retained during upgrade
