### ISSUE TITLE
Update setting for Playlist toast

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#4098]
Title: Show Menu Notification Badge
Description: When enabled, a badge will be displayed on the main menu icon, indicating media on the page may be added to Brave Playlist.
Default: true

![IMG_2943](https://user-images.githubusercontent.com/318119/131169449-b33cb024-0b7b-4083-b1a3-d578fd71b09d.PNG)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.31(21.9.14.15)
- Verified test plan from [#4106](https://github.com/brave/brave-ios/pull/4106)
- Verified setting is enabled by default 
- Verified when setting is enabled badge is show no menu
- Verified when setting is disabled badge is not shown on menu

Setting On | Setting Off | Badge Shown | Badge Hidden
-- | -- | -- | -- | 
![image](https://user-images.githubusercontent.com/17010094/133409920-f8d9a02d-b798-49c2-9739-e16b70b219d2.png) | ![image](https://user-images.githubusercontent.com/17010094/133409933-bfa35c5c-1c4f-4897-a4a8-042e0969cbb0.png) | ![image](https://user-images.githubusercontent.com/17010094/133409960-a0ecf6e7-0b13-4e2d-b6ab-0874f4631e27.png) | ![image](https://user-images.githubusercontent.com/17010094/133409985-d725341d-c43c-4d84-8468-23b2a562a108.png)

------------
Verification passed on iPhone 7+ with iOS 14.8 running 1.31(21.9.14.15)
- Verified test plan from [#4106](https://github.com/brave/brave-ios/pull/4106)
- Verified setting is enabled by default 
- Verified when setting is enabled badge is show no menu
- Verified when setting is disabled badge is not shown on menu

Setting On | Setting Off | Badge Shown | Badge Hidden
-- | -- | -- | --  
![image](https://user-images.githubusercontent.com/17010094/133409308-6d6b5cfd-f15a-4f02-a03f-692e42cd8ac6.png) | ![image](https://user-images.githubusercontent.com/17010094/133409330-ceef6856-8d2e-4f3d-9689-1b0e482d31d1.png) | ![image](https://user-images.githubusercontent.com/17010094/133409404-51b7096d-fbff-48a1-b9a2-4e3754f5c6c8.png) | ![image](https://user-images.githubusercontent.com/17010094/133409365-3f2dfbea-34f0-477d-9eca-e4c64cd8323d.png)

------------
Verification passed on iPad Pro with iOS 15 running 1.31(21.9.14.15)
- Verified test plan from [#4106](https://github.com/brave/brave-ios/pull/4106)
- Verified setting is enabled by default 
- Verified when setting is enabled badge is show no menu
- Verified when setting is disabled badge is not shown on menu

Setting On | Setting Off | Badge Shown | Badge Hidden
-- | -- | -- | -- | 
![image](https://user-images.githubusercontent.com/17010094/133411328-47820609-ccaa-476e-bcb8-cc2b682e18f0.png)| ![image](https://user-images.githubusercontent.com/17010094/133411214-eccda4ee-8a5d-410d-ae28-2d3dca0246f4.png) | ![image](https://user-images.githubusercontent.com/17010094/133411165-b6e59582-fb85-4906-88a7-f9b539a9aed0.png) | ![image](https://user-images.githubusercontent.com/17010094/133411132-5c5ce603-3746-4e1b-9e2c-daf4f3087796.png)
