### ISSUE TITLE
IMDB Website not showing Playlist Error when it should

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#4099]
### Description: 
- IMDB's website has a misconfigured HLS stream. It allows you to add to playlist but shows nothing when it can't play the stream.
- It should definitely show an error when the stream cannot be played due to misconfiguration of any kind. Instead, the error is silently hidden.

### Steps to Reproduce 
  1. Go to: https://m.imdb.com/title/tt13495314/?ref_=fn_al_tt_1
  2. Do NOT play the trailer.
  3. Add it to playlist via the 3-dot menu.

**Actual result:** 
- Stream will NOT play

**Expected result:**
- Should show an error

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.31

**Device details:** 
Any

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.32(21.10.6.16)
- Verified steps from issue description

iPhone XR (iOS 15.0.1) | iPhone 7+ (iOS 14.8) | iPad Pro (iOS 15.1 Beta 3)
-- | -- | --
<img width=250 src=https://user-images.githubusercontent.com/17010094/136544061-aae45d17-ea5a-4e83-b26c-f4ff6f978c4f.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/136544115-a0cf8e9a-7574-412a-a011-4e942bdf8b44.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/136544089-e665dc69-9f1e-42ec-bac9-2c9f13e354b0.png>
