### ISSUE TITLE
No scanner button to sync on iOS

### ISSUE THREAD

**Issue by dai10512** [brave/brave-ios#4101]
### Description: 
First, I wanted to sync brave with desktop browser and iOS browser. Desktop Brwoser let me scan QR code by iOS browser, in detail they tell us to move to "settings" and "brave sync", finally push the buton "scan to sync QR code". But acctually, such buton couldn't be found by iOS.  

### Steps to Reproduce 
  1. desktop display 
<img width="400" alt="スクリーンショット 2021-08-28 9 58 30 png_墨消し済み" src="https://user-images.githubusercontent.com/38497198/131201926-373d17c0-7cde-4505-b4e7-d1eaae729157.png">

  2. iOS [settings]
  (1)
 <img width="300" alt="IMG_0601 jpeg_墨消し済み" src="https://user-images.githubusercontent.com/38497198/131201811-583221f4-d635-49da-b8af-376c8e1b7ae8.PNG">
  (2)
<img width="300" src="https://user-images.githubusercontent.com/38497198/131201794-4beb31d1-1de3-4872-ac39-a684bd8eebab.jpeg">
  (3) issue
<img width="400" alt="IMG_0601 jpeg_墨消し済み" src="https://user-images.githubusercontent.com/38497198/131201772-e2104a7f-9d61-4d48-91ea-63822e8d35b5.png">

**Actual result:** 
No scanner button to sync on iOS

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Brandon-T** [comment]
Hi @dai10512 

Your phone shows that you already have a sync chain created.
In order for the phone to scan the Desktop QR Code, the phone cannot be in a sync chain.
If the sync chain is already created on the phone, then you need to join that sync chain on Desktop.
If the sync chain is created on Desktop, then your phone needs to join the Desktop sync chain.

However, in your case, you have a sync chain on phone, and a different sync chain on Desktop, so you won't see the scan button.
If you want the phone to scan the Desktop QR Code, then you need to "Leave Sync Chain" on the phone, then scan the Desktop QR Code.
