### ISSUE TITLE
Playlist: no way to play video in the background with a different speed

### ISSUE THREAD

**Issue by shamrin** [brave/brave-ios#4102]
### Description

Brave iOS Playlist resets the video speed to 1x when playing in the background. There's no way to play video other than on 1x when the screen is locked.

### Steps to Reproduce 

  1. Start playing a video in the Playlist.
  2. Change the speed to 2x.
  3. Lock the screen. (Video is paused.)
  4. Start the video again from control on the lock screen.

**Actual result:**

The video is played (in the background) with 1x speed.

**Expected result:**

The video should be played with 2x speed.

**Reproduces how often:**

Every time.

**Brave Version:** 

1.30.1 (21.8.17.19)

**Device details:** 

iPhone 11 (iOS 13.6)

### Additional Information

Possibly related: https://community.brave.com/t/playlist-keeps-resetting-speed-on-play-wont-persist-across-videos-or-after-pause/269748

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.31(21.9.13.20)
- Verified steps from issue description
- Encountered [#4159](#4159) & [#4161](#4161)
-------
Verification passed on iPad Pro with iOS 14.6 running 1.31(21.9.13.20)
- Verified steps from issue description
- Encountered [#4159](#4159) & [#4161](#4161)
