### ISSUE TITLE
Brave Search api returns error 403

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4103]
### Description: 
It's due to us not passing User-Agent header to the /can/answer request

### Steps to Reproduce 
Must be done on Dev build
  1. Enable Brave Search debug
  2. Enable `Fallback mixing` from settings at search.brave.com
  2. Query for `Super Brave` at search.brave.com
  3. Go to Brave Search debug menu

**Actual result:** 
No response is returned

**Expected result:**
Should be able to see response times

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.31(21.9.8.16)
- Verified test plan from issue description
-------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.31(21.9.13.20)
- Verified test plan from issue description
-------
Verification passed on iPad Pro with iOS 14.6 running 1.31(21.9.13.20)
- Verified test plan from issue description
