### ISSUE TITLE
Remove playlist item from url bar button does not always work

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4111]
### Steps to Reproduce 
1) add to Brave playlist
2) open in playlist
3) tap done
4) tap button in url bar
5) tap remove

**Actual result:** 
Fails to remove

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 15 running 1.31(21.9.14.15)
- Verified steps from issue description
- Verified able to remove playlist item from button 
-----------
Verification passed on iPhone 7+ with iOS 14.8 running 1.31(21.9.14.15)
- Verified steps from issue description
- Verified able to remove playlist item from button 
-----------
Verification passed on iPhone XR with iOS 13.5 running 1.31(21.9.14.15)
- Verified steps from issue description
- Verified able to remove playlist item from button
