### ISSUE TITLE
Implement Logins & Password Screens

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#4112]
## Problem Description 

The iOS Browser should have screen where Passwords & Logins can be viewed and interacted. This controller should include list of saved logins, and also actions like edit, delete and search etc.

## Feature Overview 

The Passwords & Logins feature will contain a new security menu item for Passwords & Logins. The item will represent user the list of password being saved and provide some functionality over the list like deleting and searching. Every password & login item will redirect to a detail screen where user can update, delete and do some actions like fill & open.

## Design 

![131541463-01fd590e-3b0d-4b99-b192-abfb31122c0c](https://user-images.githubusercontent.com/6643505/131563090-69dfd755-d897-4d61-a7f0-001a7b3b94e6.png)

## Implementation Details 

First Part List Screen:

-  A new entry point will be added in Settings under Security Section for Logins & Passwords.
- The controller will present the a search bar for filtering the login items for username and hostname (website)
- Saved Logins toggle and Show in Application Menu toggle will be places in list screen.
- The saved login items will be displayed in list style and favicon, hostname and account name will also be displayed in every row.
- There will be edit table functionality where we can activate edit mode for the list view and in addition swipe to delete items will be supported.
- A alert will prompted when user wants to delete an login item for approval.

Second Part Detail Screen:

- Detail screen will include information showing Website, Username, Password, Created Date.
- The password will be shown in secure mode until edit is activated and there will be delete button that will be prompting the alert for deleting the actual login & password item.
- The edit mode will activate username as the responder and return item for the keyboard will be next.
- Selecting password item will show the password and changing the responder to a separate field should re-active secure field.
- Pressing done either on navigation bar or in keyboard to end editing will save the changes.
- Delete button will work same way in lis screen which will propmt a alert and if okay is selected it will delete the item and navigate list screen.
- Website, Name and Password rows will have a click actions when it is table is not in edit mode. these actions will vary which item is clicked on.

## User Experience 

1. Navigate to Settings and security section Logins & Password menu item will be present
2. Clicking this menu item will present the password list screen described above
3. Filtering/Searching can be activated by clicking the search field
4. Any item can be deleted using swipe to delete or by pressing the edit mode in navigation bar
5. Enabling Saved Logins Toggle will activate the existing save login functionality like before
6. Enabling Show in Application Menu toggle will add Passwords as a menu item under directly under application for easy accessing like History Bookmarks etc
7. Clicking any password item will open up details about the login item 
8. Editing can be enabled by clicking the edit button on navigation bar
9. After deleting any item, the view for listing the passwords will be navigated automatically.
10. Website, Username and Password item will have click action when the list is not in edit mode. Website row will have Copy - Open & Fill, Username will have Copy and Password will have Copy and Reveal actions that can be clicked.

### Additional information 

Also for enhancing the security the password screen will also include blur background when application is not on active display and if browser lock is on the entry to passwords screen will also require Authentication. (This will mimic the password screen implementation of iOS Passwords screen)

https://user-images.githubusercontent.com/6643505/131565277-4aea34ee-43f5-4409-951d-42078a86066b.MP4

![1 6](https://user-images.githubusercontent.com/6643505/131565667-370dbfc4-9d8d-4bda-9533-faa7d18e46fc.png)

When user enabled the Show in Application Menu Toggle, the menu item will be presented in Setting Menu for easy access.

![1 8](https://user-images.githubusercontent.com/6643505/131565677-72d0bba6-6063-4894-862c-3bd84317a137.png)

**Comment by iccub** [comment]
Reopening, code is merged but hidden from UI until we are ready to test it

**Comment by soner-yuksel** [comment]
The Restore PR is merged #4743.

The feature can be tested with 1.34

**Comment by soner-yuksel** [comment]
Ability of showing passwords on main settings page is removed along with the Show in Application Menu Toggle in password list screen.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.34 (22.1.5.15)
- Verified a new setting is available for `Logins & Passwords` under Security
- Verified `Save Logins` is enabled by default
- Verified disabling `Save logins` doesn't prompt save logins prompt on sites
- Verified selecting `Save Login` automatically saves the credentials under `Logins & Passwords`
- Verified opening a saved credentials and clicking on the website brings up popup for `Copy` and `Open & Fill`
- Verified selecting `Open & Fill` loads a new tab and auto-populates the credentials 
- Verified visiting a site with saved credentials auto-populates the credentials
- Verified clicking on the username  shows popup to copy the username
- Verified clicking on the password filed shows popup for `Copy` and `Reveal`
- Verified selecting `Reveal` shows the password in plain text
- Verified selecting `Copy` copies username/password to clipboard
- Verified able to delete a credential from details view, list view
- Verified opening a credential shows the date it was saved on
- Verified searching for a credential filters out the matching records
- Verified when no matching result is found shows message `No logins found`
- Verified when biometric lock for app is enabled, opening `Logins & Passwords` requests biometric unlock
- Verified password won't autofill on private tabs
- Verified save password is not prompted for private tabs

![image](https://user-images.githubusercontent.com/17010094/148570790-6975796a-1383-4676-946e-d756329acd09.png) | ![image](https://user-images.githubusercontent.com/17010094/148570807-e4b2312a-7fe0-4f11-bb1e-d1fa92a8e1dc.png) | ![image](https://user-images.githubusercontent.com/17010094/148570832-68084819-74a4-448b-a8bb-9fb97a0e94cc.png) | ![image](https://user-images.githubusercontent.com/17010094/148570839-cd7f5e03-8294-4e0e-b96f-338934de6731.png) | ![image](https://user-images.githubusercontent.com/17010094/148570854-d0299e56-e363-4201-9ac7-bd645682580e.png)
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/148570878-66900196-f4f3-4404-9203-c58e97289621.png) | ![image](https://user-images.githubusercontent.com/17010094/148570893-9400ee5e-d5fb-480f-b074-93808a850df2.png) | ![image](https://user-images.githubusercontent.com/17010094/148570904-01bfd660-a443-484a-885d-18cc4fdd2b9c.png) | ![image](https://user-images.githubusercontent.com/17010094/148570926-65d22da2-9a29-4ddd-b8da-3eda437572f9.png)


----------
Verification passed on iPhone XR with iOS 15.2 running 1.34 (22.1.5.15)
- Verified a new setting is available for `Logins & Passwords` under Security
- Verified `Save Logins` is enabled by default
- Verified disabling `Save logins` doesn't prompt save logins prompt on sites
- Verified selecting `Save Login` automatically saves the credentials under `Logins & Passwords`
- Verified opening a saved credentials and clicking on the website brings up popup for `Copy` and `Open & Fill`
- Verified selecting `Open & Fill` loads a new tab and auto-populates the credentials 
- Verified visiting a site with saved credentials auto-populates the credentials
- Verified clicking on the username  shows popup to copy the username
- Verified clicking on the password filed shows popup for `Copy` and `Reveal`
- Verified selecting `Reveal` shows the password in plain text
- Verified selecting `Copy` copies username/password to clipboard
- Verified able to delete a credential from details view, list view
- Verified opening a credential shows the date it was saved on
- Verified searching for a credential filters out the matching records
- Verified when no matching result is found shows message `No logins found`
- Verified when biometric lock for app is enabled, opening `Logins & Passwords` requests biometric unlock
- Verified password won't autofill on private tabs
- Verified save password is not prompted for private tabs

![image](https://user-images.githubusercontent.com/17010094/148570146-e48ebd00-49cf-4ab8-9c97-d02ecf497412.png) | ![image](https://user-images.githubusercontent.com/17010094/148570190-3b128f64-ea5f-4d19-962a-c1edfcf2dfae.png) | ![image](https://user-images.githubusercontent.com/17010094/148570205-dd102c01-11d0-4c7b-84c7-ad9b89f6802a.png) | ![image](https://user-images.githubusercontent.com/17010094/148570224-f22e3eba-0345-4463-a182-fa359eb50fc3.png) | ![image](https://user-images.githubusercontent.com/17010094/148570252-a1556ded-e9fe-47c6-94ce-eaa746445ebf.png) | ![image](https://user-images.githubusercontent.com/17010094/148570496-83c07a85-1f40-4a27-b8e4-e00aff24ba9b.png)
-- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/148570278-a6790a24-1dce-4c7e-b759-d4b41b3f25b9.png) | ![image](https://user-images.githubusercontent.com/17010094/148570290-767ae6ba-4bef-4b2d-b7c5-25cd9738058a.png) | ![image](https://user-images.githubusercontent.com/17010094/148570309-bd173d07-fa5e-4ee2-bb4e-79d7f12d1e63.png) | ![image](https://user-images.githubusercontent.com/17010094/148570326-00432cca-748a-4c5f-bb31-31963c141277.png) | ![image](https://user-images.githubusercontent.com/17010094/148570461-7178f3ec-f2ad-44cb-b2d9-ed0894f29d24.png)


----------
Verification passed on iPad Pro with iOS 15.3 running 1.34 (22.1.5.15)
- Verified a new setting is available for `Logins & Passwords` under Security
- Verified `Save Logins` is enabled by default
- Verified disabling `Save logins` doesn't prompt save logins prompt on sites
- Verified selecting `Save Login` automatically saves the credentials under `Logins & Passwords`
- Verified opening a saved credentials and clicking on the website brings up popup for `Copy` and `Open & Fill`
- Verified selecting `Open & Fill` loads a new tab and auto-populates the credentials 
- Verified visiting a site with saved credentials auto-populates the credentials
- Verified clicking on the username  shows popup to copy the username
- Verified clicking on the password filed shows popup for `Copy` and `Reveal`
- Verified selecting `Reveal` shows the password in plain text
- Verified selecting `Copy` copies username/password to clipboard
- Verified able to delete a credential from details view, list view
- Verified opening a credential shows the date it was saved on
- Verified searching for a credential filters out the matching records
- Verified when no matching result is found shows message `No logins found`
- Verified when biometric lock for app is enabled, opening `Logins & Passwords` requests biometric unlock
- Verified password won't autofill on private tabs
- Verified save password is not prompted for private tabs

![image](https://user-images.githubusercontent.com/17010094/148569451-dd66cc10-da16-468d-8df4-4c16abb53bda.png) | ![image](https://user-images.githubusercontent.com/17010094/148569469-810b2f3f-047f-4778-a637-ab7461b340cc.png) | ![image](https://user-images.githubusercontent.com/17010094/148569482-5afff866-9354-41f3-bd21-80487ba89fc2.png) | ![image](https://user-images.githubusercontent.com/17010094/148569495-ce4432ca-5103-48b3-843a-5efed0676286.png)  |![image](https://user-images.githubusercontent.com/17010094/148569740-e2d9ecdb-0f4d-4daf-8c6d-02f1add27530.png)
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/148569825-e473308b-027e-4f6e-b993-c847556c9f5a.png) | ![image](https://user-images.githubusercontent.com/17010094/148569865-a3004a3a-53c5-467f-ab9d-4c48b489a179.png) | ![image](https://user-images.githubusercontent.com/17010094/148569892-cde2ddff-a034-4114-85cf-932ea9e3d34d.png) | ![image](https://user-images.githubusercontent.com/17010094/148569923-97fd5c59-f224-446a-85c0-0a7f00bb1957.png)

------

Encountered #4814
