### ISSUE TITLE
Fix new settings strings

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4116]
### Description: 
Fix new settings strings

### Steps to Reproduce 
  1.  Install 1.31 build
  2. Check text on new settings
  3. Seems confusing

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/131674204-500ad6d1-39b3-4ae4-b5a0-fcfbb532e760.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/17010094/131674226-f7c37507-ea26-4e59-87bd-171b162239ad.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.31(21.8.31.9)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 12` running `iOS 14.8` using `1.31 (21.9.14.15)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 14.8` using `1.31 (21.9.14.15)`
* Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.31 (21.9.14.15)`

**`iPhone iOS 14.8`** | **`iPad Air (3rd Gen) iOS 14.8`** | **`iPad Mini 4 iOS 13.7`**
-----------------------|---------------------------------|-----------------------------
![IMG_9029](https://user-images.githubusercontent.com/2602313/133372686-a2d4b27e-8b1e-4d0b-b3c2-2624e345f39c.PNG) | ![IMG_9F84DD200090-1](https://user-images.githubusercontent.com/2602313/133372931-781fe802-0bbc-4774-b38b-8642f1d48890.jpeg) | ![IMG_0060598AE042-1](https://user-images.githubusercontent.com/2602313/133373443-6e1677c4-93f5-4202-8378-7a38a6a09416.jpeg)
