### ISSUE TITLE
Brave Beta is not registered as a browser 

### ISSUE THREAD

**Issue by iam-cult** [brave/brave-ios#4117]
### Description: 
Brave Beta is not registered in the settings as a browser, and is not on the list of browsers for default browser

### Steps to Reproduce 
  1. Install Brave Beta
  2. Go to the Brave Beta Settings entry
  3. Attempt to set it as default browser

**Actual result:** 
![image](https://user-images.githubusercontent.com/65368815/131676203-1f216a1f-87e2-4a0c-8875-400859116b53.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/65368815/131676275-57d0dad9-8411-4c2e-beee-8d234eeb924d.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 

Version 1.31 (21.8.31.9)

**Device details:** 

Device iPhone12,8 (iOS 14.7)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

**Comment by iccub** [comment]
more details here https://github.com/brave/brave-ios/issues/4943

perhaps one day we will use a single app for beta and prod builds
