### ISSUE TITLE
Incorrect favicons on clean install

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4120]
### Description: 
Incorrect favicons on clean install

### Steps to Reproduce 
  1. Clean install 1.30.1 or 1.31
  2. Open new tab
  3. Favicons are wrong on default favourites

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/131686435-f0a5a2a8-4e2b-4fb0-bd6c-e10ca3c44c68.png)

**Expected result:**
Correct favicons for favourites

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent issue

**Brave Version:** 
1.30.1 and 1.31 possibly on older builds as well

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
Possibly related to #3345, #3818 &  #3986

**Comment by Uni-verse** [comment]
Verification completed using `1.36 (22.3.2.9) BraveCore 1.36.108 (99.0.4844.51)`

**PASSED** on `iPhone 12 Pro | iOS 15.1.1`
**PASSED** on `iPhone X | iOS 14.4.2`
**PASSED** on `iPad (7th Gen) | iOS 15.2.1`

- Verified favicons are rendering properly on clean install/relaunch

Scenarios Tested: https://github.com/brave/brave-ios/pull/5001#issue-1143452835

- [x] Re-installed app many times 
- [x] Re-launched app continuously
