### ISSUE TITLE
QR scanner doesn’t show domain before opening

### ISSUE THREAD

**Issue by kaytwo** [brave/brave-ios#4126]
### Description: 

QR code scan notification from stock camera app does not show hostname before visiting URL.

### Steps to Reproduce 
  1. Set brave as default browser
  2. Open stock camera, point at QR code
  3. Observe “open in brave” with no host name shown

**Actual result:** 

![4ED30232-7D36-440F-AD8C-DE94961332B3](https://user-images.githubusercontent.com/587187/131856153-862c2da5-b225-41e0-a9de-3b23ac335b7a.png)

**Expected result:**

(With safari as default browser)

![3B57E0F7-2857-4C74-8808-0B9990DC73D6](https://user-images.githubusercontent.com/587187/131856158-ba7ec292-1296-406b-9a66-365186b12d3f.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100%

**Brave Version:** 

1.30.1

**Device details:** 

12 mini
14.7.1 
**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 
Yep

### Additional Information
Thank you!

**Comment by kylehickinson** [comment]
Hi @kaytwo, unfortunately we have no control over what the stock Camera app does when scanning QR codes so we won't be able to do anything to fix this. We will keep an eye out for Apple releasing some sort of API to help with this in future releases.
