### ISSUE TITLE
Hide or Alter 'Favorites' Label in Absence of Favorites

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ios#4128]
### Description: 
If there are no favorites to show, hide (or perhaps alter) the "Favorites" label when the user focuses the address bar.

### Steps to Reproduce 
  1. Delete all favorites via long-press on NTP favicons
  2. Focus address bar

**Actual result:** 
Note "Favorites" Label is shown without any favorites beneath.

**Expected result:**
No label, or perhaps "No favorites" shown instead. The latter could still be confusing for users.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy.

**Brave Version:** 
1.30.1

### Additional Information
Reported [on Twitter](https://twitter.com/armandcerna/status/1433458676916899840). 
![image](https://user-images.githubusercontent.com/815158/131894290-b8303672-f237-46ba-ac53-000a9e643532.png)

**Comment by gprabaga-ford** [comment]
@iccub  I made fix for this bug in local, shall I raise PR for this?

**Comment by prabagaranganesan** [comment]
@iccub I made fix for this bug in local, shall I raise PR?

**Comment by srirambv** [comment]
<details>
<summary>Verification passed on iPhone 7+ with iOS 14.8 running 1.32.1(21.10.18.10)</summary>

With Favourites | Without Favourites | Without recent search history
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/137869866-5e08e712-c5a1-4b42-b794-27fafea55ef3.png) | ![image](https://user-images.githubusercontent.com/17010094/137869885-8e948454-e778-4e73-af2d-8fcfd86598cc.png) | ![image](https://user-images.githubusercontent.com/17010094/137869895-afe39619-d8ff-4c3b-a786-4a695b1e9175.png)

</details>

------------
<details>
<summary>Verification passed on iPhone XR  with iOS 15.0.1 running 1.32.1(21.10.18.10)</summary>

With Favourites | Without Favourites | Without recent search history
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/137869794-112ca3a2-85fc-4a01-9996-985d478678e5.png) | ![image](https://user-images.githubusercontent.com/17010094/137869815-0c56406a-f39b-461f-914a-091b915f757e.png) | ![image](https://user-images.githubusercontent.com/17010094/137869826-93e82640-91dd-4070-af81-68f256ae41c1.png)

</details>

-------------
<details>
<summary>Verification passed on iPad Pro with iOS 15.1 Beta 3 running 1.32.1(21.10.18.10)</summary>

With Favourites | Without Favourites | Without recent search history
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/137870197-96180250-062a-493a-9073-a68b7440fe6f.png) | ![image](https://user-images.githubusercontent.com/17010094/137870236-056a5a7b-f289-4138-b69a-423c2bd45619.png) | ![image](https://user-images.githubusercontent.com/17010094/137870254-dd986782-2a90-4cce-9ef4-91c824413ce4.png)

</details>
