### ISSUE TITLE
Update Playlist for CarPlay iOS 14+

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#4134]
### Description: 
- CarPlay currently uses the iOS 13+ interface only. This gives use the least amount of customizability and a ton of bugs that Apple just won't fix.
- We should add support for iOS 14+ interfaces separately so if we ever drop iOS 13, we can just delete that section of the code. This allows us to have more customizability in terms of UI AND ability to detect whenever the car is plugged in/available.

### Steps to Reproduce 
  1. iOS 13 interface looks different from iOS 14. This is the only way to tell.

**Comment by srirambv** [comment]
Verified CarPlay works fine on both iOS 14 and iOS 15. 
- Verification notes can be found here https://github.com/brave/brave-ios/issues/3673#issuecomment-948503193
