### ISSUE TITLE
Tab appears "black" when tab next to it is closed

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-ios#4149]
### Description: 
If at least two tabs are open, closing one of the tabs (using the x) causes the tab to the immediate left of the closed tab to appear blank. Refresh does not fix the black screen — you have to move to a different tab, then back again for the site content to appear. 

### Steps to Reproduce 

1. Open 3 tabs (for example) to different sites
2. Select the middle tab
3. Close the middle tab
4. Tab to left is automatically selected, observe “black” webpage contents

**Actual result:** 

https://user-images.githubusercontent.com/3299098/132757870-6a004742-45d6-4a57-99b3-3e43d1585658.MP4

**Expected result:**
Contents should not appear black

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
v1.30.1

**Device details:** 
iPad and iPhone

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 15 running 1.31(21. 9.14.15)
- Verified closing tab doesn't cause the previous tab to appear blank
-----------
Verification passed on iPhone 7+ with iOS 14.8 running 1.31(21. 9.14.15)
- Verified closing tab doesn't cause the previous tab to appear blank
-----------
Verification passed on iPhone XR with iOS 13.5 running 1.31(21. 9.14.15)
- Verified closing tab doesn't cause the previous tab to appear blank

**Comment by danawoodman** [comment]
I'm getting this with Version 1.30.1 (21.8.17.19) Device iPhone13,3 (iOS 14.7.1)

**Comment by iccub** [comment]
This is fixed in 1.31 @danawoodman, you can go to app store and update the app, it's live

**Comment by danawoodman** [comment]
Weird, for some reason my phone wasn't auto updating the app. Downloaded the update and it works, thanks!

**Comment by iccub** [comment]
No worries :) glad it works for you
the release is at staged rollout at the moment, 10% of users got it, it will be 100% of users later this week

**Comment by danawoodman** [comment]
Ah that makes sense!
