### ISSUE TITLE
Blank webpages in tab view after restarting brave

### ISSUE THREAD

**Issue by gh0sti** [brave/brave-ios#4150]
### Description: 

Webpages should keep a static image of previously loaded content in tab view as other browsers work

### Steps to Reproduce 
  1. Open webpages
  2. Close brave out of app switcher 
  3. Launch brave browser again 

**Actual result:** 
![image](https://user-images.githubusercontent.com/4202657/132890233-2627bfa4-f39d-4270-a6b2-d890ebe96776.png)

**Expected result:**
Should work like chrome or other browsers where it keeps a static image of what was previously viewed

![image](https://user-images.githubusercontent.com/4202657/132890379-067c9ec7-3693-47ae-91ad-cee5f0d190af.png)

**Reproduces how often:** 
Every time

**Brave Version:** 1.30.1

**Device details: iOS 15 b8 also on 14.7 and iPhone 11 pro max

**Comment by soner-yuksel** [comment]
Fixed with https://github.com/brave/brave-ios/issues/5180.
