### ISSUE TITLE
websites are not loading and the webview appears black

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4158]
### Description: 

When attempting to load any website, the entire webview turns black and never renders the website correctly. This happens every single time by either typing in a URL or clicking on a top side via the NTP. Seems to be working fine with `1.31 (21.9.8.16)` so something regressed with `1.31 (21.9.13.20)`.

### Steps to Reproduce

  1. install `1.31 (21.9.13.20)` via TF
  2. attempt to load a website by typing a URL or tapping on any of the top tiles via the NTP
  3. you'll notice that the website won't load and the webview appears black

**Actual result:** 

**`Example`** | **`Example`**
----------------|-----------------
![IMG_0598](https://user-images.githubusercontent.com/2602313/133197224-7e4a5773-ff85-43ad-8871-17513b64f3fc.PNG) | ![IMG_0599](https://user-images.githubusercontent.com/2602313/133197227-90be4feb-8193-48c6-9c82-8fbbb9c9f39b.PNG)

**Expected result:**

Websites should be loading within the webview without any issues.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR/Cases.

**Brave Version:** 

* `1.31 (21.9.13.20)` - **Reproduced**
* `1.31 (21.9.8.16)` - **Reproduced**

**Device details:** 

* `iPhone 6s+` running `iOS 13.6` - **Couldn't reproduced**
* `iPad Mini 4` running `iOS 13.7` - **Reproduced**

**Website problems only:** `N/A`
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @iccub @kylehickinson @srirambv

**Comment by srirambv** [comment]
Need to retest #4125 on iOS 13.5 once this issue is resolved

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.31(21.9.14.15)
- Verified steps from issue description
- Verified able to load pages without issue

-------------

Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using `1.31 (21.9.14.15)`

* verified that opening websites via `Top Sites` under NTP worked without any issues
* verified that opening websites by typing into the URL bar worked without any issues
* verified that opening websites via search results worked without any issues
