### ISSUE TITLE
Remove Unnecessary nullable attribute from API properties 

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#4166]
### Description: 

The API class properties inside brave_core_main header is defined as `nullable`. 

There are no conditions that requires these properties to be nullable and this causes an insecure `force-unwrapping` in AppDelegate on iOS side. This property attribute should be removed from brave-core side.

**Comment by soner-yuksel** [comment]
Re-opening it, until brave-core 1.31 is pulled.

**Comment by kylehickinson** [comment]
@soner-yuksel In the future, open these issues in brave-browser so they can be closed as part of brave-core merging. You only need to open one in brave-ios if QA needs to test something specific
