### ISSUE TITLE
PrivilegedRequest no longer works on iOS-15

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#4173]
### Description: 
- iOS 15 sandboxes the URLRequest that is sent to the WKWebView. In other words, it makes a COPY OR reconstructs the request. Any associated values with the request, is therefore lost. 
- In other words, `URLProtocol.property(forKey: SOME_KEY, in: self)` will NOT work on `WKWebView` requests on iOS 15+.

- As a result of the above, Reader-Mode and other `localhost` requests are broken completely and will be denied automatically.

### Steps to Reproduce 
  1. Enter reader-mode on iOS 15

**Actual result:** 
- Reader-Mode does NOT work.

**Expected result:**
- Reader-Mode should work.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily Reproduced

**Brave Version:** 
Any

**Device details:** 
iOS 15+

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 15 running 1.31(23) build
- Verified test plan from [#4174](#4174)
- Verified reader mode works as expected
- Verified session restore works as expected
- Verified session restore works as expected on upgrade
- Verified Error pages shows as expected
- Verified NTP works fine 
- Verified NTP SI works as expected
- Verified custom favourites for referral installs work as expected
