### ISSUE TITLE
New tab page always show `localhost:6585/about/home/#panel=0` for title until focus is changed 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4177]
### Description: 
New tab page always show `localhost:6585/about/home/#panel=0` for title until focus is changed 

### Steps to Reproduce 
  1. Clean install on iOS 15 device
  2. NTP during onboarding shows the localhost title
  3. Open a new tab shows the localhost title
  4. Switch focus to another tab or open a new one, previous tab with localhost title changes to New Tab

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/133544457-ea5534bd-6cf7-40b8-b6ca-90b068472c11.png)

**Expected result:**
Should show New Tab instead of localhost

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.31(22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
Note: this is a regression from previous build. It works fine with 1.31(21.9.14.15)

**Comment by iccub** [comment]
Can be retested in `1.31 (23)` or newer

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.31(23) build
- Verified new tabs shows `New Tab` instead of localhost
-----------
Verification passed on iPhone 7+ with iOS 14.8 running 1.31(23) build
- Verified new tabs shows `New Tab` instead of localhost
-----------
Verification passed on iPad Pro with iOS 15 running 1.31(23) build
- Verified new tabs shows `New Tab` instead of localhost
