### ISSUE TITLE
Scrolling feels janky 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4178]
### Description: 
Scrolling feels janky 

### Steps to Reproduce 
  1. Install 1.31(22)
  2. Load a couple of tabs and visit pages 
  3. Try to scroll through the page, scroll is very janky

**Actual result:** 
Scrolling feels janky 

**Expected result:**
No jankiness while scrolling

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.31(22)

**Device details:** 
iPad Pro (iOS 15)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by iccub** [comment]
Moving to 1.32, hard to pinpoint what's wrong at the moment

**Comment by srirambv** [comment]
This seems to be fixed or at least much better on the Beta 3 install of iOS 15.1 Going to close the issue as Passed as we don't have a specific item to pinpoint and say this is the root cause.
