### ISSUE TITLE
Search Engines onboarding on iOS15 has too much space between items

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4184]
### Steps to Reproduce 
  1. Fresh launch on iOS 15
  2. See engine picker onboarding

**Actual result:** 
Big space

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 15 running 1.31(23) build
- Verified spacing between search engines in onboarding is even
  <img width=400 src=https://user-images.githubusercontent.com/17010094/133759027-06694b0a-0a76-45cb-bc16-13307ffed23f.png>
