### ISSUE TITLE
Disable playlist option for talk.brave.com

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4187]
### Description: 
Disable playlist option for talk.brave.com

### Steps to Reproduce 
  1. Visit talk.brave.com and initiate a call
  2. Add to playlist notification is shown on menu and notification
  3. Adding the call just adds a 1sec audio that says `End-to-End encryption is disabled`

**Actual result:** 
Playlist option shows up for talk.brave.com and adds a 1sec audio 

**Expected result:**
Disable playlist option as there is a call recording feature available

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.31(22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T

**Comment by iccub** [comment]
I will move it for next release as we discussed it on yesterdays meeting

**Comment by Brandon-T** [comment]
Fixed already and verified in a separate ticket.
