### ISSUE TITLE
Menu navigation bar appears on iPad and is transparent in settings

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4188]
### Description: 

On iOS 15, when you view the app menu on iPad a blank navigation bar is visible and when you visit settings it is a weird blurred transparent colour. This should be the standard white and not visible at all on the main menu

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 15 running 1.31(23) build
- Verified test plan from [#4189](#4189)

![image](https://user-images.githubusercontent.com/17010094/133760193-1de77328-7b7e-4953-9a89-7c7b4d39227e.png) | ![image](https://user-images.githubusercontent.com/17010094/133760250-428a4f7e-b74a-49c7-bee3-9ed12aca9413.png)
-- | --
