### ISSUE TITLE
Black screen keep showing after every brave app launch activity.

### ISSUE THREAD

**Issue by prabagaranganesan** [brave/brave-ios#4190]
### Description: 
After every launch of Brave app, black screen keep showing for quite some time.

### Steps to Reproduce 
  1. Launch the app with some pre opened browse tabs

**Actual result:** 
There is black screen appears for quite some time until it reloads the pre opened tabs.
And app became unresponsive until the black screen disappears

**Expected result:**
App should open pre tabs immediate after app launch and it should responsive after app launch

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 

**Device details:** 
Simulator iphone 12 latest

**Comment by prabagaranganesan** [comment]
https://user-images.githubusercontent.com/10757213/133657427-289407a6-3746-41ac-8271-2820a0cef7b8.mov

**Comment by prabagaranganesan** [comment]
I was able to find out the root cause of this problem and made fix for this and attached video after fix. Shall I raise PR for this change?

https://user-images.githubusercontent.com/10757213/133716184-4da79150-ed28-4657-a0b9-8eb984bdda1e.mov

.

**Comment by srirambv** [comment]
@prabagaranganesan does this only affect iOS 12 or other versions as well? If its iOS 12 only then I don't think this needs fixing as the lowest supported version is iOS 13

**Comment by prabagaranganesan** [comment]
@srirambv I have tested this in simulator with iOS 14.5 version in debug environment.

**Comment by prabagaranganesan** [comment]
I mean this can happen in all iOS versions.

**Comment by srirambv** [comment]
cc: @kylehickinson @iccub

**Comment by kylehickinson** [comment]
Hi @prabagaranganesan, we'd be happy to review a PR that fixes this if you open one :)

**Comment by bsclifton** [comment]
Nice work @prabagaranganesan 😄 We'd love a PR!

**Comment by prabagaranganesan** [comment]
Sure, I will raise a PR today.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8 running 1.32.1(21.10.20.18)
- Verified background the app and bringing it to focus doesn't show any black screen on launch
- Verified removing app from memory and relaunching it doesn't show any black screen on launch
------------
Verification passed on iPhone XR with iOS 15.0.1 running 1.32.1(21.10.20.18)
- Verified background the app and bringing it to focus doesn't show any black screen on launch
- Verified removing app from memory and relaunching it doesn't show any black screen on launch
------------
Verification passed on iPad Pro with iOS 15.1 Beta 3 running 1.32.1(21.10.20.18)
- Verified background the app and bringing it to focus doesn't show any black screen on launch
- Verified removing app from memory and relaunching it doesn't show any black screen on launch
