### ISSUE TITLE
Brave’s action ‘Create PDF’ not working since 1.31 update

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4193]
Investigate:
https://community.brave.com/t/brave-s-action-create-pdf-not-working-since-1-31-update/284008

**Comment by kylehickinson** [comment]
Looks like it still works properly if you use the Create PDF action inside the share sheet instead of from the menu, so perhaps something broke in the menu part somehow.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.31.1(21.9.27.15)
- Verified test plan from https://github.com/brave/brave-ios/pull/4216

iPhone 7+ (iOS 14.8) | iPad Pro (iOS 15)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/135275307-d7637dec-d52d-4d07-9d4a-537ebc262c9b.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/135275531-6aece3a6-5fea-474a-becc-1aabaeec46a2.png>
