### ISSUE TITLE
Tapping on URL bar on iOS 13 freezes the app

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4200]
### Steps to Reproduce 
  1. Be on iOS 13, have at least one favorite added
  2.  Tap on url bar

**Actual result:** 
App freezes and crashes

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 
1.31

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.31.1(21.9.27.15)
- Verified steps from issue description
- Verified no app freeze or crash when focusing on URL bar
