### ISSUE TITLE
Remove NPM's Babel Dependencies

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#4206]
### Description: 
 - Cleanup by removing NPM's Babel dependencies

### Test Plan:
- Test Find-In-Page
- Test Reader Mode
- Test Tracking Protection Stats
- Test element focus
- Test Fingerprinting & Shields
- Test Auto-Fill/Logins
- Test Brave-Search
- Test Adblock

**Comment by iccub** [comment]
I will mark this as `qa/no` because the session restoration upgrade will require the same set of app retesting
