### ISSUE TITLE
Bug - A flaw in sanitizing reader-mode

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#4208]
### Description: 
- Reader-Mode sanitizes the HTML in Javascript
- Someone can override `string.replace` to break sanitization. 
- Sanitization should be done in native code, and all scripts should use `WKContentWorld` on iOS 14+ (This is a known issue already)

**Comment by srirambv** [comment]
Verification notes can be found [here](https://github.com/brave/security/issues/586#issuecomment-930197366)
