### ISSUE TITLE
Buy VPN screen lost its theme color.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4211]
### Steps to Reproduce 
  1. Make sure your app has light theme set
  2. Tap on 3dot menu
  3. Tap on Brave VPN

**Actual result:** 
Back/Restore purchase buttons are not visible

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 15 running 1.31.1(21.9.27.15)
- Verified steps from issue description
- Verified Back and Restore buttons are visible on both dark and light theme

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/135276776-105d8f35-2351-495f-8402-c8f66ad39ff4.png) | ![image](https://user-images.githubusercontent.com/17010094/135276813-0e2f6035-0925-4f02-bdc5-26a4e760772c.png)
