### ISSUE TITLE
Side padding for address bar is not symmetrical

### ISSUE THREAD

**Issue by pashynskykh** [brave/brave-ios#4214]
### Description: 
Side padding for address bar is not symmetrical

### Steps to Reproduce 
  1. Open Brave browser
  2. Check side padding for address bar

**Actual result:** 
![IMG_4675](https://user-images.githubusercontent.com/14852335/134457085-96afe841-c10d-4f59-8d4d-d52f185c0242.PNG)

**Expected result:**
Side padding is symmetrical.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
Version 1.31 (23)

**Device details:** 
iPhone 11, iOS15

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.35 (22.1.24.16)`

**`Light Theme`** | **`Dark Theme`**
--------------------|--------------------
![IMG_0529](https://user-images.githubusercontent.com/2602313/150872972-e8b783cd-f5dd-48aa-aa39-a9db7dff5e87.jpg) | ![IMG_0531](https://user-images.githubusercontent.com/2602313/150872988-4b0e03c3-2ad1-41e0-9eed-6fb406deff3d.jpg)
![IMG_0530](https://user-images.githubusercontent.com/2602313/150873056-a4fd6c7c-2420-4a7d-846f-90205643439a.jpg) | ![IMG_0532](https://user-images.githubusercontent.com/2602313/150873064-17deb150-813d-4329-9962-fd1518f59c64.jpg)

----------------------------------

Verification **PASSED** on `iPhone 11` running `iOS 14.7.1` using `1.35 (22.1.24.16)`

**`Light Theme`** | **`Dark Theme`**
--------------------|--------------------
![IMG_3762](https://user-images.githubusercontent.com/2602313/150872447-0a644c86-ba78-4f78-a7e8-cbb5d20bd3b0.jpg) | ![IMG_3764](https://user-images.githubusercontent.com/2602313/150872473-3dfa8fad-9da4-4814-a558-15bae0e91218.jpg)
![IMG_3763](https://user-images.githubusercontent.com/2602313/150872489-5f5447f8-3a51-4bc4-9e52-add42399c993.jpg) | ![IMG_3765](https://user-images.githubusercontent.com/2602313/150872504-0cc9da56-2895-4aa0-9142-df59ed88e919.jpg)

----------------------------------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.2` using `1.35 (22.1.24.16)`

**`Light Theme`** | **`Dark Theme`**
--------------------|--------------------
![IMG_0345](https://user-images.githubusercontent.com/2602313/150889471-a8122787-1620-4cc5-b39d-d3c84f9c47f3.jpg) | ![IMG_0347](https://user-images.githubusercontent.com/2602313/150889481-e5d19e18-ddfd-472d-b502-97fb5f54932b.jpg)
![IMG_0346](https://user-images.githubusercontent.com/2602313/150889490-03533dae-950c-4242-a863-f2a77150fa99.jpg) | ![IMG_0348](https://user-images.githubusercontent.com/2602313/150889495-cf3cf75e-e050-4e80-a2b2-f8046f29eaa9.jpg)
