### ISSUE TITLE
Add the ability to dump AMP 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4219]
### Description: 
Add the ability to stop Google AMP pages loading, instead load the native URL.

Users will have the option to enable this setting or not and we'll need to decide whether it is defaulted on or off

Some work was done [here](https://github.com/brave/brave-core/pull/4950) but needs to be finished and incorporated into the products. 

### Links
https://github.com/brave/security/issues/850

cc @pes10k

**Comment by Uni-verse** [comment]
Verification `PASSED` on iPhone using version `1.39 (22.5.24.16)`
Test Devices: 
`iPhone 12 Pro` | `iOS 15.4`
`iPhone X` | `iOS 14.4.2`

- [x] De-AMP setting under Brave Shields & Privacy
- [x] De-AMP Enabled by default (1.39 RC2)
- [x] Prevents loading Google AMP pages, loads native URL

<details>

OFF | ON
-|-
![IMG_2990](https://user-images.githubusercontent.com/17885425/170155875-895bdd84-5521-4544-8a3d-fbd8390520f1.PNG) | ![IMG_2991](https://user-images.githubusercontent.com/17885425/170155881-495fc58a-eea2-4d23-88f5-e3af77e02f97.PNG)

</details>

STR from Test Plan - https://github.com/brave/brave-ios/pull/5278#issue-1211663233

**Confirm amp redirects for top stories (De-AMP OFF)** `PASS`

<details> 

1. Disable de-amp setting
2. Go to google [search](https://www.google.com/)
3. Do a search for "top stories"
4. In the top stories section some links will take you to a link similar to: https://www.google.com/amp/s/{some_url} (take note of the part in {some_url})
5. Go to the following links and you should not be redirected anywhere:

https://www.cbc.ca/amp/1.6432270
https://fingerprint-protection-test.herokuapp.com/amp

1 | 2
-|-
![IMG_2989](https://user-images.githubusercontent.com/17885425/170152639-3414d12f-b087-4191-958a-4c980f8b373c.PNG) | ![IMG_2988](https://user-images.githubusercontent.com/17885425/170152644-cbff2f23-112f-4035-9e05-20d18a5f9321.PNG)

</details>

**Test Sites w/ De-AMP Enabled**  `PASS`

<details>

1. Enable de-amp settings
2. Go to the following urls and you should be redirected
3. https://www.cbc.ca/amp/1.6432270 -> https://www.cbc.ca/news/{some-path} (notice /amp is missing)
4. https://fingerprint-protection-test.herokuapp.com/amp -> https://amp.dev/documentation/guides-and-tutorials/start/create/basic_markup/

Step 3 | Step 4
-|-
![IMG_2995](https://user-images.githubusercontent.com/17885425/170153195-f32f6b24-6d3f-4a9b-aee9-aa1a465426d8.PNG) | ![IMG_2992](https://user-images.githubusercontent.com/17885425/170153259-c8d2e78c-32fd-4d8e-9c1c-b8f8213f3d1f.PNG)
![IMG_2994](https://user-images.githubusercontent.com/17885425/170153191-54c2234a-85bd-4808-a071-d3c575cd8156.PNG) | ![IMG_2993](https://user-images.githubusercontent.com/17885425/170153314-1de0c4af-b2d2-4330-b82c-d0b1a9904c52.PNG)

</details>

**Top Stories w/ De-AMP Enabled** `PASS`

<details>

1. Go to google [search](https://www.google.com/)
2. Do a search for "top stories"
3. In the top stories section when you click on links you should not be sent to https://www.google.com/amp/s/{some_url}
<table>
<tr><td>De-AMP Off</td><td>De-AMP On</td></tr>
<tr>
<td>
https://amp.theguardian.com/business/2022/may/24/ukraine-invasion-may-be-start-of-third-world-war-says-george-soros
</td>
<td>
https://www.theguardian.com/business/2022/may/24/ukraine-invasion-may-be-start-of-third-world-war-says-george-soros
</td>
</tr>
</table>
</details>

**Comment by Uni-verse** [comment]
Verification `PASSED` on iPad using version `1.39 (22.5.24.16)`

Test Devices:
iPad (7th Gen) | iOS 15.4

- [x] De-AMP setting under Brave Shields & Privacy
- [x] De-AMP Enabled by default (1.39 RC2)
- [x] Prevents loading AMP pages, loads native URL

<details>

1 | 2
-|-
![IMG_0317](https://user-images.githubusercontent.com/17885425/170364366-a5c098ec-3bad-4faa-a1ac-d10f051b9ea6.PNG) | ![IMG_0316](https://user-images.githubusercontent.com/17885425/170364355-3a8df490-35c1-4ab0-b853-24d243f9d871.PNG)


</details>

**Test Sites w/ De-AMP Enabled**  `PASS`

<details>

1. Enable de-amp settings
2. Go to the following urls and you should be redirected
3. https://www.cbc.ca/amp/1.6432270 -> https://www.cbc.ca/news/{some-path} (notice /amp is missing)
4. https://fingerprint-protection-test.herokuapp.com/amp -> https://amp.dev/documentation/guides-and-tutorials/start/create/basic_markup/

Step 3 | Step 4
-|-
![IMG_0317](https://user-images.githubusercontent.com/17885425/170363861-70af035c-e3d9-4dd0-8716-00de8e79f6ea.PNG) | ![IMG_0318](https://user-images.githubusercontent.com/17885425/170363871-a8ba9e3b-427f-4d35-87b7-8999652c9040.PNG)

</details>
