### ISSUE TITLE
Both reader and playlist buttons visible at the same time on youtube

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4226]
### Steps to Reproduce 
  1. Go to a video on youtube.com

**Actual result:** 

<img width="331" alt="Zrzut ekranu 2021-09-27 o 11 34 30" src="https://user-images.githubusercontent.com/6950387/134883516-0bfed291-263b-4e51-8442-7adb9c85becb.png">

**Expected result:**
One button should be visible.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 
iOS 15

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.31.1(21.9.27.15)
- Verified only playlist button is shown on YT when a video is playing
- Verified only reader mode button is shown when opening an article 

iPhone XR (iOS 13.5) | iPhone 7+(iOS 14.8) | iPad Pro (iOS 15)
-- | -- | --
<img width=240 src=https://user-images.githubusercontent.com/17010094/135279225-436d8705-17c3-452d-a6d9-c1f6284faa8b.png> | <img width=300 src=https://user-images.githubusercontent.com/17010094/135279083-3e133cf6-27c9-44d5-aaa8-8796287e5f51.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/135279341-b7f05145-9312-4dd1-b1cc-010a9a70cb18.png>
