### ISSUE TITLE
Clean exit check broken on latest development build

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4228]
### Steps to Reproduce 
  1. Open few tabs
  2. Force close the app
  3. Reopen

**Actual result:** 
App think it crashed and ask to restore tabs.

**Expected result:**
Should restore tabs without prompt

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 
Happens on latest development, does not happen on production builds.

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
This can be marked as verified after Manual pass is complete as the test plan touches a lot of items that we run as part of manual pass checks

**Comment by srirambv** [comment]
Closing and marking as verified as #4385 & #4387 is verified
