### ISSUE TITLE
Update user agent for iOS 15

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4230]
Mobile UA works now, desktop one uses outdated iOS 14 UA

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 15 running 1.31.1(21.9.27.15)

Desktop UA | Mobile UA
-- | --
![image](https://user-images.githubusercontent.com/17010094/135112752-1a246a54-7bd8-4077-9250-63a14b268d65.png) | ![image](https://user-images.githubusercontent.com/17010094/135112925-ce81f79d-978c-4774-bc4d-3cff20549b01.png)
