### ISSUE TITLE
Add option to disable 'Add to playlist' toolbar button

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4234]
Add new toggle under playlist settings
Title: `Enable toolbar button`, no footer text.
The setting should be enabled by default.

Put it at the top, above `show notification badge` setting.

This setting should disable url button only, the menu item stays.

**Comment by anthonypkeane** [comment]
@iccub can you please add a screenshot of the new menu here so @rmcfadden3 can take a look and give it the ok?

**Comment by iccub** [comment]
It's the first option

<img width="338" alt="Zrzut ekranu 2021-09-29 o 11 52 18" src="https://user-images.githubusercontent.com/6950387/135246081-6f821e75-6524-43f0-9589-6468422d56f8.png">

**Comment by iccub** [comment]
at first glance looks like we should capitalize first letters for it

**Comment by anthonypkeane** [comment]
@iccub I want to block this one for a moment until @rmcfadden3 has reviewed the copy.

**Comment by rmcfadden3** [comment]
@anthonypkeane — how's this?

Header: Enable quick-access button
Body: Adds a playlist button (it looks like 4 lines with a + symbol) beside the address bar in the Brave browser. This button gives you quick access to open Playlist, or add or remove media.

**Comment by iccub** [comment]
After update

<img width="353" alt="Zrzut ekranu 2021-09-30 o 11 38 03" src="https://user-images.githubusercontent.com/6950387/135428101-9bcf5648-2e61-4801-a176-0b38ca2b2ee0.png">

**Comment by rmcfadden3** [comment]
It's maybe a little long, now that I see it in context. But I don't see anything obvious that we can cut. So, I'm calling this one good.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.32(21.10.6.16)
- Verified the availability of the new settings and the position of the settings
- Verified the setting is enabled by default

iPhone 7+ (iOS 14.8) | iPhone XR (iOS 15.0.1) | iPad Pro (iOS 15.1 Beta 3)
-- | -- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/136546736-45261755-da07-4e2f-8524-f1c672ad278c.png> | <img width=240 src=https://user-images.githubusercontent.com/17010094/136546763-89ee98d5-5fb0-4c25-8ebb-ddc560dfb7d8.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/136546681-52921304-6567-4044-9307-056bc8c446cb.png>
