### ISSUE TITLE
Opening links from other app when Brave is set as default broken on latest development

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4236]
### Steps to Reproduce 
  1. Set Brave as default
  2. Go to other app, like notes
  3. Tap on url

**Actual result:** 
Brave opens but the link does not show up

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8 running 1.32.1(21.10.20.18)
- Verified steps from issue description
- Verified opening links from other apps with Brave as default loads the page correctly 
------------
Verification passed on iPhone XR with iOS 15.0.1 running 1.32.1(21.10.20.18)
- Verified steps from issue description
- Verified opening links from other apps with Brave as default loads the page correctly 
------------
Verification passed on iPad Pro with iOS 15.1 Beta 3 running 1.32.1(21.10.20.18)
- Verified steps from issue description
- Verified opening links from other apps with Brave as default loads the page correctly
