### ISSUE TITLE
When a phone call comes through, Playlist stops playing and never resumes

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#4237]
### Description: 
- When a phone call comes through, Playlist stops playing and never resumes
- Playlist needs to handle session interruption

### Steps to Reproduce 
  1. Play some video in playlist
  2. Someone else calls you
  3. Playlist pauses.
  4. End the phone call.

**Actual result:** 
- Playlist never resumes playback.

**Expected result:**
- Playlist should continue playback when the phone call ends.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Comment by Uni-verse** [comment]
Verification completed using` Version 1.36 (22.2.11.11)`

**PASSED** on `iPhone 12 Pro` / `iOS 15.1.1`
**PASSED** on `iPhone X` / `iOS 14.4.2`

- Verified playlist resumes after call ends
- Verified playlist resumes playback in minimized mode after call is ended.
- When phone call comes in, playlist pauses playback
