### ISSUE TITLE
Update wallpapers

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4239]
## Description
Please update the background wallpaper images

## Design
<img width="286" alt="Screen Shot 2021-10-06 at 5 32 55 PM" src="https://user-images.githubusercontent.com/2388823/136302131-510d250c-a7de-4799-b6ba-db5a49399c89.png">

## Assets
Assets and photo attribution:
https://bravesoftware.slack.com/archives/C7TG12KC3/p1633458074003900
AVIF, WEBP, and compressed JPG available.
For the photo attribution - Corwin and David won't have any links.

**Comment by karenkliu** [comment]
Designs added!

**Comment by anthonypkeane** [comment]
focal points(x, y coordinates) required on mobile

**Comment by karenkliu** [comment]
@anthonypkeane I sent it to Michal already!

**Comment by iccub** [comment]
Karen gave me her optimal views for bg images, i have to run it and get exact x,y values, no blocker on my side

**Comment by Uni-verse** [comment]
Verification completed using `1.35 (22.1.24.23)`

**PASSED** on `iPhone 12 Pro` running `iOS 15.1.1`
**PASSED** on `iPad (7th Gen)` running ` iOS 15.2.1`
**PASSED** on `iPhone X` running `iOS 14.4.2`

- Verified open 15+ new tabs, make sure new wallpapers show up. - https://github.com/brave/brave-ios/pull/4866#issue-1109252280

- Verified proper attribution attached.
- Verified able to view wallpaper in landscape/portrait.
- Verified new wallpapers show up in private tabs

62 | 63 | 64 | 65
-|-|-|-
![IMG_2587](https://user-images.githubusercontent.com/17885425/151080379-53eab483-a1de-4957-bbb6-3f72fb72e179.PNG) | ![IMG_2584](https://user-images.githubusercontent.com/17885425/151080427-dd355914-0f00-4433-aa27-1fcaea267edf.PNG) | ![IMG_2591](https://user-images.githubusercontent.com/17885425/151080447-b2d5eb24-7f7e-4242-8772-ee7add172cda.PNG) | ![IMG_2594](https://user-images.githubusercontent.com/17885425/151079895-7c207ccb-0588-418d-9588-05c30687ece2.PNG)

66 | 67 | 68 | 69
-|-|-|-
![IMG_2589](https://user-images.githubusercontent.com/17885425/151080467-a5821bae-b06f-4558-9412-ce3338c685ad.PNG) | ![IMG_2590](https://user-images.githubusercontent.com/17885425/151080476-251e37c4-fe03-4a22-be0e-86af802e2089.PNG) | ![IMG_2596](https://user-images.githubusercontent.com/17885425/151081443-801fda30-bcce-4cae-a8d9-b60033c1e4c3.PNG) | ![IMG_2582](https://user-images.githubusercontent.com/17885425/151080615-5ee415c4-e99b-41ca-89d6-7ee39f325437.PNG)

70 | 71 | 72 | 73
-|-|-|-
![IMG_2590](https://user-images.githubusercontent.com/17885425/151080635-e635cec3-4d14-4c96-b481-6d6ed0d8138d.PNG) | ![IMG_2581 2](https://user-images.githubusercontent.com/17885425/151080761-fec4b448-daad-49e0-afbd-bb52e9e528b3.PNG) | ![IMG_2592](https://user-images.githubusercontent.com/17885425/151080787-118c5a5c-7e1a-4008-be95-6b19a6e36a9c.PNG) | ![IMG_2593](https://user-images.githubusercontent.com/17885425/151080835-de141a45-33cf-4045-936a-477ead8a7f21.PNG)

74 | 75| 76 | *
-|-|-|-
![IMG_2588](https://user-images.githubusercontent.com/17885425/151080874-8c75677e-c1f7-4dde-afe2-6e9cc9884b3c.PNG) | ![IMG_2586](https://user-images.githubusercontent.com/17885425/151080094-35e207b9-3aa0-4629-91e6-f047dde50455.PNG) | ![IMG_2595](https://user-images.githubusercontent.com/17885425/151079758-966c88af-36ff-46bd-82f1-bf56e80b800a.PNG)
