### ISSUE TITLE
iOS15 UI menu bug on iPad

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4240]
### Description: 
I'm seeing a a UI bug on the iPad menu, image attached. 

![Open a New Browser Tab](https://user-images.githubusercontent.com/7606853/134999004-2378b79c-b121-4e01-9914-3255e1930d5e.png)

**Comment by iccub** [comment]
This is fixed in 1.31,
duplicate of https://github.com/brave/brave-ios/issues/4188
