### ISSUE TITLE
Going back from a Brave News article is not possible anymore.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4241]
### Steps to Reproduce 
  1. Go to NTP, tap on a news article
  2. Try to go back to ntp

**Actual result:** 
You can't

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 
iOS 15

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.31.1(21.9.28.16)
- Verified steps from issue description
- Verified able to swipe back to NTP from Brave News article\
------------
Verification passed on iPhone 7+ with iOS 14.8 running 1.31.1(21.9.28.16)
- Verified steps from issue description
- Verified able to swipe back to NTP from Brave News article
------------
Verification passed on iPad Pro with iOS 15 running 1.31.1(21.9.28.16)
- Verified steps from issue description
- Verified able to swipe back to NTP from Brave News article
