### ISSUE TITLE
Handle keyring auto-lock based on user actions

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#4260]
As of https://github.com/brave/brave-core/pull/10297 the keyring will automatically lock after 5m of inactivity.  A new API (`NotifyUserInteraction`) has been added to the `KeyringController` so that when a user performs some action we may reset that 5m

Note: We are also waiting on https://github.com/brave/brave-browser/issues/18438 so that the setting can be altered on iOS

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33 (21.12.9.23)
- Verified default auto-lock is set to 5 mins
- Verified using the wallet for 5 mins doesn't auto-lock it
- Verified keeping wallet idle for 4 mins and then using the wallet reset the timer from 4 mins
- Verified wallet is auto-locked after the specified timeout whether or not it is in use or in background
------------
Verification passed on iPhone XR with iOS 15.1 running 1.33 (21.12.9.23)
- Verified default auto-lock is set to 5 mins
- Verified using the wallet for 5 mins doesn't auto-lock it
- Verified keeping wallet idle for 4 mins and then using the wallet reset the timer from 4 mins
- Verified wallet is auto-locked after the specified timeout whether or not it is in use or in background
------------
Verification passed on iPad Pro with iOS 15.2 running 1.33 (21.12.9.23)
- Verified default auto-lock is set to 5 mins
- Verified using the wallet for 5 mins doesn't auto-lock it
- Verified keeping wallet idle for 4 mins and then using the wallet reset the timer from 4 mins
- Verified wallet is auto-locked after the specified timeout whether or not it is in use or in background
