### ISSUE TITLE
Reset saved password in keychain when you restore a wallet successfully

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#4265]
If you previously enable Face ID/Touch ID when creating your wallet then restore your wallet to another wallet it doesn't reset the stored password and will fill the incorrect password.

The saved password should be removed from the keychain when a wallet is restored successfully

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33 (21.12.9.23)
- Verified restoring a new wallet when an existing wallet already being there doesn't cause any issue with new password
- Verified able to restore wallet and set fingerprint to unlock and works fine
-----------
Verification passed on iPhone XR with iOS 151 running 1.33 (21.12.9.23)
- Verified restoring a new wallet when an existing wallet already being there doesn't cause any issue with new password
- Verified able to restore wallet and set fingerprint to unlock and works fine
----------
Verification passed on iPad Pro with iOS 15.2 running 1.33 (21.12.9.23)
- Verified restoring a new wallet when an existing wallet already being there doesn't cause any issue with new password
- Verified able to restore wallet and set fingerprint to unlock and works fine
