### ISSUE TITLE
Replace crypto onboarding images with illustrations when added

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#4266]

**Comment by srirambv** [comment]
<details>
<summary>Verification passed on iPhone 7+ with iOS 14.8 running 1.33(21.11.30.21)</summary>


- Verified onboarding/unlock wallet screens are as per spec and match desktop 

Light theme

Onboarding |Set Password | Fingerprint | Restore Crypto | Backup Crypto | Backup Seed | Verify Seed | Unlock Wallet | 
-- | -- | -- | -- | -- | -- | -- | --
<img width=500 src=https://user-images.githubusercontent.com/17010094/144382301-28311d68-2219-4dc9-8198-b4b79eaa4ded.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/144382614-475f9c18-2ae2-494d-8670-ebca1996f935.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/144382748-531e84c9-f588-49e1-8a89-2d446c8a59d4.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/144382565-1c1e767f-fd3e-4cb8-96a6-b6a6239a77de.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/144382785-c79d2311-ee0e-45e4-9b1f-1de5cb64afd1.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/144383053-392ae72b-b0ea-401c-84f0-ddcb884a224b.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/144383067-0427411e-52ea-4b4d-96f0-757b1210b81a.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/144382218-bb22dee9-333f-41c1-b2bf-16a5d4a32dfe.png>

Dark Theme

Onboarding | Set Password | Fingerprint | Restore Crypto | Backup Crypto | Backup Seed | Verify Seed | Unlock Wallet  
-- | -- | -- | -- | -- | -- | -- | --
<img width=500 src=https://user-images.githubusercontent.com/17010094/144382331-78daeb4c-c169-48cf-80c0-4a164de24ae4.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/144382644-c13ffdf9-a088-45f9-b816-a5380ab83363.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/144382739-657660f2-472d-42bf-8c30-0cdc7b6b6590.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/144382352-7f26f7e7-bdb6-4a9f-adc8-b378d5e378e9.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/144382822-f9f779ae-a4a9-4406-abb5-8ac720e2faed.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/144383020-52096205-2b3e-456e-96b2-bab15de4af9c.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/144383085-c72c5286-2934-4386-8276-98726a362d76.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/144382182-2368cd25-cc6e-4545-86e1-7a844f271296.png>

</details>

---------
<details>
<summary>Verification passed on iPhone XR with iOS 15.1 running 1.33(21.11.30.21)</summary>


- Verified onboarding/unlock wallet screens are as per spec and match desktop 

Light theme

Onboarding |Set Password | Restore Crypto | Backup Crypto | Backup Seed | Verify Seed | Unlock Wallet | 
-- | -- | -- | -- | -- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/144386960-5396ef91-f5ee-4d66-a678-91a194745914.png) | ![image](https://user-images.githubusercontent.com/17010094/144387074-569c0236-d3d2-49e4-bbf1-86649b53b5a6.png) | ![image](https://user-images.githubusercontent.com/17010094/144387029-6e8c7fab-7165-40ae-ab40-180e0c826457.png) | ![image](https://user-images.githubusercontent.com/17010094/144387125-88b67866-2b40-4c65-b99b-f07fb3ad1cd7.png) | ![image](https://user-images.githubusercontent.com/17010094/144387202-2d32caf8-bf1a-486e-96f0-64d12ba49111.png) | ![image](https://user-images.githubusercontent.com/17010094/144387252-6f16e683-56b8-4657-95e6-7ba06d224147.png) | ![image](https://user-images.githubusercontent.com/17010094/144387280-65047d7c-9b2f-448f-85d5-629c8fabf853.png)


Dark Theme

Onboarding | Set Password |  Restore Crypto | Backup Crypto | Backup Seed | Verify Seed | Unlock Wallet  
-- | -- | -- | -- | -- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/144387010-d763a143-d263-4f32-b6b6-e6dcc4060bc0.png) | ![image](https://user-images.githubusercontent.com/17010094/144387085-3ce43a2c-9821-4b72-be10-dca8e9648bc9.png) | ![image](https://user-images.githubusercontent.com/17010094/144387045-277db70b-8a8b-4a14-bdb0-d4b8791cef88.png) | ![image](https://user-images.githubusercontent.com/17010094/144387177-84807037-c090-4f6e-999e-9470c1bbb54f.png)  | ![image](https://user-images.githubusercontent.com/17010094/144387237-fcbba3df-2113-445a-951c-e3004a7b1c30.png) | ![image](https://user-images.githubusercontent.com/17010094/144387270-1aadc4e2-6695-4fa7-8bed-c4fd1dcae54e.png) | ![image](https://user-images.githubusercontent.com/17010094/144387299-6435200a-12c4-4e01-8092-1d9bb0e0ebfa.png)


</details>

-----------
<details>
<summary>Verification passed on iPad Prowith iOS 15.2 Beta running 1.33(21.11.30.21)</summary>


- Verified onboarding/unlock wallet screens are as per spec and match desktop 

Light theme

Onboarding |Set Password | Fingerprint | Restore Crypto | Backup Crypto | Backup Seed | Verify Seed | Unlock Wallet | 
-- | -- | -- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/144388383-9dec31a8-ec53-4aa4-92d5-07e65fb55c8b.png) | ![image](https://user-images.githubusercontent.com/17010094/144388520-dbcc5e25-4a3f-4e77-8737-553a5445c3e0.png) | ![image](https://user-images.githubusercontent.com/17010094/144388568-56fdf687-78c8-49ca-8e21-3e7124d96de6.png) | ![image](https://user-images.githubusercontent.com/17010094/144388488-01f77df3-d579-46b3-9695-a3e1326d4fe8.png) | ![image](https://user-images.githubusercontent.com/17010094/144388662-a38344a8-876d-45ca-822d-6e95d61fc390.png) | ![image](https://user-images.githubusercontent.com/17010094/144388697-66d68268-e757-41c7-9f03-e42a14ccd6b5.png) | ![image](https://user-images.githubusercontent.com/17010094/144388731-a17d1762-7904-42ee-a737-ca5e7b42fbdb.png) | ![image](https://user-images.githubusercontent.com/17010094/144388460-120a23a4-712b-412b-9af7-388bb2abc50d.png)

Dark Theme

Onboarding | Set Password | Fingerprint | Restore Crypto | Backup Crypto | Backup Seed | Verify Seed | Unlock Wallet  
-- | -- | -- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/144388398-ebba133c-680a-462d-b2d0-fca1ab955ca1.png) | ![image](https://user-images.githubusercontent.com/17010094/144388530-f9ddfe43-ebf9-4470-a5ce-fcd0e0b643a3.png) | ![image](https://user-images.githubusercontent.com/17010094/144388627-0d76fca0-c18f-45c5-8c9b-41fc521b1e18.png) | ![image](https://user-images.githubusercontent.com/17010094/144388501-c26a95bf-04ee-4a2b-884e-93f4f037d596.png) | ![image](https://user-images.githubusercontent.com/17010094/144388679-1d9c7440-d9de-4d8c-bad3-02fb0bed371e.png) | ![image](https://user-images.githubusercontent.com/17010094/144388720-67e4d57b-f471-4b33-8a1e-89fea0cfcaf5.png) | ![image](https://user-images.githubusercontent.com/17010094/144388749-b04f4125-02d5-4160-b19f-a51eed5aee38.png) | ![image](https://user-images.githubusercontent.com/17010094/144388439-cb9670dc-7f37-4cd5-bb82-868393e093d2.png)

</details>
