### ISSUE TITLE
Add asset search support

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#4268]
The search button on the Crypto page displays a list of assets that is searchable.  Tapping on an asset from this screen displays an Asset Detail screen

This is currently partially complete, and needs completing to match design in Figma/MVP spec

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.33(21.11.30.21)
- Verified able to search for a token from the asset search button
- Verified selecting a token loads the token info, price etc

iPhone 7+ (iOS 14.8) | iPhone XR (iOS 15.1) | iPad Pro (iOS 15.2 Beta)
-- | -- | --
<video width="640" height="480" src=https://user-images.githubusercontent.com/17010094/144392182-0b65ec2d-a656-4297-8615-f78a1532d4c9.MP4> | <video width="640" height="480" src=https://user-images.githubusercontent.com/17010094/144392242-3ad43764-3c91-443c-b583-362764293723.MP4> | <video width="640" height="480" src=https://user-images.githubusercontent.com/17010094/144392300-60b5f917-4bef-4e01-9106-9592dc92bff2.MP4>
