### ISSUE TITLE
Add support for editing visible user assets

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#4269]
When a user taps the "Edit Visible Assets" button, they should be displayed a list of user assets from the token registry that they can set visible or not.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.33(21.11.30.21)
- Verified able to add more tokes via `Edit Visible Assets`
- Verified searching and selecting adds the asset to list
- Verified able to remove the token from visible list
- Verified able to add custom asset which will be shown
- Verified errors when add custom asset doesn't have a value 

iPhone 7+ (iOS 14.8) | iPhone XR (iOS 15.1) | iPad Pro (iOS 15.2 Beta)
-- | -- | --
<video width="400" src=https://user-images.githubusercontent.com/17010094/144390351-e176d3a0-91ad-4275-8d82-f10733cd98f7.MP4> | <video width="400" src=https://user-images.githubusercontent.com/17010094/144390372-cfa702d9-9a07-45d8-a8c5-25d698f43a09.MP4> | <video width="400" src=https://user-images.githubusercontent.com/17010094/144390299-270b006d-cfa6-4934-9d2a-dfc2cbbecda4.MP4>
