### ISSUE TITLE
Integrate asset details UI with wallet API

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#4270]
The UI is mostly done but needs integration with the proper APIs

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.33(21.12.7.21)
- Verified prices, balances, price history, and transactions are show correctly 

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.1) | iPad Pro (iOS 15.2)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/145271328-45d4f200-00e8-414f-99a0-c1609c72ce9e.png> | <img width=240 src=https://user-images.githubusercontent.com/17010094/145271388-4d9de381-49c2-4d48-afbe-27750690fcfd.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/145271367-0e7fce44-ab9b-47ca-8d10-0b6ebf3156ea.png>
