### ISSUE TITLE
Add support for swapping crypto in wallet

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#4271]
The "Swap" button in the Buy/Send/Swap popover does not currently show anything.  

See MVP doc/Figma for designs.

UI is partially done already

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33(21.12.7.21)
- Verified Swap Crypto opens up Swap transaction details
- Verified able to select token from the list of swap from and swap to 
- Verified after amount is entered it automatically calculates the swap value for the receiving token
------------
Verification passed on iPhone XR with iOS 15.1 running 1.33(21.12.7.21)
- Verified Swap Crypto opens up Swap transaction details
- Verified able to select token from the list of swap from and swap to 
- Verified after amount is entered it automatically calculates the swap value for the receiving token
------------
Verification passed on iPad Pro with iOS 15.2 running 1.33(21.12.7.21)
- Verified Swap Crypto opens up Swap transaction details
- Verified able to select token from the list of swap from and swap to 
- Verified after amount is entered it automatically calculates the swap value for the receiving token
