### ISSUE TITLE
Add support for buying crypto in wallet

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#4272]
The "Buy" button in the Buy/Send/Swap popover does not currently show anything.  

See MVP doc/Figma for designs.

Desktop currently links to Wyre, iOS will likely do the same

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33(21.12.7.21)
- Verified Buy crypto provides an input field to enter value
- Verified clicking on `Continue to Wyre` pre-populates the entered amount on the landing page
------------
Verification passed on iPhone XR with iOS 15.1 running 1.33(21.12.7.21)
- Verified Buy crypto provides an input field to enter value
- Verified clicking on `Continue to Wyre` pre-populates the entered amount on the landing page
------------
Verification passed on iPad Pro with iOS 15.2 running 1.33(21.12.7.21)
- Verified Buy crypto provides an input field to enter value
- Verified clicking on `Continue to Wyre` pre-populates the entered amount on the landing page
