### ISSUE TITLE
Add support for sending crypto in wallet

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#4273]
The "Send" button in the Buy/Send/Swap popover does not currently show anything.  

See MVP doc/Figma for designs.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33(21.12.7.21)
- Verified Send Crypto opens up send transaction details
- Verified able to select token from the list 
- Verified able to send tokens to another address specified
- Verified send transaction fails when receiving address is a contract address
- Verified send transaction fails when receiving address is same as sending address
------------
Verification passed on iPhone XR with iOS 15.1 running 1.33(21.12.7.21)
- Verified Send Crypto opens up send transaction details
- Verified able to select token from the list 
- Verified able to send tokens to another address specified
- Verified send transaction fails when receiving address is a contract address
- Verified send transaction fails when receiving address is same as sending address
------------
Verification passed on iPad Pro with iOS 15.2 running 1.33(21.12.7.21)
- Verified Send Crypto opens up send transaction details
- Verified able to select token from the list 
- Verified able to send tokens to another address specified
- Verified send transaction fails when receiving address is a contract address
- Verified send transaction fails when receiving address is same as sending address
