### ISSUE TITLE
Add related assets/transactions info to Accounts Activity screen

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#4274]
The accounts screen should display any related transactions and assets when you tap to view an account from the accounts screen.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.33(21.12.7.21)
- Verified prices, balances, price history, and transactions are show correctly 

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.1) | iPad Pro (iOS 15.2)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/145271842-c2d38970-45fc-43ae-b6de-da36a3fbc138.png> | <img width=240 src=https://user-images.githubusercontent.com/17010094/145271921-ae696d7b-d5a3-4735-9c00-6d6676424187.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/145271862-fce7b2ac-0d0c-4e66-b40f-3c6cf90db499.png>
