### ISSUE TITLE
Load proper icons for tokens/assets

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4279]
Right now we just have black circles, these should load the correct icons from the wallet component.

**Comment by kylehickinson** [comment]
Blocked: requires https://github.com/brave/brave-core/pull/10343 which is in `v1.32.40`

**Comment by kylehickinson** [comment]
Should be unblocked now

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 15.2 Beta running 1.33 (21.11.30.21)
- Verified tokens show proper icon 

![image](https://user-images.githubusercontent.com/17010094/144244994-0c0b4037-91d9-4b16-baa2-18b9199a9314.png) | ![image](https://user-images.githubusercontent.com/17010094/144244950-f5daa372-797a-4108-b11a-826fbb691c2b.png) | ![image](https://user-images.githubusercontent.com/17010094/144244966-5dbe7744-3eec-4dcb-b63e-2b35f2c14381.png)
-- | -- | -- 

------
Verification passed on iPhone XR with iOS 15.1 Beta running 1.33 (21.11.30.21)
- Verified tokens show proper icon 

![image](https://user-images.githubusercontent.com/17010094/144245390-46bba6f0-b86e-462a-adfd-43fa6a98d7bb.png) | ![image](https://user-images.githubusercontent.com/17010094/144245371-6ce6d43a-1454-43e9-a6ca-f93b42dfc807.png) | ![image](https://user-images.githubusercontent.com/17010094/144245398-c6e3d5c0-7bde-4d5a-8e0a-79a83f657d11.png)
-- | -- | -- 

------
Verification passed on iPhone 7+ with iOS 14.8 Beta running 1.33 (21.11.30.21)
- Verified tokens show proper icon 

![image](https://user-images.githubusercontent.com/17010094/144245462-353b7ac4-ad57-4848-8626-bad614f5a25f.png) | ![image](https://user-images.githubusercontent.com/17010094/144245482-811d7529-dc30-4081-a7d2-ff5c38d07f65.png) | ![image](https://user-images.githubusercontent.com/17010094/144245492-3e796507-7afd-4e93-ab42-3beea333f3d8.png)
-- | -- | --
