### ISSUE TITLE
Improve Brave ads performance on iOS (part 2)

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#4281]
### Description: 
Previously captured with https://github.com/brave/brave-browser/issues/18118

Some users were experiencing bad performance when Rewards enabled on iOS. All users affected reported the problem going away when Rewards turned off. A fix was delivered with https://github.com/brave/brave-core/pull/10088 and this definitely helps - but some users reporting some slowness still

Some notes from @tmancey 
> the cause here was that state was being written to JSON and this state over the last x years has continued to grow for heavy users of the browser.
> ... we never got to moving state from JSON to databases/prefs. However, this state is now moving away from JSON due to other changes

Issues to address this have been created here:
- [Migrate Brave ads client state from JSON to database/prefs](https://github.com/brave/brave-browser/issues/5150)
- [Migrate Brave ads confirmations state from JSON to database/prefs](https://github.com/brave/brave-browser/issues/5151)
- [Implement Brave Ads performance tests for ad serving](https://github.com/brave/brave-browser/issues/4389)

### Steps to Reproduce 
  1. Have Brave Rewards (and Ads) enabled
  2. Use Brave for a long time and have a large Ads history
  3. Be presented ads

**Actual result:** 
It seems the browser freezes before delivering an Ad

**Expected result:**
There should be no lock up on UI thread / no visible perf impact to user

**Reproduces how often:**
Depends on user and their history and may also impact older devices more

**Brave Version:**
1.31.1

**Device details:**
@jsecretan had experienced - (unsure of phone model)
@bsclifton experienced on iPhone 12 mini; after https://github.com/brave/brave-core/pull/10088 things seem OK

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Good news, Ads should be performant now :) let's close it
