### ISSUE TITLE
Make blocking scripts detectable, similar to Safari's behavior

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#429]
To see what I mean, disable javascript in Safari(advanced options in settings)
and look at results of google search and twitter

Brave with javascript blocked
<img width="854" alt="zrzut ekranu 2018-11-20 o 22 23 47" src="https://user-images.githubusercontent.com/6950387/48803754-24102700-ed13-11e8-9bb6-6a8b54115741.png">

Safari with javascript blocked
<img width="872" alt="zrzut ekranu 2018-11-20 o 22 23 23" src="https://user-images.githubusercontent.com/6950387/48803759-27a3ae00-ed13-11e8-9c85-bf9e0cfbbf20.png">

As you can see websites can see that Safari has javascript blocked and tries to server non-javascript friendly websites.

We need to research whether it is possible to do in `WKWebView`. Implementing this would result in better browsing experience without js enabled.

**Comment by cndouglas** [comment]
This will likely be fixed with #428.

Setting `webView.configuration.preferences.javascriptEnabled = false` gives the following:
![](https://user-images.githubusercontent.com/19424103/48816880-8a904780-ed09-11e8-9bfd-fd79750aa1c5.png)

**Comment by iccub** [comment]
@jhreis did some initial tests with `javascriptEnabled` and said it didn't work this way. 
We plan to work on this shortly after iOS 1.7 is released, thanks for doing the research Liunkae :)

**Comment by cndouglas** [comment]
Fixed by #428. Confirmed in the current master:
![image](https://user-images.githubusercontent.com/19424103/49459281-4d6d9000-f7b4-11e8-9b34-0fd26ed4e3eb.png)

**Comment by iccub** [comment]
Fixed by https://github.com/brave/brave-ios/issues/428
