### ISSUE TITLE
Usage Ping - Week of Installation date format issues

### ISSUE THREAD

**Issue by porteron** [brave/brave-ios#4290]
### Description: 
Depending on the day about 10-20k usage pings coming from ios are sending a bad date format for `woi` (week of installation). The accepted format is YYYY-MM-DD. What we are seeing  on our end is YYYY-M-D or YYYY-MM-D.

Examples:
```
"woi":"2019-1-7"       // should be "2019-01-07"
"woi":"2019-1-21"     // should be "2019-01-21"
"woi":"2018-5-7"      // should be "2019-05-07"
"woi":"2018-9-24"   // should be "2019-09-24"
``` 

Just want to make sure there is not an issue on the reporting side, of course this could be a malicious person sending bad date formats. 

**Brave Version:** 
All versions

**Comment by iccub** [comment]
We have robust unit tests for DAU pings, i will recheck how we send it and fix if needed

**Comment by iccub** [comment]
We checked with mitm proxy, request use correct date.
Feel free to start a thread in slack if you want more brainstorming on this

![Image from iOS (1)](https://user-images.githubusercontent.com/6950387/136093500-25db1509-6bf2-41ea-a3e6-efba33fb6cf9.png)

**Comment by porteron** [comment]
thanks @iccub, that looks good to me. I just wanted to put it on record, probably just people spamming the usage ping endpoint.
