### ISSUE TITLE
Add support for adding custom ERC20/ERC721 tokens

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4294]
On the "Edit Visible Assets" screen, we need to add a button to add a custom asset.  That asset can then be selected/unselected as a visible asset and be part of portfolio balance calculations

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33(21.12.9.23)
- Verified able to add a ERC20 token via `Add custom token`
- Verified added token is shown in the visible asset list
- Verified uncheck the custom token added doesn't remove it just hides it from visible list
- Verified able to swipe delete the custom token that is added from the visible asset list 
- Support of ERC721 will be tested when [#4536](#4536) lands
------------
Verification passed on iPhone XR with iOS 15.1 running 1.33(21.12.9.23)
- Verified able to add a ERC20 token via `Add custom token`
- Verified added token is shown in the visible asset list
- Verified uncheck the custom token added doesn't remove it just hides it from visible list
- Verified able to swipe delete the custom token that is added from the visible asset list 
- Support of ERC721 will be tested when [#4536](#4536) lands
------------
Verification passed on iPad Pro with iOS 15.2 running 1.33(21.12.9.23)
- Verified able to add a ERC20 token via `Add custom token`
- Verified added token is shown in the visible asset list
- Verified uncheck the custom token added doesn't remove it just hides it from visible list
- Verified able to swipe delete the custom token that is added from the visible asset list 
- Support of ERC721 will be tested when [#4536](#4536) lands
