### ISSUE TITLE
In rare cases, the application can use lots of space when using Playlist downloading

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#4296]
### Description: 
- Sometimes the application can use a lot of space when downloading from Playlist.
- This is caused by the system caching files to `com.apple.UserManaged...` folder and although it is supposed to be deleted over time by the system OR by the user via the `Settings.app` (system settings app), it is not happening.
- We need to therefore allow users to delete these files AND make sure the download manager handles deleting these things and updating items when downloads are restored. This is because the system automatically triggers a `resume download` whenever we allocate `URLSessionConfiguration.background(withIdentifier: ".....background.session")`. It means, if we delete these files prematurely, downloads may NOT resume! The system is also free to cancel downloads whenever it feels like it!

### Steps to Reproduce 
  1. Go to any website that downloads `HLS` video streams
  2. Add the video to playlist
  3. Open playlist, let it fully download the video that was just added.
  4. Swipe on the item, and tap on `DELETE OFFLINE CACHE` icon (the one on the furthest left of the swipe menu - x-cloud icon)
  5. Swipe again, this time press `Save For Offline` icon (the one on the furthest left of the swipe menu - cloud icon)
  6. Before the item is complete (let's say 5% downloaded for example), swipe UP and kill the application completely.
  7. Restore the application and go to playlist.
  8. Notice that the `cloud` icon in the swipe menu is still there OR the space of your application is larger but the offline cache is missing.
  9. You can delete this cache via the System settings menu.
  10. After a while, the system will automatically resume the download when restoring the app. This means the space will automatically go back to normal. How long after is unknown!

**Actual result:** 
- Taking up unnecessary space

**Expected result:**
- Shouldn't take up extra space

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent

### Additional Information
- It can sometimes be hard to find a website that uses HLS streams reliably, so this may be very hard to reproduce.

**Comment by srirambv** [comment]
Marking as QA/No after discussing with @Brandon-T
