### ISSUE TITLE
Tab tray keyboard navigation broken on iOS 15

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4299]
### Steps to Reproduce 
  1. iOS 15 iPad, connect hardware keyboard
  2. Open Tab Tray
  3. Press on of arrow keys

**Actual result:** 
Does nothing

**Expected result:**
Should switch between tabs

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.1` using `1.33 (21.12.8.23)`

* verified the STR/Cases outlined via https://github.com/brave/brave-ios/issues/4299#issue-1019940084
* ensured that you can switch between tabs using all the arrow keys (left/right & up/down) without issues
