### ISSUE TITLE
Restore tab blank screen for Japanese sites

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4301]
### Description: 
Feels like something wrong with url decoding

### Steps to Reproduce 
  1. Go to https://rocketnews24.com/category/%E3%82%B0%E3%83%AB%E3%83%A1/
  2. Kill the app
  3. Reopen

**Actual result:** 
Blank screen, url is empty

**Expected result:**
Should restore the tab properly

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.0.1 running 1.32(21.10.13.18)
- Verified steps from issue description
---------
Verification passed on iPad Pro with iOS 15.1 Beta 3 running 1.32(21.10.13.18)
- Verified steps from issue description
---------
Verification failed on iPhone 7+ with iOS 14.8. Logged follow up issue #4321
