### ISSUE TITLE
Add setting for wallet auto-lock

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4302]
Right now the wallet auto-locks after 5m of inactivity, we need to add a setting to change that

Blocked by: https://github.com/brave/brave-browser/issues/18438

**Comment by srirambv** [comment]
Verificaton passed on the following devices running 1.33(21.12.9.17)
- Verified `Automatically Lock After` setting has 4 default options to choose from
- Verified what ever setting is being set, wallet auto-locks after the time is past
- Verified setting can be accessed via Wallet menu -> Settings
- Verified setting can be accessed via 3 dot menu -> Wallet 

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.1) | iPad Pro (iOS 15.2)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/145468588-741c5f1b-0d80-4e1b-897d-fa790d7e1170.png> | <img width=240 src=https://user-images.githubusercontent.com/17010094/145468611-1f29fe59-220c-4a52-8f48-732cc8b4f40e.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/145468633-05048759-c959-4cc9-90d1-bd9c352e5f23.png>
