### ISSUE TITLE
Make Brave Search to show as first engine in search engine picker

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4305]

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8 running 1.32(21.10.13.11)
- Verified Brave search is listed as the first search engine in the engine picker
- Verified other search engines are listed in alphabetical order 
---------
Verification passed on iPhone XR with iOS 15.0.1 running 1.32(21.10.13.11)
- Verified Brave search is listed as the first search engine in the engine picker
- Verified other search engines are listed in alphabetical order 
---------
Verification passed on iPad Pro with iOS 15.1 Beta 3 running 1.32(21.10.13.11)
- Verified Brave search is listed as the first search engine in the engine picker
- Verified other search engines are listed in alphabetical order
