### ISSUE TITLE
Update Session Restore and GCDWebServer code

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#4308]
### Description: 
- We should minimize use of the GCDWebServer and start using the custom url SchemeHandler.
- Firefox has already done a similar change to their SessionRestore and InternalURL and PrivilegedRequest

**Comment by stephendonner** [comment]
## Verified `PASSED` using Brave `1.32.3 (21.11.13.9)` on an `iPhone 6s`, running `iOS 15.0.21`


### Test Reader-Mode
  - confirmed I can change color scheme (`Light`, `Dark`, `Sepia`)
  - confirmed I can change the font from `Sans-serif` to `Serif` and back
  - confirmed I can increase and decrease text size
  - confirmed I can change contrast
  - confirmed using articles from `ew.com`, `time.com`, and `sfgate.com` that content, images, and formatting was the same, between `1.32.3 (21.11.13.9)` and `1.32.2 (21.11.4.20)` versions

### Test Session Restore
  - confirmed I could force-quit and session-restore sites
  - confirmed I could shut down Brave, relaunch, and have it restore my tabs (with previously focused tab still focused)
  - confirmed I could background Brave, and upon return, have it restore my tabs, as above
### Test Session Restore of Japanese website with Kanji or Katakana characters in the URL
  - force-quit and session-restored `https://ja.wikipedia.org/wiki/%E3%82%B9%E3%82%BF%E3%83%BC%E3%83%BB%E3%82%A6%E3%82%A9%E3%83%BC%E3%82%BA%E3%82%B7%E3%83%AA%E3%83%BC%E3%82%BA`
### Test Session Restore of multiple tabs
  - tested thoroughly as part of https://github.com/brave/brave-ios/issues/4490
### Test About Home page
  - confirmed `Privacy Policy` and `Terms of Use` links and pages work/render
### Test About License page
  - filed https://github.com/brave/brave-ios/issues/4521

###  Test Error Pages like on `gsdgsdglkangajkngkalngakgdaga.com` or random website
  - confirmed I got `This site can't be reached` interstitial pages, which match the designs from https://github.com/brave/brave-ios/issues/4338
###  Test Error Pages on bad certificate website like: `https://expired.badssl.com/`
  - filed https://github.com/brave/brave-ios/issues/4518 for the background color for `Your connection is not private` error pages
### Test Error Pages when there is no network (turn on airplane mode)
   - confirmed I got the `No Internet` interstitial, as part of https://github.com/brave/brave-ios/issues/4338

------------
Verification passed on iPhone XR with iOS 15.0.1 running 1.32.3
- Verified test plan from https://github.com/brave/brave-ios/pull/4325

------------
Verification passed on iPad Pro with iOS 15.2 Beta 2 running 1.32.3
- Verified test plan from https://github.com/brave/brave-ios/pull/4325
