### ISSUE TITLE
Core Data file permission crashes

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4312]

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8 running 1.32.1(21.10.20.18)
- Verified no browser crash after a certain amount of idle time when a url is opened via Safari
------------
Verification passed on iPhone XR with iOS 15.0.1 running 1.32.1(21.10.20.18)
- Verified no browser crash after a certain amount of idle time when a url is opened via Safari
------------
Verification passed on iPad Pro with iOS 15.1 Beta 3 running 1.32.1(21.10.20.18)
- Verified no browser crash after a certain amount of idle time when a url is opened via Safari
