### ISSUE TITLE
Manual test run for 1.32 on `iPad Mini 4` running `iOS 13`

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4317]
## Installer

- [x] Check that installer is close to the size of the last release
- [x] Check the Brave version in About and make sure it is EXACTLY as expected

## Data

- [x] Verify that data from the previous build appears in the updated build as expected (bookmarks, etc)
- [x] Verify that the cookies from the previous build are preserved after upgrade
- [x] Verify saved password are retained after upgrade
- [x] Verify stats are retained after upgrade
- [x] Verify sync chain created in the previous version is still retained on upgrade
- [x] Verify per-site settings are preserved after upgrade

## Shields Settings

- [x] Enable all switches in settings and visit a site and disable block scripts. Kill and relaunch the app and verify if the site shield settings are retained

## Bravery settings

- [x] Check that HTTPS Everywhere works by loading http://https-everywhere.badssl.com/
- [x] Turning HTTPS Everywhere off or shields off both disable the redirect to https://https-everywhere.badssl.com/
- [x] Check that block ad and unblock ad works on http://slashdot.org
- [x] Check that toggling to blocking and allow ads works as expected
- [x] Verify that clicking through a cert error in https://badssl.com/ works
- [x] Verify that Safe Browsing works (https://www.raisegame.com/)
- [x] Enable block script globally from settings, Visit https://twitter.com/, nothing should load. Tap on Shields and disable block script, the page should load properly
- [x] Verify that preferences default Brave Shields settings take effect on pages with no site settings
### Fingerprint Tests
  - [x] Verify that turning on fingerprinting protection in preferences shows 3 fingerprint blocked at https://browserleaks.com/canvas . Verify that turning it off in the Bravery menu shows 0 fingerprints blocked
  - [x] Verify that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ when fingerprinting protection is on
  - [x] Verify that https://diafygi.github.io/webrtc-ips/ doesn't leak IP address when `Block all fingerprinting protection` is on

## Content tests

- [x] Go to https://feedly.com/ and make sure that the password can be saved.  Make sure the saved password is auto-populated when you visit the site again
- [x] Open an email on http://mail.google.com/ or `inbox.google.com` and click on a link. Make sure it works
- [x] Verify that PDF is loaded over https at https://basicattentiontoken.org/BasicAttentionTokenWhitePaper-4.pdf
- [x] Verify that PDF is loaded over HTTP at http://www.pdf995.com/samples/pdf.pdf
- [x] Verify that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run)
- [x] Verify that search results from https://startpage.com/ open in a new tab (due to target being _blank_)

## App linker

- [x] Long press on a link in the Twitter app to get the share picker, choose Brave. Verify Brave doesn't crash after opening the link

## Session storage

- [x] Verify that tabs restore when closed, including active tab

**Comment by kjozwiak** [comment]
@srirambv change the title if you end up running through this 👍

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Mini 4` running `iOS 13.7` using the following build:

```
1.32 (21.10.13.18)
```
