### ISSUE TITLE
Add numbers to backup wallet phrase screens

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4320]
The current implementation does not include numbers next to each word in the phrase, which makes it confusing to understand the order of the numbers.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.1 running 1.33 (21.12.9.17)
- Verified backup wallet screen has all the phrases numbered

Seed Phrase | Verify Seed
-- | --
![image](https://user-images.githubusercontent.com/17010094/145467244-34307860-b465-4daf-81d6-dcd6d22e80a2.png) | ![image](https://user-images.githubusercontent.com/17010094/145467627-138aafd6-b636-43e9-8797-122c2599e3d7.png)

---------
Verification passed on iPad Pro with iOS 15.2 running 1.33 (21.12.9.17)
- Verified backup wallet screen has all the phrases numbered

Seed Phrase | Verify Seed
-- | --
![image](https://user-images.githubusercontent.com/17010094/145467803-848b307b-575d-472a-bd10-da2979c9070b.png) | ![image](https://user-images.githubusercontent.com/17010094/145467866-96f736ef-d1e4-4bc1-8843-78bda5a1d398.png) 

-------

Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33 (21.12.9.23)
- Verified backup wallet screen has all the phrases numbered

Seed Phrase | Verify Seed
-- | --
![image](https://user-images.githubusercontent.com/17010094/145515773-ce376af0-e3ca-405b-8e1e-421fb21ea401.png) | ![image](https://user-images.githubusercontent.com/17010094/145515882-a790cc36-1524-4033-b9ca-72059d06d984.png)
