### ISSUE TITLE
[Follow up #4301] Restore tab blank screen for Japanese sites 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4321]
### Description: 
[Follow up #4301] Restore tab blank screen for Japanese sites 

### Steps to Reproduce 
  1. Go to https://rocketnews24.com/category/%E3%82%B0%E3%83%AB%E3%83%A1/
  2. Kill the app
  3. Relaunch app, tab loads blank

**Actual result:** 
Blank screen, url is empty

**Expected result:**
Should restore the tab properly

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.32(21.10.13.18)

**Device details:** 
iPhone 7+ (iOS 14.8)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc: @iccub @Brandon-T

**Comment by iccub** [comment]
This got fixed some time ago
