### ISSUE TITLE
Deprecate ours HTTPSE in favor of the one bundled in WKWebView

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4335]
This flag is enabled by default on iOS 15.
https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/3752243-upgradeknownhoststohttps

We can remove the current https implementation for iOS 15 devices.
There's chances this will be also an option for iOS 14.5, but we have to wait for newer XCode to verify it. That's why I'm putting `blocked` label

**Comment by diracdeltas** [comment]
what are known hosts in this case? are they using a list?

https://docs.google.com/document/d/1HnLAluEeHt7xNEo60vxyVzRFi0JQ_t0h_ZVrPXfQR9o/edit should probably be updated with this info

**Comment by iccub** [comment]
@diracdeltas  Apple has zero details for this API, same for webkit source 
https://github.com/WebKit/WebKit/blob/main/Source/WebKit/UIProcess/API/Cocoa/WKWebViewConfiguration.h#L134

We can only say we are going to use the same lists as Safari on iOS and other 3rd party browsers

**Comment by iccub** [comment]
Added formal security review for it here, unfortunately Apple does not provide much info about it
https://github.com/brave/security/issues/632

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.1 running 1.32.3(21.11.13.9)
- Verified test plan from https://github.com/brave/brave-ios/pull/4433
- Verified when setting is enabled site auto-upgrades to https
- Verified when setting is disabled site loads via http and there is no upgrade to https
------------
Verification passed on iPad Pro with iOS 15.2 Beta 2 running 1.32.3(21.11.13.9)
- Verified test plan from https://github.com/brave/brave-ios/pull/4433
- Verified when setting is enabled site auto-upgrades to https
- Verified when setting is disabled site loads via http and there is no upgrade to https
