### ISSUE TITLE
Put 'Set as default' setting on top of settings screen.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4336]

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using the following build:

```
1.33 (21.12.6.21)
```

**`Example`** | **`Example`**
---------------|----------------
![IMG_0398](https://user-images.githubusercontent.com/2602313/145086615-eb3f26e3-cf4e-487c-a8d0-7e943abca31c.png) |![IMG_0399](https://user-images.githubusercontent.com/2602313/145086623-4685d26f-1bad-4a49-8886-b22e6fc6da72.png)

----------------------------

Verification **PASSED** on `iPhone 6+` running `iOS 14.6` using the following build:

```
1.33 (21.12.6.21)
```

**`Example`** | **`Example`**
---------------|---------------
![IMG_0200](https://user-images.githubusercontent.com/2602313/145086814-8266e928-5107-4ac3-b889-bac14f8e5610.png) |![IMG_0201](https://user-images.githubusercontent.com/2602313/145086839-a04671d3-28eb-4d59-aa83-c0d891972dc8.png)

----------------------------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.1` using the following build:

```
1.33 (21.12.6.21)
```

**`Example`** | **`Example`**
---------------|--------------
![IMG_0309](https://user-images.githubusercontent.com/2602313/145087171-64ba0cab-00b2-4842-8a18-7b5d1b998e80.png) | ![IMG_0310](https://user-images.githubusercontent.com/2602313/145087177-92c34d99-00e3-4a6c-9fdd-d34b1be72002.png)
