### ISSUE TITLE
Update error pages design.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4338]
The html files we use are outdated, update them according to screenshots in this ticket https://github.com/brave/brave-ios/issues/483

Interstitial pages:

![image](https://user-images.githubusercontent.com/2388823/129392245-6d1f76e9-3500-47ad-8bf3-c465a1fa386e.png)

Page might charge you money:

![image](https://user-images.githubusercontent.com/2388823/114470222-63b96100-9ba3-11eb-8221-73526e4673e9.png)

Connection not private:

![image](https://user-images.githubusercontent.com/2388823/114472546-49818200-9ba7-11eb-8a95-929434b64d1d.png)

Phishing warning:

![image](https://user-images.githubusercontent.com/2388823/114472555-4dad9f80-9ba7-11eb-9cd9-2964f7b88bd6.png)

Malware warning:

![image](https://user-images.githubusercontent.com/2388823/114472564-530aea00-9ba7-11eb-945f-41a05f7a2971.png)

Unwanted software warning:

![image](https://user-images.githubusercontent.com/2388823/114472576-58683480-9ba7-11eb-9b88-ca589b710352.png)

**Comment by rmcfadden3** [comment]
Hi @anthonypkeane & @iccub. Here's comments for each of the error messages:

- "This page isn't working" … lgtm. No changes
- "This site can't be reached" … would be nice if we could give the user some recourse, e.g. "Try re-typing the URL, or opening a search engine and searching for the new URL." But if we can't, message is OK as-is.
- "No internet" … suggest changing the title to "No internet access" and then prefacing the bullet points with a line that says "It appears you're not online. To fix this, try:"
- "Your clock is ahead" … suggest changing this title to "Your system time is wrong" and then changing the CTA button to "Update date / time"
- "Connect to network" … lgtm. No changes.
- "Did you mean example.com?" … lgtm. No changes.
- "The page ahead may try to charge you money" … suggest changing title to "The page you're trying to visit may charge you money"
- "Your connection is not private" … lgtm. No changes.
- "Deceptive site ahead" … lgtm. No changes.
- "The site ahead contains malware" … suggest changing title to "The site you're trying to visit contains malware"
- "The site ahead contains harmful programs" … suggest changing title to "The site you're trying to visit contains harmful programs"

**Comment by iccub** [comment]
Note to QA: Not all copy could be updated. I updated what I could.
As long as there's typos, nothing to verify 1:1 by qa in my opinion

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8 running 1.32.3 (21.11.13.9)
- Verified error pages use new design

Malware | Phishing | No Internet | Not Private | Can't Reach 
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/142032990-7da7eaa1-c462-48ba-9883-32505572c694.png) | ![image](https://user-images.githubusercontent.com/17010094/142032972-34195be2-ae43-4d5c-b4e9-2d5b3c0d57a9.png) | ![image](https://user-images.githubusercontent.com/17010094/142033032-30928ed9-9e93-4f10-95a8-4923b42b40d1.png) | ![image](https://user-images.githubusercontent.com/17010094/142033010-70e4c4f9-a230-4c31-a59d-6abd0185aefa.png) | ![image](https://user-images.githubusercontent.com/17010094/142033018-7988f012-be60-4ec1-b0ce-877dfce80bdc.png)

------------------

Verification passed on iPhone XR with iOS 15.0.1 running 1.32.3 (21.11.13.9)
- Verified error pages use new design

Malware | Phishing | No Internet | Not Private | Can't Reach 
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/142032880-606c191f-5dfa-465c-8eda-8bcdee25cdd7.png) | ![image](https://user-images.githubusercontent.com/17010094/142032899-a2eda9df-40dc-42c9-942d-6a9cb39fc875.png) | ![image](https://user-images.githubusercontent.com/17010094/142032851-ea88d82d-542f-4597-b5a5-88f610d99cdc.png) | ![image](https://user-images.githubusercontent.com/17010094/142032865-c8e3203f-55dc-453d-a4c2-0ef8bbd9582c.png) | ![image](https://user-images.githubusercontent.com/17010094/142032838-e2af2ff5-bd68-4a0b-9771-7a88c471321c.png)

------------------

Verification passed on iPad Pro with iOS 15.2 Beta2 running 1.32.3 (21.11.13.9)
- Verified error pages use new design

Malware | Phishing | No Internet | Not Private | Can't Reach 
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/142033112-f8dd4ff8-e0a1-470e-9c22-b783334b6da0.png) | ![image](https://user-images.githubusercontent.com/17010094/142033098-26427a06-40af-45df-8382-b9719139d194.png) | ![image](https://user-images.githubusercontent.com/17010094/142033150-2b253ccf-480a-425f-a8dd-45ec63cff03b.png) | ![image](https://user-images.githubusercontent.com/17010094/142033132-25b74cfb-47c8-439c-a5ea-3f9a5f32bd7d.png) | ![image](https://user-images.githubusercontent.com/17010094/142033169-70adf92c-5dc2-47e2-b351-d62b68c9a81f.png)

------------------

Verification passed on iPad 5th Gen with iOS 14 running 1.32.3 (21.11.13.9)
- Verified error pages listed below

Malware | Malware
----- | -----
![IMG_0559](https://user-images.githubusercontent.com/28145373/142063094-16960c58-c37b-4157-b60d-80c8c5820a3d.PNG) | ![IMG_0560](https://user-images.githubusercontent.com/28145373/142063101-98d28ad7-a8de-4a49-bf50-754bea15d7d7.PNG)

Phishing | Phishing
----- | -----
![IMG_0557](https://user-images.githubusercontent.com/28145373/142063197-0e1281e6-a23c-4e6b-9604-e11469dad7e3.PNG) | ![IMG_0558](https://user-images.githubusercontent.com/28145373/142063217-212a67b3-c151-451e-a5e5-47e4640cd21c.PNG)

Not Private | Not Private | Site cannot be reached | No Internet | Insecure connection
----- | ----- | ----- | ----- | -----
![private1](https://user-images.githubusercontent.com/28145373/142063534-43f8315a-72a3-4b21-b6d3-efdf62a7fc45.PNG) | ![private2](https://user-images.githubusercontent.com/28145373/142063542-d144ebfa-d900-425e-9f4c-b07cf17a3595.PNG) | ![site cannot be reached](https://user-images.githubusercontent.com/28145373/142063557-c9ec4300-29df-4456-ac40-0456a0781297.PNG) | ![no internet](https://user-images.githubusercontent.com/28145373/142063569-6ce9f61a-5bfc-4a23-b5ce-31e7cb5b2a06.PNG) | ![secure connection](https://user-images.githubusercontent.com/28145373/142063589-bc134bc4-9518-4413-893e-951b0ac9d99d.jpg)


-----------------------
