### ISSUE TITLE
Sometimes when sharing a URL with Brave, it doesn't open

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#4339]
### Description: 
- Open a URL in Safari
- Share it with Brave
- Doesn't Open

### Steps to Reproduce 
  1. Open a URL in Safari
  2. Share it with Brave

**Actual result:** 
- URL doesn't open

**Expected result:**
- URL should open

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.32.1

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8 running 1.32.1(21.10.20.18)
- Verified steps from issue description
- Verified links open when shared from Safari
------------
Verification passed on iPhone XR with iOS 15.0.1 running 1.32.1(21.10.20.18)
- Verified steps from issue description
- Verified links open when shared from Safari
------------
Verification passed on iPad Pro with iOS 15.1 Beta 3 running 1.32.1(21.10.20.18)
- Verified steps from issue description
- Verified links open when shared from Safari
