### ISSUE TITLE
Support setting a default currency code in wallet settings

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#4341]
### Description: 
In iOS Wallet/Buy Screen, we need an update on the TextField that shows the correct currency on the right side based on user's preferred currency. Currently we are just showing a `$` sign on the left side of the TextField which may not apply to all currencies. 

In wallet settings, we should show the current currency code from WalletService with ability to set a new code from a pre-defined list of currency codes

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.39 (22.5.30.17)
- Verified steps from [#5277](https://github.com/brave/brave-ios/pull/5277)
- Verified `US` is set as default currency
- Verified changing `US` to `EUR` shows the Euro currency indicator in wallet
- Verified currency indicator(position) is shown based on region locale 
- Verified setting default currency to `EUR` and setting locale/region to US shows the Euro currency indicator but shows in front of the balance

USD (Default) | USD Currency indicator | GBP Default Currency | GBP Currency indicator | EUR Default Currency | EUR Currency Indicator | Incorrect locale for default currency
-- | -- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/171222233-84793532-0ba9-4da0-b126-af74ab1f6f8f.png) | ![image](https://user-images.githubusercontent.com/17010094/171222318-85056b56-9e9e-49ab-85fe-e6ab53ce5428.png) | ![image](https://user-images.githubusercontent.com/17010094/171222629-b0483668-9cd4-45ba-8ffc-98447c48b59e.png) | ![image](https://user-images.githubusercontent.com/17010094/171222764-4c88c2f5-11d0-4bf9-9b01-a771674d0b67.png) | ![image](https://user-images.githubusercontent.com/17010094/171222657-eb78cbf8-4aa9-4ae1-ad40-9be87abab09a.png) | ![image](https://user-images.githubusercontent.com/17010094/171222711-7f1c649c-a5f9-4620-b713-f6042aad921c.png) | ![image](https://user-images.githubusercontent.com/17010094/171223466-052e3c71-b8a1-4ec5-b244-3f3533ad8a95.png)

----------
Verification passed on iPhone XR with iOS 15.3 running 1.39 (22.5.30.17)
- Verified steps from [#5277](https://github.com/brave/brave-ios/pull/5277)
- Verified `US` is set as default currency
- Verified changing `US` to `RUB` shows the RUB currency indicator in wallet
- Verified currency indicator(position) is shown based on region locale 
- Verified setting default currency to `RUB` and setting locale/region to US shows the RUB currency indicator but shows in front of the balance

USD (Default) | USD Currency indicator |  RUB Default Currency | RUB Currency indicator | JPY Default Currency | JPY Currency Indicator | Incorrect locale for default currency
-- | -- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/171227653-b86c6d2f-398f-41e7-86c4-ca58eb948915.png) | ![image](https://user-images.githubusercontent.com/17010094/171227635-15be5d8c-76e2-435e-ae39-4ad8ddae3ac5.png) | ![image](https://user-images.githubusercontent.com/17010094/171227676-29260bc4-a453-444a-b583-98fbe184f1ac.png) | ![image](https://user-images.githubusercontent.com/17010094/171228091-77e6a1f9-34f0-4a65-9cd7-fb4a9ab58da8.png) | ![image](https://user-images.githubusercontent.com/17010094/171228133-b03a28c6-c19c-4582-91b2-9b7b1858c539.png) | ![image](https://user-images.githubusercontent.com/17010094/171228113-ce3efd4d-50e1-4d9d-bf3f-8723c5abc597.png) | ![image](https://user-images.githubusercontent.com/17010094/171227511-21642c34-965e-45b4-bc3b-7c274fb970fb.png)

--------

Verification passed on iPad Pro with iOS 15.5 Beta running 1.39 (22.5.30.17)
- Verified steps from [#5277](https://github.com/brave/brave-ios/pull/5277)
- Verified `US` is set as default currency
- Verified changing `US` to `CHK` shows the CHK currency indicator in wallet
- Verified currency indicator(position) is shown based on region locale 
- Verified setting default currency to `CHK` and setting locale/region to US shows the CHK currency indicator but shows in front of the balance

USD (Default) | USD Currency indicator | CHK Default Currency | CHK Currency indicator | INR Default Currency | INR Currency Indicator | Incorrect locale for default currency
-- | -- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/171230572-cbaf0024-2f22-4b6c-a5eb-e89fdc4f71f0.png) | ![image](https://user-images.githubusercontent.com/17010094/171230552-cc337be0-6068-4588-91f9-63e620402222.png) | ![image](https://user-images.githubusercontent.com/17010094/171230631-b57bf4a8-67c7-4976-8cc7-8c493aadafa9.png) | ![image](https://user-images.githubusercontent.com/17010094/171230655-4170ead7-e39d-4bc8-b203-e9de43bdbc6a.png) | ![image](https://user-images.githubusercontent.com/17010094/171230682-130c44d8-b694-449d-9556-b814bcbe3c61.png) | ![image](https://user-images.githubusercontent.com/17010094/171230697-08f829fe-933b-4d5d-a4a7-ba4954fcd002.png) | ![image](https://user-images.githubusercontent.com/17010094/171230513-6c05e1f3-7aad-47d5-888a-d93ce7c03b06.png)
