### ISSUE TITLE
Hide screen in App Switcher 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4356]
### Description: 
If a user is in PBO mode, by default hide screen in App Switcher.

Use this screen when switching apps: https://www.figma.com/file/irDJRP35FUwsRu60Wp9fM6/iOS-onboarding?node-id=1107%3A26026

Potentially have an On/Off option for this in Settings > Brave Shields & Privacy under Other Privacy Settings

**Comment by iccub** [comment]
so we do that already using a gray background

**Comment by anthonypkeane** [comment]
https://appfigures.com/reviews/42132121512L_lSvK5hL-WhgF9BkwFbMCw?lang=en
