### ISSUE TITLE
download .mobileconfig files and auto import into settings app similar to Chrome for iOS and Safari

### ISSUE THREAD

**Issue by gh0sti** [brave/brave-ios#4358]
## Problem Description
 Allow Brave Browser on iOS to download mobile config files to auto import into settings app.

## Feature Overview 
Chrome v 95 just added this feature https://apps.apple.com/us/app/google-chrome/id535886823

## Implementation Details 
similar to how in safari if you download and install mobile config for ios beta/dev updates

## User Experience 

1. head to developer.apple.com sign in and download mobile config of latest iOS beta
2. popup similar to safari states that the mobile config is in settings and ready for review to install.

**Comment by kylehickinson** [comment]
Chromium implementation: 

- [Part 1](https://source.chromium.org/chromium/chromium/src/+/1a9d33d8826b18003e67102033b903e6be1507c2)
- [Part 2](https://source.chromium.org/chromium/chromium/src/+/0c3ef80869943bd1b00a30de9f6297c796f24a0a)

**Comment by gh0sti** [comment]
Could this feature be added soon? It’s frustrating trying to install mobile config files for testing iOS betas when I have to move the config from brave downloads over to my iPhone storage download folder.

**Comment by hffvld** [comment]
Hi @kylehickinson I tried to verify it but looks like the `Sign in` page is not loading in `Brave` - #8392.

cc @kjozwiak

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.2
Brave build: 1.60 (23.11.9.15)
BraveCore: 1.60.114 (119.0.6045.124)
```

Filed follow-up issue #8392 and #8393
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-ios/issues/4358#issue-1030746748 > Verify

OR

2. Copy and Paste this URL `https://gist.githubusercontent.com/nstanke/1df2ad86487c3b9a805d/raw/9b09ade1208a7f9ab41d3b3e7ca76fb1d877bece/mailinabox.mobileconfig` > Verify

**ACTUAL RESULTS:**
- Verified that pop-up message is shown and states that the mobile config is in settings and ready for review to install.

---------------------------

|Brave|Safari|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/c0e54a96-b9b6-43fe-8565-bc55112d52bd) | ![2](https://github.com/brave/brave-ios/assets/128532965/8743a8ec-b23f-4cc1-aa57-dc725eac6b80) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/367d8a0c-1a81-44ee-a4ad-fab5911344e9) | ![2](https://github.com/brave/brave-ios/assets/128532965/2969a165-5b6e-42fa-bf6d-f6f3b2d05e8a) |

https://github.com/brave/brave-ios/assets/128532965/bd0a52a1-75eb-47cc-a0ba-5cdaa0583f82
