### ISSUE TITLE
Playback starts with Music app when device is disconnected and reconnected to CarPlay

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4361]
### Description: 
Playback starts with Music app when device is disconnected and reconnected to CarPlay

### Steps to Reproduce 
  1. Play music from the Music App
  2. Open Brave on iPhone and open Playlist to start playlist audio/video to play through CarPlay
  3. Disconnect device from CarPlay, Lock screen removes Brave Playlist and shows Music App as paused
  4. Connect the device back to CarPlay, Music app starts playback 

**Actual result:** 
Playback starts with Music app when device is disconnected and reconnected to CarPlay

**Expected result:**
Should playback from Brave Playlist as that was the last app which was used to play via CarPlay

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.32.1(21.10.19.14)

**Device details:** 
iPhone 7+ (iOS 14.8)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T @iccub please move it out of milestone if its not a release blocker

**Comment by Brandon-T** [comment]
This is done entirely by the system. We don't have control of which app gets priority over playback. Technically the system is supposed to start the last played app, but not sure why Music gets priority over Brave. The same happens to Spotify as well :S

**Comment by srirambv** [comment]
In that case we can close this as wontfix. If there is a remote chance that we can control it then we can do it otherwise its fine to close.
