### ISSUE TITLE
Playback pauses when a phone call is received

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4362]
### Description: 
Playback pauses when a phone call is received

### Steps to Reproduce 
  1. Connect device to CarPlay
  2. Either play an item from Brave Playlist or via CarPlay
  3. Receive a phone call (Talk or disconnect)
  4. Playback doesn't resume

**Actual result:** 
Playback pauses when a phone call is received

**Expected result:**
Playback should resume as this works with Music App

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.32.1(21.10.19.14)

**Device details:** 
iPhone 7+ (iOS 14.8)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T

**Comment by srirambv** [comment]
This happens when you access another app like WhatsApp/Telegram where Siri starts talking and closing the app doesn't resume playback with Playlist. Works with Music App

**Comment by Brandon-T** [comment]
PR is Blocked: https://github.com/brave/brave-ios/pull/4238

**Comment by iccub** [comment]
Moving out of the milestone

**Comment by iccub** [comment]
Fixed here https://github.com/brave/brave-ios/issues/4237
