### ISSUE TITLE
Error when trying to start playback

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4365]
### Description: 
Playback fails when trying to play a playlist item. Possibly related to #4364

### Steps to Reproduce 
  1. Add item to playlist 
  2. Connect device to CarPlay
  3. Try to play the video file via CarPlay

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/138084095-48fcc0dd-44af-463c-9e0c-8a4d19dccbdb.png) | ![image](https://user-images.githubusercontent.com/17010094/138089004-3538269c-b872-4d39-918a-6e85a81fd4e8.png)
-- | --

**Expected result:**
No such error

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Only once

**Brave Version:** 
1.32.1(21.10.19.14)

**Device details:** 
iPhone XR (iOS 15.0.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T

**Comment by iccub** [comment]
This will be fixed in next build i'll make with rest of playlist bugfixes,
if this will not fix it then there's not much we can do about it

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8 running 1.32.1(21.10.20.18)
- Verified steps from issue description
- Verified no error when playing the file via CarPlay or via playlist on Brave App
-----------
Verification passed on iPhone XR with iOS 15.0.1 running 1.32.1(21.10.20.18)
- Verified steps from issue description
- Verified no error when playing the file via CarPlay or via playlist on Brave App
