### ISSUE TITLE
YouTube Playback Pauses While Scrolling

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ios#437]
### Description: 
Videos will halt playback while the page is being scrolled.

### Steps to Reproduce 
  1. Navigate to https://www.youtube.com/watch?v=dRekGX6dQRY
  2. Scroll down the page during playback

**Actual result:**
Video and audio halt until scrolling has finished.

**Expected result:**
Video (or at least audio) should continue while scrolling.

**Reproduces how often:**
Always.

**Brave Version:**
1.6.6 (18.11.15.17)

**Device details:**
iPhone 6s

**Website problems only:**
- did you check in Safari/Firefox (WkWebView-based browsers)? 
Works in Safari

### Additional Information 
Reported on [Twitter](https://twitter.com/oskarkruschitz/status/1066747065982754819).

**Comment by iccub** [comment]
It does not happen in 1.7.
I will close it, feel free to resubmit the bug to the old repo https://github.com/brave/browser-ios
