### ISSUE TITLE
Handle buy UI for different ethereum chains

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4371]
When you select a test network, the UI changes to show slightly different copy and the button opens a test faucet as seen on desktop nightly:

<img width="299" alt="image" src="https://user-images.githubusercontent.com/529104/138168332-92271842-cb5b-4650-a13e-4d970b800a11.png">

URLs are hard-coded here: https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/utils/buy-asset-url.ts

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33 (21.12.7.21)
- Verified for each network, Buy UI shows specific network details

Ethereum | Rinkeby | Ropsten | Goerli | Kovan
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/145274441-cd69c83f-0c0f-4f45-8872-253e7100a85e.png) | ![image](https://user-images.githubusercontent.com/17010094/145274454-642d4b89-f630-4d03-86d3-d31140af8a18.png) | ![image](https://user-images.githubusercontent.com/17010094/145274466-857cb237-c7ac-49a5-b51b-f1cfe42a6368.png) | ![image](https://user-images.githubusercontent.com/17010094/145274476-872d98db-9fa3-4529-8c5e-66f857cf2018.png) | ![image](https://user-images.githubusercontent.com/17010094/145274486-ceb2be7d-eb33-4dcc-b60b-606b281383c6.png)

---------
Verification passed on iPhone XR with iOS 15.1 running 1.33 (21.12.7.21)
- Verified for each network, Buy UI shows specific network details

Ethereum | Rinkeby | Ropsten | Goerli | Kovan
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/145274367-38e562d7-0b5b-4588-8301-e1fc1abb05b1.png) | ![image](https://user-images.githubusercontent.com/17010094/145274382-6406467c-fe98-4e8a-b07d-c822b22f2a42.png) | ![image](https://user-images.githubusercontent.com/17010094/145274394-346c5624-8011-4fb4-a4b8-de7422743926.png) | ![image](https://user-images.githubusercontent.com/17010094/145274406-38aaf89d-a1be-464b-83bf-c460c2c3f66e.png) | ![image](https://user-images.githubusercontent.com/17010094/145274417-345cad94-5ec1-44bb-9e28-706503c59ad1.png)

---------
Verification passed on iPad Pro  with iOS 15.2 running 1.33 (21.12.7.21)
- Verified for each network, Buy UI shows specific network details

Ethereum | Rinkeby | Ropsten | Goerli | Kovan
-- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/145274258-4a96dc8b-1011-4803-a576-739b98545124.png) | ![image](https://user-images.githubusercontent.com/17010094/145274278-85b47b5a-e347-4fb5-96b3-9197e7891a00.png) | ![image](https://user-images.githubusercontent.com/17010094/145274292-f102d73d-a85a-4217-ab7f-3a691a34ff0b.png) | ![image](https://user-images.githubusercontent.com/17010094/145274301-b8eebe3e-9fc8-466f-992d-4979486dd188.png) | ![image](https://user-images.githubusercontent.com/17010094/145274319-40c42a61-6a04-4f30-9cee-e8f75ffba51f.png)
