### ISSUE TITLE
Updated onboarding - 'Set as default' callout revamp

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4373]
See `Mobile Onboarding 2021 Revision` doc in shared drive.
`Set Brave as default` section

- [ ] Update our current default browser callout with new designs

**Comment by GeetaSarvadnya** [comment]
Verification is **PASSED** `iPad 7th Generation version iOS 15.1` running `Brave version 1.33 (21.11.30.21)`

- Logged https://github.com/brave/brave-ios/issues/4603
- Currently, we can't set brave as default and there is no API to check whether brave is the default browser or not. So there is no point in testing the upgrade cases in this situation, In this issue default browser UI validation is covered
- Default browser callout functionality is covered in the issue https://github.com/brave/brave-ios/issues/4376

<details>
<summary>Set default browser modal UI validations_PASSED</summary>
 
- Confirmed `Set Brave as default` prompt is shown for the new user
- Confirmed content text message shown on the prompt is as per the Figma spec
- Confirmed click on `Skip this` opens up the NTP
- Confirmed click on `Set as default` button opens up the device settings page

**Light theme** | **Dark theme**
----------------|---------------
![IMG_0096](https://user-images.githubusercontent.com/38657976/144647085-c8971632-59fb-444e-b14b-68fea9201cf1.PNG) | ![IMG_0097](https://user-images.githubusercontent.com/38657976/144647129-3c01a600-d7b7-404c-a6fa-1781366605ee.PNG)
</details>

**Comment by stephendonner** [comment]
Verification is **PASSED** `iPhone 6s on iOS 14.4.2` running `Brave version 1.33 (21.12.10.20)`

- @GeetaSarvadnya logged https://github.com/brave/brave-ios/issues/4603
- Currently, we can't set brave as default and there is no API to check whether brave is the default browser or not. So there is no point in testing the upgrade cases in this situation, In this issue default browser UI validation is covered
- Default browser callout functionality is covered in the issue https://github.com/brave/brave-ios/issues/4376

<details>
<summary>Set default browser modal UI validations - PASSED</summary>
 
- Confirmed `Set Brave as default` prompt is shown for the new user
- Confirmed content text message shown on the prompt is as per the Figma spec
- Confirmed click on `Skip this` opens up the NTP
- Confirmed click on `Set as default` button opens up the device settings page

**Light theme** | **Dark theme**
----------------|---------------
![Image from iOS (6)](https://user-images.githubusercontent.com/387249/145651735-0fab4666-f5e3-42a3-a613-24822981f545.png) | ![Image from iOS (7)](https://user-images.githubusercontent.com/387249/145651744-960bd0f2-dca9-4582-8669-297cc0eabb10.png)


</details>

-----

Verification is **PASSED** `iPhone 6s on iOS 15.1` running `Brave version 1.33 (21.12.10.20)`

- @GeetaSarvadnya logged https://github.com/brave/brave-ios/issues/4603
- Currently, we can't set brave as default and there is no API to check whether brave is the default browser or not. So there is no point in testing the upgrade cases in this situation, In this issue default browser UI validation is covered
- Default browser callout functionality is covered in the issue https://github.com/brave/brave-ios/issues/4376

<details>
<summary>Set default browser modal UI validations - PASSED</summary>
 
- Confirmed `Set Brave as default` prompt is shown for the new user
- Confirmed content text message shown on the prompt is as per the Figma spec
- Confirmed click on `Skip this` opens up the NTP
- Confirmed click on `Set as default` button opens up the device settings page

**Light theme** | **Dark theme**
----------------|---------------
![Image from iOS](https://user-images.githubusercontent.com/387249/145652138-70d9d28f-96af-4d1d-be9e-a787d15f87a4.png) | ![Image from iOS (1)](https://user-images.githubusercontent.com/387249/145652136-904df3f1-a6e5-4467-abdd-91250077a5ae.png)
</details>
