### ISSUE TITLE
Updated onboarding - Shields education revamp

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4375]
See `Mobile Onboarding 2021 Revision` doc in shared drive.
`Brave Shields Ongoing Education` section

- [ ] Update shield education popups. Expand it for all regions
- [ ] Remove popups that are not used anymore, they should be in figma

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPad 7th Generation version iOS 15.1` running `Brave version 1.33 (21.12.9.23)`

<details>
<summary>Shield education popups_US Region</summary>

**_Shields intro messages removed_**

1. Confirmed `Trackers and ads blocked on this page` popup is removed from 1.33 (visit amazon.com/any adblocking website and ensure the `Trackers and ads blocked on this page` popup isn't shown)
2. Confirmed `10+ trackers popover` is removed from 1.33 (visit cnn.com and confirm 10+ trackers popover is not shown)
3. Confirmed HTTPS upgrade doesn't trigger a popup message when we visit the non-HTTPS site (http://hackernews.com It'removed from 1.32 itself so no popup message in 1.33)

- `X shields blocked popups` testing is covered for US region in https://github.com/brave/brave-ios/issues/4627

</details>


<details>
<summary>Shield education popups_JP Region</summary>

**_Shields intro messages removed_**

1. Confirmed `Trackers and ads blocked on this page` popup is removed from 1.33 (visit amazon.com/any adblocking website and ensure the `Trackers and ads blocked on this page` popup isn't shown)
2. Confirmed `10+ trackers popover` is removed from 1.33 (visit cnn.com and confirm 10+ trackers popover is not shown)
3. Confirmed HTTPS upgrade doesn't trigger a popup message when we visit the non-HTTPS site (http://hackernews.com It'removed from 1.32 itself so no popup message in 1.33)

- `X shields blocked popups` testing is covered for JP region in https://github.com/brave/brave-ios/issues/4627

</details>

---------------

Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.33 (21.12.13.3)`

<details>
<summary>Shield education popups_US Region</summary>

**_Shields intro messages removed_**

1. Confirmed `Trackers and ads blocked on this page` popup is removed from 1.33 (visit amazon.com/any adblocking website and ensure the `Trackers and ads blocked on this page` popup isn't shown)
2. Confirmed `10+ trackers popover` is removed from 1.33 (visit cnn.com and confirm 10+ trackers popover is not shown)
3. Confirmed HTTPS upgrade doesn't trigger a popup message when we visit the non-HTTPS site (http://hackernews.com It'removed from 1.32 itself so no popup message in 1.33)

- `X shields blocked popups` testing is covered for US region in https://github.com/brave/brave-ios/issues/4627

</details>


<details>
<summary>Shield education popups_JP Region</summary>

**_Shields intro messages removed_**

1. Confirmed `Trackers and ads blocked on this page` popup is removed from 1.33 (visit amazon.com/any adblocking website and ensure the `Trackers and ads blocked on this page` popup isn't shown)
2. Confirmed `10+ trackers popover` is removed from 1.33 (visit cnn.com and confirm 10+ trackers popover is not shown)
3. Confirmed HTTPS upgrade doesn't trigger a popup message when we visit the non-HTTPS site (http://hackernews.com It'removed from 1.32 itself so no popup message in 1.33)

- `X shields blocked popups` testing is covered for JP region in https://github.com/brave/brave-ios/issues/4627

</details>

---------------

Verification **PASSED** on `iPhone 6+` running `iOS 14.6` using `1.33 (21.12.13.3)`

<details>
<summary>Shield education popups_US Region</summary>

**_Shields intro messages removed_**

1. Confirmed `Trackers and ads blocked on this page` popup is removed from 1.33 (visit amazon.com/any adblocking website and ensure the `Trackers and ads blocked on this page` popup isn't shown)
2. Confirmed `10+ trackers popover` is removed from 1.33 (visit cnn.com and confirm 10+ trackers popover is not shown)
3. Confirmed HTTPS upgrade doesn't trigger a popup message when we visit the non-HTTPS site (http://hackernews.com It'removed from 1.32 itself so no popup message in 1.33)

- `X shields blocked popups` testing is covered for US region in https://github.com/brave/brave-ios/issues/4627

</details>


<details>
<summary>Shield education popups_JP Region</summary>

**_Shields intro messages removed_**

1. Confirmed `Trackers and ads blocked on this page` popup is removed from 1.33 (visit amazon.com/any adblocking website and ensure the `Trackers and ads blocked on this page` popup isn't shown)
2. Confirmed `10+ trackers popover` is removed from 1.33 (visit cnn.com and confirm 10+ trackers popover is not shown)
3. Confirmed HTTPS upgrade doesn't trigger a popup message when we visit the non-HTTPS site (http://hackernews.com It'removed from 1.32 itself so no popup message in 1.33)

- `X shields blocked popups` testing is covered for JP region in https://github.com/brave/brave-ios/issues/4627

</details>
