### ISSUE TITLE
Updated onboarding - Sync and Rewards scheduled callouts.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4376]
See `Mobile Onboarding 2021 Revision` doc in shared drive.
`Day 4: Sync other devices` and `Day 7: Rewards` sections

- [ ] Add sync callout
- [ ] Add Rewards callout

**Comment by GeetaSarvadnya** [comment]
- Callouts should be shown only for the new users, not for the existing users, mentioned in the spec (table at the end) and confirmed with @soner-yuksel 

Callout days for different popups
```
VPN callout will happen on OR after 4days
Sync callout will happen on OR after 6days
Rewards callout will happen on OR after 8days
Default browser callout will happen on OR after 10days
```

### Test plan:

**Callout Orders for New user_Normal Browsing mode**

<details>
<summary>Case 1: Order of popovers when if no of days >=4days</summary>

(4 days passed 1 callout conditions is satisfied)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro messages
3. Kill the app from memory
4. Set the device date ahead by 4+ days (In my case I have set it to 15th Dec)
5. Relaunch the app and confirm VPN callout is shown to the user
6. Kill the app from memory and relaunch the app
7. Confirm no callout will happen
8. Repeat step 6 and confirm no callout will happen

</details>

<details>
<summary>Case 2: Order of popovers when if no of days =6days</summary>

(6 days passed and 2 callout conditions are satisfied)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro message
3. Kill the app from memory
4. Set the device date ahead by 6 days
5. Relaunch the app and confirm VPN callout is shown to the user
6. Kill the app from memory 
7. Relaunch the app and confirm Sync callout is shown to the user

</details>

<details>
<summary>Case 3: Order of popovers when if no of days >=7days</summary>

(7 days passed and 2 callout conditions are satisfied)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro message
3. Kill the app from memory
4. Set the device date ahead by 6+ days (In my case I have set it to 17th Dec)
5. Relaunch the app and confirm VPN callout is shown to the user
6. Kill the app from memory and relaunch
7. Sync callout should happen
8. Kill the app from memory and relaunch
9. No other callout will be shown 
10. Repeat step 8 again and confirm no callouts will happen

</details>

<details>
<summary>Case 4: Order of popovers when if no of days >=9days</summary>

(9 days passed and 3 callout conditions are satisfied)

1. Launch browser, skip the onboarding flow, and dismiss NTP intro messages
2. Kill the app from memory
3. Set the device date ahead by 9 days (In my case I have set it to 19th Dec)
4. Launch browser
5. VPN call should happen in 1st launch
6. Kill the app from memory
7. Rewards callout should happen
8. Kill the app from memory
9. Sync callout should happen
</details>

<details>
<summary>Case 5: Order of popovers when if no of days >=10days</summary>

(10 days passed and all the 4 callout conditions are satisfied)

1. Launch browser, skip onboarding and dismiss NTP intro messages
2. Kill the app from memory
3. Set the device date ahead by 12 days (in my case I have set it to 22nd Dec)
4. Launch browser
5. VPN callout should happen (as per the spec VPN callout should happen 1st when all the conditions are satisfied)
6. Kill the app from memory
7. Launch browser
8. Default browser callout should happen (as it has got precedence over the brave rewards)
9. Kill the app from memory
10. Launch browser
11. Rewards callout should happen (If rewards are available for the region) as It has got precedence over sync callout 
12. Kill the app from memory
13. Launch browser
14. Sync callout should happen
</details>

<details>
<summary>Case 6: Order of popovers when sync is enabled and if no of days >=6days</summary>

(6 days passed 2 callout conditions are satisfied (VPN and Sync). But sync callout should not happen if Sync is enabled)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro messages
3. Enable the standalone sync
4. Kill the app from memory
5. Set the device date ahead by 6+ days (In my case I have set it to 17th Dec)
6. Relaunch the app
7. VPN callout should happen
8. Kill the app from memory
9. Relaunch the app
10. Sync callout should not happen as sync is already enabled
11. Repeat steps 8 and 9 and ensure no callouts will happen

</details>

<details>
<summary>Case 7: Order of popovers when sync is enabled and if no of days >=8days</summary>

(8 days passed 3 callout conditions are satisfied (VPN, Sync, and Rewards). But sync callout should not happen if Sync is enabled)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro messages
3. Enable the standalone sync
4. Kill the app from memory
5. Set the device date ahead by 8+ days (In my case I have set it to 19th Dec)
6. Relaunch the app
7. VPN callout should happen
8. Kill the app from memory
9. Relaunch the app
10. Rewards callout should happen
11. Repeat steps 8 and 9 and confirm sync callout will not happen as it's enabled (no callouts will happen in this step)

</details>

<details>
<summary>Case 8: Order of popovers when sync is enabled and if no of days >=10days</summary>

(10 days passed all the 4 callout conditions are satisfied (VPN, Sync, Rewards, and Default browser). But sync callout should not happen if Sync is enabled)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro messages
3. Enable the standalone sync
4. Kill the app from memory
5. Set the device date ahead by 10+ days (In my case I have set it to 22nd Dec)
6. Relaunch the app
7. VPN callout should happen
8. Kill the app from memory
9. Relaunch the app
10. Default browser callout should happen
11. Repeat steps 8 and 9
12. Rewards callout should happen
13. Repeat steps 8 and 9
14. No callouts should happen (sync callout will not happen as sync is already enabled)

</details>

<details>
<summary>Case 9: Order of popovers when Rewards is enabled and if no of days >=8days</summary>

(8 days passed 3 callout conditions are satisfied (VPN, Sync, and Rewards). But Rewards callout should not happen if Rewards is enabled)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro messages
3. Enable the Rewards (Tap on BR panel in NTP and click on `Start` in Rewards popup)
4. Kill the app from memory
5. Set the device date ahead by 8+ days (In my case I have set it to 19th Dec)
6. Relaunch the app
7. VPN callout should happen
8. Kill the app from memory
9. Relaunch the app
10. Sync callout should happen
11. Repeat steps 8 and 9
12. No callouts should happen 
</details>

<details>
<summary>Case 10: Order of popovers when Rewards is enabled and if no of days >=10days</summary>

(10 days passed all the 4 callout conditions are satisfied (VPN, Sync, Rewards, and Default browser). But rewards callout should not happen if Rewards is enabled)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro messages
3. Enable the Rewards (Tap on BR panel in NTP and click on `Start` in Rewards popup)
4. Kill the app from memory
5. Set the device date ahead by 10+ days (In my case I have set it to 22nd Dec)
6. Relaunch the app
7. VPN callout should happen
8. Kill the app from memory
9. Relaunch the app
10. Default browser callout should happen
11. Repeat steps 8 and 9
12. Sync callout should happen
13. Repeat steps 8 and 9
14. No callouts should happen (rewards callout will not happen as rewards is already enabled)

</details>

**Callout Orders for New user_Private Browsing Only mode**

**Prerequisites:** After installing brave, skip the onboarding flow and dismiss the NTP intro messages and then open Settings>Brave Shields & Privacy>Enable `Private Browsing Only` switch for each case.

<details>
<summary>Case 1: Order of popovers when if no of days >=4days</summary>

(4 days passed 1 callout conditions is satisfied)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro messages
3. Kill the app from memory
4. Set the device date ahead by 4+ days (In my case I have set it to 15th Dec)
5. Relaunch the app and confirm VPN callout is shown to the user
6. Kill the app from memory and relaunch the app
7. Confirm no callout will happen
8. Repeat step 6 and confirm no callout will happen

</details>

<details>
<summary>Case 2: Order of popovers when if no of days =6days</summary>

(6 days passed and 2 callout conditions are satisfied)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro message
3. Kill the app from memory
4. Set the device date ahead by 6 days
5. Relaunch the app and confirm VPN callout is shown to the user
6. Kill the app from memory 
7. Relaunch the app and confirm Sync callout is shown to the user

Step 5 | Step 7
----------|--------

</details>

<details>
<summary>Case 3: Order of popovers when if no of days >=7days</summary>

(7 days passed and 2 callout conditions are satisfied)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro message
3. Kill the app from memory
4. Set the device date ahead by 6+ days (In my case I have set it to 17th Dec)
5. Relaunch the app and confirm VPN callout is shown to the user
6. Kill the app from memory and relaunch
7. Sync callout should happen
8. Kill the app from memory and relaunch
9. No other callout will be shown 
10. Repeat step 8 again and confirm no callouts will happen

Step 7 | Step 5
-------|-------
![IMG_0202](https://user-images.githubusercontent.com/38657976/145550035-47812475-146c-4e99-9bd6-35a32c934ea9.PNG)

</details>

<details>
<summary>Case 4: Order of popovers when if no of days >=9days</summary>

(9 days passed and 3 callout conditions are satisfied)

1. Launch browser, skip the onboarding flow, and dismiss NTP intro messages
2. Kill the app from memory
3. Set the device date ahead by 9 days (In my case I have set it to 19th Dec)
4. Launch browser
5. VPN call should happen in 1st launch
6. Kill the app from memory
7. Rewards callout should happen
8. Kill the app from memory
9. Sync callout should happen

Step 7 | Step 9 | Step 5
-------|-------|--------
![IMG_0200](https://user-images.githubusercontent.com/38657976/145548211-ccff0878-fc87-45bc-8fd8-24f60b9de602.PNG) | ![IMG_0201](https://user-images.githubusercontent.com/38657976/145548237-b9c3724b-711c-48d0-80be-f895ad6434dd.PNG)
</details>

<details>
<summary>Case 5: Order of popovers when if no of days >=10days</summary>

(10 days passed and all the 4 callout conditions are satisfied)

1. Launch browser, skip onboarding and dismiss NTP intro messages
2. Kill the app from memory
3. Set the device date ahead by 12 days (in my case I have set it to 22nd Dec)
4. Launch browser
5. VPN callout should happen (as per the spec VPN callout should happen 1st when all the conditions are satisfied)
6. Kill the app from memory
7. Launch browser
8. Default browser callout should happen (as it has got precedence over the brave rewards)
9. Kill the app from memory
10. Launch browser
11. Rewards callout should happen (If rewards are available for the region) as It has got precedence over sync callout 
12. Kill the app from memory
13. Launch browser
14. Sync callout should happen

 step 8 | step 11 | step 14 | Step 5
-----|----|-------|-----
![IMG_0193](https://user-images.githubusercontent.com/38657976/145469360-0e4b3ba1-32f4-430c-a725-133d5b87347e.PNG) | ![IMG_0194](https://user-images.githubusercontent.com/38657976/145469491-b2dcbba7-5f29-4bcb-ac7a-081ffeb3d68a.PNG) | ![IMG_0195](https://user-images.githubusercontent.com/38657976/145469579-0ded44cf-c972-45a1-adc3-913f12b60f32.PNG)

</details>

<details>
<summary>Case 6: Order of popovers when sync is enabled and if no of days >=6days</summary>

(6 days passed 2 callout conditions are satisfied (VPN and Sync). But sync callout should not happen if Sync is enabled)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro messages
3. Enable the standalone sync
4. Kill the app from memory
5. Set the device date ahead by 6+ days (In my case I have set it to 17th Dec)
6. Relaunch the app
7. VPN callout should happen
8. Kill the app from memory
9. Relaunch the app
10. Sync callout should not happen as sync is already enabled
11. Repeat steps 8 and 9 and ensure no callouts will happen

</details>

<details>
<summary>Case 7: Order of popovers when sync is enabled and if no of days >=8days</summary>

(8 days passed 3 callout conditions are satisfied (VPN, Sync, and Rewards). But sync callout should not happen if Sync is enabled)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro messages
3. Enable the standalone sync
4. Kill the app from memory
5. Set the device date ahead by 8+ days (In my case I have set it to 19th Dec)
6. Relaunch the app
7. VPN callout should happen
8. Kill the app from memory
9. Relaunch the app
10. Rewards callout should happen
11. Repeat steps 8 and 9 and confirm sync callout will not happen as it's enabled (no callouts will happen in this step)

</details>

<details>
<summary>Case 8: Order of popovers when sync is enabled and if no of days >=10days</summary>

(10 days passed all the 4 callout conditions are satisfied (VPN, Sync, Rewards, and Default browser). But sync callout should not happen if Sync is enabled)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro messages
3. Enable the standalone sync
4. Kill the app from memory
5. Set the device date ahead by 10+ days (In my case I have set it to 22nd Dec)
6. Relaunch the app
7. VPN callout should happen
8. Kill the app from memory
9. Relaunch the app
10. Default browser callout should happen
11. Repeat steps 8 and 9
12. Rewards callout should happen
13. Repeat steps 8 and 9
14. No callouts should happen (sync callout will not happen as sync is already enabled)

</details>

<details>
<summary>Case 9: Order of popovers when Rewards is enabled and if no of days >=8days</summary>

(8 days passed 3 callout conditions are satisfied (VPN, Sync, and Rewards). But Rewards callout should not happen if Rewards is enabled)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro messages
3. Enable the Rewards (Tap on BR panel in NTP and click on `Start` in Rewards popup)
4. Kill the app from memory
5. Set the device date ahead by 8+ days (In my case I have set it to 19th Dec)
6. Relaunch the app
7. VPN callout should happen
8. Kill the app from memory
9. Relaunch the app
10. Sync callout should happen
11. Repeat steps 8 and 9
12. No callouts should happen 

</details>

<details>
<summary>Case 10: Order of popovers when Rewards is enabled and if no of days >=10days</summary>

(10 days passed all the 4 callout conditions are satisfied (VPN, Sync, Rewards, and Default browser). But rewards callout should not happen if Rewards is enabled)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro messages
3. Enable the Rewards (Tap on BR panel in NTP and click on `Start` in Rewards popup)
4. Kill the app from memory
5. Set the device date ahead by 10+ days (In my case I have set it to 22nd Dec)
6. Relaunch the app
7. VPN callout should happen
8. Kill the app from memory
9. Relaunch the app
10. Default browser callout should happen
11. Repeat steps 8 and 9
12. Sync callout should happen
13. Repeat steps 8 and 9
14. No callouts should happen (rewards callout will not happen as rewards is already enabled)

</details>

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.33 (21.12.10.20)` on an `iPhone 6s (iOS 14.4.2)`.

Ran through `Case 5: Order of popovers when no. of days 10 >`.

NOTE:

Filed the following two issues for the callout-cards' incorrect ordering:
* https://github.com/brave/brave-ios/issues/4721 (Japan region)
* https://github.com/brave/brave-ios/issues/4719 (US region)

**Comment by LaurenWags** [comment]
Verified on `iPad mini` with `iOS 15` running `1.33 (21.12.13.3)`

<details>
<summary>Case 5: Order of popovers when if no of days =10days</summary>

(10 days passed and all the 4 callout conditions are satisfied)

1. Launch browser, skip onboarding and dismiss NTP intro messages
2. Kill the app from memory
3. Set the device date ahead by 10 days (in my case I have set it to 23rd Dec)
4. Launch browser
5. VPN callout should happen (as per the spec VPN callout should happen 1st when all the conditions are satisfied)
6. Kill the app from memory
7. Launch browser
8. Default browser callout should happen (as it has got precedence over the brave rewards)
9. Kill the app from memory
10. Launch browser
11. Rewards callout should happen (If rewards are available for the region) as It has got precedence over sync callout 
12. Kill the app from memory
13. Launch browser
14. Sync callout should happen

Step 5 | Step 8 | Step 11 | Step 14
----- | ----- | ----- | -----
![IMG_0176](https://user-images.githubusercontent.com/28145373/145830665-7d8edb3b-335d-4eba-80af-b7d5b7ecf19a.PNG) | ![IMG_0177](https://user-images.githubusercontent.com/28145373/145830680-8f626c21-1aff-4c9f-a9d1-480f5a27db45.PNG) | ![IMG_0178](https://user-images.githubusercontent.com/28145373/145830695-94099880-672a-4f95-8985-47168e778fea.PNG) | ![IMG_0179](https://user-images.githubusercontent.com/28145373/145830698-4d93d381-baab-4c65-8aad-53af747c70d5.PNG)
</details>

<details>
<summary>Case 5: Order of popovers when if no of days >10days</summary>

(more than 10 days passed and all the 4 callout conditions are satisfied, although out of order - see logged issue https://github.com/brave/brave-ios/issues/4719)

1. Launch browser, skip onboarding and dismiss NTP intro messages
2. Kill the app from memory
3. Set the device date ahead by 12 days (in my case I have set it to 25th Dec)
4. Launch browser
5. VPN callout should happen (as per the spec VPN callout should happen 1st when all the conditions are satisfied)
6. Kill the app from memory
7. Launch browser
8. Default browser callout should happen (as it has got precedence over the brave rewards)
9. Kill the app from memory
10. Launch browser
11. Rewards callout should happen (If rewards are available for the region) as It has got precedence over sync callout 
12. Kill the app from memory
13. Launch browser
14. Sync callout should happen

Step 5 | Step 8 | Step 11 | Step 14
----- | ----- | ----- | -----
![IMG_0171](https://user-images.githubusercontent.com/28145373/145830883-c8f14368-a9bf-4bf2-800e-92bb646eaea1.PNG) | ![IMG_0172](https://user-images.githubusercontent.com/28145373/145830894-a05ef685-a5f1-46d6-ab46-20cdae5e2aeb.PNG) | ![IMG_0173](https://user-images.githubusercontent.com/28145373/145830906-f205aea1-73cd-42ca-9bc4-ad0f16c358cc.PNG) | ![IMG_0174](https://user-images.githubusercontent.com/28145373/145830919-adb401fe-d5dd-4b9e-8719-4769eeabc805.PNG)

Note, as mentioned, steps 5 and 8 results are switched. Known issue.

</details>

<details>
<summary>Case 8: Order of popovers when sync is enabled and if no of days =10days</summary>

(10 days passed all the 4 callout conditions are satisfied (VPN, Sync, Rewards, and Default browser). But sync callout should not happen if Sync is enabled)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro messages
3. Enable the standalone sync
4. Kill the app from memory
5. Set the device date ahead by 10 days (In my case I have set it to 23rd Dec)
6. Relaunch the app
7. VPN callout should happen
8. Kill the app from memory
9. Relaunch the app
10. Default browser callout should happen
11. Repeat steps 8 and 9
12. Rewards callout should happen
13. Repeat steps 8 and 9
14. No callouts should happen (sync callout will not happen as sync is already enabled)

Step 7 | Step 10 | Step 12
----- | ----- | -----
![IMG_0180](https://user-images.githubusercontent.com/28145373/145833200-f72e4844-deb4-4db7-9446-29c2a93e8bf4.PNG) | ![IMG_0181](https://user-images.githubusercontent.com/28145373/145833212-be07c660-31a4-46c8-87a8-bfdb29fc048b.PNG) | ![IMG_0182](https://user-images.githubusercontent.com/28145373/145833227-94b8a4f0-3bda-4a32-aabc-875fa9b69dd2.PNG)

</details>

<details>
<summary>Case 8: Order of popovers when sync is enabled and if no of days >10days</summary>

(>10 days passed all the 4 callout conditions are satisfied (VPN, Sync, Rewards, and Default browser). But sync callout should not happen if Sync is enabled. First 2 call outs are out of order - see logged issue https://github.com/brave/brave-ios/issues/4719)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro messages
3. Enable the standalone sync
4. Kill the app from memory
5. Set the device date ahead by 12 days (In my case I have set it to 25th Dec)
6. Relaunch the app
7. VPN callout should happen
8. Kill the app from memory
9. Relaunch the app
10. Default browser callout should happen
11. Repeat steps 8 and 9
12. Rewards callout should happen
13. Repeat steps 8 and 9
14. No callouts should happen (sync callout will not happen as sync is already enabled)

Step 7 | Step 10 | Step 12
----- | ----- | -----
![IMG_0183](https://user-images.githubusercontent.com/28145373/145834714-f1d257d5-d06f-4801-9ce8-0a9cf524f10b.PNG) | ![IMG_0184](https://user-images.githubusercontent.com/28145373/145834728-d6168fa3-d956-4125-b6b6-ee640c8927fc.PNG) | ![IMG_0185](https://user-images.githubusercontent.com/28145373/145834741-ee276b37-f797-4c9f-aa5f-c55ed1822b5c.PNG)

Note, as mentioned, steps 7 and 10 results are switched. Known issue.

</details>

<details>
<summary>Case 10: Order of popovers when Rewards is enabled and if no of days =10days</summary>

(10 days passed all the 4 callout conditions are satisfied (VPN, Sync, Rewards, and Default browser). But rewards callout should not happen if Rewards is enabled)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro messages
3. Enable the Rewards (Tap on BR panel in NTP and click on `Start` in Rewards popup)
4. Kill the app from memory
5. Set the device date ahead by 10 days (In my case I have set it to 23rd Dec)
6. Relaunch the app
7. VPN callout should happen
8. Kill the app from memory
9. Relaunch the app
10. Default browser callout should happen
11. Repeat steps 8 and 9
12. Sync callout should happen
13. Repeat steps 8 and 9
14. No callouts should happen (rewards callout will not happen as rewards is already enabled)

Step 7 | Step 10 | Step 12
----- | ----- | -----
![IMG_0186](https://user-images.githubusercontent.com/28145373/145838284-d96c9391-f70d-4675-8978-9ba795f233e6.PNG) | ![IMG_0187](https://user-images.githubusercontent.com/28145373/145838296-7ba1bfb9-52b2-45f9-93c4-3e0ec1a730a8.PNG) | ![IMG_0188](https://user-images.githubusercontent.com/28145373/145838308-4d3324fe-19db-4cf9-935e-61b6bf8a6493.PNG)

</details>

<details>
<summary>Case 10: Order of popovers when Rewards is enabled and if no of days >10days</summary>

(10+ days passed all the 4 callout conditions are satisfied (VPN, Sync, Rewards, and Default browser). But rewards callout should not happen if Rewards is enabled. First 2 call outs are out of order - see logged issue https://github.com/brave/brave-ios/issues/4719)

1. Clean profile 1.33
2. Skip the onboarding flow and dismiss the NTP intro messages
3. Enable the Rewards (Tap on BR panel in NTP and click on `Start` in Rewards popup)
4. Kill the app from memory
5. Set the device date ahead by 12 days (In my case I have set it to 25th Dec)
6. Relaunch the app
7. VPN callout should happen
8. Kill the app from memory
9. Relaunch the app
10. Default browser callout should happen
11. Repeat steps 8 and 9
12. Sync callout should happen
13. Repeat steps 8 and 9
14. No callouts should happen (rewards callout will not happen as rewards is already enabled)

Step 7 | Step 10 | Step 12
----- | ----- | -----
![IMG_0189](https://user-images.githubusercontent.com/28145373/145838977-7c7a455f-69f8-4065-9ecf-96afb6be6aec.PNG) | ![IMG_0190](https://user-images.githubusercontent.com/28145373/145838988-69b7f38c-dadd-4e8a-afa6-d00191f2e0fd.PNG) | ![IMG_0191](https://user-images.githubusercontent.com/28145373/145838997-0b4174aa-5e0d-45cb-87e9-1257f9d2e4b7.PNG)

Note, as mentioned, steps 7 and 10 results are switched. Known issue.

</details>
