### ISSUE TITLE
Updated onboarding - Revamp 3dot menu on new tab page

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4377]
See `Mobile Onboarding 2021 Revision` doc in shared drive.
`Browser Menu` section

- [ ] Update menu on new tab page
- [ ] Do not change order of items on menu when on a website

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPad 7th Generation version iOS 15.1` running `Brave version 1.33 (21.12.9.23)`


### US Region

<details>
<summary>Browser Menu on NTP</summary>

- NTP intro messages are covered in https://github.com/brave/brave-ios/issues/4372#issuecomment-984465058
- When the user goes through the onboarding flow, skip on any slide opens up the NTP, and NTP intro messages are shown, after dismissing the `All set!` popup the welcome onboarding flow ends.
- Confirmed that tap on 3 dot menu opens up the `Browser menu` which contains settings mentioned in the screenshots below
- Confirmed `Brave news` and `talk` are hidden in PBO mode
- Confirmed tap on Brave talk opens up www.talk.brave.com 
- Confirmed `Brave News` appear in the browser menu when brave news is enabled via NTP
- Confirmed tap on the playlist will open up the playlist window
- Confirmed wallet (Beta) setting got added to the browser menu

Browser menu on NTP | Browser menu on website | Private browsing Only settings (PBO)
-------|-------|------
![IMG_0207](https://user-images.githubusercontent.com/38657976/145612205-c58acae6-4291-4ae7-9e99-e8f85e865f4e.PNG) | ![IMG_0208](https://user-images.githubusercontent.com/38657976/145612238-546c57cc-7608-4dfc-bc57-a1cee679ee4c.PNG) | ![IMG_0209](https://user-images.githubusercontent.com/38657976/145612259-aee120ff-c587-4450-a40b-28a868248805.PNG)

</details>

<details>
<summary>Browser Menu on Website</summary>

- Confirmed wallet (Beta) setting got added to the browser menu
- Confirmed all the existing settings are shown 
- Confirmed there is no change in the browser menu on the website, changes are applied only for the browser menu on NTP
</details>

### JP Region

<details>
<summary>Browser Menu on NTP</summary>

- Confirmed that tap on 3 dot menu opens up the `Browser menu` which contains settings mentioned in the screenshots below
- Confirmed `Brave news` and `talk` are hidden in PBO mode
- Confirmed tap on Brave talk opens up www.talk.brave.com 
- Confirmed `Brave News` appear in the browser menu when brave news is enabled via NTP
- Confirmed tap on the playlist will open up the playlist window
- Confirmed wallet (Beta) setting got added to the browser menu

Browser menu on NTP | Browser menu on website | Private browsing Only settings (PBO)
-------|-------|------
![IMG_0213](https://user-images.githubusercontent.com/38657976/145621950-b461d565-7910-4cad-b97f-17594d7755c8.PNG) | ![IMG_0212](https://user-images.githubusercontent.com/38657976/145621981-9c2c8bf1-660b-4d5a-ad17-654cfda546b0.PNG) | ![IMG_0214](https://user-images.githubusercontent.com/38657976/145622010-dc8a8dd8-444a-4ecf-848a-31b4692eae23.PNG)


</details>

<details>
<summary>Browser Menu on Website</summary>

- Confirmed wallet (Beta) setting got added to the browser menu
- Confirmed all the existing settings are shown 
- Confirmed there is no change in the browser menu on the website, changes are applied only for the browser menu on NTP

</details>

**Comment by stephendonner** [comment]
Verification **PASSED** on `iPhone 6, iOS 15.0.2` running `Brave version 1.33 (21.12.10.20)`


### US Region

<details>
<summary>Browser Menu on NTP</summary>

- NTP intro messages are covered in https://github.com/brave/brave-ios/issues/4372#issuecomment-984465058
- When the user goes through the onboarding flow, skip on any slide opens up the NTP, and NTP intro messages are shown, after dismissing the `All set!` popup the welcome onboarding flow ends.
- Confirmed that tap on 3 dot menu opens up the `Browser menu` which contains settings mentioned in the screenshots below
- Confirmed `Brave news` and `talk` are hidden in PBO mode
- Confirmed tap on Brave talk opens up www.talk.brave.com 
- Confirmed `Brave News` appear in the browser menu when brave news is enabled via NTP
- Confirmed tap on the playlist will open up the playlist window
- Confirmed wallet (Beta) setting got added to the browser menu

Browser menu on NTP | Browser menu on website | Private browsing Only settings (PBO)
-------|-------|------
![Image from iOS (2)](https://user-images.githubusercontent.com/387249/145648442-56d31e52-b43a-4b50-b18b-b2c110ba771b.png) | ![Image from iOS (3)](https://user-images.githubusercontent.com/387249/145648470-26f3219a-4886-4e1c-a4d8-669560e6f89a.png) | ![Image from iOS (4)](https://user-images.githubusercontent.com/387249/145648493-46c8cead-a133-413b-b825-a8efae0c2efd.png)




</details>

<details>
<summary>Browser Menu on Website</summary>

- Confirmed `Wallet (Beta)` setting got added to the browser menu
- Confirmed all the existing settings are shown 
- Confirmed there is no change in the browser menu on the website, changes are applied only for the browser menu on NTP
</details>

### JP Region

<details>
<summary>Browser Menu on NTP</summary>

- Confirmed that tap on 3 dot menu opens up the `Browser menu` which contains settings mentioned in the screenshots below
- Confirmed `Brave news` and `talk` are hidden in PBO mode
- Confirmed tap on Brave talk opens up www.talk.brave.com 
- Confirmed `Brave News` appear in the browser menu when brave news is enabled via NTP
- Confirmed tap on the playlist will open up the playlist window
- Confirmed wallet (Beta) setting got added to the browser menu

Browser menu on NTP | Browser menu on website | Private browsing Only settings (PBO)
-------|-------|------
![Image from iOS](https://user-images.githubusercontent.com/387249/145648643-03c261a3-f24b-48b6-a818-28797dec950c.png) | ![Image from iOS (1)](https://user-images.githubusercontent.com/387249/145648656-bc1754b1-3f82-42ba-afbd-6cb80ac4c2dc.png) | ![Image from iOS (2)](https://user-images.githubusercontent.com/387249/145648666-0b9027a3-09a5-442a-8bc3-a545cb29a7f7.png)




</details>

<details>
<summary>Browser Menu on Website</summary>

- Confirmed `Wallet (Beta)` setting got added to the browser menu
- Confirmed all the existing settings are shown 
- Confirmed there is no change in the browser menu on the website, changes are applied only for the browser menu on NTP

</details>

-----------

Verification **PASSED** on `iPhone 6, iOS 14.4.2` running `Brave version 1.33 (21.12.10.20)`


### US Region

<details>
<summary>Browser Menu on NTP</summary>

- NTP intro messages are covered in https://github.com/brave/brave-ios/issues/4372#issuecomment-984465058
- When the user goes through the onboarding flow, skip on any slide opens up the NTP, and NTP intro messages are shown, after dismissing the `All set!` popup the welcome onboarding flow ends.
- Confirmed that tap on 3 dot menu opens up the `Browser menu` which contains settings mentioned in the screenshots below
- Confirmed `Brave news` and `talk` are hidden in PBO mode
- Confirmed tap on Brave talk opens up www.talk.brave.com 
- Confirmed `Brave News` appear in the browser menu when brave news is enabled via NTP
- Confirmed tap on the playlist will open up the playlist window
- Confirmed wallet (Beta) setting got added to the browser menu

Browser menu on NTP | Browser menu on website | Private browsing Only settings (PBO)
-------|-------|------
![Image from iOS](https://user-images.githubusercontent.com/387249/145650851-df66869e-c01d-4f9f-98ff-38af1c336c2f.png) | ![Image from iOS (1)](https://user-images.githubusercontent.com/387249/145650883-ee401483-4e6f-4e82-a9f7-c3bfdb898dc0.png) | ![Image from iOS (3)](https://user-images.githubusercontent.com/387249/145650912-77773db2-4843-4313-bae2-9f69bb1604a1.png)






</details>

<details>
<summary>Browser Menu on Website</summary>

- Confirmed `Wallet (Beta)` setting got added to the browser menu
- Confirmed all the existing settings are shown 
- Confirmed there is no change in the browser menu on the website, changes are applied only for the browser menu on NTP
</details>

### JP Region

<details>
<summary>Browser Menu on NTP</summary>

- Confirmed that tap on 3 dot menu opens up the `Browser menu` which contains settings mentioned in the screenshots below
- Confirmed `Brave news` and `talk` are hidden in PBO mode
- Confirmed tap on Brave talk opens up www.talk.brave.com 
- Confirmed `Brave News` appear in the browser menu when brave news is enabled via NTP
- Confirmed tap on the playlist will open up the playlist window
- Confirmed wallet (Beta) setting got added to the browser menu

Browser menu on NTP | Browser menu on website | Private browsing Only settings (PBO)
-------|-------|------
![Image from iOS (5)](https://user-images.githubusercontent.com/387249/145650670-63832f6f-072d-4a74-9135-25dacb9d5fd4.png) | ![Image from iOS (4)](https://user-images.githubusercontent.com/387249/145650799-a953bbd9-ae30-4fe0-9df9-4e31ca4a41c8.png) | ![Image from iOS (3)](https://user-images.githubusercontent.com/387249/145650812-256541df-3c7d-4a76-8cc0-f8a11583bc80.png)






</details>

<details>
<summary>Browser Menu on Website</summary>

- Confirmed `Wallet (Beta)` setting got added to the browser menu
- Confirmed all the existing settings are shown 
- Confirmed there is no change in the browser menu on the website, changes are applied only for the browser menu on NTP

</details>
