### ISSUE TITLE
Updated onboarding - Playlist callout revamp

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4378]
See `Mobile Onboarding 2021 Revision` doc in shared drive.
`Youtube + Playlist` section

- [ ] Update the playlist callout. `Watch the video` part can be skipped for now.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPad 7th Generation` running Brave version `1.33 (21.12.6.2)`

- Logged https://github.com/brave/brave-ios/issues/4635
- Logged https://github.com/brave/brave-ios/issues/4637
- Logged https://github.com/brave/brave-ios/issues/4645


### US Region

<details>
<summary>Playlist callout_New user_PASSED</summary>

**YT domain**

- Confirmed the `Youtube playlist intro message` is shown on the playlist while playing any video on youtube.com  
- Confirmed content message is shown in the playlist intro message is as per the Figma spec 
- Confirmed youtube playlist intro message is dismissed when the user taps on the video
- Confirmed youtube playlist intro message is shown only once on youtube.com
- Go through the welcome onboarding flow and enter youtube.com In the `Enter a website` search box in the last slide and confirm `Youtube playlist intro message` is shown on the playlist while playing any video on youtube.com   

Example | Example
---------|--------
![IMG_0104](https://user-images.githubusercontent.com/38657976/144799509-d5d0325d-162f-42c7-85ee-74ee5d8e3b41.PNG) | ![IMG_0103](https://user-images.githubusercontent.com/38657976/144799561-2a9a0d22-0332-4aea-b3cc-01b7129adbd7.PNG)

**Vimeo domain**
- Confirmed the `Playlist intro message` is shown on the playlist while playing any video on vimeo.com 
- Confirmed content message is shown in the playlist intro message is as per the Figma spec
- Confirmed playlist intro message is dismissed when the user taps on the video
- Confirmed playlist intro message is shown only once on vimeo.com
- Go through the welcome onboarding flow and enter https://vimeo.com/bravelaurenwags In the `Enter a website` search box in the last slide and confirm `Vimeo playlist intro message` is shown on the playlist while playing a video on vimeo.com   

Example | Example
---------|--------
![IMG_0119](https://user-images.githubusercontent.com/38657976/144840602-09a0169a-2802-45cf-b1ff-1786412f598d.PNG) | ![IMG_0117](https://user-images.githubusercontent.com/38657976/144840637-2040064b-afc1-4343-9502-a89d489cc2cd.PNG)

**Twitch domain**
- Confirmed the `Playlist intro message` is shown on the playlist while playing any video on twitch.com 
- Confirmed content message is shown in the playlist intro message is as per the Figma spec
- Confirmed playlist intro message is dismissed when the user taps on the video
- Confirmed playlist intro message is shown only once on twitch.tv
- Go through the welcome onboarding flow and enter https://Twitch.tv In the `Enter a website` search box in the last slide and confirm `Twitch playlist intro message` is shown on the playlist while playing a video on twitch.tv   
- Logged https://github.com/brave/brave-ios/issues/4635

Example | Example
---------|--------
![IMG_0125](https://user-images.githubusercontent.com/38657976/144983483-5baadb7e-81c9-49df-a069-20372d197ac1.PNG) | ![IMG_0126](https://user-images.githubusercontent.com/38657976/144983530-481d43bf-9bec-489a-a0a4-c02d8410e819.PNG)

</details>

<details>
<summary>Playlist callout_Existing user_PASSED</summary>

- Confirmed playlist intro message is shown for the existing users for the video domains (YT/Vimeo/Twitch)

- Install `1.32.3 (21.11.17.19)` and open any `YT/Vimeo/Twitch` video and view the message `would you like to add a video to playlist message` and then upgrade the profile to `1.33 (21.12.6.21)` and open any video and ensure `Playlist intro message` is shown on the video

- Install `1.32.3 (21.11.17.19)` and open any YT video and view the message `would you like to add a video to playlist message` and then upgrade the profile to `1.33 (21.12.6.21)` and enter any video domain the URL bar and ensure `Playlist intro message` is shown on the video
</details>

### JP Region

<details>
<summary>Playlist callout_New user_PASSED</summary>

**https://www.nicovideo.jp video domain**

- Confirmed the `Playlist intro message` is shown on the playlist while playing any video on https://www.nicovideo.jp
- Confirmed content message is shown in the playlist intro message is as per the Figma spec
- Confirmed playlist intro message is dismissed when the user taps on the video
- Confirmed playlist intro message is shown only once on https://www.nicovideo.jp
- Go through the welcome onboarding flow and enter https://www.nicovideo.jp In the `Enter a website` search box in the last slide and confirm `Twitch playlist intro message` is shown on the playlist while playing a video 
- Logged https://github.com/brave/brave-ios/issues/4635

Example | Example
---------|--------
![IMG_0134](https://user-images.githubusercontent.com/38657976/144984630-c74d13e3-284f-4ca0-8280-fa15f03af4a2.PNG) | ![IMG_0131](https://user-images.githubusercontent.com/38657976/144984657-e4486162-fed9-452c-904d-ed95cb5ba41a.PNG)
</details>

<details>
<summary>Playlist callout_Existing user_PASSED</summary>

- Confirmed playlist intro message is shown for the existing users for the video domains https://www.nicovideo.jp/

- Install `1.32.3 (21.11.17.19)` and open YT video and view the message `would you like to add a video to playlist message` and then upgrade the profile to `1.33 (21.12.6.21)` and open any video and ensure `Playlist intro message` is shown on the video

- Install `1.32.3 (21.11.17.19)` and open any video from https://www.nicovideo.jp/ and view the message `would you like to add a video to playlist message` and then upgrade the profile to `1.33 (21.12.6.21)` and tap on any video and ensure `Playlist intro message` is shown on the video
</details>

-------------------

Verified on `iPhone 6s Plus` with iOS 15.1 running `Brave version 1.33 (21.12.9.19)`
Verified on `iPhone 7 Plus` with iOS 14.4.2 running `Brave version 1.33 (21.12.9.19)`

### US Region

<details>
<summary>Playlist callout_New user_PASSED</summary>

**YT domain**

- Confirmed the `Youtube playlist intro message` is shown on the playlist while playing any video on youtube.com  
- Confirmed content message is shown in the playlist intro message is as per the Figma spec 
- Confirmed youtube playlist intro message is dismissed when the user taps on the video
- Confirmed youtube playlist intro message is shown only once on youtube.com per session, and twice overall
- Go through the welcome onboarding flow and enter youtube.com In the `Enter a website` search box in the last slide and confirm `Youtube playlist intro message` is shown on the playlist while playing any video on youtube.com   

iPhone iOS 15 | iPhone iOS 14
---------|--------
![iOS15 YT](https://user-images.githubusercontent.com/28145373/145480439-887859da-fa21-4f71-8951-f330d2025544.PNG) | ![iOS14 YT](https://user-images.githubusercontent.com/28145373/145480444-3b33e553-b0a8-400f-b143-7e83ae6bab21.PNG)

**Vimeo domain**
- Confirmed the `Playlist intro message` is shown on the playlist while playing any video on vimeo.com 
- Confirmed content message is shown in the playlist intro message is as per the Figma spec
- Confirmed playlist intro message is dismissed when the user taps on the video
- Confirmed playlist intro message is shown only once on vimeo.com per session, and twice overall
- Go through the welcome onboarding flow and enter https://vimeo.com/bravelaurenwags In the `Enter a website` search box in the last slide and confirm `Vimeo playlist intro message` is shown on the playlist while playing a video on vimeo.com   

iPhone iOS 15 | iPhone iOS 14
---------|--------
![iOS15 iphone](https://user-images.githubusercontent.com/28145373/145487832-438fca11-8007-4deb-8077-66fb7c3e88c1.PNG) | ![iOS14 Iphone](https://user-images.githubusercontent.com/28145373/145487836-4e945b28-973c-499e-8c47-756b6cc0b006.PNG)

**Twitch domain**
- Confirmed the `Playlist intro message` is shown on the playlist while playing any video on twitch.com 
- Confirmed content message is shown in the playlist intro message is as per the Figma spec
- Confirmed playlist intro message is dismissed when the user taps on the video
- Confirmed playlist intro message is shown only once on twitch.tv per session, and twice overall
- Go through the welcome onboarding flow and enter https://Twitch.tv In the `Enter a website` search box in the last slide and confirm `Twitch playlist intro message` is shown on the playlist while playing a video on twitch.tv   

iPhone iOS 15 | iPhone iOS 14
---------|--------
![iOS15 twitch](https://user-images.githubusercontent.com/28145373/145489155-cbae1a28-7529-4cd1-a6cd-a1f2f5c45cdb.jpeg) | ![iOS14 twitch](https://user-images.githubusercontent.com/28145373/145489161-b0167db4-8ef4-455f-96f6-93f9381feb12.jpeg)

</details>


Verified on `iPhone 6s Plus` with iOS 15.1 running `Brave version 1.33 (21.12.9.23)`
Verified on `iPhone 7 Plus` with iOS 14.4.2 running `Brave version 1.33 (21.12.9.23)`

<details>
<summary>Playlist callout_Existing user_PASSED</summary>

- Confirmed playlist intro message is shown for the existing users for the video domains (YT/Vimeo/Twitch) when it wasn't shown twice prior to upgrade

- Install `1.32.3 (21.11.17.19)` and open any `YT/Vimeo/Twitch` video and view the message `would you like to add a video to playlist message` and then upgrade the profile to `1.33 (21.12.9.23)` and open any video and ensure `Playlist intro message` is shown on the video

- Install `1.32.3 (21.11.17.19)` and open any YT video and view the message `would you like to add a video to playlist message` and then upgrade the profile to `1.33 (21.12.9.23)` and enter any video domain the URL bar and ensure `Playlist intro message` is shown on the video
</details>

### JP Region

<details>
<summary>Playlist callout_New user_PASSED</summary>

**https://www.nicovideo.jp video domain**

- Confirmed the `Playlist intro message` is shown on the playlist while playing any video on https://www.nicovideo.jp
- Confirmed content message is shown in the playlist intro message is as per the Figma spec
- Confirmed playlist intro message is dismissed when the user taps on the video
- Confirmed playlist intro message is shown only once on https://www.nicovideo.jp
- Go through the welcome onboarding flow and enter https://www.nicovideo.jp In the `Enter a website` search box in the last slide and confirm `Twitch playlist intro message` is shown on the playlist while playing a video 

iPhone iOS 15 | iPhone iOS 14
---------|--------
![iOS15 iPhone](https://user-images.githubusercontent.com/28145373/145582933-8a5f0727-a14e-4333-80bb-37073cc74f0a.jpeg) | ![iOS14 iPhone](https://user-images.githubusercontent.com/28145373/145582961-a24229b2-12d2-4f4d-ba0c-00ebe54f89ee.jpeg)

</details>

<details>
<summary>Playlist callout_Existing user_PASSED</summary>

- Confirmed playlist intro message is shown for the existing users for the video domains https://www.nicovideo.jp/

- Install `1.32.3 (21.11.17.19)` and open YT video and view the message `would you like to add a video to playlist message` and then upgrade the profile to `1.33 (21.12.9.23)` and open any video and ensure `Playlist intro message` is shown on the video

- Install `1.32.3 (21.11.17.19)` and open any video from https://www.nicovideo.jp/ and view the message `would you like to add a video to playlist message` and then upgrade the profile to `1.33 (21.12.9.23)` and tap on any video and ensure `Playlist intro message` is shown on the video
</details>
