### ISSUE TITLE
Fingerprint issue on jcrew.narvar.com

### ISSUE THREAD

**Issue by ryanbr** [brave/brave-ios#4379]
### Description: 
IOS Fingerprint prevents site from loading (url adjusted to hide orginal personal details) `https://jcrew.narvar.com/tracking/jcrew/UPS?tracking_numbers=1Z6Y3114YW99302468&order[%E2%80%A6]utm_source=email&utm_medium=email&utm_campaign=order-shipped`

### Steps to Reproduce 
  1. Open `https://jcrew.narvar.com/tracking/jcrew/UPS?tracking_numbers=1Z6Y3114YW99302468&order[%E2%80%A6]utm_source=email&utm_medium=email&utm_campaign=order-shipped`
  2. Endless loading
  3.

**Actual result:** 
![unnamed (11)](https://user-images.githubusercontent.com/1659004/138190842-987bb494-f73f-47a1-882b-17afb0001b8a.jpg)

**Expected result:**

![unnamed (12)](https://user-images.githubusercontent.com/1659004/138191239-08bc167b-7aac-41e4-943e-4630c3003360.jpg)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.32.1 (Brave Dev)

**Device details:** 
iPhone 8plus

**Website problems only:**
- did you check with Brave Shields down? Yes (Disabling Fingerprinting)
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Tested on Android and Desktop (include strict fingerprinting). Doesn't break on these platforms.

Some fingerprinting errors on the Desktop: (maybe related):
![navar-finger](https://user-images.githubusercontent.com/1659004/138190940-1ef8b330-1aac-4016-9254-faf322e03756.png)

**Comment by cuba** [comment]
@ryanbr could you provide a new link so we can test if the new FP implementation solves this issue?
