### ISSUE TITLE
Playback fails when device is connected back to CarPlay 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4383]
### Description: 
Playback fails when device is connected back to CarPlay 

### Steps to Reproduce 
  1. Add items to playlist
  2. Connect device to CarPlay
  3. Open Brave on CarPlay
  4. Play an item from the playlist
  5. Disconnect device from CarPlay
  6. Reconnect device to CarPlay, playback doesn't resume

_**NOTE: With the same steps as above instead of playing item via CarPlay, if you start a track on iPhone Playlist and then disconnect and reconnect device, playback resumes automatically**_

**Actual result:** 
Playback fails when device is connected back to CarPlay 

**Expected result:**
Playback should resume irrespective of how the track was played in the first place

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.32.1(21.10.20.18)

**Device details:** 
iPhone 7+ (iOS 14.8) & iPhone XR (iOS 15.0.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
Not same as #4361

**Comment by Brandon-T** [comment]
Resuming playback is entirely up to the system. It is not up to the developer to resume the last played item in CarPlay. The system handles playing the item again.

The same thing happens in Spotify. I can probably add code to automatically play the item again, but not sure that I should OR if it will conflict with the system doing it.

**Comment by iccub** [comment]
let's close as wontfix
