### ISSUE TITLE
Manual test run for 1.32.1 on iPhone X using iOS 15

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4387]
## Installer

- [x] Check that installer is close to the size of the last release
- [x] Check the Brave version in About and make sure it is EXACTLY as expected

## Data

- [x] Verify that data from the previous build appears in the updated build as expected (bookmarks, etc)
- [x] Verify that the cookies from the previous build are preserved after upgrade
- [x] Verify saved password are retained after upgrade
- [x] Verify stats are retained after upgrade
- [x] Verify sync chain created in the previous version is still retained on upgrade
- [x] Verify per-site settings are preserved after upgrade

## Bookmarks

- [x] Verify that creating a bookmark works
- [x] Verify that clicking a bookmark from bookmark manager loads the bookmark
- [x] Verify that deleting a bookmark works
- [x] Verify that creating a bookmark folder works
- [x] Verify that creating a bookmark inside the created folder works
- [x] Verify that you can add a bookmark directly inside a bookmark folder
- [x] Verify that you can delete a bookmark in edit mode
- [x] Verify that you can delete a bookmark folder with bookmarks inside
- [x] Verify adding a bookmark domain, subpaths is retained and you are successfully able to visit the domain subpath in a new tab

## Favourites

- [x] Verify editing favourite and changing URL updates the favicons accordingly
- [x] Verify that you can remove favourites
- [x] Verify that you can add new favourites from the share menu

## Context menus

- [x] Make sure context menu items in the URL bar work
- [x] Make sure context menu items on content work with no selected text
- [x] Make sure context menu items on content work with selected text
- [x] Make sure context menu items on content work inside an editable control (input, textarea, or contenteditable)
- [x] Context menu: verify you can Open in Background Tab, and Open in Private Tab

## Downloads

- [x] Verify that you can save an image from a site
- [x] Verify that you are able to save a gif image

## Reader Mode

- [x] Visit http://theverge.com, open any article, verify the reader mode icon is shown in the URL bar
- [x] Verify tapping on the reader mode icon opens the article in reader mode
- [x] Edit reader mode settings and open different pages in reader mode and verify if the setting is retained across each article

## Gestures

- [x] Verify zoom in / out gestures work on https://www.homedepot.com/
- [x] Verify that navigating to a different origin resets the zoom
- [x] Swipe back and forward to navigate, verify this works as expected

## Password Managers

- [x] Verify tapping on 1Password on the slide-out keyboard launches 1Password App and able to select the stored credentials
- [x] Verify tapping on bitwarden password manager in the autofill field launches the app and auto-fills the stored data

## Shields Settings

- [x] Enable all switches in settings and visit a site and disable block scripts. Kill and relaunch the app and verify if the site shield settings are retained

## Browser Lock

- [x] Verify browser lock enables device passcode to be lock/unlock the browser
- [x] Verify swipe up/swipe down with browser in focus doesn't ask for device passcode
- [x] Verify cancel passcode shows unlock message
- [x] Remove the app from memory and relaunch, enter a wrong passcode, the browser should not be unlocked
- [x] Verify cancel fingerprint confirmation/face unlock shows enter passcode window when fingerprint/face unlock is set up on the device

## Brave Rewards/Ads

- [x] Verify wallet is auto-created after enabling rewards
- [x] Verify when you click on the BR panel while on a site, the panel displays if the site is verified or not
- [x] Verify ads are only shown when the app is being used
- [x] Verify clicking on an ad notification shows the landing page
- [x] Verify inline-ads show on Brave News and is correctly redeemed from the server
- [x] Verify `view`,`clicked` and `landed` and `dismiss` states are logged based on the action

## Sync

- [x] Verify you are able to join sync chain by scanning the QR code
- [x] Verify you are able to join sync chain using code words
- [x] Verify you are able to create a sync chain on the device and add other devices to the chain via QR code/Codewords
- [x] Verify that bookmarks from other devices on the chain show up on the mobile device after sync completes
- [x] Verify newly created bookmarks get synced to all devices on the sync chain
- [x] Verify existing bookmarks before joining sync chain also gets sync'd to all devices on the sync chain
- [x] Verify histroy sync is disabled by default. Enabling it starts sync'ing history items as well (limited to 200 entries)
- [x] Verify sync works on an upgrade profile and new bookmarks added post-upgrade sync's across devices on the chain
- [x] Verify you can create a standalone sync chain with one device

## Playlist & Autoplay

- [x] Verify Playlist is enabled by default on a clean install
- [x] Verify when a site with audio/video is detected, playlist button is shown in URL bar and a notification badge on the menu
- [x] Verify clicking the playlist button adds audio/video to playlist and initiates offline play
- [x] Verify able to add audio/video to playlist via share menu
- [x] Verify able to add audio/video to playlist via long press context menu
- [x] Verify Autoplay is enabled by default
- [x] Verify with autoplay enabled, able to play audio/video automatically
- [x] Verify with background audio enabled, able to play audio/video with device locked or app in background

## Brave News

- [x] Verify Brave News opt-in is shown on a clean install
- [x] Verify once opted-in Brave news starts showing artciles
- [x] Verify promoted content is shown on Brave News
- [x] Verify in-line ads are shown on Brave News
- [x] Verify able to add custom RSS feed to the list of sources
- [x] Verify able to disable content from a particular publisher by long press on the card

## Bravery settings

- [x] Check that HTTPS Everywhere works by loading http://https-everywhere.badssl.com/
- [x] Turning HTTPS Everywhere off or shields off both disable the redirect to https://https-everywhere.badssl.com/
- [x] Check that block ad and unblock ad works on http://slashdot.org
- [x] Check that toggling to blocking and allow ads works as expected
- [x] Verify that clicking through a cert error in https://badssl.com/ works
- [x] Verify that Safe Browsing works (https://www.raisegame.com/)
- [x] Enable block script globally from settings, Visit https://twitter.com/, nothing should load. Tap on Shields and disable block script, the page should load properly
- [x] Verify that preferences default Brave Shields settings take effect on pages with no site settings
### Fingerprint Tests
  - [x] Verify that turning on fingerprinting protection in preferences shows 3 fingerprint blocked at https://browserleaks.com/canvas . Verify that turning it off in the Bravery menu shows 0 fingerprints blocked
  - [x] Verify that audio fingerprint is blocked at https://audiofingerprint.openwpm.com/ when fingerprinting protection is on
  - [x] Verify that https://diafygi.github.io/webrtc-ips/ doesn't leak IP address when `Block all fingerprinting protection` is on

## Content tests

- [x] Go to https://feedly.com/ and make sure that the password can be saved.  Make sure the saved password is auto-populated when you visit the site again
- [x] Open an email on http://mail.google.com/ or `inbox.google.com` and click on a link. Make sure it works
- [x] Verify that PDF is loaded over https at https://basicattentiontoken.org/BasicAttentionTokenWhitePaper-4.pdf
- [x] Verify that PDF is loaded over HTTP at http://www.pdf995.com/samples/pdf.pdf
- [x] Verify that https://mixed-script.badssl.com/ shows up as grey not red (no mixed content scripts are run)
- [x] Verify that search results from https://startpage.com/ open in a new tab (due to target being _blank_)

## WebAuthn

- [x] Verify browser prompts for security key when trying to login to accounts 
- [x] Verify you are able to successfully authenticate an account using security key when prompted
- [x] Verify quickly connect and disconnect doesn't cause issue authenticating using security keys
- [x] Verify you are able to use security keys on both normal and private tabs
- [x] Verify you are able to use security keys to authenticate using NFC 

## App linker

- [x] Long press on a link in the Twitter app to get the share picker, choose Brave. Verify Brave doesn't crash after opening the link

## Session storage

- [x] Verify that tabs restore when closed, including active tab

**Comment by stephendonner** [comment]
Verified `PASSED` using `Brave 1.32.1 (21.10.21.16)` on everything except the `WebAuthN` section; @kjozwiak mind picking that up when you get a chance, and adding keywords?  🙏

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 12` running `iOS 15.0.2` via the following PR(s):

```
1.32.1 (21.10.21.16)
```

Went through the `WebAuthn` section without any issues. Created https://github.com/brave/brave-ios/issues/4398
