### ISSUE TITLE
Update portfolio backup banner colours

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4389]
They switched to the error-red colour rather than warning-yellow

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33 (21.12.7.21)
- Verified backup banner colour is updated to warning-yellow

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/145262438-935d505c-ed14-4dfd-9849-fc690a516fce.png) | ![image](https://user-images.githubusercontent.com/17010094/145262446-2623ccc7-f4a9-44e9-8813-9c2ee74feb49.png)

--------
Verification passed on iPhone XR with iOS 15.1 running 1.33 (21.12.7.21)
- Verified backup banner colour is updated to warning-yellow

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/145262394-602354ba-80ad-4b41-8f0d-54704019b99a.png) | ![image](https://user-images.githubusercontent.com/17010094/145262409-92b08cfc-630b-42b2-966f-87e5e23e5ffa.png)

--------
Verification passed on iPad Pro with iOS 15.2 running 1.33 (21.12.7.21)
- Verified backup banner colour is updated to warning-yellow

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/145262419-d5d39950-b610-4a57-89cc-06174c98139e.png) | ![image](https://user-images.githubusercontent.com/17010094/145262429-f21d5164-eaf4-4dbc-aee9-43ea98deaa4d.png)
