### ISSUE TITLE
Disable access to swap on testnets

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4394]
Desktop disables Swap on most chains, we should do the same.

If a user is on an unsupported chain, we should disable the swap button. If a user changes chains while on the swap screen we should display some sort of UI notifying the user that they cannot swap on that chain.

Desktops hard-coded support chains:

```typescript
export const BuySupportedChains = [
  kMainnetChainId,
  kRinkebyChainId,
  kRopstenChainId,
  kGoerliChainId,
  kKovanChainId,
  kLocalhostChainId
]

export const SwapSupportedChains = [
  kMainnetChainId,
  kRopstenChainId
] 
```

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.33(21.12.7.21)
- Verified swap is disabled and notification is shown about it 

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.1) | iPad Pro (iOS 15.2)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/145263358-461313db-e1c7-4618-aabb-f34d56695c22.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/145263485-fb805b9b-623a-4690-b04f-d7329b311a55.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/145263321-cd95457f-286d-402f-8836-6d4e5b98b908.png>
