### ISSUE TITLE
Add ability to view URL before loading the page from the QR Code Scanner

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4395]
### Description: 

The QR Code scanner we have within the app by either selecting the QR code icon in the URL bar (when focused) or via an App Shortcut loads the URL immediately upon scanning. We should provide the user with the ability to see the URL scanned before loading the URL for privacy/security reasons.

**Comment by kylehickinson** [comment]
@rmcfadden3 Can we get some copy for this? There are two flows, the user scans a QR code that contains plain text and the user scans a QR code that contains a URL.

I am thinking an alert that displays a different title/message based on the scanned content to explain that one will open a URL and one will begin a search for that URL.

Proposed:

URL Title: `Load URL`
URL Message: `Do you want to load the following url? {URL}`
Buttons: `Yes` | `Cancel`

Plaintext title: `Perform Search`
Plaintext message: `Perform a search with the following query? {Query}`
Buttons: `Yes` | `Cancel`

We can also merge these two to use the same copy if it can be generalized

**Comment by rmcfadden3** [comment]
@kylehickinson — your copy looks solid to me. I think it makes sense to split out into 2 separate messages, rather than trying to merge & generalize.

Couple small editing nits:

- "URL" should be in all caps in URL message body.
- Plaintext title should be in sentence case. So "Perform search" rather than "Perform Search"

**Comment by kylehickinson** [comment]
No longer necessary with the merged change: https://github.com/brave/brave-ios/pull/7319
