### ISSUE TITLE
[hackerone] #1376708 - Address bar spoofing

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#4396]
https://hackerone.com/reports/1376708

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.0.1 running 1.32.1(21.10.25.13)
- Verified notes [here](https://github.com/brave/internal/issues/820#issuecomment-952071162)
------------
Verification passed on iPad Pro with iOS 15.0.1 running 1.32.1(21.10.25.13)
- Verified notes [here](https://github.com/brave/internal/issues/820#issuecomment-952071162)
