### ISSUE TITLE
Reader mode doesn't show any article text

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#440]
### Description: 
Reader mode doesn't show any article text

### Steps to Reproduce 
  1. Visit https://theverge.com and open any article
  2. Click on the reader mode icon in URL bar
  3. Article doesn't show anything in reader mode (See attached video)

**Actual result:** 
[Reader Mode issue.zip](https://github.com/brave/brave-ios/files/2614770/Reader.Mode.issue.zip)

**Expected result:**
Should open the page in reader mode

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.11.21.22)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
It's probably site specific, does it happen on other websites and articles? I opened this article and it worked for me

**Comment by jhreis** [comment]
Please compare against Firefox's reader mode.

**Comment by iccub** [comment]
Seems to be working now, closing
