### ISSUE TITLE
Add more iPad keyboard shortcuts

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4400]
New Shortcuts added are:

Close All Tabs
Show History
Show Downloads
Show Bookmarks
Add to Favourites
Share With

Find in Page" key commands are organized and "Find Next" and "Find Previous" is shown only when there is a text in search bar.

Tab Navigation Key Commands are added to Show tab # 1-9 - Command + 1-9. These shortcuts are not marked with title but they exist like in other browsers. 

Another shortcut that is asked by users is for "Opening recently Closed" Tabs. This might require some work related with adding "Recently Closed Tabs" into our History.

https://github.com/brave/brave-ios/issues/3039

**Comment by iccub** [comment]
this is blocked until we decide on all shortcuts we want to add

**Comment by iccub** [comment]
To do: Investigate what keyboard shortcuts other browsers use that we don't, mostly try to match safari-iOS.

Look for iPad shortcut ideas in our github too.
Once done, you can update this ticket with all shortcuts we will add.

Not all shortcuts have to be added immediately, we can deliver easier ones first, harder ones later

**Comment by soner-yuksel** [comment]
The description is update, please check the details and about test plans in the PR.

**Comment by Uni-verse** [comment]
Verification completed on `iPad (7th Gen)` running `iPadOS 14.4.2` using `1.35 (22.1.21.14)`

Keyboard: Apple Smart Keyboard 

Enhancement Acceptance Criteria - https://github.com/brave/brave-ios/pull/4786#issue-1091235382

**UI Changes**

- Verified new shortcuts are added to the keyboard shortcuts guide (hold ⌘)
- Verified "Find Next" and "Find Previous" are shown in the keyboard shortcuts guide when text is present in the find in page (⌘ + F) search field. 

**Functionality**

- Verified pressing ⌘ + Y will show history page
- Verified pressing ⌘ + J will show "downloads" directory in the file.app 
- Verified pressing ⌘ + shift + O shows Bookmarks
- Verified pressing ⌘ + shift + D will add to favorites
- Verified pressing ⌘ + S will show share popup
**Failed** - pressing ⌘ + shift + tab will close all tabs (Note: this action does not close tabs but actually switches out of app gracefully) @soner-yuksel - was this requirement meant to behave this way? I think ⌘ shift tab is also the shortcut to switch apps on iPad. 

CC: @kjozwiak 

- Verified pressing ⌘ + F will show 'Find in Page' bar
- Verified pressing ⌘ + G will find next match 
- Verified pressing ⌘ + shift + G will find previous match
- Verified pressing ⌘ + 1-9 will make active tabs based on the order displayed.
- Verified user is able to use the new commands in private browsing mode.  

![IMG_0106](https://user-images.githubusercontent.com/17885425/150615703-e40c7ad5-d188-4cbb-be8f-b7008da9db3a.PNG)

![IMG_0107](https://user-images.githubusercontent.com/17885425/150615706-2a3bac06-ff53-4b61-8ce0-76b39d24f03b.PNG)

**Comment by raulchen** [comment]
@iccub @Uni-verse Hi, glad that Brave is adding more support for hardware keyboards on iPads. For me, the most annoying issue is that the ctrl+tab shortcut is broken. Could you take a look at this issue https://github.com/brave/brave-ios/issues/4502 ? Thank you!

**Comment by soner-yuksel** [comment]
@raulchen your concern with next tab should be fixed with this
https://github.com/brave/brave-ios/issues/5136

**Comment by soner-yuksel** [comment]
@Uni-verse failed shortcut is removed because of clash with system key shortcut

https://github.com/brave/brave-ios/issues/5136

**Comment by raulchen** [comment]
@soner-yuksel thanks. But it seems that ctrl+tab is replaced by a different shortcut in the latest version. 
I think ctrl+tab is still possible on iOS 15. This is how Firefox fixes this issue. https://github.com/mozilla-mobile/firefox-ios/pull/9658
