### ISSUE TITLE
Brave iOS cancels audio playing from other apps, even when pages aren't playing audio

### ISSUE THREAD

**Issue by pes10k** [brave/brave-ios#4402]
https://pitchfork.com/reviews/albums/various-artists-ill-be-your-mirror-a-tribute-to-the-velvet-underground-and-nico/ is the example in front of me right now.  Brave kills the audio (and because the video on the page is muted, the device goes silent).  This happens even if i dont unmute the video.

When i open in Safari, the background audio keeps playing as expected until i unmute the video.

**Comment by iccub** [comment]
More discussion about it here

https://bravesoftware.slack.com/archives/C06UXF3KJ/p1632748490240200

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave 1.33 (21.12.8.23) on an iPhone 6s running 15.0.2 and another iPhone 6s running 14.4.2.

Steps:

1. opened the `Podcasts` app
2. played a podcast
3. launched Brave `1.33 (21.12.8.23)`
4. loaded `https://pitchfork.com/reviews/albums/various-artists-ill-be-your-mirror-a-tribute-to-the-velvet-underground-and-nico/`
5. confirmed podcast is still playing audibly in the background
6. confirmed no audio from webpage
7. confirmed `Enable Auto-Play` preference is removed from `Settings`

![Image from iOS](https://user-images.githubusercontent.com/387249/145317318-69dcb732-2add-41e5-abaa-c34d1e00262a.png)

**Comment by kjozwiak** [comment]
So on the `iPad`, loading https://pitchfork.com/reviews/albums/various-artists-ill-be-your-mirror-a-tribute-to-the-velvet-underground-and-nico while other audio is playing will mute that audio. It's basically the same behaviour as Safari. @iccub mentioned that all we did was basically set a WebKit flag and the above issue really had no code.
