### ISSUE TITLE
[Follow up #4396]Address bar spoofing still needs fixing

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4404]
[Follow up #4396]Address bar spoofing still needs fixing

More info here: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1635243687051800?thread_ts=1635217386.045700&cid=C06UXF3KJ

cc: @jumde

**Comment by Brandon-T** [comment]
Not possible to fix: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1635280104067600?thread_ts=1635217386.045700&cid=C06UXF3KJ

Happens in every browser on both Desktop and Mobile.
