### ISSUE TITLE
progress indicator/scrubber doesn't restart to `0:00` when playback is restarted

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4408]
### Description: 

When enabling `Restart Playback` via the `Playback Options` under the `CarPlay` device, tapping on a video that's already playing will restart playback but not restart the progress indicator/scrubber back to `0:00`.

### Steps to Reproduce

**`Perquisites:`** iPhone connected to `CarPlay`

  1. launch Brave and connect your device to `CarPlay`
  2. save a few videos via `Playlist`
  3. enable `Restart Playback` via the Brave's `Playback Options` within `CarPlay`
  4. tap on a saved video within `CarPlay` and it should start playing
  5. tap on `Back` and tap in the same video to restart playback
  6. you'll notice that the audio will restart but the progress indicator/scrubber won't reset

Repeat `#5` once or twice to reproduce the issue.

**Actual result:** 

Example of issue occurring ---> https://youtu.be/rQESxomSZJo

**Expected result:**

Indicator/Scrubber should be restarted back to `0:00` when playback restarts.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

* `1.32.1 (21.10.25.13)`

**Device details:** 

* `iPhone 12` running on `iOS 15.0.2` while connected to a `CarPlay` device

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @srirambv @Brandon-T @anthonypkeane

**Comment by srirambv** [comment]
Repro'd the issue so problem exists with both wired and wireless carplay.


May also be related to #4160

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8 running 1.32.1(21.10.27.16)
- Verified steps from issue description
- Verified progress indicator resets to 0.00 when playback is restarted
- Encountered https://github.com/brave/brave-ios/issues/4421 
-------------
Verification passed on iPhone 7+ with iOS 14.8 running 1.32.1(21.10.27.16)
- Verified steps from issue description
- Verified progress indicator resets to 0.00 when playback is restarted
- Encountered https://github.com/brave/brave-ios/issues/4421
