### ISSUE TITLE
Reader mode heading missing

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#441]
### Description: 
Reader mode heading missing

### Steps to Reproduce 
  1. Open https://theverge.com/ and open an article
  2. Click on the URL bar reader mode option
  3. Shows up as `Aa`

**Actual result:** 
1.7(18.11.21.22)
![image](https://user-images.githubusercontent.com/17010094/49004784-13383900-f18b-11e8-9393-5eedefe037be.png)

1.6.6 appstore version
![image](https://user-images.githubusercontent.com/17010094/49004799-1c290a80-f18b-11e8-8f99-155268e810ea.png)

**Expected result:**
Similar to 1.6.6

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.11.21.22)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Looks like it's site specific bug, I tried it out and it works for me. I do not think anything has changed between 1.6 and 1.7 in regards of reader mode.

Does this happen on other websites/articles too?

**Comment by jhreis** [comment]
We are not currently going to change this behavior.

**Comment by jhreis** [comment]
@iccub that comment meant for #440 ?

**Comment by iccub** [comment]
I deleted and moved it :)
