### ISSUE TITLE
Not possible to play video on Twitter with autoplay video disabled

### ISSUE THREAD

**Issue by parsd51** [brave/brave-ios#4412]
### Description: 
Not possible to play video on Twitter with autoplay video disabled.
Prerequistite: Automatic video playback disabled.

### Steps to Reproduce 
  1. Open: https://twitter.com/rondevdrenthe?lang=da. No need to log-in.
  2. Scroll down to a video
  3.

**Actual result:** 
Rotationting circle in the middle of the video.
Video is not playing

**Expected result:**
Playbutton to start playback

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
1.32

**Device details:** 
Ipad Air 4, iPadOS 15.1

**Website problems only:**
- did you check with Brave Shields down? Same problem
- did you check in Safari/Firefox (WkWebView-based browsers)? I cannot find how to toggle autoplayback

### Additional Information
I have only seen this with Twitter. There are sites where it works fine.

**Comment by iccub** [comment]
let's close as stale, reopen if you still experience it
