### ISSUE TITLE
Reset stores upon wallet reset

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4413]
When we reset the wallet we should reset all of the stores that are held in `WalletStore` to ensure we get refreshed data

Currently if you reset the wallet and re-create a wallet without dismissing wallet at least once portfolio data isn't updated correctly such as the selected chain.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1  running 1.33(21.12.7.21)
- Verified changing network and resetting wallet and restarting over doesn't retain it
- Encountered [#4665](#4665) & [#4666](#4666)
-------
Verification passed on iPhone XR  with iOS 15.1 running 1.33(21.12.7.21) 
- Verified changing network and resetting wallet and restarting over doesn't retain it
-------
Verification passed on iPad Pro with iOS 14.8.1  running 1.33(21.12.7.21)
- Verified changing network and resetting wallet and restarting over doesn't retain it
