### ISSUE TITLE
Update Brave Wallet icon

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4418]
iOS is currently using the old crypto wallets icon, we should switch to the newer icon: 
<img width="91" alt="image" src="https://user-images.githubusercontent.com/529104/139278823-3f096ea4-c7f6-4fdd-9439-5d128ce6be24.png">

Located in Icons figma doc

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33(21.12.7.21)
- Verified wallet icon is updated on menu and in settings

Menu (Light) | Menu (Dark) | Setting (Light) | Setting (Dark)
-- | -- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/145211794-775c9b00-b32e-494b-93b8-9656378d2fb9.png) | ![image](https://user-images.githubusercontent.com/17010094/145211923-808fc275-0bd5-4178-b816-c5b1c38c8cc2.png) | ![image](https://user-images.githubusercontent.com/17010094/145211831-98267411-ecbc-4dca-a6b7-ebb78d788eb7.png) | ![image](https://user-images.githubusercontent.com/17010094/145211882-7146b545-0f57-4530-a1c7-2a10e9854642.png)

------------
Verification passed on iPhone XR with iOS 15.1 running 1.33(21.12.7.21)
- Verified wallet icon is updated on menu and in settings

Menu (Light) | Menu (Dark) | Setting (Light) | Setting (Dark)
-- | -- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/145212227-bb7ea3d1-26b3-4c03-9fa9-f6df4b7ad458.png) | ![image](https://user-images.githubusercontent.com/17010094/145212207-056c0bce-22be-4235-b98a-c4a8060ce5d8.png) | ![image](https://user-images.githubusercontent.com/17010094/145212244-3529c676-1649-4cbb-a788-2b2cc0d0521b.png) | ![image](https://user-images.githubusercontent.com/17010094/145212252-7bf740af-cc46-4a6b-b007-ed8f375aaace.png)

------------
Verification passed on iPad Pro with iOS 15.2 running 1.33(21.12.7.21)
- Verified wallet icon is updated on menu and in settings

Menu (Light) | Menu (Dark) | Setting (Light) | Setting (Dark)
-- | -- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/145212068-bd5ed363-28c1-421a-b56b-583bbf1ea16f.png) | ![image](https://user-images.githubusercontent.com/17010094/145212006-57d3d271-1791-47d8-9d19-e6f8ccc60a42.png) | ![image](https://user-images.githubusercontent.com/17010094/145212049-4ff4636f-74e0-4080-b580-766e20577ec9.png) | ![image](https://user-images.githubusercontent.com/17010094/145212028-a57b0ae3-28dd-49ec-bf27-5c9d605340e3.png)
