### ISSUE TITLE
Tabs bar scroll each time the app is launched into memory

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#442]
### Description: 
Tabs bar scroll each time the app is launched into memory

### Steps to Reproduce 
  1. Open about 20 tabs and visit pages 
  2. Keep tab 20 as active tab and remove app from memory
  3. Launch app again, see tabs bar scroll all the way till end to make the 20th tab active

**Actual result:** 
Tabs bar scroll each time the app is launched into memory

**Expected result:**
Shouldn't scroll instead set focus directly on the previous active tab

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.11.21.22)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
Related: https://github.com/brave/brave-ios/issues/736

**Comment by iccub** [comment]
same as https://github.com/brave/brave-ios/issues/736
