### ISSUE TITLE
Add option to enable biometric unlock when restoring wallet

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4420]
When you restore a wallet we currently dont give the user the option to enable biometric unlock, we should add that to match create wallet.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.33(21.12.7.21)
- Verified option to enable biometric unlock is shown for restoring a wallet

iPhone 7+ (iOS 14.8.1) | iPad Pro (iOS 15.2)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/145252664-ed6aa8be-f137-4c84-83d7-e157e2235fe9.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/145252677-829264c2-089d-468e-831a-81b1c5f22a88.png>
