### ISSUE TITLE
Transaction Details UI

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4425]
Tapping on a transaction should show full details about that transaction

Ref from figma (not final design): 
<img width="401" alt="image" src="https://user-images.githubusercontent.com/529104/139460290-7a190324-495c-4362-ab2c-ddd53416eee5.png">

**Comment by Uni-verse** [comment]
Verified using `1.38 (22.4.8.16)`

Devices: 

`iPhone 12` | `iOS 15.4`
`iPhone X` | `iOS 14.4.2`
`iPad (7th Gen)` | `iOS 15.2.1`


- Ensured tapping on transactions will display details
- Tapping `Done` will dismiss window
- Tapping on Transaction hash link will open block explorer

iPad | iPhone
-|-
![IMG_0252](https://user-images.githubusercontent.com/17885425/162806209-b204f9ab-fe78-4540-b27a-cf0bbcccc614.PNG) | ![IMG_2603](https://user-images.githubusercontent.com/17885425/162806250-59d38be2-49f4-4010-be59-278d169fcf5d.PNG)
