### ISSUE TITLE
Provide time out details for incorrect passcode lockdown

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#443]
### Description: 
Provide time out details for incorrect passcode lockdown

### Steps to Reproduce 
  1. Enable passcode
  2. Try resting passcode with 3 incorrect attempts
  3. Doesn't show how long you should wait before trying again

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/49008540-15eb5c00-f194-11e8-8cad-31390561b495.png)

**Expected result:**
Should inform user how much time to wait before trying to change passcode again

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.11.21.22)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
Once locked out doesn't allow you to login if you remove the app from memory and relaunch app is rendered useless

**Comment by kylehickinson** [comment]
Just realized we'll need new copy for this. What is it expected to say? "Please try again in 15m" ? (cc @anthonypkeane)

**Comment by anthonypkeane** [comment]
@kylehickinson pls defer this enhancement until after 1.7.0. We can pick it up then.

**Comment by srirambv** [comment]
Yeah it should be more like iOS time out message when you have unsuccessful unlock attempts

**Comment by kylehickinson** [comment]
@anthonypkeane Still need copy for this as per [above comment](https://github.com/brave/brave-ios/issues/443#issuecomment-442111852)

**Comment by anthonypkeane** [comment]
Brave is disabled
try again in **n** minutes

**Comment by kylehickinson** [comment]
@anthonypkeane  So no more "maximum attempts reached" ?

**Comment by anthonypkeane** [comment]
> @anthonypkeane So no more "maximum attempts reached" ?

@tomlowenthal can you please confirm the text change?

**Comment by tildelowengrimm** [comment]
> Too many failed attempts
> Try again in $TIME minutes

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.19.15)
* Verified text from #1976 
![image](https://user-images.githubusercontent.com/17010094/69171656-5ee5a000-0aca-11ea-8904-8c35dc309421.png)
![image](https://user-images.githubusercontent.com/17010094/69171668-63aa5400-0aca-11ea-845c-80c78bb04466.png)
---------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.19.15)
* Verified text from #1976 
![image](https://user-images.githubusercontent.com/17010094/69171627-51301a80-0aca-11ea-8123-dbf8467e56d0.png)
![image](https://user-images.githubusercontent.com/17010094/69171634-555c3800-0aca-11ea-985a-86c3f8f23ba9.png)
---------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.19.15)
* Verified text from #1976 
![image](https://user-images.githubusercontent.com/17010094/69171569-3cec1d80-0aca-11ea-8b86-fa2a3f540461.png)
![image](https://user-images.githubusercontent.com/17010094/69171578-41b0d180-0aca-11ea-9454-8045ce5d645b.png)
---------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.19.15)
* Verified text from #1976 
![image](https://user-images.githubusercontent.com/17010094/69172108-3e6a1580-0acb-11ea-968a-f97bbb07f9c6.png)
![image](https://user-images.githubusercontent.com/17010094/69172120-445ff680-0acb-11ea-82f2-db4913cee9bc.png)
---------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.19.15)
* Verified text from #1976 
![image](https://user-images.githubusercontent.com/17010094/69171592-470e1c00-0aca-11ea-9b92-715f742165c6.png)
![image](https://user-images.githubusercontent.com/17010094/69171981-f3e89900-0aca-11ea-91f0-656c6fdf8c33.png)

**Comment by anthonypkeane** [comment]
> > Too many failed attempts
> > Try again in $TIME minutes

There needs to be a line break after _attempts_  as per the comment from @tomlowenthal 
reopening ticket

**Comment by kylehickinson** [comment]
Let's open up a follow-up ticket and keep this ticket closed since it'll require re-verification and technically "new" translations.
