### ISSUE TITLE
Implement Privacy Hub feature.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4435]
See `Privacy Report` project in figma.

**Comment by srirambv** [comment]
<details>
<summary>Verification passed on iPhone XR with iOS 15.4.1 running 1.38 (22.4.29.16)/(22.5.4.18)</summary>
<br>

- Verified stats has a new label `Privacy Hub`

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/167080416-b949a5e0-461a-4177-93d9-3f488bc72e80.png) | ![image](https://user-images.githubusercontent.com/17010094/167080446-57be2aa7-e038-4577-9147-1d2828cffa28.png)

- Verified tapping on the stats opens up the privacy hub and shows stats

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/167080642-737fe6ca-50ef-40e8-98f7-69da1e6d0b04.png) | ![image](https://user-images.githubusercontent.com/17010094/167080658-183bfa76-0476-4c46-86ef-2d5aa111e34d.png)

- Verified there is a notification prompt shown on top of the privacy hub

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/167080642-737fe6ca-50ef-40e8-98f7-69da1e6d0b04.png) | ![image](https://user-images.githubusercontent.com/17010094/167080658-183bfa76-0476-4c46-86ef-2d5aa111e34d.png)

- Verified with notification prompt enabled, every Sunday at 11 AM there is a notification shown on lock screen
- Verified notification prompt is only shown when system notifications is enabled and `Show Shields Data` is enabled
   ![image](https://user-images.githubusercontent.com/17010094/167080153-2bb5e108-6639-46b7-935b-3f13b9f209d7.png)

- Verified when no sites are visited a message is shown to visit sites to start populating the stats in privacy hub
- Verified `Most frequent tracker & ad` shows the tracker that was found on the highest number of unique sites visited in that week 

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/167081140-641c9694-57bd-473c-83d5-42c8fd716c2e.png) | ![image](https://user-images.githubusercontent.com/17010094/167081128-45f4f081-87d0-49c3-af45-71c735b79e03.png)

- Verified Brave VPN alerts is only shown when VPN is enabled
- Verified `All time` section shows the most frequent tracker that is blocked and the website with the highest number of unique trackers captured
- Verified clicking on `All item lists` shows details of all the trackers blocked by both Shields and VPN and the websites with the total number of blocked items on each of them

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/167081015-13b47376-231b-4bf0-b04a-5ade3eb10898.png) | ![image](https://user-images.githubusercontent.com/17010094/167081023-518ede02-c56b-455b-a97e-c6eba117997d.png)
![image](https://user-images.githubusercontent.com/17010094/167081431-531ca5cf-b3d4-4a0e-879c-b28dd19eca08.png) | ![image](https://user-images.githubusercontent.com/17010094/167081356-ff99a414-3418-457a-a689-76d23a4bc5f0.png)

- Verified clicking on `All Alerts` lists `Trackers & Ads blocked`, `Location Pings` & `Email Trackers` blocked by VPN 

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/167080973-e6b5c943-3c43-46b1-bc97-72729c4206fc.png) | ![image](https://user-images.githubusercontent.com/17010094/167080963-7b4d47ff-c972-47e5-8a36-ce57a3940c83.png)

- Verified selecting `Consolidate data` on non-release build forces data consolidation and retains all time data and purges last 7 days data
- Verified onboarding message is shown when min trackers is crossed and the user has not manually opened the privacy hub
   ![image](https://user-images.githubusercontent.com/17010094/167081214-64bb176c-a1e6-4119-9ed6-43054eb263ee.png)

- Verified Shields settings has a new option `Privacy Hub` under `Manage Website Data`

Shields Settings | Privacy Hub Settings
-- | --
![image](https://user-images.githubusercontent.com/17010094/167081565-f46dff61-9131-43ca-9496-1d12cc5da1e0.png) | ![image](https://user-images.githubusercontent.com/17010094/167081598-ae99344c-6d2c-4b99-a6d8-90c9d6e63ff1.png)

- Verified able to clear shields data via the trash button on the privacy hub screen or via privacy hub settings

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/167081488-b41e2302-94a4-4077-a71c-e0e4c45502d3.png) | ![image](https://user-images.githubusercontent.com/17010094/167081513-5d3f6c45-fce1-4e76-bdd8-142febd80739.png)

- Logged [#5328](https://github.com/brave/brave-ios/issues/5328)
- Verified Shields data is stored after 1min of visiting the site and VPN alert is stored after 5 mins of usage

</details>

-----------
<details>
<summary>Verification passed on iPad Pro with iOS 15.5 Beta 3 running 1.38 (22.4.29.16)/(22.5.4.18)</summary>
<br>

- Verified stats has a new label `Privacy Hub`

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/167084642-06afc690-001d-4678-ab20-2984aa5ef26b.png) | ![image](https://user-images.githubusercontent.com/17010094/167084658-909a31dc-e4f8-40da-a5ac-d851e076baa8.png)

- Verified tapping on the stats opens up the privacy hub and shows stats

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/167110334-f9372253-0ed6-46e0-9140-7b5f931d8c4c.png) | ![image](https://user-images.githubusercontent.com/17010094/167110312-10efdc1f-f8e6-485b-88b2-a27696f8df5b.png)

- Verified there is a notification prompt shown on top of the privacy hub

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/167110377-59001af6-ba35-4139-ac36-2eddb73a1624.png) | ![image](https://user-images.githubusercontent.com/17010094/167110397-2f94f8de-6b36-47bc-bec4-4a17d4aa48ae.png)

- Verified with notification prompt enabled, every Sunday at 11 AM there is a notification shown on lock screen
- Verified notification prompt is only shown when system notifications is enabled and `Show Shields Data` is enabled

![image](https://user-images.githubusercontent.com/17010094/167085396-6a063cf5-b3dc-4a31-b7d8-afe9aa9af486.png) | 

- Verified when no sites are visited a message is shown to visit sites to start populating the stats in privacy hub
- Verified `Most frequent tracker & ad` shows the tracker that was found on the highest number of unique sites visited in that week 

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/167110334-f9372253-0ed6-46e0-9140-7b5f931d8c4c.png) | ![image](https://user-images.githubusercontent.com/17010094/167110312-10efdc1f-f8e6-485b-88b2-a27696f8df5b.png)

- Verified Brave VPN alerts is only shown when VPN is enabled
- Verified `All time` section shows the most frequent tracker that is blocked and the website with the highest number of unique trackers captured
- Verified clicking on `All item lists` shows details of all the trackers blocked by both Shields and VPN and the websites with the total number of blocked items on each of them

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/167085123-73056492-d9f7-48a3-9e98-f5dd01e67f63.png) | ![image](https://user-images.githubusercontent.com/17010094/167085103-a1bcd0de-bfbb-4ee9-a064-a6d1fa777b4a.png)

- Verified clicking on `All Alerts` lists `Trackers & Ads blocked`, `Location Pings` & `Email Trackers` blocked by VPN 

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/167085057-ed4b5d13-4132-4e9a-8e76-ca59a2abd986.png) | ![image](https://user-images.githubusercontent.com/17010094/167085074-8a7d1402-7a19-4904-bcfd-d6d4e9f93bac.png)

- Verified selecting `Consolidate data` on non-release build forces data consolidation and retains all time data and purges last 7 days data
- Verified onboarding message is shown when min trackers is crossed and the user has not manually opened the privacy hub

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/167085009-64177380-0bf3-4c51-85f7-212053bfd767.png) | ![image](https://user-images.githubusercontent.com/17010094/167085022-7c3a4965-8d66-4c97-b41d-2af08d48033a.png)

- Verified Shields settings has a new option `Privacy Hub` under `Manage Website Data`

Shields Settings | Privacy Hub Settings
-- | --
![image](https://user-images.githubusercontent.com/17010094/167110683-a681ef2c-5422-4d20-9fe8-e0307d6daf57.png) | ![image](https://user-images.githubusercontent.com/17010094/167110703-50d8e0fc-1dd7-4c54-a06b-875b98f94e4b.png)

- Verified able to clear shields data via the trash button on the privacy hub screen or via privacy hub settings

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/167110877-3e19fc50-c15b-4a03-857f-f43455adfb53.png) | ![image](https://user-images.githubusercontent.com/17010094/167110901-9c0aeead-ed2c-47e3-93ea-bccd4d619802.png)

- Encountered [#5328](https://github.com/brave/brave-ios/issues/5328)
- Verified Shields data is stored after 1min of visiting the site and VPN alert is stored after 5 mins of usage

</details>
