### ISSUE TITLE
Updated onboarding - Brave Search callouts for existing users

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4437]
See `Search Engine Default Promo (Mobile)` doc in shared drive.

**Comment by Uni-verse** [comment]
Verified using version `1.40 (22.6.24.14)` on `iPad (7th Gen)` running `iPadOS 15.5`

- Verified Test Plan in https://github.com/brave/brave-ios/pull/5432#issue-1258517750 and confirmed change in https://github.com/brave/brave-ios/pull/5562#issue-1280552035

New & Existing Users

- Confirmed users will be shown search callout upon installation.
- Confirmed `Brave Search Promotion Cell` will not be displayed if search engine set to `Brave`
- Confirmed changing search engine from `brave` to `google` or `bing` will display the cell
- Verified `Promotion Cell` is not shown in `private mode`
- Confirmed promotion cell is not displayed on first launch for new users. Relaunching the app will display the promotion cell. 

Brave search promotion cell button functionality

- Confirmed search query load will also add a query parameter `action=makeDefault` `https://search.brave.com/search?q=......&action=makeDefault` when users use the promotional cell search `Try Brave Search`
- Confirmed promotion cell has 2 states: `Maybe Later` & `Dismiss`.
- Confirmed when users taps `Maybe Later` in the promotional cell, this will change the state of the button to `Dismiss` next time it is shown to the user. 
- Confirmed tapping on `Dismiss` will hide the promotion and will not be displayed again in this app version.
- Verified font size is aligned for buttons in the promotional search cell. 

engine != brave | engine == brave | using promotion search | Dismissing promotion search cell
-|-|-|-
![IMG_0406](https://user-images.githubusercontent.com/17885425/175647794-f1216988-00e2-4fea-9f47-b219d353186e.PNG) | ![IMG_0405](https://user-images.githubusercontent.com/17885425/175647754-19d07eb1-eb2f-4c64-9b76-31e5ee76463f.PNG) | ![IMG_0407](https://user-images.githubusercontent.com/17885425/175647834-52e591b8-5f52-460b-b8ff-71a2087155c6.PNG) | ![IMG_0409](https://user-images.githubusercontent.com/17885425/175647866-a0533902-f8c9-462d-afcf-a5e6b2314fcd.PNG)

**Comment by Uni-verse** [comment]
Verified using version `1.40 (22.6.24.14)` on `iPhone 12 Pro` | `iOS 15.4` & `iPhone X` | `iOS 14.4.2`

- Verified Test Plan in https://github.com/brave/brave-ios/pull/5432#issue-1258517750 and confirmed change in https://github.com/brave/brave-ios/pull/5562#issue-1280552035

New & Existing Users

- Confirmed users will be shown search callout upon installation.
- Confirmed `Brave Search Promotion Cell` will not be displayed if search engine set to `Brave`
- Confirmed changing search engine from `brave` to `google` or `bing` will display the cell
- Verified `Promotion Cell` is not shown in `private mode`
- Confirmed promotion cell is not displayed on first launch for new users. Relaunching the app will display the promotion cell. 

Brave search promotion cell button functionality

- Confirmed search query load will also add a query parameter `action=makeDefault` `https://search.brave.com/search?q=......&action=makeDefault` when users use the promotional cell search `Try Brave Search`
- Confirmed promotion cell has 2 states: `Maybe Later` & `Dismiss`.
- Confirmed when users taps `Maybe Later` in the promotional cell, this will change the state of the button to `Dismiss` next time it is shown to the user. 
- Confirmed tapping on `Dismiss` will hide the promotion and will not be displayed again in this app version.
- Verified font size is aligned for buttons in the promotional search cell. 

engine != brave | query params
-|-
![IMG_3147 2](https://user-images.githubusercontent.com/17885425/175652693-a169163c-4fd0-49fb-ae73-f536d9fa5aa7.PNG) | ![IMG_3146](https://user-images.githubusercontent.com/17885425/175653035-dbd13a3b-4c35-4e1e-9df3-23943222af8a.PNG)
