### ISSUE TITLE
Downloads improvements

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4438]
We want to achieve the same result as chrome-iOS.
When you open downloads it will open Files.app in 'downloads' location.

**Comment by Uni-verse** [comment]
Verification completed on the following devices using build version `1.35 (22.1.21.14)`

**PASSED** on `iPhone 12 Pro` running `iOS 15.1.1`
**PASSED** on `iPad (7th Gen)` running `14.4.2`

- Verified when you open downloads it will open Files.app in 'downloads' location.

https://user-images.githubusercontent.com/17885425/150605053-17954b93-cdb9-4a2c-9ecc-7b5d1eeba0cf.MP4
