### ISSUE TITLE
Transaction Confirmation UI

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#4444]
Once unapproved transaction is successfully sent, a transaction confirmation sheet should show up in order to let user to proceed the send-transaction.

Ref from figma:
![Screenshot 2021-11-01 at 10 33 01 AM](https://user-images.githubusercontent.com/1187676/139688481-4a7925fd-cfa3-49b5-82eb-c3c956c7bbe9.png)

**Comment by kylehickinson** [comment]
Superseded by #4445
