### ISSUE TITLE
Integrate Brave Wallet Transaction Confirmation UI with API

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#4445]
Integrate the wallet transaction confirmation screen with `approveTransaction` API

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33 (21.12.9.23)
- Verified transaction confirmation UI is shown for both Send/Swap 
- Verified able to switch between Low/Optimal(default)/High presets
- Verified able to set custom price for the transaction as well
- Verified transaction confirmation screen is shown for both send and swap 

Confirmation Screen | Default settings | Custom pricing
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/145538423-45210c95-168c-4d55-866d-6ffa3d04d5fa.png) | ![image](https://user-images.githubusercontent.com/17010094/145538462-7fe92107-99d6-413d-940e-a951fbfb8f9d.png) | ![image](https://user-images.githubusercontent.com/17010094/145538524-f3a89543-8e50-4671-b51f-86d640e4d8e4.png)


--------
Verification passed on iPhone XR with iOS 15.1 running 1.33 (21.12.9.23)
- Verified transaction confirmation UI is shown for both Send/Swap 
- Verified able to switch between Low/Optimal(default)/High presets
- Verified able to set custom price for the transaction as well
- Verified transaction confirmation screen is shown for both send and swap 

Confirmation Screen | Default settings | Custom pricing
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/145539275-2b6097c8-6e6d-49b8-9319-9309a3e3cb05.png) | ![image](https://user-images.githubusercontent.com/17010094/145539287-ee92bee6-b9a2-4c2f-870f-29d1d5da76dd.png) | ![image](https://user-images.githubusercontent.com/17010094/145539297-238b9c0e-ad73-47fa-a2b3-975c9ca8ebf3.png)

--------
Verification passed on iPad Pro with iOS 15.2 running 1.33 (21.12.9.23)
- Verified transaction confirmation UI is shown for both Send/Swap 
- Verified able to switch between Low/Optimal(default)/High presets
- Verified able to set custom price for the transaction as well
- Verified transaction confirmation screen is shown for both send and swap 

Confirmation Screen | Default settings | Custom pricing
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/145539181-e0476928-57c8-4146-9cc8-af98c92e68e5.png) | ![image](https://user-images.githubusercontent.com/17010094/145539197-f0687b2b-a17c-4d56-9241-de498519a021.png) | ![image](https://user-images.githubusercontent.com/17010094/145539236-335d3c98-a2b9-413b-8f0d-547ff5107f3f.png)
