### ISSUE TITLE
Updated onboarding - Shields education revamp- Animation

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#4450]
Add animation to Shields education.

The white highlight circles pulsate continuously, even while popping is showing; this will  be same animation as the Shields intro message.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPad 7th Generation version iOS 15.1` running `Brave version 1.33 (21.12.7.21)`

- Confirmed that white highlight circles pulsate continuously, even while popping is showing 
- Shield intro detailed testing is done in Case 3, 4 in  https://github.com/brave/brave-ios/issues/4372#issuecomment-984465058

https://user-images.githubusercontent.com/38657976/145205371-9d91cb61-4a54-4275-9abb-86dd0adc3804.MP4
