### ISSUE TITLE
Closing Browser on NTP should not focus on First Tab

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#4455]
### Description: 

When user kills application in any tab and it is not NTP, the relaunch works properly and focuses last opened tab.

However when we left user in NTP, it opens first tab. This is very confusing for user especially with users lots of tabs open.
We should change this behaviour from first-tab to last tab.

### Steps to Reproduce 
  1. Open Browser and NTP
  2. Close App
  3. Check First tab is focused

**Actual result:** 

First tab is focused

**Expected result:**

Last tab or last visited tab should be focused

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.32.5(21..11.2.16)

**Device details:** 
All Devices

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA 

### Additional Information

https://user-images.githubusercontent.com/6643505/139932056-5334bba9-2ba0-47d1-b2da-46931dc08ffa.MP4

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPad 7th Generation version iOS 15.1` running `Brave version 1.33 (21.12.10.17)

----------------------

Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.33 (21.12.10.20)`

* Also ensured that upgrading from `1.32.3` -> `1.33` selects the last opened tab

----------------------

Verification **PASSED** on `iPhone 6+` running `iOS 14.6` using `1.33 (21.12.10.20)`

* Also ensured that upgrading from `1.32.3` -> `1.33` selects the last opened tab
