### ISSUE TITLE
Brave Wallet iOS 14 audit and fixes

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4461]
There are a number of SwiftUI-related bugs when running in iOS 14.  We should do a 14 audit along with the [accessibility audit](#4303) to fix up anything missed.

## Known Bugs on iOS 14:

- <details><summary>Settings padding is too large and footer lacks padding</summary> <img width="390px" src="https://user-images.githubusercontent.com/529104/140187006-931ae750-70a4-48d1-bca9-30400e42adf8.png" /></details>
- <details><summary>Navigation link highlight remains visible (Related to brave/brave-browser#36880) </summary> <img width="390px" src="https://user-images.githubusercontent.com/529104/140187265-170ddaba-80cb-4a3c-bf0b-16f8a5b954ad.png" /></details>
- <details><summary>Account picker context menu is broken and has white background</summary> <img width="390px" src="https://user-images.githubusercontent.com/529104/140187567-bfaaf1d9-42e0-4b94-aad6-ab8453cab36c.png" /></details>
- <details><summary>Missing placeholder on search bars</summary> <img width="390px" src="https://user-images.githubusercontent.com/529104/140187652-e5a6f900-8227-48db-a632-1968256aa6c5.png" /></details>

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33(21.12.7.21)

<details>
<summary>Settings and footer padding looks fixed</summary>

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/145215081-f451f248-0e43-40f3-bea1-44c01e742d2e.png) | ![image](https://user-images.githubusercontent.com/17010094/145215071-18628428-4285-4cfd-a551-d1fb3c587b97.png)

</details>
<details>
<summary>Navigation link highlight doesn't remain visible</summary>

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/145215057-6175fa33-3fef-4853-ada2-ee015b5f93b1.png) | ![image](https://user-images.githubusercontent.com/17010094/145215026-bc542103-9c98-4842-abd6-1f4da946a723.png)

</details>
<details>
<summary>Account picker context menu doesn't have a white background</summary>

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/145214898-bae92f5d-4453-4fad-a12b-6738d4407741.png) | ![image](https://user-images.githubusercontent.com/17010094/145214886-ce7bf91f-ce2b-4a03-8fa3-d5105abb27e1.png)

</details>
<details>
<summary>Search bar has placeholder text</summary>

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/145214935-4edffa4a-31c2-4f34-8b80-1206be979418.png) | ![image](https://user-images.githubusercontent.com/17010094/145214918-d467e022-690f-46f1-ba41-44c7e9f0b0bf.png)


</details>
