### ISSUE TITLE
New Tab Page shows Local as title causing  `L`to show up on tab tray preview

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4462]
### Description: 
New Tab Page shows Local as title causing  `L`to show up on tab tray preview

### Steps to Reproduce 
  1. Install 1.32.5
  2. Open a new tab and open menu
  3. Open tab tray

**Actual result:** 

![image](https://user-images.githubusercontent.com/17010094/140255667-56881390-71ff-402b-abd2-03512cba0d49.png) | ![image](https://user-images.githubusercontent.com/17010094/140255683-b0068db9-b6e9-458f-bd4c-8bf5cf705bb7.png)
-- | --

**Expected result:**
Should not show as local or show `L` in tab tray view

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.32.5

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by stephendonner** [comment]
Verified `PASSED` using `1.32.5 (21.11.10.19)` on an iPhone 6s running iOS 15.0.2.  Reproduced with a `beta` build.

`beta` | normal tabs | private tabs
-------|--------|---------
![Image from iOS](https://user-images.githubusercontent.com/387249/142046851-553d9770-186c-4c08-9ae4-51b45ddabf8b.png) | ![Image from iOS (2)](https://user-images.githubusercontent.com/387249/142046899-52281c42-1bfe-46bb-81d8-a109a600e62b.png) | ![Image from iOS (1)](https://user-images.githubusercontent.com/387249/142047141-80f087f2-41b4-4f06-8415-f96e95e698bc.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air 3` running `iOS 15.1` using the following build:

```
1.32.3 (21.11.13.9)
```
* verified the STR/Cases outlined via https://github.com/brave/brave-ios/issues/4462#issue-1044339247 and ensured that `L` wasn't appearing on NTP when viewing them via the tab tray as per the original issue.

**`Normal mode`** | **`PB mode`**
---------------------|------------------
![image](https://user-images.githubusercontent.com/2602313/142048129-86e69ba6-b55a-462e-bf5f-3f46f8486f03.png) | ![image](https://user-images.githubusercontent.com/2602313/142051027-8c5e1a59-67d9-4907-909b-be5a52a5aa66.png)

-------

Verification **PASSED** on `iPhone 6s+` running `iOS 14.6` using the following build:

```
1.32.3 (21.11.13.9)
```

* verified the STR/Cases outlined via https://github.com/brave/brave-ios/issues/4462#issue-1044339247 and ensured that `L` wasn't appearing on NTP when viewing them via the tab tray as per the original issue.

**`Normal mode`** | **`PB mode`**
---------------------|------------------
![image](https://user-images.githubusercontent.com/2602313/142049440-baaff1af-7790-4017-83ab-296632589881.png) | ![image](https://user-images.githubusercontent.com/2602313/142050775-d3a1b3a7-e52c-4836-8d13-7c16161df237.png)

**Comment by stephendonner** [comment]
Verified `PASSED` using `1.32.3 (21.11.13.9)` on an iPhone 6s running iOS 15.0.2.  Reproduced with a `beta` build.

`beta` | normal tabs | private tabs
-------|--------|---------
![Image from iOS](https://user-images.githubusercontent.com/387249/142046851-553d9770-186c-4c08-9ae4-51b45ddabf8b.png) | ![Image from iOS](https://user-images.githubusercontent.com/387249/142049934-b914a4fd-c512-47a7-bd44-85d3cb5bdecb.png) | ![Image from iOS (1)](https://user-images.githubusercontent.com/387249/142049956-7c73a779-9951-48ef-af68-a99ea0f4b465.png)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.0.1 running 1.32.3 (21.11.13.9)
- Verified steps from issue description
- Verified no share sheet is show in menu when opened on new tab
- Verified no tab title is shown on tab tray view
- Verified no tab title is shown on menu 

Tab Tray (Normal tab) | Tab Tray (Private tab) | Menu (Normal tab) | Menu (Private tab)
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/142128980-530181d1-884d-4f7c-9904-e7fdcc77a112.png) | ![image](https://user-images.githubusercontent.com/17010094/142128986-be2fcfbc-e17a-4f66-a4eb-5d9158b0ca8c.png) | ![image](https://user-images.githubusercontent.com/17010094/142128999-cd1d96ea-9cc6-46e9-97a1-0f7f0e99975f.png) | ![image](https://user-images.githubusercontent.com/17010094/142128991-a58bafb3-5d53-427c-ae9e-44fbd3e10554.png)
