### ISSUE TITLE
Browser crash when trying to reorder favourites

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4463]
### Description: 
Browser crash when trying to reorder favourites

### Steps to Reproduce 
  1. Install 1.32.5 (21.11.2.23)
  2. Close default browser modal and enable/hide search history (optional steps)
  3. Long press and drag favourite, browser crashes
  4. Focus URL bar and drag and drop, browser crashes

**Actual result:** 

https://user-images.githubusercontent.com/17010094/140313573-e0e27851-b0ce-4e4f-a110-31892fa43492.MP4

**Expected result:**
No crash just reorder favourites

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.32.5(21.11.2.23)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
Found while testing #3713

**Comment by kjozwiak** [comment]
Went through the following STR/Cases on the devices/iOS versions mentioned below:

* verified the STR/Cases outlined via https://github.com/brave/brave-ios/issues/4463#issue-1044715498
* verified the STR/Cases outlined via https://github.com/brave/brave-ios/pull/4469#issue-1044948903
* ensured that you can re-order `Favourites` within NTP without any issues
* ensured that you can re-order `Favourites` while viewing them by tapping on `Show More`
* ensured that you can add new `Favourites` and they're visible via NTP if there's less than four already set
* ensured that you can add new `Favourites` and they're added under `Show More` when there's already four under NTP
* ensured that `Open in New Tab` & `Open in New Private Tab` worked as expected when long tapping icons
* ensured that you can `Remove Favorite` without issues
* ensured that you can `Edit Bookmark` without issues
* ensured that removing all of the `Favourites` didn't cause any issues/crashes (known issue in the past)
* ensured that the above cases also work under `Private Browsing`

Devices/iOS versions used for the above STR/Cases:

* Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.33 (21.12.6.21)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.1` using `1.33 (21.12.7.21)`

**Comment by kjozwiak** [comment]
Found https://github.com/brave/brave-ios/issues/4651 while running through the above and will need to be tested on `iOS 14` once https://github.com/brave/brave-ios/issues/4651 has been resolved/fixed.

**Comment by kjozwiak** [comment]
As per above, `iOS 14` will be checked/tested via https://github.com/brave/brave-ios/issues/4651. As per @soner-yuksel, the iOS team is looking into fixing the issue which is more challenging. Worst case, moving `Favorites` under the NTP will be disabled on `iOS 14` if a solution can't be found in time for `1.33.x`.
