### ISSUE TITLE
Nested bookmarks are not removed from sync

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#447]
### Steps to Reproduce 
  1. Create a folder and add few bookmarks there.
  2. Remove the folder
  3. Join another device to sync group

**Actual result:** 
Bookmarks from the previously deleted folder are shown on the new device

**Comment by btlechowski** [comment]
* Verified passed with 1.9 (19.3.9.1) on iPhone SE using the test plan from description.
* Verified passed with 1.9 (19.3.9.1) on iPad 5th Gen using STR above
* Verified passed with 1.9 (19.3.9.1) on iPhone 8 using STR above
* Verification passed on iPhone 7+/6 and iPad Pro running 1.9(19.3.9.1)
* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR.
