### ISSUE TITLE
Sync UX Hotfix - Codewords Alert Popup

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-ios#4470]
See details at https://github.com/brave/internal/issues/824

**Comment by kjozwiak** [comment]
Verification **PASSED** on the following devices/builds:

* `iPhone` running `iOS 15.0.2` using `1.32.2 (21.11.4.20)`
* `iPad 5th Gen` running `iOS 14` using `1.32.2(21.11.4.20)`
*  `iPad 5th Gen` running `iOS 15` using `1.32.2(21.11.4.20)`

QA verification notes can be found via https://github.com/brave/internal/issues/824#issuecomment-962128671. @LaurenWags @stephendonner thanks for running through the verifications 👍

**Comment by soner-yuksel** [comment]
Opened this ticket again, because it is removed with https://github.com/brave/brave-browser/issues/19670 but this is causing incompatibility with Android right now.

So it has to be added back until https://github.com/brave/brave-browser/issues/19670 is address on Android side.

**Comment by soner-yuksel** [comment]
Closing this because the new conditions will be addressed with https://github.com/brave/brave-ios/issues/7887
