### ISSUE TITLE
Deprecate Yubico sdk in favor of built-in webauth of WKWebView

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4473]
WebAuth added most of webauth items we need, and maintaining this sdk might not be worth anymore.

Remove yubico sdk and corresponding webauth javascript files.
To verify and check what is supported by webkit what not, you can use the google doc from this ticket
https://github.com/brave/security/issues/649

**Comment by kjozwiak** [comment]
Adding missing `QA/Yes` label as QA will need to run through this as it's a large change.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 14.7.1` using `1.35 (22.2.4.17)`

### `Test Case 1 - using https://demo.yubico.com/webauthn-technical/registration`

* ensured tapping on `Cancel` dismisses the WebAuthn modal
* ensured that clicking on `Retry` re-displays the WebAuthn modal after being dismissed via `Cancel`
* ensured that clicking on `Use Security Key` takes you to the `Insert and activate your security key, or bring it near the top of your iPhone` modal
* ensured that the `Password` WebAuthn modal is displayed if the YubiKey is protected by a password
* ensured that inserting an incorrect password if the YubiKey is protected doesn't crash Brave
* ensured that removing/inserting the YubiKey several times didn't crash Brave
* ensured that clicking on `Continue` loads the modal requesting that the website used `Face ID`
* ensured that the user has a selection re: using `Face ID` or the `Security Key` if `Face ID` was used as the initial selection/choice

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|
![image](https://user-images.githubusercontent.com/2602313/152937501-99d832d2-665e-4320-b4bf-20010acb2634.png) | ![image](https://user-images.githubusercontent.com/2602313/152937546-216fad1a-de56-467c-9ea7-4fe207f6b5a3.png) | ![image](https://user-images.githubusercontent.com/2602313/152937588-c754e7e3-0bc2-4eb0-8499-dd936de6e93b.png) | ![image](https://user-images.githubusercontent.com/2602313/152937632-972a4094-7ca7-464d-958d-34b4369b2401.png) | ![image](https://user-images.githubusercontent.com/2602313/152937688-619388c9-6bdd-4dde-86ae-2d1ee55680e8.png) | ![image](https://user-images.githubusercontent.com/2602313/152937738-791fead7-0480-47d2-908a-78a3246aad44.png) | ![image](https://user-images.githubusercontent.com/2602313/152937783-b9726774-505a-41a8-a48b-d390fda4e26f.png) | ![image](https://user-images.githubusercontent.com/2602313/152937842-eb82b59b-afa3-40cd-9b3a-b4de224304f8.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|
![image](https://user-images.githubusercontent.com/2602313/152938038-d63a1883-e241-44f7-9cd6-605396fe79cf.png) | ![image](https://user-images.githubusercontent.com/2602313/152938069-718467a5-1486-4e87-8688-90d10b2adefc.png) | ![image](https://user-images.githubusercontent.com/2602313/152938096-bc162a78-e99a-4b01-b605-eb8c0cdf1d24.png) | ![image](https://user-images.githubusercontent.com/2602313/152938117-33998873-da1b-4951-9e5d-7dc3dd108323.png) | ![image](https://user-images.githubusercontent.com/2602313/152938157-95522a73-9e21-43e3-b6d4-f5c7564c6d33.png) | ![image](https://user-images.githubusercontent.com/2602313/152938185-dc5da496-45b6-49b8-9823-6fea0ecd4300.png) | ![image](https://user-images.githubusercontent.com/2602313/152938235-e2bd09d3-5911-4892-aa61-d94e6f33c9aa.png) | ![image](https://user-images.githubusercontent.com/2602313/152938299-48ecaac9-f705-46f0-a80d-662299cf3c4f.png) | ![image](https://user-images.githubusercontent.com/2602313/152938501-4e1dc089-0066-4d48-9300-ef6a7114a8e7.png)

Also ensured that NFC `Yubikeys` are working as per the following:

![image](https://user-images.githubusercontent.com/2602313/153074724-2c31d548-4504-4ee0-9755-a07726683585.png)

### `Test Case 2 - GitHub`

* ensured that you can add a YubiKey into GH and authenticate/log into GH without any issues
* ensured that you can use `Face ID` as a key and authenticate/log into GH without any issues
* ensured that both YubiKey & `Face ID` are being displayed in the modal when `Face ID` is added as an authentication method
* ensured that `For this website` entry is removed from the modal if `Face ID` is removed as an authenticator via GH
* ensured that `Found no credentials on this device is displayed` if user attempts to authenticate using a key that was removed
* ensured that passwordless authentication works as expected

![image](https://user-images.githubusercontent.com/2602313/153074773-d9badfec-1307-4e36-89c5-80a3bac02b8f.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**| **`Example`** | **`Example`**|
----------------|----------------|----------------|----------------|---------------|-----------------|----------------
![image](https://user-images.githubusercontent.com/2602313/152942757-6ac2ac39-f7a3-4114-a7da-4fdfdda02191.png) | ![image](https://user-images.githubusercontent.com/2602313/152942810-be1f68e4-f5dd-433e-a933-2a7e8fde3c1d.png) | ![image](https://user-images.githubusercontent.com/2602313/152942850-f38ca949-3c68-4c2a-af22-b7541903f2e1.png) | ![image](https://user-images.githubusercontent.com/2602313/152942880-71625a2c-e2ba-4517-adb2-2c28c72f5ffe.png) | ![image](https://user-images.githubusercontent.com/2602313/152942920-5795b956-b1f4-40fe-b01e-2fd80c221035.png) | ![image](https://user-images.githubusercontent.com/2602313/152942941-ad903c5c-e9c9-4dc7-8f4e-1a0afa76e0ef.png) | ![image](https://user-images.githubusercontent.com/2602313/152942982-1366827b-6b24-45bc-8702-afc08831ce9f.png)

### `Test Case 3 - https://webauthn.io`

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**| **`Example`** 
----------------|----------------|----------------|----------------|---------------|----------------
![image](https://user-images.githubusercontent.com/2602313/153073157-f546eaf0-e7de-4da0-95e3-48884310c5f8.png) | ![image](https://user-images.githubusercontent.com/2602313/153073194-fe50e3c4-3b54-4044-804d-1766ac7ef49e.png) | ![image](https://user-images.githubusercontent.com/2602313/153073230-05120965-8545-4458-ba8c-83a991d9df6d.png) | ![image](https://user-images.githubusercontent.com/2602313/153073262-605ee75d-842b-49ec-a3bf-68caf2665f9a.png) | ![image](https://user-images.githubusercontent.com/2602313/153073308-747e01b8-bd99-4bc9-b0c5-26f7d1bebe3d.png) | ![image](https://user-images.githubusercontent.com/2602313/153073328-af611020-c8d0-45bf-8780-fe90f624a79d.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 12` running `iOS 15.3` using `1.35 (22.2.4.17)`

### `Test Case 1 - using https://demo.yubico.com/webauthn-technical/registration`

* ensured tapping on `Cancel` dismisses the WebAuthn modal
* ensured that clicking on `Retry` re-displays the WebAuthn modal after being dismissed via `Cancel`
* ensured that clicking on `Use Security Key` takes you to the `Insert and activate your security key, or bring it near the top of your iPhone` modal
* ensured that the `Password` WebAuthn modal is displayed if the YubiKey is protected by a password
* ensured that inserting an incorrect password if the YubiKey is protected doesn't crash Brave
* ensured that removing/inserting the YubiKey several times didn't crash Brave
* ensured that clicking on `Continue` loads the modal requesting that the website used `Face ID`
* ensured that the user has a selection re: using `Face ID` or the `Security Key` if `Face ID` was used as the initial selection/choice

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|
![image](https://user-images.githubusercontent.com/2602313/153076850-cad05e14-f7c9-4f73-a517-bf9b6ef687f1.png) | ![image](https://user-images.githubusercontent.com/2602313/153076888-3bd7fbd8-3d1e-4584-adf0-36eed33b0b9b.png) | ![image](https://user-images.githubusercontent.com/2602313/153076918-faf2c3e4-b1ed-4262-8bc8-2b769115eded.png) | ![image](https://user-images.githubusercontent.com/2602313/153076956-d51a34a6-4550-4740-846e-100dddd6649a.png) | ![image](https://user-images.githubusercontent.com/2602313/153076997-2ae1270d-3158-41d5-8183-010804704c14.png) | ![image](https://user-images.githubusercontent.com/2602313/153077032-cda3e37c-c34b-433c-a45e-17a16088c6e2.png) | ![image](https://user-images.githubusercontent.com/2602313/153077071-31ac9567-688a-4017-a365-6a63840eeba8.png) | ![image](https://user-images.githubusercontent.com/2602313/153077112-bf220598-d114-41b2-8329-a301965308c1.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** 
----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------
![image](https://user-images.githubusercontent.com/2602313/153078650-9ad13d7d-1172-4439-bc78-8c75657333d3.png) | ![image](https://user-images.githubusercontent.com/2602313/153078691-12ca2208-1292-4735-9ed0-861b29964126.png) | ![image](https://user-images.githubusercontent.com/2602313/153078743-e41ab6ab-d62f-4743-a973-0881bfb3f105.png) | ![image](https://user-images.githubusercontent.com/2602313/153078776-8a8cc4c1-3d8e-4e06-a5ff-8b61ba704465.png) | ![image](https://user-images.githubusercontent.com/2602313/153078907-ea0034dc-0e16-4088-8ade-2bc80fd9e928.png) | ![image](https://user-images.githubusercontent.com/2602313/153078936-dbab4a62-5b4e-4346-a522-7f5d504321ae.png) | ![image](https://user-images.githubusercontent.com/2602313/153078988-02728a5b-00a2-44ea-896a-8f5d2f89a7a7.png) | ![image](https://user-images.githubusercontent.com/2602313/153079046-a044b9ed-cf7a-4f5e-bc72-9c6a2aa5f9ef.png) | ![image](https://user-images.githubusercontent.com/2602313/153079112-c66f67c6-df63-4787-b31c-7a2ccbf617d6.png)

### `Test Case 2 - GitHub`

* ensured that you can add a YubiKey into GH and authenticate/log into GH without any issues
* ensured that you can use `Face ID` as a key and authenticate/log into GH without any issues
* ensured that both YubiKey & `Face ID` are being displayed in the modal when `Face ID` is added as an authentication method
* ensured that `For this website` entry is removed from the modal if `Face ID` is removed as an authenticator via GH
* ensured that `Found no credentials on this device is displayed` if user attempts to authenticate using a key that was removed
* ensured that passwordless authentication works as expected

![image](https://user-images.githubusercontent.com/2602313/153080834-da801bd2-f65c-4ff3-a199-58b41234ce28.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|---------------
![image](https://user-images.githubusercontent.com/2602313/153080652-10374e1d-3e17-458a-9f46-2ea7a15de42a.png) | ![image](https://user-images.githubusercontent.com/2602313/153080669-32ea547c-7dcb-4cdd-a201-ecf96c3226a6.png) | ![image](https://user-images.githubusercontent.com/2602313/153080722-2a849b46-3e10-4e0e-8f74-96beab220643.png) | ![image](https://user-images.githubusercontent.com/2602313/153080759-6403e50e-bfb1-481e-b59f-7a88c12c9f8b.png) | ![image](https://user-images.githubusercontent.com/2602313/153080788-408be04e-cdf2-4671-aaec-b8b5d94844d3.png)

### `Test Case 3 - https://webauthn.io`

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|----------------|---------------
![image](https://user-images.githubusercontent.com/2602313/153082097-37dd0719-687e-4358-be24-b88af7bb4037.png) | ![image](https://user-images.githubusercontent.com/2602313/153082122-ff46cd6f-5272-44da-be47-9bd52c644d97.png) | ![image](https://user-images.githubusercontent.com/2602313/153082154-09758c4b-0238-4b90-9c04-41353aba7028.png) | ![image](https://user-images.githubusercontent.com/2602313/153082187-672cd2ad-98c9-421c-8975-7c82ea87ef67.png) | ![image](https://user-images.githubusercontent.com/2602313/153082213-56ed6691-588a-40b6-9da5-66c1145fa90a.png) | ![image](https://user-images.githubusercontent.com/2602313/153082277-0a0d3c33-4709-44ac-8264-7ea2d421f2e6.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|----------------|----------------|----------------|---------------
![image](https://user-images.githubusercontent.com/2602313/153082334-42fc296e-57eb-41c1-bfa9-e1eec8d548a9.png) | ![image](https://user-images.githubusercontent.com/2602313/153082380-6b126c34-bb6f-43e6-b619-c2a664672d82.png) | ![image](https://user-images.githubusercontent.com/2602313/153082403-037bb43a-0789-4a8e-ab3a-728e55f9953f.png) | ![image](https://user-images.githubusercontent.com/2602313/153082440-732bcf0d-1d11-4ce6-bf51-66cb92c9a934.png) | ![image](https://user-images.githubusercontent.com/2602313/153082475-32e06575-2146-4083-8b0e-a9341adbdf20.png) | ![image](https://user-images.githubusercontent.com/2602313/153082502-4ec98af2-faa2-430a-a1f9-a0d1e2924e4c.png) | ![image](https://user-images.githubusercontent.com/2602313/153082524-d2467b84-bb2d-4373-807a-7cf45d83ecbb.png) | ![image](https://user-images.githubusercontent.com/2602313/153082576-c8918679-011c-4485-a9dd-c3defc8cde10.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.3` using `1.35 (22.2.4.17)`

### `Test Case 1 - using https://demo.yubico.com/webauthn-technical/registration`

* ensured tapping on `Cancel` dismisses the WebAuthn modal
* ensured that clicking on `Retry` re-displays the WebAuthn modal after being dismissed via `Cancel`
* ensured that clicking on `Use Security Key` takes you to the `Insert and activate your security key, or bring it near the top of your iPhone` modal
* ensured that the `Password` WebAuthn modal is displayed if the YubiKey is protected by a password
* ensured that inserting an incorrect password if the YubiKey is protected doesn't crash Brave
* ensured that removing/inserting the YubiKey several times didn't crash Brave
* ensured that clicking on `Continue` loads the modal requesting that the website used `Face ID`
* ensured that the user has a selection re: using `Face ID` or the `Security Key` if `Face ID` was used as the initial selection/choice
* ensured that passwordless authentication works as expected

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|
![image](https://user-images.githubusercontent.com/2602313/153103564-fabd2faf-ef05-4381-9b58-82dca80ee8d7.png) | ![image](https://user-images.githubusercontent.com/2602313/153103585-85745eff-946c-4fac-aaec-9350f4820404.png) | ![image](https://user-images.githubusercontent.com/2602313/153103613-2cef917e-a41d-44db-9e17-f6b1c225cb65.png) | ![image](https://user-images.githubusercontent.com/2602313/153103645-524998c5-220f-49e5-85af-b0014e46981c.png) | ![image](https://user-images.githubusercontent.com/2602313/153103668-90ee8861-76ef-4fde-938b-f021c4acfe30.png) | ![image](https://user-images.githubusercontent.com/2602313/153103694-752610f6-bc5e-4060-b399-a58035e629ed.png) | ![image](https://user-images.githubusercontent.com/2602313/153103711-cca2370d-507f-4ba0-8b0b-2e8f02740202.png) | ![image](https://user-images.githubusercontent.com/2602313/153103734-405df977-5318-452a-bbd9-1b21aeb50e83.png)


**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------
![image](https://user-images.githubusercontent.com/2602313/153104057-93582991-9082-4d2c-a33d-38d544f539c6.png) | ![image](https://user-images.githubusercontent.com/2602313/153104074-862268ec-63a3-4225-a575-c03324be8aab.png) | ![image](https://user-images.githubusercontent.com/2602313/153104100-3e39bfab-87cd-4ea0-b53e-acc3d695d586.png) | ![image](https://user-images.githubusercontent.com/2602313/153104136-f5ff3a38-0bc3-4b4a-97c6-e00d8b7b35a8.png) | ![image](https://user-images.githubusercontent.com/2602313/153104154-a101852e-47d8-4bdb-b28e-de3f67d59666.png) | ![image](https://user-images.githubusercontent.com/2602313/153104178-31dc08fa-6c6c-4705-8336-a57d555bf046.png) | ![image](https://user-images.githubusercontent.com/2602313/153104240-b7658509-140c-44be-8da3-198812d92b1c.png) | ![image](https://user-images.githubusercontent.com/2602313/153104268-9419946e-6fa8-4864-aa39-a452b1688cb0.png)

### `Test Case 2 - GitHub`

* ensured that you can add a YubiKey into GH and authenticate/log into GH without any issues
* ensured that you can use `Face ID` as a key and authenticate/log into GH without any issues
* ensured that both YubiKey & `Face ID` are being displayed in the modal when `Face ID` is added as an authentication method
* ensured that `For this website` entry is removed from the modal if `Face ID` is removed as an authenticator via GH
* ensured that `Found no credentials on this device is displayed` if user attempts to authenticate using a key that was removed

![image](https://user-images.githubusercontent.com/2602313/153104771-64637ddb-ee8b-4101-93ed-077cdabd0be5.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|---------------|-----------------
![image](https://user-images.githubusercontent.com/2602313/153104802-83f8e1d0-40e6-4644-99a9-dea0c6f9786c.png) | ![image](https://user-images.githubusercontent.com/2602313/153104816-1810e5ad-5396-4b8a-855f-40776f4b8f65.png) | ![image](https://user-images.githubusercontent.com/2602313/153104849-ef62fba2-228b-4b1e-a215-6a37aed39b4a.png) | ![image](https://user-images.githubusercontent.com/2602313/153104877-03ed464b-1c21-4246-9fd9-a58514afd433.png) | ![image](https://user-images.githubusercontent.com/2602313/153104916-676b1a93-1eea-43c2-8f9c-f84bacc96ae4.png) | ![image](https://user-images.githubusercontent.com/2602313/153104938-fd48f41d-76b6-441a-8802-449a03fec236.png)

### `Test Case 3 - https://webauthn.io`

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|----------------|---------------
![image](https://user-images.githubusercontent.com/2602313/153115372-5b584682-5a47-40e2-9cc5-1f5757ebd047.png) | ![image](https://user-images.githubusercontent.com/2602313/153115399-937e2e04-7671-4a09-8d90-b1899b316b2e.png) | ![image](https://user-images.githubusercontent.com/2602313/153115423-df4e9c31-ef5c-42a0-b607-20d582dcba21.png) | ![image](https://user-images.githubusercontent.com/2602313/153115444-8de6945b-c66f-4d76-a63b-a2b514a3e6a9.png) | ![image](https://user-images.githubusercontent.com/2602313/153115468-d1e441c0-587a-46b6-90be-ab9dc947ee11.png) | ![image](https://user-images.githubusercontent.com/2602313/153115505-91ad22af-8265-4405-8435-dedd9d20aa49.png)

**`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`** | **`Example`**
----------------|----------------|----------------|----------------|----------------|----------------|----------------|---------------
![image](https://user-images.githubusercontent.com/2602313/153115912-18eecce2-d185-4549-b2b7-ea657e45fd3f.png) | ![image](https://user-images.githubusercontent.com/2602313/153115967-6243290b-8af0-42a6-9fae-14f2dd31bbb3.png) | ![image](https://user-images.githubusercontent.com/2602313/153115984-8a6128de-b42c-4453-97f9-c6ee0e8e0c29.png) | ![image](https://user-images.githubusercontent.com/2602313/153116014-e035fa4d-c65e-48d7-87bd-9e64c314264d.png) | ![image](https://user-images.githubusercontent.com/2602313/153116038-49b8adec-6dce-4ef9-886a-28ef296b6709.png) | ![image](https://user-images.githubusercontent.com/2602313/153116059-817374b5-2c6e-4f00-989b-20495f67537f.png) | ![image](https://user-images.githubusercontent.com/2602313/153116128-a8bcbaf8-1e13-46de-98b5-243c8641374f.png) | ![image](https://user-images.githubusercontent.com/2602313/153116147-ffaf824b-5dca-4f3c-9e69-a0fc42348cc1.png)
