### ISSUE TITLE
White bar overlay doesn't disappear when playing Playlist video 

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-ios#4475]
### Description: 
White bar at bottom of screen ("safe area"?) does not disappear when playing saved video content on Brave Playlist for iPhone (X).

### Steps to Reproduce 

1. Save a video to brave playlist
2. Press play
3. The white bar doesn’t disappear

**Actual result:** 
[will add screenshot when user supplies it]
![image](https://user-images.githubusercontent.com/3299098/140589503-bdc4e035-6806-49fa-a33c-617e8775d9fb.png)

**Expected result:**
White bar should disappear when video playback begins

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
Version 1.31.1 (21.9.28.16)

**Device details:** 
iPhone 11 X

### Additional Information
Original user report:
https://community.brave.com/t/iphone-home-bar-still-visible-while-playing-media-in-brave-playlist/297041

**Comment by Uni-verse** [comment]
Verified using version 1.46 (22.12.8.20) on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.4.2

STR: https://github.com/brave/brave-ios/issues/4475#issue-1046304078

- Verified white bar overlay disappears when playing video in full screen mode in playlist

https://user-images.githubusercontent.com/17885425/206779794-8b19b1cb-15e0-4b26-842a-316fbc857a85.MP4
