### ISSUE TITLE
Add ability to toggle biometric unlock in wallet settings

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4485]
Right now there's no way to enable biometric unlock when creating or restoring a wallet and no way to disable it once enabled. We should add the ability to turn it on/off from the wallet settings

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.38 (22.4.25.21)
- Verified test plan from [#5182](https://github.com/brave/brave-ios/pull/5182)
- Verified able to toggle biometric unlock on new wallets created
- Verified able to enable biometric unlock on restored wallets
- Verified when biometrics/face id is not registered the setting is not shown 

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.3) | iPad Pro (iOS 15.4.1 Beta)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/165733815-bd0d1065-204b-48bb-9502-cefed36729fa.mp4> | <img width=350 src=https://user-images.githubusercontent.com/17010094/165730137-caf065c9-65bc-4fd4-b4d2-a6575e5660a1.png> | <video src=https://user-images.githubusercontent.com/17010094/165734751-b267ddab-e25b-4346-9895-0e72ccf09a83.mp4>
