### ISSUE TITLE
Unlocking a wallet sometimes leads to no visible user assets

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4487]
There seems to be a small race condition between unlocking/creating/restoring a wallet and calling the API to get a users visible assets which causes it to return an empty list (which then means we dont load any portfolio details)

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33 (21.12.7.21)
- Verified creating wallet shows all default wallet assets and portfolio 
- Verified restoring wallet shows all user wallet assets and portfolio 
- Verified unlocking wallet doesn't cause the wallet to show empty values
------------
Verification passed on iPhone XR with iOS 15.1 running 1.33 (21.12.7.21)
- Verified creating wallet shows all default wallet assets and portfolio 
- Verified restoring wallet shows all user wallet assets and portfolio 
- Verified unlocking wallet doesn't cause the wallet to show empty values
------------
Verification passed on iPad Pro with iOS 15.2 running 1.33 (21.12.7.21)
- Verified creating wallet shows all default wallet assets and portfolio 
- Verified restoring wallet shows all user wallet assets and portfolio 
- Verified unlocking wallet doesn't cause the wallet to show empty values
