### ISSUE TITLE
App not backgrounds cleanly when killed from app switcher

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4490]
### Steps to Reproduce 
Test on iOS 15
  1. Open the app and few tabs with it
  2. Open app switcher, swipe up to kill the app
  3. Reopen the app

**Actual result:** 
Often crashes

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
We should check `iOS 14` quickly just to make sure that the above changes didn't affect restoring sessions in `iOS 14`. Also a good idea to check the above on multiple devices just to make sure we can't reproduce the crash anymore.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 12` running `iOS 15.1` using the following build:

```
1.32.3 (21.11.13.9)
```

Basically went through the following STR/Cases several times (~25 times) and ensured that Brave didn't crash. It was pretty easy to reproduce the original issue using the following STR:

* ensured that Brave doesn't crash after restoring it several times in quick succession
* ensured that Brave doesn't crash after restoring it when it's been closed for ~10min
* ensured that Brave doesn't crash after restoring it when it's been closed for ~a day (went through this on the weekend)
* ensured that quickly switching through several tabs via the tab tray doesn't crash the browser
* ensured that closing Brave while the tab tray is opened doesn't crash the browser
* ensured that backgrounding Brave and then switching back to Brave doesn't crash the browser

**Comment by kjozwiak** [comment]
I won't add `QA Pass - iPhone` until a few more people run through the above.

**Comment by stephendonner** [comment]
Verified `PASSED` using `1.32.3 (21.11.13.9)` on an `iPhone 6s` running `iOS 15.0.2`

Easily reproduced the crash using `1.32.3 (21.11.12.16)` on the same device/OS.

Confirmed I no longer see the crashes when doing the following:

* after restoring Brave several times in quick succession
* after restoring it when it's been closed for ~10min
* quickly switching through several tabs via the tab tray
* closing Brave while the tab tray is opened
* backgrounding Brave and then switching back to Brave

----------

Verified `PASSED` using `1.32.3 (21.11.13.9)` on an `iPad 5th Gen` running `iOS 14`

Confirmed no crashes observed while checking the following:

* after restoring Brave several times in quick succession
* after restoring it when it's been closed for ~10min
* quickly switching through several tabs via the tab tray
* closing Brave while the tab tray is opened
* backgrounding Brave and then switching back to Brave

-------

Verification passed on iPhone X with iOS 15.0.1 running 1.32.3(21.11.13.9)
- Verified no crash when closing Brave via app switcher
- Verified no crash when closing Brave via app switcher with tab tray open
- Verified no crash when Brave is opened after a while 
- Verified no crash when switching quickly between tabs via bottom bar swipe
- Verified no crash when switching quickly between tabs via tab tray
- Verified no crash when opening and closing tab tray 
- Verified no crash when closing tabs via tab tray

--------------------

Verified `PASSED` using `1.32.3 (21.11.13.9)` on an `iPad mini` running `iOS 15.0.2`

Easily reproduced the crash using `1.32.3 (21.11.12.16)` on the same device/OS.

Confirmed I no longer see the crashes when doing the following:

* after restoring Brave several times in quick succession
* after restoring it when it's been closed for ~10min
* quickly switching through several tabs via the tab tray
* closing Brave while the tab tray is opened
* backgrounding Brave and then switching back to Brave
