### ISSUE TITLE
Bookmarks are sometimes not synced in their corresponding folders.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#450]
Sometimes when you quickly add folders and bookmarks, syncing them on other device result in bookmarks being outside of folders

**Comment by iccub** [comment]
Related https://github.com/brave/browser-ios/issues/1776

**Comment by LaurenWags** [comment]
* Verified passed with 1.9 (19.3.9.1) on iPad 5th Gen. Tried adding bookmarks and folders quickly. Also imported bookmarks/folders and verified they were all synced correctly.
* Verified passed with 1.9 (19.3.9.1) on iPhone SE. All folders and bookmarks synced correctly.
* Verified passed with 1.9 (19.3.9.1) on iPhone 8. All folders and bookmarks synced correctly.
* Verification **PASSED** with `1.9 (19.3.27.19)` on `iPad Mini 4`

**Comment by srirambv** [comment]
Ran into #985 while verifying the issue when same bookmarks are added/deleted when syn chain is enabled

**Comment by srirambv** [comment]
This needs to be verified again after #985 is fixed. Marking as 1.10 GH milestone so that it gets verified for the next build.

**Comment by kjozwiak** [comment]
Going to remove this from `1.10` as it doesn't seem like any work went into this one.

> Ran into #985 while verifying the issue when same bookmarks are added/deleted when syn chain is enabled

Looks like #985 still hasn't been resolved. Sounds like we'll need to wait for #985 to be resolved before we start going through this one again. @michal, does the above sound right? If not, please move it back into `1.10` 👍

**Comment by iccub** [comment]
@kjozwiak Sync is going to be reworked anyway so we can wait with it. It's ok to remove it from 1.10
