### ISSUE TITLE
Tab switching keyboard shortcut new tab (ctrl + tab) 

### ISSUE THREAD

**Issue by raulchen** [brave/brave-ios#4502]
### Steps to Reproduce 
  1. open at least 2 tabs
  2. press ctrl + tab on a hardware keyboard 

**Actual result:** 

nothing happens.

**Expected result:**

Switches to the next tab.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Easily reproduced

**Brave Version:** 

Version 1.32.2 (21.11.4.20)

**Device details:** 

iPad Pro 2020, iPad OS 15.1

**Website problems only:**
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by raulchen** [comment]
I tested a few browsers. Safari and Edge are fine. Chrome doesn’t use the same keyboard shortcut. Firefox has the same issue.

**Comment by raulchen** [comment]
Firefox has fixed this bug. Looks like an iOS 15 compatibility issue.
https://github.com/mozilla-mobile/firefox-ios/issues/9532

**Comment by Uni-verse** [comment]
Verified using version `1.43 (22.9.2.15)`

Test Devices:
`iPad (7th Gen)` | `iOS 15.5`

Using STR in https://github.com/brave/brave-ios/issues/4502#issue-1051088826

Created as a follow up - https://github.com/brave/brave-ios/issues/5972

**Comment by Uni-verse** [comment]
Verified using version `1.43 (22.9.2.15)`

Test Devices:
`iPad (7th Gen)` | `iOS 15.5`

Created as a follow up - https://github.com/brave/brave-ios/issues/5972
