### ISSUE TITLE
Wallet handles unkown error and insufficient liquidity errors in swap

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#4503]
### Description: 

There should be 4 errors in Swap:
1. insufficient balance
2. insufficient funds for gas
3. Insufficient liquidity
4. unknown error
Currently missing last too. unkown error is for all other errors other than the first 3

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.1 running 1.33(21.12.9.17)
- Verified all errors are handled for swap

Insufficient Balance | Insufficient Liquidity | Insufficient Funds for Gas | Unknown Error 
-- | -- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/145465179-7e7f34a3-b36b-4eb7-90c0-65a2f10102dc.png) | ![image](https://user-images.githubusercontent.com/17010094/145465484-bb5cf512-a609-4d39-abb7-a90333e74ac0.png) | ![image](https://user-images.githubusercontent.com/17010094/145465164-4fa9f7d8-3d3a-49cb-a1c1-972093b176a7.png) | ![image](https://user-images.githubusercontent.com/17010094/145465194-dc42e154-13b5-42d2-ab7c-2bc7bdb8cc51.png)

------
Verification passed on iPad Pro with iOS 15.2 running 1.33(21.12.9.17)
- Verified all errors are handled for swap

Insufficient Balance | Insufficient Liquidity | Insufficient Funds for Gas | Unknown Error 
-- | -- | -- | -- 
![image](https://user-images.githubusercontent.com/17010094/145465562-492fc524-910f-4b6e-bcaa-69ca14dc89aa.png) | ![image](https://user-images.githubusercontent.com/17010094/145465682-705ea2a7-c501-4cf8-87f4-dbed44bbfc1c.png)| ![image](https://user-images.githubusercontent.com/17010094/145465586-f0f94b28-2e86-47eb-89ff-36a0ac15e7e4.png) | ![image](https://user-images.githubusercontent.com/17010094/145465501-699a3fbc-283e-4bc2-b10d-f84665cb8ce6.png)
