### ISSUE TITLE
Make it possible to duplicate already opened tabs 

### ISSUE THREAD

**Issue by dave90dave** [brave/brave-ios#4513]
## Problem Description 
Of I want to open the same browser tab twice, I must copy the link of that tab, open a new tab, and paste it in that tab.

would it not be more sufficient, to add a option to duplicate tabs?

## Feature Overview 
By adding a button, to duplicate the currently opened tab.

## Design 
I don’t have a sketch yet. But it maybe could be included in the context menu. Or even better: on the tab overview page.

## User Experience 
Non-binding example:
1. User clicks on tab overview button
2. User long presses on a certain tab, to show the duplicate button.
3. User clicks in the button, duplicate tab.
4. Tab is duplicated

**Comment by soner-yuksel** [comment]
Closing this issue since it will be address in another ticket.

@dave90dave please refer https://github.com/brave/brave-ios/issues/5235 for duplicate action and its design choice and/or extra information.
