### ISSUE TITLE
"Your connection is not private" interstitial pages should be yellow, instead of white

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#4518]
### Description: 

"Your connection is not private" interstitial pages should be yellow, instead of white (spun off from https://github.com/brave/brave-ios/issues/4338)

### Steps to Reproduce 
  1. install `1.32.3 (21.11.13.9)`
  2. load any of the error pages under `Certificate` on `https://badssl.com`, such as `https://captive-portal.badssl.com`
  3. look at the background color

**Actual result:** 
Background is white

![Image from iOS (2)](https://user-images.githubusercontent.com/387249/142066588-2cd8be1f-4263-48a0-bb42-bb828f2a0e6b.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/387249/142066153-ad56bf72-d28c-43a8-9612-b87269d0f123.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
Brave `1.32.3 (21.11.13.9)`

**Device details:** 
iPhone 6s (iOS 15.0.2)

cc @kylehickinson @jamesmudgett @Brandon-T

**Comment by kjozwiak** [comment]
Moving this into `1.32.3` as it looks like @Brandon-T has a PR in progress via https://github.com/brave/brave-ios/pull/4527.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.32.3(21.11.17.19)

iPhone 7+ (iOS 14.8) | iPhone XR (iOS 15.0.1) | iPad Pro (iOS 15.2.Beta 3)
-- | -- | --
<img width=400 src=https://user-images.githubusercontent.com/17010094/142415217-91764069-c4bb-489d-aad7-075f6aa0b911.png> | <img width=320 src=https://user-images.githubusercontent.com/17010094/142415181-5566786c-0c4a-4e46-af84-da0b2299e9d9.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/142415386-dc634816-477b-40dd-913d-302331596345.png>
