### ISSUE TITLE
Make User Assets the only available assets to send transaction in testnets

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#4520]
### Description: 
Currently, for all the networks, user can choose from user assets to send assets.
We need to make ETH the only asset that support sending in all the testnets (not the mainnet)

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33 (21.12.9.23)
- Verified ETH is the only asset by default on testnet
------
Verification passed on iPhone XR with iOS 15.1 running 1.33 (21.12.9.23)
- Verified ETH is the only asset by default on testnet
------
Verification passed on iPad Pro with iOS 15.2 running 1.33 (21.12.9.23)
- Verified ETH is the only asset by default on testnet
