### ISSUE TITLE
About Licenses page is blank

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#4521]
### Description: 

About Licenses page is blank

Found while testing https://github.com/brave/brave-ios/issues/4308

### Steps to Reproduce 
  1. install `1.32.3 (21.11.13.9)`
  2. launch Brave
  3.tap on the 3-dot menu on the bottom toolbar
  4. tap `Settings`
  5. swipe down to the very bottom
  6. tap on `Licenses` under `ABOUT`

**Actual result:** 
Only a blank page loads

![Image from iOS (3)](https://user-images.githubusercontent.com/387249/142072463-86fa14d5-cb62-4b9b-b28a-61fba6371746.png)

**Expected result:**

![Image from iOS (4)](https://user-images.githubusercontent.com/387249/142072431-ed5859a7-11c1-4978-b9c3-6eddfb5850a4.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
Brave `1.32.3 (21.11.13.9)`

**Device details:** 
`iPhone 6s (iOS 15.0.3)`

**Comment by LaurenWags** [comment]
Verified passed on iPad 5th Gen with iOS 14 running 1.32.3 (21.11.17.15)

Verified STR from https://github.com/brave/brave-ios/issues/4521#issue-1055410699

Confirmed Licenses page loads.
Confirmed able to expand various sections on Licenses page.

![IMG_0572](https://user-images.githubusercontent.com/28145373/142273174-562a7dfc-3ad0-423c-88dd-8ccb7beb78d3.PNG)

--------------------

Verified passed on iPad mini with iOS 15 running 1.32.3 (21.11.17.15)

Verified STR from https://github.com/brave/brave-ios/issues/4521#issue-1055410699

Confirmed Licenses page loads.
Confirmed able to expand various sections on Licenses page.

![Image from iOS](https://user-images.githubusercontent.com/28145373/142273206-46541746-22d0-4609-9757-1652809732dd.png)

-------------------

Verification **PASSED** on `iPhone 12` running `iOS 15.1` using `1.32.3 (21.11.17.19)`

* ensured that the `License` page loads without any issues
* ensured that you can expand the various available sections

![image](https://user-images.githubusercontent.com/2602313/142457272-20c298a9-16a1-442c-ae8d-9acdadc26c7a.png)

-------------------

Verification **PASSED** on `iPhone 6s+` running `iOS 14.6` using `1.32.3 (21.11.17.19)`

* ensured that the `License` page loads without any issues
* ensured that you can expand the various available sections

![image](https://user-images.githubusercontent.com/2602313/142457344-955f761b-f74e-478a-a459-fc7cbcee0c55.png)
