### ISSUE TITLE
Remove canvas fingerprinting protection

### ISSUE THREAD

**Issue by gpestana** [brave/brave-ios#4522]
Currently, the canvas fingerprinting protection is breaking captchas for iOS users. Remove the canvas fingerprint protection for now and improve the fingerprint protection implementation with farbling etc later on.

test plan https://github.com/brave/internal/issues/844

**Comment by srirambv** [comment]
Verification passed and verification notes can be found here https://github.com/brave/internal/issues/844#issuecomment-1005722849
