### ISSUE TITLE
some shield settings not retained on upgrade

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#4528]
### Description: 
Some shield settings are not retained on upgrade

### Steps to Reproduce 
  1. Install app store version (1.32.2) 
  2. Visit site like blizzard.com 
  3. Disable scripts 
  4. Close tab 
  5. Close Brave 
  6. Upgrade on release TF to 1.32.3 
  7. Open blizzard.com again 
  8. Scripts are enabled

**Actual result:** 
Scripts are enabled after upgrade

**Expected result:**
Scripts should still be disabled after upgrade

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.32.3 (21.11.13.9)

**Device details:** 
iPad iOS 14

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
reproduced by @srirambv 

cc @brave/legacy_qa

**Comment by iccub** [comment]
Can be retested in `1.32.3 (21.11.17.19)` despite this ticket still being open

**Comment by LaurenWags** [comment]
Verification passed on iPad 5th Gen with iOS 14 running 1.32.3 (21.11.17.19)

* Verified STR from https://github.com/brave/brave-ios/issues/4528#issue-1056361625. Confirmed the per site setting for "Block scripts" was retained after upgrade.
* Set amazon.com to enable cross-site trackers prior to upgrade. Confirmed this setting was retained after upgrade.
* Set raisegame.com to enable phishing prior to upgrade. Confirmed this setting was retained after upgrade.
* Set browserleaks.com/canvas to block fingerprinting prior to upgrade. Confirmed this setting was retained after upgrade.
* Set apple.com to disable HTTPS upgrades prior to upgrade. After upgrade this per site shield setting was no longer available.
* Enabled all per site settings for nytimes prior to upgrade. Confirmed all settings retained after upgrade.
* Disabled all per site settings for cnn prior to upgrade. Confirmed all settings retained after upgrade.
* Disabled shields entirely for stackoverflow. Confirmed main shields setting switch was retained after upgrade.

-------------------

Verification **PASSED** on `iPhone 12` running `iOS 15.1` using `1.32.3 (21.11.17.19)`

* enabled `Block Cross-Site Trackers`, `HTTPSE`, `Block Phishing & Malware`, `Block Scripts`, `Block all Cookies`, `Block Fingerprinting` via `Settings` and ensured everything was retained after upgrading to `1.32.3 (21.11.17.19)`
* disabled `Block Scripts` via `https://www.blizzard.com` after globally enabling via `Settings` and ensured that the setting was retained after upgrading
* enabled `Block Fingerprinting` via https://browserleaks.com/canvas and ensured that the setting was retained after upgrading
* disabled Brave shields via https://www.zerohedge.com and ensured that the setting was retained after upgrading
* disabled `Block Cross-Site Trackers` via https://www.buzzfeed.com and ensured that the setting was retained after upgrading
* ensured that `Upgrade Connections to HTTPS` was no longer available under Brave shields after upgrading but enabled globally
* disabled all available settings under Brave shields via https://videocardz.com and ensured that the settings were retained after upgrading
* enabled all available settings under Brave shields via https://amazon.com and ensured that the settings were retained after upgrading
* disabled `Block Phishing` via https://www.raisegame.com and ensured that the setting was retained after upgrading

-------------------

Verification **PASSED** on `iPhone 6s+` running `iOS 14.6` using `1.32.3 (21.11.17.19)`

* enabled `Block Cross-Site Trackers`, `HTTPSE`, `Block Phishing & Malware`, `Block Scripts`, `Block all Cookies`, `Block Fingerprinting` via `Settings` and ensured everything was retained after upgrading to `1.32.3 (21.11.17.19)`
* disabled `Block Scripts` via `https://www.blizzard.com` after globally enabling via `Settings` and ensured that the setting was retained after upgrading
* enabled `Block Fingerprinting` via https://browserleaks.com/canvas and ensured that the setting was retained after upgrading
* disabled Brave shields via https://www.zerohedge.com and ensured that the setting was retained after upgrading
* disabled `Block Cross-Site Trackers` via https://www.buzzfeed.com and ensured that the setting was retained after upgrading
* ensured that `Upgrade Connections to HTTPS` was no longer available under Brave shields after upgrading but enabled globally
* disabled all available settings under Brave shields via https://videocardz.com and ensured that the settings were retained after upgrading
* enabled all available settings under Brave shields via https://amazon.com and ensured that the settings were retained after upgrading
* disabled `Block Phishing` via https://www.raisegame.com and ensured that the setting was retained after upgrading

----------------

Verification passed on iPad mini with iOS 15 running 1.32.3 (21.11.17.19)

* enabled `Block Cross-Site Trackers`, `HTTPSE`, `Block Phishing & Malware`, `Block Scripts`, `Block all Cookies`, `Block Fingerprinting` via `Settings` and ensured everything was retained after upgrading to `1.32.3 (21.11.17.19)`
* Verified STR from https://github.com/brave/brave-ios/issues/4528#issue-1056361625. Confirmed the per site setting for "Block scripts" was retained after upgrade.
* Set amazon.com to enable cross-site trackers prior to upgrade. Confirmed this setting was retained after upgrade.
* Set raisegame.com to enable phishing prior to upgrade. Confirmed this setting was retained after upgrade.
* Set browserleaks.com/canvas to block fingerprinting prior to upgrade. Confirmed this setting was retained after upgrade.
* Set apple.com to disable HTTPS upgrades prior to upgrade. After upgrade this per site shield setting was no longer available.
* Enabled all per site settings for nytimes prior to upgrade. Confirmed all settings retained after upgrade.
* Disabled all per site settings for cnn prior to upgrade. Confirmed all settings retained after upgrade.
* Disabled shields entirely for stackoverflow. Confirmed main shields setting switch was retained after upgrade.
