### ISSUE TITLE
Changes to sync QR code 

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#4534]
### Description: 
See https://github.com/brave/internal/issues/832

**Comment by LaurenWags** [comment]
@Brandon-T should this be in the 1.33 milestone?

**Comment by kjozwiak** [comment]
> @Brandon-T should this be in the 1.33 milestone?

yup, I'll add it @LaurenWags. Should have had the `1.33.x` milestone once this was merged.

**Comment by LaurenWags** [comment]
iOS <--> iOS sync verification notes are here: https://github.com/brave/brave-browser/issues/19550#issuecomment-988183230

iOS <--> Android and iOS <--> desktop cases will also be covered under https://github.com/brave/brave-browser/issues/19550.

**Comment by stephendonner** [comment]
Verified `PASSED` with Brave `1.33 (21.12.13.3)` on various iOS devices running both `15.0.2` and `14.4.2`.

As @LaurenWags wrote above, iOS <--> iOS and desktop (on all platforms) <---> iOS have now been tested and covered in https://github.com/brave/brave-browser/issues/19550.
