### ISSUE TITLE
Add EIP1559 support

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#4537]

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33(21.12.7.21)
- Verified EIP-1559 support is available for both send and swap transactions

Default | Custom 
-- | --
![image](https://user-images.githubusercontent.com/17010094/145267943-b5a54358-bba6-4d86-b00c-9f0b38841041.png) | ![image](https://user-images.githubusercontent.com/17010094/145267949-a925f3fd-9f0a-4cc7-8b5e-7058a84586cd.png)


------------
Verification passed on iPhone XR with iOS 15.1 running 1.33(21.12.7.21)
- Verified EIP-1559 support is available for both send and swap transactions

Default | Custom 
-- | --
![image](https://user-images.githubusercontent.com/17010094/145267901-60678d72-f1b7-46d8-8eef-7a84307f0282.png) | ![image](https://user-images.githubusercontent.com/17010094/145267919-44498d1c-44f9-4c20-a3b4-24aa925ae056.png)

------------
Verification failed on iPad Pro with iOS 14.8.1 running 1.33(21.12.7.21)
- Ran in to crash ([#4667](#4667)) when trying to submit a transaction so couldn't get the edit gas modal
