### ISSUE TITLE
Rewards Panel is showing Publisher info on NTP

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#4539]
### Description: 
- On NTP, open rewards panel
- It shows "Publisher not verified"

### Steps to Reproduce 
  1. Open Rewards Panel on NTP

**Actual result:** 
- Shows publisher not verified

**Expected result:**
- Should not show publisher information

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.32.1+

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPad 7th Generation version iOS 15.1` running `Brave version 1.33 (21.12.7.21)`

- Reproduced the issue in-app store version 1.32
- Confirmed `"Publisher not verified"` message is not shown in NTP Brave Rewards panel in 1.33

![IMG_0181](https://user-images.githubusercontent.com/38657976/145246574-21dacf4f-8e56-45f7-b6b4-1bccb6befdc5.PNG)

-------

Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.33 (21.12.7.21)`

**`Regression`** | **`Fixed`** | **`Unverified`** | **`Verified`**
------------------|-------------|------------------|---------------
![IMG_0408](https://user-images.githubusercontent.com/2602313/145288574-c01450c2-5416-4015-8fef-86146a94acb3.png) | ![IMG_0409](https://user-images.githubusercontent.com/2602313/145288587-a940bd0d-f3df-41c5-bdfc-97de56720ded.png) | ![IMG_0410](https://user-images.githubusercontent.com/2602313/145288598-b300eede-1afb-4f6a-a0ba-40c9bd8512ff.png) | ![IMG_0411](https://user-images.githubusercontent.com/2602313/145288612-1284f939-db16-4d7f-8df2-0729e795098e.png)

-----------

Verification **PASSED** on `iPhone 6+` running `iOS 14.6` using `1.33 (21.12.7.21)`

**`Regression`** | **`Fixed`** | **`Unverified`** | **`Verified`**
------------------|-------------|------------------|---------------
![IMG_0206](https://user-images.githubusercontent.com/2602313/145290129-774db5ba-cd50-4994-a09d-f393c7a4c3e7.png) | ![IMG_0207](https://user-images.githubusercontent.com/2602313/145290142-7138fd12-83a3-469f-be7f-69d64d122c34.png) | ![IMG_0208](https://user-images.githubusercontent.com/2602313/145290148-98d725c2-5459-45d0-8456-70366f692676.png) | ![IMG_0209](https://user-images.githubusercontent.com/2602313/145290153-e6fcffbc-56e1-4a9b-92ac-d69ba0ec35cc.png)
