### ISSUE TITLE
Tapping on the pulse animation in onboarding popover doesn't dismiss the popover

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#4542]
### Description: 
- When onboarding popover is shown, tapping the item that the popover points at, doesn't open the item or dismiss it.
- https://bravesoftware.slack.com/archives/C06UXF3KJ/p1637567929300100

**Actual result:** 
- Doesn't dismiss the popover

**Expected result:**
- Should dismiss the popover or open the item it points at.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.32.3+

**Comment by GeetaSarvadnya** [comment]
Verification passed on `iPad 7th Generation version iOS 15.1` running Brave version `1.33 (21.11.30.21)`
Covered the testing in Case 1, 2,3, and 4  in https://github.com/brave/brave-ios/issues/4372#issuecomment-984465058  
- Ensured tapping on the item on the popover opens up the item
- Ensured popups in the welcome onboarding flow can be dismissed

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.33 (21.12.8.22)` on an iPhone 6s running iOS `15.0.2` and another iPhone 6s running iOS `14.4.2`

Confirmed I could tap to dismiss the pulse and popover animations on the onboarding screens.

iOS 14.4.2 | iOS 15.0.2
------------|------------
<video src="https://user-images.githubusercontent.com/387249/145322836-5e7dfa4b-589b-4d2d-97d9-4a405c022847.MP4"> | <video src="https://user-images.githubusercontent.com/387249/145322864-723478d6-d872-4870-9673-434215572b8e.MP4">
