### ISSUE TITLE
Onboarding NTP shows on websites when it shouldn't

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#4544]
### Description: 
- Onboarding NTP shows on websites when it shouldn't

### Steps to Reproduce 
  1. On the last page of onboarding, select `Enter a Website`
  2. Enter `brave.com` (Do not hit cancel)
  3. NTP overlay shows on top of the website

**Actual result:** 
![image](https://user-images.githubusercontent.com/1530031/142923974-554b7b25-98e0-4e6d-a15d-c32b8cd57a17.png)

**Expected result:**
Should not show

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.32.3

**Comment by iccub** [comment]
marking as qa/no because this should be tested as a part of whole onboarding process
