### ISSUE TITLE
Moving bookmark down causes swap of position.

### ISSUE THREAD

**Issue by parsd51** [brave/brave-ios#4547]
### Description: 
Moving bookmark down causes swap of position.

### Steps to Reproduce 
  1. Have quite many bookmarks in total (not sure if it matters)
  2. Move a bookmark one or several places DOWN.
  3.

**Actual result:** 
Bookmark is swapped with the one above.

Exception: Moving it to the last position works.

**Expected result:**
Bookmark is located where it’s placed.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.32.3 (21.11.17.19)

**Device details:** 
Ipad Air 4, iPadOS 15.1

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by Uni-verse** [comment]
Verified using version `1.43 (22.9.1.15)`

Test Devices:

1. `iPhone 12 Pro` running `iOS 15.5`
2. `iPhone X` running `iOS 14.4.2`
3. `iPad (7th Gen)` running `iPadOS 15.5`


- Verified when moving bookmark  does not cause it to swap.
- Verified when moving folders does not cause unexpected behavior.
- Verified ensured moving bookmarks does not case the swap to happen on `upgraded profile.`

https://user-images.githubusercontent.com/17885425/188178802-1285f7e3-af60-44f3-89c3-942596d92ea0.MP4
