### ISSUE TITLE
Restore SwiftPM's resolved file

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#4552]
### Description: 
- Swift PM's resolved file was removed accidentally.
- 
**Brave Version:** 
1.32.x

**Comment by kjozwiak** [comment]
Assuming there's nothing that QA needs to do here so labelling this as `QA/No` and `release-notes/exclude`. @Brandon-T please change the labels if that's if there's anything that QA needs to here including STR/Cases 👍
