### ISSUE TITLE
Filter out ERC721 tokens  from token selection in Send and Swap

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#4554]
### Description: 
ERC721 Tx is not yet supported in MVP. 
However, there are ERC721 tokens coming from `TokenRegistery`. We need to filter then out from the selection in Send and Swap Screens.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.33(21.11.30.21)
- Verified ERC721 tokens are not listed on Swap screen 

iPhone &+ (iOS 14.8) | iPhone XR (iOS 15.1) | iPad Pro (iOS 15.2 Beta)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/144288762-624ec169-c196-4a87-8582-1d1950936daa.png> | <img width=240 src=https://user-images.githubusercontent.com/17010094/144288907-53a60bc4-bc3a-4ea2-b25d-334755c7d17e.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/144288880-db4d1193-fadf-4726-b328-0466f819f444.png>
