### ISSUE TITLE
Selecting localhost network crashes the app

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4556]
If you attempt to change your chain to `Localhost` it will crash the app.

We should remove localhost from the options list anyways as iOS does not support setting up an chain locally anyways

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8 running 1.33(21.11.30.21)
- Verified `localhost` is not shown in network dropdown on any of the screens

Portfolio | Send | Swap
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/144277174-dd6951dc-c1d2-4591-9d5e-7b7811ec3598.png) | ![image](https://user-images.githubusercontent.com/17010094/144277191-6a850e0c-6f52-417a-806f-fbea2623b01d.png) | ![image](https://user-images.githubusercontent.com/17010094/144277201-021e1fb5-a11f-4de3-80eb-23bc259fb43b.png)

------------
Verification passed on iPhone XR with iOS 15.1 running 1.33(21.11.30.21)
- Verified `localhost` is not shown in network dropdown on any of the screens

Portfolio | Send | Swap
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/144277038-1c997f19-18c2-4fbc-a02e-379265ad0f2f.png) | ![image](https://user-images.githubusercontent.com/17010094/144277048-d3bda64b-fb00-47d7-9fe4-0dceba8477ea.png) | ![image](https://user-images.githubusercontent.com/17010094/144277059-855340bb-a530-4065-942c-2c543533be8a.png)

------------
Verification passed on iPhone 7+ with iOS 14.8 running 1.33(21.11.30.21)
- Verified `localhost` is not shown in network dropdown on any of the screens

Portfolio | Send | Swap
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/144277115-e1cab6e5-e6e3-4b85-b3ed-e6ae7fe41fac.png) | ![image](https://user-images.githubusercontent.com/17010094/144277129-5028ac0d-87c9-488e-8674-fb65da243211.png) | ![image](https://user-images.githubusercontent.com/17010094/144277141-c7b962f9-f873-42a4-be0c-bb517524ea21.png)
