### ISSUE TITLE
Qwant, Startpage links and popups do not work in private mode

### ISSUE THREAD

**Issue by danishjafri88** [brave/brave-ios#456]
We should handle window.open when in private mode

Enhancement for #446 & #455:

**What**
In private mode the WKProcessPool of the WKWebViewConfiguration is overridden to avoid passing of cookies and other data between WKWebViews. This behaviour when combined with a popup ie window.open results in a crash

**Why**
When a window.open is called the parent WKWebView calls the delegate method: 

```
optional public func webView(_ webView: WKWebView, createWebViewWith configuration: WKWebViewConfiguration, for navigationAction: WKNavigationAction, windowFeatures: WKWindowFeatures) -> WKWebView?
``` 

in `WKUIDelegate`. It provides a configuration for the new window. When in private mode, this configuration is altered resulting in corruption of configuration and subsequent crash.

**Current-Fix**
For now all popups are blocked when in private mode. (BrowserViewController.swift)
See: https://github.com/brave/brave-ios/issues/456#issuecomment-474025905

**Enhancement**
Two possible solutions:

1. Keep blocking popups and instead show an alert telling the user of the reason.
2. Intercept popup call in private mode, create a new tab (not a popup) with the same request and return nil. (What other info needs to be used from the callback can be discussed later.)

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

**Comment by kylehickinson** [comment]
This affects one of the search engines we support, Startpage.com, which by default opens search results in a new window.

**Comment by jhreis** [comment]
Please see: https://github.com/brave/brave-ios/issues/446#issuecomment-441873132 for rationale.

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+ running 1.9(19.03.27.19)
  - Verified search results on Startpage and Qwant in private tabs load result in a new tab
  - Also verified steps from https://github.com/brave/brave-ios/issues/446 description 

* Verification passed on iPad Pro running 1.9(19.03.27.19)
  - Verified search results on Startpage and Qwant in private tabs load result in a new tab
  - Also verified steps from https://github.com/brave/brave-ios/issues/446 description 

* Verification passed on iPhone SE running 1.9 (19.03.27.19)
  - Verified search results on Startpage and Qwant in private tabs load result in a new tab
  - Also verified steps from https://github.com/brave/brave-ios/issues/446 description 

* Verification passed on iPad 5th Gen running 1.9 (19.03.27.19)
  - Verified search results on Startpage and Qwant in private tabs load result in a new tab
  - Also verified steps from https://github.com/brave/brave-ios/issues/446 description

* Verification **PASSED** with `1.9 (19.3.27.19)` on `iPad Mini 4`
  - Verified search results on Startpage and Qwant in private tabs load result in a new tab
  - Also verified steps from https://github.com/brave/brave-ios/issues/446 description 

- Verification passed on iPad 5th Gen running 1.9 (19.03.28.14)
 - Verified search results on Startpage and Qwant in private tabs load result in a new tab
 - Also verified steps from https://github.com/brave/brave-ios/issues/446 description
