### ISSUE TITLE
Add a easy way to copy wallet address 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4561]
### Description: 
Add a easy way to copy wallet address. Right now you need to go to Accounts -> Account name -> Edit -> copy. There should be an easy way to copy the address

**Actual result:** 
No easy way to copy address with long press or easy copy button

**Expected result:**
Long press on account name to copy address or add a small clipboard button to copy address

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
NA

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @kylehickinson @jamesmudgett

**Comment by Uni-verse** [comment]
Verification completed on following devices using build version `1.35 (22.1.14.22)`

PASSED on `iPhone 12 Pro` running `iOS 15.1.1` 
PASSED on `iPhone X` running `iOS 14.4.2`
PASSED on `iPad (7th Gen)` running `iPadOS 14.4.2`

- Verified long press shows clipboard copy option
- Verified clipboard value matches the wallet address

Note: Was not able to import secondary account for testing. 

UI on iPhone

https://user-images.githubusercontent.com/17885425/150231893-99fb33ec-01a7-46cc-97b3-386156f2f9ff.MP4
