### ISSUE TITLE
Adding an account within the asset details screen doesn't update the accounts list

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4562]
### Description: 

If you tap "Add Account" on the asset details page and successfully make an account the account doesn't get immediately get added to the list of accounts in that screen. We should update that accounts list after that happens. 

We do already handle `accountsChanged` on this page so perhaps there is a race condition between the observer being called and the account being returned by `defaultKeyringInfo`

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.35 (22.1.24.23)
- Verified test plan from [#4816](https://github.com/brave/brave-ios/pull/4816)
- Verified new accounts are listed without having to navigate back from the screen

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.2) | iPad Pro (iOS 15.3)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/150943355-6ba7ea9c-b08b-4ee8-adba-d66ce56d917f.mp4> | <video src=https://user-images.githubusercontent.com/17010094/150943380-2244fd2d-4b3c-4d7a-b98e-763e5a9cf3f5.mp4> | <video src=https://user-images.githubusercontent.com/17010094/150943212-eb636b6d-499e-4f87-b4f8-b838771eb984.mp4>
