### ISSUE TITLE
Swap Button gets reset after an error

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#4563]
### Description: 
Any error occurs after `priceQuote` will reset the swap button

### Steps to Reproduce 
  1. Go to wallet swap
  2. pass price quote by entering some amount of selling token
  3. mimic an error (make sure its not one of the following cases: 1. insufficient balance, 2. insufficient liquidity, 3. insufficient funds for gas, 4. low allowance)

**Actual result:** 
Swap button should be disabled with `Unknown error` title

**Expected result:**
Swap button is initially set to `Unknown error` then becomes `Swap`

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.33(21.11.30.21)
- Verified swap button doesn't reset when it encounters `Unknown error`

iPhone 7+ (iOS 14.8) | iPhone XR (iOS 15.1) | iPad Pro (iOS 15.2 Beta)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/144270198-9057d0cc-75a7-46c9-a602-0dfd78f44950.png> | <img width=240 src=https://user-images.githubusercontent.com/17010094/144270903-0e7c7727-8b56-4c8d-8cb2-839d43a1c5fe.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/144270916-ff1f8c30-763b-420c-8052-e27062d6f5e5.png>
