### ISSUE TITLE
DDG modal can't be dismissed when popup keyboard is active 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#457]
### Description: 
DDG modal can't be dismissed when popup keyboard is active 

### Steps to Reproduce 
  1. Open a new private tab either via long press or via tab container
  2. Tap on the DDG info modal while the popup keyboard is active 
  3. Can't dismiss it until you open a site and the keyboard autohides

**Actual result:** 
https://drive.google.com/open?id=1SAARv7zROxwlsTD7jCwrDjcGPlY0mRAa

**Expected result:**
If DDG modal shows up keyboard should be hidden so that the info modal can be closed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.11.21.22)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
When the DDG button is selected, we should dismiss the keyboard.
