### ISSUE TITLE
Brave News NTP crash

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4575]
Look for recent crashes in Xcode organizer. Happens on iOS 15 devices only

<img width="468" alt="Zrzut ekranu 2021-11-29 o 14 51 24" src="https://user-images.githubusercontent.com/6950387/143879850-85d06f49-558b-4d20-94eb-29c9f9a1e709.png">

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.34(22.1.4.19)
- Verified closing default browser modal and Brave News opt-in modal doesn't cause any crash
------------
Verification passed on iPhone XR with iOS 15.2 running 1.34(22.1.4.19)
- Verified closing default browser modal and Brave News opt-in modal doesn't cause any crash
-------------
Verification passed on iPad Pro with iOS 15.3 running 1.34(22.1.4.19)
- Verified closing default browser modal and Brave News opt-in modal doesn't cause any crash
