### ISSUE TITLE
Crash when adding page to favorites

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#4578]
### Description: 
Noticing a crash when adding a page to favorites. This did happen before - not sure if this is a regression

### Steps to Reproduce 
  1. Have an existing profile with bookmarks, favorites, etc (I have 13 favorites saved)
  2. Visit a page (ex: https://reddit.com/r/random)
  3. Click the "..." in bottom right of page
  4. Scroll the menu up
  5. Pick `Add to Favorites`

**Actual result:** 
- Brave crashes :(
- When relaunching, you can open saved tabs and this works 👍 
- Favorite WAS actually saved

**Expected result:**
- Saving favorite without crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
Dev - 1.33 (21.11.22.22)

**Device details:** 
iPhone 12 mini

**Comment by kjozwiak** [comment]
Going to label this one as a duplicate and will use https://github.com/brave/brave-ios/issues/4651 which I labelled as `release/blocking`. As per https://github.com/brave/brave-ios/issues/4463#issuecomment-988475923, the cases mentioned via https://github.com/brave/brave-ios/issues/4463#issuecomment-988289255 will be QA'd in https://github.com/brave/brave-ios/issues/4651 once a solution is found for `iOS 14`.
