### ISSUE TITLE
Add note about using 0x on swap UI

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4579]
Desktop has a label at the bottom of their Swap panel that says `Brave uses 0x as a DEX aggregator.` and includes an icon for more info. We will need to incorporate this into the swap screen on iOS as well.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.33(21.11.30.21)
- Verified Swap screen has a 0x disclaimer
- Verified clicking on the info button brings up the disclaimer message
- Verified clicking on the `Learn more` button loads a new tab and navigates to `https://0x.org`

iPhone 7+ (iOS 14.8) | iPhone XR (iOS 15.1) | iPad Pro (iOS 15.2 Beta)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/144259142-cd3137e2-f7ad-434b-9dda-11b0365a0044.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/144259179-6eda5cc6-e60f-4d16-ab03-d19fb57cad1a.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/144259198-82c97d72-13bc-4956-96d3-392ebb9a1d02.png>
