### ISSUE TITLE
Cancel on touch id doesn't bring up passcode field

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#458]
### Description: 
Cancel on touch id doesn't bring up passcode field

### Steps to Reproduce 
  1. Enable passcode from settings
  2. Enable touch id and require passcode immediately
  3. Background the app and bring into focus, asks for touch id, cancel doesn't bring passcode field instead asks to use touch id to unlock. Incorrect fingerprint brings up passcode option

**Actual result:** 
Cancel touch id doesn't bring up passcode field

**Expected result:**
Cancel on touch id should automatically bring passcode field

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.11.21.22)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
What is behavior on 1.6?

**Comment by srirambv** [comment]
1.6 brings up passcode when you cancel touch id
