### ISSUE TITLE
Restore widgets

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4582]
Widgets extension target was removed from project, restore it once we get back to this project.

**Comment by Brandon-T** [comment]
Whoever takes up this assignment, please see: https://github.com/brave/brave-ios/pull/4692
When this ticket is complete, we should re-test favourites.

In the code, search for `// MARK: Widgets Disabled due to Crash on iOS 14 Favourites - Brandon T.`

**Comment by Brandon-T** [comment]
Found the reason for the crash. 
It is: https://bugs.swift.org/browse/SR-12288
It is solved in [#4738](https://github.com/brave/brave-ios/pull/4738)
