### ISSUE TITLE
Wallet page indicator has incorrect width on iPad until scrolled

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4586]
### Description: 

When you unlock wallet and get to the crypto pages screen the gradient page indicator that appears under the selected page will be the wrong size until you swipe the screen

![image](https://user-images.githubusercontent.com/529104/144133267-b302d627-2749-4a10-a23b-f458b2ff73e0.png)

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 15.3 running 1.34 (22.1.4.19)
- Verified wallet page indicator shows correctly on both landscape and portrait mode

Portfolio (Landscape) | Account (Landscape)
-- | --
![image](https://user-images.githubusercontent.com/17010094/148244641-7082d818-6616-4678-8d80-1bde431c5c40.png) | ![image](https://user-images.githubusercontent.com/17010094/148244511-66d3c398-7474-4cae-8c01-178b31c9de07.png)


Portfolio (Portrait) | Account (Portrait)
-- | --
![image](https://user-images.githubusercontent.com/17010094/148244286-8eed3001-d7ff-49de-b0ae-53efede7c531.png) | ![image](https://user-images.githubusercontent.com/17010094/148244387-64cbb4c5-bf2d-4c89-a4f0-d5899a3ee127.png)
