### ISSUE TITLE
Brave crashes upon tapping on the `Not now` or `Skip` buttons on the `Make Brave your default browser` slide. 

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#4593]
### Description: 
Found while testing https://github.com/brave/brave-ios/issues/4542

Brave crashes upon tapping on the `Not now` or `Skip` buttons on the `Make Brave your default browser` slide. 

### Steps to Reproduce 
  1. Clean profile 1.33 (21.11.30.21)
  2. Tap on the `Not now` or `Skip` buttons on the `Make Brave your default browser` slide. 
  3. No action is taken place, slide remained as it is
  4. Background the app and relaunch
  5. Repeat step 2 
  6. Repeated steps 4 and 5 twice 
  7. Brave crash

**Actual result:** 
No crash

**Expected result:**
User should be taken to next screen when tap on `Not now` or `Skip` buttons

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100 % with above steps
**Brave Version:** 

1.33 (21.11.30.21)
**Device details:** 
iPhone 8 and iOS 15.1

**Website problems only:**
- did you check with Brave Shields down?NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @bsclifton @Brandon-T @brave/legacy_qa

**Comment by GeetaSarvadnya** [comment]
Please note this issue is happening only on my device iPhone 8 - iOS 15.1. Click on any button on the `Set brave default browser` slide will crash the browser. Apart from this other slides are working fine.

**Comment by soner-yuksel** [comment]
Cant reproduce this with various devices and simulator using both iOS 15 and iOS 14.

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPhone 8 version iOS 15.1` running `Brave version 1.33 (21.12.14.16)`
