### ISSUE TITLE
Page load progress gets stuck when tab is closed quickly 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#460]
### Description: 
Page load progress gets stuck when tab is closed quickly 

### Steps to Reproduce 
  1. Visit any site in a new tab
  2. Open a new tab and load https://badssl.com
  3. Quickly close badssl.com tab while the page is loading, the blue progress indicator gets stuck on the current tab

**Actual result:** 
https://drive.google.com/open?id=1UPoHGvIeVBYGk4NVf3Pr--y-SeQM0ujz

**Expected result:**
Once tab is closed page load should not continue and the progress indicator should be removed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.11.21.22)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
This was accidentally closed. Actually closed #469
