### ISSUE TITLE
Japan NTP Tutorial Page regression 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4601]
### Description: 
In the new [onboarding](https://github.com/brave/brave-ios/issues/4298), we appear to have a regression of https://github.com/brave/brave-ios/issues/3389

Can we please open https://brave.com/ja/ntp-tutorial/ in a background Tab for new users. This tab won't be in focus initially as either:

- https://m.yahoo.co.jp/
- https://wired.jp/
- https://number.bunshun.jp/
- user defined

will be

cc @soi-tnk

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPad 7th Generation version iOS 15.1` running `Brave version 1.33 (21.12.7.21)`

- Confirmed https://brave.com/ja/ntp-tutorial/ page opened in the background tab for the new users
- Confirmed https://brave.com/ja/ntp-tutorial/ is not the active tab or focused if user skip the onboarding flow (NTP is the active tab)
- Confirmed if user select/enter any site in the last slide, the selected site is opened and focused, https://brave.com/ja/ntp-tutorial/ is in the background tab

-----

Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.33 (21.12.7.21)`

- Confirmed https://brave.com/ja/ntp-tutorial/ page opened in the background tab for the new users
- Confirmed https://brave.com/ja/ntp-tutorial/ is not the active tab or focused if user skip the onboarding flow (NTP is the active tab)
- Confirmed if user select/enter any site in the last slide, the selected site is opened and focused, https://brave.com/ja/ntp-tutorial/ is in the background tab

-----

Verification **PASSED** on `iPhone 6+` running `iOS 14.6` using `1.33 (21.12.7.21)`

- Confirmed https://brave.com/ja/ntp-tutorial/ page opened in the background tab for the new users
- Confirmed https://brave.com/ja/ntp-tutorial/ is not the active tab or focused if user skip the onboarding flow (NTP is the active tab)
- Confirmed if user select/enter any site in the last slide, the selected site is opened and focused, https://brave.com/ja/ntp-tutorial/ is in the background tab

Ran into https://github.com/brave/brave-ios/issues/4601#issuecomment-989178685 on `iOS 14`.

**Comment by kjozwiak** [comment]
Ran into https://github.com/brave/brave-ios/issues/4672 on `iOS 14`. I don't think it's a blocker and users will still see the NTP on-boarding modals when they open a new NTP. Everything else is working as expected. Going to label this `QA Pass - iPhone`. We'll run through it again via https://github.com/brave/brave-ios/issues/4672 on `iOS 14` if it ends up getting fixed.
