### ISSUE TITLE
Set Brave as default browser message is shown in NTP even after setting brave as default browser via Onboarding modal

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#4603]
### Description: 

Found while testing https://github.com/brave/brave-ios/issues/4372

Set Brave as default browser message is shown in NTP even after setting brave as default browser via Onboarding modal
### Steps to Reproduce 
  1. Clean profile 1.33 (21.11.30.21)
  2. Go through the onboarding flow and set brave as the default browser
  3. Open an NTP 
  4. Set brave as the default browser message is shown

**Actual result:** 
Set Brave as default browser message is shown in NTP even after setting brave as default browser via Onboarding modal

https://user-images.githubusercontent.com/38657976/144389467-45c3174e-62ef-4e6e-afd5-851371c73109.MP4

**Expected result:**
Once brave is set as a default browser via onboarding flow, set default browser message shouldn't be shown in NTP

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.33 (21.11.30.21)

**Device details:** 
iPad (7th generation) - iOS 15.1

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information

cc: @Brandon-T @soner-yuksel @iccub

**Comment by Brandon-T** [comment]
Atm, this is impossible to fix. There is no API available (that is not private) to detect if we're the default browser or if it's already set.

**Comment by soner-yuksel** [comment]
Closing this ticket since there is no way to achieve this behaviour
