### ISSUE TITLE
Look into disabling screenshot of sensitive data(seed) on wallet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4604]
Similar to Android(https://github.com/brave/brave-browser/issues/19864), look into disabling taking screenshot of seed words but maybe allow portfolio or possibly add a share feature for it similar to share stats

cc: @nuo-xu @kylehickinson @jamesmudgett

**Comment by HEagle18** [comment]
I wasn't able to screenshot seedwords during the week on iOS. 

Could we close this out @nuo-xu @StephenHeaps ?

**Comment by nuo-xu** [comment]
Yes. Close as completed.
