### ISSUE TITLE
Update password validation to use shared desktop implementation

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4605]
We now have a shared implementation for password validation in BraveCore (https://github.com/brave/brave-core/pull/11327) based on sec review.

The current iOS password logic was:

- More than 7 characters
- At least 1 number
- At least 1 special character (`\ ~ ! @ # $ % ^ & * ( ) + = ? ; : | < > , . ' " { } / [ ] \ - _`)

The new shared password validation logic is:

- At least 7 characters
- At least 1 number
- At least 1 letter
- At least one non-alphanumeric

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.33(21.12.9.23)
- Verified test plan from issue description
- Verified entering a password that doesn't satisfy the criteria shows the message below the password field

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.1) | iPad Pro (iOS 15.2)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/145528386-b5b5fbd2-1e05-4cf7-8f58-98566f9a1c75.png> | <img width=240 src=https://user-images.githubusercontent.com/17010094/145528393-e1d69299-dd70-42e6-b78a-f5b21d1d008c.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/145528412-44c58030-64ce-44a2-a14d-723ff6fa340c.png>
