### ISSUE TITLE
3dot menu intro popup isn't shown in NTP even though stats data is present in the NTP

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#4607]
### Description: 
Found while testing https://github.com/brave/brave-ios/issues/4372
3dot menu intro popup isn't shown in NTP even though stats data is present in the NTP

### Steps to Reproduce 
  1. Clean profile 1.33 (21.11.30.21)
  2. Go through the welcome onboarding flow
  3. Tap on Yahoo.com in the last slide
  4. Click on any link on the yahoo to store trackers data in NTP
  5. Open a NTP
  6. 3dot menu intro popup isn't shown in NTP even though stats data is present in the NTP

**Actual result:** 
3dot menu intro popup isn't shown in NTP even though stats data is present in the NTP

https://user-images.githubusercontent.com/38657976/144456818-3b01f831-4e93-4dba-aed2-fbd4f10719c4.MP4

**Expected result:**

3dot menu intro popup should be shown in NTP when stats data is present in the NTP
**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Easy
**Brave Version:** 

1.33 (21.11.30.21)
**Device details:** 

iPad 7th Generation - iOS 15.1
**Website problems only:**
- did you check with Brave Shields down?NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T @soner-yuksel @iccub

**Comment by iccub** [comment]
fixed on latest build

**Comment by GeetaSarvadnya** [comment]
Verification passed on `iPad 7th Generation version iOS 15.1` running `Brave version 1.33 (21.12.2.18)`

https://user-images.githubusercontent.com/38657976/144559158-a3c9625d-09ed-4ed0-9c29-0440048879b3.MP4

----------------

Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.33 (21.12.7.21)`

* verified the STR/Cases outlined via https://github.com/brave/brave-ios/issues/4607#issue-1069714773

----------------

Verification **PASSED** on `iPhone 6+` running `iOS 14.6` using `1.33 (21.12.7.21)`

* verified the STR/Cases outlined via https://github.com/brave/brave-ios/issues/4607#issue-1069714773

**Comment by kjozwiak** [comment]
Created https://github.com/brave/brave-ios/issues/4652 when running through the above cases.
