### ISSUE TITLE
NTP intro popup message is shown when stats data is zero

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#4610]
### Description: 
Found while testing #4372
NTP intro popup message is shown when stats data is zero

### Steps to Reproduce 
   1. Clean profile 1.33 (21.12.2.15)
   2. Click on the `Skip` button in the 2nd welcome screen `Privacy made easy` slide
   3. NTP intro popup message is shown on NTP when stats data is zero

**Actual result:** 
NTP intro popup message is shown when stats data is zero

https://user-images.githubusercontent.com/38657976/144478638-93622d44-9d66-42f7-a9de-72d5bc0bc502.MP4

**Expected result:**
As per the spec the NTP intro message should be shown only when some stats data is collected in NTP

From spec - `The first time the user lands on the NTP and Brave stats have some data, this intro message is shown:`

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.33 (21.12.2.15)

**Device details:** 
iPas 7th Generation - iOS 15.1

**Website problems only:**
- did you check with Brave Shields down?NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T @soner-yuksel @iccub

**Comment by iccub** [comment]
closing, for now we decided to update the spec and to not handle this case
