### ISSUE TITLE
Better handle private key and recovery phrases when the user copies them

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4613]
### Description: 

We have copy buttons on the recovery phrase backup screens and the account private key screen, we should ensure that when this data is copied to the users pasteboard it is excluded from handoff and it expires after a given time (currently: 60s, but may change)

Pending investigation but: We should also clear the users pasteboard if they successfully import a secondary account with a private key

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33 (21.12.9.23)
- Verified steps from issue description
- Verified private key copied to clipboard is cleared after 60 secs
- Verified recovery seed copied to clipboard is cleared after 60 secs
- Verified copying a private key to clipboard and importing it as secondary account clears the clipboard after 60 secs
- Verified copying seed words to restore wallet clears the clipboard after 60 secs
- Verified copying random 12 words to clipboard doesn't clear it when trying to restore using it
-----------
Verification passed on iPhone XR with iOS 15.1 running 1.33 (21.12.9.23)
- Verified steps from issue description
- Verified private key copied to clipboard is cleared after 60 secs
- Verified recovery seed copied to clipboard is cleared after 60 secs
- Verified copying a private key to clipboard and importing it as secondary account clears the clipboard after 60 secs
- Verified copying seed words to restore wallet clears the clipboard after 60 secs
- Verified copying random 12 words to clipboard doesn't clear it when trying to restore using it
------------
Verification passed on iPad Pro with iOS 15.2 running 1.33 (21.12.9.23)
- Verified steps from issue description
- Verified private key copied to clipboard is cleared after 60 secs
- Verified recovery seed copied to clipboard is cleared after 60 secs
- Verified copying a private key to clipboard and importing it as secondary account clears the clipboard after 60 secs
- Verified copying seed words to restore wallet clears the clipboard after 60 secs
- Verified copying random 12 words to clipboard doesn't clear it when trying to restore using it
