### ISSUE TITLE
Add fee notice for swap

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4617]
We currently do not explicitly display the swap fees collected by Brave. This must be visible while presenting the quote to the user.

Above swap button after slip tolerance a note should be made about swap fees.

Copy is: `Quote includes a 0.875% Brave fee.`

Desktop: https://github.com/brave/brave-core/pull/11410

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.33(21.12.7.21)
- Verified there is a fee notice on swap screen

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.1) | iPad Pro (iOS 15.2)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/145264087-da6f0ed9-e7e4-4847-a21a-6ec911423cdc.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/145264125-69106f83-74aa-4a91-81cd-55909b1acc04.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/145264108-fa3f884c-36bf-44c5-9f4a-9019a0072452.png>
