### ISSUE TITLE
Add Price data powered by CoinGecko

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4618]
Add `Price data powered by CoinGecko` in the footer of the Asset Details screen

Desktop: https://github.com/brave/brave-core/pull/11078

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.33(21.12.7.21)
- Verified there is a notice about Price data provided by CoinGecko

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.1) | iPad Pro (iOS 15.2)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/145264473-7f2a6d6d-134c-443f-9890-d0a303dd3a00.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/145264451-9a59ae66-2606-43c8-9004-57d62da6bfcc.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/145264490-c7e22f7c-606e-46d8-99e8-fc018ebca8bd.png>
