### ISSUE TITLE
Update copy for X shields blocked popup

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4627]
Header: X trackers & ads blocked!
Body: Congrats on reaching this privacy milestone.
CTA: Share the news

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPad 7th Generation version iOS 15.1` running `Brave version 1.33 (21.12.6.21)`
- Encountered https://github.com/brave/brave-ios/issues/4645
- Encountered https://github.com/brave/brave-ios/issues/4655
- Logged https://github.com/brave/brave-ios/issues/4678

### US Region

<details>
<summary>1000 Trackers and Ads blocked popup_New user_PASSED</summary>

- Confirmed trackers and ads blocked tooltip is shown correctly when `1000 trackers and ads are blocked`
- Confirmed design of the `Trackers and ads blocked` tooltip is as per the spec doc
- Confirmed `Trackers and ads blocked` tooltip is white background as mentioned in the spec doc
- Confirmed click on `Share the news` opens up the share tool picker
- Confirmed stats can be shared via `Share the news`

Light theme | Share picker | Shared stats
--------|---------|------
![IMG_0155](https://user-images.githubusercontent.com/38657976/145070799-997080d1-b064-4cab-84a3-b8bccae75123.PNG) | ![IMG_0156](https://user-images.githubusercontent.com/38657976/145070939-d5a464c2-10ff-41e2-866a-f394fda6bbc3.PNG) | ![File (4)](https://user-images.githubusercontent.com/38657976/145071004-f582cf16-671c-4cf5-9e8a-3ed08afdd02f.jpg)
</details>

<details>
<summary>5000 Trackers and Ads blocked popup_New user_PASSED</summary>

- Confirmed trackers and ads blocked tooltip is shown correctly when `5000 trackers and ads are blocked` (encountered #4645)
- Confirmed design of the `Trackers and ads blocked` tooltip is as per the spec doc
- Confirmed `Trackers and ads blocked` tooltip is white background as mentioned in the spec doc
- Confirmed click on `Share the news` opens up the share tool picker
- Confirmed stats can be shared via `Share the news`
- Logged https://github.com/brave/brave-ios/issues/4645

Dark theme | Share picker | Shared stats
---------|------|-------
![IMG_0158](https://user-images.githubusercontent.com/38657976/145070842-4ea4d0f0-857e-451f-ad60-fbe7aea37d1b.PNG) | ![IMG_0159](https://user-images.githubusercontent.com/38657976/145071615-4943b6eb-2e25-4ec8-adaf-c0dcfc9e0135.PNG) | ![File](https://user-images.githubusercontent.com/38657976/145071728-f0551328-73fb-4bf1-b3dd-2236017b9267.jpg)
</details>


### JP Region

<details>
<summary>1000 Trackers and Ads blocked popup_New user_PASSED</summary>

- Confirmed trackers and ads blocked tooltip is shown correctly when `1000 trackers and ads are blocked`
- Confirmed design of the `Trackers and ads blocked` tooltip is as per the spec doc
- Confirmed `Trackers and ads blocked` tooltip is white as mentioned in the spec doc
- Confirmed click on `Share the news` opens up the share tool picker
- Confirmed stats can be shared via `Share the news`

Light theme | Dark theme | Share picker | Stats shared
--------|---------|------|----------
![IMG_0162](https://user-images.githubusercontent.com/38657976/145027039-50f2a562-f49d-4e7c-a5f6-49c971348165.PNG) | ![IMG_0160](https://user-images.githubusercontent.com/38657976/145027054-88985193-0fe7-462b-922a-d688529c7c98.PNG) | ![IMG_0161](https://user-images.githubusercontent.com/38657976/145072613-525df94f-d556-4653-9d05-05ad7018e2d1.PNG) | ![File (1)](https://user-images.githubusercontent.com/38657976/145027170-89e7127a-64d9-4329-9eb5-bc3a28602c59.jpg)

</details>

<details>
<summary>1000 Trackers and Ads blocked popup_Existing user</summary>

Encountered  https://github.com/brave/brave-ios/issues/4678
</details>

---------------

Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.33 (21.12.10.20)`

### US Region

<details>
<summary>1000 Trackers and Ads blocked popup (New User) - PASSED</summary>

- Confirmed trackers and ads blocked tooltip is shown correctly when `1000 trackers and ads are blocked`
- Confirmed design of the `Trackers and ads blocked` tooltip is as per the spec doc
- Confirmed `Trackers and ads blocked` tooltip is white background as mentioned in the spec doc
- Confirmed click on `Share the news` opens up the share tool picker
- Confirmed stats can be shared via `Share the news`
</details>

<details>
<summary>5000 Trackers and Ads blocked popup (New User) - PASSED</summary>

- Confirmed trackers and ads blocked tooltip is shown correctly when `5000 trackers and ads are blocked`
- Confirmed design of the `Trackers and ads blocked` tooltip is as per the spec doc
- Confirmed `Trackers and ads blocked` tooltip is white background as mentioned in the spec doc
- Confirmed click on `Share the news` opens up the share tool picker
- Confirmed stats can be shared via `Share the news`
</details>

### JP Region

<details>
<summary>1000 Trackers and Ads blocked popup (New User) - PASSED</summary>

- Confirmed trackers and ads blocked tooltip is shown correctly when `1000 trackers and ads are blocked`
- Confirmed design of the `Trackers and ads blocked` tooltip is as per the spec doc
- Confirmed `Trackers and ads blocked` tooltip is white as mentioned in the spec doc
- Confirmed click on `Share the news` opens up the share tool picker
- Confirmed stats can be shared via `Share the news`
</details>

<details>
<summary>1000 Trackers and Ads blocked popup (Existing user) - PASSED</summary>

* verifications completed via https://github.com/brave/brave-ios/issues/4678#issuecomment-990581843

</details>

---------------

Verification **PASSED** on `iPhone 6+` running `iOS 14.6` using `1.33 (21.12.10.20)`

### US Region

<details>
<summary>1000 Trackers and Ads blocked popup (New User) - PASSED</summary>

- Confirmed trackers and ads blocked tooltip is shown correctly when `1000 trackers and ads are blocked`
- Confirmed design of the `Trackers and ads blocked` tooltip is as per the spec doc
- Confirmed `Trackers and ads blocked` tooltip is white background as mentioned in the spec doc
- Confirmed click on `Share the news` opens up the share tool picker
- Confirmed stats can be shared via `Share the news`
</details>

<details>
<summary>5000 Trackers and Ads blocked popup (New User) - PASSED</summary>

- Confirmed trackers and ads blocked tooltip is shown correctly when `5000 trackers and ads are blocked`
- Confirmed design of the `Trackers and ads blocked` tooltip is as per the spec doc
- Confirmed `Trackers and ads blocked` tooltip is white background as mentioned in the spec doc
- Confirmed click on `Share the news` opens up the share tool picker
- Confirmed stats can be shared via `Share the news`
</details>

### JP Region

<details>
<summary>1000 Trackers and Ads blocked popup (New User) - PASSED</summary>

- Confirmed trackers and ads blocked tooltip is shown correctly when `1000 trackers and ads are blocked`
- Confirmed design of the `Trackers and ads blocked` tooltip is as per the spec doc
- Confirmed `Trackers and ads blocked` tooltip is white as mentioned in the spec doc
- Confirmed click on `Share the news` opens up the share tool picker
- Confirmed stats can be shared via `Share the news`
</details>

<details>
<summary>1000 Trackers and Ads blocked popup (Existing user) - PASSED</summary>

* verifications completed via https://github.com/brave/brave-ios/issues/4678#issuecomment-990581843

</details>
