### ISSUE TITLE
Favourites show low resolution icons for some sites

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#463]
### Description: 
Favourites show low resolution icons for some sites

### Steps to Reproduce 
  1. Visit https://quora in a new tab and add to favourites
  2. Open a new tab, shows low resolution image
  3. Add to bookmark, image doesn't look like low resolution because of small size

**Actual result:** 
![image from ios](https://user-images.githubusercontent.com/17010094/49147903-f8e99100-f32b-11e8-8ece-6b0b42da7696.png)

FF
![image from ios 1](https://user-images.githubusercontent.com/17010094/49147916-fdae4500-f32b-11e8-97ad-e541a01bb0f3.png)

**Expected result:**
Should look similar to FF 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.11.21.22)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by LaurenWags** [comment]
@jhreis some sites still show low res favicon, but it matches FF. Is this expected/ok? (see one below for Diablo III)
![Image from iOS](https://user-images.githubusercontent.com/28145373/54359569-5256a100-4639-11e9-8c96-1596e2006416.png)

**Comment by srirambv** [comment]
assume the site favicon itself is of low resolution. Is that why its so pixelated?

**Comment by srirambv** [comment]
Discussed with @jhreis regarding the issue. Moving to 1.10

**Comment by jhreis** [comment]
We have a partial fix for this in 1.9, but apparently it was not good enough, we have additional work on this too for 1.10.

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+ (iOS 12.3.1) running 1.10(19.07.08.19)
![File (1)](https://user-images.githubusercontent.com/17010094/60975109-5b126780-a2f9-11e9-9991-545d3b1fd61a.jpg)

* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.12.14)
![IMG_0B2BC62D62D1-1](https://user-images.githubusercontent.com/28145373/61149457-352ec380-a4af-11e9-92a6-0fd01ad597b6.jpeg)
