### ISSUE TITLE
Crash when dragging the rewards panel

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4631]
### Description: 
https://bravesoftware.slack.com/archives/C06UXF3KJ/p1638564762421400

> if I tap on the rewards icon and then drag the popup panel to rotate it, and then keep going beyond 45 degrees then it will hang/crash reliably 100% of the time.  Doesn’t happen with the Brave shields popup

Note: This crash may kill open tabs too - can you please double check.

**Comment by Uni-verse** [comment]
Verification completed on `iPhone 12 Pro` running `iOS 15.1.1` using build version `1.35 (22.1.21.14)`

**PASSED** - Tapping on rewards panel and dragging/rotating greater than 45 degrees does not cause crash - https://github.com/brave/brave-ios/issues/4631#issue-1070982889

https://user-images.githubusercontent.com/17885425/150597875-a3c7a362-82ba-454b-98a2-3c2d4c5c5a10.MP4

**Comment by Uni-verse** [comment]
Verification completed on `iPad (7th Gen)` running `iPadOS 14.4.2` using build version `1.35 (22.1.21.14)`

**PASSED** - Tapping on rewards panel and dragging/rotating greater than 45 degrees does not cause crash - https://github.com/brave/brave-ios/issues/4631#issue-1070982889
