### ISSUE TITLE
Unable to register fingerprint message but still allows to unlock wallet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4636]
### Description: 
Unable to register fingerprint message but still allows to unlock wallet

### Steps to Reproduce 
  1. Clean install TF build
  2. Enable Wallet, enter password
  3. Shows Enable fingerprint mesasge
  4. Click on enable, throws error
  5. Lock wallet and try to unlock, shows fingerprint message, allows to unlock 

**Actual result:** 

https://user-images.githubusercontent.com/17010094/144833121-80a389a9-0c39-4867-bcf3-089540ea66ab.MP4

**Expected result:**
Should not throw error 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.33(21.12.6.2)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
Note: Once you reset wallet and try to create again the biometric error doesn't show.

**Comment by kylehickinson** [comment]
Investigating led to finding that the is `errSecDuplicateItem` which is caused by setting up biometrics after deleting the app with the same password as you did in a prior install because keychain items persist even if you delete the app. Will add a check to remove the keychain entry if you install Brave and dont have a wallet created

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33(21.12.9.23)
- Verified resetting wallet and recreating it without closing doesn't show error when trying register biometric enrolment
-------------
Verification passed on iPhone XR with iOS 15.1 running 1.33(21.12.9.23)
- Verified resetting wallet and recreating it without closing doesn't show error when trying register biometric enrolment
------------
- Verification passed on iPad Pro with iOS 15.2 running 1.33(21.12.9.23)
- Verified resetting wallet and recreating it without closing doesn't show error when trying register biometric enrolment
