### ISSUE TITLE
Referral check confirmation is not shown for clean install leading to empty tiles on NTP

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#4637]
### Description: 
Found while testing https://github.com/brave/brave-ios/issues/4378
NTP top tiles are not shown when you have something copied in the clipboard

### Steps to Reproduce 
  1. Copy something in the clipboard
  2. Install the latest app 1.33 (21.12.6.2) from TF
  3. Skip or view the welcome onboarding flow
  4. NTP is blank, doesn't show any top tiles, due to onboarding flow, referral check might have broken

**Note:** Follow the same steps in-app store version 1.32 and observe top tiles are shown in the NTP

**Actual result:** 
NTP top tiles are not shown when you have something copied in the clipboard

**1.33**

https://user-images.githubusercontent.com/38657976/144834574-4153a21f-718a-4f2d-8c47-c4d655966654.MP4

**1.32**

https://user-images.githubusercontent.com/38657976/144834790-7f2f2ac3-acad-44c1-b8eb-99541c3b0819.MP4

**Expected result:**
Top tiles should be shown

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.33 (21.12.6.2)

**Device details:** 
iPad 7th Generation - iOS 15.1

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T @soner-yuksel @iccub

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPad 7th Generation version iOS 15.1` running `Brave version 1.33 (21.12.7.21)`
- Confirmed referral code check screen is shown when something is copied in the clipborad
- Confirmed NTP top tiles are shown when welcome onboarding flow skipped or viewed

https://user-images.githubusercontent.com/38657976/145162871-9f945e89-8e3e-4299-8847-727e577e94cb.MP4

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave Dev `1.33 (21.12.8.22)` on an iPhone 6s, iOS 15.0.2, and another iPhone 6s, iOS 14.4.2.

Confirmed I could dismiss all popovers
Confirmed the new-tab page had sites (`YouTube`, `Amazon`, `Wikipedia`, and `Twitter`) shown

14.4.2 | 15.0.2
-------|--------
<video src="https://user-images.githubusercontent.com/387249/145325910-471f169f-cd59-4b1b-a734-8f4409b2ccd6.MP4"> | <video src="https://user-images.githubusercontent.com/387249/145325929-e97addc0-638c-41ed-92e0-20a7fe11bde5.MP4">
