### ISSUE TITLE
Stats onboarding border is not dismissed when scrolled to Brave News

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4638]
### Description: 
Stats onboarding border is not dismissed when scrolled to Brave News

### Steps to Reproduce 
  1. Clean install build 1.33
  2. Skip onboarding and go to NTP, shows border on stats 
  3. Scroll down and enable Brave News
  4. Stats border is retained even on News. Try tapping inside the border to load news article doesn't work 

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/144840494-7385b0f3-716d-445a-b297-9b1ff737a4b8.png)

**Expected result:**
Dismiss the onboarding outlines when navigated away

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.33(21.12.6.2)

**Device details:** 
iPhone 7+ (iOS 14.8.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

**Comment by GeetaSarvadnya** [comment]
Not reproducible on iPhone 8 and iPad 7th Generation on the latest build of 1.33

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6+` running `iOS 14.6` using `1.33 (21.12.8.23)`

**`1.33(21.12.6.2)`** | **`1.33 (21.12.8.23)`**
----------------------|-------------------------
![IMG_0216](https://user-images.githubusercontent.com/2602313/145447164-d935eddb-2c57-4528-8bcb-364a1b387c8d.png) | ![IMG_0217](https://user-images.githubusercontent.com/2602313/145447207-4b2a6501-6b11-4b1f-885a-a5c89ac2db8f.png)
