### ISSUE TITLE
Ethereum address validation 

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#4641]
In Send Screen, users will be asked to input the `to` account address to send the crypto to.
We need some validation before enable the `Send` button to proceed the tx.
1. address cannot be the same account address as `from`
2. address cannot be contract address (need to iterate all tokens from TokenRegistery + user's assets)

Give a warning message if address is not valid. 

cc @jamesmudgett @bbondy these new copies will only be in English and we will order translation for the next release.

**Comment by srirambv** [comment]
Verification passed on iPhone XR7+ with iOS 14.8.1 running 1.33 (21.12.9.23)
- Verified when receiving address is same as sending an error is shown
- Verified when receiving address is token's contract address, error is shown

Same Address | Contract Address
-- | --
![image](https://user-images.githubusercontent.com/17010094/145547271-c579e01e-2b8d-4e2d-be65-2b135dc916b0.png) | ![image](https://user-images.githubusercontent.com/17010094/145547287-dffac563-f644-4f98-a67a-c2ff1494b686.png)

--------
Verification passed on iPhone XR with iOS 15.1 running 1.33 (21.12.9.23)
- Verified when receiving address is same as sending an error is shown
- Verified when receiving address is token's contract address, error is shown

Same Address | Contract Address
-- | --
![image](https://user-images.githubusercontent.com/17010094/145547365-223abfd8-07dc-4808-9b40-6677c71fa6bf.png) | ![image](https://user-images.githubusercontent.com/17010094/145547417-7350d85a-89f7-40c7-a6bc-ab1aad3bb105.png)

--------
Verification passed on iPad Pro with iOS 15.2 running 1.33 (21.12.9.23)
- Verified when receiving address is same as sending an error is shown
- Verified when receiving address is token's contract address, error is shown

Same Address | Contract Address
-- | --
![image](https://user-images.githubusercontent.com/17010094/145547553-55fa811f-1d56-475f-a455-bc5955d99416.png) | ![image](https://user-images.githubusercontent.com/17010094/145547575-413118fb-df04-44da-99c1-74d5a1b5d8bd.png)
