### ISSUE TITLE
Hide private elements during screen recording and alert user when screenshot is taken on private screens

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4643]
### Recording

- Start recording your screen
- Verify on backup recovery phrase flow that words are not visible
- Verify on account private key screen that key is hidden while recording
- End recording
- Verify screens appear as normal
- If possible repeat while AirPlaying screen to a different device (TV/Mac/QuickTime/etc.)

### Screenshots

- Visit backup screen
- Take a screenshot
- Verify alert appears on the screen telling the user that their recovery key may have been leaked to a cloud service
- Repeat on account private key screen

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33(21.12.9.19)
- Verified seed words are hidden when screen recording is started
- Verified when a screenshot is taken a warning message is shown to delete the screenshot
- Verified this happens on back up seed screen, verify seed screen and view private key screen

Screenshot on `Your recovery phrase` | Screenshot on `Your recovery phrase` | Screenshot on Private Key | Screen recording on `Your recovery phrase` | Screen recording on `Verify recovery phrase` | Screen recording on `Private Key`
-- | -- | -- | -- | -- | -- |
![image](https://user-images.githubusercontent.com/17010094/145514091-1128b5cc-bc5f-44ae-b40f-415b3819b3e8.png) | ![image](https://user-images.githubusercontent.com/17010094/145514105-2bec236f-2fb0-4597-af9d-49e8db57025c.png) | ![image](https://user-images.githubusercontent.com/17010094/145514153-de2d2ac0-4584-4085-aad4-d8f99c7cd3a8.png) | ![image](https://user-images.githubusercontent.com/17010094/145514178-503dbd05-261b-468a-828e-adcedec02aab.png) | ![image](https://user-images.githubusercontent.com/17010094/145514195-c3bf3665-fc0e-4c0f-8720-11fd51d3dc17.png) | ![image](https://user-images.githubusercontent.com/17010094/145514165-6a5102a5-493f-4057-9876-8fa0f9a8cd53.png)

--------------
Verification passed on iPhone XR with iOS 15.1 running 1.33(21.12.9.19)
- Verified seed words are hidden when screen recording is started
- Verified when a screenshot is taken a warning message is shown to delete the screenshot
- Verified this happens on back up seed screen, verify seed screen and view private key screen

Screenshot on `Your recovery phrase` | Screenshot on `Your recovery phrase` | Screenshot on Private Key | Screen recording on `Your recovery phrase` | Screen recording on `Verify recovery phrase` | Screen recording on `Private Key`
-- | -- | -- | -- | -- | -- |
![image](https://user-images.githubusercontent.com/17010094/145513628-1f889c7e-7fc2-4632-8cb1-0a065386ceca.png) | ![image](https://user-images.githubusercontent.com/17010094/145513637-51d68924-2b5a-44f7-b1dd-308bf7777c5c.png) | ![image](https://user-images.githubusercontent.com/17010094/145513690-5374cbe7-c99a-40a5-9c02-e264dba36044.png) | ![image](https://user-images.githubusercontent.com/17010094/145513741-ca1bb56c-d19f-4264-b25e-9257ea678ecf.png) | ![image](https://user-images.githubusercontent.com/17010094/145513758-e436b478-56cb-4792-8c62-8b8e71d42dfd.png) | ![image](https://user-images.githubusercontent.com/17010094/145513720-459c5017-7c97-44a7-a80e-a1f4fd3f73c1.png)

--------------
Verification passed on iPad Pro with iOS 15.2 running 1.33(21.12.9.19)
- Verified seed words are hidden when screen recording is started
- Verified when a screenshot is taken a warning message is shown to delete the screenshot
- Verified this happens on back up seed screen, verify seed screen and view private key screen

Screenshot on `Your recovery phrase` | Screenshot on `Your recovery phrase` | Screenshot on Private Key | Screen recording on `Your recovery phrase` | Screen recording on `Verify recovery phrase` | Screen recording on `Private Key`
-- | -- | -- | -- | -- | -- |
![image](https://user-images.githubusercontent.com/17010094/145514546-f6e38619-5342-4582-ba51-a785b88b701a.png) | ![image](https://user-images.githubusercontent.com/17010094/145514585-a0f3510c-5363-450c-be05-1b93f77dbfd3.png) | ![image](https://user-images.githubusercontent.com/17010094/145514632-52b3a649-1c06-4a5d-9615-72e450edaaae.png) | ![image](https://user-images.githubusercontent.com/17010094/145514642-ef1eadcc-30a0-41e1-a5d6-adc474636148.png) | ![image](https://user-images.githubusercontent.com/17010094/145514657-57028a6e-e835-466e-89c5-1074dbf497a5.png) | ![image](https://user-images.githubusercontent.com/17010094/145514672-596cd9f7-3c07-4ed0-b6a1-9a4d4874348d.png)
