### ISSUE TITLE
browser crashing when moving/editing or adding `Favorites` via NTP

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4651]
### Description: 

When either editing/adding or drag & dropping favorite tiles on `iOS 14`, brave will crash instantly. This is 100% reproducible on `iOS 14` only. Crashes aren't present in `iOS 15`. Found while running through https://github.com/brave/brave-ios/issues/4463. This also happens if you go into `Show More` and attempt to move around any of the `Favorites` in that view as well.

Crash Stack --> [Client-2021-12-07-164357.ips.beta.txt](https://github.com/brave/brave-ios/files/7671780/Client-2021-12-07-164357.ips.beta.txt)

### Steps to Reproduce
 
  1. install `1.33 (21.12.6.21)` via TF
  2. Skip onboarding and dismiss the modal popups re: Shields/Settings
  3. move around any of the `Favorites` under NTP (instant crash)
  4. edit and try saving any `Favorite` tile under NTP (instant crash)
  5. adding a new `Favorite` (instant crash)

**Actual result:** 

Crash Stack --> [Client-2021-12-07-164357.ips.beta.txt](https://github.com/brave/brave-ios/files/7671780/Client-2021-12-07-164357.ips.beta.txt)

**Expected result:**

Browser shouldn't be crashing when interacting with NTP tiles on `iOS 14`

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible following the STR/Cases mentioned above.

**Brave Version:** 

* `1.33 (21.12.6.21)` 

**Device details:** 

* `iPhone 12` running `iOS 15.1.1` - **`Couldn't reproduce/working as expected`**
* `iPhone 6+` running `iOS 14.6` - **`Crashes instantly whenever moving Favorites`**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @bsclifton @anthonypkeane @Brandon-T @kylehickinson @soner-yuksel

**Comment by kjozwiak** [comment]
Once the above is fixed, we'll need to run through the cases mentioned in https://github.com/brave/brave-ios/issues/4463#issuecomment-988289255 as well. However, if a solution can't be found, it sounds like we'll disable the ability to move the `Favorites` via NTP on `iOS 14` which means the test cases will differ.

**Comment by soner-yuksel** [comment]
Temporary change for Issue #4651 - Disabling Favourites ordering for iOS 14 until next Release (1.34) in PR-[4657](https://github.com/brave/brave-ios/pull/4657)

**Comment by kjozwiak** [comment]
> Temporary change for Issue #4651 - Disabling Favourites ordering for iOS 14 until next Release (1.34) in PR-[4657](https://github.com/brave/brave-ios/pull/4657)

Moving this into `1.34.x` as QA will run through https://github.com/brave/brave-ios/issues/4685 on `1.33` to make sure the ability to move NTP tiles has been disabled on `iOS 14` and still works on `iOS 15`.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6+` running `iOS 14.6` using `1.33 (21.12.10.20)`

* ensured that you can't move around favorite tiles under NTP
* ensured that you can't move around favorite tiles under the `Favorite` section when tapping on the URL bar
* ensured that any attempt on moving tiles doesn't cause any issues/crashes or obvious regressions
* ensured that you can still `Edit` & `Remove` tiles without any issues
* ensured that you can still `Add` favorite tiles without any issues
