### ISSUE TITLE
NTP onboarding message is not shown when clipboard check is done on clean install

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#4653]
### Description: 
Found while testing https://github.com/brave/brave-ios/issues/4637

NTP onboarding message is not shown when clipboard check is done on clean install

### Steps to Reproduce 
  1. Copy something in the clipboard
  2. Install the latest build `1.33 (21.12.7.21)`
  3. Confirm Referral code check screen is presented
  4. Click on `Skip` in any slide in the onboarding flow
  5. NTP is opened
  6. NTP doesn't show NTP intro message, opening a new NTP will show NTP intro message

**Note:** This occurs only in the copy clipboard scenario, without copy clipboard if the user skip the onboarding flow, the NTP intro message is shown in the opened NTP

**Actual result:** 
NTP intro message is not shown in an opened NTP

https://user-images.githubusercontent.com/38657976/145166604-b63fec8e-89f6-42dd-862a-d972da3b2cb6.MP4

**Expected result:**

NTP intro message should be shown in an opened NTP
**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.33 (21.12.7.21)

**Device details:** 

iPad 7th Generation - iOS 15.1
**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information

cc: @Brandon-T @soner-yuksel @iccub

**Comment by GeetaSarvadnya** [comment]
This issue persists for JP region also.

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.33 (21.12.8.23)`
* Verification **PASSED** on `iPhone 6+` running `iOS 14.6` using `1.33 (21.12.8.23)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.1` using `1.33 (21.12.8.23)`

Using the STR/Cases mentioned via https://github.com/brave/brave-ios/issues/4653#issue-1074097797, ensured that:

* ensured that the NTP on-boarding is displayed when a user taps on `Allow one-time clipboard check` and skips on-boarding.
* ensured that the NTP on-boarding is displayed when a user taps on `Do not allow this check` and skips on-boarding.
