### ISSUE TITLE
After upgrade unable to pass through the referral code check

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#4655]
### Description: 
 After upgrade unable to pass the referral code check

Looks like this issue got introduced after fixing the issue https://github.com/brave/brave-ios/issues/4637

### Steps to Reproduce 

  1. Copy something in the clipboard
  2. Clean profile `1.32.3 (21.11.17.19)`
  3. `Anonymous referral code check` popup screen is displayed
  4. Clicked on `Allow one-time clipboard check`
  5. Popup is dismissed and NTP is opened
  6. Upgrade to `1.33 (21.12.7.21)`
  7. `Anonymous referral code check` popup screen is displayed
  8. Click on `Allow one-time clipboard check` or `Do not allow this check` - nothing happens, the popup is not dismissed
  9. The popup is not going away it remained as is on the screen 

**Actual result:** 

After upgrade unable to pass through the referral code check

https://user-images.githubusercontent.com/38657976/145216902-5993c474-7a49-45db-85fd-0ba690c01d1a.MP4

**Expected result:**

The popup should be dismissed
**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
 `1.33 (21.12.7.21)`

**Device details:** 

iPad 7th Generation - iOS 15.1
**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T @soner-yuksel @iccub

**Comment by kjozwiak** [comment]
Went through the STR/Cases outlined via https://github.com/brave/brave-ios/issues/4655#issue-1074422254 and ensured that the clipboard permission isn't being displayed after upgrading. I also ensured that both `Allow one-time clipboard` and `Do not allow this check` cases worked.

* Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.33 (21.12.8.23)`
* Verification **PASSED** on `iPhone 6+` running `iOS 14.6` using `1.33 (21.12.8.23)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.1` using `1.33 (21.12.8.23)`
