### ISSUE TITLE
Move wallet to features section on NTP and add beta label

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4659]

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.33 (21.12.9.17)
- Verified Wallet is moved into the features section on NTP and reads `Wallet (Beta)`

iPhone 7+ (iOS 14.8) | iPhone XR (iOS 15.1) | iPad Pro (iOS 15.2)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/145463138-e082ca05-911e-446e-91cf-8389f1fee188.png> | <img width=240 src=https://user-images.githubusercontent.com/17010094/145463156-2fbe8213-5708-49c6-bb1e-6a36cd85d9b6.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/145463182-1e8dceef-1730-4742-adf3-956766e14318.png>
