### ISSUE TITLE
Cookie controls migration sets wrong values

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#466]
STR:

1. Install brave1.6.6
2. Set cookie control to some value
3. Upgrade to 1.7

Cookie setting will be wrong, for example
Block all cookies on 1.6 converts to don't block cookies
Don't block cookies on 1.6 converts to block 3rd party cookies
etc.

Looks like enum values are different between codebases

**Comment by kylehickinson** [comment]
1.7 uses the actual `HTTPCookie.AcceptPolicy` raw values when saving/reading from `UserDefaults` however it looks like 1.6 set their own values for each one in a mapping. I'll fix the migration so it uses the appropriate mapping :)
