### ISSUE TITLE
iOS <--> iOS sync won't complete

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#4662]
### Description: 

Sync will not work in scenario below. 

### Steps to Reproduce 

From Cross-timezone tests (see https://github.com/brave/internal/issues/832#issuecomment-973471650)
1. Setup iOS device 1 on the Los Angeles timezone.
2. Setup iOS device 2 on the Auckland (NZ) timezone.
3. Create a Sync chain on iOS 1.
4. Attempt to join the Sync chain on iOS 2 (it should WORK but it does not).
5. Reset both iOS profiles.
6. Create Sync chain on iOS 2.
7. Attempt to join the Sync chain on iOS 1 (it should WORK but it does not).

 iOS device 1 was iPhone 6s Plus w/ iOS 15 and iOS device 2 is iPad 5th Gen w/ iOS 14.

**Actual result:** 
Sync will not work 

**Expected result:**
Should work

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.33 (21.12.7.21) on both

**Device details:** 
iOS device 1 was iPhone 6s Plus w/ iOS 15 and iOS device 2 is iPad 5th Gen w/ iOS 14

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc @brave/legacy_qa 

reproduced by @stephendonner

**Comment by stephendonner** [comment]
Reproduced this too.

For the failure in step 4, `Attempt to join the Sync chain on iOS 2 (it should WORK but it does not)`, I get this: `Unable to create new sync group.  Expired`

For the failure in step 7, `Attempt to join the Sync chain on iOS 1 (it should WORK but it does not).`, I get this: `Unable to create new sync group.  Too New`

step 4 | step 7
-------|------
![Image from iOS (2)](https://user-images.githubusercontent.com/387249/145248678-35fd8901-321b-4ded-9abb-e04d5e498c1c.png) | ![Image from iOS (3)](https://user-images.githubusercontent.com/387249/145248856-2bba38da-999f-4feb-a200-10ab57434e53.png)

Device 1: iPhone 6s, iOS 15.0.2
Device 2: iPhone 6s, iOS 14.4.2

Both were running `1.33 (21.12.7.21)`

**Comment by kjozwiak** [comment]
hmm seems like @Brandon-T @soner-yuksel and myself can't reproduce the above but we should figure out why @stephendonner & @LaurenWags are having issues. I basically ran through the STR/Cases outlined via https://github.com/brave/brave-ios/issues/4662#issue-1074607426 as per the following:

* changed the time zone on `iPhone 6s+` running `14.6` and downloaded/installed `1.33.x (21.21.7.21)` via TF (Device A)
* changed the time zone on `iPhone 12` running `15.1.1` and downloaded/installed `1.33.x (21.21.7.21)` via TF (Device B)
* created a new sync profile with Device A and ensured that the QR code was visible
* added Device B by scanning the visible QR code that's visible on Device A

**Comment by LaurenWags** [comment]
Device reboot for both @stephendonner and I seems to have solved this problem. Closing as we are unable to reproduce.

Additional notes from @Brandon-T that could be helpful: 

```
Note: When changing times on iOS, you must dismiss the keyboard for the time to take effect. Also, you must kill the app and restart it, because the app doesn’t see the newly set time or time-zone.
```
