### ISSUE TITLE
Wallet doesn't auto-lock after continued app usage 

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4669]
### Steps to Reproduce 
  1. Unlock wallet
  2. Leave wallet
  3. Use the app for longer than your auto-lock setting is set to

**Actual result:** 
Wallet is unlocked

**Expected result:**
Wallet should be locked

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.1 running 1.33(21.12.9.17)
- Verified steps from issue description
- Verified wallet is auto-locked when the auto-lock time has passed even when browser is being used
---------
Verification passed on iPad Pro with iOS 15.2 running 1.33(21.12.9.17)
- Verified steps from issue description
- Verified wallet is auto-locked when the auto-lock time has passed even when browser is being used
---------
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33(21.12.9.23)
- Verified steps from issue description
- Verified wallet is auto-locked when the auto-lock time has passed even when browser is being used
