### ISSUE TITLE
Japan NTP tutorial page is being set as active tab when skipping on-boarding

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4672]
### Description: 

When skipping the new onboarding flow while on the Japan locale, the https://brave.com/ja/ntp-tutorial page is opened and made active which means the user doesn't see a NTP and won't see the initial on-boarding modals via the NTP until they open a new tab.

### Steps to Reproduce
 
  1. download/install `1.33 (21.12.7.21)` via TF (ensure Region/Language is set to `Japan` before launching Brave)
  2. skip the on-boarding and you'll notice that https://brave.com/ja/ntp-tutorial is set as the active tab rather than a NTP

**Actual result:** 

https://brave.com/ja/ntp-tutorial is being set as the active tab when skipping on-boarding rather than the NTP

**Expected result:**

NTP page should be opened as the active tab so the user see's the on-boarding modals and https://brave.com/ja/ntp-tutorial should be opened in the background.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases mentioned below.

**Brave Version:** 

* `1.33 (21.12.7.21)`

**Device details:** 

`iPhone 12` running `iOS 15.1.1` - **Couldn't reproduce**
`iPhone 6+` running `iOS 14.6` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @anthonypkeane @kylehickinson @soner-yuksel @Brandon-T

**Comment by soner-yuksel** [comment]
Cant reproduce this, It is working as expected. @kjozwiak 

https://user-images.githubusercontent.com/6643505/145286043-bc090562-08f2-4496-9d42-7447c85e13cb.mp4

**Comment by kjozwiak** [comment]
Removing from `1.34` as it's not a high priority issue. @aekeus and team can decide prioritization 👍

**Comment by soner-yuksel** [comment]
With new onboarding the problem still persists but it actually persists for all iOS versions and actually the NTP tutorial page for Japan is not shown at all.

**Comment by kjozwiak** [comment]
@soner-yuksel looks like we're missing a milestone. Assuming this should go into `1.43.x`?

**Comment by soner-yuksel** [comment]
@kjozwiak yes thats is correct it should go 1.43.

**Comment by Uni-verse** [comment]
Verified using `1.43 (22.9.8.13)`

Test Devices:
iPhone 12 Pro & XR | iOS 15.5
iPad (7th Gen) | iOS 15.5
iPhone X | iOS 14.4.2

Testing based on STR in https://github.com/brave/brave-ios/issues/4672#issue-1074808865

Scenario: 

1. Install app version 1.43 via TF  
2. Set region and language to `Japan` in device system settings
3. Launch Brave
4. Skip on-boarding and ensured `New Tab Page` is the active tab

- Verified NTP is the `active tab` when launching brave with Japan locale (set before first launch)
- Verified Tool tips are displayed
- Verified ` https://brave.com/ja/ntp-tutorial` is opened in the background. 

iPhone 12 (Japan first launch)

https://user-images.githubusercontent.com/17885425/189201302-352b84ab-0ea5-41d2-8d0a-39bd020fc951.MP4


iPad (Japan first launch)

Example | Example | Example | Example
-|-|-|-
![IMG_0546](https://user-images.githubusercontent.com/17885425/189200224-b6966859-75bf-4b8e-b6ef-e643eaa79e06.PNG) | ![IMG_0547](https://user-images.githubusercontent.com/17885425/189200251-c8c7ccad-2fff-45c4-8dc3-b49e3d855513.PNG) | ![IMG_0548](https://user-images.githubusercontent.com/17885425/189200265-b8fa11c9-5414-4fe7-83be-c8e39acdebb1.PNG) | ![IMG_0549](https://user-images.githubusercontent.com/17885425/189200285-cc077ec3-ef0e-4462-bc21-45302acd9db8.PNG)
