### ISSUE TITLE
can't bypass the clipboard permission screen when there's something in clipboard

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4675]
### Description: 

Looks like `1.33 (21.12.8.21)` regressed the clipboard permission screen. If you have something within the clipboard, Brave will warn the user and ask for permission to check and see if we can find a referral code. However, both `Allow one-time clipboard check` & `Do not allow this check` buttons are not working so there's no way to get past the screen.

### Steps to Reproduce

  1. copy some random text on iOS so there's something via the clipboard
  2. install `1.33 (21.12.8.21)`  via TF
  3. launch Brave and you should get the clipboard permission screen

**Actual result:** 

Notice that you can't get past the screen and the  `Allow one-time clipboard check` & `Do not allow this check` buttons are not working.

**Expected result:**

Should be able to use both the `Allow one-time clipboard check` & `Do not allow this check` buttons to pass the screen and continue with the onboarding experience.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases mentioned above.

**Brave Version:** 

* `1.33 (21.12.8.21)`

**Device details:** 

* `iPhone 12` running `iOS 15.1.1` - **Reproduced**
* `iPhone 6+` running `iOS 14.6` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @anthonypkeane @bsclifton @kylehickinson @Brandon-T

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.33 (21.12.8.23)`
* Verification **PASSED** on `iPhone 6+` running `iOS 14.6` using `1.33 (21.12.8.23)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.1` using `1.33 (21.12.8.23)`

STR/Cases used for verification:

* ensured that the clipboard permission screen doesn't appear if there's nothing in the clipboard
* ensured that the clipboard permission screen appears when there's something copied via the clipboard
* ensured that both `Allow one-time clipboard check` & `Do not allow this check` are working correctly and dismiss the screen
* ensured that the `Brave pasted from` modal appears at the top when selecting `Allow one-time clipboard check`

**Comment by TD540** [comment]
Is this issue fixed? Because I'm still having the same trouble with the clipboard permission screen (development branch `5e58edf82f0fccf738d62bca9ec91320b2eebea7`)

```
2021-12-13 00:40:13.684 [Info] [UserReferralProgram.swift:152] pingIfEnoughTimePassed() > Could not retrieve download id model from preferences.
2021-12-13 00:40:13.756100+0100 Client[22480:550760] [boringssl] boringssl_metrics_log_metric_block_invoke(144) Failed to log metrics
2021-12-13 00:40:13.772 [Debug] [NTPDownloader.swift:151] getNTPResource(for:_:) > NTPDownloader Cache is still valid
```

**Comment by Brandon-T** [comment]
It is fixed.
In release builds you will not be stuck. If you're testing development, you need to disable the onboarding skipping, which doesn't happen in release.

So it's 100% fixed.
