### ISSUE TITLE
Trackers and ads blocked tooltips are not shown in an upgraded profile for both JP and US regions

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#4678]
### Description: 

Found while testing https://github.com/brave/brave-ios/issues/4627

Trackers and ads blocked tooltips are not shown in an upgraded profile for both JP and US regions
### Steps to Reproduce 
  
**Scenario 1: US region**
 
  1. Clean profile 1.32 (app store version)
  2. Upgrade the profile to 1.33 (TF latest version)
  3. Open cnn.com and reload until 1000 trackers and ads blocked in NTP
  4. Make sure CNN is the active tab
  5. Quit brave (kill the app and relaunch)
  6. 1000+ trackers and ads blocked popup is not shown
  
**Scenario 2: US region**
 
  1. Clean profile 1.32 (app store version)
  2. View all the education popups
       - Tap on amazon.com top tile in NTP and ensure the `Trackers and ads blocked...` popup is shown
       - Quit brave
       - Open youtube.com and confirm `Ads blocked while watching videos...` popup is shown
       - Quit brave
       - Open cnn.com and ensure the `10+ trackers and ads blocked...` popup is shown
  2. Upgrade the profile to 1.33 (TF latest version)
  3. Open cnn.com and reload page until 1000 trackers and ads blocked in NTP
  4. Make sure CNN is the active tab
  5. Quit brave
  6. 1000+ trackers and ads blocked popup is not shown

**Scenario 3: JP region**

 1. Clean profile 1.32 (app store version)
  2. View all the education popups
       - Tap on amazon.com top tile in NTP and ensure the `Trackers and ads blocked...` popup is shown
       - Quit brave
       - Open youtube.com and confirm `Ads blocked while watching videos...` popup is shown
       - Quit brave
       - Open cnn.com and ensure the `10+ trackers and ads blocked...` popup is shown
  3. Open cnn.com and reload the page until 900+ trackers and ads blocked in NTP
  4. Upgrade the profile to 1.33 (TF latest version)
  5. Reload cnn.com and ensure 1000+ trackers and ads are blocked in NTP (add another 100+ trackers 1.33)
  6. Make sure cnn.com is the active tab
  7. Quit brave
  8.1000+ trackers and ads blocked popup is not shown

**Scenario 4: JP region**

  1. Clean install 1.32 for JP region
  2. Collect 400+ trackers
  3. Quit brave (kill app and relaunch)
  4. 10+ trackers and ads blocked popup is shown
  5. Collect trackers up to 900+
  6. Upgrade the profile to 1.33
  7. Collect the trackers to 1000+
  8. Repeat step 3
  9. Not getting 1000+ trackers and ads blocked popup
  10. Collect the trackers up to 5000+
  11. Repeat step 3
  12. Not getting 5000+ trackers and ads blocked

  
**Actual result:** 

Trackers and ads blocked tooltips are not shown in an upgraded profile for both JP and US regions
**Expected result:**
Trackers and ads blocked tooltip should be shown once the threshold is reached

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 

1.33 (21.12.8.23)
**Device details:** 

iPad 7th Generation - iOS 15.1
**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T @soner-yuksel @iccub

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.33 (21.12.9.23)`
  * **`Scenario 1: US region`** - `PASSED` using STR/Cases from https://github.com/brave/brave-ios/issues/4678#issue-1075433183
  * **`Scenario 2: US region`** - `PASSED` using STR/Cases from https://github.com/brave/brave-ios/issues/4678#issue-1075433183
  * **`Scenario 3: JP region`** - `PASSED` using STR/Cases from https://github.com/brave/brave-ios/issues/4678#issue-1075433183
  * **`Scenario 4: JP region`** - `PASSED` using STR/Cases from https://github.com/brave/brave-ios/issues/4678#issue-1075433183

------

* Verification **PASSED** on `iPhone 6+` running `iOS 14.6` using `1.33 (21.12.9.23)`
  * **`Scenario 1: US region`** - `PASSED` using STR/Cases from https://github.com/brave/brave-ios/issues/4678#issue-1075433183
  * **`Scenario 2: US region`** - `PASSED` using STR/Cases from https://github.com/brave/brave-ios/issues/4678#issue-1075433183
  * **`Scenario 3: JP region`** - `PASSED` using STR/Cases from https://github.com/brave/brave-ios/issues/4678#issue-1075433183
  * **`Scenario 4: JP region`** - `PASSED` using STR/Cases from https://github.com/brave/brave-ios/issues/4678#issue-1075433183

------
Verification **PASSED** on `iPad 7th Generation version iOS 15.1` running `Brave version 1.33 (21.12.10.17)`
- Verified all 4 cases and confirmed scenarios are working as expected.
