### ISSUE TITLE
Migration in private browsing mode crashes on rule compilation.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#468]
### Steps to Reproduce 
  1. Install brave1.6.6
  2. Enable private browsing only in settings
  3. Upgrade to 1.7

The app crashes on launch. Relaunching the app doesn't help

Some error logs I got
```
Content Rule List compiling failed: Moving file failed.
Content Rule List compiling failed: Moving file failed.
Content Rule List compiling failed: Moving file failed.
2018-11-28 12:57:26.914 [Error] [ContentBlockerHelper.swift:72] compile(ruleStore:) > Content blocker 'upgrade-http' errored: The operation couldn’t be completed. (WKErrorDomain error 6.)
(lldb) po error
Error Domain=WKErrorDomain Code=6 "(null)" UserInfo={NSHelpAnchor=Rule list compilation failed: Unspecified error during compile.}
```

**Comment by kylehickinson** [comment]
Seems to only occur when setting private browsing only on 1.6 FIRST. If I set it in 1.7 and restart everything's fine… Will continue investigation…

**Comment by iccub** [comment]
It also doesn't happen when you change PBM default preference in 1.7 to true and then run it

**Comment by kylehickinson** [comment]
Those errors come straight from WebKit, but not sure what's causing it yet: https://github.com/WebKit/webkit/blob/master/Source/WebKit/UIProcess/API/APIContentRuleListStore.cpp#L363

**Comment by kylehickinson** [comment]
This is due to the file system lock in place in 1.6 when private browsing is enabled [here](https://github.com/brave/browser-ios/blob/development/brave/src/webview/PrivateBrowsing.swift#L35).

I assume 1.7 will have to unlock these directories during migration
