### ISSUE TITLE
VPN callout is not happening after 4 days

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#4682]
### Description: 
Found while testing https://github.com/brave/brave-ios/issues/4373
Vpn callout after 4 days is not working as expected
### Steps to Reproduce 
  1. Clean profile 1.33
  2. Skip the onboarding flow
  3. Dismiss the NTP intro messages
  4. Kill the app 
  5. Set the device date ahead by 4 days if it's production build install
  6. Relaunch app
  7. Vpn callout is not happening

**Actual result:** 
Vpn callout is not happening

**Expected result:**
Vpn callout should happen after 4 days

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 

1.33 (21.12.8.23)
**Device details:** 
iPad 7th Generation - iOS 15.1

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T @soner-yuksel @iccub

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.33 (21.12.9.23)` on an iPhone 6s running iOS `15.0.2` and another iPhone 6s running iOS `14.4.2`.

iOS 14.4.2 | iOS 15.0.2
------------|------------
<video src="https://user-images.githubusercontent.com/387249/145502972-66b5af3e-8477-4fee-8311-3316a2de444d.MP4"> | <video src="https://user-images.githubusercontent.com/387249/145503020-a80fd134-45d8-4fbe-bf6b-0edb7acd1a19.MP4">

----------------------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.1` using `1.33 (21.12.9.23)`

![image](https://user-images.githubusercontent.com/2602313/145509927-68af9b13-6007-412d-8d2d-2ffbea38dfc3.png)
