### ISSUE TITLE
Race condition allows on-screen keyboard to pre-empt onboarding tour

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#4684]
### Description: 
Race condition allows on-screen keyboard to pre-empt onboarding tour

### Steps to Reproduce 
1. install `1.33 (21.12.8.23)`
2. launch Brave
3. on the `Privacy made easy` screen, tap on `Skip` at the bottom
4. (timing on this is pretty difficult) now, tap on the URL bar, to bring up the on-screen keyboard
5. look at the screen

**Actual result:** 

![Image from iOS (7)](https://user-images.githubusercontent.com/387249/145448017-da763fc2-dc77-4e93-8600-e3a80073ec3e.png)

https://user-images.githubusercontent.com/387249/145448046-094e9b72-e1c3-4c4f-9053-ad3bad4a11ce.MP4

**Expected result:**
![Image from iOS (8)](https://user-images.githubusercontent.com/387249/145448451-81cec04a-4703-456b-8f55-b78ed9716409.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Very intermittent - timing-dependent, for sure

**Brave Version:** 
`1.33 (21.12.8.23)`

**Device details:** 
iPhone 6s, iOS 14.4.2

**Comment by soner-yuksel** [comment]
Onboarding is totally changed so the steps to produce this ticket is changed with it.

Right now the Privacy Hub NTP alert is being shown on a different time but same can be produced when alert is shown on the screen.

**Comment by Uni-verse** [comment]
Verified using `1.43 (22.9.8.13)`

Unable to reproduce on the following devices after many attempts:

Test Devices:
iPhone 12 Pro & XR | iOS 15.5
iPad (7th Gen) | iOS 15.5
iPhone X | iOS 14.4.2

- Verified tapping on the URL bar after onboarding doesn't enable the modal to get stuck.
