### ISSUE TITLE
disable the ability to move NTP `Favorite` tiles on `iOS 14`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4685]
### Description: 

Due to https://github.com/brave/brave-ios/issues/4651 and the complexity required to fix the issue in time, it was decided to disable the ability to move around `Favorite` tiles on the NTP for `iOS 14` devices.

### Steps to Reproduce

* see https://github.com/brave/brave-ios/issues/4651 STR that caused the crash
* ensure that you can't move around `Favorite` tiles under NTP
* ensure that you can still move around tiles under the `Favorite` section once you tap on the URL

**Actual result:** 

Brave crashing whenever attempting to move around the NTP Favorite tiles on `iOS 14`

**Expected result:**

Disabled the ability to move around tiles under NTP. Crash will be fixed at a later time via https://github.com/brave/brave-ios/issues/4651.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases mentioned above.

**Brave Version:** 

* `1.33 (21.12.6.21)` 

**Device details:** 

* `iPhone 12` running `iOS 15.1.1` - **`Couldn't reproduce/working as expected`**
* `iPhone 6+` running `iOS 14.6` - **`Crashes instantly whenever moving Favorites`**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

**Comment by kjozwiak** [comment]
Fixed as per https://github.com/brave/brave-ios/issues/4651#issuecomment-988978983. Closing.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6+` running `iOS 14.6` using `1.33 (21.12.8.23)`

* ensured that you can't move around favorite tiles under NTP
* ensured that you can't move around favorite tiles under the `Favorite` section when tapping on the URL bar
* ensured that any attempt on moving tiles doesn't cause any issues/crashes or obvious regressions
* ensured that you can still `Edit` & `Remove` tiles without any issues
* ensured that you can still `Add` favorite tiles without any issues

**Comment by kjozwiak** [comment]
Quick note: still running into https://github.com/brave/brave-ios/issues/4651 while I was QAing the above. Sounds like @Brandon-T found a cause that's related to some widget code that wasn't removed from `1.33`. Once removed, we'll re-enable drag & dropping as well as that will address the crashes we've been seeing.

**Comment by soner-yuksel** [comment]
Ability to Drag and drop for Favourites in iOS 14 is added back with this PR https://github.com/brave/brave-ios/pull/4692 which was merged in 1.33.
and the disabled widgets are added back with this Issue https://github.com/brave/brave-ios/issues/4582
