### ISSUE TITLE
Fail to swap low allowance ERC20 token after activation

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#4686]
### Steps to Reproduce 
  1. Have some DAI or USDC on Ropsten make sure they are low allowance (i believe they are initially with allowance $0.00)
  2. Try to swap between these two. You will see the swap button will be something like `Activate token DAI`
  3. Click the `Activate token XXX` 

**Actual result:** 
Nothing happened 

**Expected result:**
Swapped screen should be dismissed and Confirmation panel of this tx will be brought up.
After confirm this tx. It should appears in the Tx lists under that account with the correct status.

**Reproduces how often:** [Easily reproduced]

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.1 running 1.33 (21.12.9.23)
- Verified `Activate Token XXX` is shown
- Verified selecting activate token bring up approve transaction screen
- Verified able to submit approval transaction 

Activate Token | Approve Transaction
-- | --
![image](https://user-images.githubusercontent.com/17010094/145567488-91f66278-d71c-4113-bd1f-4e3fb64d89ce.png) | ![image](https://user-images.githubusercontent.com/17010094/145567430-2dd70f93-e373-44d5-81ae-5f0c280fba37.png)

----------
Verification passed on iPad Pro with iOS 15.2 running 1.33 (21.12.9.23)
- Verified `Activate Token XXX` is shown
- Verified selecting activate token bring up approve transaction screen
- Verified able to submit approval transaction 

Activate Token | Approve Transaction
-- | --
![image](https://user-images.githubusercontent.com/17010094/145567341-bb1c2b0e-f2dd-4ea9-8f3e-0868e0f56bd4.png) | ![image](https://user-images.githubusercontent.com/17010094/145567381-bfba94c0-1580-4573-9b3d-0c08e8f49d6c.png)
