### ISSUE TITLE
BAT/rewards icon appears greyed out when dismissing on-boarding via skip

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4693]
### Description: 

When launching the rewards on-boarding by tapping on the rewards panel, skipping on-boarding will make the BAT icon appear greyed out. However easily recovers/returns to the expected state when either refreshing the page or tapping on the BAT icon again.

### Steps to Reproduce

  1. download/install `1.33 (21.12.9.19)`
  2. skip the initial on-boarding during first launch and dismiss the on-boarding modals via NTP
  3. load a random website
  4. tap on the rewards panel and tap on `Skip`

You'll notice the BAT icon looks greyed out.

**Actual result:** 

![image](https://user-images.githubusercontent.com/2602313/145484206-6941b8f6-4f81-4a2c-9d81-8ca31a708266.png)

**Expected result:**

![image](https://user-images.githubusercontent.com/2602313/145484262-c9887d72-e89c-403b-bd7b-3956b19b8d35.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases mentioned above.

**Brave Version:** 

* `1.33 (21.12.9.19)`

**Device details:** 

* `iPhone 12` running `iOS 15.1.1` using `1.33 (21.12.9.19)` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @bsclifton @anthonypkeane @kylehickinson

**Comment by kjozwiak** [comment]
Still reproducible via `1.33 (21.12.9.23)` using the STR/Cases outlined via https://github.com/brave/brave-ios/issues/4693#issue-1076111629.

**Comment by Uni-verse** [comment]
Verification completed using `1.35 (22.1.24.16)`

**PASSED** on `iPhone 12` running `iOS 15.1.1`
**PASSED** on  `iPhone X` running `iOS 14.4.2` tested on build version `1.35 (22.1.24.23)`

- Verified when user skips through the onboarding modal that the brave rewards icon is not greyed out.
- Verified brave icon appears in information state when skipping onboarding screens.  
- Verified user is able to use rewards

iPhone 12 | iPhone X
-|-
![IMG_2373](https://user-images.githubusercontent.com/17885425/150879278-3ce162d4-45e7-47a0-8fa1-0374660abd60.jpg) | ![IMG_2581](https://user-images.githubusercontent.com/17885425/151062451-8ce65ef2-a496-4714-b077-99a5b9293399.PNG)


----------------

Verification **PASSED** on `iPhone 11` running `iOS 14.7.1` using `1.35 (22.1.24.23)`

* verified the STR/Cases outlined via https://github.com/brave/brave-ios/issues/4693#issue-1076111629
* ensured that the rewards icon doesn't appear greyed out when enable rewards

**`Example`** | **`Example`** | **`Example`** 
---------------|-----------------|----------------
![IMG_3769](https://user-images.githubusercontent.com/2602313/150920620-0d43dd14-8d3b-4ff6-9a1d-f7af4f2a240c.jpg) | ![IMG_3770](https://user-images.githubusercontent.com/2602313/150920628-f5e402f7-ceaf-4e2e-8ef6-210b32dfc147.jpg) | ![IMG_3771](https://user-images.githubusercontent.com/2602313/150920633-e9518082-4445-42e2-8aff-ece1986327cf.jpg)

----------------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.2` using `1.35 (22.1.24.23)`

* verified the STR/Cases outlined via https://github.com/brave/brave-ios/issues/4693#issue-1076111629
* ensured that the rewards icon doesn't appear greyed out when enable rewards

**`Example`** | **`Example`** | **`Example`** 
---------------|-----------------|----------------
![image](https://user-images.githubusercontent.com/2602313/150921376-67e95cb0-bbb6-47ec-93c8-ced2e0510516.png) | ![IMG_0353](https://user-images.githubusercontent.com/2602313/150921439-647f6bbf-7384-4c79-97c9-40fbb261d120.jpg) | ![IMG_0354](https://user-images.githubusercontent.com/2602313/150921460-26f25a92-2339-4880-9581-418e1fc01119.jpg)
