### ISSUE TITLE
Set settings panel to dark when PB mode is switched on

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#470]
### Description: 
Set settings panel to dark when PB mode is switched on

### Steps to Reproduce 
  1. Open a Private tab or switch on PB only
  2. Open settings
  3. Enjoy (not really) the black and white contrast 

**Actual result:** 
![file](https://user-images.githubusercontent.com/17010094/49151160-2850cb80-f335-11e8-8da2-907d25180eac.jpg)

**Expected result:**
Something similar to the PB colour scheme

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.11.21.22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
cc: @jamesmudgett @bradleyrichter for mockups

**Comment by kylehickinson** [comment]
No longer valid, bookmark menu has changed with proper dark mode
