### ISSUE TITLE
Browser crash when edit visible assets is selected resulting in wallet reset 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4701]
### Description: 
Browser crash when edit visible assets is selected

### Steps to Reproduce 
  1. Create wallet
  2. Click on `Edit Visible Assets`
  3. Browser crash

**Actual result:** 

https://user-images.githubusercontent.com/17010094/145541123-8e608108-2301-4973-bd8d-945e98329e7f.MP4

**Expected result:**
No crash when selecting edit tokens and definitely not resetting wallet because of crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.33 (21.12.9.23)

**Device details:** 
iPhone 7+ (iOS 14.8.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
No crash on iOS 15 devices

**Comment by srirambv** [comment]
Note: 
1. Wallet is not reset if there a transaction on the account (reject is also fine)
2. Browser crashes whenever you try to open asset list even on send/swap screen selecting token list crashes browser

**Comment by kylehickinson** [comment]
Turns out this is a crash due to compiling the code with Xcode 13.2 so I am going to close it and ask you to verify on the next build which will _not_ be using Xcode 13.2

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.33 (21.12.10.17)
- Verified selecting edit visible assets on portfolio screen doesn't crash the browser
- Verified selecting send transaction and selecting token list doesn't crash the browser
- Verified selecting search assets on swap screen doesn't crash the browser
