### ISSUE TITLE
new onboarding needs translations

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#4703]
### Description: 
While testing https://github.com/brave/brave-ios/issues/4378, noticed that the new onboarding doesn't have translations. 

### Steps to Reproduce 
  1. Set device to another language (I used region = Japan, language = Japanese)
  2. Clean install 1.33
  3. View onboarding

**Actual result:** 

Onboarding is in English

Example | Example | Example
----- | ----- | -----
![IMG_0028](https://user-images.githubusercontent.com/28145373/145580901-dd0a4647-fabb-467f-9b7a-965cf58b6f04.PNG) | ![IMG_0029](https://user-images.githubusercontent.com/28145373/145580912-4d9dc7e7-8ff5-4fc3-98e3-047045dea59b.PNG) | ![IMG_0030](https://user-images.githubusercontent.com/28145373/145580927-2a7106ba-84df-4ad8-a4f5-f61b13d1d8a3.PNG)

**Expected result:**

Onboarding to be in the language selected, in this case, Japanese

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.33 (21.12.9.23)

**Device details:** 
all

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc @brave/legacy_qa

**Comment by srirambv** [comment]
Translations are not yet done please check once https://github.com/brave/brave-ios/issues/4632 is merged
