### ISSUE TITLE
Per domain shield block settings are not migrated

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#471]
### Steps to Reproduce 
  1. Install brave1.6.6
  2. Open arstechnica.com, turn off ads blocking
  3. Upgrade to 1.7
  4. Go to arstechnica.com

Notice that shields are toggled on

**Comment by jhreis** [comment]
Since domain settings are handled in CD, most likely it is just pointing to wrong CD instance. Related to PR #414

**Comment by iccub** [comment]
It points to correct db, but looks like there's some bug in 1.6, even on 1.6 all shields in Domain can be nil, yet it still somehow works, I'm still looking at it
