### ISSUE TITLE
Crash on NTP Stats Onboarding

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#4716]
### Description: 
Fixing Crash by Nuo: xcode://organizer/crashes/downloadPoint?adamId=1052879175

### Steps to Reproduce 
  1. Launch app 
  2. Go through onboaring
  3. Get to NTP stats onboarding and do NOT dismiss
  4. Kill app.
  5. Repeat all steps above in order.

### Result
- Crash on NTP stats onboarding (extremely hard to reproduce)

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.33 (21.12.10.20)`
* Verification **PASSED** on `iPhone 6+` running `iOS 14.6` using `1.33 (21.12.10.20)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.1` using `1.33 (21.12.10.20)`

STR/Cases used for the above devices/iOS versions:

* re-launched Brave ~40 times while the NTP was opened and ensured Brave didn't crash
