### ISSUE TITLE
tab count displays infinity when over 99 tabs opened

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#472]
### Description: 
If you open 99 tabs, tab count reads 99. Once you get to 100, tab count switches to infinity symbol.

### Steps to Reproduce 
  1. Open 99 tabs. Note tab count.
  2. Open one more tab.
  3.

**Actual result:** 
Tab count now says infinity.
![screen shot 2018-11-27 at 5 16 59 pm](https://user-images.githubusercontent.com/28145373/49156450-66c19880-f2eb-11e8-9202-67e381ee7d2d.png)

**Expected result:**
Tab count should accurately reflect number of opened tabs.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.7(18.11.21.22)

**Device details:** 
iPad

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
This is intentional behavior, no room to show 3 characters there.
