### ISSUE TITLE
VPN callout-card positioning is incorrect in Japan region

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#4721]
### Description: 

VPN callout-card positioning is incorrect in Japan region

Cross-referenced issues:
* https://github.com/brave/brave-ios/issues/4719

### Steps:

0. set iOS `region` setting to `Japan`, and restart the phone
1. install `Brave` `1.33 (21.12.10.20)` or later, from TestFlight
2. launch Brave
3. confirm you get the `Privacy made easy` screen
4. tap `Let's go`
5. tap the Kanji below the `Set as default` button
6. tap on the very bottom Kanji on the next screen
7. tap to dismiss the Shields onboarding tour slide
8. tap to dismiss the bottom `All set!` tour slide
9. force-quit Brave
10. go to the `Date & Time` screen under `Settings` -> `General`
11. toggle `Set Automatically` to `OFF`
12. choose a date 10+ days from now (I usually use 12)
13. force-quit the `Settings` (`Date & Time`) app
14. re-launch Brave
15. note the order of the callouts:

`Default browser` -> `Rewards` -> `Sync` -> `VPN`

I believe per discussion with @GeetaSarvadnya in Japan region it should still be:

`VPN` -> `Default browser` -> `Rewards` -> `Sync`

run #1 | run #2
-------|-------
<video src="https://user-images.githubusercontent.com/387249/145710818-c2eaa43e-829e-453f-92d7-8ada019cea23.MP4"> | <video src="https://user-images.githubusercontent.com/387249/145710843-c16b89b9-177c-42f8-8634-c60680c319c2.MP4">

Actual Results:

The VPN callout comes last (or sometimes 2nd), but never first

Expected Results:

I believe per all specs/discussions/issues I've seen, the VPN callout is supposed to be first

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 
Brave `1.33 (21.12.10.20)`

**Device details:** 
iPhone 6s (iOS 14.4.2)

cc @GeetaSarvadnya @soner-yuksel @Brandon-T @anthonypkeane

**Comment by GeetaSarvadnya** [comment]
As per the slack thread explanation, closing the issue https://bravesoftware.slack.com/archives/C06UXF3KJ/p1639415370235300?thread_ts=1639310900.218900&cid=C06UXF3KJ
