### ISSUE TITLE
Back up your crypto wallet content message isn't translated in FR, JP and DE locales

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#4724]
### Description: 
Found while testing https://github.com/brave/brave-ios/issues/4632
Back up your crypto wallet content message isn't translated in FR, JP and DE localess
### Steps to Reproduce 
  1. NA
  2.
  3.

**Actual result:** 

![IMG_0263](https://user-images.githubusercontent.com/38657976/145788315-801ab305-90a9-47ae-8879-f4579829fa18.PNG)

**Expected result:**
Back up your crypto wallet content message should be translated in FR and DE locales

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Easy
**Brave Version:** 
1.33 (21.12.13.3)

**Device details:** 
iPad 7th Generation - iOS 15.1

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @kylehickinson @Brandon-T @srirambv @soner-yuksel

**Comment by soner-yuksel** [comment]
@nuo-xu Can you take a look at this ?

**Comment by kjozwiak** [comment]
Quick example of Japan not being translated as I ran into this last night while running through https://github.com/brave/brave-ios/issues/4715 👍 

![145758621-f4d2b021-512c-4d0e-8bf7-33dc695b0f98](https://user-images.githubusercontent.com/2602313/145853077-c4fb8684-3c8e-4236-b4c1-5d387eb622b5.png)

**Comment by nuo-xu** [comment]
This translation is missing. It will need to be ordered and added in the next release.

**Comment by kylehickinson** [comment]
Fixed by #4831

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6s+` running `iOS 14.6` using the following build:

```
1.34 (22.1.10.19)
```

* Verified the STR/Cases mentioned via https://github.com/brave/brave-ios/issues/4724#issue-1078295536.

**`Korean`** | **`Swedish`**
--------------|---------------------
![IMG_0258](https://user-images.githubusercontent.com/2602313/148878882-c27655e2-d369-490f-b050-cd156eb38fa7.png) | ![IMG_0259](https://user-images.githubusercontent.com/2602313/148878885-7ca42433-139d-4a9e-9ed9-882c280529b0.png)

-------

Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using the following build:

```
1.34 (22.1.10.19)
```

* Verified the STR/Cases mentioned via https://github.com/brave/brave-ios/issues/4724#issue-1078295536.

**`Russian`** | **`Portuguese`**
--------------|---------------------
![IMG_0512](https://user-images.githubusercontent.com/2602313/148878007-24d580e3-3ee8-4cf1-98ae-19c77c9d765b.png) | ![IMG_0513](https://user-images.githubusercontent.com/2602313/148878032-fc38dc5e-711c-46b8-b214-b4efeb54dd47.png)

-------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.1.1` using the following build:

```
1.34 (22.1.10.19)
```

**`Italian`** | **`German`**
--------------|---------------------
![IMG_0337](https://user-images.githubusercontent.com/2602313/148879557-d52877c5-bd5c-48af-afe4-8fefa1cc9c1e.png) | ![IMG_0338](https://user-images.githubusercontent.com/2602313/148879560-fd9edd39-0057-4f81-ba35-71d745a195d2.png)
