### ISSUE TITLE
Cancel string isn't translated in DE, JP and FR locales

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#4725]
### Description: 

Cancel string isn't translated in DE, JP and FR locales

### Steps to Reproduce 
  1. NA
 
**Actual result:** 
![IMG_0269](https://user-images.githubusercontent.com/38657976/145811416-d1fc39ec-d378-44ca-ac3d-e0489562dd32.PNG)
![IMG_0268](https://user-images.githubusercontent.com/38657976/145811429-4931a2a4-83af-453b-aeaf-346cb5520de4.PNG)
![IMG_0270](https://user-images.githubusercontent.com/38657976/145811446-642b77f8-dd61-4be6-bbd8-3eb16d7b756d.PNG)

**Expected result:**
Cancel string should be translated in DE and FR locales

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Easy
**Brave Version:** 
1.33 (21.12.13.3)

**Device details:** 
iPad 7th Generation - iOS 15.1

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @kylehickinson @Brandon-T @srirambv @soner-yuksel

**Comment by soner-yuksel** [comment]
@nuo-xu Can you look at this ?

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPad 7th Generation version iOS 15.1` running `Brave version 1.33 (21.12.14.16)`

**_Germany DE_**
Example | Example | Example
----|----|-----
![IMG_0292](https://user-images.githubusercontent.com/38657976/146053604-7702d78d-e27c-48ca-abc6-27344d9ecf35.PNG) | ![IMG_0290](https://user-images.githubusercontent.com/38657976/146053620-54c75b9b-cc3b-425b-9f2b-137c205339b0.PNG) | ![IMG_0289](https://user-images.githubusercontent.com/38657976/146053636-7eef3927-ceda-424b-a80f-8646a04f3819.PNG)

**_France FR_**
Example | Example | Example
----|----|-----
![IMG_0294](https://user-images.githubusercontent.com/38657976/146053412-8e7ae497-85ec-48f2-a8c8-0d2f2d238856.PNG) | ![IMG_0295](https://user-images.githubusercontent.com/38657976/146053443-4b905ae9-4ff7-4a7e-8b11-da67f6b84308.PNG) | ![IMG_0293](https://user-images.githubusercontent.com/38657976/146053456-701e5f4f-56ff-4da1-ab8a-87378f54599e.PNG)

**_Japan JP_**
Example | Example | Example
----|----|-----
![IMG_0298](https://user-images.githubusercontent.com/38657976/146053164-8730dd64-2705-40e6-a386-a336de4ad0b5.PNG) | ![IMG_0297](https://user-images.githubusercontent.com/38657976/146053184-26042a02-3839-435d-857e-de331c39f5b5.PNG) | ![IMG_0296](https://user-images.githubusercontent.com/38657976/146053207-082f3bc8-10eb-4d63-a61a-eca043d8a713.PNG)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.33 (21.12.14.16)`

**`German`**

Example | Example | Example
----|----|-----
![IMG_0491](https://user-images.githubusercontent.com/2602313/146088180-53ddb06b-70b6-42a6-97b1-ae1a274b7fd1.png) | ![IMG_0495](https://user-images.githubusercontent.com/2602313/146088183-0933b77d-2b2c-4af7-a94f-cfc96fd89f88.png) | ![IMG_0496](https://user-images.githubusercontent.com/2602313/146088184-83b1486c-f3ff-4f8a-8fa5-da4cc024da52.png)

**`French`**

Example | Example | Example
----|----|-----
![IMG_0492](https://user-images.githubusercontent.com/2602313/146088328-31a84f2d-8089-4832-8aef-7304f8aae179.png) | ![IMG_0493](https://user-images.githubusercontent.com/2602313/146088329-66055a69-fa82-4570-b753-9ab6835f3740.png) | ![IMG_0494](https://user-images.githubusercontent.com/2602313/146088330-45bac75d-782e-4626-8438-c6f56c762ab6.png)

**`Japanese`**

Example | Example | Example
----|----|-----
![IMG_0497](https://user-images.githubusercontent.com/2602313/146088668-e0cb7ffe-952e-4c4d-a370-88d0e9267951.png) | ![IMG_0498](https://user-images.githubusercontent.com/2602313/146088672-17aefc56-e210-4e41-b25d-933fef119055.png) | ![IMG_0499](https://user-images.githubusercontent.com/2602313/146088673-733d9299-3548-4c23-8e57-df9f2028f63a.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 6+` running `iOS 14.6` using `1.33 (21.12.14.16)`

**`German`**

Example | Example | Example
----|----|-----
![IMG_0240](https://user-images.githubusercontent.com/2602313/146090545-5268a58e-000f-44b8-a247-9729a08cc1d5.png) | ![IMG_0239](https://user-images.githubusercontent.com/2602313/146090546-12d8f9c3-dff0-4906-964f-02a04b084db8.png) | ![IMG_0238](https://user-images.githubusercontent.com/2602313/146090548-a0c3110c-166a-4e29-99bc-f904cc63ece3.png)

**`French`**

Example | Example | Example
----|----|-----
![IMG_0243](https://user-images.githubusercontent.com/2602313/146090498-1374a6fc-4f6c-453c-bbc7-2beda20e01fa.png) | ![IMG_0242](https://user-images.githubusercontent.com/2602313/146090499-9ddbd610-e854-4260-aaee-ba16479db7e2.png) | ![IMG_0241](https://user-images.githubusercontent.com/2602313/146090500-52771456-dcab-4db4-aec4-45252c0e14c4.png)


**`Japanese`**

Example | Example | Example
----|----|-----
![IMG_0246](https://user-images.githubusercontent.com/2602313/146090450-462b1dfe-abb5-40b1-8788-2b4ff27b9c16.png) | ![IMG_0245](https://user-images.githubusercontent.com/2602313/146090451-820e628d-ddcb-4c05-8ae2-e79a69102b72.png) | ![IMG_0244](https://user-images.githubusercontent.com/2602313/146090452-f25deabb-35df-4fbb-b73d-279d3208e9b2.png)
