### ISSUE TITLE
screenshot detected modal under backup words not translated

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4727]
### Description: 

The modal that warns users that they're about to take a screenshot of the backup words isn't translated.

### Steps to Reproduce
 
  1. download/install `1.33 (21.12.13.3)` (or any build that has Brave Wallet)
  2. run through the setup and attempt to take a screenshot when the backup words are shown/generated

**Actual result:** 

![IMG_0236](https://user-images.githubusercontent.com/2602313/145855009-5ab9a25f-35f9-4d9a-be3a-351babdd6589.png)

**Expected result:**

Example text should be translated.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases outlined above.

**Brave Version:** 

* `1.33 (21.12.13.3)` (or any version that has Brave Wallet)

**Device details:** 

* `iPhone 12` running `iOS 15.1.1` - **Reproduced**
* `iPhone 6+` running `iOS 14.6` - **Reproduced**
* `iPad Air (3rd Gen)` running `iOS 15.1` - **Reproduced**

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @iccub @anthonypkeane @bsclifton @kylehickinson

**Comment by kylehickinson** [comment]
Fixed by #4831

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using the following build:

```
1.34 (22.1.10.19)
```

* Verified the STR/Cases mentioned via https://github.com/brave/brave-ios/issues/4727#issue-1078765049.

**`Japan`** | **`German`**
------------|----------------
![IMG_0509](https://user-images.githubusercontent.com/2602313/148862468-20777b8b-1985-4032-9a0c-4dd81ee5ca93.png) | ![IMG_0511](https://user-images.githubusercontent.com/2602313/148862473-8e25f10c-e535-4f3e-a755-bb6a89c3025b.png)

-----------

Verification **PASSED** on `iPhone 6s+` running `iOS 14.6` using the following build:

```
1.34 (22.1.10.19)
```

* Verified the STR/Cases mentioned via https://github.com/brave/brave-ios/issues/4727#issue-1078765049.

**`French`** | **`Spanish`**
------------|----------------
![IMG_0257](https://user-images.githubusercontent.com/2602313/148863202-f08a7e03-54c7-4018-a1f2-2b32475e4d54.png) | ![IMG_0255](https://user-images.githubusercontent.com/2602313/148863210-d6ae40e9-a4c7-4000-81b3-cabfba6ded2b.png)

-----------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.1.1` using the following build:

```
1.34 (22.1.10.19)
```

* Verified the STR/Cases mentioned via https://github.com/brave/brave-ios/issues/4727#issue-1078765049.

**`Chinese (Traditional)`** | **`Polish`**
------------|----------------
![IMG_0334](https://user-images.githubusercontent.com/2602313/148863749-aa05c7c3-c0c3-46af-a3a1-601d92199fcf.png) | ![IMG_0336](https://user-images.githubusercontent.com/2602313/148863757-dec36c35-173c-4a59-8399-a7b7b4dcc593.png)
