### ISSUE TITLE
Long button text in Spanish is unreadable

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#4732]
### Description: 

Long button text in Spanish is unreadable

### Steps to Reproduce 
  1. install `1.33 (21.12.13.3)`
  2. switch to a Spanish-speaking locale (language) in iOS
  3. launch Brave
  4. go through the onboarding tour until you see the translated `Make Brave your default browser` screen
  5. look at the button strings for `Set as default`

**Actual result:** 

![145875417-6c1b61e5-8eb6-4824-8d1b-a5c46958eb8b (1)](https://user-images.githubusercontent.com/387249/145939538-fc4015db-fdcc-4818-ab2c-a621982d55d1.png)

**Expected result:**

The button text should fit inside the button, whether it's via a translation/copy change, or multi-line buttons

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
`1.33 (21.12.13.3)`

**Device details:** 
iPhone 6s, iOS 14.4.2 and 15.0.2

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.35 (22.1.24.23)`
* Verification **PASSED** on `iPhone 11` running `iOS 14.7.1` using `1.35 (22.1.24.23)`
* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.2` using `1.35 (22.1.24.23)`

**`iPhone 12 iOS 15.1.1`** | **`iPhone 11 iOS 14.7.1`** | **`iPad Air (3rd Gen) iOS 15.2`**
-----------------------------|-----------------------------|------------------------------------
![IMG_0535](https://user-images.githubusercontent.com/2602313/150893068-853af72d-fa2f-4cef-854c-3a848b260a9e.png) | ![IMG_3768](https://user-images.githubusercontent.com/2602313/150893071-2e49d1cd-33f7-406e-96c1-55eece2d1c29.png) | ![IMG_0351](https://user-images.githubusercontent.com/2602313/150893075-87674aae-49c5-4a34-9101-007690f1ec5d.png)
