### ISSUE TITLE
global Shields defaults should read Shields global defaults in Brave Shields' panel

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#4740]
### Description: 

`global Shields defaults` should read `Shields global defaults` in Brave Shields' panel

### Steps to Reproduce 
  1. install `1.33 (21.12.15.2)`
  2. launch Brave
  3. breeze through onboarding
  4. tap on the 3-dots menu icon on the bottom-right toolbar
  5. tap on `Settings`
  6. load a site like `tmz.com`
  7. tap on the Brave Shields icon
  8. in the resulting doorhanger dialog, look at the bottom, under `GLOBAL CONTROLS`
  9. tap on `Change global Shields default`
  10. look at the heading `BRAVE SHIELDS GLOBAL DEFAULTS` in the resulting screen

**Actual result:** 

on the 1st screen, it reads `... global Shields defaults`

![Image from iOS (2)](https://user-images.githubusercontent.com/387249/146324351-81ba5b2d-38be-4bde-bf3c-17f3cf41be94.png)

**Expected result:**

Word order: `Shields global defaults`

![Image from iOS (3)](https://user-images.githubusercontent.com/387249/146324379-4b1059cb-27ce-4aef-b6d6-c382b0fef7a4.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.49 (23.3.15.17)
- Verified steps from [#7065](https://github.com/brave/brave-ios/pull/7065)
- Verified `Change global Shields default` now reads `Change Shields Global Defaults`
- Verified `Advanced controls` now read `Advanced Controls`

iPhone 7+ (iOS 15.7.3) | iPhone XR (iOS 16.3.1) | iPad Pro (16.4 Beta 2)
-- | -- | -- 
<img width=300 src=https://user-images.githubusercontent.com/17010094/225568920-e7109ac7-a84e-48df-96e9-8505dc82769c.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/225568893-a4a6bf9a-6e3b-42b6-9cb4-7a8bac8ef3d8.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/225569209-2c76c23c-e0bc-46a6-84ac-2c576270b883.png>
