### ISSUE TITLE
Add extra validation of ETH address in send

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#4744]
### Description: 
Same as Desktop ref: https://github.com/brave/brave-browser/issues/19532

In Ethereum an address casing is used as a checksum for validation. We should check this and if it fails give an error.

If an input address matches the API result for KeyringController's GetChecksumEthAddress then don't give a warning
If an address has each alphabetic character as lowercase, give a warning that the address has no checksum information and might be invalid.
If an address has each alphabetic character as uppercase, give a warning that the address has no checksum information and might be invalid.
If an address has both lowercase and uppercase alphabetic characters, and it doesn't match the checksum address, give an error and don't allow the user to send.

API available in  v1.35.30 and above

**Comment by srirambv** [comment]
<table>
      <tr colspan="4">Verification passed on the following devices running <code>1.38 (22.4.25.21)<br></code></tr>
 <tr><br>
   </tr>
   <tr>
      <th>
      </th>
      <th>:ballot_box_with_check: iPhone 7+ (iOS 14.8.1)</th>
      <th>:ballot_box_with_check: iPhone XR (iOS 15.4.1)</th>
      <th>:ballot_box_with_check: iPad Pro (iOS 15.5 Beta)</th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-ios/pull/5275>#5275</a></li>
         <li>Verified address validation happens for same address/checksum/contract/invalid address</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Invalid ETH Address
      </td>
      <td><img width=400 src=https://user-images.githubusercontent.com/17010094/165743917-b655b659-10be-4efa-81f8-ef308b02f995.png>
      </td>
      <td><img width=320 src=https://user-images.githubusercontent.com/17010094/165744768-01095b3b-202b-4042-acb3-044d3f0a9af7.png>
      </td>
      <td><img width=580 src=https://user-images.githubusercontent.com/17010094/165744183-6b147075-a286-4b37-a0b1-34837cb23bc3.png>
      </td>
   </tr>
   <tr>
      <td>Invalid Checksum
      </td>
      <td><img width=400 src=https://user-images.githubusercontent.com/17010094/165745029-07d18d27-cb45-45d8-9dc2-ccac15364f5f.png>
      </td>
      <td><img width=320 src=https://user-images.githubusercontent.com/17010094/165744984-60c84bfd-c231-4888-be02-eb8c4d49bc0b.png>
      </td>
      <td><img width=580 src=https://user-images.githubusercontent.com/17010094/165745089-ff112d00-ce48-4817-b063-931624881666.png>
      </td>
   </tr>
   <tr>
      <td>Invalid Checksum (lower/upper case)
      </td>
      <td><img width=400 src=https://user-images.githubusercontent.com/17010094/165745374-3ab498a3-7bcb-45af-a839-2e56a21701f2.png>
      </td>
      <td><img width=320 src=https://user-images.githubusercontent.com/17010094/165745641-b203cddd-61d4-438f-a9be-c906bae2d632.png>
      </td>
      <td><img width=580 src=https://user-images.githubusercontent.com/17010094/165745170-0dd2acc7-92c0-47eb-a40b-add1c8845e74.png>
      </td>
   </tr>
   <tr>
      <td>Own Address
      </td>
      <td><img width=400 src=https://user-images.githubusercontent.com/17010094/165745479-bbad7045-5a81-4bc5-b470-d54abf11c3c0.png>
      </td>
      <td><img width=320 src=https://user-images.githubusercontent.com/17010094/165745559-2cc0de27-8c36-4322-bc7c-444a46b8a4d1.png>
      </td>
      <td><img width=580 src=https://user-images.githubusercontent.com/17010094/165745232-7a308f81-bfef-47a5-93dd-114500c13c38.png>
      </td>
   </tr>
   <tr>
      <td>Contract Address
      </td>
      <td><img width=400 src=https://user-images.githubusercontent.com/17010094/165745434-415dddbc-674e-4203-ba70-b2fc2ec60046.png>
      </td>
      <td><img width=320 src=https://user-images.githubusercontent.com/17010094/165745582-a0625ebd-89bf-41b5-9c40-7c6d26f34d91.png>
      </td>
      <td><img width=580 src=https://user-images.githubusercontent.com/17010094/165745213-060bead3-e002-4715-9af8-d0dab8a45117.png>
      </td>
   </tr>
</table>
