### ISSUE TITLE
Add prefill in Add Custom Token when user inputs token contract address

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#4745]
Align with Desktop did ref: https://github.com/brave/brave-core/pull/11589

### Description: 

Wired up `GetTokenInfo` API to the Add Custom Token UI

Built a useTokenInfo hook that can be reused through out the wallet front end to find tokenInfo by contract address.
Will first check a users visibleTokens, then fallback to the fullTokenList and then fallback to the new getTokenInfo API from Etherscan
First implementation for this hook is now being used in the Add Custom Token ui, in the Edit Visible Assets modal.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.36 (22.2.23.20)
- Verified steps from [#4974](https://github.com/brave/brave-ios/pull/4974)
- Verified on mainnet, pasting contract address auto-populates the token details and adds it when submitted
- Verified on mainnet, re-adding the the custom token that is already added shows an error message
- Verified on other network, adding a custom token doesn't autofill as its not available in the default token list
- Verified on other network, adding a custom token and then trying to re-add the same token auto-populates the fields but shows error when trying to re-add it 
- Encountered [#5019](https://github.com/brave/brave-ios/issues/5019)

Scenario 1 & 3 | Scenario 2 & 3
-- | --
<video src=https://user-images.githubusercontent.com/17010094/155478424-ad4cacb8-7cae-4874-91b6-2063d5be07a1.MP4> | <video src=https://user-images.githubusercontent.com/17010094/155478655-1dddf6f2-2a2c-4a36-b8ae-ff24812b9dba.MP4>

--------------
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.36 (22.2.23.20)
- Verified steps from [#4974](https://github.com/brave/brave-ios/pull/4974)
- Verified on mainnet, pasting contract address auto-populates the token details and adds it when submitted
- Verified on mainnet, re-adding the the custom token that is already added shows an error message
- Verified on other network, adding a custom token doesn't autofill as its not available in the default token list
- Verified on other network, adding a custom token and then trying to re-add the same token auto-populates the fields but shows error when trying to re-add it 
- Encountered [#5019](https://github.com/brave/brave-ios/issues/5019)

Scenario 1 & 3 | Scenario 2 & 3
-- | --
<video src=https://user-images.githubusercontent.com/17010094/155478461-46071ba0-0125-420b-bc0e-48e441e9ab17.MP4> | <video src=https://user-images.githubusercontent.com/17010094/155478706-747ba016-2c1c-44f7-86ef-755ec19cc6a6.MP4>

--------------
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.36 (22.2.23.20)
- Verified steps from [#4974](https://github.com/brave/brave-ios/pull/4974)
- Verified on mainnet, pasting contract address auto-populates the token details and adds it when submitted
- Verified on mainnet, re-adding the the custom token that is already added shows an error message
- Verified on other network, adding a custom token doesn't autofill as its not available in the default token list
- Verified on other network, adding a custom token and then trying to re-add the same token auto-populates the fields but shows error when trying to re-add it 
- Encountered [#5019](https://github.com/brave/brave-ios/issues/5019)

Scenario 1 & 3 | Scenario 2 & 3
-- | --
<video src=https://user-images.githubusercontent.com/17010094/155478389-5b93eec6-0f6d-4460-9f29-16a1c444e607.MP4> | <video src=https://user-images.githubusercontent.com/17010094/155478604-a5f4b144-1006-4437-b530-c393b59d1de3.MP4>
