### ISSUE TITLE
iPhone reappears after being removed by other device on Sync chain

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#4747]
### Description: 

iPhone reappears after being removed by other device on Sync chain

Found while testing https://github.com/brave/brave-browser/issues/19561

### Steps to Reproduce 
1. new profile of desktop `1.34.66`
2. launch Brave
3. set up a Sync chain
4. join Sync chain from iOS `1.34 (21.12.16.17)`
5. from desktop, click on the trash-can icon to remove the iOS device
6. click `OK` when prompted to confirm
7. wait 3 minutes
8. look at the Sync screen on desktop
9. look at the Sync screen on iOS

**Actual result:** 

iOS | desktop
----|----------
![Image from iOS (5)](https://user-images.githubusercontent.com/387249/146600651-7dee1c49-7a50-4f88-b8a8-bccd98f7e329.png) | ![desktop-devices](https://user-images.githubusercontent.com/387249/146600963-7c79c7e8-5c14-41d4-b444-74b03daa4d91.png)

**Expected result:**

Once removed remotely by the other Sync-chain device, it should stay removed

![Image from iOS (6)](https://user-images.githubusercontent.com/387249/146600776-580b7499-67b4-4a5c-bee2-b7644783e592.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
Brave `1.34 (21.12.16.17)`

**Device details:** 
iOS 14.4.2

@AlexeyBarabash

**Comment by soner-yuksel** [comment]
This ticket will be closed when a brave-core release bump is made with https://github.com/brave/brave-ios/issues/4761

**Comment by stephendonner** [comment]
> This ticket will be closed when a brave-core release bump is made with #4761

Sadly, this isn't fixed as of `1.34 (21.12.21.19)`, which includes https://github.com/brave/brave-ios/issues/4759/https://github.com/brave/brave-ios/issues/4761, and we thought that'd fix it.  @AlexeyBarabash are you able to help with this?

**Comment by AlexeyBarabash** [comment]
@stephendonner 
The only thing I can do - it is to create uplift PR for  https://github.com/brave/brave-core/pull/11313 into 1.33.x . 
Will it help?

**Comment by AlexeyBarabash** [comment]
And I don't understand why I didn't create the uplift PRs once the main was merged. Probably I had missed to do that by mistake.

**Comment by stephendonner** [comment]
> @stephendonner The only thing I can do - it is to create uplift PR for [brave/brave-core#11313](https://github.com/brave/brave-core/pull/11313) into 1.33.x . Will it help?

Not sure we want to backport this to 1.33.x's next hotfix build, probably just want to make sure it's working in 1.34.x.

Our new hypothesis is that there was xcode caching in the previous build, and we're rechecking it now.  (Filing a crasher, too.)

**Comment by Brandon-T** [comment]
This is fixed now. Just tested it.
