### ISSUE TITLE
Add Sync-Internals URL support to view sync info

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#4748]
## Feature Overview 
- Brave Desktop and Android and Chrome-iOS have the ability to visit `brave://sync-internals` or `chrome://sync-internals` to view sync info. iOS should have the same.

## Design 

![image](https://user-images.githubusercontent.com/1530031/146633274-683dc111-e656-42f0-b22f-1e418a99c7b9.png)

## Implementation Details
- Requires Brave-Core work
- Requires integration into Brave-iOS

**Comment by Uni-verse** [comment]
Verification completed using build `version 1.36 (22.2.11.11)` `BraveCore 1.36.87 (98.0.4758.87)`

**PASSED** on `iPhone 12 Pro` / `iOS 15.1.1`
**PASSED** on `iPhone X` / `iOS 14.4.2`
**PASSED** on `iPad (7th Gen)` / `iPadOS 15.2.1`

**Acceptance Criteria:**

- Adds a view to display Sync-Internals when visiting brave://sync-internals URL
- User is able to view the sync-internals screen by tapping on the gear icon under settings > sync
- User is able to navigate back from the sync-internals screen with the UI back button on the page header
- User is able to start a new sync chain and add other devices
- User is able to scan a sync code to sync to existing chain
- Sync internals reflects data from devices on sync chain

iPhone | iPad
-|-
![IMG_2448](https://user-images.githubusercontent.com/17885425/154154164-d7089d81-b548-454b-a763-bece9099733a.PNG) | ![IMG_0147](https://user-images.githubusercontent.com/17885425/154154177-95157702-b4fe-4907-b0ab-52aa1e71621c.PNG)
