### ISSUE TITLE
Crash when iOS device is remotely removed from Sync chain

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#4764]
### Description: 

Crash when iOS device is remotely removed from Sync chain (found while re-testing https://github.com/brave/brave-ios/issues/4747).

### Steps to Reproduce 
1. new profile of desktop `1.34.x`
2. launch Brave
3. set up a Sync chain
4. join Sync chain from iOS `1.34 (21.12.21.21)`
5. from desktop, click on the trash-can icon to remove the iOS device
6. click OK when prompted to confirm
7. wait 3 minutes
8. look at the Sync screen on desktop
9. look at the Sync screen on iOS

**Actual result:** 
I'm crashing before the 3 minutes is even finished in step #7 (so it appears the sync-chain removal is attempted, which is good, at least)

https://user-images.githubusercontent.com/387249/147006633-ac8de2d6-fb29-46b3-8a23-500c31b60191.MP4

**Expected result:**

Device should be remotely removable from the Sync chain, without crashing.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
`1.34 (21.12.21.21)`

**Device details:** 
iPhone 6s (`iOS 14.4.2`)

cc @soner-yuksel @Brandon-T @AlexeyBarabash

**Comment by Brandon-T** [comment]
Does this happen on 1.33.x? @stephendonner

**Comment by soner-yuksel** [comment]
Yes I can reproduce this too on develop, it started after merging https://github.com/brave/brave-ios/pull/4760

**Comment by stephendonner** [comment]
> Does this happen on 1.33.x? @stephendonner

Nope; the iOS device also doesn't get removed, but that's the whole point of the other brave-core fix, as we know.  No crashes.

**Comment by Brandon-T** [comment]
So it means something in BraveCore 1.34.x broke it :(

**Comment by stephendonner** [comment]
Verified `PASSED` using `1.34 (21.12.22.15)` on a Google Pixel XL running Android 9.0.

Followed my original steps and can confirm I didn't crash, and the device gets removed from the Sync chain.


https://user-images.githubusercontent.com/387249/147140989-0941beb5-b088-4444-a046-990bbcc5ae0e.MP4
