### ISSUE TITLE
Closed tabs are not fully closed

### ISSUE THREAD

**Issue by varialle** [brave/brave-ios#4765]
### Description: 
I've noticed the bug where media sounds continue to play after the tab is closed--this happens almost every time for me--but I just discovered that, when a tab is connected to a chatroom-like website, closing the tab doesn't actually sever your connection to the website; after you close the tab, others who are able to see whether you are in the "room" see that you are still online, when closing that tab in any other browser would normally disconnect you from the website. 

### Steps to Reproduce 
  1. Log into a website where others can see your "connected" status, e.g. browser-based discord, f-list.net/chat3. mxrp.chat, or any website where closing the tab will normally show others that you have left the room.
  2. Close the tab. (I think you may need to have other tabs open, potentially connected to the same website. Not sure whether closing the tab while that tab is selected makes a difference.) 
  3. With another account/on another device, check to see whether your original connection is still listed as online. 

**Actual result:** 
Your phone stays connected to the website, as others can see that you are still online and media (for example, notification sounds when people message you) continues to play on your phone. 

**Expected result:**
Closing a tab should cut the connection between your phone and the website you were on, ending any playing media and disconnecting you from any chat rooms/websites.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Very regularly.

**Brave Version:** 
version 1.32.3 (21.11.17.19)

**Device details:** 
iPhone 11 (iOS 15.1)

**Website problems only:**
- did you check with Brave Shields down?
yes.
- did you check in Safari/Firefox (WkWebView-based browsers)? 
yes.

### Additional Information
I often use a vpn but disabling it doesn't seem to fix the issue.

**Comment by iccub** [comment]
should be fixed, will reopen if this still happens
