### ISSUE TITLE
Change to new way to Reset Wallet for brave-core 1.36.x upgrade

### ISSUE THREAD

**Issue by bbondy** [brave/brave-ios#4777]
### Description: 

Before 1.35.x brave-core, you could just call KeyringController::Reset to reset the wallet. This changes as of this PR:
https://github.com/brave/brave-core/pull/11669/files#diff-d5d80c8bf10054827601d890b9e85e6c9bfc4304b17089bd7d443c94c554f232R19

Resetting Wallet must change to this new method for upgrade to 1.36.x brave-core or else there will be Reset regressions.

cc @nuo-xu or @kylehickinson

**Comment by bbondy** [comment]
Update: BraveWalletService::Reset will need to be called only, and that can be done from mojo:
https://github.com/brave/brave-core/pull/11754

**Comment by bbondy** [comment]
Moved this to 1.36.x since I'm going to leave the new changes in 1.36.x and revert the 1.35.x changes so there's no upgrade needed for it.

**Comment by nuo-xu** [comment]
For QAs,
Please do a sanity test on wallet resetting to make sure resetting is not broken.
Thanks

**Comment by Uni-verse** [comment]
Verification in completed using `1.36 (22.2.17.10)` 

**PASSED** on `iPhone 12 Pro` running `iOS 15.1.1`
**PASSED** on `iPhone X` running `iOS 14.4.2`
**PASSED** on `iPad (7th Gen)` running `iPadOS 15.2.1`

Scenarios: 

- Able to reset brave wallet after upgrading app
- Able to reset created brave wallet
- Able to reset restored brave wallet
- Able to reset restored third party wallet (meta mask)
- User is taken to the Brave Wallet landing screen upon resetting 
- User is able to reset wallet via the account tab settings > reset
- User is able to reset wallet via the 3 dot menu > settings > reset

**Comment by Uni-verse** [comment]
Retested and updated post with new version `1.36 (22.2.17.10)` when finding relaunching app after resetting wallet still showed active wallet. 

@nuo-xu

**Comment by Uni-verse** [comment]
> Retested and updated post with new version `1.36 (22.2.17.10)` when finding relaunching app after resetting wallet still showed active wallet.
> 
> @nuo-xu

Just to clarify, I re-tested this scenario and was not able to repro on the build version above so its a PASS. This concludes the verification.
