### ISSUE TITLE
WebGL fingerprint protection

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#478]
### Description: 
WebGL fingerprinting works with fingerprinting protection turned on

### Steps to Reproduce 
  1. Toggle "Fingerprint Protection" in settings
  2. Navigate to https://browserleaks.com/webgl
  
**Actual result:** 
WebGL fingerprinting works

**Expected result:**
Should not work

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
Development version (60a82d37c7987162971f1d23bf5a8639131a27b5)

**Device details:** 
Simulator (iPhone XS - iOS 12.1)

**Comment by danishjafri88** [comment]
Fingerprint protection is currently looking more into canvas FP. For WebGL FP, we have to build a list of all possible WebGL functions which can be used to generate a fingerprint. 
More details about such functions are available in these links:
https://panopticlick.eff.org/
https://browserleaks.com/webgl

Another way of handling this FP is by disabling WebGL completely when FPP is on, or spoof the video card info.

**Comment by jhreis** [comment]
This is reproducible in 1.6 as well. 🤕

**Comment by srirambv** [comment]
Canvas and WebRTC were the only two things blocked on current release version.

**Comment by jumde** [comment]
@jhreis -  Ok cool. This does not block 1.7. I'll tag the issues that are blocking from the security standpoint accordingly. For now, I'm filing all security/privacy issues that I run into, let me know if you want me to hold off on filing the low-pri issues for now?

**Comment by jumde** [comment]
This is addressed in 1.19.

**Comment by iccub** [comment]
Closing and moving to 1.20 for formal QA verification

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.20(20.08.13.15)
- Verified WebGL fingerprinting is blocked when the setting is enabled in Shields
------------
Verification passed on iPhone 7+ with iOS 14 running 1.20(20.08.13.15)
- Verified WebGL fingerprinting is blocked when the setting is enabled in Shields
------------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.20(20.08.13.15)
- Verified WebGL fingerprinting is blocked when the setting is enabled in Shields
------------
Verification passed on iPad Pro with iOS 13. running 1.20(20.08.13.15)
- Verified WebGL fingerprinting is blocked when the setting is enabled in Shields
-----------
Verification passed on iPad Pro with iOS 13.5 running 1.20(20.08.13.15)
- Verified WebGL fingerprinting is blocked when the setting is enabled in Shields
