### ISSUE TITLE
When Brave is closed, selecting "New private window" from context menu opens standard window

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-ios#4783]
### Description: 
Trying to launch a new private tab while the browser is closed on iOS, Brave will open a standard tab instead. This issue appears to be present only on iPhone devices -- have been unable to reproduce this on iPad devices.

### Steps to Reproduce 
  1. Ensure that the browser is closed entirely (swipe up to close/quit)
  2. Long-press the Brave icon
  3. Select `New Private tab` from the context menu
  4. Observe that Brave launches in a standard tab

**Actual result:** 
Standard tab is launched.

**Expected result:**
Private tab should be launched instead.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily on the right devices

**Brave Version:** 
v1.33

**Device details:** 
iOS 15.2 on iPhone 11/iPhone 8

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information
Initial user report: https://community.brave.com/t/home-screen-quick-action-new-private-tab-no-longer-works/319044/4
Internal slack convo: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1640815212446800

**Comment by kjozwiak** [comment]
BTW, this also happens with the `Scan QR Code` context menu. Seems like a general issue when attempting to use the context menu's when long tapping the Brave icon while Brave isn't running.

Regression range:

* `1.33 (21.12.14.16)` - Reproduced
* `1.32.3 (21.11.17.19)` - Reproduced
* `1.32.2 (21.11.4.20)` - Reproduced
* `1.32.1 (21.10.28.15)` - Reproduced
* `1.32 (21.10.13.18)` - Couldn't reproduce

**Comment by Uni-verse** [comment]
Verification PASSED on `iPhone 12 Pro` running `iOS 15.1.1` and `iPhone X` running `iOS 14.4.2` using build 

```
1.35 (22.1.14.22)
```

Acceptance Criteria:

1.  PASSED - Open new private window from context menu https://github.com/brave/brave-ios/issues/4783#issue-1090784718
2. PASSED - Using Scan QR Code from context menu with active private tab https://github.com/brave/brave-ios/issues/4783#issuecomment-1003219826 

**`iOS 15.1.1`** | **`iOS 14.4.2`**
------------------|-----------------
![IMG_2335](https://user-images.githubusercontent.com/17885425/150032361-8309511f-2bde-4166-a606-9619ea5e7b0c.PNG) | ![IMG_2571](https://user-images.githubusercontent.com/17885425/150034387-77781a21-6d89-4de9-b817-3fddd8f42632.PNG)

-----

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.2` using `1.35 (22.1.14.22)`

**`Cases while Brave is not running in the background`** (Original issue)

* verified the STR/Cases outlined via https://github.com/brave/brave-ios/issues/4783#issue-1090784718 (Private Tab)
* verified the STR/Cases outlined via https://github.com/brave/brave-ios/issues/4783#issuecomment-1003219826 (QR Code)
* ensured that `New Tab +` opens a tab without any issues when Brave isn't running in the background

**`Cases while Brave is running in the background`**

* ensured that `Scan QR Code` correctly switches to Brave and displays the `Scan QR Code` modal
* ensured that `New Private Tab` opens a private tab without any issues
* ensured that `New Tab +` opens NTP without any issues

**Comment by Uni-verse** [comment]
> BTW, this also happens with the `Scan QR Code` context menu. Seems like a general issue when attempting to use the context menu's when long tapping the Brave icon while Brave isn't running.
> 
> Regression range:
> 
> * `1.33 (21.12.14.16)` - Reproduced
> * `1.32.3 (21.11.17.19)` - Reproduced
> * `1.32.2 (21.11.4.20)` - Reproduced
> * `1.32.1 (21.10.28.15)` - Reproduced
> * `1.32 (21.10.13.18)` - Couldn't reproduce

Was hoping you could provide the test steps for this. Are we keeping a private tab active for this? Thanks.

**Comment by soner-yuksel** [comment]
It is bug found over an existing feature. I believe it will be more than sufficient to test If other actions are working while default browser mode was active and  browser is closed entirely (swipe up to close/quit).
