### ISSUE TITLE
Bookmarks page not remembered when using the toolbar icon

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-ios#4789]
### Description: 
On iOS, some users are reporting that the last state of the bookmarks menu (when selected from the icon) is not remembered once a link is clicked. For example, if you were to tap the icon, then go to `Mobile bookmarks --> Folder 1 --> Folder 2` then click on a link, tapping the bookmarks icon again will start all the way back at `Mobile bookmarks`. Note that this is not the case if the bookmarks menu is accessed through the main menu. May be iPad specific.

### Steps to Reproduce 

1. Open Brave and tap bookmarks icon
2. Drill into your bookmarks — this user went to Mobile bookmarks --> Imported bookmarks
3. Tap on any bookmark to navigate to the site
4. Tap the bookmarks icon again

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily/always for users who are experiencing this

**Brave Version:** 
v1.33

**Device details:** 
iPad (iOS 15.2)

### Additional Information
User reports:
https://community.brave.com/t/selecting-bookmark-icon-now-have-to-drill-down-for-bookmarks/318723/5
https://community.brave.com/t/bookmarks-icon-doesn-t-recall-last-used-state-ios/319369

**Comment by warwickmm** [comment]
I can reproduce this on an iPhone (iOS 15.2) with version 1.33(21.12.14.16).

#4770 seems related.

**Comment by soner-yuksel** [comment]
@warwickmm thanks for the warning, closing the other ticket ticket as duplicate

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPad 7th Generation iOS version 15.2` running `Brave 1.34 (22.1.5.15)`
1. Tap on the bookmarks icon in the URL bar (behind the lock icon) ->Tap on the Desktop bookmarks or Mobile bookmarks->Tap on any bookmark folder -> tap on any bookmark to open the website->Website is opened and bookmarks menu is closed.
2. Tap again on the bookmark icon in the URL bar (behind the lock icon) 

**Actual**: when I come back and tap on the bookmark menu, the place in the menu is remembered which is expected

https://user-images.githubusercontent.com/38657976/148510215-ceb035fa-fd16-44b1-a8f0-712e7a4fb0b7.MP4
