### ISSUE TITLE
Shield stats are not migrated

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#479]
### Steps to Reproduce 
  1. Install brave1.6.6
  2. Open few websites so shield stats increment
  3. Close all tabs
  4. Upgrade to 1.7

All shields after migration are set to 0

**Comment by kylehickinson** [comment]
They are correctly migrated. However 1.6 requires that you background the app to save.

Installed 1.6 → Visited sites → 5 trackers blocked, 15 ads blocked → *backgrounded application*
Installed 1.7 → Verified 5 trackers blocked, 15 ads blocked
