### ISSUE TITLE
Add unit tests for unquote function in reader more

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4794]
See this PR
https://github.com/brave/brave-ios/pull/4773

**Comment by VaishaliDesai** [comment]
Hello there, I would like to take up this good first issue to contribute to this repository.

**Comment by VaishaliDesai** [comment]
Somehow Git doesn't let me push my changes to the branch :/

```
remote: Permission to brave/brave-ios.git denied to VaishaliDesai.
fatal: unable to access 'https://github.com/brave/brave-ios.git/': The requested URL returned error: 403

**Comment by kylehickinson** [comment]
Hey @VaishaliDesai you have to fork brave-ios first to your own repository 🙂 After that you can push your changes to that new fork and open a PR from there

**Comment by VaishaliDesai** [comment]
Thank you for your help @kylehickinson. This is my very first attempt in contribution to open source. Your comments helped me raised my first PR. Here it is https://github.com/brave/brave-ios/pull/4854.
