### ISSUE TITLE
Search history headers are not sorted correctly

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#4801]
### Description: 

Found while testing https://github.com/brave/brave-ios/issues/3398
Search history headers are not sorted correctly
### Steps to Reproduce 
Case 1:

  1. Clean profile 1.34
  2. Open 4 websites and confirm history is stored in History
  3. Set the device date ahead by 1 week
  4. Search history header is sorted as `Last month` instead of `Last week`

Case 2:

  1. Set the device date 1 month behind (I have set it to Dec 1st 2021)
  2. Clean profile 1.34
  2. Open 4 websites and confirm history is stored in History
  3. Set the device date to today's date
  4. Search history header is sorted as `Earlier` instead of `Last month`

**Actual result:** 
Search history headers are not sorted correctly
Case 1:
![IMG_2713](https://user-images.githubusercontent.com/38657976/148235922-899e2452-213c-45e3-9b40-bf8309f5a268.PNG)

Case 2:
![IMG_2714](https://user-images.githubusercontent.com/38657976/148235941-6b59c52e-f590-4581-829f-5bd729bb30fa.PNG)

**Expected result:**

Search history headers should be sorted correctly
**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.34

**Device details:** 
iPhone 8 - iOS 15.2

**Website problems only:**
- did you check with Brave Shields down?NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @kylehickinson @Brandon-T @soner-yuksel

**Comment by soner-yuksel** [comment]
So this behaviour is working as expected.

For instance If you will move the date more than one month before the existing date, the items added added will be seen as that are added more than a month before period.

In this case they will be classified as "Earlier" not in the "Last Month".

This is same for the cases mentioned except the one mentioned here.
