### ISSUE TITLE
`No search history result` isn't showing up the correct message

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#4802]
### Description: 
Found while testing https://github.com/brave/brave-ios/issues/3398
`No search history result` isn't showing up the correct message
### Steps to Reproduce 
  1. Clean profile 1.34
  2. Open 4 websites and confirm history is stored in History
  3. Open Search history bar and enter any website which is not listed in the search history list
  

**Actual result:** 
![IMG_2712](https://user-images.githubusercontent.com/38657976/148239393-af1266bd-f84e-4d15-8b25-1d31dd33dbe6.PNG)

**Expected result:**
 `No search results found` message should be shown in search result history
**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

1.34
**Device details:** 
iPhone 8 - iOS 15.2

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @soner-yuksel @kylehickinson @iccub @Brandon-T

**Comment by Uni-verse** [comment]
Verification completed on following devices using build version `1.35 (22.1.14.22)`

**PASSED** on `iPhone 12` Pro running `iOS 15.1.1`
**PASSED** on `iPhone X` running `iOS 14.4.2`
**PASSED** on `iPad (7th Gen)` running `iPadOS 14.4.2`

- Verified 'No search result found' is displayed when not returning search match - https://github.com/brave/brave-ios/issues/4802#issue-1094446550
- Verified Search Results legend is display above the text results. 

Scenarios Tested: 

- History search functionality (scanning text, clearing, cancel)
- Deleting history via delete icon
- Verifying search results with sync chain
- Navigating using ui back button
- Searching while using iPhone's reach accessibility feature

![IMG_2342](https://user-images.githubusercontent.com/17885425/150242780-a19d3cf4-d9cb-4d39-aa58-694f5e2c8f2c.PNG)
