### ISSUE TITLE
Wire up SKU SDK to a JavaScript DOM element

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#4804]
### Description: 
Desktop is supporting VPN purchases using the account.brave.com website and (in browser) using the SKU SDK (see implementation in https://github.com/brave/brave-core/pull/10847; not merged yet).

The goal would be to use this service to fetch/set a Desktop VPN credential on iOS

### Additional details:
@kylehickinson has added a Service wrapper (`brave/ios/browser/skus/skus_service_factory.h`) in the PR which creates a browser state compatible version of the SkuService which has four calls:
- `refresh_order`
- `fetch_order_credentials`
- `prepare_credentials_presentation`
- `credential_summary`

On Desktop, these JS methods are optionally exposed to page. Calls look like this:
- `window.chrome.braveSkus.refresh_order('0ee1e3ee-afc3-4f2f-b2a2-3d1e401e1530')`
- `window.chrome.braveSkus.fetch_order_credentials('0ee1e3ee-afc3-4f2f-b2a2-3d1e401e1530')`
- `window.chrome.braveSkus.credential_summary('vpn.brave.software')`
- `window.chrome.braveSkus.prepare_credentials_presentation('vpn.brave.software', '*')`

As noted above, these should be optionally injected only on the following origins:
- `vpn.brave.com` (prod)
- `vpn.bravesoftware.com` (staging)
- `vpn.brave.software` (dev)

The intention is for the Brave Accounts website to detect and use these APIs so that a credential can be delivered to the browser.

#### iOS
- [Detect and store VPN state after sign-in](https://github.com/brave/brave-ios/issues/4805)

#### Android
- [(Android) Detect and store VPN state after sign-in](https://github.com/brave/brave-browser/issues/20374)

#### Desktop
- [Integrate the SKU SDK into the browser](https://github.com/brave/brave-browser/issues/17614)
- [(Desktop) Detect and store VPN state after sign-in](https://github.com/brave/brave-browser/issues/17254)

**Comment by iccub** [comment]
I will handle all work in a single ticket https://github.com/brave/brave-ios/issues/4805
