### ISSUE TITLE
Save logins switch is shown when focus is set to search field without any saved passwords

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4814]
### Description: 
Save logins switch is shown when focus is set to search field without any saved passwords

### Steps to Reproduce 
  1. Clean install 
  2. Open `Logins & Password` from menu
  3. Focus on search field
  4. `Save Logins` text is hidden but the switch isn't

**Actual result:** 

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.2) | iPad Pro (iOS 15.3)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/148543149-94f1bab9-3f45-461d-95d9-34f7f720b266.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/148543164-0588e56e-e8b8-4d81-8f40-9517c5677beb.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/148543175-61dabfe4-0ce5-429b-be84-10faa56b16f3.png>

**Expected result:**
Hide the switch when text is hidden

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.34 (22.1.5.15)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @soner-yuksel

**Comment by Uni-verse** [comment]
Verifications completed using 1.35 (22.1.24.16)

**PASSED** on `iPhone 12` Pro on `iOS 15.1.1`
**PASSED** on `iPhone X` on `iOS 14.4.2`
**PASSED** on `iPad (7th Gen)` on `iPadOS 14.4.2`



- Verified 'Save Logins' Text and Switch is hidden when text filter field is in focus 
- Verified user is able to edit saved logins 
- Verified saved login matches are shown with search 

https://github.com/brave/brave-ios/pull/4852#issue-1102136442

Search | Saved Logins 
-|-
![IMG_2371](https://user-images.githubusercontent.com/17885425/150868691-b8a29e8d-e12e-40fe-9754-ff8051012036.PNG) | ![IMG_2372](https://user-images.githubusercontent.com/17885425/150868702-151069ad-c605-4471-bc2e-71b0b00407ef.PNG) 

Search | Saved Logins
-|-
![IMG_0110](https://user-images.githubusercontent.com/17885425/150869867-41addd2c-1c01-434f-9c31-f608593ae556.PNG) | ![IMG_0109](https://user-images.githubusercontent.com/17885425/150869881-28e0653b-36f0-4a6d-9b05-462c84a06616.PNG)
