### ISSUE TITLE
Brave News header with Settings icon shouldn't show until after opted in

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#4815]
### Description: 

Brave News header with Settings icon shouldn't show until after opted in

### Steps to Reproduce 
  1. install `1.34 (22.1.5.15)`
  2. launch Brave
  3. tap through onboarding
  4. on the new-tab page, swipe down
  5. look at the `Brave News` heading with Settings icon at the top of the opt-in page

**Actual result:** 

![Image from iOS (1)](https://user-images.githubusercontent.com/387249/148586678-f839dc61-b8cf-4cad-8d13-b3516ef5c49b.png)

**Expected result:**

![Screenshot_20220107-085955](https://user-images.githubusercontent.com/387249/148586733-ad88b971-b9ff-4648-a8f2-7370aa018570.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 

Brave `1.34 (22.1.5.15)`

**Device details:** 

`iPhone 6s` `(iOS 15.0.2, 19A404)`

cc @mattmcalister

**Comment by kylehickinson** [comment]
@stephendonner Is there any reasoning for this other than "Android is doing it this way"? Personally I would say the header is fine and _maybe_ the only thing that needs to be hidden is the settings icon.

**Comment by kylehickinson** [comment]
cc @jamesmudgett for design decision

The header makes sense honestly, you are still in "Brave News" part of NTP

**Comment by stephendonner** [comment]
> @stephendonner Is there any reasoning for this other than "Android is doing it this way"? Personally I would say the header is fine and _maybe_ the only thing that needs to be hidden is the settings icon.

Not inherently; I'm just doing my due diligence in filing for consideration :-)

**Comment by mattmcalister** [comment]
No need for this change, atm. Let's look at it when we're ready to implement the new onboarding for Brave News. Feel free to close this issue @stephendonner
