### ISSUE TITLE
settings menu stays opened when long tapping and opening bookmark via `Open in New Tab`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4820]
### Description: 

When you long tap an individual saved bookmark and select `Open in New Tab`, the bookmark is opened correctly in a new tab but the `Settings` menu stays opened rather than being closed. The `Setting` menu is dismissed correctly if you open bookmarks by long tapping the folder, but doesn't work for individual bookmarks.

### Steps to Reproduce

  1. download/install Brave (`1.34 (22.1.5.15)` in this instance)
  2. save a bookmark into `Mobile Bookmarks` (doesn't need to be in another folder)
  3. long tap on the saved bookmark and select `Open in New Tab`

Notice that the bookmark opens in a new tab but the `Settings` menu is still opened and doesn't close.

**Actual result:** 

![image](https://user-images.githubusercontent.com/2602313/148716261-35bb88d7-38dc-4e9c-b2eb-49519b09750a.png)

**Expected result:**

`Settings` menu should be closed once a bookmark as been opened. Users shouldn't have to close `Settings` manually.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases mentioned above.

**Brave Version:** 

* `1.34 (22.1.5.15)`

**Device details:** 

* `iPhone 6s+` running `iOS 14.6` - **Reproduced**
* `iPhone 12` running `iOS 15.1.1` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

**Comment by Uni-verse** [comment]
Verification PASSED using 1.38 (22.4.25.21)

Devices:
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad | iOS 15.2.1

- Settings menu is dismissed when long tapping and opening bookmark via `Open in New Tab`

https://user-images.githubusercontent.com/17885425/165811268-e24517bf-8f01-4eca-8e23-f5af329685b5.mov

**Comment by iccub** [comment]
This fix caused regressions https://github.com/brave/brave-ios/issues/5319 and https://github.com/brave/brave-ios/issues/5318
I'm reopening this issue and moving it out of the milestone

**Comment by iccub** [comment]
Update: We managed to fix it, would be good to retest it just in case

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.4` using `1.38 (22.5.4.18)`

* ensured that tapping `Open in New Tab` dismisses the `Mobile Bookmarks` modal/menu and opens the tab as expected
* ensured that tapping `Open in New Private Tab` dismisses the `Mobile Bookmarks` modal/menu and opens the tab as expected
* ensured that `Copy Link` works and correctly copies the specified link into the clipboard (made sure pasting works as well)

--------------

Verification **PASSED** on `iPhone 11` running `iOS 15.4.1` using `1.38 (22.5.4.18)`

* ensured that tapping `Open in New Tab` dismisses the `Mobile Bookmarks` modal/menu and opens the tab as expected
* ensured that tapping `Open in New Private Tab` dismisses the `Mobile Bookmarks` modal/menu and opens the tab as expected
* ensured that `Copy Link` works and correctly copies the specified link into the clipboard (made sure pasting works as well)

Created #5331 while running through the above cases.
