### ISSUE TITLE
Update order of buttons on 'create sync chain' screen

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4821]
First primary button should be to scan qr code,
secondary button to start a new sync chain

**Comment by srirambv** [comment]
I'd say we keep as is and Android should change the order. Reason mentioned here https://github.com/brave/brave-browser/issues/20274#issuecomment-1008894549

**Comment by YashasviChaurasia** [comment]
@iccub @srirambv @phatblat @kim0 Is this Issue still open?
Thank you

**Comment by jacobmbarnard** [comment]
Also checking to see if this is still open... is it?

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 [iOS 16.5.1]
- iPad Air [iPadOS 16.5]
Brave build: 1.56 (23.7.13.16)
BraveCore: 1.56.5 (115.0.5790.75)
```
---------------------------

**STEPS:**
1. Launch Brave > Three-dot menu > Settings
2. Sync > Verify
3. Tap `I have a Sync Code` > Verify
4. Go back and tap `Start a new Sync Chain` > Verify

**ACTUAL RESULTS:**
- Verified that the first button on `Create sync chain` screen is `I have a Sync Code` and the second button is `Start a new Sync Chain`
- Verified that the functionality of both buttons is not broken

---------------------------

*iPhone*
|1.52.x|1.56.x|1.56.x|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/5db90895-af4a-47ec-8748-6b31e108717f) | ![2](https://github.com/brave/brave-ios/assets/128532965/fdebff25-9ae9-4207-8f58-c79655e61045) | ![3](https://github.com/brave/brave-ios/assets/128532965/7cebc3cb-6d8e-4067-893e-6d13a28b9b1d) |

*iPad*
|1.52.x|1.56.x|1.56.x|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/853d8abd-b003-4eb3-b344-5be01c83082d) | ![2](https://github.com/brave/brave-ios/assets/128532965/0876488d-7f66-46e2-8a80-f7b84dc5e398) | ![3](https://github.com/brave/brave-ios/assets/128532965/5c77caa4-dc0c-48b8-a7cb-bfa179b09254) |
