### ISSUE TITLE
Add ability to fetch, add, modify, remove custom netoworks in settings

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#4822]
### Description: 

Matching desktop, add ability in settings to see a list of custom networks, add, modify, and remove custom networks.  
DO NOT allow to remove current network. 
Using EthJsonRpcController’s AddEthereumChain 
![image](https://user-images.githubusercontent.com/1187676/148817602-3f157ffe-edb6-4678-b3b0-89921b86519c.png)
![Screen Shot 2022-01-10 at 11 10 09 AM](https://user-images.githubusercontent.com/1187676/148798776-f077edac-7098-42df-8d92-e8b3198bd388.png)
![Screen Shot 2022-01-10 at 11 10 21 AM](https://user-images.githubusercontent.com/1187676/148798797-b4671679-d899-4ae0-b8d2-369ec8d3641a.png)

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.36 (22.02.23.20)
- Verified test plan from [#4942](https://github.com/brave/brave-ios/pull/4942)
- Verified able to add a custom network
- Verified a new option for add network is available on network drop-down
- Verified error message is shown for mandatory fields when trying to save
- Verified error message is shown for invalid chainID and RPC URL
- Verified can't add duplicate entry for a custom network
- Verified editing a custom network doesn't allow editing chainID 
- Verified able to swipe delete an added custom network
- Verified added custom network is shown on the network drop-down 
- Verified setting custom network as default and swipe delete resets network to Mainnet
- Verified only send is shown on quick action button for custom network
------------
Verification passed on iPhone XR with iOS 15.3 running 1.36 (22.02.23.20)
- Verified test plan from [#4942](https://github.com/brave/brave-ios/pull/4942)
- Verified able to add a custom network
- Verified a new option for add network is available on network drop-down
- Verified error message is shown for mandatory fields when trying to save
- Verified error message is shown for invalid chainID and RPC URL
- Verified can't add duplicate entry for a custom network
- Verified editing a custom network doesn't allow editing chainID 
- Verified able to swipe delete an added custom network
- Verified added custom network is shown on the network drop-down 
- Verified setting custom network as default and swipe delete resets network to Mainnet
- Verified only send is shown on quick action button for custom network
------------
Verification passed on iPad Pro with iOS 15.4 Beta running 1.36 (22.02.23.20)
- Verified test plan from [#4942](https://github.com/brave/brave-ios/pull/4942)
- Verified able to add a custom network
- Verified a new option for add network is available on network drop-down
- Verified error message is shown for mandatory fields when trying to save
- Verified error message is shown for invalid chainID and RPC URL
- Verified can't add duplicate entry for a custom network
- Verified editing a custom network doesn't allow editing chainID 
- Verified able to swipe delete an added custom network
- Verified added custom network is shown on the network drop-down 
- Verified setting custom network as default and swipe delete resets network to Mainnet
- Verified only send is shown on quick action button for custom network
