### ISSUE TITLE
Add ability to switch custom networks

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#4823]
### Description: 

Add ability to switch to the new networks. Using EthJsonRpcController’s SetNetwork and GetAllNetworks which are already used.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.36 (22.2.23.20)
- Verified able to switch to custom networks from portfolio page
- Verified able to switch to custom networks from Send screen
- Verified able to switch from custom networks to default networks when on Send screen

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.3) | iPad Pro (iOS 15.4 Beta)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/155471171-f80c03ee-8ead-493f-827b-b59869e82e35.MP4> | <video src=https://user-images.githubusercontent.com/17010094/155471327-91e74821-df45-480f-9be6-feda64ccfdf1.MP4> | <video src=https://user-images.githubusercontent.com/17010094/155471128-bc5fd158-4ae0-47e4-b89e-a829e0b50a60.MP4>
