### ISSUE TITLE
Make sure send is working in Polygon mainnet 

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#4824]
### Description: 

Make sure sends work on Polygon mainnet for testing

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.36 (22.02.23.20)
- Verified test plan from [#4942](https://github.com/brave/brave-ios/pull/4942)
- Verified able to send from Account 1 to Account 2 on both Polygon Mainnet and Polygon Testnet 

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.3) | iPad Pro (iOS 15.4 beta)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/155517554-a1cfe4f1-81b5-418c-b634-e8094befbb30.MP4> | <video src=https://user-images.githubusercontent.com/17010094/155517640-f8ae3e7b-b0eb-494b-9607-59c282c65323.MP4> | <video src=https://user-images.githubusercontent.com/17010094/155517515-71748a1e-3f0f-4026-89a6-dfc5f823fd9f.MP4>
