### ISSUE TITLE
Remove buy and swap ability for EVM compatible chains

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#4825]
### Description: 

Icon on the bottom to bring up Buy/Send/Swap menu should only list Send for now for EVM compatible chains.

Note: Edit visible asset list and asset list are different per network. I’d like to get rid of the decimals field and only show it when it’s an unknown chainId. Maybe we should do this at the same time?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.36 (22.2.15.22)
- Verified when EVM chain is selected on the network drop down only Send is shown
- Verified setting Ethereum mainnet in network and opening Buy/Swap widget, network selector doesn't lists custom EVM network

<table> 
<tr>
      <th>
      </th>
      <th>:ballot_box_with_check: iPhone 7+ (iOS 14.8.1)</th>
      <th>:ballot_box_with_check: iPhone XR (iOS 15.3)</th>
      <th>:ballot_box_with_check: iPad Pro (iOS 15.4 beta)</th>
   </tr>
   <tr>
      <td><b>Light</b>
      </td>
      <td><img width=350 src=https://user-images.githubusercontent.com/17010094/154214362-e2442aac-1439-4490-9a3f-3f1b5a28315b.png>
      </td>
      <td><img width=280 src=https://user-images.githubusercontent.com/17010094/154214440-0f84425e-ebc1-43d9-b921-15a66a9a2b6a.png>
      </td>
      <td><img width=500 src=https://user-images.githubusercontent.com/17010094/154214408-540fc4a7-4c8f-4c9c-b68b-b70e0f0c82d4.png>
      </td>
   </tr>
   <tr>
      <td><b>Dark</b>
      </td>
      <td><img width=350 src=https://user-images.githubusercontent.com/17010094/154214387-12167106-291c-4f5a-bcaa-2d2181549905.png>
      </td>
      <td><img width=280 src=https://user-images.githubusercontent.com/17010094/154214460-a686cbd0-d056-4636-8bee-b0564369cc02.png>
      </td>
      <td><img width=500 src=https://user-images.githubusercontent.com/17010094/154214423-10edacd5-5290-41aa-830d-13f84a497092.png>
      </td>
   </tr>
</table>
