### ISSUE TITLE
Add a shortcut to add new custom network from all network selection dropdowns.

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#4827]
### Description: 

An extra row at the last of the dropdown menu for users to click to shortcut to Add Network Screen.

![simulator_screenshot_751936E5-420D-4EEA-8579-35FA150C6AA5](https://user-images.githubusercontent.com/1187676/153895028-c46949cf-dcbe-4e34-92f9-dfc810e25043.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.36 (22.2.15.22)
- Verified `Add Network ... +` is shown on network drop downs on Portfolio / Buy / Send / Swap
- Verified on both dark and light theme


**Light**

<table>
   <tr>
      <th>
      </th>
      <th>:ballot_box_with_check: iPhone 7+ (iOS 14.8.1)</th>
      <th>:ballot_box_with_check: iPhone XR (iOS 15.3.1)</th>
      <th>:ballot_box_with_check: iPad Pro (iOS 15.4 Beta)</th>
   </tr>
   <tr>
      <td>Portfolio
      </td>
      <td><img width=350 src=https://user-images.githubusercontent.com/17010094/154210329-bfc692e2-3415-42fb-8c84-4b2336f05583.png>
      </td>
      <td><img width=280 src=https://user-images.githubusercontent.com/17010094/154209477-4c31dd8a-71a9-4447-9292-e6b6c668654f.png>
      </td>
      <td><img width=500 src=https://user-images.githubusercontent.com/17010094/154210096-61b17210-4da4-411e-8507-04857d518f15.png>
      </td>
   </tr>
   <tr>
      <td>Buy
      </td>
      <td><img width=300 src=https://user-images.githubusercontent.com/17010094/154210344-1cb5ba2f-9fbb-4954-a441-4d99592920c4.png>
      </td>
      <td><img width=280 src=https://user-images.githubusercontent.com/17010094/154209464-41615356-95a9-40d3-baf7-8059b6015e66.png>
      </td>
      <td><img width=500 src=https://user-images.githubusercontent.com/17010094/154209557-c03c0c3e-f0c2-4b09-b90a-080b3610f448.png>
      </td>
   </tr>
   <tr>
      <td>Send
      </td>
      <td><img width=300 src=https://user-images.githubusercontent.com/17010094/154210363-4e0bd9aa-2818-4da5-bb2e-485f1acc335d.png>
      </td>
      <td><img width=280 src=https://user-images.githubusercontent.com/17010094/154209455-1c6bf272-67bd-4b6e-844b-b0797ac2be59.png>
      </td>
      <td><img width=500 src=https://user-images.githubusercontent.com/17010094/154209672-e92abd83-738c-46a6-bc14-06ca5930f092.png>
      </td>
   </tr>
   <tr>
      <td>Swap
      </td>
      <td><img width=300 src=https://user-images.githubusercontent.com/17010094/154210390-91fbee6e-2598-4df9-a0b5-b3f722ce0fbf.png>
      </td>
      <td><img width=280 src=https://user-images.githubusercontent.com/17010094/154209439-cf11c97e-2020-4697-b873-9cf0f0b17267.png>
      </td>
      <td><img width=500 src=https://user-images.githubusercontent.com/17010094/154209529-753ab28a-25d1-4f88-92a4-1cffb0f36726.png>
      </td>
   </tr>
</table>

**Dark**

<table>
   <tr>
      <th>
      </th>
      <th>:ballot_box_with_check: iPhone 7+ (iOS 14.8.1)</th>
      <th>:ballot_box_with_check: iPhone XR (iOS 15.3.1)</th>
      <th>:ballot_box_with_check: iPad Pro (iOS 15.4 Beta)</th>
   </tr>
   <tr>
      <td>Portfolio
      </td>
      <td><img width=350 src=https://user-images.githubusercontent.com/17010094/154210407-4bf66824-a821-4b32-8428-c24b5d7c154d.png>
      </td>
      <td><img width=280 src=https://user-images.githubusercontent.com/17010094/154211779-8f89722c-99a4-4d0f-acd8-b34d66e67de8.png>
      </td>
      <td><img width=500 src=https://user-images.githubusercontent.com/17010094/154211606-c1ce001a-58b4-4b8e-af3c-9070ab2b6f82.png>
      </td>
   </tr>
   <tr>
      <td>Buy
      </td>
      <td><img width=300 src=https://user-images.githubusercontent.com/17010094/154210433-95754001-f8f9-4b47-b791-62fdf7656cd2.png>
      </td>
      <td><img width=280 src=https://user-images.githubusercontent.com/17010094/154209099-6a57b37a-1776-4e55-9b8d-ab546630a85b.png>
      </td>
      <td><img width=500 src=https://user-images.githubusercontent.com/17010094/154208917-4d47a777-421a-4085-bce8-388816ef539c.png>
      </td>
   </tr>
   <tr>
      <td>Send
      </td>
      <td><img width=300 src=https://user-images.githubusercontent.com/17010094/154210444-4b1af64b-0faf-4960-b17d-ed27cecee6da.png>
      </td>
      <td><img width=290 src=https://user-images.githubusercontent.com/17010094/154209118-427d0374-6e0c-4106-8036-a1aa6f6470f7.png>
      </td>
      <td><img width=500 src=https://user-images.githubusercontent.com/17010094/154208889-711a8e75-a86a-42f5-bd6d-7d4e0729308a.png>
      </td>
   </tr>
   <tr>
      <td>Swap
      </td>
      <td><img width=300 src=https://user-images.githubusercontent.com/17010094/154210455-5b90fdc5-9a63-4be3-b00e-7a262d271397.png>
      </td>
      <td><img width=280 src=https://user-images.githubusercontent.com/17010094/154209136-1602ca45-dc42-4b84-b773-66af293ce43d.png>
      </td>
      <td><img width=500 src=https://user-images.githubusercontent.com/17010094/154208938-4cbf6914-dd0c-4a9c-93f9-7413dc4d639a.png>
      </td>
   </tr>
</table>
