### ISSUE TITLE
Update error/warning page communication and iconography & use Google Safe Browsing via proxy

### ISSUE THREAD

**Issue by tildelowengrimm** [brave/brave-ios#483]
## Description
As on desktop, we should use Google's Safe Browsing service to avoid phishing & malware.

## Designs
Create responsive webpage designs that work for mobile & desktop widths. 

Interstitial pages:

![image](https://user-images.githubusercontent.com/2388823/129392245-6d1f76e9-3500-47ad-8bf3-c465a1fa386e.png)

Page might charge you money:

![image](https://user-images.githubusercontent.com/2388823/114470222-63b96100-9ba3-11eb-8221-73526e4673e9.png)

Connection not private:

![image](https://user-images.githubusercontent.com/2388823/114472546-49818200-9ba7-11eb-8a95-929434b64d1d.png)

Phishing warning:

![image](https://user-images.githubusercontent.com/2388823/114472555-4dad9f80-9ba7-11eb-9cd9-2964f7b88bd6.png)

Malware warning:

![image](https://user-images.githubusercontent.com/2388823/114472564-530aea00-9ba7-11eb-945f-41a05f7a2971.png)

Unwanted software warning:

![image](https://user-images.githubusercontent.com/2388823/114472576-58683480-9ba7-11eb-9b88-ca589b710352.png)

## Assets
Figma: https://www.figma.com/file/aJu3WGDztEWNZgwQTD9yx2/?node-id=0%3A49

## Test Plan

1. Navigate to https://testsafebrowsing.appspot.com
2. Confirm all webpage warnings URLs display the safe browsing warning.

## Notes
Given that these are webpages, the same design is used for all platforms. Android & Desktop: https://github.com/brave/brave-browser/issues/7464

**Comment by jumde** [comment]
Looks like SafeBrowsing is not implemented yet: https://testsafebrowsing.appspot.com/

**Comment by karenkliu** [comment]
Designs and assets added!

**Comment by karenkliu** [comment]
Cross-platform reference:
Desktop: https://github.com/brave/brave-browser/issues/1149#event-2871439122
Android: https://github.com/brave/browser-android-tabs/issues/2381

**Comment by fmarier** [comment]
Note: as per the [Google UI requirements](https://developers.google.com/safe-browsing/v4/usage-limits#UserWarnings) the screens need to say "**Google** Safe Browsing" and not "**Brave** Safe Browsing".

I will be fixing desktop in brave/brave-browser#7614.

**Comment by fmarier** [comment]
@karenkliu In addition to the "Brave Safe Browsing" bit, I noticed that the designs say "your Mac". Should that be "your device" instead since we're talking about iOS?

**Comment by karenkliu** [comment]
@fmarier Yes - sounds good to me!

**Comment by karenkliu** [comment]
Updated designs to reflect that these should be full-screen HTML pages using our web UI.

**Comment by anthonypkeane** [comment]
@karenkliu can you confirm that these designs are up to date? Thanks

**Comment by karenkliu** [comment]
@anthonypkeane Yes

**Comment by karenkliu** [comment]
Do you still need anything from me for this?

**Comment by anthonypkeane** [comment]
If the designs are up to date @karenkliu I don't need anything from you.

@iefremov When you have a moment can you please review this issue again. We want to implement this in iOS now. Thanks

**Comment by iccub** [comment]
This ticket is too big and we went with using Apple's provided api for safe browsing.

Moving the 'update design' part to https://github.com/brave/brave-ios/issues/4338
