### ISSUE TITLE
Option to disable link preview

### ISSUE THREAD

**Issue by NN---** [brave/brave-ios#4839]
Please add option to disable link preview on long touch.
iOS.

**Comment by kylehickinson** [comment]
@NN--- This feature already exists, when you long press on a URL while browsing you will see a menu below the preview window. The last option in that menu is "Hide Link Previews" (or "Show Link Previews" if you've already hidden it)

**Comment by NN---** [comment]
Thanks.
I looked in the application settings.
Would it be possible to add the option there too?
Thanks.
