### ISSUE TITLE
Find native alternative to clear app document folder

### ISSUE THREAD

**Issue by danishjafri88** [brave/brave-ios#484]
In **CacheClearable** of type **Clearable** contents of app document folders are deleted.
This does not seem a very safe approach(in light of #304). Any public api alternative is more advisable.

**Comment by jhreis** [comment]
For QA, re-test following test plan for: https://github.com/brave/brave-ios/issues/304

**Comment by kylehickinson** [comment]
Don't think this is valid anymore as of https://github.com/brave/brave-ios/commit/a61f18a
