### ISSUE TITLE
Restore old tab tray animation

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4841]
### Description: 

We recently refactored the tab tray and replaced the presentation animation with a standard sheet. Feedback suggests that users liked the old version better and so we should restore the transform-style animation

**Comment by iccub** [comment]
Copying over improvement suggestions from the pull request

Improvements that could happen: Instead of taking a screenshot of the NTP/web page we should use the actual BVC and do scale + anchorPoint animations so that we are safer from screenshot & final view not matching causing a slight mismatch.

**Comment by Uni-verse** [comment]
Verification PASSED on `iPhone 12 Pro` running `iOS 15.1.1` using build `version 1.35 (22.1.14.22)`

- Verified transform-style animation is applied to tab tray

Test Scenarios (for each device)

- Access the tab tray as usual from the browser
- Add new tabs until the number of tabs exceeds the on-screen space
- Verify that tabs transform correctly even when the tab would be off-screen initially (and vice-versa tapping on a partially off-screen tab, or tapping done while selected tab is off-screen)
- Verify private mode acts as normal
- Verify removing all tabs acts as normal

![IMG_2338](https://user-images.githubusercontent.com/17885425/150184174-2f0c31dc-dda4-4e1c-8de9-666acfc2dcb2.PNG)

https://user-images.githubusercontent.com/17885425/150184192-b4af1464-c900-4931-a278-2cf4704a0646.MP4

Verification PASSED on `iPhone X` running ` iOS 14.4.2` using build `version 1.35 (22.1.14.22)`

![IMG_2577](https://user-images.githubusercontent.com/17885425/150184880-0750a3f2-8b8f-4d05-8b6c-8522fc27216d.PNG)

https://user-images.githubusercontent.com/17885425/150184902-bf57a0e0-14a5-4e6b-8d36-318c96a6ae1c.MP4

Verification PASSED on `iPad (7th Gen)` running `iPadOS 14.4.2` using build `version 1.35 (22.1.14.22)`

![IMG_0099](https://user-images.githubusercontent.com/17885425/150185038-98eb02a4-d144-46c6-a5ba-64237a1eff1f.PNG)
![IMG_0100](https://user-images.githubusercontent.com/17885425/150185050-0b05f8e2-814b-4b00-b2b8-40f64047264e.PNG)
![IMG_0101](https://user-images.githubusercontent.com/17885425/150185060-79c03e5a-94eb-4069-ad96-40b1078e6547.PNG)
