### ISSUE TITLE
Add ability to target specific platforms for NTPSI

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4844]
### Description: 
Details in https://github.com/brave/brave-browser/issues/17450

Add the ability to target platforms, specifically 'ios', 'android', and 'desktop' for new tab page sponsored image campaigns.

NTPSI campaigns can then be targeted for one or two platforms with the default option that NTPSI campaigns are targeted for all platforms.

**Comment by anthonypkeane** [comment]
cc @bradleyrichter

**Comment by Uni-verse** [comment]
Verification completed using build `version 1.36 (22.2.15.22)` 

**PASSED** on `iPhone 12 Pro` / `iOS 15.1.1`
**PASSED** on `iPhone X` / `iOS 14.4.2`
**PASSED** on `iPad (7th Gen)` / `iPadOS 15.2.1`

Test Plan: 

 - Sanity check that you are still able to see sponsored new tab page images. -  https://github.com/brave/brave-ios/pull/4951#issue-1126059592
 
![Screen Shot 2022-02-15 at 5 03 49 PM](https://user-images.githubusercontent.com/17885425/154176392-c6d9d71c-9d44-42a5-ab3e-f645046d5510.png)
