### ISSUE TITLE
Printer Abuse Bug

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#4848]
### Description: 
1. A malicious website can abuse the `print` function of the browser via `window.print`

### Steps to Reproduce 
  1. In Security Ticket.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12 Pro` running `iOS 15.1.1` using `1.35 (22.1.30.17)`

- Verified suppress message will prevent the print window modal from repeatedly showing. 

Note : Suppress message shows up twice 

https://user-images.githubusercontent.com/17885425/151874777-5d3ba97f-eded-4093-8b2e-4e1d9fc825bd.MP4

--------------------------------

Verification **PASSED** on `iPhone 12` running `iOS 15.2.1` using `1.35 (22.1.30.17)`

* ensured that printing works as expected once the initial print modal appears via https://brandon-t.github.io/WindowPrint.html
* ensured that tapping on `Suppress Alerts` stops the printer modal from re-appearing
* ensured that `Suppress Alerts` only applies to that tab instance (opening the website in a new tab will spam the printer modal)
* ensured that you can still print when a user suppresses the modal via `Suppress Alerts`
* ensured that tapping on `Cancel` on the `Suppress Alerts` modal works as expected

--------------------------------

Verification **PASSED** on `iPhone 11` running `iOS 14.7,1` using `1.35 (22.1.30.17)`

* ensured that printing works as expected once the initial print modal appears via https://brandon-t.github.io/WindowPrint.html
* ensured that tapping on `Suppress Alerts` stops the printer modal from re-appearing
* ensured that `Suppress Alerts` only applies to that tab instance (opening the website in a new tab will spam the printer modal)
* ensured that you can still print when a user suppresses the modal via `Suppress Alerts`
* ensured that tapping on `Cancel` on the `Suppress Alerts` modal works as expected

--------------------------------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.2` using `1.35 (22.1.30.17)`

* ensured that printing works as expected once the initial print modal appears via https://brandon-t.github.io/WindowPrint.html
* ensured that tapping on `Suppress Alerts` stops the printer modal from re-appearing
* ensured that `Suppress Alerts` only applies to that tab instance (opening the website in a new tab will spam the printer modal)
* ensured that you can still print when a user suppresses the modal via `Suppress Alerts`
* ensured that tapping on `Cancel` on the `Suppress Alerts` modal works as expected

**Comment by kjozwiak** [comment]
QA found https://github.com/brave/brave-ios/issues/4922 while running through the above 👍 Thanks for getting the issue filed @Uni-verse.
