### ISSUE TITLE
Unable to use yubikey (fido) in Ipad

### ISSUE THREAD

**Issue by fulvi0** [brave/brave-ios#4857]
### Description: 

Hi,

I'm using brave recently, and I tried to login into my Google account with 2FA, using key (Yubikey), where the Browser popup a modal screen indicating to insert the key, ones I insert the key, doesn't go on, stay with the popup on. I try in Firefox, with the same process to login to my Google account and using the same yubikey, and works properly, maybe its an issue with Brave.

### Steps to Reproduce 
  1. Goes to Account.google.com, input my credentials.
  2. Google request de 2fa with the key
  3. Brave popup a modal screen indicating to insert the key; and stuck here.

![image](https://user-images.githubusercontent.com/4769081/149666415-cbc869c4-ba62-42c8-9ae2-d7686bfe8da1.png)

**Expected result:**
Login to my account of google using the key

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:**
Brave Version 1.34 (22.1.10.19)

**Device details:**
Device iPad13,6 (iPadOS 15.2.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

I check with Firefox and works.

**Comment by Brandon-T** [comment]
Solved by: https://github.com/brave/brave-ios/pull/4758
