### ISSUE TITLE
Tabs and history lost when browsing history and cache is not selected in clear data

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#486]
### Description: 
Tabs and history lost when browsing history and cache is not selected in clear data

### Steps to Reproduce 
  1. Add browsing history
  2. Uncheck all except saved logins in clear private data
  3. Clear data, all tabs and history is lost even though only saved login was selected

**Actual result:** 
Tabs and history lost when browsing history and cache is not selected in clear data

**Expected result:**
Should only remove data for which the selection is made

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Eady

**Brave Version:** 
1.7 (18.11.28.22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
This is an existing issue on 1.6.6 as well

**Comment by danishjafri88** [comment]
#482 fixes this
