### ISSUE TITLE
Wrong Top Section Header Padding in various Screens

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#4860]
## Description: 

Wrong Top Section Header Padding for various controllers should be fixed.

**Actual result:** 

### Search Suggestions Screen

![search-broken](https://user-images.githubusercontent.com/6643505/149811909-8637f86d-5dbf-4eff-8765-846c3a8f5266.png)

### Bookmarks Screens

![bookmark-broken](https://user-images.githubusercontent.com/6643505/149812557-80b1ea03-482c-4cf3-990a-63c77629eb7f.png)

### Custom Search Engine Screens

![quick-search-broken](https://user-images.githubusercontent.com/6643505/149816040-715b5173-be30-4505-b778-8c279e0d166e.png)

## Steps to Reproduce 
  1 .Launch the application
  2. Check unnecessary spaces shown in the screenshots above

**Expected result:**

Uncessary Header Paddings Should be removed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.34

**Device details:** 
iOS device with iOS 15

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by Uni-verse** [comment]
Verification completed on  using 1.35 `(22.1.24.16)`

**PASSED** on `iPhone 12 Pro` running `iOS 15.1.1`
**PASSED** on `iPhone X` running `iOS 14.4.2`

- Verified Search Suggestion Screen
- Verified Bookmarks Screen
- Verified Custom Search Engine Screen

Search Screen | Search Screen 
----------------|----------------
![IMG_2362](https://user-images.githubusercontent.com/17885425/150851936-ef4d2637-c51f-49b6-9e99-d6acc3e068a6.PNG) | ![IMG_2363](https://user-images.githubusercontent.com/17885425/150851944-5b59be4e-d568-4476-b173-408eba42f1ef.PNG) 
-----------------------

Bookmarks | Bookmarks Folder 
----------------|----------------
![IMG_2364](https://user-images.githubusercontent.com/17885425/150851946-b3aad409-28c6-4fa5-820f-ee733cbda914.PNG) | ![IMG_2365](https://user-images.githubusercontent.com/17885425/150851948-b6e4bb77-8ba0-4d5b-87e8-f4a41d361fa2.PNG) 

Quick Search Engine | Custom Search Screen 
----------------|----------------
![IMG_2366](https://user-images.githubusercontent.com/17885425/150851961-a2e91a22-ba30-468b-baf7-ae266f30ab8f.PNG) | ![IMG_2367](https://user-images.githubusercontent.com/17885425/150851964-def62205-e95b-457b-99a9-d29208933e5f.PNG)

**Comment by Uni-verse** [comment]
Verification **PASSED** on `iPad (7th Gen)` running `iOS 15.2.1` using build version `1.35 (22.1.24.23)`

- Verified Search Suggestion Screen
- Verified Bookmarks Screen
- Verified Custom Search Engine Screen

Search | Bookmarks | Settings
-|-|-
![IMG_0112](https://user-images.githubusercontent.com/17885425/151064353-cad1d3ef-66e1-4b4b-90c7-441eb6d969f4.PNG) | ![IMG_0119](https://user-images.githubusercontent.com/17885425/151064838-86d177e7-5381-4361-ac49-4290844a42fb.PNG)![IMG_0118](https://user-images.githubusercontent.com/17885425/151064856-84de6707-90c7-489d-9352-245811bb2ea7.PNG) | ![IMG_0117](https://user-images.githubusercontent.com/17885425/151064302-27ab32d7-2ef4-4e09-af49-a92f8410c1d8.PNG) |![IMG_0116](https://user-images.githubusercontent.com/17885425/151064323-7f1d2684-be24-4ae2-96ff-11fff0bc5132.PNG)
