### ISSUE TITLE
Search Suggestions fail for Custom Search Engine After Relaunch

### ISSUE THREAD

**Issue by ACodingGenie** [brave/brave-ios#4862]
### Description: 
Adding a custom search engine via `Menu` ---> `Add Search Engine` allows the search suggestions to work properly. However, if you relaunch Brave, they no longer work and the search engine has to be deleted and re-added. This can be quite frustrating and not a new issue.

### Steps to Reproduce 
  1. Add a custom search engine like SearX or Whoogle using `Menu` --> `Add Search Engine`
  2. Assign that search engine to be the default in `Standard Tab` in `Search Engine` settings
  3. Ensure `Show Search Suggestions` is toggled on.
  4. DO NOT CLOSE Brave and try to search for something.
  5. Notice how the search suggestions are populating.
  6. Now close Brave `completely`using the `App Switcher`
  7. Relaunch Brave and search for something.
  8. Search suggestions are no longer populating.

**Actual result:** 
Search suggestions don't show up after relaunching Brave and search engine has to be deleted and re-added.

**Expected result:**
Search suggestions should work normally regardless just like a search engines built into Brave.

**Reproduces how often:**
Easily

**Brave Version:**
v1.34 (22.1.10.19)

**Device details:** 
iPhone SE 2020. iOS 15.2.1

**Comment by Uni-verse** [comment]
Verification completed using 1.38 (22.4.25.21)

Devices:
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad (7th Gen) | iOS 15.2.1

- Verified STR per https://github.com/brave/brave-ios/issues/4862#issue-1106260741
- Ensured search suggestion are shown using custom search engine after relaunching Brave app 

https://user-images.githubusercontent.com/17885425/165631463-d13943dd-142b-4f1e-a2b9-248e7085fa21.MP4
