### ISSUE TITLE
Add skipValidation flag to request quota on swap

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4869]
Similar to https://github.com/brave/brave-browser/issues/20572. This also needs to get fixed on iOS and released ASAP.

```
0x team is pushing a fix that is going to break our current swap from ERC20 token if not enough allowance.
```

CCing @kylehickinson @anthonypkeane @bsclifton @srirambv

**Comment by kjozwiak** [comment]
Closing as @kylehickinson pulled in the latest b-c and created `1.34.1 (22.1.20.22)`

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.2 running 1.35(22.1.20.22)
- Verified steps from [brave/brave-core#11903](https://github.com/brave/brave-core/pull/11903)

Activate Token | Confirm Activation | Swap Enabled
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/150523593-684fcca7-edd5-4b83-8bbd-db93b6304e98.png) | ![image](https://user-images.githubusercontent.com/17010094/150523600-37f69924-3b8a-48d7-afdc-9e58d073e84b.png) | ![image](https://user-images.githubusercontent.com/17010094/150523609-e5e88d73-1a2b-4816-9b51-cba247ebffa3.png)
