### ISSUE TITLE
Some HTML properties not configurable in Brave-iOS

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#4871]
### Description: 
- HTMLMediaElement, HTMLAudioElement, and HTMLVideoElement do not have a configurable `src` attribute.

### Steps to Reproduce 
  1. Visit: `https://app.close.com/`

**Actual result:** 
- Login screen not showing

**Expected result:**
- Login screen should show.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
All

**Device details:** 
All

**Website problems only:**
- Yes that specific website only. 
- The `HTMLMediaElement.src` property is being redefined by the website developers. I do not see anywhere in `ECMAScript` that says it must be configurable or not so it seems to be implementation defined(??)

### Additional Information
- Solution is to default to whatever `WebKit` implements. This might break playlist and/or video and audio for some website that decides to change the native implementation of the property (especially if they don't call the original function [trampoline]), but not sure.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 12` running `iOS 15.1.1` using `1.35 (22.1.24.23)`

**`1.34 (22.1.10.19)`** | **`1.35 (22.1.24.23)`**
--------------------|--------------------
![IMG_0533](https://user-images.githubusercontent.com/2602313/150891451-ba4e5aa2-255d-48d7-b0c8-146c7f832d5a.png) | ![IMG_0534](https://user-images.githubusercontent.com/2602313/150891464-0fd7c94f-752b-4dde-9ade-c755c0c137e2.png)

------------------------

Verification **PASSED** on `iPhone 11` running `iOS 14.7.1` using `1.35 (22.1.24.23)`

**`1.34 (22.1.10.19)`** | **`1.35 (22.1.24.23)`**
--------------------|--------------------
![IMG_3766](https://user-images.githubusercontent.com/2602313/150891109-c1e7454b-9c14-4927-80c7-9e97cf638af9.png) | ![IMG_3767](https://user-images.githubusercontent.com/2602313/150891126-d1d92592-7fce-4c57-8adf-3f219260a77b.png)

------------------------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.2` using `1.35 (22.1.24.23)`

**`1.34 (22.1.10.19)`** | **`1.35 (22.1.24.23)`**
--------------------|--------------------
![IMG_0349](https://user-images.githubusercontent.com/2602313/150891875-4c1f30b9-8ef4-468d-9583-1d0381be5460.png) | ![IMG_0350](https://user-images.githubusercontent.com/2602313/150891899-2e80ed2f-d5c4-4c51-87e4-492ce3ec44ae.png)
