### ISSUE TITLE
Onboarding screen reorganization

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4876]
We want to remove first screen and deprecate the intention to check user's clipboard for referral code.

**Comment by Uni-verse** [comment]
Verification completed using` 1.36 (22.2.28.23)`

**PASSED** on `iPhone 12 Pro | iOS 15.1.1`
**PASSED** on `iPhone X | iOS 14.4.2`
**PASSED** on `iPad (7th Gen) | iOS 15.2.1`

Test Scenario: https://github.com/brave/brave-ios/pull/4989#issue-1140108914

- Copy some random text to your clipboard
- Fresh install the app
- Verify that there is no screen that asks for your clipboard, the first screen should be 'Welcome to Brave - Let's go'

https://user-images.githubusercontent.com/17885425/156424567-d2e55c98-49de-4e8c-9f51-5f1a9db007bc.mov
