### ISSUE TITLE
Base work for allowing user to share playlist folders

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4877]
Look for `Playlist Shared folders iOS implementation spec` for more details

**Comment by Uni-verse** [comment]
Verified using version `1.43 (22.9.9.14)`

Test Devices:
iPhone XR running iOS 15.x
iPhone 12 Pro running iOS 16.x
iPhone X running iOS 14.4.2
iPad running iPadOS 15.x

Spec: https://docs.google.com/document/d/12TPQzwHKTfSVxrK7ULzJbLqkFVdOENYqVY5Tygi2II4/edit

**Landing Page** ( playlist.bravesoftware.com/{Folder_Name} ) 

Case: Brave not installed (Safari or Chrome)

- Verified URL link and App Store link is displayed on landing page when brave is not installed
- Verified that the link can be copied and contains correct URL
- Verified tapping on the app store link will launch the brave app download page

Example | Example
-|-
![IMG_3609](https://user-images.githubusercontent.com/17885425/190019267-cd0d2234-eccf-47ff-9ee9-55fd05ce7638.PNG) | ![IMG_0587](https://user-images.githubusercontent.com/17885425/190019408-6fd733f6-5c73-4081-b41c-552a28fc31fe.PNG)

Case: Brave Installed 

- Verified the Brave Playlist button is displayed on the landing page when brave is downloaded
- Tapping the Playlist button on the landing page will launch the playlist page in the app and load the shared playlist

Example | Example
-|-
![IMG_0585](https://user-images.githubusercontent.com/17885425/190019779-6a6e8363-47ef-4d22-ac46-0c8b77d88aab.PNG) | ![IMG_3607](https://user-images.githubusercontent.com/17885425/190019929-361adbdd-ba44-4aab-8f02-c316f8f1fa3e.PNG)


**Playlist UI**

- Verified user is able to play videos before adding playlist
- Verified Tapping `+Add` will show `Managing your Playlist data` modal. `+Add` button will be replaced with 3 dot menu in the sidebar header. 
- Verified playlist is added to the users lists when tapping `Add playlist now`
- Verified Playlist settings will be launched when tapping `Settings`
- Verified edit folder name will be shown when user tries to Rename shared playlist using the 3 dot menu
- Verified selecting Save Offline Data will automatically download the videos if auto-save is disabled
- Verified Playlist is deleted when tapping `Delete Playlist`
- Verified Swipe sharing/offline saving functionality 
- Verified Swiping to delete will remove shared playlist in folder view
- Verified a loading animation is present while the shared playlist is being loaded

UI (Loading Shared Playlist)  | +Add button  | Add Modal | Folder View | Menu
-|-|-|-|-
![IMG_3601](https://user-images.githubusercontent.com/17885425/190020838-2206ec7a-41f5-4f78-934c-8dc2e7b6ad75.PNG) | ![IMG_3605](https://user-images.githubusercontent.com/17885425/190020911-d8508529-0952-4b12-85ce-d0e80271bbcd.PNG) |  ![IMG_3602](https://user-images.githubusercontent.com/17885425/190020855-76fd03d0-e9e7-4977-b674-c1368e9c0c6e.PNG) | ![IMG_3604](https://user-images.githubusercontent.com/17885425/190020878-8dc37d66-4be5-4bdd-a4da-1d4a0be03f29.PNG) | ![IMG_3610](https://user-images.githubusercontent.com/17885425/190021567-d2a14ec0-cc6f-45c6-8e34-555136f2c0e2.PNG)


UI (Loading Shared Playlist)  | +Add button  | Add Modal | Folder View | Menu
-|-|-|-|-
![IMG_0575](https://user-images.githubusercontent.com/17885425/190021184-ef002e69-c8f8-412b-856e-eff31bf034fc.PNG) | ![IMG_0576](https://user-images.githubusercontent.com/17885425/190021185-a48e06a3-6c2d-43d8-a4ff-ab19fcfdd11a.PNG) | ![IMG_0578](https://user-images.githubusercontent.com/17885425/190021200-a9863c0b-3fed-4c8e-b9a5-7c65c03475d7.PNG) | ![IMG_0570](https://user-images.githubusercontent.com/17885425/190021270-8ab30b6b-e586-43f9-b47d-ffa0ad2f176f.PNG) | ![IMG_0589](https://user-images.githubusercontent.com/17885425/190021611-4f089c72-972f-401a-8732-e98bf7521d4a.PNG)

**Upgraded Profile**

- Verified tapping the playlist share button from the landing page will open the playlist on an upgraded profile

**Sync Now**

- Verified Syncing will update the shared playlist if changes were made by the creator(Changed items from 10 to 9 in this case) using `Sync Now` in the 3 dot menu

Before Syncing | After Syncing
-|-
![IMG_0570](https://user-images.githubusercontent.com/17885425/190023402-29aef08e-6079-4ebe-8f95-593c7569d214.PNG) | ![IMG_0590](https://user-images.githubusercontent.com/17885425/190023285-8fa461d5-c09e-444b-9205-b38496988804.PNG)
