### ISSUE TITLE
Integrate with Guardianconnect

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4878]
https://github.com/GuardianFirewall/GuardianConnect

**Comment by Uni-verse** [comment]
Verified using version `1.42 (22.8.10.15)`

Test Devices:
iPhone 12 | iOS 15.5
iPhone X | iOS 14.4.2
iPad (7th Gen) | iPadOS 15.5

Test Plan: https://github.com/brave/brave-ios/pull/5495#issue-1266649504

- Purchased `new subscription` of VPN with `new profile` on version `1.41` and confirmed its enabled, upgraded build to `1.42` and ensured VPN was still connected. 
- Purchased new subscription of VPN with `new profile` and confirmed profile was added and VPN is working as expected. 
- Verified user is able to change regions/location in the settings and host is updated.
- Verified user is connect successfully to VPN after going through the restore flow with an `existing subscription`. 
- Verified `VPN` is working as expected on `iOS 14.x` on new profile and also upgraded profile. 
- Verified user is able to `disconnect` from the VPN using the menu/settings switch 
- Verified user is able to `remove` the `VPN profile` from the `device settings`

iPhone happy path VPN flow
1 | 2 | 3 | 4 |5
-|-|-|-|-
![IMG_3418](https://user-images.githubusercontent.com/17885425/184253286-dda558d1-ed13-4e3b-a402-6e6ea62c2857.PNG) | ![IMG_3419](https://user-images.githubusercontent.com/17885425/184253293-8d9d4c09-837d-4447-9cde-546946713aa8.PNG) | ![IMG_3420](https://user-images.githubusercontent.com/17885425/184253295-3002d9a5-8c35-42b8-9107-f6a2833c0846.PNG) | ![IMG_3421](https://user-images.githubusercontent.com/17885425/184253297-08276e21-3ddc-48f9-b7f8-87c2e5a4a744.PNG) | ![IMG_3422](https://user-images.githubusercontent.com/17885425/184253299-4f7c7442-14c6-4b87-9b71-e64dd38eee75.PNG)

iPad happy path VPN flow
1 | 2 | 3 | 4 | 5 | 6
-|-|-|-|-|-
![IMG_0508](https://user-images.githubusercontent.com/17885425/184253427-4eee6207-518f-47ef-8be0-4e801ed49c4b.PNG) | ![IMG_0509](https://user-images.githubusercontent.com/17885425/184253436-fc0e3e04-6e68-459a-b72e-5cea589b9ca1.PNG) | ![IMG_0510](https://user-images.githubusercontent.com/17885425/184253443-c5ea6f4c-a0fd-4ebb-9634-36be036cd3cc.PNG) | ![IMG_0511](https://user-images.githubusercontent.com/17885425/184253448-8f4f9cd4-1d11-41ac-8f3f-7ee81ed9d29f.PNG) | ![IMG_0512](https://user-images.githubusercontent.com/17885425/184253451-93b30693-b88f-4ec0-8e04-1a1ccebdfdc5.PNG) | ![IMG_0513](https://user-images.githubusercontent.com/17885425/184253459-995d1b15-9e71-4c39-a5d6-b058679979b7.PNG)
