### ISSUE TITLE
New tab doesn't increase count for Trackers blocked

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#488]
### Description: 
New tab doesn't increase count for Trackers blocked

### Steps to Reproduce 
  1. Visit a script heavy site like youtube.com/slashdot.org/theverge.com
  2. Check blocked items on shields 
  3. Open a new tab, same blocked count is shown for ads while tracker protection is always 0 no matter how many sites you visit

**Actual result:** 
New tab doesn't increase count for Trackers blocked

**Expected result:**
Ad blocked count and trackers blocked count should be independently shown on new tab 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.11.28.22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
Fix: Combine ads and trackers UI, there should only be one option for this, just like the domain shields panel (they are combined there).
