### ISSUE TITLE
Items are not deleting from Playlist - UI not updating

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4885]
### Description: 

Reported by a user https://appfigures.com/reviews/42132121512LQO0K0IIsuTm95iux_cOSCw?lang=en and by Brendan

https://user-images.githubusercontent.com/7606853/150652653-892391ed-3a50-42d3-9f47-acfd4919c785.MP4

### Steps to Reproduce 
  1. Add an item to Playlist
  2. Swipe to try and delete it
  

**Actual result:** 
UI won't refresh and the item appears to be not deleted (when fixing the bug please check that the video is in fact deleted)

**Expected result:**
UI should update and the items should be deleted

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.35 (22.1.14.22)

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verification completed using `1.35 (22.1.26.20)`

**PASSED** on iPhone 12 Pro running `iOS 15.1.1`
**PASSED** on iPhone X running `iOS 14.4.2`
**PASSED** on iPad (7th Gen) running` iOS 15.2.1`

https://github.com/brave/brave-ios/issues/4885#issue-1111664567
- Verified user is able to add video to playlist 
- Verified user is able to remove the video from playlist by swiping to delete

- Verified using playlist in private tab
- Verified user is able to disable offline data, share video in playlist
- Verified user is able to remove video by using the playlist icon from address bar
- Verified video in playlist queue is downloaded successfully

iPhone | iPad
-|-
https://user-images.githubusercontent.com/17885425/151275847-954b4499-15ff-4233-8e14-0eda9895dbbc.MP4 | https://user-images.githubusercontent.com/17885425/151457847-360673f1-d0d2-483c-a584-dc39e6813409.MP4

**Comment by Uni-verse** [comment]
**Blocked** by https://github.com/brave/brave-ios/issues/4904

**Comment by Uni-verse** [comment]
> **Blocked** by #4904

Fix Verified - https://github.com/brave/brave-ios/pull/4907
