### ISSUE TITLE
Added and removed favourites show up as search suggestions on private tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#489]
### Description: 
Added and removed favourites show up as search suggestions on private tab

### Steps to Reproduce 
  1. Visit a few sites and add them as favourites
  2. Delete a couple of them 
  3. Open a new private tab and type `h`, newly added and removed favourites along with default ones show up as site suggestions. Newly added one's doesn't have the ⭐️ next to them only the default ones

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/49211763-4d514700-f3e6-11e8-9523-b1f298d4773b.png)

**Expected result:**
No idea whats the expected behaviour. @jhreis @kylehickinson  need to confirm the expected behaviour

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.11.28.22)

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
I'm not sure I understand the issue here, I believe this is correct since you still visited those pages and therefore when it populates the url suggestions (via a mix of bookmarks, favourites, history, etc), it would populate that site you visited as well.

**Comment by jhreis** [comment]
@srirambv As @kylehickinson pointed out, these will show up as suggestions (expected behavior), however, is there an issue with the ⭐️? 

> Newly added one's doesn't have the ⭐️

This is not correct, also, are removed one's also still stared?

**Comment by srirambv** [comment]
@jhreis removed favourites are not listed. Its only the new additions that show up without the ⭐️ and default one's that are still there show with ⭐️

**Comment by jhreis** [comment]
@srirambv newly added ones should still have ⭐️ if they are bookmarked at all. That should be staying in sync. So if that is the case, please file that.

However, this functions as normal, at least given current information. History is still a huge factor here, and any favorited website in normal mode would be in history, leading to being displayed in a search suggestion.
