### ISSUE TITLE
using `MOZMBA` as attribution when searching using Bing

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4890]
### Description: 

When searching via Brave within iOS, we use `MOZMBA` as the search attribution. I'm pretty sure this belongs to Mozilla which means any Brave user searching with Bing is generating revenue for Mozilla. @iccub confirmed that we basically use the same code we pulled so I'm pretty sure this belongs to Mozilla.

```
https://www.bing.com/search?q=test&pc=MOZB&form=MOZMBA
```

### Steps to Reproduce

  1. launch Brave
  2. Using Bing, perform a search and you'll notice `pc=MOZB&form=MOZMBA` being used as the search attribution

**Actual result:** 

Using the following search attribution when using Bing:

```
https://www.bing.com/search?q=test&pc=MOZB&form=MOZMBA
```

**Expected result:**

Should be using something else other than `MOZMBA` which belongs to Mozilla.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases mentioned above.

**Brave Version:** 

`1.34 (22.1.10.19)` - **Reproduced**
`1.35 (22.1.24.16)` - **Reproduced**

**Device details:** 

* `iPhone 11` running `iOS 14.7.1` - **Reproduced**
* `iPhone 12` running `iOS 15.1.1` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @iccub @bsclifton @janypiotrowski

**Comment by kjozwiak** [comment]
Desktop & Android has a similar issue as per https://github.com/brave/brave-ios/issues/4890 but uses `CHROMN` rather than `MOZMBA`.

**Comment by Uni-verse** [comment]
Verification completed using build version `1.35 (22.1.26.20)`

**PASSED** on `iPhone X` running `iOS 14.4.2`
**PASSED** on `iPhone 12 Pro` running `'iOS 15.1.1'`
**PASSED** on `iPad (7th Gen)` running `iPadOS 15.2.1`

- Verified MOZMBA attribution is removed when using Bing Search in a new tab - https://github.com/brave/brave-ios/issues/4890#issue-1113109543
-Verified removed while searching in private tab. 

iPhone | Tablet 
-|-
![IMG_2405](https://user-images.githubusercontent.com/17885425/151263808-d81966d2-1954-4b6c-9923-7b3915191f7e.PNG) | ![IMG_0129](https://user-images.githubusercontent.com/17885425/151263899-c4cd17e7-6270-4648-b1ae-a2ba522497b6.PNG)
