### ISSUE TITLE
can't dismiss/slide down the `Quick Search` settings menu

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4891]
### Description: 

Attempting to dismiss the `Quick-Search Engines` settings menu by sliding it downwards doesn't work. User needs to click on `< Search` to go back to the main `Search` settings page to then be able to dismiss the settings page.

### Steps to Reproduce

  1. install/launch Brave (doesn't matter which version as this is currently in the release)
  2. go into `Settings` -> `Search Engines` -> `Quick-Search Engines`
  3. attempt to dismiss the settings page by sliding the modal/page down (doesn't work)
  4. go back to the main search settings page by tapping on `< Search` and dismiss it by sliding it down (works as expected)

**Actual result:** 

Can't dismiss the `Quick-Search Engines` settings page by sliding it down which is the default behaviour for our settings pages.

**Expected result:**

Users should be able to dismiss the  `Quick-Search Engines` settings page by sliding it down.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases outlined above.

**Brave Version:** 

`1.34 (22.1.10.19)` - **Reproduced**
`1.35 (22.1.24.16)` - **Reproduced**

**Device details:** 

* `iPhone 11` running `iOS 14.7.1` - **Reproduced**
* `iPhone 12` running `iOS 15.1.1` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @iccub @soner-yuksel

**Comment by srirambv** [comment]
If you tap on the top of settings menu then it hides. Thats a work around if needed. It works on all menu items

**Comment by Uni-verse** [comment]
Verified using version `1.43 (22.9.2.15)`

Test Devices:
`iPhone 12 Pro` & `XR `| `iOS 15.5`
`iPhone X` | `iOS 14.4.2`

Using STR from https://github.com/brave/brave-ios/issues/4891#issue-1113131749

- Verified user is able to dismiss the settings menu by sliding down from the Quick Search page. 
- Verified on iOS 14.x devices
- Verified on iOS 15.x devices

https://user-images.githubusercontent.com/17885425/188990509-213450f3-6be9-45f2-8db0-5cffb1f78cbf.MP4
