### ISSUE TITLE
Searching a token and loading the details doesn't allow for the Send/Swap buttons to work 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4893]
### Description: 
Searching a token and loading the details doesn't allow for the Send/Swap buttons to work 

### Steps to Reproduce 
Scenario 1:

  1. Clean profile
  2. Click on search asset 
  3. Search for BAT
  4. Select BAT from the list, loads asset details
  5. Tap on Buy/Send/Swap doesn't load the respective action sheet

Scenario 2:

  1. Clean profile
  2. Add a custom asset say TUSD
  3. Open asset detail from search result
  4. Tap on Send doesn't load
  5. Close the asset page and click on quick action button
  6. Select Send, doesn't load the send token action page
  7. Select Swap, loads close and select send loads send action page

**Actual result:** 

Scenario 1 | Scenario 2
-- | --
<video src=https://user-images.githubusercontent.com/17010094/150954408-fc334196-d3d3-4d01-90a1-a5bbbcf43667.mp4> | <video src=https://user-images.githubusercontent.com/17010094/150954428-9d105624-756b-4220-9888-d76b83bb2cda.mp4>

**Expected result:**
Should be able to select action items from asset details page

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.35(22.1.24.23)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
cc: @nuo-xu

**Comment by Uni-verse** [comment]
Verification completed using `1.35 (22.1.27.21)`

**PASSED** on `iPhone 12 Pro` running `iOS 15.1.1`
**PASSED** on `iPhone X running` `iOS 14.4.2`
**PASSED** on `iPad (7th Gen)` running `iPadOS 15.2.1`

https://github.com/brave/brave-ios/issues/4893#issue-1113673518

**Verified Scenario**: Tapping on Buy/Send/Swap buttons in the asset details after searching will display the respective action sheet. 
**Verified Scenario**: After adding a custom asset, user is able to user the Send/Swap buttons after loading asset details from search result.
**Verified Scenario**: User is able to load the swap page using the quick action buttons.

iPhone | iPad
-|-
https://user-images.githubusercontent.com/17885425/151629028-3eb2a092-a01e-472a-b8a4-146ae763b317.MP4 | https://user-images.githubusercontent.com/17885425/151629184-8d1b5aa5-a840-481e-b8f7-3ed12f3c5770.MP4
