### ISSUE TITLE
Opening Brave Wallet from landscape orientation doesn't force portrait

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4896]
### Description: 

If you open Brave Wallet while you're in landscape it can get into some weird states

### Steps to Reproduce 
  1. Rotate to landscape
  2. Open the menu
  3. Open Brave Wallet

**Actual result:**

Brave Wallet presents in landscape despite only supporting portrait mode. Also further rotation can cause some strange bugs:

![IMG_5130](https://user-images.githubusercontent.com/529104/151062923-91c05b16-8422-4f84-a513-44ca9f3d1700.PNG)

**Expected result:**

Should force into portrait mode and not bug out while rotating

**Reproduces how often:** Always

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.36 (21.2.11.1) 
- Verified opening Brave Wallet in landscape mode forces portrait mode
- Encountered [#4982](https://github.com/brave/brave-browser/issues/36884)
--------
Verification passed on iPhoneXR with iOS 15.3 running 1.36 (21.2.11.1) 
- Verified opening Brave Wallet in landscape mode forces portrait mode
- Encountered [#4982](https://github.com/brave/brave-browser/issues/36884)
--------
Verification passed on iPad Pro with iOS 15.4 (Beta 2) running 1.36 (21.2.11.1) 
- Verified opening Brave Wallet in landscape mode doesn't force portrait mode
- Verified switching between landscape and portrait mode fits the wallet UI accordingly
