### ISSUE TITLE
Brave Search suggestion shows 'beta' label

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4899]
### Steps to Reproduce 
  1. Set BraveSearch as default
  2. Enable search suggestion
  3. Start typing something

**Actual result:** 
![Image from iOS](https://user-images.githubusercontent.com/6950387/151210840-79761a4a-fbd4-447c-b446-9af901d0b924.jpg)

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verification completed using build version `1.35 (22.1.26.17)`

**PASSED** on `iPhone X` running `iOS 14.4.2`
**PASSED** on `iPhone 12 Pro` running `'iOS 15.1.1'`
**PASSED** on `iPad (7th Gen)` running `iPadOS 15.2.1`

- Verified 'Brave Search' is shown beneath the search field when brave is default search engine - https://github.com/brave/brave-ios/issues/4899#issue-1115253577

iPhone 12 | iPhone X | iPad
-|-|-
![IMG_2403](https://user-images.githubusercontent.com/17885425/151249110-51979297-f60c-4312-a2da-06073166df0b.PNG) | ![IMG_2600](https://user-images.githubusercontent.com/17885425/151249118-f3a2e80b-8ada-4d34-ade5-e68775e2d18d.PNG) | ![IMG_0128](https://user-images.githubusercontent.com/17885425/151249098-482833fe-3fc4-4de0-ab4e-6b6849c80a39.PNG)
