### ISSUE TITLE
Site shield setting set in PB tab gets propagated to normal tabs

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#490]
### Description: 
Site shield setting set in PB tab gets propagated to normal tabs as well

### Steps to Reproduce 
  1. Visit https://wired.com in a new private tab
  2. Enable Fingerprint protection from shields for that site
  3. Close PB tab and open the same site in normal tab, shields settings are propagated to normal tab 

**Actual result:** 
Site shield setting set in PB tab gets propagated to normal tabs as well

**Expected result:**
Changes should only persist in private tabs

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.11.28.22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by tildelowengrimm** [comment]
If this targets 1.7.1, that'd be _okay_, I guess, if it has to be. But it's pretty important.
