### ISSUE TITLE
Deleting Item from CoreData does not update the NSFetchResultControllers

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#4902]
### Description: 
- Deleting an item in CoreData deletes the item, but only updates controllers when restarting the app or the screen.

### Steps to Reproduce 
  1. See the PR's Test-Plan: https://github.com/brave/brave-ios/pull/4901

**Actual result:** 
- GUIs don't update

**Expected result:**
- UIs should update

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced.

**Brave Version:** 
Any

**Device details:** 
Any

**Comment by kjozwiak** [comment]
Closing this off as https://github.com/brave/brave-ios/pull/4901 was merged and QA already received a TF build with the fix.

**Comment by Uni-verse** [comment]
Verification completed using `1.35(22.1.27.21)` 

**PASSED** on `iPhone 12 Pro` running `iOS 15.1.1`
**PASSED** on `iPhone X` running `iOS 14.4.2`
**PASSED** on `iPad (7th Gen)` running `iPadOS 15.2.1`

https://github.com/brave/brave-ios/pull/4901#issue-1115381231
- Verified deleting item from playlist is immediately reflected in the UI
- Verified deleting recent searches is immediately reflected in the UI
- Verified playlist functionality
- Verified recent search functionality
