### ISSUE TITLE
JavaScript operators appear instead of the destination URL as headers of long-press menus launched from certain hyperlinks & link buttons

### ISSUE THREAD

**Issue by brnnnfx** [brave/brave-ios#4905]
### Description: 
JavaScript operators appear instead of the destination URL as headers of long-press menus launched from certain hyperlinks & link buttons

### Steps to Reproduce 
  1. On Brave for iOS, navigate to [comc.com](https://www.comc.com/)
  2. In the search bar at the top of the page, search for a popular athlete, such as "Sidney Crosby"
  3. Long-press on a price underneath one of the sports cards to show the long-press menu options > look at the menu header
  4. Dismiss the menu
  5. Tap on one of the sports cards to open its page
  6. In the top right corner, long press on the hyperlink 'Add item to my cart' to show the long-press menu options > look at the menu header

**Actual result:**

You'll see unhelpful noise in the form of the JavaScript operator / function being displayed as the header, such as `javascipt:%20doNothing();` or `javascript:AddAll(######,%20null,%20null,%200,%20'username')` which is often just noise.

![image2](https://user-images.githubusercontent.com/12024098/151273896-81773bc5-1069-4a9b-9a39-aac383273446.jpg)
![image1](https://user-images.githubusercontent.com/12024098/151273891-80e9d3e9-fc5f-4743-a241-21c78b0bd826.jpeg)

**Expected result:**
Whenever possible, the header should show the destination URL so I know where it will take me.

When not possible, it should say `JavaScript` to be consistent with Google Chrome

**Reproduces how often:** 
Easily reproduced, multiple ways to reproduce

**Brave Version:** 
Brave 1.34.1 (22.1.20.22)

**Device details:** 
iPhone 7 Plus running iOS 15.2.1

**Website problems only:**
Checked with Brave Shields down

Confirmed Google Chrome does not have this issue; it either displays the destination URL or just `JavaScript` in the menu header

### Additional Information
This third screenshot is from an button to 'Buy it now' if you are logged in with an account.

![image3](https://user-images.githubusercontent.com/12024098/151273901-0a7e7cf7-c968-4bd1-b4bd-20cb3691afd5.jpg)

**Comment by Brandon-T** [comment]
Fixed in: https://github.com/brave/brave-ios/pull/6760
