### ISSUE TITLE
fix spacing at both ends of the URL bar

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4906]
### Description: 

We should fix the spacing in the URL bar at both ends. As per the example mentioned below, you can tell that there's more spacing on the right hand side compared to the left hand side. We should make this symmetrical.

### Steps to Reproduce
 
  1. launch brave (used `1.35 (22.1.26.20)` in this case but any version will do)
  2. load any website and notice the spacing at both ends of the URL bar (not symmetrical)

**Actual result:** 

![image](https://user-images.githubusercontent.com/2602313/151275998-8aa81277-1fdf-446b-8499-3d0fc1ddf981.png)

**Expected result:**

Spacing on both ends of the URL bar should be even/symmetrical.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases outlined above.

**Brave Version:** 

* `1.35 (22.1.26.20)` - **Reproduced**
* `1.34.1 (22.1.20.22)` - **Reproduced**

**Device details:** 

* `iPhone 12` running `iOS 15.1.1`
* `iPhone 11` running `iOS 14.7.1`

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @kylehickinson

**Comment by Uni-verse** [comment]
Verified using `1.37 (22.3.29.15)`

Devices:
iPhone running iOS 15.4
iPhone running iOS 14.4.2
iPad running 15.2.1

- Verified space on both ends of url is equal
- Verified url spacing when user hides rewards icon and/or enables shortcut to bookmarks 

iOS 14 | iOS 15
-|-
![IMG_2634](https://user-images.githubusercontent.com/17885425/161319981-29eb5445-0b4e-4fbf-a484-4609e220a7cb.jpg) | ![IMG_2572](https://user-images.githubusercontent.com/17885425/161319733-2117c06d-fbd8-4a36-b412-6673ca299bc4.jpg)

iPad
![IMG_0236](https://user-images.githubusercontent.com/17885425/161320418-bdf1bbf1-4464-447d-8d9b-c975ecc21773.jpg)
