### ISSUE TITLE
Removing app from memory and relaunch causes empty tabs

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#491]
### Description: 
Removing app from memory and relaunch causes empty tabs

### Steps to Reproduce 
  1. Visit a few sites in each new tab
  2. Go to settings and enable all shields switches
  3. Remove app from memory 
  4. Relaunch the app, all tabs just retain the site name but is empty, no url, shields shows generic shields text

**Actual result:** 
https://drive.google.com/open?id=1IiJbbmKpJsoGKdBCPpYtejn4xnK-g1jv

**Expected result:**
Should not lose webview state after app is relaunched

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.11.28.22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by danishjafri88** [comment]
#482 fixes this issue

**Comment by danishjafri88** [comment]
Fixed in #498
