### ISSUE TITLE
Brave Wallet / Brave Swap: Displaying Brave DEX Aggregator 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4911]
iOS version of https://github.com/brave/brave-browser/issues/20463

Needs to replace `Brave Dex Aggregator` on quick action sheet to `Swap tokens and assets`

**Comment by Uni-verse** [comment]
Verification completed using Beta App version 1.37 (22.3.11.18)

```
iPhone 12 Pro | iOS 15.1.1
iPhone X | iOS 14.4.2
iPad (7th Gen) | iOS 15.2.1

```
- Verified copy change to `Swap tokens and assets` under `Swap` quick action
https://github.com/brave/brave-browser/issues/20463#issuecomment-1023861230

iPhone | iPad
-|-
![IMG_2523](https://user-images.githubusercontent.com/17885425/158494080-694aa0c0-3aab-43f2-a9c6-d19a5b9ba03f.PNG) | ![IMG_0194](https://user-images.githubusercontent.com/17885425/158494098-23fad72f-c142-433f-bda3-f773b1b5fe16.PNG)
