### ISSUE TITLE
Show active transactions and token balances in the panel

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4912]
iOS Version of [#19533](https://github.com/brave/brave-browser/issues/19533)

**Comment by HEagle18** [comment]
@StephenHeaps do we still need this issue ? or maybe it should be edited ?

**Comment by StephenHeaps** [comment]
> @StephenHeaps do we still need this issue ? or maybe it should be edited ?

I believe this can be closed. This issue to be for displaying recent transactions button (and list) in the wallet panel, and the balance of the network token. Both were included as part of the initial ethereum dapps release. cc @srirambv 

![Simulator Screen Shot - iPhone 14 Pro - 2023-01-18 at 09 37 00](https://user-images.githubusercontent.com/5314553/213199570-fb6e1a3a-500f-4358-a5dc-352e5058e2c8.png)
