### ISSUE TITLE
Fix Brave Ads conversions

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#4914]
### Steps to Reproduce 
  1. See https://github.com/brave/brave-browser/issues/19943

**Actual result:** 
Ads are not converted

**Expected result:**
Ads should be converted

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verifications completed using build version `1.36 (22.2.11.11)`
Environment: Production (brave ads), Staging (inline ads)

**PASSED** on iPhone 12 / iOS 15.1.1

- Verified ad conversion log data 

**brave ads**

```
default	11:57:30.013653-0800	Client	[Info] [BraveCore] [ad_notification_event_clicked.cc:38] > Successfully logged ad notification clicked event
default	11:57:30.014281-0800	Client	[Debug] [BraveCore] [ads_impl.cc:761] > Successfully processed deposit for ad_notification with creative instance id 329dec71-3126-4169-923a-9b5a541e78b3 and click valued at 0
default	11:57:30.014368-0800	Client	[Info] [BraveCore] [confirmations.cc:69] > Confirming click for ad_notification with transaction id 85084dcf-c9de-47ff-b285-26c662b65bfd and creative instance id 329dec71-3126-4169-923a-9b5a541e78b3

```
**inline ads**

```
default	13:53:09.144752-0800	Client	[Debug] [BraveCore] [inline_content_ad_event_clicked.cc:23] > Clicked inline content ad with uuid 19e89e41-4b5c-471b-8cd6-5622123240d8 and creative instance id cbe9f40d-257f-429c-939c-39f3d05a0372
default	13:53:09.156605-0800	Client	[Debug] [BraveCore] [ads_impl.cc:761] > Successfully processed deposit for inline_content_ad with creative instance id cbe9f40d-257f-429c-939c-39f3d05a0372 and click valued at 0
default	13:53:09.156641-0800	Client	[Info] [BraveCore] [confirmations.cc:69] > Confirming click for inline_content_ad with transaction id 34fbf15a-46b7-4863-b6fb-0ed40bfa0d64 and creative instance id cbe9f40d-257f-429c-939c-39f3d05a0372
default	13:53:09.156677-0800	Client	[Info] [BraveCore] [redeem_unblinded_token.cc:55] > Redeem unblinded token
```

--------------

**PASSED** on iPad (7th Gen) / iPadOS 15.2.1

- Verified ad conversion log data 

**brave ads**

```
default	13:30:54.649141-0800	Client	[Info] [BraveCore] [ad_notification_event_clicked.cc:38] > Successfully logged ad notification clicked event
default	13:30:54.649169-0800	Client	[Debug] [BraveCore] [ads_impl.cc:761] > Successfully processed deposit for ad_notification with creative instance id d913fc6b-18bf-4fce-af08-6add37f67814 and click valued at 0
default	13:30:54.649228-0800	Client	[Info] [BraveCore] [confirmations.cc:69] > Confirming click for ad_notification with transaction id fcd1daff-492a-4654-81f5-881579e87d38 and creative instance id d913fc6b-18bf-4fce-af08-6add37f67814
default	13:30:54.649339-0800	Client	[Info] [BraveCore] [redeem_unblinded_token.cc:55] > Redeem unblinded token
```
**inline ads**

```
default	13:49:38.632363-0800	Client	[Debug] [BraveCore] [inline_content_ad_event_clicked.cc:23] > Clicked inline content ad with uuid a7d5bfba-408b-4045-a454-aca035a54bd6 and creative instance id cbe9f40d-257f-429c-939c-39f3d05a0372
default	13:49:38.640573-0800	Client	[Debug] [BraveCore] [ads_impl.cc:761] > Successfully processed deposit for inline_content_ad with creative instance id cbe9f40d-257f-429c-939c-39f3d05a0372 and click valued at 0
default	13:49:38.640780-0800	Client	[Info] [BraveCore] [confirmations.cc:69] > Confirming click for inline_content_ad with transaction id 3deafd0a-a042-47a2-be05-ab7f22365b17 and creative instance id cbe9f40d-257f-429c-939c-39f3d05a0372
default	13:49:38.640840-0800	Client	[Info] [BraveCore] [redeem_unblinded_token.cc:55] > Redeem unblinded token
default	13:49:38.640880-0800	Client	[Info] [BraveCore] [redeem_unblinded_token.cc:74] > CreateConfirmation

```

--------------

**PASSED** on iPhone X / iOS 14.4.2

- Verified ad conversion log data 

**brave ads**

```
default	13:42:02.275965-0800	Client	[Info] [BraveCore] [ad_notification_event_clicked.cc:38] > Successfully logged ad notification clicked event
default	13:42:02.276168-0800	Client	[Debug] [BraveCore] [ads_impl.cc:761] > Successfully processed deposit for ad_notification with creative instance id 1070e131-f8df-40f9-974f-54f5d86e9d67 and click valued at 0
default	13:42:02.276315-0800	Client	[Info] [BraveCore] [confirmations.cc:69] > Confirming click for ad_notification with transaction id 1f15e62f-fe16-41d2-83b7-7e0933b429fc and creative instance id 1070e131-f8df-40f9-974f-54f5d86e9d67
default	13:42:02.279431-0800	Client	[Info] [BraveCore] [redeem_unblinded_token.cc:55] > Redeem unblinded token
```
**inline ads:**

```
default	13:47:53.090821-0800	Client	[Info] [BraveCore] [ads_impl.cc:908] > Transferred ad for https://brave.com/careers
default	13:47:53.098869-0800	Client	[Debug] [BraveCore] [ads_impl.cc:761] > Successfully processed deposit for inline_content_ad with creative instance id cbe9f40d-257f-429c-939c-39f3d05a0372 and landed valued at 0
default	13:47:53.099262-0800	Client	[Info] [BraveCore] [confirmations.cc:69] > Confirming landed for inline_content_ad with transaction id 0d6c674f-e1b7-41ba-948d-d974f895dec7 and creative instance id cbe9f40d-257f-429c-939c-39f3d05a0372
default	13:47:53.110894-0800	Client	[Info] [BraveCore] [redeem_unblinded_token.cc:55] > Redeem unblinded token
```

**Comment by LaurenWags** [comment]
Removed QA Pass labels per discussion here: https://bravesoftware.slack.com/archives/GAA4017R7/p1645128024836109?thread_ts=1644875875.865699&cid=GAA4017R7

**Comment by Uni-verse** [comment]
Verification completed using `1.36 (22.3.3.9), braveCore 1.36.108 (99.0.4844.51)`

 Devices: `iPhone 12 Pro | iOS 15.x` , `iPhone X | iOS 14.x`, `iPad (7th Gen) | iOS 15.x`

Test Plan: https://github.com/brave/brave-browser/issues/19943#issue-1072467606

**PASS** - Force Ad for creativeInstanceId
**PASS** - Go to conversion URL: https:brave.com/?vac=DOM
**PASS** - Confirm that conversion ID is extracted into conversion queue table
**FAIL** - Confirm that conversionEnvelope is generated and sent in ads confirmation

**iOS Logs**
iOS 15: (iPhone) 
`default	13:12:14.645015-0800	Client	[Info] [BraveCore] [confirmations.cc:284] > Successfully redeemed unblinded token for ad_notification with confirmation id b88e1b6d-a28d-4002-a667-841298b1f083, transaction id 74864560-d634-4a72-a986-d5def6721797, creative instance id 0e3fa44c-edd4-4ad3-b21e-e6c93ef001c4 and conversion. You now have 4 unblinded payment tokens which will be redeemed in 0 hours, 32 minutes, 46 seconds at 1:45 PM`

iOS 15: (iPad)
`default	10:00:20.219934-0800	Client	[Info] [BraveCore] [confirmations.cc:284] > Successfully redeemed unblinded token for ad_notification with confirmation id 8ce6fe98-6698-47f1-98b9-a3f39a7e7654, transaction id 6241745e-558d-4137-bdc9-7140056f30ab, creative instance id 0e3fa44c-edd4-4ad3-b21e-e6c93ef001c4 and conversion. You now have 1 unblinded payment tokens which will be redeemed in 0 hours, 6 minutes, 38 seconds at 10:06 AM`

iOS 14: 
`default	14:39:34.166682-0800	Client	[Info] [BraveCore] [confirmations.cc:284] > Successfully redeemed unblinded token for ad_notification with confirmation id 261acb34-dde4-4255-9913-af8ec064e4bd, transaction id e9f5b658-ee19-4500-950c-e43be503e20e, creative instance id 0e3fa44c-edd4-4ad3-b21e-e6c93ef001c4 and conversion. You now have 1 unblinded payment tokens which will be redeemed in 0 hours, 38 minutes, 50 seconds at 3:18 PM
`

**https://ads-serve.bravesoftware.com/v2/confirmation/261acb34-dde4-4255-9913-af8ec064e4bd/**
{
	"blindedPaymentTokens": ["zrO+trqwgPDShe2bG/NRC/mtrZdt8YdMatu2HqjjMBQ="],
	"buildChannel": "dev",
	"creativeInstanceId": "0e3fa44c-edd4-4ad3-b21e-e6c93ef001c4",
	"payload": {},
	"platform": "ios",
	"publicKey": "JnPs9+7NSdmFflbIvMs0/6BBDt99JMgEvm+9mHNByjI=",
	"studies": [],
	"type": "conversion"
}

**Catalog used for map local:**

```
{
	"ping": 7200000,
	"version": 9,
	"campaigns": [
{
			"ptr": 1,
			"endAt": "2025-07-22T14:27:00.000Z",
			"startAt": "2021-05-20T14:27:00.000Z",
			"dailyCap": 10,
			"dayParts": [],
			"priority": 1,
			"campaignId": "9bb85ea3-f510-4047-8cbb-4ba40fe3e84d",
			"geoTargets": [{
					"code": "US",
					"name": "United States"
				}
			],
			"advertiserId": "93130af3-2def-4ecb-b836-b3772e73b3c9",
			"creativeSets": [{
					"oses": [{
							"code": "i1g4cO6Pl",
							"name": "linux"
						}, {
							"code": "_Bt5nxrNo",
							"name": "macos"
						}, {
							"code": "k80syyzDa",
							"name": "ios"
						}
					],
					"value": "0.01",
					"perDay": 100,
					"perWeek": 0,
					"channels": [],
					"perMonth": 0,
					"segments": [{
							"code": "Svp7l-zGN",
							"name": "untargeted",
							"parentCode": ""
						}
					],
					"totalMax": 200,
					"creatives": [{
							"type": {
								"code": "notification_all_v1",
								"name": "notification",
								"version": 1,
								"platform": "all"
							},
							"payload": {
								"body": "Test VAC - VAC ID from URL parameter",
								"title": "Verifiable Ad Conversion - URL",
								"targetUrl": "https://www.nytimes.com"
							},
							"creativeInstanceId": "0e3fa44c-edd4-4ad3-b21e-e6c93ef001c4"
						}
					],
					"conversions": [{
							"type": "postview",
							"urlPattern": "https://*.nytimes.com/section/world*",
							"extractExternalId": true,
							"observationWindow": 30,
							"conversionPublicKey": "eRoz/e8xAASYj47rZ73B11+RYRveZcQS8e6hC7UeeCw="
						}
					],
					"creativeSetId": "2003f580-4703-408a-aab4-881230aa4a6c",
					"splitTestGroup": ""
				}
			]
		}
	],
	"catalogId": "383783d68a5185899b2e54e4a9ea7343ed74b69x"
}
```

Logs: 
[ios_ad_conversion_conf.log](https://github.com/brave/brave-ios/files/8188951/ios_ad_conversion_conf.log)
[ios14_ad_conversion_conf.log](https://github.com/brave/brave-ios/files/8189119/ios14_ad_conversion_conf.log)
[confirm_conversion.log](https://github.com/brave/brave-ios/files/8188955/confirm_conversion.log)

**Comment by Uni-verse** [comment]
Follow up issue for conversionEnvelope - https://github.com/brave/brave-ios/issues/5059

**Comment by kjozwiak** [comment]
Labelling as `QA/Blocked` till we have a resolution for https://github.com/brave/brave-ios/issues/5059. We still need to decide if https://github.com/brave/brave-ios/issues/5059 is `release/blocking`.

**Comment by Uni-verse** [comment]
This has been resolved with https://github.com/brave/brave-ios/issues/5059
