### ISSUE TITLE
YouTube history is not saved when "block cross-site cookies" is enabled

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-ios#4916]
### Description: 
When on youtube.com (signed in), it seems that Youtube history is not recorded when the `Block cross-site cookies` option is enabled in Shields. Note that this issue was not present in the the previous version of the browser (v1.33x). I only saw the issue occur after updating to v1.34.1.

### Steps to Reproduce 
  1. Visit YouTube.com
  2. Sign into your Youtube account
  3. Visit `Library --> History` and observe your current history.
  4. Return to the home page (or search) and stream video content.
  5. Go back to `Library --> History`

**Actual result:** 
Last video(s) watched are not recorded in `History`.

**Expected result:**
Newly watched videos should be recorded in YT history.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily/always.

**Brave Version:** 
v1.34.1

**Device details:** 
iPad w/iOS 15.3

**Website problems only:**
- did you check with Brave Shields down? 
**Shields down works as the "block cross-site cookies" option is disabled.** 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
User report: 
https://community.brave.com/t/youtube-watch-history-not-working-when-black-cross-site-trackers-is-enabled/332171

**Comment by Chad90b** [comment]
is this ever going to be fixed?

**Comment by Brandon-T** [comment]
We no longer have "Block cross-site cookies" preference. It is enabled automatically now and the history is working :)
