### ISSUE TITLE
IDN domains not working

### ISSUE THREAD

**Issue by pattyland** [brave/brave-ios#4918]
### Description: 
All domains with special letters such as an ö triggers a Google search instead of display the website.

### Steps to Reproduce 
  1. Enter "ö.de" in the URL bar
  2. Hit open
  3. Be disappointed

**Actual result:** 
A Google search for "ö.de" is started

**Expected result:**
Calling up the ö.de page or its redirection to https://www.dasoertliche.de/

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Alsways

**Brave Version:** 
v.1.24.1 (22.1.20.22)

**Device details:** 
iPhone X (iOS 15.2.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.8.20)` on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.4.2
iPad - iPadOS 15.x

Using STR in https://github.com/brave/brave-ios/issues/4918#issue-1119150481

- Verified support for special characters in domains
- Verified domain page is loaded for `ö.de` directly and search is not made

Example | Example
-|-
![IMG_0067 2](https://user-images.githubusercontent.com/17885425/206781084-a9671a69-4099-4fd1-a0aa-c220486eae72.PNG) | ![IMG_4210](https://user-images.githubusercontent.com/17885425/206781144-092b3302-cb24-4ca2-b27b-e30cd095c7be.PNG)
