### ISSUE TITLE
Custom favourites show up as https://localhost:6751/about/sessionrest... in history

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#492]
### Description: 
Custom favourites show up as https://localhost:6751/about/sessionrest... in history

### Steps to Reproduce 
  1. Visit a few sites in new tab and add as favourite and open the default favourites in new tabs
  2. Enable Block scripts and fingerprint from settings and remove the app from memory
  3. Relaunch the app, go to history
  4. Newly added custom top tiles show up as `https://localhost:6751/about/sessionrest...`

**Actual result:** 
https://drive.google.com/open?id=1f7Fzz_0a7RFmxefmBQ4_914M7q9wMA7t

**Expected result:**
Should show proper site name 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.11.28.22)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
This is caused by js blocking global setting turned on and restoring a tab, it also happens with regular bookmarks. I have an idea how to fix it
