### ISSUE TITLE
Clearing recent searches does not update UI and is hard to tap

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4923]
### Description: 

The "clear" button on recent searches does not update the UI after using it. It's hit box is also too small and is difficult to tap

The clear button is too far from the edge as well

### Steps to Reproduce 
  1. Search with the Recent Searches preference enabled
  2. Open a new tab and tap on the URL bar
  3. Tap clear, and then "Clear Recent" when the action sheet appears

**Actual result:** Recent searches stay visible

**Expected result:** Recent searches should be removed from the list

**Reproduces how often:** Always

**Brave Version:** 1.34.1 Live

https://user-images.githubusercontent.com/529104/151883156-8575b125-8e5b-4e5a-b608-44237ba62012.MP4

**Comment by Brandon-T** [comment]
Should be fixed by: https://github.com/brave/brave-ios/pull/4901
Will double check and also check the `hard to tap` issue.

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 [iOS 16.6]
- iPad Air [iPadOS 16.5]
Brave build: 1.57 (23.8.16.21)
BraveCore: 1.57.47 (116.0.5845.96)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Tap on `Search bar` > Tap `Show` Recent Searches
3. Search anything
4. Open NTP > Tap on `Search bar` > Tap `Clear`
5. Clear Recent > Verify

**ACTUAL RESULTS:**
- Verified that `Cear Recent` is working, and search results are removed
- Verified that it's easy to tap on buttons to clear search results
- Verified that `Cancel` button is working
- Verified that tapping on a previous search result is opening actual search results

---------------------------

*iPhone*

https://github.com/brave/brave-ios/assets/128532965/53b86e06-47ca-41b1-b0da-d42620475752

*iPad*

https://github.com/brave/brave-ios/assets/128532965/d0d3beaf-1fc1-4ba5-ae8d-b2a56eaec2ff
