### ISSUE TITLE
Brave iPad keyboard shortcut conflicts with native system function

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#4928]
### Description: 
We recently added more keyboard shortcuts for iPad, one of them being 'close all tabs' with ⌘ + shift + tab which seems to conflict with the native apple shortcut for switching apps. Therefore, it is not working as expected.

Reference: https://github.com/brave/brave-ios/issues/4400

### Steps to Reproduce 
  1. Connect physical keyboard to iPad
  2. Launch Brave
  3. Open several new tabs
  4. Hold the ⌘ Key to display the keyboard shortcuts guide for reference.
  5. Press ⌘ + shift + tab to close all tabs according to the requirement

[iOS 14 UI]
![IMG_0107](https://user-images.githubusercontent.com/17885425/152021128-4d0c4f0a-f9ba-4f95-b710-08afb9436ebd.PNG)

**Actual result:** 
Key press will trigger the native system switch apps function (⌘ + tab)

**Expected result:**
Key press should close all open tabs

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily, Repro Rate: 100%

**Brave Version:** 
`1.35 (22.1.30.17)`

**Device details:** 
`iPad (7th Gen)` running `iPadOS 15.2.1`
Also observable on `iPadOS 14.4.2`
**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by soner-yuksel** [comment]
Closing since this issue is fixed in https://github.com/brave/brave-ios/issues/5194
