### ISSUE TITLE
Enable/Disable FP causes DDG modal and Pin modal to pop on private tab

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#493]
### Description: 
Disable FP causes DDG modal and Pin modal to pop on private tab

### Steps to Reproduce 
  1. Enable fingerprint protection in settings
  2. Set Qwant as default search engine for PB
  3. Open a new PB tab, no `Enable Pin` modal is shown since Qwant is set as default search engine
  4. Search for something, Qwant should be used to search
  5. Go to settings and disable fingerprint protection 
  6. Go back to PB tab, DDG modal pops up on the search result, once you dismiss pin modal pops up

**Actual result:** 
https://drive.google.com/open?id=1JwIlJVX09kh4kAcEFpzbVi8_VlZv6Bb-
Disable FP causes DDG modal and Pin modal to pop on private tab

**Expected result:**
1. Should show `Enable Pin` popup even if DDG is not set as default or any other SE is set
2. Disable/enable Fingerprint in settings should have no effect on the modals popup

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.11.28.22)

**Device details:** 
iPhone 7+(iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
Actual issue has nothing to do with FPP, simply that the check to display the popups is done with the assumption that you were coming from the tab tray (show the popup when the browser comes back into display), however you entered private mode via long-press shortcut.  Fixing this now :)
