### ISSUE TITLE
I can't delete 4 hours video that stored with Playlist

### ISSUE THREAD

**Issue by Kuehar** [brave/brave-ios#4932]
### Description: 
I downloaded 4 hours YouTube video with iPhone's Brave browser.
After I wathced this video,I tried to delete that but I can't.
I attempted some ways such as rebooting the Brave to delete long time video.

### Steps to Reproduce 
  1.Download over 2hours video

**Actual result:** 
Can't delete it.

**Expected result:**
can delete it

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
always

**Brave Version:** 
1.34.1

**Device details:** 
iPhone XR

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
this was fixed in by another fix, closing it to retest it by QA

**Comment by Uni-verse** [comment]
Verification completed using `1.36 (22.2.3.11)` 

**PASSED** on `iPhone 12 Pro` running `iOS 15.1.1`
**PASSED** on `iPhone X` running `iOS 14.4.2`
**PASSED** on `iPad (7th Gen)` running `iPadOS 15.2.1`

https://github.com/brave/brave-ios/issues/4932#issue-1121935956

- Verified videos over 2 hours are able to be deleted from playlist
- Verified user can delete multiple videos in playlist
- Verified toggling playlist as well as playlist functions (play/pause, play rate, scrubbing, minimizing)
- Verified deleting saved and unsaved videos
