### ISSUE TITLE
adding `Cancel` into the `Suppress Alerts` modal on iPad

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4934]
### Description: 

When receiving the  `Suppress Alerts` modal, you'll notice that the `Cancel` doesn't exist. Some users might get confused what the modal exactly means and might not want to click on `Suppress Alerts`. Tapping away from the modal does dismiss it though so that might be good enough. CCing @aekeus re: product and if we want to keep it this way.

### Steps to Reproduce
 
  1. visit https://brandon-t.github.io/WindowPrint.html

**Actual result:** 

![IMG_0355](https://user-images.githubusercontent.com/2602313/152217661-310f96ef-288f-4b38-aefc-3ee83b8d6a21.png)

**Expected result:**

![IMG_3772](https://user-images.githubusercontent.com/2602313/152218150-a790bdbd-bffa-4454-a384-566096cfea52.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases mentioned above.

**Brave Version:** 

* `1.35 (22.2.2.16)`

**Device details:** 

* `iPad Air (3rd Gen)` running `iOS 15.2` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @Brandon-T

**Comment by Uni-verse** [comment]
Verified **PASSED** on iPad (7th Gen) using `1.38 (22.4.25.21)` running iOS 15.2.1

Test URL:  https://brandon-t.github.io/WindowPrint.html

- Cancel button is added to the Suppress Alerts modal on iPad. 
- User is able to dismiss the modal by clicking/tapping `Cancel`

![IMG_0267](https://user-images.githubusercontent.com/17885425/165803606-df0ad79a-85aa-40be-be2e-8f8ab5881860.PNG)
