### ISSUE TITLE
Swap value is reset to 0 when it crosses a threshold

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4944]
### Description: 
Swap value is reset to 0 when it crosses a threshold. Found while investigating https://github.com/brave/brave-core/pull/12127

### Steps to Reproduce 
  1. Enable Wallet
  2. Select Swap
  3. Enter an unusually long decimal value, input values resets to 0

**Actual result:** 

https://user-images.githubusercontent.com/17010094/152483603-241b9423-0d79-47c4-aad4-688e725f74d1.MP4

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 
iPhone XR (iOS 15.3)

**Website problems only:**
- did you check with Brave Shields down?NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu

**Comment by Uni-verse** [comment]
Verified using version `1.37 (22.3.29.15)`

Devices: 
`iPad (7th Gen)` running `iOS 15.2.1`
`iPhone 12 Pro` running `iOS 15.4`
`iPhone X` running `iOS 14.4.2`

- Inputting long decimal value doesn't reset to 0.

https://user-images.githubusercontent.com/17885425/160724429-f40cc117-5f95-4f93-a130-d105e9244a2c.MOV
