### ISSUE TITLE
Better distinguish active tab vs inactive on iPad

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4947]
### Description: 
Slack: https://bravesoftware.slack.com/archives/G01F4JUNXAQ/p1643997586726859

The contrast levels of inactive vs active tabs on the iPad are not good, we need to make this easier for users, especially if using dark mode.

**Comment by Uni-verse** [comment]
Verification **PASSED** on `iPad (7th Gen)` running `iPadOS 15.2.1` using version `1.36 (22.2.17.10)`

Acceptance Criteria - https://github.com/brave/brave-ios/pull/4993#issue-1140497948

- [x] light mode: unselected tab 5% → 10% dark overlay
- [x] dark mode: url bar + tab bar background: secondary → tertiary background
- [x] selected tab text color: text02 → text01
- [x] unselected tab: title label alpha 60% → 80%
- [x] added private mode tints to tab bar
- [x] removed line between url bar and tab bar

Scenarios Tested: 

- Verified Settings > Appearance > Automatic respects native settings
- Url bar is hidden in private tab when in app switch mode
- User able to Create/Close tabs on tab bar
- User able to use tab tray functionality
- Rearranging tabs manually with swipe action
- User is able to search tabs 
- Split View Mode 

**Light Mode:** 
Old | New
-|-
![IMG_0149](https://user-images.githubusercontent.com/17885425/154566289-d54efefa-63f1-4557-a6df-5224e45a92c6.PNG) | ![IMG_0148](https://user-images.githubusercontent.com/17885425/154566172-6c26ae6d-b66e-46d1-94b1-a1b016e45eb1.PNG)

**Dark Mode**
Old | New 
-|-
![IMG_0155](https://user-images.githubusercontent.com/17885425/154566710-ec2c991d-aeec-407c-815e-e22fa7b3151d.PNG) | ![IMG_0154](https://user-images.githubusercontent.com/17885425/154566667-f0533c8e-53be-4c65-aeaf-77f8d703f205.PNG)

**Private Tab:** 
Old | New
-|-
![IMG_0157](https://user-images.githubusercontent.com/17885425/154567167-60440eb4-a8f0-4806-8658-620fc496c2a4.PNG) | ![IMG_0156](https://user-images.githubusercontent.com/17885425/154567158-f0367711-e6c7-4be5-9878-f92ac503b2c1.PNG)
