### ISSUE TITLE
`Supress Alerts` appearing in other unrelated tabs

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4949]
### Description: 

Sometimes when you tap away to dismiss the `Supress Alerts` model and open a new tab, the modal will re-appear under the new tab even though the tab isn't related nor is the cause of the `Supress Alerts` modal appearing.

### Steps to Reproduce

  1. visit https://brandon-t.github.io/WindowPrint.html using an `iPad`
  2. once the modal appears, dismiss it by tapping anywhere on the screen and quickly open a new tab

You'll notice that it's also difficult to dismiss the modal as it keeps appearing in certain cases.

**Actual result:** 

**`Example`** | **`Example`**
----------------|-----------------
![image](https://user-images.githubusercontent.com/2602313/152737474-e87edbf1-6dd4-493e-9878-a9b8568a8b86.png) | ![image](https://user-images.githubusercontent.com/2602313/152737501-80644665-1d1a-4c31-aa58-db5c4fc221bd.png)

**Expected result:**

The `Supress Alerts` modal shouldn't be appearing on other tabs unrelated to the tab that's causing the modal to appear.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases mentioned above.

**Brave Version:** 

`1.35 (22.2.417)`

**Device details:** 

* `iPad Air (3rd Gen)` running `iOS 15.2` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @Brandon-T

**Comment by soner-yuksel** [comment]
This issue is also fixed with https://github.com/brave/brave-ios/issues/4934
