### ISSUE TITLE
`k` visible for short time when transition occurs after tapping on `Skip`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4950]
### Description: 

When a user taps on `Skip` during onboarding, the letter `k` is left behind while the transaction occurs to load the next step in the onboarding process.

### Steps to Reproduce

  1. download/install Brave (new profile so you get the onboarding experience)
  2. tap on `Skip` and notice that the `k` will be visible for a few seconds while onboarding moves to the next step

**Actual result:** 

![IMG_0542](https://user-images.githubusercontent.com/2602313/152739812-5bedde2c-6baa-406c-ac5b-c08aabeeeb25.png)

**Expected result:**

Tapping on `Skip` should transition into the next step without leaving any artefacts behind (even though it's a second or two)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases outlined above.

**Brave Version:** 

`1.35 (22.2.417)`

**Device details:** 

* `iPhone 12` running `iOS 15.3` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

**Comment by kylehickinson** [comment]
Technically this can be closed because https://github.com/brave/brave-ios/pull/4962 removes that button entirely.  We can re-open if the first screen's skip button is ever re-added

**Comment by kylehickinson** [comment]
Going to keep it open as the second screen has a similar issue

**Comment by Uni-verse** [comment]
Verification completed using `1.37 (22.3.29.15)`

FAIL -  iPhone 12 Pro | iOS 15.4 (Still able to repro) - https://github.com/brave/brave-ios/issues/5192
PASSED - iPhone X | iOS 14.4.2
PASSED - iPad (7th Gen) | iOS 15.2.1

iPhone 12 Pro 

https://user-images.githubusercontent.com/17885425/161169561-9b9d68d3-0406-4959-aaf4-cbbf666d4657.MP4
