### ISSUE TITLE
Display Chromium/brave-core version in the app

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4953]
To verify correctness of brave-core builds we ship in iOS, it would be nice to place this info somewhere.
The code on core side is ready https://github.com/brave/brave-core/pull/12147

We have to decide where to put it

**Comment by Uni-verse** [comment]
Verification completed using build version `1.36 (22.2.11.11)`

**PASSED** on `iPhone 12 Pro` / `iOS 15.1.1`
**PASSED** on `iPhone X` / `iOS 14.4.2`
**PASSED** on `iPad (7th Gen)` / `iPadOS 15.2.1`

https://github.com/brave/brave-ios/issues/4953#issue-1126185449

- Clicking on version in settings > about will display BraveCore version
- BraveCore version displayed below app version
- User is able to dismiss the modal
- User is able to copy app info to clipboard 

iPhone | iPad
-|-
![IMG_2605](https://user-images.githubusercontent.com/17885425/153927605-40b217aa-ed7a-4d21-b3e5-a02b3dc06953.PNG) | ![IMG_0146](https://user-images.githubusercontent.com/17885425/153927587-44f49150-ad07-4604-bba6-accf7849575e.PNG)
