### ISSUE TITLE
tab search bar still active after completing search which requires two taps to select found tab

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4954]
### Description: 

When a user searches for a tab via the "tab search bar", the OSK is dismissed correctly but the search bar is still active which means the user needs to do the following before being able to tap on results:

* tap on `Cancel` via the `search toolbar` to remove active state
* tap anywhere to remove the active state from the search bar and then tap on the tab that have been found

Either route requires two taps. I think the correct way of doing the above should be the following:

* user does a search and tabs on `Search` via the OSK
* OSK is dismissed
* active state is removed from the tab search bar

In this case, user just needs to tap on their found tab rather than tapping twice.

### Steps to Reproduce

  1. launch Brave (use the dev build from TF so you can load the QA links and generate a bunch of tabs)
  2. once you have several tabs opened, initiate a search
  3. notice that you need to basically tap twice to select the tabs that were found

**Actual result:** 

As per the above, users need to tap twice to be able to select the tab that was found via "tab search"

**Expected result:**

Only a single tap should be required to select the tabs that were found while searching for tabs

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases mentioned above.

**Brave Version:** 

* `1.35 (22.2.4.17)`

**Device details:** 

* `iPhone 12` running `iOS 15.3` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @anthonypkeane @kylehickinson

**Comment by Uni-verse** [comment]
Verification passed using `1.35.1 (22.2.9.16)`

**PASSED** on `iPhone 12 Pro` | `iOS 15.1.1`
**PASSED** on `iPhone X` | `iOS 14.4.2`
**PASSED** on `iPad (7th Gen)` |  `iOS 15.2.1`

- Verified when user performs search in tab search using the OSK search key, OSK is dismissed and user is able to click once to load the tab. - https://github.com/brave/brave-ios/issues/4954#issue-1126400893
- Verified tab search works as expected in private tabs
- Verified tapping 'Cancel' will remove active state from search bar
- Verified tapping 'X' will remove active state from search bar [iPad]

iPhone UI

https://user-images.githubusercontent.com/17885425/153263800-516c5724-0f74-4f4a-ba38-9ab3b09600fe.MP4
