### ISSUE TITLE
Onboarding cleanup

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#4955]
Just some cleanup around onboarding screens

**Comment by anthonypkeane** [comment]
Context

I want to remove the 'skip' button from the first slide (Privacy made easy). The skip button will remain on all other slides to allow the user to skip onboarding if they wish. 


![IMG_CD33F1BC9884-1](https://user-images.githubusercontent.com/7606853/153031252-91ad2053-73a4-4022-b48f-e750c8f7560c.jpeg)

**Comment by Uni-verse** [comment]
Verification completed using build version `1.36 (22.2.11.11)`

**PASSED** on `iPhone 12 Pro` / `iOS 15.1.1`
**PASSED** on `iPhone X` / `iOS 14.4.2`
**PASSED** on `iPad (7th Gen)` / `iPadOS 15.2.1`

https://github.com/brave/brave-ios/issues/4955#issuecomment-1032813423
- Verified 'skip' button is removed from the first onboarding screen.
- Verified other skip buttons remain on other screens. 

iPhone 12 Pro | iPhone X | iPad
-|-|-
![IMG_2445](https://user-images.githubusercontent.com/17885425/153925496-08d3f5ca-cf53-421d-a931-2fd3c0fb28f7.PNG) | ![IMG_2604](https://user-images.githubusercontent.com/17885425/153925521-6ca15d8c-2eda-4894-ab36-c8d97d28c654.PNG) | ![IMG_0145](https://user-images.githubusercontent.com/17885425/153925536-e2524b38-b2dd-4ab8-8c5a-81a37a05c907.PNG)
