### ISSUE TITLE
Add ability to disable Recent Searches

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4956]
### Description: 
User Review: https://appfigures.com/reviews/42132121512Lde5cfmwNnQclelIbU6KsVA?lang=en
`Needs to turn off the search save feature and have a feature to clear all data automatically upon exit.`

This is a fair point, we should add the ability to disable Recent Searches

**Comment by kjozwiak** [comment]
Adding into `iOS Release Plan` for triage 👍

**Comment by Brandon-T** [comment]
We do have the ability to clear recent searches and to disable it already:

![image](https://user-images.githubusercontent.com/1530031/153009566-84ce06e8-908f-456a-94af-00f965466dbd.png)

![image](https://user-images.githubusercontent.com/1530031/153009657-70d8f68b-b34f-42a8-a1f7-04b60f24826c.png)

**Comment by anthonypkeane** [comment]
okay, thank you. Closing the issue
