### ISSUE TITLE
Move Reset for wallet into BraveWalletService

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4957]
iOS version of https://github.com/brave/brave-browser/issues/20346

> Currently the ResetWallet function is not usable from iOS.
> This changes it so you only need to call reset on BraveWalletService.
> It also fixes a bug with reloading a tab when not needed for restoring a wallet seed phrase.

**Comment by srirambv** [comment]
Fixed with https://github.com/brave/brave-core/pull/11754

**Comment by nuo-xu** [comment]
This can be verified through #4777

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.36 (22.2.23.20)
- Verified steps from issue description
- Verified reset wallet removes all settings (auto lock, biometric unlock etc)
- Verified reset wallet deleted the custom network that is added
- Verified reset wallet hides the wallet option in settings
- Verified reset works fine on a clean wallet install
- Verified reset wallet works on restored wallet 
- Verified when reset is done via wallet menu, upon successful reset, brings up the onboarding modal
- Verified when reset is done via More menu-> Wallet -> Reset or via wallet, setting is hidden until user onboard's again
-----------
Verification passed on iPhone XR with iOS 15.3 running 1.36 (22.2.23.20)
- Verified steps from issue description
- Verified reset wallet removes all settings (auto lock, face unlock etc)
- Verified reset wallet deleted the custom network that is added
- Verified reset wallet hides the wallet option in settings
- Verified reset works fine on a clean wallet install
- Verified reset wallet works on restored wallet 
- Verified when reset is done via wallet menu, upon successful reset, brings up the onboarding modal
- Verified when reset is done via More menu-> Wallet -> Reset or via wallet, setting is hidden until user onboard's again
------------
Verification passed on iPad Pro with iOS 15.4 Beta running 1.36 (22.2.23.20)
- Verified steps from issue description
- Verified reset wallet removes all settings (auto lock, bio-metric unlock etc)
- Verified reset wallet deleted the custom network that is added
- Verified reset wallet hides the wallet option in settings
- Verified reset works fine on a clean wallet install
- Verified reset wallet works on restored wallet 
- Verified when reset is done via wallet menu, upon successful reset, brings up the onboarding modal
- Verified when reset is done via More menu-> Wallet -> Reset or via wallet, setting is hidden until user onboard's again
