### ISSUE TITLE
can't `Proceed to...` when landing on a certificate error

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4958]
### Description: 

When confronted with a certificate error, you can't proceed to the website by selecting `More Details` -> `Proceed to [x]`.

### Steps to Reproduce

  1. install `1.35` via TF
  2. visit https://badssl.com and click on any of the certificate errors (`expired`, `wrong.host`, `self-signed`)
  3. once you receive the certificate error, attempt to bypass the error by clicking on `Proceed to [website]`

You'll notice nothing happens and you won't be able to bypass the certificate error. This is working correctly under `1.34.1 (22.1.20.22)`.

**Actual result:** 

Can't proceed/bypass a certificate error page by going into `More Details` -> `Proceed to [x]`

**Expected result:**

Users should be able to bypass the certificate error page like they were able to do via `1.34.1 (22.1.20.22)`.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases outlined above.

**Brave Version:** 

* `1.35 (22.2.4.17)`

**Device details:** 

* `iPhone 12` running `iOS 15.3` - **Reproduced**
* `iPhone 11` running `iOS 14.7.1` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `Yes, still not working as expected with shields disabled`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

**Comment by srirambv** [comment]
Reproduced this issue while testing a different one.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 12` running `iOS 15.3` using `1.35.1 (22.2.9.16)`

* ensured that the certificate error page is being displayed correctly when visiting the following:
  * https://expired.badssl.com
  * https://wrong.host.badssl.com
  * https://self-signed.badssl.com
  * https://untrusted-root.badssl.com
  * https://revoked.badssl.com
* ensured that `Back to safety` takes the user to the previous page
* ensured that `Hide details` expands/displays for information regarding the error including the `Proceed to [x]` link
* ensured that tapping on `Proceed to [x]` works as expected
* ensured that certificate "Allow" choices are reset once the browser restarts (users should see the certificate warning again)

**`Example (Expired)`** | **`Example (Expired)`** | **`Example (Wrong Host)`** | **`Example (Wrong Host)`**  
--------------------------|--------------------------|---------------------------------|------------------------------
![image](https://user-images.githubusercontent.com/2602313/153258248-8072b7c9-f098-4bfa-9a4f-69cfb406ceab.png) | ![image](https://user-images.githubusercontent.com/2602313/153258323-7763eb28-5a07-4217-b591-00bf9704000f.png) | ![image](https://user-images.githubusercontent.com/2602313/153258417-b3f9a3b7-4ade-4baa-9ab9-4c457e240d84.png) | ![image](https://user-images.githubusercontent.com/2602313/153258459-f02d304b-98bb-43a9-9267-46d3234b8c5d.png)

**`Example (Self Signed)`** | **`Example (Self Signed)`** | **`Example (Untrusted)`** | **`Example (Untrusted)`**  
--------------------------|--------------------------|---------------------------------|------------------------------
![image](https://user-images.githubusercontent.com/2602313/153258636-014833e8-8469-4bb0-8e3d-7083a573f3b4.png) | ![image](https://user-images.githubusercontent.com/2602313/153258728-38740ab0-d982-4685-8557-87480608ae87.png) | ![image](https://user-images.githubusercontent.com/2602313/153258772-c74fce0a-cfa1-4d87-8fd8-229816f69820.png) | ![image](https://user-images.githubusercontent.com/2602313/153258833-195b892a-d3ff-417a-ac31-88574db53a56.png)

------------------------

Verification **PASSED** on `iPhone 11` running `iOS 14.7.1` using `1.35.1 (22.2.9.16)`

* ensured that the certificate error page is being displayed correctly when visiting the following:
  * https://expired.badssl.com
  * https://wrong.host.badssl.com
  * https://self-signed.badssl.com
  * https://untrusted-root.badssl.com
  * https://revoked.badssl.com
* ensured that `Back to safety` takes the user to the previous page
* ensured that `Hide details` expands/displays for information regarding the error including the `Proceed to [x]` link
* ensured that tapping on `Proceed to [x]` works as expected
* ensured that certificate "Allow" choices are reset once the browser restarts (users should see the certificate warning again)

**`Example (Expired)`** | **`Example (Expired)`** | **`Example (Wrong Host)`** | **`Example (Wrong Host)`**  
--------------------------|--------------------------|---------------------------------|------------------------------
![image](https://user-images.githubusercontent.com/2602313/153271471-b54f297f-9b13-47c7-97f3-b12011ac3415.png) | ![image](https://user-images.githubusercontent.com/2602313/153271522-b5cf6e6d-34cc-4bc4-99ba-6578858ee6ef.png) | ![image](https://user-images.githubusercontent.com/2602313/153271575-f0670af6-15ec-4a9e-ab4a-5a061d194435.png) | ![image](https://user-images.githubusercontent.com/2602313/153271613-6fb1af88-b108-4a21-8a2b-e94a62669757.png)

**`Example (Self Signed)`** | **`Example (Self Signed)`** | **`Example (Untrusted)`** | **`Example (Untrusted)`**  
--------------------------|--------------------------|---------------------------------|------------------------------
![image](https://user-images.githubusercontent.com/2602313/153271663-0fe3fbe4-a52a-4a88-a848-731da8596f4f.png) | ![image](https://user-images.githubusercontent.com/2602313/153271682-6bf0cd8d-510e-4aac-9b97-b4b5eba4343f.png) | ![image](https://user-images.githubusercontent.com/2602313/153271713-708864a7-95c1-4152-b320-6f563ffe3ba8.png) | ![image](https://user-images.githubusercontent.com/2602313/153271747-4312c300-52ec-4641-8ce0-e77adea24914.png)

------------------------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.3` using `1.35.1 (22.2.9.16)`

* ensured that the certificate error page is being displayed correctly when visiting the following:
  * https://expired.badssl.com
  * https://wrong.host.badssl.com
  * https://self-signed.badssl.com
  * https://untrusted-root.badssl.com
  * https://revoked.badssl.com
* ensured that `Back to safety` takes the user to the previous page
* ensured that `Hide details` expands/displays for information regarding the error including the `Proceed to [x]` link
* ensured that tapping on `Proceed to [x]` works as expected
* ensured that certificate "Allow" choices are reset once the browser restarts (users should see the certificate warning again)

**`Example (Expired)`** | **`Example (Expired)`** | **`Example (Wrong Host)`** | **`Example (Wrong Host)`**  
--------------------------|--------------------------|---------------------------------|------------------------------
![image](https://user-images.githubusercontent.com/2602313/153318761-489c76f9-cbaf-4840-b2b4-8625b3d8eeec.png) | ![image](https://user-images.githubusercontent.com/2602313/153318777-8c118a6b-4219-4bca-a044-61ee539b4511.png) | ![image](https://user-images.githubusercontent.com/2602313/153318813-69b394c6-f101-4b69-ad01-cabdb64b8551.png) | ![image](https://user-images.githubusercontent.com/2602313/153318840-a645ce77-a7a4-40d0-a950-58775966b447.png)


**`Example (Self Signed)`** | **`Example (Self Signed)`** | **`Example (Untrusted)`** | **`Example (Untrusted)`**  
--------------------------|--------------------------|---------------------------------|------------------------------
![image](https://user-images.githubusercontent.com/2602313/153318853-b21fb921-abce-4c8c-96d9-54869844684e.png) | ![image](https://user-images.githubusercontent.com/2602313/153318876-8921f7a9-4717-4da0-8e4c-7deb4a92ab5f.png) | ![image](https://user-images.githubusercontent.com/2602313/153318899-5a371c18-e042-4613-8e0a-6be68a2317a2.png) | ![image](https://user-images.githubusercontent.com/2602313/153318925-90d9055c-4412-46ac-b69d-4226f51d3860.png)
