### ISSUE TITLE
horizontal tab tray & omnibox quickly go white then return to expected them when opening tabs in PB

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4960]
### Description: 

When opening new tabs via PB, you'll notice that the horizontal tab list and the omnibox will go white for a few seconds before loading the default PB theme. This appears to be a regression and doesn't happen in `1.34.1`. Assuming it's caused by the addition of https://github.com/brave/brave-ios/issues/3396.

### Steps to Reproduce

  1. install `1.35` via TF
  2. switch over the PB and start opening NTP via `+`

**Actual result:** 

* Example of issue occurring ---> https://youtu.be/8-t_E6Qf-ww

**Expected result:**

Shouldn't appear like it's "flashing/bugging" out. Should be using the same theme consistently rather than transitioning from `white` to the default PB theme.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases outlined above.

**Brave Version:** 

* `1.35 (22.2.4.17)`

**Device details:** 

* `iPhone 12` running `iOS 15.3` - **Reproduced**
* `iPhone 11` running `iOS 14.7.1` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

**Comment by Uni-verse** [comment]
@iccub This was not resolved with https://github.com/brave/brave-ios/pull/4993

I am still able to repro this on iOS 15, 14 mobile and tablet using 1.36.108 with dark mode disabled. I will be creating a follow up issue.

CC: @kjozwiak 

iPhone UI
https://user-images.githubusercontent.com/17885425/156671571-1f34fb40-68ff-406f-82af-ea3f51fa78e4.MP4

**Comment by iccub** [comment]
I will reopen it and move out of the milestone then @Uni-verse

**Comment by Uni-verse** [comment]
Verification PASSED using version 1.39 (22.5.24.16)

Test Devices:
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad (7th Gen) | iOS 15.4

- Confirmed no "flashing/bugging" out present when opening NTP in PB
- Confirmed opening NTP tab using tray icon + icon
- Confirmed opening NTP using + icon on webpages

iPad

https://user-images.githubusercontent.com/17885425/170369656-54f82541-e163-4b08-bd18-93967c05f99d.MP4

iPhone

https://user-images.githubusercontent.com/17885425/170369625-e4132c85-31f4-4885-a77b-821f7abe6852.MP4
