### ISSUE TITLE
Picture-in-picture bug

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4964]
### Description: 
https://appfigures.com/reviews/42132121512LM7npgW_B0BbQ4shVPDJ4QQ?lang=en

I've seen a number of reviews saying Picture-in-picture  is no longer working

### Steps to Reproduce 
  1. Navigate to YouTube 
  2. Play a video, select full screen
  3. Close Brave

**Actual result:** 
PiP plays for a moment then closes

**Expected result:**
PiP should stay playing

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.35

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by anthonypkeane** [comment]
Another review with a similar issue: https://appfigures.com/reviews/42132121512LenBYtDfcYxmjfl9lUo9qxQ?lang=en

**Comment by Uni-verse** [comment]
Verified using `1.38 (22.4.8.16)`

Devices: 

`iPhone 12` | `iOS 15.4`
`iPhone X` | `iOS 14.4.2`
`iPad (7th Gen)` | `iOS 15.2.1`

- Verified PIP will play when backgrounding app

https://user-images.githubusercontent.com/17885425/162836872-5d5d72b9-648e-4957-b073-8867bda7f0d2.MP4
