### ISSUE TITLE
Manual test run for `1.35.1` running `iOS 15` on `iPhone`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#4970]
## Installer

- [x] Check that installer is close to the size of the last release
- [x] Check the Brave version in About and make sure it is EXACTLY as expected

## Data

- [x] Verify that data from the previous build appears in the updated build as expected (bookmarks, history, etc.)
- [x] Verify that cookies from the previous build are preserved after upgrade
- [x] Verify saved passwords are retained after upgrade
- [x] Verify stats are retained after upgrade
- [x] Verify sync chain created in the previous version is still retained on upgrade
- [x] Verify per-site settings are preserved after upgrade

## Bookmarks

- [x] Verify that creating a bookmark works
- [x] Verify that tapping a bookmark from bookmark manager loads the bookmark
- [x] Verify that deleting a bookmark works
- [x] Verify that creating a bookmark folder works
- [x] Verify that creating a bookmark inside the created folder works
- [x] Verify that you can add a bookmark directly inside a bookmark folder
- [x] Verify that you can delete a bookmark in edit mode
- [x] Verify that you can delete a bookmark folder with bookmarks inside
- [x] Verify adding a bookmark domain, subpaths is retained and you are successfully able to visit the domain subpath in a new tab

## Favourites

- [x] Verify editing favourites and changing their URLs updates the favicons accordingly
- [x] Verify that you can remove favourites
- [x] Verify that you can add new favourites from the `Share with...` menu

## Downloads

- [x] Verify that you can save an image from a site
- [x] Verify that you are able to save a GIF image

## Reader Mode

- [x] Visit `http://theverge.com`, open any article, verify the reader mode icon is shown in the URL bar
- [x] Verify tapping on the reader mode icon opens the article in reader mode
- [x] Edit reader mode settings and open different pages in reader mode and verify if the setting is retained across each article

## Password Managers

- [x] Verify tapping on 1Password on the slide-out keyboard launches 1Password app and you're able to select the stored credentials
- [x] Verify tapping on Bitwarden password manager in the autofill field launches the app and auto-fills the stored data

## Brave Rewards/Ads

- [x] Verify wallet is auto-created after enabling Rewards
- [x] Verify when you click on the Brave Rewards panel while on a site, the panel displays if the site is verified or not
- [x] Verify ads are only shown while the app is being used
- [x] Verify tapping on an ad notification shows the landing page
- [x] Verify inline-content ads show on Brave News and are correctly redeemed from the server
- [x] Verify `view`,`clicked`, `landed`, and `dismiss` states are logged based on the action

## Content tests

- [x] Verify that PDF is loaded over `HTTPS` at `https://basicattentiontoken.org/BasicAttentionTokenWhitePaper-4.pdf`
- [x] Verify that PDF is loaded over `HTTP` at `http://www.pdf995.com/samples/pdf.pdf`

## Session storage

- [x] Verify that tabs restore when closed, including active tab

**Comment by kjozwiak** [comment]
In addition the above, we'll need to check the following:

* [x] Printing the current page (Share Menu -> Print OR call `window.print()`)
* [x]  Bookmarklets (Save a bookmarklet like: `javascript:alert('test');` and execute it on any page)
* [x] Find-In-Page (Settings -> Find In Page. Test that it still works and that going previous and next result works)
* [x] Tracking protection stats (visit a page with tracking such as `Youtube`, and test that the stats increase)

**Comment by Uni-verse** [comment]
Verification **PASSED** on `iPhone 12 Pro` running `iOS 15.1.1` using `1.35.1 (22.2.9.16)`

*Tested upgrading/data using `1.35.1 (22.2.10.16)`
