### ISSUE TITLE
iOS inline-display/content ads are missing button text

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-ios#4976]
### Description: 

iOS inline-display/content ads are missing button text

### Steps to Reproduce 
  1. install `1.36`
  2. launch Brave
  3. tap on `...`
  4. tap `Settings`
  5. tap `View Rewards Debug Menu`
  6. tap on `Staging` on `Override`
  7. tap `Done`
  8. restart Brave
  9. open a new-tab page
  10. swipe down until you see `Staging - Inline Test 2`
  11. look at the `()` on its bottom right

**Actual result:** 

`Fung Brave News Inline Display Ad - ios/android ()` <-- Missing button text

![Image from iOS](https://user-images.githubusercontent.com/387249/153502307-aafa2fb0-46bd-4658-8e39-a84fb845dd52.png)

**Expected result:**

`Fung Brave News Inline Display Ad - ios/android (Work at Brave)`

Android | desktop
--------|---------
![Screenshot_20220210-133913](https://user-images.githubusercontent.com/387249/153502103-393f21d3-e233-4a9f-b4b8-09f061d07f72.png) | <img width="1312" alt="Screen Shot 2022-02-10 at 1 35 32 PM" src="https://user-images.githubusercontent.com/387249/153502166-0ae345b7-4d4c-45eb-9671-5c75247e8817.png">

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100%

**Brave Version:** 

Brave `1.36 (22.2.3.11)`

**Device details:** 

iPhone 6s, iOS 14.4.2 (18D70)

cc @Uni-verse @iambrianfung @btlechowski @tmancey

**Comment by stephendonner** [comment]
Verified `PASSED` using Brave `1.36 (22.2.11.11)` on an `iPhone 6s`, running `iOS 14.4.2`.

![Image from iOS](https://user-images.githubusercontent.com/387249/153644447-fca14e34-86f6-4be6-a43d-2af103b2b196.png)

**Comment by Uni-verse** [comment]
Verified using `1.36 (22.2.17.10)`

Environment: Staging Rewards/Staging News

- Verified CTA is showing and user is able to click to open page

iPad | iPhone
-|-
![IMG_0158](https://user-images.githubusercontent.com/17885425/154586366-80084b15-47ac-43de-9256-e9baf7c00ba7.PNG) | ![IMG_2606](https://user-images.githubusercontent.com/17885425/154586375-407ed853-dd19-4784-9396-e4eed8ff000e.PNG)
