### ISSUE TITLE
Add ability to swap selected tokens directly from Swap screen

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4979]
When you're on the swap screen the only way to swap the two tokens you're swapping is to go in manually do it via the list, we should add a button between the from/to fields that flips the tokens

**Comment by kylehickinson** [comment]
You can use `chevron.up.chevron.down` icon in a button between the from/to sections

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.36 (22.2.23.20)
- Verified test plan from [ #5014](https://github.com/brave/brave-ios/pull/5014)
- Verified pre-filled values are retained when quick switch on swap screen

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.3) | iPad Pro (iOS 15.4 Beta)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/155521452-81ad209a-fc47-408e-8fca-ff56a789c247.MP4> | <video src=https://user-images.githubusercontent.com/17010094/155521490-c76d7379-670b-4229-8aef-c09a4037458c.MP4> | <video src=https://user-images.githubusercontent.com/17010094/155521424-f5fae5f6-0247-4f3d-b7b8-1cd2683437f6.MP4>
