### ISSUE TITLE
Display native currency at the top of the token list by default in buy/send/swap

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4980]
The token list is currently sorted alphabetically but it would be good to bubble up certain tokens to the top. At the very least we should show the native currency (ETH on Ethereum for instance) at the top of the list.

We could also bubble up the users visible assets to the top of the list as its likely they want to interact with them the most.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.36 (22.02.23.20)
- Verified steps from [#5011](https://github.com/brave/brave-ios/pull/5011)
- Verified native currency is shown on top of the token list by default on Buy/Send/Swap screen
- Verified custom tokens shows upon Swap screen token list 

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.3) | iPad Pro (iOS 15.4 beta)
-- | -- | --
<video height=500 src=https://user-images.githubusercontent.com/17010094/155482593-3c41c59d-5106-46f0-917d-83e1735b3e72.MP4> | <video height=500 src=https://user-images.githubusercontent.com/17010094/155482636-11e5dfff-a5bb-41df-aba5-2b10db214173.MP4> | <video height=500 src=https://user-images.githubusercontent.com/17010094/155482547-5faaa2b4-8b7e-414b-90f3-ccf8d744f86b.MP4>
