### ISSUE TITLE
Show custom user assets in Swap tokens list 

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#4981]
We should show custom user assets to the selectable token list within Swap.  In conjunction with https://github.com/brave/brave-ios/issues/4980 these tokens should show up at the top of the list

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.36 (22.02.23.20)
- Verified steps from [#5011](https://github.com/brave/brave-ios/pull/5011)
- Verified custom tokens shows upon Swap screen token list 

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.3) | iPad Pro (iOS 15.4 beta)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/155482593-3c41c59d-5106-46f0-917d-83e1735b3e72.MP4> | <video src=https://user-images.githubusercontent.com/17010094/155482636-11e5dfff-a5bb-41df-aba5-2b10db214173.MP4> | <video src=https://user-images.githubusercontent.com/17010094/155482547-5faaa2b4-8b7e-414b-90f3-ccf8d744f86b.MP4>
