### ISSUE TITLE
Disabling all sources shows Brave Inline Ads but restart removes it

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#4995]
### Description: 
Disabling all sources shows Brave Inline Ads but restart removes it

### Steps to Reproduce 
  1. Enable Brave News
  2. Go to All sources and disable them all
  3. Open a new tab, shows Inline ads (depending on how many are available in catalog)
  4. Open a few more tabs continues to show the inline ads
  5. Close and restart the browser no inline ads are shown. shows message about enable sources

**Actual result:** 

https://user-images.githubusercontent.com/17010094/154424764-8e177bf8-4403-4dc8-94b5-156e1f424bfb.MP4

**Expected result:**
TBD

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.36

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @mattmcalister @kylehickinson

**Comment by kylehickinson** [comment]
@srirambv I don't think this is an issue, it's behaved like this forever. It's likely that you hit the cap on ads cc @tmancey

**Comment by tmancey** [comment]
Ads are shown because the feed is still active. I do not think this is something many/or any users would experience, but if we did want to fix then after removing all sources we should instantly show the "No articles to show" without the need to restart

**Comment by kylehickinson** [comment]
Solution to be implemented: Don't show any inline ads unless there are items shown in the feed

**Comment by Uni-verse** [comment]
Verification in Progress

**PASSED** on `iPad (7th Gen) | iPadOS 15.2.1`
**PASSED** on iPhone 12 Pro | iOS 15.1.1 
**PASSED** on iPhone X | iOS 14.4.2

**Test Scenario:**

- Test regular feed, ensure ads and feed items are visible
- Install fresh (required to reset ads cap), disable all sources, verify that no inline ads appear
- Add a source that results in more than 10 feed items and verify ads and feed items are visible

UI 
https://user-images.githubusercontent.com/17885425/156674071-e9cf020c-f9f9-4439-9ee4-176a63c02f35.MP4
