### ISSUE TITLE
Playlist UI Bug

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#4996]
### Description: 

Small UI issue with the menu notification to alert users that they can add an item to their playlist 

![Screenshot 2022-02-16 at 18 30 19](https://user-images.githubusercontent.com/7606853/154512499-50ec79c6-9d72-4b73-8647-38e96d1bd8cb.jpeg)

**Comment by Uni-verse** [comment]
Verified fixed using beta `1.37 (22.3.23.17)` on iPad (7th Gen) running `iPadOS 15.2`

- Playlist notification bubble fits in UI
- Playlist notification displays in portrait and landscape
- User able to add/remove video to playlist
- When removing item from playlist, playlist notification bubble reappears

Landscape | Portrait
-|-
![IMG_0208](https://user-images.githubusercontent.com/17885425/159802211-8b7f1795-d998-4f49-918f-3de94961671a.PNG) | ![IMG_0209](https://user-images.githubusercontent.com/17885425/159802227-faf5fa0b-9a0b-4a91-b4ca-bd3dc8ea9845.PNG)
