### ISSUE TITLE
Brave Playlist autoplays content despite autoplay setting

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-ios#4998]
### Description: 
When you add a video(s) to your Brave Playlist, if the autoplay option in `Settings --> Playlist --> Autoplay` is set to "disabled", videos will autoplay anyway. My assumption here is that having the option toggled off, that no saved videos should play until the user elects to do so. 

### Steps to Reproduce 

1. Make sure Auto-Play is turned off in the Playlist settings
2. Add a YouTube vide to Playlist
3. Go to Playlist 

**Actual result:** 
Videos will autoplay

**Expected result:**
Video should not autoplay

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
v1.34.1

**Device details:** 
iPhone/iPad

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information
User reported this behavior here:
https://community.brave.com/t/playlist-auto-play-setting-is-not-working-it-will-always-auto-play-regardless/332447

**Comment by srirambv** [comment]
With Autoplay disabled for playlist, adding a video from YT to playlist and loading immediately after adding is causing the issue of auto play. However if after pausing the YT playback and adding to playlist and then opening a new tab and then playlist doesn't auto play. Even if you close and reopen the app it doesnt autoplay.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12`, `iPad (9th Gen)` running `iOS 16.2`, `iPadOS 15.6.1` respectively using version `1.48 (23.2.13.20)`

- Ensured that videos are not playing automatically when playlist `autoplay` is disabled
- Ensured that videos are respecting the playlist setting when opening playlist from youtube as well as using the playlist in the menu.

Example | Example
-|-
![IMG_0990](https://user-images.githubusercontent.com/17885425/218844418-f893d03c-1117-4cfb-a790-d824a7025c36.PNG) | ![IMG_4482](https://user-images.githubusercontent.com/17885425/218844431-8e8e0baa-cf08-487a-8751-b686f9698eb1.PNG)
