### ISSUE TITLE
Update Show Tab Bar default setting

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#5005]
### Description: 

To clean up the first user experience I think we should update this default as follows

![IMG_EAE5DB331F6E-1](https://user-images.githubusercontent.com/7606853/154814968-9e1bf466-e55e-42f4-b485-a152378caeb9.jpeg)

**Comment by Uni-verse** [comment]
Verified using version `1.43 (22.9.2.15)`

Test Devices:
`iPhone 12 Pro` & `XR `| `iOS 15.5`
`iPad (7th Gen)` | `iOS 15.5`
`iPhone X` | `iOS 14.4.2`

Scenarios:

**Clean profile:** 

- Verified `Show in Landscape Only` is selected under `Show Tabs Bar` settings
- Verified tabs are not shown in portrait mode on mobile
- Verified `Show Tabs` is disabled by default on 1.43.x on `iPad`
- Verified enabling `Show Tabs` will display tab bar on `iPad`
- Verified tab bar works in private viewing mode

Example | Example
-|-
![IMG_3568](https://user-images.githubusercontent.com/17885425/188733607-c9553ba4-84d6-42c9-9240-fb05362a3f3e.PNG) | ![IMG_0543](https://user-images.githubusercontent.com/17885425/188733623-2bd64f49-5de6-471d-8064-7aeb3265ba03.PNG)


**Upgraded profile:**

- Verified Tab setting will persist when upgrading to 1.43.x
- Verified Tabs can be disabled after upgrade if they were enabled
- Verified Tabs can enabled post upgrade after they were disable

Upgrade Example (Tabs ON) | Upgrade Example (Tabs ON)
-|-
![IMG_3567](https://user-images.githubusercontent.com/17885425/188733982-c4a40938-9c3d-4961-9d96-f2d662746046.PNG) | ![IMG_0541](https://user-images.githubusercontent.com/17885425/188734037-b3378cb4-0867-4a77-8548-3fb325b35682.PNG)
