### ISSUE TITLE
New Tab button menu improvements

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5006]
See more at https://community.brave.com/t/tab-button-changes-v-1-35-1/340729/8

Add haptic feedback when user taps on it.
Show a prompt before removing multiple tabs

**Comment by Uni-verse** [comment]
Verification completed using version `1.36 (22.2.24.17)
`
**PASSED** on `iPhone 12 Pro` |` iOS 15.1.1`
**PASSED** on `iPhone X` | `iOS 14.4.2`
**PASSED** on` iPad (7th Gen)` | `iPadOS 15.2.1`

Acceptance Criteria: 

UI

- [x] prompt top CTA : `Close All {number} Tabs`
- [x] prompt bottom CTA: `Cancel` (iPhone only)
- [x] prompt description text: `Are you sure you want to close all open tabs?`
- [x] Cancel CTA text color is blue 
- [x] Close All Tabs text color is red
- [x] Cancel CTA only specific to iPhone
- [x] Prompt supports double digit number

Functionality

- [x] Add haptic feedback when user taps on it.
- [x] Show a prompt before removing multiple tabs
- [x] User able to close all tabs at the prompt
- [x] User able to dismiss the prompt
- [x] Don't prompt user when closing single tab with tab tray
- [x] Using Private tabs
- [x] Works in Private browsing mode

iPad | iPhone 
-|-
![IMG_0161](https://user-images.githubusercontent.com/17885425/155803383-59b92112-f059-47cd-aff7-4788c55fc3ef.PNG) | ![IMG_2608](https://user-images.githubusercontent.com/17885425/155803390-7f71b206-f146-45fc-95b1-1b0226a07430.PNG)
