### ISSUE TITLE
When you enter private mode and press +, two tabs are added

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5008]
### Steps to Reproduce 
  1. Open private mode
  2. Tap on `+` button

**Actual result:** 
Two tabs are opened

**Expected result:**
Should be one tab only.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verification completed using version `1.36 (22.2.24.17)`

**PASSED** on `iPhone 12 Pro` | `iOS 15.1.1`
**PASSED** on `iPhone X` | `iOS 14.4.2`
**PASSED** on `iPad (7th Gen)` | `iPadOS 15.2.1`

- Verified Tap on + button in private mode opens single tab
- Verified single tab is opened with homescreen app context menu
