### ISSUE TITLE
Haptics/vibration don't stop when holding on tabs icon while page is scrolling up

### ISSUE THREAD

**Issue by ghost** [brave/brave-ios#5010]
### Description: 
iPhone haptics spazz out when I hold my finger on the tabs icon (to bring up 'close tab' or 'close all X tabs') while the page is scrolling from a swipe up

### Steps to Reproduce 
  1. Go to page with scroll
  2. Scroll up
  3. Hold down on tabs icon

**Actual result:** 

**Expected result:**
Not haptics to behave this way

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always happens

**Brave Version:** 
Version 1.35.1 (22.2.10.16)

**Device details:** 
iPhone 13, iOS 15.2.1

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

**Comment by Uni-verse** [comment]
Verification completed using version `1.36 (22.2.24.17)`

**PASSED** on `iPhone 12 Pro` | `iOS 15.1.1`
**PASSED** on `iPhone X` | `iOS 14.4.2`
**PASSED** on `iPad (7th Gen)` | `iPadOS 15.2.1`

- Not able to repro the continuous haptics on the RC (1.36)
