### ISSUE TITLE
Swap Amount Displayed as 0 in Transaction Confirmation Screen

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5016]
### Description: 
Wrong swap amount in transaction confirmation screen

### Steps to Reproduce 
  1. Make a swap from ETH to BAT in mainnet 
  2. Let the transaction confirmation screen to show up
 

**Actual result:** 
The swap amount displayed as 0.0000 ETH

![IMG_2320](https://user-images.githubusercontent.com/1187676/155358904-83295fb4-6477-4c5a-8309-1b34144da0c1.PNG)

**Expected result:**
Correct amount should be displayed 

for example:
![IMG_2321](https://user-images.githubusercontent.com/1187676/155359083-8a1bf345-ba73-463a-8ced-10cdefa008b2.PNG)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 
 1.35.1 (22.2.10.16)

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Tx:
https://etherscan.io/tx/0x98b35cf7157b3e5f611339dbad7d044fecc77b51683d78109da6614317e758c5

**Comment by StephenHeaps** [comment]
Investigating this issue, it occurs for all swaps where the from token is not ETH (0.0000 ETH will be displayed).

I believe we need a core update for this fix, and currently there is an experimental PR with a new `TransactionType` called `ETHSwap`: https://github.com/brave/brave-core/pull/12797

**Comment by StephenHeaps** [comment]
For Transaction Summaries (list of transactions), swap fix was handled in https://github.com/brave/brave-ios/issues/5731.
For Transaction Details, swap fix was handled in https://github.com/brave/brave-ios/issues/5735.
For Transaction Confirmation, swap fix will be handled in https://github.com/brave/brave-ios/issues/5734.

Will close after #5734 lands.

**Comment by StephenHeaps** [comment]
Closing as completed in #5731, #5734, #5735.
