### ISSUE TITLE
Update text on error message for adding an existing asset

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5019]
### Description: 
Update text on error message for adding an existing asset

### Steps to Reproduce 
  1.Try to add a custom token that is already in the visible asset list

**Actual result:** 
<img width=300 src=https://user-images.githubusercontent.com/17010094/155477154-6b6713bf-bb75-4d72-9bfa-a6249e61c43d.png>

**Expected result:**
`Token is already in the visible asset list` would be a more meaningful error message

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.36 (22.02.23.20)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @jamesmudgett @nuo-xu @kylehickinson @rmcfadden3

**Comment by rmcfadden3** [comment]
Without knowing anything else, this seems reasonable to me:

Header: Cannot add custom token
Body: Token is already in your visible asset list.
CTA: OK

**Comment by nuo-xu** [comment]
As per Slack
iOS copy will match Desktop for now. 
Separate issue https://github.com/brave/brave-browser/issues/21296 created to update with more user friendly error message in the future.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.36 (22.2.28.23)
- Verified error message now matches desktop 

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.3) | iPad Pro (iOS 15.4 Beta)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/156317843-f80b854d-068d-477d-835f-677ec63c39d2.png> | <img width=240 src=https://user-images.githubusercontent.com/17010094/156317620-5b5ad1fa-9302-4648-bea1-6b80daa592b6.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/156317924-56c51a6b-c5f1-44c5-a9d0-1c93a671a03b.png>
