### ISSUE TITLE
Update brave-core to 1.36 RC

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5021]

**Comment by Uni-verse** [comment]
Verification completed using version 1.36 (22.2.24.17)

**PASSED** on iPhone 12 Pro | iOS 15.1.1
**PASSED** on iPhone X | 14.4.2
**PASSED** on iPad (7th Gen) | iPadOS 15.2.1

- BraveCore version updated to: 1.36.105

![IMG_2607](https://user-images.githubusercontent.com/17885425/155800611-cf6f412e-117b-4585-8338-9525d2ac6f2e.PNG)
