### ISSUE TITLE
Slow portfolio balance calls can cause balance to show incorrectly

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#5027]
If you switch to the same network multiple times (which will cause balance calls to execute) there is a chance for the balance calls to double-up as the assets for that network will be the same.  The balances will then add up incorrectly.

Most likely there are race conditions between fetching balances and prices where `userVisibleAssets` is already set with some balances and thus its adding balances to a state that isn't currently 0.

**Comment by Pavneet-Sing** [comment]
After further usage:
- It keeps on adding the original amount to the balance
- The incorrect balance remains there after lock/unlock

Possible quick fixes:
- Don't do anything if the newly selected network is same as the previous one
- Show loading to block the selection until the balance is refreshed

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 10` running `15.4.1` using `1.37 (22.4.6.8)`

Went through the STR/Cases outlined via https://github.com/brave/brave-ios/pull/5098#issue-1166829757 and ensured that the current balance wasn't appearing as `$0.00` or was exceeding what's actually present.

**`Example`** | **`Example`**
---------------|----------------
![image](https://user-images.githubusercontent.com/2602313/162234903-baa8eb51-d619-4672-a006-ac05092f81e6.png) | ![image](https://user-images.githubusercontent.com/2602313/162234971-44088161-6959-4f25-964c-3a87d0c448b1.png)

----

Verification **PASSED** on `iPhone 6+` running `14.6` using `1.37 (22.4.6.8)`

Went through the STR/Cases outlined via https://github.com/brave/brave-ios/pull/5098#issue-1166829757 and ensured that the current balance wasn't appearing as `$0.00` or was exceeding what's actually present.

**`Example`** | **`Example`**
---------------|----------------
![image](https://user-images.githubusercontent.com/2602313/162238711-09b72a40-1a1a-45ce-a42f-82a0942731c0.png) | ![image](https://user-images.githubusercontent.com/2602313/162238854-a000e17f-d56b-4383-bf8a-755a2153d619.png)
