### ISSUE TITLE
Favicon images need trilinear magnification filter.

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#504]
Favicon images need trilinear magnification filter. Can see choppiness on reddit and cmc defaults.
https://stackoverflow.com/questions/12730384/ios-uiimageview-scaling-image-down-produces-aliased-image-on-ipad-2

![img_1147](https://user-images.githubusercontent.com/318119/49253440-42011a00-f3ec-11e8-93b8-1cbb3e7a619a.PNG)

**Comment by jhreis** [comment]
@jamesmudgett Currently we set both the minification and magnificaiton:

```
        imageView.layer.minificationFilter = kCAFilterTrilinear
        imageView.layer.magnificationFilter = kCAFilterNearest
```

To confirm, you want the `magnificationFilter` set to `kCAFilterTrilinear`?
