### ISSUE TITLE
Autofill of username on login fields on iOS MOBILE using password manager does not work

### ISSUE THREAD

**Issue by PedroPini** [brave/brave-ios#5042]
### Description: 
Unable to autofill username when using password manager like NordPass

### Steps to Reproduce 
  1.Install NordPass and enable password manage as option for Password autofill on Password under settings on iOS
  2.Go to login to your amazon or gmail account
  3.Click on username

**Actual result:** 
Username is blank not autofill options

**Expected result:**
Clicking on username should raise a prompt on the virtual keyboard on iOS to select Password and then allow NordPass to fill in the username field from the appropriate entry from the password manger's vault

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Happens every login with every website

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Does the issue resolve itself when disabling Brave Shields? NO
Does the issue resolve itself when disabling Brave Rewards? No
Is the issue reproducible on the latest version of Chrome? Yes

**Comment by kylehickinson** [comment]
Hi @PedroPini, The auto-fill powered from the iOS keyboard is unfortunately out of our control. I believe this WebKit bug report is related: https://bugs.webkit.org/show_bug.cgi?id=203299

You can continue to track progress there and hopefully Apple improves this in the future!
