### ISSUE TITLE
Force Scripts blocked stats label to two lines

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#505]
Support localization, possibly use "Scripts %@Blocked" as string and add "\r" when called.

![img_1147](https://user-images.githubusercontent.com/318119/49253509-6e1c9b00-f3ec-11e8-9bb9-8e84ce155d60.PNG)

**Comment by srirambv** [comment]
I think scripts block should be removed from stats. This will always remain zero if user doesn't block scripts from settings/shields. Its a dead UI tbh. Amount users blocking scripts globally or per site is very slim compared to users who would allow.

We can just include Ad/Tracker and time saved for now. 

cc: @anthonypkeane

**Comment by kylehickinson** [comment]
This was removed in #524
