### ISSUE TITLE
Reset local transactions from wallet settings.

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5051]
A duplicate issue of https://github.com/brave/brave-browser/issues/19760

reset local transaction from wallet settings

**Comment by Uni-verse** [comment]
Verification Completed using version `1.37 (22.3.29.15)`

Devices:
`iPhone 12 Pro` | `iOS 15.4`
`iPhone X` | `iOS 14.4.2`
`iPad (7th Gen)` | `iOS 15.2.1`

- [x] make some transactions so they show up under account activity screen
- [x] go to wallet settings and click rest transaction row
- [x] (a pop up will show up to ask users to confirm)
- [x] click reset in the pop up
- [x] go back to account activity screen, the list of transactions should be gone.


Txn before clearing | Settings | Confirm message | after clearing
-|-|-|-
![IMG_2561](https://user-images.githubusercontent.com/17885425/161118979-0f52da55-f7b8-4b78-b948-7dffcb26f6f1.PNG) | ![IMG_2562](https://user-images.githubusercontent.com/17885425/161118986-54ddf960-5fe5-42ee-8f94-27601dd42d8f.PNG) | ![IMG_2563](https://user-images.githubusercontent.com/17885425/161118988-7bd98020-6fa6-4df6-a847-976ee1feb0f0.PNG) | ![IMG_2564](https://user-images.githubusercontent.com/17885425/161118993-fa10c3d4-6eb8-4683-a9f2-f83a7dbf39c6.PNG)

Tablet
1 | 2
-|-
![IMG_0226 2](https://user-images.githubusercontent.com/17885425/161121056-669f6dcd-6fe9-49ed-9ba9-b548a0bb8602.PNG) | ![IMG_0227](https://user-images.githubusercontent.com/17885425/161121213-8c61a9e0-563e-4009-a49d-60850eac01b9.PNG)
