### ISSUE TITLE
Customize Nonce in transaction confirmation panel.

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5052]
add the ability for users to customize the nonce # for unapproved transactions in the transaction confirmation screen.

Desktop design reference:
<img width="377" alt="Screen Shot 2022-03-03 at 3 26 02 PM" src="https://user-images.githubusercontent.com/1187676/156647401-fbe2620a-2d83-46ad-8f1e-4d90e47295ea.png">
<img width="412" alt="Screen Shot 2022-03-03 at 3 26 08 PM" src="https://user-images.githubusercontent.com/1187676/156647396-7e681db6-1898-4f20-8c46-df6c2a73f272.png">

**Comment by Uni-verse** [comment]
Verification completed using version `1.37 (22.3.2.23.17)`

Devices:
`iPhone 12 Pro` | `iOS 15.4`
`iPhone X` | `iOS 14.4.2`
`iPad (7th Gen)` | `iOS 15.2.1`

- Verified Custom Nonce modal in `Advanced Settings`
- Verified `Confirmed` transaction status when entering sequential nonce value.
- Verified `Error` or `Rejected` transaction status for non-sequential nonce value. 

Note: on iOS 14, the `Save` button on the custom nonce screen is activated but not functional until user enters value in the field.  

Txn Hash - [0x56ffd9ab4a2d72aaad88de41ed66c3d25d002dffaeb4032f4052664514c0aa1e](https://ropsten.etherscan.io/tx/0x56ffd9ab4a2d72aaad88de41ed66c3d25d002dffaeb4032f4052664514c0aa1e)

iPhone | iPad
-|-
![IMG_2630](https://user-images.githubusercontent.com/17885425/160012281-60c4de1a-b9ab-4884-9cf2-d2cf48b96e02.PNG) | ![IMG_0221](https://user-images.githubusercontent.com/17885425/160012260-3d0db286-d93e-4f7f-bd83-3ccf74a1fdde.PNG)
