### ISSUE TITLE
Touch position on share sheet is not correctly placed when long pressing on link/image.

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#5054]
### Description: 
When long pressing on a link then clicking on Share Link, the position of the share sheet arrow is not pointing to the correct element the user clicked on.

### Steps to Reproduce 
  1. Open page with links and/or images
  2. Long press on image or link
  3. Click on "Share Link"

**Actual result:** 
The position of the share sheet arrow is not pointing to where the user clicked but about 200px higher.
note: the position changes depending on the size of the navigation bar, The offset is smaller with a collapsed navigation bar
<img width="239" alt="Screen Shot 2022-03-04 at 9 57 01 AM" src="https://user-images.githubusercontent.com/909331/156786153-54327ceb-323c-4dd4-be35-0ac8f35bd458.png">

**Expected result:**
The position of the share sheet arrow should be pointing to exactly where the user clicked.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Every time

**Brave Version:** 
1.36

**Device details:** 
iPad Pro 5th Generation

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
The cause of this is because we use `self.view` instead of `braveWebView`

**Comment by Uni-verse** [comment]
Verification Completed using version` 1.37 (22.3.29.15)` on `iPad (7th Gen)` running `iOS 15.2.1`

- Verified arrow is pointing to the correct item for the share sheet after context menu.
- Verified displaying correctly in both orientations

Portrait | Landscape
-|-
![IMG_0230](https://user-images.githubusercontent.com/17885425/161134487-8c15e5fc-3584-4630-9954-a1361d18f5f3.PNG) | ![IMG_0229](https://user-images.githubusercontent.com/17885425/161134520-95521a4c-c7a2-4c3b-a416-f6c9ba56f49b.PNG)
