### ISSUE TITLE
Deleted website data for 3 specific websites reappears after reopening Brave

### ISSUE THREAD

**Issue by timchilds** [brave/brave-ios#5057]
### Description: 
Deleted cookies for the following 3 websites reappears after reopening Brave.

- eaff.com
- grammarly.com
- uphold.com

Perhaps some test data that was never removed from the code?

### Steps to Reproduce 
  1. Go to Settings -> Brave Shields & Privacy -> Manage Website Data
  2. Select Remove All
  3. Close the app
  4. Open the app
  5. Go to Settings -> Brave Shields & Privacy -> Manage Website Data

**Actual result:** 
Cookie data is displayed for the following 3 websites:

- eaff.com
- grammarly.com
- uphold.com

**Expected result:**
Screen displays "No  Saved Website Data"

**Reproduces how often:**
Easily reproduced

**Brave Version:** 
Version 1.35.1 (22.2.10.16)

**Device details:** 
iPhone SE, iOS 15.3.1

### Additional Information
Video attached.

https://user-images.githubusercontent.com/28269287/156811774-cade0aab-94eb-4816-8877-bdfedaa8a015.mov

**Comment by iccub** [comment]
We had similar report from the AppStore review I believe

**Comment by iccub** [comment]
Those are non tracking cookies, just passing this info to our partners that this is an instance of Brave Browser.

Confirmed with the Ads team we can removed them altogether since they are not used on iOS anymore

**Comment by Uni-verse** [comment]
Verified completed using beta app version `1.37 (22.3.11.18)`

Devices used:

```
iPhone 12 Pro | iOS 15.1.1
iPhone X | iOS 14.4.2
iPad (7th Gen) | iOS 15.2.1
```

- Cookies no longer show after being deleted
