### ISSUE TITLE
Folder name changes back to original name when app is removed from memory and relaunched

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5065]
### Description: 
Folder name changes back to original name when app is removed from memory and relaunched

### Steps to Reproduce 
  1. Install 1.36(22.3.3.9)
  2. Create a playlist folder and give it a name ex `Fav Music`
  3. Add a playlist item to the above created folder (Optional step)
  4. Rename the folder to some other name ex `Rock Music`
  5. Close playlist and remove app from memory
  6. Relaunch browser and check the name of the folder its reverted back to the original name (in this case `Fav Music`)

**Actual result:** 

https://user-images.githubusercontent.com/17010094/157195817-88c4aefc-7e3b-4102-9966-3ad5bcd42fed.MP4

**Expected result:**
Should retain the changes

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.36 (22.3.3.9)

**Device details:** 
iOS XR (iOS 15.3.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T

**Comment by Uni-verse** [comment]
Verification completed using version `1.36 (22.3.8.21) BraveCore 1.36.108 (99.0.4844.51)`

**PASSED** on iPhone 12 Pro | iOS 15.1.1
**PASSED** iPhone X | iOS 14.4.2
**PASSED** on iPad (7th Gen) | iOS 15.2.1

- Verified relaunching app doesn't revert back to the original folder name

https://user-images.githubusercontent.com/17885425/157357579-c2f2e71c-763f-41cd-b4ad-c768fa6f38f0.MP4
