### ISSUE TITLE
Wrong folders playlist items are shown when playing an item from a different folder

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5068]
### Description: 
Wrong folders playlist items are shown when playing an item from a different folder

### Steps to Reproduce 
  1. Add 2 playlist item in folder A
  2. Add 1 playlist item in folder B
  3. Connect to CarPlay
  4. Open folder A on device and start playing an item 
  5. Use CarPlay to navigate to Folder B and play the playlist item 
  6. On mobile device, only playlist folder name updates to B but still lists playlist items from folder A

**Actual result:** 
Wrong folders playlist items are shown when playing an item from a different folder

**Expected result:**
Should update the playlist items when folder is changed. Note only happens when connected to CarPlay

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.36 (22.3.3.9)

**Device details:** 
iPhone XR (iOS 15.3.1) + CarPlay

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.3.1 running 1.36 (22.3.8.21)
- Verified steps from issue description
- Verified when folders are changed via CarPlay, it updates the folder name and folder items on the device as well
- Encountered [#5077](https://github.com/brave/brave-ios/issues/5077)

**Comment by Uni-verse** [comment]
Verified using 1.36 (22.3.11.16) on iPhone 12 Mini with iOS 14.5 (Simulator)

- Verified steps from issue description
- Verified when folders are changed via CarPlay, it updates the folder name and folder items on the device as well
