### ISSUE TITLE
CarPlay shows a message on screen when moving a file that's being played, from one folder to other 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5070]
### Description: 
CarPlay shows a message on screen when moving a file that's being played, from one folder to other 

### Steps to Reproduce 
  1. Add a playlist item in a custom folder
  2. Connect CarPlay and play the item 
  3. While playing move the item to a different folder, CarPlay shows message about no templates

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/157197122-fff0ae77-1167-47ca-bbd2-41a83b71ef22.png)

**Expected result:**
Maybe go back to Playlist home folder 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.36(22.3.3.9)

**Device details:** 
iPhone XR (iOS 15.3.1) + CarPlay

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T

**Comment by Uni-verse** [comment]
Verified using version `1.36.108 (99.0.4844.51)` on XCode Simulator `iPhone 12 Pro` running `iOS 15.2`, i`Phone X` running `iOS 14.5`

- Verified when moving a playlist item thats playing, CarPlay doesnt show message 'No templates are available to be popped'
- Verified CarPlay shows playlist home folder

iOS 15: 
<img width="401" alt="Screen Shot 2022-03-11 at 4 07 27 PM" src="https://user-images.githubusercontent.com/17885425/157994138-d913f4d0-d0bd-4575-9c1e-f4839c7434e5.png">

iOS 14:
<img width="399" alt="Screen Shot 2022-03-11 at 4 23 53 PM" src="https://user-images.githubusercontent.com/17885425/157995135-adbb63ad-db38-4b5a-8a90-64f71693a44d.png">

cc: @srirambv might want to check with the hardware as well just in case.
