### ISSUE TITLE
Youtube URL/state not remembered after closing browser

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-ios#5075]
### Description: 
When browsing Youtube, if a video is being viewed and the browser is closed, re-opening the browser will start Youtube back at the youtube homepage (youtube.com), rather than remembering the state/place the site was last on before the browser was closed. 

### Steps to Reproduce 
  1. Visit Youtube.com
  2. Start watching/streaming a video
  3. Close the browser (all the way, not just minimize/move to background)
  4. Re-launch browser

**Actual result:** 
Observe that the tab with Youtube on it has reverted from whatever video/page you were last on back to the youtube homepage. 

**Expected result:**
Browser should relaunch in on last known page.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
v1.34.1

**Device details:** 
iPad iOS v15.3

**Website problems only:**
- did you check with Brave Shields down? Yes
- did you check in Safari/Firefox (WkWebView-based browsers)? Yes

### Additional Information
User brought this issue to our attention:
https://community.brave.com/t/open-tab-urls-are-not-remembered-correctly-when-re-opening-brave/350548

**Comment by Uni-verse** [comment]
Verified using 1.37 (22.3.29.15)

Devices:
iPhone running iOS 15.4
iPhone running iOS 14.4.2
iPad running 15.2.1

 - Re-launching app will reload most recent youtube URL/state.
