### ISSUE TITLE
Add black color for the reader mode background.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5076]
Requested by a user on Twitter.
Currently we offer white, sepia and gray colors.
Safari offers all those 3 + pure black

**Comment by mrmathew** [comment]
that was me; thanks for considering the enhancement request! The pure black will be very welcome for a true dark mode UX, especially on an amoled screen.

**Comment by iccub** [comment]
thanks for raising this, should be trivial to add, we only have to rethink the UI to fit the fourth color

**Comment by Uni-verse** [comment]
Verification completed using `1.37 (22.3.23.17)`
Devices: 

`iPhone 12 Pro` | `iOS 15.4`
`iPhone X` | `iOS 14.4.2`
`iPad (7th Gen)` | `iPadOS 15.2`

Test Plan: Reference: https://github.com/brave/brave-ios/pull/5133#issue-1175332999

- [x] Enter reader mode.
- [x] Verify that black reader mode style works.
- [x] Verify that you can tap on either Reader Mode or the button to the right to access reader mode settings.
- [x] Verify that UI looks good with dark and light themes.
- [x] Navigating to different page retains reader settings.
- [x] Reader mode in Private Tabs

1 | 2 | 3
-|-|-
![IMG_2629](https://user-images.githubusercontent.com/17885425/159809393-7c284dda-b96d-4b1e-9069-832901569d4e.PNG) | ![IMG_0212](https://user-images.githubusercontent.com/17885425/159809783-b069e573-84cc-4a2f-8a32-e6274529722d.PNG) | ![IMG_2533](https://user-images.githubusercontent.com/17885425/159811112-f7a3bae8-58eb-4b52-8a39-4028dab7dd3d.PNG)
