### ISSUE TITLE
[Follow up #5068] Navigating back doesn't update the folder details on device

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5077]
### Description: 
[Follow up #5068] Navigating back doesn't update the folder details on device

### Steps to Reproduce 
  1. Follow steps from #5068
  2. Navigate to a different folder, ensure it updates the playlist items on device
  3. Navigate back to root folder on CarPlay, device still retains the different folders playlist items

**Actual result:** 
Navigating back doesn't update the folder details on device

**Expected result:**
Update playlist folder name and files to currently playing item's folder name and other list items if user navigates away from a different folder

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.36 (22.3.8.21)

**Device details:** 
iPhone XR (iOS 15.3.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T @iccub

**Comment by Uni-verse** [comment]
Verification completed using 1.36 (22.3.11.16) on XCode Simulator

Devices: 
iPhone 12 mini | iOS 15.2
iPhone X | iOS 14.5

- Verified folder details are updated when navigating between them.
