### ISSUE TITLE
FavIcon fallback aren't shown properly on Playlist

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#5086]
### Description: 
- Sometimes on Playlist, the favicon fails to load

### Steps to Reproduce 
  1. Go to `https://apple.ca`
  2. Add video to playlist
  3. Go to create a new folder. Notice the fav-icon isn't shown.

1. Go to https://www.bbc.co.uk/sounds/play/p0bp8nhq
2. Add video to playlist via menu
3. No fav-icon showing.

**Actual result:** 
No icon shown for fav-icon

**Expected result:**
![image](https://user-images.githubusercontent.com/1530031/157729439-a1840d54-9ef8-4094-bf9f-603cd43c1249.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.34?

**Comment by Uni-verse** [comment]
Verified completed using beta app version` 1.37 (22.3.11.18)`

Devices used:

```
iPhone 12 Pro | iOS 15.1.1
iPhone X | iOS 14.4.2
iPad (7th Gen) | iOS 15.2.1
```
- Verified Favicon are displayed in the playlist thumbnail images
- Adding to playlist via share menu
- Adding to playlist via url icon
- Adding to playlist via long press
- Moving playlist items

iPhone | iPad
-|-
![IMG_2520](https://user-images.githubusercontent.com/17885425/158471087-4675c780-1577-4119-b2f4-f25e5f2841a8.PNG) | ![IMG_0191](https://user-images.githubusercontent.com/17885425/158471070-936c90e4-ba53-4745-8500-73b2d709c728.PNG)
