### ISSUE TITLE
Particle Renderer not showing on Playlist audio only

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#5088]
### Description: 
- Sometimes on audio only websites, the particle renderer doesn't show properly.

### Steps to Reproduce 
  1. Go to BBC: https://www.bbc.co.uk/sounds/play/p0bp8nhq
  2. Add video to playlist via menu.
  3. Video portion shows black screen

**Actual result:** 
Video portion shows black screen.

**Expected result:**
Should show particle renderer

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
N/A

**Comment by Uni-verse** [comment]
Verified completed using beta app `version 1.37 (22.3.11.18)`

**Devices used:** 

```
iPhone 12 Pro | iOS 15.1.1
iPhone X | iOS 14.4.2
iPad (7th Gen) | iOS 15.2.1
```

- Verified particles are displayed when playing audio files
- Checked several different sources

**Sources checked:** 

- Librivox.org
- https://www.bbc.co.uk/sounds/play/p0bp8nhq

https://user-images.githubusercontent.com/17885425/158448210-6ce219cc-db10-4bbf-b285-a43cd58e52dd.MP4
