### ISSUE TITLE
Playlist player panning and tapping gestures for media navigation (iPadOS)

### ISSUE THREAD

**Issue by yuriymacdev** [brave/brave-ios#5089]
## Problem Description/Feature overview

For easier movie navigation on an iPad, add ability to scroll over the media by performing a panning gesture over the playerLayer. Also navigation gestures like double taps on the left/right sides of the playerLayer to skip 15 seconds back and forth would create a better experience.

## Design 

I've implemented these features in my local build. It works like shown on the video:

![ProposalVideo](https://github.com/yuriymacdev/FeatureProposal/raw/main/BravePlayerProposal.gif)

In general, the experience is similar to one of the official YouTube player for iPad. 
It proved to be quite convenient, at least for myself.

### Additional information 

Perhaps some basic player design improvements would be needed to indicate to the user that the feature is available to use.

I would be happy to submit a pull request if Brave/iOS team considers this feature worth adding into the official branch.

**Comment by iccub** [comment]
this is amazing @yuriymacdev, let me talk to the design team, see if we have green light for it

**Comment by yuriymacdev** [comment]
@iccub thanks for consideration!

I also added a few more gestures in my build (like double tapping in the player's central area to toggle play/pause and vertical panning gesture to adjust playback volume). Perhaps the feature planners might consider having these added as well?

Also, if I may ask - what do you have PlaylistParticleEmitter class for (the one that shows fireworks effect on top of the playlist's playerLayer when scrolling the video timeline)? Is the browser supposed to show this effect permanently when scrolling?

**Comment by iccub** [comment]
Talked to the team @yuriymacdev.
Feel free to implement the additional gestures on iPad :) if not, we will want to implement it by ourselves too I think
The new gestures you mention sounds good to me too, you can include them in your pull request

The particle emitter is to show for audio media items, items which do not have a video attached,
@Brandon-T knows more, he is in charge of the Playlist project development

**Comment by yuriymacdev** [comment]
@iccub 
> Feel free to implement the additional gestures on iPad :)
> The new gestures you mention sounds good to me too, you can include them in your pull request

Done!
[https://github.com/brave/brave-ios/pull/5102](https://github.com/brave/brave-ios/pull/5102)

**Comment by Uni-verse** [comment]
Verified using `1.37 (22.3.29.15)`

Devices:
`iPad (7th Gen)` running `iPadOS 15.2.1`
`iPhone 12 Pro` running `iOS 15.4`
`iPhone X` running `iOS 14.4.2`

- User able to scroll through video by using panning gesture
- User able to change volume with vertical panning
- Double tapping on central zone in video will toggle play/pause
- Double tapping on left/right sides will skip video by 15 seconds
- Able to use gestures on mobile devices
- Able to use gestures when playing non-video playlist items

Issues encountered:  https://github.com/brave/brave-ios/issues/5196

https://user-images.githubusercontent.com/17885425/161334084-0dab03eb-8fb1-42ea-bfea-4a5447a9df24.mov
