### ISSUE TITLE
Background audio for playlist not working for videos after locking screen [iOS 15 ONLY]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#5093]
### Description: 
Locking device screen while playlist video is playing stops pauses the video unless its in PIP mode. This is different than iOS 14 where the video continues to play after screen locks until user wakes up device. 

### Steps to Reproduce 
  1. Clean install
  2. Navigate to Brave settings menu
  3. Toggle ON 'Enable Background Audio' under 'General' 
  4. Open New Tab
  5. Navigate to Twitch.tv or Youtube, add video to playlist
  6. Open playlist to play video 
  7. Lock screen after video starts playing

**Actual result:** 
Video pauses

https://user-images.githubusercontent.com/17885425/157794873-c7e4f2ec-2d37-4641-8da2-a0d1a4bdce04.mov

**Expected result:**
Video should continue playing

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily, Repro Rate: 100% (iOS 15 ONLY)

**Brave Version:** 
`1.36 (22.3.10.22) BraveCore 1.36.108 (99.0.4844.51)`

**Device details:** 
`iPhone 12 Pro | iOS 15.1.1`
`iPad (7th Gen) | iOS 15.2.1`

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Just a note: On iOS 14, after screen locks, it will continue playing until user wakes up device

**Comment by iccub** [comment]
@Uni-verse does it happen on Brave 1.35.1 too? You added `regression` label i assume this is new bug

**Comment by iccub** [comment]
We have a fix, but let's fix this in next build due to time constraints.

This behavior changes from time to time, iOS behavior likes to change in regards to background playback

**Comment by Uni-verse** [comment]
Verification completed using `version 1.37 (22.2.11.18)` with `iPad (7th Gen)` running `iOS 15.2.1`, `iPhone 12` Pro running`'iOS 15.2`

**PASS** - Playlist playback works while device screen locked
**FAIL** - Respecting background audio setting - https://github.com/brave/brave-ios/issues/5114

https://user-images.githubusercontent.com/17885425/158295318-0a66975c-5ef7-4e1d-9f92-33f975e9b775.mov
