### ISSUE TITLE
Quick Search Engine Change - Adding Default Engines in Quick Search Toolbar

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#5101]
### Description: 

Default Selected Engine should be in Quick Search Engine list when it is used in Search Controller Screen search Toolbar.

The default Engine will be places as the first item and the default engine should be Brave Search If user is in 1 of the brave search regions ["US", "CA", "GB", "FR", "DE"]

### Steps to Reproduce 
  1. Fresh Install Brave Browser
  2. Start typing in Omnibox and accept Search suggestions
  3. Check default Search Engine (Brave Search) is not included in quick search engine bar

**Actual result:** 

![21](https://user-images.githubusercontent.com/6643505/158448266-1f5f64aa-b26a-44fe-8723-2139dc5176f4.png)

**Expected result:**

![1](https://user-images.githubusercontent.com/6643505/158448182-b48b1010-3c1c-41d9-aedc-390c280de63c.png)

**Comment by kylehickinson** [comment]
@anthonypkeane Brave isn't visible because Brave Search is already your selected search engine so it wouldn't make sense to include Brave there. This has how it has always functioned

**Comment by soner-yuksel** [comment]
Yeah this is certainly not a bug, it is working as expected. This is an enhancement over the existing behaviour. Tomorrow I will update the ticket with more details and Test Plans so it will be clear what is changed and updated.

**Comment by soner-yuksel** [comment]
The ticket is updated with additional information and PR is created for it.

**Comment by Uni-verse** [comment]
Verification completed using beta version `1.37 (22.3.11.18)`

Test Devices: 

`iPhone 12 Pro` | `iOS 15.4`
`iPhone X` | `iOS 14.4.2`
`iPad (7th Gen)` | `iOS 15.2.1`

Test Plan: 

- [x] Default search engine is used in quick search toolbar
- [x] Default search engine not displayed in Quick-Search Engines settings
- [x] Brave is default search engine in regions ["US", "CA", "GB", "FR", "DE"]
- [x] Brave is not default outside of regions ["US", "CA", "GB", "FR", "DE"]
- [x] Brave will not be default search engine in Sweden region (negative test)

iPhone (DE Region) | iPhone | iPad
-|-|-
![IMG_2525](https://user-images.githubusercontent.com/17885425/159563360-62aa7d6d-545a-449a-b547-4a4b6672f1cb.PNG) | ![IMG_2526](https://user-images.githubusercontent.com/17885425/159563365-dd53982b-7a02-439f-93a6-182aebf1246f.PNG) | ![IMG_0201](https://user-images.githubusercontent.com/17885425/159563350-7fb98011-8c2c-4b9e-aa79-01137f3ce3f8.PNG)
