### ISSUE TITLE
Add new EVM network

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#5103]
![add-network](https://user-images.githubusercontent.com/318119/158424403-dc836d08-09a8-4f6c-bcc1-2a9720cbbcb8.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40 (22.6.24.14)
- Verified steps from [ #5164](https://github.com/brave/brave-ios/pull/5164)
- Verified network picker is available in panel after connecting to Dapp
- Verified able to get the network switch confirmation window 
- Verified able to see network details when clicking on `View details` on switch network confirmation prompt
- Verified able to get the Network approval screen
- Verified able to add network and successfully 
- Verified pressing cancel on Switch confirmation screen, network isn't changed

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/175914032-c04bbb05-6bcf-45e3-b114-a663b7843323.MP4> | <video src=https://user-images.githubusercontent.com/17010094/175912702-69ede837-ed02-4e3a-8649-7a640c66c77c.MP4> | <video src=https://user-images.githubusercontent.com/17010094/175914502-dac996af-b8eb-4ebe-a613-f422a03c91f3.MP4>
