### ISSUE TITLE
Dapp add new token prompt

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#5104]
![add-token](https://user-images.githubusercontent.com/318119/158424631-9bd15ccf-ab7d-4ed7-beac-ebbe9e305b4f.png)

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.40 (22.6.22.18)
- Verified test plan from [#5187](#5187)
- Verified custom tokens can be added 
- Verified custom tokens that are added are listed under portfolio

Add ETH Token | Listed Token | Add BSC Token | Listed token
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/175290961-b6465a1f-4267-4035-8c9e-1e8cb0123087.png) | ![image](https://user-images.githubusercontent.com/17010094/175290980-4669af24-4630-436e-9125-4579a35b5432.png) | ![image](https://user-images.githubusercontent.com/17010094/175290885-cc2dc94f-5df8-4c9d-93e0-9c21a995b5fa.png) | ![image](https://user-images.githubusercontent.com/17010094/175290902-1ad94d83-a301-42b3-a2cf-6b9ac6be1bcd.png)


Verification passed on iPhone XR with iOS 15.4.1 running 1.40 (22.6.22.18)
- Verified test plan from [#5187](#5187)
- Verified custom tokens can be added 
- Verified custom tokens that are added are listed under portfolio

Add ETH Token | Listed Token | Add BSC Token | Listed token
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/175291830-13217236-5a95-4cd0-adf9-a3319df4eb0f.png) | ![image](https://user-images.githubusercontent.com/17010094/175291849-ed73024f-6fc2-4700-b13c-eaca8a05a64c.png) | ![image](https://user-images.githubusercontent.com/17010094/175291858-1c46e12a-8cd2-4c93-b351-9b9b9abd794e.png) | ![image](https://user-images.githubusercontent.com/17010094/175291876-5379a52d-1cf6-4430-8c63-2e3dacbf24f9.png)


Verification passed on iPad Pro with iOS 15.6 Beta running 1.40 (22.6.22.18)
- Verified test plan from [#5187](#5187)
- Verified custom tokens can be added 
- Verified custom tokens that are added are listed under portfolio

Add ETH Token | Listed Token | Add Fantom Token | Listed token
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/175289640-451b062f-be99-453f-b407-426b99b23f13.png) | ![image](https://user-images.githubusercontent.com/17010094/175289661-95b6d51f-7620-44eb-b908-0bce0026e091.png) | ![image](https://user-images.githubusercontent.com/17010094/175289705-0ce86593-d135-4c3b-bf1b-c36979d2dfc6.png) | ![image](https://user-images.githubusercontent.com/17010094/175289679-4c7f2d11-83af-4e40-a226-c01182ddfff1.png)
