### ISSUE TITLE
Pending confirmations button

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#5105]
![ios-wallet-pending](https://user-images.githubusercontent.com/318119/158425334-29d8c0df-1334-4cd6-80f9-0c8545765b4e.png)

![panel-pending](https://user-images.githubusercontent.com/318119/158425344-fb9cf311-360a-4b75-82a7-51faaa0fead7.png)

Button to appear when confirmations are dismissed to view the wallet.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40 (22.6.23.15)
- Verified steps from [ #5245](https://github.com/brave/brave-ios/pull/5245)
- Verified a bell icon is shown on the wallet portfolio page for a pending transaction
- Verified clicking on the bell icon on portfolio screen brings back the transaction approval screen
- Verified a bell icon is shown in the panel as well for any pending transaction
- Verified clicking on the bell icon on panel brings back the transaction approval screen
- Verified clicking on the wallet icon on a Dapp shows the pending transaction 

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/175917004-c3845794-d16f-414a-b70a-52f931e4212e.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/175916020-055766ca-5668-4a84-a85a-75c3f7a963b6.png> | <img width=430 src=https://user-images.githubusercontent.com/17010094/175917052-b6bd5466-5a59-415d-846f-06242d59c686.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/175916981-91b70f04-e083-45e5-b2c1-14c6e8f2a9d3.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/175915985-584031ce-f22b-4a87-a7bd-da9fec55d89f.png> | <img width=430 src=https://user-images.githubusercontent.com/17010094/175917025-099cdd14-9e3a-46ab-8f45-34045dee0591.png>
