### ISSUE TITLE
Dapp wallet permission UI & flow

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#5106]
Select accounts to permission
![permission](https://user-images.githubusercontent.com/318119/158425588-9839ddb1-a955-45b2-9b2e-26efa67544d1.png)

![confirm-permission](https://user-images.githubusercontent.com/318119/158429941-9d127b6f-da4a-4450-bb1e-1c82b1f20de7.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40 (22.6.24.14)
- Verified steps from [ #5186](https://github.com/brave/brave-ios/pull/5186)
- Verified Dapp origin is displayed on the connected site screen
- Verified able to connect to other accounts from edit connected site screen
- Verified once connected it changes the text to `Switch`
- Verified shows the number of connected accounts on Dapp 
- Encountered [#5594](https://github.com/brave/brave-ios/issues/5594) (Probably should be fixed for 1.40) & [#5595](https://github.com/brave/brave-ios/issues/5595) (Not blocking 1.40 release)

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/175924766-1c045b3c-c696-4a91-88c2-e8d63ce8f6e4.MP4> | <video src=https://user-images.githubusercontent.com/17010094/175924819-40799478-9e70-4a8f-b65e-34163bf1b5b2.MP4> | <video src=https://user-images.githubusercontent.com/17010094/175924849-00d4991c-bbc9-4c03-86aa-d843ab8e7116.MP4>
