### ISSUE TITLE
Dapp support account spend prompt

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#5107]
![spend](https://user-images.githubusercontent.com/318119/158425807-62429d54-0070-4c14-b650-4d9a17ef6b6a.png)

**Comment by srirambv** [comment]
<table>
      <tr colspan="4">Verification passed on the following devices running <code>1.38 (22.4.25.21)<br></code></tr>
 <tr><br>
   </tr>
   <tr>
      <th>
      </th>
      <th>:ballot_box_with_check: iPhone 7+ (iOS 14.8.1)</th>
      <th>:ballot_box_with_check: iPhone XR (iOS 15.4.1)</th>
      <th>:ballot_box_with_check: iPad Pro (iOS 15.5 Beta)</th>
   </tr>
   <tr>
      <td colspan=4></td>
   <tr>
      <td>
      </td>
      <td colspan=3>
         <ul>
         <li>Verified steps from <a href=https://github.com/brave/brave-ios/pull/5237>#5237</a></li>
         <li>Verified able to set unlimited approval for Swaps</li>
         <li>Verified able to set custom approval for Swaps</li>
        </ul>
      </td>
   </tr>
   <tr>
      <td>Activate Token
      </td>
      <td><img width=400 src=https://user-images.githubusercontent.com/17010094/165790715-360ac3fa-3a26-4e26-b0fd-09764a0db8fd.png>
      </td>
      <td><img width=320 src=https://user-images.githubusercontent.com/17010094/165791049-9afefad4-2ace-45ac-9f42-e9ab33045ee9.png>
      </td>
      <td><img width=580 src=https://user-images.githubusercontent.com/17010094/165791253-db2778b5-6870-4422-adc0-975239861356.png>
      </td>
   </tr>
   <tr>
      <td>Unlimited Approval
      </td>
      <td><img width=400 src=https://user-images.githubusercontent.com/17010094/165790768-98bde746-436a-40d9-b790-4136b23b6d6f.png>
      </td>
      <td><img width=320 src=https://user-images.githubusercontent.com/17010094/165791066-7ec98ed1-baa6-41b0-ae7d-68eba391571f.png>
      </td>
      <td><img width=580 src=https://user-images.githubusercontent.com/17010094/165791293-1c3e090c-bfdd-4558-9be3-4a6342f142a2.png>
      </td>
   </tr>
   <tr>
      <td>Edit Permission
      </td>
      <td><img width=400 src=https://user-images.githubusercontent.com/17010094/165790820-6864264a-87b9-45c5-839a-1808da989026.png>
      </td>
      <td><img width=320 src=https://user-images.githubusercontent.com/17010094/165791106-188d0700-1008-4e5f-a84e-f927fa283f05.png>
      </td>
      <td><img width=580 src=https://user-images.githubusercontent.com/17010094/165791368-4d8486fb-905c-44a3-93a0-ec89e5e6691a.png>
      </td>
   </tr>
   <tr>
      <td>Custom Allowance
      </td>
      <td><img width=400 src=https://user-images.githubusercontent.com/17010094/165790881-8ee7916a-74d0-4b62-b7cd-ffde26da1c25.png>
      </td>
      <td><img width=320 src=https://user-images.githubusercontent.com/17010094/165791134-b6c76fc4-7742-4fc5-82fc-1e1eb6b8d310.png>
      </td>
      <td><img width=580 src=https://user-images.githubusercontent.com/17010094/165791416-8abc85a9-1af7-4749-bb60-220b3add6d7a.png>
      </td>
   </tr>
</table>
