### ISSUE TITLE
Dapp connect banner to onboarding

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#5109]
![Screen Shot 2022-03-15 at 8 52 44 AM](https://user-images.githubusercontent.com/318119/158430328-6f049a40-4105-4433-b6ab-8c1381269165.png)

When a Dapp notification fires and the wallet hasn't been setup.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.40 (22.6.24.14) 
- Verified clicking on the Dapp connect banner loads the onboarding flow when wallet is not created
-----------
Verification passed on iPhone XR with iOS 15.4.1 running 1.40 (22.6.24.14) 
- Verified clicking on the Dapp connect banner loads the onboarding flow when wallet is not created
-----------
Verification passed on iPad Pro with iOS 15.6 Beta running 1.40 (22.6.24.14) 
- Verified clicking on the Dapp connect banner loads the onboarding flow when wallet is not created
