### ISSUE TITLE
Youtube pre-roll ads are not blocked

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#511]
### Description: 
Youtube pre-rol ads are not blocked

### Steps to Reproduce 
  1. Install 1.7 (18.11.30.3)
  2. Watch a video on YT in a new tab
  3. Open a new tab and visit YT and play a random video
  4. After 2-3 videos played on the second tab, preroll ad shows up

**Actual result:** 
![image from ios](https://user-images.githubusercontent.com/17010094/49272394-61a14c80-f497-11e8-9577-6778722ba8b4.png)

**Expected result:**
Should block all pre-roll ads

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent happened twice but not continuous 

**Brave Version:** 
1.7  (18.11.30.3)

**Device details:** 
iPhone 7+ (IOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
Please re-test with upcoming beta

**Comment by jhreis** [comment]
Closing this due to age, and lack of activity. If this is still an issue, please refile.

**Comment by jhreis** [comment]
Apparently still an issue, so reopening.

**Comment by iccub** [comment]
Putting it to 1.19 for time being, we consider making 1.18.1 hotfix for it

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 13.5.1 running 1.18.1(20.07.03.15)
- Verified steps from issue description
- Verified no ads shown on a normal tab
- Verified no ads shown on a private tab
- Verified opening a link via the context menu in normal/private tab doesn't show an ad
- Verified on both clean install and upgrade scenario
--------------------
Verification passed on iPhone XR with iOS 13.5 running 1.18.1(20.07.03.15)
- Verified steps from issue description
- Verified no ads shown on a normal tab
- Verified no ads shown on a private tab
- Verified opening a link via the context menu in normal/private tab doesn't show an ad
- Verified on both clean install and upgrade scenario
--------------------
Verification passed on iPhone 6 with iOS 12.4.7 running 1.18.1(20.07.03.15)
- Verified steps from issue description
- Verified no ads shown on a normal tab
- Verified no ads shown on a private tab
- Verified opening a link via the context menu in normal/private tab doesn't show an ad
- Verified on both clean install and upgrade scenario
--------------------
Verification passed on iPad Pro with iOS 12.4.5 running 1.18.1(20.07.03.15)
- Verified steps from issue description
- Verified no ads shown on a normal tab
- Verified no ads shown on a private tab
- Verified opening a link via the context menu in normal/private tab doesn't show an ad
- Verified on both clean install and upgrade scenario
--------------------
Verification passed on iPad Pro with iOS 13.6
 running 1.18.1(20.07.03.15)
- Verified steps from issue description
- Verified no ads shown on a normal tab
- Verified no ads shown on a private tab
- Verified opening a link via the context menu in normal/private tab doesn't show an ad
- Verified on both clean install and upgrade scenario
---------------------
Logged https://github.com/brave/brave-ios/issues/2698 as follow up
