### ISSUE TITLE
Dapp needs to communicate with unauthorized wallet

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#5110]
![Screen Shot 2022-03-15 at 8 53 01 AM](https://user-images.githubusercontent.com/318119/158430440-9c642097-8e8b-43de-bade-3fc7fc3d5445.png)

When a Dapp notification fires and the wallet is not authenticated.

**Comment by nuo-xu** [comment]
Can be verified using Dev 1.4 or above build.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40 (22.6.22.18)
- Verified Dapp is able to communicate with a locked wallet

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) 
-- | --
<video src=https://user-images.githubusercontent.com/17010094/175283466-580199a1-d8b7-40b0-8f97-0818cdd6e6b7.MP4> | <video src=https://user-images.githubusercontent.com/17010094/175284885-6b722ddf-816c-4da9-9663-db0c32d8a324.MP4>
