### ISSUE TITLE
Dapp needs to communicate with wallet (interaction)

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#5112]
![Screen Shot 2022-03-15 at 8 52 23 AM](https://user-images.githubusercontent.com/318119/158431174-1b886c1d-297a-4eaf-82fa-ec83c9bcbd2e.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40 (22.6.22.18)
- Verified test plan from [#5240](https://github.com/brave/brave-ios/pull/5240)
- Verified Dapp interaction works fine with wallet not created, wallet created but locked, Unlocked wallet and with ad notifications

<table>
   <tr>
      <th>
      </th>
      <th>:ballot_box_with_check: iPhone 7+ (iOS 14.8.1)</th>
      <th>:ballot_box_with_check: iPhone XR (iOS 15.4.1)</th>
      <th>:ballot_box_with_check: iPad Pro (iOS 15.6 Beta)</th>
   </tr>
   <tr>
      <td>No Wallet is created
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/175526025-7fe5ee49-95ff-4f9b-8f3c-260801560deb.MP4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/175523751-2a5e80f7-c0b9-4649-8aa9-d8a8542be453.MP4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/175528500-5f18675a-836d-4872-ad4d-7717ca7afd8c.MP4>
      </td>
   </tr>
   <tr>
      <td>Account is locked
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/175526036-ac1b1e9b-e20c-4367-aa6b-5b4f19b5d8ae.MP4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/175523793-02885c28-ead1-4011-87f0-698cd04eaa4c.MP4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/175528509-abb2b83c-df2f-4ad3-a8c5-61e110d49a2e.MP4>
      </td>
   </tr>
   <tr>
      <td>Account is not locked
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/175526040-fbd9b488-0d1f-4982-b714-d11ffdc0f654.MP4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/175523857-90349bdb-a433-4e0f-a990-565ec76681b4.MP4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/175528513-73186fa7-94db-423f-84e1-813c2ffcef78.MP4>
      </td>
   </tr>
   <tr>
      <td>Auto-dismiss after 30 sec
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/175526046-a0140ce0-3bbb-43b7-80fc-854203ea422f.MP4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/175523906-f0309ee7-93d9-4a4f-8628-28ba9a85f9cc.MP4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/175528519-4c15f1df-5d52-46fa-a80a-d28b38e6ad18.MP4>
      </td>
   </tr>
   <tr>
      <td>Notification queued behind Rewards Ads
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/175526055-16074858-5d1a-4280-b662-38dd63d1c433.MP4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/175523937-cdeef691-c43e-4ba4-be37-72afa4962838.MP4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/175528533-6fe80420-a404-4ef1-bf09-d2b505a10398.MP4>
      </td>
   </tr>
   <tr>
      <td>Overridden by Rewards Ads
      </td>
      <td><video width=1200 src=https://user-images.githubusercontent.com/17010094/175526059-8680f9b1-ef70-4f4d-b18c-9c3898125b94.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/175524140-e2348693-579e-4dc4-b96d-8d9900e4e796.mp4>
      </td>
      <td><video width=1000 src=https://user-images.githubusercontent.com/17010094/175528912-0bb99157-55e0-4ace-8296-23e4c7025017.mp4>
      </td>
   </tr>
</table>
