### ISSUE TITLE
Webview doesn't load page after clearing browsing data

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#512]
### Description: 
Webview doesn't load page after clearing browsing data

### Steps to Reproduce 
  1. Add browsing history
  2. Clear browsing data from settings
  3. Tap on favourite from new tab page, doesn't load 
  4. Open a second new tab and tap on the same favourite, page loads correctly 

**Actual result:** 
Webview doesn't load page after clearing browsing data

**Expected result:**
Should load properly on new tab on first attempt

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.11.30.3)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
#464

**Comment by danishjafri88** [comment]
Fixed in #476

**Comment by danishjafri88** [comment]
Fixed in #476
