### ISSUE TITLE
ERC20 Approval transactions display incorrectly

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5120]
### Description: 

ERC20 approval transactions display incorrectly in the account activity list view for the Ropsten network.
We use hardcoded addresses for swapping USDC and DAI on Ropsten network, and these assets are not shown in the 'Edit Visible Assets' view so they do not appear in the Account Activity view, which causes our ERC 20 approval tx summary to only show 'Approved' and not 'Approved x USDC/DAI' (top tx is ERC20Approve tx type for USDC). 

### Steps to Reproduce 
  1. Switch to Ropsten network
  2. If you have 0 DAI, swap some ETH to DAI
  3. Open swap panel and try to swap DAI to ETH. Swap button should show 'Activate Token DAI'. Tap it.
  4. Confirm the approve transaction
  5. Open account activity and view transactions list

**Actual result:** 
![activityview-development](https://user-images.githubusercontent.com/5314553/158627529-4bb2ec14-73be-436e-8adb-44e473cbc820.png)

**Expected result:**
Activity view shows DAI, USDC in Assets list
Transactions list shows 'Approved x DAI' / 'Approved x USDC' for ERC20Approve tx types

**Reproduces how often:** 
Easily reproduced

### Additional Information
Currently we are fetching tokens from the Blockchain Registry on the Ethereum Mainnet network, no matter which network is currently selected. The Blockchain Registry now returns the correct tokens and addresses for the Ropsten test network, so we should remove the hardcoded DAI / USDC addresses used for swapping on Ropsten test network and allow the user to add/remove any user assets returned from Blockchain Registry on Ropsten.

This affects a number of views:

- Edit user visible assets
  - Should be able to add DAI / USDC as visible assets on Ropsten network without adding as custom assets.
- Account activity view (account detail)
  - Asset list updated for new DAI / USDC user visible assets (if added by user)
  - Transaction list should show symbol for ERC 20 Approve transactions
- Asset search view
  - Should only show assets for that network
- Send Token
  - Same as before, should see ETH / DAI / USDC (previously they were hardcoded addresses for the assets)
- Swap Token
  - Should function the same as before, should see ETH / DAI / USDC (previously they were hardcoded addresses for the assets)

**Comment by antuun** [comment]
l do not ask for money never l only trate to make an account in metamask  but l cant because they ask me foy keys and secret phrase thats why l didnt

**Comment by Uni-verse** [comment]
Verification Completed using beta version `1.37 (22.3.23.17) BraveCore 1.37.101 (99.0.4844.83)`

Test Devices:
`iPhone 12 Pro` | `iOS 15.4`
`iPhone X` | `iOS 14.4.2`
`iPad (7th Gen)` | `iOS 15.2`

Test Steps: https://github.com/brave/brave-ios/issues/5120#issue-1171196128
Txn Hash: [0xd18c9567eb3fc0ef6de1e4f813a0376e7202d6d50f09bf43cd0423c08f066ed7](https://ropsten.etherscan.io/tx/0xd18c9567eb3fc0ef6de1e4f813a0376e7202d6d50f09bf43cd0423c08f066ed7)

- [x] Activity view shows DAI, USDC in Assets list
- [x] Transactions list shows 'Approved x DAI' / 'Approved x USDC' for ERC20Approve tx types

iOS 14 (iPhone) | iOS 15 (iPhone) | iPad (iOS 15)
-|-|-
![IMG_2626](https://user-images.githubusercontent.com/17885425/159789703-647651e3-d634-470f-88c8-9bea6dc28137.PNG) | ![IMG_2531](https://user-images.githubusercontent.com/17885425/159795486-4f651a17-82aa-4226-b962-35185724f5a0.PNG) | ![IMG_0206](https://user-images.githubusercontent.com/17885425/159794347-4532aa20-4271-4a26-b538-99e84b6118a3.PNG)
