### ISSUE TITLE
Add wallet usage to stats updater

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#5122]
### Description: 

DAU ping should include a new param that includes some wallet data.

This will require some brave-core exposure however as there is no method in KeyringService to get the last unlock date

See: 
- https://github.com/brave/brave-core/blob/master/browser/brave_stats/brave_stats_updater_params.cc
- https://github.com/brave/brave-core/tree/master/components/brave_stats/browser

### Test Plan

- Verify `wallet2` query parameter exists when testing DAU ping (via proxy or working with stats team)
- Verify if wallet is not created, `wallet2` is always `0`
- Otherwise if wallet is created the value is based on last ping and last unlock date, see documentation of this helper method for more details: https://github.com/brave/brave-core/blob/a0bb8c80a1fafd2046ba359324ebd74a2b520dd9/components/brave_stats/browser/brave_stats_updater_util.cc#L107

**Comment by porteron** [comment]
Verified that we are receiving and storing values for walletActive2. I’m seeing records with both 1 and 0 for iOS and version 1.38.0.

**Comment by srirambv** [comment]
> Just verified that we are receiving and storing values for walletActive2. I’m seeing records with both 1 and 0 for iOS and version 1.38.0.


Confirmation from @porteron that values are being received for wallet. Marking issue as verified.
