### ISSUE TITLE
Playlist only migrates first 20 items to folders

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#5125]
### Description: 
- Playlist migrates only the first 20 items when updating from 1.35 to 1.36. This bug was first reported here: https://community.brave.com/t/playlist-files-disappeared-after-brave-update-1-36/359820
- Solution: Change `fetchLimit` to `fetchBatchSize`

### Steps to Reproduce 
  1. On 1.35 add 23 videos
  2. Update to 1.36

**Actual result:** 
- Saved Folder only shows 20 videos

**Expected result:**
- Should show all 23 videos

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
- Easily reproduced

**Brave Version:** 
- 1.36

**Device details:** 
- All

### Additional Information
- Data is not lost. It's just not showing.

**Comment by Uni-verse** [comment]
Verification completed using 1.37 (22.3.29.15)

Devices: 
- iPhone 12 running iOS 15.4
- iPhone X running iOS 14.4.2
- iPad (7th Gen) running iOS 15.2.1

Scenario Tested: 

- Upgrading 1.36.1 (22.3.17.19) --> 1.37 (22.3.29.15)
- Items are retained in playlist post upgrade.
- Over 20 items are retained in playlist after upgrading app.
- Ensured user able to move, edit, share and delete playlist items.
- Creating empty folders.
- Creating new folder with items.
- Deleting empty folder, deleting all folders
- Playing video (YT)
- Playlist gestures
- Using PIP
- Audio playback (vibrivox.org)

iPad | iPhone
-|-
![IMG_0239](https://user-images.githubusercontent.com/17885425/161595830-1cd14a3a-ab13-427c-a728-f80032be75e5.PNG) | ![IMG_2576](https://user-images.githubusercontent.com/17885425/161595834-b0aea47a-d83f-48ab-8cdb-8938ec147fe0.PNG)
