### ISSUE TITLE
Manual test run for `1.36.1` on `iPad/iPhone` running `iOS 14`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#5130]
## Installer

- [ ] Check that installer is close to the size of the last release
- [ ] Check the Brave version in About and make sure it is EXACTLY as expected

## Data

- [ ] Verify that data from the previous build appears in the updated build as expected (bookmarks, history, etc.)
- [ ] Verify that cookies from the previous build are preserved after upgrade
- [ ] Verify saved passwords are retained after upgrade
- [ ] Verify stats are retained after upgrade
- [ ] Verify sync chain created in the previous version is still retained on upgrade
- [ ] Verify per-site settings are preserved after upgrade

## Playlist & Autoplay

- [ ] Verify Playlist is enabled by default on a clean install
- [ ] Verify when a site with audio/video is detected, `Playlist` button is shown in URL bar and a notification badge on the menu
- [ ] Verify clicking the `Playlist` button adds audio/video to playlist and initiates offline play
- [ ] Verify able to add audio/video to playlist via share menu
- [ ] Verify able to add audio/video to playlist via long press context menu
- [ ] Verify Autoplay is disabled by default
- [ ] Verify with Autoplay enabled, able to play audio/video automatically
- [ ] Verify with background audio enabled, able to play audio/video with device locked or app in background

**Comment by ghost** [comment]
Hello, i have this migration issue and i am glad that you are working at it's fix so fast, thank you for the bug fix.

**Comment by Thed13** [comment]
How can i help with solving this issue ? I have an iphone 6s with ios 14, so i can test the 1.36.1, right ? Thanks in advance.

**Comment by iccub** [comment]
we skip the hotfix and go directly for the 1.37 build, it will have the playlist folders migration in it as well

**Comment by iccub** [comment]
The update fixing playlist folders migration is out @Thed13, you may need to go to the app store manually since we just released it
