### ISSUE TITLE
Reader mode URLs show up in history

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5131]
### Steps to Reproduce 
  1. Go to a wikipedia article
  2. Enter reader mode
  3. Open history panel

**Actual result:** 
Reader mode url with localhost shows up.

**Expected result:**
Should not show up

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verification completed using `1.37 (22.3.23.17)`

Devices:
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad (7th Gen) | iPadOS 15.2

```
STR:

1. Go to a wikipedia article
2. Enter reader mode
3. Open history panel
```

- Verified Reader mode URLs don't show up in history
