### ISSUE TITLE
Clear Private Data should reset the Shield Preferences on Domains

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5134]
### Description: 

The `clear data` shortcut does not have ability to clear `Domain` persistent data like shield settings or other `Domain` persistent data

### Steps to Reproduce 
  1. Open a website
  2. Disable Brave Shields for the website
  3. Close tab
  4. Tap 3-dot menu
  5. Tap 'Settings'
  6. Tap 'Brave Shields & Privacy'
  7. Tap 'Clear Data Now'
  8. Re-open website from step 1

**Actual result:** 

- Brave shield and any other changes done to Shield preferences remains not changed (not reseted)

**Expected result:**

- Brave shield and other changes to Shield preferences is reset to default value of enabled

**Reproduces how often:** 
Easily reproduced

**Brave Version:** 
N/A

**Device details:** 
N/A

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information

Desktop is using a separate toggle for site & shield data, in future we might need to consider making changes to toggles to clarify the changes.

<img width="527" alt="reset" src="https://user-images.githubusercontent.com/5314553/159638783-173df0e5-ac45-459b-8bea-f9fef04cc320.png">

**Comment by Uni-verse** [comment]
Verified using `1.37 (22.3.29.15)`

Devices: 
iPhone running iOS 15.4
iPhone running iOS 14.4.2
iPad running 15.2.1

- Clearing data will reset site shield settings to default.
