### ISSUE TITLE
Update bottom bar on iPhone to use the same background colour as the URL bar

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#5153]
### Description: 

The colours were mismatched but after releasing we realized we want to have them the same

**Comment by Uni-verse** [comment]
Verified using version `1.38 (22.4.8.16)`

Devices: 
- `iPhone 12` running `iOS 15.4`
- `iPhone X` running `iOS 14.4.2`
- `iPad (7th Gen)` running `iOS 15.2.1`
-----

- Ensured top/bottom toolbar colors match in light, dark and night mode themes

iPhone Night Mode | iPhone light theme | iPad Night Mode | iPad Dark Theme
-|-|-|-
![IMG_2596](https://user-images.githubusercontent.com/17885425/162541571-d8953370-78e5-46f4-b486-9682ad55b2c7.PNG) | ![IMG_2597](https://user-images.githubusercontent.com/17885425/162541575-7099b61b-d4d2-4ff4-aa3d-5c4d09130a9a.PNG) | ![IMG_0248](https://user-images.githubusercontent.com/17885425/162541590-b59147ce-5aa6-4979-acfc-e7c928c973b0.PNG) | ![IMG_0249](https://user-images.githubusercontent.com/17885425/162541607-78c53a62-480f-4f4d-981a-cc9d88639c93.PNG)
