### ISSUE TITLE
Swipe capability for Standard to Private Tabs

### ISSUE THREAD

**Issue by warm-bagel** [brave/brave-ios#5155]
## Feature Overview 
Simple functionality - I can do a pull request and try to update it locally myself if I can find it in the code.

## Design 
No need for a sketch - just the ability to swipe rather than clicking 'Private' button & the reverse.

## User Experience 

1. Explained above
2. 
3.

**Comment by davidcollini** [comment]
Where would the user be swiping from with this feature

**Comment by davidcollini** [comment]
Also if you want to switch from a normal tab to a private tab quickly, you can long press the plus button on the bottom, but it doesn’t work the other way around

**Comment by iccub** [comment]
Yeah we do not want to have this behavior at the moment. There's enough places to go into the priv mode. I will close it and reopen if this is something we plan to do
