### ISSUE TITLE
Edit button is visible when playing a full screen video in the Playlist

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5162]
### Steps to Reproduce 
  1. Add a video to playlist
  2. Go to the folder where the video is stored
  3. Tap on 'full screen' button in top right in the video player

**Actual result:** 

![IMG_0058](https://user-images.githubusercontent.com/6950387/160409664-852830f5-ca8e-4012-bd71-504a86984ed6.PNG)

**Expected result:**
Bottom bar with 'edit' button on it should not be visible

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verification completed using `1.38 (22.4.25.21)`

Devices:
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad (7th Gen) | iOS 15.2.1

- Confirmed Edit button is not visible when playing video in full screen in the Playlist

iPad | iPhone
-|-
![IMG_0261](https://user-images.githubusercontent.com/17885425/165633297-08726774-6290-4348-a83b-ed8266289a7f.PNG) | ![IMG_2649](https://user-images.githubusercontent.com/17885425/165633310-72c6a2f2-b626-4ade-ac63-0cb94ac9f7ab.PNG)
