### ISSUE TITLE
Pressing Brave Shields Icon while presenting Tracker Intro Pop-Over does not present Shields Screen

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#5163]
### Description: 
Onboarding information pop-over showing #of trackers should be updated. The wave animation is cut by the pop-over window itself and pressing Brave icon should dismiss this pop-over and present Shields screen.

### Steps to Reproduce 
  - Fresh Install Brave
  -  Go over the onboarding
  - Open a website like Youtube that will have some trackers blocked

**Actual result:** 

The wave pulse animation is cut from bottom by the pop-over and clicking Brave icon doesn't display Shields screen

![breathing](https://user-images.githubusercontent.com/6643505/160474044-330f3202-3909-4eeb-b39a-eab961f03ccd.png)

**Expected result:**

Animation should not be cut and clicking Brave icon should present Shiels screen

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
Any version

**Device details:** 
Any device

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by Uni-verse** [comment]
Verification PASSED using 1.38 (22.4.25.21)

Devices: 
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad | iOS 15.2.1

- Ensured shields wave animation is not cut off and user is able to click to present shields screen. 

iPhone | iPad
-|-
![IMG_2658](https://user-images.githubusercontent.com/17885425/165805465-6e5c6807-d702-41d2-a961-a613991ab7b5.PNG) | ![IMG_0268](https://user-images.githubusercontent.com/17885425/165805512-5cc7ee62-c4e0-4bdd-b75a-05d3ba3911db.PNG)
