### ISSUE TITLE
Expose iOS receipt blob for VPN purchase for Premium Services website

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#5166]
## Description
Related to https://github.com/brave/account-brave-com/issues/24

Basically, for folks that have purchased the VPN product using the in-app-purchase (IAP) mechanism on iOS, we should expose a new element in the DOM:
`window.chrome.braveVpn.receipt`

This will be a base64 encoded JSON blob in a format like:
```
{
  "type": "<enum android, ios>",
  "raw_receipt": "<store receipt blob>"
}
```

This should ONLY be exposed when on the Brave Premium website (account.brave.com / account.bravesoftware.com / account.brave.software). The implementation will be iOS specific as WkWebview has limitations

Implementation for this needs to be security/privacy reviewed

**Comment by iccub** [comment]
This is qa/no until https://github.com/brave/brave-ios/issues/4805 is merged and the staging endpoints have something we can end-to-end test
