### ISSUE TITLE
Night Mode Enhancements

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#5172]
## Problem Description 
Some websites are automatically following Appearance Preferences of the system and we should not not invert the colours inside these websites. 

The list of websites that should not inject Night Mode script is consist of "twitter", "youtube", "twitch", "macrumors", "9to5mac", "soundcloud", "netflix", "github", "developer.apple", "search.brave", "wowhead"

In addition when Night Mode is activated, the Appearance of the application is automatically set to dark mode. In addition the colours for bottom and top toolbars colours will be set the darker solids black colour so the indication of dark mode will be better.

## Test Plan 

  - Enable Dark Mode
  - Check Blocked website colours are not effected
  - Check Un blocked website colours are inverted 
  - Check enable/disable Night Mode

**Actual result:** 

All website colours are inverted and there is no change in Application Appearance colours.

**Comment by Uni-verse** [comment]
Verified using version `1.38 (22.4.8.16)`

Devices: 
- `iPhone 12` running `iOS 15.4`
- `iPhone X` running `iOS 14.4.2`
- `iPad (7th Gen)` running `iOS 15.2.1`
-----
- Blocked website colors are not affected (youtube, twitter)
- Un-blocked website colors are inverted in `Night Mode`
- Top/Bottom toolbars are set to darker color when `Night Mode` is enabled
- Ensured that `Night Mode` will override the `automatic` setting in `appearance`
- Ensured `Night Mode` works from `share menu` and menu is close upon selection
- Ensured all other appearance themes work

ON | OFF
-|-
![IMG_2589](https://user-images.githubusercontent.com/17885425/162537331-e411fb04-cb95-4ebd-9d8e-c0269cbb1e20.PNG) | ![IMG_2590](https://user-images.githubusercontent.com/17885425/162537339-6cd192d0-9ca8-4046-a482-9ca12586a474.PNG)

OFF | ON
-|-
![IMG_0246](https://user-images.githubusercontent.com/17885425/162537379-f8611d8e-df2f-4a6d-b58b-0bd454e8e296.PNG) | ![IMG_0247](https://user-images.githubusercontent.com/17885425/162537383-b1623b1b-e714-4f67-9265-1b510b9d19d1.PNG)
