### ISSUE TITLE
Allow linking iOS purchased VPN to account.brave.com

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#5175]
### Description: 
We should add a new link in `Settings` > `Brave Firewall + VPN` section

- For spec, search Google Drive for `UX Flow for Redeeming VPN paid via Mobile IAP`
- Design issue https://github.com/brave/design/issues/16

New option would be something like (see design issue for exact copy):
`Link purchase to your Brave account to use on other devices`

Clicking would open the account page with a specific intent set. URL will be like https://account.brave.com/?intent=connect-receipt&product=vpn (see https://github.com/brave/account-brave-com/issues/24 for final details)

When that page is visited, the website will be able to read the receipt (see https://github.com/brave/brave-ios/issues/5166 and https://github.com/brave/account-brave-com/issues/24)

## Latest design (from Figma) - where the button is added
<img src="https://user-images.githubusercontent.com/4733304/195143715-221aa779-30aa-4cd5-956a-aae766f2bdac.png" width="250px">

![image](https://user-images.githubusercontent.com/4733304/195144800-0c805549-8ea0-4c3b-ae2d-90a369c2cc17.png)

**Comment by Uni-verse** [comment]
Verified on `1.46 (22.12.13.0)` & `1.46 (22.12.15.19)` on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPad - iPadOS 16.x

Clean profile: 

Preconditions: Use of @mailinator or @brave email accounts

1. Purchase VPN on iOS using test card
2. Enable VPN Profile
3. From VPN settings, use the Links to connect credentials to account.brave.com page

- Verified using `Link purchase to your Brave account` sends `intent=connect-receipt&product=vpn` to account.brave.com
- Verified Coming Soon message is provided to the user in production account page
- Verified request ?intent=connect-receipt-test&product=vpn will present page to connect subscription on staging account page
- Verified tapping on `connect my subscription now` will show successful connection message 
- Verified credentials buy logging into staging account page to confirm `purchased on iOS badge` appears

Example | Example | Example | Example
-|-|-|-
![IMG_0206 2](https://user-images.githubusercontent.com/17885425/208182980-b550c2ac-7544-488a-acc3-76531219755a.PNG) | ![IMG_4239](https://user-images.githubusercontent.com/17885425/208182624-47d7ff65-72ec-4e9c-8801-e34b46482da8.PNG) | ![IMG_4241](https://user-images.githubusercontent.com/17885425/208182643-e0548d9c-f1da-42f0-bff9-650af6fb336e.PNG) | ![IMG_0207](https://user-images.githubusercontent.com/17885425/208182610-38304403-4472-4492-b9de-b560b9ee7ad1.PNG)
![IMG_0874](https://user-images.githubusercontent.com/17885425/208183831-854e2562-4eba-4ddf-87fd-9fd0ae6fe011.PNG) | ![IMG_0877](https://user-images.githubusercontent.com/17885425/208184066-07bfc2a7-0bfc-4508-80e3-39d486b3108e.PNG) | ![IMG_0878](https://user-images.githubusercontent.com/17885425/208184259-6a7c2262-93b5-4b76-8dc4-60c2efcc462c.PNG) | ![IMG_0879](https://user-images.githubusercontent.com/17885425/208184265-d24ec01c-39ab-46b9-a84b-88a5892204d6.PNG)

![Screen Shot 2022-12-16 at 1 09 09 PM](https://user-images.githubusercontent.com/17885425/208184349-bc299c18-1dad-4636-b76b-b9f47624e802.png)

Upgraded Profile: 

1. Purchase VPN on iOS using test card on version 1.45.2
2. Enable VPN Profile
3. Upgrade to 1.46.x
4. Navigate to VPN settings, confirm receipt links are present
5. Use Staging link to connect credentials on the staging account page

- Verified user is able to connect subscription at `account.bravesoftware.com`

Example | Example | Example | Example
-|-|-|-
![IMG_0207](https://user-images.githubusercontent.com/17885425/208186531-2fc6f7b0-63ae-4e8c-9166-b96dab887ae2.PNG) | ![IMG_0880](https://user-images.githubusercontent.com/17885425/208190381-d3c43c5f-7e40-4626-8be2-82d60e0ba8a8.PNG) | ![IMG_0881](https://user-images.githubusercontent.com/17885425/208190385-ea410efb-53f0-45d9-a78c-575a521b4194.PNG) | ![IMG_0882](https://user-images.githubusercontent.com/17885425/208190396-7402dea7-2061-44ee-8c46-bfde77fa783f.PNG)
