### ISSUE TITLE
Update url bar button priority

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5178]
### Description: 
Likely shouldn't show reader mode button when wallet button is visible. Priority is Wallet > Playlist > Reader for buttons shown.

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 
![Simulator Screen Shot - iPhone 13 - 2022-03-30 at 11 37 59](https://user-images.githubusercontent.com/5314553/160874719-cf8b1b91-d82d-4124-af58-24f38f266e71.png)

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Marking as QA/No as there is no easy way to test it.
