### ISSUE TITLE
Tab Tray does not work in landscape mode

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5179]
### Steps to Reproduce 
  1. Use Brave in landscape mode on iPhone
  2. Tap on Tabs button to open up the tab tray

**Actual result:** 
The tab tray is displayed in portrait mode

**Expected result:**
Should be in landscape

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using version `1.38 (22.4.21.22)` on `iPhone 12 Pro` running `iOS 15.2`, `iPhone X` running `iOS 14.4.2`

- Confirmed fix where the tab tray will not open in landscape and forces view to portrait. 

https://user-images.githubusercontent.com/17885425/164839507-26ce5da8-e30c-43e4-a96e-3d6c2ca4b138.mov
