### ISSUE TITLE
[Bug] - Websites with Dynamic Loading not storing screenshots & state properly

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#5180]
### Description: 
- Some websites like Youtube & Twitter uses dynamic loading. They modify the history stack in the browser, so we don't get a callback like `didFinish` in `WKWebView`. This can cause problems where we attempt to save screenshots for TabTray or saving History. The history part was solved in an earlier PR, so this PR will solidify that and solve the screenshots part.

### Steps to Reproduce 
  1. See: https://github.com/brave/brave-ios/issues/5075

**Actual result:** 
- Youtube or Twitter not session restoring properly.
- Screenshots in TabTray sometimes blank.

**Expected result:**
- Should restore correct page
- Should show correct tabs screenshots in TabTray.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.35

**Comment by Uni-verse** [comment]
Verification completed using `1.38 (22.4.28.18)`

Devices: 
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad | IOS 15.2.1

Test Case #1 Using STR https://github.com/brave/brave-ios/issues/5075#issue-1162929123

- Confirmed that session is being restored correctly on YT and Twitter

Test Case #2 Tab tray session screenshots

1. Open many videos on youtube in new tabs
2. Close the app using the app switcher
3. Relaunch brave
4. Open tab tray

- Ensured that the correct urls are being restored in the screenshots when tab tray is open

Note: The body of the screenshots in the tab tray aren't showing intermittently. This is more noticable on iPad

iPad | iPhone
-|-
![IMG_0270](https://user-images.githubusercontent.com/17885425/165981491-de872042-77c2-47d7-aef1-0d2c5d3a0f16.PNG) | ![IMG_2672](https://user-images.githubusercontent.com/17885425/165981497-f67a1fa9-12fe-459a-b0db-cca6b75c6612.PNG)
