### ISSUE TITLE
Clear ETH permissions when resetting wallet, clearing site data

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5189]
### Description: 
When we reset wallet from wallet settings, or clear site data we should remove ETH permissions from the `Domain`

### Steps to Reproduce 
  1. Open a dapps site like app.uniswap.org
  2. Connect one of your wallet accounts
  3. Reset wallet from wallet settings
  4. Restore / add a new wallet (different account than previous)
  5. Open the same dapps site like app.uniswap.org
  6. Open wallet panel from URL bar
  7. Tap 'Connected...' to view the connected accounts (might need PR #5186). The header will state n+1 accounts connected but only list the accounts in the current wallet (the previously connected account is not shown as a row) because we didn't clear eth permissions for this domain.

**Actual result:** 
<img width="488" alt="Screen Shot 2022-03-31 at 1 29 04 PM" src="https://user-images.githubusercontent.com/5314553/161116427-72da6166-9617-41fd-9b63-34538754653e.png">

**Expected result:**
Header only lists same # of accounts as shown in account rows, `Domain` data cleared on reset

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

https://github.com/brave/brave-ios/pull/5147/files#r833678892

**Comment by srirambv** [comment]
This isn't fixed. Still seeing it happen when you restore without resetting wallet https://github.com/brave/brave-ios/issues/5594

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.40 (22.6.27.15)
- Verified steps from [#5258](https://github.com/brave/brave-ios/pull/5258)
- Verified resetting a wallet with connected accounts with Dapp and then restoring/creating a new wallet and visiting the Dapp triggers new connection 
- Verified Clearing Site Data also removes all the connected site details 
- Verified clearing site data only removes the connected account details and doesn't reset any other settings
----------
Verification passed on iPhone XR with iOS 15.4.1running 1.40 (22.6.27.15)
- Verified steps from [#5258](https://github.com/brave/brave-ios/pull/5258)
- Verified resetting a wallet with connected accounts with Dapp and then restoring/creating a new wallet and visiting the Dapp triggers new connection 
- Verified Clearing Site Data also removes all the connected site details 
- Verified clearing site data only removes the connected account details and doesn't reset any other settings
----------
Verification passed on iPad Pro with iOS 15.6 Beta running 1.40 (22.6.27.15)
- Verified steps from [#5258](https://github.com/brave/brave-ios/pull/5258)
- Verified resetting a wallet with connected accounts with Dapp and then restoring/creating a new wallet and visiting the Dapp triggers new connection 
- Verified Clearing Site Data also removes all the connected site details 
- Verified clearing site data only removes the connected account details and doesn't reset any other settings
