### ISSUE TITLE
Request desktop site still loads mobile site

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#519]
### Description: 
Request desktop site still loads mobile site

### Steps to Reproduce 
  1. Visit https://mobile.twitter.com/ or https://m.facebook.com
  2. Select `Request desktop link` from share menu
  3. Page reloads, but still stays on mobile site

**Actual result:** 
Request desktop site still loads mobile site

**Expected result:**
Should load desktop site

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.11.30.3)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
@srirambv Do you have any other instances that the Request Desktop feature does not work?

These specific examples also don't work in Safari leading me to believe Facebook/Twitter are doing something specific to ensure they are showing the user the mobile site despite the change in user-agent to reflect a desktop browser.

**Comment by tildelowengrimm** [comment]
Not actually a bug — those `m.` sites load a mobile version regardless of UA &c.

**Comment by srirambv** [comment]
@kylehickinson @tomlowenthal  FF correctly loads the desktop version of the page when requested. And even Safari loads desktop link for me. 

Here's the recording of what happens on Brave vs FF
https://drive.google.com/open?id=17_4xZxNZP3pl6icHde_SiyapR-tzTkdv

So its definitely a bug on 1.7

**Comment by tildelowengrimm** [comment]
It look like Firefox drops the `mobile.` prefix from the domain, which I think is a _bad_ behavior. If you visit `mobile.twitter.com` or whatever on desktop, you still end up at `mobile.twitter.com` or whatever.

The litmus test would be as follows:
- turn on "request desktop site"
- visit `twitter.com`
→ If you get redirected to `mobile.twitter.com` ❌
→ If you stay at `twitter.com` ✅
