### ISSUE TITLE
[Follow up to #4950] k visible for short time when transition occurs after tapping on Skip

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#5192]
### Description: 
When a user taps on Skip during onboarding, the letter k is left behind while the transaction occurs to load the next step in the onboarding process.

Still able to repro this on my iPhone 12 Pro | iOS 15.4

### Steps to Reproduce 

1.  download/install Brave (new profile so you get the onboarding experience)
2. tap on `Skip` and notice that the `k` will be visible for a few seconds while onboarding moves to the next step

**Actual result:** 

https://user-images.githubusercontent.com/17885425/161170104-57b4586d-b6dc-4409-860b-487ba6e48752.MP4

**Expected result:**
Tapping on Skip should transition into the next step without leaving any artefacts behind (even though it's a second or two)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
`1.37 (22.3.29.15)`

**Device details:** 
iPhone 12 running iOS 15.4

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Not a big deal since we are going to revamp the onboarding UI soon, let's keep this ticket open for now

**Comment by iccub** [comment]
Not valid since the onboarding has been updated
