### ISSUE TITLE
Close all tabs with a keyboard shortcut

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#5194]
## Problem Description 

This issue is actually also to Shortcut Enhancement issue https://github.com/brave/brave-ios/pull/5137.

We removed the `Close All Tabs` shortcut because the choice of shortcuts selection was clashing with system shortcuts.

## Feature Overview 

This shortcut is requested by users and this time we will use `Command-Option-W` key combination. (this is also used in Safari)

## Design 

![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-04-01 at 14 05 39](https://user-images.githubusercontent.com/6643505/161318316-9e52b97d-3ca8-4473-8eb0-5af3659ff57d.png)

## User Experience 

- Hold CMD and chose Close All Tabs shortcut or
- Press CMD+Option+W
- All Tabs should be closed and a new tab should be created

**Comment by Uni-verse** [comment]
Verified using version `1.38 (22.4.8.16)` on `iPad (7th Gen)` running `iOS 15.2.1`

- Close all tabs shortcut displayed in keyboard shortcuts 
- Pressing cmd + option + W keys will close all open tabs and create new tab

https://user-images.githubusercontent.com/17885425/162841598-2784b1eb-336a-4d59-9ec8-4cdcc8167dbd.MP4
