### ISSUE TITLE
Swipe up menu causes momentary white overlay when passcode is enabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#520]
### Description: 
Swipe up menu causes momentary white overlay when passcode is enabled

### Steps to Reproduce 
  1. Enable passcode from settings
  2. Disable `Require passcode immediately` 
  3. Swipe up to bring action menu
  4. Close swipe menu, momentary white overlay shown on browser. If too many background apps are running it is even more noticible

**Actual result:** 
Swipe up menu causes momentary white overlay when passcode is enabled

**Expected result:**
Passcode setting shouldn't cause any kind of overlay effect when using swipe up or swipe down menu 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.11.30.2)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
This is necessary to protect user information when the app becomes deactivated. Closing the app, double tapping home button, opening external menu (e.g. swiping up from bottom), all require us to cover the screen.
