### ISSUE TITLE
Sometimes Cosmetic Filters can crash when making a network request

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#5208]
### Description: 
- Under some very weird circumstances, Cosmetic Filters can crash while making a network request

### Steps to Reproduce 
  1. No idea

**Actual result:** 
- Crash in Xcode Organizer

**Expected result:**
- No Crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Very Hard

**Brave Version:** 
1.36

**Device details:** 
Any

**Comment by Uni-verse** [comment]
Cosmetic Filtering verification PASSED using RC # 2 per https://github.com/brave/brave-ios/issues/2683
