### ISSUE TITLE
New viewport units not working

### ISSUE THREAD

**Issue by bre7** [brave/brave-ios#5210]
### Description: 
New viewport units aren't working as intended in Brave.

### Steps to Reproduce 
  1. Open Brave in portrait mode
  2. Go to https://cdpn.io/pen/debug/MWrQoXg

**Actual result:** 
When scrolling down then up, sections are resized.

<img src="https://user-images.githubusercontent.com/3183848/161845024-8d90237e-39fa-4bb2-a993-77dbd2682477.gif" alt="safari" width="45%"> <img src="https://user-images.githubusercontent.com/3183848/161845084-7dba1f56-f62d-4d89-93c9-7aeabe9e6be8.gif" alt="brave" width="45%">
(Left: Safari / Right: Brave)

**Expected result:**
Fixed 100lvh height sections (bottom bar should be ignored)

**Reproduces how often:**
Always

**Brave Version:** 
Version 1.36 (22.3.11.16)

**Device details:** 
iOS 15.4.1

**Website problems only:**
- did you check with Brave Shields down? Yes
- did you check in Safari/Firefox (WkWebView-based browsers)? Yes, works as intended in Safari.

### Additional Information
Support for the new viewport units was added in iOS 15.4 (https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes)

**Comment by iccub** [comment]
I hope they added it to WKWebView instances too

**Comment by bre7** [comment]
This looks like the webkit issue https://bugs.webkit.org/show_bug.cgi?id=237979 but the "Reported Date" seems to be after iOS 15.4 was released 😕

**Comment by iccub** [comment]
nice find, looks like the target iOS version is undecided yet

https://github.com/WebKit/WebKit/blob/main/Source/WebKit/UIProcess/API/Cocoa/WKWebView.h#L640

**Comment by bre7** [comment]
Thanks for the info !

Well 🤷‍♂️ I guess time to close since it has nothing to do with Brave itself
