### ISSUE TITLE
BraveCore sometimes crashes the app when the app is killed

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#5211]
### Description: 
- Sometimes when the app is forcefully killed, it will be considered a crash because BraveCore causes it to hang.

### Steps to Reproduce 
  1. Kill the app

**Actual result:** 
- Crash

**Expected result:**
- No Crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Very very hard to reproduce

**Brave Version:** 
Any

**Device details:** 
Any

**Comment by iccub** [comment]
Switching to `QA/No` as this is hard to reproduce. We will monitor xcode crash logs in next build, see if that helped
