### ISSUE TITLE
Deletion problem Custom-Search Engine

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#5215]
### Description: 

Cant delete the Custom-Added Search Engine from Search Engines Screen when the engine is default engine. And user is not warned about this behaviour at all. 

### Steps to Reproduce 
  1. Add 2 Custom Search Engines
  2. Go Settings Search Engines
  3. Try to delete first Custom Search Engine

**Actual result:** 

First Engine cant be deleted

**Expected result:**

All Custom Engines should be deleted and user should get a proper prompt.

![engines](https://user-images.githubusercontent.com/6643505/161848299-dc2d9d70-e85f-4db3-90c6-f9e4e732f399.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Easily Reproduced

**Brave Version:** 

1.37 Appstore

**Device details:** 

All Devices Models

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by Uni-verse** [comment]
Verified using `1.38 (22.4.8.16)`

Devices: 

`iPhone 12` | `iOS 15.4`
`iPhone X` | `iOS 14.4.2`
`iPad (7th Gen)` | `iOS 15.2.1`


- Verified deleting the first item in the custom search engine list.
- Verified deleting using swipe gesture and deleting in edit mode.
- Ensured user is able to delete all the custom search engines.
- Ensured user is able to add custom search engine after deleting
