### ISSUE TITLE
Dapp Signature Request prompt

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5218]
Integrate SignatureRequestView for signature requests from dapp sites

![signature request](https://user-images.githubusercontent.com/5314553/161874130-adc1a80d-2b76-4955-a2c4-b16acd0b11af.png)

**Comment by diracdeltas** [comment]
FYI there is an open issue on desktop to show the origin of the site in the panel whenever a site makes a request. iOS should do the same. cc @jamesmudgett . https://github.com/brave/brave-browser/issues/21915

**Comment by StephenHeaps** [comment]
@diracdeltas We have a backlogged ticket for bolding the eTLD+1, which I have updated to include adding the full origin to all request panels so both will be handled in: https://github.com/brave/brave-ios/issues/5188

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.40 (22.6.23.18)
- Verified steps from [#5207](https://github.com/brave/brave-ios/pull/5207)
- Verified multiple sign requests are handled correctly 
- Verified able to sign requests in FIFO order
- Encountered [#5582](https://github.com/brave/brave-ios/issues/5582)

Request 1 | Request 2
-- | --
![image](https://user-images.githubusercontent.com/17010094/175877099-a45dc968-c5bb-4f13-bab2-3f326e187495.png) | ![Image from iOS](https://user-images.githubusercontent.com/17010094/175877472-982b0474-d740-470a-a58c-9979f59013e7.png)


----------------
Verification passed on iPhone XR with iOS 15.4.1 running 1.40 (22.6.23.18)
- Verified steps from [#5207](https://github.com/brave/brave-ios/pull/5207)
- Verified multiple sign requests are handled correctly 
- Verified able to sign requests in FIFO order
- Encountered [#5582](https://github.com/brave/brave-ios/issues/5582)

Request 1 | Request 2
-- | --
![image](https://user-images.githubusercontent.com/17010094/175877283-a54ba39c-edbd-4959-bae6-4a8ae975be18.png) | ![image](https://user-images.githubusercontent.com/17010094/175877127-33331b2d-3afd-43d7-aaec-3094d7ac3304.png)


----------------
Verification passed on iPad Pro with iOS 15.6 running 1.40 (22.6.23.18)
- Verified steps from [#5207](https://github.com/brave/brave-ios/pull/5207)
- Verified multiple sign requests are handled correctly 
- Verified able to sign requests in FIFO order
- Encountered [#5582](https://github.com/brave/brave-ios/issues/5582)

Request 1 | Request 2
-- | --
![image](https://user-images.githubusercontent.com/17010094/175877619-b0e65071-986e-49a5-a2db-4d81cad9149e.png) | ![image](https://user-images.githubusercontent.com/17010094/175877631-52662a8f-5389-417a-bd18-9aed723cfcee.png)
