### ISSUE TITLE
Crash when double tapping last selected word verifying recovery phrase

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5219]
### Description: 
Crash can occur when double tapping the last selected word when verifying the recovery phrase during wallet setup

### Steps to Reproduce 
  1. Start setup for a new wallet
  2. On verify recovery phrase view, tap 1 word
  3. When there is only 1 word in the top 'selected words' box, double tap it
  4. Crashes

**Actual result:** 

https://user-images.githubusercontent.com/5314553/161986790-2b8da3bc-a184-44c1-b45c-0924fccaf19a.mov

**Expected result:**
Doesn't crash

**Reproduces how often:**
Easily reproduced

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verification PASSED using `1.38 (22.4.28.18)`

Devices:
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad | iOS 15.2.1

- Confirmed double tapping last selected word verifying recovery phrase does not cause crash on clean install. 

- Confirmed verifying last word will cause crash on 1.37, performed brave upgrade to 1.38 RC and then loaded wallet portfolio to click banner to backup recover phrase. Ensured double tapping to select last word in the verification process will not crash app.
