### ISSUE TITLE
Inconsistent naming in context menu on bookmarks 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#522]
### Description: 
Inconsistent naming in context menu on bookmarks 

### Steps to Reproduce 
  1. Add a boookmark  
  2. Long press on the bookmark to bring context menu 
  3. Inconsistent naming for New tab and Private tab

**Actual result:** 
Context menu on Bookamarks
![file 1](https://user-images.githubusercontent.com/17010094/49288902-0dfb2700-f4c8-11e8-86fe-ec57c080feb9.jpg)

Context menu on a link in webview
![file 2](https://user-images.githubusercontent.com/17010094/49288908-15bacb80-f4c8-11e8-9716-e10b5e652ff1.jpg)

**Expected result:**
Naming should be consistent similar to context menu on webview

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.11.30.3)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
cc'ing @jamesmudgett
