### ISSUE TITLE
[Playlist] - Sometimes when near the end of a stream, particle emitter shows when seeking

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#5222]
### Description: 
- When near the end of a stream, while seeking towards the very end, sometimes the particle emitter shows

### Steps to Reproduce 
  1. Seek to the end of a stream using the gestures (drag on the video/screen). Does not happen with the `seek bar`.

**Actual result:** 
- Particle Emitter shows

**Expected result:**
- Particle Emitter should not show

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent

**Brave Version:** 
1.37.x-beta

**Device details:** 
Any

**Comment by Uni-verse** [comment]
Verification completed using `1.38 (22.4.25.21)`
Devices: 

`iPhone 12 Pro` | `iOS 15.4`
`iPhone X` | `iOS 14.4.2`
`iPad` | `iOS 15.2.1`

- Particle emitter is not active using the gestures or at any time during playtime
- Particle emitter is not active at the end of stream

https://user-images.githubusercontent.com/17885425/165574680-cee29e2c-65ef-45e5-90d2-6cf6dfc12869.mov
