### ISSUE TITLE
Add debouncing to iOS

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#5225]
### Description: 
In order to stop trackers we skip certain middle man url and go directly to the redirected urls. This is called debouncing. More [here](https://brave.com/privacy-updates/11-debouncing/).

The trackers to debounce could be found here:
https://github.com/brave/adblock-lists/blob/master/brave-lists/debounce.json

### Testing
The following site has been provided for testing debouncing:
https://dev-pages.brave.software/navigation-tracking/index.html
However, this does not support the testing of `base64` decoded redirect URLs

### Related
https://github.com/brave/devops/issues/7220

**Comment by Uni-verse** [comment]
Verification `PASSED` using `1.39 (22.5.30.17)` on iPhone 

Test Devices: 
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2

Debouncing Test Site: https://fingerprint-protection-test.herokuapp.com/debounce
Debounce adblock list: https://github.com/brave/adblock-lists/blob/master/brave-lists/debounce.json

- Verified if domain is in the debounce list like `*.leechall.com`, we navigate directly to the redirect URL instead.
- Verified if tracking is disabled, we don't debounce and load the url as is instead.
- Verified we will load the url as is if not in the debounce list (Scenario 1)

Scenario 1: https://www.youtube.com/redirect?q=https://example.com

Scenario 2: https://www.leechall.com/redirect.php?url=https://example.com

Tracking ON

Scenario 1 | Scenario 2
-|-
![IMG_3052](https://user-images.githubusercontent.com/17885425/171513525-04500b2b-276f-4d09-8ec4-04062d7f5f60.PNG) | ![IMG_3054](https://user-images.githubusercontent.com/17885425/171513558-75bfab3f-42a8-48d7-9d72-e08ee5244ce1.PNG)

Tracking OFF

Scenario 1 | Scenario 2
-|-
![IMG_3055](https://user-images.githubusercontent.com/17885425/171516546-89b9fbc2-689b-4447-8378-33703f966af2.PNG) | ![IMG_3056](https://user-images.githubusercontent.com/17885425/171514618-86318a06-13ff-4ccd-88c5-e2fb8489346b.PNG)

**Comment by Uni-verse** [comment]
Verification `PASSED` using `1.39 (22.5.30.17)` on iPad

Test Devices:
iPad (7th Gen) | iOS 15.5

Debouncing Test Site: https://fingerprint-protection-test.herokuapp.com/debounce
Debounce adblock list: https://github.com/brave/adblock-lists/blob/master/brave-lists/debounce.json

- Verified if domain is in the debounce list like *.leechall.com, we navigate directly to the redirect URL instead.
- Verified if tracking is disabled, we don't debounce and load the url as is instead.
- Verified we will load the url as is if not in the debounce list (Scenario 1)

Scenario 1: https://www.youtube.com/redirect?q=https://example.com
Scenario 2: https://www.leechall.com/redirect.php?url=https://example.com

Tracking ON

Scenario 1 | Scenario 2
-|-
![IMG_0348](https://user-images.githubusercontent.com/17885425/171518755-8f2d8721-79d2-4908-b64e-9fb4a52f44f3.PNG) | ![IMG_0351](https://user-images.githubusercontent.com/17885425/171518743-36d9262c-0493-485e-a998-fcdb07225753.PNG)

Tracking OFF

Scenario 1 | Scenario 2
-|-
![IMG_0348](https://user-images.githubusercontent.com/17885425/171518832-78d1b988-f9f5-4634-98b4-003d02f7ff12.PNG) | ![IMG_0350](https://user-images.githubusercontent.com/17885425/171518835-747e0e09-5975-4050-995b-141516a7d7ff.PNG)
