### ISSUE TITLE
Tab Tray Menu Button Long Press Action Improvement

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#5235]
## Problem Description 
Duplicate tab and easier way to reach bookmark tab is asked by users. In order to achieve this easier way, adding "Duplicate Active Tab" and "Add Bookmark" actions should be added to tab menu button long press actions

## Design
Bookmark All Tab action title should be changed as "Add Bookmark for %i Tabs" indicating the total number of bookmarks and 
"Add Bookmark" action will be added in the same section.

Underneath Bookmark section, the "Duplicate Active Tab" should be added before Close Tab Section.

![export](https://user-images.githubusercontent.com/6643505/162520744-82a7e3aa-6cee-474a-bbbc-bff008de2a49.png)

## Test Plan 

  - Open a new tab and check long press on tab tray icon in bottom toolbar
  - Press Duplicate Active Tab and check the actual tab url is opened in a new tab next to the active one
  
  - Long Press and check If Add Bookmark and Add Bookmark for %i Tabs buttons work as excpected
  
  "Add Bookmark" + "Duplicate Active Tab" should not exist in an empty open Tab.

**Comment by Uni-verse** [comment]
Verification `PASSED` using `1.39 (22.5.25.23)`

Test Devices: 
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad (7th Gen) | iOS 15.4

Using Test Plan in https://github.com/brave/brave-ios/issues/5235#issue-1197776061

- Confirmed `Duplicate Active Tab` option is displayed when long pressing tab tray icon
- Confirmed `Duplicate Active Tab` not showing in NTP
- Confirmed url is the same when duplicating active tab
- Confirmed `Add Bookmark` and `Add Bookmark for X Tabs` is working
- Confirmed `Close Tab` is working
- Confirmed Option is available in private browsing
- Confirmed `Close Tab` is only showing with a single NTP

1 | 2 | 3 | 4 | 5
-|-|-|-|-
![IMG_0338](https://user-images.githubusercontent.com/17885425/170557942-b0336124-b310-4b5d-8b35-52abf7b1484d.PNG) | ![IMG_0339 2](https://user-images.githubusercontent.com/17885425/170557952-f47e5c39-2ce6-4905-bef7-0e83bbd49bc5.PNG) | ![IMG_3023](https://user-images.githubusercontent.com/17885425/170555636-9f9e9b6b-edb7-45f1-913c-e042e8fa228f.PNG) | ![IMG_3024](https://user-images.githubusercontent.com/17885425/170555660-67111496-6740-484a-af00-59873de11463.PNG) | ![IMG_3025](https://user-images.githubusercontent.com/17885425/170555680-0f15b368-934e-4c88-8467-a3cae77b758d.PNG) | ![IMG_0338 2](https://user-images.githubusercontent.com/17885425/170557921-63e7e34e-0cc6-42fa-9a03-2083bedaf152.PNG)
