### ISSUE TITLE
Only round up token balance or transaction amount for displaying.

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5247]
Currently we round up amount for token balance and gasFee.
This could cause an issue that transaction amount is greater than available balance. 
Add unit test.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.38 (22.4.25.12)
  - iPhone 7+ (iOS 14.8.1)
  - iPhone XR (iOS 15.4.1)
  - iPad Pro (iOS 15.5 Beta 3)

* Verified steps from [#5253](https://github.com/brave/brave-ios/pull/5253)
* Verified value is only rounded up for display but is using the full value for transactions

ERC Send | ERC Swap
-- | --
<video src=https://user-images.githubusercontent.com/17010094/165903135-84cc7693-a09f-4f11-b675-addfc5eebf07.mp4> | <video src=https://user-images.githubusercontent.com/17010094/165903219-2f27adbd-aeb4-43c3-b8b0-ba5a66d20715.mp4>
