### ISSUE TITLE
Welcome onboarding revamp

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5249]

**Comment by Uni-verse** [comment]
Verification PASSED using `1.39 (22.5.24.16)` on iPhone

Test Devices: 
`iPhone 12 Pro` | `iOS 15.4`
`iPhone X` | `iOS 14.4.2`

Onboarding flow
- Confirmed user is able to complete onboarding on first launch. 
- Confirmed user can decline to to `set as default` by tapping `Not now` button and is taken to NTP.

Search Callout
- Confirmed after completing onboarding flow, the `Search callout` is displayed.
- Confirmed user is able to dismiss the `Search callout` by tapping on url bar or outside of the modal. 
- Verified url field becomes active if user taps on url bar while callout is displayed

Shields Callout
- Confirmed `Shields callout` is displayed when visiting cnn.com on first launch.
- Confirmed user is able to dismiss `Shields callout` by tapping on shields or out of the modal. 
- Verified shield panel will open when tapping on shields while the callout is displayed.

`Slide #1` | `Slide #2 `| `Slide #3` | `Device Settings` | `Search Callout` | `Shields Callout` | `Shields`
-|-|-|-|-|-|-
![IMG_2979](https://user-images.githubusercontent.com/17885425/170124333-937a1aee-57dc-4cf8-b706-abf7e9f16850.PNG) | ![IMG_2969](https://user-images.githubusercontent.com/17885425/170120072-d3276e16-e4e1-459f-94bb-05f7f322f075.PNG) | ![IMG_2970](https://user-images.githubusercontent.com/17885425/170120090-3ef599d5-9465-4b35-ae53-4e516d80acbd.PNG) | ![IMG_2971](https://user-images.githubusercontent.com/17885425/170120101-066030c6-a630-476f-862f-e7c80ab25c02.PNG) | ![IMG_2965](https://user-images.githubusercontent.com/17885425/170120834-690071b9-2536-4732-9810-8ef2e3637904.PNG) | ![IMG_2968](https://user-images.githubusercontent.com/17885425/170120058-39517186-f78f-45c4-a0cd-48a385809b9e.PNG) | ![IMG_2973](https://user-images.githubusercontent.com/17885425/170120461-226a5444-454d-4482-8536-d45b1183ad88.PNG) | ![IMG_2973](https://user-images.githubusercontent.com/17885425/170121252-bbaca3a0-2843-4056-a4fb-cffa274b3774.PNG)

<details><summary>Onboarding and skipping `Set as Default` </summary>

- Confirmed set as default banner is shown on NTP above the stats
- Confirmed tapping on banner will open default browser settings
- Confirmed user is able to dismiss by tapping on the `x` and banner will not be shown

https://user-images.githubusercontent.com/17885425/170125193-3d680bac-3e91-4a88-80c0-28a36bc72e0d.mov

</details>

<details><summary>Upgraded Profile </summary>

- Confirmed Onboarding flow is not shown after upgrading app.
- Confirmed Search callout is displayed after upgrading app.
- Confirmed Shields callout will only be displayed once throughout the profile lifetime (Will not be displayed with upgraded profile if it has earlier, not so with search callout)

</details>

**Comment by Uni-verse** [comment]
Verification PASSED using `1.39 (22.5.24.16)` on iPad

Test Devices:
`iPad (7th Gen)` | `iOS 15.4`

Onboarding flow
- Confirmed user is able to complete onboarding on first launch. 
- Confirmed user can decline to to `set as default` by tapping `Not now` button and is taken to NTP.
- Verified onboarding flow supports `landscape` and `portrait` mode for `iPad`

Search Callout
- Confirmed after completing onboarding flow, the `Search callout` is displayed.
- Confirmed user is able to dismiss the `Search callout` by tapping on url bar or outside of the modal. 
- Verified url field becomes active if user taps on url bar while callout is displayed

Shields Callout
- Confirmed `Shields callout` is displayed when visiting cnn.com on first launch.
- Confirmed user is able to dismiss `Shields callout` by tapping on shields or out of the modal. 
- Verified shield panel will open when tapping on shields while the callout is displayed.

`Slide #1` | `Slide #2` | `Slide #3` | `Search Callout` | `Shields Callout` | `Shields Panel`
-|-|-|-|-|-
![IMG_0311](https://user-images.githubusercontent.com/17885425/170133967-1bce4ab1-67b2-4ef6-ba33-20655e311376.PNG) | ![IMG_0305](https://user-images.githubusercontent.com/17885425/170133313-bb518745-d797-4b13-ba89-df3ef46c2d67.PNG) | ![IMG_0306](https://user-images.githubusercontent.com/17885425/170133316-74aacb6a-96b6-41b6-8d49-2f82d29d19c7.PNG) | ![IMG_0307](https://user-images.githubusercontent.com/17885425/170133317-45f72928-aafa-4d7b-b2f3-611c90956376.PNG) | ![IMG_0308](https://user-images.githubusercontent.com/17885425/170133321-cadf1a7f-b7c4-4294-9f78-ad9883aab60e.PNG) | ![IMG_0309](https://user-images.githubusercontent.com/17885425/170133322-1a427b34-6ba3-4f01-b770-9f21e62c3bd7.PNG)


<details><summary>Onboarding and skipping `Set as Default` </summary>

- Confirmed set as default banner is shown on NTP above the stats
- Confirmed tapping on banner will open default browser settings
- Confirmed user is able to dismiss by tapping on the `x` and banner will not be shown

</details>

<details><summary>Upgraded Profile </summary>

- Confirmed Onboarding flow is not shown after upgrading app.
- Confirmed Search callout is displayed after upgrading app.
- Confirmed Shields callout will only be displayed once throughout the profile lifetime (Will not be displayed with upgraded profile if it has earlier, not so with search callout)

</details>

**Comment by Uni-verse** [comment]
Translations for onboarding revamp will be tested in https://github.com/brave/brave-ios/issues/5355
