### ISSUE TITLE
Customize search engine crash app

### ISSUE THREAD

**Issue by sudo-elia** [brave/brave-ios#5254]
### Description: 
I 've tried to add a new customize search engine on the settings, but the app crashed.

### Steps to Reproduce 
  1. Open app
  2. Click three point
  3. Select settings
  4.  Select Search Engine
  5. Select add new customize search engine
  6. Select the old url https:// and paste -> https://presearch.org/
  7. Insert random title
  8. Click add

**Expected result:**
Formatter error because the url doesn't contain "search"

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
Version 1.37 (22.4.6.8)

**Device details:** 
Iphone 13 mini + (iOS 15.4.1)

### Additional Information
I know my url doesn't correct.

**Comment by iccub** [comment]
Fixed here https://github.com/brave/brave-ios/issues/5243
