### ISSUE TITLE
Add site connections list for dapps

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#5257]
### Description: 

Will be a screen inside Brave Wallet settings to allow the user to remove prior connections made to websites

Should have a button somewhere to clear all connections and preferences to automatically reject connection requests

Possibly this screen may also have preferences for controlling web3 notifications in general

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40(22.6.27.15)

**Manage Site Connections**


* Verified visiting a Dapp and connecting multiple accounts work 

* Verified `Remove All` under Settings -> Wallet -> `Manage Site Connections` removes all account connections to the Dapp
* Verified after `Remove All` is done, visiting the Dapp and checking wallet panel doesn't show any site to be connected
* Verified with multiple accounts connected to a Dapp, able to remove individual account under `Manage Site Connections` and the panel correctly shows/updates the number of accounts that are connected to the Dapp


**Default Wallet**

- Verified setting `Default Wallet` to `None` doesn't show any Dapp connection notification when interacting with Dapp

- Verified setting `Default Wallet` to `None` continues to show the badge on wallet to indicate a pending transaction/action

- Verified resetting `Default Wallet` from `None` to `Brave Wallet` and visiting a Dapp immediately shows the Dapp notification to interact with the Dapp

**Allow Sites to Request Accounts**

- Verified enabling `Allow Sites to Request Accounts`, visiting a Dapp shows account request to connect

- Verified disabling `Allow Sites to Request Accounts`, visiting a Dapp doesn't show any prompt to connect accounts with Dapp

**Display Web3 Notifications**

- Verified setting `Display Web3 Notification` to `OFF` and visiting a Dapp doesn't show the purple wallet Dapp notification toast

- Verified clicking on the wallet button prompts to connect the wallet 

- Verified setting `Display Web3 Notification` to `ON` and visiting a Dapp instantly shows the wallet Dapp notification toast to connect wallet 



iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/176137085-96b0584b-29f0-4e92-9ebf-8e6969fae1a2.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/176136956-a7355508-abea-4811-b89e-9dfdb53aedb9.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/176137124-e4595b43-ff9b-48ce-aa09-da9675765e8d.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/176137069-48661d07-6988-44c5-aa55-0884c36c2ba1.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/176137008-2c43fb32-51ab-45ff-b5da-2a0e6f4c9daa.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/176137158-8468d087-b5a8-4f4f-9375-2935ffa255dc.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/176137051-e20d2d05-85b5-433f-bcab-4c9432d5ba22.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/176136985-ed7e9ffb-9b46-4f3b-aa2e-84f76d7f94d0.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/176137182-9cb365ed-1dde-4a0a-9b0e-07ca40188694.png>
