### ISSUE TITLE
Search string is not updated if cursor is not at the end

### ISSUE THREAD

**Issue by brogers5** [brave/brave-ios#5262]
### Description: 
Search strings are not updated if cursor is not at the end of the omnibox

### Steps to Reproduce 
1. Type a string within the omnibox.
2. Move the cursor back within the string.
3. Type additional characters.

**Actual result:**
Search strings in content pane are not updated.

![934BD892-098B-4BBE-A9DC-B9308276C056](https://user-images.githubusercontent.com/6869577/163883469-d419b5fb-0131-4acb-b77b-6637c4c75673.jpeg)

The string will not be updated until new characters are typed at the end of the string.

Pressing either of the search buttons in the content pane will use the string as displayed in the button's UI. This is not consistent with the behavior for the keyboard's Go button, which will search using the omnibox's string instead.

**Expected result:**
Search strings should be consistent with the omnibox's contents.

**Reproduces how often:**
Easily reproduced

**Brave Version:** 
v1.37 (22.4.6.8)

**Device details:** 
iPhone 13 Pro Max (IOS 15.4.1)

**Comment by Uni-verse** [comment]
Verified using version `1.43 (22.9.2.15)`

Test Devices:
`iPhone 12 Pro` & `XR `| `iOS 15.5`
`iPad (7th Gen)` | `iOS 15.5`
`iPhone X` | `iOS 14.4.2`

Using STR in https://github.com/brave/brave-ios/issues/5262#issue-1207494838

- Verified search strings in content panel are updated.

![IMG_3552](https://user-images.githubusercontent.com/17885425/188686080-dbdfe404-c363-4973-9699-63376bac78c8.PNG)
