### ISSUE TITLE
Notification is cut off with NTP showing 

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5267]
Rewards Ad Notification will be cut off with NTP showing. 
![2A2059FE-951F-4967-A3E6-476C1034DD70_1_102_o](https://user-images.githubusercontent.com/1187676/164311843-e0982a2a-093d-40c4-b2c6-f917329d7a2a.jpeg)

**Comment by Uni-verse** [comment]
Verification Passed using version `1.38 (22.4.21.22)`

Devices: 
`iPhone 12 Pro` | `iOS 15.4`
`iPhone X` | `iOS 14.4.2`
`iPad` | `iPadOS 15.2.1`

- Rewards notification is not cut off in current tab or if displayed while opening a new tab.

iPhone | iPad
-|-
![IMG_2634](https://user-images.githubusercontent.com/17885425/164837955-c4051e57-1b65-4d71-8d8a-651900f5265a.PNG) | ![IMG_0259](https://user-images.githubusercontent.com/17885425/164837945-ab0bbd2c-52f9-4eec-895c-1b6901dd3517.PNG)
