### ISSUE TITLE
Fingerprinting 2.0: hardwareConcurrency

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#5268]
### Description: 
Based on the requirements here: https://github.com/brave/brave-browser/issues/10808
Note: we are applying the basic farbling requirements.

#### Summary
Farble window.navigator.hardwareConcurrency to be a value between 2 and the true value.

### Setup testing environment
1. Enable Web Inspector. This is done in the Settings app on the device under Safari -> Advanced
2. Enable debugging tools on safari (desktop).

### Testing:
Farbling tests can be found here:
https://dev-pages.brave.software/fingerprinting/farbling.html

#### Additional tests
1. Connect phone to computer using a cable
2. Open up browser and navigate to any link (YouTube.come, Brave.com, whatever)
3. Open web inspector in safari -> Develop -> <Your device> -> <url you opened>
4. Ensure Fingerprint protection is disabled
5. In the console write `window.navigator.hardwareConcurrency` You should have a true value (this will likely be 8)
6. Ensure Fingerprint protection is enabled
7. In the console write `window.navigator.hardwareConcurrency` You should have a fake value between 2 and the true value (note the true value may appear too)
8. Repeat this for other sites. Each page may give you a different random value (this is the point). But some sites may have the same random value (we don't have a huge list of random values to chose from)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.39 (22.5.24.16)
- Verified test plan from [#5269](https://github.com/brave/brave-ios/pull/5269) & on `https://fingerprint-protection-test.herokuapp.com/` 
- Verified with FP enabled the value is lower than the true value
- Verified with FP disabled show the true value
- Verified on older devices, the test shows `NaN` when FP is enabled and `undefined` when FP is disabled

<table>
<tr>
      <th>Device/OS
      </th>
      <th>:ballot_box_with_check: iPhone 7+ (iOS 14.8.1)</th>
      <th>:ballot_box_with_check: iPhone XR (iOS 15.3)</th>
      <th>:ballot_box_with_check: iPad Pro (iOS 15.5)</th>
   </tr>
   <tr>
      <td>Fingerprint ON
      </td>
      <td><img width=350 src=https://user-images.githubusercontent.com/17010094/170318592-f3ddf0c5-1ce0-4717-8113-ea64a1e89408.png>
      </td>
      <td><img width=280 src=https://user-images.githubusercontent.com/17010094/170318108-53aa01da-0580-4707-8eeb-d52b59037edd.png>
      </td>
      <td><img width=500 src=https://user-images.githubusercontent.com/17010094/170308430-59e294de-ae96-45fa-a6c3-77c3764c4328.png>
      </td>
   </tr>
   <tr>
      <td>Fingerprint OFF
      </td>
      <td><img width=350 src=https://user-images.githubusercontent.com/17010094/170318573-9f55ccca-6835-4e17-bcba-4383471030c6.png>
      </td>
      <td><img width=280 src=https://user-images.githubusercontent.com/17010094/170318139-3da63dfd-db40-4ffa-8bd1-ba971de96775.png>
      </td>
      <td><img width=500 src=https://user-images.githubusercontent.com/17010094/170308549-7b70bb86-2138-4bea-bd30-f0d3f46984ef.png>
      </td>
   </tr>
</table>
