### ISSUE TITLE
Favicon Fallback Not Working

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#528]
### Description: 
It doesn't seem as though the fuzzy favicon fallback (https://github.com/brave/browser-ios/issues/1551) is working in 1.7 (if it's implemented).

### Steps to Reproduce 
  1. Clean install of 1.7
  2. Visit huffingtonpost.com
  3. Add to bookmarks and add to Favorites on new tab.
  4. Visit kpwags.com.
  5. Add to bookmarks and add to Favorites on new tab.

**Actual result:** 
Favicon for huffpo doesn't have an icon or a letter, favicon for kpwags is fuzzy.
![img_0246](https://user-images.githubusercontent.com/28145373/49315173-b1ddd600-f4ba-11e8-89a9-0bbcc06fe8e5.PNG)
![img_0245](https://user-images.githubusercontent.com/28145373/49315183-b86c4d80-f4ba-11e8-82e2-ffd131f581bf.PNG)

**Expected result:**
I'd expect both favicons to have letters since that's how they displayed in 1.6:
![img_0247](https://user-images.githubusercontent.com/28145373/49315196-c5893c80-f4ba-11e8-8a70-a7aba3dbcfd0.PNG)
![img_0248](https://user-images.githubusercontent.com/28145373/49315204-cb7f1d80-f4ba-11e8-8587-3de58a19f2e0.PNG)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.7 (18.11.30.3)

**Device details:** 
iPad iOS12

**Website problems only:**
- did you check with Brave Shields down? n/a
- did you check in Safari/Firefox (WkWebView-based browsers)? n/a

**Comment by vinasound2** [comment]
Hi everybody.
I have a website with wordpress source code with flatsome theme purchased on themeforest.
I have a very good website setup but there is a bug with favicon on the website.
I do not know why my website only shows favicon in the admin page and the others are not.
This is link : https://vinasound.vn/muc-san-pham/micro-thu-am

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.18(20.06.09.18)
- Verified steps from issue description
- Verified fallback letters are shown for favourites
![image](https://user-images.githubusercontent.com/17010094/84265978-5d9cc300-ab41-11ea-861a-6f22aea5548c.png)
- Verified bookmarks use low res icons when fallback icons are not available
![image](https://user-images.githubusercontent.com/17010094/84278266-2682dd80-ab52-11ea-8cb1-b3af290ace63.png)
 - ~~Logged followup for bookmarks  #2615~~

-----
Verification passed on iPhone 7+ with iOS 13.4.5 running 1.18(20.06.16.08)
- Verified steps from issue description
- Verified fallback letters are shown for favourites
- Verified bookmarks use low res icons when fallback icons are not available
-------
Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.06.16.08)
- Verified steps from issue description
- Verified fallback letters are shown for favourites
![image](https://user-images.githubusercontent.com/17010094/85006698-14b7c080-b178-11ea-9671-6cdd078dd684.png)
- Verified bookmarks use low res icons when fallback icons are not available
![image](https://user-images.githubusercontent.com/17010094/85006709-18e3de00-b178-11ea-9d14-460f77d08fb8.png)
