### ISSUE TITLE
Option to switch to an open tab

### ISSUE THREAD

**Issue by manfromarce** [brave/brave-ios#5283]
## Problem Description

Follow an external link to a site that opens in a new tab even if it is already open in another tab.

## Feature Overview

This option gives opportunity to follow internal and external links to an open tab instead of opening a new one while browsing in Normal Browsing Mode.

It will automatically open the in the existing tab, no settings required.

## Implementation Details 

The option for this settings will be under Settings-> Tabs.

- When enabled an _**external links**_ (**URL**) opened in Brave browser (Brave is default browser) if user is not on Private Browsing Mode will be first checked if that particular URL exists in any tab.

>  If it exists the tab will be automatically switched instead of being opened in a new tab.

**Comment by iccub** [comment]
Interesting idea, does it exist in any other browser?

**Comment by manfromarce** [comment]
No, none that I am aware of.

**Comment by soner-yuksel** [comment]
This is something I also need from time to time, I believe many of us have an habit to open the exact same link in order to check something from external link. I believe the application should already work for external links this way but I realized there is a bug about this.

**Comment by soner-yuksel** [comment]
The ticket is updated with necessary feature details and proper issue label.

**Comment by anthonypkeane** [comment]
![open-switch-tab-1 1](https://user-images.githubusercontent.com/7606853/195702698-b8dafc90-441e-4ef8-8b8b-eceb88e6ec44.png)

Hi @rmcfadden3 - can you please review the copy for 

**Switch to an Open Tab**
and the sub heading

Thanks

**Comment by anthonypkeane** [comment]
Never mind Ryan, the team solved this another way.

**Comment by Uni-verse** [comment]
Verified using version `1.45 (22.10.28.19)` on the following device(s):

iPhone 12 - iOS 16
iPhone XR - iOS 15
iPhone X - iOS 14
iPads - iPadOS 16, 15

Using test plan from https://github.com/brave/brave-ios/pull/6094#issue-1395058710

- Verified opening external link will open existing tab in brave instead of opening new tab in normal mode

https://user-images.githubusercontent.com/17885425/199604738-812096f4-b9d2-43d8-b97e-4025ccfd3bb6.MP4
