### ISSUE TITLE
[Bug] - Lock Icon hard to tap in Address Bar

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#5285]
### Description: 
- The lock icon is a little too hard to tap in the address bar
- Increasing the tap area would be great for accessibility, so long as it doesn't affect tapping in the URL bar or tapping the URL itself.

### Steps to Reproduce 
  1. Tap lock icon to bring up certificate viewer

**Actual result:** 
- Tap area is too small.

**Expected result:**
- Should be easy to tap

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.37

**Comment by iccub** [comment]
Marking as `QA/No` because the main certificate viewer feature has not been tested yet.
It will be tested together
