### ISSUE TITLE
[Bug] - Tab not Deinitializing

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#5290]
### Description: 
- Closing a Tab is keeping Audio and other resources alive in the background
- Tab is actually still alive in the background

### Steps to Reproduce 
  1. Open a tab, play some audio
  2. Close the tab
  3. Audio keeps playing

**Actual result:** 
- Audio keeps playing

**Expected result:**
- Audio should stop

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
[Very hard to reproduce]

**Brave Version:** 
1.37.x

**Comment by Uni-verse** [comment]
Verification PASSED using `1.38 (22.4.28.18)`

Devices: 
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad | iOS 15.2.1

- Confirmed closing tab will deinitialize.
- Audio playing in a close tab will stop.


https://user-images.githubusercontent.com/17885425/165833393-62fbdd52-097a-42c6-b1fe-b1df857a0299.MP4

https://user-images.githubusercontent.com/17885425/165833408-d2595b3c-dd21-4a1c-89ac-ec0ac72de10e.MP4
