### ISSUE TITLE
Add "Force paste" menu item that bypasses onpaste handlers

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#5292]
### Description: 

iOS equivalent of https://github.com/brave/brave-browser/issues/22567

**Comment by Uni-verse** [comment]
Verified using `1.39 (22.5.25.23)`

Test Devices: 
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad (7th Gen) | iOS 15.4

- `Force Paste` is added to context menu for web text fields.
- `Paste` is working from context
- Confirmed Force Paste is bypassing onpaste handlers using Test Steps from https://github.com/brave/brave-browser/issues/22567#issue-1216331974

Portrait | Landscape | Force Paste | Paste
-|-|-|-
![IMG_3027](https://user-images.githubusercontent.com/17885425/170576169-dc80e7a3-0c1c-4381-939d-3f394cda80bc.PNG) | ![IMG_3028](https://user-images.githubusercontent.com/17885425/170576178-261b393c-ff32-49d9-a834-9d57e17641a0.PNG) | ![IMG_3031](https://user-images.githubusercontent.com/17885425/170576180-e61a230e-aee3-41e3-8180-dd274bc59d04.PNG) | ![IMG_3032](https://user-images.githubusercontent.com/17885425/170576181-285893e3-a213-4ad2-b10a-1a1d8a9c6a47.PNG)

iPad | iPad Paste | iPad Force Paste
-|-|-
![IMG_0342](https://user-images.githubusercontent.com/17885425/170577036-3ec0bf8f-0b89-4f04-8413-fc9ac417756b.PNG) | ![IMG_0340](https://user-images.githubusercontent.com/17885425/170577028-e576525b-10cd-45c3-9b58-439631a50bac.PNG) | ![IMG_0341](https://user-images.githubusercontent.com/17885425/170577033-ac3ebd34-93f1-4487-8d36-14c8ba71d7cf.PNG)
