### ISSUE TITLE
Remove Deferred dependency

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5305]
PR

https://github.com/brave/brave-ios/pull/5288

**Comment by Uni-verse** [comment]
Verified using 1.39 (22.5.20.17) 

Test Devices: 
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad (7th Gen) | iOS 15.4

- Performed sanity test around the areas mentioned in the PR Test Plan - https://github.com/brave/brave-ios/pull/5288#issue-1215159268

Launch `PASS`
- Content blocker compilation
- Tab setup
- Tab Restore

Authentication + Credential storage `PASS`
- Basic auth prompts
- Basic auth credential storage/fetching

Brave News `PASS`
- Standard sources/feed
- RSS feeds
- Card generation

Sync words copy expiration - `PASS`

Webcompat reporter - `PASS`

Favicon disk cache `PASS`

Temporary document URL resolution (Visiting PDFs, executables to download, etc.) `PASS`

Clearing Private Data `PASS`
