### ISSUE TITLE
Blocking scripts a second time shows count as 0 for any site

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5311]
### Description: 
Blocking scripts a second time shows count as 0 for any site

### Steps to Reproduce 
  1. Clean install and visit a page
  2. Open shields and block scripts for the site, ensure block count increases than what it was before 
  3. Disable Block script again, shield block count reduces to original value
  4. Re-enable block script, block count goes to 0 and doesn't show the actual blocked items

**Actual result:** 
Blocking scripts a second time shows count as 0 for any site

**Expected result:**
Should always show the blocked items not matter if its done a second time on the same page

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.35 onward

**Device details:** 
iPad Pro (iOS 15.5 Beta 3) / iPhone 7+ (iOS 14.8.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @Brandon-T @iccub @kjozwiak @Uni-verse

**Comment by iccub** [comment]
Please retest
