### ISSUE TITLE
Incorrect favicons in history panel post upgrade

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5312]
### Description: 
Incorrect favicons in history panel post upgrade

### Steps to Reproduce 
  1. Install 1.37 build from app store
  2. Visit a bunch of pages to add browsing history
  3. Upgrade to 1.38 build 
  4. Upon upgrade open the history page on the active tab, site favicons are all wrong
  5. Open a new link/reload the same active tab, favicons gets fixed in history 

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/166240214-8f48e76e-da60-4383-ad37-23a2a3a4cb50.png)

**Expected result:**
Show correct favicons when upgraded from previous version

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.38 (22.4.29.16)

**Device details:** 
iPad Pro (iOS 15.5 Beta 3)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information
cc: @Uni-verse @kjozwiak @iccub

**Comment by Uni-verse** [comment]
Verified using version `1.42 (22.8.10.15)`

Test Devices:
iPhone 12 | iOS 15.5
iPhone X | iOS 14.4.2
iPad (7th Gen) | iPadOS 15.5

Using STR based on https://github.com/brave/brave-ios/issues/5312#issue-1222893566

- Verified favicons in history panel are displayed correctly post upgrade.
- Verified user is able to load webpage via bookmarks.

iPhone 1.41 | iPad 1.41
-|-
![IMG_3415](https://user-images.githubusercontent.com/17885425/184243897-7c025935-393b-4f98-aa5b-c697f13fdfd4.PNG) | ![IMG_0506](https://user-images.githubusercontent.com/17885425/184243924-85ac818f-c51a-492e-b9d1-af553d77a9fa.PNG)
iPhone 1.42 | iPad 1.42
![IMG_3416](https://user-images.githubusercontent.com/17885425/184243966-7c7ede9c-9d85-497e-b394-708c837a09e1.PNG) | ![IMG_0507](https://user-images.githubusercontent.com/17885425/184243985-92db7351-187e-4f9e-8901-0cab6b7c56f3.PNG)
