### ISSUE TITLE
consider blocking wallet requests from first-party sandboxed iframes

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-ios#5314]
see https://github.com/brave/brave-browser/issues/22675 for details. iOS should already block requests from third-party iframes but please double check.

**Comment by kylehickinson** [comment]
iOS provider (and comms layer) will only be injected into main frame so iframes regardless of first-party/third-party will not have any 
`window.ethereum`/`window.web3` defined to make requests 

Refs:
- https://github.com/brave/brave-ios/blob/7a67280437ef95a38d21972247322f08574bd026/Client/Frontend/Browser/UserScriptManager.swift#L433 
- https://github.com/brave/brave-ios/blob/a944ce9ad533bf6856f095cab54694309d0398ca/Client/Frontend/Browser/UserScriptManager.swift#L372

**Comment by diracdeltas** [comment]
thanks kyle
