### ISSUE TITLE
Delete a bookmark from a folder removed all the mobile bookmarks

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#5318]
### Description: 

Delete a bookmark from a folder removed all the mobile bookmarks
### Steps to Reproduce 

1. Clean profile 1.38.x
2. Tap on 4 top tiles and open sites and add them to bookmarks
3. Tap on bookmarks
4. Add a bookmark folder `A`
5. Edit a bookmark and save that into the folder `A` and click on Done
6. Tap on bookmarks again
7. Tap on the folder A and delete the bookmarked site from the folder A and click on done
8. Click on the Bookmarks folder, no bookmarks are shown just an empty folder A is shown, click on the back isn't showing up the added bookmarks

 
**Actual result:** 
Delete a bookmark from a folder removed all the mobile bookmarks

https://user-images.githubusercontent.com/38657976/166636763-0df4cf70-46df-4ab9-9023-8e4da53f0ea9.MP4

**Expected result:**
Delete a bookmark from a folder should not remove all the mobile bookmarks

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Easy
**Brave Version:** 

1.38 (22.4.29.16)
**Device details:** 
iPhone 15.4.1

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @brave/qa-team @iccub @anthonypkeane

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPhone 8 iOS version 15.4.1` running `Brave version 1.38 (22.5.4.18)`

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.4` using `1.38 (22.5.4.18)`

Reproduced the original issue mentioned via https://github.com/brave/brave-ios/issues/5318#issue-1225000010 using `1.38 (22.4.29.16)` and verified that it's working as expected using `1.38 (22.5.4.18)`.
