### ISSUE TITLE
Once the bookmark is added directly into the folder user can't view the bookmarks which are added to the mobile bookmarks

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#5319]
### Description: 
Once the bookmark is added directly into the folder user can't view the bookmarks which are added to the mobile bookmarks

### Steps to Reproduce 
  1. Clean profile 1.38.x
  2. Tap on the 4 top tiles and open sites and bookmark them
  3. Create a folder A inside the mobile bookmarks
  4. Open a site buzzfeed.com or any site
  5. Bookmark the buzzfeed.com directly into the folder A
  6. Click on the buzzfeed.com bookmark and confirmed the site is opened
  7. Navigate back to the folder A and open the folder A
  8. Click on the `Back` button, no bookmarks are shown which are already added in mobile bookmarks

**Actual result:** 
Once the bookmark is added directly into the folder user can't view the bookmarks which are added to the mobile bookmarks

https://user-images.githubusercontent.com/38657976/166642530-eb419872-0257-4f53-8027-cb37db719826.MP4

**Expected result:**
User should be able to view all the bookmarks

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Easy
**Brave Version:** 
1.38 (22.4.29.16)

**Device details:** 
iPhone 15.4.1

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information

cc: https://github.com/orgs/brave/teams/qa-team @iccub @anthonypkeane

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPhone 8 iOS version 15.4.1` running `Brave version 1.38 (22.5.4.18)`

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.4` using `1.38 (22.5.4.18)`

Reproduced the original issue mentioned via https://github.com/brave/brave-ios/issues/5319#issue-1225039078 using `1.38 (22.4.29.16)` and verified that it's working as expected using `1.38 (22.5.4.18)`.
