### ISSUE TITLE
Inverted colors

### ISSUE THREAD

**Issue by stephenrudge** [brave/brave-ios#5330]
### Steps to Reproduce 
  1. Open brave browser
  2. Go to google images
  3. Picture is inverted

**Actual result:**  added
![1A90A1AA-D7B8-487F-85A7-3B111A0C8097](https://user-images.githubusercontent.com/105181957/167464664-85d1040a-7cda-4861-a702-6d80bc91ec61.png)

![94874FDE-C19E-4BCF-B93F-75A05E6EF3B3](https://user-images.githubusercontent.com/105181957/167464653-cc3bde5c-50fc-4556-8c74-7af140250279.png)

**Expected result:**
Not to have inverted 

**Reproduces how often:** [Easily reproduced, Intermittent Issue] every time 

**Brave Version:**  1.37

**Device details:**  iPhone 12ProMax IOS 15.4.1

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?  Yes, safari and Firefox are working correctly

**Comment by Brandon-T** [comment]
Hi, do you happen to have some sort of `Accessibility` settings enabled? I wasn't able to reproduce this issue on an iPhone 12 Pro on 15.4.1.

**Comment by stephenrudge** [comment]
No i do not.
I have attached a video here of my steps

Stephen Rudge

“Life is like a camera. Focus on what’s important, capture the good times, and if things don’t work out, just take another shot”

**Comment by iccub** [comment]
Is this with `Night mode` setting enabled?

**Comment by stephenrudge** [comment]
No. 
However, there was a app update today, which fixed the issue. Thank you.

**Comment by iccub** [comment]
good to hear :) let's close this, feel free to reopen if this still happens to you

**Comment by stephenrudge** [comment]
No, it is not
