### ISSUE TITLE
`Share Link` from the `Mobile Bookmarks` menu doesn't work

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#5331]
### Description: 

Clicking/Tapping on `Share Link` on bookmarks via `Mobile Bookmarks` doesn't seem to work. Doesn't seem like a recent regression as it's also broken via `1.37 (22.4.6.8)` which has been released for some time now.

### Steps to Reproduce
 
  1. launch `1.37 (22.4.6.8)` and skip all the onboarding
  2. tap on any of the top tiles and bookmark them into the default folder (doesn't need to be added into a folder)
  3. once added, go into `Settings` -> `Bookmarks`
  4. long tap on the bookmark that was added previous and select `Share Link` (notice that nothing happens)
 
**Actual result:** 

When a user taps/selects `Share Link` via the `Mobile Bookmarks` menu, nothing happens.

https://user-images.githubusercontent.com/2602313/167548023-f5d98266-c2e7-48a4-b207-326fc3b09e49.mp4

**Expected result:**

When a user taps/selects `Share Link` via the `Mobile Bookmarks` menu, we should be opening the `Share` window/modal.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases outlined above.

**Brave Version:** 

* **`1.37 (22.4.6.8)`** - Reproduced
* **`1.38 (22.5.4.18)`** - Reproduced

**Device details:** 

* `iPhone 11` running `iOS 15.4.1` - Reproduced
* `iPad Air 3rd Gen` running `iOS 15.4` - Reproduced

**Website problems only:**
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.39 (22.5.24.16)
- Verified steps from issue description
- Verified share sheet is brought up when selecting Share from bookmarks page

iPhone (iOS 14.8.1) | iPhone XR (iOS 15.3) | iPad Pro (iOS 15.5 Beta)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/170330255-0d55ef51-6454-43f2-9fa9-b09edf3fecc4.MP4> | <video src=https://user-images.githubusercontent.com/17010094/170330314-a8546288-9181-4420-81d2-1f48b6bec6b5.MP4> | <video src=https://user-images.githubusercontent.com/17010094/170330213-a2b3aa8b-c4b5-4d36-809f-304ee062f175.MP4>
