### ISSUE TITLE
Show eTLD+1 prominently in wallet

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5337]
iOS version of https://github.com/brave/brave-browser/issues/21787

> https://hackerone.com/reports/1514823
> 
> see thread here: https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1647647313657369

cc: @kylehickinson  @nuo-xu  This should probably go with Dapp support.

**Comment by kylehickinson** [comment]
Duplicate of #5188

This is definitely going in with dapp support
