### ISSUE TITLE
Incorrect microphone permission description text

### ISSUE THREAD

**Issue by samducker** [brave/brave-ios#5338]
### Description: 
On iOS Brave application the microphone permission text is referencing video and this is likely to get the Brave iOS app removed from the apple store in a subsequent release and/or confuse users.

### Steps to Reproduce 
  1. Access a website that needs to use the microphone
  2. See the permission dialog

**Actual result:** 

Client/Info.plist

`	<key>NSMicrophoneUsageDescription</key>
	<string>This lets you take and upload videos.</string>`

**Expected result:**

I have provided suggested text here

Client/Info.plist

`	<key>NSMicrophoneUsageDescription</key>
	<string>This allows use of your microphone when using Brave.</string>`

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Every time you first need microphone permission on Brave iOS

**Brave Version:** 

1.37

**Device details:** 

iPhone 11 X Pro

**Comment by Uni-verse** [comment]
Verification `PASSED` using version `1.39 (22.5.24.16)`

Test Devices:

iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad (7th Gen) | iOS 15.4

- Microphone permission text uses the following string `This allows use of your microphone when using Brave`

iPhone | iPad
-|-
![IMG_2997](https://user-images.githubusercontent.com/17885425/170367517-fd77dfe7-bef1-403f-aeba-1d6a0db5138e.PNG) | ![IMG_0319](https://user-images.githubusercontent.com/17885425/170367505-0c8d5799-c68b-4246-a864-58cdc50ec591.PNG)
