### ISSUE TITLE
Perf: Optimize text_classifer model memory usage

### ISSUE THREAD

**Issue by atuchin-m** [brave/brave-ios#5343]
The clone of Desktop/Android issue: https://github.com/brave/brave-browser/issues/21960, where memory consumption of ads library was improved and merged into 1.39.x.
Here we should only verify memory consumption improvement of iOS browser with enabled ads.

**Comment by Uni-verse** [comment]
Changing to `QA/No` as QA was not able to obtain a debug build to run the instrument test. This was already demonstrated on Desktop/Android and the code is the same. 

CC: @kjozwiak @kylehickinson
