### ISSUE TITLE
Tab Restoration Problem for Reader Mode Enabled Pages

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#5345]
### Description: 

After enabling Reader Mode on a webpage If the Reader Mode is not disabled and session restore is occurred at some reason, the website will show can not be reached error page.

### Steps to Reproduce 
  1. Go to wikpedia.com and click a language
  2. Enabled Reader Mode and do the same in multiple tabs
  3. Kill the app entirely and open the app so the websites will restore

**Actual result:** 

Showing error and faulty restore session

![Simulator Screen Shot - iPhone 13 - 2022-05-13 at 11 08 15](https://user-images.githubusercontent.com/6643505/168328123-70fc1512-e589-44b5-abb4-a4d5d4338543.png)

**Expected result:**

No error should be shown and web site should be restored properly

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily Preroduced

**Brave Version:** 
Any

**Device details:** 
Any

**Website problems only:**
- did you check with Brave Shields down? N_A
- did you check in Safari/Firefox (WkWebView-based browsers)? N_A

**Comment by Uni-verse** [comment]
Verified using version `1.38 (22.5.13.17)` on `iPhone 12 Pro` running `iOS 15.4` & `iPhone X` running iOS `14.4.2`

Using STR from https://github.com/brave/brave-ios/issues/5345#issue-1235459083

- Ensured that the session is properly restored when reader mode is enabled on a page. 

https://user-images.githubusercontent.com/17885425/168387397-bc554100-de6f-4879-a36c-b4b77cc912d7.MP4

**Comment by Uni-verse** [comment]
Verified using `1.38 (22.5.13.17)` on `iPad (7th Gen)` running `iOS 15.2.1`

Using STR from https://github.com/brave/brave-ios/issues/5345#issue-1235459083

- Ensured that the session is properly restored when reader mode is enabled on a page.
- User is able to enable/disable reader mode

![IMG_0303](https://user-images.githubusercontent.com/17885425/168388515-3b8efbf8-ec35-4659-a5c3-d56a55857134.PNG)
