### ISSUE TITLE
Update User Agent to 15.5

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5351]

**Comment by Uni-verse** [comment]
Verified using 1.39 (22.5.26.19)

Test Devices:
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad | iOS 15.5

`PASS` - Confirmed user agent updated to`15.5`
`FAIL` - user agent matches safari on iPhone
`PASS` - user agent matches safari on iPad

<details><summary>iPhone 12 iOS 15.X</summary>

Device OS version: `15.4`

Brave Browser

`user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Mobile/15E148 Safari/604.1
`

Safari Browser

`user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 15_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1`

</details>

<details><summary>iPhone X iOS 14.X</summary>

Device OS version: `14.4.2`

Safari Browser

`User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1
`
Brave Browser

`user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Mobile/15E148 Safari/604.1`

</details>

<details><summary>iPad iOS 15.X</summary>

Device OS version: `15.5`


Safari Browser

`user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15`

Brave Browser

`user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15`

</details>
