### ISSUE TITLE
New tab page favicons show a planet instead of the Brave icon

### ISSUE THREAD

**Issue by aguscruiz** [brave/brave-ios#5357]
## Problem Description 

When I open a new tab, the favicon displayed is a planet. It should be our Brave logo
![IMG_BA7A30FB6B74-1](https://user-images.githubusercontent.com/15734630/169080974-aa72957a-d61e-4356-8de4-0fcaa99bb386.jpeg)

## Design 
https://www.figma.com/file/SGHkYHpABu09if0mmxCT5g/%F0%9F%8D%8E-iOS?node-id=607%3A15182

Screenshot attached
Nevermind the actual new tab design, it's just Work in progress. Just the favicon would do for now
![image](https://user-images.githubusercontent.com/15734630/169086496-def9a877-8ed0-4b75-bdde-eb8e9b13636d.png)

## User Experience 

1. Open Brave browser
2. Create a new tab
3. See icon

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.6]
Brave build: 1.57 (23.8.18.20)
BraveCore: 1.57.47 (116.0.5845.96)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Create a new tab
3. Tap `Tabs switching button` > Verify
4. Create a few more tabs and open any website > Verify
5. Switch to `Private` tabs mode
6. Open NTP > Verify
7. Open any website > Verify

**ACTUAL RESULTS:**
- Verified that `Brave` logo is shown for `NTP`
- Verified that the website's logo is shown if the website is opened
- Verified the same behavior for `Normal` and `Private` tabs

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/02213d6f-1335-4ad2-b162-42aa4c27f446) | ![2](https://github.com/brave/brave-ios/assets/128532965/80d38b1f-915e-434f-bdca-4608e9d0dada) |

**Comment by aguscruiz** [comment]
I'm noticing the favicon in @vlad-hoff's screenshot doesn't look right. The Brave logo looks compressed. 

Look side by side here. I think the icon used has been resized weirdly.


<img width="704" alt="image" src="https://github.com/brave/brave-ios/assets/15734630/5a541cd4-5e9d-4216-99b1-e2f3f753787c">

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 [iOS 16.6]
- iPad Air [iPadOS 16.5.1]
Brave build: 1.57 (23.8.21.22)
BraveCore: 1.57.47 (116.0.5845.96)
```
---------------------------

**STEPS:**
Followed the steps from https://github.com/brave/brave-ios/issues/5357#issuecomment-1684485244

**ACTUAL RESULTS:**
- Verified that the Brave logo is shown and not shrinked

---------------------------

*iPhone*

|1.57 (23.8.21.22)| 1.57 (23.8.18.20) vs 1.57 (23.8.21.22)|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/943863d6-8e7d-4a05-97d4-6c33f9f94d3f) | ![2](https://github.com/brave/brave-ios/assets/128532965/2b81e603-1bf0-4a19-98b4-791484b8e584) |

*iPad*

|1.57 (23.8.21.22)| 1.57 (23.8.18.20) vs 1.57 (23.8.21.22)|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/592abe06-db08-4cb1-8027-4503a3b80ea2) | ![2](https://github.com/brave/brave-ios/assets/128532965/47418981-f66b-4a8a-9d0a-1a22c9591e53) |
