### ISSUE TITLE
Add badge to wallet url bar icon when pending request available

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5358]
### Description: 
When there is a pending request from a dapp site, we should show a badge to the wallet icon/button in the URL bar.

<img width="218" alt="Screen Shot 2022-05-18 at 1 59 07 PM" src="https://user-images.githubusercontent.com/5314553/169111329-2f0a033d-2649-48d0-b717-d130dba98565.png">

### Additional Information
See 'In Planning - 0.1 Mobile Dapp Support/Hide notif. banner' in Figma

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 devices running 1.40 (22.6.24.14)
- Verified steps from [#5383](https://github.com/brave/brave-ios/pull/5383)
- Verified connecting to Dapp and closing the connect window shows a notification dot on the wallet button
- Verified when there are no pending requests no bell icon is shown in panel or in wallet screen
- Verified creating a pending transaction from wallet and then visiting a Dapp triggers the wallet icon and shows a dot on the icon
- Verified accepting/rejecting a pending transaction automatically removes the badge on the wallet
- Verified `Display Web3 Notifications` in Brave Wallet setting is set to enabled by default
- Verified disabling `Display Web3 Notifications` doesn't show any Dapp notification.
- Verified disabling `Display Web3 Notifications` continues to show the badge on wallet icon when there is a pending request
----------
Verification passed on iPhone XR with iOS  15.4.1 running 1.40 (22.6.24.14)
- Verified steps from [#5383](https://github.com/brave/brave-ios/pull/5383)
- Verified connecting to Dapp and closing the connect window shows a notification dot on the wallet button
- Verified when there are no pending requests no bell icon is shown in panel or in wallet screen
- Verified creating a pending transaction from wallet and then visiting a Dapp triggers the wallet icon and shows a dot on the icon
- Verified accepting/rejecting a pending transaction automatically removes the badge on the wallet
- Verified `Display Web3 Notifications` in Brave Wallet setting is set to enabled by default
- Verified disabling `Display Web3 Notifications` doesn't show any Dapp notification.
- Verified disabling `Display Web3 Notifications` continues to show the badge on wallet icon when there is a pending request
----------
Verification passed on iPad Pro+ with iOS 15.6 Beta running 1.40 (22.6.24.14)
- Verified steps from [#5383](https://github.com/brave/brave-ios/pull/5383)
- Verified connecting to Dapp and closing the connect window shows a notification dot on the wallet button
- Verified when there are no pending requests no bell icon is shown in panel or in wallet screen
- Verified creating a pending transaction from wallet and then visiting a Dapp triggers the wallet icon and shows a dot on the icon
- Verified accepting/rejecting a pending transaction automatically removes the badge on the wallet
- Verified `Display Web3 Notifications` in Brave Wallet setting is set to enabled by default
- Verified disabling `Display Web3 Notifications` doesn't show any Dapp notification.
- Verified disabling `Display Web3 Notifications` continues to show the badge on wallet icon when there is a pending request
