### ISSUE TITLE
[Privacy Hub] Make stats appear un-tappable in private browsing mode

### ISSUE THREAD

**Issue by timchilds** [brave/brave-ios#5359]
## Problem Description 
The privacy hub is not available in private browsing mode. However the stats still appear to be tappable, which some users might interpret as the privacy hub is broken. Please see video below.

https://user-images.githubusercontent.com/28269287/169145193-62553bf7-cd90-4c75-b189-3bd2f91e11b8.MP4

## Feature Overview
When the user is in private browsing mode, remove everything from the stats that make it appear tappable:

- Icon
- Title
- Three Dots
- Pulse on tap

## Design 
N/A

**Comment by Uni-verse** [comment]
Verified using version `1.39 (22.5.24.16)`

Test Devices:
`iPhone 12 Pro` | `iOS 15.4`
`iPhone X` | `iOS 14.4.2`
`iPad (7th Gen)` | `iPadOS 15.4` 

- Confirmed opening addition tabs doesn't change the state.
- Confirmed that the following items are removed from the stats feature in private tabs and when in private browsing mode.

- [x] Icon
- [x] Title
- [x] Three Dots
- [x] Pulse on tap

Regular Tab | Private Tab
-|-
![IMG_2967](https://user-images.githubusercontent.com/17885425/170107614-57983f01-4feb-4fc1-9d43-080ab94618bd.PNG) | ![IMG_2966](https://user-images.githubusercontent.com/17885425/170107581-22fd9983-64dd-4d09-8d97-8fd898c65080.PNG)


iPad
![IMG_0304](https://user-images.githubusercontent.com/17885425/170108768-9082ea4c-20de-4c3f-ab27-64530802562d.PNG)
