### ISSUE TITLE
Changes to sync codephrase

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5362]

**Comment by Uni-verse** [comment]
Verification `PASSED` using `1.41 (22.7.19.13)`

Test Devices:
`iPhone 12 Pro` | `iOS 15.5`
`iPhone X` | `iOS 14.4.2`
`iPad (7th Gen)` | `iPadOS 15.5`

Using Test Plan in https://github.com/brave/brave-core/pull/12300#issue-1140261372

Case I:

- Verified connecting to Desktop sync chain with 24 words (old) using mobile/tablet
- Verified able to join sync chain by scanning and entering code words

Case II: 

- Verified unable to connect to sync chain on desktop after 2nd of August and later with mobile/tablet device. 
- Verified unable to connect iOS devices when changing date on old client to 2nd of August and later

Case III: 

- Verified user able to connect to new (25 word) sync chain using mobile/desktop 

Mobile | Tablet | Desktop
-|-|-
![IMG_3287](https://user-images.githubusercontent.com/17885425/179855002-dcad2d62-3f53-4bb5-ac6e-a97567cd960b.PNG) | ![IMG_0462](https://user-images.githubusercontent.com/17885425/179855021-46fc5919-77c7-493f-918a-b1fa45ca41b2.PNG) | ![Screen Shot 2022-07-19 at 2 50 18 PM](https://user-images.githubusercontent.com/17885425/179855037-c8ec547f-b334-4a9b-8a7c-c7bd6d6eb4d0.png)


Case IV: 

- Verified error message when connecting to sync chain on other devices with date moved 2 days forward

Example | Example 
-|-
![IMG_0459](https://user-images.githubusercontent.com/17885425/179852692-039c981e-0633-4572-bfae-062efe62494f.jpg) | ![IMG_3284](https://user-images.githubusercontent.com/17885425/179852713-203b679a-6179-45e2-bf96-a9f84bc9c40f.jpg)


Case V:

- Verified error message when connecting to sync chain on other devices with date moved 2 days back

Example | Example
-|-
![IMG_0460](https://user-images.githubusercontent.com/17885425/179852552-3b1ade28-ac73-4ed6-b13d-a47f3c2b6a3d.jpg) | ![IMG_3283](https://user-images.githubusercontent.com/17885425/179852562-8e36b685-1f57-4eaa-a28c-7b2b32cbfdd5.jpg)


Case VI: 

- Verified that an error message is display when entering code words incorrectly
- Verified user is able to still connect to sync chain after the error message is displayed

Example | Example
-|-
![IMG_0461](https://user-images.githubusercontent.com/17885425/179854846-f0ce5277-2d8b-4628-ad33-7c823cbef140.jpg) | ![IMG_3286](https://user-images.githubusercontent.com/17885425/179854865-d9eb3666-c6e2-4989-ade7-adcee07cd63b.jpg)
