### ISSUE TITLE
Web3 is not updated with permitted account if user ignore wallet notification 

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5365]
If user has previously give permission to a web3 site, when web3 requests permission again, a wallet notification will show as expected. 
Users at this moment, can 
1. click to connect wallet
2. swipe up to dismiss the wallet
3. ignore the wallet til it's timeout
With choices 2 and 3, user can still open wallet panel buy clicking the wallet icon in the url bar. 
It will then ask user to unlock the wallet. After user unlocks the wallet, because this domain has already have some permitted accounts, this web3 should be updated with an account connected.
Actual result: web3 didn't get updated.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40 (22.6.24.14)
- Verified steps from [#5366](https://github.com/brave/brave-ios/pull/5366)
- Verified Web3 continues to list the connected accounts even when a Dapp notification is ignored

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.6) | iPad Pro (iOS 15.6 Beta)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/175977750-a3da6a84-e2a6-4486-8cf7-388ddec6f4f9.MP4> | <video src=https://user-images.githubusercontent.com/17010094/175977779-e311a936-e389-44a2-9e40-f382a78d4799.MP4> | <video src=https://user-images.githubusercontent.com/17010094/175977833-2fb20404-fabc-42bc-9577-cfbb4b665317.MP4>
