### ISSUE TITLE
Remove Favorite is causing browser crash

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#537]
### Description: 
Remove Favorite is causing browser crash
### Steps to Reproduce 
  1. Launch brave with clean profile
  2. Open `google.com` in new tab
  3. Add site to fovorites
  4. Open a new tab and edit the added favorite to any name (e.g. Google A)
  5. Navigate to google site and click on `Sports` 
  6. Sports seach page is displayed
  7. Add search page to fovorites
  8. Open a new tab, now you can see two favorites added for google
  9. Remove favorite `Sports`
 10.  Brave crashes
  

**Actual result:** 
Remove Favorite is causing browser crash
https://drive.google.com/open?id=1AGWKz8B0odWvyjHTL6O2jjPGZjYin9m-

**Expected result:**
Brave should not crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
1.7 (18.11.30.3)

**Device details:** 
Iphone8 - iOS 12.1

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by srirambv** [comment]
Reproduced on iPad as well.
