### ISSUE TITLE
Integrate BraveTalk Jitsi SDK

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5370]
Consider using Jitsi's SDK to improve quality and reliability of Brave Talk calls on iOS devices.

**Comment by Uni-verse** [comment]
Verified using version `1.45 (22.11.7.16)` on the following device(s):

iPhone 12 Pro - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPads - iPadOS 16.x, 15.x

Using Test Plan from https://github.com/brave/brave-ios/pull/6020#issue-1374988414

- Verified starting a call on talk.brave.com launches the native Jitsi UI on Dev / Beta Channel
- Verified starting a call on release channel does not launch the native Jitsi UI

Dev / Beta Channel Example | Dev / Beta Channel Example | Dev / Beta Channel Example
-|-|-
![IMG_0757](https://user-images.githubusercontent.com/17885425/200431683-a093ec10-d415-41ef-b8a5-63657696c6c1.PNG) | ![IMG_0758](https://user-images.githubusercontent.com/17885425/200431686-4f753343-bfc4-4a33-a1a7-3b572922b3ea.PNG) | ![IMG_0759](https://user-images.githubusercontent.com/17885425/200431688-69cf8d62-82d0-4d8c-882c-3695f402df53.PNG)
![IMG_0176](https://user-images.githubusercontent.com/17885425/200431923-aeb5f350-80a6-47b2-9867-fd26355c754c.PNG) | ![IMG_0177](https://user-images.githubusercontent.com/17885425/200431925-dbd18e3a-837d-423b-8511-948367612b8d.PNG) | ![IMG_0178](https://user-images.githubusercontent.com/17885425/200431926-cf7f9860-c0d8-460d-b49f-6acc68491faf.PNG)


Release Channel (iOS) | Release Channel (iOS) | Release Channel (iOS)
-|-|-
![IMG_0173](https://user-images.githubusercontent.com/17885425/200432140-e1607adb-92fc-4644-ade2-83e665ddc200.PNG) | ![IMG_0174](https://user-images.githubusercontent.com/17885425/200432142-e7ae7a1f-33ea-485d-a63d-5f40d31821e9.PNG) | ![IMG_0175](https://user-images.githubusercontent.com/17885425/200432144-a85899a7-508c-40a3-b80b-809c5390dfb3.PNG)

Release Channel (iPad) | Release Channel (iPad)
-|-
![IMG_0760](https://user-images.githubusercontent.com/17885425/200432965-c9c7aa49-ca50-47ed-ac33-4ecb147c35c0.PNG) | ![IMG_0761](https://user-images.githubusercontent.com/17885425/200432982-80727a74-110b-4568-b907-e2f8a7d42c71.PNG)
