### ISSUE TITLE
Add debounce de-amp rules

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#5373]
### Description: 
A small part of de-amping is debouncing. Modifications will be made to the debounce rules so it can handle some de-amping as well. 

More rules can be found here: https://docs.google.com/document/d/1kvHbQMdE_vxmRWRz0LfAHzf6XoTT_pQXSwxth5rVhsk/edit#heading=h.gdplhac936j7

**Comment by Uni-verse** [comment]
Verified using version `1.42 (22.8.15.22)`

Test Devices:
iPhone 12/XR iOS 15.x
iPad iOS 15.5
iPhone X iOS 14.4.2

Verified using the test page in the test cases portion of https://github.com/brave/brave-browser/issues/23121#issue-1251376884

Tracking Disabled | Tracking Enabled
-|-
![IMG_0021](https://user-images.githubusercontent.com/17885425/185157605-34df3fba-4dc8-4154-941a-c1eb59175729.PNG) | ![IMG_0022](https://user-images.githubusercontent.com/17885425/185157612-3a5717bf-f065-4e7b-a267-475da759cb33.PNG)
![IMG_0514](https://user-images.githubusercontent.com/17885425/185157869-401c09bc-58ed-4a87-8a35-064135920ea3.PNG) | ![IMG_0515](https://user-images.githubusercontent.com/17885425/185157872-35ca7d1b-2f0e-4933-a36b-f6beeab7ddc1.PNG)
