### ISSUE TITLE
Block bad window.fetch() messages using the Rust engine

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#5374]
### Description: 
Block certain `window.fetch()` api calls by connecting to the rust engine asynchronously using apples built in javascript to swift mechanism `WKUserContentController`

### Test plan
1. You may test by building the debug version of the application and seeing if no javascript errors are thrown on the injected scripts.
2. Go to a few sites with known trackers and test that nothing is broken. (YouTube, Facebook, instagram, etc)

#### Test 2:
1. Switch languages to something that uses regional lists. (ex switch phone to the polish)
2. Go to twitter and make sure the login works

#### Test 3:
1. Go to  https://openocean.finance/ and make sure the page loads (should ideally run the application on debug mode to ensure no asserts are triggered)

**Comment by Uni-verse** [comment]
Verified using `1.41 (22.7.19.13)`

Test Devices: 
`iPhone 12 Pro` | `iOS 15.5`
`iPhone X` | `iOS 14.4.2`
`iPad` | `iPadOS 15.5`

Using Test Plan in https://github.com/brave/brave-ios/issues/5374#issue-1246635916

Test 1: 

- Verified shields still working on sites with known blockers (ads and trackers are being blocked)

Test 2:

- Verified user is able to login to twitter after switching language to Polish

iPhone | iPad
-|-
<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/179634339-df2f7203-474c-43b6-8fd4-d5955309d84a.PNG"> | <img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/179807200-deac43dc-d866-4d52-9e76-9931bae14321.PNG">


Test 3: 

Verified loading https://openocean.finance/ and make sure the page loads

iPhone | iPad
-|-
<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/179634440-f3c54145-b351-4295-8804-b5686107f866.PNG"> | <img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/179807360-9caa6d38-08a9-4c8b-9cf8-9572aa9b9ce6.PNG">
