### ISSUE TITLE
Favorites widget does not show favorites for some users

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5375]
Need investigation

**Comment by jd0x018c** [comment]
I'm having this issue. If there's anything I can do to help troubleshoot let me know. ![image](https://user-images.githubusercontent.com/77125259/170493997-3f3d2ebd-3ddc-4a7d-85be-1e74bcba5fa7.jpeg)

**Comment by iccub** [comment]
What is your iOS version? 14 or 15

**Comment by jd0x018c** [comment]
15.4.1

**Comment by jd0x018c** [comment]
Looks resolved to me now.

**Comment by iccub** [comment]
Let's close it then. We tried to find a way to reproduce and no luck. Will reopen if the problem still persists

**Comment by jamesjreynolds** [comment]
I'm experiencing the same issue.
- iPhone XR, 
- iOS version 16.1.1
- Brave version 1.45.1 (12.11.17.19)
