### ISSUE TITLE
NTP set to default banner still shown after setting brave as default in onboarding

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#5376]
### Description: 
User lands on NTP after first launch onboarding and `set to default` banner is displayed above stats even though user has set brave as default browser in the onboarding process.

### Steps to Reproduce 
  1. Clean install
  2. Select `Set to Default` in the second slide to load default browser settings
  3. Select brave from the list under `Default Browser App`
  4. Navigate back to Brave app, NTP will load
  5. Observe

**Actual result:** 
Banner is shown

![IMG_2986](https://user-images.githubusercontent.com/17885425/170139034-daf4bb1a-f957-4970-805e-ce5673838554.PNG)

**Expected result:**
Banner should not be shown

![IMG_2985](https://user-images.githubusercontent.com/17885425/170138242-53c57177-380d-464c-9067-7cb415ee5a93.PNG)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
Versions 1.38.x, 1.39.x

**Device details:** 
iPhone 12 Pro | IOS 15.4
iPad | iPadOS 15.4

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
We actually can't determine if a user has set the default browser to us unfortunately, but I think we were supposed to remove the button anyways if the user taps on it, cc @iccub for confirmation

**Comment by iccub** [comment]
Agreed let's remove the banner upon user click during onboarding

**Comment by Uni-verse** [comment]
Verified using 1.39 (22.5.26.19)

Test Devices:
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad | iOS 15.4

Scenario 1: 
1. Clean install
2. At the onboarding screen select `Set as Default`
3. Proceed to set brave as default in device settings, return to brave app. 
4. Observe NTP

Scenario 2: 
1. Clean install
2. At the set as default onboarding screen select `Not Now`
3. Observe banner above stats feature on NTP

Scenario 3: 
1. Clean install
2. At the set as default onboarding screen select `Not Now`
5. Tap on the set as default banner above displayed above stats
6. Set default browser to brave when settings are opened
7. Return to app
8. Observe NTP

- Confirmed banner is not shown on NTP if brave is set as default 
- Confirmed banner is shown if user skips `Set as default` Step
- Confirmed banner will not be displayed after clicking on it to set brave as default before returning.

https://user-images.githubusercontent.com/17885425/170769481-40155850-ca39-4ea7-ab33-594d6726400c.MP4
