### ISSUE TITLE
Dapp permissions request model shown for website with access granted

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5381]
### Description: 
When two different dapps tabs are open and both are connected to at least 1 account in your wallet, if the wallet is locked and you receive an accounts request from each site you may be prompted to add permissions to the second dapp site after the wallet is unlocked.

### Steps to Reproduce 
  1. Open [Uniswap](https://app.uniswap.org/) in one tab and connect at least 1 account
  2. Open [Aave](https://app.aave.com/) in another tab and connect at least 1 account
  3. Quit the app, relaunch (might not required after #5363 merges, possibly just manually lock wallet)
  4. Open Uniswap tab and swipe away the web3 wallet notification
  5. Open Aave tab and tap the web3 wallet notification and unlock your wallet
  6. Visit Uniswap tab and tap wallet icon in URL bar
  7. Bug: prompted to add permissions to Uniswap which was previously granted permissions
  8. Cancel / dismiss permissions modal and reload the page. Verify access still granted to Uniswap.

Additional steps to reproduce similar & related issue:
  1. Open [Uniswap](https://app.uniswap.org/) in one tab and connect at least 1 account
  2. Quit the app, relaunch
  3. Open Uniswap tab and swipe away the web3 wallet notification
  4. Open main wallet from 3-dot menu, unlock your wallet and close the wallet modal
  5. Bug: Uniswap does not show the connected account

**Actual result:** 
Modal appears showing Uniswap is requesting account permissions but has already been granted permissions:

https://user-images.githubusercontent.com/5314553/170346642-ce3eb8c7-e796-4b09-b1ad-9953a0f9e086.mov

Additional steps to reproduce similar & related issue:

https://user-images.githubusercontent.com/5314553/170557626-8d8fea3e-ece6-4bff-83ae-63b2c53b7878.mov

**Expected result:**
Uniswap shows as connected

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ (iOS 14.8.1) running 1.40 (22.6.27.15)
- Verified steps from [#5396](https://github.com/brave/brave-ios/pull/5396)
- Verified if account is already granted permission to Dapp, reloading the Dapp page doesn't prompt to connect again
- Verified if account is already granted permission to Dapp, unlocking the wallet and loading the Dapp page automatically shows the account on Dapp

-----------
Verification passed on iPhone XR  (iOS 15.4.1) running 1.40 (22.6.27.15)
- Verified steps from [#5396](https://github.com/brave/brave-ios/pull/5396)
- Verified if account is already granted permission to Dapp, reloading the Dapp page doesn't prompt to connect again
- Verified if account is already granted permission to Dapp, unlocking the wallet and loading the Dapp page automatically shows the account on Dapp

------------
Verification passed on iPad Pro (iOS 15.6 Beta) running 1.40 (22.6.27.15)
- Verified steps from [#5396](https://github.com/brave/brave-ios/pull/5396)
- Verified if account is already granted permission to Dapp, reloading the Dapp page doesn't prompt to connect again
- Verified if account is already granted permission to Dapp, unlocking the wallet and loading the Dapp page automatically shows the account on Dapp
