### ISSUE TITLE
Dapps: Incorrect selected account provided when selected account is not the first

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5384]
### Description: 
When connecting to a dapp site for the first time, if the currently selected account is not the first account and multiple accounts are given approval to connect to the dapp site then the first account will be used instead of the second account

### Steps to Reproduce 
 
  1. Open [MetaMask test dapp site](https://metamask.github.io/test-dapp/).
  2. Tap Wallet button in URL bar
  3. In the wallet panel, tap the selected account blockie and change to any account *except* your first account
  4. Close wallet panel
  5. Tap 'Connect' on MetaMask test dapp site
  6. Connect all your accounts (first account and selected account must be give approval). Take note of your first account address, and selected account address.
  7. Notice the `Accounts` list on MetaMask displays the first account, not the selected account

**Actual result:** 
First account is given / shown on dapp site, not the selected account which was also given approval

https://user-images.githubusercontent.com/5314553/170368484-b8c974e5-30eb-4073-85a1-b451c01f6ded.mov

**Expected result:**
Selected account is given / shown on dapp site

**Reproduces how often:** 
Easily reproduced

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ (iOS 14.8.1) running 1.40 (22.6.27.15)
- Verified steps from issue description
- Verified account selected in panel is detected on Dapp when multiple accounts are linked
------------
Verification passed on iPhone XR (iOS 15.4.1) running 1.40 (22.6.27.15)
- Verified steps from issue description
- Verified account selected in panel is detected on Dapp when multiple accounts are linked
------------
Verification passed on iPad Pro  (iOS 15. Beta) running 1.40 (22.6.27.15)
- Verified steps from issue description
- Verified account selected in panel is detected on Dapp when multiple accounts are linked
