### ISSUE TITLE
Page zoom settings menu icon design grayed out in dark mode

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#5389]
### Description: 
Page Zoom settings menu icon looks different than the rest. The Icon design does not contain the white outline and needs to be updated to match the other menus.

**Actual result:** 
![IMG_3008](https://user-images.githubusercontent.com/17885425/170401909-c75ed84c-16c8-4292-9f2b-7adb11376fb1.PNG)

**Expected result:**
Update icon design to match the rest

**Brave Version:** 
1.39 (22.5.24.16)

**Device details:** 
iPhone 12 Pro 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
Actually fixed this already in #5380

**Comment by iccub** [comment]
Too late for 1.39 work @kylehickinson, we may cherry pick this fix alone though

**Comment by Uni-verse** [comment]
Verified using 1.39 (22.5.26.19)

Test Devices: 
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad | 15.4

- Confirmed Icon isnt grayed out while in dark mode 

STR:
1. Clean install 
2. Open Settings > Appearance > Theme > Dark
3. Find the Page Zoom menu @ Settings > Page Zoom
4. Observe Page Zoom Icon

After (iPad) | After (iPhone) | Before
-|-|-
![IMG_0343](https://user-images.githubusercontent.com/17885425/170601255-ce9edda1-1fe8-432a-8b77-ff85b4025393.PNG) | ![IMG_3034](https://user-images.githubusercontent.com/17885425/170601433-b3c3c67e-3976-49c1-bbe0-dcdff2a221c5.PNG) | ![IMG_3008](https://user-images.githubusercontent.com/17885425/170603118-97ba28bd-a16c-43e4-97c9-f5156fb5af58.PNG)
