### ISSUE TITLE
Disable/enable shields results in different blocked count each time

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#539]
### Description: 
Disable/enable shields results in different blocked count each time

### Steps to Reproduce 
  1. Visit https://neowin.net
  2. Toggle shields on/off, observe the blocked item count
  3. Repeat step 2 few more times, each time the block count is different

**Actual result:** 
https://drive.google.com/open?id=1ZA3BiirAowi4ntKye_K9uEsyZRFn1YMU

**Expected result:**
Blocked count should be consistent irrespective of how many times its toggled

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.11.30.3)

**Device details:** 
iPhone 7+ (iOS 12.1)
iPad (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by tildelowengrimm** [comment]
Doesn't this depend on the assumption that the same number of scripts are in fact being blocked every time you reload?

**Comment by srirambv** [comment]
Yes it should be the same number everytime. May be a lesser count is still valid considering a script might be missed or not loaded but over count is not correct. Since there is no way to see what scripts are being blocked its impossible to say whats going on. Subsequent reloads might be blocking a legitimate script from running

**Comment by jhreis** [comment]
I don't think this is necessary an issue. Websites are hyper dynamic, and could be loading scripts based on all sorts of random behaviors. I would suspect this behavior is expected, especially since websites often attempt to continually load scripts or ads over time, leaving a news page up for 1 minute vs 30 seconds will often have wildly different block counts.

**Comment by tildelowengrimm** [comment]
I'm with Joel — I attribute this inconsistency to the site trying to load a different combination of scripts on different reloads.
