### ISSUE TITLE
Sync QR code updates

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5391]
See https://github.com/brave/brave-browser/issues/22420 counterpart

**Comment by Uni-verse** [comment]
Verification completed using version `1.40 (22.6.21.16)`

Devices: iPhone 12 | iOS 15.4, iPhone X | iOS 14.4.2 | iPad (7th Gen) | iOS 15.5

Creating Chain

- Confirmed user is able to start a new sync chain on device.
- Confirmed QR Code contains the brave logo and rounded dots.

Joining Chain

- Confirmed able to join sync chain by scanning QR code that contains brave logo and rounded dots.
- After joining sync chain, Add New Device will display QR code with brave logo and rounded dots.
- Able to join sync chain created on desktop by scanning.
- Able to add other mobile devices to sync chain by scanning generated QR code.
- Able to join sync chain by scanning/entering words from older apps (use old QR code)

Share link QR

- Confirmed able to scan new QR code generated on desktop and successfully open link.
- Confirmed able to scan QR code from older apps and open link.

Upgraded Profile

- Installed app version 1.39.x, started sync chain and confirmed QR code is original
- Updated app to version 1.40.x and confirmed the QR code has updated and contains the brave logo and rounded dots in the corners.  

Example | Example
-|-
![IMG_3118](https://user-images.githubusercontent.com/17885425/174910779-f83a36dc-0667-4c2e-9967-401c5c57fc44.PNG) | ![IMG_0377](https://user-images.githubusercontent.com/17885425/174910798-d91e6b24-d8fe-404d-85eb-168c5a5ffd63.PNG)
