### ISSUE TITLE
Privacy Hub notification does nothing when app is not loaded in memory

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5394]
STR:

1. Install app, enable notification from the privacy hub
2. Close the app and remove it from app switcher.
3. Wait until the notification is delivered
4. Tap on the notification

Result: It opens the app, but not privacy hub

Note for testers:
This is easier to test on dev builds, notification there is shown after 5 minutes of enabling it, opposed to 'every sunday at 11 AM' in prod builds

**Comment by Uni-verse** [comment]
Verified using 1.39 (22.5.26.19)

Test Devices:
iPhone 12 Pro | iOS 15.4
iPhone X | iOS 14.4.2
iPad | iOS 15.4

Using STR from https://github.com/brave/brave-ios/issues/5394#issue-1249537699

- Confirmed Privacy Hub is loaded when tapping on the Privacy Report Notification.
