### ISSUE TITLE
DAU ping overcount returned users

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5397]
See this thread for more info

**Comment by Uni-verse** [comment]
Verified for version `1.39.0` on `release` channel for iOS.

- Verified with stats team that we are receiving usage pings for `1.39` on` release` channel. A total of `11` records from `June 1 - 2, 2022`

Below is the information captured. 
{
   "_id":"ObjectId(""6298eeddc5816da72564cacc"")",
   "platform":"ios",
   "channel":"release",
   "version":"1.39.0",
   "daily":true,
   "weekly":true,
   "monthly":true,
   "first":true,
   "ads_enabled":false,
   "virtual_machine":false,
   "woi":"2022-05-29",
   "ref":"none",
   "country_code":"US",
   "region":"WA",
   "dtoi":"2022-06-02",
   "walletActive":0,
   "walletActive2":0,
   "ts":NumberLong(1654189789),
   "year_month_day":"2022-06-02",
   "braveDataCenter":false,
   "braveAPIKeyStatus":"matched"
}
