### ISSUE TITLE
Display origin w/ bolded eTLD+1 on transaction confirmations

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5405]
### Description: 
We should use the OriginInfo property on a transaction to display the origin w/ bolded eTLD+1 on the transaction confirmation view

<img width="316" alt="Screen Shot 2022-05-27 at 5 10 00 PM" src="https://user-images.githubusercontent.com/5314553/170790197-3e34f7ab-1a78-47d2-9656-5f4ec4ee5a36.png">

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

Transactions created within the wallet appear to have the URLOrigin `chrome://wallet/`. We should display 'Brave Wallet' for this case.

In some instances we may want to display the favicon, for Brave Wallet origin we should use the Brave logo:
<img width="540" alt="Screen Shot 2022-05-27 at 5 18 40 PM" src="https://user-images.githubusercontent.com/5314553/170790730-fb487afe-9f42-4f4b-b618-4d1d800cff4d.png">

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40 (22.6.24.14)
- Verified steps from [#5412](https://github.com/brave/brave-ios/pull/5412)
- Verified Origin with bolded eTLD+1 is shown on transaction confirmations

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/175988995-f96ce9b9-2be4-442d-b351-2e1e198e3a8c.png>| <img width=250 src=https://user-images.githubusercontent.com/17010094/175987661-212f74b3-9776-4fee-8811-c04f31a751ed.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/175990198-a4d7c340-1575-4295-9288-536001332ed7.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/175989017-ea4bf6c0-5b39-4fb9-a4e9-2d7f3ccc3676.png>| <img width=250 src=https://user-images.githubusercontent.com/17010094/175987688-a3fc817d-6bac-463b-a959-dc7a4a9a323c.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/175990182-8ed29331-2698-4fa9-8986-0271cebe3711.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/175988964-55bfbb0e-8a9f-4b6a-9661-e2ca0623ac79.png>| <img width=250 src=https://user-images.githubusercontent.com/17010094/175987722-4720d8f0-0907-4c25-8884-e279d0e8d10d.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/175990166-407181dc-cc39-4d01-8c4e-68d6c1fb4f3d.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/175988978-e424ec4c-f9d4-49d8-9bbe-9d594d86ad33.png>| <img width=250 src=https://user-images.githubusercontent.com/17010094/175987743-136a25ee-e44c-49fa-9cb5-6e9acbf972c0.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/175990140-bd0301aa-9e37-4378-bdc4-b5eaf1cfba06.png>
