### ISSUE TITLE
Change Coredata NSManagedObjectContexts save to background.

### ISSUE THREAD

**Issue by danishjafri88** [brave/brave-ios#541]
CoreData NSManagedObjectContexts are not used properly. Saves are done in main context in some places. 

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Related https://github.com/brave/brave-ios/issues/409

**Comment by danishjafri88** [comment]
A certain mismanaged context save causes #537

**Comment by jhreis** [comment]
Closed per: https://github.com/brave/brave-ios/pull/681
