### ISSUE TITLE
Add New Network Screen text color not inverted 

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#5413]
### Description: 
When in dark mode the text color is not inverted when adding new network/chain. 

Scenario 1: 
Adding new network (black text but should be white)

Scenario 2: 
Editing existing network (text changes from white to black when applying focus on fields)

### Steps to Reproduce 
  1. Set theme to dark mode
  2. Create brave wallet, open brave wallet
  3. Navigate to settings > networks > + 
  4. Start typing in the fields
  5. Save the network
  6. Tap on existing network 
  7. Tap on fields
  8. Observe

**Actual result:** 
![IMG_3044](https://user-images.githubusercontent.com/17885425/171308205-049f9e93-cf94-4639-aa26-aa8f7d0ff4be.PNG)

**Expected result:**
![IMG_3046](https://user-images.githubusercontent.com/17885425/171308282-96869e47-a341-4280-b6c1-59b402783204.PNG)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.39 (22.5.30.17)

**Device details:** 
iPhone 12, iPad |  iOS 15.x, 14.x

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40 (22.6.27.15)
- Verified Add new network screen text colour is not inverted in dark mode
- 
iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/175994102-3c0e17e6-1eee-470c-b8b0-9a136ee57bb4.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/175994121-81397e2d-46fc-4ea7-8232-80147d764e28.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/175994144-adc5e056-9491-4b07-9a5b-0ff157772b31.png>
