### ISSUE TITLE
DApps connect request won't trigger brave wallet onboarding flow

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5414]
### Steps to Reproduce 
  1. make sure you didn't create brave wallet on your ios brave browser
  2. go to a DApp and trigger it to request connect
      * [Uniswap](https://app.uniswap.org/) app will automatically request. 
      * [Skiff](https://app.skiff.com) will requires you click login with with brave wallet
  3. Observe the Wallet icon appears on the url bar w/o badge but no wallet notification or onboarding flow show up. User needs to manually click the wallet icon in url bar

**Actual result:** 
Wallet icon appears in URL bar without badge. No wallet notification shown.

https://user-images.githubusercontent.com/5314553/171515369-ac7b2027-c4b0-4109-b64e-d0be3caf06a4.mov

**Expected result:**

Notification is shown, wallet icon displays badge

**Comment by diracdeltas** [comment]
mentioned this in the sec review, but if the intent is to allow this without any user gesture on a page, it should be rate-limited so the site can't spam the user by opening the wallet screen over and over again.

**Comment by nuo-xu** [comment]
> mentioned this in the sec review, but if the intent is to allow this without any user gesture on a page, it should be rate-limited so the site can't spam the user by opening the wallet screen over and over again.

@diracdeltas a wallet notification will show up at the beginning for user to click in order to start the onboarding flow. 
In the wallet settings, we have an option for user to turn off the wallet notification completely. We also created a new [issue](https://github.com/brave/brave-ios/issues/5441) for wallet notification to have a swap action (could be swipe to opt-out wallet notification) for future enhancement.
