### ISSUE TITLE
'Manage website data' screen gets filled while in private mode

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5415]
### Description: 
Reported here https://community.brave.com/t/lots-of-website-data-remains-after-clearing-history-ios-15-3-15-4/365627/19

### Steps to Reproduce 
  1. Use private browsing mode
  2. Browse websites
  3. Exit private browsing mode, go to 'manage website data' screen

**Actual result:** 
Manage website data screen has entries, should be empty

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Hard to reproduce for me, our users have success in reproducing it sometimes

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by diracdeltas** [comment]
Was anyone able to repro it?

**Comment by iccub** [comment]
No, we tried for some time and no luck

**Comment by grower-rhyme** [comment]
Been meaning to report this for a while. I was going to open an issue but I think it may be related and I may know how to help you recreate it: try opening something in another tab. I have my setup set to stay in Private Browsing forever, but I've noticed that if I open something in another tab, even when I clear all tabs and close the browser sometimes there's still data there. Try going to privacyguides.org (for example) while in private mode, then click the "Start Your Privacy Journey" button and open it in a new private tab. Then go check "Manage Website Data" in the settings and you'll see Github.com and privacyguides.org both listed there. Try closing the browser, closing the tabs, whatever, it doesn't go away til you manually clear it.

If this is an unrelated issue, let me know and I'll open a new issue for it.

**Comment by iccub** [comment]
It must be the same issue @grower-rhyme, i will try reproducing it with websites you mentioned.
I tried to repro on many popular news sites etc, and never been able to persist anything

**Comment by iccub** [comment]
@grower-rhyme I think I found the issue. When you long press on a link to open in new tab do you have the 'website previews' enabled?
Looks like the preview might not be respecting the private mode. We need to disable it for this mode or see if we can harden it

**Comment by grower-rhyme** [comment]
> @grower-rhyme I think I found the issue. When you long press on a link to open in new tab do you have the 'website previews' enabled?

Correct. AFAIK that's the default behavior of Brave. In fact, I don't even see a way to disable that feature, which would be a nice temporary fix cause personally I don't need that feature (though I'm sure others would prefer it).

> Looks like the preview might not be respecting the private mode. We need to disable it for this mode or see if we can harden it

Woo! Glad I could help make Brave just a little better :)

**Comment by iccub** [comment]
@grower-rhyme just scroll down on the link you long pressed, there should be menu option at the bottom 'hide link previews'
![IMG_C1635E8F5CF5-1](https://user-images.githubusercontent.com/6950387/185997832-676ead75-905e-4747-9050-ea5b656d70b7.jpeg)

**Comment by grower-rhyme** [comment]
@iccub Just followed your instructions and can confirm no longer having data retention issues. Thanks!

**Comment by Uni-verse** [comment]
Verification in progress

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.43 (22.9.9.15)
- Verified steps from [#5415 (comment)](https://github.com/brave/brave-ios/issues/5415#issuecomment-1221618890)
- Verified no site data is listed under `Manage website data`
- Verified no data leak from private tabs
- Encountered [#5998](https://github.com/brave/brave-ios/issues/5998)
--------------
Verification passed on iPhone XR with iOS 15.6.1 running 1.43 (22.9.9.15)
- Verified steps from [#5415 (comment)](https://github.com/brave/brave-ios/issues/5415#issuecomment-1221618890)
- Verified no site data is listed under `Manage website data`
- Verified no data leak from private tabs
- Encountered [#5998](https://github.com/brave/brave-ios/issues/5998)
--------------
Verification passed on iPad Pro with iOS 16.1 running 1.43 (22.9.9.15)
- Verified steps from [#5415 (comment)](https://github.com/brave/brave-ios/issues/5415#issuecomment-1221618890)
- Verified no site data is listed under `Manage website data`
- Verified no data leak from private tabs
- Encountered [#5998](https://github.com/brave/brave-ios/issues/5998)
