### ISSUE TITLE
New/Edit Site Connection doesn't bold eTLD+1

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5423]
### Description: 
eTLD+1 should be bold on New Site Connection view and Edit Site Connection view

### Steps to Reproduce 
  1. Clear Uniswap connections from 'Manage Site Connections' in Brave Wallet settings
  2. Open [Uniswap](https://app.uniswap.org)
  3. Tap notification / wallet icon to be prompted for new site connection
  4. Observe New Site Connection.
  5. Edit site accessible by tapping 'Connect' on wallet panel after closing new site connection

**Actual result:** 

![new site connection](https://user-images.githubusercontent.com/5314553/171503631-c53ace0a-03c3-4696-a492-04c1b4e71c72.png) | ![edit site connection](https://user-images.githubusercontent.com/5314553/171503812-f9f096a5-b31d-408a-8da6-aa236ec3b36d.png)
--|--

**Expected result:**

eTLD+1 is bolded in the display. Example from transaction confirmation:

![img](https://user-images.githubusercontent.com/5314553/171280591-8a8bdf0f-5a4d-4826-91a7-5f43f4b7a9f7.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40(22.6.27.15)
- Verified New/Edit site connection detail has eTLD+1 in bold

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/175992417-d2deab27-3550-483b-9620-e8be55ce08ac.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/175992339-90a3cdd2-b155-4048-b158-eea781e40ef0.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/175992395-621ae7d0-5347-4dea-a0e4-61f6203fae7f.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/175992436-3027ba2c-709c-4573-a962-d2392e7c5c07.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/175992360-7d910ab3-042a-4001-9770-1c85f4cd67a1.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/175992382-99a98175-b02a-49dd-8365-14f82b6b0eb5.png>
