### ISSUE TITLE
Dapp Implement Get Encryption Public Key & Decrypt Requests

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5424]
### Description: 

Need to support `GetEncryptionPublicKeyRequest` and `DecryptRequest` for web3 / dapps

### Steps to Reproduce 
for `GetEncryptionPublicKeyRequest` request
  1. Open [Metamask Test Dapp Site](https://metamask.github.io/test-dapp/) 
  2. Tap 'GET ENCRYPTION KEY'
 
for `DecryptRequest` request
  1. Open [Metamask Test Dapp Site](https://metamask.github.io/test-dapp/) 
  2. Enter message in field under 'GET ENCRYPTION KEY' button
  3. Tap 'ENCRYPT'
  4. Tap 'DECRYPT'

**Actual result:** 

Nothing happens, requests not implemented

**Expected result:**

Similar to other dapp requests, modal shown for each request

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

Desktop panels:

<img width="317" alt="get encryption public key request" src="https://user-images.githubusercontent.com/5314553/171516167-79d8e806-3158-4048-b08b-4b618a6f6aee.png"> | <img width="318" alt="decrypt request" src="https://user-images.githubusercontent.com/5314553/171516169-b7244505-d01a-43f9-9c01-fafbca8dbe54.png"> | <img width="316" alt="decrypt request - showing message" src="https://user-images.githubusercontent.com/5314553/171516176-3f65cd02-2d4f-47d4-bb37-243bc3f0a153.png">
--|--|--

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40 (22.6.25.17)
- Verified steps from [#5464](https://github.com/brave/brave-ios/pull/5464)
- Verified when a screenshot is discovered on decrypt screen warning message is shown
- Verified if a screen recording is in progress, decrypted message is not shown. Only shown after recording stops
- Verified when a screenshot is detected on private key view, warning message is shown 
- Verified if a screen recording is in progress, private key is not shown. Only shown after recording stops

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/175996770-70242180-948d-4e7d-bfde-ee98d83fe896.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/175996761-3821a117-4f14-477d-a0c8-14037e16e96c.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/175996831-a2afd0af-676e-42a4-b6b7-be483990eefa.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/175996804-9a5b3ee7-0e2e-406e-9354-dca96775ed3a.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/175996741-6b20f3fd-ca49-40a1-a553-63310e11b6cc.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/175996847-a7bda066-d7c9-49c1-a00d-e687253e7dab.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/175996816-d36cd001-63c0-48f2-9a5a-c6c3c4c63ea4.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/175996719-f95d9e0c-6e51-41b6-871c-d522997b7a04.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/175996855-c3535871-f4e4-46ea-9267-9d131f16ad29.png>
