### ISSUE TITLE
Automatically show dapp requests received while wallet panel is open

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5433]
### Steps to Reproduce 
  1. Remove web3 site connections for [app.skiff.com](https://app.skiff.com/) in wallet settings
  2. Visit [app.skiff.com](https://app.skiff.com/)
  3. Tap 'Log in with Brave Wallet'
  4. Tap wallet notification
  5. Connect a wallet account
  6. When new site connection view dismisses after connecting an account, leave panel open until wallet badge to appears on wallet button in URL bar
  7. Observe request is not automatically shown
  8. Close wallet panel and tap wallet button in URL bar
  9. Observe request received is now shown modally

**Actual result:** 

https://user-images.githubusercontent.com/5314553/171697518-7e91f5c2-b41f-4dbc-b58e-e0ed5a019630.mov

**Expected result:**

Should not have to close wallet panel and re-open to see new request. Additionally the bell icon should appear on the wallet panel.

**Reproduces how often:** 
Easily reproduced

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by nuo-xu** [comment]
can verify #5541via this ticket.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40(22.6.27.15)
- Verified steps from [#5448](https://github.com/brave/brave-ios/pull/5448)
- Verified Dapp requests are shown automatically without having to click on wallet panel 

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/176004763-cad269f3-8462-41e1-8fea-dd7773228796.MP4> | <video src=https://user-images.githubusercontent.com/17010094/176004789-b7ba14ec-846c-4302-a594-2d400940af33.MP4> | <video src=https://user-images.githubusercontent.com/17010094/176004822-1f572989-aeba-414a-bc93-93ff5b1ae174.MP4>
