### ISSUE TITLE
Block scripts increases count when all tabs are loaded

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#544]
### Description: 
Block scripts increases count when all tabs are loaded

### Steps to Reproduce 
  1. Load all QA tabs, wait till all tabs are loaded
  2. Enable block script from settings
  3. Open a new tab, scripts blocked count increases even though all tabs are already loaded

**Actual result:** 
https://drive.google.com/open?id=1g_KoJhfKl7Sh4ogWUfyOJkX6c7q1g41x

**Expected result:**
Should only increase count after visiting a site post script blocking

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.11.30.3)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
When block script is enabled from settings, all open tabs are reloaded hence the count increases on newtab. Not sure if this is expected behaviour? On desktop global settings changes doesn't affect already open tabs unless they are reloaded. Setting change doesn't trigger page reload on opened tabs

cc: @jhreis

**Comment by jhreis** [comment]
This is expected behavior. Background tabs may continue loading resources or ads even when the user is not on that page, and these should be counted.
