### ISSUE TITLE
Deleting tab from tab search result seems to clear the query to display full tabs

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5447]
## Steps to Reproduce 
  1. Open few tabs (make sure you have some duplicated tabs e.x www.brave.com)
  2. search `brave` 
  3. it should display all the tabs that has domain include the key words
  4. delete one of the search result tabs

**Actual result:** 
I should see n -1 amount of tabs that i have searched

**Expected result:**
all the tabs

**Comment by Uni-verse** [comment]
Verified using `1.40 (22.6.21.16)`

Test Devices:
iPhone 12 | iOS 15.4
iPhone X | iOS 14.4.2
iPad | iOS 15.5

- Verified deleting tab from tab search results doesn't clear the query and all tabs that match search term are displayed.
- Verified clearing search without issues displaying the tabs
- Verified tab search functionality on normal and private tabs

Searching for "brave" | After deleting one of the search result tabs
-|-
![IMG_3116](https://user-images.githubusercontent.com/17885425/174874031-acd5f71a-4315-4290-b8f8-9c5f246b9adf.PNG) | ![IMG_3117](https://user-images.githubusercontent.com/17885425/174874043-e8154384-9dc0-40db-baf3-c87a59eb17fe.PNG)

![IMG_0375](https://user-images.githubusercontent.com/17885425/174874368-568f658c-b58a-408f-a147-a03c532a0257.PNG)
