### ISSUE TITLE
Favourites retain clicked state when a new tab is quickly opened

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#545]
### Description: 
Favourites retain clicked state when a new tab is quickly opened

### Steps to Reproduce 
  1. Tap on a favourite
  2. Before page loads tap on a new tab
  3. Favourite from step 1 looks pressed on new tab until its tapped again or app is relaunched

**Actual result:** 
Favourites retain clicked state when a new tab is quickly opened

**Expected result:**
Should not retain clicked state on new tab

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.11.30.3)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Invalid per https://github.com/brave/brave-ios/issues/2578
