### ISSUE TITLE
Transaction confirmation does not dismiss when last transaction is confirmed

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5450]
### Description: 

When viewing a transaction via the Wallet Panel (typically from a dapp request) and viewing the only/last request, the reject button correctly dismisses the modal confirmation view but the confirm button usually does not.

### Steps to Reproduce 
  1. Open [Uniswap](https://app.uniswap.org/) and connect an account
  2. Choose a 'to' token
  3. Enter a value to swap
  4. Tap 'Swap'
  5. Tap 'Confirm Swap'
  6. Tap Wallet notification
  7. Tap 'Confirm'
  8. Observe view updates to show 'no transaction' state but does not dismiss.
  9. Same flow but tapping confirm seems to always dismiss correctly

**Actual result:**

https://user-images.githubusercontent.com/5314553/172192781-e64e306c-01ea-4b19-b7ec-62391f4bf694.mov

**Expected result:**

'Confirm' button dismisses the same as 'Reject'

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

`TransactionConfirmationView` is checking if the `confirmationStore.transactions.count == 1`. It's likely that the transaction is removed prior to the completion block being called, so the transaction count is 0 and the view does not dismiss

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40 (22.6.27.15)
- Verified steps from issue description
- Verified confirming a transaction auto-dismisses the transaction confirmation screen


iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/176142000-4aa1e08d-46df-4201-a65a-1ab8ab82bd9a.MP4> | <video src=https://user-images.githubusercontent.com/17010094/176142042-949d82ca-b1f6-4712-a067-41fe83219479.MP4> | <video src=https://user-images.githubusercontent.com/17010094/176142061-83200cbd-6562-48b5-8dc3-1f6c8fe46ad5.MP4>
