### ISSUE TITLE
Reset Wallet needs to wipe out DApps permissions and other wallet preferences

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5458]
Once user decides to reset wallet, we need to clear existed DApps preferences and all other wallet preferences.

**Comment by Akrson** [comment]
No

**Comment by Dndptvvxcn** [comment]
My phone broke think some one has hacked it 


Sent from Yahoo Mail for iPhone


On Tuesday, June 7, 2022, 7:21 pm, Nuo Xu ***@***.***> wrote:




Once user decides to reset wallet, we need to clear existed DApps permissions and all other wallet preferences.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.40 (22.6.27.15)
- Verified steps from [#5478](https://github.com/brave/brave-ios/pull/5478)
- Verified reset wallet wipes out Dapp permissions and other wallet preferences
- Encountered [#5604](https://github.com/brave/brave-ios/issues/5604)
---------
Verification passed on iPhone XR with iOS 15.4.1 running 1.40 (22.6.27.15)
- Verified steps from [#5478](https://github.com/brave/brave-ios/pull/5478)
- Verified reset wallet wipes out Dapp permissions and other wallet preferences
---------
Verification passed on iPad Pro with iOS 15.6 Beta running 1.40 (22.6.27.15)
- Verified steps from [#5478](https://github.com/brave/brave-ios/pull/5478)
- Verified reset wallet wipes out Dapp permissions and other wallet preferences
