### ISSUE TITLE
Infinite redirect loop between amp page and non-amp page

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#5461]
### Description: 
Infinite redirect on the following urls 
* https://digiday.com/marketing/googles-david-temkin-sheds-light-on-the-companys-preparations-for-disabling-third-party-cookies/amp/
* https://thehustle.co/06022022-elvis-vegas-weddings
* https://t.co/0Ydr4haUQd 

https://user-images.githubusercontent.com/909331/172476022-8bc811d4-16d0-4a44-9395-9f0d565e3aa9.MP4

### Steps to Reproduce 
  1. Enable de-amping
  2. Navigate to the url above

**Actual result:** 
Infinite load loop between amp and non-amp page

**Expected result:**
Should load the page without an infinite redirect (in this case, amp should fail and load the amp page)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.39

**Device details:** 
N/A

**Website problems only:**
- did you check with Brave Shields down?
no issue with brave shields down because its caused by enabling brave shields. But this is still a de-amp issue.
- did you check in Safari/Firefox (WkWebView-based browsers)? 
Yes. Only an iOS issue

### Additional Information
This is caused by a battle between de-amping forcing a non-amp page and the server hosting the website forcing the amp page.

**Comment by Uni-verse** [comment]
Verified PASSED using `1.39.1 (22.6.10.17)`

Devices Tested on: 
iPhone 12 | iOS 15.4
iPad | iOS 15.5
iPhone X iOS 14.4.2

- Went through the STR/Test plan on https://github.com/brave/brave-ios/issues/5461#issue-1263826903 and verified URLs are loading with De-AMP enabled.
- Ensured navigating back and forth does not cause loading loop

iPhone | iPad
-|-
![IMG_3095](https://user-images.githubusercontent.com/17885425/173423876-77c7aa99-f01d-4d0a-a2f4-ea4240a91876.PNG) | ![IMG_0372](https://user-images.githubusercontent.com/17885425/173423867-ac393a37-bd3e-4a2c-988c-a94eccfc63ab.PNG)
