### ISSUE TITLE
Add Ramp.network & Sardine on iOS

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#5465]
Providers:
1. Ramp.Network
2. Sardine
3. Wyre
Note: Testnets do not support in Buy

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.45 (22.10.25.19)
- Verified test plan from [#6201](https://github.com/brave/brave-ios/pull/6201)
- Verified different providers are shown before purchasing 
- Verified `Ramp.network`, `Sardine` & `Wyre` providers are shown depending on which is supported
- Verified `Sardine` is only shown when locale is set to US
- Verified `fixed_network=<networkname>` appended to the URL so user can't change the token on 

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.6.1) | iPad Pro (iOS 16.1)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/198086695-8d42d188-0ff8-4e48-87b3-d18c41e0970e.mp4> | <video src=https://user-images.githubusercontent.com/17010094/198085856-4c5cb803-e8fe-4699-a507-ae125206882c.mp4> | <video src=https://user-images.githubusercontent.com/17010094/198090574-ed9925f3-117e-40fd-a460-65abc0106ae5.mp4>
