### ISSUE TITLE
Blockie colours don't match other platforms

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#5472]
### Description: 

The colours used for blocks don't match when the addresses are the same between desktop and iOS

**Comment by srirambv** [comment]
Verification passed on following devices  running 1.40 (22.6.27.15)
- Verified blockie colours match desktop
- Encountered [#5610](https://github.com/brave/brave-ios/issues/5610)

Desktop | iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta)
-- | -- | -- | --
<img width=400 src=https://user-images.githubusercontent.com/17010094/176099629-0a383dd6-b9e7-4731-94cd-550193582439.png> |  <img width=300 src=https://user-images.githubusercontent.com/17010094/176132610-ca0b9157-641d-48d2-9c7f-e46eb5164db8.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/176132736-ad0dd419-b668-4c61-acdd-f45f18358a1f.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/176132649-4d28a299-bd0f-49b1-be4c-2a81b6a293bb.png>
