### ISSUE TITLE
Add context menu to truncate account address so that users can reveal full address

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5477]
Add context menu to truncated account address so that users can 
- reveal full address
- tap to copy full address

![Simulator Screen Shot - iPhone 13 Pro - 2022-06-08 at 13 07 42](https://user-images.githubusercontent.com/1187676/172863192-6ce1e6fa-f877-4823-9b2d-3aac7771b7f1.png)
![Simulator Screen Shot - iPhone 13 Pro - 2022-06-08 at 13 10 48](https://user-images.githubusercontent.com/1187676/172863320-8590567f-7d97-4e79-b5ea-ccd4ccce1b4b.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40 (22.6.22.18)
- Verified account full address is shown on long press

<table>
   <tr>
      <th>
      </th>
      <th>:ballot_box_with_check: iPhone 7+ (iOS 14.8.1)</th>
      <th>:ballot_box_with_check: iPhone XR (iOS 15.4.1)</th>
      <th>:ballot_box_with_check: iPad Pro (iOS 15.6 Beta)</th>
   </tr>
   <tr>
      <td>Buy/Send/Swap 
      </td>
      <td><img width=300 src=https://user-images.githubusercontent.com/17010094/175273818-30d315b3-9c0f-4097-82c4-78fdeab875d5.png>
      </td>
      <td><img width=250 src=https://user-images.githubusercontent.com/17010094/175272581-bcac8d4f-c3a1-48cb-9e3b-3212d23da8cf.png>
      </td>
      <td><img width=500 src=https://user-images.githubusercontent.com/17010094/175273068-6e0d5ae4-662a-458d-aa13-f282b9785018.png>
      </td>
   </tr>
   <tr>
      <td>Account on Portfolio
      </td>
      <td><img width=300 src=https://user-images.githubusercontent.com/17010094/175272766-534d5031-98d3-4ca8-8b9b-9ef9fd5b7f72.png>
      </td>
      <td><img width=250 src=https://user-images.githubusercontent.com/17010094/175272602-66bb4236-d936-4765-9ce6-df1771f2afd6.png>
      </td>
      <td><img width=500 src=https://user-images.githubusercontent.com/17010094/175273008-fe4f2a48-df74-42a0-9d62-067158f62f70.png>
      </td>
   </tr>
   <tr>
      <td>Select account 
      </td>
      <td><img width=300 src=https://user-images.githubusercontent.com/17010094/175272890-68117a63-880d-4153-9870-52ac8b14be0b.png>
      </td>
      <td><img width=250 src=https://user-images.githubusercontent.com/17010094/175272635-4b60ef45-9db4-4fed-9a76-a632916dc50a.png>
      </td>
      <td><img width=500 src=https://user-images.githubusercontent.com/17010094/175272975-565b5107-1f55-4d8f-97ab-7420f2229aaf.png>
      </td>
   </tr>
   <tr>
      <td>Wallet Panel
      </td>
      <td><img width=300 src=https://user-images.githubusercontent.com/17010094/175272853-e78ccfac-5b90-4f76-b1be-49d2465cc7ad.png>
      </td>
      <td><img width=250 src=https://user-images.githubusercontent.com/17010094/175272671-98960b55-5e6f-4e27-a1af-0a60bb3c9350.png>
      </td>
      <td><img width=500 src=https://user-images.githubusercontent.com/17010094/175272949-23006513-fb15-4b17-927c-4fb7108815a1.png>
      </td>
   </tr>
</table>
