### ISSUE TITLE
Changing from dapp to a new site may continue to show wallet icon

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5483]
### Description: 

Wallet url bar button shows in url bar after changing to a new url 

### Steps to Reproduce 
  1. Visit a dapp site and perform some wallet interaction to show the wallet icon in the url bar
  2. Change URL to brave.com which does not have wallet integration
  3. Observe wallet icon in URL bar until next layout pass (clicking wallet button will remove it)

**Actual result:** 

https://user-images.githubusercontent.com/5314553/172897290-08140c65-35b1-4794-9cfd-34fd01e4954f.mp4

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40 (22.6.21.16)
- Verified steps from issue description
- Verified navigating away from Dapp to a normal page hides the wallet button instantly as the page is loaded

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/175012508-4405ca31-0e61-4b19-8732-9d44ce23baf5.MP4> | <video src=https://user-images.githubusercontent.com/17010094/175009163-84731ec4-767f-4397-b7e3-f851bf65933b.MP4> | <video src=https://user-images.githubusercontent.com/17010094/175012947-4b12682f-10bf-475c-b603-b1e903b9c1b3.MP4>
