### ISSUE TITLE
Lock icon on Dapp interaction toast message needs proper adjustment

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5500]
### Description: 
Lock icon on Dapp interaction toast message needs proper adjustment

### Steps to Reproduce 
  1. Install 1.40 build on iPhone XR
  2. Visit a Dapp to trigger the notification
  3. See the squished version of the lock icon on the toast message

**Actual result:** 
<img width=300 src=https://user-images.githubusercontent.com/17010094/173110369-5b3b9aef-3e3b-4f9b-abff-8bfde2cbb5ae.png>

**Expected result:**

iPhone 7+ (iOS 14.8.1) | iPad Pro (iOS 15.6 Beta)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/173110466-b444072e-7bd8-4d7f-bc45-28c18e311dda.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/173110696-6a8bf9b9-861c-49dc-acb3-984056cc0fed.png>

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.40 (22.6.9.16)

**Device details:** 
iPhone XR (iOS 15.3)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by srirambv** [comment]
@StephenHeaps the icon seems to be too small now. Is this ok? 
![image](https://user-images.githubusercontent.com/17010094/175005358-1e92a5c3-14cc-49e9-bcba-cf26348c6b05.png)

**Comment by StephenHeaps** [comment]
This seems like a bug. It doesn't occur every time, and changing the dynamic text size seems to resolve it to the expected size. Will re-open and take a look.

https://user-images.githubusercontent.com/5314553/175038888-efa0e797-26d2-4d07-bd21-29a7e8f4fefb.mp4

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.4.1 running 1.40 (22.6.27.15)
- Verified lock icon on Dapp notification looks properly scaled
![image](https://user-images.githubusercontent.com/17010094/176002999-dfa4460d-aa75-48f7-8698-5b41e1a9b3ca.png)
