### ISSUE TITLE
Wallet icon is still retained when switching tabs

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5501]
### Description: 
Wallet icon is still retained when switching tabs 

### Steps to Reproduce 
  1. Visit a Dapp and trigger wallet connect
  2. Open and close the panel
  3. Open coingecko in a second tab and try to add a token (fails)
  4. Switch back to tab 1 from step 1 so wallet icon is shown in URL
  5. Swipe to coingecko tab, wallet icon is shown
  6. Click the wallet button, hides the button

**Actual result:** 

https://user-images.githubusercontent.com/17010094/173112063-da9a43be-6fa7-49ce-9095-66a44948c267.MP4

**Expected result:**
Should not show wallet button if there is no Dapp interaction

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.40 (22.6.9.16)

**Device details:** 
iPhone XR (iOS 15.3)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
Note: Only repro's on iPhone XR not on other devices
cc: @nuo-xu @StephenHeaps

**Comment by StephenHeaps** [comment]
Handled in https://github.com/brave/brave-ios/pull/5516

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.4.1 running 1.40(22.6.21.16) Dev build
- Verified steps from issue description
- Verified switching tabs automatically hides the wallet button
