### ISSUE TITLE
Update brand logo for Ecosia

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#5504]
### Description: 
Per https://bravesoftware.slack.com/archives/C015G1THCAJ/p1654884889038839

Please update the brand logo for Ecosia

![New Ecosia logo 6 22](https://user-images.githubusercontent.com/7606853/173131026-1491a2fa-f4c9-443d-99ad-d4c471d8f539.png)

**Comment by Uni-verse** [comment]
Verified using 1.40.1 (22.7.5.21)

Test Devices:
iPhone 12 Pro | iOS 15.5
iPhone X | iOS 14.4.2
iPad (7th Gen) | iOS 15.5

- Verified brand logo for `Ecosia` in the brave app UI matches the specs
- Verified brand logo under `Quick-Search Engines`
- Verified brand logo in `History` and `Bookmarks` Tabs
- Verified Ecosia brand `favicon` in `favorites`
- Verified logo appears correctly when using search, `search suggestions`
- Verified brand logo is updated in private mode

<hr>

History | Favorites favicon | New bookmark | Existing bookmarks | Using Search | Search settings
-|-|-|-|-|-
![IMG_3218](https://user-images.githubusercontent.com/17885425/177634128-bf08ed8a-3e09-4351-9f99-8e41c9fb6631.PNG) | ![IMG_3220](https://user-images.githubusercontent.com/17885425/177634137-98a5c2ba-5148-4d7d-a433-4b7f8506d7b1.PNG) | ![IMG_3221](https://user-images.githubusercontent.com/17885425/177634147-8b10bbac-f4d7-4ad0-8273-da67b34c12be.PNG) | ![IMG_3222](https://user-images.githubusercontent.com/17885425/177634148-654dfbad-8afa-4bcf-8a33-5b336059caa4.PNG) | ![IMG_3216](https://user-images.githubusercontent.com/17885425/177634184-6cb81c30-015f-4697-b8d9-3cf7c58b473d.PNG) | ![IMG_3217](https://user-images.githubusercontent.com/17885425/177634198-00d4b16e-d771-427a-9510-d7adb64df93c.PNG)

<hr>

Default Search Engine | Searching | History | New bookmark | Favorites | Existing bookmarks
-|-|-|-|-|-
![IMG_0423](https://user-images.githubusercontent.com/17885425/177640364-33660f5c-34d0-4176-993d-5a547862286d.PNG) | ![IMG_0424](https://user-images.githubusercontent.com/17885425/177640387-2a9bd5ce-cd92-4490-99f2-efb8aaeab6a8.PNG) | ![IMG_0425](https://user-images.githubusercontent.com/17885425/177640388-cddb53e6-6c39-49b2-8052-239fa9dcc48c.PNG) | ![IMG_0426](https://user-images.githubusercontent.com/17885425/177640392-250288d0-b1ad-4aac-bdfe-bfda7fcea099.PNG) | ![IMG_0427](https://user-images.githubusercontent.com/17885425/177640396-ecdbfddc-b59d-4185-b96f-2c4afc022a8c.PNG) | ![IMG_0428](https://user-images.githubusercontent.com/17885425/177640399-3d1ca334-5c32-4ee2-8a35-909284b93b32.PNG)
