### ISSUE TITLE
White screen on restored tabs is back

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5508]
Possibly a regression

**Comment by Uni-verse** [comment]
Verified using `1.40 (22.6.29.0)`

Test Devices: 
iPhone 12 Pro | iOS 15.5
iPhone X | iOS 14.4.2
iPad (7th Gen) | iPadOS 15.5

- Ensured white screen doesn't show up on restored tabs. 
- Ensured restored tabs don't show as white screen after updating app.

Mobile | iPad | version
-|-|-
![IMG_3174](https://user-images.githubusercontent.com/17885425/176556109-b32c5794-86fc-4ea4-a4bc-c1f07f49544e.PNG) | ![IMG_0416](https://user-images.githubusercontent.com/17885425/176556104-7f527440-9ad1-4cf3-ab3a-c118d2e08204.PNG) | ![IMG_0415](https://user-images.githubusercontent.com/17885425/176556092-2cbd4279-6404-4932-9bfc-3cca2e4f1bc0.PNG)
