### ISSUE TITLE
External links should request user confirmation

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#551]
### Description: 
Third party apps can be opened from Brave without user confirmation 

### Steps to Reproduce 
  1. Navigate to mailto://abc@abc.com
  
**Actual result:** 
Mail opens

**Expected result:**
Request user confirmation before opening external apps.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Everytime

**Brave Version:** 
1.7 (18.11.30.03)

**Device details:** 
iPhone SE/iOS 12.1

**Comment by kylehickinson** [comment]
Should a popup be brought up for any non web URL scheme or just non-first-party Apple app schemes?

**Comment by tildelowengrimm** [comment]
Any scheme which will open an app other than Brave.

**Comment by kylehickinson** [comment]
Port copy from 1.6, however also need to have this alert come up for all apps not just third-party: https://github.com/brave/browser-ios/blob/development/Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift#L191

**Comment by jumde** [comment]
One more test case: 

1. Install appear.in from app store
2. Navigate to appear.in/brr
3. Click `Open in App` - No user confirmation is needed

**Comment by kjozwiak** [comment]
Example of the modal notification:

<img width="433" alt="Screen Shot 2019-11-22 at 11 27 01 AM" src="https://user-images.githubusercontent.com/2602313/69442699-0b1dc580-0d1b-11ea-8593-08ad40d3b1aa.png">

Verification **PASSED** on `iPhone 6s` running `iOS 13.2.2` using `1.14 (19.11.22.15)`
* ensured that navigating to `mailto://abc@abc.com` displayed the above modal
* ensured that selecting `Don't Allow` doesn't load `Mail`
* ensured that selecting `Allow` correctly opens the `Mail` application
* went through https://github.com/brave/brave-ios/issues/551#issuecomment-455807313 and ensured the above modal wasn't being displayed

Verification **PASSED** on `iPhone 6s+` running `iOS 12.4.1` using `1.14 (19.11.22.15)`
* ensured that navigating to `mailto://abc@abc.com` displayed the above modal
* ensured that selecting `Don't Allow` doesn't load `Mail`
* ensured that selecting `Allow` correctly opens the `Mail` application
* went through https://github.com/brave/brave-ios/issues/551#issuecomment-455807313 and ensured the above modal wasn't being displayed

Verification **PASSED** on `iPad Air 3rd Gen` running `iOS 13.3` using `1.14 (19.11.22.15)`
* ensured that navigating to `mailto://abc@abc.com` displayed the above modal
* ensured that selecting `Don't Allow` doesn't load `Mail`
* ensured that selecting `Allow` correctly opens the `Mail` application
* went through https://github.com/brave/brave-ios/issues/551#issuecomment-455807313 and ensured the above modal wasn't being displayed

Verification **PASSED** on `iPad Mini 4` running `iOS 12.4.1` using `1.14 (19.11.22.15)`
* ensured that navigating to `mailto://abc@abc.com` displayed the above modal
* ensured that selecting `Don't Allow` doesn't load `Mail`
* ensured that selecting `Allow` correctly opens the `Mail` application
* went through https://github.com/brave/brave-ios/issues/551#issuecomment-455807313 and ensured the above modal wasn't being displayed

**Comment by anthonypkeane** [comment]
If the users presses Don't allow, what happens @kylehickinson 

Will the user be prompted again next time they visit that site and perform the same action?

**Comment by kylehickinson** [comment]
@anthonypkeane They will continue to be prompted each time

**Comment by jumde** [comment]
@kylehickinson - can we use AlertPopupView instead of the regular modal. It seems phishable. I can open a follow up issue for that

**Comment by kylehickinson** [comment]
I mean, we could, however webpage alerts title's are always their origins as seen here: 

https://github.com/brave/brave-ios/blob/89149ed8d362506e00a907cf0d9e09ce59672d9a/Client/Frontend/Browser/BrowserPrompts.swift#L138-L144

**Comment by srirambv** [comment]
@jumde  we can add a new issue and mark it for next release unless its a high priority for the current one

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.22.15)
* Verified visiting `mailto://abc@abc.com` shows the confirmation message
![image](https://user-images.githubusercontent.com/17010094/69572268-c6e82a80-0f91-11ea-9837-404384eb7806.png)
* Verified clicking Allow swithces to Mail app and opens an email with the email abc@abc.com 
* Verified clicking Don't Allow doesn't load the Mail app
* Verified test plan from https://github.com/brave/brave-ios/issues/551#issuecomment-455807313

**Comment by kjozwiak** [comment]
> If the users presses Don't allow, what happens @kylehickinson

As per @kylehickinson via https://github.com/brave/brave-ios/issues/551#issuecomment-558283010, the modal goes away and the user is prompted again. Also went through those cases via https://github.com/brave/brave-ios/issues/551#issuecomment-558280003.

@jumde as per https://github.com/brave/brave-ios/issues/551#issuecomment-558301978, is this something we need to fix in this version or can it moved into the next release? We'll need to know ASAP so someone can start working on it. Can you create a new issue or would you like QA to do it?

**Comment by kjozwiak** [comment]
Talked to @jumde who mentioned using `AlertPopupView` instead of a regular modal isn't urgent and can be addressed in the next version. Created https://github.com/brave/brave-ios/issues/2039 as a follow up and added it into https://github.com/brave/brave-ios/milestone/33.
