### ISSUE TITLE
Wallet: Only inject wallet provider in a secure context

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5518]
Ref: Desktop/Android PR https://github.com/brave/brave-core/pull/13739
Ref: https://github.com/brave/security/issues/887#issuecomment-1154447929

We want to inject wallet provider to a page that is secure and only have secure content.

**Comment by StephenHeaps** [comment]
Re-opening to handle treating a page that has loaded mixed-content as insecure and rejecting dapp requests.

ref: https://github.com/brave/security/issues/887#issuecomment-1162409406

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.40 (22.6.24.14)
- Verified steps from [#5522](https://github.com/brave/brave-ios/pull/5522) / [#5558](https://github.com/brave/brave-ios/pull/5558)
- Verified able to connect to a Dapp which is available over secure connection
- Verified unable to trigger Dapp connection over `http`. (Used eth manual test page via proxy and couldn't trigger dapp connection notification)
-----------
Verification passed on iPhone XR with iOS 15.6 running 1.40 (22.6.24.14)
- Verified steps from [#5522](https://github.com/brave/brave-ios/pull/5522) / [#5558](https://github.com/brave/brave-ios/pull/5558)
- Verified able to connect to a Dapp which is available over secure connection
- Verified unable to trigger Dapp connection over `http`. (Used eth manual test page via proxy and couldn't trigger dapp connection notification)
-----------
Verification passed on iPad Pro with iOS 15.6 Beta running 1.40 (22.6.24.14)
- Verified steps from [#5522](https://github.com/brave/brave-ios/pull/5522) / [#5558](https://github.com/brave/brave-ios/pull/5558)
- Verified able to connect to a Dapp which is available over secure connection
- Verified unable to trigger Dapp connection over `http`. (Used eth manual test page via proxy and couldn't trigger dapp connection notification)
