### ISSUE TITLE
Handling truncated domains

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#552]
From: https://github.com/brave/browser-ios/issues/1100

## Test Plan:

1. Navigate to http://random-test-domain.paypal.com/randompath - Verify that paypal.com is focussed in the address bar
2. Navigate to http://random-test.paypal.com/randompath - Verify that `random-test.paypal.com` is focussed in the address bar

This issue was highlighted in the HindSight paper recently: https://www.securitee.org/files/hindsight_ccs2017.pdf

**Comment by tildelowengrimm** [comment]
Preferred behavior:
- right-align the TLD
- highlight the ETLD+1

**Comment by jumde** [comment]
@srirambv - added the test plan, let me know if you have any questions. cc: @danishjafri88

**Comment by srirambv** [comment]
Verification passed on iPhone XR with 13.1 beta 2 running 1.12(19.09.07.03)
![image](https://user-images.githubusercontent.com/17010094/64565214-45351900-d321-11e9-9217-fe0fb67c038a.png)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Air 3rd Generation iOS 13.1` running `1.12 (19.09.10.18)`:

<img width="791" alt="Screen Shot 2019-09-11 at 12 09 19 AM" src="https://user-images.githubusercontent.com/2602313/64667621-6b91ac00-d428-11e9-8baa-4a1a7ae9b047.png">
<img width="794" alt="Screen Shot 2019-09-11 at 12 09 10 AM" src="https://user-images.githubusercontent.com/2602313/64667622-6b91ac00-d428-11e9-99ff-663464228479.png">

Verification **PASSED** on `iPhone 6s+` using `iOS 12.4.1` running `1.12 (19.09.13.06)`:

![IMG_9917](https://user-images.githubusercontent.com/2602313/64884290-589cf880-d62f-11e9-87b1-a40e85a9492b.PNG)
![IMG_9916](https://user-images.githubusercontent.com/2602313/64884291-589cf880-d62f-11e9-9f27-57d974f97d2f.PNG)
