### ISSUE TITLE
Match Safari in anonymizing js method values

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5523]
More details https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1655233690880109?thread_ts=1655232077.572789&cid=C023VS4HJ6Q

**Comment by thypon** [comment]
I think we should implement a generic utils method to lift this issue. Hereafter an example implementation:

```javascript
const generatePPToString = (body) => {
    const toString = () => {
      return body
    }

    const recursiveToString = () => {
      return Object.toString.toString()
    }

    recursiveToString.toString = recursiveToString
    toString.toString = recursiveToString

    return toString
  }
  ```

**Comment by thypon** [comment]
Cc @cuba regarding https://github.com/brave/brave-ios/pull/5444

**Comment by Brandon-T** [comment]
This was done as part of the Javascript refactor and also in SolanaWeb3.js
