### ISSUE TITLE
[Brave-Core] - New Threading modules causes crashes on iOS

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#5528]
### Description: 
- With Cr102 & Cr103, Brave-Core has changed its underlying threading code and causes iOS to crash when loading Brave-Core.
- iOS Crashes when migrating bookmarks and history.
- iOS Crashes when deleting passwords.
- iOS Crashes when importing and exporting bookmarks.

### Steps to Reproduce 
  1. Import or Export bookmarks.
  2. Delete ALL history.
  3. Delete bookmarks or history one by one.

**Actual result:** 
- Crashes

**Expected result:**
- Should not crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.40+

**Device details:** 
Any

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iPadOS 15.5` using `1.40 (22.6.27.15)`

- Confirmed crash is not observed when delete bookmarks/history
- Confirmed able to import/export bookmarks
- Confirmed able to delete history and bookmarks one by one
- Confirmed able to delete all history
- Confirmed able to delete passwords/autofill

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 15.5` & `iPhone X` running `iOS 15.5` using `1.40 (22.6.27.15)`

- Confirmed crash is not observed when delete bookmarks/history
- Confirmed able to import/export bookmarks
- Confirmed able to delete history and bookmarks one by one
- Confirmed able to delete all history
- Confirmed able to delete passwords/autofill
