### ISSUE TITLE
Wallet: Make sure eTLD+1 wraps as a whole 

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5534]
### Description: 
In many screens, we display eTLD+1 to indicates this DApp is making a request or eth permission edit mode.
We have bolded the eTLD+1 but currently it wrapps and breaks it apart when the url origin is long enough. This is hard for users to notice the eTLD+1 part from the long url. That is a security concern we need to fix. 

### Steps to Reproduce 
  1. Go to any screen display url origin. for example, edit site connection screen
  2. make sure the eTLD+1 is bolded and wrapped as a whole if the url is very long

**Actual result:** 
![eTLD+1-wrapps](https://user-images.githubusercontent.com/1187676/174109390-b063a092-1561-43a7-aea8-351484f9ef82.png)

**Expected result:**
![eTLD+1_wrapps_correct](https://user-images.githubusercontent.com/1187676/174110102-5ceb219e-c752-4f8e-ab59-01af300dda8e.png)

**Note: after this https://github.com/brave/brave-ios/pull/5522, insecure context page will no longer get injected wallet provider js.**
Here is a [long url with wallet dapp functionality](http://www.reddit.com_______________________________________________.__________________________.______________www.reddit.com______________________________________________________.___._______________wwwwwwwwwwwwwwwwwwwwwwwwwwwwwww.xdv.cz.srv21.endora.cz/metapoc/index.html)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.40 (22.6.21.16)
- Verified eTLD+1 is shown prominently on panel 
- Verified eTLD+1 wraps and shows full domain name
- Verified on both light and dark theme
- Encountered [#5557](https://github.com/brave/brave-ios/issues/5557) specifically on iPhone XR

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/175042881-6c3aa598-1640-4173-b7aa-b77b8522525b.png> | <img width=280 src=https://user-images.githubusercontent.com/17010094/175042638-c2d4e16f-72e0-4d02-9fa7-9d57e461224f.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/175042795-d73c2ab4-8073-48a3-b4df-8ce376151468.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/175042714-1e5b4f4d-87fd-40a9-97f7-fe0177b7981d.png> | <img width=280 src=https://user-images.githubusercontent.com/17010094/175043151-9fb949b3-a075-4ae9-a45f-f07e3a1e6a8f.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/175042766-ef449574-4d9d-491d-a7cc-39cb6bbb4985.png>
