### ISSUE TITLE
Wallet panel shows onboarding before any other state

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5537]
### Description: 
Reported to typically occur on Polygon network, most times when tapping the wallet icon in the URL bar the onboarding state is shown on the panel briefly before the locked/unlocked states. Sometimes it shows onboarding long enough that user can tap on button to trigger onboarding when the wallet is already setup, getting into a weird state

### Steps to Reproduce 
  1. Use dapp on polygon network
  2. Tap wallet icon

**Actual result:** 

Onboarding is shown

**Expected result:**

Loading state / don't show onboarding

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

I'm unable to reproduce / visually see this one myself, but can see in layout logs we show onboarding for 2 layout passes. A loading state should resolve this.

More info / report video:
https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1655318011732479

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.40(22.6.27.15)
- Verified steps from issue description
- Verified with network set to Polygon, there is no onboarding shown when opening the wallet panel
- Verified on a few Dapps with network set to Polygon
----------
Verification passed on iPhone XR with iOS 15.4.1 running 1.40(22.6.27.15)
- Verified steps from issue description
- Verified with network set to Polygon, there is no onboarding shown when opening the wallet panel
- Verified on a few Dapps with network set to Polygon
----------
Verification passed on iPad Pro with iOS 15.6 Beta running 1.40(22.6.27.15)
- Verified steps from issue description
- Verified with network set to Polygon, there is no onboarding shown when opening the wallet panel
- Verified on a few Dapps with network set to Polygon
