### ISSUE TITLE
Block dapp requests from inactive tabs

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5539]
### Description: 

ref: https://github.com/brave/security/issues/887#issuecomment-1154351471

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.40 (22.6.27.15)
- Verified steps from [ #5540](https://github.com/brave/brave-ios/pull/5540)
- Verified having wallet connected to both Sushiswap and Uniswap, and keeping Sushiswap as focused tab, removing all accounts from Manage site connections, removes wallet account association from both the site. Uniswap shows `Connect Wallet` when focused 
---------
Verification passed on iPhone XR with iOS 15.4.1 running 1.40 (22.6.27.15)
- Verified steps from [ #5540](https://github.com/brave/brave-ios/pull/5540)
- Verified having wallet connected to both Sushiswap and Uniswap, and keeping Sushiswap as focused tab, removing all accounts from Manage site connections, removes wallet account association from both the site. Uniswap shows `Connect Wallet` when focused 
---------
Verification passed on iPad Pro with iOS 15.6 Beta running 1.40 (22.6.27.15)
- Verified steps from [ #5540](https://github.com/brave/brave-ios/pull/5540)
- Verified having wallet connected to both Sushiswap and Uniswap, and keeping Sushiswap as focused tab, removing all accounts from Manage site connections, removes wallet account association from both the site. Uniswap shows `Connect Wallet` when focused
