### ISSUE TITLE
SSL Trust Validation too strict [does not match Safari's relaxed validation]

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#5543]
### Description: 
- Brave-iOS SSL trust validation is too strict; it validates the BasicX509Policy and Mixed-Content
- All other browsers on iOS validate only the SSLTrustPolicy and do not validate Mixed-Content 
- iOS blocks Mixed-Content by default, so no need to validate it

### Steps to Reproduce 
  1. Visit `https://kevsong.com`
  2. Notice the icon in the URL bar + the certificate viewer says the website is not secure

**Actual result:** 
- Website is not secure

**Expected result:**
- Website should be secure as per other browsers relaxed trust validation

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
- Any

**Device details:** 
- Any

**Website problems only:**
- Did you check in Safari/Firefox (WkWebView-based browsers)? Yes
- Happens only in Brave-iOS

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5]
Version 1.52 (23.6.14.13)
BraveCore 1.52.125 (114.0.5735.110)
```
---------------------------

**STEPS:**
1. Launch Brave
2. Go to https://kevsong.com
3. Verify the icon in the URL bar + the certificate viewer 

**ACTUAL RESULTS:**
- Verified that the icon in the URL search bar is shown a `lock`
- Verified that the certificate viewer is showing that the website https://kevsong.com is secure and valid

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/34507b94-841c-4d70-91b8-eb454e1c00ce) | ![2](https://github.com/brave/brave-ios/assets/128532965/23bee524-f0ea-4919-8456-0b53ecef3f2b) |
