### ISSUE TITLE
Reader mode custom fonts (Fira/New York) not being used within the reader mode page

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#5553]
### Description: 

The reader mode serif and sans-serif fonts are defaulting to helvetica/times instead of the custom fonts

**Actual result:**

Reader mode uses Helvetica/Times New Roman

| Sans-Serif | Serif |
| --- | --- |
| ![IMG_E02B102D6D6C-1](https://user-images.githubusercontent.com/529104/174649092-ee23de74-21d2-41b9-b2b6-51a4da25ddd6.jpeg) |  ![IMG_96FD277F87CB-1](https://user-images.githubusercontent.com/529104/174649079-4e35875b-8479-46f7-b749-979296e74d39.jpeg)

**Expected result:**

Reader mode should use Fira Sans/New York Medium

| Sans-Serif | Serif |
| --- | --- |
| ![Simulator Screen Shot - iPhone 13 Pro - 2022-06-20 at 12 57 59](https://user-images.githubusercontent.com/529104/174649205-8d9cfde7-e80b-4cd2-9c29-2835b4bac73e.png) | ![Simulator Screen Shot - iPhone 13 Pro - 2022-06-20 at 12 58 04](https://user-images.githubusercontent.com/529104/174649218-d42d3e8d-5a25-4ab5-b512-60ba8b2c6478.png) |

**Reproduces how often:** Always
**Brave Version:** 1.39

**Comment by Uni-verse** [comment]
Verified using 1.40 (22.6.21.16)

Test Devices: 
iPhone 12 | iOS 15.4
iPhone X | iOS 14.4.2
iPad | iOS 15.5

- Verified Reader Mode uses Fira Sans/New York Medium by default.
- Verified Reader settings will persist when changing webpages.

Sans Serif | Serif
-|-
![IMG_3114](https://user-images.githubusercontent.com/17885425/174869379-97912045-61c8-4efd-9a75-00895416aa9d.PNG) | ![IMG_3115](https://user-images.githubusercontent.com/17885425/174869385-abf8a94b-a474-4e84-9acf-cf5b5a97f600.PNG)
![IMG_0373](https://user-images.githubusercontent.com/17885425/174869446-ecc21eaf-cbfb-48f6-b7e2-74dc940a4a49.PNG) | ![IMG_0374](https://user-images.githubusercontent.com/17885425/174869451-3dc67c85-f93f-4d7e-a71d-a32c0c7d0c6e.PNG)
