### ISSUE TITLE
Browser crash when trying to remove connected site

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5566]
### Description: 
Browser crash when trying to remove connected site

### Steps to Reproduce 
  1. Connect to a Dapp via panel
  2. Open settings -> Wallet -> Manage site conenctions
  3. Swipe left to delete the connected site, browser crashes

**Actual result:** 
Browser crash when trying to remove connected site

**Expected result:**
No crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Only once upon upgrade to 1.40 (22.6.22.18)

**Brave Version:** 
1.40 (22.6.22.18)

**Device details:** 
iPhone 7+ (iOS 14.8.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by srirambv** [comment]
Ran into this again when trying to verify #5596. Happened on RC build after upgrading.

**Comment by HEagle18** [comment]
Reducing from P1 to P2. This will also not be an issue when we stop supporting iOS 14. Talked it over with Sri and Stephen. Sri will do more testing to see if its still an issue.

**Comment by HEagle18** [comment]
@srirambv I wasn't able to reproduce this neither was Stephen on iOS team. We also no longer support iOS 14. Closing out.
