### ISSUE TITLE
Share link copies active tab URL 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#557]
### Description: 
Share link copies active tab URL 

### Steps to Reproduce 
  1. Visit a few sites and add to history
  2. Open a new tab and visit a site
  3. With that active tab open history from settings
  4. Long press on a history entry that is different from step 2 and tap on share link
  5. Select app to share, adds url of the active tab instead of the the link from history

**Actual result:** 
https://drive.google.com/open?id=14dWZ0DUpecVYg7B2HURiIzPSuwB-tFke

**Expected result:**
Should copy the URL from history to share

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.12.3.22)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Fixed in https://github.com/brave/brave-ios/pull/517
