### ISSUE TITLE
Portfolio chart is not populating for timeframes 1H, 1D & 1W

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-ios#5570]
### Steps to Reproduce 
  1. add assets outside of ETH and WBTC to your portfolio
  2. and see does chart come up for 1H, 1D or 1 W
  3.

**Actual result:** 
<img width="411" alt="Screenshot 2022-06-23 at 17 07 28" src="https://user-images.githubusercontent.com/12224304/175331991-1a17368e-0cb3-4f5e-97a0-9d0d449d96ca.png">

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
all times

**Brave Version:** 
1.39.1

**Device details:** 
iPhone 11

**Website problems only:**
- did you check with Brave Shields down? no
- did you check in Safari/Firefox (WkWebView-based browsers)? no

**Comment by nuo-xu** [comment]
closing this since we now fetching price and price history individually if as a whole failed. 
missing price history in asset details screen is tracked here https://github.com/brave/brave-ios/issues/5816
