### ISSUE TITLE
Dapp interaction is not shown on first try if wallet is not created

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5571]
### Description: 
Dapp interaction is not shown on first try if wallet is not created

### Steps to Reproduce 
  1. Clean install
  2. Do not create wallet
  3. Trigger wallet notification
  4. Create wallet and continue
  5. Closes onboarding and shows wallet panel
  6. Close panel and reopen panel shows wallet connect info

**Actual result:** 

https://user-images.githubusercontent.com/17010094/175327476-8bf1a3f8-b8a5-40dc-a9a2-840a350bfe66.MP4

**Expected result:**
Should show wallet connect info as soon as the account is created

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.40

**Device details:** 
iPhone 7+ (iOS 14.8.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by StephenHeaps** [comment]
Closing as we match desktop behaviour for DApp onboarding. We show the DApp connect when we receive connect request, [which is currently rejected in Core when there is no wallet setup to show onboarding](https://github.com/brave/brave-core/blob/55b64b2b0a5a50b0b2eec77f75a944f97065df16/components/brave_wallet/browser/ethereum_provider_impl.cc#L1111-L1120).

Desktop:

https://github.com/brave/brave-ios/assets/5314553/c39bcfa2-da92-4662-a1e5-efcc0b750974

iOS:

https://github.com/brave/brave-ios/assets/5314553/2bfc9085-a6b6-4b7c-84ea-006a989715b8
