### ISSUE TITLE
Add Solana to the network selector

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#5577]
Should prompt for new Solana account creation if a user hasn't created one after selecting the Solana network.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.42 (22.8.8.19) 
- Verified `Solana Mainnet Beta` is shown under Select Network dropdown
- Verified selecting `Solana Mainnet Beta` prompts to create an account if not already created
- Verified selecting `Solana Mainnet Beta` from dropdown in portfolio/buy/send/swap screens prompts to create a new account if not already created
- Verified selecting `No` in the account creation prompt resets the network back to previous selection
- Verified selecting `Yes` in the account creation prompt creates a new Solana Account and sets it as active account & network
- Verified able to update account name at the time of creation and is retained
- Verified adding an account via accounts tab doesn't prompt when Solana is selected
- Logged https://github.com/brave/brave-browser/issues/36774

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 16 Beta 3)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/183611023-38a00956-17d9-418e-976a-04ceb553923c.MP4> | <video src=https://user-images.githubusercontent.com/17010094/183610487-a64b65fa-270b-480f-ba83-a37ece1a5f7a.MP4> | <video src=https://user-images.githubusercontent.com/17010094/183611304-b68b8c17-69c0-42bf-add5-7f0cf1cad379.MP4>
