### ISSUE TITLE
Login to Facebook keeps redirecting 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#558]
### Description: 
Login to Facebook keeps redirecting 

### Steps to Reproduce 
  1. Install 1.7 (18.12.3.22)
  2. Open https://m.facebook.com/
  3. Enter credentials and click login
  4. Throw phone in anger as it doesn't allow you to login and instead keeps trying to redirect

**Actual result:** 
Need to practice zen to keep self calm

**Expected result:**
Waste time scrolling through FB feed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.12.3.22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? 
Yes, still doesn't work chances of breaking iPhone is more 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
Issue reproduced by @GeetaSarvadnya

**Comment by srirambv** [comment]
This only happens when you upgrade from 1.7 (18.11.30.03). On clean install of 1.7(18.12.3.22) it logs in but you can only see the page when shields is down. Shields up just keeps a blank page.

**Comment by jhreis** [comment]
~Probably something with content rules.~
Probably not content rules actually, if shields don't impact it.

**Comment by iccub** [comment]
This does not happen to me when going 1.6->1.7.
Could we revisit this ticket once QA will test 1.6 upgrades?

**Comment by srirambv** [comment]
@iccub all issues with `QA/Yes` will be rechecked once the migration build is available.

**Comment by jhreis** [comment]
This should be fixed now due to adblock file upgrade. @srirambv can you please retest?

**Comment by srirambv** [comment]
Checked on migration as well. Login works fine. Page doesn't keep redirecting like before. Closing as fixed
