### ISSUE TITLE
Dapp interaction notification stays on when a new tab is opened

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5580]
### Description: 
Dapp interaction notification stays on when a new tab is opened

### Steps to Reproduce 
  1. Trigger Dapp notification
  2. Open a new tab
  3. Notification stays on top of new tab

**Actual result:** 

https://user-images.githubusercontent.com/17010094/175529508-d237a406-4c22-46ca-b710-71888d4075cb.mp4

**Expected result:**
Should close the notification when a new tab is opened 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.40(22.6.22.18)

**Device details:** 
iPad Pro (iOS 15.6 Beta)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by diracdeltas** [comment]
also shouldn't `This page` say the origin of the page in keeping with our wallet security guidelines?

**Comment by StephenHeaps** [comment]
> also shouldn't `This page` say the origin of the page in keeping with our wallet security guidelines?

Any request that is shown when tapping the notification should show the origin as well, but I agree we should also show the origin on this notification too.

**Comment by StephenHeaps** [comment]
Handled in https://github.com/brave/brave-ios/pull/5626

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.41 (22.7.11.19)
- Verified steps from issue description and [#5626](https://github.com/brave/brave-ios/pull/5626)
- Verified Dapp interaction notification is removed when a new tab is opened

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta 3)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/179034906-ef1e4a40-4f13-4e9a-b1c6-370742b2ff9d.MP4> | <video src=https://user-images.githubusercontent.com/17010094/179034915-912a83bc-deaa-49b5-8a3e-b9ba3c77ef5b.MP4> | <video src=https://user-images.githubusercontent.com/17010094/179034925-184e8696-e3b5-4502-814c-672bfcc0f54a.MP4>
