### ISSUE TITLE
On swaps, keypad should disappear when you touch anywhere outside of keypad

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-ios#5584]
### Description: 
keypad doesn't go away and user doesn't get to see the important information easy without scrolling. See Phantom swaps for a good example.

### Steps to Reproduce 
  1. try to do a swap. 
  2. enter in 'swap from' asset and amount and then click on screen outside numpad 
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by StephenHeaps** [comment]
Thanks for the UX feedback @HEagle18, we have a similar open issue to handle this by adding a toolbar to the number pad keyboards with a button to dismiss the keyboard. We can investigate a tap outside of keyboard to dismiss as well.
https://github.com/brave/brave-ios/issues/4978

**Comment by HEagle18** [comment]
perfect
