### ISSUE TITLE
Able to still connect to wallets when default provider is set to none

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5597]
### Description: 
Able to still connect to wallets when default provider is set to none

### Steps to Reproduce 
  1. Clean profile and create wallet
  2. Visit a Dapp and trigger connection notification
  3. Go to Settings -> Wallet -> Set default provider to none
  4. Click on connection notification, allows you to connect to Dapp

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/175951643-344dbbc5-2cab-4241-aac5-01fca4f4fbb0.png)

**Expected result:**
Dismiss Dapp connection notification when default provider is set to none

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.40 (22.6.24.14)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by diracdeltas** [comment]
probably should prioritize this since it seems like a privacy issue for users who set provider to 'None' to avoid sites being able to fingerprint them, etc.

**Comment by iccub** [comment]
Removing release blocker label, per wallet-dev convo, this will be fixed in 1.41

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.41 (22.7.11.19)
- Verified steps from issue description and [#5626](https://github.com/brave/brave-ios/pull/5626)
- Verified wallet notification is dismissed when provider is set to none

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta 3)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/179034877-2a0fc30f-6166-411d-bd44-7937d5c525f5.MP4> | <video src=https://user-images.githubusercontent.com/17010094/179034899-994b38ca-c8b9-4058-af3f-83317351bfd9.MP4> | <video src=https://user-images.githubusercontent.com/17010094/179034904-3564f8a4-050c-4927-a38c-295c6f03c82a.MP4>
