### ISSUE TITLE
[Sync] - Sync Types should not be selectable

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#5601]
### Description: 
- Sync types being selectable are allowing the user to see the wrong menu

### Steps to Reproduce 
  1. Create a new sync chain on iOS.
  2. Tap on the `History` or `Bookmarks` cell.
  3. Shows the "Remove this device from the chain" alert.

**Actual result:** 
- Shows alert from the bottom of the screen

**Expected result:**
- Should not show anything. Cell should only allow tapping on the switches

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
- Easily reproduced

**Brave Version:** 
- Any

**Device details:** 
- Any

**Comment by Uni-verse** [comment]
Verified using `1.40 (22.6.27.15)`

Devices: 
`iPhone 12` | `iOS 15.5`
`iPhone X` | `iOS 14.4.2`
`iPad` | `iPadOS 15.5`

- Used STR from https://github.com/brave/brave-ios/issues/5601#issue-1285908899 to verify that `history` and `bookmarks `sync switches should not be selectable. 
- Verified alert is not shown when toggling the switches.

https://user-images.githubusercontent.com/17885425/176025795-cc68c655-42f6-4bfe-b8d8-e8d3d427360e.MP4
