### ISSUE TITLE
Reset wallet doesn't remove the added networks

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5604]
### Description: 
Reset wallet doesn't remove the added networks

### Steps to Reproduce 
  1. Add a custom network on iOS 14 device
  2. Reset wallet
  3. Create a new wallet account
  4. Check settings, all wallet settings are defaulted, added networks are not removed

**Actual result:** 

https://user-images.githubusercontent.com/17010094/175999701-e4879652-1996-425f-8e0e-22fdcdbdd75b.MP4

**Expected result:**
Should remove added networks

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.40 (22.6.27.15)

**Device details:** 
iPhone 7+ (iOS 14.8.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps 
Note: not an issue on iOS 15 devices

**Comment by StephenHeaps** [comment]
A similar bug can also be reproduced on iOS 15:
1. Add custom network
2. Open main wallet
3. Navigate to wallet settings
4. Verify custom network exists in custom networks list
5. Tap 'Reset Wallet'
6. **Do not dismiss/close wallet**
7. Tap 'Get Started'
8. Setup wallet
9. Navigate to wallet settings
10. Observe custom network still shown.

Note: This is separate (but similar) to the above iOS 14-only bug. Both are just visual bugs; the networks list would be empty after app quit + relaunch. 

https://user-images.githubusercontent.com/5314553/176200281-0e7ef8d1-a347-4438-a3e5-0b5a535373cd.mp4

**Comment by srirambv** [comment]
Verification passed on iPhon 7+ with iOS 14.8.1 running 1.41(22.7.11.19) Dev build

https://user-images.githubusercontent.com/17010094/178679684-84960181-019b-4a38-8635-52c2fc71f417.mp4
