### ISSUE TITLE
Block colours are inverted compared to desktop

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5610]
### Description: 
Block colours are inverted compared to desktop

### Steps to Reproduce 
  1. Create account on desktop
  2. Restore the same seed on iOS
  3. Open wallet panel, colour of the panel is inverted compared to desktop

**Actual result:** 
Desktop | iOS
-- | -- 
<img width=200 src=https://user-images.githubusercontent.com/17010094/176099629-0a383dd6-b9e7-4731-94cd-550193582439.png> |  <img width=200 src=https://user-images.githubusercontent.com/17010094/176100301-5e2ea9bd-55f3-4a8f-a4a2-6d823070e9f3.png>

**Expected result:**
Should be same 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.40 (22.6.27.15)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps @jamesmudgett @kylehickinson

**Comment by StephenHeaps** [comment]
Blockie colours are no longer used on wallet panel since updated Blockie styling in https://github.com/brave/brave-ios/issues/8375
