### ISSUE TITLE
Wallet: Context Menu showing wrong account address

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5612]
### Steps to Reproduce 
  1. open wallet (make sure you have multiple accounts)
  2. go to either send or swap
  3. click the account info on the top header
  4. long press any not currently selected account so it will show a context menu
  

**Actual result:** 
1. observe that the full account address is displaying the current selected account's address
2. if you click copy address and paste it somewhere else it actually copied the current selected account's full address

**Expected result:**
In context menu it should display the focused account full address
copy address action should copy the focused account full address

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easy

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.40 (22.6.28.18)
- Verified steps from issue description
- Verified long press on a non selected account shows the correct address and not selected address
- Verified copying address for non-selected account is copied to clipboard and not the selected account address
----------
Verification passed on iPhone XR with iOS 15.4.1 running 1.40 (22.6.28.18)
- Verified steps from issue description
- Verified long press on a non selected account shows the correct address and not selected address
- Verified copying address for non-selected account is copied to clipboard and not the selected account address
----------
Verification passed on iPad Pro with iOS 15.6 Beta running 1.40 (22.6.28.18)
- Verified steps from issue description
- Verified long press on a non selected account shows the correct address and not selected address
- Verified copying address for non-selected account is copied to clipboard and not the selected account address
----------
Encountered #5618 on iOS 16
