### ISSUE TITLE
Youtube URL/state not remembered after closing browser

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#5615]
Regression of #5075

**Comment by Uni-verse** [comment]
Verified using 1.40 (22.6.28.18) 

Test Devices: 
iPhone 12 | iOS 15.5
iPhone X | iOS 14.4.2
iPad (7th Gen) | iOS 15.5

- Confirmed state persists after relaunching browser using STR from https://github.com/brave/brave-ios/issues/5075#issue-1162929123
- Confirmed tab preview state is remembered, and includes URL after relaunching app.
