### ISSUE TITLE
Available accounts not listed on Send/Swap screen 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5618]
### Description: 
Available accounts not listed on Send/Swap screen 

### Steps to Reproduce 
  1. Create wallet and add multiple accounts
  2. Open Send/Swap screen
  3. Tap on Account dropdown, shows address instead of available accounts

**Actual result:** 

https://user-images.githubusercontent.com/17010094/176261001-0a0b9e69-ddf1-454a-a273-d69a93663acc.mp4

**Expected result:**
Selecting dropdown should list all accounts

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.40 (22.6.28.18)

**Device details:** 
iPad Pro (iOS 16 Beta 2)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by HEagle18** [comment]
@srirambv I'm on iphone 11 and 1.39.1 and this flow works fine. Can you try on on iphone with yours ?

**Comment by StephenHeaps** [comment]
> @srirambv I'm on iphone 11 and 1.39.1 and this flow works fine. Can you try on on iphone with yours ?

@HEagle18 It's an iOS 16 (beta) issue only at the moment I believe.

**Comment by kjozwiak** [comment]
Reproduced as well on `iPhone 11` using `iOS 16` running `1.40 (22.6.29.0)` as per the following examples:

**`Example`** | **`Example`**
---------------|-----------------
![IMG_3868](https://user-images.githubusercontent.com/2602313/176372974-2b45a0e1-115b-49e4-8775-db4542b9b729.PNG) | ![IMG_3869](https://user-images.githubusercontent.com/2602313/176372984-47690fbe-8bb8-4080-9ac6-8bef752b2983.PNG)

Went through the same STR/Case mentioned above using `iPhone 6s+` using `iOS 15` running `1.40 (22.6.29.0)` and couldn't reproduce the issue as per the following:

**`Example`** | **`Example`**
---------------|-----------------
![IMG_0262](https://user-images.githubusercontent.com/2602313/176378679-1dba7181-9cc3-4ca4-bdd3-667565851f4b.PNG) | ![IMG_0263](https://user-images.githubusercontent.com/2602313/176378677-85efa4bb-282c-417d-84d1-ccbfa61d138b.PNG)

Definitely a `iOS 16` issue as it's working fine on `iOS 15` 👍

**Comment by StephenHeaps** [comment]
This issue _appears_ to be resolved on iOS 16 beta 4 when built with Xcode 13 / iOS 15 SDK.
However, will keep this issue open to track issue when building with Xcode 14 / iOS 16 SDK which as of beta 4 requires scrolling down then back up before the button works as expected:

https://user-images.githubusercontent.com/5314553/183106223-0e37d446-5d85-4ae1-81c7-50a5f3d9442c.mov

**Comment by nuo-xu** [comment]
Double checked with Xcode 14.1 beta 2. Button in header starts working

**Comment by srirambv** [comment]
Verification passed on iPad Pro running 1.45 (22.10.25.19)
- Verified steps from issue description
- Verified dropdown shows all accounts created
- Encountered [#6273](https://github.com/brave/brave-ios/issues/6273)


https://user-images.githubusercontent.com/17010094/198387196-4b92b211-467d-4813-8383-e1c7deec2bde.MP4
