### ISSUE TITLE
Crash when deleting bookmarks in folders 

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#5623]
### Description: 
Not sure the exact repro steps or root cause but seems to be happening intermittently when deleting bookmarks from a folder after previously removing bookmark from another folder. Possibly has to do with removing last item from a folder. 

Likely regression, possibly related to new threading modules issue - https://github.com/brave/brave-ios/issues/5528 

### Steps to Reproduce 
  1.  Scan QR code to sync to chain with some bookmarks in folders 
  2. Navigate to any folder and remove bookmarks
  3. Return to root and switch folders, try to remove bookmarks in folder
  4. Repeat steps 2 & 3 until crash

**Actual result:** 
Removing bookmark in folder will cause crash using STR

<table><tr><td>

https://user-images.githubusercontent.com/17885425/176330720-b043b343-140c-4807-8640-eb566c9afb25.MP4

</td></tr></table>

**Expected result:**
Should not crash

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent

**Brave Version:** 
1.40 (22.6.28.18)

**Device details:** 
iPhone 12 | iOS 15
iPhone X | iOS 14

**Comment by Uni-verse** [comment]
Update: Was not able to repro using new bookmarks and folders. Seems to be only happening after connecting to sync chain and removing the bookmarks from the chain.

**Comment by iccub** [comment]
Removing release blocker label and lowered priority, we want to fix it in next release which is 1.41

**Comment by iccub** [comment]
Should be fixed in latest 1.42, please retest

**Comment by Uni-verse** [comment]
Verified using `1.42 (22.8.8.19)`

Test Devices:

iPhone XR iOS 15.5
iPad (7th Gen) iOS 15.5
iPhone X iOS 14.4.2

- Ensured crash is not reproduced when deleting bookmarks in folders using the STR in https://github.com/brave/brave-ios/issues/5623#issue-1288067673
- Ensured crash is not reproducible when upgrading from 1.41 -> 1.42
