### ISSUE TITLE
Remove `transferrableAmount` and the support for draining old wallets into desktop.

### ISSUE THREAD

**Issue by szilardszaloki** [brave/brave-ios#5632]
### Description: 
https://github.com/brave/brave-core/pull/13974 removes `GetTransferableAmount()` from the `Ledger`'s interface. `GetTransferableAmount()` is used by `transferrableAmount`, which is used in [4 places](https://github.com/brave/brave-ios/search?q=transferrableAmount) in the iOS client. These references and all UI + functionality related to draining old wallets into desktop should be removed, since we no longer support it.

### Additional Information
cc: @kylehickinson

**Comment by kylehickinson** [comment]
This was removed a while ago
