### ISSUE TITLE
'Try Brave Search' button cut in other languages

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5644]
### Steps to Reproduce 
  1. Use other than english language
  2. Trigger the Brave Search popup by not having B-S set as default

**Actual result:** 
![IMG_29EFA711BB80-1 (1)](https://user-images.githubusercontent.com/6950387/177385418-c24e53e8-cdc4-44b8-91f2-10da8195dad9.jpeg)

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Fixed here https://github.com/brave/brave-ios/pull/5639

**Comment by Uni-verse** [comment]
Verified using `1.40.1 (22.7.5.21)`

Test Devices:
iPhone 12 Pro | iOS 15.5
iPhone X | iOS 14.4.2
iPad (7th Gen) | iOS 15.5

- `Try Brave Search` button in search promo cell is not cut off in other languages.
- Search promo cell displayed correctly after dismissing the search promo cell the first time. 

iPhone | iPad
-|-
<img width="400" alt="1" src="https://user-images.githubusercontent.com/17885425/177627883-c40d6170-1c3b-4eaa-8967-6657bd7e7d62.PNG"> | <img width="400" alt="2" src="https://user-images.githubusercontent.com/17885425/177627924-7dc1943c-a9ce-4a3c-983b-16c208b4a0e9.PNG">
Dismiss Once (iPhone) | Dismiss Once (iPad)
<img width="400" alt="3" src="https://user-images.githubusercontent.com/17885425/177627957-12daa0d4-3af5-40a9-9238-53250d4aa6d5.PNG"> | <img width="400" alt="4" src="https://user-images.githubusercontent.com/17885425/177628013-ce20e74d-2bf2-45f1-ab8d-3dcbcfae2eb7.PNG">
iOS 14 | Dismiss Once (iOS 14)
<img width="400" alt="5" src="https://user-images.githubusercontent.com/17885425/177629427-6748a941-1fe1-4b3f-a831-6d76d5286204.PNG"> | <img width="400" alt="6" src="https://user-images.githubusercontent.com/17885425/177629464-846bb0ee-a203-45e0-8743-8928cfc5441c.PNG">
