### ISSUE TITLE
Update URL bar and toolbar collapsing behaviour

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#5645]
### Description: 

- Should match Safari more closely
- Should fix the bug where the tabs bar goes dark and the url bar collapses funny (items move/get squished)
- Prep for bottom bar

**Comment by Uni-verse** [comment]
Verified using `1.41 (22.7.11.19)` on `iPhone 12 Pro` running `iOS 15.5` & `iPhone X` running `iOS 14.4.2`

- Verified `URL bar`/`toolbar` behavior is collapsing/expanding smoothly when scrolling and matches `Safari` more closely.
- Verified bug fix where the tabs bar goes dark and the url bar collapses funny (items move/get squished)
- Verified user is able to use `tab bar` when selected for `only landscape` and visibility transitions are working smoothly.
- Verified `URL bar` transitions are smooth without the tab bar (Tab bar is disabled).
- Verified switching between portrait and landscape happens smoothly and doesn't impact tool bar transitions.
- Verified URL bar and toolbar visibility transitions while in `Reader Mode` are smooth and match Safari behavior.

<table><tr><td>iOS 15 (dark)</td></td><td>iOS 15 (light)</td><td>iOS 14</td></tr>
<tr>
<td>

https://user-images.githubusercontent.com/17885425/178846107-33940f98-a33a-4cc1-a9a6-fbe1a29b9a99.MP4

</td>
<td>

https://user-images.githubusercontent.com/17885425/178846163-114d6174-feed-4d4a-8e95-13944d318804.MP4

</td>
<td>

https://user-images.githubusercontent.com/17885425/178846210-7cbd5ab8-fc5f-47fa-9754-f11dc05727bf.MP4

</td>
</tr></table>

**Comment by Uni-verse** [comment]
Verified using `1.41 (22.7.11.19)` on `iPad (7th Gen)` running `iPadOS 15.5`

- Verified `URL bar`/`toolbar` behavior is collapsing/expanding smoothly when scrolling and matches `Safari` more closely.
- Verified bug fix where the tabs bar goes dark and the url bar collapses funny (items move/get squished)
- Verified `URL bar` transitions are smooth without the tab bar (Tab bar is disabled).
- Verified switching between `portrait` and `landscape` happens smoothly and doesn't impact tool bar transitions.
- Verified URL bar and toolbar visibility transitions while in `Reader Mode` are smooth and match `Safari` behavior.
- Verified URL bar and `top/bottom toolbar` transitions happen smoothly while in split mode. 

https://user-images.githubusercontent.com/17885425/178848666-eda61feb-a80e-48d8-8bef-098529cfc14f.MP4
