### ISSUE TITLE
Add toggle to show/hide test networks in wallet settings

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5646]
### Description: 

Add a toggle in Wallet settings to show/hide test networks.

ref: https://github.com/brave/brave-browser/issues/21650

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.41 (22.7.11.19)
- Verified a new setting for `Show test networks` is shown under Wallet ->Networks 
- Verified the settings is disabled by default on clean install or on upgrade
- Verified test networks are only shown when the settings is enabled
- Verified if the current network is set to a Test network, post upgrade it is retained and remaining networks are removed 
- Encountered [#5687](https://github.com/brave/brave-browser/issues/36883) on iPad

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 16 Beta 3)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/178991934-b44fd1ae-2e02-41e1-bad8-ff299d4fdd9f.MP4> | <video src=https://user-images.githubusercontent.com/17010094/178991955-48a65f5b-4b35-4e0c-b8aa-1d8d9c95a72f.MP4> | <video src=https://user-images.githubusercontent.com/17010094/178991968-6180ac3f-3215-43b9-81ea-63bb43a931d0.MP4>
