### ISSUE TITLE
Shields stats doesn't work post migration

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#565]
### Description: 
Shields doesn't work post migration

### Steps to Reproduce 
  1. Install 1.6.6 from appstore
  2. Upgrade to 1.7 (18.12.04.23)
  3. Open a new tab and visit a site, open shields all stats show 0

**Actual result:** 
Shields doesn't work post migration

**Expected result:**
Shields should do its job

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.12.04.23)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
Fixed per: https://github.com/brave/brave-ios/pull/543
