### ISSUE TITLE
Automatically redirect to alternative website frontends

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5657]
reddit.com/r/brave -> old.reddit.com/r/brave

**Comment by Uni-verse** [comment]
Verification `PASSED` using `1.41 (22.7.15.11)`

Devices: 
iPhone 12 | iOS 15.5
iPhone X | iOS 14.4.2
iPad | iPadOS 15.5

Menu/UI

- Confirmed both redirect toggles are disabled by default (not pictured)
- Confirmed Setting Cell Title `Website Redirects` matches specs 
- Confirmed `Copy` for redirection info footers match latest specs
- Confirmed that cell titles like `reddit.com -> old.reddit.com` as example would not be translated

iPad Example | iPad Example | iPhone Example | iPhone Example
-|-|-|-
![IMG_0449](https://user-images.githubusercontent.com/17885425/179296079-bd5da7b2-9d25-4880-8c99-51e04cab5e67.PNG) | ![IMG_0450](https://user-images.githubusercontent.com/17885425/179296111-60bdfec1-7ff4-4639-bb5e-698a1311d94a.PNG) | ![IMG_3262](https://user-images.githubusercontent.com/17885425/179296321-84624216-129b-4e75-ba42-f0233d4992b8.PNG) | ![IMG_3263](https://user-images.githubusercontent.com/17885425/179296328-7db7cdbf-1138-4871-ab14-364f8256a815.PNG)

Redirects

- Ensured that enabling the redirect toggle for `reddit` will redirect user to `old reddit` frontend
- Ensured that user is able to bypass the redirect logic and view the new reddit by entering `new.reddit.com` for the domain
- Ensured that enabling the direct toggle for `npr` will redirect users to `text.npr.org` frontend
- Ensured that loading `reddit.com` or `npr.org` will not redirect to alternate frontends if switch is disabled

<table>
<tr><td>


https://user-images.githubusercontent.com/17885425/179299658-444c3005-522b-46d2-a56a-7fda77f4edc7.MP4


</td><td>


https://user-images.githubusercontent.com/17885425/179299710-cf36ddc9-a15a-42ba-b40d-921745e430ad.MP4


</td></tr>
</table>

Tabs/Share link

- Ensured open url via `share link` will behave accordingly (redirect if switch enabled)
- Ensured users can load the alternate frontend urls in `private mode`
