### ISSUE TITLE
Brave Search - Make Default in more countries

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#5661]
### Description: 
In addition to the existing 5 countries, please make Brave Search the default search engine for:

- Austria
- Spain
- Mexico

**Comment by Uni-verse** [comment]
Verified using version `1.41 (22.7.11.19)`

Test Devices:
`iPhone 12` | `iOS 15.5`
`iPhone X` | `iOS 14.4.2`
`iPad (7th Gen)` | `iOS 15.5`

- Verified Brave Search is default in the following regions.

Austria: 

iPhone | iPhone | iPad | iPad
-|-|-|-
![IMG_3256](https://user-images.githubusercontent.com/17885425/179096163-f1b82fb2-4f55-4a6a-8526-3d6c4f4b076f.PNG) | ![IMG_3257](https://user-images.githubusercontent.com/17885425/179096174-bbc01342-227f-409c-844c-a9b20177c40f.PNG) | ![IMG_0441](https://user-images.githubusercontent.com/17885425/179096205-09ebaeea-a827-48c6-b77e-edb3adff7367.PNG) | ![IMG_0442](https://user-images.githubusercontent.com/17885425/179096226-977a7cc8-a3f3-4ab5-bbc3-dcf889743616.PNG)

Spain: 

iPhone | iPhone | iPad | iPad
-|-|-|-
![IMG_3258](https://user-images.githubusercontent.com/17885425/179096944-0765df89-c9f1-456a-9571-65586fdcb0a5.PNG) | ![IMG_3259](https://user-images.githubusercontent.com/17885425/179096953-a0c214cb-d2b7-4eb8-a654-c4a45b2c5915.PNG) | ![IMG_0443](https://user-images.githubusercontent.com/17885425/179096992-1364bd05-92a5-4b6a-bad5-3ee3e7f2e6ea.PNG) | ![IMG_0444](https://user-images.githubusercontent.com/17885425/179096999-f8b555ec-8627-4ec0-af92-dc65c7c7abff.PNG)


Mexico: 

iPhone | iPhone | iPad | iPad
-|-|-|-
![IMG_3260](https://user-images.githubusercontent.com/17885425/179098252-4d1bbb3a-a935-4829-937d-49e6ddf0e8cf.PNG) | ![IMG_3261](https://user-images.githubusercontent.com/17885425/179098275-9e27cb02-73a3-4247-8c30-8f9afba1d8ce.PNG) | ![IMG_0445](https://user-images.githubusercontent.com/17885425/179098297-fb2b6d5d-b1c9-4e67-aacc-539424cba385.PNG) | ![IMG_0446](https://user-images.githubusercontent.com/17885425/179098300-dbb5ab85-f8d9-49c7-8494-42b23a28b779.PNG)
