### ISSUE TITLE
Full text not shown on button in search promo in some non-US languages (iOS 14)

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#5662]
### Description: 
Full text not shown on button in search promo, specifically in Polish where there would be more characters (iOS 14)

iOS 15 | iOS 14
-|-
![IMG_3224](https://user-images.githubusercontent.com/17885425/177864711-a20755aa-0741-4ab7-aabc-1a0a86d69d17.PNG) | ![IMG_2728](https://user-images.githubusercontent.com/17885425/177864783-426379ae-d4a8-4b34-b308-5ed6f229fdd6.PNG)

### Steps to Reproduce 

Precondition: Set language to Polish (Polski)

  1. Clean install 
  2. Set default search engine to anything other than brave search
  3. Restart the app 
  4. Search for something in the URL box
  5. Observe search promo

**Actual result:** 
Button text doesn't encompass the whole description

**Expected result:**
Should show full description (3 words in polish, see above picture)

**Brave Version:** 
1.40.1 (22.7.5.21)

**Device details:** 
iPhone iOS 14

**Comment by Uni-verse** [comment]
Related to https://github.com/brave/brave-ios/issues/5644

**Comment by iccub** [comment]
We'll most likely address in 1.41, after the hotfix release

**Comment by Uni-verse** [comment]
Verified using version `1.41 (22.7.11.19)` on `iPhone X` running `iOS 14.4.2`

Using STR from https://github.com/brave/brave-ios/issues/5662#issue-1298061135 Seems like this is behaving differently on some versions of iOS 14. For example on iOS 14.5 & 14.7 the button is able to display the full text but not on an iPhone X running 14.4.2. However the requirement is satisfied on all iOS 14 devices in landscape orientation. 

- Ensured full text is shown on button in search promo on iOS 14.5+ devices
- Ensured full text is displayed in landscape mode on all iOS 14 devices.
- Ensured this change does not impact iOS 15 and Tablets on iPadOS 15 and users are able to use the search promo including both dismiss cases. 

iOS 14.5 | iOS 14.4.2
-|-
<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/179077143-c42ec5fb-75d8-478f-b09f-200e34896f37.png"> | <img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/179077016-cf7fe868-bc62-449b-af60-9b84abb0fb49.PNG">
