### ISSUE TITLE
CarPlay crash 

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5669]
Reported here https://community.brave.com/t/iphone-carplay-bug/409687/5

Also can be seen in xcode crash organizer
[2022-07-05_15-30-49.4502_+0300-67479c3bbc26e3ad5aa09267aaf0d0090824039f.txt](https://github.com/brave/brave-ios/files/9084936/2022-07-05_15-30-49.4502_%2B0300-67479c3bbc26e3ad5aa09267aaf0d0090824039f.txt)

**Comment by Uni-verse** [comment]
Verified using `1.41 (22.7.22.16)` on `iPhone 12` Pro with `iOS 15.5`

- Confirmed CarPlay crash is not reproducible on launch. 
- Confirmed connecting and disconnecting to CarPlay is successful.

CarPlay Sim | Brave App | Mobile Carplay
-|-|-
![Screen Shot 2022-07-22 at 2 36 04 PM](https://user-images.githubusercontent.com/17885425/180571948-e5c9ae8c-d0ec-44be-98e6-684485e1985e.png) | ![IMG_3305](https://user-images.githubusercontent.com/17885425/180572412-c317c1e2-22c4-4412-aa0e-c2b0778163ca.PNG) | ![IMG_3306](https://user-images.githubusercontent.com/17885425/180572419-e05a4f0c-54b0-400d-844e-0335f6a6118f.PNG)

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 11` running `iOS 16` using `1.41 (22.7.22.16)`.

Downloaded/Installed `1.40. (22.6.29.0)` and added several videos from `YT` and reproduced the issue as Brave wouldn't launch and crashed when selecting it via `CarPlay` as per the following:

* https://youtu.be/KBrMhFXnA64

Upgraded to `1.41 (22.7.22.16)` using TF and confirmed that Brave launched via `CarPlay` and played the added videos via the `Playlist` without any issues as per the following:

* https://youtu.be/PUzLKLy3Za8
