### ISSUE TITLE
Page loaded in normal tab is shown upon migration when app is set to PB only

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#567]
### Description: 
Page loaded in normal tab is shown upon migration when app is set to PB only

### Steps to Reproduce 

1. Install 1.6.6. from appstore
2. Visit a few sites in new tabs on normal mode
3. Enable Pin 
4. Enable PB only from settings and keep empty tab
5. Upon launch after upgrade, webpage opened in first normal tab is loaded by default

**Actual result:** 
Page loaded in normal tab is shown upon migration when app is set to PB only

**Expected result:**
Should just open a blank private tab

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.12.04.23)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
This also happens in 1.7 alone, after app relaunch
