### ISSUE TITLE
Update icon for website redirects project

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5674]

**Comment by Sam-Sibley** [comment]
@iccub Here are the redirect icons:
[redirects icons.zip](https://github.com/brave/brave-ios/files/9129466/redirects.icons.zip)

**Comment by Sam-Sibley** [comment]
Let me know if the colors are not right as Im not 100% sure on what we use in production. So I made an educated guess based on what i can see in figma.

**Comment by iccub** [comment]
All good on our end @Sam-Sibley, thanks
