### ISSUE TITLE
Private tabs is lost during migration update when app is in background

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#568]
### Description: 
Private tabs is lost during migration update when app is in background

### Steps to Reproduce 
  1. Set 1.6.6 to be on normal tabs 
  2. Open a couple of private tabs and visit sites in them
  3. Background the app and upgrade to 1.7
  4. After upgrade launch, pin is enabled(#566) and private tabs opened are lost, focus is set to first normal tab

**Actual result:** 
Private tabs is lost during migration update when app is in background

**Expected result:**
Should retain the private tabs that were active when app was still in memory

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.12.04.23)

**Device details:** 
iPhone and iPad

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
This is expected behavior. This is basically a desktop browser upgrade, where it has to quit the app to upgrade. Since we don't save private browsing data, these cannot be recovered.
