### ISSUE TITLE
Page load seems slow after migration

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#569]
### Description: 
Page load seems slow after migration

### Steps to Reproduce 
  1. Have a good amount of tabs and browsing history on 1.6.6
  2. Background the app and upgrade to 1.7 (18.12.04.23)
  3. Launch browser post ugprade and open a new tab and visit a site, page load seems pretty slow

**Actual result:** 
Page load seems slow after migration

**Expected result:**
Page load shouldn't be compromised because of upgrade

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.12.04.23)

**Device details:** 
Reproduced it on iPhone and iPad

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
This is pretty ambiguous, does this happen after relaunching and everything?

**Comment by srirambv** [comment]
I only experienced this right after upgrade launch. Removing app from memory and relaunching did bring in some improved speed.

**Comment by jhreis** [comment]
Since we have already released, and almost all users have upgraded, closing this as unnecessary.
