### ISSUE TITLE
Favicons not cache properly and not pulling from the cache

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#5692]
### Steps to Reproduce 
  1. Visit any website.
  2. Favicons are downloaded correctly.
  3. Close the tab.
  4. Visit History, Bookmarks, or make a search (but do not submit the search, we only care about the suggestions)

**Actual result:** 
- Application makes a request for all icons

**Expected result:**
- Application should not request favicons again. It should pull favicons from cache for sites visited in the past.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
- Easily reproduced

**Brave Version:** 
- Any

**Device details:** 
- Any

**Website problems only:**
- Nope

**Comment by Uni-verse** [comment]
Verified using `1.41 (22.7.19.13)`

Test Devices:
`iPhone 12 Pro` | `iOS 15.5`
`iPhone X` | `iOS 14.4.2`
`iPad (7th Gen)` | `iPadOS 15.5`

Using test plan in https://github.com/brave/brave-ios/issues/5692#issue-1305268976

- Verified application pulls favicons from cache when necessary

Example | Example | Example
-|-|-
![IMG_0454](https://user-images.githubusercontent.com/17885425/179813700-a0340da5-f1bf-43a2-87be-0e4fcd528de8.PNG) | ![IMG_3275](https://user-images.githubusercontent.com/17885425/179813709-d65e8b2c-7f07-447e-86bc-623a39da5ed1.PNG) | ![IMG_3276](https://user-images.githubusercontent.com/17885425/179813729-65490bd1-aa0a-4d19-be9e-042d3fa72b57.PNG)
