### ISSUE TITLE
Allow tapping near bottom of screen while toolbars are collapsed to expand

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#5695]
### Description: 

Similar to Safari, when the URL bar + toolbars are collapsed, we should allow tapping near the bottom of the screen to expand the toolbar

**Comment by Uni-verse** [comment]
Verified using `1.42 (22.8.8.19)`

Test Devices:

iPhone 12 & XR iOS 15.5
iPad (7th Gen) iOS 15.5
iPhone X iOS 14.4.2

Based on context in https://github.com/brave/brave-ios/issues/5695#issue-1305310829

- Verified when toolbars are collapsed, user can tap on the bottom end of the screen to expand the `top + bottom toolbars.`
- Verified new change to tap-to-expand toolbars in `private mode`.
- Verified top toolbar will expand when user taps on bottom end of the screen when in `landscape orientation.`
- Verified toolbars will expand/collapse normally when `tab bar is disabled`.
- Verified toolbars will expand/collapse normally when bookmarks shortcut is enabled for the `URL bar` and `Rewards icon is hidden`.

UI behavior

<table><tr><td>

https://user-images.githubusercontent.com/17885425/183920130-650cc92f-202e-414e-bd9c-79fd7c806f64.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/183923358-277936d2-0cdc-4d16-a563-e2e04bbbd9d2.MP4

</td></tr></table>

**Comment by ego-lay-atman-bay** [comment]
I'm actually experiencing this same issue.

my device: iPad pro (10.5-inch) iOS (iPadOS) 15.3.1

Brave Version 1.42 (22.8.15.22)

**Comment by kylehickinson** [comment]
@ego-lay-atman-bay Hi, what issue are you experiencing in particular? This issue was for adding the feature to tap the bottom to expand. Perhaps you meant to comment on https://github.com/brave/brave-ios/issues/5846? If so, that issue has been fixed and should be in the next released version of Brave (1.43)

**Comment by ego-lay-atman-bay** [comment]
@kylehickinson The issue I'm having is not that, in fact I didn't notice that https://github.com/brave/brave-ios/issues/5846 was an issue with me. The problem I have is, I cannot tap things on the bottom of the page, or anything that is at the bottom of the screen, even when there is no toolbar. 

after looking back at this issue, I now realize it's not the same thing. I might want to create a new issue.

**Comment by kylehickinson** [comment]
@ego-lay-atman-bay the problem you explained sounds exactly like the issue I linked, which will be fixed in the upcoming release
