### ISSUE TITLE
Call `OnOnboardingShown` when Wallet onboarding is shown (P3A prep)

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-ios#5699]
### Description: 

When the Wallet onboarding is shown, `OnOnboardingShown` in `BraveWalletService` should be called. This will ensure the new P3A question (added in brave/brave-core#14081) for onboarding conversion works (once P3A is implemented for iOS).

**Comment by StephenHeaps** [comment]
Onboarding P3A handled with https://github.com/brave/brave-browser/issues/35981.
