### ISSUE TITLE
Translated text should have a line break in shields

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#570]
### Description: 
Translated text should have a line break in shields

### Steps to Reproduce 
  1. Switch device language to French
  2. Visit any site and open up shields
  3. Shields panel cover 80% of UI

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/49508882-e4684400-f8a9-11e8-8b41-e894c261e141.png)

**Expected result:**
Shields panel should not cover 80% of browser UI

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.12.04.23)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Liunkae** [comment]
Is this a problem that needs to be resolved on Transifex?

**Comment by LaurenWags** [comment]
Is this only applicable for iPhones since iPads have bigger screens?

**Comment by LaurenWags** [comment]
For reference, this is what I'm seeing on iPad with each orientation:
![img_0258](https://user-images.githubusercontent.com/28145373/51924436-061e0d00-23bb-11e9-8b2e-0d07689160dd.PNG)
![img_0259](https://user-images.githubusercontent.com/28145373/51924463-0dddb180-23bb-11e9-9c55-056e2faa014b.PNG)

**Comment by srirambv** [comment]
@LaurenWags I think this is iPhone specific. Since shields covers most of the UI. Updated the issue label to mark it as iPhone specific
