### ISSUE TITLE
Issue with some request URLs not being parsed properly when request blocking

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#5700]
### Description: 
The issue is with some characters that are allowed in JS URL that are not allowed with swift URL

### Steps to Reproduce 
  1. Use debug mode
  2. Go around the amazon website (click links, scroll, etc)
  3. Should get an assertion failure (this crash only happens on debug mode, does not crash in production)

**Actual result:** 
Assertion failure triggered

**Expected result:**
No assertion should be triggered

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Putting `QA/No` as this mostly affects our debug builds
