### ISSUE TITLE
Internal #883

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#5702]
https://github.com/brave/internal/issues/883

**Comment by Uni-verse** [comment]
Verified using `1.41 (22.7.19.13)`

Test Devices:
`iPhone 12 Pro` | `iOS 15.5`
`iPhone X` | `iOS 14.4.2`
`iPad (7th Gen)` | `iPadOS 15.5`

Using Test Plan in https://github.com/brave/internal/issues/883#issue-1306396773

New Profile:

- Verified enrolled status shows `Enrolled` in rewards internals page
- Verified promotions claiming in debug menu

Example | Example | Example
-|-|-
![IMG_3277](https://user-images.githubusercontent.com/17885425/179825719-803a1f5f-c8bd-4115-928f-044c841fc2c5.jpg) | ![IMG_3279](https://user-images.githubusercontent.com/17885425/179825641-81d5b410-6fc3-4fe8-a436-bfb960558582.jpg) | ![IMG_3278](https://user-images.githubusercontent.com/17885425/179826924-81e7909b-2527-43ac-8bc1-794bce83e92f.PNG)

Upgraded Profile: 

- Verified enrolled state is `Not Enrolled` in internals page on a new profile using `1.40`
- Verified enrolled state is `Enrolled` in internals page after upgrading from `1.40` to `1.41`

1.40 | 1.41
-|-
![IMG_3281](https://user-images.githubusercontent.com/17885425/179825799-bef2b19c-9fc1-440c-b6cc-09d5dfec3d5a.jpg) | ![IMG_3282](https://user-images.githubusercontent.com/17885425/179825807-4b9a20f5-756e-44d0-91e0-79dacc39d49e.jpg)
![IMG_0455](https://user-images.githubusercontent.com/17885425/179826276-1df4c40c-5c3b-4740-b113-8ab4b34a6bbd.PNG) | ![IMG_0456](https://user-images.githubusercontent.com/17885425/179826295-a54d082a-586e-4ef4-991b-86b3685ab58e.jpg)
