### ISSUE TITLE
Preloaded favicons missing after loading url

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#5713]
### Description: 
Favorites missing favicon when opening NTP after visiting URL

https://user-images.githubusercontent.com/17885425/179622294-d0f025d6-0309-4636-88a5-cf2efa1a4bb7.MP4

### Steps to Reproduce 
  1. Clean install
  2. Tap on Youtube favorite that is preloaded
  3. Open NTP
  4. Repeat with other favorites

**Actual result:** 
See Description

**Expected result:**
Favicon is displayed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy Reproduced, follow STR

**Brave Version:** 
1.41 (22.7.18.17)

**Device details:** 
iPhone 12 Pro

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Fixed here https://github.com/brave/brave-ios/pull/5708

**Comment by Uni-verse** [comment]
Verified per https://github.com/brave/brave-ios/issues/5692#issuecomment-1189370816
