### ISSUE TITLE
Renamed favorites are not showing site favicons

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#572]
### Description: 
Renamed favorites are not showing site favicons

### Steps to Reproduce 
  1. Open any site 
  2. Add it to favorite
  3. Open a new tab, click on added favorite, edit the favorite name to any name

**Actual result:** 
Renamed favorites are not showing site favicons
![img-20181130-wa0003](https://user-images.githubusercontent.com/38657976/49514842-47160b80-f8bb-11e8-8ef3-b1fb1b9b53e4.jpg)

**Expected result:**
Renamed favorites should show site favicons

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
80 % Reproducible rate

**Brave Version:** 
1.7 (18.11.30.03)

**Device details:** 
iPhone 8 (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by kylehickinson** [comment]
Ref #471 (Same underlying issue)

**Comment by kylehickinson** [comment]
Please re-test, as I believe this is fixed

**Comment by kylehickinson** [comment]
Replicated by changing pre-set favourite's URL (youtube.com) to another site that I already had visited therefore should already have a favicon for (GitHub.com)

![simulator screen shot - iphone x - 2018-12-19 at 14 45 12](https://user-images.githubusercontent.com/529104/50243983-b2240f80-039c-11e9-94f5-5dd123111d06.png)

**Comment by jhreis** [comment]
Not sure updating favicon dynamically with an edited URL is super necessary. Does this persist even after revisiting that site?

**Comment by srirambv** [comment]
@jhreis yes after revisiting the site favicon isn't updated.

**Comment by iccub** [comment]
Seems to be working now :) closing
