### ISSUE TITLE
Update user rating prompt logic

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5722]
details tba

**Comment by timchilds** [comment]
@iccub here is the Android spec for this:
https://docs.google.com/document/d/1SN4Tdu0WUkyvnCkuVy76T34GJgNH3fBGEtgobme4YS4/edit?usp=sharing

I think we can likely re-use all/some of the logic. But unsure if iOS has an equivalent API for displaying the review prompt in-app? https://developer.android.com/guide/playcore/in-app-review

cc @anthonypkeane @Sam-Sibley

**Comment by iccub** [comment]
thanks @timchilds

**Comment by Uni-verse** [comment]
Removing `QA/Yes` label as QA were not able to test the user rating prompt logic in TF builds.

CC: @kjozwiak
