### ISSUE TITLE
Add network picker to add custom asset screen

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5725]
### Description: 

Currently adding a custom asset is done on the selected network. We should add a picker to the UI to support adding for a network that is not currently selected.

Desktop for example:
<img width="555" alt="desktop add custom asset" src="https://user-images.githubusercontent.com/5314553/180065837-2f409240-b3ba-4980-979d-38729451ebc0.png">

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.45.2 (22.11.23.16)
- Verified steps from [#6346](https://github.com/brave/brave-ios/pull/6346)
- Verified Add custom token option opens up a new UI for adding tokens/NFT
- Verified a new network selector is shown on add custom token/NFT screen
- Verified adding token address automatically pulls in from token registry for supported tokens 
- Verified adding token address where its not available in token registry doesn't auto-populate the token details
- Verified able to successfully add an NFT 
- Verified adding a custom token without Icon URL and Coingecko ID adds the token successfully but doesn't show the price in token details view and no icon is shown in portfolio
- Verified adding `FRAX` for Avalanche C-Chain automatically pre-populates token details from token registry
- Verified switching network from Avalanche to Ethereum mainnet hides the token on Ethereum mainnet
- Verified adding `Bitcoin Avalanche Bridged` to Avalanche C-Chain without Icon URL and Coingecko ID still allows to add token but doesn't show the price or icon 
- Encountered [#6467](https://github.com/brave/brave-ios/issues/6467) & [#6468](https://github.com/brave/brave-ios/issues/6468)

![image](https://user-images.githubusercontent.com/17010094/203609856-5bb9a71d-46f1-4cca-9f0d-8f92214e385b.png) | ![image](https://user-images.githubusercontent.com/17010094/203609872-4464d6c8-1134-409f-9ba6-1c03e6bf3218.png) | ![image](https://user-images.githubusercontent.com/17010094/203609899-18ffe736-b9e3-4d31-aaf0-4311685e3116.png) | ![image](https://user-images.githubusercontent.com/17010094/203609967-a3a3f782-580e-41d4-992e-2c7c428dd6ff.png) | ![image](https://user-images.githubusercontent.com/17010094/203609928-a4b97b07-5a4e-4701-a1e0-9b790acfff82.png) | ![image](https://user-images.githubusercontent.com/17010094/203609948-865cad8e-a84a-437a-960c-230e815ed9b9.png)
-- | -- | -- | -- | -- | --
-----------
Verification passed on iPhone XR with iOS 15.6.1 running 1.45.2 (22.11.23.16)
- Verified steps from [#6346](https://github.com/brave/brave-ios/pull/6346)
- Verified Add custom token option opens up a new UI for adding tokens/NFT
- Verified a new network selector is shown on add custom token/NFT screen
- Verified adding token address automatically pulls in from token registry for supported tokens 
- Verified adding token address where its not available in token registry doesn't auto-populate the token details
- Verified able to successfully add an NFT 
- Verified adding a custom token without Icon URL and Coingecko ID adds the token successfully but doesn't show the price in token details view and no icon is shown in portfolio
- Verified adding `FRAX` for Avalanche C-Chain automatically pre-populates token details from token registry
- Verified switching network from Avalanche to Ethereum mainnet hides the token on Ethereum mainnet
- Verified adding `Bitcoin Avalanche Bridged` to Avalanche C-Chain without Icon URL and Coingecko ID still allows to add token but doesn't show the price or icon 
- Encountered [#6467](https://github.com/brave/brave-ios/issues/6467) & [#6468](https://github.com/brave/brave-ios/issues/6468)

![image](https://user-images.githubusercontent.com/17010094/203611429-0c564b5a-4019-4334-8110-1802e3ead90b.png) | ![image](https://user-images.githubusercontent.com/17010094/203611471-2d4c38b6-e732-401d-afb5-dba20ff41ab4.png) | ![image](https://user-images.githubusercontent.com/17010094/203611499-b8095556-bb87-4034-a28e-7b8e3e502e38.png) | ![image](https://user-images.githubusercontent.com/17010094/203611527-6e47d6dd-a6eb-487b-8138-8cf34b1db6b4.png) | ![image](https://user-images.githubusercontent.com/17010094/203611588-823facde-7fd6-4a65-af96-339363e8d8a3.png) | ![image](https://user-images.githubusercontent.com/17010094/203611571-3432b737-ceba-45cb-a42f-4d06ff25675e.png)
-- | -- | -- | -- | -- | --

----------
Verification passed on iPad Pro with iOS 16.1 running 1.45.2 (22.11.23.16)
- Verified steps from [#6346](https://github.com/brave/brave-ios/pull/6346)
- Verified Add custom token option opens up a new UI for adding tokens/NFT
- Verified a new network selector is shown on add custom token/NFT screen
- Verified adding token address automatically pulls in from token registry for supported tokens 
- Verified adding token address where its not available in token registry doesn't auto-populate the token details
- Verified able to successfully add an NFT 
- Verified adding a custom token without Icon URL and Coingecko ID adds the token successfully but doesn't show the price in token details view and no icon is shown in portfolio
- Verified adding `FRAX` for Avalanche C-Chain automatically pre-populates token details from token registry
- Verified switching network from Avalanche to Ethereum mainnet hides the token on Ethereum mainnet
- Verified adding `Bitcoin Avalanche Bridged` to Avalanche C-Chain without Icon URL and Coingecko ID still allows to add token but doesn't show the price or icon 
- Encountered [#6467](https://github.com/brave/brave-ios/issues/6467) & [#6468](https://github.com/brave/brave-ios/issues/6468)

![image](https://user-images.githubusercontent.com/17010094/203614705-3ceb9102-f0d5-4b54-8c49-9edaf8436335.png)  | ![image](https://user-images.githubusercontent.com/17010094/203614729-dbb2b873-299f-4310-ad90-d9ae5b7e70a8.png) | ![image](https://user-images.githubusercontent.com/17010094/203614819-75fc8f19-cc21-4c3f-9005-8d9db7ca5a15.png) | ![image](https://user-images.githubusercontent.com/17010094/203614800-ecb2deee-13c9-4989-8e58-66a74ffc2b9e.png) | ![image](https://user-images.githubusercontent.com/17010094/203614756-2b383b85-b12e-4af1-82e9-2751a820632b.png) | ![image](https://user-images.githubusercontent.com/17010094/203614836-d83a39b0-c264-49f2-837a-afe987fe948e.png)
-- | -- | -- | -- | -- | --
