### ISSUE TITLE
Unable to join raffles on poap.fun dapp

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5727]
### Description: 

Report received that the poap.fun dApp doesn’t recognize POAP that connected wallet has. And cannot join raffle even if the wallet has the specific POAP to join the raffle.

More info: https://bravesoftware.slack.com/archives/C02S9LFEXU4/p1658402959515739

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by StephenHeaps** [comment]
The `Connect Wallet` button not always showing the connected wallet address & not recognizing owned POAPs will be resolved with https://github.com/brave/brave-ios/pull/7029.

The `Join Raffle` button not prompting a signature request is caused by an incorrect response to some Ethereum dapp requests on iOS. This will be resolved with https://github.com/brave/brave-browser/issues/28843.

**Comment by StephenHeaps** [comment]
QA/Blocked until `Join Raffle` button issue is resolved

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.50 (23.4.171.6)
- Verified test plan from [#7029](https://github.com/brave/brave-ios/pull/7029)

iPhone 7+ (iOS 15.7.3) | iPad Pro (iOS 16.5 Beta)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/233073762-d2fdd768-6cdc-4027-83bc-7cf590175b60.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/233073737-6da49887-f433-4856-84b7-2da950a72797.png>
