### ISSUE TITLE
Add filter lists enable/disable screen similar to desktop

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#5729]
### Description: 
The following screen needs to be implemented in iOS:
<img width="709" alt="Screen Shot 2022-07-21 at 4 20 55 PM" src="https://user-images.githubusercontent.com/909331/180324777-4d881ba4-94d3-4093-a2ef-ba9310714acd.png">

### Additional Information
Security review: https://github.com/brave/security/issues/975

**Comment by ryanbr** [comment]
How much of the ios blocking functionality is supported? @cuba

**Comment by Uni-verse** [comment]
Verified using version `1.44 (22.10.7.17)`

`iPhone 12` running `iOS 16.x`
`iPhone XR` running `iOS 15.5`
`iPhone X` running `iOS 14.4.2`
`iPad (7th Gen)` running `iPadOS 15.7`

Spec: https://docs.google.com/document/d/1EWPRDNt3tqxnTjydZXdeiI75Ene0BMEajE4ZHFQCTa8/edit?usp=sharing

**Acceptance Criteria:**

1. Add a new Brave setting to “Suppress `switch to app` notifications and prompts"
2. Enabled by default (Privacy Settings)
3. Content Filtering setting page (Filter lists)
4. Fanboy's Mobile Notifications List enabled by default
5. Switch to app suppression functionality

- Verified `Block 'Switch to App' Notices` switch is present under Other privacy settings section in brave shields settings and is enabled by default
- Verified `Content Filtering` page is displayed under `global default shield` settings
- Verified user is able to toggle switches in the filter lists page 
- Verified switch selections persist if user `relaunches` brave app
- Verified `Fanboy's Mobile Notification List` is `enabled` by default in the settings page and in the content filters page
- Verified navigating to` reddit` and `linkedin` pages will not prompt user to switch to app on default settings
- Verified disabling `Switch to App` switch will show the switch to app prompts - https://github.com/brave/brave-ios/issues/6145
- Verified the `Fanboys Mobile Notification List` under `Content filters` will have the same state as the setting under privacy settings (Block 'Switch to App' Notices). User is able to enabled and disable the switch from either page.

Filter Lists | Content Filtering | LinkedIn Page | Privacy Settings
-|-|-|-
![IMG_3751 3](https://user-images.githubusercontent.com/17885425/194726287-6f99a993-74bb-48f3-bfe6-bcd8e2436426.PNG) | ![IMG_3754 3](https://user-images.githubusercontent.com/17885425/194726293-48539968-1ba1-4fd6-b5ce-bf5836c00e19.PNG) | ![IMG_3860](https://user-images.githubusercontent.com/17885425/194726314-7f9665ad-f2e3-471f-8b41-33f292e2c4f6.PNG) | ![IMG_3861](https://user-images.githubusercontent.com/17885425/194726406-0ae3b551-3f3b-429f-8d5b-68b03ddd1261.PNG)

Enabled (Privacy Settings) | Disabled (Privacy Settings) | Content Filters Setting | Filters
-|-|-|-
![IMG_0621](https://user-images.githubusercontent.com/17885425/194726467-fab87635-a54f-42c0-abde-0cad58cba12c.PNG) | ![IMG_0623](https://user-images.githubusercontent.com/17885425/194726468-72639da6-2fc8-490f-8bba-bf30c0174658.PNG) | ![IMG_0624](https://user-images.githubusercontent.com/17885425/194726469-a648114b-0032-427b-af00-bca27f3bbf68.PNG) | ![IMG_0626](https://user-images.githubusercontent.com/17885425/194726944-4b90208e-7a26-4e62-b119-73c22029d6cd.PNG)
