### ISSUE TITLE
Add debounce setting to shields

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#5730]
### Description: 
Add a setting in shields which will enable debouncing
Note:
1. Iff debounce and de-amp is enabled apply de-amp de-bounce rules 
2. When de-amp is disabled, but debounce is enabled, still apply non-de-amp debounce rules
3. The shield setting will likely exist somewhere on global shield settings near the de-amp setting
4. Global setting only. No setting per domain.

### Additional Information
Related to the following desktop ticket: https://github.com/brave/brave-browser/issues/24020

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 16.2` using version `1.48 (23.2.10.14)`

Based on test plan used in https://github.com/brave/brave-ios/pull/6377#issue-1445504592 and the acceptance criteria in
https://github.com/brave/brave-ios/issues/5730#issue-1313876545

- Ensured that debounce setting is shown under global shield settings
- Ensured deferred referrer shown on test page is `https://dev-pages.brave.software/`
- Ensured that de-bounce rules are applied when `Auto-Redirect Tracking URLs` is enabled
- Ensured that de-bounce rules are appled when `Auto-Redirect Tracking URLs` is enabled and de-AMP is disabled
- Ensured that de-bounce rules are not applied when`Auto-Redirect Tracking URLs` is disabled

**Scenario 1 (De-bouncing and De-AMP enabled)**

1. Ensured Auto-Redirect AMP Pages is enabled in global settings
2. Ensured Auto-Redirect Tracking URLs is enabled in global settings
3. Load test page `https://dev-pages.brave.software/navigation-tracking/debouncing.html`
4. Run default test

Example | Example
-|-
![IMG_4475](https://user-images.githubusercontent.com/17885425/218568554-8042d37a-ff12-4018-ac7c-674ac853286f.PNG) | ![IMG_4476](https://user-images.githubusercontent.com/17885425/218568572-6c5bc1ba-b20b-4782-ba08-fd2ed8adba33.PNG)

**Scenario 2 (Debouncing enabled, De-AMP disabled)**

1. Enabled `Auto-Redirect Tracking URLs` 
2. Disabled `Auto-Redirect AMP Pages`
3. Load test page `https://dev-pages.brave.software/navigation-tracking/debouncing.html`
4. Run default test

Example | Example
-|-
![IMG_4479](https://user-images.githubusercontent.com/17885425/218569410-28cb9cab-9db6-4d9c-b18d-e96cb2b1725c.PNG) | ![IMG_4480](https://user-images.githubusercontent.com/17885425/218569413-a30d0b06-6b8d-4c24-82b3-8bf6b67f941a.PNG)


**Scenario 3 (Debouncing disabled, De-AMP disabled)**

1. Disabled `Auto-Redirect Tracking URLs` 
2. Disabled `Auto-Redirect AMP Pages`
3. Load test page `https://dev-pages.brave.software/navigation-tracking/debouncing.html`
4. Run default test

Example | Example
-|-
![IMG_4481](https://user-images.githubusercontent.com/17885425/218569814-4bbbb506-7d36-4911-bd8d-fa06457c1cc5.PNG) | ![IMG_4477](https://user-images.githubusercontent.com/17885425/218569837-674e7879-bb44-4df5-9a4a-157656e29b91.PNG)

**Comment by Uni-verse** [comment]
Verified on `iPad (9th Gen)` running `iPadOS 15.6.1` using version `1.48 (23.2.10.14)`

Based on test plan used in https://github.com/brave/brave-ios/pull/6377#issue-1445504592 and the acceptance criteria in
https://github.com/brave/brave-ios/issues/5730#issue-1313876545

- Ensured that debounce setting is shown under global shield settings
- Ensured deferred referrer shown on test page is `https://dev-pages.brave.software/`
- Ensured that de-bounce rules are applied when `Auto-Redirect Tracking URLs` is enabled
- Ensured that de-bounce rules are appled when `Auto-Redirect Tracking URLs` is enabled and de-AMP is disabled
- Ensured that de-bounce rules are not applied when`Auto-Redirect Tracking URLs` is disabled


Scenarios based on https://github.com/brave/brave-ios/issues/5730#issuecomment-1428651981

Scenario 1 | Scenario 2 | Scenario 3
-|-|-
![IMG_0113 2](https://user-images.githubusercontent.com/17885425/218571290-447db253-5981-4a3c-b028-4e4e677675ae.PNG) | ![IMG_0114 2](https://user-images.githubusercontent.com/17885425/218571318-5a968ec4-ba04-4c18-b369-6390c6e16f0a.PNG) | ![IMG_0115 2](https://user-images.githubusercontent.com/17885425/218571322-50268cb7-3181-401e-8f2e-29091ba6cbc9.PNG)
