### ISSUE TITLE
Hide recovery seed phrase when app is backgrounded

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5744]
### Description: 

When the application is backgrounded, the recovery seed phrase should be hidden so it's not visible in the app switcher.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.42 (22.8.8.19)
- Verified steps from [#5755](https://github.com/brave/brave-ios/pull/5755)
- Verified recovery seed phrase is hidden when backgrounded
- Verified for both `Verify recovery phrase` screen and `Your recovery phrase` screen


iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/183714212-ccfe5031-00b5-47ce-8dd5-33e8e422e15c.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/183714130-21956065-3846-4f88-ace9-77fff5897236.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/183714313-6d3f1fad-bf7f-4f37-96e3-e0fd5292ca31.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/183714251-da2324be-ac4d-4ff5-aa5c-3bf960be3fc2.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/183714106-b58de9b6-a51c-49ba-ab0b-04a69e5657e4.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/183714364-ee195775-a505-4412-9d1b-74858601c115.png>
