### ISSUE TITLE
Bump BraveCore to 1.42.x

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#5747]
Bumping Brave-Core to latest 1.42.x

As per [brave-browser Release schedule](https://github.com/brave/brave-browser/wiki/Brave-Release-Schedule):
Channels will migrate July 26, 2022, Released on August 2, 2022, using Chromium 103

**Comment by iccub** [comment]
Reopening until we merge a RC build of 1.42

**Comment by iccub** [comment]
Looks like previous build was RC already, closing. Going to reference this ticket with the latest brave-core pull
