### ISSUE TITLE
Wallet: same address error message doesn't clear up after selected account changed.

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5773]
### Steps to Reproduce 
  1. make sure your selected network is Solana
  2. go to send to check what the selected account is. and copy the same address
  3. paste the copied address in the send address field
  4. observe `The receiving address is your own address` error message appears
  5. change selected account to another 

**Actual result:** 
the old error message didnt disappear 

**Expected result:**
address field should revalidate again after selected account changed.

**Reproduces how often:** [Easily reproduced]

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.42 (22.8.8.19)
- Verified steps from issue description
- Verified same address error message is cleared when a different account is selected
- Verified same address error message changes to invalid ETH address when an Eth account is selected

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 16 Beta 3)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/184075816-595fdc87-4171-4d9c-b9fc-6ccb1c557843.mp4> | <video src=https://user-images.githubusercontent.com/17010094/184075883-28a81702-44a6-4589-9054-5cf93d9a724b.mp4> | <video src=https://user-images.githubusercontent.com/17010094/184075911-57c4457f-0c13-4875-8854-501888e36d58.mp4>
