### ISSUE TITLE
With background play enabled, paused video resumes play when navigating away from the tab

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5775]
### Steps to Reproduce 
  1. Enable background audio playback
  2. Open a youtube video
  3. Pause it
  4. Switch to another tab

**Actual result:** 
Audio resumes playing

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by davidcollini** [comment]
Thank you !

**Comment by Uni-verse** [comment]
Verified using `1.42 (22.8.8.19)`

Test Devices:

iPhone XR iOS 15.5
iPad (7th Gen) iOS 15.5
iPhone X iOS 14.4.2

Using STR in https://github.com/brave/brave-ios/issues/5775#issue-1327485672

- Verified video play does not resume when switching tabs.
