### ISSUE TITLE
Wallet: Clear up logic for showing or hiding buy/send/swap options

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5776]
### Description: 
Currently we have wrong or partially correct logic to determine show or hide buy/send/swap options though out the wallet.

For Buy:
Mobile only support Buy with Wyre right now. 
1. we need to fetch buyable tokens using correct chain id with Wyre provider
2. after compare with desktop, currently there are three networks support buy with Wyre. They are Eth Mainnet, EVM Polygon Mainnet and EVM Acalanche Mainnet

For Send:
No restriction

For Swap:
User api from BraveWalletSwapService.isSwapSupported to show or hide swap option.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.42 (22.8.12.17)
- Verified steps from issue description
- Verified `Continue to Wyre` option is only shown for Ethereum network
- Verified correct account address and entered value is pre-populated in the Wyre url
- Verified when there is no input put in a default value for purchase is auto-filled
- Verified Send option is shown for all networks
- Verified Swap option is only shown for supported netwroks


iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/184596867-b7f63edb-780d-46d0-b089-9336a68e1104.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/184596827-005da09f-5ca6-4986-8c88-ad68650f1e47.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/184597116-af6a04f3-2c8b-4132-8166-2ee03b69d84d.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/184596883-702b0a84-bd8b-47da-a6bd-559ec75171da.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/184596816-09f4a6fc-259b-43fb-a5c8-963f6e8471b2.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/184597096-396555ac-02eb-4ef3-acd7-7b574ebc6101.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/184596899-4465a9d5-d709-4f27-b604-17908fa45c7d.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/184596848-69b157c1-6da4-44de-8ea0-0c851222cfc4.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/184597079-725720c5-29cf-4003-b44f-8032e43befdd.png>
