### ISSUE TITLE
Wallet Bug: User visible asset doesn't display correct fiat value in Solana

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5779]
![image](https://user-images.githubusercontent.com/1187676/182864052-7f260082-850a-47ef-88c0-67f1eedc8ed4.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.42 (22.611.22)
- Verified correct fiat value is shown for all assets


iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/184330820-6e779d80-1f8a-4617-9e77-062fc3fa9e36.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/184330956-ee242fbf-f36f-4c9e-a08c-f3d252dc135e.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/184331099-3d97a637-3a50-4df5-8950-c409c7828a3a.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/184330704-16a8fe59-b6e6-4086-996a-a088d0e40bbd.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/184330936-55ef6fc0-eb44-43c7-a343-5ad115536c35.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/184331065-bc464174-aae5-4428-b175-d6ec7b72983c.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/184330644-c0f05ebc-724c-4186-b3ab-97ac9dbf58b7.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/184330886-8aae445c-2bc7-4f3b-8aa2-82a416e72f8b.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/184331023-73fd4ea9-697d-402c-af2a-14ee53fd517c.png>
