### ISSUE TITLE
Wallet Bug: Can add the same account twice. 

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5780]
Once as a primary account and once as a secondary account. 

Steps to repro:
1. copy a private key in a different wallet on your HD path (e.g. account 2) (I used slope finance to export the key)
2. import the key into the wallet by pasting the private key in
3. add an account again without pasting anything in

![image](https://user-images.githubusercontent.com/1187676/182864660-3fed217f-a5ed-4d83-b7a9-8f67dca20567.png)

**Comment by StephenHeaps** [comment]
Investigating this issue, we are blocking importing a secondary account via private key. An alert will be shown with `Failed to import account` title and `Please try again` message for both Solana and Ethereum accounts.

The issue in question here is potentially not possible to be fixed, see more details here:
https://github.com/brave/brave-ios/pull/5719#issuecomment-1205588021
