### ISSUE TITLE
Wallet: Update buy with Wyre supported chain ids

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5781]
Polygon mainnet and Avalanche mainnet are excluded from the supported list due to core side bug [#24444](https://github.com/brave/brave-browser/issues/24444) 
After [#24444](https://github.com/brave/brave-browser/issues/24444) resolved, we will add these two networks back to the supported list.

**Comment by StephenHeaps** [comment]
Closing because we no longer use Wyre
