### ISSUE TITLE
Add Bridge to Aurora button on asset detail screen

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#5785]
Android version of https://github.com/brave/brave-browser/issues/24377

Add "Bridge to Aurora" button on all supported assets (this screen shows all supported assets including both highlighted and not highlighted)

![Image](https://user-images.githubusercontent.com/318119/182908142-5d532fb6-c791-4673-a594-9fb2b8c19901.png)

## Example placement

![Image](https://user-images.githubusercontent.com/318119/182908671-28f727b0-00cc-46f4-a939-c3717fe1949e.png)

## First time tapping on bridge button

![Image](https://user-images.githubusercontent.com/318119/182950994-4686f461-3ec9-4399-982d-3f4a8b667669.png)

(Lets show a system dialog that informs the user of the risks, the learn more button should be a system button and not a link in the message body. Three buttons [Continue, Cancel, Learn more], learn more link https://ethereum.org/en/bridges/#bridge-risk)

**Comment by nuo-xu** [comment]
as discussed in wallet channel we will show aurora bridge button for tokens
if the token has a bridge address or the token is a native token, and the token chainId is eth mainnet

**Comment by nuo-xu** [comment]
keep 1.59 milestone since it has been shipped out in 1.43 but not verified

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.2 running 1.60 (23.11.12.17)
- Verified steps from [#5873](https://github.com/brave/brave-ios/pull/5873)
- Verified `Bridge to Aurora` button is shown on supported tokens
- Verified `Bridge to Aurora` button is not shown on unsupported tokens
- Verified `Bridge to Aurora` button is only shown for Ethereum Mainnet
- Verified selecting `Do not show again` doesn't show the permission prompt when selecting `Bridge to Aurora` button
- Verified `Learn more about using Rainbow Bridge` loads `https://doc.aurora.dev/bridge/bridge-overview/`
- Verified `Learn how to reduce risk on Rainbow Bridge loads `https://rainbowbridge.app/approvals`

https://github.com/brave/brave-ios/assets/17010094/98fb9dc2-2d54-4763-9688-78f55d13df4d
