### ISSUE TITLE
Wallet: Remove url reference from send token to address field placeholder

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5786]
### Description: 

Sending to a url is not currently supported on iOS, but the placeholder copy in the to address field suggests we do. We should remove the reference to url until that is supported.

ref: https://github.com/brave/brave-ios/pull/5719#issuecomment-1205820793

![Enter address or url](https://user-images.githubusercontent.com/5314553/182963388-d5a87bbd-3863-4e82-8f09-dde426cec7bd.png) | ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-04 at 18 19 11](https://user-images.githubusercontent.com/5314553/182962353-d6023969-099a-4581-817f-1d591169b36e.png)
--|--

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.42 (22.8.8.19)
- Verified test plan from [##5788](https://github.com/brave/brave-ios/pull/5788)
- Verified refence of `URL` is removed from Send address field
- Verified entering a valid URL still shows the error message


iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/183668541-7b287ce0-74ac-4aa3-9bd3-576af259db27.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/183668421-48a93f09-9209-4242-a02a-050980227a81.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/183671401-fa0f5ab2-7658-43c5-a737-4e6452b772c4.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/183668569-6bf75d86-82c2-4b2e-b3b2-b90b3d835a86.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/183668405-4813c93d-12d0-48ad-9f53-861171811aea.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/183671440-50ad80e6-bb57-4fd1-840c-75cefc0f2661.png>
