### ISSUE TITLE
Wallet: Support sending transactions to a domain (ENS)

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5787]
### Description: 

Update send transaction view / logic to support sending to a domain.

ref / more info: 
https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1659646211852199
https://github.com/brave/brave-browser/issues/18681
https://github.com/brave/brave-browser/issues/18656

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.49 (23.3.9.17)
- Verified steps from [#7030](https://github.com/brave/brave-ios/pull/7030)
- Verified Offchain lookup works as expected
- Verified clicking on `Learn more` loads Wiki page about ENS lookup
- Verified Settings is set to `Ask` by default
- Verified setting is set to `Enabled` when `Use ENS Domain` is selected
- Verified when setting is set to `Disabled` , `offchainexample.eth` domain lookup fails 
- Encountered [#7079](https://github.com/brave/brave-ios/issues/7079)

iPhone 7+ (iOS 15.7.3) | iPhone XR (iOS 16.3.1) | iPad Pro (16.4 Beta 2)
-- | -- | -- 
<video src=https://user-images.githubusercontent.com/17010094/224374097-74a24376-550a-4e0f-a926-497bf3cfc3f7.MP4> | <video src=https://user-images.githubusercontent.com/17010094/224374022-4de5ecc8-8754-420e-8479-073c389b8a81.MP4> | <video src=https://user-images.githubusercontent.com/17010094/224373941-0a722463-2358-4873-9f43-1a44a706e5c9.MP4>
