### ISSUE TITLE
[security] Pin SSL certificates with Chromium API

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-ios#5789]
### Description: 
SSL Pinning doesn't work for the domains listed in https://github.com/brave/brave-core/blob/master/chromium_src/net/tools/transport_security_state_generator/input_file_parsers.cc

### Steps to Reproduce 
  1. Navigate to https://ssl-pinning.someblog.org/

**Actual result:** 
Webpage loads without an SSL error
<img width="841" alt="image" src="https://user-images.githubusercontent.com/10810135/182973562-61f8c4ed-caff-4a0e-877f-246e7aa8ee50.png">

**Expected result:**
Webpage fails to load with an SSL error

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced,

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
I see the same result on Brave desktop btw

**Comment by Brandon-T** [comment]
Issue happens on Desktop as well.
Desktop, iOS, and Android do not pin against `Sectigo RSA Domain Validation Secure Server CA` or `USERTrust RSA Certification Authority`.

For Youtube, it makes calls to `i.ytimg.com` and it has CA `GTS CA 1C3` and intermediate: `GTS Root R1`.
Brave Desktop doesn't pin this one either. So we'd get error: 
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/1530031/183219258-de64cd4d-04d4-4a1b-9b59-efa1ea1a1fc5.png">

I can check and see what the issue is on iOS, because it should be pinning `amazon.com` and it indeed isn't.

**Comment by Brandon-T** [comment]
Related: https://github.com/brave/brave-core/pull/9781 (Rebased).

**Comment by kjozwiak** [comment]
Now that we've uplifted https://github.com/brave/brave-core/pull/16719 & https://github.com/brave/brave-core/pull/16720, assuming this needs to go into the `1.47` milestone?

**Comment by Brandon-T** [comment]
> Now that we've uplifted https://github.com/brave/brave-core/pull/16719 & https://github.com/brave/brave-core/pull/16720, assuming this needs to go into the `1.47` milestone?

We will put this one into 1.48.x I believe. Since we'll put so many other fixes into 1.47.x. It will be too much.

I think it's fine in 1.48.x :)

**Comment by Uni-verse** [comment]
Verified completed using version `1.48 (23.2.21.21)` on `iPhone 12`, `IOS 16.1` & `iPad (9th Gen)`, `iPadOS 15.6.1`

Test Case:

1. Navigate to `https://ssl-pinning.someblog.org/`
2. Confirm webpage fails to load with SSL error

- Reproduced issue with version 1.47.x
- Upgraded app version to 1.48.x and confirmed ssl error is displayed when the page fails to load. 

1.47 | 1.48
-|-
![IMG_4561](https://user-images.githubusercontent.com/17885425/220491611-a7797ef1-1a8e-4b2a-94ce-75f72e6fd5d2.PNG) | ![IMG_4558](https://user-images.githubusercontent.com/17885425/220491639-f3ad7e52-1182-4744-a11f-d997c35a368e.PNG)

Example | Example | Example
-|-|-
![IMG_4558](https://user-images.githubusercontent.com/17885425/220491695-61e779b0-9145-4da9-a738-52fb5db48641.PNG) | ![IMG_4559](https://user-images.githubusercontent.com/17885425/220491696-c554ba08-48a6-46b1-b584-a24efd0bd2ad.PNG) | ![IMG_4560](https://user-images.githubusercontent.com/17885425/220491698-9a078cd4-1ea7-44a5-aa14-69af77077799.PNG)
![IMG_0147 2](https://user-images.githubusercontent.com/17885425/220491743-39c0d045-82b5-48dd-95e4-e34fba2ece11.PNG) | ![IMG_0148 2](https://user-images.githubusercontent.com/17885425/220491748-5ac917ec-446f-41cb-bc83-4fd23c9c2463.PNG) | ![IMG_0149 3](https://user-images.githubusercontent.com/17885425/220491751-9d6076cc-1c87-4d28-934c-8a3ae7c534b9.PNG)
