### ISSUE TITLE
Issues on some websites due to request blocking script

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#5791]
### Description: 
The issue is caused when sometimes (not sure why) the web kit message handlers are empty. The solution is to store the message handler as a const when the script loads and use it

### Steps to Reproduce 
  1. Enable shields
  2. Go to https://opensea.io/
  3. Click on hamburger menu

**Actual result:** 
Hamburger menu doesn't function

**Expected result:**
Should open a menu

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Every time

**Brave Version:** 
1.41

**Device details:** 
N/A

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using `1.42 (22.8.8.19)` 

Test Devices:

iPhone XR iOS 15.5
iPad (7th Gen) iOS 15.5
iPhone X iOS 14.4.2

Using the test plan in https://github.com/brave/brave-ios/issues/5791#issue-1329468233

- Confirmed hamburger menu is functional on https://opensea.io
- Confirmed user is able to use the menu with shields disabled as well. 


<table><tr><td>1.41 (issue exists)</td><td>1.42 (resolved)</td><td>1.42 (Tablet)</td></tr>
<tr><td>

https://user-images.githubusercontent.com/17885425/183735789-8762450d-3c7f-4f39-b64d-04f8ca2a92ed.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/183735803-b0cdfdac-344e-48e7-b869-46e5e8ac0425.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/183735905-f37596ef-9e97-4f9e-b4de-9cf1d44a8bff.MP4

</td></tr>
</table>
