### ISSUE TITLE
Selecting account type causes network to switch positions

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5793]
### Description: 
Selecting account type causes network to switch positions

### Steps to Reproduce 
  1. Upgrade to 1.42 build
  2. Create wallet and go to accounts tab
  3. Click on `+` to create account
  4. Select Solana from network and go back to selection page, Solana and Ethereum switch places

**Actual result:** 

https://user-images.githubusercontent.com/17010094/183040580-905639ee-ff2a-4157-843b-ea0c2532065f.mp4

**Expected result:**
Should not change position of network selector

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.42 (22.8.3.17)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps @jamesmudgett

**Comment by StephenHeaps** [comment]
This should have been fixed in https://github.com/brave/brave-ios/pull/5784, available in the next build with Solana enabled (hopefully next build).

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.42 (22.8.8.19)
- Verified steps from issue description
- Verified network position doesn't change when trying to add an account and cancelling it.


iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta)
-- | -- | --
<video width=300 src=https://user-images.githubusercontent.com/17010094/183685871-4158d9a7-d248-426d-b65c-1ca856d17711.MP4> | <video width=250 src=https://user-images.githubusercontent.com/17010094/183704320-370bd66e-d0a5-4dd9-9278-e3cd076731be.MP4> | <video width=400 src=https://user-images.githubusercontent.com/17010094/183704184-df72e2dd-92aa-488e-8194-950405cd9120.MP4>
