### ISSUE TITLE
Wallet Bug: Formatting SPL Token amount is not respecting token decimals in sending transaction

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5796]
### Description: 
Wrong formatting send SPL token amount in sending

### Steps to Reproduce 
  1. send some amount of SPL token (make sure this SPL token decimal is not 9)
  2. check the confirmation screen

**Actual result:** 
the send amount is wrong
1. it will be much bigger if the spl token decimals is smaller than 9
2. it will be much smaller if the spl token decimals is bigger than 9

**Expected result:**
the send amount should be the same as user input in send screen

**Reproduces how often:** [Easily reproduced]

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.4.1 running 1.42 (22.8.11.22)
- Verified steps from [#5797](https://github.com/brave/brave-ios/pull/5797)
- Verified amount value is shown correctly 

![image](https://user-images.githubusercontent.com/17010094/184328140-8477be59-3b4a-4950-aa1f-bcc4c52a1de1.png) | ![image](https://user-images.githubusercontent.com/17010094/184328168-b857608f-3cf9-4ba9-b9f0-a4d9e26e4c0b.png) | ![image](https://user-images.githubusercontent.com/17010094/184328186-0bd34e2e-2076-47dc-8156-3c280b065a3b.png) | ![image](https://user-images.githubusercontent.com/17010094/184328199-1c023e0a-d16e-495b-b776-2bfcd0223869.png)
-- | -- | -- | --
