### ISSUE TITLE
Consider Not Restoring Tabs when Disabling PBO

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#580]
When a user turns on PBO on, we should prompt them that this will destroy all of their tabs (potentially other data?). This prevents a user who stays in PBO mode for many months from having super old tabs being restored. It can appear to be a security vulnerability.

Ref: https://github.com/brave/brave-ios/pull/576/

**Comment by jhreis** [comment]
Need final copy on what this user-message/confirmation should be.

**Comment by anthonypkeane** [comment]
Text for alert:

Enabling Private Browsing Only will close your current tabs

Cancel | Okay

@tomlowenthal can you pls confirm?

**Comment by tildelowengrimm** [comment]
> Private Browsing Only mode will close all your current tabs and log you out of all sites.

**Comment by jhreis** [comment]
Do we have final product / security approval for this then @tomlowenthal and @anthonypkeane sounds like we do using the above copy?

**Comment by anthonypkeane** [comment]
The alert text is

Private Browsing Only mode will close all your current tabs and log you out of all sites.
Cancel | Okay

**Comment by jhreis** [comment]
Note to whoever picks this up. We then need to clear cookies to make sure users are also logged out of all of their sites.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.2 running 1.14(19.11.27.14)
* Verified enabling PBO shows warn message 
* Verified logged in session in a normal tab is lost when PBO is enabled
* Verified disabling PBO goes back to a normal tab and tabs from previous sessions are lost
* Verified browsing history is not lost when PBO is toggled
* Verified site shields settings are not lost when PBO is toggled
---------
Verification passed on iPhone 7+ with iOS 13.2 running 1.14(19.11.27.14)
* Verified enabling PBO shows warn message 
* Verified logged in session in a normal tab is lost when PBO is enabled
* Verified disabling PBO goes back to a normal tab and tabs from previous sessions are lost
* Verified browsing history is not lost when PBO is toggled
* Verified site shields settings are not lost when PBO is toggled
---------
Verification passed on iPhone 6 with iOS 12.4 running 1.14(19.11.27.14)
* Verified enabling PBO shows warn message 
* Verified logged in session in a normal tab is lost when PBO is enabled
* Verified disabling PBO goes back to a normal tab and tabs from previous sessions are lost
* Verified browsing history is not lost when PBO is toggled
* Verified site shields settings are not lost when PBO is toggled
---------
Verification passed on iPad Pro with iOS 13.2 running 1.14(19.11.27.14)
* Verified enabling PBO shows warn message 
* Verified logged in session in a normal tab is lost when PBO is enabled
* Verified disabling PBO goes back to a normal tab and tabs from previous sessions are lost
* Verified browsing history is not lost when PBO is toggled
* Verified site shields settings are not lost when PBO is toggled
---------
Verification passed on iPad Pro with iOS 12.4 running 1.14(19.11.27.14)
* Verified enabling PBO shows warn message 
* Verified logged in session in a normal tab is lost when PBO is enabled
* Verified disabling PBO goes back to a normal tab and tabs from previous sessions are lost
* Verified browsing history is not lost when PBO is toggled
* Verified site shields settings are not lost when PBO is toggled
