### ISSUE TITLE
Terminating the app throws fatal error from brave-core end.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5804]
### Steps to Reproduce 
  1. Use a non debug build
  2. Kill the app from memory

**Actual result:** 
Crash popup will show up

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Let's close since this can be tested on 1.42 builds.
For `1.43` we wait on the brave-core build to close related pull request

**Comment by Uni-verse** [comment]
Verified using `1.42 (22.8.10.15)`

Test Devices:

iPhone XR iOS 15.5
iPad (7th Gen) iOS 15.5
iPhone X iOS 14.4.2

- Confirmed removing the app from memory doesn't trigger error.

https://user-images.githubusercontent.com/17885425/184183342-7c3a959f-daa4-46e5-a5c0-3723effbc68a.MP4
