### ISSUE TITLE
Infinite redirect during de-amping

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#5812]
### Description: 
When there is a server side redirect to the amp page, it causes an infinite redirect loop to occur.

### Steps to Reproduce 
  1. Go to http://azurewaikiki.com/

**Actual result:** 
Infinite redirect loop

**Expected result:**
Should land on http://azurewaikiki.com/amp as the server redirects you and you should not have infinite loading

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Every time

**Brave Version:** 
1.4.2

**Device details:** 
Any

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using `1.42 (22.8.10.9)`

Test Devices:

iPhone XR iOS 15.5
iPad (7th Gen) iOS 15.5
iPhone X iOS 14.4.2

- Ensured loading http://azurewaikiki.com/ does not cause a redirect loop
- Ensured user is able to disable shields at http://azurewaikiki.com/

<table><tr><td>1.41</td><td>1.42</td></tr>
<tr><td>

https://user-images.githubusercontent.com/17885425/184011056-c12d525c-1bb4-4aa7-a8d1-adf33e1b3796.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/184010693-8eb54f87-abbd-47af-80d5-28d56cfbb35b.MP4

</td></tr></table>
