### ISSUE TITLE
Unable to see/select networks when Solana is set as default and trying to connect wallet on Ethereum Network

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5815]
### Description: 
Unable to see/select networks when Solana is set as default and trying to connect wallet on Ethereum Network

### Steps to Reproduce 
  1. Create Solana account
  2. Set it as active network and account
  3. Visit `https://app.1inch.io/` and connect wallet
  4. Shows connection notification message
  5. Change `Solana` to `Ethereum` on the dropdown in panel 
  6. Close the panel and reopen, network selector is empty even though Eth account is set as active
  7. Change active network to Ethereum on wallet and go back to panel, shows all networks 

**Actual result:** 

https://user-images.githubusercontent.com/17010094/183650984-499b0aa0-d8cd-4644-9956-8061b14af06c.MP4

**Expected result:**
Should be able to connect to a Dapp on EVM even when Solana is set as active. Changing it via panel should change it in wallet as well

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.42 (22.8.8.19)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by StephenHeaps** [comment]
Can reproduce occasionally by just opening/closing the panel via URL bar wallet button. Still investigating, but from logs we're failing to fetch the networks from Core to populate the networks list.

**Comment by srirambv** [comment]
Blocked on https://github.com/brave/brave-ios/issues/5843

**Comment by srirambv** [comment]
Verification passed as part of https://github.com/brave/brave-ios/issues/5843#issuecomment-1214684272
