### ISSUE TITLE
Wallet bug: Cannot see price history (chart) for some tokens on Mainnet (possibly other networks)

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5816]
![Simulator Screen Shot - iPhone Xʀ - 2022-08-09 at 09 50 46](https://user-images.githubusercontent.com/1187676/183666432-0c0062b9-ecf0-44df-b520-d5be7bc93a56.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.42 (22.8.11.22)
- Verified selected tokens show price history
- Verified randomly picked tokens on other networks as well and balance was shown


iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.4.1) | iPad Pro (iOS 15.6 Beta)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/184350778-bd5ad881-157b-4e2c-b631-0c6f5a81f177.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/184350748-fd64fa56-3ee3-42ab-94c1-002a0d9336db.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/184350819-aff7662e-43c3-40dc-851f-ce7325370c42.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/184350800-edb41e60-e73d-4016-bace-fb7422d60131.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/184350757-43451d44-1aff-44cc-9936-17b67eb9e7fa.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/184350851-54a72f62-87ee-4856-b256-05a50a569a2d.png>
