### ISSUE TITLE
Adding custom image links for favourites logos

### ISSUE THREAD

**Issue by DEFCON001** [brave/brave-ios#5820]
Certain sites don't advertise logos when added as favourites or bookmarks. This us a bigger issue with favourites now they are implemented as a widget. You can have multiple favourites on your homescreen that don't have an obvious logo, rather having a single letter, making it hard to tell what favourite is what. Adding an extra value in the "long hold Favourite -> Edit Bookmark" setting such as "Image url", so the user can set a custom image for the bookmark would fix this issue.

See current implementation:
(Edit Bookmark Setting):
![image](https://user-images.githubusercontent.com/73466675/183732772-937db2f2-baa4-4e0e-884f-8f5e63a1ede3.jpeg)
(Letters inside of favourites widget, hard to recognise):
![image](https://user-images.githubusercontent.com/73466675/183733854-158b13fb-de3d-48b9-80db-43361dfabbcc.jpeg)

**Comment by Brandon-T** [comment]
Hi, this website has a fav-icon. 
iOS will improve the favicon handling in a future PR coming soon, and it will display that website's icon from your screenshot.

**Comment by iccub** [comment]
Closing as this should be handled here https://github.com/brave/brave-ios/pull/5970
