### ISSUE TITLE
Saved passwords are viewable on iOS by clicking "Edit" (no security prompt required)

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-ios#5831]
### Description: 
On iOS, one can view any saved password information by going to `Settings --> Logins and passwords --> Edit`. The behavior here should be the same as when you click `Reveal` on the password, wherein you are prompted to enter your system password, fingerprint or faceID before viewing the password. The `Edit` button seems to bypass this prompt entirely.

### Steps to Reproduce 
  1. Launch Brave on iOS
  2. Go to `Login and passwords`
  3. Select a login/password and tap `Edit`

**Actual result:** 
Password is revealed and editable.

**Expected result:**
User should be prompted to enter system password/fingerprint/ID before information is revealed and/or editable. 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily/every time

**Brave Version:** 
v1.39.111

**Device details:** 
iPad/iOS 15.6

**Comment by Uni-verse** [comment]
Verified using version `1.43 (22.9.2.15)`

Test Devices:
`iPhone 12 Pro` & `XR `| `iOS 15.5`
`iPad (7th Gen)` | `iOS 15.5`
`iPhone X` | `iOS 14.4.2`

Test Plan based on STR in https://github.com/brave/brave-ios/issues/5831#issue-1334999523

Scenarios: 

`Clean Profile`: 
- Created username/password data by logging into website and saving password. Proceeded to `menu > settings > Logins & Passwords`. Tap on login entry, select `Edit` Confirmed user is required enter `system password`, `touch id` or `faceID`.

`Upgraded Profile`:
- Installed app version 1.42.x, populated the login/password with data via sync chain or manually saving passwords. Confirmed using `Edit` will expose the password without authentication.
- Upgraded app to version 1.43.x, opened login page and selected `Edit` option. Confirmed user will be prompted with `system password`, `touch id` or `faceID`. 

Example | Example
-|-
![IMG_3556](https://user-images.githubusercontent.com/17885425/188701543-1528a606-233b-40aa-b6f7-de786c82d234.PNG) | ![IMG_0539](https://user-images.githubusercontent.com/17885425/188701571-4fb09c27-b818-404d-9557-abfceeff2bee.PNG)
