### ISSUE TITLE
Portfolio balance doesn't update correctly

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5833]
### Description: 
Portfolio balance doesn't update correctly

### Steps to Reproduce 
  1. Install/Upgrade to 1.42 (22.8.10.15)
  2. Restore wallet which has balance on multiple networks
  3. Change network on portfolio page
  4. Balance doesn't auto update for iOS 16 device, only updates when you select a token and go back to portfolio
  5. Balance takes a while to auto-update for iOS 15/14 device 

**Actual result:** 

https://user-images.githubusercontent.com/17010094/184085718-3f193c0d-7788-400a-b9bd-4717765e4646.mp4

**Expected result:**
Should update immediately after network is changed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.42 (22.8.10.15)

**Device details:** 
iPhone 7+ (iOS 14.8.1) / iPhone XR (iOS 15.4.1) / iPad Pro (iOS 16 Beta 3)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @jamesmudgett @StephenHeaps.

**Comment by StephenHeaps** [comment]
Is this possibly network related? I'm unable to reproduce on iOS 16 beta 3, and iOS 15.5. It's possible it just loads after you had opened asset details (though the price history loads quick in asset details 🤔). If you wait longer and don't open asset details does it load on iOS 16 eventually?

iPadOS 16 beta 3:

https://user-images.githubusercontent.com/5314553/184185509-381f72c0-bad8-4078-81d5-decf62d95b58.mov

iOS 15 beta 3:

https://user-images.githubusercontent.com/5314553/184185366-4362cc92-0a48-4898-b9fb-ad1ac60fe286.mov

iPad OS 15.5:

https://user-images.githubusercontent.com/5314553/184185611-91d8149f-5988-42e0-97a3-157823023e26.mov

iOS 15.5:

https://user-images.githubusercontent.com/5314553/184185685-6ada301f-ed27-434d-a383-da0291b2fe65.mov

**Comment by srirambv** [comment]
Doesn't seem to be an issue with the latest build. Closing the issue for now as invalid. We can reopen it if it starts to happen again.
