### ISSUE TITLE
Changing network in panel doesn't auto-switch to the corresponding account

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5844]
### Description: 
Changing network in panel doesn't auto-switch to the corresponding account

### Steps to Reproduce 
  1. Create Wallet and create Solana account
  2. Set Solana as active network/account
  3. Open Wallet panel and change network to Ethereum, Solana account is still active account
  4. Change Network Back to Solana and switch back to Ethereum, still same
  5. Change account to Ethereum account, starts to switch automatically after manual selection

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/184372921-b541257a-cf9a-452e-a653-8d59006768b1.png)

**Expected result:**
Account and Network should match when either one of them are selected 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.42 (22.8.11.22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by StephenHeaps** [comment]
Should be resolved in https://github.com/brave/brave-ios/pull/5845

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ (iOS 14.8.1)/iPhone XR (iOS 15.4.1)/iPad Pro (iOS 16 Beta 3) running 1.40 (22.6.27.15)
- Verified steps from issue description
- Verified changing network in panel automatically updates the corresponding account
- Verified on both clean and upgrade profiles
