### ISSUE TITLE
Tapping the bottom of the screen when the URL bar is collapsed on iPad/landscape should not expand the URL bar

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#5846]
### Description: 

This was meant for when a bottom toolbar was currently being hidden, but it looks like its even when there's no bottom toolbar being hidden. We should make sure that tapping that bottom area doesnt expand the toolbar when there's no hidden bar to expand.

### Steps to Reproduce 
  1. Use an orientation/device that doesn't have a bottom toolbar such as iPhone landscape, or iPad (not multitasking)
  2. Scroll to the bottom of a page, see the URL bar collapse
  3. Tap the bottom edge

**Actual result:** 
Expands the top toolbar

**Expected result:**
Shouldn't expand anything since there is no bottom toolbar

**Reproduces how often:** Always
**Brave Version:** 1.42 (but been there since collapsed bar merged)

**Comment by iccub** [comment]
Sounds like this bug is related https://community.brave.com/t/when-click-buttons-lying-at-the-bottom-of-the-screen-on-ipad-nothing-happens-when-clicking-on-at-least-two-websites-happens/425736

**Comment by Uni-verse** [comment]
Verified using `1.43 (22.9.7.15)`

Test Devices:
iPhone 12 Pro & XR | iOS 15.5
iPad (7th Gen) | iOS 15.5
iPhone X | iOS 14.4.2

- Confirmed was able to reproduce behavior on version 1.42.x. 
- Ensured tapping on the bottom of screen in landscape orientation will not expand toolbars on version 1.43.x
- Ensured tapping on the bottom area of the screen still expands the toolbar in portrait orientation (iPhone)
- Ensured toolbars don't expand when there is no bottom toolbar when tapping on bottom edge of screen.
