### ISSUE TITLE
Wallet reset doesn't remove wallet notification badge

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5848]
### Description: 
Wallet reset doesn't remove wallet notification badge

### Steps to Reproduce 
  1. Initiate a wallet notification badge
  2. Open Settings and reset wallet
  3. Wallet icon in URL bar continues to show the badge
  4. Click on wallet opens onboarding 

**Actual result:** 

https://user-images.githubusercontent.com/17010094/184400630-37b40d65-2f7c-4a72-a473-1f4fa90fee66.MP4

**Expected result:**
Should remove badge when wallet is reset

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.42 (22.8.11.22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by srirambv** [comment]
This still seems to happen on 1.43 (22.9.2.15)

https://user-images.githubusercontent.com/17010094/188409112-7d1cd09c-0fa1-4e77-a747-9cdbf614e424.MP4

**Comment by nuo-xu** [comment]
reopen since QA can still repro on 1.43 build. Move to 1.44 to investigate more.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.44 (22.9.29.15)
- Verified steps from issue description
- Verified resetting Wallet removes Wallet notification badge as well


iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.6.1) | iPad Pro (iOS 16.1)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/193565437-7a77e19d-9c39-4b1e-a766-69f2e251aa67.MP4> | <video src=https://user-images.githubusercontent.com/17010094/193567529-ff1703a5-96d7-44a2-9ead-8fe526ad88d3.MP4> | <video src=https://user-images.githubusercontent.com/17010094/193568120-3595f8e4-9ad6-4224-8435-76896415d267.MP4>
