### ISSUE TITLE
Logins & Passwords 'save login' toggle hidden behind search bar

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5856]
### Description: 
Odd UI quirk when in edit mode for 'Logins & Passwords' , tapping edit and then selecting a save password row, then tapping back. 'Save Logins' row gets hidden behind the search / filter bar.

### Steps to Reproduce 
  1. Open Settings -> Logins & Passwords
  2. Tap edit in navigation bar
  3. Tap a saved login
  4. Tap back in navigation bar

**Actual result:**

![IMG_EA1C50DA2B54-1](https://user-images.githubusercontent.com/5314553/184417123-8768d07d-b4d4-40bf-b69b-a2768aa60c84.png)

**Expected result:**

**Reproduces how often:**
Easily reproduced

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using `1.45 (22.10.31.21)` using the following device(s):

iPhone 12 Pro | iOS 16.x
iPhone XR | iOS 15.x
iPhone X | iOS 14.x
iPad | iOS 16.x

Using STR in https://github.com/brave/brave-ios/issues/5856#issue-1337547339

- Confirmed could not reproduce behavior where save login toggle is hidden when tap on saved login and back again.

encountered (follow up): https://github.com/brave/brave-ios/issues/6298
