### ISSUE TITLE
[hackerone] security tokens issue

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-ios#5859]
https://hackerone.com/reports/1668723

credit: [nishimunea](https://hackerone.com/nishimunea)

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 11` running `iOS 16` using `1.42 (22.8.15.22)` as per https://github.com/brave/internal/issues/896#issuecomment-1217366442

* Verification **PASSED** on `iPhone 6s+` running `iOS 15.6` using `1.42 (22.8.15.22)` as per https://github.com/brave/internal/issues/896#issuecomment-1217366442

* Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 15.6`  using `1.42 (22.8.15.22)` as per https://github.com/brave/internal/issues/896#issuecomment-1217366442

**Comment by kjozwiak** [comment]
@Uni-verse @srirambv I don't have a `iOS 14` device anymore but we should check the above with `iOS 14` just to make sure it's working/fixed as well as it's a `P1` security issue. Can add the verification notes into https://github.com/brave/internal/issues/896 and mentioned that it passed in this issue 👍

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.42 (22.8.15.22). Verification notes can be found here https://github.com/brave/internal/issues/896#issuecomment-1217491963
