### ISSUE TITLE
Re-enable custom search engines button or remove entirely

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#586]
Ref #582 
Ref #495 

There is underlying code which allows a user to add a custom search engine when they are searching in popular website (i.e. YouTube)

Determine whether or not we want to keep this feature and re-add the button or if we would want to remove all this functionality entirely and its underlying implementation.

**Comment by srirambv** [comment]
@kylehickinson @jhreis we should probably consider allowing users to add custom SE similar to FF. With #920 and #895 we don't have ability to add custom SE that user wants to use.

**Comment by srirambv** [comment]
@kylehickinson @jhreis we should probably consider allowing users to add custom SE similar to FF. With #920 and #895 we don't have ability to add custom SE that user wants to use or already have it set on the older version. 

cc: @kjozwiak @bbondy @BrendanEich @diracdeltas

**Comment by cndouglas** [comment]
Related: #936 (Add support for OpenSearch)

**Comment by Brave-Matt** [comment]
+1 https://www.reddit.com/r/brave_browser/comments/ayon2e/ios_search_engines/

**Comment by srirambv** [comment]
@anthonypkeane @jhreis This one needs to go with 1.9 in my opinion.

**Comment by jhreis** [comment]
Excluding from release notes, as #936 will be included, and these will go together.

**Comment by jhreis** [comment]
Closing as duplicate of #936 (even though other ticket is newer, it is more clear).

**Comment by isaacjara17** [comment]
I think this feature would be loved or at least liked by everyone. Why isn't it implemented yet?
