### ISSUE TITLE
Top search bar click target too small: Almost always opens the result directly when clicking it

### ISSUE THREAD

**Issue by kevinXmichael** [brave/brave-ios#5862]
## Description

When I use the search bar on top and get results, I want to use the autocomplete feature to type something additional later on.
But currently the click target is too small, clicking on the icon and not hitting in perfectly, almost always opens the result directly instead of completing it in the top search bar.

## Steps to Reproduce

1. Open Brave
2. Click on the top search bar
3. Search something to get suggestions

## Actual Result

Click target too small: Almost always opens the result directly

## Expected result

When I click anywhere on the right side, it should autocomplete instead of open the result directly

## Reproduces how often

Everytime

## Brave Version

1.41.1 (22.7.27.20)

## Device

iPhone 12 Pro, iOS Version 16.0 (Beta)

## Screenshots

<img src="https://user-images.githubusercontent.com/54347972/184604474-3582368d-6888-4d67-82b8-09c305a87046.jpg" width="400" height="auto" />

**Comment by Uni-verse** [comment]
Verified using version `1.43 (22.9.2.15)`

Test Devices:
`iPhone 12 Pro` & `XR `| `iOS 15.5`
`iPad (7th Gen)` | `iOS 15.5`
`iPhone X` | `iOS 14.4.2`

Test Plan: https://github.com/brave/brave-ios/issues/5862#issue-1338706381

- Verified user is able to select the suggestions more comfortably as the click target size has increased. 
- Verified user is still able to select the search results.
