### ISSUE TITLE
All tabs overview: search bar on top is narrowed down to smallest size

### ISSUE THREAD

**Issue by kevinXmichael** [brave/brave-ios#5863]
## Description

When I open the all tabs overview, search bar on top is narrowed down to smallest size.

## Steps to Reproduce
1. Open Brave
2. Click on the bottom "counter" to open all tabs (probably open a few before if don't have opened tabs)
3. Search bar is always too small, clicking on it expands it

## Actual Result

Search bar too small, not extended

## Expected result

Search bar too small, should be extended

## Reproduces how often

Everytime

## Brave Version

1.41.1 (22.7.27.20)

## Device

iPhone 12 Pro, iOS Version 16.0 (Beta)

## Screenshots

<img src="https://user-images.githubusercontent.com/54347972/184605361-50f1bc1e-8a7b-4e8b-96b7-446f353f3893.JPG" width="400" height="auto" />

<img src="https://user-images.githubusercontent.com/54347972/184605374-48663c16-89e1-4fff-bd2e-df70e51f9323.jpg" width="400" height="auto" />

**Comment by iccub** [comment]
thanks, this looks like a beta bug, we'll try to fix soon

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.43 (22.9.9.14)
- Verified tabs search box is shown properly and able to search 
- Verified tabs search box is shown for both normal and private tabs

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.6.1) | iPad Pro (iOS 16.1)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/189691201-f0c2dd7c-ce77-48b9-af29-1a2d99a902fb.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/189691099-e4ac40de-fd8d-4f0d-8f47-51d1f154827d.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/189690917-bc57c49c-64d5-4bbe-8997-0b0bb37e0d2a.png>
