### ISSUE TITLE
Update readability dependency

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5865]
Our readability dep has hard pinned version from 2019, let's update it and grab changes from the upstream.

**Comment by Uni-verse** [comment]
Verified using `1.43 (22.9.9.14)`

Test Devices:
iPhone 12 Pro & XR with iOS 15.x
iPhone X with iOS 14.4.2
iPad with iPadOS 15.x

Using Test Plan in https://github.com/brave/brave-ios/pull/5866#issue-1338858833

- Ensured Reader mode icon is present in the URL bar
- Ensured reader mode is able to be enabled in normal and & private tabs
- Ensured user is able to change the reader mode settings and changes take effect
- Ensured reader mode settings persist between different pages 

iPhone | IPad
-|-
![IMG_0030](https://user-images.githubusercontent.com/17885425/189421049-1a8ea027-b3d8-4802-9b65-443fa4115f34.PNG) | ![IMG_0553](https://user-images.githubusercontent.com/17885425/189421077-1534e001-443d-4f63-9b83-c829fd12b7d7.PNG)
