### ISSUE TITLE
Shortcuts widget is no longer configurable

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#5874]
### Steps to Reproduce 
  1. Add a configurable widget the home screen (Single stat or shortcuts widget)
  2. Long press widget and choose "Edit Widget"

**Actual result:** 
You are shown an empty screen

**Expected result:**
You should be shown configuration options

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
1.40+

**Comment by Uni-verse** [comment]
Verified using version `1.43 (22.9.2.15)`

Test Devices:
`iPhone 12 Pro` & `XR `| `iOS 15.5`
`iPad (7th Gen)` | `iOS 15.5`
`iPhone X` | `iOS 14.4.2`

Using STR in https://github.com/brave/brave-ios/issues/5874#issue-1341810935

- Verified user is able to edit shortcuts & privacy stat widget when long pressing
- Verified user is able to select options from the menu list for the shortcut widget
- Verified user is able to select from the options for the privacy widget

Example | Example
-|-
![IMG_3553](https://user-images.githubusercontent.com/17885425/188695220-cef82ce4-5f8e-43ab-bc84-c5ef51151b52.PNG) | ![IMG_3554](https://user-images.githubusercontent.com/17885425/188695227-d7306922-b8b9-4025-a378-c143a91ad931.PNG)
![IMG_0537](https://user-images.githubusercontent.com/17885425/188695251-098bbb3b-692a-48fa-9625-1774b827172c.PNG) | ![IMG_0538](https://user-images.githubusercontent.com/17885425/188695259-a9e05f42-01f1-4be6-ba90-6f85a79e9ed8.PNG)
