### ISSUE TITLE
Add additional Password-protection to private key reveal from Account screen

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5881]
### Description: 

To increase the overall security, revealing a private key from the account screen should require re-entering the wallet password

### Steps to Reproduce 
  1. Open Brave Wallet
  2. Tap 'Accounts' tab
  3. Tap an account
  4. Tap 'Details'
  5. Tap 'Private Key'
  6. No password protection to reveal/show private key

### Additional Information

ref: https://github.com/brave/brave-browser/issues/24322

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 runnin 1.45 (22.10.25.19)
- Verified steps from issue description and [ #6151](https://github.com/brave/brave-ios/pull/6151)
- Verified tapping `Show private key` button to shows the private key
- Verified tapping `Hide private key` button to hides the private key
- Verified able to view private key either by entering password or touch/face id
- Verified biometrics button (face id / touch id) auto-fills when enabled

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.6.1) | iPad Pro (iOS 16.1)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/198366518-9e1c8fd1-612b-42c5-8829-7f68605c052f.MP4> | <video src=https://user-images.githubusercontent.com/17010094/198367039-426e9e65-97e5-48fa-b5c4-64e0f5044928.MP4> | <video src=https://user-images.githubusercontent.com/17010094/198367103-6a599345-0942-4562-a6b1-7ab4827dd8a2.MP4>
