### ISSUE TITLE
Add additional Password-protection for Wallet Backup Seed reveal

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5882]
### Description: 

To increase the overall security, revealing the Brave Wallet backup seed phrase from should require re-entering the wallet password

### Steps to Reproduce 
Always:
  1. Open & unlock Brave Wallet
  2. Tap 'Accounts' tab
  3. Tap 'Backup'
  4. No password protection

If seed phrase not backed up:
  1. Open & unlock Brave Wallet
  2. Tap banner at top of Portfolio ('Back up your wallet now to protect your crypto assets and ensure you never lose access.').
  3. No password protection

### Additional Information

ref: https://github.com/brave/brave-browser/issues/24534

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.45 (22.10.25.19)
- Verified steps from [#6167](https://github.com/brave/brave-ios/pull/6167)
- Verified no second password prompt is shown during onboarding 
- Verified clicking on banner in portfolio shows password prompt before showing the backup seed phrase
- Verified clicking on `Backup` in accounts tabs shows password prompt before showing the backup seed phrase
- Verified able to view backup seed phrase via both password or biometric unlock
-----------
Verification passed on iPhone XR with iOS 15.6.1 running 1.45 (22.10.25.19)
- Verified steps from [#6167](https://github.com/brave/brave-ios/pull/6167)
- Verified no second password prompt is shown during onboarding 
- Verified clicking on banner in portfolio shows password prompt before showing the backup seed phrase
- Verified clicking on `Backup` in accounts tabs shows password prompt before showing the backup seed phrase
- Verified able to view backup seed phrase via both password or biometric unlock
------------
Verification passed on iPad Pro with iOS 16.1 running 1.45 (22.10.25.19)
- Verified steps from [#6167](https://github.com/brave/brave-ios/pull/6167)
- Verified no second password prompt is shown during onboarding 
- Verified clicking on banner in portfolio shows password prompt before showing the backup seed phrase
- Verified clicking on `Backup` in accounts tabs shows password prompt before showing the backup seed phrase
- Verified able to view backup seed phrase via both password or biometric unlock
