### ISSUE TITLE
Wallet Bug: A crash happens for some tokens in asset details screen.

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5886]
### Description: 
For tokens that only has one or no price history will cause a crash 

### Steps to Reproduce 
  1. open wallet
  2. go to asset details for tokens like AAPL or ABNB on Solana Mainnet 
  

**Actual result:** 
App will crash

**Expected result:**
Users should be able to check asset details 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.43 (22.9.2.15)
- Verified steps from issue description
- Verified no crash when adding tokens to portfolio 
- Encountered [#5966](https://github.com/brave/brave-ios/issues/5966)

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.6.1) | iPad Pro (iOS 16.1)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/188422752-c42d788b-61a5-43ad-8ea0-477d8f26ac0a.MP4> | <video src=https://user-images.githubusercontent.com/17010094/188424104-f970f501-8bd0-4f6b-8985-2a8a14d05431.MP4> | <video src=https://user-images.githubusercontent.com/17010094/188422726-37719c58-b53e-4f9f-b8cc-ac0a04a154d9.MP4>
