### ISSUE TITLE
Wallet bug: Cannot send or swap decimal if device region is set to countries that use comma for decimals

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5889]
### Description: 
Wallet failed to convert input to decimal number which block users from sending or swapping if users' keyboard using comma for decimal numbers.

### Steps to Reproduce 
  1. set region to a country that use comma for decimal numbers (e.x Poland)
  2. open wallet
  3. try to send and swap with a decimal number
  

**Actual result:** 
send and swap are disabled 

**Expected result:**
user should be able to send and swap when they have sufficient balance 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.6.1 running 1.43 (22.9.2.15)
- Verified steps from issue description
- Verified able to submit a send/swap transaction with locale set to use comma for decimals

https://user-images.githubusercontent.com/17010094/188427139-e2453b43-fd25-490c-9f09-0570765b527c.MP4
