### ISSUE TITLE
Bookmarks Partially Occluded by Brave UI

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ios#589]
### Description: 
Bookmarks may be partially occluded by browser UI.

### Steps to Reproduce 
1. Add a bunch of bookmarks (enough that scrolling is necessary)
2. Scroll to the bottom of the list of bookmarks

**Actual result:** 
Last bookmark is partially occluded.

![image](https://user-images.githubusercontent.com/815158/49562562-b3a40100-f8e1-11e8-8a56-6526249fb02e.png)

**Expected result:**
All bookmarks should be shown and easily reachable.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always.

**Brave Version:** 
1.6.6 (18.11.15.17)

**Device details:** 
iPhone X

**Comment by srirambv** [comment]
I cant reproduce this on iPhone 7/iPad. Could be iPhone X specific

**Comment by kylehickinson** [comment]
This is no longer an issue in 1.7
