### ISSUE TITLE
 Pdf reader is not hiding the tabs and url-bar

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5894]
See https://community.brave.com/t/pdf-reading-is-not-hiding-the-tabs-and-url-bar/425809

**Comment by Uni-verse** [comment]
Verified using `1.44 (22.10.5.17`) using the following device(s):

`iPhone 12` running `iOS 16.0`
`iPhone XR` running `iOS 15.5`
`iPhone X` running `iOS 14.4.2`
`iPad (7th Gen)` running `iPadOS 15.7`

Acceptance Criteria:

- Verified toolbars are not hidden when viewing PDF files on app version `1.43.x`
- Verified toolbars are hidden with `bottom bar` enabled
- Verified toolbars are hidden with `top bar` enabled
- Verified transitioning from `portrait` to `landscape` is working and does not cause issues with alignment
- Verified `disabling tab bar` works when loading PDF 
- Verified private mode
- Verified upgrade use case: 
1. Install clean profile using 1.43
2. Load PDF
3. upgrade to 1.44
4. Open existing tab and scroll to ensure tabs are being hidden

<hr>

<table><tr><td>Default (1.43)</td><td> Default (1.44)</td></tr>
<tr><td>

https://user-images.githubusercontent.com/17885425/194599000-b3a6ecdb-d5b8-43e8-bfc9-806b2cf615f3.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/194602084-b94b9da3-1aeb-413b-86fe-9398f2e654fe.MP4

</td></tr></table>


<table><tr><td>Bottom bar, tabs enabled</td><td>Landscape</td></tr>
<tr><td>

https://user-images.githubusercontent.com/17885425/194601123-5c41fd20-02da-4577-9ab2-3950b3684b46.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/194601685-a5227d0b-5334-4369-a205-b2f155e07608.MP4

</td></tr></table>

IPad (Portrait) | iPad (Landscape)
-|-
![IMG_0619](https://user-images.githubusercontent.com/17885425/194609188-3271996c-e21d-4677-8437-841411b2bc84.PNG) | ![IMG_0620](https://user-images.githubusercontent.com/17885425/194609205-7cc12c5c-2e1e-4b4c-b542-d9e99c705a01.PNG)
