### ISSUE TITLE
Tab Mode changes does not preserve tab index

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#5898]
### Description: 
Inside the tab tray while changing from Normal Tab to Private Mode the index of chose tab from normal mode is forgotten.
And changing back to Normal Model from Private mode selects the first tab in Tab-Tray and doesnt highlight it.

This causes great discomfort between mode changes especially for a users which has great number of tabs open.

### Steps to Reproduce 
  1. Open Tab -Tray in normal Mode when a any other tab is elected except the first one
  2. Switch to Private Mode
  3. Switch back to Normal Mode
  4. The first tab is selected as current tab and not marked with blue shadow

**Actual result:** 

https://user-images.githubusercontent.com/6643505/185706219-ac7be18e-d247-4103-882f-22f12bfe1780.MP4

**Expected result:**
After changing back to Normal Mode the previously selected Tab should be highlighted and selcetd a scurrent

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
N/A

**Device details:** 
N/A

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by Uni-verse** [comment]
Verified using version `1.43 (22.9.1.15)`

Test Devices:

`iPhone 12 Pro` running `iOS 15.5`
`iPhone X` running `iOS 14.4.2`
`iPad (7th Gen)` running `iPadOS 15.5`

Using STR in https://github.com/brave/brave-ios/issues/5898#issue-1344891417

- Tested on version`1.42.x` with `clean profile`, opened several tabs and switched tab modes to confirm issue exists. Proceeded to upgrade app to version `1.43.x` and confirmed that the tab index is preserved when user switches tab modes. 

- Confirmed that current tab contains blue shadow after upgrading from `1.42.x`

- Confirmed tab index is preserved on `clean profile` when switching tab modes.

<table><tr><td>Mobile</td><td>Tablet</td></tr>

<tr><td>

https://user-images.githubusercontent.com/17885425/188232926-4164459f-9d3c-43b7-87e1-e9cdc22b54e9.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/188232977-803cb0b3-224a-42ba-a905-2d83468e38ee.MP4

</td></tr>
