### ISSUE TITLE
Wallet: Let user select active RPC endpoint for custom networks

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5902]
This is an iOS version https://github.com/brave/brave-browser/issues/20516

**Comment by nuo-xu** [comment]
keep 1.59 milestone since this has been shipped in 1.56 version but not verified.

**Comment by srirambv** [comment]
QA blocked on #8266 & #8267

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-ios/issues/8267#issuecomment-1822270790. Encountered https://github.com/brave/brave-ios/issues/8462
