### ISSUE TITLE
Collapsed URL sometimes shows on top of expanded bar when opening Brave from background

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#5904]
### Description: 

Sometimes when you open Brave from the background the collapsed URL bar shows on top of the expanded URL bar

### Steps to Reproduce 
  1. Open link while Brave is backgrounded (possibly while the bar is collapsed? not sure)
  2.
  3.

**Actual result:** 
![Image from iOS](https://user-images.githubusercontent.com/529104/185971930-975e5f45-2a54-4c21-bcc7-d9d7f29783ae.jpg)
![Untitled](https://user-images.githubusercontent.com/529104/185972093-aa111231-e2c9-4ea1-8d01-1a6ccc1ccab9.png)

**Expected result:** Shouldn't be showing
**Reproduces how often:** Intermittent Issue
**Brave Version:** Live (likely 1.41+)

**Comment by Uni-verse** [comment]
Verified using version `1.43 (22.9.2.15)`

Test Devices:
`iPhone 12 Pro` & `XR `| `iOS 15.5`
`iPad (7th Gen)` | `iOS 15.5`
`iPhone X` | `iOS 14.4.2`

Using STR from https://github.com/brave/brave-ios/issues/5904#issue-1346688603

- Verified was not able to reproduce issue when bar is collapsed and also expanded when opening link.
