### ISSUE TITLE
Tabs bar shown when a favourite is loaded after deleting browser data

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#591]
### Description: 
Tabs bar shown when a favourite is loaded after deleting browser data

### Steps to Reproduce 
Scenario 1: 
 1. Clear browsing history
  2. Tap on a favourite in new tab
  3. Tabs bar is shown for the single tab and remains as `New tab` until a second tab is loaded for the tab title to show up

Scenario 2
  1. Clear browsing history
  2. Type a url and load the site
  3. No tabs bar shown, open a new tab, tab contains the site title correctly where page was loaded

**Actual result:** 
https://drive.google.com/open?id=1Ozys66HKes1limLVvoe17hkoKzR9Gz2j

**Expected result:**
Tabs bar should only be shown if there are 2 or more tabs

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7(18.12.06.00)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
iPad also has similar behaviour but tabs bar is always shown even for one tab. Tab title is not updated until active tab focus is changed by opening a new tab.
Here's the iPad behaviour https://drive.google.com/open?id=1N-ATP7DH8u829xSHcIK8xD_LOI_3Oib7

**Comment by LaurenWags** [comment]
Verified passed with iPad 1.7.2 (19.1.15.15). Note - tab bar was enabled for the single tab on iPad as noted in description.
Verified passed on iPhone SE (iOS 12.1.2) with 1.7.2 (19.1.15.15)
Verification passed on iPhone 8 (iOS 12.1.2) with 1.7.2 (19.1.15.15)
