### ISSUE TITLE
Remove BAT from showing up as default listed token

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#5911]
### Description: 
Remove BAT from showing up as default listed token 

### Steps to Reproduce 
  1. Create Wallet
  2. BAT is listed as default token
  3.

**Actual result:** 
BAT is listed as default token

**Expected result:**
Should only list native tokens by default

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
All

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
Desktop/Android issue https://github.com/brave/brave-browser/issues/24892

**Comment by lukemulks** [comment]
https://github.com/brave/brave-browser/issues/24892#issuecomment-1229533955
