### ISSUE TITLE
Inject isBrave for all frames

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5913]
Test Plan:
Visit iccub.github.io
Tap on the isBrave iFrame check

Should return true

**Comment by Uni-verse** [comment]
Verified using version `1.43 (22.9.2.15)`

Using STR in https://github.com/brave/brave-ios/issues/5913#issue-1347946617

- Verified the` isBrave iFrame` check is returning `true` on `iccub.github.io` test page mobile and tablet devices.

Test Devices: 
iPhone 12 Pro & XR | iOS 15.5
iPad (7th Gen) | iOS 15.5
iPhone X | iOS 14.4.2


Mobile | Tablet 
-|-
![IMG_3551](https://user-images.githubusercontent.com/17885425/188668155-2e97f4b0-1301-4866-bfb3-227b01b82d9c.PNG) | ![IMG_0536](https://user-images.githubusercontent.com/17885425/188668150-c584ff6e-1ab2-4094-bfb2-e8ddc6fc7d6e.PNG)
