### ISSUE TITLE
New tab/New private tab missing in long press context menu

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#592]
### Description: 
New tab/New private tab missing in long press context menu

### Steps to Reproduce 
  1. Install/upgrade to 1.7 (18.12.06.00)
  2. Long press on tab container
  3. Only shows `Close all x tabs` and `Close tab`, doesn't have `Open New tab` and `Open New Private tab` options

**Actual result:** 
New tab/New private tab missing in long press context menu

**Expected result:**
New tab/New private tab options should be available in long press context menu 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7 (18.12.06.00)

**Device details:** 
iPad (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
Not sure if this is expected behaviour but if tabs bar is hidden the only way is to go to tab container and launch which is annoying

**Comment by kylehickinson** [comment]
> Not sure if this is expected behaviour but if tabs bar is hidden the only way is to go to tab container and launch which is annoying

This is interesting, the context menu with the new tab/new private tab is actually in the + button on iPhone, but since we have the + button in the tab bar on iPad the user doesn't get it.

Maybe it would be good to add the long-press shortcuts to the iPad add-tab button (in the tab bar) and when the tab bar is hidden, re-add the regular iPhone add tab button in the top toolbar

@srirambv @jhreis thoughts?

**Comment by srirambv** [comment]
>Maybe it would be good to add the long-press shortcuts to the iPad add-tab button (in the tab bar) and when the tab bar is hidden, re-add the regular iPhone add tab button in the top toolbar

++ for this. I think the long press action menu should be for + button rather than the tabs icon(current behaviour). Would only require it on the tabs icon if tabs bar is hidden.

**Comment by kylehickinson** [comment]
@srirambv Please see #596 for screenshots of solution
