### ISSUE TITLE
Add iOS 16 lock screen widgets

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5920]

**Comment by Uni-verse** [comment]
Verified using version `1.45 (22.10.28.19)` on `iPhone 12 Pro` running `iOS 16.1`

Additional sanity testing notes on fresh and upgraded profiles for iOS 16 widgets available in https://github.com/brave/brave-ios/issues/6166#issuecomment-1295376080

**Favorites lock screen widget** - `PASS`

- YouTube favorite is set as default
- Favorites list provides all urls currently in brave favorites
- Able to add multiple favorite widgets for lock screen
- Able to a mix of favorites + shortcuts to the lock screen widget area

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_4017](https://user-images.githubusercontent.com/17885425/199099973-bf6ca8d4-faf6-4b9f-9ae8-142d686ab04d.PNG) | ![IMG_4018](https://user-images.githubusercontent.com/17885425/199100002-01ac4168-8082-4b87-8df8-ed87bd6f581f.PNG) | ![IMG_4019](https://user-images.githubusercontent.com/17885425/199100007-a9e06d42-8234-4ead-9cca-e4a585b941d1.PNG) | ![IMG_4020](https://user-images.githubusercontent.com/17885425/199100020-c26a2a56-9a6c-4ac3-93cc-557489658272.PNG) | ![IMG_4021](https://user-images.githubusercontent.com/17885425/199100031-7642fb85-8c87-4780-aa6f-ae7a27f9e621.PNG) | ![IMG_4022](https://user-images.githubusercontent.com/17885425/199100033-f07ecfd8-3662-441b-8d16-1e24f06966ce.PNG)

**Shortcut lock screen widget** - `PASS`

 - New Tab shortcut widget shown by default
 - List of options for views available when selecting lock screen widget
 - Adding multiple shortcut widgets via lock screen wallpaper
 - Using shortcuts from lock screen will launch that appropriate view

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_4008 2](https://user-images.githubusercontent.com/17885425/199097666-497da71d-36d7-450f-9936-f87a496b3ae5.PNG) | ![IMG_4016](https://user-images.githubusercontent.com/17885425/199097697-eb2b4675-2f38-4395-82d2-9f28d90074f9.PNG) | ![IMG_4015](https://user-images.githubusercontent.com/17885425/199097717-b143b563-8592-41d1-98da-ad6dcdd796f8.PNG) | ![IMG_4013](https://user-images.githubusercontent.com/17885425/199097733-ad52f469-4ae1-47a7-8429-6cb5ce16c3d2.PNG) | ![IMG_4012](https://user-images.githubusercontent.com/17885425/199097744-353f3ca0-98f0-4dcc-80b4-f3f645866eb6.PNG)

**Upgrade Cases** - `PASS`

- Able to add favorites and shortcuts on upgraded profile (1.44.1 -> 1.45)
- Able to add and load custom favorites from previous version
- Able to add and launch QR code scanner widget introduced in 1.45.x
