### ISSUE TITLE
Problem with Tab Display Title including "localhost"

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#5924]
### Description: 

Right now if the Title of a tab contains localhost, we are using an empty title in order to eliminate localhost domains. But his causes a problem with sites that has local host in their title like "How to setup a localhost server?"

More information can be found https://github.com/brave/brave-ios/pull/5809#discussion_r954203215

**Actual result:** 

Title will be empty

**Expected result:**

Title should be shown.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
N/A

**Device details:** 
N/A

**Comment by Uni-verse** [comment]
Verified using version `1.45 (22.11.7.16)` on the following device(s):

iPhone 12 Pro - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPads - iPadOS 16.x, 15.x

Using STR/expected result in https://github.com/brave/brave-ios/issues/5924#issue-1350969688

- Verified tab titles containing "localhost" are shown in sync tab display

Example | Example
-|-
![IMG_4057](https://user-images.githubusercontent.com/17885425/200397505-acfd3aaa-1181-4c3e-9375-2e3f52806f52.PNG) | ![IMG_0755](https://user-images.githubusercontent.com/17885425/200397695-f58618ab-b1f2-4a8f-87ed-e3f838f6aa4b.PNG)
