### ISSUE TITLE
Location bar container can sometimes expand its height far beyond required size

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#5925]
![image](https://user-images.githubusercontent.com/529104/186707904-85f58730-9b45-44a5-8d25-5e6e800c2000.png)

Brave Version: 1.42 (22.8.15.22)
OS: 15

## Test Case

This is extremely intermittent (only 1 case seen so far), so if you cannot reproduce, just verify that the URL bar works as usual across multiple font sizes

**Comment by Uni-verse** [comment]
Verified using `1.43 (22.9.7.15)`

Test Devices:
iPhone 12 Pro & XR | iOS 15.5
iPad (7th Gen) | iOS 15.5
iPhone X | iOS 14.4.2

Using STR/Test Plan from https://github.com/brave/brave-ios/issues/5925#issue-1351093844

- Verified URL bar works with variety of font sizes.
- Verified launching app/NTP with different system font sizes.
