### ISSUE TITLE
Playlist item not saving its last position

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#5940]
### Description: 
Slack Link: https://bravesoftware.slack.com/archives/CKJCXTP9B/p1661862230456169

Playlist item not saving its last position

### Steps to Reproduce 
  1. Open a video website
  2. Add a video to offline 
  3. Play the video and note the time when you stop
  4. Close Playlist and Brave
  5. Open Brave and Playlsit

**Actual result:** 
- Video position in step 3 is not saved

**Expected result:**
- Video position should be saved and the video should start where the user stopped

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using `1.43 (22.9.9.14)`

Test Devices:
iPhone 12 Pro & XR with iOS 15.x
iPhone X with iOS 14.4.2
iPad with iPadOS 15.x

Using STR in https://github.com/brave/brave-ios/issues/5940#issue-1355892725

- Verified playlist item play position is being saved 

<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/189407695-71d471bb-f350-435f-be34-1713f99b86af.PNG">
