### ISSUE TITLE
Wallet: Hide `Connect` button in wallet panel if selection account is solana coin type and no permission has ever given

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5943]
Solana connection is called first from the website. Don’t show the connect button on sites that none of the solana accounts has been granted connection permissions

**Comment by nuo-xu** [comment]
Close as https://github.com/brave/brave-ios/pull/6021 has been merged.

**Comment by srirambv** [comment]
Verification passed as part of https://github.com/brave/brave-ios/issues/6570#issuecomment-1343168291

**Comment by StephenHeaps** [comment]
I've updated the milestone as Solana Dapps has been moved to v1.47 release for iOS. This ticket has been verified but remains behind a feature flag.
