### ISSUE TITLE
Wallet: User should able to manage web3 settings based on different coin types

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#5945]
### Description: 
Since we are introducing Solana Dapps Support, users should be able to easily manage web3 settings based on the coin type (so far, .eth and .sol)
Settings UI will have a little update that web3 specific settings will be separate based on coin type. 

![simulator_screenshot_A0EC574B-A931-46B8-B524-D01D7834D0A3](https://user-images.githubusercontent.com/1187676/189202899-147e5187-7fff-4cf4-b795-9d83e61508aa.png) | ![simulator_screenshot_DAB07451-AB23-450D-9534-8F8F6C1C3B00](https://user-images.githubusercontent.com/1187676/189202917-196113f7-d786-4882-a74e-626594f3b7a7.png)
-- | --

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.44 (22.9.29.15)
- Verified steps from issue description & [#5991](https://github.com/brave/brave-ios/pull/5991)
- Verified Ethereum Web3 provider settings works as expected
- Verified disabling the setting doesn't interact with any Dapp
- Verified disabling Wallet provider to None doesn't interact with Dapps
- Verified setting Solana account as active account still allows to interact with Ethereum Dapps
----------
Verification passed on iPhone XR with iOS 15.7 running 1.44 (22.9.29.15)
- Verified steps from issue description & [#5991](https://github.com/brave/brave-ios/pull/5991)
- Verified Ethereum Web3 provider settings works as expected
- Verified disabling the setting doesn't interact with any Dapp
- Verified disabling Wallet provider to None doesn't interact with Dapps
- Verified setting Solana account as active account still allows to interact with Ethereum Dapps
---------
Verification passed on iPad Pro with iOS 16.1 running 1.44 (22.9.29.15)
- Verified steps from issue description & [#5991](https://github.com/brave/brave-ios/pull/5991)
- Verified Ethereum Web3 provider settings works as expected
- Verified disabling the setting doesn't interact with any Dapp
- Verified disabling Wallet provider to None doesn't interact with Dapps
- Verified setting Solana account as active account still allows to interact with Ethereum Dapps
