### ISSUE TITLE
Buttons in top toolbar are hard to tap and have decreased tap areas compared to prior versions

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#5952]
### Description: 

Regression most likely while adding dynamic type to the URL bar + toolbars caused the buttons to only have tap areas on the content area (image) instead of increased amounts around them.  This is most noticeable in landscape where additional buttons are added

**Comment by Uni-verse** [comment]
Verified using version `1.43 (22.9.2.15)`

Test Devices:
`iPhone 12 Pro` & `XR `| `iOS 15.5`
`iPad (7th Gen)` | `iOS 15.5`
`iPhone X` | `iOS 14.4.2`

- Verified I was able to easily tap top toolbar buttons in portrait and landscape orientation.
- Verified top toolbar were easily accessible when playlist url button is present.
