### ISSUE TITLE
Tab-Sync UI Revamp Part 1

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#5955]
### Description: 

This ticket is follow-up for https://github.com/brave/brave-ios/issues/3229

This is the first part of the UI Revamp after merging Tab Sync. 

It includes part of changes from https://www.figma.com/file/SLFLpMd7F7Tu58qGBdcUQG/iOS-Settings?node-id=1213%3A9562

First will include 

1. Icon Revision
2. Localization Changes
3. Empty states Action for Sync Types
4. Behaviour for Search control

**Comment by Uni-verse** [comment]
Verified using `1.43 (22.9.9.14)`

Test Devices:
iPhone XR running iOS 15.x
iPhone 12 Pro running iOS 16.x
iPhone X running iOS 14.4.2
iPad running iPadOS 15.x

Test Plan based on https://github.com/brave/brave-ios/pull/5956#issue-1357882621

- Verified enabling and disabling open tab sync state
- Verified leaving and joining sync chain
- Verified search tab behavior when searching in one segmented tab and switching to the other

Example | Example
-|-
![IMG_0042](https://user-images.githubusercontent.com/17885425/189955383-70a5207f-6e64-4a17-85ef-665f822e27d8.PNG) | ![IMG_0043](https://user-images.githubusercontent.com/17885425/189955673-ccf9dac7-e6c0-4538-b63a-2de2fcec9a77.PNG)


https://user-images.githubusercontent.com/17885425/189955480-ca74e5b0-38a6-453a-b49d-6b4ecd1b2207.MP4
