### ISSUE TITLE
Playlist enhancement - saving position for items in the list

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#5959]
## Problem Description
If you have a playlist and use it for songs, it seems to work fine as-is. Each time an entry becomes active (ex: current item finishes playing, it moves to the next one), the newly activated entry plays starting at the 0 position.

This can be troublesome for cases where you're not listening to a song... but you're listening to something longer, like a podcast or an audiobook. **In this case, saving the position of this entry is important to you.**

## Feature Overview 
The position should be saved. We can remove/null out the position once the item finishes playing

## User Experience 

1. User adds 2 podcasts into a playlist
2. User jumps to entry 2 and listens to half of it
3. User jumps back to entry 1 and listens to the whole thing
4. After entry 1 finishes, it moves to entry 2
5. Entry 2 should start at the halfway point

**Comment by bsclifton** [comment]
Also an opportunity to be thoughtful - we can go back like 5-10 seconds to give the person context to where they were last time they were at this partially played position

**Comment by anthonypkeane** [comment]
Thanks Brian, I think 2-3 seconds should work fine.

**Comment by iccub** [comment]
Moving to a new ticket, this task needs more discussion https://github.com/brave/brave-ios/issues/6694
