### ISSUE TITLE
Close All Tabs action should close Tabs for current Tab Mode

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#5963]
### Description: 

`Close All # Tabs` action should close all the tabs for the current Tab Mode (Normal / Private).

This should also include actions for iPad shortcuts that are closing all Tabs.

### Steps to Reproduce 
  1. Start Browser in Normal Mode
  2. Open some random tabs
  3. Navigate Tab Tray and change viewing mode to Private
  4. Open 4 (could be any number) tabs in private mode
  5. Close Tab Tray and long press tab icon on bottom bar
  6. Choose action Close All Tabs 
   
**Actual result:** 

All Tabs including tabs in normal mode is closed

**Expected result:**

Only Tabs in current mode should be closed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
Current 1.42 - 1.43 Dev

**Device details:** 
N/A

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information

Reported by @bbondy cc @iccub

**Comment by Uni-verse** [comment]
Verified using version `1.43 (22.9.2.15)`

Test Devices:
iPhone 12 Pro & XR | iOS 15.5
iPad (7th Gen) | iOS 15.5
iPhone X | iOS 14.4.2

Using STR in https://github.com/brave/brave-ios/issues/5963#issue-1360267548

- Verified only the current view mode is closed when using `Close all # Tabs` in the tab tray
- Verified user is use other functions in the tab tray menu
- Verified Close All Tabs works in normal tab mode after closing all the tabs in private viewing mode
