### ISSUE TITLE
Add additional Password-protection for secondary account removal

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#5967]
### Description: 

Add password protection to secondary account removal

### Steps to Reproduce 
  1. Import an account
  2. Try to delete the account
  3. No password protection

### Additional Information

ref: https://github.com/brave/brave-browser/issues/24711

example UI from desktop:
<img width="448" alt="password protect account removal" src="https://user-images.githubusercontent.com/5314553/188517159-8c260335-c296-4891-ab71-c3b98aaff9e3.png">

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.45 (22.10.25.19)
- Verified test plan from [#6149](https://github.com/brave/brave-ios/pull/6149)
- Verified password request is shown before removing a secondary account
- Encountered [#6271](https://github.com/brave/brave-ios/issues/6271)

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.6.1) | iPad Pro (iOS 16.1)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/198381342-419f7156-8ba5-411e-a665-1f628476ba38.MP4> | <video src=https://user-images.githubusercontent.com/17010094/198379880-2b31ec00-c4e2-4fed-9233-b28f7142b6b5.MP4> | <video src=https://user-images.githubusercontent.com/17010094/198382665-bc52614a-8581-4661-859f-17444f84b48d.MP4>
