### ISSUE TITLE
Questionable copy for closing all tabs

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#597]
Strange copy here: ![iphone-landscape 3x](https://user-images.githubusercontent.com/529104/49596914-65c2e380-f949-11e8-8f48-555182d6ab29.png)

"Close All 2 Tabs" which is weirdly worded but not technically incorrect.

Could be instead "Close All Tabs" or "Close 2 Tabs"

**Comment by srirambv** [comment]
This was reported on 1.5.x as well. I'd vote for `Close x tabs` instead of all tabs. Also when there is only one tab the `Close X tabs` should not be shown and just close tab to be shown

**Comment by kylehickinson** [comment]
> Also when there is only one tab the Close X tabs should not be shown and just close tab to be shown

This is already the current case :)

**Comment by tildelowengrimm** [comment]
"Close all tabs (2)"?

**Comment by jamesmudgett** [comment]
We copy Safari wording on iOS.
