### ISSUE TITLE
Compile blocklists from raw text filter lists

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#5975]
### Description: 
There is no reason why we need to fetch separate blocklists when we have the ability to compile them ourselves on the iOS side.

### Additional Information
For this we need the raw text versions of the files to be exposed. This is done here: https://github.com/brave/brave-browser/issues/36035
And we need to be able to compile blocklists from the engine. This is done here: https://github.com/brave/brave-core/pull/14475

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using version `1.57 (23.8.29.17)`

Test Plan: https://github.com/brave/brave-ios/pull/7277#issue-1673203869

- Verified cosmetic filtering is working (cookie notices, open in app dialog).
- Verified cookie consent notices, open in app dialogs are shown when shields is down.

Open IA dialog | Open IA dialog | Cookie | Open IA dialog (Shields Down)
-|-|-|-
![IMG_3489](https://github.com/brave/brave-ios/assets/17885425/0ff5b14c-7d2f-4b22-8a9d-a00976ebbc57) | ![IMG_3490 2](https://github.com/brave/brave-ios/assets/17885425/392d5e33-cbdb-4a1e-b375-238296d67754) | ![IMG_3491](https://github.com/brave/brave-ios/assets/17885425/bb8f26c6-240d-4173-837a-1567fbbb7ca5) | ![IMG_3494](https://github.com/brave/brave-ios/assets/17885425/8da7a88e-9f26-48e7-9d56-ff1ab0ec7f70)

- Verified cosmetic filtering tests in test page https://dev-pages.brave.software/filtering/cosmetic-filtering.html
- Verified tracking protection in test page https://test-pages.privacytests.org/tracking_content.html
- Verified testing scriptlets in https://dev-pages.brave.software/filtering/scriptlets.html

Aggressive | Normal | CF tests | tracking protection | scriplets
-|-|-|-|-
![IMG_3492 2](https://github.com/brave/brave-ios/assets/17885425/ad88851c-b648-49ae-bfc3-a2f0ad696b78) | ![IMG_3493](https://github.com/brave/brave-ios/assets/17885425/6f5c8495-dd60-4f85-bbcc-b0d036ae7a1e) | ![IMG_3495](https://github.com/brave/brave-ios/assets/17885425/49d8dfa8-2e42-45af-9c7e-c6f38854126d) | ![IMG_3496](https://github.com/brave/brave-ios/assets/17885425/b812326b-7830-47d7-b7fa-9044a2254e76) | ![IMG_3497](https://github.com/brave/brave-ios/assets/17885425/6f6eb299-07a9-48e7-98e9-b84b9f144a40)

- Ensured that preroll ads on youtube and ads on webpages are blocked.
- Ensured that ads are shown when shields are down. 
- Ensured ads are blocked in aggressive and standard mode.

YT | YT | Buzzfeed | Buzzfeed
-|-|-|-
![IMG_3502](https://github.com/brave/brave-ios/assets/17885425/5ce75ed4-d691-4503-a89b-fd4d8574d4e7) | ![IMG_3503 2](https://github.com/brave/brave-ios/assets/17885425/c86889b3-9d7b-47ba-b006-cf96b4648968) | ![IMG_3504](https://github.com/brave/brave-ios/assets/17885425/e432cf45-0c56-4fca-b7ad-8ce32bf2cb58) | ![IMG_3505](https://github.com/brave/brave-ios/assets/17885425/e99ea510-f97b-49c8-864e-86241b852bbb)
