### ISSUE TITLE
Request blocking should only depend on main frame's URL

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#5976]
### Description: 
We use the current frame url to check for settings. Settings should depend solely on the mainframe url and not the subframes url
It's impossible to test the problem. 

### Steps to Reproduce 
This issue was discovered because of similar flawed logic on Filter lists. However filter lists is not yet in development so there is no issue reproducible issue on development to test. What we can test is that de-bouncing, and de-amping is working as expected.

**Actual result:** 
N/A

**Expected result:**
De-bouncing and de-amping is working as expected

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent issue

**Brave Version:** 
1.42

**Device details:** 
Any

### Additional Information
This may be related to this: https://community.brave.com/t/brave-sheild-breaks-sites-even-when-all-the-settings-are-turned-off/429151/4

Not the part that states that sites are broken. But the part where the user states when disabling all shields the sites are still broken.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.43(22.9.9.14) 
- Verified de-bouncing works fine on `https://dev-pages.brave.software/navigation-tracking/debouncing.html`
- Verified de-amp test from [#5812](https://github.com/brave/brave-ios/issues/5812)
----------
Verification passed on iPhone XR with iOS 15.6.1 running 1.43(22.9.9.14) 
- Verified de-bouncing works fine on `https://dev-pages.brave.software/navigation-tracking/debouncing.html`
- Verified de-amp test from [#5812](https://github.com/brave/brave-ios/issues/5812)
----------
Verification passed on iPad Pro with iOS 16.1 running 1.43(22.9.9.14) 
- Verified de-bouncing works fine on `https://dev-pages.brave.software/navigation-tracking/debouncing.html`
- Verified de-amp test from [#5812](https://github.com/brave/brave-ios/issues/5812)
