### ISSUE TITLE
Do not reset selected region when VPN reset config is tapped

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5978]
Change requested by our VPN vendor.

**Comment by Uni-verse** [comment]
Verified using version 1.44 (22.10.5.17) on the following device(s):

- iPhone 12 running iOS 16.x
- iPhone X running iOS 14.4.2
- iPad (7th Gen) running iPadOS 15.7

Using acceptance criteria from https://github.com/brave/brave-ios/pull/5989#issue-1366594909

- Verified `Region` is not reset but only the `hostname` may change when using `Reset VPN configuration`
- Verified `Region` is not reset using upgraded profile.

Before Reset | Before Reset | After Reset | After Reset
-|-|-|-
![IMG_0610](https://user-images.githubusercontent.com/17885425/194153748-79909856-439d-4947-961a-1dc30d2d7339.PNG) | ![IMG_0611](https://user-images.githubusercontent.com/17885425/194153755-5dc70122-509b-4431-8d47-b5c127d70bd6.PNG) | ![IMG_0612](https://user-images.githubusercontent.com/17885425/194153760-7657d5f5-c60f-45a2-a74e-e840ed1d9c4d.PNG) | ![IMG_0613](https://user-images.githubusercontent.com/17885425/194153763-395302a3-59ab-43fc-bf69-650b1a61b7f6.PNG)
![IMG_3732](https://user-images.githubusercontent.com/17885425/194153977-92c177d9-9d58-4e8b-802d-c390d626346f.PNG) | ![IMG_3736](https://user-images.githubusercontent.com/17885425/194153994-e572cfe7-6818-4e88-b1c0-b132882ff3f1.PNG) | ![IMG_3737](https://user-images.githubusercontent.com/17885425/194153999-84487d74-8eed-49b3-a12e-6ede79c79b31.PNG) | ![IMG_3735](https://user-images.githubusercontent.com/17885425/194153988-4a51e16c-6a26-4bee-a1ec-39de4a5d9922.PNG)
