### ISSUE TITLE
iOS is not sending some URLs from History to Sync Engine

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#5979]
### Description: 

The history is not syncing with other devices in the sync chain If the URL entered doesnt include `www` and only including domain + subdirectory. This is happening also when the url entered is redirected.

### Steps to Reproduce 

1. Type in URL in address bar
2. Visit site
3. This will appear in History on iPhone but not on Desktop.

**Actual result:** 

The valid website entered is not synced with engine.

**Expected result:**

All valid Urls appeared in History should be synced.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
Any

**Device details:** 
Any

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information

This ticket is created after a report in browser side. https://github.com/brave/brave-browser/issues/25146 Reported by @Saoiray

**Comment by Uni-verse** [comment]
Verified using `1.43 (22.9.8.13)`

Test Devices:
iPhone 12 Pro & XR | iOS 15.5
iPad (7th Gen) | iOS 15.5
iPhone X | iOS 14.4.2

Using STR in https://github.com/brave/brave-ios/issues/5979#issue-1364730398

- Ensured `URL` that the user entered into the `URL box` is sent to sync chain and shows up on `desktop` and other devices.
- Ensured history opened via `bookmarks` is sent to sync chain and shows up on desktop.
- Ensured history is updated on other `iOS devices` in the sync chain.
- Ensured enter `www` and the `domain` will still be sent to sync chain like before.
- Ensured sync chain is updated when user `deletes` history.
- Ensured sync chain compatibility between iOS 15.x & iOS 14.x devices.

Example | Example | Example | Example
-|-|-|-
![IMG_0552](https://user-images.githubusercontent.com/17885425/189224947-f2cbc47a-f836-4a34-ac1e-e2b3211a9da0.PNG) | ![IMG_3580](https://user-images.githubusercontent.com/17885425/189224584-52a3c12f-a285-45ce-872c-73e202a22524.PNG) | ![Screen Shot 2022-09-08 at 4 36 45 PM](https://user-images.githubusercontent.com/17885425/189225326-38dffa81-b4b7-4c25-bd90-ea87662d991e.png) | ![screenshot-1662669572746](https://user-images.githubusercontent.com/17885425/189224861-c4ffb608-5ab3-482b-b75a-23142d76a7c0.png)
