### ISSUE TITLE
Full Screen - Popover Callout Optimizations

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#5981]
- Callout Manager should be moved to Onboarding target and the responsibility of logic should be evaluated outside Browser.

- Present Callout logic should be unified so when the presentation logic is changed or any alteration to callouts (edits / remove / add) can be easily done

- Onboarding popups should be dismissible by tapping outside of them When the popup shows up, when you tap outside of it the view should be dismissed

**Comment by soner-yuksel** [comment]
@iccub alterations is made to this ticket so while editing for 1 click dismissal, some useful changes can be made to callout logic and target ownership of logic.

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.51 (23.5.15.14)`

Using Test Plan in https://github.com/brave/brave-ios/pull/7292#issue-1675450140

- Ensured Link Subscription, Default Browser, VPN and Bottom Bar callouts are presented and user is able to dismiss by tapping outside of the pop-up

Link Subscription | Default Browser | Bottom Bar | VPN
-|-|-|-
![IMG_3205](https://github.com/brave/brave-ios/assets/17885425/b18d1324-c1fb-460f-a99f-5d45acd949f9) | ![IMG_3207](https://github.com/brave/brave-ios/assets/17885425/d8df74fe-4676-4086-8c7f-30c3256d1714) | ![IMG_3204](https://github.com/brave/brave-ios/assets/17885425/12c3cc4b-2269-450c-bc54-18a6aba7b53a) | ![IMG_3208](https://github.com/brave/brave-ios/assets/17885425/a3b5594f-93ab-424f-89c9-8c54c7745cca)
