### ISSUE TITLE
When playing next item automatically, item is not highlighted in playlist.

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#5982]
### Description: 
When playing next item automatically, item is not highlighted in playlist.

### Steps to Reproduce 
  1. Navigate to site with videos or audio
  2. Add at least 2 items to playlist 
  3. Begin playing first item in playlist, then use gesture to scroll to right before the end of the recording. Allow the recording to run its course. 
  4. Next item should play automatically
  5. Observe which item is highlight/selected

**Actual result:** 
Next item is not highlighted

<table><tr><td>Example 1</td><td>Example 2</td></tr>

<tr><td>

https://user-images.githubusercontent.com/17885425/188922480-caf2db94-3e44-4b63-b3c3-39f758911c60.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/188923267-fd3830ab-fd77-4c44-a8a5-469614577ec8.MP4

</td></tr></table>

**Expected result:**
The item playing should be highlighted/selected in the playlist automatically

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easly, every time

**Brave Version:** 
1.43 (22.9.2.15)

**Device details:** 
iPhone

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
@Uni-verse Is this a regression?

**Comment by Uni-verse** [comment]
Verified using version `1.44 (22.10.7.17)`

`iPhone 12` running `iOS 16.x`
`iPhone XR` running `iOS 15.5`
`iPhone X` running `iOS 14.4.2`
`iPad (7th Gen)` running `iPadOS 15.7`

Using STR in https://github.com/brave/brave-ios/issues/5982#issue-1364878310

- Verified next video playing is highlighted 

Logged UI issue for iPad - https://github.com/brave/brave-ios/issues/6135

https://user-images.githubusercontent.com/17885425/194778054-f89bdf9b-c9ee-4927-9343-b079dc5b9a7f.mov
