### ISSUE TITLE
Tab-Sync UI Revamp Part 2 

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#5984]
### Description: 

This ticket is follow-up for https://github.com/brave/brave-ios/issues/3229

This is the second part of the UI Revamp after merging Tab Sync. 

It includes part of changes from https://www.figma.com/file/SLFLpMd7F7Tu58qGBdcUQG/iOS-Settings?node-id=1213%3A9562

Second section of improvements will include 

1. Tab List UI redesign
2. Sending Screen - animation with send

**Comment by Uni-verse** [comment]
Verified using `1.44 (22.10.13.13)` using the following device(s):

iPhone 12 | iOS 16.x
iPhone XR | iOS 15.x
iPhone X | iOS 14.x
iPad | iOS 15.x

<table><tr><td>

- Verified sending to `mobile` and `desktop` devices connected to sync chain
- Verified `send to your devices` flow includes sending screen as well as the sent screen
- Verified that `UI` conforms to the `figma` specs in dark and light modes 
- Verified tab shared can be loaded on the other end when received
- Verified sending to devices on an `upgraded profile`

Logged: 

- https://github.com/brave/brave-ios/issues/6173
- https://github.com/brave/brave-ios/issues/6174
- https://github.com/brave/brave-ios/issues/6175

</td><td>

https://user-images.githubusercontent.com/17885425/195702102-2b98f17b-dc1b-4512-8116-d570739b7301.mov

</td></tr></table>


<details><summary>iPhone</summary>

**Sending to Mobile Devices**

Send to your devices list | Sending | Sent
-|-|-
![IMG_3902](https://user-images.githubusercontent.com/17885425/195699008-66ec2e82-3933-44f8-b6cf-01bb41942eb1.PNG) | ![IMG_3903](https://user-images.githubusercontent.com/17885425/195699032-be4a46cf-a9d1-48c6-b0d5-6231d4862fde.PNG) | ![IMG_3904](https://user-images.githubusercontent.com/17885425/195699056-58ac8e16-b2a1-4348-9e4b-ca52260815b4.PNG)
![IMG_3905](https://user-images.githubusercontent.com/17885425/195699087-c7098e2d-d161-4508-ba9a-e5772e56dc8f.PNG) | ![IMG_3906](https://user-images.githubusercontent.com/17885425/195699111-a58bb7a4-afc6-4e1e-a815-23b2633f4611.PNG) | ![IMG_3907](https://user-images.githubusercontent.com/17885425/195699127-09b75092-8882-4fec-ace7-cdfb7bbbdc76.PNG)


**Sending to Desktop**

List | Sending | Sent
-|-|-
![IMG_3908](https://user-images.githubusercontent.com/17885425/195699146-9c32092e-fe6e-437f-b935-2ac94c92c346.PNG) | ![IMG_3909](https://user-images.githubusercontent.com/17885425/195699156-9e88b21e-b236-4570-8021-0ba9e99e50ed.PNG) | ![IMG_3910](https://user-images.githubusercontent.com/17885425/195699167-bb4d7811-3b12-46a3-8608-de2cac2aed6d.PNG)

</details>

<details><summary>iPad</summary>

List | Sending | Sent
-|-|-
![IMG_0652](https://user-images.githubusercontent.com/17885425/195703608-c12f646a-2332-440c-a3dd-c28e4eb823cd.PNG) | ![IMG_0653](https://user-images.githubusercontent.com/17885425/195703630-55d5be10-ad46-44d1-814b-bf329fd543bd.PNG) | ![IMG_0654](https://user-images.githubusercontent.com/17885425/195703637-99646cf8-c3ba-4cc0-8936-9875511c86e6.PNG)
![IMG_0660](https://user-images.githubusercontent.com/17885425/195704059-32efc774-bae3-4810-ad4f-1670b0041e5b.PNG) | ![IMG_0650](https://user-images.githubusercontent.com/17885425/195704100-8474a5b7-5f72-487b-b327-de1ce4e4bbfd.PNG) | ![IMG_0651](https://user-images.githubusercontent.com/17885425/195704102-8f02592f-3358-4987-aab9-da5aee9d3e61.PNG)

</details>
