### ISSUE TITLE
Hamburger menu should bring up Settings menu

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#60]
Hamburger menu brings up bookmark settings
![image](https://user-images.githubusercontent.com/17010094/41775976-04c8dfc2-75f4-11e8-8751-cb0930be76e4.png)

**Comment by jhreis** [comment]
This is correct behavior. Brave v1 hamburger menu opens this same menu, just on the side panel.

**Comment by tmancey** [comment]
@srirambv Are you happy for us to close this issue as won't fix, based upon @jhreis above comment?

**Comment by srirambv** [comment]
Its good enough for the first iteration. But would be good to have settings pop up for second iteration as its a general flow to show the settings menu from hamburger. The panel does look (empty) bad and useless for someone who doesn't use bookmarks.

**Comment by jhreis** [comment]
This is the exact same behavior as v1, any changes to this menu will need to go through full design iterations.

**Comment by jamesmudgett** [comment]
Hamburger should not open settings directly.
