### ISSUE TITLE
Brave Ads issuers fail to update

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#6001]
Basically a copy of https://github.com/brave/brave-browser/issues/25266 as it was only created via https://github.com/brave/brave-browser and we need an issue on `iOS` so we don't forget to QA/verify that ads are working as expected.

> 

## Description 

Brave Ads issuers fail to update on iOS, meaning ads will never be shown.

## Steps to Reproduce

   1. Fresh install
   2. Launch browser

## Actual result:

`Issuers already up to date` appears in the Rewards diagnostic log

## Expected result:
`Updated issuers` should appear in the Rewards diagnostic log

## Reproduces how often: 

Easily reproduced

## Version/Channel Information:

- Can you reproduce this issue with the current release? No
- Can you reproduce this issue with the beta channel? Yes
- Can you reproduce this issue with the nightly channel? Yes

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? N/A
- Does the issue resolve itself when disabling Brave Rewards? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by kjozwiak** [comment]
CCing @kylehickinson @iccub just as a heads up 👍

**Comment by kjozwiak** [comment]
Closing as the above as merged into `1.44.x` via https://github.com/brave/brave-core/pull/15033#pullrequestreview-1104816821.

**Comment by Uni-verse** [comment]
Verified using version `1.44 (22.10.14.13)` on the following device(s):

iPhone 12 running iOS 16.x
iPhone XR running iOS 15.x
iPhone X runnning iOS 14.x
iPad running iOS 15.x

- Ensured ads are working after enabling brave rewards
- Ensured inline ads are showing up in the news feed

iPhone Example | iPhone Example | iPhone Example | iPad Example 
-|-|-|-
![IMG_3922](https://user-images.githubusercontent.com/17885425/195885421-0d2502d1-8ba0-4900-9a22-882d89c54b37.PNG) | ![IMG_3923](https://user-images.githubusercontent.com/17885425/195885423-c6080dab-77e8-47ae-a400-3fa7414a7905.PNG) | ![IMG_3924](https://user-images.githubusercontent.com/17885425/195885428-5fca79db-3570-4d30-9c4a-bc63fb5171e4.PNG) | ![IMG_0681](https://user-images.githubusercontent.com/17885425/195885448-3b0600da-7b39-42d7-abc2-b88828dcc398.PNG)
