### ISSUE TITLE
Include option for users to hide privacy stats and favorites from the NTP 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6003]
### Description: 
https://github.com/brave/brave-browser/issues/22921

Details TBD, we may be able to follow android

**Comment by iccub** [comment]
@Sam-Sibley for settings placement, name and icon

**Comment by anthonypkeane** [comment]
Possible Design

<img width="745" alt="Screenshot 2022-09-19 at 3 08 09 pm" src="https://user-images.githubusercontent.com/7606853/191110860-58df9f40-5f0d-42c1-9a4f-963ca93a3c2f.png">

**Comment by Uni-verse** [comment]
Verified using `1.44 (22.10.10.19)` using the following device(s):

iPhone 12 | iOS 16.x
iPhone XR | iOS 15.x
iPhone X | iOS 14.x
iPad (7th Gen) | iPadOS 15.x


<details><summary>Privacy Hub - PASS</summary>

Verified the following use case(s):

- Privacy Hub is shown by default
- Disabling Privacy Hub via NTP
- Disabling Privacy Hub via settings switch
- Loading NTP with only Privacy Hub enabled
- Re-enabling Privacy Hub after it has been disabled
- Disabling Privacy Hub in Private Browsing mode
- With Favorites being enabled and privacy hub disabled on multiple tabs, re-enabling privacy hub and disabling favorites will update the tabs when user loads them.

Example | Example | Example
-|-|-
![IMG_3878](https://user-images.githubusercontent.com/17885425/195186130-cbb0d821-428b-447a-9047-ba86d92309a4.PNG) | ![IMG_3872](https://user-images.githubusercontent.com/17885425/195186254-4d5d583c-870e-4e6f-b119-177d69f55848.PNG) | ![IMG_3879](https://user-images.githubusercontent.com/17885425/195188138-80593d94-f8c4-4cfd-a1ef-cf44ccf241fb.PNG)


</details>

<details><summary>Favorites - PASS</summary>

Verified the following use case(s):

- Favorites are showing by default
- Disabling Favorites with the settings switch under `New Tab Page` will remove Favorites from each open tab
- Re-Enabling Favorites
- Creating new favorites using the share menu will also respect the switch

Example | Example
-|-
![IMG_3876](https://user-images.githubusercontent.com/17885425/195189909-62d69c07-f4b4-4519-aafe-f8a343423210.PNG) | ![IMG_3873](https://user-images.githubusercontent.com/17885425/195190067-25be999e-68c4-4d16-aaeb-411a12b0dbc6.PNG)

</details>


<details><summary>Settings Menu - PASS</summary>

- Verified widget switch are situated in the New Tab Page settings menu
- Verified user is able to toggle switches
- Verified user is able to access background images sub menu
- Verified disabling sponsored images will show normal/traditional backgrounds

Example | Example 
-|-
![IMG_3879](https://user-images.githubusercontent.com/17885425/195190616-837539ab-21a0-460b-a27c-5d979ff909d5.PNG) | ![IMG_3877](https://user-images.githubusercontent.com/17885425/195190652-eae3eb80-c2fc-4d7b-a078-1814efa10555.PNG)

</details>


<details><summary>Testing on iPads</summary>

- [x] Menu 
- [x] Favorites
- [x] Privacy Hub
- [x] BP Mode
- [x] Empty NTP
- [x] En-enabling
- [x] Disabling/Enabling Sponsored images

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_0640](https://user-images.githubusercontent.com/17885425/195192197-c674d4d4-9a3c-4775-b0ee-eda1c52c0180.PNG) | ![IMG_0641](https://user-images.githubusercontent.com/17885425/195192217-e6297e6d-f284-4c21-bd7c-9686655c2352.PNG) | ![IMG_0642](https://user-images.githubusercontent.com/17885425/195192241-1bad99c5-fa76-425d-8fcf-e7c113021128.PNG) | ![IMG_0643](https://user-images.githubusercontent.com/17885425/195192271-5d19998d-34b4-45af-94d0-591df2396064.PNG) | ![IMG_0644](https://user-images.githubusercontent.com/17885425/195192302-9816bebc-405c-428e-a0c8-be30d75e2b18.PNG) | ![IMG_0645](https://user-images.githubusercontent.com/17885425/195192333-19026280-c0c8-4f7c-a65d-e322ad23f2f6.PNG)


</details>
