### ISSUE TITLE
Support Solana Dapp transactions in Transaction Parser

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6004]
### Description: 

Need to support two Solana dapp transaction types in our `TransactionParser`: `SolanaDappSignAndSendTransaction` & `SolanaDappSignTransaction`.

We should be able to parse the from & to address for the transaction, the gas fee, and decode the instructions for the 'Details' tab of Transaction Confirmation.

### Additional Information

Currently desktop/core is using Solana Web3 library in [transaction-parser.ts](https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/common/hooks/transaction-parser.ts#L274-L333) & [solana-instruction-utils.ts](https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/utils/solana-instruction-utils.ts) to parse these transactions. We should wait for instruction decoding to be available:
https://github.com/brave/brave-browser/issues/23960
https://github.com/brave/brave-browser/issues/23961

**Comment by StephenHeaps** [comment]
I've updated the milestone as Solana Dapps has been moved to v1.47 release for iOS.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.47 (23.1.16.16)
- Verified steps from [#6211](https://github.com/brave/brave-ios/pull/6211)
- Verified transaction instruction details are shown similar to Desktop 

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (16.2)
-- | -- | -- 
<video src=https://user-images.githubusercontent.com/17010094/213160295-067e7060-b25e-4bcc-b525-fbea653e0f40.MP4> | <video src=https://user-images.githubusercontent.com/17010094/213160369-ad57917c-2c2e-4e61-87ce-f2853579f151.MP4> | <video src=https://user-images.githubusercontent.com/17010094/213160283-49bda7e0-32fa-4859-8aa3-d7248c3e7191.MP4>
