### ISSUE TITLE
Add Solana Sign Transaction / Sign All Transactions panel

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6005]
### Description: 

We'll need to add 2 new request types (`BraveWallet.SignTransactionRequest` / `BraveWallet.SignAllTransactionsRequest`)  to `PendingRequest` & `WebpageRequestResponse` enums, and use this new view in `RequestContainerView`

Sign Transaction:
<img width="316" alt="sign-transaction-1" src="https://user-images.githubusercontent.com/5314553/189911846-7861c796-a8da-4567-adc4-b43853e817f1.png"> | <img width="320" alt="sign-transaction-2" src="https://user-images.githubusercontent.com/5314553/189911860-01aa74f5-137e-4931-8fd5-e75cda7c7bd0.png">
--|--

Sign All Transactions (multiple):

<img width="318" alt="sign-all-transactions-1" src="https://user-images.githubusercontent.com/5314553/189912174-7a900018-e9d5-4b62-bef4-ac6de5b60756.png"> | <img width="319" alt="sign-all-transactions-2" src="https://user-images.githubusercontent.com/5314553/189912179-09036ae1-3d5c-4221-b74b-68d95af93a2d.png">
--|--

### Additional Information

https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/components/extension/sign-panel/sign-transaction-panel.tsx

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46 (22.12.6.19)
- Verified steps from [ brave/brave-ios#6245](https://github.com/brave/brave-ios/pull/6245)
- Verified able to sign and send transactions on Solana 
- Verified able to sign messages on Solana 
- Encountered
   - https://github.com/brave/brave-ios/issues/6567
   - https://github.com/brave/brave-ios/issues/6569
   - https://github.com/brave/brave-ios/issues/6570
   - https://github.com/brave/brave-browser/issues/36694
   - https://github.com/brave/brave-ios/issues/6572

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (iOS 16.2)
-- | --  | --
<video src=https://user-images.githubusercontent.com/17010094/206163530-f7b75141-a8c0-4fbf-bda7-a6d73cd76234.MP4> | <video src=https://user-images.githubusercontent.com/17010094/206162467-1aa79d16-d2b3-4336-b3f5-ddd218741632.MP4> | <video src=https://user-images.githubusercontent.com/17010094/206164444-dd7e9450-3f82-4fe8-ae11-a632e7196dc6.MP4>

**Comment by StephenHeaps** [comment]
I've updated the milestone as Solana Dapps has been moved to v1.47 release for iOS. This ticket has been verified but remains behind a feature flag.
