### ISSUE TITLE
Wallet: Eth Dapps Permission Management Updates

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6010]
### Description: 
This issue is caused by #5945 which can only be verified with 1.45 + build.
#5945 has been closed since PR #[5991](https://github.com/brave/brave-ios/pull/5991) has been merged. However, this PR will change the UI for managing ETH Dapps permission. 
Please refer to  #5945 for the new UI, and please verify managing ETH Dapps permission is still working as expected.

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-ios/issues/5945#issuecomment-1265717506
