### ISSUE TITLE
Suppress Mobile “Switch to App” Annoyances

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6011]
### Description: 
Spec
https://bravesoftware.slack.com/archives/C03MMJ4CHEZ/p1661878378715489?thread_ts=1661878373.627779&cid=C03MMJ4CHEZ

Apply the switch to app suppression filter lists by default (this ticket).
Add a toggle to enable/disable the lists (future work - needs some UX thought).

**Comment by iccub** [comment]
Depends on https://github.com/brave/brave-ios/issues/5729

**Comment by Uni-verse** [comment]
Verified using version `1.44 (22.10.7.17)`

iPhone 12 running iOS 16.x
iPhone XR running iOS 15.5
iPhone X running iOS 14.4.2
iPad (7th Gen) running iPadOS 15.7

Testing was completed as a part of https://github.com/brave/brave-ios/issues/5729#issuecomment-1272390155

Issues logged: https://github.com/brave/brave-ios/issues/6145
