### ISSUE TITLE
HTTPS Everywhere fail when loading webpages

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#6012]
### Description: 
HTTPS Everywhere fail when loading webpages

### Steps to Reproduce 
  1. Visit `http://https-everywhere.badssl.com` in a new tab
  2. Page loads with red background, HTTPSE isn't working
  3. Visit `https://https-everywhere.badssl.com` in a second tab
  4. Page loads with green background, but shows `HTTPS Everywhere is not working`
  5. Toggle `Upgrade Connections to HTTPS`, still same result

**Actual result:** 

https://user-images.githubusercontent.com/17010094/190133950-08ddbf7b-a1a7-4185-84dc-d1bf4e09f44e.MP4

**Expected result:**
Should auto-upgrade to HTTPS when available

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.43(22.9.9.14)

**Device details:** 
iPhone XR (iOS 15.6.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? Yes, same in Safari as well 

![image](https://user-images.githubusercontent.com/17010094/190134234-cef251cf-0793-4c18-af9b-8ea65348de00.png) | ![image](https://user-images.githubusercontent.com/17010094/190134258-2d529c52-ead7-4b4f-8790-cd7f8f4e6304.png)
-- | --

### Additional Information
cc: @iccub @Brandon-T @cuba @Uni-verse @kjozwiak

**Comment by Brandon-T** [comment]
Hi @srirambv,
It is not broken. This is expected. `badssl.com` is not in Apple's `https` upgrade list.

On iOS 15+ we are using Apple's `HTTPSUpgrade` built into WebKit.
They have a specific list of websites that they care about that will upgrade automatically.

For example if you went to `http://wikipedia.org/` (http) it will upgrade to `https://wikipedia.org/` (https).
On iOS 14, we use our own lists, so we are upgrading the site to `https` ourselves.

**Comment by srirambv** [comment]
Thanks @Brandon-T. Yes your steps work fine. Will update the regression test plan so we can check it going forward. Closing the issue as invalid.
