### ISSUE TITLE
Device with PB only mode causes the main device to show onboarding message on Tabs sync 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#6013]
### Description: 
Device with PB only mode causes the main device to show onboarding message on Tabs sync 

### Steps to Reproduce 
Device 1: Set to normal tabs browsing
Device 2: Set to Private browsing only mode

1. Add browsing history on device 1
2. Create a sync chain on the device and enable all sync switches
3. Add device 2 to the sync chain and enable all sync switches
4. Device 1 shows onboarding message in sync tabs in tab tray
5. Device 2 shows all the history from device 1 sync'd under device name
6. Go back to device 1 and click on Start a sync chain , takes onboarding to create a new sync chain but its already created and has the device linked

**Actual result:** 

Device 1 with normal tabs | Device 2 with PB only mode
-- | --
<img width=290 src=https://user-images.githubusercontent.com/17010094/190192327-a17192cd-7817-43db-9a0e-e51a23913de6.png> | <img width=350 src=https://user-images.githubusercontent.com/17010094/190192408-da4fa1cd-3f61-4786-aed5-f76b7df5d78a.png>

**Expected result:**
Do not show onboarding when sync chain is already created

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.43 (22.9.9.14)

**Device details:** 
Device 1: iPhone XR (iOS 15.6.1)
Device 2: iPhone 7+ (iOS 14.8.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @soner-yuksel @Uni-verse @kjozwiak

**Comment by soner-yuksel** [comment]
This behaviour which causes the the bug showing wrong empty state ,actually happens 
when the device 

- has successfully joined the sync chain
- has enabled the open tabs as sync type
but - has **_no_** synced sessions from other devices from the chain (this encapsulates the case there is only one device in sync chain)

**Comment by Uni-verse** [comment]
Verified using version `1.44 (22.10.7.17)`

`iPhone 12` running `iOS 16.x`
`iPhone XR` running `iOS 15.5`
`iPhone X` running `iOS 14.4.2`
`iPad (7th Gen)` running `iPadOS 15.7`

Using STR from https://github.com/brave/brave-ios/issues/6013#issue-1373162822

- Verified sync tab screen does not show onboarding flow when sync chain is created.
- Verified `Show Sync Settings` is displayed 
- Verified tapping on `Show Sync Settings` will display the sync settings

iPhone | iPad | Settings
-|-|-
![IMG_0078](https://user-images.githubusercontent.com/17885425/194775062-92ec5758-bfeb-4608-9821-4cff4f480869.PNG) | ![IMG_0627](https://user-images.githubusercontent.com/17885425/194775063-df955ec1-7a40-4a8a-9e25-73ec58c15f1a.PNG) | ![IMG_0628](https://user-images.githubusercontent.com/17885425/194775145-1c60d596-7d15-4549-9fd2-69716ec67198.PNG)

Test Scenario 1 under https://github.com/brave/brave-ios/pull/6028#issue-1376272893

- Verified enabling sync chain from tab sync page
- Verified leaving open tabs disabled will show enable tab syncing in the tab sync flow
- Verified tapping on enable tab syncing show final state of the flow

iPhone | iPad
-|-
![IMG_3862](https://user-images.githubusercontent.com/17885425/194775901-40b2c351-c82c-43db-92a3-6380b5c7d00f.PNG) | ![IMG_0629](https://user-images.githubusercontent.com/17885425/194775899-8928fa1c-67fe-4b3f-a52a-3e5eb69e245b.PNG)
