### ISSUE TITLE
improving `Make Brave default browser` panel/screen during onboarding

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#6014]
### Description: 

I think we can improve the `make brave the default` panel/screen on devices with bigger screens, specifically `iPad` devices. I think we can improve the following:

* make it larger horizontally as it looks like we're trying to squeeze everything inside a small vertical modal
* decrease the size of the `Not now` text below the `Set as default browser` (seems to be a lot larger than anything else in the panel)

### Steps to Reproduce
 
  1. download/install the latest version of `Brave` (either version works as this has been an issue for a while)
  2. start running through the onboarding and you'll notice that the `Default Browser` 

**Actual result:** 

![IMG_0375](https://user-images.githubusercontent.com/2602313/190226732-16ab91be-e636-43c4-8700-a751516c5d28.PNG)

**Expected result:**

I think we can make it look a bit better and more symmetrical compared to what we have now. Seems like we're squeezing too much inside a small vertical space. For example, the text portion looks squeezed.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases mentioned above.

**Brave Version:** 

* `1.42 (22.8.15.22)`

**Device details:** 

* `iPad Air (3rd Gen)` running `iOS 16` - **Reproduced**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

**Comment by Uni-verse** [comment]
Verified using version `1.45 (22.10.28.19)` using devices below:

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPads - iPad OS 16.x, 15.x

- Confirmed that onboarding dialog is larger horizontally

Tablet Example | Tablet Example | Mobile Example
-|-|-
![IMG_0011 2](https://user-images.githubusercontent.com/17885425/199094720-c11a12e6-bc7c-4cc1-83a0-52eba8287cb2.PNG) | ![IMG_0730 2](https://user-images.githubusercontent.com/17885425/199094753-3a73e3f2-f17a-495c-b366-183f74f21ca7.PNG) | ![IMG_0154 2](https://user-images.githubusercontent.com/17885425/199095045-003eacd8-e425-44f0-90b2-d1bb2196784a.PNG)
