### ISSUE TITLE
NTP SI on iOS does not respect wallpaper specific logo overrides

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6015]
### Description: 

When there's a specific logo passed in with a NTP SI logo it is not shown and instead the main campaign logo is always shown

### Steps to Reproduce:

On Brave Dev (staging campaigns) open tabs until you begin to see NTP SI's. They will rotate through 3 different Brave Search campaigns. 

## Expected:

> SI `#1` - Woman walking away from camera, logo text is “Logo “Private, independent, & open. Search without a trace.” it should link to https://search.brave.com/?source=Private-Independent-Open-Search-Without-A-Trace
> SI `#2` - Woman walking with dog away from the camera, logo text is “Private, independent, & open. The search engine that doesn’t track you.” It should link to [https://search.brave.com/?source=Private-Independent-Open-The-Search-Engine-That-Doesn't-Track-You](https://search.brave.com/?source=Private-Independent-Open-The-Search-Engine-That-Doesn%27t-Track-You)
> SI `#3` - Logo text is “Explore freely with our unbiased, private search engine.” It should link to https://search.brave.com/?source=Explore-Freely (Same background as SI `#1` but different logo and URL.)

## Actual:

You only see the main campaign logo regardless of wallpaper which has the logo "Private, independent, & open. Search without a trace"

**Comment by Uni-verse** [comment]
Testing in Progress using Brave Dev `1.44 (22.10.13.13)` using the following device(s):

iPhone 12 | iOS 16.x
iPhone XR | iOS 15.x
iPhone X | iOS 14.x
iPad | iOS 15.x

SI 1 (Girl walking away from camera)

- Verified logo text is “Logo “Private, independent, & open. Search without a trace.”
- Verified links to https://search.brave.com/?source=Private-Independent-Open-Search-Without-A-Trace

Example | Example
-|-
![IMG_0107](https://user-images.githubusercontent.com/17885425/195724497-d0b34055-167a-4e46-8a30-c0525eec230f.PNG) | ![IMG_0104](https://user-images.githubusercontent.com/17885425/195724324-b75b4ab1-5240-413e-9db5-2a6ba26786e1.PNG)


SI 2 - (Woman walking with dog away from the camera) 

- Verified logo text is “Private, independent, & open. The search engine that doesn’t track you.” It should link to 
- Verified links to https://search.brave.com/?source=Private-Independent-Open-The-Search-Engine-That-Doesnt-Track-You

Example | Example
-|-
![IMG_0105](https://user-images.githubusercontent.com/17885425/195724328-7cac7a49-3d89-4eb7-b1a3-a002edb31305.PNG) | ![IMG_0106](https://user-images.githubusercontent.com/17885425/195724496-02f39224-789b-4c43-9273-86168e812408.PNG)


SI 3 

- Verified Logo text is “Explore freely with our unbiased, private search engine.” 
- Verified links to https://search.brave.com/?source=Explore-Freely

Example | Example
-|-
![IMG_0108](https://user-images.githubusercontent.com/17885425/195725155-39aad3c2-f815-46d1-b4bf-28bb815b9c7f.PNG) | ![IMG_0109](https://user-images.githubusercontent.com/17885425/195725165-69417101-8937-457d-bd05-2e370b473db7.PNG)

iPad

SI 1 | SI 2 | SI 3
-|-|-
![IMG_0662](https://user-images.githubusercontent.com/17885425/195726115-84e9f34f-2167-4ee2-9431-96df21760c51.PNG) | ![IMG_0663](https://user-images.githubusercontent.com/17885425/195726120-3cebccde-c08b-4685-afee-e88a8bde5a16.PNG) | ![IMG_0664](https://user-images.githubusercontent.com/17885425/195726126-567deaee-0b81-4af0-9afc-15805e64ffc6.PNG)
