### ISSUE TITLE
URL does not update on session restored tabs

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6023]
### Steps to Reproduce 
1. Open wikipedia in one tab
2. Relaunch the app
3. Wikipedia tab restores, go to youtube on this tab
4. Go to a random video
5. Notice the url still points to the youtube main page
6. This will work after refresh, if you navigate back to main YT page it still breaks

**Actual result:** 
Wrong URL in the address bar

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100% for me

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by soner-yuksel** [comment]
@iambrianfung is reporting issue is not fixed https://github.com/brave/brave-ios/issues/6106

I tried to replicate anyways I can with restored tabs. fresh tabs, external link etc but couldn't manage.

QA please do a detailed test and try to find out what are the reliable, or intermittent steps

**Comment by Uni-verse** [comment]
@soner-yuksel There is a similar issue atm impacting playlist, its most likely related to this issue. If I add a video to playlist, any other video I navigate to will show that its added already. Also, the video description in the playlist if you open the playlist in another video url. 

Steps to reproduce:
1. Open a new tab
2. Navigate to YT
3. Click on random video, add to playlist
4. Navigate to another video
5. Observe that playlist shows video is add
6. Now, open playlist from menu

Actual: Notice that the video description doesn't match the playlist url added (it shows the description for the current page user is visiting) 


https://user-images.githubusercontent.com/17885425/194778919-bfa15f2d-9ad8-4fd0-a529-7c3c4fbf65d4.MP4



cc: @iccub

**Comment by Uni-verse** [comment]
> @soner-yuksel There is a similar issue atm impacting playlist, its most likely related to this issue. If I add a video to playlist, any other video I navigate to will show that its added already. Also, the video description in the playlist if you open the playlist in another video url.
> 
> Steps to reproduce:
> 
> 1. Open a new tab
> 2. Navigate to YT
> 3. Click on random video, add to playlist
> 4. Navigate to another video
> 5. Observe that playlist shows video is add
> 6. Now, open playlist from menu
> 
> Actual: Notice that the video description doesn't match the playlist url added (it shows the description for the current page user is visiting)
> 
>  RPReplay_Final1665345733.MP4 
> cc: @iccub

This was resolved -  https://github.com/brave/brave-ios/issues/6133

**Comment by Uni-verse** [comment]
Verified on `1.44 (22.10.13.13)` using the following device(s):

iPhone 12 | iOS 16.x
iPhone XR | iOS 15.x
iPhone X | iOS 14.x
iPad (7th Gen) | iOS 15.x

Not able to reproduce this anymore using the STR in https://github.com/brave/brave-ios/issues/6023#issue-1375930223
