### ISSUE TITLE
Add Brave Ads status headers to search.brave.com

### ISSUE THREAD

**Issue by jsecretan** [brave/brave-ios#6024]
### Description: 
In preparation for Brave Ads on Brave Search, it is helpful for the Brave Search backend to understand whether the requesting browser has Brave Ads enabled. As such, we should add a header to any call to Brave Search (and its associated dev/staging environments), whether originating from the main search box or the Omnibox: `X-Brave-Ads-Enabled` should be set to `1` when Brave Ads is enabled on the device.

This issue may provide some guidance on the best way to accomplish that: https://github.com/brave/brave-ios/issues/887

**Comment by tmancey** [comment]
@brave/ios ok if I pick this up, or would you prefer to assign to somebody else? Thanks

**Comment by iccub** [comment]
go ahead @tmancey

**Comment by tmancey** [comment]
Updated https://github.com/brave/brave-browser/wiki/Custom-Headers

**Comment by Uni-verse** [comment]
Verified using version `1.45.2 (22.11.18.20)` on the following device(s):

`iPhone 12 Pro` -` iOS 16.x`
`iPhone X` - `iOS 14.x`
`iPads` - `iPadOS 16.x, 15.x`

### Clean Profile

- Verified X-Brave-Ads-Enabled header is not appended to the request

![Screen Shot 2022-11-23 at 11 17 22 AM](https://user-images.githubusercontent.com/17885425/203601683-4a493c0d-47ef-40a7-ad69-5fe6f2bc6629.png)


### Ads Enabled

- Verified X-Brave-Ads-Enabled header is appended to the request when using search.brave via the omnibox or the main search box

![Screen Shot 2022-11-23 at 11 17 11 AM](https://user-images.githubusercontent.com/17885425/203601718-acb24bb9-ba7a-47c9-b5d5-0806c72d5e9f.png)


### Ads Disabled

- Verified Disabling Rewards will remove the header from request

![Screen Shot 2022-11-23 at 11 18 27 AM](https://user-images.githubusercontent.com/17885425/203601901-c9675b6d-b93a-4b25-9de3-6d45df6da4b8.png)
