### ISSUE TITLE
Privacy Hub NTP prompt can show while in overlay mode

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6025]
![Simulator Screen Shot - iPad Pro (12 9-inch) (5th generation) - 2022-09-16 at 10 22 08](https://user-images.githubusercontent.com/6950387/190663444-5fa815f9-00d4-4a73-8b51-efd0a4ed9e6a.png)

**Comment by srirambv** [comment]
Steps to repro

* Clean install 
* Do not interact with privacy hub 
* Visit pages so that stats value increase to a threshold where it triggers the notification
* Open a new tab so focus is set to URLbar
* Privacy hub notification is shown on top of NTP favourites rather than on stats

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.15.19)` on the following device(s):

iPhone XR - iOS 15.x
iPhone 12 - iOS 16.x
iPad (7th Gen) - iPadOS 16.x

Using STR based on https://github.com/brave/brave-ios/issues/6025#issuecomment-1342905725

- Verified NTP prompt doesn't show while in overlay mode

Example | Example
-|-
![IMG_0211](https://user-images.githubusercontent.com/17885425/208761789-3e72bdc3-215d-4a9f-b0e2-ee7aeb15b526.PNG) | ![IMG_0888](https://user-images.githubusercontent.com/17885425/208761835-3296f4e6-eb0c-4310-9d10-f42192650334.PNG)
