### ISSUE TITLE
removing blank area from shields panel

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#6027]
### Description: 

We should remove the extra blank spacing that's being added at the bottom of the shields panel. It doesn't seem necessary as it's not being used and it takes up a lot of unnecessary space.

### Steps to Reproduce 

  1. install any version of Brave (this issue has been around for some time)
  2. once installed, visit any random website and tap on the Brave Shields panel
  3. you'll notice that a large blank area is being added at the bottom that's not being used for anything

**Actual result:** 

![IMG_0376](https://user-images.githubusercontent.com/2602313/190693846-ebcca358-14b2-4372-9797-f56b8da2e421.PNG)

**Expected result:**

Should look similar to the below re: not displaying the large blank space at the bottom of the panel.

![image](https://user-images.githubusercontent.com/2602313/190693537-2fab3d02-bb66-4e35-ab39-69cc268a57b1.png)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases outlined above.

**Brave Version:** 

* `1.42 (22.8.15,22)`

**Device details:** 

* `iPad Air 3rd Gen` running `iOS 16.1` - **Reproduced the issue**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

**Comment by Uni-verse** [comment]
Verified using version `1.45 (22.10.28.19)` on `iPad` running `iPadOS 16.x` & `iPadOS 15.x`

Using STR in https://github.com/brave/brave-ios/issues/6027#issue-1376212410

- Verified that the blank areas in the shields panel are removed.
- Verified shield panel in landscape and portrait does not contain the blank spaces.

Example | Example
-|-
![IMG_0013 2](https://user-images.githubusercontent.com/17885425/199256131-38c5ba6f-4deb-4dd6-8966-15ed30f52620.PNG) | ![IMG_0731 2](https://user-images.githubusercontent.com/17885425/199256273-d3fd88ff-2834-4f29-90b2-05e347903def.PNG)
