### ISSUE TITLE
Tabs bar not visible by default for new users on iPad

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6034]
### Steps to Reproduce 
  1. Fresh install on an ipad

**Actual result:** 
No tabs bar visible

**Expected result:**
Should be there

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using `1.44 (22.10.5.17`) on `iPad (7th Gen)` running `iPadOS 15.7`

Tested the scenario in https://github.com/brave/brave-ios/pull/6035#issue-1379970034

- Ensured new users can see the tabs bar by default on iPad
- Ensured new users can disable tabs bar using Settings > Tabs Bar (OFF)
- Ensured sharing tabs doesn't display the tabs bar if it is disabled.

Example | Example 
-|-
![IMG_0614](https://user-images.githubusercontent.com/17885425/194369873-75c756c8-ed1f-4e93-bcf3-3afb89573541.PNG) | ![IMG_0615](https://user-images.githubusercontent.com/17885425/194369881-2d1a7ac9-9e39-43d4-abf7-ee0cf7ca875b.PNG)
