### ISSUE TITLE
Playlist enhancement - Folder starting point

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6042]
### Description: 
Context: https://bravesoftware.slack.com/archives/DED41F59S/p1663774202025089

Some music players like Spotify restart the user at the start of a playlist when they enter the list. There are many good reasons to do this and perhaps we should provide an option.

By Default, if a user enters a Playlist, we will start playing music/video from the beginning of that Playlist. However this functionality shouldn’t impact https://github.com/brave/brave-ios/issues/5940 or https://github.com/brave/brave-ios/issues/5959

This will require some UX and thinking and we can perhaps add this into the upcoming redesign @Sam-Sibley

**Comment by iccub** [comment]
Moving to a new ticket, this task needs more discussion https://github.com/brave/brave-ios/issues/6694
