### ISSUE TITLE
Verify Solana Account Creation for New Wallet

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6044]
Since this Core has uplifted this change to 1.44 https://github.com/brave/brave-core/pull/15135, we will need to verify Solana Account will be created when a new wallet is set up. 

Steps:
1. Create new wallet and check that Solana acc is created, default coin is Solana, and default network is Solana mainnet beta.
2. Restore wallet and check same conditions.
3. Check lock& restore case.
4. Check that if wallet was created before the update, solana won't be choosed as default and no solana account won't be created after the update.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.44 (22.9.29.15)
- Verified steps from issue description and [#6045](https://github.com/brave/brave-ios/pull/6045)
- Verified creating a new wallet automatically creates Solana account
- Verified restoring wallet from seed works fine and app doesn't go into infinite loop
----------
Verification passed on iPhone XR with iOS 15.6.1 running 1.44 (22.9.29.15)
- Verified steps from issue description and [#6045](https://github.com/brave/brave-ios/pull/6045)
- Verified creating a new wallet automatically creates Solana account
- Verified restoring wallet from seed works fine and app doesn't go into infinite loop
----------
Verification passed on iPad Pro with iOS 16.1 running 1.44 (22.9.29.15)
- Verified steps from issue description and [#6045](https://github.com/brave/brave-ios/pull/6045)
- Verified creating a new wallet automatically creates Solana account
- Verified restoring wallet from seed works fine and app doesn't go into infinite loop
