### ISSUE TITLE
Implement show account creation flow

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6046]
### Description: 

As part of Solana dapps work, we have a new `BraveWalletProviderDelegate` function `func showAccountCreation(_ type: BraveWallet.CoinType)` which is called when a user tries to connect to a Solana dapp without a Solana account/keyring. As of 1.44, users will have a Solana account by default however users who setup their Wallet before 1.44 will not have one and we need to show the account creation flow when this delegate function is called.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46 (22.12.6.19)
- Verified steps from [#6075](https://github.com/brave/brave-ios/pull/6075)
- Verified account creation modal is shown when interacting with Solana Dapp
- Verified closing and reopening wallet panel shows the account creation screen
- Verified after account creation is done shows account connection screen
- Encountered [#6593](https://github.com/brave/brave-ios/issues/6593) on iOS 14 device

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (iOS 16.2)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/206154396-6c454368-563b-44f5-8990-624574f4ae1d.MP4> | <video src=https://user-images.githubusercontent.com/17010094/206154470-e620acda-9883-4dbb-8bbd-2c20b17c60f2.MP4> | <video src=https://user-images.githubusercontent.com/17010094/206154352-312d2760-5c66-40a9-98bd-2dc1339777d6.MP4>

**Comment by StephenHeaps** [comment]
I've updated the milestone as Solana Dapps has been moved to v1.47 release for iOS. This ticket has been verified but remains behind a feature flag.
