### ISSUE TITLE
Wallet: Move network selector to the left align with the connect button.

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6056]
Current:
![simulator_screenshot_4BCF0C73-44C5-4F7E-88C8-D5B7083DCF7B](https://user-images.githubusercontent.com/1187676/192037167-f3853550-0ef3-4514-8377-7c519183ae00.png)

New:
![Screen Shot 2022-09-23 at 2 52 43 PM](https://user-images.githubusercontent.com/1187676/192037352-9c69e64a-4c03-4657-a775-83055843a264.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46 (22.12.1.14)
- Verified test plan from [#6325](https://github.com/brave/brave-ios/pull/6325)
- Verified network selector is left aligned on panel
- Verified  buy/send/swap screen shows full network name

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (iOS 16.2)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/205114687-6c8b0f51-72d4-4e7f-94e8-a41caa9ff8d9.png> | <img width=240 src=https://user-images.githubusercontent.com/17010094/205111029-f71fb9a3-a06d-4fb0-8676-83a85ae83b52.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/205112109-6a7b2e5d-6bc4-493b-871f-be516e73f19a.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/205114749-19790148-983c-4e1c-aa33-73e4ee22dbd4.png> | <img width=240 src=https://user-images.githubusercontent.com/17010094/205111078-82c3268e-97c2-4de5-a9fc-bbb40709c27f.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/205112135-e78133c2-6e2d-4484-bd48-448099e78767.png>
