### ISSUE TITLE
Disable Clear browsing settings when in PB mode

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#606]
### Description: 
Disable Clear browsing settings when in PB mode otherwise leads to confusion similar to https://github.com/brave/brave-ios/issues/605

### Steps to Reproduce 
  1. Open Private tab
  2. Open settings and clear private tab
  3. All settings are shown and doesn't differentiate if its for normal or private tabs

**Actual result:** 
Disable Clear browsing settings when in PB mode

**Expected result:**
Disable clear private data option when PB mode is switched on 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
All

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
By PB mode do you mean "Private Browsing Only" or just when you're currently in a private tab?

**Comment by srirambv** [comment]
During Private browsing only mode

**Comment by kylehickinson** [comment]
Turning on private only browsing doesn't erase your history for regular tabs (it even currently keeps your regular tabs—which is a different issue: #580). So the user could definitely still clear their private data when they're browsing private only mode. After they do it once though if they never turn off private only mode then there'd be no more data to remove.

**Comment by jhreis** [comment]
We will be renaming this copy to add more clarity, which should help with this confusion, but this specifically we do not currently want.
