### ISSUE TITLE
Improve Favicon fetching

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6066]
## Test Plan:
- Test Favicons in History
- Test Favicons in Bookmarks
- Test Favicons in Sync-Chain (sync bookmarks and history)
- Test visiting a website, showing tab switcher with Favicon.
- Test visiting a website, showing tab switcher with Favicon, and close the tab, expect no crashes on tab close.
- Test Favicons in widgets

**Comment by Uni-verse** [comment]
Verified using version `1.48 (23.2.21.21)` on `iPhone 12`, `IOS 16.1` & `iPad (9th Gen)`, `iPadOS 15.6.1`

Test Scenarios: https://github.com/brave/brave-ios/issues/6066#issue-1388275914

**New Profile:**

- Ensured Favicons are showing up in `history`
- Ensured Favicons are showing up in `bookmarks`
- Ensured Favicons are displayed in the `tab switcher` when visiting urls
- Ensured Favicons are displayed when connecting to `sync chain` and enabling, history along with the defaulted bookmark preference.
- Ensured that `adding`, `editing` and `deleting` favorites works and not does cause crash. 
- Ensured that closing tabs does not cause crash
- Ensured that Favicons are displayed properly in `Brave Widgets` on the homescreen and on lockscreen widgets

**Upgraded Profile:**

- Ensured that Favicons are retained on upgraded profile in History, Bookmarks and for Favorites (NTP)
- Ensured that user is able to close tabs and tap on items in bookmarks and history.

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_0142 3](https://user-images.githubusercontent.com/17885425/220482200-c79d3034-2c83-4839-b310-85a88bfcf256.PNG) | ![IMG_0143 2](https://user-images.githubusercontent.com/17885425/220482208-2e249f51-34e8-4462-893c-030644eb3cfe.PNG) | ![IMG_0144](https://user-images.githubusercontent.com/17885425/220482226-a8b2bb0d-c48a-4050-b5c5-d1a357d1c43f.PNG) | ![IMG_0145 2](https://user-images.githubusercontent.com/17885425/220482250-01f21abe-aa30-4e38-b228-d646261bf6a1.PNG) | ![IMG_0146 2](https://user-images.githubusercontent.com/17885425/220482261-48ac3b5a-cc3d-47cc-8dfb-ce149557275f.PNG)
![IMG_4549](https://user-images.githubusercontent.com/17885425/220482430-2c5b8658-ba8c-43c5-85c3-22a38395f229.PNG) | ![IMG_4550](https://user-images.githubusercontent.com/17885425/220482433-8138f306-e945-43c8-ab9a-f3d2175aa693.PNG) | ![IMG_4551](https://user-images.githubusercontent.com/17885425/220482434-c33cbf45-1341-4947-ae76-d5f2f326a303.PNG) | ![IMG_4552](https://user-images.githubusercontent.com/17885425/220482435-2e631b07-b713-443a-b5d4-7930cdb5eef7.PNG) | ![IMG_4553](https://user-images.githubusercontent.com/17885425/220482437-8f84f52f-edda-4c55-9679-ba7dc968d4c4.PNG)
