### ISSUE TITLE
Add http://vid.puffyan.us/ to add to playlist bar

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6071]
### Description: 
Per: https://bravesoftware.slack.com/archives/CKJCXTP9B/p1664230502841389

Please add http://vid.puffyan.us/ to add to playlist bar

**Comment by Uni-verse** [comment]
Verified using 1.44 (22.10.13.13) using the following device(s):

iPhone 12 | iOS 16.x
iPhone XR | iOS 15.x
iPhone X | iOS 14.x
IPad | iPadOS 15.x

- Verified playlist supports https://vid.puffyan.us
- Verified playlist icon shows up when loading video
- Verified user is able to add using the url bar, the share menu as well as long pressing on the video.

https://user-images.githubusercontent.com/17885425/195660296-e0aaa512-339e-42d5-adc9-e67d3ae24e2f.mov

**iPad UI**
![IMG_0649](https://user-images.githubusercontent.com/17885425/195662111-b9332b71-6fe4-4c6e-aef4-3b0c3768af2f.PNG)
