### ISSUE TITLE
UI built with SwiftUI List and Form backgrounds have the wrong colour on iOS 16

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6072]
### Description: 

**Prefix: Requires building with Xcode 14 and iOS 16 SDK**

On iOS 16 `List` and `Form` are no longer backed by `UITableView` which means the `UITableView` appearance overrides do not affect them so the background colours on them will not be the right ones

**Comment by Uni-verse** [comment]
Verified using version `1.45 (22.11.2.16)` on the following device(s):

iPhone 12 Pro - iOS 16.1
iPad (7th Gen) - iPadOS 16.x

- Verified general menu/settings, privacy hub and wallet view background colors have not regressed with Xcode 14 builds for iOS version 16.

iPhone
Example | Example | Example | Example
-|-|-|-
![IMG_4033](https://user-images.githubusercontent.com/17885425/199613164-c90d293d-f34e-47ce-b522-66754bccc533.PNG) | ![IMG_4034](https://user-images.githubusercontent.com/17885425/199613167-05551bbf-ef32-4b4c-9ec1-300ef0a6fcf3.PNG) | ![IMG_4038](https://user-images.githubusercontent.com/17885425/199613863-5da072b4-4ae3-4ca5-b467-ac03122fb7d0.PNG) | ![IMG_4039](https://user-images.githubusercontent.com/17885425/199613867-dcf78bdb-f920-4a4d-aa91-8701a90fd5af.PNG)

iPad 
Example | Example | Example | Example
-|-|-|-
![IMG_0733](https://user-images.githubusercontent.com/17885425/199614635-eeb37561-ee9f-4f17-8dad-c9e9ac0c9800.PNG) | ![IMG_0734](https://user-images.githubusercontent.com/17885425/199614646-f5a61efc-c563-4d31-b238-814d1495066d.PNG) | ![IMG_0735](https://user-images.githubusercontent.com/17885425/199614655-0bb81ade-6a0a-4e4c-a3b5-a7cc39c2351b.PNG) | ![IMG_0736](https://user-images.githubusercontent.com/17885425/199614663-5f220935-160c-44b7-b019-3833478958a4.PNG)
