### ISSUE TITLE
Dismiss tab tray when tapping on an empty space there

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6078]
Matching Safari functionality

**Comment by kylehickinson** [comment]
FYI this only seems to be the case when running in compact width layout (iPhone portrait or iPad with multitasking)

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.8.20)` on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.4.2
iPad - iPadOS 16.x, 15.x

- Verified tapping on the tab tray background closes the tab tray.
- Verified closing tab tray requires portrait orientation for iPhone devices, split functionality for iPads.

<table><tr><td>Example</td><td>Example</td></tr>

<tr><td>

https://user-images.githubusercontent.com/17885425/206813394-cdff7f46-c6ba-4097-880f-0d3b7cce2c7f.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/206813404-eaafd2e8-784b-4e10-8a7f-3838d97ed227.MP4

</td></tr></table>
