### ISSUE TITLE
Internal #903

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6079]
https://github.com/brave/internal/issues/903

**Comment by iccub** [comment]
Closed in https://github.com/brave/brave-ios/pull/5935

**Comment by Uni-verse** [comment]
Verified on `1.44 (22.10.17.13)` AND/OR `1.44 (22.10.14.13)` using the following device(s):

iPhone 12 | iOS 16.x
iPhone XR | iOS 15.x
iPhone X | iOS 14.x
iPad | iOS 15.x

Based on test plan in https://github.com/brave/internal/issues/903#issuecomment-1262471666

- Verified basic functionality for the following features: 

Playlist
Shields
Reader-Mode
Brave Talk
DeAMP
Request Blocking
Cosmetic Filters
Night Mode
Brave Wallet
Stats Reporting

Issues Logged: 

https://github.com/brave/brave-ios/issues/6192
https://github.com/brave/brave-ios/issues/6198
