### ISSUE TITLE
Closing locked wallet windows causes issues with bottom URL bar 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#6086]
### Description: 
Closing locked wallet windows causes issues with bottom URL bar 

### Steps to Reproduce 
  1. Clean install 
  2. Create wallet
  3. Wait for wallet to auto lock
  4. Wait for device to auto lock (not sure if needed)
  5. Unlock device and close wallet locked screen
  6. Bottom URL bar is not visible 

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/193253846-00b0c185-11f2-4735-8b83-b180b99866f4.png)

**Expected result:**
Should not messup bottom URL bar

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Happened once

**Brave Version:** 
1.44 (22.9.29.15)

**Device details:** 
iPhone XR (iOS 15.6.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @kylehickinson @brave/legacy_qa

**Comment by Uni-verse** [comment]
Verified using version `1.44 (22.10.14.13)` on the following device(s):

iPhone 12 running iOS 16.x
iPhone XR running iOS 15.x
iPhone X runnning iOS 14.x
iPad running iOS 15.x

Unable to reproduce issue using STR in https://github.com/brave/brave-ios/issues/6086#issue-1392249771

- URL bar is shown when closing wallet locked screen

<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/195882995-35597bef-f1c3-48f4-9eab-783787c33309.PNG">
