### ISSUE TITLE
Sending to another address using QR code is not working on IOS

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-ios#6087]
## Description 

Tried sending to a Metamask and Gamestop wallet via QR code but it couldn't read the QR code.

## Steps to Reproduce

   1. 
   2. 
   3. 

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by jamesmudgett** [comment]
Lets strip the "Ethereum:" part of the qr code data

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.44 (22.10.7.17)
- Verified steps from [#6088](https://github.com/brave/brave-ios/pull/6088)
- Verified scanning wallet QR code doesn't prefix network name 
- Verified for both Solana and Ethereum accounts

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.6.1) | iPad Pro (iOS 16.1 Beta)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/194861565-1ecaa2d0-64c1-4841-b379-80335f68fbcf.mp4> | <video src=https://user-images.githubusercontent.com/17010094/194861587-8ef3ca40-4c4f-4b07-835a-3696b941bf21.mp4> | <video src=https://user-images.githubusercontent.com/17010094/194861551-ba06fedc-fe8b-41a0-8f27-b116f87ec6e2.mp4>
