### ISSUE TITLE
Brave behaves as default browser despite settings menu showing Safari as default browser 

### ISSUE THREAD

**Issue by harr1424** [brave/brave-ios#6089]
### Description: 
I installed Brave browser and set it as the default browser on my iOS device.  Next, I switched my default browser to Safari. Clicking http/https links in other applications will launch Brave browser despite the settings menu for Brave browser showing Safari as the set default browser. 

### Steps to Reproduce 
  1. Install Brave browser for iOS 
  2. Set Brave as default browser
  3. From the iOS settings menu specific to Brave browser, set default browser to Safari
  4. Open links in other applications

**Actual result:** 
Links open in Brave and not Safari. 

**Expected result:**
Links should open in the browser displayed as default, in this case Safari. 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Reproduces with 100% of links across all applications. 

**Brave Version:** 
1.4.3 (22.9.9.14)

**Device details:** 
iPhone SE (iOS 1.0.2)

**Comment by kylehickinson** [comment]
This is unfortunately something out of our control since its controlled by the OS itself.

I recommend restarting your phone if this happens again, thanks.
