### ISSUE TITLE
Youtube shows ads regression

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6090]
Caused because we removed the `YoutubeAdblock.js` here https://github.com/brave/brave-ios/pull/6070

**Comment by Uni-verse** [comment]
Verified using `1.44 (22.10.5.17)` using the following device(s):

`iPhone 12` running `iOS 16.0`
`iPhone XR` running `iOS 15.5`
`iPhone X` running `iOS 14.4.2`
`iPad (7th Gen)` running `iPadOS 15.7`

Using test plan in https://github.com/brave/brave-ios/pull/6091#issue-1394923464

- Verified that preroll ads on youtube do not show up on normal and private tabs

Example | Example
-|-
![IMG_3756](https://user-images.githubusercontent.com/17885425/194586203-a141476b-0dfe-480d-b126-3537ecd8f901.PNG) | ![IMG_0618](https://user-images.githubusercontent.com/17885425/194587482-373c0372-8cf9-47c9-b14c-4fec5595f44c.PNG)
