### ISSUE TITLE
Wallet is using an obsolete password policy

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#6093]
iOS version of https://github.com/brave/brave-browser/issues/22817

**Comment by StephenHeaps** [comment]
~We should add a button/toggle to show/hide password with this ticket.~
Separated to: https://github.com/brave/brave-ios/issues/7181

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.2 running 1.60(23.11.7.17)
- Verified steps from [ #7182](https://github.com/brave/brave-ios/pull/7182)
- Verified minimum password length message is shown on both new wallet creation and when restoring wallet
