### ISSUE TITLE
missing url schema default to http instead of https and doesn't upgrade to https if http is not implemented

### ISSUE THREAD

**Issue by erwan-joly** [brave/brave-ios#6098]
### Description: 
When searching a domain with only https available. Browser will try loading http first, fail and won't load https (Even if upgrade connections to HTTPS is set to true).
Only way to make it load https is to specify it in the URL. https schema should be the default not http

### Steps to Reproduce 
  1. search for an URL with only HTTPS available example `marketracoon.com`
  2. enjoy the error `this site can't be reached`
  3. search for `https://marketracoon.com ` notice it is up

**Actual result:** 
this site can't be reached

**Expected result:**
The browser should not default to http but https (even more in this case as Upgrade Connections to HTTPS is set to true)

**Reproduces how often:** 
Everytime I look at a page that does not have HTTP support but has HTTPS support (aws api gateway with regional domains websites).

**Brave Version:**
1.43 (22.9.9.14)

**Device details:** 
Iphone 12 Pro max iOS 16.0

**Website problems only:**
- did you check with Brave Shields down? YES still happening
- did you check in Safari/Firefox (WkWebView-based browsers)? Yes Safari does not have this bug

**Comment by diracdeltas** [comment]
have you tried using "always use secure connections" in brave://settings/security?

**Comment by iccub** [comment]
I see the same behavior on iOS-Safari and FF-iOS. Can be webkit specific

**Comment by erwan-joly** [comment]
> have you tried using "always use secure connections" in brave://settings/security?

This link doesn't bring anywhere on my phone. My issue is on iOS not desktop I think this settings link is for desktop. 


> I see the same behavior on iOS-Safari and FF-iOS. Can be webkit specific

tested again on safari for some reason it's working with marketracoon.com but not with another address maybe safari cache the schema somewhere. So yeah could be webkit specific :/ 
Is there a better place I can report this bug ?
It may not be counted as a bug on other brothers though as they do not automatically upgrade connection to https. 
I think "upgrade connections to HTTPS" option should automatically search for https rather than calling http then going https

**Comment by iccub** [comment]
https://bugs.webkit.org/ is the place.
I tested all iOS browsers and none seems to work with it

I believe Safari iOS auto updates to https too and we share lists with them
https://www.macrumors.com/2021/06/08/safari-ios-15-macos-monterey-https-upgrades/

It's interesting case though, I wonder if we could fix that on our end and what would be the implications

**Comment by erwan-joly** [comment]
webkit bug report answer:

>WebKit doesn't have the logic to try https when connection on port 80 is refused, and probably shouldn't, because that's trivial to implement in a browser, and not necessarily appropriate for every other embedder.

>We do have upgradeKnownHostsToHTTPS on WKWebViewConfiguration, but [marketracoon.com](http://marketracoon.com/) is not currently on the known list. And that's only about known hosts, not about retrying.

**Comment by iccub** [comment]
Thanks for the update from the webkit team.
Let's close this ticket for now and keep an eye on whether they will modify this behavior at webkit level
