### ISSUE TITLE
Wallet: Make sure deprecated testnets migration successfully once upgrade to 1.44

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6104]
In 1.44 we will deprecate testnets:
1. Rinkeby
2. Ropsten
3. Kovan

and add a new supported testnet: Sepolia
If user selected one of above three deprecated testnets in an older versiom of Brave app, once they upgrade to 1.44, the selected network will be migrated to be the Eth Mainnet.
This issue is to verify there is no hangs or crash in 1.44 build if user upgrade their app to 1.44 with a selected testnet that is deprecated in 1.44

Reproducible hang and possible crash steps:
1. Download any version before 1.44
2. open wallet and select one of above deprecated testnet 
3. upgrade to 1.44
5. reopen brave and go to wallet
6. observe the selected network is now Eth mainnet with no hangs or crashes.

**Comment by nuo-xu** [comment]
@srirambv please make sure testing it with core 1.44.109 or above. Thanks 🙂

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.44 (22.10.10.19)
- Verified steps from issue description
- Verified deprecated testnets are removed upon upgrade
- Verified device doesn't hang when its set to Ethereum post upgrade
- Verified only `Goreli` and `Sepolia` testnets are available for Ethereum Network
- Encountered an existing issue [#6141](https://github.com/brave/brave-ios/issues/6141)

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.6.1) | iPad Pro (iOS 16.1 Beta)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/195071069-c8912a15-7f05-4194-b7be-5a91e5ad5319.mp4> | <video src=https://user-images.githubusercontent.com/17010094/195071418-73bfaa7f-e56e-440f-8c1e-2b65dfcf0b76.mp4> | <video src=https://user-images.githubusercontent.com/17010094/195072312-b8b9848c-46fe-4629-8a57-dca7472e4806.mp4>
