### ISSUE TITLE
Website content does not respect safe areas

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6114]
See Safari vs Brave comparison, screenshots do not show the notch but you can see Brave's website taking entire screen

![IMG_0465](https://user-images.githubusercontent.com/6950387/194317777-b8d32d31-b5c7-4731-a16d-8c3b754808d1.PNG)
![IMG_0464](https://user-images.githubusercontent.com/6950387/194317785-11df955c-b054-47be-834f-8ba575fffed9.PNG)

**Comment by Uni-verse** [comment]
Verified on `iPhone 12`, `iOS 16.1` & `iPad (9th Gen)`, `iPadOS 15.6.1` using version `1.48 (23.2.15.17)`

Using Test Plan in https://github.com/brave/brave-ios/pull/6823#issue-1553762615

- Ensured toolbars are collapsing when user scrolls in `portrait` and `landscape` orientation.
- Ensured toolbars are expanding when user scrolls back up
- Ensured toolbars are collapsing/expanding with tabs bar enabled/disabled
- Ensured toolbars are collapsing/expanding with `reader mode` enabled

Example | Example | Example | Example
-|-|-|-
![IMG_4510](https://user-images.githubusercontent.com/17885425/219452919-1bfcdd9f-817f-464e-a368-fd1ca2968f11.PNG) | ![IMG_4511](https://user-images.githubusercontent.com/17885425/219452924-2eeac38a-afd6-4db2-a8c8-ac823ba41791.PNG) | ![IMG_4512](https://user-images.githubusercontent.com/17885425/219452926-b305b7c5-e2c5-400d-9cf0-6e2160b61ef7.PNG) | ![IMG_4513](https://user-images.githubusercontent.com/17885425/219452929-59b6437a-e5c8-482f-b7ea-6ce7f81fba28.PNG)
![IMG_0127 2](https://user-images.githubusercontent.com/17885425/219452987-4005771b-580d-4bde-b1b0-0fa5d10b8566.PNG) | ![IMG_0128 3](https://user-images.githubusercontent.com/17885425/219452991-afb76dbf-2341-473b-9c7d-de643dcbce19.PNG) | ![IMG_0129 2](https://user-images.githubusercontent.com/17885425/219452997-f5543fe1-c74d-4e51-82b3-675c07555240.PNG) | ![IMG_0130](https://user-images.githubusercontent.com/17885425/219453011-9b25b629-ac90-4fab-ae2b-3dccd562cea7.PNG)
