### ISSUE TITLE
Find-In Page Bar Related Issues

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#6118]
### Description: 

**_De-activation:_**

There are multiple issues related with FindInPage de-activation.

After dismissing Find-In Page Bar using X button, the text is still selected and it is obstructing engaging the page in any other way.

This is reported by a user https://community.brave.com/t/cant-select-text-after-using-find-in-page/430885

However this problem persists also for other cases like adding a new tab using Bottom Bar / changing a tab using Tabs Bar or activating Tab Tray from Bottom Bar when Fin-In Page is still activated.

**_Presentation:_**

In addition to the other issues mentioned, activating Find-In Page when URL Bar is is activated as Bottom Bar has a problem with displaying the Bar under the keyboard when it is first activated.

### Steps to Reproduce 

**_De-activation:_**

1. Open a webpage in Brave IOS browser
2. Find text on page
3. Use the x button to dismiss the find in page bottom bar / Change the tab using Tab Bar / Open a new tab using BottomBar / Open TabTray using BottomBar 
4. Try to select text that doesn’t match the find on page results.
5. The find on page result is selected instead of the text I selected.

**_Presentation:_**

1. Open a webpage in Brave IOS browser
2. Activate URL Bottom Bar
3. Find text on page
4. Bar is presented under keyboard

**Actual result:** 

https://user-images.githubusercontent.com/6643505/194398967-dfad78c7-f388-4e81-bc15-ba0c6e2fcaa0.mp4

**Expected result:**

The proper de-activation and presentation of bar Find-In Page

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
Any version

**Device details:** 
Any 

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by Uni-verse** [comment]
Verified using `1.44 (22.10.10.19)` using the following device(s):

iPhone 12 | iOS 16.x
iPhone XR | iOS 15.x
iPhone X | iOS 14.x
iPad (7th Gen) | iPadOS 15.x

Using STR from https://github.com/brave/brave-ios/issues/6118#issue-1400178907

**De-Activation Case:**

- Ensured using Find in Page via the menu will display search field
- Ensured dismissing Find in Page bar using the `x` button and not searched text is not highlighted in the body
- Ensured switching to another tab using the tab bar will dismiss Find in Page as well as clearing search results
- Ensured Find in Page is dismissed by creating a new tab and searching a different term on another webpage

<table><tr><td>iPad Example</td><td>iPad Example</td><td>iPad Example</td></tr><tr>

<td>

https://user-images.githubusercontent.com/17885425/195163238-1530ca52-fcad-4ab5-8af7-773d4ba98674.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/195163359-4215d424-59f7-4534-8158-dbd07238dd12.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/195163540-ee97b122-1bff-416e-a1d4-f059912ad5b9.MP4

</td></tr></table>

<table><tr><td>iPhone Example</td><td>iPhone Example</td><td>iPhone Example</td></tr><tr>

<td>

https://user-images.githubusercontent.com/17885425/195164131-aa7caf60-ddba-4b95-b0ff-4304a271407c.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/195164262-157b9b76-74b8-4273-944e-f82feb5a8d2b.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/195164360-029c2e89-64ea-426a-9494-09ee60021b1d.MP4

</td></tr></table>

**Presentation Case:**

- Verified bar is presented above the keyboard when using Find in Page with the bottom bar enabled 
- Verified Find in Page works in Reader Mode

Example | Example
-|-
![IMG_3869](https://user-images.githubusercontent.com/17885425/195185620-9561f60f-3765-4323-b514-c23dbbbabc1c.PNG) | ![IMG_3870](https://user-images.githubusercontent.com/17885425/195185638-cf0a4b41-2020-4cc0-9650-ff2e268ff2d6.PNG)
