### ISSUE TITLE
Remove Sync Onboarding Callout

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#6131]
### Description: 

Remove Sync Onboarding Callout which is presented Full-Screen in favour of new Empty screen states under Tab Tray. 

**Expected result:**

Sync Onboarding Full-Screen Callout should be removed

**Comment by Uni-verse** [comment]
Verified using version `1.45 (22.10.28.19)` using devices below:

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPads - iPad OS 16.x, 15.x

- Verified Sync Onboarding Callout is not shown on 6th day after installing the app
- Verified on fresh profile as well as upgraded profile
