### ISSUE TITLE
Can't add multiple items to playlist from url bar

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6133]
### Steps to Reproduce 
  1. Go to youtube
  2. Add a video
  3. Switch to another video

**Actual result:** 
It shows like it's added already.

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using `1.44 (22.10.10.19)` using the following device(s):

iPhone 12 | iOS 16.x
iPhone XR | iOS 15.x
iPhone X | iOS 14.x
iPad (7th Gen) | iPadOS 15.x

- Verified user is able to add multiple items to playlist
- Verified video description matches the url

https://user-images.githubusercontent.com/17885425/195119767-f0122c58-1b45-4435-94a4-2b098057ad64.MP4
