### ISSUE TITLE
Hackerone 1727527

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6137]
See https://hackerone.com/reports/1727527

**Comment by kjozwiak** [comment]
@Uni-verse @srirambv verifications STR/Cases can be found via visiting certain links crashes brave on iOS #936 - https://github.com/brave/internal/issues/936 which can be used for verification notes.

**Comment by Uni-verse** [comment]
Verified using version `1.45 (22.11.7.16)` on the following device(s):

iPhone 12 Pro - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPads - iPadOS 16.x, 15.x

Verification notes can be found here: https://github.com/brave/internal/issues/936#issuecomment-1306139993
