### ISSUE TITLE
Switch to app Reddit prompts not suppressed by default

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#6145]
### Description: 
App should be suppressing Reddit and Linkedin switch to app prompts by default but seems like Reddit prompts are still coming up.

### Steps to Reproduce 
  1. Clean install 1.44.x
  2. Navigate to menu > Brave Shields & Privacy and disable `Allow universal links to open in external apps` in other privacy settings.
  3. Search Reddit thread
  4. Load page from search results

**Actual result:** 
Switch to app prompts shown

Example | Example
-|-
![IMG_3745 2](https://user-images.githubusercontent.com/17885425/195122857-4045a1b9-9a7f-4ae3-a85c-c55a285eb99b.PNG) | ![IMG_3858](https://user-images.githubusercontent.com/17885425/195122792-e3d9ff22-50a6-49f1-80bb-237ef4581a74.PNG)

**Expected result:**
Switch to app should be suppressed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
1.44.x

**Device details:** 
iPhone 12, XR, X

**Comment by iccub** [comment]
won't fix probably, until new adblock shields update fixes it
