### ISSUE TITLE
Enable Solana Dapps support by default

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6154]
### Description: 

Enable Solana Dapps support by default

**Comment by StephenHeaps** [comment]
I've updated the milestone as Solana Dapps has been moved to v1.47 release for iOS.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.47 (23.1.20.16)
- Verified able to connect to Solana Dapps by default
- Verified able to perform a Sign transaction on Solana Dapp
- Verified able to perform a Send transaction on Solana Dapp
- Verified able to perform a Send SPL token transaction on Solana Dapp
- Verified able to perform a Sign Message transaction on Solana Dapp
----------
Verification passed on iPhone XR with iOS 15.7.1 running 1.47 (23.1.20.16)
- Verified able to connect to Solana Dapps by default
- Verified able to perform a Sign transaction on Solana Dapp
- Verified able to perform a Send transaction on Solana Dapp
- Verified able to perform a Send SPL token transaction on Solana Dapp
- Verified able to perform a Sign Message transaction on Solana Dapp
----------
Verification passed on iPad Pro with iOS 16.2 running 1.47 (23.1.20.16)
- Verified able to connect to Solana Dapps by default
- Verified able to perform a Sign transaction on Solana Dapp
- Verified able to perform a Send transaction on Solana Dapp
- Verified able to perform a Send SPL token transaction on Solana Dapp
- Verified able to perform a Sign Message transaction on Solana Dapp
