### ISSUE TITLE
Typo in main menu (Norwegian translation)

### ISSUE THREAD

**Issue by pashynskykh** [brave/brave-ios#6155]
### Description: 
I’m the main menu there’s «Sidezoon» instead of «sidezoom».
Disclaimer: I’m not a native speaker.

### Steps to Reproduce 
  1. Open menu.
  2. See typo.

**Expected result:**
«Sidezoom» or just «Zoom».

**Actual result:** 
«Sidezoon»:
![CB912379-307B-479B-90D7-E680F2A21DB7](https://user-images.githubusercontent.com/14852335/195262062-2f9bff26-fb64-4b07-bb52-e24cdb97cbed.jpeg)

**Brave Version:** 
Versjon 1.43 (22.9.9.14)

**Device details:** 
iPhone 11, iOS 16.0.3.

**Comment by Uni-verse** [comment]
Verified on `1.45 (22.11.3.16)` using the following device(s):

iPhone 12 - iOS 16.1
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPads - iPadOS 16.x & 15.x

- Verified Page Zoom translation in Norwegian locales for shared menu as well as settings menu
- Verified `Zoom` is shown for Page Zoom in Norwegian languages

**Norsk bokaml**
Example | Example
-|-
![IMG_4045](https://user-images.githubusercontent.com/17885425/199796771-92092d96-9e34-49c7-8fe2-2177347acd01.PNG) | ![IMG_4046](https://user-images.githubusercontent.com/17885425/199796774-dfdd02f3-76df-4a1f-95ce-1fbd31922706.PNG)

**Norsk nynorsk**
Example | Example
-|-
![IMG_0742](https://user-images.githubusercontent.com/17885425/199796908-557b449b-d550-4e32-b002-e41025dc7339.PNG) | ![IMG_0743](https://user-images.githubusercontent.com/17885425/199796933-a0a668aa-5ca5-4ccd-9936-1105f6181d63.PNG)
