### ISSUE TITLE
Incorrect favicon show when opening private tab using tab tray in landscape mode

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#6158]
### Description: 
Incorrect favicon show when opening private tab using tab tray in landscape mode

### Steps to Reproduce 
  1. Clean install
  2. Rotate device to landscape
  3. Long press on tap tray icon to show menu
  4. Select New Private Tab
  5. Observe Favicon

**Actual result:** 
Incorrect favicon displayed

https://user-images.githubusercontent.com/17885425/195369873-df16f023-8f1c-4fae-8a6a-b7468e5b1ef6.mov

**Expected result:**
Favicons should be correct

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always using STR

**Brave Version:** 
1.44 (22.10.10.19)

**Device details:** 
iPhone

**Comment by iccub** [comment]
closing in favor of https://github.com/brave/brave-ios/issues/6066
