### ISSUE TITLE
Add QR scanner widget shortcut, improve search widget behavior

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6166]
For the search widget behavior, if we are not on NTP we should open a new tab and focus on address bar

**Comment by Uni-verse** [comment]
Verified using version `1.45 (22.10.25.16)` on the following devices:

iPhone 12 / iOS 16.x
iPhone XR / iOS 15.x
iPhone X / iOS 14.x
iPad (9th gen) / iPadOS 15.x

Acceptance Criteria: 

1. Add QR scanner widget shortcut
2. For the search widget behavior, if we are not on NTP we should open a new tab and focus on address bar

**Improve search widget behavior (Home screen)**

<details>

- Verified using the `search widget search` from home screen will open NTP and focus on address bar when NTP is not open.
- Verified tapping on the `New Tab` option in the search widget will launch new tab page and focus on the url box.
- Verified tapping on the `Private Tab` option in the search widget will launch a private tab and focus on the url box.
- Verified launching new tab through app `context menu` on the home screen will focus on url box.
- Verified launching new tab through app `context menu` on the home screen on `upgraded profile` will focus on url box.

<table><tr><td>iPhone</td><td>iPad</td></tr>

<tr><td>

https://user-images.githubusercontent.com/17885425/198714783-2cd5d82a-6478-40a1-a5fa-6be7314f0933.mov

</td><td>

https://user-images.githubusercontent.com/17885425/198715124-9705551b-688f-4931-8bed-22887d5df37b.MP4

</td></tr></table>

iPad Example | iPad Example
-|-
![IMG_0728](https://user-images.githubusercontent.com/17885425/199079228-8f62855b-ea62-4504-a5ea-fd4a42c52156.PNG) | ![IMG_0729](https://user-images.githubusercontent.com/17885425/199079526-f2e7fdb2-748d-4ee5-a69e-10170f06c36e.PNG)


</details>

**Improve search widget behavior (lock screen)**

<details>

- Verified using search shortcut from lock screen will open NTP and focus on the url box
- Verified search shortcut works with browser lock enabled

Example | Example
-|-
![IMG_4008](https://user-images.githubusercontent.com/17885425/199050798-2b4e012f-fab2-4acc-9119-f291fb361667.PNG) | ![IMG_4007](https://user-images.githubusercontent.com/17885425/199050388-ada301db-c962-4f4c-94af-ce20fe6c87d3.PNG)


</details>

**Add QR scanner widget shortcut (home screen)**

<details>


- Verified QR scanner code is added to the widget options list
- Verified tapping on the widget will launch the QR scanner

<table><tr><td>QR scanner widget</td><td>List</td><td>Screen recording</td></tr>

<tr><td>

![IMG_3991](https://user-images.githubusercontent.com/17885425/198720603-c7436be8-8e8a-4e38-b0a3-70130e1f7df6.PNG)

</td><td>

![IMG_3992](https://user-images.githubusercontent.com/17885425/198720613-0cf74473-9431-47e5-80f9-70fa8ef1f775.PNG)

</td><td>

https://user-images.githubusercontent.com/17885425/198720512-326b5d20-2747-475a-b67f-b685d238bc0b.MP4

</td></tr></table>

iPad Example | iPad Example
-|-
![IMG_0726](https://user-images.githubusercontent.com/17885425/199079790-e63a4e93-cdec-4108-ad3d-deab2ad46f3c.PNG) | ![IMG_0729](https://user-images.githubusercontent.com/17885425/199079835-a2bd6cd7-4206-402f-9f12-3a66a019a1c7.PNG)

</details>

**Add QR scanner widget shortcut (lock screen)**

<details>

- Verified QR scanner code is added to the widget options list for lock screen 
- Verified tapping on the widget will launch the QR scanner when screen is locked
- Verified QR scanner shortcut widget works with browser lock enabled

<table><tr><td>QR scanner widget</td><td>List</td></tr>

<tr><td>

https://user-images.githubusercontent.com/17885425/199047672-279b8827-27a3-4d03-a380-fc3f00675880.MP4

</td><td>

![IMG_4004](https://user-images.githubusercontent.com/17885425/199047743-3a76c551-88ff-467a-9065-d0f5aa90cff0.PNG)

</td></tr></table>

</details>
