### ISSUE TITLE
[hackerone] `tel:` URI scheme loading in sub frames

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-ios#6168]
https://hackerone.com/bugs?report_id=1730391&subject=brave

**Comment by kjozwiak** [comment]
@Uni-verse @srirambv verifications STR/Cases can be found via https://github.com/brave/internal/issues/953 which can also be used for verification notes.

**Comment by Uni-verse** [comment]
Verified per https://github.com/brave/internal/issues/953#issuecomment-1306542915
