### ISSUE TITLE
Shields panel toggle is off in German locale

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6171]
<img width="475" alt="Zrzut ekranu 2022-10-13 o 20 47 03" src="https://user-images.githubusercontent.com/6950387/195680887-8ce7b88e-751d-41f8-9319-59f3a8c5b859.png">

**Comment by iccub** [comment]
Maybe this can be a bigger ticket, to make this panel support dynamic fonts

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.49 (23.3.15.17)
- Verified steps from [#6984](https://github.com/brave/brave-ios/pull/6984)
- Verified text is line wrapped and doesn't push the button off alignment 

iPhone 7+ (iOS 15.7.3) | iPhone XR (iOS 16.3.1) | iPad Pro (16.4 Beta 2)
-- | -- | -- 
<img width=300 src=https://user-images.githubusercontent.com/17010094/225595447-f9dd5131-5c58-4ab8-9d52-b44cd7f86c7a.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/225595606-accc1dbc-fb6f-485c-9a0e-a0cffbb5044b.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/225598841-e3959968-012b-47b4-b43c-3b4e858e3071.png>
