### ISSUE TITLE
Can't unlock browser when going back to foreground

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6172]
Testflight feedback

<img width="747" alt="Zrzut ekranu 2022-10-13 o 20 49 26" src="https://user-images.githubusercontent.com/6950387/195682748-f7e4e306-f0e0-44f0-9c6b-a964c7c9ff94.png">

**Comment by iccub** [comment]
need QA to try to repro

**Comment by Uni-verse** [comment]
Not reproducible on `1.45 (22.10.25.19)`. Used fresh profile, and checked upgraded profile with browser lock enabled on the following devices:

iPhone 12 Pro | iOS 16.1
iPhone XR | iOS 15.5
iPhone X | iOS 14.4.2

CC: @iccub
