### ISSUE TITLE
"Copy clean URL" feature

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6179]
### Description: 
Per: https://github.com/brave/brave-browser/issues/23315

### Testing strategy:
Found in the following document: https://docs.google.com/document/d/1ea7eF3s0WTsTlmMPr8LYp5KUyNg8eK4omjizo27qvJE

Implement the "Copy clean URL" feature on iOS

**Comment by anthonypkeane** [comment]
https://github.com/brave/brave-browser/issues/26013

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.58 (23.9.26.21)`

Spec: https://docs.google.com/document/d/1ea7eF3s0WTsTlmMPr8LYp5KUyNg8eK4omjizo27qvJE


- Verified `Copy Clean Link` option appears in the context menu for links as well as when long pressing on address bar.
- Verified `Copy Clean Link` option cleans URL when used on page context menu and address bar.
- Verified test scenarios on test page - https://fmarier.github.io/brave-testing/query-filter.html
- Verified using Copy Clean Link on amazon product page strips params known to be specific to `id`, `email` or `individual click`

Example Amazon Product URL containing multiple `id` in params 

_Copy link_

https://www.amazon.com/Honest-Company-Conscious-Plant-Based-Sustainable/dp/B07GS3Q397/ref=mp_s_a_1_4?crid=1EAQPHVE4LCMY&keywords=honest+diapers&qid=1696358517&rdc=1&sprefix=honest+diapers%2Caps%2C116&sr=8-4

_Copy Clean Link_

https://www.amazon.com/Honest-Company-Conscious-Plant-Based-Sustainable/dp/B07GS3Q397/ref=mp_s_a_1_4?keywords=honest+diapers&rdc=1&sr=8-4

Example | Example | Example
-|-|-
![IMG_3556 2](https://github.com/brave/brave-ios/assets/17885425/62599253-b442-4b6c-aa33-2768e1f38e7c) | ![IMG_3554 2](https://github.com/brave/brave-ios/assets/17885425/a3f483b1-881d-46c1-aa0c-a947087e33a3) | ![IMG_3553 2](https://github.com/brave/brave-ios/assets/17885425/ed4b5735-2d78-48c9-a98e-7f9ab5351bb9)
