### ISSUE TITLE
Add support for Unstoppable Domains

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-ios#6182]
### Description: 
We have this built on desktop already. Here is the PR for it where you will get more information https://github.com/brave/brave-core/pull/10529

Should support unstoppable domains in wallet send address. The address should resolve with the domain and the currently selected token.

Supported extensions: https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/common/constants/domain-extensions.ts

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.50 (23.4.17.16)
- Verified steps from [#7104](https://github.com/brave/brave-ios/pull/7104)
- Verified Unstoppable Domains are resolved 
- Verified resolving Unstoppable Domains change depending on the network selected 

iPhone 7+ (iOS 15.7.3) | iPad Pro (iOS 16.5 Beta)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/232731354-2416bb98-2eb3-4f66-8f21-58d33ec3ee65.MP4> | <video src=https://user-images.githubusercontent.com/17010094/232731570-28124945-d679-49e1-aaad-db91a5bf727b.MP4>
