### ISSUE TITLE
Infinite loading loop logging into Github

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6186]
### Description: 

After logging into Github, the tab gets stuck in an infinite loading loop. Disabling shields does not fix the loop.

### Steps to Reproduce 
  1. Fresh install BraveDev from Testflight
  2. Open `github.com`
  3. Login to Github (I have 2FA enabled, not sure if required step)
  4. Observe infinite loop

**Actual result:** 

https://user-images.githubusercontent.com/5314553/195928834-4014f383-a79c-4caf-897d-61046ace396f.MP4

**Expected result:**

No infinite loading loop

**Reproduces how often:**

Easily reproduced

**Brave Version:** 

BraveDev 22.10.14.13

**Device details:** 

Reproduced on:
iOS 16.1 beta 5 (20B5072b) on iPhone 14 Pro
iOS 16.1 beta 3 (20B5056e) iPhone simulator

**Website problems only:**
- did you check with Brave Shields down?
Yes
- did you check in Safari/Firefox (WkWebView-based browsers)? 
Yes, Safari on iOS 16.1 beta 5 (20B5072b) on iPhone 14 Pro (no issue).

### Additional Information

App Store build working fine:
```
Version 1.43 (22.9.9.14)
BraveCore 1.43.91 (105.0.5195.102)
Device iPhone15,2 (iOS 16.1)
```

Unable to reproduce on iOS 16.0 simulator (`release` branch, commit `1362d47f9f878bb837c6611ac395f177cf13047b`):
```
BraveCore 1.44.112 (106.0.5249.119)
Device arm64 (iOS 16.0)
Version 0.0 (1.2.3.4)
```

**Comment by soner-yuksel** [comment]
@Uni-verse this seems like a release blocker for 1.44. Can you replicate this on your side ?

**Comment by StephenHeaps** [comment]
I'm able to reproduce on BraveDev v1.44 (22.10.17.18) from Testflight, but not able to reproduce on App Store Brave v1.44 (22.10.17.18). Tried a fresh install for both, this needs more investigation.

**Comment by soner-yuksel** [comment]
Found steps that can be reproducible. @Uni-verse 

Fresh install BraveDev from Testflight
Copy `http://anlasiriz.net/` and open it in url bar
Observe infinite loop.

**Comment by iccub** [comment]
Little pixies fixed it for us and seems to work for both urls reported. I will close and let QA to double check it

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 16.2` using version `1.47 (23.1.30.21)`

Preconditions (Github.com)
- 2FA is enabled


---
- Ensured page loads ok when visiting `http://anlasiriz.net/` per https://github.com/brave/brave-ios/issues/6186#issuecomment-1310810561
- Ensured page loads ok when logging into `github.com` per https://github.com/brave/brave-ios/issues/6186#issue-1409778764

<table><tr><td>Example 1</td><td>Example 2</td></tr>

<tr><td>

https://user-images.githubusercontent.com/17885425/215895519-46488cfb-6f89-4b7d-8646-132046e7a726.mov

</td><td>

https://user-images.githubusercontent.com/17885425/215895585-9efc7fc2-4860-462d-905b-630dc14e21eb.mov

</td></tr></table>
