### ISSUE TITLE
Can't add a shared playlist post JS refactor

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6187]
### Description: 

There was a small regression after #5935 that made you unable to add a shared playlist

### Test Case

Just try to add a shared playlist via test page

**Comment by Uni-verse** [comment]
Verified on `1.44 (22.10.17.13)` using the following device(s):

iPhone 12 | iOS 16.x
iPhone XR | iOS 15.x
iPhone X | iOS 14.x
iPad | iOS 15.x

- Verified downloading shared playlist using the `playlist.brave.com/bsa-sample` test page
- Verified adding shared playlist 
- Verified added playlist is shown in playlist folder view
- Verified deleting shared playlist
- Verified playback for videos in the shared playlist


Example | Example | Example 
-|-|-
![IMG_3947](https://user-images.githubusercontent.com/17885425/196215035-9dec7c03-1535-4148-8776-c683fad5e2da.PNG) | ![IMG_3948](https://user-images.githubusercontent.com/17885425/196215038-c834d0f3-1002-4316-a48d-2b7ef21344f6.PNG) | ![IMG_3949](https://user-images.githubusercontent.com/17885425/196215046-aea9ad45-4b38-4647-a3c8-18130046aed6.PNG)
![IMG_0709](https://user-images.githubusercontent.com/17885425/196215115-03dd006b-756a-4536-a337-0d4c28f429a9.PNG) |  ![IMG_0712](https://user-images.githubusercontent.com/17885425/196215125-c0a6a5dc-97d9-4b2e-98d2-d9cba43d2399.PNG) | ![IMG_0711](https://user-images.githubusercontent.com/17885425/196215120-7c5fe617-d02f-4021-8dec-cabaa25a0be2.PNG)
