### ISSUE TITLE
Truncate URL display from the left

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-ios#6190]
iOS equivalent of https://github.com/brave/brave-browser/issues/26052
see https://docs.google.com/document/d/1UNDiYiRtV9aCw1fm8LCjabi_dDORtccDRiVKr_ojZfM/edit#heading=h.gzlrh4sgxpw1 for details

test cases: 
https://long-extended-subdomain-name-containing-many-letters-and-dashes.badssl.com/ysigsgksgkskgslgsogslgslgslgslgslgsogsogsogslgsogsyosoys
https://verylongdomainnametotestvariousthings.blogspot.com/

**Comment by diracdeltas** [comment]
@kylehickinson can we get someone assigned to this?

**Comment by kylehickinson** [comment]
@diracdeltas just to confirm, is this issue for the truncation from left with the current full URL implementation? The spec listed in the issue is for hiding the rest of the url and only displaying the origin when not in edit mode

**Comment by diracdeltas** [comment]
@kylehickinson we can probably take this in stages. for now i'd be happy if just the behavior on iOS matched android so the TLD+1 is always visible and gets truncated from the left if it's too long

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` & `iPad (9th Gen)` running `iOS 16.2`, `iPadOS 15.6.1` respectively using version `1.48 (23.2.10.14)`

Based on Test plan in https://github.com/brave/brave-ios/issues/6190#issue-1409863517: 

- Verified URL is truncated from the left when loading [test page 1](https://long-extended-subdomain-name-containing-many-letters-and-dashes.badssl.com/ysigsgksgkskgslgsogslgslgslgslgslgsogsogsogslgsogsyosoys) and [test page 2](https://verylongdomainnametotestvariousthings.blogspot.com/)
- Verified long submains are truncated with and without path 
- Verified URL is truncated using HTTP

with path | without path
-|-
![IMG_4468](https://user-images.githubusercontent.com/17885425/218543064-eac25ad3-7ef5-491c-af11-0a9d5c81df09.PNG) | ![IMG_4470](https://user-images.githubusercontent.com/17885425/218543297-10f9fb9b-9510-4d44-8623-c77993c37643.PNG)
![IMG_0110](https://user-images.githubusercontent.com/17885425/218543336-9b22ac03-a9dc-4901-ab7c-6b2f1cf40c84.PNG) | ![IMG_0111 2](https://user-images.githubusercontent.com/17885425/218543349-e2bcaf9a-6edf-4cc8-adbb-eb94ce4eb3c6.PNG)
