### ISSUE TITLE
[hackerone] Show correct location for `blob:` URLs

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-ios#6191]
https://hackerone.com/reports/1735900
We show an incorrect location when a `blob:` URL is loaded.

**Comment by kjozwiak** [comment]
@Uni-verse @srirambv verifications STR/Cases can be found via https://github.com/brave/internal/issues/952 which can also be used for verification notes.

**Comment by Uni-verse** [comment]
Verified per https://github.com/brave/internal/issues/951#issuecomment-1311196869
