### ISSUE TITLE
Opening an unavailable link will not show URL or 'This site can't be reached' page

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6194]
### Description: 

Opening a url that is unavailable from another app will not show the 'This site can't be reached' page.
Opening the same url in-app by entering the URL in the URL bar will show the 'This site can't be reached' page.

### Steps to Reproduce 
  1. Tap an unavailable URL (ex. http://extensions.inrialpes.fr/brave) in another app and open in Brave
  2. Observe empty URL bar, blank white page
  3. Copy paste the URL into the URL bar and tap go
  4. Observe 'This site can't be reached' page

**Actual result:** 

![IMG_C0A138F169B1-1](https://user-images.githubusercontent.com/5314553/196209131-f66a9c68-ef7c-4827-a9c1-5789fd567980.jpeg)

**Expected result:**

![IMG_59F942857FD8-1](https://user-images.githubusercontent.com/5314553/196209268-fa07e6de-d482-4374-9868-51de22e76ad2.jpeg)

**Reproduces how often:** 

Easily reproduced

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using `1.46 (22.12.15.19)` on the following devices(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPad - iPadOS 15.x

Using STR in https://github.com/brave/brave-ios/issues/6194#issue-1411721559

- Verified `This site cant be reached` page is shown when open unavailable link in brave.
- Verified `This site cant be reached` page is shown when open link in brave using share picker
- Verified normal links work in brave. 

Example | Example
-|-
![IMG_0210](https://user-images.githubusercontent.com/17885425/208200745-7eb4d295-d50f-4acd-8108-96107adcb0c8.PNG) | ![IMG_0069 2](https://user-images.githubusercontent.com/17885425/208200886-f661f4ba-e3fa-4871-b586-1a8c9c6e5d6b.PNG)
