### ISSUE TITLE
Playlist Items on Playlist Folders not loading properly and shows as Expired

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#6195]
### Description: 
- Sometimes when visiting a Playlist Folder page, the items are loading as expired.

### Steps to Reproduce 
  1. Visit https://playlist.bravesoftware.com/japan-sample/ for example
OR:
  1. Have a playlist item that is expired, and try to play it.

**Actual result:** 
- Item does not load or shows up as all expired.

**Expected result:**
- Item should load and not show as expired.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
- Easily reproduced.

**Brave Version:** 
- 1.43

**Comment by Uni-verse** [comment]
Completed using version `1.45 (22.11.8.15)` on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPads - iPadOS 16.x, 15.x

Using STR from https://github.com/brave/brave-ios/issues/6195#issue-1411744857

Encountered: https://github.com/brave/brave-ios/issues/6359

<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/200877050-0289b97f-e225-4852-b05c-1054b87676ab.PNG">
