### ISSUE TITLE
DuckDuckGo Integration Migration

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#62]
Migrate existing DDG in private mode screens and functionality.

- [ ] DDG popup screen when coming to Private Browsing for the first time
- [ ] DDG label on private browsing 
    - Only visible if DDG is _not_ the default search engine for private mode
    - Tapping on it DDG label re-opens the pop up
- [ ] Popup options must both work (Yes and No)

| Label | Popup |
| --- | --- |
| ![Screen Shot 2018-09-28 at 10.27.43 AM.png](https://images.zenhubusercontent.com/5b4cfb87b69de9433c0523d6/ff7bf832-2693-4d5c-8af7-8f01596474d8) | ![Screen Shot 2018-09-28 at 10.27.34 AM.png](https://images.zenhubusercontent.com/5b4cfb87b69de9433c0523d6/80ecfa02-8cbe-4511-9c47-be21e58da51d) |

**Comment by iccub** [comment]
Related PR: https://github.com/brave/browser-ios/pull/1633

**Comment by kylehickinson** [comment]
We need to know where DuckDuckGo copy is going to go as well as if the popup will show up on the empty-private tabs tray (i.e. where the user sees the private-mode copy now) or still on the users first private tab

![Simulator Screen Shot - iPhone 8 - 2018-09-27 at 15.52.09.png](https://images.zenhubusercontent.com/5b4cfb87b69de9433c0523d6/3068a328-0ba9-4760-ad08-a39d2a39d2e7)

**Comment by kylehickinson** [comment]
Spoke to James: DDG callout will still happen on the new tab, DDG copy will appear at the bottom of the favourites list regardless of if it is not visible (too many favourites)
