### ISSUE TITLE
[hackerone] fix `file:` URIs UI

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-ios#6218]
Fix UI issues when opening `file:` URIs
https://hackerone.com/reports/1744197

**Comment by stoletheminerals** [comment]
https://hackerone.com/reports/1745117

**Comment by kjozwiak** [comment]
@Uni-verse @srirambv verifications STR/Cases can be found via https://github.com/brave/internal/issues/951 which can also be used for verification notes.

**Comment by Uni-verse** [comment]
Verified per https://github.com/brave/internal/issues/951#issuecomment-1311196869
