### ISSUE TITLE
[hackerone] Disable external schemes opening in child tabs

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-ios#6219]
https://hackerone.com/reports/1744892

**Comment by kjozwiak** [comment]
@Uni-verse @srirambv verifications STR/Cases can be found via https://github.com/brave/internal/issues/950 which can also be used for verification notes.

**Comment by Uni-verse** [comment]
Verified per https://github.com/brave/internal/issues/950#issuecomment-1307630043
