### ISSUE TITLE
URL bar, tab bar is blank / not visible

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6221]
### Description: 

The URL bar and tab bar can be hidden from view entirely, but the space they should be in remains. Re-focusing the keyboard

### Steps to Reproduce 
  1. Use a device with a safe area / notch
  2. Enable bottom bar if not enabled ~& always show tab bar settings~
  3. Open at least 2 tabs
  4. On one of the tabs, visit any webpage with text entry, ex. https://search.brave.com/
  5. Tap to start editing the text field
  6. Rotate device to landscape
  7. Tap tab url / top bar in landscape
  8. Observe tab bar blank, no longer showing the origin of the tab
  9. Dismiss keyboard. Observe url bar / tab bar not visible
  10. Rotate device back to portrait, Observe url bar / tab bar not visible
  11. Re-focusing the textfield and dismissing the keyboard should restore the url bar and tab bar

**Actual result:** 

![IMG_3660](https://user-images.githubusercontent.com/5314553/197202314-bf1e2022-7ea5-4b27-8e12-b7655ac02516.png) | ![IMG_3661](https://user-images.githubusercontent.com/5314553/197202325-c2981f8d-8ba3-43d4-bf76-e4236d03d523.png)
--|--

Video showing mouse clicks:

https://user-images.githubusercontent.com/5314553/197206840-840602a3-9528-443d-ab99-bd2ce6676836.mov

**Expected result:**

URL bar & tab bar are visible

**Reproduces how often:** 

Easily reproduced (with steps), but requires landscape, keyboard & tapping tab origin

**Brave Version:** 

1.44+

**Device details:** 

Tested on iOS 15.6.1 (iPhone XS), iOS 16.1 RC1 (iPhone 14 Pro)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using `1.44.1 (22.10.25.18)` on the following device(s):

iPhone 12 / iOS 16.x
iPhone XR / iOS 15.x
iPhone X / iOS 14.x

- Verified unable to reproduce using the STR in https://github.com/brave/brave-ios/issues/6221#issue-1418344623

https://user-images.githubusercontent.com/17885425/198062267-406f5136-841e-4c23-ae8d-e19524abd161.mov
