### ISSUE TITLE
Playlist videos are overwritten by the new added video.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6223]
### Steps to Reproduce 
Adding a video to playlist, and I can play it without problem at this time
Adding 1 more video to playlist, then first video is overwritten by this 2nd video and I cannot play 1st video
Adding the other video, then 1st and 2nd video are overwritten by 3rd video

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using version `1.44.1 (22.10.25.18)` on the following device(s):

iPhones running iOS 16.x, 15.x, 14.x
iPads running iOS 16.x, 15.x

Using test criteria in https://github.com/brave/brave-ios/pull/6220#issue-1418088239

- Verified adding new items to playlist will not override playback for existing items.
- Verified only the current item will be removed when deleting playlist items.

Example | Example
-|-
![IMG_0718](https://user-images.githubusercontent.com/17885425/197882138-c0de422d-f3b4-4f35-883f-51b9ea4ef963.PNG) | ![IMG_0143](https://user-images.githubusercontent.com/17885425/197883210-3c2ee76f-62c7-4014-9030-ce32d9970df1.PNG)
