### ISSUE TITLE
Can't remove old playlist items

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6224]
### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using version(s) `1.44.1 (22.10.25.18)` & `1.44.1 (22.10.24.18)` on the following device(s):

iPhones running iOS 16.x, 15.x, 14.x
iPads running iOS 16.x, 15.x

Using test plan in https://github.com/brave/brave-ios/pull/6231#issue-1421023464

-Ensured the following actions are working as expected for `iPhone` & `iPad` on OS versions `16`, `15`, and `14`

iOS 16

- [x] Deleting playlist items
- [x] Deleting playlist items in different folders
- [x] Deleting folders with items
- [x] Deleting folders without items
- [x] Attempting to delete items in SharedFolders - `FAIL` - https://github.com/brave/brave-ios/issues/6237
- [x] Adding folders in older versions of Brave, then upgrading to a newer version, and deleting the items in those folders. - `FAIL` - https://github.com/brave/brave-ios/issues/6238

iOS 15

- [x] Deleting playlist items
- [x] Deleting playlist items in different folders
- [x] Deleting folders with items
- [x] Deleting folders without items
- [x] Attempting to delete items in SharedFolders 
- [x] Adding folders in older versions of Brave, then upgrading to a newer version, and deleting the items in those folders

iOS 14

- [x] Deleting playlist items
- [x] Deleting playlist items in different folders
- [x] Deleting folders with items
- [x] Deleting folders without items
- [x] Attempting to delete items in SharedFolders 
- [x] Adding folders in older versions of Brave, then upgrading to a newer version, and deleting the items in those folders

iPadOS 15

- [x] Deleting playlist items
- [x] Deleting playlist items in different folders
- [x] Deleting folders with items
- [x] Deleting folders without items
- [x] Attempting to delete items in SharedFolders 
- [x] Adding folders in older versions of Brave, then upgrading to a newer version, and deleting the items in those folders
