### ISSUE TITLE
Allow users navigate to .eth domains (ENS)

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#6225]
Support navigating to ENS domain in omnibox, including offchain lookup. The default setting should be to ask the user before proceeding to lookup the domain. If the lookup returns

Allow ENS Interstitial | Allow ENS Offchain Interstitial
--|--
<img width="651" alt="ENS interstitial" src="https://user-images.githubusercontent.com/5314553/222174954-3051608e-b4dc-449e-9976-a4dbf6f1c782.png"> | <img width="689" alt="ENS Offchain interstitial" src="https://user-images.githubusercontent.com/5314553/222174958-732778ce-cd2e-4cff-bffd-4b5e4364ea46.png">

ENS wallet address resolution including offchain lookup is handled via: https://github.com/brave/brave-ios/issues/5787

**Comment by nuo-xu** [comment]
Note: iOS does not support IPFS at this moment.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.2 running 1.60 (23.11.12.17)
- Verified steps from [#7153](https://github.com/brave/brave-ios/pull/7153)
- Verified settings for `Resolve Solana Name Service (SNS) Domain Names` is set to `Ask` as default
- Verified settings for `Resolve Ethereum Name Service (ENS) Domain Names` is set to `Ask` as default
- Verified settings for `Allow ENS Offchain Lookup` is set to `Ask` as default
- Verified visiting `https://offchainexample.eth` brings up ENS interstitial page
- Verified selecting `Disable` on interstitial page sets ENS lookup setting to disabled
- Verified selecting `Proceed using Infura` brings up Offchain lookup interstitial page
- Verified selecting `Disable` on offchain lookup disables ENS offchain lookup setting to disable
- Verified selecting `Proceed with offchain lookup` brings up IPFS interstitial page 
- Verified visiting `https://onybose.sol` brings up SNS interstitial page
- Verified selecting `Disable` on interstitial page sets SNS lookup setting to disabled
- Verified selecting `Proceed using Syndica server` sets SNS to enabled and redirects to `https://anirudha.co`

https://github.com/brave/brave-ios/assets/17010094/7f23e79f-6bdc-4d14-b51a-fb691ebd8886
