### ISSUE TITLE
[Follow up to 6224] Unable to remove shared playlist on fresh profile 

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#6237]
### Description: 
Unable to remove shared playlist on fresh profile, seems to be working on if adding shared playlist on 1.44 and then upgrading to 1.44.1. 

https://user-images.githubusercontent.com/17885425/197664285-df11bc06-3a52-40c6-9dbf-9f6096fd64bf.MP4

### Steps to Reproduce 

Prerequisite:
- Fresh profile version `1.44.1`
- Download sample shared playlist from `playlist.brave.com/bsa-sample`
- Add shared playlist after its downloaded 

`Use Case 1: `

  1. Remove playlist using 3-dot menu in playlist view

`Use Case 2: `

1. Navigate back to folder view after adding shared playlist
2. Remove shared playlist using swipe delete

**Actual result:** 
Playlist is not removed

**Expected result:**
Playlist should be removed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 
1.44.1

**Device details:** 
iPhone / iOS 16.x

**Comment by soner-yuksel** [comment]
@Uni-verse Fix here https://github.com/brave/brave-ios/pull/6220 actually fixes the problem and everything will work perfectly for 1.44.1 as you tested. 

However the videos added in 1.44 is going to have the same tag (before the fix), even after upgrading it to 1.44.1, deleting one will delete all of the videos of that tag. this is why it happens.

So this only effects the videos which is added in 1.44 and 1.44 is 10% rollout and it doesn't effects a little amount of users and videos. Releasing 1.44.1 as soon as possible will be sufficient for this ticket. cc @iccub @Brandon-T

**Comment by soner-yuksel** [comment]
Tested this problem over and over again with different devices and can not reproduce this issue. Every-time the deletion is successful. 

However found a problem while testing this and created https://github.com/brave/brave-ios/pull/6243 which should be added in 1.44.1 with pull request https://github.com/brave/brave-ios/pull/6244 @iccub @Brandon-T

**Comment by iccub** [comment]
Needs retesting

**Comment by Uni-verse** [comment]
Verified using version `1.44.1 (22.10.25.18)` on the following device(s):

iPhones running iOS 16.x, 15.x, 14.x
iPads running iOS 16.x, 15.x

- Ensured playlist can be removed on fresh profile either using the 3-dot menu in playlist view or in folder view by swiping to delete. 

<table><tr><td>iPhone</td><td>iPad</td></tr>

<tr><td>

https://user-images.githubusercontent.com/17885425/197887123-e3cf7dc8-74f9-4a39-9803-4dbbb4e90db1.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/197888041-cce81f47-3b3f-44cb-b69b-83ab7f87131f.MP4

</td></tr></table>
