### ISSUE TITLE
[Follow up to 6224] Removing playlist item will remove all items after on upgraded profile

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#6238]
### Description: 
Removing playlist item will remove all after upgrading app

### Steps to Reproduce 
  1. Install 1.44
  2. Add a few playlist items
  3. Create new folder and place some items inside
  4. Upgrade app to 1.44.1
  5. Open playlist folder created earlier
  6. Remove last item

**Actual result:** 
Removes all items

**Expected result:**
Removes current item

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.44.1

**Device details:** 
iPhone / iOS 16.x

**Comment by soner-yuksel** [comment]
@Uni-verse Fix here https://github.com/brave/brave-ios/pull/6220 actually fixes the problem and everything will work perfectly for 1.44.1 as you tested.

However the videos added in 1.44 is going to have the same tag (before the fix), even after upgrading it to 1.44.1, deleting one will delete all of the videos of that tag. this is why it happens.

So this only effects the videos which is added in 1.44 and 1.44 is 10% rollout and it effects a little amount of users and videos. Releasing 1.44.1 as soon as possible will be sufficient for this ticket. cc @iccub @Brandon-T

**Comment by iccub** [comment]
Let's close and verify on 1.43->1.44.1 upgrade, skip adding new videos in 1.44

**Comment by Uni-verse** [comment]
Verified using version(s) `1.44.1 (22.10.25.18)` on the following device(s):

iPhones running iOS 16.x, 15.x, 14.x
iPads running iOS 16.x, 15.x

Verified as part of sanity testing playlist in https://github.com/brave/brave-ios/issues/6224#issuecomment-1289866251
