### ISSUE TITLE
Url bar can be overlapped by tab bar

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6242]
### Description: 

When scrolling down on a site it's possible that the url bar / toolbar are only animated ~90% of the way, which causes the collapsed state of the bar to overlap the url bar.

### Steps to Reproduce 
  1. Visit https://twitter.com/joseph_carney/status/1584839230219464705 on iPhone 14 Pro (simulator works).
      - This may be reproducible on other sites / devices, but it might be content size related and I can reproduce on this site/tweet on iPhone 14 Pro
  2. Scroll up/down until you see animation in 90% state
  3. Tap url bar to open keyboard

**Actual result:** 

https://user-images.githubusercontent.com/5314553/197803603-0eade3d7-4668-444a-aaa1-a21e9c77d5f4.mov

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

1.44+

**Device details:**

iPhone 14 Pro

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by nuo-xu** [comment]
similar issue happens in https://testnets.opensea.io/assets/goerli/0xa1e0345046cfdfe30914b2d13e800fbadc856144/27

**Comment by Uni-verse** [comment]
Verified using version 1.46 (22.12.13.0) on the following device(s):

iPhone XR - iOS 15.x
iPhone 12 - iOS 16.x
iPhone X - iOS 14.x
iPads - iPadOS 16.x

- Verified URL bar does not overlap tap bar

https://user-images.githubusercontent.com/17885425/207671677-0d2ea8c1-bf22-4907-b5d4-ae9ab91212ef.MP4
