### ISSUE TITLE
[Follow up to 6224] Adding shared playlist multiple times might not succeed 

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#6243]
### Description: 

Adding and deleting shared playlist over and over again  will cause failure while adding the shared playlist. It will fail adding same playlist folder after deleting. This will cause an assertion failure in debug builds.

### Steps to Reproduce 
  1. Add shared playlist from `playlist.brave.com/bsa-sample`
  2. Delete the folder after loading
  3. Repeat until there is an error

**Actual result:** 
Adding fill fail.

**Expected result:**
It should add with no problem.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
`1.44`

**Device details:** 
Any

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using version(s) `1.44.1 (22.10.25.18)` on the following device(s):

iPhones running iOS 16.x, 15.x, 14.x
iPads running iOS 16.x, 15.x

- Confirmed able to `add` and `remove` playlist repeatedly from using shared list from `playlist.brave.com/bsa-sample`

<table><tr><td>iPad</td><td>iPhone</td></tr>

<tr><td>

https://user-images.githubusercontent.com/17885425/197892012-d639330b-2686-45e6-94bc-83b41a46e9a6.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/197892237-a5d7c6bd-9e01-4d12-9045-320a30c4632f.MP4

</td></tr></table>
