### ISSUE TITLE
iPhone and iPad SI is not vertically centered on landscape. Portrait is fine

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6247]
### Description: 
We seem to have an issue with SI on iOS

From Brad
iPhone and iPad SI is not vertically centered on landscape. Portrait is fine

![IMG_0209](https://user-images.githubusercontent.com/7606853/197897863-8279606c-df9f-4bb5-8fb0-5d8cccea0800.jpg)
![IMG_0210](https://user-images.githubusercontent.com/7606853/197897868-e5821128-fe82-422a-9b59-0ca7f3fb5c0a.jpg)

**Comment by Uni-verse** [comment]
Verified using `1.45 (22.10.31.21)` on the following device(s):

iPhone 12 Pro - iOS 16.1
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPad - iPadOS 16.x, 15.x

- Verified iPhone and iPad SI vertically and horizontally centered. 

iPad | iPhone
-|-
![IMG_0015 2](https://user-images.githubusercontent.com/17885425/199259548-65ca0284-12f1-46cb-bd36-8cf87aada324.PNG) | ![IMG_0155 2](https://user-images.githubusercontent.com/17885425/199259551-a94e3b3d-51a7-4ea0-844e-9ea408e78f25.PNG)
![IMG_0014 2](https://user-images.githubusercontent.com/17885425/199259838-96fa5c4e-4370-479f-b7f8-3c9bcf0c4439.PNG) | ![IMG_0156 2](https://user-images.githubusercontent.com/17885425/199259856-99a4aac6-4b3e-4749-b823-fe831a29776e.PNG)
