### ISSUE TITLE
New features user education - bottom toolbar

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6248]
### Description: 
Add UI (or new feature alert) to notify existing users of the bottom toolbar

UI TBC

@Sam-Sibley and @anthonypkeane to put the details in here

**Comment by anthonypkeane** [comment]
We could use an updated version of https://github.com/brave/brave-ios/pull/4577 or https://www.figma.com/file/PqLTp3DnANLQMM1XzaChqZ/Mobile-VPN?node-id=2407%3A23999

**Comment by anatolydsgn** [comment]
@anthonypkeane Updated Design here. 
https://www.figma.com/file/KQAbL5AQeftvFNXUlI2jHN/Brave-Playlist?node-id=4128%3A194614&t=I6J7eO94qGicgwT8-1

**Comment by anthonypkeane** [comment]
As a V1 perhaps but I was thinking we do a mini onboarding. 

A mini version of the new user onboarding (without the leaves etc) and ask the user to stop for a moment and be aware of the change we are making. 
We won't trigger this for all updates, just the bigger ones, like the one introducing the bottom URL bar. 

Lets discuss on Slack @anatolydsgn

**Comment by anatolydsgn** [comment]
Got it Anthony, I'll mock something up over tomorrow.

**Comment by anatolydsgn** [comment]
@anthonypkeane here's another iteration - https://www.figma.com/file/KQAbL5AQeftvFNXUlI2jHN/Brave-Playlist?node-id=1%3A3984&t=HdNLwtHqVJZ7zhN9-1

**Comment by iccub** [comment]
@anatolydsgn this link does not open anything relevant for me?

**Comment by Uni-verse** [comment]
Verified using version `1.47 (23.1.18.17` on the following device(s):

iPhone 12 Pro | iOS 16.2
iPhone XR | iOS 15.5
iPhone X | iOS 14.4.2

**Upgraded Profile with tabs (landscape only)**

- Ensured that bottom toolbar education modal is presented to user when upgrading from 1.46.2 with top toolbar enabled.
- Ensured toolbar switches to bottom mode after selecting `Move Tabs Bar`
- Ensured that the setting is updated correctly to reflect the current state
- Ensured if user dismisses the modal, the toolbar position does not change
- Ensured modal is dismissed if user selects `Maybe Later` and toolbar position does not change

Example | Example | Example
-|-|-
![IMG_4291](https://user-images.githubusercontent.com/17885425/213270417-b120a470-de33-4d77-b0aa-2ea25f67d707.PNG) | ![IMG_4292](https://user-images.githubusercontent.com/17885425/213270428-2c85bb27-7dfc-4be8-9187-8ad78b6c68ad.PNG) | ![IMG_4293](https://user-images.githubusercontent.com/17885425/213270456-533dcccc-e432-4f61-9599-9ef5e427573b.PNG)

**Upgraded Profile with tabs**

- Ensured that bottom toolbar education modal is presented to user when upgrading from 1.46.2 with top toolbar enabled.
- Ensured toolbar switches to bottom mode after selecting `Move Tabs Bar`
- Ensured that the setting is updated correctly to reflect the current state

Example | Example | Example
-|-|-
![IMG_2835 2](https://user-images.githubusercontent.com/17885425/213276886-22069c34-78ce-42f4-a8a6-2619dc730852.PNG) | ![IMG_2836 2](https://user-images.githubusercontent.com/17885425/213276900-c3e3c765-5a54-4d6f-93f5-36de6e7217cb.PNG) | ![IMG_2837 2](https://user-images.githubusercontent.com/17885425/213276914-e05b2c7a-790d-4b6e-8ef5-17f60192f2c6.PNG)

**Upgraded Profile without tabs**

- Ensured that bottom toolbar education modal is presented to user when upgrading from 1.46.2 with top toolbar enabled.
- Ensured toolbar switches to bottom mode after selecting `Move Tabs Bar`
- Ensured that the setting is updated correctly to reflect the current state

Example | Example
-|-
![IMG_4294](https://user-images.githubusercontent.com/17885425/213271318-31f8eda3-a9fa-4bf7-9967-ac073166df23.PNG) | ![IMG_4295](https://user-images.githubusercontent.com/17885425/213271324-cd381333-321c-4103-ac1b-7f8dcab3803c.PNG)

**Upgraded Profile w/ bottom bar (negative test)**

- Verified users that have bottom toolbar enabled are not presented this modal when upgrading from previous version.
