### ISSUE TITLE
Leaving URL bar overlay mode with the cancel button after hiding the keyboard does not restore the toolbar/leaves gap on NTP

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6259]
### Steps to Reproduce 
  1. Enable bottom bar if not on
  2. Focus the URL bar
  3. Dismiss the keyboard by swiping downwards from above the keyboard to over the keyboard
  4. Tap the "Cancel" button next to the URL bar

**Actual result:** Toolbar is not visible, if on NTP there will be a gap
**Expected result:** Toolbar should be restored, NTP should have correct size
**Reproduces how often:** Always
**Brave Version:** 1.44

https://user-images.githubusercontent.com/529104/198115772-e160f37b-ac56-4da3-a9fb-adebdccc756b.mov

Ref #6235

**Comment by Uni-verse** [comment]
Verified on 1.45 (22.11.3.16) using the following device(s):

iPhone 12 - iOS 16.1
iPhone XR - iOS 15.x
iPhone X - iOS 14.x

Test Plan: https://github.com/brave/brave-ios/issues/6259#issue-1424571569

- Verified hiding keyboard by swiping down and tapping the cancel button does not leave gap on NTP
- Verified does not leave gap on webpage

<table><tr><td>NTP - iOS 16.x</td><td>Webpage - iOS 14.x</td><tr>

<td>

https://user-images.githubusercontent.com/17885425/199783714-45010431-2eb2-49d3-ac0e-486f8b24a31c.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/199784198-7b1f3ec6-ffc1-44e9-acdd-c510d5ba7bd2.MP4

</td></tr></table>
