### ISSUE TITLE
Reverse order of URL bar context menu items when using bottom bar

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6260]
### Description: 

When you are using bottom bar we should reverse the order of the menu items when you long press and display the context menu. This will mean that the Paste & Go/Paste commands will be closer to your finger instead of on the opposite side

This will be more common in iOS 16 as they introduced a API to do this for you.

Ref #6235

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 [iOS 16.5.1]
- iPad Air [iPadOS 16.5]
Brave build: 1.56 (23.7.13.16)
BraveCore: 1.56.5 (115.0.5790.75)
```
---------------------------

**STEPS:**
1. Launch Brave
2. Three-dot menu > Settings > TABS > Enable `Bottom Bar` 
3. Now go back and open any website
4. Long tap on URL bar > Verify
5. Go back to settings and enable `Top Bar` now
6. Long tap on URL bar > Verify

**ACTUAL RESULTS:**
- Verified the order of buttons on URL bar. From top to bottom: 
  - `Paste and Go`, `Paste` and `Copy Address` when `Top Bar` is enabled;
  - `Copy Address`, `Paste` and `Paste and Go` when `Bottom Bar` is enabled;
- Verified that functionality of the context menu is not broken

---------------------------

*iPhone*
|Bottom Bar [Dark Mode]|Bottom Bar [Light Mode]|Top Bar [Dark Mode]|Top Bar [Light Mode]|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/c51b47bc-0dc2-4eef-b383-76f77fdc0b6d) | ![2](https://github.com/brave/brave-ios/assets/128532965/f432ee87-63aa-4ce1-86c3-9a772ee97787) | ![3](https://github.com/brave/brave-ios/assets/128532965/4b90edda-8062-4640-8323-b63cd5a0b149) | ![4](https://github.com/brave/brave-ios/assets/128532965/74c59035-b16b-4f51-89f6-f53338b9f3b1) |

*iPad*
|Top Bar [Dark Mode]|Top Bar [Light Mode]|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/71d85d17-9b72-4492-9f0f-102d09fbf53f) | ![2](https://github.com/brave/brave-ios/assets/128532965/2d7e82ae-e86e-41da-a6ef-146669349366) |
