### ISSUE TITLE
Ensure shields are loaded before the first tab launches.

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#6261]
### Description: 
When launching the application (after it is terminated) shields may not be applied momentarily.

### Steps to Reproduce 
  1. Go to a website with visible blocking. For example https://dev-pages.brave.software/filtering/scriptlets.html or https://youtube.com (we block ads here)
  2. Kill the app
  3. Launch the app

**Actual result:** 
Shields not applied applied: 
1. https://dev-pages.brave.software/filtering/scriptlets.html does not show true for all values
2. Youtube shows ads when watching a video

**Expected result:**
Should apply shields right away (for that first tab):
1. https://dev-pages.brave.software/filtering/scriptlets.html should show true for all values
2. Youtube should not show ads when watching a video

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproducible

**Brave Version:** 
1.45

**Device details:** 
N/A

### Additional Information
Caused by independently loading shields and the first tab. This is a race condition and usually the tab loads faster than the shields. Need to improve loading the shields (and block the first tab) from cache.
This is tricky because we don't want to block the app from launching the first tab (so it doesn't look slow) for the sake of loading shields

Youtube navigation doesn't solve the issue because it's a single page application. you need to refresh YouTube to solve the ads problem. Most people are not aware of this and stay and navigate YouTube which gives them ads all the time if this is the first page they go to after launching the app.

**Comment by Uni-verse** [comment]
Verification completed using version `1.45.1 (22.11.17.19)` on the following device(s):

iPhone 12 Pro - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPads iPadOS

Using STR in https://github.com/brave/brave-ios/issues/6261#issue-1424585258

- Verified shields are loaded immediately when re-launching app after visiting https://youtube.com as well as https://dev-pages.brave.software/filtering/scriptlets.html
- Verified values on test page - https://dev-pages.brave.software/filtering/scriptlets.html are showing `true` after re-launching app.

Example | Example | Example
-|-|-
![IMG_4120](https://user-images.githubusercontent.com/17885425/202563338-afa36344-12d4-46a4-b542-86e837cdb050.PNG) | ![IMG_4121](https://user-images.githubusercontent.com/17885425/202563454-6fb392c0-1a66-46e3-a68d-27426be7a0d2.PNG) | ![IMG_4122](https://user-images.githubusercontent.com/17885425/202563460-00697f2c-d9d4-4efe-b685-63bd46c24415.PNG) 
![IMG_0779](https://user-images.githubusercontent.com/17885425/202565481-6c9ca5ae-8bab-4294-b801-8e8a70a0feb1.PNG) | ![IMG_0780](https://user-images.githubusercontent.com/17885425/202565536-b0abcfcf-115d-43a6-bc01-e582e50486de.PNG) | ![IMG_0784](https://user-images.githubusercontent.com/17885425/202566110-3798ad7e-9892-4763-ace0-b0b9b5f20bae.PNG)

Notes: Additional test notes - https://github.com/brave/brave-ios/issues/6411#issuecomment-1319311809
