### ISSUE TITLE
Update search engine defaults for BR / AR

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6263]
### Description: 
Update search engine defaults for:

Brazil (BR)
Argentina (AR)

Related to https://github.com/brave/brave-ios/issues/5661

Desktop/Android: https://github.com/brave/brave-browser/issues/26181

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.8.20)` on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPad - iPadOS 16.x

### Brazil

- Verified `Brave` is the default SE for `BR` region
- Verified `Brave` is the default SE for normal and private tabs
- Verified searching in url box will use `search.brave.com`

Example | Example | Example | Example
-|-|-|-
![IMG_4198](https://user-images.githubusercontent.com/17885425/206750918-1e025d8c-363e-476b-a49d-21cd17f096c6.PNG) | ![IMG_4199](https://user-images.githubusercontent.com/17885425/206750923-6c401c6f-c749-4277-93a5-5da36b35f4f5.PNG) | ![IMG_4200](https://user-images.githubusercontent.com/17885425/206750925-6a3a3f34-d3af-47e7-8b5a-e04874ded9c9.PNG) | ![IMG_4201](https://user-images.githubusercontent.com/17885425/206750928-37bdb6fe-6096-43d8-a554-acf4032aa863.PNG)

### Argentina

- Verified `Brave` is the default SE for `AR` region
- Verified `Brave` is the default SE for normal and private tabs
- Verified searching in url box will use `search.brave.com`

Example | Example | Example | Example
-|-|-|-
![IMG_0851](https://user-images.githubusercontent.com/17885425/206751024-e8bee1f6-d2f9-40a6-b7aa-078d2b9198e0.PNG) | ![IMG_0852](https://user-images.githubusercontent.com/17885425/206751042-d26cbef5-af69-441e-929c-0e7e715982ca.PNG) | ![IMG_0853](https://user-images.githubusercontent.com/17885425/206751062-73f19c2f-f2f4-4ee5-b5d5-60ed2bab4416.PNG) | ![IMG_0854](https://user-images.githubusercontent.com/17885425/206751086-bc9da4b1-cf14-4242-ab49-2aabf154780b.PNG)
