### ISSUE TITLE
Move Onboarding into a separate SPM target

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#6269]
## Problem Description 

Onboarding related classes, views , assets should be moved to separate SPM target. cDependencies should be taken care of accordingly.

This will include classes for Welcome Screen and Callouts.

**Comment by Uni-verse** [comment]
Verified on `1.45 (22.11.3.16)` using the following device(s):

iPhone 12 - iOS 16.1
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPads - iPadOS 16.x & 15.x

- Performed sanity checks for onboarding screens and callouts

iPhone 
Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_4047](https://user-images.githubusercontent.com/17885425/199842494-e16f051b-113a-46d8-aba7-0c186ea7f457.PNG) | ![IMG_4048](https://user-images.githubusercontent.com/17885425/199842522-eade3127-d263-4216-a44c-ddf78010464b.PNG) | ![IMG_4049](https://user-images.githubusercontent.com/17885425/199842547-27ca3644-453c-4717-9901-70010cd56668.PNG) | ![IMG_4050](https://user-images.githubusercontent.com/17885425/199842589-aceb1434-3ec8-4d9e-bed9-ef92a33d27cf.PNG) | ![IMG_4051](https://user-images.githubusercontent.com/17885425/199842594-c12035ee-7174-4446-bc89-04fb35e7e5b8.PNG) | ![IMG_0162](https://user-images.githubusercontent.com/17885425/199844048-20252fbc-4af7-4dba-9dc6-b29920e45b96.PNG)

iPad
Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_0744](https://user-images.githubusercontent.com/17885425/199842870-ea1c16bc-c95c-4570-b825-8f3a101bd3bb.PNG) | ![IMG_0745](https://user-images.githubusercontent.com/17885425/199842892-3e361eaa-a982-42c7-bfb7-9aa375c3983f.PNG) | ![IMG_0746](https://user-images.githubusercontent.com/17885425/199842901-9bd8da14-b0e2-4cc3-a01f-963cd5556b8f.PNG) | ![IMG_0747](https://user-images.githubusercontent.com/17885425/199842945-84f6c0dd-f0ae-4107-8798-66a668209f23.PNG) | ![IMG_0749](https://user-images.githubusercontent.com/17885425/199842967-aa096f84-4fc8-4892-b643-12df6169d00e.PNG) | ![IMG_0751](https://user-images.githubusercontent.com/17885425/199842983-79f54e7c-44d1-467f-bcad-b3bdf361d99a.PNG)
