### ISSUE TITLE
Add more brave:// URL scheme actions

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#627]
It'd be nice to offer more url schemes than the only one we support right now (`open-url`) which requires that the input be a URL.

Possible additions:
- [x] `brave://search?q=<search-query>`: Allow a user to pass in any string that would search with whatever search engine the user is currently using
- [ ] `brave://bookmark?url=<url>`: Allow the user to bookmark a URL from outside the app

In addition to the url scheme we have: `brave://open-url?url=<url>` which will fail if a non-url string is passed through.

**Comment by jhreis** [comment]
~We need to have some discussion to identify what specifically is wanted here. Blocking for now.~

Those two above would be great. We will need some mechanism for notification regarding the bookmarking, but initial backend logic can be built first.

**Comment by iccub** [comment]
Search action implemented by an external contributor, added followup ticket for the bookmark action https://github.com/brave/brave-ios/issues/3825

**Comment by iccub** [comment]
Moved to 1.29,
late security review requested here https://github.com/brave/security/issues/492

cc @jumde

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.29(21.7.16.17)
- Verified test plan from https://github.com/brave/brave-ios/pull/3582
- Verified words/sentences are searched with default Search Engine when shared via share sheet
- Logged #3944 for PB only scenario
--------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.29(21.7.16.17)
- Verified test plan from https://github.com/brave/brave-ios/pull/3582
- Verified words/sentences are searched with default Search Engine when shared via share sheet
- Logged #3944 for PB only scenario
------------
Verification passed on iPad Pro with iOS 14.6 running 1.29(21.7.16.17)
- Verified test plan from https://github.com/brave/brave-ios/pull/3582
- Verified words/sentences are searched with default Search Engine when shared via share sheet
- Logged #3944 for PB only scenario
