### ISSUE TITLE
Sync chain flow via tab sync displayed in landscape [iOS 16]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#6275]
### Description: 
In landscape view, user is not forced to portrait when sync chain modals are displayed via tab sync flow. Instead, sync chain modals are displayed in landscape which results in some elements not shown correctly as we display these flow in portrait only.

We should fix this flow for landscape on iOS 16 or force portrait mode to avoid potential usability issues

### Steps to Reproduce 
  1. Fresh profile
  2. Open tab tray, select `tabs from other devices` segmented tab
  3. Rotate device to landscape
  4. Tap on `Start a sync chain`
  5. Sync modal will display in landscape
  6. Select Select the `Tablet or Phone` option
  7. Observe
  8. Delete sync chain
  9. Repeat steps.. this time choose `I have a sync code`
  10. Notice the scan modal in landscape is not displayed correctly

**Actual result:** 
Sync chain modals are not displayed in portrait view.
Example | Example
-|-
![IMG_3981](https://user-images.githubusercontent.com/17885425/198390777-01423ca5-98b1-407c-8f19-ee672ed9d056.jpg) | ![IMG_3982](https://user-images.githubusercontent.com/17885425/198390778-2c2ef834-4953-4695-a243-1a2db04af5e2.PNG)

**Expected result:**
We should fix this flow in landscape or force portrait to avoid potential usability issues

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.45.x

**Device details:** 
iPhone 12 Pro, iOS 16.x

**Comment by soner-yuksel** [comment]
@Uni-verse this is not only iOS 16 right ? And does this happen when you start sync chain from settings ?

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7`and iPad (7th Gen) running iPadOS 17.0 using version `1.61 (23.12.11.17)`

- Ensured all flow screens are forced to display in portrait in the segmented tab sync flow. 
- Ensured joining sync chain using code words and scanning QR code is successful. 
- Spot checked sync flow on iPad to ensured nothing has regressed.
- Ensured Sync Internals data is populated after joining sync chain. 

_Case 1: Start a new Sync Chain_

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_3663](https://github.com/brave/brave-ios/assets/17885425/f1814cc7-a0b1-49da-98ee-bca84a062e50) | ![IMG_3664](https://github.com/brave/brave-ios/assets/17885425/d24e22cd-306f-41b5-9ebd-37c1b01f6c29) | ![IMG_3665](https://github.com/brave/brave-ios/assets/17885425/17a14b99-5a7c-4ea2-82a5-c4f4ce0a5e47) | ![IMG_3666](https://github.com/brave/brave-ios/assets/17885425/70200096-4924-4da5-b5e6-ce7a30cbba28) | ![IMG_3667](https://github.com/brave/brave-ios/assets/17885425/39e58741-f5d4-4b7a-a397-77f0dc588d2c)

_Case 2: I have a Sync Code_

Example | Example | Example
-|-|-
![IMG_3664](https://github.com/brave/brave-ios/assets/17885425/a66291f2-ebab-4f57-a19e-8d38c161eb82) | ![IMG_3668](https://github.com/brave/brave-ios/assets/17885425/2aa2ef0f-a92b-4e5e-bea5-895ae2c6446e) | ![IMG_3669](https://github.com/brave/brave-ios/assets/17885425/9fd73961-078d-4e14-b9c0-3f2e1fde79b0)

_Case 3: iPad (spot check)_

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_1254](https://github.com/brave/brave-ios/assets/17885425/3cad8f9c-4180-4796-9a72-c7488024034f) | ![IMG_1255](https://github.com/brave/brave-ios/assets/17885425/0de9d2c1-cb39-436d-94f2-5b03ca6e346d) | ![IMG_1256](https://github.com/brave/brave-ios/assets/17885425/3c9fb52d-0ec3-4f96-80b2-16c0f7c40da3) | ![IMG_1257](https://github.com/brave/brave-ios/assets/17885425/fb334309-1750-43ea-94f4-9f37829b91bf) | ![IMG_1258](https://github.com/brave/brave-ios/assets/17885425/2c12c6e8-ac2a-42c1-b21c-d3cd2089d827)
