### ISSUE TITLE
Playlist URL bar prompt isn't showing for rumble.com

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6276]
### Description: 
Playlist URL bar prompt isn't showing for odysee.com 

### Steps to Reproduce 
  1. Open rumble.com and tap on a video

**Actual result:** 
- Prompt UI to add the video to Playlist doesn't appear from the URL bar

**Expected result:**
- Prompt to add the video to Playlist should appear from the URL bar

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.45

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.8.20)` on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPad - iPadOS 15.x

Using STR in https://github.com/brave/brave-ios/issues/6276#issue-1426266402

- Verified playlist prompt is shown in the URL bar for rumble.com.
- Verified adding video to playlist using the icon in URL bar.
- Verified adding video using long press.
- Verified adding video using the share menu
- Verified removing video from playlist by tapping on `Remove` in the URL bar modal.

Example | Example | Example
-|-|-
![IMG_0201 2](https://user-images.githubusercontent.com/17885425/206588803-f4c3762d-33a6-43a6-bf86-862d510738cd.PNG) | ![IMG_0202](https://user-images.githubusercontent.com/17885425/206588806-11b66d33-63f5-4198-89d5-d482b701e843.PNG) | ![IMG_0060 3](https://user-images.githubusercontent.com/17885425/206588841-24c0966d-2c06-4820-8b69-cd9289c2d62b.PNG)
