### ISSUE TITLE
Update user agent to include iOS 16 devices

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6280]

**Comment by Uni-verse** [comment]
Verified using `1.45 (22.11.3.16)` on iPhone & iPad running OS version 16.x

- Verified user agent is 16.1 for iOS 16 devices

iOS Example | iPadOS Example 
-|-
![Screen Shot 2022-11-03 at 1 25 25 PM](https://user-images.githubusercontent.com/17885425/199793000-01bb847c-5dfa-429d-aeef-8a6de045411f.png) | ![Screen Shot 2022-11-03 at 1 28 03 PM](https://user-images.githubusercontent.com/17885425/199793002-52ad50a0-a6e4-4ebd-bd88-470f1c749574.png)
