### ISSUE TITLE
When tapping on url bar, sometimes text suggestions show up on iOS 16.1

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6285]
### Steps to Reproduce 
Must be iOS 16.1 device.
  1. Tap on some part of url bar

**Actual result:** 

https://user-images.githubusercontent.com/6950387/198727622-6be0ef23-f7d6-4b3c-84e6-dfd263da081c.MOV

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using the following configuration(s):

1.45 (22.11.2.16) on iPhone 12 Pro running iOS 16.1
1.45 (22.11.3.13) on iPad running iPadOS 16.1

https://user-images.githubusercontent.com/17885425/199773072-99aae594-e19a-48e2-862d-fef9f3000735.MP4

Version | Version
-|-
![IMG_0740](https://user-images.githubusercontent.com/17885425/199773234-64a21377-2bc1-4b37-8d00-6d57c6b015f4.jpg) | ![IMG_4042](https://user-images.githubusercontent.com/17885425/199773241-7293738b-7390-48b9-8da3-2bb0fcbe743a.jpg)
