### ISSUE TITLE
Get rid of top bar on new tab page

### ISSUE THREAD

**Issue by davidcollini** [brave/brave-ios#6290]
## Problem Description 

The new tab page with bottom bar enabled has a gray bar on the top that could look better without it

![image](https://user-images.githubusercontent.com/89056889/198840135-ddb2cb1c-da09-49a1-863a-5179c649131b.jpeg)

## User Experience 

1. 
2. 
3. 

### Additional information

**Comment by iccub** [comment]
Hi, no plans to have that for now
