### ISSUE TITLE
Brave shields say 0 blocked on every site

### ISSUE THREAD

**Issue by xSuave** [brave/brave-ios#6291]
### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 
Some youtube ads are being leaked at bottom of video 

**Expected result:**
Actually # of blocked should be shown 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

- - [ ] ### Additional Information![image](https://user-images.githubusercontent.com/114322024/199352182-b5f81508-49bd-4f46-912b-aa17461dcd98.jpeg)

**Comment by iccub** [comment]
Should be fixed. QA team: let's retest in 1.46

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.13.0)` on the following device(s):

iPhone XR - iOS 15.x
iPhone 12 - iOS 16.x
iPhone X - iOS 14.x
iPads - iPadOS 16.x

- Ensured Shields does not display 0 blocked when loading any webpage

Example | Example
-|-
![IMG_0868](https://user-images.githubusercontent.com/17885425/207465184-ec00f67c-b302-4c53-8795-b82d9a71da88.PNG) | ![IMG_4226](https://user-images.githubusercontent.com/17885425/207465208-31b72553-3e2d-4010-83d9-9c5a50aa3283.PNG)
