### ISSUE TITLE
Bookmark import not working

### ISSUE THREAD

**Issue by timchilds** [brave/brave-ios#6294]
### Description: 
The iOS bookmarks import feature appears to be broken.

### Steps to Reproduce 
  1. Export bookmarks from Brave Desktop (or Chrome).
  2. Attempt to import the exported html file from step 1.

**Actual result:** 
The import fails.
![image](https://user-images.githubusercontent.com/28269287/199073674-b31c51e0-1e0e-46c5-a5c7-fe7602619f7b.png)

**Expected result:**
Bookmarks are imported successfully.

**Reproduces how often:**
Easily reproduced

**Brave Version:** 
Version 1.43 (22.9.9.14)

**Device details:** 
iPhone SE (iOS 16.1)

**Comment by Brandon-T** [comment]
https://user-images.githubusercontent.com/1530031/212393123-cc2eb7aa-2f45-4aab-986d-c5b4a7a59381.mov

Cannot reproduce the issue on the latest Chrome or Brave + 1.46.x

**Comment by timchilds** [comment]
@Brandon-T I just tried using latest Chrome + Brave 1.46.2. Still seeing the same import failure.

**Updated to 1.46.2**
https://user-images.githubusercontent.com/28269287/212397347-10218232-a697-41a6-ba85-89221e404288.MP4

**Fresh 1.46.2 Install**
https://user-images.githubusercontent.com/28269287/212397462-439426ae-18a7-4d16-8a65-7169794b1bc7.MP4

Perhaps related to iPhone model? I'm using iPhone SE (2022) on iOS 16.1.1. 

Here's the bookmark import file I'm using (zipped, GH won't let me upload an HTML file):
[bookmarks_1_13_23.html.zip](https://github.com/brave/brave-ios/files/10414607/bookmarks_1_13_23.html.zip)

It's importing ok on Chrome Desktop and Brave Desktop.

**Comment by Brandon-T** [comment]
https://user-images.githubusercontent.com/1530031/212398831-6ca3f98e-73a9-44f5-9b23-284d28c40676.mov
`2023-01-13 14:04:36.113983-0500 Client[49938:914924] [Brave] Bookmarks Import - Completed Import Successfully`
It does give warnings in the console about importing your particular bookmarks file. However, it does indeed import correctly for me.

I'll look into the warnings and see if they give a hint about what could possibly be wrong. But so far, the file you've uploaded definitely works for me on both device and simulator.


**EDIT:** I checked the Chromium code vs. ours. It's an EXACT match. So there's no difference in their code vs. ours.

**Comment by Uni-verse** [comment]
Verified on `iPhone XR` running `iOS 15.5` using version `1.47 (23.1.18.17)`

Test Plan:

1. Install 1.47.x
2. Open bookmarks window
3. Select `Import Bookmarks` from root directory
4. Select Bookmarks file in finder

- Verified user is able to import bookmarks file (html) successfully
- Verified success dialog is presented when operation is completed

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_0275 2](https://user-images.githubusercontent.com/17885425/213512761-a51f077e-479d-49d1-b688-d889df24c327.PNG) | ![IMG_0276 2](https://user-images.githubusercontent.com/17885425/213512767-63f18248-53a5-4e5e-aa6c-34d74d4f5197.PNG) | ![IMG_0277 2](https://user-images.githubusercontent.com/17885425/213512772-a2391440-a673-4265-af12-01ee4f468e3b.PNG) | ![IMG_0278 2](https://user-images.githubusercontent.com/17885425/213512775-a592546e-252c-481a-ab45-dad80d023247.PNG) | ![IMG_0279 2](https://user-images.githubusercontent.com/17885425/213512780-895b294f-db92-42e0-83fe-8d048920b47a.PNG)

**Comment by soner-yuksel** [comment]
Re-opened because of regression and new PR with the fix is coming soon.

**Comment by soner-yuksel** [comment]
PR for the new fix is here https://github.com/brave/brave-ios/pull/7002, it has be tested for 1.48
