### ISSUE TITLE
Playlist autoplaying when adding Shared Folder

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#6295]
### Description: 
- Playlist will auto-play an unrelated folder when adding a shared folder
- https://bravesoftware.slack.com/archives/C01QVPRR3RR/p1666609944907779

### Steps to Reproduce 
  1. Turn Auto Play on
  2. Add items to Saved folder
  3. Notice Items will auto-play
  4. Exit Playlist
  5. Visit Shared Playlist website
  6. Add Shared Playlist
  7. Notice: Plays items from saved folder automatically.

**Actual result:** 
- Play items from other folders while shared playlist is loading

**Expected result:**
- Should not play items from other folders when shared playlist is loading

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
- Easily reproduced

**Brave Version:** 
- 1.43.x

**Device details:** 
- Any

**Comment by Uni-verse** [comment]
Verified on `1.45 (22.11.3.16)` using the following device(s):

iPhone 12 - iOS 16.1
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPads - iPadOS 16.x & 15.x

Scenario Tested: 

1. Added videos to playlist
2. Enabled Auto Play in playlist settings 
3. Confirm that Auto Play is working when opening playlist 
4. Navigated to playlist.brave.com/bsa-sample
5. Tap the download playlist item
6. Playlist view will open and shared list should be previewed
7. Tap `Add +` to save the playlist
8. Make sure sound volume is up to confirm saved videos are not playing

- Verified saved videos are not played when add shared playlist
- Verified saved videos and shared list items can both be played after adding playlist

Example | Example 
-|-
![IMG_0159](https://user-images.githubusercontent.com/17885425/199788084-3516a87a-a6db-4cf4-ae32-d9caa05436f0.PNG) | ![IMG_0160](https://user-images.githubusercontent.com/17885425/199788098-2f80a24b-06ea-4052-a676-40148ae43bfd.PNG)
![IMG_0016 2](https://user-images.githubusercontent.com/17885425/199789579-48e86886-3bde-4a58-91cb-5943b2cdc4db.PNG) | ![IMG_0017 2](https://user-images.githubusercontent.com/17885425/199789581-c979661b-305b-4d2a-9b65-52ee2e31fe30.PNG)
