### ISSUE TITLE
Private Browsing Leaking History when using "Open in Brave"

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#630]
### Steps to Reproduce 
1. Using “Private browsing only”
1. In 3rd party application, open link from share sheet, select "Open in Brave"
1. Brave opens with default screen
1. Open link from share sheet again 
1. Link opens in Brave, non-private browsing mode; page is retained in browser history.

**Actual result:** 
Stores private history in the history table

**Expected result:**
Keep private search data private

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
1.7

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by danishjafri88** [comment]
Another issue stemming from this is that the UI is blocked (Non responsive).
STR: As above and once webpage loads tap on tab tray button.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+
