### ISSUE TITLE
Changing text size on iOS 16 with Portfolio open layout bug

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6304]
### Description: 

Changing the accessibility text size on Portfolio on iOS 16+ when built with Xcode 14+ will cause layout to break until the view is scrolled

### Steps to Reproduce 
  1. Open Portfolio
  2. Change accessibility text size (can add to control centre)
  3. Observe broken layout

**Actual result:** 

Device:

https://user-images.githubusercontent.com/5314553/199537273-d679b427-f53f-4c09-bf87-be07fd61ba28.MP4

Simulator:

https://user-images.githubusercontent.com/5314553/199538034-7b8b9ac0-4da1-4317-b906-34afed59ab21.mp4

**Expected result:**

Layout does not break, shows larger text sizes correctly

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Looks like this is still an issue on the latest build 1.45 (22.11.2.16). Portoflio/Account tabs are not shown and balance graph overlaps on the tokens. Close and reopen wallet fixes the issue

https://user-images.githubusercontent.com/17010094/199663325-37dcf51c-4edf-4e9f-a83d-85d605354884.MP4

Will add a new issue for this

**Comment by srirambv** [comment]
Marking as QA/No as this is now superseded by https://github.com/brave/brave-ios/issues/6312
