### ISSUE TITLE
Lockscreen widgets should not be redacted if the phone is locked

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6305]
### Steps to Reproduce 
  1. Add few lockscreen widgets
  2. Lock the screen
  3. Tap on the screen but do not unlock it

**Actual result:** 
![IMG_1324](https://user-images.githubusercontent.com/6950387/199551605-59cb08e1-2589-4a2c-a400-2e156c0f58ed.png)

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using version `1.45 (22.11.2.16)` on `iPhone 12 Pro` running `iOS 16.1`

Using STR from https://github.com/brave/brave-ios/issues/6305#issue-1433475794

- Confirmed lock screen widgets are appear normal when screen is still locked after user taps it

<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/199753472-fa6f7e99-2fa3-4b24-8b0f-20605c7ae3ea.PNG">
