### ISSUE TITLE
Tab sync screen empty state text does not fit the width in Polish locale

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6306]
### Steps to Reproduce 
  1. Set language to Polish
  2. Go to the tab tray, go to synced tabs

**Actual result:** 
![File](https://user-images.githubusercontent.com/6950387/199551949-e56b45db-b5ef-4af1-848a-31d3fa734698.jpg)

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verifed using version `1.46 (22.12.8.20)` on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.4.2

Scenario: 

1. Set lang to Polish (Polski)
2. Open tab tray, tap on synced tab page

- Confirmed that the tab sync empty state text fits the width using Polish locale.

![IMG_4218](https://user-images.githubusercontent.com/17885425/206812326-5cb51283-397b-4f0c-8a60-96c57cbe47dd.PNG)
