### ISSUE TITLE
Changing text size on iOS 16 with Portfolio open layout bug

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#6312]
### Description: 
Changing text size on iOS 16 with Portfolio open layout bug. Followup to #6304

### Steps to Reproduce 
  1. Add text size to control centre
  2. Open wallet page
  3. Increase text size to max via control centre
  4. Wallet page is not shown properly
  5. Portfolio/Accounts tab is no shown, Graph overlaps on the tokens
  6. Close and reopen wallet page, auto-fixes the display

**Actual result:** 

https://user-images.githubusercontent.com/17010094/199663325-37dcf51c-4edf-4e9f-a83d-85d605354884.MP4

**Expected result:**
Layout does not break, shows larger text sizes correctly

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.45 (22.11.2.16)

**Device details:** 
iPad Pro (iOS 16.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @StephenHeaps @nuo-xu

**Comment by StephenHeaps** [comment]
This fix should be available in BraveDev v1.45 (22.11.3.13) or later, completed in https://github.com/brave/brave-ios/pull/6307

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 16.1 running 1.45 (22.11.3.13)
- Verified steps from issue description
- Verified changing text size updates the portfolio layout correctly
- Encountered [#6327](https://github.com/brave/brave-ios/issues/6327)


https://user-images.githubusercontent.com/17010094/200011236-e1fe1246-ddcf-482d-829d-3ed6eba8e078.mov
