### ISSUE TITLE
Can take 6 hours on a fresh install to download new ad-block rules

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#6320]
### Description: 
It's been discovered that the fetch tasks for getting files sleep for 6 hours before actually doing a download. This could result in new installs not having the ad-block rules for up to 6 hours (or longer if the app is not used frequently).

### Steps to Reproduce 
  1. Delete the app
  2. Install the app and run it
  3. Run the test here: https://test-pages.privacytests.org/tracking_content.html

**Actual result:** 
Google tag manager is not blocked (this is because the bundled rules don't block it

**Expected result:**
Google tag manager should be blocked 

Note: Facebook tracker is not being blocked instead. This is an issue that is being investigated separately and is the reason why this issue has been discovered.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.44

**Device details:** 
Any

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
This is caused by a sleep that happens before the download is performed instead of after

**Comment by Uni-verse** [comment]
Verification completed using version `1.45 (22.11.7.16)` on the following device(s):

iPhone 12 Pro - iOS 16.x
iPhone XR - iOS 15.x
iPads - iPadOS 15.x

Scenario: 

1. Installed 1.45.x
2. Navigate to test URL -https://test-pages.privacytests.org/tracking_content.html
3. Expect Google Tag Manager to be blocked

Encountered - https://github.com/brave/brave-ios/issues/6348

<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/200444885-f38926f1-2f52-4c65-a24c-a918a73f9e84.PNG">
