### ISSUE TITLE
Error pages not loading assets

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6322]
### Steps to Reproduce 
  1. Go to an error page, like `example.comasdasda`

**Actual result:** 
![IMG_1303](https://user-images.githubusercontent.com/6950387/199842525-4e9e06ea-216f-4af6-9c41-df1ff477c193.PNG)

**Expected result:**
Should look nicer

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using version `1.45 (22.11.7.16)` on the following device(s):

iPhone 12 Pro - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPads - iPadOS 16.x, 15.x

Verified assets for error pages are loading when visiting a page like `brave.xom`

Example | Example
-|-
![IMG_4056](https://user-images.githubusercontent.com/17885425/200391485-0d98910b-644e-4b9f-89f8-d18bed418715.PNG) | ![IMG_0753](https://user-images.githubusercontent.com/17885425/200391497-4226760f-dc6c-4a54-a758-bf7577ba4d1b.PNG)
