### ISSUE TITLE
Wallet: Un-exclude ERC721 tokens in Asset Search

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6326]
There are couple places that token list exclude ERC721 tokens
1. Asset search screen by clicking the magnifier icon in wallet home screen.
2. Edit visible asset screen
3. Token list in send token screen if there are ERC721 tokens have been added as visible assets

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.45.2 (22.11.23.16)
- Verified steps from [#6332](https://github.com/brave/brave-ios/pull/6332)
- Verified able to search and list ERC721 tokens in Edit visible asset screen
- Verified able to search and list ERC721 tokens in Send screen
- Encountered [#6476](https://github.com/brave/brave-ios/issues/6476)
----------------
Verification passed on iPhone XR with iOS 15.6.1 running 1.45.2 (22.11.23.16)
- Verified steps from [#6332](https://github.com/brave/brave-ios/pull/6332)
- Verified able to search and list ERC721 tokens in Edit visible asset screen
- Verified able to search and list ERC721 tokens in Send screen
- Encountered [#6476](https://github.com/brave/brave-ios/issues/6476)
----------------
Verification passed on iPad Pro with iOS 16.1 running 1.45.2 (22.11.23.16)
- Verified steps from [#6332](https://github.com/brave/brave-ios/pull/6332)
- Verified able to search and list ERC721 tokens in Edit visible asset screen
- Verified able to search and list ERC721 tokens in Send screen
- Encountered [#6476](https://github.com/brave/brave-ios/issues/6476)
