### ISSUE TITLE
Randomly choose a new tab page sponsored background image from a random campaign

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#6329]

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.15.19)` using the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPad - iPadOS 16.x

- Verified background sponsored images are selected from random campaign
- Verified tapping on links in the sponsored images will take user to landing page

Example | Example
-|-
![IMG_0889](https://user-images.githubusercontent.com/17885425/208782607-2b9fc7d5-b6c8-4a94-adcd-0fb7f5b13d6c.PNG) | ![IMG_4247](https://user-images.githubusercontent.com/17885425/208782612-b1563dd6-d202-4a9a-a280-f5f3e4b87f58.PNG)
