### ISSUE TITLE
Bing Search Results in WebKitErrorDomain

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ios#633]
### Description: 
Search results on Bing (and presumably elsewhere) yield a `WebKitErrorDocument` at times.

### Steps to Reproduce 
1. Navigate to bing.com
2. Search _lions_
3. Switch to image results

**Actual result:** 
`WebKitErrorDomain` result.

**Expected result:**
Image results.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100% of the time.

**Brave Version:** 
1.7

**Device details:** 
iOS 12.

**Website problems only:**
- did you check with Brave Shields down? Shields are inoperable in this scenario (for now)
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
This seems to be an issue with the content blocker lists. Whether or not this is a conversion issue, a limited subset of rules issue, or a whitelist not at the end problem has yet to be seen.
