### ISSUE TITLE
Current tab is not always focused in tab bar

### ISSUE THREAD

**Issue by warwickmm** [brave/brave-ios#6333]
### Description: 
If there are enough tabs where they do not fit in the tab bar, the current tab is not always in focus in the tab bar.

### Steps to Reproduce 
  1. Determine how many tabs can be opened before the tab bar "scrolls".  Call this N.
  2. Open N + 2 tabs.
  3. Switch to tab N + 2
  4. Close tab N + 2.  The page for tab N + 1 is now displayed.
  5. Notice that tab N + 1 in the tab bar is not fully visible.  One has to scroll the tab bar in order to close tab N + 1.

**Actual result:** 

The visible page is "[iOS] P3A work to gather average usage data for dormant user engagement".  However, the tab bar shows

![actual](https://user-images.githubusercontent.com/17345532/200036710-022a3d90-a794-44cd-8be9-a48bbaf4cf2a.jpg)

**Expected result:**

The tab for the current page should be focused in the tab bar:

![expected](https://user-images.githubusercontent.com/17345532/200036731-36fb0d01-1961-4a16-a37b-985b7b26a19d.jpg)

**Reproduces how often:** Easily reproduced

**Brave Version:** 1.44.1 (22.10.25.18)

**Device details:** 

* iPad Air (5th gen)
* iPhone 12 mini

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using version 1.46 22.12.13.0) on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPad (7th Gen) - iPadOS 16.x

Using STR in https://github.com/brave/brave-ios/issues/6333#issue-1436403462

- Confirmed that tab bar is showing active tab opened
- Confirmed user is able to open new tab and tab bar is updated correctly
- Confirmed user is able to re-position tabs manually

<table><tr><td>iOS</td><td>iPadOS</td></tr>

<tr><td>

https://user-images.githubusercontent.com/17885425/207667291-6d3e9833-f17b-45ab-ba30-b4240e7df6b6.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/207667429-5a0a0c2c-5315-48a9-9c0a-676042bec617.MP4

</td></tr></table>
