### ISSUE TITLE
Wallet: Add custom NFT asset

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6334]
Currently iOS only allow users to add ERC20 token as custom assets.
We should support ERC721 tokens

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.6.1. running 1.45.2 (22.11.23.16)
- Verified steps from [#6360](https://github.com/brave/brave-ios/pull/6360)
- Verified able to add NFT's via the add custom token screen 
- Verified able to list the added NFT token in portfolio 
- Verified clicking on the NFT loads the asset details page but no metadata is shown

Solana NFT | Ethereum NFT
-- | --
![image](https://user-images.githubusercontent.com/17010094/203781779-5ae0b8a4-c26e-477b-8cf8-8811ed73d17b.png) | ![image](https://user-images.githubusercontent.com/17010094/203781793-a1b2949b-0bb4-44b9-a31f-701e99efe0b9.png)

------------
Verification passed on iPhone 7+ with iOS 14.8.1. running 1.45.2 (22.11.23.16)
- Verified steps from [#6360](https://github.com/brave/brave-ios/pull/6360)
- Verified able to add NFT's via the add custom token screen 
- Verified able to list the added NFT token in portfolio 
- Verified clicking on the NFT loads the asset details page but no metadata is shown

Solana NFT | Ethereum NFT
-- | --
![image](https://user-images.githubusercontent.com/17010094/203781831-41dde378-aba6-49de-a37f-dbaa8ce1306b.png) | ![image](https://user-images.githubusercontent.com/17010094/203781837-56243f29-18c9-4fdd-8480-7381ef639091.png)

------------
Verification passed on iPad Pro with iOS 16.1 running 1.45.2 (22.11.23.16)
- Verified steps from [#6360](https://github.com/brave/brave-ios/pull/6360)
- Verified able to add NFT's via the add custom token screen 
- Verified able to list the added NFT token in portfolio 
- Verified clicking on the NFT loads the asset details page but no metadata is shown

Solana NFT | Ethereum NFT
-- | --
![image](https://user-images.githubusercontent.com/17010094/203781736-8639eee3-0f8c-42b3-94e0-955f5dfc0396.png) | ![image](https://user-images.githubusercontent.com/17010094/203781715-e47a57d1-e8d1-40aa-8a85-a7e132ce8564.png)
