### ISSUE TITLE
Enable cookie consent notice blocking does not work

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#6338]
### Description: 
The component ids have changed to reflect the raw format component ids. Our hard-coded ids no longer match which results in broken functionality.

### Steps to Reproduce 
  1. Enable block cookie consent
  2. Go to filter lists
  3. See that the correct filter list is enabled

**Actual result:** 
No filter list is enabled (crashes on debug builds due to an assertion failure)

**Expected result:**
The cookie consent filter list should be enabled

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced on latest brave core update

**Brave Version:** 
1.46

**Device details:** 
N/A

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by parsd51** [comment]
Is this only a dev builds problem?
Else I will suggest 1.45 branch or 1.45.1

**Comment by Uni-verse** [comment]
Verified using version 1.46 (22.12.13.0) on the following device(s):

iPhone XR - iOS 15.x
iPhone 12 - iOS 16.x
iPhone X - iOS 14.x
iPads - iPadOS 16.x

- [x] Case: Enable setting in menu

1. Clean install 1.46.x
2. Launch app, navigate to menu > Brave Shields and Privacy 
3. Scroll down to bottom of global defaults section, enabled `Block Cookie Consent Notices`
4. Tap on Content Filtering in the same section

- Confirm Easylist-Cookie List Filter is enabled

- [x] Case: Cookie Banner callout 

1. Clean install 1.46.x
2. Open webpage
3. Relaunch browser
4. Select Yes for the Cookie banner prompt
5. Navigate to settings > Brave Shields and Privacy 

- Confirmed Cookie Block Consent Notices is enabled
- Confirmed Easylist-Cookie List Filter is enabled

Encountered (iPad Only) - https://github.com/brave/brave-ios/issues/6641

Example | Example
-|-
![IMG_4228](https://user-images.githubusercontent.com/17885425/207469484-1d30630b-4d88-4795-8159-d02cdd71a6b4.PNG) | ![IMG_4229](https://user-images.githubusercontent.com/17885425/207469489-3d2caf75-322d-4a38-a071-8448dcdd43dc.PNG)
