### ISSUE TITLE
Command+T keyboard shortcut with private browsing on freezes browser

### ISSUE THREAD

**Issue by cndouglas** [brave/brave-ios#634]
### Description: 
Reported on Twitter: https://twitter.com/maxart/status/1073247308253294592
> Am I the only user with issues on the new iPad Pro, when pressing cmd + T with the Apple folio keyboard in this new release? (“Private browsing only” is On, pressing cmd+t turns the browser unusable - can’t interact with touch nor type)

Confirmed with latest master on iPad Pro 3rd generation simulator. Pressing Command+T puts the browser in an unstable state (see the screen recording below).

### Steps to Reproduce 
  1. Run Brave on iPad Pro (device with keyboard or simulator).
  2. Tap the tabs button and change tap the Private button to enable private browsing.
  3. Tap the plus button to create a new tab.
  4. Press the keyboard shortcut Command+T.

**Actual result:**
The browser gets in an unstable state. The tabs disappear and the URL bar is activated. Tapping Cancel and then any other button causes the entire browser to freeze.
![](https://user-images.githubusercontent.com/19424103/50050472-697d0580-00c1-11e9-950b-c3750334adf2.gif)

**Expected result:**
A new tab should be created.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:**
Version 1.7 master

**Device details:**
- Newest iPad Pro, iOS 12.x
- iPad Pro 3rd generation, iOS 12.1

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verified on iPad Pro
