### ISSUE TITLE
iOS brave search bar is delayed (lagging)

### ISSUE THREAD

**Issue by redklouds** [brave/brave-ios#6340]
### Description: 
Search bar in app is delayed keyboard inputs.

### Steps to Reproduce 
  1. Download app
  2.open 30 random tab contents
  3.close all tabs
  4.close brave completely 
  5.open new tab search, observe keyboard delay

**Actual result:** 

https://user-images.githubusercontent.com/8161665/200193695-cc8582f3-8f1e-4da6-8156-af27f84d4360.MOV

**Expected result:**

should be smooth and not delayed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Reproduced 4 times, deleted  application reinstalled, repeated the above  

**Brave Version:** 

Version 1.44.1 (22.10.25.18)

**Device details:** 

iphone 13 pro max
15.6.1 (19G82)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jacobmbarnard** [comment]
No problems on iPhone 11 running iOS 15.7.1 and Brave 1.44.1 (22.10.25.18). Brave Shields up the whole time. I think iOS 15.6.1 is less secure. iOS 15.7.1 patched quite a bit. Maybe try running the test again with iOS 15.7.1 or later. How far back should Brave for iOS go to support an older OS? Is that spec'd/doc'd anywhere?

**Comment by jacobmbarnard** [comment]
Also tried with shields down. No problems.

**Comment by jacobmbarnard** [comment]
How much free space is on your device? Did you have any apps running in the background?

**Comment by redklouds** [comment]
Hey everyone sorry for the delay, I have about 70GB of free space on my IPhone 13 pro max. I'm closing this, because no traction, going to switch to chrome for the time being.
