### ISSUE TITLE
Wallet: No sign message request when connect wallet to Rarible

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6349]
### Description: 
Failed to connect Brave Wallet to Rarible. Site shows error message. 

### Steps to Reproduce 
  1. go to rarible.com
  2. connect to Brave Wallet
  3. click notification and unlock wallet
  4. give permission for some eth accounts
  5. agree to switch to eth mainnet if you are not currently on mainnet
  

**Actual result:** 
Rarible site shows error message 

![simulator_screenshot_B5D9F33D-0072-48B1-8F61-7662B2CC6EDE](https://user-images.githubusercontent.com/1187676/200474259-b81b85be-ad95-44f8-9d68-d4bbd90078fb.png)

**Expected result:**
Sign message should appear to ask user to sign about their age restriction 

**Reproduces how often:** [Easily reproduced]

**Comment by StephenHeaps** [comment]
The sign request is not received due to an incorrect response to some Ethereum dapp requests on iOS. This should also be resolved with https://github.com/brave/brave-browser/issues/28843.

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-ios/issues/7287#issuecomment-1537868342
