### ISSUE TITLE
Playlist does not work on websites like Rumble & Bichute

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#6350]
### Description: 
- Playlist does not work on websites like Rumble

### Steps to Reproduce 
  1. Go to Bichute
  2. Search "Test" or anything
  3. Tap on a video

**Actual result:** 
- No playlist icon and no long-press if the icon is missing

**Expected result:**
- Should either allow playlist icon or long-press on the video to add it to playlist

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.44.x

**Device details:** 
Any

**Website problems only:**
- Typo but website specific.

**Comment by Uni-verse** [comment]
Verified using version `1.45 (22.11.8.15)` on the following device(s):

iPhone 12 Pro - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPads - iPadOS 16.x, 15.x

Using STR in https://github.com/brave/brave-ios/issues/6350#issue-1440289866

- Verified user is able to add videos to playlist using long press on rumble.com and bitchute.com.
- Verified user will be prompted to open playlist after adding video
- Verified user is able to open playlist and view the video
- Verified user is able to remove video from playlist

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_4070](https://user-images.githubusercontent.com/17885425/200674549-a51a4904-c493-45a2-8c5e-8f0f028d2522.PNG) | ![IMG_4071](https://user-images.githubusercontent.com/17885425/200674573-65a61375-0b3e-4816-a2ea-42d5ce94ce5f.PNG) | ![IMG_4074](https://user-images.githubusercontent.com/17885425/200674599-3b9ac572-3f4e-442e-8e44-ae291e817a26.PNG) | ![IMG_4075](https://user-images.githubusercontent.com/17885425/200674608-6fd746a4-0a4f-4647-a1fa-154dd8427633.PNG) | ![IMG_4073](https://user-images.githubusercontent.com/17885425/200674585-793a08d1-9638-40ef-98f9-0d5c494ffa7e.PNG)

Example | Example | Example
-|-|-
![IMG_0765](https://user-images.githubusercontent.com/17885425/200675326-169de627-451e-4f3a-b97b-9727be671629.PNG) | ![IMG_0766](https://user-images.githubusercontent.com/17885425/200675333-abd05287-c4b0-41ce-bf0b-577bd37bc60a.PNG) | ![IMG_0767](https://user-images.githubusercontent.com/17885425/200675343-a57ff8ff-1d0f-4efe-bfaf-11a9e9fadd54.PNG)
