### ISSUE TITLE
Show assets from all networks in Portfolio (Multichain)

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6352]
### Description: 

Show user assets for all networks on Portfolio with a network filter that defaults to `All Networks':

<img width="278" alt="portfolio multi-chain" src="https://user-images.githubusercontent.com/5314553/200594835-c975eb12-354c-4aaa-a872-308779959569.png">

Show network icon in bottom-right of non-native assets:
<img width="345" alt="network assets" src="https://user-images.githubusercontent.com/5314553/200595343-ac64613b-b495-4f24-8109-ebfd5c1ed58c.png">

**Comment by srirambv** [comment]
Verification passed on the following device running 1.46 (22.12.1.14)
- Verified a new option `All Networks` is shown on Portfolio page above assets
- Verified clicking on it loads the network filter
- Verified `All Networks` is the default setting 
- Verified changing network updates the tokens accordingly
- Verified changing network and closing wallet and reopening it resets the network filter back to `All Networks`

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (iOS 16.2)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/205286892-2ad3528c-157b-4eb3-846f-7b03bad23c28.MP4> | <video src=https://user-images.githubusercontent.com/17010094/205283352-30e792cc-eb61-4832-a542-de781a8b5be3.MP4> | <video src=https://user-images.githubusercontent.com/17010094/205286807-411f8454-d8f1-46d9-bfdd-1d46e55ac044.MP4>
