### ISSUE TITLE
Show all network assets in Edit User Assets (Multichain)

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6353]
### Description: 

Similar to #6352 we should show user assets from all networks in the Edit User Assets modal. Currently they only display for the current network.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.46 (22.12.3.0)
- Verified steps from [#6479](https://github.com/brave/brave-ios/pull/6479)
- Verified network name is shown for each asset
- Verified network filter is shown in bottom left 
- Verified clicking on network filter shows the available networks and a check mark next to selected network
- Verified search asset works as expected
- Verified add custom asset button is still shown at the bottom right corner and clicking on it brings up add token modal 
------------
Verification passed on iPhone XR with iOS 15.7.1 running 1.46 (22.12.3.0)
- Verified steps from [#6479](https://github.com/brave/brave-ios/pull/6479)
- Verified network name is shown for each asset
- Verified network filter is shown in bottom left 
- Verified clicking on network filter shows the available networks and a check mark next to selected network
- Verified search asset works as expected
- Verified add custom asset button is still shown at the bottom right corner and clicking on it brings up add token modal 
-------------
Verification passed on iPad Pro with iOS 16.2 running 1.46 (22.12.3.0)
- Verified steps from [#6479](https://github.com/brave/brave-ios/pull/6479)
- Verified network name is shown for each asset
- Verified network filter is shown in bottom left 
- Verified clicking on network filter shows the available networks and a check mark next to selected network
- Verified search asset works as expected
- Verified add custom asset button is still shown at the bottom right corner and clicking on it brings up add token modal
