### ISSUE TITLE
Update cross platform vpn logic for v2 credentials

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6357]
## Description
We may (or may not) need to make changes to accomodate the SKU credentials v2

No changes required to use the new system; but we will be required to cache the subscriber credentials once we get them to avoid burning through all of the credentials for a given day. Unlike before, there are only a certain number of preallocated credentials for each day

**Comment by bsclifton** [comment]
Carried over from https://github.com/brave/brave-browser/issues/26254

(notes removed; see requirements below)

**Comment by bsclifton** [comment]
Thanks @iccub for walking through the code with me over video chat 😄 

For reference, we made the changes needed for Desktop and Android with https://github.com/brave/brave-core/pull/15702

**Here are the requirements we needed to satisfy:**

1. When calling `prepare_credential_presentation`, we get SKU response as cookie; we need to save the expiration time also.
https://github.com/brave/brave-ios/blob/78fc6f6d09dfc06c2a87d4a45b6e4d194a833cfb/Client/Frontend/Browser/BraveSkusWebHelper.swift#L106-L116

2. We should update code to store the Guardian "subscriber" credential to have that instead (I think it is named `skusCredential` right now; maybe it can be called `desktopSubscriberCredential` or similar).  The **credential itself** along with **expiration time** are critical to store as a profile preference so we can easily look at it. It's very Important that this persists between app launches (which it appears to be doing already 😄)
https://github.com/brave/brave-ios/blob/78fc6f6d09dfc06c2a87d4a45b6e4d194a833cfb/Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Paged/BraveSkusScriptHandler.swift#L120-L121

3. Application-wise, we should not call `prepare_credential_presentation` unless:
    a. We don't have a credential yet
    b. We have a credential, but it's expired (now > expiration time)
    
4. We can set a timer to fire on the expiration timestamp we get back in #1 above. When that expiration time is reached, we want to clear the stored credential and expiration time and fetch a new one

**Comment by Uni-verse** [comment]
Verified using `1.46 (22.12.15.19)` on the following devices(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPad - iPadOS 15.x

- Verified credentials are valid if user relaunches the app
- Verified VPN credentials are valid if user changes servers
- Verified VPN profile is updated when changing server

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_4244](https://user-images.githubusercontent.com/17885425/208204243-e82b3dff-9f1c-42f1-9539-ffd23072b393.PNG) | ![IMG_4245 2](https://user-images.githubusercontent.com/17885425/208204245-626706b7-b08b-439b-9871-7d3082322885.PNG)  | ![IMG_0070](https://user-images.githubusercontent.com/17885425/208204372-3d50fcf8-33e8-4758-aaed-56b7f4583e52.PNG) | ![IMG_0072 2](https://user-images.githubusercontent.com/17885425/208204375-3d6d7ab7-8820-47e7-b0a7-603fc53ec2fc.PNG) | ![IMG_0073](https://user-images.githubusercontent.com/17885425/208204390-9197778f-db57-47ca-86a7-cfe13cedd808.jpg)
