### ISSUE TITLE
Lock screen widget icon UI issue [iOS 16]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#6358]
### Description: 
Brave favicon seen in the lock screen while using the shortcut widgets (STR not known)

### Steps to Reproduce 
  1. Navigate to device settings > Wallpaper
  2. Find the tab that show `CURRENT` and click Customize for the left panel (lock screen)
  3. Tap where it shows `+ ADD WIDGETS`
  4. Add Widgets view will show up, scroll down to find and select brave browser app
  5. Once the brave widgets are shown, swipe left once and tap on `Favorites`
  6. The Favorites widget will be added to the lock screen box, tapping that widget in the box again will bring up Favorites list
  7. Select a URL
  8. Tap `X` to close the brave widget screen
  9. Tap `X` again
  10. Tap `Done` in top right corner
  11. Continue to use the tap for some time
  12. Check lock screen if changed periodically 

**Actual result:** 
<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/200865217-1bc5c8d2-f85a-4580-8ffc-fee008852755.jpg">

**Expected result:**
Brave Favicon should not be there as there currently isn't a shortcut for the app

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Observed once

**Brave Version:** 
1.45

**Device details:** 
iPhone 12 Pro - iOS 16.1

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
closing in favor of https://github.com/brave/brave-ios/issues/6066
