### ISSUE TITLE
[Follow up to 6195] Videos showing as expired are not loading

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#6359]
### Description: 
Videos showing as expired are not loading

### Steps to Reproduce 
 
  1. Download sample playlist from playlist.brave.com/bsa-sample
  2. Make sure all the videos in shared playlist are not loading as expired

**Actual result:** 
Example | Example
-|-
![IMG_4079](https://user-images.githubusercontent.com/17885425/200879152-d4f84bbd-fd1c-4d22-9b63-c42c50b7c92e.PNG) | ![IMG_4080](https://user-images.githubusercontent.com/17885425/200879178-044977e5-535c-4db2-8727-ca3fca32175e.PNG)

**Expected result:**
Items should load and not show as expired.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent

**Brave Version:** 
1.45.x

**Device details:** 
iPhone, iPad

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Updated the STR as the original issue https://github.com/brave/brave-ios/issues/6195#issue-1411744857 was that all the shared playlist items seemed to have been loading as expired.

CC: @srirambv @kjozwiak

**Comment by Uni-verse** [comment]
Verified on `1.45 (22.11.14.16)` using the following device(s):

iPhone XR - iOS 15.x
iPhone 12 - iOS 16.x
iPads - iPadOS 16.x, 15.x 

Using STR in https://github.com/brave/brave-ios/issues/6359#issue-1442352685

- Verified downloading the sample shared playlist does not show all videos as expired on clean profile.
- Verified sample shared playlist items are preserved on upgraded profile and user is able to play selected items.
- Verified removing shared playlist.
- Verified re-downloading after removing shared playlist
- Verified playlist video is updated after user is prompted with re-opening certain videos.

<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/201735085-0b8d2b46-9a49-4a31-92c3-dd044f1db0f5.PNG">

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.6.1 running 1.45(22.11.14.16)
- Verified playlist items in the playlist folders load as expected even when previewing
- Verified playlist itmes in the playlist folders load as expected when added to local playlist
- Verified with an expired item in playlist folder all other videos/audio load when saved for offline
- Verified expired video shows prompt to reopen when avialable or just throws error when it can't be redownloaded
