### ISSUE TITLE
UI Unresponsive in #630 & #634

### ISSUE THREAD

**Issue by danishjafri88** [brave/brave-ios#636]
### Description: 
In #630 & #634 The UI became unresponsive when tab tray controller was tapped (or keyboard shortcut was used) after the STR in those issues. There is a inherent issue in the code to show tab tray, which blocks UI.

### Steps to Reproduce 
  1. Follow STR in #634  or #630 
  2. Tap on tab tray button / Press command+T

**Actual result:** 
Unresponsive UI(This may not be reproducible as the fixes for above issues avoids this problem.)

**Expected result:**
Tab tray is shown.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verified on iPhone 7+ and iPad Pro. No UI freeze

**Comment by srirambv** [comment]
* Verification passed on iPhone 7 running 1.9.2(19.5.8.23)
* Verification passed on iPhone 8 running 1.9.2(19.5.8.23)
* Verified passed with iPad 5th Gen running 1.9.2(19.5.8.23) - followed STR from #630 and then steps in description. Unable to test with steps from #634 as I don't have an external keyboard for my iPad.
* Verification passed on iPhone SE running 1.9.2(19.5.8.23)
* Verification passed on `iPad Mini 4 using iOS 12.2 running 1.9.2(19.5.8.23)`
