### ISSUE TITLE
Wallet: NFT Details Screen

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6361]
![Screenshot 2022-11-09 at 12 19 28 PM](https://user-images.githubusercontent.com/1187676/200897546-dc8f13f0-70a9-449f-8e43-b5a1e893298b.png)

Note: the copy of the button title will change from `Send NFT` to `Send`

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46 (22.12.7.22)
- Verified steps from [#6471](https://github.com/brave/brave-ios/pull/6471) 
- Verified as part of [#6501 (comment)](https://github.com/brave/brave-ios/issues/6501#issuecomment-1342521957)
- Verified loading NFT details screen shows description of the NFT when image is loaded
- Verified if image is not loaded shows `Image is not available` message and no description is shown 
- Verified ERC 721 token details is shown as per new design
- Verified ERC 721 token details renders correct NFT details
- Verified clicking on the ERC 721 token id loads a new tab and opens the block explorer page for the NFT 
- Encountered [#6608](https://github.com/brave/brave-ios/issues/6608) & [#6609](https://github.com/brave/brave-ios/issues/6609)

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (iOS 16.2)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/206433768-5c5a1292-07df-4cf5-adf0-c3106483f65e.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/206431473-31d155b8-9043-4704-b79a-cd1346c0dccd.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/206433746-21508a00-d37b-49c3-a962-770b1bdceeca.png>
