### ISSUE TITLE
Wallet: Send NFT

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6367]
User should be able to send NFT both ERC721 and Solana NFT

Some UI updates in Send Screen:
1. remove amount
2. remove percentage grids

Tx Confirmation should also handle Tx parsing with NFT tokens. Display correct amount `1`
Tx History should display correct information about NFT tx.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.6.1 running 1.45.2 (22.11.23.16)
- Verified steps from [#6385](https://github.com/brave/brave-ios/pull/6385)
- Verified able to send Ethereum NFT token from one address to another
- Verified able to send Solana NFT token from one address to another
- Verified NFT Send button changes to `Insufficient balance` when NFT balance is zero
- Verified Send button changes to `Insufficient balance` when a non-zero value is added more than the available balance

Solana NFT Send | Send Solana NFT | Confirm Solana NFT Send | Ethereum NFT Send | Send Ethereum NFT | Confirm Ethereum NFT Send | Insufficient funds on Send token | Insufficient balance for NFT Send
-- | -- | -- | -- | -- | -- | -- | --
![image](https://user-images.githubusercontent.com/17010094/203787048-546007ee-3489-4a33-816c-ac45dc9de7f0.png) | ![image](https://user-images.githubusercontent.com/17010094/203786715-baf6459b-d5c9-4d25-ba5a-dca9b96f744f.png) | ![image](https://user-images.githubusercontent.com/17010094/203786767-797e4562-f37a-4c90-a5c4-653863c6a257.png) | ![image](https://user-images.githubusercontent.com/17010094/203787009-7e5d3355-e20c-4e53-8cdf-4753aa1f94b5.png) | ![image](https://user-images.githubusercontent.com/17010094/203786908-e4d93a43-e807-49c3-be0d-654a8864a840.png) | ![image](https://user-images.githubusercontent.com/17010094/203786830-bef82c92-3acc-43ed-985c-73b30b20ae8b.png) | ![image](https://user-images.githubusercontent.com/17010094/203787110-aabd302a-2da5-4894-a8cd-0f80bf5af957.png) | ![image](https://user-images.githubusercontent.com/17010094/203787243-eb98dcc5-6cfe-4c1b-a8ba-bde74ca3d36b.png)
