### ISSUE TITLE
Wallet: Asset detail screen UI updates for NFT basic support

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6369]
In the release of NFT basic support. We will not handle NFT metadata which is a requirement to implement new NFT detail screen design #6361 
This issue will update the existed Token Detail Screen to render NFT information.
1. remove price graph 
2. remove buy/send/swap
3. remove goingecko info label

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.6.1 running 1.45.2 (22.11.23.16)
- Verified steps from [#6403](https://github.com/brave/brave-ios/pull/6403)
- Verified on NFT details view there is no graph,coingecko id or price information

Solana NFT | Ethereum NFT
-- | --
![image](https://user-images.githubusercontent.com/17010094/203787955-43dcbfbd-5ff0-42b6-8c73-56da8543c4cc.png) | ![image](https://user-images.githubusercontent.com/17010094/203787930-14f90eb5-fa5b-4778-8b15-3ccd59bf9fb8.png)
