### ISSUE TITLE
Crash when dragging current URL onto itself

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6374]
### Description: 

If you long press the text in the URL bar while editing it will lift up, if you then simply move a little to the left/right and drop it will crash

### Steps to Reproduce 
  1. Visit any website 
  2. Tap URL bar to focus text
  3. Long press on focused text to cause a full URL drag
  4. Drop it slightly to the left/right of your pick up spot

**Reproduces how often:** Easily
**Brave Version:** 1.45 tested and reproduced but possibly from before then

Video:

https://user-images.githubusercontent.com/529104/201219875-e38ec224-0c77-42d0-9a6a-b718c7c010ec.mov

**Comment by Uni-verse** [comment]
Verified on `iPhone XR` running `iOS 15.5` using version `1.47 (23.1.18.17)`

Using STR from https://github.com/brave/brave-ios/issues/6374#issue-1444653127

- Verified crash is not encountered when dragging current URL onto itself


https://user-images.githubusercontent.com/17885425/213522634-92e85a56-11cb-482f-9856-e28f7b30e196.MP4
