### ISSUE TITLE
Wallet: Prompt users Add custom asset screen when adding ERC721 assets fetched from token registry that do not have a Token Id

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6379]
There are 5 ERC721 tokens from token registry do not have `tokenId` which will cause users fail to add them as visible asset. 
We should prompt users the Add Custom Asset screen so that they can manually input a tokenId for them when they want to add those tokens as visible assets.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.45.2 (22.11.23.16)
- Verified steps from [#6389](https://github.com/brave/brave-ios/pull/6389)
- Verified able to add ERC721 tokens from token registry that do not have a token id
- Verified after adding ERC721  token unchecking it in edit token hides the token in portfolio
- Encountered [#6478](https://github.com/brave/brave-ios/issues/6478) on iOS 16

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.6.1) | iPad Pro (iOS 16.1)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/203808597-b8a33169-83fe-4dff-9f2c-7adb1bada08b.MP4> | <video src=https://user-images.githubusercontent.com/17010094/203808652-026dc562-014a-47c9-9bed-504157cdc222.MP4> | <video src=https://user-images.githubusercontent.com/17010094/203808564-1b53ee5c-6064-4821-b43b-00c46e9785c9.MP4>
