### ISSUE TITLE
Fix cosmetic filtering gap

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#6390]
### Description: 
Apply the same fix to iOS as https://github.com/brave/brave-core/pull/15930

### Steps to Reproduce 
The steps in the above PR cannot be used as it requires custom filter lists which don't exist (yet) on iOS.

But we can at least test that cookie notices are blocked in places such as reddit properly as the modified script is used to block such notices.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily reproduced

**Brave Version:** 
1.45

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.15.19)` on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPad - iPadOS 16.x

Using STR in https://github.com/brave/brave-ios/pull/6396#issue-1449959414

- Confirmed enabling `fanboy mobile notifications list` will block open in app notices on `reddit.com`
- Confirmed open in app notices will be shown when `fanboy mobile notifications list` is disabled

Disabled | Enabled
-|-
![IMG_0218 2](https://user-images.githubusercontent.com/17885425/208997050-fb3c68d9-3d61-40f4-9cff-76eed6921826.PNG) | ![IMG_0219 2](https://user-images.githubusercontent.com/17885425/208997059-dbe9438c-e07c-48de-a594-c9fe8f369d02.PNG)
