### ISSUE TITLE
Display NFTs in Account Details

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6394]
### Description: 

Similar to Portfolio but show NFTs section in account details:
https://github.com/brave/brave-ios/issues/6363

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.45.2 (22.11.23.16)
- Verified steps from [#6400](https://github.com/brave/brave-ios/pull/6400)
- Verified NFT details are shown in Account details screen

Solana Account | Ethereum Account
-- | --
![image](https://user-images.githubusercontent.com/17010094/203790690-33ef0636-5474-4d01-876c-6ab681c859e7.png) | ![image](https://user-images.githubusercontent.com/17010094/203790679-99b114a0-f60e-4f28-a5dd-3cc7899b0c87.png)

------------
Verification passed on iPhone XR with iOS 15.6.1 running 1.45.2 (22.11.23.16)
- Verified steps from [#6400](https://github.com/brave/brave-ios/pull/6400)
- Verified NFT details are shown in Account details screen

Solana Account | Ethereum Account
-- | --
![image](https://user-images.githubusercontent.com/17010094/203790720-6bbf06a1-1b73-4d2a-873c-cf9bae9a4313.png) | ![image](https://user-images.githubusercontent.com/17010094/203790749-118b078d-6c63-4ad5-a00e-72faf6b22d43.png)

------------
Verification passed on iPad Pro with iOS 16.1 running 1.45.2 (22.11.23.16)
- Verified steps from [#6400](https://github.com/brave/brave-ios/pull/6400)
- Verified NFT details are shown in Account details screen

Solana Account | Ethereum Account
-- | --
![image](https://user-images.githubusercontent.com/17010094/203790603-8cb9b8bc-3e94-47e0-b2f5-ac758e99c435.png) | ![image](https://user-images.githubusercontent.com/17010094/203790638-83c2376b-7cf1-41f8-9609-718fd6e1fe33.png)
