### ISSUE TITLE
Opening multiple tabs cause UI misalignment

### ISSUE THREAD

**Issue by parsd51** [brave/brave-ios#6398]
### Description: 
Opening multiple tabs cause UI misalignment. I have seen it in various cases, but this case is reproducible.
When opening and closing tabs afterwards one have to align the tab to be able to close it,

### Steps to Reproduce 
  1. Have two tabs open, last one active
  2. Press bookmark icon next to url bar
  3. Longpress a bookmarkfolder with 6 bookmarks with “Open All”
  4. Close the last tab open (the active one)

**Actual result:** 
Alignment is misfitted for the last tab

**Expected result:**
Alignment is not misfitted for the last tab

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
1.45.1

**Device details:** 
Ipad Air 4, ipados 16.1

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Pictures of OK/NOK case added.

**Comment by parsd51** [comment]
The NOK case:
![1CBCC002-AE81-4BA9-BDAF-5C5B70C467B9](https://user-images.githubusercontent.com/46404286/201971722-37d05440-d01a-4888-bc08-2a8987ca8b14.jpeg)
The OK case:
![AD11B067-7A56-4196-A67C-37DB257E8D68](https://user-images.githubusercontent.com/46404286/201972019-2812c9db-1b16-4f04-865b-ed6a176dbb64.jpeg)

**Comment by parsd51** [comment]
Similar case in: https://github.com/brave/brave-ios/issues/6333

**Comment by iccub** [comment]
I'll close as duplicate and we will try to fix that in 6333 ticket, in 1.46 build hopefully
