### ISSUE TITLE
Accessing the URL field using VoiceOver is broken

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6401]
### Description: 

Regression caused by https://github.com/brave/brave-ios/pull/6286 which made actions on the url bar while VoiceOver is active not actually do anything

### Steps to Reproduce 
  1. Turn on VoiceOver
  2. Highlight the URL bar
  3. Double-tap to activate

**Actual result:** Nothing happens
**Expected result:** URL bar should focus
**Reproduces how often:** Always

**Comment by Uni-verse** [comment]
Verified using version `1.45.2 (22.11.18.20)` on the following device(s):

iPhone 12 Pro - iOS 16.x
iPhone X - iOS 14.x
iPhone XR - iOS 15.x
iPads - iPadOS 16.x

- Verified user is able to access URL field with voiceover on.
- Verified user is able to enter characters into the field with voiceover on.

Example | Example
-|-
![IMG_0788](https://user-images.githubusercontent.com/17885425/203608727-3ff67332-7c99-426b-abde-4cea94ea0b82.PNG) | ![IMG_4133](https://user-images.githubusercontent.com/17885425/203608735-ac54e6e4-c982-43cb-b8bc-049ad6a08d6b.PNG)
