### ISSUE TITLE
Please Title Case Block cookie consent notice setting

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6407]
### Description: 

![IMG_2318B6B9CA26-1](https://user-images.githubusercontent.com/7606853/202266199-6c66b019-7247-4890-9f3b-e48e823a9048.jpeg)

e

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.13.0)` on the following device(s):

iPhone XR - iOS 15.x
iPhone 12 - iOS 16.x
iPhone X - iOS 14.x
iPads - iPadOS 16.x

- Verified `Block Cookie Consent Notices` setting has Title Case

Example | Example
-|-
![IMG_4223](https://user-images.githubusercontent.com/17885425/207462830-00c243c4-8cd2-44b1-95c8-8d07849e212b.PNG) | ![IMG_0865](https://user-images.githubusercontent.com/17885425/207462841-99e3cb04-668e-48dc-a658-a16d713b2511.PNG)
