### ISSUE TITLE
Ads being shown on YouTube.

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#6411]
### Description: 
Youtube ad-block is not working on first launches

### Steps to Reproduce 
  1. Launch the app first time
  2. Go directly to YouTube
  3. Watch some videos

**Actual result:** 
Ads are being presented

**Expected result:**
Ads should not be presented

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.45

**Device details:** 
Any but slower devices and slower connections suffer more from this.

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Related highly to this: https://github.com/brave/brave-ios/issues/6261 because it's caused due to ads being shown while the engine is being loaded. If you go to YouTube wile this is happening then you will get ads. Navigating in YouTube does not solve the issue you really need to refresh the page to get rid of ads. This is a very obscure fix.

**Comment by Uni-verse** [comment]
Verification completed using version `1.45.1 (22.11.17.19)` on the following device(s):

iPhone 12 Pro - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPads - iPadOS 16.x/15.x

**Fresh Profile (1.45.1):**

1. Launch the app first time
2. Go directly to YouTube
3. Watch some videos

- Verified pre-roll ads are not shown on version 1.45.1
- Verified that once the filter lists are downloaded, the content ads are removed.

<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/202580374-02952921-5b95-4631-bbff-c0f0360f4922.PNG">

Note: Some content ads are still shown on initial load after fresh install, All of these will be gone after reloading page a min later. See examples below:

iPad (OS16) | iPad (OS15) | iPhone X (OS14)
-|-|-
![IMG_0781](https://user-images.githubusercontent.com/17885425/202569486-476b4c4a-2d2d-4892-b9a2-7229749418f5.PNG) | ![IMG_0051](https://user-images.githubusercontent.com/17885425/202569682-dcc27824-b292-42ea-b838-3139fe0142fc.PNG) | ![IMG_2789](https://user-images.githubusercontent.com/17885425/202569789-82dc2cf2-3f9b-470f-aa0b-8c473f806f64.PNG)

**Upgraded Profile (1.44.1 -> 1.45.1):**

1. Installed 1.44.1
2. Navigate to YouTube
3. Watch some videos (user should be seeing content ads on initial load)
4. Open another tab, load a webpage that has ads like yahoo.com or cnn.com
5. After several minutes (to allow lists to download) upgrade to 1.45.1
6. Open youtube.com
7. Watch some videos, confirm no pre-roll ads are shown
8. open webpage that has ads, confirm no ads are shown

- Verified pre-roll ads are not shown on version 1.45.1
- Verified that once the filter lists are downloaded, the content ads are removed.

Example | Example
-|-
![IMG_0785](https://user-images.githubusercontent.com/17885425/202583552-97907fda-1976-4e73-a03e-f46e113916f5.PNG) | ![IMG_0786](https://user-images.githubusercontent.com/17885425/202583564-d805504a-7c61-4de2-9145-c2f70f3bf194.PNG)

**Upgraded Profile (1.45 -> 1.45.1)**

1. Installed 1.45
2. Navigated to YouTube
3. Watched some videos (user should be seeing content ads on initial load)
4. Opened another tab, loaded a webpage that has ads like yahoo.com or cnn.com
5. After several minutes (to allow lists to download) upgraded to 1.45.1
6. Opened youtube.com
7. Watched some videos, confirmed no pre-roll ads are shown
8. opened webpage that has ads, confirmed no ads are shown

- Verified that pre-roll ads are not shown on upgraded profile.
- Verified that content ads were not encountered on youtube.com when upgrading from 1.45

<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/202584663-402f5984-76b6-4162-bd21-50524053dfbc.PNG">

Additional testing with shields loading can be found here - https://github.com/brave/brave-ios/issues/6261#issuecomment-1319228204
