### ISSUE TITLE
Dropped frames on both `transition` and `animation` CSS properties

### ISSUE THREAD

**Issue by pmpinto** [brave/brave-ios#6412]
### Description: 
Brave on both iOS and iPad OS is dropping frames while animating elements, no matter how simple they are.

Test environments:
**A**: https://jsfiddle.net/umjx3wL9/
  Animating a `div` with `translate` over 250ms;
**B**: https://jsfiddle.net/umjx3wL9/1/
  Animating a `div` with `transform` over 250ms;
**C**: https://jsfiddle.net/umjx3wL9/2/
  Animating a `div` with `transform` over 2500ms;

### Steps to Reproduce 
  1. Visit any of the test links from above
  2. Hover the yellow 🟨 portion
  3. Watch the red 🟥 portion animate
  4. Test on desktop and witness the drastic difference

**Actual result:** 
Frames are dropped during the animation on iOS/iPad OS, most noticeable on the beginning/end of it.

**Expected result:**
Smooth animation, as it does on Chrome for iOS/iPad OS, or even Brave for desktop.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
Version 1.4.4.1 (22.10.25.18)

**Device details:** 
* iPhone 14 Pro on iOS 16.1.1
* iPad Air 5 on iPad OS 16.1.1

**Website problems only:**
- did you check with Brave Shields down?
Yes, same issue.
- did you check in Safari/Firefox (WkWebView-based browsers)? 
Safari does great too.

**Comment by kylehickinson** [comment]
Tested on iPhone 13 Pro, iOS 16.1.1, Brave 1.46 beta - Couldn't reproduce
Tested on iPad Mini gen 6, iOS 16.1.1, Brave 1.45.1 - Couldn't reproduce

**Comment by pmpinto** [comment]
Can confirm! Cannot reproduce it on 1.45.1, neither on iOS nor iPad OS ✅ 
Thanks!
