### ISSUE TITLE
Update the bundled content blocking json files

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#6415]
### Description: 
Our bundled content blocking file is somewhat out of date

### Steps to Reproduce 
  1. Launch the app
  2. Go to https://test-pages.privacytests.org/tracking_content.html

**Actual result:** 
A value of `false` is displayed some entries

**Expected result:**
All entries should have "true"

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.15.19)` using the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPad - iPadOS 16.x

- Verified all entries have value `true` in the test page - https://test-pages.privacytests.org/tracking_content.html

Example | Example
-|-
![IMG_0214 2](https://user-images.githubusercontent.com/17885425/208786109-87b2804f-a68e-4133-baf5-ec29d313df42.PNG) | ![IMG_0893](https://user-images.githubusercontent.com/17885425/208786122-673f0554-57f2-40aa-84f8-e1c21ffdfe83.PNG)
