### ISSUE TITLE
Make sure json format blocklists are before displaying first tab

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#6416]
### Description: 
We don't wait for our json blocklists to be loaded before launching the first tab. This is a smaller fix of #6261.

### Steps to Reproduce 
  1. Launch the app (new install)
  2. Go to https://test-pages.privacytests.org/tracking_content.html

**Actual result:** 
All values are false

**Expected result:**
Should have true for most values (technically all but that is fixed in a different PR)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent (race condition between device speed and how the user takes to get to that page. May be difficult to reproduce)

**Brave Version:** 
1.45

**Device details:** 
The slower the device, the more frequently this occurs.

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
We decided to fix #6261, this one is invalid unless we go back to this way of solving the problem
