### ISSUE TITLE
Wallet: Tx Confirmation Panel UI updates

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6418]
![image13 copy](https://user-images.githubusercontent.com/1187676/202532660-cbc9772a-86f8-4f39-b9ec-87ace8646971.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.48 (23.2.10.14)
- Verified steps from [#6826](https://github.com/brave/brave-ios/pull/6826)
- Verified swap transactions displays necessary information
- Verified edit gas fee and advanced settings works as expected

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (16.2)
-- | -- | -- 
<video src=https://user-images.githubusercontent.com/17010094/218407131-5d1a6679-88e3-419e-b72e-1387c55264d4.MP4> | <video src=https://user-images.githubusercontent.com/17010094/218409306-aaa031e2-3136-4a79-9d46-91636e24dcf3.MP4> | <video src=https://user-images.githubusercontent.com/17010094/218424872-db8b9e1f-f149-4e00-8f00-778d481ae516.MP4>
