### ISSUE TITLE
Open in new tab not working in Private Browsing

### ISSUE THREAD

**Issue by mil1i** [brave/brave-ios#642]
### Description: 
After updating to the newest version for iOS, I am unable to open search links using my default search engine: Startpage.

Startpage.com by default opens all links in new window/tab. I always run Brave in 'Private Browsing Only', so any settings I change for Startpage.com do not save. If I search using Google, the links open but obviously Google just has you follow the link instead of opening new window/tab.

This also may relate in another way to issue #592 in which if I attempt to long-press on the links to open in a new tab, no context menu appears to be able to force open in a new tab. This issue is only present in 

### Steps to Reproduce 
  1. Open Brave in Private Browsing Mode
  2. Search using Startpage.com
  3. Attempt to open link, or attempt to long press link

**Actual result:** 
Nothing loads, no new tab is opened.

**Expected result:**
Opens link in new tab/window

**Reproduces how often:** [Easily reproduced]
Always

**Brave Version:** 
Version 1.7 (18.12.07.16)

**Device details:** 
iPhone XS, iOS 12.1.1

**Website problems only:**
- did you check with Brave Shields down? Checked with Shields down, did not change outcome.
- did you check in Safari/Firefox (WkWebView-based browsers)? Checked with Non-Private Browsing mode, and Safari. Works fine.

**Comment by kylehickinson** [comment]
Hey, @mil1i, thanks for the report! :)

We actually have a bug already reported for this very behaviour (#456) and we hope to get a fix for it in the near future! I'm going to close this one as a dupe for the time being, but you can keep track of the fix from #456
