### ISSUE TITLE
Manual test run for 1.45.1 on iPad running iOS 15

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#6421]
## Installer

- [x] Check that installer is close to the size of the last release
- [x] Check the Brave version in About and make sure it is EXACTLY as expected

## Data

- [x] Verify that data from the previous build appears in the updated build as expected (bookmarks, history, etc.)
- [x] Verify that cookies from the previous build are preserved after upgrade
- [x] Verify saved passwords are retained after upgrade
- [x] Verify stats are retained after upgrade
- [x] Verify sync chain created in the previous version is still retained on upgrade
- [x] Verify per-site settings are preserved after upgrade

## Shields Settings

- [x] Enable all switches in `Settings` and visit a site and disable `Block Scripts`. Kill and relaunch the app and verify if the site Shields settings are retained

## Bravery settings

- [x] Check that block ad and unblock ad works on `http://slashdot.org`
- [x] Check that toggling to blocking and allow ads works as expected
- [x] Verify that tapping through a cert error in `https://badssl.com` works
- [ ] Verify that Safe Browsing works `https://www.raisegame.com`
- [x] Enable `Block Scripts` globally from `Settings`.  Visit `https://twitter.com`, nothing should load. Tap on `Shields` and disable `Block Scripts`; the page should load properly.
- [x] Verify that default Brave Shields settings take effect on pages with no site settings

### Fingerprint Tests

  - [ ] Verify that turning on fingerprinting protection in preferences shows `3 fingerprints blocked` at `https://browserleaks.com/canvas`. Verify that turning it off in the Bravery menu shows `0 fingerprints blocked`.
  - [ ] Verify that the audio fingerprint is blocked at `https://audiofingerprint.openwpm.com` when fingerprinting protection is on
  - [x] Verify that `https://diafygi.github.io/webrtc-ips/` doesn't leak IP address when `Block all fingerprinting protection` is on

## App linker

- [x] Long-press on a link in the Twitter app to get the share picker, choose Brave. Verify Brave doesn't crash after opening the link.

## Session storage

- [x] Verify that tabs restore when closed, including active tab

**Comment by LaurenWags** [comment]
For the below cases:

```
  - [ ] Verify that turning on fingerprinting protection in preferences shows `3 fingerprints blocked` at `https://browserleaks.com/canvas`. Verify that turning it off in the Bravery menu shows `0 fingerprints blocked`.
  - [ ] Verify that the audio fingerprint is blocked at `https://audiofingerprint.openwpm.com` when fingerprinting protection is on
```

both show `0` items blocked, known issue reported via https://github.com/brave/brave-ios/issues/6192 and https://github.com/brave/brave-ios/issues/6198

For the below case:

```
  - [ ]  Verify that Safe Browsing works https://www.raisegame.com
```

skipped per discussion with @Uni-verse - test case needs to be updated

**Comment by LaurenWags** [comment]
Tests verified with iPad 5th Gen running iOS15 and `1.45.1 (22.11.17.19)`
