### ISSUE TITLE
ERC20 Approve for unknown token fails to display

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6425]
### Description: 

When receiving an ERC20 approve transaction for a symbol not in the user asset list or our token registry, we fail to display any information on the Transaction Confirmation screen.

Additional details:
https://bravesoftware.slack.com/archives/C02S9LFEXU4/p1668712405196229

Workaround: Add the token being approved to Brave Wallet via 'Edit User Assets' -> 'Add custom token' button.

### Steps to Reproduce 
  1. Visit Uniswap
  2. Create a swap transaction from a token that is not added in your assets list, or in the token registry (Does not display in 'Edit User Assets' modal)
  3. Observe 'empty' Transaction Confirmation modal

**Actual result:** 

![image (6)](https://user-images.githubusercontent.com/5314553/202567382-5b973c4d-a276-4bf5-b15e-fbc6bd179043.png)

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.47 (23.1.4.10)
- Verified steps from [#6651](https://github.com/brave/brave-ios/pull/6651)
- Verified `LINK` token is shown in the summary when tapping the transaction to open Transaction Detail
- Verified `LINK` token is shown in the transaction summary

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (16.2)
-- | -- | -- 
<video src=https://user-images.githubusercontent.com/17010094/212140713-6882819f-8ff0-4555-ae6e-89792d6bb7e6.MP4> | <video  src=https://user-images.githubusercontent.com/17010094/212140789-d7c98584-cb49-4b86-96bf-087692d62aed.MP4> | <video  src=https://user-images.githubusercontent.com/17010094/212140691-d1b90a4d-da96-45b3-ad59-b18e29208c29.MP4>
