### ISSUE TITLE
Show assets from all networks in Account Details (Multichain)

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6428]
### Description: 

Similar to https://github.com/brave/brave-ios/issues/6352, we should display user assets from all networks matching the account coin type in Account Details page

Show network icon in bottom-right of non-native assets:
<img width="345" alt="network assets" src="https://user-images.githubusercontent.com/5314553/200595343-ac64613b-b495-4f24-8109-ebfd5c1ed58c.png">

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.46 (22.12.3.0)
- Verified steps from [#6493](https://github.com/brave/brave-ios/pull/6493)
- Verified clicking on accounts tab and selecting Eth account lists all the tokens from Ethereum/EVM chains
- Verified all NFT's from Ethereum/EVM chains are displayed under NFT section
- Verified all submitted/confirmed transactions are shown under Transaction section
- Verified clicking on Solana account under accounts tab lists all visible tokens for Solana Network
- Verified all NFT's from Solana network are listed under NFT section for Solana network
- Verified all submitted/confirmed transactions are shown under Transaction section for Solana network
----------
Verification passed on iPhone XR with iOS 15.7.1 running 1.46 (22.12.3.0)
- Verified steps from [#6493](https://github.com/brave/brave-ios/pull/6493)
- Verified clicking on accounts tab and selecting Eth account lists all the tokens from Ethereum/EVM chains
- Verified all NFT's from Ethereum/EVM chains are displayed under NFT section
- Verified all submitted/confirmed transactions are shown under Transaction section
- Verified clicking on Solana account under accounts tab lists all visible tokens for Solana Network
- Verified all NFT's from Solana network are listed under NFT section for Solana network
- Verified all submitted/confirmed transactions are shown under Transaction section for Solana network
----------
Verification passed on iPad Pro with iOS 16.2 running 1.46 (22.12.3.0)
- Verified steps from [#6493](https://github.com/brave/brave-ios/pull/6493)
- Verified clicking on accounts tab and selecting Eth account lists all the tokens from Ethereum/EVM chains
- Verified all NFT's from Ethereum/EVM chains are displayed under NFT section
- Verified all submitted/confirmed transactions are shown under Transaction section
- Verified clicking on Solana account under accounts tab lists all visible tokens for Solana Network
- Verified all NFT's from Solana network are listed under NFT section for Solana network
- Verified all submitted/confirmed transactions are shown under Transaction section for Solana network
