### ISSUE TITLE
Add 1.45.2 translations

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6438]

**Comment by Uni-verse** [comment]
Verified using version `1.45.2 (22.11.18.20)` on the following device(s):

iPhone 12 Pro - iOS 16.x
iPhone XR - iOS 14.x
iPads - iPadOS 16.x

Using Test Plan in https://github.com/brave/brave-ios/pull/6439#issue-1455471521 for checking strings in French, German and Russian locales. Also checked general UI/menu settings for regressions.

### Portfolio Page - NFT Assets

France

Example | Example
-|-
![IMG_0795](https://user-images.githubusercontent.com/17885425/203621556-e350b774-e17c-41ee-b785-8c3fe12d10bc.PNG) | ![IMG_0796](https://user-images.githubusercontent.com/17885425/203621558-360a28c2-71eb-4777-93ea-38615b50ce0e.PNG)


German 

Example | Example
-|-
![IMG_4138](https://user-images.githubusercontent.com/17885425/203622030-f629f476-65bd-4714-ba58-8e50ec2d6c00.PNG) | ![IMG_4139](https://user-images.githubusercontent.com/17885425/203622032-716143d0-ea80-459a-b4c3-99ee73cd850c.PNG)


Russian

Example | Example
-|-
![IMG_0192](https://user-images.githubusercontent.com/17885425/203622553-09427b51-533c-4edb-907d-2af625bd0106.PNG) | ![IMG_0193 2](https://user-images.githubusercontent.com/17885425/203622555-94983263-2721-41ac-83af-5380c757a80a.PNG)


### Add Custom Asset - NFT Page

French 

Example | Example
-|-
![IMG_0793](https://user-images.githubusercontent.com/17885425/203621540-8671ce8f-978d-481d-80ed-22be2de69d7e.PNG) | ![IMG_0794](https://user-images.githubusercontent.com/17885425/203621550-5ee4e892-97c1-4371-ba6d-dadec30d668e.PNG)

German

Example | Example | Example
-|-|-
![IMG_4135](https://user-images.githubusercontent.com/17885425/203622114-71382781-931c-47ed-8923-e309d81f6866.PNG) | ![IMG_4136](https://user-images.githubusercontent.com/17885425/203622118-d754187b-d76c-47eb-abd1-cff42ab1a30a.PNG) | ![IMG_4137](https://user-images.githubusercontent.com/17885425/203622120-b3be7716-e501-4a8a-8274-85d4693fae24.PNG)

Russian

Example | Example | Example
-|-|-
![IMG_0189](https://user-images.githubusercontent.com/17885425/203622222-78abbf29-0067-442e-a937-9ef3ea917504.PNG) | ![IMG_0190](https://user-images.githubusercontent.com/17885425/203622224-e83d6c89-68e7-4d32-b0c2-fdb59ff8d2c5.PNG) | ![IMG_0191 2](https://user-images.githubusercontent.com/17885425/203622227-578c5fa5-c6a6-420c-9aa2-dad11dd2c762.PNG)
