### ISSUE TITLE
Black line shown towards top of screen when scrolling YT homepage

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#6443]
### Description: 
Black line shown towards top of screen on YT homepage when scrolling

<img width="500" alt="black bar" src="https://user-images.githubusercontent.com/17885425/203091020-7e0e7604-b652-480f-81ea-19ecef7c2967.jpg">

### Steps to Reproduce 
  1. Install 1.45.x
  2. Navigate to youtube.com
  3. Scroll the homepage

**Actual result:** 

Blank line is shown when top/bottom bar are hidden

https://user-images.githubusercontent.com/17885425/203092219-f9ec184b-5ffa-41c1-90f6-e5e275598367.MP4

**Expected result:**
No black line

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.45.x

**Device details:** 
iPhone

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
@Uni-verse This is a bug on YouTube, not Brave. It can be replicated on Mobile Safari as well
