### ISSUE TITLE
Changing Brand / Interaction Color

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#6446]
## Problem Description 

Design team wants to change orange traditional brand/interaction color. and we have started implementing a blue color for some new features. Our design team is moving forward with blue and so we want to go and update all the orange we have in the code to blue.

## Feature Overview 

- Switching the orange to the purple, this will be a more manual process finding a lot of the places we use braveOrange and swapping it with the blurple

- Updating the actual blurple can be done in the asset catalog in the DesignSystem module/folder 

- Additionally include some parts of the app which are missing accent color on checkmark and toggle.

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.15.19)` on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPad - iPadOS 16.x

- Verified switching from brave orange or blurple
- Verified toggles, lists, checkboxes have blue
- Verified that buttons/text does cancels, resets/delete are red color

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_0221 2](https://user-images.githubusercontent.com/17885425/209003681-c5a5da71-2c8b-4e13-800f-c595ef32ae11.PNG) | ![IMG_0223 2](https://user-images.githubusercontent.com/17885425/209003709-b41625c1-34d3-45da-92cc-66e3bde0206c.PNG) | ![IMG_0224](https://user-images.githubusercontent.com/17885425/209003721-fcc18470-0cb0-48e5-813d-20abca3ab9cf.PNG) | ![IMG_0226 3](https://user-images.githubusercontent.com/17885425/209003747-182b874a-4e15-404c-8c5f-2ec4f46d2a95.PNG) | ![IMG_0227 3](https://user-images.githubusercontent.com/17885425/209003752-40aeae37-87c5-4b3e-98fd-94e8ae2ccc25.PNG) | ![IMG_0225 2](https://user-images.githubusercontent.com/17885425/209003785-496ee681-7577-4568-abe7-d22c59b91d9d.PNG)
![IMG_0903](https://user-images.githubusercontent.com/17885425/209003902-2fa48fe7-ca7f-44c2-82dc-3f4021fe9578.PNG) | ![IMG_0904](https://user-images.githubusercontent.com/17885425/209003915-7d1a05dd-4956-43a1-9926-028c07afb1d2.PNG) | ![IMG_0900](https://user-images.githubusercontent.com/17885425/209003969-71f59937-57ef-4dd1-9368-fb112fd5da85.PNG) | ![IMG_0908](https://user-images.githubusercontent.com/17885425/209004335-6452e17d-a0b9-4d65-bc90-5b3b03d1f165.PNG) | ![IMG_0910](https://user-images.githubusercontent.com/17885425/209004347-0620b705-036e-4a3b-a18d-81f17ea758c1.PNG) | ![IMG_0906](https://user-images.githubusercontent.com/17885425/209004448-4d439a30-561d-412e-b672-71404cb5801d.PNG)
