### ISSUE TITLE
Playlist :: Items aren't being deleted

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6449]
### Description: 
In the TF version 1.46, items I added to Playlist previously are not being deleted now.  

Version 1.46 (22.11.14.15)
BraveCore 1.46.104 (107.0.5304.110)
Device iPhone13,3 (iOS 16.1)

**Comment by iccub** [comment]
closing for re-testing

**Comment by Uni-verse** [comment]
Verified using version `1.48 (23.2.10.14)` on the following device(s):

`iPhone 12`, `iOS 16.2`
`iPad (9th Gen)`, `iPadOS 15.6.1`
`iPhone X`, `iOS 14.4.2`

**Fresh Profile:**

- Ensured users are able to delete playlist items
- Ensured users are able to delete playlist folders 
- Ensured deleting in edit mode works

Example | Example | Example
-|-|-
![IMG_4419](https://user-images.githubusercontent.com/17885425/218218602-a53fbedb-a5ea-45bd-8144-52855efbd2f8.PNG) | ![IMG_4420](https://user-images.githubusercontent.com/17885425/218218607-265bdab1-0c41-4906-9911-5f8869484715.PNG) | ![IMG_4421](https://user-images.githubusercontent.com/17885425/218218608-c54f3f4f-9c33-4f79-9742-aad9406b22a1.PNG)


**Existing Profile:** 

- Ensured deleting playlist items works on upgraded profile
- Ensured items added post upgrade can be deleted

Previous version | Current Version
-|-
![IMG_4423](https://user-images.githubusercontent.com/17885425/218218970-4d0f3528-7c91-444b-bac8-3ac86d1dbae4.PNG) | ![IMG_4425](https://user-images.githubusercontent.com/17885425/218218978-ec1d97f8-975e-4403-8ede-0ad9903c051a.PNG)
![IMG_0108 2](https://user-images.githubusercontent.com/17885425/218220503-297c8d71-12a0-4fb7-9bc9-18a4f8b85ddd.PNG) | ![IMG_0109 2](https://user-images.githubusercontent.com/17885425/218220512-746fa95c-688e-4e6b-a672-a7de57b968a1.PNG)
