### ISSUE TITLE
Tab bar rotation bug

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6452]
### Description: 

Rotating the device in certain conditions causes url bar to be stuck in collapsed state

### Steps to Reproduce 
  1. Enable bottom tab bar, always show tab bar
  2. Open at least 2 tabs
  3. Rotate to landscape mode
  4. Scroll down so the tab bar goes to collapsed state
  5. Rotate back to portrait mode

**Actual result:** 

https://user-images.githubusercontent.com/5314553/203355194-62b47b9a-5607-409d-bd9e-cfe52189cdaf.mov

**Expected result:**

URL bar is visible or bar remains in collapsed state in Portrait mode

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.8.20)` on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.4.2

STR: https://github.com/brave/brave-ios/issues/6452#issue-1460101937

- Verified URL bar is visible after rotating device

https://user-images.githubusercontent.com/17885425/206777874-52c60864-94dd-4457-a53d-752b046e58d6.MP4
