### ISSUE TITLE
Add Hide for now capability to Filter Open Tab Session 

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#6453]
## Problem Description 

When a device is removed from Sync Chain, the Open Tab Sessions of this device is not removed by the server automatically. The time limit server initiates the clean up is after 14 days of inactivity. 

https://old.reddit.com/r/brave_browser/comments/y5zas2/old_iphone_stuck_on_sync_chain_even_though_i/

## Feature Overview- Implementation Details  

Add `Hide for now` functionality on client side, this capability is merged on Chromium iOS side with https://github.com/brave/brave-core/pull/16003

Along with the `Hide for now`, add `Open All` to session header and also include `open` - `share` - `copy` to tab information in the list.

## Design 

Long Press to table section view header

![1 2](https://user-images.githubusercontent.com/6643505/203367423-25856a70-80bc-426e-9a5b-b9b4425584d6.png)

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.15.29)` on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPad (7th Gen) - iOS 16.x

- Verified clicking `Open All` for device in list will open all tabs
- Verified `Hide for now` removes device from the tab sync page
- Verified user is able to open all tabs from desktop client on mobile and vice versa
- Verified long press on tabs listed will bring up context menu
- Verified tab is opened in new tab using`Open in New Tab` from context menu
- Verified value in clipboard using `Copy Link`
- Verified `Share Link` works and user is able to share tab using `Send to my devices`

Example | Example 
-|-
![IMG_4249](https://user-images.githubusercontent.com/17885425/208966567-80a1727f-7fa4-4057-bff2-2f53bd76e7d1.PNG) | ![IMG_4255](https://user-images.githubusercontent.com/17885425/208970951-c14f19e1-9a5c-4805-bb08-121f751fb63f.PNG)
![IMG_0895](https://user-images.githubusercontent.com/17885425/208966604-5abb0191-4263-4754-81d8-7529f5ac26f4.PNG) | ![IMG_0899](https://user-images.githubusercontent.com/17885425/208970995-6a4939ff-28ce-4611-bb08-b7c4b63fd56a.PNG)
