### ISSUE TITLE
Wallet: Send Screen auto-dismissed

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6460]
### Description: 
if you go to Buy/Send/Swap Screen from asset detail, those screens will auto-dismissed
1. if you change selected account
2. if you change your selected network
3. if asset detail finishes loading at the background 

### Steps to Reproduce 
  1. open brave wallet
  2. go to any asset detail 
  3. click either buy/send/swap
  4. click account picker
  5. change to another account 
 

**Actual result:** 
account list will dismiss, and right after, buy/send/swap screen will be dismissed as well

**Expected result:**
should stay at buy/send/swap screen

**Reproduces how often:** [Easily reproduced]

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.45.2 (22.11.23.16)
- Verified steps from issue description and [#6463](https://github.com/brave/brave-ios/pull/6463)
- Verified send screen doesn't auto-dismiss when selecting Send form portfolio or token details screen
- Verified send screen doesn't auto-dismiss for NFT or Tokens
-----------
Verification passed on iPhone XR with iOS 14.8.1 running 1.45.2 (22.11.23.16)
- Verified steps from issue description and [#6463](https://github.com/brave/brave-ios/pull/6463)
- Verified send screen doesn't auto-dismiss when selecting Send form portfolio or token details screen
- Verified send screen doesn't auto-dismiss for NFT or Tokens
-----------
Verification passed on iPad Pro with iOS 16.1 running 1.45.2 (22.11.23.16)
- Verified steps from issue description and [#6463](https://github.com/brave/brave-ios/pull/6463)
- Verified send screen doesn't auto-dismiss when selecting Send form portfolio or token details screen
- Verified send screen doesn't auto-dismiss for NFT or Tokens
