### ISSUE TITLE
Startup time increased after 1.45.* update

### ISSUE THREAD

**Issue by pashynskykh** [brave/brave-ios#6461]
### Description: 
Before 1.45 update, Brave was the fastest browser. Now it takes much more time to load the application. 

### Steps to Reproduce 
  1. Open Brave Browser on iOS.

**Actual result:** 
Brave is loading fast. Even faster than Safari.

**Expected result:**
Brave is loading slower. And 2x slower, than Safari,

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Often, but looks like not every time. 

**Brave Version:** 
1.45.1 (22.11.17.19)

**Device details:** 
iPhone 11, iOS 16.1.1

**Comment by iccub** [comment]
How big is the delay you are experiencing roughly?

We had a fix some adblock timing problems and this introduced small delay before the app loads, from our tests it looked like no higher than 1 second.

**Comment by iccub** [comment]
Second question: Do you have many custom filter lists enabled or just the default set of lists?

**Comment by pashynskykh** [comment]
@iccub 

> How big is the delay you are experiencing roughly?

Total load of application now took up to 2 seconds. Before this update, it was loading almost immediately. I think, delay is 1 second, maybe a little more.

> Second question: Do you have many custom filter lists enabled or just the default set of lists?

Yes, I have 9 filter lists enabled (I need filters for Nordic countries and Ukraine).

**Comment by iccub** [comment]
Thanks @pashynskykh. We are looking into fixing this

**Comment by Uni-verse** [comment]
Verified using version `1.47 (23.1.30.21)` on the following device(s):

iPhone 12, iOS 16.2
iPad (9th Gen), iPadOS 15.6.1
iPhone X, iOS 14.42


- Ensured there is no delay during brave startup on 1.47.x
- Ensured adblock is working, youtube ad lists are ready when app is loaded.

Example | Example
-|-
![IMG_0099 2](https://user-images.githubusercontent.com/17885425/215911382-4a42fc15-8063-4ece-bb6c-e9ff549c95e1.PNG) | ![IMG_4356](https://user-images.githubusercontent.com/17885425/215911438-9663cbf2-c41e-4747-bcc8-6f424b621b4e.PNG)
