### ISSUE TITLE
Adderss bar (at the bottom): inputted URL misaligned with autocompletion 

### ISSUE THREAD

**Issue by pashynskykh** [brave/brave-ios#6462]
### Description: 
Inputted URL misaligned with autocompletion in address bar.

### Steps to Reproduce 
  1. Open browser.
  2. Start typing in URL.
  3. See autocompletion. 

**Actual result:** 
Inputted URL misaligned with autocompletion in address bar.

**Expected result:**
Inputted URL aligned with autocompletion in address bar.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Every time.

**Brave Version:** 
1.45.1 (22.11.17.19).

**Device details:** 
iPhone 11, iOS 16.1.1

### Additional Information - screenshot
![IMG_0105](https://user-images.githubusercontent.com/14852335/203493984-d38ee08d-adb1-4686-ad1a-85a6736e88f1.jpg)

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.7.14)` on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPads iPadOS 16.x, 15.x

Using STR in https://github.com/brave/brave-ios/issues/6462#issue-1461213543

Example | Example
-|-
![IMG_0058 3](https://user-images.githubusercontent.com/17885425/206299764-636e36c8-5149-43ac-b147-84ff99b38147.PNG) | ![IMG_4188](https://user-images.githubusercontent.com/17885425/206299955-7a4c34b8-cd64-44d0-bff7-e8f4e6956765.PNG)
