### ISSUE TITLE
Youtube playback quality Safari parity mismatch

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6475]
We should try to match Safari in what playback options are available on youtube. See screenshots to notice differences

Sample url https://www.youtube.com/watch?v=Uz-Ei3vqo-Q
Default - desktop UA

<img width="1001" alt="Zrzut ekranu 2022-11-24 o 11 18 46" src="https://user-images.githubusercontent.com/6950387/203761111-018f5185-86fe-468a-958a-dbb6cc3aea86.png">

Mobile UA
<img width="1244" alt="Zrzut ekranu 2022-11-24 o 11 27 10" src="https://user-images.githubusercontent.com/6950387/203761185-82bcfa22-b3be-4d4e-a14c-7c741660240c.png">

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.15.19)` using the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPad - iPadOS 16.x

- Verified playback quality on youtube.com matches Safari youtube page

Example | Example
-|-
![IMG_0212 2](https://user-images.githubusercontent.com/17885425/208785082-b95de473-7bec-4880-ae35-9e30783b1cc3.PNG) | ![IMG_0213 2](https://user-images.githubusercontent.com/17885425/208785089-34429b27-f8d7-4bd0-931a-2b5327e681bc.PNG)
![IMG_0890](https://user-images.githubusercontent.com/17885425/208785124-f602b3c5-e9d2-4490-a7d1-f10f3383016f.PNG) | ![IMG_0892](https://user-images.githubusercontent.com/17885425/208785128-45b89626-88b6-48a3-b308-7e2a545e9297.PNG)
