### ISSUE TITLE
ERC721 tokens doesn't list under search asset screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#6476]
### Description: 
ERC721 tokens doesn't list under search asset screen

### Steps to Reproduce 
  1. Add ERC721 token to portfolio
  2. Click on the search token icon in wallet home screen
  3. Type in the token name, nothing shows up

**Actual result:** 

https://user-images.githubusercontent.com/17010094/203777661-054dfe79-a0c6-4f46-b08d-7e5ce375a445.MP4

**Expected result:**
Should list token in search token screen

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.45.2 (22.11.23.16)

**Device details:** 
iPhone XR (iOS 15.6.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @StephenHeaps @nuo-xu

**Comment by StephenHeaps** [comment]
Closing as fixed in https://github.com/brave/brave-ios/pull/6510

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-ios/issues/6481#issuecomment-1339093100
