### ISSUE TITLE
Show assets from all networks in Token Search (Multichain)

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6481]
### Description: 

Similar to https://github.com/brave/brave-ios/issues/6353, we should display assets from all networks.

It may make sense to include user assets in this view to resolve https://github.com/brave/brave-ios/issues/6476

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46(22.12.3.0)
- Verified steps from [#6510](https://github.com/brave/brave-ios/pull/6510)
- Verified able to filter tokens from a specific network
- Verified able to search for custom token in search asset 
- Verified all tokens from all networks are listed by default

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (iOS 16.2)
-- | -- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/205882509-9db24e73-db75-400d-9f75-6fe7b79b5b4d.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/205882080-1266321e-6630-4687-b6ac-e889b15094de.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/205884121-db306521-d5b7-416a-95ff-91e6b54441b7.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/205882542-e6bd112d-3960-4933-89d2-16f7b4ba594e.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/205882026-3401a194-0f74-473b-bf4d-6baa405924d2.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/205884135-08188074-683f-4bfe-8dc1-fb64c38016a3.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/205882563-9c5f0a25-d0f1-4376-843a-c6060eaf0393.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/205882136-5f5763c0-f5f6-448d-89aa-90bf16c5e3ca.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/205884159-6accbd8c-46cb-4606-bf85-f7cd1397a684.png>
