### ISSUE TITLE
Add mute keyboard shortcuts to Brave Talk native integration

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6484]
### Description: 

Add keyboard shortcuts for muting & unmuting your mic using the same shortcuts as the web (`m` to toggle, space bar to unmute while pressed)

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.15.19)` on iPads running `iPadOS 16.x` & `iPadOS 15.x`

Keyboards: Apple attached smart keyboard for iPad

- Confirmed shortcuts for muting & unmuting mic match web
- Confirmed `m` key to toggle microphone w/ attached keyboard
- Confirmed holding down `space bar` key to unmute microphone
- Confirmed shortcuts are working when user has not enabled microphone permissions on the call, user will be prompted to allow microphone in brave talk. 
- Confirmed shortcuts are working when user has enabled microphone in the join screen. User is able to toggle and enable with space bar while muted

Mic Permissions | Mic enabled | Mic disabled
-|-|-
![IMG_0074 2](https://user-images.githubusercontent.com/17885425/208749403-277e6792-bf83-4152-b593-cddfc85b4575.PNG) | ![IMG_0886](https://user-images.githubusercontent.com/17885425/208749407-39d17d9e-a282-4141-bfc8-7daf619a73e0.PNG) | ![IMG_0887](https://user-images.githubusercontent.com/17885425/208749409-60d5b5a4-57a1-4a5a-8461-51ad4bc94efe.PNG)
