### ISSUE TITLE
Additional filter lists block less than on desktop

### ISSUE THREAD

**Issue by davidcollini** [brave/brave-ios#6487]
### Description: 
On desktop, fanboy annoyances and ublock origin annoyances list block a lot more than they do on iOS

Sites such as 
Zoro.to
Actvid.com
9anime.to

work without the website constantly switching to a different tab on desktop, but on mobile, this isn’t blocked

### Steps to Reproduce 
  1. Enable fanboy annoyances and ublock annoyances
  2. Go to one of these sites and notice how tabs constantly open compared to these lists blocking the tabs opening on desktop
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
cc @ryanbr

**Comment by ryanbr** [comment]
Ios blocking is still a work in progress. Many of these sites will also change adservers on a daily basis to counter any additions we do. I have made some updates today, see if it helps. @IronMaltese

**Comment by davidcollini** [comment]
While it’s definitely not 100%, I do notice an improvement, Thank you!

**Comment by davidcollini** [comment]
Also since these sites constantly try to get around filter lists, maybe you can look into an opt-in switch to block popovers altogether, similar to what another iOS browser, [Snowhaze](https://github.com/snowhaze/SnowHaze-iOS) does in an optional setting

**Comment by davidcollini** [comment]
I just updated TestFlight, and this is working very well, thanks!
