### ISSUE TITLE
Changing network doesn't close the network picker screen and update the tokens on portfolio

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#6491]
### Description: 
Changing network doesn't close the network picker screen and update the tokens on portfolio

### Steps to Reproduce 
  1. Install 1.45.2 on iOS 16 device
  2. Create wallet 
  3. Add this Custom NFT as asset: https://testnets.opensea.io/assets/goerli/0xd046b780bcc00f59a6a0294a042e9468d08ceb0d/23
      - This asset returns an error when calling GetERC721Balance with message `execution reverted: ERC721: owner query for nonexistent token` which causes the bug. Any asset returning this error message should result in the same.
  4. Select network dropdown and change network, doesn't auto close network picker screen
  5. Manually close the screen
  6. Network is updated but tokes aren't

**Actual result:** 

https://user-images.githubusercontent.com/17010094/204003687-56e8864f-a7cc-40f9-94a3-da987518c60c.MP4

**Expected result:**
Should auto close the network selection window and update tokens accordingly 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.45.2 (22.11.23.16)

**Device details:** 
iPad Pro iOS 16.1

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by iccub** [comment]
The dev team tried to reproduce it and we were not able to. Tried few different devices and on simulators as well

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 16.1 running 1.45.2 (22.11.29.0)
- Verified steps from issue description and [#6503](https://github.com/brave/brave-ios/pull/6503)
- Verified able to switch network 
- Verified switching network automatically updates the tokens for that network

https://user-images.githubusercontent.com/17010094/204510684-4eb2c682-6541-4f9e-ad8c-9e57d28c4767.MP4

Also did a sanity check on iPhone 7+ (iOS 14.8.1) & iPhone XR (iOS 15.6.1)

**Comment by srirambv** [comment]
This is fixed in https://github.com/brave/brave-ios/commit/8e6b0b8a699c2816a79310a15aa7f544e4c33aa9
