### ISSUE TITLE
NFT overlaps on token in portfolio

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#6492]
### Description: 
NFT overlaps on token in portfolio

### Steps to Reproduce 
Don't know. All I did was change tokens and network in Send screen

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/204011006-8941e427-b0d2-44b9-8459-56af9597d542.png)

**Expected result:**
Tokens should not overlap

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Happened once

**Brave Version:** 
1.45.2 (22.11.23.16)

**Device details:** 
iPhone 7+ (iOS 14.8.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @StephenHeaps @nuo-xu

**Comment by StephenHeaps** [comment]
Closing as this is not relevant / possible after Portfolio v2 UI:
https://github.com/brave/brave-ios/issues/8072
