### ISSUE TITLE
Keyboard overlaps url bar for Find in Page

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6495]
### Description: 

With bottom url bar enabled, 'Find in Page' shows the url bar ~50% under the keyboard. Does not occur with url bar at top.

### Steps to Reproduce 
  1. Enable bottom url bar
  2. Visit any website
  3. Tap 3-dot menu, tap 'Find in Page'

**Actual result:** 

![find in page](https://user-images.githubusercontent.com/5314553/204309840-2a3fb9e2-b599-4cf7-bdf0-e2be791ab6f0.png)

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using version 1.46 (22.12.7.14) on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPads iPadOS 16.x, 15.x

Using STR in https://github.com/brave/brave-ios/issues/6495#issue-1466588144

- Verified keyboard doesnt overlap url bar when using `Find in Page`

Example | Example
-|-
![IMG_4187](https://user-images.githubusercontent.com/17885425/206298592-11f41cd8-e469-4774-8061-e1eedaf925fb.PNG) | ![IMG_0057 2](https://user-images.githubusercontent.com/17885425/206298605-897a1050-6f00-42dc-afba-1f76df6b9232.PNG)
