### ISSUE TITLE
redesign the error page

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#650]
### Description: 
The error page in V1.7 is not clear and needs design work

<img width="437" alt="screen shot 2018-12-18 at 11 15 19 am" src="https://user-images.githubusercontent.com/7606853/50178478-78c6a380-02b9-11e9-9db2-360a875cf0e4.png">

**Comment by kylehickinson** [comment]
I think we already have a ticket for something similar: #317

**Comment by jhreis** [comment]
Closing as duplicate of: https://github.com/brave/brave-ios/issues/317
