### ISSUE TITLE
Wallet: NFT asset icon in portfolio and other token list screen

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6501]
We are not able to fetch NFT (ERC721) token's metadata. This means asset icon can render NFT image if asset is ERC721 and has image data.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46 (22.12.7.22)
- Verified steps from [#6534](https://github.com/brave/brave-ios/pull/6534)
- Verified NFT asset icon is shown in portfolio and on other token list screen such as search asset or edit asset
- Verified when NFT metadata isn't loaded or available it shows a monogram letter of the NFT

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (iOS 16.2)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/206428266-457b5121-aaa7-4019-bc25-3ad19e2a3ed7.MP4> | <video src=https://user-images.githubusercontent.com/17010094/206428329-7a328005-19a1-40b2-8c83-bebac1b1dfcc.MP4> | <video src=https://user-images.githubusercontent.com/17010094/206428098-e005e4b3-0ea9-4bbd-a94a-9df7712c8b76.MP4>
