### ISSUE TITLE
[Brave News] Update copy for subhead on `Show Brave News` toggle in Settings

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-ios#6505]
The `Show Brave News` toggle includes a subhead. The copy should state the following:

`Follow your favorite sources, in a single feed. Just open a tab in Brave, scroll down, and… voila! Brave News is ad-supported with private, anonymized ads."`

**Comment by Uni-verse** [comment]
Verified on version `1.46 (22.12.6.11)` using the following devices:

iPhone 12 Pro - iOS 16.x
iPhone XR - iOS 15.x
iPad (7th Gen) - iPadOS 16.x

- Verified Brave News onboarding banner subhead copy is updated.
- Verified copy on NTP and brave news settings in menu

iPad Example | iPhone Example | iPhone Example
-|-|-
![IMG_0822](https://user-images.githubusercontent.com/17885425/206015912-2013392a-d660-4261-adaa-a8cc7f30e6f4.PNG) | ![IMG_4180](https://user-images.githubusercontent.com/17885425/206016481-97dce8a8-1f14-4845-b4a3-389fe5db6ddb.PNG) | ![IMG_4181](https://user-images.githubusercontent.com/17885425/206016516-4f94b1d8-47b4-4ce6-9dea-d685f467590a.PNG)
