### ISSUE TITLE
Buy / Send / Swap doesn't respect prefilled token network

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6509]
### Description: 

Buy / Send / Swap can be opened with a prefilled token, but use the currently selected network which may not match that token.

### Steps to Reproduce 
  1. Open Buy / Send / Swap and select Ethereum network
  2. Close Buy / Send / Swap and tap Solana Mainnet asset in Portfolio assets list
  3. Tap 'Buy' or 'Send' or 'Swap' on asset detail page
  4. Observe correct token selected, but Ethereum network displayed (token belongs to Solana).
      - Note: the balance will always be 0, so transaction can't be created.

**Actual result:** 

https://user-images.githubusercontent.com/5314553/204588142-5f758f3b-0482-456d-b990-92b96e972654.mov

**Expected result:**

Selected network should switch to prefilled token, or don't prefill the token.

**Reproduces how often:** 

Easy

**Brave Version:** 

v1.46 (22.11.28.21) or later

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8.1 running 1.46 (22.12.6.19)
- Verified steps from [#6535](https://github.com/brave/brave-ios/pull/6535)
- Verified network tokens are prefilled when network is changed
----------
Verification passed on iPhone XR with iOS 15.7.1 running 1.46 (22.12.6.19)
- Verified steps from [#6535](https://github.com/brave/brave-ios/pull/6535)
- Verified network tokens are prefilled when network is changed
----------
Verification passed on iPad Pro with iOS 16.2 running 1.46 (22.12.6.19)
- Verified steps from [#6535](https://github.com/brave/brave-ios/pull/6535)
- Verified network tokens are prefilled when network is changed
