### ISSUE TITLE
Buy only shown on Asset Details when supported by Wyre

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6514]
### Description: 

'Buy' button is only displayed in Asset Details when the token is supported via Wyre. We should display 'Buy' for any token supported by Wyre, Ramp or Sardine

### Steps to Reproduce 
  1. Open Wallet
  2. Tap Buy/Send/Swap and open 'Buy' modal
  3. Select Solana Mainnet in network picker
  4. Verify providers are available for SOL token.
  5. Close Buy modal
  6. In Portfolio, tap 'SOL' on Solana Mainnet
  7. Observe no 'Buy' button shown

**Actual result:** 

https://user-images.githubusercontent.com/5314553/204663320-74fb6660-213e-4eba-8933-72ab868897f8.mp4

**Expected result:**

'Buy' button is displayed for SOL on Solana Mainnet

**Reproduces how often:** 

Easily reproduced

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46 (22.12.6.11)
- Verified steps from [#6515](https://github.com/brave/brave-ios/pull/6515)
- Verified Buy button is shown on asset details screen for Solana Tokens
- Verified Swap is shown for supported tokens on asset details screen

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) |iPad Pro (iOS 16.2)
-- | -- | --
<video src=https://user-images.githubusercontent.com/17010094/205967175-757651e0-c0b6-4192-a508-bcb3ee34d97c.MP4> | <video src=https://user-images.githubusercontent.com/17010094/205967202-a8a87009-5317-4d41-abdc-19c7b5f084d4.MP4> | <video src=https://user-images.githubusercontent.com/17010094/205967161-6d3d96bd-051f-4d1b-8425-bb12ced6f2de.MP4>
