### ISSUE TITLE
`show more` button under NTP being removed when deleting a tile from `Favorite`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#6516]
### Description: 

Removing a `tile` from the `Favorite` widget removes the `Show more` button under NTP and it never appears to return/recover unless you add another website into the `Favorite` widget. Once added, the `Show more` returns and functionality returns to normal.

Seems like this is specific to mobile and not `iPads` as I couldn't reproduce the issue with my `iPad` that's running `iOS 16 BETA`.

### Steps to Reproduce

  1. launch/install brave from TF or the App Store (reproducible using `1.45.1 (22.11.17.19)` & `1.45.2 (22.11.29.0)`
  2. run through onboarding (doesn't matter if you skip or run through everything)
  3. once the NTP loads, remove any tile from the first row and you'll notice that the `Show more` button is removed
  4. visit and website and add it into the `Favorite` widget (you'll notice that the `Show more` button appears again)

Please see the attached video below for an example of the issue occurring.

**Actual result:** 

https://user-images.githubusercontent.com/2602313/204738230-78024f40-0860-45c2-8066-43b713b4389d.mp4

**Expected result:**

We shouldn't be removing the `Show more` button if there's more than four tiles saved when a user removes a tile from `Favorite`.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible when using the STR/Cases outlined above.

**Brave Version:** 

* `1.45.1 (22.11.17.19)` - **Reproducible**
* `1.45.2 (22.11.29.0)` - **Reproducible**

**Device details:** 

* `iPhone 11` running `iOS 16.2` - **Reproducible**
* `iPad Air (3rd Gen)` running `iOS 16 BETA` - **Couldn't reproduce**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @srirambv @Uni-verse

**Comment by kylehickinson** [comment]
I can't seem to reproduce this anymore in 1.48, can you please re-test?

**Comment by Uni-verse** [comment]
Testing completed on `iPhone 12`, `iPhone XR` running `iOS 16.2`, `iOS 15.5` using version `1.48 (23.2.10.14)`

- Unable to reproduce on version 1.48

Example | Example
-|-
![IMG_4471](https://user-images.githubusercontent.com/17885425/218547526-93150670-9e62-4295-8452-cedb67ad1327.PNG) | ![IMG_4472](https://user-images.githubusercontent.com/17885425/218547528-6c0f0dcc-a1a5-45fd-b15e-347a46532171.PNG)
