### ISSUE TITLE
scrolling/swiping stops working under https://www.theblock.co after using `Open in New Tab`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#6518]
### Description: 

Scrolling/Swiping under https://www.theblock.co will stop working after using `Open In New Tab` making it impossible to use the website. I run into this pretty consistently making it impossible to use the website. Sometimes scrolling will just stop working when scrolling through https://www.theblock.co/latest.

### Steps to Reproduce 

  1. launch/install brave from TF or the App Store (reproducible using `1.45.1 (22.11.17.19)` & `1.45.2 (22.11.29.0)`
  2. run through onboarding (doesn't matter if you skip or run through everything)
  3. load https://www.theblock.co/latest
  4. long tap on several of the article images and click on `Open in New Tab`

You'll notice after opening ~2-3 websites using the STR/Cases mentioned above, scrolling will break on the active tab.

**Actual result:** 

The ability to scroll/swipe through the website eventually breaks under https://www.theblock.co making it impossible to use the website. Here's a quick video of the issue occurring. You won't see the scrolling gestures but near the end, I'm attempting to scroll through the website and nothing happens:

https://user-images.githubusercontent.com/2602313/204747822-57d257a3-920b-49a2-be1b-572ba393fbe8.mp4

**Expected result:**

The ability to scroll/swipe through https://www.theblock.co should always work and not break. Once it breaks, it makes the entire tab usable and users need to either switch context or close the tab all together.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible when using the STR/Cases outlined above.

**Brave Version:** 

* `1.45.1 (22.11.17.19)` - **Reproducible**
* `1.45.2 (22.11.29.0)` - **Reproducible**

**Device details:** 

* `iPhone 11` running `iOS 16.2` - **Reproducible**
* `iPad Air (3rd Gen)` running `iOS 16 BETA` - **Reproducible**

**Website problems only:**

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `No` (still reproducible when shields have been disabled)

### Additional Information

CCing @srirambv @Uni-verse

**Comment by kylehickinson** [comment]
On regular Safari, after opening a few tabs, this popup appears: 

![Image](https://user-images.githubusercontent.com/529104/220457144-14440550-8b85-4365-8338-71d563461e8f.png)

My guess is that cosmetic filters are removing it but not removing the `overflow-hidden` class applied to the `<body>` tag

```
.overflow-hidden {
  overflow: hidden!important;
}
```

**Comment by kylehickinson** [comment]
@cuba to verify why the styles are not being applied properly

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` & `iPad (9th Gen)` running `iPadOS 15.5`

STR: https://github.com/brave/brave-ios/issues/6518#issue-1469249941

- Ensured that user is able to scroll through `https://www.theblock.co` after opening a new tab from this page.

Example | Example
-|-
![IMG_0171 2](https://user-images.githubusercontent.com/17885425/228352641-597bf4a8-f1ca-4299-8601-164356358378.PNG) | ![IMG_2856](https://user-images.githubusercontent.com/17885425/228352678-c18a6c60-21e1-4f1c-bbd7-dc06db44f646.PNG)
