### ISSUE TITLE
Update RSS title after loading feed

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6519]
### Description: 

When you add an RSS feed to Brave News we fetch the HTML from a webpage to get any rss feeds and list them out. The title that they list on the webpage itself doesn't always match the one that is in the actual RSS feed XML. We should update the feed once we load it so it looks nicer.

### Example
1. Attempt to add `mediagazer.com` RSS feed
2. Notice the title is "RSS" instead of Mediagazer which is what it is inside the RSS feed XML

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.2.14)` on the following device(s):

`iPhone 12 Pro` -` iOS 16.1`
`iPhone XR` - `iOS 15.x`
`iPhone X` - `iOS 14.4.2`
`iPad` - `iPadOS 16.x`

Using STR from https://github.com/brave/brave-ios/issues/6519#issue-1469862238

- Verified able to add `mediagazer.com` RSS feed 
- Verified RSS title is updated after loading feed


Original Title | After Add RSS | After Adding RSS (iPad)
-|-|-
![IMG_4150](https://user-images.githubusercontent.com/17885425/205354022-97fce1f3-0964-40fc-ad0d-e0b7f96f72d0.PNG) | ![IMG_4151](https://user-images.githubusercontent.com/17885425/205354026-f6d43f88-bd63-469e-9ac5-ea2cf6bbec21.PNG) | ![IMG_0799](https://user-images.githubusercontent.com/17885425/205354016-891fd56c-2fcc-4ac7-980b-900315e60478.PNG)
