### ISSUE TITLE
URL bar only showing origin in both display & edit mode

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6521]
### Description: 

We are only showing the origin (with www) in the URL bar even when a user taps to edit the URL.

Share URL seems to be unaffected, so its just the URL bar

### Steps to Reproduce 
  1. Launch app and visit any page (e.g. `amazon.com`)
  2. Navigate to other pages
  3. See URL bar only displaying the origin
  4. Tap to edit the URL bar
  5. See URL inside the text field is also only displaying the origin

**Actual result:** Only the origin shows
**Expected result:** The full url should show
**Reproduces how often:** Always
**Brave Version:** 1.46 (22.11.28.21)
**Device details:** iPhone 13 Pro (16.1.1)

https://user-images.githubusercontent.com/529104/204850948-764049cc-8f12-4092-826b-7f2969c1be6e.mp4

**Comment by diracdeltas** [comment]
This is a pretty bad regression - possible to add a test for it?

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.8.20)` on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPad - iPadOS 16.x

https://github.com/brave/brave-ios/issues/6521#issue-1469892795

- Verified that full URL is displayed in the URL bar
- Verified that full URL is shown while in edit mode

Example | Example
-|-
![IMG_0849](https://user-images.githubusercontent.com/17885425/206744480-2d7384ec-090a-46c7-9d3d-3451eb4eeb89.PNG) | ![IMG_0204 2](https://user-images.githubusercontent.com/17885425/206744651-5b2b7733-d632-4bbe-8e6c-780404ecd396.PNG)
