### ISSUE TITLE
Auto enable certain regional filter lists

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#6523]
### Description: 
Automatically enable certain filter lists that are well maintained based on device language. For the time being we want to at least enable the Japanese filter list. 

**Actual result:** 
When launching the app for the first time, the Japanese filter list is not enabled

**Expected result:**
When launching the app for the first time, the Japanese filter list should be automatically enabled

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.45

**Device details:** 
Any

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
We disabled the automatic filter lists when we added a filter lists screen which allows a user to chose which filter lists to enable regardless of language. Previously, filter lists were automatically enabled depending on your device language. (we also only supported language specific filter lists and not filter lists such as cookie consent blocking)

This is in parity of desktop/android

**Comment by Uni-verse** [comment]
Verified on `iPhone 12`, `iOS 16.2` & `iPad (9th Gen)`, `iPadOS 15.6.1` using version `1.48 (23.2.13.20)`

- Ensured that Adguard Japanese filters are enabled on a new profile with region set to `Japan`

Example | Example
-|-
![IMG_0121 2](https://user-images.githubusercontent.com/17885425/218888470-0ae254f0-65d0-4d86-a1b5-dbed416c13cd.PNG) | ![IMG_4487](https://user-images.githubusercontent.com/17885425/218888516-e5b432f5-46b5-4b5b-8ad0-8f3f54d17a41.PNG)
