### ISSUE TITLE
Re-enable HTTPSE UI

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#653]
Revert https://github.com/brave/brave-ios/pull/651

**Comment by srirambv** [comment]
Verified HTTPSE global shield setting is available
Verified HTTPSE can be turned off at site level and works fine
Verified HTTPSE upgrade fails when turned off at site level/global level
Verified HTTSPE upgrade fails when shields is turned off for a site

**Comment by LaurenWags** [comment]
Verified items from https://github.com/brave/brave-ios/issues/653#issuecomment-454702484 on iPad 5th Gen using 1.7.2 (19.1.16.16).
