### ISSUE TITLE
Update VPN CTA - Purchase Flow

### ISSUE THREAD

**Issue by timchilds** [brave/brave-ios#6533]
We recently received some feedback for improving subscription rates. One of the ideas is related to the VPN CTA. The suggestion is to emphasize "FREE" more as this usually helps increase conversion.

![image](https://user-images.githubusercontent.com/28269287/205127899-cc40080c-09ed-4cc3-920e-0e6b405740e5.png)

## Requirements
1. Change the VPN purchase flow to a two step:

```
1. Tap monthly or yearly (yearly selected by default)
2. Tap "TRY 7 DAYS FREE" button (this is a new button - it does not currently exist)
```

2. Bold and underline the "free 7-day trial" text.

3. Make the one year option the first option (put it above the monthly option).

----

Android ticket for reference: https://github.com/brave/brave-browser/issues/26791

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using version `1.56 (23.7.14.16)`

Acceptance Criteria: https://github.com/brave/brave-ios/issues/6533#issue-1471749600

- Ensured yearly VPN option is selected by default
- Ensured that free 7 day trial text is underlined
- Ensured that user is able to select both option
- Ensured yearly option is on top
- Ensured tapping on `Try 7 Days Free CTA` will advance user in the flow
- Ensured purchasing monthly and yearly options is successful

Example | Example | Example | Example | Example | Example | Example
-|-|-|-|-|-|-
![IMG_3337](https://github.com/brave/brave-ios/assets/17885425/29aa82ad-1618-4452-8e94-5f881efbf826) | ![IMG_3334](https://github.com/brave/brave-ios/assets/17885425/2f382388-72c7-4105-a783-c0a0c49eeaf8) | ![IMG_3335](https://github.com/brave/brave-ios/assets/17885425/3f57d12a-1bcc-4a30-b675-8a2922a1cbe3) | ![IMG_3338](https://github.com/brave/brave-ios/assets/17885425/c2017f22-c792-479e-b71e-87c3023fee31) | ![IMG_3339](https://github.com/brave/brave-ios/assets/17885425/3e4b7352-62f1-4bdb-bb25-374f4aa5bb0e) | ![IMG_3340](https://github.com/brave/brave-ios/assets/17885425/7b0031f3-561a-40cd-a941-72b7e59b00cc) | ![IMG_3341](https://github.com/brave/brave-ios/assets/17885425/277efe3b-e8b1-41f2-b76d-06d2778880db)
