### ISSUE TITLE
P3A slide buttons color isn't dark blue in dark mode for existing users

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#6536]
### Description: 
P3A slide buttons color isn't dark blue in dark mode for existing users

### Steps to Reproduce 
  1. Set the device to Dark mode
  2. Clean profile 1.45.x 
  3. Upgrade the profile to 1.46.x
  4. P3A slide buttons color isn't dark blue in dark mode for existing users

**Actual result:** 

P3A slide buttons color isn't dark blue in dark mode for existing users

**Expected result:**
As per figma spec, the P3A slide buttons should be in dark blue color in dark mode for existing users
https://www.figma.com/file/irDJRP35FUwsRu60Wp9fM6/iOS-onboarding?node-id=3321%3A54735&t=OHK0wJLjBiri43Xq-0
**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.46.x

**Device details:** 
iPhone 8 - iOS 16.1.1

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information

cc: @brave/qa-team @kylehickinson @anthonypkeane

**Comment by kylehickinson** [comment]
This is expected, we use a lighter blurple across dark mode for better visibility

**Comment by Uni-verse** [comment]
Verified using version 1.46 (22.12.8.20) on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.4.2
iPad - iPadOS 15.x

- Verified P3A slide buttons color is blue for existing users

Example | Example
-|-
![IMG_4207](https://user-images.githubusercontent.com/17885425/206770645-6a9495ee-0771-42ed-9ba2-ee5155e772d4.PNG) | ![IMG_0855](https://user-images.githubusercontent.com/17885425/206770923-7943b915-c7dc-4153-8d09-c809c1c9edbb.PNG)
