### ISSUE TITLE
Low res image in brave news feed

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#6542]
### Description: 
Low res image appearing in brave news feed

### Steps to Reproduce 
  1. Clean install
  2. Turn on Brave News 
  3. Look for articles from `Washington Post` or `The New York Times`

**Actual result:** 
![IMG_0797](https://user-images.githubusercontent.com/17885425/205374333-16f22591-7ea7-4941-b6d4-5a2fe17c5373.jpg)

**Expected result:**
high res, crisp image like the rest

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.46 (22.12.2.14), 1.45.2

**Device details:** 
iPhone, iPad

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
Im going to close this as not planned as we can't do anything about this on the client side, we should open a ticket in the news aggregator repo instead
