### ISSUE TITLE
If Only Empty Tab is Present, Brave Should Open External Links Within That Same Tab Rather Than Creating a New Tab

### ISSUE THREAD

**Issue by mdrockwell** [brave/brave-ios#6554]
### Description: 
If you close all of your open tabs, Brave automatically opens an empty tab. If you then open an external link, the app should use the empty tab to display it instead of creating a new tab.

### Steps to Reproduce 
1. Close all open tabs in Brave — the browser automatically opens the new tab page.
2. Open a link in Brave from another app.

**Actual result:**
You will end up with two tabs open in Brave:

- The empty new tab that was created after closing all open tabs.
- The webpage that was opened from the external link.

**Expected result:**
Since the only open tab is the new tab page, the link should open within that same tab.

**Reproduces how often:**
Easily reproducible, happens every time.

**Brave Version:** 
v1.45.1 (22.11.17.19)

**Device details:** 
iPhone 13 Pro (iOS 16.1.1)

**Comment by Uni-verse** [comment]
Verified on `iPhone 12`, `iOS 16.1` & `iPad (9th Gen)`, `iPadOS 15.6.1` using version `1.48 (23.2.16.18)`

- Ensured that if an empty tab is present, brave will open external links in the same tab

Example | Example
-|-
![IMG_0132](https://user-images.githubusercontent.com/17885425/219525830-ba884266-a579-41b8-8200-0e5ea93ee1bf.PNG) | ![IMG_0134 2](https://user-images.githubusercontent.com/17885425/219525838-21c0d143-c948-4fe2-9027-1e3fd91ac9e8.PNG)
