### ISSUE TITLE
News displays channel source even if source is explicitly hidden

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6559]
### Description: 

If you hide a source via the feed long-press gesture it will still appear in the feed if that source exists in a channel

### Steps to Reproduce 
  1. Long press feed item and choose to hide content from that source
  2. Reload feed

**Actual result:**
Items from that source still appear in the feed

**Expected result:**
Items from that source should not appear in the feed

**Comment by Uni-verse** [comment]
Verified on `1.46 (22.12.7.14)` using the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPad - iOS 16.x

- Verified hiding content in feed using long press gesture will unfollow on channels.
- Verified hiding content in feed and updating feed will not show that source anymore.
- Verified user is able to re-enable that source and articles will be displayed in the news feed.

Following Page (before hiding) | Popular Source (before hiding) | Context Menu | Hidden Confirmation | Following Page (after hiding) | Popular Source (after hiding)
-|-|-|-|-|-
![IMG_0830](https://user-images.githubusercontent.com/17885425/206246422-13a80f07-2bbc-4649-b256-d412fa379ea3.PNG) | ![IMG_0831](https://user-images.githubusercontent.com/17885425/206246431-8d97638f-b3cb-47f6-93e9-826392c14028.PNG) | ![IMG_0832](https://user-images.githubusercontent.com/17885425/206246439-3896bd8f-6781-40f9-9a1c-23b591140cef.PNG) | ![IMG_0833](https://user-images.githubusercontent.com/17885425/206246455-4333af01-2422-4365-958a-bbbb7e3c2d0c.PNG) | ![IMG_0834](https://user-images.githubusercontent.com/17885425/206246466-f3fa38f2-4a8b-4e37-8348-a622464c67f4.PNG) | ![IMG_0835](https://user-images.githubusercontent.com/17885425/206246475-1ea0c4bf-3fa2-4d59-aa79-16a6a524cb74.PNG)

Example | Example | Example | Example
-|-|-|-
![IMG_0194 2](https://user-images.githubusercontent.com/17885425/206247581-60d5016f-8bde-4bfc-913a-214fe4fda11b.PNG) | ![IMG_0195](https://user-images.githubusercontent.com/17885425/206247594-8c2e5c2f-9db0-4cc7-82f1-ed6ae241b827.PNG) | ![IMG_0196](https://user-images.githubusercontent.com/17885425/206247600-61f03319-6aa1-44eb-9a43-021f942e280b.PNG) | ![IMG_0197](https://user-images.githubusercontent.com/17885425/206247604-e40b0965-bc78-4c1a-b81e-c1f6b6995a17.PNG)
