### ISSUE TITLE
Add content blocker compile checks to fastlane test lane

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#656]
Use [does-it-compile.swift](https://github.com/brave/ab2cb/blob/script-fixes/does-it-compile.swift) to determine if all lists shipped in the app compile

**Comment by iccub** [comment]
Seems to be fixed by https://github.com/brave/brave-ios/commit/e8314a24799c70a9cdb8861d8b1e33edf4ef75c0

Please note that regional lists are not checked by it because they are not bundled, they are downloaded at app launch
