### ISSUE TITLE
News feed long press menu shows button to show source instead of hide

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6560]
### Description: 

When you long press an item in the feed the action at the bottom is to "allow content from {source}" instead of hide. It should show hide by default and only show the opposite if you've recently hidden a source in the current generated feed

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.7.14)` on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.x
iPads iPadOS 16.x, 15.x

- Verified long press context menu will show hide source

<img width="500" alt="0" src="https://user-images.githubusercontent.com/17885425/206295031-c6a00846-e075-482d-9476-578528ce3e90.PNG">
