### ISSUE TITLE
Sign button is not shown fully 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#6567]
### Description: 
Sign button is not shown fully 

### Steps to Reproduce 
  1. Connect to Solana Dapp
  2. Sign transaction
  3. Click on confirm button
  4. Sign message on button is not shown fully

**Actual result:** 
![image](https://user-images.githubusercontent.com/17010094/205979614-c18dd5b6-1e6b-41ed-b33c-4505c59a0706.png)

**Expected result:**
Show Sign message on the button

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.46 (22.12.6.11)

**Device details:** 
iPhone 7+ (iOS 14.8.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc; @nuo-xu @StephenHeaps

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46 (22.12.7.22)
- Verified steps from [ #6581](https://github.com/brave/brave-ios/pull/6581)
- Verified `Cancel` button has `X` and is aligned with other cancel button
- Verified `Sign` text is not truncated

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (16.2)
-- | -- | -- 
<img width=300 src=https://user-images.githubusercontent.com/17010094/206526361-ebbcabe3-2a2d-4f78-a022-1aa06f22ab63.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/206526429-a69647f3-f08d-4442-a779-0b48c3d70b2d.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/206527428-fcbdf6f7-eefa-43c8-814f-9a0489211bba.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/206526330-8344abf3-d702-4f7d-adc7-1843a9ad5a83.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/206526458-7d668a84-b1bc-403c-9dfa-e68997e8d75b.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/206527455-b94e0788-ab70-40a5-8d7d-79d027ad0fde.png>

**Comment by StephenHeaps** [comment]
I've updated the milestone as Solana Dapps has been moved to v1.47 release for iOS. This ticket has been verified but remains behind a feature flag.
