### ISSUE TITLE
Dapp Connect button state issue

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#6570]
### Description: 
Dapp Connect button state issue

### Steps to Reproduce 
**Scenario 1**
  1. Connect to Solana Dapp
  2. Open Panel and click on connected button
  3. Click on Revoke and close the connection page
  4. Continues to show Connected until you close and reopen the panel and then hides

**Scenario 2**
  1. Connect to Solana Dapp
  2. Open Panel and click on connected button
  3. Change network to Ethereum
  4. Change network back to Solana 
  5. Continues to show Disconnected until you close and reopen the panel it then updates to connected

**Actual result:** 
Dapp Connect button state are not acurate

**Expected result:**
Should show correct state

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.46 (22.12.6.11)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46 (22.12.7.22)
- Verified steps from issue description
- Verified button connect state is shown correctly

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (16.2)
-- | -- | -- 
<video src=https://user-images.githubusercontent.com/17010094/206538171-3464ec9b-1aa8-47f7-ab6d-5cb0a704d07e.MP4> | <video src=https://user-images.githubusercontent.com/17010094/206538190-ea5f1a1c-2b0f-49d2-b85d-a6d633bc6353.MP4> | <video src=https://user-images.githubusercontent.com/17010094/206538145-1448c227-d56c-41f8-a934-bd2998f945bc.MP4>

**Comment by StephenHeaps** [comment]
I've updated the milestone as Solana Dapps has been moved to v1.47 release for iOS. This ticket has been verified but remains behind a feature flag.
