### ISSUE TITLE
Ethereum network shows up before changing it to Solana on Sign transaction confirmation screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#6572]
### Description: 
Ethereum network shows up before changing it to Solana on Sign transaction confirmation screen

### Steps to Reproduce 
  1. Connect to Solana Dapp
  2. Click on Sign transaction
  3. Panel opens shows Ethereum network first before updating it to Solana

**Actual result:** 
Ethereum network shows up before changing it to Solana on Sign transaction confirmation screen

**Expected result:**
Should not show Ethereum network before changing to Solana. Should directly show Solana network

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.46 (22.12.6.11)

**Device details:** 
iPhone XR (iOS 15.7.1)

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by StephenHeaps** [comment]
This should be resolved with https://github.com/brave/brave-ios/pull/6620. As part of that fix, we are no longer displaying any network until the correct network is fetched. Previously Ethereum Mainnet could be shown for the initial network.

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-ios/issues/6618#issuecomment-1398032343
