### ISSUE TITLE
Show blank page instead of NTP/site preview when switching apps

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-ios#6577]
### Description: 
When switching apps on iOS, Brave should show a blank screen (or innocuous icon/image, etc) when browser is in Private mode and switching between apps, rather than showing the NTP, address bar, icons or any other information currently contained on the browser. 

![image](https://user-images.githubusercontent.com/3299098/206014085-f1b42e4a-60e2-485f-80b0-a50224dfee16.png)

Internal conversation:
https://bravesoftware.slack.com/archives/C06UXF3KJ/p1670356534286049
Community request for the feature:
https://community.brave.com/t/exiting-switching-tab-will-not-hide/448076/6

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.0]
Brave build: 1.58 (23.9.19.14)
BraveCore: 1.58.124 (117.0.5938.62)
```

Filed follow-up issue #8095
---------------------------
<details>
<summary> Standard Tab </summary>

**STEPS:**
1. Launch Brave 
2. Open `NTP` in `Standard Tab` mode
3. Use the app switch gesture to see all opened apps > Verify
4. Return to Brave > Open any website
5. Use the app switch gesture to see all opened apps > Verify

**ACTUAL RESULTS:**
- Verified that all info is shown for `NTP` in `Standard Tab` mode when switching apps
- Verified that all info is shown for websites in `Standard Tab` mode when switching apps
- Verified the same behavior when Brave is in `foreground` and `background`

---------------------------

|NTP|YT|Wikipedia|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/5fcf1017-2273-4fff-8fdd-c62f395ceb27) | ![2](https://github.com/brave/brave-ios/assets/128532965/328be725-8270-4a33-b1ba-f9858fd804da) | ![3](https://github.com/brave/brave-ios/assets/128532965/db64e613-18c8-4443-b3e3-e9debbc307f5) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/64bc184a-e98c-4107-a99b-af0be1013918) | ![2](https://github.com/brave/brave-ios/assets/128532965/764f21dc-fc21-4e69-9216-78cba4060df9) | ![3](https://github.com/brave/brave-ios/assets/128532965/5b3ef385-f512-41df-b5ff-b7ba576c27e2) |
</details>

<details>
<summary> Private Tab </summary>

**STEPS:**
1. Launch Brave 
2. Open `NTP` in `Private Tab` mode
3. Use the app switch gesture to see all opened apps > Verify
4. Return to Brave > Open any website
5. Use the app switch gesture to see all opened apps > Verify
6. Tap `tab switch` button > Use the app switch gesture to see all opened apps > Verify
7.  Open `NTP` > Tap `Search` button  > Use the app switch gesture to see all opened apps > Verify

**ACTUAL RESULTS:**
- Verified that a blank screen is shown for `NTP` in `Private Tab` mode when switching apps
- Verified that a blank screen is shown for websites in `Private Tab` mode when switching apps
- Verified the same behavior when Brave is in `foreground` and `background`

---------------------------

|NTP|Wikipedia|YT|Tabs switch|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/49d1a62c-65cb-44a5-8ae9-18bc78eb46b1) | ![2](https://github.com/brave/brave-ios/assets/128532965/254a23bf-3202-4a67-a485-067d84ea7a3a) | ![3](https://github.com/brave/brave-ios/assets/128532965/b5dc466d-5c1e-46be-92ac-f88144b05832) | ![4](https://github.com/brave/brave-ios/assets/128532965/8d1a3a0b-7fab-4655-8d75-4a1e6ed7e706) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/59738f5e-4925-4c02-a7c3-fc3e0f7cc683) | ![2](https://github.com/brave/brave-ios/assets/128532965/97e69c19-6305-44bb-aefc-68f68b4d5636) | ![3](https://github.com/brave/brave-ios/assets/128532965/5aeea8be-7127-4027-9b88-a5a909aebc01) | ![4](https://github.com/brave/brave-ios/assets/128532965/1a4f8692-480a-4227-96f0-435a52bb3424) |
</details>
