### ISSUE TITLE
Incorrect balance can be shown in Wallet Panel

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6584]
### Description: 

The Wallet Panel might show the mainnet balance when a test network is selected after multichain updates.

### Steps to Reproduce 
  1. Use Solana account with different balance on Mainnet than Testnet / Devnet
  2. Open a Solana Dapp, ex `https://pwgoom.csb.app/`
  3. Tap wallet icon
  4. Change network to Solana Testnet / Devnet
  5. Observe Mainnet balance is still displayed
  6. Change network to Solana Mainnet
  7. Observe Mainnet balance is still displayed

**Actual result:** 

Mainnet balance is always displayed

https://user-images.githubusercontent.com/5314553/206040764-b9d7dcb1-2f3d-42e1-ae5a-f472f653fe01.mov

**Expected result:**

The balance of the native asset on the currently selected network should be displayed

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

Bug is caused by fetching the first asset matching the network symbol without verifying the `chainId` so Mainnet balance will be shown on Wallet panel when either test network is selected.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.7.1 running 1.46 (22.12.7.22)
- Verified steps from issue description and [#6585](https://github.com/brave/brave-ios/pull/6585)
- Verified balance updates correctly when network is changed 

https://user-images.githubusercontent.com/17010094/206727758-2fe9c28c-6cae-4be9-9749-994dcd4b8301.MP4
