### ISSUE TITLE
Unable to redirect Apple Maps URLs to the Maps app properly

### ISSUE THREAD

**Issue by kdenhartog** [brave/brave-ios#6586]
### Description: 

When opening an address from Facebook Messengers native app it opens what appears to be the default browser 

### Steps to Reproduce 
  1. Click an address in Facebook Messenger
  2. Redirects to default browser (Brave) with a URL that includes the address as a query parameter
  3. Click "Allow" when prompted to "Allow link to switch apps" 

**Actual result:** 
Prompts the user permission to redirect to another app over and over again while opening new tabs.

**Expected result:**
Open address in Apple Maps app

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Every time

**Brave Version:** 
v1.45.1 (22.11.17.19)

**Device details:** 
iPhone 14 pro max with iOS version 16.1.1 (20B101)

**Website problems only:**
- did you check with Brave Shields down? Shields are not being injected by default for this tab it appears
- did you check in Safari/Firefox (WkWebView-based browsers)? Works when Safari is set as the default browser, but not when Brave is.

### Additional Information
See video here: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1670368189672649
It has personal information I'd rather not publish publicly, but fine if other Brave team members see it.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 16.1` using version `1.48 (23.2.15.17)`

- Ensured that URLs from messenger app are re-directed to Maps app.

Example | Example
-|-
![IMG_4506](https://user-images.githubusercontent.com/17885425/219435401-8ef27e6c-c01f-4c75-8323-e684eeec94ad.PNG) | ![IMG_4505](https://user-images.githubusercontent.com/17885425/219435393-39f9953d-c3b0-4be4-ae06-457c2526c653.PNG)
