### ISSUE TITLE
Saving a GIF doesn't work (Saves as still image)

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#659]
### Steps to Reproduce 
  1. Go to giphy.com
  2. Long-press a gif, click "Save Image"
  3. Verify in Photos.app that the saved image is not a gif

**Actual result:** A still image is saved
**Expected result:** A gif should be saved
**Reproduces how often:** Easily
**Brave Version:** 1.7.1 Beta (100733d)
**Device details:** iPhone X iOS 12.1.1

Note: Copy Image _does_ copy the gif version and not the still image.

**Comment by cndouglas** [comment]
I implemented a fix for this in the old version: brave/browser-ios#1480. I'll port it over.

**Comment by LaurenWags** [comment]
Verified passed on iPad with 1.7.2 (19.1.15.15)
Verified passed on iPhone SE (iOS 12.1.2) with 1.7.2 (19.1.15.15)
Verification passed on iPhone 6 (iOS 12.1.2) and iPad Pro (iOS 12.1.2) with 1.7.2(19.1.15.15)
Verified passed on iPhone 8 (iOS 12.1.2) with 1.7.2 (19.1.15.15)

**Comment by GeetaSarvadnya** [comment]
Verification passed on iPhone 8 (iOS 12.1.2)
