### ISSUE TITLE
The mtrics `DomainFingerprintSettingsBelowGlobal` and `DomainFingerprintSettingsAboveGlobal` are not reported in local state file until the fingerprinting settings is disabled via shield panel

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#6596]
### Description: 
The mtrics `DomainFingerprintSettingsBelowGlobal` and `DomainFingerprintSettingsAboveGlobal` are not reported in local state file until the fingerprinting settings is disabled via shield panel

### Steps to Reproduce 
  1. Clean profile 1.46 (22.12.7.14)
  2. Open local state file via Settings
  3. The metrics `Brave.Shields.DomainFingerprintSettingsBelowGlobal` and `Brave.Shields.DomainFingerprintSettingsAboveGlobal` are NOT shown in local state file
  5. Open a site and disable "Block Fingerprinting" switch via shield panel
  6. The metrics `Brave.Shields.DomainFingerprintSettingsBelowGlobal = 1` and `Brave.Shields.DomainFingerprintSettingsAboveGlobal = 0` are shown in the local state file as expected
  

**Actual result:** 
The metrics `DomainFingerprintSettingsBelowGlobal` and `DomainFingerprintSettingsAboveGlobal` are not reported in local state file until the fingerprinting settings is disabled via shield panel

**Expected result:**
The metrics `DomainFingerprintSettingsBelowGlobal` and `DomainFingerprintSettingsAboveGlobal` should be reported in local state file without changing the fingerprinting settings

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Easy
**Brave Version:** 

1.46 (22.12.7.14)
**Device details:** 
iPhone 8 - 16.1.1

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @brave/qa-team @kylehickinson @anthonypkeane

**Comment by kylehickinson** [comment]
This will be fixed by https://github.com/brave/brave-ios/pull/6595, please re-test after it is merged and released

**Comment by GeetaSarvadnya** [comment]
Verification **PASSED** on `iPhone 8 version 16.1.1` running `Brave Dev 1.46 (22.12.7.22)`

- Verified the STR from the decsription and ensured `Brave.Shields.DomainFingerprintSettingsBelowGlobal =0` and `Brave.Shields.DomainFingerprintSettingsAboveGlobal =0` are reported in local state file

![IMG_3263](https://user-images.githubusercontent.com/38657976/206418869-fddadb78-fa1d-4d67-a1c2-8f1c111ef27e.PNG)
