### ISSUE TITLE
Dapps panel is not showing any balance

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-ios#6597]
### Description: 

Dapps panel is not showing any balance 

https://user-images.githubusercontent.com/11755381/206243807-c69c8cb4-be63-42c2-9cbc-a0225e0afe51.MP4

**Expected result:**
Should show balance

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.46 (22.12.6.11)

**Device details:** 
16.1.1

cc: @StephenHeaps @nuo-xu (please add appropriate labels, not authorised)

**Comment by StephenHeaps** [comment]
This one should be resolved with https://github.com/brave/brave-ios/issues/6584 which should be available in the next Testflight build. Closing as duplicate, other ticket can be re-opened if issue remains

**Comment by Pavneet-Sing** [comment]
Able to reproduce the above on 1.46 (22.12.6.19)

https://user-images.githubusercontent.com/11755381/206404422-44d45f7b-5efb-4370-87ea-96f21ed121cb.MP4
