### ISSUE TITLE
Cookie Controls

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#66]
Be able to manage / clear cookies. Functionality should be comparable to browser-ios

**Comment by kylehickinson** [comment]
@jhreis Is this the Privacy → `Cookie Control` and `Clear Private Data` setting from browser-ios's setting page?

If it is you can assign this to me since I've already ported over most of it while porting Settings :)

**Comment by jhreis** [comment]
Yup, that's the one. Assigned 😄

**Comment by kylehickinson** [comment]
Added in #61 but wasn't referenced
