### ISSUE TITLE
Enable link vpn button for production builds

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6602]
Related ticket https://github.com/brave/brave-ios/pull/6214

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.8.20)` on the following device(s):

iPhone 12 - iOS 16.x
iPhone XR - iOS 15.x
iPhone X - iOS 14.4.2
iPad - iPadOS 15.x

Test Plan: https://github.com/brave/brave-ios/pull/6613#issue-1485023964

Use Case: `PASSED`
encountered: https://github.com/brave/brave-ios/issues/6628

1. Install 1.46 Release channel build
2. Purchase VPN or restore existing subscription
3. Install VPN profile
4. Open VPN settings
5. Confirm link VPN button is shown

Example | Example | Example | Example
-|-|-|-
![IMG_4202](https://user-images.githubusercontent.com/17885425/206756071-5d9ef801-d496-427c-89b1-d08ae28b83be.PNG) | ![IMG_4203](https://user-images.githubusercontent.com/17885425/206756094-9cc757d5-fe59-43ee-9db4-f594b0f1280c.PNG) | ![IMG_4204](https://user-images.githubusercontent.com/17885425/206756118-a906b2f0-e44e-40da-93b7-edbe8ec06f86.PNG) | ![IMG_4206](https://user-images.githubusercontent.com/17885425/206756266-e19737dc-9637-4a39-ab58-4f2662eb26f4.PNG)
![IMG_0062 2](https://user-images.githubusercontent.com/17885425/206756484-412f844d-866e-4308-8b8a-894711796d7d.PNG) | ![IMG_0063 2](https://user-images.githubusercontent.com/17885425/206756492-76042c5d-8aa5-4a4b-ae6b-19bd0616f25f.PNG) | ![IMG_0064 2](https://user-images.githubusercontent.com/17885425/206756505-11cced0f-172e-4f7b-be70-2ca1b3d70ef6.PNG) | ![IMG_0066 2](https://user-images.githubusercontent.com/17885425/206756513-6bfdbace-231c-4346-8cc2-d6c1d525abed.PNG)
