### ISSUE TITLE
Apply eth_signTransaction UI changes (1.48.x brave-core)

### ISSUE THREAD

**Issue by darkdh** [brave/brave-ios#6606]
core changes https://github.com/brave/brave-core/pull/16247

Requires UI changes for
1. Post confirmation showing transaction is signed but will be sent by DApp like 
<img width="325" alt="Screen Shot 2022-12-01 at 17 53 49" src="https://user-images.githubusercontent.com/11330831/206314442-60ba1f09-568b-4bd0-bb6d-c26bae19e2b7.png">

2. Handle display for new transaction status `Signed`

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 16.3.1 running 1.49 (23.3.3.16)
- Verified test plan from [#6960](https://github.com/brave/brave-ios/pull/6960)
- Verified `Transaction Submitted` message is shown after a transaction is submitted
- Verified clicking on `View on block explorer` in the transaction submitted loads the block explorer 
- Verified once transaction is confirmed the `Transaction Submitted` message shows option to close or receipt

https://user-images.githubusercontent.com/17010094/223385735-8299d9f9-9308-4b66-b86e-84fd616d5462.MP4
