### ISSUE TITLE
Solana NFT shows Token standard as ERC721 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#6608]
### Description: 
Solana NFT shows Token standard as ERC721 

### Steps to Reproduce 
  1. Add a Solana NFT to potfolio
  2. Open NFT details screen
  3. Token standard shows as ERC721 instead of SPL Token

**Actual result:** 
<img width=400 src=https://user-images.githubusercontent.com/17010094/206401096-4aacac72-3132-44d1-852e-86dedb2d850f.png>

**Expected result:**
Should be SPL Token

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.46 (22.12.7.22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.15.19)` on the following device(s):

iPhone 12 - iOS 16.x
iPad - iPadOS 15.x

Using STR from https://github.com/brave/brave-ios/issues/6608#issue-1484073086

- Verified NFT details screen does not show up for Solana NFTs

Example | Example | Example
-|-|-
![IMG_4263](https://user-images.githubusercontent.com/17885425/209387296-ba855506-33fd-4d80-a5c2-b7c1889b8b41.PNG) | ![IMG_4264](https://user-images.githubusercontent.com/17885425/209387305-ac5fb865-66c7-43cd-84f2-1afcb2d03ebe.PNG) | ![IMG_4265](https://user-images.githubusercontent.com/17885425/209387312-5782daa6-683a-4b71-a190-17be2515676a.PNG)
![IMG_0081](https://user-images.githubusercontent.com/17885425/209389907-9dd690ef-7859-49f5-ab08-3e3539a56811.PNG) | ![IMG_0082](https://user-images.githubusercontent.com/17885425/209389915-2bc9ade6-c85e-4bb5-a534-afde0507d45b.PNG) | ![IMG_0083](https://user-images.githubusercontent.com/17885425/209389923-896d10a0-c5e5-47f2-9c83-050618e93ec0.PNG)
