### ISSUE TITLE
Blockchain info is not shown when description and image is shown

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#6609]
### Description: 
Blockchain info is not shown when description and image is shown

### Steps to Reproduce 
  1. Add an NFT token to portfolio
  2. Click on NFT to view details screen
  3. Blockchain details are shown when image/description is not loaded

**Actual result:** 
<img width=300 src=https://user-images.githubusercontent.com/17010094/206431016-b1eea4ea-da0e-4129-ae38-71260aee2cdd.png>

**Expected result:**
<img width=300 src=https://user-images.githubusercontent.com/17010094/206431035-0dd4b0ce-1da9-425d-801c-1c3924edeb9b.png>

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.46 (22.12.7.22)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps 

Note: If the token image is not shown on the portfolio page and if you open NFT details it still shows the Blockchain details (This part is intermittent)
<img width=300 src=https://user-images.githubusercontent.com/17010094/206431473-31d155b8-9043-4704-b79a-cd1346c0dccd.png>

**Comment by nuo-xu** [comment]
this is resolved by https://github.com/brave/brave-ios/pull/6617
