### ISSUE TITLE
Can't open Brave through share tool from feedly

### ISSUE THREAD

**Issue by darkdh** [brave/brave-ios#661]
### Description: 
![image from ios](https://user-images.githubusercontent.com/11330831/50297800-7e93c480-0432-11e9-8478-1587add7dacd.png)
Nothing happened after I click Brave

FWIW, I share the article to Note and I notice it is not pure URL
It contains title like this
`
Facebook doesn't need to sell your data. It has been giving it away free for years. https://www.recode.net/2018/12/19/18148517/facebook-data-partnerships-mark-zuckerberg-new-york-times-privacy
` which is probably the root cause

### Steps to Reproduce 
  1. Share article on feedly
  2. Click Brave

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
1.7.1(18.12.19.01)

**Device details:** 
iPhoneX 12.1.2

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by danishjafri88** [comment]
The text shared has both title and url components mashed into one. This as stated above is not a URL which can be opened. How other browsers handle this:
FF: treats it as a search term and shows dialog to search in ff.
Cake: Opens cake browser
Chrome: No Option is available for chrome(It only takes URL)
Safari: No Option is available for Safari (Only takes URL)
Brave: Nothing Happens

Possible Solutions:
- Only take URLS
- Either open as URL or use the text as search item.
- Show a invalid URL Dialog.

**Comment by tildelowengrimm** [comment]
Couldn't we attempt to parse out the URL?

**Comment by jhreis** [comment]
@tomlowenthal yeah, I think that would be a good approach. Are there any security concerns with just parsing out the string, and randomly attempting to identify a URL? Assume we'd pull just the first / last URL (since a string can have multiple)?

**Comment by tildelowengrimm** [comment]
@jhreis Obvi we should parse the input safely. But I think that just reading a string until we get something looking like a URL and opening the first one we find is probably the expected behavior.

**Comment by jhreis** [comment]
Parse string, and pull just the first possible URL. If no URL is detectable, then fail silently and just open the application (current behavior).

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13 running 1.12(19.9.4.23)
* Verified using the share button and selecting Brave Beta opens the article
* Verified using the share button at the bottom of the article and selecting Brave Beta opens the article
* Verified using either share button on Feedly and opening in Brave with PB mode only turned on loads the article in PB tab
[Feedly.zip](https://github.com/brave/brave-ios/files/3580704/Feedly.zip)

Verification **PASSED** on `iPad Air 3rd Generation` with `iOS 13.1` running `1.12 (19.09.07.03)`:

* ensured that sharing articles from `feedly` via the bottom & top `Share` buttons opens Brave and loads the specified article without any issues
* ensured the above two cases also work when Brave is in PB

Verification **PASSED** on `iPhone 6s+` using `iOS 12.4.1` running `1.12 (19.09.13.06)`:

* ensured that sharing articles from `feedly` via the bottom & top `Share` buttons opens Brave and loads the specified article without any issues
* ensured the above two cases also work when Brave is in PB
