### ISSUE TITLE
Playlist not working fully on DailyMotion

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#6610]
### Description: 
- On DailyMotion, playlist shows videos as already added even if they aren't. As long as one video is added, it believes ALL videos are added, so no new ones can be added.

### Steps to Reproduce 
  1. Visit DailyMotion
  2. Add a video
  3. Try to add ANOTHER video

**Actual result:** 
- URL bar shows the other video is already added
- Currently added video in playlist has an incorrect title

**Expected result:**
- Should allow adding another video

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
- Easily reproduced

**Brave Version:** 
- 1.46+

**Device details:** 
- Any

**Website problems only:**
- Yes. DailyMotion problem

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.13.0)` on the following device(s):

iPhone XR - iOS 15.x
iPhone 12 - iOS 16.x
iPad - iPadOS 16.x

- Ensured new/next videos do not show up as added when adding first videos
- Ensured user is able to add and remove dailymotion videos
- Ensured user is able to add to playlist using the icon in the URL bar, shared menu and long press context menu

Example | Example | Example | Example | Example
 -|-|-|-|-
![IMG_4220](https://user-images.githubusercontent.com/17885425/207454296-c121f4ad-5b7f-49d8-9845-1ae824ad99cd.PNG) | ![IMG_4221](https://user-images.githubusercontent.com/17885425/207454314-665d94bf-6913-4efb-b186-dc13f7caf843.PNG) | ![IMG_4222](https://user-images.githubusercontent.com/17885425/207454325-c7850b96-f754-4eb8-aee2-8deba6aa57e6.PNG) | ![IMG_0861](https://user-images.githubusercontent.com/17885425/207454368-0b2eaa0d-c57a-421c-baa6-eaaaf0e9adbb.PNG) | ![IMG_0862](https://user-images.githubusercontent.com/17885425/207454370-8eeece70-20ab-423d-a5ab-efcd37e0571b.PNG)
