### ISSUE TITLE
Sign Transaction modal can show wrong network

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6618]
### Description: 

Sign Transaction modal is showing the selected network without checking the coin type of the sign transaction request.

### Steps to Reproduce 
  1. Open [Solana test dapp site](https://pwgoom.csb.app/) and connect
  2. Tap 'Sign Transaction' and tap the notification to open the request modal
  3. Swipe to dismiss the Sign Transaction modal
  4. On the Wallet panel, change the selected network to Ethereum Mainnet
  5. Tap the bell icon to re-open the Sign Transaction modal
  6. Observe 'Ethereum Mainnet' displayed in top left, but Solana account shown.

**Actual result:** 
![image (7)](https://user-images.githubusercontent.com/5314553/206533680-f938393f-a62b-42b5-b708-cdc8d70d4b1e.png)

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by StephenHeaps** [comment]
I've updated the milestone as Solana Dapps has been moved to v1.47 release for iOS.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.47 (23.1.18.17)
- Verified steps from [#6620](https://github.com/brave/brave-ios/pull/6620)
- Verified correct network name is shown on transaction approval screen

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (16.2)
-- | -- | -- 
<video src=https://user-images.githubusercontent.com/17010094/213645077-ba61d3e1-c2f1-4e45-bbfe-9c396ecbcdc3.MP4> | <video  src=https://user-images.githubusercontent.com/17010094/213645094-cb90efca-8c36-488d-bbe6-0ba5319b61c2.MP4> | <video  src=https://user-images.githubusercontent.com/17010094/213645059-6af767c7-68e5-42a9-aca5-d2f7e5f83e60.MP4>
