### ISSUE TITLE
Swap transaction not working from Solana Dapps

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6619]
### Description: 
Solana dapps are complaining `assign to readonly property` when users try to swap from a solana dapp with connected brave wallet account

### Steps to Reproduce 
  1. open brave browser
  2. go to jup.ag
  3. connect your brave wallet with this dapp
  4. try to make a swap transaction

**Actual result:** 
error shows up saying `Attempt to assign readonly property`

**Expected result:**
(a notification would show up saying dapp trying to interact with you)
a sign transaction request will show up after you click the notification
click continue to pass the warning state
click sign to complete the transaction.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.7.1 running 1.47 (23.1.18.17)
- Verified steps from issue description
- Verified able to perform a Swap transaction on Solana Dapp

https://user-images.githubusercontent.com/17010094/213673418-a1708173-a242-442d-b28e-f520bfaa16dc.MP4
