### ISSUE TITLE
Research on blocking third party cookies.

### ISSUE THREAD

**Issue by danishjafri88** [brave/brave-ios#662]
WkWebView does not have an API to set cookie policy, rather it a has default policy of preventing cross-site tracking (By blocking access to local storage from third party - cross domain contexts.). 
For more info check #485.

In #660 a js hook was added to block all cookie and localStorage Access which gives the option of blocking all cookies. Another advancement that can be made here is to book all third party cookies not just cross domain one. Some theoretical ways of doing this are:

1. Add Content block list rule of action: `block-cookies` with load-type as `third-party`. This will strip all cookies from a request. On the downside, cookie is still accessible and can be read and sent as any other header.
2. Add logic to the js hook to block any localStorage/Cookie access from third-party context and let other pass.

Another good to have feature would be to have a user setting to allow/disallow localStorage access to websites. Maybe a wrapper or hook over [Storage Access API](https://webkit.org/blog/8124/introducing-storage-access-api/)

### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jumde** [comment]
I just verified that 3p cookies (not localStorage/sessionStorage) is blocked by default on iOS:

1. Cookies set in JS: http://dustiest-limitation.000webhostapp.com/first_party.html
2. Cookies set on server side: http://dustiest-limitation.000webhostapp.com/first_party.php

**Comment by jhreis** [comment]
Related: https://github.com/brave/brave-ios/issues/761
