### ISSUE TITLE
Part of the webpage appears blank after loading completes

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#6623]
### Description: 
Part of the webpage appears blank after loading completes

Possibly related to https://github.com/brave/brave-ios/issues/6615 & https://github.com/brave/brave-ios/pull/6621

### Steps to Reproduce 
Rotate to landscape.
Go to amazon.com
Open any link as a preview (long-press).
Then hit Open in New Tab
Close the tab.
Refresh the page.
Wait 3-5 seconds.
Click on the URL bar.
Submit the search (so the page does a FRESH load, and not load from cache).

**Actual result:** 

Example | Example
-|-
![IMG_0841](https://user-images.githubusercontent.com/17885425/206564870-3e0f2325-755c-47e5-a2bc-a5dcb5e53da7.PNG) | ![IMG_0842](https://user-images.githubusercontent.com/17885425/206564875-bc10632c-a05b-4cd6-adcc-896714c1f519.PNG)

**Expected result:**
Should display page correctly

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent

**Brave Version:** 
1.46.x

**Device details:** 
iPad

**Website problems only:**
- did you check with Brave Shields down? Yes
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Reopened, latest fix did not help

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.13.0)` on the following device(s):

iPhone XR - iOS 15.x
iPhone 12 - iOS 16.x
iPads - iPadOS 16.x, 15.x

Based on STR in https://github.com/brave/brave-ios/issues/6623#issue-1485386427 & https://github.com/brave/brave-ios/issues/6615#issue-1485031124

- Verified no longer reproducible on `1.46 (22.12.13.0)` in landscape or portrait orientation.
- Verified opening link in new tab with `link previews` enabled/disabled.
- Verified switch tab banner appears at the bottom of the page instead of on top.
- Verified tabs are responsive across multiple sites
- Verified using reader mode does not crash the tab (previous use case)

Example | Example
-|-
![IMG_0863](https://user-images.githubusercontent.com/17885425/207459324-09859d95-394f-4cd2-bf93-b195a067386a.PNG) | ![IMG_0864](https://user-images.githubusercontent.com/17885425/207459484-9da93355-7009-4d03-a2df-c8a1cbc4a7a7.PNG)
