### ISSUE TITLE
Add Help Centre link on the settings dropdown on Wallet

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-ios#6626]
### Description: 
Add a link in wallet settings for users to access help centre. See desktop for examples. 

This is the link it should be sent to https://support.brave.com/hc/en-us/categories/360001059151-Brave-Wallet
### Steps to Reproduce 
  1.
  2.
  3.

**Actual result:** 
![Screenshot 2022-12-09 at 14 43 43](https://user-images.githubusercontent.com/12224304/206715669-1c4b9a5c-e32d-4ae7-8523-199fb738ad9d.png)
Maybe we could add it to this dropdown

**Expected result:**

<img width="299" alt="Screenshot 2023-02-14 at 9 22 30 AM" src="https://user-images.githubusercontent.com/5314553/218765667-1964aade-1cc9-4d20-ad8d-207301d9c70c.png">

https://www.figma.com/file/ZK2POu5oNDFtOoz3Xpr9mi/%F0%9F%93%B1-Help-Center?node-id=1701%3A25883&t=r7T7XPSQ5I0j3TVx-4

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.48 (23.2.10.14)
- Verified steps from [#6916](https://github.com/brave/brave-ios/pull/6916)
- Verified `Help Centre` link is shown in context menu and panel menu
- Verified clicking on it loads `https://support.brave.com/hc/en-us/categories/360001059151-Brave-Wallet`

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (16.2)
-- | -- | -- 
<video src=https://user-images.githubusercontent.com/17010094/218398246-3937099e-f976-4e39-ae43-bcaf46ebaa75.MP4> | <video src=https://user-images.githubusercontent.com/17010094/218398192-5c4715f2-33c9-44cd-a03d-e41b9fa286b7.MP4> | <video src=https://user-images.githubusercontent.com/17010094/218398144-b7937cd4-6129-4ba6-bfa0-8ea025488613.MP4>

**Comment by kleantzogu** [comment]
UI: https://www.figma.com/file/ZK2POu5oNDFtOoz3Xpr9mi/%F0%9F%93%B1-Help-Center?node-id=1701%3A25883&t=r7T7XPSQ5I0j3TVx-4

**Comment by StephenHeaps** [comment]
> UI: https://www.figma.com/file/ZK2POu5oNDFtOoz3Xpr9mi/%F0%9F%93%B1-Help-Center?node-id=1701%3A25883&t=r7T7XPSQ5I0j3TVx-4

@kleantzogu We currently have this Help Center row at the bottom similar to desktop, with the lock row separate using larger divider. Should we adjust to match these designs?

![217916046-b6dec573-74b6-49ed-a938-88a0062eb0a9](https://user-images.githubusercontent.com/5314553/218757822-56c874cd-4af1-4ffc-aace-f6d7b8c51c86.png)

**Comment by kleantzogu** [comment]
@StephenHeaps Better match the design since the separator can divide in-wallet and external links _(Help Center in this case)_.

**Comment by StephenHeaps** [comment]
Changed this to QA/No as this was already verified and just the divider position is changing. cc @srirambv
