### ISSUE TITLE
Fix issue with stats of one page bleeding into another page

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#6632]
### Steps to Reproduce 
  1. Ensure ad-block and trackers are enabled
  2. Go to YouTube.com
  3. Go to search.brave.com

**Actual result:** 
Actual tracker count is > 0

**Expected result:**
Blocked tracker count should be 0 (we don't track the user)

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.46

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.13.0)` on the following device(s):

iPhone XR - iOS 15.x
iPhone 12 - iOS 16.x
iPads - iPadOS 16.x

Scenario: 

1. Ensure ad-block and trackers are enabled
2. Go to YouTube.com
3. Go to search.brave.com

- Verified ad tracker blocked count = 0

Example | Example
-|-
![IMG_0873](https://user-images.githubusercontent.com/17885425/207673646-5aa1b70f-1771-49d2-9de7-af6bbc3ca4e0.PNG) | ![IMG_4234](https://user-images.githubusercontent.com/17885425/207673650-9823bfda-8160-4acf-8991-78969d49aa40.PNG)
