### ISSUE TITLE
melin.com does not render correctly

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6633]
### Steps to Reproduce 
  1. Visit melin.com

**Actual result:** 
Page is mostly blank

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Possibly related to https://github.com/brave/brave-ios/issues/6623

**Comment by Uni-verse** [comment]
Verified using version `1.46 (22.12.13.0)` on the following device(s):

iPhone XR - iOS 15.x
iPhone 12 - iOS 16.x
iPhone X - iOS 14.4.2
iPads - iPadOS 16.x, 15.x

- Verified `melin.com` is rendering correctly 
- Verified able to load webpage with `shields` enabled and disabled

Shields ON | Shields OFF
-|-
![IMG_4224](https://user-images.githubusercontent.com/17885425/207463646-585a6856-ed77-4006-a83a-3460503e2029.PNG) | ![IMG_4225](https://user-images.githubusercontent.com/17885425/207463655-f018be50-1fa6-4735-b831-8718c8c984a0.PNG)
![IMG_0866](https://user-images.githubusercontent.com/17885425/207463678-3d8dba40-b239-4eb9-a308-15d7754b84e7.PNG) | ![IMG_0867](https://user-images.githubusercontent.com/17885425/207463684-8e125722-94ab-4d0d-b3d0-4277f70da54d.PNG)
