### ISSUE TITLE
Add SNS support to Brave Wallet on iOS

### ISSUE THREAD

**Issue by bbondy** [brave/brave-ios#6639]
This support is already in brave-core 1.47.x
> .sol SNS address resolution – Users can send tokens to any ASCII based “.sol” address 
> and subdomain subject to applicable restrictions Brave must legally abide by, such as 
> OFAC. 

SNS support in brave-core (https://github.com/brave/brave-browser/issues/27027, https://github.com/brave/brave-browser/issues/26652, https://github.com/brave/brave-browser/issues/25907)

Please do this by the end of Q1. 
cc @nuo-xu @StephenHeaps

**Comment by StephenHeaps** [comment]
This has merged in v1.47, however the feature flag remains disabled by default. A core change would be required to enable for public builds. The PR test plan includes steps for enabling the feature flag in non-public builds for testing.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.47 (23.1.18.17)
- Verified steps from [#6728](https://github.com/brave/brave-ios/pull/6728)
- Verified able to resolve `.sol` domain to address
- Verified when an invalid domain is typed in shows error message
- Verified full address is displayed below the SNS domain after resolving
- Verified correct `Send To` address is used in Transaction Confirmation screen

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (16.2)
-- | -- | -- 
<video src=https://user-images.githubusercontent.com/17010094/213749642-7b2d81b1-baa2-4d74-bccd-d6485e578cf8.MP4> | <video src=https://user-images.githubusercontent.com/17010094/213749755-8c855aa0-b9f2-4b8e-95d5-5e44c03b29fb.MP4> | <video src=https://user-images.githubusercontent.com/17010094/213752758-786d0792-2150-491f-8bb0-0533d9254cff.MP4>
