### ISSUE TITLE
Brave VPN should use WireGuard by default

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#6646]
## Problem Description 
Our current VPN integration (using GuardianConnect library) is using IKEv2 protocol. This can be problematic for some folks who are connected to VPN while on WiFi. The root cause is unknown, but their WiFi connection will drop. Please see https://github.com/brave/brave-ios/issues/6645

## Feature Overview
GuardianConnect has the ability to use WireGuard as the protocol. We'd need to make some changes to our code-base

## Design 
We shouldn't need a design unless we wanted to let the user choose. If we let the user choose, we may want to default to WireGuard.

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.50 (23.4.25.20)`

Using Test Plan in PR - https://github.com/brave/brave-ios/pull/7125#issue-163442612

**Fresh User**

- Ensured purchasing a new VPN subscription is successful
- Ensured that VPN profile is set and connection is established

**Existing Plan**

- Ensured that resetting VPN configuration will set new VPN profile and establish a connection.

Example | Example | Example | Example | Example | Example | Example
-|-|-|-|-|-|-
![IMG_3015 2](https://user-images.githubusercontent.com/17885425/234736575-abd9690a-926a-4171-b8bc-15225ced56fb.PNG) | ![IMG_3016 2](https://user-images.githubusercontent.com/17885425/234736577-4ff652c4-b8da-4a96-a70e-3dc64222d284.PNG) | ![IMG_3017 2](https://user-images.githubusercontent.com/17885425/234736580-d8970875-dce0-47b5-af49-0757b397365f.PNG) | ![IMG_3018 2](https://user-images.githubusercontent.com/17885425/234736592-11ed049c-346c-44b7-ba1c-3fd51daba883.PNG) | ![IMG_3019 2](https://user-images.githubusercontent.com/17885425/234736596-7f6847cc-5f0b-40e6-80d1-26a236d4598e.PNG) | ![IMG_3020 2](https://user-images.githubusercontent.com/17885425/234736597-e685b3cf-69cb-430c-aa5d-f27713ef2df1.PNG) | ![IMG_3023 3](https://user-images.githubusercontent.com/17885425/234736679-2c81aa42-f10e-476b-a6b5-f81d0b613441.PNG)
