### ISSUE TITLE
Frontend iOS support for running DiscoverAssets on page refresh

### ISSUE THREAD

**Issue by nvonpentz** [brave/brave-ios#6652]
Same as https://github.com/brave/brave-browser/issues/26547 but for iOS.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.
- Verified steps from [#6751](https://github.com/brave/brave-ios/pull/6751)
- Verified loading spinner next to asset when fetching asset info
- Verified asset list is shown 
- Encountered [#6929](https://github.com/brave/brave-ios/issues/6929) on iOS 15.7.1

iPhone 7+ (iOS 14.8.1) | iPad Pro (16.2)
-- | -- 
<video src=https://user-images.githubusercontent.com/17010094/218432868-bd083600-8431-4c14-9a3f-dc019780135e.MP4> | <video src=https://user-images.githubusercontent.com/17010094/218432786-4a76ddc5-b58b-429b-b1a0-e64da40ecb7c.MP4>
