### ISSUE TITLE
Wallet: Support Solana NFT metadata 

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6654]
In core 1.48 we will have a new API to fetch solana NFT metadata. We will need to integrate this in order to display Solana NFT image in various format.

**Comment by nuo-xu** [comment]
uplifted to 1.47

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.7.2 running 1.47 (21.1.30.21)
- Verified steps from [#6771](https://github.com/brave/brave-ios/pull/6771)
- Verified able to send Solana NFT to other accounts

![image](https://user-images.githubusercontent.com/17010094/216077563-a339c828-ce7b-414b-9647-6aaa6e4a6231.png)
