### ISSUE TITLE
Brave iOS browser throws TypeError on all pages visited in incognito mode

### ISSUE THREAD

**Issue by rdwallis** [brave/brave-ios#6656]
### Description: 
Brave iOS browser throws `TypeError: undefined is not an object (evaluating 'window.ethereum.selectedAddress = undefined')` on all pages visited in incognito mode

I've created a [test page](https://rdwallis.github.io/rdwallis/BraveBug.html) which appends all thrown errors to the document but I think this occurs on every website visited in incognito mode.

### Steps to Reproduce 
  1. Open Brave Browser in Incognito Mode
  2. Visit https://rdwallis.github.io/rdwallis/BraveBug.html
  3. You will see multiple Js Errors appended to the document

**Actual result:** 
![IMG_8CFC6957AC15-1](https://user-images.githubusercontent.com/534044/208618557-c13001be-96d9-422f-a5c3-7e6582de7184.jpeg)

**Expected result:**
Blank Page with no errors like on Safari

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Every time any page is visited in incognito mode.

**Brave Version:** 
Version 1.45.2 (22.11.29.0)
BraveCore 1.45.134 (107.0.5304.141)
Device iPhone13,1 (iOS 16.2)

**Device details:** 
iPhone 12 mini (iOS 16.2)

**Website problems only:**
- did you check with Brave Shields down?
Yes, problem occurs with Brave Shields up or down
- did you check in Safari/Firefox (WkWebView-based browsers)? 
Yes, problem does not occur

### Additional Information
I think the error is caused by this line of code: 
https://github.com/brave/brave-ios/blob/6bce727178fbf74fa3ae2c1d53abc806727bed72/Client/Frontend/Browser/BrowserViewController/BrowserViewController%2BWallet.swift#L452

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.7.2 running 1.47( 23.2.1.14)
- Verified no errors are shown when visiting `https://brandon-t.github.io/wallet/wallet.html` on both normal and private tabs

Normal Tab | Private tab
-- | --
![image](https://user-images.githubusercontent.com/17010094/216109471-086a170e-bea4-49d4-8e8f-d0c5f2e7ddae.png) | ![image](https://user-images.githubusercontent.com/17010094/216109488-ea2032d1-9be3-4c78-9ee8-e8cae11d2657.png)


NOTE: if the page loads on http it still throws error on normal tabs but not on private tabs

Normal Tab with HTTP | Private Tab with HTTP
-- | --
![image](https://user-images.githubusercontent.com/17010094/216109695-5069a417-d830-41bd-9d03-7a9dd4e160ac.png) | ![image](https://user-images.githubusercontent.com/17010094/216109678-7df988e6-3291-4ba2-a75c-57b3187054a3.png)

**Comment by JFrankfurt** [comment]
encountering this now on a local dapp build, but not in incog.
