### ISSUE TITLE
[hackerone] #473654 - Address Bar Spoofing

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#666]
https://hackerone.com/bugs?report_id=473654

**Comment by diracdeltas** [comment]
removed sec-high since it's classified as medium on h1 (which seems right to me)

**Comment by jumde** [comment]
@diracdeltas - we are using the `sec-high` label to track priority items (slated for release or release +1 ) for brave-ios. I did this to avoid creating another label for security issues, let me know if you'd like me to create a separate label for these issues.

**Comment by diracdeltas** [comment]
@jumde yeah, i would prefer if a separate label were used for that if the security issues are not necessarily high severity

**Comment by diracdeltas** [comment]
no big deal if it's too much work to change the labels though; i don't think we use sec-high much across the organization

**Comment by jumde** [comment]
no issues, updated.

**Comment by jumde** [comment]
fixed: https://github.com/brave/brave-ios/pull/773

**Comment by diracdeltas** [comment]
not sure why this wasn't auto-closed by #773

**Comment by LaurenWags** [comment]
* Verified passed with 1.9 (19.3.9.1) on iPad 5th Gen using the test plan from https://github.com/brave/brave-ios/pull/773
* Verification passed on iPhone 7+ running 1.9 (19.3.9.1)
* Verified passed with 1.9 (19.3.9.1) on iPhone SE using the test plan from https://github.com/brave/brave-ios/pull/773
* Verified passed with 1.9 (19.3.9.1) on iPhone 8 using the test plan from https://github.com/brave/brave-ios/pull/773
* Verification passed on iPhone 6 and iPad Pro running 1.9(19.3.9.1)
* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR.
