### ISSUE TITLE
Playlist :: Items sometimes not being deleted 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6660]
### Description: 
User reported https://appfigures.com/reviews/42132121512LW_ELU2VzLnWDVVkD6uuOWA?lang=en

I ran into this also but I can't reproduce 100% of the time.

### Steps to Reproduce 
  1. Add a video to Playlist (for offline mode)
  2. Upgrade versions of the app
  3. Swipe to remove the video

**Actual result:** 
- it won't delete / be removed

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Brandon-T** [comment]
I believe this bug is fixed now and videos are deleted properly.

**Comment by Uni-verse** [comment]
Verified on `1.62 (24.1.9.23)` using `Phone 12` running `IOS 17.1.1`

- Confirmed issue is not reproducible on upgraded profile after running through STR in https://github.com/brave/brave-ios/issues/6660#issue-1506984330
- Confirmed items in Playlist are deleted successfully using edit mode or swipe. 
- Confirmed deleted items can be re-added Playlist.

Example | Example | Example
-|-|-
![IMG_5560](https://github.com/brave/brave-ios/assets/17885425/48df1b0f-f54f-4993-b90b-af0f01bd9ba5) | ![IMG_5565](https://github.com/brave/brave-ios/assets/17885425/48a2d4a7-115a-4a83-bd53-041def989086) | ![IMG_5566](https://github.com/brave/brave-ios/assets/17885425/5665fb7c-8e08-4119-9921-f82c8dd6f034)
