### ISSUE TITLE
Sync code cut off in Tab sync chain flow [iPad]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#6665]
### Description: 
We recently increased the size of the QR code being displayed to fix an issue with scanning from Android devices. We should adjust the modal so QR code on iPads does not overflow.

### Steps to Reproduce 
  1. Install 1.46.x
  2. Open Tab tray
  3. Switch to Tabs from other devices
  4. Tap `Start a sync chain`
  5. Select `Tablet or Phone` on `Choose Device Type` screen to display the sync code for scanning

**Actual result:** 
![IMG_0927](https://user-images.githubusercontent.com/17885425/209192931-c5b247b4-e05b-4603-9aa4-33eb2433766c.PNG)

**Expected result:**
Sync code should not be cut off

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.46 (22.12.15.19)

**Device details:** 
iPad, iOS 16.x

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iPadOS 16.1` using version `1.47 (23.1.13.18)`

Test Steps: 

1. Install version 1.47
2. Launch app
3. Open tab tray, select segmented tab (tabs from other devices)
4. Tap on `Start a sync chain ->` button
5. In the next screen, select `Start a new Sync Chain`
6. In the Device Type screen, select `Tablet or Phone` to display the QR code
7. Confirm that the modal with the QR code is scrollable and you can join sync chain with other devices
8. Tap `Done`

- Verified user can successfully complete sync chain flow via segmented tab
- Verified that QR code is scanning and user is able to join via scanning or code words
- Verified Code Words tab can be selected to show the recovery phrase
- Verified modal containing QR Code is scrollable
- Verified user is able to create a standalone sync chain
- Verified flow in landscape and portrait orientation

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_0933](https://user-images.githubusercontent.com/17885425/212424212-b5277a8e-46e7-4947-a50a-891aad8b43bb.PNG) | ![IMG_0934](https://user-images.githubusercontent.com/17885425/212424213-a4f20559-fd32-4cb5-96fa-8b9d50125474.PNG) | ![IMG_0935](https://user-images.githubusercontent.com/17885425/212424216-351001dd-caa7-4e4f-a77c-ea4292509f89.PNG) | ![IMG_0936](https://user-images.githubusercontent.com/17885425/212424219-911696e4-eb54-4d90-a348-127f6a9fa72a.jpg) | ![IMG_0937](https://user-images.githubusercontent.com/17885425/212424221-2b6b60dc-e75f-44c1-aad1-27725528c02c.jpg) | ![IMG_0938](https://user-images.githubusercontent.com/17885425/212424223-08bbd4a0-208f-4944-94fa-7341accd13b5.PNG)
![IMG_0939](https://user-images.githubusercontent.com/17885425/212424334-66cb0bdc-92ac-4713-9c19-504a81afc2fb.PNG) | ![IMG_0940](https://user-images.githubusercontent.com/17885425/212424336-22a40833-2fce-411f-8379-3efb26064dc6.PNG) | ![IMG_0941](https://user-images.githubusercontent.com/17885425/212424337-a798eec6-cbd1-4887-8e36-393c2c10a431.jpg) | ![IMG_0942](https://user-images.githubusercontent.com/17885425/212424339-b8e25e14-9d95-40fc-b602-27aeeb4add5f.jpg) | ![IMG_0943](https://user-images.githubusercontent.com/17885425/212424342-89a32d25-e61c-4dbb-9c3f-38d3408409d0.jpg) | ![IMG_0944](https://user-images.githubusercontent.com/17885425/212424343-e68098ee-5daf-4233-b8e9-c9ab2932ca75.PNG)

**Comment by danielo515** [comment]
Why is this closed? I still get the same problem in the latest version available
