### ISSUE TITLE
[hackerone] Apply Chromium's IDN encoding in Shields UI

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-ios#6673]
https://hackerone.com/reports/1819329

**Comment by stoletheminerals** [comment]
In addition to shields we need to apply the same encoding rules (if it's not already applied) in other places where we display domain names (e.g wallet) cc @diracdeltas

**Comment by soner-yuksel** [comment]
@stoletheminerals I will take care of the problem mentioned in Shields Screen. Shields info screen is an edge we missed and other places like (URL Bar, History, Bookmarks, Open Tabs etc) is working properly. I am only not sure about Wallet. cc @Brandon-T 

@StephenHeaps can you check Wallet regarding to this.

**Comment by StephenHeaps** [comment]
@soner-yuksel do we need the fix in Settings -> Brave Shields & Privacy -> Manage Website Data?

For Wallet, we display url origin in a few places that this would need investigated / applied I believe:
- Panels
    - `SuggestedNetworkView`
    - `AddSuggestedTokenView`
    - `EditSiteConnectionView`
    - `NewSiteConnectionView`
    - `EncryptionView`
    - `SignTransactionView`
    - `SignatureRequestView`
- Wallet Settings
    - `DappsSettings` / `SiteConnectionDetailView`
- Dapp notification
    - `WalletConnectionView`
- Transaction confirmation
    - `TransactionConfirmationView` / `TransactionHeader`

**Comment by StephenHeaps** [comment]
Wallet is using `URLOrigin` already which has this fix applied. `BraveWallet.OriginInfo` is also used, [which uses URLOrigin internally](https://github.com/brave/brave-core/blob/4469ba7d168d10b989b1ea0f9ce257e47396414d/components/brave_wallet/common/brave_wallet.mojom#L848).

Examples:
WalletConnectionView|NewSiteConnectionView|EditSiteConnectionView|DappsSettings|SiteConnectionDetailView|SuggestedNetworkView
--|--|--|--|--|--
<img width="488" alt="WalletConnectionView" src="https://user-images.githubusercontent.com/5314553/210427157-64b2bb45-0896-4c53-8230-8fd539eea741.png"> | <img width="488" alt="NewSiteConnectionView" src="https://user-images.githubusercontent.com/5314553/210427173-0db516e2-1444-4850-8924-50db40a3619a.png"> | <img width="488" alt="EditSiteConnectionView" src="https://user-images.githubusercontent.com/5314553/210427636-3cb5848b-c6c4-4fa8-ba32-6322a485eb9b.png"> | <img width="488" alt="DappsSettings" src="https://user-images.githubusercontent.com/5314553/210427207-e366fe8f-c08c-4768-b3bd-d2976acd85b7.png"> | <img width="488" alt="SiteConnectionDetailView" src="https://user-images.githubusercontent.com/5314553/210427214-009d5561-7756-4ba1-9988-9eee8781b0e6.png"> | <img width="488" alt="SuggestedNetworkView" src="https://user-images.githubusercontent.com/5314553/210427224-e42ddfdd-9e24-496f-85db-247ac56dace8.png">

Tested by calling `await window.solana.connect()` /  `window.ethereum.request({"method": "wallet_switchEthereumChain", params: [{"chainId": "0x89"}]})` for `SuggestedNetworkView` (`BraveWallet.OriginInfo`) on `hxxps://www.xn--80ak6aa92e.com` sample site. 

cc @stoletheminerals

**Comment by soner-yuksel** [comment]
With the PR https://github.com/brave/brave-ios/pull/6689 the Shields screen is fixed and showing proper ended URL.

And here are some screenshots from rest of application which is using proper IDN domain

 
![proper check](https://user-images.githubusercontent.com/6643505/210638438-38cb7e9d-7116-4694-a759-375c8b65552c.png)

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 16.2` using version `1.47 (23.1.30.21)`

Test Plan: 

1. Visit hxxps://www.xn--80ak6aa92e.com
2. Open Brave Shield panel from the address bar
3. "[apple.com](http://apple.com/)" SHOULD NOT BE shown in the panel

- Confirmed that `apple.com` is not shown in the panel when loading `hxxps://www.xn--80ak6aa92e.com`

Example | Example
-|-
![IMG_4353](https://user-images.githubusercontent.com/17885425/215899613-78811718-67fd-4b2a-ac19-02878a3d0100.PNG) | ![IMG_4354](https://user-images.githubusercontent.com/17885425/215899615-cf415b6f-5e57-4010-879d-cab652e76de0.PNG)
