### ISSUE TITLE
Error in webView:decidePolicyForNavigationAction when return .cancel

### ISSUE THREAD

**Issue by Elter71** [brave/brave-ios#6674]
### Description: 

Hi, I found problem with webView:decidePolicyForNavigationAction as async method. When the method returns `.cancel` website will still be rendering in the main frame.

It happened only in development in the last release version ([v1.45.2](https://github.com/brave/brave-ios/releases/tag/v1.45.2)) everything is fine.

### How to reproduces: 
 
Overwrite webView:decidePolicyForNavigationAction methods adding return `.cancel` on top of it. (just like on screenshots) 
<img width="1697" alt="Screenshot 2023-01-02 at 18 39 48" src="https://user-images.githubusercontent.com/15349174/210264027-7c681198-df14-42e4-a63a-4082b4aa3469.png">
<img width="1282" alt="Screenshot 2023-01-02 at 18 39 44" src="https://user-images.githubusercontent.com/15349174/210264066-913ac13f-6ef4-4626-8ce9-63a924a9c745.png">

After that check, if all websites will be blocked.

**Comment by Brandon-T** [comment]
Fixed in: https://github.com/brave/brave-ios/pull/6731

**Comment by iccub** [comment]
I'll label as qa/no as QA does not test things with debugger attached
