### ISSUE TITLE
Both reveal and copy password actions should prompt for authentication

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6675]
### Description: 
See https://community.brave.com/t/passwords-stored-in-brave-are-not-private/457682/6

### Steps to Reproduce 
1. Open Brave
2. Open the Settings menu
3. Under “Security”, you will find “Logins & Passwords”
4. Tap on any login.
5. Note that when you click “reveal” on the password, it prompts you for Face ID, Touch ID, or a system password
6. When tapping on “copy”, there is no authentication or verification and it simply copied the password to your clipboard.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` & `iPhone XR` running `iOS 16.2` & `iOS 15.5` respectively using version `1.47 (23.1.17.15)`

Using STR in https://github.com/brave/brave-ios/issues/6675#issue-1517206582

- Verified tapping on copy or reveal in the context menu will prompt user for authentication
- Verified decline Face ID will prompt user for passcode
- Verified user is able to copy password using context menu
- Verified user is able to reveal and hide password using context menu 

Example | Example | Example
-|-|-
![IMG_4289](https://user-images.githubusercontent.com/17885425/213259564-af4fde83-42c1-4dbe-9111-4bad440fbaf0.PNG) | ![IMG_4290](https://user-images.githubusercontent.com/17885425/213259567-1ed57f75-86c7-462f-8d79-7910deca9609.PNG) | ![IMG_0270 3](https://user-images.githubusercontent.com/17885425/213259636-d426a1a9-9f4c-45af-a449-2943c960ae88.PNG)
