### ISSUE TITLE
Brave News card generation is not respecting score/sorting 

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6677]
### Description: 

Brave News cards are being rendered in the incorrect order

### Steps to Reproduce 
  1. Launch the app, enable news, etc.
  2. Notice the cards may not be new
  3. Kill app & relaunch
  4.  Notice cards are not even in the same order as before

### Expected result:
The card generation should be consistent within the cached lifetime of the feed

### Brave Version: 1.46

**Comment by kjozwiak** [comment]
Reproduced the original issue on `iPhone 11` running `iOS 16.2` with `1.46 (22.12.15.19)` using the STR/Cases outlined via https://github.com/brave/brave-ios/issues/6677#issue-1517685434 as per the following:

https://user-images.githubusercontent.com/2602313/210934119-1d1282e8-23d3-410e-ab27-863c66b1f96e.mp4

Notice that some of the articles are several hours/days old but are still appearing at the top of the news feed. Restarting the application also retrieves a new list of articles every single time and the first once is randomly selected with various timestamps.

------------------------

Verification **PASSED** on `iPhone 11` running `iOS 16.2` using the `1.46.1 (23.1.5.18)` as per the following:

* ensured that the most recent articles are appearing at the top of the feed
* ensured that restarting the browser doesn't regenerate/populate the feed in a random order
* ensured that you can swipe through the feed without any issues/noticeable performance issues
* ensured that the current position of the feed is saved when switching/returning back to the NTP

https://user-images.githubusercontent.com/2602313/210935384-75954afa-a05a-423e-bec0-5c3200436241.mp4

------------------------

Verification **PASSED** on `iPad Air (3rd Gen)` running `iOS 16.2` using the `1.46.1 (23.1.5.18)` as per the following:

* ensured that the most recent articles are appearing at the top of the feed
* ensured that restarting the browser doesn't regenerate/populate the feed in a random order
* ensured that you can swipe through the feed without any issues/noticeable performance issues
* ensured that the current position of the feed is saved when switching/returning back to the NTP

Example of the above working on `iPad` -- >https://youtu.be/MxX1Ya-B-kY
