### ISSUE TITLE
Playlist: Add an option for playback speed to 2.5x

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6682]
### Description: 
https://twitter.com/vac93302099/status/1608950353764175872?s=20&t=h_jqc-7IWDUd4RNfelvq2w

Please add an option for playback speed to 2.5x

cc @anatolydsgn

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` & `iPad (9th Gen)` running `iOS 15.6.1` using version `1.50 (23.4.14.17)`

- Ensured 2.5x playback option is added in playlist.
- Ensured next video will automatically play at 2.5x speed when this option is selected.
- Ensured playlist existing buttons and gesture functionality works as expected.
- Ensured that 2.5x playback option is available in full screen also in pip.
- Ensured 2.5x works when app is in the background or lock screen is enabled.
- Ensured 2.5x playback option is working while playing audio
- Ensured 2.5x playback works on existing videos with upgraded profile

Encountered: https://github.com/brave/brave-ios/issues/7256, https://github.com/brave/brave-ios/issues/7258

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_2963](https://user-images.githubusercontent.com/17885425/232129180-7520b6ac-62b1-4723-8bc6-89678d97c61f.PNG) | ![IMG_2964](https://user-images.githubusercontent.com/17885425/232129185-f959d058-d55d-4f81-a457-aa40dad01acb.PNG) | ![IMG_0214 3](https://user-images.githubusercontent.com/17885425/232133900-1b162d6e-7421-4dc1-83ea-e39b577d998a.PNG) | ![IMG_0215 2](https://user-images.githubusercontent.com/17885425/232142848-9ec28f17-b1fc-4ecc-89f7-baaa7f663eaa.PNG) | ![IMG_2966 2](https://user-images.githubusercontent.com/17885425/232142212-cd096e04-21b0-4e00-8e7a-bc50c4f06fbf.PNG)
