### ISSUE TITLE
Wallet: Remove wyre from on-ramp options

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6683]
Wyre is one of the on-ramp options for user to purchase assets. Since Wyre will shut down their service soon, we need to prepare to clean the on ramp options by removing wyre.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.46.1 (23.1.5.18)
- Verified steps from [#6685](https://github.com/brave/brave-ios/pull/6685)
- Verified `Wyre` is not shown as a provider in Buy screen for various tokens
- Verified on both clean install and upgrade

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (16.2)
-- | -- | -- 
<video src=https://user-images.githubusercontent.com/17010094/210999013-33aa83ca-7c22-41a5-8b0f-b1bc73f1adcb.MP4> | <video src=https://user-images.githubusercontent.com/17010094/210999054-03d650f4-e334-4929-bc10-5f4bb8525438.MP4> | <video src=https://user-images.githubusercontent.com/17010094/210999415-ebd22cad-dcb8-47c2-9a60-9bd1d51cd722.MP4>
