### ISSUE TITLE
Search favicon missing in address bar

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#6684]
### Description: 
Search favicon missing in address bar

### Steps to Reproduce 
  1. Install 1.46
  2. Tap on address bar
  3. Enter a search term

### Actual result: 
Missing search icon

<img width="400" alt="1" src="https://user-images.githubusercontent.com/17885425/210598924-a1a0ce7b-280b-4e80-b41b-a17fe0005e0a.PNG">

### Expected result:
Search icon in address bar

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

### Brave Version: 
1.44+

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
iPhone

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
@Uni-verse Can you clarify what icon is missing and what is expected? I see 2 search icons in the screenshot: next to the search term at the top, and one in the quick-search, is there supposed to be a different one?  Here's a screenshot from 1.45.2: 
![IMG_49A9253F84F9-1](https://user-images.githubusercontent.com/529104/216657282-64035277-b35d-48b7-b80f-353e241d9100.jpeg)

**Comment by Uni-verse** [comment]
> @Uni-verse Can you clarify what icon is missing and what is expected? I see 2 search icons in the screenshot: next to the search term at the top, and one in the quick-search, is there supposed to be a different one? Here's a screenshot from 1.45.2: ![IMG_49A9253F84F9-1](https://user-images.githubusercontent.com/529104/216657282-64035277-b35d-48b7-b80f-353e241d9100.jpeg)

@kylehickinson Perhaps its invalid - maybe i missed something when creating the issue. I should have added a little more context in the issue as I cant recall now what exactly i was referring to. I see the version is 1.44+, perhaps something in 1.43 looked different, I'll double check but in the meantime we can close as invalid.
