### ISSUE TITLE
[hackerone] don't show `sms/tel` dialog for non-active tabs

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-ios#6687]
https://hackerone.com/reports/1819652

**Comment by soner-yuksel** [comment]
Yeah I believe If we check the external url host is same with the url host that send this action, we can determine if this is valid or not.

@stoletheminerals What should be our solution here ? Not trigger the tel/sms action or show some additional info on the pop-up ?

**Comment by stoletheminerals** [comment]
@soner-yuksel we should definitely not trigger a pop-up if the tab is not-active. Having additional info in the dialog would be great though, similar to a JS pop-up:
<img width="436" alt="image" src="https://user-images.githubusercontent.com/10810135/210653643-330bbc1a-fdb0-4990-aeb1-820a5a92c2ec.png">

**Comment by soner-yuksel** [comment]
Sounds good

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 16.2` using version `1.47 (23.1.30.21)`

Based on Test Plan in https://github.com/brave/brave-ios/pull/6704#issue-1521075431

**Test 1:**

1. Visit hxxps://csrf.jp/brave/sms.php
2. Tap "Click Me" button
3. [google.com](http://google.com/) is opened in the new tab
4. Confirmation dialog for sms: link should not be shown on [google.com](http://google.com/)

Example | Example
-|-
![IMG_4348](https://user-images.githubusercontent.com/17885425/215898950-d4a11b55-b68a-400f-82e8-801e3a7ede7f.PNG) | ![IMG_4350](https://user-images.githubusercontent.com/17885425/215898968-7dbbe0fc-9b13-4394-93ca-c84752a57021.PNG)


**Test 2:**

1. Visit a website with a call to action like a business on [google](https://www.google.com/search?q=carpet&source=hp&ei=cOy1Y9qyEeXQkPIP64SFuAU&oq=carpet&gs_lcp=ChFtb2JpbGUtZ3dzLXdpei1ocBADMggIABCABBCxAzILCAAQgAQQsQMQgwEyBQgAEIAEMgUIABCABDILCC4QgAQQsQMQ1AIyBAgAEAMyCAgAEIAEEMkDMgUIABCSAzoOCAAQjwEQ6gIQjAMQ5QI6EQguEIAEELEDEIMBEMcBENEDOgsILhCABBCxAxCDAToICAAQsQMQgwE6DgguEIAEELEDEIMBENQCOggILhCABBDUAjoUCC4QgAQQsQMQgwEQxwEQ0QMQ1AI6DgguEIAEELEDEMcBENEDOgsIABCABBDJAxCLAzoICAAQkgMQiwM6DgguELEDEIMBEMcBENEDOgsILhCABBDHARDRAzoOCC4QgwEQ1AIQsQMQgAQ6EQguEIAEELEDEIMBEMcBEK8BOg4ILhCABBDJAxDHARCvAToICC4QgAQQsQM6CAguELEDEIMBUIkSWMhlYJlsaAhwAHgAgAGVAYgBowuSAQM0LjmYAQCgAQGwAQ-4AQI&sclient=mobile-gws-wiz-hp&dlnr=1&sei=hOy1Y-F-5KWq2w_mx6DIBQ#dlnr=1&trex=m_t:lcl_akp,rc_f:rln,rc_ludocids:15437203984229734589,ru_gwp:0%252C7,ru_lqi:CgZjYXJwZXQxfRUaAAAAAABIh87qoeeAgIAIWhIQABgAIgZjYXJwZXQqBAgDEACSAQ5mbG9vcmluZ19zdG9yZZoBJENoZERTVWhOTUc5blMwVkpRMEZuU1VSWE9YWkxSSFZSUlJBQqoBDhABKgoiBmNhcnBldCgA,ru_phdesc:M3Ayh4oddxI,trex_id:N7qfbb&lpg=cid:CgIgAQ%3D%3D)
2. Press call button
3. Check new dialog includes website

<img width="500" alt="0" src="https://user-images.githubusercontent.com/17885425/215897759-52b73c17-2af4-41af-acc9-d7f78508ccb3.PNG">
