### ISSUE TITLE
Wallet: User Mint Address for Solana NFT

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6707]
iOS version of [brave/brave-browser/issues/27664](https://github.com/brave/brave-browser/issues/27664)

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 16.2 running 1.47 (23.1.30.21)
- Verified Solana NFT uses Mint address 

Add NFT screen | NFT details screen
-- | --
![image](https://user-images.githubusercontent.com/17010094/216012511-416b1462-4313-4b3a-8943-fb8b194abfab.png) | ![image](https://user-images.githubusercontent.com/17010094/216012546-86ffc9f2-9e8a-406c-8a4e-2b475662eed6.png)
