### ISSUE TITLE
Brave news taking long time to load / getting stuck on spinner [iOS < 14.5]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#6713]
### Description: 
This seems to be intermittent when relaunching app/toggling brave news off/on.  

### Steps to Reproduce 
  1. Clean install 1.46.1 on iOS device running version < 14.5
  2. Enable brave news from settings and immediately add custom rss feed using the search field (`dappradar.com/blog` was used)
  3. Toggling brave news switch off and then back on again
  4. Check the news feed to make its loading
  5. Now, relaunch browser
  6. Check the news feed to make sure its loading 

### Actual result: 
Gets stuck on spinner animation/takes long time to load (1-2 mins)

https://user-images.githubusercontent.com/17885425/211077089-11228ce4-cfda-4a29-99b3-c4b744c47f57.mov

### Expected result:
Feed should load/update

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Intermittent

### Brave Version: 
1.46.1 (23.1.5.18)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
iPhone X - iOS 14.4.2

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
please retest

**Comment by Uni-verse** [comment]
Not reproducible using version `1.47 (23.1.30.21)` on `iPhone X` running `iOS 14.4.2`

Using STR in https://github.com/brave/brave-ios/issues/6713#issue-1522993069

- Confirmed that news feed is loaded fine when added custom rss, relaunching browser and toggling the news switch

Example | Example
-|-
![IMG_2840](https://user-images.githubusercontent.com/17885425/215905015-7a2f41ef-1f6d-4c83-a8f2-fc176b220233.PNG) | ![IMG_2841](https://user-images.githubusercontent.com/17885425/215905020-ee19fa03-e29a-4961-83c3-ed629b3bdfa0.PNG)
