### ISSUE TITLE
Search field missing when enabling brave news from settings

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#6714]
### Description: 
Search field missing when enabling brave news from settings

Not a regression, can be reproduced on 1.46

### Steps to Reproduce 
  1. install 1.46.x
  2. Launch app, navigate to news settings in 3 dot menu
  3. Enable brave news
  4. Confirm search field is missing
  5. Go back to main menu and come back to brave news settings page
  6. Confirm search field is now shown

### Actual result: 

https://user-images.githubusercontent.com/17885425/211079367-2a66d09b-d00a-4583-9a35-63aa9e27ec22.MP4

### Expected result:
Should display the search field when enabling brave news

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

### Brave Version: 
1.46, 1.46.1

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
iOS 15, 16

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
@Uni-verse it's actually there, you just have to pull down… its a strange iOS bug after adding the search bar on the navigation bar

**Comment by Uni-verse** [comment]
Verified on `iPhone XR` running `iOS 15.5` using version `1.47 (23.1.17.15)`

**Clean Profile**

- Verified search field is showing when enabling news from settings menu

Example | Example
-|-
![IMG_0256](https://user-images.githubusercontent.com/17885425/213209634-8ed8397b-1db9-4b93-b9c6-9c1ce6db928c.PNG) | ![IMG_0257 2](https://user-images.githubusercontent.com/17885425/213209644-bffff6e9-0999-433d-be02-e8b25b20ddd4.PNG)


**Upgraded Profile**

- Verified search field is showing when enabling news from settings menu on upgraded profile

1. Install 1.46.x
2. Upgrade to 1.47.x
3. Opt into Brave News from settings menu

Example | Example
-|-
![IMG_0258 2](https://user-images.githubusercontent.com/17885425/213209673-b4e34c23-8b67-4cc0-bb57-720de5065bec.PNG) | ![IMG_0259 2](https://user-images.githubusercontent.com/17885425/213209675-e754648f-07ee-4fa3-b6d4-670e459c754a.PNG)
