### ISSUE TITLE
Brave iOS preloads podcast episodes without user interaction - inflates industry download stats

### ISSUE THREAD

**Issue by johnspurlock** [brave/brave-ios#6715]
### Description: 
Podcast hosting companies always use [`<audio preload="none">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#attr-preload) on their embedded players, so as not to prefetch/download any episode that a listener does not explicitly play.  This is due to the way open podcasting works, where the industry still uses downloads as the only proxy for listens that is available on the server side.

Brave, however, seems to ignore this attribute in some cases and prefetches the audio on page load, with no user playback intent.  This inflates download stats, and therefore can affect what shows charge to their advertisers.

Note it does not seem to happen on every web player, just a subset, but even these players do not have the same problem on other iOS browsers - it seems specific to Brave.

My hunch is that it has something to due with the [Brave Playlist](https://brave.com/playlist/) feature - as the requests are not sent with the Brave iOS user agent, rather the generic "AppleCoreMedia" user-agent, a sure sign that an app is using AVPlayer/AVURLAsset without changing the default user-agent (which you should also do! [example here](https://github.com/Automattic/pocket-casts-ios/blob/trunk/podcasts/PlaybackItem.swift))

Is there a way to disable the Playlist feature on iOS to validate this theory?

This is a pretty big deal as it affects $$$ in the podcast world, and as a long time user of Brave I would hate to see Brave singled out as a bad actor here.

Thanks!

### Steps to Reproduce 
  1.  Use a client proxy like [Charles](https://www.charlesproxy.com/)
  2. Navigate to one of the following known problematic urls:
      - https://buzzcast.buzzsprout.com/231452/11989348-podcasting-trends-that-should-stay-in-2022
      - https://theunnoticed.cc/
      - https://anchor.fm/potd

### Actual result:
  Audio is fetched!

### Expected result:
  No audio is fetched

### Reproduces how often:
  Every time

**Comment by johnspurlock** [comment]
Thanks for addressing this so quickly!

Any idea when 1.47 will be pushed to the app store?  Just ballpark: this week, next week etc

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 16.2` using version `1.47 (23.2.1.14)`

Based on STR in https://github.com/brave/brave-ios/issues/6715#issue-1524580643

- Confirmed Brave is not fetching audio when navigating to the problematic urls
- Confirmed Brave is no longer calling `audio.buzzsprout`

1.46 | 1.47
-|-
![Screen Shot 2023-02-02 at 12 52 16 PM](https://user-images.githubusercontent.com/17885425/216404450-f35943ec-40db-4eba-946a-5a5f21a4c943.png) | ![Screen Shot 2023-02-02 at 12 55 34 PM](https://user-images.githubusercontent.com/17885425/216404453-2bd94d1d-e1c0-47cf-80fc-8334cb4108eb.png)

**Comment by johnspurlock** [comment]
It's live in the App Store, thanks again!
