### ISSUE TITLE
[Playlist] - Downloading the saving item multiple times even if already saved offline

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#6717]
### Description: 
- Playlist can save an item multiple times even if already saved offline. 
- https://bravesoftware.slack.com/archives/C06UXF3KJ/p1672909649017259

### Steps to Reproduce 
  1. Save an item offline

### Actual result: 
- Saves offline multiple times

### Expected result:
- Should save only once

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily reproduced

### Brave Version: 
- 1.46.x

### Device details: 
- Any

**Comment by Uni-verse** [comment]
Verified on `iPhone 12 Pro` running `iOS 16.2` using version `1.47 (23.2.1.14)`

Based on the test steps in https://github.com/brave/brave-ios/issues/6717#issue-1525780140

- Ensured that when playing videos in playlist they are saved offline only once. 
- Ensured that playlist items are not saved multiple times when relaunching browser

![IMG_4363](https://user-images.githubusercontent.com/17885425/216399543-9834776c-44f6-49bb-9695-fefa96cf0765.PNG)
