### ISSUE TITLE
Brave News cards incorrectly ordered when following both sources and channels

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6721]
### Description: 

If you follow both a source and a channel the ordering of the cards can become incorrect after merging sources followed by implicitly channel and sources followed directly.

### Steps to Reproduce 
  1. Follow sources directly
  2. Follow channels

### Actual result:
Cards will be out of order

### Expected result:
Cards should be in order

### Reproduces how often: 
Easily

### Brave Version: 
1.46+

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iPadOS 16.1` using version `1.47 (23.1.17.15)`

Using STR from https://github.com/brave/brave-ios/issues/6721#issue-1525910111

- Ensured following both sources and channels shows cards in correct order.
- Ensured toggling brave news on/off doesn't change state of lists
- Ensured news sources will load in normal and private tabs 

Example | Example
-|-
![IMG_0946](https://user-images.githubusercontent.com/17885425/213222345-a8836dbf-2909-4d57-8e4d-d5d92a24def8.PNG) | ![IMG_0947](https://user-images.githubusercontent.com/17885425/213222360-3f02b533-143a-41ea-a255-2b329962c364.PNG)
