### ISSUE TITLE
Update search engine default for IN 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6726]
### Description: 
Related: https://github.com/brave/brave-browser/issues/27709

Update search engine default for India:

- India (IN)

**Comment by anthonypkeane** [comment]
@iccub holding this work for the moment. I'll unblock it once we can move forward. It can be implement, but just not released right now.

**Comment by iccub** [comment]
Sounds good. It's trivial to implement so I will wait until decision is done

**Comment by anthonypkeane** [comment]
This can go ahead @iccub  - ideally landing in 1.48 or 1.49. Thanks

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 16.2`& `iPad (9th Gen)`running `iPadOS 15.6.1` using version `1.48 (23.2.10.14)`

**Clean Profile**

- Ensured Brave is default SE in `India` locale
- Ensured searching in the URL box uses search.brave.com

Example | Example
-|-
![IMG_4411](https://user-images.githubusercontent.com/17885425/218167168-cb7e03f8-12b9-43ed-8bd7-5c75a2f314da.PNG) | ![IMG_4418](https://user-images.githubusercontent.com/17885425/218168580-bcfe0690-a6d2-4c08-9cd8-e4f23c828458.PNG)
![IMG_0101 3](https://user-images.githubusercontent.com/17885425/218174882-80f5041c-19e0-427f-b685-7343ff39965d.PNG) | ![IMG_0102 2](https://user-images.githubusercontent.com/17885425/218174905-3ab80bfa-af43-4099-8734-91b41bfa7b7a.PNG)


**Upgraded Profile**

1. Installed 1.47.x 
2. Launched app, confirmed `Google` is default SE on `India` locales
3. Upgraded version to 1.48.x
4. Launched app, confirmed `Google` default SE is retained.

- Ensured SE is retained on existing profile
- Ensured searching in the URL box uses google search

Example | Example
-|-
![IMG_4416](https://user-images.githubusercontent.com/17885425/218170176-88c9bb8f-7d57-4038-a1d4-8aad49a0605a.PNG) | ![IMG_4417](https://user-images.githubusercontent.com/17885425/218170178-77775d78-b1e4-46fa-b432-85c6b2ea8f8f.PNG)
![IMG_0104 2](https://user-images.githubusercontent.com/17885425/218175010-652d55e5-9726-4a3e-a068-241abe769775.PNG) | ![IMG_0105 2](https://user-images.githubusercontent.com/17885425/218175018-35a7ad25-0ade-4c93-a543-5f3929abca40.PNG)
