### ISSUE TITLE
YouTube hoverplay on iPad is incorrectly interacting with WKWebView

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6727]
### Description: 

When scrolling YouTube on my iPad, hoverplay is incorrectly interacting with WKWebView as I scroll the site. 

<img width="1234" alt="Screen Shot 2023-01-09 at 1 51 20 PM" src="https://user-images.githubusercontent.com/7606853/211421187-b8dd518e-58b2-4446-aecf-0c6b7ab0b97f.png">

**Comment by iccub** [comment]
Has to be fixed on Youtube's end. Same result in Safari for me
