### ISSUE TITLE
URL bar improvements on slow connection and on slow websites

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6730]
See PR for test plan

**Comment by Uni-verse** [comment]
Verified on `iPhone 12`, `iOS 16.1` & `iPad (7th Gen),` `iPadOS 16` using version `1.48 (23.2.16.18)`

Test Plan: https://github.com/brave/brave-ios/pull/6759#issue-1531416114

- Ensured that loading URLs from outside of the app using the share extension works.
- Ensured that tabs are reloaded when relaunching the app.
- Ensured that URLs are loading via URL bar submission.
- Ensured progress bar displays the progress of the page load quicker
- Ensured that URL bar shows URL when loading the page and is not empty

Example | Example | Example
-|-|-
![IMG_4520](https://user-images.githubusercontent.com/17885425/219512773-d146b4ce-0230-4c77-957e-100977f5b984.PNG) | ![IMG_4518](https://user-images.githubusercontent.com/17885425/219512788-6cf967fe-8f87-4b39-b732-b33995873499.PNG) | ![IMG_4517](https://user-images.githubusercontent.com/17885425/219512807-242b9ab7-6c88-421a-b09c-b6fe04a96015.PNG)
![IMG_0998](https://user-images.githubusercontent.com/17885425/219520050-9e1d4d72-c28f-4bd3-8684-b931a6defa73.PNG) | ![IMG_0997](https://user-images.githubusercontent.com/17885425/219520058-32ff9478-0813-41c8-8d32-3d56e0572b03.PNG) | ![IMG_0996](https://user-images.githubusercontent.com/17885425/219520067-ca9c3870-d201-4eb9-81c7-5802bd4e00d2.PNG)

https://user-images.githubusercontent.com/17885425/219514545-508f85ba-6037-4d9f-855a-9d57521f777e.mov
