### ISSUE TITLE
Slight update to P3A text

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6737]
### Description: 
please update the onboarding P3A text to

Share Completely Private and Anonymous Product Insights. [x]
This helps us learn what Brave features are used most often. Change at any time in Brave Settings under ‘Brave Shields and Other Privacy Settings.

cc @fmarier @PrivacyMatters

**Comment by Uni-verse** [comment]
Verified using version `1.48 (23.2.16.18)` on the following device(s):

- `iPhone 12`, `iOS 16.1`
- `iPhone XR`, `iOS 15.5`
- `iPad (9th Gen),` `iPadOS 15.6.1` 

- [x] Verified P3A onboarding copy update

Example | Example
-|-
![IMG_4528](https://user-images.githubusercontent.com/17885425/219798946-85b52c57-ee56-4f39-9717-d9e2c2a94ac7.PNG) | ![IMG_4529](https://user-images.githubusercontent.com/17885425/219798959-49dc8d78-6e05-456a-9f45-b71ad31f0e89.PNG)
![IMG_0139 3](https://user-images.githubusercontent.com/17885425/219799013-585aa51f-d980-4e8a-ad61-a6c13696ec5b.PNG) | ![IMG_0140 3](https://user-images.githubusercontent.com/17885425/219799022-1a46d724-490a-4984-b426-3a51c122cf49.PNG)

**Comment by PrivacyMatters** [comment]
Looks good - thx @anthonypkeane
