### ISSUE TITLE
can't scroll on `https://www.skysports.com/football` due to cookie consent being enabled in certain cases

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#6741]
### Description: 

I ran into this several times where `https://www.skysports.com/football` becomes unscrollable/unusable. Once you disable the `Block Cookie Consent Notices`, the website will start working. If you either reject/approve the cookie consent and then re-enable `Block Cookie Consent Notices` setting, the website will still function and then eventually stop again.

### Steps to Reproduce 

  1. install/launch `1.46.2 (23.1.10.20)`
  2. run through onboarding and then restart the browser
  3. click on `Yes` on the `Cookie Consent` panel that will appear right after the restart
  4. visit `https://www.skysports.com/football` and you'll get a cookie consent
  5. restart the browser and the same tab will reload again (active tab) and the cookie consent won't be appearing

However, now you can't use the website as it's unscrollable. Disabling `Block Cookie Consent Notices` fixes the issue once you've made a decision on the cookie consent (I always reject/then enable the feature again).

### Actual result: 

`https://www.skysports.com/football` becomes unusable/unscrollable when `Block Cookie Consent Notices` has been enabled

Example of the issue --> https://youtu.be/xRRdJG5xeFo

### Expected result:

Users should be able to scroll through websites without any issues and not experience webcompat issues when `Block Cookie Consent Notices` has been enabled.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

100% reproducible when using the STR/Cases outlined above.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? `Yes`
- Can you reproduce this issue with the previous version of the current build from TestFlight? `Yes`
- Can you reproduce this issue with the current build from AppStore? `Yes` using `1.46.2 (23.1.10.20)`

### Device details: 

* `iPhone 11` running `iOS 16.2` - **Reproduced**

### Website problems only:

- did you check with Brave Shields down? `Yes` - doesn't fix the issue, `Block Cookie Consent Notices` needs to be disabled.
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

**Comment by ryanbr** [comment]
Temporarily disabled; https://github.com/easylist/easylist/commit/956f807d0426a5fdd86e8b711ce1efdc7261fa8f  

Lets retest in 24/48hrs.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12`, `iOS 16.2` & `iPad (9th Gen),` `iPadOS 15.6.1` using version `1.48 (23.2.13.20)`

Using STR in https://github.com/brave/brave-ios/issues/6741#issue-1529476419

1. Install 1.48
2. Complete onboarding, enable `Cookie Banner Consent Blocking`
3. Visit `https://www.skysports.com/football`
4. Restart browser and reload page

- Ensured website loads and is scrollable after re-launching browser

Example | Example | Example
-|-|-
![IMG_4487](https://user-images.githubusercontent.com/17885425/218891395-8a6b514b-3435-42ea-bd25-ccea00f46ab0.PNG) | ![IMG_4488](https://user-images.githubusercontent.com/17885425/218891400-12819aaa-7370-41c5-8ded-794caf902e90.PNG) | ![IMG_4489](https://user-images.githubusercontent.com/17885425/218891401-601c93e2-dde9-4129-8aa7-170efc245a3b.PNG)
![IMG_0122 2](https://user-images.githubusercontent.com/17885425/218891608-e6c2ebe8-f879-4da3-9fd4-faac7d938b78.PNG) | ![IMG_0123 2](https://user-images.githubusercontent.com/17885425/218891610-7bd09fce-fc0b-494c-bf46-c61f40d3bf7b.PNG)
