### ISSUE TITLE
disabling shields/`Block Cross-Site Trackers` doesn't display the ads within the page

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#6743]
### Description: 

When disabling/enabling `Block Cross-Site Trackers` or the shields in general, you'll get into a case where disabling shields will stop displaying the ads within the page. For example, on a clean install, disabling the shields on certain sites will start displaying the ads which is expected as you're disabling shields, however, after doing it a few times, ads will stop appearing even if shields or `Block Cross-Site Trackers` has been disabled.

### Steps to Reproduce 

  1. download/install `1.46.2 (23.1.10.20)` and run through onboarding
  2. visit https://www.buzzfeed.com and disable shields (you should start seeing ads load within the page)
  3. re-enable shields and you should see the ads disappear/being blocked as expected
  4. disable `Block Cross-Site Trackers` via the shields panel and you should see ads being loaded within the page
  5. enable ``Block Cross-Site Trackers`` within the shields panel and the ads will disappear/being blocked
  6. run through steps 1-5 a few times and you'll notice that ads stop appearing within the page even if shields is disabled

Please take a look at the video for more context which makes the above easier to follow/understand.

### Actual result: 

Example of the issue occurring that's being described above --> https://youtu.be/egwpCQyzLoc

### Expected result:

From a user perspective, disabling the shields should start showing ads on the page rather than disabling shields doing nothing.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

100% reproducible when running through the STR/Cases outlined above.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? `Yes`
- Can you reproduce this issue with the previous version of the current build from TestFlight? `Yes`
- Can you reproduce this issue with the current build from AppStore? `Yes` using `1.46.2 (23.1.10.20)`

### Device details: 

* `iPhone 11` running `iOS 16.2` - **Reproduced**
* `iPhone 12` running `iOS 16.2` - **Reproduced**

### Website problems only:

- did you check with Brave Shields down? `Yes` (as mentioned above, its part of the issue re: ads not appearing)
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

**Comment by iccub** [comment]
Please retest and try other websites. I tried to repro and couldn't
It could be that this particular website stops showing ads after few reloads

**Comment by Uni-verse** [comment]
Unable to reproduce this using the STR in https://github.com/brave/brave-ios/issues/6743#issue-1529551688 on `iPhone 12` running `iOS 16.1` & `iPhone XR` running `iOS 15.5` using version `1.48 (23.2.15.17)`

Test Pages: 
`https://www.pcgamer.com`
`https://wwwbuzzfeed.com`

Example | Example
-|-
![IMG_4501](https://user-images.githubusercontent.com/17885425/219429721-0859393e-6868-43ef-9f8e-65a35d978d75.PNG) | ![IMG_4502](https://user-images.githubusercontent.com/17885425/219429743-2f4f0598-cc23-4974-a532-9a5d7b250d44.PNG)
![IMG_4503](https://user-images.githubusercontent.com/17885425/219429820-2426c285-fdc5-49f9-b753-19918df60449.PNG) | ![IMG_4504](https://user-images.githubusercontent.com/17885425/219429846-86fd5b1a-7ba8-488c-8843-431c8866e47f.PNG)
