### ISSUE TITLE
Brave News feed displays duplicate cards when following multiple regions

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6745]
### Description: 

If you follow sources that belong in multiple regions and also follow a source that only belongs to one it causes both those regions feeds to download.  The sources that belong to both of the regions would end up showing duplicate items from those sources

### Steps to Reproduce 
  1. Prefix: Set phone's region to en_US or use debug override
  1. Follow "Gaming" channel, "Gamerant" source and "The Independent" source

### Actual result: 
Gamerant source feed items will be duplicated at the top

### Expected result:
Shouldn't duplicate

### Reproduces how often: 
Easy

### Brave Version:
1.46+

**Comment by Uni-verse** [comment]
Verified on `iPhone XR` running `iOS 15.5` using version `1.47 (23.1.17.15)`

Using STR in https://github.com/brave/brave-ios/issues/6745#issue-1529596367

- Verified subscribing to sources from multiple regions does not result in duplicate news cards in the feed.

 Example | Example
-|-
![IMG_0260](https://user-images.githubusercontent.com/17885425/213215885-7ae10537-d135-413c-90f6-1d0a689e22aa.PNG) | ![IMG_0261 2](https://user-images.githubusercontent.com/17885425/213215923-f16faecd-9baa-4d3e-af96-efadbfc4340c.PNG)
