### ISSUE TITLE
Playlist :: Auto-Play - set to on by default

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6749]
### Description: 

Please change the default for Playlist :: Auto-Play  and have it On by default. 

![IMG_AED22BEC5661-1](https://user-images.githubusercontent.com/7606853/211963595-5509baaf-1415-4b9a-b5d6-5b5c4c0521c1.jpeg)

**Comment by iccub** [comment]
To be precise, we will change the default for new users only. We should avoid altering default settings for existing users

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` & `iPhone XR` running `iOS 16.2` & `iOS 15.5` using version `1.47 (23.1.23.20)`

Reproduced with `1.47 (23.1.18.17)`

<img width="500" alt="old" src="https://user-images.githubusercontent.com/17885425/214170004-a407eb1c-78df-4516-b64e-d2f107b3919c.PNG">

Upgraded to `1.47 (23.1.23.20)`

- Verified Autoplay setting in playlist is retained when on existing profile

Clean profile install `1.47 (23.1.23.20)`

- Verified Autoplay setting in playlist is ON by default
- Verified Playlist videos are playing automatically when autoplay is enabled (default)

<img width="500" alt="new" src="https://user-images.githubusercontent.com/17885425/214173604-9a0ba35b-10d5-4101-bbd5-c2cc8b393b36.PNG">
