### ISSUE TITLE
Crash on yourls website

### ISSUE THREAD

**Issue by fdiengdoh** [brave/brave-ios#6752]
### Steps to Reproduce 
  1. visit https://yourls.org/
  2.
  3.

### Brave Version: Version 1.46.2 (23.1.10.20)

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? yes
- did you check in Safari/Firefox (WkWebView-based browsers)? yes

**Comment by Uni-verse** [comment]
Verified on `iPhone 12`, `iPad (9th Gen)` running `iOS 16.2`, `iPadOS 15.6.1` respectively using version `1.48 (23.2.13.20)`

- Ensured loading `https://yourls.org` does not crash

Example | Example
-|-
![IMG_4484](https://user-images.githubusercontent.com/17885425/218847253-56340933-42d1-4e99-893f-808c39d9589e.PNG) | ![IMG_0991](https://user-images.githubusercontent.com/17885425/218847296-bca58e13-0a90-498f-bc64-609fd1250ef2.PNG)
