### ISSUE TITLE
Restoring VPN does not allow user to enter vpn settings

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6753]
### Steps to Reproduce 
  1. Buy VPN
  2. Uninstall the app
  3. Go to vpn -> restore purchase
  4. Go to vpn settings

### Actual result: 
Buy vpn screen is shown

### Expected result:
Should open vpn settings screen.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 16.2 `using version `1.47 (23.1.23.20)`

Test Plan: 

1. Purchase VPN
2. Uninstall App
3. Re-install App
4. Restore VPN
5. Open VPN settings

- Ensured VPN settings are opened after restoring VPN

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_4334](https://user-images.githubusercontent.com/17885425/214468618-4ef2fbf9-1ecf-4372-81c8-614df0663678.PNG) | ![IMG_4335](https://user-images.githubusercontent.com/17885425/214468620-73fc1656-abc6-4380-9192-1c57b528d363.PNG) | ![IMG_4336](https://user-images.githubusercontent.com/17885425/214468621-f5421d46-6c50-44dc-b4b7-76cd594bd2dd.PNG) | ![IMG_4341](https://user-images.githubusercontent.com/17885425/214468737-2af370c8-f6c3-495e-997b-3d8cd373fd64.PNG) | ![IMG_4342](https://user-images.githubusercontent.com/17885425/214468740-dd75acdb-ba99-44d1-af99-856d52679113.PNG) | ![IMG_4343](https://user-images.githubusercontent.com/17885425/214468741-fba133f5-3f9c-429a-8fde-254af7967f48.PNG)
