### ISSUE TITLE
Don't show web preview for javascript links

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6758]
### Description: 

For javascript links, we shouldn't show our web preview w/ ability to open in a new tab.

### Steps to Reproduce 
  1. Visit https://cp24.com/
  2. Tap and hold on any of the video title/descriptions
  3. Tap 'open in a new tab'

### Actual result: 

Brave:

https://user-images.githubusercontent.com/5314553/212188448-0552ccf1-1838-4be3-9581-4f92d29945a9.MP4

Safari:

https://user-images.githubusercontent.com/5314553/212188524-7060bb9f-16b5-4c2b-83a1-7c915251aa86.mov

### Expected result:

Don't show preview window, or option to open in a new tab

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

https://bravesoftware.slack.com/archives/GB9CJGQV6/p1673559087844689?thread_ts=1673558722.193979&cid=GB9CJGQV6

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 16.2` using version `1.47 (23.1.18.17)`

**Steps to Reproduce**

1. Visit `https://cp24.com/`
2. Tap and hold on any of the video title/descriptions
3. Tap 'open in a new tab'
4. Web preview should be blocked

- Verified web previews for all schemes other than https/http are blocked

<table><tr><td>HTTPS/HTTP scheme</td><td>JS Scheme / All Else</td></tr>

<tr><td>

https://user-images.githubusercontent.com/17885425/213542525-dfd77675-6e15-4722-92a4-c3741f9f0f11.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/213542510-aef0e939-4a79-40ab-9ec9-067cf374c3a0.MP4

</td></tr></table>
