### ISSUE TITLE
Issue with logging into blockclubchicago.org

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#6761]
### Description: 
The website doesn't do anything when trying to enter the email address

### Steps to Reproduce 
  1. go to https://blockclubchicago.org/2023/01/12/can-city-slow-down-drivers-around-grant-park-new-plan-will-consider-ways-to-reduce-traffic-officials-say/
  2. Click on hamburger menu
  3. Scroll down and click on Sign In
  4. Click on Log in
  5. enter valid email address (ask me for it)

### Actual result: 
Nothing happens

### Expected result:
Should show password box

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 16.2` using version `1.47 (23.1.18.17)`

STR: https://github.com/brave/brave-ios/issues/6761#issue-1532045765

- Ensured that password box is shown after entering valid email account.

<img width="500" alt="passbox" src="https://user-images.githubusercontent.com/17885425/213552653-c44b36e5-d5d9-405d-a97a-f3f3a0e40a5b.PNG">
