### ISSUE TITLE
Remove Onboarding background gradient images and render with code

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6765]
### Description: 

These images are 12.5MB alone, and can be removed and just rendered in code instead of loading an image

The gradient is not a standard universal one but its closed to this:

`background: linear-gradient(138.22deg, #A314AE 17.61%, #4A0EE3 83.5%);` in Figma

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` & `iPad (7th Gen)` running `iOS 16.2` using version `1.48 (23.2.7.21)`

- Ensured user is able to complete onboarding
- Ensured onboarding flow remains the same

<table><tr><td>Version 1.47</td><td>Version 1.48</td></tr>

<tr><td>

https://user-images.githubusercontent.com/17885425/217913238-62a77baa-1876-4579-9c0f-e01899fa1d78.mov

</td><td>

https://user-images.githubusercontent.com/17885425/217912617-02663ead-69bb-4487-8335-49c47a1bd2fc.mov

</td></tr></table

Version 1.48 (Tablet)

https://user-images.githubusercontent.com/17885425/217916515-8bea6b43-0927-47d5-a645-ff3bed4d4609.mov
