### ISSUE TITLE
Incorrect favicon shown in NTP favourites

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6767]
### Description: 

Incorrect favicon can be shown in Favourites on new tab page.

### Steps to Reproduce 
  1. Clear Amazon from history & enable tab bar always visible (not 100% if this step is required)
  2. Start with 0 tabs on NTP
  3. Tap and hold Twitter icon, tap 'Open in New Tab'
  4. Tap 'x' to close Twitter tab
  5. Observe Amazon favicon displayed as Twitter favicon

### Actual result: 

https://user-images.githubusercontent.com/5314553/212431305-3c0de019-e4c6-406e-b8d7-9549a091a133.MP4

### Brave Version: 

App Store build 
```
Version 1.46.2 (23.1.10.20)
BraveCore 1.46.144 (108.0.5359.128)
Device iPhone15,2 (iOS 16.2)
```

First noticed on on `feature/recently-closed` branch with development build.

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
closing in favor of https://github.com/brave/brave-ios/issues/6066
