### ISSUE TITLE
Hide Browser History Suggestion in PBM

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#6773]
### Description: 

Browser History suggestions and other suggestion types should not appear when user is using the Private Browsing Only Mode.

In PBM we dont show History from normal Mode and to be in line we should also hide suggestions to be consistent.

Reports related with issue:
https://community.brave.com/t/browser-history-suggestions-while-private/462991

**Comment by Uni-verse** [comment]
Verified on `iPhone XR` running `iOS 15.5` using version `1.47 (23.1.18.17)`

Using Test Plan in https://github.com/brave/brave-ios/pull/6774#issue-1535480353

- Encountered: https://github.com/brave/brave-ios/issues/6801

Example | Example
-|-
![IMG_0282 2](https://user-images.githubusercontent.com/17885425/213525558-c41e5fe9-eeb1-4d1b-8279-18d98c0c3f1d.PNG) | ![IMG_0283 2](https://user-images.githubusercontent.com/17885425/213525560-aa2883e6-d4e5-4171-9f91-271cf23beab1.PNG)
