### ISSUE TITLE
`Duplicate Active Tab` opens a blank page when in `Reader Mode` 

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-ios#6776]
### Description: 
When a web page opened in `Reader Mode` pressing `Duplicate Active Tab` opens a blank page instead of the original url

### Steps to Reproduce 
  1. Go to https://en.wikipedia.org/wiki/Software
  2. Activate Reader Mode
  3. Long press on toolbar and press Duplicate Active Tab

### Actual result: 
A blank page is opened

### Expected result:
A reader mode version of https://en.wikipedia.org/wiki/Software should be opened

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always (kinda?)

### Brave Version: 
The latest build from the AppStore (1.46.2 (23.1.10.20)) as well as a local `development` build 
- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details: 
iPhone 14 Pro (iOS 16.2) / iPad Pro 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
So last week I was checking one of the recent PRs and found that `Duplicate Active Tab` doesn't work for tabs in reader mode. I then tested it on AppStore build and it was working ok there, so I thought it's just a PR issue. 
I ran few tests today and it looks like I can reproduce it on all devices, even the old 1.45.* version.
When pressing Duplicate Active Tab Brave throws an error:
`2023-01-16 22:40:05.058660+0000 Client[50217:130482771] [Brave] Denying unprivileged request: http://localhost:6596/reader-mode/page?url=https://en.m.wikipedia.org/wiki/Software`
Seems like it's trying to open GCDWebServer's URL and fails here https://github.com/brave/brave-ios/blob/1434ecb55e07848f0d10ad6284854ddbaf852d70/Client/Frontend/Browser/BrowserViewController/BrowserViewController%2BWKNavigationDelegate.swift#L166
and here
https://github.com/brave/brave-ios/blob/1434ecb55e07848f0d10ad6284854ddbaf852d70/Sources/Shared/Extensions/URLExtensions.swift#L525

**Comment by Brandon-T** [comment]
Fixed inadvertently in: https://github.com/brave/brave-ios/issues/6776

**Comment by Uni-verse** [comment]
Not reproducible on `iPhone 12` running `iOS 16.2` using version `1.47 (23.1.20.16)`

- Duplicate Active Tab option is no longer available while reader mode is enabled.

![IMG_4313](https://user-images.githubusercontent.com/17885425/213813690-f46f9704-ad29-4777-ba57-62145f3a4f86.PNG)
