### ISSUE TITLE
Customize Brave Tabs bar modal doesn't show `Maybe later` button on iOS 14 light theme

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#6779]
### Description: 
Customize Brave Tabs bar modal doesn't show `Maybe later` button on iOS 14

### Steps to Reproduce 
  1. Install 1.46.2 from App store
  2. Switch to light theme 
  3. Move tabs bar to top from settings
  4. Visit a couple of pages in a new tab
  5. Upgrade to 1.47 (23.1.16.16)
  6. On launch shows Customize Brave Tabs Bar message but doesn't show the `Maybe later` button` 
  7. Change theme to dark from action centre, `Maybe later` message is shown

### Actual result: 

Light | Dark
-- | --
![image](https://user-images.githubusercontent.com/17010094/212926545-cf82989f-80ed-4df9-8de7-d1eccfeff6ba.png) | ![image](https://user-images.githubusercontent.com/17010094/212926571-e1302f76-4696-4612-bbc6-82fba508ca68.png)

### Expected result:
Show in all themes

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Not sure
- Can you reproduce this issue with the current build from AppStore? Not sure

### Device details: 
iPhone 7+ (iOS 14.8.1)

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @kylehickinson @Uni-verse @kjozwiak @iccub

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 14.4.2` using version `1.47 (23.1.18.17)`

Following the upgraded use case steps in https://github.com/brave/brave-ios/issues/6779#issue-1536486825

- Ensured that `Maybe later` on the toolbar intro modal is visible in all themes.

Light | Dark
-|-
![IMG_2839](https://user-images.githubusercontent.com/17885425/213551740-2c2db1ed-4ef3-4abc-9469-7d54e825496b.PNG) | ![IMG_2838](https://user-images.githubusercontent.com/17885425/213551752-d4536e85-791a-40ad-9216-2c6d4718ded9.PNG)
