### ISSUE TITLE
opening brave ad notifications that use `itms-appss://` opens tabs that can't resolve and stay opened

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#6782]
### Description: 

When you receive certain ad notifications that open the `App Store`, we open a new tab as well that never ends up resolving as `itms-appss://` is being used. I'm not sure if that's being done on purpose or it's the only way to open the `App Store`. But it would be a lot better if we just opened the `App Store` rather than creating new tabs that don't resolve due to the URL not being a valid URL. In this particular case, the following URL was being used:

* `itms-appss://apps.apple.com/app/apple-store/id1546049391?mt=8`

### Steps to Reproduce 

**`Quick note`** - this is going to pretty hard to reproduce until you receive an ad notifications from Brave that opens the `AppStore`.

  1. install any version of Brave via TF (or via the `AppStore`)
  2. ensure that you have `Brave Rewards` enabled
  3. once you receive an ad notification, tap on the notification and notice that a new tab is opened before the `AppStore` opens

### Actual result: 

**`Example`** | **`Example`**
----------------|-----------------
![image](https://user-images.githubusercontent.com/2602313/213003977-922e8f91-e98f-489f-99d6-5a2e6368273c.png) | ![image](https://user-images.githubusercontent.com/2602313/213004586-737ba67c-9d6d-4786-91e0-531afc857f0a.png)

### Expected result:

If possible, we shouldn't be opening new tabs when an ad notification opens the `AppStore`. Users who use ad notifications might end up with several unresolved tabs after a while. For example, I noticed ~3-4 tabs within my `Tab View` that looked unresolved and couldn't resolve which were related to the above issue.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

100% reproducible once you get an ad notification that opens the `AppStore`

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? `Yes`
- Can you reproduce this issue with the previous version of the current build from TestFlight? `Yes`
- Can you reproduce this issue with the current build from AppStore? `Yes`

### Device details: 

* `iPhone 12` running `iOS 16.2` using `1.46.2 (23.1.10.20)` - **Reproduced**

### Website problems only:

- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

### Additional Information

CCing @kylehickinson as we discussed this one in the `iOS` meeting ~2 weeks or so ago.

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` & `iPad (7th Gen)` running `iPadOS 16.4` using version `1.49 (23.3.31.9)`

- Ensured that opening ad notifications that use itms-appss:// does not open tabs that dont get resolved.
- Ensured that tapping on apple store related ads opens apple store webpage for Tablets

iOS Example | iOS Example | iOS Example
-|-|-
![IMG_2896](https://user-images.githubusercontent.com/17885425/229626645-d837dfc3-8f6c-48f0-8ad9-3b7395ee7c79.PNG) | ![IMG_2897](https://user-images.githubusercontent.com/17885425/229626647-f25e9c4c-e649-416e-8f61-e22ffc853aae.PNG) | ![IMG_2898](https://user-images.githubusercontent.com/17885425/229626653-e765cd17-6d8d-4828-a647-a65d7aeed0f3.PNG)

**iPad Example**
![IMG_1047](https://user-images.githubusercontent.com/17885425/229627082-ab697363-f535-4bbc-862f-0a8d8f1fecc7.PNG)
