### ISSUE TITLE
Brave News opt-in modal/card animation not working when opening new NTP

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#6787]
### Description: 

If a user hasn't opted into `Brave News` and still sees the opt-in modal/card via NTP, the modal/card won't initially animate when opening NTP until the user scrolls the opt-in modal/card out of sight. Once the user starts scrolling up again and the modal/card becomes visible, the animations start working as expected.

### Steps to Reproduce

  1. install/launch `1.46.2 (23.1.10.20)` and run through the initial onboarding
  2. once the NTP opens/is visible, notice that the images/animations are missing from the Brave News opt-in modal/card
  3. open a NTP and scroll up and you'll notice that all the images are appearing but the animation isn't working
  4. scroll back down so the Brave News opt-in card isn't visible anymore and then scroll back up so it's visible
  5. once it becomes visible, the animations will start working as expected

Please see https://github.com/brave/brave-ios/issues/6786 regarding the correct images not initially loading on a new profile.

### Actual result: 

https://user-images.githubusercontent.com/2602313/213083740-4aa42c30-232c-465d-a7b0-fd5a4490c8ef.mp4

### Expected result:

The animations on the `Brave News` opt-in modal/card should be working as soon as the user sees the opt-in card/modal.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases outlined above.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Reproducible with `1.47 (23.1.17.15)`
- Can you reproduce this issue with the previous version of the current build from TestFlight? Reproducible with `1.46 (22.12.15.19)`
- Can you reproduce this issue with the current build from AppStore? Reproducible with `1.46.2 (23.1.10.20)`

### Device details: 

* `iPhone 11` running `iOS 16.2` - **Reproduced**

### Website problems only:
- did you check with Brave Shields down? `N/A` 
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A` 

### Additional Information

CCing @srirambv @Uni-verse @iccub

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.49 (23.3.15.17)
- Verified steps from issue description
- Verified Brave News opt-in modal shows animation every time it is brough into focus either by hiding and bringing it up or by opening a new tab

iPhone 7+ (iOS 15.7.3) | iPhone XR (iOS 16.3.1) | iPad Pro (16.4 Beta 2)
-- | -- | -- 
<video src=https://user-images.githubusercontent.com/17010094/225574367-4c366298-6fa8-4e51-b53e-902eca511837.MP4> | <video src=https://user-images.githubusercontent.com/17010094/225574389-58c08c5b-4d3a-412c-820f-4b24b17afff4.MP4> | <video src=https://user-images.githubusercontent.com/17010094/225574341-03a6dc37-5493-432d-93f5-44f475c46680.MP4>
