### ISSUE TITLE
closing/re-launching Brave quickly will sometimes cause Brave to crash

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#6788]
### Description: 

I don't remember the context but I remember discussing this before on Slack re: Brave crashing if you close/re-open the application pretty quickly several times in a row. Sometimes it happens after ~2-3 restarts and sometimes it takes a while to get into a state where it ends up crashing as soon as you close it when it's been re-opened. Note, this usually only happens when you close Brave right after it was opened. Assuming it has something to do with the application not closing correctly till it's restarted again.

I believe @Uni-verse mentioned he's seen something similar before after restarting Brave. Probably worth seeing if we can prevent this from happening even though it's a edge case.

### Steps to Reproduce
 
  1. install/launch `1.46.2 (23.1.10.20)` and run through the initial onboarding
  2. once onboarding has been completed, close/re-open Brave

Repeat the above a few times re: closing/re-opening Brave right away and you'll run into the crash. Once you've crashed once, you'll reproduce it every time when you quickly restart. However, if you wait ~1min or so, the application usually never crashes.

### Actual result: 

https://user-images.githubusercontent.com/2602313/213087165-b0294c4a-b07c-4b2d-8db2-4f6583bc6317.mp4

### Expected result:

Probably shouldn't be crashing the application even though the above case is an edge case that most users won't run into. However, worth seeing what's causing the crash in case the bug can lead to other issues down the road.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases outlined above.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Reproducible with `1.47 (23.1.17.15)`
- Can you reproduce this issue with the previous version of the current build from TestFlight? Reproducible with `1.46 (22.12.15.19)`
- Can you reproduce this issue with the current build from AppStore? Reproducible with `1.46.2 (23.1.10.20)`

### Device details: 

* `iPhone 11` running `iOS 16.2` - **Reproduced**

### Website problems only:
- did you check with Brave Shields down? `N/A` 
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A` 

### Additional Information

CCing @srirambv @iccub

**Comment by kylehickinson** [comment]
@kjozwiak / @brave/qa-team If this is the same thing we discussed on Slack a while ago then this is an iOS bug, you can reproduce it with basically any app and no crash reports are generated for it. Basically when you swipe away an app to force kill it there's a small delay before the application is actually closed, if you reopen the app before that time iOS doesn't stop the close, so it appears to "crash" the app when in reality its just closing it from when you swiped it away
