### ISSUE TITLE
omnibox disappears when the `cookie consent` banner/toast appears while

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#6789]
### Description: 

When attempting to type into the omnibox right after the second browser restart while the `cookie consent` panel/toast is appearing, you'll get into a state where the omnibox will disappear but the OSK will still be visible. Typing into the OSK while in this state will re-display the area of the UI were the omnibox is usually located but won't be accessible/usable.

### Steps to Reproduce 

  1. install/launch `1.46.2 (23.1.10.20)` and run through the initial onboarding
  2. once onboarding has been completed, start typing into the omnibox and enable `Recent Search` & `Search Suggestions`
  3. load blizzard.com and restart the browser
  4. right after restarting the browser, quickly tap on the omnibox and start editing/typing before the `cookie consent` panel appears

### Actual result: 

**`Example`** | **`Example`**
---------------|-----------------
![image](https://user-images.githubusercontent.com/2602313/213106224-8da375e7-548a-4f17-bab0-450fd97b51bc.png) | ![image](https://user-images.githubusercontent.com/2602313/213106169-ac35b738-4528-4cdd-83f2-d99831dee030.png)

Here's an example video of the issue occurring (easier to understand when visually seeing it):

https://user-images.githubusercontent.com/2602313/213113098-218a4595-cbc9-430f-ae54-a6aa4fde1e04.mp4

cc

### Expected result:

The omnibox shouldn't be getting into a state where it's not visible when it should while the OSK is still visible/usable.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases outlined above.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Reproducible with `1.47 (23.1.17.15)`
- Can you reproduce this issue with the previous version of the current build from TestFlight? Reproducible with `1.46 (22.12.15.19)`
- Can you reproduce this issue with the current build from AppStore? Reproducible with `1.46.2 (23.1.10.20)`

### Device details: 

* `iPhone 11` running `iOS 16.2` - **Reproduced**

### Website problems only:
- did you check with Brave Shields down? `N/A` 
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A` 

### Additional Information

CCing @srirambv @iccub @Uni-verse

**Comment by Uni-verse** [comment]
Verified on `iPhone 12`, `iOS 16.1` & `iPad (9th Gen)`, `iPadOS 15.6.1` using version `1.48 (23.2.15.17)`

Test steps based on https://github.com/brave/brave-ios/issues/6789#issue-1537548856

- Ensured omnibox is visible when typing 

Example | Example
-|-
![IMG_4500](https://user-images.githubusercontent.com/17885425/219205745-d1e24018-6014-42cb-8eb5-00c1aec9e0fa.PNG) | ![IMG_0125 2](https://user-images.githubusercontent.com/17885425/219205845-b8c89862-f796-4d35-9d2f-2aeedc55da71.PNG)
