### ISSUE TITLE
[Bug] - Playlist not working on animedao and 9anime

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#6794]
### Description: 
Playlist does not work on the following websites:
- https://9anime.to/
- https://animedao.to/

### Steps to Reproduce 
  1. Visit the above websites

### Actual result: 
- Playlist does not show an icon on the settings menu or in the URL bar

### Expected result:
- Playlist should work on the above websites

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily Reproduced

### Brave Version: 

- 1.46.x

### Device details: 
- Any

### Website problems only:
- Yes

**Comment by Uni-verse** [comment]
Verified using version `1.47 (23.1.23.20)` on `iPhone 12` running `iOS 16.2`

- Ensured playlist icon appears in the URL or the share menu when visiting `https://9anime.to/`
- Ensured playlist icon appears in the URL or the share menu when visiting `https://animedao.to/`
- Ensured user is able to add videos to playlist from the share menu

Example | Example
-|-
![IMG_4325](https://user-images.githubusercontent.com/17885425/214444856-d37912d9-8fee-40a9-9b2e-2d4a905d3c00.PNG) | ![IMG_4326](https://user-images.githubusercontent.com/17885425/214444861-c60f153a-7615-448b-a928-d4a0e6bc3910.PNG)
![IMG_4327](https://user-images.githubusercontent.com/17885425/214444864-042caf0a-9e76-477d-b47d-42a47100d759.PNG) | ![IMG_4328](https://user-images.githubusercontent.com/17885425/214444867-a3662590-c8ce-4973-a1d5-5196734a0b47.PNG)
