### ISSUE TITLE
[Bug] - ReaderMode should not use GCDWebServer and instead use WKURLSchemeHandler

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#6796]
### Description: 
- Like all other interstitial pages, ReaderMode needs to use `WKURLSchemehandler` instead of `GCDWebServer`

### Steps to Reproduce 
  1. N/A See Internal Ticket: https://github.com/brave/internal/issues/919

### Actual result: 
- ReaderMode uses localhost URL

### Expected result:
- ReaderMode should not use localhost URL

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily Reproduced

### Brave Version: 

- ALL versions

### Device details: 
- All devices

**Comment by Uni-verse** [comment]
Verified using version `1.47 (23.1.20.16)` on the following device(s):

iPhone 12, iOS 16.2
iPad (7th Gen), iPadOS 16.1
iPhone XR, iOS 15.5
iPhone X, iOS 14.4.2

- Ensured user is able to enable and disable reader mode on webpages via icon in URL bar.
- Ensured that reader mode works in `normal` & `private tabs`
- Ensured reader mode setting bar works with top toolbar enabled.
- Ensured that top toolbar collapses when scrolling through webpage with reader mode enabled.

Example | Example | Example
-|-|-
![IMG_0953](https://user-images.githubusercontent.com/17885425/213825414-08afa2c2-e467-4423-85c6-b63f7b54b853.PNG) | ![IMG_0954](https://user-images.githubusercontent.com/17885425/213825415-472dacbe-6935-4d19-aa36-b3388d556f09.PNG) | ![IMG_0955](https://user-images.githubusercontent.com/17885425/213827297-ef53da02-d203-4667-98eb-2b8559367c5f.PNG)
-|-|-
![IMG_4314](https://user-images.githubusercontent.com/17885425/213825486-d240ce34-0cde-4a8e-88c3-0a197f04b23a.PNG) | ![IMG_4315](https://user-images.githubusercontent.com/17885425/213825491-0ad0316b-c923-4cb6-b53c-0e227d3b69fb.PNG) | ![IMG_4316](https://user-images.githubusercontent.com/17885425/213827316-fa0012f6-0c17-44e8-ad2e-ddc426e2a660.PNG)
