### ISSUE TITLE
URL not visible in address bar after Google search

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6798]
### Description: 

When the default search engine is set to either Google or Duck Duck Go, and you search something using the omnibar then tap the search bar no address or search term is displayed

### Steps to Reproduce 
  1. Change default search engine to Google / Duck Duck Go (might work with others, only tested these 2)
  2. On new tab page enter any search term into the omnibar and search
  3. Tap the address bar
  4. Observe no search term or address displayed

### Actual result: 

https://user-images.githubusercontent.com/5314553/213523063-e4027e59-2610-4813-891c-4020491f357d.mp4

### Reproduces how often: 

Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Brandon-T** [comment]
Fixed in: https://github.com/brave/brave-ios/pull/6768

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 16.2` using version `1.47 (23.1.20.16)`

**Steps to Reproduce**

1. Change default search engine to Google / Duck Duck Go
2. On new tab page enter any search term into the omnibar and search
3. Tap the address bar
4. Observe no search term or address displayed

- Verified tapping on the URL box does not show empty field after searching with `Google` or `DuckDuckGo`
- Verified search term is highlighted/selected when tapping on URL box after on the search results page

DuckDuckGo | DuckDuckGo
-|-
![IMG_4310](https://user-images.githubusercontent.com/17885425/213773108-7af68bbf-0e0f-4051-96c4-39c3d0b71af7.PNG) | ![IMG_4312](https://user-images.githubusercontent.com/17885425/213773112-6dc1156e-6213-4dd2-a9ce-9a6bf554f431.PNG)
Google | Google
![IMG_4308](https://user-images.githubusercontent.com/17885425/213773165-43de4e21-64f9-4c28-9a79-41b0dde88b5a.PNG) | ![IMG_4309](https://user-images.githubusercontent.com/17885425/213773166-2de67e68-9dcb-463b-89f1-3029565fe71b.PNG)
