### ISSUE TITLE
NTP should work with New Tab Long Press Menu Actions

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#6799]
### Description: 

New Tab long press menu actions needs to be added to Search icon in toolbar while user is in NTP. 

This is especially necessary for users to open a private tab without navigating to Tab Tray while they are are on NTP.

The behaviour will be same like + Button when the tab has a loaded webview. cc @StephenHeaps

**Comment by Uni-verse** [comment]
Verified on `iPhone 12`, `iPhone XR` running `iOS 16.2`, `iOS 15.5` using version `1.48 (23.2.7.21)`

- Ensured long press action on `magnifying glass` on NTP shows new tab menu
- Ensured menu is showing in `normal` and `private browsing` modes
- Ensured menu is showing and user is able to open new tabs with `tabs bar` on top and bottom

Example | Example | Example
-|-|-
![IMG_0291 2](https://user-images.githubusercontent.com/17885425/217900485-7fe70dc7-b5b3-469d-bdfc-7325550769ca.PNG) | ![IMG_0289 2](https://user-images.githubusercontent.com/17885425/217900525-7b54a216-7ca4-40bc-a406-87b43dcc0ff3.PNG) | ![IMG_0292 2](https://user-images.githubusercontent.com/17885425/217900595-251db6b0-6114-4278-b80c-b8cd15750d9f.PNG)
