### ISSUE TITLE
Add NTP-SI P3A reporting

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-ios#6806]
### Description: 

Add NTP-SI P3A reporting for iOS. See brave/brave-browser#24609 for implementation details on Desktop + Android. Also see internal spec for more conceptual details

**Comment by tmancey** [comment]
FYI: For landed iOS would need to start a 10 second timer for now. The ads library does not inform the browser if an ad was landed.

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.6]
Brave build: 1.57 (23.8.16.21)
BraveCore: 1.57.47 (116.0.5845.96)
```
---------------------------

**STEPS:**
1. Fresh launch Brave Dev build
2. Settings > BraveCore Switches > `P3A` section
3. Enable `Don't randomize upload interval` > Set `Express rotation interval` to a low number (I set it to 3) > Save
4. Go back to `Settings` > View Chromium Local State > Refresh > Verify there are no `creativeInstanceId.` records under `p3a` section
5. Now go back and open NTP > Keep open NTP until SI is shown
6. Open SI page > Wait ~10 seconds
7. Go to `Settings` > View Chromium Local State > Refresh > Verify `creativeInstanceId.` records with suffixes `views`, `clicks` and `lands` are shown
8. Delete and reinstall Brave
9. Now enable `Rewards` first:
- Settings > BraveCore Switches > Log Verbosity > Paste the following: */brave_ads/*=6,*/bat_ads/*=6,*/brave_rewards/*=6,*/bat-native-ledger/*=6
- Return to `Settings` > View Rewards Debug Menu > Switch `Override` from `None` to `Staging` > Restart Brave
- Enable `Rewards`
10. Repeat Steps 2 - 7 > Verify there are no `creativeInstanceId.` records with suffixes `views`, `clicks` and `lands` are shown at this time

**ACTUAL RESULTS:**
- Verified that there are no `creativeInstanceId.` records under `p3a` section when `Rewards` is OFF and no SI viewed
- Verified that `creativeInstanceId.` records with suffixes `views`, `clicks` and `lands` are shown when `Rewards` is OFF and SI viewed
- Verified that there are no `creativeInstanceId.` records under `p3a` section when `Rewards` is ON and SI viewed

---------------------------

*Rewards is OFF*
|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/5359af64-da48-423b-8e7c-96d663fb72d9) | ![2](https://github.com/brave/brave-ios/assets/128532965/93774796-99a1-4b0a-a74c-273159508902) | ![3](https://github.com/brave/brave-ios/assets/128532965/ed41f28c-23e1-4348-baec-d0cee1db2f95) |

*Rewards is ON*
|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/872a24dd-18ba-4427-9688-5e98167404c4) | ![2](https://github.com/brave/brave-ios/assets/128532965/fe853498-0ca1-4fff-bc26-1373604db540) | ![3](https://github.com/brave/brave-ios/assets/128532965/e514cbac-f428-40c4-9767-3ba1a512a460) | ![4](https://github.com/brave/brave-ios/assets/128532965/d704704a-2664-4696-aa74-295a1efebbbf) |
