### ISSUE TITLE
Playlist :: Carplay 15 sec backward, fast backward, pause and resume buttons not working

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6807]
### Description: 
Person reported in reported to the buttons on CarPlay that: 

"These buttons dont work in my car screen, so i have to control via my phone, but i'm unsure of other cars or if this is a known issue"

**Comment by anthonypkeane** [comment]
Brandon, ideally can we get this fix into 1.48

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 16.1` using version `1.48 (23.2.24.14)`

- Ensured that 15 sec backward, forward, pause and resume buttons are working in Carplay
- Ensured that buttons are working on mobile device in playlist

Mobile | CarPlay Sim
-|-
![IMG_4577](https://user-images.githubusercontent.com/17885425/221331572-859faa1b-d24e-43d3-9404-74e9c3d9951a.PNG) | ![Screen Shot 2023-02-24 at 9 21 24 PM](https://user-images.githubusercontent.com/17885425/221331540-5c7e0eb5-450d-42f4-b526-6b6d16770860.png)
