### ISSUE TITLE
Ensure users can see Swap functionality on portfolio page for new wallet users

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-ios#6811]
## Description 

Right now on iOS, when a new wallet is setup. The users default account goes to Solana and since we don't currently have Solana swaps on Mobile, we don't show this option. 

A temporary fix to this is to show the swap functionality on the portfolio screen beside BUY and SEND, even though Solana swaps isn't supported yet. 

Link to conversation https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1674231066776899

## Steps to Reproduce

   1. Set up a new wallet
   2. Click the action button at bottom of the screen
   3. 

## Actual result:

![IMG_6592](https://user-images.githubusercontent.com/12224304/213759664-a5c8eb24-2862-497d-8897-edfaacd3e249.png)

## Android Device details:
   - Install type (ARM, x86):
   - Device type (Phone, Tablet, Phablet):
   - Android version:

## Version/Channel Information:

- Can you reproduce this issue with the current release? 
- Can you reproduce this issue with the beta channel? 
- Can you reproduce this issue with the nightly channel? 

## Other Additional Information:

- Does the issue resolve itself when disabling Brave Shields? 
- Does the issue resolve itself when disabling Brave Rewards? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.48 (23.2.15.17)
- Verified steps from [#6935](https://github.com/brave/brave-ios/pull/6935)
- Verified `Buy`, `Send` and `Swap` buttons are shown for all networks
- Verified for unsupported network, selecting `Swap` shows message 
- Encountered [#6965](https://github.com/brave/brave-ios/issues/6965)

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (16.2)
-- | -- | -- 
<img width=300 src=https://user-images.githubusercontent.com/17010094/219618376-aa2ebef1-3d96-4026-b649-0b1e7642dff9.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/219614438-246da825-4a24-4eea-9b6b-9d6fcfc9f00e.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/219619215-cfd299bb-ddc5-4664-b446-e60fac87591e.png>
