### ISSUE TITLE
Remove usage of LocalRequestHelper

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#6813]
### Description: 
- LocalRequestHelper.swift handler is not currently injected into any pages.
- Everything seems to work without it, but there are `potential` edge cases where it MIGHT be used, so we should inject it OR rewrite those internal scripts to remove it.

### Steps to Reproduce 
  1. N/A

**Comment by Uni-verse** [comment]
Verified using version `1.48 (23.2.21.18)` on `iPhone 12`, `iOS 16.1` & `iPad (7th Gen)`, `iPadOS 16`

Using Test Plan in https://github.com/brave/brave-ios/pull/6814#issue-1551372210

- Ensured that entering and exiting Reader mode works
- Ensured that entering, exiting Reader Mode works using a very bad network/edge in developer mode

Example | Example | Example
-|-|-
![IMG_4545](https://user-images.githubusercontent.com/17885425/220472339-6244c697-c48a-4824-b42e-aee7a62404c0.PNG) | ![IMG_4546](https://user-images.githubusercontent.com/17885425/220472349-393e4419-4600-4581-9c97-e60b2c260951.PNG) | ![IMG_4547](https://user-images.githubusercontent.com/17885425/220472360-0fca796e-c987-4f4e-920d-b18a0b44da9f.PNG)
![IMG_1011](https://user-images.githubusercontent.com/17885425/220472441-2c8dcb80-4fe0-420e-bc21-2a90dcb067e6.PNG) | ![IMG_1012](https://user-images.githubusercontent.com/17885425/220472445-b97b4ceb-e939-44cf-97d3-c5d46ac37b79.PNG) | ![IMG_1015](https://user-images.githubusercontent.com/17885425/220472551-b6fba022-083a-4457-88e4-c59af12143eb.PNG)
