### ISSUE TITLE
ipfs:// scheme support for iOS

### ISSUE THREAD

**Issue by cypt4** [brave/brave-ios#6818]
1) Add remote gateway setting https://github.com/brave/brave-ios/issues/6835
2) Support opening ipfs:// schemes from navigation bar https://github.com/brave/brave-ios/issues/7013
3) Support opening ipfs:// schemes from links https://github.com/brave/brave-ios/issues/7128
4) Nav bar url rewrite ? https://github.com/brave/brave-ios/issues/7013
5) Handle ipfs:// url clicking from other apps https://github.com/brave/brave-ios/issues/7129
6) ~~ipfs:// subresource loading~~

**Comment by nuo-xu** [comment]
@cypt4 we are not going to support ipfs scheme url subresource loading, same as SNS/ENS/UD, since it needs more custom js injection which we are trying to avoid due to security/privacy concern. 
cc @jamesmudgett

**Comment by nuo-xu** [comment]
Close as all sub-issues are closed.
