### ISSUE TITLE
Updated bookmark is not sent to sync

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#682]
### Steps to Reproduce 
  1. Join a sync group
  2. Edit a bookmark

**Actual result:** 
New result is not sent to the sync server.

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
* Verification passed on iPhone 6/7+/iPad Pro using 1.9(19.3.9.1)
* Verified passed with 1.9 (19.3.9.1) on iPhone SE
* Verified passed with 1.9 (19.3.9.1) on iPhone 8
*  Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR.
