### ISSUE TITLE
Allow to permanently delete Sync accounts

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6820]
Implement Permanently Delete Sync Chain functionality with details

The Delete Action
The delete button is added to Sync Settings and this is handling functionality like the actual delete chain action, removing sync observers, resetting the chain and clearing the local preferences. The delete action will show an alert to user similar to Android but using the design used for pop-ups in iOS settings.

The Account Deleted Error
After validating sync code words, a new callback is added to validate if account is not deleted and if it is deleted according to error type, app shows account deleted error alert and like delete chain action it will removing sync observers and clears the local preferences.

The Account Deleted Observer
Adding an observer and handling different cases for different parts of the application when the sync chain is deleted from another device.

**Comment by iccub** [comment]
We will probably want it for 1.48

**Comment by Uni-verse** [comment]
Verified using `1.49 (23.3.23.15)` on `iPhone X` running `iOS 16.3.1` & `iPad (9th Gen)` running `iPadOS 15.6.1`

Test Plans: https://github.com/brave/brave-ios/issues/6820#issue-1553328533, https://github.com/brave/brave-ios/pull/7031#issue-1603746305

Encountered: https://github.com/brave/brave-ios/issues/7146

**Case: Delete Action**

- Confirmed `Delete Sync Account` button is present when joining or created a sync chain.
- Confirmed delete message is shown when `Delete Sync Account` button is tapped
- Confirmed that user is able to dismiss the delete confirmation message
- Confirmed that pressing delete will remove user from sync chain flow and take user back to settings menu
- Confirmed user is able to join/create sync chain after deleting previous sync chain

iPhone | iPhone | iPad | iPad
-|-|-|-
![IMG_2847](https://user-images.githubusercontent.com/17885425/227632339-b6bf8145-9174-416e-bd5c-8d4ecfbe55e8.PNG) | ![IMG_2853](https://user-images.githubusercontent.com/17885425/227632487-38ddc767-f625-4f3b-9d2f-356068593a5b.PNG) | ![IMG_0163](https://user-images.githubusercontent.com/17885425/227632605-20cde25f-48f3-406d-abbc-4390304eb128.jpg) | ![IMG_0164](https://user-images.githubusercontent.com/17885425/227632608-420a2935-a832-4fd2-b119-bcc9ce10fb2a.PNG)


**Case: Account Deleted Error**

- Confirmed when scanning QR code of sync chain is that deleted will display error message
- Confirmed that other devices that were in the sync chain will be shown in error or removed from the sync chain page after deleting sync chain permanently.

Example | Example
-|-
![IMG_2850](https://user-images.githubusercontent.com/17885425/227633436-fc74d170-7885-4172-88e2-00ff5b394f0d.jpg) | ![IMG_0167](https://user-images.githubusercontent.com/17885425/227633461-e88b39d5-462f-409d-9604-09eadfe6a864.jpg)

**Case: Account Deletion Observer**

- Confirmed that other devices in the sync chain will be removed from the sync chain or shown a message that no devices are in the sync chain.

Example | Example | Example
-|-|-
![IMG_2848](https://user-images.githubusercontent.com/17885425/227633365-f2c72446-b064-4312-a096-7c273fcfd352.PNG) | ![IMG_0166](https://user-images.githubusercontent.com/17885425/227634031-4c21487a-055f-449b-a35a-ee283cc4dfa0.PNG) | ![IMG_2849](https://user-images.githubusercontent.com/17885425/227634080-f7de0677-d39c-4ae3-8160-60ef8605dbd6.PNG)
