### ISSUE TITLE
Recent searches 'show more' text is cut in some languages

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6824]
### Steps to Reproduce 
  1. Search for something
  2. Enable recent searches setting

### Actual result: 
![IMG_6D6A8BAC0509-1](https://user-images.githubusercontent.com/6950387/214145043-8d8ebb20-58e7-437d-b41f-c4dce26459db.jpeg)

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: iPhone 14 [iOS 16.4.1] and iPad Air [iPadOS 16.4.1]
Version: 1.51 (23.5.5.18) 
BraveCore: 1.51.110 (113.0.5672.77)
```

**STEPS:**
1. Launch Brave
2. Open search bar > Enable `Recent Searches`
3. Make some searches

**ACTUAL RESULTS:**
- Verified that `Show more` in different languages is not truncated 

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://user-images.githubusercontent.com/128532965/236583125-851dc33c-c9a2-4923-acde-8327caa70175.png) | ![2](https://user-images.githubusercontent.com/128532965/236583124-8224553c-1fd8-4c47-b7d0-ffc7ff6c7847.png) | ![3](https://user-images.githubusercontent.com/128532965/236583122-00afcd69-9d51-41d6-a4c8-4cae52e374be.png) | ![4](https://user-images.githubusercontent.com/128532965/236583123-b9adf243-e9fe-4cea-b089-02b074c7234e.png) |

|5|6|
|:-:|:-:|
| ![1](https://user-images.githubusercontent.com/128532965/236583113-6735ede5-c5e2-42b5-b062-971a675e0e2b.png) | ![2](https://user-images.githubusercontent.com/128532965/236583119-61e3d475-18b4-429e-9782-72a2441b751b.png) |
