### ISSUE TITLE
Wallet: Empty NFT tx confirmation via dapp when NFT is not added as user visible asset.

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6827]
When user initiate an NFT transfer transaction but didn't add that NFT as his visible asset, an empty transaction confirmation will be displayed.

![Simulator Screen Shot - iPhone 14 Pro - 2023-01-23 at 14 57 46 (1)](https://user-images.githubusercontent.com/1187676/214160475-de3eb2bc-54e5-4e01-996f-debd56d0dbb9.png)

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.7.2 running 1.47 (23.2.1.14)
- Verified steps from [#6828](https://github.com/brave/brave-ios/pull/6828)
- Verified transaction confirmation prompt shows necessary information 

https://user-images.githubusercontent.com/17010094/216119452-c5bc83d1-828c-4a52-bc4d-00b6db32760c.MP4
