### ISSUE TITLE
Add custom filter list URLs

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#6841]
### Description: 
Add the ability to add custom filter lists similar to desktop found in the following page:

<img width="680" alt="Screenshot 2023-01-26 at 3 28 34 PM" src="https://user-images.githubusercontent.com/909331/214861462-4439d67c-5c0f-4a76-af8d-214bfce93dc7.png">

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.50 (23.4.25.20)`

_Custom Filter List UI_

- Confirmed custom filter list URLs can be added to the list.
- Confirmed custom filters can be disabled.
- Confirmed custom filters can be deleted by swipe gesture or in edit mode.
- Confirmed duplicate custom filters cannot be added.
- Confirmed error message is shown for non-https urls in the field.
- Confirmed multiple custom urls can be added.
- Confirmed `Last updated` message when script was last updated is shown in the contents.
- Confirmed `Download failed` is shown when custom url fails to load.

Example | Example | Example | Example | Example | Example | Example
-|-|-|-|-|-|-
![IMG_2995 2](https://user-images.githubusercontent.com/17885425/234702925-bcf5d1c7-1cdd-467a-8267-9e38fc274361.PNG) | ![IMG_2996](https://user-images.githubusercontent.com/17885425/234702930-83ac8078-68df-4b62-9dc3-e17b685dfee9.PNG) | ![IMG_3005 2](https://user-images.githubusercontent.com/17885425/234702985-e9a01250-cb69-41ad-9f41-cc138f56f95c.PNG) | ![IMG_3006 2](https://user-images.githubusercontent.com/17885425/234702990-e7362aed-f244-4054-8809-c177db26a92f.PNG) | ![IMG_3007 2](https://user-images.githubusercontent.com/17885425/234702994-bd06a2ac-614b-48dc-84b9-102bef09eed6.PNG) | ![IMG_3010 2](https://user-images.githubusercontent.com/17885425/234703095-3ea6de4d-4372-416a-872e-69163aecff60.PNG) | ![IMG_3011](https://user-images.githubusercontent.com/17885425/234703100-1c730669-93a7-4b3e-85c0-124b70d594e0.PNG)


_Shields/Blocking Tests_

Test Plan: https://github.com/brave/brave-ios/pull/6857#issue-1566703611

Using Custom filter URL - https://gist.githubusercontent.com/cuba/f13fce20b8fbd043ac8174e39ba16788/raw/af09db2fbda948dcf7a90781716c51f5e36f2237/TestAdBlockRules.txt

- Ensured that It will remove a script from `https://twitch.tv/` and will result in the blocked count to be 1 (testing script blocking)
- Ensured that header is removed in `https://example.com/` (testing cosmetic filtering)

twitch.tv | example.com
-|-
![IMG_2997 2](https://user-images.githubusercontent.com/17885425/234702707-2de1bd34-21fe-4559-8e47-137ce3fe3281.PNG) | ![IMG_2999](https://user-images.githubusercontent.com/17885425/234702652-d08e5f8d-461d-47cd-9b2b-3dcd3190c6cf.PNG)

- Ensured all values return true on test page - https://dev-pages.brave.software/filtering/scriptlets.html
- Ensured all values return true and blocked count is 19 on test page - https://test-pages.privacytests.org/tracking_content.html
- Ensured disabled shields will disable the scripts blocking.

Example | Example | Example | Shields DOWN
-|-|-|-
![IMG_3001 2](https://user-images.githubusercontent.com/17885425/234703802-e9911949-75d7-40c5-92b4-5038d8655100.PNG) | ![IMG_3002 2](https://user-images.githubusercontent.com/17885425/234703833-c5c97ff0-aef4-4209-82cf-88d93132b680.PNG) | ![IMG_3003 2](https://user-images.githubusercontent.com/17885425/234703835-44cadbf8-952b-4280-a446-60e65b5b9d4f.PNG) | ![IMG_3012 3](https://user-images.githubusercontent.com/17885425/234704166-b28dac5b-3f92-4ecc-92c6-e86539363e41.PNG)

_Upgraded Profile_

- Ensured custom filter list URLs can be added and are applied on websites when upgrading from `1.49.1` -> `1.50.x`
- Ensured custom filter list URLs can be added and are applied on websites when upgrading from `1.49.x` -> `1.50.x`
