### ISSUE TITLE
Solana Swap

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6847]
### Description: 

Integrate Solana Swap into existing native swap UI using Jupiter as DEX aggregator

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 16.3.1 running 1.49 (23.3.9.17)
- Verified steps from [#6915](https://github.com/brave/brave-ios/pull/6915)
- Verified able to submit Solana Swap transaction
- Verified transaction is listed under Solana Account Transactions
- Encountered [#7075](https://github.com/brave/brave-ios/issues/7075) & [#7076](https://github.com/brave/brave-browser/issues/36881)


https://user-images.githubusercontent.com/17010094/224312875-4c0ced12-c4c1-46fa-b2c3-299aef49db86.MP4
