### ISSUE TITLE
Remove JitsiSDK framework from production builds.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6849]
This framework is in experimental state and currently exposed to dev and public beta channels only.
We will re-add it once it passes all audits

Test Plan:
- use production build only
- launch BraveTalk and verify that it works, can be a simple test, nothing detailed

**Comment by kjozwiak** [comment]
Closing as https://github.com/brave/brave-ios/pull/6843 has been merged. Should be verifiable once we get new TF builds.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 16.2` using version `1.47 (23.1.30.21)`

Test Plan:

1. Install 1.47 Release channel build from TF
2. Launch BraveTalk
3. Install 1.47 Dev channel build from TF
4. Launch BraveTalk

- Ensured that JitsiSDK is removed from production/release channel builds

Prod Build | Dev Build
-|-
![IMG_4357](https://user-images.githubusercontent.com/17885425/215932582-590ca97a-a3e3-43ec-86e7-28b3d0c66295.PNG) | ![IMG_4358](https://user-images.githubusercontent.com/17885425/215932592-3166f0d4-9196-4139-9d8c-c29a0af555fe.PNG)
