### ISSUE TITLE
Wallet: move IPFS settings to Web3

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6851]
Currently we have an open [PR](https://github.com/brave/brave-ios/pull/6757) for adding IPFS settings. and an open [PR](https://github.com/brave/brave-ios/pull/6844) for renaming `Wallet` settings to `Web3` settings and adding SNS Domain settings.
After these two PRs get merged in, we will need to move IPFS settings under `Web3` as well and become its own IPFS section.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.48 (23.2.7.21)
- Verified test plan from [#6880](https://github.com/brave/brave-ios/pull/6880)
- Verified `Wallet` setting is changed to `Web3` on clean install and post upgrade
- Verified there is no `IPFS` setting in menu
- Verified `IPFS` setting is listed under `Web3`
- Verified able to update `NFT Gateway` 
- Encountered [#6909](https://github.com/brave/brave-ios/issues/6909) on iOS 15

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (16.2)
-- | -- | -- 
<video src=https://user-images.githubusercontent.com/17010094/217600479-73e5a230-251f-4948-a91c-68222672f92c.MP4> | <video src=https://user-images.githubusercontent.com/17010094/217600555-a3695823-3003-4c5c-bb69-0936b5947a65.MP4> | <video src=https://user-images.githubusercontent.com/17010094/217600404-d95e7aa5-d113-4091-9b32-0aa65eca400a.MP4>
