### ISSUE TITLE
Shortcuts and Intent Donations not working

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6856]
### Description: 

Browser Intent actions and donations are not working

### Steps to Reproduce 
  1. Load any website in a new tab
  2. Check INInteraction is giving any error related with Intent definition file

Client Unable to initialize 'OpenWebsiteIntent'. Please make sure that your intent definition file is valid.
Client [Intents] -[INInteraction initWithIntent:response:] No intent was provided in the interaction: <INInteraction: 0x600000cb4f60> {
    intent = <null>;
    intentResponse = <null>;
    intentHandlingStatus = Unspecified;
    
Client [Intents] -[INInteraction donateInteractionWithCompletion:]_block_invoke Cannot donate interaction with (null) that has no valid shortcut types

Client [Brave] Failed to donate shortcut open website, error: Cannot donate interaction with intent that has no valid shortcut types: <INInteraction: 0x600000c88de0> {
    intent = <INIntent: 0x600001a46880> {
    intentResponse = <null>;
    intentHandlingStatus = Unspecified;
} for intent (null)

### Actual result: 

This causes Intent interactions fail and some shortcuts not work at all.

### Expected result:

Intents and shortcuts should work properly

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore?  Yes

### Device details: 
Any

### Website problems only:
- did you check with Brave Shields down? N/A

### Additional Information

The intent definition file is having a problem with target ownership, the PR solving this situation will not need QA testing.

**Comment by soner-yuksel** [comment]
Updated the ticket information with actual problem @iccub @anthonypkeane
