### ISSUE TITLE
No favorite sites in the widget

### ISSUE THREAD

**Issue by A-t-s-u-s-h-i** [brave/brave-ios#6859]
### Description: 
There are several reports that widget doesn’t show any favorite sites. It is hardly reproducible. But the same reports are increasing on Apply AppStore Review little by little.

### Actual result: 
iPhone SE(2nd gen)/iOS16.1.1
![image1 (1)](https://user-images.githubusercontent.com/79502386/216220827-ec6cd264-9b06-456e-945b-8d9c888c2816.png)
![unnamed](https://user-images.githubusercontent.com/79502386/216219095-0e91ef27-a048-447d-99be-3ee92203d9a1.png)

### Expected result:
The widget shows favorite sites.

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Hard to reproduce intentionally.

### Device details: 
I got details from 2 users so far.(But more users have reported)
* iPhone SE(2nd gen)/iOS16.1.1
* Unknown device/iOS16.2

**Comment by Uni-verse** [comment]
Verified using `1.49 (23.3.21.15)` on the following device(s):

`iPhone XR`, `iOS 15.5`
`iPad (7th Gen)`, `iPadOS 16.3.1`
`iPhone 12 Pro`, `iOS 16.4`

- Ensured favorite sites are shown in the widget.
- Ensured that adding new favorites will show up in the widget.
- Ensured upgrading from a previous app version with existing favorites widget is successful and all favorites are kept.

Example | Example
-|-
![IMG_0315](https://user-images.githubusercontent.com/17885425/227250214-f020575c-d4bc-497e-958f-6318d6d072cc.PNG) | ![IMG_1045](https://user-images.githubusercontent.com/17885425/227250218-d2b3ac7c-d3e8-4c0f-a503-f0414e48028e.PNG)
