### ISSUE TITLE
Cookie Blocking Copy

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#686]
When enabling cookie blocking we will present a popup explaining some contextual information about this option and need the following copy:

- Title for the alert
- Information for the alert "Blocking all cookies does ..."
    - This will also reload all of their tabs in some manor
- Error alert copy in case we are unable to activate the setting

**Comment by danishjafri88** [comment]
Additional Info: 
Blocking all cookies will do the following(of which user should be informed):
1. Remove all current session data and reload websites fresh.
2. Block access to `cookies`, `localStorage`, `sessionStorage` etc which may cause problems in some websites. 

Need copy to inform in a more layman terminology. 

How Safari does it:
![img_7637](https://user-images.githubusercontent.com/5398557/50931333-4b1fe500-1488-11e9-842a-d230437e7d77.PNG)

Note that we don't delete cookies, we simply block all access to it. The access to old cookies will be resumed once they disable Block All Cookies.

**Comment by anthonypkeane** [comment]
CC'ing @tomlowenthal to approve

Title: Block all Cookies?
Message: Blocking all Cookies will prevent some websites from working correctly.

Cancel | Block All

**Comment by tildelowengrimm** [comment]
Approved.

**Comment by jhreis** [comment]
Closed per: https://github.com/brave/brave-ios/pull/660
