### ISSUE TITLE
Wallet: Submitted/Completed State after user confirms a transaction 

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6861]
After a user confirms a transaction, add a loading and submitted state
If this user stays at this screen, we will display a completed state when the transaction is completed

<img width="606" alt="Screenshot 2023-02-09 at 4 55 30 PM" src="https://user-images.githubusercontent.com/1187676/217948323-8946f28a-5ebb-465f-a09c-9722ab4ab4be.png">

<img width="405" alt="Screenshot 2023-02-01 at 11 00 29 AM" src="https://user-images.githubusercontent.com/1187676/216388121-5c7518f0-3873-405c-a437-10532d1fabeb.png">

<img width="478" alt="216392209-3a4945e1-7e53-4e80-9d38-61df0c6efb28" src="https://user-images.githubusercontent.com/1187676/216396917-cb2101eb-66ba-4dc6-8db8-4c64c15e462a.png">

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 16.3.1 running 1.49 (23.3.3.16)
- Verified test plan from [#6960](https://github.com/brave/brave-ios/pull/6960)
- Verified `Transaction Submitted` message is shown after a transaction is submitted
- Verified clicking on `View on block explorer` in the transaction submitted loads the block explorer 
- Verified once transaction is confirmed the `Transaction Submitted` message shows option to close or receipt

https://user-images.githubusercontent.com/17010094/223385735-8299d9f9-9308-4b66-b86e-84fd616d5462.MP4
