### ISSUE TITLE
Brave’s action ‘Create PDF’ not working from menu

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6865]
### Description: 

Same issue as https://github.com/brave/brave-ios/issues/4193 but looks like it regressed at some point 

### Steps to Reproduce 
  1. Load a web page
  2. Open the menu and choose Create PDF

### Actual result:
Nothing happens

### Expected result:
PDF share sheet should appear

### Reproduces how often: 
Easily

### Brave Version:
Version 1.46.2 (23.1.10.20)

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 16.2` using version `1.48 (23.2.7.21)`

- Ensured that tapping on `Create PDF` will bring up the shared menu
- Ensured user is able to save the pdf file in device storage

Example | Example
-|-
![IMG_4410](https://user-images.githubusercontent.com/17885425/217921492-e346f1c6-9c70-4a07-bf5f-90d72baa982a.jpg) | ![IMG_4407](https://user-images.githubusercontent.com/17885425/217921489-8b44e772-2708-42e8-ba67-ed74dbf635d2.PNG)
