### ISSUE TITLE
Playlist :: I can't add audio from soundcloud.com to Playlist

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6868]
### Description: 
I can't add audio from soundcloid.com to Playlist

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 16.4` & `iPhone X` running `iOS 16.3.1` using version `1.49 (23.3.31.9)`

- Ensured playlist icon is enabled when playing audio on soundcloud.com

Logged https://github.com/brave/brave-ios/issues/7180 as a follow up

Example | Example | Example
-|-|-
![IMG_4664](https://user-images.githubusercontent.com/17885425/229183969-662af46d-8f76-43c3-bd6d-f2439fc59e70.PNG) | ![IMG_4668](https://user-images.githubusercontent.com/17885425/229184099-47a62d58-45b2-4deb-9311-c847c816f28a.PNG) | ![IMG_4667](https://user-images.githubusercontent.com/17885425/229183987-18a36425-01b9-4527-9609-2905b7a40352.PNG)
