### ISSUE TITLE
Can't re-order bookmarks inside of a folder

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#687]
### Steps to Reproduce 
  1. Make a folder, add few bookmarks into it
  2. Try to move one of the bookmarks

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 
1.7.1

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by LaurenWags** [comment]
@iccub when you say `Try to move one of the bookmarks` - do you mean move a bookmark out of the folder or drag/drop it further up or down a the list of bookmarks?
cc @srirambv

**Comment by srirambv** [comment]
I believe its just sorting of bookmarks inside the folder. I dont think there is option to move in and out of folders. If it is just sorting and rearranging bookmarks inside the folder it works in edit mode.

**Comment by GeetaSarvadnya** [comment]
I don't see any option to move bookmarks into/outside the folder in iPhone 8.

**Comment by iccub** [comment]
@srirambv is correct. Sorry for bad wording. It just did not work when you are inside of a folder, and want to reorder bookmarks there

**Comment by LaurenWags** [comment]
thanks for confirming @iccub ! Just wanted to make sure I was testing correctly.
