### ISSUE TITLE
Night Mode toggle inverts website images colours into negative

### ISSUE THREAD

**Issue by ArturAronov** [brave/brave-ios#6870]
### Description: 
Brave inverts image colours into negative when forcing dark mode into webpage, for website that don't have dark mode. Not all websites with light theme get their image colours inverted into negative. This only happens with Night Mode toggled on.

### Steps to Reproduce 
  1. Toggle Night Mode to On
  2. Visit: https://www.ktls.edu.hk

### Actual result: 
![image](https://user-images.githubusercontent.com/52620016/216504820-60a78a0b-67b3-4875-b1e2-d552951218b6.PNG)

### Expected result:
![image](https://user-images.githubusercontent.com/52620016/216504834-e5861679-143f-4e39-a487-1fbf1e1ab3b3.png)

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Selected websites that don't have light/dark mode toggle

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details: 
iOS version 16.1.1
iPhone Model: 12 Pro
Brave version: 1.46.2
iOS default colour theme: dark

### Website problems only:
- did you check with Brave Shields down? Yes 
- did you check in Safari/Firefox (WkWebView-based browsers)?  Yes

**Comment by iccub** [comment]
I see the same result in Firefox and we share similar logic for applying night mode colors. Probably nothing we can fix unless we improve our scripts significantly, sorry
