### ISSUE TITLE
Back button to NTP is not active/tappable

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6873]
### Description: 

Loading a link from NTP usually makes the back button active allowing you to navigate back to the NTP, this is broken as of  ([latest development](https://github.com/brave/brave-ios/commit/ca22cabb24e92fce4d3c1a64582a6c9c84ca2b65))

### Steps to Reproduce 
  1. Load favorite/Brave news/etc from NTP

### Actual result: 
Cant tap back button

### Expected result:
Should be able to tap back button

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

https://user-images.githubusercontent.com/529104/216664566-46759b06-bd00-4c69-a9f6-8ddc081ef543.mov

**Comment by Uni-verse** [comment]
Verified on `iPhone 12`, `iPad (9th Gen)` running `iOS 16.2`, `iPadOS 15.6.1` respectively using version `1.48 (23.2.10.14)`

- Confirmed back button back to NTP is active and takes user back to NTP

https://user-images.githubusercontent.com/17885425/218555604-2e29c88a-8210-4eb6-b723-5a166d65db9d.MP4
