### ISSUE TITLE
Disable filter lists when shields are off

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#6881]
### Description: 
Right now the filter lists don't get disabled when shields are off. They should be disabled when shields are off

### Steps to Reproduce 
  1. Enable shields and a filter list and go to a site to test its working (could use the block open in app notifications filter list and go to reddit.com to see if the notifications are blocked)
  2. Disable shields
  3. Check if the notifications are blocked.

### Actual result: 
Notifications are blocked

### Expected result:
Notifications should not be blocked

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Every time

### Brave Version: 
1.48

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
![Simulator Screen Shot - iPhone 14 Pro - 2023-02-05 at 12 04 47](https://user-images.githubusercontent.com/909331/216815269-130b53e4-717c-4878-a29b-14ef7c7fa15b.png)

**Comment by Uni-verse** [comment]
Verified on `iPhone 12`, `iOS 16.1` & `iPhone XR`, `iOS 15.5` using app version `1.48 (23.2.15.17)`

Test Scenario  (Based on STR in https://github.com/brave/brave-ios/issues/6881#issue-1571385936)

Precondition: `Fanboy's Mobile Notification` filter enabled

1. Install 1.48
2. Visit `reddit.com`
3. Ensured switch to app notification is not shown
4. Open privacy settings and disable `Block Cross-Site Trackers`
5. Reload `reddit.com`
6. Confirm notification is now displayed
7. Re-enable ad-block in settings
8. Confirm notification is blocked again at `reddit.com` 

Encountered issue: Switch to App setting is not enabled on new profile - https://github.com/brave/brave-ios/issues/6953

https://user-images.githubusercontent.com/17885425/219155869-298fdf37-93aa-4de8-8f66-b469a016976d.MP4
