### ISSUE TITLE
Loading some websites hanging because of a Intermittent error caused by injected scripts

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#6888]
### Description: 

Weird behaviour while loading a webpage where webpage hangs and freezes entire Webview. Please check reproduction steps, videos and additional information section for extra details.

### Steps to Reproduce 

Steps 1: 
  1. Load [twitch.tv](http://twitch.tv/)
  2. Refresh the website
  3. Website hangs - Cant scroll, press cancel or refresh

Steps 2:
  1. Load [twitch.tv](http://twitch.tv/)
  2. After it finishes loading, tap on the URL bar, click on YouTube
  3. Website hangs

### Actual result: 

Website hangs - Cant scroll, press cancel or refresh

https://user-images.githubusercontent.com/6643505/217055115-7207fff2-ff92-4371-89f8-81dfc00b4c61.mp4

https://user-images.githubusercontent.com/6643505/217055137-c196ecfd-2d7f-49aa-835c-e0c97e273112.mov

### Expected result:

No infinite loads or hangs on the website- loads properly 

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Intermittent Issue however If you can’t reproduce try deleting app/resetting iOS sim (Device > Erase all contents & settings) before trying

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight?  Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
N/A however the tests are being done using a iPhone iOS 16.3 and simulator 16.2

### Website problems only:
- did you check with Brave Shields down? Disabling adblock shield (cross-site trackers) fixes the problem
- did you check in Safari/Firefox (WkWebView-based browsers)? Yes, obviously this doesnt happen in other browsers but at this context it is not applicable. 

### Additional Information

<img width="904" alt="image (7)" src="https://user-images.githubusercontent.com/6643505/217055062-e1fe8305-878d-454f-a00e-dc0511b65595.png">

This can be reproduced reliably on simulator / device. Logs in Safari are showing “kek” logs repeat recursively and the number of kekFinity increases continuously and tab loses it capability of refresh and stop.

So according to the tests performed the problem is being suspected in RequestBlocking script however it is not 100 percent.

When the website successfully loads once, this will not happen again because WebKit is probably caching state of current webview.

So after getting the error If Block Cross Site trackers are disabled, the problem might stop.

<img width="358" alt="image (8)" src="https://user-images.githubusercontent.com/6643505/217056588-48a5557e-f210-4635-bebe-d77bbf3310f8.png">

To reproduce as mentioned above Erase All content should be invoked in simulator, while testing is being done on simulator.

This is a very likely the CAUSE and CULPRIT for external links is causing application to freeze in black screen. It has been reproduced while doing tests related the problem.

![1](https://user-images.githubusercontent.com/6643505/217060997-cfd98089-60c3-4937-9fbd-a5d4b950f6a4.png)

cc @cuba @brave/ios @kjozwiak @Uni-verse

**Comment by Uni-verse** [comment]
Verified on `iPhone 12`, `iOS 16.1` & `iPad (9th Gen),` `IPadOS 15.6.1` using version `1.48 (23.2.22.16)`

- Reproduced issue by visiting `https://twitch.tv` using version `1.48 (23.2.21.21)`

https://user-images.githubusercontent.com/17885425/220775008-2cd45bca-9c33-4e4e-84f5-69519e91c188.MP4

- Upgraded to `1.48 (23.2.22.16)`
- Ensured that twitch.tv was loading successfully 
- Ensured refreshing tab reloads the page successfully
- Ensured opening a new tab and loading another webpage like youtube.com does not hang or freeze based on STR in https://github.com/brave/brave-ios/issues/6888#issue-1573090995
- Ensured loading twitch.tv does not hang on a new profile/fresh install

https://user-images.githubusercontent.com/17885425/220776067-946c75d5-d484-4e74-a419-b543ec61fba8.MP4
