### ISSUE TITLE
Wallet: Add support for Transak provider 

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#6890]
in order of 
1. ramp.network
2. sardine
3. transak

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.48 (23.2.7.21)
- Verified steps from [ #6891](https://github.com/brave/brave-ios/pull/6891)
- Verified the purchase options are in the order `Ramp` , `Sardine`, `Transak`
- Verified `Sardine is only shown for US locale and for supported tokens only

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (16.2)
-- | -- | -- 
<video src=https://user-images.githubusercontent.com/17010094/217871907-985c7f01-426b-4b67-a8a5-8d1db0c97fe9.MP4> | <video src=https://user-images.githubusercontent.com/17010094/217887701-9705b2e4-8269-4c9f-9dfd-ff00d4ed0059.MP4> | <video src=https://user-images.githubusercontent.com/17010094/217887547-ccbd6861-9457-4af0-9d78-6e6336423470.MP4>
