### ISSUE TITLE
EIP712Domain data should be displayed

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6892]
### Description: 

iOS version of https://github.com/brave/brave-browser/issues/28048

cc @kdenhartog

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 15.7.1 running 1.48 (23.2.22.16)
- Verified steps from [#6911](https://github.com/brave/brave-ios/pull/6911)
- Verified EIP712 domain data is shown in sign transaction confirmation screen

https://user-images.githubusercontent.com/17010094/220708943-6baa66a5-e868-4e30-85de-152a2970e0d6.MP4
