### ISSUE TITLE
Solana QR codes are not supported for send

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-ios#6896]
### Description: 
Solana QR codes are not supported for send.

### Steps to Reproduce 
  1. Login wallet
  2. Open send
  3. Scan a brave Solana account QR code

### Expected result:
Should get the Solana account address

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

### Additional Information
https://bravesoftware.slack.com/archives/C02S9LFEXU4/p1675775224948849?thread_ts=1675449869.032959&cid=C02S9LFEXU4

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.48 (23.2.15.17)
- Verified steps from [#6922](https://github.com/brave/brave-ios/pull/6922)
- Verified scanning the QR code shows the correct Solana Address
- Verified `solana:` prefix is not shown and address does not display as invalid SOL address.

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (16.2)
-- | -- | -- 
<video src=https://user-images.githubusercontent.com/17010094/219381999-e04f5acc-e2a6-4bf0-9067-5d960a9a5615.MP4> | <video src=https://user-images.githubusercontent.com/17010094/219382077-e3ba6c77-148a-4b22-90db-63a9d71d3dd0.mov> | <video src=https://user-images.githubusercontent.com/17010094/219382162-092b460d-e570-4101-83ec-472928c7a35d.MP4>
