### ISSUE TITLE
App Storage debug info

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6905]
Look for "App Storage debug info for iOS users mini spec" in gdrive

**Comment by Uni-verse** [comment]
Verified on version `1.48 (23.2.13.20)` using the following device(s):

iPhone 12, iOS 16.1
iPad (7th Gen), iPadOS 16.1
iPad (9th Gen), iPadOS 15.6.1
iPhone X, iOS 14.4.2

- Verified that iOS version, app version and file struction is included when tapping on `Copy app size info to clipboard`

```
Setup: iPad, iPadOS 16.1, Brave 1.48
Library(47.3 MB)
	Caches(1.3 MB)
	WebKit(4.7 MB)
		ContentRuleLists(4.2 MB)
	SplashBoard(11.2 MB)
		Snapshots(11.2 MB)
			sceneID:com.brave.ios.browser-default(11.2 MB)
	Application Support(30.1 MB)
		cmf-data(3.1 MB)
		Chromium(25.3 MB)
			BraveWallet(7.5 MB)
			BrowserMetrics(9.3 MB)
			cffkpbalmllkdoenhmdmpbkajipdjfam(3.4 MB)

```
Example | Example
-|-
![IMG_4491](https://user-images.githubusercontent.com/17885425/218895454-87a513b8-83ce-4d43-ac79-d1c3f82a3501.PNG) | ![IMG_0994](https://user-images.githubusercontent.com/17885425/218895487-f8be05a4-a5b5-4659-bc38-077295d723a0.PNG)
