### ISSUE TITLE
HTTPSE upgrade count not shown on shields

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#691]
### Description: 
HTTPSE upgrade count not shown on shields

### Steps to Reproduce 
  1.Visit https://https-everywhere.badssl.com/
  2. Open shields
  3. HTTPS shows count as 0 

**Actual result:** 
![file 1](https://user-images.githubusercontent.com/17010094/50960034-6f141280-14ea-11e9-94d7-c442a2d617df.jpg)

**Expected result:**
Shields should show  count 1 for HTTPSE

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7.3 (19.1.09.19)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? 
N/A

**Comment by srirambv** [comment]
The stats for HTTPSE on new tab also remains 0.

**Comment by kylehickinson** [comment]
The stats will not increase if you're visiting an already upgraded website (STR step 1 says visit **https**://https-everywhere.badssl.com)

I reproduced visiting http variant as well, fixing

**Comment by srirambv** [comment]
@kylehickinson Not really. Its supposed to update. This is the behaviour on desktop
![https](https://user-images.githubusercontent.com/17010094/51042259-da8cdb80-15e1-11e9-8ea2-e67db64451f7.gif)

**Comment by kylehickinson** [comment]
Desktop only seems to do that the first time you visit the website and only when you are scheme-less. If I load `badssl.com` it increase the stat, if I load `https://badssl.com` it doesn't.
