### ISSUE TITLE
Please update the default search provider list for South Korea

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6912]
### Description: 
Per: https://github.com/brave/brave-browser/issues/18855

Please add the follow search engines for South Korea and update the default. 

Naver & Daum

Please make Naver the default for new users. 

**Naver**
![210639164-f38566f9-87a0-48a2-98df-50f148eea080](https://user-images.githubusercontent.com/7606853/217667063-19b5e351-662a-4b7a-a9a4-04d8eb43e2c3.svg)

**Daum**
![210812848-9275a614-cee8-4429-af99-b56be70a483f](https://user-images.githubusercontent.com/7606853/217666841-4c1ae490-6354-4507-8be7-a814ccfddbaa.svg)

**Comment by anthonypkeane** [comment]
@iccub can we line this up in 1.53, it is live on Android/Desktop now. Thanks

**Comment by iccub** [comment]
sure

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5.1]
Brave build: 1.56 (23.7.19.18)
BraveCore: 1.56.6 (115.0.5790.90)
```
---------------------------
<details>
<summary> New user flow - PASS </summary>

**STEPS:**
1. Change Region to South Korea in device settings
2. Fresh install and then launch Brave 
3. Three-dot menu > Settings > Search Engines > Verify
4. Open `Standard Tab` > Verify
5. Go back and open `Private Tab` > Verify
6. Go back and open NTP > Make a search request > Verify
7. Repeat the same for `Private Tab` > Verify

**ACTUAL RESULTS:**
- Verified that `Naver` and `Daum` SE were added to the South Korean region
- Verified that default SE for South Koria is set to `Naver` for both `Standard Tab` and `Private Tab`
- Verified that search results are shown with the correct SE
- Verified that `Naver` and `Daum` avatar icons are shown in the keyboard's `search bar`

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/236fcc23-3b46-43e9-a9dc-2df537f0abc2) | ![2](https://github.com/brave/brave-ios/assets/128532965/145df682-b78e-49fe-bba6-35511113bd56) | ![3](https://github.com/brave/brave-ios/assets/128532965/5805df3a-df2f-4bc0-b9fd-ec5d21dd3aa4) | ![4](https://github.com/brave/brave-ios/assets/128532965/b1a3215b-c220-448a-b08c-51658a05dd68) |

https://github.com/brave/brave-ios/assets/128532965/5263101c-f0ff-416c-80a3-471d221f4542
</details>

<details>
<summary> Upgraded user flow - PASS </summary>

**STEPS:**
1. Change Region to South Korea in device settings
2. Have `Brave 1.52` installed on a device > Confirm that there are no `Naver` or `Daum` SE in Brave settings
3. Upgrade to `Brave 1.56` and then launch the app 
4. Three-dot menu > Settings > Search Engines > Verify
5. Open `Standard Tab` > Verify
6. Go back and open `Private Tab` > Verify
7. Go back and open NTP > Make a search request > Verify
8. Repeat the same for `Private Tab` > Verify

**ACTUAL RESULTS:**
- Verified that `Naver` and `Daum` SE were added to the South Korean region
- Verified that default SE for South Koria is set to `Naver` for both `Standard Tab` and `Private Tab`
- Verified that search results are shown with the correct SE
- Verified that `Naver` and `Daum` avatar icons are shown in the keyboard's `search bar`

---------------------------

https://github.com/brave/brave-ios/assets/128532965/2ce9bc38-e799-46aa-ba42-7c392eeccab8
</details>
