### ISSUE TITLE
Brave is the worst browser when Night Mode On

### ISSUE THREAD

**Issue by NaaeemMalik** [brave/brave-ios#6913]
### Description: 
It can't show images properly, it can't play videos 
Look how the images look 
![image](https://user-images.githubusercontent.com/35663485/217776505-863ab3cd-6ff8-4031-ba69-0c15b2b9d99b.png)

Clicking on videos play button on many sites doesn't do anything 

### Steps to Reproduce 
  1. Go to any site that shows images or movies eg https://thewarroom.ag
  2.see 

### Expected result:
Show images and play videos 

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always on many sites 

### Brave Version: 
Downloaded from App Store 1.46.2
Production level issue, have been facing since so long 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details: 
iPhone 11 Pro Max
iOS 16.2 

### Website problems only:
![image](https://user-images.githubusercontent.com/35663485/217779770-0030822f-cead-48fd-b911-83dc4d68b31d.png)
https://bannety.monster/movies/play/5884796-plane-2023

- did you check with Brave Shields down? Up
- did you check in Safari/Firefox (WkWebView-based browsers)? 
Safari and chrome also don't play this video but shows images properly 
### Random Tags
@fmarier @Brandon-T @szilardszaloki @iccub

**Comment by Brandon-T** [comment]
The videos play for me. Do you happen to have any specific shields on, on the website? Can you try turning off shields and let us know if it plays?

![image](https://user-images.githubusercontent.com/1530031/217835119-e09991ad-a646-4750-aad0-345cd7a39a70.png)

![image](https://user-images.githubusercontent.com/1530031/217835005-7ade3fe2-3baf-47be-9459-51fd9bbd67a6.png)

![image](https://user-images.githubusercontent.com/1530031/217835070-318240dc-c165-4449-81ae-57114a7492a1.png)

**Comment by NaaeemMalik** [comment]
problem is with Plane 2023 not this movie, all browsers on my phone cant play that video, so turning of shields isnt gonna do anything 

plus images on almost all pages dont show properly, they show as black and white , this images issue is only in Brave not on any other browser

**Comment by kylehickinson** [comment]
@NaaeemMalik It looks like you have Night Mode on which inverses colours, try turning that off in Settings > Appearance

**Comment by NaaeemMalik** [comment]
yes, now everything works, it showing images and also playing Plane movie, Thankyou so much, its my default browser and couldnt switch it otherwise I would have, browser looks batter with night mode then the dark more though , I thought it was in light mode when I saw Night mode off , didnt know the difference.

Thankyou so much, its the best browser on iOS

**Comment by NaaeemMalik** [comment]
if it has sync functionality with Brave on other OS same like Chrome and Safari, its gonna be unstoppable , current Sync doesnt do anything useful

**Comment by kylehickinson** [comment]
Thanks @NaaeemMalik, we do have Sync (Settings > Sync), we currently sync bookmarks, history, passwords and open tabs at the moment and have plans for more sync types in the future.

We're going to close this for now but we'll look to improve night mode in the future including seeing if we can not invert images.

**Comment by NaaeemMalik** [comment]
Maybe you can put some information or alert about this night mode functionality when you turn it on to demotivate people that it's not same as dark mode, also inverting images isnt useful bcz you can then see more white then you see otherwise. but it also breaks videos.

I had to reinstall windows and now all my history and bookmarks is gone bcz apparently browser is needed to remain open when sync is happening so it's not same as chrome, I can trust chrome and safari that wherever I go I can access everything, or share urls to my other devices.

chrome stores passwords in plain text (I am sure about on windows) does brave also do that being a privacy browser
