### ISSUE TITLE
Asset loading spinner is not visible 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#6929]
### Description: 
Asset loading spinner is not visible 

### Steps to Reproduce 
  1. Import an account which has asset balance 
  2. Wait for asset auto-discovery 
  3. Loading spinner is not shown 

### Actual result: 

https://user-images.githubusercontent.com/17010094/218433794-afd32708-914d-400d-805e-335efcc2cbbe.MP4

### Expected result:
Should show icon

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 
iPhone XR (iOS 15.7.1)

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @StephenHeaps @nuo-xu

**Comment by StephenHeaps** [comment]
Could you re-test this with 'Network Link Conditioner' active to slow down your network? I see the spinner when I first load in, but core is caching the last fetched block which causes it to load 0 assets immediately next request (second launch in this video).

'Network Link Conditioner' is [also available on device (if developer mode enabled)](https://nshipster.com/network-link-conditioner/#enabling-network-link-conditioner-on-ios-devices) in Settings.app -> Developer -> Network Link Conditioner

https://user-images.githubusercontent.com/5314553/218488444-3bc411d2-0194-4bea-851e-08ecf915e6d6.mov
