### ISSUE TITLE
Bottom address bar is showing on iPads

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6939]
### Steps to Reproduce 
  1. Install 1.46 on iPad
  2. Upgrade to 1.47
  3. Verify that no bottom url bar promo is showing

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)`, `iPadOS 16.2` & `iPad (7th Gen)`, `iPad 15.6.1` using version `1.48 (23.2.13.20)`

Steps to Reproduce

1. Install 1.46 on iPad
2. Upgrade to 1.47/1.48
3. Verify that no bottom url bar promo is showing

- Ensured bottom url promo is not shown on iPad when upgrading version.

https://user-images.githubusercontent.com/17885425/218893881-c6487ee4-6374-4a77-af6d-85ff29779a9f.MP4
