### ISSUE TITLE
Websites that lack a favicon.ico are stored in core-data, which means they will override the icons on top-sites

### ISSUE THREAD

**Issue by nadav-bar-lev** [brave/brave-ios#6946]
### Description: 
Why websites that lack a favicon.ico are stored in core-data?
And why you preferred the favicon saved on core-data on the bundled icons (top-sites)?
That cause that if i define a new site (that lack of favicon.ico) on the top-sites, when i navigate to this site, you are saving the favicon data (without the image) on the core-data and the bundled icons have no effects anymore.

### Steps to Reproduce 
  1. Add https://talon-sec.com/ to top-sites.json file
  2. Add it to the preload-favorites list (in appendPopularEnglishWebsites() function)
  3. Open the NTP and click on Talon icon. (on this step, you save the favicon on core-data, although there is no image in /favicon.ico)
  4. Open the NTP again - the Talon icon is the default one (T letter) instead the image in the top-sites.

**Comment by Brandon-T** [comment]
In `v1.48.x`, Favicons are no longer used from `CoreData`.
This issue should already be fixed. 
I verified that the favicons from websites that have none, are not stored in the cache and will fallback to the bundled icons.

Also, that website has a favicon: 
![image](https://user-images.githubusercontent.com/1530031/219113780-cdb53936-7753-481d-9b38-00b2c8d07f35.png)

If this is still an issue, please re-open the ticket and assign it to me and leave a comment. I will take a further look.

**Comment by nadav-bar-lev** [comment]
Thank you @Brandon-T
Yeah, I'm currently using version 1.47. 
Would you mind sharing which commit resolved this issue please?

**Comment by Brandon-T** [comment]
Hi @nadav-bar-lev,
It was changed in: https://github.com/brave/brave-ios/commit/f28dfeae5c19f3581dcfe6ed8423f767ae95b2c9 and improved further in: https://github.com/brave/brave-ios/pull/6950/commits/2fcd59096eac8bd774875f4630bc53f8bde5e5f9
