### ISSUE TITLE
BrowserMetrics folder increases in size every app launch

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6948]
### Description: 

Due to a Chromium bump, a bug is occuring where every time the app launches a 4.2MB file in the `Application Support/Chromium/BrowserMetrics` folder.

### Steps to Reproduce 
  1. Launch the app a couple of times
  2. View Sandbox Inspector in the debug settings

### Actual result: 
BrowserMetrics folder will contain many files looking like `BrowserMetrics-{id}.pma`

### Expected result:
The BrowserMetrics folder should not exist or at most contain 1-2 files

### Reproduces how often:
Easily

### Brave Version: 
First noticed in early 1.48 builds, not sure which Chromium bump caused the bug but it could be the reason for large app size spikes we've been seeing in 1.47 reviews

**Comment by kylehickinson** [comment]
Closed by #6947

**Comment by Uni-verse** [comment]
Verified on `iPhone 12`, `iOS 16.1` & `iPad (9th Gen),` `iPadOS 15.6.1` using version `1.48 (23.2.16.18)`

**Test Scenario:**
 
1. Launched app 3 times
2. Viewed Sandbox Inspector in the debug settings

- Ensured that app size does not increase after each launch
- Ensured that BrowserMetrics folder is not present under `Application Support/Chromium/`

1st Launch | 2nd Launch | 3rd Launch | Folders
-|-|-|-
![IMG_4524](https://user-images.githubusercontent.com/17885425/219797261-6c977d6a-f9b3-4041-aac7-295bac78dea0.PNG) | ![IMG_4525](https://user-images.githubusercontent.com/17885425/219797268-4fb8aea9-d1d6-4153-9334-78c6df45d708.PNG) | ![IMG_4526](https://user-images.githubusercontent.com/17885425/219797271-fe69f65c-2c9c-4f65-964c-8a536e19f8bd.PNG) | ![IMG_4527](https://user-images.githubusercontent.com/17885425/219797274-22bb9441-0c8e-4681-a9bc-1750f8878297.PNG)
![IMG_0135 2](https://user-images.githubusercontent.com/17885425/219797332-b2ae5743-6731-4460-b9b5-7a656801fc27.PNG) | ![IMG_0136 2](https://user-images.githubusercontent.com/17885425/219797343-6d72938f-dc24-472f-a39a-b319faf72846.PNG) | ![IMG_0137](https://user-images.githubusercontent.com/17885425/219797358-9bb2d52c-5f77-44e9-a81c-883a14181654.PNG) | ![IMG_0138 2](https://user-images.githubusercontent.com/17885425/219797366-30eda5a7-7d42-4345-8a4f-e1e1b7e6edc0.PNG)
