### ISSUE TITLE
Delete bookmarks crash

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6949]
<img width="799" alt="Zrzut ekranu 2023-02-15 o 17 01 12" src="https://user-images.githubusercontent.com/6950387/219082429-d9e134da-6d3b-4cf1-a406-1b261883c3a0.png">

**Comment by Uni-verse** [comment]
Verified on `iPhone 12`, `iOS 16.1` & `iPad (9th Gen)`, `iPadOS 15.6.1` using version `1.48 (23.2.16.18)`

Test Plan: 

1. Reproduced crash upon bookmark deletion using voiceover on `1.48 (23.2.13.20)`
2. Installed `1.48 (23.2.16.18)`
3. Created some bookmarks
4. Enabled voiceover
5. Open bookmarks tab

- Ensured bookmark is able to be deleted using voiceover 

<table><tr><td>

https://user-images.githubusercontent.com/17885425/219523146-7c1d16df-c18f-4ba6-9c8a-6dc083723f52.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/219523650-911c2c01-cfaa-485f-ab40-16faa29a0d23.mov

</td></tr></table>
