### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#695]
All tasks related to Brave Sync functionality.

**Comment by willstocks** [comment]
@iccub - do you happen to know if there's a "firm" or "semi-firm" deadline for this feature to hit completion, or even beta?

Looks like quite a few unhappy users here: https://community.brave.com/t/brave-sync-for-ios/8368 and by the looks of it, they just want to know if/when they can expect to see the feature as it has been promised over the course of ~2 years now.

Looking forward to going all-in on Brave 😁

**Comment by iccub** [comment]
Hi @willstocks-tech, the official deadline was to ship it around end of February but we've got some delays unfortunately.

The plan now is to land Sync in Brave 1.9. There are two major features coming to 1.9:
1. Sync
2. Additional regional adblocking filters

Sync is a priority now for us, we are currently preparing a new build for QA to test.
QA already did like two rounds of testing it so I hope there's not much more bugs left to be found :)

I have personally tested iOS-iOS bookmark sync on my development builds and for me it is in a pretty good shape. 

First release of Sync will be most likely labeled as beta(same as on desktop and Android)

Thanks for linking the community thread, I will post it there too

**Comment by willstocks** [comment]
That's great news, thanks @iccub!! 

And yes, it's definitely worth putting an update in that thread - I think it will put a lot of the angrier minds at ease knowing that it's due soon, even if still in beta form!

**Comment by jhreis** [comment]
Closing this epic, as no longer using Zenhub.
