### ISSUE TITLE
ERC721 NFTs with different token identifiers may show incorrect balance

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6954]
### Description: 

On Portfolio, the balance calculations are not taking into account the token id so two ERC721 NFTs from the same collection (same contract address) but with different token ids might report the same balance

ref: https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1676555545832879

### Steps to Reproduce 
pre-requisite: Own 1 ERC721 NFT that belongs to a collection with an NFT you don't own. Same contract address, symbol and chain but different token id.
1. Add 2 ERC721 NFTs with same contract address, symbol and chain but different token ids (you must have a different balance for the two NFTs)
    e.g. [NFT1](https://testnets.opensea.io/assets/goerli/0xef6cdea5845c5ce10a533bd20fdfe9b174ab1687/9) and [NFT2](https://testnets.opensea.io/assets/goerli/0xef6cdea5845c5ce10a533bd20fdfe9b174ab1687/4)
2. Observe balance is displayed the same for both, despite only owning one.

h/t @Pavneet-Sing

**Comment by Pavneet-Sing** [comment]
I think the steps to produce this issue on iOS would be:

   1. Buy two NFTs with same contract addressed and symbol. e.g.  [NFT1](https://testnets.opensea.io/assets/goerli/0xef6cdea5845c5ce10a533bd20fdfe9b174ab1687/9) and [NFT2](https://testnets.opensea.io/assets/goerli/0xef6cdea5845c5ce10a533bd20fdfe9b174ab1687/4)
   2. Make sure the balance is accurate on Portfolio screen

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.49 (23.3.3.16)
- Verified steps from [#6983](https://github.com/brave/brave-ios/pull/6983)
- Verified correct balance is shown for NFT's with the same contract address but with different token id's

iPhone XR (iOS 16.3.1) | iPad Pro (iOS 16.4 Beta 2)
-- |--
<video src=https://user-images.githubusercontent.com/17010094/223710123-d28488de-92ba-44f5-8bbf-5b0c199c29e2.MP4> | <video src=https://user-images.githubusercontent.com/17010094/223710056-efb299a5-0eca-4f6a-b22f-416a1bd9d824.MP4>
