### ISSUE TITLE
Incorrect text color in dark mode for Sign Message

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6956]
### Description: 

Incorrect text colour in sign message after adding bolding to domain/message title

### Steps to Reproduce 
1. Visit https://brandon-t.github.io/test-dapp-eip-712/ test site
2. Connect and tap Sign under Sign Typed Data V4
3. Switch to dark mode and observe incorrect text color / hard to read message

### Actual result: 

![Simulator Screen Shot - iPhone 14 Pro - 2023-02-16 at 09 49 03](https://user-images.githubusercontent.com/5314553/219397814-bc8dcda1-f42e-4e4e-90b3-30d44b64b2ae.png)

Found by @srirambv testing https://github.com/brave/brave-ios/issues/6892

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.
- Verified steps from [#6955](https://github.com/brave/brave-ios/pull/6955)
- Verified text colour is shown correctly based on browser/device theme

iPhone 7+ (iOS 14.8.1) | iPhone XR (iOS 15.7.1) | iPad Pro (16.2)
-- | -- | -- 
<img width=300 src=https://user-images.githubusercontent.com/17010094/219622602-eda86c09-fbc9-4eba-a85c-1304ceb7217a.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/219622339-c6c900c4-1311-47bb-bcab-330c35dd592f.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/219622488-b7ba232f-26ec-4be7-a485-9be1ee1bc846.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/219622542-053ebab8-d3b4-4188-9d72-644d3bc095c1.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/219622372-3294cf81-cae3-4c98-8416-2b0d5033ac92.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/219622444-fabd7474-fb6f-413d-89a7-3374c3b6c494.png>
