### ISSUE TITLE
Decide and implement how to deal with duplicated Bookmarks.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#696]
### Steps to Reproduce 
  1. Join two devices into a sync group.
  2. Add Wikipedia bookmark on device A
  3. Add the same url Wikipedia bookmark on device B

**Actual result:** 
We need to decide how to handle this case, currently it is not handled at all

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by anthonypkeane** [comment]
The Spec for Sync states that we don't handle duplicates. 
If a user has www.brave.com on their iPhone and Mac and syncs, they will end up with 2 www.brave.com's

**Comment by iccub** [comment]
Thanks for clarification @anthonypkeane

**Comment by iccub** [comment]
Per convo from here https://github.com/brave/brave-ios/pull/667#discussion_r249128518
We don't need to do any additional work to support bookmark duplicates. Closing.
