### ISSUE TITLE
Shields panel url should show origin only, not full url

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#6964]
### Steps to Reproduce 
  1. Go to some wikipedia article
  2. Open shields panel

### Actual result: 
Full url shows

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.49 (23.3.15.17)
- Verified steps from [ #7042](https://github.com/brave/brave-ios/pull/7042)
- Verified only the origin name is shown and not the full URL

iPhone 7+ (iOS 15.7.3) | iPhone XR (iOS 16.3.1) | iPad Pro (16.4 Beta 2)
-- | -- | -- 
<img width=300 src=https://user-images.githubusercontent.com/17010094/225571268-485e4932-0b0b-473f-9f1f-bdab43652968.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/225571302-3ae2d4ec-4834-4e77-a422-e292776ebc17.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/225571206-9c2cdd4d-60e1-4c1c-9e92-f03358bff53b.png>
