### ISSUE TITLE
Unable to add custom network via panel prompt

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#6965]
### Description: 
Unable to add custom network via panel prompt

### Steps to Reproduce 
  1. Visit `https://chainlist.org`
  2. Select a network and try to add
  3. Approve prompt shows up twice but never adds the network to the list. For some network it keeps prompting and never adds it

### Actual result: 

https://user-images.githubusercontent.com/17010094/219615961-f43ed1c0-918f-4be0-8328-2d7376bcaae8.MP4

### Expected result:
Should be able to add a custom network

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
All devices

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by StephenHeaps** [comment]
It looks like adding `Astar` network from chainlist.org fails, it does not add the network on desktop either ('Approve' button doesn't work) 🤔. I need to investigate a bit more here. cc @darkdh. Edit: This occurs when the RPC calls for the network fail; we don't add the network.

For some other networks I have tested there does seem to be an iOS bug here that causes 'Add Network' to be shown a second time after you approve it once. The second time this view appears, you can tap 'Cancel' or 'Approve' to get around this bug, after which 'Switch Network' will be shown correctly. I am investigating a fix for this.

https://user-images.githubusercontent.com/5314553/219811105-d5543c08-5191-47e6-942f-79b18d4b8fd8.mov

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.49 (23.3.9.17)
- Verified steps from [#7047](https://github.com/brave/brave-ios/pull/7047)
- Verified adding a custom token works as expected
- Verified trying to add `Astar` network fails and shows error message
- Encountered [#7074](https://github.com/brave/brave-ios/issues/7074) for iOS 16 Beta 

iPhone 7+ (iOS 15.7.3) | iPhone XR (iOS 16.3.1)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/224280596-26c3826b-6dd9-4adc-94e4-6743e10881e0.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/224280540-59d4aee6-358a-4e34-ba50-4b850a3c5163.png>
