### ISSUE TITLE
Google Oauth window does not autoclose after success

### ISSUE THREAD

**Issue by paymog** [brave/brave-ios#6966]
### Description: 

I recently implemented Google Oauth on my website with popup behavior. However, since popup is not supported on mobile, a new tab is opened to go through the oauth flow. After the flow succeeds, Brave iOS does not autoclose the tab. However, Safari does autoclose the tab. This behavior persists even with shields turned off for accounts.google.com which is the domain that does the oauth.

### Steps to Reproduce 
  1. Visit https://lookielooapp.com/signup on Brave iOS
  2. Try signing in with google
  3. See new tab open up and then seemingly hang
  4. go back to the Lookieloo tab
  5. see that you're logged in
  6. try the flow with Safari/chrome

### Actual result: 

The Oauth consent flow seems to hang indefinitely

![image](https://user-images.githubusercontent.com/1986950/219699532-74fb01c3-091a-44a3-8742-d5f53be41d4e.png)

Even though the actual application successfully logs in

![image](https://user-images.githubusercontent.com/1986950/219699587-1f9bb93d-5660-49ed-bd03-94013bf78b08.png)

### Expected result:

I expect brave to autoclose the tab after success, just like chrome and safari.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Always

### Brave Version: 

Version 1.47 (23.2.1.14)
BraveCore 1.47.189 (109.0.5414.119)
Device iPhone14,5 (iOS 16.2)

- Can you reproduce this issue with the most recent build from TestFlight? didn't try
- Can you reproduce this issue with the previous version of the current build from TestFlight? didn't try
- Can you reproduce this issue with the current build from AppStore? I'm up to date according to the app store

### Device details: 

Device iPhone14,5 (iOS 16.2)

### Website problems only:
- did you check with Brave Shields down? yes
- did you check in Safari/Firefox (WkWebView-based browsers)?  yes

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 [iOS 16.6]
- iPad Air [iPadOS 16.5]
Brave build: 1.57 (23.8.16.21)
BraveCore: 1.57.47 (116.0.5845.96)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Open https://lookielooapp.com/signup or https://tunein.com
3. Sign up/Sign in with Google
4. Enter login credentials > Verify

**ACTUAL RESULTS:**
- Verified that Sign up/Sign in with Google is working
- Verified that blank page is self-closed after sign-in is done

---------------------------

*iPhone*

https://github.com/brave/brave-ios/assets/128532965/04d405a7-ab58-46cc-81b1-73081dc8c0b1

*iPad*

https://github.com/brave/brave-ios/assets/128532965/6fbab7c3-c9d0-4987-8345-e357c14e8804
