### ISSUE TITLE
Playlist :: Moving from portrait to landscape changes the video position 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#6971]
### Description: 
I found that moving from portrait to landscape changes the video last played position. Easier to reproduce for long videos.

**Comment by hkarmoush** [comment]
I was not able to reproduce this, could you please specify the steps to reproduce

**Comment by iccub** [comment]
we may close for our QA team to retest if this can't be reproduced

**Comment by Uni-verse** [comment]
@Uni-verse QA to check if reproducible

**Comment by Uni-verse** [comment]
Not reproduced on `iPad (9th Gen)` running `iPadOS 15.6.1` & `iPhone X` running `iOS 16.3.1` using version `1.51 (23.4.28.18)` 

- Confirmed moving from portrait to landscape does not change the video position. 

<table><tr><td>short video</td><td>long video</td><td>iPhone</td></tr>

<tr><td>

https://user-images.githubusercontent.com/17885425/236260840-c4e5f5cb-ec35-477e-b155-4f043732df5d.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/236260888-6d647c01-91a5-4fea-88c5-6c4ede3dc002.MP4

</td><td>

https://user-images.githubusercontent.com/17885425/236276227-731d6fa7-ec5a-4135-b3bb-eee4e6fdab81.MP4

</td></tr></table>
