### ISSUE TITLE
Browser Crashes when visiting specific website(s)

### ISSUE THREAD

**Issue by elgertam** [brave/brave-ios#6974]
### Description: 
My iOS-based Brave browser crashes when I visit https://localfirstweb.dev/.

### Steps to Reproduce 
  1. Open Brave browser on iOS
  2. Visit https://localfirstweb.dev/

### Actual result:

Brave crashes

### Expected result:

A webpage loads

### Brave Version: Version 1.47 (23.2.1.14) BraveCore 1.47.189 (109.0.5414.119)

- Can you reproduce this issue with the most recent build from TestFlight? Haven't tried the TestFlight build
- Can you reproduce this issue with the previous version of the current build from TestFlight? See above
- Can you reproduce this issue with the current build from AppStore? Yes

### Website problems only:
- did you check with Brave Shields down? Crashed before I could turn shields off
- did you check in Safari/Firefox (WkWebView-based browsers)? Yes (Safari)

### Additional Information
This is corroborated by commenters on Hacker News https://news.ycombinator.com/item?id=34858718.

**Comment by kylehickinson** [comment]
Tested with 1.48 and looks like its already fixed there by #5970

1.48 will be released in the next few weeks
