### ISSUE TITLE
Auto-complete adding custom Solana asset(s)

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#6982]
### Description: 

Entering a token mint address when adding a Solana custom asset should auto-complete the fields when possible.

ex. USD Coin with mint address `EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v`

https://user-images.githubusercontent.com/5314553/220676638-b0cf5c35-705d-4582-a5ec-9fb6a9e505c8.mp4

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.
- Verified steps from [#6990](https://github.com/brave/brave-ios/pull/6990)
- Verified adding custom Solana tokens automatically fills in the details when address is pasted in
- Verified able to still add Ethereum address and auto-complete the token details

iPhone XR (iOS 15.7.1) | iPad Pro (16.4 Beta 2)
-- | -- 
<video src=https://user-images.githubusercontent.com/17010094/223098049-d3e8c0ed-6c72-4a39-8329-7753b0b1dcde.mov> | <video src=https://user-images.githubusercontent.com/17010094/223097987-19472c7e-c991-429b-adc9-0b9e68123d37.MP4>
