### ISSUE TITLE
Spoof referer headers by default

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#699]
Referer headers can be used to track users. Spoof the headers to the requesting url.

**Comment by kylehickinson** [comment]
This is probably not possible given our limited APIs, but would need much more investigation

**Comment by diracdeltas** [comment]
the default policy is webkit is now origin-when-crossorigin and is not overrideable according to @fmarier, so if that's also the case in Brave iOS, this is lower priority

**Comment by fmarier** [comment]
No longer needed, see #2494 for referrer tests.

**Comment by jumde** [comment]
dupe of https://github.com/brave/brave-ios/issues/2494
