### ISSUE TITLE
Display "Never Saved" domains in password sync in a separate section like desktop

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6991]
### Description: 

When you have password sync and sync websites that you've chosen to "never save"/prompt to save on desktop they will sync as empty passwords in iOS.  These should appear under a "Never Saved" section similar to desktop

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/529104/220718982-65c09646-b0e7-447a-a4e5-78f11bf807b3.png">

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` & `iPad (7th Gen)` running `iPadOS 16.4` using version `1.50 (23.4.17.16)`

- Ensured that logins marked as `never save` appear in the `Never Saved` section in the iOS password manager
- Ensured that login entries in the `Never Saved` section can be viewed and deleted via gestures. 
- Ensured that login entries in the `Never Saved` section can be deleted in edit mode. 
- Ensured that `Never Saved` logins show up on an existing profile (1.49.1 -> 1.50)

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![Screenshot 2023-04-17 at 4 55 54 PM](https://user-images.githubusercontent.com/17885425/232616689-535bee3c-6a7f-4e72-8d1d-1f7fa7d7fb7c.png) | ![IMG_2972](https://user-images.githubusercontent.com/17885425/232616054-57bc0075-dffc-4e56-a7bd-7acafff1a4b7.jpg) | ![IMG_2973 2](https://user-images.githubusercontent.com/17885425/232616060-9d705432-f88c-4400-ac6d-387845e9a807.PNG) | ![IMG_2974](https://user-images.githubusercontent.com/17885425/232616065-d6212ad1-d1c8-4d3f-9651-b676985bf034.jpg) | ![IMG_1048](https://user-images.githubusercontent.com/17885425/232616218-1e806a6d-8b19-4128-bfb4-31be78b4f462.PNG) | ![IMG_1049](https://user-images.githubusercontent.com/17885425/232616232-c6e4e45b-7c9e-4fcc-8a8d-0fe6b06f5818.jpg)
