### ISSUE TITLE
Favicon monograms should be always capitalized

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6995]
### Description: 

Monogram icons for history/bookmarks whos title is lowercased produce a lowercased monogram, this should be always capitalized

![image](https://user-images.githubusercontent.com/529104/220773388-e0d7a220-925e-43c1-bd0a-d582504fc0af.png)

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 16.1` & `iPad` running `iPadOS 15.6.1`  using version `1.48 (23.2.24.14)`

- Ensured Favicon monograms are should shown capitalized in history & bookmarks

![IMG_4575](https://user-images.githubusercontent.com/17885425/221326921-059f5a78-c01c-4cd6-9d0f-c46c6d7a31f3.jpg)
