### ISSUE TITLE
Favourites favicons are blurry/pixelated when synced from desktop

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6996]
### Description: 

When you sync history & bookmarks with Desktop the favicons that are synced with them are low-resolution 16x16 icons. These are being used in Favourites which look very blurry/pixelated. They are also not replaced with a better icon when visiting the website.

### Steps to Reproduce 
  1. Verify on fresh install that bundled icons are still used for favourites (reddit in particular)
  2. Enable sync (history) and sync with a desktop client
  3. On desktop client visit `reddit.com` and wait for the history to sync

### Actual result:
The reddit icon goes from the bundled blue one to a pixelated one and does not upgrade even when visiting the website

![image](https://user-images.githubusercontent.com/529104/220774341-dab14bc3-df7b-4f30-83ea-2f8d8750e85a.png)

### Expected result:
The reddit icon should either ignore the tiny favicon and use the bundled one or upgrade when you visit the website

### Reproduces how often:
Easily

### Brave Version:
1.48

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 16.1` & `iPad` running `iPadOS 15.6.1`  using version `1.48 (23.2.24.14)`

Based on Test Plan in https://github.com/brave/brave-ios/pull/7005#issue-1597545294

- Ensured when syncing to desktop, favicons will show as low res until user visits the URL
- Ensured that favicons are updated to HD when tapping on URL in history and bookmarks

Before | After
-|-
![IMG_0158](https://user-images.githubusercontent.com/17885425/221327529-d653876d-b432-45a0-adf1-5bf0929e9285.jpg) | ![IMG_0161](https://user-images.githubusercontent.com/17885425/221327531-c9ae1d55-dea8-401c-9347-969c3fc1bec9.jpg)
