### ISSUE TITLE
Only load http/https URLs when scanning a QR code from the URL bar

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#6997]
### Description: 

Currently any valid URL scheme is loaded, we should restrict that to only http/https URLs.

### Steps to Reproduce 

1. go to https://brave.com/
2. click the url bar
3. delete all characters
4. click the scan QR code button
5. scan the attached QR code (`javascript:alert(document.domain);`)

![image](https://user-images.githubusercontent.com/529104/220781802-7470ec42-a44d-486a-8d73-6db089276c01.png)

### Actual result: 
For this QR code, it will do nothing because `javascript` schemes are only valid in a bookmarklet context.
For other URLs likely they will fail to load

### Expected result:
Any non-http/https URL should be submitted as a search query to the users default search engine

### Reproduces how often:
Always

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.49 (23.3.15.17)
- Verified steps from issue description
- Verified scanning the QA code from issue description performs search on the SE and doesn't load it as a URL

iPhone 7+ (iOS 15.7.3) | iPhone XR (iOS 16.3.1) | iPad Pro (16.4 Beta 2)
-- | -- | -- 
<video src=https://user-images.githubusercontent.com/17010094/225588711-85fe9a14-0de1-41e3-9346-099dc907d7fa.MP4> | <video src=https://user-images.githubusercontent.com/17010094/225588804-ac599265-2d2c-4177-852d-4e88c27bc731.MP4> | <video src=https://user-images.githubusercontent.com/17010094/225588690-d05f85f5-74e0-46b7-b540-550a8b2044d3.MP4>
