### ISSUE TITLE
Rewrite ipfs urls in the wallet views

### ISSUE THREAD

**Issue by cypt4** [brave/brave-ios#6999]
Using nft gateway setting

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 15.7.3 running 1.49 (23.3.15.17)
- Verified steps from [#7000](https://github.com/brave/brave-ios/pull/7000)
- Verified after adding NFT, image is downloaded via the NFT gateway url set in settings

NFT Gateway (dweb.link) | NFT Gateway (nftstorage.link) | NFT on device | Device NFT Gateway (dweb.link) | Device NFT Gateway (nftstorage.link)
-- | -- | -- | -- | -- 
<img width=700 src=https://user-images.githubusercontent.com/17010094/226583843-4b489d97-783d-4ca7-8c88-50dbd222dc1d.png> |<img width=700 src=https://user-images.githubusercontent.com/17010094/226583813-b6818f08-d3fb-4f38-8fd8-0bcf873b08af.png> | <img width=500 src=https://user-images.githubusercontent.com/17010094/226584152-ae85fdb2-5548-46f9-9eb7-4f99b1cbc622.png> | <img width=130 src=https://user-images.githubusercontent.com/17010094/226584210-c274a505-b5ef-49fe-8e58-82c187fabac6.png> | <img width=100 src=https://user-images.githubusercontent.com/17010094/226584191-3d16b772-7766-4129-9ff6-d60adc3d065d.png>
