### ISSUE TITLE
Toolbar/URL bar UI parity with 1.x

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#70]
https://github.com/brave/brave-ios/pull/16/files
For reference, setup from old fork.

- [ ] Toolbar: Brave 1.6 has back, forward, share, new tab, and tab list
- [ ] URL Bar: Refresh button moved into url bar from toolbar.
- [ ] Element sizes: URL Bar + Toolbar are both shorter in 1.6

**Comment by jhreis** [comment]
https://github.com/brave/brave-ios/pull/16/files
For reference, setup from old fork.

**Comment by kylehickinson** [comment]
- [ ] Toolbar: Brave 1.6 has back, forward, share, new tab, and tab list
- [ ] URL Bar: Refresh button moved into url bar from toolbar.
- [ ] Element sizes: URL Bar + Toolbar are both shorter in 1.6
