### ISSUE TITLE
New/background tabs disappear

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#700]
User reports that their tabs have disappeared. 

 They had 40 tabs opened from playstationlifestyle.net
On re-opening Brave about 20 remained. 

<img width="632" alt="screen shot 2019-01-11 at 2 05 29 pm" src="https://user-images.githubusercontent.com/7606853/51062052-40f60780-15aa-11e9-88d4-df0abb6b6234.png">

**Comment by iccub** [comment]
Couldn't reproduce, closing as stale. Will reopen if there's another report of it
