### ISSUE TITLE
IPFS navigation support for iOS

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#7013]
iOS will have three options:
1. Ask
2. Gateway
3. Disabled

Ask will open an interstitial page for user to either proceed using a public gateway to resolve or disable it. 

In settings, we should also provide the support for users to customize the ipfs public gateway value. 

For the interstitial page and settings, please refer to what desktop has.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.50 (24..417.16)
- Verified steps from [#7127](https://github.com/brave/brave-ios/pull/7127)
- Verified a new setting for IPFS is shown under Web3 settings
- Verified `Resolve IPFS Resources` is set to `Ask` by default
- Verified `https://dweb.link` is set as default for `IPFS Public Gateway Address`
- Verified `https://nftstorage.link` is set as default for `IPFS Public Gateway Address for NFT`
- Verified able to set a different domain for both `IPFS Public Gateway Address` & `IPFS Public Gateway Address for NFT`
- Verified visiting `vitalik.eth` initiates ENS resolution interstitial page
- Verified proceed using ENS shows IPFS interstitial page
- Verified selecting `Disable` on interstitial page fails to load page and sets setting to `Disabled`
- Verified selecting `Use a public gateway` loads the page using the set default gateway
- Verified able to view page certificate on IPFS page loaded via public gateway
- Verified able to load `ipns://` page and load interstitial page or load the public gateway page successfully
- Verified clicking an IPFS URL like `ipfs://QmX4nfgA35MiW5APoc4P815hMcH8hAt7edi5H3wXkFm485/1688.html` from Notes or external app, automatically switches to Brave and loads the page
- Verified IPFS page shows error on private tabs regardless of what setting is set 


iPhone 7+ (iOS 15.7.3) | iPad Pro (iOS 16.5 Beta)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/232752450-c1a54d24-18ed-4830-a5e2-5582d930977a.MP4> | <video src=https://user-images.githubusercontent.com/17010094/232752632-3514d20b-1316-4443-9c67-f65a1e932cbc.MP4>
<img width=300 src=https://user-images.githubusercontent.com/17010094/232753368-5f6ddca9-3a0a-4d61-9725-0169d40b242d.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/232753397-9625a78c-50b5-4522-b3b3-1a9542d95a84.png>
