### ISSUE TITLE
Cross platform vpn does not renew

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7014]
### Steps to Reproduce 
  1. Buy on desktop, claim the vpn on iOS
  2. Wait at least a day to make sure the credential is expired and we have to refresh it

### Actual result: 
VPN config is removed

### Expected result:
The vpn config should stay alive

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `1.49 (23.3.31.9)` on `iPhone XR` running `iOS 15.5`

Test Plan: 

1. Purchase VPN on Desktop, claim on iOS 
2. Wait at least a day to make sure credential is expired

- Ensured VPN config stays alive

Example | Example
-|-
![IMG_0320](https://user-images.githubusercontent.com/17885425/229899002-e50c31eb-3658-49f2-b362-24768acee45e.PNG) | ![IMG_0321](https://user-images.githubusercontent.com/17885425/229899008-c173d1c3-b109-4747-b710-ce5ec9d32737.PNG)
