### ISSUE TITLE
Open in app is not hiding on google maps website

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#7024]
### Description: 
The open in app dialogs and buttons are not hiding on google maps

![image](https://user-images.githubusercontent.com/909331/221630988-260756c2-aaad-444c-b628-224e8b4d6c49.png)
![image](https://user-images.githubusercontent.com/909331/221631035-114e2836-85e1-47b2-9293-9dda9cfb074d.png)

### Steps to Reproduce 
  1. Enable "Fanboy's Mobile Notifications List" Filter List (wait a moment for the engine to get recompiled)
  2. Go to https://google.com/maps

### Actual result: 
"Open in app" popup and button is visible

### Expected result:
"Open in app" popup and button should not appear

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Every time

### Brave Version: 
1.47

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details: 
Any

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Issue with certain css rules being invalid. Will need further investigation to find out why the invalid css rules are there but for now fixed by cathing with invalid css rules.

```
Inserting rule: :matches-path(/travel/hotels/) div[data-is-promoted="true"]{display:none !important;} failed: SyntaxError: The string did not match the expected pattern.
Inserting rule: :matches-path(/^/search\?.*tbm=shop/) html[itemtype$="/SearchResultsPage"] #cnt div[class^="_-L"][class*="sh-sr__"]{display:none !important;} failed: SyntaxError: The string did not match the expected pattern.
```

**Comment by Uni-verse** [comment]
Verification completed using `1.49 (23.3.31.9)` on `iPhone X` running `iOS 16.3.1`

Scenario 1: `FAILED`

1. Install 1.49.x
2. Wait a few mins for scripts to load
3. Navigating to `https://www.google.com/maps`
4. Confirm popups are blocked 

Example | Example
-|-
![IMG_2882](https://user-images.githubusercontent.com/17885425/229565526-d267540e-431b-4bf6-9d46-c15ecf5151c6.PNG) | ![IMG_2884](https://user-images.githubusercontent.com/17885425/229565531-e9cf0c94-5c9c-4349-9c0c-9ce679f99baa.PNG)

Created follow up issue: https://github.com/brave/brave-ios/issues/7188
