### ISSUE TITLE
Remove SDWebImage SVG

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#7026]
### Description: 
- SDWebImage SVG crashes a lot when parsing SVGs
- We should remove it and use the Brave-Core SVG parser

### Brave Version: 
- 1.48.x

**Comment by nuo-xu** [comment]
Reopen this issue for Wallet team to remove the SDWebImage SVG coder and use the new api https://github.com/brave/brave-core/blob/master/ios/browser/api/web_image/web_image.h to load svg image
also label `qa/yes` to make sure nothing is broken.

**Comment by nuo-xu** [comment]
keep 1.59 milestone since this has been shipped in 1.57 but not verified.

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.60 (23.11.12.17)`

- Ensured using the test plan https://github.com/brave/brave-ios/pull/7881#issue-1852401188 does not cause a crash when loading sites that use SVGs. 
- Ensured that NFT images on previous version of the app are still pertained and showed.
- Ensured that importing NFTs in Brave Wallet is working on fresh and existing profiles.
- Ensured that images from popular sources are rendered correctly

Example | Example | Example | Example
-|-|-|-
![IMG_3628 2](https://github.com/brave/brave-ios/assets/17885425/7a334e5d-51ce-4f52-b4f6-8908e230c0af) | ![IMG_3629 2](https://github.com/brave/brave-ios/assets/17885425/a66571a2-b4f9-4f5c-af52-206454523cca) | ![IMG_3630 2](https://github.com/brave/brave-ios/assets/17885425/14fb308f-a587-42b3-ac63-c88e855ffe14) | ![IMG_3631](https://github.com/brave/brave-ios/assets/17885425/042bfcdc-09ba-4e2f-89bd-4aeffc9a9c2a)

1.58.2 | 1.60
-|-
![IMG_3634 2](https://github.com/brave/brave-ios/assets/17885425/04e80978-8374-481c-a07c-4f389f8ca43a) | ![IMG_3635 2](https://github.com/brave/brave-ios/assets/17885425/1cb425e9-60ba-4afe-ace6-e87e4bd5aec8)
