### ISSUE TITLE
Uniswap balance on Polygon chain is not being shown on Buy-Send-swap screen

### ISSUE THREAD

**Issue by Pavneet-Sing** [brave/brave-ios#7035]
### Actual result: 

https://user-images.githubusercontent.com/11755381/222193650-2fc17901-8c36-48ac-954e-5b8bba1b74bf.MP4

### Expected result:
Should show correct balance

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Y
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Additional Information
Android issue: https://github.com/brave/brave-browser/issues/28824 (could be same logical issue )

**Comment by StephenHeaps** [comment]
@Pavneet-Sing I noticed you have `Account 1` selected in Send/Swap on Polygon, but you only have a balance on `Account 2` in UNI asset details page on Polygon. Could you confirm with `Account 2` selected when opening Send/Swap for UNI on Polygon?

**Comment by Pavneet-Sing** [comment]
@StephenHeaps Thanks, my bad. Closing. Please add invalid tag as I don't have the access to modify.
