### ISSUE TITLE
[WebKit] File uploaded are not cleaned up when Brave is force closed with the page open

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#7036]
### Description: 

When a user uploads a file through a web page, WebKit will copy said file to the `/tmp` directory in the app sandbox. If the user does not close the tab they used to upload (thus destroying the WKWebView) before the app terminates, then WebKit no longer cleans up the file and it remains on disk until the OS decides to purge `/tmp` directories to recover disk space.

Related to https://github.com/brave/brave-ios/issues/6822

### Steps to Reproduce 
  1. Visit a page where you can upload files to (e.g. dropbox, etc.)
  2. Select a file through the relevant file picker (depending on the website, could be a photo picker, video picker, files picker). You don't actually have to upload it, just select it through the form
  3. Force close the app (via app tray)

### Actual result:
In the `Sandbox Inspector`, a folder prefixed with `WKVideoUpload`, `WKWebFileUpload`, or `WKFileUploadPanel` will be present in the `tmp` root folder. Inside that folder will be the file you selected in step 2

### Expected result:
In the `Sandbox Inspector` there should be no leftover data from your file uploads in prior browsing sessions when launching the app

### Reproduces how often:
Easily

### Brave Version: 
Probably for a while, this is a WebKit bug

**Comment by Uni-verse** [comment]
Verification completed on `iPhone 12` running `iOS 16.4` using version `1.49 (23.3.31.9)` Dev Channel

Using Steps to Reproduce in https://github.com/brave/brave-ios/issues/7036#issue-1605606061

- Ensured that `tmp` folder in the `sandbox inspector` does not have any leftover data or contain anything prefixed with WKVideoUpload, WKWebFileUpload, or WKFileUploadPanel

<img width="500" alt="1" src="https://user-images.githubusercontent.com/17885425/229223800-47470f6c-53d6-43e9-a65c-4b04cea91271.PNG">
