### ISSUE TITLE
Favicon crash when visiting certain websites using `Request Desktop`

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7037]
### Steps to Reproduce 
  1. Go to google.com on your phone
  2. Tap 3 dot menu -> Request Desktop site

### Actual result: 
Crash

### Brave Version: 
1.48 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verification **PASSED** on the following device(s) using version `1.48.1 (23.3.2.0)`

`iPhone 12`, `iOS 16.1`
`iPhone XR`, `iOS 15.5`
`iPad (7th Gen)`, `iPadOS 16.3`

Test Scenario: https://github.com/brave/brave-ios/issues/7037#issue-1605607103

1. Visit `Google.com`
2. Tap menu > request desktop site
3. Repeat steps for `apple.com` & `facebook.com`

- Ensured that requesting desktop site will reload the webpage successfully and will not crash on`google.com`, `apple.com` and `facebook.com`
- Ensured that user is able to request mobile site again and page changes to the mobile site

Google.com | Apple.com
-|-
![IMG_4604](https://user-images.githubusercontent.com/17885425/222314789-c05f7e3e-d754-4026-b192-4104df6a759d.PNG) | ![IMG_1023](https://user-images.githubusercontent.com/17885425/222314816-87a0293c-862f-4b12-ae8d-68f8664127e3.PNG)
![IMG_4603](https://user-images.githubusercontent.com/17885425/222314837-433e16f6-31b9-4f48-a969-2f31d299c901.PNG) | ![IMG_1024](https://user-images.githubusercontent.com/17885425/222314872-8a2efb10-b693-48f5-bdc9-f8fa9d64c677.PNG)

**Comment by kjozwiak** [comment]
Verified **PASSED** on `iPhone 11` running `iOS 16.2` using `1.48.1 (23.3.2.0)` using the STR/Cases outlined via https://github.com/brave/brave-ios/issues/7037#issue-1605607103.

Originally reproduced the crash on `1.48 (23.2.26.19)` and confirmed that it wasn't happening/crashing on `1.48.1 (23.3.2.0)` when switching between Desktop/Mobile views.

Example of the issue occurring via  `1.48 (23.2.26.19)`:

https://user-images.githubusercontent.com/2602313/222503346-6d900eb3-20c8-40b3-9825-909e6ae626ee.mp4

Example of the issue resolved/not happening via `1.48.1 (23.3.2.0)`:

https://user-images.githubusercontent.com/2602313/222503476-d41ace93-a77a-43a1-970f-b8a785ff3b77.mp4

Also went through a few other popular websites and ensure that requesting the desktop view didn't crash the browser.
