### ISSUE TITLE
2.0 Home Screen

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#704]
### Home (Light)
![home light 2x](https://user-images.githubusercontent.com/318119/51217100-a5cb9d80-18db-11e9-8fd5-36660b228d29.png)

### Home (Dark Con-- unrelated to "dark" mode)
![home 2x](https://user-images.githubusercontent.com/318119/51217116-b845d700-18db-11e9-9cb6-e39b825c8954.png)

### Home (Dark Mode)
![home dark mode 2x](https://user-images.githubusercontent.com/318119/51217123-bda32180-18db-11e9-96d8-8dc198b5d55c.png)

### Home (Private)
![home private 2x](https://user-images.githubusercontent.com/318119/51217176-f4793780-18db-11e9-9e6f-53aab997c846.png)

![home light private 2x](https://user-images.githubusercontent.com/318119/51217127-c98ee380-18db-11e9-88f9-fe6e58eaca12.png)

- Optimize light or dark display for contrast against background image.
- User defined background image or fallback to Brave presets.
- Privacy mode toolbar and address bar color styling.
- Include sunglasses icon in privacy mode (address bar on home only)

**Comment by jamesmudgett** [comment]
Cover overlay gradient
[home_gradients.zip](https://github.com/brave/brave-ios/files/2757717/home_gradients.zip)

**Comment by jhreis** [comment]
Closing this epic, as no longer using Zenhub.
