### ISSUE TITLE
2.0 Modal View

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#705]
### Modal View (Presentation)
![bookmarks](https://user-images.githubusercontent.com/318119/51143881-7dbd3b00-1804-11e9-9b7c-b32f223f31c4.png)

### Modal View (Private Mode)
![home private tab tray](https://user-images.githubusercontent.com/318119/51144312-88c49b00-1805-11e9-8ae8-7ea9a465082a.png)

**Goals**

1. Ability to present any viewController as custom modal presentation.
2. Interactive dismiss (swipe down), or scroll content to present as full-screen.
3. Close button and overlay-tap-to dismiss optional flags.
4. Responds to keyboard presentation/hide, when keyboard presents modal should transition to full-screen mode. On keyboard hide modal should return to original state (half-view or remain in full view)
5. Background blur (may require capturing superview contents on viewWillAppear and using under visual effects view), background color override to set a 'tint' within contentView on visual effect view, see private mode modals)
6. By default modal background should inherit background color of toolbar.

**Comment by jhreis** [comment]
Closing this epic, as no longer using Zenhub.
