### ISSUE TITLE
Auto-upgrade of Youtube video resolution

### ISSUE THREAD

**Issue by kevincolyar** [brave/brave-ios#7055]
### Description: 

When using the mobile version of the YouTube website in fullscreen mode, rotating the screen should upgrade the resolution from 360p to 720p.

At one point (late fall of 2022?) I believe this was working on Brave iOS but appears to have reverted back to the old way of handling YouTube video resolution.  

### Steps to Reproduce 
  1.  Play video on YouTube mobile website (notice resolution is set to Auto (360p in my case).
  2.  Enter fullscreen
  3.  Video resolution does not improve.

### Actual result: 

Video resolution stays at 360p.

### Expected result:

Video resolution should improve to 720p.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced.

### Brave Version: 1.48.1 (23.3.2.0)

- Can you reproduce this issue with the most recent build from TestFlight?
Don't have TestFlight.

- Can you reproduce this issue with the previous version of the current build from TestFlight?
Dont have TestFlight.

- Can you reproduce this issue with the current build from AppStore? 
Yes

### Website problems only:
- did you check with Brave Shields down? 
Yes

- did you check in Safari/Firefox (WkWebView-based browsers)? 
No, I only use Brave.

**Comment by anthonypkeane** [comment]
Please place this setting under GENERAL , Block Popups

STREAMING PLAYBACK
Enable Playback at Max Quality
-> Display the value as we do for Appearance

Tapping on Enable Playback at Max Quality take the user to a screen where we display the following

Title: STREAMING PLAYBACK
Off
Allow over Wi-Fi 
Allow over Cellular 
Description: 
_Enabling this experimental feature will playback YouTube video at the maximum quality available and may use additional data._

The user can check either Off, Allow over Wi-Fi or Allow over Cellular as they can in the Podcast setting (image below for reference) 

Cellular should automatically localize to Mobile given the users region. 

@aguscruiz can you please provide an icon for ^


@iccub if we can combine https://github.com/brave/brave-ios/issues/7654 with this ticket it will clean the menu up a bit. 

Thanks

Example 
![IMG_990082B65CBC-1](https://github.com/brave/brave-ios/assets/7606853/0b5d1d8f-ecbc-4c31-8976-b5d37b345276)

![IMG_990082B65CBC-2](https://github.com/brave/brave-ios/assets/7606853/3b439642-f86a-4c28-b2b4-461d1e2eb255)
![IMG_F206ADDF2549-1](https://github.com/brave/brave-ios/assets/7606853/7cca26ef-953c-4103-bd53-a4e32d3ace3d)

**Comment by hffvld** [comment]
Verified on `iPhone 14`using version(s):
```
Device/OS: iPhone 14 [iOS 16.5.1]
Brave build: 1.56 (23.7.19.18)
BraveCore: 1.56.6 (115.0.5790.90)
```

Filed follow-up issue #7769 and #7771
---------------------------

**STEPS:**
1. Launch Brave 
2. Three-dot menu > Settings
3. Open `Media` under `DISPLAY` section
4. Find `YOUTUBE` section > Tap `Highest Quality Playback` > Verify
5. Go back and open www.youtube.com > Play any video
6. Tap ⚙︎ icon > Verify
7. Go back to `Highest Quality Playback` screen and change the setting to `Always on` > Verify video playback
8. Repeat Step 7, but this time enable `Only while using WiFi`

**ACTUAL RESULTS:**
- Verified that the new `YouTube` section appeared under `DISPLAY` > `Media`
- Verified that the default preset is set to `Off` for the `Highest Quality Playback`
- Verified pop-up menu UI for a separate video on www.youtube.com
- Verified when `Highest Quality Playback` is set to `Off`, default video quality is set to `Auto (360p)`
- Verified when `Always on` or `Only while using WiFi` is ON, video quality is set to `720p` automatically (in 720p is available for the video)

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/00195492-8d29-4451-8fa1-1ef4d2767577) | ![2](https://github.com/brave/brave-ios/assets/128532965/e10c70dd-9f8c-411d-bb5e-a0b776e58105) | ![3](https://github.com/brave/brave-ios/assets/128532965/3253f488-6ed2-48e7-bc68-308d38788286) |
|4|5|6|
 |![4](https://github.com/brave/brave-ios/assets/128532965/267e3681-05f4-44df-b949-91d610e26fdd) | ![5](https://github.com/brave/brave-ios/assets/128532965/be39529a-6694-4810-becc-3ed588655cb2) | ![6](https://github.com/brave/brave-ios/assets/128532965/96d93232-2df5-491d-b6ab-28704293f525) |

https://github.com/brave/brave-ios/assets/128532965/6d3f4109-3f15-4f31-b51f-943788e8d64f

**Comment by anthonypkeane** [comment]
@iccub 

Pls change
Allows desktop-quality resolution
for
Allows high-quality resolution

Pls update the settings options to:
On
Allow over Wi-Fi (enabled default)
Off

**Comment by iccub** [comment]
Copy and default behavior tracked here https://github.com/brave/brave-ios/issues/7776
