### ISSUE TITLE
In an RSS-only Brave News state, the "New Content Available" button comes up every time NTP is viewed

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#7059]
### Description: 

The purple "New Content Available" button shows up every time you come back from visiting a link in a RSS-only feed

### Steps to Reproduce 
  1. Enable Brave News and unfollow Top Sources (and any other sources you're following)
  2. Follow an RSS feed of your choosing (replicated with Daring Fireball: `https://daringfireball.net/feeds/main`)
  3. Visit an RSS feed's link
  4. Click the back button to go back to NTP/Brave News

### Actual result:
The "New Content Available" button appears every time

### Expected result:
It should not appear unless the sources expire (24 hours) or you edit your sources

### Reproduces how often:
Easily

**Comment by Uni-verse** [comment]
Verified using `1.49 (23.3.23.15)` on `iPhone 12 Pro` running `iOS 16.4` while running though https://github.com/brave/brave-ios/issues/7063#issuecomment-1481455784
