### ISSUE TITLE
2.0 Tab Tray

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#706]
### Tab Tray
![home tab tray](https://user-images.githubusercontent.com/318119/51144780-ee655700-1806-11e9-927d-02a0febc4a2c.png)

![home tab tray list](https://user-images.githubusercontent.com/318119/51147681-0d1c1b80-1810-11e9-9c80-a1bc310036f5.png)

![browser tab tray long press](https://user-images.githubusercontent.com/318119/51144787-f3c2a180-1806-11e9-9fea-7aa2e4cf0848.png)

**Goals**

1. Present open tabs as a modal presentation over current content.
2. Default to carousel mode - optimized for site content display.
3. List mode optimizes for titles and favicon
4. Long-press or 3D touch to present expanded screenshot (available on both list and carousel modes), second tap will select and open tab.
5. Animation for left/right scroll on carousel (TBD)

**Comment by jhreis** [comment]
Closing this epic, as no longer using Zenhub.
