### ISSUE TITLE
Visiting a link blogs RSS feed in Brave News can load the linked URL instead of the blogs URL

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#7063]
### Description: 

Tapping on an RSS feed entry for a link blog (e.g. Daring Fireball) will load the link the blog refers to directly instead of the blog post

### Steps to Reproduce 
  1. Enable Brave News and disable other sources
  2. Add a link blog that posts Atom RSS feeds that contains multiple links (Daring Fireball is an example: `https://daringfireball.net/feeds/main`) to Brave News
  3. Click on an entry that appears in Brave News

### Actual result:
It opens the URL that the blog links to

### Expected result:
It should open the blog post 

### Reproduces how often:
Easily

**Comment by Uni-verse** [comment]
Verified using `1.49 (23.3.23.15)` on `iPhone 12 Pro` running `iOS 16.4`

Tested using STR in https://github.com/brave/brave-ios/issues/7063#issue-1615941411

- Confirmed clicking on entry in brave news will open the blog post

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_4645](https://user-images.githubusercontent.com/17885425/227262416-bff5e9eb-7011-475c-a3e9-9738125c9829.PNG) | ![IMG_4646](https://user-images.githubusercontent.com/17885425/227262425-9bd061b4-211c-48f2-9b39-3382012885a1.PNG) | ![IMG_4647](https://user-images.githubusercontent.com/17885425/227262429-fa77ca53-c10e-4197-a976-03a43076a77b.PNG) | ![IMG_4648](https://user-images.githubusercontent.com/17885425/227262431-d12ae28f-c764-44ec-baf4-054b69abd49b.PNG) | ![IMG_4649](https://user-images.githubusercontent.com/17885425/227262438-33c2ead4-bf99-4723-b97a-aec76d84008e.PNG)
