### ISSUE TITLE
Session storage for VPN linking lost during login

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#7067]
### Description: 
When a person has VPN purchased as in-app-purchase, they can link it using the account.brave.com website

In product, they'd go to Brave Firewall + VPN and link account. This asks the user to login which involves sending an email with a magic link.

If you click the link instead of copying it into your browser, it opens a new session (new tab) which no longer has the purchase token information shared. When doing a link the user is met with an error (see screenshot below)

### Steps to Reproduce 
1. Have VPN purchased on iOS
2. Go to `Settings` > `Brave Firewall + VPN`
3. Click link to link account
4. account.brave.com is pulled up (if inspected, the `braveVpn.receipt` value will be there in session storage)
5. You'll be prompted for email. Enter and click OK
6. Check email
7. Don't copy/paste URL into your original window. Instead, either open a new tab and paste OR click the link (if you're using webmail which will open in Brave)

## Actual result 
![image](https://user-images.githubusercontent.com/4733304/223879690-b0946864-c006-4e72-96f6-97c050649218.png)

## Expected result
Details should be readable by account.brave.com website

### Reproduces how often: [Easily reproduced, Intermittent Issue]
100%

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.49 (23.3.28.19)`

Test Plan: https://github.com/brave/brave-ios/issues/7067#issue-1616168084

- Verified localStorage is used for receipt storage
- Verified user is able to open a new tab and link subscription receipt

Example | Example | Example
-|-|-
![IMG_2859](https://user-images.githubusercontent.com/17885425/228680185-725e72cd-e835-4752-b3e8-bc8ebc06bfc2.PNG) | ![IMG_2860](https://user-images.githubusercontent.com/17885425/228680201-b3161f4f-d525-4739-941c-4f706ae6d647.PNG) | ![IMG_2862](https://user-images.githubusercontent.com/17885425/228680216-e9ab9fb0-a650-43a0-bc93-e780fb970f38.PNG)

https://user-images.githubusercontent.com/17885425/228680247-d1d8ee91-e81a-4454-ba4c-9a247da9c252.MP4
