### ISSUE TITLE
2.0 History

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#707]
### History
![history limited date span](https://user-images.githubusercontent.com/318119/51146292-44d49480-180b-11e9-82f4-bad5dc335947.png)
![history limited date span confirm](https://user-images.githubusercontent.com/318119/51146300-4900b200-180b-11e9-9fc3-a0ff7cb38409.png)

 Modal presentation of history. 

**Goals**

1. Search history
2. Secondary y-scroll of indices of displayed table sections. Tapping on date scrolls tableview contents to respective date section.
3. "Clear History" button with options

**Comment by jhreis** [comment]
Closing this epic, as no longer using Zenhub.
