### ISSUE TITLE
Wallet: NFT with ipfs image url is not displaying correct asset icon

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#7078]
NFT image with ipfs url is resolved in side NFT details screen. but it is missed for asset icon. This will cause NFT asset icon displaying monogram instead of the correct image. 
![simulator_screenshot_7C7E1B6D-2483-4CB8-831D-7CC7AEF22BE1](https://user-images.githubusercontent.com/1187676/224372585-98f5193c-2ce1-4b69-afa2-f76edb1c6cfc.png)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.49 (23.3.15.17)
- Verified steps from [#7081](https://github.com/brave/brave-ios/pull/7081)
- Verified NFT icon is being displayed correctly through out the wallet

iPhone 7+ (iOS 15.7.3) | iPhone XR (iOS 16.3.1) | iPad Pro (16.4 Beta 2)
-- | -- | -- 
<img width=300 src=https://user-images.githubusercontent.com/17010094/225565091-80bdad3f-9931-4c14-93e4-5903a3d86e83.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/225565860-f422c7aa-a2e8-41dc-bfed-daf2ea4e106c.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/225567304-bfd98f44-fa56-4b12-b995-a532d43c1c11.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/225565076-b73fc7bb-7624-4ffc-bf75-5a68b35a7e38.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/225565901-9a2911f9-2cb1-4b8c-ad5b-a265619f741b.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/225567242-d1fd83ed-bf16-4752-aed0-3ac937e99ca4.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/225565033-3a44f7cf-3e7e-4ef1-94bc-2ce7400c795b.png> | <img width=250 src=https://user-images.githubusercontent.com/17010094/225565953-c115900f-fa65-4f36-8eda-26df577d9a4d.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/225567277-8a847390-2a59-4e68-96bf-99b63a57f566.png>
