### ISSUE TITLE
Remove brave-core object migrations from unsupported versions

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#7086]
### Description: 

The brave-core data migrations should be removed for Bookmarks - History - Passwords. 

This should include any error warnings while migrations are happening or pages that are being shown in result of errors.

In addition this cleanup process will include legecy Bookmark migrations between old and new versions before brave-core is introduced.

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.50 (23.4.25.20)`

Testing based on Test Plan in https://github.com/brave/brave-ios/pull/7087#issue-1622121000

- Performed sanity check for Bookmarks, History and Passwords
- Ensured nothing is broken on upgraded profile for Bookmarks, History and Logins

Example | Example | Example | Example
-|-|-|-
![IMG_3038](https://user-images.githubusercontent.com/17885425/234990248-a537d1aa-e8ba-4c24-8bc1-2956c7db541f.PNG) | ![IMG_3039](https://user-images.githubusercontent.com/17885425/234990260-2e6f5130-54cc-40d0-8841-84a1f5c76176.PNG) | ![IMG_3043](https://user-images.githubusercontent.com/17885425/234990264-e6685daf-bb49-478a-b2b4-2e2a23c26dbf.PNG) | ![IMG_3044 2](https://user-images.githubusercontent.com/17885425/234990271-c478b318-cfdb-44ad-b90d-86ee6f8d9e1e.PNG)
