### ISSUE TITLE
Unstoppable Domain navigation

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7089]
### Description: 

iOS version of
https://github.com/brave/brave-browser/issues/15158

Implement navigating to Unstoppable domains in the browser via omnibar / url bar. The default should be to ask the user before navigating via an interstitial page.

Supported extensions: https://github.com/brave/brave-core/blob/master/components/brave_wallet_ui/common/constants/domain-extensions.ts

Terms of Use: https://consensys.net/terms-of-use/
Privacy Policy: https://consensys.net/privacy-policy/

Interstitial:
<img width="653" alt="Unstoppable Domains interstitial" src="https://user-images.githubusercontent.com/5314553/225027500-85f336ef-debb-4acf-850d-ec36eef9e90e.png">

Wallet address resolution will be handled in https://github.com/brave/brave-ios/issues/6182

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.50 (24.417.16)
- Verified steps from [#7165](https://github.com/brave/brave-ios/pull/7165)
- Verified navigating to UD domain brings up the interstitial page
- Verified `Terms of use` and `Privacy Policy` points to Consensys (Infura) pages
- Verified clicking on `Proceed using Infura server` loads the IPFS interstitial page if its set to `Ask` else loads the page using specified public gateway
- Verified UD domain resolution only works on normal tabs and not on private tabs

iPhone 7+ (iOS 15.7.3) | iPad Pro (iOS 16.5 Beta)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/233032849-ce65ec1e-e543-48e3-9748-9d34a1909b74.MP4> | <video src=https://user-images.githubusercontent.com/17010094/233032797-bdb90c76-c5bc-42a4-b676-80869d2b4f46.MP4>
