### ISSUE TITLE
2.0 Dark Mode

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#709]
### More Menu Switch
![homemenu 2x](https://user-images.githubusercontent.com/318119/51205106-fb8f4e00-18b9-11e9-992e-d9336b560146.png)

### Dark Mode (Toolbar and input)
![home dark mode 2x](https://user-images.githubusercontent.com/318119/51205434-c1727c00-18ba-11e9-9cf7-8a679007f125.png)

### Browser in dark mode
![browser dark mode](https://user-images.githubusercontent.com/318119/51205228-3f825300-18ba-11e9-8485-e34ca4ce8da0.png)

**Comment by maxwowpow** [comment]
Now with the iOS 13 this will be a must, hold tight for the "+1" comments.

On the topic note, Apple actually copied the Safari's private view dark-mode to the normal, so they were identical in b4, but then ended up coloring the buttons in non-private mode:

![image](https://user-images.githubusercontent.com/169885/62638660-33d1a900-b93e-11e9-906d-67fc4eb65d2f.png)

In the private mode they are white.

**Comment by jhreis** [comment]
Closing this epic, as no longer using Zenhub.
Don't worry, we are working on dark mode 😄

**Comment by jhreis** [comment]
Created new, non-epic issue: https://github.com/brave/brave-ios/issues/1493
