### ISSUE TITLE
Brave News fetches no feeds if you follow only individual sources and no channels

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#7093]
### Description: 

If you only follow sources and no channels then Brave News fetches no feeds and you end up with an empty feed

### Steps to Reproduce 
  1. Turn on Brave News
  2. Unfollow Top Sources and follow some individual sources (Investopedia for example)
  3. Open a new tab

### Actual result: 
Empty feed

### Expected result:
Should load feed for those sources

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

**Comment by Uni-verse** [comment]
Verified using `1.49 (23.3.23.15)` on `iPhone 12 Pro` running `iOS 16.4`

Using STR in https://github.com/brave/brave-ios/issues/7093#issue-1624130323

- Ensured that feed is shown when following only individual sources.

Example | Example | Example | Example
-|-|-|-
![IMG_4650](https://user-images.githubusercontent.com/17885425/227264233-2466eb28-2930-4c2c-b17f-9c93f6fe228d.PNG) | ![IMG_4651](https://user-images.githubusercontent.com/17885425/227264237-07f4fdd2-910d-4933-b067-10a10594a114.PNG) | ![IMG_4652](https://user-images.githubusercontent.com/17885425/227264244-f431ab01-f59a-4520-8163-b188dab4c76a.PNG) | ![IMG_4653](https://user-images.githubusercontent.com/17885425/227264246-110c15a4-d4b9-4a6f-aae1-a45fa9779698.PNG)

**Comment by voxelshaper** [comment]
This bug is active again.
In Android and Linux.
