### ISSUE TITLE
Shields show Session Restore - Reader Mode Internal URL 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#7103]
### Description: 
Shields show `INTERNAL://LOCAL/SESSIONRESTORE?URL=` whilst the page is loading. In addition when Reader Mode is activated Shields show `INTERNAL://LOCAL/READER-MODE?URL=`  if reader mode is activated.

### Steps to Reproduce 
Test 1:
  1. Load a page
  2. Quit browser and relaunch
  3. Open shields while the page is loading
 
Test 2:
  1. Load a page
  2. Activate Reader mode
  3. Open shields

### Actual result: 

![test1 1](https://user-images.githubusercontent.com/6643505/232516799-26acd5a9-57c0-4e10-b81a-179291c31057.png)

### Expected result:
Should show original URL

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 
1.49(23.3.15.7)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details: 
All

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @kylehickinson @iccub @Brandon-T

**Comment by soner-yuksel** [comment]
This problem also happens with Reader-Mode pages. The ticket is updated accordingly with test plan and ss's added.

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: iPhone 14 [iOS 16.4.1] and iPad Air [iPadOS 16.4.1]
Version: 1.51 (23.5.8.16) 
BraveCore: 1.51.110 (113.0.5672.77)
```

**STEPS:**

Test 1:
1. Load a page
2. Quit browser and relaunch
3. Open shields while the page is loading

Test 2:
1. Load a page
2. Activate Reader mode
3. Open shields

**ACTUAL RESULTS:**
- Verified actual URL is shown in Shields when restarting Brave
- Verified actual URL is shown in Shields when Reader Mode is enabled

https://user-images.githubusercontent.com/128532965/236900016-6cc53b8a-2f7f-4c71-a7e1-a04dfcaca43d.mov

https://user-images.githubusercontent.com/128532965/236900222-f53ff71e-3f84-4501-ba19-86d5797da0b7.mov
