### ISSUE TITLE
[CarPlay] - Some folders not showing on the CP stack

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#7105]
### Description: 
1. Some folders do not show correctly when using CarPlay

### Steps to Reproduce 
  1. Add Folders (Saved, Other Folders, and Shared Folders)
  2. Open CarPlay
  3. Some folders not showing

### Actual result: 
- Only some folders show (Saved and Other Folders)

### Expected result:
- Should show all folders

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily Reproduced

### Brave Version: 
- 1.48.x

### Device details: 
- CarPlay Car

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.49 (23.3.31.9)`

- Ensured folders are showing up in CarPlay
- Ensured creating new folders while CarPlay is running are showing up
- Ensured basic CarPlay functionality (skip, stop/play, navigation)
- Ensured user is able enable playback for media in folders on CarPlay
- Ensured removing folders will update correctly on CarPlay

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_2873](https://user-images.githubusercontent.com/17885425/229553897-bd67ba88-4d92-4931-8b4e-b49c0b8bef9d.PNG) | ![Screen Shot 2023-04-03 at 11 11 46 AM](https://user-images.githubusercontent.com/17885425/229554043-90f62b0b-a949-416d-a978-2dc017b8aa3a.png) | ![Screen Shot 2023-04-03 at 11 12 09 AM](https://user-images.githubusercontent.com/17885425/229554046-805cefbc-6256-4bdd-b240-faae4b6e811d.png) | ![Screen Shot 2023-04-03 at 11 12 28 AM](https://user-images.githubusercontent.com/17885425/229554050-6a544919-79a6-4b44-8d89-42f8d2e6a8d9.png) | ![Screen Shot 2023-04-03 at 11 12 55 AM](https://user-images.githubusercontent.com/17885425/229554052-bcd65b3b-b96e-4bdc-b5a2-83fe6bc2672a.png) | ![IMG_2877](https://user-images.githubusercontent.com/17885425/229554249-5ac9a387-7643-44c7-9717-f8f5b620f1a5.PNG)
