### ISSUE TITLE
Define `window.braveEthereum` to proxy provider at `window.ethereum`

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7109]
### Description: 

With changes in https://github.com/brave/brave-core/pull/17658 (intended to be uplifted to v1.49) we will need to define a `window.braveEthereum` proxy to the `window.ethereum` provider or we'll lose access to `on` / `emit` / `removeListener ` / `removeAllListeners`. Without this change, it would break anything calling the above methods events (ex. chain change or account changes being emitted).

**Comment by yrliou** [comment]
This can be closed now as we ended up with only exposing window.ethereum.
