### ISSUE TITLE
On Restore Wallet, you should be able to see full recovery phrase from within box

### ISSUE THREAD

**Issue by HEagle18** [brave/brave-ios#7112]
### Description: 
When trying to restore your recovery phrase, you should be able to see all of 12 words when you reveal the phrase. 

### Steps to Reproduce 
  1. enter in a recovery phrase on the reset wallet flow 
  2. you won't be able to all 12 words together
  3.

### Actual result: 

on this screen
![IMG_7891](https://user-images.githubusercontent.com/12224304/226380823-be7267e7-d05a-4c96-8606-b6f87e70cd4f.png)

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by nuo-xu** [comment]
Close this issue since it became irrelevant with V2 design. Users now can reveal all recovery-phrase in the V2 design.
