### ISSUE TITLE
Drop contents of "tmp" folder at app launch

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7114]
This may potentially fix app storage problems users report

**Comment by iccub** [comment]
do not remove if storage low enough

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using build version `1.50 (23.4.17.16)`

Used Test Plan in https://github.com/brave/brave-ios/issues/7036#issue-1605606061

- Ensured that tmp folder is emptied after app is relaunched
- Ensured that app launches successfully when tmp folder contains files over limit (100Mb)

Before re-launch | After re-launch
-|-
![IMG_2969 2](https://user-images.githubusercontent.com/17885425/232567163-df3fcd61-2df2-4564-870e-b7e0233b38b6.PNG) | ![IMG_2970 2](https://user-images.githubusercontent.com/17885425/232567166-ed0bde76-c9c6-498b-8a00-53b4554adef4.PNG)
