### ISSUE TITLE
Favicon flickers sometimes when rendering in History Search

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#7116]
### Description: 
- When searching history, favicons flicker

### Steps to Reproduce 
  1. Open History
  2. Search for any existing history

### Actual result: 
- Favicon flickers

### Expected result:
- Favicon should render immediately

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily reproduced

### Brave Version: 

- 1.48.x

**Comment by Uni-verse** [comment]
Verified using `1.49 (23.3.23.15)` on `iPhone X` running `iOS 16.3.1` & `iPad (9th Gen)` running `iOS 15.6.1`

Using STR in https://github.com/brave/brave-ios/issues/7116#issue-1632995446

- Ensured favicon dont flicker in history page or when searching history
- Ensured favicon dont flicker in history if sync chain is connected

Example | Example
-|-
![IMG_0162 2](https://user-images.githubusercontent.com/17885425/227608632-0366f71e-2210-4f56-8b1f-63290f9ff4d9.PNG) | ![IMG_2846](https://user-images.githubusercontent.com/17885425/227608637-c79d28c7-5798-4448-a866-ab1dd114f48f.PNG)
