### ISSUE TITLE
Remove legacy logins.db

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7120]
After converting the Login/Credential data be stored and used with Chromium APIs, the purpose of this cumbersome implementation of manually encrypted lost its value.
The database is only used for storing Basic Authentication Credentials which is not needed to be stored for arbitrary application launches.

In addition to clean-up the purpose of removal is to have a relief for the problem this database might be causing when application is trying to retrieve data and actually stuck while doing it, especially when opening new external urls and waking up with browser lock feature.

**Comment by hffvld** [comment]
Verified, the issue is not reproducible in build 1.50. Basic Auth required only once for a particular site until Brave is closed and relaunched.

------------------

```
Device/OS: iPhone 14 [iOS 16.4.1] and iPad Air [iPadOS 16.4.1]
Brave build: 1.50 (23.4.19.20)
```

**Screenshot/Screencast:**

https://user-images.githubusercontent.com/128532965/233479401-4038b780-b1d7-4e5e-9f0a-7e9960a98acf.mov
