### ISSUE TITLE
Small favicons in widgets

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7124]
<img width="492" alt="Zrzut ekranu 2023-03-21 o 17 44 27" src="https://user-images.githubusercontent.com/6950387/226681254-e792d8dc-77d5-4ccc-b6d4-115ee310ea58.png">

**Comment by Uni-verse** [comment]
Verified on `1.50 (23.4.12.13)` on `iPhone X` running `iOS 16.3.1`

- Confirmed small favicons are not generated when adding favorites to lock screen widget.

![IMG_2946](https://user-images.githubusercontent.com/17885425/231518531-9267c5de-8a4a-4779-873e-8d96e91a1038.PNG)
