### ISSUE TITLE
IPFS links in website

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#7128]
When user clicks an IPFS link from a website in Brave browser this should trigger the whole IPFS navigation flow.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.50 (23.4.17.16)
- Verified clicking on an IPFS/IPNS link loads correctly based on Resolve IPFS Resources setting (Ask/Enabled/Disabled)

iPhone 7+ (iOS 15.7.3) | iPad Pro (iOS 16.5 Beta)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/233251396-632b04d1-9174-4fc9-b6f6-77cd8f04b385.MP4> | <video src=https://user-images.githubusercontent.com/17010094/233251339-c9df0a42-a95a-448b-8fcd-c73f3bf2ad37.MP4>
