### ISSUE TITLE
IPFS links from other apps

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#7129]
When user clicks an ipfs links from other apps, it should open Brave and start the whole ipfs navigation flow.

**Comment by nuo-xu** [comment]
from discusstion in https://github.com/brave/security/issues/1227
@stoletheminerals mentioned "If we plan to handle ipfs:// links from other apps (https://github.com/brave/brave-ios/issues/7129) we should probably disable it in iframes. The same we did it for sms and tel schemes: https://github.com/brave/brave-ios/issues/6168"
It's also good timing to switch to a whitelist (https://github.com/brave/brave-ios/pull/6181#pullrequestreview-1142818253)

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-ios/issues/7013#issuecomment-1512855313
