### ISSUE TITLE
White gradient appears on the URL bar when clipping long URLs on private mode

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#7132]
### Description: 
The leading fade that is placed on the URL bar when a domain is too long to show in its entirety sometimes has the wrong colour

### Steps to Reproduce 
  1. Open a private tab
  2. Load a very long domain that exceeds the URL bar container (https://verylongdomainnametotestvariousthings.blogspot.com/)

### Actual result: 

https://user-images.githubusercontent.com/529104/226940548-e4df9b3d-91bd-46f1-89d5-5b66bf3add6e.mp4

### Expected result:

Should match the URL bar so it looks like a fade

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily

**Comment by Uni-verse** [comment]
Verified on `1.50 (23.4.12.13)` on `iPhone X` running `iOS 16.3.1`

Using STR in https://github.com/brave/brave-ios/issues/7132#issue-1635911182, verified that white gradient does not appear when clipping long URLs in Private mode.

![IMG_2942](https://user-images.githubusercontent.com/17885425/231505758-3cbbd4a4-ac41-47ba-8e68-e9e57808e63a.PNG)
