### ISSUE TITLE
Send button disabled when address missing checksum

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7136]
### Description: 

When we detect the send address is missing checksum, we display `This address cannot be verified (missing checksum). Proceed?` but the button to proceed / create the send transaction is disabled

### Steps to Reproduce 
  1. Open send in Wallet
  2. Select an Ethereum network
  3. Enter a to address in all lower-case
  4. Observe `This address cannot be verified (missing checksum). Proceed?` error copy shown, but `Send` button disabled.

### Actual result: 

![missing checksum](https://user-images.githubusercontent.com/5314553/227232881-7b587cfb-34fc-4ca5-ae49-46e65b7b0c1a.png)

### Expected result:

User should be able to create the transaction

### Reproduces how often: 

Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

Desktop logic changed for this warning in Nightly but old logic that matches iOS is still in v1.49.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 15.7.3 running 1.50 (23.4.17.16)
- Verified steps from [#7137](https://github.com/brave/brave-ios/pull/7137)
- Verified when all characters are lowercase, shows error but enables the Send button and shows the correct address in send confirmation screen
- Verified when all characters are uppercase, shows error but enables the Send button and shows the correct address in Send confirmation screen
- Verified when there is a mixture of upper and lowercase letters causing a mismatch in checksum, Send button is disabled 

Uppercase | Lowercase | Checksum mismatch
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/233071925-c2bd783c-05b6-42ff-a978-204bd660d204.png) | ![image](https://user-images.githubusercontent.com/17010094/233071729-6758725a-eebf-4a30-9863-19012f02687d.png) | ![image](https://user-images.githubusercontent.com/17010094/233071693-2cac0a24-5427-49ef-a12c-b64366b82e65.png)

--------------
Verification passed on iPad Pro with iOS 16.5 Beta running 1.50 (23.4.17.16)
- Verified steps from [#7137](https://github.com/brave/brave-ios/pull/7137)
- Verified when all characters are lowercase, shows error but enables the Send button and shows the correct address in send confirmation screen
- Verified when all characters are uppercase, shows error but enables the Send button and shows the correct address in Send confirmation screen
- Verified when there is a mixture of upper and lowercase letters causing a mismatch in checksum, Send button is disabled 

Uppercase | Lowercase | Checksum mismatch
-- | -- | --
![image](https://user-images.githubusercontent.com/17010094/233071875-f0cab241-cc27-4c03-8ac0-bbaf3038d9ea.png)| ![image](https://user-images.githubusercontent.com/17010094/233071627-33a93216-c320-48a9-b1d1-c44c198b13ff.png) | ![image](https://user-images.githubusercontent.com/17010094/233071607-9cdf383a-8bf6-42bf-929b-e9041d66c3b9.png)
