### ISSUE TITLE
Favicons sometimes flicker or take too long to load

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#7139]
### Description: 
- Sometimes when visiting a site, favicons will flicker on the tab tray
- Sometimes favicons flicker or load too slowly on the home screen
- When searching without a scheme such as `http`, favicons don't load until the page loads

### Steps to Reproduce 
  1. Visit search.brave.com
  2. Search for news ycombinator
  3. Visit the website
  4. Favicon should be "Y" if it doesn't load.
--
1. Open Tab tray
2. Close Tab Tray
3. Open Tab Tray
4. Repeat
5. Icon should be consistent and NOT flicker or load.

### Expected result:
- Icon should be consistent and load very fast

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Intermittent Issue

### Brave Version: 

- 1.49.x

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.49 (23.3.28.19)`

Followed the test steps in https://github.com/brave/brave-ios/issues/7139#issue-1638238594

- Confirmed Favicon has `Y` if it doesn't load
- Confirmed Favicon does not flicker or take too long to load when opening and closing tab tray

Example | Example
-|-
![IMG_2857](https://user-images.githubusercontent.com/17885425/228667827-75d40dc8-7e5a-413e-a472-4e419dc021a2.PNG) | ![IMG_2858](https://user-images.githubusercontent.com/17885425/228667843-a04c41e3-c5b5-4004-83fc-31b99d477e84.PNG)
