### ISSUE TITLE
Verify Wallet usage stats 

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7143]
### Description: 

Wallet usage stats stopped reporting correctly in v1.48 which should be resolved with: https://github.com/brave/brave-browser/issues/29305.

After a core bump, we need to re-verify https://github.com/brave/brave-ios/issues/5122:

- Verify `wallet2` query parameter exists when testing DAU ping (via proxy or working with stats team)
- Verify if wallet is not created, `wallet2` is always `0`
- Otherwise if wallet is created the value is based on last ping and last unlock date, see documentation of this helper method for more details: https://github.com/brave/brave-core/blob/a0bb8c80a1fafd2046ba359324ebd74a2b520dd9/components/brave_stats/browser/brave_stats_updater_util.cc#L107

**Comment by StephenHeaps** [comment]
Should be available in BraveDev `1.49 (23.3.28.19)` and later

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 16.4 running 1.49 (13.3.31.9)
- Verified wallet usage stats report correctly 

Wallet not used | Wallet used
-- | --
<img  src="https://user-images.githubusercontent.com/17010094/230038524-ffa18c56-6c5d-45be-9025-3271ab0e32ac.png"> | <img src="https://user-images.githubusercontent.com/17010094/230038542-768a066b-f681-46d6-a12f-056b105ed7b0.png">
