### ISSUE TITLE
Cleanup ContentBlockerManager and improve its speed.

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#7147]
### Description: 
The content blocker manager uses a timed sync mechanism. Because apple caches rule lists, this is actually not needed. We don't need to recompile anything on re-launches, just when settings and data changes. 

This caching way makes it very difficult to work with custom filter lists and adds extra overhead on background threads for no reason.

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.50 (23.4.25.20)`

Using Test Plan in https://github.com/brave/brave-ios/pull/7131#issue-1635615749

- Ensured that page has true for all values when loading `https://test-pages.privacytests.org/tracking_content.html.`
- Ensured that app launches relatively quickly with many filters enabled in the content filtering.
- Ensured that cosmetic filtering is working when loading `twitter.com` or `reddit.com`
- Ensured that script loading test page is passing, showing true when shields are up and null when shields down - https://dev-pages.brave.software/filtering/scriptlets.html

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_3028 2](https://user-images.githubusercontent.com/17885425/234921497-e84ca540-6d53-4ba8-9b6c-1d74df4a2f85.PNG) | ![IMG_3030](https://user-images.githubusercontent.com/17885425/234921545-fd0956b1-60f2-4aca-8ccc-cf6f2d87dcd1.PNG) | ![IMG_3031 2](https://user-images.githubusercontent.com/17885425/234921547-7fbacba4-5b8a-4e04-8b80-6c850a427f3c.PNG) | ![IMG_3032 2](https://user-images.githubusercontent.com/17885425/234921593-691ccac7-e4a5-4dca-932c-3b6cd94cf9e7.PNG) | ![IMG_3034 2](https://user-images.githubusercontent.com/17885425/234921617-1c1b6cb8-0e3e-40db-9571-e3c494896777.PNG) | ![IMG_3036](https://user-images.githubusercontent.com/17885425/234921619-6a599bc2-983e-4064-be28-d50c4508025c.PNG)
