### ISSUE TITLE
Playlist :: Last saved position isn't being saved

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#7158]
### Description: 
The updates coming via "Playlist Last Played Position" will hopefully resolve this but I find that the last saved position is rarely saved.

**Comment by hffvld** [comment]
Verified, the issue is not reproducible in build 1.50. Last played position for each video is saved and restored when Playlist/Brave is closed and reopened.

------------------

```
Device/OS: iPhone 14 [iOS 16.41]
Brave build: 1.50 (23.4.17.16)
```

https://user-images.githubusercontent.com/128532965/232875587-348ce752-b84b-4bcc-87dc-e183ae16ed25.mov
