### ISSUE TITLE
Migrate Session Restore to WebKit's Session Restore

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#7166]
## Problem Description 
- Current Session Restore uses URL hacks and parsing and Javascript to restore a web-page. This can be slow, introduce security flaws, etc.

## Feature Overview 
- We can use WebKit's interactionState to retrieve session info, and to restore it as well.
- This drastically reduces the amount of work needed to restore a session and will have much less bugs.

## Implementation Details 
- Use Chromium's SessionHistorySynthesizer
- Migrate Session Restore to WebKit's interactionState using the synthesizer
- Migrate session screenshots and cleanup the code

## User Experience 

1. Faster session restores
2. Less black screens
3. Everything is handled by WebKit & Apple instead of us
4. Less JS injection
5. Less potential security flaws

**Comment by Uni-verse** [comment]
@Uni-verse @vlad-hoff QA to test upgrading from 1.50 and 1.49 to ensure theres no issues with tabs migration from earlier versions for users.

cc: @kjozwiak

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` per https://github.com/brave/brave-ios/issues/7303#issuecomment-1544775490

Note: QA will also cover additional session/NTP scenarios in the manual passes https://github.com/brave/brave-ios/issues/7447 & https://github.com/brave/brave-ios/issues/7446

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `16.3.1` using version `1.51 (23.5.11.17)`

**_Fresh Profile_**

- Verified tabs are restored properly and in the same order when re-launching application.
- Verified active tab is restored correctly after relaunching.

Before | After
-|-
![IMG_1070](https://github.com/brave/brave-ios/assets/17885425/531c0494-3db1-4ba9-a3b4-8ba7d1d60c41) | ![IMG_1071](https://github.com/brave/brave-ios/assets/17885425/66078dc8-b5b6-489b-a02a-8bf16ad1f56a)



**_1.49 -> 1.51_**

- Verified tabs are restored properly and in the same order when upgrading from `1.49.1 (23.4.12.18)` -> `1.51 (23.5.11.17).`
- Verified active tab is restore from the previous version.
- Verified white screen was not encountered when restoring tabs

1.49 | 1.51
-|-
![IMG_1062](https://github.com/brave/brave-ios/assets/17885425/cd1a3947-fa47-404a-9904-886b2d376042) | ![IMG_1063](https://github.com/brave/brave-ios/assets/17885425/dfdb3f87-04c5-405b-bfd4-590aebb13e27)

**_1.50 -> 1.51_**

- Verified tabs are restored properly and in the same order when upgrading from `1.50 (23.4.25.20)` -> `1.51 (23.5.11.17).`
- Verified active tab is restore from the previous version.
- - Verified white screen was not encountered when restoring tabs

1.50 | 1.51
-|-
![IMG_1068](https://github.com/brave/brave-ios/assets/17885425/08cbaec2-ce8d-41a7-9727-2dd6f679f7cd) | ![IMG_1069](https://github.com/brave/brave-ios/assets/17885425/49fb618c-586a-4ec1-ab25-96c1487b9b79)
