### ISSUE TITLE
Brave News widget

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7168]
Related ticket https://github.com/brave/roadmap/issues/582

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` & `iPad (7th Gen)` running `iOS 16.4` using build version `1.50 (23.4.19.20)`

_Top News widgets on Homescreen_

- Verified that small news widget (single article) will rotates every 15m, refreshes after 60m on the homescreen
- Verified that medium news widget rotates every 15m, refreshes after 60m
- Verified large news widget rotates every 20m, refreshes after 60m
- Verified tapping on news article will load the article inside brave

Example | Example | Example | Example
-|-|-|-
![IMG_2975](https://user-images.githubusercontent.com/17885425/233462878-4a5fd17b-f5bd-47c9-b301-660cfbdbce09.PNG) | ![IMG_2976 2](https://user-images.githubusercontent.com/17885425/233462895-95dbe1dc-36a5-4e62-9ddd-8d8c0b7d34d5.PNG) | ![IMG_1050](https://user-images.githubusercontent.com/17885425/233463324-ef8388ba-2ae6-4277-997e-3c024dc86e97.PNG) | ![IMG_1053](https://user-images.githubusercontent.com/17885425/233463329-b4dd2fb8-b2ed-451d-a7fc-ca32750abe60.PNG)


_Top News widgets on Lockscreen_

- Verified that small news widget (single article) will rotates every 15m, refreshes after 60m on the lockscreen

Example | Example
-|-
![IMG_2979 2](https://user-images.githubusercontent.com/17885425/233462913-664d751a-efd5-4504-931d-d30a8961fe76.PNG) | ![IMG_2982](https://user-images.githubusercontent.com/17885425/233463711-4e98b27c-eca5-405f-8bb9-9c9553a104dc.PNG)
