### ISSUE TITLE
Wallet: NFT tab

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#7173]
Specs: https://docs.google.com/document/d/1pDQwtGIk3xTrYI_3XTHCMqN-sLdUPfgGDDjAgi295bQ/edit#heading=h.kdsk65e6o18b

1. Remove NFT section from Portfolio 
2. Add NFT tab which displays all selected user's visible NFTs
3. Click each NFT inside NFT will open its details screen
4. Network filter that filters NFTs inside NFT tab

**Comment by diracdeltas** [comment]
cc @stoletheminerals - need to ensure that NFT's that contain js/html don't get executed

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.51(23.4.28.18)
- Verified steps from [#7174](https://github.com/brave/brave-ios/pull/7174)
- Verified there is no NFT section under portfolio
- Verified NFT is now listed in a separate tab
- Verified able to add NFTs from different chain 
- Verified selecting an NFT shows the image and NFT details
- Verified able to filter NFTs based on network filter 

iPhone 7+ (iOS 15.7.3) | iPhone 13 (iOS 16.4.1) | iPad Pro (16.4 Beta 4)
-- | -- | -- 
<video src=https://user-images.githubusercontent.com/17010094/236509276-ceb143a8-17fd-4707-aedc-b78192842ba1.MP4> | <video src=https://user-images.githubusercontent.com/17010094/236498663-973f92fe-1b50-4b66-a704-705b288163fe.mp4> | <video src=https://user-images.githubusercontent.com/17010094/236499289-057813b5-120d-43bf-ab93-f563e5f1024e.MP4>
