### ISSUE TITLE
Origin Password section shown for Add Solana Account

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7175]
### Description: 

Json password field is shown when json is detected in private key field, but json import is disabled for Solana

### Steps to Reproduce 
  1. Open Add Account view and select Solana
  2. Enter any json (ex. `{}`) in the private key field
  3. Observe Origin Password section now shown

### Actual result:

![Simulator Screen Shot - iPhone 14 Pro - 2023-03-30 at 17 32 13](https://user-images.githubusercontent.com/5314553/228969927-ecd9ad76-1743-4c2a-b52a-30164ef3968b.png)

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 16.3.1 running 1.49 (23.3.31.9)
- Verified Origin password section is not shown for adding Solana account
- Verified Origin password section is still shown for adding Ethereum account

https://user-images.githubusercontent.com/17010094/229173531-70f224cc-0bce-4b18-896f-b72540549043.MP4

---------
Verification passed on iPad Pro with iOS 16.4 Beta 4 running 1.49 (23.3.31.9)
- Verified Origin password section is not shown for adding Solana account
- Verified Origin password section is still shown for adding Ethereum account

https://user-images.githubusercontent.com/17010094/229173499-7e36190f-a821-48f2-81c4-964a36e17411.MP4
