### ISSUE TITLE
2.0 Toolbars

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#718]
### Address Bar

![address bar light](https://user-images.githubusercontent.com/318119/51147446-1f498a00-180f-11e9-926b-86bee2f30706.png)
![address bar dark mode](https://user-images.githubusercontent.com/318119/51147447-1f498a00-180f-11e9-9cdb-4952e08e68ea.png)
![address bar private](https://user-images.githubusercontent.com/318119/51147449-1f498a00-180f-11e9-8298-dfcbf1c6c599.png)

### Toolbar
![toolbar light](https://user-images.githubusercontent.com/318119/51147469-31c3c380-180f-11e9-90c5-dbc7b67e3188.png)
![toolbar dark mode](https://user-images.githubusercontent.com/318119/51147470-31c3c380-180f-11e9-8d4e-8be7e8ec364f.png)
![toolbar private](https://user-images.githubusercontent.com/318119/51147471-31c3c380-180f-11e9-8daf-13f8c8cfdb2c.png)

### More Menu

![browser more menu](https://user-images.githubusercontent.com/318119/51147482-3ee0b280-180f-11e9-8451-74fce8c165ed.png)

- More menu should inherit background color of toolbar

### iPad
![toolbar-tabs](https://user-images.githubusercontent.com/318119/51150854-28d9ee80-181d-11e9-815a-008b4d1dcdb6.png)

- Tabs always visible on iPad and landscape XS Max and Plus. Single tab open will keep same design pattern.

**Comment by jhreis** [comment]
Closing this epic, as no longer using Zenhub.
