### ISSUE TITLE
[Follow up to #6868] Playlist icon is not shown url bar always on soundcloud

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#7180]
### Description: 
Playlist icon initially shown in url bar when loading a video but if i go back to homepage and try another video it's not shown.

Follow up to https://github.com/brave/brave-ios/issues/6868

### Steps to Reproduce 
  1. Navigate to soundcloud.com
  2. Play a video, open the full player view. Confirm playlist icon shows
  3. Go back to results
  4. Open another video

### Actual result: 
Playlist icon is not shown

First video | Another video
-|-
![IMG_4664](https://user-images.githubusercontent.com/17885425/229185932-dbd20cfd-cf88-4942-82aa-0b8e12c9befe.PNG) | ![IMG_4665](https://user-images.githubusercontent.com/17885425/229185938-0516d3d3-50d3-451e-ae5b-4add392b9665.PNG)

### Expected result:
Playlist icon should be shown

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

### Brave Version:  `1.49 (23.3.31.9)`

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? N/A

### Device details: 
`iPhone 12`, `iOS 16.4`
`iPhone X`, `iOS 16.3.1`

**Comment by Brandon-T** [comment]
Cannot be fixed due to the way soundcloud works (Soundcloud does not use an audio tag and the page itself modifies history manually).

Fixing this issue breaks other websites.
