### ISSUE TITLE
`Block Switch to App Notices` switch no longer works

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#7188]
### Description: 
**Context:** 
We have had some issues with the switch in recent releases where the setting switch itself was changing state after navigating out of settings and therefore app was not blocking the `switch to app notices` on webpages when enabled. After fixing the issue with the switch state, it was determined that `block switch to app notices` which is linked to `fanboy mobile notifications` list is no longer blocking these type of pop ups. However, `fanboy web annoyances` in the `content filter` list seems to be blocking these now instead when enabled. This has changed since this switch was working as expected on 1.46.x with mobile pop ups.

### Steps to Reproduce 
  1. Clean Install `1.49 (23.3.31.9)`
  2. Wait a few mins for scripts to load
  3. Visit `https://google.com/maps` or `twitter.com` or `reddit.com`

### Actual result: 
google | twitter | reddit
-|-|-
![IMG_2884](https://user-images.githubusercontent.com/17885425/229563250-04fe69e2-b333-4f3b-9cbc-ba87fcd03196.PNG) | ![IMG_2885](https://user-images.githubusercontent.com/17885425/229563255-6fa8b0e3-7870-4a3f-8862-e82c4188be2c.PNG) | ![IMG_2886](https://user-images.githubusercontent.com/17885425/229563261-e6a33262-0ec0-451d-b59c-19ee1c848693.PNG)

### Expected result:
Popups should be blocked

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

### Brave Version:  `1.49 (23.3.31.9)`

- Can you reproduce this issue with the most recent build from TestFlight?  Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
`iPhone X`, `iOS 16.3.1`

**Comment by soner-yuksel** [comment]
I am having a similar problem related with **Cookie Consent Notices**. I think we must fix this before releasing 1.49.
@iccub @cuba 

Some examples:

![1 1 1 2](https://user-images.githubusercontent.com/6643505/229571517-417b338f-5a7a-4da4-bcbd-88204677904b.png)

**Comment by Uni-verse** [comment]
Closing as done based on https://github.com/brave/brave-ios/commit/39b66f1ac891f1a3d28cc9ceebc03236f6608c1c

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.49 (23.4.3.20)`

Test Plan: https://github.com/brave/brave-ios/issues/7188#issue-1652349885

- Ensured that open in app dialogs are blocked when loading `reddit.com`, `twitter.com`, `linkedin.com` and `google.com/maps`
- Ensured that `Block Switch to App Notices` is enabled by default on clean profile
- Ensured that disabling `Block Switch to App Notices` or `Fanboy Mobile noticifications` list will show the open in app dialogs

Default (ON) | Default (ON) | Default (ON)  | Default (ON) | Default (ON) | Default (ON)
-|-|-|-|-|-
![IMG_2899](https://user-images.githubusercontent.com/17885425/229636137-efa5c957-4b6f-4a91-948c-a57f0ca12a71.PNG) | ![IMG_2900](https://user-images.githubusercontent.com/17885425/229636150-ad0e2c79-23dc-4804-935e-46ffbc647c98.PNG) | ![IMG_2901](https://user-images.githubusercontent.com/17885425/229636153-2467f21c-d8f8-4969-8fc1-6b807ed171b0.PNG) | ![IMG_2902](https://user-images.githubusercontent.com/17885425/229636155-44ddfa67-dea7-4068-8abd-874f07ebf044.PNG) | ![IMG_2903](https://user-images.githubusercontent.com/17885425/229636156-ba13bfad-f20c-4634-bbcb-dafd6df0aaa1.PNG) | ![IMG_2904](https://user-images.githubusercontent.com/17885425/229636870-4d1bfe95-fa98-4fd1-aee8-492530395b07.PNG)
OFF | OFF | OFF | OFF | OFF | OFF
![IMG_2905](https://user-images.githubusercontent.com/17885425/229636953-961f8c0f-2b46-460e-93f2-35c2e56fac90.PNG) | ![IMG_2906](https://user-images.githubusercontent.com/17885425/229636955-b2a0f024-e03e-4485-98f5-993ef5212f74.PNG) | ![IMG_2907](https://user-images.githubusercontent.com/17885425/229636957-ad8dcbec-b89f-40c4-bf2c-d98feda2aba9.PNG) | ![IMG_2908](https://user-images.githubusercontent.com/17885425/229636960-97e56f63-52a9-48aa-8d42-a27121019853.jpg) | ![IMG_2909](https://user-images.githubusercontent.com/17885425/229636961-ee90f44b-234f-468f-95e8-688c4aa2690d.PNG) | ![IMG_2910](https://user-images.githubusercontent.com/17885425/229636962-df03f2be-818b-4691-8ed6-44dfc41513c6.PNG)
