### ISSUE TITLE
Add `scriptletGlobals` to Brave iOS

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-ios#7194]
iOS version of https://github.com/brave/brave-browser/issues/29435, see there for details

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.50 (23.4.19.20)`

- Ensured that tests are passing (showing `true` values) when loading `https://dev-pages.brave.software/filtering/scriptlets.html` based on the Test Plan in https://github.com/brave/brave-ios/pull/7195#issue-1652811801

- Ensured that the following websites are loading successfully:
https://explorecams.com/photos/model/canon-eos-5d-mark-ii
https://waves4you.com/

- Ensured that scriptlets test plan is passing on an `existing profile` when upgrading from version `1.49.1`


Example | Example | Example
-|-|-
![IMG_2984](https://user-images.githubusercontent.com/17885425/233686713-d84cb74a-2876-4b6a-90ab-3bd8b5abce04.PNG) | ![IMG_2985 2](https://user-images.githubusercontent.com/17885425/233686718-9b911954-8546-4b8b-bcd2-48ff8f6844a2.PNG) | ![IMG_2986 2](https://user-images.githubusercontent.com/17885425/233686723-f278efd7-a179-4f5e-abd0-0644e9dbb739.PNG)
