### ISSUE TITLE
SKU credential (in VPN) should be cached indefinitely until redeemed or expired

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#7196]
### Description: 
This is the iOS version of https://github.com/brave/brave-browser/issues/29345 - which fixed for Desktop/Android.

Basically, when a person enables VPN by visiting account.brave.com the time-limited credentials v2 are used. Through the SKU SDK, the `prepare_credentials_presentation` is called and a credential is presented. We're already parsing this partly because we need to get the expiration date.

Besides storing expiration date, we should also store the credential **until it gets redeemed** (or it expires). If Guardian's API has a service outage when we are requesting subscriber credentials, I don't believe we are retrying. If we try to call `prepare_credentials_presentation` again, it'll report that the user is out of credentials and ultimately they have to wait until the next day

**Comment by bsclifton** [comment]
Solution for Desktop/Android one here:
https://github.com/brave/brave-core/pull/17789

One thought which might help keep implementation clean (kudos to @simonhong):
Just like how we cache the subscriber credentials, we also cache the SKU credential until it's redeemed. On Desktop/Android, the cached value being persisted to disk (which has subscriber credential)  is a dictionary (`base::Value::Dict`). 
- After SKU SDK present is called (but BEFORE subscriber credentials issued), this has two values (`expiration` and `skus_credential`)
- After subscriber credentials are redeemed, a new empty dictionary is created and only the new fields are written (`expiration`, `credential`)

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.50 (23.4.27.20)`

Using Test Plan in https://github.com/brave/brave-ios/pull/7253#issue-1668495736

- Ensured purchasing VPN from account.brave.com works and VPN connection is establish. 
- Ensured disabling and then re-enabling VPN is successful
- Ensured changing region in VPN settings is successful and connection is updated.

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_3059](https://user-images.githubusercontent.com/17885425/235191925-79148242-87a5-4c5c-9a7e-a38b75164f61.PNG) | ![IMG_3060](https://user-images.githubusercontent.com/17885425/235191928-a52ac7e5-4b86-4a1f-a4f0-33007bc2a9e8.PNG) | ![IMG_3061](https://user-images.githubusercontent.com/17885425/235191929-b7ef0c6d-90fc-4077-8a77-3553c014688d.PNG) | ![IMG_3062](https://user-images.githubusercontent.com/17885425/235191937-2fd19df4-f675-4e4a-b1b8-530d72da9340.PNG) | ![IMG_3063](https://user-images.githubusercontent.com/17885425/235191939-4013db83-5499-4487-b708-1bb4e9b62930.PNG) | ![IMG_3064](https://user-images.githubusercontent.com/17885425/235191942-00f82f3a-143d-4ac2-86e3-560969bbb4d4.PNG)
