### ISSUE TITLE
Wallet: Activity tab

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7198]
### Description: 

Integrate activity tab for transactions in wallet. 

Networks & Accounts filter separated to https://github.com/brave/brave-ios/issues/7233

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.
- Verified steps from [#7248](https://github.com/brave/brave-ios/pull/7248)
- Verified Activity tab lists all the submitted and unsubmitted tranactions
- Verified rejected transactions are not listed
- Verified transactions from all networks are listed
- Verified clicking on the transaction shows the details as expected

iPhone 13 (iOS 16.4.1) | iPad Pro (16.4 Beta 4)
-- | -- 
<video src=https://user-images.githubusercontent.com/17010094/236809218-06c6776c-29f9-4fd8-a510-b19d3561c235.MP4> | <video src=https://user-images.githubusercontent.com/17010094/236810885-b252d1f6-5c55-4b37-a629-139299f15bb4.MP4>
