### ISSUE TITLE
Sync code/QR Code says above but is actually below

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#720]
### Description:
Sync code/QR Code says above but is actually below

### Steps to Reproduce

  1. Create a sync chain on Desktop
  2. Enable Camera access and try to scan QR code
  3. Add a new device option screen says QR Code/Code words above but its actually below the text

### Actual result:
![image from ios 1](https://user-images.githubusercontent.com/17010094/51179308-1f1ebc80-18eb-11e9-8164-2b6a9797a0ab.png)
![image from ios](https://user-images.githubusercontent.com/17010094/51179309-204fe980-18eb-11e9-8e8b-2f9508f38f09.png)

### Expected result:
Should be corrected

**Reproduces how often:** [Easily reproduced/Intermittent issue]
Easy

**Brave Version:** 
1.7.3 (19.01.14.19)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by LaurenWags** [comment]
* Verified passed with 1.9 (19.3.9.1) on iPad 5th Gen 

![IMG_D1EC69AD5EE5-1](https://user-images.githubusercontent.com/28145373/54380516-108e2080-4662-11e9-9241-0077de6f1f51.jpeg)

![IMG_525E7F749218-1](https://user-images.githubusercontent.com/28145373/54380521-12f07a80-4662-11e9-9480-2d3db29c4517.jpeg)

* Verified passed with 1.9 (19.3.9.1) on iPhone SE
* Verified passed with 1.9 (19.3.9.1) on iPhone 8
* Verification passed on iPhone 7/6 and iPad Pro running 1.9(19.3.9.1)
* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR.
