### ISSUE TITLE
Tx Confirmation presented over Asset Detail dismisses automatically

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7200]
### Description: 

Transaction confirmation view dismisses automatically when presented over asset detail view

### Steps to Reproduce 
  1. Visit an asset detail page via Portfolio
  2. Tap Send/Swap and create the transaction
  3. Observe tx confirmation is shown, but dismisses automatically

### Actual result: 

https://user-images.githubusercontent.com/5314553/229853630-01e0b000-ccef-4a37-bf97-6efc398d78f6.mp4

### Expected result:

Does not dismiss automatically

### Reproduces how often: 

Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by StephenHeaps** [comment]
Similar to regression of https://github.com/brave/brave-ios/issues/6460

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 16.5 beta running 1.49.1(23.4.12.18)
- Verified steps from [#7203](https://github.com/brave/brave-ios/pull/7203)
- Verified creating a new wallet shows enable biometric modal
- Verified restoring a wallet shows enable biometric modal 
- Verified dismissing biometric doesn't cause any issue during wallet creation or restore
- Verified `Bridge to Aurora` shows the popup correctly each time
- Verified selecting `Do not show again` on the `Bridge to Aurora` modal doesn't show it again 
- Verified Buy/Send/Swap modal is not auto-dismissed when changing network in respective screen
- Verified transaction confirmation screen is not auto-dismissed and shows details as expected for both send and swap transactions

https://user-images.githubusercontent.com/17010094/231739101-3467b899-3b98-4a25-b6a4-d7f858a6937d.MP4
