### ISSUE TITLE
Wallet: Market Tab

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#7202]
Description:
Integrate market tab. 
Figma: https://www.figma.com/file/muVcmcu4RFNu0LkXe9VRDl/Wallet-Panel?node-id=1406-218312&t=EssV5dFsjKICuh2p-0
Each Token row should show:
Token name, token symbol, token image, 24h price change %, price of asset
Tapping an asset will open to Asset Details

TBD:
1. search
2. filter
3. sorting
4. rank

Desktop screenshot for reference
<img width="994" alt="Screenshot 2023-04-04 at 12 43 22 PM" src="https://user-images.githubusercontent.com/1187676/229860268-863d7f4c-36f7-4d97-afea-702fa63c3496.png">

**Comment by diracdeltas** [comment]
may need a quick security review

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.51 (23.4.28.18)
- Verified steps from [#7298](https://github.com/brave/brave-ios/pull/7298)
- Verified wallet now shows a Market tab
- Verified switching to Market tab shows loading state populating the token list
- Verified token's name, symbol, logo, current price and price delta is shown
- Verified clicking on any token navigates to the token detail screen
- Verified inside token detail screen there is no information related to the active/selected network 
- Verified inside token detail screen, there is no account balances or transactions listed
- Verified inside token detail screen, price, price delta and price history are being shown
- Verified inside token detail screen, token  rank, 24h volume and market cap information are being shown
- Verified tokens pertaining to the selected network show `Buy` button in token details screen but tokens of different network doesn't show the `Buy` button in token details screen

iPhone 7+ (iOS 15.7.3) | iPad Pro (16.4 Beta 4)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/236385438-33b85db4-1e17-41eb-afeb-3b956353c3ac.MP4> | <video src=https://user-images.githubusercontent.com/17010094/236385498-930f81b5-e296-492c-9e81-42b642508ea4.MP4>
