### ISSUE TITLE
Cannot change region

### ISSUE THREAD

**Issue by TroySigX** [brave/brave-ios#7204]
### Steps to Reproduce 
  1. Search something on using brave engine
  2. Attempt to change search region (e.g United States to Global)
  3. Attempt failed

### Actual result: 
![image](https://user-images.githubusercontent.com/88051085/229948452-5a7d5591-a5d8-4e0d-bd8c-98f278bf3a40.png)
As you can see, they whole panel turns grey

### Expected result:
Should be able to change region

### Brave Version: v1.48.1

- Can you reproduce this issue with the most recent build from TestFlight? Not tried
- Can you reproduce this issue with the previous version of the current build from TestFlight? Not tried
- Can you reproduce this issue with the current build from AppStore? Yes

### Website problems only:
- did you check with Brave Shields down? Yes
- did you check in Safari/Firefox (WkWebView-based browsers)? Not related

### Additional Information

**Comment by kylehickinson** [comment]
Hi @TroySigX is this still happening for you? Seems like it may have been specific to Brave Search and not the iOS app as I wasn't able to reproduce it with shields up or down on both app store builds and local builds.

**Comment by TroySigX** [comment]
The issue still persists. It open happens on my Ipad (IpadOS), but not my Iphone (IOS).

**Comment by kylehickinson** [comment]
Thanks @TroySigX, we've figured out the issue and this will be fixed on the Brave Search side of things (https://github.com/brave/search/pull/7459). I'm going to close this for now as there's nothing left for us to do on the iOS side. Hopefully you will see this fix soon!
