### ISSUE TITLE
Playlist Favicons Flicker or show Tiny

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#7207]
### Description: 
- Sometimes Playlist favicons flicker: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1680514620667379
- Sometimes icons render way too small

### Steps to Reproduce Flickering
  1. Add a video to Playlist (the video needs to be one that does NOT have thumbnails, and has favicons only)
  2. Open Playlist
  3. The favicon renders
  4. Close Playlist
  5. Open Playlist
  6. The favicon renders, but it takes some time, and can look like it's not cached properly.

### Steps to Reproduce (Tiny icons - This can happen on playlist but is much easier to reproduce on the Favourites screen!)
  1. Fresh install
  2. Visit youtube
  3. QUICKLY close the tab!
  4. Youtube Favourite icon is now blurry instead of crisp.

### Expected result:
- Smooth icon rendering
- Crisp icons

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Intermittent Issue

### Brave Version: 
- 1.49.x

### Device details: 
- Any

### Website problems only:
- Kind of (Youtube specifically for blurry icons as they can return a 16x16 favicon.co from: https://m.youtube.com/static/favicon.ico. However, the desired icon is: https://m.youtube.com/static/apple-touch-icon-180x180-precomposed.png)

**Comment by hffvld** [comment]
Verified and opened follow up issue #7271 - "Favicons still flickers or shown blurry in build 1.50"

------------------

```
Device/OS: iPhone 14 [iOS 16.3]
Brave build: 1.50 (23.4.17.16)
```
