### ISSUE TITLE
Disable orientation change for Sync screens on iPhone

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#721]
### Steps to Reproduce 
  1. Launch sync in horizontal mode

**Actual result:** 
![zrzut ekranu 2019-01-15 o 13 40 50](https://user-images.githubusercontent.com/6950387/51181366-42d20a80-18cb-11e9-9ea9-837574872835.png)

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
Solution for this was to lock entire settings screen orientation.

**Comment by srirambv** [comment]
Verification passed on iPhone 7  running 1.9(19.3.9.1)
![Image from iOS](https://user-images.githubusercontent.com/17010094/54381300-cad25780-4663-11e9-9ca0-dc90c3942b32.png)

Verified passed with 1.9 (19.3.9.1) on iPhone SE 
Verified passed with 1.9 (19.3.9.1) on iPhone 8
