### ISSUE TITLE
[Feature-Request] Block Playlist from showing up on Brave-Talk

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#7213]
### Description: 
- Playlist should not show up in the menu, long-press menu, or URL bar on Brave-Talk
- https://bravesoftware.slack.com/archives/CKJCXTP9B/p1680794411049629

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.50 (23.4.27.20)`

- Confirmed `Add to Brave Playlist` option is removed from the share menu when using Brave Talk
- Confirmed Playlist option is shown in share menu when using app version 1.49.1 and then is not available after upgrading to 1.50 (23.4.27.20).

1.49.1 | 1.50
-|-
![IMG_3047](https://user-images.githubusercontent.com/17885425/234995296-e87eeac4-44b3-4434-8b44-b20b34045604.PNG) | ![IMG_3046 2](https://user-images.githubusercontent.com/17885425/234995275-1f23d456-7dcf-4d55-98ab-f871dac088ae.PNG)
