### ISSUE TITLE
"Block cross-site trackers" blocks Stripe payment UIs

### ISSUE THREAD

**Issue by awalker-stripe** [brave/brave-ios#7217]
### Description: 
Hello! 👋 Stripe here. We've been getting reports that Brave on iOS is blocking certain merchants' checkout flows. In particular, users are blocked from being able to submit payment details through our Elements UIs.

### Steps to Reproduce 
  1. On Brave on iOS, visit https://stripe.dev/elements-examples/

### Actual result: 

Below the phone field, our card form does not load:

![brave](https://user-images.githubusercontent.com/51334696/230690495-ce327bec-897e-4907-a454-867060fc28fe.PNG)

### Expected result:

Card form below the phone field: 

![safari](https://user-images.githubusercontent.com/51334696/230690477-da85e935-6b05-4645-853c-80e18178f5dd.PNG)

### Brave Version: 

Current build from App Store: v1.49 (23.4.3.20)

### Device details: 
iPhone 11 and iPhone 13 (iOS 16.1.1)

### Website problems only:
Unchecking "Block Cross-Site Trackers" allows the card form to appear fine. Website works in Safari iOS.

**Comment by fruchtose-stripe** [comment]
I can also add that this issue is not present in Brave for macOS.

**Comment by ryanbr** [comment]
I'm not able to see this, what filter lists are enabled?

![unnamed-stripe](https://user-images.githubusercontent.com/1659004/231598566-1feabf52-9912-4698-bb10-1735c4aee7be.jpg)

**Comment by iccub** [comment]
Are you still able to reproduce it?
We had a bug on Friday with filter lists which were fixed and updated shortly after this ticket has been created so maybe the issue is resolved by now?

**Comment by fruchtose-stripe** [comment]
Hi @iccub. Thank you for the response. I just tried to reproduce using the instructions above. I'm happy to say that payment form is now showing as expected. Thank you so much for fixing this issue! I will close this out on my end.
