### ISSUE TITLE
[iOS] Rewards: Remove "Transfer your existing wallet funds to a desktop wallet" messaging

### ISSUE THREAD

**Issue by Miyayes** [brave/brave-ios#7219]
## Description

Messaging here about transferring BAT to a desktop wallet should be removed:

![image](https://user-images.githubusercontent.com/11497541/230926566-eb511372-9d71-4d82-9b19-bcab9928d1ea.png)

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` & `iPad (9th Gen)` running `iOS 15.6.1` using `1.51 (23.4.28.18)`

- Ensured that message is removed from Rewards settings page

Example | Example | Example
-|-|-
![IMG_3099](https://user-images.githubusercontent.com/17885425/236317191-6fff4921-7ce4-4c81-b92a-c0acc9ecf924.PNG) | ![IMG_3100](https://user-images.githubusercontent.com/17885425/236317198-a28687b1-3a86-498a-8e56-5629a36fc773.PNG) | ![IMG_0231 3](https://user-images.githubusercontent.com/17885425/236317218-c1041994-d878-4421-b04e-cc29dbbb2b60.PNG)
