### ISSUE TITLE
CSS Transitions not animating

### ISSUE THREAD

**Issue by ghostlexly** [brave/brave-ios#7224]
### Description: 
CSS Transitions are not animating properly. It's as though the CSS value goes from one state to another with no transition applied.

### Steps to Reproduce 
  1. Open a website that uses CSS Transitions. https://anytype.io/ and https://vercel.com/workflow are good examples. You can also check the material ui's "drawer" https://mui.com/material-ui/react-drawer/
  2. The transitions don't work

### Actual result: 
Same as the issue #5177 

### Expected result:
Same as the issue #5177 

### Reproduces how often:
Easily Reproduced

### Brave Version: 

1.49 (23.4.3.20)

### Device details: 

iPhone 13 , iOS 16.2

### Website problems only:
- did you check with Brave Shields down? 
yes
- did you check in Safari/Firefox (WkWebView-based browsers)? 
yes, works on both

**Comment by kylehickinson** [comment]
Tested this on latest release version and no problems here (iPhone 13 Pro, 16.4).  I saw in the other issue that they mentioned resetting experimental Safari features helped. Also you don't have lockdown mode enabled right?

**Comment by Uni-verse** [comment]
Verified on `iPad (9th Gen)` running `iPadOS 15.6.1` using version `1.51 (23.5.15.14)`

- Ensured CSS transitions are working on the following sites:

- [x] https://anytype.io/
- [x] https://vercel.com/workflow

- Ensured react-drawer menu is expanded in https://mui.com/material-ui/react-drawer/

Example | Example | Example
-|-|-
![IMG_0236 2](https://github.com/brave/brave-ios/assets/17885425/a5bcfd91-8c5e-4a7e-a893-b66ab9d1c407) | ![IMG_0237 2](https://github.com/brave/brave-ios/assets/17885425/5675171c-9409-4cc6-9d0e-ba77cf351aac) | ![IMG_0238 2](https://github.com/brave/brave-ios/assets/17885425/181dfdbf-bb9d-4cd4-ad9e-e82d30ec8819)
