### ISSUE TITLE
Implement selected network per origin

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7225]
Parent issue: https://github.com/brave/brave-browser/issues/24414
Android issue: https://github.com/brave/brave-browser/issues/29635

Core network related API will have optional `Origin` when setting/getting network. If origin is not provided, a fallback default network will be used. (one per coin type)

**Comment by darkdh** [comment]
Update:

1. `JsonRpcService.getChainId(CoinType coin, url.mojom.Origin? origin)` has been split into `GetDefaultChainId` and `GetChainIdForOrigin`
2. There are convenient methods `GetChainIdForActiveOrigin` and `SetChainIdForActiveOrigin` in `BraveWalletService` can be used if `BraveWalletServiceDelegate::GetActiveOrigin` has been implemented properly on the platform

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 16.5 running 1.52 (23.6.9.13)
- Verified steps from [#7470](https://github.com/brave/brave-ios/pull/7470)
- Verified changing network per tab is retained
- Verified Buy/Send/Swap retains the previously selected network
- Verified able to submit transactions on different networks in different tabs 
- Verified able to set different networks on different tabs and panel reads the correct network when switching between tabs
- Verified selected network doesn't affect a pending transaction when user changes network on Buy/Send/Swap screen
- Verified submitted transactions shows correct network in activity details 
- Verified adding a custom network and switching to it is only set to that domain. Navigating to a different site shows default coin selection on Panel

<video src=https://github.com/brave/brave-ios/assets/17010094/32f9277c-7986-425e-807c-2f0710b7f788> | <video src=https://github.com/brave/brave-ios/assets/17010094/887cafd8-ed9c-489a-9b25-f74244276629> | <video src=https://github.com/brave/brave-ios/assets/17010094/c67471a0-21a2-43c9-b177-b601c6871110>
-- | -- | --
