### ISSUE TITLE
IPNS links from other apps.

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#7227]
Similar to #7129 we want to support user opening `ipns://` scheme url from other apps.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.50 (23.4.17.16)
- Verified steps from [#7228](https://github.com/brave/brave-ios/pull/7228)
- Verified IPNS links opened from other apps switches context to Brave and loads the page depending on what the setting is set to (Ask/Enabled/Disabled)

iPhone 7+ (iOS 15.7.3) | iPad Pro (iOS 16.5 Beta)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/233035681-6a901ec6-2fac-4baa-b797-13c3ad2f2dcd.MP4
> | <video src=https://user-images.githubusercontent.com/17010094/233035532-80e3c5b2-bac7-4e33-825c-549dfd3afea6.MP4>
