### ISSUE TITLE
"Dark Mode" setting is inverting image colors on presearch.com

### ISSUE THREAD

**Issue by jejopl** [brave/brave-ios#7229]
### Description: 
"Dark Mode" setting is inverting image colors on presearch.com

### Steps to Reproduce 
  1. Enable dark mode on the browser
  2. Visit presearch.com

### Actual result: 

![image](https://user-images.githubusercontent.com/32012330/231418407-8ac64e55-f78f-4d11-a406-9548f6110e5e.png)

### Expected result:
![image](https://user-images.githubusercontent.com/32012330/231418792-2060ff65-909d-41b1-914e-2049b87d6a9d.png)

### Brave Version: 1.48.1 (23.3.2.0)

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down?  yep
- did you check in Safari/Firefox (WkWebView-based browsers)? yep

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: iPhone 14 [iOS 16.4.1] and iPad Air [iPadOS 16.4.1]
Version: 1.51 (23.5.8.18) 
BraveCore: 1.51.110 (113.0.5672.77)
```
---------------------------

**STEPS:**
1. Enable Dark Mode on the browser
2. Visit presearch.com

**ACTUAL RESULTS:**
- Verified proper theme is applied and color of the text/pics is not inverted

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/02db6ced-7851-4a92-9d8d-4bb4a4eee965) | ![2](https://github.com/brave/brave-ios/assets/128532965/9d46f92a-c9d1-4b85-8f9f-440b25b3743c) | ![3]() | ![4]() |
|3|4|
| ![3](https://github.com/brave/brave-ios/assets/128532965/78f9ca00-565f-4463-9e27-77bad389e395) | ![4](https://github.com/brave/brave-ios/assets/128532965/7495587e-8762-47d2-a5e5-c61cfe0cd183) |
