### ISSUE TITLE
Fingerprinting is broken on iOS

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#7231]
### Description: 
Fingerprinting is broken on iOS

#### Test 1
  1. Go to https://dev-pages.brave.software/fingerprinting/farbling.html (the green page)

#### Actual result: 
- "Plugins" show `0000000`
- "Plugins", "Hardware Concurrency", and "Speech Voices" should be the same for all frames (not broken, just needs to be tested)

#### Expected result:
- [ ] "Plugins" should show a random value
- [ ] "Plugins", "Hardware Concurrency", and "Speech Voices" should be the same for all frames

#### Test 2
  2. Take note of the values of "Plugins", "Hardware Concurrency", and "Speech Voices",
  3. Refresh the page

#### Actual result: 
- Same values on both pages (this is not broken, just needs to be tested) 

#### Expected result:
- [ ] Same values on both pages

#### Test 3
  4. Take note of the values of "Plugins", "Hardware Concurrency", and "Speech Voices",
  5. Click on "Other page" (the red page)

#### Actual result: 
- Same values on both pages

#### Expected result:
- [ ] Different values on both pages

#### Test 4
  6. Take note of the values of "Plugins", "Hardware Concurrency", and "Speech Voices",
  7. Terminate the application (don't delete it) and re-launch it
  8. Load the same page on Test 3 (the red page) (should load automatically)

#### Actual result: 
- The values are the same as before the launch

#### Expected result:
- [ ] The values should not be the same

#### Test 5
  9. Verify Test 3 but on the green page
  10. Terminate the application (don't delete it) and re-launch it
  11. Load the same page on Test 3 (the red page) (should load automatically)

#### Actual result: 
- The values are the same as before the launch

#### Expected result:
- [ ] The values should not be the same

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

### Brave Version: 
1.4.8

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details: 
Any

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Caused by a broken farbling script

**Comment by Uni-verse** [comment]
Verified on `1.49.1 (23.4.12.18)` on `iPhone X` running `iOS 16.3.1`

Test Plan: https://github.com/brave/brave-ios/issues/7231#issue-1664912095

<details><summary>Test 1</summary>

- "Plugins" should show a random value
- "Plugins", "Hardware Concurrency", and "Speech Voices" should be the same for all frames

<img width="400" alt="0" src="https://user-images.githubusercontent.com/17885425/231827386-2d3a0a0d-4607-4846-9819-de68d0d1a601.jpg">

</details>

<details><summary>Test 2</summary>

- Confirmed values are the same on both test pages

Test 2A | Test 2B
-|-
![IMG_2950](https://user-images.githubusercontent.com/17885425/231827558-5b0616f3-8334-4c0a-b07a-e3df2f4977b9.jpg) | ![IMG_2951](https://user-images.githubusercontent.com/17885425/231827561-335053e6-6377-425f-9cab-20b2e5f111c4.jpg)

</details>

<details><summary>Test 3</summary>

- Confirmed values are different on both test pages

Test 3A | Test 3B
-|-
![IMG_2952](https://user-images.githubusercontent.com/17885425/231827852-0755a63e-044e-4589-a93d-bd140b2732f3.jpg) | ![IMG_2953](https://user-images.githubusercontent.com/17885425/231827854-d1d32d82-b01b-43bf-b13f-53f0613603c8.jpg)

</details>

<details><summary>Test 4</summary>

- Confirmed values are different on both test pages

Test 4A | Test 4B
-|-
![IMG_2957](https://user-images.githubusercontent.com/17885425/231828057-8cb227ea-a0cf-4507-9cdb-242f1df73aff.jpg) | ![IMG_2958](https://user-images.githubusercontent.com/17885425/231828061-fc55483d-af62-49c4-b136-84f01309fd60.jpg)

</details>

<details><summary>Test 5</summary>

- Confirmed values generated are not the same

Test 5A | Test 5B
-|-
![IMG_2959](https://user-images.githubusercontent.com/17885425/231828159-9760cafa-c94f-407d-a659-7fa7f2e0ebe5.jpg) | ![IMG_2960](https://user-images.githubusercontent.com/17885425/231828160-8d7d1d4f-ba69-419a-b5a2-bd6cea27533e.jpg)

</details>

**Comment by Uni-verse** [comment]
Verified on `iPad (9th Gen)` running `iPadOS 15.6.1` using version `1.49.1 (23.4.12.18)`

- Confirmed farbling tests are working as expected based on test plan in https://github.com/brave/brave-ios/issues/7231#issue-1664912095

Example | Example | Example | Example | Example | Example | Example
-|-|-|-|-|-|-
![IMG_0204](https://user-images.githubusercontent.com/17885425/231872936-9d32debc-91e2-448b-85d4-c03ba8418176.jpg) | ![IMG_0205](https://user-images.githubusercontent.com/17885425/231872949-b08a6c06-2c5b-4cf5-9a90-c29d99cfc21e.jpg) | ![IMG_0206](https://user-images.githubusercontent.com/17885425/231872953-d24bec2b-0cfd-4ede-a6e5-4195a39747a5.jpg) | ![IMG_0207](https://user-images.githubusercontent.com/17885425/231872960-516e8e40-bc18-45dd-bfb7-2e54de84c081.jpg) | ![IMG_0208](https://user-images.githubusercontent.com/17885425/231872962-281a2959-a44f-4237-8c94-fe8e6a5c50f6.jpg) | ![IMG_0209](https://user-images.githubusercontent.com/17885425/231872967-6ebe215e-b039-4377-ae02-38ad00b3ced2.jpg) | ![IMG_0210](https://user-images.githubusercontent.com/17885425/231872974-0a66dd23-352c-49c5-9ac2-5b1294c8b0a3.jpg)
