### ISSUE TITLE
Show transactions from all networks on activity tab

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7233]
Currently we are [only able to fetch all transactions for the selected network for each coin type](https://github.com/brave/brave-core/blob/master/components/brave_wallet/common/brave_wallet.mojom#L1273-L1275). A [core change is in progress](https://github.com/brave/brave-browser/issues/29638) to give us the ability to fetch transactions for all networks instead of just the selected network. When this is available, we should add an accounts & network filter to the [Activity tab](https://github.com/brave/brave-ios/issues/7198).

Discussion ref: https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1680806641725749

Accounts filter should default to All Accounts and network filter should default to All Networks.

Empty State:
<img width="847" alt="Screenshot 2023-04-04 at 10 36 08 AM" src="https://user-images.githubusercontent.com/5314553/229827546-024cb059-dbcf-41e6-8aaa-93a54cc0c8c6.png">

With Transactions:
<img width="841" alt="Screenshot 2023-04-04 at 10 37 26 AM" src="https://user-images.githubusercontent.com/5314553/229827558-91d054ad-c3c1-42c9-96de-95bbf4be6048.png">

`blocked` until https://github.com/brave/brave-browser/issues/29638 is available.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 16.5 running 1.52 (23.6.22.18)
- Verified steps from [#7441](https://github.com/brave/brave-ios/pull/7441)
- Verified all completed transaction activity from all network is shown under activity tab
- Verified rejected transactions are only shown under the account and not under activity tab

https://github.com/brave/brave-ios/assets/17010094/73312c6f-068d-4a2f-8d22-fa189ec27352
