### ISSUE TITLE
Use built-in iOS 16 find in page control

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#7238]
### Description: 

On iOS 16 there is a new API that lets us get proper find-in page for free without using private APIs, we should switch to that on iOS 16 devices

**Comment by Uni-verse** [comment]
Verified on the `iPhone X` running `iOS 16.3.1` & `iPhone XR` running `iOS 15.5` using version `1.51 (23.5.10.20)`

Following test plan in https://github.com/brave/brave-ios/pull/7235#issue-1665392798, verified functionality on the following platforms. 

_iOS 16_

<details><summary>Basic Functionality (Fresh Profile)</summary>

- Confirmed tapping on `Find in Page` on a webpage will bring up the find in page UI in the omni-box.
- Confirmed entering a search term in the text field will highlight all matches on the page with a count.
- Confirmed tapping `Search` key in the keyboard will collapse keyboard and only show find in page window. 
- Confirmed tapping the `x` will clear the search field for find.
- Confirmed tapping `Done` in the omni-box will close the `Find in Page` window.
- Confirmed searching with Find in Page with top & bottom URL bars.

Example | Example | Example
-|-|-
![IMG_3162](https://github.com/brave/brave-ios/assets/17885425/303eed89-19e9-480c-bae8-3ca9016bb406) | ![IMG_3169](https://github.com/brave/brave-ios/assets/17885425/1f0a6a40-43e1-46d1-94f2-74536f919164) | ![IMG_3164](https://github.com/brave/brave-ios/assets/17885425/d14f50d3-e320-4ea3-8a83-511acb614f63)

</details>

<details><summary>Search Options & Reader Mode</summary>

- Confirmed searching using `Find in Page` with `Reader Mode` enabled.
- Confirmed tapping the hourglass dropdown will show search options.

Example | Example
-|-
![IMG_3167](https://github.com/brave/brave-ios/assets/17885425/6f9422e5-5d7f-4c1b-8bd3-09d24abc0696) | ![IMG_3161](https://github.com/brave/brave-ios/assets/17885425/3713c012-010b-4daf-92b3-c5ef9e159093)

</details>

<details><summary>Case Search & Iteration</summary>

- Confirmed using `Match Case` will search case sensitive.
- Confirmed user is able to iterate through the found results using the arrow functions in the omni-box.

Example | Example
-|-
![IMG_3165 2](https://github.com/brave/brave-ios/assets/17885425/37e7853c-42db-4dba-8fef-9b3702002538) | ![IMG_3166 2](https://github.com/brave/brave-ios/assets/17885425/004da336-b975-47aa-b25d-b776f59aa670)

</details>

<details><summary>Existing Profile</summary>

- Confirmed `Find in Page` search works and does not interfere with shields, rewards and wallet pop-ups.

</details>

_iOS 15_

<details><summary>Regression</summary>

- Confirmed Find in Page functionality on iOS 15 has not regressed.
- Confirmed Find in Page has not regressed after upgrading with existing profile.

Example | Example | Example
-|-|-
![IMG_0339 3](https://github.com/brave/brave-ios/assets/17885425/10e8f790-e343-4586-b18b-8418b6cb3575) | ![IMG_0340 2](https://github.com/brave/brave-ios/assets/17885425/7bcbaf8a-5283-4d78-895e-e9b03f915503) | ![IMG_0341 2](https://github.com/brave/brave-ios/assets/17885425/bb3e36b6-dae7-4b55-bbb9-21403aee2a4c)


</details>

**Comment by Uni-verse** [comment]
Added `QA/Test-All-Platforms` as this functionality needs to be checked on iPhone as well as iPad.

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iOS 16.3.1` using version `1.51 (23.5.11.17)`

Based on Test Plan in https://github.com/brave/brave-ios/pull/7235#issue-1665392798

- Verified Find in Page uses the new built control.
- Verified entering search term in search field will display matches and user is able to iterate through results.
- Verified results are highlighted on the page.
- Verified user is able to use attached keyboard with iPad.
- Verified Find in Page in Reader Mode.
- Verified search option settings are applied to the results.

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_1055](https://github.com/brave/brave-ios/assets/17885425/b729060e-332d-4681-8cf6-cfbb81a96461) | ![IMG_1056](https://github.com/brave/brave-ios/assets/17885425/1ebab468-2c35-4e0b-af5a-2323a20fa91c) | ![IMG_1057](https://github.com/brave/brave-ios/assets/17885425/4c19033e-5b42-4a1e-8c39-31654e7362f1) | ![IMG_1058](https://github.com/brave/brave-ios/assets/17885425/e21593f7-b54c-4897-9992-1ac503fe0511) | ![IMG_1059](https://github.com/brave/brave-ios/assets/17885425/7270d23a-5641-474b-b00b-2c966047dd36) | ![IMG_1060](https://github.com/brave/brave-ios/assets/17885425/a27b9223-00cc-4581-81f0-79ac3fe0f693)
