### ISSUE TITLE
Move `Block Popups` toggle out of `Brave Shields & Privacy` settings

### ISSUE THREAD

**Issue by antonok-edm** [brave/brave-ios#7247]
The setting doesn't really full under the category of Shields or Privacy. It could be moved to general settings, or removed altogether (note that brave-core does not have an analogous setting).

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` & `iPad (9th Gen)` running `iOS 15.6.1` using `1.51 (23.4.28.18)`

- Confirmed `Block Popups` toggle is moved to General Settings
- Confirmed Block Popups toggle state is retained on upgraded profile
- Confirmed `Block Popups` toggle is enabled by default on new profile

Example | Example 
-|-
![IMG_3096](https://user-images.githubusercontent.com/17885425/236315205-1520a34b-6f44-4d5c-be90-1950cd86d6b3.PNG) | ![IMG_3097](https://user-images.githubusercontent.com/17885425/236315212-d64d12ef-7482-4325-99f1-044cfb84504e.PNG)
![IMG_0230 3](https://user-images.githubusercontent.com/17885425/236315527-527c3916-82bf-4c0e-9318-7315c03ac25d.PNG) | ![IMG_0229 3](https://user-images.githubusercontent.com/17885425/236315543-d43b4e40-0aad-4a77-aa12-18805c0936f1.PNG)
