### ISSUE TITLE
VPN Protocol (Tunnel) Option

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#7255]
### Description: 
For the VPN Wireguard vs IKEv2 option, please add an option in VPN Settings called **VPN Protocol**
Tapping this opens a screen with 2 options: (Wireguard being selected as default)

- IKEv2
- Wireguard

And example from Guardian VPN application

![1 1 1 1 1](https://user-images.githubusercontent.com/6643505/233189508-a85afdb9-9ad3-4d98-8e97-5d2e1fd16459.png)

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.51 (23.5.8.18)`

_New Profile_

- Verified WireGuard is default protocol for VPN.
- Verified switching to IKEv2 is successful and VPN connection is re-established and VPN connection modal is shown.
- Verified changing regions using settings or the quick access region switcher works on both protocols.
- Verified resetting configuration in VPN settings is successful.

Issues encountered:
https://github.com/brave/brave-ios/issues/7412
https://github.com/brave/brave-ios/issues/7414
https://github.com/brave/brave-ios/issues/7413

Example | Example | Example | Example | Example | Example | Example | Example
-|-|-|-|-|-|-|-
![IMG_3127 2](https://github.com/brave/brave-ios/assets/17885425/1e71c34a-b5f7-4cf9-b9e3-f6ed2ca4f9fb) | ![IMG_3132 3](https://github.com/brave/brave-ios/assets/17885425/eb4e2064-b956-4910-80a7-ff40428457b8) | ![IMG_3133 3](https://github.com/brave/brave-ios/assets/17885425/1faaea1d-395e-48ad-b9d2-a2f46435e08c) | ![IMG_3140 2](https://github.com/brave/brave-ios/assets/17885425/fe7f6f13-2bb6-45a4-9a1f-0b958e42fd2f) | ![IMG_3141 2](https://github.com/brave/brave-ios/assets/17885425/d5ed1a38-55e4-4917-b882-583039893ee3)| ![IMG_3142 2](https://github.com/brave/brave-ios/assets/17885425/88905ee5-8c47-4889-98aa-d819e5d6245e) | ![IMG_3143 2](https://github.com/brave/brave-ios/assets/17885425/e6945fee-e824-450c-a1fc-598d9d91bec5) | ![IMG_3144](https://github.com/brave/brave-ios/assets/17885425/3ab7908b-09c8-4c02-b1de-6a12af10b857)

_Existing Profile_

- Verified WireGuard is default protocol for VPN.
- Verified switching to IKEv2 is successful and VPN connection is re-established and VPN connection modal is shown.
- Verified changing regions using settings or the quick access region switcher works on both protocols.
