### ISSUE TITLE
[Follow up to #6682] Playlist video janky when using 2.5x playback speed option (iPad)

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#7256]
### Description: 
When using 2.5x playback speed on iPad, video does not play smoothly and is not audible 

Follow up to https://github.com/brave/brave-ios/issues/6682

### Steps to Reproduce 
  1. Install 1.50
  2. Navigate to youtube.com
  3. Add some videos to playlist
  4. Load some playlist videos and change playback speed to 2.5x

### Actual result: 
Does not play smoothly, not audible

https://user-images.githubusercontent.com/17885425/232144311-0159409e-3564-4818-850a-4e04528e8c6e.MP4

### Expected result:
Should play smoothly at 2.5x speed

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

### Brave Version:  `1.50 (23.4.14.17)`

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 
iPad (9th Gen), iPadOS 15.6.1

**Comment by iccub** [comment]
changed to `qa/no` because we remove 2.5 playback functionality
