### ISSUE TITLE
Playback speed changes when pausing/playing video in PiP/minimized mode

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#7258]
### Description: 
Playback speed is reset to 1x when pausing/playing in PiP mode

### Steps to Reproduce 
  1. Install 1.50
  2. Navigate to youtube.com
  3. Add some videos to playlist
  4. Open playlist and watch a video
  5. Change the playback speed from 1x to 2x
  6. Go into picture in picture mode
  7. pause the video and then resume playback
  8. Go back to full screen view

### Actual result: 
Playback speed changes

https://user-images.githubusercontent.com/17885425/232147052-d780ae50-ebb8-43b9-88fa-ce2301f77fa3.MP4

### Expected result:
Should not change playback speed

### Brave Version:  `1.50 (23.4.14.17)`, `1.49.1 (23.4.12.18)`

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? N/A

### Device details: 
iPhone, iPad
iOS 16, 15

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 [iOS 17.0]
- iPad Air [iPadOS 16.5.1]
Brave build: 1.58 (23.9.19.14)
BraveCore: 1.58.124 (117.0.5938.62)
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-ios/issues/7258#issue-1668906486

**ACTUAL RESULTS:**
- Verified that the video is still playing with 1x, 1.5x or 2.0x speed in `PIP Mode` and in `Browser` and not resetting to 1.x speed

---------------------------

*iPhone*

https://github.com/brave/brave-ios/assets/128532965/d20976e8-225b-4446-8095-2fa634d15b41

*iPad*

https://github.com/brave/brave-ios/assets/128532965/a2a4febf-1f59-4d64-87b1-840163e9352e
