### ISSUE TITLE
[hackerone] Show a prompt for QR-code scanned URLs

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-ios#7260]
We should show a prompt before navigating to a URL that was scanned with the QR-code scanner.

https://hackerone.com/reports/1946534

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` & `iPad (9th Gen)` running `iOS 15.6.1` using `1.51 (23.4.28.18)`

Using Test Plan in https://github.com/brave/brave-ios/pull/7319#issue-1680495000

- Verified scanning QR using omnibar doesn't auto-submit URL and shows URL selected in `normal` and `private` mode.
- Verified scanning URL doesn't auto-submit on `upgraded profile`.
- Verified scanning QR works and loads the URL successfully.
- Verified scanning QR works with `bottom bar` and `top bar` modes.
- Verified scanning has not regressed on normal and private tabs

Bottom Bar | Top Bar | Private Tabs | iPad
-|-|-|-
![IMG_3093](https://user-images.githubusercontent.com/17885425/236299041-d95f2f5f-edb2-4c69-8bed-71912f6d8f29.PNG) | ![IMG_3095 2](https://user-images.githubusercontent.com/17885425/236299104-f15f48da-e1d8-460e-b695-afaa5597e73d.PNG) | ![IMG_3094](https://user-images.githubusercontent.com/17885425/236300100-3a366108-4ce9-4782-a2ce-49af977688ac.PNG) | ![IMG_0227 4](https://user-images.githubusercontent.com/17885425/236299993-724856fa-b899-4e8a-b24c-0c968d6e61ee.PNG)
