### ISSUE TITLE
Sort Portfolio assets by balance

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7261]
### Description: 

Sort the assets in Portfolio by balance

ref: https://bravesoftware.slack.com/archives/C02S9LFEXU4/p1681538988908419

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.
- Verified steps from []()

iPhone 7+ (iOS 15.7.3) | iPad Pro (16.4 Beta 4)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/236374122-518dc126-1a49-496c-a343-4560a5da698f.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/236374092-45ba102d-055f-4bd8-aa93-4ae8f39614b3.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/236374149-3f85d25a-f2cc-4a0c-8f98-f230dbc85693.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/236374113-0f7963bd-effc-4b30-a045-87d3b534165b.png>
<img width=300 src=https://user-images.githubusercontent.com/17010094/236374157-349f5dd9-9d6d-4cb6-8d11-ae2c9bf66d26.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/236374106-569e4e34-7dd0-4e09-aecc-a9e72b563ba4.png>
