### ISSUE TITLE
Issue with attempting to block sync requests using request blocker

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#7267]
### Description: 
The following page won't render: https://ec-plus.panasonic.jp/
https://user-images.githubusercontent.com/909331/232587216-971b55bf-ecce-479f-a6dd-ef9fb828ee08.MP4

### Steps to Reproduce 
  1. With shields on, go to the following page: https://ec-plus.panasonic.jp/

### Actual result: 
Page does not render

### Expected result:
Page should render

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.50 (23.4.25.20)`

Using STR in https://github.com/brave/brave-ios/issues/7267#issue-1671815978

- Ensured page renders when visiting `https://ec-plus.panasonic.jp/.`
- Ensured that items show as blocked on the page.
- Ensured that page renders with `Adguard Japanese filters` enabled in Content filter lists

Example | Example | Example
-|-|-
![IMG_3024 3](https://user-images.githubusercontent.com/17885425/234916912-e90ff38d-4376-493e-bb34-faecca790106.PNG) | ![IMG_3025 3](https://user-images.githubusercontent.com/17885425/234916936-c67ebb2f-3b87-417b-91e0-854c730a5e3f.PNG) | ![IMG_3027 2](https://user-images.githubusercontent.com/17885425/234916939-4406fda5-8f46-46cb-beca-fb417a34c0a2.PNG)
