### ISSUE TITLE
[Follow up to #7207] Favicons still flickers or shown blurry in build 1.50

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#7271]
### Description: 

Follow up to #7207

Playlist Favicons flickers

### Steps to Reproduce 
  1. Add a video to Playlist (the video needs to be one that does NOT have thumbnails, and has favicons only)
  2. Open Playlist > Observe, that he favicon renders
  3. Close and reopen Playlist > Observe, that the favicon renders again
  4. Keep Playlist opened > Observe, that favicon renders each ~5 sec 

Favicons are blurry

### Steps to Reproduce 
   1. Fresh install
   2. Visit Wiki or Reddit
   3. QUICKLY close the tab
   4. Observe, that Favorite icon is now blurry instead of crisp 

### Actual result: 

In the new build 1.50 (23.4.17.16):
- Playlist favicons flickers when keeping Playlist opened 

https://user-images.githubusercontent.com/128532965/232616549-e9900c32-42fe-4eab-a4f3-add0c227427a.mov
- Favicons on NTP sometimes shown blurry. This is happening on first attempt, then icon is shown crisp again <img width="473" alt="Blurry Wiki" src="https://user-images.githubusercontent.com/128532965/232616975-6fa5fa11-0250-4ba4-b838-cfb9579a1d64.png">

https://user-images.githubusercontent.com/128532965/232616965-216f22c1-fd02-440e-b1d9-09a07866def7.mov

### Expected result:

Favicons must not flicker in Playlist and must be crisp on NTP

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

1.50 (23.4.17.16)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 

iPhone 14 [iOS 16.3]

**Comment by Uni-verse** [comment]
Verified on `1.50 (23.4.25.20)` on `iPhone X` running `iOS 16.3.1`

Using STR in https://github.com/brave/brave-ios/issues/7271#issue-1672016007

- Ensured playlist thumbnail icons do not flicker when closing/opening playlist
- Ensured favicons on NTP stay crisp after loading `wikipedia.org` and `reddit.com`

Example | Example
-|-
![IMG_2993 2](https://user-images.githubusercontent.com/17885425/234646514-c488c471-67ee-4304-8f45-57d8f0eaf649.PNG) | ![IMG_2994 2](https://user-images.githubusercontent.com/17885425/234646528-16e8e994-3541-4e46-88d4-d8f6fb80c3fa.PNG)
