### ISSUE TITLE
Use Symbol when adding variables to xhr objects

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#7272]
### Description: 
In order to avoid conflicts with other code, we attach variables to xhr objects using Symbol instead of a static variable name. This should prevent conflicts and also unwanted manipulation/extraction of these variables

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.51 (23.4.28.17)`

Testing based on test plan in https://github.com/brave/brave-ios/pull/7273#issue-1672846829

*NOTE* - upgraded profile scenarios will be tested by default in the manual pass for rewards / blocking count

- Ensured creating rewards profile is working on new profile as well as upgraded profile
- Ensured ads are being shown

Example | Example | Example
-|-|-
![IMG_3115 2](https://user-images.githubusercontent.com/17885425/236532828-5f70488a-66a0-4e84-b9f1-321da5995dba.PNG) | ![IMG_3116 2](https://user-images.githubusercontent.com/17885425/236532837-ccca0fef-c29a-4f0d-b2eb-74915106039f.PNG) | ![IMG_3117 2](https://user-images.githubusercontent.com/17885425/236532877-40b17914-3ff4-4803-bdde-9ab289bb98b9.PNG)

- Ensured that blocked counts are shown in shields panel
- Ensured that trackers are listed/updated in privacy hub stats

Example | Example | Example | Example
-|-|-|-
![IMG_3118 2](https://user-images.githubusercontent.com/17885425/236536096-83a4b57f-ae9b-4b8d-9b9a-dddeac401e96.PNG) | ![IMG_3122 2](https://user-images.githubusercontent.com/17885425/236536125-d16305af-a495-45c7-8ca5-4616fa8c7d72.PNG) | ![IMG_3123 2](https://user-images.githubusercontent.com/17885425/236536145-7cd4c2cc-3b83-4226-a0f7-31c64b26c4a1.PNG) | ![IMG_3124 2](https://user-images.githubusercontent.com/17885425/236536148-3c8ed598-0327-4cad-8d5e-bec2d04f61a3.PNG)
