### ISSUE TITLE
Disable filter lists that are currently incompatible with iOS (i.e. Anti-porn list)

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#7278]
### Description: 
Certain filter lists are not compatible with iOS for the time being (And hopefully not for long).

### Steps to Reproduce 
  1. Go to filter lists

### Actual result: 
Anti-porn list is visible

### Expected result:
Anti-port should not be in the list

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: iPhone 14 [iOS 16.4.1] and iPad Air [iPadOS 16.4.1]
Version: 1.51 (23.5.8.18) 
BraveCore: 1.51.110 (113.0.5672.77)
```
---------------------------

**STEPS:**
1. Launch Brave > Three Dot Menu > Settings
2. Brave Shields & Privacy > Content Filtering

**ACTUAL RESULTS:**
- Verified that `Blocklists Anti-porn list` is not shown anymore

|Before in 1.50|After in 1.51|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/5907e733-e027-441f-8e25-d6f71f5ecf5f) | ![2](https://github.com/brave/brave-ios/assets/128532965/9edc1adb-521c-40d0-9d28-cf84e554d341) |
