### ISSUE TITLE
Omnibar missing after trying to change search settings

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7280]
### Description: 

Omnibar is missing after entering a search term and opening search settings.

### Steps to Reproduce 
prerequisite: Tab bar set to bottom
  1. Open a new tab
  2. Enter a search term
  3. Tap magnifying glass icon in the keyboard toolbar
  4. Tap done
  5. Observe search / omni bar is missing

### Actual result: 

https://user-images.githubusercontent.com/5314553/232892099-19477037-a945-43c3-a201-2d5454b87cd9.mov

### Reproduces how often: 

Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5.1]
Brave build: 1.56 (23.7.13.16)
BraveCore: 1.56.5 (115.0.5790.75)
```
---------------------------

**STEPS:**
1. Launch Brave
2. Open a new tab
3. Enter a search term in the URL bar
4. Tap `magnifying glass` icon in the keyboard toolbar
5. Tap `Done` > Verify

**ACTUAL RESULTS:**
- Verified that URL search bar is not hidden/removed

---------------------------

*Bottom Bar*

https://github.com/brave/brave-ios/assets/128532965/a26e8507-6569-4aac-bcee-319d899fed69

*Top Bar*

https://github.com/brave/brave-ios/assets/128532965/c1231c5c-4bf7-4df0-a0f4-b521719956a2
