### ISSUE TITLE
[Playlist] Last played or first item in Playlist is start playing depend on what page is currently opened

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#7281]
### Description: 
"Last played" or "first" item in Playlist is start playing depend on what page is currently opened 

### Steps to Reproduce 
  1. Open youtube.com or vimeo.com (or another support video source website), for example
  2. Three dot Menu > Playlist
  3. Play 2nd or any next video
  4. Tap "Done" > Reopen Playlist > Observe, that 1st video is playing now
  5.  Repeat steps 1 -4, but this time open any not supported website, for example airbnb.com
  6. Now observe, that last played video is playing when reopening Playlist

### Actual result: 
When user is located on supported website and opens Playlist, first video is start playing by default, however when user is located on not supported website, then last played video continue playing on opening Playlist. 

https://user-images.githubusercontent.com/128532965/232910693-d944feb7-e039-4e47-8f34-06074e62c684.mov

### Expected result:
One of these two options must work, either last played item, either first item every time user opens Playlist. And according to https://github.com/brave/brave-ios/issues/6042 I believe, first item is default one.

### Reproduces how often: 

Easily reproduced

### Brave Version: 

1.50 (23.4.17.16)

### Device details: 

iPhone 14 [iOS 16.4.1] and iPad Air [iPadOS 16.4.1]

**Comment by iccub** [comment]
This is correct behaviour actually.
It plays where you left off from the current page. So if you’re watching a video, and you open playlist and that video is in your playlist, it plays where you left off from the page, and not the last left off video you watched last time.
