### ISSUE TITLE
[Playlist] Highlight for currently playing item is not shown in Playlist

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#7282]
### Description: 
Highlight for currently playing item is not shown in Playlist

### Steps to Reproduce 
  1. Open YT or Vimeo and add some items to the Playlist
  2. Three dot Menu > Playlist
  3. When video start playing, wait for ~5 sec > Observe, that highlight is not shown anymore
  4. Select another video in the list > Observe, highlight is not there

### Actual result: 
Highlight for currently playing item is not shown in build 1.50. This is Regression from 1.49.1 where issue is not observed

https://user-images.githubusercontent.com/128532965/232920977-aedc9ec1-798a-4dbd-8ca2-2389e3dce6f8.mov

### Expected result:
Currently playing video must be highlighted in the Playlist, so user can easily see what item is plying right now

### Reproduces how often: 

Easily reproduced

### Brave Version: 

1.50 (23.4.17.16)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? No
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 

iPhone 14 [iOS 16.4.1] and iPad Air [iPadOS 16.4.1]

**Comment by Uni-verse** [comment]
Verified `1.50 (23.4.25.20)` on `iPhone X` running `iOS 16.3.1`

Using STR in https://github.com/brave/brave-ios/issues/7282#issue-1673928646

- Ensured video that is playing is highlighted in playlist

![IMG_2991 2](https://user-images.githubusercontent.com/17885425/234642424-ffb67a93-b22d-48fb-b18e-74e7af555ff9.PNG)
