### ISSUE TITLE
[Playlist] Wrong title & thumbnail or a video are shown for the first file in Playlist if saved from the main page

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#7283]
### Description: 
Wrong title and thumbnail or a video are shown for the first audio/video in Playlist if that file saved from the main page of the source

### Steps to Reproduce 
  1. For example, open YT or Vimeo main page (where you see multiple videos on one screen)
  2. Observe "Add to playlist" button in search bar > Tap it
  3. Open Playlist now and confirm that video was added. Remember name and thumbnail pic
  4. Go back to main page and scroll through the videos. Make sure "Add to Playlist" button is green
  5. Open Playlist again > Observe, thumbnail and name for the first video is changed

### Actual result: 
If user added a file from the main page of YT (for example), then scrolled through the videos and opened Playlist, there will be shown wrong title and thumbnail for the first audio/video file in Playlist. Sometimes, whole video is replaced.

https://user-images.githubusercontent.com/128532965/232930067-5cf17fd4-5ff0-4794-a034-3fe49adacebb.mov

https://user-images.githubusercontent.com/128532965/232930374-78dde17b-caa5-47e7-9930-959234b82da2.mov

### Expected result:
Correct thumbnail and name must be shown for each audio/video that were added to the Playlist

### Reproduces how often: 

Easily reproduced

### Brave Version: 

1.50 (23.4.17.16)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 

iPhone 14 [iOS 16.4.1] and iPad Air [iPadOS 16.4.1]

**Comment by Uni-verse** [comment]
Verified on `1.50 (23.4.25.20)` on `iPhone X` running `iOS 16.3.1`

Using STR in https://github.com/brave/brave-ios/issues/7283#issue-1673978625

Encountered Issue: https://github.com/brave/brave-ios/issues/7340

https://user-images.githubusercontent.com/17885425/234636096-f7df9484-9556-4a7e-8550-8650dd2c281f.MP4
