### ISSUE TITLE
Private text is not fully shown in tab tray

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#7285]
### Description: 
Private text is not fully shown in tab tray

### Steps to Reproduce 
  1. Install or upgrade to 1.50 via TF
  2. Open a private tab
  3. Open tab tray, `Private` text is shown as `Pr...te`

### Actual result: 
![image](https://user-images.githubusercontent.com/17010094/233061275-49c045ee-d162-410b-a7aa-859246377cff.png)

### Expected result:
Show full text 

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes on 1.50 (23.4.17.16)
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes on 1.49.1 (23.4.12.18)
- Can you reproduce this issue with the current build from AppStore? Yes 

### Device details: 
iPhone 7+ (iOS 15.7.3)

### Website problems only:
- did you check with Brave Shields down?  NA
- did you check in Safari/Firefox (WkWebView-based browsers)?  NA

### Additional Information 
cc: @brave/qa-team @iccub

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5]
Version: 1.52 (23.6.9.13)
BraveCore: 1.52.117 (114.0.5735.90)
```
---------------------------

**STEPS:**
1. Launch Brave
2. Open tab tray > Open a `Private tab'
3. Open tab tray once again > Verify

**ACTUAL RESULTS:**
- Verified `Private` word is not truncated and fully visible

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/97726cab-beb4-4116-b8da-5a70d3e3fb06) | ![2](https://github.com/brave/brave-ios/assets/128532965/e1b2ba16-f3f5-47bb-8e06-a9e89c365e60) | ![3](https://github.com/brave/brave-ios/assets/128532965/0fbfcb5e-a4cb-4948-bdf5-5d46ce195a44) |

**Comment by hffvld** [comment]
Hi @srirambv I verified that the issue is not reproducible on my device, but it could be related to iOS 15 or a smaller screen size. So, maybe you can double-check it on `iPhone 7+ (iOS 15.7.3)`?
