### ISSUE TITLE
[Playlist] - Shared Playlist Update Setting

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#7293]
### Description: 
Please enable Sync Playlist Folders Automatically to default On and Title Case the setting. 

![IMG_89EDF1C52578-1](https://user-images.githubusercontent.com/7606853/233206441-b745c02d-8ef0-4c4e-8ff0-7cadd23bac19.jpeg)

**Comment by anthonypkeane** [comment]
@iccub Can we get this in 1.51 please? TY

**Comment by iccub** [comment]
sure

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` & `iPad (9th Gen)` running `iOS 15.6.1` using `1.51 (23.4.28.18)`

- Verified `Sync Playlist Folders Automatically` toggle is `enabled` by default
- Verified the setting has title case.

Example | Example
-|-
![IMG_3103](https://user-images.githubusercontent.com/17885425/236320559-cb2694cc-8874-4271-967b-3eb30f7878fd.PNG) | ![IMG_0233 3](https://user-images.githubusercontent.com/17885425/236320600-23d5a739-32ac-4a00-a6f6-f9f4c136286b.PNG)
