### ISSUE TITLE
Update pending transactions to support all networks for a coin type

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7295]
### Description: 

With the changes in https://github.com/brave/brave-core/pull/17986, we are now able to fetch transactions for all networks on each coin type (current logic uses the selected network for each coin type). We should update the pending requests to fetch transactions for all networks on a given coin type, and update Transaction Confirmation to make sure the correct network for the transaction is displayed (no longer guaranteed be the selected network for the coin type).

`GetAllTransactionInfo` now accepts a `chain_id` parameter, and the `chain_id` is stored on each `TransactionInfo` model.

Requires BraveCore v1.52.x

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 16.5 running 1.52 (23.6.1.15)
- Verified steps from [#7424](https://github.com/brave/brave-ios/pull/7424)
- Verified pending transaction button is shown irrespective of which network is set as active network
- Verified `Transaction Completed` message is shown once the transaction is confirmed 
- Verified `View Receipt` shows the correct network 
- Verified confirm/reject transaction action works as expected
- Logged [#7572](https://github.com/brave/brave-ios/issues/7572)

https://github.com/brave/brave-ios/assets/17010094/806faf85-9f80-4938-9a41-dc99fe4d2664
