### ISSUE TITLE
Update DApp requests to show request network

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7296]
### Description: 

With the changes in https://github.com/brave/brave-core/pull/17986, the `chain_id` of the request is now stored on the `SignatureRequest` model. We should display the network for the signature request on [SignatureRequestView](https://github.com/brave/brave-ios/blob/development/Sources/BraveWallet/Panels/Signature%20Request/SignatureRequestView.swift).

Additionally, the `chain_id` of the transaction being signed is now stored on the `SignTransactionRequest` model. We should update [SignTransactionView](https://github.com/brave/brave-ios/blob/development/Sources/BraveWallet/Panels/Sign%20Transaction/SignTransactionView.swift) to display the correct network for this `chain_id` instead of the selected network.

Requires BraveCore v1.52.x

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.52 (23.6.1.15)
- Verified steps from [#7384](https://github.com/brave/brave-ios/pull/7384)
- Verified changing network in panel continues to show the request network correctly
- Verified for both Solana and Ethereum transactions

iPhone 13 (iOS 16.5) | iPad Pro (iOS 16.6 Beta)
-- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/24087f35-35bb-489c-8804-d4210bbc6608>| <video src=https://github.com/brave/brave-ios/assets/17010094/144ca5b0-d4c5-4e15-b4e3-9928584919a6>
