### ISSUE TITLE
Tabs not restoring properly

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#7303]
### Description: 
- Tabs don't restore correctly on development

### Steps to Reproduce 
  1. Install AppStore 1.49.x
  2. Open some tabs
  3. Install Development (Release scheme) 1.51.x

### Actual result: 
- Tabs are not restored

### Expected result:
- Tabs should be restored

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduces

### Brave Version: 

- 1.51.x

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.51 (23.5.11.17)`

**_Fresh Profile_**

- Verified tabs are restored properly and in the same order when re-launching application.
- Verified active tab is restored correctly after relaunching.

Before | After
-|-
![IMG_3175](https://github.com/brave/brave-ios/assets/17885425/69f5289b-9a0a-4ce0-b152-fcaa9cf9d157) | ![IMG_3176](https://github.com/brave/brave-ios/assets/17885425/6cd1399b-4a7c-4213-bc02-076a9cecbf4f)

**_1.49 -> 1.51_**

- Verified tabs are restored properly and in the same order when upgrading from `1.49.1 (23.4.12.18)` -> `1.51 (23.5.11.17).`
- Verified active tab is restore from the previous version.
- Verified white screen was not encountered when restoring tabs

1.49 | 1.51
-|-
![IMG_3171](https://github.com/brave/brave-ios/assets/17885425/bb42f921-782f-43b4-a1a2-2442e3b73edb) | ![IMG_3172](https://github.com/brave/brave-ios/assets/17885425/ed7d3a05-f814-4f74-8f30-1d37bef630b5)


**_1.50 -> 1.51_**

- Verified tabs are restored properly and in the same order when upgrading from `1.50 (23.4.25.20)` -> `1.51 (23.5.11.17).`
- Verified active tab is restore from the previous version.
- - Verified white screen was not encountered when restoring tabs

1.50 | 1.51
-|-
![IMG_3173](https://github.com/brave/brave-ios/assets/17885425/e5f702ef-2fa6-40cc-a3d5-963848f0eadb) | ![IMG_3174 2](https://github.com/brave/brave-ios/assets/17885425/d51d05ba-0c43-4a8d-963d-90682d15dd4a)
