### ISSUE TITLE
Reset wallet does not hide wallet specific sections

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7312]
### Description: 

Reset wallet does not hide wallet specific sections until settings is closed and re-opened _only when opened from main app settings_.

### Steps to Reproduce 
  1. Tap `...` menu and tap Settings
  2. Tap 'Reset Brave Wallet' and confirm the reset on the alert
  3. Observe Wallet settings are still visible until Web3 Settings is closed and re-opened.

### Actual result: 

https://user-images.githubusercontent.com/5314553/233715093-33040073-309b-49a3-af83-d79ed317d2a5.mp4

### Expected result:

Hide the wallet specific settings that are hidden when wallet is not setup.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

This does not occur when resetting wallet from within Brave Wallet -> Settings (only occurs when reset from main app settings):

https://user-images.githubusercontent.com/5314553/233715230-2fa8835c-ec4a-40b3-8f79-1b117a846ca4.mp4

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.50 (23.4.21.21)
- Verified steps from [#7313](https://github.com/brave/brave-ios/pull/7313)
- Verified reset clears all Wallet specific settings
- Encountered [#7320](https://github.com/brave/brave-ios/issues/7320)

iPhone 7+ (iOS 15.7.3)  | iPad Pro (16.4 Beta 4)
-- | -- 
<video src=https://user-images.githubusercontent.com/17010094/233914693-2851e752-245b-4ac3-b228-9212c4a88ea2.MP4> | <video src=https://user-images.githubusercontent.com/17010094/233915355-33d7c872-b237-49f5-8398-651989636da9.MP4>
