### ISSUE TITLE
Add App Review API in iOS

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#732]
### Description: 
Add the standard Apple App Review API to our iOS app.

Please post the configurable variables here and we can decide on what works best for our needs

**Comment by kylehickinson** [comment]
The API is [SKStoreReviewController](https://developer.apple.com/documentation/storekit/skstorereviewcontroller). 

There isn't any real configuration for usage other than requesting to show it. We however can choose when to request the popup, based on user action like say, the 10th new tab, the 10th launch, etc.

**Comment by anthonypkeane** [comment]
@jamesmudgett lets split this into 2 parts

1) Add a menu option in settings that allow a user to press the button and provide feedback. We can use the Apple SDK to facilitate this

2) In a later release, we can decide on the logic for alerting users and requesting the review.

James, can you pls decide on where to put the menu item in 1?

**Comment by anthonypkeane** [comment]
Security Review of [SKStoreReviewController](https://developer.apple.com/documentation/storekit/skstorereviewcontroller). here https://github.com/brave/internal/issues/506

**Comment by jhreis** [comment]
Blocked, until split into two tickets (for two parts outlined above).

**Comment by jhreis** [comment]
We need to identify how / when we will present this information to the user.

**Comment by jamesmudgett** [comment]
Can copy this https://github.com/mozilla-mobile/focus-ios/blob/4039b47cb0ed15e875f889f9a6566bf1c52573bd/Blockzilla/BrowserViewController.swift#L482

**Comment by anthonypkeane** [comment]
We should request feedback as follows: 

1st: after: 14 launches
2nd: after: 41 launches
3rd after: 121 launches

Hard rule, the min days between asks is 60 days

cc @jamesmudgett for verification

**Comment by anthonypkeane** [comment]
@jhreis You should have all the info you need here, pls LMK if not? Thanks

**Comment by iccub** [comment]
I'm switching QA label on it to `NO` since the app store review prompt will show only in release builds.
Let me know if this should be changed or we should add some debug info for QA.
