### ISSUE TITLE
Wallet: Soften consecutive newline characters to 3 and more

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#7321]
Currently the check for consecutive newline characters is 2 and more. 
We need to temporarily soften it to 3 and more to avoid showing a warning message for SIWE request message, since SIWE request message is displayed via signature request panel. 
Once we have a specific SIWE request panel UI, we will revert the check back to 2 and more in signature request panel.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.51 (23.4.28.18)
- Verified steps from [#7328](https://github.com/brave/brave-ios/pull/7328)
- Verified no consecutive newline message is shown on sign message for Web3 calls

iPhone 7+ (iOS 15.7.3) | iPad Pro (iOS 16.5 Beta 4)
-- | --
<video src=https://user-images.githubusercontent.com/17010094/236373470-e443873f-f1f4-4775-bde7-2333a02e060c.MP4> | <video src=https://user-images.githubusercontent.com/17010094/236373459-f202fb04-4de3-4a2c-92c3-23b2ebcadbba.MP4>
