### ISSUE TITLE
Empty page title when displaying "switch to tab" entries in search controller for restored tabs that have not been opened

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#7324]
### Description: 

The "Switch to Tab" entries for restored tabs seem to be missing the page title and url

### Steps to Reproduce 
  1. Open multiple tabs for different websites
  2. Kill and re-launch app 
  3. Tap on the URL bar and type in the websites of tabs that were restored but not opened 

### Actual result:
The entry shown for "Switch to Tab" is missing the title and the "Switch to Tab" subtitle
<img width="394" alt="image" src="https://user-images.githubusercontent.com/529104/234101912-b92181f5-4876-4b2c-a21d-b31ad67f538c.png">

### Expected result:
Show the title/subtitle
<img width="392" alt="image" src="https://user-images.githubusercontent.com/529104/234102009-3622c4bd-350b-4904-895c-445c8d2369a8.png">

### Brave Version: development (1.51)

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: iPhone 14 [iOS 16.4.1] and iPad Air [iPadOS 16.4.1]
Version: 1.51 (23.5.5.18) 
BraveCore: 1.51.110 (113.0.5672.77)
```
**STEPS:**
1. Open multiple tabs for different websites
2. Kill and re-launch app
3. Tap on the URL bar and type in the websites of tabs that were restored but not opened

**ACTUAL RESULTS:**
- Verified that page title for restored websites is shown when the search is done

https://user-images.githubusercontent.com/128532965/236569134-cd5c8c64-c187-44ad-9b61-56913fa06dcd.mov
