### ISSUE TITLE
Update wallet reset title

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7337]
### Description: 

Update wallet reset title to `Reset and clear wallet data` [as discussed here](https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1682324758670509).

Android issue: https://github.com/brave/brave-browser/issues/30005

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.51 (23.4.28.18)
- Verified wallet reset title is now updated to `Reset and Clear Wallet Data`

iPhone 7+ (iOS 15.7.3) | iPad Pro (iOS 16.5 Beta 4)
-- | --
<img width=300 src=https://user-images.githubusercontent.com/17010094/236259085-87d64b7b-d905-4779-b53f-014e1b22ffe4.png> | <img width=400 src=https://user-images.githubusercontent.com/17010094/236258977-25cd5d83-c6d6-4cf3-b545-e258683e9cc0.png>
