### ISSUE TITLE
HTTPSE shows working when HTTPSE is disabled in shields

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#734]
### Steps to Reproduce 
  1. Open https://github.com/brave/brave-ios/issues/730 in a new tab
  2. Scroll down to Bravery settings section and long press on http://https-everywhere.badssl.com/ and open in a new tab
  3. Ensure HTTPSE shows as working
  4. Disable HTTPSE from shields, page still shows HTTPSE as working
  5. Reload the same page, shows HTTPSE as not working

**Actual result:** 
https://youtu.be/SohYA3_QnJM

**Expected result:**
Should not confuse this much

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7.2(19.1.15.15)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
#691

**Comment by LaurenWags** [comment]
Verified passed with iPad 5th Gen using 1.7.2 (19.1.16.16)

Verified passed on iPhone SE (iOS 12.1.2) with 1.7.2 (19.1.16.16)

Verification passed on iPhone 6 (iOS 12.1.2) using 1.7.2(19.16.16)

Verification passed on iPhone 8 (iOS 12.1.2) using 1.7.2(19.1.16.16)
