### ISSUE TITLE
Sometimes when entering PIP mode the application crashes

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#7347]
### Description: 
- When entering picture in picture, and returning from the background to the app, the application crashes.

### Steps to Reproduce 
  1. Watch a video in Playlist
  2. Enter Picture-In-Picture
  3. Minimize the app to the background (springboard)
  4. Restore the app to the foreground

### Actual result: 
- Crash

### Expected result:
- Should not crash

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Very very hard to reproduce!

### Brave Version: 

- 1.49.x

### Device details: 
- iOS 16+

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using app version `1.50 (23.4.27.16)`

- Ensured entering/exiting PIP mode does not cause application to crash
- Ensured moving window in PIP mode does not cause crash
- Ensured that playback functions work in PIP Mode

Example | Example | Example
-|-|-
![IMG_3053 2](https://user-images.githubusercontent.com/17885425/234997887-0348e8cc-a3af-44d9-b46b-d716841e5a1f.PNG) | ![IMG_3054 2](https://user-images.githubusercontent.com/17885425/234997920-d8bc5632-239b-4e62-8d24-2943feeb33be.PNG) | ![IMG_3055 2](https://user-images.githubusercontent.com/17885425/234997936-329a0cfe-6769-403b-843b-f976535cca16.PNG)
