### ISSUE TITLE
Update Playlist to use Async-Await

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#7349]
### Description: 
- Update Playlist to use Async-Await to get rid of massive amounts of duplicate code and observers (combine publishers)
- This will make playlist much simpler and potentially much faster

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.52 (23.6.28.13)`

- Ensured adding/removing playlist using icon in url bar, shared menu and long pressing on the video
- Ensured playlist video opens and video plays
- Ensured moving, deleting and downloading playlist items works
- Ensured user is able to delete media, folders with media by swiping as well as edit mode
- Ensured CarPlay is enabled and works with playlist. 
- Ensured adding shared playlist folders works - https://github.com/brave/brave-ios/issues/7658
- Ensured Playlist data is preserved when upgrading
- Ensured Playlist support on the following websites:
  - youtube.com
  - dailymotion.com
  - twitch.tv
  - rumble.com

Example | Example | Example | Example | Example | Example | Example
-|-|-|-|-|-|-
![IMG_3278 2](https://github.com/brave/brave-ios/assets/17885425/2d00eb5e-900a-4038-8a8d-3e734aac6ef6) | ![IMG_3279](https://github.com/brave/brave-ios/assets/17885425/135a5838-64c0-45c2-8170-0644b5e0b5c2) | ![IMG_3280 2](https://github.com/brave/brave-ios/assets/17885425/f0f370f4-d4ec-460d-b08b-9b63bc410867) | ![IMG_3281](https://github.com/brave/brave-ios/assets/17885425/d8ff0d91-a4c3-4150-9585-7728bdb6a170) | ![IMG_3282](https://github.com/brave/brave-ios/assets/17885425/910a9f97-4803-4a62-96a5-f1666a5a0520) | ![IMG_3285](https://github.com/brave/brave-ios/assets/17885425/bb275f09-6339-4e54-9726-924eed5a3ce7) | ![IMG_3287 2](https://github.com/brave/brave-ios/assets/17885425/9a1aae2e-8213-4511-b1e4-832e76079ceb)

**Comment by Uni-verse** [comment]
Verified on `iPad` running `iPadOS 15.5` using version `1.52 (23.6.28.13)`

- Ensured adding/removing playlist using icon in url bar, shared menu and long pressing on the video
- Ensured playlist video opens and video plays
- Ensured moving, deleting and downloading playlist items works
- Ensured user is able to delete media, folders with media by swiping as well as edit mode
- Ensured adding shared playlist folders works - https://github.com/brave/brave-ios/issues/7658
- Ensured Playlist data is preserved when upgrading
- Ensured Playlist support on the following websites:
  - youtube.com
  - dailymotion.com
  - twitch.tv
  - rumble.com

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_0255 2](https://github.com/brave/brave-ios/assets/17885425/20f48ae2-b6d7-412e-b189-2e94934abe49) | ![IMG_0256 2](https://github.com/brave/brave-ios/assets/17885425/383e6a4e-066c-4faf-8e69-534a4f8e6cce) | ![IMG_0257 3](https://github.com/brave/brave-ios/assets/17885425/476bd3d1-00ec-40be-a3f1-6b03971a90fd) | ![IMG_0258 3](https://github.com/brave/brave-ios/assets/17885425/3e010cb9-d6a6-437d-aad5-4404f6ef0bfb) | ![IMG_0259 3](https://github.com/brave/brave-ios/assets/17885425/edddceb6-03c8-4e2f-b309-9146968ea98a) | ![IMG_0260 2](https://github.com/brave/brave-ios/assets/17885425/eaa69656-0c57-4575-b91b-d79fc601fa1c)
![IMG_0263 3](https://github.com/brave/brave-ios/assets/17885425/ce61c703-dd6a-4847-a5bf-a6aeb0bd0817) | ![IMG_0264 3](https://github.com/brave/brave-ios/assets/17885425/42c930a9-ae72-4858-8ff8-3c5488fb810b) | ![IMG_0265 3](https://github.com/brave/brave-ios/assets/17885425/8f4b4566-8fa2-4e68-8aca-761d08478747) | ![IMG_0267 3](https://github.com/brave/brave-ios/assets/17885425/d70c5aac-30b1-473a-80ed-c79a1aeb4b4c) | ![IMG_0268 3](https://github.com/brave/brave-ios/assets/17885425/75fee79a-3f2b-4972-877b-5093eb2299d9) | ![IMG_0269 2](https://github.com/brave/brave-ios/assets/17885425/0200001d-baf4-4ffd-851c-8861accc32ec)
