### ISSUE TITLE
Bookmarks from sync are received in wrong order.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#735]
### Steps to Reproduce 
  1. Add few bookmarks on both devices
  2. Pair them with sync

**Actual result:** 
The order of bookmarks on both devices is not the same

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+/6 and iPad Pro using 1.9(19.3.9.1)
  - Verified bookmark/folder order is retained on bookmark hanger
  - Verified order of nested bookmarks inside folder is also maintained
  - Verified re-ordering bookmarks/folders, propagates the changes to all devices on the chain

- Verified passed with 1.9 (19.3.9.1) on iPhone 8
  - Verified bookmark/folder order is retained on bookmark hanger
  - Verified order of nested bookmarks inside folder is also maintained
  - Verified re-ordering bookmarks/folders, propagates the changes to all devices on the chain

* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR.
  - Verified bookmark/folder order is retained on bookmark hanger
  - Verified order of nested bookmarks inside folder is also maintained
  - Verified re-ordering bookmarks/folders, propagates the changes to all devices on the chain

* Verified passed with 1.9 (19.3.9.1) on iPhone SE
