### ISSUE TITLE
Add standard (non-aggressive) Adblock mode

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#7352]
### Description: 
We mostly use standard ad-blocking in iOS except for cosmetic filtering. The intention is to add a option to use standard or aggressive tracking and privacy blocking in iOS to conform to the same standards as desktop as seen in the following screenshots:

<img width="393" alt="Screenshot 2023-04-27 at 11 56 32 AM" src="https://user-images.githubusercontent.com/909331/234915778-80507173-8763-47ad-b9e5-8a4a9132a542.png">

<img width="682" alt="Screenshot 2023-04-27 at 11 56 53 AM" src="https://user-images.githubusercontent.com/909331/234915760-e2cc46f0-5748-469f-a814-c85bfc7afd29.png">

Here is what we currently have in iOS:
![Simulator Screen Shot - iPhone 14 Pro - 2023-04-27 at 11 58 30](https://user-images.githubusercontent.com/909331/234915993-8cbf309d-1697-44a9-a1cd-d4987aedb970.png)
<img width="398" alt="Screenshot 2023-04-27 at 11 58 20 AM" src="https://user-images.githubusercontent.com/909331/234916004-eb2183e7-da35-4552-9d87-61bd32196580.png">

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` & `iPad (7th Gen)` running `iPadOS 16.3.1` using version `1.51.1 (23.5.19.19)`

- Verified test scenarios in https://github.com/brave/brave-ios/pull/7437#issue-1705670346 on `fresh profile` and `upgraded profile`. Additional shields functionality testing was performed in https://github.com/brave/brave-ios/issues/7428#issuecomment-1559805037 for `iPhone` and https://github.com/brave/brave-ios/issues/7428#issuecomment-1561627041 for `iPad.` 

Test 1 (standard) | Test 1 (aggressive) | Test 2 (standard) | Test 2 (aggressive)
-|-|-|-
![IMG_3267](https://github.com/brave/brave-ios/assets/17885425/d9a2ce48-4b89-416a-8327-6cf5bb3044ca) | ![IMG_3268](https://github.com/brave/brave-ios/assets/17885425/b4b68f02-f528-462e-824a-b7da6f882903) | ![IMG_3270 2](https://github.com/brave/brave-ios/assets/17885425/3e47aada-1b17-4e80-b883-9d2e85910fa6) | ![IMG_3270](https://github.com/brave/brave-ios/assets/17885425/d5d90925-ef7d-48b8-ab60-e294da93aaa2)

Test 5 (standard) | Test 5 (aggressive)
-|-
![IMG_3271](https://github.com/brave/brave-ios/assets/17885425/ae135957-1d47-41a6-a6dd-bd111b303e35) | ![IMG_3272 2](https://github.com/brave/brave-ios/assets/17885425/914430b2-93b4-4029-9bcc-a4024f02cced)
