### ISSUE TITLE
Playlist :: Small text update

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#7353]
### Description: 
Please update the text from from Saved to Offline to Added to Offline

![IMG_1781](https://user-images.githubusercontent.com/7606853/234929026-44e28c83-46a5-45ac-b5a1-c121e573f864.png)

@iccub as part of this can you please search for other "Saved" words and list them here so we can update if needed. 
Thanks

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5]
Version: 1.52 (23.6.9.13)
BraveCore: 1.52.117 (114.0.5735.90)
```
---------------------------

**STEPS:**
1. Launch Brave
2. Go to www.youtube.com > Open any video
3. Add the video to playlist
4. Three-dot Menu > Playlist > Three-dot Menu > Remove Offline Data
5. Three-dot Menu > Save Offline Data > Verify

**ACTUAL RESULTS:**
- Verified that `Saved to Offline` updated to `Added to Offline`

<img width="602" alt="Screenshot 2023-06-12 at 12 03 46" src="https://github.com/brave/brave-ios/assets/128532965/a2cd048b-2d34-45c8-a133-37adc7804b0b">
