### ISSUE TITLE
Relaunching app always focus on the last tab 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#736]
### Description: 
Relaunching app always focus on the last tab 

### Steps to Reproduce 
  1. Open 4-5 tabs and visit different sites in it
  2. Set tab 1 to focus and remove the app from memory
  3. Relaunch app, automatically focus is set to the last tab

**Actual result:** 
Relaunching app always focus on the last tab 

**Expected result:**
Focus should be set to the same tab that was active before the app was removed from memory

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7.2(19.1.15.15). Reproduces on app store build as well

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
This is an annoying problem for  people who are big on tabs. @jhreis @danishjafri88 @kylehickinson

**Comment by LaurenWags** [comment]
Reproduced on iPad 5th Gen with 1.7.2 (19.1.16.16)

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.8 running 1.32.5(21.11.2.23)
- Verified steps from issue description
- Verified closing and relaunching the app sets focus on the previously active tab :+1: 
-------------
Verification passed on iPhone XR with iOS 15.0.1 running 1.32.5(21.11.2.23)
- Verified steps from issue description
- Verified closing and relaunching the app sets focus on the previously active tab 
-----------
Verification passed on iPad Pro with iOS 15.1 Beta 3 running 1.32.5(21.11.2.23)
- Verified steps from issue description
- Verified closing and relaunching the app sets focus on the previously active tab
