### ISSUE TITLE
Allow cosmetic filtering script to be non-aggressive (not hide 1st party elements)

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#7360]
### Description: 
This is a prerequisite to issue #7352

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` & `iPad (7th Gen)` running `iPadOS 16.3.1` using version `1.51.1 (23.5.19.19)`

As the PR associated is a prerequisite to https://github.com/brave/brave-ios/issues/7352. 

QA has verified test scenarios in https://github.com/brave/brave-ios/pull/7437#issue-1705670346 on `fresh profile` and `upgraded profile`. Additional shields functionality testing was performed in https://github.com/brave/brave-ios/issues/7428#issuecomment-1559805037 for `iPhone` and https://github.com/brave/brave-ios/issues/7428#issuecomment-1561627041 for `iPad.`
