### ISSUE TITLE
Spam on myBB forums using Brave

### ISSUE THREAD

**Issue by prov3it** [brave/brave-ios#7362]
When using Brave on iOS im posting spam like: "a[href^="https://camfapr.com/landing/click/"]" and a dozen other links after writing my message and pressing post or send. I only have this issue using this browser and on those specific forums. How is something like this possible?

Due to privacy i cannot share any website information, other than its running an updated version of myBB. Is it possible that this is Brave related? Or do i have to look in another corner?

**Comment by kylehickinson** [comment]
This is most likely a forum specific issue, Brave does not inject any data into forms.
