### ISSUE TITLE
Number is added in front of title for tabs and history

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#7364]
### Description: 
Having how many opened and sync chain / Open tabs enabled, i noticed that the title for youtube tabs and also for history will have a number in round brackets prepending it. Example: (36) 

Steps to reproduce may not to exact

### Steps to Reproduce 
  1. Install 1.50.x
  2. Open some YT videos, and some other tabs
  3. Add some videos to playlist that are opened
  4. Connect to sync chain, enabled open tabs
  5. Continuing building history, add more items videos to play after connecting to sync chain
  6. Observe for issue in tab bar and in history page

### Actual result: 
Example | Example
-|-
![IMG_0222 2](https://user-images.githubusercontent.com/17885425/235459024-c6bcf1e3-2a6f-4f8c-8599-3e41efac4e1a.PNG) | ![IMG_0224 2](https://user-images.githubusercontent.com/17885425/235459043-f7882e80-c30e-4437-b5f5-3692062ec475.PNG)

### Expected result:
Should not show number

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduce, issues shows often

### Brave Version:  `1.50 (23.4.27.16)`

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? TBD

### Device details: 
iPad (9th) Gen, iPadOS 15.6.1

**Comment by kylehickinson** [comment]
Going to close this as its a website issue and not Brave
