### ISSUE TITLE
Downvotes fail to redeem for ad confirmations 

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#7365]
### Description: 
Downvotes fail to redeem for ad confirmations, not a regression

### Steps to Reproduce 
  1. Install 1.50.x or 1.49.1 dev channel build
  2. Enable verbose logging (*/brave/*=5) in debug settings
  3. Enable rewards 
  4. When ad notification is shown, swipe to left to remove (should see thumbs down)
  5. Confirm view, click, dismiss, downvote ad nconfirmation is logged (console.app)
  6. Observe whether downvote confirmation is redeemed

### Actual result: 
![Screenshot 2023-04-28 at 7 29 46 PM](https://user-images.githubusercontent.com/17885425/235462105-7a3929f6-a15d-4b9c-bcc0-2edb0d9a4f5f.png)

### Expected result:
Should be redeemed

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

### Brave Version:  `1.50 (23.4.27.16)`

- Can you reproduce this issue with the most recent build from TestFlight?  Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
Reproducible on 1.49.1.x
Reproducible on 1.50.x

**Comment by tmancey** [comment]
@Uni-verse could you please set the logging level to 6, and if possible send the log as a text file? Thanks

**Comment by btlechowski** [comment]
Not reproducible on desktop

Brave | 1.52.86 Chromium: 113.0.5672.77 (Official Build) beta (64-bit) 
-- | --
Revision | c4236862955e005c2187105415ac4a2ecf86dff1-refs/branch-heads/5672_62@{#3}
OS | Ubuntu 18.04 LTS

```
[2796:2796:0511/122650.153867:VERBOSE1:redeem_opted_in_confirmation.cc(363)] Successfully redeemed opted-in downvote confirmation for ad_notification with transaction id 9d8f453a-1135-4d77-b67e-7f88b0d2cb3f and creative instance id 4cda3ae7-1f70-4bca-b361-ca01d6a8f1ed

```

**Comment by tmancey** [comment]
cc @tackley fix for 404 not found

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using version `1.53 (23.7.6.16)`

Using STR in https://github.com/brave/brave-ios/issues/7365#issue-1690846337

- Ensured that downvotes are successfully redeemed for ad notifications

![Screenshot 2023-07-07 at 12 13 50 PM](https://github.com/brave/brave-ios/assets/17885425/973dee2a-84e6-4dc0-80be-a9b7fb4cd6bb)
