### ISSUE TITLE
Wallet: NFT auto discovery

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#7370]
```[tasklist]
### Tasks
- [x] Add Web3 "Enable NFT discovery" option in Settings
- [x] Add "Enable NFT auto-discovery" popup in NFT tab
```

**Comment by diracdeltas** [comment]
please note the concerns here: https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1682628895078679?thread_ts=1682622628.848399&cid=C023VS4HJ6Q. in particular it should be possible for the user to remove an NFT if it seems malicious, and the setting should link to https://github.com/brave/brave-browser/wiki/NFT-Discovery for more info. cc @stoletheminerals

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 16.5 running 1.52 (23.6.1.16)
- Verified steps from [#7400](https://github.com/brave/brave-ios/pull/7400)
- Verified `Enable NFT Discovery` setting is shown under Web3 settings 
- Verified `Enable NFT Discovery` is disabled by default
- Verified restoring a wallet that has NFT's brings up the auto-discovery popup when navigating to NFT tab
- Verified clicking on the `Learn more` link on the auto-discovery popup loads [GitHub Wiki page](https://github.com/brave/brave-browser/wiki/NFT-Discovery) about NFT
- Verified manually toggle `Enable NFT Discovery` setting doesn't show the auto-discovery modal when switching to NFT tab
- Verified able to manually add an NFT via Import NFT dialog in the NFT tab

<video src=https://github.com/brave/brave-ios/assets/17010094/f3eefde3-60f9-45b1-9a09-5d45eaac3882> | <video src=https://github.com/brave/brave-ios/assets/17010094/fd5d328e-cd35-484e-be06-96cadc7a5eda> | <video src=https://github.com/brave/brave-ios/assets/17010094/41e9e543-70f3-4e43-a2e0-b1b810601962>
-- | -- | --
