### ISSUE TITLE
Slide mode cannot be turned off

### ISSUE THREAD

**Issue by acli** [brave/brave-ios#7372]
### Description: 
The right edge is used in many apps. However, when interacting with the right edge, Brave would sometimes come out in “slide” mode. In the past, we can just change to full-screen mode and switch back to the other app. Now this no longer works; even after switching to full-screen mode, Brave continues to slide out when interacting with the right edge, making Brave unusable.

### Steps to Reproduce 
  1. Run Brave
  2. Use other apps until interacting with the right edge causes Brave to slide out
  3. Try to disable slide mode

### Actual result: 
Slide mode cannot be disabled. And there is no preference to turn this unwanted function off.

### Expected result:
Either Brave should honour the user’s selected mode, or there should be a preference to disable this unwanted function.

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Happens multiple times every day.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details: 
Brave Version 1.46.2 (23.1.10.20)

iPadOS 16.3.1

**Comment by iccub** [comment]
I do not think it's something we can control
