### ISSUE TITLE
Duplicate Safe Browsing settings

### ISSUE THREAD

**Issue by fmarier** [brave/brave-ios#7373]
When we enabled Safe Browsing (via Apple API), we removed the old list-based feature we had, but it appears that we left the original toggle around:
![signal-2023-05-01-21-21-06-190](https://user-images.githubusercontent.com/167821/235754243-957de7da-4237-46d5-a9cf-a2e5fa67cb2b.jpg)

In addition, the text label underneath the correct setting is not the correct one:
![signal-2023-05-01-21-20-37-894](https://user-images.githubusercontent.com/167821/235754241-d6788884-94b1-4fb2-a126-486e0dd98c34.jpg)

This is what was agreed in the [security review](https://github.com/brave/security/issues/693#issuecomment-1010306309):

> Block Dangerous Websites
> Safe Browsing protects against websites which are known to be dangerous.

Therefore there are two changes to make:

- [x] Delete the old *Block Phishing and Malware* toggle.
- [ ] Update the label text for the *Block Dangerous Sites* toggle.

**Comment by fmarier** [comment]
@iccub Thank you for deleting the old setting.

Looking at your PR, I didn't see the updated label text. Did you intend to do it in a separate PR?

**Comment by iccub** [comment]
@fmarier Brandon said it will be in followup ticket. We ordered translations for build 1.51 already

**Comment by fmarier** [comment]
Sounds good. Is there another issue already open for this or should we keep this one open?

**Comment by iccub** [comment]
Let's close. Followup ticket here https://github.com/brave/brave-ios/issues/7430

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: iPhone 14 [iOS 16.4.1] and iPad Air [iPadOS 16.4.1]
Version: 1.51 (23.5.11.22)
BraveCore: 1.51.114 (113.0.5672.92)
```
---------------------------

**STEPS:**
1. Launch Brave > Three Dot Menu > Settings
2. Brave Shields & Privacy > Verify

**ACTUAL RESULTS:**
- Verified that `Block Phishing and Malware` setting is removed
- Verified that `Block Phishing Control` was removed from `Shields Popover`

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/63c0a31e-28ca-4bf2-8e74-8c2bd45d1730) | ![2](https://github.com/brave/brave-ios/assets/128532965/5ebe1a9b-8e7e-47ce-b9e1-b940fa92d8d0) |

NOTE: `Safe Browsing protects against websites which are known to be dangerous.` text changes tracked here #7430
