### ISSUE TITLE
Safe Browsing setting is missing a "Learn More" link

### ISSUE THREAD

**Issue by fmarier** [brave/brave-ios#7374]
The Safe Browsing setting (*Block Dangerous Sites*) we have is missing a "Learn More" link to take users to our support page: https://support.brave.com/hc/en-us/articles/15222663599629-Safe-Browsing-in-Brave

This was brought up during the [security review](https://github.com/brave/security/issues/693#issuecomment-1010306309) but never implemented.

This is separate from the changes in #7373 since @kylehickinson said that it would be harder to get a link added there.

**Comment by fmarier** [comment]
Equivalent brave-core issue is https://github.com/brave/brave-browser/issues/20514

**Comment by anthonypkeane** [comment]
Please use "Learn More" vs "Learn more" when implementing. Thanks
