### ISSUE TITLE
Opening/Closing a lot of tabs causes UI stutter

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#7375]
### Description: 
- Opening or Closing a lot of tabs, causes the UI to freeze or stutter.

### Steps to Reproduce 
  1. Bookmark 10+ tabs
  2. Hold down the finger on the bookmarks folder and choose "Open All"
  3. All tabs open

### Actual result: 
- UI freeze

### Expected result:
- Should lazy load and open all tabs without issue

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily reproduced

### Brave Version: 
- 1.51 (actually not sure???)

**Comment by Uni-verse** [comment]
Verified on `iPad (9th Gen)` running `iPadOS 15.6.1` & `iPhone X` running `iOS 16.3.1` using version `1.51 (23.5.15.14)`

Using STR in https://github.com/brave/brave-ios/issues/7375#issue-1693063680

- Ensured that opening 10+ bookmarked tabs does not cause UI to stutter.
- Ensured that closing 10+ tabs does not cause stutter issues.
- Ensured closed tabs show up in `Recently Closed Tabs` Page.

<table><tr><td>Recently Closed</td><td>Screen recording</td></tr>

<tr><td>

![IMG_0235 3](https://github.com/brave/brave-ios/assets/17885425/8f1e8370-426b-4f39-acc1-b628ca54aa91)

</td><td>

https://github.com/brave/brave-ios/assets/17885425/346abe96-79fa-40be-90c1-1c86d3bde25d

</td></tr></table>

Example | Example | Example
-|-|-
![IMG_3209](https://github.com/brave/brave-ios/assets/17885425/69cc64c4-1da0-4f6f-809b-12cb460cf4fe) | ![IMG_3210](https://github.com/brave/brave-ios/assets/17885425/6f9e1b72-67a9-4310-a17c-8dbdc1374ac4) | ![IMG_3211](https://github.com/brave/brave-ios/assets/17885425/cd04b19c-6076-48ec-8b55-ab22c743810c)
