### ISSUE TITLE
Clicking on Twitter icon switches to Twitter app instead of loading the page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#738]
### Description: 
Clicking on Twitter icon switches to Twitter app instead of loading the page

### Steps to Reproduce 
  1. Visit https://brainbondy.com/ in a new tab
  2. Click the Twitter icon on the top right corner of the home page
  3. App switches to Twitter without confirmation 

**Actual result:** 
https://youtu.be/xq5id6yT77Y

**Expected result:**
Should either load the page in a new tab or same tab or prompt if app context switching is being done

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7.2(19.1.15.15)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
An issue exists for this #551 with an accompanying PR: #619

**Comment by srirambv** [comment]
Perfect :+1: . Didn't come up when I search.  Closing as dupe
