### ISSUE TITLE
VPN easy access region switcher

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#7380]
### Description: 

VPN Easy Region Switcher

Details TBA

Search VPN ideas in Google Doc and read Easier Country Selection

Figma File VPN https://www.figma.com/file/PqLTp3DnANLQMM1XzaChqZ/Mobile-VPN?node-id=1662-21300&t=OZ2r2P1cvHZpvGcS-0

Section iOS: Country Selector Main Menu Addition

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.51 (23.5.8.18)`

_Fresh Profile_

- Verified `VPN Region` is shown in the menu when VPN is enabled.
- Verified `Current Setting` is shown in menu on New Tab page.
- Verified disabling VPN hides the `VPN Region` setting.
- Verified VPN server region is set to `Automatic` by default.
- Verified country flag is displayed corresponding to server region that is selected.
- Verified that changing server regions using different protocols works.
- Verified VPN region setting in private browsing mode.

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_3151](https://github.com/brave/brave-ios/assets/17885425/a7d0fef3-fff5-4284-b1aa-a53fab0cd328) | ![IMG_3152](https://github.com/brave/brave-ios/assets/17885425/37abd1e4-4b5c-4c2d-b863-b3f8f81104e3) | ![IMG_3142 2](https://github.com/brave/brave-ios/assets/17885425/a60c6931-a34b-43c5-8b2d-8e1a5bf680b8) | ![IMG_3156](https://github.com/brave/brave-ios/assets/17885425/913070d7-bc03-4758-83cb-355478b5f7d7) | ![IMG_3157](https://github.com/brave/brave-ios/assets/17885425/e8700310-0b8e-4699-a469-098e2861e09c)

 _Existing Profile_
 
 Issues encountered:
 https://github.com/brave/brave-ios/issues/7432
 
 - Verified purchasing VPN in previous version and then upgrading shows easy access switcher.
 - Verified changing regions works on upgraded profile.
 - Verified custom region is retained when upgrading from 1.50.x
