### ISSUE TITLE
Wallet: Show transactions from all networks under each account activity screen

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#7385]
Since core is going to be upgraded to 1.52.x, we will have the ability to fetch all transactions from all networks. Currently, we are only fetching all transactions that belong to that account from the current selected(default) network of that account's coin type.

For example, if a user has an Eth account with address 0xA and it has Tx A on Eth Mainnet, and Tx B on Polygon, and the default network for Eth coin type is Eth Mainnet
Currently we display transactions under 0xA is:
Tx A on Eth Mainnet
Expected the transactions under 0xA is:
Tx A on Eth Mainnet
Tx B on Polygon

This requirement is very similar to #7233 except this issue is for Account Activity Screen
This requirement should also apply to `AccountTransactionListView`. Can be integrated in the same issue but feel free to create a separated issue if necessary.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 16.5 running 1.52 (23.6.22.18)
- Verified steps from [#7441](https://github.com/brave/brave-ios/pull/7441)
- Verified all completed transaction activity from all network is shown under activity tab
- Verified rejected transactions are only shown under the account and not under activity tab

https://github.com/brave/brave-ios/assets/17010094/88a2f5dc-6c52-48f6-b7bb-e0eea16c254b
