### ISSUE TITLE
Clicking on a cal invite doesn't add that cal invite to the iOS calendar 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#7386]
### Description: 
When Brave is set as default, and a user clicks on a cal invite, the invite isn't added to the calendar, instead the cal file ics file is downloaded to files. 

With Safari, the file is added to the calendar. 

More here: https://bravesoftware.slack.com/archives/G01F4JUNXAQ/p1683137678857819

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5] 
Version: 1.52 (23.6.9.13)
BraveCore: 1.52.117 (114.0.5735.90)
```
---------------------------

**STEPS:**
1. Launch Brave > NTP
2. Edit one of the NTP favorites to this URL https://developer.apple.com/wwdc23/WWDC2023.ics
3. Then tap it and it should open a "add calendar event" screen

NOTE: It will open a blank screen over the browser window. This is the only way to make it work unfortunately, chrome iOS does the same thing

**ACTUAL RESULTS:**
- Verified that opening`.ics` file is offering to add a calendar event
- Verified that a new calendar event is created successfully
- Verified if a calendar invite is existing already, then only `Delete Event` option is available when opening `.ics` invite file

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/4b2fc63d-5f4d-4fcb-8d59-a9edd7951716) | ![2](https://github.com/brave/brave-ios/assets/128532965/4a8802fa-e8d4-4340-9363-e982967139d3) |

https://github.com/brave/brave-ios/assets/128532965/d19c3796-671a-4b78-a39a-ceafc01d727e
