### ISSUE TITLE
☀️ Light Theme + "Private Browsing Only".

### ISSUE THREAD

**Issue by TheAresjej** [brave/brave-ios#7387]
## Problem Description
If Private Browsing Only is enabled, the browser changes its theme to a dark one (incognito purple) - should use the general theme settings.

## Feature Overview
Please remove the reference to changing the appearance in the privacy options.

## Design
Default Colors.

## Implementation Details
Temporarily, you can add a comment to the design call until you come up with a better solution.

**Comment by iccub** [comment]
No plans to do that currently. There will be some color updates but it's still going to stay within purple color range
