### ISSUE TITLE
Adding favourite without http/https prefix doesn't load the site

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#739]
### Description: 
Adding favourite without http/https prefix doesn't load the site

### Steps to Reproduce 
  1. Clear profile on 1.7.2(19.1.15.15)
  2. Edit a favourite and add title as `Github` and replace url with `github.com`
  3. Load the edited favourite, doesn't load the site
  4. Edit the same favourite and add `https://` prefix in URL
  5. Load the favourite, site is loaded correctly

**Actual result:** 
https://youtu.be/kGOyRhP-3WQ

**Expected result:**
Should be able to load the site since user doesn't add https/http prefix in URL bar while loading the site

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7.2(19.1.15.15)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by JonKaleidoscope** [comment]
Hey @srirambv,
I was investigating potential fixes for this solution and I wanted to vocalize some concerns and possible solutions before creating the PR with the changes.

1. The path forward seems to include some light `URL` string parsing for the absence of a url scheme and to simply inject a default scheme since one it is not provided. Should we be adding `http://` or `https://`. I am leaning on the side of `http://` because it is not guaranteed all sites will support `https://` and the clever sites redirect `http` traffic to `https`.

2. Where should this scheme injection logic happen? 
        A. The easiest place appears to be at the delegate handler for the favorites. The downside with this approach is it does not solve all scenarios. There is a similar issue occurring for Bookmarks as well.
        B. At the point the URL gets inserted into the Address Bar. This approach resolves the issue occurring in A however the favicon images for the favorite/bookmarks do not update correctly because the URL is running into the same issue with the schema when retrieving the favicon image.
        C. Rewriting the URL at the point it get's saved as a Favorite / Bookmark. This seems like the best approach. It requires a little sleight of hand on the Brave side but seems do the trick. The favicon images refreshes nicely and when the user taps on the newly save bookmark, they are navigated to the website successfully. Only downside here it the change may be slightly heavy handed.

Overall I am thinking I’m going to implement 2C.

**Comment by iccub** [comment]
This issue also happens for editing bookmarks.

@JonKaleidoscope  Another approach could be to force user to use correct http scheme, and show an error otherwise.

@jhreis do you have any preference how to deal with this?

**Comment by JonKaleidoscope** [comment]
@iccub you are absolutely right that is a valid option. That may also cause some overhead for creating that experience in both the favorites and bookmark sections. In addition, I caution that may also cause a slightly awkward user experience. When you put a `URL` in an address bar for a browser, you go to a site while probably not even thinking twice about adding a `http://`. It just populates that information for you. I think the same should hold true for creating and launching bookmarks.

**Comment by jhreis** [comment]
The ideal here would be to jus take whatever is in `bookmark.url`, shove it into the location bar on the top, and "hit" enter.

Whether it is:
>https://www.brave.com

>brave.com

>I love chocolate

Shouldn't matter. If it is not a valid URL, the location bar will just perform its default action, which would generally be a search. The location bar handles all of this logic for us (e.g. appending scheme), so best to just let it do its work.

Does that sound pretty good @JonKaleidoscope @iccub ?

**Comment by JonKaleidoscope** [comment]
![giphy](https://user-images.githubusercontent.com/43318682/51437299-6c43bb00-1c6a-11e9-8ca1-dba9ffadb17e.gif)

@jhreis Sounds pretty good. 

I created a PR with the changes so you all can take a look and tell me what you think. I do want to note this change enables the _Favorites_ to accept pretty much any string not just URL's. The _Favorites_ UI allowed for easier changes but modifying the _Bookmarks_ to accept values that are not URL's is little more involved. In the nature of keeping PR's small, I think those changes would be better served in another PR.

The `BookmarksViewController` uses `URLRow` which requires the value to be an actual `URL`. [See details here](https://github.com/brave/brave-ios/blob/12df4aac9219cc6795866eab9de16f8696d5e45f/Client/Frontend/Menu/BookmarksViewController.swift#L95)

The `URLRow` is a part of **Eureka** framework and the implementation details for this particular class can be found [here](https://github.com/xmartlabs/Eureka/blob/master/Source/Rows/FieldsRow.swift).

**Comment by LaurenWags** [comment]
* Verified passed with 1.9 (19.3.9.1) on iPad 5th Gen using STR from above. Encountered and logged https://github.com/brave/brave-ios/issues/971
* Verification passed on iPhone 7+ running 1.9(10.3.9.1), Also encountered #971 
* Verification passed on iPhone 6 and iPad Pro 
* Verified passed with 1.9 (19.3.9.1) on iPhone SE
* Verified passed with 1.9 (19.3.9.1) on iPhone 8, encountered #971
* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR. Also experienced #971
