### ISSUE TITLE
Headers for responses should be case-insensitive

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#7394]
### Description: 
- Currently when Brave-iOS parses headers, it parses them case-insensitive

### Steps to Reproduce 
  1. None

### Actual result: 
- Headers are Case-Sensitive parsed which can cause hidden bugs

### Expected result:
- Should parse headers case-insensitive

### Test Plan:
- In the PR :)

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.3.1` using version `1.51 (23.5.11.17)`

Using Test Plan in https://github.com/brave/brave-ios/pull/7395#issue-1697869251

_**NTP Backgrounds**_

- Ensured that background images on NTP are showing
- Ensured that sponsored images are showing on NTP
- Ensured that disabling background images in settings will not display them on NTP
- Ensured background/sponsored image are shown while using VPN

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_3177](https://github.com/brave/brave-ios/assets/17885425/0dfff9fa-0e01-4d68-9948-24bea5c5a923) | ![IMG_3178](https://github.com/brave/brave-ios/assets/17885425/4d1f97d7-ab66-4062-ae08-fadf7df33ce6) | ![IMG_3179](https://github.com/brave/brave-ios/assets/17885425/310bc229-98d5-4b1e-a89d-1fe77cfc9c75) | ![IMG_3180 2](https://github.com/brave/brave-ios/assets/17885425/9e6ec1b7-3f81-4555-bd95-235998193af5) | ![IMG_3182](https://github.com/brave/brave-ios/assets/17885425/3f5e1508-ef52-4614-980f-5b30dcacc5b6) | ![IMG_3183](https://github.com/brave/brave-ios/assets/17885425/685f1280-0ea9-4851-b3be-8fa5bf02457f)

_**Adblock lists**_

- Ensured that page has `true` for all values with shields up and `null` with shields down when loading `https://test-pages.privacytests.org/tracking_content.html.`
- Ensured that app launches relatively quickly with many filters enabled in the content filtering.
- Ensured that cosmetic filtering is working when loading `twitter.com` or `reddit.com`
- Ensured that script loading test page is passing, showing true when shields are up and null when shields down - https://dev-pages.brave.software/filtering/scriptlets.html

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_3185](https://github.com/brave/brave-ios/assets/17885425/46104aca-16c0-463b-96e9-0e1c9fbe391a) | ![IMG_3187](https://github.com/brave/brave-ios/assets/17885425/65cfea06-7973-4405-830f-737fc2cca2a0) | ![IMG_3188](https://github.com/brave/brave-ios/assets/17885425/aadef384-fcc4-4a8f-a07e-620e9a1e5b8b) | ![IMG_3189](https://github.com/brave/brave-ios/assets/17885425/fb26c39e-341c-41c0-a427-d45dcb2db0c8) | ![IMG_3190](https://github.com/brave/brave-ios/assets/17885425/6153878d-10bf-4787-8957-416439d26e50) | ![IMG_3191](https://github.com/brave/brave-ios/assets/17885425/59b414ba-be3e-4a6c-8484-0ee98b643088)

**_Playlist Sharing_**

- Confirmed downloading and saving a shared playlist is working using `bsa-sample` playlist.
- Confirmed shared playlist folder loads in Brave Playlist and user is able to use playback.
- Confirmed deleting shared playlist folder.

Example | Example | Example | Example
-|-|-|-
![IMG_3195](https://github.com/brave/brave-ios/assets/17885425/deaf56ac-3b19-4f12-9a1c-9696c56ebc0b) | ![IMG_3196](https://github.com/brave/brave-ios/assets/17885425/1061d80c-bbf5-4b14-ad96-359e30ab94c2) | ![IMG_3197](https://github.com/brave/brave-ios/assets/17885425/8fd68aca-8d2c-48dd-8b6e-34e0f38163e0) | ![IMG_3198](https://github.com/brave/brave-ios/assets/17885425/e8be4e48-73fb-48a8-abf0-5af12937b221)
