### ISSUE TITLE
Monogram favicons change their color every app launch

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7396]
### Steps to Reproduce 
  1. Add example.com to favorites
  2. Notice its favicon background color
  3. Restart the app
  4. Notice the bg color again

### Actual result: 
It changes, bad for visual memory

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5]
Version: 1.52 (23.6.9.13)
BraveCore: 1.52.117 (114.0.5735.90)
```
---------------------------

**STEPS:**
1. Launch Brave > NTP
2. Go to www.example.com > Three-dot Menu > Add to Favorites
3. Return to NTP > Verify background color for www.example.com
4. Restart the app > Verify the background color for www.example.com once again

**ACTUAL RESULTS:**
- Verified that the favicon for www.example.com has the same background color before and after the app restart.

https://github.com/brave/brave-ios/assets/128532965/81c69463-b4bd-4415-9a33-385d9d026d50
