### ISSUE TITLE
Scrolling Tab Bar Long-Press problem

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#7397]
### Description: 

Scrolling Tabs Bar is rarely crashing when a tab is long-pressed

### Steps to Reproduce 
  1. Make Tabs Bar Visible
  2. Add 10+ tabs
  3. Long press a view inside scrolling Tabs Bar 
  4. Crash when started moving

### Actual result: 
Crash in rare cases

### Expected result:
No crash at all

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Very hard to reproduced

### Brave Version: 
Any

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
Any

### Website problems only:
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.4.1]
Version: 1.51 (23.5.11.17)
BraveCore: 1.51.114 (113.0.5672.92)
```
---------------------------

**STEPS:**
1. Add 10+ tabs
2. Make Tabs Bar visible
3. Long press a view inside the scrolling Tabs Bar
4. Try to move tabs around

**ACTUAL RESULTS:**
- Verified that no crashes were observed when long press on any tab on Tabs Bar
- Verified that it's possible to reorganize tabs

https://github.com/brave/brave-ios/assets/128532965/a9a6eb53-36df-4c8c-9014-8ce6032a408c

https://github.com/brave/brave-ios/assets/128532965/ea879896-519b-47a2-b5e8-c9b3ad23c48f
