### ISSUE TITLE
Open Tabs Session Time hour format display error

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#7410]
### Description: 
The proper @4 hr time should be displayed in Open Tabs screen

### Steps to Reproduce 
  1. Sync Open Tabs
  2. Check hour display on session

### Actual result: 
24 hr time is displayed but also am/pm

### Expected result:
Hour should be displayed properly on 24 hr

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 💯 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 💯 
- Can you reproduce this issue with the current build from AppStore? 💯 

### Device details: 
N/A

### Website problems only:
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5] 
Version: 1.52 (23.6.9.13)
BraveCore: 1.52.117 (114.0.5735.90)
```
---------------------------
<details>
<summary> 12 hour format - PASS </summary>

**STEPS:**
1. Disable `24-Hour Time` in device settings
2. Launch Brave > Tab tray
3. Choose `Tabs from Other Devices` > Turn on Sync > Verify

**ACTUAL RESULTS:**
- Verified that the time format is shown correctly on `Tabs from Other Devices` screen when a 24-hour format is disabled

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/24c35f62-ff67-4f8f-8429-a9c7639ca156) | ![2](https://github.com/brave/brave-ios/assets/128532965/252c2912-07e3-4f43-9204-ddea5aabd1fa) | ![3]() | ![4]() |
</details>

<details>
<summary> 24 hour format - PASS </summary>

**STEPS:**
1. Enable `24-Hour Time` in device settings
2. Launch Brave > Tab tray
3. Choose `Tabs from Other Devices` > Turn on Sync > Verify

**ACTUAL RESULTS:**
- Verified that the time format is shown correctly on `Tabs from Other Devices` screen when a 24-hour format is enabled

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/e46b670e-11a4-41b5-83c9-756f3919a5d3) | ![2](https://github.com/brave/brave-ios/assets/128532965/674b0014-2c53-492c-b956-27894502893d) |
</details>
