### ISSUE TITLE
VPN profile fails to initialize after purchase

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#7413]
### Description: 
VPN profile fails to initialize after purchase

Usually works the second time, sometimes takes a few tries on the install VPN profile screen on my device.

### Steps to Reproduce 
  1. Install 1.51.x, 1.50.x
  2. Complete IAP (Sandbox)
  3. Install VPN Profile
  4. Observe

### Actual result: 
![IMG_3128 3](https://user-images.githubusercontent.com/17885425/236935891-225c6470-8eb7-4982-ba91-bbdc772fa50f.PNG)

### Expected result:
Should prompt user to allow install

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

### Brave Version: `1.51 (23.5.8.16)`

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
iPhone 12, iOS 16.4
iPhone X, iOS 16.3.1

**Comment by iccub** [comment]
I noticed it few times in the past too. I would not block on it but it definitely keeps happening

**Comment by soner-yuksel** [comment]
> I noticed it few times in the past too. I would not block on it but it definitely keeps happening

Same here, it happened me couple of times, will try to dig into it and find out why this might be happening for next release.

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5] and iPad Air [iPadOS 16.4.1]
Version 1.52 (23.6.14.13)
BraveCore 1.52.125 (114.0.5735.110)
```
---------------------------

**STEPS:**
1. Launch Brave > Three-dot menu
2. Brave VPN > Purchase new subscription (Staging)
3. Install VPN Profile > Verify

**ACTUAL RESULTS:**
- Verified that I was able to purchase a new VPN subscription and install a certificate
- Verified that VPN can be turned ON and OFF

---------------------------

**iPhone 14**

https://github.com/brave/brave-ios/assets/128532965/58036113-baa0-42cf-853c-1b12d92c0213

**iPad Air**

https://github.com/brave/brave-ios/assets/128532965/f38458d7-18c6-4f65-93a0-f094d5d84e35
