### ISSUE TITLE
1.49.1 works, 1.50+ crashes on launch

### ISSUE THREAD

**Issue by mailinglists35** [brave/brave-ios#7415]
AppStore 1.49.1 works, AppStore 1.50 crashes on launch, Testflight 1.51 crashes on launch. see multiple recent crash logs from Testflight "share data" as well as share with developers from Analytics from AppStore version.

iOS 15.0
iPhone 13 mini

please do not suggest iOS update, I cannot. please fix it for all supported iOS. please do not raise minimum iOS version.

**Comment by mailinglists35** [comment]
yes I deleted and reinstalled, no success.

Yes I am able to upgrade+downgrade and confirm the breaking change has happened in 1.49.1 > 1.50

**Comment by mailinglists35** [comment]
no there is no jailbreak

**Comment by d9j** [comment]
seems like devs have no bandwidth to support/ test older ios versions :/

**Comment by iccub** [comment]
We have iOS 15 devices but they are on newer versions.
This crashes for 15.0 and 15.1 only. Swift's async await bug of some kind

We have a fix and the 1.51 build with it should be live this week.

**Comment by mailinglists35** [comment]
thanks, 1.51 testflight 23.5.12.16 works okay!
