### ISSUE TITLE
Custom Header Issue

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#742]
There is an issue were partner sites, such as Dow Jones are not able to detect whether or not traffic to their site is coming from Brave. 

@mandar-brave can you please provide the original spec for this functionality

**Comment by kjozwiak** [comment]
### Issue 1 ###

When installing Brave on iOS via one of the Dow Jones partner referral pages, you won't receive the tab where you can subscribe/sign up to either MW or Barrons and receive the premium content that was promised. Reproducible on both https://brave.com/dowjones-marketwatch and https://brave.com/dowjones-barrons

STR:

* Open https://brave.com/dowjones-marketwatch or https://brave.com/dowjones-barrons using Safari
* Once the referral promo page loads, click on the orange `Download Brave` button
* Tap on `Open` on the `Open in "App Store"?` modal
* Download `Brave` via the App Store (should have launched when tapping `Open` above)
* Once `Brave` has been installed, click on `Open` within the App Store

You'll notice that Brave is launched but the Dow Jones subscription/sing up tab isn't being loaded. Used `1.7.1 (18.12.19.01)`.

### Issue 2 ###

When your either logging in or logging out from a premium account that you received through the Brave promo on Brave iOS, you'll be redirected the following link which displays a blank page:

```https://accounts.barrons.com/assets/secondary-rp-sync.html?iframe_id=iframe-rp-barrons.com-1547673626804&ns=prod/accounts-barrons```

Example:

![img_9743](https://user-images.githubusercontent.com/2602313/51281586-df220d00-19b0-11e9-81b4-37043fd93094.PNG)

When you hit the following website, nothing will happen. You'll need to reload MW.

STR:

* launch `1.7.1 (18.12.19.01)`
* visit https://www.marketwatch.com/
* login into a premium account that you've received via the Brave promo

Once you login, you'll be directed to the above link and you'll see a white screen. Nothing happens and you'll need to manually go back to MW. Seems like the redirect is broken.

**Comment by kjozwiak** [comment]
Regarding premium content, seems like it's working. Here's some more information on both MW:

Once you've created a premium MW account via the Brave promotion, you'll be able to access the `Revolution Investing`. Example:

![img_9744](https://user-images.githubusercontent.com/2602313/51282044-2230b000-19b2-11e9-9524-3500d9590511.PNG)

Clicking on one of the premium articles under `Revolution Investing` will load the full article without any issues. I clicked on several premium articles within `1.7.1 (18.12.19.01)` and they all loaded without any issues.

Once you're logged out, accessing the same articles will display the `Subscribe` button as expected. Example:

![img_9746](https://user-images.githubusercontent.com/2602313/51282328-d2061d80-19b2-11e9-8876-18175454112c.PNG)

Logging into a premium account that was created using a Brave promotion within Chrome (or other browsers) will correctly display the `You have complimentary access to this premium newsletter when using Brave Browser`. Example:

![img_9741](https://user-images.githubusercontent.com/2602313/51282433-198ca980-19b3-11e9-8aae-c4eb0c281f4a.PNG)

![img_9742](https://user-images.githubusercontent.com/2602313/51282448-21e4e480-19b3-11e9-9865-fad985ceab0c.PNG)

**Comment by kjozwiak** [comment]
Working through some issues with Brarrons right now. I'll add more information once I understand what is happening. Also happening on Desktop.

**Comment by jhreis** [comment]
Related: #748

**Comment by kylehickinson** [comment]
@jhreis  Are these tickets still valid (this and #748)? 

Can't remember if we are even using custom headers anymore

**Comment by iccub** [comment]
Should be invalid now
