### ISSUE TITLE
Playlist Revamp: URL bar icons & menus

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#7422]
See Figma: `iOS Playlist`

Should replace the icons used for playlist, along with change the popover when adding an item and showing a menu when tapping an added item that allows for quickly changing where the video is saved, remove/undo and opening in playlist

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air`using version(s):
```
Device/OS: iPhone 14 [iOS 16.5] and iPad Air [iPadOS 16.4.1]
Version: 1.52 (23.6.22.18)
BraveCore: 1.52.125 (114.0.5735.110)
```

Filed follow-up issue #7644

---------------------------

**STEPS:**
1. Fresh install Brave > Launch Brave > Open www.youtube.com > Verify
2. Tap on `Watch the video` > Verify
3. Return to www.youtube.com > Open any video > Tap `Save to playlist` button > Verify
4. Add another video to a playlist > While toast notification is shown, tap `Change` > Verify
5. Tap `Add to playlist` button once again for the file that is already in the playlist > Verify
6. While the popover menu is opened, tap `Remove` > Verify
7. Tap `Undo` > Verify
9. While the popover menu is opened, tap `Change Playlist` > Verify
10. While the popover menu is opened, tap `Open In Playlist` > Verify

**ACTUAL RESULTS:**
- Verified that the pop-up is shown for the first landing on www.youtube.com
- Verified when tapping on `Watch the video` link, [brave.com/playlist](https://brave.com/playlist/) is opened
- Verified that `Add to playlist` button is working and video is added to a default playlist
- Verified that the toast notification is hidden ~4 seconds after the file is added to a playlist
- Verified that `Move to` UI is opened and the user can create a new playlist and move files between them
- Verified that the popover menu is opened when tapping `Add to playlist` for a file that is already in the playlist
- Verified that tapping `Remove` is removing the file from the playlist
- Verified that it's possible to `Undo` delete action
- Verified that `Move to` UI is opened and the user can create a new playlist and move files between them
- Verified that the current playlist is opened and the video starts playing from the moment where it was stopped playing last time

<details>
<summary> iPhone </summary>

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/ec5b4c27-8513-48eb-9c24-8c6caa44efb6) | ![2](https://github.com/brave/brave-ios/assets/128532965/22ef83aa-a851-43ea-8f2c-ac7156c599c2) | ![3](https://github.com/brave/brave-ios/assets/128532965/0eb02a77-6d19-43e8-a681-8bbd62816ee0) | ![4](https://github.com/brave/brave-ios/assets/128532965/1a5d296b-1b5a-415d-b109-d4e15473d392) |
|5|6|7|8|
| ![1](https://github.com/brave/brave-ios/assets/128532965/a4f36d14-3002-4691-ae5c-b247ffa56f9d) | ![2](https://github.com/brave/brave-ios/assets/128532965/889d74d8-5c23-4e1f-8e69-cd1791603293) | ![3](https://github.com/brave/brave-ios/assets/128532965/dd660a07-620c-4ebb-b499-9e27876a4084) | ![4](https://github.com/brave/brave-ios/assets/128532965/889f2215-4ced-4dfe-b80a-ad77246c572c) |
</details>

<details>
<summary> iPad Air </summary>

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/0a493713-864d-4834-8eb5-214651de20d4) | ![2](https://github.com/brave/brave-ios/assets/128532965/435cf0dc-a972-45e3-b811-4239845f913c) | ![3](https://github.com/brave/brave-ios/assets/128532965/c9ab7c51-87e6-44db-ade1-53e10d94156a) | ![4](https://github.com/brave/brave-ios/assets/128532965/ddaa217c-1beb-46d2-9c40-25c27689d22a) |
|5|6|7|8|
| ![1](https://github.com/brave/brave-ios/assets/128532965/c266ea99-3799-4d27-9c62-612e8870b3a3) | ![2](https://github.com/brave/brave-ios/assets/128532965/2bb96d46-0763-46ef-9942-887848f7f652) | ![3](https://github.com/brave/brave-ios/assets/128532965/6f22ad3d-a049-49e7-8744-dfbdbb85aed8) | ![4](https://github.com/brave/brave-ios/assets/128532965/60d80139-b217-4e53-aed4-1a227c088010) |
</details>
