### ISSUE TITLE
How to access dev tools?

### ISSUE THREAD

**Issue by jtheletter** [brave/brave-ios#7425]
I have a website that is displaying unexpected colors only on iOS Brave. Not on macOS Brave (not in desktop view, not in emulated mobile view), and not on Safari, Chrome, Firefox, or Edge in macOS or iOS.

To troubleshoot this in iOS Safari, I would connect iPhone to Mac via USB, launch macOS Safari, click from menubar Develop, click iPhone, select the browser tab, and I would have full and live access to dev tools.

How can I do this sort of debugging for iOS Brave?

**Comment by kylehickinson** [comment]
As of 1.50, using iOS 16.4, you can do this using the same steps as you do for Safari via the Develop menu.
