### ISSUE TITLE
Update Safe Browsing setting text, follow up to #7373

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7430]
See #7373

**Comment by hffvld** [comment]
Verified on `iPhone 14`  using version(s):
```
Device/OS: iPhone 14 [iOS 16.5] 
Version: 1.52 (23.6.9.13)
BraveCore: 1.52.117 (114.0.5735.90)
```
---------------------------

**STEPS:**
1. Launch Brave > Three-dot Menu
2. Settings > Brave Shields & Privacy
3. Scroll down and find `Block Dangerous Websites` > Verify title and subtitle strings

**ACTUAL RESULTS:**
- Verified that the new string for the title is `Block Dangerous Websites`
- Verified that the new string for the subtitle is `Safe Browsing protects against websites which are known to be dangerous. Learn More`
- Verified that `Block Dangerous Websites` is set to ON by default
- Verified that tapping on`Learn More` in `Safe Browsing protects against websites which are known to be dangerous. Learn More` is redirecting to https://support.brave.com/hc/en-us/articles/15222663599629-Safe-Browsing-in-Brave

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/0bf7e991-1e3a-4eb8-9977-3328ecf3ac6b) | ![2](https://github.com/brave/brave-ios/assets/128532965/7cd86d3e-c153-41f7-80f6-3d870d33a093) |
