### ISSUE TITLE
VPN region easy access displays incorrect region on existing profile

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#7432]
### Description: 
VPN easy access region switcher does not show correct region set.

1.50.x -> 1.52.x

### Steps to Reproduce 
  1. Install 1`.50.x` app version
  2. Enabled VPN
  3. Change region something other than your region (Canada in this case)
  4. Upgrade to version `1.52.x`
  5. Open menu on NTP, check region selected
  6. Open VPN settings, check location selected

### Actual result: 

https://github.com/brave/brave-ios/assets/17885425/bc5c495c-791f-42f4-b83e-74de222f00f1

### Expected result:
The region set on previous version should be shown

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

### Brave Version:  `1.52 (23.5.10.20)`

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 
iPhone X, iOS 16.3.1

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: iPhone 14 [iOS 16.4.1] and iPad Air [iPadOS 16.4.1]
Version: 1.51 (23.5.11.22)
BraveCore: 1.51.114 (113.0.5672.92)
```
Filed follow-up issue #7448 and #7449

---------------------------
<details>
<summary> Upgrade profile - PASS </summary>

**STEPS:**
1. Install 1.50.x app version
2. Enabled VPN
3. Change region to something other than your region (Canada in this case)
4. Upgrade to version 1.51.x
5. Open the menu on NTP, check the region selected
6. Open VPN settings, and check the location selected

**ACTUAL RESULTS:**
- Verified previously set country is shown after the upgrade
- Verified previous VPN status restored after the upgrade

https://github.com/brave/brave-ios/assets/128532965/f48b6269-44ff-49d1-bbcd-3e411193d293

</details>

<details>
<summary> Fresh profile - FAIL </summary>

**STEPS:**
1. Install 1.51.x app version
2. Enabled VPN
3. Change region to something other than your region
4. On the menu on NTP check the region selected
5. Open VPN settings > Check the location selected
6. Close and relaunch Brave > on the menu on NTP check the region selected
7. Open VPN settings > Check the location selected

**ACTUAL RESULTS:**
- Verified VPN is enabled
- Verified correct region is shown on the menu on NTP when the location is changed
- Verified correct region is shown in VPN settings when the location is changed

https://github.com/brave/brave-ios/assets/128532965/9fe4c111-d9c3-423a-80e8-13ecff76fe63

</details>
