### ISSUE TITLE
Discover assets loading indicator is not removed

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7433]
### Description: 

A certain case can cause the loading spinner shown on Portfolio when discovering assets is not removed correctly.

### Steps to Reproduce 
  1. Unlock your wallet
  2. Wait for loading spinner beside `Assets` header to disappear
  3. Lock your wallet & immediately unlock it again
  4. Observe loading spinner never stops until scrolling

### Actual result: 

https://github.com/brave/brave-ios/assets/5314553/fbb380f7-bdda-4526-9b69-d701bf7ee7a6

### Expected result:

Loading indicator is eventually removed after discovery completes

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.52 (23.6.1.16)
- Verified steps from [#7434](https://github.com/brave/brave-ios/pull/7434)
- Verified asset loading indicator is not shown every time wallet is locked and unlocked

iPhone 7+ (iOS 15.4.8) | iPhone 13 (iOS 16.5) | iPad Pro (iOS 16.6 Beta)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/5cc261bf-a751-44de-ac1c-9064b60dafff> | <video src=https://github.com/brave/brave-ios/assets/17010094/4968ceeb-6b5b-4edf-8c78-338981eb2fe4> | <video src=https://github.com/brave/brave-ios/assets/17010094/fab08743-cdcb-422c-b747-6ce76aa4f0e3>
