### ISSUE TITLE
Typo in localization key - "HistortMenuItem"

### ISSUE THREAD

**Issue by jlerner** [brave/brave-ios#7435]
### Description: 
There's a typo in the localization key "HistortMenuItem".

### Steps to Reproduce 
  1. See localization files, such as BraveStrings.swift.

### Actual result: 
Not a UI issue.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jlerner** [comment]
I have a fix but haven't yet figured out how to push a branch.

**Comment by iccub** [comment]
You can try this guide
https://docs.github.com/en/get-started/quickstart/contributing-to-projects
