### ISSUE TITLE
Wallet: Auto-discovery of assets resets the visible assets pref

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#7443]
iOS version of https://github.com/brave/brave-browser/issues/28749

**Comment by srirambv** [comment]
Verification passed iPhone 7 with iOS 15.7.3 running 1.53 (23.7.6.16)
- Verified steps from [#7534](https://github.com/brave/brave-ios/pull/7534)
- Verified disabling a token from visible list and importing a new account to trigger auto-discover doesn't add the disabled token to visible list
- Verified NFTs from the imported account shows up correctly
- Verified hiding an NFT doesn't come back to NFT grid when browser is restarted
----------
Verification passed iPhone 13 with iOS 16.5 running 1.53 (23.7.6.16)
- Verified steps from [#7534](https://github.com/brave/brave-ios/pull/7534)
- Verified disabling a token from visible list and importing a new account to trigger auto-discover doesn't add the disabled token to visible list
- Verified NFTs from the imported account shows up correctly
- Verified hiding an NFT doesn't come back to NFT grid when browser is restarted
----------
Verification passed iPad Pro with iOS 16.6 Beta running 1.53 (23.7.6.16)
- Verified steps from [#7534](https://github.com/brave/brave-ios/pull/7534)
- Verified disabling a token from visible list and importing a new account to trigger auto-discover doesn't add the disabled token to visible list
- Verified NFTs from the imported account shows up correctly
- Verified hiding an NFT doesn't come back to NFT grid when browser is restarted
