### ISSUE TITLE
[Follow up to #7432] An Infinite loading spinner is shown next to toggle switch when enabling VPN

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#7448]
### Description: 

Follow-up to #7432

### Steps to Reproduce 
  1. Launch Brave > Three Dot Menu
  2. Enable VPN
  3. Don't close the panel > Observe

### Actual result: 

An infinite loading spinner is shown next to the toggle switch when enabling VPN via the pop-up menu. If you close and reopen that menu, the loading spinner is not there anymore.

NOTE: This issue is not reproducible with 1.52

https://github.com/brave/brave-ios/assets/128532965/e816cae1-8baa-4fb3-920c-56ea9f2fc40f

### Expected result:

When enabling VPN, infinite loading spinner must not be shown

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes, with the latest 1.51
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 

iPhone 14 [iOS 16.4.1]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by soner-yuksel** [comment]
@vlad-hoff I cant reproduce this, did you try reproducing it with latest 1.51 (23..5.11.22)

**Comment by soner-yuksel** [comment]
@vlad-hoff I retested using 2 devices both latest 1.51 an d 1.52. Both is not having this particular problem. Please can you take a look again.
cc @iccub Can you also try when you have a chance ?

**Comment by hffvld** [comment]
Hi @soner-yuksel I'm sorry for the delayed reply. I just tried to install the latest 1.51.1 (23.5.19.19) build, and the issue is still reproducible.

https://github.com/brave/brave-ios/assets/128532965/5ff0eea2-7df9-49fc-aa09-07f7f605fc5b

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5]
Version 1.52 (23.6.14.13)
BraveCore 1.52.125 (114.0.5735.110)
```

Filed follow-up issue #7606

---------------------------

**STEPS:**
1. Launch Brave > Three-dot Menu > Brave VPN
2. Purchase VPN (for TF) and install certificate
3. Three-dot Menu > Enable/Disable `Brave VPN` > Verify

**ACTUAL RESULTS:**
- Verified that enabling or disabling `Brave VPN` from the main menu is not showing infinite loading spinner anymore
- Verified that the same infinite loading spinner is not shown when enabling/disabling VPN from `Brave Firewall + VPN` menu


https://github.com/brave/brave-ios/assets/128532965/94be60b2-0ac5-4f76-8f66-77d4d15f7a85
