### ISSUE TITLE
[Follow up to #7432] VPN Region country flag is not shown when relaunching Brave

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#7449]
### Description: 

Follow-up to #7432

### Steps to Reproduce 
  1. Launch Brave > Eanble VPN
  2. In VPN Region change location to another country> In the menu on NTP check country and flag are shown
  3. Close and relaunch Brave > Open menu on NTP > Check country and flag 

### Actual result: 

When VPN is enabled and the user is closing and reopening Brave, the country's flag is not shown anymore

https://github.com/brave/brave-ios/assets/128532965/e4c16419-7c4c-467c-94e3-a4257dea6ae1

### Expected result:

The flag for the enabled county in the VPN settings must be shown

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Version: 1.51 (23.5.11.22)
BraveCore: 1.51.114 (113.0.5672.92)

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 

iPhone 14 [iOS 16.4.1]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
It is a timing issue. At app launch it takes a bit of time to fetch available regions.
I think this is not a blocker but we will try to fix it, add a loading state to that screen perhaps

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using version `1.53 (23.7.6.16)`

- Verified STR in https://github.com/brave/brave-ios/issues/7449#issue-1707992688 and ensured that the country flag is shown after re-launching the Brave app.
- Verified flag is not reset when resetting configuration in the VPN settings

Example | Example
-|-
![IMG_3327 3](https://github.com/brave/brave-ios/assets/17885425/e55b523e-0967-46bc-a777-0bd9fff5a160) | ![IMG_3328 2](https://github.com/brave/brave-ios/assets/17885425/05556b2e-091b-4047-bf61-b86ec15aa756)
