### ISSUE TITLE
Transaction lists may open block explorer with incorrect url

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7455]
### Description: 

Transactions lists in Wallet no longer are limited to the selected network only, but in a few cases we are using selected network to build the block explorer URLs.

This applies to:
- Transactions List view (shown from Wallet Panel). Only possible on v1.52+.
    - This list displays transactions from all networks (for that account) after [show transactions from all networks on Activity tab, Account details, Account Transactions List (from panel)](https://github.com/brave/brave-ios/pull/7441)
    - Issue location: [AccountTransactionListView](https://github.com/brave/brave-ios/blob/development/Sources/BraveWallet/Crypto/Accounts/AccountTransactionListView.swift#L46)
- Account Details.
    - Bug could occur if you have Solana selected, and open Ethereum account details with at least 1 transaction.
    - Additionally in v1.52+, this view displays transactions from all networks after [show transactions from all networks on Activity tab, Account details, Account Transactions List (from panel)](https://github.com/brave/brave-ios/pull/7441)
    - Issue location: [AccountActivityView](https://github.com/brave/brave-ios/blob/development/Sources/BraveWallet/Crypto/Accounts/Activity/AccountActivityView.swift#L124)
- Asset Detail view
    - Bug could occur if you have Solana selected, and open Asset Detail for a non-Solana token.
    - Issue location: [AssetDetailView](https://github.com/brave/brave-ios/blob/development/Sources/BraveWallet/Crypto/Asset%20Details/AssetDetailView.swift#L106)
- Transaction Details view: 
    - Bug could occur if you have a Solana network selected, and open transaction details for Ethereum network transaction.
    - Additionally in v1.52+, this is more likely to occur after [displaying pending transactions from all networks](https://github.com/brave/brave-ios/pull/7424) and [show transactions from all networks on Activity tab, Account details, Account Transactions List (from panel)](https://github.com/brave/brave-ios/pull/7441)
    - Issue location: [TransactionDetailsView](https://github.com/brave/brave-ios/blob/development/Sources/BraveWallet/Crypto/Transactions/TransactionDetailsView.swift#L64)
- Transaction Status view displayed after transaction is confirmed:
    - Bug could occur if you have a Solana network selected, and open transaction confirmation for Ethereum network transaction.
    - Additionally in v1.52+, this is more likely to occur after [displaying pending transactions from all networks](https://github.com/brave/brave-ios/pull/7424)
    - Issue location: [TransactionStatusView](https://github.com/brave/brave-ios/blob/development/Sources/BraveWallet/Crypto/Transaction%20Confirmations/TransactionStatusView.swift#L42)

### Steps to Reproduce 
  1. Create Transaction on Goerli and confirm it so it's on the blockchain
  2. Open Uniswap in a tab
  3. Change network to any other Ethereum network
  4. Open Transactions list
  5. Tap and hold to open context menu and open on blockchain explorer
  6. Observe incorrect blockchain explorer used

### Actual result: 

https://github.com/brave/brave-ios/assets/5314553/a9497796-c00c-4c0f-bf41-f0795596906f

### Expected result:

Goerli blockchain explorer url is used

### Reproduces how often: 

Easily reproduced

### Brave Version: 

Only applicable to Brave iOS versions created May 15th 2023 or later.

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 16.5 running 1.52 (23.6.1.16)
- Verified steps from issue description and [ #7456](https://github.com/brave/brave-ios/pull/7456)
- Verified correct block explorer link is opened irrespective of which network is set as active
- Verified transaction list from panel loads the correct block explorer
- Verified transaction from the account page loads the correct block explorer irrespective of which is set as active
- Verified add token screen links to the correct token page


<video src=https://github.com/brave/brave-ios/assets/17010094/398bd8e7-1610-4bd3-8c01-da1b7e677e31> | <video src=https://github.com/brave/brave-ios/assets/17010094/25e46ebb-8900-43aa-a4e7-c33d85a7f5ad>
-- | --
