### ISSUE TITLE
[Playlist] Play/Pause button is not updated when collapsing and reopening Brave

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#7459]
### Description: 

Play/Pause button is not updated when collapsing and reopening Brave

### Steps to Reproduce 
  1. Launch Brave > Go to music.youtube.com and add a song to a Playlist by tapping an icon on URL bar, for example
  2. Open settings > Make sure `Enable Background Audio` is OFF
  3. Open Playlist from the menu > Observe `Pause` button is shown
  4. Collapse Brave > Notice that music stopped playing
  5. Reopen Brave > Observe `Pause` button and no music playing

### Actual result: 

`Pause` button is shown instead of a `Play` button when music was playing and the user collapsed and then reopened Brave (`Enable Background Audio` is OFF).

https://github.com/brave/brave-ios/assets/128532965/3ff091ad-53c4-4e17-be85-9d9cff9dc78e

### Expected result:

When Brave collapsed/reopened, `Play` button must be shown if `Enable Background Audio` is OFF

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.51 (23.5.15.14)
BraveCore: 1.51.114 (113.0.5672.92)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 

iPhone 14 [iOS 16.4.1]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Brandon-T** [comment]
This should already be fixed.

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.2
Brave build: 1.62 (24.1.9.23)
BraveCore: 1.62.128 (120.0.6099.144)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-ios/issues/7459#issue-1711082034

**ACTUAL RESULTS:**
- Verified that audio and video added to the playlist continue playing when hiding Brave or locking the phone
- Verified that `Play` / `Pause` button is shown according to the audio/video file status

---------------------------

https://github.com/brave/brave-ios/assets/128532965/e16b6b80-92a3-43dc-9eb8-44dce31b10c1
