### ISSUE TITLE
Emit accountsChanged event args as an array

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7463]
### Description: 

`accountsChanged` ethereum DApp event is emitting the first allowed account as a string instead of an array containing the first allowed account. Additionally we should emit empty array instead of empty string when not accounts allowed.

[Provider documentation](https://docs.metamask.io/wallet/reference/provider-api/#accountschanged), [Core `accountsChanged` event to align with](https://github.com/brave/brave-core/blob/master/components/brave_wallet/renderer/js_ethereum_provider.cc#L622-L633)

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 16.5 running 1.52 (23.5.26.15)
- Verified steps from [#7483](https://github.com/brave/brave-ios/pull/7483)
- Verified switching account updates the account details on the Dapp correctly 
- Verified on both Brave Web3 Talk and Uniswap

Brave Talk | Uniswap
-- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/8b5f3858-2de9-4939-9824-1503a1329622> | <video src=https://github.com/brave/brave-ios/assets/17010094/0ee96c9c-f633-4c03-80a4-5e0ba588b722>
