### ISSUE TITLE
App crashes when attempting to migrate a legacy wallet

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#7464]
### Description: 

In 1.52.x we moved some of the Ledger code on the core side to use mojo, which surfaced an issue with the current legacy wallet migration code and possible threading problems

### Steps to Reproduce 
  1. On 1.51 and lower: Enable rewards, then go to Rewards Debug settings and tap on "Create Legacy Wallet"
  2. Update to 1.52
  3. Launch and observe crash

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5] 
Version: 1.52 (23.6.22.18)
BraveCore: 1.52.125 (114.0.5735.110)
```
---------------------------

**STEPS:**
1. On 1.51 and lower: Enable rewards, then go to Rewards Debug settings and tap on `Create Legacy Wallet`
2. Update to 1.52
3. Launch and Verify

**ACTUAL RESULTS:**
- Verified that Brave is not crashing

---------------------------

https://github.com/brave/brave-ios/assets/128532965/ad54a9b7-424d-471b-af34-3549522f0000
