### ISSUE TITLE
Playlist issues

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#7466]
### Description: 

User reported a few issues with Playlist

```
A few current bugs with the iOS playlist. Note, 2x speed is used in all circumstances.

1. Locking screen causes video to pause

2. Unpausing video causes it to start playing again, but many times at 1.5x (still says 2x though)

3. Manually have to advance playlist
```

https://twitter.com/vac93302099/status/1658259870750236672?s=20

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5] and iPad Air [iPadOS 16.4.1]
Version 1.52 (23.6.14.13)
BraveCore 1.52.125 (114.0.5735.110)
```

---------------------------

**STEPS:**
1. Launch Brave > Go to www.youtube.com
2. Add some videos to Playlist by tapping a thumbnail in a search bar
3. Three-dot menu > Playlist 
4. Play a video > Change the speed to 1.5x > Lock device > Verify
5. Go back to Playlist and change the playback speed to 2x > Lock device > Verify

**ACTUAL RESULTS:**
- Verified that video from Playlist is keep playing while device is locked
- Verified that video is playing on 1x, 1.5x and 2x speed while device is locked
- Verified video is playing when Brave is minimized

https://github.com/brave/brave-ios/assets/128532965/9e8dd44a-18b3-4291-a7ca-9107a9e0f371
