### ISSUE TITLE
Update NTP images

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#7467]
### Description: 
Please update the new NTP images

@aguscruiz can you please provide the images for iOS

Slack: https://bravesoftware.slack.com/archives/C07HD31EZ/p1684269417070739

**Comment by aguscruiz** [comment]
@petemill was working on optimizing them. He would have the latest version of them 👍

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using version `1.53 (23.7.6.16)`

- Verified NTP images are updated
- Verified disabling background images in the settings will not display them on NTP
- Verified NTP images are on rotation and SI are displayed every 4th tab

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_3320 2](https://github.com/brave/brave-ios/assets/17885425/dacef0a1-54c3-4f84-9444-c2982bf9fb09) | ![IMG_3321 2](https://github.com/brave/brave-ios/assets/17885425/3fbd91b2-748a-40c8-98a6-30e77191dcdf) | ![IMG_3323 2](https://github.com/brave/brave-ios/assets/17885425/f6973e13-b3ca-4edc-9269-4b595c9590c7) | ![IMG_3324 2](https://github.com/brave/brave-ios/assets/17885425/7fe3b399-7662-43e2-801d-9b6798e52558) | ![IMG_3325 2](https://github.com/brave/brave-ios/assets/17885425/bf84eb12-81e8-4e68-ac21-3ad8954f2bf5)
