### ISSUE TITLE
QR Code Scanning erroneously  hides Scrollin Tabs Bar

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#7476]
### Description: 

If Scrolling Tab Bar is enabled and QR code scanning is used from URL Bar, after canceling the QR Code Scan the Tabs Bar disappear for the current tab.

### Steps to Reproduce 
  1. Enable Tabs Bar
  2. Create new tab
  3. Activate the URL bar entry
  4. Press QR code button
  5. Close QR Code button with done
  6. Check scrolling tab bar is disappeared

### Actual result: 

Tabs Bar disappeared for that particular Tab

https://github.com/brave/brave-ios/assets/6643505/8308489b-da92-4804-9e19-14723435e10c

### Expected result:

Tab Bar should never disappear with usage of QR Code Scan

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily Reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? Y

### Device details: 
Any iPhone

### Website problems only:
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5] and iPad Air [iPadOS 16.4.1]
Version 1.52 (23.6.14.13)
BraveCore 1.52.125 (114.0.5735.110)
```
---------------------------

**STEPS:**
1. Launch Brave > Thre-dot Menu > Settings
2. Scroll down and find `Tabs Bar` > Set to `On`
3. Go back and open a few tabs
4. Tap in the URL search bar > Delete URL
5. Tap on QR Code thumbnail > When opened, tap Done > Verify

**ACTUAL RESULTS:**
- Verified that the scrollable Tab Bar is not disappeared when closing QR code scanner

https://github.com/brave/brave-ios/assets/128532965/b2943c7b-406d-4d6c-b162-35e3a6756081

https://github.com/brave/brave-ios/assets/128532965/94842bcd-7a19-4f9e-ad0b-4b5e8d2c94ce
