### ISSUE TITLE
[Feature] Blocklist for Safari

### ISSUE THREAD

**Issue by ghost** [brave/brave-ios#7478]
## Problem Description
Like you must know some apps totally ignore default browser and open safari right away, witch bypass all your privacy protection and worse the ads/tracker blocker.

## Feature Overview
The feature is to provide something similar to firefox foccus, aka provide some blocklist (maybe used in brave) to safari as well like this when app ignore you the user remain "somewat" protected (even if of course it will be less than i user the brave app directly)

## Design
No Idea

## Implementation Details 
No Idea

## User Experience 

1. Enable the feature in brave
2. Go to "Safari adblock" settings
3. Be sure to tell user that if they not use brave the list will not be updated properly.

### Additional information
Until Apple fix the fact that apps can ignore user's browser settings this feature can help to protect your user even in the case of the dev who purposefully try to avoid your protection.

**Comment by iccub** [comment]
The product team has decided there's no plans for a standalone blocklist app, closing this ticket for now
