### ISSUE TITLE
Login List View Background Color Issue

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#7481]
### Description: 

The Background color in LoginList Controller is glitching under disclosure view when user is in dark mode

### Steps to Reproduce 
  1. Open Logins & Passwords
  2. Check faulty background

### Actual result: 

![xxcxx1](https://github.com/brave/brave-ios/assets/6643505/8797de10-76c6-4d61-8d42-c5d29cedf7f3)

### Expected result:

Background should be using bravebackground

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
Any

### Website problems only:
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5]
Version: 1.52 (23.6.1.16)
BraveCore: 1.52.117 (114.0.5735.90)
```
---------------------------

**PRECONDITIONS:**
- Make sure that some login credentials are already saved in Brave

**STEPS:**
1. Launch Brave > Three-dot Menu
2. Settings > Logins & Passwords > Verify

**ACTUAL RESULTS:**
- Verified that the background on `Logins & Passwords` screen is using brave background for saved credentials 

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/843ca3d8-717f-4b48-91d5-e7fe445926fb) | ![2](https://github.com/brave/brave-ios/assets/128532965/3fc57e1b-736a-43ed-be88-32d4de6da399) | ![3](https://github.com/brave/brave-ios/assets/128532965/c9bad6f4-22d9-4709-9677-434bd7aeaed2) | ![4](https://github.com/brave/brave-ios/assets/128532965/12418ba9-7af8-453a-8add-5c8c4c2b7f17) |
