### ISSUE TITLE
Opening playlist pauses the video at beginning, audio continues in background [intermittent]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#7485]
### Description: 
Opening playlist pauses the video, audio continues in background

### Steps to Reproduce 
  1. Fresh install 1.51
  2. Navigate to youtube.com
  3. Click to play video
  4. Add video to playlist and open playlist when page loads
  5. Observe playback
  6. Keep repeating until issue occurs

### Actual result: 

https://github.com/brave/brave-ios/assets/17885425/2c9ca1d3-b3fd-4773-aada-cd4c8960efef

### Expected result:
Playback should not pause

### Reproduces how often: [Easily reproduced, Intermittent Issue]
5-10% repro rate (iOS 16.3.1)

### Brave Version:  1.51 (23.5.16.16)

- Can you reproduce this issue with the most recent build from TestFlight? TBD
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? TBD

### Device details: 
iPhone 12, iOS 16.3.1 - reproducible

### Additional Information
Very intermittent

**Comment by Brandon-T** [comment]
I debugged this.
Turns out, Playlist is NOT actually pausing the audio; Youtube is.

Whenever anything "covers" the entire screen, Youtube is checking the page's `visibilitystate` observer and pausing the audio themselves.

So this is a bug on youtube itself, and not playlist. Not sure if I can do anything about it tbh.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12 Pro` running `iOS 17.1.1` using version `1.62 (24.1.9.23)`

- Confirmed this is no longer reproducible on fresh install as well as upgraded profile. 
- Ensured that videos can be added on YouTube to Playlist successfully and are not paused when opening them in Playlist.

https://github.com/brave/brave-ios/assets/17885425/cc4db72e-7a03-4d54-94c5-4920bf7cfae3
