### ISSUE TITLE
[Security] - Internal #915

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-ios#7491]
### Description: 
https://github.com/brave/internal/issues/915

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5] 
Version: 1.52 (23.6.9.13)
BraveCore: 1.52.117 (114.0.5735.90)
```

---------------------------

**STEPS:**
1. Launch Brave
2. Three-dot Menu > Wallet
3. Create a new wallet and stop when on `Your recovery phrase` screen
4. Use device gesture to bring up all opened apps > Verify
5. Connect the device to the computer and launch QuickTime player 
6. Share device screen > Verify

**ACTUAL RESULTS:**
- Verified that all n-words have the same blurring box length

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/1b96588c-75df-4f92-8c57-47f0cef69348) | ![2](https://github.com/brave/brave-ios/assets/128532965/9e9e0262-ec6d-45e3-896c-f666703c1d31) | ![3](https://github.com/brave/brave-ios/assets/128532965/5a4f46fc-90df-4588-b51f-b656dd13224b) |
