### ISSUE TITLE
Deleting Sync Chain from Tab Tray should update Open Session Screen properly

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#7493]
### Steps to Reproduce 
  1. Join a Sync Chain
  2. Open Tab Tray
  3. Switch to Open Session Segment
  4. Open Sync Settings from that screen
  5. Delete the sync chain 

### Actual result: 

The screen is not being dismissed after sync chain is deleted

And even done button is pressed and screen dismisses, the status of the empty screen is not showing right.

### Expected result:

Setting screen should dismiss.
empty screen should suggest creating a chain.

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Everytime

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
Latest

### Website problems only:
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5] 
Version: 1.52 (23.6.9.13)
BraveCore: 1.52.117 (114.0.5735.90)
```
---------------------------
<details>
<summary> Delete Sync chain from Tab Tray - PASS </summary>

**PRECONDITIONS:**
Sync chain already set

**STEPS:**
1. Launch Brave  > Open Tab tray
2. Switch to `Tabs from Other Devices`
3. Enable tab syncing > Authenticate sign in
4. Delete Sync Account > Delete > Verify

**ACTUAL RESULTS:**
- Verified that deleting a sync chain is closing `Sync settings` screen
- Verified that the user sees `Start a sync chain` screen

https://github.com/brave/brave-ios/assets/128532965/f6fe49ae-3945-4eea-9ded-729941267a82

</details>

<details>
<summary> Delete Sync chain from Settings - PASS </summary>

**PRECONDITIONS:**
Sync chain already set

**STEPS:**
1. Launch Brave  > Three-dot Menu > Settings
2. Sync > Authenticate sign in
5. Delete Sync Account > Delete > Verify

**ACTUAL RESULTS:**
- Verified that deleting a sync chain is closing `Sync settings` screen
- Verified that the user transferred to the main Three-dot Menu screen

https://github.com/brave/brave-ios/assets/128532965/2edd10df-7261-465b-98d0-049f96afa967

</details>
