### ISSUE TITLE
Wallet: Remove the network label in `GetEncryptionPublicKeyRequest` and `DecryptRequest` request panel 

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#7495]
Since those requests have no difference for different chainId. we should remove the network info label in those request panel. 
<img width="468" alt="Screenshot 2023-05-19 at 1 06 37 PM" src="https://github.com/brave/brave-ios/assets/1187676/34855678-c700-45d7-aa78-a4c8bbf79cdb">

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.53 (23.7.6.16)
- Verified steps from [#7558](https://github.com/brave/brave-ios/pull/7558)
- Verified network name is not shown on Encryption request screen

iPhone 7+ (iO 15.7.3) | iPhone 13 (iOS 16.5) | iPad Pro (iOS 16.6 Beta)
-- | -- | --
<img width=300 src=https://github.com/brave/brave-ios/assets/17010094/8e322056-6afe-4e6a-b338-52d253634f6a> | <img width=250 src=https://github.com/brave/brave-ios/assets/17010094/18dba2c1-2378-4ea3-833e-26239c8eaded>| <img width=400 src=https://github.com/brave/brave-ios/assets/17010094/87266ba3-cc70-4d01-8d02-5c4ae6e6f350>
