### ISSUE TITLE
Rate app news card

### ISSUE THREAD

**Issue by timchilds** [brave/brave-ios#7497]
https://github.com/brave/internal/issues/1023

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5.1]
Brave build: 1.56 (23.7.19.18)
BraveCore: 1.56.6 (115.0.5790.90)
```

---------------------------

**STEPS:**
1. Fresh install Brave > Launch Brave 
2. Turn on Brave News
3. Close and relaunch Brave 4 times more (in total it will be 5th launch)
4. Scroll down and find `Liking Brave?` app rate card
5. Tap on `Brave app rate` news card > Verify
6. Uninstall Brave and then repeat Steps 1 - 4
7. Tap and hold `Brave app rate` news card > Tap `Hide` > Verify
8. Uninstall Brave and then repeat Steps 1 - 4
9. Tap and hold `Brave app rate` news card > Tap `Rate Brave` > Verify

**ACTUAL RESULTS:**
- Verified that `Brave app rate` news card is shown on a 5th app launch
- Verified that tapping on `Brave app rate` news card is transferring to App Store `Write a Review` page
- Verified when returning back to Brave from the App Store `Write a Review` page, `Brave app rate` news card is not shown again
- Verify, that the pop-up menu for `Brave app rate` news card is working and user can `Hide` or `Rate Brave` from there

---------------------------

|Dark Mode|Dark Mode|Light Mode|Light Mode|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/a98505cc-9973-4ed4-9847-f2df7408acb6) | ![2](https://github.com/brave/brave-ios/assets/128532965/e8fb5394-315a-467f-85a4-6371a0049e0b) | ![3](https://github.com/brave/brave-ios/assets/128532965/4cf127ad-cd68-45dc-adb0-6bf53647253e) | ![4](https://github.com/brave/brave-ios/assets/128532965/2a06be67-d807-487b-814f-8e700d04dfa1) |

https://github.com/brave/brave-ios/assets/128532965/834ba118-6a8e-4201-9499-fc26f5dce551
