### ISSUE TITLE
Preroll ads shown as black screen when disabling 'Ads Blocking' in shields

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#7501]
### Description: 
When Ads Blocking is disabled in shields panels, pre-roll ads will show black screen when playing. This does not happen when shields are disabled, the ads play/show normally.

Not a regression. Impacts 1.51, 1.51.1

### Steps to Reproduce 
  1. Install 1.51
  2. Wait a few mins after installing
  3. Open youtube.com
  4. Disable `Tracking & Ads Blocking` toggle in shields
  5. Play a popular video with ads
  6. Observe ad

### Actual result: 
![IMG_3220 2](https://github.com/brave/brave-ios/assets/17885425/31aea598-2981-443a-94c7-d526e9e450a8)

### Expected result:
![IMG_3240](https://github.com/brave/brave-ios/assets/17885425/a2d73c01-dc5c-4f5a-8333-7dc2a290ad88)

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

### Brave Version:  1.51.x

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
iPhone X, iOS 16.3.1

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5]
Version: 1.52 (23.6.1.16)
BraveCore: 1.52.117 (114.0.5735.90)
```
---------------------------

**STEPS:**
  1. Launch Brave
  2. Wait a few mins after installing
  3. Open youtube.com
  4. Brave Shields > Disable `Trackers & Ads Blocking` toggle 
  5. Play a popular video with ads > Verify

**ACTUAL RESULTS:**
- Verified that ads are shown when `Trackers & Ads Blocking` toggle is OFF

https://github.com/brave/brave-ios/assets/128532965/e9ae92c4-832d-4936-8efb-291a17b4d457
