### ISSUE TITLE
Add unit tests for cosmetic filtering and request blocking scripts

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#7502]
### Description: 
The following scripts need to be tested to make sure they are functioning properly:
- `SelectorsPollerScript.js`
- `RequestBlockingScript.js`

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5] and iPad Air [iPadOS 16.4.1]
Version: 1.52 (23.6.22.18)
BraveCore: 1.52.125 (114.0.5735.110)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Navigate to several websites > Verify 
3. Three-dot menu > Settings > Brave Shields & Privacy
4. Trackers & Ads Blocking > Set to `Disabled`
5. Navigate to several websites > Verify 
6. Three-dot menu > Settings > Brave Shields & Privacy
7. Block Cookie Consent Notices > Set to `OFF`
8. Navigate to several websites > Verify 

**ACTUAL RESULTS:**
- Verified that the Cosmetic Filtering script is hiding elements as expected.
- Verified by enabling/disabling `Trackers & Ads blocking`, `Block all Cookies`, `Block Cookie consent notices` and `Block Scripts`

---------------------------

**Trackers & Ads blocking**

https://github.com/brave/brave-ios/assets/128532965/0eae6854-5fc0-44db-a348-15d689f32de4

### Block all Cookies and Block Cookie consent notices

https://github.com/brave/brave-ios/assets/128532965/2d99a646-d4d1-46f6-b6fd-73aff4246118

**Block Scripts**

https://github.com/brave/brave-ios/assets/128532965/628a4048-7bee-4dbd-8deb-27ecfbbe00b4
