### ISSUE TITLE
Wallet: Dismiss pending request panel will dismiss full screen wallet

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#7505]
If open a pending request panel on top of full screen wallet, the dismiss button will dismiss the request panel along with the full screen wallet. 
The dismiss button should only dismiss the request panel and let user stays in wallet.

https://github.com/brave/brave-ios/assets/1187676/6c8f1a83-07e6-449f-a04e-2664604b4c75

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.53 (23.7.6.16)
- Verified steps from [ #7557](https://github.com/brave/brave-ios/pull/7557)
- Verified dismissing pending request panel doesn't close the browser, only dismisses the request panel

iPhone 7+ (iOS 15.7.3) | iPhone 13 (iOS 16.5) | iPad Pro (iOS 16.6 Beta)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/f8aab2ae-110e-42c1-b9ef-c8c7d2fbd922> | <video src=https://github.com/brave/brave-ios/assets/17010094/9425f7ba-c2aa-4ae7-a15a-83a7cee15d35>  | <video src=https://github.com/brave/brave-ios/assets/17010094/2452a557-39b0-4aee-a15f-8539e7232f01>
