### ISSUE TITLE
Question: user agent recognition for Brave

### ISSUE THREAD

**Issue by bridzius** [brave/brave-ios#751]
### Description: 
Currently, brave for iOS has the user agent for "Firefox for iOS", which makes sense, since it uses it underneath. 
For example:
```
Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/1.7.1b18.12.19.01 Mobile/16D5032a Safari/605.1.15
```
Is this a feature of the fingerprinting protection and it is expected for websites to assume that the customer is using FxiOS instead of Brave?
Or are there plans to actually having a Brave-specific UA at some point in the future?

**Comment by jhreis** [comment]
Currently this is intentional to prevent fingerprinting of Brave users. Once Brave usage gets to a point where someone using Brave is relatively common then we plan to modify this. Android is currently scheduled to do this: https://github.com/brave/browser-android-tabs/issues/712

**Comment by jhreis** [comment]
Feel free to respond if you have followup questions, going to close for now though 😄
