### ISSUE TITLE
Search buttons are behind safe area when using hardware keyboard

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7514]
### Description: 

The alternate search engine quick action buttons are hidden behind the bottom safe area when a hardware keyboard is used.

### Steps to Reproduce 
Required: Device with a bottom safe area, ex. iPhone X, 11, 12, 13, 14
  1. Enable top toolbar (required) in settings
  2. Connect a hardware keyboard
  3. Tap URL bar
  4. Enter any character
  5. Observe search quick actions are in the safe area

### Actual result: 

![Simulator Screenshot - iPhone 13 Pro - 2023-05-25 at 10 40 30](https://github.com/brave/brave-ios/assets/5314553/00dea110-acd1-4e09-8f6d-046a31e15ed2)

### Expected result:

Buttons are above safe area

### Reproduces how often: 

Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

I don't have iPad on hand but simulator seems to show it not in the safe area on iPad

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5.1]
Brave build: 1.56 (23.7.13.16)
BraveCore: 1.56.5 (115.0.5790.75)
```
---------------------------

**STEPS:**
1. Launch Brave > Three-dot menu > Settings
2. Enable `Top Bar`
3. Connect physical keyboard to the device
4. NTP > Tap in serch bar
5. Type something with a physical keyboard > Verify

**ACTUAL RESULTS:**
- Verified that search quick actions are not covered by the safe area

---------------------------

|Top Bar|Bottom Bar|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/b4f5f525-6ae4-429e-8b98-039036718051) | ![2](https://github.com/brave/brave-ios/assets/128532965/7a8385d9-3d13-4eca-9c6f-dd384fba1272) |
