### ISSUE TITLE
Tabs not restored after closing private tab or toggling tab view [intermittent]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#7517]
### Description: 
Tabs not restored after closing private tab or toggling tab view

So far only reproduced on iPad using 1.51.1 but its very intermittent (have not tried earlier versions alot)

In the repro steps I have safe browsing disabled (dangerous sites blocking) and mode set to aggressive but this could be a coincidence as it usually happens after closing private tab and/or toggling tab view

### Steps to Reproduce 

**Note:** Intermittent issue, no exact repro steps at this time

  1. Install 1.51.1
  2. Set Ad blocking mode to `Aggressive`
  3. Disable `Block Dangerous Sites` in privacy settings
  4. Re-launch browser once
  5. Open some new tabs and load some web pages
  6. Open url in new private tab
  7. Open tab view, switch out of private mode
  8. Now toggle tab view in regular mode
  9. Try to load some tabs

### Actual result: 
Some tabs appear white, fail to restore, **page refresh does not work, have to close tab**

https://github.com/brave/brave-ios/assets/17885425/ea2d3293-007b-415a-8e1d-b4b9f959773a

### Expected result:
Tabs should be restored

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Intermittent

### Brave Version:  1.51.1 

- Can you reproduce this issue with the most recent build from TestFlight? TBD
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? TBD

### Device details: 
iPad (9th Gen), iPadOS 15.6.1

### Website problems only:
- did you check with Brave Shields down? Ad blocking set to aggressive in gobals, dangerous sites blocking disabled
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by hffvld** [comment]
Verified on `iPad Air` using version(s):
```
Device/OS: iPad Air [iPadOS 16.4.1]
Version: 1.52 (23.6.28.13)
BraveCore: 1.52.129 (114.0.5735.198)
```
---------------------------

**STEPS:**
  1. Launch Brave < Three-dot menu > Settings > Brave Shields & Privacy
  2. Trackers & Ads Blocking >  Set to `Aggressive`
  3. Scroll down > Disable `Block Dangerous Sites`
  4. Re-launch the browser once
  5. Open some new tabs and load some web pages
  6. Open URL in new Private tab
  7. Open tab view, switch out of Private mode
  8. Now toggle tab view in regular mode
  9. Try to load some tabs

**ACTUAL RESULTS:**
- Verified that all tabs/pages in a Regular tab mode can be opened as usual and no black page is shown

---------------------------

https://github.com/brave/brave-ios/assets/128532965/d4ddd302-ae38-45c2-a428-555baa10d1e4
