### ISSUE TITLE
HTTPSE doesn't work when updating from previous version

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#752]
Due to the fact that the HTTPSE content blocker is cached by WebKit

### Steps to Reproduce 
  1. Install previous version (1.7.1) and launch the application at least once (to point where url bar is active)
  2. Upgrading to 1.7.2 (19.1.17.16)
  3. Visit https://badssl.com and loading https://https-everywhere.badssl.com/

**Actual result:** Fails to upgrade links to https
**Expected result:** https-everywhere.badssl.com should show HTTPSE working
**Reproduces how often:** Likely always
**Brave Version:** 1.7.2 (19.1.17.16)

**Comment by srirambv** [comment]
Verification passed on iPhone 6 running  1.7.2(19.1.18.15)
