### ISSUE TITLE
Select Token to Send view

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7523]
### Description: 

Create a single view to allow selecting an account and asset at the same time similar to brave://wallet/send.

<img width="490" alt="Select Token to Send" src="https://github.com/brave/brave-ios/assets/5314553/940e17b9-128f-496e-973c-4c9fc3427276">

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.56 (23.7.19.18)
- Verified steps from [#7576](https://github.com/brave/brave-ios/pull/7576)
- Verified all accounts are listed when select token is shown
- Verified able to filter tokens based on network and shows all accounts from selected networks
- Verified able to view tokens with zero balance
- Verified selecting a token shows the correct account address
- Verified selecting an NFT shows correct account address and balance

iPhone 7+ (iOS 15.7.3) | iPhone 13 (iOS 16.5) | iPad Pro (iOS 16.6 Beta)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/c0b45b7b-2247-43c4-95f7-671baea8a182> | <video src=https://github.com/brave/brave-ios/assets/17010094/dca60c5b-9f6c-4a8e-825e-fc96cbe270b8> | <video src=https://github.com/brave/brave-ios/assets/17010094/f85a29b6-198f-4a09-9f50-48666c199a26>
