### ISSUE TITLE
Playlist Revamp - Onboarding

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#7526]
### Description: 

Replace the Playlist Onboarding with the new revamped version (see Figma)

**Comment by Uni-verse** [comment]
Verified on the following devices using build version `1.53 (23.6.23.14)
`
```
iPhone X, running iOS 16.5.1,
iPhone XR running iOS 15.5
iPad (9th Gen) running iPadOS 15.6.1

```
- Ensured onboarding popup is activated on initial launch when loading a webpage with media.
- Ensured user is able to successfully complete the flow on new profile & upgraded profile. https://github.com/brave/brave-ios/issues/7671
- Ensured user is able to dismiss the popup at any stage of the flow. https://github.com/brave/brave-ios/issues/7663
- Ensured user is able to add media early in the flow (before prompting to in the flow).
- Ensured onboarding popup is shown up to 2 times. 
- Ensured onboarding popup is displayed on different media sites on initial launch.

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_3293](https://github.com/brave/brave-ios/assets/17885425/034c2799-4611-41ba-b2ba-de3938128002) | ![IMG_3294](https://github.com/brave/brave-ios/assets/17885425/164392e5-7a62-485d-badd-a0ac9006c68f) | ![IMG_3302](https://github.com/brave/brave-ios/assets/17885425/2e10a702-24b3-4ab4-80a6-ce01732a2d3b) | ![IMG_3295](https://github.com/brave/brave-ios/assets/17885425/dc49e586-b8f2-4749-8220-4e560c487d98) | ![IMG_3296](https://github.com/brave/brave-ios/assets/17885425/f2699f47-0100-4e26-b638-99efd393f9b0)


Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_0277 3](https://github.com/brave/brave-ios/assets/17885425/4f14eb25-2a8f-4618-b8ff-85637a4d05cd) | ![IMG_0278 3](https://github.com/brave/brave-ios/assets/17885425/ec319508-165f-4ccd-9592-dded649c98ec) | ![IMG_0279 3](https://github.com/brave/brave-ios/assets/17885425/f90c0324-9c4f-4a92-843c-afc04ee7632e) | ![IMG_0280 2](https://github.com/brave/brave-ios/assets/17885425/95e71b08-774b-464e-bf0c-54c2481ec8fe) | ![IMG_0281 2](https://github.com/brave/brave-ios/assets/17885425/32150d69-8233-4653-9c4f-43d5ad6b4f93)
