### ISSUE TITLE
Reader mode in Hebrew language incorrect showing content

### ISSUE THREAD

**Issue by ilyak83** [brave/brave-ios#7532]
![Screenshot_1](https://github.com/brave/brave-ios/assets/37582972/a45a02ea-3487-47de-a19f-b38372494c62)
When enabling the reader mode for Hebrew content all the text shift form left to right instead form right to left.
Please see the attached screenshot - on the left side its correct original view and on the right side is incorrect view.

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5.1]
Brave build: 1.56 (23.7.13.16)
BraveCore: 1.56.5 (115.0.5790.75)
```
---------------------------

**STEPS:**
1. Launch Brave
2. Open RTL website, for example [Hebrew](https://hebrewnews.com/article/55513) or [Arabic](https://ar.timesofisrael.com/%d8%ba%d8%a7%d9%84%d8%a7%d9%86%d8%aa-%d9%8a%d8%a3%d9%85%d8%b1-%d8%a8%d8%a7%d8%ad%d8%aa%d8%ac%d8%a7%d8%b2-4-%d8%a5%d8%b3%d8%b1%d8%a7%d8%a6%d9%8a%d9%84%d9%8a%d9%8a%d9%86-%d8%af%d9%88%d9%86-%d8%aa%d9%87/)
3. Enable `Reader Mode` > Verify

**ACTUAL RESULTS:**
- Verified that RTL websites are shown correctly in `Reader Mode`

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/60007190-27d0-4a06-a11b-5a0508a63d70) | ![2](https://github.com/brave/brave-ios/assets/128532965/4301c9ff-a678-4363-956b-42e693514ac1) | ![3](https://github.com/brave/brave-ios/assets/128532965/ec46cd1c-8fa6-4af9-a17a-c350586a69c9) | ![4](https://github.com/brave/brave-ios/assets/128532965/7164439e-35cf-4705-9d6b-3a45f3fbcd1d) |
