### ISSUE TITLE
Playlist sometimes shows small audio files on youtube

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#7537]
### Description: 
- Sometimes on Youtube playlist adds a small 3s audio file

### Steps to Reproduce 
Visit youtube
1. Playlist shows in the URL bar
2. Add the item to playlist

### Actual result: 
- The item is added as a small 3s audio file.

### Expected result:
- Should not add audio only on Youtube.

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily reproduced

### Brave Version: 
- 1.48.x

### Device details: 
- Any

### Website problems only:
- Yes

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5]
Version: 1.52 (23.6.1.16)
BraveCore: 1.52.117 (114.0.5735.90)
```
---------------------------

**STEPS:**
1. Launch Brave
2. Open youtube.com
3. Add video/audio to the Playlist
4. Open Playlist > Play added videos/audios > Verify

**ACTUAL RESULTS:**
- Verified that only actual video/audio files were added to the playlist
- Verified that a small 3 sec audio file is not added to the playlist

https://github.com/brave/brave-ios/assets/128532965/9c8b95aa-1b11-4ee1-8f50-a74358ea4861
