### ISSUE TITLE
Add network level standard mode

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#7539]
### Description: 
We are only handling aggressive/standard for cosmetic filtering. This is a gap in the functionality. We need to update the code to also handle network level standard blocking

### Test plan
1. Test content blockers here: https://test-pages.privacytests.org/tracking_content.html
2. Ensure blocked count is 19 on the above page.
3. Test scriplets here: https://dev-pages.brave.software/filtering/scriptlets.html

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iPadOS 16.3.1` using version `1.57 (23.9.4.13)`

- Verified test plan in https://github.com/brave/brave-ios/issues/7539#issue-1731981696

Example | Example
-|-
![IMG_1213](https://github.com/brave/brave-ios/assets/17885425/fc8946b9-da85-4f59-800d-1a8fbeccd47a) | ![IMG_1214](https://github.com/brave/brave-ios/assets/17885425/69ac5fc6-081d-482b-b983-2c9b3d179ae6)
