### ISSUE TITLE
Domain is not shown on NFT details screen

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#7543]
### Description: 
Domain is not shown on NFT details screen

### Steps to Reproduce 
  1. Import a wallet that has a UD domain NFT
  2. Open NFT detail screen
  3. `.CRYPTO` is not visible on the UD NFT

### Actual result: 
<img width=300 src=https://github.com/brave/brave-ios/assets/17010094/b786ad04-f7c6-4ed6-a3b3-4ffe323e61c5>

### Expected result:
Similar to Android
<img width=300 src=https://github.com/brave/brave-ios/assets/17010094/869e655d-7486-4563-a6f2-ed7024f449f2>

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 
iPhone 13 (iOS 16.5)

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by nuo-xu** [comment]
This is due to the limitation of rendering svg images on iOS. 
We do have a disclaimer at the bottom to let users understand svg maybe not exactly the same as the NFT image.
<img width="421" alt="Screenshot 2023-05-31 at 9 04 41 PM" src="https://github.com/brave/brave-ios/assets/1187676/7524a2a8-89de-4b10-b158-4ed70984c093">

**Comment by nuo-xu** [comment]
we have now change our svg renderer to be the one from chromium which should be able to render text in svg. in addition, we have the `The image rendered above may not exactly match the NFT` disclaimer at the bottom of the NFT details screen in case we have some problems rendering the svg correctly.
