### ISSUE TITLE
Wallet: NFT improvement on importing  

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#7556]
Some users from the community gave us some feedback that it's a bit hard to import NFTs in our Wallet. 
We agree that there is some improvement we can do on this topic. 

1. long press on each NFT grid to hide NFT
2. adding a `+` button in NFT tab for users to click which will open `Add custom asset` screen
3. In the `Add custom asset` screen, move token's contract address on top of the form like what desktop has.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.53 (23.7.6.16)
- Verified steps from issue description and [#7563](https://github.com/brave/brave-ios/pull/7563)
- Verified long press on NFT shows the hide button
- Verified able to hide and show NFTs
- Verified clicking on `+` on NFT tab brings up the add custom token prompt
- Verified `Token Address` is set at the top of the add custom token on Add NFT screen

iPhone 7+ (iOS 15.7.3) | iPhone 13 (iOS 16.5) | iPad Pro (iOS 16.6 Beta)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/0c678cf6-6c5b-4dff-92d6-93d6d8f593ed> | <video src=https://github.com/brave/brave-ios/assets/17010094/80d204f5-3120-4436-a8f4-4dcb8369e231> | <video src=https://github.com/brave/brave-ios/assets/17010094/0e8564df-0009-4a3a-90d2-6000ff348a4c>
