### ISSUE TITLE
Enable Brave Talk x Jitsi SDK integration on release builds

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#7560]
### Description: 

Security issue closed last week: https://github.com/brave/security/issues/894

So this can now be enabled on Release builds

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using version `1.56 (23.7.25.16)`

Test Plan: https://github.com/brave/brave-ios/pull/7561#issue-1738558204

- Verified Native Brave Talk is enabled on release builds
- Verified user is able to join the brave talk meeting

Example | Example | Example | Example
-|-|-|-
![IMG_3375](https://github.com/brave/brave-ios/assets/17885425/ce780f06-45c4-4f1a-be9d-705aef8ecf35) | ![IMG_3376](https://github.com/brave/brave-ios/assets/17885425/2ae3fb0b-ab57-408d-91aa-0face605daed) | ![IMG_3377](https://github.com/brave/brave-ios/assets/17885425/8630b89c-e76f-4100-9a09-879f5434ad26) | ![IMG_3378](https://github.com/brave/brave-ios/assets/17885425/9d121438-c41e-41fe-8363-3429526f44bf)
