### ISSUE TITLE
Add support for multi-window

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#7574]
## Problem Description 
- Add support for Multi-Window on iPad

## Feature Overview 
- The browser should be able to have multiple windows side by side. For example, Safari allows it.
- You should have private and regular modes side by side if the user wishes.
- Should have a button to open multiple windows.
- Optionally should allow dragging a tab from one window to another.
- Optionally should allow merging one window with another.

**Comment by Uni-verse** [comment]
**Verified** on `iPad (7th Gen)` running `iPadOS 16.5.1` using version `1.57 (23.8.28.18)`

<details><summary>Settings Menu (Private Tabs) </summary>

- Ensured that Private Tabs menu is shown for normal and private tabs but not in PBM.

Example | Example
-|-
![IMG_1155](https://github.com/brave/brave-ios/assets/17885425/ecc66cf4-b2ac-4c6e-b725-9ed16080bb8d) | ![IMG_1161](https://github.com/brave/brave-ios/assets/17885425/3cb85e5f-1d0a-431d-96cd-bc10cf7ac522)

</details>

<details><summary>Actions / Context Menu</summary>

- Ensured that `Open in New Private Window` & `Open in New Window` appear in the context menu.
- Ensured that tab is opened in the appropriate window/mode when using the `Open in New Private Window` & `Open in New Window`.
- Ensured that new actions show up in context menu in private and normal tabs.

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_1146](https://github.com/brave/brave-ios/assets/17885425/f72367df-ff3b-4df1-ae32-770061f12883) | ![IMG_1147](https://github.com/brave/brave-ios/assets/17885425/0f4eaf7b-140f-4759-aaaa-1465e9b08833) | ![IMG_1148](https://github.com/brave/brave-ios/assets/17885425/1dfef6d4-2d2f-4888-9ad0-46501808bc38) | ![IMG_1134](https://github.com/brave/brave-ios/assets/17885425/4357a017-fc1f-4eae-a00f-1560719d5885) | ![IMG_1150](https://github.com/brave/brave-ios/assets/17885425/56ca9ae0-8dc1-4be2-9106-4e86f08aac75)

</details>

<details><summary>Menus / Icons / Onboarding in Windowed Mode</summary>

- Ensured Playlist, Brave Wallet, and Reader Mode icons are displayed in windowed mode.
- Ensured User is able to interact with icons in windowed mode.
- Ensured that onboarding pop-ups are shown while in split view.

Example | Example | Example | Example
-|-|-|-
![IMG_1165](https://github.com/brave/brave-ios/assets/17885425/2d7ad5aa-5117-4c5d-8c7d-1a821d11adb0) | ![IMG_1166](https://github.com/brave/brave-ios/assets/17885425/6f0c720e-7bce-4bbf-9027-99b0bd1054a1) | ![IMG_1167](https://github.com/brave/brave-ios/assets/17885425/f242bdd1-ee18-4766-849b-45ee8f628104) | ![IMG_1168](https://github.com/brave/brave-ios/assets/17885425/65d22687-86c1-424c-8230-d5b3721694e2)



Encountered: 
https://github.com/brave/brave-ios/issues/7976
https://github.com/brave/brave-ios/issues/7978

</details>

<details><summary>Screen Modes</summary>

- Ensured that user is able to the different Screen Modes while having multiple windows open.

Example | Example
-|-
![IMG_1142](https://github.com/brave/brave-ios/assets/17885425/82793075-8c08-47f8-a81b-2bf7645fce7d) | ![IMG_1149](https://github.com/brave/brave-ios/assets/17885425/79aa71b1-8b14-4832-b91a-d025c769fb79)

</details>

<details><summary>Windows View</summary>

- Ensured user is able to view all instances of brave when opening app or when using `Show All Windows` from the home screen context menu
- Ensured closing windows by swiping

Example | Example | Example | Example
-|-|-|-
![IMG_1164](https://github.com/brave/brave-ios/assets/17885425/187e259a-4340-4c47-9f99-8c3c04b4aa4a) | ![IMG_1140](https://github.com/brave/brave-ios/assets/17885425/b8385438-ca69-4c00-8bfa-93ac9ae41375) | ![IMG_1154](https://github.com/brave/brave-ios/assets/17885425/50a3159d-c89b-4ba9-88b3-d6e2a3c4a2d7) | ![IMG_1163](https://github.com/brave/brave-ios/assets/17885425/743ae32c-6be8-45dc-97ef-33e2c1918b93)

</details>

<details><summary>Existing Profile</summary>

- Ensured opening private tabs and private tab windows works on existing profile.
- Ensured entering split view modes works.
- Ensured opening new window for normal tabs works from the context menus.

</details>
