### ISSUE TITLE
Filecoin EVM Testnet shown in Secondary Networks list

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7583]
### Description: 

Filecoin EVM Testnet should be shown with the Goerli testnet and Sepolia testnet, not in the `Secondary Networks` list.

![IMG_9945](https://github.com/brave/brave-ios/assets/5314553/d6094f1c-8b21-453d-858c-abb478135bde)

https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1686161405273159

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.53 (23.7.6.16)
- Verified steps from [#7584](https://github.com/brave/brave-ios/pull/7584)
- Verified Filecoin EVM testnet is listed under test network along with other test networks
- Verified Filecoin EVM testnet is not listed under Secondary network

iPhone 7+ (iOS 15.7.3) | iPhone 13 (iOS 16.5) | iPad Pro (iOS 16.6)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/af7c104a-44f3-41d4-8aa5-d5b4d30086b4> | <video src=https://github.com/brave/brave-ios/assets/17010094/457e76dd-5a5c-4acc-8e7e-bbbe6cdecb49> | <video src=https://github.com/brave/brave-ios/assets/17010094/f012787e-7d19-492b-a2bb-c976150cd815>
