### ISSUE TITLE
Portfolio Filters and Display Settings

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7585]
### Description: 

Add a modal that contains filters and display settings for Portfolio (ideally re-usable with NFT / Activity tabs, etc.).

<img width="241" alt="Filters and Display Settings" src="https://github.com/brave/brave-ios/assets/5314553/744ac75d-a2d3-48f9-9153-f3da4a627099"> | <img width="261" alt="Filters and Display Settings" src="https://github.com/brave/brave-ios/assets/5314553/f74341c4-0caa-4ecb-9790-e51b4b465f94">
--|--

Group By (TBD, needs Portfolio v2 designs):
- Accounts
- Network
- None

Sort Assets:
- Price/fiat high -> low (default, current behaviour)
- Price/fiat low -> high
- A-Z
- Z-A

Hide assets with <$1 value toggle.

Network Filter(s):
- Checkmark/box beside each network, grouped by Primary/Secondary/Test networks. 
- Primary networks are shown, secondary & test networks hidden behind expandable arrow button.
- All networks selected by default, except test networks (current behaviour).

Accounts Filter:
- All accounts are selected by default

cc @kleantzogu @jamesmudgett @HEagle18

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.57 (23.8.23.20)
- Verified steps from [#7665](https://github.com/brave/brave-ios/pull/7665)
- Verified able to group assets by accounts or networks
- Verified able to sort asset based on balance High to low/low to high
- Verified able to sort asset in ascending (A to Z) or descending (Z to A)
- Verified able to hide tokens with < 0.5 balance
- Verified able to filter portfolio by specific account
- Verified able to filter portfolio by specific network
- Verified saved settings is retained between browser restarts
- Encountered  [#7942](https://github.com/brave/brave-ios/issues/7942), [#7943](https://github.com/brave/brave-browser/issues/36775), [#7944](https://github.com/brave/brave-ios/issues/7944), [#7945](https://github.com/brave/brave-ios/issues/7945), [#7946](https://github.com/brave/brave-ios/issues/7946)

iPhone 7+ (iOS 15.7.8) | iPhone 13 (iOS 16.6) | iPad Pro (iOS 16.6)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/4739cfad-ab27-43b9-a8c8-bb6a6ca38f08> | <video src=https://github.com/brave/brave-ios/assets/17010094/f4b98e4b-13ea-4c36-9ef6-b009d36d79fa> | <video src=https://github.com/brave/brave-ios/assets/17010094/87b2fb85-9962-4122-bb64-3bbdea4fca4e>
