### ISSUE TITLE
Edit visible assets is not visible on NFT tab when you hide an NFT from visible list

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#7591]
### Description: 
Edit visible assets is not visible on NFT tab when you hide an NFT from visible list

### Steps to Reproduce 
  1. Add an NFT to visible list
  2. Switch to NFT tab and click on edit visible asset and disable the NFT from visible list
  3. NFT tab now only shows Import NFT and only way to add it back is from portfolio page

### Actual result: 
Edit visible assets is not visible on NFT tab when you hide an NFT from visible list

### Expected result:
Maybe show the Edit visible asset button to show that Wallet already has an NFT but is not not set to visible 

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 
All

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps @HEagle18 @jamesmudgett @kleantzogu @minkyeongshin

**Comment by nuo-xu** [comment]
@srirambv I think we can close this issue since now NFT is inside Portfolio tab and the only way to edit visible assets is under Assets tab. it's the same behaviour as desktop.

**Comment by srirambv** [comment]
Issue is invalid. Closing the issue
