### ISSUE TITLE
Certificate Viewer some fields crop prematurely and not showing all information 

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#7603]
### Description: 

There is a problem with rendering sections on certificate view details. When Certificate Viewer is opened some field are not fully shown until the field is out of the view and back again in view

### Steps to Reproduce 
  1. Open a proper secure website like Wikipedia.org
  2. Scroll down to check if all fields are rendered properly
  3. Some long field like signature is now shown entirely

### Actual result: 

Fields are cropped

Uploading Simulator Screen Recording - iPhone 14 - 2023-06-15 at 11.55.04.mp4…

### Expected result:

Every detail be shown in full

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version:  AppStore 1.51.2

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 

Any iPhone

### Website problems only:
- did you check with Brave Shields down? N-A
- did you check in Safari/Firefox (WkWebView-based browsers)?  N-A

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using version `1.56 (23.7.19.18)`

- Verified all the information in each field is shown in certificate viewer
