### ISSUE TITLE
Allow Multiple Selection for Network Filters

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7607]
### Description: 

Update the existing network filter view to allow multiple networks to be selected for filtering (removing the `All Networks` option. This will later be integrated with https://github.com/brave/brave-ios/issues/7585 (pushed as a detail view).

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 16.5 running 1.56 (23.7.31.17)
- Verified steps from [#7617](https://github.com/brave/brave-ios/pull/7617)
- Verified network filter works as expected on portfolio tab
- Verified Test networks are not enabled on Portfolio, NFT tabs when test networks are enabled 
- Verified Test networks are enabled by default on Activity, Edit visible assets and Send token tabs
- Verified show/hide button enables/disables test networks when enabled

https://github.com/brave/brave-ios/assets/17010094/18098074-0135-4a13-9d87-79ebcb01659b
