### ISSUE TITLE
Turn Sardine on for all wallet users

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7608]
### Description: 

iOS version of https://github.com/brave/brave-browser/issues/30333 / https://github.com/brave/brave-browser/issues/31096

>Right now, Sardine is only turned on for US users. We want to turn it on for global wallet users now as well. They recently added global support for cards.
>
>link to discussion -> https://bravesoftware.slack.com/archives/C03FP409W2X/p1683817345044179

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 16.6 running 1.57 (23.8.23.20)
- Verified steps from [#7735](https://github.com/brave/brave-ios/pull/7735)
- Verified Sardine is shown as a provider for purchase of ETH
- Verified Sardine is shown as a provider for purchase of SOL (subject to availability in the region)

https://github.com/brave/brave-ios/assets/17010094/d5092e8c-40f4-48cd-b808-930802c74018
