### ISSUE TITLE
Favourites title cut off when reader mode enabled

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7609]
### Description: 

Reader Mode header cuts off “Favourites” title when url bar is focused.

### Steps to Reproduce 
  1. Visit a website with reader mode support and enable reader mode
  2. Tap url bar to focus
  3. `Favourites` label is half under the reader mode header

### Actual result:

![IMG_4872](https://github.com/brave/brave-ios/assets/5314553/ba1bb118-9a6b-4589-bbb4-4c7085adef55) | ![IMG_4873](https://github.com/brave/brave-ios/assets/5314553/9faf7e08-9f83-41d6-aba6-f4b65d61b460)
-|-

### Reproduces how often: 

Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using version `1.56 (23.7.19.18)`

- Verified favorites on not cut off when reader mode is enabled

Example | Example
-|-
![IMG_3363](https://github.com/brave/brave-ios/assets/17885425/46890a20-f55f-42fa-8fca-b033029ef104) | ![IMG_3362](https://github.com/brave/brave-ios/assets/17885425/4aedc280-9db6-4ca8-b93c-ae2dfc83b03e)
![IMG_3368](https://github.com/brave/brave-ios/assets/17885425/472dfa12-222d-4af2-8d64-eac6afc4db33) | ![IMG_3369](https://github.com/brave/brave-ios/assets/17885425/4fdbfa80-71b7-481a-a81c-a60060281f45)
