### ISSUE TITLE
Block all 3p storage

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#761]
### Description: 
Brave on iOS blocks 3p (eTLD+1) cookies by default. Add a switch to disable 3p storage by default. 

### Steps to Reproduce 
  1. Navigate to http://dustiest-limitation.000webhostapp.com/first_party.html
  2. Local Storage/Session Storage are not blocked for the third party.

**Actual result:** 
Local storage/session storage are not blocked

**Expected result:**
All 3p storage should be blocked

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
Development

**Device details:** 
iPhone SE

**Comment by jumde** [comment]
@danishjafri88 @jhreis - I think we can do this by adding a check similar to

```
if (window.top.location.origin != window.location.origin) {
   // block cookies
}
```

in CookieControl.js. Thoughts?

**Comment by danishjafri88** [comment]
@jumde yeah that is where I got the idea for yubikey

**Comment by jumde** [comment]
PR in progress, though we do need a toggle in the settings screen for this.

**Comment by danishjafri88** [comment]
@jumde apart from checking this in js you have to set the cookie control filter to third party. Additionally do not lock cookie folder in settings
