### ISSUE TITLE
Find In Page Bar dismisses when touched using top bar mode

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#7610]
### Description: 

A user reported:

> When I “find on page” and there are multiple results, clicking down arrow to get the next result instead causes the search to be cleared and the search bar to go away.
> 
> Brave version 1.51.2 (23.6.5.22)
> 
> iOS 16.5
> 
> I feel like this has been happening for several weeks.

And I confirmed it seems to be specific to top bar mode

### Steps to Reproduce 
  1. Enable top bar mode
  2. Enter find in page mode and enter a query
  3. Try to tap on an arrow to navigate search results 

### Actual result: 
The bar immediately dismisses

### Expected result:
It should navigate search results

### Reproduces how often:
Easily

### Brave Version: 
1.51.2 Release but likely a bug since #7238 was merged

### Device details: iPhone (haven't tested iPad yet)

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using version `1.52 (23.6.30.11)`

Using STR in https://github.com/brave/brave-ios/issues/7610#issue-1762304842

- Verified navigating through search results for `Find in Page` with top bar enabled
- Verified opening `Find in Page` using the context menu `find selection`

Example | Example | Example | Example
-|-|-|-
![IMG_3288](https://github.com/brave/brave-ios/assets/17885425/4d8a11af-c48e-4bbe-9b80-b9efc43c2399) | ![IMG_3289](https://github.com/brave/brave-ios/assets/17885425/f81fdd83-351b-4316-a944-f29eb56e1fc2) | ![IMG_3291](https://github.com/brave/brave-ios/assets/17885425/843963a6-0f24-4d69-b89d-8017d160d486) | ![IMG_3292](https://github.com/brave/brave-ios/assets/17885425/c3e971c0-27ee-4dd0-a593-8eafe2d1d01b)
