### ISSUE TITLE
Cosmetic filtering issues during slow internet connections

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#7612]
### Description: 
when the page takes a while to load, cosmetic filtering does not work as expected. This is caused by a flaw with how we poll new selectors after the initial page selector query. The query is fine, but we fail to add selectors for the added nodes (we only add selectors for sub-nodes). In addition there was a flaw with arguments passed to a method when we switch to polling mode when a new element is added. These two problems conspired to cause ads to appear intermittently.

### Steps to Reproduce 
  1. Enable slow internet connection (You can use network link conditioner for this)
  2. Go to https://theverge.com

### Actual result: 
- Cookie banner appears

### Expected result:
- Cookie banner should not appear

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

### Brave Version: 
1.51.2

### Additional Information
Caused by 2 problems on the cosmetic filtering script

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5]
Version: 1.52 (23.6.22.18)
BraveCore: 1.52.125 (114.0.5735.110)
```
---------------------------

**STEPS:**
1. Device settings > Developer
2. Network link conditioner
3. Enable a slow internet connection
4. Launch Brave > Go to https://theverge.com/ > Wait until the page will be loaded

**ACTUAL RESULTS:**
- Verified that the Cookie banner does not appear when the internet speed is slow

---------------------------

https://github.com/brave/brave-ios/assets/128532965/a1b82bcf-a328-43ec-81f8-757c06d1e08b
