### ISSUE TITLE
Colored status bar leaks in overlay mode

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7615]
### Steps to Reproduce 
  1. visit news.ycombinator.com notice the orange top bar
  2. tap on url bar to enter overlay mode

### Actual result: 
Status bar area stays orange

### Expected result:
Should match the overlay background color

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5.1]
Brave build: 1.56 (23.7.18.21)
BraveCore: 1.56.6 (115.0.5790.90)
```

Filed follow-up issue #7755
---------------------------

**PRECONDITIONS:**
Make sure `Bottom Bar` is enabled

**STEPS:**
1. Launch Brave
2. Go to www.news.ycombinator.com
3. Tap on URL bar to enter overlay mode > Verify

**ACTUAL RESULTS:**
- Verified that `Status bar` area is matching the overlay background color

---------------------------

|1.52.1|1.56 [Bottom Bar]|1.56 [Top Bar]|1.56 [Landscape Mode]|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/38f4da2d-7281-4a11-aad9-10d1662c2542) | ![2](https://github.com/brave/brave-ios/assets/128532965/8ad803da-f975-408f-9202-b09fc86032ab) | ![3](https://github.com/brave/brave-ios/assets/128532965/9998c2a2-d38c-4ca1-b5df-21569a78bee3) | ![4](https://github.com/brave/brave-ios/assets/128532965/f7e65dc7-e9e3-4ceb-b52d-bd7fa8bf231d) |
