### ISSUE TITLE
Portfolio Filters Empty State(s)

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7618]
### Description: 

Title: `No available assets`
Description: `Deposit or purchase tokens to get started. If you don't see tokens from an imported account, check the filters and display settings. Unknown tokens may need to be added as custom assets.`

https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1686939237810999

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.57 (23.8.23.20)
- Verified steps from [#7826](https://github.com/brave/brave-ios/pull/7826)
- Verified able to group assets by accounts or networks
- Verified able to sort asset based on balance High to low/low to high
- Verified able to sort asset in ascending (A to Z) or descending (Z to A)
- Verified able to hide tokens with < 0.5 balance
- Verified able to filter portfolio by specific account
- Verified able to filter portfolio by specific network
- Verified saved settings is retained between browser restarts
- Encountered  [#7942](https://github.com/brave/brave-ios/issues/7942), [#7943](https://github.com/brave/brave-browser/issues/36775), [#7944](https://github.com/brave/brave-ios/issues/7944), [#7945](https://github.com/brave/brave-ios/issues/7945), [#7946](https://github.com/brave/brave-ios/issues/7946)

iPhone 7+ (iOS 15.7.8) | iPhone 13 (iOS 16.6) | iPad Pro (iOS 16.6)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/cd238f84-d5d9-47bf-a441-f1290a33044b> | <video src=https://github.com/brave/brave-ios/assets/17010094/55a6f04b-ec36-43cf-aaf1-839e3a474ae1> | <video src=https://github.com/brave/brave-ios/assets/17010094/fcc1214d-cf8c-4c49-96e7-96f0351ef1a8>
