### ISSUE TITLE
Account change may not select expected account

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7621]
### Description: 

Switching accounts from one coin type to another, while also changing the selected account for that coin type may select the wrong account.

### Steps to Reproduce 
  1. Have 2 or more accounts for both coin types (Ethereum and Solana)
  2. Select the first account for Ethereum & Solana
  3. In the Wallet panel, 
      - if Ethereum is selected choose the second Solana account.
      - If Solana is selected choose the second Ethereum account
   4. (race condition so not every time) Observe incorrect account is selected, or loop causing bad app performance.

### Actual result: 

https://github.com/brave/brave-ios/assets/5314553/96274d36-dff4-46b0-a2f8-3b21f67cabd9

### Expected result:

Selects the account user taps on.

### Reproduces how often: 

Does not occur every time, but reproducible.

### Brave Version: 

Regressed in v1.53 with #7523 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

cc @srirambv

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.56 (23.7.19.18)
- Verified steps from [#7622](https://github.com/brave/brave-ios/pull/7622)
- Verified correct account name is shown when network is changed or account is change via account selector
- Verified Send show sthe correct token based on account/network selecgted 

iPhone 7+ (iOS 15.7.3) | iPhone 13 (iOS 16.5)
-- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/29b6abef-f948-4f07-a386-8c604765653f> | <video src=https://github.com/brave/brave-ios/assets/17010094/7218eabf-7bfc-41a9-919b-2655d7c173a6>
