### ISSUE TITLE
Adding custom network does not add native asset to visible assets

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7623]
### Description: 

When adding a custom network, the network's native asset used to be automatically added as a visible asset shown in Portfolio. Since moving to core data for user assets, this does not occur.

### Steps to Reproduce 
  1. Add an EVM network (via Settings or DApp like https://chainlist.org)
  2. Open Portfolio and observe the added network's native asset is not visible
  3. Tap 'Edit User Assets'
  4. Filter to only the newly added network
  5. Observe the only asset (native asset) is unchecked.

### Actual result: 

https://github.com/brave/brave-ios/assets/5314553/857145a9-cd52-4b53-88d2-7f2e2a3a641a

### Expected result:

Native asset is added as a visible asset.

### Reproduces how often: 

Easily reproduced

### Brave Version:

Regressed in v1.53 with #7443 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

The native asset is not removed from Core Data when you remove the network, so if you remove the network & re-add it, it will have the previous visibility status.

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.56 (23.7.19.18)
- Verified steps from issue description
- Verified native token is listed when a custom network is manually added

iPhone 7+ (iOS 15.7.3) | iPhone 13 (iOS 16.5) | iPad Pro (iOS 16.6 Beta)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/9fe728ba-0265-4677-9891-8a4227a8b4a7> | <video src=https://github.com/brave/brave-ios/assets/17010094/741efda6-fe5c-4c83-b7a0-686574f43f61> | <video src=https://github.com/brave/brave-ios/assets/17010094/b0e2b792-3ed2-4bbe-a2d9-35ae3a597852>
