### ISSUE TITLE
Cosmetic filters are bleeding into WYSIWYG editors

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#7626]
### Description: 
WYSIWYG editors are revealing the html style we append to the body causing some people to think we are injecting malicious links to the page. This is because some of these styles have selectors containing hrefs to known tracker pages.

https://www.reddit.com/r/brave_browser/comments/14fk8q5/brave_browser_adds_links_to_submitted_forms/

### Steps to Reproduce 
Steps are available on the reddit thread above.

1. go to https://surveyjs.io/form-library/examples/custom-widget-ckeditor/angular
2. enter some text in the box and click Complete
3. Look at the generated text

### Actual result: 
Generated code contains a stylesheet with a large list of hide selectors some of which have urls to questionable sites

### Expected result:
The stylesheet should not be visible in the generated code.

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5] and iPad Air [iPadOS 16.4.1]
Version: 1.52 (23.6.22.18)
BraveCore: 1.52.125 (114.0.5735.110)
```
---------------------------

**STEPS:**
1. Launch Brave
2. Go to https://surveyjs.io/form-library/examples/custom-widget-ckeditor/angular
3. Enter some text in the box and click `Complete`
4. Look at the generated `text` > Verify

**ACTUAL RESULTS:**
- Verified that there is no `styling` added to the text 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/1d4b386c-f488-4609-a050-305ceb6fa696) | ![2](https://github.com/brave/brave-ios/assets/128532965/d7404908-f384-4f64-870f-e54ca133b750) | ![3](https://github.com/brave/brave-ios/assets/128532965/4baaf294-8b83-48fa-beea-21dcf0635840) | ![4](https://github.com/brave/brave-ios/assets/128532965/23d9b044-6b8c-45d3-86d5-602d9f208648) |
