### ISSUE TITLE
Suggested video ads on youtube

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#763]
### Description: 
From https://github.com/brave/browser-ios/issues/782 

### Steps to Reproduce 
  1. Navigate to youtube.com

**Actual result:** 
Ads are visible

**Expected result:**
Ads should be blocked

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
Development

**Device details:** 
iPhone SE

**Comment by jhreis** [comment]
@jumde Is this still an issue?

**Comment by jumde** [comment]
@joel - Repros on development: 

![image](https://user-images.githubusercontent.com/1903815/54847229-11930380-4c9b-11e9-99f5-72d4df4965cb.png)

**Comment by iccub** [comment]
This is because afaik we do not support cosmetic filters, closing in favor of more general ticket https://github.com/brave/brave-ios/issues/2683
