### ISSUE TITLE
Tabs do not restore their titles only url

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7636]
### Steps to Reproduce 
  1. Open couple tabs
  2. Close the app
  3. Reopen

### Actual result: 
No titles are restored, only urls

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5.1]
Brave build: 1.56 (23.7.19.18)
BraveCore: 1.56.6 (115.0.5790.90)
```
---------------------------

**STEPS:**
1. Launch Brave
2. Open a few tabs
3. Close and then relaunch Brave
4. Tap `tab switch` button > Verify

**ACTUAL RESULTS:**
- Verified that after Brave relaunched, tabs restore they `title`

---------------------------

|1.52|1.56|1.56|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/c95ffcde-53ba-42ad-bced-caad9605eb85) | ![2](https://github.com/brave/brave-ios/assets/128532965/2560b326-0c76-4bea-bf5f-2539b531b6a0) | ![3](https://github.com/brave/brave-ios/assets/128532965/8192c0cd-5471-40a5-ba1a-fe48e02c7dcd) |

https://github.com/brave/brave-ios/assets/128532965/4025b77a-0f6b-44ef-8eaa-29b8a1ad4ae0
