### ISSUE TITLE
Solana DApp Connect Show Multiple Accounts

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7637]
### Description: 

Follow up to [brave-browser #31109](https://github.com/brave/brave-browser/issues/31109).
All Solana accounts should be shown in the `Connect` modal (`NewSiteConnectionView`), but only one account should be selectable at a time (ETH should still allow multiple account selection).

Need to confirm behaviour/logic of `RequestPermissions` after changes: https://github.com/brave/brave-ios/blob/development/Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController%2BWallet.swift#L239-L244

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17 running 1.58 (23.9.19.14)
- Verified steps from [brave-core#19200](https://github.com/brave/brave-core/pull/19200)
- Verified solana connect prompt shows all available Solana accounts when connecting to a Dapp
- Encountered [#8088](https://github.com/brave/brave-ios/issues/8088)

https://github.com/brave/brave-ios/assets/17010094/c1bc0cc1-2143-45d2-99df-813c6f91b3b5
