### ISSUE TITLE
Sort test network tokens to end of Select Token to Send

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7640]
### Description: 

Test network tokens should not be sorted to top of each account list in Select Token to Send

### Steps to Reproduce 
  1. Have a test network with larger value than mainnet token (ex. ETH on Goerli > ETH on Mainnet
  2. Enable 'Show test networks' in Web3 Settings.
  3. Open Send & tap the token to select a token to send
  4. ETH on Goerli should be listed below ETH on Mainnet despite larger balance

### Actual result:

![Simulator Screenshot - iPhone 14 Pro - 2023-06-26 at 10 25 03](https://github.com/brave/brave-ios/assets/5314553/f971906b-367f-49b6-889c-793c96d0827f)

### Expected result:

![Screenshot 2023-06-26 at 10 18 14 AM](https://github.com/brave/brave-ios/assets/5314553/73da2ee0-8ec3-4a7d-979c-5c284100e5c2)

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.56 (23.7.14.16)
- Verified steps from issue description
- Verified test networks are always shown at the end of the select token screen

iPhone 7+ (iOS 15.7.3) | iPhone 13 (iOS 16.5) | iPad Pro (iOS 16.6 Beta)
-- | -- | --
<img width=300 src=https://github.com/brave/brave-ios/assets/17010094/4a93d502-2bc1-4c62-a729-76c85389dd54> | <img width=250 src=https://github.com/brave/brave-ios/assets/17010094/024c7147-eda8-4af6-84d0-488ae58003d6> | <img width=400 src=https://github.com/brave/brave-ios/assets/17010094/6450bba7-21bf-4e10-8603-26252bbb1c1c>
<img width=300 src=https://github.com/brave/brave-ios/assets/17010094/a1103d0f-4587-4e1e-b016-1738d737d87b> | <img width=250 src=https://github.com/brave/brave-ios/assets/17010094/1b17e50d-8675-47fc-bc1a-571c026c8f2e> | <img width=400 src=https://github.com/brave/brave-ios/assets/17010094/99d0ce5d-2bf6-4025-bb9c-a41a356edc59>
