### ISSUE TITLE
URL Bar Context Menu is interfering with URL Bar Custom Buttons Long Press Action

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#7642]
### Description: 

The change from using long-press action / action_sheet behaviour for copy-paste actions on URL bar to context menu for URL Bar is blocking long-press actions for custom buttons like refresh or reader mode.

Right now only refresh button has a long press action that presents action sheet for loading the website using desktop/mobile mode.

To fix this the context menu can be triggered from url text field however it is not working due to url bar textfield is having drag and drop delegate.

Need some other idea / solution to handle this.

### Steps to Reproduce 
  1. Long-Press on Refresh button
  2. It selects and activates url bar and shows context menu

### Actual result: 
It selects and activates url bar and shows context menu

### Expected result:
It should show a load website in desktop mode action sheet

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily produced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? YES

### Device details: 
Any

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 [iOS 16.6]
- iPad Air [iPadOS 16.5]
Brave build: 1.57 (23.8.16.21)
BraveCore: 1.57.47 (116.0.5845.96)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Open any website
3. Tap and hold on `Refresh` button or `URL search bar` > Verify

**ACTUAL RESULTS:**
- Verified that the context menu is opened when tapped `Refresh` button or `URL search bar`
- Verified that `URL search bar` is not activated and context menu is not overlapped with Copy/Paste menu

---------------------------

|iPhone|iPad|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/10b2b4d8-57e0-4f03-a560-56e8437efb2e) | ![2](https://github.com/brave/brave-ios/assets/128532965/672152d9-49b8-419d-8ebb-2c2a3fb100db) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/15e6e91d-1aea-4dc2-ba80-96a5c845e8e3) | ![2](https://github.com/brave/brave-ios/assets/128532965/0d695a96-79bf-4f06-bef1-2e34d43d0834) |
