### ISSUE TITLE
[Follow up to #7422] "Add to playlist" button is shown outside of search bar

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#7644]
### Description: 

Follow-up to #7422

### Steps to Reproduce 
  1. Fresh install Brave
  2. Launch Brave and open www.youtube.com
  3. As soon as the page starts loading, scroll down to hide the `Bottom bar` > Observe

### Actual result: 

`Add to playlist` button is shown outside of the search bar when `Bottom bar` is hidden.

<img width="462" alt="Screenshot 2023-06-26 at 16 12 11" src="https://github.com/brave/brave-ios/assets/128532965/c48f9382-a454-4c76-a177-5b46ca56f045">

https://github.com/brave/brave-ios/assets/128532965/577536a1-316d-4405-bcc0-a0f6eededc1a

### Expected result:

`Add to playlist` button must be shown in the search bar only.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Version: 1.52 (23.6.22.18)
BraveCore: 1.52.125 (114.0.5735.110)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? No
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 

iPhone 14 [iOS 16.5]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
This is already fixed in 1.53 with these changes: https://github.com/brave/brave-ios/issues/7526

Please re-open this issue if you need us to fix this for the 1.52 release
