### ISSUE TITLE
Tabs bar reorder crash

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7645]
### Steps to Reproduce 
Hard to reproduce

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.1]
Brave build: 1.58 (23.10.6.14)
BraveCore: 1.58.139 (117.0.5938.153)
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-ios/pull/8161#issue-1914126793

**ACTUAL RESULTS:**
- Verified that Brave is not crashing

---------------------------

https://github.com/brave/brave-ios/assets/128532965/897c02a5-3e6a-4f35-9b86-53a999425682
