### ISSUE TITLE
Black screen issue

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#7648]
### Description: 
https://appfigures.com/reviews/42132121512LADuK2LOX4NEm3izozy6Lgw?lang=en

When you close the screen with automatic lock or open another screen and return, the video screen will be black and only the sound will be played.
I fixed it once by updating BRAVE,
This problem has returned with an iOS update. I'm inconvenient and in trouble.

**Comment by anthonypkeane** [comment]
https://github.com/brave/brave-ios/issues/6661

**Comment by anthonypkeane** [comment]
https://appfigures.com/reviews/42132121512LrQflkQts1PrEHgHLtr0qRQ?lang=en

**Comment by anthonypkeane** [comment]
https://appfigures.com/reviews/42132121512L7OGPl5ctokvrXAH_3Q5n4w?lang=en

**Comment by anthonypkeane** [comment]
Linked to: https://github.com/brave/brave-ios/issues/6661

**Comment by kylehickinson** [comment]
Closed to be tracked here: https://github.com/brave/brave-browser/issues/36064
