### ISSUE TITLE
Update Shields Off description to match desktop

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#765]
## Description: 
Shields off description only covers ads and trackers:

<img width="441" alt="screen shot 2019-01-19 at 12 24 27 pm" src="https://user-images.githubusercontent.com/1903815/51431992-a9b23500-1be5-11e9-8e9b-137ebdc9f1d5.png">

Shields off description on desktop browser:
![shields off](https://user-images.githubusercontent.com/2388823/60132285-09da7380-9750-11e9-9cb5-c96401585225.png)

## Expected Result
Update the description to match desktop string:
![Browser - shields off](https://user-images.githubusercontent.com/2388823/60132329-2080ca80-9750-11e9-9459-746ba8e3636a.png)

### Steps to Reproduce 
  1. Navigate to any site
  2. Turn shields off

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
Dev

**Device details:** 
iPhone SE

**Comment by karenkliu** [comment]
Closing this as this will be covered in the new Shields refresh https://github.com/brave/brave-ios/issues/1923 cc @anthonypkeane
