### ISSUE TITLE
Search results are always shown with "Google search" when using "Look Up" option even when SE is different from Google

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#7659]
### Description: 

Search results are always shown with `Google search` when using `Look Up` option even when SE is different from Google.

### Steps to Reproduce 
  1. Launch Brave > Three-dot menu > Settings
  2. Search Engines > Confirm that `Google search` is not set for both `Standard Tab` and `Private Tab`
  3. Go back and open www.wikipedia.org (or any other website)
  4. Tap and hold on any word to bring `Context menu` > Tap `Look Up`
  5. Scroll down > Tap `Search Web` with Brave > Observe

### Actual result: 

Search results are always shown with `Google search` when using `Look Up` option in the context menu even when SE is different from Google.

https://github.com/brave/brave-ios/assets/128532965/c3368b2a-f367-426c-bcd5-75287dcdb847

### Expected result:

When searching for something with the context menu `Look Up` option, the results must be shown with the selected Search Engine.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.52 (23.6.28.13)
BraveCore: 1.52.129 (114.0.5735.198)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 

iPhone 14 [iOS 16.5]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
This feature is not a Brave one, it's controlled by the Search Engine you have set in Safari and we can't change this unfortunately.

The only reason it even opens in Brave is due to the app being set as your default browser.

This is similar to searching via Spotlight search in iOS which also uses your Safari search preferences.
