### ISSUE TITLE
Playlist popup not dismissed when selecting 'maybe later'

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#7663]
### Description: 
Playlist intro popup not dismissed when selecting 'maybe later'

![IMG_0273](https://github.com/brave/brave-ios/assets/17885425/9c2da2f8-c718-4baf-a76b-b358806c4e2a)

### Steps to Reproduce 
  1. Install 1.53.x
  2. Navigate to youtube.com
  3. Play a video, playlist intro popup should be shown
  4. Select `Discover How` CTA
  5. Next, select `Maybe Later` on the next modal
 
### Actual result: 
Does not dismiss the popup

### Expected result:
Should dismiss the intro popup 

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

### Brave Version: 
1.53 (23.6.23.14)

- Can you reproduce this issue with the most recent build from TestFlight?  Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 
All devices, All OS

**Comment by iccub** [comment]
this onboarding does not exist in 1.52?

**Comment by Uni-verse** [comment]
> this onboarding does not exist in 1.52?

You are correct, I mistakenly entered the 1.52 build version. Its updated.

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` & `iPad (9th Gen)` running `iPadOS 15.6.1` using version `1.53 (23.7.6.16)`

- Ensured popup is dismissed when tapping `maybe later`
- Ensured that popup can be dismissed twice using `maybe later` 

<table><tr><td>iPhone</td><td>iPad</td></tr>

<tr><td>

https://github.com/brave/brave-ios/assets/17885425/103fb2ed-aa12-4a93-b31a-50328e0f1adc

</td><td>

https://github.com/brave/brave-ios/assets/17885425/965fcae4-ea02-4470-a51f-dd2a05196561

</td></tr></table>
