### ISSUE TITLE
"Block Fingerprinting" is not working on iOS 16.5+ for the Audio verification

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#7672]
### Description: 

`Block Fingerprinting` is not working on iOS 16.5+ for the Audio verification

### Steps to Reproduce 
  1. Launch Brave
  2. Open https://audiofingerprint.openwpm.com
  3. Tap `Fingerprint me!` > Observe 

### Actual result: 

When `Block Fingerprinting ` in Brave Shields is ON, Audio Fingerprints not blocked on https://audiofingerprint.openwpm.com. This is happening on both iPhone with iOS 16.5.1 and iPad with iOS 16.5, but based on @Uni-verse results, it's not happening on iOS 15.

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/af34f394-cdf8-4f99-b2c9-62990180bcb8) | ![2](https://github.com/brave/brave-ios/assets/128532965/bb406b7c-b991-4b8d-a845-91a3b7099781) |

### Expected result:

Audio Fingerprints on https://audiofingerprint.openwpm.com must be blocked when `Block Fingerprinting ` in Brave Shields is ON.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.52 (23.6.30.11)
BraveCore: 1.52.129 (114.0.5735.198)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 

iPhone 14 [iOS 16.5.1]
iPad Air [iPadOS 16.5]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
As discussed with @cuba, we've disabled audio farbling a while ago. Going to close the above as `closed/invalid`. @vlad-hoff a good check to see if we farble certain features would be https://dev-pages.brave.software/fingerprinting/farbling.html. @pes10k made a `iOS` specific column which indicates which features support farbling.
