### ISSUE TITLE
Would be nice to see the number of saved bookmarks under the folder name

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#7674]
### Description: 

Would be nice to see the number of saved bookmarks under the folder name

### Steps to Reproduce 
  1. Launch Brave 
  2. Open any website > Bookmark it
  3. Open `Bookmarks` > Observe that the user can't see how many bookmarks are saved in the folder

### Actual result: 

The user can't see how many bookmarks are saved in the folder. 

|iOS|Android|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/9a588753-734a-4048-9fb3-78d04d72c75d) | ![2](https://github.com/brave/brave-ios/assets/128532965/8be345f8-c3ec-48a6-9c73-de83365f4811) |

### Expected result:

It would be nice to see the number of saved bookmarks under the folder name. Similar thing implemented on Android already.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.52 (23.6.30.11)
BraveCore: 1.52.129 (114.0.5735.198)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 

iPhone 14 [iOS 16.5.1]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using version `1.56 (23.7.18.21)`

- Verified  bookmark count is displayed below folder name.
- Verified default state shows `0 bookmarks`, adding 1 bookmark will show `1 bookmark`
- Verified synced folders display the count from other devices.
- Verified removing/adding bookmarks in folder we update count.
- Verified bookmarking all tabs will show correct count for `Saved Tabs` folder in bookmarks
- Verified importing bookmarks displays the bookmark count.

Example | Example | Example | Example
-|-|-|-
![IMG_3343](https://github.com/brave/brave-ios/assets/17885425/b9dc0029-8a81-424f-8ba4-887a528a6850) | ![IMG_3344](https://github.com/brave/brave-ios/assets/17885425/a9bb5101-3708-44d3-8cb1-be539daf8eec) | ![IMG_3345](https://github.com/brave/brave-ios/assets/17885425/58ac2405-e575-481a-b7b8-167a398b113d) | ![IMG_3346](https://github.com/brave/brave-ios/assets/17885425/a978e4d3-6610-4a9d-b228-6dd79b2975e2)
