### ISSUE TITLE
The word "video" must be changed to "media" on any applicable pop-up message during "Playlist" onboarding

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#7675]
### Description: 

The word `video` must be changed to `media` on any applicable pop-up message during `Playlist` onboarding

### Steps to Reproduce 
  1. Launch Brave
  2. Open www.music.youtube.com  > Find some Audio album or a song
  3. Observe the first `Playlist` onboarding pop-up message > Tap `Discover How`
  4. Observe the second pop-up message `Introducing Brave Playlist` > Observe the word `video`

### Actual result: 

It's confusing to see the word `video` when doing `Playlist` onboarding on a website like www.music.youtube.com with opened song, but not a video.

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/a928cd2d-2759-4b38-bf74-fd30e1ebdd1b) | ![2](https://github.com/brave/brave-ios/assets/128532965/6edd1085-cf79-48b6-af4f-90031fbdb481) | ![3](https://github.com/brave/brave-ios/assets/128532965/adb9530f-42b2-4c75-804a-129ef4608961) | ![4](https://github.com/brave/brave-ios/assets/128532965/f08a8436-7f44-46a2-807e-478d2af3935d) |

### Expected result:

It would be nice to update the word `video` to `media` on any applicable pop-up message during `Playlist` onboarding since it's possible to add video and audio files to Brave Playlist.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.53 (23.6.23.14)
BraveCore: 1.53.102 (114.0.5735.133)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 

iPhone 14 [iOS 16.5.1]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by hkarmoush** [comment]
can I take over on this? @iccub @vlad-hoff

**Comment by kylehickinson** [comment]
Im not sure if we are actually planning on making this change so best to leave it for now, @hkarmoush. Thanks though!
