### ISSUE TITLE
Voice search icon in the url bar changes size sometimes

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#7676]
### Description: 
Voice search icon in the url bar changes size sometimes depending on the url

papa bear | mama bear | baby bear ( I think)
-|-|-
<img width="250" alt="2" src="https://github.com/brave/brave-ios/assets/17885425/bc25070f-827d-4715-9013-b1a8f7f9f8db"> | <img width="250" alt="2" src="https://github.com/brave/brave-ios/assets/17885425/f5c8f92f-ab4b-4711-9783-1b0c42e85d1e"> | <img width="250" alt="2" src="https://github.com/brave/brave-ios/assets/17885425/09df74d6-5f6b-4508-96cc-ca4689a0c33f">

### Steps to Reproduce 
  1. Install 1.53.x
  2. Navigate to webpage, tap on url and clear
  3. Observe icon size, search again
  4. Repeat a few times

### Actual result: 
Voice search icon does not display the same size

### Expected result:
Should be shown the same size in url bar

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

### Brave Version:  1.53 (23.6.23.14)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No (New feature)

### Device details: 
iPhone, iOS 16.3.1

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.6]
Brave build: 1.56 (23.7.31.17)
BraveCore: 1.56.13 (115.0.5790.136)
```
---------------------------

**STEPS:**
Followed the steps from https://github.com/brave/brave-ios/issues/7676#issue-1786794433

**ACTUAL RESULTS:**
- Verified that `Voice search` mic icon is not scaled/changing the size when doing multiple searches.

---------------------------

https://github.com/brave/brave-ios/assets/128532965/e2d3157c-7f62-4a1c-8ecc-ae2b0989dad4
