### ISSUE TITLE
Add 'Media' settings section

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7677]

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` & `iPad (9th Gen)` running `iOS 15.5` using version `1.56 (23.7.19.18)`

**Fresh Profile**

- Verified `Media` section appears under Display  in the Settings.
- Verified `Enable Background Audio` is disabled by default on clean profile.
- Verified Background audio when app is backgrounded or screen is locked when Background Audio is enabled.
- Verified user is able to select options in the quality settings for youtube
- Verified youtube quality settings are set to `Always On` by default

**Existing Profile**

- Verified Background play setting preference is retained when upgrading from `1.52.1` -> `1.56`

Example | Example | Example
-|-|-
![IMG_3355](https://github.com/brave/brave-ios/assets/17885425/2fb0d59a-5ce2-45b9-956c-9f457ced873c) | ![IMG_3356](https://github.com/brave/brave-ios/assets/17885425/41469b95-bcff-440e-9aef-4d322b596f8b) | ![IMG_3357](https://github.com/brave/brave-ios/assets/17885425/d5c64e01-408a-430c-8383-85781d9bfb20)
![IMG_3361](https://github.com/brave/brave-ios/assets/17885425/b56dbdcc-a923-453e-89a4-e3113c3c1734) | ![IMG_3360](https://github.com/brave/brave-ios/assets/17885425/34aa72aa-b870-4f56-af65-6f3bb5ee5f09) | ![IMG_3358](https://github.com/brave/brave-ios/assets/17885425/d5b166fb-6b64-484a-aca9-97c35ad59624)

Example | Example | Example
-|-|-
![IMG_0303 3](https://github.com/brave/brave-ios/assets/17885425/2fb6e300-b66d-4787-a121-88a1c892faa6) | ![IMG_0302 3](https://github.com/brave/brave-ios/assets/17885425/780f7558-fa35-499c-8d5e-31ee6bd0384f) | ![IMG_0301 2](https://github.com/brave/brave-ios/assets/17885425/be302a67-c0bc-414b-9ddf-de5a994c2081)
![IMG_0298 3](https://github.com/brave/brave-ios/assets/17885425/5dddf718-9be5-475e-8a80-d99ea681265d) | ![IMG_0299 3](https://github.com/brave/brave-ios/assets/17885425/e4510a61-0caf-4842-bbe9-c2250bcbecb9) | ![IMG_0300 2](https://github.com/brave/brave-ios/assets/17885425/25bda49c-685b-474c-b5a8-13e0958eb406)
