### ISSUE TITLE
Private Mode - Add a disclaimer about custom search engines 

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#7685]
## Problem Description 

Need to include disclaimer on the custom search engine page and default search engine page in private mode to explain it is restricted to normal mode.

## Design 
Need approval for footer in search engine screens.

### Additional information 

Ticket: https://github.com/brave/brave-ios/issues/3300

Security Concern: https://github.com/brave/reviews/issues/314#issuecomment-777829874

**Comment by iccub** [comment]
We will allow to add custom SE in private mode. closing this one
