### ISSUE TITLE
Voice search not detecting sound

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#7686]
### Description: 
Voice search does not seem to be working only on OS version 15 for iPads

This is not an issue on iOS 15/16 or iPadOS 16

### Steps to Reproduce 
  1. Install 1.53.x
  2. Once on new tab, select the microphone icon in the URL bar
  3. Enable mic permissions for Brave
  4. Once the voice search modal opens, search query with your voice

### Actual result: 

https://github.com/brave/brave-ios/assets/17885425/ce4fb53b-27cf-4c79-9814-4844373f1f6d

### Expected result:
Sound should be detected, query should be entered using voice

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always (iPadOS 15)

### Brave Version:  1.53 (23.6.23.14)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? No (new feature)
- Can you reproduce this issue with the current build from AppStore? No (new feature)

### Device details: 
`iPad (9th Gen)`, `iPadOS 15.6.1`

**Comment by srirambv** [comment]
Seeing the issue in iPhone 13(iOS 16.5) as well so not specifically limited to iPad

**Comment by soner-yuksel** [comment]
I tried to debug this or check in detail, I have no answer to what is happening here. This is either a problem with microphone on that device or some permission problem or you guys are using some headphone or some bluetooth headphones.

**Comment by iccub** [comment]
@Uni-verse @srirambv do you have non english OS language or region set?

**Comment by Uni-verse** [comment]
Verified on `iPad (9th Gen)` running `iOS 15.5` using version `1.56 (23.7.19.18)`

Using test plan in https://github.com/brave/brave-ios/pull/7727#issue-1801757172

- Verified that microphone icon is hidden when not supported for the current locale

![IMG_0304 2](https://github.com/brave/brave-ios/assets/17885425/ed78a143-e9e0-4938-b165-9ba43a44987e)
