### ISSUE TITLE
Call disconnect on Solana Provider when permission revoked

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7688]
### Description: 

Related to https://github.com/brave/brave-browser/issues/24974.

Above PR implements a new `DisconnectEvent` on `SolanaEventsListener` which should emit the disconnect event. This event listener method will be called when `Disconnect()` is called on the provider. We need to implement the above new `SolanaEventsListener` method, and call disconnect on the provider when permissions are revoked for the site (assuming it's open & has a provider).

cc @darkdh 

### Test Plan

1. Setup wallet with fresh profile.
2. Open two tabs and navigates to different Solana DApps in each and set network to Solana Mainnet for both.
3. Connect to both DApps
4. Check both panels showing "Connected".
5. Open Web3 Settings -> Solana and verify both connections shown.
6. Revoke the entry associated with one of the two DApps opened in step 2.
7. Switch to the tab for DApp whose permission was revoked and verify `Connected` is not shown.
8. Switch to the tab for the other DApp, verify it still shows `Connected`.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17 running 1.58 (23.9.19.14)
- Verified steps from issue description
- Verified different dapps connected or disconnected state with Solana wallet is correctly shown in panel

https://github.com/brave/brave-ios/assets/17010094/524ffba6-62b8-42d1-ac96-e0bf208023a0
