### ISSUE TITLE
Brave Rewards crashes the app when swiping to close

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#7690]
### Description: 
- When swiping the application up in the task switcher in order to close it, the app will crash sometimes

### Steps to Reproduce 
  1. Swipe up to kill the app.

### Actual result: 
- Crash

### Expected result:
- Should not crash

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Intermittent Issue

### Brave Version: 
- 1.51.x

- Can you reproduce this issue with the most recent build from TestFlight?  - Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight?  - Yes
- Can you reproduce this issue with the current build from AppStore?  - Yes

### Device details: 
- Any

**Comment by Uni-verse** [comment]
Verified using `1.56 (23.7.19.18)` using the following device(s):

iPhone X, iOS 16.5.1
iPhone XR, iOS 15.6.1
iPad (9th Gen), iPadOS 15.5
iPad (7th Gen), iPadOS 16.5.1

- Ensured swiping to close app did not cause app to crash with and without Browser Lock feature enabled.
