### ISSUE TITLE
Web compat issues on youtube when scrolling/reloading page [iPad]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#7692]
### Description: 
Web compat issues on youtube when scrolling/reloading page [iPad]

Related to: https://github.com/brave/brave-ios/issues/7655

### Steps to Reproduce 
  1. Install 1.52.x
  2. Navigate to youtube.com
  3. Play some videos, scroll through the comments/related videos
  4. Try reloading the page and adding video to playlist and then return from playlist

### Actual result: 
Content fails to load/starts to freeze up

### Expected result:
Content should load and navigation should be fluid

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

### Brave Version:  Any 1.52.x

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
iPadOS

**Comment by iccub** [comment]
Please retest in `1.52.1 (23.7.11.14)`

**Comment by Uni-verse** [comment]
Verified on `iPad (9th Gen)` running `iPadOS 15.6.1` using version `1.52.1 (23.7.11.14)`

Using STR in https://github.com/brave/brave-ios/issues/7692#issue-1791653705

- Confirmed that scrolling/reloading youtube does not cause freezing, content loading issues.
- Confirmed adding videos to playlist and returning to youtube site does not cause web compat issues.

**Comment by iccub** [comment]
I am reopening this one and changing milestone. This time we go for a proper fix. Not for a code revert.
Let me know if you would prefer a new ticket instead
