### ISSUE TITLE
Voice Search (and other onboarding popups) appear off screen when using iPad multi-tasking/split-view

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#7693]
### Description: 

Anything that uses `PopupViewController` (such as Voice Search and some onboarding popups) would present incorrectly when using iPad and having Brave mutlitasking with any other app 

### Steps to Reproduce 
  1. Open Brave on iPad, Tap the ••• in the center of the status bar and tap "Split View", pick any app 
  2. Tap on Voice Search in the URL bar

### Actual result:

Popup appears off-screen

![image](https://github.com/brave/brave-ios/assets/529104/8e58e6e5-dd40-4231-9e94-c9061d209265)

### Expected result:

Popup appear sized correctly inside the current available bounds

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily

**Comment by hffvld** [comment]
Verified on `iPad Air` using version(s):
```
Device/OS: iPad Air [iPadOS 16.5]
Brave build: 1.56 (23.7.19.18)
BraveCore: 1.56.6 (115.0.5790.90)
```
---------------------------

**STEPS:**
1. Launch Brave > Tap `•••` in the center of the status bar > Tap `Split View1 > Pick any app
2. Open NTP > Tap the `Microphone` thumbnail in the search bar > Verify

**ACTUAL RESULTS:**
- Verified that Brave `Voice Search` UI is shown correctly in `Split screen` Mode
- Verified in `Portrait Mode` and `Landscape Mode`
- Verified with different app proportions

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/c55eac0f-6c77-439c-9edd-123653b7b82e) | ![2](https://github.com/brave/brave-ios/assets/128532965/8280eff8-f683-4d8c-b6ae-6a0ebc0a095d) | ![3](https://github.com/brave/brave-ios/assets/128532965/59145a26-427a-47a8-b8b2-82cdf50f5f0e) |
|4|5|6|
| ![1](https://github.com/brave/brave-ios/assets/128532965/5b687a9b-da0e-41eb-8d7e-fae2f89a219e) | ![2](https://github.com/brave/brave-ios/assets/128532965/772bc35b-62ba-47ad-98ca-e15ae5e7f4d3) | ![3](https://github.com/brave/brave-ios/assets/128532965/7c15c06b-f2cc-412d-a035-26b2479948de) |
