### ISSUE TITLE
Text update for the restore tabs page

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#7695]
### Description: 
Please update the text on this page to

Brave Closed Unexpectedly
Unfortunately, Brave crashed or did not close properly. 
Restore your tabs?
Yes | No

![IMG_4283](https://github.com/brave/brave-ios/assets/7606853/7a33bd34-badb-4a93-9b67-db79f9904d9e)

**Comment by hkarmoush** [comment]
Only had to modify the strings inside `BraveStrings.swift`

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.6]
Brave build: 1.57 (23.8.18.20)
BraveCore: 1.57.47 (116.0.5845.96)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Settings > View Rewards Debug Menu > CHange `Override` to any other value to trigger `Brave crash` > Exit Now
3. Observe the message about sharing the report > Skip it
4. Launch Brave > Verify
5. Tap `No` > Verify
6. Trigger `Restore tab page` message once again > Tap `Yes` > Verify

**ACTUAL RESULTS:**
- Verified the strings on `Restore tab page` message
- Verified that the message is:
```
             Brave quit unexpectedly.
Unfortunately, Brave crashed or did not close properly.
               Restore your tabs?
                   No  |   Yes
```
- Verified that tabs are not restored when tapped `No`, and tabs are restored when tapped `Yes`
---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/757aa609-de9e-4b98-8e7a-4fddc6bc1772) | ![2](https://github.com/brave/brave-ios/assets/128532965/05c01f12-22cd-4c47-980e-796a7c5a47f2) |

**Comment by anthonypkeane** [comment]
The text on the device doesn't match the text in the issue, please look at this again

(Note: please watch for Title Case also)
