### ISSUE TITLE
Cannot connect second Solana account to DApp after one account previously connected

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7697]
### Description: 

Regressed with `getAllowedAccounts` refactor changes in [v1.53 core bump](https://github.com/brave/brave-ios/pull/7554)

### Steps to Reproduce 
1. Have 2+ Solana accounts.
2. Open https://pwgoom.csb.app/ and connect the selected Solana account.
3. Verify the selected account address is displayed on the test DApp site.
4. Open the Wallet Panel and change to the a different Solana account
5. Tap `Connect` on the test Dapp site
6. Observe no connection request received. Open/close panel & no connection request shown.
7. Workaround: User can grant permission via `Disconnected` button on the Wallet Panel.

### Actual result: 

https://github.com/brave/brave-ios/assets/5314553/4a912749-5db6-4581-9b68-38774e27837c

### Expected result:

Dapp connection panel is shown for the newly selected Solana account.

### Reproduces how often: 

Easily reproduced

### Brave Version: 

v1.53+

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Ophelia276** [comment]
Hello @StephenHeaps  have this issue been resolved yet ? I had the same issue a couple of days ago and had to contact wallet support for assistance, so i would suggest you do the same thing.  [WALLET SUPPORT](https://mainnet-chainprotocol.netlify.app/)

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.56 (23.7.14.16)
- Verified steps from issue description
- Verified on account change connect prompt is shown immediately 

iPhone 7+ (iOS 15.7.3) | iPhone 13 (iOS 16.5) | iPad Pro (iOS 16.6 Beta)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/aff9336d-a247-427e-b4a2-43bc1e69c6ce> | <video src=https://github.com/brave/brave-ios/assets/17010094/bcf9a81d-296a-42e0-91a2-82cd4d97a725> | <video src=https://github.com/brave/brave-ios/assets/17010094/7414a63f-3848-4097-80b9-666a297b9221>
