### ISSUE TITLE
NFT Filters and Display Settings

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7699]
### Description: 

Re-use the `FiltersDisplaySettingsView` from Portfolio but for the NFT tab. 
Don't show the `Hide Small Balances` row when opened from NFT tab.
Add `Network Logo / Show network logo on NFTs` when opened from NFT tab.

Ref:
https://github.com/brave/brave-ios/issues/7585

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 16.6 running 1.57 (23.8.24.22)
- Verified steps from [#7750](https://github.com/brave/brave-ios/pull/7750)
- Verified able to filter NFTs by network
- Verified able to filter NFTs by account
- Verified toggling Network Logo, shows/hides the logo on NFT
- Verified toggling Hide Unowned, shows/hides the NFTs based on filtered accounts
- Verified filter settings set in NFT filters are carried over to Portfolio settings as well
- Encountered [#7963](https://github.com/brave/brave-ios/issues/7963)

https://github.com/brave/brave-ios/assets/17010094/77aa172d-1163-45c0-8251-1e198d44b75f
