### ISSUE TITLE
[hackerone] OpenSearch issues

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-ios#7702]
https://hackerone.com/reports/2057565

Please also check my comment here https://hackerone.com/reports/2057565#activity-22722892

**Comment by hffvld** [comment]
Hi @stoletheminerals do you know what website can QA use to validate the fix for this ticket?

**Comment by hffvld** [comment]
@stoletheminerals @soner-yuksel In build 1.52 I was able to install `Custom SE` from  https://csrf.jp/2023/brave_opensearch.php and see a request to `bad_sugest.php`. However, with build 1.56 (23.7.19.18) I can't install `Custom SE`. Is this expected?

|1.52|1.56|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/9e50a29d-2930-4ada-b8b1-7dbff85417df) | ![2](https://github.com/brave/brave-ios/assets/128532965/f776f860-f06a-4343-b35b-5b992674fa5f) |

*1.56 (23.7.19.18)*

https://github.com/brave/brave-ios/assets/128532965/589383d0-19b2-4027-a971-d0a304050563

**Comment by stoletheminerals** [comment]
@vlad-hoff yep this is expected, one of the issues was that Brave allowed adding multiple search providers with the same name, which led to crashes and other weird behaviours. @soner-yuksel added a check, so when you add a new SE and there is already a SE with the same name - Brave will return an error. 
To test other issues in the ticket you will need to modify the HTTP response of search3.xml file, just change short and long names from Google to something else (e.g EvilTest)

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5.1]
Brave build: 1.57 (23.7.26.15)
BraveCore: 1.57.13 (115.0.5790.90)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Visit https://en.m.wikipedia.org/wiki/Main_Page
3. Tap the magnifier button and activate the search
4. Tap Add custom search engine button over the keyboard > Verify
5. Go to settings > Search engines > Add Custom Search Engine
6. Type `https://wikipedia.org/search?q=%s` > Then type Name as `Wikipedia (en)` > Add > Verify
7. Settings Search Engines > Disable `Show Search Suggestions`
8. Type a search query > Verify

**ACTUAL RESULTS:**
- Verified that both `suggestion - search` URL template is written on the description on alert
- Verified that an error message is shown when trying to add the same SE (URL and Name)
- Verified that Brave is not sending requests to suggestion API when `Show Search Suggestions` is OFF

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/5a8f29b2-db0e-40b7-9b65-a77a395f9e65) | ![2](https://github.com/brave/brave-ios/assets/128532965/b61c330a-0898-492b-8cc9-224a61ed094f) | ![3](https://user-images.githubusercontent.com/128532965/255727702-f776f860-f06a-4343-b35b-5b992674fa5f.png) | ![4](https://github.com/brave/brave-ios/assets/128532965/71be6261-575d-438d-a3f5-2601c3a3a05d) |

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/d523f97b-bd3a-4d04-9bca-b55746629c4e) | ![2](https://github.com/brave/brave-ios/assets/128532965/e5961c81-d48b-4e27-b834-aa9306d9429e) | ![3](https://github.com/brave/brave-ios/assets/128532965/194d77b9-4043-4694-92ec-04414f0619b0) | ![4](https://github.com/brave/brave-ios/assets/128532965/89428207-2c81-4737-9f5d-447d9d7ab537) |
