### ISSUE TITLE
Favorites on NTP reorder crash

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#7714]
### Description: 
Per discussion in https://bravesoftware.slack.com/archives/C01QQG17D4Z/p1689083244817479, there have been some SDK changes to be applied with 1.52.1.

cc @iccub for more information

### Steps to Reproduce

1. Install 1.52
2. Try to move favorites around NTP
3. Observe any crashes

**Comment by iccub** [comment]
I updated title. STR sounds good to me

**Comment by kjozwiak** [comment]
Thanks for getting the above created @LaurenWags 👍 Always good to have a record re: issues of what went into a release even though it might be `QA/No` and not user facing.
