### ISSUE TITLE
Reader mode bar background color doesn't match night mode & private mode 

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#7717]
### Description: 

The reader mode bar background color uses the light or dark url bar background color regardless of night mode or private mode state.

### Steps to Reproduce 
  1. Open a wikipedia page and activate reader mode
  2. Turn on night mode or private mode

### Actual result:

The reader mode bar at the top of the page does not match the url bar background color

| Private Mode | Night Mode | 
| --- | --- |
| ![Simulator Screenshot - iPhone 14 Pro - 2023-07-11 at 14 56 54](https://github.com/brave/brave-ios/assets/529104/01c555ca-be57-4659-a1dc-996d152d4f12) | ![Simulator Screenshot - iPhone 14 Pro - 2023-07-11 at 14 56 45](https://github.com/brave/brave-ios/assets/529104/95b767fb-f350-4979-bdab-9e1aa4964bd9) |

### Expected result:

Should match

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.0]
Brave build: 1.58 (23.9.19.14)
BraveCore: 1.58.124 (117.0.5938.62)
```
---------------------------
<details>
<summary> Standard Tab </summary>

**STEPS:**
1. Launch Brave 
2. Open the Wikipedia website > Tap `Reader Mode` button in the URL search bar > Verify UI color
3. Three-dot menu > Night Mode > Verify UI color
4. Tree-dot menu > Settings > TABS > Enable `Top Bar`
5. Return to Wikipedia > Verify UI with and without `Night Mode` again

**ACTUAL RESULTS:**
- Verified that UI color has proper color with and without `Night Mode`
- Verified above behavior with `Top Bar` and `Bottom Bar`

---------------------------

|Bottom Bar, no Night Mode|Bottom Bar with, Night Mode|Top Bar, no Night Mode|Top Bar with, Night Mode|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/ccd4eac3-6a77-4fe5-bdbc-4851cd8047b0) | ![2](https://github.com/brave/brave-ios/assets/128532965/90e6dda8-f6dc-49e6-971f-8310755ee78e) | ![3](https://github.com/brave/brave-ios/assets/128532965/03cf91f2-4ce4-4e18-8878-1d5fa11b31f6) | ![4](https://github.com/brave/brave-ios/assets/128532965/3f0b019d-51af-44d9-ba64-c4db1ff8fcff) |
</details>

<details>
<summary> Private Tab </summary>

**STEPS:**
1. Launch Brave 
2. Tap `Tab switch` button > Private > `+` button
3. Open the Wikipedia website > Tap `Reader Mode` button in the URL search bar > Verify UI color
4. Three-dot menu > Night Mode > Verify UI color
5. Tree-dot menu > Settings > TABS > Enable `Top Bar`
6. Return to Wikipedia > Verify UI with and without `Night Mode` again

**ACTUAL RESULTS:**
- Verified that UI color has proper color with and without `Night Mode` (In a `Private Mode` it has the same color)
- Verified above behavior with `Top Bar` and `Bottom Bar`

---------------------------

|Bottom Bar, no Night Mode|Bottom Bar with, Night Mode|Top Bar, no Night Mode|Top Bar with, Night Mode|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/692d3291-c1f9-4353-b998-be8417d4f27e) | ![2](https://github.com/brave/brave-ios/assets/128532965/6c2cae7b-0d5f-48f2-a65b-e660aa87b7f4) | ![3](https://github.com/brave/brave-ios/assets/128532965/37f41940-3384-45f9-96c1-84e513582751) | ![4](https://github.com/brave/brave-ios/assets/128532965/6e753526-d174-4fd3-a259-921cb751b656) |
</details>
