### ISSUE TITLE
Sync order is not updating after reordering bookmarks.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#772]
More actions will be done after a server side bug https://github.com/brave/sync/issues/231 is fixed

For now when you reorder a bookmark on one device it does not get updated on other devices, tested on iOS-iOS so far.

**Comment by anthonypkeane** [comment]
@iccub 

Do you only find this when moving bookmarks under the same folder, or do you find it all the time?

**Comment by iccub** [comment]
On iOS, only moving bookmarks under the same folder is supported. 
So it happens every time I try to move a bookmark

**Comment by anthonypkeane** [comment]
cc @darkdh

**Comment by srirambv** [comment]
There is a weird bug here when bookmarks/folders are reordered on one device
Device 1: iPhone 7+ sync chain creator with existing bookmarks
Device 2: iPad Pro created empty bookmark folder post sync
Reorder all bookmark folders to the end post sync causes the following

Device 1:
![image from ios](https://user-images.githubusercontent.com/17010094/52327005-86262180-2a10-11e9-9bda-9e26c0dfa7f9.png)
Device 2:
![file 5](https://user-images.githubusercontent.com/17010094/52327013-8de5c600-2a10-11e9-91ea-273dc745391f.jpg)


Closing the bookmark tray and reopening it shows correctly. Also some times it messes up the ordering and folders start showing up with weird colours

**Comment by iccub** [comment]
Could you make a separate issue for it @srirambv?

**Comment by iccub** [comment]
Update on this issue:
it was caused by a client side bug, I have a fix for it ready

**Comment by srirambv** [comment]
* Verification passed on iPhone 6/7+ and iPad Pro running 1.9(19.3.9.1)
* Verified passed with 1.9 (19.3.9.1) on iPhone SE
* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR.
