### ISSUE TITLE
Wallet Selected Account Refactor

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7723]
### Description: 

Address changes with the [Selected Account Refactor](https://github.com/brave/brave-browser/issues/31013) in BraveCore.

`selectedCoin`/`setSelectedCoin` no longer exist. Instead we get the `selectedAccount`, `ethDappSelectedAccount`, and `solDappSelectedAccount` from KeyringService's `GetAllAccounts()`.

`EnsureSelectedAccountForChain(CoinType coin, string chain_id) => (AccountId? account_id);` was added to WalletService select the correct account (if needed) after changing network. This helps avoid race conditions previously hit when switching account/network.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 15.7.8 running 1.58 (23.9.21.21)
- Verified steps from [#7725](https://github.com/brave/brave-ios/pull/7725)
- Verified able to switch between accounts/network in panel
- Verified able to connect to a Dapp successfully
- Verified when multiple accounts are there and selected account is shown as default when trying to connect to a Dapp
- Verified able to switch networks/accounts in Buy screen
- Verified able to switch tokens from accounts in Send screen
- Verified switching network automatically switches accounts on Swap screen
- Verified selecting a token and selecting Send/Swap from the token details page pre-populates the token in the Send/Swap screen respectively
- Verified able to add Ethereum/Solana/Filecoin accounts
-----------
Verification passed on iPhone 13 with iOS 17 running 1.58 (23.9.21.21)
- Verified steps from [#7725](https://github.com/brave/brave-ios/pull/7725)
- Verified able to switch between accounts/network in panel
- Verified able to connect to a Dapp successfully
- Verified when multiple accounts are there and selected account is shown as default when trying to connect to a Dapp
- Verified able to switch networks/accounts in Buy screen
- Verified able to switch tokens from accounts in Send screen
- Verified switching network automatically switches accounts on Swap screen
- Verified selecting a token and selecting Send/Swap from the token details page pre-populates the token in the Send/Swap screen respectively
- Verified able to add Ethereum/Solana/Filecoin accounts
-----------
Verification passed on iPad with iOS 16.7 running 1.58 (23.9.21.21)
- Verified steps from [#7725](https://github.com/brave/brave-ios/pull/7725)
- Verified able to switch between accounts/network in panel
- Verified able to connect to a Dapp successfully
- Verified when multiple accounts are there and selected account is shown as default when trying to connect to a Dapp
- Verified able to switch networks/accounts in Buy screen
- Verified able to switch tokens from accounts in Send screen
- Verified switching network automatically switches accounts on Swap screen
- Verified selecting a token and selecting Send/Swap from the token details page pre-populates the token in the Send/Swap screen respectively
- Verified able to add Ethereum/Solana/Filecoin accounts
