### ISSUE TITLE
Allow Custom Search Engines to be default in Private Mode

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#7733]
### Description: 

The custom Search Engines Added can not be selected as default search engine for private mode

### Steps to Reproduce 
  1. Add a custom Search Engine
  2. Go Settings - Search - Private Tab

### Actual result: 

- Cant see custom search engines

### Expected result:

-Able to see and set as default search engine

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
Any

### Website problems only:
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information

Security Ticket related with issue

https://github.com/brave/reviews/issues/1333#issuecomment-1631243239

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5.1]
Brave build: 1.56 (23.7.13.16)
BraveCore: 1.56.5 (115.0.5790.75)
```
---------------------------

**STEPS:**
1. Add a custom Search Engine
2. Go to Settings > Search Engines
3.  Private Tab > Set a custom search engine
4. Go back and open `Private tab` > Enter search query > Verify

**ACTUAL RESULTS:**
- Verified that a custom search engine can be set and used for `Private tab`
- Verified that a custom search engine can be set and used for `Normal tab`

---------------------------

https://github.com/brave/brave-ios/assets/128532965/bbb2dd52-dcba-4bfa-acf1-ebdc1783e40a
