### ISSUE TITLE
Crash at Browsing Mode Change while drag-drop action in Tab Tray

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#7737]
### Description: 
https://appfigures.com/reviews/42132121512L44ERBxmkCeXQjERXN2I4BQ?lang=en

Hello, when being in the incognito overview and dragging one window with one finger, and then clicking the „private“ flag, the browser crashes

1.52

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
QA please give it a small test. we cant repro

**Comment by hffvld** [comment]
Hey @iccub I was able to reproduce it on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.5.1]
Brave build: 1.56 (23.7.19.18)
BraveCore: 1.56.6 (115.0.5790.90)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Open at least 2 tabs
3. Tap on `Tab switch` button
4. Tap and hold on any tab, so you can drag the tab around
5. Now keep holding/dragging the tab and with another finger tap `Private` button > Observe Brave is crashing

**ACTUAL RESULTS:**
- Brave is crashing when user is holding a tab and tapping on `Private` button at the same time.

---------------------------

https://github.com/brave/brave-ios/assets/128532965/9244c12f-a4e8-45e9-b0cd-2d263be5ee1a

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.6]
Brave build: 1.57 (23.8.16.21)
BraveCore: 1.57.47 (116.0.5845.96)
```
---------------------------

**STEPS:**
Followed the steps from https://github.com/brave/brave-ios/issues/7737#issuecomment-1644855791

**ACTUAL RESULTS:**
- Verified that Brave is not crashing when switching between `Normal` and `Private` tabs

---------------------------

https://github.com/brave/brave-ios/assets/128532965/c07616e3-204d-4a70-9bc8-fe50172dc509
