### ISSUE TITLE
VPN support email can be generated without picking a category

### ISSUE THREAD

**Issue by bsclifton** [brave/brave-ios#7749]
### Description: 
Guardian VPN support has shared that customers who have purchased using in-app-purchase can create a support email without having picked a category. 

Ideally, we'd have them pick one of the options (Can't connect to VPN, no internet when connected, slow connection, website doesn't work, other)

**Comment by anthonypkeane** [comment]
The initial logic here was it can create friction for the user to **have** to select a category.  Sounds like Guardian VPN support are asking for this. Do we know if it is causing them a lot of issue by not having this selection by some users? Thanks

**Comment by anthonypkeane** [comment]
In discussion: https://bravesoftware.slack.com/archives/C0141L60REG/p1689893079310289

**Comment by soner-yuksel** [comment]
Closed by https://github.com/brave/brave-ios/issues/7828
