### ISSUE TITLE
Device is not removed from Sync when other device deletes it

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#775]
### Steps to Reproduce 
  1. Join device A and device B
  2. On device B remove device A
  3. Open Sync settings on device A

**Actual result:** 
Sync settings are showing with only device B presented, sync chain is not removed from the device(A)

**Expected result:**
Device should be removed from Sync chain

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by LaurenWags** [comment]
* Verified passed with 1.9 (19.3.9.1) on iPad 5th Gen using STR above
* Verified passed with 1.9 (19.3.9.1) on iPhone SE
* Verified passed with 1.9 (19.3.9.1) on iPhone 8
* Verification passed on iPhone 7+/6 and iPad Pro  running 1.9(19.3.9.1)
* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR.
