### ISSUE TITLE
Wallet: Tx summary blockie group is displaying the wrong color for `to address`

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#7751]
We are only looking at the eth `to address` for eth tx, so it will break if its a solana transaction. 

![simulator_screenshot_13669600-AF88-4E33-9606-B69A8ED208FD](https://github.com/brave/brave-ios/assets/1187676/8ea30106-30bc-4b59-9bf8-0ef32ed1f1d0) | ![simulator_screenshot_4FFA5999-A6BD-4093-8FFA-B5F92DA6DECE](https://github.com/brave/brave-ios/assets/1187676/2a93242e-e625-4724-9f8b-d2d68b97bbe0)
--|--

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 16.6 running 1.57 (23.8.24.22)
- Verified steps from [ #7754](https://github.com/brave/brave-ios/pull/7754)
- Verified transaction summary shows correct blockie colour of the pending transactions

https://github.com/brave/brave-ios/assets/17010094/5194f240-3c4d-43bd-941d-0c57da627c8d
