### ISSUE TITLE
Reopen last closed tab in tab tray context menu

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7752]
## Problem Description 

Could we add a `Reopen Last Closed Tab` option to the context menu on the tap tray button? I believe we already have a re-open last closed tab hotkey, but a menu option would be nice when no hardware keyboard is connected.

We may want to make sure there is a 'last closed tab' before showing the option, similar to `Duplicate Active Tab` is only visible when on a webpage (not visible on new tab page).

## Feature Overview 

It reopens the last closed tab.

## Design 

![IMG_555E72C35948-1](https://github.com/brave/brave-ios/assets/5314553/9f2b12c2-e184-48d5-aef5-111adbfc6af4)

### Additional information 

Ref
https://bravesoftware.slack.com/archives/G01F4JUNXAQ/p1679086733461429

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.6]
Brave build: 1.57 (23.8.16.21)
BraveCore: 1.57.47 (116.0.5845.96)
```
Filed follow-up issue #7897
---------------------------

**STEPS:**
1. Fresh launch Brave 
2. Tap and hold `Tab button` to see the context menu > Verify
3. Open 2 tabs > Tap and hold `Tab button` to see the context menu > Verify
4. Close one tab > Tap and hold `Tab button` to see the context menu
5. Tap `Reopen Last Closed Tab` > Verify
6. Close both tabs one by one > Tap and hold `Tab button` to see the context menu
7. Tap `Reopen Last Closed Tab` > Verify
8. Tap and hold `Tab button` to see the context menu again > Tap `Reopen Last Closed Tab` > Verify

**ACTUAL RESULTS:**
- Verified that `Reopen Last Closed Tab` is not shown when no tabs were recently closed
- Verified that `Reopen Last Closed Tab` is shown when some tabs were closed already
- Verify that it's possible to restore recently closed tabs
- Verified that it's possible to restore more than one recently closed tab, and tabs are restored in the correct order

---------------------------

|No recently closed tabs|With recently closed tabs|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/26c83f0c-b481-49ec-9012-3f588886672a) | ![2](https://github.com/brave/brave-ios/assets/128532965/fa300d71-9097-42e9-99df-e5bd9cc17d29) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/0cf87812-c695-4e66-ab36-a324ca3f06f4) | ![2](https://github.com/brave/brave-ios/assets/128532965/27530564-ab6a-43e0-81b6-65e39a2b8501) |

https://github.com/brave/brave-ios/assets/128532965/952cce9e-529a-4ee7-925d-da2c244a1c99
