### ISSUE TITLE
Support Portfolio Group By Filter

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7765]
### Description: 

Support `Group by` filter in Portfolio. 
Title:  `Group by`
Description: `Group assets by`
Options: `None` (default), `Accounts`, `Networks`

If a group has no tokens visible (after other filters are applied), it should be hidden. Ex. Hiding small balances & grouping by account, an account group with no balance for any token would be hidden.

Portfolio v2 designs have grouping support, if done with Portfolio v1 use section grouping.

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-ios/issues/7618#issuecomment-1691481368
