### ISSUE TITLE
Add filter / search bar to Select a Token to Send

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7768]
### Description: 

Add a search bar / filter to `Select a Token to Send` view.
When opening Send from Asset Details, we should pre-populate the search field with the token symbol.

![search](https://github.com/brave/brave-ios/assets/5314553/68de4ef8-114e-46ac-83c7-6d76baddd2c2)

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 16.6 running 1.57 (23.8.24.22)
- Verified steps from [#7799](https://github.com/brave/brave-ios/pull/7799)
- Verified select token screen is shown when clicking on Send
- Verified selecting Send from token details page pre-populates the token and loads the select token screen to select from different account
- Encountered [#7923](https://github.com/brave/brave-ios/issues/7923)

https://github.com/brave/brave-ios/assets/17010094/fa603655-3c68-48fd-9d91-ad5306ccc4b8
