### ISSUE TITLE
Media Settings copy update

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7776]
per https://github.com/brave/brave-ios/issues/7055#issuecomment-1648937689

Pls change
Allows desktop-quality resolution
for
Allows high-quality resolution

Pls update the settings options to:
On
Allow over Wi-Fi (enabled default)
Off

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` & `iPad (9th Gen)` running `iPadOS 15.6.1` using version `1.56 (23.7.25.16)`

Acceptance Criteria: https://github.com/brave/brave-ios/issues/7776#issue-1819125163

- Verified copy updated to `Allows high-quality resolution`
- Verified `Allow over Wi-Fi` set as default for Quality Settings page
- Verified copy changes to options on Quality Settings page

Example | Example
-|-
![IMG_3372](https://github.com/brave/brave-ios/assets/17885425/aad489fe-3337-43c0-a612-e31a882e90a6) | ![IMG_3373](https://github.com/brave/brave-ios/assets/17885425/31ccbbd4-acb9-4e5c-9c12-797e02a0aebf)
![IMG_0315 2](https://github.com/brave/brave-ios/assets/17885425/96b8d00b-565f-4764-9dce-f2dd24e126ca) | ![IMG_0316 3](https://github.com/brave/brave-ios/assets/17885425/655403a4-edf9-45e4-8b27-f2c0fd4d97f9)
