### ISSUE TITLE
Add support for EIP-6963

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7779]
### Description: 

> Add support for EIP-6963 https://eips.ethereum.org/EIPS/eip-6963
You can test via:
https://eip6963.org/

iOS version of https://github.com/brave/brave-browser/issues/30595

- ~Will need `window.braveEthereum` defined so we can use the event handlers from core due to [ethereum_provider.js](https://github.com/brave/brave-core/blob/eaf5cf705d25fc3ca26426cdb44d6e793d121926/components/brave_wallet/resources/ethereum_provider.js) checking for `window.braveEthereum` existence.~ Updated in https://github.com/brave/brave-ios/pull/7867
- Will need to define the `EIP6963AnnounceProviderEvent`, and listen for `EIP6963RequestProviderEvent` event. When `EIP6963RequestProviderEvent` is received, we should emit `EIP6963AnnounceProviderEvent`.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.2 running 1.60 (23.11.12.17)
- Verified steps from [#8034](https://github.com/brave/brave-ios/pull/8034)
- Verified `https://eip6963.org/` sees Brave Wallet with an icon and can connect
- Verified Ethereum DApp functionality still working as expected on multiple DApp sites.

https://github.com/brave/brave-ios/assets/17010094/a935f556-d5fc-42ce-844b-ee6367c84885
