### ISSUE TITLE
can't add certain websites as favourites

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#778]
### Description: 

Sometimes certain websites can't be added as a favourite due to the `Add to Favourites` button not being displayed under the `Sharing & Actions` area.

### Steps to Reproduce 

  1. open brave and load `us.diablo3.com/en/`
  2. tap on the `Sharing & Actions` button and you'll notice that `Add to Favourites` is missing

**Actual result:** 

![img_9747](https://user-images.githubusercontent.com/2602313/51576091-e51d5f80-1e82-11e9-86fe-4cea36ab956c.PNG)

**Expected result:**

Should be able to add any website via the `Add to Favourites` button under `Sharing & Actions`

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

* `1.7.3 (19.1.22.17)` - Reproduced
* `1.7.2 (19.1.18.15)` - Reproduced

**Device details:** 

* Used `iPad Mini 4 running iOS 12.1.3` & `iPhone 6s+ running  iOS 12.1.3`

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by danishjafri88** [comment]
@jhreis the mime type for this site is "application/xhtml+xml" which should be treated same as "text/html". I pushing a pr for the same. If the current implementation is what is wanted we can close the pr.

**Comment by LaurenWags** [comment]
* Verified passed with 1.9 (19.3.9.1) on iPad 5th Gen using STR above
* Verification passed on 1.9 (19.3.9.1). Verified the STR on iPhone 8 
* ~Verification passed on Samsung s7 (ARM), Brave v1.0.84-rc.2~
* Verification passed on iPad Pro, iPhone 6/7+ running 1.9(19.3.9.1)
* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR.
