### ISSUE TITLE
No visible assets after restoring wallet without resetting first

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7785]
### Description: 

After restoring a wallet without resetting the existing wallet first, there are no visible assets displayed in Portfolio.

### Steps to Reproduce 
  1. Reset your wallet if you haven't already (not 100% sure if required, any existing wallet might suffice)
  2. Create a new wallet
  3. After wallet onboarding/setup and Portfolio is shown, lock the wallet and tap `Restore` on the unlock wallet screen
  4. Restore your wallet
  5. Observe no visible assets selected

### Actual result: 

No visible assets are shown / selected

https://github.com/brave/brave-ios/assets/5314553/dec46f6d-2123-4cbf-a836-345a220bed1a

### Expected result:

Default visible assets are shown & selected

### Reproduces how often: 

Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 16.5 running 1.56 (23.7.31.17)
- Verified steps from issue description
- Verified disabling tokens and restoring wallet again shows all the tokens as expected
