### ISSUE TITLE
App hangs and crashes on launch when you have 100s of tabs open

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#7786]
### Description: 

When you have 100s of tabs open it can slow down the launch of the app by a lot and if it hangs long enough the OS will crash the app

### Steps to Reproduce 
  1. Create 100s of tabs (If testing against PR, use "Create 1000 Tabs" in debug settings section)
  2. Kill & launch the app
  3. The same hang can be seen when deleting all open tabs*

### Actual result:

Hangs for long period, and may crash

### Expected result:

Should launch immediately

### Reproduces how often: 

Easily with enough tabs

### Additional Information

Crash log

[Client-2023-07-24-074311 (1).txt](https://github.com/brave/brave-ios/files/12176016/Client-2023-07-24-074311.1.txt)

**Comment by Uni-verse** [comment]
Verified on the following devices using version `1.56 (23.7.25.16)`

`iPhone X`, `iOS 16.5.1`
`iPhone XR`, `iOS 15.5`
`iPad (9th Gen)`, `iPadOS 15.6.1`

- Ensured app does not hang or crash when launching with >150 tabs
- Ensured closing >150 tabs does not cause app to crash
- Ensured opening >150 saved tabs does not hang app


https://github.com/brave/brave-ios/assets/17885425/f1831c16-0e6d-459e-a726-3e88a328bb9f
