### ISSUE TITLE
Stripe on-ramp

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7794]
### Description: 

Support on-ramp from Stripe in Buy flows.

iOS version of https://github.com/brave/brave-browser/issues/31397

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17 running 1.58 (23.9.20.15)
- Verified steps from [#7879](https://github.com/brave/brave-ios/pull/7879)
- Verified `0` is shown as the placeholder and `USD $` as the default currency selector
- Verified Stripe On-Ramp is only available when USD is set as the purchase token
- Verified changing from USD to other Fiat currency doesn't list Stripe as an on-ramp provider

https://github.com/brave/brave-ios/assets/17010094/bf0ab1eb-36bb-4b46-86dc-348fcb9ed029
