### ISSUE TITLE
Add Haptic Feedback Voice Search for successful query

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#7798]
### Description: 

Add a haptic feedback (vibration sounds and impact feedback) for successful voice search entry

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.0]
Brave build: 1.57 (23.8.23.20)
BraveCore: 1.57.53 (116.0.5845.114)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. NTP > Tap in the URL search bar
3. Invoke `Voice search` > Ask some query
4. Wait until the search flow is done > Verify

**ACTUAL RESULTS:**
- Verified that `Voice search` is working (no regression)
- Verified that `haptic feedback` is triggered after a successful voice search

---------------------------

*I'm not sure how to record the video with haptic feedback representation :)*

https://github.com/brave/brave-ios/assets/128532965/84e2ef73-1522-41f6-9917-19c1f8eaeae7
