### ISSUE TITLE
Possible duplicated auto-discovered assets after restoring wallet

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7804]
### Description: 

Requires an account with balance on non-native assets that will be found via asset auto-discovery

### Steps to Reproduce 
1. Fresh install
2. Setup wallet with assets that get found by asset auto discovery
3. Close wallet
4. Open Settings -> Web3
5. Reset Wallet
6. Open Wallet
7. Restore wallet from step 2

### Actual result: 

Assets found via auto discovery are duplicated in Portfolio, Edit User Assets, etc.

![Screenshot 2023-07-28 at 3 36 06 PM](https://github.com/brave/brave-ios/assets/5314553/5188ac5d-9232-4673-890b-e8330de5d5b4) | ![Screenshot 2023-07-28 at 3 38 34 PM](https://github.com/brave/brave-ios/assets/5314553/b1b7639e-28b4-4943-95f2-f9f82af28658)
--|--

### Expected result:

No duplicated assets

### Reproduces how often: 

Not sure it occurs every time, but consistent enough to reproduce.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 16.5 running 1.56 (23.7.31.17)
- Verified steps from issue description
- Verified restoring wallet doesn't duplicate tokens
