### ISSUE TITLE
Sync devices from settings still can't be swiped to delete

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#781]
This should be disabled per the new Sync UI updates from https://github.com/brave/brave-ios/issues/719

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+/6 and iPad Pro running 1.9(19.3.9.1)
* Verified passed with 1.9 (19.3.9.1) on iPhone SE
* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR.
