### ISSUE TITLE
'Items' in change playlist view not translated

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#7813]
### Description: 
Items in change playlist folder view not translated

### Steps to Reproduce 
  1. Install `1.56.x`
  2. Change device language to non-english
  3. Navigate to video site
  4. Add media to playlist 
  5. Tap on playlist icon in url bar
  6. Select `Change Playlist`
  7. Observe 'item count' string under folder

### Actual result: 
![IMG_3395](https://github.com/brave/brave-ios/assets/17885425/8cab8c06-c357-41ad-9584-40553ea9417e)

### Expected result:
'items' should be translated

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always

### Brave Version:  1.56 (23.7.31.17)

- Can you reproduce this issue with the most recent build from TestFlight?  Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 
iPhone, iPad

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.2
Brave build: 1.60 (23.11.7.17)
BraveCore: 1.60.113 (119.0.6045.105)
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-ios/issues/7813#issue-1832073159

**ACTUAL RESULTS:**
- Verified that `item count` is translated into other languages.

---------------------------

|English|Russian|Spanish|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/b41a58d3-05bd-4fcf-b8f8-5de8fc0877f5) | ![2](https://github.com/brave/brave-ios/assets/128532965/4358a903-9ceb-4e06-add4-5f48a75de8ff) | ![3](https://github.com/brave/brave-ios/assets/128532965/78cb5335-82e4-4191-a9c6-12a602b69bae) |
|French|German|Japanise|
| ![1](https://github.com/brave/brave-ios/assets/128532965/6b8eba58-5696-42ea-b10d-51d54e65e9f9) | ![2](https://github.com/brave/brave-ios/assets/128532965/5826d23b-a6b6-4c9b-940d-c30e802dba50) | ![3](https://github.com/brave/brave-ios/assets/128532965/6d4c3798-03ea-4be7-bfed-6ef78e9d2bbd) |
