### ISSUE TITLE
Broken search: wrong result numbers

### ISSUE THREAD

**Issue by EvgeniyDoctor** [brave/brave-ios#7814]
### Description: 
Search shows wrong numbers of the result.

### Steps to Reproduce 
  1. search for something
  2. search for another value
  3. search again for your first request

### Actual result: 

1. Here is screenshot of my first search for the 'fox' word. As you can see, it is already broken:<br>![3](https://github.com/brave/brave-ios/assets/15073200/1b0eb5ea-5311-4c46-ad60-498791e3bc24)
2. After this i searched for another word and then again searched for the 'fox':<br>![4](https://github.com/brave/brave-ios/assets/15073200/7db939fe-4f6c-4e93-b50b-1de08d30aea1)
3. And i did step number 2 one more time:<br>![5](https://github.com/brave/brave-ios/assets/15073200/fcb1effc-3019-47cb-8646-87f988ef39a4)

And now i have 6 matches out of 1!

### Expected result:
Numbers should be correct.

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Often, but not always.

### Brave Version: 
1.52.1 (23.7.11.14)

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details: 
Iphone 11
IOS 15.7.1

### Website problems only:
- did you check with Brave Shields down? No.
- did you check in Safari/Firefox (WkWebView-based browsers)? No.

**Comment by iccub** [comment]
see https://github.com/brave/brave-ios/issues/7815#issuecomment-1665859111
