### ISSUE TITLE
Broken search: wrong numbering

### ISSUE THREAD

**Issue by EvgeniyDoctor** [brave/brave-ios#7815]
### Description: 
The numbering of search results is broken.

### Steps to Reproduce 
  1. Search for something
  
### Actual result: 
The numbering starts from the latest match.

1. Here is the first match of my search request, but is has number 2:<br>![1](https://github.com/brave/brave-ios/assets/15073200/2f7c89ed-dc2b-4bf9-b96e-bc56dbe97153)
2. But the latest one on this page has number 1:<br>![2](https://github.com/brave/brave-ios/assets/15073200/0cac28a7-4c25-4188-b41b-826afef73c66)

### Expected result:
The numbering should start from the topmost match.

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Pretty often.

### Brave Version: 
1.52.1 (23.7.11.14)

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details: 
Iphone 11
IOS 15.7.1

### Website problems only:
- did you check with Brave Shields down? No.
- did you check in Safari/Firefox (WkWebView-based browsers)? No.

**Comment by iccub** [comment]
From iOS 16 we started using Apple's api for find in page functionality. It is much more robust.
We do not plan to maintain the iOS 15 version or do any bigger bug fixes, as this iOS version will be dropped by us soon, sorry.
Closing as wont fix
