### ISSUE TITLE
Checkmark does not show beside selected account

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7823]
### Description: 

In the `Select Account` panel, the checkmark for the selected account is not always shown

### Steps to Reproduce 
  1. Open Wallet Panel and tap the blockie for the selected account
  2. In the `Select Account` modal, the checkmark might not be shown. If displayed, select a different account & re-open.

### Actual result: 

https://github.com/brave/brave-ios/assets/5314553/c5254b1a-6231-4392-82cf-8306662cfb28

### Expected result:

Checkmark always shown beside selected account

### Brave Version: 

v1.57+ (no checkmark is shown in earlier designs).

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.57 (23.8.21.22)
- Verified steps from [#7824](https://github.com/brave/brave-ios/pull/7824)
- Verified check mark is shown correctly on the selected account

iPhone 7+ (iOS 15.7.8) | iPhone 13 (iOS 16.6) | iPad Pro (iOS 16.6)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/444c76a4-3ea2-4f84-ac9b-1b5d6d199505> | <video src=https://github.com/brave/brave-ios/assets/17010094/d23a704c-16fb-45f0-a1b7-cf892943b2e9> | <video src=https://github.com/brave/brave-ios/assets/17010094/55d37102-6919-4f40-b440-7554f5270add>
