### ISSUE TITLE
Sign-In with Ethereum

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7827]
### Description: 

> eip: https://eips.ethereum.org/EIPS/eip-4361
> spec: https://docs.google.com/document/d/1WM96l81vZ4Rcu4RD4x3gGn7HcePBqsJ9qWq2sVwNE_Y/

iOS version of https://github.com/brave/brave-browser/issues/32077
Core / parent issue: https://github.com/brave/brave-browser/issues/32076

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.60 (23.11.12.17)
- Verified steps from [#8319](https://github.com/brave/brave-ios/pull/8319)
- Verified Sign-In with Ethereum UI is shown when trying to approve and sign-in on `https://login.xyz`
- Verified clicking on `See details` on SIWE UI shows details of the message
- Verified SIWE with resources list the resource details in the message details on `https://metamask.github.io/test-dapp`
- Verified error message is shown for `Wrong statement format`, `Domain mismatch`. `Account mismatch` and `Network mismatch` when format is wrong
- Verified no error message is shown and falls back to `EIP-191` format when an incorrect format is used
Note: Non-ASCII and consecutive new line tests were checked by Dev/Security team hence skipped while QA verification

iPhone 13 (iOS 17.2) | iPad Pro (iOS 16.7.2) | iPhone 7+ (iOS 15.8)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/ac0e9294-6460-4bbb-8690-da41a05b19e6> | <video src=https://github.com/brave/brave-ios/assets/17010094/69b93d0a-35e9-4d3b-8a70-ddf116ebf9ee> | <video src=https://github.com/brave/brave-ios/assets/17010094/cecc7410-6d87-42b4-ae9e-fa5ad7dabea2>
