### ISSUE TITLE
Adding Issue Category Separately to VPN Contact Form 

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#7828]
## Problem Description 

Issue Category is a necessary field to distinguish problems inside contact form email for VPN. This field is also needed in support email subject field.

## Feature Overview 

The Issue selection should be added as a second step to email creation and it should be mandatory. After selecting the issue type the email should be populated where issue type is also added in email subject field.

## Design 

![supportmeialtest13211](https://github.com/brave/brave-ios/assets/6643505/0a9e7ecf-6cb1-40c0-9287-f19ca16d76be)

## Implementation Details 

The issue selector will be used as 2nd screen after first step and choosing a category will create the new populated email. With this way not much code change will be required.

## User Experience 

1. Go Settings 
2. Press Brave Firewall + VPN
3. Press Contact Technical Support
4. Choose (toggle) categories which are necessary
5. Click Continue to Email
7. Issue Selection screen presented
8. Select a issue
9. email should be presented with necessary Issue in subject and body for the email

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iPadOS 16.5.1` using version `1.57 (23.8.28.22)`

- Confirmed issue presented in the email subject and body using STR in https://github.com/brave/brave-ios/pull/7829#issue-1835778748

Example | Example | Example
-|-|-
![IMG_1173](https://github.com/brave/brave-ios/assets/17885425/92c06bae-9410-4be3-92c5-2ad5060e8d2e) | ![IMG_1174](https://github.com/brave/brave-ios/assets/17885425/09c8cf3b-9625-4a6f-8697-d4a3275ebc5f) | ![IMG_1175](https://github.com/brave/brave-ios/assets/17885425/ae281e27-33a8-4a70-accb-2fe0b7891ca4)
