### ISSUE TITLE
Closing tab does not stop media play 

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#7831]
### Description: 
Closing tab does not stop media play, only reproducible on cellular enabled devices.

Regression in 1.56.x

### Steps to Reproduce 
  1. Install 1.56.x
  2. Enabled background play in Media setting menu
  3. Load youtube and play video
  4. Closing the current tab
  5. Confirm media play has stopped

### Actual result: 
Audio does not stop

https://github.com/brave/brave-ios/assets/17885425/b67e007c-167c-4219-97fd-d877a972fc7e

### Expected result:
Audio should stop

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 
iPhone X, 16.5.1 - cellular enabled
iPhone 12 Pro, 16.6 - cellular enabled

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
@Uni-verse nice catch 👍 I can also reproduce this using `1.56 (22.8.3.22)` but can't reproduce using `1.52.1 (23.7.11.14)`.

* `iPhone 12` running `iOS 16.5.1` - **Reproduced** (on both `WiFi` & `Cellular`)

**Comment by Uni-verse** [comment]
Verified on the following devices using dev channel build `1.56 (23.8.4.21)` & `1.56 (23.8.4.20)` for release channel. 

iPhone X, iOS 16.5.1
iPhone 12 Pro, iOS 16.6

Preconditions: cellular enabled on device

- Verified STR in https://github.com/brave/brave-ios/issues/7831#issue-1837242125 and unable to reproduce using build above. 
- Verified background play will stop when disabled in settings when background/locking screen.
- Verified adding videos to playlist works and user is able to open video in playlist.

https://github.com/brave/brave-ios/assets/17885425/94551ae9-70f7-44f9-81a5-8146ec162459

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPhone 12` running `iOS 16.6` using `1.56 (23.8.4.21)` on the `Dev` channel

Using the STR/Cases outlined via https://github.com/brave/brave-ios/issues/7831#issue-1837242125, reproduced the original issue that @SergeyZhukovsky mentioned as per https://github.com/brave/brave-ios/issues/7831#issuecomment-1666168271 before running through the verifications mentioned below.

* ensured that the original issue isn't occurring re: media YT media still playing when closing the tab
* ensured that audio is being played in the background when `Enable Background Audio` is enabled via the lock screen
* ensured that audio is being played in the background when Brave is backgrounded and another app is being used
* ensured that the background audio stops when Brave is closed while `Enable Background Audio` is enabled
  * ensured starting the browser again didn't automatically play the previous video that was being played before closing Brave
* ensured that you can add videos from YT into `Playlist` without any issues
* ensured that the audio is **NOT** not being played when switching tabs while `Enable Background Audio` is **disabled**
* ensured that the audio is **NOT** not being played when backgrounding Brave while `Enable Background Audio` is **disabled**

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using `1.56 (23.8.4.21)` 

- Ensured background play works when backgrounding app or locking device screen on fresh & existing profile.
- Ensured media does not play in background when background play is disabled in Media settings menu.
- Ensured background play preference is retained when upgrading to 1.56.
- Ensured adding YT videos and other media to playlist works and user is able to view media in playlist. 
- Ensured Playlist onboarding tutorial is shown and user is able to complete the flow or dismiss the tutorial.
- Ensured closing tab will stop audio when background play is enabled (STR: https://github.com/brave/brave-ios/issues/7831#issue-1837242125)
