### ISSUE TITLE
Restored but unopened tabs not added to Recently Closed Tabs

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7832]
### Description: 

Tabs that have been restored, but not opened yet are not added to Recently Closed Tabs list when 

### Steps to Reproduce 
  1. Open 2 or more tabs
  2. Fully quit Brave from app switcher
  3. Open Brave
  4. Tap and hold on tab tray button and tap `Recently Closed Tabs`
  5. Clear list if not empty (not required, but easier to see bug)
  6. Tap and hold on tab button, tap `Close All n Tabs`
  7. Tap and hold on tab tray button and tap `Recently Closed Tabs`
  8. Observe only the active tab is added

### Actual result: 

https://github.com/brave/brave-ios/assets/5314553/b765915d-41a4-4566-b65c-bfb07dc8ec45

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

I am not overly familiar with Recently Closed Tabs code, but if I had to guess it's because the `Tab` url is nil in this case. You can get the url via `SessionTab.from(tabId: id)?.url`:
https://github.com/brave/brave-ios/blob/development/Sources/Brave/Frontend/Browser/BrowserViewController/BrowserViewController%2BWallet.swift#L173-L180

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.0]
Brave build: 1.57 (23.8.28.18)
BraveCore: 1.57.53 (116.0.5845.114)
```
---------------------------

**STEPS:**
Followed the steps from https://github.com/brave/brave-ios/issues/7832#issue-1837308834

**ACTUAL RESULTS:**
- Verified that restored but not opened yet tabs are added to `Recently Closed Tabs` list
- Verified that it's possible to restore tabs from `Recently Closed Tabs` list

---------------------------

https://github.com/brave/brave-ios/assets/128532965/820e6825-ab34-46d4-9d3c-450cb4ff7805
