### ISSUE TITLE
[hackerone] Add `Suppress` button to `Allow link to switch apps?` pop-up

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-ios#7835]
https://hackerone.com/reports/2098015

**Comment by diracdeltas** [comment]
@iccub any updates here?

**Comment by iccub** [comment]
We target 1.58 for this one. We will start working on it soon

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.58 (23.10.4.11)`

Feature was verified following the test plan in https://github.com/brave/brave-ios/pull/8048#issue-1891160653 as well as updated criteria in https://github.com/brave/brave-ios/pull/8048#issuecomment-1716076444 as shown below

**_Acceptance Criteria_**

1. First and second prompt - we show the user Allow link to switch app message as before.
2. On third and all consecutive prompts - we SWAP the "Dont Allow" button with "Suppressed Alerts" for all the next prompts on this page.
3. The counter should reset if the user reloads the page and different URL should reset values

**_Test Results_**

- Ensured first and second prompt will show the normal allow link to switch app. 
- Ensured `Suppress` button is shown on the third consecutive attempt when triggering `Allow link to switch apps` prompt.
- Ensured `Allow link to switch apps` is not shown after suppressing. Opening tab view will also not resume them to be
shown after suppression as observed here - https://github.com/brave/brave-ios/pull/8048#issuecomment-1724038447
- Ensured that closing tab or visiting different URL will reset the counter

Example | Example | Example
-|-|-
![IMG_3571](https://github.com/brave/brave-ios/assets/17885425/7ab59e6e-82fe-4a5f-a23b-5a28a1fd2119) | ![IMG_3569](https://github.com/brave/brave-ios/assets/17885425/f5c0bcb8-e24e-4fac-8538-406e0c8f1ab4) | ![IMG_3570](https://github.com/brave/brave-ios/assets/17885425/d546d69a-9362-4dd8-849f-7619813f50a4)

**Comment by soner-yuksel** [comment]
This issue needs to be tested again in 1.61 along side with https://github.com/brave/brave-ios/issues/8494

**Comment by Uni-verse** [comment]
Verified on `iPhone X` and `iPhone 12` running `iOS 16.7` and `iOS 17.1.1` respectively using version `1.61 (23.12.23.17)`

- Verified Acceptance Criteria / test plan in https://github.com/brave/brave-ios/issues/7835#issuecomment-1751332845
- Verified universal links are opening in external apps.
- Verified links in browser are opening in external apps by default.
- Verified links in browser are opened in new tab when `Allow universal links to open in external apps` is disabled.

Encountered: https://github.com/brave/brave-ios/issues/8563

Allow to switch prompt | Suppress button | Opening link | Mail app | Opened Mail app link (default) | Internal Link | Opened internal link
-|-|-|-|-|-|-
![IMG_3671](https://github.com/brave/brave-ios/assets/17885425/e50e20ca-ec47-4f20-8654-eb8db892a8ea) | ![IMG_3672](https://github.com/brave/brave-ios/assets/17885425/ff4a4baa-b71b-4277-a2d1-551150647398) | ![IMG_3673](https://github.com/brave/brave-ios/assets/17885425/a304e9a7-8061-4b3b-9633-0971484936e9) | ![IMG_3674](https://github.com/brave/brave-ios/assets/17885425/705b9edb-417c-4d66-a532-ac11e84ce374) | ![IMG_3675](https://github.com/brave/brave-ios/assets/17885425/700d77d3-3fb5-4f08-b579-6047ad09d356) | ![IMG_3677](https://github.com/brave/brave-ios/assets/17885425/f83538bb-5f23-482c-a4de-59eea2a5c44e) | ![IMG_3678](https://github.com/brave/brave-ios/assets/17885425/0632792a-6604-4ff2-ad76-0e806bf111fb)
