### ISSUE TITLE
Opening of multiple bookmarks shows only last bookmark

### ISSUE THREAD

**Issue by parsd51** [brave/brave-ios#7836]
### Description: 
Opening of multiple bookmarks shows only last bookmark (with wrong header)

### Steps to Reproduce 
  1. Have one or more tabs open, in my example one new tab is open (tab A)
  2. Select bookmarks from icon next to url/input line, or via menu.
  3. Longpress a folder with bookmarks (in my case six)
  4. Press ‘Open all’

### Actual result: 
Tab A’s header is shown along with the last bookmark content in the list. 
A tab on tab A’s header opens all selected tabs with tab A highlighted.

### Expected result:
All six bookmarks should open with the last bookmark in the list active.

### Reproduces how often: [Easily reproduced, Intermittent Issue]
100%

### Brave Version: 
Brave Version 1.56 (23.8.4.21) (released version)

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details: 
Ipad Air 4, IpadOS 16.6

### Website problems only:
- did you check with Brave Shields down? Yes, same problem
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 [iOS 16.6]
- iPad Air [iPadOS 16.5.1]
Brave build: 1.57 (23.8.21.22)
BraveCore: 1.57.47 (116.0.5845.96)
```
---------------------------
<details>
<summary> iPhone - PASS </summary>

**STEPS:**
1. Launch Brave 
2. Three-dot menu > Settings > Find `TABS` section > `Top Bar` is ON > `Tabs Bar` is OFF
3. Go back and open at least 2 tabs
4. Open `Bookmarks` from the button next to the URL search bar or from the Three-dot menu
5. Choose the folder that contains at least 2 saved websites > Tap and hold on it > Open all > Done > Verify
6. Return to `Settings` > Find `TABS` section > `Top Bar` is ON > `Tabs Bar` is ON
7. Repeat Steps 3 - 5 > Verify
8. Return to `Settings` > Find `TABS` section > `Top Bar` is ON > `Tabs Bar` is set to `Landscape Only`
9. Repeat Steps 3 - 5 > Verify
10. Return to `Settings` > Find `TABS` section > `Bottom Bar` is ON > `Tabs Bar` is OFF
11. Repeat Steps 3 - 5 > Verify
12. Return to `Settings` > Find `TABS` section > `Bottom Bar` is ON > `Tabs Bar` is ON
13. Repeat Steps 3 - 5 > Verify
14. Return to `Settings` > Find `TABS` section > `Bottom Bar` is ON > `Tabs Bar` is set to `Landscape Only`
15. Repeat Steps 3 - 5 > Verify

**ACTUAL RESULTS:**
- Verified that the tab header and currently shown tab both are correct
- Verified that all bookmarked tabs are opened, and the last bookmark on the list is on the active tab 

---------------------------

*`Top Bar` is ON > `Tabs Bar` is OFF*

https://github.com/brave/brave-ios/assets/128532965/9f86bf05-63c0-4877-b5e9-291bb67149f0

*`Top Bar` is ON > `Tabs Bar` is ON*

https://github.com/brave/brave-ios/assets/128532965/2f429463-dacc-48fc-8bbc-302678058a3a

*`Top Bar` is ON > `Tabs Bar` is `Landscape Only`*

https://github.com/brave/brave-ios/assets/128532965/8a68cace-ab9d-43e3-adf7-78a2907696c9

*`Bottom Bar` is ON > `Tabs Bar` is OFF*

https://github.com/brave/brave-ios/assets/128532965/d276b6d7-8cdd-4184-9439-71d394fa46d5

*`Bottom Bar` is ON > `Tabs Bar` is ON*

https://github.com/brave/brave-ios/assets/128532965/c289dd0c-342d-4bd2-9f8a-ed5489aff000

*`Bottom Bar` is ON > `Tabs Bar` is `Landscape Only`*

https://github.com/brave/brave-ios/assets/128532965/e45c9a5a-f596-4072-8a1d-eefcc05c58b5

</details>

<details>
<summary> iPad - PASS </summary>

**STEPS:**
1. Launch Brave 
2. Three-dot menu > Settings > Find `TABS` section > Make sure `Tabs Bar` is ON
3. Go back and open at least 2 tabs
9. Open `Bookmarks` from the button next to the URL search bar or from the Three-dot menu
16. Choose the folder that contains at least 2 saved websites > Tap and hold on it > Open all > Done > Verify
17. Now open `Settings` again > `TABS` section > Turn OFF `Tabs Bar`
18. Repeat Steps 3 - 5 > Verify

**ACTUAL RESULTS:**
- Verified that the tab header and currently shown tab both are correct
- Verified that all bookmarked tabs are opened, and the last bookmark on the list is on the active tab 

---------------------------

*`Tabs Bar` is ON*

https://github.com/brave/brave-ios/assets/128532965/439234f5-b612-42e4-87d5-18a3df5783dd

*`Tabs Bar` is OFF*

https://github.com/brave/brave-ios/assets/128532965/73ff9870-e782-46ef-bad8-7604a4165d3c

</details>
