### ISSUE TITLE
Crash in BraveAds::inlineContentAdsWithDimensions

### ISSUE THREAD

**Issue by aseren** [brave/brave-ios#7837]
### Steps to Reproduce 
- Run Brave on iOS with a fresh profile.
- Join Brave Rewards.
- Join Brave Today
- Scroll a news feed until an Ad is shown

Brave Core version is 1.57.x.
The corresponding brave core issue: https://github.com/brave/brave-browser/issues/32091

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 [iOS 17.0]
- iPad Air [iPadOS 16.5.1]
Brave build: 1.57 (23.8.28.18)
BraveCore: 1.57.53 (116.0.5845.114)
```
---------------------------

**STEPS:**
Followed the steps from https://github.com/brave/brave-ios/issues/7837#issue-1839926594

**ACTUAL RESULTS:**
- Verified that Brave is not crashing when Rewards and Brave News are enabled

---------------------------

*iPhone*

https://github.com/brave/brave-ios/assets/128532965/150acd22-bc28-4481-91ec-bf68f5d533b8

*iPad*

https://github.com/brave/brave-ios/assets/128532965/b89d6833-6ebb-456a-b0ba-4c8f9696d663
