### ISSUE TITLE
Private Stats background not showing on NTP

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#7844]
### Description: 
- Private Stats background no longer shows on NTP:

### Steps to Reproduce 
  1. View NTP in regular mode

### Actual result: 
![image](https://github.com/brave/brave-ios/assets/1530031/79af72cc-9e8f-42cf-9894-643f82432fea)

### Expected result:
<img width="267" alt="image" src="https://github.com/brave/brave-ios/assets/1530031/db9eaedd-223d-4f57-aba1-c992da493596">

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily reproduced

### Brave Version: 
- 1.57.x

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using version `1.57 (23.8.18.20)`

- Ensured Private Stats background is shown on NTP on fresh profile.
- Ensured user is able to hide/show the Stats on NTP in `New Tab Page` settings.
- Ensured stats background is shown when upgrading from 1.56.x -> 1.57x.

Fresh Profile | Existing Profile | Private Tab
-|-|-
![IMG_3473](https://github.com/brave/brave-ios/assets/17885425/495ae83a-6fac-464f-a004-6ca2a973b648) | ![IMG_3476](https://github.com/brave/brave-ios/assets/17885425/d9cd7a42-15d6-4dc7-82b3-637b472d536d) | ![IMG_3475](https://github.com/brave/brave-ios/assets/17885425/4cf218f1-0197-47db-8caf-d14b6a360f20)
