### ISSUE TITLE
Rewards/Ads can't be disabled

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#7846]
### Description: 

Rewards/Ads can't be disabled via the Rewards panel in 1.57+

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using version `1.57 (23.8.18.20)`

<details><summary>Case: Fresh Profile</summary>

- Ensured Brave Rewards toggle can be disabled via the panel after enabling on fresh profile.
- Ensured Toggle in Brave Rewards menu can be disabled.

Example | Example
-|-
![IMG_3464 2](https://github.com/brave/brave-ios/assets/17885425/32ea1d80-0f00-4c1c-8cb2-3e6836f57b9c) | ![IMG_3465 2](https://github.com/brave/brave-ios/assets/17885425/05a432ee-651f-4d12-b30e-357592290f9e)

</details>

<details><summary>Case Existing Profile</summary>

- Ensured Brave Rewards toggle can be disabled after enabling Rewards on 1.56.x and then upgrading to 1.57.x
- Ensured Brave Rewards toggle can be disabled if Rewards was enabled after upgrading to 1.57.x.

</details>
