### ISSUE TITLE
Update Sync Local Authentication Logic

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#7849]
### Description: 
Linked to https://github.com/brave/brave-ios/issues/7436
Slack: https://bravesoftware.slack.com/archives/C0816QH3R/p1689972393401329?thread_ts=1685503730.825809&cid=C0816QH3R

Please update the logic when showing the PIN as follows

- Request a PIN/Biometrics when the user decides to sync All or Passwords
- Request a PIN/Biometrics when the user wants to add new device to sync

1. ask for auth when user toggle password-sync option or wants to add a device to sync
2. if no auth enabled at all you are not allowed to disable or enable password sync
3. If no auth set up when you tap on the password sync toggle show user an alert that they need to enable pincode/faceid. 

And take the user to iOS settings, or privacy settings if possible
Use the current lockscreen UI, alert should be shown for point 3

**Comment by iccub** [comment]
per discussions on slack we will show the lockscreen only when password sync is toggled.
and if no authentication set up we will show the user a prompt telling them to enable it first

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1`

<details><summary>Case: New Profile - Main flow</summary>

- Ensured creating sync chain using sync settings menu.
- Ensured adding a new device does not require authentication when creating sync chain.
- Ensured password sync and Add New Device are behind authentication.

Example | Example | Example | Example | Example
-|-|-|-|-
![Screenshot 2023-08-22 at 1 49 54 PM](https://github.com/brave/brave-ios/assets/17885425/0ee39287-ebda-4f9e-942e-9198046e1873) | ![Screenshot 2023-08-22 at 1 50 05 PM](https://github.com/brave/brave-ios/assets/17885425/672a0a7d-edd8-4e0a-a413-9e3e175f6e56) | ![Screenshot 2023-08-22 at 1 50 24 PM](https://github.com/brave/brave-ios/assets/17885425/fa8a27d7-ca74-4f38-a4fa-777aef47123f) | ![Screenshot 2023-08-22 at 1 50 31 PM](https://github.com/brave/brave-ios/assets/17885425/c71a007a-fbe6-49f4-9196-bdaa782817f9) | ![Screenshot 2023-08-22 at 1 52 42 PM](https://github.com/brave/brave-ios/assets/17885425/a4bdfd8e-e207-4174-af79-11b67d48a2bd)


</details>

<details><summary>Case: New Profile - Segmented Tab flow</summary>

- Ensured creating sync chain through the `Tabs from Other Devices` flow.
- Ensured adding a new device does not require authentication when creating sync chain.
- Ensured password sync and Add New Device are behind authentication.

Example | Example | Example | Example | Example
-|-|-|-|-
![Screenshot 2023-08-23 at 5 35 26 PM](https://github.com/brave/brave-ios/assets/17885425/f4588fb9-4984-4a4b-8122-d407890e0cda) | ![Screenshot 2023-08-23 at 5 35 34 PM](https://github.com/brave/brave-ios/assets/17885425/41d83b81-937d-4db7-9cf8-b4df1e377e31) | ![Screenshot 2023-08-23 at 5 35 46 PM](https://github.com/brave/brave-ios/assets/17885425/98eab295-7da6-44b7-bc20-3172f26cefdd) | ![Screenshot 2023-08-23 at 5 36 11 PM](https://github.com/brave/brave-ios/assets/17885425/e6ab7d9c-9be9-45f6-a269-a6000c7c45e9) | ![Screenshot 2023-08-23 at 5 41 13 PM](https://github.com/brave/brave-ios/assets/17885425/2d28ae3b-ed71-4293-97b4-d08036341196)

</details>

<details><summary>Case: Existing Profile - Sync chain exists</summary>

- Ensured created sync chain exists after upgrading.
- Ensured adding new device as well as password sync is behind authentication.
- Ensured user is able to add a new device.
- Ensured open tabs sync is working in Other Devices Segmented Tab.

</details>

<details><summary>Case: Existing Profile - No sync chain</summary>

- Ensured creating sync chain works using main flow
- Ensured creating sync chain works using `Tabs from Other Devices` flow
- Ensured Add New Device & Password sync require authentication

</details>

<details><summary>Case: System Auth not set up</summary>

- Verified message is displayed to user to setup authentication before using password sync & Add New Device features.

![IMG_3483](https://github.com/brave/brave-ios/assets/17885425/60f48a00-8e48-417d-9895-abeb3c658ed8)

</details>

<details><summary>Case: Enabling feature after setting up authentication in system</summary>

- Verified Password sync and Add New Device function requires authentication to be setup on the device.
- Verified setting up passcode on device will allow Password Sync and Add New Device to work.

![IMG_3483](https://github.com/brave/brave-ios/assets/17885425/60f48a00-8e48-417d-9895-abeb3c658ed8)

</details>

<details><summary>Case: Using Sync authentication with Private Tab FaceID enabled</summary>

- Verified adding new device and using password sync when Private Tab PIN is enabled.

Example | Example | Example
-|-|-
![IMG_3481](https://github.com/brave/brave-ios/assets/17885425/f91f8d3e-7add-44fb-8504-17e5921dd759) | ![IMG_3482](https://github.com/brave/brave-ios/assets/17885425/588007e8-0b96-4ce1-a18a-422192b65a8e) | ![IMG_3481](https://github.com/brave/brave-ios/assets/17885425/743326a5-ba91-46b7-9ef3-290720e42ffc)

</details>

<details><summary>Case: Using Sync Auth with Browser Lock enabled</summary>

- Verified adding new device and using password sync when Browser Lock is enabled.

![IMG_3484](https://github.com/brave/brave-ios/assets/17885425/95f8785d-1846-45fa-9a38-607c732ddffb)

</details>

Issues Encountered:
https://github.com/brave/brave-ios/issues/7911

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iPadOS 16.5.1`

<details><summary>Case: New Profile - Main flow</summary>

- Ensured creating sync chain using sync settings menu.
- Ensured adding a new device does not require authentication when creating sync chain.
- Ensured password sync and Add New Device are behind authentication.
- Ensured entering passcode works if FaceID is disabled or entered incorrectly.

Example | Example | Example | Example | Example | Example | Example
-|-|-|-|-|-|-
![Screenshot 2023-08-23 at 1 58 31 PM](https://github.com/brave/brave-ios/assets/17885425/ce2f840d-0874-4602-95be-5cb5afde0e87) | ![Screenshot 2023-08-23 at 1 58 40 PM](https://github.com/brave/brave-ios/assets/17885425/74e8c15b-830b-4e9a-889c-e4e2a9edf8df) | ![Screenshot 2023-08-23 at 1 58 47 PM](https://github.com/brave/brave-ios/assets/17885425/828c84fe-f517-49e1-ae68-1fb8f449619b) | ![Screenshot 2023-08-23 at 1 59 31 PM](https://github.com/brave/brave-ios/assets/17885425/0c0db7e0-b931-4155-bb4c-fc40b945e131) | ![Screenshot 2023-08-23 at 1 59 44 PM](https://github.com/brave/brave-ios/assets/17885425/c3697125-50a2-4a68-b261-fe7d7d30bbfb) | ![Screenshot 2023-08-23 at 2 00 00 PM](https://github.com/brave/brave-ios/assets/17885425/5549a530-3ea0-4cc1-a0bd-f173a5e0797d) | ![Screenshot 2023-08-23 at 2 00 17 PM](https://github.com/brave/brave-ios/assets/17885425/f5da6f58-3a75-41a0-a67e-27201eb99cd9)

</details>

<details><summary>Case: New Profile - Segmented Tab flow</summary>

- Ensured creating sync chain through the `Tabs from Other Devices` flow.
- Ensured adding a new device does not require authentication when creating sync chain.
- Ensured password sync and Add New Device are behind authentication.

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![Screenshot 2023-08-24 at 12 14 31 PM](https://github.com/brave/brave-ios/assets/17885425/77943f2c-766c-4251-bd17-1fe73da7b2c1) | ![Screenshot 2023-08-24 at 12 14 39 PM](https://github.com/brave/brave-ios/assets/17885425/bba9db56-cfee-48c5-95e4-124a36f278a3) | ![Screenshot 2023-08-24 at 12 14 47 PM](https://github.com/brave/brave-ios/assets/17885425/1b3a42c4-3c68-4942-b557-de5cf790a74d) | ![Screenshot 2023-08-24 at 12 14 53 PM](https://github.com/brave/brave-ios/assets/17885425/a066cd8c-ad8b-4405-8da5-a83908d09676) | ![Screenshot 2023-08-24 at 12 15 25 PM](https://github.com/brave/brave-ios/assets/17885425/815b6d7c-53d2-4a74-ad0f-b04206172d5a) | ![Screenshot 2023-08-24 at 12 15 33 PM](https://github.com/brave/brave-ios/assets/17885425/b463d838-43c5-4ef7-88f0-b0f52fd2ac78)

</details>

<details><summary>Case: Existing Profle - Sync chain exists</summary>

- Ensured created sync chain exists after upgrading.
- Ensured adding new device as well as password sync is behind authentication.
- Ensured user is able to add a new device.
- Ensured open tabs sync is working in Other Devices Segmented Tab.

</details>

<details><summary>Case: Existing Profile - No sync chain</summary>

- Ensured creating sync chain works using main flow
- Ensured creating sync chain works using `Tabs from Other Devices` flow
- Ensured Add New Device & Password sync require authentication

</details>

<details><summary>Case: Using Sync authentication with Private Tab FaceID enabled</summary>

- Verified adding new device and using password sync when Private Tab PIN is enabled.

Example | Example | Example
-|-|-
![Screenshot 2023-08-24 at 12 19 56 PM](https://github.com/brave/brave-ios/assets/17885425/4a7f66d7-1eed-47fa-8e59-2d7a34a84899) | ![Screenshot 2023-08-24 at 12 20 23 PM](https://github.com/brave/brave-ios/assets/17885425/94884818-4466-40f3-8bee-4d438bc345cb) | ![Screenshot 2023-08-24 at 12 20 47 PM](https://github.com/brave/brave-ios/assets/17885425/8cff653d-bc28-4cf8-b79c-199565a8b2f0)

</details>

<details><summary>Case: Using Sync Auth with Browser Lock enabled</summary>

- Verified adding new device and using password sync when Browser Lock is enabled.

Example | Example
-|-
![Screenshot 2023-08-24 at 12 20 47 PM](https://github.com/brave/brave-ios/assets/17885425/cc7b97e8-d594-4448-80a4-5a86778c6513) | ![Screenshot 2023-08-24 at 12 21 42 PM](https://github.com/brave/brave-ios/assets/17885425/df70b51f-5980-4e3a-afda-469283044e90)

</details>

Issues Encountered:
https://github.com/brave/brave-ios/issues/7911
