### ISSUE TITLE
Tab selection for TabsBar interface is done after active website is loaded

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#7851]
### Description: 

The selection of active tab is done after current site is loaded and this creates a a very bad looking visual while loading. In addition to the bad animation, if the internet speed is slow the selection is done until resources are loaded so it seems like it is stuck.

### Steps to Reproduce 
  1. Enable Tabs Bar
  2. Load multiple tabs (+10 tabs etc)
  3. Remove the app from background if it is active
  4. Launch fresh
  5. Observe the active tab is selected after website is loaded

### Actual result: 

https://github.com/brave/brave-ios/assets/6643505/4041157b-b1b7-49b3-a49a-e6c6f5327485

The active tab is selected after website is loaded

### Expected result:

The active tab should be selected before any loading happens

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? YES

### Device details: 
Any

### Website problems only:
- did you check with Brave Shields down? N-A
- did you check in Safari/Firefox (WkWebView-based browsers)? N-A

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.0]
Brave build: 1.58 (23.9.19.14)
BraveCore: 1.58.124 (117.0.5938.62)
```
---------------------------

**STEPS:**
Followed the steps from https://github.com/brave/brave-ios/issues/7851#issue-1842117558

**ACTUAL RESULTS:**
- Verified that the active tab is selected before any loading happens

---------------------------

https://github.com/brave/brave-ios/assets/128532965/f5d18da9-79ea-4e7c-b756-669479fd37ec
