### ISSUE TITLE
Add 'Private tabs' settings section

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7855]
Under Tabs section.
It will have two settings: private tabs persistence and biometric unlock

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using app version `1.57 (23.8.18.16)`

<details><summary>Case: Fresh Profile</summary>

- Verified Test Plan in https://github.com/brave/brave-ios/pull/7868#issue-1845883601.
- Ensured enabling private mode lock will prompts user to authenticate.
- Ensured disabling `Require Face ID` toggle and enabling `Browser lock` setting still works. 
- Ensured user is able to enter passcode to unlock private tabs when face id fails.
- Ensured user is able to cancel authentication.
- Ensured disabling `Keep Private Tabs` toggle will close all private tabs.
- Ensured that Private tabs are not cleared if switching tab mode or exiting browser when `Keep Private Tabs` enabled

Example | Example | Example | Example
-|-|-|-
![Screenshot 2023-08-18 at 4 20 07 PM](https://github.com/brave/brave-ios/assets/17885425/f2810c53-88d6-445f-bada-bf4831e9d7dd) | ![Screenshot 2023-08-18 at 4 20 25 PM](https://github.com/brave/brave-ios/assets/17885425/01883b50-bd22-4b5f-a62d-babd0747aa98) | ![Screenshot 2023-08-18 at 4 20 45 PM](https://github.com/brave/brave-ios/assets/17885425/6ae59b85-6cac-48ce-9a1f-e7b6148026d2) | ![Screenshot 2023-08-18 at 4 23 09 PM](https://github.com/brave/brave-ios/assets/17885425/cbb1f385-71c1-4ec5-beb9-f66f7b3bb783)

</details>

<details><summary>Case: Existing Profile</summary>

- Verified Test Plan in https://github.com/brave/brave-ios/pull/7868#issue-1845883601.
- Ensured enabling private mode lock will prompts user to authenticate on existing profile.
- Ensured user is able to enter passcode to unlock private tabs when face id fails.
- Ensured disabling `Require Face ID` toggle and enabling `Browser lock` setting still works. 
- Ensured user is able to cancel authentication.
- Ensured disabling `Keep Private Tabs` toggle will close all private tabs.
- - Ensured that Private tabs are not cleared if switching tab mode or exiting browser when `Keep Private Tabs` enabled

</details>

<details><summary>Case: Private tab entry points</summary>

- Ensured opening private tab works from NTP works
- Ensured opening private tab works using + works
- Ensured opening private tab works from promo widget
- Ensured opening private tab works from widgets on lockscreen
- Ensured opening private tabs works from iOS home screen
- Ensured opening articles on news widget in private tab when enabled

</details>

<details><summary>Case: Browser Lock enabled</summary>

- Ensured disabling `Require Face ID` toggle and enabling `Browser lock` setting still works. 
- Ensured enabling both Require Face ID and Browser Lock will require authentication for both launching browser and private tabs access.

</details>

<details><summary>Case: Private Browsing Mode</summary>

- Verified activating Private Browsing will remove the Private Tabs setting menu

</details>
