### ISSUE TITLE
1.51 migration crash when lot of tabs are open

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7857]
### Steps to Reproduce 
  1. Install a 1.50 build.
  2. Add a lot of tabs. On dev builds go to settings and scroll down tap 'add 1000 tabs' once or twice
  3. Upgrade to 1.51 or newer

### Actual result: 
The app will freeze for 20 seconds then crash

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by hffvld** [comment]
Verified on `iPhone 14`using version(s):
```
Device/OS: iPhone 14 [iOS 16.6]
Brave build: 1.57 (23.8.18.20)
BraveCore: 1.57.47 (116.0.5845.96)
```
---------------------------
<details>
<summary> Upgrade 1.50 to 1.51 - PASS </summary>

**STEPS:**
Followed the steps from https://github.com/brave/brave-ios/pull/7865#issue-1845321379

**ACTUAL RESULTS:**
- Verified that Brave is not freezing or crashing when a lot of tabs (1000 - 2000) are opened

---------------------------

*1000 tabs*

https://github.com/brave/brave-ios/assets/128532965/f12fdd82-f243-4075-a311-b3415210fc07

*2000 tabs*

https://github.com/brave/brave-ios/assets/128532965/ee317a66-8d8a-4af2-b520-aabed5d49fca

</details>

<details>
<summary> Upgrade 1.56 to 1.57 - PASS </summary>

**STEPS:**
Followed the steps from https://github.com/brave/brave-ios/pull/7865#issue-1845321379

**ACTUAL RESULTS:**
- Verified that Brave is not freezing or crashing when a lot of tabs (1000 - 2000) are opened

---------------------------

*1000 tabs*

https://github.com/brave/brave-ios/assets/128532965/322cd9da-2a10-4fbb-9953-86cdc45f3d65

*2000 tabs*

https://github.com/brave/brave-ios/assets/128532965/2c1b587a-0a76-4441-810c-58f7145f8a4c

</details>
