### ISSUE TITLE
Add query param stripping

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#7861]
### Description: 
We need to implement query param stripping in iOS. Most of the logic is found in brave-core

### Test plan
1. Test all links on the following page: https://fmarier.github.io/brave-testing/query-filter.html
2. Test all links on the following page: https://fmarier.org/query-filter-test.html (It should also pass the tests that claim that "Don't work as expected"). In this page, trackers such as `fbclid` should be removed on all pages.
3. Make sure that back and forward works fine as well on some of these links. There shouldn't be any strangenesses with using back and forward buttons while navigating these links.

**Comment by Uni-verse** [comment]
**Verified** on `iPad (7th Gen)` running `iPadOS 16.5.1` using version `1.57 (23.8.28.22)`

- Ensured all test links work as expected in https://fmarier.github.io/brave-testing/query-filter.html.
- Ensured all test links work as expected in https://fmarier.org/query-filter-test.html.
- Ensured navigating back and forward doesn't cause any issues with the page load.

Example | Example | Example
-|-|-
![IMG_1178](https://github.com/brave/brave-ios/assets/17885425/e7a5354a-c830-423a-b515-509d249ce4e2) | ![IMG_1179](https://github.com/brave/brave-ios/assets/17885425/f34b289f-da50-4bc9-86de-3d2d1390efc6) | ![IMG_1182](https://github.com/brave/brave-ios/assets/17885425/b7c58b10-2189-488f-bf6c-1c4929b34f05)
![IMG_1183](https://github.com/brave/brave-ios/assets/17885425/2eba81b4-8d73-4dc3-b77a-ff1c957965e3) | ![IMG_1184](https://github.com/brave/brave-ios/assets/17885425/3dcd4aaa-45ca-4e39-aa9c-1d66c2e32a36) | ![IMG_1185](https://github.com/brave/brave-ios/assets/17885425/af8b09c2-0915-467d-88f3-c91c7296b190)
