### ISSUE TITLE
Removing Bookmark using toggle button doesn't send it to Sync server

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#787]
### Steps to Reproduce 
  1. Save bookmark
  2. Open Settings
  3. Toggle the bookmark button to delete bookmark
  1. Deletion is not synced

**Actual result:** 

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by LaurenWags** [comment]
* Verified passed with 1.9 (19.3.9.1) on iPad 5th Gen
  * Verified STR from description (deleting via bookmark toggle button) also verified deleting bookmark via edit mode
  * Verified for bookmarks in folders also.
* Verified passed with 1.9 (19.3.9.1) on iPhone SE using the test plan from the description. Also checked when deleting bookmark through edit mode.
* Verified passed with 1.9 (19.3.9.1) on iPhone 8
  * Verified STR from the description (deleting via bookmark toggle button) also verified deleting bookmark via edit mode
  * Verified for bookmarks in folders also.
* Verification passed on iPhone 7+/6 and iPad Pro running 1.9(19.3.9.1)
  - Verified bookmark deletion is sync'd 
  - Verified bookmark folder deletion is sync'd
  - Verified edit-> delete bookmark also syncs changes 
* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR.
  - Verified bookmark deletion is sync'd 
  - Verified bookmark folder deletion is sync'd
  - Verified edit-> delete bookmark also syncs changes
