### ISSUE TITLE
iPad YouTube Bug

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#7871]
### Description: 
https://bravesoftware.slack.com/archives/C06UXF3KJ/p1691785809666409

Noticing an issue on Brave release on iPad Version 1.56 (23.8.4.21) where if I load a YouTube video and close the tab, it continues to play.

**Comment by Brandon-T** [comment]
Fixed in: https://github.com/brave/brave-ios/pull/7833

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 [iOS 17.0]
- iPad Air [iPadOS 16.5.1]
Brave build: 1.58 (23.9.19.14)
BraveCore: 1.58.124 (117.0.5938.62)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Open https://youtube.com
3. Start playing a video
4. Close the YT tab > Verify

**ACTUAL RESULTS:**
- Verified that the YT video stopped playing as soon as the YT tab was closed

---------------------------

*iPad*

https://github.com/brave/brave-ios/assets/128532965/d742cf82-0e18-45e6-aabd-06bc0c9a2c9f

*iPhone*

https://github.com/brave/brave-ios/assets/128532965/984c22f6-83d0-4557-8558-69c24e02ccd7
