### ISSUE TITLE
Malformed URLs for i.redd.it posts when using the reddit.com -> old.reddit.com website redirect

### ISSUE THREAD

**Issue by F-Smith** [brave/brave-ios#7873]
### Description: 
I recently noticed that when clicking on images in subreddits that are hosted on the `i.redd.it` domain, Brave loads up a random post on `reddit.com/r/funny` instead of the image I clicked on...

Upon closer inspection, I see that the post URL gets appended to this URL `https://old.reddit.com/r/funny/comments/media/nice_hat/` as a query string.

For example, if you click on a post `https://i.redd.it/05cnhtc5yo331.jpg` it will incorrectly form the URL as: `https://old.reddit.com/r/funny/comments/media/nice_hat/?url=https%3A%2F%2Fi.redd.it%2F05cnhtc5yo331.jpg`

### Steps to Reproduce 
  1. Open the Brave iOS browser
  2. Enable the `reddit.com` -> `old.reddit.com` redirect (Settings -> Website Redirect)
  3. Go to a subreddit, e.g. `https://old.reddit.com/r/AccidentalRenaissance/`
  4. Select a post where after the post title, it says `(i.redd.it)`
  5. Click on either the image thumbnail or the post title.
  6. Observe how you end up on an entirely different URL of `/r/funny/comments/media/nice_hat`

### Expected result:
- I should see the image of the post I've clicked on.

### Reproduces how often:
Easily reproduced whenever I click on a post with the `(i.redd.it)` domain after the post title

### Brave Version:
Version v1.56 (23.8.4.21)

- Can you reproduce this issue with the current build from AppStore? **Yes**

### Device details:
iOS 16.5.1

### Website problems only:
- did you check with Brave Shields down? **Yes, issue persists**
- did you check in Safari/Firefox (WkWebView-based browsers)? **Yes, issue doesn't exist**

### Additional Information
- Only seems to apply to image assets hosted on i.redd.it
- Doesn't affect video assets hosted on v.redd.it
- If you want to workaround this bug and still get to the post URL, you need to click on the number of comments next to the post instead of the post title or thumbnail.

**Comment by kylehickinson** [comment]
Looks like Reddit changed the way they load `i.redd.it` links… we'll have to see if there's a way to get around this without additional replacement logic 

For investigation sake:

- `i.redd.it/{id}` redirects to
- `reddit.com/media?url={iredditurl}` which we rewrite as
- `old.reddit.com/media?url={iredditurl}` 

Unfortunately the final destination is not handled as a media lookup and instead is handled as a legacy post lookup, it just so happens that this "nice hat" post has a post ID of `media`…

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.6]
Brave build: 1.57 (23.8.18.20)
BraveCore: 1.57.47 (116.0.5845.96)
```
---------------------------
<details>
<summary> Upgraded profile - PASS </summary>

**STEPS:**
Follow the steps from https://github.com/brave/brave-ios/issues/7873#issue-1848494384

**ACTUAL RESULTS:**
- Verified that the proper picture is opened when `reddit.com` > `old.reddit.com` redirect is enabled

---------------------------

https://github.com/brave/brave-ios/assets/128532965/d0c1f1d2-60d9-4149-a47f-ccbaefab4ca8

</details>

<details>
<summary> Fresh install - PASS </summary>

**STEPS:**
Follow the steps from https://github.com/brave/brave-ios/issues/7873#issue-1848494384

**ACTUAL RESULTS:**
- Verified that the proper picture is opened when `reddit.com` > `old.reddit.com` redirect is enabled

---------------------------

https://github.com/brave/brave-ios/assets/128532965/ba64f825-6236-4e85-ae36-21666c8e73fe

</details>
