### ISSUE TITLE
Replace "ads enabled duration" P3A metric with "ad types enabled" 

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-ios#7876]
Replace `Brave.Rewards.AdsEnabledDuration` with `Brave.Rewards.AdTypesEnabled`.

If you have rewards enabled, which ad types do you have enabled?

0. None
1. NTP only
2. Push only
3. NTP + Push

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.1]
Brave build: 1.58 (23.10.6.14)
BraveCore: 1.58.139 (117.0.5938.153)
```
---------------------------

**STEPS:**
1. Fresh install `Dev build`
2. Launch Brave and go through onboarding
3. Open `Settings` > View Brave Histogram (p3a) Logs > Confirm that `Brave.Rewards.AdsEnabledDuration` is not shown > Verify
4. Return to `Settings` > New tab page > Image type > Set to `Default images`
5. Return to `Settings` > View Brave Histogram (p3a) Logs > Verify
6. Return to `Settings` > New tab page > Image type > Set to `Sponsored`
7. Return to `Settings` > View Brave Histogram (p3a) Logs > Verify
8. Return to `Settings` > New tab page > Image type > Set to `Default images` 
9. Return to `Settings` > Brave Rewards > Enable rewards
10. Return to `Settings` > View Brave Histogram (p3a) Logs > Verify
11. Return to `Settings` > New tab page > Image type > Set to `Sponsored` 
13. Return to `Settings` > View Brave Histogram (p3a) Logs > Verify

**ACTUAL RESULTS:**
- Verified that Brave no longer reports `Brave.Rewards.AdsEnabledDuration`, but instead it updated with `Brave.Rewards.AdTypesEnabled`
- Verified that `Brave.Rewards.AdTypesEnabled` report `0` when both `Rewards` and `Sponsored image` are OFF
- Verified that `Brave.Rewards.AdTypesEnabled` report `1` when `Rewards` is OFF but `Sponsored image` is ON
- Verified that `Brave.Rewards.AdTypesEnabled` report `2` when `Rewards` is ON but `Sponsored image` is OFF
- Verified that `Brave.Rewards.AdTypesEnabled` report `3` when both `Rewards` and `Sponsored image` are ON

---------------------------

|After fresh install|`Rewards` and `Sponsored image` is OFF|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/14852f1b-0e27-4de0-9fe8-8b5a85f321b1) | ![2](https://github.com/brave/brave-ios/assets/128532965/6669569c-7559-4e8f-8cf0-069ee5842e4e) |
|`Rewards` is OFF but `Sponsored image` is ON||`Rewards` is ON but `Sponsored image` is OFF|
| ![1](https://github.com/brave/brave-ios/assets/128532965/06f23129-3f39-4ddd-85ab-649822c95035) | ![2](https://github.com/brave/brave-ios/assets/128532965/e9207cb1-695e-4275-9b6d-22c082af2a08) |
|`Rewards` and `Sponsored image` are ON|2|
| ![1](https://github.com/brave/brave-ios/assets/128532965/612d20ea-7d15-4be0-9564-a556d88f4202) | ![2]() |
