### ISSUE TITLE
Occasional inverted colors when searching Brave Search in Night Mode

### ISSUE THREAD

**Issue by pes10k** [brave/brave-ios#7877]
I have night mode enabled on iOS

Sometimes when I search on Brave Search, some of the images in the search results end up inverted, like this
![image](https://github.com/brave/brave-ios/assets/76526/ceef3089-ab74-4166-8273-08b5ee423ae4)

usually if i reload the page though, the images end up presented as normal 
![image](https://github.com/brave/brave-ios/assets/76526/32e87916-ba5e-4895-ab7f-d42b47b3e26b)

Additional details:
1. problem doesn't happen consistently, but happens semi-often for me, a few times a week or so.
1. I haven't noticed any pattern between the search query and whether this problem comes up
1. from looking at the above images, you can see that there are other small differences in the styling of the inverted and not-inverted versions of the pages (for example, some font sizing/width), which makes me think that the problem is markup or a stylesheet being accidentally included / omitted, and not something deeper)

**Comment by BenjaminMichaelis** [comment]
I get this quite frequently.

I have just gone to msn.com just as a sample site to show this occurring. 

I seem to see the issue occur with night mode on brave. Refreshing the page for me does not fix it.

![image](https://github.com/brave/brave-ios/assets/22186029/06d1bf5f-63fa-4c08-9e9d-52e6a00d4151)

https://github.com/brave/brave-ios/assets/22186029/5037be46-b2fe-4fae-99ae-0ce83f992a7d

Version 1.56 (23.8.4.21) BraveCore 1.56.13 (115.0.5790.136) Device iPhone14,2 (iOS 16.6)

**Comment by hffvld** [comment]
Hi @Brandon-T 

I'm still able to reproduce this issue on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.2
Brave build: 1.61 (23.12.11.17)
BraveCore: 1.61.102 (120.0.6099.71)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Open https://msn.com
3. Three-dot menu > Enable `Night Mode` > Observe

--------------------------

|Night mode `Off`|Night mode `On`|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/7b00059c-e394-460f-ad3a-abe582ffe4a2) | ![2](https://github.com/brave/brave-ios/assets/128532965/953bdc7c-e649-47e4-91dc-8b79a2efcf26) |

https://github.com/brave/brave-ios/assets/128532965/d61e6146-eec7-4819-89f3-c13cd22f7d46

**Comment by hffvld** [comment]
Closing this issue in favor of the follow-up issue #8554.
