### ISSUE TITLE
Coinbase on-ramp

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7880]
### Description: 

Support on-ramp from Coinbase in Buy flows.

iOS version of https://github.com/brave/brave-browser/issues/32083

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17 running 1.58 (23.9.20.15)
- Verified steps from [#7985](https://github.com/brave/brave-ios/pull/7985)
- Verified Coinbase is shown as an on-ramp provider for GBP/CAD/EUR/USD
- Verified selecting Coinbase for the above fiat currency loads the Coinbase Pay URL
- Verified Coinbase is not shown as a provider for currencies other than CAD/GBP/EUR/USD

https://github.com/brave/brave-ios/assets/17010094/8c708429-f4e3-49e8-9e38-10b17989c2c7
