### ISSUE TITLE
Browser Lock - Cancel Issue

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#7893]
### Description: 

There is problem with Browser Lock screen logic reported by a user in community forums which doesnt block user from entering browser.

Community Report: https://community.brave.com/t/brave-browser-reuses-password-lock-for-opening-lock-after-accessing-passwords-cancel-button-then-unlocks-browser/501830

### Steps to Reproduce 

1. Make sure your Browser Lock is turned on, and access your saved passwords
2. Go to the iOS home menu, and reopen the app
3. You will now see the interface for the password lock, with the cancel button
4. Press cancel and snoop around on the person’s tabs because this browser’s lock just got bypassed

### Actual result: 

Cancel is presented on main browser lock

### Expected result:

It should not be allowing user to cancel

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
Any

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 16.6]
Brave build: 1.57 (23.8.18.20)
BraveCore: 1.57.47 (116.0.5845.96)
```
---------------------------
<details>
<summary> Upgrade profile - PASS </summary>

**STEPS:**
Followed the steps from https://github.com/brave/brave-ios/issues/7893#issue-1855570119

**ACTUAL RESULTS:**
- Verified that `Cancel` button is not shown and the user is not able to use Brave without unlocking it with a password or biometrics

---------------------------

https://github.com/brave/brave-ios/assets/128532965/d8f1ffdb-fe48-439e-b041-82e6967ecad7

</details>

<details>
<summary> Fresh install - PASS </summary>

**STEPS:**
Followed the steps from https://github.com/brave/brave-ios/issues/7893#issue-1855570119

**ACTUAL RESULTS:**
- Verified that `Cancel` button is not shown and the user is not able to use Brave without unlocking it with a password or biometrics

---------------------------

https://github.com/brave/brave-ios/assets/128532965/6d1f3aa7-aea5-4661-acc5-1de352d35272

</details>
