### ISSUE TITLE
Whitelist twitter on Playlist 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#7896]
### Description: 
Since we launch Playlist, Twitter has become more and more involved in video. Please whitelist twitter.com and possible x.com (if that will be the new URL for Twitter) so users can more easily use Playlist and the Playlist's video playback features on Twitter.

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.58 (23.9.26.21)`

- Ensured that playlist icon appears in URL bar when viewing videos on twitter.com or x.com.
- Ensured that playlist tutorial can be completed when on twitter.com or x.com.
- Ensured that user can add videos using the share menu or by long pressing on video.

_**Playlist on Twitter**_
Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_3538](https://github.com/brave/brave-ios/assets/17885425/c745bf31-36b5-4dec-b285-87f3161f4bfe) | ![IMG_3539](https://github.com/brave/brave-ios/assets/17885425/2fabfc59-f9b8-4e1a-8911-308f85ac5914) | ![IMG_3540](https://github.com/brave/brave-ios/assets/17885425/f0699203-bee0-413a-8920-c3ab954cede5) | ![IMG_3545](https://github.com/brave/brave-ios/assets/17885425/f718bfbe-dfe4-417e-99b6-a091e09bd813) | ![IMG_3546](https://github.com/brave/brave-ios/assets/17885425/ea2b2f2e-f00d-44c0-8ef3-830ba610d898)

**_Playlist Tutorial on Twitter.com / X.com_**

Example | Example | Example
-|-|-
![IMG_3542](https://github.com/brave/brave-ios/assets/17885425/57b4f37a-0f1f-49fa-a782-5224a60cadb6) | ![IMG_3543](https://github.com/brave/brave-ios/assets/17885425/b5210a43-4a20-4ce7-a9f3-e8dcf346ba42) | ![IMG_3544](https://github.com/brave/brave-ios/assets/17885425/3b79ea4b-a47c-418e-bb3d-48115693bc7f)
