### ISSUE TITLE
Favorites overlay leaks through the status bar

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7898]
See https://community.brave.com/t/brave-favourites-favorites-page-is-this-normal/501317

**Comment by kylehickinson** [comment]
This seems to be have been fixed by one of the latest PRs, please re-test in 1.59

**Comment by hffvld** [comment]
Verified on `iPhone 14`using version(s):
```
Device/OS: iPhone 14 / iOS 17.1
Brave build: 1.60 (23.11.4.14)
BraveCore: 1.60.105 (119.0.6045.59)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Add few any websites to a favorite, so their favicons will be shown on `NTP`
3. Scroll through favicons > Verify

**ACTUAL RESULTS:**
- Verified that favicons are not overlaying through the status bar

---------------------------

|Reproduced|Fixed|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/fbef33b2-316e-48ef-9fc4-2f3726a8ba04) | ![2](https://github.com/brave/brave-ios/assets/128532965/8a882603-2db0-4ea6-aa25-2cabd4ba23e0) |
