### ISSUE TITLE
Remove Zip Foundation dependency

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7901]
@kylehickinson found it can be replaced with https://developer.apple.com/documentation/foundation/nsfilecoordinator/1407416-coordinate

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.0]
Brave build: 1.58 (23.9.26.17)
BraveCore: 1.58.129 (117.0.5938.88)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Activate `Rewards`
3. Three-dot menu > Settings
4. Brave Rewards > Rewards Internals
5. Share > Share > Send it with Gmail. for example
6. Check shared file > Verify

**ACTUAL RESULTS:**
- Verified that the user is still able to share a .zip file with a JSON file inside of it

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/570da84c-2fba-4af9-87da-49600993bf86) | ![2](https://github.com/brave/brave-ios/assets/128532965/ee5a14b6-ee14-4d0a-b2aa-0081a2474535) | ![3](https://github.com/brave/brave-ios/assets/128532965/ade11b84-57cc-487c-9c8f-13b17dc4e2c0) | ![4](https://github.com/brave/brave-ios/assets/128532965/7376444c-d05c-489f-9ede-b8dce360c8a5) |

https://github.com/brave/brave-ios/assets/128532965/fde9c1aa-b769-4d81-a7b5-65df00d8039b
