### ISSUE TITLE
Crash switching to Polygon in Swap

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7907]
### Description: 

Crash when switching to Polygon in native Swap after change to use WebImageDownloader from core.

### Steps to Reproduce 
Swap:
  1. Open Swap
  2. Change network to Polygon
  3. Crash
  
Edit User Assets:
1. Open Portfolio and tap Edit User Assets button beside filters button
2. Optional: Change network filter to only have Polygon network selected
3. Scroll down list until crashes

### Actual result: 

Crashes

### Expected result:

Does not crash

### Reproduces how often: 

Easily reproduced

### Brave Version: 

v1.57+

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.57 (23.8.24.22)
- Verified steps from [#7908](https://github.com/brave/brave-ios/pull/7908)
- Verified no crash when selecting Polygon on Swap screen
- Verified no crash when filtering tokens to Polygon network in edit visible asset screen
- Encountered [#7961](https://github.com/brave/brave-ios/issues/7961)

iPhone 7+ (iOS 15.7.8) | iPhone 13 (iOS 16.6) | iPad Pro (iOS 16.6)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/f706130f-4f3a-40b9-a241-54091ab86e4d> | <video src=https://github.com/brave/brave-ios/assets/17010094/0879dd88-0134-4830-a870-ec65fd02098f> | <video src=https://github.com/brave/brave-ios/assets/17010094/798672cf-b7c1-424c-a3d3-1770220b552f>
