### ISSUE TITLE
Close button in join native Brave Talk lobby does not work

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#7909]
### Description: 

If you tap the "Close" button in the native brave talk lobby (where you can enter your name and join the call) nothing happens.

### Steps to Reproduce 
  1. Open a Brave Talk link and load the native UI
  2. Tap the "Close" button in the top left corner

### Actual result:
Nothing happens

### Expected result:
Close the window

### Reproduces how often: 
Easily

### Brave Version: 1.56+ but likely since native Talk was introduced

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using version `1.57.1 (23.9.20.7)`

- Ensured `Close` button is working in the talk lobby

https://github.com/brave/brave-ios/assets/17885425/2b10720c-238a-4db7-b3fb-e59885272937

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 [iOS 17.0]
- iPad Air [iPadOS 16.5.1]
Brave build: 1.57.1 (23.9.20.7)
BraveCore: 1.57.53 (116.0.5845.114)
```
---------------------------

**STEPS:**
Followed the steps from https://github.com/brave/brave-ios/issues/7909#issue-1859974279

**ACTUAL RESULTS:**
- Verified that `Close` button is working in native Brave Talk in the lobby.

---------------------------

*iPhone*

https://github.com/brave/brave-ios/assets/128532965/a2514367-4627-49f0-a9b6-e8a83d0ee4b9

*iPad*

https://github.com/brave/brave-ios/assets/128532965/165d5337-3a4d-4f72-a8bf-5f3e238dea66
