### ISSUE TITLE
Brave Rewards 1.0

### ISSUE THREAD

**Issue by jamesmudgett** [brave/brave-ios#791]
This issue aims to outline native rewards panels integration into 1.7.x. Updates will be made to the description of this issue.

### Address bar
https://share.goabstract.com/b332b20a-6c46-4e74-a018-a732a1f540c7
![brave ios rewards](https://user-images.githubusercontent.com/318119/51707400-bf10d000-1fe6-11e9-9fed-378614613393.png)

- Updated toolbar colors for normal tabs.
- Reload button to be inset in address input container, as well as divider line, brave shields, and bat logo.
- Notification indicators should be hideable 

### Rewards Panel
https://share.goabstract.com/36e85a35-61aa-4958-8f9a-6fdf882086e0
![rewards welcome screen](https://user-images.githubusercontent.com/318119/51707460-e7003380-1fe6-11e9-8b80-f8373b32c00f.png)

- Initial state of Rewards welcome screen if a previous use has not been detected. (Returning user screen will be updated shortly)

**Comment by jhreis** [comment]
Closing per: https://github.com/brave/brave-ios/issues/39
