### ISSUE TITLE
Brave playlist isn’t working with bitchute

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#7916]
### Description: 
https://twitter.com/vac93302099/status/1694056384973939037?s=20

User reports

Looks like the Brave playlist isn’t working with bitchute, at least on iOS. Can’t add any bitchute videos to the playlis

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.58 (23.10.4.11)`

- Ensured playlist icon in url bar is shown when loading https://www.bitchute.com.
- Ensured playlist tutorial works on bitchute.com.
- Ensured adding bitchute video from url bar, share menu and long press works.
- Ensured user is able to navigate through playlist menu from url bar icon.
- Ensured removing item from playlist using url bar menu works.

Example | Example | Example | Example
-|-|-|-
![IMG_3559](https://github.com/brave/brave-ios/assets/17885425/7dd24693-f925-49b0-a2cd-e90444d37363) | ![IMG_3560](https://github.com/brave/brave-ios/assets/17885425/9625d428-bcc3-444d-9216-f29b50369c59) | ![IMG_3561](https://github.com/brave/brave-ios/assets/17885425/bd048751-09b0-464c-854e-19104bc40ab6) | ![IMG_3562](https://github.com/brave/brave-ios/assets/17885425/fa6eaf44-9031-4580-806c-565ef6948ad5)
