### ISSUE TITLE
Sync Beta label

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#792]
Pls add a Beta label to Sync

https://github.com/brave/brave-browser/issues/3079

**Comment by GeetaSarvadnya** [comment]
* Verification passed on Iphone 8 - IOS version 12.1.4

![IMG-20190314-WA0001](https://user-images.githubusercontent.com/38657976/54376251-a9478f00-46a8-11e9-9fea-e13587b26e3e.jpg)

* Verified passed with 1.9 (19.3.9.1) on iPad 5th Gen

![IMG_9BF8DD8F5FA5-1](https://user-images.githubusercontent.com/28145373/54376682-f94b3500-4659-11e9-9647-aa26bfb87265.jpeg)

* Verified passed with 1.9 (19.3.9.1) on iPhone SE
* Verification passed on iPhone 7+/6 and iPad Pro running 1.9(19.3.9.1)
* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR.
