### ISSUE TITLE
Display Swap Protocol Fees

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7924]
### Description: 

iOS version for front-end implementation of https://github.com/brave/brave-browser/issues/32464

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.2 running 1.60 (23.11.7.17)
- Verified steps from [#8233](https://github.com/brave/brave-ios/pull/8233)
- Verified Swap protocol fee is show as mentioned below 
   * MATIC-USDC (Polygon)
      * Brave Fee 0.875%
      * Protocol Fee 0.15%
   * MATIC-SUSHI (Polygon)
      * Brave Fee 0.875%
   * SOL-USDC (Solana)
      * Brave Fee 0.85%
   * SOL-CMFI (Solana)
      * Brave Fee Free ~0.85%~


MATIC-USDC (Polygon) | MATIC-SUSHI (Polygon) | SOL-USDC (Solana) | SOL-CMFI (Solana)
-- | -- | -- | --
![image](https://github.com/brave/brave-ios/assets/17010094/92d92afd-b8bf-4e82-9da9-d2f31e206162) | ![image](https://github.com/brave/brave-ios/assets/17010094/d00bd2a0-7686-439b-bc7f-4be2f4fa6993) | ![image](https://github.com/brave/brave-ios/assets/17010094/236f6deb-8fc3-4a02-9b06-b7248f1791e8) | ![image](https://github.com/brave/brave-ios/assets/17010094/99f85fd1-0810-4644-a905-ae195f5c7a98)
