### ISSUE TITLE
Crash on FilterListResourceDownloader

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#7930]
### Description: 
We see reports of crashes on `FilterListResourceRownloader` when reading and writing to Preferences

### Steps to Reproduce 
Cannot reproduce as only stack traces are available

### Actual result: 
Crashes

### Expected result:
Should not crash

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Intermittent Issue

### Brave Version: 
1.57

### Device details: 
N/A

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
Need to main actor isolate the Preferences read/write

**Comment by iccub** [comment]
Marking as qa/no because it seems to be a rare crash. only 2 occurrence in the public beta so far

**Comment by cuba** [comment]
Still an issue, new fix is coming.
