### ISSUE TITLE
Update Brave News opt-in card locales

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#7932]
New Regions were added to Brave News: `de_DE`, `fr_FR`, `en_AU`, `en_IN`, they should be added to the list that is used to show the opt-in card for Brave News

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.0]
Brave build: 1.58 (23.9.26.21)
BraveCore: 1.58.129 (117.0.5938.88)
```
Filled issue #8167
---------------------------
<details>
<summary> Fresh install - PASS </summary>

**STEPS:**
1. Change device language and location to `de_DE`
2. Fresh install and launch Brave
3. NTP > Verify `Brave News` opt-in card
4. Enable News > Verify
5. Repeat Steps 1 - 4 for `fr_FR`, `en_AU` and `en_IN` > Verify

**ACTUAL RESULTS:**
- Verified that `Brave News` opt-in card is shown on NTP for `de_DE`, `fr_FR`, `en_AU`, `en_IN`
- Verified that opt-in is working

---------------------------

|de_DE|fr_FR|en_AU|en_IN|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/48b31157-69ed-45e2-aa59-000ca206cd3c) | ![2](https://github.com/brave/brave-ios/assets/128532965/786aa4d2-c20e-4327-9676-9637b1c3d5d7) | ![3](https://github.com/brave/brave-ios/assets/128532965/1f3f9257-b4fb-4201-bc36-54f912518e21) | ![4](https://github.com/brave/brave-ios/assets/128532965/b6b7bf29-6087-4746-b9cb-e6007cbf3a44) |

https://github.com/brave/brave-ios/assets/128532965/13329bae-a321-43cc-96d3-b72bb10b2d14

</details>

<details>
<summary> Upgrade install - FAIL </summary>

**STEPS:**
1. Change device language and location to `de_DE`
2. Fresh install build `1.57.2` and launch Brave
3. Go through onboarding and land on `NTP` > Confirm that `Brave News` opt-in card is not shown
4. Upgrade Brave to build `1.58` and launch it
5. Verify if the `Brave News` opt-in card is shown on `NTP`
7. Repeat Steps 1 - 5 for `fr_FR`, `en_AU` and `en_IN` > Verify the same

**ACTUAL RESULTS:**
- Observed that the `Brave News` opt-in card is not shown on `NTP` after upgrade to build `1.58`.

---------------------------

https://github.com/brave/brave-ios/assets/128532965/f35ac523-dc07-409b-9036-23c9bf2c51a3

</details>
