### ISSUE TITLE
Development branch build issue

### ISSUE THREAD

**Issue by bibin-jaimon** [brave/brave-ios#7938]
### Description: 
- Not able to run the development branch
- self is missing in some closures.

### Steps to Reproduce 
  1. Clone and build development branch

### Actual result: 
![Screenshot 2023-08-24 at 2 26 54 AM](https://github.com/brave/brave-ios/assets/22428886/24408b57-3930-4fe0-8b82-c19d9ecdf4e3)

### Expected result:
Should be able to run the debug build

**Comment by kylehickinson** [comment]
Please update your Xcode to Xcode 14.3 to match our CI, our README is slightly out of date
