### ISSUE TITLE
Update Jitsi SDK to 8.3.1-lite

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7940]

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 [iOS 17.1]
- iPad Air [iPadOS 16.5.1]
Brave build: 1.58 (23.10.17.8)
BraveCore: 1.58.141 (117.0.5938.153)
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-ios/pull/7934#issue-1863916665

**ACTUAL RESULTS:**
- Verified that `Brave Talk` is working and the app is not crashing
- Verified UI is working, and able to send chat messages, raise/lower a hand, send reactions, change the settings, etc.

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/920ca21e-bd87-414f-aed1-03af105d2cf7) | ![2](https://github.com/brave/brave-ios/assets/128532965/2e801467-d94f-4bce-adf8-bb91f9687ca6) | ![3](https://github.com/brave/brave-ios/assets/128532965/f8f75cf1-1822-4e79-83f4-f5d62ae7543e) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/ec504a1a-1659-463b-b042-2b1b72a5fd78) | ![2](https://github.com/brave/brave-ios/assets/128532965/6d657705-a7f7-4c95-bf9a-9e88145d13f0) | ![3](https://github.com/brave/brave-ios/assets/128532965/eb8d7cd2-b010-4af7-8fcb-145c2d639dc6) |
