### ISSUE TITLE
Portfolio graph is hidden when sorting assets by account

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#7945]
### Description: 
Portfolio graph is hidden when sorting assets by account

### Steps to Reproduce 
  1. Restore a wallet with balance
  2. Ensure graph is shown after balance is loaded
  3. Group assets by account and save it
  4. Graph is hidden 
  5. Reset portfolio settings, graph comes back 

### Actual result: 

https://github.com/brave/brave-ios/assets/17010094/b830a608-5148-460d-9594-fc1149e46fe3

### Expected result:
Should show the graph irrespective of what settings is set

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 
All

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by StephenHeaps** [comment]
Investigating this it seems it's related to `weth` being auto-discovered (>0 balance) and attempting to fetch price history returns only 1 historical price, so only the one value is shown. For example, fetching price history for `eth` vs `usd` using 1-day time-frame returns 289 historical prices. Fetching the same for `weth` returns 1 historical price.

I was able to reproduce on v1.56 (using account with some `weth` balance), prior to Portfolio filters integration:

https://github.com/brave/brave-ios/assets/5314553/bb48c5e0-c4a7-4280-bdd5-8020f44f857b

**Comment by StephenHeaps** [comment]
Created https://github.com/brave/brave-browser/issues/36634 to handle the graph datapoints issue mentioned above. 

Further investigation found this is a separate issue specific to iOS when grouping assets by Accounts, and having at least 1 owned NFT (>0 balance) with an [`assetRatioId`](https://github.com/brave/brave-ios/blob/be1d1929867d4d2c7c2323d0287595a1d46b3317/Sources/BraveWallet/Extensions/BraveWalletExtensions.swift#L287-L297) that has history available.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.2 running 1.60 (23.11.7.17)
- Verified steps from [#8300](https://github.com/brave/brave-ios/pull/8300)
- Verified Portfolio graph is not hidden when sorting assets by account

https://github.com/brave/brave-ios/assets/17010094/e61c69c1-74c7-42a1-b343-9d5c691761a8
