### ISSUE TITLE
Portfolio group by accounts shows Filecoin accounts prior to support

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7947]
### Description: 

When grouping by account, Filecoin account groups are shown with no assets.

### Steps to Reproduce 
  1. Restore a wallet with FIL balance
  2. Open Filters & Display Settings
  3. Change `Group By` to `Accounts`
  4. Tap save
  5. Observe `Filecoin Account 1` group is shown with 0 assets.

### Actual result: 

![Filecoin account group](https://github.com/brave/brave-ios/assets/5314553/f6096501-269e-41f8-81bd-aac358e44f62)

### Expected result:

Filecoin accounts hidden until supported

### Reproduces how often: 

Easily reproduced

### Brave Version:

v1.57+

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 16.6 running 1.57 (23.8.28.22)
- Verified steps from issue description
- Verified Filecoin accounts are not shown on an restored wallet when portfolio is grouped by account

https://github.com/brave/brave-ios/assets/17010094/f7424c6a-9ab0-4eca-811c-c31ca4a79f5f
