### ISSUE TITLE
NFT Filters Reset button does not reset some filters

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#7948]
### Description: 

NFT tab's Filters & Display Settings modal does not reset `Network Logo` or `Hide Unowned` when changed from default values and tapping `Reset`

### Steps to Reproduce 
  1. Open NFT tab and tap Filters & Display Settings button
  2. Change `Network Logo` toggle to be on/enabled
  3. Change `Hide Unowned` toggle to be on/enabled
  4. Tap `Reset`
  5. Observe toggles are not reset

### Actual result: 

Toggles are not reset to default values

### Expected result:

Toggles are reset to default values

### Reproduces how often: 

Easily reproduced

### Brave Version: 

v1.57+

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 16.6 running 1.57 (23.8.28.22)
- Verified steps from issue description
- Verified reset button resets all filters to default state in NFT filter settings

https://github.com/brave/brave-ios/assets/17010094/5aac06d3-7cb6-4f12-82fd-55a123a615a6
