### ISSUE TITLE
Improve the speed of compiling engines

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#7955]
### Description: 
When we change settings, the engines need to be re-compiled to apply the latest results. This delay is noticeable. We would like to minimize this delay so that it is minimally noticeable or (ideally) unoticible.

### Steps to Reproduce 
  1. Enable cooke consent blocking and open in app notice blocking
  2. Go to https://dev-pages.brave.software/filtering/additional-lists.html
  3. Notice that the images on the right are hidden (note there is a delay which is identified by this issue: https://github.com/brave/brave-ios/issues/7954)
  4. Disable cooke consent blocking and open in app notice blocking
  5. Keep refreshing the page until the images on the right no longer hide

### Actual result: 
It takes a long while before the new rules are applied. It takes several refreshes (usually before this happens)

### Expected result:
The rules should be applied almost right away (if not right away)

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.1]
Brave build: 1.58 (23.10.6.14)
BraveCore: 1.58.139 (117.0.5938.153)
```
---------------------------

**STEPS:**
1. Fresh install and launch Brave
2. Open https://amazon.co.uk or https://anker.com
3. Confirm that the cookie consent notice is getting hidden right away
4. Three-dot menu > Settings > Brave Shield & Privacy
5. Turn off `Block cookie consent notices`
6. Return to a website > Refresh the page > Verify
7. Go back to the settings and enable `Block cookie consent notices`
8. Return to a website > Refresh the page > Verify

**ACTUAL RESULTS:**
- Verified that previously it took ~20 seconds to apply new settings when enabling/disabling `Block cookie consent notices`
- Verified that now it almost immediately applies new settings when enabling/disabling `Block cookie consent notices`

---------------------------

*Build 1.58*

https://github.com/brave/brave-ios/assets/128532965/c840d8d4-6637-4720-987b-f97ae47f0add

*Build 1.57.2*

https://github.com/brave/brave-ios/assets/128532965/94b2bce7-1469-4549-8ca0-5b37ef9e0a27
