### ISSUE TITLE
Favicons on NTP may appear blurry

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7973]
Sometimes when a favicon is fetched the quality of it is not great

**Comment by hffvld** [comment]
Hi @iccub and @Brandon-T I still see the blurred `Amazon` favicon in the latest build.

-----------------
```
Device/OS: iPhone 14 [iOS 17.1]
Brave build: 1.58 (23.10.6.14)
BraveCore: 1.58.139 (117.0.5938.153)
```
-----------------
|Before|After|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/b7e939c0-6ad3-42f2-9311-1b9903d9f2b1) | ![2](https://github.com/brave/brave-ios/assets/128532965/ec853beb-7174-46d8-acf3-f5d61e3ff7e8) |

**Comment by Brandon-T** [comment]
> Hi @iccub and @Brandon-T I still see the blurred `Amazon` favicon in the latest build.
> 
> 
> 
> -----------------
> 
> ```
> 
> Device/OS: iPhone 14 [iOS 17.1]
> 
> Brave build: 1.58 (23.10.6.14)
> 
> BraveCore: 1.58.139 (117.0.5938.153)
> 
> ```
> 
> -----------------
> 
> |Before|After|
> 
> |:-:|:-:|
> 
> | ![1](https://github.com/brave/brave-ios/assets/128532965/b7e939c0-6ad3-42f2-9311-1b9903d9f2b1) | ![2](https://github.com/brave/brave-ios/assets/128532965/ec853beb-7174-46d8-acf3-f5d61e3ff7e8) |

Hi, that's actually the icon Amazon sends back on their page. That's the highest quality icon you're seeing. In the "before", that's our bundled icon. In the "after", that is the icon on Amazon.com/favicon.ico

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.1]
Brave build: 1.58 (23.10.6.14)
BraveCore: 1.58.139 (117.0.5938.153)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Land on `NTP`
3. Notice Wikipedia favicon > Tap it
4. Open another `NTP` > Compare Wikipedia favicon > Verify

**ACTUAL RESULTS:**
- Verified that favicons before opening a website and after opening a website are in high quality (except Amazon)

---------------------------

|1.57.2 before website launch|1.57.2 after website launch|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/27e4d3ec-975e-4ae5-bae6-a8c2157c0e58) | ![2](https://github.com/brave/brave-ios/assets/128532965/50fb9acf-144b-4e5d-bc89-6de813264e4c) |
|1.58 before website launch|1.58 after website launch|
| ![1](https://github.com/brave/brave-ios/assets/128532965/afc5717f-b46d-4f6c-8495-fc6f75792519) | ![2](https://github.com/brave/brave-ios/assets/128532965/270ee0cc-c395-4334-b374-89c5e02777d0) |
