### ISSUE TITLE
[Follow up to #7860] "Default browser prompt" must not be shown after 14 days since installation

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#7977]
### Description: 

Follow-up to #7860

### Steps to Reproduce 
1. Fresh install and launch Brave 
2. Start onboarding flow > Don't set Brave as the default browser and select `Not now`
3. Tap `Done` > Wait until landed on NTP > Confirm there is no `Default browser prompt` is shown
4. Device `Settings` > Update the date to be `<7 days` from today
5. Relaunch Brave > Confirm there is no `Default browser prompt` on NTP
6. Now update the date between `7 and 14 days` from today
7. Relaunch Brave > Confirm that `Default browser prompt` is shown on NTP
8. Now update the date to be`>14 days` from today
9. Relaunch Brave > Observe, `Default browser prompt` still shown

### Actual result: 

Observed that `Default browser prompt` is still shown after 14 days since installation, and the prompt actually removed only on the 18th day after installation.

https://github.com/brave/brave-ios/assets/128532965/cc0923d1-f02c-404f-b04b-edebac3b8af2

### Expected result:

`Default browser prompt` must be removed after 14 days since Brave installation.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.57 (23.8.28.13)
BraveCore: 1.57.53 (116.0.5845.114)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 

iPhone 14 [iOS 17.0]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by soner-yuksel** [comment]
@vlad-hoff There was typo and 17 days was used instead of 14 but it should be fixed with https://github.com/brave/brave-ios/issues/7969, it can be great if you can re-stest.
Also while testing better to count 7 days after and 14 days after cause we are not checking this fully perfect tike diffrence here(it is not necessary only days difference)

https://github.com/brave/brave-ios/assets/6643505/6ea0251d-46d8-46a1-97a6-92911dcece7a

**Comment by iccub** [comment]
Please retest on the latest build `1.57 (23.8.29.17)`

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.0]
Brave build: 1.57 (23.8.29.22)
BraveCore: 1.57.53 (116.0.5845.114)
```
---------------------------

**STEPS:**
Followed the steps from https://github.com/brave/brave-ios/issues/7977#issue-1870309697

**ACTUAL RESULTS:**
- Verified that `Default browser prompt` is not shown on NTP after `14 days` since installation

---------------------------

https://github.com/brave/brave-ios/assets/128532965/9628cde3-665d-4e49-95e4-bc06af3632e1
