### ISSUE TITLE
Update user agent to iOS 16.6

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#7987]

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.58 (23.9.26.17)`

- Ensured user agent is 16.6 for both mobile and desktop using web debugging proxy.

![Screenshot 2023-09-27 at 6 23 25 PM](https://github.com/brave/brave-ios/assets/17885425/cbb82a7b-477c-4d38-9b4f-9b80c9283df8)
![Screenshot 2023-09-27 at 6 24 49 PM](https://github.com/brave/brave-ios/assets/17885425/a70a0b1b-2e5a-4899-960b-88bb092fb47a)
