### ISSUE TITLE
Update VPN Icon

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#7995]
### Description: 

Please update the VPN icon in all places within the app

Figma: https://www.figma.com/file/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%A6%81-Browser?type=design&node-id=2050-21340&mode=design

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.0]
Brave build: 1.58 (23.9.26.21)
BraveCore: 1.58.129 (117.0.5938.88)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. While on `NTP` > Three-dot menu > Verify
3. Open any website > Three-dot menu > Verify
4. Settings > Verify

**ACTUAL RESULTS:**
- Verified that the new `VPN` icon is shown in all 3 places

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/c28778f5-4fb7-4ae1-90af-4839888a7339) | ![2](https://github.com/brave/brave-ios/assets/128532965/62849b98-7cdc-4446-8068-0a3c81fb4c10) | ![3](https://github.com/brave/brave-ios/assets/128532965/6278f422-2bc8-43aa-8a49-269526be4904) | ![4](https://github.com/brave/brave-ios/assets/128532965/7b8b2b59-c314-468b-81b2-a00b2bd49e0d) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/335577df-a3ba-420d-92fa-0dd736fe0065) | ![2](https://github.com/brave/brave-ios/assets/128532965/5eac81e6-dd4e-487a-bd1d-16f8ef6dc4f4) | ![3](https://github.com/brave/brave-ios/assets/128532965/e5cd8a74-4a66-40f2-9ebe-ecc1fb91c2dc) | ![4](https://github.com/brave/brave-ios/assets/128532965/af93ba1c-fd25-4c79-9d63-6b171fefb793) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/c69aa229-2756-4280-b2d3-613cf985c88d) | ![2](https://github.com/brave/brave-ios/assets/128532965/5a634c33-8389-4d15-aa9f-b8587537c20b) | ![3](https://github.com/brave/brave-ios/assets/128532965/ac771863-0c29-4fab-8268-8fe9d030cda8) | ![4](https://github.com/brave/brave-ios/assets/128532965/c3d1133c-0483-4303-9a3d-d5512dc2a353) |
