### ISSUE TITLE
Switching Private Mode Tab Tray cause position loss in Normal Mode 

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#7996]
### Description: 

When user open Tab Tray in normal mode and switched to private mode, the position in normal mode is put back up to the beginning. This causes confusion for the user especially if they had multiple tabs.

### Steps to Reproduce 
  1. Open Tab Tray
  2. Check which tab is highlighted in the collection view and where is the scrool
  3. Switch to private mode
  4. And back to normal mode
  5. Check position in Tab tray is lost entirely and positioned to top 

### Actual result: 

https://github.com/brave/brave-ios/assets/6643505/f51f2611-529d-428b-bc12-8e25ed2ee5e1

It is pointing top of the list

### Expected result:

It should show where the selected tab position is

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Every time

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? True
- Can you reproduce this issue with the previous version of the current build from TestFlight? True
- Can you reproduce this issue with the current build from AppStore? True

### Device details: 
Any

### Website problems only:
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.0]
Brave build: 1.58 (23.9.26.21)
BraveCore: 1.58.129 (117.0.5938.88)
```
---------------------------

**STEPS:**
Followed the steps from https://github.com/brave/brave-ios/issues/7996#issue-1874071057

**ACTUAL RESULTS:**
- Verified that the previously selected tab stays selected after returning from `Private Mode` to `Normal Mode`
- Verified that tab position is not lost after returning from `Private Mode` to `Normal Mode`
- Verified that switching back from `Private Mode` to `Normal Mode` always positions the selected tab in the viewing area

---------------------------

https://github.com/brave/brave-ios/assets/128532965/6d92dc56-b21e-4fa0-917b-25c1e513e138
