### ISSUE TITLE
Sync Ordering - 1.7.4

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#800]
### Description: 
I created a sync chain in this order

Desktop (Version 0.59.28 Chromium: 72.0.3626.64 (Official Build) beta (64-bit)) - which had the bookmarks
Added 1.7.4 
Added Android V1.0.72

The ordering of the bookmarks on iOS were up-side-down

Every bookmark was ordered the wrong way around, inc the bookmarks within folders

**Comment by jhreis** [comment]
Dup: https://github.com/brave/brave-ios/issues/735
