### ISSUE TITLE
The total number of saved bookmarks does not include bookmarks from subfolders.

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#8000]
### Description: 

The total number of saved bookmarks does not include bookmarks from subfolders.

### Steps to Reproduce 
  1. Launch Brave
  2. Open `Bookmarks` > Mobile Bookmarks
  3. Create new folder inside > Done
  4. Open any website > THree-dot menu > Add Bookmark
  5. Location > Change default `Mobile Bookmarks` to the newly created folder > Save
  6. Open Bookmarks > Find `Mobile Bookmarks` folder > Observe that the bookmarks from the subfolder are not counted

### Actual result: 

Observed that saved bookmarks in subfolders are not counted as the total number of saved bookmarks.

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/6f56c51c-f141-4a89-a620-e6a7ef865a9d) | ![2](https://github.com/brave/brave-ios/assets/128532965/82fa91fc-6589-4785-b7d8-4613cc7e5188) |

### Expected result:

All bookmarks must be counted towards the total number of saved bookmarks including subfolders.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.57 (23.8.29.22)
BraveCore: 1.57.53 (116.0.5845.114)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 

iPhone 14 [iOS 17.0]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
lets remove the count.
keep it in the long press

**Comment by iccub** [comment]
removing this ticket and adding a new one which removes the count numbers
