### ISSUE TITLE
Display the VPN subscription in the App Store

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#8001]
### Details - Setting up Promotion and Implementation

To promote in app purchase on AppStore these steps should be handled on AppStore Connect side as 

`Step 1`

You can promote in-app purchases and subscriptions on your App Store product page if you’ve [added a promotional image](https://developer.apple.com/help/app-store-connect/create-an-app-record/view-and-edit-app-information)

After that these steps should be followed.

- In-app purchase should be Add or remove in-app purchases for promotion

- In-app purchase should be Customize the order of your promoted in-app purchases

- Promote only relevant in-app purchases to customers ) this step will also need code changes using [SKProductStorePromotionController](https://developer.apple.com/documentation/storekit/skproductstorepromotioncontroller)

So after AppStore Connect side is added with proper promotional image and other criteria, next step should be adding proper delegate method into the source code.

https://developer.apple.com/help/app-store-connect/configure-in-app-purchase-settings/promote-in-app-purchases

`Step 2`

- Adding delegate method shouldAddStorePayment 
[paymentQueue(_:shouldAddStorePayment:for:)](https://developer.apple.com/documentation/storekit/skpaymenttransactionobserver/2877502-paymentqueue) delegate method from SKPaymentTransactionObserver should be implemented 

This protocol method should determine if payment can be processed if user pressed the promotion on AppStore and opened the app.

This method's implementation should handle important steps of recognizing App is currently on a state(like onboarding) and return status accordingly for payment process, If not save the deferred payment until payment can be processed in a better situation.

In addition it will signal main browser to show VPN Buy Screen before triggering the payment to make user have the context before buying or providing a second chance to make them think about the deal.

- Properly Handle Visibility Settings 
[SKProductStorePromotionController](https://developer.apple.com/documentation/storekit/skproductstorepromotioncontroller) will be implemented to handle the proper visibility and order for the purchases, on top of the order visibility assigned in AppStore Connect to have specific mobile device criteria such as If the in-app Purchase already implemented not to show that to user. 

https://developer.apple.com/documentation/storekit/skpaymenttransactionobserver/promoting_in-app_purchases

### Testing

Testing Subscription Promotion is not very well designed on Apple side only way to test it is running promotion URL in another browser like Safari which in our case will be itms-services://?action=purchaseIntent&bundleId=com.brave.ios.browser&productIdentifier=bravevpn.monthly if this is a Release build for monthly transaction in app purchase

https://developer.apple.com/documentation/storekit/in-app_purchase/testing_promoted_in-app_purchases

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.1.1` using version `1.61 (23.12.18.22)`

- Verified test plan in https://github.com/brave/brave-ios/issues/8001#issue-1875613985


https://github.com/brave/brave-ios/assets/17885425/0ce7ed60-d43d-431c-9219-eb09a9a549b0
