### ISSUE TITLE
Main menu not popping up when in windowed mode [iPad]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#8004]
### Description: 
Menu does not pop up when tapping 3 dot menu in split view/split over mode or sometimes when connected to physical keyboard due to the center keyboard language settings modal showing. 

### Steps to Reproduce 

Case 1: 

  1. Enter split screen mode by tapping on the 3 dot in top center of window
  2. Select `Slide Over` for another Brave window
  3. Try to toggle the menu in the slide over window several times, sometimes the three dots gets grayed out and nothing happens when you tap.
  
  Case 2: 

  1. Attach physical keyboard 
  2. Use `Open in New Window` when long pressing on link on webpage
  3. Sometimes the menu in the new window doesn't work because of the keyboard menu modal that shows up

### Actual result: 
![IMG_1191](https://github.com/brave/brave-ios/assets/17885425/c9bb57d2-dcb3-4d6d-84b7-fca9412e02bf)

### Expected result:
Menu should pop up

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Intermittent

### Brave Version:  1.57 (23.8.29.22)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No (new feature)

### Device details: 
iPad (7th Gen) 16.5.1

**Comment by kylehickinson** [comment]
Fixed by https://github.com/brave/brave-ios/pull/8184

**Comment by hffvld** [comment]
Verified on `iPad Air` using version(s):
```
Device/OS: iPad Air / iPadOS 16.7.2
Brave build: 1.60 (23.11.7.17)
BraveCore: 1.60.113 (119.0.6045.105)
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-ios/issues/8004#issue-1875793897

**ACTUAL RESULTS:**
- Verified that `Main menu` can be opened when in `Split View` + `Slide Over`
- Verified that `Main menu` can be opened when the `physical keyboard` is connected and opened a new tab in the new window

---------------------------

https://github.com/brave/brave-ios/assets/128532965/03bbf106-f5b0-4975-9909-e35ac1069ef0

https://github.com/brave/brave-ios/assets/128532965/c09cf821-31d7-40f4-8e60-5d56286f9d9b
