### ISSUE TITLE
Sync Chain Creating - 1.7.4

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#801]
Linked to: https://github.com/brave/brave-ios/issues/800

I created a sync chain ^^

On iPhone, 2 instances of my Mac firstly, and this my iPhone were created. 

On my Mac and Android, the chain was correct

![IMG_1608.PNG](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/d5e22f9d-bfda-465b-9363-916ac5173ffb)

Correct
![screenshot (4).jpg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/9b2b6a57-8f1d-4e2b-9591-cc6c3122db2a)
![Screen Shot 2019-01-25 at 10.52.37 AM.png](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/cafbb498-e5fa-4172-b8e7-ccf720076313)

**Comment by jhreis** [comment]
Dup: https://github.com/brave/brave-ios/issues/789
