### ISSUE TITLE
Opening Private Tab from App Icon Long Press over website requires Basic Auth Challenge in normal mode causes issues

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#8017]
### Description: 

Opening Private Tab from icon over website requires Basic Auth in normal mode causes issues.

The private mode is opened with old tab from normal mode and basic authentication window can be seen

### Steps to Reproduce 
  1. Open normal mode and load 
  2. https://search.brave.software/
  3. Check Basic Authentication is presented
  4. Kill the app
  5. Open from app icon long press using private mode
  6. check same website with basic authentication is shown in private mode

### Actual result: 

Opens same website on Private mode with Basic Authentication warning

https://github.com/brave/brave-ios/assets/6643505/45e26b6f-99b3-401e-b4fe-5996bd171ced

### Expected result:

It should open private mode clean and safe

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
Any

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.2
Brave build: 1.60 (23.11.4.14)
BraveCore: 1.60.105 (119.0.6045.59)
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-ios/issues/8017#issue-1878003698

**ACTUAL RESULTS:**
- Verified that the `Private tab` opened as `NTP` without https://search.brave.software/

---------------------------

https://github.com/brave/brave-ios/assets/128532965/188ffa88-1ea1-45a8-a07f-f8d1b5c9cc60
