### ISSUE TITLE
Brave iOS 1.56 - Search from iOS doesn't use selected search engine in settings

### ISSUE THREAD

**Issue by nnpcYvIVl** [brave/brave-ios#8018]
Brave uses DuckDuckGo as the default search even though I have Google configured for my search engine. See attached screenshots.

![search settings](https://github.com/brave/brave-ios/assets/8421414/d78a7d44-59db-4ff3-81e5-18f42864af7a)

![1](https://github.com/brave/brave-ios/assets/8421414/00e79a7a-228f-41c7-9f3f-880b73ee505f)

![2](https://github.com/brave/brave-ios/assets/8421414/a233a836-d04f-401d-b645-93b21657d0dd)

**Comment by iccub** [comment]
Siri Suggestions use whatever you have set in Safari. It's Apple's limitation sorry. Nothing we can do about it
