### ISSUE TITLE
[iOS 17] Fingerprinting is broken and showing the same values on both pages and after relaunching Brave when Shields enabled

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#8019]
### Description: 

[iOS 17] Fingerprinting is broken and showing the same values on `both pages` and after `relaunching Brave` when `Shields enabled`

### Steps to Reproduce 
  1. Launch Brave
  2. Go to https://dev-pages.brave.software/fingerprinting/farbling.html
  3. Make sure `Brave Shields` is enabled > Generate fingerprints
  4. Check results for `Plugins`, `Hardware connectivity and `Speech voices`
  5. For each separate feature the value must be the same in every column, but different for each feature
  6. Close and relaunch Brave > Run the test again
  7. Compare values with results in the previous step  > Observe that values are the same
  8. Open another page https://dev-pages.bravesoftware.com/fingerprinting/farbling.html
  9. Run the test and compare results > Observe that values are the same
  
Note: Hardware concurrency is hit or miss. We farble number of cores between 2-8 (on iOS 14 and can be less on older devices). With such a low variety of numbers, it's possible that both both test pages get the same value. This can be seen by killing the app and relaunching it. A new random value is given to the farbler and you will see the same values repeating on average 1/7 times as there are only 1/7 possible values we can use.

### Actual result: 

When `Brave Shields` is enabled on a device with `iOS 17` the values for farbling tests are the same. On iPad with iPadOS 16.5.1 the values are different as expected, so I believe this is `iOS 17` specific issue.

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/a50e584a-fe53-4f06-aded-58b2ccc22337) | ![2](https://github.com/brave/brave-ios/assets/128532965/d5d95356-1037-4086-aea6-42ab161eb4b3) | ![3](https://github.com/brave/brave-ios/assets/128532965/41c19f9a-5d3f-4272-acac-a97cfcd1174f) | ![4](https://github.com/brave/brave-ios/assets/128532965/9e62764d-750b-49e8-a1ce-f39fa820f0d0) |

### Expected result:

Results must have different values for farbling tests.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.57 (23.9.1.15)
BraveCore: 1.57.53 (116.0.5845.114)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 

iPhone 14 [iOS 17.0]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iPadOS 17.0` using version `1.57.1 (23.9.18.13)`

- Verified generated values are different for the features using STR in https://github.com/brave/brave-ios/issues/8019#issue-1878263332.
- Verified farbling test passes on staging and dev test sites.

Test 1 | Test 2
-|-
![IMG_1222](https://github.com/brave/brave-ios/assets/17885425/9011b492-b6d7-440e-bbcd-975a7f635273) | ![IMG_1223](https://github.com/brave/brave-ios/assets/17885425/a2fb6707-9280-48e6-8bd9-a2046ddc3855)

**Comment by hffvld** [comment]
Verified on `iPhone 14`using version(s):
```
Device/OS: iPhone 14 [iOS 17.0]
Brave build: 1.57.1 (23.9.20.7)
BraveCore: 1.57.53 (116.0.5845.114)
```
---------------------------
<details>
<summary> Shileds ON </summary>

**STEPS:**
Followed the steps from https://github.com/brave/brave-ios/issues/8019#issue-1878263332

**ACTUAL RESULTS:**
- Verified that the results have different values for farbling tests.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/f961d260-13bb-48ad-8843-b1eed9d82b30) | ![2](https://github.com/brave/brave-ios/assets/128532965/449d2800-3321-46b9-9b3e-8085b48200f4) | ![3](https://github.com/brave/brave-ios/assets/128532965/3bb344f5-af55-439b-b852-055f0c806f62) | ![4](https://github.com/brave/brave-ios/assets/128532965/64d08f8d-c412-45aa-ae3e-982c4927193e) |
</details>

<details>
<summary> Shileds OFF </summary>

**STEPS:**
Followed the steps from https://github.com/brave/brave-ios/issues/8019#issue-1878263332 but this time wit h`Shileds` `OFF`

**ACTUAL RESULTS:**
- Verified that no regression appeared and results have the same values for farbling tests.

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/82e663d8-6749-4f01-bd28-b5e4bd96b25e) | ![2](https://github.com/brave/brave-ios/assets/128532965/83d4636e-2668-4a1d-a636-2da740f5a3b2) | ![3](https://github.com/brave/brave-ios/assets/128532965/53842643-efda-4f83-8b9a-fb2155634f09) | ![4](https://github.com/brave/brave-ios/assets/128532965/4189c77c-c542-4535-a1c0-a4b9b5691479) |
</details>
