### ISSUE TITLE
Incorrect asset detail can be opened in asset search

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8023]
### Description: 

Opening asset detail can result in incorrect token being opened.

### Steps to Reproduce 
  1. Open Asset Search View and tap on a token to open asset detail
  2. Tap back and tap on a different token
  3. Repeat until incorrect token is displayed in asset detail

### Actual result: 

https://github.com/brave/brave-ios/assets/5314553/c94545e4-f614-4839-b904-5bdf20e0eda5

### Expected result:

Asset tapped on shows in asset detail

### Reproduces how often: 

Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.58 (23.9.19.14)
- Verified steps from [#8024](https://github.com/brave/brave-ios/pull/8024)
- Verified correct asset details are shown when selecting from search asset

iPhone 7+ (iOS 15.7.8) | iPhone 13 (iOS 17) | iPad (iOS 16.7)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/271fb283-da01-45e3-b3a5-834afb8d282e> | <video src=https://github.com/brave/brave-ios/assets/17010094/be201963-5371-4798-93ab-69cd6c78e4f4> | <video src=https://github.com/brave/brave-ios/assets/17010094/8fed183a-6d2e-4139-8d9e-756d0282311d>
