### ISSUE TITLE
"Select All" option not appearing when long-pressing text 

### ISSUE THREAD

**Issue by Brave-Matt** [brave/brave-ios#803]
### Description: 
Long-pressing on an article or text on a webpage reveals the context menu, but the `Select All` option is not present. Seems to be happening across all iOS devices and any/all text.

### Steps to Reproduce 
  1. Launch Brave, visit a website with text that can be selected
  2. Long-press on some text to show context menu

**Actual result:** 
Context menu appears, `Select All` option is not available

**Expected result:**
Should see this option every time. 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always 

**Brave Version:** 
v1.7.2

**Device details:** 
Multiple device types

### Additional Information 
Initial user reporting the issue:
https://community.brave.com/t/ios-select-all-option-not-available-since-latest-update/43360/2

**Comment by srirambv** [comment]
I dont think we ever had this option on the new code base? I don't see in FF or Safari either. May be this will be a feature to add in but definitely not available on the current build or on FF/Safari

**Comment by iccub** [comment]
It is iOS controlled, we do not modify it as far as I know
