### ISSUE TITLE
itms-apps scheme is not working

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#8035]
See https://github.com/mozilla-mobile/firefox-ios/issues/16240

STR Enter the URL itms-apps://apps.apple.com/app/pulse-secure/id945832041?l=en in the address bar

**Comment by hffvld** [comment]
Hi @iccub it's still opening a search instead of a warning message in the latest `1.58` and `1.59` builds.

https://github.com/brave/brave-ios/assets/128532965/13db1e7a-20d9-47b0-8d8c-1ce059ab18cc

**Comment by iccub** [comment]
thanks. lets reopen

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.2
Brave build: 1.60 (23.11.9.15)
BraveCore: 1.60.114 (119.0.6045.124)
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-ios/pull/8318#issue-1962735801

**ACTUAL RESULTS:**
- Verified that opening a universal link like the Appstore link `itms-apps://apps.apple.com/app/pulse-secure/id945832041?l=en` is triggering an alert message saying that this link will be opened in an external app and requires user approval.

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/df07ec28-5697-4739-8cb5-e93022640da0) | ![2](https://github.com/brave/brave-ios/assets/128532965/a9c0f1d7-59c9-4ff5-b27e-00891846bba0) |

https://github.com/brave/brave-ios/assets/128532965/bfe0f8b5-6d14-4a98-8037-bcb6cf452449
