### ISSUE TITLE
[RFE] Add global setting to always request desktop version

### ISSUE THREAD

**Issue by tonyjames** [brave/brave-ios#804]
### Description: 
On my iPad Pro it would be useful to have an option in settings to always request the desktop version of websites without having press and hold on the refresh button.

**Brave Version:** 
Version 1.7.2 (19.01.18.15)

**Device details:** 
iPad Pro 11”
iOS 12.1.3

**Comment by iccub** [comment]
Fixed some time ago in https://github.com/brave/brave-ios/issues/1290, nothing to see here, doing cleanup of old tickets :)
