### ISSUE TITLE
Remove the bookmark count number

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#8041]

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.0]
Brave build: 1.58 (23.9.26.21)
BraveCore: 1.58.129 (117.0.5938.88)
```
Filed follow-up issue #8169
---------------------------

**STEPS:**
1. Launch Brave 
2. Add some websites to `Bookmarks`
3. Three-dot menu > Bookmarks > Verify
4. Tap and hold on a bookmarks folder > Conform that message with the total count of bookmarks shown
5. Tap it > Verify that all bookmarks are opened

**ACTUAL RESULTS:**
- Verified that the bookmark count number is not shown under the folder name
- Verified that the bookmark count number is shown when tapping and holding on a bookmark folder

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/dbf38ae2-0acf-44b8-b08f-e3e5e2ba85e4) | ![2](https://github.com/brave/brave-ios/assets/128532965/df885c53-7ecb-4127-86e9-54a7a118a824) |
