### ISSUE TITLE
Default Browser Notification - Update (Text - Default Logic)

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#8045]
### Description: 
https://old.reddit.com/r/brave_browser/comments/16ft2w2/brave_browser_sending_notifications_to_set/

Related: https://github.com/brave/brave-ios/issues/7860

Please update this notification and don't show if
--> Remove if one external url is opened(via mail app, notes, other apps...)

Also, update the text as following (pending @rmcfadden3 approval)

Title: "Enhance Your Privacy with Brave"
Subtitle: "Protect your data – Set Brave as your default browser."

**Comment by rmcfadden3** [comment]
Maybe something like:

Header: Get Brave protection, on every link
Body: Set Brave as your default browser

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.0]
Brave build: 1.58 (23.9.22.13)
BraveCore: 1.58.129 (117.0.5938.88)
```

Filed follow-up issue #8163
---------------------------
<details>
<summary> Notification. Updated strings. </summary>

**STEPS:**
1. Launch Brave 
2. Go through onboarding and don't set it as `Default browser`
3. Go to device settings > Update time on 2 hours forward
5. Pull down the notification drawer > Verify

**ACTUAL RESULTS:**
- Verified that notification to set Brave as default browser is shown in 2 hours after Brave installation
- Verified updated strings in the notification:
  - Title: `Get Brave protection, on every link`
  - Body: `Set Brave as your default browser`

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/8d2a4b07-e3fc-48eb-9248-d83c2cc44c81) | ![2](https://github.com/brave/brave-ios/assets/128532965/7efd6a86-00d9-47a2-9c67-e8dc9f8c77ed) | ![3](https://github.com/brave/brave-ios/assets/128532965/e63f06dd-ede5-4382-8b77-8f2b2f9562b7) |

https://github.com/brave/brave-ios/assets/128532965/9d180bbe-2f2e-4f63-bf7c-739c3321d212

</details>

<details>
<summary> Notification. Functionality. </summary>

**STEPS:**
1. Launch Brave 
2. Go through onboarding and don't set it as `Default browser`
4. Launch Gmail > Open a link with Brave
5. Go to device settings > Update time on 2 hours forward
6. Check notification > Verify

**ACTUAL RESULTS:**
- Verify that notification must not be shown after an external link is opened via Gmail or another 3P app
- Observed that notification is still shown after an external link was opened via Gmail

---------------------------

https://github.com/brave/brave-ios/assets/128532965/53e7143b-b857-4886-b1ac-31ac5f5b7daa

</details>
