### ISSUE TITLE
Small P3A Onboarding text update

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#8056]
### Description: 

Linked to https://github.com/brave/brave-ios/issues/1938

Please update the word **Done** on the P3A screen to **Continue**

Question for Devs, will Start Browsing easily fit in the UI?

**Comment by iccub** [comment]
We aim to avoid long text for buttons cc @jenn-rhim

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.0]
Brave build: 1.58 (23.9.22.13)
BraveCore: 1.58.129 (117.0.5938.88)
```
---------------------------

**STEPS:**
1. Fresh install and launch Brave 
2. Select Brave to be the default browser or skip it
3. Observe `Help make Brave better.` screen > Verify

**ACTUAL RESULTS:**
- Verified that `Continue` button is shown on `Help make Brave better.` screen
- Verified new user can tap `Continue` and land on NTP

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/187c01ef-3d9d-4559-8ab6-679a3f63b1f2) | ![2](https://github.com/brave/brave-ios/assets/128532965/4ac9cfe8-9121-4318-9071-e5c06d628587) |
