### ISSUE TITLE
Unable to add pass/ticket to iOS Wallet

### ISSUE THREAD

**Issue by iambrianfung** [brave/brave-ios#8057]
### Description: 
"add to Wallet" feature to add passes/tickets to the iphone wallet does not work on release or dev channels.

### Steps to Reproduce 
  1. Open Brave Browser
  2. Join an event on [lu.ma](https://lu.ma/)
  3. Attempt to add ticket to your wallet

### Actual result: 
Brave does not download the ticket or open the Wallet app to open. The page seemingly refreshes and does not prompt the user.

### Expected result:
how it works in safari
![safari](https://github.com/brave/brave-ios/assets/24831890/d5c5cfc6-3ad8-4032-b049-8d85f314241c)

### Reproduces how often: [Easily reproduced, Intermittent Issue]
`Easy reproduced`

### Brave Version: 
`Version 1.57 (23.9.4.13)`
- Can you reproduce this issue with the most recent build from TestFlight? `Yes`
- Can you reproduce this issue with the previous version of the current build from TestFlight? `Version 1.58 (23.8.23.22)`
- Can you reproduce this issue with the current build from AppStore? `Yes`

### Device details: 
iphone 13 mini

### Website problems only:
- did you check with Brave Shields down? `Yes`
- did you check in Safari/Firefox (WkWebView-based browsers)? 

`Yes` Works fine on Safari.
Broken for Firefox and Firefox Focus
![firefox](https://github.com/brave/brave-ios/assets/24831890/c7e5514d-be77-43ca-95b9-5db5daa62e67)
![firefoxfocus](https://github.com/brave/brave-ios/assets/24831890/064ea8c2-d232-477d-a091-ca635ee12cb8)

### Additional Information

This issue had been raised as far back as 2019
https://community.brave.com/t/add-to-apple-wallet-doesnt-work-on-southwest-com-ios/77275
https://community.brave.com/t/ios-fail-to-create-pass/183742

**Comment by kylehickinson** [comment]
Blocked by https://github.com/brave/brave-ios/issues/1424

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using versoin `1.62 (24.1.11.20)`

- Verified STR in https://github.com/brave/brave-ios/issues/8057#issue-1894603221.
- Verified pass is added to wallet successfully on `lu.ma` website and shows up in iOS wallet. 

Example | Example | Example
-|-|-
![IMG_3690](https://github.com/brave/brave-ios/assets/17885425/645d33fa-43a1-47be-bb03-b21e7dd21864) | ![IMG_3691](https://github.com/brave/brave-ios/assets/17885425/238911eb-0186-432c-8dcf-b66a854d9946) | ![IMG_3692](https://github.com/brave/brave-ios/assets/17885425/bc97a95d-4eda-4900-ba2f-29f692fff995)
