### ISSUE TITLE
Problem Moving Inactive Tab in Scrolling TabsBar on iPad

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#8058]
### Description: 

Moving Inactive Tab in Scrolling TabsBar on iPad  should move tab desired location and activate it. The behaviour works properly in iPhone but not working on iPad.

### Steps to Reproduce 
  1. Activate Tabs Bar
  2. Move inactive Tab
  3. Check selection behaviour

### Actual result: 

The inactive tab is not moved to the new position and get activated

### Expected result:

the inactive tab should be moved to new position and tab should be active

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily Reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes 
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 

Any iPad Modal

### Website problems only:
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information
It works properly on iPhone but not iPad

**Comment by hffvld** [comment]
Verified on `iPad Air` using version(s):
```
Device/OS: iPad Air / iPadOS 16.5.1
Brave build: 1.60 (23.11.4.14)
BraveCore: 1.60.105 (119.0.6045.59)
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-ios/issues/8058#issue-1894835022

**ACTUAL RESULTS:**
- Verified that the inactive tab can be easily moved and become active
---------------------------

https://github.com/brave/brave-ios/assets/128532965/d6219726-de9c-4c74-8538-8588ed449807
