### ISSUE TITLE
Guardian-Connect crash [fixed server side]

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#8059]

**Comment by iccub** [comment]
Fixed on the server side.
To test: run a sanity test and buy the vpn using in app purchase method

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using version `1.57.1 (23.9.20.7)`

- Ensured in-app purchase and installing profile will enable VPN.
- Ensured VPN tunneling and switching regions is working.
- Ensured changing protocol will update the VPN.
- Ensured disabling and then re-enabling VPN via the toggles works.
