### ISSUE TITLE
Block all cookies from settings affects already opened pages

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#806]
### Description: 
Block all cookies from settings affects already opened pages

### Steps to Reproduce 
  1. Visit jsdfiddle.net in a new tab, ensure page is loaded
  2. Enable `Block all cookies` from settings
  3. Once settings page is closed, jsfiddle.net reloads and site doesn't load completely as cookies are blocked

**Actual result:** 
Block all cookies from settings affects already opened pages

**Expected result:**
Settings change should only affect new pages that are visited. Already opened pages/tabs should only get affected if the tab/page reloads. 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.7.3(19.01.23.19)

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
This is expected and correct behavior, see https://github.com/brave/brave-ios/issues/871
