### ISSUE TITLE
Window.open performance issue when closing all tabs

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8060]
### Description: 
- Some websites can call `window.open` hundreds of times to create hundreds of windows when "Block Popups" are disabled.
- This can cause issues with closing all tabs

### Steps to Reproduce 
  1. See slack: https://bravesoftware.slack.com/archives/C6R461GF4/p1694573614483589
  2. https://hackerone.com/reports/2146323

### Actual result: 
- Should kill tabs as fast as possible

### Expected result:
- Tabs aren't killed properly

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily reproduced

### Brave Version: 
- Any

### Device details: 
- Any

### Website problems only:
- Yes. See the slack channel for the specific website

**Comment by Uni-verse** [comment]
Verified using `1.57.2 (23.9.25.17)` on `iPhone X` running `iOS 16.5.1`

Tested using `hxxps://funny-pothos-493f94.netlify.app/` with block pop-ups disabled
- Ensured all tabs can be closed when websites are calling window.open many times. 

https://github.com/brave/brave-ios/assets/17885425/cd870427-a69a-4954-b3df-d6d123b7f2b1
