### ISSUE TITLE
App annoyances are not being sufficiently blocked

### ISSUE THREAD

**Issue by iambrianfung** [brave/brave-ios#8066]
### Description: 
LinkedIn App notification is not being blocked/hidden when `Block 'Switch to App' Notices` is toggled.

This is caused by invalid selectors being sent to the script:
For linkedin
```
div.feed-shared-update-v2:has(span.update-components-actor__description:-abp-contains(/Anzeige|Sponsored|Promoted|Dipromosikan|Propagováno|Promoveret|Gesponsert|Promocionado|促銷內容|Post sponsorisé|프로모션|Post sponsorizzato|广告|プロモーション|Treść promowana|Patrocinado|Promovat|Продвигается|Marknadsfört|Nai-promote|ได้รับการโปรโมท|Öne çıkarılan içerik|Gepromoot|الترويج/))
```

```
div.feed-shared-update-v2:has(span.update-components-actor__sub-description:-abp-contains(/Anzeige|Sponsored|Promoted|Dipromosikan|Propagováno|Promoveret|Gesponsert|Promocionado|促銷內容|Post sponsorisé|프로모션|Post sponsorizzato|广告|プロモーション|Treść promowana|Patrocinado|Promovat|Продвигается|Marknadsfört|Nai-promote|ได้รับการโปรโมท|Öne çıkarılan içerik|Gepromoot|الترويج/))
```

For instagram
```
div[style="max-height: inherit; max-width: inherit; display: none !important;"]:has(span:-abp-contains(Paid partnership with ))
```
```
div[style="max-height: inherit; max-width: inherit; display: none !important;"]:has(span:-abp-contains(Paid partnership))
```
```
div[style="max-height: inherit; max-width: inherit;"]:has(span:-abp-contains(Paid partnership with ))
```

### Steps to Reproduce 
  1. Open Brave Browser
  2. Confirm `Block 'Switch to App' Notices` is toggled on
  3. Visit https://www.linkedin.com/
  4. Notice that there is banner prompt for the app
  5. Log in - notice that there is a banner prompt for the app

### Actual result: 
![Image from iOS (2)](https://github.com/brave/brave-ios/assets/24831890/95fa645d-bfe3-4604-81bc-0b56a03dae1f)
![IMG_4319](https://github.com/brave/brave-ios/assets/24831890/43e9e27f-eac8-4019-861e-32b851ec2d7c)
![Image from iOS (3)](https://github.com/brave/brave-ios/assets/24831890/e0f6b609-9bc7-45a6-843f-984193f40f5a)

### Expected result:
No App Banner

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

### Brave Version: 
Version 1.57 (23.9.4.13)
Version 1.58 (23.8.23.22)

- Can you reproduce this issue with the most recent build from TestFlight?  `Yes`
- Can you reproduce this issue with the previous version of the current build from TestFlight?  `Yes`
- Can you reproduce this issue with the current build from AppStore? `Yes`

### Device details: 
iPhone 13 Mini

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
https://bravesoftware.slack.com/archives/C3GNZANPR/p1694561748786329

Similar issue on Instagram as well
![IMG_4327](https://github.com/brave/brave-ios/assets/24831890/ba776252-a03b-4842-9bb2-e9d10e7d9b38)

**Comment by Uni-verse** [comment]
Verified on `iPhone 12 Pro` running `iOS 17.0.3` using version `1.58 (23.10.11.20)`

- Ensured open-in-app dialogs are suppressed on sites such as `reddit.com`, `twitter.com`, `linkedin.com` and `instagram.com`
- Ensured disabling Shields will expose the dialogs on the sites. 

_Shields up_

Example | Example | Example | Example
-|-|-|-
![IMG_5150](https://github.com/brave/brave-ios/assets/17885425/0d8d6a2b-41fc-4512-9eed-da22a8594153) | ![IMG_5151](https://github.com/brave/brave-ios/assets/17885425/33983fe2-feb7-4b20-9f14-9edf0e1134ef) | ![IMG_5152](https://github.com/brave/brave-ios/assets/17885425/4d180552-5b47-4a12-9c80-7d3d79056ef3) | ![IMG_5153](https://github.com/brave/brave-ios/assets/17885425/ecd35bee-7797-49a2-97d6-87ecfacf09e9)

_Shields down_
Example | Example | Example
-|-|-
![IMG_5155](https://github.com/brave/brave-ios/assets/17885425/87d4c604-55b2-4c05-909e-7ddf70d1cdd4) | ![IMG_5156](https://github.com/brave/brave-ios/assets/17885425/5b5d50b2-f767-4f33-a098-aea33ba4320d) | ![IMG_5157](https://github.com/brave/brave-ios/assets/17885425/2f3ff424-ce02-44d3-a053-d87049e7af9e)
