### ISSUE TITLE
URL autocomplete is annoying when trying to delete the URL

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#807]
### Description: 
URL autocomplete is annoying when trying to delete the URL

### Steps to Reproduce 
  1. Visit a site to add to history
  2. Open a new tab and visit the same site 
  3. Try to edit the URL, autocomplete keeps filling the URL from history 

**Actual result:** 
URL autocomplete is annoying when trying to delete the URL

**Expected result:**
In edit mode autocomplete should not complete making it hard to edit the URL

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
All

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
@srirambv it doesn't prevent you from deleting anything though, right? I believe we match Safari on this, it continues to attempt to autofill even on deletion for example:

1. visit: abc1.com
1. visit: abc2.com
1. go back to abc1.com
1. start editing url, and delete the `1.com` (left with `abc)
1. autofills `2.com` automatically for you

**Comment by iccub** [comment]
Another report here https://community.brave.com/t/ios-url-autofills-after-every-backspace-press/49057
It's harder to delete a url on Brave compared to other browsers, needs twice as much deletions

**Comment by srirambv** [comment]
@jhreis there is no loss in typing. Its just a super annoying thing to see autocomplete fill in URL when you just want to type in. May be have a toggle similar to auto suggest search terms in settings to autocomplete URL or not

**Comment by iccub** [comment]
Another complaint from reddit
https://www.reddit.com/r/brave_browser/comments/bnqo9f/any_way_to_stop_history_suggestions_popping_up/

**Comment by Brave-Matt** [comment]
@iccub stole the thread I came here to post

**Comment by anthonypkeane** [comment]
Linked to https://github.com/brave/brave-ios/issues/868

When 868 is fixed, this can be closed

**Comment by srirambv** [comment]
Verification passed on iPhone Xr with iOS 13.2 running 1.13(19.10.18.15)
* Verified deleting in URL doesn't try to autocomplete from history

Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.18.15)
* Verified deleting in URL doesn't try to autocomplete from history

Verification passed on iPhone 7+ with iOS 13.2 running 1.13(19.10.18.15)
* Verified deleting in URL doesn't try to autocomplete from history

Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.18.15)
* Verified deleting in URL doesn't try to autocomplete from history

Verification passed on iPhone 6 with iOS 12.4 running 1.13(19.10.18.15)
* Verified deleting in URL doesn't try to autocomplete from history
