### ISSUE TITLE
Support 'Clean Copy Link' from Sharesheet

### ISSUE THREAD

**Issue by JoeTot** [brave/brave-ios#8070]
## Problem Description 
On desktop, Brave allows me to strip tracking parameters from a URL using the 'Clean Copy Link' feature. On mobile, I would like to have the same functionality from the share sheet so that I can share or copy a link without tracking from Brave to other apps using the sharesheet.

## Feature Overview 
Adding this functionality to mobile will remove the issue of using the system native 'copy link' functionality which copies the entire link, including tracking params, and instead give me the option through Brave to copy a clean link without tracking.

## User Experience 

1. User clicks on the share button
2. Sharesheet is displayed with 'Copy Clean Link' option
3. User clicks on option in sharesheet and has the link with tracking params stripped copied to keyboard.

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.4 (21E217)
- iPad Air / iPadOS 16.7.2
Brave build: 1.63 (161)
BraveCore: 1.63.161 (122.0.6261.57)
```

Filed follow-up issue brave/brave-browser#36506
---------------------------
<details>
<summary> Main menu </summary>

**STEPS:**
1. Launch Brave 
2. Go to https://www.amazon.com/all-new-amazon-fire-tv-stick-4k-max/dp/B0BP9SNVH9/ref=s9_acsd_al_ot_c2_x_1_t?_encoding=UTF8&pf_rd_m=ATVPDKIKX0DER&pf_rd_s=mobile-hybrid-4&pf_rd_r=P9GZHCJP7839WFQXN52C&pf_rd_p=1d9ebc6c-2407-4dc4-86b9-cf0e479e0da9&pf_rd_t=&pf_rd_i=8521791011, for example
3. Open Brave's `Main menu` > *Verify that `Copy Clean Lin`k is shown*
4. Tap `Copy Clean Link` > Insert copied text in any text editor or chat app > *Verify*

**ACTUAL RESULTS:**
- Verified that `Copy Clean Link` is shown in the `Main menu`
- Verified that `Copy Clean Link` is working and URL link copied without trackers

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/553703be-3b82-494b-9075-4d32dac43b36) | ![2](https://github.com/brave/brave-ios/assets/128532965/eca6a952-11b5-422a-9638-ff57ee67458d) | ![3](https://github.com/brave/brave-ios/assets/128532965/06b4b141-6fdf-49a2-8139-b90a09278248) |
</details>

<details>
<summary> Share menu </summary>

**STEPS:**
1. Launch Brave 
2. Go to https://www.amazon.com/all-new-amazon-fire-tv-stick-4k-max/dp/B0BP9SNVH9/ref=s9_acsd_al_ot_c2_x_1_t?_encoding=UTF8&pf_rd_m=ATVPDKIKX0DER&pf_rd_s=mobile-hybrid-4&pf_rd_r=P9GZHCJP7839WFQXN52C&pf_rd_p=1d9ebc6c-2407-4dc4-86b9-cf0e479e0da9&pf_rd_t=&pf_rd_i=8521791011, for example
3. Tap the `Share` button located in the bottom navigation bar > *Verify `Copy Clean Link` is shown in the menu*
4. Tap `Copy Clean Link` > Insert copied text in any text editor or chat app > *Verify*

**ACTUAL RESULTS:**
- Verified that `Copy Clean Link` is shown in the Sharesheet menu
- Verified  that `Copy Clean Link` is working and URL link copied without trackers

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/49ee5a9b-62b1-4b95-a5de-be0eeb9b2e77) | ![2](https://github.com/brave/brave-ios/assets/128532965/58b930e1-6461-41fd-8f19-a418dfc6605f) | ![3](https://github.com/brave/brave-ios/assets/128532965/8443dcbc-6b51-4693-8f44-ef4a7ac00782) | ![4](https://github.com/brave/brave-ios/assets/128532965/ad397c1b-f2fe-4c09-96c4-2466f2d7a1b5) |

https://github.com/brave/brave-ios/assets/128532965/31fbbe92-cbf9-4dfb-97d2-accd23a75e58
</details>
