### ISSUE TITLE
Portfolio v2

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8072]
### Description: 

Integrate Portfolio v2 designs with NFT tab integrated into Portfolio.

https://www.figma.com/file/muVcmcu4RFNu0LkXe9VRDl/Wallet-2.0?type=design&node-id=4738-346151&mode=design&t=NBz1FjJKMDbkYMY8-4

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.60 (23.11.12.17)
- Verified  Buy / Send / Swap buttons open their expected views and work as expected
- Verified tapping the graph timeframe selector shows the updates correctly 
- Verified price indicator is green for balance increases, red for balance decreases
- Verified tapping on the Assets / NFTs selector shows the Assets/NFTs correctly
- Verified tapping on individual assets & NFTs opens and shows the details as expected
- Verified switching to assets section and opening filters, lists it by network/account and shows outline when expanded or collapsed

iPhone 13 (iOS17.2) | iPad Pro (iOS 16.8.2) | iPhone 7+ (iOS 15.8)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/7ebb96a7-b836-4f83-99ce-dbebc025834b> | <video src=https://github.com/brave/brave-ios/assets/17010094/439bc1c2-3d13-4774-80e6-88d6ccaf4866> | <video src=https://github.com/brave/brave-ios/assets/17010094/2d426796-ec20-4113-b9a5-06463e7ed1d0>
