### ISSUE TITLE
Wallet: NFT grouping

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#8073]
NFT collection should be able to be grouped by accounts or network. 
Same grouping option as in Portfolio

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.60 (23.11.7.17)
- Verified steps from [#8289](https://github.com/brave/brave-ios/pull/8289)
- Verified NFT filter shows options for show/hide Network logo, Hide Unowned NFT and filter based on Account/Network
- Verified filtering based on accounts, filters all NFTs based on Accounts. Also filters hidden NFTs 
- Verified filtering based on network, filters all NFTs based on network. Also filters hidden NFTs
- Verified filtering based on account automatically enabled `Hide Unowned` switch and disabled

iPhone 13 (iOS 17.2) | iPad Pro (iOS 16.7.2) | iPhone 7+ (iOS 15.8)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/035e0ee0-7238-4169-bc46-fe53e5233eb4> | <video src=https://github.com/brave/brave-ios/assets/17010094/fd61ecb1-b513-408f-83ba-8f528a007a13> | <video src=https://github.com/brave/brave-ios/assets/17010094/121a99b5-1665-4e2e-ab6d-257de55a3771>
