### ISSUE TITLE
Crash when reordering tabs in the tab bar [iPadOS 17]

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#8074]
### Description: 
Crash when moving tabs around in the tab bar

Have not reproduced it yet in 1.57

### Steps to Reproduce 
  1. Open a bunch of tabs
  2. Attempt to move some tabs around
  3. After app crashes, moving tabs again will leave empty space

### Actual result: 

https://github.com/brave/brave-ios/assets/17885425/8a87be5e-7d82-4fa7-ad13-6863d02fac2a

### Expected result:
Should not crash

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Happens often but can be difficult to reproduce

### Brave Version:  `1.57.1 (23.9.13.14)`

- Can you reproduce this issue with the most recent build from TestFlight? TBD
- Can you reproduce this issue with the previous version of the current build from TestFlight? TBD
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 
iPad (7th Gen) iPadOS 17.0

**Comment by iccub** [comment]
It is not related to the beta I believe. We see such crash in our logs. Something we should fix soon

**Comment by parsd51** [comment]
Could it be related to?: https://github.com/brave/brave-ios/issues/8058

**Comment by soner-yuksel** [comment]
@parsd51 yeah probably they are related and agree with @iccub we should check this out soon

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iPadOS 17.0` using version `1.60 (23.11.20.17)`

Note: There is currently an OS level issue that produces crash using similar STR and is not fixable on our side. 
Encountered: TBD

- Ensured that crash is not reproducible using STR in https://github.com/brave/brave-ios/issues/8074#issue-1898843911
- Ensured that empty space is not observed after the crash.
