### ISSUE TITLE
Update Browser Colors

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#8078]
### Description: 

Refs https://github.com/brave/roadmap/issues/802

Light/Dark/Private mode color changes for browser specific Chrome:

- Main browser view (top & bottom url bar, tab bar, toolbar)
- Reader mode
- Tab Switcher (note: Old design with new colors, not yet updated to new design yet)
- Favourites & Search overlay (when url bar is highlighted)
- Also removes distinction between "Night Mode" dark mode and regular dark mode

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.2
- iPad Air / iPadOS 16.7.2
Brave build: 1.60 (23.11.9.15)
BraveCore: 1.60.114 (119.0.6045.124)
```
Filed follow-up issue #8396
---------------------------

**STEPS:**
1. Check the following from https://github.com/brave/brave-ios/issues/8078#issue-1901122604

**ACTUAL RESULTS:**
- Verified new UI color in `Dark Mode`, `Light Mode` and `Incognito Mode`
- Verified and compared colors in `Dark Mode` with and without `Night Mode`

---------------------------

|Dark Mode|Light Mode|Incognito|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/e95f45b8-3eaa-4d52-ab38-1c2864f68560) | ![2](https://github.com/brave/brave-ios/assets/128532965/f8e9058b-bf2e-4295-9c44-bf9fe41327dd) | ![3](https://github.com/brave/brave-ios/assets/128532965/1aec5d98-aa05-46c7-8c2b-d4ccd0cd4dc2) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/3f00b6f3-f5ec-4e83-befd-99fb9557f4e8) | ![2](https://github.com/brave/brave-ios/assets/128532965/1a4673a8-1a8b-4ede-9442-a529a64c54c3) | ![3](https://github.com/brave/brave-ios/assets/128532965/a84a9b73-2191-4011-91f4-de22053e94ef) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/c6df5af3-1e56-4217-95f3-cd92689ab233) | ![2](https://github.com/brave/brave-ios/assets/128532965/f547e929-7c3f-43dd-9b10-b90ccb7be339) | ![3](https://github.com/brave/brave-ios/assets/128532965/a71479bc-70e8-4c1e-b978-6ccde0243451) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/5e3a10b5-9ba9-40ae-bd9b-3e87708d60dc) | ![2](https://github.com/brave/brave-ios/assets/128532965/1e1f2f78-a9af-4b64-8c04-f5b95f06950c) | ![3](https://github.com/brave/brave-ios/assets/128532965/294839b0-8c1a-4e13-9dbd-fdca0afecb07) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/7cf9c3a0-9900-4930-aefa-7a09a57470c2) | ![2](https://github.com/brave/brave-ios/assets/128532965/809bfd09-a8b3-47de-9a02-c37da302c7fe) | ![3](https://github.com/brave/brave-ios/assets/128532965/3b19fe6c-964b-4aba-bd03-0b9a8ba5eb3c) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/df2969db-4a15-4591-a9f6-4857cdc6d26f) | ![2](https://github.com/brave/brave-ios/assets/128532965/4bcb475d-dc44-4a62-97ec-e484e54ac85c) | ![3](https://github.com/brave/brave-ios/assets/128532965/5b984941-4c34-4bf5-9957-517b3ea8ad8d) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/77623b79-3e94-435a-ba91-6d89781736f2) | ![2](https://github.com/brave/brave-ios/assets/128532965/4eea6466-83c1-4e26-89a4-3208791ed7e1) | ![3](https://github.com/brave/brave-ios/assets/128532965/a1ad3e85-8f18-40bd-a69a-447b118c4fd5) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/e51220e6-b7d4-43a2-b328-1876e0dcbe55) | ![2](https://github.com/brave/brave-ios/assets/128532965/e628fae0-53b1-4396-849e-1e1f16b2a81f) | ![3](https://github.com/brave/brave-ios/assets/128532965/0f848f8e-daad-49fa-a0be-a24f3025ba27) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/ddeaece7-0e8d-4c9c-905c-0ac031267565) | ![2](https://github.com/brave/brave-ios/assets/128532965/16b2776c-fa63-4887-ad7b-dba5ccf154c8) | ![3](https://github.com/brave/brave-ios/assets/128532965/ba281e4e-6242-407e-89e4-d8950df2bf72) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/e99c529d-fdad-4ecb-aeea-ee8f41c9145f) | ![2](https://github.com/brave/brave-ios/assets/128532965/48d37e5d-a78d-41de-9e1c-382ee9d7d331) | ![3](https://github.com/brave/brave-ios/assets/128532965/481440c1-8c1f-47fe-9e1f-e2d5ad9f51d1) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/fd6c9212-b28b-4fe0-bed9-2fa82af19110) | ![2](https://github.com/brave/brave-ios/assets/128532965/2f964914-cf6a-47d9-ab4e-f159b483487f) | ![3](https://github.com/brave/brave-ios/assets/128532965/6bffe8ca-154f-41b4-81b1-e66874f04053) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/103c7eb2-1f62-4d66-a7ab-7baf991ed5d8) | ![2](https://github.com/brave/brave-ios/assets/128532965/59daead0-448d-4b13-bc3e-22124e0b6c2c) | ![3](https://github.com/brave/brave-ios/assets/128532965/35b0582e-dbe3-4936-9016-d9d5072797e5) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/f875ddf8-1f6c-4216-a646-3af0e86ac43e) | ![2](https://github.com/brave/brave-ios/assets/128532965/a8624d88-8f51-4d73-91e1-5047b4a8d5a8) | ![3](https://github.com/brave/brave-ios/assets/128532965/4f21a85e-4aff-4e03-877e-660a4f87f2ab) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/f64df3d8-e8c8-4f5a-aafe-e9bd1edc8ee8) | ![2](https://github.com/brave/brave-ios/assets/128532965/271fda14-9730-493b-843b-090146d3b433) | ![3](https://github.com/brave/brave-ios/assets/128532965/6d1a1a76-1714-4f4f-917d-f516d14f65f4) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/011f45b4-94d9-4a6a-ae84-d81fd3048731) | ![2](https://github.com/brave/brave-ios/assets/128532965/ece49b6e-ea20-464c-997d-b75504d12e58) | ![3](https://github.com/brave/brave-ios/assets/128532965/c0c4dd15-c663-4395-a513-287863001502) |
