### ISSUE TITLE
Global settings changes should only affect new pages or when an existing page is reloaded

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#808]
### Description: 
Global settings changes should only affect new pages or when an existing page is reloaded. The current behaviour is quite different from desktop. On Desktop this is what happens
1. Visit sites keep default shields settings
2. Block all cookies from global settings
3. Switch to the tab visited in step 1, page doesn't reload but shields shows cookies blocked because global settings is changed, only reload actually causes the global settings to take affect via shields. There is no voluntary reload triggered for any page both active/inactive(background)

But on iOS the current behaviour is

1. Visit sites and keep default shields settings
2. Block all cookies from  settings
3. Active tab reloads without user interaction
4. Disable Block all cookies from settings
5. All open tabs reload to make way for the settings change

**Expected result:**
Behaviour needs to be same on all platforms.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
All the time

**Brave Version:** 
1.7.3

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
#806

**Comment by iccub** [comment]
We could also warn the user that changing a global setting will cause all opened tabs to reload

**Comment by jhreis** [comment]
This change was intentionally reverted.
