### ISSUE TITLE
Portfolio Settings v2

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8089]
### Description: 

Replacement for the `...` menu in Wallet:

<img width="345" alt="settings" src="https://github.com/brave/brave-ios/assets/5314553/da5d1a88-2985-4c32-acb0-191cb4dee02a">

https://www.figma.com/file/muVcmcu4RFNu0LkXe9VRDl/Wallet-2.0?type=design&node-id=4520-426499&mode=design&t=CqFK8MCjLOYmJGsO-0

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.60 (23.11.7.17)
- Verified steps from [#8175](https://github.com/brave/brave-ios/pull/8175)
- Verified Portfolio settings shows new menu
- Verified `Balances`, `Graph` and `NFTs` tab toggles are displayed in rows
- Verified `Balances`, `Graph` and `NFTs` tab toggles are only shown in Portfolio and not on any other tabs
- Verified hiding balance hides it on all assets and portfolio
- Verified able to open Wallet settings from menu itself
- Verified able to lock wallet from menu from any tab
- Verified Help centre opens link in a new tab
- Encountered [#8381](https://github.com/brave/brave-ios/issues/8381)

iPhone 13 (iOS 17.2) | iPad Pro (iOS 16.7.2) | iPhone 7+ (iOS 15.8)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/cbf07a69-5345-4b37-a335-a9c61d67a591> | <video src=https://github.com/brave/brave-ios/assets/17010094/8df38e61-fff7-4331-9598-8936d4bdbb3f> | <video src=https://github.com/brave/brave-ios/assets/17010094/52317ae3-9a61-42a7-9b4e-052d807fa3bf>
