### ISSUE TITLE
Fix NTP-SI P3A total count metric name

### ISSUE THREAD

**Issue by DJAndries** [brave/brave-ios#8092]
The NTP-SI P3A total count metric name is incorrect. On iOS, it's currently `creativeInstanceId.count.total`. In order to correspond with reports from other platforms, the name should be changed to `creativeInstanceId.total.count`.

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `IOS 16.7` using version `1.58 (23.9.26.21)` 

Preconditions: 
1. Will need the iOS debug menu so dev channel build is required
2. Enabled the following BraveCore Switches and corresponding values (see image)
      - `Dont Randomize Upload Interval`
      - `Upload Interval` = 60 (seconds)
      - `Typical Rotation Interval` = 60 (seconds)
      - `Express Rotation interval` = 60 (seconds)
3. App restart may be required
4. User will have to cycle through NTP SI campaign for the creativeinstanceid to show up.

<img width="300" alt="preconditions" src="https://github.com/brave/brave-ios/assets/17885425/010201e7-7863-4905-b1fc-da53751415b2">



- Ensured metric name is `creativeInstanceId.total.count` in histogram logs
- Ensured creativeinstanceid is incremented each time user views NTP SI

logged - https://github.com/brave/brave-ios/issues/8178

![IMG_3549](https://github.com/brave/brave-ios/assets/17885425/a8a4c248-6824-4fda-bd89-2d789f0022fb)
