### ISSUE TITLE
Top-level domain blocking (with interstitial)

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#8096]
### Description: 
Sometimes we block entire (document) pages. In this case we need to show a page telling the user this page is blocked with an ability to continue anyways

**Comment by ShivanKaul** [comment]
@cuba can you clarify, do we currently block pages without an interstitial? What would the user see?

**Comment by ShivanKaul** [comment]
These are some test websites:
1. https://adcash.com/
2. https://actionsplash.com/

**Comment by cuba** [comment]
@ShivanKaul no we do not, however its doable in iOS

**Comment by Uni-verse** [comment]
Verified on `iPhone 12 Pro` running `iOS 17.3.1` using version `1.63 (169)`

- Ensured domain is blocked using test plan in https://github.com/brave/brave-ios/pull/8589#issue-2052898310
- Ensured bringing down Shields will load the page.

Shields up | Shields down
-|-
![IMG_5782](https://github.com/brave/brave-ios/assets/17885425/5bbac731-fe1d-45b5-8d3a-76f4d2749671) | ![IMG_5784](https://github.com/brave/brave-ios/assets/17885425/af139e36-7f2e-46b5-98eb-911a0d791d52)
