### ISSUE TITLE
Incorrect account opening Send from Filecoin asset detail

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8107]
### Description: 

Tapping `Send` on Filecoin asset detail for Filecoin Mainnet will crash if user has no Filecoin accounts

### Steps to Reproduce 
  1. Setup a wallet without any Filecoin accounts or restore a wallet without FIL balance (so no Filecoin accounts are created)
  2. Open FIL on Filecoin Mainnet asset detail screen
  3. Tap Send
  4. Incorrect account is selected for Filecoin mainnet

### Actual result: 

Incorrect account type is selected (not a Filecoin account).
Crashes on debug builds.

https://github.com/brave/brave-ios/assets/5314553/01e1a532-de48-4e43-8330-95f0b90e3ef0

### Expected result:

Prompts to create a Filecoin account

### Reproduces how often: 

Easily reproduced

### Brave Version:

v1.58

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17 running 1.58 (23.9.22.14)
- Verified steps [#8118](https://github.com/brave/brave-ios/pull/8118)
- Verified account creation screen is shown for Filecoin when there are no filecoin account created when selecting Buy/Send from FIL token details screen
- Verified Filecoin Mainnet / Testnet is pre-selected in account creation screen
- Verified correct account is shown when selecting Buy/Send screen


<video src=https://github.com/brave/brave-ios/assets/17010094/4611030d-5541-4a27-acc4-32dfcce2fd10> | <video src=https://github.com/brave/brave-ios/assets/17010094/5f9fd024-0b0a-4500-98b4-96da95b3ee0e>
-- | --
