### ISSUE TITLE
Crash when opening the rewards panel the first time in a fresh install

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#8109]
### Description: 

In 1.59.x there is a crash when you open the rewards panel if it was never turned on in prior installations 

### Steps to Reproduce 
  1. Fresh install
  2. Open rewards panel (ignore onboarding prompt)

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` & `iPad (7th Gen)` running `iOS 17.0.3` & `iPadOS 17.0` respectively using version `1.60 (23.11.7.17)`

Example | Example
-|-
![IMG_5253](https://github.com/brave/brave-ios/assets/17885425/cf4556f6-9454-45de-8bef-9bdceefd1431) | ![IMG_1246](https://github.com/brave/brave-ios/assets/17885425/b283fd65-4a34-4c7c-975f-e212be6047e2)
