### ISSUE TITLE
Sync String Contains Lower Quotations (`,,`)

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#811]
We have ,,'s from the string

![IMG_1613.PNG](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/5624c311-c579-44b5-96d4-359598de808d)

**Comment by GeetaSarvadnya** [comment]
@iccub The device name is not in uppercase quotations. Is this expected?

![IMG-20190314-WA0000](https://user-images.githubusercontent.com/38657976/54375886-e8c1ab80-46a7-11e9-8f43-d9844bf1b5a2.jpg)

**Comment by iccub** [comment]
Yes this is expected, we removed quotation marks from device name

**Comment by GeetaSarvadnya** [comment]
* Verification passed on iPhone 8 - IOS version 12.1.4- Tested on brave version 1.9
* Verified passed with 1.9 (19.3.9.1) on iPad 5th Gen

![IMG_54F8A497DAC6-1](https://user-images.githubusercontent.com/28145373/54382055-8942ac00-4665-11e9-92ac-ae25b361fe06.jpeg)

* Verified passed with 1.9 (19.3.9.1) on iPhone SE
* Verification passed on iPhone 7+/6 and iPad Pro running 1.9(19.3.9.1)
* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR.
