### ISSUE TITLE
Safe Sign support for CoW 🐮 orders

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8114]
### Description: 

Requires Desktop issue: https://github.com/brave/brave-browser/issues/33093

Core has the parsing work done, we should display these requests in our existing Safe Sign UI previously designed for 0x swaps.

Also should investigate using `GetEthTokenSymbol` / `GetEthTokenDecimals` for unknown tokens, currently we are only using `GetTokenInfo` from Asset Ratio Service but it only supports Mainnet.

When finding non-nil `EthSignTypedDataMeta? meta;`, we should display "Free" for the network fee as it's a sign request not a transaction.

cc @onyb

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.4 running 1.24 (24.1.29.12)
- Verified steps from [ brave/brave-ios#8533](https://github.com/brave/brave-ios/pull/8533)
- Verified able to place order on `https://swap.cow.fi`
- Verified able to place order with a custom recipient on `https://swap.cow.fi`
- Verified able to view order details by clicking on the `Details` button in the confirmation screen
- Verified able to place Swap order on native tokens on `https://swap.cow.fi`
- Verified able to place Swap order on unknown tokens via 0x Swap
- Encountered [#8722](https://github.com/brave/brave-browser/issues/36697)

Swap | Custom Address
-- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/685a80e8-1c30-48b6-af2e-a93ccf6f5796> | <video src=https://github.com/brave/brave-ios/assets/17010094/4fd17ca6-55a1-4ec2-b1ad-bfcb3ea19021>
