### ISSUE TITLE
Incorrect account shown in panel after Switch Chain request with non-ethereum account selected

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8115]
### Description: 

When approving a Switch Chain request from an Ethereum DApp with a Solana account selected/displayed in the panel, the network changes to the new chain but the account does not update correctly to display an Ethereum account. Closing and re-opening the panel resolves panel state issue.

### Steps to Reproduce 
  1. Visit Chainlist.org and connect your Ethereum account.
  2. Select Ethereum Mainnet in wallet panel (this ensures Ethereum Mainnet is selected as ethereum network for Chainlist.org).
  3. Select Solana Mainnet in wallet panel
  4. Search for Gnosis or any Ethereum chain you are not currently on, tap `Add to Brave` / `Connect Wallet` button.
  5. Add to Brave if not already added, then tap `Switch` on `Switch Network` panel
  6. Observe `Gnosis` chain displayed in Network Picker capsule and checkmark shown beside Gnosis when Network Selection opened, but Solana Account is still selected in the panel.
  7. Closing the panel and re-opening should correct the network/account state bug.

### Actual result: 

https://github.com/brave/brave-ios/assets/5314553/9b5585c6-9c98-4acc-9d24-0881ec09dd5e

### Expected result:

Ethereum account is shown as selected in panel after switching to Ethereum network via Switch Network request

### Reproduces how often: 

Easily reproduced

### Brave Version: 

v1.58+

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by StephenHeaps** [comment]
@srirambv This should be fine to verify with https://github.com/brave/brave-ios/issues/7723

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17 running 1.58 (23.0.21.21)
- Verified steps from [#8116](https://github.com/brave/brave-ios/pull/8116)
- Verified correct account/network is shown when switching when connected to Dapp

https://github.com/brave/brave-ios/assets/17010094/e0147262-6c1b-4d1d-ac6f-b83b28cab3ee
