### ISSUE TITLE
Backup flow from Accounts tab cannot be completed

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8120]
### Description: 

Tapping `Backup` in Accounts tab, the process cannot be completed / modal is not dismissed after verifying recovery phrase words.

### Steps to Reproduce 
  1. Open Accounts tab
  2. Tap `Backup`
  3. Toggle confirmation switch, enter wallet password and tap `Continue`
  4. Tap `View my recovery phrase` (write it down if not already written down), then tap `Continue`
  5. Enter words requested from recovery phrase
  6. After entering the 3rd and final word from recovery phrase verification, tap `Continue`
  7. Observe nothing occurs

### Actual result: 

No video due to recovery phrase 🤐

### Expected result:

Backup modal dismisses, or shows confirmation screen. Something should happen when `Continue` is pressed

### Reproduces how often: 

Easily reproduced

### Brave Version: 

v1.57+

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

cc @srirambv @nuo-xu

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.0.2 running 1.58 (23.10.11.20)
- Verified steps from issue description
- Verified backup flow completes when initiated from Accounts tab
