### ISSUE TITLE
[AIChat] - Implement Brave-Leo Settings Menu UI

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8126]
## Feature Overview 
- Implement the Brave-Leo settings menu UI

## Implementation Details 
- Implement all of the switches
- Implement model selection menu item
- Implement Linking purchases menu item
- Implement Subscription Management menu item
- Implement reset & clearing data menu item

**Comment by kjozwiak** [comment]
As per https://github.com/brave/brave-browser/issues/36585#issuecomment-1985028037 & https://bravesoftware.slack.com/archives/C04KPE0BUDU/p1709872123838319?thread_ts=1709830872.231289&cid=C04KPE0BUDU, going to close this one off as `QA/No` and `release-notes/exclude` as we'll use https://github.com/brave/brave-browser/issues/36585 as a guide/main issue to run through `Leo` via `1.63.x`.
