### ISSUE TITLE
[AIChat] - Default Model Menu UI

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8127]
## Feature Overview 
- The default model menu UI lets the user select which chat-models they would like to use. Example: Llama vs. Claude

## Implementation Details 
- Implement the UI to allow the user to select different models

**Comment by kjozwiak** [comment]
As per https://github.com/brave/brave-browser/issues/36585#issuecomment-1985028037 & https://bravesoftware.slack.com/archives/C04KPE0BUDU/p1709872123838319?thread_ts=1709830872.231289&cid=C04KPE0BUDU, going to close this one off as `QA/No` and `release-notes/exclude` as we'll use https://github.com/brave/brave-browser/issues/36585 as a guide/main issue to run through `Leo` via `1.63.x`.
