### ISSUE TITLE
[AIChat] - Top Navigation UI

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8128]
## Feature Overview 
- The chat interface has a top navigation bar that contains a three-dot menu

## Implementation Details 
- Implement the top navigation bar's close button
- Implement the top navigation bar's erase/clear chat button
- Implement the top navigation bar's three-dot menu button

**Comment by kjozwiak** [comment]
As per https://github.com/brave/brave-browser/issues/36585#issuecomment-1985028037 & https://bravesoftware.slack.com/archives/C04KPE0BUDU/p1709872123838319?thread_ts=1709830872.231289&cid=C04KPE0BUDU, going to close this one off as `QA/No` and `release-notes/exclude` as we'll use https://github.com/brave/brave-browser/issues/36585 as a guide/main issue to run through `Leo` via `1.63.x`.
