### ISSUE TITLE
[AIChat] - Chat UI Implementation

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8130]
## Feature Overview 
- The Chat has a TextView that displays rich text as a response to summarization or a response from the model
- The Chat has to show the user's prompt above the response
- The Chat has a refresh, copy, thumbs-up, thumbs-down, share menu

## Implementation Details 
- Implement the TextView in a Collection-View with a model to hold the history of the chat
- Implement the prompt above the response with the profile icon and the prompt text itself
- Implement the refresh, copy, rating, share component floating above the chat

**Comment by kjozwiak** [comment]
As per https://github.com/brave/brave-browser/issues/36585#issuecomment-1985028037 & https://bravesoftware.slack.com/archives/C04KPE0BUDU/p1709872123838319?thread_ts=1709830872.231289&cid=C04KPE0BUDU, going to close this one off as `QA/No` and `release-notes/exclude` as we'll use https://github.com/brave/brave-browser/issues/36585 as a guide/main issue to run through `Leo` via `1.63.x`.
