### ISSUE TITLE
[AIChat] - Suggested Follow-Ups UI

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8131]
## Feature Overview 
- The chat has a "Suggested Follow-Ups UI" which has a "Summarize Page" button or other suggested actions

## Implementation Details 

- Check if the suggestions are dynamic and come from Brave-Core to generate the UI, or if the suggestions are static and implement it accordingly.

**Comment by kjozwiak** [comment]
As per https://github.com/brave/brave-browser/issues/36585#issuecomment-1985028037 & https://bravesoftware.slack.com/archives/C04KPE0BUDU/p1709872123838319?thread_ts=1709830872.231289&cid=C04KPE0BUDU, going to close this one off as `QA/No` and `release-notes/exclude` as we'll use https://github.com/brave/brave-browser/issues/36585 as a guide/main issue to run through `Leo` via `1.63.x`.
