### ISSUE TITLE
[AIChat] - Enter Prompt Input UI

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8132]
## Feature Overview 
- A user needs a place to enter their prompt that brings up the keyboard, the ability to dismiss the keyboard, and the ability to enter the prompt with voice-search

## Implementation Details 
- Implement the input field
- Implement the ability to dismiss the keyboard on swipe down
- Implement the ability to enter a prompt via voice-search
- Implement the "send" button change when the text field is not empty

**Comment by kjozwiak** [comment]
As per https://github.com/brave/brave-browser/issues/36585#issuecomment-1985028037 & https://bravesoftware.slack.com/archives/C04KPE0BUDU/p1709872123838319?thread_ts=1709830872.231289&cid=C04KPE0BUDU, going to close this one off as `QA/No` and `release-notes/exclude` as we'll use https://github.com/brave/brave-browser/issues/36585 as a guide/main issue to run through `Leo` via `1.63.x`.
