### ISSUE TITLE
[AIChat] - Provide Feedback UI

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8133]
## Feature Overview 
- The provide Feedback UI allows the user to provide feedback via a drop-down of selected options, and via entering some text or via voice-assistant
-  In a chat, a user can be prompted to "provide feedback" to the AI to let us know whether the response was helpful or not.

## Implementation Details 
- Implement the ability to select an option
- Implement the ability to enter feedback text via keyboard
- Implement the ability to enter feedback via voice-assistant
- Implement the Learn-More link text
- Implement the cancel/submit buttons

**Comment by kjozwiak** [comment]
As per https://github.com/brave/brave-browser/issues/36585#issuecomment-1985028037 & https://bravesoftware.slack.com/archives/C04KPE0BUDU/p1709872123838319?thread_ts=1709830872.231289&cid=C04KPE0BUDU, going to close this one off as `QA/No` and `release-notes/exclude` as we'll use https://github.com/brave/brave-browser/issues/36585 as a guide/main issue to run through `Leo` via `1.63.x`.
