### ISSUE TITLE
[AIChat] - Feedback Submitted UI

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8134]
## Feature Overview 
- Implement the feedback submitted UI where the feedback is removed from the chat interface once submitted

## Implementation Details 
- Remove the Feedback UI from the chat interface once submitted
- Add a Feedback "Toast" that displays the "Feedback was submitted successfully"

**Comment by kjozwiak** [comment]
As per https://github.com/brave/brave-browser/issues/36585#issuecomment-1985028037 & https://bravesoftware.slack.com/archives/C04KPE0BUDU/p1709872123838319?thread_ts=1709830872.231289&cid=C04KPE0BUDU, going to close this one off as `QA/No` and `release-notes/exclude` as we'll use https://github.com/brave/brave-browser/issues/36585 as a guide/main issue to run through `Leo` via `1.63.x`.
