### ISSUE TITLE
[AIChat] - Chat Contextual Menu

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8135]
## Feature Overview 
- The chat as a contextual menu that allows the user to switch models on the fly, go premium, suggest questions, and access settings

## Implementation Details 
- Implement the popover menu
- Add the models to the popover menu and allow the user to select models on the fly
- Add the ability to visit settings
- Add the ability to go premium from the menu

**Comment by kjozwiak** [comment]
As per https://github.com/brave/brave-browser/issues/36585#issuecomment-1985028037 & https://bravesoftware.slack.com/archives/C04KPE0BUDU/p1709872123838319?thread_ts=1709830872.231289&cid=C04KPE0BUDU, going to close this one off as `QA/No` and `release-notes/exclude` as we'll use https://github.com/brave/brave-browser/issues/36585 as a guide/main issue to run through `Leo` via `1.63.x`.
