### ISSUE TITLE
Wallet Line Chart v2

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8136]
### Description: 

Update the design of the line chart used in Portfolio and Asset Details for v2 UI.

<img width="272" alt="line chart" src="https://github.com/brave/brave-ios/assets/5314553/a548038a-55cc-4ebc-8ddc-b79e16182e44">

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.62 (24.1.22.22)
- Verified steps from [#8525](https://github.com/brave/brave-ios/pull/8525)
- Verified wallet portfolio and asset details has line chart v2 

iPhone 13 (iOS 17.3 Beta) | iPad (iOS 16.7.5) | iPhone 7+ (iOS 15.8)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/129c65fc-af38-44d9-ae32-ad436c972ce8> | <video src=https://github.com/brave/brave-ios/assets/17010094/48bf43db-d984-41d5-9eb4-dcf9f08281f9> | <video src=https://github.com/brave/brave-ios/assets/17010094/e6821286-c980-4470-a9ac-a0d70a65d215>
