### ISSUE TITLE
Asset Detail v2

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8137]
### Description: 

Update Asset Detail to v2 designs

<img width="272" alt="asset detail stats" src="https://github.com/brave/brave-ios/assets/5314553/33fa7fd0-fa3c-4046-9a44-77d768bb7c37"> | <img width="269" alt="asset detail accounts" src="https://github.com/brave/brave-ios/assets/5314553/1cdbf7fb-e145-4b48-b7b7-64c05105a1f6"> | <img width="269" alt="asset detail transactions" src="https://github.com/brave/brave-ios/assets/5314553/90df0ce5-649d-49e9-b116-b054c7b7b895">

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.4 running 1.62 (24.1.29.12)
- Verified steps from [#8595](https://github.com/brave/brave-ios/pull/8595)
- Verified asset details view has `Accounts` and `Transactions` tab 
- Verified token details view from Market doesn't have `Accounts` and `Transactions` tab

![image](https://github.com/brave/brave-ios/assets/17010094/d5c1ab83-5cdd-4dda-8cc5-8bcba675e751) | ![image](https://github.com/brave/brave-ios/assets/17010094/b58f8b79-2bbe-4d02-b798-b673d89f84d9) | ![image](https://github.com/brave/brave-ios/assets/17010094/156de01a-5169-42cf-88ed-debfc9687d9d)
-- | -- | --
![image](https://github.com/brave/brave-ios/assets/17010094/f2da40ff-1c2b-4dd1-b56f-63da3bc63ef0) | ![image](https://github.com/brave/brave-ios/assets/17010094/0a6c40ad-448f-4164-9dfa-1126ff7d4a1d) | ![image](https://github.com/brave/brave-ios/assets/17010094/5b796e15-f0ed-46d7-b27c-2acc84933de0)
