### ISSUE TITLE
Background audio does not stop when closing tab 

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#8141]
### Description: 
Background audio does not stop when closing tab 

Note: This is reproducible on 1.57/1.57.1 but seems to be resolved in 1.58

### Steps to Reproduce 
  1. Enable background audio on fresh profile
  2. Open a tab (1)
  3. Open another tab (2)
  4. Open youtube, play video
  5. Open link on this page in new tab (3)
  6. Switch to new tab
  7. Background audio should be playing
  8. Open tab view, close youtube page
  9. Monitor the sound
  10. Close one of the two tabs remaining
  11. Confirm audio should end

### Actual result: 
https://github.com/brave/brave-ios/assets/17885425/7894a790-201a-4b5d-a550-1338506168ed

### Expected result:
Background audio should stop

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Always using STR above

### Brave Version:  `1.57.1 (23.9.20.7)`

- Can you reproduce this issue with the most recent build from TestFlight? NO (1.58)
- Can you reproduce this issue with the previous version of the current build from TestFlight? NO (1.58)
- Can you reproduce this issue with the current build from AppStore? YES

### Device details: 
iPhone X, 16.5.1

**Comment by iccub** [comment]
Should be fixed with https://github.com/brave/brave-ios/issues/8060 please give it a try

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using version `1.57.2 (23.9.25.17)`

- Verified background audio does not continuing after closing out the video tab using https://github.com/brave/brave-ios/issues/8141#issue-1909475823
- Verified background audio stops on fresh profile and existing profile (1.57 -> 1.57.2)
