### ISSUE TITLE
Tab Selection is broken when switching modes

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8146]
### Description: 
When switching between private mode (with persistence) and regular mode, the wrong UI shows and sometimes you cannot exit private mode. https://community.brave.com/t/leaving-private-mode-is-buggy/506403/8

### Steps to Reproduce 
  1. Fresh Install
  2. Enable Settings -> Private Tabs -> Keep Private Tabs
  3. Open New Tab and navigate to Youtube
  4. Open New Tab and navigate to Amazon
  5. Long-Press on any item on Amazon and "Open in New **Private** Tab".
  6. Open the Tab Tray/Switcher
  7. Tap on the "Private" button on the bottom left corner of the tab tray.
  8. Close "Amazon" tab in regular mode using the X icon at the top right corner of the tab in the tab tray.
  9. Switch back to private mode.
  10. Switch back to regular mode.
  11. Press "Done".

### Actual result: 
- Shows "Youtube" in Private Mode UI

### Expected result:
- Should show Youtube in Regular Mode UI.

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily Reproduced

### Brave Version: 
- 1.57.x

### Device details: 
- Any

### Website problems only:
- No

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.5.1` using version `1.57.2 (23.9.25.17)`

- Unable to reproduce using STR in https://github.com/brave/brave-ios/issues/8146#issue-1911709540 on `1.57.2 (23.9.15.17)`

Example | Example
-|-
![Screenshot 2023-09-25 at 6 04 02 PM](https://github.com/brave/brave-ios/assets/17885425/230dd81b-9e6b-470a-a011-bcab45232e0a) | ![Screenshot 2023-09-25 at 6 04 29 PM](https://github.com/brave/brave-ios/assets/17885425/abc9c0a4-e0b3-48e6-8e13-3280006c4d90)

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iPadOS 17.0` using version `1.57.2 (23.9.25.17)`

- Ensured that switching modes does not break tab selection using STR in https://github.com/brave/brave-ios/issues/8146#issue-1911709540

![IMG_1226](https://github.com/brave/brave-ios/assets/17885425/a8ba2d50-1e7d-4933-8923-d46d57246351)
