### ISSUE TITLE
Problem with toggling Sync Types from Settings

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#8148]
### Description: 

Toggling different Sync types are enabling wrong/disabling wrong types

### Steps to Reproduce 
  1. Join Sync Chain
  2. Check Bookmarks is enabled by default
  3. Check enabling other type actually disabling bookmarks
  4. Control checking using Sync Internals

### Actual result: 

After joining sync chain enabling another typer disbles bookmarks

### Expected result:

Joining a Sync chain should enable bookmarks automatically and changing pother types should work properly

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
Any

### Website problems only:
- did you check with Brave Shields down? N-A
- did you check in Safari/Firefox (WkWebView-based browsers)? N-A

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.0]
Brave build: 1.58 (23.9.26.17)
BraveCore: 1.58.129 (117.0.5938.88)
```
---------------------------

**STEPS:**
Followed the steps from https://github.com/brave/brave-ios/issues/8148#issue-1911772444

**ACTUAL RESULTS:**
- Verified that enabling/disabling one type of sync setting is not affecting another one

---------------------------

https://github.com/brave/brave-ios/assets/128532965/5e9fbd66-7059-4189-8612-f03683777e8c
