### ISSUE TITLE
The playlist stops playing when using `PIP` mode

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#8151]
### Description: 

The playlist stops playing when using `PIP` mode.

### Steps to Reproduce 
  1. Launch Brave
  2. Open https://youtube.com or https://music.youtube.com, for example
  3. Add a few video/audio files to the playlist
  4. Open `Playlist` > Play a file
  5. Tap the `PIP` button > Collapse Brave and stay on the home screen or open any other app
  6. Observe, when the file ends playing, the next file is not starting to play

### Actual result: 

Observed, when the file from Playlist ends playing, the next file does not start to play if using `PIP` mode and in another app. And if in `PIP` and Brave is open, the next file starts playing, but if you're on another website, it's opening `Playlist`.

https://github.com/brave/brave-ios/assets/128532965/7812451a-54ed-4fc0-9a33-70838b8b751b

### Expected result:

Playlist files must continue playing when using `PIP` mode, Brave in the background and currently using another app.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.57.2 (23.9.22.21)
BraveCore: 1.57.53 (116.0.5845.114)

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? YES

### Device details: 

Device/OS: iPhone 14 [iOS 17.0]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.62 (24.1.29.12)`

- Ensured next video is played when in PIP mode using Playlist. 
- Ensured next video is played when PIP is enabled when another app is focused. 

<table><tr><td>PIP in Brave</td><td>PIP in another app</td></tr>

<tr><td>

https://github.com/brave/brave-ios/assets/17885425/725d4f97-8501-4849-b455-2ec045f64d06

</td><td>

https://github.com/brave/brave-ios/assets/17885425/f9ee35c0-bd67-4617-b16d-1f07922e4f2c

</td></tr></table>
