### ISSUE TITLE
Update user agent for iOS 17

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#8155]

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iPadOS 17.0` using version `1.60 (23.11.7.17)`

**Desktop**

![Screenshot 2023-11-08 at 4 03 46 PM](https://github.com/brave/brave-ios/assets/17885425/e0f5262b-b982-478a-9b06-e54e266cad0a)

**Mobile**

![Screenshot 2023-11-08 at 4 14 23 PM](https://github.com/brave/brave-ios/assets/17885425/bddd8def-58db-4787-bfcd-725cfda4bda5)
