### ISSUE TITLE
iOS 17 memory leaks causes Wallet user asset migration duplicate assets

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#8160]
Capturing any sort of class inside of a struct that captures via a block leaks.
This will create some zombie store classes that still observe wallet services changes. This results, if user resets wallet then restore a wallet without closing browser will duplicate user assets in Portfolio. 

Steps:
1. Open Wallet
2. Unlock to Portfolio 
3. Click the B/S/S button and choose one of the options
4. Dismiss the screen (memory leaks)
5. Go to settings and reset the wallet 
6. Restore a wallet (has auto-discovery assets) from the wallet landing page.
7. Observe asset duplication in Portfolio 

Note: technically in step 6 restore any wallet with or without auto-discovery assets has a potential to get duplication user assets due to the race-condition caused by this memory leaks. but wallet with auto-discovery assets can reproduce this issue every time. 

More info on leak:
https://github.com/structuredpath/AppleBugReports/tree/main/FB13194873

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 15.7.9 running 1.58 (23.10.11.20)
- Verified steps from issue description
- Verified restoring wallet doesn't duplicate the tokens
- Verified tokens are not duplicated in edit visible assets
- Verified tokens are not duplicated in any B/S/S screens 
- Verified locking/unlocking wallet and auto-discovery doesn't cause any duplication of tokens 
----------
Verification passed on iPad Pro with iOS 16.7 running 1.58 (23.10.11.20)
- Verified steps from issue description
- Verified restoring wallet doesn't duplicate the tokens
- Verified tokens are not duplicated in edit visible assets
- Verified tokens are not duplicated in any B/S/S screens 
- Verified locking/unlocking wallet and auto-discovery doesn't cause any duplication of tokens 
----------
Verification passed on iPhone 13 with iOS 17.0.2 running 1.58 (23.10.11.20)
- Verified steps from issue description
- Verified restoring wallet doesn't duplicate the tokens
- Verified tokens are not duplicated in edit visible assets
- Verified tokens are not duplicated in any B/S/S screens 
- Verified locking/unlocking wallet and auto-discovery doesn't cause any duplication of tokens
