### ISSUE TITLE
[Follow up to #8045] Notification asking to set Brave as the default browser is still shown after an external link opened via the 3P app

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#8163]
### Description: 

Follow-up to #8045

### Steps to Reproduce 
1. Launch Brave 
2. Go through onboarding and don't set it as `Default browser`
4. Launch Gmail > Open a link with Brave
5. Go to device settings > Update time on 2 hours forward
6. Check notification > Observe

### Actual result: 

Observed that notification asking to set Brave as the default browser is still shown after an external link opened via the 3P app

https://github.com/brave/brave-ios/assets/128532965/a1a49727-37ee-4bf1-a139-60abdf0e652c

### Expected result:

Notification must not be shown if an external link is opened via 3P app, like Gmail or Slack.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.58 (23.9.26.17)
BraveCore: 1.58.129 (117.0.5938.88)

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 

iPhone 14 [iOS 17.0]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Reproducible on `iPhone X` running `iOS 16.5.1` using STR in description.

<img width="400" alt="0" src="https://github.com/brave/brave-ios/assets/17885425/f442c55e-e1f7-4d91-bebc-37f85ba3723b">

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.1]
Brave build: 1.58 (23.10.6.14)
BraveCore: 1.58.139 (117.0.5938.153)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-ios/pull/8186#issue-1925012033

**ACTUAL RESULTS:**
- Verified that notification is not shown if an external link is opened via 3P app, like Gmail.

---------------------------

https://github.com/brave/brave-ios/assets/128532965/9053fe47-6962-4298-a494-13b65081f367

https://github.com/brave/brave-ios/assets/128532965/3fcee87e-a049-4ae8-9d6e-02e0a7f5c245
