### ISSUE TITLE
Wallet Bottom Tab Bar

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8166]
### Description: 

Update the current page control at the top of wallet (Portfolio / Activity / Accounts / Market) to be a Tab Bar at the bottom.

<img width="347" alt="Screenshot 2023-09-27 at 3 50 19 PM" src="https://github.com/brave/brave-ios/assets/5314553/d384c7f8-94b1-4859-b9fa-684680824b0e">

https://www.figma.com/file/muVcmcu4RFNu0LkXe9VRDl/Wallet-2.0?type=design&node-id=4738-346151&mode=design&t=NBz1FjJKMDbkYMY8-4

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.2 running 1.60 (23.11.12.17)
- Verified steps from [#8287](https://github.com/brave/brave-ios/pull/8287)
- Verified bottom tabs bar is always shown
- Verified Wallet settings opens up in the same view on all options of tabs bar
- Verified `...` button on Portfolio shows the graph,NFT,balance options
- Verified pending requests show up correctly on Activity tab and works as expected

https://github.com/brave/brave-ios/assets/17010094/a1835022-6173-4870-9c00-8d31391458d1
