### ISSUE TITLE
[Follow up to #7932] `Brave News` opt-in card is not shown after Brave upgrade when News wasn't enabled previously

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#8167]
### Description: 

Follow-up to #7932

### Steps to Reproduce 
1. Change device language and location to `de_DE`
2. Fresh install build `1.57.2` and launch Brave
3. Go through onboarding and land on `NTP` > Confirm that `Brave News` opt-in card is not shown
4. Upgrade Brave to build `1.58` and launch it
5. NTP > Observe that the `Brave News` opt-in card is not shown

### Actual result: 

The `Brave News` opt-in card is not shown on NTP after the Brave upgrade when News wasn't enabled previously.

https://github.com/brave/brave-ios/assets/128532965/f35ac523-dc07-409b-9036-23c9bf2c51a3

### Expected result:

The `Brave News` opt-in card must be shown on NTP after the Brave upgrade when News wasn't enabled previously.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.58 (23.9.26.21)
BraveCore: 1.58.129 (117.0.5938.88)

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 

iPhone 14 [iOS 17.0]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
@vlad-hoff We won't be able to fix this unfortunately, at least for existing users. The language check happens on first launch *_only_*. We don't track when a user explicitly hides opt-in or if the language check ever failed to find and show the opt-in card so we have no way of knowing if a user upgraded and should see opt-in now that a language is supported.

**Comment by hffvld** [comment]
Got it. Thanks for clarification @kylehickinson

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.1]
Brave build: 1.60 (23.11.4.14)
BraveCore: 1.60.105 (119.0.6045.59)
```
---------------------------

**STEPS:**
1. Change device language and location to the `unsupported language region`, for example, `France`
2. Launch Brave > Land on `NTP` > Confirm that the `Brave News` opt-in card is not shown
3. Kill the app
4. Update device language and location to the `supported language region`, for example, `USA`
5. Relaunch Brave > Land on `NTP` > Verify that the opt-in card for the `Brave News` is shown

**ACTUAL RESULTS:**
- Verified that the opt-in card for `Brave News` is shown when changing from `unsupported` to `supported` language/region

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/49144e9e-3324-4c5c-9713-80c6a6f80250) | ![2](https://github.com/brave/brave-ios/assets/128532965/c638e07e-56b1-4948-9f7e-c52b5e60d00c) |
