### ISSUE TITLE
The whole text doesn't fit the size of the `cookie consent notices` pop-up message.

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#8168]
### Description: 

Need to shrink the text on the `cookie consent notices` pop-up message to fit the stings and CTA button in some languages.

### Steps to Reproduce 
  1. Change device language to `German`, `French` or `Russian`, for example
  2. Fresh install and launch Brave > Go through the onboarding flow
  3. Close and relaunch Brave to see the `cookie consent notices` pop-up message > Observe

### Actual result: 

The cookie consent notices pop-up message is too long for the message window in some languages, and some of the text is cut off. The user needs to scroll through it to see the `Got it` CTA button. This is happening, for example, for German, French or Russian languages.

|French|French|German|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/edeeedb4-c44d-44e3-b3da-7107ff8a972e) | ![2](https://github.com/brave/brave-ios/assets/128532965/f144fdc8-7d94-44f5-b6e5-e137859d4f54) | ![3](https://github.com/brave/brave-ios/assets/128532965/a65bb16e-f42f-4d23-8890-06bce60f4975) |
|Russian|Russian|English|
| ![1](https://github.com/brave/brave-ios/assets/128532965/6a0479fd-5e45-4a21-93af-278aa4165a2d) | ![2](https://github.com/brave/brave-ios/assets/128532965/03f229e3-2305-4fea-a34d-5e113518427b) | ![3](https://github.com/brave/brave-ios/assets/128532965/2791613e-b339-481d-b9f4-34e8af216435) |

### Expected result:

The whole text must fit the size of the `cookie consent notices` pop-up message.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.58 (23.9.26.21)
BraveCore: 1.58.129 (117.0.5938.88)

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? YES

### Device details: 

iPhone 14 [iOS 17.0]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
We will most likely drop this modal. may be invalid issue

**Comment by soner-yuksel** [comment]
The popover is removed entirely https://github.com/brave/brave-ios/pull/8230
1.59
