### ISSUE TITLE
Cannot open menu on iPad in split view on iOS 17

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8183]
### Description: 

Tapping the `...` on iOS 17 when in multi-window / split view does not open the menu

### Steps to Reproduce 
  1. Open Brave on iOS 17
  2. Tap system `...` at top-center of screen and select "Split View"
  3. Tap Brave on iPad home screen to open Brave side-by-side with Brave
  4. Tap Brave `...` menu on either window (bottom-right)

### Actual result: 

https://github.com/brave/brave-ios/assets/5314553/cc9e910e-f1a4-4a22-9181-a00439a8ace1

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iPadOS 17.0` using version `1.58 (23.10.6.14)`

- Verified STR in https://github.com/brave/brave-ios/issues/8183#issue-1924896012 and ensured that menu is able to be opened when in split view.
- Ensured menus are opening from bottom and top toolbars when split view enabled.
- Ensured menus are opening when private and normal sessions are loaded in split view.

Example | Example | Example
-|-|-
![IMG_1233](https://github.com/brave/brave-ios/assets/17885425/5372945e-8583-4a71-b80c-294be01e432f) | ![IMG_1234](https://github.com/brave/brave-ios/assets/17885425/da76b309-f886-4244-b287-1a74f1b4e392) | ![IMG_1235](https://github.com/brave/brave-ios/assets/17885425/1980f4f1-7240-43f3-9176-4320296df776)
