### ISSUE TITLE
Adblock crash

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#8191]
The application crashes periodically. This is more prevalent on older devices such as an iPhone 6s.

On newer devices, The cause of this is trying to compile too many filter lists in parallel where memory might grow when compiling too fast beyond a reasonable threshold. Even when compiling in series, memory might grow when there is no throttling in place. However it is unlikely to crash unless compiling 500 filter lists. But as a precaution a small delay should be added for older devices or if the device is under stress.

On older devices iPhone 6s, no matter how we throttle the compilation we still get crashes when compiling more than ~37 filter lists even if they are throttled and in series.

**Comment by Uni-verse** [comment]
Verified on the following devices using version `1.58 (23.10.17.8)`

iPhone 12 Pro, iOS 17.0.3
iPhone X, iOS 16.7
iPhone XR, iOS 15.5
iPad (7th Gen), iOS 17.0
 
 Encountered: https://github.com/brave/brave-ios/issues/8277
 
- Ensured that filter lists selection is limited to 30 on older devices such as iPhone X, XR.
- Ensured that newer devices (iPhone 12 Pro+) are able to enable all filter on the page.
- Ensured that crash does not happen on fresh profile on older or new devices. 
- Ensured that opening many tabs with filter lists enabled does not cause crash or sluggishness.
- Ensured that crash is not observed when upgrading. 

iPhone 12 Pro | iPad Gen 7
-|-
![IMG_5193](https://github.com/brave/brave-ios/assets/17885425/55d15afe-dc82-4d2e-833f-3a17a5368f38) | ![IMG_1241](https://github.com/brave/brave-ios/assets/17885425/df0f0e5a-17d0-4f30-be77-4271faec7435)
