### ISSUE TITLE
Apple Search Ads Install Attribution

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#8203]
## Problem Description 

Search `Apple Search Ads: Install Attribution` on `Google Doc` for basic requirement break down

### Additional information 

After fetching [attribution token](https://developer.apple.com/documentation/ad_services/aaattribution/3697093-attributiontoken) this token will be used on `ad services api`  (https://api-adservices.apple.com/api/v1/) in order to fetch attribution payload from Apple.

This payload contains information indicating if user had search ad impression and campaignId.

Field | Data type | Description
-- | -- | --
attribution | Boolean | The attribution value. A value of true returns if a user clicks an Apple Search Ads impression up to 30 days before your app download. If the API can’t find a matching attribution record, the attribution value is false.
campaignId | Integer | The unique identifier for the campaign.Use Get Campaign-Level Reports in the Apple Search Ads Campaign Management API to correlate your attribution response by campaignId.
conversionType | String | The type of conversion is either Download or Redownload.Conversion types appear in your campaign reports in the Apple Search Ads Campaign Management API. See the ExtendedSpendRow object for more information.
countryOrRegion | String | The country or region for the campaign.Use Get Campaign-Level Reports to correlate your attribution response by countryOrRegion in the Apple Search Ads Campaign Management API.

After fetching proper payload this information will be used to generate a a proper referral code and will be passed with existing mechanism.

The privacy security review for Install Attribution https://github.com/brave/reviews/issues/1312

First attribution field is checked if install is coming from search ad and if it does the referral code is prefix with `ASA`. 

If not it checked user referral program can provide a code if empty organic install code 001 is actually prefixed with `BRV`.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.0.1` using version `1.60 (23.11.16.15)`

**Preconditions:**

1. Fresh install dev channel build
2. View URP logs in debug settings menu on first launch
3. Relaunch browser
4. View URP logs for attribution logs / ref code

- Ensured that `DAU ping with added ref` is not logged on fresh install.
- Ensured that DAU ping is logged after re-launching browser.
- Ensured that reference code is of type `ASA` as this is test reference code when installing from TF.

Example | Example
-|-
![IMG_5279](https://github.com/brave/brave-ios/assets/17885425/ba658361-5f81-40e1-8106-fa18f3f6fa31) | ![IMG_5280](https://github.com/brave/brave-ios/assets/17885425/9500a808-ccea-419f-bd1f-f85685739b75)
