### ISSUE TITLE
Wallet: NFT spam management improvement 

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#8205]
1. Update NFT to have 2-section instead of 3 (Collection/Hidden/Spam -> Collection/Hidden)
2. Update actions for NFTs under `Collection` to have actions of 
- Hide 
- ~~Mark as junk~~
- Don't show in wallet
3. Update actions for non-junk NFT under `Hidden` to have actions of 
- Unhide 
- ~~Mark as junk~~
- Don't show in wallet
4. Update actions for junk NFT under `Hidden` to have actions of
- Mark as not junk 
- Don't show in wallet 
5. Add a `JUNK` label on the top left of any junk NFT

<img width="509" alt="Screenshot 2023-10-06 at 4 50 18 PM" src="https://github.com/brave/brave-ios/assets/1187676/21a653e8-1621-428b-b6b9-b7561cbb4ab3">

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.60 (23.11.23.16)
- Verified steps from [#8226](https://github.com/brave/brave-ios/pull/8226)
- Verified NFT tab has `Collected` and `Hidden` option in dropdown with number indication
- Verified restoring a wallet with NFTs and switching to NFT tab prompts for `Auto discover`
- Verified selecting `Auto-discover` finds and loads all the owned NFTs
- Verified able to manually add NFTs that aren't owned by the wallet
- Verified all owned NFTs are listed under `Collected`
- Verified `Junk` NFTs are listed under `Hidden` by default 
- Verified `Junk` NFT has `Junk` label added to it
- Verified long press on collected NFT shows `Hide` and `Don't Show in Wallet` options
- Verified selecting `Hide` on a collected NFT moves the NFT to `Hidden` section
- Verified long press on a junk NFT shows `Mark as Not Junk` and `Don't Shown in Wallet`
- Verified selecting `Mark as Not Junk` removes the junk label and moves it to `Collected` 
- Verified there is no option to mark a collected NFT as `Junk`
- Verified `Don't Show in Wallet` in collected/hidden, removes the NFT from view but wallet address is still the owner
- Verified hiding an NFT from view hides it in Portfolio and in Send screen
- Verified hiding an NFT doesn't list it when searched on Send screen but still shows up on Edit Visible assets and Account details screen

<details>
<summary>Screenshots</summary>


| iPhone 13 (iOS 17.2) | iPad Pro (iOS 16.7.2) | iPhone 7+ (iOS 15.8) |
|--------|--------|--------|
| ![image](https://github.com/brave/brave-ios/assets/17010094/6d3e4fe2-6152-490b-824e-e474c4fc81b3)| ![IMG_0030](https://github.com/brave/brave-ios/assets/17010094/e1c2bb77-027a-43f2-9144-2de4491d6872)| ![image](https://github.com/brave/brave-ios/assets/17010094/c5391421-920c-4113-b365-3d832c8334b7)|
| ![image](https://github.com/brave/brave-ios/assets/17010094/288fd672-356a-4cc4-9a55-177dd0cfeca5) | ![IMG_0035](https://github.com/brave/brave-ios/assets/17010094/d7328000-3584-4190-a2a4-c3ef599333f8) | ![image](https://github.com/brave/brave-ios/assets/17010094/1a3b4e07-c5b6-42cd-b9ad-0eeb1baf561b) |
| ![image](https://github.com/brave/brave-ios/assets/17010094/5be43c34-86d9-46c4-82f6-977cad8c28c2) | ![IMG_0032](https://github.com/brave/brave-ios/assets/17010094/01d16361-d107-4e14-8c91-98ff06debb49)| ![image](https://github.com/brave/brave-ios/assets/17010094/3857e7bf-b518-472d-943f-9ccbc76d0874) |
| ![image](https://github.com/brave/brave-ios/assets/17010094/f9fb53c8-c11e-427e-bf3e-1b0c3d128bd8) | ![IMG_0033](https://github.com/brave/brave-ios/assets/17010094/62857c25-391d-4bea-8e86-a3e3fa925ca7)| ![image](https://github.com/brave/brave-ios/assets/17010094/7e8faf13-5c36-4390-ab64-cd55cf95a2c4)| 
| ![image](https://github.com/brave/brave-ios/assets/17010094/63ca7594-1d51-418e-a547-3bdc48868ec1) | ![IMG_0034](https://github.com/brave/brave-ios/assets/17010094/94750a68-9834-4f93-bbe6-61ee4f3aecd7)| ![image](https://github.com/brave/brave-ios/assets/17010094/723ff478-5e59-4309-a5ed-6db995819799)| 

</details>
