### ISSUE TITLE
Back-Forward list favicon rendered incorrectly

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#8206]
![IMG_0903](https://github.com/brave/brave-ios/assets/6950387/802af923-20cb-4df1-b845-40b1ffdabbd6)

**Comment by Uni-verse** [comment]
Verified on `iPhone 12 Pro` running `iOS 17.0.3` using version `1.60 (23.11.7.17)`

- Ensured that Back-Forward buttons render favicons correctly on fresh install and existing profiles.

Back (light) | Back (dark) | Forward (dark)
-|-|-
![IMG_5260](https://github.com/brave/brave-ios/assets/17885425/589b297a-7751-4e06-bf32-2575e90c9ebf) | ![IMG_5261](https://github.com/brave/brave-ios/assets/17885425/c59c52e4-ea3a-4f13-85b3-d28f3fb738e7) | ![IMG_5262](https://github.com/brave/brave-ios/assets/17885425/de774fd2-3bf6-4d6f-8355-82ecf0490dd5)
