### ISSUE TITLE
Remove dislike ad button

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#8211]
Users are disliking most ads on iOS. So, we need to disable and discuss the UX at a later date. Users are unable to dislike on Android.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.0.3` using version `1.60 (23.11.4.14)`

- Verified the dislike button and swipe sideways dismiss capability has been removed from ad notifications.
- Verified that user can still dismiss ad by swiping upward.
- Verified tapping on the ad will load the landing page.

<img width="300" alt="1" src="https://github.com/brave/brave-ios/assets/17885425/15e22612-560b-480a-9bc2-391aa0f483de">
