### ISSUE TITLE
App crashes on launch when using a language that Brave supports but Chromium/brave-core doesn't

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#8213]
### Description: 

Brave has its own set of localized languages that are independent from Chromium's list. When the app launches it loads the Chromium resource packs for the selected language the user is using, however there are languages that are supported by Brave but not Chromium such as `pt_BR` (Chromium only has `pt` and `pt_PT`). This fails to find load the resource pak since that language isn't localized and results in a failed [`CHECK`](https://github.com/brave/brave-core/blob/82b05012fc6b5ab8535cf283db6856ad5eedd7eb/ios/browser/brave_web_main_parts.mm#L48)

### Steps to Reproduce 
  1. Set language to Portuguese (Brazil) (should also crash with certain Korea/China language/region combos)
  2. Launch the app

### Actual result:
Crashes

### Expected result:
Fall back to Chromium supported languages and don't crash

### Reproduces how often: 
Always

### Brave Version:
I believe we saw this crash log in 1.58, but tested and confirmed in 1.59+

**Comment by iccub** [comment]
Should be fixed as a part of latest core bump, please test using the STR

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.58 (23.10.17.18)`

- Verified STR in https://github.com/brave/brave-ios/issues/8213#issue-1935673121 and confirmed Brave app does not crash using `pt_BR` locale.
- Verified user is able to re-launch Brave with crashing.
- Verified launching Brave without issues on fresh install as well as existing profile in pt_Br locale.

Example | Example | Example
-|-|-
![IMG_3588](https://github.com/brave/brave-ios/assets/17885425/1db402fb-6747-49fb-8ff7-bf398bb96fbd) | ![IMG_3589](https://github.com/brave/brave-ios/assets/17885425/d127cb2e-dd46-437b-9578-1f72d671cc9c) | ![IMG_3590](https://github.com/brave/brave-ios/assets/17885425/1b8b3f2d-361d-4fed-929b-e8e14348e724)
