### ISSUE TITLE
Remove cookie consent info popup

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#8217]
platform parity

**Comment by hffvld** [comment]
Verified on `iPhone 14`  using version(s):
```
Device/OS: iPhone 14 / iOS 17.1
Brave build: 1.60 (23.11.4.14)
BraveCore: 1.60.105 (119.0.6045.59)
```
---------------------------
<details>
<summary> Fresh install </summary>

**STEPS:**
1. Fresh install build `1.60` and launch Brave 
2. Go through the onboarding flow until you land on NTP
3. Tree-dot menu > Settings
4. Brave Shields & Privacy > Block Cookie Consent Notices > Verify that toggle switch is `ON`
5. Go back to `NTP` and open https://amazon.co.uk > Verify that cookie consent is blocked
6. Close and Relaunch Brave > Verify that `Block Cookie Consent Notice` is not shown

**ACTUAL RESULTS:**
- Verified that the `Block Cookie Consent Notices` 
- Verified that cookie consent is blocked when opening websites
- Verified that `Block Cookie Consent Notice` is not shown anymore (before it was shown in the 2nd Brave launch)

---------------------------

https://github.com/brave/brave-ios/assets/128532965/af27908c-5d18-4833-a74f-1e43f2f388fe

</details>

<details>
<summary> Upgrade install </summary>

**STEPS:**
1. Fresh install build `1.58.2` or lower (the one where cookie consent is shown) and launch Brave 
2. Go through the onboarding flow until you land on NTP
3. Tree-dot menu > Settings
4. Brave Shields & Privacy >  > Verify that the toggle switch is `ON`
5. Go back to `NTP` and open https://amazon.co.uk > Verify that cookie consent is blocked
6. Close and update Brave to build `1.60`
7. Launch Brave > Verify that `Block Cookie Consent Notice` is not shown
8. Open https://amazon.co.uk > Verify that cookie consent is blocked

**ACTUAL RESULTS:**
- Verified that the `Block Cookie Consent Notices` toggle switch is `ON` by default after Brave upgrade
- Verified that cookie consent is blocked when opening websites
- Verified that `Block Cookie Consent Notice` is not shown anymore (before it was shown in the 2nd Brave launch)

---------------------------

https://github.com/brave/brave-ios/assets/128532965/0ada2089-5f80-43c4-a649-24deec66fd56

</details>
