### ISSUE TITLE
Aggressive only mode is not being applied to regional filter lists

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#8218]
### Description: 
Some filter lists should be treated as always aggressive. But this is not the case. 

### Steps to Reproduce 
  1. Ensure cookie consent notice blocking is enabled
  2. Go to https://www.jimmycarr.com/
  3. See the cookie consent notice

### Actual result: 
Sees the cookie consent notice

### Expected result:
Should not see cookie consent notice

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

### Brave Version: 
1.58

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details: 
N/A

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.0.3` using version `1.58 (23.10.16.14)`

- Verified STR in https://github.com/brave/brave-ios/issues/8218#issue-1937990430
- Verified cookie consent notice is not shown

Example | Example
-|-
![IMG_5162](https://github.com/brave/brave-ios/assets/17885425/9fc1a2d9-5b06-4b9a-bd8a-1fb4f8639fd7) | ![IMG_5163](https://github.com/brave/brave-ios/assets/17885425/1e6dc84d-adea-44a2-9cbb-877625d2144e)
