### ISSUE TITLE
Fix issue where content blockers are sometimes removed and recompiled during launch

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#8219]
### Description: 
Sometimes the content blockers are removed and recompiled unnecessarily during launch. 
This cannot be tested.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
At the very least the adblocking aspect should be sanity tested after this change

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.0.3` using version `1.58 (23.10.17.8)`

Sanity tested the following areas

_Content ads / Video ads_

- Ensured that content ads are blocked on `youtube.com`, `x.com` and other sites with default settings on fresh install.
- Ensured that preroll ads are not shown for youtube videos when Shields are up. Bringing down Shields will show the ads.
- Ensured adblocking is working in `standard` and `aggressive` modes

Example | Example
-|-
![IMG_5187](https://github.com/brave/brave-ios/assets/17885425/f0fcaf32-42a2-4007-8a6f-dfcab18a9d39) | ![IMG_5188](https://github.com/brave/brave-ios/assets/17885425/4eaecb09-2c2d-4725-8ca4-a22626f325a5)

_Cosmetic Filtering_

Example | Example | Example | Example
-|-|-|-
![IMG_5174](https://github.com/brave/brave-ios/assets/17885425/1a7e9424-d647-405c-bf7e-5d0dffcee47b) | ![IMG_5175](https://github.com/brave/brave-ios/assets/17885425/ed6619bb-6f40-4b3c-8bb4-09183ee999ae) | ![IMG_5189](https://github.com/brave/brave-ios/assets/17885425/618206b7-476e-47ca-ae8a-14b66b87bd2e) | ![IMG_5184](https://github.com/brave/brave-ios/assets/17885425/53c9993b-e5ef-433a-a244-e8e49d343336)
![IMG_5183](https://github.com/brave/brave-ios/assets/17885425/5020e293-fd7a-4c54-8424-f66534b39773) | ![IMG_5175](https://github.com/brave/brave-ios/assets/17885425/d413d094-e673-4b68-af3a-59996650b3a4) | ![IMG_5182](https://github.com/brave/brave-ios/assets/17885425/2d9349a3-f700-4bce-a43e-0a50eeb0247d) | ![IMG_5185](https://github.com/brave/brave-ios/assets/17885425/fad648c1-9b3a-4edf-8bd6-56c434d850a6)


_Cookie Consent Notice_ 

Example | Example
-|-
![IMG_5173](https://github.com/brave/brave-ios/assets/17885425/68a02fb4-2fed-44d3-b34c-316cf463f7e0) | ![IMG_5181](https://github.com/brave/brave-ios/assets/17885425/07e0dc96-6c40-4e26-a916-86531f979ff2)


_Tracking Content_

<img width="300" alt="0" src="https://github.com/brave/brave-ios/assets/17885425/ea4451dd-b427-48ce-9b8d-8eb648594a04">
