### ISSUE TITLE
Youtube ads are leaking, mostly on iPad

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#8239]
Ads are leaking. We investigate it and look for a proper fix.
It seems to affect all browsers and extensions currently

https://bravesoftware.slack.com/archives/C3GNZANPR/p1696994460127209

**Comment by Saoiray** [comment]
Want to add in that some have mentioned this on MacOS as well. Perhaps I should have left topics separate, but merged everything together over at https://community.brave.com/t/cumulative-topic-for-shields-causing-offline-message/510642 except for the Japan topic at https://community.brave.com/t/youtube/509858

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iPadOS 17.0` using version `1.58 (23.10.16.14)`

- Ensured ads are not shown on youtube.com when user is either logged in or not.
- Ensured pre-roll ads are not shown when viewing videos on youtube.com.
- Ensured ads are not shown in private tabs.
- Ensured ads are shown when disabling shields or ad blocking.
- Ensured ads were not shown on existing profile after upgrading on youtube.com

Example | Example | Example | Example
-|-|-|-
![IMG_1236](https://github.com/brave/brave-ios/assets/17885425/95370435-5cb4-44f4-a20c-1b30bac92b21) | ![IMG_1237](https://github.com/brave/brave-ios/assets/17885425/fef27bef-46b3-4a90-99b2-8c2a8fea49d3) | ![IMG_1238](https://github.com/brave/brave-ios/assets/17885425/a9ac2da1-d46a-438b-a686-7dea0cccb498) | ![IMG_1239](https://github.com/brave/brave-ios/assets/17885425/4fa14828-3f48-4ab9-a01e-f43dadc7eb29)
