### ISSUE TITLE
`Learn more` on the Brave Rewards panel overlaps other text

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#8243]
### Description: 

`Learn more` on the Brave Rewards panel overlaps other text.

### Steps to Reproduce 
  1. Launch Brave
  2. Enable `Rewards` by tapping BR icon in the URL search bar or by going to the settings
  3. Open any unsupported website, for example https://amazon.com
  4. Tap BR icon > Observe. Sometimes you need to reopen BR panel multiple times (~2 - 10 times) to see the issue.

### Actual result: 

`Learn more` for unsupported websites on the Brave Rewards panel overlaps other text. This is happening on iPad in both `Landscape` and `Portrait` mode, but I wasn't able to reproduce it on iPhone.

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/e2d3309f-00a3-4b9b-85e3-0fd5117b4d93) | ![2](https://github.com/brave/brave-ios/assets/128532965/05509048-f221-4dd9-9324-ecd14efdc614) |

### Expected result:

`Learn more` must not overlap other text on BR panel.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.58 (23.10.12.20)
BraveCore: 1.58.139 (117.0.5938.153)

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? YES

### Device details: 

Device/OS: iPad Air [iPadOS 16.5.1]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
Probably fixed by https://github.com/brave/brave-ios/commit/533cebf2e854d218f360274aee397994b994d789 (1.60.x)

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 [iOS 17.1]
- iPad Air [iPadOS 16.5.1]
Brave build: 1.60 (23.11.4.14)
BraveCore: 1.60.105 (119.0.6045.59)
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-ios/issues/8243#issue-1940826656

**ACTUAL RESULTS:**
- Verified that `Learn More` is not overlapping with other strings
- Verified the same on `iPad` and `iPhone`

---------------------------

|iPad|iPhone|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/7a5912b7-b4de-4c2b-aec7-8f082f18f625) | ![2](https://github.com/brave/brave-ios/assets/128532965/fc843e1a-d19d-4234-9bf2-6a47c17c391e) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/de17e967-93c3-4f78-a801-0136ebfdacfe) | ![2](https://github.com/brave/brave-ios/assets/128532965/b911b564-4c07-4224-a245-514a3cc2b183) |
