### ISSUE TITLE
Ads are not shown after enabling rewards on fresh profile

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#8244]
### Description: 
Ads are not shown after enabling rewards on fresh profile

### Steps to Reproduce 
  1. Fresh install (dev channel)
  2. Enable log verbosity level 6
  3. Enable rewards
  4. Wait for some ads
  5. Enable news for inline ads

### Actual result: 
No ad notifications

### Expected result:
Ads should be shown

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

### Brave Version: 
1.58 (23.10.11.20)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 
iPhone

**Comment by kjozwiak** [comment]
@vldmrkl @Uni-verse there's also several cases that @aseren mentioned/wrote up via https://github.com/brave/brave-core/pull/20511#issue-1940918264 that can be used when verifying the above 👍

**Comment by iccub** [comment]
Fixed in latest build, please retest

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.58 (23.10.17.8)`

- Ensured the following cases are working as expected based on test plan in https://github.com/brave/brave-core/pull/20511#issue-1940918264

**_Upgrade Path_** 

- Ensured that ads are shown after installing 1.57.x, enabling Rewards and then upgrading to 1.58.x
- Ensured that ads can be viewed after clicking on the notification.

**_NTP SI_**

- Ensured NTP Sponsored Images are shown when Rewards is in enabled state.
- Ensured NTP Sponsored Images are shown when Rewards is in disabled state (re-launching the browser or opening a new tab after changing state).
- Ensured NTP Sponsored Images are shown after enabling Rewards and then disabling it.
- Ensured clicking the sponsored image link will open the landing page. 

Example | Example | Example
-|-|-
![IMG_3594](https://github.com/brave/brave-ios/assets/17885425/9074432e-3954-4eca-913d-a797bf52b7b7) | ![IMG_3595](https://github.com/brave/brave-ios/assets/17885425/82a39064-9dfd-4317-877c-d37c5dd75692) | ![IMG_3592](https://github.com/brave/brave-ios/assets/17885425/cfed8344-c3ff-4108-99fd-e5aa7732ef2b)


**_News Ads_**

- Ensured news ads are shown when Rewards is in enabled state.
- Ensured news ads are shown when Rewards is in disabled state.
- Ensured news ads are shown after enabling Rewards and then disabling it.
- Ensured that user is taken to the landing page after tapping on the inline news ad.

Example | Example
-|-
![IMG_3597 3](https://github.com/brave/brave-ios/assets/17885425/785a4c93-b428-4ccf-a04b-676a75408957) | ![IMG_3596 2](https://github.com/brave/brave-ios/assets/17885425/5aca25b2-8a8b-40d1-b63c-4a5be6eafb64)


**_Ad Notifications_**

- Ensured ad notifications are shown when Rewards is in enabled state.
- Ensured ad notifications are not shown when Rewards is in disabled state.
- Ensured ad notifications are not shown after enabling Rewards and then disabling it.
- Ensured that user is taken to the landing page after tapping on the ad.

Example | Example | Example
-|-|-
![IMG_3599](https://github.com/brave/brave-ios/assets/17885425/85c15730-bde9-4b6b-b0ad-fe2a237a1839) | ![IMG_3591](https://github.com/brave/brave-ios/assets/17885425/215c2a8f-0a49-4bad-b39f-0b5157035767) | ![IMG_3592](https://github.com/brave/brave-ios/assets/17885425/1c90f6e6-9f76-4d64-8947-bd051a7d56ae)
