### ISSUE TITLE
Sometimes songs from YT Music can't be loaded into the Playlist buffer

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#8246]
### Description: 

Sometimes songs from YT Music can't be loaded into the Playlist buffer and the error is shown.

### Steps to Reproduce 
  1. Launch Brave
  2. Open https://music.youtube.com
  3. Play some music (with or without video) > Add media files to the Playlist
  4. Open Playlist > Play these files > Observe

### Actual result: 

Sometimes songs from YT Music can't be loaded into the Playlist buffer and the error is shown.

- I tried older Brave builds and the issue is reproducible there as well, so, I'm not sure if this is a server-side/back-end issue, because I didn't notice this issue before.
- I was able to reproduce it on iPad and iPhone.
- Also I was able to reproduce it for the videos from YT.

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/90bdecca-212b-4044-bb8b-9fc73f0f17a5) | ![2](https://github.com/brave/brave-ios/assets/128532965/df8b7800-8c6b-46d5-b7cd-a3f42e355e41) |

https://github.com/brave/brave-ios/assets/128532965/0f374eaf-936e-4433-8868-974b7d4c64ca

### Expected result:

Added to the Playlist song or video file must be buffered and playable.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

Brave build: 1.58 (23.10.13.14)
BraveCore: 1.58.139 (117.0.5938.153)

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? YES

### Device details: 

- iPhone 14 [iOS 17.1]
- iPad Air [iPadOS 16.5.1]

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Brandon-T** [comment]
This was due to a blob issue and should be fixed already :)
