### ISSUE TITLE
Fix shields parity between desktop and iOS

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#825]
Shields behaviour should be same on all platforms. Currently there is parity between desktop and iOS on how individual feature of shields work

#### HTTPS: 
Desktop:
1. Visit any site in a new tab
2. Disable HTTPS globally 
3. Shields shows the change from step 2 but only affects when existing page is reloaded

iOS:
1. Visit any site in a new tab
2. Disable HTTPS globally 
3. Active tab is automatically reloaded to make the changes

#### Cookies:
Desktop:
1. Visit any site in a new tab
2. Disable all cookies globally 
3. Shields shows the change from step 2 but only affects existing page when its reloaded 

iOS:
1. Visit any site in a new tab
2. Disable HTTPS globally 
3. Active tab reloads automatically to block cookies

**Comment by tildelowengrimm** [comment]
We do not expect to have Shields parity between desktop and iOS. The limitations of WKWebView mean that a lot of shields functionality will be slightly different on iOS.
