### ISSUE TITLE
Brave News Ads do not appear after rewards is toggled on & off

### ISSUE THREAD

**Issue by aseren** [brave/brave-ios#8254]
Found in version 1.60.x

### Steps to Reproduce 
  1. Run fresh install
  2. Enable Brave Rewards
  3. Disable Brave Rewards
  4. Enable Brave News

### Actual result: 
Brave News Ads are not requested/shown in the feed

### Expected result:
Brave News Ads should appear in the feed

**Important note**: Ads are requested/shown after browser restart.

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.0.3` using version `1.58 (23.10.16.20)`

Using STR in https://github.com/brave/brave-ios/issues/8254#issue-1945617363, verified News ads are shown after rewards is toggled on & off.

Setup:

1. Fresh install on dev channel
2. Enable staging env for rewards and news
3. Relaunch browser
4. Enable Brave Rewards
5. Disable Brave Rewards
6. Enable Brave News

<img width="500" alt="0" src="https://github.com/brave/brave-ios/assets/17885425/f9316dad-48f9-4cf6-bddb-1509b3193640">
