### ISSUE TITLE
Reordering Favourites shows duplicated items

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#8255]
### Description: 

Noticing a weird thing on both release and dev, when dragging the bookmarks favourites to reorder them, the icons duplicate one of the icons.
When opening a new tab, restart, or leaving the NTP, it seems to correct itself

### Steps to Reproduce 
  1. Open Browser
  2. Create a new empty tab and order favourites in NTP

starting: A B C D
drag D between A & B
shows: A B C C
clicking the “new B” will send to D

### Actual result: 

![213131](https://github.com/brave/brave-ios/assets/6643505/4cf7105a-9ac1-473b-98b6-e7879252e0c7)

### Expected result:

Organize favourites with no problem

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily Reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
iOS 17 iPhone X 17.0.3

### Website problems only:
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information
Reported by @iambrianfung

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.0.3` using version `1.60 (23.11.7.17)` 

- Ensured Favorites are not duplicated using the STR in https://github.com/brave/brave-ios/issues/8255#issue-1945629314.
- Ensured that moving around newly added Favorites does not cause favicon duplication or sends user to incorrect url.

Fresh install | Moving D to B | Tapping on new B
-|-|-
![IMG_5264](https://github.com/brave/brave-ios/assets/17885425/fab6d60d-d59b-4339-af5e-dfd389ae436e) | ![IMG_5265](https://github.com/brave/brave-ios/assets/17885425/87c47eb9-321a-4953-9bb1-51f31c578e97) | ![IMG_5266](https://github.com/brave/brave-ios/assets/17885425/8446778a-2822-4f09-b9bf-47a2981fe690)
