### ISSUE TITLE
Fix issue with 3rd party check

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#8259]
### Description: 
In iOS we are comparing hosts for a 3rd party check due to an invalid understanding of content blocker 3rd party checks. 

### Steps to Reproduce 
  1. Go to `https://nypost.com/`
  2. Attempt to log-in with shields on and standard mode

### Actual result: 
Cannot login and no error presented

### Expected result:
Could log in with standard mode

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

### Brave Version: 
1.58

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details: 
Any

### Website problems only:
- did you check with Brave Shields down? Works
- did you check in Safari/Firefox (WkWebView-based browsers)? Works

### Additional Information
Invalid 3rd party check comparing host instead of domain.

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 [iOS 17.1]
Brave build: 1.58 (23.10.17.8)
BraveCore: 1.58.141 (117.0.5938.153)
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-ios/issues/8259#issue-1946203274

**ACTUAL RESULTS:**
- Verified that the user is able to sign in to https://nypost.com/ using an `email`
- Verified that the user is able to sign in to https://nypost.com/ using `Google sign in`
- Verified above behavior when `Shields` are ON and `Trackers & Ads Blocking` set to `Aggressive`, `Standard` and `Disabled`

---------------------------

*Sign in with an email*

https://github.com/brave/brave-ios/assets/128532965/23987636-4719-4c6c-9fe2-ff6e47195879

*Sign in with Google*

https://github.com/brave/brave-ios/assets/128532965/15c365ff-9072-46a1-aefc-627b49283ef9
