### ISSUE TITLE
Add additional fields to submit report view

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#8270]
### Description: 
We need to add details and contact info to the submit report view. In reality the whole view was re-written from scratch to support new tools and styles.

### Test Strategy
1. Open and submit the report view the 3 different available ways
  a. through the settings menu
  b. Through the share menu
  c. Through the shields (Shields off) menu
2. Enable dark mode and see the results
3. Test on iPad as the presentation is slightly different
4. Submit the report offering something in the new fields and seeing the results here: https://stats.brave.com/dashboard#webcompat

Note: on iOS 15, there is a slight problem with the background of the description (text editor) field.

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.2
- iPad Air / iPadOS 16.7.2
Brave build: 1.60 (23.11.7.17)
BraveCore: 1.60.113 (119.0.6045.105)
```

Filed follow-up issue #8380
---------------------------
<details>
<summary> Settings menu </summary>

**STEPS:**
1. Launch Brave 
2. Open any website
3. Tree-dot menu > Scroll down and tap `Report a Broken Site` > Verify
4. Add some info to the `Additional details (optional)` and `Contact me at: (optional)` fields
5. Tap `Submit` > Verify
6. Go to https://stats.brave.com/dashboard#webcompat > Verify results

**ACTUAL RESULTS:**
- Verified that the new UI is shown for `Report a Broken Site` pop-up
- Verified that it's possible to submit a report `with` or `without` optional `Additional details` and `Contact me at:`
- Verified that results are appearing at https://stats.brave.com/dashboard#webcompat
- Verified that it's possible to cancel and close the pop-up

---------------------------

<details>
<summary> iPhone </summary>

*Dark Mode*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/4cf77721-1e8e-468f-ab96-e47f49d4d349) | ![2](https://github.com/brave/brave-ios/assets/128532965/25346e07-df9f-46d2-9d80-4700466cabc1) | ![3](https://github.com/brave/brave-ios/assets/128532965/d8d52322-aab4-41ec-9ad1-8528b4671105) | ![4](https://github.com/brave/brave-ios/assets/128532965/3e050bfa-e97b-406c-ba94-0088bb4ba6c0) |

*Light Mode*

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/578f651e-4a89-4d1d-b725-49f34cb51db8) | ![2](https://github.com/brave/brave-ios/assets/128532965/1b67d393-3617-4815-b9f0-44284c00813e) | ![3](https://github.com/brave/brave-ios/assets/128532965/08e98484-68ed-4b6a-bc4b-dc3002224cbd) |
</details>

<details>
<summary> iPad </summary>

*Dark Mode*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/0a750241-cc35-452e-8b71-40cf73c97b1a) | ![2](https://github.com/brave/brave-ios/assets/128532965/f4f4f489-c658-4467-8723-88abfc6e0155) | ![3](https://github.com/brave/brave-ios/assets/128532965/b2be3054-713e-4d60-ba4d-b5f34678c302) | ![4](https://github.com/brave/brave-ios/assets/128532965/58bb4574-4f05-4013-b18a-8630a5919645) |

*Light Mode*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/d4a08666-a2bf-46d9-aabd-08d71c2764e5) | ![2](https://github.com/brave/brave-ios/assets/128532965/03f59d33-fb79-47db-b157-a682c7383915) | ![3](https://github.com/brave/brave-ios/assets/128532965/f2f96c50-95e5-4e58-bf0f-e7d6644c50b1) | ![4](https://github.com/brave/brave-ios/assets/128532965/2875ed72-4fdc-4e6c-903b-223d354e52fa) |
</details>
</details>

<details>
<summary> Share menu </summary>

**STEPS:**
1. Launch Brave 
2. Open any website
3. Tree-dot menu > Share with... > Scroll down and tap `Report a Broken Site` > Verify
4. Add some info to the `Additional details (optional)` and `Contact me at: (optional)` fields
5. Tap `Submit` > Verify
6. Go to https://stats.brave.com/dashboard#webcompat > Verify results

**ACTUAL RESULTS:**
- Verified that the new UI is shown for `Report a Broken Site` pop-up
- Verified that it's possible to submit a report `with` or `without` optional `Additional details` and `Contact me at:`
- Verified that results are appearing at https://stats.brave.com/dashboard#webcompat
- Verified that it's possible to cancel and close the pop-up

---------------------------

<details>
<summary> iPhone </summary>

*Dark Mode*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/1483fc29-0bb0-44d6-b376-d298d31d7704) | ![2](https://github.com/brave/brave-ios/assets/128532965/192c4190-1b62-478e-8b75-f2b22742bd61) | ![3](https://github.com/brave/brave-ios/assets/128532965/38bdfcd1-e8db-4022-8a6a-517d34fa8496) | ![4](https://github.com/brave/brave-ios/assets/128532965/3835e7c8-8bc6-41ce-b2c9-482ccc81683f) |

*Light Mode*

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/3d05903d-a93b-4788-8c89-8ba7d35baa03) | ![2](https://github.com/brave/brave-ios/assets/128532965/e29ba882-4bcb-4ed5-b89b-9d5eb1cdc564) | ![3](https://github.com/brave/brave-ios/assets/128532965/677bad81-8884-4d18-9d01-f61c7c79ac18) |
</details>

<details>
<summary> iPad </summary>

*Dark Mode*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/be12f0bc-28a4-4a81-b06d-10e612456ab8) | ![2](https://github.com/brave/brave-ios/assets/128532965/ed01dd29-d34d-4212-b914-f4191514d1d8) | ![3](https://github.com/brave/brave-ios/assets/128532965/e6917b0d-6a95-4962-99a8-7e4577cb6208) | ![4](https://github.com/brave/brave-ios/assets/128532965/c4f13e40-ae4d-4ac9-9a1b-5db6fc183df5) |

*Light Mode*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/138f8222-f6f0-4854-a1c5-6e7093476e56) | ![2](https://github.com/brave/brave-ios/assets/128532965/73ce2878-f493-4022-82bb-107f88b2b5ab) | ![3](https://github.com/brave/brave-ios/assets/128532965/7fe490a8-43aa-4c69-aaac-b20720b26b3c) | ![4](https://github.com/brave/brave-ios/assets/128532965/4fac7107-7193-4e5f-a419-24e2c8b9ad95) |
</details>
</details>

<details>
<summary> Shields menu </summary>

**STEPS:**
1. Launch Brave 
2. Tap `Brave Shields` > Disable it
3. Tap `Report a Broken Site` > Verify
4. Add some info to the `Additional details (optional)` and `Contact me at: (optional)` fields
5. Tap `Submit` > Verify
6. Go to https://stats.brave.com/dashboard#webcompat > Verify results

**ACTUAL RESULTS:**
- Verified that the new UI is shown for `Report a Broken Site` pop-up
- Verified that it's possible to submit a report `with` or `without` optional `Additional details` and `Contact me at:`
- Verified that results are appearing at https://stats.brave.com/dashboard#webcompat
- Verified that it's possible to cancel and close the pop-up

---------------------------

<details>
<summary> iPhone </summary>

*Dark Mode*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/60c3a67b-008f-4fb8-8ae8-ae9a4698e1db) | ![2](https://github.com/brave/brave-ios/assets/128532965/ff82d849-0500-488c-aaca-2396870e3add) | ![3](https://github.com/brave/brave-ios/assets/128532965/63cbdd05-2ebe-429d-b660-58e98a434148) | ![4](https://github.com/brave/brave-ios/assets/128532965/da96befb-31c4-40c3-8944-fd5ae840f4b0) |

*Light Mode*

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/e1c2f336-1a09-4f46-be2c-778b5f235285) | ![2](https://github.com/brave/brave-ios/assets/128532965/823f27fd-f849-4f62-974e-b159fceabe6f) | ![3](https://github.com/brave/brave-ios/assets/128532965/0ed11574-179c-4114-bf64-6d9045586b6a) |
</details>

<details>
<summary> iPad </summary>

*Dark Mode*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/a3d3767e-862d-4f20-89c1-7108e0e3c89b) | ![2](https://github.com/brave/brave-ios/assets/128532965/6d4d494a-61e8-47e7-87d3-3420f32bb263) | ![3](https://github.com/brave/brave-ios/assets/128532965/a4c0b9b0-8f67-4151-874c-c69926590f7e) | ![4](https://github.com/brave/brave-ios/assets/128532965/d322256b-616d-4ac5-a43a-79f36239b0c8) |

*Light Mode*

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/67ee25f2-f542-4a47-8022-63679b55d3cf) | ![2](https://github.com/brave/brave-ios/assets/128532965/803277cf-9f6d-4de1-8536-0210c5f3fd61) | ![3](https://github.com/brave/brave-ios/assets/128532965/9e7cefca-e136-4967-8cb6-5c817268bd9c) | ![4](https://github.com/brave/brave-ios/assets/128532965/bf6a85d7-700c-49b8-bf0b-8fccd0161169) |
</details>
</details>
