### ISSUE TITLE
Add setting to always load YouTube links in Brave

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#8272]
### Description: 

We have a preference that alters the apps ability to load universal links in regular browsing mode. This will add a toggle in the Media settings that ensure YouTube links are always loaded within Brave even when universal links are allowed to load normally.

This preference will be enabled by default for **new users only**

Design: https://www.figma.com/file/SLFLpMd7F7Tu58qGBdcUQG/iOS-Settings?type=design&node-id=2720%3A19034&mode=design&t=fPqKj0gTBQRdgHgp-1

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.0.3` using version `1.60 (23.11.4.14)`

- Ensured `Open YouTube links in Brave` is enabled by default only for new users.
- Ensured youtube links are opened in external app when `Open YouTube links in Brave` is disabled.
- Ensured youtube links open based on setting preference on fresh and existing profiles.
- Ensured toggling any of the Media settings do not change `Open YouTube links in Brave` state

Fresh Profile | Existing Profile
-|-
![IMG_5240](https://github.com/brave/brave-ios/assets/17885425/229cbd67-6807-47aa-86dd-847eef1c629f) | ![IMG_5241](https://github.com/brave/brave-ios/assets/17885425/a1b5d9a0-7b4f-409d-ad59-bdbec3576d7a)


<table><tr><td>Disabled</td><td>Enabled</td></tr>

<tr><td>

https://github.com/brave/brave-ios/assets/17885425/1f9711ee-1393-4625-ac3a-c697b4303fdb

</td><td>

https://github.com/brave/brave-ios/assets/17885425/1eb8c32f-d010-4f14-ad19-b9e38ad5e9fe

</td></tr></table>
