### ISSUE TITLE
[Follow up to 8191] Older devices crashing after upgrading with all filter lists enabled 

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#8277]
### Description: 
Older devices crashing after upgrading with all filter lists enabled 
Related: https://github.com/brave/brave-ios/issues/8191

### Steps to Reproduce 
  1. Install 1.57.x on iPhone X/XR or iPad Gen 7
  2. Enable all filter lists under Content Filtering
  3. Upgrade to 1.58.x
  4. Observe

### Actual result: 

https://github.com/brave/brave-ios/assets/17885425/e30f682c-7540-447a-a728-fc0a42fb32f0

### Expected result:
No crash. Lists to be reduced to some amount to prevent crash when upgrading

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` & `iPhone 12 Pro` running `iOS 17.0.3` using version `1.58 (23.10.18.20)`

Using STR in https://github.com/brave/brave-ios/issues/8277#issue-1948394378

- Ensured that upgrading with all filter lists does not crash on older devices such as iPhone X.
- Ensured that total amount of selectable filter lists is limited based on device memory after upgrading.
- Ensured that filter lists are selectable on fresh install and limited based on device memory.
- Ensured that custom lists are retained when upgrading.
- Ensured that if user has custom filters in addition to filter lists selected when upgraded, the default lists are prioritized.

Example | Example | Example
-|-|-
![IMG_5199](https://github.com/brave/brave-ios/assets/17885425/b2c4c3c4-b1c8-4cbd-90b7-0e98110a6f32) | ![IMG_3602 2](https://github.com/brave/brave-ios/assets/17885425/c3504bc5-22fd-497c-95ca-a26a3f3f9d0d) | ![IMG_3603 2](https://github.com/brave/brave-ios/assets/17885425/869aae0e-e733-40fa-b2f2-f9906494bc1f)

**Comment by nihil-admirari** [comment]
> Ensured that upgrading with all filter lists does not crash on older devices such as iPhone X.

Both iPhone 13 and iPad Air 3 began to crash unstoppably after updating to the latest version from AppStore.

> Ensured that total amount of selectable filter lists is limited based on device memory after upgrading.

Still possible to crash iPhone 13 by selecting too many filters.

And just out of curiosity: previous versions were totally happy with all the filters. Why the latest version suddenly acquired a limitation?

**Comment by nihil-admirari** [comment]
Plus some message in the UI about a device not having enough memory would be beneficial: currently filters are just greyed out without any explanation.
