### ISSUE TITLE
Referral links don't launch landing page when installed

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#828]
### Description: 
Referral links don't launch landing page when installed

### Steps to Reproduce 
  1. Uninstall any version of Brave on the device
  2. Visit referral promo page for DJ/MW on safari
  3. Close App store when opened
  4. Install build from TF
  5. Launch app doesn't show the landing page for DJ/MW

**Actual result:** 
Referral links don't launch landing page when installed

**Expected result:**
Once app is installed via TF, landing page should be shown for DJ/MW

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
Both 1.7.4 and 1.7.3 on both BC and RC

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
@anthonypkeane @jhreis  marking this for 1.8 as its a pretty bad bug for install via TF
cc: @brave/legacy_qa  @danishjafri88

**Comment by srirambv** [comment]
Moving temporarily to 1.9 as this is still under review

**Comment by iccub** [comment]
Should be fixed by now right @jhreis?

**Comment by jhreis** [comment]
Yeah, although were some server issues involved I believe. Needs more QA around the board though.

**Comment by iccub** [comment]
This should be fixed, moving to 1.21 to retest it, as it is not super important right now and 1.20 has other high priority items

**Comment by srirambv** [comment]
This still seems broken. https://bravesoftware.slack.com/archives/C06UXF3KJ/p1601286432038100

**Comment by kjozwiak** [comment]
We have https://github.com/brave/brave-browser/issues/9287 filed for Android/Desktop as well. However, at least MW worked on those platforms. Honestly, it's been a pain to get anyone to fix anything relating to Barrons/MW.

Mentioned that QA will stop wasting their time checking/verifying anything related to Barrons/MW until it's actually fixed.

**Comment by iccub** [comment]
not applicable anymore
