### ISSUE TITLE
Long press  action (Context Menu) on "Favorites" shows `Edit Bookmark`

### ISSUE THREAD

**Issue by iambrianfung** [brave/brave-ios#8286]
### Description: 
When hard press on "favorites" the menu provides `Edit Bookmark`. This is the incorrect term.

### Steps to Reproduce 
  1. Open Brave Browser
  2. Hard press on one of the favorites

### Actual result: 
![IMG_4452](https://github.com/brave/brave-ios/assets/24831890/65ec0696-f71f-4473-bb24-b06b024684d9)

### Expected result:
It should probably say 'Edit Favorite'

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

### Brave Version: 
`1.57.2 (23.9.27.14)`
`1.59 (23.10.12.20)`
- Can you reproduce this issue with the most recent build from TestFlight? `Yes`
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? `Yes`

### Device details: 
iPhone 13 Mini (iOS 17.0.3)

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` & `iPad (7th Gen)` running `iOS 17.0.3` & `iPadOS 17.0` respectively using version `1.60 (23.11.7.17)`

- Ensured that Edit Bookmark is replaced with Edit Favorite in the context menu

Example | Example
-|-
![IMG_5251](https://github.com/brave/brave-ios/assets/17885425/45f00f17-9007-4d27-a6ca-6f456b82fbf2) | ![IMG_5252](https://github.com/brave/brave-ios/assets/17885425/f4a49b99-d6ba-4663-966a-2cd06f088872)
![IMG_1244](https://github.com/brave/brave-ios/assets/17885425/71d1e1b8-1fdb-4936-99d9-0cd712b44519) | ![IMG_1245](https://github.com/brave/brave-ios/assets/17885425/5d916626-8030-4fe6-9186-c1e7ed2b4e56)
