### ISSUE TITLE
Report an issue switches to normal tab even with PB only enabled

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#829]
### Description: 
Report an issue switches to normal tab even with PB only enabled. Issue originally reported on community https://community.brave.com/t/report-a-bug-forces-user-out-of-private-browsing/43681

### Steps to Reproduce 
  1. Enable PB mode only from settings
  2. Open settings and go to Report an issue
  3. Normal tab is opened, Can't open tab container have to exit PB mode to actually see the normal tab where the community page is opened

**Actual result:** 
Report an issue always switches to normal tab even with PB only enabled

**Expected result:**
If report an issue is triggered via PB, then it should be opened in a PT only

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
All

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Moving to 1.9 as not a regression. Confirmed by @jhreis

**Comment by LaurenWags** [comment]
* Verified passed with 1.9 (19.3.9.1) on iPad 5th Gen using STR above
* Verified passed with 1.9 (19.3.9.1) on iPhone 8 using STR above
* Verified passed with 1.9 (19.3.9.1) on iPhone SE
* Verification passed on iPad Pro/iPhone 6/7+ running 1.9(19.3.9.1)
  - Verified on PB mode only 
  - Verified by launching a private tab and opening report an issue loads in private tab only
* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR.
  - Verified on PB mode only 
  - Verified by launching a private tab and opening report an issue loads in private tab only
