### ISSUE TITLE
Increase the number of engines on older devices

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#8292]
### Description: 
The number of max engines is set to a value that is just too little. On an iPhone 6s it's 5 and on an iPhone X it's 15.

### Steps to Reproduce 
  1. Install the application on various devices
  2. Go to the filter list settings and enable as many engines as possible

### Actual result: 
4 on iPhone 6s, 14 on iPhone X

### Expected result:
The number is arbitrary and depends on the memory of the device but a floor of 19 and ceiling of 39 should be imposed on all devices. (note the total is N filter lists + 1 as the default filter list takes 1 spot)

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.60 (23.11.22.17)`

- Ensured that selecting 19 filters is the floor on iPhone X with fresh and existing profiles.

Example | Example
-|-
![IMG_3644 2](https://github.com/brave/brave-ios/assets/17885425/a9fee8b7-af63-450d-be8e-558dcee374e5) | ![IMG_3645 2](https://github.com/brave/brave-ios/assets/17885425/40072f9c-0a2d-416c-98a2-410be56cc9da)
