### ISSUE TITLE
Impose the max engines limitation on content blockers

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#8294]
### Description: 
We do not restrict the number of content blockers we compile. Currently we compile all of them (about 50). We want to change this so the max limitation we impose on engines also applies to content blockers.

### Test steps
Note: Testing should be done on the worst possible device: iPhone 6s, 7, 8, X, XR, XS) as these are the devices that reproduce the crashes the easiest)

1. Enable all possible filter lists (max should be 20 on really old devices)
2. Test network blocking. This is not as straightforward as cosmetic filtering and scriplets as there is often no visual queue something is blocked. You can test a custom rule [here](https://gist.githubusercontent.com/cuba/f13fce20b8fbd043ac8174e39ba16788/raw/9fdecbdef9aa93b1d1c0a4126c5dc495bb9c08d4/TestAdBlockRules.txt)
 - Network blocking: You will see the brave logo blocked on https://brave.com
 - Cosmetic filtering: You will see the header blocked on https://example.com
3. Go to google.com, open inspector, go to console and look for network blocking such as 
```
Content blocker prevented frame displaying https://www.google.com/ from loading a resource from https://adservice.google.ca/adsid/google/ui?gadsid=AORoGNROksXZG6mHPzCKEhxR9nwLpJsQpIXHBco6r5CKwDeNPQ2jLMs9qg
```
4. Test all pass [here](https://test-pages.privacytests.org/tracking_content.html)
5. Test scriplets [here](https://dev-pages.brave.software/filtering/scriptlets.html)
6. Test cosmetic filtering [here](https://dev-pages.brave.software/filtering/cosmetic-filtering.html)
7. Test the above after killing the app and re-launching
8. Test that the speed of applying filter list changes is near instant. (this is no longer instant as before but should still be fast enough that the user doesn't notice. Lets go with something reasonable here, if there is a 1 second delay that's fine, if its 5 seconds then maybe something worth creating an issue for)

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.58.1 (23.10.30.19)`

_**Fresh Profile**_

- Ensured the following using the test plan mentioned in https://github.com/brave/brave-ios/issues/8294#issue-1953001753 for fresh install case.
- Ensured that enabling all filter lists possble (17) will not cause any performance issues or crashes. 
- Ensured that creating a custom filter using url [custom url list](https://gist.githubusercontent.com/cuba/f13fce20b8fbd043ac8174e39ba16788/raw/9fdecbdef9aa93b1d1c0a4126c5dc495bb9c08d4/TestAdBlockRules.txt) blocks the Brave svg logo at the top of `https://brave.com` and the header in `https://example.com`
- Ensured there are 19 items shown in https://test-pages.privacytests.org/tracking_content.html and `passed` is `true` when Shields are up. Disabling Shields will show 'false' for all except the facebook tracker (only in aggressive mode).
- Ensured that scriptlets are being applied correctly using test page https://dev-pages.brave.software/filtering/scriptlets.html
- Ensured CF tests are passing with regular and aggressive ad block setting.
- Ensured filter lists changes are applied quickly (tested paywall bypass switch on nytimes.com articles)

brave.com | example.com | filter lists | CF test | Scriptlets test | tracking content test
-|-|-|-|-|-
![IMG_3607 2](https://github.com/brave/brave-ios/assets/17885425/bc1613e4-860f-488b-a474-0fa048e54aa3) | ![IMG_3608 2](https://github.com/brave/brave-ios/assets/17885425/8599a5a2-31bb-4715-95f9-7e0d909c7a79) | ![IMG_3604 2](https://github.com/brave/brave-ios/assets/17885425/14ea4570-3f90-4972-a3c5-81cad8a06c3e) | ![IMG_3615 2](https://github.com/brave/brave-ios/assets/17885425/182a1432-1832-4eaf-974e-4c6d3363ac3b) | ![IMG_3613 2](https://github.com/brave/brave-ios/assets/17885425/b0445daa-cb13-414f-a5f3-e011372e2b2e) | ![IMG_3610 2](https://github.com/brave/brave-ios/assets/17885425/90133f72-2ef8-40eb-adf7-1750c9d64f32)

_**Existing Profile Case: 1.58.x -> 1.58.1**_

- Ensured all steps (aside from the inspector) have successfully passed on existing profile after upgrading

**_Existing Profile Case: 1.57.2 -> 1.58.1_**

- Ensured all steps (aside from the inspector) have successfully passed on existing profile after upgrading

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.0.3` using version `1.58.1 (23.10.30.19)`

- Ensured all steps were successful when test plan in https://github.com/brave/brave-ios/issues/8294#issue-1953001753 on fresh & existing profiles.
- Ensured enabling filters on existing profile does not cause performance issues or app to crash.
- Ensured test are passed in regular and aggressive ad-blocking mode.

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_5213](https://github.com/brave/brave-ios/assets/17885425/1b7400e8-a71f-4e76-a369-6381359cbfdd) | ![IMG_5214](https://github.com/brave/brave-ios/assets/17885425/17cb81f1-1458-4249-9f45-4eeddee5a748) | ![IMG_5215](https://github.com/brave/brave-ios/assets/17885425/f2f54c67-de5c-4e17-aa52-eb0501967952) | ![IMG_5216](https://github.com/brave/brave-ios/assets/17885425/6883f334-969a-462e-af3d-4cf048f79e4f) | ![IMG_5217](https://github.com/brave/brave-ios/assets/17885425/82347afc-333c-4d7b-8a23-6e1b401ad57f) | ![IMG_5218](https://github.com/brave/brave-ios/assets/17885425/ef344727-cd19-4973-bf44-1b0b72b7dd1b)
