### ISSUE TITLE
Can’t open link a new tab

### ISSUE THREAD

**Issue by ghost** [brave/brave-ios#830]
### Description: 

Open a new link in a new tab in Brave, on iOS 12.2b, it is not possible by long pressing on the link—since the Open in a new tab is not available. 

I have to open a new tab and copy&paste the link manually.

### Steps to Reproduce 
  1. Go on a page with a link
  2. Long press on the click
  3. Look for the ‘Open in a new tab’ option

**Actual result:** 

Available options:

- Open
- Add to 'Reading list'
- Copy
- Share

![](https://i.imgur.com/0ABxWiL.png)

**Expected result:**

Long pressing on the link provides the option to open the link in a new tab.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

Everytime I use Brave, since a couple of days ago.

**Brave Version:** 

V1.7.3 (19.01.25.15)

**Device details:** 

iPhone 7 (iOS 12.2 Beta)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 

Safari works correctly. So does Chrome.

**Comment by iccub** [comment]
Thanks for the report.
I saw this bug too, but it does not happen too often for me and it is per-tab based. So closing the tab and opening a new one fixes the bug.

**Comment by ghost** [comment]
Nice to hear that. I just tried it and doesn’t work for me.

**Comment by iccub** [comment]
Hey, I just wanted to let you know that this issue is most likely fixed.
It is an Apple's Webkit bug, but we've done some workaround and all should be good.

It won't probably land in the next release however, but in next + 1, so please have some patience and sorry for the problems

Posting here two links for future reference(the Webkit bug related)

https://bugs.webkit.org/show_bug.cgi?id=193366
https://bugzilla.mozilla.org/show_bug.cgi?id=1520629

**Comment by ghost** [comment]
Okay, thank you for letting me know!

**Comment by cndouglas** [comment]
+1 from @joha1 in #994.

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/unable-to-open-in-new-tab/50369?u=eljuno

**Comment by willstocks** [comment]
Thanks @eljuno! ☺️ Extending the original details in the community link, I can confirm I'm seeing this on any tab I open at the mo 😔

**Comment by VimS** [comment]
I got the same Issue on IOS 12.2 with Brave 1.8

**Comment by iccub** [comment]
Sorry for that, we will most likely release a hotfix for this, shortly after 1.9 lands

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+ / iPhone 6 and iPad Pro running 1.9(19.3.26.19) on iOS 12.2
* Verification passed on iPhone SE running 1.9 (19.3.29.16) on iOS 12.1
* Verified passed on iPad 5th Gen with 12.1. Updated iPad to 12.2 and verified passed on 12.2 as well
* Verification **PASSED** on `iPad Mini` running `iOS 12.1` & `iPhone 6s+` running `iOS 12.2`
  * long press on links and ensured that `Open in New Tab`, `Open in New Private Tab`, `Copy Link` and `Share Linked` worked
  * long press on images and ensured that `Open Image In New Tab`, `Open in New Private Tab`, `Save Image` and `Copy Image` worked
  * long press on text and ensured that `Copy`, `Look up`, `Share..` and `Fine on Page` worked
  * long press on the URL and ensured that `Paste & Go`, `Paste` and `Copy Address` worked
* Verification passed on iPhone SE running 1.9 (19.3.29.16) on iOS 12.2

**Comment by nqnx** [comment]
> Verification passed on iPhone 7+ / iPhone 6 and iPad Pro running 1.9(19.3.26.19) on iOS 12.2

Is that a typo and meant to be 19.3.29.19? Because on iPhone 8, iOS 12.2 and Brave 1.9 (19.3.29.14) it does not work yet.

**Comment by iccub** [comment]
@nqnx just before 1.9 release we found few crashes related to `open in new tab` and we had to quickly revert it back and release without this fix.
We plan to release a hotfix for new tab only early this week

**Comment by joha1** [comment]
>  we found few crashes related to open in new tab and we had to quickly revert it back and release without this fix.

So that's why I now can't open anythin in a new tab? I can get the popup menu on long press, even when scripts are off, but I now only have the option to open the link (in the same tab... kinda useless), even when I have the scripting shield switched off (=scripts on).

**Comment by iccub** [comment]
@joha1 yes, we managed to fix it but we found the app was crashing for unknown reasons and we decided to postpone shipping the fix.
As I said before, we will try to push a hotfix release this week

**Comment by srirambv** [comment]
- Reverified on iPhone 7/6 and iPad Pro running 1.9.1 (19.04.02.12). Context menu option available for long press on a link. 

Reverified on iPad 5th Gen running 1.9.1 (19.04.02.12). Context menu option available for long press on a link. 

Reverified on iPhone 8 running 1.9.1 (19.04.02.12). Context menu option available for long press on a link.

**Comment by iccub** [comment]
Brave 1.9.1 is out, please update the app to get this fixed for you

**Comment by nqnx** [comment]
Thank you very much!

**Comment by VimS** [comment]
> Brave 1.9.1 is out, please update the app to get this fixed for you

Fixed the Issue for me.

**Comment by joha1** [comment]
Still doesn't work for me.
But the behaviour changed. Now a long press just doesn't do anything, whereas before, it simply opened the link after letting go of it.
With javascrip on, background tabs work as expected.
What else could be wrong on my side?

**Comment by iccub** [comment]
What's your device model, device version and Brave version @joha1?

**Comment by joha1** [comment]
@iccub I'm on an iphone SE on iOS 12.2 (16E227). Brave, according to the "about" in settings is on 1.9.1 (19.04.02.12)

So as far as I can see, everything seems current.

**Comment by btlechowski** [comment]
Re-verified on iphone SE on iOS 12.2, Brave 1.9.1 (19.04.02.12)

**Comment by iccub** [comment]
@joha1 @btlechowski 
The issue is that `Open in new tab` does not work with javascript disabled(via settings page).
After disabling JS i can reproduce it on my iPhone 7 12.1

That's an interesting edge case, I made separate ticket for it here https://github.com/brave/brave-ios/issues/1055
