### ISSUE TITLE
Allow Syncing All History

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#8305]
With Chromium enables History datatype and with CR119 the old TypedUrls datatype, which was used for History Sync, is wiped out from Chromium codebase.

The Desktop and Android change is covering most of the implementation for History API on iOS side with
https://github.com/brave/brave-core/pull/20329

Over that PR iOS side will have the changes with PR https://github.com/brave/brave-core/pull/20642

This PR will be merged together with CR119 uplift and "Allow Syncing All History" should be enabled with 1.60.

The reflection of this change on iOS repo is we have to remove typed url detection while adding item to History so All Item can be synced automatically. And since this separation is not needed anymore it has to be removed and cleaned from repository.

This will only effect History Items so The adding removing History with or without sync will be enough for testing.

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.60 (23.11.12.17`

Test Plan: https://github.com/brave/brave-core/pull/20329#issue-1917760373

**Browse / manually removing entries**

- Ensured that history is synced on Devices A, B and C. 
- Ensured history items are removed on all synced devices after deleting on one device. 
- Ensured that new devices that join sync chain do not show the deleted history. 

Example | Example
-|-
![IMG_3636 2](https://github.com/brave/brave-ios/assets/17885425/95992c2d-0424-410e-8e17-a327bb83812c) | ![IMG_3637 2](https://github.com/brave/brave-ios/assets/17885425/68028ccf-1e45-4038-845d-65efc4d48a3e) 

![Screenshot 2023-11-14 at 10 56 28 AM](https://github.com/brave/brave-ios/assets/17885425/6786c056-574e-4d6e-877f-1a199074befc)

**Time Based History Cleanup**

- Ensured browsing history is cleared on all synced devices when clearing history for the last hour. 

Before | After
-|-
![IMG_3640 2](https://github.com/brave/brave-ios/assets/17885425/a6ac40a6-bb48-4dea-b1d2-16a5ebc726c5) | ![IMG_3641 2](https://github.com/brave/brave-ios/assets/17885425/6424df22-9d91-4afa-81ba-8d307819e7ef)


**Android**

- Ensured history is synced on Android device. 
- Ensured deleting history item from Android device is synced across chain. 

Example | Example
-|-
![Screenshot 2023-11-15 at 4 58 41 PM](https://github.com/brave/brave-ios/assets/17885425/cc1ff7b7-539a-453f-b276-b242d398aef8) | <img width="600" alt="0" src="https://github.com/brave/brave-ios/assets/17885425/724ede44-6724-4d98-ac29-c62a8d449d89">
