### ISSUE TITLE
Refactor Certificate-Viewer UI

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8308]
## Problem Description 
- Certificate Viewer UI currently shows invalid icon when displaying the warning in the URL-Bar even when the certificate is valid. It shows because the page is using Mixed-Content so `hasSecureContentOnly` is false.

## Implementation Details 
- We should refactor certificate viewer so that it separates the two things like Desktop has in 1.59.x

## User Experience 

1. Warning icon will NOT show for pages using Mixed-Content.
2. URL-Bar will show 3-dot icon or other icon, and when tapping that, a menu will display where the user can see if the certificate is invalid or the page has invalid content or both.

**Comment by diracdeltas** [comment]
> Warning icon will NOT show for pages using Mixed-Content.


@Brandon-T actually if a page uses mixed content, it should show up the same as HTTP (insecure). discussed with @kylehickinson in https://github.com/brave/reviews/issues/1443#issuecomment-1792962411.

**Comment by Brandon-T** [comment]
> > Warning icon will NOT show for pages using Mixed-Content.
> 
> @Brandon-T actually if a page uses mixed content, it should show up the same as HTTP (insecure). discussed with @kylehickinson in [brave/reviews#1443 (comment)](https://github.com/brave/reviews/issues/1443#issuecomment-1792962411).

Hmm are we certain that we want to keep this behaviour? 
That is the existing behaviour atm and it seemed like everyone was against it in this thread: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1686523204739419?thread_ts=1684812382.308159&cid=C06UXF3KJ

I'm okay with with either decision. If we keep the behaviour, then this PR can be closed.

**Comment by diracdeltas** [comment]
@Brandon-T the key question is, does iOS display mixed content images? from talking to @kylehickinson, it seemed like iOS would block mixed scripts but allow mixed images to show up. if that's the case, it should show up as insecure. (desktop is different because it blocks/upgrades both mixed scripts and images)

from the thread it wasn't clear to me whether the sec/privacy folks knew if it was actually allowing mixed content.

very.badssl.com is a site that tries to load both mixed scripts and images.

**Comment by diracdeltas** [comment]
here's the comment where it seemed like iOS is allowing mixed content images: https://github.com/brave/reviews/issues/1443#issuecomment-1792920966

**Comment by diracdeltas** [comment]
another option - i'd be ok with showing the HTTP warning icon in grey instead of red if the site is valid HTTPS but loads mixed content. https://bravesoftware.slack.com/archives/C06UXF3KJ/p1699486715080099?thread_ts=1684812382.308159&cid=C06UXF3KJ

**Comment by Brandon-T** [comment]
> @Brandon-T the key question is, does iOS display mixed content images? from talking to @kylehickinson, it seemed like iOS would block mixed scripts but allow mixed images to show up. if that's the case, it should show up as insecure. (desktop is different because it blocks/upgrades both mixed scripts and images)
> 
> from the thread it wasn't clear to me whether the sec/privacy folks knew if it was actually allowing mixed content.
> 
> very.badssl.com is a site that tries to load both mixed scripts and images.

Yes, iOS always displays/displayed the mixed-content images, but not run insecure scripts.

**Comment by diracdeltas** [comment]
in that case, let's show mixed content for now as either the insecure icon (red warning sign) or a grey warning sign in the URL bar. 

once we implement auto-upgrade/blocking of mixed content, it can be changed to the fully secure state.

**Comment by Brandon-T** [comment]
This is fixed in the latest iOS as per the URL bar re-design.
