### ISSUE TITLE
Small text update on onboarding

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#8316]
### Description: 
Pls make the text Title Case, i.e.

Set Brave as Default Browser?
Set Default
Not Now

<img width="421" alt="Screenshot 2023-10-25 at 2 57 03 PM" src="https://github.com/brave/brave-ios/assets/7606853/f6f48438-bd53-48f5-be20-a1fb818009d5">

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` & `iPad (7th Gen)` running `iOS 17.0.3` & `iPadOS 17.0` respectively using version `1.60 (23.11.7.17)`

-Ensured strings mentioned in https://github.com/brave/brave-ios/issues/8316#issue-1962304510 are in title case

Example | Example
-|-
![IMG_5250](https://github.com/brave/brave-ios/assets/17885425/eded87eb-3709-4045-a621-103dd806c80a) | ![IMG_1243](https://github.com/brave/brave-ios/assets/17885425/77312e75-aee4-4795-a6dc-9a1ef245b443)
