### ISSUE TITLE
Menu Update for VPN Status 

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#8317]
### Description: 
Can we make the menu update with the VPN status without having to go back?

https://github.com/brave/brave-ios/assets/7606853/307d92ed-2564-4822-9a72-70afe76b4625

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.0.3` using version `1.60 (23.11.7.17)`

- Ensured that menu updates based on VPN status

https://github.com/brave/brave-ios/assets/17885425/7059824e-b343-45c8-9804-a7f381f589e0
