### ISSUE TITLE
Pressing the back button (once or twice) loads a stale version of the cached page

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#832]
Reported by a user

“Bug report for brave mobile: almost every time I press the back button once or twice, I see a stale version of the cached page and have to hit refresh to get the current one...”

@srirambv I can't reproduce this one, could you help?

**Comment by srirambv** [comment]
@anthonypkeane  Would require more detailed steps to try

**Comment by kylehickinson** [comment]
This is most likely just the way iOS web view works and we likely cannot do anything about it
