### ISSUE TITLE
Wallet Unlock v2

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8328]
### Description: 

Update unlock wallet UI to v2 designs

https://www.figma.com/file/muVcmcu4RFNu0LkXe9VRDl/Wallet-2.0?type=design&node-id=3450-270248&mode=design&t=DREDr7B7bgPks8Bj-4

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.61 (23.11.30.17)
- Verified steps from [#8340](https://github.com/brave/brave-ios/pull/8340)
- Verified Unlock v2 screens are as per figma design
- Verified biometric unlock works as expected


| iPhone 13 (iOS 17.2) | iPad (iOS 16.7.2) | iPhone7+ (iOS 15.8) |
|--------|--------|--------|
<img width=200 src=https://github.com/brave/brave-ios/assets/17010094/fd94e01a-146b-4211-b867-26d087ae79df> | <img  src=https://github.com/brave/brave-ios/assets/17010094/454b30f7-5ec0-4645-bfb3-e4fc92f784df> | <img width=300 src=https://github.com/brave/brave-ios/assets/17010094/2171c3d2-af60-4599-9007-01648c1b0655>
| ![image](https://github.com/brave/brave-ios/assets/17010094/38cda409-912c-43b0-9977-7e929883e25c)| ![image](https://github.com/brave/brave-ios/assets/17010094/7b50c57e-e976-440b-a953-d3d0fe76d711)| ![image](https://github.com/brave/brave-ios/assets/17010094/3e3d3743-0f5a-47a8-8a54-297f2b7aae24)|
| ![image](https://github.com/brave/brave-ios/assets/17010094/307fa9ae-a23c-4156-b8f7-0061827e87d7)| ![image](https://github.com/brave/brave-ios/assets/17010094/ed9912df-0958-4d77-8cda-c4c5fecef5dc) | ![image](https://github.com/brave/brave-ios/assets/17010094/ce6e4bf6-a38c-490a-961c-98e8c0e33d49)|
