### ISSUE TITLE
Send to your Devices action "Send" button placement

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#8329]
## Problem Description 

The behaviour around Send Web Page functionality should be changed related with how Send button is presented in UX.
This is creating some problem in certain devices where aspect ratio doesnt allow full list to be presented with send button at the bottom of the list.

## Enhancement Overview 

So the solution here is to remove the send button from bottom of the device list. This will also make sending mor elogical cause the user can add devices up to 10 which will eventually make this button very hard to reach and find for users.

## Design 

![Simulator Screenshot - iPhone 14 Pro - 2023-10-26 at 09 39111](https://github.com/brave/brave-ios/assets/6643505/b4828eee-5af3-4a2f-bf2c-a45039f74b8d)

Send button should be where title and cancel appears.

## Implementation Details 

So the Send To Your Device button here should removed and send action should be added in navigation bar as right bar button item.

## User Experience 

1. Open Settings
2. Press Send to Your Devices
3. Press Send

### Additional information 

To use this feature device should be ina sync chain with other devices

**Comment by Uni-verse** [comment]
Verified on `iPhone 12 Pro` running `iOS 17.0.3` using version `1.60 (23.11.4.14)`

- Ensured that `Send` action button is placed into the header section
- Ensured that `Send` action button is shown when multiple devices are connected
- Ensured sharing works with mobile and desktop clients using `Send to your Devices`

Device selection | Sending | Sent
-|-|-
![IMG_5233](https://github.com/brave/brave-ios/assets/17885425/a18e2bd6-746c-453e-88e9-c13e9f4ea4e0) | ![IMG_5234](https://github.com/brave/brave-ios/assets/17885425/4fdec097-625d-4192-b571-6c56ec393a36) | ![IMG_5235](https://github.com/brave/brave-ios/assets/17885425/c2afcb1a-8782-49de-b261-8ddcaee4b20e)
![IMG_5236](https://github.com/brave/brave-ios/assets/17885425/26bd27e1-374f-4b76-9be1-dd8337dd087f) | ![IMG_5237](https://github.com/brave/brave-ios/assets/17885425/e5102708-d3b2-4984-b583-c73c66053845) | ![IMG_5238](https://github.com/brave/brave-ios/assets/17885425/1d0d64b6-5406-4340-8fa3-54fa7f4178f4)

![Screenshot 2023-11-07 at 10 29 06 AM](https://github.com/brave/brave-ios/assets/17885425/c9741428-56e6-45d1-b32a-404a3cf91d43)
