### ISSUE TITLE
Stupide question ... How to enable sync ?

### ISSUE THREAD

**Issue by thib5** [brave/brave-ios#833]
Hi , I look every where on the iOS menu and can find how to enable the sync...

Thanks

**Comment by iccub** [comment]
Hi, Sync for iOS is not available yet, it is in final stages of development and should be ready later this month.
More info here https://support.brave.com/hc/en-us/articles/360021218111-How-do-I-set-up-Sync-

However, If you want to enable preview of Sync for a local development build, you can do so by disabling `NO_SYNC` flag in the project build settings.

Closing this ticket for now but feel free to add a comment if you have any more questions

**Comment by Razva** [comment]
> Hi, Sync for iOS is not available yet, it is in final stages of development and should be ready later this month.

Don't want to be rude but can we *really* expect this at least on the end of *this* (03.2019) month?

**Comment by jhreis** [comment]
It is currently undergoing QA. We hope that it will be live by the end of March. We should have more details in the next week or so.
