### ISSUE TITLE
Cannot close cookie consent popups

### ISSUE THREAD

**Issue by maarsson** [brave/brave-ios#8331]
### Description: 
Certain types of cookie consent popups are not closeable (not clickable?). None of the buttons works, the popup just remains.

### Steps to Reproduce 
  1. Go to https://www.boredpanda.com/ 
  2. Try to click on "Agree". Nothing happens.
  3. Try to click on "More options". Nothing happens.
  4. It is always with this type of consent popup, on several other websites.

### Expected result:
Depending on settings, the whole popup should be blocked, or the popup functionality should remain if the popup shows.

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced (with the current build from AppStore)

### Brave Version: 
1.58 (23.10.18.20)

### Device details: 
iPhone 12
iOS 17.0.3

### Website problems only:
The issue occurs with default setting, Shields on
The issue can be fixed by disabling JS (but then the most pages will not work)
The issus can be fixed by disabling all cookies in the settings (but then many other pages will not work)
The issue does not occur in Safari

**Comment by ryanbr** [comment]
Is consent blocking enabled? A fix to block the consent message showing went out [10 days ago ](https://github.com/easylist/easylist/commit/79e79dee762c85adf781605de0fe049a6ab14310)

I checked the latest stable/release Brave build, not seeing any consent nags here

**Comment by maarsson** [comment]
I deleted the app and all its settings from the phone, the reinstalled, and turned on consent blocking.
Now everything works properly.
