### ISSUE TITLE
Cursor glitches

### ISSUE THREAD

**Issue by cooperbang** [brave/brave-ios#8332]
### Description: 
Setting the cursor in the address bar doesn´t work well.

### Steps to Reproduce 
1. Open a website by typing an URL (e.g. https://www.apple.com/shop/buy-iphone/carrier-offers) end pressing "Open" button afterwards.
2. Tap on the URL in address bar with your finger to edit the URL and try to set the cursor inside a word.

### Actual result:
It´s impossible to set the cursor in the middle of the words “apple”, “com”, „shop“, etc. (e.g. after the „a“ letter in the word „apple“. The cursor only can be set before or after the single words.

### Expected result:
It should be possible to set the cursor at any position of the URL.
Tapping and holding on a word for about half a second brings up a magnifying glass in iOS and  it should be possible to set the cursor at any position within any word.

### Reproduces how often: 
Easily reproduced

### Brave Version:
1.58 (23.10.18.20)

### Device details:
iPhone 11 (iOS 17.1)

**Comment by kylehickinson** [comment]
Thanks for the report @cooperbang, seems like there's a conflict with the drag/drop gesture that we'll need to sort out. In the meantime you should be able to shift the cursor by holding down the space bar on the keyboard. Here's an example: https://twitter.com/AppleSupport/status/1506669866698297346

Hope that helps for now!

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.2
Brave build: 1.60 (23.11.4.14)
BraveCore: 1.60.105 (119.0.6045.59)
```
Filed follow-up issue #8374
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-ios/pull/8347#issue-1971366264
2. Followed the steps from https://github.com/brave/brave-ios/issues/8332#issue-1967740259

**ACTUAL RESULTS:**
- Verified that nothing is happening when long pressing and dragging the URL bar on the `NTP`
- Verified that the URL bar can be lifted and dropped in the text field when long pressing and dragging a website URL
- Verified that the cursor is movable and can be set in any place when long pressing and moving a cursor if no words are selected in the URL bar
- Verified that any part of the URL address can be selected by moving front and back cursors if any part of the address is selected
- Verified that any part of the URL address can be selected by moving the cursor while holding the `Space bar` on the keyboard
- Verified that cursor must be set only before or after the word/number/symbol with a `short tap`. The same was observed in `Safari`

---------------------------

*Long press and drag the URL bar on the NTP → nothing should happen*

https://github.com/brave/brave-ios/assets/128532965/e397bb44-965e-4a35-b3e7-89f576737c03

*Visit a website, long press and drag on the URL bar and drag → The URL bar should lift and be droppable*

https://github.com/brave/brave-ios/assets/128532965/7a9bac57-57b3-4c4b-bd2d-b1c0e1961d3c

*Visit a website, tap on the URL bar, and attempt to move the cursor via long-press → The cursor should be movable and shouldn't lift the entire URL bar. Note: It is possible to start a drag session if you've selected a number of characters and long-press on the selected range which will show the text you've selected and not the URL bar (this is unrelated)*

https://github.com/brave/brave-ios/assets/128532965/5b0d0cb2-1731-4423-936c-9323ef1b1138

*Visit a website, tap on the URL bar, and while the address is selected, attempt to move the front and back cursors → Any part of the URL address must be selected*

https://github.com/brave/brave-ios/assets/128532965/a16f2607-c1bc-432d-bb3d-011cbe3b4c16

*Visit a website, tap on the URL bar, and attempt to move the cursor by holding the `Space bar` on the keyboard → Any part of the URL address must be selected*

https://github.com/brave/brave-ios/assets/128532965/32666562-90e4-406d-b334-7d9b54002f5c

*Visit a website, tap on the URL bar, tap again to unselect the text, and attempt to `short tap` in the middle of any word to set the cursor there → Cursor must be set only before or after the word/number/symbol. The same was observed in `Safari`*

https://github.com/brave/brave-ios/assets/128532965/25b08186-1bb2-4d70-a2a7-f8180b03979a
