### ISSUE TITLE
Add  Open Browser History and Open Tabs from Other Devices Activity Based Shortcuts

### ISSUE THREAD

**Issue by errende** [brave/brave-ios#8333]
## Feature Overview 

Add requested actions to shortcuts for opening screens of "Browser History" and "Tabs Open in Other Devices" .

## Design 

The actions should be added in Brave Settings for quick interaction.

![testt](https://github.com/brave/brave-ios/assets/6643505/b5bc0464-a678-4454-89d3-bc53a8b815c6)

## Implementation Details 

User Activity Shortcut list is as follows:

Open New Tab
Open New Private Tab
Clear Browser History
Enable VPN
Open Brave Today
Open Playlist

Add Open Browser History and Open Tabs from Other Devices Activity Based Shortcuts implementation.

## User Experience 

Same with other Activity Shortcuts, Add them through the settings and invoke the action from shortcuts app or Siri itself.

### Additional information 

For base implementation please read https://github.com/brave/brave-ios/pull/3579

**Comment by soner-yuksel** [comment]
Hi @errende I believe you are talking about Shortcut support for custom actions right? 
Did you check our Shortcut support in Brave Settings? I believe the "Clear History" implementation should be there.

**Comment by errende** [comment]
@soner-yuksel 

> Hi @errende I believe you are talking about Shortcut support for custom actions right? Did you check our Shortcut support in Brave Settings? I believe the "Clear History" implementation should be there.

Yes but all the shortcuts available for Brave are completely useless compared to everything iOS Chrome and Safari can do. 
I'm not looking for clearing my browsing history i want to be able to open the "device page" or "history page" to access my opened synced tabs currently on PC faster

**Comment by soner-yuksel** [comment]
So what is useless and useful is clearly debatable here.

However If you can clearly state which actions you would like to see, we can add the implementation for it.

For instance what is device page btw? I can add Open History Screen and Open Synced Tabs Screen actions if this is what you have in mind

**Comment by errende** [comment]
> So what is useless and useful is clearly debatable here.


The fact that iOS Chrome and Safari have several dozens of shortcuts features that Brave does not have is not really debatable. 

The only one currently available in Apple shortcuts for Brave is "Open Website" and the ones that can get added from inside the Brave app itself are all extremely niche feature such as "activate VPN" or "open Open Brave News"

> For instance what is device page btw? I can add Open History Screen and Open Synced Tabs Screen actions if this is what you have in mind

Adding both of these options would be awesome. 
I was unsure of how it is properly labeled. The goal would indeed be to view the page showing tabs currently opened in the sync paired devices. Chrome calls this shortcuts "Recent tabs".

Thank you for putting up with my bad explaining, i sure can stutter with the specifics sometimes

**Comment by soner-yuksel** [comment]
What I wanted to say nothing done here is coincidental. You might not find the actions implemented useful but it is designed according what our users interact with the most and created quick actions for those. The reason we have feature request option is hear about our users needs. 

Thats said, I will create an issue for this enhancement for both of the actions you want. And you can keep track the stage(status) of the implementation. I will link it here. Maybe not next version but I will try to add it to the one after that which will be 1.60.

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.2
Brave build: 1.61 (23.12.14.18)
BraveCore: 1.61.102 (120.0.6099.71)
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-ios/pull/8387#issue-1986241715

**ACTUAL RESULTS:**
- Verified that `Open Bookmarks`, `Open Browser History` and `Open Tabs from Other Devices` shortcuts added to the `Settings`
- Verified that shortcuts from above can be used with `Shortcats`/`Siri` 

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/73a5a923-95eb-4c8c-8ac2-207e9213226c) | ![2](https://github.com/brave/brave-ios/assets/128532965/d6c58c05-eaa6-4e77-a40d-204130997129) | ![3](https://github.com/brave/brave-ios/assets/128532965/25321981-677a-4bf4-a800-c0f4bc463fdd) |

https://github.com/brave/brave-ios/assets/128532965/7834f8a2-438f-4baf-b6c5-1cca378532d8
