### ISSUE TITLE
User Agent String is Stale

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ios#834]
### Description: 
Brave uses the Firefox user-agent string to _fly under the radar_. Unfortunately, the Brave User Agent String gives inquiring websites the idea that the user is on an extremely out of date version of Firefox.

_Firefox_
Mozilla/5.0 (iPHone; CPU iPhone OS 12_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/**14.0b12646** Mobile/16C101 Safari/605.1.15

_Brave_
Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/**1.7.3b19.01.25.15** Mobile/16C101 Safari/605.1.15

1.7.3 is Brave's version number, which is much smaller than the 14.0 version number for Firefox.

Issue spotted by [Zooko on Twitter](https://twitter.com/zooko/status/1091879910384300032):

![image](https://user-images.githubusercontent.com/815158/52173710-133a5380-274f-11e9-9970-f83fb18bedb7.png)

**Actual result:**
User Agent String contains substantially different version numbers than Firefox.

**Expected result:**
User Agent String should be up-to-date.

### Related
#751

**Comment by srirambv** [comment]
Verification passed on iPhone 7
* Verified visiting forbescrypto on 1.7 shows user agent string error
* Verified upgrading to 1.8 doesn't show the error and loads the site correctly

**Comment by kjozwiak** [comment]
Went through the following using an `iPad Mini 4` which is running `iOS 12.1.4`:

* Reproduced original issue using `1.7.4 (19.01.30.19)`
* Verified that the issue has been resolved using `1.8 (19.02.20.21)`

**Comment by kjozwiak** [comment]
Verified the same cases I used above using `iPhone 6s+` running `iOS 12.1.4`.
