### ISSUE TITLE
Menu always displayed in some websites.

### ISSUE THREAD

**Issue by Romaindcrl** [brave/brave-ios#8341]
### Steps to Reproduce 
  1. Open Brave on an iPad or on an iPhone in landscape mode.
  2. Go to https://github.com/brave for example. 
  3. Now you have the menu "New repository, Import repository, New codespace, New gist" Always displayed.

### Expected result:

![IMG_5EB0DF21ED58-1](https://github.com/brave/brave-ios/assets/81828658/ba56660b-ecee-48a7-87aa-6f734500c8ac)

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Every time for me. I tried to disable shields and it didn't worked.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? : Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? : Yes
- Can you reproduce this issue with the current build from AppStore? : Yes

### Device details: 
iPhone 11 on ios 17.2 and iPad air 5th on iPadOS 17.2

### Website problems only:
- did you check with Brave Shields down? : Yes
- did you check in Safari/Firefox (WkWebView-based browsers)? : Yes, no problem on others

**Comment by iccub** [comment]
seems to work

**Comment by Romaindcrl** [comment]
Yes, it is working now. Maybe it was fixed with the last week's release.
