### ISSUE TITLE
Add support for POST search requests

### ISSUE THREAD

**Issue by Romaindcrl** [brave/brave-ios#8342]
## Problem Description 
Actually, GET requests are not private. So, when you search for anything on brave search, your ISP or anyone on a public wi-fi is able to know what is your search about. Some search engines like startpage integrate POST requests so your query is not located in the url. It works on brave but not natively, you have to go on startpage.com then activate "POST requests". If it can be activated on brave natively and maybe on brave search in the future, it can be cool.

## Feature Overview 
Just add a radio input into brave settings so the user can chose if he wants to use POST requests if he's search engine have this option.

## Implementation Details 
<img width="688" alt="Capture d’écran 2023-10-31 à 16 19 58" src="https://github.com/brave/brave-ios/assets/81828658/ed5c6fd5-41b1-43af-86b1-ac23da4d5cf4">

## User Experience 
1. Enable POST requests in brave settings.
2. Enjoy more privacy if the search engine use POST requests

### Additional information 
I can't request this feature for brave search because it is not open source but if someone at Brave wants to...

**Comment by stoletheminerals** [comment]
@TheFlute07 in which cases an ISP or other users on public Wi-FI network would be able to see your SSL encrypted GET request, but won't be able to see SSL encrypted POST request? Keep in mind that search engines in Brave on iOS are HTTPS-only

**Comment by Romaindcrl** [comment]
@stoletheminerals Thanks for your reply, sorry but I saw this feature on Starpage and in my mind GET requests were visible even if https was enabled. I'll close this request with this comment so as not to waste any more of your time. Have a nice day.
