### ISSUE TITLE
Add 'Creating Wallet' step to Wallet Onboarding

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8345]
### Description: 

BraveCore is updating to only register for Wallet Data Files component updates once a wallet has been created, restored or imported in https://github.com/brave/brave-core/pull/20741. This will add a longer async step to `CreateWallet` / `RestoreWallet` that we should show a `Creating Wallet...` step for.

Figma link:
https://www.figma.com/file/oXIiv45pIhF2RGlpEjOfUg/Wallet-onboarding?type=design&node-id=6297-76948&mode=design&t=tFyYpPADJlsYz5jJ-4

https://bravesoftware.slack.com/archives/C3T9S9WKD/p1697828962342039?thread_ts=1697754201.567329&cid=C3T9S9WKD

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.3 with 1.62 (24.1.25.17)
- Verified steps from [#8509](https://github.com/brave/brave-ios/pull/8509)
- Verified `Creating Wallet...`  step shown before creating wallet
- Verified onboarding works as expected for both clean wallet and restore wallet
- Verified dismissing during `Creating Wallet...` and reopening wallet shows Portfolio
