### ISSUE TITLE
Activity v2

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8349]
### Description: 

Implement v2 designs for the Activity tab 

<img width="216" alt="activity tab" src="https://github.com/brave/brave-ios/assets/5314553/0a7b6ccc-491d-4862-8ea1-792a1c2e222a"> | <img width="317" alt="transaction types" src="https://github.com/brave/brave-ios/assets/5314553/9470b0d9-370d-4b67-85ee-a0d877e21efa">
--|--

https://www.figma.com/file/muVcmcu4RFNu0LkXe9VRDl/Wallet-2.0?type=design&node-id=11042-326457&mode=design&t=ZHC6Meo8jpABcgUY-4

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.60 (23.11.30.17)
- Verified steps from [#8390](https://github.com/brave/brave-ios/issues/8390)
- Verified all transactions types are listed under activity tab
- Verified able to filter out transactions
- Verified transactions are grouped by day
- Additional verification [here](https://github.com/brave/brave-ios/issues/8379#issuecomment-1850067384)

<details>
<summary><b>iPhone 13 (iOS 17.2)</b></summary>

![image](https://github.com/brave/brave-ios/assets/17010094/f95624f3-d880-4dc4-a56e-d8ac4532293a) | ![image](https://github.com/brave/brave-ios/assets/17010094/825015f3-5c61-4245-a4d9-b70fff69ca92)
-- | --
![image](https://github.com/brave/brave-ios/assets/17010094/9881e040-542b-4cda-8ffa-cf5120770ee5) | ![image](https://github.com/brave/brave-ios/assets/17010094/0cd8ea66-326b-4594-a18e-4444030a58eb)


</details>
<details>
<summary><b>iPad (iOS 16.7.2)</b></summary>

![image](https://github.com/brave/brave-ios/assets/17010094/0aeb24eb-dc99-4839-8f11-c3bb40540b00) | ![image](https://github.com/brave/brave-ios/assets/17010094/c721c2dd-8700-4c05-8ead-ab4fa4596c60)
-- | --
 ![image](https://github.com/brave/brave-ios/assets/17010094/5d9b8b56-117b-41d4-a1c5-5d67784eff5c) | ![image](https://github.com/brave/brave-ios/assets/17010094/bf46c5f4-9fb8-4653-a28f-dc7dff6ab782)

</details>
<details>
<summary><b>iPhone 7+ (iOS 15.8)</b></summary>

![image](https://github.com/brave/brave-ios/assets/17010094/1208223e-b54e-4f51-ac29-8169a9cfbfa8) | ![image](https://github.com/brave/brave-ios/assets/17010094/55c6b74e-39e4-46aa-876f-3b0a65c89384)
-- | --
![image](https://github.com/brave/brave-ios/assets/17010094/556b369f-8687-4ef3-8a86-3ac58c90572d) | ![image](https://github.com/brave/brave-ios/assets/17010094/cd62aeb0-5c65-4b36-9647-4167026601f7)

</details>
