### ISSUE TITLE
Adding high quality youtube videos to playlist does not work

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#8350]

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` and `iPhone X` running `iOS 17.0.3` and `iOS 16.7` respectively using version `1.58.2 (23.11.3.10)`

- Ensured high quality youtube videos can be added to playlist

Example | Example | Example
-|-|-
![IMG_5225](https://github.com/brave/brave-ios/assets/17885425/d2971c4d-6c6b-40a7-bb85-822a37782a71) | ![IMG_5226](https://github.com/brave/brave-ios/assets/17885425/3ef604e0-cc33-4a3e-ab40-d5f26027005e) | ![IMG_5227](https://github.com/brave/brave-ios/assets/17885425/8122e15f-d52a-4c1b-93a9-980271b17ab7)
