### ISSUE TITLE
Add Subscription Custom Offer Codes Interaction

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#8353]
## Problem Description 

Custom Offer Code should be able redeemed inside Brave Browser. 

## Feature Overview 

Custom code can be redeemed in two ways:

- Within the app, if you’ve incorporated a redeem feature (which we’ll cover in the next section).

- Using the offer code URL: share the URL of the offer code as mentioned below with the user, and they can redeem it by clicking on the URL or opening the URL inside the app.

## Design 

A Redeem Code button should be added to bottom action menu in BUYVPNScreen.

![teatduaa](https://github.com/brave/brave-ios/assets/6643505/cb2ba0d2-4fd6-444e-b095-1b0515bc7ea4)

## Implementation Details 

Browser should support opening https://apps.apple.com/redeem links properly and VPN Purchase screen should have Redeem Code functionality where custom offer codes can be handled.

## User Experience 

1. Open VPN Screen
2. Press Redeem Button
3. Check VPN Code Redeem Handled properly

### Additional information 

After handling SKPaymentQueue.default().presentCodeRedemptionSheet() is presented the default Redeem sheet, be sure VPN functionality is properly handled.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` & `iPad` running `iOS 17.1.1`& `iPadOS 17.0` respectively using version `1.61 (23.12.18.22)`

- Verified `https://apps.apple.com/redeem` page is opened when tapping on `Redeem Code` button using test plan in https://github.com/brave/brave-ios/pull/8354#issue-1975123287
- Verified tapping on `cancel` button in the redeem code page will dismiss the page
- Verified entering value in the redeem code field will enable the `Redeem` button
- Verified error message is shown if code is invalid
- Verified `Try Another Code` will take user back to `https://apps.apple.com/redeem` page

Example | Example | Example | Example
-|-|-|-
![IMG_5432](https://github.com/brave/brave-ios/assets/17885425/d0398add-d853-4cba-9b60-4c11e815e374) | ![IMG_5435](https://github.com/brave/brave-ios/assets/17885425/6bd18974-640b-48ad-be97-82d1dba4c0ed) | ![IMG_5436](https://github.com/brave/brave-ios/assets/17885425/d5f719d7-6e0b-4433-ad97-bac3bb7eaff1) | ![IMG_5438](https://github.com/brave/brave-ios/assets/17885425/f6a86325-1c27-4b0d-be61-a9dbd88ced57)
![IMG_1269](https://github.com/brave/brave-ios/assets/17885425/83c463e8-9118-4f26-bac2-4314c229f977) | ![IMG_1270](https://github.com/brave/brave-ios/assets/17885425/e724092c-2277-427e-a46e-43f424d92976) | ![IMG_1272](https://github.com/brave/brave-ios/assets/17885425/9cba627b-ac9f-4a17-bde1-5dd944c6601e) | ![IMG_1273](https://github.com/brave/brave-ios/assets/17885425/b7024db2-5839-4a66-a825-8f359d4aaedd)
