### ISSUE TITLE
Disable create wallet button once tapped

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8357]
### Description: 

We should disable the `Continue` button on `Create a Password` screen once tapped and `CreateWallet` has been called. Repeated calls to `CreateWallet` can cause [DCHECK hit in core](https://github.com/brave/brave-browser/issues/34095).

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.2 running 1.60 (23.11.12.17)
- Verified steps from [#8358](https://github.com/brave/brave-ios/pull/8358)
- Verified `Continue` button is disabled when pressing the `Return` button on keyboard on password screen
- Verified `Continue` button is disabled when pressed once on the password screen
- Verified only one Ethereum and one Solana account is created when creating a new wallet
- Verified restoring wallet restores all discovered accounts
----------
Verification passed on iPhone 7+ with iOS 15.8 running 1.60 (23.11.12.17)
- Verified steps from [#8358](https://github.com/brave/brave-ios/pull/8358)
- Verified `Continue` button is disabled when pressing the `Return` button on keyboard on password screen
- Verified `Continue` button is disabled when pressed once on the password screen
- Verified only one Ethereum and one Solana account is created when creating a new wallet
- Verified restoring wallet restores all discovered accounts
----------
Verification passed on iPad Pro with iOS 16.7.2 running 1.60 (23.11.12.17)
- Verified steps from [#8358](https://github.com/brave/brave-ios/pull/8358)
- Verified `Continue` button is disabled when pressing the `Return` button on keyboard on password screen
- Verified `Continue` button is disabled when pressed once on the password screen
- Verified only one Ethereum and one Solana account is created when creating a new wallet
- Verified restoring wallet restores all discovered accounts
- Verified restoring on split screen, active window continues with onboarding while the other window dismisses it
- Verified on creating wallet on split view, onboarding is dismissed on inactive window when password is created on active view
- Encountered [#8425](https://github.com/brave/brave-ios/issues/8425)
