### ISSUE TITLE
Private mode text is cut

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#836]
### Steps to Reproduce 
  1. Open Private browsing mode in Polish locale

**Actual result:** 
![img_2358](https://user-images.githubusercontent.com/6950387/52215816-2b1bef80-2895-11e9-8686-2cc7b96aa8ac.PNG)

**Expected result:**
Text should not be trimmed. It should either auto shrink or be split to two lines

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPad Mini 4 running iOS 12.3.1` using `1.10 (19.07.10.17)`
   * Found  https://github.com/brave/brave-ios/issues/1239

![IMG_0241](https://user-images.githubusercontent.com/2602313/61097193-500a2500-a428-11e9-9c3c-0d5dbeb8e11b.PNG)

* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.10.17)`
  * Found  https://github.com/brave/brave-ios/issues/1239

![IMG_9756](https://user-images.githubusercontent.com/2602313/61097179-3bc62800-a428-11e9-9d2b-2d8b3ae41d6f.PNG)
