### ISSUE TITLE
Add separator between inactive tabs

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8361]
## Problem Description 

Please add a separator between inactive tabs with new tab design UI distinguish between 2 inactive tabs similar to desktop.

![Simulator Screenshot - iPhone 14 Pro - 2023-11-06 at 13 47 33](https://github.com/brave/brave-ios/assets/5314553/8739d1c5-e6e9-46f2-ba22-3722be06c637) | <img width="824" alt="PNG image" src="https://github.com/brave/brave-ios/assets/5314553/e077b98f-25f6-4fb7-9406-5504fff72611">
--|--

**Comment by kylehickinson** [comment]
Ref brave/brave-ios#8078

**Comment by kylehickinson** [comment]
Updated Browser UI in Figma design doesn't include them but I agree we should add them back anyways

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.2
- iPad Air / iPadOS 16.7.2
Brave build: 1.61 (23.12.11.17)
BraveCore: 1.61.102 (120.0.6099.71)
```
Observed this issue brave/brave-browser#36102 during the verification 
---------------------------

**STEPS:**
1. Launch Brave 
2. Open multiple tabs
3. Switch between tabs to make a random tab an `active tab` > Verify

**ACTUAL RESULTS:**
- Verified that a separator between non-active tabs is present
- Verified that the separator is shown with `Top Bar` and `Bottom Bar` and when `Tabs Bar` is set to `On` or `Landscape Only`

---------------------------

*iPhone / iOS 17.2*

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/51388c80-d9ba-4d6d-89bf-40658360dcb2) | ![2](https://github.com/brave/brave-ios/assets/128532965/504e2b13-498c-4d5e-b2ca-4fe3af8b1152) | ![3](https://github.com/brave/brave-ios/assets/128532965/7fd27376-1c0d-4d67-aef5-a9f830466609) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/7daa9e8c-5d69-47ba-b577-068cc86dd860) | ![2](https://github.com/brave/brave-ios/assets/128532965/3d077a94-38ca-42e4-8305-467e32efdd3d) | ![3](https://github.com/brave/brave-ios/assets/128532965/2f5143c8-5cb5-48d5-9f09-505713b54043) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/11fbb8f2-5dbd-4dce-9c4f-d0187c222383) | ![2](https://github.com/brave/brave-ios/assets/128532965/b727737b-60a6-48e4-bac4-eaaa040df75c) | ![3](https://github.com/brave/brave-ios/assets/128532965/f709e5e8-4423-4e9b-854d-a85cdf0b7687) |

*iPad Air / iPadOS 16.7.2*

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/1c1d0f91-3524-406b-8d62-0b66eb072d97) | ![2](https://github.com/brave/brave-ios/assets/128532965/6cec9290-7dbb-4f8e-991f-ec5a3639a4ad) | ![3](https://github.com/brave/brave-ios/assets/128532965/504e7c8c-ec0d-4f62-b3b4-7999083f4d33) |
