### ISSUE TITLE
Youtube rendering issue

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#8364]
### Description: 
When going to YouTube, the page sometimes renders badly
![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-11-06 at 15 25 30](https://github.com/brave/brave-ios/assets/909331/504b49dd-70e1-451f-8807-dce982647eff)

### Steps to Reproduce 
  1. Open two YouTube tabs on iPad and play a video on each
  2. Keep switching between the two tabs until issue occurs

### Actual result: 
Page renders badly

### Expected result:
Page should render properly

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 
1.60

### Device details: 
iPad Pro 12.9" (6th generation) simulator

### Website problems only:
- did you check with Brave Shields down?  Yes, occurs with shields off as well
- did you check in Safari/Firefox (WkWebView-based browsers)?  Yes. Does not occur in safari

### Additional Information
Seems to be caused by the following PR: https://github.com/brave/brave-ios/pull/8363

**Comment by hffvld** [comment]
Verified on `iPad Air` using version(s):
```
Device/OS: iPad Air / iPadOS 16.7.2
Brave build: 1.60 (23.11.12.17)
BraveCore: 1.60.114 (119.0.6045.124)
```

Filed follow-up issue #8406
---------------------------

**STEPS:**
1. Launch Brave 
2. Followed the steps from https://github.com/brave/brave-ios/issues/8364#issue-1980286448

**ACTUAL RESULTS:**
- Verified that YT UI is rendered correctly when switching between tabs
- Verified the same when refreshing these tabs as well

---------------------------

https://github.com/brave/brave-ios/assets/128532965/56f35247-1929-4ee0-9b1c-6931b51cd59f
