### ISSUE TITLE
Content blockers are not removed when ad-block and tracking protection is disabled

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#8369]
### Description: 
We remove content blockers when all shields are disabled but not when ad-block and tracking protection is disabled

### Steps to Reproduce 
Will need to inspect the page
  1. Enable inspector
  2. Load a website (e.x. amazon.com). (Refresh if you enabled inspector after loading the page)
  3. Notice content is being blocked via the content blocker (i.e. you see: `Content blocker prevented frame displaying ...` debug messages)
  3. Clear console, Disable "Trackers & Ads Blocking" and allow the page to reload.

### Actual result: 
Content still being blocked (i.e. you still see `Content blocker prevented frame displaying...` debug messages)

### Expected result:
Content should not be blocked (i.e. should not see any `Content blocker prevented frame displaying...` debug messages)

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

### Brave Version: 
v1.58

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details: 
Any

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.0.3` using version `1.60 (23.11.7.17)`

- Verified STR in https://github.com/brave/brave-ios/issues/8369#issue-1982009739
- Verified content blockers are removed when `Trackers & Ads Blocking` is disabled in Shields.
- Verified disabling Shields will also remove content blockers
- Verified re-enabling `Trackers & Ads Blocking` switch will more content blockers

Default | ad-Block disabled in Shields | Shields disabled | Re-enabling ad-blocking
-|-|-|-
![Screenshot 2023-11-08 at 11 58 05 AM](https://github.com/brave/brave-ios/assets/17885425/41e71a29-9046-461e-b2db-dcf196f94a6f) | ![Screenshot 2023-11-08 at 11 58 58 AM](https://github.com/brave/brave-ios/assets/17885425/86ce3b48-9471-4d58-962b-c0cbfe08ba79) | ![Screenshot 2023-11-08 at 12 00 44 PM](https://github.com/brave/brave-ios/assets/17885425/7486818b-4bfb-4aa3-81d9-a77ed7dda5f3) | ![Screenshot 2023-11-08 at 12 01 05 PM](https://github.com/brave/brave-ios/assets/17885425/0bade28c-5ecd-45ac-8742-8da326e9bdb4)
