### ISSUE TITLE
[Follow up to #8332] Cursor is misplaced for a selected URL when that URL doesn't fit the screen

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#8374]
### Description: 

Follow-up to #8332

### Steps to Reproduce 
  1. Launch Brave
  2. Open any website with a long URL, for example, https://www.apple.com/shop/buy-iphone/carrier-offers or https://en.m.wikipedia.org/wiki/National_Organization_for_the_Reform_of_Marijuana_Laws
  3. Tap on the URL search bar > Observe

### Actual result: 

The cursor is misplaced for a selected URL when that URL doesn't fit the screen. This is happening in both `Portrait` and `Landscape` Modes.

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/b4ee2fb5-fb05-40dc-8dea-305a83d6e504) | ![2](https://github.com/brave/brave-ios/assets/128532965/4883f6a4-8e62-4c32-b35e-437b96bcc08f) |

https://github.com/brave/brave-ios/assets/128532965/5d043d18-f5d2-4752-866b-cfc5670bd262

### Expected result:

`Front` and `Back` cursors must be properly shown.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

```
Brave build: 1.60 (23.11.7.17)
BraveCore: 1.60.113 (119.0.6045.105)
```

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? YES

### Device details: 

iPhone 14 / iOS 17.2

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Most likely an iOS 17 bug. Need more investigation

**Comment by cooperbang** [comment]
Still a occurs with Brave Version 1.61 (23.12.18.22) and iOS 17.2.1 (iPhone 11).

I think it‘s not an iOS 17 Bug because in Safari it’s ok.

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.2
Brave build: 1.62 (24.1.9.23)
BraveCore: 1.62.128 (120.0.6099.144)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-ios/pull/8612#issue-2064698049

**ACTUAL RESULTS:**
- Verified that `short` and `long` URLs are  selected properly

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/711bfdb8-d466-4e36-8b8d-37110b36c840) | ![2](https://github.com/brave/brave-ios/assets/128532965/5c607666-3c88-4d02-bd4d-12e6dc93b970) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/6b4bb682-09e5-4bbf-853d-232f2c20431b) | ![2](https://github.com/brave/brave-ios/assets/128532965/f2e9df88-b349-4788-95f9-2b0820b17b1d) |
