### ISSUE TITLE
Update Blockies

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8375]
### Description: 

Update Blockie’s to the new styling: 

https://github.com/brave/blockies/pull/2

ref:
https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1699450616856909

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.62 (24.1.25.17)
- Verified steps from [#8510](https://github.com/brave/brave-ios/pull/8510)
- Verified blockies are updated to new icon as per design
- Verified updated blockies is shown in all locations

iPhone 13 (iOS 17.3) | iPad (iOS 16.7.8) | iPhone 7+ (iOS 15.8)
-- | -- | --
![image](https://github.com/brave/brave-ios/assets/17010094/b7a0b906-ca2c-47c9-904f-9a27282dd14a) | ![image](https://github.com/brave/brave-ios/assets/17010094/f25a96da-d17d-4fa5-ba92-19d214650726) | ![IMG_0069](https://github.com/brave/brave-ios/assets/17010094/8bfd11fb-fa04-4da7-8f91-ccd1b3fb2604)
![image](https://github.com/brave/brave-ios/assets/17010094/c1be632e-7420-4a11-b057-47a0fad232db) | ![image](https://github.com/brave/brave-ios/assets/17010094/2e7efeae-a857-47f0-9937-441ec3e10527) | ![IMG_0068](https://github.com/brave/brave-ios/assets/17010094/9d40f01c-fef8-4448-941f-99cac8fdd8e4)
![image](https://github.com/brave/brave-ios/assets/17010094/6c9a1762-859f-4e18-ba87-68ec59ca00e7) | ![image](https://github.com/brave/brave-ios/assets/17010094/73001417-cf01-4fd1-814a-a4e86c3f0c30) | ![IMG_0071](https://github.com/brave/brave-ios/assets/17010094/af2f03cf-663d-4056-9667-63b70eadc860)
![image](https://github.com/brave/brave-ios/assets/17010094/a6fa21d2-d27b-474e-bcc8-97be45d6114d) | ![image](https://github.com/brave/brave-ios/assets/17010094/a640b737-af0f-48e3-87cf-7e14ec963522) | ![IMG_0072](https://github.com/brave/brave-ios/assets/17010094/60cf4339-bc90-4761-9716-ac7fd0469a64)
![image](https://github.com/brave/brave-ios/assets/17010094/10d3296d-4c45-4a0a-a526-7a870ca0a074) | ![image](https://github.com/brave/brave-ios/assets/17010094/6320a5f1-dd22-476a-9610-db6b6ba8f2de) | ![IMG_0070](https://github.com/brave/brave-ios/assets/17010094/d47d6d9a-9178-498d-87c7-3f113ec9feb8)
