### ISSUE TITLE
Transaction Detail v2

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8379]
### Description: 

Update Transaction Detail to v2 UI

<img width="238" alt="Send ETH - In Progress" src="https://github.com/brave/brave-ios/assets/5314553/eaba2446-39bf-477f-b18c-1f4d3ef08c6d"> | <img width="227" alt="Send ETH - Failed" src="https://github.com/brave/brave-ios/assets/5314553/ca567b4e-e37d-4540-95f9-663c15c4cb51"> | <img width="232" alt="Send ETH - Success" src="https://github.com/brave/brave-ios/assets/5314553/e753d4c6-8a49-49b0-87a4-d3d27230c639"> |  <img width="241" alt="Send NFT" src="https://github.com/brave/brave-ios/assets/5314553/cd54fb51-bffd-4955-8800-dc7e239a31a7">
--|--|--|--

https://www.figma.com/file/muVcmcu4RFNu0LkXe9VRDl/Wallet-2.0?type=design&node-id=11042-326457&mode=design&t=ZHC6Meo8jpABcgUY-4

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.61(23.12.30.17)
- Verified steps from [#8474](https://github.com/brave/brave-ios/pull/8474)
- Verified transaction hash is shown 
- Verified able to copy the From and To address
- Verified selecting Account and opening the transactions shows the transaction UI similar to shown in Activity tab
- Verified selecting token and opening the transactions shows the transaction UI similar to shown in Activity tab
- Verified transaction hash can be copied by tapping on the copy button next to transaction hash
- Verified correct explorer link is opened when tapped on the open in explorer button

<details>
<summary><b>iPhone 13 (iOS 17.2)</b></summary>

![image](https://github.com/brave/brave-ios/assets/17010094/66ba06f9-11cb-4349-824a-f65e330941a7) | ![image](https://github.com/brave/brave-ios/assets/17010094/6a421a17-ed7f-47eb-b8e8-79fd34034694) | ![image](https://github.com/brave/brave-ios/assets/17010094/a8145329-d75f-4fb7-9246-bfdd52e0dbd2) | ![image](https://github.com/brave/brave-ios/assets/17010094/fe156cef-4850-480e-992b-dd7971096269) |![image](https://github.com/brave/brave-ios/assets/17010094/8e2f404c-060c-458e-afbc-768a5f3bcaa9)
-- | -- | -- | -- | --
![image](https://github.com/brave/brave-ios/assets/17010094/68fa1da0-86e9-456c-ac92-dbb5626214b4) | ![image](https://github.com/brave/brave-ios/assets/17010094/a3314779-55c5-4a31-b7d1-e0aa6642f4b7) | ![image](https://github.com/brave/brave-ios/assets/17010094/570909ce-1dd2-425f-9467-9c7cf11109e9) | ![image](https://github.com/brave/brave-ios/assets/17010094/7ad12a09-0fc0-45f3-8eb5-aff87f3e95d9) |  ![image](https://github.com/brave/brave-ios/assets/17010094/3a27ee5b-b16f-4f7d-a0b0-3f3127ccbdd2)


</details>

<details>
<summary><b>iPad  (iOS 16.7.2)</b></summary>

 ![IMG_0050](https://github.com/brave/brave-ios/assets/17010094/d4cdf76f-fa0d-4c1d-90c6-cf9c6343ffa7) | ![IMG_0051](https://github.com/brave/brave-ios/assets/17010094/ddc031db-66db-4ac2-a20b-c393d2a0480f) | ![IMG_0054](https://github.com/brave/brave-ios/assets/17010094/f5c1c5f3-bd12-4f44-9add-01e002ed10fd) | ![IMG_0055](https://github.com/brave/brave-ios/assets/17010094/6a574fa0-0fea-46e0-b8e0-8be71a617528)
-- | -- | -- | --
![IMG_0049](https://github.com/brave/brave-ios/assets/17010094/1678b484-36ae-4d2b-80a9-b56acf1323c9) |  ![IMG_0052](https://github.com/brave/brave-ios/assets/17010094/62ae274f-5939-4764-b9b0-6855d21c3fe9) | ![IMG_0053](https://github.com/brave/brave-ios/assets/17010094/2bf3ce54-0ee1-4f5a-b6a6-113db167c0b7) | ![IMG_0056](https://github.com/brave/brave-ios/assets/17010094/0a553247-a53b-46ad-8ab4-1eb4a0d3033f)

</details>
<details>
<summary><b>iPhone 7+ (iOS 15.8)</b></summary>

![image](https://github.com/brave/brave-ios/assets/17010094/98515655-6f31-4f05-bf51-cbf4b1a89721) | ![image](https://github.com/brave/brave-ios/assets/17010094/dc5c203c-ca0d-4616-9c7a-3e4f71eb6fcd) |![image](https://github.com/brave/brave-ios/assets/17010094/3e1bf73c-3fdd-4548-a465-12be17d70e9d) | ![image](https://github.com/brave/brave-ios/assets/17010094/e5421ed1-a3c9-4eb8-aea8-165d2d6d8d4c) | ![image](https://github.com/brave/brave-ios/assets/17010094/99f75a81-3f6d-4050-bb77-79a8b77c967b)
-- | -- | -- | -- | --
![image](https://github.com/brave/brave-ios/assets/17010094/7af957e2-58b6-4e06-b31e-97fa7cd761d5) | ![image](https://github.com/brave/brave-ios/assets/17010094/ea66748e-8392-4408-b897-9499ed05b566) |  ![image](https://github.com/brave/brave-ios/assets/17010094/8614624d-58a4-4d15-856d-de4c97d42861) | ![image](https://github.com/brave/brave-ios/assets/17010094/feba8c32-e724-40a2-9b51-8ec32aeb2f30) | ![image](https://github.com/brave/brave-ios/assets/17010094/b0f2620d-8bc8-4a23-a5e4-853e0a2d6cfc)

</details>
