### ISSUE TITLE
Handling External links on NTP does not work

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#8383]
### Description: 

Universal links which should trigger an external app have problem for triggering designated action when they are executed in NTP.

### Steps to Reproduce 
  1. Copy Paste and universal link like AppStore link https://apps.apple.com/us/app/brave-private-web-browser-vpn/id1052879175 
  2. Press Go 
  3. Check link doesnt trigger

### Actual result: 

Running the link from NTP doesnt do anything at all.

https://github.com/brave/brave-ios/assets/6643505/b203d241-bf56-4a76-8022-4483eb5c5f8c

### Expected result:

Link should trigger and show an alert saying this link will open an external link and require a user approval click

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
Problem started with 1.58

### Website problems only:
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

### Additional Information
This problem is introduced while handling https://github.com/brave/brave-ios/pull/8048

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.2
- iPad Air / iPadOS 16.7.2
Brave build: 1.60 (23.11.9.15)
BraveCore: 1.60.114 (119.0.6045.124)
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-ios/issues/8383#issue-1985745037

**ACTUAL RESULTS:**
- Verified that opening a universal link like the Appstore link `https://apps.apple.com/us/app/brave-private-web-browser-vpn/id1052879175` is triggering an alert message saying that this link will be opened in an external app and requires a user approval.

---------------------------

|iPad|iPhone|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/51582737-3273-4aa8-b0a0-08cd02b8369c) | ![2](https://github.com/brave/brave-ios/assets/128532965/07563472-ff94-4e2f-a16f-013e733e5951) |

https://github.com/brave/brave-ios/assets/128532965/b4f0281e-312b-48c3-8adf-1bc43b845f37
