### ISSUE TITLE
Sign in page on https://developer.apple.com is not loading

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#8392]
### Steps to Reproduce 
  1. Launch Brave
  2. Go to https://developer.apple.com
  3. Hamburger menu > Account > Observe

### Actual result: 

The sign-in page on https://developer.apple.com is not loading in `Brave`. At the same time, it's working fine in `Safari` and `Chrome` on the same `iPhone` and `iPad`. Also, it's working in `Brave` on `Android`.

|iPhone Brave|
|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/5d1e3fbc-f0c9-493e-b9f2-a3b4282d5fd3) |

https://github.com/brave/brave-ios/assets/128532965/0a870bac-5d49-4626-be96-c6932efe2bc2

### Expected result:

The sign-in page must be loaded properly.

|iPhone Safari|iPhone Chrome|Android Brave|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/3db33688-4ff6-427b-af4e-21202d8a98c5) | ![2](https://github.com/brave/brave-ios/assets/128532965/ebd6d947-8ed9-4635-92f9-e7b4de160a24) | ![3](https://github.com/brave/brave-ios/assets/128532965/9e5b9bc8-35e6-402d-a80d-30ad54c91ade) |

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

```
Brave build: 1.60 (23.11.9.15)
BraveCore: 1.60.114 (119.0.6045.124)
```

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? YES

### Device details: 

```
- iPhone 14 / iOS 17.2
- iPad Air / iPadOS 16.7.2
```

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
This is caused by a change in Apple's login page which conflicts with security hardening done in our base JS script (`__firefox__.js`), it will affect all versions including app store

**Comment by kylehickinson** [comment]
Re-opening as the change didnt seem to fix it

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.2
Brave build: 1.60 (23.11.15.16)
BraveCore: 1.60.114 (119.0.6045.124)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Follow the steps from https://github.com/brave/brave-ios/issues/8392#issue-1988143798

**ACTUAL RESULTS:**
- Verified that the sign-in page on `https://developer.apple.com/` is loading properly.

---------------------------

|1|
|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/8c392aba-2342-479d-8822-2a7051a90ed2) |
