### ISSUE TITLE
[Follow up to #4358] The page is not closed/removed automatically after `.mobileconfig` file is downloaded

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#8393]
### Description: 

Follow-up to #4358

### Steps to Reproduce 
  1. Launch Brave
  2. Go to `https://gist.githubusercontent.com/nstanke/1df2ad86487c3b9a805d/raw/9b09ade1208a7f9ab41d3b3e7ca76fb1d877bece/mailinabox.mobileconfig`
  3. See a pop-up message > Tap `Allow`
  4. Tap `Close` > Observe
  5. Tap `Done` > Observe

### Actual result: 

The page is not closed/removed automatically after `.mobileconfig` file is downloaded.

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/1bbc87fc-d23e-4c9c-8b09-105a3cb7dc66) | ![2](https://github.com/brave/brave-ios/assets/128532965/01328be4-3d22-496d-abfb-6b86685e215a) | ![3](https://github.com/brave/brave-ios/assets/128532965/c6d06323-760d-44de-a8b7-01b257590c1d) | ![4](https://github.com/brave/brave-ios/assets/128532965/ba80751e-03ad-4901-a492-5a118f112863) |

https://github.com/brave/brave-ios/assets/128532965/c065ed1f-9c34-442b-a993-957bdb439742

### Expected result:

After `.mobileconfig` file is downloaded, that page must be closed/removed automatically similar to what is happening in Safari.

https://github.com/brave/brave-ios/assets/128532965/a7ed56dd-59e1-4a41-bb2e-f44021c9c371

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

```
Brave build: 1.60 (23.11.9.15)
BraveCore: 1.60.114 (119.0.6045.124)
```

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? N/A
- Can you reproduce this issue with the current build from AppStore? N/A

### Device details: 

iPhone 14 / iOS 17.2

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
Good catch! This works when loading a mobileconfig would be done in a new tab or that tab ends up being `about:blank` but doesnt seem to work when you load it directly from the URL bar using a raw mobileconfig url

**Comment by kylehickinson** [comment]
This turned out to be unrelated to `mobileconfig` specifically and can happen to any cancelled request that we have

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.1.1` and `iPhone X` running `iOS 16.7` using version `1.61 (23.12.7.20)`

Using STR in https://github.com/brave/brave-ios/issues/8393#issue-1988265395

- Ensured that address bar is empty after successfully downloading the profile and closing the windows. 

Example | Example | Example | Example
-|-|-|-
![IMG_5375](https://github.com/brave/brave-ios/assets/17885425/c1c6bd65-c6c4-436e-a53d-071f3b2f9758) | ![IMG_5376](https://github.com/brave/brave-ios/assets/17885425/75a586c6-a0db-4c2d-96fc-c44d8d66f9ce) | ![IMG_5377](https://github.com/brave/brave-ios/assets/17885425/fafafe5f-fbc5-49a6-b5aa-ae4b9b1fada6) | ![IMG_5378](https://github.com/brave/brave-ios/assets/17885425/7dda2a8c-726f-4598-a8da-1e2799c71f4d)
