### ISSUE TITLE
[Follow up to #8078] `VPN` title has a different font color than all other strings in the `Main menu`

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#8396]
### Description: 

Follow-up to #8078

### Steps to Reproduce 
  1. Launch Brave `1.60.x`
  2. Open `Main menu` by tapping `•••` > Observe

### Actual result: 

The `VPN` title has a different font color than all other strings in the `Main menu`. It looks a little bit lighter.

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/88876d5b-72a3-467a-b92b-5fbaf08aa228) | ![2](https://github.com/brave/brave-ios/assets/128532965/95f52c7d-3b90-4a14-afbc-8982146bae46) | ![3](https://github.com/brave/brave-ios/assets/128532965/2bc9ba94-9ca0-46c2-ba4f-20f824e5bba2) | ![4](https://github.com/brave/brave-ios/assets/128532965/a4c8a276-e186-424a-9040-45bfba9acf40) |

### Expected result:

All strings in the `Main menu` must have the same font color.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

```
Brave build: 1.60 (23.11.9.15)
BraveCore: 1.60.114 (119.0.6045.124)
```

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? NO
- Can you reproduce this issue with the current build from AppStore? NO

### Device details: 

iPhone 14 / iOS 17.2

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `iPhone X` using version `1.61 (23.12.7.19)`

- Ensured all menu items in main menu have the same text color. 

Example | Example
-|-
![Screenshot 2023-12-07 at 4 42 12 PM](https://github.com/brave/brave-ios/assets/17885425/f4050ba8-6c95-48e8-ac2b-5cf9a8795e1a) | ![Screenshot 2023-12-07 at 4 42 22 PM](https://github.com/brave/brave-ios/assets/17885425/c15313b6-c30a-40e4-bc5c-856d115325dd)
![Screenshot 2023-12-07 at 4 49 32 PM](https://github.com/brave/brave-ios/assets/17885425/be5d3938-b840-4ecf-98f1-003ab3f735b1) | ![Screenshot 2023-12-07 at 4 49 45 PM](https://github.com/brave/brave-ios/assets/17885425/0555a146-1234-4714-89c5-ba689f969673)
