### ISSUE TITLE
iPad displays bottom toolbar incorrectly after opening Playlist

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#8410]
### Description: 
There is a bad UI bug on 1.58

![IMG_0997](https://github.com/brave/brave-ios/assets/7606853/fe7bb7e2-f8c2-42ee-9b9b-d6eaf2a98aa2)

### Steps to Reproduce 
  1. Open Brave on iPad
  2. Open Playlist
  3. Add an item to Playlist (may not be needed)
  4. Close Playlist

### Actual result: 
UI is very broken, iPhone UI on iPad

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kylehickinson** [comment]
Most likely related to https://github.com/brave/brave-ios/issues/8407

**Comment by kylehickinson** [comment]
Closing in favor of https://github.com/brave/brave-ios/issues/8421
