### ISSUE TITLE
NFT Popups not dismissed on auto-lock

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8412]
### Description: 

The popup to auto-discover NFTs, and the popup to confirm removal of an NFT are not dismissed when the wallet is auto-locked, blocking interaction with Wallet Unlock

### NFT Auto-discovery
  1. Restore a Wallet
  2. Update Auto-lock timer to 1 minute in Web3 Settings
  3. Visit Portfolio tab & Tap NFTs in segmented control
  4. Do not interact with popup, wait for auto-lock.
  5. Observe popup visible over unlock screen, blocking interaction
  
### NFT Removal
  1. Update Auto-lock timer to 1 minute in Web3 Settings
  2. Tap & hold on an NFT and select `Don't show in wallet`
  3. Do not interact with popup, wait for auto-lock.
  4. Observe popup visible over unlock screen, blocking interaction
  
  
### Actual result: 

![Discovery](https://github.com/brave/brave-ios/assets/5314553/452dd23d-ac85-433a-a5c2-e64311de975b) | ![Remove NFT](https://github.com/brave/brave-ios/assets/5314553/83382d53-ac64-405b-8e20-86a7693fdb00)
--|--

### Expected result:

Alerts are dismissed when wallet is auto-locked

### Reproduces how often: 

Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.2 running 1.61 (23.11.30.17)
- Verified steps from [#8413](https://github.com/brave/brave-ios/pull/8413)
- Verified NFT auto-discovery modal is dismissed when wallet is auto-locked
- Verified unlocking wallet clears the modal and switching to NFT tab triggers it again
- Verified Remove NFT modal is dismissed when wallet is auto-locked
- Verified unlocking wallet clears the modal and long press on the same NFT brings up the Remove NFT modal

NFT Auto-Discovery | NFT Remove NFT Modal
-- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/6c22c3a1-495d-4cc9-9acd-af69fe70f486> | <video src=https://github.com/brave/brave-ios/assets/17010094/be49328f-2ee1-49ad-ac83-982691033d92>
