### ISSUE TITLE
Wallet: Solana NFT in Asset Search is going to Asset Details instead of NFT details

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#8418]
STR:
1. Set up wallet and add a Solana NFT
2. Open Asset search screen and find that NFT
3. Click this NFT 
Expect:
NFT Details Screen
Actual:
Asset Detail Screen

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.61 (23.11.30.17)
- Verified steps from issue description
- Verified NFT details is shown when selecting NFT 
- Encountered [#8513](https://github.com/brave/brave-ios/issues/8513) on iOS 15.8

iPhone 13 (iOS 17.2) | iPad (iOS 16.7.2)
-- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/56909fb8-0e55-4270-9005-3787bedeac63> | <video src=https://github.com/brave/brave-ios/assets/17010094/5f7b6ea6-cde9-4a1e-a56d-a1083ec5f883>
