### ISSUE TITLE
Copy mistake in confirmation message after resetting VPN config

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#8431]
### Description: 
Copy mistake in confirmation message after resetting VPN config

### Steps to Reproduce 
  1. Enable VPN
  2. Open Brave Firewall + VPN settings menu
  3. Select Reset Configuration, confirm reset
  4. Observe 

### Actual result: 
<img width="500" alt="0" src="https://github.com/brave/brave-ios/assets/17885425/0300802e-0b60-4d6e-8ca2-c0d108f04dd4">

### Expected result:
Should be "reset"

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

### Brave Version: 
1.60

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? No (new feature)

### Device details: 
iPhone

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by soner-yuksel** [comment]
Success case should show 


Title: Reset Successful
Body: VPN configuration has been reset successfully.

**Comment by soner-yuksel** [comment]
And Reset case will be 

Title: Reset Failed
Body: Unable to reset VPN configuration. Please try again. If the issue persists, contact support for assistance.
Buttons: Close | Try Again

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.0.3` using version `1.60 (23.11.20.17)`

- Verified copy changes for `Reset Configuration` setting flow.
- Verified tapping `Try Again` when resetting fails will reset configuration again. 
- Verified tapping `Close` will close dialogs.

Reset Success | Reset Failed
-|-
![IMG_5292](https://github.com/brave/brave-ios/assets/17885425/fdb1925e-8b32-4af8-825c-543c50ebacf3) | ![IMG_5293](https://github.com/brave/brave-ios/assets/17885425/c14e1a6b-e86e-4804-b814-aee0bf73abf0)
