### ISSUE TITLE
Unable to `dismiss` or `downvote` ad notification on iPhone and iPad

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#8444]
### Description: 

Unable to `dismiss` or `downvote` ad notifications on iPhone and iPad.

### Steps to Reproduce 
  1. Launch Brave
  2. Enable `Brave Rewards`
  3. Wait until you see `ad notification`
  4. Try to `dismiss` or `downvote` it > Observe

### Actual result: 

Unable to `dismiss` or `downvote` ad notifications on iPhone and iPad.

https://github.com/brave/brave-ios/assets/128532965/19dc4b28-699d-464b-904c-4e3212d696af

### Expected result:

Must be able to `dismiss` or `downvote` ad notifications.

|1|
|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/c76b0f21-3dea-40ee-af1b-840f673e6938) |

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

```
Brave build: 1.60 (23.11.17.20)
BraveCore: 1.60.114 (119.0.6045.124)
```

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? NO
- Can you reproduce this issue with the current build from AppStore? NO

### Device details: 

- iPhone 14 / iOS 17.2
- iPad Air / iPadOS 16.7.2

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
This was removed in 1.60

https://github.com/brave/brave-ios/issues/8211
