### ISSUE TITLE
App crashes when leaving a Brave Talk call

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#8446]
### Description: 

Small regression in https://github.com/brave/brave-ios/pull/8306

### Steps to Reproduce 
  1. Launch native talk via talk.brave.com 
  2. End the call or close before entering the call

### Reproduces how often: 
Always

### Brave Version: 1.60+

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.1.1` using version `1.60 (23.11.20.17)`

- Verified crash is not reproducible using STR in https://github.com/brave/brave-ios/issues/8446#issue-2002466384.
- Verified ending brave talk call or closing before entering the call does not cause crash.
- Verified crash does not happen on fresh and upgrading profiles.
