### ISSUE TITLE
Device name gets duplicated if sync chain fails the first time

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#845]
### Description: 
Device name gets duplicated if sync chain fails the first time

### Steps to Reproduce (May not be reliable steps)
  1. Scan a QR code quickly 
  2. Move the camera away and lock the device so that sync chain fails
  3. Scan the QR again to join the sync chain
  4. Device name gets duplicated

**Actual result:** 
Device name gets duplicated if sync chain fails the first time

**Expected result:**
Device name shouldn't get duplicated if sync chain fails the first time and device joins a chain on second attempt

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
In between easy and intermittent. If you are lucky everytime otherwise its intermittent

**Brave Version:** 
1.8(19.02.05.03)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
Related to #844

**Comment by LaurenWags** [comment]
Reproduced on iPad 5th Gen with 1.9 (19.03.09.01). ~~No idea how my sync chain failed the first time, but it did and when I went to retry sync I saw the device name listed twice:~~ Consistently got sync chain to fail with https://github.com/brave/brave-ios/issues/977
![IMG_0285](https://user-images.githubusercontent.com/28145373/54454811-af814e00-4730-11e9-996f-a70d067e22cc.PNG)
