### ISSUE TITLE
Don't navigate to `javascript://` URLs from the omnibox

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-ios#8453]
### Description: 
It seems that something was changed recently that enabled omnibox navigations to `javascript://` URLs. It should be reverted.

### Steps to Reproduce 
  1. Go to any webpage
  2. Type javascript:alert(123) in the url bar
3. Press enter

### Actual result: 
An alert is displayed
<img src="https://github.com/brave/brave-ios/assets/10810135/498da882-b4af-4c33-aeb2-2837fc9110c3" width=300></img>

### Expected result:
Nothing happens

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
Reproducible in the development build
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 
No

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by diracdeltas** [comment]
nice find. @brave/ios is there some kind of automated or QA test that can be added to make sure it doesn't regress again?

**Comment by soner-yuksel** [comment]
> nice find. @brave/ios is there some kind of automated or QA test that can be added to make sure it doesn't regress again?

@kjozwiak can we add this small test case to manual passes ?

Sorry this was caused by me while refactoring visit type state inside the browser.
@stoletheminerals I tagged you in the PR and thanks for the catch.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.1.1` using version `1.60 (23.11.24.16)`

https://github.com/brave/brave-ios/assets/17885425/66eb74c9-fa54-4bcb-ab1c-82b96a89af98

**Comment by kjozwiak** [comment]
> > nice find. @brave/ios is there some kind of automated or QA test that can be added to make sure it doesn't regress again?
> 
> @kjozwiak can we add this small test case to manual passes ?
> 
> Sorry this was caused by me while refactoring visit type state inside the browser. @stoletheminerals I tagged you in the PR and thanks for the catch.

@soner-yuksel @diracdeltas we'll add a quick check/test into our manual passes. Created https://github.com/brave/qa-resources/issues/565 so we don't forget.
