### ISSUE TITLE
Accounts tab modals reset when returning from background

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8459]
### Description: 

Modals presented in the account tab are reset when the app is backgrounded and then user returns from background. This can also occur when using biometrics to fill in password in the Backup Seed Phrase flow.

#### Backup modal
  1. Visit Accounts tab
  2. Tap `Backup` button.
  3. Enter password and toggle the switch then press `Continue`
      - Alternatively, you can simply use Face ID / Touch ID to reproduce the bug. This technically puts the app into background state, then active state.
  4. Open application switcher to 'background' Brave app.
  5. Bring Brave app back into active state.
  6. Observe Backup flow has been reset to the start / password screen (password field empty, toggle disabled).
  
#### Add account modal
  1. Visit Accounts tab
  2. Tap `+` button.
  3. Tap on any of the coin types to enter a detail view
  4. Open application switcher.
  5. Bring Brave back into foreground
  6. Observe Add Account flow has been reset to the start / coin type selection. 

### Actual result: 

https://github.com/brave/brave-ios/assets/5314553/00bf82ea-10bf-425c-ba4a-f71b90f45032

### Expected result:

Modals remain in state they were backgrounded in.

### Reproduces how often: 

Easily reproduced

### Brave Version: 

v1.60+ (requires built with Xcode 15 SDK)

### Device details: 

iOS 17+

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.60 (23.11.23.16)
- Verified steps from issue description and [#8460](https://github.com/brave/brave-ios/pull/8460)
- Verified Backup wallet phrase flow is not reset when App is backgrounded/switched back
- Verified Account creation flow is not reset when App is backgrounded/switched back

iPhone 13 (iOS 17.2) | iPad Pro (iOS 16.7.2) | iPhone 7+ (iOS 15.8)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/73682f68-eefe-426f-8272-38ce07f176fa> | <video src=https://github.com/brave/brave-ios/assets/17010094/5e0d9984-e1e5-4545-aed5-7ed173d172c3> | <video src=https://github.com/brave/brave-ios/assets/17010094/6e910e3b-ef7b-4908-b96d-f68d22d72b18>
<video src=https://github.com/brave/brave-ios/assets/17010094/325ef17a-342c-4371-9b75-e67cd912d0a5> | <video src=https://github.com/brave/brave-ios/assets/17010094/167f92c4-27bc-4192-989c-017eb4a9d0a4> | <video src=https://github.com/brave/brave-ios/assets/17010094/af02b6c8-ff16-41f0-a300-679fa71292d2>
