### ISSUE TITLE
Sync page doesn't update until navigating out of sync page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#846]
### Description: 
Sync page doesn't update until navigating out of sync page

### Steps to Reproduce 
  1. Create sync chain on desktop
  2. Use QR code to join the sync chain on iOS
  3. Remove iOS device from desktop
  4. Desktop name gets duplicated on iOS, sync chain isn't removed, You can still add a new sync device via iOS
  5. Navigate out of settings page only then sync resets and shows the sync main page

**Actual result:** 
Sync page doesn't update until navigating out of sync page

**Expected result:**
Once device is reset and removed form sync chain it should automatically come out to sync home page

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy. Was able to reproduce it twice

**Brave Version:** 
1.8(19.02.05.03)

**Device details:** 
iPhone 7+ (iOS 12.1)
BC on Linux running 0.59.35

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by btlechowski** [comment]
* Verified passed with 1.9 (19.3.9.1) on iPhone SE using the test plan from description. After removing iOS device. user is moved back to settings.
* Verified passed with 1.9 (19.3.9.1) on iPad 5th Gen using STR from description. After iOS was removed from sync chain, Settings was displayed.
* Verified passed with 1.9 (19.3.9.1) on iPhone using STR from the description. After iOS was removed from sync chain, Settings was displayed.
* Verification passed on iPad Pro/iPhone 6/7+ running 1.9(19.3.9.1)
* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR. After iOS was removed from sync chain, Settings was displayed.
