### ISSUE TITLE
Tokens gets listed as NFT when hiding/unhiding NFTs

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#8463]
### Description: 
Tokens gets listed as NFT when hiding/unhiding NFTs

### Steps to Reproduce 
  1. Import wallet with NFTs
  2. Add a couple of NFTs that you don't own
  3. Hide/Unhide, sort by Network and save settings
  4. Native Tokens gets listed as NFTs

### Actual result: 

https://github.com/brave/brave-ios/assets/17010094/83258a22-488d-4f31-aa2c-e827cb251c03

### Expected result:
Should not show Native tokens as NFTs

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Intermittent

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? NA

### Device details: 
iPhone 13 (iOS 17.2)

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by kjozwiak** [comment]
@iccub @StephenHeaps after chatting with @srirambv, we should probably get this one fixed in `1.60.x` if possible.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.2 running 1.60 (23.11.23.16)
- Verified steps from issue description and [#8470](https://github.com/brave/brave-ios/pull/8470)
- Verified native tokens are not shown when hiding/unhiding NFTs


https://github.com/brave/brave-ios/assets/17010094/74cf033c-2750-450e-bdd1-7146d5be9e57
