### ISSUE TITLE
[Follow up to #8421] Toolbar could still get swapped in certain scenarios and iPad toolbar isnt showing all toolbar items

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#8475]
### Steps to Reproduce 

iPad UI bug:
  1. Launch on iPad in full screen
  2. Verify navigation buttons/menu buttons are visible instead of missing

iPhone toolbar swap bug:
  1. Open tab tray
  2. Move to landscape
  3. Leave tab tray
  4. Verify your toolbar is at the top of the screen in landscape mode

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` and `iPad (7th Gen)` running `iOS 17.1.1` and `iPadOS 17.0` respectively using version `1.60 (23.11.24.16)`

- Ensured toolbar does not change to landscape using STR in https://github.com/brave/brave-ios/issues/8475#issue-2008825868
- Ensured UI elements are not missing on iPad. 

https://github.com/brave/brave-ios/assets/17885425/ad0824df-a8c1-4e32-85f6-01535c7773b4
