### ISSUE TITLE
[Playlist]Different video is added to playlist on twitter.com

### ISSUE THREAD

**Issue by A-t-s-u-s-h-i** [brave/brave-ios#8479]
### Description: 
Different video is added to playlist when I try to add playlist video on twitter.com

### Steps to Reproduce 
  1. Showing(Playing) video on twitter.com
  2. Tap [♪+] icon in address bar
 
### Actual result: 
I saw 2 cases of result

a) On twitter video, related video would be shown after swiping down the display. In most case, this related video is added to playlist

b) Something is added to playlist, but it can't be played

So, it seems like that if playlist is able to fetch the related video, it would be added. If it isn't, broken data would be added.

https://github.com/brave/brave-ios/assets/79502386/d02f1add-b66f-4397-b0c2-b62e657dddc2

### Expected result:
The video that user is operating is added to playlist

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
Yes

- Can you reproduce this issue with the previous version of the current build from TestFlight? 
On the previous version, cannot add playlist video because of another issue.

- Can you reproduce this issue with the current build from AppStore? 
Yes

### Device details: 
iPhone13 Pro/iOS17.1.1

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.61 (23.12.11.17)`

- Ensured that correct video is added to playlist on twitter.com when using icon in the address bar. 
- Ensured video can be opened and played in playlist after adding. 

Example | Example
-|-
![IMG_3659](https://github.com/brave/brave-ios/assets/17885425/388e79eb-3675-4ec2-a323-4b9421e156a6) | ![IMG_3660](https://github.com/brave/brave-ios/assets/17885425/f37d8533-4ecb-4c20-af49-23c970dab762)
