### ISSUE TITLE
Sync chain creator gets listed twice on the second device

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#848]
### Description: 
Sync chain creator gets listed twice on the second device

### Steps to Reproduce 
  1. Create sync chain on device 1
  2. Scan QR code on device 2
  3. Device 1 gets listed twice on device 2

**Actual result:** 
![file 2](https://user-images.githubusercontent.com/17010094/52270156-19564d00-2966-11e9-9caa-423dbfbdeea7.jpg)
![file 3](https://user-images.githubusercontent.com/17010094/52270160-1b201080-2966-11e9-8967-ae5efce3e0c6.jpg)

**Expected result:**
Should only list the device once

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Device details:** 
Device 1: iPad Pro (iOS 12.1.2) running 1.8(19.2.5.3) - Sync chain creator
Device 2: iPhone 7+ (iOS 12.1.2) running 1.8(19.2.5.3) 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by LaurenWags** [comment]
* Verified passed with 1.9 (19.3.9.1) on iPhone 8 using STR above
* Verification passed on iPad Pro/iPhone 6/7+ running 1.9(19.3.9.1)
* Verified passed with 1.9 (19.3.9.1) on iPhone SE
* Verified passed with 1.9 (19.3.9.1) on iPhone 8
* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR.
