### ISSUE TITLE
Wallet: NFT Tab does not display correct NFTs after hide/unhide with slow connection

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#8481]
https://github.com/brave/brave-ios/assets/1187676/72bc9616-2db7-413a-ad40-097d5c65b59e

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.2 running 1.60 (23.11.27.16)
- Verified steps from [#8486](https://github.com/brave/brave-ios/pull/8486)
- Verified moving NFTs into hidden state before image metadata is fetched, continues to show in hidden tab along with Junk NFTs

https://github.com/brave/brave-ios/assets/17010094/051c0f9e-14a8-4202-9e5d-9d174f62e684
