### ISSUE TITLE
Portrait Orientation Locking on Phone is not working

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#8484]
### Description: 

The orientation lock is not working properly for sync screens related with API change in iOS16.

Also related with https://github.com/brave/brave-ios/issues/6275

### Steps to Reproduce 

1. Fresh profile
2. Open tab tray, select tabs from other devices segmented tab
3. Rotate device to landscape
4. Tap on Start a sync chain
5. Sync modal will display in landscape
6. Select Select the Tablet or Phone option
7. Observe
8. Delete sync chain
9. Repeat steps.. this time choose I have a sync code
10. Notice the scan modal in landscape is not displayed correctly

### Actual result: 

The screen in landscape is not displayed **correctly**

### Expected result:
The portrait display lock should work properly

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
iPhone iOS 16- 17

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information

Additionally same flow should be tested for Settings -> Sync screens

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.61 (23.12.7.20)`

- Verified STR in https://github.com/brave/brave-ios/issues/8484#issue-2010250540 and ensured portrait orientation locking is working in the sync flow. 

<table><tr><td>1.60</td><td>1.61</td></tr>

<tr><td>

https://github.com/brave/brave-ios/assets/17885425/e383c5dd-dcc1-4697-aa65-e61fa5201c6e

</td><td>

https://github.com/brave/brave-ios/assets/17885425/831b488a-5b37-4163-a571-e4b86894a7fb

</td></tr></table>
