### ISSUE TITLE
iPad Slide-Over cannot click links

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8489]
### Description: 
- When in slide-over mode, some links on some pages cannot be clicked/tapped.
- When in slide-over mode, all pages are rendering with the Desktop User-Agent even if the webView is very very small. This can cause accessibility issues. Safari detects the size-class and determines which UA to use:

Brave:
[![image](https://github.com/brave/brave-ios/assets/1530031/04d0b09d-6631-4d45-8cee-93ce9c938e6c)](https://files.slack.com/files-pri/T04PX1BU8-F067D00CMSR/image.png)

Safari: 
![image](https://github.com/brave/brave-ios/assets/1530031/10ce05f4-0e69-4748-bb69-51d860c82621)

### Steps to Reproduce 
  1. Open Safari
  2. Open Brave
  3. Tap the three-dot menu at the top of the screen
  4. Enter "Slide-Over" mode with Brave on Top and Safari below (Stage Manager)

### Actual result: 
- Brave renders the page extremely small (Desktop mode in a mobile form-factor) even after refreshing

### Expected result:
- Brave should render the mobile site

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily reproduced

### Brave Version: 
- All versions

### Device details: 
- iPad only

**Comment by hffvld** [comment]
Verified on `iPad Air` using version(s):
```
Device/OS: iPad Air / iPadOS 16.7.2
Brave build: 1.61 (23.12.11.17)
BraveCore: 1.61.102 (120.0.6099.71)
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-ios/issues/8489#issue-2012802787

**ACTUAL RESULTS:**
- Verified that Brave is rendering the pages in `Mobile` view when in `Slide Over` mode
- Verified that the results are matching the same from Safari

---------------------------

|Safari|Brave|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/d593891e-95bb-4915-be76-417ff225df68)) | ![2](https://github.com/brave/brave-ios/assets/128532965/df0eef94-5441-42ab-a5fb-8e9515bff308) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/50da6aae-537f-46ba-83e3-be41e70138d2) | ![2](https://github.com/brave/brave-ios/assets/128532965/82650760-a4a3-46bb-a359-92bb8d01c916) |
