### ISSUE TITLE
Reset and resync still shows the older device name from previous sync

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#849]
### Description: 
Reset and resync still shows the older device name from previous sync

### Steps to Reproduce 
  1. Create a sync chain on device 1
  2. Add device 2 to the chain by scanning the QR code
  3. Reset sync on device 2
  4. Reset sync on device 1 as well
  5. Recreate sync on device 1, shows device 2 in the devices list

**Actual result:** 
Reset and resync still shows the older device name from previous sync

**Expected result:**
Reset and resync shouldn't show the older device from previous sync

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.8(19.2.5.3)

**Device details:** 
Device 1: iPad Pro (iOS 12.1.2)
Device 2: iPhone 7+ (iOS 12.1.2)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
By `3. Reset sync on device 2` you mean removing itself from the sync chain?
I can't reproduce it on my development build

**Comment by srirambv** [comment]
Yes that is correct. Since its able to retain sync chain when the other device removes itself.

**Comment by LaurenWags** [comment]
* Verified passed with 1.9 (19.3.9.1) on iPad 5th Gen using STR above
* Verification passed on iPad Pro/iPhone 6/iPhone 7+ running 1.9(19.3.9.1)
* Verified passed with 1.9 (19.3.9.1) on iPhone SE
* Verified passed with 1.9 (19.3.9.1) on iPhone 8
* Verification **PASSED** with `1.9 (19.3.27.19)` on `iPad Mini 4` using the above STR.
