### ISSUE TITLE
Privacy Hub hide action approval alert

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#8493]
## Problem Description 

Privacy Hub hide feature can lead to users to lead losing the UI for the feature because the settings for NTP is deep inside the settings. 

I believe this is important especially we want to refactor and make a new User Interface for Privacy Hub.

Some reports related with this 
https://appfigures.com/reviews/42132121512LypxXs8QE7k7HeCXIbzFYGw?lang=en

<img width="310" alt="Screenshot 2023-11-28 at 2 32 01 PM" src="https://github.com/brave/brave-ios/assets/6643505/ad5ac919-66ed-4753-b1d9-feaebbfeb210">

## Feature Overview 

When the Hide action is activated `first time`, it should show a dialog (an alert) asking user if they are sure about the action and the dialog should indicate where they can turn it back on or change settings for NTP.

## Design 

This is the actual representation for hiding the Privacy Hub. The suggested action will show an alert when action is triggered. Please check the video to understand the source of the issue mentioned.

https://github.com/brave/brave-ios/assets/6643505/f3058a84-d50a-4c8f-a05d-8e7c204f22be

And the suggested action

https://github.com/brave/brave-ios/assets/6643505/16ec533d-6c09-413b-981e-40ddfa1cbe03

## Implementation Details 

An Alert should be displayed after triggering Hide Privacy Hub action which should include information about where visibility settings are and in addition to approve and cancel buttons.

## User Experience 

1. Press 3 dot on corner of Privacy Hub
2. Press Hide Privacy Hub 
3. An alert should be shown
4. Press OK and check privacy Hub is hidden after pressing approve action

### Additional information 

The alert should be displayed only first time when user pressed Hide Privacy Hub action to inform user about consequences of teh actions. And how to revert them.

**Comment by anthonypkeane** [comment]
Title: Hide Privacy Stats
Description: Tap Hide to remove the Privacy Stats widget. You can always re-enable in Settings, under New Tab Page
CTA: Cancel | Hide

cc @soner-yuksel

**Comment by Uni-verse** [comment]
Verified on `iPhone 12 Pro` running `iOS 17.1.1` using version `1.62 (24.1.9.23)`

- Verified alert is shown when trying to hide Privacy Hub the first time on fresh and existing profiles. 
- Verified that Privacy Hub is displayed again when enabling `Privacy Hub` in the `New Tab Page` settings.
- Verified alert is not shown the second time user selects option to hide.
- Verified alert will be shown again if user dismisses the message with `Cancel` button.

Example | Example | Example
-|-|-
![IMG_5551](https://github.com/brave/brave-ios/assets/17885425/6947cfb9-90d4-4eb5-9055-9b6cc8428720) | ![IMG_5552](https://github.com/brave/brave-ios/assets/17885425/e72c9ce0-9c74-464d-a43d-2c3920ffa009) | ![IMG_5553](https://github.com/brave/brave-ios/assets/17885425/cedf4b50-6407-4c07-9e7a-0035b94397c4)
