### ISSUE TITLE
links not opening third party apps when `target=blank/open in new tab`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#8494]
### Description: 

As originally reported via https://x.com/StrawberrySith/status/1729823719030202673, AppStore links using `target=blank/open in new tab` are not opening/working as expected. Looks like it's generally working now that we've fixed https://github.com/brave/brave-ios/issues/8383.

### Steps to Reproduce 

  1. open https://connect.causality.xyz and attempt tapping/opening the `App Store` link

For context/information can be found via https://x.com/StrawberrySith/status/1729823719030202673 as mentioned above.

### Actual result: 

Tapping on the `App Store` link doesn't do anything.

### Expected result:

Tapping on the `App Store` link should produce the modal re: opening the link in another application (in this case the App Store)

### Reproduces how often: [Easily reproduced, Intermittent Issue]

100% reproducible using the STR/Cases outlined above.

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? `Yes`
- Can you reproduce this issue with the previous version of the current build from TestFlight? `Yes`
- Can you reproduce this issue with the current build from AppStore? `Yes

### Device details: 

* `iPhone 11` running `iOS 17.1.1` - **Reproduced**

### Website problems only:
- did you check with Brave Shields down? `N/A`
- did you check in Safari/Firefox (WkWebView-based browsers)? `N/A`

**Comment by soner-yuksel** [comment]
This ticket should be tested along with the ticket https://github.com/brave/brave-ios/issues/7835 which is reopened.

**Comment by hffvld** [comment]
Verified on `iPhone 14`using version(s):
```
Device/OS: iPhone 14 / iOS 17.2
Brave build: 1.61 (23.12.11.17)
BraveCore: 1.61.102 (120.0.6099.71)
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-ios/issues/8494#issue-2016705307

**ACTUAL RESULTS:**
- Verified that `App store` is opened when tapping `App Store` link in Brave while on https://connect.causality.xyz/

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/024a32bb-7559-4db6-b184-73cd96a573b8) | ![2](https://github.com/brave/brave-ios/assets/128532965/08d42c91-121d-42a3-8336-ce3c606b3957) | ![3](https://github.com/brave/brave-ios/assets/128532965/1a612bbe-b2dc-43f5-822b-4d70f1385e1a) |
