### ISSUE TITLE
Long press on a link sometimes opens a different link.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#850]
### Steps to Reproduce 
  1. Long press on a link

**Actual result:** 
Sometimes it navigates to wrong link.

**Expected result:**
Should navigate to correct website.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Not easy to reproduce. That's why I'm setting QA to `NO`

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
Let's research this one a bit, and see if we can identify what exactly is going on, we'll then prioritize it for development.
