### ISSUE TITLE
Fix Brave Logo usages in widgets in dark mode

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#8502]
### Description: 

The top news list widgets and top news lock screen widget use an inversed monochrome brave logo which is the wrong usage of the logo

![img_0061](https://github.com/brave/brave-ios/assets/529104/b7329919-5c34-4489-996f-e2000576eacf)

<img width="377" alt="image" src="https://github.com/brave/brave-ios/assets/529104/b30e13e0-00cc-46c7-b073-555d89af3d1e">

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.2
Brave build: 1.61 (23.12.7.20)
BraveCore: 1.61.101 (120.0.6099.71)
```
---------------------------

<details>
<summary> Fresh install </summary>

**STEPS:**
1. Fresh install Brave
2. Go to the device home screen > Add shortcut
3. Add Brave News shortcuts > Verify

**ACTUAL RESULTS:**
- Verified that `Brave logo` has proper color on all widgets
- Verified the same in the `Light` and `Dark` mode

---------------------------

|Light Mode|Dark Mode|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/9cb0d9f3-3675-4b00-9328-e536541738eb) | ![2](https://github.com/brave/brave-ios/assets/128532965/abe66842-a3e1-4bdd-99bf-d45ae4e362a3) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/ae92810e-239c-40db-a2c1-03ade0223170) | ![2](https://github.com/brave/brave-ios/assets/128532965/6d315006-410c-491a-93aa-b183ec07e19b) |

</details>

<details>
<summary>Upgrade install </summary>

**STEPS:**
1. Install Brave `1.60`
2. Go to the device home screen > Add shortcut
3. Add Brave News shortcuts > Observe the issue with the `News` widget
4. Upgrade Brave to `1.61` build > Verify

**ACTUAL RESULTS:**
- Verified that `Brave logo` has proper color on all widgets
- Verified the same in the `Light` and `Dark` mode

---------------------------

|Light Mode `1.60`|Light Mode `1.61`|Dark Mode `1.60`|Dark Mode `1.61`|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/23dfaf9e-5c2d-4069-ab59-c968178d5164) | ![2](https://github.com/brave/brave-ios/assets/128532965/ef7a7dfa-eee3-4df4-9ad7-2f47cd35fde8) | ![3](https://github.com/brave/brave-ios/assets/128532965/ae0e0dcb-5a3b-4dfd-aafc-ba674e398db1) | ![4](https://github.com/brave/brave-ios/assets/128532965/bb590686-034b-46da-b9c1-ac227353a406) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/5dccb8ed-2c4f-4d22-b1ba-c246e0e08c5e) | ![2](https://github.com/brave/brave-ios/assets/128532965/f6d1b139-02a1-4728-bdb4-72da84920b12) | ![3](https://github.com/brave/brave-ios/assets/128532965/b999529b-0fdf-484d-aaff-92b6a61aeb9c) | ![4](https://github.com/brave/brave-ios/assets/128532965/34323f1c-9fd7-4def-98ae-43f63a7718ff) |

</details>
