### ISSUE TITLE
Display title tag when long-pressing on image

### ISSUE THREAD

**Issue by murphyd** [brave/brave-ios#851]
### Description: 
When long-pressing on an image, it shows the image URL but no title text. Could this show the title text like Safari does?

Sites such as XKCD.com have title tags on images and are only available by long-pressing the image in Safari.

### Steps to Reproduce 
  1. Go to XKCD.com
  2. Long press on the comic picture until it prompts you to Open Image In New Tab / Save Image / Copy Image.
  3. At the top, you'll see a path to the image, but not the title text. 
  4. Compare this with Safari by following steps 1-3 above. You'll see Safari shows the text in the title tag.

**Actual result:** 
First picture: Brave. Second picture: Safari.
![image](https://user-images.githubusercontent.com/4502617/52278944-50a50980-2926-11e9-9303-42a2dea2b7d5.png)
![image](https://user-images.githubusercontent.com/4502617/52278967-661a3380-2926-11e9-9fc6-b68738829c02.png)

**Expected result:**
No expected result. 

**Reproduces how often:** 
100% of the time.

**Brave Version:**
iOS 1.7.4.

**Device details:** 
iPhone XS, iOS 12.1.3

**Comment by LaurenWags** [comment]
* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.12.14)

![IMG_0316](https://user-images.githubusercontent.com/28145373/61155737-99598380-a4bf-11e9-9222-79da9c7cefc5.PNG)

* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`

![IMG_9765](https://user-images.githubusercontent.com/2602313/61388120-662f3f80-a885-11e9-8c9b-28836b5aed47.PNG)

![IMG_9764](https://user-images.githubusercontent.com/2602313/61388122-662f3f80-a885-11e9-88a1-da0ea79f9d09.PNG)

- Verification passed on iPhone 8 running iOS 12.3.1 using 1.10(19.07.16.23)
![IMG_0070](https://user-images.githubusercontent.com/38657976/61392395-5131cb00-a8dc-11e9-81fc-4e1d609beb17.PNG)
![IMG_0071](https://user-images.githubusercontent.com/38657976/61392408-568f1580-a8dc-11e9-81f3-32296820027f.PNG)
![IMG_0072](https://user-images.githubusercontent.com/38657976/61392412-5a229c80-a8dc-11e9-8ce3-e3f4c6237955.PNG)
