### ISSUE TITLE
Update SNS interstitial page copy for new provider

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8515]
## Description 

Update the copy for the SNS interstitial page for change of provider.

More info:

https://github.com/brave/devops/issues/10126#issuecomment-1830367288

https://bravesoftware.slack.com/archives/C023VS4HJ6Q/p1701455844311989

iOS version of https://github.com/brave/brave-browser/issues/34700

**Comment by StephenHeaps** [comment]
`wallet/sns-copy` branch is ready once we have wiki link for SNS privacy policy/terms:
https://github.com/brave/brave-ios/compare/wallet/sns-copy

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.3 running 1.61 (23.12.18.22)
- Verified steps from [ #8553](https://github.com/brave/brave-ios/pull/8553)
- Verified setting `Resolve Solana Name Service(SNS) Domain Names` to`Ask` and visiting `onybose.sol` brings up the new interstitial page
- Verified changing setting to `Disabled`, doesn't bring up the interstitial page
- Verified `help page` loads `https://github.com/brave/brave-browser/wiki/Resolve-Methods-for-Solana-Name-Service`
- Verified clicking `Disable` in the interstitial page, disables the setting
- Verified clicking `Proceed using an SNS server` loads the page correctly

https://github.com/brave/brave-ios/assets/17010094/8a0608b1-d526-42cd-b5ee-6febfd8bf33e
