### ISSUE TITLE
Add Open in Brave to iOS Share Sheet Action (Action Extension)

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#8516]
## Problem Description 

 Brave Browser should appear in OS default Share Sheet for URL related actions. This will provide extra visibility and easy access to Brave users on iOS thorough other applications while using the Share Sheet. 

## Feature Overview 

Adding Brave as Action Extension on iOS will add `Open in Brave` action to default share sheet. So Brave can be reached outside the application environment. It will also help for users having multiple browsers and want to use Brave for certain actions or links.

![1](https://github.com/brave/brave-ios/assets/6643505/c8d81a29-cd00-4e50-85de-a330f2e23e40)

## Design 

There is no design choice to be made here but it will look like the actions shown in he example

## Implementation Details 

Action extensions are displayed in the action view controller, accessed by users when they tap the Share button within an active application. These extensions are situated in the action section of this panel, alongside default actions like printing and copying content.

When an Action extension is developed, it needs to specify the content types it is capable of handling.

For Brave's case this should be 

NSExtensionActivationSupportsText
NSExtensionActivationSupportsWebPageWithMaxCount
NSExtensionActivationSupportsWebURLWithMaxCount

- An action extension target should be added
- Display Name of Extension should be changed
- ActionViewController should be implemented with item provider conforming identifier type and load

## User Experience 

1. Open any app and share url or text
2. Check share sheet has open in brave action
3. this share functionality should search the text in brave or open link

### Additional information 

It needs be tested and implemented to see if this behaviour could be possible to detect it is a text or link and do desired action according to it.

**Comment by kylehickinson** [comment]
How is this different than the Open in Brave share extension we already have? Is it just so there's another option?

**Comment by soner-yuksel** [comment]
Pretty much **yes**, so as far as I understood share extension covers the top section with coloured app actions and no action text.

But this action extension actually adds it to the list in bottom section with monochromatic icon and we can define a localizable text to the action that will be performed. It is much more visible and we can actually add different types of actions here. (Not just opening links maybe)

**Comment by anthonypkeane** [comment]
In terms of text, 

**Open in Brave** should easily fix in english and other languages 

Open in Brave Browser is better but it is prod too long.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.3.1` using version `1.63 (161)`

- Ensured `Open in Brave` is shown in the share sheet on fresh install and upgraded profile.
- Ensured opening links outside of Brave with the share sheet works.
- Ensured opening links from Safari works with the share sheet. 
- Ensured `Allow universal links to open in external apps` works as expected when opening links within Brave. 

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_5740](https://github.com/brave/brave-ios/assets/17885425/d370c84c-7ad9-4746-8d1d-727825e03fb4) | ![IMG_5750](https://github.com/brave/brave-ios/assets/17885425/41730d66-93e2-4cc6-a1b9-1db3d9ad5b6c) | ![IMG_5741](https://github.com/brave/brave-ios/assets/17885425/829e7d76-8f0a-4ceb-bbc1-c7a4ebec0e14) | ![IMG_5742](https://github.com/brave/brave-ios/assets/17885425/ec712146-b840-4dcc-b695-878c8d927c83) | ![IMG_5743](https://github.com/brave/brave-ios/assets/17885425/3e8424ca-990d-4b60-9f5e-8c462bcae7cd)

**_Opening links with text_**

- Ensured opening sharing text with `Open in Brave` from the share sheet will place text in the URL. 

Example | Example
-|-
![IMG_5748](https://github.com/brave/brave-ios/assets/17885425/f438c332-005a-4ec2-8168-3669d779a40a) | ![IMG_5749](https://github.com/brave/brave-ios/assets/17885425/33c43dfe-c600-4b65-a23b-5f547037ef2c)
