### ISSUE TITLE
ASA Custom Onboarding Feature Linkage

### ISSUE THREAD

**Issue by timchilds** [brave/brave-ios#8521]
## Problem Description
We want to customize the onboarding experience for iOS users. Apple Search Ads is by far the best / easiest way to acquire iOS users. However it does not support deep links, which are usually required to customize the onboarding experience for users.

## Feature Overview
Spec: Apple Search Ads: Feature Linkage Google Docs

## Implementation Details
- See spec above.
- API calls must only occur when user has opted in to `share completely private and anonymous product insights`.

## User Experience
1. User searches "VPN" on app store.
2. User taps on one of Brave's ASA ads.
3. User is presented with VPN focused custom listing.
4. User installs.
5. User opens app and finishes general onboarding (taps continue on `Help make Brave better` screen)
6. User is presented with VPN Paywall.

_^^ in future the above could be for some other feature. e.g. Playlist, Leo, etc._

cc @soner-yuksel

**Comment by Uni-verse** [comment]
@Uni-verse QA to check feature once 1.62 is published to the app store.
