### ISSUE TITLE
Fetch unknown tokens for transactions on any EVM network(s)

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8529]
### Description: 

Currently we are using an Ethereum Mainnet only API to fetch unknown token symbol & decimals for Ethereum mainnet transactions. We can update to use `GetEthTokenSymbol` and `GetEthTokenDecimals` to fetch these values for any EVM network. We should update logic to support this for non-Mainnet transactions.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.4 running 1.62 (24.1.29.12)
- Verified steps from [#8530](https://github.com/brave/brave-ios/pull/8530)
- Verified token symbol and transaction value shows up as expect in Swap Confirmation, Activity tab, Tx details

![image](https://github.com/brave/brave-ios/assets/17010094/7b4a4de3-c716-48be-885c-3c2b3090b205) | ![image](https://github.com/brave/brave-ios/assets/17010094/64198698-cf94-4360-aa62-c9a2b4117f56) | ![image](https://github.com/brave/brave-ios/assets/17010094/b6bb690d-8f4c-4b17-af02-f3e12afd58c1)
-- | -- | --
![image](https://github.com/brave/brave-ios/assets/17010094/bd05c676-9c1a-4028-9edd-96a9e241aa71) | ![image](https://github.com/brave/brave-ios/assets/17010094/f3fc0531-c4a8-48f1-8d9a-d23aca0394a8) | ![image](https://github.com/brave/brave-ios/assets/17010094/37b80ad2-51ce-4454-b1a6-3c6e4bab50fb)
