### ISSUE TITLE
Bookmark scrolling is difficult when it just starts to overflow the view

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#853]
### Description: 
Bookmark scrolling is difficult when it just starts to overflow the view

### Steps to Reproduce 
  1. Import/add bookmarks just enough that it starts to overflow from the standard bookmark UI
  2. Try scrolling down to see the last bookmark
  3. Bookmark flyout window closes and doesn't scroll

**Actual result:** 
https://youtu.be/YWtllahiglg

**Expected result:**
Should be able to scroll through easily and not just close the flyout menu

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.8(19.2.5.3). Probably reproduces on the appstore build as well

**Device details:** 
iPhone 7+ (iOS 12.1.2)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
This is really annoying. This will be addressed when we dump this menu, so going to mark it as `won't have`, and this will be fixed when we rebuild the menus.
