### ISSUE TITLE
Toggling night mode auto-dismisses menu

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8535]
### Description: 

Tapping `Back` to get out of settings after enabling/disabling Night Mode toggle will automatically dismiss the app menu.

### Steps to Reproduce 
  1. Have >1 open tabs 
  2. Tap `...`, tap Settings, tap Appearance
  3. Toggle the night mode switch on or off.
  4. Tap back
  5. Tap back again
  6. Observe menu disappears on it's own.
  
  Alternative STR:
  1. Have >1 open tabs 
  2. Tap `...` and toggle night mode switch
  3. Observe menu disappears immediately

### Actual result: 

<video src="https://github.com/brave/brave-ios/assets/5314553/8242ffda-7c31-458d-9b60-62a5d5e09034"> |  <video src="https://github.com/brave/brave-ios/assets/5314553/b28319f2-f920-4edd-89a9-78c9504f90cd">
--|--

### Expected result:

Don't auto-dismiss menu

### Reproduces how often: 

Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

Requires a tab to be open to reproduce; likely related to site specific settings in the pan modal menu.

**Comment by soner-yuksel** [comment]
Alternative STR

- Have >1 open tabs
- Tap ... and toggle night mode switch
- Observe menu disappears immediately

is actually supposed to work this way. After toggling night mode from directly through 3 dot menu, the menu should disappear so it can act like a quick toggle.

But it is this part in the code causing the issue with main STR to reproduce.

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.3
Brave build: 1.62 (24.1.11.20)
BraveCore: 1.62.128 (120.0.6099.144)
```
---------------------------

**STEPS:**
  1. Launch Brave > Open 1 tab 
  2. Three-dot menu > Settings > Appearance
  3. Toggle the `Night Mode` switch On or Off
  4. Tap `Back` > Tap `Back` again > Verify

**ACTUAL RESULTS:**
- Verified that `Menu` doesn't disappear on its own

---------------------------

https://github.com/brave/brave-ios/assets/128532965/39ffc957-529a-46b4-9d27-929e2fd566aa
