### ISSUE TITLE
[Jitsi SDK] Brave is crashing when hanging up the call

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#8536]
### Description: 

Brave is crashing when hanging up the call.

### Steps to Reproduce 
  1. Launch Brave `0.0 (23.11.17.19)`
  2. Tree-dot menu > `Talk` > Start free call
  3. Join meeting > Tap the red button to hang up > Observe the crash

### Actual result: 

Brave is crashing when hanging up the call.

I checked Brave `1.61 (23.12.7.20)` and the issue is not reproducible there.

https://github.com/brave/brave-ios/assets/128532965/820cf8a6-b2cf-4c02-b845-216271258cd8

### Expected result:

Brave must not crash when hanging up the call.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

```
Brave build: 0.0 (23.11.17.19)
BraveCore: 1.61.69 (119.0.6045.124)
Jetsi SDK: 8.6.0
```

- Can you reproduce this issue with the most recent build from TestFlight? N/A
- Can you reproduce this issue with the previous version of the current build from TestFlight? N/A
- Can you reproduce this issue with the current build from AppStore? N/A

### Device details: 

Device/OS: iPhone 14 / iOS 17.2

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

Cross-referencing the same issue from `Jitsi` repo - https://github.com/jitsi/brave-tracker/issues/140

**Comment by soner-yuksel** [comment]
Closing this ticket since it is tracked in jitsi SDK
