### ISSUE TITLE
[Jitsi SDK] The `Enable lobby` toggle switch is jiggling when enabling or disabling it

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#8538]
### Description: 

The `Enable lobby` toggle switch is jiggling when enabling or disabling it.

### Steps to Reproduce 
  1. Launch Brave
  2. NTP > Three-dot menu > Talk > Start free call
  3. Join meeting > Three-dot menu
  4. Security options > `Enable` or `Disable` the toggle switch > Observe

### Actual result: 

The `Enable lobby` toggle switch is jiggling when enabling or disabling it.

|1|
|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/ec6fb64f-aa5e-44d3-bd45-e09f777e1b91) |

https://github.com/brave/brave-ios/assets/128532965/67f5da53-5853-43e8-8d37-5ae4b157737b

### Expected result:

The `Enable lobby` toggle switch must not jiggle when enabling or disabling it.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

```
Easily reproduced
```

### Brave Version: 

```
Brave build: 1.61 (23.12.7.20)
BraveCore: 1.61.101 (120.0.6099.71)
```
and 
```
Brave build: 0.0 (23.12.8.11)
BraveCore 1.61.101 (120.0.6099.71)
Jetsi SDK: 8.6.0
```

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? YES

### Device details: 

```
iPhone 14 / iOS 17.2
```

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

Cross-referencing the same issue from `Jitsi` repo - https://github.com/jitsi/brave-tracker/issues/141

**Comment by soner-yuksel** [comment]
Closing this ticket since it is tracked in jitsi SDK
