### ISSUE TITLE
[Jitsi SDK] The `Share` button is not working properly in the `Brave Talk` when trying to invite someone

### ISSUE THREAD

**Issue by hffvld** [brave/brave-ios#8539]
### Description: 

The `Share` button is not working in the `Brave Talk` when trying to invite someone.

### Steps to Reproduce 
  1. Launch Brave
  2. NTP > Three-dot menu > Talk > Start free call
  3. Join meeting > Tap the `People` icon in the top right corner to invite someone
  4. Tap `Invite Someone` > Tap `Share` button > Observe, that nothing is happening
  5. Enter phone number > Tap `Share` button > Observe, that nothing is happening

### Actual result: 

The `Share` button is not working as expected in the `Brave Talk` when trying to invite someone:
- When no phone number is entered or when the phone number is there, but not selected, nothing is happening if tapping the `Share` button.
- When the phone number is checked `✔️`, tapping the `Share` button (or `Send` button) starts a phone call.
- The`Share` button is located too low (too close to the `Gesture` bar).

|1|
|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/5663735e-92c2-4c2e-9891-0b5b74336748) |

https://github.com/brave/brave-ios/assets/128532965/dae80b02-b1d9-47c9-b31e-cdb4d4e07bae

### Expected result:

The `Share` button must work as expected.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced

### Brave Version: 

```
Brave build: 1.61 (23.12.7.20)
BraveCore: 1.61.101 (120.0.6099.71)
```
and
```
Brave build: 0.0 (23.12.8.11)
BraveCore 1.61.101 (120.0.6099.71)
Jetsi SDK: 8.6.0
```

- Can you reproduce this issue with the most recent build from TestFlight? YES
- Can you reproduce this issue with the previous version of the current build from TestFlight? YES
- Can you reproduce this issue with the current build from AppStore? YES

### Device details: 

```
Device/OS: iPhone 14 / iOS 17.2
```

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information

Cross-referencing the same issue from `Jitsi` repo - https://github.com/jitsi/brave-tracker/issues/142

**Comment by soner-yuksel** [comment]
Closing this ticket since it is tracked in jitsi SDK
