### ISSUE TITLE
[Bug] - Joining a Sync chain on iOS Crashes with Cr-120 (Nightly)

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8540]
### Description: 
https://github.com/brave/brave-browser/issues/34804

### Steps to Reproduce 
  1. Create a Sync Chain on Desktop Cr-120 (Nightly)
  2. Join the sync chain from iOS Cr-120 build

### Actual result: 
- Crash

### Expected result:
- Should not Crash

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily Reproduced

### Brave Version: 
- Cr-120 (1.62.85+)

### Device details: 
- Any

**Comment by iccub** [comment]
this is fixed on `release`/1.61 branch and can be tested there.
we are going to uplift to 1.62 as well

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.61 (23.12.13.17)`
 

**_1.61 - Fresh Profile_**

1. Create sync chain on desktop (Nightly) 1.63.41
2. Join sync chain on iPhone device 1.61 (23.12.13.17)

- Ensured joining sync from from sync menu and also using segmented tab flow is successful.
- Ensured browser does not crash when joining sync chain.  

Example | Example
-|-
<img width="250" alt="0" src="https://github.com/brave/brave-ios/assets/17885425/c86e31cd-1758-4170-a9dc-4428d23daf67"> | ![Screenshot 2023-12-14 at 4 43 34 PM](https://github.com/brave/brave-ios/assets/17885425/4da60969-f8da-4639-8185-e82c5a9e107b)


**_1.61 - Upgraded Profile_**

1. Create sync chain on desktop (Nightly) 1.63.41
2. Fresh install 1.60.x on iPhone device
3. Update to 1.61.x
4. Join sync chain on iPhone device

- Ensured joining sync from from sync menu and also using segmented tab flow is successful.
- Ensured browser does not crash when joining sync chain.
