### ISSUE TITLE
add GPC for iOS

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-ios#8556]
for parity with https://github.com/brave/brave-browser/issues/32231

**Comment by anthonypkeane** [comment]
@iccub Lets try get this into 1.62

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.3
Brave build: 1.62 (24.1.9.23)
BraveCore: 1.62.128 (120.0.6099.144)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Three-dot menu > Settings > Brave Shields & Privacy
3. Find `Enable Global Privacy Control` > Verify
4. Close the settings and go to any website, for example, Wikipedia
5. In Safari on the Desktop open `Web Inspector` > Console
6. Paste the query `navigator.globalPrivacyControl` > Enter > Verify the response result
7. Now disable `Enable Global Privacy Control` in Brave settings > Refresh the opened webpage
8. In the Console paste the query `navigator.globalPrivacyControl` again > Enter > Verify the response result
9. Now go to https://global-privacy-control.glitch.me/ which was used to verify the same issue on Desktop and Android
10. Check the `Client-side detection` section when `Enable Global Privacy Control` is ON > Verify
11. Now disable `Enable Global Privacy Control` > Refresh the page https://global-privacy-control.glitch.me/ > Verify

**ACTUAL RESULTS:**
- Verified that `Enable Global Privacy Control` is enabled by default
- Verified that in the Console:
  - `navigator.globalPrivacyControl` shows `true` when `Enable Global Privacy Control` is ON
  - `navigator.globalPrivacyControl` shows `false` when `Enable Global Privacy Control` is OFF
- Verified that https://global-privacy-control.glitch.me/ shows the correct results:
  - When `Enable Global Privacy Control` is ON, `Client-side detection` shows `navigator.globalPrivacyControl: true`
  - When `Enable Global Privacy Control` is OFF, `Client-side detection` shows `navigator.globalPrivacyControl: false`

---------------------------

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/0af607a4-62e8-4d13-b9d3-279ac514c0d2) | ![2](https://github.com/brave/brave-ios/assets/128532965/9c235402-8786-440f-bea9-e28875bf382a) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/072faee3-4072-454a-99bb-3f8d0f9e2e39) | ![2](https://github.com/brave/brave-ios/assets/128532965/5ce96d62-232c-429e-85cd-3854a4dcdd0f) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/924bba47-64bc-4384-b25d-e0f168885b51) | ![2](https://github.com/brave/brave-ios/assets/128532965/b2f89f31-7a9b-404d-9ae0-83bcf27380bf) |
