### ISSUE TITLE
Wallet: Update NFT balance cache after user made a NFT transaction

### ISSUE THREAD

**Issue by nuo-xu** [brave/brave-ios#8558]
NFTs balances are cached in Portfolio to increase the performance. 
But currently the cache is not updated correctly after user made a NFT transaction. 
This will cause NFT tab to display incorrect NFTs when it's grouped by `Account` or `Hide Unowned` is toggled on.

**Comment by srirambv** [comment]
Verified as part of https://github.com/brave/brave-ios/issues/8560#issuecomment-1920959806
