### ISSUE TITLE
Add "Review Brave" Option in Settings

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#856]
### Description: 

Add a "Review Brave" option in settings that utilizes `SKStoreReviewController` and presents a review prompt to the user.

This should go _above_ "Report a bug" under the "Support" column.

**Comment by LaurenWags** [comment]
When I tap on 'Rate Brave', Safari opens and then I get a popup that says 'Open in "App Store"?'. Is this expected? 

![IMG_E6B32A03BB8B-1](https://user-images.githubusercontent.com/28145373/54375854-344c6900-4658-11e9-9f23-1edd096b03d1.jpeg)

**Comment by cndouglas** [comment]
@LaurenWags No, it should go directly to the App Store.

Looks like the deep link URL is incorrect. I'll fix it.

**Comment by LaurenWags** [comment]
thanks @Liunkae - reopening this issue.

**Comment by cndouglas** [comment]
URL fixed by this PR: #972

**Comment by srirambv** [comment]
* Verification passed on iPad Pro/iPhone 6/iPhone 7+ running 1.9(19.3.9.1) for the option being available in setting. 
* Verified passed with 1.9 (19.3.9.1) on iPhone SE. Reproduced #972.
* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR.

@LaurenWags could you please log a new issue for https://github.com/brave/brave-ios/issues/856#issuecomment-472961020 which @Liunkae  can refer it in #972

**Comment by LaurenWags** [comment]
@srirambv logged https://github.com/brave/brave-ios/issues/989

**Comment by kjozwiak** [comment]
> This should go above "Report a bug" under the "Support" column.

Noticed that the `Rate Brave` menu item is **BELOW** `Report a bug` and not **ABOVE** it.  @jhreis is this an issue? From the sounds of the original comment, it should be the first item under `Support`. Example using `1.9 (19.03.25.21)`:

![IMG_1A6862C635E9-1](https://user-images.githubusercontent.com/2602313/55054861-984b3600-5037-11e9-8dbc-d0322e908e54.jpeg)

CCing @srirambv

**Comment by cndouglas** [comment]
@kjozwiak See @jhreis's comment: https://github.com/brave/brave-ios/pull/873#issuecomment-469384058

**Comment by kjozwiak** [comment]
@Liunkae perfect 👍 Much appreciated.
