### ISSUE TITLE
Endless page reload on brave.search news

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#8561]
### Description: 
Endless refresh is caused by endlessly setting `image.src = ""`

### Steps to Reproduce 
  1. Enable shields
  2. Go to https://search.brave.com/news?q=test
  3. Scroll down

### Actual result: 
Page refreshes

### Expected result:
Page should not refresh

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced (note: search team might fix the issue on their end rendering this unreproducible)

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.2
Brave build: 1.60.1 (23.12.15.0)
BraveCore: 1.60.122 (119.0.6045.163)
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-ios/issues/8561#issue-2042015845

**ACTUAL RESULTS:**
- Verified that there is no problem while scrolling

---------------------------

https://github.com/brave/brave-ios/assets/128532965/7ad2af7d-d5a3-46d6-8ea6-ce85e04ed4cd
