### ISSUE TITLE
Update tracking protection script from upstream

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#8562]
https://github.com/mozilla-mobile/firefox-ios/blob/main/Client/ContentBlocker/TrackingProtectionStats.js

Test plan:
Sanity test shields stats tracking, make sure they still count blocked ads

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.62 (24.1.25.17)`

- Ensured Shields stats tracking is showing count for blocked ads / trackers in Panel
- Ensured Privacy Hub shows ad-block data from websites
- Ensured stats are updated for blocked ads in Shields panel in regular and private tabs.
- Ensured disabling all blocking from Shields panel updates the stats/count accordingly.
- Ensured stats are updated when using normal as well as aggressive mode. 

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_3698](https://github.com/brave/brave-ios/assets/17885425/bfcde37d-44c2-40d6-bc30-b0ffd3c8df89) | ![IMG_3699](https://github.com/brave/brave-ios/assets/17885425/35411faf-80d5-4c7b-b234-ac18198dc12a) | ![IMG_3701](https://github.com/brave/brave-ios/assets/17885425/246cb56b-1605-4dce-985a-f3f5e29ad6d4) | ![IMG_3702](https://github.com/brave/brave-ios/assets/17885425/4d6dde27-bfba-44be-83fc-6d17285d6d52) | ![IMG_3703](https://github.com/brave/brave-ios/assets/17885425/49b203fa-a7ae-431d-9c2d-10f2553d0bd1)
