### ISSUE TITLE
Remove screentime

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#8566]

**Comment by Uni-verse** [comment]
Verified on `iPhone X` and `iPad (7th Gen)` running `iOS 16.7` and `iPadOS 17.0` respectively using version `1.60.1 (23.12.15.0)`

- Ensured that `Screen Time` setting is removed.
- Ensured that websites within brave cannot be time restricted in normal and private modes. 
- Ensured that Brave app can still have time restrictions.

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_3681](https://github.com/brave/brave-ios/assets/17885425/eed3a2b8-9eaa-41ee-853f-a4ca7aa57556) | ![IMG_3682](https://github.com/brave/brave-ios/assets/17885425/a7f4f5d9-0301-4d80-9adc-ec55d16dc62b) | ![IMG_3683](https://github.com/brave/brave-ios/assets/17885425/bd0695da-b701-4143-bafb-c3e3c756b4ce) | ![IMG_3684](https://github.com/brave/brave-ios/assets/17885425/8c13dde1-1b38-418e-8430-9843ad945ad0) | ![IMG_3685](https://github.com/brave/brave-ios/assets/17885425/c6852ceb-beba-4836-9e13-72ec698840b2)

Example | Example | Example
-|-|-
![IMG_1263](https://github.com/brave/brave-ios/assets/17885425/758c963e-b904-43cd-bc1d-34bbcb61bb7f) | ![IMG_1265](https://github.com/brave/brave-ios/assets/17885425/c4cfc5c4-dac8-48b6-9f10-dfb9246643a2) | ![IMG_1266](https://github.com/brave/brave-ios/assets/17885425/fcb74fa5-b05b-44f3-aac4-267e2b20ebcb)

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.1.1` using version `1.60.1 (23.12.15.0)`

- Ensured that Screen Time is removed from settings. 
- Ensured that URLs are not time restricted in Brave. 

Example | Example | Example
-|-|-
![IMG_5412](https://github.com/brave/brave-ios/assets/17885425/c5cddcc1-0e2a-4989-bb92-70d84304e019) | ![IMG_5413](https://github.com/brave/brave-ios/assets/17885425/4ee1e998-d8a7-4eaa-b151-c025d70fcd5a) | ![IMG_5414](https://github.com/brave/brave-ios/assets/17885425/c375a814-3d21-4f5b-a32e-53d1f0880147)

**Comment by Uni-verse** [comment]
Verified on `iPhone XR` running `iOS 15.5` using version `1.60.1 (23.12.15.0)`

- Ensured that Screen Time is removed from settings.
- Ensured that URLs are not time restricted in Brave. 

Example | Example | Example 
-|-|-
![IMG_0364 2](https://github.com/brave/brave-ios/assets/17885425/351a25b9-c0c0-4171-929e-26a6ccbf0601) | ![IMG_0365 2](https://github.com/brave/brave-ios/assets/17885425/81668ac9-1bb2-4935-9fe4-38bb447684b6) | ![IMG_0366 2](https://github.com/brave/brave-ios/assets/17885425/ee7a5db8-517a-4520-bd9b-8a6541403c10)
