### ISSUE TITLE
Screen Time Circumvention Bug

### ISSUE THREAD

**Issue by StandishMan25** [brave/brave-ios#8579]
### Description: 

Happy to see #3939 released! I found a bug though. I have been able to consistently bypass screen time by opening a new tab from the locked tab. 

### Steps to Reproduce 
  1. Browse site that has app limit and wait for time limit to hit.
  2. After limit hits, press `+` (new tab)
  3. View open tabs and tap back on locked tab. Content is now unlocked.

Bonus, after doing this it appears you can browse the site without limit in new tabs as well. 

Force closing the app and reopening will reinstate the limit, but follow the steps above to circumvent it again. I did it multiple times to ensure the repro steps just now.

### Actual result: 

<img src="https://github.com/brave/brave-ios/assets/10331270/46adade9-2f4c-40c6-8e4b-c57f66c87fed" width="400" />
<img src="https://github.com/brave/brave-ios/assets/10331270/79b40b66-42e3-49a9-9a3b-0d58035a5e80" width="400" />
<img src="https://github.com/brave/brave-ios/assets/10331270/2f681feb-fe6d-4e66-8f39-b9405b997052" width="400" />
<img src="https://github.com/brave/brave-ios/assets/10331270/398794a1-fec9-45c9-935a-96fdd9ecf2a4" width="400" />

### Expected result:

Screen time should remain in place after opening a new tab.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced.

### Brave Version: 

1.60 (23.11.27.16)

- Can you reproduce this issue with the current build from AppStore? 

Yes.

### Device details: 

iPhone 13 Pro (iOS 17.1.2)

**Comment by soner-yuksel** [comment]
@StandishMan25 we had to disable the screentime temporarily because it is causing application to get stuck with no response in upcoming release. https://github.com/brave/brave-ios/pull/8568

However we have a task to re-release https://github.com/brave/brave-ios/issues/8565 asap.

We will work on it to fix all the problems and appreciate the bug report related with it since we have consider this scenario while testing before the release.

By the way, did you have freezing problem while using the application with last version?

**Comment by soner-yuksel** [comment]
It should be fixed https://github.com/brave/brave-ios/pull/8611

**Comment by hffvld** [comment]
Verified on `iPhone 14`using version(s):
```
Device/OS: iPhone 14 / iOS 17.4 Beta
Brave build: 1.62 (24.1.29.12)
BraveCore: 1.62.153 (121.0.6167.85)
```

Filed follow-up issue #8715 and #8718
---------------------------
<details>
<summary> Standard tab </summary>

**STEPS:**
1. Device settings > Screen time > App limits
2. Set a limit for any website, for example, `youtube.com` or `theverge.com`
3. Launch Brave > Settings > Brave Shields & Privacy
4. Scroll down and turn on `Enable Screen Time` > Close the settings
5. NTP > Go to `youtube.com` (or `theverge.com`) > Wait for the screen time to hit the limit
6. Tap `+` to open NTP > Tap `view opened tabs` button
7. Tap on `locked` with screen time tab > Verify

**ACTUAL RESULTS:**
- Verified that `time limit` is applied for a website and can't be bypassed by switching tabs

---------------------------

https://github.com/brave/brave-ios/assets/128532965/e38362ec-785c-49f3-8f25-b5d8c7a707b5
</details>

<details>
<summary> Private tab </summary>

**STEPS:**
1. Device settings > Screen time > App limits
2. Set a limit for any website, for example, `youtube.com` or `theverge.com`
3. Launch Brave > Settings > Brave Shields & Privacy
4. Scroll down and turn on `Enable Screen Time` > Close the settings
5. Tap the `view opened tabs` button > Private
6. NTP > Go to `youtube.com` (or `theverge.com`) > Wait for the screen time to hit the limit
7. Tap `+` to open NTP > Tap `view opened tabs` button
8. Tap on `locked` with screen time tab > Verify

**ACTUAL RESULTS:**
- Verified that `time limit` is applied for a website and can't be bypassed by switching tabs.
- Observed that `time limit` only applied to the website, which was locked in the `Standard` tab first. If opening a website which never been locked in the `Standard` tab, the `time limit` is not applied in the `Private` tab.

---------------------------

https://github.com/brave/brave-ios/assets/128532965/eec99bb7-91dd-40f1-ac46-d99fc1c96fa1
</details>

**Comment by StandishMan25** [comment]
> @StandishMan25 we had to disable the screentime temporarily because it is causing application to get stuck with no response in upcoming release. #8568
> 
> However we have a task to re-release #8565 asap.
> 
> We will work on it to fix all the problems and appreciate the bug report related with it since we have consider this scenario while testing before the release.
> 
> By the way, did you have freezing problem while using the application with last version?

My apologies, I thought I would get emails for updates to this but never did. Will have to look at my settings. Thanks for fixing it! I did not recall having any freezing problems.
