### ISSUE TITLE
Deleting bookmark folders doesn't sync across correctly 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#859]
### Description: 
Deleting bookmark folders doesn't sync across correctly 

### Steps to Reproduce 
  1. Create sync chain with desktop on device 1 and import bookmarks on desktop, ensure syncs to device 1
  2. Sync device 2 using QR code, ensure all bookmarks and folders are sync'd 
  3. Delete the bookmark folder sync'd from desktop 
  4. Bookmarks inside folders are deleted on device 1 but folder structure is retained
  5. Remove app from memory on device 1 and relaunch, same folder structure is maintained on device 1

**Actual result:** 
Device 1:
![file 6](https://user-images.githubusercontent.com/17010094/52333612-b1663c00-2a23-11e9-87d4-286e776c58ed.jpg)
Device 2:
![file 7](https://user-images.githubusercontent.com/17010094/52333616-b32fff80-2a23-11e9-9cd8-e14a256949f0.jpg)

**Expected result:**
All deleted bookmark/folders should be removed from all devices

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent 

**Brave Version:** 
1.8(19.02.05.03)

**Device details:** 
Device 1: iPhone 7+ sync chain creator, has bookmarks from desktop
Device 2: iPad pro deletes the bookmark folder sync'd from desktop

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by LaurenWags** [comment]
* Verified passed with 1.9 (19.3.9.1) on iPad 5th Gen using STR above
* Verification passed on iPad Pro/iPhone 6/7+ running 1.9(19.3.9.1)
* Verification **PASSED** with `1.9 (19.3.27.19)` on `iPad Mini 4` using the above STR.
