### ISSUE TITLE
"Scan QR Code" from quick action to open a new tab

### ISSUE THREAD

**Issue by tomato645** [brave/brave-ios#8594]
## Problem Description 
Currently, when I use "Scan QR Code" on home screen (quick action), the app opens the URL in existing tab. 

## Feature Overview 
Open the URL from the QR code in a new tab.

## Implementation Details 
**Scan QR code in quick action:**
<img src="https://github.com/brave/brave-ios/assets/89794096/756d9d79-1811-4f17-a8e0-ea3a9cb099d4" width="30%" alt="1 Home_screen" />
**Scan QR code in url bar:**
<img src="https://github.com/brave/brave-ios/assets/89794096/7c09b1da-6a88-4466-a101-c14c5d96b6af" width="30%" alt="URL_bar" />

## User Experience 

1. From quick action -> Open URL in new tab
2. From search bar -> Same

**Comment by soner-yuksel** [comment]
@tomato645 this makes sense, I also checked other Browser interaction it is aligned with this behaviour.

**Comment by tomato645** [comment]
Thank you @soner-yuksel !!!

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.4 Beta
Brave build: 1.63 (161)
BraveCore: 1.63.161 (122.0.6261.57)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-ios/pull/8621#issue-2066271706
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the new tab is opened when scanning QR via long tap > `Scan QR Code` 

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/5b30b7de-8853-4076-8a84-f87c7870c0cc) | ![2](https://github.com/brave/brave-ios/assets/128532965/1a2ff173-786a-4852-b7c6-a2c5dfc7a5ed) | ![3](https://github.com/brave/brave-ios/assets/128532965/f3c5df67-a9c9-4eb7-ab3a-7c534ca34390) |

https://github.com/brave/brave-ios/assets/128532965/6ba9879f-750f-4056-8a4a-a22ec1ada087
