### ISSUE TITLE
Accounts Tab v2

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8600]
### Description: 

Update Accounts tab to v2 designs

**Comment by srirambv** [comment]
Verification passed on the following devices running 1.63 (151) 
- Verified steps from [#8659](https://github.com/brave/brave-ios/pull/8659)
- Verified accounts tab still showing all accounts, with total fiat values and the tokens with most balance displayed
- Verified tapping the account card or tapping `...` and selecting `View Details` loads account assets / transactions view
- Verified tapping `...` and `Edit` should open modal for the account to edit the account's name
- Verified tapping `...` and `Export` opens private key flow for the account
- Verified `Backup Wallet` works as expected when navigated via accounts menu
- Verified `Add Account` works as expected when navigated via accounts menu
- Encountered [#36428](https://github.com/brave/brave-browser/issues/36428), [#36429](https://github.com/brave/brave-browser/issues/36429), [#36430](https://github.com/brave/brave-browser/issues/36430), [#36431](https://github.com/brave/brave-browser/issues/36431)

iPhone 13 (iOS 17.6) | iPad (iOS 16.7.5) | iPhone 7+ (iOS 15.8.1)
-- | -- | --
<video src=https://github.com/brave/brave-ios/assets/17010094/91d4fb5b-05d2-4e8c-87ca-00b5e7255627> | <video src=https://github.com/brave/brave-ios/assets/17010094/5440c3ed-c584-4e33-a31a-49753e0bcf66> | <video src=https://github.com/brave/brave-ios/assets/17010094/405f9650-db0c-4126-b52a-417758210d32>
