### ISSUE TITLE
Jupiter v4 to v6 migration

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8603]
Update iOS for changes for migrating Swap Service to Jupiter v6 api.

https://github.com/brave/brave-browser/issues/35091

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.4 running 1.62 (24.1.25.17)
- Verified steps from [#8633](https://github.com/brave/brave-ios/pull/8633)
- Verified multiple quote options are removed
- Verified Swap work as expected

https://github.com/brave/brave-ios/assets/17010094/61d0b4c2-9340-4978-b6fe-10b5065c0091
