### ISSUE TITLE
[hackerone] Fix background tab navigation 

### ISSUE THREAD

**Issue by stoletheminerals** [brave/brave-ios#8606]
More details: https://hackerone.com/reports/2302358

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.3
Brave build: 1.62 (24.1.9.23)
BraveCore: 1.62.128 (120.0.6099.144)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-ios/pull/8618#issue-2066074711

**ACTUAL RESULTS:**
- Verified that it opens a `new tab` with Google but no trigger happens and opens `SafariViewController`.
- Verified the same with `Shileds` ON and OFF.

---------------------------

*Reproduced with build 1.61*

https://github.com/brave/brave-ios/assets/128532965/7aab0b4c-7ec6-4a95-906d-d1d82d4c912b

*Verified with build 1.62*

https://github.com/brave/brave-ios/assets/128532965/6bc9365c-373a-443f-86cb-e9751dd60aad
