### ISSUE TITLE
Add Browser Lock Authentication when disabling Browser Lock

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8608]
## Feature Overview 
- We should authenticate the user when attempting to disable browser lock from settings

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.62 (24.1.25.10)`

- Verified user has to authenticate when disabling `Browser Lock` feature on fresh and upgraded profiles. 

https://github.com/brave/brave-ios/assets/17885425/bc35dc87-cfd8-4667-8988-35f315f5dcde
