### ISSUE TITLE
Playlist auto download is not working

### ISSUE THREAD

**Issue by ahmed-shehata** [brave/brave-ios#8614]
### Description: 

Playlist auto download does not seem to work, even when the configuration is enabled in settings.

### Steps to Reproduce 
  1. Open Youtube.com
  2. Select a video
  3. Click on the add to playlist button

### Actual result:

Videos are not saved, user has to manually invoke the download again for each video.

https://github.com/brave/brave-ios/assets/4982099/40ec3d5e-de1e-40e1-9ccc-b161c23f956e

### Expected result:

Videos should auto download when added to playlist

**Comment by ahmed-shehata** [comment]
I've fixed it here: https://github.com/brave/brave-ios/pull/8615

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.3
Brave build: 1.62 (24.1.9.23)
BraveCore: 1.62.128 (120.0.6099.144)
```

Filed follow-up issue #8641
---------------------------

**STEPS:**
  1. Launch Brave
  2. Go to https://youtube.com
  3. Add a few videos to the playlist with any method (URL search bar, long tap, Menu)
  4. Three-dot menu > Playlist > Verify

**ACTUAL RESULTS:**
- Verified that all added to the `playlist` videos must be auto-downloaded.

---------------------------

|1|
|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/0e92953d-6ca6-4a41-9380-18e3fd9295a7) |

https://github.com/brave/brave-ios/assets/128532965/18cbfb3d-8660-485c-b524-64c5f5723398
