### ISSUE TITLE
Manual test run for `1.61.1` on `iPhone/iPad` running `iPod OS/iOS 15`

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#8624]
## Installer

- [x] Check that installer is close to the size of the last release
- [x] Check the Brave version in About and make sure it is EXACTLY as expected

## Data

- [x] Verify that data from the previous build appears in the updated build as expected (bookmarks, history, etc.)
- [x] Verify that cookies from the previous build are preserved after upgrade
- [x] Verify saved passwords are retained after upgrade
- [x] Verify stats are retained after upgrade
- [x] Verify sync chain created in the previous version is still retained on upgrade
- [x] Verify per-site settings are preserved after upgrade

## Brave Rewards/Ads

- [x] Verify wallet is auto-created after enabling Rewards
- [x] Verify when you click on the Brave Rewards panel while on a site, the panel displays if the site is verified or not
- [x] Verify ads are only shown while the app is being used
- [x] Verify tapping on an ad notification shows the landing page
- [x] Verify inline-content ads show on Brave News and are correctly redeemed from the server
- [x] Verify `view`, `clicked`, `landed`, `dismiss`, and `downvote` confirmation states are logged based on the action. Ensure these are working for inline ads, ad notifications and sponsored images.

## App linker

- [x] Long-press on a link in the Twitter app to get the share picker, choose Brave. Verify Brave doesn't crash after opening the link

## Session storage

- [x] Verify that tabs restore when closed, including active tab

**Comment by Uni-verse** [comment]
Verified on `iPad (9th Gen)` running `iPadOS 15.5` using version `1.61.1 (24.1.4.20)`
