### ISSUE TITLE
iOS makes requests to safebrowsing.googleapis.com despite using Apple's safe browsing data

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8627]
## Description 

Connections are being made by Chromium at some point to fetch safebrowsing related data on iOS.  There are 2 issues here:
- This request should not be happening since the iOS build utilizes Apple's built-in safe browsing data. 
- This request is not redirected from `safebrowsing.googleapis.com` to the proxied service `safebrowsing.brave.com`.  The call itself fails anyways right now due to the lack of API key provided.

## Steps to Reproduce

1. Prefix: Start a network proxy such as Proxyman/Charles
2. Launch iOS
3. Load any website and wait approx. 30-90s
4. Repeat 3 if it doesn't appear

## Reproduces how often: 

Easily

## Brave version (brave://version info)
Tested on 1.63

Linked: https://github.com/brave/brave-browser/issues/35137
Fixed by: https://github.com/brave/brave-core/pull/21494

**Comment by Brandon-T** [comment]
This was merged in to 1.62 already.

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.62 (24.1.25.17)`

Preconditions: 
- Enable HTTP proxy on iOS device, monitor requests after loading several URLs. 

- Verified STR in https://github.com/brave/brave-ios/issues/8627#issue-2068052252.
- Verified requests to `safebrowsing.googleapis.com` are not made after loading `https://yahoo.com`, `https://coindesk.com` and `https://www.brave.com`

Example | Example
-|-
![Screenshot 2024-01-26 at 4 43 07 PM](https://github.com/brave/brave-ios/assets/17885425/b9b907de-2cd7-47b3-b9fd-ba48075da55a) | ![Screenshot 2024-01-26 at 4 43 19 PM](https://github.com/brave/brave-ios/assets/17885425/3f10da10-a343-4c62-a07f-21a32a6714e1)
