### ISSUE TITLE
Disable Button Search Suggestion Opt-in not updating

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#8630]
### Description: 

The disable search suggestion button doesnt update the UI when it is first pressed

### Steps to Reproduce 
  1. Fresh Install Brave
  2. Search for a keyword test
  3. Check Search Suggestion Opt-In View and press disable

### Actual result: 

The Opt-in view is still visible after disbling which confuse user as it is not working

### Expected result:

Disable button should update UI automatically and hide opt in view

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily Reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
Any

### Website problems only:
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.4 (21E217)
Brave build: 1.63 (161)
BraveCore: 1.63.161 (122.0.6261.57)
```
---------------------------

**STEPS:**
1. Follow the steps from https://github.com/brave/brave-ios/issues/8630#issue-2070843932
2. *Verify*

**ACTUAL RESULTS:**
- Verified that the `Search Suggestions` button gets disabled when the user taps it and the whole dialog disappears right away
- Verified that the `Search Suggestions` is not appearing again
- Verified that tapping `Enable` on the `Search Suggestions` dialog enables the feature

---------------------------

*Reproduced with `1.62.1`*

https://github.com/brave/brave-ios/assets/128532965/74c783b3-5518-4090-9beb-88a94a53f74c

*Verified with `1.63`*

https://github.com/brave/brave-ios/assets/128532965/abcd29a1-69b2-4e6a-a27b-70f589d96da2
