### ISSUE TITLE
Intermittent Incorrect URL Bar state and various fixes related with state and url 

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#8635]
### Description: 

URL Bar update moved to `didFailProvisionalNavigation` to support spoofing prevention properly. For cancelation  `didFailProvisionalNavigation` should be used.

This way we can cover both cancelation url update problem and also blank address bar before loading starts.

Issues closed related with this were 

https://github.com/brave/brave-ios/issues/8393
https://github.com/brave/brave-ios/issues/8576

Also the async trigger for observe webview key values inside didCommit is removed. In addition verifyTrust is forced to run async and the awaited result is used on updateURL bar.

We are thinking these 2 changes will solve the intermittent problem related with loading urls stuck in insecure state.

In addition this change also should be tested where we show secure icon when insecure website is loaded.

https://github.com/brave/brave-ios/issues/7403

### Test Plan

Test all the STRs in these 3 tickets, fresh test all over again.

https://github.com/brave/brave-ios/issues/8393
https://github.com/brave/brave-ios/issues/8576
https://github.com/brave/brave-ios/issues/7403

In addition always keep an eye on if a insecure website indicator shown on a secure website.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12 Pro` running `iOS 17.1.1` using version `1.62 (24.1.11.20)`

- Verified test plan in https://github.com/brave/brave-ios/issues/8393
- Verified test plan in https://github.com/brave/brave-ios/issues/8576
- Verified test plan in https://github.com/brave/brave-ios/issues/7403
- Verified warning icon is shown in the URL bar for insecure sites (HTTP).
- Verified warning icon is not shown while loading websites (HTTPS). 

Example | Example | Example | Example | Example | Example
-|-|-|-|-|-
![IMG_5568](https://github.com/brave/brave-ios/assets/17885425/ef384d59-e611-43c0-af4f-f707a39b4e0e) | ![IMG_5570](https://github.com/brave/brave-ios/assets/17885425/280b227c-730a-4a93-a1da-f4e4877a80bc) | ![IMG_5571](https://github.com/brave/brave-ios/assets/17885425/eb9f8d45-509e-4dce-a447-d1e20dc7bec1) | ![IMG_5572](https://github.com/brave/brave-ios/assets/17885425/680eb206-292e-4ae1-b59a-ebd5fe32a7a8) | ![IMG_5574](https://github.com/brave/brave-ios/assets/17885425/ed9226bd-bee6-43eb-bd96-a5882b0717a4) | ![IMG_5576](https://github.com/brave/brave-ios/assets/17885425/5d1fea00-a1bb-4c54-b81b-b19cc915ecd2)
