### ISSUE TITLE
[Crash] - When visiting invalid URLs, the app can crash and get into a crash loop

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8647]
### Description: 
- When loading invalid URLs, the app will save the URL to disk, and upon reloading the page, it can crash. It can also crash when opening the URL in a new tab via the context-menu.

### Steps to Reproduce 
  1. Visit: https://boardgamedesignlab.com/mechanism-master-list/
  2. Long-Press on `Auction: Once Around`
  3. Open In New Tab

### Actual result: 
- Crash

### Expected result:
- Should not Crash

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily Reproduced

### Brave Version: 
- All versions

### Device details: 
- All devices

### Website problems only:
- Yes

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.62 (24.1.25.17)`

- Ensured crash does not happen using STR in https://github.com/brave/brave-ios/issues/8647#issue-2079301520
- Ensured crash does not happen when opening `Auction: Once Around` link in private tab

Example | Example | Example
-|-|-
![IMG_3708](https://github.com/brave/brave-ios/assets/17885425/95f0b646-b382-45b6-a1fb-a0741d73744d) | ![IMG_3709](https://github.com/brave/brave-ios/assets/17885425/43c6448c-139a-4b18-8e16-33a834089e87) | ![IMG_3710](https://github.com/brave/brave-ios/assets/17885425/2b11bae6-e4b9-45ce-b279-859d7ee910d9)
