### ISSUE TITLE
Remove max number of filter lists

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#8656]
### Description: 
We added a limit to filter list when we had crashes. This was since resolved and found to be an issue on brave core

### Steps to Reproduce 
1. Go to filter lists
2. See that you can enable all filter lists and so do that
3. Go back to page with all filter lists enabled and see that nothing bad happens (such as a crash)
4. Kill app and reopen it and see that it loads timely and ad-blocking/CF works

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.4 Beta
Brave build: 1.63 (161)
BraveCore: 1.63.161 (122.0.6261.57)
```
---------------------------

<details>
<summary> Fresh profile </summary>

**STEPS:**
1. Follow the flow from https://github.com/brave/brave-ios/issues/8656#issue-2084745207
2. *Verify*

**ACTUAL RESULTS:**
- Verified that Brave is not crashing 
- Verified that all filters can be enabled at the same time

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/87985e36-256b-40b2-beeb-a06a29f9b5ab) | ![2](https://github.com/brave/brave-ios/assets/128532965/b848ba7c-fc83-49fe-88e9-25223e521c68) | ![3](https://github.com/brave/brave-ios/assets/128532965/1f8200bd-48e2-4065-bac5-44d60e6611b0) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/5c2f10f6-fa5d-4f99-a1e3-1c1f264a47a7) | ![2](https://github.com/brave/brave-ios/assets/128532965/514d680b-f668-4b36-9fc9-cd69cc152d93) | ![3](https://github.com/brave/brave-ios/assets/128532965/d2b277c3-83e5-4aa2-b2fb-ce7445a21f46) |

https://github.com/brave/brave-ios/assets/128532965/63914e3c-8ef2-41f3-9c34-5df6ce76a0b4

</details>

<details>
<summary> Upgraded profile </summary>

**STEPS:**
1. Install and launch Brave `1.62.1`
2. Settings > Brave Shields & Privacy > Content Filtering
3. Enable all possible filters 
4. Follow the flow from https://github.com/brave/brave-ios/issues/8656#issue-2084745207
5. *Verify*

**ACTUAL RESULTS:**
- Verified that Brave is not crashing 
- Verified that all filters can be enabled at the same time
- Verified that all Filters can be enabled after Brave upgrade

https://github.com/brave/brave-ios/assets/128532965/b1df6e20-8ab7-45cd-9857-89f713f49330
</details>
