### ISSUE TITLE
Account Details v2

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8663]
### Description: 

Account Details v2 design updates:

<img width="195" alt="Account Details" src="https://github.com/brave/brave-ios/assets/5314553/00d54889-ad26-4513-aa14-a964e1ed0311"> | <img width="199" alt="Account Details Tokens" src="https://github.com/brave/brave-ios/assets/5314553/78b6196e-097f-4bf4-88ee-545ac5b174a7">
--|--

**Comment by srirambv** [comment]
Verification passed on the iPhone 13(iOS 17.6) / iPad (iOS 16.7.1) / iPhone 7+ (iOS 15.8.1) running 1.63 (161) 
- Verified steps from [#8716](https://github.com/brave/brave-ios/pull/8716)
- Verified opening account details for each coin type (Ethereum, Solana, Filecoin) works
- Verified total fiat balance loads correclty
- Verified asset list loads with balance and prices of selected account
- Verified NFTs grid loads with metadata
- Verified transactions list loads as expected for selected account
- Verified Dapp settings opens for ETH/SOL accounts
- Verified tapping `...` and tap `Edit` allows to edit account name 
- Verified updating account name updates it in account details view as well
- Verified tapping `...` and tap `Export` loads the private key modal
