### ISSUE TITLE
Auto-upgrade passive mixed content using a content blocker

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#8664]
### Description: 

Security review https://github.com/brave/reviews/issues/1488

iOS/WebKit only auto-upgrades active mixed content such as scripts, but we should also add a content blocker to auto-upgrade passive content such as images as per https://www.w3.org/TR/mixed-content/#upgrade-algorithm

The content blocker rule in question:

```json
{
  "trigger": {
    "url-filter": "http://.*",
    "if-top-url": ["https://.*"],
    "resource-type": [
      "image", "media"
    ]
  },
  "action": {
    "type": "make-https"
  }
}

**Comment by diracdeltas** [comment]
Note that if the content cannot be upgraded (ex: doesn't support HTTPS) it should be blocked from loading

**Comment by kylehickinson** [comment]
@diracdeltas Can you elaborate? Content blockers only give us so much control, the above will simply make http images, videos and audio URLs load on https and we won't know prior if they actually support https. Those loads would still happen but just fail with some error (likely 404)

**Comment by diracdeltas** [comment]
> @diracdeltas Can you elaborate? Content blockers only give us so much control, the above will simply make http images, videos and audio URLs load on https and we won't know prior if they actually support https. Those loads would still happen but just fail with some error (likely 404)

It's fine if they don't support HTTPS; the important thing is that they don't load over HTTP if the HTTPS redirect fails.

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.4 Beta
Brave build: 1.62 (24.1.25.17)
BraveCore: 1.62.153 (121.0.6167.85)
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-ios/pull/8680#issue-2090953133

**ACTUAL RESULTS:**
- Verified that `very.badssl.com` (or any mixed content site) shows only the `triangle` icon but that the icon is still tappable.
- Verified that `http.badssl.com` and `expired.badssl.com` still display the appropriate `Not Secure` title.
- Verified via Safari Web Inspector that `HTTP` content was promoted to `HTTPS`. A `console` log appears noting that it `promoted the image to HTTPS` and the `Network` tab displays a `lock` next to the upgraded content.

---------------------------

*Standard tab*

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/eb195079-4cbe-4002-8daa-b42df0c76c7b) | ![2](https://github.com/brave/brave-ios/assets/128532965/a86ca769-582b-4a75-8117-5952591ae2c9) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/39ad04b7-57c6-488d-96f8-7f9d0e5fab53) | ![2](https://github.com/brave/brave-ios/assets/128532965/18677aab-9faf-49b6-8581-0ab6158e86b4) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/50e6976a-16c7-46b9-901f-4f7572b7b298) | ![2](https://github.com/brave/brave-ios/assets/128532965/e12dfec6-ae5f-44f2-849d-946e5cac51fd) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/30173675-2b48-44be-aa8a-a92d718e3766) | ![2](https://github.com/brave/brave-ios/assets/128532965/d1a2743f-87b5-49db-8a94-26740d4098cc) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/b0a8436c-4989-4a3c-877f-96d1855659c6) | ![2](https://github.com/brave/brave-ios/assets/128532965/111f4e21-179b-4150-a6ee-3d3b2b033a07) |

*Private tab*

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/b8f208e0-fe1c-47a2-8d57-b6f733fc4da7) | ![2](https://github.com/brave/brave-ios/assets/128532965/a6f72d1f-2f1b-4604-9c8f-479ae4de646d) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/73a8ce1f-db6a-4121-9fcc-75a7caf9c4d2) | ![2](https://github.com/brave/brave-ios/assets/128532965/e09edd71-1751-4170-9a61-de000ca93221) |
 | ![1](https://github.com/brave/brave-ios/assets/128532965/f720e958-963d-46d9-b831-a96a1be6a432) | ![2](https://github.com/brave/brave-ios/assets/128532965/afc33c69-afa8-4d9a-84b6-3324dbe58a57) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/63dc0cc0-02b4-4135-955b-c0fb581137dd) | ![2](https://github.com/brave/brave-ios/assets/128532965/30988925-d20f-4225-8bec-dd2b2eb1cf4f) |
