### ISSUE TITLE
Opening an external URL in a mode different from where the URL is already open causes a freeze

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8665]
### Description: 
- Opening a URL in regular or private mode, when already opened in the opposite mode will freeze the app.

### Steps to Reproduce 
  1. Open any URL in regular browsing mode.
  2. Switch to Private Browsing Mode.
  3. Open the same URL from an external app (such as iMessage).

### Actual result: 
- URL is not actually opened. App seems like it's frozen (it isn't actually frozen)

### Expected result:
- Should Open the new URL in the current mode, in a new tab

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily Reproduced

### Brave Version: 
- All

### Device details: 
- All

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.4 Beta
Brave build: 1.62 (24.1.25.17)
BraveCore: 1.62.153 (121.0.6167.85)
```
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-ios/issues/8665#issue-2086802173

**ACTUAL RESULTS:**
- Verified that Brave is not freezing when the same tab is opened in both `Standard` and `Private` tab

---------------------------

*Reproduced with `1.61.1`*

https://github.com/brave/brave-ios/assets/128532965/15e5683f-df44-4fdd-8dcd-3fe888c1933e

*Verified with `1.62`*

https://github.com/brave/brave-ios/assets/128532965/beb12f46-04be-4d32-addf-7fdd5d354460
