### ISSUE TITLE
Webcompat reporter sending internal://local URL instead of correct one

### ISSUE THREAD

**Issue by ShivanKaul** [brave/brave-ios#8667]
### Description: 

We're getting several internal://local URLs on the webcompat reporter backend. This points towards a bug on the client-side, since an internal URL doesn't help us fix Shields issues. The two cases where this seems to be happening is:

1. User is in Reader mode
2. User is on an error page

Interestingly, if I go through hamburger menu to report the site, the URL shows up correctly.

### Steps to Reproduce 
  1. Start Reader mode on a website like https://www.themediterraneandish.com/shakshuka-recipe/
  2. Shields down
  3. Report site

Can also repro by going to a website and turning off wifi/data, in which case the URL shows up as internal://local/errorpage

### Actual result: 

![IMG_9865](https://github.com/brave/brave-ios/assets/5284154/eeb6f126-8772-4fca-827e-7231a1c54e1c)

### Expected result:

![IMG_9867](https://github.com/brave/brave-ios/assets/5284154/7162a1aa-f5f3-4b34-9b37-3942d9744cf7)

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.4 Beta
Brave build: 1.63 (161)
BraveCore: 1.63.161 (122.0.6261.57)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Go to https://chromeunboxed.com or https://www.themediterraneandish.com/shakshuka-recipe/, for example 
3. Open any article > Enable `Reader Mode`
4. Brave Shields > Disable shields
5. Tap `Report a Broken Site` > *Verify*

**ACTUAL RESULTS:**
- Verified that `internal://local/` is not shown when reporting a website via `Brave Shields` or `Main menu`
- Verified that the correct URL is shown 

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/9fb63c26-057c-4f89-ab72-029768dcc932) | ![2](https://github.com/brave/brave-ios/assets/128532965/77004b0a-366d-4c09-94b6-e2ede6363c27) | ![3](https://github.com/brave/brave-ios/assets/128532965/df713ebf-fbc7-4f21-b4ae-e8ee96434501) | ![4](https://github.com/brave/brave-ios/assets/128532965/82bf7dc1-69e6-4365-b286-a0faa0b62416) |
