### ISSUE TITLE
Status bar changes its position in horizontal mode on settings screen.

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#867]
### Steps to Reproduce 
  1. Open settings
  2. Flip phone to landscape

**Actual result:** 
<img width="947" alt="zrzut ekranu 2019-02-6 o 18 59 59" src="https://user-images.githubusercontent.com/6950387/52362813-ac17ea00-2a41-11e9-9cab-d509a26eb542.png">

**Expected result:**
Should stay in portrait mode

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13 running 1.12(19.9.4.23)
* Verified rotating device to landscape and open setting forces the UI to rotate to portrait mode
* Verified same behaviour for Bookmarks/History/Downloads/Add Bookmark options from menu
* Logged follow up issue #1491

Verification **PASSED** on `iPad Air 3rd Generation` with `iOS 13.1` running `1.12 (19.09.07.03)`:
* ensured that rotating between `portrait` and `landscape` correctly switches the UI and everything appears aligned
   * ensured `Settings`, `History`, `Bookmarks`, `Downloads`,  `Add Bookmark` and `Share with...` worked as expected

Verification passed on iPhone 7+ with iOS 12.4.1 running 1.12(19.09.13.06)
* Verified rotating device to landscape and open setting forces the UI to rotate to portrait mode
* Verified same behaviour for Bookmarks/History/Downloads/Add Bookmark options from menu
* Logged follow up issue #1491
