### ISSUE TITLE
'Sync everything' enabled when connecting device to sync chain [CR121] 

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#8677]
### Description: 

This should be tested in 1.63 on iOS side after uplift https://github.com/brave/brave-core/pull/21632 merged

Issue on Android side https://github.com/brave/brave-browser/issues/35333

### Steps to Reproduce 
Start with fresh profile
Add device by scanning QR code.
Check Sync Data Preferences

### Expected result:

Only Sync Bookmarks should be enabled in preferences.

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily reproduced

### Brave Version: 

Test it using 1.63 build

### Device details: 
Any

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.62 (24.1.25.10)`

- Verified STR in https://github.com/brave/brave-ios/issues/8677#issue-2090876540
- Verified only syncing bookmarks is enabled when connecting to sync chain. 
- Verified connecting to sync chain via segmented tab flow and settings flow on fresh profile. 
- Verified connecting to sync chain on upgraded profile shows only bookmarks syncing by default. 

<img width="400" alt="01" src="https://github.com/brave/brave-ios/assets/17885425/dbd198d2-1314-47b6-8355-51adfd56c13e">
