### ISSUE TITLE
Stop Recommending Alexa Top Sites for Search Suggestions.

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#868]
We currently autocomplete urls with a list from https://github.com/brave/brave-ios/blob/development/Client/Assets/topdomains.txt

With a clean history it will autosuggest sites, if you start typing letters in the url bar
for example: on a fresh app type letter `k` in the url bar, it will fill rest of the url to `kohls.com`

We need to decide if this is good practice or not

**Comment by srirambv** [comment]
#807 should also be considered as part of the fix for this

**Comment by jhreis** [comment]
Completely kill this feature, and all topdomains.txt related logic.

**Comment by jamesmudgett** [comment]
![IMG_2781](https://user-images.githubusercontent.com/318119/56238294-c37fde80-6053-11e9-927f-535ba9edfbdc.jpg)

**Comment by jamesmudgett** [comment]
Remove topdomains from autofill

**Comment by srirambv** [comment]
@jamesmudgett @iccub  is there a limit for the number of history/bookmark items show up when typing in?

**Comment by anthonypkeane** [comment]
> @jamesmudgett @iccub is there a limit for the number of history/bookmark items show up when typing in?

5

**Comment by srirambv** [comment]
@anthonypkeane  I am seeing 7 
![image](https://user-images.githubusercontent.com/17010094/67040904-73f99880-f0f2-11e9-9626-d72c98645962.png)

**Comment by anthonypkeane** [comment]
It is ok and we can tidy it up in later builds.

**Comment by srirambv** [comment]
Verification passed on iPhone Xr with iOS 13.2 running 1.13(19.10.18.15)
* Verified Alexa top sites are not shown as recommendations on a clean profile
* Verified only sites from bookmark/history is shown in the suggestion list
* Logged #1734  to restrict the number of suggestion

Verification passed on iPad Pro with iOS 13.2 running 1.13(19.10.18.15)
* Verified Alexa top sites are not shown as recommendations on a clean profile
* Verified only sites from bookmark/history is shown in the suggestion list

Verification passed on iPhone 6 with iOS 13.2 running 1.13(19.10.18.15)
* Verified Alexa top sites are not shown as recommendations on a clean profile
* Verified only sites from bookmark/history is shown in the suggestion list

Verification passed on iPad Pro with iOS 12.4 running 1.13(19.10.18.15)
* Verified Alexa top sites are not shown as recommendations on a clean profile
* Verified only sites from bookmark/history is shown in the suggestion list
