### ISSUE TITLE
Security Certificate row shown in menu when no certificate found

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8688]
### Description: 

Security Certificate row can be shown in menu when there is no certificate to show

### Steps to Reproduce 
  1. Paste `https://www.m.youtube.com/user/YouTube/playlists?app=desktop` into url bar
  2. Tap `...` menu
  3. Tap `Security Certificate` row
  4. Observe menu closes, nothing shown

### Actual result: 

https://github.com/brave/brave-ios/assets/5314553/987ed910-8938-4f7e-a074-06c827391c6b

### Reproduces how often: 

Easily reproduced

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by Uni-verse** [comment]
Verified on `iPhone X` running `iOS 16.7` using version `1.62 (24.1.25.10)`

- Verified STR in https://github.com/brave/brave-ios/issues/8688#issue-2094642928 on fresh and upgraded profiles. 
- Verified tapping on `Security Certificate` in menu will display certificate when loading `https://www.m.youtube.com/user/YouTube/playlists?app=desktop`.


https://github.com/brave/brave-ios/assets/17885425/1b53624d-cd35-4ccb-922a-684c5d668ce0
