### ISSUE TITLE
JS DoS

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#87]
```
<script>
   while(true) {
     alert(1);
   }
</script>
```

## Test Plan

- please see PR

**Comment by tmancey** [comment]
@jumde hi, you classified this issue as a bug, then removed bug. Can you please let me know if this is a bug or an enhancement as I am making sure all tickets are correctly labeled to help with reporting?

**Comment by jumde** [comment]
label `bug` sounds good.

**Comment by danishjafri88** [comment]
The app is susceptible to js DOS attack especially the window.alert attack. The alert shown blocks the entire screen.
For other bowsers following is the result:
FF: same as brave
Safari: custom alert component
![img_6069](https://user-images.githubusercontent.com/5398557/49171783-4fbf8c80-f365-11e8-8ed8-553a18fe94e8.JPG)
Chrome: Blocking alert with option to suppress window.alert after multiple alerts are thrown
![img_6067](https://user-images.githubusercontent.com/5398557/49171830-71b90f00-f365-11e8-9151-a7abf8caf2c7.JPG)
![img_6068](https://user-images.githubusercontent.com/5398557/49171834-74b3ff80-f365-11e8-82e5-bdc7b9b44944.JPG)

Possible solutions for this DOS attack is either of Chrome's or Safari's way.

**Comment by jamesmudgett** [comment]
@danishjafri88 We need a way to suppress, the Chrome flow works well.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13 running 1.12(19.09.04.23)
* Verified app doesn't hang when constant popups show up
* Verified selecting `Ok` or `Cancel` doesn't cause app to hang
* Verified `Suppress notifications` only affect for that particular session and doesn't show up again until the tab is closed and reopened

Verification **PASSED** on `iPad Air 3rd Generation iOS 13.1` running `1.12 (19.09.10.18)`:

* Verified app doesn't hang when constant popups show up
* Verified selecting `Ok` or `Cancel` doesn't cause app to hang
* Verified `Suppress notifications` only affect for that particular session and doesn't show up again until the tab is closed and reopened

**Comment by kjozwiak** [comment]
@danishjafri88 quick question regarding this fix. Whenever you suppress the modal/dialog/alerts, the page becomes unresponsive. Example:

* open https://github.com/brave/brave-ios/pull/770 in a new tab
* tap on https://dustiest-limitation.000webhostapp.com/alert.html
* suppress the alert and you'll notice that the page becomes unresponsive and appears as it's still attempting to load. Tapping on the `X` to stop the load doesn't do anything. You'll need to basically close the tab and re-open.

Is the above expected? Or should the page recover once you suppress the alerts?

**Comment by srirambv** [comment]
@kjozwiak  that expected. More discussion on this here: https://bravesoftware.slack.com/archives/C06UXF3KJ/p1567691573119300

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 12.4.1 running 1.12(19.09.13.06)
* Verification passed on https://www.guyrutenberg.com/wp-content/uploads/2007/11/alertloop.html
* LInks from PR are not working so only verified on https://www.guyrutenberg.com/wp-content/uploads/2007/11/alertloop.html
