### ISSUE TITLE
Block all cookies global setting doesnt stick 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#870]
### Description: 
Block all cookies global setting doesnt stick 

### Steps to Reproduce 
  1. Update/Install 1.8(19.02.06.22)
  2. Enable Block all cookies from settings
  3. Setting resets back to default state

**Actual result:** 
![ios](https://user-images.githubusercontent.com/17010094/52401215-29e20100-2ae7-11e9-8a10-f3c1ea7d2007.gif)

**Expected result:**
Settings changes should be persistent 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.8(19.02.06.22)

**Device details:** 
iPhone 7+ (iOS 12.1.2)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 7+
* Verified clearing browsing data and then enabling setting retains the state change
* Verified setting works on both normal and private tabs
* Verified clearing browser data with setting enabled clears all history

**Comment by kjozwiak** [comment]
Went through the test plan @srirambv mentioned above using an `iPad Mini 4` which is running `iOS 12.1.4`:

* Verified that the issue has been resolved using `1.8 (19.02.20.21)`
