### ISSUE TITLE
[ads] Unify iOS kBraveNTPBrandedWallpaper

### ISSUE THREAD

**Issue by tmancey** [brave/brave-ios#8701]
Corresponding changes to https://github.com/brave/brave-browser/issues/35522

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.4 Beta
Brave build: 1.62 (24.2.6.11)
BraveCore: 1.62.158 (121.0.6167.139)
```
Filed follow-up issue #8740
---------------------------

**STEPS:**
1. Followed the steps from https://github.com/brave/brave-ios/pull/8702#issue-2100748362
2. And https://github.com/brave/brave-browser/issues/35522#issuecomment-1928847709

**ACTUAL RESULTS:**
- Verified that `NTP SI` is shown on 2nd `NTP` for `BraveNTPBrandedWallpaper`/`initial_count_to_branded_wallpaper`
- Verified that `NTP SI` must be shown on every 3rd `NTP` for `BraveNTPBrandedWallpaper`/`count_to_branded_wallpaper` but observed it on every 4th `NTP`

---------------------------

*Rewards opt-out*

https://github.com/brave/brave-ios/assets/128532965/5a3c39d6-265a-41e5-b0a8-5136974c8c12

*Rewards opt-in*

https://github.com/brave/brave-ios/assets/128532965/a665a750-353a-423d-a01d-8b3a71be9644
