### ISSUE TITLE
Match Desktop SSL Cert Display

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8703]
### Description: 
iOS shows the handshake certificate when the navigation fails. Chrome does not.

### Steps to Reproduce 
  1. Visit https://10000-sans.badssl.com/ in Google Chrome or Brave Desktop
  2. Visit the same site on iOS
  3. View certificate on Both iOS and Desktop.

### Actual result: 
- iOS shows the certificate

### Expected result:
- Should not show

### Reproduces how often: [Easily reproduced, Intermittent Issue]
- Easily reproduced

### Brave Version: 
- 1.62.x
### Website problems only:
- Yes

### Additional Information
- Related to: https://github.com/brave/brave-ios/issues/8688

**Comment by hffvld** [comment]
Verified on `iPhone 14` using version(s):
```
Device/OS: iPhone 14 / iOS 17.4 Beta
Brave build: 1.62 (24.1.29.12)
BraveCore: 1.62.153 (121.0.6167.85)
```

Filed follow-up issue #8712
---------------------------

<details>
<summary> Show cert - PASS </summary>

**STEPS:**
1. Install and launch Brave `1.62`
2. Open NTP and go to `https://www.m.youtube.com/user/YouTube/playlists?app=desktop` > Verify
3. Tap `Not Secure` > View Certificate > Verify
4. Three-dot menu > Security Certificate > Tap it > Verify
5. Reload the page > Verify the same as in the previous steps

**ACTUAL RESULTS:**
- Verified that `Not Secure` is shown in the URL search bar
- Verified that the certificate is shown when tapping `View Certificate`
- Verified that `Security Certificate` is shown in the settings and the certificate can be viewed
- Verified that the same behavior after refreshing the page

---------------------------

|1|2|3|4|
|:-:|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/79ea578d-de2a-41f1-afe3-e32a201e643a) | ![2](https://github.com/brave/brave-ios/assets/128532965/f25d6e7f-756e-4d91-91a9-4c1f199d8bc5) | ![3](https://github.com/brave/brave-ios/assets/128532965/a6b452a0-89ba-4471-8207-ab636a4624ab) | ![4](https://github.com/brave/brave-ios/assets/128532965/47b95671-3926-4cf6-a9dd-760a8414a300) |

https://github.com/brave/brave-ios/assets/128532965/a1b42bce-e699-4ae8-9fbb-2ebaab860f6e
</details>

<details>
<summary> Hide cert - FAIL </summary>

**STEPS:**
1. Install and launch Brave `1.62`
2. Open NTP and go to `https://10000-sans.badssl.com/ ` > Verify
3. Tap `Not Secure` > Verify
4. Three-dot menu > Scroll down > Verify that `Security Certificate` is not shown
5. Reload the page > Verify the same as in the previous steps

**ACTUAL RESULTS:**
- Verified that `Not Secure` is shown in the URL search bar
- Verified that `View Certificate` is not shown when tapping on `Not Secure`
- Observed that `Security Certificate` is shown in the settings, but tapping on it is not opening the certificate itself
- Verified that the same behavior after refreshing the page

---------------------------

|1|2|3|
|:-:|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/43339d05-6215-4ce9-bc1f-4744ea07ade3) | ![2](https://github.com/brave/brave-ios/assets/128532965/c737baa2-200b-44c2-8a63-cc289ee3e17b) | ![3](https://github.com/brave/brave-ios/assets/128532965/108671ca-d9cd-440e-bf69-3b45804ff344) |

https://github.com/brave/brave-ios/assets/128532965/0002241d-af5d-4dd9-8d20-bfcd23edc70d
</details>
