### ISSUE TITLE
Add ability to view all version info like on Desktop

### ISSUE THREAD

**Issue by Brandon-T** [brave/brave-ios#8705]
### Description: 
- With WebUI, iOS is capable of showing all version info. It just doesn't do it atm.
- It should show the version info that shows on Desktop and Android.

**Comment by hffvld** [comment]
Verified on `iPhone 14` and `iPad Air` using version(s):
```
Device/OS: 
- iPhone 14 / iOS 17.4 Beta
- iPad Air / iPadOS 16.7.2
Brave build: 1.62 (24.2.8.16)
BraveCore: 1.62.158 (121.0.6167.139)
```
Filed follow-up issue #8752
---------------------------

**STEPS:**
1. Install and launch Brave 
2. Three-dot menu > Settings
3. About > Tap `Version...` > *Verify `View all version info.` is shown*
4. Tap `View all version info.` > *Verify the page with version info is shown*

**ACTUAL RESULTS:**
- Verified that `View all version info.` is shown in the settings
- Verified that `View all version info` page is opened and show the info

---------------------------

*iPhone 14*

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-ios/assets/128532965/c3fd0f5a-d24d-4379-93ce-6c16a53091e4) | ![2](https://github.com/brave/brave-ios/assets/128532965/eb3a0436-32a0-45a7-9089-26701d957f22) |
| ![1](https://github.com/brave/brave-ios/assets/128532965/493893bf-9b72-470a-8706-57a53badf97b) | ![2](https://github.com/brave/brave-ios/assets/128532965/18c17b1f-5b50-46c9-ad75-be2464099bb7) |

*iPad Air*

|1|2|
|:-:|:-:|
| ![1](https://github.com/brave/brave-variations/assets/128532965/ddd23445-aaf4-4897-ba0a-bde99b8872c3) | ![2](https://github.com/brave/brave-variations/assets/128532965/c35878cd-f49e-43a6-83b0-acb587213899) |
| ![1](https://github.com/brave/brave-variations/assets/128532965/9dae2997-2399-49af-9226-a845a5084ce8) | ![2](https://github.com/brave/brave-variations/assets/128532965/b1f69623-1424-447e-a31d-21e69f840c40) |
