### ISSUE TITLE
Incorrect alignment of NFTs on iOS 17.3

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#8708]
### Description: 
Incorrect alignment of NFTs on iOS 17.3

### Steps to Reproduce 
1. Restore a wallet with NFTs
2. Once Portfolio is shown, dismiss wallet
3. Tap `...` -> `Settings` -> `Web3` (must be done through browser settings)
4. Reset wallet
    - Do not quit / relaunch the app
5. Re-open wallet and restore the same wallet from step 1
6. Open NFT tab, enable auto-discovery and wait
7. Observe auto-discovered assets are duplicated (Portfolio & NFTs), NFTs display as a single line due to duplicates

![IMG_205C30BE77EE-1](https://github.com/brave/brave-ios/assets/5314553/418e0d8f-2744-4fb4-a97f-7633ee21cc4e) | ![IMG_506D224B51D2-1](https://github.com/brave/brave-ios/assets/5314553/d209405d-9824-4eaf-bb5e-d9e87405e129)
--|--

### Actual result: 

https://github.com/brave/brave-ios/assets/17010094/da3a436a-c23e-4f6c-8fb2-176b03f800d8

### Expected result:
<img width=300 src=https://github.com/brave/brave-ios/assets/17010094/698dd3d5-a4ea-4950-a258-d01a0e89546d>

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easy

### Brave Version: 

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? NA
- Can you reproduce this issue with the current build from AppStore? No

### Device details: 
iPhone 13 (iOS 17.3)

### Website problems only:
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information
cc: @nuo-xu @StephenHeaps

**Comment by StephenHeaps** [comment]
Updated steps to reproduce with consistent steps

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.4 running 1.62 (24.2.7.2)
- Verified steps from issue description and [#8739](https://github.com/brave/brave-ios/pull/8739)
- Verified NFTs are aligned correctly and not duplicated
- Encountered [#8744](https://github.com/brave/brave-ios/issues/8744)
