### ISSUE TITLE
Portfolio asset filters does not always open

### ISSUE THREAD

**Issue by StephenHeaps** [brave/brave-ios#8709]
### Description: 

Sometimes tapping the filters button in the assets section of Portfolio tab does not open the filters tray intermittently.

### Steps to Reproduce 
  1. Scroll to bottom of Portfolio
  2. Scroll to top
  3. Tap filters button
  4. Observe filters tray does not open (intermittent)
     - Sometimes scrolling up/down will open the tray

### Actual result: 

Tapping filters button does not open filters tray.

https://github.com/brave/brave-ios/assets/5314553/c314b0d4-1d5c-4baa-99a5-012e463aeec3

### Expected result:

Tapping filters button always opens filters tray

### Reproduces how often: 

Intermittent Issue

### Brave Version:

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Website problems only:
- did you check with Brave Shields down? 
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.4 running 1.62 (24.1.29.12)
- Verified steps from issue description and [#8710](https://github.com/brave/brave-ios/pull/8710)
- Verified portfolio filter opens when scrolling up and down on portfolio asset list

https://github.com/brave/brave-ios/assets/17010094/c0db8f55-e580-4948-afca-a2764fa196c8
