### ISSUE TITLE
Reload All Tabs on Global Toggle Changes

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#871]
When the user modifies `blockAllCookies` all tabs should be reloaded _after_ confirming the reload with the user.

- [x] Revert: https://github.com/brave/brave-ios/issues/808
- [x] Follow suggestion: https://github.com/brave/brave-ios/issues/808#issuecomment-458105376

STR: Follow iOS steps on https://github.com/brave/brave-ios/issues/808

**Comment by kylehickinson** [comment]
Is this still valid?

**Comment by iccub** [comment]
All tabs seem to be reloaded now on cookie setting toggle
