### ISSUE TITLE
Brave Talk will mute / unmute when minimized and spacebar is pressed.

### ISSUE THREAD

**Issue by murphyd** [brave/brave-ios#8717]
### Description: 

If I minimize Brave Talk in Brave so I can use the browser, hitting the space bar while in another window (e.g. typing an email) will also mute/unmute the microphone. 

### Steps to Reproduce 
  1. Start a Brave Talk call
  2. Press the down arrow in the top-left hand corner to mimimize BVrave talk 
<img width="232" alt="image" src="https://github.com/brave/brave-ios/assets/4502617/13ed9c28-6bfe-4f8a-aee4-dd2ab8209004">

  3. In another window (or address bar) begin typing. You’ll hear it mute/unmute if the sound is on.

### Expected result:
Hotkeys/shortcuts for Brave Talk should not be active when Brave Talk is minimized.

### Reproduces how often: [Easily reproduced, Intermittent Issue]
100% of the time.

### Brave Version: 
Version 1.61.1 (24.1.4.20)

- Can you reproduce this issue with the most recent build from TestFlight? Yes.
- Can you reproduce this issue with the previous version of the current build from TestFlight? N/A
- Can you reproduce this issue with the current build from AppStore? Yes.

### Device details: 
IPadOS 17.3

Cc: @kylehickinson

**Comment by hffvld** [comment]
Verified on `iPad Air` using version(s):
```
Device/OS: iPad Air / iPadOS 16.7.2
Brave build: 1.63 (161)
BraveCore: 1.63.161 (122.0.6261.57)
```
---------------------------

**STEPS:**
1. Launch Brave 
2. Connect physical keyboard
3. Go to `talk.brave.com` > Start a call
4. Tap `∨` in the top left corner to minimize `Brave Talk` window
5. Open `NTP` > URL search bar
6. Start typing > Tap the `Spacebar` > Verify 

**ACTUAL RESULTS:**
- Verified that `Mic` Mute/Unmute is not triggered when tapping the `Spacebar` on the keyboard while `Brave Talk` is in use

---------------------------

*Repro with 1.62.1*

https://github.com/brave/brave-ios/assets/128532965/093713d1-e466-4ae4-9d75-6a40a8874125

*Verified with 1.63*

https://github.com/brave/brave-ios/assets/128532965/e7845674-0f40-43f1-910d-c610f2769e8c
