### ISSUE TITLE
Adapt to uBO's scriptletGlobals change from Map to object

### ISSUE THREAD

**Issue by cuba** [brave/brave-ios#8727]
### Description: 
Changes reflecting: https://github.com/brave/brave-browser/issues/35679

**Comment by Uni-verse** [comment]
Verified on `iPhone 12 Pro` running `iOS 17.3` using version `1.62 (24.2.2.21)`

Test Plan: https://github.com/brave/brave-core/pull/21813#issuecomment-1922497211

<details><summary>Youtube.com Homepage</summary>

1. new profile
2. load youtube.com
3. stay logged out
4. click around
5. return to youtube.com
6. reload with desktop version
7. click around
8. return to homepage

- Ensured no ads are shown when returning to youtube.com homepage using mobile and desktop versions.

Example | Example
-|-
![IMG_5641](https://github.com/brave/brave-core/assets/17885425/c22cbebf-a38c-4e50-9ac2-fe59e838b85e) | ![IMG_5652](https://github.com/brave/brave-core/assets/17885425/f4f9d4c6-fede-4305-863d-0a51c54cdddf)


</details>

<details><summary>Direct URLs</summary>

- Ensured loading youtube URL does not present ads.

![IMG_5642](https://github.com/brave/brave-core/assets/17885425/a35f9e4f-a271-4ee1-a23c-b4b3c12b022a)


</details>

<details><summary>Searches</summary>

1. Use search on homepage, observe results
2. Change site to desktop version, use search
3. Observe search results

- Ensured no ads are present in the search results page on youtube.com

Example | Example
-|-
![IMG_5645](https://github.com/brave/brave-core/assets/17885425/667023c8-5cb0-4273-9224-d2da6468a41c) | ![IMG_5653](https://github.com/brave/brave-core/assets/17885425/4c730716-e24c-41d9-a227-f62fa234450f)


</details>

<details><summary>Live</summary>

- Ensured ads are not shown when viewing Live videos

![IMG_5647](https://github.com/brave/brave-core/assets/17885425/566996cd-8c5a-4ae4-bfef-0e2031434d5a)


</details>

<details><summary>Movies</summary>

- Ensured viewing movies on youtube.com does not present ads
- Ensured that seeking does not cause ads to be shown

![IMG_5649](https://github.com/brave/brave-core/assets/17885425/58ae9c5d-da97-4acd-bd86-d778d2d48e71)


</details>

<details><summary>Shields Off</summary>

- Ensured ads are shown when Shields are disabled or Ad-blocking is disabled in the shields panel.

Example | Example
-|-
![IMG_5650](https://github.com/brave/brave-core/assets/17885425/3dc36d67-a10b-4fcd-a440-b092ba186dee) | ![IMG_5651](https://github.com/brave/brave-core/assets/17885425/d78d2e8c-1bb5-436f-9a3f-80c63443026c)

</details>

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iOS 17.0` using version `1.62 (24.2.7.10)`

Test Plan: https://github.com/brave/brave-core/pull/21813#issuecomment-1922497211

<details><summary>Youtube.com Homepage</summary>

1. new profile
2. load youtube.com
3. stay logged out
4. click around
5. return to youtube.com
6. reload with desktop version
7. click around
8. return to homepage

- Ensured no ads are shown when returning to youtube.com homepage using mobile and desktop versions.

Example | Example
-|-
![IMG_1277](https://github.com/brave/brave-ios/assets/17885425/08b1e4a7-8828-4e95-b61f-74e2566fbd58) | ![IMG_1278](https://github.com/brave/brave-ios/assets/17885425/a96aaf31-76bf-473b-a20a-f4e9f7cfe003)

</details>

<details><summary>Direct URLs</summary>

- Ensured loading youtube URL does not present ads.

![IMG_1288](https://github.com/brave/brave-ios/assets/17885425/d24eb6b9-b3b2-4479-99b9-5ee50f6dd6a9)

</details>

<details><summary>Searches</summary>

1. Use search on homepage, observe results
2. Change site to desktop version, use search
3. Play video from search results

- Ensured no ads are present in the search results page on youtube.com
- Ensured no ads when playing video from search results page.

Example | Example
-|-
![IMG_1290](https://github.com/brave/brave-ios/assets/17885425/239cf7c3-1dab-4c2a-bec4-633cfb574bff) | ![IMG_1291](https://github.com/brave/brave-ios/assets/17885425/ebbe28e9-1710-4ae8-a410-70229d8d6cc1)

</details>

<details><summary>Live</summary>

- Ensured ads are not shown when viewing Live videos

![IMG_1289](https://github.com/brave/brave-ios/assets/17885425/342b9c4d-5592-4eab-b2f1-d0928e9a7784)


</details>

<details><summary>Movies</summary>

- Ensured viewing movies on youtube.com does not present ads
- Ensured that seeking does not cause ads to be shown

Example | Example
-|-
![IMG_1278](https://github.com/brave/brave-ios/assets/17885425/bed22b11-748d-408d-9875-d31e1a16a143) | ![IMG_1280](https://github.com/brave/brave-ios/assets/17885425/0465b1a1-aae3-4c18-9bab-c1b9dce3bda1)


</details>

<details><summary>Shields Off</summary>

- Ensured ads are shown when Shields are disabled or Ad-blocking is disabled in the shields panel.

Example | Example
-|-
![IMG_1285](https://github.com/brave/brave-ios/assets/17885425/22466e42-53ef-4050-89b6-2207fc0a80ce) | ![IMG_1286](https://github.com/brave/brave-ios/assets/17885425/f4d7df2c-eb30-4374-9974-9ff0611f3cc9)


</details>
