### ISSUE TITLE
Screen Time option does not appear in settings

### ISSUE THREAD

**Issue by dwwmmn** [brave/brave-ios#8760]
### Description: 

Going to Settings > Brave Shields & Privacy should show an option to enable or disable Screen Time, but there is no such option.

### Steps to Reproduce 
  1. Enable Screen Time in the Settings app by navigating to Screen Time > App Limits > Add Limit.
  2. In Brave navigate to Settings > Brave Privacy & Shields.

### Actual result: 

![image](https://github.com/brave/brave-ios/assets/4575591/03f75109-a25a-4805-904a-502ac430ab45)
![image](https://github.com/brave/brave-ios/assets/4575591/b56ef9d2-ad5f-405f-ae59-fbb02e1013b8)
![image](https://github.com/brave/brave-ios/assets/4575591/fa801687-c18d-4b3e-8df2-19a96be9e99d)

### Expected result:

There should be a toggle to disable or enable interaction with Screen Time.

### Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced.

Tried: re-installing Brave, enabling and disabling system-wide Screen Time, adding and removing individual websites from tracking, looking in other menus in case the setting was moved.

### Brave Version: 

Version 1.61.1 (24.1.4.20) BraveCore 1.61.102 (120.0.6099.71) Device iPhone14,7 (iOS 17.2.1)

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? *Yes*

### Device details: 

iPhone 14, iOS 17.2.1 (21C66)

### Website problems only:
- did you check with Brave Shields down? *Yes*
- did you check in Safari/Firefox (WkWebView-based browsers)? *N/A*

### Additional Information

N/A

**Comment by dwwmmn** [comment]
Sorry I didn't see #8601 somehow. We can just close this if needed. When is the feature planned for re-release?

**Comment by iccub** [comment]
ScreenTime had bugs and we had to disable it temporarily.
In 1.62 which should go live next week we re-add this setting.
For now it's disabled by default so just remember to enable it after upgrading to 1.62

If all goes well we are reenabling it for users in 1.63
