### ISSUE TITLE
Buy/Send/Swap not opening from Asset Details 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#8774]
Refer https://github.com/brave/brave-browser/issues/36266 for test plan. Issue logged for verification purpose

**Comment by kjozwiak** [comment]
Closing a duplicate as per https://github.com/brave/brave-ios/issues/8776#issuecomment-1970041691. We'll be releasing the above via the `1.62.1` HF which will include the new `Jitsi SDK`.
