### ISSUE TITLE
1.62.1 Hotfix Issues

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#8775]
# 1.62.1 Planning

## Included

_**Wallet Asset Detail Fix**_

- [x] https://github.com/brave/brave-browser/issues/36266

**_Jitsi Upgrade_**

- [x] https://github.com/brave/brave-browser/issues/36353

**_URL Bar Secure Content_**

- [x] https://github.com/brave/brave-browser/issues/36024

**_ASA Linkage_**

- [x] https://github.com/brave/brave-browser/issues/36326

## Not Included

**_Security Issues_**

- ~~https://github.com/brave/brave-browser/issues/36092~~

- ~~https://github.com/brave/brave-browser/issues/36259~~

**_Youtube Black Screen_**

- ~~https://github.com/brave/brave-browser/issues/36064~~

**Comment by kjozwiak** [comment]
Closing the above as we decided to include the following issues after a discussion via the weekly `iOS` planning/triage call:

* Buy/Send/Swap not opening from Asset Details #8776
* Update JitsiSDK to 8.6.3 #8777
* Url bar falsely showing insecure state in 1.62+ #8778
* Problem ASA Custom Onboarding Linked Screen #8779
