### ISSUE TITLE
Buy/Send/Swap not opening from Asset Details

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#8776]
## Description: 

Buy, send and swap are not opening for some assets when tapped in Asset Details. The bug seems to occur on any asset with no account balance.

## Steps to Reproduce 
  1. Open Wallet
  2. Scroll Portfolio to find ETH on Optimism.
      - Seems to occur on any asset where user does not have any account balance
  3. Tap 'Buy'
  4. Observe buy does not open
      - Buy/send/swap do not open either
      - Some other assets do open as expected. Needs investigation.

## Actual result: 

https://github.com/brave/brave-browser/assets/5314553/c8a5ae71-652c-4e63-9130-86e3e8f27804

## Reproduces how often: [Easily reproduced, Intermittent Issue]

Easily reproduced with ETH on Optimism, not all assets failing to open.

## Brave Version: 

v1.62 App Store

- Can you reproduce this issue with the most recent build from TestFlight? 
- Can you reproduce this issue with the previous version of the current build from TestFlight? 
- Can you reproduce this issue with the current build from AppStore? 

### Device details:

iPhone 14 Pro iOS 17.3.1

### Website problems only:
- Does the issue resolve itself when disabling Brave Shields?
- Is the issue reproducible on the latest version of Mobile Safari? 

### Additional Information

Community report: 
https://community.brave.com/t/i-cannot-send-or-swap-crypto/532738/3

**Comment by soner-yuksel** [comment]
This ticket is copy of https://github.com/brave/brave-browser/issues/36266. It is created by the request of Quality Assurance team for tracking purposes of hotfix.

**Comment by kjozwiak** [comment]
Thanks @soner-yuksel 👍 Labelling https://github.com/brave/brave-browser/issues/36266 as `QA/No` and `release-notes/exclude` as it will be verified via `1.62.1` using the `brave-ios` repo. @srirambv also verified the issue via `master` using the `brave-core` repo as per https://github.com/brave/brave-core/pull/22229#issuecomment-1963412013. Also closing https://github.com/brave/brave-ios/issues/8774 as a duplicate as we decided to include the fix in the `1.62.1` HF.

**Comment by srirambv** [comment]
Verification passed on iPhone 13 with iOS 17.4 running 1.62.1 (24.2.28.21)
- Verified steps from [brave/brave-core#22229](https://github.com/brave/brave-core/pull/22229)
- Verified Buy/Send/Swap buttons work as expected and loads correct screen when opened from asset details screen

https://github.com/brave/brave-browser/assets/17010094/dc1534a3-ae97-48a6-bb3c-a1511eef1f11
