### ISSUE TITLE
Update JitsiSDK to 8.6.3

### ISSUE THREAD

**Issue by soner-yuksel** [brave/brave-ios#8777]
This resolves couple of bugs we have like joining conferences with many participants.

**Comment by soner-yuksel** [comment]
This ticket is copy of https://github.com/brave/brave-browser/issues/36353. It is created by the request of Quality Assurance team for tracking purposes of hotfix.

**Comment by kjozwiak** [comment]
Closing as the above was merged/added into `1.62.1` as per https://bravesoftware.slack.com/archives/C06UXF3KJ/p1709156791608489. QA originally went through the above using a `0.0` build as per https://github.com/brave/qa-resources/issues/559#issuecomment-1961734101, https://github.com/brave/qa-resources/issues/559#issuecomment-1962155578, https://github.com/brave/qa-resources/issues/559#issuecomment-1963509985 & https://github.com/brave/qa-resources/issues/559#issuecomment-1964430570.

@hffvld @Uni-verse we'll need to run through a few spot checks just to make sure that there's no obvious regressions now that the SDK was merged into `1.62.x`. I wouldn't waste time going through the same thorough checks as we already verified the SDK via `0.0` but it's definitely worth checking just to make sure it works within `1.62.x`. @srirambv mind quickly spot checking the `Web3` portion?

We'll probably also need to run through quickly spot check via `1.65.x` just to make sure that builds build via `brave-core` are working well with the new SDK before we uplift into `1.64.x` & `1.63.x` via https://github.com/brave/brave-core/pull/22344 & https://github.com/brave/qa-resources/issues/559. However, at that point, we can label https://github.com/brave/brave-browser/issues/36353 as `QA/No` and `release-notes/exclude` it's technically going out via `1.62.1`.

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.3.1` using version `1.62.1 (24.3.28.21)`

- Ensured `talk.brave.com` is working.
- Ensured using different orientations in call does not cause problems.
- Ensured Car Mode, Low Bandwidth Mode is working. 
- Ensured `talk.brave.software` is working.
- Ensured PIP is working.

Example | Example | Example | Example | Example | Example | Example
-|-|-|-|-|-|-
![IMG_5763](https://github.com/brave/brave-ios/assets/17885425/47044c08-39aa-4179-8fc9-5e98b3170374) | ![IMG_5764](https://github.com/brave/brave-ios/assets/17885425/100708f1-b295-4c3d-9651-02792bfb4f78) | ![IMG_5765](https://github.com/brave/brave-ios/assets/17885425/b78b81d1-98c3-4693-b7e1-826f4afc556d) | ![IMG_5766](https://github.com/brave/brave-ios/assets/17885425/959a388c-7289-4e1e-aaf5-e3d740fad080) | ![IMG_5767](https://github.com/brave/brave-ios/assets/17885425/91257041-2f90-425f-a0c0-621354203f09) | ![IMG_5768](https://github.com/brave/brave-ios/assets/17885425/19a15cdd-6308-4f36-94e4-116874a78b92) | ![IMG_5769](https://github.com/brave/brave-ios/assets/17885425/a80b1d2c-f79a-4841-99ac-12e7291c651e)

**Comment by Uni-verse** [comment]
Verified on `iPad (7th Gen)` running `iOS 17.0` using version `1.62.1 (24.3.28.21)`

- Ensured `talk.brave.com` is working.
- Ensured using different orientations in call does not cause problems.
- Ensured Car Mode, Low Bandwidth Mode is working. 
- Ensured `talk.brave.software` is working.
- Ensured PIP is working.

Example | Example | Example | Example | Example
-|-|-|-|-
![IMG_1295](https://github.com/brave/brave-ios/assets/17885425/f59ab088-79ae-48e5-82e5-5a48bb01d2d3) | ![IMG_1296](https://github.com/brave/brave-ios/assets/17885425/9b939989-20d9-4d32-b727-c3894832f02c)| ![IMG_1300](https://github.com/brave/brave-ios/assets/17885425/1d7d30ab-0734-4d8c-a966-4ae42cd3ae98) | ![IMG_1301](https://github.com/brave/brave-ios/assets/17885425/581c300a-e494-420a-85e0-faeb4ddcaa3c) | ![IMG_1305](https://github.com/brave/brave-ios/assets/17885425/82732664-2ebc-4b03-aa91-c5c04c380f4f)
