### ISSUE TITLE
[1.62.2] Error interstitial pages are not loaded

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#8789]
### Description: 

See https://github.com/brave/brave-browser/issues/36688

### Steps to Reproduce  
  1. Visit `expired.badssl.com`
  2. Visit a non-existent URL such as `dsafdsafd.brave.com`

### Actual result:
The page fails to load

### Expected result:
Error page interstitial should be shown

### Reproduces how often: 
Easily

### Brave Version:
1.62.1+

**Comment by Uni-verse** [comment]
Verified on `iPhone 12` running `iOS 17.3.1` using version `1.62.2 (24.3.11.17)`

- Verified test plans in https://github.com/brave/brave-ios/issues/8789#issue-2180032660 & https://github.com/brave/brave-browser/issues/36688#issue-2179272053 on fresh and upgraded profiles.
- Ensured that error interstitial pages are loaded on `https://badssl.com`
- Ensured that `https://www.synology.com`, `https://openwrt.org`, `portainer.io` and other self-signed SSL Certificate websites are loading successfully

Error url | Badssl.com | Badssl.com | Synology | OpenWRT | Portainer
-|-|-|-|-|-
![IMG_5814](https://github.com/brave/brave-ios/assets/17885425/e752096d-7c31-4269-a4cb-ee28b0a89258) | ![IMG_5815](https://github.com/brave/brave-ios/assets/17885425/1d725f3b-832d-481e-b323-1dd796b7560c) | ![IMG_5816](https://github.com/brave/brave-ios/assets/17885425/06d7210b-bedd-416f-a6ed-970148baf9ea) | ![IMG_5817](https://github.com/brave/brave-ios/assets/17885425/432bd5c9-9fb7-4dbd-9274-4369191e9a96) | ![IMG_5818](https://github.com/brave/brave-ios/assets/17885425/281445db-d980-42d9-bd8b-791809b03005) | ![IMG_5819](https://github.com/brave/brave-ios/assets/17885425/233a1ce6-2ce5-4ad4-b5ea-285de9affd47) | ![IMG_5820](https://github.com/brave/brave-ios/assets/17885425/eb9cfa15-7f8e-4319-aa38-86743a357dd5)
