### ISSUE TITLE
Update Favorites Graphic Resizing

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#88]
See: https://github.com/brave/brave-ios/pull/54/files#r200178171

**Comment by iccub** [comment]
It's added already, I forgot to remove the old method so it still showed in the PR.

**Comment by jhreis** [comment]
Closing per above. Change link:
https://github.com/brave/brave-ios/pull/54/files#diff-298a0530860f6c00ef6053b1637da019R69
