### ISSUE TITLE
Focus set to new tab when using "Open in Brave"

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#881]
### Description: 
Focus set to new tab when using "Open in Brave". Found while testing #630 

### Steps to Reproduce 
  1. Set Brave to use PB only and remove from memory
  2. Open a 3rd party app and open a link in Brave via share sheet
  3. Brave opens 2 tab one new tab and second tab with the link, focus automatically set to empty new tab

**Actual result:** 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/17010094/52464004-2742e280-2b9f-11e9-9a16-e42b4a8bcc63.gif)

**Expected result:**
Should always focus on the tab that is opening the link 

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.8 (19.02.07.22)

**Device details:** 
iPhone 7+ (iOS 12.1.2)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
Is this actually just a private browsing issue?

**Comment by kylehickinson** [comment]
Couldn't reproduce this issue on development following the STR

**Comment by kylehickinson** [comment]
@srirambv Please re-verify

**Comment by srirambv** [comment]
Closing the issue as not able to reproduce it any more.
