### ISSUE TITLE
Exiting PB mode causes normal tab to become blank with incorrect URL 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#888]
### Description: 
Exiting PB mode causes normal tab to become blank with incorrect URL 

### Steps to Reproduce 
  1. Open any link in a new tab
  2. Long press on a link on the page and open in new tab
  3. Switch to the new tab by tapping on the background tab, do not use the switch button 
  4. Open the same link or different link from step 2 in a new private tab
  5. Open tab container and exit private mode by clicking on the `Private` button on the bottom left 
  6. Close the second tab from step 3 by swiping the tab to left/right in tab container
  7. Open the tab from step 1, URL bar has URL which was opened in a new tab/private tab, entire tab is blank but tab title is correct. URL uses the dark mode private tab colour for normal tab
  8. Reload the tab just changes the URL to correct value, page doesn't load
  9. Current tab is useless have to remove app from memory and relaunch to reuse the tab  

**Actual result:** 
![iospb](https://user-images.githubusercontent.com/17010094/52547942-d62a2d00-2df0-11e9-867c-f7155ac371f6.gif)

**Expected result:**
Should switch back to normal tabs correctly

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.8(19.02.07.22)

**Device details:** 
All devices 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Is this a regression?

**Comment by srirambv** [comment]
No this is not a regression. Happens on Appstore build as well.

**Comment by srirambv** [comment]
Not a regression so moving to 1.9

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13 running 1.12(19.09.05.20)
* Verified steps from original issue description on a clean install
* Verified that issue reproduced on 1.11.4 and not reproducible after upgrade to 1.12(19.09.05.20)

Verification **PASSED** on `iPad Air 3rd Generation` using `iOS 13.1` running `1.12 (19.09.11.22)`:

* Verified steps from original issue description on a clean install
* Verified that issue reproduced on `1.11.4` and not reproducible after upgrade to `1.12 (19.09.11.22)`

Verification passed on iPhone 7+ with iOS 12.4.1 running 1.12(19.09.13.06)
* Verified steps from original issue description on a clean install
* Verified that issue reproduced on 1.11.4 and not reproducible after upgrade to 1.12(19.09.05.20)
