### ISSUE TITLE
'Open With' Offers only Chrome and Safari

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ios#889]
### Description: 
A user reports that 1.7.4 only offers to open links in Chrome or Safari.

**Actual result:** 

![image](https://user-images.githubusercontent.com/815158/52551328-9be56f00-2da1-11e9-9286-bbb800b488af.png)

**Expected result:**
The user should be able to open the resource in Brave.

**Reproduces how often:**
Easily reproduced.

**Brave Version:** 
1.7.4 (TBD)

**Device details:** 
TBD

**Comment by srirambv** [comment]
Brave comes up on share menu. This would be a good options as well

**Comment by iccub** [comment]
This is Google's custom popup on youtube to manipulate users to install their app
