### ISSUE TITLE
Brave on iOS Overrides Firefox’s “New Tab” on Today extension

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#890]
https://my.pcloud.com/publink/show?code=XZdE4l7ZHlLjDPOUsajjEiswKV6GSyBextVX

### Description: 
Tapping "New Tab"/"New Private Tab" on Firefox's Today extension opens in Brave instead

### Steps to Reproduce 
  1. 3D Touch Firefox app icon to open today extension (or add today extension to widgets list)
  2. Tap new tab/new private tab

**Actual result:** Opens Brave
**Expected result:** Opens Firefox
**Reproduces how often:** Always
**Brave Version:** 1.7.4 Live

## Solution Research

It seems that Firefox uses `MozInternalURLScheme` in Info.plist which Brave may still be accidentally registering post re-fork/1.7.

Seen here: https://github.com/mozilla-mobile/firefox-ios/blob/cde7291029ce8710396aa217021f456e54744077/Extensions/Today/TodayViewController.swift#L110

**Comment by kylehickinson** [comment]
For now set label as `release-notes/exclude` but we could include it if we wanted to bring attention to it (Probably not needed)

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+ running 1.9(19.3.9.1)
   - Verified new tab button in add widget doesn't launch Brave
   - Verified new tab button force touch option doesn't launch Brave 

Verified passed with 1.9 (19.3.9.1) on iPhone SE
* Verification passed on iPhone 8 running 1.9(19.3.9.1)
   - Verified new tab button in add widget doesn't launch Brave
   - Verified new tab button force touch option doesn't launch Brave
