### ISSUE TITLE
Add option to clear tabs on exit/swipe remove

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#893]
### Description: 
Add option to clear tabs on exit/swipe remove. Should be a setting option to clear tab when app is removed from memory

### Additional Information 
Feature requested on community  https://community.brave.com/t/option-to-close-tabs-on-exiting-i-e-swipe-closing-the-app/44582

Marking to 2.0 UX. 
cc: @jamesmudgett to consider adding this for the 2.0 UI

**Comment by danielholmhansen** [comment]
2.5 years later and nothing has happened yet :)

Please implement the option. The private view does this automatically, but has other disadvantages as it kind of just is an all-in-one close/delete everything solution. So being able to choose this as an option in settings on normal view would be nice.

**Comment by schrodyn** [comment]
Is this feature ever going to happen?
