### ISSUE TITLE
Cleanup iOS Search Engines

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#895]
Match:
https://github.com/brave/brave-browser/issues/3316

iOS Search Repo:
https://github.com/brave/Brave-iOS-SearchPlugins

Search engines to support:
- Google
- DDG
- Qwant
- StartPage
- Bing (_excluded_ from `tr`, `ru`, `th`)
- Yandex (_included_ in `tr`, `ru`, `kk`, `be`)
- Any pre-set search engines
> on iOS there is a search engine for "normal" browsing and one for "Private", so maybe up to 2 additional search engines.

- Infogalactic will be completely dropped regardless of user's set engine in either mode.

**Comment by kjozwiak** [comment]
Waiting for https://github.com/brave/brave-ios/issues/920 to be resolved before verifying.

**Comment by LaurenWags** [comment]
Using iPad 5th Gen and 1.8 (19.2.26.22) on Test Flight:
- Verified test cases 1, 2, 3 from https://github.com/brave/brave-core/pull/1648 for US, France, Germany for both Normal and Private tab search engines. (Additional testing notes can be found at https://github.com/brave/brave-ios/issues/920#issuecomment-468017657)
- Verified Bing customizations for the following regions: Turkey (language=Turkish), Russia (language=Russian), Thailand (language=Thai). Note, for Thailand Google was default search engine. Other two had Yandex as default.
- Verified Yandex customizations for the following regions: Turkey (language=Turkish), Russia (language=Russian), Kazakhstan (language=Russian), and Belarus (language=Russian). Note, for these countries Yandex was the default search engine not Google. 
Note - Bing/Yandex customizations use language, but Qwant customization uses region. 
- Verified if Infogalactic was set as search engine for Normal or Private tab, when updated to 1.8 it was replaced with the region's default search engine. Verified for US, France, and Germany regions.

Verified using iPhone SE, Brave 1.8 (19.2.26.22) on Test Flight.

**Comment by kjozwiak** [comment]
Went through the above cases that @LaurenWags outlined using the following devices:

* `iPad Mini 4` running `iOS 12.1.4`
* `iPhone 6s+` running `iOS 12.1.4`
