### ISSUE TITLE
Cookies deleted when `Block-all-cookies` is toggled on and then off

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#897]
### Description: 
`Block all cookies` should not delete cookies.

### Steps to Reproduce 
  * Navigate to `http://dustiest-limitation.000webhostapp.com/first_party.html` - sets all storage
  * Navigate to `http://dustiest-limitation.000webhostapp.com/data.html` - no storage api calls here
  * Turn on `Block all cookies`.
  * Navigate to `http://dustiest-limitation.000webhostapp.com/view.html` - to check if storage is not available
  * Turn off `Block all cookies`.
  * Refresh `http://dustiest-limitation.000webhostapp.com/view.html` - to check if storage is available

**Actual result:** 
Cookies are deleted

**Expected result:**
Cookies should not be deleted

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

cc: @danishjafri88

**Comment by kjozwiak** [comment]
@jumde @joe looks like http://dustiest-limiation.000webhostapp.com/first_party.html doesn't exist anymore. Is there any other sites/STR that we can use to verify that this has been fixed?

**EDITED**:

There was a type in the original STR, links should be the following:

* http://dustiest-limitation.000webhostapp.com/first_party.html
* http://dustiest-limitation.000webhostapp.com/data.html

**Comment by jumde** [comment]
> @jumde @joe looks like http://dustiest-limiation.000webhostapp.com/first_party.html doesn't exist anymore. Is there any other sites/STR that we can use to verify that this has been fixed?

@kjozwiak - Updated the issue, there was a typo: http://dustiest-limitation.000webhostapp.com/first_party.html

**Comment by kjozwiak** [comment]
@jumde hmmm I don't think this is working :( Either the issue wasn't fixed, or the STR that we're using are not correct. Here's the STR that I'm following:

* Navigate to http://dustiest-limitation.000webhostapp.com/first_party.html
* Navigate to http://dustiest-limitation.000webhostapp.com/view.html
* ensure that `Cookies` display `stp=stp` & `Local Storage` displays `stp`
* Enable `Block All Cookies` via `Settings`
* Refresh http://dustiest-limitation.000webhostapp.com/view.html (`Cookies` & `Local Storage` should be blank)
* Disable `Block All Cookies` via `Settings`
* Refresh http://dustiest-limitation.000webhostapp.com/view.html (`Cookies` should display `stp=stp` & `Local Storage` should display `stp`)

But once I disable `Block All Cookies` after I've enabled it, I'm getting the following:

![IMG_9809](https://user-images.githubusercontent.com/2602313/61478828-71a36900-a960-11e9-8905-12a0c53197db.PNG)

**Comment by jumde** [comment]
> @jumde hmmm I don't think this is working :( Either the issue wasn't fixed, or the STR that we're using are not correct. Here's the STR that I'm following:
> 
> * Navigate to http://dustiest-limitation.000webhostapp.com/first_party.html
> * Navigate to http://dustiest-limitation.000webhostapp.com/view.html
> * ensure that `Cookies` display `stp=stp` & `Local Storage` displays `stp`
> * Enable `Block All Cookies` via `Settings`
> * Refresh http://dustiest-limitation.000webhostapp.com/view.html (`Cookies` & `Local Storage` should be blank)
> * Disable `Block All Cookies` via `Settings`
> * Refresh http://dustiest-limitation.000webhostapp.com/view.html (`Cookies` should display `stp=stp` & `Local Storage` should display `stp`)
> 
> But once I disable `Block All Cookies` after I've enabled it, I'm getting the following:
> 
> ![IMG_9809](https://user-images.githubusercontent.com/2602313/61478828-71a36900-a960-11e9-8905-12a0c53197db.PNG)

@kjozwiak - http://dustiest-limitation.000webhostapp.com/first_party.html was initially setting a session cookie, I've updated the code to set a normal cookie. @danishjafri88 and I verified on a TF build, it works. Let us know if you're still running into any issues.

**Comment by kjozwiak** [comment]
* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`
   * went through the STR outlined under https://github.com/brave/brave-ios/issues/897#issuecomment-512913241 and ensured that both `Local Storage` and `Cookies` are restored when enabling/disabling `Block All Cookies`

![IMG_9808](https://user-images.githubusercontent.com/2602313/61484658-5b4fda00-a96d-11e9-99ba-119cc61cc3f8.PNG)

* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.16.23)
   * went through the STR outlined under https://github.com/brave/brave-ios/issues/897#issuecomment-512913241 and ensured that both `Local Storage` and `Cookies` are restored when enabling/disabling `Block All Cookies`
![IMG_23236666B440-1](https://user-images.githubusercontent.com/28145373/61485431-26dd1d80-a96f-11e9-903b-5c9f9240fc8f.jpeg)
