### ISSUE TITLE
Update functionality of clearing cache and clearing cookies

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#898]
### Description: 
From: https://github.com/brave/brave-ios/pull/883#issuecomment-462992521

Update: `Clear cookies`  to `Cookies & site data` to clear cookies, local storage, cache, &c all together.

cc: @tomlowenthal @danishjafri88

**Comment by diracdeltas** [comment]
Option A:

1. make the "Clear Cache" switch only clear cache data types - looks like that is already done in https://github.com/brave/brave-ios/pull/883/files#diff-4bac6a5edc33f19d87eed145642db0a8R78
2. make the "Clear cookies" switch clear all data types

Option B: just combine them into a single "Clear cookies and cache" switch that clears all data types

the rationale is that @tomlowenthal mentioned he expects clearing cookies to also clear caches which can be kind of used like a cookie

**Comment by jumde** [comment]
Personally I prefer option A, while debugging site issues i've often run into situations where i'd like the only the cache to be cleared.

**Comment by srirambv** [comment]
Based on discussion with @jumde marking the issue as `QA/No`
