### ISSUE TITLE
Block Scripts

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#90]
```
let baseRule = [{'trigger':{'url-filter':'.*','resource-type':['script']},'action':{'type':'block'}}]
```

Main place of complication here regards domain exceptions.

If Global Script Blocking (GSB) is `off` a `blacklist` of domains must be tracked.

If GSB is `on` a `whitelist` of domains must be tracked.

---

Whenever GSB is changed, all domain-specific script settings are left alone.

Whenever a domain exception is created, it i stored in CoreData, and the adblock script rule rebuilt and reloaded. During rebuilding, CD is quiried to build the `blacklist`/`whitelist`

Domain flags will be tracked in CoreData:

`shield_noScript`
`shield_allOff`

```
let domainString = Domain.domainAndScheme(fromUrl: url)
let basePredicate = NSPredicate(format: "url == %@", domainString)

...

// Gives us `whitelist` if GSB is on
// Gives us `blacklist` if GSB is off
let exceptionListPredicate = NSPredicate(format: "shield_noScript == \(!shield_allOff)")
let exceptionListDomains = // ...
```

The new baseRule ends up being:

```
let baseJSON = [{'trigger':{'url-filter':'.*','resource-type':['script']},'action':{'type':'block'}}]

let exceptionListKey = GSB.isOn ? "unless-domain" : "if-domain"
baseJSON["trigger"][exceptionListKey] = exceptionListDomains

// Reload Lists

// Refresh Tab
```

There are two situations that blocking logic must be handled.

- On creation of a tab's webview (can happen beyond just tab creation), content rules must be loaded into the webview's configuration
- Reloaded on change

**Comment by jhreis** [comment]
This is part of shields implementation and has not been started. There is a shields epic: https://github.com/brave/brave-ios/issues/29
