### ISSUE TITLE
Play media in Background or with Screen Off

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#902]
## Description
While playing music/podcasts/audio, if you lock your iPhone or press the Home button, the music or video stops. 

Requested on community https://community.brave.com/t/no-background-video-playing-on-iphon/45273
and a personal +1 on having this feature for at least 2.0

## Expected Result
Update the app so that playing music/podcasts/audio files in background is allowed similar to Android.

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/youtube-won-t-play-in-background/50037?u=eljuno

**Comment by judge2020** [comment]
Note that Apple/Google may push back if the iOS app adds background play: 

https://www.macrumors.com/2017/09/04/youtube-app-protube-pulled-from-app-store/

I would still like to see this added. If there are issues, it could be included as a different target for those who can sideload.

**Comment by danishjafri88** [comment]
There are two known issues, 
1. iOS by default pauses video in webviews when app is in background until user explicitly plays them from control center.
Str: 
Open any video(NOT Youtube) and go to background. (iOS pauses it)
Open control center and play the video

2. Crash on Lock screen:
Happens with the code in #1068 
-> Allow playback in background in settings
-> Play a video
-> lock screen
-> Wait

This issue stems from the fact that we have an encrypted CoreData DB. This encryption is enforced when the phone is locked or when the app is not running. Any attempt to write while its locked results in app crash.

**Comment by eljuno** [comment]
+1 from Community https://community.brave.com/t/iphone-unable-to-watch-youtube-video-audio-clip-on-brave-while-making-display-off-or-phone-locked/90522?u=eljuno

**Comment by jhgorse** [comment]
The "Private Browser with Adblock" app can play video audio in the background for iOS.

**Comment by iccub** [comment]
Closing in favor of playlists https://github.com/brave/brave-ios/issues/902

**Comment by jhgorse** [comment]
What is a playlist?

**Comment by iccub** [comment]
@jhgorse a new app feature that allows you to watch audio or video in background, in offline mode etc.
The feature will be live for users very soon
