### ISSUE TITLE
Pull-to-Refresh functionality

### ISSUE THREAD

**Issue by kenijo** [brave/brave-ios#916]
Now that Brave for iOS is rewritten with a new architecture, could be please expect to see pull-to-refresh back, similarly to what is available on Chrome?
And pull-to-create new tab / pull-to-close tab as well?

**Comment by srirambv** [comment]
Personal +1 for pull down reload. Its a handy feature when using the device in one hand

**Comment by kylehickinson** [comment]
Design confirmed by @jamesmudgett:

- Feature would be controlled by a user preference under the "General" section in Settings. The toggle would have the copy `Enable Pull-to-refresh` and would be enabled by default and the icon would be the same as the refresh icon in the URL bar.
- Pull-to-refresh is only active on non-local/error pages, so you won't be able to pull to refresh on badssl warnings and such

Known Issues that we're ok with for the first iteration:
- This uses the system API for reload, which `WKWebView` doesn't "officially" support. There is a small jump that occurs when you refresh using pull-to-refresh where the `WKWebView` likely resets the scroll origin so it doesn't animate as nicely back down (or hold until the user lets go of the scroll)
- Doesnt work on websites that take over scrolling (twitter timelines for instance) 
- Its a bit janky on pages that stick things to the header (like YouTube/Reddit), and you can't see the refresh control

Fixing these issues would require a much more extensive Pull-to-refresh implementation that doesn't rely on the system API

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.29(21.7.16.17)
- Verified able to do a pull down reload of a page 
- Verified new setting `Enable Pull-to-refresh` is available in settings under General
- Verified setting is enabled by default on clean install and upgrade
- Verified disabling the setting doesn't do a pull down reload of the page
- Verified pull down reload doesn't work on error pages irrespective of the setting state
- Verified enable/disable setting doesn't ask for a restart
------------
Verification passed on iPhone 7+ with iOS 14.5.1 running 1.29(21.7.16.17)
- Verified able to do a pull down reload of a page 
- Verified new setting `Enable Pull-to-refresh` is available in settings under General
- Verified setting is enabled by default on clean install and upgrade
- Verified disabling the setting doesn't do a pull down reload of the page
- Verified pull down reload doesn't work on error pages irrespective of the setting state
- Verified enable/disable setting doesn't ask for a restart
------------
Verification passed on iPad Pro with iOS 14.6 running 1.29(21.7.16.17)
- Verified able to do a pull down reload of a page 
- Verified new setting `Enable Pull-to-refresh` is available in settings under General
- Verified setting is enabled by default on clean install and upgrade
- Verified disabling the setting doesn't do a pull down reload of the page
- Verified pull down reload doesn't work on error pages irrespective of the setting state
- Verified enable/disable setting doesn't ask for a restart

**Comment by fsheidaiee** [comment]
Hi its a mandatory option to disable pull to refresh specially for dex users with mouse and keyboard in android.
please make that option available again.
thank
