### ISSUE TITLE
Disable FP still blocks items and doesn't load page

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#917]
### Description: 
Disable FP still blocks items and doesn't load page

### Steps to Reproduce 
  1. Upgrade to 1.8
  2. Enable FP globally
  3. Visit giphy.com and open a gif
  4. Check shields, shows 3 blocked FP 
  5. Disable FP from shields, still shows  blocked items
  6. Toggle FP setting again for the the page to actually load the gif image

**Actual result:** 
Disable FP still blocks items and doesn't load page

**Expected result:**
Disable FP should load the page correct and not block any more items

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.8(19.2.20.22)

**Device details:** 
iPad and iPhone

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
@jhreis marking this for 1.9. Not a blocker but not desirable as well but workaround is to toggle the setting again

**Comment by BekzhanKaspakov** [comment]
During my tries to reproduce this issue I stumbled upon a bug when FP button in settings becomes useless(toggling brings no effect on FP) after toggling same button in shields. Should that be filed as separate issue?
Also could you please provide some other website for reproducing this issue, because giphy.com is blocked in my country?

**Comment by BekzhanKaspakov** [comment]
Disregard my previous comment. I realized that this was intentional functionality. The settings in shields are specific for a website they were toggled on.

**Comment by jhreis** [comment]
The fix for this ticket was reverted due to breaking adblocking.
