### ISSUE TITLE
Navigations to `about:` domains from standard URLs should go to `about:blank`

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#92]
STR:

- Navigate to a server with html

```
<script>
  window.location.href = 'about:preferences';
</script>
```

**Comment by jhreis** [comment]
What is the current behavior, and what is expected on the about:blank page?

**Comment by jumde** [comment]
Looks like `about:` URLs on iOS are not mapped to user pages similar to Desktop. Closing. Sorry for the false alarm.
