### ISSUE TITLE
Default search engines that were removed are being reverted to region defaults

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#920]
### Description: 

Upgrading `1.7.4 (19.02.01.22)` --> `1.8 (19.02.20.22)` will always revert the search engine to the regions default (either Google/Qwant) even though the user has already picked another default from the preexisting list.

### Steps to Reproduce 

  1. download `1.7.4 (19.02.01.22)` from the App Store and open Brave
  2. change the default search engine to `Amazon` and the PB default to `Yahoo`
  3. upgrade to `1.8 (19.02.20.22)` using the `ipa` file that was provided
  4. relaunch brave and you'll notice that the default search engine is either Google/Qwant

**Actual result:** 

Currently reverting the default search engine to either Google/Qwant every time.

**Expected result:**

If a user has selected another search engine from the preexisting list, we should honour that choice.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

Upgrading from 1.7.4 (19.02.01.22)` --> `1.8 (19.02.20.22)`

**Device details:** 

Used `iPad Mini 4 running iOS 12.1.4`

**Comment by srirambv** [comment]
Don't think this is a blocker or expected behaviour. Since user sets a different SE which is not on approved list, we should not retain it, reason being iOS doesn't allow adding/removing SE similar to b-c. We should only use the list of approved SE list irrespective of what is set.

**Comment by kjozwiak** [comment]
Definitely a blocker as we should never revert users search engines, even if they're removed from Brave. This is even more problematic with iOS due to not being able to re-add search engines. This is the same behaviour b-c is using and should be the same behaviour on iOS/android as per earlier discussions with @rebron and others when implementing the above spec/work.

**Comment by LaurenWags** [comment]
Verified passed when updating from 1.7.3 (19.1.23.19) on Test Flight to 1.8 (19.2.26.22) on Test Flight using iPad 5th Gen. Verified STR for US, France, and Germany regions for both Normal and Private tab search engines.

**Comment by btlechowski** [comment]
Verification passed on when updating from 1.7.3 (19.1.23.19) to 1.8 (19.2.26.22) on Test Flight using iPhone SE. Regions tested: Poland, US, Germany, Russia.

**Comment by kjozwiak** [comment]
Verification **PASSED** on `iPad Mini 4` and `iPhone 6s+` using `iOS 12.1.4`. Went through the following:

* Upgraded from `1.7.3 (19.1.23.19)` to 1.8 `(19.2.26.22)` using TF (Canada/Germany/France)
* ensured that search engines for both regular tabs/PB weren't reset even though the default search engines were removed due to the refactor

Went through the above cases at least 10 times on each device using different combination of search engines.
