### ISSUE TITLE
Blocking too much content in Japan

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#923]
### Description: 

We have received info that our shields are too aggressive in Japan and are blocking legitimate content. 

### Examples 

See _**Ad Blocking Complaints from Japan**_ Google Doc in Brave Drive

**Comment by Teay1985** [comment]
issue

**Comment by anthonypkeane** [comment]
We have an internal process for this now. I'll share info soon

**Comment by anthonypkeane** [comment]
closing as this is being tracked https://bravesoftware.slack.com/archives/C2FQMN4AD/p1560293669058700
