### ISSUE TITLE
Disable 3p dynamic HSTS | Expect-CT | PKP headers

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#925]
### Description: 
Headers like "Strict-Transport-Security", "Expect-CT", "Public-Key-Pins", "Public-Key-Pins-Report-Only" can be used for fingerprinting in 3p context. 

For more info: https://github.com/brave/brave-browser/issues/3419

### Repro steps:

1. Disable HTTPS Everywhere
2. Navigate to `https://jsfiddle.net/x5mqb807/` - This loads content from `avatars2.githubusercontent.com` which sets the `Strict-Transport-Security` header.

**Comment by tildelowengrimm** [comment]
Is the solution that we'll *remember* headers set by third parties but only apply them to first parties, or that we'd only remember or apply when the site is a first party?

**Comment by jumde** [comment]
See: https://github.com/brave/browser-laptop/issues/12223#issuecomment-353670524

**Comment by ShivanKaul** [comment]
[Public Key Pins](https://udn.realityripple.com/docs/Web/HTTP/Headers/Public-Key-Pins) and [Expect-CT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT) are deprecated headers, and for HSTS, we follow Safari which does partition the [HSTS cache](https://privacytests.org/ios.html).
