### ISSUE TITLE
adding bookmarks after updating visually replaces older ones in the UI (restores after re-opening bookmarks)

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#927]
### Description: 

When updating from `1.7.4 (19.02.01.22)` to `1.8 (19.2.26.22)`, adding bookmarks after the update will start visually replacing other bookmark/folders that have already been created.

It's a UI issue and it doesn't actually replace the other already added bookmarks. Closing/Reopening settings/bookmarks will return everything back to a normal state.

### Steps to Reproduce 
  1. download `1.7.4 (19.02.01.22)` from App Store
  2. add a folder in bookmarks and add a random website into the newly created folder
  3. add a random bookmark in the root directory
  4. update to `1.8 (19.2.26.22)` using an `ipa` file
  5. once updated, go to another random website and attempt to add the bookmark
  4. you'll notice it will replace either the folder or the root bookmark in the UI
  5. close/re-open bookmarks and it and everything will be restored

**Actual result:** 

Example of the issue occurring: https://youtu.be/CcLls9xv2-M

**Expected result:**

Bookmarks should be added without having any strange behaviour where the UI replaces the folder

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible using the above STR.

**Brave Version:** 

Upgrading from `1.7.4 (19.02.01.22)` to `1.8 (19.2.26.22)` (using the `ipa` file)

**Device details:** 

* `iPad Mini 4 running iOS 12.1.4` - Reproduced
* `iPhone 6s+ running iOS 12.1.4` - Reproduced

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by iccub** [comment]
Great find, thanks @kjozwiak

**Comment by kjozwiak** [comment]
Verification **PASSED** using the following devices:

* `iPad Mini 4 running iOS 12.1.4` - **PASSED**
* `iPhone 6s+ running iOS 12.1.4` - **PASSED**

Went through the following cases:

* ensured that the original issue mentioned in https://github.com/brave/brave-ios/issues/927#issue-415407855 has been resolved when upgrading from `1.7.4 (19.02.01.22)` to `1.8 (19.02.28.23)`
* ensured that creating bookmark folders, adding bookmarks within folders, removing folders, removing folders with bookmarks, adding bookmarks to the root folder, opening bookmarks, removing bookmarks worked under `1.8 (19.02.28.23)`.

Verification passed using iPhone SE, build 1.8(19.2.28.23). 
Updated 1.7.3(19.1.23.19) with 1.8(19.2.28.23). Verified that bookmarks, cookies, session, per site shield settings, global settings, search engines, passwords were retained after install.
Verified that bookmark manager works.

Verification passed using iPad 5th Gen using 1.8 (19.02.28.23)
Also went through the following upgrade case:
* with 1.7.4 from app store: added bookmarks, history, tabs, stats, cookie, login/password, site specific shield settings, added custom sites to ‘favorites/top site tiles’
* set default search engine to DDG for Normal and Private tabs
* updated using 1.8 ipa file
* verified version change (1.7.4 -> 1.8) and the following were retained: bookmarks, history, tabs, stats, cookie, login/password, site specific shield settings, custom sites in ‘favorites/top site tiles’, search engine setting. Active Tab was not maintained (this is a known issue https://github.com/brave/brave-ios/issues/736).
