### ISSUE TITLE
Disable file:// URLs

### ISSUE THREAD

**Issue by jumde** [brave/brave-ios#93]
STR:

- Navigate to file://opt

**Comment by jhreis** [comment]
What is the expected behavior? Error? Redirect somewhere else?

**Comment by jumde** [comment]
- Safari on iOS shows an alert
- Opera navigates to the default search engine
- Chrome just shows `Download Failed`

I think alert might be too intrusive, navigating to default search engine sounds good?

**Comment by tmancey** [comment]
@jhreis @jumde Has the expected behaviour been agreed please so I can update the description

**Comment by tmancey** [comment]
@anthonypkeane Could you please see my comment on August 22nd, so we can unblock

**Comment by anthonypkeane** [comment]
@tmancey 

If a user navigates to file:// we should take the user to the “home” screen

![IMG_2B596D90CF64-1.jpeg](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/452bb63e-4068-424b-a463-07a2a98cf6bf)

**Comment by jhreis** [comment]
@anthonypkeane and clear out the URL? Maybe would feel like a bug if the user enters a custom URL, and it brings then to the home screen and removes the URL?

**Comment by iccub** [comment]
This seems to work now, navigating to file:// url leave you where you were before, home screen or a website you are on
