### ISSUE TITLE
Displaying an incorrect favicon in the Tab window

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#933]
### Description: 
We are displaying a cached or incorrect favicon in the tab window

See the favicon icon for macrumurs.com  in the image below

![IMG_1843.PNG](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/03b6fc41-7374-4309-9308-5b1c0829a286)

**Comment by jhreis** [comment]
@anthonypkeane Please follow the template to make sure you provide the information we need here.

**Comment by kylehickinson** [comment]
@anthonypkeane Have you seen this issue come up since? Can this be closed?

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.5 running 1.18(20.06.09.18)
- Verified correct favicon is shown in tab tray
- Verified switching from private tabs to normal doesn't cause  any issue with tab favicon 
------
Verification passed on iPhone 7+ with iOS 13.5.1 running 1.18(20.06.09.18)
- Verified correct favicon is shown in tab tray
- Verified switching from private tabs to normal doesn't cause  any issue with tab favicon 
------
Verification passed on iPad Pro with iOS 12.4.5 running 1.18(20.06.09.18)
- Verified correct favicon is shown in tab tray
- Verified switching from private tabs to normal doesn't cause  any issue with tab favicon
