### ISSUE TITLE
Add back github search engine

### ISSUE THREAD

**Issue by Jacalz** [brave/brave-ios#935]
### Description: 
The recent update `1.8` removed a lot of the search engines and I would love if you could add back the GitHub one, I used it a lot and I know more people who did. It was great and set you out from other browsers. I am not saying that you should add back all of them but GitHub is so drastically different from the others and an incredibly useful tool for open source contributors and developers alike...

### Steps to Reproduce 
  1. Go to search engine settings and notice that GitHub is gone...

**Actual result:** 
Go GitHub search engine.

**Expected result:**
Should have a GitHub search engine.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
v1.8 (19.02.28.23)
 
**Device details:** 
Doesn't matter

**Comment by cndouglas** [comment]
#936 (Add support for OpenSearch) would be a good long term solution.

**Comment by iccub** [comment]
Did you have GH search set as a default or have you used it while typing a url and then choosing it from the list above the keyboard?

**Comment by Jacalz** [comment]
I used it as a quick search engine over the keyboard...

**Comment by jhreis** [comment]
As @Liunkae pointed out, we'll address this with: https://github.com/brave/brave-ios/issues/936
This will support GitHub as well as any other website that supports OpenSearch.
