### ISSUE TITLE
Add support for OpenSearch

### ISSUE THREAD

**Issue by cndouglas** [brave/brave-ios#936]
Users should be able to add websites as search engines if they support the [OpenSearch standard](https://developer.mozilla.org/en-US/docs/Web/OpenSearch). This would allow users to add custom search engines, which is helpful now that many search engines have been removed from settings.

This feature is already supported by Brave Core (desktop).

For example, GitHub supports OpenSearch. Every page on GitHub has a `<link rel="search"` tag in the `<head>` of its HTML:
```HTML
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="GitHub">
```

The linked XML file (https://github.com/opensearch.xml) contains the URL format for search terms:
```XML
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/" xmlns:moz="http://www.mozilla.org/2006/browser/search/">
<ShortName>GitHub</ShortName>
<Description>Search GitHub</Description>
<InputEncoding>UTF-8</InputEncoding>
<Image width="16" height="16" type="image/x-icon">https://github.com/favicon.ico</Image>
<Url type="text/html" method="get" template="https://github.com/search?q={searchTerms}&ref=opensearch"/>
<moz:SearchForm>https://github.com/search</moz:SearchForm>
</OpenSearchDescription>
```

**Comment by anthonypkeane** [comment]
James, we'll need some UI here

**Comment by cndouglas** [comment]
<s>Here's an OpenSearch parser class from the Firefox Focus iOS app:
https://github.com/mozilla-mobile/focus-ios/blob/master/Blockzilla/OpenSearchParser.swift</s>

Edit: The actual upstream source is https://github.com/mozilla-mobile/firefox-ios/blob/master/Client/Frontend/Browser/OpenSearch.swift, and @danishjafri88 points out that it is already included in https://github.com/brave/brave-ios/blob/development/Client/Frontend/Browser/Search/OpenSearch.swift

**Comment by danishjafri88** [comment]
@Liunkae The parser class is in brave-ios too. Thanks for the help anyways!!

**Comment by jhreis** [comment]
UI will be inherited from FF, see https://github.com/brave/brave-ios/issues/586 for some more internal information.

**Comment by danishjafri88** [comment]
@jhreis of #582 & #495 only #582 has UI which I have incorporated. #495 Only lets you edit(reorder/delete) the table datasource. There is no UI to add a custom engine like FF.

**Comment by maxwowpow** [comment]
It's a good manner to put at least some kind of workaround to the thread. Many features are supported indirectly through other extension/options etc.

The DuckDucksGo "!bang"-search can do this already, so kind of can brave. If we set/use duckduckgo as a search engine, than typing "`!gi nike`" will bring me google image search of nikes.
If I type "`!gh kodi`" I'll find myself right on the github search result page for that.

Maybe people (new other users) could be made aware of this and use this in the meantime. Through the documentation and marketing/website e.g.

https://duckduckgo.com/bang

(of course just clicking a custom search engine icon for mostly used engines is more productive 🥇 )

**Comment by jhreis** [comment]
Good info @maxgrass. I think part of this is to allow people to add Reddit, Amazon, Ebay, whatever else as a search engine. Power-user commands like you list are definitely useful too!

**Comment by pde** [comment]
What's the time-frame for getting this done? Could you please (pretty please) revert the removal of previously available search engines if this ui isn't done and about to ship?

**Comment by pde** [comment]
And @maxgrass that tip is creative though unfortunately it takes five accurate taps on ios to type something like  "!w ", plus the extra latency of dns, tcp, and tls handshakes to ddg, which is a lot on slow networks. So the ux remains far worse than brave previously provided.

**Comment by mandar-brave** [comment]
@anthonypkeane @janypiotrowski we need to prioritize this to P1.

**Comment by bsclifton** [comment]
+1 from https://twitter.com/samlustgarten/status/1282215397832327170 - whether it was OpenSearch or just being able to manually add a search engine

**Comment by szaimen** [comment]
Would love to see this, too!

**Comment by orkunkl** [comment]
Any updates?

**Comment by isaacjara17** [comment]
Any updates? It is my favorite possible feature

**Comment by soner-yuksel** [comment]
An updated test plan and change details can be found 
https://docs.google.com/document/d/1ujsC_pNCdHGxsq_o-2Tzsyn91o_x5pheA-0hP8GBV7g/

**Comment by srirambv** [comment]
Search for Open Search/ Manual Search Engine Addition in GDrive for additional information about the spec and details for test plan.

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4 running 1.24 (21.3.17.16)
- Verified test plan from https://github.com/brave/brave-ios/pull/323 

   <details>
   <summary><b>Case 1</b></summary>

   * Verified websites that support open search shows a `Add search Engine` button
   <br>

   GitHub | Wikipedia
   -- | --
   ![image](https://user-images.githubusercontent.com/17010094/111626856-5bf5df00-87e6-11eb-8598-9cc1f7982514.png) | ![image](https://user-images.githubusercontent.com/17010094/111626882-60ba9300-87e6-11eb-9be6-a37307669b26.png)
   
   * Verified tapping on the `Add Seach Engine` button asks for confirmation to add 
   
   GitHub | Wikipedia
   -- | --
   ![image](https://user-images.githubusercontent.com/17010094/111632736-b2feb280-87ec-11eb-9570-1116d11d8405.png) | ![image](https://user-images.githubusercontent.com/17010094/111632763-b98d2a00-87ec-11eb-9a86-bf6bc76c0f08.png)

   
   * Verified adding a SE shows confirmation toast message
   
   GitHub | Wikipedia
   -- | --
   ![image](https://user-images.githubusercontent.com/17010094/111633530-85fecf80-87ed-11eb-81a7-0d67383582da.png) | ![image](https://user-images.githubusercontent.com/17010094/111633389-5c45a880-87ed-11eb-8a07-3fc737643196.png)

   </details>

   <details>
   <summary><b>Case 2</b></summary>
   <br>
   <details>
   <summary><b>Auto Add</b></summary>
  
    - Verified entering a site that supports open search automatically enables the `Add` button and can add the site to SE list
   <br>

    https://user-images.githubusercontent.com/17010094/111629421-2d2d3800-87e9-11eb-9ff1-80837faf29f9.MP4

   </details>
  
   <details>
   <summary><b>Manual Add</b></summary>

   - Verified able to manually add a site to custom SE list
   <br>

   https://user-images.githubusercontent.com/17010094/111631867-d117e300-87eb-11eb-8121-aea5c8305101.MP4


   - Verified trying to re-add the same SE via manually throws error
    <br>

    https://user-images.githubusercontent.com/17010094/111631731-a9287f80-87eb-11eb-89c2-c2ff04da7e69.MP4


   </details>
   </details>
   <details>
   <summary><b>Case 3</b></summary>
   
   - Verified custom SE can be set as default SE
   - Verified adding custom SE as default still retains it in the custom list
   - Verified able to reorder the SE in SE list or quick search list
   - Verified able to swipe delete the Custom SE
   - Verified able to delete SE by clicking on edit 
  </details>
--------------------
Verification passed on iPhone XR with iOS 13.5 running 1.24 (21.3.17.16)
- Verified test plan from https://github.com/brave/brave-ios/pull/323 

   <details>
   <summary><b>Case 1</b></summary>

   * Verified websites that support open search shows a `Add search Engine` button
   <br>

   GitHub | Wikipedia
   -- | --
   ![image](https://user-images.githubusercontent.com/17010094/111657861-bea9a380-8803-11eb-9ff2-50b1ed2585f4.png) | ![image](https://user-images.githubusercontent.com/17010094/111657893-c5d0b180-8803-11eb-8a96-44833aa72d80.png)

   * Verified tapping on the `Add Seach Engine` button asks for confirmation to add 
   
   GitHub | Wikipedia
   -- | --
   ![image](https://user-images.githubusercontent.com/17010094/111657964-d4b76400-8803-11eb-8d70-8364e9b05430.png) | ![image](https://user-images.githubusercontent.com/17010094/111657932-cd905600-8803-11eb-971f-0878091ff7e4.png)
   
   * Verified adding a SE shows confirmation toast message
   
   GitHub | Wikipedia
   -- | --
   ![image](https://user-images.githubusercontent.com/17010094/111658015-df71f900-8803-11eb-8af0-ab497a29a5b3.png)  | ![image](https://user-images.githubusercontent.com/17010094/111658037-e6990700-8803-11eb-9137-f96503f5f638.png)


   </details>

   <details>
   <summary><b>Case 2</b></summary>
   <br>
   <details>
   <summary><b>Auto Add</b></summary>
  
    - Verified entering a site that supports open search automatically enables the `Add` button and can add the site to SE list

    https://user-images.githubusercontent.com/17010094/111660888-70e26a80-8806-11eb-80df-f0f5197edca5.MP4

   <br>
  </details>
  
   <details>
   <summary><b>Manual Add</b></summary>

   - Verified able to manually add a site to custom SE list
   <br>

    https://user-images.githubusercontent.com/17010094/111661086-a12a0900-8806-11eb-8127-c920df98dca1.MP4

   - Verified trying to re-add the same SE via manually throws error
    <br>

    https://user-images.githubusercontent.com/17010094/111660936-7dff5980-8806-11eb-84c1-450841725ff5.MP4

   </details>
   </details>
   <details>
   <summary><b>Case 3</b></summary>
   
   - Verified custom SE can be set as default SE
   - Verified adding custom SE as default still retains it in the custom list
   - Verified able to reorder the SE in SE list or quick search list
   - Verified able to swipe delete the Custom SE
   - Verified able to delete SE by clicking on edit 
  </details>

**Comment by 3nprob** [comment]
For normal tabs this works fine once configured. However, the option is not available private tabs at all. That is quite significant.

More minor, one is restricted to the defaults on startup, with no indication that alternatives are possible.

Testflight 1.24 (21.3.17.17)
