### ISSUE TITLE
Password lockout timer doesn't disappear after a certain amount of time

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#938]
### Steps to Reproduce 
  1. Set pass code
  2. Close the app and reopen it to show the password prompt
  3. Enter wrong password 3 times
  4. Close the app, wait 15 minutes. Try to keep the app in memory, don't launch other apps etc.
  5. Open the app again

**Actual result:** 
You can't enter a password after waiting 15 minutes

**Expected result:**
You should be able to enter password after a lockout time is over

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information 
Technical note: this is due to fact that the code for presenting the lockout does not go away when opening the app from foreground. It works if you kill the app and reopen it. 
The responsible VC most likely needs to observe for `UIApplicationWillEnterForeground`

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+ (iOS 12.3.1) running 1.10(19.07.08.19)
  - Verified able to unlock after the lockout timer is reset  

* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.12.14)
  - Verified able to unlock after the lockout timer is reset
