### ISSUE TITLE
Ensure sync code words/qr code doesn't get stuck while generating

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#942]
### Description: 
Some times sync code words/qr code may take time to generate causing the sync screen to be blank

### Steps to Reproduce 
  1. Enable sync
  2. Create a new sync chain
  3. Code word/QR code sometime doesn't show up

**Actual result:** 
![file](https://user-images.githubusercontent.com/17010094/53915159-6e50b600-402d-11e9-82d8-4d7f9b3021dd.jpg)

**Expected result:**
Should always generate code words/qr code

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent. Ran into this only twice but cant consistently reproduce

**Brave Version:** 
1.9(19.3.2.15)

**Device details:** 
iPhone 7+ (iOS 12.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by LaurenWags** [comment]
* Verified passed with 1.9 (19.03.25.21) on iPad 5th Gen using STR from description.
* Verification passed on iPhone 6/7 and iPad pro running 1.9(19.3.25.21)
* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR.
* Verification passed on iPhone 8 running 1.9(19.3.25.21)
* Verification passed on iPhone SE running 1.9(19.3.25.21)
