### ISSUE TITLE
Bookmarks added in offline mode doesn't sync to all devices

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#943]
### Description: 
Bookmarks added in offline mode doesn't sync to all devices

### Devices
Device 1: iPhone 7+
Device 2: iPhone 6

### Steps to Reproduce 
  1. Create a sync chain on device 1 and sync device 2 using QR code
  2. Visit a site in device 1 and put it on airplane mode
  3. Bookmark the site on device 1 and give a custom name 
  4. Visit the same site from step2 in device 2 when online and bookmark
  5. Bookmark from device 2 is sync'd to device 1, but bookmark from added in offline mode doesn't sync to device 2

**Actual result:** 
Device 1:
![file 2](https://user-images.githubusercontent.com/17010094/53915707-73facb80-402e-11e9-91b9-1cc304b411af.jpg)

Device 2:
![file 1](https://user-images.githubusercontent.com/17010094/53915710-765d2580-402e-11e9-9d7a-5dd13d2df513.jpg)

**Expected result:**
All bookmarks must be sync'd when all devices are online

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.9(19.3.2.15)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
What if you update the failing bookmark after turning off plane mode? 
Is it sent to other device then?

**Comment by srirambv** [comment]
>What if you update the failing bookmark after turning off plane mode?

Its not failing bookmark. Its just added as a bookmark when device is offline

Updating that bookmark sync everything instantly, that is added to the sync chain in offline mode.

**Comment by srirambv** [comment]
Ran into anther scenario while testing this 
1. Device 2 add a bookmark in offline mode and edit as `ESPN offline`
2. Add the same bookmark in device 1 and edit it as `ESPN offline` as well
3. Device 1 duplicates the bookmark but then removes one of them
4. Device 2 keeps the two bookmarks 

Device 1
![file 2](https://user-images.githubusercontent.com/17010094/53971813-9c84d300-40cb-11e9-91eb-a1a15a0e5095.jpg)

Device 2
![file 1](https://user-images.githubusercontent.com/17010094/53971781-85de7c00-40cb-11e9-9f53-d0ac58fb2b75.jpg)
