### ISSUE TITLE
Device removed when offline doesn't get removed from the sync chain

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#944]
### Description: 
Device removed when offline doesn't get removed from the sync chain

### Devices
Device 1: iPhone 7+
Device 2: iPhone 6

### Steps to Reproduce 
  1. Create sync chain on device 1
  2. Sync device 2 using QR code, ensure both devices are listed in each other
  3. Put device 1 on offline mode, remove device 1 from sync chain on device 1
  4. Sync device 1 again to the sync chain by scanning QR code on device 2
  5. Both devices show device 1 twice 

**Actual result:** 
Device removed when offline doesn't get removed from the sync chain

**Expected result:**
Changes made offline should propagate when devices are online

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.9 (19.02.03.15)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by LaurenWags** [comment]
Verified passed with 1.9 (19.03.25.21) on iPad 5th Gen using STR from description. Was unable to remove a device from sync chain when in offline mode.
![IMG_0293](https://user-images.githubusercontent.com/28145373/55011442-40bbb480-4fbc-11e9-8d0f-d69dd49bfbc3.PNG)

Verified passed with 1.9 (19.03.25.21) on iPhone 8 using STR from the description. Step 3 - was unable to remove a device from sync chain when the device is in offline mode.
![Device offline](https://user-images.githubusercontent.com/38657976/55024523-0df9d680-5025-11e9-9bb3-f2c86df71008.png)

Verification passed on iPhone 7+/ iPhone 6 and iPad Pro all running 1.9(19.3.25.21). Trying to remove sync during offline shows the error message 
iPad Pro
![image](https://user-images.githubusercontent.com/17010094/55092927-da04cc80-5089-11e9-8625-978dafd55581.png)
iPhone 6 
![image](https://user-images.githubusercontent.com/17010094/55093042-07517a80-508a-11e9-83f9-8c75095dcdeb.png)
iPhone 7+
![image](https://user-images.githubusercontent.com/17010094/55092953-e4bf6180-5089-11e9-8fc4-9cdf4b974ce1.png)

* Verification **PASSED** with `1.9 (19.3.27.19)` on `iPad Mini 4` using the above STR. Was unable to remove a device from sync chain when device was offline.
