### ISSUE TITLE
Bottom nav disappears when creating new tab and dismissing keyboard

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#947]
Steps to Reproduce (add as many as necessary):

Press + for new tab from new tab screen
Tap anywhere on screen to remove keyboard
Actual Result (gifs and screenshots are welcome!):

See the recording: https://discourse-cdn-sjc1.com/business4/uploads/brave/original/3X/4/b/4b0331a5753960e60dc6db688ab202f31b0ac58c.MP4

Expected result:

I should be able to view my tabs via the switcher, not have to tap on another tab to then reach it

Reproduces how often:

Brave Version(See the About Brave page in Settings):

iOS Brave 1.8

Mobile Device details

iPhone XS Max

Android/iOS Version

iOS 12.2 (latest public beta)

**Comment by iccub** [comment]
This seems to be working on current build

**Comment by srirambv** [comment]
This seems to work only when you do a swipe outside the keyboard frame to hide it. Instinctively user would tap outside the keyboard to dismiss it which is still not recognized only swipe is. We should capture the tap as well outside the keyboard and dismiss it. Even better solution(may be not possible) is to bring the keyboard up above the bottom bar that way we can eliminate the tap/swipe outside the keyboard.

Reopening the issue and moving out of 1.12 milestone

**Comment by kylehickinson** [comment]
@srirambv  I can't seem to reproduce this. Is this still an issue?

**Comment by srirambv** [comment]
@kylehickinson  yes this still reproduces but I am ok closing this issue as working as expected and reopen it if any user complains about it. Seems like Safari doesn't recognise the tap as well only registers swipe outside the keyboard.
