### ISSUE TITLE
1Password Activity doesn't appear in share sheet

### ISSUE THREAD

**Issue by kylehickinson** [brave/brave-ios#948]
### Description: 

When you tap the share button on the a web page, the 1Password activity should be showing up if the user has 1Password installed and has the activity enabled in share sheets.

### Steps to Reproduce 
  1. Visit any login page (or any page really)
  2. Tap the share button

**Actual result:** 1Password is missing from that list
**Expected result:** 1Password should be in that list
**Reproduces how often:** Easily
**Brave Version:** 1.8 Live

**Comment by jvaleski** [comment]
To be clear, this is only an issue when there is an external keyboard (e.g. Bluetooth) connected to the iOS device. This is a big problem on iPads (where users often have BT keyboards connected).

https://community.brave.com/t/unable-to-access-1password-from-activites-share-menu-on-ios/42023/5

**Comment by multiformeingegno** [comment]
+1
Actually this is always a problem, not just when there is an external keyboard connected.

**Comment by scqawk** [comment]
I would add that the iOS wide password fill option isn’t presented with iOS split keyboard on iPad, either. However, the standard keyboard has the password select option... the share sheet extension would work around these issues.

**Comment by SeanDunford** [comment]
Experiencing this as well with latest brave. 


Originally 1Password came up in share menu. 


Then in a later version there was an icon that appeared on top of the keyboard. 


Now it seems that iOS’ own password menu above the keyboard appears instead of the brave one password bar.

**Comment by LaurenWags** [comment]
* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.12.14). Verified STR from description.

![IMG_071E4060EB28-1](https://user-images.githubusercontent.com/28145373/61251133-98c32600-a727-11e9-8cf2-167b2b2dd8d5.jpeg)

* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`
   * logged into several websites using `1Password` without any issues

![IMG_9810](https://user-images.githubusercontent.com/2602313/61484401-e8466380-a96c-11e9-8d1e-c8923c2e0f83.PNG)
