### ISSUE TITLE
Editing bookmarks/folder in iOS doesn't propagate to Desktop 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#951]
### Description: 
Editing bookmarks/folder in iOS doesn't propagate to Desktop 

### Devices
Device 1: Ubuntu 18.04 running `0.61.47 `
Device 2: iPhone 7+ running 1.9.(19.3.6.15)

### Steps to Reproduce 
  1. Import bookmarks into desktop profile before enabling sync
  2. Create sync chain on desktop and add iPhone to the chain using QR code
  3. Ensure all bookmarks from desktop is sync'd to the mobile
  4. Edit bookmark folder name on iPhone, Edit bookmark title on iPhone
  5. Changes don't propagate to desktop
  6. Add a new bookmark on iPhone to force sending records, still bookmark/folder from step 4 doesn't show up on desktop 

**Actual result:** 
Desktop folder names unchanged
![screenshot from 2019-03-08 10-27-52](https://user-images.githubusercontent.com/17010094/54038084-ad961880-418d-11e9-9100-8ed7d6da8d58.png)

Edited bookmark title doesn't change on desktop
![screenshot from 2019-03-08 10-33-10](https://user-images.githubusercontent.com/17010094/54038108-bbe43480-418d-11e9-87a8-397dbafb678a.png)

Folder names changed on iPhone
![file 3](https://user-images.githubusercontent.com/17010094/54038164-de764d80-418d-11e9-9cdb-b64bf3f2ca08.jpg)

Bookmark title edited on iPhone
![file 4](https://user-images.githubusercontent.com/17010094/54038204-f51ca480-418d-11e9-9326-3ad964070560.jpg)

**Expected result:**
Any changes made on iPhone too bookmarks or folders should propagate to all devices on the chain

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by LaurenWags** [comment]
* Verified passed with 1.9 (19.03.25.21) on iPad 5th Gen using STR from description.
* Verified passed with 1.9 (19.03.25.21) on iPhone 8 using STR from description
* Verification passed on iPhone 6/iPhone 7+ and iPad pro all running 1.9(19.3.25.21)
* Verification passed on iPhone 6, running 1.9 (19.03.25.21)
* Verification **PASSED** with `1.9 (19.3.27.19)` on `iPad Mini 4` using the above STR.
