### ISSUE TITLE
Swipe gesture on bookmark hanger is difficult when its at last bookmark

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#953]
### Description: 
Swipe gesture on bookmark hanger is difficult when its at last bookmark

**Actual result:** 
![123](https://user-images.githubusercontent.com/17010094/54041462-c4406d80-4195-11e9-892f-d40c586ee25d.gif)

**Expected result:**
Better handling of swipe up/down gesture on bookmark hanger

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
All

**Device details:** 
All

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by jhreis** [comment]
This will all be replaced pretty soon, so going to block for now.

**Comment by jhreis** [comment]
Going to allow a fix for this, and we'll re-address more fully with the new menu.

**Comment by LaurenWags** [comment]
* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.12.14). Verified STR from description.
* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`
