### ISSUE TITLE
Regional adblock option showing for English locale

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#959]

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+ running 1.9(19.3.25.21)
  - Verified no regional adblock shown in settings for English locale
  - Verified regional adblock option shows up and enabled by default when a different locale is set

* Verified passed with 1.9 (19.03.25.21) on iPad 5th Gen using test plan from https://github.com/brave/brave-ios/pull/961
 - Verified no regional adblock shown for English language:

![IMG_EBF9D1B2B672-1](https://user-images.githubusercontent.com/28145373/55005741-e9fdad00-4fb2-11e9-810b-18820fdfac2f.jpeg)

* Verified regional adblock shown for another (French) language:

![IMG_A9FB823E97F8-1](https://user-images.githubusercontent.com/28145373/55005750-ed913400-4fb2-11e9-83d8-d09ae4400bef.jpeg)

* Verification passed on iPhone 8 running 1.9(19.3.25.21)
  - Verified no regional adblock shown in settings for English locale

![English - No regional ad block](https://user-images.githubusercontent.com/38657976/55021874-8067b800-501f-11e9-90d9-007f7a7335cc.png)

* Verified regional adblock option shows up and enabled by default when a different locale is set

![Spanish - Regional Adblock](https://user-images.githubusercontent.com/38657976/55021892-878ec600-501f-11e9-9e52-bd5ffdeed999.png)

* Verification passed on iPhone 6 running 1.9(19.3.25.21)
  - Verified no regional adblock shown in settings for English locale
  - Verified regional adblock option shows up and enabled by default when a different locale is set

* Verification **PASSED** with `1.9 (19.3.27.19)` on `iPad Mini 4` using the above STR.
  - Verified no regional adblock shown in settings for English locale
  - Verified regional adblock option shows up and enabled by default when a different locale is set
