### ISSUE TITLE
Latest update removed Wikipedia search?

### ISSUE THREAD

**Issue by pde** [brave/brave-ios#960]
With the latest Brave iOS release, the Wikipedia quick-search engine disappeared. It was very useful as a shortcut, and it's very distressing that it's gone.

**Comment by Jacalz** [comment]
Looks like they cleaned out most of the search engines which is both annoying and incredibly frustrating for people who used te almost every day.

**Comment by srirambv** [comment]
Open search will be implemented which will allow to add custom SE's 

https://github.com/brave/brave-ios/issues/586, https://github.com/brave/brave-ios/issues/936

**Comment by pde** [comment]
I saw the recent Brave update, but didn't see a way to reenable Wikipedia or add new custom search engines?

**Comment by pde** [comment]
Even if there is some hidden UI for adding custom search engines, I'd recommend adding a few common search engines back in, because they're more discoverable for users in that form, and a super useful feature that sets Brave ahead of most other mobile browsers.

**Comment by Jacalz** [comment]
Yeah I totally agree with @pde about adding back a couple common search engines. It makes it way easier for users and it would set brave a part from most other browsers. I would recommend adding back for example Wikipedia and Github...

**Comment by pde** [comment]
@tomlowenthal want to reopen?

**Comment by tildelowengrimm** [comment]
You'll be able to customize your list of search engines. We're not planning to change the default search engine list.

**Comment by pde** [comment]
That's really a shame, and is causing worse experiences for your users :(

**Comment by isaacjara17** [comment]
> You'll be able to customize your list of search engines

Well that was over a year agor. When will this feature come to Brave? I would absolutely love it
