### ISSUE TITLE
x callback URL's appear to be broken

### ISSUE THREAD

**Issue by anthonypkeane** [brave/brave-ios#968]
### Description: 
A user reported that there is an issue in V1.8 where x callback URL's are not working

![image.png](https://images.zenhubusercontent.com/5b919b7b7859ca34f6abcb40/510c2632-e480-41c6-a060-618274e21294)

**Comment by kylehickinson** [comment]
Is there an example of the URL they're trying to use?

**Comment by iccub** [comment]
Closed due to inactivity and no more details provided

**Comment by jhreis** [comment]
They are talking about https://app-talk.com/about/ I believe. I am going to leave this closed, but something to keep in mind in case this comes up again.
