### ISSUE TITLE
In Private window `Open Image In New Tab` opens the image in a Normal tab

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/brave-ios#969]
### Description: 
In Private window `Open Image In New Tab` opens the image in a Normal tab

### Steps to Reproduce 
  1. Open a private window
  2. Open any webpage
  3. Hold the image and Tap `Open Image In New Tab`

**Actual result:** 
The image opens in a Normal tab

**Expected result:**
The image should open in a private tab

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Always

**Brave Version:** 

1.8
**Device details:** 
iPhone 8

**Website problems only:**
- did you check with Brave Shields down? NA
- did you check in Safari/Firefox (WkWebView-based browsers)? NA

### Additional Information 
The issue is reported by the community

https://community.brave.com/t/in-private-browsing-open-image-in-new-tab-opens-the-image-in-a-regular-tab/48541

**Comment by srirambv** [comment]
* Verification passed on iPhone 7 running  1.9(19.3.25.21)
* Verified passed with 1.9 (19.03.25.21) on iPad 5th Gen
* Verified passed with 1.9 (19.03.25.21) on iPhone 8
* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR.
* Verification passed on  iPhne 6 running 1.9(19.3.25.21)
* Verification passed on  iPhone SE running 1.9(19.3.25.21)
