### ISSUE TITLE
Fingerprint Protection

### ISSUE THREAD

**Issue by jhreis** [brave/brave-ios#97]
**What is browser FP**
It it the collection of as many browser identification points as possible at a website that can then be later matched against the browser characteristics of known people and track their activity.

**FP techniques**
- Cookies and tracking
- Canvas Fingerprinting.
**Canvas FP**
Canvas FP is done by creating a hidden canvas on the document and draw a known text (mostly with some colour/font pattern) on it. Then the canvas html apis(ToDataURL) are used to get the Base64 encoded representation of binary pixel data. A hash of this data is used as a fingerprint.
**WebGL FP**
It is done in similar fashion like Canvas FP, but utilises the JS graphics api to generate fingerprint from 3D objects identifying the GPU etc.
More details on https://browserleaks.com/ and https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js

**Implementing FPP**
To block FP certain JS api's are overridden so as to not provide any system characteristics. A js script is injected into the browser before page load (in some cases it may be good to inject even after page load). This disallows the website JS scripts from accessing the device info.

**How to do it in 1.7**
 The FPP js script is in browser-ios codebase: browser-ios/brave/src/page-hooks/FingerprintingProtection.js

The FPP script should be injected into the user script folder, and enabled/disabled similarly to how image blocking works:

```
webView?.evaluateJavaScript("window.__firefox__.NoImageMode.setEnabled(\(enabled))")
```

Rather than adding/removing the script, change a "FPP" flag that gives the script enough info to know what to do.

**How good is current script**
Passes following:
https://amiunique.org ✅
https://browserleaks.com ✅
But fails in https://panopticlick.eff.org ❌

Results are same as old codebase ie browser-ios. 
Future release should encompass blocking of other ways of FP.

**Comment by tmancey** [comment]
This ticket is blocked with development as needs further information
