### ISSUE TITLE
Rename Sync to Brave Sync on settings screen

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#973]
This String needs to be translated so we won't include this in 1.9 release

![54379775-6cf04080-4660-11e9-930a-473a1d016a9a](https://user-images.githubusercontent.com/6950387/54386488-59150080-4699-11e9-89f5-fa18441700c9.jpeg)

**Comment by srirambv** [comment]
Its Sync (beta) on Android 
![image](https://user-images.githubusercontent.com/17010094/54387342-83eb5e80-4671-11e9-971e-cc22a6478524.png)
and Sync on desktop 
![image](https://user-images.githubusercontent.com/17010094/54387314-6a4a1700-4671-11e9-83c2-185a88ef91f0.png)


We should probably have the same naming as Android. 

cc: @anthonypkeane

**Comment by srirambv** [comment]
Moving this into 1.10 release. Its blocking  #719

**Comment by LaurenWags** [comment]
* Verified passed on iPad 5th Gen (iOS 12.3.1) running 1.10 (19.07.12.14)

![IMG_837F84D10C60-1](https://user-images.githubusercontent.com/28145373/61155205-4c28e200-a4be-11e9-9a0a-b6d1cceb6d07.jpeg)
Encountered and logged https://github.com/brave/brave-ios/issues/1248

* Verification **PASSED** on `iPhone 6s+ running iOS 12.3.1` using `1.10 (19.07.16.23)`
   * As per https://github.com/brave/brave-ios/issues/1252, it was reverted from `Brave Sync` -> `Sync`

![IMG_9783](https://user-images.githubusercontent.com/2602313/61464843-f41e2f80-a944-11e9-800a-3655dcd5403f.PNG)
