### ISSUE TITLE
unable to create a new sync group

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#977]
### Description: 
Found while testing https://github.com/brave/brave-ios/issues/447, #845 

In the scenario below, I get the message 'Unsuccessful Unable to create a new sync group'.

### Steps to Reproduce 
1. Install 1.9
2. Add some bookmarks and folders (I had two folders with one bookmark in each, and one loose bookmark)
3. Delete one of the bookmark folders
4. Open settings and navigate to Sync
5. Tap on ‘Start a new Sync Chain’
6. Tap on Computer

**Actual result:** 
Get message that says Unsuccessful Unable to create a new sync group.
![IMG_EF69321B0F0C-1](https://user-images.githubusercontent.com/28145373/54455975-61217e80-4733-11e9-89d2-a84f3effeee3.jpeg)

**Expected result:**
No error, able to create sync group.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily

**Brave Version:** 
1.9 (19.03.09.01)

**Device details:** 
iPad 5th Gen

**Website problems only:**
- did you check with Brave Shields down? n/a
- did you check in Safari/Firefox (WkWebView-based browsers)?  n/a

### Additional Information 
If you tap on OK and try again, you will get loading spinner indefinitely. Close and reopen Brave results in https://github.com/brave/brave-ios/issues/845#issuecomment-473400743

Also, if I skip deleting the bookmark folder (step 3), sync chain creates properly.

**Comment by iccub** [comment]
Should be fixed by https://github.com/brave/brave-ios/pull/970

I tested it using the str above

**Comment by iccub** [comment]
Closing via https://github.com/brave/brave-ios/pull/970, please retest it once new beta build is ready
