### ISSUE TITLE
Maximizing video, minimizing brave causes number pad to show with video.

### ISSUE THREAD

**Issue by gortok** [brave/brave-ios#979]
### Description: 

With a maximized video playing from YouTube, minimizing and bringing brave up via its icon causes the video to show along with the number pad.
### Steps to Reproduce 
  1.open video on YouTube. Maximize it.
  2.use lower bar swipe up gesture to minimize brave.
  3.use the icon to get back to brave, note similar outcome to screenshots below.

**Actual result:**

![CDBF991C-F110-465C-B343-41F225DCE245](https://user-images.githubusercontent.com/699891/54482331-25acb000-4818-11e9-9231-9d102e016cbd.png)
![39638B93-97FA-47EF-9B3E-45D501F69CC9](https://user-images.githubusercontent.com/699891/54482332-25acb000-4818-11e9-93f6-912e7987087a.png)
![6ED480E5-67F7-4970-8156-1F248091D19B](https://user-images.githubusercontent.com/699891/54482333-25acb000-4818-11e9-85f5-03e3c31b07d9.png)

**Expected result:**

Expect pin window to hide video.
**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
v1.8

**Device details:** 
iPhone 10, iOS 12.1.4

### Additional Information

**Comment by srirambv** [comment]
Reproduced the issue. Unable to unlock browser because video overlay is blocking the passcode screen and showing only the number pad.

**Comment by kylehickinson** [comment]
Good place to start looking: This is likely due to the fact that a video player is a new `UIWindow`, and is likely placed on top of passcode entry `UIWindow`

**Comment by jhreis** [comment]
Yeah, this has security concerns too then. 🤕

**Comment by tildelowengrimm** [comment]
This passcode lock feature is becoming harder and harder to maintain, and it's not even a particularly effective security boundary. We should probably drop the whole passcode lock feature.

**Comment by srirambv** [comment]
* Verification passed on iPhone 7+ running 1.9.2(19.04.24.20)

**Comment by GeetaSarvadnya** [comment]
* Verification passed on iPhone 8 running 1.9.2(19.5.8.23)
* Verification passed on iPhone SE running 1.9.2(19.5.8.23)
* Verification passed on `iPad Mini 4 using iOS 12.2 running 1.9.2(19.5.8.23)`
* Verification passed on `iPhone 6s+ using iOS 12.2 running 1.9.2(19.5.8.23)`
* Verification passed on iPad pro running 1.9.2(19.5.8.23). Verified on Twitch as YT doesn't go full screen on iPad
