### ISSUE TITLE
Intermittently bringing brave up from being minimized causes the pin window to show with no number pad.

### ISSUE THREAD

**Issue by gortok** [brave/brave-ios#980]
### Description: 

Hard to reproduce but regularly brave will come up from being minimized with no numberpad showing on the passcode screen.
### Steps to Reproduce 
  1. Use brave.
  2. Minimize it.
  3. Bring it back up via its icon, note that no number pad shows. Only way to correct is force quit brave.

**Actual result:** 
![1410A816-4412-4A85-A73E-510D12722DB1](https://user-images.githubusercontent.com/699891/54482393-488b9400-4819-11e9-8eb2-50fd939b5240.png)

**Expected result:**

Expect number pad to come up when passcode window comes up.
**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Intermittent. Can not reliably reproduce but it does happen regularly.

**Brave Version:** 
1.8

**Device details:** 
iPhone 12.1.4

**Comment by kjozwiak** [comment]
@jhreis should this be removed from the `1.10` milestone or are we planning on fixing this? I don't see a release associated with this one on `ZenHub` either.

**Comment by jhreis** [comment]
Related: https://github.com/brave/brave-ios/issues/1122

**Comment by jhreis** [comment]
Regardless of the solution here, we should also make the keyboard present on clicking on the UI somewhere, see #1122 for related notes.

**Comment by srirambv** [comment]
Verification passed on iPhone XR with iOS 13.1 beta 2 running 1.12(19.09.05.20)
* Verified pin window show up with keyboard when the app is launched for the first time
* Verified pin window show up with keyboard when the app is launched from background
* Verified pin window show up with keyboard when the device is unlocked with Brave as the active app
* Verified pin window show up with keyboard when app swipe to bring Brave app as active

Verification **PASSED** on `iPad Air 3rd Generation iOS 13.1` running `1.12 (19.09.11.15)`:

* Verified pin window show up with keyboard when the app is launched for the first time
* Verified pin window show up with keyboard when the app is launched from background
* Verified pin window show up with keyboard when the device is unlocked with Brave as the active app
* Verified pin window show up with keyboard when app swipe to bring Brave app as active

Verification **PASSED** on `iPhone 6s+` using `iOS 12.4.1` running `1.12 (19.09.13.06)`:

* Verified pin window show up with keyboard when the app is launched for the first time
* Verified pin window show up with keyboard when the app is launched from background
* Verified pin window show up with keyboard when the device is unlocked with Brave as the active app
* Verified pin window show up with keyboard when app swipe to bring Brave app as active
