### ISSUE TITLE
Rate Brave deeplink URL is incorrect- follow up to 856

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#989]
### Description: 
Follow up from https://github.com/brave/brave-ios/issues/856#issuecomment-472961020

When I tap on 'Rate Brave', Safari opens and then I get a popup that says 'Open in "App Store".

### Steps to Reproduce 
  1. Navigate to Settings
  2. Tap on Rate Brave

**Actual result:** 
Get a popup that says 'Open in "App Store".
![856comment](https://user-images.githubusercontent.com/28145373/54564756-f8d8d400-49a2-11e9-8192-7462d9e034c2.jpeg)

**Expected result:**
App Store opens

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
easily

**Brave Version:** 
1.9(19.3.9.1)

**Device details:** 
all

**Website problems only:**
- did you check with Brave Shields down? n/a
- did you check in Safari/Firefox (WkWebView-based browsers)?  n/a

### Additional Information 
cc @Liunkae @srirambv

**Comment by btlechowski** [comment]
Reproduced on 1.9 (19.3.9.1) on iPhone SE

**Comment by cndouglas** [comment]
I updated the commit message to mention this issue.

**Comment by LaurenWags** [comment]
* Verified passed with 1.9 (19.03.25.21)

![IMG_0287](https://user-images.githubusercontent.com/28145373/55001731-a3588480-4fab-11e9-887b-b58c2610752f.PNG)


* Verification passed on iPhone 7+ running 1.9(19.3.25.21), clicking automatically opens appstore and switches to add review comments page
*  Verification passed on iPhone 8 running 1.9(19.3.25.21).  Click on Rate Brave opens appstore and switches to add review comments page

![Rate brave popup](https://user-images.githubusercontent.com/38657976/55017475-ce2bf280-5016-11e9-8523-d82bd9d2e347.png)

* Verification **PASSED** with `1.9 (19.03.25.21)` on `iPad Mini 4` using the above STR.

* Verification passed on iPhone 6 running 1.9(19.3.25.21), clicking automatically opened appstore and switches to add review comments page

* Verification passed on iPhone 6 running 1.9(19.3.25.21) using STR from the description
