### ISSUE TITLE
Bookmark with empty title from desktop doesn't update on iOS

### ISSUE THREAD

**Issue by iccub** [brave/brave-ios#992]
### Steps to Reproduce 
  1. Pair iOS device and desktop
  2. Add a bookmark on desktop
  3. Edit the bookmark to have empty title, so only favicon is visible

**Actual result:** 
Title doesn't get updated on iOS

**Expected result:**
Title should update on iOS

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by LaurenWags** [comment]
@iccub I'm a little unclear on the expected result here. It looks like the title did update when viewed in Edit Mode:
![syncedbkmk-editmode](https://user-images.githubusercontent.com/28145373/55003427-c89ac200-4fae-11e9-80c6-00a030b63e6a.png)

But when viewing the bookmark in regular (non-edit) mode, I see the URL. Is this expected? 
![syncedbookmark](https://user-images.githubusercontent.com/28145373/55003463-da7c6500-4fae-11e9-9c0b-1e0f6b3ccc31.png)

**Comment by iccub** [comment]
@LaurenWags  On bookmark panel we show `displayTitle` which means if no title is provided, bookmark's url is presented.
In edit mode you can of course edit both name and the url.

**Comment by LaurenWags** [comment]
* Verified passed with 1.9 (19.03.25.21) on iPad 5th Gen
* Verified passed with 1.9 (19.03.25.21) on iPhone 8
* Verification passed on iPhone 6/7 and iPad Pro running 1.9(19.3.25.21)
* Verification passed on iPhone SE running 1.9 (19.3.25.21)
* Verification **PASSED** with `1.9 (19.3.27.19)` on `iPad Mini 4` using the above STR.
